### ISSUE TITLE
Can't reset password for account created with external SSO

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#1001]
Hi. Someone was authenticated recently with LDAP for our application and a new account was created. When attempting to reset the user's password, we were alerted that reseting passwords for LDAP users is not possible.

**Comment by hexylena** [comment]
Yep. Most people who use LDAP are using it through some existing infrastructure where a password reset functionality is already in place. Perhaps we should provide administrators with the ability to redirect to a URL for this case? Would that solve your issue?

**Comment by MatthewRalston** [comment]
Well, in that case would the password be there standard password for our SSO service? I don't think we were passing that through with the headers. It's worth noting that we did not activate the "auth_config_file" but instead passed the authentication through the headers.

**Comment by natefoo** [comment]
If you are using `use_remote_user`, there should not be a password set for the user, and the `external` column in the `galaxy_user` table is designed to prevent these accounts from ever being logged in to if you disable `use_remote_user`.

**Comment by MatthewRalston** [comment]
Okay. It sounds like this is a "feature" then. We are still working on an Apache config to address #972 so we can re-enable our SSO.
