### ISSUE TITLE
Augment Workflow Model for Registeries

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#10016]
I was needing to add workflow authors to the workflow model for Dockstore (the current user is a fine guess I suppose, but it should be a persistent and user editable field IMO).

At the BCC 2020 IWC BoF though people working workflowhub.eu were willing to discuss minimum workflow metadata standards with me and so we went through the work they had done and also isolated "license" (as a URI coming from https://spdx.org/licenses/ presumably) and version information as additional data we would like to capture and make user-specifiable in the UI.

**Comment by nsoranzo** [comment]
During the BCC 2020 Collaboration Fest we worked on a list of possible licenses to use for software and/or content (both can apply to workflows I think): https://docs.google.com/document/d/16vnRtDjrx5eHSl4jXs2vMaDTI6luyyLzU6xMvRHsnbI/edit?usp=sharing

**Comment by mvdbeek** [comment]
I'd say this is done with https://github.com/galaxyproject/galaxy/pull/10408
