### ISSUE TITLE
Workflow schedulers hang after database connection loss

### ISSUE THREAD

**Issue by selten** [galaxyproject/galaxy#10038]
I've noticed that if the workflow schedulers have even a momentary loss of connection to the database, they will no longer schedule workflows until either the workflow scheduler is killed or Galaxy has been restarted. 
This in contrast to the Galaxy UI and job handlers which seem to be able to recover by themselves from such an event.

**Comment by mvdbeek** [comment]
We recently fixed that ... I think 20.09 shouldn't have that problem anymore.
