### ISSUE TITLE
History dataset separators disappeared from 20.05 user interface

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#10066]
Without a line separator between datasets in the history it is really hard to know, especially for hidden/deleted datasets, to tell where information about one dataset begins or ends.

![Screenshot from 2020-08-05 12-49-56](https://user-images.githubusercontent.com/4742081/89404531-71683e00-d71a-11ea-84eb-f3524bdcc6ac.png)

**Comment by dannon** [comment]
Fixed in 10675.
