### ISSUE TITLE
Login broken in :dev for require_loginTrue

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1007]
@dannon @guerler 
![login-error](https://cloud.githubusercontent.com/assets/458683/10837099/8a8b1014-7e83-11e5-9ad0-38a72306317b.png)

**Comment by nsoranzo** [comment]
It seems `trans.request.referer` is None, may be fixed by using `trans.request.referer or ''`, but I'm not sure if `__get_redirect_url()` should be called with an empty string. This should be checked throughout this file.

**Comment by guerler** [comment]
Yes, I agree. This seems to be the issue. I wonder why this issue occurred just recently tho.

**Comment by hexylena** [comment]
Agreed, since it was working just the other day when you fixed it.

**Comment by dannon** [comment]
Yep, that's exactly what I was looking for too.  @nsoranzo's fix seems reasonable, but I want to know why this broke first.

**Comment by carlfeberhard** [comment]
This is fixed, right?
