### ISSUE TITLE
Add "tgz" to datatypes_conf.xml.sample

### ISSUE THREAD

**Issue by fubar2** [galaxyproject/galaxy#10079]
There's "grd.tgz" but no "tgz" datatypes in the default datatypes_conf.xml.sample and I was wondering if there's a particular reason why it shouldn't be there for tools that generate gzipped tar files?

Of course, it's easy enough to add locally, but the now resurrected Tool Factory needs it since it puts toolshed ready tgz archives in a user's history and adding this makes it work and may not break much.
```
  <datatype extension="tgz" type="galaxy.datatypes.binary:Binary" subclass="true" mimetype="multipart/x-gzip" display_in_upload="true" />
```
Yes, the toolfactory is back - it even seems to pass planemo test and the planemo tool_factory command now works properly with some small changes in my fork.

**Comment by mvdbeek** [comment]
Done in https://github.com/galaxyproject/galaxy/pull/10080, thanks again @fubar2!
