### ISSUE TITLE
Failed Invocation of workflow

### ISSUE THREAD

**Issue by subinamehta** [galaxyproject/galaxy#10085]
Hello,

I am trying to invoke a workflow on usegalaxyEU server and it reports that Invocation scheduling failed. Half of the tools involved in the workflow runs and the rest doesn't queue.

<img width="767" alt="Screen Shot 2020-08-10 at 12 50 02 PM" src="https://user-images.githubusercontent.com/27242621/89808348-0480e980-db08-11ea-854f-651e773165cb.png">

here is the workflow :https://usegalaxy.eu/u/subina/w/metatranscriptomics-full-workflow---gtn-imported-from-uploaded-file-2
History: https://usegalaxy.eu/u/subina/h/imported-t3ametatranscriptomicsworkflow .

It will be great if we can troubleshoot this issue!

**Comment by bgruening** [comment]
The stack trace is here: https://gist.github.com/bgruening/f536129e7c15c6df5ec4cbfe4b277ab3
