### ISSUE TITLE
Masthead menus do not disappear unless menu title clicked 

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#10092]
It seems the masthead menu items became a toggle where when one clicks on a menu title, the menu opens but to hide the menu, you have to click on the menu title again as opposed to a random place on the page. This does not seem like feature to me?

![image](https://user-images.githubusercontent.com/338642/89946190-8d735000-dbf0-11ea-9a4e-d23215fb10e9.png)

**Comment by OlegZharkov** [comment]
Thanks a lot for noticing it. It must have been fixed a while ago in https://github.com/galaxyproject/galaxy/pull/9789

I will take a look

**Comment by afgane** [comment]
Thanks for a quick fix.
