### ISSUE TITLE
Toolboxes of recommended tools not opening in workflow editor

### ISSUE THREAD

**Issue by anuprulez** [galaxyproject/galaxy#10095]
Toolboxes of recommended tools do not open in the workflow editor after clicking on the recommended tools in the popover. This issue is present in the [dev branch](https://github.com/galaxyproject/galaxy/tree/dev). The currently deployed codebase `release_20.05` on the EU server does not have this issue.

![Screenshot from 2020-08-12 18-07-35](https://user-images.githubusercontent.com/3022518/90016086-1e1c5f80-dcc7-11ea-8260-076ce7680d36.png)

**Comment by dannon** [comment]
Fixed in #10097

**Comment by anuprulez** [comment]
@dannon  thanks!
