### ISSUE TITLE
Short Term Performance Testing Plan

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#10105]
We had an informal discussion around performance testing over the PSU happy hour yesterday trying to generate ideas about how to do high impact performance testing of Galaxy. There wasn't a lot of real clear answers or optimism around catching performance issues ahead of time.

There was some general consensus that probably more people working on the dev branch of Galaxy and (to that end) more people using test.galaxyproject.org will likely result in us catching more issues ahead of time than performance testing (at least in the middle term) - we thought lifting test quotas, synchronizing the tool panel, and doing aggressive cleanup of data would be a way to accomplish that but that was blocked for now on using containers across usegalaxy.org and test.galaxyproject.org.

Around augmenting the actual CI processes around performance testing though - we thought the biggest gain with the littlest risk would be... 
- To use Github Actions (instead of Jenkins). Jenkins could allow us to control the way jobs run more reproducibly but we we're concern about the admin overhead. @assuntad23 did offer to take over some of the Jenkins maintenance activities though. 
- Augment the existing API tests with metrics collection instead of writing new tests. We already have some infrastructure in place and this could provide benefit in certain scenarios without writing new tests. The problem of instrumenting Galaxy and publishing reports for PRs would provide immediate benefit for PR review without requiring new tests and would be in place if we wanted to write specific performance tests that would block regression-inducing  builds in the future. 
- Some infrastructure for A/B testing individual PRs (target branch vs. PR branch) on the same machine / within the same CI run would allow us to control some variables related to the test environment and changes over time while also prevent us from having to maintain a historical record of the performance data (and have to reason about it in some normalized way). That infrastructure for A/B testing could have other applications also - such as comparing UI differences after a PR or workflow output differences.

So I'm thinking I'll try to make a little incremental progress on these points rather than deliver a risky performance suite as I had hoped this quarter. NFS upgrades and performance improvements from @mvdbeek have largely blunted the immediacy of this need luckily anyway. And we have many other plans we are certain will improve problematic performance issues (writing history exports to galaxy.files plugins, adding a MQ for tool submissions, etc..).

**Comment by OlegZharkov** [comment]
> * To use Github Actions (instead of Jenkins). Jenkins could allow us to control the way jobs run more reproducibly but we we're concern about the admin overhead. @assuntad23 did offer to take over some of the Jenkins maintenance activities though.


That's a great idea :fireworks::fireworks::fireworks:
Also would be great to run all those selenium tests simultaneously, one github-actions job per test. (I can take a look on that, if needed)
