### ISSUE TITLE
Workflow node insertion via recommendations has undefined name

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#10101]
Looks like properties aren't bubbled up through events correctly; taking a look now.

![image](https://user-images.githubusercontent.com/155398/90139084-e1437d80-dd45-11ea-8200-69925a704b39.png)

**Comment by dannon** [comment]
@anuprulez Noticed this too and is working on a fix.

**Comment by anuprulez** [comment]
@dannon if you allow, I can open a PR for this fix?

**Comment by dannon** [comment]
@anuprulez Absolutely, please do!
