### ISSUE TITLE
Shared status column dropped from new workflow list view

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#10114]
In the old (backbone-based?) user-specific workflow list view, there used to be a column indicating whether a workflow was shared or not. Apparently, this column was dropped during the rewrite of the page so a user currently has a very hard time identifying/unsharing their shared workflows.

**Comment by wm75** [comment]
In addition, there is currently no way to sort workflows on the *Bookmark* column.

**Comment by OlegZharkov** [comment]
> In the old (backbone-based?) user-specific workflow list view, there used to be a column indicating whether a workflow was shared or not. Apparently, this column was dropped during the rewrite of the page so a user currently has a very hard time identifying/unsharing their shared workflows.

Hm, do you mean `published`? I can include it there, if you want. I don't see any problem, why not



> In addition, there is currently no way to sort workflows on the _Bookmark_ column.

This might be trickier.... I should take a closer look...
