### ISSUE TITLE
merge columns tool does not work when used directly from an input in a workflow, works standalone

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/galaxy#10113]
example workflow:
https://usegalaxy.org/workflow/sharing?id=6871c64dc815582d

example history:
https://usegalaxy.org/u/bradlanghorst/h/test-merge-in-workflow 

the  output should contain another column (concatenating columns 1-3) but the tool seems to lose the column numbers specified in the workflow.

running the tool outside of the workflow does work fine

**Comment by bwlang** [comment]
maybe helpful:
if you add the cut columns tool between the input and the merge tool (basically a useless cat), the merge tool executes with the correct arguments.
maybe related to the merge tool's dynamic list of columns? 
If so - I suspect other tools might also be affected.

**Comment by guerler** [comment]
Thank you for reporting this. Can you the fix the Workflow URL. I will import it to reproduce the error.

**Comment by guerler** [comment]
Thank you for reporting this. Can you the fix the Workflow URL. I will import it to reproduce the error.

I created a workflow containing the merge tool: https://usegalaxy.org/u/guerler/w/merge-tool-with-1-input, and I can reproduce this issue. It seems to occur for implicitly converted datasets. If you convert the `bed` file manually to a `tabular` file the `column` metadata of the dataset is populated correctly.

**Comment by bwlang** [comment]
seem like you already have it ... but just in case not - here's a better url
 https://usegalaxy.org/u/bradlanghorst/w/test-merge

**Comment by mvdbeek** [comment]
Just tried the example again, and it's working. There were a lot of fixes in the 21.01 cycle, not sure which one fixed it.
