### ISSUE TITLE
Job Resource Params not working anymore

### ISSUE THREAD

**Issue by code4dna** [galaxyproject/galaxy#10132]
We had the job_resource_params_conf.xml configured on version 20.01 and it was working great. However, we noticed it stopped working and only loads the defaults (cores and walltime) instead of switching based on the resources selected in the tools. The only change in the configuration I noticed is that slurm-drmaa was upgraded from 1.0.7 to 1.1.0 since our Slurm version was updated to 19.05. (although I'm not sure if 1.0.7 was the previous version). Any way to check if this update affected the job resource parameters selection?

**Comment by charmichaeld** [comment]
I got it figured out. I used to could have `<destinations default="1day1core">` as the default destination and the job resource parameters selection worked for every tool but after updating slurm-drmaa, the following does not work anymore:
```
<destinations default="1day1core">
    <destination id="local" runner="local"/>
    <destination id="1day1core" runner="slurm">
        <param id="nativeSpecification">--time=24:00:00 --nodes=1 --ntasks-per-node=1 --cpus-per-task=1 --mem=2000</param>
    </destination>
    <destination id="1day2cores" runner="slurm">
        <param id="nativeSpecification">--time=24:00:00 --nodes=1 --ntasks-per-node=1 --cpus-per-task=2 --mem=4000</param>
    </destination>
    <destination id="dynamic_cores_time" runner="dynamic">
        <param id="type">python</param>
        <param id="function">dynamic_cores_time</param>
    </destination>
</destinations>
```

Now I've changed the default destination to the dynamic runner and now the job resource parameter selection is working.
```
<destinations default="dynamic_cores_time">
```

**Comment by code4dna** [comment]
I got it figured out. I used to could have <destinations default="1day1core"> as the default destination and the job resource parameters selection worked for every tool but after updating slurm-drmaa, the following does not work anymore:

```
<destinations default="1day1core">
    <destination id="local" runner="local"/>
    <destination id="1day1core" runner="slurm">
        <param id="nativeSpecification">--time=24:00:00 --nodes=1 --ntasks-per-node=1 --cpus-per-task=1 --mem=2000</param>
    </destination>
    <destination id="1day2cores" runner="slurm">
        <param id="nativeSpecification">--time=24:00:00 --nodes=1 --ntasks-per-node=1 --cpus-per-task=2 --mem=4000</param>
    </destination>
    <destination id="dynamic_cores_time" runner="dynamic">
        <param id="type">python</param>
        <param id="function">dynamic_cores_time</param>
    </destination>
</destinations>
```

Now I've changed the default destination to the dynamic runner and now the job resource parameter selection is working.

`<destinations default="dynamic_cores_time">`
