### ISSUE TITLE
Toolshed js ?

### ISSUE THREAD

**Issue by fubar2** [galaxyproject/galaxy#10142]
Executive summary: Running a local toolshed in "out of the box" mode seems broken in dev at present. Quick and dirty fix:
make static/scripts/bundled and soft link static/dist/* static/scripts/bundled/ works - in case anyone needs it.

Longer version:

Looks like default toolshed base javascript path needs updating.

Main toolshed seems to fill page script src templates like 
```
<script src="/static/scripts/bundled/libs.chunk.js?v=1598068810" type="text/javascript"></script>
<script src="/static/scripts/bundled/base.chunk.js?v=1598068810" type="text/javascript"></script>
```
and it works :)

A recent dev clone produces the same - but those paths do not exist after building the client - after all, galaxy currently uses
```
<script src="/static/dist/libs.chunk.js?v=1597905027" type="text/javascript"></script>
<script src="/static/dist/base.chunk.js?v=1597905027" type="text/javascript"></script>
<script src="/static/dist/analysis.bundled.js?v=1597905027" type="text/javascript"></script>
```

Am I missing something or could this do with some competent adjustment?

**Comment by dannon** [comment]
@fubar2 Cool!  The fix has been merged into 20.05, and it'll be pulled forward to dev in #10151
