### ISSUE TITLE
<repeat> default="1" not working

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#1016]
Running with `planemo serve` `default="1"` does not show the param. `min="1"` does.

```
<repeat name="repeat_test" default="1" title="Test">
  <param name="RP" type="text" value="" label="RP"/>
</repeat>
```

**Comment by jmchilton** [comment]
Is this a bug, if so is this documented somewhere or is there an old example tool that this worked with? Or is this a feature request?

**Comment by scholtalbers** [comment]
I suspect a bug, see tool conf docs: https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax#A.3Crepeat.3E_tag_set where it is a valid option. I have not yet looked for a tool that uses it as well.

**Comment by hexylena** [comment]
I believe I remember this worked at one point...

**Comment by hexylena** [comment]
ping @guerler
