### ISSUE TITLE
HTTP 500 Error when installing tools from Toolshed

### ISSUE THREAD

**Issue by PHemarajata** [galaxyproject/galaxy#10193]
Hi, I have a local instance of 20.05. Last month I was able to install new tools, but today when I tried at install a new tool I ran into an error.

raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://toolshed.g2.bx.psu.edu/api/repositories/get_repository_revision_install_info?name=deeptools_plot_pca&owner=bgruening&changeset_revision=69264da0ce77

Can anyone please help? Thank you!

**Comment by mvdbeek** [comment]
That was a temproary issue on the toolshed and should be resolved now.
