### ISSUE TITLE
Galaxy 20.05 Filter1 fails on previously working input

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10205]
Upgrading to Galaxy 20.05 from 19.09 has the following error occur for the Filter1 tool within a workflow:

```
Illegal/invalid in condition 'c3=='genomic_island' and 'Parent=' not in c9'
```

It isn't clear what is invalid about that condition.

**Comment by bernt-matthias** [comment]
Quotes look odd, isn't it?

**Comment by innovate-invent** [comment]
The outer quotes are from the error formatting, they do not exist in the tool input

**Comment by bernt-matthias** [comment]
My guess is that the `=` in `'Parent='` confuses the parser. I guess its a good idea to extent https://github.com/galaxyproject/galaxy/blob/74611ce7c6dba86161f53d19a7256bbaf139a84b/tools/stats/filtering.py#L58 by some error messages

Do you have a history somewhere that you could share?

**Comment by innovate-invent** [comment]
I just go the same error for a different rule: `Illegal/invalid in condition 'c3=='genomic_island''`

I'll see if I can PM you a link to the history on gitter

**Comment by bernt-matthias** [comment]
Tested the tool on a local Galaxy 20.05 on the data. Works like a charm. So I'm afraid, that I can't help at the moment.

Do you have the chance to run the `tool_script.sh` or its contents in the exact same environment as the job? Then you could debug this.

**Comment by mvdbeek** [comment]
Any chance that's fixed with https://github.com/galaxyproject/galaxy/pull/10266 ?

**Comment by nsoranzo** [comment]
Pretty sure #10266 (and its backport #10274) fix this, but feel free to reopen if not!
