### ISSUE TITLE
20.05: Change output datatype ignored in workflow editor

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10228]
![image](https://user-images.githubusercontent.com/1768820/93246655-f1ce8580-f741-11ea-80f3-2aa0ff13b2d5.png)

The output type is not changed in the tool node output and tools are not able to connect.

Galaxy 20.05

**Comment by mvdbeek** [comment]
I don't see this on usegalaxy.org or locally. Can you say a bit more on how to reproduce this ?

**Comment by innovate-invent** [comment]
You are right, it appears to not affect new workflows. All of my imported ones from 19.09 are having problems.

**Comment by dannon** [comment]
Should be fixed in #10237

**Comment by innovate-invent** [comment]
Thanks!

**Comment by innovate-invent** [comment]
This issue is still present in 20.09

**Comment by mvdbeek** [comment]
Please provide more details.

**Comment by mvdbeek** [comment]
I just tried the basic case and it works fine.

**Comment by innovate-invent** [comment]
I am not sure if there was a regression, but I am finding that the changed output type is not reflected in the workflow output:
![image](https://user-images.githubusercontent.com/1768820/184734794-5743fdf6-9d08-4b2b-92e5-a4fb81cf7887.png)

I have the example workflow above embedded as a subworkflow and I am not able to make connections to tools expecting a newick file despite when I run the workflow it outputs a newick file.

This applies to 21.05 and 22.01.

**Comment by innovate-invent** [comment]
Continued at #14463
