### ISSUE TITLE
Collection element datasets not hidden when copied for "listpaired". Elements are hidden for "paired".

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#10229]
Example`from history`: https://usegalaxy.org/u/jen-galaxyproject/h/dna-ngs-test-datasets-variant-tuto
Example `to history`: https://usegalaxy.org/u/jen-galaxyproject/h/test-history-copied-data

ping @jmchilton

**Comment by jmchilton** [comment]
@assuntad23 and I are discussing this and #10230 - I just wanted to verify this is a problem for copying whole histories? These histories weren't produced by copying individual datasets right?

**Comment by jennaj** [comment]
The problem seems to be resolved now in 20.09. This was from copying datasets -- not the entire history but I just checked both and are working Ok.

Datasets added to collections still do lose their tags once added to a collection. That is the other issue. And whether that is on purpose or not -- I don't know. Personally I prefer if the tags propagated if start with a hash "#"

**Comment by jennaj** [comment]
Wrong! Still a problem. How to reproduce:

Start here: https://usegalaxy.org/u/jen-galaxyproject/h/dna-ngs-test-datasets-variant-tuto

Try copying dataset 6 (listpaired collection) into a new history -- the elements are not hidden. https://usegalaxy.org/u/jen-galaxyproject/h/test-copy-listpaired

Go back to the original history and try copying dataset 9 or 15 -- the collection elements are hidden

**Comment by assuntad23** [comment]
This is only a problem with list of pairs created before 20.09. Any collections created before that may continue to have this issue.

**Comment by mvdbeek** [comment]
Are you sure about that ? What fixed it ? If I follow @jennaj's instructions I still see that the HDAs are unhidden.

**Comment by jennaj** [comment]
Well, we thought was fixed .. but the "hide original elements" was a factor in one of the tests. Couldn't reproduce after, but also didn't fully start over from scratch. 

My original test didn't hide the original elements. And if that is reproducible by you, then still open!

**Comment by assuntad23** [comment]
fixed in #10508
