### ISSUE TITLE
Collection element datasets lose their tags when copied for "listpaired" + "paired"

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#10230]
Example `from history`: https://usegalaxy.org/u/jen-galaxyproject/h/dna-ngs-test-datasets-variant-tuto
Example `to history`: https://usegalaxy.org/u/jen-galaxyproject/h/test-history-copied-data

ping @jmchilton

**Comment by jennaj** [comment]
Related: https://github.com/galaxyproject/galaxy/issues/10229

**Comment by assuntad23** [comment]
Fixed in #10761
