### ISSUE TITLE
Workflow editor tool search breaks on search

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#10236]
May or may not be related to empty sections or sections without ids ?
In either case if this happens all further searches break:
<img width="772" alt="Screenshot 2020-09-17 at 12 31 25" src="https://user-images.githubusercontent.com/6804901/93459496-1497a000-f8e2-11ea-9391-cef728665ab5.png">

This is on 20.05

**Comment by jmchilton** [comment]
I've tried a bunch of different things and I can't reproduce it - empty sections no longer appear though. So can we call this issue fixed by: https://github.com/galaxyproject/galaxy/pull/10363.

**Comment by mvdbeek** [comment]
Likely not a problem anymore
