### ISSUE TITLE
Workflow Invocation list performance issues

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#10249]
The Workflow Invocation list loads pretty slow after a couple hundred invocations. Suggesting revising it for lazy loading.

**Comment by mvdbeek** [comment]
We're loading up the full invocation details on initial load, that is unnecessary. But we should also allow filter, search pagination etc. I would like to work on this in the next release.

**Comment by guerler** [comment]
This seems to have been mostly resolved by now right?
