### ISSUE TITLE
Improve error handling in new simplified run workflow form

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#10268]
The new run workflow form does currently not highlight errors i.e. missing datasets. It would be nice to highlight those.

**Comment by guerler** [comment]
Additional note, it seems that when there is a version conflict with a certain step, the workflow run form appears but does not submit the job. Observed on dev with `splitfasta` tool version.

**Comment by mvdbeek** [comment]
That's fixed with https://github.com/galaxyproject/galaxy/pull/12124
