### ISSUE TITLE
ToolShed: we can't move hgweb.config file 

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#10271]
I tried to move `hgweb.config` from the root directory of Galaxy to the `config` directory.
I tried to change the ToolShed config in `config/tool_shed.yml`:
```
  # Where the hgweb.config file is stored. The default is the Galaxy
  # installation directory.
  hgweb_config_dir: config
```
But it breaks the build of the whoosh index (and I was then unable to install a tool from our ToolShed as they were not found anymore by the api `toolshed/api/repositories`).

All the paths are fine:
```
python scripts/tool_shed/build_ts_whoosh_index.py -c /softs/bioinfo/galaxy-dev/config/tool_shed.yml --config-section tool_shed -d
Full options:
config_file: /softs/bioinfo/galaxy-dev/config/tool_shed.yml
file_path: /softs/bioinfo/galaxy-dev/database/local_toolshed
hgweb_config_dir: /softs/bioinfo/galaxy-dev/config
debug: True
dburi: postgresql://localtools........
config_section: tool_shed
whoosh_index_dir: database/toolshed_whoosh_indexes
```
But the script will try to look for files in a wrong path (there is an extra `config` in it, as `lib/tool_shed/util/shed_index.py` use `hgweb_config_dir` in the join ):
`mercurial.error.RepoError: b'repository /softs/bioinfo/galaxy-dev/config/database/local_toolshed/000/repo_4 not found'`
https://github.com/galaxyproject/galaxy/blob/53217ea908ea6d2410270287a0abb2bea1416edc/lib/tool_shed/util/shed_index.py#L119

**Comment by mvdbeek** [comment]
This is the correct behavior, the entries in hgweb.config have to either be absolute or relative to hgweb_config_dir.
The tool shed should be writing absolute paths in hgweb.config, at least since 20.05. if these are still relative because you haven't added any repositories on 20.05 you'll have to set absolute paths in hgweb.config
