### ISSUE TITLE
Purged datasets listed as available for use in visualization drop-down selection

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#10278]
<img width="1381" alt="Screen Shot 2020-09-23 at 4 05 36 PM" src="https://user-images.githubusercontent.com/40246333/94082998-07cded00-fdb7-11ea-9b7a-a60f901e8b19.png">

All datasets that have the appropriate datatype are listed in the available datasets for the visualization drop-down selectors, whether or not they have been hidden or purged

**Comment by OlegZharkov** [comment]
I will work on it
