### ISSUE TITLE
Error when installed JAVA

### ISSUE THREAD

**Issue by H1207953831** [galaxyproject/galaxy#10280]
the installation error will occur if the Java language is installed while the galaxy is being built locally.

**Comment by bgruening** [comment]
@H1207953831 can you please give us the error report? Galaxy is not installing JAVA, so there needs to be another error.

**Comment by H1207953831** [comment]
It could be until I install Galaxy platform on another computer, because I still need to use this platform built for scientific research，so it will take a while.

**Comment by mvdbeek** [comment]
You may want to ask your question on help.galaxyproject.org or https://gitter.im/galaxyproject/Lobby.
