### ISSUE TITLE
Tool box labels do not keep indentation when wrapped.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#10297]
![image](https://user-images.githubusercontent.com/458683/94250692-d7ef2880-ff21-11ea-974b-20990ea9e6db.png)

the tool panel sections do fine, just the labels.

**Comment by dannon** [comment]
Just occurred to me that this is an older revision screenshot, and I think I (accidentally) fixed this bug already when working on some stuff.  The following should be in 20.09:

![image](https://user-images.githubusercontent.com/155398/94758024-05950100-036a-11eb-9c7f-932005a4468b.png)


I'll take a look at a 20.05 quickfix though.

**Comment by hexylena** [comment]
Thanks @dannon!
