### ISSUE TITLE
The interactive environment menu bar needs to be fixed. 

### ISSUE THREAD

**Issue by jaidevjoshi83** [galaxyproject/galaxy#10291]
The appearance of The interactive environment menu bar is not proper.  It's showing up the double menu bar. 

<img width="1678" alt="Screen Shot 2020-09-24 at 4 01 16 PM" src="https://user-images.githubusercontent.com/17113046/94195193-b38f3f80-fe80-11ea-920f-c976a67ac6f3.png">

**Comment by dannon** [comment]
Looks like the GIE Launcher page needs to detect an iframe and not load the masthead; I thought this was implemented across the board for embedded subpages like this, but we may have missed one.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/10329, thanks for the report @jaidevjoshi83!
