### ISSUE TITLE
Quota meter text v-center off

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#10290]
![image](https://user-images.githubusercontent.com/155398/94188826-ebde5000-fe77-11ea-8555-aac4ddadf262.png)

Thanks for noticing this @luke-c-sargent!

**Comment by jmchilton** [comment]
I checked a 20.05 server and this wasn't an issue - I think it is a regression in 20.09. I noticed this too when I was playing with usage and quota stuff in #10221.

The difference seems to be a line height:

<img width="346" alt="Screen Shot 2020-09-25 at 11 27 26 AM" src="https://user-images.githubusercontent.com/216771/94285807-2f8d9400-ff22-11ea-9484-59c88041a607.png">

If I uncheck that in the inspector it is fixed.
