### ISSUE TITLE
Failed to install Fastuniq.

### ISSUE THREAD

**Issue by H1207953831** [galaxyproject/galaxy#10303]
I used the administrator method to install FASTUNIQ, but the installation failed. So I would like to ask whether the platform is already incompatible with FASTUNIQ.
I used another tool named Deduplicate FASTQ files. there also an error.the error message is:galaxy/galaxy_20.05/database/shed_tools/toolshed.g2.bx.psu.edu/repos/mvdbeek/dedup_hash/f33e9e6a6c88/dedup_hash/dedup_hash/dedup_hash.py:74: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  cur_hash = self.hash_modul

**Comment by mvdbeek** [comment]
Can you please report this at help.galaxyproject.org.

**Comment by H1207953831** [comment]
Since FastUniq has stopped updates, I found another solution，called Redup
