### ISSUE TITLE
scripts/fetch_eggs.py removed

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#1030]
File `scripts/fetch_eggs.py` was present in the last release (Oct 2015): https://github.com/galaxyproject/galaxy/blob/release_15.10/scripts/fetch_eggs.py

Recent work on the dev branch (by @natefoo etc) has removed various code to do with Python eggs. The removal of `scripts/fetch_eggs.py` has broken my TravisCI script which runs `python scripts/fetch_eggs.py` as part of setting up a test Galaxy instance. Currently only the stable branch Galaxy still works, the dev branch is broken, e.g.

https://travis-ci.org/peterjc/galaxy_blast/jobs/87703129

```
...
$ python scripts/fetch_eggs.py
python: can't open file 'scripts/fetch_eggs.py': [Errno 2] No such file or directory
```

What would the bootstrapping equivalent be for fetching Python dependencies? Use `pip install -r requirements.txt` perhaps?

**Comment by natefoo** [comment]
It's unfortunately a bit more complicated than that, we are using pip and wheels, but pip/wheel still don't support wheels for Linux for a couple of reasons. One of these reasons (the lack of ABI tag support in Python 2) I have written the support for and it should be released with a forthcoming major version of pip. The other reason (a lack of platform tag specificity) I have written support for but it's not likely to get into pip any time soon, as those discussions on distutils-sig seem to have stalled and I am not sure what direction they want to take. This means that for now, we are using our own version of pip. Technically you don't have to use our version of pip, but if you don't, you'll be compiling a _lot_ of stuff when you `pip install -r requirements.txt`. Our version lets you download the Linux wheels on https://wheels.galaxyproject.org/

The steps to take now begin at [line 101 in common_startup.sh](https://github.com/galaxyproject/galaxy/blob/dev/scripts/common_startup.sh#L101)

**Comment by peterjc** [comment]
Thanks - that's very helpful. Is there any value in resurrecting a stub `scripts/fetch_eggs.py` (and other scripts) which prints something reassuring about this change? Otherwise this looks like just a documentation issue...

I will attempt to tweak my TravisCI setup to cope with the dev branch (wheels) and the current stable releases (eggs)...

**Comment by peterjc** [comment]
Thanks @natefoo - I presume you mean us to do something like this (see also #1035):

```
$ pip install --extra-index-url http://wheels.galaxyproject.org/simple/ --trusted-host wheels.galaxyproject.org -r requirements.txt
```

But how would I install Galaxy's modified pip (on top of a standard pip) in order to use your pre-build wheel files?

**Comment by nsoranzo** [comment]
@peterjc Have you tried `./scripts/common_startup.sh` ?

**Comment by peterjc** [comment]
Thanks - exploring that now.

P.S. The PR with all the changes was https://github.com/galaxyproject/galaxy/pull/428

**Comment by natefoo** [comment]
@peterjc Good idea with the stub scripts - I'll add those.

If not using `./scripts/common_startup.sh` itself (I don't either on usegalaxy.org), you'll at least want to run line 101 and the contents of the `if` block following (to line 114).

**Comment by natefoo** [comment]
@peterjc looking a your Travis config... I was going to recommend that you run `./scripts/common_startup.sh --skip-venv --dev-wheels` in place of `python ./scripts/fetch_eggs.py` but it looks as if you're doing exactly that in your latest build. Looks like it's been successful.

**Comment by peterjc** [comment]
Yes, touch wood. Some unrelated SQLite issues requiring re-running some of the builds, but yes - just got a green light on the branch, and have made the change on the master branch and expect the result soon: https://github.com/peterjc/galaxy_blast/commit/c3292e68f8d6493f962b92a020a1c06a87bed688

Thanks for confirming this is a sensible solution :)
