### ISSUE TITLE
jbrowse tool test failure

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#10319]
jbrowse test #4 fails: https://github.com/galaxyproject/tools-iuc/runs/1174089497?check_suite_focus=true#step:9:3198

Probable cause: 9d3d5cb7572aff2942c68b37fdff0c4801c51a7f (tensorflow bump to 2.3.1)

**Comment by mvdbeek** [comment]
I think that's simple test result differences, see https://github.com/galaxyproject/tools-iuc/issues/3203#issuecomment-699935656
