### ISSUE TITLE
scratchbook with dataset collection oddity

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#10311]
Sorry for not knowing a better title for this, but what I found is this:
When you have a collection and you're trying to view one of the datasets contained within it with the scratchbook enabled, then what's getting displayed are the contents of what seems to be a random other dataset (maybe even from other users?).
When you view the same dataset without the scratchbook, or with the scratchbook but the dataset expanded first, then things work as they should.

**Comment by wm75** [comment]
@dannon I'm not sure whether this is a front-end issue, but maybe you're the right person to investigate?

**Comment by dannon** [comment]
This sounds like we're mixing identifiers in scratchbook code.  @guerler sound right?
