### ISSUE TITLE
unable to delete own dataset in data libraries

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1032]
reported by @jxtx 

I created a dataset in "JHU AS.020.124.02.FA15 Environmental Biomes” data library using the beta interface. It hung, and now I apparently don’t have permission to delete my own dataset? (this is test)
(can manage it in the admin UI, but still a bit odd)

**Comment by martenson** [comment]
Were you logged in as the same user (admin) the whole time? What error are you getting?
The library has no permissions attached to it nor do the folders so I assume you were doing it under the admin account.

**Comment by martenson** [comment]
I would appreciate some extra information, because I cannot reproduce this. ping @jxtx

**Comment by jxtx** [comment]
I would have been logged in as the same user, an admin, the whole time. I did not get any error, it just hung. I'll try to reproduce when I have some time.

**Comment by martenson** [comment]
I tried again and was not able to reproduce, please reopen if you happen to see it again.
