### ISSUE TITLE
In data collections, unless history item is expanded, edit button will lead to incorrect dataset

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#10328]
<img width="1383" alt="Screen Shot 2020-09-29 at 12 12 08 PM" src="https://user-images.githubusercontent.com/40246333/94604887-2582d280-024d-11eb-95c8-ff4b780a3f05.png">
<img width="1383" alt="Screen Shot 2020-09-29 at 12 11 58 PM" src="https://user-images.githubusercontent.com/40246333/94604896-29165980-024d-11eb-8baa-b53379279fd2.png">

When attempting to edit information about a dataset inside a collection by clicking the pencil icon, if the history item is not clicked and expanded first, the edit screen that appears will not correspond to the dataset clicked. Once the item is expanded, this goes away, and appears to stay away for that item specifically, but continues for all other datasets until they are expanded in turn.

**Comment by dannon** [comment]
Similar issue to #10311

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/10427
