### ISSUE TITLE
Workflow submission form swallows informative error message

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#10340]
```
Marius van den Beek @mvdbeek 11:52
can you check in the developer console if there is an additional error message coming from the server ?
for the requests that comes back with a 400 status code

M Bernt @bernt-matthias 11:53
I see the POST request POST https://galaxy.intranet.ufz.de/api/workflows/7170b83bc9c7a2a5/invocations

Marius van den Beek @mvdbeek 11:53
yeah, what’s the response there ?

M Bernt @bernt-matthias 11:54
AHHHH: field1: "Invalid column choice. Please try again after editing metadata of your input dataset by clicking on the pencil icon next to it."

Marius van den Beek @mvdbeek 11:54
ah!
we need to be better at forwarding this in the user interface
can you create an archive of the history so we can make sure we get a better error message ?
```

**Comment by mvdbeek** [comment]
this is on 20.05

**Comment by bernt-matthias** [comment]
For completeness. The bug occurred when using https://github.com/galaxyproject/galaxy/blob/dev/tools/filters/compare.xml (which appears in the Galaxy 101 tutorial). The first data set input is a bed file and the data column input does not show an option. In the tutorial I just manually enter a number and it works. But when I construct a workflow from this then the workflow run form does not unfold this step and the missing input is easily missed. 

I guess also the workflow should not be submittable at all.

**Comment by guerler** [comment]
xref: #10268

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/12124
