### ISSUE TITLE
Error importing TRS workflow

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#10359]
<img width="1523" alt="Screenshot 2020-10-05 at 14 59 49" src="https://user-images.githubusercontent.com/6804901/95082589-8d3c9000-071b-11eb-91eb-afd490288dca.png">

I guess something in the mapping isn't quite right ?
https://dockstore.org/workflows/github.com/mvdbeek/workflow-testing-repo/COVID-19%20variation%20analysis%20on%20Illumina%20metagenomic%20data:master?tab=dag looks ok

**Comment by mvdbeek** [comment]
I guess most people don't actually use whitespaces ?

**Comment by jmchilton** [comment]
Easy to reproduce. I'll see if I can figure out the problem.

**Comment by jmchilton** [comment]
Well I get a similar problem in the UI and I don't get it for my workflows, so probably not related to the API we're using. Let me see what I can figure out:

<img width="1229" alt="Screen Shot 2020-10-05 at 3 15 57 PM" src="https://user-images.githubusercontent.com/216771/95121898-b9f1a700-071d-11eb-8a4e-7da348ef5886.png">

**Comment by bgruening** [comment]
@jmchilton maybe that also helps: https://github.com/ga4gh/tool-registry-service-schemas/issues/153

**Comment by jmchilton** [comment]
I can't fork your repo @mvdbeek because I have one of the same name and I can't push to yours. 

```diff
commit 48a7210dbb2113f2ad4d02bd8ba176b0219f2e9f (HEAD -> master)
Author: John Chilton <jmchilton@gmail.com>
Date:   Mon Oct 5 15:45:34 2020 -0400

    These need forward slashes I think, right?

diff --git a/.dockstore.yml b/.dockstore.yml
index f37de7d..8364fe3 100644
--- a/.dockstore.yml
+++ b/.dockstore.yml
@@ -1,7 +1,7 @@
 version: 1.2
 workflows:
 - name: 'COVID-19 variation analysis on Illumina metagenomic data'
-  primaryDescriptorPath: workflows/sars-cov-2-variant-calling/workflow.ga
+  primaryDescriptorPath: /workflows/sars-cov-2-variant-calling/workflow.ga
   subclass: Galaxy
   testParameterFiles:
-  - workflows/sars-cov-2-variant-calling/workflow-test.yml
+  - /workflows/sars-cov-2-variant-calling/workflow-test.yml
```

Is this problem this?

**Comment by mvdbeek** [comment]
The forward slashes were the problem, but that broke the tools and DAG previews in the dockstore interface, and the examples on dockstore or the GTN don't use forward slashes.

**Comment by jmchilton** [comment]
Odd - the DAG with Github Actions is working for a smaller workflow (https://github.com/jmchilton/galaxy-workflow-dockstore-example-3). I'll ping the Dockstore team and see if they have ideas.

**Comment by coverbeck** [comment]
Is the problem now with the DAG, the import, or both?

**Comment by denis-yuen** [comment]
It sounds like the question is that the DAG is functional for https://dockstore.org/workflows/github.com/jmchilton/galaxy-workflow-dockstore-example-3:version_3?tab=dagbut not for https://dockstore.org/workflows/github.com/mvdbeek/workflow-testing-repo/COVID-19%20variation%20analysis%20on%20Illumina%20metagenomic%20data:master?tab=dag

Looking superficially, it looks like part of the problem might be that there is a validation error, it seems to be parsing the test parameter file as a json when it is actually a yaml (might be an assumption since WDL and CWL use JSON) and it seems to be dragging down the rest of it.

**Comment by mvdbeek** [comment]
Hmm, https://dockstore.org/my-workflows/github.com/jmchilton/galaxy-workflow-dockstore-example-3 also specifies test parameters as yaml, but that's interesting, I can skip the yaml file for now (and I think JSON might also work for us ?)

**Comment by denis-yuen** [comment]
Created https://github.com/dockstore/dockstore/issues/3851 
I also see a validation error on 3, so there might be more than one issue going on.

**Comment by bgruening** [comment]
We have deployed a local hack at usegalaxy.eu that makes it work on Dockstore and WorkflowHub.eu. https://github.com/usegalaxy-eu/galaxy/pull/85

Of course, this is just a hack and it would be nice if both TRS servers could behave identical.

**Comment by denis-yuen** [comment]
> We have deployed a local hack at usegalaxy.eu that makes it work on Dockstore and WorkflowHub.eu. [usegalaxy-eu#85](https://github.com/usegalaxy-eu/galaxy/pull/85)
> 
> Of course, this is just a hack and it would be nice if both TRS servers could behave identical.

Re-reading the beginning of  https://github.com/ga4gh/tool-registry-service-schemas/issues/153 
I think this is on a different issue from the beginning of the thread 

My understanding is that it seems like Dockstore can either use `id` or `name` property for a tool version for input to `version_id` in the end point of `/tools/{id}/versions/{version_id}`.  workflowhub.eu can only use `id`
Unfortunately, it seems like the TRS specification is a bit ambiguous on the meaning of `name` which we had interpreted as being a part of the `id` field. 

Can I confirm?

**Comment by bgruening** [comment]
> Unfortunately, it seems like the TRS specification is a bit ambiguous on the meaning of name which we had interpreted as being a part of the id field.

Yes, this is true. The spec could be more clear. BioContainers and workflowhub.eu are using the ID to my knowledge. The `name` seems to be not very intuitive given how arbritrary it can be.
