### ISSUE TITLE
Trailing comma in history search panel (subtitle: "Found [n],")

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#10358]
![comma](https://user-images.githubusercontent.com/6132258/95047101-72cecc00-06b3-11eb-88ce-29e761640819.png)

**Comment by ic4f** [comment]
This happens when there are no deleted and no hidden datasets, or no deleted. If there are both hidden and deleted datasets, or just hidden datasets, there is no trailing comma.

**Comment by cat-bro** [comment]
I'd like to look into this one
