### ISSUE TITLE
Data Manager toolform does not load on Test

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1036]
Results in an empty middle pane. No errors in JS console.

Log in as admin and try https://test.galaxyproject.org/root?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Fdata_manager_sam_fasta_index_builder%2Fsam_fasta_index_builder%2F0.0.2

**Comment by guerler** [comment]
It seems to work for me. I get an error for the anon user and the tool form for admins. Executing the tool also seems to work properly.
![untitled](https://cloud.githubusercontent.com/assets/2105447/11085845/df8d87c4-8818-11e5-8d42-91f09a820126.png)
![untitled1](https://cloud.githubusercontent.com/assets/2105447/11085848/e2decbea-8818-11e5-8e88-3a3bdb32f44a.png)

**Comment by martenson** [comment]
yep, this got fixed, the Test is updated as of yesterday, closing
