### ISSUE TITLE
Move from sqlalchemy-migrate to alembic

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#10369]
It's time we move from sqlalchemy-migrate to alembic. 
See discussion here: https://github.com/galaxyproject/galaxy/issues/7159#issuecomment-451219566 + comments [here](https://github.com/galaxyproject/galaxy/blob/release_20.09/lib/galaxy/model/migrate/versions/0102_add_tool_dependency_status_columns.py#L40) and [here](https://github.com/galaxyproject/galaxy/blob/release_20.09/lib/galaxy/model/migrate/versions/util.py#L94). There are 12 occurrences of `# SQLAlchemy Migrate has a bug` in migration scripts (11 refer to the same bug). As mentioned in the linked discussion, and to the best of my knowledge, it appears that sqlalchemy-migrate is no longer maintained (last commit was a year ago; moved to opendev), whereas alembic is doing fine (current version 1.4.3). I think we should move.

Unless there are objections, I'd like to take this on, aiming for the ~~21.01~~ 21.05 release.

**Comment by ic4f** [comment]
Changing milestone as per https://github.com/galaxyproject/galaxy/pull/13108#issuecomment-1021278281

**Comment by ic4f** [comment]
Done in #13513.
