### ISSUE TITLE
Workflow sheduler db-skip-locked assignment fails with empty handlers section

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10386]
Taken from gitter:
@mvdbeek 
Just a guess, which is that without any listed handlers we’re not setting up the ItermGrabber
I think that if https://github.com/galaxyproject/galaxy/pull/10177/files#diff-d7e80a366f3965777de95cb0f5b13a4eR270 there was following the initial logic of only activating db-skip-locked if expclitly configured
but I’ll have to write a test to figure this out

Related: https://github.com/galaxyproject/galaxy/pull/10177

**Comment by innovate-invent** [comment]
Possibly fixed by https://github.com/galaxyproject/galaxy/pull/10371

**Comment by jmchilton** [comment]
#10177 seems to have an explicit test for empty handlers. Can I close this?

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/10371 fixed this.
