### ISSUE TITLE
Liftover on usegalaxy.org is non-functional

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1039]
tool id="liftOver1" name="Convert genome coordinates" version="1.0.4"

**Convert coordinates of** Input BED format directly from UCSC, with known loaded liftover data in the loc, fails to load target genomes under the menu option **To**

Examples: 
data: bed6 file from UCSC using default region & exons for hg38 or hg19
test history: https://usegalaxy.org/u/jen-bx-galaxy-edu/h/liftover-test
hg38 dbkey/database = no liftover data available
hg19 dbkey/database = same

Related: https://github.com/galaxyproject/galaxy/commit/2ae60fbd84d87931e26227c27db36aae9b1323b0

**Comment by jmchilton** [comment]
Ping @natefoo - do we just need to update main's `tool_data_table_conf.xml`?

**Comment by natefoo** [comment]
Please try now, it should be fixed.

**Comment by jennaj** [comment]
Fix confirmed at usegalaxy.org
