### ISSUE TITLE
Move from grunt/uglify to webpack

### ISSUE THREAD

**Issue by carlfeberhard** [galaxyproject/galaxy#1041]
The **longer term goal** is to use webpack to move Galaxy to a client-side/API-driven web application and to simplify the entire js process (and our codebase) as a side effect. 

The **immediate goal** here is to use webpack to bundle front end scripts and **_improve the performance of the front end**_ (specifically usegalaxy.org) by reducing the number of requests (i.e. 1 bundle v. 12 modules) used for client scripts. For this round, the focus is mainly on the 'Analyze Data'/index/home page with a side benefit of bundling the 'common' libraries like jQuery/backbone/etc. for the other pages. 

(see also: https://trello.com/c/7midE7Bx)
(see part 2 at: #1207)
# Webpack

Webpack (http://webpack.github.io) traces the dependency tree and bundles all the needed modules (and minifies/removes-unused-code when doing a production bundle). Webpack uses an 'entry'/app point as the root of the tree and these are defined in the webpack.config file. Ideally, webpack can create multiple bundles: 
- one or more app entry points and their dependencies
- a common bundle(s) of all the modules shared by all the apps
- any asynchronous bundles that might be loaded sometime after the page is loaded

Webpack uses a loader system to bundle/include different resources into a page. Loaders can be used to transpile javascript (from coffee or es6), build templates, and even css and images: http://webpack.github.io/docs/loaders.html
# JS Modules in Galaxy

Webpack is a transition for us and a transition from an uncompleted transition to requriejs/AMD (and the r optimizer). We now have three (or four if you count grunt) different module/building methods to support: mako + script tags, defined modules + AMD/require, apps + webpack bundling. All have to (at least temporarily) co-exist and work for various pages. This means a lot of extra code to do the same thing in different ways.

My personal opinion on this process is that we should have been concentrated less on removing mako/removing the iframe and more on the api. We still have a lot of pages using POST+GET/UIControllers and we'll need to move that functionality to the API. If we don't and still point backbone at the web controllers when they are expecting a RESTful server, we're just moving technical debt to the front end. This has already started happening, so the API will have to come after. /rant/IMO

It's also the first time we're having to define definite, discrete apps as opposed to a collection of pages.

This is a disruptive, (hopefully not-so) painful, band-aid style change - so patience and feedback is appreciated.
# Usage
- You'll need to install webpack using npm. I installed mine globally: `npm install -g webpack`
- The client directory already installs what it needs there and that's where you'll call webpack to bundle the files: `cd my-galaxy/client; webpack`
- You can compile a non-fully-compressed version of the bundles: `webpack -d`
- Or a compressed 'production' version (much slower): `webpack -p`
- You can also watch for changes: `webpack --watch -d`
- Webpack bundles will be (?) found in `static/scripts/bundled`
- Webpack includes source maps and is debugger compatible (little or no id mangling in the -d version)
# For this release

To do:
- [x] use handlebars loaders to load tool menu templates
- [x] modularize/re-locate code in root directory: galaxy.base.js, galaxy.panels.js, etc. for use in commonLibs
- [x] make sure url parameters from root/index are getting to their targets (ideally via a Router - but 
- [x] consolidate menu, masthead and 'app' page layout views
- [x] separate concerns of App and page layout, make App objects smaller (a simple namespace or router)
- [x] incorporate i18n plugin and localize properly (while still allowing parallel require version)
- [x] clean up
- [x] smoke test most pages
- [x] update and move longer term goals to new issue

**Comment by martenson** [comment]
This sounds awesome. I will help as much as I can.

**Comment by dannon** [comment]
@carlfeberhard Like I mentioned before -- let me know if we can help, or if you want to revisit the idea of having a short group hackathon to knock this out.
