### ISSUE TITLE
Visually Re-organize Tool Metadata?

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#10440]
<img width="1097" alt="Screen Shot 2020-10-16 at 12 19 32 PM" src="https://user-images.githubusercontent.com/216771/96283344-12406880-0faa-11eb-91ac-4991908a5ab1.png">

We've got some different metadata about tools:
- Requirements pop-up in the header when a button is clicked in a menu. (The re-click the menu item to hide).
- Citations appear in a tab in the footer.
- xrefs appear in a tab in the footer (taking up a lot of space for a just a couple links), and they run into the citations bar in an odd way.

I've got new metadata I'd like to add including tool license and tool creator information which is synchronized with workflow metadata I'd like to add in #10408 (currently shown freely floating in the footer above but they can go wherever). There is still also other metadata we would like to include as well - relevant tutorial links and container descriptions would seem very important for instance (from usability and transparency perspectives respectively).

I think we should reorganize things a bit to make room for the new metadata (as well as future metadata) and make things a bit more cohesive.

I think many different approaches would be improvements - my opening suggestion would maybe just be to keep citations the way they are but generalize the "xrefs" visual element into a "Tool Metadata" element that would be collapsible and would have the references, requirements (removing them from the header/menu), and the new license and creator information just sort of listed cleanly inside.

Anybody hate this or have strong feelings as to an alternative?

**Comment by mvdbeek** [comment]
I like the collapsible idea, I think we shouldn't overload users with these metadata things, so that would be a neat solution.
We could maybe call this `About this tool` ?

**Comment by jmchilton** [comment]
@mvdbeek Yes - "About this tool" is a lot better than "Tool Metadata"!

I discussed this briefly with @guerler and his preference was to go a bit farther and merge citation information with the rest of this metadata and keep it as a single tab in the citations widget.

I like the idea of merging it all together and keeping it clean - but I'm not sure I think the bibtex tab would make sense to me then. I'd prefer abandoning tabs altogether then and just having the bibtex a popout or something. @guerler didn't like that I think however.

**Comment by hexylena** [comment]
:+1: to merge.  Maybe the BibTeX could just become a copy button like the "copy this tool id"?

**Comment by dannon** [comment]
Yeah, I think I added the bibtex tab and it's just not super useful as a first class tab -- the whole intent was an unstyled, raw version for copy -- that makes sense @hexylena

**Comment by guerler** [comment]
Overall I like this idea a lot, it would be nice to increase the visibility of tool developers and references.

**Comment by bgruening** [comment]
> Anybody hate this or have strong feelings as to an alternative?

I love this!

@jmchilton would it also make sense to expose the schemas.org annotation (aggregated at) https://usegalaxy.org/tools/json in every single tool?

**Comment by jmchilton** [comment]
Current distillation of this this discussion to pick apart while I work on the copy citations BibTex button - that is a good idea!

Unexpanded: 
<img width="1091" alt="Screen Shot 2020-10-16 at 3 54 12 PM" src="https://user-images.githubusercontent.com/216771/96303152-f350cf00-0fc7-11eb-80c3-74cf8055745b.png">

Expanded: 

<img width="1094" alt="Screen Shot 2020-10-16 at 3 54 19 PM" src="https://user-images.githubusercontent.com/216771/96303164-f77cec80-0fc7-11eb-9f28-180d23533434.png">

**Comment by jmchilton** [comment]
@bgruening that page isn't working for me, it seems like a very good idea though!

**Comment by bgruening** [comment]
Mh, the schema is hidden, it should be a hidden json (intended to be only readable by crawlers) ... not good if this is not working anymore. I will try to look at it.

**Comment by nsoranzo** [comment]
@jmchilton Looks nice to me too! Two suggestions:
- Maybe we could use a different button type for "About this tool" to make it clear that this will be expanded inside the page
- Replace geeky "chain" links with normal text links

**Comment by jmchilton** [comment]
I agree the button is off-putting. I'll work on finding something more pleasant.

Geeky though it may be I think providing consistent visual warnings about links that open to external content and in new windows are important from an accessibility standpoint:

> The objective of this technique is to provide a warning before automatically opening a new window or tab. Opening new windows automatically when a link is activated can be disorienting for people who have difficulty perceiving visual content, and for some people with cognitive disabilities, if they are not warned in advance.

taken from https://www.w3.org/TR/WCAG20-TECHS/G201.html (admittedly a different context that makes it clear what we're doing here doesn't go far enough... but I think the consistency is an important start).

Also if you use the creator widget for instance - that user type icon brings up a small table of all the metadata (much of which you don't want in the summary but might be interesting to dig deeper), the orcid links to the configured orcid.org profile, and the external link is the user's specified schema.org URL attribute. I'm not really sure which of these would be the most appropriate to make the actual name hyperlink to. Also some of the entries will have external links and some won't - making the name conditionally linked out like that seems questionable and inconsistent.

If we don't care about accessibility or consistency - I could make the license name a hyper link - but I don't think it makes sense for the creator content.

If it is just about the geek-ness of the link icon - could we do external link instead? https://fontawesome.com/v4.7.0/icon/external-link

**Comment by jmchilton** [comment]
<img width="1075" alt="Screen Shot 2020-10-19 at 10 30 36 AM" src="https://user-images.githubusercontent.com/216771/96464772-38f2df00-11f6-11eb-87b4-c590cd957fdf.png">

I got the copy bibtex button working, I'm skeptical this is an accessibility improvement - but it sure is slick.

I replaced the button with a link, but it still isn't clear it will expand in the page -- maybe I should add like a down arrow icon https://fontawesome.com/icons/angle-double-down?style=solid after the text when it is unexpanded.

**Comment by nsoranzo** [comment]
> If it is just about the geek-ness of the link icon - could we do external link instead? https://fontawesome.com/v4.7.0/icon/external-link

The external link arrow is indeed a much better fit IMO.

> I replaced the button with a link, but it still isn't clear it will expand in the page -- maybe I should add like a down arrow icon https://fontawesome.com/icons/angle-double-down?style=solid after the text when it is unexpanded.

We used to have a button with a single down arrow to indicate "expand this" in /workflows/invocations, but it seems it was removed in 20.09 .
Another example in the code base are the sections in the tool form, which can be collapsed/expanded: these use underlined text and an open/crossed eye icon.

Regarding the creators section, a good inspiration could come from the GTN contributor pages: https://training.galaxyproject.org/training-material/hall-of-fame/bebatut/ (in particolar the external links to ORCID, GitHub...)
