### ISSUE TITLE
Optional workflow file inputs prevent workflow scheduling if not provided

### ISSUE THREAD

**Issue by jancrichter** [galaxyproject/galaxy#10450]
A while ago I asked on gitter about optional workflow inputs, as they did not work at all for me (in the sense that scheduling failed when no input file was supplied to the optional input). @mvdbeek asked for the associated traceback at the time, but sadly I got distracted, sorry about that. Here it is now, as the problem has, well, become a problem again: 

```
galaxy.workflow.run ERROR 2020-10-08 15:20:46,023 [p:17600,w:0,m:4] [WorkflowRequestMonitor.monitor_thread] Failed to execute scheduled workflow.
Traceback (most recent call last):
File "lib/galaxy/workflow/run.py", line 83, in __invoke
outputs = invoker.invoke()
File "lib/galaxy/workflow/run.py", line 174, in invoke
remaining_steps = self.progress.remaining_steps()
File "lib/galaxy/workflow/run.py", line 316, in remaining_steps
self._recover_mapping(invocation_step)
File "lib/galaxy/workflow/run.py", line 518, in _recover_mapping
step_invocation.workflow_step.module.recover_mapping(step_invocation, self)
File "lib/galaxy/workflow/modules.py", line 638, in recover_mapping
progress.set_outputs_for_input(invocation_step, already_persisted=True)
File "lib/galaxy/workflow/run.py", line 423, in set_outputs_for_input
raise ValueError(message)
ValueError: Step with id WorkflowStep[index=1,type=data_input] not found in inputs_step_id ({51562: <galaxy.model.HistoryDatasetAssociation(1452904) at 0x7f34d10af438>, 51564: <galaxy.model.HistoryDatasetAssociation(1452902) at 0x7f34b9c96668>, 51565: <galaxy.model.HistoryDatasetAssociation(1452905) at 0x7f34b9c96c88>, 51566: <galaxy.model.HistoryDatasetAssociation(1452903) at 0x7f34c7fdc6d8>})
galaxy.workflow.scheduling_manager DEBUG 2020-10-08 15:20:46,032 [p:17600,w:0,m:4] [WorkflowRequestMonitor.monitor_thread] Workflow invocation [122327] scheduled
```

This is on Galaxy 20.05, updated to latest changes about 3 weeks ago. I'm unfortunately not at liberty to share the workflow. I have, however, observed the same behavior in three separate workflows now, in all of which the optional input is connected to a different tool. In all cases the tool's input is also optional and in all cases I have tried connecting the optional workflow input to the tool before and after switching it to optional. In all scenarios the workflow runs fine if the input file is provided but is scheduled only partly and reports failed scheduling when it is not. 

The workflows also work fine if no optional input is connected to the tool and instead the file is input to the tool by scrolling down in the workflow launch screen. The latter is the way it is currently being used but users would highly appreciate the convenience of an input at the top. 

Thanks for any help.

**Comment by astrovsky01** [comment]
As we work on this, are you able to remove the optional input tools in the workflow in favor of adding them into the input options on the workflow form before running?

**Comment by jancrichter** [comment]
Hi, 
thanks for looking into this. I am not sure I understand your request, though. 

Currently the workflows are being used with the tools in place, but their optional inputs not connected to any workflow input. So the user needs to scroll down in the workflow launcher to make the select the input file on the specific workflow step.

I took the time today to create a minimal failing example. Doing this, I was able to figure out the specific conditions under which this occurs:

* There is a **tool 2** that consumes an optional data input, which is supplied by an optional workflow data input
* There is a **tool 3** which creates an output collection using "discover_datasets" which is in turn consumed by a **tool 1** using a "data" input with `multiple='true'`
* Tool 1 and 3 have NO connection to tool 3
* when the optional input is provided scheduling always works 
* when the optional input to tool 3 IS provided through the optional workflow input, scheduling succeeds
* when the optional input to tool 3 IS NOT provided through the optional workflow input, scheduling fails
* when the optional input to tool 3 is provided DIRECTLY to the tool, scheduling succeeds

Sorry for the seemingly arbitrary tool numbering. A heavily censored verison of the workflow is attached.
[minimal.txt](https://github.com/galaxyproject/galaxy/files/5409267/minimal.txt)

**Comment by mvdbeek** [comment]
> Currently the workflows are being used with the tools in place, but their optional inputs not connected to any workflow input. So the user needs to scroll down in the workflow launcher to make the select the input file on the specific workflow step.

To clarify, when you say optional input, do you create an input like this ?

<img width="961" alt="Screenshot 2020-10-20 at 16 21 17" src="https://user-images.githubusercontent.com/6804901/96599528-51472480-12f0-11eb-9227-ec0899a22304.png">

Adding files to step ad-hoc is known not to work. In general we don't recommend changing tool options on the workflow run form. All user-definable parameters should be specified as input parameters.

**Comment by jancrichter** [comment]
What you are showing in the screenshot is what I want to have. In my description I call this an "optional workflow input". These, however, do not work correctly in my workflows, as described above.

**Comment by mvdbeek** [comment]
Your workflow file doesn't show any optional inputs so it is difficult to understand which inputs are connected where and how you do that.

> * There is a **tool 2** that consumes an optional data input, which is supplied by an optional workflow data input

Where is this optional data input coming from ? Are you adding this like I show in the screenshot above ?

**Comment by mvdbeek** [comment]
Let me

> * There is a **tool 3** which creates an output collection using "discover_datasets" which is in turn consumed by a **tool 1** using a "data" input with `multiple='true'`

And is that `multiple="true"` input also marked with `optional="true"` ?

**Comment by jancrichter** [comment]
The optional input is step index 2:

![image](https://user-images.githubusercontent.com/40425803/96602386-40e47900-12f3-11eb-94ff-f79c3f39077f.png)

And yes, I added it like you showed in the screenshot.

The `multiple=true` input is not marked as `optional="true"` but that is as it should be. This input is non-optional and will always be provided to tool 1 by tool 3.

**Comment by mvdbeek** [comment]
Thanks, and tool 3's optional input has `optional="true"` ?

**Comment by jancrichter** [comment]
Yes it does.

And again, thanks for having a look. This seems to be a pretty niche problem.

**Comment by jancrichter** [comment]
Oh my, I just realised where the confusion came from. There was a significant error in the tool numbering in my main post, sorry about that. It is fixed now.

**Comment by mvdbeek** [comment]
Let me see if I can build a testcase for this

**Comment by mvdbeek** [comment]
Is this the situation you're describing ?
<img width="818" alt="Screenshot 2022-01-24 at 13 17 27" src="https://user-images.githubusercontent.com/6804901/150781571-74dfc51f-7df4-4cde-bb8b-e4e67b20047b.png">

I guess I don't understand what's the difference between these two cases
> when the optional input to tool 2 IS NOT provided through the optional workflow input, scheduling fails
when the optional input to tool 2 is provided DIRECTLY to the tool, scheduling succeeds

Can you check if the best practice panel check reports any errors ?

**Comment by jancrichter** [comment]
The screenshot does indeed show the situation I describe. 

The best practice panel makes no complaints.

Maybe this makes the two situations clearer: 

1) There is an explicit "Input dataset", set to optional, connected to the tool's optional input. If the input file is not provided, scheduling fails.
2) Nothing is connected to the tool's optional input. If needed it is supplied ad-hoc, as you call it, via the extended workflow form. With this setup scheduling always succeeds.

However, in the meantime, I have noticed that this behaviour has another aspect. The reason it is caused in the above scenario, is that scheduling of the workflow is paused at some point, due to the "discover_datasets" output of "tool 3" (the scheduler of course does not know how many jobs to schedule until it finishes.

This problem with optional workflow inputs seems to show up in cases where any circumstance like the one described above causes scheduling to wait for a period of time and if the tool with optional input can only be scheduled after the pause.

The original workflows in question are rather sizable (> of 150 steps) and do include subworkflows.

Hope that helps.

**Comment by mvdbeek** [comment]
I think I got this one covered in https://github.com/galaxyproject/galaxy/pull/14641
