### ISSUE TITLE
Move the quota's widget documentation link into the main configuration file

### ISSUE THREAD

**Issue by gmauro** [galaxyproject/galaxy#10457]
https://github.com/galaxyproject/galaxy/blob/6b467183a52422a1b1bfb3d6f5e0a2193a2388f7/client/src/mvc/user/user-quotameter.js#L139

Move this URL into the https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample file

**Comment by jmchilton** [comment]
I've refactored that client code a bit in https://github.com/galaxyproject/galaxy/pull/10212/files - I will try to wrap this fix into that PR or my objectstore work.

**Comment by jmchilton** [comment]
Included as https://github.com/galaxyproject/galaxy/pull/10212/commits/b628309c80d7d7188bd9d4dc40a0ebcae1d59908 in #10212. If someone wants an easy paper-cut win they can merge my PR 😆.

**Comment by gmauro** [comment]
@jmchilton  too easy :rofl:
