### ISSUE TITLE
data libraries subsearch

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1045]
from @golharam 

>I have a data library with over 200 files in it.  Half of them are "clipped" and the other half are not.  I'd like to be able to search and display a subset of files in the data library.  This will make selecting the files I want to import into my history much easier.

**Comment by martenson** [comment]
@golharam How helpful would it be to include searching the subfolders?

**Comment by golharam** [comment]
Probably helpful....in my case, all the files are in the top-level of the
library.  Perhaps being able to search at any level or throughout the
entire library.

**Comment by bwlang** [comment]
subfolder search would be extremely useful...

**Comment by bgruening** [comment]
Any news on this. I was just ask about this one again. Thanks!

**Comment by martenson** [comment]
@bgruening no progress afaik

**Comment by martenson** [comment]
folder filter implemented in https://github.com/galaxyproject/galaxy/pull/8277
