### ISSUE TITLE
Change the unit of time when displaying jobs in admin

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#10474]
Currently, under Admin -> Jobs, the cutoff time for displaying current/recent jobs is in seconds, defaulting to 180. Minutes seem like a more applicable unit here given that even the default is set to multiple minutes, not a handful of seconds...

![image](https://user-images.githubusercontent.com/338642/96635944-8cdef000-12ea-11eb-8660-b6c7336713de.png)

**Comment by OlegZharkov** [comment]
I will look into that

**Comment by mvdbeek** [comment]
If you want to extend this beyond a paper-cut project I think it would also be crazy good if we can paginate and search jobs. That could be similar to what you did for the library pagination. If limited to a user we can even expose that outside of the admin panel.

**Comment by OlegZharkov** [comment]
> If you want to extend this beyond a paper-cut project I think it would also be crazy good if we can paginate and search jobs. That could be similar to what you did for the library pagination. If limited to a user we can even expose that outside of the admin panel.

could be done, but it has to be a separate issue
