### ISSUE TITLE
Make choice on Yes/No toggle more apparent

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#10477]
The default Yes/No toggle button (used e.g. for `<param type="boolean">` tool inputs) does not radiate with clarity in which option is selected. Is _Yes_ or _No_ selected here?
![image](https://user-images.githubusercontent.com/338642/96644368-f9f88280-12f6-11eb-8433-5758f24f4221.png)

At the very minimum, I feel making the selected text bold would help. Better yet, replacing the component with a slider (or a more visually discerning element) would help.

**Comment by guerler** [comment]
Working on it.
