### ISSUE TITLE
Display consistent format for job runtime

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#10473]
Clicking dataset info and viewing job runtime under Job Metrics displays the following (and I'm still not sure how long that job actually took):

![image](https://user-images.githubusercontent.com/338642/96635528-f4e10680-12e9-11eb-9cb1-8c73efeecab2.png)

**Comment by kxk302** [comment]
I'm going to work on this.

**Comment by kxk302** [comment]
Created PR: https://github.com/galaxyproject/galaxy/pull/10504
