### ISSUE TITLE
Being able to specify per-tool specs in the k8s runner

### ISSUE THREAD

**Issue by almahmoud** [galaxyproject/galaxy#10481]
Similar to how containers for specific tools can be mapped to use certain images/requests, it'd be cool to be able to override other specs for the job runner per tool (eg: use node affinity to redirect certain tools to certain kinds of nodepools, give a specific service account only to certain tools, etc...)

**Comment by mvdbeek** [comment]
The way I understand the issue you can do that by mapping tools to destinations in your job conf file. That seems doable both with static or dynamic job destinations mapping.

**Comment by almahmoud** [comment]
It is doable through job conf, but can be annoying to create a separate destination/environment just to change one job spec for a tool. The paper-cut is basically extending https://github.com/galaxyproject/galaxy-helm/blob/master/galaxy/files/rules/k8s_container_mapper.py to change more specs than just requests and container.
