### ISSUE TITLE
/api/authenticate/baseauth throws exception when auth header missing

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10513]
`GET /api/authenticate/baseauth` should return an informative response

[example](https://usegalaxy.org/api/authenticate/baseauth)

Currently returns
```json
{"err_msg": "Uncaught exception in exposed API method:", "err_code": 0}
```

**Comment by OlegZharkov** [comment]
Hmmm, I am going to create a PR, that addresses it. What response do you expect to see?

**Comment by dannon** [comment]
@OlegZharkov How about I just fix this in https://github.com/galaxyproject/galaxy/pull/10521

**Comment by OlegZharkov** [comment]
@dannon Oh, I just saw it. Sure, I will just suggest changes in your PR

**Comment by dannon** [comment]
@OlegZharkov No, it's fine, was just offering to help since it's the same endpoint I was already going through -- I see you already made the PR, no worries.

**Comment by OlegZharkov** [comment]
> @OlegZharkov No, it's fine, was just offering to help since it's the same endpoint I was already going through -- I see you already made the PR, no worries.

yeah, sorry I saw your comment after the PR. Ok then, I will leave it as it is.
