### ISSUE TITLE
Add API endpoint to allow admins to fetch users API keys

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10515]
Currently `GET /api/authenticate/baseauth` is the only endpoint that exposes [this function](https://github.com/galaxyproject/galaxy/blob/cf11df1234f5f69edc98a8c7b776b87531fb621b/lib/galaxy/managers/api_keys.py#L16)

The only alternative is `GET /api/users/{id}/api_key/inputs`, parse an awkward response, check if the API key exists and `POST /api/users/{id}/api_key` if not.

Ideally `GET /api/users/{id}/api_key` should be mapped to the linked function that creates the api key if it does not exist.

**Comment by innovate-invent** [comment]
Relevant code:
https://github.com/galaxyproject/galaxy/blob/95b0b4f01450fde74f3491903927b7787980086d/lib/galaxy/webapps/galaxy/buildapp.py#L678-L682
https://github.com/galaxyproject/galaxy/blob/95b0b4f01450fde74f3491903927b7787980086d/lib/galaxy/webapps/galaxy/buildapp.py#L733-L737
https://github.com/galaxyproject/galaxy/blob/95b0b4f01450fde74f3491903927b7787980086d/lib/galaxy/webapps/galaxy/api/users.py#L719-L724

**Comment by mvdbeek** [comment]
> Ideally `GET /api/users/{id}/api_key` should be mapped to the linked function that creates the api key if it does not exist.

GET shouldn't modify resources, I'd prefer `GET` to get the API key and `POST` or `PUT` to set it, that feels like a clean mapping.

> `GET /api/users/{id}/api_key/inputs`, parse an awkward response,

Agreed, that /api/users/{id}/api_key should have a clean response.

**Comment by innovate-invent** [comment]
POST would be reasonable so long as it calls the get_or_create function and does not recreate the api key on each call.
