### ISSUE TITLE
Add toolshed category:  "Structural Materials Analysis"

### ISSUE THREAD

**Issue by jj-umn** [galaxyproject/galaxy#10535]
@natefoo 
I'm working with an NSF grant to develop tools and datatypes for structural material analysis using High Energy X-ray Diffraction Microscopy:
```
NSF Award Notice for Award ID 2037773
Project Title: RAISE: A Materials Science Gateway for X-ray Imaging and Modeling of Microstructures
```
I think those tools will probably belong in a new toolshed category.

**Comment by mvdbeek** [comment]
Awesome @jj-umn! I've created the category on the testtoolshed, let me know if that looks good and I'll do the same on the toolshed.

**Comment by jj-umn** [comment]
@mvdbeek   Thanks, Marius.   I'll check with the grant members, and try to get a resolution within a couple days.

**Comment by jj-umn** [comment]
@mvdbeek  The Grant participants wanted to alter the description slightly. So the final answer is:

  category:      Structural Materials Analysis      
  description:  Tools for High Energy X-ray Imaging, Diffraction, and Modeling of Microstructures

Can you add that to the main toolshed.
Thanks,
JJ

**Comment by dannon** [comment]
@jj-umn Just added this to the main toolshed, should be good to go now.
