### ISSUE TITLE
data libraries interface speed regression

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#10538]
After the rewrite in 20.09 the DLs interface feels much slower. One of the reasons could be that there is a lot of additional javascript calls in unnecessary places illustrated below.

![Galaxy](https://user-images.githubusercontent.com/1814954/97008703-78496480-1543-11eb-855a-02bec691d121.png)
![Galaxy](https://user-images.githubusercontent.com/1814954/97008841-a3cc4f00-1543-11eb-8bda-251a28e4fd8c.png)

![Galaxy___UMSA___Data_Libraries_and_New_Issue_·_galaxyproject_galaxy](https://user-images.githubusercontent.com/1814954/97009210-1c331000-1544-11eb-90a1-a2c29012260c.png)

**Comment by martenson** [comment]
opening the 1000 genomes library(that has one folder) from https://usegalaxy.org/library/list (where the library app should already be loaded?) takes 8.41 seconds
![Galaxy](https://user-images.githubusercontent.com/1814954/97010138-505b0080-1545-11eb-894c-649967e48cc3.png)

**Comment by martenson** [comment]
cc @OlegZharkov

**Comment by OlegZharkov** [comment]
> opening the 1000 genomes library(that has one folder) from https://usegalaxy.org/library/list (where the library app should already be loaded?) takes 8.41 seconds

Do you mean 1000 files in a library? Note, that there's no pagination in 20.09, it's a different PR https://github.com/galaxyproject/galaxy/pull/10204

clicking on the file though... I will take a look

**Comment by martenson** [comment]
@OlegZharkov I mean `1000 Genomes` [library](https://usegalaxy.org/library/folders/Ff5109f746542d96d) that has one folder in it, sorry for the confusing example 😆

**Comment by OlegZharkov** [comment]
> @OlegZharkov I mean `1000 Genomes` [library](https://usegalaxy.org/library/folders/Ff5109f746542d96d) that has one folder in it, sorry for the confusing example 
> 
> edit: with browser caching enabled this particular request goes down from 8s to 2s which is arguably much better, but the experience of browsing a "file system" with 2s delay on clicks is still something we might want to improve

yeah, partially the problem is that we are going through AnalysisRouter.js now instead of galaxy.library.js and it takes some time to mount the component. We also need to find out a better way to hide tools panel, not just instant animation

But yes, please enable caching.  Also we should probably vuefy this dataset view and cache it in the store
![image](https://user-images.githubusercontent.com/15801412/97204526-7a672980-17b6-11eb-91c9-a2f759781df8.png)
