### ISSUE TITLE
GalaxyFS-latest is incompatible with current version of Cloudman

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#1053]
During launch I see the following error

```
2015-11-10 14:08:37,400 ERROR     supervisor:155  Fault starting supervisord prog: <Fault 20: "NO_FILE: can't find command '/mnt/galaxy/galaxy-app/lib/galaxy/web/proxy/js/lib/main.js'">
```

**Comment by hexylena** [comment]
That's the NodeJS proxy for GIEs that's failing to run. Hmm. I'm happy to answer questions about GIEs but I know nothing about cloudman :/

**Comment by MatthewRalston** [comment]
Thank you @erasche. It turns out that the npm modules were not installed, and I needed to navigate to the appropriate directory and run `npm install` with appropriate proxy settings. The current tarball is still incompatible, but after this correction, I can use galaxy okay. :)
