### ISSUE TITLE
Composite datatype upload dialog broken in 20.09

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#10550]
Currently the upload dialog for composite datatypes is broken on all public instances running 20.09 (.org, .eu, test), but not on usegalaxy.org.au (still on 20.05).

On affected instances, you can select the datatype you would like to create (so I don't think this is https://github.com/galaxyproject/galaxy/issues/9877), but then you won't be offered the dialog to actually upload any files.

**Comment by mvdbeek** [comment]
Thanks @wm75, that should be fixed in https://github.com/galaxyproject/galaxy/pull/10551
