### ISSUE TITLE
404 error browsing data libraries

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10554]
Accessing the dataset library list via the menu bar browses to /library/list but operations on libraries (creating a new library) sends the browser to /library/list/# causing library links to attempt to browse to /library/list/folders/Ff2db41e1fa331b3e which is invalid and should be /library/folders/Ff2db41e1fa331b3e.

**Comment by OlegZharkov** [comment]
Hi @innovate-invent, thanks for report. What version are you using? That should be fixed in https://github.com/galaxyproject/galaxy/pull/10284

**Comment by innovate-invent** [comment]
Ah, I must have pulled just before this PR was merged
