### ISSUE TITLE
Tools with variable number of inputs fail to name correctly using #{}

### ISSUE THREAD

**Issue by GuyReeves** [galaxyproject/galaxy#1055]
The revised rename dataset setup appears to be working well but it appears that tools which take variable inputs do not appear to take the name of any specified  input dataset (even if input datasets are assigned numbers in in the text presented to the user   eg input1, input2 
 Tools which do not work 
Convert, Merge, Randomize 0.0.0.1 - using ‘Header' option
FreeBayes - even when using single input BAM
Concatenate datasets tail-to-head (Galaxy Tool Version 1.0.0)

Consequently, these tools  break workflow 'naming-chains' which pass the basename of a starting input dataset across the  entire workflow.  Thanks  Guy

**Comment by bgruening** [comment]
@GuyReeves can you attach an example workflow?

**Comment by GuyReeves** [comment]
https://usegalaxy.org/u/guy1/w/using-input-file-names-imported-from-uploaded-file  

will this work?  I have added all three tools to a simple  workflow .  In the annotations are my comments on what happens and what I think should be happening.

I noticed today that while Convert, Merge, Randomize 0.0.0.1  does not use the  input dataset name  for naming the output, while version  0.0.0.2  does. 
 Note that version 0.0.01 takes  'input_bam'   while version 0.0.2 takes  'input_bams'

**Comment by bwlang** [comment]
I've also observed this with some tools... e.g.

> MIRA v4.0 de novo assember Takes Sanger, Roche 454, Solexa/Illumina, Ion Torrent and PacBio reads (Galaxy Tool Version 0.0.9)

We see this hint in the workflow editor:
`
This action will rename the output dataset. Click here for more information. Valid inputs are: read_group_0|filenames.
`

I've tried 
`#{filenames|basename}.assembled`
and
`#{read_group_0|filenames|basename}.assembled`
both produce
".assembled"

**Comment by jennaj** [comment]
Is this the correct pull request fix? Or was this fixed earlier and then became a problem again?
 https://github.com/galaxyproject/galaxy/pull/5021

Trying to figure out if this can be closed or not.

**Comment by oliverbader** [comment]
Is there a solution to this? I'm having this issue still with FreeBayes 3.1.5 @usegalaxy.eu
