### ISSUE TITLE
Some UX issues on 20.09

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy#10553]
I did not use Galaxy for a while but today I have seen several issues in Galaxy 

On History panel:

- Static text for collection when scrolling

  ![galaxy_history_bug](https://user-images.githubusercontent.com/1842467/97189021-7500e380-17a4-11eb-9a26-18685cb87506.gif)

On Multiple panel

- Strange stuff when scrolling

  ![galaxy_multiple_history_ux_bug](https://user-images.githubusercontent.com/1842467/97189365-cc06b880-17a4-11eb-9c41-a5438021175d.gif)

- Duplication of a dataset (number 18 in the second history)

  ![Screenshot 2020-10-26 at 11 29 03](https://user-images.githubusercontent.com/1842467/97190577-2bb19380-17a6-11eb-8d45-4bd345396ed6.png)

---

Details

**Server**: usegalaxy.eu
**Browser**: Firefox 81.0.2

**Comment by mvdbeek** [comment]
The masthead also seems to be able to scroll, but if you do that in the multi-history view you end up with this:
<img width="2227" alt="Screenshot 2020-10-26 at 17 25 04" src="https://user-images.githubusercontent.com/6804901/97199589-759f7700-17b0-11eb-81b5-7a58fc0f4c3c.png">

**Comment by wm75** [comment]
Same scrolling issues with Chromium.

**Comment by mvdbeek** [comment]
@guerler @OlegZharkov @dannon can I ask one of you to take a look at this ? Would be nice to ship the release without these bugs.

**Comment by mvdbeek** [comment]
> * Duplication of a dataset (number 18 in the second history)

that's not necessarily a bug, if you can share the history we can look at it in more detail. the rest should be fixed.
