### ISSUE TITLE
masthead banner is not showing up correctly

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1057]
![screenshot 2015-11-10 17 15 11](https://cloud.githubusercontent.com/assets/1814954/11077543/a65e6238-87ce-11e5-8a68-be7f24fc9aed.png)

**Comment by guerler** [comment]
This should fix it: https://github.com/galaxyproject/galaxy/pull/1059

**Comment by guerler** [comment]
Fixed in #1059.

**Comment by guerler** [comment]
Thanks.

**Comment by martenson** [comment]
Thank you @guerler, I assigned myself yesterday but your night-tour of fixing bugs was faster. :)
