### ISSUE TITLE
Replace tool panel sections with EDAM

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#10587]
Since I proposed this in the round table, figured I'd document my vision here a bit.

**Background**

We need a solution for the tool panel sections. They're non-uniform, they're hard to categorise properly, everyone does their own thing, it's a mess. Every admin needs to decide for themselves where the tool should go and they aren't always the best people to make that decision (speaking for myself here, I know nothing about where some rna tools go.)

**Solution**

Burn the tool_conf, shed_tool_conf, and integrated tool panel to the ground. Instead, we rely primarily on the EDAM terms sourced from the tools. For every EDAM term, users will see a "section" in Galaxy. We can natively nest these based on the EDAM hierarchy.

Now, we just have: the list of tools installed (shed database, maybe a list of tools in a tooL_conf like file.) And we have the EDAM terms.

**Possible Issues**

1. Tools aren't annotated with EDAM. Great, we should fix this. Throwing anything without tags in an "UNCATEGORISED" section at the end will be good motivation.
2. Old tools aren't annotated. Let's update them. Tools generally won't change EDAM types over time, so if any of the versions in the lineage are annotated with some tags, then we can take those.
3. Admins want their own sections? @jmchilton proposed that we permit additional ontologies that can be used, and admins can tag these tools (either in the tool, or outside in the database?)

**Benefits**

- No more shed_tool_conf or ITP. @natefoo, @Slugger70 and other admins everywhere rejoice :tada:
- Better EDAM annotation of existing tools
- Hierarchical tool panel
- Users can find tools by well annotated "thing I want to do", and can find them across every applicable section.

**Comment by hexylena** [comment]
Starting places for work:

Review these!

- [ ] galaxyproject/tools-iuc#1905
- [ ] galaxyproject/tools-iuc#1897

Implement this:

- [ ] expose edam in toolbox
- [ ] new toolbox based around edam.

**Comment by bgruening** [comment]
ping @hmenager @matuskalas

**Comment by hexylena** [comment]
ping @inkuzmin

**Comment by innovate-invent** [comment]
I would caution against having tools listed within the edam tree. It could get annoying to find deeply nested tools.
Having a edam tree view adjacent to a flat tool list, which is then filtered by the selection in the tree would be better.
It also provides the opportunity to collapse the tree view and have a simple search box at the top of the tool list.

**Comment by hexylena** [comment]
A flat list would definitely be my desired entrypoint! a tree only as a second view if development time would not be excessive.

**Comment by hmenager** [comment]
I completely agree with warnings related to any overly complex UI. The UI should:
- still be "simple", e.g. as flat as possible
- be customisable, but not ask users anything complex like providing an ontology to get it.

So:
- step #1 annotate properly a significant set of IUC tools
- step #2 prototype a bit to see how the resulting tool panel could look like
and then, start implementation.

I'll be happy to help in any way.

**Comment by hexylena** [comment]
I think I might have motivation to work on the galaxy portion of this a bit? If there's no PR in the next two weeks, anyone else should feel free to take over :)

**Comment by shenweiyan** [comment]
This is a great job! Admins want their own sections, is there any progress in this work now?

**Comment by hexylena** [comment]
Yep @shenweiyan it's live on usegalaxy.org and EU, check out the little button next to tool search

**Comment by hexylena** [comment]
(and admins have always been able to define their own sections if they need! just edit your tool conf and rearrange things as you like)

**Comment by shenweiyan** [comment]
Thanks @hexylena 

I see that users can use `edam_topics` or `edam_operations`  to define their own sections. And must the names of sections derived from any number of EDAM topic references or EDAM operation references? 

But I see some other sections (as shown below), such as `for Activity`, `for Publication`, etc. How can the administrators achieve this? 
<img width="289" alt="galaxy-edam" src="https://user-images.githubusercontent.com/26101369/146472206-2c20d667-760e-4e74-a6d6-b07c623094ac.png">

**Comment by hexylena** [comment]
I honestly don't know. I'd not seen the extra new ones those are super cool
and we need to be using them in other places. I'll let you know if I find
out!

(Anyone else please feel free to chime in with documentation here)

Steven Shen ***@***.***> schrieb am Fr., 17. Dez. 2021, 02:12:

**Comment by bgruening** [comment]
Please have a look at: https://github.com/galaxyproject/galaxy/pull/12327

**Comment by hexylena** [comment]
@shenweiyan it looks like it was in https://github.com/galaxyproject/galaxy/pull/12327 but I missed it, very neat. I have not been able to find .orgs config though, but maybe I'm searching with the wrong terms or the wrong branch or so.

**Comment by hexylena** [comment]
@bgruening would you be open to EU having some defined based off of GTN topics?

**Comment by jmchilton** [comment]
That screenshot was generated on my dev machine. Those panel categories are available and the icons will work - but I assumed they would be hand-crafted by admins when I wrote it.

I need to circle this back to this but https://github.com/jmchilton/gx-tool-db was some subsequent work that could be used to automate some of that and collaborate on annotations. It can read training materials into a tabular database and then has functionality for extracting that in different ways back into these tool panel definitions - that could be a way to populate trainings. It can also read the usegalaxy.eu flavors into the tabular database and could extract activities that way as well - that could be a way to define activities.

**Comment by hexylena** [comment]
Yeah I had the same thought about subdomains @bgruening, it really covers a
lot of similar use cases. @jmchilton oh wow, you already thought of the
thing and did it, that's super cool! This covers a lot of my use cases for
sure

Björn Grüning ***@***.***> schrieb am Fr., 17. Dez. 2021,
17:15:
