### ISSUE TITLE
Workflow list sorting issue

### ISSUE THREAD

**Issue by foellmelanie** [galaxyproject/galaxy#10600]
Hi, 

just wanted to report a strange behaviour of the workflow list: 

On the EU Server the [workflow list](https://usegalaxy.eu/workflows/list) "updated" column seems not to move accordingly when sorting for other columns: 

Screenshot of original workflow list: 
![wf_original_order](https://user-images.githubusercontent.com/16114269/97800542-4ec0c500-1c36-11eb-8fdb-9f5a94bb99e2.png)

Clicking on "Name" sorts workflows according to name and it sorts all other columns accordingly, but the "updated" column stays exactly the same: 
![wf_name_sorted](https://user-images.githubusercontent.com/16114269/97800562-7fa0fa00-1c36-11eb-8018-6d3ba922f7b9.png)

Thanks,
Melanie

**Comment by bgruening** [comment]
@OlegZharkov can you look at this please.

**Comment by OlegZharkov** [comment]
> @OlegZharkov can you look at this please.

yes, sure

**Comment by OlegZharkov** [comment]
Hmmm, isn't this issue supposed to be closed after https://github.com/galaxyproject/galaxy/pull/10678 is merged or does it happen only if it's merged in dev?

**Comment by dannon** [comment]
Automatic closure happens once merged to repo main branch, which here is dev, yep.
