### ISSUE TITLE
Masthead footnote icons shifted, minor ui glitch

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#10614]
The Masthead icons are shifted. Created this issue to keep track of it.

<img width="203" alt="image" src="https://user-images.githubusercontent.com/2105447/97888992-cdcb0180-1cf9-11eb-8bdc-92a34bd5dc6c.png">

**Comment by mvdbeek** [comment]
I haven't noticed this myself, but maybe that would be fixed by https://github.com/galaxyproject/galaxy/pull/10641 ?

**Comment by dannon** [comment]
Can reopen if this pops back up, but it seems fixed.
