### ISSUE TITLE
test failing more on 15.10 than on dev

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1061]
we have following trouble with testing 15.10 PRs
ping @guerler 
## casperjs tests fail for 5 testcases

they do not fail on dev

this might be because of fixes by @carlfeberhard that are in dev but not in 15.10
this is probably (some of the) related fixes https://github.com/galaxyproject/galaxy/pull/944

```
casperjs_runner.Test_03_HistoryPanel.test_00_history_panel
casperjs_runner.Test_03_HistoryPanel.test_20_anonymous_histories
casperjs_runner.Test_04_HDAs.test_00_HDA_states
casperjs_runner.Test_05_API.test_00_history_api
casperjs_runner.Test_05_API.test_01_hda_api
```
## API tests timing out more often

we might be missing some fixes (bigger timeouts) that we added to dev

list of tests that probably time out, ping @jmchilton 

```
api.test_libraries.LibrariesApiTestCase.test_create_dataset
api.test_histories.HistoriesApiTestCase.test_import_export
api.test_workflow_extraction.WorkflowExtractionApiTestCase.test_extract_with_copied_inputs
api.test_jobs.JobsApiTestCase.test_search
api.test_jobs.JobsApiTestCase.test_index_multiple_states_filter
```

**Comment by guerler** [comment]
Thanks! (:

**Comment by martenson** [comment]
xref recent affected PRs:  #1038 #1059 #1060

**Comment by jmchilton** [comment]
Opened #1065 lets see if that fixes more of these issues.

**Comment by jmchilton** [comment]
This is really awesome @martenson, we have for a long time perpetually said we need to run the tests and keep them passing but through your dedication (and others such as Nicola and Eric) we are really getting close to a point where tests won't be allowed to break anymore and that is exciting.

**Comment by martenson** [comment]
timeout of API tests seems better, the casperjs is down to 2 failing tests, and connection string change did not seem to help #1087

**Comment by martenson** [comment]
I think we did a decent job of getting up to speed, we have 2 failing casperjs tests for 15.10 that we still do not know how to fix but they are not failing on dev
