### ISSUE TITLE
[20.09] WF step box not updated on step input format change

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#10622]
In the WF editor, when you change the format of certain step input data that change is no longer getting reflected in the graphical step box and connectibility of the step does not get updated either.
Only current workaround is to save the WF in the non-updated (and non-connected) form, then reload and connect the step.

Examples are:
- multiqc's "Which tool was used to generate logs?" selection, which will always remain at the default "BAMtools" selection in the step box.
- Split file to dataset collection, for which changes to "Select the file type to split" are not propagated unless you reload the WF.

Seen on usegalaxy.eu after upgrade to 20.09

**Comment by mvdbeek** [comment]
Whoa, how did we not notice that before? Thanks @wm75!
