### ISSUE TITLE
database/tmp dir filling up

### ISSUE THREAD

**Issue by DanBerrios** [galaxyproject/galaxy#10628]
Our /database/tmp dir appears to be filling up and consuming our disk space. We have set "job_cleanup" to "always" in galaxy.yml.  Is it ok to remove the files manually in /database/tmp?  This is not the job working directory, which is set to a separate dir in our object store conf.xml.  Are these files that used during job execution but originate from other sources, like local file uploads?  What are these files.... ?

**Comment by nsoranzo** [comment]
You need to routinely clean this directory, see https://training.galaxyproject.org/training-material/topics/admin/tutorials/maintenance/slides.html#10
