### ISSUE TITLE
[20.09] usability regression on mobile (and on desktop too) - no navigation bar

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#10624]
With 20.09 the navigation bar gets hidden below a certain display width to avoid overflowing text.
Unfortunately, this simple solution comes at a cost for users that try to reserve only half their screen for Galaxy and are, for example, browsing training material in the other half. They now cannot access important bits of the UI like Workflows anymore.
This is even worse on mobile devices. At least on my phone, I cannot get the navigation bar to display even if I rotate the display to horizontal. Galaxy has never been a pleasure to use on mobile, but it *was* possible if you really needed it.

A possible solution used by other websites could be turning the whole nav bar into a vertical drop-down menu with expandable sections representing the nav bar items, if the display is narrower than the threshold width.

**Comment by OlegZharkov** [comment]
Duplicate https://github.com/galaxyproject/galaxy/issues/9844

**Comment by wm75** [comment]
Thanks for the pointer @OlegZharkov
