### ISSUE TITLE
'Hide history panel' glitch in the UI

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#10638]
Probably screenshots explain this better than paragraphs of text. Original view:

![image](https://user-images.githubusercontent.com/32272674/98353927-53172480-2020-11eb-976d-04d3b9821f64.png)

After clicking the icon in the bottom right corner to hide the history panel:

![image](https://user-images.githubusercontent.com/32272674/98354030-75a93d80-2020-11eb-84dd-05c3ea07e789.png)

Now I can unexpectedly scroll to the right and see an empty white space with some misplaced icons and text:

![image](https://user-images.githubusercontent.com/32272674/98354149-9d98a100-2020-11eb-987c-223c820dbfad.png)

Seems quite similar to some of the issues in https://github.com/galaxyproject/galaxy/issues/10553.

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/10644, thanks @simonbray!
