### ISSUE TITLE
Unable to remove toolshed tools from favorites release_20.09

### ISSUE THREAD

**Issue by code4dna** [galaxyproject/galaxy#10664]
I have this commit installed:
```
commit c49d4f722698b164652c0e0212796035987f1a05
Merge: 6fb4d6b 699b5c8
Date:   Mon Nov 9 08:58:44 2020 -0500
```

I noticed that tools installed with toolshed cannot be removed from favorites but the default installed tools can be removed from favorites.

**Comment by dannon** [comment]
@code4dna I just tested this out and it seems to be working in my hands -- is there a traceback associated with the request, or any other information you can share?

**Comment by code4dna** [comment]
It doesn't produce any messages in galaxy.log. I remember selecting an older version of a tool and clicking the Favorite button but am not sure if that is what caused it. Now when I click the Added button to remove from favorites, the button just appears in the pressed state without removing from favorites.
![added](https://user-images.githubusercontent.com/17836321/98894613-bfec4d80-246a-11eb-8afb-6e2f3c8efea3.png)

**Comment by dannon** [comment]
Ahh!  Can you open the javascript developer console in your browser and see if there are any errors output there?

**Comment by code4dna** [comment]
This error message shows up after clicking the Added button to remove from Favorites
```
DELETE  https://test.tamu.edu/testgalaxy/api/users/303905fee1757a23/favorites/tools/toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fminimap2%2Fminimap2%2F2.17%2Bgalaxy2
[HTTP/1.1 404 Not Found 23ms]
```

**Comment by dannon** [comment]
@code4dna My request looks just like that, without the proxy prefix:
DELETE http://192.168.0.101:8080/api/users/f2db41e1fa331b3e/favorites/tools/toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fminimap2%2Fminimap2%2F2.17%2Bgalaxy2
```

How is this test galaxy configured?  The root is at `https://test.tamu.edu/testgalaxy/` and other requests to that location work fine?  Where is the request intercepted (so, it never shows up in the Galaxy logs, right?  we need to figure out why not.)

**Comment by code4dna** [comment]
We have five Galaxy instances. Each is proxied with apache using a different port and group. So far we haven't had problems switching tools, running jobs, doing tool installation and other admin stuff (since working out the cookie_path issue). 

```
    ProxyPass /testgalaxy           uwsgi://localhost:4001/
    ProxyPassReverse /testgalaxy    uwsgi://localhost:4001/
    RewriteRule ^/testgalaxy/$ /testgalaxy [R,L]
    <Location "/testgalaxy">
        SSLRequireSSL
        AuthType CAS
        Require group testgalaxy
        AuthGroupFile /opt/rh/httpd24/groups/testgalaxy

        RewriteCond %{IS_SUBREQ} ^false$
        RewriteCond %{LA-U:REMOTE_USER} (.+)
        RewriteRule . - [E=RU:%1]

        RequestHeader set X-URL-SCHEME https
        RequestHeader set REMOTE_USER  %{REMOTE_USER}s
    </Location>
```

No messages in galaxy.log
Here is the apache log:
`[17/Nov/2020:00:33:44 -0600] "DELETE /testgalaxy/api/users/303905fee1757a23/favorites/tools/toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Fbwa%2Fbwa%2F0.7.17.4 HTTP/1.1" 404 196`

**Comment by dannon** [comment]
Is there any other rewrite rule that might be interfering based on matching `toolshed`?  A local toolshed you're redirecting somehow?

**Comment by code4dna** [comment]
There are no other rewrite rules or proxy definitions matching a toolshed.
Each of our Galaxies runs as a different user such as user testgalaxy instead of user galaxy. This keeps permissions between our Galaxies separated.

**Comment by code4dna** [comment]
we now have 22.05 installed and this is no longer an issue

**Comment by dannon** [comment]
@code4dna Great, good to know!
