### ISSUE TITLE
Alter tags of workflow via API

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10684]
Currently it is not possible to alter tags of a workflow after creation via the API.
```
PUT /api/workflows/{id}
{ "tags": [...] }
```
Should be added to that endpoint.

**Comment by mvdbeek** [comment]
You can do that, but I agree the payload is too complicated.

**Comment by innovate-invent** [comment]
ah, tags wasn't included in the docs: https://docs.galaxyproject.org/en/latest/api/api.html#galaxy.webapps.galaxy.api.workflows.WorkflowsAPIController.update

**Comment by davelopez** [comment]
This was addressed in #10748
