### ISSUE TITLE
Errored hidden datasets should show as errored rather than hidden in histories view

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10689]
![image](https://user-images.githubusercontent.com/1768820/98741008-c2fb1700-2360-11eb-8dae-9ba47a6a0234.png)

This view is useful for tracking the state of a workflow. Because errored datasets are displayed as hidden, it is unclear that there were errors in the workflow. I usually have to open the history and search for errored datasets.

**Comment by mvdbeek** [comment]
That would be a giant pain (this is what we had before). The next iteration of the invocation view will do a much better job at it.
