### ISSUE TITLE
This workflow contains missing tools. It cannot be saved until they have been removed from the workflow or installed.

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10687]
```
PUT /api/workflows/{id}
{ "workflow": ... }
```
returns "This workflow contains missing tools. It cannot be saved until they have been removed from the workflow or installed."

It is bizarre that a workflow can be uploaded with missing tools but not replaced.

**Comment by mvdbeek** [comment]
Its not about the upload, we just don't want to destroy workflows.

**Comment by innovate-invent** [comment]
So the workflow must be deleted and recreated to update it?
