### ISSUE TITLE
[20.09] Subworkflow outputs not settable as workflow outputs

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10719]
![image](https://user-images.githubusercontent.com/1768820/99106955-f1176b80-2599-11eb-8b26-6086c96a42c9.png)
The outputs of the subworkflow do not have the option to be set as workflow outputs

**Comment by mvdbeek** [comment]
This is now possible:
<img width="301" alt="Screenshot 2022-10-28 at 17 17 46" src="https://user-images.githubusercontent.com/6804901/198673114-cc0c7938-d1ce-488a-bc88-6f8f3c8a8062.png">
