### ISSUE TITLE
FTP problems with pluggable upload components

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#10721]
With https://github.com/galaxyproject/galaxy/pull/9888 and dropbox activated (and working:+1:) FTP seems to have problems and is throwing the following error:

> Unable to fetch gxftp://brazil-and-isc1.filter.vcf
> `<urlopen error unknown url type: gxftp>`

**Comment by bgruening** [comment]
Found my error. Handlers have not been restarted :(

**Comment by ajs6f** [comment]
This happens repeatedly for our attempt at setting up Galaxy's FTP functionality. It is usually cured for a while by restarting Galaxy but comes back within a few attempts at upload, after which it occurs persistently.
