### ISSUE TITLE
Add job duration on Admin Jobs

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#10736]
`Admin->Jobs` page lists several job properties and it would be informative to also add a column for job duration for running jobs.

Additionally, the width of the columns is off so adjusting those to be more suitable for the values they take would help the layout. Formatting the `Last Update` to make it a bit more human readable would also help.

![image](https://user-images.githubusercontent.com/338642/99428992-61ddc100-28d5-11eb-9447-82087759b80e.png)

**Comment by dannon** [comment]
Admin interface has additional clarifying text and better representation of update time for unfinished jobs.
