### ISSUE TITLE
Hide the user API key on Admin by default

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#10734]
The page `Admin->Users` shows all of the users API keys.
![image](https://user-images.githubusercontent.com/338642/99424899-36a4a300-28d0-11eb-9fd1-93217882a2e5.png)

At the very least, this should be hidden by default (eg, displayed as a bunch of `*` chars), and unless there is a good reason for it, it should just be removed altogether.

**Comment by dannon** [comment]
+1 to just removing it.  If impersonation is enabled an admin can jump through the hoops to get it if necessary.
