### ISSUE TITLE
Add amount of storage a user is consuming on Admin

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#10733]
The `Admin->Users` page lists a number of properties about a user. Would be great to add a column listing how much storage the user is currently consuming.

![image](https://user-images.githubusercontent.com/338642/99424432-a6fef480-28cf-11eb-9b42-5c3eb5267251.png)

**Comment by dannon** [comment]
I actually did this last week, let me find the PR.

**Comment by afgane** [comment]
Nice! This is the best example of a paper-cut to date: it got done before being posted :)
