### ISSUE TITLE
[20.09] Workflow list in tool box lists duplicates

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10746]
While editing a workflow with subworkflows the workflow list in the toolbox lists duplicates of the subworkflows.

![image](https://user-images.githubusercontent.com/1768820/99479449-0c240b80-290b-11eb-97d8-2ebe80558138.png)

Possibly listing every revision?

**Comment by mvdbeek** [comment]
These are hidden subworkflows

**Comment by innovate-invent** [comment]
If I have only one workflow with only one instance of each subworkflow in it, why does it list more than one?

**Comment by dannon** [comment]
Fixed in #10759
