### ISSUE TITLE
Run workflow button does NOT gray-out when clicked -- causing big problems in long running workflow. Execute button does gray-out

### ISSUE THREAD

**Issue by rbrown1422** [galaxyproject/galaxy#1075]
Good morning Team,
Could you please fix the "Run workflow" button that does NOT gray-out when clicked?   This causes my users to double-click it and then major issues.
Attached is the problem button, and two other "Execute" buttons that work correctly -- one also involved in workflows.
Thanks
bob brown

![run on tool in galaxy -- uses execute button does gray-out](https://cloud.githubusercontent.com/assets/5491126/11125176/7515a7d6-8936-11e5-981e-8b8e8fe1eaec.png)
![rerun workflow by starting from previous run history -- click rerun uses execute button](https://cloud.githubusercontent.com/assets/5491126/11125174/75127dcc-8936-11e5-8b86-06600ee80c91.png)
![inital run of a workflow in galaxy -- use run workflow button doesnot gray-out](https://cloud.githubusercontent.com/assets/5491126/11125175/75133474-8936-11e5-9740-c8c0ea780c65.png)

**Comment by rbrown1422** [comment]
Doesn't another else have an issue with this?  For my lab staff the workflow is slow to start so it appears they didn't click the button and click it again. The workflow is a 5 hr process so it runs once, wipes  out the results and runs again.   Yes, I guess I could code around it but that is not the point of user feedback.
Thanks
Bob

**Comment by mvdbeek** [comment]
many things have changed since 2015, if that's still an issue please file a new issue.
