### ISSUE TITLE
Workflow reports history_dataset_as_image with path option broken

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#10764]
In https://github.com/galaxyproject/galaxy/pull/9769 @OlegZharkov implemented additional syntax for workflow reports including the ability to display an extra file (e.g. from a composite datatype) as an image in the report.
This particular functionality relying on an optional path argument to history_dataset_as_image seems to have been broken at some point since then (it seems that the path argument is getting ignored now), maybe as a result of https://github.com/galaxyproject/galaxy/pull/10121 (?), and should be restored.

**Comment by OlegZharkov** [comment]
I will investigate

**Comment by wm75** [comment]
Thanks @OlegZharkov! It's working perfectly again.

**Comment by OlegZharkov** [comment]
> Thanks @OlegZharkov! It's working perfectly again.

thank's for noticing :+1:
