### ISSUE TITLE
Inconsistency for "batch" workflow connections for optional outputs

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#10778]
In a workflow I want run the following tools one after the other: 

1. `Input Dataset Collection` 
2. `FeatureFinderMultiplex` 
3. `IDMapper`

`FeatureFinderMultiplex` has optional outputs that depend on a select box: `Optional Outputs`

If I connect 1 -> 2, select the optional output of 2 (needed is `out`), and then connect 2 -> 3; then the connection between 2 and 3 is not a "map over connection", i.e. it is not batch mode (not sure about terminology).

If I first select the optional output of 2 (needed is `out`), and then connect 1->2 and 2->3; then the 
connection between 2 and 3 is a "map over connection", i.e. 2 runs in batch mode. 

The later is the expected behavior and I guess the other variant would not work. 

Not sure if this is a bug or a feature. I guess this is a similar problematic as conditionals that affect  in/output. 

This happens on 20.05 and 20.09 (tested on usegalaxy.org)

**Comment by mvdbeek** [comment]
Yep, that's a bug, but it shouldn't be too complicated to fix.
