### ISSUE TITLE
render OpenEBench link in toolform, similar to bio.tools

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#10787]
We are starting to annotate tools with bio.tool IDs in the [xref tag](https://github.com/galaxyproject/galaxy/pull/7905). The same IDs can be used to create an additional link to OpenEBench. The links look like `https://openebench.bsc.es/tool/galactic_circos`. The last part is the bio.tool ID.

It would be nice if we can add an additional bullet-point linking to OpenEBench as well.

![grafik](https://user-images.githubusercontent.com/469983/99948289-89230b00-2d79-11eb-81ed-5be944cf3587.png)

It would be also nice to add small logos about projects.

**Comment by jmchilton** [comment]
Is #10789 okay?

**Comment by bgruening** [comment]
Lovely! Thanks!!!!
