### ISSUE TITLE
Provide default container to be used for tool execution

### ISSUE THREAD

**Issue by torfinnnome** [galaxyproject/galaxy#10795]
It would be very convenient to have an official container to be used as a fall-back/default container when running Galaxy in a container-only setting, used in these parameters:

`docker_default_container_id` and `singularity_default_container_id`.

**Comment by innovate-invent** [comment]
That container would have to somehow have all tools that do not have containers installed into it. How would one predict such a thing?
You should look into the involucro functionality, it will generate a container for a tool if one is not found.

**Comment by bernt-matthias** [comment]
I guess the current solution is https://github.com/galaxyproject/galaxy/blob/076a695afd90d9ad7b140aabd02871422496c770/lib/galaxy/config/sample/job_conf.sample.yml#L522

Please reopen if needed

**Comment by bernt-matthias** [comment]
I agree with @innovate-invent. One solution might be to mount possibly existing conda envs into such a container.

@bgruening mentioned something along these lines.

**Comment by torfinnnome** [comment]
Yeah, better to use something like this: https://github.com/galaxyproject/usegalaxy-playbook/blob/8fdaa15df9ad098b5c3a8627a5321a461f83f8e1/env/common/templates/galaxy/config/tpv/defaults.yaml.j2#L29

**Comment by bernt-matthias** [comment]
I can't understand my answer myself anymore. My current me would answer with https://github.com/galaxyproject/galaxy/blob/e8a288b2d389b756c651cbe1a5682239dd6233fe/lib/galaxy/config/sample/container_resolvers.yml.sample#L105
