### ISSUE TITLE
Find S3 storage+hosting for testing artifacts.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#10793]
We've migrated a bunch stuff from Jenkins to Github actions - which will hopefully improve the stability but there are some short comings relative to Jenkins. Jenkins would serve HTML result summaries, host screenshots for all Selenium tests, etc.. The testing and hardening team identified connecting Github actions to S3 buckets (or some other storage) as a way to improve Galaxy's testing infrastructure.

@OlegZharkov would also like to work on automating generation of screenshots for use by training material (like the way the rule builder documentation works) and would like some permanent storage for that to automate deployment to.

**Comment by OlegZharkov** [comment]
any update on S3, by any chance?

**Comment by OlegZharkov** [comment]
this issue should be closed
