### ISSUE TITLE
Remove `folder_up` button from data folder

### ISSUE THREAD

**Issue by OlegZharkov** [galaxyproject/galaxy#10800]
Initially suggested by @bgruening 

Would it make sense to remove `..` button from data library folder?
Since we have our great PathBar already, we don't really need `..`, do we?
![image](https://user-images.githubusercontent.com/15801412/100145989-7acc1080-2e99-11eb-9fc2-3feec9a8e36f.png)

**Comment by nsoranzo** [comment]
My suggestions:
- replace the `..` with an upwards arrow (less geeky)
- instead of wasting an entire "line" for one button, put the upwards arrow button on the left of the "select all" checkbox, on the same line as the table headers. The Dropbox web interface does something similar.

**Comment by OlegZharkov** [comment]
> My suggestions:
> 
> * replace the `..` with an upwards arrow (less geeky)
> * instead of wasting an entire "line" for one button, put the upwards arrow button on the left of the "select all" checkbox, on the same line as the table headers. The Dropbox web interface does something similar.

I think, an arrow on the left side of "select all" is slightly ambiguous. Maybe it will make sense, if we move pathbar between the folder table and home button. Otherwise, I think we can easily remove that button, our pathbar already replicates its functionality

**Comment by afgane** [comment]
+1 to @OlegZharkov most recent comment: the `..` (or a replacement) seems redundant. I'm also in favor of moving the breadcrumb path under the row of icons. As is, the gray bar appear more like a title to the page than a navigation mechanism.
