### ISSUE TITLE
implement 'explain/showcase this tool' feature on the toolform

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1081]
This would be available when the tool has test data and test case available. The implementation details can vary, some ideas:
- just providing the test datasets and showing a help text
- auto executing the test job with explanations (visible in history)
- showing automatically created introduction #1064 with step by step explanation of what is happening

ping @bgruening

**Comment by bgruening** [comment]
That's it :) I would pre-load the datasets into the tool. Tools with many different input, needs to have the correct inputs in the right order. Also setting the parameters specified in the test section might help.

Thanks for creating the issue!

**Comment by hexylena** [comment]
Yes! I've wanted this for a while.

I'd add another use case:
- filling out the toolform with some parameters specified in the help text

So anyone reading the help text could click a button and have the toolform populated. (Though I think this is do-able by just constructing a complicated URL... I never got around to testing that).

I really want this for my [NCBI Entrez suite](https://testtoolshed.g2.bx.psu.edu/repository/display_tool?repository_id=7427787295f1f939&render_repository_actions_for=tool_shed&tool_config=%2Fsrv%2Ftoolshed%2Ftest%2Fvar%2Fdata%2Frepos%2F002%2Frepo_2166%2Fefetch.xml&changeset_revision=a42fa980bbd5) which could really benefit from it

**Comment by bgruening** [comment]
@erasche; @martenson and me was talking about a intro integration. So what if we could auto generate a Intro based on a tool form, maybe a test-section and describe the tool interactively.

**Comment by hexylena** [comment]
@bgruening yes, I thought "filling out the form" for the user (and maybe explaining wtih intro.js) would work nicely with intro / the above ideas.

**Comment by mblue9** [comment]
I think this is an excellent idea! Does it overlap with the Interactive Tours?

Did I also see somewhere that there were plans to make the tools' test-data available though the tool-form "Options" drop-down? As that alone would save time right now on finding and loading in the test-data and make it quicker to troubleshoot issues like this: https://github.com/galaxyproject/tools-iuc/issues/1824 (where I manually uploaded the test-data to test the tool through the GUI)

**Comment by dannon** [comment]
@mblue9 Yep, it's the same thing.  We should have closed out this issue a while back, there's now a webhook for generating these tours on the fly, see https://github.com/galaxyproject/galaxy/pull/4019  (and certainly ping us if you have any trouble with it, but it should do exactly what you're looking for here!)

**Comment by mblue9** [comment]
Thanks @dannon! I had just found that issue and tested it out but it didn't work in my case, I'll put a comment in that issue.

**Comment by dannon** [comment]
@mblue9 Ok, sure, would appreciate the feedback on what didn't work for you!
