### ISSUE TITLE
improve UX when searching tool panel

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1084]
This is very relevant to Main, Freiburg Galaxy and other Galaxies that have hundreds of tools.
The basic problems:
- the tool panel shows only subset of relevant results (mostly because there is no space for more)
- the shown order is not corresponding to the search score because it is overriden by the tool section order

**Comment by hexylena** [comment]
I think all of these points are included in #2272, closing in favour of that one with more info.
