### ISSUE TITLE
Can't connect optional input to optional subworkflow input

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10864]
![image](https://user-images.githubusercontent.com/1768820/101413172-a9ce8300-3898-11eb-9914-353bb556b27f.png)

The input of the "test" subworkflow is optional along with the parent workflow input.

[Galaxy-Workflow-Unnamed_workflow.ga.txt](https://github.com/galaxyproject/galaxy/files/5655612/Galaxy-Workflow-Unnamed_workflow.ga.txt)

**Comment by martenson** [comment]
fixed by https://github.com/galaxyproject/galaxy/pull/10869
