### ISSUE TITLE
Remove `show_params.mako`

### ISSUE THREAD

**Issue by OlegZharkov** [galaxyproject/galaxy#10860]
We kinda need to port it to Vue and that file should be gone. There are just few very little things left to make it happen:

- [ ] Job Dependencies 
- [ ] Inheritance Chain
- [ ] Command Line
- [ ] Dataset peek

Everything else is already a Vue component. I guess, Job Dependencies are the only component-worth thing left there. 

Can someone please tell me how do I enable Job Dependencies locally? For example, I can see FastQC dependency on EU. The same tool returns no dependencies locally, is it buried somewhere in configs or do I look at the wrong place?

(would be grateful if someone assigns this issue to me)
(maybe paper-cut?)

**Comment by bgruening** [comment]
@OlegZharkov can you please have a look at https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample#L1753 and the following options.

**Comment by OlegZharkov** [comment]
> @OlegZharkov can you please have a look at https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample#L1753 and the following options.

Unfortunately, didn't help. Should be something else
