### ISSUE TITLE
Adjust run.sh and run_tests.sh to use gunicorn + fastapi by default

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#10885]
This depends on https://github.com/galaxyproject/galaxy/pull/10823 and https://github.com/galaxyproject/galaxy/issues/10884

This includes making sure --daemonize and --reload continue to work.

**Comment by bgruening** [comment]
@mvdbeek I really like where this is going. But I'm concerned that we have still `paste` around, need to support `uwsgi` etc ...
Can we make sure that at least `paste` gets dropped in this transition?

**Comment by mvdbeek** [comment]
Yes, absolutely.

**Comment by jmchilton** [comment]
I think reload is already broken right? At least under uwsgi?

**Comment by mvdbeek** [comment]
One thing less to worry about. I think you can `HUP` the process, but uwsgi is so configurable that we may not have configured it to do that 😆

**Comment by mvdbeek** [comment]
Alright, `APP_WEBSERVER=dev ./run.sh` is starting galaxy with the new stack now (https://github.com/galaxyproject/galaxy/pull/11772). I think it's time now to make this the default. @davelopez volunteered to take a look at this.

**Comment by davelopez** [comment]
Sorry for dropping the ball with this Marius!

**Comment by mvdbeek** [comment]
Ah, no worries, we did talk about, I should've change the assignment back then.

**Comment by mvdbeek** [comment]
And finally @natefoo knocked it out of the park with https://github.com/galaxyproject/galaxy/pull/13224
