### ISSUE TITLE
Sqlalchemy 1.4 compatibility

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#10892]
SQLAlchemy 1.4 is going to remove a considerable amount legacy patterns and is going to gain asyncio support.
There are migration notes for 1.4 [here](https://docs.sqlalchemy.org/en/14/changelog/migration_14.html) and more explicit instruction for migrating to 2.0 style [here](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html).

This might also be the right moment to move at least a subset of our mappings to use declarative base, which is the predominant form of mapping. Most examples in the sqlalchemy docs use declarative base, and I think this would developers that are new to SQLAlchemy (and everyone else IMO). 

SQLAlchemy 1.4 is currently in beta (1.4.0b1 released on 11/2/20). Thus, we start by making the code base compatible with 1.4 without breaking it under 1.3 (2021 Q1), followed by migration to 1.4, tentatively in 2021 Q2, provided sqlalchemy 1.4.0 is released and is stable.

**Comment by ic4f** [comment]
Done in #11737 and #12064
