### ISSUE TITLE
Clarify input states on the Admin->Jobs page

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#10941]
The Admin -> Jobs page provides a table with the currently running jobs but it is not always clear why is a job in the state that it's in and I believe this is due to the ambiguity of input column. From what I've been, the input can be in state `ok`, `new`, and `running` (presumably others as well but I haven't seen those). What does state `running` mean on an input? I guess the fact a job that will produce that input is currently running, but I don't see a way to link that input to a job. At the very least, it feels we should add a bit of help text on this page that describes what the meaning of each dataset (and job) state is. Better, inputs would link to their respective job. And ideally, there would be a `reason` column added for why is a job not running for example (as in inputs not available yet, not enough resources).

![image](https://user-images.githubusercontent.com/338642/102391843-41705780-3fa4-11eb-95ed-f1198f13051a.png)

**Comment by OlegZharkov** [comment]
fixed in https://github.com/galaxyproject/galaxy/pull/11205
