### ISSUE TITLE
Beta history panel issues

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#10947]
Super-exciting to have the history PR merged finally, that is a monumental piece of work, congrats @Nerdinacan ! And it looks really good too.
Nevertheless, here are some issues from my first impressions:

- [ ] Opening a tiny history with 2 items takes about 19 seconds with a call to the http://127.0.0.1:8081/api/histories?q=deleted&qv=None&view=betawebclient
  
![Screenshot 2020-12-17 at 10 39 07](https://user-images.githubusercontent.com/6804901/102470382-2eb55b80-4054-11eb-9e02-bdd41228e017.png)

- [x] The blue loading strips occasionally re-appear when hovering over the panel
- [ ] The Collapse Expanded Datasets button fails with 
```
vue.runtime.esm.js:1888 TypeError: e.emit is not a function
    at click (ContentOperations.vue?7cbb:1)
    at zt (vue.runtime.esm.js:1854)
    at n (vue.runtime.esm.js:2179)
    at zt (vue.runtime.esm.js:1854)
    at HTMLButtonElement.n (vue.runtime.esm.js:2175)
    at HTMLButtonElement.o._wrapper (vue.runtime.esm.js:6917)
```
- [ ] Select history dropdown is limited to the history panel div extent, it seems:
![Screenshot 2020-12-17 at 10 43 49](https://user-images.githubusercontent.com/6804901/102470934-dcc10580-4054-11eb-816e-fee3017acef9.png)
- [ ] The history dropdown is not scrollable / scrolls super weirdly, it sorts of stutters
  - [x] Is this why you're doing the call to http://127.0.0.1:8081/api/histories ? In that case, could you just fetch the history names ?
  - [ ] Selecting histories from there is probably not useful, I usually need to see contents, tags and modification times to find the history I want. That might just be my personal preference though
  - [ ] The unhide operation for collection elements is the first icon on the left, where we used to be able to look into the dataset. Maybe you can switch the view button back to that position and move the unhide into the `:` menu ?
 
![Screenshot 2020-12-17 at 10 48 43](https://user-images.githubusercontent.com/6804901/102471505-9029fa00-4055-11eb-920b-47320885fbd8.png)

- [ ] What does the the copy datasets button do / how do I use it ?
![Screenshot 2020-12-17 at 10 56 01](https://user-images.githubusercontent.com/6804901/102472367-881e8a00-4056-11eb-9841-58f1470185c0.png)

- [x] I don't think the path should appear outside of the detailed view:

<img width="337" alt="Screenshot 2020-12-17 at 16 56 17" src="https://user-images.githubusercontent.com/6804901/102511268-df3d5280-4088-11eb-92ee-57a185330633.png">

- [ ] For HDAs I think we'd want to have the eye icon visible even on the collapsed dataset view
<img width="801" alt="Screenshot 2020-12-17 at 16 57 48" src="https://user-images.githubusercontent.com/6804901/102511375-0005a800-4089-11eb-9c0f-7585a9c9ccc1.png">

- [x] The order of icons under dataset details could use reordering to reflect common usage, plus they are bunched a bit too closely together with icons being a tad too small. 
Current order: 
![image](https://user-images.githubusercontent.com/338642/102556295-8eccf180-4096-11eb-899d-1b5c565362fa.png)
More intuitive order:
![image](https://user-images.githubusercontent.com/338642/102556312-97252c80-4096-11eb-98a2-10cb1b530e76.png)
- [ ] Anonymous histories don't have an option to use the beta history panel.
- [x] ClickToEdit shouldn't just close editing mode because a different value sits there for a second. Seems like requiring the user to hit enter or something would be more usable - also it makes automated testing trickier than it should be.

**Comment by jmchilton** [comment]
"Advanced Searching" filters (https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/history/tutorial.html) don't seem to work. Am I doing it wrong, is it a TODO, or are we dropping it?

**Comment by jmchilton** [comment]
```diff
diff --git a/client/src/components/History/ContentItem/Dataset/DatasetMenu.vue b/client/src/components/History/Conten
index 52f1f179f7..0316c60314 100644
--- a/client/src/components/History/ContentItem/Dataset/DatasetMenu.vue
+++ b/client/src/components/History/ContentItem/Dataset/DatasetMenu.vue
@@ -34,7 +34,7 @@
         <PriorityMenuItem
             v-if="expanded"
             key="edit-tags"
-            title="Edit History Tags"
+            title="Edit Dataset Tags"
             :pressed="showTags"
             @click.stop="$emit('update:showTags', !showTags)"
             icon="fas fa-tags"
```

**Comment by astrovsky01** [comment]
Deleted collections update the shown/deleted/hidden incorrectly— it shows the total history items + collection deleted, but adds the total files not including collection to hidden, and they do not show up when specified to be shown


<img width="291" alt="Screen Shot 2020-12-17 at 4 42 39 PM" src="https://user-images.githubusercontent.com/40246333/102561631-05afbd80-408a-11eb-86c5-2f3386346c42.png">
<img width="291" alt="Screen Shot 2020-12-17 at 4 42 47 PM" src="https://user-images.githubusercontent.com/40246333/102561637-08121780-408a-11eb-88d0-914492e1f682.png">

Individual deletions increment properly. though

**Comment by astrovsky01** [comment]
Clicked option help bubbles stay up until clicked away, even when hovering over other options:
<img width="303" alt="Screen Shot 2020-12-17 at 5 12 53 PM" src="https://user-images.githubusercontent.com/40246333/102562194-65f32f00-408b-11eb-9604-7dbe60278c63.png">

Also, is there a way to hide a dataset without going into multiple dataset operations? Or temporarily make hidden datasets viewable without either a) making them all unhidden completely or b) going through the filter and making *only* the hidden datasets viewable?

**Comment by Nerdinacan** [comment]
> "Advanced Searching" filters (https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/history/tutorial.html) don't seem to work. Am I doing it wrong, is it a TODO, or are we dropping it?
> 
> Update: Actually hid is working, maybe it is just format?

I didn't mean to drop that, but I totally did. I think I completely forgot about it. We can add it in though without too much pain. I think we just need to modify SearchParams and the two functions that respectively turn SearchParams into a pouchDB query and a URL for the api.

**Comment by Nerdinacan** [comment]
> "Advanced Searching" filters (https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/history/tutorial.html) don't seem to work. Am I doing it wrong, is it a TODO, or are we dropping it?
> 
> Update: Actually hid is working, maybe it is just format?

I did not intend to drop that functionality, I DID, however, completely forget about it. It shouldn't be that hard to add in. There is an explicit SearchParams object that currently just has the one text field. We need to modify that, and the two functions that respectively turn those params into a query for PouchDB and a url for the ajax loader.

**Comment by hexylena** [comment]
@mvdbeek pointed me to the demo on test and it's so exciting! I love being able to rename things directly in the history interface, it's a game changer for me. The filtering under a button will prevent SOOO many complaints during training, I'm so excited. It fixes a longstanding bug I've had. 

bigger:

- [ ] name tags do not show up without editing the dataset's tags.
- [ ] I really struggle with this share icon, I know it's been discussed before but this one I really struggle to connect with the meaning "share". Googling for "share icon" literally everything is 3 dot android one, or the curvy arrow right.
- [ ] the click targets are so tiny. I'm struggling to get the correct history action. same for datasets.

smaller:
- [ ] history tagging feels very laggy, is there a chance these components can be instantaneous / and sync in background?
- [ ] same with editing the annotation, at first the responses were so slow I could leave the box and all the contents would disappear. Not sure how to repro some of this though :/ 
- [ ] made a history annotation, tabbed, it saved. Tried to delete that (just enter, backspace, tab to exit.) would not save.
- [ ] tool help button seems nonfunctional? (at least on an uploaded dataset.)
- [ ] Not clear why I can't close the filter (it was because I had filters applied.)
- [ ] Shows "matches N" even when filter isn't applied.
- [ ] "Select History" dropdown, is that a quick switcher? Maybe retitle it "Switch to recent history" or so?

**Comment by Nerdinacan** [comment]
@hexylena Thanks for reviewing! It's still pretty rough yet, let me try to address some of your concerns though.

**Tiny Click Targets on buttons**
I agree. I was explicitly trying to re-use bootstrap's buttons for conformance reasons, but those canned button components are pretty lousy on these small menu bars. They really just need to be simple hover-state graphics. I'll rework it to make them simpler.

**Tags sluggish, tags, wierd, etc.**
I have a complete rewrite of the tag editor on deck. I will make sure to reference these issues when it's ready.

**Annotation/Name slow to update**
Yep, the way it currently works, it's waiting for confirmation from the server to update the "non-editable" view, so you hit "save" and it goes to the server and you watch it change, which is good for validation purposes, but a weird user experience. I'll see what I can do.

"Select History"
Select History is supposed to be a quick-switcher, yes. A dropdown list of your histories that changes the current history in the side panel. Changing a title like this is pretty easy, I invite you to make any cosmetic text changes you like with a quick PR.

Thanks again. I have a kinda big bug-fix update coming that will likely address some of the other problems you noticed, and some you didn.t

**Comment by hexylena** [comment]
@Nerdinacan I didn't actually expect a response, wow, thanks :) Everything sounds good!

I think there's been some discussion in the past of similar "synced" components like that. I think anton made a comparison at one meeting of the whole validation cycle feeling slow for deleting many datasets in the history, vs other webapps that do optimistic updates.

But super cool to see, I look forward to the next iteration!

**Comment by mvdbeek** [comment]
@Nerdinacan Now that this is live on usegalaxy.org I had another look at large histories. The scrolling isn't usable there. Maybe this is is because of large gaps in the visible hids ?
<img width="351" alt="Screenshot 2021-03-16 at 12 40 56" src="https://user-images.githubusercontent.com/6804901/111303489-e1498a00-8654-11eb-9e23-5eabc471df98.png">
There's plenty of collections below that, but I can't navigate there.

**Comment by jkh1** [comment]
Following up from #11632. The history content doesn't appear in the history panel on Firefox (but does when using Opera). This doesn't appear to be a cache problem (starting with an empty cache or clearing the cache is no fix) but I see the following errors in the console:
```
A mutation operation was attempted on a database that did not allow mutations. CacheWorker.worker.bundled.worker.js:10:55934
    I https://usegalaxy.eu/static/dist/CacheWorker.worker.bundled.worker.js:10
    onerror https://usegalaxy.eu/static/dist/CacheWorker.worker.bundled.worker.js:10
error in cache$ indexed_db_went_bad: unknown ContentProvider.js:75:40

```
Finally some UX comments: bring back some of the menu icons next to the history name and out of the dots menu. It is annoying to have to go inside a menu when one just wants to quickly browse the content of a few files. And the icons at the top of the panel and the top of the history are too small and packed together increasing the likelihood of fat fingering an unwanted option.

**Comment by jkh1** [comment]
The error is caused by the privacy settings of Firefox, more precisely when it is set to not remember history.

**Comment by Nerdinacan** [comment]
> @Nerdinacan Now that this is live on usegalaxy.org I had another look at large histories. The scrolling isn't usable there. Maybe this is is because of large gaps in the visible hids ?
> <img alt="Screenshot 2021-03-16 at 12 40 56" width="351" src="https://user-images.githubusercontent.com/6804901/111303489-e1498a00-8654-11eb-9e23-5eabc471df98.png">
> There's plenty of collections below that, but I can't navigate there.

@mvdbeek 

Yup. I've been looking at nothing but this kind of thing for the past two weeks. I will update you when I have progress, which I believe will be very soon. I have one PR (the bulk selection) which I believe I have to split in 2 because a lot of it has turned into a testing/performance review on the HistoryContentProvider for exactly the reasons you are mentioning.

**Comment by Nerdinacan** [comment]
> The error is caused by the privacy settings of Firefox, more precisely when it is set to not remember history.

I confess I didn't try using this with FF's privacy mode. 

But it might be possible to not use IndexDB for the cache. PouchDB has several cache provider options, maybe we can just use "memory" when IndexedDB is not available due to FF's security policies. I'll see if it even works first, but if it does then what will happen is the "cache" will simply be memory-based for when you're in private browsing mode, but it will use the indexedDb file tables when that's available.

I think that might be the best we can hope for if Firefox has decided that IndexDB is a security risk.

**Comment by Nerdinacan** [comment]
@hexylena 

> I'm back with more thoughts.
> 
> **Bug**
> 
> On small widths it has a bad z-index and gets cropped.
> ![image](https://user-images.githubusercontent.com/458683/110605887-dfca1e80-8189-11eb-8e6f-611745c32ac7.png)
> 
> **Opinion**
> Overall the new iconography for the history panel bothered me a bit and I struggled to articulate why, but I think I can write something coherent now....

I was hoping one of the other devs would take a swing at modifying the cosmetics of the new components, but nobody has bothered to try yet. 

I'm certainly not married to the icons, but what I was trying to give us was what's called a "priority menu" in design circles. It means the important stuff appears as icons (important meaning closer to the top of the list) and the rest appear on the dropdown, and it updates itself based on the amount of horizontal room that is available. You make stuff more "important" by putting it closer to the top of the list. Then it's more likely to end up as an icon (width permitting).

All we need to do to reduce the icon-zoo is simply give the menus less horizontal room with a couple lines of css. The components I built will literally do the rest for you.

I do agree with you that there's a lot of weird little niche options available on the menus. Some of that I hope to clean up with the bulk operations PR which I think reduces the need for a bunch of seemingly redundant options by reinterpreting what a "selection" means inthe UI. 

That's one of 2 big things I'm juggling right now. The explanation of what I want to try with bulk operations is here:
https://github.com/galaxyproject/galaxy/pull/11436

I hope to return to that very soon as I resolve the scrolling issues others also noted in this thread. (Today I hope!) 
Those two things are related in subtle ways and it will be easier to do the scrolling fix first, then the bulk operations menu. 

If those both work out will be then be less menu items to worry about and we can all complain about icons until we get tired. :)

Thanks!

**Comment by hexylena** [comment]
Just getting around to respond to this.

## priority menu

yeah, that definitely makes sense! I like it in theory, just in practice it seems to be a lot of irrelevant icons and that they move around which will present UX issues for non-experienced users.

>  All we need to do to reduce the icon-zoo is simply give the menus less horizontal room with a couple lines of css. The components I built will literally do the rest.

fantastic! thanks for writing easy to work with components :) If I could be so bold as to suggest the icons that should appear always, with the rest in the menu, until it gets too small.

- multi-history
  - I think this one is fine honestly. Those are all common actions, fine for them to be buttons at wide widths. Here I **really** like the priority menu.
- history
  - tag
  - annotate
  - maybe copy.
- history filters
  - multiselect
  - filter
- datasets
  - view data (this is the most important one for us. I'm ok to lose the pencil/delete, but not the eyeball.)
  - maybe pencil?

I'm worried about the usability of this a lot for new users.

## Double clicking

Lots of our users aren't super computer literate, and here's the issue:

> If you double click in the wrong place to open a dataset you can immediately delete it before you understand what happened

I can promise this will happen on a regular basis given the folks I've watched use galaxy. I'm not sure how to fix this. maybe make it one of the always shown icons to help prevent? Is there a way the icons can appear somewhere below the name, rather than at the top?

> The choice to split the menus up was partially technical and partially logical

this definitely makes sense to me. From someone who is familiar with the underlying objects, I can definitely appreciate it, I think this change I can definitely get used to. 

> I think the 3 main domains "History list, history object header, current selection" need more visual distinction.

agreed! I wonder if there's some visual distinction we can give to the dropdown menus as well? There's three identical buttons nearby, I can imagine this being painful for training. (even just colours?)

![image](https://user-images.githubusercontent.com/458683/114013285-a5769e80-9867-11eb-8dfa-ff7bfed71c5c.png)

I look forward to #11436 !

**Comment by mvdbeek** [comment]
Nested Collections can be navigated to, but the individual datasets can't be expanded or viewed.
You can test this with `collection_creates_dynamic_nested ` when you start Galaxy with the test tools (`GALAXY_CONFIG_OVERRIDE_TOOL_CONFIG_FILE="test/functional/tools/samples_tool_conf.xml"`).

![expand nested collection](https://user-images.githubusercontent.com/6804901/115033231-7943c900-9eca-11eb-95cd-f985672c523a.gif)

**Comment by Nerdinacan** [comment]
> collection_creates_dynamic_nested

@mvdbeek 
I am seeing this. Even weirder, I'm seeing that the new collections only sometimes appear in the request. Will look at this next.

**Comment by Nerdinacan** [comment]
> I can promise this will happen on a regular basis given the folks I've watched use galaxy. I'm not sure how to fix this. maybe make it one of the always shown icons to help prevent? Is there a way the icons can appear somewhere below the name, rather than at the top?

The right answer for that is usually a confirm prompt, either an explicit modal or just a basic HTML confirm ok/cancel.

**Comment by hexylena** [comment]
> confirm prompt ... [enforced selection]

Both of those are understandable but sound like negatives from the ease-of-use perspective. Is it such a negative to have the delete/view buttons always visible? but both alternatives are more clicks than it used to be for an action I don't feel is so rare in my day to day use. (Key word there is 'feel' i guess, I recognise I'm a bit biased here for how things used to be. that said I'm still super excited for the rename-in-dataset, fewer clicks there is so nice.)

**Comment by Nerdinacan** [comment]
> > confirm prompt ... [enforced selection]
> 
> Both of those are understandable but sound like negatives from the ease-of-use perspective. Is it such a negative to have the delete/view buttons always visible? but both alternatives are more clicks than it used to be for an action I don't feel is so rare in my day to day use. (Key word there is 'feel' i guess, I recognise I'm a bit biased here for how things used to be. that said I'm still super excited for the rename-in-dataset, fewer clicks there is so nice.)

Ahhh I misread your issue. Sure we can see about having the menu always show important buttons. I just noticed that the current CSS is jamming it all in the corner there when it's collapsed.

**Comment by nsoranzo** [comment]
I'll add here a couple of paper-cut issues I noticed, but let me know if a separate issue would be better:

- In the old history panel, to edit the annotation of a dataset or of the whole history you first had to click the speech balloon icon. In the new panel, this is needed only to edit the annotation of the whole history, while for datasets a placeholder "Edit annotation..." is shown. These should be synced one way or the other.
- Editing a dataset annotation: if I expand a dataset in the history panel and click on "Edit annotation...", it doesn't close if I click outside of it, while this does work for the dataset name.

**Comment by jmchilton** [comment]
If you click into collections, tags can be rendered but they aren't added correctly.

```
libs.chunk.js?v=1625019660:sourcemap:55 Error: missing contents_url
    at d.value (DatasetCollection.js:15)
    at new e (ModelBase.js:10)
    at d.<anonymous> (analysis.bundled.js?v=1625019660:28)
    at new n (ModelBase.js:27)
    at d.<anonymous> (analysis.bundled.js?v=1625019660:28)
    at new c (Content.js:13)
    at d.<anonymous> (analysis.bundled.js?v=1625019660:28)
    at new d (DatasetCollection.js:11)
    at a.dsc (DscProvider.js:36)
    at hn.get (libs.chunk.js?v=1625019660:sourcemap:7)
    at hn.evaluate (libs.chunk.js?v=1625019660:sourcemap:7)
    at a.dsc (libs.chunk.js?v=1625019660:sourcemap:7)
    at a.render (DscProvider.js:92)
    at a.t._render (libs.chunk.js?v=1625019660:sourcemap:7)
    at a.r (libs.chunk.js?v=1625019660:sourcemap:7)
    at hn.get (libs.chunk.js?v=1625019660:sourcemap:7)
    at hn.run (libs.chunk.js?v=1625019660:sourcemap:7)
    at fn (libs.chunk.js?v=1625019660:sourcemap:7)
    at Array.<anonymous> (libs.chunk.js?v=1625019660:sourcemap:7)
    at Yt (libs.chunk.js?v=1625019660:sourcemap:7)
```

This along with the aforementioned issues around renaming usability I think are the biggest blockers to porting the tests. You also cannot un-annotate histories - if you clear the textbox corresponding to an annotation it doesn't clear out the old annotations. I found a work around in Selenium for changing annotations but fixing the underlying issue would be nice.

**Comment by dannon** [comment]
Looks like everything in this has been addressed in the latest revisions of the new history.
