### ISSUE TITLE
Incorrect processing of config options set to a list of paths

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#10942]
Setting `tool_data_table_config_path` to a list of values causes an error like this one:
```
OSError: Error reading file '/home/sergey/0dev/galaxy/_galaxy/dev/config/['tool_data_table_conf.xml'': failed to load external entity "/home/sergey/0dev/galaxy/_galaxy/dev/config/['tool_data_table_conf.xml'"
```
The cause for the error is incorrect path processing in the config module. This may or may not affect other config options.

**Comment by ic4f** [comment]
Also, need to check whether this is related to processing of YAML list values in general (ref: `admin_users` issue discovered during admin training in Barcelona, 2020) - i.e., is the cause related to processing of paths, or processing of list parameters?
