### ISSUE TITLE
[20.09] Change tool output datatype ignored

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#10958]
In a workflow, changing a tools output type has no effect.

![image](https://user-images.githubusercontent.com/1768820/102526938-417a6100-4051-11eb-9459-04d751aedeb1.png)

[Galaxy-Workflow-Unnamed_workflow.ga.txt](https://github.com/galaxyproject/galaxy/files/5711380/Galaxy-Workflow-Unnamed_workflow.ga.txt)

Related: https://github.com/galaxyproject/galaxy/issues/10228

**Comment by mvdbeek** [comment]
That workflow works fine for me and produces a newick output.
