### ISSUE TITLE
Add support to Plausible

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#10954]
[Plausible](https://plausible.io/) is a privacy-friendly alternative to Google Analytics (GA). During a discussion on the admin Gitter channel, @hexylena suggested we could add support for it in addition to GA.

**Comment by hexylena** [comment]
Tagged paper cut, it should be pretty easy. Copy and paste the google analytics but with plausible URL.

**Comment by selten** [comment]
Maybe also add support for [matomo](https://matomo.org/) so there is an option to host it yourself instead of relying on a 3rd party.

**Comment by hexylena** [comment]
Plausible is self hosted, fwiw.
https://plausible.galaxyproject.eu/training.galaxyproject.org

selten <notifications@github.com> schrieb am Do., 11. Feb. 2021, 22:25:

**Comment by nsoranzo** [comment]
Fixed in #11351.
