### ISSUE TITLE
Workflow invocation problems with large collections

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#10966]
Since over a week I'm struggling to get one of my WFs running on .eu. Various versions of the WF (https://usegalaxy.eu/workflow/export_to_file?id=adb3676c3450a227) give invocation failures with tracebacks like https://gist.github.com/bgruening/fc6767ddaf93fd4d9db0d00c45315b19

The exact evaluation problem (and the step at which invocation fails) usually changes when I modify the WF, but so far I haven't found a version that could be invoked successfully on .eu.

The issue only occurs if the WF is run with large enough collections (over 100 samples) and I'm not even sure whether it's a Galaxy core problem or a scheduling configuration issue on .eu, but if somebody could take a look it would be highly  appreciated and I'd be willing to help debugging.

**Comment by mvdbeek** [comment]
Hmm, maybe this is `maximum_workflow_jobs_per_scheduling_iteration`, which defaults to 1000 since 20.09. Any chance you could bump that upat .eu  temporarily ?

**Comment by wm75** [comment]
My vague impression from observing the scheduling dynamics on .eu is actually that scheduling of collections interferes somehow with scheduling of regular jobs with simple dataset inputs (the evaluation problem in the traceback also seems to refer to the output of a step that's not dealing with collections).

Going to rerun with increased `maximum_workflow_jobs_per_scheduling_iteration` now though.

**Comment by wm75** [comment]
So increasing `maximum_workflow_jobs_per_scheduling_iteration` to 2000 gave successful scheduling of the WF.
I'm a bit sceptical still whether that fixed the underlying issue though:
My suspicion is that the **root** cause of the whole issue is that this WF is branched and that the scheduling of simple jobs in one branch interferes with simultaneous scheduling of collections in the other branch. Now what happened with the new setting was that somehow the two branches got scheduled sequentially, i.e. the steps from one branch only got scheduled after all steps from the other branch had been scheduled successfully.

**Comment by mvdbeek** [comment]
Yeah, that makes some sense to me, and that gives me a good angle to look into what's going on there. I don't quite see how the branched progress could influence another branch, but that would explain why I haven't been able to reproduce other reports.
