### ISSUE TITLE
Workflow editor bug: step copy duplicates Label/Annotation fields

### ISSUE THREAD

**Issue by cgirardot** [galaxyproject/galaxy#10979]
Since the last version, the copy step function in the workflow editor behaves weirdly. 

How to reproduce:
- create a simple WF : input -> bowtie2 -> bamCoverage 
- give a label to the `bamCoverage` step
- save, close and re-open (important as it seems that the bug is not present when the WF was never saved&closed)
- click the duplicate button on `bamCoverage` step

<img width="1136" alt="wf_copy_bug" src="https://user-images.githubusercontent.com/10990795/102781477-08672700-4398-11eb-8b38-3eed149c2264.png">

**Comment by wm75** [comment]
#11287 occurs under somewhat different circumstances, but seems likely to be the same issue

**Comment by wm75** [comment]
Was misreading the desciption above. #11287 is a true duplicate
