### ISSUE TITLE
Workflow editor bug : number of output datasets  in right panel does not update with selection

### ISSUE THREAD

**Issue by cgirardot** [galaxyproject/galaxy#10978]
I am using the `rename` feature extensively in my WF. Since the last release (at least), the right panel does not update the output datasets upon option selection. For example, in the bowtie2 tool, the user can optionally ask for the unaligned reads to be generated or a mapping stats report to be created. When doing so, the right panel does not reflect the selection (as shown on the screenshot). One needs to save, close and reopen the WF.

<img width="1082" alt="Screenshot 2020-12-21 at 14 07 00" src="https://user-images.githubusercontent.com/10990795/102780496-50854a00-4396-11eb-820c-ac303f011ac7.png">

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11602
