### ISSUE TITLE
Option to add data sets "from user directory" in 20.09

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#10982]
Seems that on 20.09 the the menu in the shared libraries view does not contain: 

```
Add Data Sets -> From User Directories
```

Was working before and as far as I can see my configuration did not change in this respect.

**Comment by bgruening** [comment]
We need to add also a test for this, so it never gets dropped again.

**Comment by bgruening** [comment]
ping @OlegZharkov

**Comment by OlegZharkov** [comment]
This should've been fixed already. Are you sure that everything is up to date? Otherwise, what do you see in your `metadata` in `http://localhost:8080/api/folders/{folder_id}/contents`?

**Comment by bernt-matthias** [comment]
This may be true. I'm on 845419b210cfc394b960df1947468b4f6a103d91 from Nov 29th. I will try to update and check.

**Comment by bernt-matthias** [comment]
The option is back after the update. Thanks for your feedback.

**Comment by bernt-matthias** [comment]
Hah. Option was only back for my user (which is an admin), but not as a regular user (at least when I impersonate this user). 

Might it be that I need to rebuild the client?

**Comment by OlegZharkov** [comment]
> Hah. Option was only back for my user (which is an admin), but not as a regular user (at least when I impersonate this user).
> 
> Might it be that I need to rebuild the client?

if it's still not shown, then back-end probably returns `can_add_library_item: false`
if you open `http://localhost:8080/api/folders/{folder_id}/contents` what is  the value of `metadata` -> `can_add_library_item` ?

**Comment by bernt-matthias** [comment]
`can_add_library_item` is `true`

**Comment by OlegZharkov** [comment]
> `can_add_library_item` is `true`

This is very weird. Are you sure that you impersonated as a regular user?

**Comment by bernt-matthias** [comment]
> This is very weird. Are you sure that you checked this as a regular user?

100%
