### ISSUE TITLE
20.09 regression: Data Type column missing/replaced in data library UI

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#10997]
In 20.05 the data library UI had a `Data Type` column (e.g. https://usegalaxy.fr/library/list#folders/Fb58ecc291a94c03f from usegalaxy.fr which is still at 20.05) which made it possible to sort datasets by format. For folders the value of this column was `folder`.
In 20.09 this was replaced by the `Type` column (e.g. https://usegalaxy.eu/library/folders/Fa21272e5bd712216 ), which is just either `folder` or `file`, basically redundant with the icon on the very left of each line.

Can we have the data type back please?

Ping @OlegZharkov

**Comment by OlegZharkov** [comment]
@nsoranzo
thanks for reporting!
