### ISSUE TITLE
Data library: no change in number of displayed elements

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy#11002]
Hi,

I tried to display all elements of a data library (28 in total) in a page by changing the number on the bottom. But increasing the number did not change the number of displayed elements (still 15) and I can not access anymore the 2nd page (so all elements)

![Screenshot 2020-12-28 at 10 24 16](https://user-images.githubusercontent.com/1842467/103204415-9e023980-48f7-11eb-93cb-db687030cd96.png)

---

Details
- Server: usegalaxy.eu
- Browser: Firefox 84.0

**Comment by bgruening** [comment]
ping @OlegZharkov

**Comment by OlegZharkov** [comment]
Sorry, I've changed the page surfing mechanism with pagination. So it turns out  that I forgot to watch for this value change. Sorry, my fault and thanks a lot for reporting!
