### ISSUE TITLE
UI: Available tool versions should be sorted from latest to oldest

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#11004]
In the tool form, the Versions button allow to select a different version of the tool to be used. The dropdown list of available tool versions is presently sorted from the oldest (on top) to the latest (at the bottom), I think it should be the inverse, so that newer versions are closer to the button.

**Comment by cat-bro** [comment]
having a look at this for papercuts

**Comment by mvdbeek** [comment]
Done in https://github.com/galaxyproject/galaxy/pull/11490
