### ISSUE TITLE
Can galaxy allow all users to access, but only the registers can upload data or run jobs?

### ISSUE THREAD

**Issue by shenweiyan** [galaxyproject/galaxy#11014]
Can the Galaxy instance allow all users(anonymous and registered) free to browse around and see what's available without registering, but only the registers can upload data or run jobs? 

I only see `require_login` and `user_activation_on` parameter in galaxy.yml, but none of them can satisfy this.

**Comment by bgruening** [comment]
@shenweiyan you can set `limits` in your job_conf.xml file and configure resources for users that are not registered.
Can you please use help.galaxyproject.org, gitter or our mailing list for such questions?
