### ISSUE TITLE
login required, but still view static/welcome.html

### ISSUE THREAD

**Issue by ghost** [galaxyproject/galaxy#1104]
We want folks to see static/welcome.html when they first come to our instance, but must login to use any tools. We set "require_login = True", but this means the site first shows "This Galaxy instance has been configured such that only users who are logged in may use it." instead of static/welcome.html. It would be nice to able to display the welcome text to folks just visiting our server (or stumbling upon it) but restrict use to  validated users.

**Comment by hexylena** [comment]
I'd :+1: this suggestion, we had similar problems with advertising with just a "login required" page. People had to know the resource was there before getting over the energy of activation to actually give their email to a random internet service.

**Comment by guerler** [comment]
:+1:

**Comment by guerler** [comment]
This here might be a solution: https://github.com/galaxyproject/galaxy/pull/1105
