### ISSUE TITLE
Feature request: create an admin user to go with the master_api_key

### ISSUE THREAD

**Issue by cyrilcros** [galaxyproject/galaxy#11065]
Would it please be possible to create a dedicated admin user to go with the `master_api_key`? 
Because it has no associated user, using it to control the api often triggers bugs like https://github.com/galaxyproject/galaxy/issues/10178 or https://github.com/galaxyproject/galaxy/issues/6699 .  I myself got the same error code while trying to use the API to upload a dataset, on the server side the trace was `lib/galaxy/model/security.py` line 757 `user_get_default_permissions`: https://github.com/galaxyproject/galaxy/blob/594f826a86f169ddb238567ddb61ce4260d2f25c/lib/galaxy/model/security.py#L753
It is called by `tools/actions/upload_common.py` with `trans.user=None` in the case of the `master_api_key`: https://github.com/galaxyproject/galaxy/blob/594f826a86f169ddb238567ddb61ce4260d2f25c/lib/galaxy/tools/actions/upload_common.py#L196

Creating some sort of system user with admin permission would fix a wide class of API errors that are not properly caught right now when using the master key. The current work around seems to be to specify an admin user account with a bogus email, create a matching user via the master api key and then use that new admin API key. That's annoying and I can't see how it is different in terms of security.

**Comment by nsoranzo** [comment]
@cyrilcros Thanks for opening this issue! We discussed your suggestion and prefer to not implement it, the intended use case of the master API key is only to bootstrap a server, in particular to create a real admin account. I've tried to clarify that in https://github.com/galaxyproject/galaxy/pull/11067 .
Hopefully that's not a big deal for you.

**Comment by cyrilcros** [comment]
@nsoranzo Thanks, that does make sense.
