### ISSUE TITLE
DataSource tools broken on Chrome due to SameSite cookie attribute

### ISSUE THREAD

**Issue by ericenns** [galaxyproject/galaxy#11066]
DataSource tools are broken on Chrome >=84 no longer sends cookies without `SameSite=None; Secure` in third party context (i.e. Post request from external site to galaxy). Firefox and Edge has not yet made this default behaviour and I am unsure of Safari.

Details on SameSite cookies can be found [here](https://web.dev/samesite-cookies-explained/).

To make DataSource tools work again you would have to add `SameSite=None; Secure` to the cookies generated by Galaxy, but this would only work on Galaxy instances which use SSL (Chrome ignores SameSite if Secure is missing from cookie).

To get this to work in Galaxy, python 3.8 is required to add `SameSite` attribute to cookie, on python 3.7 and later monkey patching is required. (https://stackoverflow.com/questions/50813091/how-do-i-set-the-samesite-attribute-of-http-cookies-in-python/50813092#50813092)

Just adding `SameSite=None; Secure` could break functionality on older browsers (https://www.chromium.org/updates/same-site/incompatible-clients).

**Comment by mvdbeek** [comment]
Pushing this, but this one is a high-priority fix

**Comment by ic4f** [comment]
> Pushing this, but this one is a high-priority fix

I'll get to it this ASAP.

**Comment by ericenns** [comment]
Would this be better addressed by adding a one time auth token to the callback url, and using that to authenticate the request? We are still running into this issue with our IRIDA galaxy datasource tool and are unable to get our integration tests working as a result.

**Comment by mvdbeek** [comment]
It's a good idea and what I thought we should do initially, but in principle you should also be able to run the data source tools without first passing through the Galaxy link. We might just add `SameSite=None; Secure` for the tool_runner prefix and see how far that gets us.
