### ISSUE TITLE
Inconsistent results of LDA effect size

### ISSUE THREAD

**Issue by zjb-xmm** [galaxyproject/galaxy#11070]
Hello,
First of all thank you for all of your hard work developing such an informative and intuitive tool. I have been successful in running the LEfSE analyses for some of my data, but unfortunately, for the same data, only the name of class is changed, and the LDA results are different.

Any guidance would be greatly appreciated.
all the best

**Comment by hexylena** [comment]
Hi @zjb-xmm, this is the repository for the Galaxy source code, not the tools or a particular server.

I'm afraid we cannot provide support for the LEfSE server, you will need to contact their admins.
