### ISSUE TITLE
Forms Modernization (WF and Tool) via Vueification

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#11076]
This is a large project, a bottom-up, incremental rebuild of the tool form that we can make progress on in chunks.

Q1 goal is *not to replace the entire thing*, but to identify the right strategy and start replacing form items.  These are widely used across the application and will require caution.

A nice perk is that this will enable us to elminimate select2, a lot more jquery, and use native vue components in many more places across the application that are tied to older code.

The most recently discussed approach:

> This issue can be approached from two sides in parallel. While one project can focus on replacing the Workflow Editor Form with a Vue Component which does not rely on the Form Base Extension, the second project may extend the `form-parameters.js` to allow embedding Vue components as Input elements.

<img width="915" alt="Screen Shot 2021-10-18 at 11 19 31 PM" src="https://user-images.githubusercontent.com/2105447/138784418-e41657c5-95c6-4e61-9477-4b7c891712c6.png">

**Comment by guerler** [comment]
#12227, #12031, #11898

**Comment by guerler** [comment]
List of remaining Backbone based input elements:
See `parameter.js` for more details.

- [] text, password: "_fieldText"
- [] select, data_column, genomebuild, group_tag: "_fieldSelect"
- [] data, data_collection: "_fieldData"
- [] integer, float: "_fieldSlider"
- [] drill_down: "_fieldDrilldown"
- [] color: "_fieldColor"
- [] library_data: "_fieldLibrary"
- [] ftpfile: "_fieldFtp"
- [] upload: "_fieldUpload"
- [] rules: "_fieldRulesEdit"
- [] directory_uri: "_fieldDirectoryUri"
- [] data_dialog: "_fieldDialog"

**Comment by OlegZharkov** [comment]
thx Sam. I will be on `colour`

**Comment by dannon** [comment]
I converted the remaining individual parameters to issues and linked them up above.
