### ISSUE TITLE
RStudio Active Interactive Tool not starting in the EU instance

### ISSUE THREAD

**Issue by fpsom** [galaxyproject/galaxy#11081]
Hi all!

I’ve been encountering the following issue with the RStudio Active Interactive Tool, as accessed through the https://usegalaxy.eu/ instance. Although it seems to start correctly (see screen 1), it appears to be constantly “restarting” (at least the job on the history is “blinking” every few seconds). At the same time, it’s listed as stopped (but feels more like a “zombie” to me - see screen 2).

- screen 1
![screen1](https://user-images.githubusercontent.com/1426106/103991805-ddecda80-519b-11eb-8adc-a8f05eafc54b.png)

- screen 2
![screen2](https://user-images.githubusercontent.com/1426106/103991811-e218f800-519b-11eb-83db-99f9759c550e.png)

I may be doing wrong, but any ideas / suggestions would be very welcome! Thanks!

**Comment by bgruening** [comment]
I can reproduce it and will look into it. I Will close it as this is an EU-specific issue. Thanks @fpsom for reporting.

**Comment by hexylena** [comment]
@bgruening why don't we just transfer it? One sec :)
