### ISSUE TITLE
Option to disable tool cache

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#11082]
We do want to be able to disable the tool cache if it causes trouble. 21.01 has some improvements to xml macro parsing, so even without the cache loading is should be reasonably fast.

**Comment by bgruening** [comment]
That would be nice. EU has still memory issues every week we update our tools, e.g. when a lot of tool installation happens.

**Comment by mvdbeek** [comment]
Can't exclude it, but it would be a big surprise if the cache has any impact on memory.
