### ISSUE TITLE
Workflow tagging - unclear where to click

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11090]
It's just whitespace, I think it would benefit from being more like the textboxes where it's clear there's a component to click on.

![image](https://user-images.githubusercontent.com/458683/104165675-040fb600-53fa-11eb-8d25-f172887aee25.png)

**Comment by OlegZharkov** [comment]
Hi @hexylena,

I cannot reproduce, I see a tag icon there. Where do you encounter this?
![image](https://user-images.githubusercontent.com/15801412/114877809-5355f000-9e08-11eb-820a-26dc82cd3ee7.png)

**Comment by hexylena** [comment]
This looks resolved, you're right! Nice.
