### ISSUE TITLE
Improve job/workflow handler management

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#11119]
With the upcoming move to fastAPI/uvicorn/gunicorn away from uwsgi we likely need a way to manage handlers (which was previously done by uwsgi, at least for mules).

@natefoo's wishlist looks like this:
- If using db-preassign (there are defined <handler> tags and no assign_with attribute on <handlers>), start the defined handlers
- If using db-skip-locked (no defined <handler>tags orassign_with="db-skip-locked`) we will need some config option to say "start N handlers"
- Start whatever handler(s) and workflow scheduler(s) should be started based on the config
- Signal to stop and wait for clean termination (it's currently configurable and can be quite long)
- Force terminate if clean termination times out
- Restart processes if they die unexpectedly (preferably with a backoff if they fail too quickly too many times in a given time period)

**Comment by mvdbeek** [comment]
@dannon suggested we could look at http://garywiz.github.io/chaperone/guide/chap-intro.html. An alternative might be https://circus.readthedocs.io/en/latest/, which using zeromq for IPC. We should probably check out both -- I think both could do what we want, although chaperone does come with some warnings about running in userspace, while zeromq could potentially be quite interesting for multi-node setups.

**Comment by mvdbeek** [comment]
Just putting that here:
mvdbeek
awesome, kill -USR2 <master_pid> starts up a new master, while the old one stays alive, so when the new one is up you can kill the old one and you did a zero downtime restart
that's with gunicorn
I thought -HUP was supposed to behave that way (except it would kill the old processes automatically), but I guess I misunderstood
mvdbeek
Nice, kill -TTIN starts additional workers ... not that I can think of a reason to do it, but that's neat

That's for the web handlers

**Comment by mvdbeek** [comment]
Someone already did the scripting for us:
```
GALAXY_CONFIG_FILE=config/galaxy.yml unicornherder --pidfile herder.pid -- 'galaxy.webapps.galaxy.fast_factory:factory()' --pythonpath lib -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8080 automates the zero downtime restart dance
```
That's with https://github.com/alphagov/unicornherder

**Comment by natefoo** [comment]
So this is mostly done with Gravity now, but one thing that's sort of cumbersome is that defining dynamic handlers in the Gravity config doesn't automatically get them used as handlers (or rather, doesn't stop the gunicorn server from handling jobs) unless you explicitly set `assign: ['db-skip-locked']` in the `handling` section of the job config.

The [scaling docs](https://docs.galaxyproject.org/en/master/admin/scaling.html#job-handler-assignment-methods) need an update, but beyond that, maybe Galaxy should read the Gravity config and figure this out itself so you don't have to set it explicitly. I did add [a warning in Gravity](https://github.com/galaxyproject/gravity/blob/24ce6ac29bdef2384fbd51351116bc469ad2185f/gravity/config_manager.py#L245), but people using Ansible won't see this.

**Comment by natefoo** [comment]
Separate issue for the remaining bit: https://github.com/galaxyproject/galaxy/issues/15887
