### ISSUE TITLE
Cannot delete history from within history

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11127]
I'm pretty sure this used to be an option? But I don't see delete history in the history menu anymore and I miss it.

**Comment by mvdbeek** [comment]
That was a deliberate decision to make the cog menu more streamlined. I do agree though, in the same way I think it's unfortunate import history is not next to export history.

**Comment by mvdbeek** [comment]
The new beta history panel has a delete button though, so maybe we close this ?
<img width="285" alt="Screenshot 2021-01-14 at 11 52 58" src="https://user-images.githubusercontent.com/6804901/104581636-21918980-565f-11eb-8e8f-a268fb0e7f5c.png">

**Comment by hexylena** [comment]
20.09 specific missing feature, hah, ok, sounds good. If it'll be fixed in the next release that's fine for me.

**Comment by hexylena** [comment]
what's the hand shaking icon supposed to be? Don't tell me that's sharing?

**Comment by mvdbeek** [comment]
I think this has been gone for a year or more now?

**Comment by hexylena** [comment]
Guess I didn't use it that often :sweat_smile:

**Comment by mvdbeek** [comment]
Share-or-publish, yeah. If you wanna have a quick look, it's live on test.galaxyproject.org.

**Comment by mvdbeek** [comment]
(you'll start at the regular history panel, and in the cog menu you can switch to beta). There's a long list of issues already at https://github.com/galaxyproject/galaxy/issues?q=is%3Aissue+is%3Aopen+panel
