### ISSUE TITLE
Job stuck in new state

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#11146]
A problem on our 20.09 instance, when trying to run samtools stats from this covid-19 gtn tutorial: https://training.galaxyproject.org/training-material/topics/assembly/tutorials/assembly-with-preprocessing/tutorial.html#mapping-of-nanopore-reads

The (3) jobs are stuck in new state, looking like this in the history:

![image](https://user-images.githubusercontent.com/238755/104750574-94c8f780-5754-11eb-9c6f-a11463c0abcc.png)

In the logs I have 3 errors like this:

```
galaxy.web_stack.transport DEBUG 2021-01-15 16:38:33,341 [p:29115,w:0,m:1] [UWSGIFarmMessageTransport.dispatcher_thread] Released lock
galaxy.web_stack.transport DEBUG 2021-01-15 16:38:33,341 [p:29117,w:0,m:3] [UWSGIFarmMessageTransport.dispatcher_thread] Acquired message lock, waiting for new message
galaxy.web_stack.transport DEBUG 2021-01-15 16:38:33,342 [p:29117,w:0,m:3] [UWSGIFarmMessageTransport.dispatcher_thread] Received message: {"target": "job_handler", "params": {"task": "setup", "job_id": null}, "__classname__": "JobHandlerMessage"}
galaxy.web_stack.transport ERROR 2021-01-15 16:38:33,349 [p:29117,w:0,m:3] [UWSGIFarmMessageTransport.dispatcher_thread] Exception in mule message handling
Traceback (most recent call last):
  File "lib/galaxy/web_stack/transport.py", line 119, in _dispatch_messages
    self.dispatcher.dispatch(msg)
  File "lib/galaxy/web_stack/message.py", line 46, in dispatch
    self.__funcs[msg.target](msg)
  File "lib/galaxy/web_stack/message.py", line 147, in default_handler
    getattr(self, '_handle_%s_msg' % msg.task)(**msg.params)
  File "lib/galaxy/jobs/handler.py", line 823, in _handle_setup_msg
    if job.handler is None:
AttributeError: 'NoneType' object has no attribute 'handler'
```

After restarting the server the stuck jobs start and complete properly, but new ones will get stuck too until another restart.
Any clue on what's going on? (We plan to have a training session on this next tuesday :D)

**Comment by mvdbeek** [comment]
Do you have the logs for a few lines above this ? There should be something like `Added job to the job queue, id:` ?

**Comment by abretaud** [comment]
That was fast! Yes the patch works like a charm, thanks so much @mvdbeek !
Have a nice weekend!

**Comment by mvdbeek** [comment]
Thanks for the report @abretaud!
