### ISSUE TITLE
Integron_finder error 

### ISSUE THREAD

**Issue by nwalas** [galaxyproject/galaxy#11141]
Hi, 

My previous issue was closed but I never received an answer for my request? Sorry I'm on a bit of a time crunch.

____________
I am using the online galaxy interface for integron_finder, but when I run my fasta file I get a failed return with the following error.

Fatal error: Exit code 1 ()
Traceback (most recent call last):
File "/mount/gensoft2/exe/Integron_Finder/1.5.1/bin/integron_finder", line 1608, in
alphabet=Seq.IUPAC.unambiguous_dna)
File "/local/gensoft2/adm/lib/python2.7/site-packages/

How can this be fixed? 

Thank you,
Niko

**Comment by nsoranzo** [comment]
As mentioned in the previous issue you opened, this issue is not appropriate for this repository. Please get in touch with the admins of the Galaxy instance you are using.

**Comment by bgruening** [comment]
@nwalas can you mabe hint us in the direction which Galaxy server you are using?

**Comment by nsoranzo** [comment]
@bgruening It's Pasteur, see https://github.com/galaxyproject/galaxy/issues/11120

**Comment by bgruening** [comment]
Oh thanks ... I will try to contact a few people.

**Comment by nwalas** [comment]
Ahh I see okay, it wasn't clear to me in the previous response I needed to contact someone else directly. Thank you for the quick response Nicola! and thank you for offering your help too Björn!

Much appreciated
