### ISSUE TITLE
Design and implement process of tool deployment automation 

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1115]
## Automate tool deployment

I believe we have the most of the things we need to automate tool deployment on Galaxy servers using Ansible. We need someone to explore if that is true.
## benefits

This would make the toolset available on Main (and other servers using this) more transparent and useful to people that want to 'mirror Main'.
It would also lower our overhead of manging hundreds of tools manually through admin UI.
## relevant work 

from @afgane, @natefoo and others
https://github.com/galaxyproject/ansible-galaxy-tools
https://github.com/afgane/galaxy-tools-playbook
## basic outline: 

You have a tool.yaml file (https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/tool_list.yaml.sample) stored publicly which is initially prefilled with all the tools and versions installed on the instance (can use publicly available shed_conf.xml and other configs to create this). 
Changing this file and running the relevant Ansible playbook would result in the relevant tools being installed on the given instance. This playbook would probably be connected to the usegalaxy-playbook run so it would propagate the mutable configurations as one of the steps.
All that would be left is to manually restart nodes.

bonus: 
- The logs created during the installation could probably be made available.
- Sending a summary email to -lab or -commiters of what got installed/uninstalled.
- Create a 'Main toolset diff' to be included in the release notes.

**Comment by hexylena** [comment]
+1000.

**Comment by afgane** [comment]
I believe the main outstanding issue here for Nate that paused further
integration into the usegalaxy-playbook was logging, which wasn't native to
the role, so I'd say we should focus on that first.

**Comment by mvdbeek** [comment]
As demanded by @martenson , here is a small script to recover a tool_list.yml from a running galaxy instance (needs admin api key). this is WIP.
https://github.com/ARTbio/tools-artbio/blob/master/helper_scripts/get_tool_yml_from_gi.py

**Comment by martenson** [comment]
Thank you @mvdbeek !

**Comment by afgane** [comment]
On the @natefoo's [issue of supporting native logging](https://github.com/galaxyproject/ansible-galaxy-tools/issues/2#issuecomment-130752007) in the Ansible role/playbook - does anyone have any pointers on how to do this?
It seems Ansible does not and will not support [task output streaming](https://github.com/ansible/ansible/issues/3887#issuecomment-54672569), which means we cannot just link to the installation script log to get interactive feedback about the tool installation progress. 
I guess we could redo [the tool installation file format](https://github.com/galaxyproject/ansible-galaxy-tools/blob/master/files/tool_list.yaml.sample) to have the keys be stored as Ansible variables and then run the tool installation script in a loop via Ansible for each tool listed in the tools file (I'm not even sure if multiple values for the same variable can be defined in a single file and then have Ansible loop over all of those). 
Or - any other ideas?

**Comment by natefoo** [comment]
We could use the [include_vars](http://docs.ansible.com/ansible/include_vars_module.html) task, which would get us the tools list as `tools` and then just use `with_items` on `tools`. But the install script would need to take an argument that specified only installing the named tool.

**Comment by mvdbeek** [comment]
Well, include_vars seems to be the way to go, and then using a [`with_nested`](https://docs.ansible.com/ansible/playbooks_loops.html#nested-loops) loop should do it?

**Comment by martenson** [comment]
I think we have this fully in place via https://github.com/galaxyproject/ephemeris and https://github.com/usegalaxy-eu/usegalaxy-eu-tools

**Comment by natefoo** [comment]
https://github.com/galaxyproject/usegalaxy-tools actually
