### ISSUE TITLE
galaxy shut down without operation？

### ISSUE THREAD

**Issue by bestweicheng** [galaxyproject/galaxy#11163]
[pid: 16553|app: 0|req: 12/18] 210.28.30.60 () {40 vars in 802 bytes} [Fri Jan 15 23:36:09 2021] GET /api/users/f2db41e1fa331b3e => generated 272 bytes in 51 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 1)
210.28.30.60 - - [15/Jan/2021:23:36:09 +0800] "GET /api/histories/e89067bb68bee7a0/contents?limit=500&offset=0&order=hid&v=dev&q=deleted&q=purged&q=visible&qv=False&qv=False&qv=True HTTP/1.1" 200 - "http://172.19.231.192:3365/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
[pid: 16553|app: 0|req: 12/19] 210.28.30.60 () {40 vars in 1007 bytes} [Fri Jan 15 23:36:09 2021] GET /api/histories/e89067bb68bee7a0/contents?limit=500&offset=0&order=hid&v=dev&q=deleted&q=purged&q=visible&qv=False&qv=False&qv=True => generated 2009 bytes in 99 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 3)
210.28.30.60 - - [15/Jan/2021:23:36:09 +0800] "GET /api/histories/e89067bb68bee7a0?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter HTTP/1.1" 200 - "http://172.19.231.192:3365/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
[pid: 16553|app: 0|req: 13/20] 210.28.30.60 () {40 vars in 927 bytes} [Fri Jan 15 23:36:09 2021] GET /api/histories/e89067bb68bee7a0?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter => generated 121 bytes in 62 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 0)
Gracefully killing worker 1 (pid: 16553)...
galaxy.app DEBUG 2021-01-16 01:48:04,310 [p:16553,w:1,m:0] [uWSGIWorker1Core0] Shutting down
galaxy.queue_worker INFO 2021-01-16 01:48:04,361 [p:16553,w:1,m:0] [uWSGIWorker1Core0] Sending reconfigure_watcher control task.
galaxy.util.monitors DEBUG 2021-01-16 01:48:04,420 [p:16553,w:1,m:0] [uWSGIWorker1Core0] Joining monitor thread
galaxy.jobs.handler INFO 2021-01-16 01:48:04,420 [p:16553,w:1,m:0] [uWSGIWorker1Core0] sending stop signal to worker thread
galaxy.util.monitors DEBUG 2021-01-16 01:48:04,421 [p:16553,w:1,m:0] [uWSGIWorker1Core0] Joining monitor thread
galaxy.jobs.handler INFO 2021-01-16 01:48:04,421 [p:16553,w:1,m:0] [uWSGIWorker1Core0] job handler queue stopped
galaxy.jobs.runners INFO 2021-01-16 01:48:04,421 [p:16553,w:1,m:0] [uWSGIWorker1Core0] LocalRunner: Sending stop signal to 4 job worker threads
galaxy.jobs.runners INFO 2021-01-16 01:48:04,421 [p:16553,w:1,m:0] [uWSGIWorker1Core0] Waiting up to 30 seconds for job worker threads to shutdown...
galaxy.jobs.runners INFO 2021-01-16 01:48:04,422 [p:16553,w:1,m:0] [uWSGIWorker1Core0] All job worker threads shutdown cleanly
galaxy.jobs.handler INFO 2021-01-16 01:48:04,422 [p:16553,w:1,m:0] [uWSGIWorker1Core0] sending stop signal to worker thread
galaxy.util.monitors DEBUG 2021-01-16 01:48:04,423 [p:16553,w:1,m:0] [uWSGIWorker1Core0] Joining monitor thread
galaxy.jobs.handler INFO 2021-01-16 01:48:04,423 [p:16553,w:1,m:0] [uWSGIWorker1Core0] job handler stop queue stopped
galaxy.app DEBUG 2021-01-16 01:48:04,424 [p:16553,w:1,m:0] [uWSGIWorker1Core0] Finished shutting down

**Comment by bestweicheng** [comment]
what's wrong with my server?

**Comment by ZeroDesigner** [comment]
I meet the same problem as yours. Have you fix it ?

**Comment by EmmettPeng** [comment]
I encountered the same problem. Anyone could help with this?

**Comment by mvdbeek** [comment]
> Gracefully killing worker 1 (pid: 16553)...

I don't think there's anything obviously wrong on the Galaxy side, this is uwsgi shutting down the server due to some event, most likely SIGINT or SIGTERM.
You'll want to look at how you're starting Galaxy and how you have configured what happens if a process exceeds memory limits.

**Comment by martenson** [comment]
this is likely outdated issue, please provide new info and reopen if so inclined
