### ISSUE TITLE
Workflow can be submitted even when a non-optional select with no_options validator ha no option selected

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#11182]
A user tried to execute https://training.galaxyproject.org/training-material/topics/metagenomics/tutorials/metatranscriptomics/workflows/main_workflow.ga but I had not installed reference data yet. Which led to a tool error for `sortmerna`

Since the reference data select is not optional and also has a validator: https://github.com/bgruening/galaxytools/blob/d2767c87b1cc7459fd0d51c5c87f8e51d88d7f48/tools/rna_tools/sortmerna/sortmerna.xml#L208 I'm wondering why the workflow could be submitted. 

release_20.09

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/17048
