### ISSUE TITLE
Extract dataset from list extracts all the tags

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#11199]
If a dataset collection is created and the elements of the collection have tags, when the Extract Dataset tool is used, the extracted dataset element inherits *all* the tags of elements in the collection. This image illustrates the problem:

![image](https://user-images.githubusercontent.com/4154788/105343675-9d08b300-5bea-11eb-959a-0e4f494c6618.png)

**Comment by mvdbeek** [comment]
If you want to change this you need to look at https://github.com/galaxyproject/galaxy/blob/7ffe71dd84ea67c48453d710272161db5d599124/lib/galaxy/tools/__init__.py#L2889. The right thing would be to ignore the passed in tags and copy them from the element object

**Comment by pvanheus** [comment]
Thanks @mvdbeek . BTW I cannot reproduce this with the new (Beta) history view because Extract Dataset throws an error (see below) but that's a different problem.

```
The server could not complete the request. Please contact the Galaxy Team if this error persists. Error executing tool with id '__EXTRACT_DATASET__': 'str' object has no attribute 'copy'

{
    "history_id": "f597429621d6eb2b",
    "tool_id": "__EXTRACT_DATASET__",
    "tool_version": "1.0.0",
    "inputs": {
        "input": {
            "values": [
                {
                    "id": "f597429621d6eb2b",
                    "hid": 8,
                    "name": "datasets",
                    "src": "hdca",
                    "tags": []
                }
            ],
            "batch": false
        },
        "which|which_dataset": "first"
    }
}
```

**Comment by nsoranzo** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11206 .

**Comment by mmiladi** [comment]
Hello, I receive exactly the same error on the EU server and my WFs have become unfunctional. Is there any progress on this `copy` attribute error?

> Thanks @mvdbeek . BTW I cannot reproduce this with the new (Beta) history view because Extract Dataset throws an error (see below) but that's a different problem.
> 
> ```
> The server could not complete the request. Please contact the Galaxy Team if this error persists. Error executing tool with id '__EXTRACT_DATASET__': 'str' object has no attribute 'copy'
> 
> {
>     "history_id": "f597429621d6eb2b",
>     "tool_id": "__EXTRACT_DATASET__",
>     "tool_version": "1.0.0",
>     "inputs": {
>         "input": {
>             "values": [
>                 {
>                     "id": "f597429621d6eb2b",
>                     "hid": 8,
>                     "name": "datasets",
>                     "src": "hdca",
>                     "tags": []
>                 }
>             ],
>             "batch": false
>         },
>         "which|which_dataset": "first"
>     }
> }
> ```

**Comment by mvdbeek** [comment]
Can you create a full bug report with instructions how to reproduce @mmiladi ?
