### ISSUE TITLE
XSD: the tool id attribute allows any string as per the schema definition

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11196]
The current definition in the XSD file for the [tool id attribute allows any string](https://github.com/galaxyproject/galaxy/blob/5b0f47fd87c52ad2860e233d5e2d6da8d474e4be/lib/galaxy/tool_util/xsd/galaxy.xsd#L132) while the [attribute documentation](https://docs.galaxyproject.org/en/latest/dev/schema.html#attributes) states:
>should be lowercase and contain only letters, numbers, and underscores.

and the [IUC best practices recommendations](https://planemo.readthedocs.io/en/latest/standards/docs/best_practices/tool_xml.html#tool-ids) states:
>- Tool IDs should contain only [a-z0-9_-].
>- Multiple words should be separated by underscore or dashes

I propose adding a `<xs:simpleType>` with a pattern restriction that complies with these requirements. Or should the schema not enforce this rule to validate the XML document?

**Comment by bgruening** [comment]
Plus one for enforcing.

**Comment by davelopez** [comment]
Adding this restriction and providing an invalid `id` will probably result in planemo lint displaying `Invalid XML found in file` with the corresponding error message and the Galaxy Tools Extension showing an issue in the problems tab similar to this:

![image](https://user-images.githubusercontent.com/46503462/105343274-b1947d80-5be1-11eb-99be-08fc1d84280a.png)

As far as I know, it should not break any existing tool id, since this is only used when linting tools, but probably will mark `planemo lint` as failed in the CI when making a PR against a tool repository.
Is this behavior undesired?

**Comment by mvdbeek** [comment]
I think so, since that means we can't update the tool for fixes.

**Comment by davelopez** [comment]
Oops... Understand! 😅 
Then do not add the restriction to the XSD and probably include an additional custom validation to the [extension](https://github.com/galaxyproject/galaxy-language-server/tree/master/client) and/or [planemo linter](https://github.com/galaxyproject/planemo/blob/master/planemo/lint.py) that will check this pattern and treat it only as a `Warning`.

I will close this then :)

**Comment by bgruening** [comment]
> I think so, since that means we can't update the tool for fixes.

I think we should lint tools like this, to avoid people adding more "tools with spaces in IDs". The old tools are then failing, that is another problem we should fix elsewhere, e.g. skipping lints in shed.yml ... but the correct thing is to warn users about a "wrong" ID, isn't it?

**Comment by mvdbeek** [comment]
I think David suggested the right thing here. The XSD linting doesn't allow this amount of flexibility.
