### ISSUE TITLE
Unexpected authnz failures bleed through to the UI

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#11207]
https://github.com/galaxyproject/galaxy/blob/66e666b67833dd4f8da58f0b68292cfa7480a956/lib/galaxy/authnz/managers.py#L304 this is not optimal. I am gonna say we don't want to pass random exceptions out of the API and into the UI.

**Comment by martenson** [comment]
In addition the UI would ideally consist of more than an error message for the plethora of errors that can happen while authenticating remotely.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11212
