### ISSUE TITLE
404 from the "logged in as ..." in masthead

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#11208]
### click here

![Galaxy](https://user-images.githubusercontent.com/1814954/105486977-b162b380-5caf-11eb-9adc-30d2b9d1d1dd.png)

### get here

![404_Not_Found](https://user-images.githubusercontent.com/1814954/105487030-c3445680-5caf-11eb-94ef-980c0085a443.png)

**Comment by OlegZharkov** [comment]
can someone close this please
