### ISSUE TITLE
Public name validation at user creation

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#11237]
Per the interface in User Prefs, `Public name must contain only lowercase letters, numbers and "-". It also has to be shorter than 255 characters but longer than 2.`

But this isn't enforced at account creation time.  I can create a user with the publicname `dot.name`.

The requirements at registration state different requirements:

```
Public names must be at least three characters in length and contain only lower-case letters, numbers, dots, underscores, and dashes ('.', '_', '-').
```

We need to either relax user prefs (if appropriate) or fix validation at registration and adjust the error message.  Looking through usage, I don't see a technical issue with allowing all three separators `. _ -`

**Comment by nsoranzo** [comment]
We have been allowing these 3 characters for >4 years, see https://github.com/galaxyproject/galaxy/pull/2947 . In that PR I updated also the Mako templates, not sure when the UI got out of sync, but I'd just update the messages and find a fix for https://github.com/galaxyproject/galaxy/issues/11209

**Comment by dannon** [comment]
Cool, that's what I was leaning towards too.

**Comment by nsoranzo** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11260 .
