### ISSUE TITLE
Workflow editor step deletion appears to re-order inputs

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1124]
It's easiest if you can toggle between the two images quickly to see what exactly is going on. 

![snapshot2](https://cloud.githubusercontent.com/assets/458683/11252036/bee35580-8df9-11e5-97ba-6b3ca81f8a66.png)
![snapshot3](https://cloud.githubusercontent.com/assets/458683/11252037/beefec50-8df9-11e5-8e71-527ba4818130.png)

In the first image, step 7 no longer has any inputs (we switched the format of the tool that was connected to it so the connection broke. I went to remove this particular output (note changed name in second picture) when I noticed a strange thing, instead of all input connectors moving up, the last input connector was dropped completely, and the inputs just moved up. This caused a lot of outputs to go to the _wrong_ inputs.

**Comment by mvdbeek** [comment]
That should be fixed in https://github.com/galaxyproject/galaxy/pull/11542 ... finally 😆

**Comment by hexylena** [comment]
Omg! amazing! <3
