### ISSUE TITLE
MultiQC (type=data/multiple=true) doesn't suggest my list:paired collection

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11248]
Collection not shown as an option:

![image](https://user-images.githubusercontent.com/458683/106180107-29dbdf80-619c-11eb-91ac-b3b540e3d8c0.png)

the collection:

![image](https://user-images.githubusercontent.com/458683/106180163-39f3bf00-619c-11eb-80a6-dbef5dd64599.png)

But I can totally drag and drop it

![image](https://user-images.githubusercontent.com/458683/106180199-46781780-619c-11eb-90dc-0188b9ed8576.png)

Is this expected behaviour? I think @shiltemann reports she hit that too.

**Comment by mvdbeek** [comment]
Yes, multiqc would need to accept paired input.

**Comment by hexylena** [comment]
But it does? It will process my collection, as multiple=True it just loops over every element in the list, and every pair in the pairs?

**Comment by mvdbeek** [comment]
It needs to allow `type="list,paired"`. We cannot do what we do for lists for pairs/list of pairs, if you map out that logic there's no common thing that will always work.

**Comment by hexylena** [comment]
Oh, we're having different conversations. What you mean is there's no general solution for multiple=True processing list:paired? Ok, that's fine, that makes sense. I was still confused by the acceptance and processing of this type despite that restriction, but, it works for my case for now. Thanks!

**Comment by mvdbeek** [comment]
Ah, yeah, drag-and-drop only works in the very simplest case of a single HDA picked out of a collection (and then it skips all normal validations). There's a couple of issues on that, but I don't think we'll look into it before the tool form is vue-ified.
