### ISSUE TITLE
Automatically suggest names for paired list for list:paired

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11249]
When you're using the list:paired builder it makes a nice name for the paired dataset based on the common portion of both:

![image](https://user-images.githubusercontent.com/458683/106185964-e5544200-61a3-11eb-9049-23edf4583b8c.png)

The paired builder should do the same, just auto-suggest the common portion:

![image](https://user-images.githubusercontent.com/458683/106185905-cbb2fa80-61a3-11eb-9504-777033d708ac.png)

**Comment by assuntad23** [comment]
closed with #11489

**Comment by hexylena** [comment]
ah fantastic! thanks @assuntad23 that'll be nice to have feature parity there.
