### ISSUE TITLE
Composite dataset items fail to render in workflow report PDF

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#11275]
https://github.com/galaxyproject/galaxy/pull/9769 brought support for referencing elements of composite datatypes in workflow reports - a great feature!
Currently though these references do not seem to work properly when exporting the report to pdf.

To reproduce the issue take a look at this public history:
https://usegalaxy.eu/u/wolfgang-maier/h/reportcompositetest

and try to run this workflow:
https://usegalaxy.eu/u/wolfgang-maier/w/test-wf-report-with-composite
with dataset 1 of the history.

**Comment by wm75** [comment]
@OlegZharkov if you could come up with a fix for the image display at least, it would help me greatly.

**Comment by mvdbeek** [comment]
I guess https://github.com/galaxyproject/galaxy/pull/11296 closes this ?
