### ISSUE TITLE
Dataset tags lost when copying or sharing histories

### ISSUE THREAD

**Issue by bcclaywell** [galaxyproject/galaxy#1133]
One of our users is using dataset tags to manage the datasets in an RNA-seq experiment, and has reported that these tags are lost when making a copy of a history to run different analyses, or when the history is shared with another user so they can run their own.

We're running off the 15.07 branch.

**Comment by GuyReeves** [comment]
I just noticed this as well.

**Comment by nsoranzo** [comment]
Duplicate of #1135.
