### ISSUE TITLE
Convert users to sign up

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11372]
I think we're doing a poor job of converting anonymous users into signups. This presents as a common problem in training of "why isn't X available" or "where is my history button" which we have to explain often.

I think we should do a couple things:

- an always-on banner with "Some features will not available until you register. Click here to register. Thank you for trying Galaxy!"
- https://github.com/galaxyproject/galaxy/issues/10418
- We should re-add the disabled buttons but grey them out
   - history switch
   - workflows
   - user menu
   - generally make it look 100% like the logged in process (with the addition of the banner)
- On hover there should be a popup "This feature is only available for registered users"
- On click of those (visually) disabled buttons, redirect them to the registration page.

See slack's example of "Show the feature they want + convert"

![image](https://user-images.githubusercontent.com/458683/107935948-5193bb80-6f82-11eb-9385-bf1a4b695af5.png)

xref https://github.com/galaxyproject/galaxy/issues/5898 but orthogonal. xref #11374 which is part of the reason this came up

**Comment by mvdbeek** [comment]
I think we're doing that in many places now. From here on I think we can open more issues with specific cases where this would be a good idea.

**Comment by hexylena** [comment]
Sure, I can open more specific ones, since there is no pop up for the greyed out buttons (new history, switch, rename history)
