### ISSUE TITLE
urls are lost on upload

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11371]
Can't we store these in the metadata? Somewhere? It always bugs me when I upload a file via url and then rename it, and the original URL is lost.

**Comment by nsoranzo** [comment]
It could be among the Tool Parameters for `upload1`, but it's not.

**Comment by assuntad23** [comment]
@hexylena I started digging in to this a little bit today, but got caught up on a few other things too, and am only got back to it this evening. 

#11276 was a step in the right direction to remediate this. If you look at a more recent upload (21.05+), in the details view, you should see the url in the request_json part of Tool Parameters.
![Screenshot from 2021-09-16 22-08-47](https://user-images.githubusercontent.com/26912553/133722644-96a95cb4-188f-44ba-9808-2d42a188d127.png)

Do we want to display the URL individually under Dataset Information or is the current view satisfactory?

**Comment by hexylena** [comment]
Ah that's a huge improvement!!! Arguably better than just the individual URLs since here we can see all of the settings which is really nice. 

I've had a look on test.galaxyproject.org and I think this fixes it! Thank you so much for letting me know
