### ISSUE TITLE
Renaming chromosome in vcf file

### ISSUE THREAD

**Issue by tcrispino13** [galaxyproject/galaxy#11395]
Hi! I am new to the world of bioinformatics and had been using the usegalaxy.org for sometime now.
I am supposed to merge two vcf files which are SNP datasets.
I've already checked the reference genome in both the datasets but I am having trouble merging them maybe because for the CHROM column, one dataset has CHR01 while the other has 1 only, 
I am seeking help on how I am going to execute such job using the galaxy using the bcftools annotate function.
Thank you so much for your help!

**Comment by bernt-matthias** [comment]
You may try one of the search and replace text tools. If this does not help I would suggest to check at https://help.galaxyproject.org/.

Also https://training.galaxyproject.org/ is an excellent resource.
