### ISSUE TITLE
Officially deprecate the Mercurial repository

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1139]
Recently I have noticed multiple dev-list questions about bugs that were already fixed in GitHub but not propagated to BitBucket causing disappointments. 
I think the propagation of commits to BitBucket is significantly more overhead than we expected when making the decision and thus **I propose to officialy deprecate the BitBucket repository** to motivate deployers to switch. I imagine this being in 15.10 release notes.
 We can also try to perfect the 'how to' on wiki (https://wiki.galaxyproject.org/Develop/SourceCode#How_to_transfer_Galaxy_instance_from_Mercurial_Bitbucket_to_Git_GitHub).
ping @natefoo @jxtx

**Comment by hexylena** [comment]
:+1: Want to set an (optimistic) milestone of 16.01?

**Comment by nsoranzo** [comment]
:+1: 

I've raised this same point on IRC some weeks ago.

**Comment by bgruening** [comment]
Yes to deprecation, but we should communicate this well and give maintainers at least 2 release cycles to adopt. I can assume that many admins fear this migration.

**Comment by nsoranzo** [comment]
Actually it seem the migration went pretty smooth for everybody who switched, I haven't seen complains on the mailing list.

I don't see the point of making new releases on bitbucket if we don't keep them updated.

**Comment by mvdbeek** [comment]
:+1:

**Comment by dannon** [comment]
Totally agree.  It's counterproductive to have releases on bitbucket if they aren't up to date, so we need to either fix and automate updates, or just tell folks to migrate.  Migration is certainly easier on us, if we think deployers will be OK with it.

**Comment by natefoo** [comment]
:+1:, and let's publish the migration procedure.

I'm fine with waiting until post-16.01 (16.04?)

**Comment by bgruening** [comment]
> Actually it seem the migration went pretty smooth for everybody who switched, I haven't seen complains on the mailing list.

But this does not tell you of how many instances still using bitbucket.

> I don't see the point of making new releases on bitbucket if we don't keep them updated.

Sure, but this is a different point. I'm in favour of this, my point is just we need to communicate this well enough, get Galaxy Admins involved and give some more time. 16.04 seems good to me.

**Comment by martenson** [comment]
I see this as 'Yes, start actively discouraging deployers from using BitBucket.' I will add the note to 15.10 release notes.

**Comment by blankenberg** [comment]
16.07 might be better for a hard cutoff, so that we aren't swamped with migration issues just before GCC2016.

**Comment by dannon** [comment]
New GCC Workshop:  Hands-on repo migration!

**Comment by nsoranzo** [comment]
> But this does not tell you of how many instances still using bitbucket.

What about an online poll to get some data about this?
- Are you still using bitbucket or have you migrated to git?
- If you migrated, how difficult was the process?

**Comment by martenson** [comment]
I added the deprecation note to the release notes https://github.com/galaxyproject/galaxy/pull/868

**Comment by dannon** [comment]
I pinged @tnabtaf and volunteered to do a quick bit on this at the next GalaxyAdmins meeting -- seems like an ideal platform for getting feedback from current admins as to what they're still using _and_ for giving a crash course on upgrading.

**Comment by martenson** [comment]
good idea @dannon

**Comment by tnabtaf** [comment]
Hi all, 

I'm following up on the documentation front.  
1. I'm aggressively updating the wiki.  
   1. All references to Mercurial are now either historic or have to do with the tool shed.
   2. References to Bitbucket are proving more challenging, but I'm trying to be fearless.
2. **Unless anyone objects** I'll update the landing pages for Galaxy Repos in bitbucket to say something like what the cloudman repo says: This repository has moved to Github and the one here is no longer updated. Please switch to using https://github.com/galaxyproject/...

Please object before Monday., August 15.

**Comment by martenson** [comment]
thanks @tnabtaf

**Comment by tnabtaf** [comment]
Hi All, 

A few things that are requiring more knowledge than I have
1. https://wiki.galaxyproject.org/Admin/Config/Performance/Cluster - references to BitBucket.
2. https://wiki.galaxyproject.org/Admin/Tools/ToolDependencies - references to bitbucket

Anyone feel like taking those on?

**Comment by jmchilton** [comment]
I update the first to remove references to bitbucket and galaxy-dist (I still references egg scrambling though).

The second - https://wiki.galaxyproject.org/Admin/Tools/ToolDependencies - references to bitbucket for other projects and should not be updated.

Thanks @tnabtaf!

**Comment by tnabtaf** [comment]
I've updated the Bitbucket pages to redirect to the GitHub pages.  In most cases, I also deleted the rest of the text on the page.

I **did not** update https://bitbucket.org/galaxy/playbook as the most recent commit is 2016/06/01.

I think I'm now done.
