### ISSUE TITLE
edit_datasets might be broken for some datasets

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#11406]
The edit datasets page just won't load

This came up during the smorgasbord training, and I think @cat-bro saw this as well.
In my case I saw this locally on a h5ad dataset. This seems to be broken on 20.09 at least.

**Comment by mvdbeek** [comment]
And for the history in https://usegalaxy.eu/u/clarisse.orniacki/h/clustering-3k-pbmcs-with-scanpy this also happens for a h5ad dataset.

**Comment by davelopez** [comment]
I tried to debug this a little bit using the h5ad dataset at the top of [this history](https://usegalaxy.eu/u/clarisse.orniacki/h/clustering-3k-pbmcs-with-scanpy) provided by Marius and what I found was:

The API call `GET /dataset/get_edit?dataset_id={dataset_id}` returns OK and produces a 592KB JSON with one of the `attribute_inputs.select` (called `obs_names`) containing 2638 options.

Here is a chunk of the JSON:
````JSON
{
   "display_name":"Galaxy112-[Inspect_and_manipulate_(tl.rank_genes_groups)_on_data_91__Annotated_data_matrix].h5ad",
   "message":"Required metadata values are missing. Some of these values may not be editable by the user. Selecting \\'Auto-detect\\' will attempt to fix these values.",
   "status":"warning",
   "dataset_id":"d413a19dec13d11e",
   "attribute_inputs":[
       ...
      {
         "type":"select",
         "multiple":true,
         "optional":null,
         "name":"obs_names",
         "label":"obs_names",
         "options":[
            [
               "AAACATACAACCAC-1",
               "AAACATACAACCAC-1",
               true
            ],
            [
               "AAACATTGAGCTAC-1",
               "AAACATTGAGCTAC-1",
               true
            ],
            [
               "AAACATTGATCAGC-1",
               "AAACATTGATCAGC-1",
               true
            ],
            [
               "AAACCGTGCTTCCG-1",
               "AAACCGTGCTTCCG-1",
               true
            ],
            ...
````

This ends up with the UI trying to create 2638 choice elements and literally hanging the page in this `addSelectedChoice` function.

![image](https://user-images.githubusercontent.com/46503462/110142431-72f40480-7dd6-11eb-9d5d-0b1aba2b199a.png)

I am afraid I don't know what will be a good solution here, I hope at least this simplifies further debugging or fixing :)

**Comment by bgruening** [comment]
ping @mtekman

**Comment by mtekman** [comment]
Yep, likely related to https://github.com/galaxyproject/galaxy/issues/11516 -- on my todo list.

I think the simple solution here would be to reduce the amount of metadata given by AnnData datasets. This has been patched a few hundred times in recent times, to work with the various unstable versions of ScanPy -- however ScanPy 1.7.x now seems quite stable (indeed they have [removed all previous documentation](https://scanpy.readthedocs.io/en/stable/) to their prior unstable releases) so I will target that in the next patch.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11574
