### ISSUE TITLE
[21.01] Select option no longer present when uploading dataset from workflow form.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#11432]
Tested on usegalaxy.org as part of the workflow tutorial.

**Comment by jmchilton** [comment]
This is seeming very non-trivial to fix. I tried to pass selectable around more. Namely this:

```diff
+++ b/client/src/components/Upload/helpers.js
@@ -43,6 +43,10 @@ export const commonProps = {
         type: Function,
         default: null,
     },
+    selectable: {
+        type: Boolean,
+        default: false,
+    },
     auto: {
         type: Object,
         default: function () {
```

with the addition of initializing the option in a couple other places.

But then whether the button would appear or now depends on if the tool panel button was clicked first in a session or the tool form button. So maybe there is some state sharing - but it results in some Vue property issues.

<img width="607" alt="Screen Shot 2021-02-22 at 10 07 00 PM" src="https://user-images.githubusercontent.com/216771/108797898-5ea04400-755a-11eb-8b7f-86fd0e97f2d3.png">

**Comment by mvdbeek** [comment]
@Nerdinacan any chance you could look at this ? I think that is related to mounting the upload modal just once ? Fwiw the callback should be passed in https://github.com/jmchilton/galaxy/blob/a12316de44cf663f03235d3496830eacad917ea6/client/src/components/DataDialog/DataDialog.vue#L138
We'd probably have to emit the `selectable` throught the eventHub ? This should make it to 21.01.

**Comment by Nerdinacan** [comment]
@mvdbeek Will do. Hopefully it's just a missed prop definition in the wrappers that get it initialized

**Comment by Nerdinacan** [comment]
https://github.com/galaxyproject/galaxy/pull/11457

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11457, minor tweak in #11576
