### ISSUE TITLE
ColumnMaker fails with 1-column input with misleading error message

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#11438]
https://usegalaxy.org/u/jmchilton/h/unnamed-history-2

> Missing or invalid 'columns' metadata value, click the pencil icon in the history item and select the Auto-detect option to correct it.  This tool can only be used with tab-delimited data.

**Comment by nsoranzo** [comment]
You scared me for a minute, but that's actually a "user error". You forced a single-column dataset to the tabular format, but the tool requires at least 2 columns: https://github.com/galaxyproject/tools-iuc/blob/master/tools/column_maker/column_maker.py#L34-L36

**Comment by jmchilton** [comment]
The comment is right there:

```
# To be considered tabular, data must have at least one column.
```

The input has a column.

It does appear not be an issue with 21.01 since I have the same issue with usegalaxy.eu.

https://usegalaxy.eu/u/jmchilton/h/unnamed-history

It is very believable that this is in fact a "user error" but I'm trying to help with release testing so I should be instructed what I'm doing wrong relative to (https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/workflow-parameters/tutorial.html#read-a-parameter-from-a-dataset) or we should fix the problem (in Galaxy or the tutorial). Just closing this like that was discouraging.

**Comment by nsoranzo** [comment]
Apparently this tool is living (by mistake) on both tools-iuc and tools-devteam repos, and I pointed you to the wrong one which was never uploaded to the TS, sorry about that!

The check in the (outdated) version installed on Main (1.3.1) is:

https://github.com/galaxyproject/tools-devteam/blob/b8e88baa69cfc250620a2fd39b9566aa31ef7e6f/tools/column_maker/column_maker.py#L23-L25

```python
if in_columns < 2:
    # To be considered tabular, data must fulfill requirements of the sniff.is_column_based() method.
    exit("Missing or invalid 'columns' metadata value, click the pencil icon in the history item and select the Auto-detect option to correct it.  This tool can only be used with tab-delimited data.")
```

Clearly this is a misleading error message.

UseGalaxy.eu has the latest version coming from tools-devteam (1.5), but the error message is the same:

https://github.com/galaxyproject/tools-devteam/blob/master/tools/column_maker/column_maker.py#L50-L60

So there are multiple issues (but none of them is a Galaxy metadata issue):
- the tools-devteam version needs to be merged into tools-iuc and removed from tools-devteam
- the merged tool should either allow 1-column tabular or fail with a proper error message
- the tutorial may be more specific in the input required by the tool (I haven't looked much into that though).

Sorry I closed this issue bluntly, but I spent a large amount of time fixing metadata handling in this release and I was just too happy that was not another such issue.

Would it be OK for you if we move this to the tools-iuc repo?

**Comment by jmchilton** [comment]
Ahh - presumably this tool was fixed in IUC for this tutorial (https://github.com/galaxyproject/tools-iuc/commit/7fb196da957e87fab8bc3f2e623c611a3980e0c7#diff-6a9d09e794e9ba536636097d2ffd74250ba04d99d2687aac811a2488e149772e) and then overwritten by tools-devteam changes. That is a real mess but you're right it doesn't seem to be metadata related at all.
