### ISSUE TITLE
RuleBuilder Nested List Tutorial Returns an Empty List

### ISSUE THREAD

**Issue by assuntad23** [galaxyproject/galaxy#11437]
While running through this tutorial: https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/upload-rules-advanced/tutorial.html#building-nested-lists

At the Nested List Step, I encountered an error.  The list that is returned is empty : there are no logs in the console, there are no errors on the page.
Here is a screenshot: 
![Screenshot from 2021-02-22 15-05-38](https://user-images.githubusercontent.com/26912553/108763584-8625eb00-751f-11eb-8c4c-acffdb34e608.png)

Here is the JSON that was generated: 
{
  "rules": [
    {
      "type": "add_filter_count",
      "count": 1,
      "which": "first",
      "invert": false
    },
    {
      "type": "add_column_regex",
      "target_column": 11,
      "expression": "([^\\d]+)\\d+",
      "group_count": 1
    }
  ],
  "mapping": [
    {
      "type": "url",
      "columns": [
        9
      ]
    },
    {
      "type": "list_identifiers",
      "columns": [
        12,
        0
      ],
      "editing": false
    }
  ]
}

**Comment by mvdbeek** [comment]
The very last line in the tutorial points to a dataset that doesn't exist anymore:
```
galaxy.tool_util.provided_metadata DEBUG 2021-03-09 10:32:41,991 unnamed outputs [{'__unnamed_outputs': [{'destination': {'type': 'hdca', 'object_id': 8248}, 'collection_type': 'list:list', 'name': 'new collection', 'error_message': 'Failed to fetch collection element(s):\n\n- Failed to fetch url https://sra-download.ncbi.nlm.nih.gov/traces/sra46/SRR/005238/SRR5363715. HTTP Error 404: Not Found', 'elements': None}]}]
```
.
We need to fix the tutorial and make this more robust (all the other datasets downloaded fine after all), but I think this has always resulted in an empty collection and is not a new regression, so it shouldn't block the release.
