### ISSUE TITLE
IPython container does not start up on existing notebooks

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#1143]
It appears that Galaxy times out trying to start iPython session on an existing notebook. This does not happen on other datasets. In [this history](https://test.galaxyproject.org/u/anton/h/abl1-duplex-data) dataset **51** contains a small iPython notebook, but I cannot get it started.

**Comment by bgruening** [comment]
@nekrut can this be closed?

**Comment by martenson** [comment]
If I create a notebook in Jupyter and then try to open it in iPython it opens in Jupyter anyways, is that as expected?

**Comment by hexylena** [comment]
We want to deprecate IPython, so .. yes?

**Comment by hexylena** [comment]
Also, this can be closed. We patched the container in https://github.com/bgruening/docker-ipython-notebook/commit/e509d3d3e35be9a4493a9a9c59e7ec4f78feb7aa

**Comment by martenson** [comment]
Awesome, thanks @erasche
