### ISSUE TITLE
Database exception preventing workflow invocations to be scheduled

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11433]
A database exception was breaking the scheduling of new jobs, see [this trace](https://gist.github.com/mvdbeek/397c77cbef98121bc3ea089a4860d27a)

**Comment by davelopez** [comment]
This should be fixed now.

(For some reason, the closing keywords to auto-close issues when the PR is merged are not always working...)

**Comment by nsoranzo** [comment]
The auto close only works when the commit with the magic keyword and issue number reaches the default branche (i.e. `dev` for us). So if the PR was targeting a release branch (like in this case), that should happen when we merge forward.

**Comment by davelopez** [comment]
Ohh I see, thanks Nicola for clarifying. For the next time, I assume then is better to just leave them open until the change reaches `dev`.

**Comment by nsoranzo** [comment]
We don't have a policy for this, so if you close them I think it's fine, just wanted to clarify how it works!
