### ISSUE TITLE
Text wrapping in left pane can break up words

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#11445]
Incorrect text wrapping in left pane: word can be broken up to fit:

![image](https://user-images.githubusercontent.com/6132258/108801375-8ea01500-7563-11eb-9eb5-b28aaebae16a.png)

In the above example "Datasets" is broken up. Screenshot obtained via Galaxy 101 tutorial / 21.01 release testing.

**Comment by mvdbeek** [comment]
That is not a blocker, it has probably always been a problem.

**Comment by mvdbeek** [comment]
That's gonna be obsolete pretty soon with the move to the new history.
