### ISSUE TITLE
Update sort tool from 1.1.0 to 1.1.1 to be consistent with the Galaxy 101 tutorial

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#11444]
Can we update the sort tool  from 1.1.0 to 1.1.1 to be consistent with the Galaxy 101 tutorial (usegalaxy.eu uses 1.1.1)?
This is *not* a bug; the tool works fine, but the tutorial steps for 1.1.1 are inconsistent with 1.1.0.

**Comment by mvdbeek** [comment]
Doesn't seem related to Galaxy. If usegalaxy.eu uses a newer version that must be a tool shed version ?

**Comment by ic4f** [comment]
Indeed. Closing.
