### ISSUE TITLE
Dataset header not displayed in central pane

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#11443]
When viewing a dataset in the central pane (by clicking the eye icon), the header of the dataset is empty, whereas screenshots from (at least one) tutorial show a header (see any dataset screenshot in the [Galaxy 101 tutorial](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101/tutorial.html), e.g. Optional: Obtaining the Data directly from UCSC >> step 3). 

Examining the HTML reveals an empty `th` element; the styling is correct (adding text to the element displays the header correclty).  The preview in the left bar displays the header correctly.

**Comment by ic4f** [comment]
Also see #11644 - it has more details and a screenshot

**Comment by foellmelanie** [comment]
The EU Server was updated tonight and runs now in version 21.0.1 which made the problem disappear :)

**Comment by davelopez** [comment]
Confirmed that is working in `.org` and locally.
Thanks @foellmelanie for checking!

**Comment by mvdbeek** [comment]
I don't think we had any commit that would have fixed this. Did you try this with @ic4f's example ?

**Comment by davelopez** [comment]
I tried with my own datasets that were also not displaying the header a week ago and now they are.
But yeah, no idea what change may have fixed that or what did make the header not to be displayed either :/

**Comment by mvdbeek** [comment]
<img width="1315" alt="Screenshot 2021-03-18 at 12 05 31" src="https://user-images.githubusercontent.com/6804901/111616526-454d8900-87e2-11eb-80e2-b9f8728355ff.png">
This is with https://github.com/galaxyproject/galaxy/blob/dev/test-data/library/5.bed ... I presume that is what @ic4f is describing ?

**Comment by davelopez** [comment]
🤯 
You are right, with that file the header does not get displayed. Maybe it is related to the fact that the file itself does not have a header.
A week ago even files that have a proper header were not displaying it, like:
````csv
Sepal.Length,Sepal.Width,Petal.Length,Petal.Width,Species
5.1,3.5,1.4,0.2,setosa
4.9,3,1.4,0.2,setosa
4.7,3.2,1.3,0.2,setosa
4.6,3.1,1.5,0.2,setosa
5,3.6,1.4,0.2,setosa
5.4,3.9,1.7,0.4,setosa
4.6,3.4,1.4,0.3,setosa
5,3.4,1.5,0.2,setosa
4.4,2.9,1.4,0.2,setosa
4.9,3.1,1.5,0.1,setosa
5.4,3.7,1.5,0.2,setosa
4.8,3.4,1.6,0.2,setosa
4.8,3,1.4,0.1,setosa
````
But now they are, and I assumed this was fixed 😅 
I'll reopen it, thanks for double-checking @mvdbeek ;)

**Comment by mvdbeek** [comment]
I think something is wrong when serializing dataset.metadata ... if you call `dataset.to_dict()` you somehow erase metdata.column_names ... that is bizarre

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11664
