### ISSUE TITLE
When extracting a workflow from history, the tool for imported datasets appears as Unknown

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11449]
When importing a dataset from a `Data Library` (instead of uploading your own file) and then trying to `Extract Workflow` from history, the <del>dataset</del> tool will appear as `Unknown`. Maybe something like `Import File` can be more consistent?

Example using both methods:

![image](https://user-images.githubusercontent.com/46503462/108831898-0d7c6880-75cb-11eb-8554-00ac49d1bd40.png)

This may be just a papercut.

**Comment by mvdbeek** [comment]
It's the tool that is unknown, but yes, that would be a good papercut
