### ISSUE TITLE
sqlalchemy_utils prevents migration to sqlalchemy 1.4

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#11459]
Ref: #10892 
Updating to SQLAlchemy 1.4 (currently 1.4.0b3 as of 2/15/21) breaks Galaxy. The immediate cause is incompatibility of SQLAlchemy 1.4 with sqlalchemy-utils. The specific error happens because sqlalchemy-utils [imports a private member](https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/functions/orm.py#L14) from sqlalchemy (which was [removed in this commit](https://github.com/sqlalchemy/sqlalchemy/commit/dce8c7a125cb99fad62c76cd145752d5afefae36#diff-073ef5bba260cb71e47c71f18b30feac8cc00772a7e6f2137a6182417cee9029)). This is just the first error that prevents Galaxy from starting up; there may be more errors.

We use this dependency in 1 unit test + 7 lib modules. We use `create_database`, `database_exists`, `view.DropView`, `view.CreateView`, and `create_view`.

I see 3 possible solutions: (a) fix the problem upstream; (b) find an alternative library; (c) implement the required functionality. 

EDIT: currently, addressing this upstream. 

EDIT 2: after addressing this upstream, I'm restoring the initial version of this issue (see below). Tentatively, I see 2 options: (a) use a patched fork; and (b) implement locally. I'll try both, but I'm inclined to do (b). We *really use just a fraction* of what sqlalchemy-utils has to offer, so implementing what we need seems the simplest way. To quote the Go community, "A little copying is better than a little dependency".

---restored version:
Given that sqlalchemy-utils is not very actively maintained (v. 0.36.8, highest supported Python = 3.6, last commit on 9/27/20, although there is some discussion in Issues) and has not been updated to support SQLAlchemy 1.4, I think it's unreasonable to patch this one error, as it is unlikely to address the overall compatibility issue.

Selecting another library is an option; however, given the limited scope of its usage in our code base, as well as the relatively simple functionality it provides, I think implementing this in the code base makes more sense. As an extra benefit, that will reduce our dependency graph.

**Comment by ic4f** [comment]
Resolved in #11696.
