### ISSUE TITLE
Scratchbook enhancement: Include "i" info/view details for datasets in pop-out windows

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1146]
Current: Scratchbook does not currently place dataset/job details into a pop-out window

Request: Include it. Would be super useful when comparing parameters used for multiple, similiar tool runs

Visual of current action now in the UI:
<img width="868" alt="scratchbook_viewdetails_no-popup" src="https://cloud.githubusercontent.com/assets/8999735/11309588/8a82770e-8f79-11e5-89f2-96a8bd3b83f7.png">

**Comment by hexylena** [comment]
:+1:

**Comment by jennaj** [comment]
@guerler Thanks for considering and adding this in!!
