### ISSUE TITLE
Data libraries search on enter triggers a refresh of the page

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11465]
## Steps
- Go to `https://{your-galaxy}/library/list`.
- Type something in the search and hit enter.
- The page gets reloaded and the results are lost.

![bug_search02](https://user-images.githubusercontent.com/46503462/109019193-0f245a00-76b9-11eb-84e8-e9be1d3836a7.gif)

**Comment by OlegZharkov** [comment]
no worries, the entire backbone implementation of `/library/list` will be rewritten soon.

**Comment by jmchilton** [comment]
Sounds like we aren't going to fix for 21.01 so I'm pushing the milestone to 21.05. Thanks y'all!
