### ISSUE TITLE
Running tools on collections containing failed datasets is difficult

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#11460]
I have two collections of equal size, and want to run a tool with them as two inputs. However, as one of them has at least one failed dataset, the jobs do not schedule with this error `the previously selected dataset has entered an unusable state`. It's quite frustrating, because I'd like to continue the analysis with the majority of the datasets which are in an ok state and forget about the failed ones. Running 'Filter failed datasets' does not help, as correspondence between the two input collections will be lost.

I did find a workaround, which is to put the tool into a workflow, but this feels very hack-y.

**Comment by bernt-matthias** [comment]
After filtering the collection you could extract the identifiers and then filter the other collection with this list. Or?

**Comment by simonbray** [comment]
Yeah you are right, I also realised that after making the issue. There are multiple options, even if none of them really seem ideal.
