### ISSUE TITLE
Nora Visualization  could not load datasets

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11468]
This is only failing currently in https://usegalaxy.org/

Use this [sample dataset](https://usegalaxy.org/u/davelopez/h/test-nora-visualization) to test.

## Steps
![nora_org](https://user-images.githubusercontent.com/46503462/109036366-d04ad000-76c9-11eb-9b5a-88ce18ac5a34.gif)

**Comment by mvdbeek** [comment]
<img width="1256" alt="Screenshot 2021-02-24 at 18 03 16" src="https://user-images.githubusercontent.com/6804901/109037211-c5446f80-76ca-11eb-9a48-fc120237f4b0.png">
@dannon that's probably an easy one for you ?

**Comment by dannon** [comment]
Taking a look, yep!

**Comment by dannon** [comment]
Okay, did some digging and it looks like this is an error in noraviz's assuming basic http protocol, which has been fixed upstream, something like the following:

```
-               xhr.open('GET', 'http://' + params.url +  suffix , true);
+               xhr.open('GET', `${window.location.protocol}//${params.url}${suffix}` , true);
```

I need to merge in the latest noraviz and republish it with a version bump and it should be good to go.

**Comment by davelopez** [comment]
(For some reason, the keywords to auto-close issues when the PR is merged are not always working...)
