### ISSUE TITLE
Add an indication a request is pending when listing jobs running on Admin

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#11474]
Queries that list currently running jobs on Admin -> Jobs can take a long time but there it is not immediately evident the request is pending. A spinner, grayed-out page, or some similar indication would be nice.

**Comment by dannon** [comment]
I'll add an indicator here.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11205
