### ISSUE TITLE
disabled upload button in rule builder without explanation

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11476]
Unclear why the upload button is disabled (took me a minute to figure out "missing url"). We should show that somewhere in the UI that "you cannot upload until you set one column as the URL"

![image](https://user-images.githubusercontent.com/458683/109126798-f44ff500-774d-11eb-85a1-28256544a962.png)

Edit: yes, it says it at the top but no one reads the instructions.

**Comment by assuntad23** [comment]
@hexylena Do yo think this should be an alert at the top of the modal or would a tool tip suffice?

**Comment by hexylena** [comment]
A tool tip would be great!

tor. 18. mar. 2021, 17:26 skrev Assunta DeSanto ***@***.***>:

**Comment by assuntad23** [comment]
PR # 11682 closed this issue

**Comment by hexylena** [comment]
awesome!! thank you @assuntad23
