### ISSUE TITLE
Leaving iPython window is a showstopper

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#1147]
If you are in iPython, and you click on, for example, link in the Masthead, the center pane changes and you're dead if you have not saved (though even if you saved you cannot restart #1143). Perhaps I masthead icon is needed that would allow you to come back to your existing containers.

**Comment by hexylena** [comment]
So the options are : 
- open in a new window/tab
- open in scratch pad
- we write code to handle this case

**Comment by nekrut** [comment]
Can we try 1 and 2 and see how it goes?

**Comment by hexylena** [comment]
For 1, just click viz, then right click "Open in New Window/Tab", 
for 2 just activate the  scratchpad and it should pop up? I don't use the scratchpad often.

**Comment by hexylena** [comment]
Hopefully @guerler could suggest to @bgruening and @erasche where we could stick a "Warning, you're leaving your page" whenever you attempt to change the main window away from a GIE.

**Comment by martenson** [comment]
alternatively opening ipython can hide the toolpanel and possibly the masthead too, offering single 'save and exit ipython' option instead while providing more canvas space

**Comment by hexylena** [comment]
Sure, we could set all GIEs to open in a new window. It decreases the magic a bit though :/

(Retagged, currently GIEs behave like **every** other Galaxy tool which completely looses your work if you accidentally (or intentionally) navigate away from it. It may seem bad but it's standard behaviour for galaxy tools meaning this is an enhancement.)

**Comment by martenson** [comment]
What Galaxy's UI features are useful when the notebook is opened? refresh history, dataset peeks (and metadata maybe) not much else? We should not clutter their ipython workspace. We can just animate them out (as it happens when you click on the hide arrows at bottom corners).

**Comment by bgruening** [comment]
And you probably want to see your history with the numbers.
I see where the confusion comes from. In the old iframe builds we actually had this notification that when you leave the content will be lost, similar to the workflow editor.

**Comment by bgruening** [comment]
@martenson animate the toolbar and the masthead out would be wonderful.

**Comment by hexylena** [comment]
@martenson if you're using the scratchbook, all of Galaxy's features are useful, no? (as long as you don't change route to edit workflows)

**Comment by nekrut** [comment]
I don't like the new window precisely because you do not see history

**Comment by hexylena** [comment]
@nekrut great, that rules that one out. How about the scratchbook as an intermediate option until we get the notification on navigation implemented?

**Comment by nekrut** [comment]
let's try it!

**Comment by martenson** [comment]
I still lobby for hiding at least the toolpanel :)
ps: ipython in the scratchbook is a killerfeature!

**Comment by nekrut** [comment]
that makes sense

**Comment by bgruening** [comment]
@martenson and now try BAM.iobio and IPython in the scratchbook!

**Comment by bgruening** [comment]
All glory to @guerler for this awesome feature!

**Comment by nekrut** [comment]
on test?

**Comment by natefoo** [comment]
In a scratchbook works beautifully.. It warns you if you would do anything that would kill the frame, even if hidden.

**Comment by nekrut** [comment]
I sooo stupid - i didn't expect that it just works. Soooo coool in scratchbook!

**Comment by martenson** [comment]
it is like scratchbook was designed for ipython :D

**Comment by martenson** [comment]
![screenshot 2015-11-20 16 01 24](https://cloud.githubusercontent.com/assets/1814954/11311937/db4ff5fe-8fa0-11e5-9d87-dc92480d696a.png)

**Comment by bgruening** [comment]
Hilarious!

**Comment by hexylena** [comment]
And impossible with the new proxy. Hmm. The new proxy imposes an artificial limit of running just 1 GIE of a given type at a time (so 1x ipython, 1x rstudio is OK). Is this a use case we actually want to support? :fearful:

**Comment by martenson** [comment]
9 is probably not a usecase, 2 might be reasonable, somebody actually using iPython would know more though

**Comment by nekrut** [comment]
I'n not sure we even need 2

**Comment by hexylena** [comment]
Great, then I won't write in support for it in the proposed replacement proxy. Thanks for feedback.

**Comment by blankenberg** [comment]
I can certainly see myself having several open windows, with different/same histories, especially if there are any long running steps in one notebook; maybe I want to replay a notebook against several different datasets. Some limit (just as with jobs) does seem reasonable though

**Comment by hexylena** [comment]
@blankenberg okay, opened an issue for it. https://github.com/erasche/gie-proxy/issues/2

(Edit: Context for those who don't know why I want to replace the proxy: the current one is unpleasant and node dependencies are a nightmare across systems. I threw together a golang one that can be precompiled for a range of architectures and shipped with Galaxy, making the process much easier. It also has a REST API to allow adding/removing routes while the current nodejs one uses files for IPC)

**Comment by nekrut** [comment]
Fair enough
