### ISSUE TITLE
Missing dependency for some datatype converters

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11479]
When converting `.pdb`, `.gro`, `.xtc`, `.trr` and `.dcd` datatypes between them the conversion fails with:
````
/galaxy-repl/main/jobdir/033/613/33613894/tool_script.sh: line 10: gmx: command not found
````

## Steps
- Use [these datasets](https://usegalaxy.org/u/davelopez/h/test-pdb-and-gro-converters) for testing.
- Edit one of the dataset's attributes.
- Select the `Convert` tab and choose any of the applicable converters (excluding `Convert tabular to CSV`).

**Comment by nsoranzo** [comment]
The converters specify the correct `<requirement type="package" version="2020.4">gromacs</requirement>` , so the problem seems to be that the dependency was not installed on the Galaxy server (Main I believe) after upgrading to 21.01 .

**Comment by simonbray** [comment]
Interesting, doesn't the dependency get installed automatically when the tool is run?

**Comment by mvdbeek** [comment]
Only on dev instances, auto installation has a lot of problems on production servers that aren't really solvable.

**Comment by mvdbeek** [comment]
I'd say this is not a really bug but a deployment issue. Should we close this ?

**Comment by simonbray** [comment]
@davelopez didn't you also encounter an issue running it locally? otherwise I agree we should close

**Comment by mvdbeek** [comment]
That was maybe not clear, dev instance means you've either enabled a container resolver, or set conda auto install.

**Comment by mvdbeek** [comment]
We also test all the converters in CI, so this surely works in principle.

**Comment by davelopez** [comment]
Ok, I'll close it then, thanks for clarifying!

**Comment by mvdbeek** [comment]
I've added a small hint to usegalaxy.org's install instructions: https://github.com/galaxyproject/usegalaxy-playbook/wiki/Updating-Galaxy-Main#installing-andor-updating-internal-tool-dependencies
