### ISSUE TITLE
Expose tool id in the tool help

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#11472]
Currently, to get the tool id, one has to either run the tool and then copy the tool id from the dataset info page or figure out the id out form the tool link. Neither is ideal. Displaying the tool id as part of the tool help section, next to the citation would be much more accessible.

**Comment by OlegZharkov** [comment]
on it

**Comment by bgruening** [comment]
Why not putting it on the same spot as the tool-link? Get link, get tool ID?
![grafik](https://user-images.githubusercontent.com/469983/109141381-f752e180-775d-11eb-83f5-03ca20a50b2c.png)

**Comment by OlegZharkov** [comment]
> Why not putting it on the same spot as the tool-link? Get link, get tool ID?
> ![grafik](https://user-images.githubusercontent.com/469983/109141381-f752e180-775d-11eb-83f5-03ca20a50b2c.png)

well, that's exactly what I was about to do :)

**Comment by afgane** [comment]
Thank you all for a rapid UX improvement!
