### ISSUE TITLE
Upload button tooltip blocking search box

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#11493]
There are 2 buttons in the top left corner of the screen: upload data and show sections. They have almost identical styling and identical mouseover effect. However, one has a tooltip, the other one does not, which feels inconsistent. More importantly, the tooltip appears right on top of the search box, effectively blocking it (and with the mouse over the tooltip, it won't disappear). Worse, I've noticed that when I need to search for a tool, the mouse cursor, in most cases, will travel across that button, triggering the tooltip and blocking the search box, unless moving at a high enough speed. Having to move the mouse up, then down just to get rid of the tooltip becomes a little annoying after several tool runs.

![image](https://user-images.githubusercontent.com/6132258/109251945-62320600-77ba-11eb-891c-4b99eeb35fa9.png)

This is my first formal UI gripe! :smile:

**Comment by mvdbeek** [comment]
I think that tooltip is pretty silly too, I don't think `Download from URL or upload files from disk` adds any information that `Upload Data` doesn't provide. I'll remove it.
