### ISSUE TITLE
Clear Search button in History does not clear search text in some cases

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11504]
I am not sure if this is intended behavior.
## Steps
- Write something in the History `search datasets` box (but do not press enter)
- Use the `clear search` button.
- Nothing happens. Here I will expect the input search text to be cleared.

![image](https://user-images.githubusercontent.com/46503462/109339530-12117d00-7868-11eb-8d53-986fa7f228d6.png)

Similar behavior happens in the `search histories` and `search all datasets` from the Histories panel. In these cases, after pressing enter and then use the clear search button, the search results are successfully cleared but the search text remains.

![search](https://user-images.githubusercontent.com/46503462/109341465-c1e7ea00-786a-11eb-842d-aa6c94ebf92d.gif)

Also notice a little glitch when searching histories where the next history from current slightly moves behind the current history.

**Comment by dannon** [comment]
It should definitely clear the box in addition to it being the actively applied search -- sounds like a bug.  Is there anything in the developer console?

**Comment by davelopez** [comment]
Nothing shows up in the developer console :(
