### ISSUE TITLE
Error loading/executing workflow

### ISSUE THREAD

**Issue by kxk302** [galaxyproject/galaxy#11502]
@innovate-invent reported this error when executing his workflow:

"err_msg": {"cut_type_options|list": "parameter 'list': invalid options ('4,5,1') were selected (valid options: 1,4,5)"}, "err_code": 0, "err_data": {"5": {"cut_type_options|list": "parameter 'list': invalid options ('4,5,1') were selected (valid options: 1,4,5)"}}}

I re-produced the problem with the attached workflow and input files. Please remove the .txt extension from the workflow/input files (they were added as Github does not accept those file types as attachment).

The problem is that in ColumnListParameter's get_legal_values(), the column values is a string of comma separated integers (instead of being a list). Added code to handle this situation.

[example.gff3.txt](https://github.com/galaxyproject/galaxy/files/6050220/example.gff3.txt)

[Cluster_islands.ga.txt](https://github.com/galaxyproject/galaxy/files/6050218/Cluster_islands.ga.txt)

[example.fasta.txt](https://github.com/galaxyproject/galaxy/files/6050223/example.fasta.txt)

P.S. It seems a previous attempt was made to fix this issue: https://github.com/galaxyproject/galaxy/pull/11341

**Comment by innovate-invent** [comment]
Great! Can you push your fix so I can test it out?

**Comment by kxk302** [comment]
@innovate-invent I am creating a Pull Request next, so it can be reviewed, before its pushed.
