### ISSUE TITLE
WF best practices UI - Attempt to auto-fix causes temporal loss of metadata

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11503]
First of all, this feature is simply AMAZING!

During the release testing, I run into a strange little issue:

## Steps
- Use [this simple Workflow](https://gist.github.com/davelopez/fd488690bdff60578a59bf0545f45535) for testing.
- Go to `Workflow Options -> Check for Best Practices`
- Notice this WF has correct `Metadata - Annotations` but `Input Metadata` and `Outputs` are not so good.
- Select `Attempt to fix any issue that can be automatically fixed.`
- Notice the `License` and `Creator` metadata is now gone and checking for best practices again will report that.

![wf_best](https://user-images.githubusercontent.com/46503462/109316271-bb964580-784b-11eb-8ec8-adff4eb5a482.gif)

**Comment by jmchilton** [comment]
Oh dear, good catch. I'll try to take a pass at this today.
