### ISSUE TITLE
imported workflows losing their tags

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#11505]
If I import workflows they lose their tags.

**Comment by mvdbeek** [comment]
How does that happen ? Through sharing ? It does seem to work fine for me.

**Comment by bgruening** [comment]
I imported a public workflow in my user-account.

**Comment by jmchilton** [comment]
Yeah - I just tried this on usegalaxy.org and can confirm the tags were lost on import.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11663
