### ISSUE TITLE
Improve wheel/venv-related flags to common_startup.sh

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#1150]
The current set of flags do not allow enough flexibility and cause problems for some environments where we really want to allow people to start w/o a virtualenv (e.g. if they are using Conda, or just really don't want a venv). Additionally, `--skip-venv` is not accurately named - it causes the script to skip creation of a venv but doesn't skip requirement of the venv.

New/modified flags should be:
- `--no-create-venv` (default is to create): Do not create .venv
- `--no-replace-pip` (defaults to replacing pip): Do not replace pip with Galaxy pip, wheels with C extensions will be built from source on most platforms.
- `--skip-venv` (default is to not skip): Skip checking `$VIRTUAL_ENV` (implies `--no-create-venv` and `--no-replace-pip`).
- ~~`--unpinned-requirements` (default is pinned): Install requirements without explicit version pinning.~~

~~To support `--unpinned-requirements`~~ we should rename `requirements.txt` to `pinned-requirements.txt` and create a new `requirements.txt` that does not pin exact versions, but properly uses the comparison operators to specify known incompatibilities.

Additional work related to using `extras_require` to install galaxy with pinned or unpinned dependencies (e.g. `pip install galaxy[unpinned]`) will be done later in relation to #921.

Related issue galaxyproject/planemo#377

**Comment by natefoo** [comment]
@jmchilton `lib/galaxy/requirements.txt` will be renamed to `lib/galaxy/pinned-requirements.txt`, but do you recall whether we took a position on the root `requirements.txt`. In the long run this should be the unpinned version, but in the short term I think it may make sense to continue to point it at the pinned version. Reason being that if someone is installing a Galaxy server and sees `requirements.txt` there's a non-zero chance they'd try to `pip install -r` it.

**Comment by jmchilton** [comment]
@natefoo But isn't that what we would want them to do?

**Comment by natefoo** [comment]
It is and... for some reason I thought we'd want them to get the pinned versions, but I think that's incorrect, we want unpinned unless you are in a release branch.

**Comment by jmchilton** [comment]
My position was that they should always get unpinned versions in requirements.txt not just in dev - but that docker-galaxy-stable and your ansible playbook (and hence main) would use the pinned versions.

**Comment by natefoo** [comment]
Ok. We do depend on two modified versions of dependencies (pysam and Whoosh), I am not sure how to make unpinned versions of these (especially since using something like `git+https://` for pysam would mean it'd have to be compiled.

**Comment by jmchilton** [comment]
@natefoo Can you just pin those two dependencies for now?

**Comment by natefoo** [comment]
That's what I was thinking.
