### ISSUE TITLE
Problem building metadata commands on 21.01 for older version of salmon. 

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#11510]
This is probably a model store bug but I thought the model store stuff wouldn't be written without extended metadata on?

```
RefactoringTool DEBUG 2021-03-01 14:27:03,636 Refactoring auto_translate_cheetah
galaxy.jobs.runners ERROR 2021-03-01 14:27:03,818 (3442089) Failure preparing job
Traceback (most recent call last):
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 242, in prepare_job
    stderr_file=stderr_file,
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 283, in build_command_line
    stderr_file=stderr_file,
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/jobs/command_factory.py", line 128, in build_command
    __handle_metadata(commands_builder, job_wrapper, runner, remote_command_params)
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/jobs/command_factory.py", line 235, in __handle_metadata
    kwds={'overwrite': False}
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/jobs/__init__.py", line 2103, in setup_external_metadata
    **kwds)
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/metadata/__init__.py", line 167, in setup_external_metadata
    'id': dataset_collection.id,
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/model/store/__init__.py", line 1397, in __exit__
    self._finalize()
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/model/store/__init__.py", line 1248, in _finalize
    collections_attrs_out.write(to_json(self.collections_attrs))
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/model/store/__init__.py", line 1233, in to_json
    return json_encoder.encode([a.serialize(self.security, self.serialization_options) for a in attributes])
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/model/store/__init__.py", line 1233, in <listcomp>
    return json_encoder.encode([a.serialize(self.security, self.serialization_options) for a in attributes])
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/model/__init__.py", line 4489, in serialize
    collection=self.collection.serialize(id_encoder, serialization_options),
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/model/__init__.py", line 4330, in serialize
    elements=list(map(lambda e: e.serialize(id_encoder, serialization_options), self.elements))
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/model/__init__.py", line 4330, in <lambda>
    elements=list(map(lambda e: e.serialize(id_encoder, serialization_options), self.elements))
  File "/mnt/galaxy/tmp/galaxyworks2/galaxy/server/lib/galaxy/model/__init__.py", line 4765, in serialize
    rval["child_collection"] = element_obj.serialize(id_encoder, serialization_options)
AttributeError: 'NoneType' object has no attribute 'serialize'
```

**Comment by mvdbeek** [comment]
We changed that so that we don't need to pickle HDA objects anymore (https://github.com/galaxyproject/galaxy/pull/11288)

**Comment by mvdbeek** [comment]
Do you have the version of salmon at hand and the commit of the server ?

**Comment by jmchilton** [comment]
It should be toolshed.g2.bx.psu.edu/repos/bgruening/salmon/salmon/1.3.0+galaxy1 and I just double checked that it is the latest 21.01 (20313d24e607ee1b6fca29f3b23d814a6323a99e). Also this was in a workflow so it might be an issue with this step being called too soon and that collection not being populated yet? Hmm...

**Comment by mvdbeek** [comment]
Maybe we need to skip serializing `None` at this point or serialize it to null ? https://github.com/mvdbeek/galaxy/blob/3ce3718a62ead922e51427a9c7a9e99aaecc635c/lib/galaxy/model/__init__.py#L4764 
Looks a bit like the assumption was that it can only be a HDA or a DatasetCollection

**Comment by jmchilton** [comment]
So it failed on a second workflow run so it is an at least semi-consistent problem. It works fine to re-run the tool after the workflow has finished - then the red job runs fine.

If you're running a dataset collection as input and the backbone isn't yet populated - isn't that always going to be a problem? I guess maybe this is just a job running on part of the collection and the rest of the collection isn't ready - and this is the only time we've tried to serialize that containing collection. Seems questionable to serialize the whole containing collection when just running a small part - but I guess I did that for a reason? Hmm...

**Comment by mvdbeek** [comment]
> guess maybe this is just a job running on part of the collection and the rest of the collection isn't ready

But in that case we are probably not writing out the whole collection. Can you share the workflow with me ?

**Comment by jmchilton** [comment]
It isn't my workflow to share unfortunately - and it has a bunch of non-standard tools anyway. I will say the failing step is being mapped over by a list with on element.

I tried to make a simplified version that just had all the inputs leading up to the problematic step and one output after the problematic step. And it didn't fail when I ran the simplified version through the GUI so that was infuriating. I wonder if there is a difference between running it in the GUI and running it via workflow tests (maybe the parameters for the output filters are slightly different?).

I'll keep the issue updated as I make progress.

**Comment by jmchilton** [comment]
I reran the workflow with a more verbose exception message and with a forced a flush before metadata generation to rule that out as the problem. The workflow still failed and failed with the following information:

```Failing to serialize dataset collection element {'model_class': 'DatasetCollectionElement', 'element_type': None, 'element_index': 0, 'element_identifier': 'el1', 'id': 2742680} becuase element_object is None```

**Comment by jmchilton** [comment]
Some more added logging for future debugging purposes:

```
galaxy.metadata INFO 2021-03-09 02:24:45,726 writing output name output_quant
galaxy.metadata INFO 2021-03-09 02:24:45,732 writing output collection output_gene_quant
RefactoringTool DEBUG 2021-03-09 02:24:45,767 Refactoring auto_translate_cheetah
```

**Comment by jmchilton** [comment]
```
    <outputs>
        <data name="output_quant" format="tabular" from_work_dir="output/quant.sf" label="${tool.name} on ${on_string} (Quantification)" />
        <data name="output_gene_quant" format="tabular" from_work_dir="output/quant.genes.sf" label="${tool.name} on ${on_string} (Gene Quantification)">
            <filter>geneMap</filter>
        </data>
```

It is interesting that output_gene_quant is an empty collection when adding outputs but output_quant is a dataset. This seems like a real problem. They are identical entities in the input declaration.

**Comment by jmchilton** [comment]
In the tool action for that job - that dataset is being filtered out.

```
job_handler_1.log:galaxy.tools.actions INFO 2021-03-12 22:39:25,163 Filtering output [output_gene_quant] for toolshed.g2.bx.psu.edu/repos/bgruening/salmon/salmon/1.3.0+galaxy1
job_handler_1.log:galaxy.tools.actions INFO 2021-03-12 22:39:25,163 Filtering output [output_bam] for toolshed.g2.bx.psu.edu/repos/bgruening/salmon/salmon/1.3.0+galaxy1
job_handler_1.log:galaxy.tools.actions INFO 2021-03-12 22:39:25,163 Filtering output [postSample] for toolshed.g2.bx.psu.edu/repos/bgruening/salmon/salmon/1.3.0+galaxy1
```

**Comment by jmchilton** [comment]
Indeed - quant is unfiltered at the collection level but filtered at the output level. I guess this explains the problem. 

Looks like a Runtime value, disconnected input is to blame. 

```
galaxy.tools.execute INFO 2021-03-13 13:15:40,728 for mapping - filtering output_quant? False - geneMap <galaxy.tools.parameters.basic.RuntimeValue object at 0x7f8a47521fd0>
galaxy.tools.execute INFO 2021-03-13 13:15:40,752 for mapping - filtering output_gene_quant? False - geneMap <galaxy.tools.parameters.basic.RuntimeValue object at 0x7f8a47521fd0>
galaxy.tools.execute INFO 2021-03-13 13:15:40,777 for mapping - filtering output_bam? True - geneMap <galaxy.tools.parameters.basic.RuntimeValue object at 0x7f8a47521fd0>
galaxy.tools.execute INFO 2021-03-13 13:15:40,778 for mapping - filtering postSample? True - geneMap <galaxy.tools.parameters.basic.RuntimeValue object at 0x7f8a47521fd0>
```
