### ISSUE TITLE
Use decompress attribute for more than compare="diff" on test outputs

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#11521]
Currently the `decompress` attribute of test outputs is only used for `compare="diff"`

https://github.com/galaxyproject/galaxy/blob/7c5a65f4c4ba8fb3f7d7e4816b914d00144c7d24/lib/galaxy/tool_util/verify/__init__.py#L239

It would be useful for many other cases: e.g. assertions (e.g. `has_n_columns` for zipped vcf files). 

One could for instance just try to decompress at the beginning of the verify function: https://github.com/galaxyproject/galaxy/blob/7c5a65f4c4ba8fb3f7d7e4816b914d00144c7d24/lib/galaxy/tool_util/verify/__init__.py#L47

**Comment by jmchilton** [comment]
This seems like an oversight - I think moving decompress to work over all the attributes would be great.

**Comment by bernt-matthias** [comment]
> This seems like an oversight.

Maybe. At least its properly documented in the xsd:  ´When this attribute is true and compare is set to diff, try to decompress files if needed.´
