### ISSUE TITLE
Workflow editor: tool box not updating correctly when changing tool settings

### ISSUE THREAD

**Issue by shiltemann** [galaxyproject/galaxy#11538]
Ran into this using Unicycler tool, changing the tools settings from the default 'paired' to 'paired collection' successfully updates the box to reflect the required inputs, but subsequently changing it back doesn't update the box. 

To reproduce:
  1. Start a new workflow and open the editor
  2. Add the Unicycler tool
  3. Change the parameter "Single or paired datasets?" from "paired" to "paired collection" 
     -> the box changes accordingly (the top two inputs for forward an reverse reads disappear, and get replaced with collection input)
  5. Change the parameter back --> box should change back but doesn't
  
Here is a gif from this on Main:

![workflow-editor-unicycler](https://user-images.githubusercontent.com/2563865/109947904-1ad7d800-7cda-11eb-8ab6-694036c8c0c7.gif)

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11542
