### ISSUE TITLE
Duplicating WF step leads to linked output labels

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11565]
I think a copy.copy (or js equiv) is missing somewhere. Those output labels are linked. Also it deleted the labels for the step + output that I had, and they reverted to `out_file1`.

![image](https://user-images.githubusercontent.com/458683/110342432-ad0a1400-802b-11eb-82ce-6154c8e0e0d5.png)

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11602
