### ISSUE TITLE
Lack of control over WF report columns

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11564]
I wrote something I expected to be rather linear and it's come out like this

![image](https://user-images.githubusercontent.com/458683/110341443-a0d18700-802a-11eb-8769-069bdfa86ad0.png)

I think two columns _can_ be super nice, but maybe we could have more control over this then? Probably forcing it to a linear layout is easiest for me though. I'd much rather that than weird whitespace stuck in the middle.

**Comment by mvdbeek** [comment]
Agreed, I also thought this is a odd layout.

**Comment by jmchilton** [comment]
@guerler is this intentional or just a CSS bug?

**Comment by shiltemann** [comment]
upvote from me. I used section headers expecting them to just be put underneath eacht other. 

The table on the left has quite a lot of columns and I really want to have it use the full width of the page, with the next section & table underneath. 

![image](https://user-images.githubusercontent.com/2563865/120165586-03868900-c1fc-11eb-8b47-bd4d838cfba1.png)

**Comment by hexylena** [comment]
I poked at this, all of the cards have a `w-50` and `float-left`, so, this seems that it was intentional (and I can understand that from the perspective of many small cards like workflow info which aren't very wide) but I think it's suboptimal. Any opposition to making those `w-100` without `float-left`?

This looks a lot better to me / it's more easy to reason about as an author

![image](https://user-images.githubusercontent.com/458683/120171949-db4e5880-c202-11eb-84ff-332f5d798881.png)

**Comment by dannon** [comment]
+1; if we do want columnar formatting at particular breakpoints we should handle it differently anyway (constraining the content column itself to wrap, instead of individual elements floating)
