### ISSUE TITLE
Logs flooded with PulsarJobRunner.monitor_thread "Received status update"

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#11579]
Still testing gxits with pulsar, after running a few jobs and stopping them, the logs of my galaxy are flooded with this kind of messages (1 per job per second):
```
[PulsarJobRunner.monitor_thread] (19077) Received status update: <class 'str'> cancelled
```
It looks like it comes from : https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/runners/pulsar.py#L307

I guess it could be as easy as removing this line, but maybe galaxy should just stop watching these jobs instead somehow?

**Comment by mvdbeek** [comment]
> I guess it could be as easy as removing this line, but maybe galaxy should just stop watching these jobs instead somehow?

That was definitely the intention, thanks for the report!

**Comment by mvdbeek** [comment]
I think you've fixed that in https://github.com/galaxyproject/galaxy/pull/11763 ?
