### ISSUE TITLE
Set element_identifier for multiple = true tool collection inputs

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#11606]
Currently in a tool wrapper, if a collection is provided to a multiple = true input, it does not provide the collection name in the element_identifier attribute of the input object.

The collection name can be meaningful to tools that are built with the intent of wrapping it in a galaxy tool wrapper.

**Comment by bernt-matthias** [comment]
Hi @innovate-invent I guess this is already here https://github.com/galaxyproject/galaxy/issues/7467

**Comment by innovate-invent** [comment]
@bernt-matthias I don't believe this is the same issue. I am referring to the tool wrapper command template.
The template is passed a variable that represents the tool input. For datasets and collection elements there is a `element_identifer` attribute, but not collection inputs. I need to be able to access the input collection name in the tool command template.

**Comment by mvdbeek** [comment]
Then you need a collection input. There's no way around it.

**Comment by innovate-invent** [comment]
I am linking to this issue from a published article. Do you mind providing a brief technical explanation of what prevents this?

**Comment by mvdbeek** [comment]
`multiple="true"` inputs do not have access to the collection when they are being evaluated.

**Comment by innovate-invent** [comment]
Thanks
