### ISSUE TITLE
Feedback on new history panel (beta version)

### ISSUE THREAD

**Issue by jkh1** [galaxyproject/galaxy#11632]
Just tried the new history panel that was just rolled out as beta. Here are a couple of comments:
The new history panel doesn't show the history content anymore. I can only see it by clicking the "show structure" button but this goes into the middle panel which is also used to view data. So now it's much harder to view a series of files since one now needs to go back and forth between viewing data and viewing history whereas before one could just click on a file in the history panel and have its content displayed in the middle panel.
If the history panel now just displays a list of small icons and the history name, I think it's wasting screen real estate and could just as well be turned into a "History" menu in the top bar.
Also there are just too many too small icons next to each other with the "view structure" one well hidden at the end. It's also a bit dangerous as the small icons are easier to fat finger and some of the icons are for deletion operations.
At least for me, this is not a UX improvement.

**Comment by bgruening** [comment]
@jkh1 can you clear your browser cache?

It should look like that:

![grafik](https://user-images.githubusercontent.com/469983/111298787-75185780-864f-11eb-94a6-dc593e153642.png)

**Comment by jkh1** [comment]
I did log in fresh from a different computer.

**Comment by jkh1** [comment]
This seems to be related to using Firefox. I just tried in Opera and I do see the history content. Though I am still not happy with it because now I have to click the small dots to be able to view a file. I think having the eye icon next to the file name was better.

**Comment by bgruening** [comment]
It works for me on Firefox, not sure how we can enforce a cache reset. The missing eye icon is a regression, I agree with that. But this is exactly why we have the new history as a preview. We are seeking comments, especially about performance. The style will be adopted until the next release. Please keep any feedback coming.

You can also post here: https://github.com/galaxyproject/galaxy/issues/10947

Thanks for your feedback.

**Comment by jkh1** [comment]
Not a cache issue. Clearing cache or starting fresh (with nothing in the cache)  still the same. However, I see some errors in the web console. Will post in #10947.

**Comment by Nerdinacan** [comment]
@jkh1 @bgruening 

Agreed. I've noticed some scrolling clumsiness as well. I've been working this last week or two on smoothing that out. I believe I'm making progress. Will update you when I have a good sample.

**Comment by dannon** [comment]
I think we've resolved the concerns here in the latest incarnation of the new history.
