### ISSUE TITLE
Column numbers of tabular files not displayed

### ISSUE THREAD

**Issue by foellmelanie** [galaxyproject/galaxy#11644]
Hi, 

after the lastest Galaxy update on the EU server, the column numbers of tabular files are not displayed anymore in the main panel. They are visible only in the history preview but this does not allow to select the right column number for files with many columns.
![Screenshot from 2021-03-17 09-44-35](https://user-images.githubusercontent.com/16114269/111439988-309bc300-8706-11eb-9a3c-4d5f7064b5f1.png)

**Comment by davelopez** [comment]
Hi @foellmelanie!
I think this is a duplicate https://github.com/galaxyproject/galaxy/issues/11443
And definitely sounds like a good papercut :)

**Comment by ic4f** [comment]
I'm closing this one since it's a duplicate, but I'll explicitly link it from the other issue, since it has an alt description and a screenshot, which is very helpful (thank you @foellmelanie!)
