### ISSUE TITLE
release docs show incorrect warning

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#11645]
This document shouldn't have this notification.

![January_2021_Galaxy_Release__v_21_01__—_Galaxy_Project_21_01_documentation](https://user-images.githubusercontent.com/1814954/111450541-c6d4e680-8710-11eb-805d-e347c3332e4f.png)

**Comment by mvdbeek** [comment]
Thanks, that's a remnant of the Jenkins setup: https://github.com/galaxyproject/galaxy/blob/dev/doc/source/conf.versioning.py#L11
