### ISSUE TITLE
Workflow steps reconnecting broken in 21.01

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#11658]
Steps to reproduce:

1. In the WF editor build any kind of 3 steps mini-WF.
2. When everything is connected, switch any two of the steps.

Outcome:

While initially things will look correct, you will see that there's a problem when you try to move the reconnected step boxes, which will leave a noodle pointing nowhere behind.
Also, when saving such a WF the altered connections will be lost upon reopening.

**Comment by mvdbeek** [comment]
Thanks @wm75, that should be fixed in https://github.com/galaxyproject/galaxy/pull/11660
