### ISSUE TITLE
clarify the data libraries folder navigation

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#11659]
Before redesign this element served the purpose of "going to the parent folder" - it was aligned with the dataset entries and mimicked the folder navigation in common file system browsers. Currently it is confusing so we could either redesign it to fit in again, or design a different way of quick navigation, or just remove it and fall back to breadcrumb navigation.

![Galaxy](https://user-images.githubusercontent.com/1814954/111599978-31e5f200-87d1-11eb-8508-fb8582e3eeb2.png)

**Comment by nsoranzo** [comment]
That's already been removed on dev. Feel free to reopen though.

**Comment by martenson** [comment]
@nsoranzo thanks for the info!

**Comment by OlegZharkov** [comment]
@martenson you can follow the discussion in https://github.com/galaxyproject/galaxy/issues/10800
