### ISSUE TITLE
consider renaming masthead "Analyze Data" to "Home"

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#11666]
I am sorry in advance for this bikeshedding-enabling issue. 

During gitter exchange we identified that "Analyze Data" is not very fitting label for a home button and not everyone is used to clicking on a logo as a way home. Furthermore even widely used websites like TW and YT have dedicated "HOME" buttons close to the logo for easy navigation to the landing page.

Hence the proposal of changing the label of "Analyze Data" to "Home". Alternatively we can come up with a different way of addressing this confusion.

**Comment by hexylena** [comment]
Maybe this would be a good opportunity to use the help forum to discuss a design decision?

**Comment by dannon** [comment]
Personally I expect the logo to the top left to always go home, but if this is a real problem for folks we need to address it in some way.  Going to assemble a few options here:

![image](https://user-images.githubusercontent.com/155398/111633064-7e2e3380-87cb-11eb-986d-7c9b452dfba7.png)

**Comment by nsoranzo** [comment]
I thought I posted a commented, but it disappeared?
Any way, I was going to suggest a home icon (which saves screen estate), so I'm very happy with the first mock-up above.

**Comment by martenson** [comment]
> Side note; on looking at this it really bugs me that logo_url is a thing. That potentially not going home breaks expectations (that at least I have). Is there a good use case for this?

+1 on breaking that, but I'd expect some custom Galaxies to actually use this :/

**Comment by assuntad23** [comment]
I like the home icon, too! It fits in with the icons on the right side.

**Comment by AnnaSyme** [comment]
I like the home icon

**Comment by bernt-matthias** [comment]
+1 for home icon

**Comment by martenson** [comment]
Changed with #11674, thank y'all for input.
