### ISSUE TITLE
License and creator info lost when renaming a workflow

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#11668]
Import, e.g., this iwc WF: https://github.com/galaxyproject/iwc/raw/main/workflows/sars-cov-2-variant-calling/sars-cov-2-pe-illumina-artic-variant-calling/pe-artic-variation.ga
which has license and creator defined.
A natural first thing to do is rename the WF (which has the *imported from uploaded file* in its name), but doing so discards the metadata.

**Comment by jmchilton** [comment]
I'll try to take a stab at this one today - I thought I had already fixed something like this with renaming but maybe it was tags.

**Comment by mvdbeek** [comment]
Thanks @wm75! Should be fixed in https://github.com/galaxyproject/galaxy/pull/11670
