### ISSUE TITLE
Workflow editor - list-valued workflow step parameters discarded when loading workflow

### ISSUE THREAD

**Issue by eschen42** [galaxyproject/galaxy#11672]
Summary: With v21.01, for a workflow stop ([advanced cut](https://toolshed.g2.bx.psu.edu/repository?repository_id=2593fd36ae8011aa)), a list-valued parameter (a list of columns to be cut or retained) is discarded when loading workflow into editor. Exporting the workflow after editing ([attached](https://github.com/galaxyproject/galaxy/files/6164975/Galaxy-Workflow-cut_out_columns_2_and_3.zip)) reveals that the list values (`2,3`) are stored in the workflow (which runs as expected), but upon loading it into the editor, they are lost from the parameter list for the step.

Note that when this tool is run interactively, a multi-select list potential values for this field is populated by scanning the input dataset (or its attributes) to determine the valid columns so that the user can point and click rather than potentially making errors while typing column numbers and figuring out correct comma-separated-value syntax.  In the workflow editor, by contrast, the user needs to specify a comma-separated list of column numbers.

My suspicion is that the `data_ref="input"` attribute for the `param` element of the tool XML is causing the editor to reset the field on load.

This occurs for me on both usegalaxy.eu and usegalaxy.org, both of which give the api/version response:
```
{"version_major": "21.01", "extra": {}}
```

**Comment by mvdbeek** [comment]
Could have sworn we already had an issue for this, but that's not a new bug. I'll take a look

**Comment by mvdbeek** [comment]
Thanks for the report @eschen42! Should be fixed in https://github.com/galaxyproject/galaxy/pull/11692
