### ISSUE TITLE
More Documentation for workflow invoke?

### ISSUE THREAD

**Issue by i-am-b-soto** [galaxyproject/galaxy#1167]
Greetings Galaxy developers. 
Some Colleagues and I are developing PHP wrappers for Galaxy functions through web services. However we have been running into issues implementing some of the functions as we are uncertain the full parameter list and the format of these parameters needed. Specifically functions such as invoke (in workflows module)
We have examined the source code and the documentation provided at   http://galaxy.readthedocs.org/en/dev/api_doc.html but are still a bit stuck at the moment. Is there another place we can check for further documentation or would it be possible to provide an example function call to invoke? 

Many thanks for your time!

**Comment by hexylena** [comment]
If you are familiar with python enough to read the documentation, you might read through BioBlend (the Galaxy python API library)'s documentation. 
- https://bioblend.readthedocs.org
- https://github.com/galaxyproject/bioblend/tree/master/bioblend/galaxy

If there are specific functions you're unclear on the purpose of, please let us know and we can correct/update documentation.

Edit: Ah, workflow invocation in particular. https://github.com/galaxyproject/bioblend/blob/master/bioblend/galaxy/workflows/__init__.py

**Comment by i-am-b-soto** [comment]
Thank you for the timely response. 
I have looked at bioblend before, though I was unsure of how up-to-date it was with the galaxy API and how closely it matched galaxy's code. 
In other words, if I pass in the parameters in the format listed on bioblend's documentation directly to the galaxy's invoke, the galaxy invoke function should run appropriately?

**Comment by hexylena** [comment]
@Kungfunub bioblend is kept extremely up-to-date relative to Galaxy's API. Their maintainers are quite active in responding to issues/galaxy API changes.

> In other words, if I pass in the parameters in the format listed on bioblend's documentation directly to the galaxy's invoke, the galaxy invoke function should run appropriately?

Correct.

**Comment by i-am-b-soto** [comment]
Thank you!
