### ISSUE TITLE
Sharing Pages returns 404

### ISSUE THREAD

**Issue by OlegZharkov** [galaxyproject/galaxy#11685]
Steps to reproduce:
1) Users -> Pages -> Add new page -> Save
2) Click on `Share or Publish`
3) get 404 
![image](https://user-images.githubusercontent.com/15801412/111787667-e3ffe580-88c7-11eb-93a2-4327fdc440f0.png)
 
That seems to work fine on 'org' and 'eu'. So either dev is broken or maybe I am doing smth wrong

EDIT:
can confirm, it works on 21.01, broken on dev

**Comment by davelopez** [comment]
Yes, this may be broken on dev since is using the new FastAPI routes and this `/sharing` route does not exist.
Probably was not documented? Anyway, I'll have a look :)

**Comment by davelopez** [comment]
It seems those Mixins I so lightly dismissed from the legacy PagesController bit me off hard now... 😓 

I found out that the API endpoint that now is missing was declared in [SharableMixin](https://github.com/galaxyproject/galaxy/blob/f4e1d2c6b3fbbaef087776d5eb54ff486224ab23/lib/galaxy/webapps/base/controller.py#L1411) along with a couple more endpoints that will be surely missing too.

I am not used to working with this kind of pattern so I didn't realize they were there and I didn't add a proper test, my apologies for that.

I will try to fix the mess... somehow 😅
