### ISSUE TITLE
Testtoolshed: reset password shows internal server error

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#1169]
Try to reset password on a non-existing email will show an internal server error instead of a proper warning/error message

**Comment by scholtalbers** [comment]
well apparently the account should exist - as I cannot create a new one with the same email account.

**Comment by scholtalbers** [comment]
uhm ok: 
- For the existing account, resetting the password will result in an internal server error. 
- Resetting the password on a non-existing account, will result in a green message telling an e-mail has been sent.

**Comment by martenson** [comment]
The green for non existing account is by design, we do not leak emails. I will look into the non working reset. Thanks for reporting.

**Comment by hexylena** [comment]
Fixed in #1170
