### ISSUE TITLE
export as "List of Pairs" from data libraries

### ISSUE THREAD

**Issue by OlegZharkov** [galaxyproject/galaxy#11699]
@assuntad23 Can you please take a look?
if you export datasets from data libraries as "List of Pairs", you get 

![image](https://user-images.githubusercontent.com/15801412/112002987-22480f80-8b29-11eb-8e87-d49a6d5eb8f5.png)

**Comment by OlegZharkov** [comment]
fixed by https://github.com/galaxyproject/galaxy/pull/11700

**Comment by dnbenso** [comment]
Hi Folks... Sorry to be a bother.  On my Galaxy server I now get either 1) a message saying "Galaxy could not be reached and may be updating. Try again in a few minutes." or 2) A collection created but with 'fastq.gz' files that point to what looks like standard error from files in another history.
On usegalaxy.eu I have only got the first option.  That is the error message, and if I create a new history for the collection the new history is created.

**Comment by mvdbeek** [comment]
Thanks @dnbenso, these are 2 different issues.

> "Galaxy could not be reached and may be updating. Try again in a few minutes."

Happens when you select a new history. The history is created but the correct history id is not passed into the list creator component.

> A collection created but with 'fastq.gz' files that point to what looks like standard error from files in another history.

There is a confusion between history datasets (HDAs) and library datasets (LDDAs)

**Comment by dnbenso** [comment]
Thanks so much for sorting this out.  It's working well on my Galaxy server
now.  If I'd had the skills to help I would have - maybe one day soon.
Thanks for the explanation too.
