### ISSUE TITLE
Job resource params working on and off

### ISSUE THREAD

**Issue by eancelet** [galaxyproject/galaxy#11709]
Hi all,

In my Galaxy instance, I tried to add some tool resource parameters. It worked for some tools but not for others.
I think I found the reason of this behavior.

When the [tool form is populated](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/__init__.py#L1360), we compare the wrapper tool id to the tool id list in job_conf.xml to know if they are linked to resource parameters. 
When this [job_conf file is parsed](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/__init__.py#L476), tool ids are converted to lowercase which is not the case when the tool wrapper is parsed.

As a solution, I would suggest [this modification](https://github.com/galaxyproject/galaxy/compare/dev...eancelet:eancelet-patch-1?expand=1).

Can anyone tel me if I'm right?

Hope that was clear enough. Let me know if not.

**Comment by mvdbeek** [comment]
Hi @eancelet I think that looks fine, I'd just change `resource_xml = self.app.job_config.get_tool_resource_xml(root.get('id').lower(), self.tool_type)` to `resource_xml = self.app.job_config.get_tool_resource_xml(root.get('id', '').lower(), self.tool_type)` so that you don't get
`AttributeError: 'NoneType' object has no attribute 'lower'`.

**Comment by eancelet** [comment]
Thanks @mvdbeek.
> Most bug fixes should target the oldest supported release exhibiting the issue

(from the Contributing Guidelines)
Should I target the release_20.01?

**Comment by mvdbeek** [comment]
Yes, that would be perfect!

**Comment by eancelet** [comment]
Hello,
The tests failed but I'm not sure it is due to my commit. Can anyone check?

**Comment by mvdbeek** [comment]
Thanks again! Fixed in https://github.com/galaxyproject/galaxy/pull/11793
