### ISSUE TITLE
Link to upload1 tool broken in tool list

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#11705]
Just noticed (thanks to one of our users) that the link to the upload1 tool from the tool list is not working:

![image](https://user-images.githubusercontent.com/238755/112123926-12c8d500-8bc2-11eb-8c9f-1d6dd93ab537.png)

Clicking on it does nothing, no js error, and no error on the server. Tested on our instance and usegalaxy.eu/org

The big "upload data" button is working great though.

**Comment by natefoo** [comment]
Fixed in #11830
