### ISSUE TITLE
Reports: date_trunc causes OperationalError: no such function with sqlite

### ISSUE THREAD

**Issue by carlfeberhard** [galaxyproject/galaxy#1171]
No one who really needs reports should be using sqlite, but makes error/QA checking the app more difficult for developers.

Steps:
- start reports
- go to 'Runs per workflow'

-> 

```
OperationalError: (sqlite3.OperationalError) no such function: date_trunc [SQL: u'SELECT date_trunc(?, date(galaxy_user.create_time)) AS date, count(galaxy_user.id) AS num_users \nFROM galaxy_user GROUP BY date_trunc(?, date(galaxy_user.create_time)) ORDER BY date DESC'] [parameters: ('month', 'month')]
```

**Comment by martenson** [comment]
I think reports are postgres only (out of the box). Given how little dev time reports are (and will be) getting I am in favor of `wontfix` and drop sqlite support completely.
What do you think?

**Comment by carlfeberhard** [comment]
@martenson Understandable - kind of amazing we can get three (?) different sql flavors to work together at all. This makes it more inconvenient to even smoke test things that crosscut our apps (like the webpack pr) - but still not impossible.

**Comment by jmchilton** [comment]
It does support MySQL now also, I merged the community PRs. I'm fine with #wontfix and happy to keep this closed but it would be nice to have and sqlite is more practical now that I think we have solved the locking issues.

**Comment by martenson** [comment]
sadly, @jmchilton,  I do not see anybody from the team working on reports. And if somebody does I will urge him/her to work on something else. :)
