### ISSUE TITLE
Using S3 Object Store using ec2 instance credentials instead of hardcoded access_key and secret_key

### ISSUE THREAD

**Issue by crashGoBoom** [galaxyproject/galaxy#11713]
Hello!
Curious if there is any way to allow using an s3 object store when running galaxy on an ec2 instance in AWS without passing in hard coded `access_key` and  `secret_key`? I would like to allow boto to just use the ec2 instances credentials. Any information or a work around would be helpful. Thanks!

**Comment by mvdbeek** [comment]
@nuwang @almahmoud do you have any insights there ? This seems like a good idea.

**Comment by almahmoud** [comment]
Note: I know very little about how Object Store is implemented in Galaxy (@VJalili might have more insight on that specifically?).
Are you running on an EC2 instance directly or on the Kubernetes stack on EC2? If the latter, I can try to help you accomplish what you want maybe with deployment modifications, if you were to kind of describe your end goal?

**Comment by crashGoBoom** [comment]
> I know very little about how Object Store is implemented in Galaxy (@VJalili might have more insight on that specifically?).
> Are you running on an EC2 instance directly or on the Kubernetes stack on EC2? If the latter, I can try to help you accomplish what you want maybe with deployment modifications, if you were to kind of describe your end goal?

Hi! This is running on an EC2 instance directly.

I believe we would simply need to remove the reference to the `access_keys` and `secret_keys` when `S3Connection` is used and boto should fall back to using the ec2 instance credentials. I wont be able to get back to this until next week (I could probably get a PR out for it at that point ) but if anyone has additional insight that would really helpful. Thank you so much!

**Comment by crashGoBoom** [comment]
This was merged so I am going to close this out.  💥
