### ISSUE TITLE
Search Tool Shed (Beta) Cannot Load Different Revision for any Tool

### ISSUE THREAD

**Issue by Wigg12** [galaxyproject/galaxy#11726]
I am using a local Galaxy environment at port 80.

I can select tools in the Search Tool Shed (Beta) and install the default revision, but it is never the most recent version. When I try to pick a different revision  for a tool (the most recent) from the pull-down all information and fields for the tool disappear. Some of my tools are at versions that do not work.

**Comment by mvdbeek** [comment]
Hi @Wigg12, versions of Galaxy that still contain the `Search Tool Shed (Beta)` are not supported anymore. We'd recommend updating Galaxy to a later release.
