### ISSUE TITLE
Trying to copy+paste from the tool stdout in job info page closes it before finishing copying

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11723]
I think it should be click to open, but not click to close, making it hard to know if I hit ctrl-c, if it will be copied.

![Peek 2021-03-24 17-28](https://user-images.githubusercontent.com/458683/112346667-74726780-8cc6-11eb-8945-e2722ed4dc61.gif)

**Comment by mvdbeek** [comment]
It should be click to close, but not on drag. If I scroll along a  list of jobs I want to close the things I am not interested in.
We discussed a separate button for closing, which would work.

**Comment by hexylena** [comment]
fair enough @ closing uninteresting, I think personally i'd prefer a separate button  (I'm liable to tap when I mean to scroll on mobile and I have a bad habit of clicking text as I read it.) but that's not generally applicable.
