### ISSUE TITLE
the upload tool entry in tool panel does not work

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#11729]
If you click on the upload tool itself (that is e.g. target url: https://usegalaxy.org/tool_runner?tool_id=upload1) you will get no response. This is confusing since it should probably provide the same functionality as the new dedicated button. 

After seeing this, one is inclined to remove the upload1 tool, but that has other consequences, since e.g. bioblend depends on it.

**Comment by martenson** [comment]
dupe of https://github.com/galaxyproject/galaxy/issues/11705

**Comment by mvdbeek** [comment]
fwiw we can hide it, that has no impact on API functionality.

**Comment by martenson** [comment]
If you mean hidden="true" then yes. But removing the tool should break things iuuc.

**Comment by martenson** [comment]
Nevertheless even if we hide it in the sample, only new Galaxies will have it hidden. Old ones would need to change their config or have the historically most used tool non-responsive.
