### ISSUE TITLE
K8S Runner: Handle API overload

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#11735]
Galaxy 21.01
```
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/jobs/runners/__init__.py", line 136, in run_next
    method(arg)
  File "/srv/galaxy/lib/galaxy/jobs/runners/kubernetes.py", line 139, in queue_job
    job.create()
  File "/srv/galaxy/venv/lib/python3.8/site-packages/pykube/objects.py", line 97, in create
    self.api.raise_for_status(r)
  File "/srv/galaxy/venv/lib/python3.8/site-packages/pykube/http.py", line 106, in raise_for_status
    raise HTTPError(resp.status_code, payload["message"])
pykube.exceptions.HTTPError: The POST operation against Job.batch could not be completed at this time, please try again.
```

Galaxy can overwhelm the k8s api server when scheduling jobs and the resulting exception is unhandled.
I am not sure if the job should be marked failed, allowing Galaxy's rescheduler logic to handle it, or if a retry loop should exist in the runner queue_job function.

Ideally Galaxy should catch uncaught exceptions upstream and apply the rescheduler logic. Currently the job just fails permanently.

Relevant: https://github.com/kubernetes/kubernetes/issues/45811
https://github.com/kubernetes/kubernetes/issues/95492

https://github.com/galaxyproject/galaxy/issues/7685

**Comment by innovate-invent** [comment]
@mvdbeek do you think reducing maximum_workflow_jobs_per_scheduling_iteration to say 200 would alleviate this?
What is the consequence of lowering this number?

**Comment by mvdbeek** [comment]
I don't think that would help, I'd assume this happens with bursts of submissions. I would think that even 200 would be leading to submissions that are too fast ? Do you know if there any rate limits in place ? If you modify https://github.com/brinkmanlab/galaxy/commit/a2e331818b90fa4e2893d8c3ef4f668f8f9fb40e to return without failing the job submission should be retried (haven't tested that, but if it does it'd be straightforward to add a per-destination rate-limit).

**Comment by innovate-invent** [comment]
Thinking about it some more, a per destination rate limit would be a good feature to have, but I think a well defined mechanism for the plugin to handle "busy" errors is a better approach.
