### ISSUE TITLE
Paired List Builder Picking Prefix Too Short

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#11744]
<img width="1676" alt="Screen Shot 2021-03-27 at 4 50 34 PM" src="https://user-images.githubusercontent.com/216771/112734521-aa108e00-8f1c-11eb-884e-ed31405e020f.png">

Ideally this would have auto-paired as ``UII_Dir_1ug_1`` presumably. Even ``UII_Dir_1ug_`` or ``UII_Dir_1ug`` I might not consider a bug - but ``UII_Dir`` is seemingly broken to my eyes.

**Comment by jmchilton** [comment]
I had a report that an older version of Galaxy didn't function this way. But looking at the 20.09 code:

Remove extensions was still really aggressive (and looks largely the same as 21.01):

https://github.com/galaxyproject/galaxy/blame/release_20.09/client/src/mvc/collection/list-of-pairs-collection-creator.js#L571

and remove extensions seemed to be the default:

https://github.com/galaxyproject/galaxy/blame/release_20.09/client/src/mvc/collection/list-of-pairs-collection-creator.js#L261

**Comment by dannon** [comment]
Fixed in #11773
