### ISSUE TITLE
Shared Workflow retaining original name and not renamed name

### ISSUE THREAD

**Issue by GarethPrice-Aus** [galaxyproject/galaxy#11752]
I wanted to help some GTN content so I did the following:
1 - Access https://training.galaxyproject.org/training-material/topics/variant-analysis/tutorials/exome-seq/tutorial.html#quality-control
2 - Download and import into my Galaxy instance (Galaxy Australia, running 21.01) the two workflows.
3 - I modified one workflow (below) and wanted to share as Feedback on the GTN page
4 - Workflow originally called
4a - exome-seq-training-full-w-cached-ref-imported-from-uploaded-file (which bares no connection to its file name or its descriptor on the GTN). Made a Copy, worked on copy until 4b
4b - Renamed to: ExomeSeq_QC_to_mapped
4c - Enable Sharing via link
4d - Presented with link id: https://usegalaxy.org.au/u/gareth-qfab/w/copy-of-exome-seq-training-full-w-cached-ref-imported-from-uploaded-file

This does not reflect the Workflow name and makes it difficult to track and hardly reproducable.

Maybe a good one for Papercuts?

Thanks, Gareth

**Comment by mvdbeek** [comment]
@GarethPrice-Aus  That seem to work on 21.05, and I think we've had some fixes that even applied before that. Any chance you can verify this works on usegalaxy.org ?
