### ISSUE TITLE
Restrict/grant user access to file sources using roles or groups

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11768]
Currently, there is a `writable` option when configuring a file source plugin like, for example:
````YAML
- type: posix
  id: posix1
  label: Posix
  doc: Files from local path
  root: /some/path/
  writable: true
````
This allows making the file source read-only or writable, but this restriction will be applied to all users. So, when `writable: true` every user will be able to write to that file source which may be inconvenient.

## Proposed functionality
It will be really interesting to provide access only to specific groups of users or roles and one easy way of doing it is by adding two new (optional) configuration options to the file source:

 ````YAML
  requires_roles: some_role
  requires_groups: some_group
````

- If those options are not present, the behavior will be the same as the actual, so everyone will have access to the file source.
- If any of the options are defined, only users with the specific roles or groups will be able to list, access, and/or write.
- If both options are defined, only users that satisfy both conditions are granted access.
- If any of the options are defined, but there is no user context the access will be granted to preserve the current behavior.
- If the `writable` option is disabled, even users that have access will not be able to write.
- Admin users will always have access (write permission will always depend on the `writable` option).

## Bonus points
Will be nice to use some basic boolean logic (`not`, `or`, `and`) to define the access rules like:
````YAML
requires_groups: not GROUP
````

````YAML
requires_groups: GROUP or GROUP1
````

**Comment by bgruening** [comment]
implemented in #11769
