### ISSUE TITLE
Hiseq Count continous error

### ISSUE THREAD

**Issue by GOVINDMAHENDRASINGH** [galaxyproject/galaxy#11774]
Hi,
I am using HISAT2 BAM input files and GTF format reference annotation file  of maize genome (Zm-B73-REFERENCE-NAM-5.0) for Hiseq count for RNA expression analysis.
I have double checked the format. BAM HISAT2 output file and GTF annotation file.
But i getting continous error in Hiseq count saying 

[bam_sort_core] merging from 32 files and 1 in-memory blocks...
100000 GFF lines processed.
200000 GFF lines processed.
300000 GFF lines processed.
400000 GFF lines processed.
500000 GFF lines processed.
600000 GFF lines processed.
700000 GFF lines processed.
800000 GFF lines processed.
900000 GFF lines processed.
1000000 GFF lines processed.
Error occured when processing GFF file (line 1008439 of file /galaxy-repl/main/files/054/183/dataset_54183511.dat):
  start is larger than end
  [Exception type: ValueError, raised in _HTSeq.pyx:67].

Annotation file i downloaded from  ncbi assembly " Zm-B73-REFERENCE-NAM-5.0"  https://www.ncbi.nlm.nih.gov/assembly/GCF_902167145.1/

pls suggest me how to proceed

**Comment by mvdbeek** [comment]
> start is larger than end

Your GFF file is invalid. I would report this to the NCBI.
