### ISSUE TITLE
Period at the end of paired-list item names 

### ISSUE THREAD

**Issue by assuntad23** [galaxyproject/galaxy#11781]
Follow-up from #11773
There should be no trailing period. 

![image](https://user-images.githubusercontent.com/26912553/113465968-fe78a980-9405-11eb-9b56-29cce5bd1fa8.png)

**Comment by jmchilton** [comment]
Thanks for creating this issue @assuntad23!

**Comment by mvdbeek** [comment]
@assuntad23 any chance you can take a look at this and https://github.com/galaxyproject/galaxy/issues/12135 ?

**Comment by assuntad23** [comment]
I think this is easily solved, just by using the filters? 

Since the name is autogenerated with the filters in mind; if you use the .1.fastq/.2.fastq filter it doesn't add the period.

![Screenshot from 2021-06-16 12-19-22](https://user-images.githubusercontent.com/26912553/122256642-42c00580-ce9d-11eb-8559-d331e53f5730.png)
