### ISSUE TITLE
Whitespace is not visible in RBU and causes upload failure

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11809]
The urls look fine here, right?

![2021-04-08_18-06_1](https://user-images.githubusercontent.com/458683/114060105-5182ae80-9895-11eb-916e-85bd91de811a.png)

But it fails, and only for the :eagle: :eyes: notice the whitespace

![2021-04-08_18-06](https://user-images.githubusercontent.com/458683/114060111-534c7200-9895-11eb-8eca-8c0b6d975459.png)

I had to open the post request inspector to see what it was complaining about and that it wasn't just a ui issue.

![2021-04-08_18-07](https://user-images.githubusercontent.com/458683/114060115-53e50880-9895-11eb-852f-4cb616ba6a09.png)

**Resolution**

Should we auto-strip whitespace? lstrip()? Make it more visible in UIs?

**Comment by bgruening** [comment]
This is also true in the normal URL-paste upload form.

**Comment by bernt-matthias** [comment]
Is this related to my recent gitter question?

**Comment by afgane** [comment]
For the URL-paste form, this was fixed (at least once): https://github.com/galaxyproject/galaxy/issues/8196

**Comment by bernt-matthias** [comment]
Thanks @afgane. Will the API test that will be added here  https://github.com/galaxyproject/galaxy/pull/11818 cover this?

> Is this related to my recent gitter question?

No

**Comment by ic4f** [comment]
Fixed in #12474 (strips whitespace from both ends)
