### ISSUE TITLE
Summary Statistics tool failing to find rpy2

### ISSUE THREAD

**Issue by code4dna** [galaxyproject/galaxy#11804]
Hi, for our Galaxy v20.09, Summary_Statistics1 is installed by default but the dependencies do not seem to be available even though Manage Dependencies shows rpy2 @2.9.4 is installed for Summary_Stastics1

```
Traceback (most recent call last):
  File "/general/sw/hprc/galaxy/kaiser/galaxy/tools/stats/gsummary.py", line 10, in <module>
    from rpy2.rpy_classic import BASIC_CONVERSION, NO_CONVERSION, r, RException, set_default_mode
ModuleNotFoundError: No module named 'rpy2.rpy_classic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/general/sw/hprc/galaxy/kaiser/galaxy/tools/stats/gsummary.py", line 13, in <module>
    from rpy import BASIC_CONVERSION, NO_CONVERSION, r, RException, set_default_mode
ModuleNotFoundError: No module named 'rpy'
```

**Comment by mvdbeek** [comment]
I would recommend reinstalling this rpy2 version. I tested this against https://quay.io/repository/biocontainers/rpy2?tag=2.9.4&tab=tags and it works correctly, and we have internal jenkins build testing against rpy2 installed from Conda.

**Comment by code4dna** [comment]
Thanks, reinstalling the rpy2 2.9.4 conda dependency through the admin interface didn't fix it. It's works now by changing the requirement in the gsummary.xml tool to our lmod rpy2 module.
