### ISSUE TITLE
Support for archives with multiple files when uploading.

### ISSUE THREAD

**Issue by broodjeaap** [galaxyproject/galaxy#1180]
It would be very useful to have an option to not unpack an archive when uploading an archive or turning it into a collection of all the files in the archive.

I used to work around this with a custom upload tool where I had commented out some code in upload.py, but this recently stopped working on the XML side:
![uploadzip](https://cloud.githubusercontent.com/assets/1033693/11421581/23d39a76-9436-11e5-9d54-5eb54d07004e.png)

This goes much further than commenting out some lines (in a separate tool) so I thought I'd bring it up here.

Reading around, there was another issues about archive support, a recent one was: 
https://github.com/galaxyproject/tools-iuc/pull/354

**Comment by broodjeaap** [comment]
Kind of a solution, when uploading your archives select "peptideshaker_archive" as data type.

**Comment by mvdbeek** [comment]
Also see PR #1442 ... I guess this is a commonly requested feature.

**Comment by hexylena** [comment]
fixed in #1665
