### ISSUE TITLE
LSF CLI OOM resubmission leaves downstream jobs paused instead of allowing them to proceed once resubmission succeeds

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#11834]
We have been successfully using resubmission in 19.x versions with our LSF cluster for a couple of years. However when trying now 20.09 we see that the same datasets on the same workflow, for a workflow A->B->C, when resubmitting A due to OOM, B and C are left paused with the message:

> Input dataset 'Scanpy Read10x on data 5, data 4, and others: anndata_h5ad AnnData' is in error state. To resume this job fix the input dataset(s).

However that job A has been successfully resubmitted and finished.

To make this work in March 2019 I had to make some changes in jobs/runners/cli.py as shown in:

https://github.com/galaxyproject/galaxy/pull/6866/files#diff-ffa83d3b10370ee42672282a77b1fa8286a1005c8296bd7d943ea7833b2e4928

But my changes don't seem to be there anymore.

**Comment by pcm32** [comment]
The last version that we know this was working with is 19.05.

**Comment by pcm32** [comment]
Ok, at some point as well I also added these changes:

https://github.com/galaxyproject/galaxy/pull/7832/files

20.09 still looks like that... I'm attempting to remove that part to make it look like the current dev and see whether that fixes it.

**Comment by pcm32** [comment]
Removing the self.work_queue.put((self.mark_as_failed, ajs)) breaks the resubmission (it doesn't happen), so it is even worse.

**Comment by pcm32** [comment]
So my questions would be:

On which runners does resubmission currently works?

How are they triggering the resubmission? Do they use the `self.work_queue.put((self.mark_as_failed, ajs))`?

Was there a change at some point that made job handlers more sensitive such that it wouldn't wait for resubmissions and just stay with transient error state? On which files should I be looking for changes in the job handlers? This is similar to what we described with the model tools a while back.

**Comment by pcm32** [comment]
Also as information, our resubmission instructions come from dynamic destinations (python code type).

**Comment by pcm32** [comment]
This seems somehow related, but it seems to me it was merged before 19.05:

https://github.com/galaxyproject/galaxy/commit/c1614be1ef5abaab241bf9739fb99390a8954343

**Comment by pcm32** [comment]
Yes, those changes are all on my 19.05 installation where things work.

**Comment by mvdbeek** [comment]
None of this has changed. Was you 19.05 setup already running Python 3 ?

**Comment by pcm32** [comment]
In the `lib/galaxy/jobs/runners/state_handlers/resubmit.py` they only changes between my 20.09 and 19.05 are:

```
103,104c100
<         # Is destination needed here, might these be serialized to the database?
<         destination = resubmit.get('environment') or resubmit.get('destination')
---
>         destination = resubmit['destination']
159c155
< class _ExpressionContext:
---
> class _ExpressionContext(object):
```

No, 19.05 installation runs on python 2.7.
```

**Comment by pcm32** [comment]
On `/lib/galaxy/jobs/handler.py` the only changes between 20.09 and 19.05 there are changes related to ` def __initialize_job_grabbing(self)` , where that was replaced maybe with a class?

**Comment by pcm32** [comment]
To summarise I think, the resubmission still seems to rely on the job being marked as failed, but then this marking as failed now triggers subsequent jobs to be paused indefinitely, whereas in the past they just kept waiting and I never saw them going into a pause state. I suspect that if the resubmission is fixed not to require the mark as failed, this would also sort out the problem I reported some months ago about model tools.

**Comment by pcm32** [comment]
Shouldn't maybe this https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/handler.py#L378 be refreshed if any jobs go through the resubmission loop https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/handler.py#L403 ?

**Comment by pcm32** [comment]
When removing the mark_as_failed, resubmit.py failure() https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/runners/state_handlers/resubmit.py#L61 never gets called. I cannot find what is supposed to be calling that method to debug upstreams.... any clues on what is between the check watch items that used to be marking that as failed and the calling of the resubmit failure? Thanks

**Comment by pcm32** [comment]
I tried putting the `__filter_jobs_with_invalid_input_states` after the the resubmission loop, but the behaviour is the same, it just pauses downstream jobs at the first resubmission. Could it be that in 19.05 jobs were not tracked in the database and now all jobs are tracked in the database? That would explain the filtering call happening/not happening.

**Comment by pcm32** [comment]
Going back to runners that I know that have resubmission working:

- UNIVA / DRMAA: it has the self.work_queue.put((self.fail_job, ajs)) when the job fails https://github.com/galaxyproject/galaxy/blob/e557f3eb60fbb277ed69149e9d2f1459b11f518e/lib/galaxy/jobs/runners/drmaa.py#L246

- CONDOR: also does the `self.work_queue.put((self.fail_job, cjs))` https://github.com/galaxyproject/galaxy/blob/e557f3eb60fbb277ed69149e9d2f1459b11f518e/lib/galaxy/jobs/runners/condor.py#L191

So I think that the resubmission doesn't work without that call to fail_job. However, some filtering became at some point more sensitive to the transient failure needed for the resubmission. Or please show me a runner that has working resubmissions without the `fail_job` call. Thanks!

**Comment by pcm32** [comment]
Things I have found so far:

- I saw the execution run once with a resubmission and not showing the error (so it might be some race condition). I only managed to see this once, then it always failed.
- I have set handlers to 1 and still fails, so it is not a race between handlers.
- Resubmissions are successful and `job_state.runner_state_handled` invariably gets set to `True`.
- However, in the database, the resubmitted job is shown in Error state, as you see:

```
==> galaxy_handler0-stderr---supervisor-b5ere41l.log <==
galaxy.jobs DEBUG 2021-04-22 18:09:04,861 Pausing Job '593', Input dataset 'Scanpy Read10x on data 5, data 4, and others: anndata_h5ad AnnData' is in error state. To resume this job fix the input dataset(s).
```

 which is generated at:
https://github.com/galaxyproject/galaxy/blob/4fbcb32a8fd77d7077fdddac8b8fcaf257e9db05/lib/galaxy/jobs/handler.py#L520

**Comment by pcm32** [comment]
So at some point the state of the job is being left as Error in the database, but based on what Marius said, this should never happen if job_state.runner_state_handled is set to True.

**Comment by pcm32** [comment]
I have found the issue:

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/runners/cli.py#L174-L182

The error handling needs to go before the change_state call, or otherwise the change_state call turns the job into ERROR as the reasons for the error hadn't been handled yet (and `job_state.runner_state_handled` is not yet set to True when change_state happens). Not sure why this wasn't manifesting entirely on our 19.05 instance, but only with model jobs.

**Comment by pcm32** [comment]
PR incoming!

**Comment by mvdbeek** [comment]
I suppose you've fixed this in https://github.com/galaxyproject/galaxy/pull/11886, thanks again @pcm32!
