### ISSUE TITLE
[New history] uploaded dataset in not shown on the new history panel

### ISSUE THREAD

**Issue by OlegZharkov** [galaxyproject/galaxy#11836]
During my selenium tries, I faced a bug. When I upload a new dataset to the empty history, it doesn't appear on the new history panel. I tried to upload multiple files, the same effect. I only see them if I reload the whole page. The bug doesn't seem to happen if the history is not empty.

Sorry if it's a duplicate. Feel free to close it, if there is an existent issue in place.

![bugupload](https://user-images.githubusercontent.com/15801412/114720342-9e0c3500-9d40-11eb-946f-11b006c03139.gif)

**Comment by bernt-matthias** [comment]
It appeared to me that I had the same, but not the first added dataset, while testing https://github.com/galaxyproject/galaxy/pull/11818.. But not 100% sure.

**Comment by OlegZharkov** [comment]
fixed in https://github.com/galaxyproject/galaxy/pull/11850
