### ISSUE TITLE
Database version conflict(?) while installing Galaxy on server

### ISSUE THREAD

**Issue by EmmettPeng** [galaxyproject/galaxy#11862]
Hi Galaxy project mates!

I was just installing galaxy(21.01) on my ubuntu server and when I finished editing galaxy.yml and when running `sh run.sh`, it reported error. The stdout was shown below.
[run_log.txt](https://github.com/galaxyproject/galaxy/files/6336300/run_log.txt)

I noticed a line:
`galaxy.model.migrate.check INFO 2021-04-19 21:14:50,306 [pN:main,p:117617,w:0,m:0,tN:MainThread] At database version 172`

```
'migrate_tools'), ('required_dbs', '[]')]))])
Traceback (most recent call last):
  File "/newdatabase/newgalaxy/galaxy/.venv/lib/python3.6/site-packages/migrate/versioning/schema.py", line 50, in load
    data = list(result)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 50, in app_factory
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "lib/galaxy/app.py", line 102, in __init__
    self._configure_models(check_migrate_databases=self.config.check_migrate_databases, check_migrate_tools=check_migrate_tools, config_file=config_file)
  File "lib/galaxy/config/__init__.py", line 1252, in _configure_models
    verify_tools(self, install_db_url, config_file, install_database_options)
  File "lib/galaxy/tool_shed/galaxy_install/migrate/check.py", line 29, in verify_tools
    db_schema = schema.ControlledSchema(engine, migrate_repository)
  File "/newdatabase/newgalaxy/galaxy/.venv/lib/python3.6/site-packages/migrate/versioning/schema.py", line 33, in __init__
    self.load()
  File "/newdatabase/newgalaxy/galaxy/.venv/lib/python3.6/site-packages/migrate/versioning/schema.py", line 54, in load
    exceptions.DatabaseNotControlledError(str(exc)), tb)
  File "/newdatabase/newgalaxy/galaxy/.venv/lib/python3.6/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/newdatabase/newgalaxy/galaxy/.venv/lib/python3.6/site-packages/migrate/versioning/schema.py", line 50, in load
    data = list(result)[0]
migrate.exceptions.DatabaseNotControlledError: list index out of range
```

Does this have anything to do with mysql database version? How can I make it work? Thanks for answers!

Emmett

**Comment by mvdbeek** [comment]
Hi @EmmettPeng, please disable `check_migrate_tools ` https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample#L270.

**Comment by EmmettPeng** [comment]
> Hi @EmmettPeng, please disable `check_migrate_tools ` https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample#L270.

Thanks for your prompt reply and the problem is solved! But now I have another question: I noticed that running tools on Galaxy still uses `/<GalaxyPath>/.venv` as virtualenv instead of the conda environment. I am not sure how I can set the configuration to make galaxy tools under conda environment that I built before.

Emmett

**Comment by nsoranzo** [comment]
@EmmettPeng I think you are mixing things up: Galaxy itself use the `.venv` virtual environment (which could be based on top of a system- or conda-installed Python), while each tool will use its own conda environment, containing the packages specified in the tool requirements.

**Comment by EmmettPeng** [comment]
@nsoranzo Thanks for your reply! So you mean that galaxy's `.venv` virtual environment and the enrivonment that galaxy tools use are two independent ones? Here I installed `Bio` module on my base conda environment but the tool error still reports `Bio` module not found. That was kinda confusing to me. I am totally new to galaxy construction. Hope you can explain this to me more.

Thanks again!
Emmett

**Comment by mvdbeek** [comment]
Take a look at https://docs.galaxyproject.org/en/master/admin/conda_faq.html#how-do-conda-dependencies-work-where-do-things-get-installed, I think that should answer your question.
