### ISSUE TITLE
Update Release Testing Processes to Target Multiple Enviroments

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#11869]
It would be nice to show some progress as part of 21.05 - probably against AnVIL and GVL.

**Comment by ksuderman** [comment]
Yes, we discussed this at the last deployment WG meeting, and I will bring it up again today.  We hope to have test instances running on GCP, AWS, and Jetstream, with at least one Anvil instance running on GCP.

**Comment by jmchilton** [comment]
We did do this right? So I'm going to close this - I hope that process is documented somewhere.

**Comment by ksuderman** [comment]
> We did do this right? So I'm going to close this - I hope that process is documented somewhere.

@jmchilton Yes we did.  I will update the release testing plan to document the process.  Basically just let the Deployment WG know how many instances and what type (AWS, GCP etc) are needed and when.
