### ISSUE TITLE
Order of noodles changes after copying workflow

### ISSUE THREAD

**Issue by foellmelanie** [galaxyproject/galaxy#11889]
Hi, 

I have a workflow in which the order of two input noodles is important. However, everytime I make a copy of the workflow the order of the input noodles changes. 
Here is an example workflow in which noodle of file 2 is on top of noodle of file1: https://usegalaxy.eu/u/melanie-foell/w/v26-new-order-updatedharnblasepreprocessing

![WF_noodle_order](https://user-images.githubusercontent.com/16114269/115891067-f389c580-a455-11eb-985c-882d728107dc.png)

**Comment by mvdbeek** [comment]
These connections (multiple inputs to an input that uses `multiple="true"`) are not ordered in any way. If you need a given order you have to build a collection (https://usegalaxy.eu/root?tool_id=__BUILD_LIST__) and connect that to your MSI combine step.
