### ISSUE TITLE
Shared visualisation displays only a small section

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#11888]
In one of the computational chemistry training materials there is a link to https://usegalaxy.eu/u/sbray/v/hsp90-lig, which looks like this: 

![image](https://user-images.githubusercontent.com/32272674/115886388-28dfe480-a451-11eb-829e-4239465d935c.png)

For some reason the `charts-viewer` div has `height` fixed to 58px. I haven't checked if this applies to other shared visualisations as well, but it would be great if this could be fixed - when the tutorial was first written, it displayed fine.

FWIW if I access it via https://usegalaxy.eu/visualizations/list (i.e. not via the shared link) it looks fine.

**Comment by hexylena** [comment]
Thanks for filing it @simonbray!

**Comment by dannon** [comment]
Weird, I can take a look at this.  Thanks for the report.
