### ISSUE TITLE
make data libraries respect own filters

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#11916]
Combination of filtering on folder contents and "select all" feature is not behaving as expected - namely it selects the invisible datasets too. I suspect one of the most common operations on this screen is to filter, select, and then import to history so if you operate on many datasets currently it requires a lot of clicking.

The use case is illustrated by the screenshot below. 

![Galaxy](https://user-images.githubusercontent.com/1814954/116855977-9a125b00-abfa-11eb-84da-7720ccc30911.png)

**Comment by OlegZharkov** [comment]
A big sorry @martenson, got really distracted. Luckily https://github.com/galaxyproject/galaxy/issues/12014 reminded me about this issue. Thanks a lot for reporting!

**Comment by OlegZharkov** [comment]
fixed in https://github.com/galaxyproject/galaxy/pull/12087
