### ISSUE TITLE
Auto Pair Issues with Building "List of Dataset Pairs"

### ISSUE THREAD

**Issue by nturaga** [galaxyproject/galaxy#1192]
Trying to "build list of dataset pairs" for 12 Fastq files, which is shown in the first 2 screenshots.

![screen shot 2015-11-30 at 11 36 37 am](https://cloud.githubusercontent.com/assets/2746443/11477711/3f5f54aa-9757-11e5-888f-41e2efb66b61.png)

![screen shot 2015-11-30 at 11 36 51 am](https://cloud.githubusercontent.com/assets/2746443/11477706/3f59bc0c-9757-11e5-8338-9f0d8ab49e68.png)

Once I enter the screen to pair the datasets, I choose "Clear Filter" and select "Auto Pair'. 

![screen shot 2015-11-30 at 11 37 15 am](https://cloud.githubusercontent.com/assets/2746443/11477708/3f5a4f46-9757-11e5-8112-b6f1a4a5820f.png)

![screen shot 2015-11-30 at 11 37 24 am](https://cloud.githubusercontent.com/assets/2746443/11477710/3f5f087e-9757-11e5-9465-3d97b029a3d3.png)

The option "Auto pair" matches the pairs incorrectly, which the user realizes and then proceeds to click on "Unpair all".

![screen shot 2015-11-30 at 11 37 33 am](https://cloud.githubusercontent.com/assets/2746443/11477707/3f59d50c-9757-11e5-8133-eec2069ad867.png)

Here, the screen shows that there are now 24 datasets instead of the 12 on each side of the pairing frames. This continues to happen and the user can "Auto pair" and "Unpair" to create 48 datasets on each side, and then 96 and so on. 

![screen shot 2015-11-30 at 11 37 59 am](https://cloud.githubusercontent.com/assets/2746443/11477709/3f5d3738-9757-11e5-90c7-829595370b1e.png)

**Comment by dannon** [comment]
@nitesh1989 Does auto-pair work correctly if you use _R1 _R2 for matching filters instead of _1, _2?

(definitely a bug on the duplicate entries, though)

**Comment by nturaga** [comment]
@dannon Yes, it works well when I autopair using _R1 and _R2.

**Comment by dannon** [comment]
@nitesh1989 Perfect.  Just wanted to make sure we had one bug and not two :)

**Comment by nturaga** [comment]
Also, I do not think the default filter should display "_1" and "_2". This default feature, prevents users from seeing their data when they enter the screen (example in Screenshot number 3. This confuses users who are new to this feature, (from experience in today mornings workshop)
