### ISSUE TITLE
Replacing select2 with multiselect

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11944]
> ooh yay @ removing select2. that one causes me some complexities in the auto admin recording. Looking forward to what replaces it!

Hi @hexylena, where is that select exactly? If you could create a paper-cuts issue, it would be awesome. I'd try to replace it with Vue-multiselect during next event

_Originally posted by @OlegZharkov in https://github.com/galaxyproject/galaxy/issues/11939#issuecomment-833407192_

The select in specific @hexylena was looking at auto-clicking the genome selection dialog in [BWA mem](https://usegalaxy.eu/?tool_id=bwa_mem)

![screenshot of firefox with bwa mem tool open, and dev tools inspecting the select2 element, it's quite complex DOM for a select box.](https://user-images.githubusercontent.com/458683/117282419-02647500-ae65-11eb-924d-597d75396035.png)

**Comment by hexylena** [comment]
I struggled with scrolling it nicely (I'm using playwright.dev) and don't know, maybe the replacement is simpler and I look forward to testing it out!

**Comment by dannon** [comment]
The form element here will be replaced as a part of the tool form rewrite (https://github.com/galaxyproject/galaxy/issues/11076) this tertile, using vue-multiselect.

**Comment by hujambo-dunia** [comment]
Already addressed as part of Forms Modernization project.
