### ISSUE TITLE
[RFC] BIOM datatype metadata

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#1196]
We should define some additional metadata values for the BIOM datatype. see http://biom-format.org/documentation/format_versions/biom-1.0.html

At the bare minimum, I think we should store "type".  It is also tempting to consider storing 'rows' with metadata, 'columns' with metadata, 'matrix_type', 'matrix_element_type', 'shape', etc...perhaps all options except for 'data'.

xref https://github.com/galaxyproject/tools-iuc/issues/299 and https://github.com/galaxyproject/tools-iuc/issues/432

**Comment by bgruening** [comment]
Follow your temptation Dan!

**Comment by blankenberg** [comment]
xref https://github.com/galaxyproject/galaxy/pull/1198

**Comment by hexylena** [comment]
I guess fixed in #1198 / later edits
