### ISSUE TITLE
The tools of Get Data can't hide.

### ISSUE THREAD

**Issue by shenweiyan** [galaxyproject/galaxy#11976]
I want to hide some tools in Get Data section on local instance of Galaxy, but it doesn't work，no matter how I comment the `integrated_tool_panel.xml` and `tool_conf.xml` files.

![image](https://user-images.githubusercontent.com/26101369/118247288-983b7800-b4d5-11eb-9f4d-15773b2e9aa5.png)

Is this a bug? Or is there any way to achieve the effect I want? Thank you.

**Comment by mvdbeek** [comment]
Do not edit the integrated_tool_panel.xml file. Editing the appropriate tool conf file will work. For tools installed from the tool shed that would be the shed_tool_conf.xml file, for tools shipped by galaxy that is your tool_conf.xml file.

**Comment by shenweiyan** [comment]
Thank you very much.
