### ISSUE TITLE
Converting untranslated UI

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#11982]
Hey folks - there is a lot in the main galaxy pages that don't translate - for instance, 
![Screenshot 2021-05-14 at 14 27 13](https://user-images.githubusercontent.com/44605769/118277243-7edc0100-b4c0-11eb-9b36-1361ba780b37.png)

_Originally posted by @nomadscientist in https://github.com/galaxyproject/galaxy/issues/11891#issuecomment-841218011_

**Comment by hexylena** [comment]
Help would be appreciated to 

1. Identify untranslated fields (very easy! Go to usegalaxy.eu, change the language, and note down everything that's in the wrong language)
2. Convert these to translatable fields, e.g.:

   - https://github.com/galaxyproject/galaxy/tree/dev/client/src/nls
   - https://github.com/galaxyproject/galaxy/blob/a277c2421af56c1d2d97bead0248fb25d721ab04/client/src/mvc/dataset/dataset-li-edit.js#L469

**Comment by nomadscientist** [comment]
> Help would be appreciated to
> 
> 1. Identify untranslated fields (very easy! Go to usegalaxy.eu, change the language, and note down everything that's in the wrong language)
> 2. Convert these to translatable fields, e.g.:
>    
>    * https://github.com/galaxyproject/galaxy/tree/dev/client/src/nls
>    * https://github.com/galaxyproject/galaxy/blob/a277c2421af56c1d2d97bead0248fb25d721ab04/client/src/mvc/dataset/dataset-li-edit.js#L469

Ok, so I had a crack at Step 1: https://github.com/galaxyproject/training-material/pull/2652
I'm going to start the team on filling in the translations, but I'm not sure how to format it so it will work (i.e. Step 2).

**Comment by hexylena** [comment]
@nomadscientist for step 2 we need people familiar with the codebase and javascript a bit to help. We should register this in the cofest under the UI-UX cluster, maybe someone can either help or maybe teach you how to make the relevant changes.

**Comment by nomadscientist** [comment]
Ace, yes, thank you Helena! We'll get it translated first then, because I don't have Galaxy as a repo so wouldn't put the doc anymore, and then send it on its way.

**Comment by hexylena** [comment]
We could move it to a google sheet or something? To make the collaboration easier?

**Comment by nomadscientist** [comment]
Get out of my head! https://docs.google.com/document/d/1cjv_I3toCa11aLbyC5pv17UFID3TH9D7UqTvFCthlCk/edit?usp=sharing

**Comment by nomadscientist** [comment]
It is now completed and peer reviewed, that document of translations

**Comment by hexylena** [comment]
awesome!!!!
