### ISSUE TITLE
Libraries: number of items per page box accepts invalid input

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11993]
You can input non-positive integer values in the `number of items per page` box, for example, `-10`, `e`, `0`:

![image](https://user-images.githubusercontent.com/46503462/118697526-abb94c80-b80f-11eb-9773-52d3423d1388.png)

This can break the pagination.

**Comment by OlegZharkov** [comment]
thanks @davelopez, fixed in https://github.com/galaxyproject/galaxy/pull/11996
