### ISSUE TITLE
Libraries: breadcrum navigation does not work on dataset details.

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11997]
The breadcrum navigation works when navigating folders but fails if we are on a dataset details page.

![issue-libs-02](https://user-images.githubusercontent.com/46503462/118702584-6861dc80-b815-11eb-940c-4a6f3c4539af.gif)

**Comment by OlegZharkov** [comment]
fixed in https://github.com/galaxyproject/galaxy/pull/11998
