### ISSUE TITLE
Libraries: filtering checkboxes behave differently

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#11994]
When the `include deleted` checkbox is checked it triggers an API call, but when it is unchecked it doesn't.
The `exclude restricted` checkbox does not trigger any changes or API calls, so apparently it has no effect.

![image](https://user-images.githubusercontent.com/46503462/118699680-1a97a500-b812-11eb-884b-d5a0aa386f31.png)

**Comment by OlegZharkov** [comment]
> When the include deleted checkbox is checked it triggers an API call, but when it is unchecked it doesn't.

I don't really see an issue here. We pull non-deleted libraries only. If a user really wants to include deleted libs, we have to get them from the server. If we changes his mind, we just hide them. Do you thing I should refresh non-deleted libraries libs once `include deleted` is false?  

> The exclude restricted checkbox does not trigger any changes or API calls, so apparently it has no effect.

Well, if you want to see an effect, you need restricted libraries ;)

![exclude_restricted](https://user-images.githubusercontent.com/15801412/118702500-4b2d0e00-b815-11eb-93ab-8b0fa124565d.gif)

**Comment by davelopez** [comment]
> Do you thing I should refresh non-deleted libraries libs once include deleted is false?

Yes, I was assuming the query was refreshed after a change in the filters like `delete=false` but I see it is not really necessary if it is cached. This may be causing #11995 though or at least it can be related to how the non-deleted libraries are cached?

> Well, if you want to see an effect, you need restricted libraries ;)

Fair point 😆 I see this only filters the already loaded collection of libraries and doesn't really need an API call.
