### ISSUE TITLE
Invalid file upload causes missing file name in History panel

### ISSUE THREAD

**Issue by ksuderman** [galaxyproject/galaxy#12008]
If an invalid HTML file is uploaded by pasting the URL into the upload dialog the file name is displayed in the history panel while the job is waiting to run and while the job is running, but after HTML parsing fails the file name disappears and it is not possible to delete the history item with the 'X' icon.  

This is new in 21.05 and does not happen in 21.01 or the new beta history panel.  

**Steps To Reproduce**
1. Open the upload file dialog
2. Click `Paste/Fetch data`
2. Paste the URL `https://github.com/dlal-group/tools-iuc/blob/f7c06f553b84b93180de7919bc595df31b6aa3f5/tools/simtext/test-data/test_data`
3. Click the `Start` button

The behaviour is slightly different if you paste invalid HTML directly into the upload dialog.  In this case the upload silently fails with no error message and no item in the history.  Pasting the following text into the upload dialog exposes the problem
```
<!DOCTYPE html>
<html>
```
In 21.01 and the beta history panel the above results in a green `Pasted Entry` item in the history.

**Comment by mvdbeek** [comment]
Thanks for the report @ksuderman, fixed in https://github.com/galaxyproject/galaxy/pull/12107
