### ISSUE TITLE
Libraries: downloading a folder with subfolders does not download subfolders

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#12009]
![issue-libs-06](https://user-images.githubusercontent.com/46503462/118822919-dad7c880-b8b8-11eb-9903-086de89ed740.gif)

Only datasets in the current folder are downloaded. I am not sure if this is the intended behavior, but, as a user, I may feel confused. If it is the intended behavior, then maybe just showing some warning when subfolders are selected will be enough.

**Comment by OlegZharkov** [comment]
I guess we need to fix this on backend. What kind of warning do you have in mind? Like a Toast or something?

**Comment by OlegZharkov** [comment]
also this issue seems somehow to be the same one to https://github.com/galaxyproject/galaxy/issues/12007. Would it be a good idea to merge them?

**Comment by davelopez** [comment]
> What kind of warning do you have in mind? Like a Toast or something?

No idea, the warning will be useful only if there is some kind of technical limitation on downloading subfolders or in case it has been previously discussed and decided to not include subfolders for some reason. Maybe @martenson knows more about it?

> also this issue seems somehow to be the same one to #12007. Would it be a good idea to merge them?

I think they are related, but not exactly the same, #12007 is more about the unexpected redirect when something went wrong trying to download. So it can be fixed without having to support subfolder download in case it was decided like so.

**Comment by OlegZharkov** [comment]
fixed in https://github.com/galaxyproject/galaxy/pull/12028
