### ISSUE TITLE
'Name tags' not displaying correctly in non-current histories

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#12002]
In `histories/list`:

![image](https://user-images.githubusercontent.com/32272674/118780054-f37db980-b88b-11eb-90fa-521039eb5f96.png)

the tags for the second (non-selected) history are not shown properly. If I switch to that history and refresh:

![image](https://user-images.githubusercontent.com/32272674/118780251-23c55800-b88c-11eb-90c2-b2442d93dddd.png)

it's the other way around.

In addition, the tags are also not shown correctly in the history panel directly after switching history:

![image](https://user-images.githubusercontent.com/32272674/118780419-52433300-b88c-11eb-9cc6-9c7105081a76.png)

Refreshing the page fixes it.

![image](https://user-images.githubusercontent.com/32272674/118780565-7acb2d00-b88c-11eb-9dd1-7d56b515303f.png)

**Comment by davelopez** [comment]
I think this is fixed now :)

**Comment by simonbray** [comment]
Cool, thanks @davelopez :)
