### ISSUE TITLE
Libraries: non-admin users with `edit` permission can not change the library name or delete

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#12004]
If a non-admin user has `edit` permissions on a library, the UI displays the name as editable and, also, the `Delete` button is enabled.

![image](https://user-images.githubusercontent.com/46503462/118807427-95ab9a80-b8a8-11eb-80fd-ebca28f370d7.png)

Saving the changes or clicking `Delete` will show an error as these two particular actions require admin privileges.

![image](https://user-images.githubusercontent.com/46503462/118807935-34d09200-b8a9-11eb-8b35-eca8cffd6047.png)
Response error: `{"err_msg": "Only administrators can update libraries.", "err_code": 403002}`

It seems reasonable to disable the name textbox and the Delete button in case the user is not an Administrator. Or allow these operations for users with edit permissions, whichever makes more sense :)

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/12023
