### ISSUE TITLE
Libraries: editing a library from `page>1` displays the description of the library at the same row but at `page=1`

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#12005]
Easier to watch than to explain :)

![issue-libs-03](https://user-images.githubusercontent.com/46503462/118809732-487cf800-b8ab-11eb-8b1c-409092b681a6.gif)

**Comment by mvdbeek** [comment]
@OlegZharkov any chance you could take a look at this ? If this is too difficult with the current library this doesn't need to hold up the release, but would be nice to make sure this works.

**Comment by OlegZharkov** [comment]
> @OlegZharkov any chance you could take a look at this ? If this is too difficult with the current library this doesn't need to hold up the release, but would be nice to make sure this works.

Sorry, got distracted by something else and forgot about this issue :)
Thanks a lot for the ping

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/12080
