### ISSUE TITLE
Libraries: the `select all` checkbox when adding datasets to a library from history doesn't behave as expected

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#12006]
![issue-libs-04](https://user-images.githubusercontent.com/46503462/118812861-db6b6180-b8ae-11eb-9fc2-8007a485cbaa.gif)

I will expect the *title column checkbox* to select or unselect all the datasets in the table. In addition, selecting this checkbox allows proceeding without any real dataset selected, which may be a bit confusing.

**Comment by OlegZharkov** [comment]
yeah, this is backbone modal. Hopefully, this will be fixed in https://github.com/galaxyproject/galaxy/pull/11930

**Comment by mvdbeek** [comment]
It might be fixed in https://github.com/galaxyproject/galaxy/pull/11930, but if you think this isn't hard to do I'd totally appreciate a minimal fix for now

**Comment by OlegZharkov** [comment]
fixed in https://github.com/galaxyproject/galaxy/pull/12082
