### ISSUE TITLE
Libraries: trying to download a folder redirects you to an error message

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#12007]
![issue-libs-05](https://user-images.githubusercontent.com/46503462/118814986-0bb3ff80-b8b1-11eb-9f3f-02ed20e45f3c.gif)

**Comment by OlegZharkov** [comment]
yeah, it was like this in the previous implementation. I'm not sure how do we proceed here. I guess, we need backend support for this

**Comment by OlegZharkov** [comment]
@davelopez It was actually a just typo, I wonder why nobody complained before :laughing:

**Comment by OlegZharkov** [comment]
fixed in https://github.com/galaxyproject/galaxy/pull/12028
