### ISSUE TITLE
Libraries: exporting `all datasets in current folder` (as a collection) only exports the visible datasets at the current page

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#12014]
![issue-libs-09](https://user-images.githubusercontent.com/46503462/118831754-50936280-b8c0-11eb-8a7b-ca90e7555b0d.gif)

This may or may not be related to #11916

**Comment by OlegZharkov** [comment]
fixed in https://github.com/galaxyproject/galaxy/pull/12086
