### ISSUE TITLE
Workflow Editor - `Upgrade all workflow steps` seems to be broken

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#12024]
## Steps to reproduce
- Create a workflow
- Add a sub-workflow
- Edit the sub-workflow to increase the version and save it
- Go back to your workflow and select `Upgrade all workflow steps` from the menu.
- Notice the sub-workflow doesn't get upgraded to the last version and **there is no feedback or notification indicating if the operation went wrong**.

![wf-editor-issue-02](https://user-images.githubusercontent.com/46503462/118966440-08c91580-b96a-11eb-9705-00c2cf6a72ab.gif)

The same happens if we try to upgrade when we have a tool without the latest version.

![wf-editor-issue-01](https://user-images.githubusercontent.com/46503462/118966838-4af25700-b96a-11eb-9044-b2417b452614.gif)

**Comment by mvdbeek** [comment]
that's https://github.com/galaxyproject/galaxy/pull/11898#discussion_r632445381, I can pull that out
