### ISSUE TITLE
Workflow Editor - Improve visual feedback when adding boxes

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#12022]
I know it may sound a bit forced... but currently, if you click multiple times on a tool or any other element on the left panel, the box representing the tool is created in the same exact position inside the editor area. This, and the fact that clicking the tool in the panel, doesn't feel like pushing a real button (just a regular text on the screen), may lead to having the same tool inserted multiple times and buried behind one another. This can be confusing for less experienced users and may end up with workflows with orphaned tools.

![wf-editor-paper-cut](https://user-images.githubusercontent.com/46503462/118954843-73745400-b95e-11eb-8c0d-b64f61ce193f.gif)

Probably just adding +/- X random pixels in any direction when creating the box can do the trick or/and make it more evident when selecting an item from the left panel.

**Comment by hexylena** [comment]
Npx down + Npx right would be good, like the old windows tiling algorithm?
