### ISSUE TITLE
Cannot Execute Workflow Using Collection of Paired Lists, But Works on "Analyse Data" Invocation

### ISSUE THREAD

**Issue by quacksawbones** [galaxyproject/galaxy#12035]
Hi folks,

I'm building a data analysis pipeline for analysing paired end reads, and I'm hitting a weird error when I try to use a List of Dataset Pairs. I'm seeing this behaviour in both `pear` and `fastq-join`, but I suspect it will occur with any tool that can accepts paired end data collections as input.

My test workflow contains just one of the above tools, set to "Paired End Collection" as the input type. When I select to run this workflow and select a List of Dataset Pairs from the History, I receive the error message "cannot find 'forward'".

However, I don't think this is a problem with the tools, as I can process the List of Dataset Pairs when I execute either of the tools directly from the Tool menu.

I suspect it relates to the way that workflows processes the nested Dataset Pairs within the list (and it not going "deep enough" to find the "forward" it's looking for).

Happy to provide screenshots, share histories (or at least dump them to file somewhere) or provide whatever other information is needed

Thanks folks,

Darren

**Comment by mvdbeek** [comment]
That seems to work fine for me, here's a quick workflow that works correctly: https://gist.github.com/mvdbeek/ba867de26a3e71f9b4a2e514a463e62a
If you can share the workflow I can see if there is something odd.

Let me know if I'm missing something. Note that the original author of pear requested that we uninstall the tool from public Galaxy instances, probably a good idea to use fastq-join.

**Comment by quacksawbones** [comment]
Hi @mvdbeek,

OK, your example workflow is processing my data files fine. I suspect in this case I have missed the critical step regarding changing to the correct "Collection type" in the "Input Dataset Collection" tool in the workflow (the default is "list", and in your example workflow, it has been changed to "paired").

I will do some more testing of this in my workflows and I will either update this job with more information or let you know it's working and close it.

I don't remember seeing details on valid Collection types for the Input Dataset Collection tool in the Collections or the Galaxy 101 tutorial. Is this information documented somewhere (mainly so I can point my users to it if they run into the same issue)?

Also, thank you for the update on "Pear". I'll remove it from our Galaxy instance.

Thanks again,


DC

**Comment by quacksawbones** [comment]
Hi @mvdbeek,

I can confirm, your solution/workflow example works as expected, so I am going to close the issue. Thanks for your help.

Also, were you able to point me to any documentation for valid Collection types (specifically the behaviour of paired end data sets)? I'd like to include/refer to it in the documentation for Galaxy at my institute.

Thanks again,


DC
