### ISSUE TITLE
Workflow Editor - Connectors and/or noodle maintain incorrect state

### ISSUE THREAD

**Issue by ksuderman** [galaxyproject/galaxy#12032]
This is related to https://github.com/galaxyproject/galaxy/pull/11683 and #10788

When using the workflow editor and connecting and disconnecting tools that have restrictions on their inputs/outputs the connector and/or noodles can lose the correct state.  I have attached a screen cap that exhibits the problem, but I am not sure if it specific to these tools.

**Tools**

1. Input Dataset Collection
1. [FeatureFinderMultiplex](toolshed.g2.bx.psu.edu/repos/galaxyp/openms_featurefindermultiplex/FeatureFinderMultiplex/2.6+galaxy0)
1. [IDMapper](toolshed.g2.bx.psu.edu/repos/galaxyp/openms_featurefindermultiplex/FeatureFinderMultiplex/2.6+galaxy0)

**Steps to Reproduce**

1. Create a new workflow
1. Add the above tools
1. In the `FeatureFinderMultiplex` configuration (right panel)
   1. Under `Optional outputs` Click `Select/Unselect all`
   1. Deselect output options so `out (Output file containting the individual peptide features)` is the only selected output.
1. Connect 2 -> 3
   - Note we get a single file noodle
1. Try to connect 1 -> 2
   - Note the warning about mismatched output and input formats. (expected behavior).
1. Delete noodle between 2 -> 3
1. Connect 1 -> 2 (note batch mode connection)
1. Connect 2 -> 3 (note batch mode connection)
   - So far so good.
1. Delete noodle between 1 -> 2
1. In the `FeatureFinderMultiplex` configuration (right panel)
   - Deselect the `out` option.
      - The noodle connecting 2  -> 3 is removed (expected behavior)
   1. Under `Optional outputs` Click `Select/Unselect all`
   1. Deselect output options so `out` is the only selected output again.
1. Reconnect noodle between 2 -> 3
   - Note we get a batch mode connection (unexpected behavior)
1. Delete the noodle between 2 -> 3 and reconnect.
   - Note we now get a single file connection (unexpected behavior)
1. Connect 1 -> 2
   - We no longer get a warning about the mismatched input/output types (unexpected behavior)

![noodle-state](https://user-images.githubusercontent.com/4098072/119036862-41271e80-b97f-11eb-8edb-90be4ae9a29f.gif)

**Comment by guerler** [comment]
Thanks a lot @ksuderman for catching and describing this issue so well.
