### ISSUE TITLE
New history: mac scroll bar

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#12044]
There are two mechanisms of scroll on the new history -- fine scroll via mouse wheel/trackpad and longer-range scrolling using the scrollbar.
By default, macs hide this scrollbar unless scrolling has already been started with the trackpad/mouse, and then hides it. This makes it much more difficult to do long-range scrolling on a mac with the current version.

**Comment by martenson** [comment]
The scroll bar is visible for me on macos, maybe you have specific settings enabled or something has changed since. feel free to reopen
