### ISSUE TITLE
run_tests.sh does not install optional PostgreSQL wheel

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#1205]
If I try to run the API tests on a fresh Galaxy `dev` clone using a PostgreSQL database:

```
$ GALAXY_TEST_DBURI=postgresql://@/galaxy?host=/var/run/postgresql
$ export GALAXY_TEST_DBURI
$ ./run_tests.sh -api
```

the mandatory and test wheels are correctly installed, but not psycopg2:

```
ImportError: No module named psycopg2
```

I can pip install the wheel myself, but that seems a workaround.

Ping @natefoo @jmchilton.

**Comment by martenson** [comment]
Should probably call `get_conditional_requirements` https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/dependencies/__init__.py#L35

-dockerized does not have this problem.
