### ISSUE TITLE
New labels for release process

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#12067]
I would suggest adding these new labels `release-notes/admin`, `release-notes/user`, `QA/manual-testing`.
The first two would mean these pull-requests would be candidates for release note highlights and `QA/manual-testing` would be candidates that the release testing team should take a closer look at.

**Comment by nsoranzo** [comment]
Should we drop `major` then? I think that was supposed to be used to mark PRs to be highlighted in release notes.

Also, we could elminate the `popularity/*` labels, which have never been popular themselves :smile:

**Comment by mvdbeek** [comment]
In the end we're using the highlight label for things that should be highlighted in the release notes, and these are also getting tested.

**Comment by nsoranzo** [comment]
> In the end we're using the `highlight` label for things that should be highlighted in the release notes, and these are also getting tested.

We also have the [config/breaking](https://github.com/galaxyproject/galaxy/issues?q=is%3Aopen+label%3Aconfig%2Fbreaking+sort%3Aupdated-desc) label for things that need to be mentioned in the release notes because they potentially require a change in configuration.

> Also, we could eliminate the `popularity/*` labels, which have never been popular themselves :smile:

I've dropped them.

**Comment by mvdbeek** [comment]
Thank you!
