### ISSUE TITLE
pytest ignores tests grouped within a class

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#12071]
Currently, pytest will ignore tests grouped in classes. This was done [here](https://github.com/galaxyproject/galaxy/pull/6722/commits/721a4656d941a5462a4db046d192ef81cd1a23c1)  to get rid of pytest warnings issued when pytest attempted to collect tests from a class with a name matching the test collection pattern (`Test*`) but also with a constructor, which causes the class *not* to be collected ([see these pytest docs](https://doc.pytest.org/en/latest/explanation/goodpractices.html#conventions-for-python-test-discovery)). 

As a result, we cannot [organize tests into classes](https://docs.pytest.org/en/6.2.x/getting-started.html#group-multiple-tests-in-a-class), which can be very convenient, especially when there's a lot of tests in a module. Furthermore, if we tried to do that, the test methods inside any class would be skipped silently, which is not at all obvious and can be easily missed. 

There's a simple way to handle such classes. As per [pytest docs](https://doc.pytest.org/en/latest/example/pythoncollection.html#customizing-test-collection), "users can prevent pytest from discovering classes that start with Test by setting a boolean `__test__` attribute to `False`:"
```py
# Will not be discovered as a test
class TestClass:
    __test__ = False
```

Unless there are any objections, I'd like to use this approach and enable class-based test discovery (we don't have many classes in the code base that would need this flag). If this proves inconvenient (which I hope it won't), we can go back to function-based test only.

**Comment by ic4f** [comment]
Fixed in #12072.
