### ISSUE TITLE
Move from grunt/uglify to webpack (part 2)

### ISSUE THREAD

**Issue by carlfeberhard** [galaxyproject/galaxy#1207]
The **goal** here is to continue the process of moving from require, script tags, and mako to webpack-based script bundles.
(The original issue (part 1 of 3) is here: #1041)
(see also: https://trello.com/c/7midE7Bx)

I believe we should start this step (est. 2 of 3) by **creating entry points for some of the more app-like sections of the site** and converting them to webpack bundles:
- Pages
- workflows
- libraries
- administration

We can then begin to **move routes from the server web controllers to the client side backbone routers** in the individual apps:
1. for the root urls of each app above, convert the webcontroller to a jsAppLauncher controller class
2. Serve the root of the app as a client script/bundle (like we have root/index) by adding it to the webpack config entry points and rebuilding
3. fill in any need for mako/py based view code with js

In the **longer term**, it should be easier and less buggy to begin to fold the apps above into one single Galaxy web app launched from the root by carefully combining the client-side routes (the third and hopefully final step).

Note: again we may not want to **ever** incorporate the admin or login 'apps' with the main app for security. At the very least, switching between those two and any other app should not be determined on the client until we're **very** sure all that functionality behind those checks is secure and rock-solid. 'The client is in the hands of the enemy' and all that.
# To do:
- [ ] communicate between quotaMeter and history via Galaxy as mediator
- [ ] move over quota message to quota meter and display it when a tool is clicked
- [ ] better caching of scripts
- [ ] incorporate grunt (if needed)
- [ ] take a long look at what is **really** needed on each page load and what modules can be loaded asynchronously (tool form, upload, etc.)
- [ ] create webpack app entry points for other possible 'apps'
  - [ ] libraries
  - [ ] trackster
  - [ ] Pages
  - [ ] workflow
  - [ ] ensure proper commonChunksPlugin behavior and that it plays well with the commonLibs/vendor pattern we're using
- [ ] use style and css (and less) loaders to load base.css, etc. and move css below the fold
- [ ] remove non-webpack infrastructure
- [ ] convert all (non-async) requirejs define calls to commonJS format
- [ ] convert all pages fully and then remove the additional code (so so much additional code)

**Comment by dannon** [comment]
(this issue got left behind, but with the recent build infrastructure modernization, we're past the work described here)
