### ISSUE TITLE
optional data column is empty instead of none, when starting workflow in simplified workflow runform

### ISSUE THREAD

**Issue by foellmelanie** [galaxyproject/galaxy#12081]
Hi, 

I have a tool with an optional=TRUE data column in a workflow. When I use the full workflow form this optional parameter is set to 'None' and the tool works However, when I start the workflow in the simplified workflow runform the parameter is empty and the tool crashes because it is expecting 'None' in case the parameter is not used.

Cheers,
Melanie

**Comment by foellmelanie** [comment]
this happened with Galaxy 21.01 on EU Server

**Comment by mvdbeek** [comment]
@foellmelanie did you connect an optional data input in the workflow editor ? If not we shouldn't actually show the simplified workflow form.

**Comment by foellmelanie** [comment]
No I didn't connect an optional data input.

**Comment by bgruening** [comment]
It seems that @kxk302 actually discovered the same? or a very similar bug.

You can see this in this history: https://usegalaxy.eu/u/bgruening/h/imported-cnnnewhistory

The workflow run failed, this time even with expanded-workflow-run form according to @kxk302 ... but a simple rerun of the failed tool returns green. You can see that the `Choose a parameter name (with current value)` in both screenshots are `None` and ` ` which should not happen.

![grafik](https://user-images.githubusercontent.com/469983/120232241-6fe0a700-c253-11eb-9b03-cdb181c83466.png)

The parameter in question is defined as optional as well (that references an optional input).

https://github.com/bgruening/galaxytools/blob/e2a5eade6d0e5ddf3a47630381a0ad90d80e8a04/tools/sklearn/main_macros.xml#L1449-L1458

**Comment by mvdbeek** [comment]
@foellmelanie which tool where you using and could you provide a minimal example ?

**Comment by mvdbeek** [comment]
> You can see that the `Choose a parameter name (with current value)` in both screenshots are `None` and ` ` which should not happen.

And which one is correct here ? `""` right ?

**Comment by bgruening** [comment]
`None` I think - at least with None it turns green in both cases. I think @foellmelanie has also a str() cast https://github.com/galaxyproteomics/tools-galaxyp/blob/master/tools/cardinal/classification.xml#L118

**Comment by mvdbeek** [comment]
I think this is fixed in 21.05 / dev. https://gist.github.com/mvdbeek/a9bddc301f2cf507d5f48002754fa31b fails on usegalaxy.eu with `parameter 'sp_name': requires a value, but no legal values defined` but it works locally.

**Comment by bgruening** [comment]
We are not sure if we upgrade before GCC. Any clue what fixed that?

**Comment by mvdbeek** [comment]
You should really really update before GCC, please! This was a mess with last GCC having different version of Galaxy running. The release is stable now, no breaking bugs that we're aware of.

**Comment by mvdbeek** [comment]
> Any clue what fixed that?

I don't know for sure, but I'd assume it's this one: https://github.com/galaxyproject/galaxy/pull/11265. Please take it as a sign that you should update ASAP, I'm sure there are more things like that. I will confirm and backport.

**Comment by bgruening** [comment]
I will talk to Gianmauro and see what he thinks.

**Comment by nsoranzo** [comment]
Any chance this can be fixed in the workflow editor instead?

**Comment by mvdbeek** [comment]
Yeah, that's my suggestion. You can add a Boolean `Set Value?` that captures the difference between unset and set to `""`

**Comment by kxk302** [comment]
@mvdbeek I am still seeing the issue Bjorn reported. The first time I run this workflow, it fails. If I re-run it from the failed step onwards, it passes. 

Here is the history: https://usegalaxy.eu/u/kaivan/h/gcc2021cnn

I get this message: Tool Error An error occurred with this dataset: parameter 'sp_name': requires a value, but no legal values defined

I reported the issue. Will paste the stack trace when I receive the email.

Can we meet briefly on Monday to discuss this? Thx.

**Comment by kxk302** [comment]
Here is the stack trace:

```
Traceback (most recent call last):
  File "/opt/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 237, in prepare_job
    job_wrapper.prepare()
  File "/opt/galaxy/server/lib/galaxy/jobs/__init__.py", line 1126, in prepare
    tool_evaluator.set_compute_environment(compute_environment, get_special=get_special)
  File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 81, in set_compute_environment
    visit_input_values(self.tool.inputs, incoming, validate_inputs)
  File "/opt/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 170, in visit_input_values
    visit_input_values(input.cases[values['__current_case__']].inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload)
  File "/opt/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 174, in visit_input_values
    visit_input_values(input.inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload)
  File "/opt/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 162, in visit_input_values
    visit_input_values(input.inputs, d, callback, new_name_prefix, new_label_prefix, parent_prefix=new_name_prefix, **payload)
  File "/opt/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 176, in visit_input_values
    callback_helper(input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context)
  File "/opt/galaxy/server/lib/galaxy/tools/parameters/__init__.py", line 137, in callback_helper
    new_value = callback(**args)
  File "/opt/galaxy/server/lib/galaxy/tools/evaluation.py", line 79, in validate_inputs
    value = input.from_json(value, request_context, context)
  File "/opt/galaxy/server/lib/galaxy/tools/parameters/basic.py", line 934, in from_json
    raise ParameterValueError("requires a value, but no legal values defined", self.name, is_dynamic=self.is_dynamic)
galaxy.tools.parameters.basic.ParameterValueError: parameter 'sp_name': requires a value, but no legal values defined

```

**Comment by kxk302** [comment]
Job Information: parameter 'sp_name': requires a value, but no legal values defined

**Comment by bgruening** [comment]
And this was now with 21.05.

**Comment by mvdbeek** [comment]
It's what I've explained in https://github.com/galaxyproject/galaxy/issues/12081#issuecomment-854008356. You can download the workflow and set the `sp_name` field to null instead of `\"\"`, but that's all I can offer for now.

**Comment by kxk302** [comment]
FYI, I re-ran the training job and it succeeds. So, the problem now is in the workflow created prior to the fix. I searched the workflow file for 'sp_name' and here is what I found:

\"sp_name\": null, \"sp_value\": \"\"

So, sp_name is already null.

I could re-create the workflow and see if the saved file has anything different.

**Comment by kxk302** [comment]
So, I re-created the workflow and the job completed successfully, and re-ran it in a new history and got the same error. Marius, I'll ping you on Monday if you have a few mins to discuss.

**Comment by mvdbeek** [comment]
That's a second bug we've been chasing for a while, good to know how to reproduce it.

**Comment by kxk302** [comment]
So, I made the following change to the workflow file:

Before: 
\"hyperparams_swapping\": {\"infile_params\": null, \"param_set\": [{\"__index__\": 0, \"sp_name\": null, \"sp_value\": \"\"}]}

After:
\"hyperparams_swapping\": {\"infile_params\": null, \"param_set\": []}

And workflow now run to completion successfully (Before this change, tried setting the sp_value to null, but it still failed).

**Comment by mvdbeek** [comment]
> and re-ran it in a new history and got the same error.

That's https://github.com/galaxyproject/galaxy/issues/9886
