### ISSUE TITLE
fastq.gz file not decompressed automatically.

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/galaxy#12091]
A user on our internal galaxy reported that the JE Demultiplex tool was failing. I checked and found the following error:

```

Picked up _JAVA_OPTIONS: -Xmx4G -Xms256m [Thu Jun 03 12:30:45 GMT 2021] org.embl.gbcs.je.jemultiplexer.Jemultiplexer FASTQ_FILE1=/REDACTED/data/datasets/000/dataset_141.dat FASTQ_FILE2=/REDACTED/data/datasets/000/dataset_140.dat BARCODE_FILE=/REDACTED/data/datasets/000/dataset_155.dat BARCODE_READ_POS=BOTH BARCODE_FOR_SAMPLE_MATCHING=BOTH REDUNDANT_BARCODES=false MAX_MISMATCHES=1 MIN_MISMATCH_DELTA=1 MIN_BASE_QUALITY=10 XTRIMLEN=0 ZTRIMLEN=0 CLIP_BARCODE=true ADD_BARCODE_TO_HEADER=true ENSURE_IDENTICAL_HEADER_NAMES=false READ_NAME_REPLACE_CHAR=: QUALITY_FORMAT=Standard OUTPUT_DIR=results KEEP_UNASSIGNED_READ=true METRICS_FILE_NAME=/REDACTED/data/jobs/000/143/outputs/galaxy_dataset_4c2e35a6-eeff-4847-883f-74e3186a0f2b.dat GZIP_OUTPUTS=false STATS_ONLY=false    STRICT=false UNASSIGNED_FILE_NAME_1=unassigned_1.txt UNASSIGNED_FILE_NAME_2=unassigned_2.txt FORCE=false WRITER_FACTORY_USE_ASYNC_IO=true USE_EMBASE=false VERBOSITY=INFO QUIET=false VALIDATION_STRINGENCY=STRICT COMPRESSION_LEVEL=5 MAX_RECORDS_IN_RAM=500000 CREATE_INDEX=false CREATE_MD5_FILE=false GA4GH_CLIENT_SECRETS=client_secrets.json [Thu Jun 03 12:30:45 GMT 2021] Executing as REDACTED@REDACTED on Linux 4.18.0-301.1.el8.x86_64 amd64; OpenJDK 64-Bit Server VM 11.0.9.1-internal+0-adhoc..src; Picard version: 1.2 JdkDeflater [Thu Jun 03 12:30:46 GMT 2021] org.embl.gbcs.je.jemultiplexer.Jemultiplexer done. Elapsed time: 0.01 minutes. Runtime.totalMemory()=259522560
Exception in thread "main" htsjdk.samtools.SAMException: Sequence header must start with @: 
????n???n????nV#uI?6`?$?,???2????3x???????b)?`?????I?%??????????????????????????_????????????????^????????????????_?~?????~????????????????????????"???I?O???'?????^?M??/c?"????????yV1?????????V~?q????[Gn???a???I8????~=?j????o???]g????{???????x??^@}????????~??~??4???%'mXD?N??????Z=??????????A?????8&amp;??z@??????`????~?a??`?{??????pk??l???qP?fc??????{?=??'??????\|?????l??V?K?J?????Pt???b2&lt;Q??8?N^T?8D??Pe?b?`??2I{&lt;??wg??	???_b?????D?T?o??s?3?7&amp;?}g?f??Qg?????????{?h?b	????KU???g? 
at line 1 in fastq /REDACTED/data/datasets/000/dataset_141.dat 	at htsjdk.samtools.fastq.FastqReader.readNextRecord(FastqReader.java:98) 	at htsjdk.samtools.fastq.FastqReader.&lt;init&gt;(FastqReader.java:64) 	at htsjdk.samtools.fastq.FastqReader.&lt;init&gt;(FastqReader.java:52) 	at org.embl.gbcs.je.jemultiplexer.Jemultiplexer.doDemultiplexingWork(Jemultiplexer.java:236) 	at org.embl.gbcs.je.jemultiplexer.AbstractJemultiplexer.doWork(AbstractJemultiplexer.java:1036) 	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:209) 	at picard.cmdline.CommandLineProgram.instanceMainWithExit(CommandLineProgram.java:147) 	at org.embl.gbcs.je.Je.main(Je.java:109)
--
Tool Exit Code: | 1
```

Galaxy reported the dataset to have proper fastq reads however. The data was of the fastqsanger.gz type. 

Isn't galaxy supposed to present a converted dataset to tools that do not support gzip? Is there some further troubleshooting I can do?

**Comment by bgruening** [comment]
I assume your user specified the wrong datatype during upload. If the annotation of a dataset is "fastq" instead "fastqsanger.gz" then those things can happen.

**Comment by rhpvorderman** [comment]
Nope. Both datasets are fastqsanger.gz.

**Comment by bgruening** [comment]
Then it's a tool problem I guess. I looked at JE and it does not seem to distinguish between gz and not. 

ping @scholtalbers for an expert on this tool :)

**Comment by rhpvorderman** [comment]
Thanks!  Well, how can it know, given that the extensions is .dat?

**Comment by rhpvorderman** [comment]
BTW @bgruening , to make it more confusing: The user reported that the same data worked on EU galaxy.

**Comment by scholtalbers** [comment]
The tool indeed only handles uncompressed fastq, unless the dataset was linked from disk and therefor still has the right extension (something we locally use a lot through shared libraries). Possibly the wrapper on usegalaxy.eu is modified to only accept the datatypes `fastq,fastqsanger` and so galaxy will uncompress the data before sending it to the tool?

Local:

<img width="628" alt="Screenshot 2021-06-07 at 10 12 13" src="https://user-images.githubusercontent.com/102411/120982439-0132aa80-c779-11eb-88d5-21ac95fd70f4.png">

Usegalaxy.eu:
<img width="513" alt="Screenshot 2021-06-07 at 10 10 12" src="https://user-images.githubusercontent.com/102411/120982444-02fc6e00-c779-11eb-82f1-37310e4d2b22.png">

**Comment by bernt-matthias** [comment]
Seems to be a "super old" galaxy tool. One problem might be that it specifies `format="gz,fastq" ` which should probably be `format="fastq.gz,fastq" `.

If the tool is still used and there are no alternatives (cutadapt?) it might be worthwhile to port it to IUC.

The different behavior on the usegalaxies might be due to different Galaxy version or differences in the datatypes config?

**Comment by mvdbeek** [comment]
I don't think this is a Galaxy issue / one we can fix.
