### ISSUE TITLE
Need more descriptive message when saving a workflow and it fails

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#12109]
Originating in https://github.com/galaxyproject/galaxy/issues/6976#issuecomment-856193384, a user would benefit from having more insight into why a workflow failed to save when 'exception in unexposed API method occurs'.

The specific commit of Galaxy where this can be reproduced is at least #11314.

I've pulled this version locally and can reproduce the issue by just starting Galaxy with sh run.sh, then creating a workflow A, and then creating another workflow where I add workflow A and clicking Save.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/11517
