### ISSUE TITLE
sh run.sh fails at second execution

### ISSUE THREAD

**Issue by takawitter** [galaxyproject/galaxy#1210]
Because of the line 66 of lib/tool_shed/galaxy_install/migrate/check.py the config_arg becomes "./config..ini.sample" and boot process fails.
This occurs because build process of config_arg tries to change the path /galaxy/config/galaxy.ini.sample to ./config/galaxy.ini.sample, but actually it changes to ./config..ini.sample because of lack of 3rd argument of replace function.
The patch to fix it is:

```
root@2737bb02f41a:/galaxy# git diff lib/tool_shed/galaxy_install/migrate/check.py
diff --git a/lib/tool_shed/galaxy_install/migrate/check.py b/lib/tool_shed/galaxy_install/migrate/check.py
index 2545bb6..3fe7e9e 100644
--- a/lib/tool_shed/galaxy_install/migrate/check.py
+++ b/lib/tool_shed/galaxy_install/migrate/check.py
@@ -54,7 +54,7 @@ def verify_tools( app, url, galaxy_config_file, engine_options={} ):
                 break
         config_arg = ''
         if os.path.abspath( os.path.join( os.getcwd(), 'galaxy.ini' ) ) != galaxy_config_file:
-            config_arg = ' -c %s' % galaxy_config_file.replace( os.path.abspath( os.getcwd() ), '.' )
+            config_arg = ' -c %s' % galaxy_config_file.replace( os.path.abspath( os.getcwd() ), '.', 1)
         if not app.config.running_functional_tests:
             if tool_shed_accessible:
                 # Automatically update the value of the migrate_tools.version database table column.
```

I succeeded to boot galaxy in second execution using this modification.

regards.

**Comment by hexylena** [comment]
@takawitter if you have a working patch, would you mind opening a [pull request](https://help.github.com/articles/using-pull-requests/) so we can easily attribute this fix to you?

**Comment by takawitter** [comment]
Thanx. I will send a pull request.

**Comment by takawitter** [comment]
I sent that :)
https://github.com/galaxyproject/galaxy/pull/1230
