### ISSUE TITLE
New History Panel Doesn't Preserve Expanded State

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#12119]
The old history panel would preserve state around which datasets were expanded (had details shown) and which weren't and would restore the state on browser refreshes and such. There is a functional test for this ``test_refresh_preserves_state`` that I now just skip for the new history panel.

I'm fine with dropping this behavior but I did want to make sure there was a conversation around it first.

**Comment by Nerdinacan** [comment]
@jmchilton 

I'm good either way. I'll look at simply caching the "expanded items list" in the browser-side cache. Should be pretty easy to add to the provider that's in charge of figuring out what's open/closed.

**Comment by dannon** [comment]
Fixed in #12352
