### ISSUE TITLE
Sharing a WF report in a page does not share underlying datasets leading to blank spaces

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#12116]
The history was not made public, just the WF report in a galaxy page. @shiltemann tried sharing the "Public URL" (it was not actually public, we should change that column title)

![image](https://user-images.githubusercontent.com/458683/121376314-b4e69680-c941-11eb-844f-36fc54d22208.png)

After getting a report from the consumer, and going back to publish the page she double checked in a private browsing session and noticed her datasets were missing:

![image](https://user-images.githubusercontent.com/458683/121376157-92ed1400-c941-11eb-8933-cfdcba0ff49b.png)

It seems the history datasets that are referenced by the report are still private to her account and not made public.

This is on EU with default dataset privacy=true, I'm guessing that's why this wasn't caught?

I guess publishing a report should say "make report (and also all referenced datasets) public?" and then do that

**Comment by mvdbeek** [comment]
or the other way around, but one of them should be enough :)
