### ISSUE TITLE
error Couldn't find match for "65a49742e131d19f41e3f5bf63588995f7b8a9e0"

### ISSUE THREAD

**Issue by ZeroDesigner** [galaxyproject/galaxy#12125]
Hi,I am trying to install galaxy ,and this happened,what should I do to fix it?
```
yarn install v1.22.10
[1/4] Resolving packages...
warning Resolution field "chokidar@3.4.0" is incompatible with requested version "chokidar@^2.0.0"
warning Resolution field "chokidar@3.4.0" is incompatible with requested version "chokidar@^3.4.2"
warning Resolution field "chokidar@3.4.0" is incompatible with requested version "chokidar@^2.1.8"
warning Resolution field "chokidar@3.4.0" is incompatible with requested version "chokidar@^2.0.4"
warning Resolution field "chokidar@3.4.0" is incompatible with requested version "chokidar@^2.1.8"
[2/4] Fetching packages...
error Couldn't find match for "65a49742e131d19f41e3f5bf63588995f7b8a9e0" in "refs/heads/dependabot/npm_and_yarn/hosted-git-info-2.8.9,refs/heads/dependabot/npm_and_yarn/merge-1.2.1,refs/heads/develop,refs/heads/gh-pages,refs/heads/master,refs/heads/namespaced-events,refs/heads/no-deps,refs/heads/refactor,refs/heads/separate-orphan-step-template,refs/tags/0.10.3,refs/tags/0.2.0,refs/tags/v0.10.0,refs/tags/v0.10.1,refs/tags/v0.10.2,refs/tags/v0.10.3,refs/tags/v0.11.0,refs/tags/v0.12.0,refs/tags/v0.2.0,refs/tags/v0.3.0,refs/tags/v0.4.0,refs/tags/v0.5.0,refs/tags/v0.5.1,refs/tags/v0.6.0,refs/tags/v0.6.1,refs/tags/v0.6.2,refs/tags/v0.7.0,refs/tags/v0.7.1,refs/tags/v0.7.2,refs/tags/v0.7.3,refs/tags/v0.8.0,refs/tags/v0.8.1,refs/tags/v0.9.0,refs/tags/v0.9.1,refs/tags/v0.9.2,refs/tags/v0.9.3" for "https://github.com/sorich87/bootstrap-tour.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Galaxy client dependency installation failed. See ./client/README.md for more information, including how to get help.
```

**Comment by mvdbeek** [comment]
Can you try again ? that is a valid commit for boostrap-tour and works in our testing environments.

**Comment by ZeroDesigner** [comment]
> Can you try again ? that is a valid commit for boostrap-tour and works in our testing environments.

Actually, I have tried several times in the past.  But it stiil doesn't work.

**Comment by mvdbeek** [comment]
How exactly are you building the client ? Just running `run.sh`, `make client`, or something else ?

**Comment by ZeroDesigner** [comment]
> How exactly are you building the client ? Just running `run.sh`, `make client`, or something else ?

`run.sh`

**Comment by mvdbeek** [comment]
Can you try removing `.venv/lib/node_modules` and trying again ? It looks a bit like a network issue, but that might be worth a try.

**Comment by ZeroDesigner** [comment]
> Can you try removing `.venv/lib/node_modules` and trying again ? It looks a bit like a network issue, but that might be worth a try.
I remove `.venv/lib/node_modules` and try again. And it just shows this.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32703906/121541931-46d1ca80-ca3a-11eb-8256-eed876d07459.png">

**Comment by Catvick26** [comment]
i have the exact same issue

**Comment by dannon** [comment]
Sorry I'm just now seeing this issue, I'll take a look here.  There's been some work done swapping away from this library to its successor, but I can also probably just publish a clone to our npm namespace for us to use as a quick(er) fix.

**Comment by mvdbeek** [comment]
If you pull the latest commit (`git pull`) on the release_21.05, master or dev branch this should work now. Thanks for the report @ZeroDesigner!

**Comment by Catvick26** [comment]
Hi @mvdbeek, after git pull, I am seeing another error saying 'unable to access 'https://github.com/sorich87/bootstrap-tour.git/'', but I am actually able to git clone this repo. Can I download and put it into some folder to make it work? Thank you.

yarn install v1.22.10
[1/4] Resolving packages...
warning Resolution field "chokidar@3.4.0" is incompatible with requested version "chokidar@^2.0.0"
warning Resolution field "chokidar@3.4.0" is incompatible with requested version "chokidar@^2.1.8"
warning Resolution field "chokidar@3.4.0" is incompatible with requested version "chokidar@^2.0.4"
warning Resolution field "chokidar@3.4.0" is incompatible with requested version "chokidar@^2.1.8"
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads https://github.com/sorich87/bootstrap-tour.git
Directory: /mnt/software-install/galaxy/galaxy/client
Output:
fatal: unable to access 'https://github.com/sorich87/bootstrap-tour.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Galaxy client dependency installation failed. See ./client/README.md for more information, including how to get help.

**Comment by Catvick26** [comment]
sorry, pls ignore my comment above. It is working now. I think just temporarily network problem.
