### ISSUE TITLE
regex truncates sample names too much during paired list creation

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/galaxy#12135]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/61636/121832997-64509f80-cc99-11eb-9d7f-8597f3962e3f.png">

it should be converting 
DP134_1_FS_PSII_FSB_42C_A10.1.fastq -> DP134_1_FS_PSII_FSB_42C_A10
not
DP134_1_FS_PSII_FSB_42C_A10.1.fastq -> DP134_

**Comment by bwlang** [comment]
Hi @assuntad23...  we are running release_21.01
i'll have a look to see if that issue was fixed between these versions.
thanks for checking!

**Comment by bwlang** [comment]
looks like the problem was in the function
galaxy/server/client/src/components/Collections/PairedListCollectionCreator.vue
           var lcs = this._naiveStartingAndEndingLCS(
               fwdName.replace(new RegExp(this.filters[0]), ""),
               revName.replace(new RegExp(this.filters[1]), "")
           );

this.filteres[0] was alwasys _1 even if someone changed the regex

This has since been refactored

**Comment by jmchilton** [comment]
@bwlang I'm really sorry about this https://github.com/galaxyproject/galaxy/pull/11773#issuecomment-863341235. I mistargeted the previous fix to dev instead of 21.01. I'll get this backported.

**Comment by bwlang** [comment]
@jmchilton : no biggie - for me  it's not worth the effort unless you think others are stuck on 21.01 and use this feature.  I hope we'll be moving to 21.05 very soon anyway...
