### ISSUE TITLE
21.05 Running and editing workflows fails if tool versions not installed

### ISSUE THREAD

**Issue by jancrichter** [galaxyproject/galaxy#12137]
Currently, on 21.05 if I try to load an imported workflow I get an error "500 Request failed" if the workflow contains versions of tools that are not currently installed.

The log shows the usual messages about "using version x.x.x because x.x.x is not available" and the following traceback:

![Screenshot from 2021-06-14 12-19-52](https://user-images.githubusercontent.com/40425803/121877453-e4fbb400-cd0a-11eb-929b-23f01883c016.png)

**Comment by mvdbeek** [comment]
Thanks for the report, https://github.com/galaxyproject/galaxy/pull/12139 should fix it.
