### ISSUE TITLE
Hide (or remove ?) interactive environment (if no interactive environments enabled)

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#12153]
Interactive tools are the way to go, so we should either disable all of the GIE UI if no GIE as enabled or remove the UI completely, assuming there's no use for the old GIEs

**Comment by hexylena** [comment]
Remove.

**Comment by mvdbeek** [comment]
Done in https://github.com/galaxyproject/galaxy/pull/13601
