### ISSUE TITLE
Downloading collection dataset - format other than tgz

### ISSUE THREAD

**Issue by ManonD18** [galaxyproject/galaxy#12178]
Hi,
Is it possible to configure galaxy, or at least the tool in a workflow, to change the format of the archive that is downloaded when you select the entire collection ?

For the moment we can only download a .tgz which is a bit tedious to unzip in Windows (needs to be unzipped twice).

Thank you.

**Comment by mvdbeek** [comment]
Hi @ManonD18, which server are you using ? Collections are created as zip files for since the 21.01 Galaxy release.

**Comment by ManonD18** [comment]
Ohhhh this is why !
We are at 20_05 but we should be updating soon.

Thanks a lot for the answer !
