### ISSUE TITLE
Building job script when reducing large collection takes too long

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#12179]
Executing https://github.com/bgruening/galaxytools/blob/master/tools/text_processing/text_processing/cat.xml tool (via a workflow, see https://github.com/galaxyproject/galaxy/issues/12177#issuecomment-865154263 ) on a 190K element collection to reduce it to a single file is taking more than 3 hours to generate the job script (and using 4 GB of memory).

Relevant job handler log messages:
```
galaxy.jobs.mapper DEBUG 2021-06-21 13:48:03,403 [pN:handler2,p:10809,tN:JobHandlerQueue.monitor_thread] (3781025) Mapped job to destination id: hpc_webservices
galaxy.jobs.handler DEBUG 2021-06-21 13:48:26,507 [pN:handler2,p:10809,tN:JobHandlerQueue.monitor_thread] (3781025) Dispatching to slurm runner
galaxy.jobs DEBUG 2021-06-21 13:48:26,975 [pN:handler2,p:10809,tN:JobHandlerQueue.monitor_thread] (3781025) Persisting job destination (destination id: hpc_webservices)
galaxy.jobs DEBUG 2021-06-21 13:48:27,494 [pN:handler2,p:10809,tN:JobHandlerQueue.monitor_thread] (3781025) Working directory for job is: /tgac/services/galaxy/prod/galaxy/database/jobs_directory/003/781/3781025
galaxy.jobs.runners DEBUG 2021-06-21 13:49:20,193 [pN:handler2,p:10809,tN:JobHandlerQueue.monitor_thread] Job [3781025] queued (53685.233 ms)
galaxy.jobs.handler INFO 2021-06-21 13:49:20,203 [pN:handler2,p:10809,tN:JobHandlerQueue.monitor_thread] (3781025) Job dispatched
```

I'm collecting every 10' py-spi output on the job handler process.

**Comment by nsoranzo** [comment]
One py-spi output of the process, if that helps: https://gist.github.com/nsoranzo/7549cc1261a69201e1ed079099ea1419

**Comment by mvdbeek** [comment]
Hmm, that particular code path was introduced in https://github.com/galaxyproject/galaxy/pull/6798/.

**Comment by nsoranzo** [comment]
Thanks for looking at this! Let me know if you want more py-spi outputs.

**Comment by mvdbeek** [comment]
If they're different from the first one that might be interesting, yeah.

**Comment by nsoranzo** [comment]
That's slightly different: https://gist.github.com/nsoranzo/e04654a4df0e465d6e91b23c17130d40

The other 3 produced till now are basically identical.

**Comment by mvdbeek** [comment]
Those are pretty good hints. can you also run one py-spy dump command with `-l` for locals ? `remap` is supposed to stop when finding `DatasetFilenameWrapper` or `DatasetListWrapper` instances, but maybe we're entering the collection somehow ...

**Comment by nsoranzo** [comment]
Sure: https://gist.github.com/nsoranzo/c095a6dbaf2dc75ac1fe45b7086c6103

**Comment by nsoranzo** [comment]
> The other 3 produced till now are basically identical.

Given your comment about `remap`, I guess I should mention that the other 3 actually had this diff w.r.t. to the first py-spi:

```
--- py-spi_2021-06-21T17:14:22,443138790+0100.txt	2021-06-21 17:14:22.536232445 +0100
+++ py-spi_2021-06-21T17:24:22,545404978+0100.txt	2021-06-21 17:24:22.686426955 +0100
@@ -34,7 +34,8 @@
     _bootstrap_inner (threading.py:916)
     _bootstrap (threading.py:884)
 Thread 10832 (active+gil): "SlurmRunner.work_thread-1"
-    remap (boltons/iterutils.py:1082)
+    __iter__ (_collections_abc.py:744)
+    remap (boltons/iterutils.py:1075)
     find_instance_nested (galaxy/util/__init__.py:645)
     __populate_input_dataset_wrappers (galaxy/tools/evaluation.py:283)
     build_param_dict (galaxy/tools/evaluation.py:137)
```

**Comment by nsoranzo** [comment]
Building the job script finished after almost 19 hours :astonished:
All the following job handling was reasonably quick though.
In the end the job failed with "argument too long", but that should be easily fixed by https://github.com/bgruening/galaxytools/pull/1135
