### ISSUE TITLE
Singularity container resolver not working well with fetch data managers.

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/galaxy#12184]
For our institute galaxy I am using singularity as a dependency resolver. This is my container resolver configuration:
```xml
<containers_resolvers>
  <explicit_singularity />
  <cached_mulled_singularity cache_directory="{{ galaxy_mutable_data_dir }}/cache/singularity" />
  <mulled_singularity auto_install="False" cache_directory="{{ galaxy_mutable_data_dir }}/cache/singularity" />
  <build_mulled_singularity auto_install="False" cache_directory="{{ galaxy_mutable_data_dir }}/cache/singularity" />
</containers_resolvers>
```

I am trying to download reference datasets using the mothur data manager:

    toolshed.g2.bx.psu.edu/repos/iuc/data_manager_mothur_toolsuite/data_manager_fetch_mothur_reference_data/0.1.5

This uses python 2.7. Unfortunately this leads to a `name or service not known` error from urllib2. When I start the `python:2.7` container directly from the singularity cache I get: 
`│WARNING: Skipping mount /usr/local/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container`

So that is the root cause of the issue. 

I suspect that when building new images this should not occur anymore thanks to: https://github.com/galaxyproject/galaxy/pull/11966 . But if I change my resolver configuration to:

```
<containers_resolvers>
  <build_mulled_singularity auto_install="True" cache_directory="{{ galaxy_mutable_data_dir }}/cache/singularity" />
</containers_resolvers>
```
No containers are build and the jobs are run directly on the execution node.

Is there a way to influence/debug how galaxy selects the image? This is probably a problem for more data managers that fetch data from the internet.

**Comment by mvdbeek** [comment]
That is a problem with the base image that was used for that data manager and singularity itself. The easiest fix is to rebuild the image, that's in https://github.com/BioContainers/multi-package-containers/pull/1770.

```
<containers_resolvers>
  <build_mulled_singularity auto_install="True" cache_directory="{{ galaxy_mutable_data_dir }}/cache/singularity" />
</containers_resolvers>
```
that should also work. Did you remove the downloaded image from the cache directory ?

**Comment by rhpvorderman** [comment]
Thank you for your quick answer!

> that should also work. Did you remove the downloaded image from the cache directory ?

I did. It didn't build the image somehow. I am a bit confused by this.

**Comment by rhpvorderman** [comment]
Thanks @mvdbeek, the PR for the Python:2.7 rebuild fixed  the issue.
