### ISSUE TITLE
Heading and tailing space existed in email string

### ISSUE THREAD

**Issue by linnil1** [galaxyproject/galaxy#12194]
I run galaxy(21.01) in our own server and I create a new user. 
I found ` linnil1@test.com`(heading space), `linnil1@test.com `(tailing space) are treated as different user from `linnil1@test.com`(no space).

After review some code, the email string do not trim before validation or writting into database.
* https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/managers/users.py#L81
* https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/webapp/controllers/user.py#L112

I'm not sure if it's a feature or not, since I think space is not always valid in email string.

**Comment by ic4f** [comment]
It's definitely not a "feature" - we don't need leading/trailing spaces. Thank you for reporting this!

**Comment by ic4f** [comment]
Leaving this unassigned for now, as a paper-cut. I'll check back after next paper cuts day.
