### ISSUE TITLE
Some UX issues on Data Libraries

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy#12208]
Hi,

I was interacting with Data libraries yesterday and I had some issues:

- It would be nice if we could open the **Manage** for files in a new tab
- The back button from the Manage page to the folder page is always bringing back 
  - to the first page of the folder (even if we were on the 10th page)
  - with only 10 items displayed (even if we selected 60 items before)

I already mentioned that to @OlegZharkov

**Comment by OlegZharkov** [comment]
thanks @bebatut, I will look at it during the next paper cut event
