### ISSUE TITLE
Tool input <conditional/> selector param can't be added to module 

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#12239]
![image](https://user-images.githubusercontent.com/1768820/124989155-ae584700-dff3-11eb-8d56-4af3e14f8204.png)

I am unable to forward a conditional input group selector as a tool input (click a "<->" icon).
Given that the config for sub inputs is retained regardless of the selector value, I don't see why these inputs can be added to the tool module inputs.

**Comment by mvdbeek** [comment]
It's a bug that you see the `<->` icon there. For why we can't do this check out https://github.com/galaxyproject/galaxy/issues/4528. https://github.com/galaxyproject/galaxy/issues/4528#issuecomment-326643822 is something we could do though.
