### ISSUE TITLE
Advanced Workflow Input Constraints

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#12233]
Requested during the GCC 2021 by @selten.

"Are there plans for more parameter types to attempt to limit the inputs? I could see integer having some similar options as text."

All the constraints available for tools are already implemented in the client form so it should be as easy as exposing setting those up in the workflow editor and tracking them in backend modules.

**Comment by Delphine-L** [comment]
Requested by VGP people as well: Constraints on text inputs (No blank space or special characters)
