### ISSUE TITLE
Workflow best practices menu papercuts

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#12240]
## Save Button

![image](https://user-images.githubusercontent.com/458683/125075005-59cdce00-e0be-11eb-97ee-4973c58c4d55.png)

Trying out the new WF best practices (LOVE IT) but unclear that the tiny save button needs to be clicked. Could this be auto-saved?

## Format dropdown

It's out of order and not search to type, could this be a select2?

![image](https://user-images.githubusercontent.com/458683/125075205-98638880-e0be-11eb-8f11-05ef6e88730f.png)

## Fixing unlabelled inputs

I'm not sure "uncheck every output" is the right auto-fix? What about just generating a label for them like "Quast HTML Report" → "quast_html_report"?

![image](https://user-images.githubusercontent.com/458683/125075641-2dff1800-e0bf-11eb-86e7-ff97389b76f9.png)

**Comment by hexylena** [comment]
I labelled every step since I was told that was best practice, I found it very tedious, I was mostly naming the outputs the same thing as the tools.

If that's best practice, could we have an automatic fixer that automatically labels every dataset with just the name of the tool? If there's duplicates just append a 1 to it and let the user fix those as needed? (Or just generate the duplicates and force the user to fix those)

**Comment by mvdbeek** [comment]
Ah, sorry, I meant you only need to label the steps. You don't need or should label every output.

**Comment by hexylena** [comment]
Oh, yeah, I just labelled the steps, not all the outputs. But it still consisted of mostly just retyping the tool name myself which felt like something that could be automated and be a bit nicer? (And would make a nice papercut for someone.) Either that or I completely missed the point of labeling things (which I'm really only doing to make it more diffable) I really don't want to forget which tools I'm using in each step.

**Comment by mvdbeek** [comment]
> Either that or I completely missed the point of labeling things (which I'm really only doing to make it more diffable) I really don't want to forget which tools I'm using in each step.

Yeah, we might want to suggest that as the default when adding a step ? Just labelling everything using the tool id doesn't work if you use the same tool in two steps, but the best practice panel could catch this.

And yeah, the tool name should still stand out, even if we have a label, that came up in the iwc as well

**Comment by hexylena** [comment]
Yeah only time I had to do anything useful with names were 4 fastqc steps which I just appended r1/r2/trim-r1/trim-r2.

> And yeah, the tool name should still stand out, even if we have a label, that came up in the iwc as well

ah perf!

**Comment by jmchilton** [comment]
I think we've revisited these points - I'm going to close this out but feel free to reopen if the points are not met.

**Comment by hexylena** [comment]
yep, these are all fixed sufficiently. Thanks y'all.
