### ISSUE TITLE
Optional=false not working on text param

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#12281]
Working on a new wrapper with planemo, it looks like with 21.05 if I define a required text param like this:

```
<param argument="--species" type="text" optional="false" value="" label="Name of the species" />
```
I can execute the tool without entering any value in this field. That's quite unexpected, I wonder if it's always been like this or if it's a regression in recent versions (or maybe it's intended and I missed something). Any clue?

Maybe related to #11291?

**Comment by mvdbeek** [comment]
An empty string is a valid text value, right ? We are tracking this for the specialised in the workflow editor now, so we can discriminate empty string from no value. You can add a validator to prevent this.

**Comment by nsoranzo** [comment]
Yep, `<validator type="empty_field" />` should do it.

**Comment by abretaud** [comment]
Ok, yep you're right, the validator is the solution, I had just not seen it while doing some grep on iuc tools
Thanks for the help, sorry for the noise :)
