### ISSUE TITLE
Clicking "Manage Information" on the popup for a user on the User Admin page loads the manage information page for the current user

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#12294]
**Describe the bug**
When logged in as an admin user, clicking "Manage Information" on the popup for a user on the User Admin page loads the manage information page for the current user instead of the selected user.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.05.1.dev0
Commit: 55a261f0dfa2fdac4e78959f70bdbbca471ac679

**To Reproduce**
1. Go to Admin -> Users
2. Click on the popup menu button a user other than yourself
3. Click "Manage Information"
4. Manage Information page loads with your address/username instead of the user you clicked on.

**Expected behavior**
Manage Information page loads with the address/username of the user you clicked on.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by dannon** [comment]
Fixed in #12295 (I think)
