### ISSUE TITLE
Hide Tools in tool list

### ISSUE THREAD

**Issue by BigOldWei** [galaxyproject/galaxy#12325]
I tried to modify tool_ conf.xml file to hide useless tools on the left side of the page, but it's useless.

 Why? What should I do if I want to delete some tools? thank you

**Comment by dannon** [comment]
Did you restart your galaxy instance after removing the references to tools you are not interested in?

**Comment by suang207** [comment]
Thanks for your reply, I have found the reason, I should uncomment "tool_conf" in galaxy.yml
