### ISSUE TITLE
Data libraries beta: more prominent place for 'showing 15 of X items'

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#1232]
On a big screen the current default 15 item limit is too low, causing a big white space below the list of items. As nothing is displaying after the 15 items one thinks there are no more items to show. Only after carefully looking one finds the 'showing 15 of X items' at the top of the page. I believe moving this to the bottom of the list, would be more natural for pagination.

**Comment by martenson** [comment]
nice insight, I will look into it,  thank you
