### ISSUE TITLE
Enhance select export widget to support folders that do not exist yet

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#12346]
Currently, it is not¹ possible to export files to a directory that does not exist.

1) I think we should make this widget editable:
 ![grafik](https://user-images.githubusercontent.com/469983/129442386-d16c983b-b6a1-40de-8230-727fed584fb5.png) 
so that you can select an export location, but sill can add folders and names as you like.

2) folders that do not exist should be created by the backend plugins.

This is important for the VGP project.

¹ we made it work by renaming files like "/foo/bar/file.bed" in the history, but I consider this a grosk hack

**Comment by mvdbeek** [comment]
> Currently, it is not¹ possible to export files to a directory that does not exist.

That works with the tool shipped in Galaxy that will be part of 21.09

**Comment by bgruening** [comment]
xref: https://github.com/galaxyproject/galaxy/issues/12362

I think we can fix this problem very elegantly and in a general way with 2 enhancements.

1) Make the "select directory URI" editable, maybe with a [breadcrumb](https://getbootstrap.com/docs/4.0/components/breadcrumb/) widget. It needs to support writing a new non-existing path.

2) The file-input in a workflow can already filter by file-type at the moment. If we include an additional filter `by-tag` and we could specify a tag as part of the workflow and when a user-runs the workflow Galaxy will make it already easier to select the important files to export. Imaging 200 files but only 20 files to export. This would make it easy to have a workflow that assemblies the genome and tags the good result files and a second workflow that exports those 20 files into folder A and other files into folder B etc ...

@mvdbeek what do you think?
This would make it possible to tag files instead of renaming them as it is currently on the VGP workflow.

**Comment by mvdbeek** [comment]
@astrovsky01 @OlegZharkov is that fair if I assign you both ?

**Comment by bgruening** [comment]
> @bgruening Is the second point helping with the naming problem?

Indirectly. The file still needs to be renamed in the workflow, but you don't need to specify the entire path. And since you have a tag associated with datasets (lets say all datasets that should end up in one directory are tagged with the same tag) an exporting workflow will autoselect those datasets to the correct exporting step (with the correct directory).

**Comment by mvdbeek** [comment]
I think that works with https://github.com/galaxyproject/galaxy/pull/12759 now
