### ISSUE TITLE
Set path when exporting files to remote repository 

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#12362]
When using the tool :  **Export datasets** to remote files source  on test.galaxyproject.org

The need : 
- We need to be able to provide a path when we export files to organize files in a repo
- This include creating directories
- Ideally, we would have the ability to export in bulk files and put them in different places

Right now we can do that using a hack on .eu with the tool "Export datasets to different data storages". We write the paths in the file names e.g : "species/assembly/version/file.fasta" and the files are put in the right place in the repo. It is not currently possible with the tool on test that parses out the `/` character. 
The other problem is it doesn't work when the path is in the name of the collection, meaning the renaming can't be done in a workflow, the collection files need to be renamed manually or by rules, which is lengthy when we deal with a lot of collections. 

Can we find a way to make these work?

**Comment by Delphine-L** [comment]
History with an example of files to export (named with the desired path ) : https://usegalaxy.eu/u/delphine-l/h/example-file-paths

**Comment by mvdbeek** [comment]
I think we've got this now.
