### ISSUE TITLE
Admin sorting by disk usage doesn't treat zero correctly 

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#12367]
**Describe the bug**
If you sort users by disk usage in decreasing order on Admin, zero comes above all other values.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 20.05

![image](https://user-images.githubusercontent.com/338642/130327331-34d1e3ef-5d09-4b2a-bf2c-6a174fbfb502.png)

**Comment by assuntad23** [comment]
@afgane @cat-bro Can we close this issue now?

**Comment by cat-bro** [comment]
@assuntad yes, thanks!
