### ISSUE TITLE
New molecule/atomic structure datatypes

### ISSUE THREAD

**Issue by elichad** [galaxyproject/galaxy#12371]
We (the muon folks) need to support a few new datatypes. These are all different ways of encoding atomic structures. The types are:

- .cell ([CASTEP CELL file](https://www.tcm.phy.cam.ac.uk/castep/documentation/WebHelp/content/modules/castep/expcastepfilecell.htm))
- .cif ([Crystallographic Information Framework](https://www.iucr.org/resources/cif))
- .xyz ([XYZ format](https://en.wikipedia.org/wiki/XYZ_file_format))

These seem like they would fit into the 'molecules' category of datatypes (certainly there is some scope overlap with PDB files which are already supported). Though I see #12364 and now I'm unclear if we can (or should) actually add these datatypes as part of our tool suite. There may well be more datatypes needed in the future.

These file types can be hard to sniff due to flexibility in their content and the existence of other similar file types, so we propose using existing functions in the open-source [Atomic Simulation Environment](https://gitlab.com/ase/ase) to do the sniffing, by trying to read the whole file as the specified data type (this also helps with setting metadata etc.).

I've done some [preliminary work](https://github.com/galaxyproject/galaxy/compare/dev...muon-spectroscopy-computational-project:eli/add-data-types) on this which I can make into a PR if this all sounds appropriate.

**Comment by simonbray** [comment]
That would require ASE to be a Galaxy dependency which might not be a good idea. It would probably be preferable to make installation of ASE optional.

**Comment by bgruening** [comment]
@elichad I would always recommend you to create such PRs and start discussing on those :) 
Despite the optional dependency, which we can figure out I think, this looks pretty cool!
