### ISSUE TITLE
Feature request: Show a UI hint when datasets are being sanitized

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#12395]
We somewhat regularly see admins and new devs wondering why their datasets aren't rendering quite right.

We know when a dataset has been sanitized before view, if we simply added a tip at the top of the window that read something like:

> This dataset has been sanitized for your safety, if you wish to view the unsantizied dataset, simply download it, or request your admin to allow-list this tool (`iuc/fastqc/1.234+galaxy0`, [docs](https://docs.galaxyproject.org/en/master/admin/options.html?highlight=sanitize_allow#sanitize-allowlist-file)).

It would be an easy win to help users self-discover what's happening and be a bit more transparent.

Something like this:

![image](https://user-images.githubusercontent.com/458683/131652449-556bdf99-7e41-4945-9265-5d6144c91050.png)

**Comment by mvdbeek** [comment]
Duplicate of https://github.com/galaxyproject/galaxy/issues/8828 ?

**Comment by hexylena** [comment]
Very much so. I'll copy my text there then.
