### ISSUE TITLE
Datatype select drop down in workflow editor does not search

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#12421]
**Describe the bug**

In the workflow editor, when selecting a datatype for an input datasest, the user is presented with a text box that seems like it should filter with the user's text input. Currently, though, all datatypes are displayed at the same time, and do not filter, so it's just a massive list of every possible datatype, making it difficult to navigate.

<img width="276" alt="Screen Shot 2021-09-08 at 10 31 53 AM" src="https://user-images.githubusercontent.com/40246333/132556931-4d24671d-d3ef-46bd-a7ea-00e81e350a98.png">

**Comment by mvdbeek** [comment]
Not sure where/how we fixed this, but that doesn't seem to be the case anymore.
