### ISSUE TITLE
Yaml Datatypes

### ISSUE THREAD

**Issue by jj-umn** [galaxyproject/galaxy#12431]
I have several applications that rely on a yaml input for parameter settings.  
Should Yaml datatype class(es) be added to:  lib/galaxy/datatypes/text.py

**Comment by bernt-matthias** [comment]
Hey @jj-umn. There is stalled wip here https://github.com/galaxyproject/galaxy/pull/7960 that looks quite good, but needs a bit of polishing.

**Comment by jj-umn** [comment]
@bernt-matthias Thanks.   I didn't think I would be the only person to need this.

**Comment by nsoranzo** [comment]
Fixed by https://github.com/galaxyproject/galaxy/pull/7960 .
