### ISSUE TITLE
Delete multiple collections at once

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#12445]
**Describe the bug**

It seems impossible to delete multiple collections at once

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09
Commit: 7e9ed78283cba10dd89289bbdccb38e2a24436c4

**To Reproduce**

1. Create one ore more collection
2. Select them (via `Operations on multiple datasets`)
3. Try `Delete Datasets` or `Permanently delete datasets`

**Expected behavior**

Collections should be deleted. Maybe one could then rename the options to `Delete` and `Permanently delete` (i.e. omit `"datasets"`)

**Screenshots**

**Additional context**

**Comment by davelopez** [comment]
I can reproduce it too. This was most likely introduced by https://github.com/galaxyproject/galaxy/pull/12231. I will have a look...
