### ISSUE TITLE
Requests: Use eye icon to access running interactive tools and be able to share them

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#12440]
Maybe this has been discussed, but since I couldn't find it in the issues I'll give it a go.

Working with users, I see that many of them expect intuitively to be able to access a running interactive tool by pressing the Eye button in the history item:

![image](https://user-images.githubusercontent.com/368478/133004030-83b29fe6-8ec0-49c6-837e-16c799cf5bfb.png)

instead of having to go to Users -> Active Interactive Tools. Would this be feasible to implement? At least this doesn't seem to work like that in 21.05.

It would be great as well that upon sharing a history with a running interactive tool, the user who imports this would be able to access those interactive tools, currently when importing a history from another user that has a running interactive tool, these won't appear in the User -> Active Interactive Tools window.

Thanks!

**Comment by dannon** [comment]
Good news!  https://github.com/galaxyproject/galaxy/pull/12369 will address the eye icon and a few of the other rough edges around interacting with running ITs.

Sharing a running interactive tool is a significant security issue and we don't have a good path forward here.  For example, the IT might have the user's API key injected into the environment.  That'd mean anyone you share this IT with would own your account.  Needs more thought to figure out how we might be able to handle this gracefully.

**Comment by hexylena** [comment]
Duplicate of a sub-issue in https://github.com/galaxyproject/galaxy/issues/8899

(Personally, I am strongly against sharing ITs it's feels too risky and like an anti-feature. I've had a number of discussions, I cannot figure out a safe way to do it for the ones that inject the API key.)
