### ISSUE TITLE
Pages rendered markdown layout comes out strange, adding text and figure to the right of existing figures.

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#12455]
**Describe the bug**

When creating a user page with markdown on our release_21.05 instance, the rendered markdown has a very strange, "to the side" flow, as can be seen in the picture below.

![image](https://user-images.githubusercontent.com/368478/133261500-c5399acf-1d64-42db-995d-eedf7db91bfa.png)

This was achieved through the following markdown:

```
# Initial data import

Data was imported from Library item [CVRM Wu 2018](), producing a Single Cell Experiment dataset:

---galaxy
history_dataset_link(history_dataset_id=1aee95df0fc76c8d)
---

This was then transformed to Seurat and to Scanpy, using the Seurat filter cells tool and the SCE Easy tool respectively.

# tSNE plot visualisation

The Single Cell Experiment object already included a tSNE dimensionality reduction calculated, which looks like this (resolution=0.7):


---galaxy
history_dataset_as_image(history_dataset_id=41c4bd1dddcddd7e)
---

Maybe some more text here helps with the layout. Maybe some more text here helps with the layout. Maybe some more text here helps with the layout.

# UMAP plot visualisation

Using the AnnData object from the SCEasy transformation, we do a quick UMAP plot, to realise (for the same resolution), that there seems to be some batch effect:


---galaxy
history_dataset_as_image(history_dataset_id=988d3e46dc8cd4fa)
---

Indeed, observing this same UMAP through the cellxgene interactive view, we see that the UMAP
dimensionality reduction has been heavily biased by the platform:


---galaxy
history_dataset_as_image(history_dataset_id=b619176ed8229c1e)
---

After executing normalisation, find variable genes, running PCA and batch correction with Harmony, the kNN graph is computed with this corrected PCA, and from this new neighbours graph UMAP is recomputed


---galaxy
history_dataset_display(history_dataset_id=ee5ce903b8e02d2c)
---

producing now a better UMAP, with less effects from the platform and showing more adequately
the clusters previously identified with resolution 0.7


---galaxy
history_dataset_as_image(history_dataset_id=4b2737704b09c591)
---

The whole workflow encompassing all needed operations can be seen/imported here:

---galaxy
workflow_display(workflow_id=a8811b21192bbda8)
---

An interactive session to cellxgene showing the final AnnData object with UMAP, tSNE and multiple clusters resolution can be accessed [here]() for the next 20 days.
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.05
Commit: fa3828a89ef704d1094878530b3892519536f42f (release_21.05 branch)

**To Reproduce**
1. Go to the page creation menu
2. Create a new page
3. Paste the above, possibly basing it on a history where you have some PNGs. Replace `---` for triple backticks.
4. Click on the Eye button to save and preview.
5. See the unexpected layout.

**Expected behavior**

I would expect the flow of the text to go downwards, not putting text and figures to the right of existing figures.

**Screenshots**

**Additional context**

Thanks!

**Comment by dannon** [comment]
@pcm32 This is fixed in https://github.com/galaxyproject/galaxy/pull/12085, which will be in 21.09.

What you're seeing was an attempt to support a two column layout here, but it didn't quite work out.  We plan to revisit how columns might flow in pages in future revisions.

**Comment by pcm32** [comment]
Thanks @dannon ! I'm sorry for the duplicated issue, I searched for issues with the word "pages", I would have found it if using the word "report" I guess.

If you think that such backport would be accepted, yeah, that would be great. I can open a PR. Is it just a PR from Helena's branch to release_21.05 or there is something else I need to do?

**Comment by dannon** [comment]
@pcm32 No worries at all!  I'm actually *very* happy when we get issues that are already fixed -- better than the alternative!  ;)

And yeah, I'll merge it if you want to do that.  All you'd have to do would be to check out a branch from 21.05, cherry-pick that one commit over (67f976f5cab840d42a5b494f8ebecb9f79e5c2d5), and then PR it against the core 21.05.
