### ISSUE TITLE
Some issues with Virtual Scroller

### ISSUE THREAD

**Issue by assuntad23** [galaxyproject/galaxy#12458]
**Describe the bug**
This is a list of the issues I found when playing with the Virtual Scroller. I created a history with a dataset of 1008 items to test this with. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09/dev

1. Double scroll bar makes scrolling confusing. 
- It's hard to tell where you are in the history
- Larger bar jumps around and changes size a bit. 
- What is the purpose of the large bar? 
- Should they be next to eachother instead of on top of eachother? 

2. When scrolling though history with mouse scroller
- Smoothly scrolls for about three long "pulls", then stops and jumps to a seemingly random place in the history (at one point it was 500 datasets lower, at another time it was 800 datasets away)
- After about 300 datasets pass by or so, the history pauses on loading content and you are scrolling through a grey box until it catches up.

3. Top & Bottom of list Oddities
- When at the top, if waiting for a job to run, you must scroll up to see it. The history does not expand to cover the new job in the queue
- When all the way at the bottom, it is possible to show just one dataset, and a whole grey box, even if you have a bunch of datasets. This seems weird. 

**To Reproduce**
1. Create a longer history 
2. Using the new history, try to scroll up and down fast
3. Try to find a specific place in the history, like a midway point
4. Scroll all the way to the bottom 
5. Scroll all the way to the top
6. Add a job to the queue

**Expected behavior**
The scrolling should behave more consistently and should be easier to navigate through the history. Ease of use for new users is important too. 

**Screenshots**
Here's a video of me playing around with it a bit. It shows some of the odd behaviors. 
https://user-images.githubusercontent.com/26912553/133289648-b827244f-478d-424f-940b-1e1a70203384.mp4

** Vue Virtual Scroller Swap **

https://user-images.githubusercontent.com/26912553/134208000-badf53f9-c169-428e-9e15-adff6f155b88.mp4

**Comment by ic4f** [comment]
I've observed most of the issues listed here on a smaller sample size (n=100) in Chrome.

**Comment by dannon** [comment]
Closing this as resolved since we've ditched that virtual scroller.  Thanks for all the diagnosis and work here @assuntad23.
