### ISSUE TITLE
Admin panel looks odd

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#12454]
**Describe the bug**
Admin panel links are styled oddly

<img width="321" alt="Screenshot 2021-09-14 at 10 55 42" src="https://user-images.githubusercontent.com/6804901/133227901-c6d10455-8f71-49db-9143-714e2198bfad.png">

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09.dev0
Commit: c357f5e4fef1e841860c18fd462405722297046a

**To Reproduce**
1. Go to admin panel

**Expected behavior**
I guess it should look more like 21.05 ?
<img width="343" alt="Screenshot 2021-09-14 at 11 00 06" src="https://user-images.githubusercontent.com/6804901/133228362-a901783b-69ea-4f2f-84f7-8494da39aeec.png">

**Comment by neoformit** [comment]
Strange, I'm on Linux Chrome with Galaxy 21.09 and it looks normal:

![image](https://user-images.githubusercontent.com/42562517/133526341-45375d17-4f94-4b91-a638-b94f46ad8e21.png)

**Comment by ic4f** [comment]
I'm also on Linux and on Chrome, I have the same messed-up layout as @mvdbeek 
version: 21.09.dev0
commit: 2f5b7f0b4c
Chrome: 93.0.4577.63
OS: Fedora 34

This does not happen on 21.05.

![zzz](https://user-images.githubusercontent.com/6132258/133553849-84a60dc2-eeed-402d-9c8d-7c1450035821.png)

**Comment by mvdbeek** [comment]
Fixed in #12497
