### ISSUE TITLE
Not possible to unselect all datasets in beta history

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#12470]
**Describe the bug**

**Galaxy Version and/or server at which you observed the bug**
beb619054fba350e82601fc0e3b0df27d99d8adb
21.09.dev0

**To Reproduce**
In beta history, click the select icon

**Expected behavior**
Should be able to unselect all (that should probably actually be the default)

**Screenshots**
<img width="302" alt="Screenshot 2021-09-16 at 10 18 33" src="https://user-images.githubusercontent.com/6804901/133576786-326c11fd-bfbb-41a7-b14a-1a0222258224.png">

**Comment by itisAliRH** [comment]
Fixed in #13705
