### ISSUE TITLE
Beta history: history edit tag input loses focus when mouse cursor is moved over a dataset item

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#12478]
**Describe the bug**
In the beta history, the history edit tag input loses focus when mouse cursor is moved over a dataset item

Galaxy version: 21.09.dev0
Commit: 21db5e3458

**To Reproduce**
1. Enable beta history: history options > use beta history panel.
2. Make sure your history has at least 1 dataset.
3. Click the edit history icon.
4. Click the tag icon the 2 text boxes. (the icon disappears and the input element comes into focus and becomes editable and the placeholder "Add Tags" appears).
5. Before typing anything, move the mouse cursor ***down, over the list of dataset items.*** As soon as the cursor is over a dataset item, the input looses focus, the placeholder disappears and the tag icon will reappears.

**Expected behavior**
The input should not lose focus on cursor movement (the old history has the correct behavior)

**Comment by dannon** [comment]
Just checked, this is fixed in the latest version of the new history.
