### ISSUE TITLE
Beta history: dataset edit tag input loses focus when mouse cursor moves out

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#12479]
**Describe the bug**
This is similar to #12478
In the beta history, the dataset edit tag input loses focus when mouse cursor moves out.

Galaxy version: 21.09.dev0
Commit: 21db5e3458

**To Reproduce**
1. Enable beta history: history options > use beta history panel.
2. Make sure your history has at least 1 dataset.
3. Click any dataset item to expand it.
4. Click the edit icon.
5. Click the tag icon the 2 text boxes. (the icon disappears and the input element comes into focus and becomes editable and the placeholder "Add Tags" appears).
6. Before typing anything, move the mouse cursor off the placeholder; the input looses focus, the placeholder disappears and the tag icon will reappears.

**Expected behavior**
The input should not lose focus on cursor movement (the old history has the correct behavior)

**Comment by dannon** [comment]
This is fixed in the new history where we now use the central pane for editing these attributes.
