### ISSUE TITLE
Beta history: scrollbar handle jumping to mid-screen on page reload w/large histories

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#12490]
**Describe the bug**
In the beta history, with a sufficiently large number of items in the history, on page reload, the scrollbar handle will appear before the items are displayed, but once the items are displayed the handle will jump to the middle of the scrollbar, then jump back to the top. 

This **does not happen on smaller histories**, so it's a performance issue. The tested history had 3 displayed items, 2 of them were collections that contained 716 pairs (1432 datasets). This did not happen on a history that had a collection with 200 datasets. But on larger histories this behavior is consistent.

Related to #12458

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09.dev0 
Commit: 3c3d9e493cbaf69473e427d13ef1054076c680a3
OS: Linux
browser: Chrome 93.0.4577.63

**To Reproduce**
1. Enable beta history
2. Load enough datasets (tested with n=1432)
3. Group datasets into a collection
4. Hit reload and observe the handle jumping

**Expected behavior**
Handle should not jump around.

**Screenshots**
Here's a video: https://youtu.be/_YBFKe7ezY4 (it shows 2 page reloads)

**Comment by dannon** [comment]
Closing this as we're not using the virtual scroller anymore.
