### ISSUE TITLE
bug or feature: "saved datasets" shown in center panel or as one page depending on the current page

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#1252]
When at "analyze data" the "saved datasets" are shown in the center panel. When coming from e.g. workflows, "saved datasets" is shown as one page, i.e. without showing the 'current history' one can copy to.

If the action could be copy to ['current history', new history named .., 'history x'] this behavior would be more acceptable i guess..

**Comment by hexylena** [comment]
Seems to be unified now
