### ISSUE TITLE
cannot edit name of collection during upload (eu/21.05)

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#12535]
![2021-09-23_10-43](https://user-images.githubusercontent.com/458683/134478408-28682341-a210-4986-b9f2-5afba784820a.png)

I tried clicking the button to the left but it seems non-functional

**Comment by wm75** [comment]
I guess that button should just be removed? You can set the name of the collection in the subsequent "Build" dialog.

**Comment by hexylena** [comment]
I did not see a subsequent build dialog, huh. Maybe i clicked away too quickly.

**Comment by wm75** [comment]
After you press Start and the uploads have been queued, the Build button next to Start gets enabled. If you click it, it brings up the dialog I'm talking about.
If you don't press Build, your data actually doesn't end up in a collection, but gets uploaded as regular datasets.

**Comment by hexylena** [comment]
Ahh that's what I missed. I was following it up with another upload and screwed it up so I hit reset, and completely missed the build option. At least removing the name field seems sensible
