### ISSUE TITLE
Profiling the beta history

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#12534]
These are the results of profiling the current and beta history UIs. 

### METHOD SUMMARY
Expand a collection of dataset pairs; measure (a) time from click to display on UI (b) request duration
Try collections of sizes 10, 100, 500
Sample size for each collection: 10 (number of measurements)

### DESCRIPTIVE STATS
![ZZZ](https://user-images.githubusercontent.com/6132258/134390648-e349ecc6-c0f5-45d5-801e-15fb09ebff0b.png)

### NOTES
The sample sizes are not large enough to do inferential statistics. However, if we *limit conclusions to the observed data*, we see, at least, the following: 
- The new history's request duration is orders of magnitude less than that of the current history
- It is not obvious whether the new history's request duration varies with the size of the collection (unlike the current history, where the request appears to grow with the size of the collection)
- The UI response time for the old history appears to visibly grow with the size of the collection. This is not the case for the new history
- The old history appears to have a more responsive UI on smaller sizes (when there's less items to display: tested on n=10 and n=100); however, on n=500, the new history appears to be faster

### METHOD DETAILS
Created 2 fresh clones. Ran several measurements on both (one instance at a time) to verify measurements were consistent. Picket one instance for subsequent formal measurements.

**Sample data generation:**
1. Generated 2 very small source fastq datasets (5 sequences each, 2.7K each): a0_1.fq, a0_2.fq
2. Used source datasets to generate paired dataset samples of size 20, 200, 1000
3. Created a new history for each sample. Uploaded datasets.
4. For each history: created paired dataset collection from all datasets in that history
5. Result: 4 histories with collections of size 10, 100, 500

**Measurement procedure:**
1. Run browser in incognito mode, one instance at a time (no other Galaxy instances are running)2. 
2. Clear cache (browsing data) (may not affect anything, so just a sanity check)
3. Logged in as admin
4. Before each measurement:
    - reload page
    - dev tools/application tab: clear: local storage (not session storage), indexeddb, cache storage
5. Measure:
    - dev tools/performance tab: start recording > UI: click collection tab > wait for UI to display expanded collection > dev tools: stop recording
    - dev tools/performance tab: event log: record mouse click event start time
    - dev tools/performance tab: screenshots panel
    - Hover over the screenshots panel in the overview, zoom in until the first screenshot with the expected UI is displayed at max time resolution. Record the time.
    - dev tools/network tab: Locate the line with the response that contains the data (the old history had 2 potentially relevant responses, one with the data, the other with a brief summary, so I recorded both). Record the time.
 
**Notes:**
Selecting the data point for start time was simple: mouse click happened in both histories and unambiguosly indicated when the action started.

Selecting the data point for end time was difficult.The paint/load/render/script events vary considerably across the two histories. Furthermore, the last paint/render/script event in the recorded segment does not indicate the successful completion of the measured action: varying recording duration showed that those data depend entirely on when the stop recording button is pressed. Therefore, using the first screenshot that had the expected UI change appeared to be the only reliable way to do it. This is, still, not entirely consistent, as (I think) the frequency of captured screenshots diminishes as the duration of the recording increases. But I think this measurement is good enough for our purposes here.

For the new history, the first measurement in the sample was always an outlier. I decided to drop it for both histories, since it clearly was also measuring "something else" Here are the dropped measurements (first for each sample:
![aaa](https://user-images.githubusercontent.com/6132258/134400078-54ff78d3-d007-47b4-b2a7-e757ccf42690.png)

### EXAMPLE OF RAW DATA
(Raw data is here: https://gist.github.com/ic4f/331bfc06c029a9d125b44001e150c240)
![xxxx](https://user-images.githubusercontent.com/6132258/134390847-b313a5fc-9c45-47dc-97e5-d24ceca1dae2.png)

### HARDWARE/SOFTWARE:
- CPU: AMD Ryzen 9 5900X 12-Core
- OS: Linux/Fedora 34
- Browser: Chrome Version 93.0.4577.63
- Galaxy version: 21.09.dev0
- Galaxy commit: b793ccdb463fef14e54a62fe8430807b96e8875b

**Comment by dannon** [comment]
Pivoting back to the old endpoints combined with the new virtual scroller has resolved performance concerns here for now, thanks for all the profiling.  We'll want to take another look down the road as we make optimization passes, but I'll close this one out for now.
