### ISSUE TITLE
Show the number of datasets in the collection at the top level

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1256]
Looking something like this
![screenshot 2015-12-07 11 48 25](https://cloud.githubusercontent.com/assets/1814954/11633344/c05ff074-9cd8-11e5-8cdc-f3abf8fdf74f.png)

**Comment by jxtx** [comment]
How about using the folder icon which identifies using a collection on the tool form with the number of datasets, and show the longer description on hover?

**Comment by hexylena** [comment]
:+1:

**Comment by nsoranzo** [comment]
:+1:

**Comment by carlfeberhard** [comment]
(Feels like a duplicate of #400?)

I'm down with this - but, it requires that the **summary** json have the number of contained datasets/elements (the full details are fetched when the collection is expanded). At the very least (I think) this is an sql count and another query for each collection in the history. Could be wrong. That said, I'll see what I can do.

**Comment by carlfeberhard** [comment]
Duplicate of #400
