### ISSUE TITLE
Resume dependent jobs of failed collection element does not work

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#12564]
On our instance, 21.05, the rerun of a failed job in a collection (list of pairs) does not work properly. The job gets rerun as a new job (as a new single dataset in the history) and is not part of a collection anymore and the remaining steps of the workflow do not resume after the job successfully finishes. Is this issue known and possibly already fixed?

from https://gitter.im/galaxyproject/Lobby?at=6151bfbbf3449e13a496b42d
> Did you have the option to specify Replace elements in collection? and Resume dependencies from this job? on the tool form ?
> Just re-running a single job seems like the right thing to do
> If you check both, paused jobs should continue to run
> So the Replace elements in collection is not present. Only the Resume dep...
> Hmm, yeah, what tool is this ?
>trimmomatic
> I think we've got a logic error in there
> I think the bug is that the option isn't shown ... can you open an issue to keep track of this ?

ping @mvdbeek and @cgirardot

**Comment by mvdbeek** [comment]
Probably need to rethink the logic in https://github.com/mvdbeek/galaxy/blob/ed3e1ac0ac5d4ebce2bd0c27a1b307a72eef62b5/lib/galaxy/model/__init__.py#L1543-L1548. The tool in question was trimmomatic.

**Comment by scholtalbers** [comment]
@mvdbeek this is quite blocking for a @cgirardot. Looking at the logic here: https://github.com/mvdbeek/galaxy/blob/release_21.05/client/src/mvc/tool/tool-form.js#L180 I don't see a difference in the behavior of `resume dependencies` and `replace elements in collection`. On the tool form it looks like its just a label change, but not an actual different action is attached to it?

**Comment by mvdbeek** [comment]
You're not reading this right. This adds an additional parameter, which will replace the element in the failed collection.

**Comment by scholtalbers** [comment]
hmm, I'm not seeing it. There is a if/else on the label, and a push onto the inputs array with an option named `rerun_remap_job_id`. as far as i can tell, there is no loop there? And only in the end its the same if `remappable=True` or `remappable=job_produced_collection_elements`. Further in the codebase (https://github.com/mvdbeek/galaxy/blob/release_21.05/lib/galaxy/tools/actions/__init__.py#L652) it seems the replacement should be done as soon as remap is true?

**Comment by mvdbeek** [comment]
We're at different stages there. When you build the form via the re-run button we decide if the boolean parameter should be there. If it is, it will be added to the run request body when you click execute. I'm not sure what loop you're talking about. https://github.com/mvdbeek/galaxy/blob/release_21.05/lib/galaxy/tools/actions/__init__.py#L652 is downstream of the replacement -- if you don't replace the collection item you will have your downstream jobs wait for the collection that is still not a valid input.

I will make sure we have a fix in 21.09, but if you want to give fixing it a try you're welcome of course.

**Comment by scholtalbers** [comment]
ok, I don't think I'm able to solve this one. But I am wondering if we are actually hitting https://github.com/mvdbeek/galaxy/blob/5d1125e4c5eda4cfc2106213f417d2323ba7448a/lib/galaxy/model/__init__.py#L4399 instead of the form being incorrect.

**Comment by mvdbeek** [comment]
That's a good point, I;ll make sure that works.

**Comment by mvdbeek** [comment]
Hmm, I'm having a bit of trouble reproducing this. The trimmomatic input is a list of pairs, and the output is a list of pairs as well, right ?

**Comment by cgirardot** [comment]
Yes this is correct. The version used here is `Galaxy Version 0.36.6`

**Comment by scholtalbers** [comment]
We are not 100% certain if for all, but at least for some of the failed datasets, they were also resubmitted automatically before, due to slurm resource constraints and the `resubmit condition="walltime_reached"`.

**Comment by mvdbeek** [comment]
OK, so after a lot of false starts https://github.com/galaxyproject/galaxy/pull/12621 should enable this. I'm afraid this won't help once you've re-run a job using the `replace element` or `resume jobs` option, which breaks the link between the job that depends on the input dataset and the failed job.
