### ISSUE TITLE
Tag sanitization can lead to uncaught exceptions

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#12568]
**Describe the bug**
We sanitize certain tag characters, like `.`. If nothing of the tag is valid the tag value is `None`.

This then fails like so:
```
AttributeError: 'NoneType' object has no attribute 'lower'
  File "galaxy/web/framework/decorators.py", line 312, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "galaxy/webapps/galaxy/api/history_contents.py", line 1669, in update
    trans, history_id, id, payload, serialization_params, contents_type
  File "galaxy/webapps/galaxy/api/history_contents.py", line 537, in update
    return self.__update_dataset(trans, history_id, id, payload, serialization_params)
  File "galaxy/webapps/galaxy/api/history_contents.py", line 936, in __update_dataset
    self.__deserialize_dataset(trans, hda, payload)
  File "galaxy/webapps/galaxy/api/history_contents.py", line 969, in __deserialize_dataset
    self.hda_deserializer.deserialize(hda, payload, user=trans.user, trans=trans)
  File "galaxy/managers/base.py", line 762, in deserialize
    new_dict[key] = self.deserializers[key](item, key, val, **context)
  File "galaxy/managers/taggable.py", line 93, in deserialize_tags
    _tags_from_strings(item, self.app.tag_handler, new_tags_list, user=user)
  File "galaxy/managers/taggable.py", line 44, in _tags_from_strings
    tag_handler.apply_item_tags(user, item, unicodify(new_tags_str, 'utf-8'))
  File "galaxy/model/tags.py", line 195, in apply_item_tags
    self.apply_item_tag(user, item, name, value, flush=flush)
  File "galaxy/model/tags.py", line 159, in apply_item_tag
    lc_name = name.lower()
```
There's a good amount of issue in sentry that are variations on this theme:
https://sentry.galaxyproject.org/organizations/galaxy/issues/40851/?project=3&query=is%3Aunresolved+apply_item_tag&statsPeriod=14d
https://sentry.galaxyproject.org/organizations/galaxy/issues/44642/?project=3&query=is%3Aunresolved+apply_item_tag&statsPeriod=14d
https://sentry.galaxyproject.org/organizations/galaxy/issues/45723/?project=3&query=is%3Aunresolved+apply_item_tag&statsPeriod=14d

Some via the UI, others via the tagging tool.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09, but affects older version as well.

**To Reproduce**
Open the tag editor for a dataset, enter `.` and see a nice traceback in the logs and a generic `An error occurred` error message in the UI.

**Expected behavior**
- [ ] The UI should prevent submitting clearly invalid tags like this and give some guidance
- [ ] The backend should not raise uncaught exceptions ... now I am not a big fan of silently sanitizing the tags, so I don't think we should just return `None`. A MessageException might be the right response in the context of API calls.
- [ ] The tool interface should have an option to specify whether invalid tags should be skipped

**Comment by davelopez** [comment]
I can take a look at the backend part to fix the exception.

**Comment by davelopez** [comment]
I guess the second task above can be check now with https://github.com/galaxyproject/galaxy/pull/12582.
For the other two we may need a frontend person :sweat_smile:
