### ISSUE TITLE
Workflow: Loading, Saving, Editing with Large History

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#1257]
If you have a large history and try to edit, save, or add or modify steps in a workflow while that large history is your current history, things will take a long time or will fail with time out.

In my case, I have a history with >7000 items and 2 step workflow (input collection and single tool), about 95% of the time Galaxy times-out when trying to load/save/add new nodes in the editor.

Creating an empty history and setting it as the current history allows the editor to function normally. Then you can swap back to the history that you want to use when running the workflow. This is a really bad workaround.

There is no reason for the history contents to be a factor when the workflow editor is being used.

**Comment by guerler** [comment]
Can you try this patch here: https://github.com/galaxyproject/galaxy/compare/dev...guerler:fix_workflow_loading_000

**Comment by guerler** [comment]
Can you do me a favor and export one of your slow workflows to a file and check the file size? ping @blankenberg

**Comment by guerler** [comment]
Im assuming this has been resolved.
