### ISSUE TITLE
New release announcement icon does not remember state

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#12577]
The icon implemented by @hexylena in https://github.com/galaxyproject/galaxy/pull/12396 turns from white to an outlined shape when you first click on it.
However, it currently returns to unread white on the next page refresh. Tested on FF and Chromium.
Possibly related to the fact that a workaround had to be implemented for the not yet available 21.09 release notes?

**Comment by dannon** [comment]
I'll take a look, thanks @wm75

**Comment by dannon** [comment]
@hexylena Yep, that's what it's going to be; we'll want to go ahead and merge a placeholder release notes which, now that the freeze is on, is reasonable I guess; otherwise it'll just go to a broken link.

**Comment by mvdbeek** [comment]
Yeah, feel free to merge #12567

**Comment by hexylena** [comment]
Do we want folks on main seeing the new release notes before they're finished though? That would kind of defeat the purpose of the webhook then a bit, if they just see blank, dismiss it, and then never see the real ones. (But ok, maybe this is acceptable during this release and we figure out something better for the future.)
