### ISSUE TITLE
Dataset collections mixed up internally after applying rules to existing collection

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#12576]
**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09

**To Reproduce**
Follow https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/upload-rules-advanced/tutorial.html#apply-rules-to-existing-collections

At the last step (i.e. after you created the original collection and used Apply Rules twice to build reorganized collections),
try to run Apply Rules again on the original, flat collection.

The rule builder will extract column information from one of the reorganized collections instead of the original, selected one.
Same if you select one of the reorganized ones -> will use identifiers from original collection

**Shared history with the problem**
https://usegalaxy.org/u/wolma/h/test-rule-based

**Screenshots**

**Additional context**
Discovered during 21.09 release testing

**Comment by mvdbeek** [comment]
I looked at this, and to me it looks like selecting another collection does not update the target in the rule editor button. Consequently the wrong collection is retrieved from the API. This is probably related to the vue-ification of the tool form.

With this:
```diff
diff --git a/client/src/mvc/ui/ui-rules-edit.js b/client/src/mvc/ui/ui-rules-edit.js
index ad53214929..7822ba7361 100644
--- a/client/src/mvc/ui/ui-rules-edit.js
+++ b/client/src/mvc/ui/ui-rules-edit.js
@@ -106,6 +106,7 @@ var View = Backbone.View.extend({
 
     /** Return/Set current value */
     value: function (new_value) {
+        console.log("setting new value", new_value);
         if (new_value !== undefined) {
             this._setValue(new_value);
         } else {
```
I'm seeing `setting new value undefined` in my console when I select another collection, so I guess passing the new parameter is broken somewhere.

**Comment by mvdbeek** [comment]
OK, so if you select the same item in the select list a few times it will actually load the right collection. @guerler do you have any insights into this ?

**Comment by wm75** [comment]
For me, I'm seemingly getting collections from that history randomly selected when I change the item in the select list. So, yes, if I play around long enough, I will eventually see the right thing in the rule editor.
