### ISSUE TITLE
Job details not updating

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#12585]
**Describe the bug**
(From @natefoo on galaxyproject/dev)

The dataset info page on usegalaxy.org (now running 21.09) seems to have caching problems - i.e. the destination params, stdout/stderr, etc. aren't updating as they are changed in the database.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09

**Expected behavior**
Job details update with job state changes, etc.  Currently they reuse the first observed data.

**Comment by mvdbeek** [comment]
Thanks for fixing that @dannon!
