### ISSUE TITLE
Retire the masthead option Visualize > Interactive Environments?

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#12587]
**Describe the bug**
GIEs are now tools in the tool panel, and not accessible under `Visualize > Interactive Environments`. Confusing for end users. Any IEs that are _running_ are found under `User > Active InteractiveTools` instead.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 
* https://usegalaxy.org/api/version `"version_major": "21.09", "version_minor": "rc1"`
* https://usegalaxy.eu/api/version `"version_major": "21.05", "version_minor": "1.dev0"`
* https://live.usegalaxy.eu/api/version `"version_major": "21.05", "version_minor": "1.dev0"`

**To Reproduce**
1. Go to `Visualize` in the masthead
2. Click on `Interactive Environments`
3. Pull down the menu for `GIE`
4. See nothing is available
5. Click on the `Admin Docs` link (https://docs.galaxyproject.org/en/master/admin/interactive_environments.html). The file doesn't exist, servers report a version of this:
 > NoSuchKeyThe specified key does not exist.en/master/admin/interactive_environments.htmlR0ZHJT71ZHHKVXFE3OkPHC6cJOyoCZMPrkOfQxPCxoteSUMDtWrEDcnrgc8WttMNPyZ5hKhMp3emZ3SoglKuccCK2Ug=

There is an admin doc here https://docs.galaxyproject.org/en/master/dev/interactive_environments.html?highlight=gie

**Expected behavior**
Remove `Interactive Environments` from the `Visualize` menu. The entire menu could probably be dropped and just go directly to where `Create Vizualization` points to now. Admin doc link should be updated or removed.

**Screenshots**

----
<img width="530" alt="Screen Shot 2021-09-28 at 1 26 31 PM" src="https://user-images.githubusercontent.com/8999735/135163767-33d09ad1-c2c1-494c-b99a-f155a4ea8a00.png">

----

<img width="683" alt="Screen Shot 2021-09-28 at 1 28 25 PM" src="https://user-images.githubusercontent.com/8999735/135163882-c887eb6f-a051-4c60-ad1c-7b6fabd729e1.png">

----

**Additional context**
Not new, was in `21.05` but seems worth cleaning up in `21.09`. 

If there is a concern that older deployments upgrading to `21.09` might still be using this, or we want to leave this option in Galaxy for some other reason, maybe make it a true/false toggle in a config file? Default = false. If nothing else is done for this release, at least remove or update the `Admin Docs` link out. Consider adding in a redirect at https://docs.galaxyproject.org so the old link points to the current link in older deployments, chats, forums.

cc @dannon @guerler @hexylena

**Comment by dannon** [comment]
Done in #12599
