### ISSUE TITLE
Copying history export URL to clipboard not working

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#12589]
**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09 (first time I tried this so possibly existing in previous versions)
Browser: Chromium

![Screenshot from 2021-09-29 12-07-05](https://user-images.githubusercontent.com/4742081/135248622-7f8eaeac-dadf-442a-8090-1a52990203ae.png)

Clicking on the chain/link icon reports success, but copies only 'undefined' to the clipboard

**Additional context**
Discovered during 21.09 release testing.

**Comment by dannon** [comment]
@wm75 Thanks!  Good catch, should be fixed in #12618
