### ISSUE TITLE
Workflow reports/pages not rendering properly

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#12592]
**Describe the bug**
Elements in workflow reports/derived pages are not spaced correctly in all cases.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09 (usegalaxy.org)

![Screenshot from 2021-09-29 17-21-16](https://user-images.githubusercontent.com/4742081/135300057-20d25f03-8444-4084-b7b7-f9aefd13d41f.png)

Seems headers of elements are not taken into account?

![Screenshot from 2021-09-29 17-22-13](https://user-images.githubusercontent.com/4742081/135300164-8bf5d097-f87e-47cf-992f-29bcfe83d6fa.png)

and there's far too little space reserved for the workflow_display (in the "background" of the above image).

Not sure whether usegalaxy.org runs with the default stylesheet for the reports, but if so that needs a bit of tweaking.
 
**Additional context**
Discovered during 21.09 release testing.

**Comment by wm75** [comment]
To clarify, things don't look too bad as long as the workflow_display is the last element of the report, but only then.

**Comment by mvdbeek** [comment]
Can you publish one of the pages and link it up ?

**Comment by wm75** [comment]
Sure, good idea :)
https://usegalaxy.org/u/wolma/p/invocation-report-9d7696602bd48b54

**Comment by wm75** [comment]
Hmm, that's a bit unfortunate: to show the workflow_display it's not enough to make the corresponding WF accessible via link, but you need to publish it or share it with the specific user.
Published it for now.
