### ISSUE TITLE
Unexpanded workflow forms don't allow export to new history

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#12595]
<img width="569" alt="Screen Shot 2021-09-29 at 10 30 59 AM" src="https://user-images.githubusercontent.com/40246333/135319356-e35f4ecc-5629-466a-871f-cee41b105cd9.png">

I don't know if it's intentional, but workflows pages that have not been expanded to show every step do not give the option for the user to export results to another history.

To reproduce: Click to run a workflow that does not expand by default

Expected behavior: "history options" boolean input at the top of the workflow, which allows export to a new user-named history

Actual behavior: No option available

**Comment by guerler** [comment]
@astrovsky01 to my knowledge the history option is not shown for the simplified workflow form. This is probably a good feature request.
