### ISSUE TITLE
SVG files in New User Welcome not displayed in Kubernetes

### ISSUE THREAD

**Issue by ksuderman** [galaxyproject/galaxy#12606]
**Describe the bug**
This is almost certainly a problem with the Kubernetes deployment and I have opened an issue in the [Galaxy Helm Chart](https://github.com/galaxyproject/galaxy-helm/issues/330), however I wanted to get a few more eyeballs on the problem

The root cause of the problem is that the SVG files are not served with a `Content-Type` header so they are not displayed in Safari or Chrome.  The images are displayed correctly in Firefox (apparently it doesn't care about the Content-Type).  I have addressed the most common culprits (missing mime.types file, missing entry for svg files) so there is something else going on.

**Galaxy Version and/or server at which you observed the bug**
21.09-rc1

**To Reproduce**
Visit http://34.73.177.163/galaxy/welcome/new (this is an ephemeral instance and may go away without notice)

**Comment by almahmoud** [comment]
I believe this issue is specific to the Nginx configuration in the helm chart, so I'd personally close this issue in favor of the original https://github.com/galaxyproject/galaxy-helm/issues/330 where I listed two possible solutions (one of which I hot-fixed on the above server and seems to work)

**Comment by dannon** [comment]
Thanks!  Closing per request, but feel free to reopen if there's a need to tweak anything else on this end.
