### ISSUE TITLE
Rule-based uploader seems broken

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/galaxy#12602]
Describe the bug
Rule-based uploader seems to be broken.

Galaxy Version and/or server at which you observed the bug
Galaxy Version: 21.09 (usegalaxy.org).  It works fine on 21.05 (usegalaxy.eu)

To Reproduce
Follow the steps in https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/mirna-target-finder/tutorial.html#get-data. It fails both when uploading as dataset and as collection.

Expected behavior
Create four collections

Actual behavior
It triggers an error.

Screenshots
![Screenshot from 2021-09-30 14-57-43](https://user-images.githubusercontent.com/26678117/135459443-5b15c9d1-af46-4934-b7b9-a98657ad5fa0.png)

Additional context
Discovered during 21.09 release testing.

**Comment by mvdbeek** [comment]
I think that looks more like a misconfiguration of usegalaxy.org, since the uploader worked yesterday.

**Comment by mvdbeek** [comment]
Can you share the the history and put a link here ? I suppose this ran on singularity when it shouldn't have.

**Comment by gallardoalba** [comment]
> Can you share the the history and put a link here ? I suppose this ran on singularity when it shouldn't have.

Here is the history, but the failed datasets have been removed https://usegalaxy.org/u/gallardoalba/h/removebeginning . I tried to reproduce it and now it worked :S https://usegalaxy.org/u/gallardoalba/h/error-collections.

**Comment by natefoo** [comment]
It definitely does not run in Singularity, so it's not that.

**Comment by natefoo** [comment]
Correction - it doesn't normally, but if you used the `training` tag on your history, it would.

**Comment by gallardoalba** [comment]
> Correction - it doesn't normally, but if you used the `training` tag on your history, it would.

Then this is the problem.

**Comment by gallardoalba** [comment]
> Sorry, I didn't expect that to affect anyone because I didn't think anyone was using it. Should be fixed now.

Thanks!
