### ISSUE TITLE
Requirements.txt could add hashes

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1260]
https://pip.pypa.io/en/latest/reference/pip_install/#hash-checking-mode

> Since version 8.0, pip can check downloaded package archives against local hashes to protect against remote tampering. To verify a package against one or more hashes, add them to the end of the line:
> 
> ```
> FooProject == 1.2 --hash:sha256=2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824 \
>                   --hash:sha256=486ea46224d1bb4fb680f34f7c9ad96a8f24ec88be73ea8e5a6c65260e9cb8a7
> ```

**Comment by natefoo** [comment]
Is this syntax backwards compatible? Not all people will upgrade to Galaxy pip.

**Comment by hexylena** [comment]
Oh? I thought just about everyone would be using galaxy pip or later. Testing now...

**Comment by natefoo** [comment]
@jmchilton convinced me (#1150) that we should support not forcing everyone into the Galaxy worldview. ;D

**Comment by hexylena** [comment]
``` console
root@27c7be3e3825:/pypa-setuptools-f493e6c4ffd8# cat reqs.txt 
FooProject == 1.2 --hash:sha256=2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824 \
                  --hash:sha256=486ea46224d1bb4fb680f34f7c9ad96a8f24ec88be73ea8e5a6c65260e9cb8a7

root@27c7be3e3825:/pypa-setuptools-f493e6c4ffd8# pip --version
pip 7.1.2 from /usr/local/lib/python2.7/dist-packages/pip-7.1.2-py2.7.egg (python 2.7)
root@27c7be3e3825:/pypa-setuptools-f493e6c4ffd8# pip install -r reqs.txt 
Usage: pip [options]

pip: error: no such option: --hash:sha256
```

it sure isn't backwards compat. :person_frowning:  Time for a `requirements.txt` that others can use and a `requirements-secure.txt` that galaxy can use by default.

**Comment by jmchilton** [comment]
The pinned version is for galaxy and galaxy's pip - why not just use that for hashes. The unpinned version is for vanilla pip. Don't think we need a third file.

**Comment by hexylena** [comment]
Works for me.

**Comment by hexylena** [comment]
Since requirements-pinned doesn't seem to exist yet... I've added this as requirements-pinned.txt for someone to move later whenever @natefoo does his awesome stuff.
