### ISSUE TITLE
In tool forms with multiple selection text boxes, the box will not appear as visible until clicked

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#12611]
**Describe the bug**
On tool forms that have the option to input text to search against available values, until the item is clicked, it appears as though there is no text box for input at all.

**Galaxy Version and/or server at which you observed the bug**
21.09 on ORG

**To Reproduce**
1. create a dataset collection with that uses tags
2. use the deseq tool with 'how' set to 'Select group tags and corresponding levels'
3. observe the factor level 'select groups that correspond to this factor level' input

**Expected behavior**
Parameter input box should be visible empty or populated.

**Screenshots**

<img width="1297" alt="Screen Shot 2021-09-30 at 3 26 25 PM" src="https://user-images.githubusercontent.com/40246333/135538500-a4638495-005d-4d7e-95ed-cbfbdb50567b.png">

<img width="1297" alt="Screen Shot 2021-09-30 at 3 26 38 PM" src="https://user-images.githubusercontent.com/40246333/135538529-795a742b-c2f4-4dec-a136-52a28de68b32.png">

**Comment by guerler** [comment]
@astrovsky01 thanks for reporting this. This is a style issue. I created a PR to align the alert and state color themes for further investigation #12613.

**Comment by dannon** [comment]
Fixed in #12702.
