### ISSUE TITLE
Some fields not encoded in `/api/datasets/<ldda_id>?hda_ldda=ldda` response

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#12610]
**Describe the bug**
The following field are not encoded: `id`, `library_dataset_id`, `parent_library_id`

Example: https://usegalaxy.eu/api/datasets/c1316fd1f9ea9ecf?hda_ldda=ldda

The values are instead correctly encoded in https://usegalaxy.eu/api/libraries/40160950115d555e/contents/6b94bccc71f9c758 (same library dataset).

I believe the issue is due to not using a serializer in https://github.com/galaxyproject/galaxy/blob/9f99ea53ab6886934cdbd914d749dd6002dab6dd/lib/galaxy/webapps/galaxy/api/datasets.py#L160

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.05 (but this is broken in every Galaxy release that exposes this API)

**To Reproduce**
1. Visit https://usegalaxy.eu/api/datasets/c1316fd1f9ea9ecf?hda_ldda=ldda

**Expected behavior**
Encoded values

**Comment by davelopez** [comment]
I'll take a look.
