### ISSUE TITLE
Dataset tags are not appearing consistently

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#12620]
**Describe the bug**
Datasets that have tags only sometimes show their tags when not expanded. The only way to get the dataset to always show the tag is to expand it and select the tag editor. Otherwise, as analyses are run with the datasets, the tags disappear from the general history until full page reload.

**Galaxy Version and/or server at which you observed the bug**
21.09, 21.05, org and eu

**To Reproduce**
1. Upload a dataset
2. give dataset propagating tags
3. run tools on dataset
4. watch tags disappear on original dataset

**Expected behavior**
Dataset tags should always be visible

**Screenshots**
<img width="283" alt="Screen Shot 2021-10-01 at 12 06 47 PM" src="https://user-images.githubusercontent.com/40246333/135673859-562fb332-9465-49b3-9c9e-5f4eead437e4.png">

<img width="281" alt="Screen Shot 2021-10-01 at 12 06 55 PM" src="https://user-images.githubusercontent.com/40246333/135673868-d72a127e-36ac-4a8c-a58b-12edf45867f3.png">

**Additional context**

Tags are also not visible on rules-based uploaded data until a page reload

**Comment by astrovsky01** [comment]
Update: nametags will appear on reload, but all nametags on both the parent and child dataset dataset disappear until then.

**Comment by mvdbeek** [comment]
I'll push this to the next release, but if we have a fix we can apply it as far back as necessary

**Comment by dannon** [comment]
Tested as described and it's all working well now.
