### ISSUE TITLE
improve UX of WF node labels

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1264]
the labels were implemented in https://github.com/galaxyproject/galaxy/pull/1251

we probably need:
- [x] better presentation of validation of 'uniqueness' that won't use Toastr (should be only for async notifications) and just show inline renaming error
- [x] UI for hinting that the label is 'clickable' (possibly the same that is used for History name (dotted border)
- [x] Replace step names with labels when loading workflow and keep insync in the editor.
- [x] James reported landing in a state with duplicated labels on IRC. Proved to be non-trivial to reproduce.
- [x] Allow labeling tool nodes in the editor. (Other nodes use the same View for the editor but tools reuse a view from the tool form).

ping @jxtx

**Comment by hexylena** [comment]
@martenson milestone update?

**Comment by martenson** [comment]
we need a future milestone :)

**Comment by martenson** [comment]
cleared

**Comment by jmchilton** [comment]
Ping @guerler - in response to your IRC question. It would be really nice to unify name and labels to just be labels (since labels are uniform across workflow input types) - it is just a matter of doing it in a backward compatible way I guess.

**Comment by guerler** [comment]
Sounds good.

**Comment by guerler** [comment]
Fixed with a set of PRs, ending with #3644
