### ISSUE TITLE
Allowing Library datasets to be uploaded to a new history

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#1265]
The current behavior of new libraries allows one to choose an existing history to upload library datasets to. It would very useful to enable creating of a new history in this interface as well. So user will have two choices: 
- upload to an existing history (the way it works right now)
- create a new history and upload to it

**Comment by nsoranzo** [comment]
@nekrut Should this be merged in #1177?

**Comment by nekrut** [comment]
Absolutely. How?

**Comment by nsoranzo** [comment]
@nekrut I've merged this in the description of #1177.
