### ISSUE TITLE
Standard library `distutils` module is deprecated in Python 3.10

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#12654]
**Describe the bug**
and scheduled for removal in Python 3.12 (see https://docs.python.org/3.10/whatsnew/3.10.html#distutils ). Importing `distutils` in Python 3.10 generates the following warning:

```
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```

We are using it in `doc/source/conf.versioning.py` and in several scripts in `packages/` .

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: dev
Commit: 1a0a8858a2b0fc46c107412b29d59fccc430dc23

**To Reproduce**
1. `ack --type=python distutils`

**Comment by lennyjuma** [comment]
I'm new to python, how do you solve this error.. I have been forced to downgrade my python version

**Comment by nsoranzo** [comment]
@lennyjuma I don't think this (`distutils`) is what is preventing you from using Galaxy on Python 3.10, since this is just a deprecation at this stage.

**Comment by lennyjuma** [comment]
@nsoranzo thank you for your reply, I solved the issue by creating an environment using conda with an another version of python..

**Comment by ic4f** [comment]
@lennyjuma You can just create a virtual environment with a different python version. If you use virtualenv, then just do this:
`virtualenv -p [path-to-your-python-executable] .venv` Or, using venv: `[path-to-your-python-executable] -m venv .venv` (where .venv in both cases is the directory for the virtual environment). That's all you need!
Also, you might want to take a look at this: https://github.com/pyenv/pyenv.
