### ISSUE TITLE
Upload error for large files (Warning: Request Entity Too Large (413))

### ISSUE THREAD

**Issue by khabatv** [galaxyproject/galaxy#12651]
used to to be possible to upload the data in the galaxy (https://usegalaxy.eu/) without any problem. but now it gives an error about the size.
this is the case for the files bigger than 1gb size.
Warning: Request Entity Too Large (413)**Describe the bug**

Galaxy Version:
https://usegalaxy.eu/ at 06.10.2021

**To Reproduce**
1. Go to "Upload Data"
2. Click on ' choose a local file and select a file larger than 1gb'
3. Scroll down to 'Start'

**Expected behavior**
uploading the data normally

**Screenshots**
![image](https://user-images.githubusercontent.com/61308485/136148939-7ffce3d5-bef9-41eb-a8f7-508b049116ce.png)
itional context**

**Comment by hexylena** [comment]
@gmauro, in case you missed it

**Comment by gmauro** [comment]
Thank @hexylena 
@khabatv Uploads on website are limited to maximum 1GB file size. For larger files, you can use our ftp service. 
All the detail to use the service at https://galaxyproject.eu/ftp/

**Comment by hexylena** [comment]
we should reopen as a galaxy issue, if the FTP server is configured, it should give the additional hint of "try ftp" and link to that, like we do in other places.

**Comment by mvdbeek** [comment]
FWIW I'm working on overhauling the chunked uploader so it will support resume and various backend solutions via https://tus.io/. But that'll probably only be in the 22.01 release.

**Comment by hexylena** [comment]
I saw that mentioned! It'd be great, but I think the chunked uploader had issues unrelated to its implementation for us on EU and similar solutions I'm not sure will fix that. (Namely chunked content was buffered once by nginx to disk, once by uwsgi, and then finally reassembled into a file, which was hard on our FS)

**Comment by hexylena** [comment]
Ah that's very encouraging to hear! `tusd` sounds promising
