### ISSUE TITLE
Standard library `imp` module is scheduled for removal in Python 3.12

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#12658]
**Describe the bug**
Importing `imp` in Python 3.10 generates the following warning:

```
DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
```

Affected files:
`lib/galaxy/datatypes/registry.py`
`lib/galaxy/util/path/__init__.py`
`lib/galaxy/webapps/galaxy/api/webhooks.py`
`lib/galaxy/webapps/galaxy/controllers/admin.py`

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: dev
Commit: 1a0a8858a2b0fc46c107412b29d59fccc430dc23

**To Reproduce**
1. `ack --type=python 'import imp$'`

**Comment by ic4f** [comment]
Relevant at least as early as Python 3.8.11

**Comment by nsoranzo** [comment]
The warning was there also in Python 3.6, but it has been changed in Python 3.10 to announce the removal in 3.12.
