### ISSUE TITLE
job_resource_params_conf.xml no longer functional with new tool UI

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1266]
I have some HPC admins who really want this feature back. The new tool UI fails to display the job resource section as expected.

Reproducing this bug:
1. Clone galaxy
2. Rename the same job_resource_params_conf.xml
3. Uncomment the line in galaxy.ini

**Comment by hexylena** [comment]
I'll add the casperjs test and bisect this later tonight.

**Comment by hexylena** [comment]
Tested:
- 15.03
- 15.05
- dev

I'm not seeing the extra config options anywhere. Even when logged in. Am I doing something wrong? :open_mouth: ping @jmchilton, all you have to do is edit your galaxy.ini and copy the `config/job_resource_params_conf.xml{.sample,}`, right?

**Comment by jmchilton** [comment]
No - it works for me but you need to do more work.
- `cp config/job_resource_params_conf.xml.sample config/job_resource_params_conf.xml`
- Define a named resource groups, including optional defaults in `config/job_conf.xml`.

```
    <resources default="default">
      <group id="default"></group>
      <group id="select">select</group>
      <group id="memoryonly">memory</group>
      <group id="all">processors,memory,time,project</group>
    </resources>
```
- Create or update tool entries to map tools to a resource group in `job_conf.xml`.

```
    <tools>
      <tool id="upload1" destination="local" />
      <tool id="cat1" resources="select" />
      ...
```

**Comment by hexylena** [comment]
Aha.... so it's a documentation problem. I'll update docs and close this. Thanks @jmchilton

**Comment by jmchilton** [comment]
xref 
- http://dev.list.galaxyproject.org/Job-metrics-configuration-td4668660.html
- https://biostar.usegalaxy.org/p/15058/#15545

**Comment by jmchilton** [comment]
Gathered documentation point as one issue in a larger issue Nate and I have been discussing lately. https://github.com/galaxyproject/galaxy/issues/5133
