### ISSUE TITLE
Requested converter: bigwig_to_wig

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/galaxy#12688]
Recently a user requested a tool for performing the conversion from bigwig to wig.

**Comment by ericshaffique** [comment]
under linux check that the folder containing bigWigToWig is in your $PATH

export PATH=${PATH}:/your/path/to/ucsc/bin

bigWigToWig in.bigWig out.wig

or , as bigWigToWig is in your directory , you can just write

./bigWigToWig in.bigWig out.wig

**Comment by ericshaffique** [comment]
chmod +x ./bigWigToWig
and rerun your command.

**Comment by ericshaffique** [comment]
a tool for performing the conversion from bigwig to wig is bwtool which is  is command-line software for UNIX

**Comment by bgruening** [comment]
We have a start here: https://github.com/usegalaxy-eu/temporary-tools/blob/master/test/bwtool.xml

**Comment by gallardoalba** [comment]
> We have a start here: https://github.com/usegalaxy-eu/temporary-tools/blob/master/test/bwtool.xml

It seems that bwtool cannot be used because of license restrictions.
