### ISSUE TITLE
Interactive tool center panel missing entrypoint(s)

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/galaxy#12692]
**Describe the bug**
The Interactive tools "successful run UI" used to begin with a blue message box containing a link to the interactive tool entrypoint. I just updated from 21.05 to 21.09 and the blue message box has now disappeared. This creates a poor user experience as new IT users have no indication of how to access the running tool (through `User` > `Active interactive tools`).

If someone can confirm that this is in fact a bug, I am happy to take a look at it and try to fix it.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09
Commit: 1fcef64f3278bb13b433f928f32db53394306176

**To Reproduce**
1. Run any interactive tool in an IT-configured Galaxy server

**Expected behavior**
I expect to see a link to the running interactive tool (e.g. [usegalaxy.org](https://usegalaxy.org)).

**Screenshots**
This blue message box used to appear above the green `donemessagebox`:

![image](https://user-images.githubusercontent.com/42562517/136864036-84bf5017-b895-4682-b080-f19a3307ce4d.png)

**Additional context**
I tool a look at the html in the browser and it seems that nothing is being rendered in the `toolentrypoints` tag. So the element is still there, it's just empty:

```html
<div>
  <toolentrypoints job-id="e56aaf80e6cc6823""></toolentrypoints>
</div>
```

**Comment by mvdbeek** [comment]
Yep, I think that is a bug.

**Comment by mvdbeek** [comment]
Thanks for the report @neoformit, this is fixed in https://github.com/galaxyproject/galaxy/pull/12814
