### ISSUE TITLE
Importing workflow fails when not logged in

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#12735]
![image](https://user-images.githubusercontent.com/458683/137753370-01d85c23-e0b3-4824-9313-bb9f32a8ae39.png)

I clicked the link and it took me to

![image](https://user-images.githubusercontent.com/458683/137753527-16193c22-7a0a-4d59-9a92-9456fd8f3e10.png)

Expectation

- click link
- get redirected to login form
- login
- get redirected back to "workflow successfully imported"

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/13188 and https://github.com/galaxyproject/galaxy/pull/13274 should cover this.
