### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dataset'

### ISSUE THREAD

**Issue by quacksawbones** [galaxyproject/galaxy#12749]
I was using a Python wrapper script to call one of the in built Galaxy scripts ($GALAXYDIR/scripts/api/library_upload_dir.py) to load/syncronise a number of data folders between our HPC cluster and our Galaxy instance. Unfortunately, after the script executed (and failed silently by the looks), I tried to navigate to an existing data library (that was one that was being synched), and I received the error "Uncaught exception in exposed API method", with the data library and all data files within inaccessible. The only way that I could recover the Galaxy instance was to roll back to a previous server snapshot.

When I used a clean Galaxy instance to replicate the error, I found there were entries in the Galaxy database (SQLite for the clean instance) that looked incomplete in the `library_dataset_dataset_association` table. (SQLite database: [galaxy_universe.sqlite.zip](https://github.com/galaxyproject/galaxy/files/7377651/galaxy_universe.sqlite.zip) )

Galaxy Version: 20.01

1. Ensure there is a Galaxy Data Library within a Galaxy instance
2. Follow the instructions for uploading data files using "library_upload_dir.py" (here: https://docs.galaxyproject.org/en/master/admin/useful_scripts.html), *making sure to use a Galaxy Master API as the key*
3. Load the Galaxy instance and navigate to the data library
4. Data library will no longer be available, with the error message "Uncaught exception in exposed API method" displayed.

I have included two parts of the log file that were relevant (see "Logs observed during error" and "Logs of error during data upload" below).

While I understand that what I did is not the intended use of the Master API key (only by reading into this issue AFTER the event), I am wondering if we can get the following:
1. With the exception of rolling back the database/server, is there a way this error can be fixed?
2. Can there be some clarification in the documentation around the Master Galaxy API key
3. Is there a way of handling exceptions like these (though I understand this is a very broad topic)

Thanks folks,

DC

Logs during observed error:
```
10.131.200.83 - - [13/Oct/2021:15:53:56 +1100] "GET /api/libraries?deleted=false HTTP/1.1" 200 - "https://galaxy.meerkat.mcri.edu.au/library/list" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0"
[pid: 3566|app: 0|req: 127902/127902] 10.131.200.83 () {78 vars in 1586 bytes} [Wed Oct 13 15:53:56 2021] GET /api/libraries?deleted=false => generated 3230 bytes in 14 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 3)
galaxy.web.framework.decorators ERROR 2021-10-13 15:53:58,660 [p:3566,w:1,m:0] [uWSGIWorker1Core1] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/folder_contents.py", line 100, in index
    dataset = content_item.library_dataset_dataset_association.dataset
AttributeError: 'NoneType' object has no attribute 'dataset'
```

Logs of error during data upload:
```
galaxy.web.framework.webapp INFO 2021-10-13 15:51:28,620 [p:3566,w:1,m:0] [uWSGIWorker1Core0] Session authenticated using Galaxy master api key
galaxy.web.framework.decorators ERROR 2021-10-13 15:51:28,681 [p:3566,w:1,m:0] [uWSGIWorker1Core0] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/library_contents.py", line 257, in create
    status, output = self._upload_library_dataset(trans, library_id, real_folder_id, **payload)
  File "lib/galaxy/webapps/galaxy/api/library_contents.py", line 344, in _upload_library_dataset
    **kwd)
  File "lib/galaxy/actions/library.py", line 113, in _upload_dataset
    uploaded_datasets = upload_common.get_uploaded_datasets(trans, cntrller, tool_params, dataset_upload_inputs, library_bunch=library_bunch)
  File "lib/galaxy/tools/actions/upload_common.py", line 311, in get_uploaded_datasets
    data = new_upload(trans, cntrller, uploaded_dataset, library_bunch=library_bunch, history=history)
  File "lib/galaxy/tools/actions/upload_common.py", line 292, in new_upload
    upload_target_dataset_instance = __new_library_upload(trans, cntrller, uploaded_dataset, library_bunch, state)
  File "lib/galaxy/tools/actions/upload_common.py", line 250, in __new_library_upload
    trans.app.security_agent.copy_library_permissions(trans, ld, ldda)
  File "lib/galaxy/model/security.py", line 1209, in copy_library_permissions
    self.set_all_library_permissions(trans, target_library_item, permissions)
  File "lib/galaxy/model/security.py", line 944, in set_all_library_permissions
    permissions[self.permitted_actions.DATASET_MANAGE_PERMISSIONS] = [trans.app.security_agent.get_private_user_role(library_item.user)]
  File "lib/galaxy/model/security.py", line 682, in get_private_user_role
    .filter(and_(self.model.UserRoleAssociation.table.c.user_id == user.id,
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/12806
