### ISSUE TITLE
Workflow Step Label Follow Up

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1275]
This issue is for following up on workflow step labeling in the UI started with the merge of #1251.
- [ ] Replace step names with labels when loading workflow and keep insync in the editor. 
- [ ] No reason for asynchronous validation, validate on the fly and don't close the editable text if the label is invalid.
- [ ] James reported landing in a state with duplicated labels on IRC. Proved to be non-trivial to reproduce.

**Comment by martenson** [comment]
dupe of https://github.com/galaxyproject/galaxy/issues/1264
sorry for not pinging you @jmchilton

**Comment by jmchilton** [comment]
No problem, good catch @martenson.
