### ISSUE TITLE
Limits on concurrent jobs for registered users are not working

### ISSUE THREAD

**Issue by gmauro** [galaxyproject/galaxy#12777]
![Screenshot from 2021-10-25 16-53-37](https://user-images.githubusercontent.com/4559911/138719030-f821a830-ad08-47e8-b776-d98792301a6b.png)
We had a case of different users able to submit (and have them running) a number of jobs way more over our currently set limits.
We have a `registered_user_concurrent_jobs` limit set to 500, but for a single user, we had ~15k jobs running.
The user  has simply executed the tool over an input collection.

I added some code into https://github.com/galaxyproject/galaxy/blob/13c19ad891a4974f7987cf2b1b3bd05c90a6ca08/lib/galaxy/jobs/handler.py#L770 to print the value of `count` and I have seen this:
```
Oct 24 06:23:03 sn06.galaxyproject.eu python[284831]: galaxy.jobs.handler INFO 2021-10-24 06:23:03,914 [pN:handler_key_4,p:284831,tN:JobHandlerQueue.monitor_thread] checking user hard limit - user: 34531, count: 12685
Oct 24 06:23:03 sn06.galaxyproject.eu python[284831]: galaxy.jobs.handler INFO 2021-10-24 06:23:03,914 [pN:handler_key_4,p:284831,tN:JobHandlerQueue.monitor_thread] checking user hard limit - user: 34531, job: 33044543, wait
Oct 24 06:23:03 sn06.galaxyproject.eu python[284831]: galaxy.jobs.handler INFO 2021-10-24 06:23:03,914 [pN:handler_key_4,p:284831,tN:JobHandlerQueue.monitor_thread] checking user hard limit - user: 34531, count: 12685
Oct 24 06:23:03 sn06.galaxyproject.eu python[284831]: galaxy.jobs.handler INFO 2021-10-24 06:23:03,915 [pN:handler_key_4,p:284831,tN:JobHandlerQueue.monitor_thread] checking user hard limit - user: 34531, job: 33044544, wait
Oct 24 06:23:06 sn06.galaxyproject.eu python[284831]: galaxy.jobs.handler INFO 2021-10-24 06:23:06,454 [pN:handler_key_4,p:284831,tN:JobHandlerQueue.monitor_thread] checking user hard limit - user: 34531, count: 0
Oct 24 06:23:06 sn06.galaxyproject.eu python[284831]: galaxy.jobs.handler INFO 2021-10-24 06:23:06,586 [pN:handler_key_4,p:284831,tN:JobHandlerQueue.monitor_thread] checking user hard limit - user: 34531, count: 1

```
At certain point, the counter has been reset, and two more jobs went on run (together with the other 12685)

Galaxy Version: 21.05

**Expected behavior**
No more than 500 jobs running per user.

**Comment by davelopez** [comment]
I'm assuming this can now be closed @gmauro. Feel free to reopen if there's still an issue :)
