### ISSUE TITLE
[feature request] allow users to relax the workflow connection restrictions

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#12770]
When connecting workflow nodes in the editor some connections are forbidden:

![image](https://user-images.githubusercontent.com/32272674/138463238-e3b58354-a815-4ad8-a640-4308f3f53bcb.png)

Obviously there should be some restraints on connections but I sometimes needed to override this behaviour. Probably the most common case was after designing a workflow with dataset inputs, to scale up the workflow to use collection inputs instead. Galaxy does not allow you to simply swap the dataset input for a collection input.

In the past, I've downloaded the workflow and used this commit (https://github.com/simonbray/galaxy/commit/036a13139220cdad43c86508c9681950d65d0bbc) on a local Galaxy to force the connection. I was wondering if it might be possible to allow users to temporarily relax workflow connection restrictions (e.g. with an option in the workflow editor)?

**Comment by simonbray** [comment]
This doesn't make sense, instead the bugs which are causing these problems should be resolved (e.g. #12825), so I will close.

**Comment by mvdbeek** [comment]
We could consider revisiting this once we have a good way to report eventual errors that could result from this, but I agree we should fix https://github.com/galaxyproject/galaxy/issues/12825 in this case.
