### ISSUE TITLE
Collection elements linked to wrong dataset details until their jobs are finished

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#12804]
On .org but seemingly not .eu when you click on the details (i) icon of any queued or running job in a collection, the linked to dataset details page is wrong and can contain the details of seemingly random jobs/datasets (not restricted to those from your account).

Once the job finishes, i.e., the collection element turns green everything's fine, but not before.

**To Reproduce**
1. Run any tool that creates a collection
2. Go inside the collection and click any elements i icon before the element turns green

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/12805
