### ISSUE TITLE
Batch jobs triggered by "parameter collections" not correctly carried through in workflow editor

### ISSUE THREAD

**Issue by jancrichter** [galaxyproject/galaxy#12825]
**Describe the bug**
When a collection is used as file input for a tool this triggers all downstream jobs to be correctly displayed as outputting collections due to running in batch mode until tis is interrupted by a tool that consumes collections or data inputs with multiple="true".

While using "parse parameter value" or other expression tools on collections of files will produce a "collection of parameters" in the workflow editor, this will always end at the next tool, as if the tool was doing a single run with all values coming from the "parameter collection". In truth downstream tools will continue to schedule as batch jobs correctly, however their outputs cannot be connected to collection inputs as the editor does not recognize them as such.

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.eu

**To Reproduce**
I have created a small example workflow "param collection" and invoked it once to create an exmaple history on my user account (jancrichter) on usegalaxy.eu.

**Screenshots**
![image](https://user-images.githubusercontent.com/40425803/139669041-91b274a4-66d5-4559-a6fb-544080dc1718.png)

Best regards,
Jan

**Comment by mvdbeek** [comment]
@guerler could you also take a look at this one please ?

**Comment by dannon** [comment]
Test to see if this works when save/reloading the editor first (note from meeting)
