### ISSUE TITLE
Text overflows on workflow invocation page

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#12857]
Current on ORG -- longer titles for a workflow overflows involving underscores onto the associated history on the workflow invocation page. Likely not encountered very often, but it's a minor bug.

**To Reproduce**
1. Go to workflow invocation
2. View invocation for workflow with long name connected by underscores

**Expected behavior**
Text should wrap

**Screenshots**
<img width="445" alt="Screen Shot 2021-11-04 at 1 22 43 PM" src="https://user-images.githubusercontent.com/40246333/140414883-c8d60697-1ac0-482b-8cc4-00a619822bf5.png">

**Comment by dannon** [comment]
Was this on a pretty reasonable sized window?  If we have to we can swap the styling for those cells to `break-all`.

**Comment by astrovsky01** [comment]
Full screen on a 15-inch monitor, so yeah

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/13193
