### ISSUE TITLE
Indexing breaks upon deleting elements from History

### ISSUE THREAD

**Issue by tabassum-tasnia** [galaxyproject/galaxy#12866]
When one or more elements are removed from the History, the indexing breaks revealing there were elements that are removed even after deleting them from the disk. That creates an unpleasant UI after completing the history.
![Indrex breaks](https://user-images.githubusercontent.com/93257971/140615413-64d2b70b-2165-4afa-b066-c4f9947053a4.JPG)

How to reproduce the Index error: 
1. Create a new history 
2. Upload data 
3. Use a tool on the data and create an output and It will appear with the index number "1"
4. Remove the initial output
5. Use the tool again on the data and create an output. It will create the index number "2"

The indexing will be much more better if it were to appear as the number "1" instead of "2" after removing the initial output.

**Comment by bgruening** [comment]
@tabassum-tasnia even if you remove your datasets, the metadata will keep stored. This enables reproducibility. You can for example go back to deleted datasets, rerun this step and "restore" the data. This also explains why the indexing is like you see it. Removing datasets will not change the numbering.

I hope that explains what you are seeing :)
