### ISSUE TITLE
Error Uploading Data

### ISSUE THREAD

**Issue by oluchi-osuagwu** [galaxyproject/galaxy#12864]
<img width="951" alt="2021-11-06 (2)" src="https://user-images.githubusercontent.com/81054868/140601089-a92c345f-13de-4f13-a763-0450e73ac416.png">

I had an error output while trying to upload data from different sources using the "choose remote files" upload option.
I chose a data from COVID-19 FASTQ, PDB, SARS-CoV-2 result files and Encyclopedia of DNA Elements (ENCODE), when I clicked start, they ran successfully  but then showed error on my history panel. But when I uploaded several data from one source, and clicked start, it ran successfully and was successfully uploaded on my history panel.

**Comment by OlegZharkov** [comment]
Thanks a lot for reporting @Enchanteur14. Can you share the error message please?

**Comment by Enchanteur14** [comment]
![Galaxy](https://user-images.githubusercontent.com/81054868/141011658-4b07dd0e-6f93-4463-b15f-93ca6b6a7197.jpeg)


Here's a phone screenshot of the error... My laptop is unable to screenshot at this moment, I'm working on rectifying the issue

**Comment by mvdbeek** [comment]
There's not much we can do, that is a problem with the upstream server.
