### ISSUE TITLE
should we lint empty contents of <param><option>?

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#12865]
Consider the linting fail below:

Applying linter inputs... FAIL
.. ERROR: Select parameter [network_type] has multiple options with the same text content

```
            <param name="network_type" type="select" display="radio">
                <option value="signed"/>
                <option value="unsigned" selected="true"/>
            </param>
```

The above code renders and works fine in Galaxy, screenshot below:

![Galaxy](https://user-images.githubusercontent.com/1814954/140604039-e32af125-365f-4e94-be7a-58ceae969691.png)

Assigning @bernt-matthias here, since he asked for it.

**Comment by bgruening** [comment]
I would actually argue that is ok as it isk

**Comment by martenson** [comment]
I don't have a strong opinion on the linting itself but tweaking the error message could go a long way. Maybe <option>s without text content could have their own lint and message.
