### ISSUE TITLE
[form parameter] text, password: "_fieldText"

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#12871]
This is an issue for tracking/assigning conversion of the backbone form input (found here:  https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Form/Elements/parameters.js) into a vue component.

For more details see https://github.com/galaxyproject/galaxy/issues/11076

**Comment by dannon** [comment]
@neoformit is going to take a stab at this one (will update assignment when org invite propagates)

**Comment by neoformit** [comment]
Thanks @dannon

**Comment by neoformit** [comment]
I don't think `Ui.Input` or `Ui.NullableText` can be removed from `ui-misc.js` yet as other components depend on them:
- `parameters.js` : `_fieldSelect`
- `galaxy/client/src/mvc/visualization/chart/views/editor.js`

`parameters.js` will resolve itself when that gets refactored to Vue. I'm guessing we can swap out the dep in `editor.js`?

**Comment by neoformit** [comment]
https://github.com/galaxyproject/galaxy/pull/13375

**Comment by assuntad23** [comment]
Closed with #13375
