### ISSUE TITLE
[form parameter] library_data: "_fieldLibrary"

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#12877]
This is an issue for tracking/assigning conversion of the backbone form input (found here:  https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Form/Elements/parameters.js) into a vue component.

For more details see https://github.com/galaxyproject/galaxy/issues/11076

**Comment by hujambo-dunia** [comment]
Related to: `client/src/mvc/ui/ui-select-library.js`

**Comment by guerler** [comment]
Closed with #16834.
