### ISSUE TITLE
<selects> don't allow clicking on down arrow

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1287]
This is a pretty peculiar error. Apparently my PI prefers clicking the little triangle at the end of select boxes (ignoring the fact that the entire thing is a click target, _sigh_), and found that he cannot use it to open the menu.

Bad (cannot actually open the select menu)
![dataset-select-good](https://cloud.githubusercontent.com/assets/458683/11724652/d6f145b8-9f3a-11e5-955c-a842ba636cb4.png)

Good:
![dataset-select-good2](https://cloud.githubusercontent.com/assets/458683/11724651/d6e42b30-9f3a-11e5-9500-623c554491cb.png)

**Comment by nsoranzo** [comment]
Verified on Linux/Firefox and Linux/Chrome.

**Comment by hexylena** [comment]
Good point @nsoranzo, he's reporting from Windows7/Firefox

**Comment by guerler** [comment]
Thanks everyone.
