### ISSUE TITLE
[form parameter] data_dialog: "_fieldDialog"

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#12882]
This is an issue for tracking/assigning conversion of the backbone form input (found here:  https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Form/Elements/parameters.js) into a vue component.

For more details see https://github.com/galaxyproject/galaxy/issues/11076

**Comment by OlegZharkov** [comment]
Probably you assigned me to the wrong issue, I meant https://github.com/galaxyproject/galaxy/issues/12881 on the call :sweat_smile:. But I guess, that's fine

**Comment by dannon** [comment]
@OlegZharkov Ahh!  I thought you said Dialog.  No worries, un-assigning!

**Comment by assuntad23** [comment]
complete with #16236
