### ISSUE TITLE
Webdav remote file plugin is loading the entire data in memory

### ISSUE THREAD

**Issue by gmauro** [galaxyproject/galaxy#12907]
**Describe the bug**

The webdav remote plugin is using the [WebDAV](https://github.com/PyFilesystem/webdavfs) driver of PyFileSystem2.
That driver loads  the entire data in memory when constructing the WebDAVFile instance
https://github.com/PyFilesystem/webdavfs/blob/master/webdavfs/webdavfs.py#L61

If your worker node doesn't have enough memory to host the data, the job will be terminated by an OOM event

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.05

**To Reproduce**
1. Add a webdav endpoint in your file_source_conf.yml file
2. Download from there a file with a size larger of your worker's memory
3. See error

**Expected behavior**
The plugin should use a reasonable amount of memory

**Additional context**
Relevant Python packages
```
fs.webdavfs==0.4.2
webdavclient3==3.14.5
```

**Comment by mvdbeek** [comment]
I've opened https://github.com/PyFilesystem/webdavfs/issues/32, I don't think there's anything we can do within Galaxy.
