### ISSUE TITLE
AnVIL filesystem plugin upload failing + prospective solution

### ISSUE THREAD

**Issue by luke-c-sargent** [galaxyproject/galaxy#12901]
Hello;

When the new galaxy [export_remote](https://github.com/galaxyproject/galaxy/blob/release_21.09/tools/data_export/export_remote.py) tool attempts an upload, it first checks the path to ensure that directory exists. It does this by using `fs.path.dirname(target_path)` which gets the directory name (e.g., `a/b/c` for file `d` at path `a/b/c/d`) then attempts to determine if this directory exists by using the appropriate plugin's `exists` implementation. Fine for many applications but not for the anvil plugin as it stands, because there can exist a situation where a directory contains a file and a subdirectory with the same name, so there must be a way to differentiate between `a/b/c/` and `a/b/c`.

I suggest that `exists` be switched to [isdir](https://docs.pyfilesystem.org/en/latest/reference/base.html#fs.base.FS.isdir) as it is both more specific and will allow the anvil filesystem plugin to define its own isdir, hiding the details of implementation, and preventing an issue where `exists` expects a directory but finds a file, and vice versa.

if this is acceptable, its a very simple fix from the galaxy perspective as the input to and output of the two functions should be the same.

**Comment by mvdbeek** [comment]
Thanks for the report and the fix.
