### ISSUE TITLE
Feature Request: Trigger history load after workflow submission

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1290]
With the beta workflow submission, things happen more instantaneously and datasets show up periodically. This is a massive improvement IMO, however we experience a loss in the functionality because it requires a manual history refresh. 

By triggering an initial refresh following the workflow, Galaxy would see the greyed out datasets and trigger the normal polling for updates, allowing us to have the same behaviour we previously did.

**Comment by jmchilton** [comment]
The instant after the workflow submits? There will be no gray yet, nothing has been scheduled until the scheduler picks it up and starts processing things - maybe tenths of seconds later.

This isn't worth the effort IMO - the history panel just needs to be fixed to poll with a very light touch to determine if there are new datasets - they can come from more places than just workflow execution - such as tools that produce an unknown number of outputs.
