### ISSUE TITLE
Unify history copy/import functions

### ISSUE THREAD

**Issue by carlfeberhard** [galaxyproject/galaxy#1291]
Right now we use three different urls/methods to duplicate a history. I'd like to reduce that to one: the API create method. This would help add things like: adding persistence of tags and annotations when copying histories between users, etc.

Steps:
- [x] create a control to allow the user to copy/import, set the name, choose all datasets or just non-deleted (as the copy page does now)
- [x] replace the history/copy function in the history options menu
- [x] replace the history/copy function in the 'saved histories' grid
- [x] replace the history/copy function in the 'histories shared with me' grid
- [x] replace the history/copy (multiple) in the 'histories shared with me' grid as well
- [x] replace the history/imp function in history/view
- [x] replace the history/imp function in the published history page
- [x] replace the history/imp function in the Page embedded histories

(Default) naming should stay the same (e.g. 'imported :', 'Copy of ', 'shared by ...').
- [x] test with histories containing large numbers of datasets should be done as well

**Comment by hexylena** [comment]
:+1:
