### ISSUE TITLE
Forcing input into tool from history from a collection chooses wrong hidden file unless file is expanded

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/galaxy#12911]
**Forcing input into tool from history from a collection chooses wrong hidden file unless file is expanded**

https://user-images.githubusercontent.com/20641402/141484788-66def1ac-f17b-431e-ad74-2261ce463eb5.mp4

When choosing a dataset from a collection and forcing it as input to a tool, the wrong input dataset is chosen.

Upon expanding the dataset first, and trying again, then the correct input dataset is chosen.

**Galaxy Version and/or server at which you observed the bug**

Galaxy Version:  usegalaxy.eu/api/version:   

    {"version_major": "21.05", "version_minor": "1.dev0"}

**To Reproduce**
1. Click on a tool
2. Expand a collection in your history
3. Drag the desired dataset into the input data field of the tool
4. Observe the wrong hidden input is loaded
5. Expand the desired dataset by click on its name
3. Drag the desired dataset into the input data field of the tool
4. Observe that the right hidden input is loaded

**Expected behavior*

That the right hidden input is loaded without having to expand the name first

**Comment by simonbray** [comment]
Same as #10671 I think?

**Comment by mtekman** [comment]
Ah nice, I did look for existing issues but I must have missed this -- thanks for merging these issues ;-)

**Comment by mvdbeek** [comment]
Thanks for the report, should be fixed in https://github.com/galaxyproject/galaxy/pull/13290

**Comment by simonbray** [comment]
Nice, thanks for the fix!
