### ISSUE TITLE
value_in_data_table / value_not_in_data_table validator doesn't work with select type parameters

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#12928]
**Describe the bug**
The `value_in_data_table` parameter offers to validate either text or select type parameters from the contents of a tool data table. It however, fails to work as advertised for parameters of type select. The failure modes observed are (1) allowing all inputs (for the case of `multiple="true"` and `value_not_in_data_table` and (2) "flickering" the Execute button but not displaying the relevant message about a validation problem.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version 22.01 dev0
Commit: 88a69285e840fc1e5865d3597e5a1eb709144a9b

**To Reproduce**
1. Run the tool below (in Additional context) with associated data table specification.
2. Try various combinations of `value_not_in_data_table` and `value_in_data_table`.
3. Observe failure

**Expected behavior**
The text input parameter shows an example of what is expected - allow valid values, block and warn on invalid.

**Screenshots**

**Additional context**

```xml
<tool id="test1" name="test_validate" version="0.1">
    <command><![CDATA[
        echo '$input1' > '$output1'
    ]]></command>
    <inputs>
        <param name="seen" type="select" label="Contents">
            <options from_data_table="primer_scheme_bedfiles">
                <column name="value" index="0" />
            </options>
        </param>
        <param name="input1" type="select" label="Input">
            <option value="SARS-CoV-2-ARTICv1" selected="true">SARS-CoV-2 ARTIC v1</option>
            <option value="SARS-CoV-2-ARTICv2" selected="true">SARS-CoV-2 ARTIC v2</option>
            <option value="SARS-CoV-2-ARTICv3" selected="true">SARS-CoV-2 ARTIC v3</option>
            <option value="SARS-CoV-2-ARTICv4" selected="true">SARS-CoV-2 ARTIC v4</option>
            <option value="VarSkip-V1a" selected="true">NEB VarSkip-V1a</option>
            <option value="Midnight-v1" selected="true">RAPID/Midnight v1</option>
            <validator type="value_in_data_table" metadata_column="0" message="MESSAGE" table_name="primer_scheme_bedfiles" />
        </param>

        <param name="input2" type="text" label="Input2">
            <validator type="value_not_in_data_table" metadata_column="0" message="MESSAGE" table_name="primer_scheme_bedfiles" />
        </param>
    </inputs>
    <outputs>
        <data format="txt" name='output1' />
    </outputs>
</tool>
```

```xml
<tables>
    <!-- Locations of primer scheme BED files -->
    <table name="primer_scheme_bedfiles" comment_char="#" allow_duplicate_entries="False">
        <columns>value, description, path</columns>
        <file path="tool-data/primer_scheme_bedfiles.loc" />
    </table>
</tables>
```

**Comment by bernt-matthias** [comment]
I will have a look. Note that the xsd  only states: For text inputs the following validators are useful...

**Comment by bernt-matthias** [comment]
For your use case a filter would be even better. I'm thinking of something like

- dynamically define options with `from_file`
- filter by entries in data table (which needs to be implemented...

**Comment by bernt-matthias** [comment]
Python part fixed in https://github.com/galaxyproject/galaxy/pull/12936 .. flickering issue seemed to be solved by a new checkout https://gitter.im/galaxy-iuc/iuc?at=61966d63c2cc0e5343b80f7a
