### ISSUE TITLE
OIDC login failure with Azure Active directory

### ISSUE THREAD

**Issue by IslamHeggy** [galaxyproject/galaxy#12955]
**Describe the bug**

I provisioned a  Galaxy fresh installation for my company using the Ansible script provided by the Galaxy team. The installation using Ansible had some simple problems and tweaks that I will mention in the Ansible repo but in the end everything was great. 

The problem here is that I wanted to connect with azure active directory to my Galaxy installation and here I used the OIDC protocol supported by Galaxy. First of all, I installed  Galaxy version 21.01 and configured the OIDC and everything worked well. 

I wanted to install the latest release of Galaxy which is (21.09) for my customer and then the Azure active directory part is not working.

After some debugging, I found that Galaxy is throwing exceptions due to pyjwt library problem. I checked the library and found that Galaxy (21.01) is using pyjwt=1.7.1 and the Galaxy (21.09) is using pyjwt==2.1.0 which is causing the problem. I removed pyjwt==2.1.0 and installed 1.7.1 and it worked pretty well after that. I also tried installing different pyjwt versions such as 2.3.0 with no luck at all and the same error occurred. So the current fix for this is to use the 1.7.1 library. 

We need to find a permanent fix for this, Whether find and fix the current problem or define pyjwt version as 1.7.1 for 21.09 release and feature releases if it doesn't break anything else. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09
Python Version: 3.6.8
Virtual env Setup: True 
OS: CentOS 8 release 8.4.2105

**To Reproduce**
1. Run Ansible playbook to install galaxy and add the release version 21.09
2. Add OIDC integration with Azure active directory and restart the Galaxy server.
3. Try connecting with your Azure credentials. 
4. An error occurred during sign in.

**Expected behavior**
The expected behaviour here is that you can login using your azure active directory credentials.

**Screenshots**

Galaxy Server systemd logs
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11975703/142771394-cbf189ab-ab51-43b2-bdbd-3877744eb415.png"> 

Galaxy UI login Failure
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11975703/142771451-319a5037-aa12-416e-80d8-9937bac5bfc1.png">

**Comment by IslamHeggy** [comment]
After doing some research, it seems that social-oauth-core package have a problem with pyjwt library more than 1.7 

So the temporary solution is to upgrade social-oauth-core package to 4.0.3.


Here is the link of [this](https://github.com/DefectDojo/django-DefectDojo/issues/3878) finding

**Comment by bgruening** [comment]
Thanks @IslamHeggy for the report and the nice find! Are you running 4.0.3 and it works for you?

**Comment by IslamHeggy** [comment]
Yes, I tested the compatibility with 4.0.3 with the pyjwt library 2.X.X and it's working fine. 

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/11975703/143037560-1a145d7c-f8a8-4b39-b0b6-5a89f4246635.png">


I can open a PR with the change for this issue.

**Comment by nsoranzo** [comment]
@IslamHeggy As a guide for your PR, you should change the pin for `social-auth-core` in `pyproject.toml`

**Comment by mvdbeek** [comment]
Thanks for the report and fix @IslamHeggy!
