### ISSUE TITLE
Workflow can't be run with a very generic error message, details are in the actual response

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#12967]
Took me a while to figure out where to look for details of what actually happened

![image](https://user-images.githubusercontent.com/458683/143001660-88bcb0b8-6fec-41f3-affd-9cc458e466ac.png)

(But apparently this workflow has oodles of issues that weren't obvious, like flat out missing tools. Perhaps these error messages could be shown in the run interface as well? Or a call to action of "Go to the workflow editor for more details")

**Comment by mvdbeek** [comment]
I think that's the case now, at least the example of a required input missing prevents submission
