### ISSUE TITLE
Glitched through floor

### ISSUE THREAD

**Issue by sunnyplace1218** [galaxyproject/galaxy#12986]
I fazed through the floor, and landed in void.

In Playground, Kit PvP. 

Galaxy Version: I didn't understand how to check sorry but it happened at 11/25 4:30
Commit: NA Server

I expected to respawn normally on ground

Pretty sure the reason is because I died right after my enderpearl(Kit warper) landed. Not that issue, but might want to add one block beneath
![2021-11-25](https://user-images.githubusercontent.com/95054261/143502398-fbdb3565-dc91-4700-b48b-41e06320cf59.png)
.

**Comment by ic4f** [comment]
Sorry, wrong Galaxy. This repository is for the Galaxy computational research platform (please see README).
