### ISSUE TITLE
Glitched in wall this time

### ISSUE THREAD

**Issue by sunnyplace1218** [galaxyproject/galaxy#12987]
Got stuck in wall, and I see bedrock

Again, same as last time, I don't know version but 11/25 5:00
NA server, Playground, Kit PvP(Warper)

I expected to run away using pearls
![2021-11-25 (2)](https://user-images.githubusercontent.com/95054261/143503197-7456d0e1-1fb0-4f6d-852c-7a7e998cceff.png)
(This is after I used pearl one more time)
![2021-11-25 (3)](https://user-images.githubusercontent.com/95054261/143503258-31019024-baee-477c-bfe5-128ad8b210e0.png)
(F5)
![2021-11-25 (4)](https://user-images.githubusercontent.com/95054261/143503319-758ddd42-0891-4d7a-872b-
233abb0bfd5d.png)
(After couple pearls, I got surrounded by barrier with this situation and got completely stuck)
![2021-11-25 (5)](https://user-images.githubusercontent.com/95054261/143503374-d46773fd-6c82-48d9-b6f7-60f2ab9b5951.png)

So I am losing kill steak meaninglessly with this...

**Comment by ic4f** [comment]
Sorry, wrong Galaxy. This repository is for the Galaxy computational research platform (please see README).
