### ISSUE TITLE
a SAWarning in the 21.09 log

### ISSUE THREAD

**Issue by gmauro** [galaxyproject/galaxy#12981]
Just updated to 21.09, and I have several of this in the log:
`/opt/galaxy/server/lib/galaxy/jobs/handler.py:360: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly`

**Comment by mvdbeek** [comment]
That's nothing to worry about, we'll address these as we move towards sqlalchemy 2.0. @ic4f should we turn off these warnings in stable releases ?

**Comment by ic4f** [comment]
> That's nothing to worry about, we'll address these as we move towards sqlalchemy 2.0. @ic4f should we turn off these warnings in stable releases ?

Oh yes, I've seen this one - we'll get rid of them soon (there's more of the same kind and similar). No harm in turning off this warning on stable releases, I think. I don't know how to do that off the top of my head, but I'll figure it out next week.
