### ISSUE TITLE
Galaxy shutting down itself

### ISSUE THREAD

**Issue by EmmettPeng** [galaxyproject/galaxy#12998]
Hi,

I have encountered a problem that my galaxy always shut down itself, even when there are tasks still running.

The log file is here:

```
Gracefully killing worker 1 (pid: 27647)...
galaxy.app DEBUG 2021-11-28 13:44:14,736 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] Shutting down
galaxy.queue_worker INFO 2021-11-28 13:44:15,340 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] Sending reconfigure_watcher control task.
galaxy.util.monitors DEBUG 2021-11-28 13:44:15,352 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] Joining monitor thread
galaxy.jobs.handler INFO 2021-11-28 13:44:15,352 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] sending stop signal to worker thread
galaxy.util.monitors DEBUG 2021-11-28 13:44:15,353 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] Joining monitor thread
galaxy.jobs.handler INFO 2021-11-28 13:44:15,353 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] job handler queue stopped
galaxy.jobs.runners INFO 2021-11-28 13:44:15,353 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] LocalRunner: Sending stop signal to 4 job worker threads
galaxy.jobs.runners INFO 2021-11-28 13:44:15,353 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] Waiting up to 30 seconds for job worker threads to shutdown...
galaxy.jobs.runners INFO 2021-11-28 13:44:15,357 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] All job worker threads shutdown cleanly
galaxy.jobs.handler INFO 2021-11-28 13:44:15,357 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] sending stop signal to worker thread
galaxy.util.monitors DEBUG 2021-11-28 13:44:15,358 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] Joining monitor thread
galaxy.jobs.handler INFO 2021-11-28 13:44:15,358 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] job handler stop queue stopped
galaxy.app DEBUG 2021-11-28 13:44:15,365 [pN:main.web.1,p:27647,w:1,m:0,tN:uWSGIWorker1Core0] Finished shutting down
```
`

Appreciate any help!

Emmett

**Comment by hexylena** [comment]
Hi @EmmettPeng these logs only cover after the shutdown is initiated, not the portion which might have the *why* was it initiated (if it's due to a config issue for example.)  Could you please include more of your logs? And if it is something like another admin on the system initiated shutdown it would not show in the logs as the galaxy process just gets a kill signal.

**Comment by EmmettPeng** [comment]
@hexylena Hi! Here are some more logs:

`
galaxy@r920:~/galaxy_metabolic/galaxy$ tail -50 nohup.out 
galaxy.jobs.mapper DEBUG 2021-11-29 09:05:30,376 [pN:main.web.1,p:45053,w:1,m:0,tN:JobHandlerQueue.monitor_thread] (303) Mapped job to destination id: local
galaxy.jobs.handler DEBUG 2021-11-29 09:05:30,387 [pN:main.web.1,p:45053,w:1,m:0,tN:JobHandlerQueue.monitor_thread] (303) Dispatching to local runner
galaxy.jobs DEBUG 2021-11-29 09:05:30,414 [pN:main.web.1,p:45053,w:1,m:0,tN:JobHandlerQueue.monitor_thread] (303) Persisting job destination (destination id: local)
galaxy.jobs DEBUG 2021-11-29 09:05:30,420 [pN:main.web.1,p:45053,w:1,m:0,tN:JobHandlerQueue.monitor_thread] (303) Working directory for job is: /data/galaxy/galaxy_metabolic/job_working_dir/000/303
galaxy.jobs.runners DEBUG 2021-11-29 09:05:30,428 [pN:main.web.1,p:45053,w:1,m:0,tN:JobHandlerQueue.monitor_thread] Job [303] queued (39.878 ms)
galaxy.jobs.handler INFO 2021-11-29 09:05:30,439 [pN:main.web.1,p:45053,w:1,m:0,tN:JobHandlerQueue.monitor_thread] (303) Job dispatched
galaxy.jobs DEBUG 2021-11-29 09:05:30,524 [pN:main.web.1,p:45053,w:1,m:0,tN:LocalRunner.work_thread-3] Job wrapper for Job [303] prepared (71.917 ms)
galaxy.jobs.command_factory INFO 2021-11-29 09:05:30,566 [pN:main.web.1,p:45053,w:1,m:0,tN:LocalRunner.work_thread-3] Built script [/data/galaxy/galaxy_metabolic/job_working_dir/000/303/tool_script.sh] for tool command [Rscript /home/galaxy/galaxy_metabolic/galaxy/tools/RMT/full_node_attribute.r --centrality=/data/galaxy/galaxy_metabolic/user_data/datasets/000/dataset_494.dat --modularity=/data/galaxy/galaxy_metabolic/user_data/datasets/000/dataset_495.dat --outputfile=/data/galaxy/galaxy_metabolic/job_working_dir/000/303/outputs/galaxy_dataset_40e9cb5c-abaa-4899-9259-3a224f611f0c.dat --outputform=Gephi --annotation=/data/galaxy/galaxy_metabolic/user_data/datasets/000/dataset_497.dat]
galaxy.jobs.runners DEBUG 2021-11-29 09:05:30,613 [pN:main.web.1,p:45053,w:1,m:0,tN:LocalRunner.work_thread-3] (303) command is: mkdir -p working outputs configs
if [ -d _working ]; then
    rm -rf working/ outputs/ configs/; cp -R _working working; cp -R _outputs outputs; cp -R _configs configs
else
    cp -R working _working; cp -R outputs _outputs; cp -R configs _configs
fi
cd working; /bin/bash /data/galaxy/galaxy_metabolic/job_working_dir/000/303/tool_script.sh > ../outputs/tool_stdout 2> ../outputs/tool_stderr; return_code=$?; cd '/data/galaxy/galaxy_metabolic/job_working_dir/000/303'; 
[ "$GALAXY_VIRTUAL_ENV" = "None" ] && GALAXY_VIRTUAL_ENV="$_GALAXY_VIRTUAL_ENV"; _galaxy_setup_environment True
python "metadata/set.py"; sh -c "exit $return_code"
galaxy.jobs.runners.local DEBUG 2021-11-29 09:05:30,651 [pN:main.web.1,p:45053,w:1,m:0,tN:LocalRunner.work_thread-3] (303) executing job script: /data/galaxy/galaxy_metabolic/job_working_dir/000/303/galaxy_303.sh
172.16.161.95 - - [29/Nov/2021:09:05:34 +0000] "GET /api/histories/1cd8e2f6b131e891/contents?details=9f6636fc58245e7a%2C1692b16061e0ddcc%2Cc0a18d93fe04e8e5%2C5bdd2b702d04bb52%2C4a31abf1f877a79d%2C6df0b7b066ddc4c9%2C61612e311c53402a%2Cea3d97b57366b47f%2Ceff20c5ba6bf6f87%2Cb425b2361a02d64e&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=1970-01-01T00%3A00%3A00.000Z&qv=False&qv=False HTTP/1.1" 200 - "http://172.16.161.231:8111/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
[pid: 45053|app: 0|req: 240/249] 172.16.161.95 () {40 vars in 1404 bytes} [Mon Nov 29 09:05:34 2021] GET /api/histories/1cd8e2f6b131e891/contents?details=9f6636fc58245e7a%2C1692b16061e0ddcc%2Cc0a18d93fe04e8e5%2C5bdd2b702d04bb52%2C4a31abf1f877a79d%2C6df0b7b066ddc4c9%2C61612e311c53402a%2Cea3d97b57366b47f%2Ceff20c5ba6bf6f87%2Cb425b2361a02d64e&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=1970-01-01T00%3A00%3A00.000Z&qv=False&qv=False => generated 2427891 bytes in 600 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 0)
galaxy.jobs.runners.util.process_groups DEBUG 2021-11-29 09:05:36,096 [pN:main.web.1,p:45053,w:1,m:0,tN:LocalRunner.work_thread-3] check_pg(): No process found in process group 48842
galaxy.jobs.runners.local DEBUG 2021-11-29 09:05:36,097 [pN:main.web.1,p:45053,w:1,m:0,tN:LocalRunner.work_thread-3] execution finished: /data/galaxy/galaxy_metabolic/job_working_dir/000/303/galaxy_303.sh
galaxy.jobs DEBUG 2021-11-29 09:05:36,143 [pN:main.web.1,p:45053,w:1,m:0,tN:LocalRunner.work_thread-3] finish(): Moved /data/galaxy/galaxy_metabolic/job_working_dir/000/303/outputs/galaxy_dataset_40e9cb5c-abaa-4899-9259-3a224f611f0c.dat to /data/galaxy/galaxy_metabolic/user_data/datasets/000/dataset_500.dat
galaxy.model.metadata DEBUG 2021-11-29 09:05:36,158 [pN:main.web.1,p:45053,w:1,m:0,tN:LocalRunner.work_thread-3] loading metadata from file for: HistoryDatasetAssociation 508
galaxy.jobs INFO 2021-11-29 09:05:36,220 [pN:main.web.1,p:45053,w:1,m:0,tN:LocalRunner.work_thread-3] Collecting metrics for Job 303 in /data/galaxy/galaxy_metabolic/job_working_dir/000/303
galaxy.jobs DEBUG 2021-11-29 09:05:36,233 [pN:main.web.1,p:45053,w:1,m:0,tN:LocalRunner.work_thread-3] job_wrapper.finish for job 303 executed (119.325 ms)
172.16.161.95 - - [29/Nov/2021:09:05:39 +0000] "GET /api/histories/1cd8e2f6b131e891/contents?details=9f6636fc58245e7a%2C1692b16061e0ddcc%2Cc0a18d93fe04e8e5%2C5bdd2b702d04bb52%2C4a31abf1f877a79d%2C6df0b7b066ddc4c9%2C61612e311c53402a%2Cea3d97b57366b47f%2Ceff20c5ba6bf6f87%2Cb425b2361a02d64e&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=1970-01-01T00%3A00%3A00.000Z&qv=False&qv=False HTTP/1.1" 200 - "http://172.16.161.231:8111/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
[pid: 45053|app: 0|req: 241/250] 172.16.161.95 () {40 vars in 1404 bytes} [Mon Nov 29 09:05:39 2021] GET /api/histories/1cd8e2f6b131e891/contents?details=9f6636fc58245e7a%2C1692b16061e0ddcc%2Cc0a18d93fe04e8e5%2C5bdd2b702d04bb52%2C4a31abf1f877a79d%2C6df0b7b066ddc4c9%2C61612e311c53402a%2Cea3d97b57366b47f%2Ceff20c5ba6bf6f87%2Cb425b2361a02d64e&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=1970-01-01T00%3A00%3A00.000Z&qv=False&qv=False => generated 2427886 bytes in 389 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 0)
172.16.161.95 - - [29/Nov/2021:09:05:39 +0000] "GET /api/histories/1cd8e2f6b131e891?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter HTTP/1.1" 200 - "http://172.16.161.231:8111/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
[pid: 45053|app: 0|req: 242/251] 172.16.161.95 () {40 vars in 908 bytes} [Mon Nov 29 09:05:39 2021] GET /api/histories/1cd8e2f6b131e891?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter => generated 170 bytes in 57 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 0)
172.16.161.95 - - [29/Nov/2021:09:05:39 +0000] "GET /api/users/f2db41e1fa331b3e HTTP/1.1" 200 - "http://172.16.161.231:8111/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
[pid: 45053|app: 0|req: 243/252] 172.16.161.95 () {40 vars in 783 bytes} [Mon Nov 29 09:05:39 2021] GET /api/users/f2db41e1fa331b3e => generated 340 bytes in 44 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 0)
172.16.161.95 - - [29/Nov/2021:09:05:41 +0000] "GET /api/histories/1cd8e2f6b131e891/contents/datasets/47b494785f085395 HTTP/1.1" 200 - "http://172.16.161.231:8111/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
[pid: 45053|app: 0|req: 244/253] 172.16.161.95 () {40 vars in 861 bytes} [Mon Nov 29 09:05:41 2021] GET /api/histories/1cd8e2f6b131e891/contents/datasets/47b494785f085395 => generated 364285 bytes in 79 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 0)
172.16.161.95 - - [29/Nov/2021:09:05:43 +0000] "GET /datasets/47b494785f085395/display?to_ext=tabular HTTP/1.1" 200 49494 "http://172.16.161.231:8111/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36"
[pid: 45053|app: 0|req: 245/254] 172.16.161.95 () {40 vars in 911 bytes} [Mon Nov 29 09:05:43 2021] GET /datasets/47b494785f085395/display?to_ext=tabular => generated 49494 bytes in 27 msecs (HTTP/1.1 200) 4 headers in 196 bytes (1 switches on core 0)
Gracefully killing worker 1 (pid: 45053)...
galaxy.app DEBUG 2021-11-29 11:53:26,460 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] Shutting down
galaxy.queue_worker INFO 2021-11-29 11:53:27,319 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] Sending reconfigure_watcher control task.
galaxy.util.monitors DEBUG 2021-11-29 11:53:27,334 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] Joining monitor thread
galaxy.jobs.handler INFO 2021-11-29 11:53:27,335 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] sending stop signal to worker thread
galaxy.util.monitors DEBUG 2021-11-29 11:53:27,335 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] Joining monitor thread
galaxy.jobs.handler INFO 2021-11-29 11:53:27,335 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] job handler queue stopped
galaxy.jobs.runners INFO 2021-11-29 11:53:27,336 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] LocalRunner: Sending stop signal to 4 job worker threads
galaxy.jobs.runners INFO 2021-11-29 11:53:27,336 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] Waiting up to 30 seconds for job worker threads to shutdown...
galaxy.jobs.runners INFO 2021-11-29 11:53:27,337 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] All job worker threads shutdown cleanly
galaxy.jobs.handler INFO 2021-11-29 11:53:27,337 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] sending stop signal to worker thread
galaxy.util.monitors DEBUG 2021-11-29 11:53:27,338 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] Joining monitor thread
galaxy.jobs.handler INFO 2021-11-29 11:53:27,338 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] job handler stop queue stopped
galaxy.app DEBUG 2021-11-29 11:53:27,347 [pN:main.web.1,p:45053,w:1,m:0,tN:uWSGIWorker1Core0] Finished shutting down
`

See? Everything seems fine before it suddenly shut down itself. And I am pretty sure no other user is messing with the galaxy. I went through some research and I supposed it was caused by some uwsgi configuration error but I know nothing about that.

**Comment by hexylena** [comment]
That is very odd! there's really nothing there indicating some issue. `uwsgi` will kill worker threads if you have `harakiri` set and you get a really slow request? But that should only kill uwsgi's children and restart them, it shouldn't affect the overall process.

**Comment by EmmettPeng** [comment]
The same problem was reported in https://github.com/galaxyproject/galaxy/issues/11163 but clearly no clear solution was given.

**Comment by bgruening** [comment]
@EmmettPeng which Python version are you using? Can you try Python 3.6? How much memory have you available and how many handlers are you running?

**Comment by EmmettPeng** [comment]
@bgruening Default Python under .venv is 3.6.13. And there are actually another galaxy running on the same server and that one works just fine.

**Comment by EmmettPeng** [comment]
Another strange thing that I notice is: when two galaxy platforms are running at the same time, and I open them in the browser. Once I operate with one, i will automatically log out on the other. It's like they are conflicting somehow.

**Comment by EmmettPeng** [comment]
I found a solution: I lowered `threads` value, and set `processes` and `offload-threads` to `1` and it finally stopped killing itself. I'm not sure how it works but things seem fine now.

**Comment by dannon** [comment]
@EmmettPeng Thank you for following up with the solution here, glad it's working for you now!
