### ISSUE TITLE
Replace deprecated recommonmark with MyST parser

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#13005]
**Describe the bug**
Once we update to docutils >=0.17 we will hit https://github.com/readthedocs/recommonmark/issues/220 , which is not going to be fixed because recommonmark is deprecated in favour of [MyST parser](https://myst-parser.readthedocs.io/).

**Comment by hexylena** [comment]
Does that mean we'll be able to write tool help in markdown if it's getting parsed through MyST?

**Comment by nsoranzo** [comment]
> Does that mean we'll be able to write tool help in markdown if it's getting parsed through MyST?

The issue here is for building Galaxy documentation (stuff in `doc/`), I haven't looked at how/if it could be used for tool help.
