### ISSUE TITLE
Bug: galaxy.router.push ?tool_id loads incorrect tool in the UI

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13006]
Noticed by @nomadscientist when the GTN webhook was giving trainees the wrong version of the tool

Steps to reproduce:

1. Open Usegalaxy.eu
2. Open console and run

   ```
   Galaxy.router.push("?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/alevin/alevin/1.3.0+galaxy2")
   ```

Instead 1.5.1+galaxy0 is loaded. Also visible from this link: https://usegalaxy.eu/?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/alevin/alevin/1.3.0+galaxy2

however it is possible to switch to it manually

![image](https://user-images.githubusercontent.com/458683/143928362-75b80e86-f648-4fdf-b350-613c9edba134.png)

maybe @dannon knows what's going wrong here?

**Comment by hexylena** [comment]
Haven't been able to reproduce on .org, just on .EU but there it happens with other tools too. E.g. https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/circos/circos/0.69.8+galaxy2 also loads the latest version instead of the requested one. @bgruening fyi

**Comment by hexylena** [comment]
The `+` is being translated to `%20`. First is the request as sent by the UI, second is mine.

```
$ curl 'https://usegalaxy.eu/api/tools/toolshed.g2.bx.psu.edu/repos/bgruening/alevin/alevin/1.3.0%20galaxy2/build' [SNIP] | jq .id
"toolshed.g2.bx.psu.edu/repos/bgruening/alevin/alevin/1.5.1+galaxy0"
$ curl 'https://usegalaxy.eu/api/tools/toolshed.g2.bx.psu.edu/repos/bgruening/alevin/alevin/1.3.0+galaxy2/build' [SNIP] | jq .id
"toolshed.g2.bx.psu.edu/repos/bgruening/alevin/alevin/1.3.0+galaxy2"
```

**Comment by dannon** [comment]
Reopening to track the followup for direct link nav

**Comment by dannon** [comment]
Reopening because we need to take another look at this with tools with literal spaces in the tool_id, like "Show beginning1", in mind.

**Comment by mvdbeek** [comment]
Since we're tracking that in https://github.com/galaxyproject/galaxy/issues/13346 now I'll close this one.

**Comment by hexylena** [comment]
@gmauro @bgruening is there any chance to backport https://github.com/galaxyproject/galaxy/pull/13130 https://github.com/galaxyproject/galaxy/pull/13204 https://github.com/galaxyproject/galaxy/pull/13347 to 21.09 for Tapas?

@nomadscientist just reported this is still an issue on EU during her Single cell course, and it'll bite us again next week I suspect since we're pushing people to use this feature.

**Comment by nomadscientist** [comment]
Hello - yes it's biting us hard and will absolutely bite us next week with the transcriptomics tutorials. Please help!

**Comment by gmauro** [comment]
@davelopez is giving them a look

**Comment by davelopez** [comment]
Done :+1:

**Comment by hexylena** [comment]
Thanks y'all!!!!

**Comment by nomadscientist** [comment]
Bless your cotton socks!

**Comment by gmauro** [comment]
@nomadscientist the fixes has been deployed. Make a try and let us know.

**Comment by nomadscientist** [comment]
Yes it works yay!
