### ISSUE TITLE
ToolShed can not handle tool profiles that are more recent that the TS version.

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#13008]
It seems that tools with a profile > then the TS version:

* can be uploaded
* but have broken TS metadata
* can not be displayed in the TS (invalid tool)
* can not be installed in recent Galaxy version (equal to the tool profile)

Once the TS is updated, the TS metadata of this tool needs to be recalculated to make it installable in Galaxy.

**Comment by mvdbeek** [comment]
It may just be a question of checking if we're in the tool shed and skipping the profile version check
the exception in question is raised in https://github.com/mvdbeek/galaxy/blob/cbb6379184742c09967eff58914dbf8b37206654/lib/galaxy/tools/__init__.py#L821
