### ISSUE TITLE
Namespace packages and pip/wheel do not play together correctly

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#1301]
For example, doing a `pip install Paste==1.7.5.1` results in paste w/o `__init__.py` and thus it is not importable. Creating a paste wheel with `bdist_wheel` results in a wheel w/o `__init__.py` (and it produces the following message):

```
Skipping installation of build/bdist.linux-x86_64/wheel/paste/__init__.py (namespace package)
```

I am not sure what's going on here since I believe `pip install` is only reported to behave this way (see pypa/pip#3) when using `-e`, but I'm getting this behavior when trying to install the sdist. Unless something is not working correctly with the `.pth` files in this particular case (testtoolshed venv on radegast). I am also not sure how this hasn't affected more people by now.

Also affects `repoze.lru`.

**Comment by natefoo** [comment]
Upon closer inspection, the proper `-nspkg.pth` files are being created. The reason this is a problem on for the Tool Shed on radegast and nowhere else is probably because it is using uwsgi installed from apt instead of in the virtualenv as we do for Galaxy. This can probably be fixed by setting uwsgi's `-H` option, I just need to test that this is true.

**Comment by natefoo** [comment]
Confirmed, this can be fixed with `-H` or one of [its many aliases](http://uwsgi-docs.readthedocs.org/en/latest/Options.html#home). When documentation is written for wheels for 16.01, this should be noted for anyone running using uwsgi from outside the virtualenv.

The change in our ansible stuff is in galaxyproject/usegalaxy-playbook@0db21fc8feab6ff45a5346e307f8d178c7fdeef2

**Comment by hexylena** [comment]
@natefoo is this one done? :) (Closing out 16.01 issues pre-freeze)

**Comment by natefoo** [comment]
Leave it open as it's now a documentation issue that should be completed as part of the release notes for 16.01.

**Comment by natefoo** [comment]
Done in #1589
