### ISSUE TITLE
exporting tool is removing datasets from disc

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#13014]
Run new "export_remote" [tool](https://usegalaxy.eu/root?tool_id=export_remote) on collections is removing data.
Before running this tool the collection looks normal, after running the tool the collection looks like:

![grafik](https://user-images.githubusercontent.com/469983/144407009-46d7f71a-59e3-4f8d-888b-fb030f140545.png)

The actual job is also put on hold and looks like that:

![grafik](https://user-images.githubusercontent.com/469983/144407187-9c1c7cf5-79db-4e43-bf85-a8c4bffed146.png)

**Comment by bgruening** [comment]
This only happens to our knowledge with:

![grafik](https://user-images.githubusercontent.com/469983/144407610-650ee830-b414-496c-a29b-644fb9da67b5.png)

**Comment by mvdbeek** [comment]
That seems highly unlikely, can you describe how to reproduce this ?

**Comment by mvdbeek** [comment]
We debugged this a little bit and noticed that HDAs within HDCAs from imported histories (via sharing, not file/uri based) are not copies of HDAs, so if you delete these you also delete the source HDA (assuming you have the rights to do so ...). In any case that is a bug and we'll fix that. There might be something else going wrong, but if we have that first fix it should be easier to diagnose the next issue.

**Comment by mvdbeek** [comment]
The fix for imported histories is in https://github.com/galaxyproject/galaxy/pull/13021, let's see if there are any new reports ...

**Comment by mvdbeek** [comment]
I think that was fixed with https://github.com/galaxyproject/galaxy/pull/13021, but feel free to re-open if it happens again.
