### ISSUE TITLE
Required pip version isn't recent enough

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13023]
**Describe the bug**
https://github.com/galaxyproject/planemo/issues/1208#issuecomment-984831111

**Galaxy Version and/or server at which you observed the bug**
21.09

**Comment by nsoranzo** [comment]
Also with a recent version of pip, building a `cryptography` wheel shouldn't be needed: https://cryptography.io/en/latest/faq/#why-are-there-no-wheels-for-my-python3-x-version
