### ISSUE TITLE
[Feature Request] allow sorting on last login in admin users page

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13027]
It would be fantastic if the admin/users page could allow sorting on all of the columns, especially last login. We're sunsetting a galaxy and need to know who is still using it before we shut it down.

![image](https://user-images.githubusercontent.com/458683/144578978-66f5c759-6c2e-4e41-adfe-695e9496b692.png)

**Comment by cat-bro** [comment]
I'll have a go at this for paper-cuts day

**Comment by mvdbeek** [comment]
Looks like we've got this done in https://github.com/galaxyproject/galaxy/pull/13209, thanks @cat-bro!
