### ISSUE TITLE
Explicit_singularity needs a cached version

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/galaxy#13031]
Hi, I love the ability for galaxy to run singularity containers. 
As a tool maintainer I prefer setting an explicit container above leaving it blank:
- I can easily test the same container in my tool CI
- I have full control over the tools behaviour
- Fonts. Tools that generate plots need fonts.These are system provided when using conda, but alas, in containers fonts are not necessarily included, so a container needs to be adapted to have the fonts.

Anyway galaxy only seems to be able to cache mulled containers. This is unpleasant because it means galaxy has to pull a container from quay.io every time a tool is run. This is a very heavy burden on quay.io. The container should only be downloaded once.

The good news is that since the mulled caching is already in place it should (:crossed_fingers: ) be relatively straightforward to port this functionality to the explicit_singularity directive.

Edit: (Yes, I am volunteering, no I don't have an ETA yet :wink:)

**Comment by bernt-matthias** [comment]
Indeed. I was working on this a while ago. Here is where I stopped: https://github.com/bernt-matthias/galaxy/tree/topic/explicit-resolve .. should be more or less working (I remember that I even tested this on my instance .. but I can't remember why I did not finish this .. would be so important)

Feel free to continue from there if you like.

**Comment by rhpvorderman** [comment]
@bernt-matthias It is done, thanks for your pointers :slightly_smiling_face:
