### ISSUE TITLE
Galaxy loads oldest tool if multiple with the same id and version  are available

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#13030]
**Describe the bug**

If multiple tools with the same id and version are installed in an instance then Galaxy only loads one of them (which is a good idea).
Unfortunately this seems to be the older version. 

I noticed this before for data managers https://github.com/galaxyproject/galaxy/pull/12255 and also just yesterday on my instance for tools. 

**Galaxy Version and/or server at which you observed the bug**

at least 21.05

**To Reproduce**

Would be cool to have a test. Ideas welcome. 

A manual test might use the latest 2 versions of devteam `xy_plot` which were not bumped. But I'm unsure how to verify that the old version is loaded, because the download tool source button in the Galaxy UI does not work (at least for me on my instance).

**Expected behavior**

Load the newest version if this is possible (file timestamp .. but this might be dangerous). Or we need to forbid unbumped tool versions ...

**Screenshots**

**Additional context**

**Comment by mvdbeek** [comment]
I don't think that's fixable, since I don't think there's a way to tell which version is newer. A TS tool that is not bumped is updated in place via hg update, so that can't happen for TS tools.

**Comment by bernt-matthias** [comment]
OK. Just verified this. Then its fine and I can't recall how this happened for me.
