### ISSUE TITLE
Change "file_path" default in "reports.yml.sample" to "database/objects"

### ISSUE THREAD

**Issue by quacksawbones** [galaxyproject/galaxy#13053]
According to `./galaxy/lib/galaxy/config/sample/galaxy.yml.sample`, the default for `file_path` was changed to `objects` at Galaxy release_20.05.

However, in `./galaxy/lib/galaxy/config/sample/reports.yml.sample`, the default value for `file_path` is still `database/files`.

In the `reports.yml.sample`, can we please change the `file path` default to `database/objects` so it's consistent with `galaxy.yml.sample`? This will be one less thing for users to troubleshoot on a new Galaxy build.

Galaxy Version: 21.05
Commit: 35dda33fa6bd029969a87fafaec4b6bb7654b2a2

Thanks

**Comment by hexylena** [comment]
If you want to open a PR we definitely can, it should be an easy fix!

**Comment by quacksawbones** [comment]
No worries. I'll get to it as soon as I can :)

**Comment by ic4f** [comment]
@quacksawbones if you choose to implement this, you'll need to modify this file: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/reports/config_schema.yml , then run `make config-rebuild` to rebuild sample files, and add those to your PR.

**Comment by quacksawbones** [comment]
(Very first) PR created. Happy to correct things if I've made a mistake...
