### ISSUE TITLE
Rerunning failed jobs from collections hides collection instead of just the dataset

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#13052]
**Describe the bug**
When a job producing a collection element fails, Galaxy unhides the element in error state.
Rerunning the failed job used to hide the collection element again, but in 21.09 it hides the collection itself in addition.

Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09 (usegalaxy.eu)

**Comment by mvdbeek** [comment]
Do you have some more details ? Does the job create a collection, or is it a simple output that is mapped over ?

**Comment by wm75** [comment]
I've observed it with mapped-over output for various tools. Let me see if I can create a reproducible example.

**Comment by wm75** [comment]
Ok, I got https://usegalaxy.eu/u/wolfgang-maier/h/collection-hiding
try running the failed awk job on the Split file collection. This will fail for the second element and rerunning will hide the collection.

**Comment by mvdbeek** [comment]
I re-ran that job multiple times, and I'm not seeing anything odd.
![Screenshot 2022-01-12 at 15 34 41](https://user-images.githubusercontent.com/6804901/149160209-13867276-da30-4ff6-819d-321a9499930c.png)
Am I missing something ?

**Comment by mvdbeek** [comment]
Should be fixed with https://github.com/galaxyproject/galaxy/pull/13157
