### ISSUE TITLE
href missing for help resources 

### ISSUE THREAD

**Issue by mariipia10** [galaxyproject/galaxy#13066]
**Describe the bug**
When opening [usegalaxy.org](https://usegalaxy.org/) URL and clicking on help resources nothing happens.  Upon inspecting the html element, the href is missing

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version:  21.09.1

**To Reproduce**
1. Go to [usegalaxy.org](https://usegalaxy.org/)
2. Try to click/right click and inspect  on help resources 
3. See that it doesn't have an href

**Expected behavior**
Open help forum/GTN (Not sure which is the URL that is missing)

**Screenshots**
![image](https://user-images.githubusercontent.com/92181987/146267281-2b182fd0-fc6f-4b73-9e97-21904a928aae.png)

**Comment by mvdbeek** [comment]
Thanks @mariipia10, which link is that ? I don't see a "help resources". It's possible that was fixed with https://github.com/galaxyproject/galaxy/pull/12198.

**Comment by dannon** [comment]
This link was in the (now old) welcome, and it was javascript that toggled open the help menu at the top.  I fixed the javascript when we moved the welcome to the hub, but we've since decided to just drop that link too.

**Comment by mariipia10** [comment]
Awesome, thanks :)  @mvdbeek  It used to show as a URL but upon clicking nothing happened, just checked again and it isn't shown as such anymore
