### ISSUE TITLE
Multiple popovers  overlapping in interactive tour

### ISSUE THREAD

**Issue by mariipia10** [galaxyproject/galaxy#13079]
When following [this](https://usegalaxy.org/tours/core.galaxy_ui) interactive tutorial, after it uploads the data and wants to show the multiple tools galaxy has this happens

![image](https://user-images.githubusercontent.com/92181987/146279566-34eab123-8734-467c-88a9-3d8a7b6135ab.png)

Can only move forwards with arrow keys as when trying to access the endless popups scrolling down it goes up a bit and doesn't let me click the next button 

![error](https://user-images.githubusercontent.com/92181987/146279830-158e2616-e0f8-4313-a216-d458c882468a.gif)

Not an error but also this popover is duplicated

![image](https://user-images.githubusercontent.com/92181987/146280107-5fe08aa7-6827-41b8-96e8-3c03a04225f9.png)

**Comment by mariipia10** [comment]
@hexylena I'm using [this ](usegalaxy.org) server, Galaxy's version is 21.09.1
I'm running on Windows 10 Pro version 20H2 and I'm using Google Chrome version 96.0.4664.110 (Build oficial) (64 bits)

**Comment by mvdbeek** [comment]
@dannon do we want to add this to the 21.01 milestone ?

**Comment by dannon** [comment]
@mvdbeek I'm conflicted about that; let's add it for now for visibility and if I (or someone else) can fix it easily (might just be something changed targets in the new tool panel?) then let's try to get it in.  If this one doesn't make it, we can bump.

**Comment by dannon** [comment]
@itisAliRH I believe it used to select only the first matching element, and something changed in an underlying dependency.  That's probably the intended path -- we'll never want duplicate tour popups attaching to more than one element at a time.

**Comment by itisAliRH** [comment]
@dannon Yes, this is what we want. Here in https://github.com/dannon/bootstrap-tour/blob/aeb8bb540be9b801b2db9c3d606f10b94089fb60/src/coffee/bootstrap-tour.coffee#L515 , the popover selector option is a jquery selector and it selects all matched ones.

**Comment by itisAliRH** [comment]
@dannon Ok :) There is another package for vue https://www.npmjs.com/package/vue-tour. We can swap to this (which is more up-to-date and has more downloads).

**Comment by dannon** [comment]
@itisAliRH That looks nice!  It's new since I last looked at this :)

Very happy for you to take this one over.
