### ISSUE TITLE
Prefixing the galaxy url inactivate the "info" link of history datasets (release_21.09)

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/galaxy#13089]
**Describe the bug**
The bug appears when you try to serve galaxy under a prefix (say `/galaxy`) with the `release_21.09`.
Then, the info button in history datasets points to url in the form of http://34.65.235.106/galaxy/datasets/a799d38679e985db/details, which not triggers info display in the central frame of the Galaxy interface anymore. Nothing happens, except is you ask for url open in a new tab or window.
In contrast, without prefixing the galaxy url, this works as before (for instance with `release_21.05`).

<img width="600" alt="prefixed_info_bug" src="https://user-images.githubusercontent.com/11705625/146674935-faebbc55-5dd4-478b-add9-f0caab387bf8.png">

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: `{"version_major": "21.09", "version_minor": "1.dev0"}`
Commit: `8e6255f6896fe884b37a789f1f065ad3bfdb029c` 

**To Reproduce**
1. git clone https://github.com/galaxyproject/galaxy -b release_21.09
2. cp config/galaxy.yml.sample config/galaxy.yml
3. edit config/galaxy.ym:

$ diff galaxy.yml galaxy.yml.sample
```
24c24
<   http: 0.0.0.0:80
---
>   http: 127.0.0.1:8080
69c69
<   # module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
---
>   module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
73c73
<   mount: /galaxy=galaxy.webapps.galaxy.buildapp:uwsgi_app()
---
>   #mount: /galaxy=galaxy.webapps.galaxy.buildapp:uwsgi_app()
77c77
<   manage-script-name: true
---
>   manage-script-name: false
1604c1604
<   admin_users: drosofff@gmail.com
---
>   #admin_users: null
```
4. sh run.sh
```
Starting server in PID 32168.
serving on http://127.0.0.1:80
```
5. See error

Create any dataset in history (for instance import from local computer)
and click its info button

**Expected behavior**

Dataset detailed info should be displayed in the central frame. It's not

**Additional context**
I originally found the bug using the galaxykickstart ansible playbook to deploy galaxy, but have seen later on that the bug is there with a simple "sh run.sh" deployment.

**Comment by bgruening** [comment]
Fixed in #13092
