### ISSUE TITLE
resuming a dataset collection job does not work

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#1309]
I have one job that crashed and it was consuming a dataset collection. If I choose to resume the job I get the following error in my paste.log.

```
sqlalchemy.pool.QueuePool ERROR 2015-12-14 00:16:08,138 Error closing cursor
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/eggs/SQLAlchemy-1.0.8-py2.7-linux-x86_64-ucs2.egg/sqlalchemy/engine/base.py", line 1226, in _safe_close_cursor
    cursor.close()
InternalError: current transaction is aborted, commands ignored until end of transaction block
```

The user sees the following:
![datasetc](https://cloud.githubusercontent.com/assets/469983/11770184/768f09ce-a1f8-11e5-98d4-037d76adfd8f.png)

**Comment by jmchilton** [comment]
Need more information - lots of ways to supply collections to a tool and they all take very different paths through the code. Is this a:
- Implicit reduction (passing a collection to a `multiple="true"` data param).
- Explicit reduction (passing a collection to a data_collection param).
- Mapping over a data param.
- Mapping over a data collection param. (e.g. passing a list:paired to a paired parameter).
