### ISSUE TITLE
Detecting metadata can result in: OSError: telling position disabled by next() call

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/galaxy#13090]
**Describe the bug**
Uploading tabular files can result in the following stack trace:

```
galaxy.model.store.discover ERROR 2021-12-19 15:31:49,618 [pN:job_handler_0,p:8,tN:KubernetesRunner.work_thread-3] Exception occured while setting metdata
--
Sun, Dec 19 2021 9:01:49 pm | Traceback (most recent call last):
Sun, Dec 19 2021 9:01:49 pm | File "/galaxy/server/lib/galaxy/model/store/discover.py", line 203, in set_datasets_metadata
Sun, Dec 19 2021 9:01:49 pm | primary_data.set_meta()
Sun, Dec 19 2021 9:01:49 pm | File "/galaxy/server/lib/galaxy/model/__init__.py", line 3736, in set_meta
Sun, Dec 19 2021 9:01:49 pm | return self.datatype.set_meta(self, **kwd)
Sun, Dec 19 2021 9:01:49 pm | File "/galaxy/server/lib/galaxy/datatypes/interval.py", line 412, in set_meta
Sun, Dec 19 2021 9:01:49 pm | Tabular.set_meta(self, dataset, overwrite=overwrite, skip=i)
Sun, Dec 19 2021 9:01:49 pm | File "/galaxy/server/lib/galaxy/datatypes/tabular.py", line 404, in set_meta
Sun, Dec 19 2021 9:01:49 pm | if dataset_fh.tell() != dataset.get_size():
Sun, Dec 19 2021 9:01:49 pm | OSError: telling position disabled by next() call
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: Latest dev branch ({"version_major": "22.01", "version_minor": "dev0"})

**To Reproduce**
1. Upload the following Galaxy 101 training file: https://zenodo.org/record/4104428/files/UCSC-hg38-chr22-dbSNP153-Whole-Gene-SNPs.bed
2. Metadata detection fails and generates stack trace above.

**Additional context**
Bug appears to be a side-effect of this PR: https://github.com/galaxyproject/galaxy/pull/12942
Cause and description: https://stackoverflow.com/questions/49785865/meaning-of-oserror-telling-position-disabled-by-next-call-error

**Comment by nuwang** [comment]
@mvdbeek Any thoughts on this?

**Comment by mvdbeek** [comment]
Sorry, missed that one.
