### ISSUE TITLE
Clicking tool help icon on dataset triggers center panel refresh

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#13091]
**Describe the bug**
A click on any dataset's `?` icon (which expands the tool help) unhelpfully triggers a reload of the center panel taking you back to the server's landing page.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09 (.eu and .org)

**Comment by bernt-matthias** [comment]
Seems solved https://github.com/galaxyproject/galaxy/pull/13093
