### ISSUE TITLE
Select all checked in Chose remote file with no entries

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#13105]
In `Chose remote files` when opening any sources that have no entries, `Check to select all datasets` is checked and can not be clear and when clicking on the `Back` button, the `Ok` button will be enabled and the source directory is green.

Galaxy Version: `21.09.1.dev0`
Commit: `c1c82bbf11a0fdc9d52f0a8a0bf7bb1177c636f8`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `Upload Data`
2. Click on `Chose remote files`
3. Open any source that have no entries (for me it was FTP directory)
4. See checkbox is checked and can not be clear
5. Click on `Back`
6. See `Ok` button is enabled and directory opened is green

**Expected behaviour**
`Check to select all datasets` is not checked when no entries and the parent directory is not green when there are no files selected.

**Screenshots**
![bug](https://user-images.githubusercontent.com/8046843/147408073-3be3c464-5319-41f3-b324-daf94f42c949.gif)

**Comment by dannon** [comment]
Fixed in #13107
