### ISSUE TITLE
Closing release notes overlay leaves error in log

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13115]
**Describe the bug**
If you open the release notes, then close it you'll see the following error in the console logs:
```
VM18124:5 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at removeOverlay (eval at globalEval (jquery.js?49ab:1), <anonymous>:5:45)
    at HTMLDocument.eval (eval at globalEval (jquery.js?49ab:1), <anonymous>:185:9)
removeOverlay @ VM18124:5
eval @ VM18124:185
```

**Galaxy Version and/or server at which you observed the bug**
21.09 and dev, can reproduce on .org

**To Reproduce**
1. Open console
2. Click Bell Icon
3. Hit Escape

**Comment by dannon** [comment]
Reproduced this and what I'm seeing is that it's a consequence of us loading multiple webhooks, which each bind their own escape key functionality, in the global namespace.  Will throw a fix in #13116
