### ISSUE TITLE
Toolshed not supporting profile 21.09

### ISSUE THREAD

**Issue by jj-umn** [galaxyproject/galaxy#13119]
**Describe the bug**
toolshed complaining about profile 21.09
https://toolshed.g2.bx.psu.edu/view/ximgchess/hexrd/baba452d0613 tools have profile="21.09" to pick up Npz and hexrd datatypes.
hexrd versions 0.8.12+galaxy0 and 0.8.12+galaxy1 do not appear as valid tools.

An attempt to reset metadata:
```
Metadata may have been defined for some items in revision 'baba452d0613'. Correct the following problems if necessary and reset metadata.
hexrd_find_orientations.xml - The tool hexrd_find_orientations targets version 21.09 of Galaxy, you should upgrade Galaxy to ensure proper functioning of this tool.
hexrd_fit_grains.xml - The tool hexrd_fit_grains targets version 21.09 of Galaxy, you should upgrade Galaxy to ensure proper functioning of this tool.
hexrd_fit_grains.xml - The tool hexrd_fit_grains targets version 21.09 of Galaxy, you should upgrade Galaxy to ensure proper functioning of this tool.
hexrd_find_orientations.xml - The tool hexrd_find_orientations targets version 21.09 of Galaxy, you should upgrade Galaxy to ensure proper functioning of this tool.
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09 and 22.01 (dev)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
https://toolshed.g2.bx.psu.edu/api/repositories/get_ordered_installable_revisions?name=hexrd&owner=ximgchess 
does not return: baba452d0613

**Expected behavior**
Galaxy severs at version 21.09 or above should be able to install tools with profile="21.09"

**Screenshots**

**Additional context**

**Comment by mvdbeek** [comment]
Ah, we do have a fix for that, but forgot to roll it out ...

**Comment by mvdbeek** [comment]
Alright, the tool shed is updated (and should allow uploading newer profile versions even if we don't keep it updated) and I've reset the repository metadata.
