### ISSUE TITLE
List of pairs creator: iterate

### ISSUE THREAD

**Issue by carlfeberhard** [galaxyproject/galaxy#1312]
- [ ] https://trello.com/c/lLk9ICvM/1734-ui-dataset-collections-list-of-pairs-iteration-3
- [ ] Per @nitesh1989: the 'Choose filters' link doesn't express that more options are available to a (new) user when it's clicked. This might be helped by using a dropdown instead of a link. It might also help to have a link within the potential, initial error message that opens that dialog/dropdown using language matching the link below it.
- [ ] clear the TODOs
- [ ] simplify

**Comment by jmchilton** [comment]
Lists of pairs get so much attention - I feel like there are a bunch of applications that could benefit from a list of lists creator :wink: :innocent: :runner:.

**Comment by carlfeberhard** [comment]
Why is that little man running to the two giant wheels of parmesan? Is it because his frisbee got caught on one?

Fair point. I'll add it to the list.

**Comment by assuntad23** [comment]
I turned Choose Filters into a dropdown in #10240

**Comment by mvdbeek** [comment]
Happy to close it, this issue is quite old, and clear the TODOs and simplify is ... well :).
