### ISSUE TITLE
Viewing dataset Details with proxy prefix on 21.09 doubles the prefix

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#13133]
**Describe the bug**
When running Galaxy with a proxy prefix, clicking on the Details icon for a dataset duplicates the proxy prefix:

https://user-images.githubusercontent.com/338642/148569373-be9fdc8f-88b2-4e90-aa3f-ec7a7d4b057b.mp4

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09

**To Reproduce**
1. Launch an instance of Galaxy on AnVIL
2. Upload a dataset
3. Click Details button on the dataset
4. See nothing

**Expected behavior**
See dataset details.

**Additional context**
It appears the endpoint changed between 21.05 and 21.09 because a deployment of 21.05 with a proxy prefix works.

**Comment by mvdbeek** [comment]
@afgane can you confirm that's a duplicate of #13089 ? Sounds like it should be fixed by #13092

**Comment by mvdbeek** [comment]
And there are probably a few commits we should backport from https://github.com/galaxyproject/galaxy/pull/13103/commits

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/13138 contains the additional prefix fixes

**Comment by afgane** [comment]
Thanks Marius. This does look like the same issue but testing AnVIL deployments is a prolonged process so didn't test this yet but I'll close this on the assumption it will work.

**Comment by afgane** [comment]
Got this deployed and the issue has been fixed. Thanks again.
