### ISSUE TITLE
Optionally compress files in remote file export tool

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13149]
We talked about this at the backend WG meeting. This is a usecase driven by VGP.
If should have a select option
 - compress if uncompressed
 - don't change
 - compress everything ?

If could have an option to select the compression format (e.g. Windows users may prefer Zip).

**Comment by mvdbeek** [comment]
@bgruening mentioned that @astrovsky01 is going to work on this. Let me know if that's wrong.

**Comment by dannon** [comment]
This is going to turn into an IUC tool installed via toolshed.
