### ISSUE TITLE
FAILED to start common_startup_functions.sh: line 111: .venv/bin/activate: No such file or directory

### ISSUE THREAD

**Issue by topstarxxx** [galaxyproject/galaxy#13141]
**Describe the bug**
Im running anaconda3 in windows 11，follow instructions: git -> sh run.sh , after installed some packages, it stuck with activate _galaxy_ , error shows:

sh run.sh
Activating virtualenv at .venv
./scripts/common_startup_functions.sh: line 111: .venv/bin/activate: No such file or directory

maybe something incorrect in that file common_startup_functions.sh?

but, conda env list shows _galaxy_ is established 

I activate _galaxy_ manually

then run the "sh run.sh"

still not working.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: release_21.09

**Comment by mvdbeek** [comment]
We're not supporting windows. It looks like you have a .venv folder maybe that is empty ? Try removing that and try again. I don't have high hopes this is going to work though. You might want to give WSL 2 a try.

**Comment by topstarxxx** [comment]
@mvdbeek 
thank a lot for kindly saving my time!
I am a newbee in both computer and data science.
I will try the docker versions.

**Comment by mvdbeek** [comment]
If you have any questions feel free to drop by https://gitter.im/galaxyproject/Lobby or help.galaxyproject.org

**Comment by H1207953831** [comment]
I tried to use the method introduced by chatpgt to solve the problem, and found that I can run the environment, but because I am in China, some of the python packages needed for the environment dependency are not easy to install.
The method suggested by chatgpt is as follows:
cd /path/to/galaxy
python3 -m venv .venv
source .venv/bin/activate
