### ISSUE TITLE
Bug report post-submission message in an odd place + update the troubleshooting link

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#13144]
**Describe the bug**
1. When submitting a bug report from a red dataset (bug icon), the error form comes up as usual, but after clicking on "submit" the “Your error report has been sent” message is embedded into the view, instead of showing up on top. New in 21.09 or I didn't notice it before.
2. The submit "report" button stays highlighted, so doesn't look like the click worked or is fully done (when it is)
3. URL for more troubleshooting help needs to be updated -- still pointing at the hub FAQ, should point to GTN FAQ instead

**Galaxy Version and/or server at which you observed the bug**
**ORG** Galaxy Version/Commit: Galaxy version 21.09.1.dev0, commit c1c82bbf11a0fdc9d52f0a8a0bf7bb1177c636f8
**EU** Galaxy Version/Commit: 21.09 -- not sure where to get the rest there

**To Reproduce**
1. Go to either test history: 
* https://usegalaxy.org/u/jen-galaxyproject/h/test-bug-report-submission 
* https://usegalaxy.eu/u/jenj/h/test-bug-report-submission
2. Click on the bug icon in the red dataset
3. Submit the bug report
4. See problem -- message down in the report + the submit button stays highlighted

**Expected behavior**
The message should be at the top and more obvious. Maybe grey out the rest of the error report, or clear it as before.

**Screenshots**
----
<img width="349" alt="error-report-submit-confirmation-location" src="https://user-images.githubusercontent.com/8999735/148827357-f2fb1c4a-24d6-4bbb-bf80-273c1e8fa049.png">

----

<img width="552" alt="error-report-submit-button-stays-highlighed-after-submit" src="https://user-images.githubusercontent.com/8999735/148830256-5c2042fd-6448-4193-82b4-35844343e7a9.png">

----

**Additional context**
If the goal is to leave the exit/stderr information for the end-user to keep reviewing, that is fine, but confirmation of the submission should be reported at the top of the page view like the other submit functions in the center panel (tool submits, etc). 

Maybe emphasize (gray everything else out) or only include the Troubleshooting section? The link also needs an update -- point it to here instead please: https://training.galaxyproject.org/training-material/faqs/galaxy/#troubleshooting-errors 

Ideally, clicking on that link would "pop-up" the GTN site within Galaxy, not navigate away.

<img width="441" alt="error-report-troubleshooting-section" src="https://user-images.githubusercontent.com/8999735/148827289-121e8c2c-145d-4a77-a661-0a42b1be3391.png">

**Comment by natefoo** [comment]
The URL for troubleshooting [appears to not be configurable](https://github.com/galaxyproject/galaxy/blob/ccfceebcb0ddfb8a4e5599bd7dc6ca5bc3d01190/client/src/components/DatasetInformation/DatasetError.vue#L46).

**Comment by jennaj** [comment]
Oh, so hardcoded. 

I'm OK with it opening a new tab instead of the GTN within Galaxy as a first pass solution. Going to that default GTN FAQ is better than the Hub FAQ.

What is the best branch to make a PR on, Dev? I'd just submit the URL change, not the other things.

Not all servers will have the GTN built-in. Some may have alternative help sites/instructions. So eventually we probably want that to be an admin config param, with the GTN as the default.

**Comment by hexylena** [comment]
> Not all servers will have the GTN built-in.

everything new does unless they explicitly remove the gtn webhook, I'm not sure how common that would be. Agreed it should be configurable!

**Comment by natefoo** [comment]
> What is the best branch to make a PR on, Dev? I'd just submit the URL change, not the other things.

Yes, this is fine, we haven't branched 22.01 yet so it would make it into the next release.
