### ISSUE TITLE
Auto-Pair button for shared library data  (list-of-pairs import) has no effect in Galaxy 21.09

### ISSUE THREAD

**Issue by ulvitalas** [galaxyproject/galaxy#13140]
**Describe the bug**
"Auto-pair" button in this context no longer has an effect and clicking all the samples through one-by-one is required to import a list-of-pairs type of collection into the user history:
![image](https://user-images.githubusercontent.com/46785395/148762293-2505a886-ba35-4638-b566-83f3a47e08f0.png)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Go to 'Shared Data => Data Libraries...'
2. Click on 'Name of a library' known to contain paired end fastq reads.
3. Select the reads you want to import
4. Click on *Export to History => as a Collection => list of Pairs"
3. Insert appropriate extensions  to describe the pairing (e.g. _R1 & _R2 respectively)
4. Click the "Auto-pair" button in the middle
5.  Unlike (in Galaxy 20.09 we recently upgraded from & with the very same shared library dataset) the button has no effect  and the following error message is continuously being displayed:
"Could not automatically create any pairs from the given dataset names. You may want to choose or enter different filters and try auto-pairing again. cancel and reselect new elements."

**Expected behavior**
forward and reverse fastq files to be automatically recognized as pairs and the correct number of pairs to be displayed. 
Instead one has to click all the pairs through manually for the desired result and form of import. No obstacles encountered with the latter approach, just tedious with hundreds of pairs ..

**Screenshots**
![image](https://user-images.githubusercontent.com/46785395/148765513-200822fc-1aa6-46db-87bd-71ab073e1f83.png)

Manual approach:
![image](https://user-images.githubusercontent.com/46785395/148765583-bad772e4-f0ec-4ace-8e45-855e21e4df96.png)

**Additional context**
Previously existing functionality  decoupled from the button?

**Comment by assuntad23** [comment]
I found the issue -- autopairing will work if you use the predefined filters, but not if you type them yourself. I'll get to work on fixing it, but for now @ulvitalas, if you use the _R1/_R2 from the dropdown, it should work fine for you to move forward & make things a little easier. 

Please let me know if it does not.

**Comment by ulvitalas** [comment]
Thank you for finding the cause and fixing the issue. With predefined it
works OK indeed!!!
Our daily routine is handled by a bot script that bypasses it, but I have
brought it up for the sake of our research community, especially the
irregular users. Will let them know about the alternatives.
Where would be the place to add extra pre-definitions, if required?

Cheers,
Ulvi

Kontakt Assunta DeSanto ***@***.***>) kirjutas kuupäeval T,
11. jaanuar 2022 kell 21:24:

**Comment by dannon** [comment]
Should be resolved now with #13166
