### ISSUE TITLE
When tool version is changed in the workflow editor, tool_id is unchanged in downloaded .ga file

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#13153]
**Describe the bug**
If I change the version of a tool used in a workflow and then download the workflow, the tool_id and content_id show the previous tool version.  Only the changeset_revision is updated for the workflow step.

**Galaxy Version and/or server at which you observed the bug**
21.09

**To Reproduce**
1. On Galaxy Europe or Galaxy Australia upload the Galaxy 101 for everyone tutorial
`https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101-everyone/workflows/main_workflow.ga`
2. Edit the workflow and change the version of Scatterplot with ggplot2 from '2.2.1+galaxy1' to '2.2.1+galaxy2'
3. Download the workflow file
4. See that the tool_id and content_id fields for the ggplot2 steps are `toolshed.g2.bx.psu.edu/repos/iuc/ggplot2_point/ggplot2_point/2.2.1+galaxy1`

**Expected behavior**
Tool version changes in tool_id and content_id fields when the version is changed

**Additional context**
It all still works, since the changeset revision is updated when the tool version is updated through the workflow editor, so if the workflow is downloaded and reuploaded the version change is preserved, but having tool_id and content_id showing the previous version in the .ga file is confusing.

**Comment by mvdbeek** [comment]
@guerler can you take a look at this please ?
