### ISSUE TITLE
YAML files don't get displayed in centre pane on viewing

### ISSUE THREAD

**Issue by elichad** [galaxyproject/galaxy#13168]
When clicking "View data" on a txt file, the file contents are displayed in the centre pane. As YAML is a human-readable text format it would make sense (IMO) for YAML files to exhibit the same behaviour. However, for the YAML datatype the file is downloaded rather than displayed when clicking "View data". (Thanks @Jo-stfc for finding this)

Would overriding the `display_data` datatype method to default to `preview=True` work as a fix? Or is a more complex method needed?

**Comment by mvdbeek** [comment]
I think we'd just need to set the mime-type correctly, I'll take a look

**Comment by elichad** [comment]
Thanks for the quick fix! Can this be added to `dev` as well?

**Comment by mvdbeek** [comment]
Of course, but we have to change some things there since we changed the way that mimetypes are being set.

**Comment by elichad** [comment]
Ahh, gotcha.
