### ISSUE TITLE
Tool migration removal broke at least one admin view

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#13161]
**Describe the bug**
Removal of tool migration code (#13099) has caused at least one admin view to break (admin > tools > view tool migration stages). It may be not the only thing affected. Need to fix this + check for any other possible similar cases.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 11.01/dev0
Commit: 320c6a36b582c62b2c24aa584044ae179176cb17 

**To Reproduce**
1. Log in as admin. Then: admin > tools > view tool migration stages. The central pane is blank.

**Expected behavior**
The men option should be removed.

**Screenshots**
![image](https://user-images.githubusercontent.com/6132258/149359229-2402f49a-9c84-4d38-884f-3432216f33ec.png)

**Comment by mvdbeek** [comment]
Doesn't that make sense ? I think we can drop that view if we have removed the tool migration code

**Comment by dannon** [comment]
Yep, just need to cut out that interface; It's an old mako.  So you'd drop the menu option in admin-panel, kill the admin controller endpoint for it, and then drop the mako itself.
