### ISSUE TITLE
Connection issue in the workflow editor (Bowtie)

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#13173]
**Describe the bug**

![image](https://user-images.githubusercontent.com/469983/149664122-52a4e561-e7b4-4a4f-9202-f41c1aab6ee4.png)

I think both tools should be able to be connected. 

Related: https://help.galaxyproject.org/t/bowtie2-output-data-type-not-recognised-in-workflow-designer/7323

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09 on EU and ORG

**Expected behavior**

Both tools should be connectable.

**Comment by mvdbeek** [comment]
Do you have more details about this ? It seems to work fine for on .eu, .org and locally. Any additional steps I have to take ?
I tried with the linked workflow, that also seems to work.
