### ISSUE TITLE
Attempting to save workflows containing certain tools never completes.

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#1317]
Dev is affected. 

Error in console:
`Uncaught TypeError: a is not a function         http://xyz/static/scripts/mvc/citation/citation-model.js`
- Create new workflow
- Add Kraken `toolshed.g2.bx.psu.edu/repos/devteam/kraken/kraken/1.1.0` tool --> Error is logged in console.
- Save workflow --> 'Saving' spins forever

Current work around is to create workflow on working server, export, import in broken.

**Comment by mvdbeek** [comment]
This is somehow linked to the citation handling, for me tools that have citations show this behaviour (and the citation display is also broken in the tool form).

**Comment by mvdbeek** [comment]
Oh, and for me it says this in chrome's javascript console:

```
Uncaught TypeError: a.BibtexParser is not a function
```

**Comment by martenson** [comment]
@mvdbeek 
this should be ~~remedied by~~ ~~caused by~~ related to https://github.com/galaxyproject/galaxy/pull/1261 I think

**Comment by blankenberg** [comment]
I'm still getting the error I listed from citation-model.js, on latest Dev (commit 5bf926bf3ec19933c0ef82e51c919c0595bfc741).

**Comment by martenson** [comment]
@blankenberg yeah, me too

**Comment by gregvonkuster** [comment]
@martenson @blankenberg Mo too!
