### ISSUE TITLE
Numeric input slider does not seem to display fractions

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#13187]
When using the e.g. the `Lofreq filter called variants posteriorly (Galaxy Version 2.1.5+galaxy0)` tool which contains a float input element the slider allows only to switch to either `0` or `1`. Fractions in-between cannot be selected.

ref: #12937

**Galaxy Version and/or server at which you observed the bug**
In dev/22.01.

**Expected behavior**
The slider circle should be in the center allowing the selection of fractions.

**Screenshots**
<img width="632" alt="image" src="https://user-images.githubusercontent.com/2105447/150043148-bdaf91e6-bf57-455d-9caf-6a15ada08c68.png">

**Comment by davelopez** [comment]
I'll try to figure this one out
