### ISSUE TITLE
Saved History list. Include "New" Dataset counts.

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#1318]
Now that datasets are being put into the new state (instead of queued), it would be nice to list their counts on the "Saved History" page, they could be rolled back into the 'queued'/gray box. 

I have a history with >7,000 datasets from running a workflow on a collection, but it looks like the history is almost empty, and that there is a problem with running the workflow, since these 'new' (queued) datasets do not show up. It makes it much more difficult to track progress of the history without having to load it as the current history.

**Comment by jmchilton** [comment]
Sounds like this is a bug, shouldn't these be 'queued' like right away as soon as the job handlers grabs them. Wonder if I am missing something.

**Comment by hexylena** [comment]
![image](https://user-images.githubusercontent.com/458683/62788804-f9941300-bac7-11e9-8389-d56bc19a2cf7.png)
