### ISSUE TITLE
History: is hiding collections functional currently?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13199]
xref #13197 I ended up filtering some collections in my history to allow me to select just what I want, and attempted to hide it, but it doesn't seem to hide. The request completes successfully, but nothing changes. Experienced on EU. I've tested with both beta + old history.

![hiding](https://user-images.githubusercontent.com/458683/150154234-ad819393-5ab8-4983-945c-7ec4957c7b6f.gif)

## Request

![image](https://user-images.githubusercontent.com/458683/150154619-d9593f31-ff65-43d2-a4bd-819ede9b887d.png)

## Response 

and it remains visible

![image](https://user-images.githubusercontent.com/458683/150154684-92116ea3-47d5-46f6-a7d0-dacf0f1e2a61.png)

**Comment by davelopez** [comment]
I will have a look to see if there is something off at the API level

**Comment by davelopez** [comment]
Should be fixed in #13214

**Comment by hexylena** [comment]
Fantastic! Thanks so much @davelopez
