### ISSUE TITLE
"recently used rules" are unsorted, leading me to be unable to select the most recently created rule which I'm trying to edit

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13192]
I think these should probably be sorted by their timestamp?
![image](https://user-images.githubusercontent.com/458683/150118478-a1a7bc12-6cd9-4fbd-b68e-28f6787dcf55.png)

One of them fails to load

![image](https://user-images.githubusercontent.com/458683/150118590-cd7413af-4880-4725-8db7-7738cec9db12.png)

And the rule I recently used to try and build a collection (which failed to build) doesn't seem to be in that list?

![image](https://user-images.githubusercontent.com/458683/150118847-da794423-61d8-4a3e-86ab-b7c23694df7c.png)

**Comment by assuntad23** [comment]
I can take a look at this!

**Comment by assuntad23** [comment]
@hexylena I've got a PR there to sort them, but I'm not yet sure what to do about the other issues you listed.

Do you have the JSON from those rules to send to me? That way I could use it in my tests?  For the one that fails to load, you should be able to capture it, but for the other... I'm at a loss.

**Comment by hexylena** [comment]
@assuntad23 that's fantastic! 

I put a breakpoint on where the error poped up

![image](https://user-images.githubusercontent.com/458683/155109531-09edcc78-76f3-42e6-aee1-8e35234fa5b2.png)

but all of the variables there seem to be undefined. Going up the stack trace

![image](https://user-images.githubusercontent.com/458683/155109896-3dc77bf6-eb6e-438f-8cf1-174db7abf3e6.png)

still undefined there, but that's true even for a handful of old rules that load. I'm going to say this is a non-issue / something weird on my end until someone else re-reports

**Comment by assuntad23** [comment]
Fixed with #13427

Willing to re-open if we see the error issue pop up again.
