### ISSUE TITLE
Beta history: What is a valid history? It has a similar icon to 'save' for many dialogs resulting in confusion

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13198]
![image](https://user-images.githubusercontent.com/458683/150153196-7151c8b7-c35d-4dda-aa6c-1c7615b11a9d.png)

At least for me. If I hover and read the alt-text it's clear (though "Save history" is a bit misleading, we're just "Saving history metadata").

If the check mark is telling us the history is valid somehow (I didn't know we could get invalid?) then it shouldn't be using the component of a button, I think, by being clickable it's a bit misleading maybe?

**Comment by dannon** [comment]
@hexylena There's commentary on this in another issue I added that I will link up, but the short answer is that upon discussion we're looking to dump this whole interface and use the central pane for editing attributes.  The history is too dense, and as long as changes are reactive editing in the central pane offers more options.

**Comment by hexylena** [comment]
That makes sense! And sounds like quite a positive improvement. I look forward to it. (Feel free to close then, unless you want to track that it gets addressed in the new ui)

**Comment by guerler** [comment]
This has been revised, now regular buttons with labels (`Save`, `Cancel`) are shown. Reopen if additions are required.
