### ISSUE TITLE
Beta history: selecting a single item is now more difficult

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13197]
I'm not sure this is intentional? I found the older behaviour easier: enable multi-select, and then select individual / all / none. But now I'm forced into selecting all, and I need to manually de-select if I only want a single item.

![Peek 2022-01-19 15-36](https://user-images.githubusercontent.com/458683/150152203-c5eb0407-bb01-401b-8ecd-04f825089d18.gif)

Also the checkbox looks pre-checked, visually, I get *why* but maybe there's some other way to communicate "multiselect mode" than a pre-checked checkbox or so?

Additionally my normal complaint of small click targets. If you're in this multi-select mode maybe it would be possible to click anywhere on the dataset to select it? Rather than just the box?

**Comment by dannon** [comment]
@hexylena Agreed, multiselect and filtering needs work.  I like the idea of the whole element being a click target, this is good feedback, thanks!

**Comment by mvdbeek** [comment]
> the whole element being a click target,

my 2c is that it used to be convenient to see the peek in multiselect, but that could also be on hover ?

**Comment by davelopez** [comment]
xref https://github.com/galaxyproject/galaxy/pull/13555#issuecomment-1085949818

**Comment by guerler** [comment]
Has been resolved and is being worked on within the context of the bulk operations as referenced.
