### ISSUE TITLE
Beta history: difference pending query for items and empty list/etc is unclear: needs a spinner?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13201]
I've kept the network tab open to check if the request has completed (eu seems to be slow today) and it's unclear if the list is empty, or, if there's datasets but they haven't loaded yet. Maybe a spinner would fix this until the request is resolved?

![image](https://user-images.githubusercontent.com/458683/150156500-098c2a38-8e91-4300-a330-b863957dfe12.png)

**Comment by hexylena** [comment]
Ah this is in the old history, yes, that's what's needed ![image](https://user-images.githubusercontent.com/458683/150165602-6ee05f48-46ab-4ee9-b71b-9fe57f473b21.png)

**Comment by dannon** [comment]
This now indicates a count at the top, which should clarify this.

![image](https://user-images.githubusercontent.com/155398/177002299-97a8ded6-4164-4433-8d4c-77811d3af453.png)
