### ISSUE TITLE
Beta history: dataset previews (within collections) disappear on scrolling

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13200]
The preview for the top dataset disappears and won't return until I close/re-open, I'm guessing it gets lost during scrolling?
![scroll](https://user-images.githubusercontent.com/458683/150155660-c783349c-b55c-46a1-930c-263995bc4faf.gif)

**Comment by guerler** [comment]
Has been resolved in the revised new history, currently in dev.
