### ISSUE TITLE
Unexpected behavior of non optional input parameters in workflows

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#13220]
**Describe the bug**
When you use an input parameter (Simple inputs used for workflow logic) in a workflow, the default is set to "non optional".
But at execution, even is the parameter is not set, the workflow will start.
In this case (sed program) the workflow will run, but the output file won't be modified.

And if your tool uses:
```
                <param name="input" type="text" label="Project identifier">
                        <validator type="empty_field" message="Please choose a project identifier. Should not be empty !" />
                </param>
```
and if you try to link this input to `Simple inputs used for workflow logic`, the workflow will have a failed step.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: usegalaxy.eu and my own galaxy (21-09)

**To Reproduce**
Launch the workflow, and do not set any value for `Set SED program` input.
https://usegalaxy.eu/u/fredbga/w/sed---optional-no---input-param

**Expected behavior**
I would have thought that the workflow woundn't start, because it's missing a non optional input.
So when that step is one of the last step of a time consuming workflow, we discover the missing parameter very late and this is a waste of time :)

**Comment by mvdbeek** [comment]
So the problem is again that we're not discriminating `""` from `null`. I've fixed this for optional selects in https://github.com/galaxyproject/galaxy/pull/12138, but we need to do the same for simple text parameters, or maybe even all parameter types.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/13285 improves this significantly by preventing the submission if no value is set. However a use can click into the text field and not write anything, so there we submit `""` as the value (as opposed to `null` when the value isn't touched). We should probably allow specifying regexes or similar for workflow parameter validation, but that's a bigger effort.

**Comment by mvdbeek** [comment]
We've had to revert https://github.com/galaxyproject/galaxy/pull/13285 since it affects tools with required text tool parameters (that should have been optional, but that was not enforced previously, so we can't change it now). A next iteration could apply this only to text parameters within workflows, or, and that would be much better, not use the text parameter types from basic.py

**Comment by mvdbeek** [comment]
Gave this another try in https://github.com/galaxyproject/galaxy/pull/17048, at least in the context of the simplified workflow run form this should correctly prevent execution of the workflow
