### ISSUE TITLE
Simplified workflow run form doesn't do any validation / merge with new form ?

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13232]
Individual workflow parameters may contain logic to validate values (e.g don't submit a workflow if a required text parameter is null).
The old/advanced workflow run form stores events emitted by validating steps and prevents executing a workflow with invalid parameters.

Instead of adding the same logic that the old form uses we should probably merge the old and simplified forms. The new form could be the base with slots that the advanced form can fill.

**Comment by guerler** [comment]
Thanks for reporting this issue. Both forms use the `FormDisplay` component and are in that sense already merged. Further consolidation of the two might not be beneficial rather we would need to make additions to the API to reject incomplete job submissions.

**Comment by mvdbeek** [comment]
That's working now
