### ISSUE TITLE
Workflow run form validation highlighting broken

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13234]
**Describe the bug**
The advanced workflow run form doesn't highlight validation errors anymore
<img width="1300" alt="Screenshot 2022-01-24 at 18 05 56" src="https://user-images.githubusercontent.com/6804901/150830487-235893c3-86f5-4b7c-9957-67e27ea1ccbf.png">

(And the new one submits, leading to a broken invocation)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: 64d395862e0b9fb391d4e832abd8e63b82777d35 / dev

**To Reproduce**
1. Create a workflow with a required data input
2. Click submit
3. See that nothing happens

**Expected behavior**

We should highlight the step and display in blue (or was it red ?) that something needs to be fixed.
This still works on 21.09

**Comment by davelopez** [comment]
I'll try to debug this one and see if I can find something...

**Comment by davelopez** [comment]
I think this one is defying all I know about Vue reactivity... (which probably is not much :sweat_smile:)

Looks like the validation is there, but something shady is happening with the reactivity of the `error` property...

![Screenshot from 2022-01-25 17-42-12](https://user-images.githubusercontent.com/46503462/151023258-54156798-3424-41e9-a17a-e87f3b624098.png)

As far as I can understand, in the *FormNode* (which is really *FormInputs.vue*) the error prop for the *FormElement* component is correctly bound [here](https://github.com/galaxyproject/galaxy/blob/ecf714475c29e294c8562a4fe5bd4beea8965f5b/client/src/components/Form/FormInputs.vue#L66) to the `error` value of the corresponding `inputs` element. In the screenshot above you can see the error value is set correctly, but if we inspect the actual *FormElement* that is rendered, the value of the `error` prop is `null` :exploding_head: 

![Screenshot from 2022-01-25 18-03-25](https://user-images.githubusercontent.com/46503462/151024240-1cd21c39-62d8-4480-aa59-9875c1ecc476.png)

I tried multiple hacks like using a different computed property for the error based on `this.attributes.error` (which clearly contains the error message in the screenshot) but no luck... this makes me think that there is a disconnection between the `input` instance that was bound to the rendered *FormElement* in the first place, probably set before actual validation, and then, we [update the error after validation here](https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Form/FormDisplay.vue#L189) but on a different instance?

There is some inputs cloning going on in FormDisplay but I'm a bit lost here... :disappointed:
