### ISSUE TITLE
Unable to use simplified workflow interface with tools having optional inputs (e.g. FastQC)

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13247]
I was testing the simplified WF interface (love it, amazing) for some screenshots, but unfortunately it doesn't work with nearly every workflow I'd show to this group. I've concluded it is because of FastQC which has some optional inputs

![image](https://user-images.githubusercontent.com/458683/151149141-8ea3e5f5-03e9-4e62-ab07-5a8e6036e448.png)

Those seem to be considered as "disconnected runtime inputs"

```
if (model.hasOpenToolSteps) {
    console.log(
        "cannot render simple workflow form - one or more tools have disconnected runtime inputs"
```

And I can't find a way in the tool UI to say "no, I don't want those, I don't have those optional inputs, please provide nothing, and do not expose this to the user". 

I could use a proper runtime input, however, that would expose it to the user and I think that's a bit sub-optimal.

![image](https://user-images.githubusercontent.com/458683/151149437-acd3a493-f514-4721-bf80-1d30038d1554.png)

Is there a way I can declare really "these are optional and I'm saying they won't be provided" so I can take advantage of the really nice and less overwhelming interface for my users?

![image](https://user-images.githubusercontent.com/458683/151149506-1e3f3389-b169-4fdb-b6ec-69dbe1f38000.png)

**Comment by jmchilton** [comment]
> And I can't find a way in the tool UI to say "no, I don't want those, I don't have those optional inputs, please provide nothing, and do not expose this to the user".
> I could use a proper runtime input, however, that would expose it to the user and I think that's a bit sub-optimal.

I did not even consider this use case but it makes perfect sense what you're trying to do here and this is clearly a huge oversight. We don't have a way to represent this... really even at the backend level either.  I'm not sure I have any quick answers either for how to go about that.

**Comment by hexylena** [comment]
> I'm not sure I have any quick answers either for how to go about that.

Oh no worries! No quick answers needed! Would just ignoring the unconnected inputs be an option, at least if it's otherwise passing the 'best practices' check?

**Comment by mvdbeek** [comment]
> really even at the backend level either. I'm not sure I have any quick answers either for how to go about that.

Don't we have optional input datasets for that ? Seems like we could just add an option that prevents the user from being able to select a dataset

**Comment by hexylena** [comment]
fantastic, thanks @mvdbeek !!
