### ISSUE TITLE
Dataset tags non visible from the history view 

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#13243]
As part of the VGP workflow, I use dataset tags to identify key outputs. I don't want to use propagating tags because I use them to mark key datasets in the analysis. 
However, these dataset tags are not visible from the history view : 
![image](https://user-images.githubusercontent.com/11195061/151027126-e708cea1-1da7-4ebb-8d7a-60091af335db.png)

I need to "Edit tags" in the dataset to see them : 
![image](https://user-images.githubusercontent.com/11195061/151027247-e88156b8-aaf7-4ca3-a420-ed9871ee8eda.png)

Seeing them would help the readability of the history without adding propagating tags that we would have to remove at every subsequent step.  

From what I understand, hiding them is voluntary. Is there a reason in particular for that? Could we create a different kind of tag that is not propagating but visible in the history?

I can work around the problem, but I feel it add unnecessary complication to workflows that are already a pain to organize.

**Comment by hexylena** [comment]
Would renaming the dataset to call it out + hiding the other datasets not accomplish a similar level of visibility to the tags?

**Comment by Delphine-L** [comment]
I can't hide other datasets, we need them all. 
By renaming datasets, I worry that we make traceability more difficult, without the `tool on data 8` info when we need to inspect intermediate files.  

As I said I can work around the problem, it just seems to add more changes to the workflows that wouldn't be necessary if we could see the tags. Is there a reason to keep them hidden?

**Comment by davelopez** [comment]
I think this is fixed now :)
