### ISSUE TITLE
[Feature Request] Tabular dataset improvement: show lines and columns

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13258]
<img width="199" alt="Screenshot 2022-01-17 at 17 45 11" src="https://user-images.githubusercontent.com/44605769/149817098-459e3b7e-9f72-4372-9426-f886e2dcf30e.png">
It would be awesome if tabular datasets (and similar) had both 'lines' AND 'columns'

_Originally posted by @nomadscientist in https://github.com/galaxyproject/training-material/discussions/2198#discussioncomment-1985220_

**Comment by nomadscientist** [comment]
Yes this would be amazing!
