### ISSUE TITLE
Improve workflow input modules.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1325]
- [x] Implement optional flag on data inputs. https://trello.com/c/M1HQcXNG
- [ ] Auto-connect disconnected inputs. https://trello.com/c/rNy04mCj
- [x] Editor should sync up input names and labels on inputs and only expose one concept. See comments on https://github.com/galaxyproject/galaxy/pull/1251.
- [x] Allow inputs to specify a input type, this could allow tighter checks in the workflow editor.

**Comment by jmchilton** [comment]
WIP: https://github.com/jmchilton/galaxy/tree/workflow_inputs

Kind of grounded to a halt on `editor_generic_form.mako` being quite broken.

**Comment by innovate-invent** [comment]
It would be way better if the module input accepted arbitrary txt, and then used that tools input validation rather than separate validation done by the simple input.
The same goes for the dataset inputs, they should solve for all connected tools and validate the intersect of all input types

**Comment by jmchilton** [comment]
Done will be in 20.01.
