### ISSUE TITLE
Update python-irodsclient version

### ISSUE THREAD

**Issue by kxk302** [galaxyproject/galaxy#13279]
Currently, we use python-irodsclient version 1.0.0. Recently, python-irodsclient version 1.1.0 has been released. Furthermore, I found and fixed a bug in python-irodsclient in connection destructor. For Galaxy 20.01 release, we should update python-irodsclient to version 1.1.1 (Will be released soon and should have the fix for connection destructor bug)

**Comment by mvdbeek** [comment]
1.1.1 is released now, but without https://github.com/irods/python-irodsclient/pull/340, so it needs to be 1.1.2 or higher.

**Comment by mvdbeek** [comment]
Pushing this to 22.05, but all fixes can be applied to all supported branches, so this can happen whenever it is ready.

**Comment by nsoranzo** [comment]
1.1.2 came out but breaks integration tests, we need a new release with https://github.com/irods/python-irodsclient/pull/357
