### ISSUE TITLE
Planemo lint fails in 22.01 for imported macros

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#13277]
**Describe the bug**

When parsing external macros a `base` property is added to the nodes: 

https://github.com/galaxyproject/galaxy/blob/32a41700f3026aa24b151a3fd7e7205ee3fd5fee/lib/galaxy/util/xml_macros.py#L294

introduced here: https://github.com/galaxyproject/galaxy/pull/13186 (https://github.com/galaxyproject/galaxy/commit/9d6bfad2553fc15da5a1b764066ebcbc1f3bb233)

Seems that this is treated like an attribute which makes xml linting (`tool_xsd`) fail. Maybe we can just remove `base` before linting? But it might create also problems with Galaxy's linters.

**Galaxy Version and/or server at which you observed the bug**

22.01

**To Reproduce**

`planemo lint`

**Expected behavior**

No error.

**Comment by bernt-matthias** [comment]
Seems that there are then two base attributes at the nodes (one with a namespace):

```
/tmp/tmpgf2put7t:4:0:ERROR:SCHEMASV:SCHEMAV_CVC_COMPLEX_TYPE_3_2_1: Element 'xref', attribute 'base': The attribute 'base' is not allowed.
/tmp/tmpgf2put7t:4:0:ERROR:SCHEMASV:SCHEMAV_CVC_COMPLEX_TYPE_3_2_1: Element 'xref', attribute '{http://www.w3.org/XML/1998/namespace}base': The attribute '{http://www.w3.org/XML/1998/namespace}base' is not allowed.
```

this might give some possibilities for filtering for the xsd linter.

**Comment by bernt-matthias** [comment]
This one gives me nightmares. Was reading a lot. And still have no idea how to deal with it... 😬

**Comment by bernt-matthias** [comment]
Plan: 

- remove storing filename at the node .. then we also do not need to copy the node when inserting macro
- return macros paths together with the lint context and store tag + attributes in the lint message (this way external applications should be able which file a line number refers to).

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/13373, thanks for the followup @bernt-matthias!
