### ISSUE TITLE
Expose non-sensitive job metrics via API

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13294]
A common request is that people would like to see a jobs' actual runtime (not just the total time between create_time and update_time) and possibly additional metrics like CPU and memory usage (if available). We don't expose this info to non-admins in https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/managers/jobs.py#L415, but I think we should probably list a few things that are clearly not sensitive information and expose thes.

**Comment by bgruening** [comment]
I think this was implemented in https://github.com/galaxyproject/galaxy/pull/13634
