### ISSUE TITLE
YAML preview doesn't work in Firefox

### ISSUE THREAD

**Issue by elichad** [galaxyproject/galaxy#13295]
**Describe the bug**
#13168/#13176 added a text preview for the YAML filetype, but it doesn't work in Firefox. Firefox sees the intended mediatype, but still wants you to download it to view. Chrome allows you to preview the file in the Galaxy UI as intended.

**Galaxy Version and/or server at which you observed the bug**
Observed both on usegalaxy.eu `{"version_major": "21.09", "version_minor": "1.dev0"}`
and on the current tip of dev 6df8d1ae5b54bbb0961576622066a3d2b95f6728 . 
Behaviour is the same on both Mac and Windows.

**To Reproduce**
1. Use Firefox
2. Upload a file with the yaml datatype
3. Click "View data" in the history
4. See download dialog

**Expected behavior**
File is previewed like other text files.

**Screenshots**
![Firefox download dialog for a file of type text/x-yaml](https://user-images.githubusercontent.com/20683271/152193192-7a5ba6af-c4e2-4b30-b3ac-973b86712570.png)

**Additional context**
We've only tested Firefox and Chrome/Chromium. I'm not sure if other browsers behave as intended or not.

**Comment by mvdbeek** [comment]
Hmm, guess we need to set the mimetype to text/plain, that's unfortunate.

**Comment by nsoranzo** [comment]
Maybe forcing `Content-Disposition: inline` works? https://medium.com/@alfredpfrancis/how-to-force-files-to-open-in-the-browser-instead-of-downloading-95229d79d71e
