### ISSUE TITLE
Release testing 22.01

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#13319]
This is a list of tests being performed on the release of 22.01. It is intended as a way for the community and team to view and participate in the testing should they wish to. As tests are completed, please click the checkbox next to it.

For each test, please check against a local instance, all public instances, as well as cloud instances and Anvil, if possible and reasonable.

For failed tests or other general notes, please add them here:
[Test Spreadsheet](https://docs.google.com/spreadsheets/d/1eB1UncArzI_o6qFaOON64b_1nhQaLQ3u1ZUAbZP4hRc/edit#gid=0)

Highlights
- [ ] https://github.com/galaxyproject/galaxy/pull/13224
- [ ] https://github.com/galaxyproject/galaxy/pull/13068
- [x] https://github.com/galaxyproject/galaxy/pull/12940
- [ ] https://github.com/galaxyproject/galaxy/pull/12912
- [ ] https://github.com/galaxyproject/galaxy/pull/12867
- [ ] https://github.com/galaxyproject/galaxy/pull/12811
- [ ] https://github.com/galaxyproject/galaxy/pull/12500

Trainings

- [ ] [Rule Based Uploader](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/upload-rules/tutorial.html) | Area: UI
- [ ] [Rule Based Uploader: Advanced](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/upload-rules-advanced/tutorial.html) | Area: UI
- [ ] [Extracting Workflows from Histories](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/history-to-workflow/tutorial.html) | Area: UI
- [x] [Searching Your History](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/search/tutorial.html) | Area: UI
- [ ] [Understanding Galaxy history system](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/history/tutorial.html) | Area: UI
- [ ] [Group tags for complex experimental designs](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/group-tags/tutorial.html) | Area: UI
- [ ] [Multisample Analysis](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/processing-many-samples-at-once/tutorial.html) | Area: UI
- [ ] [Name tags for following complex histories](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/name-tags/tutorial.html) | Area: UI
- [ ] [Using dataset collections](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/collections/tutorial.html) | Area: UI
- [ ] [Creating, Editing and Importing Galaxy Workflows](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/workflow-editor/tutorial.html) | Area: UI
- [ ] [InterMine integration with Galaxy](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/intermine/tutorial.html) | Area: UI
- [ ] [JupyterLab in Galaxy](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/jupyterlab/tutorial.html) | Area: UI
- [ ] [Use Jupyter notebooks in Galaxy](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/galaxy-intro-jupyter/tutorial.html) | Area: UI
- [ ] [RStudio in Galaxy](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/rstudio/tutorial.html) | Area: UI
- [x] [Using Workflow Parameters](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/workflow-parameters/tutorial.html) | Area: UI
- [ ] [Downloading and Deleting Data in Galaxy](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/download-delete-data/tutorial.html) | Area: UI
- [ ] [A short introduction to Galaxy](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-short/tutorial.html) | Area: core
- [ ] [From peaks to genes](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.html) | Area: core
- [ ] [Galaxy 101](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101/tutorial.html) | Area: core
- [ ] [Galaxy 101 for everyone](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101-everyone/tutorial.html) | Area: core
- [ ] [Introduction to Genomics and Galaxy](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-strands/tutorial.html) | Area: core
- [ ] [NGS Data Logistics](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-ngs-data-managment/tutorial.html) | Area: core
- [ ] [16S Microbial analysis with Nanopore data](https://training.galaxyproject.org/training-material/topics/metagenomics/tutorials/nanopore-16S-metagenomics/tutorial.html) | Area: science
- [ ] [Whole transcriptome analysis of Arabidopsis thaliana](https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/mirna-target-finder/tutorial.html) | Area: science
- [ ] [Running jobs in Singularity](https://training.galaxyproject.org/training-material/topics/admin/tutorials/singularity/tutorial.html) | Area: admin
- [ ] [Reference Data with CVMFS](https://training.galaxyproject.org/training-material/topics/admin/tutorials/cvmfs/tutorial.html) | Area: admin
- [ ] [Data Libraries](https://training.galaxyproject.org/training-material/topics/admin/tutorials/data-library/tutorial.html) | Area: admin
- [ ] [Connecting Galaxy to a compute cluster](https://training.galaxyproject.org/training-material/topics/admin/tutorials/connect-to-compute-cluster/tutorial.html) | Area: admin
- [ ] [Mapping Jobs to Destinations](https://training.galaxyproject.org/training-material/topics/admin/tutorials/job-destinations/tutorial.html) | Area: admin
- [ ] [Recording Job Metrics](https://training.galaxyproject.org/training-material/topics/admin/tutorials/job-metrics/tutorial.html) | Area: admin
- [ ] [Running Jobs on Remote Resources with Pulsar](https://training.galaxyproject.org/training-material/topics/admin/tutorials/pulsar/tutorial.html) | Area: admin
- [ ] [Distributed Object Storage](https://training.galaxyproject.org/training-material/topics/admin/tutorials/object-store/tutorial.html) | Area: admin
- [ ] [Galaxy Installation with Ansible](https://training.galaxyproject.org/training-material/topics/admin/tutorials/ansible-galaxy/tutorial.html) | Area: admin

**Comment by hexylena** [comment]
For those testing with Tapas in mind, we'll be using all of the above, minus:
- searching
- understanding history
- group tags
- multisample
- name tags
- intermine
- Workflow parameters,  downloading/deleting

because there aren't videos for those currently. (That's welcome to change.)
