### ISSUE TITLE
Replace conda with mamba

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#13329]
[Mamba](https://mamba.readthedocs.io/) is an alternative package manager which is fully compatible with conda packages and supports most of conda’s commands.
Conda has sometimes issues when resolving requirements that cause it to stall for hours or just fail. Mamba has proved to be able to resolve the same requirements amazingly quickly and reliably for quite some time now, so I think it's time we move to Mamba.
The recommended installation method for Mamba is https://github.com/conda-forge/miniforge#mambaforge

**Comment by bgruening** [comment]
The mamba solver will be integrated into conda soon. Bioconda has decided to wait for this integration instead of switching to mamba.

**Comment by nsoranzo** [comment]
@bgruening Nice to know! The integration seems to be currently tracked at https://github.com/conda/conda/milestone/53 . Not sure how long it will take to become the default though.

**Comment by bgruening** [comment]
See also: https://github.com/conda/conda/pull/11193

**Comment by nsoranzo** [comment]
> See also: [conda/conda#11193](https://github.com/conda/conda/pull/11193)

The PR has been merged, so we should see it in a released conda soon.
