### ISSUE TITLE
data_column incompatible batch submission

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1332]
https://github.com/galaxyproject/tools-devteam/blob/master/tools/tabular_to_fasta/tabular_to_fasta.xml

I'd really rather see data_column usage decrease/disappear, but that's my personal preference. It's a pain to use and painful in workflows due to the requirement that the file with exact column counts be available at tool-configuration time making it wholly useless even if the person writing the workflow knows precisely which columns they want.

Steps to Reproduce:
- Open up tabular_to_fasta
- select more than one input file, intending to submit a batch job
- no error, just refuses to execute. 

API call shows:

``` json
{"err_data": {}, "err_msg": "Unknown error occurred while processing request.", "err_code": 0}
```

**Comment by mvdbeek** [comment]
Is this still an issue ? I think we cast these select still parameters as regular text fields in the workflow editor, so you can just enter the fields if you know them.
