### ISSUE TITLE
API Key UI Enhancement

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#13328]
Field is currently disabled for editing, and difficult to select to copy the API key out of.  Here's what it looks like now:

![image](https://user-images.githubusercontent.com/155398/153060181-5d805341-ead5-4d4b-8af6-b3d865266088.png)

It shouldn't be editable, but there's no reason it should be unselectable.  Most people visiting this page will want to select that key and then do something with it.  Adding a copy-to-clipboard button would also be nice.  Here's an example out of Google Maps as an example of how this could be improved:

![image](https://user-images.githubusercontent.com/155398/153059838-cea6d704-ec83-466e-808f-cb8eb13f2b85.png)

**Comment by dannon** [comment]
@shivani-sangwan is taking a stab at this, converting the old forms-style interface to a new vue component for representing/resetting API keys.

**Comment by dannon** [comment]
Bonus points for doing https://github.com/galaxyproject/galaxy/issues/10742 at the same time.

**Comment by afgane** [comment]
This all will be great. In addition, although possibly a bigger task, it is conceivable a user would want multiple keys (for use in different applications) so having an option to store multiple API keys would also be nice.
