### ISSUE TITLE
Export history link requires authentication

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#13331]
**Describe the bug**
Exporting a history and obtaining a link to the archive yields a link that requires authentication to obtain, which used to not be the case. The URL structure of the link also changed from release 21.09, which is likely to break downstream scripts and libraries. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01 rc1
usegalaxy.org

**To Reproduce**
1. Go to History Options -> Export history archive
2. Click on Click here to generate a new archive for this history.
3. Try to import the given link into another Galaxy, or just open it in a private window. 

**Expected behavior**
A URL that can be imported into another Galaxy instance.

**Screenshots**
![image](https://user-images.githubusercontent.com/338642/153085270-ec7a525b-5432-4130-a6d7-22854c587ac5.png)

**Comment by dannon** [comment]
xref https://github.com/galaxyproject/galaxy/pull/13330 ?

**Comment by afgane** [comment]
The linked PR looks like will fix this. How about the URL structure change?

For 21.09, archive links looked like this: https://usegalaxy.eu/history/export_archive?id=afa89b481b0a428b&jeha_id=f039d45b0ad5a177

For 22.01, the links look like this: https://usegalaxy.org/api/histories/151d6e763c0120a5/exports/1402f20d44f9f5ba

Won'

**Comment by mvdbeek** [comment]
The archives should be rotated out of the temp dir on a frequent basis,  so this has never been a stable link. I don't think we need to maintain the URL. Also the export endpoint returns the URL where you can download the archive, so it shouldn't break external scripts.

**Comment by afgane** [comment]
| ... so it shouldn't break external scripts.
Just ask @ksuderman :joy:

I didn't know the exported archive URLs expire. I'm glad I found out because we were planning on using them in documentation so we won't be doing that. 

What's the reasoning behind expiring the archive URLs? How often, or after what amount of time do they expire? Is this a configurable option for a server?

**Comment by mvdbeek** [comment]
You don't want to keep the archive forever, those can be quite large. `pg_cleanup.py` deletes these on the large public instances IIRC. That said I am wrong, we don't return the download url in the response, we expect the client to build the URL. We can probably add a fallback route.

**Comment by ksuderman** [comment]
> The archives should be deleted on a frequent basis, 

How frequent is frequent?  I was under the impression that this was the preferred method to share histories between Galaxy instances.  This feels like purging user histories when the user hasn't selected "Purge My Histories".  Do these files not count towards the user's quota?

> we expect the client to build the URL

Which is a good reason not to change how those URL are built 😉 . The people I share a URL with don't have access to call the export endpoint so can't re-build the URL if/when it changes or is deleted.

**Comment by mvdbeek** [comment]
> How frequent is frequent?

14 days ? 28 days ? Depends on the site policy, here's the script https://github.com/galaxyproject/galaxy/blob/dev/scripts/cleanup_datasets/pgcleanup.py#L1005. It is the preferred way to share between Galaxy instances, but we can't keep these forever, and it's not the most obvious assumption that we would keep the link forever

**Comment by mvdbeek** [comment]
Which is possible right from the history export dialog for writable file sources configured on the instance
<img width="1813" alt="Screenshot 2022-02-09 at 17 03 39" src="https://user-images.githubusercontent.com/6804901/153240188-a63d85a4-b816-4df5-8a60-c0ee16e82903.png">

**Comment by mvdbeek** [comment]
But to chain the export and import you need to construct the right url, because you only get the jeha_id back. I suppose this has always worked in bioblend because we always targeted the API endpoint (which isn't new). The change is that the UI tells you to get the archive via the api now, as opposed to the controller.

**Comment by ksuderman** [comment]
> Maybe, for your use case, can help to reupload the exported histories to a more long-term external storage

Yes, we have moved to S3

> Why not use

We do, but as Marius mentions, the method to derived the URL to use for import changed.  I wasn't aware the archives expired until this issue (it does explain some failures I was seeing), but that is likely a topic for another discussion/issue.

**Comment by mvdbeek** [comment]
The history export link doesn't require authentication anymore, https://github.com/galaxyproject/galaxy/pull/13330 is live on usegalaxy.org. I don't think we need to maintain non-API routes (at least we haven't in the past), but I'd suggest we note this in the release notes. How does that sound @afgane @ksuderman ?

**Comment by ksuderman** [comment]
Thanks for #13330 I will test it ASAP.

> so clearly that's a stable URL.

And it was when the "stable URL" stopped working that we raised an issue.  However, the URL stopped working for reasons other than the format change.

>  I don't think we need to maintain non-API routes

I am generally -1 on breaking things (ie removing routes that were part of a public API), but given the archived histories can disappear without warning that is likely a moot point.

**Comment by dannon** [comment]
In general practice, we have not considered the internal web controllers to be a part of the public API, only the <instance>/api/* endpoints.

**Comment by ksuderman** [comment]
We can discuss what makes up the public API at the next lab meeting, but I would put forth the proposition that when I click "Export History" and I'm told the URL is https://usegalaxy.eu/history/export_archive?id=0131c92e50486c00&jeha_id=48fdc776edc0b470 then that URL is part of a "public API".  But as I said, moot point, since we break these URLs anyway.

**Comment by mvdbeek** [comment]
Thanks @afgane & @ksuderman. Closing this with https://github.com/galaxyproject/galaxy/pull/13389 and https://github.com/galaxyproject/galaxy/pull/13330
