### ISSUE TITLE
RE:Extract Genomic DNA - cannot find tool with id

### ISSUE THREAD

**Issue by chasegomez** [galaxyproject/galaxy#13346]
When I select the Extract Genomic DNA tool from the tool shed, I receive the attached error.
![tool_lookup_error](https://user-images.githubusercontent.com/75462184/153404868-a7584b1e-cee7-4bff-8e68-b99932667d03.PNG)

**Comment by dannon** [comment]
xref https://github.com/galaxyproject/galaxy/issues/13006; I'll take care of this one.

**Comment by mvdbeek** [comment]
Thanks for the report @chasegomez, it is fixed and deployed to usegalaxy.org now.
