### ISSUE TITLE
Run workflow: simple inputs used for workflow logic not expanded

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/galaxy#13340]
**Describe the bug**
When multiple simple inputs are created, some of them are not expanded by default. This problem was reported by @mpalmada. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09 (usegalaxy.eu)

**To Reproduce**
1. Import this workflow: https://usegalaxy.eu/u/palmadamarc/w/orgone-assembly-workflow
2. Run it.

**Expected behavior**
Simple inputs used for workflow logic are not expanded. In that specific case,  assembly name, enable scaffolding with Flye and version should be expanded.

**Screenshots**
![Screenshot from 2022-02-09 17-44-50](https://user-images.githubusercontent.com/26678117/153248290-89162d83-4fb0-4273-b72f-124009d33f9f.png)

**Comment by mpalmada** [comment]
I have seen that some workflow units are expanded and some others don't without any clear logic behind. Moreover, I have not found a way to leave expanded or collapsed the different steps in the "setting the run" window.

**Comment by mpalmada** [comment]
I am wondering if this could be tricked to determine manually, just if you want, if you want to have the steps expanded or collapsed. It would be cool!
