### ISSUE TITLE
samtools 1.3 sorting for grooming BAM files

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#1336]
See http://dev.list.galaxyproject.org/Fwd-Samtools-devel-Samtools-BCFtools-HTSlib-1-3-released-td4668556.html

The old way of invoking the samtools sort subcommand has been superseded since samtools 1.0 and from samtools 1.3 release no longer works: `samtools sort [-f] [-o] in.bam out.prefix`

Galaxy needs to change how it sorts BAM files as part of data grooming:

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/binary.py#L211

At a minimum that version check could be expanded to use the newer syntax on recent samtools. Alternatively (on IUC mailing list), @yhoogstrate suggests using pysam for this.

**Comment by yhoogstrate** [comment]
I did something similar for CRAM indexing: https://github.com/galaxyproject/galaxy/pull/1182

**Comment by hexylena** [comment]
We now use pysam :)
