### ISSUE TITLE
Beta history: contents/before endpoint needs to be (a lot) faster

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13369]
Scrolling past the 50 loaded items in a history results in a "stutter" where results are fetched from the server. This needs to be somewhere in the 50-100 ms range (not just for UX, this also affects server and database load).

The beta history currently requests the detailed view, which can be cleaned up further or be split, but these are the approximate timings on my laptop on top of https://github.com/galaxyproject/galaxy/pull/13355 for a history with 101 items, mixed collections and datasets.

View | job state summary | Timing (ms)
-----|--------------------|------
Summary | No | 350
Summary | Yes | 400
Detailed | No | 1200
Detailed | Yes | 1200

It's a little unclear how much progress we can make on this on the backend side. Clearly there are a few suboptimal things in there, but also a lot of easy optimizations have been done already. 

I think this is actually much more important for the new history than the old history, where in the old history we loaded 500 visible items, which I'd estimate is sufficient for 95-99% of analysis use cases, while 50 items are sufficient for maybe 20% of histories (totally biased and estimated numbers, but we could back this up with a few queries against main).

From the user perspective I feel like 2-3 seconds are maybe acceptable on first load, but it should be much less on scrolling.
If we can't make progress (or maybe we should work on this in parallel) on getting this into an acceptable range we need to think about 
-  increasing the window size
- progressively loading more content until we reach something like 500 visible items
- loading the job state summary in separate requests. These are easy to cache IMO, and that's what the old history does.
- (you're suggestion here ;))

**Comment by mvdbeek** [comment]
Since this has bitten me before, there's definitely some caching going on when hitting the same API endpoint twice, so it is considerable faster there. But to be fair I think we have to work with the timing from the first request (which I've done here).

**Comment by mvdbeek** [comment]
I've played a bit with optimizing the contents/before endpoint in https://github.com/galaxyproject/galaxy/compare/dev...mvdbeek:optimize_views?expand=1. I'm gonna let this sit there while we figure out the endpoint to use.
One lesson from this is that we should create some representative benchmarks for the API routes we're thinking of hitting.
Some naive benchmarking showed this (before):
```
./wrk -c 1 -t 1 -d10s [http://127.0.0.1:8080/api/histories/bee6217eb4e27b0f/contents/before/366/50\?view\=summary\&visible\=True\&deleted\=False](http://127.0.0.1:8080/api/histories/bee6217eb4e27b0f/contents/before/366/50/?view\=summary\&visible\=True\&deleted\=False)
Running 10s test @ http://127.0.0.1:8080/api/histories/bee6217eb4e27b0f/contents/before/366/50?view=summary&visible=True&deleted=False
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    69.78ms   27.91ms 313.26ms   96.73%
    Req/Sec    14.72      5.30    20.00     64.58%
  149 requests in 10.07s, 3.20MB read
Requests/sec:     14.79
Transfer/sec:    325.62KB
```
and with the tweaks
```
./wrk -c 1 -t 1 -d10s [http://127.0.0.1:8080/api/histories/bee6217eb4e27b0f/contents/before/366/50\?view\=summary\&visible\=True\&deleted\=False](http://127.0.0.1:8080/api/histories/bee6217eb4e27b0f/contents/before/366/50/?view\=summary\&visible\=True\&deleted\=False)
Running 10s test @ http://127.0.0.1:8080/api/histories/bee6217eb4e27b0f/contents/before/366/50?view=summary&visible=True&deleted=False
  1 threads and 1 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    38.65ms   26.80ms 296.51ms   97.15%
    Req/Sec    28.05      5.65    40.00     75.79%
  273 requests in 10.02s, 5.82MB read
Requests/sec:     27.24
Transfer/sec:    594.75KB
```

**Comment by davelopez** [comment]
Wow! that's almost 2x faster!
I wonder how much of that time is eating up the response validation, I bet for these kinds of big responses is quite a lot and we probably shouldn't validate it at all, and just make sure we build it correctly. In the past, It has helped me identify when there was a mismatch between the response model and the actual serialized data but this is clearly something that we need to avoid.
Also, I think the [inferring router](https://fastapi-utils.davidmontague.xyz/user-guide/inferring-router/) may not be very helpful here and we will have to set the `response_model` (as you did) since it will try to validate against the return type hinted. 
Or maybe we can keep it and use the [model construct](https://pydantic-docs.helpmanual.io/usage/models/#creating-models-without-validation) when creating the response without validation :thinking:

**Comment by mvdbeek** [comment]
Yep, I tried both of these, and it does give a small speedup (~7ms IIRC). I think eventually we should do validation in our tests, but not in production.

If I can trust `EXPLAIN ANALYZE` our queries should be pretty fast, so I think we're also hitting some of sqlalchemy's ORM and our custom serializer overhead at this point. Once we really nail the endpoint parameters we need we could just return the query results as named tuples and build the response model from that. I'm hesitant to go too deep before we are sure what attributes to return. We could speculate and say we want to use the shape of our response model attributes to return an optimized sqlalchemy core construct ... but then again it feels like we'd be re-inventing the wheel (again), and making it general enough to support attributes from related models seems possible, but also a bigger project.

@guerler also thought it's possible that we don't need the total / min / max queries at all, so that would be another area of improvement.

**Comment by mvdbeek** [comment]
We're not using that endpoint anymore. Some of the tweaks in https://github.com/galaxyproject/galaxy/compare/dev...mvdbeek:optimize_views?expand=1 will still be worth implementing on a case by case basis
