### ISSUE TITLE
Beta history current history id not synced up with legacy components

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13368]
Go to Users -> Histories, switch to another history and see that you don't see the new history in the history panel

**Comment by mvdbeek** [comment]
(Where the options are rewriting all legacy components, or figuring out how to sync the current history id)

**Comment by itisAliRH** [comment]
@mvdbeek

**Comment by mvdbeek** [comment]
@itisAliRH if you need help getting started let me know!

**Comment by itisAliRH** [comment]
@mvdbeek I found the problem. The switch function used the `refresh_frame`, which only updates the legacy history
https://github.com/galaxyproject/galaxy/blob/43372cac7575dcc3e7ec3f476982878329f36629/lib/galaxy/webapps/galaxy/controllers/history.py#L359 in User>Histories, when clicking on the switch, this line fired. Then legacy history reloaded here https://github.com/galaxyproject/galaxy/blob/43372cac7575dcc3e7ec3f476982878329f36629/client/src/legacy/grid/grid-view.js#L80
Should I emit history store change from `grid-view.js` or in `history.py`?

**Comment by mvdbeek** [comment]
Yeah, I think that looks like a good fix.
