### ISSUE TITLE
Tool differential behavior between instances

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/galaxy#13374]
**Describe the bug**
It has been reported in Stringtie, but could affect other tools. Specifically, the problem is that a parameter is considered optional in *EU, but not in *ORG. I can confirm that the problem is not related to the tool version.

Code line: https://github.com/galaxyproject/tools-iuc/blob/master/tools/stringtie/stringtie.xml#L218

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: usegalaxy.org (v. 22.01) & usegalaxy.eu (v. 21.09)

**To Reproduce**
1. Import EU history: https://usegalaxy.eu/u/gallardoalba/h/stringtie-test-history
2. Run Stringtie
3. Import ORG history: https://usegalaxy.org/u/gallardoalba/h/stringtie-test-history
4. Run Stringtie

**Expected behavior**
The **Name prefix for output transcripts** should be optional in both cases.

**Comment by mvdbeek** [comment]
The parameter is not optional in the xml, why do you think it should be optional in Galaxy @gallardoalba ?

**Comment by gallardoalba** [comment]
The problem is that in usegalaxy.eu is not required to specify a value, but it is required in usegalaxy.org. I cannot understand the reason.

**Comment by mvdbeek** [comment]
It is a bug on 21.09 and earlier that we don't discriminate `null` from `""`. We do this now (but of course you can click into the text parameter and not write anything).
