### ISSUE TITLE
Question mark link in the tools requirements section is broken

### ISSUE THREAD

**Issue by gmauro** [galaxyproject/galaxy#13378]
**Describe the bug**
the ? icon in the "Requirements" section at the end of the tool's panel, it's linked to the non-existent URL https://galaxyproject.org/tools/requirements/

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01 rc1
usegalaxy.org

Galaxy Version: 21.09 1.dev0
usegalaxy.eu

**To Reproduce**
1. Go to any tool's page you prefer on .org or .eu
2. Click on the '?' at the end of the page in the Requirements section
3. See the "Page not found" error from the galaxyproject.org website

**Expected behavior**
Should appear the proper web page

**Comment by mvdbeek** [comment]
I think we need to restore this on the hub given that we link out to this page from older releases. @NickSto can you take a look at this ?

**Comment by NickSto** [comment]
Yep, tracking here: galaxyproject/galaxy-hub#1167

This was removed at some point for some reason.

**Comment by NickSto** [comment]
Okay this is now [fixed](https://galaxyproject.org/tools/requirements/).
