### ISSUE TITLE
Workflow parameters in text fields are duplicated in run form

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13372]
**Describe the bug**
![image](https://user-images.githubusercontent.com/6804901/153905644-09109f28-183b-4dfb-b127-02284db8f28a.png)
for https://usegalaxy.org/u/delphinel/w/copy-of-bionano-scaffolding-export-imported-from-uploaded-file
**Galaxy Version and/or server at which you observed the bug**
22.01

This works if you only use the text parameter via a regular text parameter, as the best practices panel would suggest, but if you want to build up a string that's a good bit more work.

**Comment by guerler** [comment]
If I understand this correctly that workflow parameters cannot be applied to non-tool steps. For tool steps they are parsed as `wpData` and processed with `replaceParams` handling within the tool step component. In order for this to work for non-tool steps a probably simple replacement function has to be added to the non-tool step wrapper. See: https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Workflow/Run/WorkflowRunForm.vue#L44

**Comment by davelopez** [comment]
Sorry, I forgot about this one... Just to see if I understand correctly what needs to be done:

Should I pass the `wpData` to `WorkflowRunDefaultStep` and, if the step label matches any of the `wpData`, don't render that parameter because is already in the *Workflow Parameters* at the top?

I'm a bit out of context here :sweat_smile:

**Comment by mvdbeek** [comment]
Hmm, so this is more complicated. This only happens when replacing a legacy parameter in a text field. It would be neat to be able to use the `${param}` syntax there, but the way these are resolved currently is by passing the parameter into the replacement dict on the client. 

We probably want to be able to replace the parameter when scheduling the step and track the step dependency in the database.

**Comment by guerler** [comment]
There has been a regression in dev.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/2105447/200037590-29f144e1-9a6e-4eee-b644-8d056c2d05e4.png">

**Comment by mvdbeek** [comment]
I think that was fixed some time ago
