### ISSUE TITLE
Installing packages from different owner with same name and same toolshed stuck in NEW

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#1338]
No obvious error in the logs.
This current case happens reproducibly on dev when installing a toolsuite that pulls in packages through tool dependencies. Note also that the Descrition column says `None`.
<img width="1424" alt="screen shot 2015-12-16 at 13 19 53" src="https://cloud.githubusercontent.com/assets/6804901/11840649/be2faa30-a3f7-11e5-97a4-86ffd17a14d2.png">
This happens typically for iuc and devteam packages that are otherwise the same.
Uninstalling and re-installing by hand resolves the problem, but for bootstrapping instances / distributing suites and workflows this is super annoying.

Before digging into this, any ideas @bgruening @gregvonkuster @martenson ?

**Comment by gregvonkuster** [comment]
@mvdbeek Can this be reproduced with a single repo install that has 2 dependencies with the same name but different owners?  This will be much easier to fix if we don't have to use a large suite for reproducing the behavior.

**Comment by mvdbeek** [comment]
Yup, I will try to get a nice testcase.

**Comment by bgruening** [comment]
@mvdbeek latest dev? We fixed one of these "white ghosts" recently afaik.

**Comment by mvdbeek** [comment]
yep, installed today, last commit d1fd23a2f4e5c5408f469ee5560f526833f5f682

**Comment by mvdbeek** [comment]
Okay, [this](https://testtoolshed.g2.bx.psu.edu/view/mvdbeek/suite_white_ghosts/f8aa371efc50) is still big and can probably be tuned down to a single package, but it suffices for stepping in with a debugger.
When I look at the "monitoring installation" screen I see that either devteam or iuc appears, so it smells like a dictionary issue very early in the install process.
<img width="1422" alt="screen shot 2015-12-16 at 15 13 10" src="https://cloud.githubusercontent.com/assets/6804901/11843264/f35c029c-a408-11e5-9e9d-cf3e91ee5bd5.png">

**Comment by gregvonkuster** [comment]
@mvdbeek Thanks for putting this together.  So does this problem arise only when there are 2 tool dependency packages with the same name and same version but with different owners?  Or will it also happen when there are 2 tool dependency packages with the same name but different versions and owner?  The former (your scenario) seems like a strange case where the relationships probably should not exist.  The latter seems strange as well, but maybe less strange - I don't know.

**Comment by mvdbeek** [comment]
Well, what I found so far is that the `create_repository_dependency_objects` method in [lib/tool_shed/galaxy_install/repository_dependencies/repository_dependency_manager.py](https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/repository_dependencies/repository_dependency_manager.py#L147) is creating all_repo_info_dict, with the package names as key, which is the problem. I suppose we could feed directly the objects instead of the repo name as key.

So yes, same package name in the same install transaction should always result in this behaviour.

**Comment by martenson** [comment]
fixed by #1366 thanks to @mvdbeek !
