### ISSUE TITLE
Tooltip not clearing for dataset tags

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#13380]
**Describe the bug**
Unlike other tooltips for dataset actions, the tooltip for tags stays visible after moving the cursor off the icon.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01
usegalaxy.org

**To Reproduce**
1. Expand a dataset and hover over the tags button

https://user-images.githubusercontent.com/338642/154098780-53fee769-6524-4ed0-99a4-2e73efada643.mov

**Comment by mvdbeek** [comment]
This can be fixed at any moment in time, I'm moving this to 22.05.

**Comment by mvdbeek** [comment]
Seems like that's fixed in the new history since we don't have that button anymore
