### ISSUE TITLE
Issues with the parsing of Visualization XMLs

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#13384]
**Describe the bug**
When attempting to visualize datasets with charts, the XML is not parsed correctly anymore.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01 & 22.05

**To Reproduce**
1. Go to 'Visualization'
2. Click on any of the Bar Diagrams
3. Expand the menu with visualization options and parameters

**Expected behavior**
The input elements should render properly with title, label, help and value.

**Screenshots**
![image](https://user-images.githubusercontent.com/2105447/154107759-0b5870b5-b528-4c17-a4e1-bc9eeec1ebf9.png)

**Additional context**
There is an existing issue with automatically rebuilding visualizations which makes tracking this issue down much more cumbersome. Changes are not always detected and rebuilding visualization takes a lot of time. Sometimes this requires to manually delete build files before re-running the build process.

**Comment by dannon** [comment]
Might be related: https://github.com/galaxyproject/galaxy/pull/13373/files
