### ISSUE TITLE
History advance searching with multiple parameters failing when multiple terms use quotes

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#13395]
On both Org and EU, searching the history using advanced searching tags functions with a single term, but using multiple has an issue using quotation marks. The search functions ok if neither use quotation marks for the query, or if neither do, but not if one has the quotes and one does not. It does not matter if either or both query is multiple words, using multiple queries with quotes results in no results.

https://user-images.githubusercontent.com/40246333/154342201-065395f7-ea4b-4569-bcac-b5924e951f46.mov

**Comment by dannon** [comment]
Looks like we need to tokenize quoted content correctly when paired with advanced search parameters.

**Comment by davelopez** [comment]
xref https://github.com/galaxyproject/galaxy/pull/13626

**Comment by guerler** [comment]
Has been resolved in #13623.
