### ISSUE TITLE
Exporting histories with "include_hidden=True" has data files missing

### ISSUE THREAD

**Issue by quacksawbones** [galaxyproject/galaxy#13391]
Hi Folks,

Found a weird bug while working on a script to download/migrate histories from one Galaxy instance to another. When `include_hidden=True` is passed into the `export_history()`  function, Galaxy will only include the hidden data files in the datasets folder. If there are no hidden data files in the history, no data files are included in the downloaded history. We wanted to migrate both deleted AND hidden data files to maintain the provenance from our old version of Galaxy. This doesn't happen when creating an export using the GUI (presumably because an identical API end point is not called)

Bioblend Version: 0.16.0
Galaxy Version: 20.01 and 21.05
Python Version: 3.6.8 and 3.9.9

To replicate (assuming a working GalaxyInstance object "gi"):

1. Create a new history (history_id="x")
2. Add two new data files
3. API - gi.histories.show_history(history_id="x")
4. API - gi.histories.update_history(history_id="x",importable=True)
5. API - jeha_id = gi.histories.export_history(history_id="x",gzip=True,wait=True)
6. API - gi.histories.download_history("x",jeha_id,open("/path/filename_nohidden.tar.gz","wb"))

_Downloaded gzipped tarball includes all files in the history in the datasets directory_

7. API - gi.histories.update_history(history_id="x",importable=False)
8. API - gi.histories.update_history(history_id="x",importable=True)
9. API - jeha_id = gi.histories.export_history(history_id="x",gzip=True,include_hidden=True,wait=True)
10. API - gi.histories.download_history("x",jeha_id,open("/path/filename_hidden.tar.gz","wb"))

_Downloaded gzipped tarball includes only hidden files in the history in the datasets directory. If no hidden files, datasets directory does not exist._

**Comment by mvdbeek** [comment]
I think we fixed that with https://github.com/galaxyproject/galaxy/pull/13387
