### ISSUE TITLE
Upload > Rule-based tab -- "Reset" button is greyed out any prior data/settings remain

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#13405]
**Describe the bug**
Upload > Rule-based > "Reset" button remains greyed out after a prior load/submission after opening the Upload tool again. No way to clear prior with a single click. The "Reset" button on the "Regular" tab doesn't clear the "Rule-based" tab. Can reproduce at ORG(22.01 pre-release) + EU(21.09) + GCP(22.01 pre-release) -- must have been none functional at least since 21.09.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Go to Upload tool > Rule-based tab
2. Paste something in there and load it
3. Go back to the Upload > Rule-based tab
4. Any prior data/settings remain, "Reset" button is greyed out
5. (The pop-up over all three buttons is the same, long, and reports a non-specific odd message -- see screenshot, and @astrovsky01 noticed it can cover the buttons)
5. To clear that, must manually remove or change prior data/settings
6. Going forward to the "Build" form, "Reset" only clears the rules applied, not the data (this was expected)

**Expected behavior**
1. Make the "Reset" button active under Upload > Rule-based tab
2. Make the "Reset" button under Upload > Regular (first tab) clear all non-default settings present in any Upload tab

**Screenshots**
<img width="888" alt="Screen Shot 2022-02-17 at 3 16 36 PM" src="https://user-images.githubusercontent.com/8999735/154591738-1cd11e57-b415-4180-9419-2b633a7b21ad.png">

<img width="972" alt="Screen Shot 2022-02-17 at 3 31 01 PM" src="https://user-images.githubusercontent.com/8999735/154591775-6c5a50d4-477c-4474-97d9-ba655dbd273f.png">

<img width="289" alt="Screen Shot 2022-02-17 at 3 29 30 PM" src="https://user-images.githubusercontent.com/8999735/154591765-9acb8876-6de0-46e0-9fd0-404e8e879d3b.png">

**Additional context**
Found during [22.01 release testing](https://github.com/galaxyproject/galaxy/issues/13319) with this [GTN tutorial](https://training.galaxyproject.org/training-material/topics/galaxy-interface/tutorials/upload-rules/tutorial.html)

**Comment by assuntad23** [comment]
Fixed with #13443
