### ISSUE TITLE
Reports: css not loaded

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#13400]
**Describe the bug**
The reports app comes up with no css. All the links to `static` locations result in 404 errors. (although the favicon is displayed, unless it's cached by the browser?)

![bad](https://user-images.githubusercontent.com/6132258/154548971-c7023ac4-5d13-46c8-85dc-045412165d09.png)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05/dev0
Commit: 88b455c953ce1b445de2cb63fadb9fc019ba1e2d

**To Reproduce**
`./run_reports.sh`

**Expected behavior**
![good](https://user-images.githubusercontent.com/6132258/154549047-8411c685-899a-4155-afd6-82f2ddecebf3.png)

**Additional context**
I've tried to bisect this, but git-bisect results are hard to interpret: at some point after a bad commit it jumps out of bounds, past the earliest bad commit - so a parent commit happened prior to the date of my earliest "good" commit. So, 

Latest "good" commit I was able to identify: 082e4d0117024c5532c4178564a62194c666e15c
The following commit is "bad", but its contents are unrelated: 4c35a01d087b66c907ecb551566bda3458f9cd57

The root cause, as per git bisect: c9cf15576cdac755a65fb295e65aea40f6a4c5c7 (Hi nate! :wink:)

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/13430
