### ISSUE TITLE
History import button is (too) hidden

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#13419]
**Describe the bug**

Users on my instance struggle to find the import button for shared histories which is quite hidden next to the text `About this history`

![Screenshot from 2022-02-19 16-44-40](https://user-images.githubusercontent.com/25689525/154808045-c7dd78d8-8aea-44d8-882a-c76dc6ee19cb.png)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09

**To Reproduce**

1. Choose a history in `Shared Data` -> `Histories`

**Expected behavior**

Would be better to have it analogous to the import page that I get as an admin when I click on a history in an error report mail: 

![Screenshot from 2022-02-19 16-49-54](https://user-images.githubusercontent.com/25689525/154808109-d685df4e-cb0d-45a7-8779-96b47a7fd690.png)

**Comment by hexylena** [comment]
I think it should also be a primary-action colour to make it more visually distinctive, it *is* the primary action most people will do on that page.
