### ISSUE TITLE
enable_account_interface removes to much

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#13418]
**Describe the bug**

`enable_account_interface` removes the complete `Manage Information` point from the user preferences page.  Besides the possibility to change username (which I really would like to forbid on my LDAP managed instance) this page contains other important setting which I would like to keep (e.g. set dropbox API keys ...)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09
Commit: f40274f6b9

**To Reproduce**

1. Set `enable_account_interface` to `False`
2. Check user preference page

**Expected behavior**

Only possibility to change username / password / delete account is removed

**Comment by davelopez** [comment]
@bernt-matthias: Sorry it took me too long to get to this one :sweat_smile:

It should be fixed in https://github.com/galaxyproject/galaxy/pull/14363 let me know if this is what you expected and if I should target an older Galaxy version.
