### ISSUE TITLE
Empty fields in tool forms no longer tolerated

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#1341]
Latest release has resulted in a truly nasty bug: you can no longer have empty fields in tool forms. For example, in Naive Variant Caller it was possible to restrict regions to chromosome only. Now, it is no longer possible as it complains about empty `start` and `end` fields. 

![image](https://cloud.githubusercontent.com/assets/4291636/11844627/cf014392-a3dd-11e5-8ce4-3899575980f8.png)

This affects all tools I have tried

**Comment by nsoranzo** [comment]
Fixed by #1319.

**Comment by guerler** [comment]
Fixed by #1343.
