### ISSUE TITLE
[Feature request] Make rule builder old rule selector more useful by showing rule preview

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13428]
Sorting the old-rules list like in #13427 will be incredibly helpful, but the labels on the old rules are a bit useless unless you're either working on the same task repeatedly, or, knew what you were doing that week/month/etc which is a stretch for some of us.

![image](https://user-images.githubusercontent.com/458683/155111726-6cf792b4-78bb-4cd5-ad46-1035b70e4ec3.png)

Since we can generate this textual list probably pretty easily from the JSON rule definition, is there a chance that on hover of the old rule

![image](https://user-images.githubusercontent.com/458683/155112259-0c839747-0a65-4b82-918d-6c0e9b197547.png)

We could show a tooltip with the steps used in that rule? Maybe it could be e.g. the first 10 rules to not make the tooltip too big, each one on a new line for visibility/clarity. (Yes I guess you could just load the individual rules, but, I'm always hesitant to do that since I know half of them will give errors for missing/wrong columns.)

**Comment by assuntad23** [comment]
Adding on to this, perhaps, we should keep track of rules for Datasets and rules for Collections, since they have different requirements. We shouldn't allow a user to select rules for Collections, if they're working on Datasets, and vise versa.

**Comment by assuntad23** [comment]
Fixed with #13438
