### ISSUE TITLE
[22.01] Visualizations not build/updated properly when building client

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#13437]
**Describe the bug**
Visualizations are currently not available. It seems that the build system does not properly generate the visualization packages. Observed on dev and main.

**To Reproduce**
1. Go to 'Visualizations'
2. Try to visualize a dataset
3. See error

**Comment by mvdbeek** [comment]
I don't think it's all visualizations (the image annotator and text editor work for instance), and it would probably be fixed by running `yarn run gulp pluginsRebuild`.

**Comment by guerler** [comment]
Do the charts based bar-diagrams work for you?

**Comment by mvdbeek** [comment]
Source of the build failure is fixed in https://github.com/galaxyproject/galaxy/pull/13493
