### ISSUE TITLE
Clock app crashes when autocorrect bypasses max string length

### ISSUE THREAD

**Issue by TeradarGold** [galaxyproject/galaxy#13431]
I am using a Galaxy S8 running Android 9.

When I go into the Alarm section in the Clock app and I type in the maximum amount of words for Alarm name, if I use autocorrect on any word and the autocorrected word is larger than the original word, then upon bypassing the max length of the Alarm name the app crashes.

**Comment by ic4f** [comment]
Sorry, but this is the wrong repository: this is Galaxy the platform for scientific research, not Galaxy the phone.
