### ISSUE TITLE
galaxy-set-metadata: command not found

### ISSUE THREAD

**Issue by jeanetx** [galaxyproject/galaxy#13446]
This has been happening over the past two weeks.  I upload a 3 column bed file (no header) as I usually do.  The file is sorted by chr start stop.  The attributes of the uploaded bed file is set to bed.  When I run Merge overlapping regions, I get the following error on the output file:
![image](https://user-images.githubusercontent.com/75327078/155752096-4e026e87-d185-43df-ba96-fc029c4cb944.png)

When I set the attributes of the output file to bed file, the job that trys to auto-detect the attributes will run forever (a previous attempt ran for >1 week).

**Comment by mvdbeek** [comment]
Thanks for the report, this currently affects some very old tools that we keep installed for reproducibility (@natefoo, can you take a look at this ?). For the time being please use https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_mergebed/2.30.0 to merge intervals.
