### ISSUE TITLE
Limit size of displayed tool parameter values in datasets details view

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#13452]
When clicking on the `info` icon for an expanded dataset in the history, the dataset details view is displayed. This works well unless one of the tool parameters is a json blob. This json blob can be very large, making scrolling to the bottom difficult and also leading to a lagging user interface. It would be nice if we can also fix the flickering of this view in this context by use of the `LoadingSpan` component.

**Galaxy Version and/or server at which you observed the bug**
In dev and on main.

**To Reproduce**
1. Upload a significant number of datasets using the FTP uploader e.g. 100
2. Select a dataset from the history and click on its title
3. Click on 'info'
4. Notice that the response json parameter contains a large blob

This can also happen in other cases.

**Expected behavior**
The displayed content for tool parameter values should be limited. Maybe using `...` and allowing users to expand the content if needed by clicking.

**Screenshots**
![image](https://user-images.githubusercontent.com/2105447/155904809-98e086e0-4981-43d1-a952-7aaa3c73ed01.png)

**Comment by itisAliRH** [comment]
I can fix it :)
