### ISSUE TITLE
RStudio webpage fails to load

### ISSUE THREAD

**Issue by nakucher** [galaxyproject/galaxy#13465]
**Describe the bug**
Galaxy reports RStudio Job Info as running, but when the hyperlink to go to RStudio is clicked and a new tab opens, the webpage waits on the site then fails to load.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Search for RStudio tool, hit execute.
2. In top menu, under User, open Active Interactive Tools.
3. When job info changes to running, click hyperlinked RStudio text to launch.
4. See issue: new tab opens, but RStudio page fails to load.

**Expected behavior**
I expect the RStudio interface to load when the webpage is opened.

**Screenshots**
<img width="1302" alt="Screen Shot 2022-03-01 at 11 50 58 AM" src="https://user-images.githubusercontent.com/80000074/156214318-ef0e1941-2e37-4597-afdf-0441f33740ed.png">

<img width="1275" alt="Screen Shot 2022-03-01 at 11 51 41 AM" src="https://user-images.githubusercontent.com/80000074/156214332-db30be95-6e38-4d15-bc81-25219a1a4240.png">

**Additional context**
When I try to launch RStudio on usegalaxy.eu, I get the same thing I see for Jupyter on main (https://github.com/galaxyproject/galaxy/issues/13464), where the job in history is waiting to run indefinitely and the Active InteractiveTools page shows the Job Info as "stopped":
<img width="1188" alt="Screen Shot 2022-03-01 at 12 35 39 PM" src="https://user-images.githubusercontent.com/80000074/156219660-72275596-f405-4429-9972-740364c86c73.png">

**Comment by chiwwong** [comment]
I encountered the same issue. May I know if there is any update on this?

**Comment by bgruening** [comment]
@chiwwong on which server are you seeing it? Are you logged in?

**Comment by bgruening** [comment]
@chiwwong @nakucher I just tested this on EU and it works. Let me know if this is still a problem and fell free to reopen this issue.

**Comment by chiwwong** [comment]
I am at usegalaxy.org

But, indeed, I am also wondering how many rams are available at the R session.
