### ISSUE TITLE
ContentResolver.openFileDescriptor VERY slow after 2/1/2022 software update

### ISSUE THREAD

**Issue by cowand** [galaxyproject/galaxy#13489]
Phone:
Model name:	Galaxy A52 5G
Model number: SM-A526U1

Last Software update:
Version: A526U1UES4CVB2 / A526U1OYM4CVB2 / A526U1UES4CVB2
Size: 233.20 MB
Security patch level: February 1, 2022

After the update was done I noticed that one of my applications that had been previously running fine was now VERY slow. Since this was an application that I wrote I was able to use Android Studio and determine where the slow down occurred.

It occurred in some code that was getting the total and free size from a directory.
Prior to the software update the line below marked with comment "<---- VERY SLOW" took a few milliseconds.
After the update this line took 13.115 SECONDS to execute. 

// This code is just a portion of the original code. rootUri is valid and no exceptions occur.
ContentResolver resolver = mContext.getContentResolver();
long timeNowMs = TimeRecorder.timeNowMs();  // Added to time the next line
ParcelFileDescriptor parcelFileDescriptor = resolver.openFileDescriptor(rootUri, "r");  // <---- VERY SLOW
long duration = TimeRecorder.timeNowMs() - timeNowMs;  // Added to get duration

I was able to replace the impacted code by doing it a completely different way as shown below. This doesn't use ContentResolver, ParcelFileDescriptor, or FileDescriptor.
This code take 3ms.

long timeNowMs = TimeRecorder.timeNowMs();
File rootFile = new File(mRootStoragePath);
if (rootFile.isDirectory()) {
    long totalSize = rootFile.getTotalSpace();
    long totalFree = rootFile.getFreeSpace();
    long totalUsed = totalSize - totalFree;
    result = totalSize + "~" + totalUsed + "~" + totalFree;
}
long duration = TimeRecorder.timeNowMs() - timeNowMs;

So I've worked around the problem but something clearly changed in the system software update.

**Comment by ic4f** [comment]
Sorry, but this is the wrong repository: this is Galaxy the platform for scientific research, not Galaxy the phone.
