### ISSUE TITLE
Always copy galaxy.yml.sample to galaxy.yml ?

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13505]
I believe the primary reason we haven't done this in the past is that we had to set values for uwsgi, but that is not the case anymore. And because we had to set values we couldn't set new default values when that becomes necessary.

The current minimal galaxy.yml doesn't need any values, it could be as short as
```yaml
galaxy:
```

I'm mentioning this because `run.sh` registers galaxy.yml.sample with gravity, so if you just copy galaxy.yml.sample to galaxy.yml after having already run `run.sh` you need to know to use `galaxyctl rename <old_config_file> <new_config_file>`.

Given that we're only removing uwsgi in 22.05 we probably need to autodetect the presence of `galaxy.yml` file in gravity, but it'd be much cleaner if we automatically registered the non-sample file.

**Comment by dannon** [comment]
I ran into this when I wiped out my config dir in an instance that had previously been configured with gravity.  It defaulted back to running with the sample, but then when I *did* set up a new galaxy.yml with my proper configuration it didn't switch back over, which I didn't expect.
