### ISSUE TITLE
Vuex provider syncing strategy (in history context)

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13510]
We have 3 different renderless data approaches (I'm just listing the core classes here).

RxProviders: uses pouchdb to store and emit data from
SingleQueryProvider: resolves promise, optionally polls for updates and caches results  
StoreProviderMixin + SimpleProviderMixin: Mix these into a class with a load method and a storeItem method. The load method will fire and items will comes out of storeItem. It's easy to add vuex's chacheActions and mapGetters to these classes (could probably also be transplanted into the SingleQueryProvider, though I do like the modularity here)

I think the rxjs/pouchdb approach is dead at this point, but it had a lot of good ideas. Most importantly one monitor would load items into pouchdb, and any number of subscribers would get new items out of pouchdb. I think that is how we should watch for changes in a history and propagate the changes down to HDA and HDCA stores.

Here's one idea how we could do that (variations are plenty):
At the top level in a hierarchy you have a HistoryProvider that loads up a history, and then monitors for changes (using update_time, see discussion in`*`). All history items that come in are put into the the slot as usual, but they're also put into vuex stores for HDAs and HDCAs`**`.

Below the HistoryProvider we have DatasetProvider and CollectionProvider. These come into play when we request dataset details / collection details. They have a getter on the same HDA and HDCA store that the HistoryProvider manages, but they're also capable of requesting a detailed view via a store action. They do not poll for changes themselves, but they watch the item that they are putting into the default slot, and if the item they watch changes they get the details (again) via a store action.

This is my naive view of how we could do this. Here are some related thoughts:

`*` history updates and filters:

The HistoryProvider needs to respect the currently selected filters (`visible`, `tags`, `deleted`, `limit`, `offset` and all the other filters), at least on the initial load (or scrolling). The strategy outlined above requires that we can also get updates for currently hidden items (i.e for HDAs inside a collection). I see 3 alternative solutions here: 
 - We could skip the filters when polling for updates in the HistoryProvider and filter client-side. That's potentially a lot of unnecessary data transfer though, this could be a bad idea, especially when we're updating a big history for which we already have partial data
 - The API could return a list of ids for all HDAs / HDCAs that have been updated but that didn't match the filters. The HistoryProvider would then just touch the update_time for these items in the HDA and HDCA store and the DatasetProvider / DatasetCollectionProvider would re-fetch data for the items they are watching. These requests could probably be bundled and submitted to a batch endpoint.
 - The DatasetProvider / DatasetCollectionProvider components could emit events containing the ids of elements that they are currently watching (plus a beforeDestroy event if they stop watching something), and a top level `BatchItemProvider` could ask for updates to these items. This sidesteps the funny roundtrip in the second option, and would probably be more reasonable on the API side. I think I prefer this.

`**` HDA & HDCA stores

These stores could have a mix of summary and detailed items, and know how to merge these, so we could reduce the amount of data we have to serialize and transfer.

I think my proposal overall centers around the idea of reducing the number of polling requests and batching things together, while keeping the flexibility of having providers for single items where it makes sense. By putting history items into vuex stores we have a reasonable way to include data providers everywhere we need them, without having to manually coordinate polling (I'm thinking of invocation reports, dataset detail views etc). I also feel like there'd be easy ways to integrate this with Server Sent Events and websockets in the future, and moving from vuex to pinia. We might even be able to poll for multiple  / all history events at the top level slot.

**Comment by dannon** [comment]
First pass handled in #13512; we can continue to iterate.
