### ISSUE TITLE
Saving a workflow with missing tools not guiding sufficiently 

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#13524]
Trying to save an edited workflow that continues to have issues does not work with an error saying the issues need to be corrected first. However, as a user, I have no idea what issues remain and meanwhile I cannot save progress that I've made thus far on fixing the workflow. It'd be nice to show the actual list of issues in the modal.

<img width="991" alt="image" src="https://user-images.githubusercontent.com/338642/157787744-9a4eeee2-3160-4c25-a70a-ed82e8c607b6.png">

**Comment by mvdbeek** [comment]
There are red boxes with the missing tools, right ? Otherwise something was wrong with the Galaxy instance.

**Comment by afgane** [comment]
This is on usegalaxy.org with the [rna-seq-reads-to-counts.ga](https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/rna-seq-reads-to-counts/workflows/rna-seq-reads-to-counts.ga) training workflow. A (white) box shows up when you try to load a workflow but nothing when you try to save it.

**Comment by mvdbeek** [comment]
Oh, that message is wrong. There's no missing tool (just a tool version mismatch), this is weird.

**Comment by mvdbeek** [comment]
@guerler do you have some time to check this out ? Looks like a problem with the state inside the editor. If you flip the versions in the workflow @afgane posted for `featureCounts` and `Samtools indxstats` you can actually save the workflow.

**Comment by mvdbeek** [comment]
In particular it's the `content_id` that doesn't get updated. This is from the PUT payload:
```
annotation: ""
content_id: "toolshed.g2.bx.psu.edu/repos/devteam/samtools_idxstats/samtools_idxstats/2.0.2"
errors: null
id: "8"
input_connections: {input: [{id: "5", output_name: "output_alignments"}]}
label: null
position: {x: 2307.5086189038825, y: 1481.5416740648673, width: 66, height: 44.22002029418945,…}
post_job_actions: {}
tool_state: {input: "{"__class__": "ConnectedValue"}", __page__: null, __rerun_remap_job_id__: null}
tool_version: "2.0.3"
type: "tool"
uuid: "f645b890-43fc-4f67-ae9f-bb63622a035e"
workflow_outputs: [{output_name: "output", label: null}]
```
The tool_version is correct, the content_id is not

**Comment by mvdbeek** [comment]
Alright, that is actually a backend problem, we return the specified tool id, and not the actual tool id. I'll have a fix
