### ISSUE TITLE
Scroll wheel to workflow editor zoom

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#13525]
The workflow editor is a canvas in which one moves around a good bit, and panning is much faster when combined with ability to quickly zoom in/out. Instead of tying the mouse scroll wheel to the scroll bar in the workflow editor, how about using to zoom in and out? With that ability, click and drag to pan would be faster than using the scroll action to scroll.

**Comment by dannon** [comment]
@ahmedhamidawan Can you open a draft or WIP PR describing what you have so far?  I'd love to play with it.  This looks really promising, but I bet we can get it linked so we don't need to replace the button with a reset.
