### ISSUE TITLE
Bind IP address in config/galaxy.yml has no effect

### ISSUE THREAD

**Issue by TonyBolger** [galaxyproject/galaxy#13543]
**Describe the bug**
Bind IP address in config/galaxy.yml has no effect, and the default 127.0.0.1 listen address is always used regardless

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: release_22.01
Commit: 4e742cdfcf38a9ab30b94e9a3808a6cf800639ae

**To Reproduce**
1. Fresh install of release_22.01 branch
2. Copy config/galaxy.yml.sample to config/galaxy.yml
3. Modify http setting in uwsgi section of config/galaxy.yml with alternative IP, either a specific interface address (e.g. "192.168.1.1") or wildcard (e.g. ":8080" or "0.0.0.0:8080")
4. Start Galaxy using run.sh
5. Observe listening IP / port (e.g. with netstat -tanp) is still 127.0.0.1. Confirm as inaccessible with remote browser. 

**Expected behavior**
Listening on specified IP, accessible via remote browser

**Comment by mvdbeek** [comment]
Hey @TonyBolger, release_22.01 has not been released yet (but should happen later today or tomorrow). You'll want to update the branch to include the newer sample, and then copy the `galaxy.yml.sample` over again. On release_22.01 we are using Gunicorn as the webserver, and you can configure the the bind in https://github.com/galaxyproject/galaxy/blob/release_22.01/lib/galaxy/config/sample/galaxy.yml.sample#L50
