### ISSUE TITLE
Transiently Failing Tests

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1355]
Looks like we have solved the problems with transiently failing API tests in dev. There are a few remaining tests in other frameworks that have problems though:
- [ ] tool_shed.functional.test_0490_export_import_repositories.TestExportImportRepository.test_0010_export_repository_capsule
- [ ] tool_shed.functional.test_0490_export_import_repositories.TestExportImportRepository.test_0015_verify_exported_capsule
- [ ] tool_shed.functional.test_0490_export_import_repositories.TestExportImportRepository.test_0020_import_repository_capsule
- [ ] maxseconds (framework test)

**Comment by martenson** [comment]
the only actually failing test is 0010. the others cannot proceed without it

**Comment by jmchilton** [comment]
I'm going to call this closed with https://github.com/galaxyproject/galaxy/pull/1401, lets reopen if PRs containing those commits have problems though.
