### ISSUE TITLE
Pasted text content offers "Copy URI"

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13558]
**Describe the bug**
Paste some text in the upload box, then open the details view 
<img width="841" alt="Screenshot 2022-03-16 at 18 40 16" src="https://user-images.githubusercontent.com/6804901/158653646-295c7a60-56fa-4003-83cb-2d94a6c75e79.png">

**Galaxy Version and/or server at which you observed the bug**
22.01

**Expected behavior**
Should probably not show this ?

**Additional context**

**Comment by dannon** [comment]
xref #13610 (maybe)

**Comment by ic4f** [comment]
We had a discussion with @jmchilton (also see #13660) about this; but it's not clear yet what's the desired behavior here. When text is pasted, there's no trailing new line character, obviously. When the pasted content is uploaded and saved as a file, we add that character on the backend and inform the user via the message above (although the text is misleading, so that needs fixing anyway). On the one hand, we should be explicit about how we modify the data. On the other, hand, when a user pastes some data (that's not a url), they expect it to be saved as a file, and a trailing new line char is just one of the things that "makes a file" (as per POSIX, and given that most Unix tools expect that). I don't think we should inform the user that to save their pasted content as a file we added a trailing new line char. Besides, I don't think there should be any difference to the user between uploading data as a file or copying and pasting the same data (in the second case we're informing them that Galaxy has modified their data).

**Comment by mvdbeek** [comment]
> I don't think we should inform the user that to save their pasted content as a file we added a trailing new line char.

That's not really a user thing, that's a reproducibility thing. We should do that, and not doing that seems to contradict

> Besides, I don't think there should be any difference to the user between uploading data as a file or copying and pasting the same data (in the second case we're informing them that Galaxy has modified their data).

I was actually convinced that we tracked the transformations for file uploads as well. That we don't do this seems inconsistent, and IMO we should fix that, but it shouldn't affect the decision to upload pasted content as files one way or another. Either we intended to only track transformations for files uploaded via URIs, and tracking the uploaded content is a bug, or we want to track them all and it's a missing feature.

**Comment by dannon** [comment]
Stepping back from implementation details, I don't think it's unreasonable that pasted contents and uploaded files might be handled somewhat differently here.  For pasted contents, I think we should probably just always ensure that it ends with a newline and is a valid file.  I'm pasting a set of random text into a box *for Galaxy to make a file from* that I can use.  Nobody is thinking about newlines at the end of their clipboard blobs.

Files are completely different though; without checking extra boxes and/or being informed and having the manipulations tracked, I would not expect Galaxy to ever manipulate file contents -- whether that's cr/lf or space/tab conversions or adding newlines.

**Comment by ic4f** [comment]
> ...For pasted contents, I think we should probably just always ensure that it ends with a newline and is a valid file. I'm pasting a set of random text into a box _for Galaxy to make a file from_ that I can use. Nobody is thinking about newlines at the end of their clipboard blobs.

That's exactly my point! I think for pasted content that is not a uri the default behavior should be *creating a valid file*, and a trailing newline char is part of that.

> Files are completely different though; 

Of course, my point was for pasted content only. I'm not suggesting any change to how we track modifications made to files.

**Comment by mvdbeek** [comment]
> For pasted contents, I think we should probably just always ensure that it ends with a newline and is a valid file.

I disagree here. We've got the posix setting and the space to to tab setting, they should both work as expected and we shouldn't just hack in the newline.

**Comment by dannon** [comment]
@mvdbeek Don't show posix setting for pasted content?  I'm really wondering what use case is supported in *not* to add a newline here in pasted contents.

**Comment by ic4f** [comment]
> @mvdbeek Don't show posix setting for pasted content, then, maybe? I'm really wondering what use case is supported in _not_ to add a newline here in pasted contents. I'd put money on this being user error more often than it is intentional usage.

Not even user error: the only way to explicitly do it is to hit enter before leaving the textbox. I'd say it's expected behavior (+1 to what's the use case of creating a file w/o a trailing newline?)

**Comment by mvdbeek** [comment]
You want to paste some content without newline that you got from a tutorial or whatnot ? It's not an important usecase, I just don't understand why you want to remove a working feature ?

**Comment by mvdbeek** [comment]
You shouldn't treat pasted content as a URI! It's what I've said in the UI meeting, and I've mentioned that https://github.com/galaxyproject/galaxy/issues/13610 would fix it.

**Comment by ic4f** [comment]
So this issue is referring to the "copy uri" icon and tool tip, not the three lines of text?

**Comment by mvdbeek** [comment]
I don't know what that means. pasted content is not a URI, so you should definitely not see the copy URI button. You can fix this by creating a Blob from the pasted content if it does not look like a URI.

**Comment by ic4f** [comment]
@mvdbeek Sorry, we discussed it not at the meeting, but in the UI channel - see our discussion on Wednesday: we discussed this particular solution: "(1) so, the text "Upon ingestion..." should NOT be displayed, right? The reason it is displayed is becuase the pasted content does not contain a trailing EOF; manually adding it solves the problem. So, if that's the case, the solution would be to append EOF to pasted content if it is missing. Is this correct?" - you agreed. Did we misunderstand each other?

> I don't know what that means. pasted content is not a URI, so you should definitely not see the copy URI button. You can fix this by creating a Blob from the pasted content if it does not look like a URI.

I'm referring to the screenshot in this issue's description - the three lines of text "Upon ingestion...."

**Comment by mvdbeek** [comment]
I did suggest the blob in the meeting. Now I'm not gonna dictate how to implement the fix, hence I said "if that works", so we can see it in code. Now that I see it I do think that the blob is a better solution that closes 2 or 3 issues instead of just one.

**Comment by ic4f** [comment]
OK, so if pasted content is not uri(s), upload via tus  (#13610), otherwise no change to existing behavior.

**Comment by jmchilton** [comment]
https://github.com/galaxyproject/galaxy/pull/13669 fixes this. One can imagine all sorts of ways we could improve the tracking of non-URI data but I think getting to a state where we aren't tracking broken things in the database is the right start.

**Comment by dannon** [comment]
Reflecting from side conversation; I think we can also improve this a bit on the client with a few indicators showing  "This is a set of URLs" or "this will be created as a file with X, Y properties" right in the upload interface.  You still have one big box to paste into for convenience, but it can be a bit more informative without too much work.
