### ISSUE TITLE
Upload interaction fails after clicking Reset

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#1356]
- Click upload
- Choose a local file
- Click Reset (accidentally...its right next to the start button)
- Click upload local file again and reselect the same file, click Open --> Upload box is not populated.

Have to reload the Galaxy interface in your browser (not just upload) in order to upload the desired file.

release_15.10 and dev are tested as affected (probably farther back as well)

**Comment by guerler** [comment]
The selector doesn't trigger a file field change if you select the same file and I agree, this should be fixed. I'll work on it.
