### ISSUE TITLE
unclickable area in input select modal

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#13575]
The tool form input selector modal has an area that does not respond to clicks. If you click anywhere on the highlighted `div` outside of the actual "Data Libraries" text nothing will happen.

The cursor is changed to "pointer" on that div so I assume it is supposed to work the same as clicking on the text, or anywhere else in the row.

![Galaxy](https://user-images.githubusercontent.com/1814954/158977968-29376752-536f-48fb-b8df-5f5af0a9e224.png)

This is on usegalaxy.org

**Comment by mvdbeek** [comment]
Duplicate of https://github.com/galaxyproject/galaxy/issues/13542 ?

**Comment by martenson** [comment]
yeah
