### ISSUE TITLE
Link masthead menu version to /api/version

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#13574]
Under the user menu, there is a Galaxy version listed and it is linked to the release notes for the given version. How about linking it to `/api/version` instead as that endpoint contains more details about the specific version running on the given server? A link to the release notes can then be included in the `extra` field available at that endpoint if it's desired by the admin.

**Comment by dannon** [comment]
Discussed in UI/UX meeting.   Leaving this linked to the release notes is most appropriate, but we can add the extra version information in a tooltip.

**Comment by dannon** [comment]
xref #14461

**Comment by dannon** [comment]
The 'About this Galaxy' page in the help menu should cover this now.
