### ISSUE TITLE
Cleaner OIDC integration on login page 

### ISSUE THREAD

**Issue by martinwolst** [galaxyproject/galaxy#13592]
Galaxy version: 21.09 1.dev0

Currently when I set:
```
enable_oidc: true
oidc_config_file: config/oidc_config.xml
oidc_backends_config_file: config/oidc_backends_config.xml
```
and provide information in the oidc files to connect to my institutional Azure AD enterprise application, I get a 'Sign in with Azure' button added to the login page below the local login. When the user clicks the button they are correctly taken though authentication and dropped back to Galaxy when complete.

**Suggested change**

I only have Azure AD authenticated users and it would be less confusing for them if one of the following 2 options were possible (via a config in Ansible):

1. Have an option to disable the local login so only 'Sign in with Azure' is visible - this can be done by manually removing the local login section of: …/galaxy/client/src/components/login/Login.vue and rebuilding the client, but this is not a good solution for managing via Ansible.

2. Have an option to auto-redirect users to the OIDC authentication service, so they don't have to click any buttons in Galaxy to login, this would make it a much cleaner user experience in an institutional setting where users are all authenticated via OIDC.

**Comment by nuwang** [comment]
@martinwolst As I recall, this should already work. Try removing all authenticators from `auth_conf.xml` so it has an empty `<auth>` section. This should remove the local login option. Then, when you are down to only oidc provider, it should automatically redirect to the first available one.

**Comment by martinwolst** [comment]
@nuwang I hadn't been using an auth_conf.xml file, I'm using the OIDC authentication built in to Galaxy: https://galaxyproject.org/authnz/config/oidc/

If I add an auth_conf.xml with an empty <auth> block and configure it in galaxy.yml I get a 502 bad gateway error.

**Comment by nuwang** [comment]
Also add `require_login: true`

**Comment by martinwolst** [comment]
> Also add `require_login: true`

is configured, I suspect I'm using a different setup to what you are looking at

**Comment by nuwang** [comment]
@martinwolst I just tried it on a local clone and it works as expected.
![image](https://user-images.githubusercontent.com/2070605/159757089-2c2075a4-de7f-4766-b2ac-60b620933ee1.png)

**Comment by nuwang** [comment]
Here's the PR that adds this functionality: https://github.com/galaxyproject/galaxy/pull/9115
Can you check whether you have that commit included?

**Comment by martinwolst** [comment]
> Here's the PR that adds this functionality: #9115 Can you check whether you have that commit included?

I do indeed have commit 9646d59 and can meet all the conditions that should make it work but it doesn't, so it's possible there has been a regression on the way to v21.09

**Comment by ahmedhamidawan** [comment]
> > Here's the PR that adds this functionality: #9115 Can you check whether you have that commit included?
> 
> I do indeed have commit [9646d59](https://github.com/galaxyproject/galaxy/commit/9646d590d6f790a5a48adf57e6f30698b83247ab) and can meet all the conditions that should make it work but it doesn't, so it's possible there has been a regression on the way to v21.09

Hey @martinwolst, I was just wondering whether the basic idea of just setting `enable_oidc` to `true`, then seeing the OIDC option on the login page was working at your end. You can refer to the video in https://github.com/galaxyproject/galaxy/pull/13651, where I have demonstrated the minor change I have made to the registration page, but regardless of those changes, are you being able to see a similar result on your login page alone (after `enable_oidc: true`:
![image](https://user-images.githubusercontent.com/78516064/161150045-f3f2ab7d-74a4-4abb-9241-9a0c093af707.png)

**Comment by dannon** [comment]
@martinwolst Trying to help debug this one.  Can you share what exactly the auth_conf.xml looks like?

**Comment by martinwolst** [comment]
> @martinwolst Trying to help debug this one. Can you share what exactly the auth_conf.xml looks like?

I didn't have an auth_conf.xml at all on the original setup, although I'm guessing there are defaults that mean the local login is active/displayed.

**Comment by martinwolst** [comment]
> > > Here's the PR that adds this functionality: #9115 Can you check whether you have that commit included?
> > 
> > 
> > I do indeed have commit [9646d59](https://github.com/galaxyproject/galaxy/commit/9646d590d6f790a5a48adf57e6f30698b83247ab) and can meet all the conditions that should make it work but it doesn't, so it's possible there has been a regression on the way to v21.09
> 
> Hey @martinwolst, I was just wondering whether the basic idea of just setting `enable_oidc` to `true`, then seeing the OIDC option on the login page was working at your end. You can refer to the video in #13651, where I have demonstrated the minor change I have made to the registration page, but regardless of those changes, are you being able to see a similar result on your login page alone (after `enable_oidc: true`: ![image](https://user-images.githubusercontent.com/78516064/161150045-f3f2ab7d-74a4-4abb-9241-9a0c093af707.png)

With just oidc enabled and no odic config files (this is what I think you suggested?) it builds, but I get a 502 Bad Gateway when I try to access galaxy

**Comment by dannon** [comment]
@martinwolst I think the configuration you're looking for is what you had at the start (`enable_oidc` set, `oidc_config.xml`
and `oidc_backends_config.xml` both existing and configured for your Azure AD), and now that we know 'auth_conf.xml` was missing -- add that from `auth_conf.xml.sample`, and then delete the inner localdb authenticator.

So it could look something like this:
```
<?xml version="1.0"?>
<auth>
<!-- Disable local authenticator, forcing redirect to OIDC
    <authenticator>
        <type>localdb</type>
        <options>
            <allow-password-change>true</allow-password-change>
        </options>
    </authenticator>
-->
</auth>
```

**Comment by dannon** [comment]
@martinwolst Great, glad it's working, and thanks for testing against the playbook as well!
