### ISSUE TITLE
api documentation for usegalaxy.org is not accessible

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#13599]
per https://docs.galaxyproject.org/en/latest/admin/migrating_to_gunicorn.html there should be api documentation at https://usegalaxy.org/api/docs

This works locally, but is not hosted on Main despite running Galaxy version 22.01.rc1, commit [c14eca964941197dd47c37cfafef274d82ebf80e](https://github.com/galaxyproject/galaxy/commit/c14eca964941197dd47c37cfafef274d82ebf80e)

**Comment by dannon** [comment]
I think this is because main's still running uwsgi, not gunicorn yet.

**Comment by martenson** [comment]
Seems this is going to get resolved with update to playbooks then. Thanks @dannon!
