### ISSUE TITLE
Extract datasets fails for list of pairs

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#13607]
**Describe the bug**

When using a list of pairs as input to `Extract datasets` and one of the identifiers of the pairs I get

```
The server could not complete this request. Please verify your parameter settings, retry submission and contact the Galaxy Team if this error persists. A transcript of the submitted data is shown below. 

{}
```

A collection is created (only shown after a refresh of the history. That suggests to contain 3 elements. Clicking on it leaves me with a blank history pane. 

**Galaxy Version and/or server at which you observed the bug**

usegalaxy.eu

**To Reproduce**

Se above.

**Expected behavior**

Ideally the corresponding pair would be extracted. I do not understand the help text .. anyway in the worst case of misuse an empty collection should be created. 

**Additional context**

https://usegalaxy.eu/u/maze/h/failure-example

**Comment by davelopez** [comment]
> A collection is created (only shown after a refresh of the history. That suggests to contain 3 elements. Clicking on it leaves me with a blank history pane.

I've reproduced the issue by providing an invalid element index to `Extract datasets` in my case. The new collection with 3 items appears in green in the old history (and white in the beta history). If you click the collection effectively leaves a blank history pane with the following console error:

```
Uncaught TypeError: Unknown element type:
    at child._getItemViewClass (collection-view.js?3a73:91:1)
    at child._createItemView (list-view.js?516e:405:1)
    at eval (list-view.js?516e:368:1)
    at Module.map (index.js?e609:197:1)
    at child.eval [as map] (backbone.js?ab5c:1466:1)
    at child.renderItems (list-view.js?516e:367:1)
    at child._buildNewRender (list-view.js?516e:220:1)
    at child.render (list-view.js?516e:206:1)
    at child._expandDrilldownPanel (history-view-edit-current.js?494a:326:1)
    at child.expandedDrilldown (history-view-edit-current.js?494a:295:1)
```

The `element_type` for each collection element, in this case, is `null` breaking the collection view rendering.
The server returned a failed collection from:
```
GET http://127.0.0.1:8080/api/histories/4ff6f47412c3e65e/contents/dataset_collections/c9468fdb6dc5c5f1?view=element-reference&fuzzy_count=1000
```

```json
{
   "hid":27,
   "history_id":"4ff6f47412c3e65e",
   "history_content_type":"dataset_collection",
   "visible":true,
   "deleted":false,
   "job_source_id":"5969b1f7201f12ae",
   "job_source_type":"ImplicitCollectionJobs",
   "create_time":"2022-04-13T16:31:55.205536",
   "update_time":"2022-04-13T16:31:55.205546",
   "id":"c9468fdb6dc5c5f1",
   "name":"collection 13 (extracted element)",
   "collection_type":"list",
   "populated":false,
   "populated_state":"failed",
   "populated_state_message":"One or more jobs failed during dataset initialization.",
   "element_count":3,
   "type":"collection",
   "model_class":"HistoryDatasetCollectionAssociation",
   "tags":[
      
   ],
   "url":"/api/histories/4ff6f47412c3e65e/contents/dataset_collections/c9468fdb6dc5c5f1",
   "contents_url":"/api/dataset_collections/c9468fdb6dc5c5f1/contents/1e8ab44153008be8",
   "elements":[
      {
         "model_class":"DatasetCollectionElement",
         "id":"2fdbd5c5858e78fb",
         "element_type":null,
         "element_index":0,
         "element_identifier":"Galaxy-[F3D0_S188_L001_001.fastq].fastqsanger.gz",
         "object":null
      },
      {
         "model_class":"DatasetCollectionElement",
         "id":"c385e49b9fe1853c",
         "element_type":null,
         "element_index":1,
         "element_identifier":"Galaxy-[F3D1_S189_L001_001.fastq]",
         "object":null
      },
      {
         "model_class":"DatasetCollectionElement",
         "id":"f7bb1edd6b95db62",
         "element_type":null,
         "element_index":2,
         "element_identifier":"Galaxy-[F3D2_S190_L001_001.fastq]",
         "object":null
      }
   ]
}
```

The resulting collection is in `"populated_state": "failed"` so I assume the correct action here is just to fix the collection rendering in the history to appear as failed and not *green*?

**Comment by davelopez** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/13728
