### ISSUE TITLE
Add Proof Key for Code Exchange (PKCE) OIDC support

### ISSUE THREAD

**Issue by gecage952** [galaxyproject/galaxy#13605]
Hi, currently when using OIDC integration, I've found that there doesn't seem to be support for the Proof Key for Code Exchange (PKCE) spec that some OIDC providers require or encourage. The spec is detailed here: https://datatracker.ietf.org/doc/html/rfc7636. On a local fork, I've managed to put a rough fix for it, but I wanted to open an actual issue on here about it. Essentially, in the OIDC authnz code, alongside the nonce and state parameters, a code verifier and code challenge should be generated. The code challenge would be sent with the authentication url and the verifier should be stored for verification later. When the token exchange happens, the verifier would need to be sent along with that request, which would result in getting the appropriate token. It shouldn't be too big of change, but I'm not sure how you would want to handle the configuration of whether to use PKCE or not. Let me know if you need more info.

**Comment by bgruening** [comment]
@afgane @nuwang do you have any idea here?

Thanks @gecage952!

**Comment by afgane** [comment]
I'm not familiar with PKCE but if it's provider specific config option, I'd think adding an option to `oidc_backends_config.xml` would be reasonable. @gecage952, if you have something working, feel free to issue a PR and we can go from there. Thanks for brining this up.

**Comment by gecage952** [comment]
> I'm not familiar with PKCE but if it's provider specific config option, I'd think adding an option to `oidc_backends_config.xml` would be reasonable. @gecage952, if you have something working, feel free to issue a PR and we can go from there. Thanks for brining this up.

Yeah, no problem. I'll look into opening one up when I get the chance.

**Comment by gecage952** [comment]
Hey, again. I opened a PR related to this issue and put some more info inside of it: https://github.com/galaxyproject/galaxy/pull/13683 .  This is my first pr to this project, so please let me know what things I should change, improve, etc. Thanks!
