### ISSUE TITLE
Expensive Quay.io query repeated for every tool invocation

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#13619]
In a containerised tool setup, Galaxy is hammering quay.io, which then is blocked by them, causing tool invocation failures.

The issue is that `resolution_cache` is not being passed down through the `resolve()` call stack:
https://github.com/galaxyproject/galaxy/blob/9614a7ef53f54e253905901483efb5496451538a/lib/galaxy/tool_util/deps/containers.py#L314

`resolution_cache` is always None, causing `self.get_resolution_cache()` to be called for every `resolve()`.
`get_resolution_cache()` returns a new cache for every call, causing the result of https://github.com/galaxyproject/galaxy/blob/3a7e11f5bf89242dcd5ef5984c2d5b68e1850d4d/lib/galaxy/tool_util/deps/mulled/util.py#L59-L86 to be discarded and reevaluated every time.

I attempted to make `cache` a member of [ContainerRegistry](https://github.com/galaxyproject/galaxy/blob/9614a7ef53f54e253905901483efb5496451538a/lib/galaxy/tool_util/deps/containers.py#L218) so that the result of `get_resolution_cache()` would be the same instance between calls, but I feel like the resolution cache should be handled upstream with the `mulled_resolution_cache`.

I think there is an architectural component missing here that should also answer the question of when is this cache purged? Periodically or on reboot?

What happens when a tool is added to biocontainers and the cache hasn't been purged? Currently it will fail to find the container until then.

Discussion: https://gitter.im/galaxyproject/dev?at=623bb21cc43500250006917a

**Comment by mvdbeek** [comment]
The problem is that we're not using the persistent portion of the cache. Generating a new `ResolutionCache` instance for each request is intended, so we're getting up to date information from e.g listing images via `docker images` or listing conda environments from disk. 

 fix is pretty simple:
```diff
diff --git a/lib/galaxy/tool_util/deps/mulled/util.py b/lib/galaxy/tool_util/deps/mulled/util.py
index 307da3c49e..ca79530add 100644
--- a/lib/galaxy/tool_util/deps/mulled/util.py
+++ b/lib/galaxy/tool_util/deps/mulled/util.py
@@ -60,6 +60,8 @@ def _namespace_has_repo_name(namespace, repo_name, resolution_cache):
     """
     Get all quay containers in the biocontainers repo
     """
+    # resolution_cache.mulled_resolution_cache is the persistent variant of the resolution cache
+    resolution_cache = getattr(resolution_cache, "mulled_resolution_cache", resolution_cache)
     cache_key = "galaxy.tool_util.deps.container_resolvers.mulled.util:namespace_repo_names"
     if resolution_cache is not None and cache_key in resolution_cache:
         repo_names = resolution_cache.get(cache_key)

```
but I'll do a little bit of refactoring so we can test and reuse this more easily, and add an expiry option.
