### ISSUE TITLE
Upload pasted content via tus

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13610]
By turning the text into a file.

**Comment by jmchilton** [comment]
Just to clarify this for myself some... pasting content into usegalaxy.org results in a broken dataset source object content - it comes through as a URI instead of as pasted content.

```{"display_apps": [], "visualizations": [{"name": "editor", "html": "Editor", "description": "Manually edit text", "logo": null, "title": null, "target": "galaxy_main", "embeddable": false, "entry_point": {"type": "mako", "file": "editor.mako", "attr": {}}, "settings": null, "groups": null, "specs": null, "href": "/plugins/visualizations/editor/show"}, {"name": "graphviz", "html": "Graph Visualization", "description": "Cytoscape-based graph visualization plugin.", "logo": null, "title": null, "target": "galaxy_main", "embeddable": true, "entry_point": {"type": "mako", "file": "graphviz.mako", "attr": {}}, "settings": null, "groups": null, "specs": null, "href": "/plugins/visualizations/graphviz/show"}, {"name": "msa", "html": "Multiple Sequence Alignment", "description": "The MSA viewer is a modular, reusable component to visualize large MSAs interactively on the web.", "logo": "./static/plugins/visualizations/msa/static/logo.png", "title": null, "target": "galaxy_main", "embeddable": true, "entry_point": {"type": "chart", "file": null, "attr": {"src": "script.js"}}, "settings": [{"label": "Show conservation", "name": "conserv", "help": "Do you want to display a bar diagram indicating sequence conservation?", "type": "boolean", "value": "true"}, {"label": "Show overview box", "name": "overviewbox", "help": "Do you want to display the overview box below the sequence alignments?", "type": "boolean", "value": "true"}, {"label": "Show interactive menu", "name": "menu", "help": "Do you want to show a menu for interactive configuration?", "type": "boolean", "value": "true"}], "groups": null, "specs": null, "href": "/plugins/visualizations/msa/show"}], "resubmitted": false, "genome_build": "?", "history_content_type": "dataset", "dataset_id": "bbd44e69cb8906b51702acf5f55be7f9", "type": "file", "rerunnable": false, "uuid": "182cc7f2-5aa1-46ab-9f1d-6d22f4a4ffca", "meta_files": [], "hashes": [], "permissions": {"manage": ["5e288d0eaef4836f"], "access": []}, "validated_state_message": null, "hda_ldda": "hda", "creating_job": "bbd44e69cb8906b597f496e5ab9aa775", "download_url": "/api/histories/4eaf81a121213564/contents/bbd44e69cb8906b5413ccc26d66c4490/display", "data_type": "galaxy.datatypes.data.Text", "display_types": [], "create_time": "2022-04-04T19:31:36.401344", "misc_blurb": "1 line", "url": "/api/histories/4eaf81a121213564/contents/bbd44e69cb8906b5413ccc26d66c4490", "visible": true, "api_type": "file", "tags": [], "name": "Pasted Entry", "file_name": "/corral4/main/objects/1/8/2/dataset_182cc7f2-5aa1-46ab-9f1d-6d22f4a4ffca.dat", "validated_state": "unknown", "model_class": "HistoryDatasetAssociation", "created_from_basename": null, "purged": false, "id": "bbd44e69cb8906b5413ccc26d66c4490", "state": "ok", "extension": "txt", "peek": "<table cellspacing=\"0\" cellpadding=\"3\"><tr><td>mooo cow<\/td><\/tr><\/table>", "sources": [{"model_class": "DatasetSource", "id": 342474, "source_uri": "mooo cow", "extra_files_path": null, "transform": [{"action": "to_posix_lines"}]}], "annotation": null, "file_size": 9, "deleted": false, "accessible": true, "file_ext": "txt", "misc_info": "uploaded txt file", "history_id": "4eaf81a121213564", "type_id": "dataset-bbd44e69cb8906b5413ccc26d66c4490", "copied_from_ldda_id": null, "update_time": "2022-04-04T19:32:11.048544", "hid": 16, "metadata_dbkey": "?", "metadata_data_lines": 1}```

**Comment by mvdbeek** [comment]
Done in https://github.com/galaxyproject/galaxy/pull/13770
