### ISSUE TITLE
Visualizations are not built correctly when using custom visualization directory

### ISSUE THREAD

**Issue by elichad** [galaxyproject/galaxy#13620]
**Describe the bug**
When using custom `visualization_plugins_directory`, the plugins in that folder are not built into `/static/plugins/<visualization_plugins_directory>` during the client build. In the UI, the visualizer names are displayed under the Visualize tab, but trying to run them gives a 404 error for chart types, and pulls the plugin from `/static/plugins/visualizations` for the mako type (i.e. the wrong location)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01 

**To Reproduce**
1. Create a new folder (e.g. `config/plugins/test_visualizations`) and populate it with `common/ example/ editor/ visualizations.dtd additional_template_paths.xml` from `config/plugins/visualizations` (symlink or copy)         
2. In galaxy.yml set `visualization_plugins_directory` to the directory you created
3. Build the client/start galaxy (I used ./run.sh)
4. Upload some tabular data to galaxy
5. Go to the Visualize tab 
6. Try to launch **example** visualizer – see 404 error in console
7. Try to launch **editor** visualizer – should work, but checking the response to the `http://localhost:8080/plugins/visualizations/editor/show?dataset_id=59606d2a36c77a56` request shows that it is using the wrong script path.

**Expected behavior**
All visualizers from `visualization_plugins_directory` are built into `/static/plugins` **and** all visualizer templates point to that location at runtime.

**Additional context**
Manually adding the new directory to the paths in client/gulpfile.js causes the plugins to be built into the correct location, but mako type templates still point to the wrong place.

**Comment by dannon** [comment]
@dannon will follow up with @mvdbeek for showing where the config values are needed from javascript land
