### ISSUE TITLE
Admins cannot use datasets for jobs, despite being able to access datasets

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13627]
As an admin I can see histories via bug reports, and even import them (because I'm an admin) but the datasets do not allow access, so I cannot run jobs in this history, using these datasets, despite my ability to *see*, download, edit metadata on, and use those datasets:

Running a job gives:
![image](https://user-images.githubusercontent.com/458683/160376350-c8f292da-fcce-4aca-b9d6-92e0c36f2853.png)

Which hides the real error message in the JSON response:
![image](https://user-images.githubusercontent.com/458683/160376234-37f368ce-f0cb-4505-8c40-1e646e6efb3f.png)

I think

- dataset access checks for jobs should be waived for admins
- the error message should include what's returned from the API response

**Comment by mvdbeek** [comment]
We also shouldn't return the numeric dataset id, should be encoded. Th error message is UI/UX thing, the permissions handling is on the backend.

**Comment by hexylena** [comment]
Oh, didn't even notice the unencoded ID, yikes, yeah. that should be fixed.

**Comment by davelopez** [comment]
I'll have a look

**Comment by davelopez** [comment]
Just to make sure I'm following the correct steps for repro:

1. `user01` has a history with some datasets (I make sure it is private by using the `Make private` option)
2. Make the History *importable*
3. Log in as `admin`
4. Go to the history link generated in step 2 and **import the history**
5. Try to run any tool in one of the datasets

So if I follow those steps in 21.09 or 22.01 I can successfully run the tool. Should I follow a different path?

**Comment by hexylena** [comment]
Step 2 is not correct, that step is skipped. The history is never shared or marked importable. 

Instead, a bug report is submitted which gives the admin a link to the history via ID, and then that history can be imported.

**Comment by davelopez** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/13628

**Comment by hexylena** [comment]
thank you @davelopez this makes my life a lot nicer helping users with their bug reports, I really appreciate it!
