### ISSUE TITLE
Tool stdout/stderr is included in Job stdout/stderr

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13637]
That's due to https://github.com/galaxyproject/galaxy/pull/13557, and because of https://github.com/galaxyproject/galaxy/blob/393151a7b3704eb174823864ca36efe06b56597e/lib/galaxy/model/__init__.py#L488 the tool stdout / tool stderr is duplicated in the stdout / stderr property of the job. I suppose we should use the old redirect instead of tee for traditional DRMs, so we include the tools' stdout/stderr in the job stdout/stderr. kubernetes doesn't have a job error script, so doesn't have this problem.

**Comment by nsoranzo** [comment]
Just wanted to mention that the core of the issue seems that in /api/jobs/<JOB_ID>?full=True the job_stdout is duplicating tool_stdout instead of being empty/different.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/13642
