### ISSUE TITLE
Unable to drag datasets in multiple histories view on Safari

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#13638]
**Describe the bug**
During a training course using UseGalaxy.eu , a couple of trainees which were using Safari reported being unable to drag datasets in the multiple histories view.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09

**To Reproduce**
1. Go to https://usegalaxy.eu/history/view_multiple using the Safari browser
2. Try to drag a dataset towards the current history
3. Datasets don't seem to be draggable at all

**Additional context**
One user reported they was able to drag and drop datasets successfully at one point, but then it stopped working.

**Comment by itisAliRH** [comment]
@nsoranzo I tested with the latest `dev` branch, and it works.

![Untitled 2](https://user-images.githubusercontent.com/8046843/162588756-1fa73a06-cae6-4de1-b6dd-313156a42b71.gif)

**Comment by nsoranzo** [comment]
@itisAliRH Thanks for having a look, unfortunately I'm reporting on behalf of these users, so cannot give more details. Also for them it seems it started after

**Comment by itisAliRH** [comment]
@nsoranzo You're welcome :) This problem was fixed after the `21.09` release because it does not work for me at https://usegalaxy.eu/history/view_multiple.
