### ISSUE TITLE
Bug in Prefered language

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#13653]
Here is what is happening on my firefox both on usegalaxy.eu and usegalaxy.org:
When I go to the webpage it is in French. I log in and it stays in French while I chose English. When I go to User Preferences Manage information, now it switches to English...
![bug_language](https://user-images.githubusercontent.com/30404086/161215315-e2a84e6d-3fab-439b-85ff-8e9a56ffcc72.gif)

**Comment by hexylena** [comment]
I've seen something similar in reverse, a student had it set to english, but it kept reverting to chinese (browser specified language)

**Comment by hujambo-dunia** [comment]
_Just in case anyone wants to reproduce this issue, here are the steps:_

1. **If not already (in French-speaking country), change Firefox's settings to French**
2. In Firefox (ideally, "Private Window"), select: Preferences/Settings >> General >> Language and Appearance >> Language >> "...for displaying menus"=`Français`, "...for displaying pages"=`French-Switzerland`
3. **Change your Galaxy's settings to English**
4. Go to: `usegalaxy.org` or `usegalaxy.eu`
5. Select: Preferences >> Manage Info >> Language = `English` >> Save button
6. To verify, go to: www.google.com to confirm text is now in French
7. Logout of Galaxy
8. Quit Firefox
9. **Try to reproduce the bug**
10. Open up FireFox (ideally, "Private Window")
11. Go to: `usegalaxy.org` or `usegalaxy.eu`
12. Confirm Top-Horizontal Navigation appears in French
13. To go: Login Page
14. Confirm Top-Horizontal Navigation still appears in French
15. Complete Login Form: Username/Password >> Submit button
16. Confirm Top-Horizontal Navigation appears in English if there is a bug (if working, should appear in French)
17. Refresh the Page
18. Confirm Top-Horizontal Navigation appears in French

_This is a standard cookie/session setting issue with the locale settings being set on the 2nd page refresh. Fix forthcoming._
