### ISSUE TITLE
Conversion of Multi-History view

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#13677]
This needs to be swapped over to use the beta history component.  First pass should largely work the same way, but could address things like https://github.com/galaxyproject/galaxy/issues/13638 and provide a style refresh.

The current implementation (https://github.com/dannon/galaxy/blob/dev/client/src/mvc/history/multi-panel.js) is Backbone, so converting it to a proper component at the same time would be great.

**Comment by guerler** [comment]
I think the first step could be to build a multistory parent component:

![image](https://user-images.githubusercontent.com/2105447/170281379-0f6aca1a-f99b-49a7-8034-01d7af408f9f.png)
