### ISSUE TITLE
Inaccessible datasets return 200 OK, rather than 403.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#13679]
I had a user do the following procedure:

- right click save icon
- copy link
- `wget $link` in their terminal
- be confused by the HTML dataset (they only checked the file in a text editor briefly.)

I think this is incorrect behaviour, it should return 403 unauthorized rather than 200 OK + web page saying "inaccessible". This can be solved most simply with the following patch, but it loses the "pretty" template. I'm not familiar enough with the plumbing to figure out where I could add an optional return code to `show_error_message`, so, is this patch acceptable? Or does someone know better here how we could start passing along proper error codes

```
diff --git a/lib/galaxy/webapps/galaxy/controllers/dataset.py b/lib/galaxy/webapps/galaxy/controllers/dataset.py
index 39c0b0b950..8049423024 100644
--- a/lib/galaxy/webapps/galaxy/controllers/dataset.py
+++ b/lib/galaxy/webapps/galaxy/controllers/dataset.py
@@ -162,7 +162,7 @@ class DatasetInterface(BaseUIController, UsesAnnotations, UsesItemRatings, UsesE
         if not data:
             raise paste.httpexceptions.HTTPRequestRangeNotSatisfiable(f"Invalid reference dataset id: {str(hda_id)}.")
         if not self._can_access_dataset(trans, data):
-            return trans.show_error_message("You are not allowed to access this dataset")
+            raise paste.httpexceptions.HTTPForbidden(f"You are not allowed to access this dataset")
         if data.purged:
             return trans.show_error_message("The dataset you are attempting to view has been purged.")
         if data.deleted and not (trans.user_is_admin or (data.history and trans.get_user() == data.history.user)):
```

**Comment by davelopez** [comment]
I will suggest changing the download link to the API instead of the old client controller, something like: 
```
GET http://<galaxy-server>/api/histories/{history_id}/contents/{dataset_id}/display
```
This should take care of the proper error handling

**Comment by hexylena** [comment]
Ah, also a good option!

**Comment by hexylena** [comment]
I've had a go and couldn't make it work, so I leave it for someone more experienced in JS than me.
