### ISSUE TITLE
Deleted datasets won't delete 

### ISSUE THREAD

**Issue by hnote123** [galaxyproject/galaxy#13684]
I'm over my disk quota, but the datasets I've deleted won't permanently delete to free up the space. It says Internal Server Error (500)

![Capture](https://user-images.githubusercontent.com/102531973/162083707-01078763-b1ac-436a-b255-f50675916382.PNG)

**Comment by bgruening** [comment]
Can you please look into your Galaxy logs and tell us what you see if that error pops up? Thanks

**Comment by davelopez** [comment]
Hi @hnote123, thanks for reporting!
As @bgruening suggested, the traceback or error message in your server logs will be really helpful to figure out what is wrong, otherwise, there's not much we can do to fix it.
