### ISSUE TITLE
`NoVersionTableError` if `database_connection` is set and `amqp_internal_connection` is not

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#13689]
**Describe the bug**
If `database_connection` is set in `config/galaxy.yml` and `amqp_internal_connection` is not, Galaxy will use the same database for AMQP communications. When starting with no database, Celery starts first and populates the database with the `kombu_message` and `kombu_queue` tables. When Galaxy/gunicorn  tries to initialise the database, it's not empty and fails with the following traceback:

```
DEBUG:galaxy.config:Configuration directory is /usr/users/ga002/soranzon/software/galaxyproject_galaxy/config
DEBUG:galaxy.config:Data directory is /usr/users/ga002/soranzon/software/galaxyproject_galaxy/database
DEBUG:galaxy.config:Managed config directory is /usr/users/ga002/soranzon/software/galaxyproject_galaxy/config
Traceback (most recent call last):
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/webapps/galaxy/buildapp.py", line 59, in app_pair
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/app.py", line 534, in __init__
    super().__init__(fsmon=True, **kwargs)
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/app.py", line 477, in __init__
    super().__init__(**kwargs)
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/app.py", line 449, in __init__
    self._configure_models(check_migrate_databases=self.config.check_migrate_databases, config_file=config_file)
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/app.py", line 370, in _configure_models
    self._verify_databases(engine, install_engine, combined_install_database)
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/app.py", line 394, in _verify_databases
    verify_databases(
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/model/migrations/__init__.py", line 288, in verify_databases
    gxy_verifier.run()
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/model/migrations/__init__.py", line 344, in run
    self._handle_nonempty_database()
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/model/migrations/__init__.py", line 369, in _handle_nonempty_database
    self._handle_no_version_table()
  File "/usr/users/ga002/soranzon/software/galaxyproject_galaxy/lib/galaxy/model/migrations/__init__.py", line 465, in _handle_no_version_table
    raise NoVersionTableError(model)
galaxy.model.migrations.NoVersionTableError: Your galaxy database has no version table; manual update is required
2022-04-07 12:43:39,511 INFO exited: gunicorn (exit status 1; not expected)
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: dev (works fine on release_22.01)
Commit: 5935182af81d5f14e3a13bb6835a468062d90858

**To Reproduce**
1. `git clone https://github.com/galaxyproject/galaxy`
2. `cd galaxy/`
3. `sed -e "s|#database_connection: null|database_connection: 'sqlite:////tmp/universe.sqlite?isolation_level=IMMEDIATE'|" config/galaxy.yml.sample > config/galaxy.yml`
4. `rm -f /tmp/universe.sqlite`
5. `./run.sh --skip-client-build` 
7. See error

**Expected behavior**
Galaxy starts without errors.

**Additional context**
This was found when updating BioBlend CI tests to work on the Galaxy dev branch.

**Comment by nsoranzo** [comment]
@ic4f Can you take look if you have some time, please?

**Comment by ic4f** [comment]
Reproduced. Couldn't reproduce with postgres: celery starts first, tries to find the nonexistent database, restarts 6 times; but then galaxy takes over, creates and initialized the database and everything works. But with sqlite this errors.

I can fix this by simply treating a database as empty if it has those 2 tables - that's easy. Then all should work as expected. However, what about starting celery after the database has been initialized - would that be better? I don't know - just asking for your opinion. If that's not an option, I'll apply my fix.

**Comment by nsoranzo** [comment]
Not sure what's the best option here, to be honest. @mvdbeek any suggestion?

**Comment by mvdbeek** [comment]
Seems difficult to control the order of startup in a robust way, so if we can do

> I can fix this by simply treating a database as empty if it has those 2 tables

that would be my preference.

**Comment by nsoranzo** [comment]
I can still reproduce the issue as described above because the check [here](https://github.com/galaxyproject/galaxy/pull/13700/files#diff-52bd4967267f38562fc83c7bb780a7482e870420aaeb4795b4e864cd55fad15dR259) is wrong (there is an additional hidden table `sqlite_sequence` in `metadata.tables`).

**Comment by OP-0** [comment]
Good day, Galaxy developers,

It seems the issue persists. Unless, I have overlooked something in the documentation...
I would like to start the Galaxy project as a multi-user (production) server with nginx (not yet conf.). So far, I have just created the virtenv (python 3.7.4), then cd galaxy, and ./run.sh . As a postgres user I have created galaxydb and the galaxy user who has all the permissions to the galaxydb. 

Could I ask for your help, hints, please?

[gunicorn.log](https://github.com/galaxyproject/galaxy/files/10122360/gunicorn.log)
+
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "ON"
LINE 9:                     ON CONFLICT DO NOTHING;
                            ^

[SQL: 
            CREATE OR REPLACE FUNCTION fn_audit_history_by_history_id()
                RETURNS TRIGGER
                LANGUAGE 'plpgsql'
            AS $BODY$
                BEGIN
                    INSERT INTO history_audit (history_id, update_time)
                    VALUES (NEW.history_id, CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
                    ON CONFLICT DO NOTHING;
                    RETURN NULL;
                END;
            $BODY$
        ]
(Background on this error at: https://sqlalche.me/e/14/f405)

**Comment by nsoranzo** [comment]
@OP-0 What version of PostgreSQL are you using? Galaxy requires version 10 or higher.

**Comment by OP-0** [comment]
Overlooked that part... I am sorry, it is postgres (PostgreSQL) 9.2.24

**Comment by OP-0** [comment]
Positive. It solved the issue! Thank you very much @nsoranzo !
