### ISSUE TITLE
Workflow editor connectors are misaligned

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#1370]
This:

![image](https://cloud.githubusercontent.com/assets/4291636/11899972/d51e08d4-a570-11e5-8d0b-e9f538b59049.png)

happens is one switches focus (clicks on) other tool on the canvas. 

This happens on current test running 191f75407ed955b3b0836b7503616f664f0d0a73 using Chrome

**Comment by hexylena** [comment]
I get this all the time too. Seemed to be caused by tool titles changing # of lines when going from bold -> non-bold

**Comment by natefoo** [comment]
I'm told this issue is not anything new, and unless there are objections I'd like to move it to the 16.04 milestone.

**Comment by guerler** [comment]
Heads up, I'll work on this very soon.
