### ISSUE TITLE
Job submission responsiveness (in new history)

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#13731]
When we submit a job we don't explicitly kick an update to the new history.  It'd feel a lot snappier if we did, instead of waiting for the poll cycle.

Job submission could either emit an event that bubbled up -- or -- job submission could simply trigger the appropriate action in vuex.

**Comment by guerler** [comment]
Yes, I think it's the latter, the job submission should take the resulting response and trigger a store mutation to populate the history item.

**Comment by mvdbeek** [comment]
You could also clear the provider polling interval instead. If you're rapidly creating new jobs (think multiple small uploads for example) and you're firing off one request per created job you'll quickly see requests piling up and coming in out of order.

**Comment by guerler** [comment]
Thats an interesting idea, was considering different strategies on how to model this. Regulating the polling interval might be another good option.

**Comment by dannon** [comment]
First step would be to reset poll delay and request the update immediately.

**Comment by assuntad23** [comment]
@dannon @mvdbeek @guerler I don't feel confident picking up this task. I think someone else will be more suitable. I'm going to unassign myself.

**Comment by dannon** [comment]
@assuntad23 No worries; thanks for giving it a look!

**Comment by mvdbeek** [comment]
I'm gonna take this one, since I ran into a related bug
