### ISSUE TITLE
More filter options for histories in UI.

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#1373]
Currently, you can toggle between showing e.g. "normal datasets" with hidden and deleted. It would be nice if we could have additional filtering of the displayed history items, including error, running, queued, is/not a collection, and perhaps also by datatype, dbkey, etc.

One use case: I have a history with 7K items, but 3 failed job runs. I want to investigate what jobs failed and why, but manually scrolling through the list to find the 3 red boxes is not a good solution.

**Comment by carlfeberhard** [comment]
https://trello.com/c/lVTvylda/1518-ui-allow-filtering-by-deleted-hidden-state-in-history-panel-search

> and perhaps also by datatype, dbkey, etc.

https://wiki.galaxyproject.org/Histories#Advanced_searching

**Comment by blankenberg** [comment]
Ah yes, excellent, thanks :) `state=error` is what I needed.

**Comment by blankenberg** [comment]
It would be pretty sweet if we could have a small note with a link to that page popup when hovering over the search field or a question mark or similar.

**Comment by jmchilton** [comment]
:+1: That search bar is absolutely amazing, but not even Anton knew about the filtering options.

**Comment by carlfeberhard** [comment]
Hi, could whoever edited my comment please not edit my comments? Thanks.

> ... but not even Anton knew about the filtering options.

http://documentcloud.github.io/visualsearch/ 

I'm aware. Not enough time to put out all the fires at once (at least with our development model right now).

**Comment by bgruening** [comment]
@blankenberg can we close this one?
