### ISSUE TITLE
Highlight filter text field to improve visibility when filter has been selected

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#13748]

**Comment by dannon** [comment]
If there's a filter text make it more visible on hover, with highlight, etc.

**Comment by ahmedhamidawan** [comment]
Does this seem like the right direction?:
**Before:**

https://user-images.githubusercontent.com/78516064/164765085-703ee7e3-5a86-4521-a519-4ec96d234a53.mov

**After:**

https://user-images.githubusercontent.com/78516064/164765112-ce01baec-3e09-4a7a-9f73-133b44dd066a.mov

**Comment by davelopez** [comment]
For me the border it's so subtle that is hard to see :sweat_smile: 
Maybe changing the entire search box background to a light blue like when a dataset is selected?

**Comment by ahmedhamidawan** [comment]
> For me the border it's so subtle that is hard to see 😅
> Maybe changing the entire search box background to a light blue like when a dataset is selected?

Ah yes, my bad. I forgot to upload the screencast where I have that done already 🤦
