### ISSUE TITLE
Show only name tags in history dataset items not all tags.

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#13747]

**Comment by dannon** [comment]
Here's some history and more background of nametags:  https://github.com/galaxyproject/galaxy/pull/3704

The short answer is that 'name' tags are just regular tags that we display in a special way  (using a `#` shorthand, and unique coloration, and displaying them by default in the history, though that last bit is busted right now as they're *all* displaying).

Tags in general are just smple key:value pairs (and the keys can be hierarchical, but for nametags are not) like `key:value`, so any tag like `name:Samplename` would show up in the history like `#Samplename`.
