### ISSUE TITLE
Throttle the scrolling speed across different browsers to improve cosmetics and avoid flickering.

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#13741]
I haven't seen a lot of this, but @guerler mentioned Safari specifically seemed flickery?

We should test safari/chrome/ff (manual observation testing) and report back here on sizeable (1k+) histories.

**Comment by guerler** [comment]
https://github.com/galaxyproject/galaxy/compare/dev...guerler:scrolling_experiment?expand=1

https://user-images.githubusercontent.com/2105447/166107875-e92f6baa-b320-4876-ae57-644c771bd412.mov
