### ISSUE TITLE
switch our clipboard copy to JS

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1375]
is used in TS and possibly elsewhere
should switch to: https://clipboardjs.com/

**Comment by hexylena** [comment]
yep, in the "share this tool" link in Galaxy. I proposed using zeroclipboard at the time when I made the original PR for the share-tool popup. https://github.com/zeroclipboard/zeroclipboard since y'all have bower infra in place (as opposed to cargo-port), it might be a better choice since it'll have much wider browser usability than zeroclipboard.

**Comment by martenson** [comment]
zeroclipboard architecture is far from good imo (`an easy way to copy text to the clipboard using an invisible Adobe Flash movie` does not sound like 'easy way' to me :))

**Comment by hexylena** [comment]
Hah, it's needed for cross-browser support. I mean... it's what github uses, so you know they're making the effort for compatibility as opposed to that one dev's project. I agree that it feels like a huge thing to tack on "just a small .swf" for copying, but I think for Galaxy it'd be worth it.

**Comment by martenson** [comment]
wait, so are you saying the zeroclipboard would be superior to clipboard.js?

**Comment by hexylena** [comment]
yes. (probably)

**Comment by martenson** [comment]
Ha, ok now I remember why this got frozen. I hate Flash. :)

**Comment by zenorocha** [comment]
+1 for clipboard.js ;)

**Comment by martenson** [comment]
https://clipboardjs.com/ now supports all major browsers and systems so we should do this

**Comment by martenson** [comment]
xref: https://github.com/galaxyproject/galaxy/issues/5831 https://github.com/galaxyproject/galaxy/issues/1034 https://github.com/galaxyproject/galaxy/issues/4073

**Comment by martenson** [comment]
we have this now
