### ISSUE TITLE
galaxy creating invalid registry.xml in job working directory

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#13757]
$ git clone git@github.com:galaxyproject/galaxy.git
$ cd galaxy/
$ python3 -m venv .venv
$ sh run.sh
$ make client

Run a simple upload job, it ends quickly with:

```
Error parsing file /Users/marten/devel/temp/lxml/galaxy/database/jobs_directory/000/2/registry.xml
Traceback (most recent call last):
  File "/Users/marten/devel/temp/lxml/galaxy/lib/galaxy/util/__init__.py", line 275, in parse_xml
    tree = etree.parse
```

galaxy log:
```
  File "src/lxml/etree.pyx", line 3536, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1902, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "metadata/registry.xml", line 4
lxml.etree.XMLSyntaxError: Extra content at the end of the document, line 4, column 116585
```

The `/Users/marten/devel/temp/lxml/galaxy/database/jobs_directory/000/2/registry.xml` has 5MB, is invalid XML, and has 63 occurrences of `</registration>` -- parts of contents seem to be copied over many times. The file is supposed to have ~100kB and be valid XML.

[registry.xml.zip](https://github.com/galaxyproject/galaxy/files/8514212/registry.xml.zip)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: dev
Commit: [ed1c4c2](https://github.com/galaxyproject/galaxy/commit/ed1c4c2ef039f7525458a201885d40a769c57615)

macos 10.14

**Comment by mvdbeek** [comment]
Do you have more information ? I can't reproduce this on a fresh clone. How's your job handling set up ? Did you activate another Galaxy instances' virtualenv before the listed commands ? `echo $GRAVITY_STATE_DIR` should be empty before you start the process. 

> make client

that should've been taken care of by run.sh

**Comment by martenson** [comment]
> I can't reproduce this on a fresh clone. 

I believe this is somehow specific to my setup. I created this issue in order to try to get to the bottom of it in case this affects more users.

> How's your job handling set up ? 

This is fresh run so everything should be default/sample -- so local runner, gunicorn, galaxy.yml.sample

> Did you activate another Galaxy instances' virtualenv before the listed commands ?

I deactivated other virtualenvs/conda envs before running this.

> echo $GRAVITY_STATE_DIR should be empty before you start the process.

I did not check whether it was set before, but just did another run making sure it is unset and it ended up the same.

> that should've been taken care of by run.sh

I have env setting in place that disables that so I included the command for completeness.

**Comment by mvdbeek** [comment]
Any tool shed repositories installed ? Can you also paste the job logs and check `database/gravity/supervisor/supervisord.conf.d/_default_.d/galaxy_gunicorn_gunicorn.conf` for anything odd ?

**Comment by mvdbeek** [comment]
I haven't heard of this in a long time, I assume we fixed this some time ago.

**Comment by mvdbeek** [comment]
please, please, if you're a developer don't just throw away your instance, that way we're never getting to the bottom of it.

**Comment by martenson** [comment]
popped up again at https://matrix.to/#/!fVQwotRzniGGJbeUUi:gitter.im/$C_GwNAAHmSSIV1qi13t6ATteDkUTpUmKLies5LQyBM0?via=gitter.im&via=matrix.org while using planemo
