### ISSUE TITLE
Hidden/visible dataset fixes for new history

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#13750]
The lock icon for hiding/unhiding is not ideal; pick a new one.  Eye, though obvious, isn't a good choice either since it's what we use for display.

Additionally, 'showing hidden datasets' in a history is now much less obvious.  You have to open the advanced search panel and uncheck 'show visible'.  The language here is much clearer as "show hidden", I think, and we could maybe add a toggle button specifically for this when bulk panel is activated?

**Comment by mvdbeek** [comment]
I like what the old history does. Since https://github.com/galaxyproject/galaxy/pull/13752 restores the hidden counts it seems reasonable to restore the show hidden / show deleted overload on the counts.

**Comment by davelopez** [comment]
I agree with Marius, this may be more intuitive for current users. Also agree on using "Show hidden" will be much clearer for the search panel.

One thing to take into account is that toggling the hidden/deleted visibility in those counts should/must rewrite the actual search filter so the total counts for bulk operations are in synch.

**Comment by bgruening** [comment]
> One thing to take into account is that toggling the hidden/deleted visibility in those counts should/must rewrite the actual search filter so the total counts for bulk operations are in synch.

Very good point, I think we should change the user-visible filter as well. So that the user sees what is happening and gets encouraged to play around with the filter and learn the syntax.

**Comment by davelopez** [comment]
Yeah, definitely the `search text` and the `search panel` should be always in synch, I think this is part of #13742

**Comment by ahmedhamidawan** [comment]
I'd like to take this one, if possible!

**Comment by dannon** [comment]
New history doesn't have info on a dataset showing hidden/deleted either:

![image](https://user-images.githubusercontent.com/155398/164049776-396eab20-e327-4083-9026-03d086fe228e.png)

**Comment by ahmedhamidawan** [comment]
Feel like this one depends on which icon is decided on in https://github.com/galaxyproject/galaxy/pull/13802

**Comment by dannon** [comment]
@ahmedhamidawan Yep, the behavior is much better now and I definitely consider that part of it handled.

**Comment by dannon** [comment]
We swapped the icon in #14052, so this should be complete.
