### ISSUE TITLE
New collection turns green before final state

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#13763]
Issue reported in chat by @qiagu 

> Hello, one of our tools outputs a collection with discovered datasets. I observed that the collection turned to green before the list contents were ready. State was

```json
{
   "hid":907,
   "history_id":"5564089c81cf7fe8",
   "history_content_type":"dataset_collection",
   "visible":true,
   "deleted":false,
   "job_source_id":"51af33325a250fc7",
   "job_source_type":"Job",
   "create_time":"2022-04-18T17:45:08.621923",
   "update_time":"2022-04-18T18:16:06.571850",
   "id":"6fb17d0cc6e8fae5",
   "name":"xxxx on data 1",
   "collection_type":"list",
   "populated":false,
   "populated_state":"new",
   "populated_state_message":null,
   "element_count":null,
   "type":"collection",
   "model_class":"HistoryDatasetCollectionAssociation",
   "tags":[
      
   ],
   "url":"/api/histories/5564089c81cf7fe8/contents/dataset_collections/6fb17d0cc6e8fae5",
   "contents_url":"/api/dataset_collections/6fb17d0cc6e8fae5/contents/0d16186aaff7cbfd",
   "elements":[
      
   ]
}
```

**Comment by qiagu** [comment]
@davelopez  Thanks for addressing this issue promptly.
To give a little bit more details, the premature green seems to happen during setting metadata stage and only emerges in history (The admin job/dataset details still show grey color, which seems correct).

**Comment by qiagu** [comment]
After revisiting the issue more closely, I realize that issue was caused our job runner which changes the job state before setting metadata. Sorry, @davelopez , now feel free to close this issue. Thank you very much again for your time and quick response!

**Comment by davelopez** [comment]
No worries! Thanks for reporting back! :+1:
