### ISSUE TITLE
Updated tools disappear from tool search results

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#13775]
**Describe the bug**
Updated tools have been disappearing from tool search results until the next time galaxy is restarted.  Users write into the help desk because busco has disappeared, for example. The tool is in the panel somewhere, but does not show up in a search.  This is happening for maybe 90% of the tools updated on Galaxy Australia.  Occasionally an updated tool will still appear in a tool search.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Australia release_21.09
Test galaxy instance, release_22.01

**To Reproduce**
If you are an admin of a galaxy instance...
1: Install an old tool shed repository revision
2: Install a newer revision of the same tool shed repository
3: Search for the tool

**Expected behavior**
An installed tool will show up in search results when searched for by repository name

**Comment by dannon** [comment]
Fixed in #13776
