### ISSUE TITLE
Admin Job Lock (too easy to toggle)

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#13774]
The administrative job lock is entirely too easy to accidentally toggle.

![image](https://user-images.githubusercontent.com/155398/164305242-cf291484-6ec2-4bb1-864c-ce5da5b315c6.png)

As a standard form input the label toggles the value for the checkbox, but I'd suggest at least one of the following things:
1) Don't make the text toggle the switch
2) Require an (at least when disabling job dispatching) "are you sure you want to disable job dispatching?" confirmation.

**Comment by hexylena** [comment]
I'd vote for 2! (And maybe a message_box for admins indicating the lock?)

**Comment by martenson** [comment]
It is not just the in-line label that triggers the silent settings, the above one does that too.

![lock_dispatch](https://user-images.githubusercontent.com/1814954/167627426-e382ced1-de6a-4def-abfc-49a98bcd237e.gif)

**Comment by mvdbeek** [comment]
I don't think this is critical for the release, I'll bump this
