### ISSUE TITLE
Fix Pulsar/Galaxy Dependencies

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1378]
- [x] Fix pulsar to use `galaxy-lib` (will ensure its use of `galaxy.util` is correct).
- [x] Import whole pulsar project as a wheel and eliminate `lib/pulsar`.
- [x] Implement an embedded pulsar job runner.

**Comment by jmchilton** [comment]
WIP @ https://github.com/jmchilton/galaxy/tree/pulsar_as_lib. It works we just have to get the wheel figured out, somehow we need to install with `--no-deps` or build a modified version of the wheel.

**Comment by jmchilton** [comment]
Actually I think what I will do is create a pulsar-lib with various optional dependencies including galaxy-lib if `standalone` flagged. Then galaxy-app version X will just be empty except depending on `galaxy-lib[stabndalone]==X`.  Should just be one more setup and Makefile file in pulsar.

Ping @natefoo in case he has any advice.

**Comment by natefoo** [comment]
Is this just so `galaxy-lib` will not conflict with Galaxy's built-in lib directory? If so, this will only be a problem until Galaxy itself switches to `galaxy-lib`.
