### ISSUE TITLE
Feature Request: Ability to use minimap to move around workflow area

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1382]
With gigantic workflows (and laptop touchpads) it would be nice if I could click an area of the minimap and go there.

![selection_526](https://cloud.githubusercontent.com/assets/458683/11940997/fec3ea0e-a7f1-11e5-865a-e4e2cd15fe4b.png)

**Comment by blankenberg** [comment]
You can currently click and drag, but just clicking or touching to move the center makes a lot of sense too.

**Comment by hexylena** [comment]
Oh, hey, you can click and drag. Perhaps a hand icon would  be useful to indicate that such an interaction is available? (Note that clicking and dragging only works if over the blue square. Clicking + dragging outside of the square results in no response)

**Comment by martenson** [comment]
Click to zoom is still very reasonable feature, I remember I missed it too when I worked with WFs.

**Comment by pvanheus** [comment]
Perhaps drag a box to zoom on the minimap? Some kind of zoom would be useful.

**Comment by dannon** [comment]
This was completed in #1843

**Comment by hexylena** [comment]
Thanks @dannon!!
