### ISSUE TITLE
When I started run.sh, I had this problem.

### ISSUE THREAD

**Issue by hayeon-pak** [galaxyproject/galaxy#13822]
Hi :)

**Describe the bug**
I wanted to install galaxy tool in my linux server.
So I processed in the below order.
` git clone -b release_22.01 https://github.com/galaxyproject/galaxy.git`
`git fetch origin && git checkout release_22.01 && git pull --ff-only origin release_22.01`
`sh run.sh`

And then, the following process was repeated continuously for two days.
![image](https://user-images.githubusercontent.com/99008387/165685425-f0cb10a7-58e7-4737-8ff2-f7c4170ab94d.png)

What I have to do?

Thank you.

**Comment by bgruening** [comment]
Go to localhost:8080 and enjoy Galaxy. ☺️

**Comment by hayeon-pak** [comment]
Oh...!!!
I thought it should to install dependencies or something more.
So, I just waited for this process to finish... lol
Thank you so much :)

But, I have one more question.
I added 8080 port to EC2 because I am using AWS. And I tried to connect to http://mylocalhost:8080.
But, I can't connect this site. 
How process I have to try?

Thanks :)

**Comment by dannon** [comment]
If it's not working then it's possible something went wrong earlier in startup.  Can you checck through the previous log statements in `gunicorn.log` (or just start it over and watch)?  What you're looking for in the logs to show a successful server start (prior to the periodic tasks) is something like this:
```
[2022-04-28 08:17:39 -0400] [17110] [INFO] Starting gunicorn 20.1.0
[2022-04-28 08:17:39 -0400] [17110] [INFO] Listening at: http://127.0.0.1:8080 (17110)
[2022-04-28 08:17:39 -0400] [17110] [INFO] Using worker: galaxy.webapps.galaxy.workers.Worker
[2022-04-28 08:17:39 -0400] [17155] [INFO] Booting worker with pid: 17155
```

Once you check that, if it looks like it should be working, then I would try from machine itself hitting `http://localhost:8080/api/version` to see what the response is.  That'd tell you if this is maybe EC2 port mapping or local to Galaxy.  If Galaxy is up you should see a response like this: (I use httpie here, but curl/wget/etc would be the same)
```
$ http http://localhost:8080/api/version
HTTP/1.1 200 OK
content-length: 48
content-type: application/json
date: Thu, 28 Apr 2022 12:22:19 GMT
server: uvicorn
x-frame-options: SAMEORIGIN
x-request-id: e7e85aadf12f4b74b773e17bd41d7819

{
    "version_major": "22.05",
    "version_minor": "dev0"
}
```

**Comment by hayeon-pak** [comment]
Thank you for reply.

In my latest log, I can find

> [2022-04-29 00:57:53 +0000] [14096] [INFO] Starting gunicorn 20.1.0
[2022-04-29 00:57:53 +0000] [14096] [INFO] Listening at: http://127.0.0.1:8080 (14096)
[2022-04-29 00:57:53 +0000] [14096] [INFO] Using worker: galaxy.webapps.galaxy.workers.Worker
[2022-04-29 00:57:53 +0000] [14256] [INFO] Booting worker with pid: 14256

So, I think galaxy server is successfully started.
And then, I tried
`http http://mylocalhost:8080/api/version`

I get just below line
> http: error: Request timed out (30s).

help...😭

**Comment by dannon** [comment]
I noticed you put `mylocalhost` again -- what url exactly are you using?  And, you're executing this command from the machine that Galaxy is running on, right?  What if you explicitly use `http://127.0.0.1:8080/` ?

**Comment by hayeon-pak** [comment]
My url is 'http://3.35.189.107:8080/'
'3.35.189.107' is remote host number of my sever.

My process was
1. `sh run.sh`
2. In web browser, I typed 
> http://3.35.189.107:8080/

**Comment by dannon** [comment]
Got it, that's what I was trying to debug -- so that's not going to work as it is currently set up since Galaxy is only listening to local connections.  .  So, right now, that Galaxy instance is only listening to local connections with the default configuration.  Look for this block in your galaxy.yml:
```
  gunicorn:

    # The socket to bind. A string of the form: ``HOST``, ``HOST:PORT``, ``unix:PATH``, ``fd://FD``. >
    bind: localhost:8080
  ```

And you'll want to change that `localhost` to a more permissive bind (like `bind: 0.0.0.0:8080` to listen on everything)

**Comment by dannon** [comment]
@hayeon-pak Going to go ahead and close this one out, but feel free to reopen if you have more problems!
