### ISSUE TITLE
suggestions for the advanced history query menue

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#13840]
This is the current advanced history filter:

![grafik](https://user-images.githubusercontent.com/469983/166155203-a2beb838-daed-4644-8339-3f52c9159bab.png)

It would be nice if we could:

* [ ] make the state filter a select box, I assume we only have a fixed set of allowed states
* [ ] the index filter could be a two-handed slider

![grafik](https://user-images.githubusercontent.com/469983/166155184-5515b497-65c9-42ce-ae20-1e5cc98d8d6c.png)

* [ ] the time filter could maybe also be a two-handed slider, or at least we should offer an example of how a `time` looks like
* [ ] I don't know if we can save a `set()` of all extensions in a history, if this is possible it would be nice to turn the extension filter also into a select box - if this is not scalable, we could auto-complete the extensions I think.
* [ ] is the show-deleted / show-visible boolean needed in this view? Should we remove it here?

**Comment by ahmedhamidawan** [comment]
Made changes to state and creation time fields:

https://user-images.githubusercontent.com/78516064/167506553-a22e102e-edba-48e6-b5f5-7103586b6015.mov

I hope that's the idea. Still working on hid
