### ISSUE TITLE
galaxy packages __init__.py: RAW_CONTENT_URL points to non-existent repos

### ISSUE THREAD

**Issue by mr-c** [galaxyproject/galaxy#13859]
https://github.com/galaxyproject/galaxy/blob/3bf949699967091c5bf86770efa6b387eddafd7d/packages/tool_util/galaxy/project_galaxy_tool_util.py#L9  → https://raw.github.com/galaxyproject/galaxy-tool-util/master/ → 400 invalid request; https://github.com/galaxyproject/galaxy-tool-util → 404

Doesn't seem to be used anywhere

Also, what is the story behind the "PROJECT_USERAME" typo?

I'll happily send a PR to remove these from all the packages, if it would be well received

**Comment by nsoranzo** [comment]
I think both the `PROJECT_OWNER = PROJECT_USERAME = "galaxyproject"` and the `RAW_CONTENT_URL = f"https://raw.github.com/{PROJECT_USERAME}/{PROJECT_NAME}/master/"` lines can be safely removed from the `project_galaxy_util.py` files inside `packages/` . PR welcome!

**Comment by mr-c** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/14040
