### ISSUE TITLE
unnecessary page reload on the workflow list page

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#13854]
On the workflow list page, http://127.0.0.1:8080/workflows/import we have page reloads when you click `create` or `import`.

![grafik](https://user-images.githubusercontent.com/469983/166493028-072aeab6-3429-48ed-8c20-b8cbcd83712a.png)

I don't think those are necessary. With all the love that has been put into this page, it would make every presentation of this part of Galaxy smoother if we can remove the reloads.

**Comment by davelopez** [comment]
xref #13984

**Comment by martenson** [comment]
this is fixed now, thanks!
