### ISSUE TITLE
Combine tag display and tag editing components in history

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#13865]
There does not seem to be a need to show the tags and the tags editor separately in the history. Previously this was necessary since only name tags where constantly shown, but since we decided to show all tags those two components should be consolidated.

**Comment by ahmedhamidawan** [comment]
That's how `StatelessTags` show up by default so it would be a really quick and easy change

**Comment by ahmedhamidawan** [comment]
Right direction? Note that tags have been removed from `DatasetActions`

https://user-images.githubusercontent.com/78516064/166827403-327fa383-dad2-4bc1-825f-e8bd95822f32.mov

**Comment by dannon** [comment]
Hrmm.  The 'add tag' icon is more jarring and adds more clutter than I anticipated there.  Swapping the color and sizing to what we've standardized to for the other content item icons would help.  Maybe we also only show it on hover of the tag editor?

**Comment by davelopez** [comment]
Or show it only when the dataset is expanded so you are more explicitly "editing this dataset"?

**Comment by dannon** [comment]
@davelopez Great idea, I like that even better than just showing it on hover.

**Comment by dannon** [comment]
@ahmedhamidawan Yeah, there's some magic in there for customizing when/how we show the tag icon based on styles; I've had to touch it before.  Ping me if you run into problems

**Comment by ahmedhamidawan** [comment]
Hows this?

https://user-images.githubusercontent.com/78516064/166967956-17a8645e-f913-4161-bd42-9acb23d4acc2.mov
