### ISSUE TITLE
Workflow editor throws console error when deleting node

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#13886]
**Describe the bug**
When deleting a selected node in the workflow editor a console error is thrown and the right panel remains empty, previously the workflow options were shown.

**Galaxy Version and/or server at which you observed the bug**
Current dev.

**To Reproduce**
1. Go to the Workflow editor
2. Create a nodes
3. Delete a node, notice the console error and empty right panel

**Expected behavior**
Should show, no node selected or select another node.

**Screenshots**
![image](https://user-images.githubusercontent.com/2105447/167303772-cb11692d-c9a3-4fed-a121-6bdb4d8ba4d8.png)

**Additional context**

**Comment by hujambo-dunia** [comment]
Note: error occurs in Safari only.
_(Restated: error is suppressed/corrected/automatically accounted for in Chrome/Firefox.)_

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/13912
