### ISSUE TITLE
Dataset info view can freeze user interface

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#13888]
**Describe the bug**
When clicking on the info icon for datasets which were part of large jobs with many other input datasets, the ui can freeze.

**Galaxy Version and/or server at which you observed the bug**
In dev.

**To Reproduce**
1. Upload a large number of FTP files e.g. 500
2. Click on `info` icon of one of the uploaded files
3. Notice how the UI becomes very slow

**Expected behavior**
The dataset info screen should quickly appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/2105447/167304115-dc6ee209-717f-4b03-9c14-9fbc61ad1963.png)

**Comment by dannon** [comment]
xref #13882; we need a properly paginated endpoint for getting outputs of a job.
