### ISSUE TITLE
Bulk Operations: ensure consistent purged state

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#13889]
<del>It seems directly purging datasets through the bulk operations endpoint does not ensure the dataset is also flagged as `deleted` for consistency.</del> It does, checked now with a test.
Also:
- Make sure that trying to **undelete** a `purged` dataset does not have any effect.
- **Purging** already `purged` datasets will have no effect (and we shouldn't expect a history change).
- Purging a `dataset_collection` should purge all its contents.

**Comment by mvdbeek** [comment]
As a note, 

> does not ensure the dataset is also flagged as `deleted` for consistency.

that might happen in Celery at any point after the request. I'm not sure how you want to deal with this, but that's probably an important gotcha. Set `enable_celery_tasks: true` in galaxy.yml and start Galaxy with run.sh to see that behavior.

**Comment by davelopez** [comment]
> that might happen in Celery at any point after the request. 

is it a really really bad idea to flag the items as `deleted` and `purged` in the database before offloading the actual *purge* task to celery? :trollface:
that way we don't even need to wait for the celery task to finish to return from `Processing...` status.

**Comment by mvdbeek** [comment]
> is it a really really bad idea to flag the items as `deleted` and `purged` in the database before offloading the actual _purge_ task to celery? :trollface:

No, I think that would be fine, although from the backend perspective ideally all of this would happen in Celery (deleting and purging).
