### ISSUE TITLE
Allow anonymous users to import histories from Shared Data - Histories

### ISSUE THREAD

**Issue by vazovn** [galaxyproject/galaxy#13896]
**Describe the bug**
When anonymous users try to import a shared history from `Shared Data` - `Histories` an error is thrown : "History could not be imported. ..." See attached file.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: {"version_major": "21.05", "version_minor": "1.dev0"}
Commit: NA

**To Reproduce**
1. Go to 'https://galaxy.immuneml.uiocloud.no/'
2. Stay unregistered and go to Shared Data > Histories
3. Select a history and click on the "+" in the upper right corner to import

**Expected behavior**
The expected behaviour would be to have the history imported to the anonymous user's history pannel.
_Would be nice if this feature is optional._ 
The expected behaviour was present in version 20.05, follow the same steps here : 'https://galaxy.immuneml.uio.no/' for a working example.

**Screenshots**
Attached
![anonymous-history-import](https://user-images.githubusercontent.com/11718320/167613694-6a697493-3886-42ec-9463-ee1ec2d04c9e.png)

**Additional context**

**Comment by nsoranzo** [comment]
Seems to work fine on 21.09 ( https://usegalaxy.org.au/ ) ?

@mvdbeek Before importing, the pop-up already warns the user: "As an anonymous user, unless you login or register, you will lose your current history after importing this history." , which I think it's fine (i.e. no need for the feature to be optional).

**Comment by vazovn** [comment]
I am fully happy with this. And _only_ one history is also fine. Just that we can not make it to the yellow pop-up.

**Comment by sveinugu** [comment]
The bug is present also in http://usegalaxy.eu, which is version 22.01

**Comment by sveinugu** [comment]
So looking closer at the error messages reveals that there is a difference between 21.05 and 22.01. The error message in 21.05 is:

"Uncaught exception in exposed API method:", "err_code": 0
    
In 22.01 the error message seems to be intended, however the error message does not harmonize with the text in the yellow box:

“You need to be logged in to create histories.", "err_code": 403001

Being able to import test data anonymously is important for the peer review process of publications related to Galaxy tools/servers.

**Comment by davelopez** [comment]
Yes, this is a regression and we are working on a fix, thanks for the details, and sorry for the inconvenience.
