### ISSUE TITLE
Use Galaxy registered email id for error reports by default

### ISSUE THREAD

**Issue by pavanvidem** [galaxyproject/galaxy#13894]
Here is a screen shot of the current error reporting form:
![image](https://user-images.githubusercontent.com/5268277/167450031-b3d731f7-2f0b-4f74-b4e1-b181641cb7ca.png)

Error report form allows manually entering an email address. A wrongly entered email id in **Please provide your email** field can result in:
- spamming a random email
- user might never get the reply from the administrators. This case can be very confusing, and happened on EU instance. A user always entered a wrong email address while sending a bug report. This could be because of browser's auto-filling feature. We answered the user (replied to the incorrect email id that was entered during the reporting) but user had been reporting the same error over and over again because our reply never reached the user's correct email id.

**A possible solution:**
A copy of the error report should always be sent to the Galaxy registered email id by default. This custom email field is only used if the user wants to add any additional email ids to forward error report to.

**Comment by dannon** [comment]
Discussed in @galaxyproject/wg-uiux; we will prefill/disable email field indicating the logged in user.  If anonymous, show a note about requiring registration for any response/correspondence.

**Comment by pavanvidem** [comment]
That sounds fair to me. They can analyze data anonymously but have to register to get support.

**Comment by pavanvidem** [comment]
Thanks for implementing this!
