### ISSUE TITLE
Offline installer (or method) of galaxy

### ISSUE THREAD

**Issue by MapleHe** [galaxyproject/galaxy#13903]
Hi, developer,

If there is any offline method to install galaxy on computing server without internet access ? I've searched for keywords like "offline installer", "offline", "install galaxy without internet access", but there seems no releted solution. The merely one post I've found that mentions the topic is [here](https://lists.galaxyproject.org/archives/list/galaxy-user@lists.galaxyproject.org/thread/P6PH76KY575X7BKILTNVCPFTIWEGNOGM/) but the link it provides has been invalid.

I'm expecting something like

```bash
# on local machine
sh run.sh --install --download-only

# on computing server
sh run.sh --install --offline --cache /path/to/downloaded/files
```

As we know, miniconda and python-pip both support offline packageinstallation.

I've found [galaxy-tool-util](https://anaconda.org/bioconda/galaxy-tool-util/files) in conda repo, which seems more like an auxiliary testing toolkit.

**Comment by hexylena** [comment]
assuming the same path + python version, yeah, good point @nsoranzo

**Comment by MapleHe** [comment]
Thank you for your suggestions and tips. So there is no "normal" way to offline install Galaxy. 

I'm trying to package these related directories as suggested and will see if it works. 

(It's weird that after the my first try of `run.sh` and then the deletion of first installation, I cannot reinstall galaxy now)

I shall close the issue now. Please comment if anyone has any other suggestion, or any new update are committed.

**Comment by hexylena** [comment]
The other alternative is use a docker image of galaxy, there you can download the image and move it between machines. It should come with base dependencies for the system.

Tool dependencies are another issue, there's no easy way to move those either.
