### ISSUE TITLE
CONVERTER_uncompressed_to_gz writes to input dir

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#13916]
**Describe the bug**
CONVERTER_uncompressed_to_gz uses bgzip to create a compressed version of the input, and writes that to the correct output path, but it also generates an index that is written next to the input because of the use of the `-i` flag, which fails when the input dir is not writeable (such as when running in a container). Per the [bgzip documentation](http://www.htslib.org/doc/bgzip.html):

> **-c, --stdout** Write to standard output, keep original files unchanged.
>
> **-i, --index** Create a BGZF index while compressing. Unless the -I option is used, this will have the name of the compressed file with .gzi appended to it.
>
> **-I, --index-name *FILE*** Index file name.

We are using the `-c` option to write to stdout, and bgzip has no knowledge of what the compressed filename will be in this case, and is using what it would be if the file were being compressed in-place (without `-c`). We need to add the `-I` option to set the filename if we actually want the index file. But - do we? If we do, it should probably be a `MetadataFile`.

**Galaxy Version and/or server at which you observed the bug**
22.01.1.dev0 (da5894fe697adee4e3d83f2e887187aad0bc7046)

**To Reproduce**
1. Go to usegalaxy.org
2. Run MiModD VCF Filter on an uncompressed vcf
3. See error

**Expected behavior**
Dataset is correctly converted to compressed vcf

**Screenshots**
Command line:
```console
cp '/corral4/main/jobs/042/665/42665018/configs/tmpy0nm2mle' 'galaxy.json' && bgzip -@ ${GALAXY_SLOTS:-1} -ci '/corral4/main/files/043/259/dataset_43259150.dat' > '/corral4/main/jobs/042/665/42665018/outputs/galaxy_dataset_1465c575-7505-4eb5-9bda-fdbb371c80dd.dat'
```

Error:
```
[E::bgzf_index_dump] Error opening /corral4/main/files/043/259/dataset_43259150.dat.gz.gzi : Read-only file system
Could not write index to '/corral4/main/files/043/259/dataset_43259150.dat.gz.gzi'
[E::bgzf_index_dump] Error opening /corral4/main/files/043/259/dataset_43259150.dat.gz.gzi : Read-only file system
Could not write index to '/corral4/main/files/043/259/dataset_43259150.dat.gz.gzi'
```

**Additional context**
N/A

**Comment by wm75** [comment]
Thanks for digging into this @natefoo !

Just a minor correction to the Steps to reproduce:
2. Got to Edit attributes for any VCF dataset (MiModD VCF Filter was just a tool that had produced a VCF in one of my histories)
3. Go to Convert and select "vcf_bgzip"

![Screenshot from 2022-05-13 18-50-46](https://user-images.githubusercontent.com/4742081/168332621-e09ec895-63ca-4d80-844c-87464b0ca526.png)

**Comment by wm75** [comment]
For the specific `vcf_bgzip` branch of the converter I'm pretty sure we do not want the index anyway because https://github.com/galaxyproject/galaxy/blob/9143dd7ca46d150ebfb26febbe187979f682da51/lib/galaxy/datatypes/tabular.py#L1043 builds a tabix .tbi metadata index for the datatype already.

I'm not sure what other datatypes would use the rather general "uncompressed file to compressed" converter though and whether the idnex would make sense for some of them.
Could be a question for @bernt-matthias ?

**Comment by bernt-matthias** [comment]
My intuition tells me that you are right @wm75 .. I also guess that creating the index would be meaningless if Galaxy is configured to output to the working dir, or?

Lets also ask @gallardoalba, who contributed the converter...

**Comment by gallardoalba** [comment]
Yes, I agree with @wm75 too.

**Comment by natefoo** [comment]
So then I believe all that is needed for the fix will be to drop `-i` from the command line?

**Comment by bernt-matthias** [comment]
Would be nice to have https://github.com/galaxyproject/planemo/pull/1199 (and/or https://github.com/galaxyproject/planemo/pull/1190 .. but I'm not that convinced of this one).
