### ISSUE TITLE
JS analysis app has trouble loading a citation

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1394]
This is from Test for tool https://test.galaxyproject.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/meme_meme/meme_meme/4.11.0.0

the bibtex seems valid: https://github.com/galaxyproject/tools-iuc/blob/master/tools/meme/meme.xml

![screenshot 2015-12-23 12 01 11](https://cloud.githubusercontent.com/assets/1814954/11981012/fc1848aa-a96c-11e5-9d6f-b6d3633266f0.png)

ping @bgruening

**Comment by jmchilton** [comment]
IUC should use a DOI - 10.1093/nar/gkl198 ?

**Comment by hexylena** [comment]
+1 for DOI, but definitely a bug in citation code if it can't display the bibtex type.

**Comment by martenson** [comment]
it does display the bibtex in other tools :/
just this one is weird, dunno why

**Comment by jmchilton** [comment]
Our JavaScript bibtex parser is very picky and I don't think there can really be said to exist a BibTeX standard - I wouldn't worry too much about it. Simplify the BibTeX until it works - in this case though I'd just use the DOI.

**Comment by bgruening** [comment]
I agree here with @jmchilton. This seems to be a special issue for this reference. I don't know why Greg was using this reference and not the other one mentioned by John.
ping @gregvonkuster

**Comment by gregvonkuster** [comment]
@martenson @bgruening @jmchilton The BibTex was taken from the original tool that I leveraged from the Galaxy core, which is still in there btw.

Citing meme does continue to state the same bibTex:
Citing MEME
Timothy L. Bailey and Charles Elkan, "Fitting a mixture model by expectation maximization to discover motifs in biopolymers", Proceedings of the Second International Conference on Intelligent Systems for Molecular Biology, pp. 28-36, AAAI Press, Menlo Park, California, 1994. 

This doi: 10.1093/nar/gkl198 is for MEME-ChIP.  Should I use it anyway?

**Comment by gregvonkuster** [comment]
There is a doi for the full meme suite: 10.1093/nar/gkp335 - should I replace the bibTex with this for the specific meme tool?  The meme tool seems to be the only one in the full meme suite that doesn't have a doi.

**Comment by martenson** [comment]
I think this is addressed by https://github.com/galaxyproject/galaxy/pull/1884
