### ISSUE TITLE
JS: do not show 'no content available' when direct loading tool

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1395]
Probably show 'loading' instead.

![screenshot 2015-12-23 12 18 16](https://cloud.githubusercontent.com/assets/1814954/11981286/50e7b9c2-a96f-11e5-94ac-29ec2d91e00f.png)

**Comment by guerler** [comment]
This has been fixed as part of #2720.

**Comment by martenson** [comment]
awesomesauce!
