### ISSUE TITLE
Break project into namespaces

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1396]
I'm going to let natefoo break it down but I guess it might make sense to start with something like galaxy-lib and galaxy-app with the further intention to break galaxy-app into galaxy-business-logic (but with a better name), galaxy-app, and galaxy-web.

**Comment by jmchilton** [comment]
Some questions @natefoo - do you want to do this before or after `pip install galaxy`? Can you lay out a checklist? Feel free to assign me TODO items. I'll continue with galaxy-lib as a standalone project for now, since I think the real problem is the wheel conflicts and that would seem largely independent of how the project is laid out on github and galaxy-lib though problematic in some ways is much better than copying the modules around in the interim.

**Comment by natefoo** [comment]
I am not sure how to properly unitize this, but I'd hope that we could limit it to `galaxy`, `galaxy-lib` (which would include commonly useful packages like `galaxy.util` and `galaxy.tools`). Do we really need a separate `galaxy-web` and `galaxy-app`?

**Comment by carlfeberhard** [comment]
@jmchilton @natefoo Is the shared code in galaxy-lib meant to eventually be removed from galaxyproject/galaxy (where it will be imported through galaxy-lib instead)?

**Comment by martenson** [comment]
@carlfeberhard afaik the idea was to not remove it but namespace it clearly within the same repo/project

**Comment by jmchilton** [comment]
Yes @martenson's comment reflects my current understanding as well.

**Comment by carlfeberhard** [comment]
@martenson This will seem dense, but can you give me an example or expand on that a bit more?

**Comment by martenson** [comment]
@carlfeberhard I can surely try, but please do not expect much, as I am not the visionary here.

I imagine the structure afterwards would look distantly similar to this:

```
.
└── galaxyproject
    ├── galaxy
    └── lib (shed wants this whole thing)
        ├── tools (planemo wants this)
        └── util (starforge wants this)
```

As I understand it, after having the sub-packages namespaced and 'independent', you would gain the ability of reusing specific parts of Galaxy in other top-level projects (planemo, starforge, shed et cetera) without relying on the whole thing. 
But importantly you would retain the coziness of working on one repo that you would have lost if you have broken it down into multiple projects.

@jmchilton @natefoo please help me here

**Comment by natefoo** [comment]
Right, it stays in one repo but when we make distribution packages (e.g. wheels), you will have separate wheels for the bits that are used by different applications. So galaxy would depend on `galaxy`, `galaxy-tools`, and `galaxy-util`, whereas planemo could depend only on `galaxy-tools` and `galaxy-util`, etc.

If anything were to be split, I'd say that the `galaxy` library and everything underneath could live in a separate repo from the rest of the Galaxy Stuff, but I think that would be a thought for way down the road.

**Comment by carlfeberhard** [comment]
Ok - I think I get it. I had noticed that galaxy-lib seems to have no paper trail back to the original commits it's incorporating (also no PR system similar to galaxyproject/galaxy, but I'm no fan of that, so...). That seemed like something better added earlier _if_ it was going to replace a large chunk of the core.

Thanks for explaining.
