### ISSUE TITLE
OutdatedDatabaseError mentions ``database_auto_migrate``, should tell you to `./manage_db.sh upgrade`

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#13988]
https://github.com/galaxyproject/galaxy/blob/b3b693ea0788f773442c8481472a87f43ccb10d7/lib/galaxy/model/migrations/__init__.py#L84 should tell you the right thing to do, which is `./manage_db.sh upgrade` IMO. Here's how we did this on 22.01: https://github.com/mvdbeek/galaxy/blob/468d5e0cbbe5a2a5aa76727c5124209da873f167/lib/galaxy/model/migrate/check.py#L136

**Comment by jdavcs** [comment]
Yes, you are right. I'll add this to #13710 in a minute.

**Comment by mvdbeek** [comment]
Ah, nice. People tend to just post the last line of a message, so that really jumped out to me. Yes, that sounds good.
