### ISSUE TITLE
Fastqc output reports should be shown as expected.

### ISSUE THREAD

**Issue by Naibin** [galaxyproject/galaxy#13998]
**Describe the bug**
Fastqc output reports cant be shown  properly on the central panel .

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: ({"version_major":"22.05","version_minor":"dev0"})
 

**To Reproduce**
1. Go to 'TOOL SHED'
2. Click on 'FASTQC'
3. Scroll down to 'UPLOAD  PAIR END FASTQ FILES', Then I execuate the programme.
4. See error：Fastqc output reports cant be shown  properly on the central panel .

**Expected behavior**

Fastqc output reports should be shown as expected.

**Screenshots**

By using my own sever ,as you cansee this is the output report.the pictures in the html page  cant be shown.  

![171576837-1504597e-4c66-4811-aa8c-e68f1a78fa85](https://user-images.githubusercontent.com/7318522/171579761-f87dba2d-3223-43b0-8023-71840a56bd2c.png)

By using the PSU galaxy.sever:https://usegalaxy.org, I got this result:
![image](https://user-images.githubusercontent.com/7318522/171577543-ba9812df-46bc-4769-9e07-53ade1da1b8f.png)

**Additional context**
Thanks for your kind help.

**Comment by mvdbeek** [comment]
You need to go to the admin panel -> Manage allowlist, then click on the tool that should be allowed to render unsanitized output.

**Comment by Naibin** [comment]
Thanks for you quick answer.Let me have try.

**Comment by Naibin** [comment]
Dear Dr. Marius, 
![image](https://user-images.githubusercontent.com/7318522/171580940-3572f7f4-1f57-477f-9fda-7c9effcf5733.png)
Now it works perfect !

But now I have another question,
![image](https://user-images.githubusercontent.com/7318522/171581836-efc1ea84-5253-4c7f-a7f7-9df93e8ee9e5.png)

 As you cansee there so many tools have been sanitized for html, is it ok for me to unsanitized all of them? 
Best wishes!

**Comment by hexylena** [comment]
>  is it ok for me to unsanitized all of them?

unfortunately you need to make the decision if you trust the tool's output. Most don't output HTML/SVG. And if you install good quality tools you're generally safer.

The threat model here is: a user generates unsafe HTML and includes a javascript attack, and then tricks you (as an admin) into opening it.

**Comment by Naibin** [comment]
@hexylena  Ok I got it, thanks so much !
