### ISSUE TITLE
Provide universal2 wheels to fix uploads

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14006]
Mostly a wheelforge issue, but before the next release we should either get upstream pylibmagic universal2 wheels or build them ourselves.
Without the wheels the pylibmagic will prevent magic from working, even if libmagic is installed from another source.

**Comment by dannon** [comment]
WIP here: https://github.com/galaxyproject/wheelforge/pull/10

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/14428
