### ISSUE TITLE
Waking up in 5.00 minutes ||| http://localhost:8080 in a browser does not work

### ISSUE THREAD

**Issue by Ural-Yunusbaev** [galaxyproject/galaxy#14002]
**Describe the bug**
Hi, after I run galaxy installation
sh run.sh
I got this
...
==> /home/ural/galaxy/database/gravity/log/celery-beat.log <==
[2022-06-02 09:33:14,497: DEBUG/MainProcess] beat: Synchronizing schedule...
[2022-06-02 09:33:14,510: DEBUG/MainProcess] beat: Waking up in 5.00 minutes.
[2022-06-02 09:38:14,574: DEBUG/MainProcess] beat: Synchronizing schedule...
[2022-06-02 09:38:14,589: DEBUG/MainProcess] beat: Waking up in 5.00 minutes.

I tried http://localhost:8080 in a browser, but it does not work.
Can you help me?

It looks like gunicorn is running: lsof -i tcp:8080
COMMAND PID USER FD TYPE DEVICE SIZE/OFF NODE NAME
gunicorn 3501081 ihnagen 6u IPv4 12054736 0t0 TCP localhost:http-alt (LISTEN)
gunicorn 3501132 ihnagen 6u IPv4 12054736 0t0 TCP localhost:http-alt (LISTEN)

**Comment by mvdbeek** [comment]
You've cut out the gunicorn logs, they should be above what you posted. You can also see them in /home/ural/galaxy/database/gravity/log/gunicorn.log

**Comment by Ural-Yunusbaev** [comment]
Marius,

Thank you for reply.
I have reinstalled it to another server as the following:
cd /home/ihnagen/soft
git clone https://github.com/galaxyproject/galaxy.git
cd galaxy
sh run.sh

After installation I tried http://localhost:8080 in a browser, but it does not work.
What might be the reason?

#This is the output of the run.sh of Starting gunicorn 20.1.0:

...
galaxy.webapps.galaxy.buildapp DEBUG 2022-06-02 11:37:11,916 [pN:main,p:3500547,tN:MainThread] Prior to webapp return, Galaxy thread <_MainThread(MainThread, started 139927394015040)> is alive.
/home/ihnagen/soft/galaxy/lib/galaxy/webapps/openapi/utils.py:461: UserWarning: Merging operation with id fetch_json_api_tools_fetch_post with operation with id fetch_form_api_tools_fetch_post.
  warnings.warn(message)
[2022-06-02 11:37:13 -0500] [3500547] [INFO] Starting gunicorn 20.1.0
[2022-06-02 11:37:13 -0500] [3500547] [INFO] Listening at: http://127.0.0.1:8080 (3500547)
[2022-06-02 11:37:13 -0500] [3500547] [INFO] Using worker: galaxy.webapps.galaxy.workers.Worker
[2022-06-02 11:37:13 -0500] [3500594] [INFO] Booting worker with pid: 3500594
galaxy.web_stack DEBUG 2022-06-02 11:37:13,358 [pN:main.1,p:3500594,tN:Thread-2] server_name set to: main.1
galaxy.jobs.manager DEBUG 2022-06-02 11:37:13,358 [pN:main.1,p:3500594,tN:Thread-2] Initializing job handler
galaxy.jobs INFO 2022-06-02 11:37:13,358 [pN:main.1,p:3500594,tN:Thread-2] Handler 'main.1' will load all configured runner plugins
galaxy.jobs.runners.state_handler_factory DEBUG 2022-06-02 11:37:13,365 [pN:main.1,p:3500594,tN:Thread-2] Loaded 'failure' state handler from module galaxy.jobs.runners.state_handlers.resubmit
galaxy.jobs DEBUG 2022-06-02 11:37:13,365 [pN:main.1,p:3500594,tN:Thread-2] Loaded job runner 'galaxy.jobs.runners.local:LocalJobRunner' as 'local'
galaxy.jobs.handler DEBUG 2022-06-02 11:37:13,365 [pN:main.1,p:3500594,tN:Thread-2] Loaded job runners plugins: local
galaxy.jobs.handler INFO 2022-06-02 11:37:13,365 [pN:main.1,p:3500594,tN:Thread-2] job handler stop queue started
galaxy.jobs.runners DEBUG 2022-06-02 11:37:13,365 [pN:main.1,p:3500594,tN:Thread-2] Starting 4 LocalRunner workers
galaxy.jobs.handler DEBUG 2022-06-02 11:37:13,367 [pN:main.1,p:3500594,tN:Thread-2] Handler queue starting for jobs assigned to handler: main.1
galaxy.jobs.handler INFO 2022-06-02 11:37:13,862 [pN:main.1,p:3500594,tN:JobHandlerQueue.monitor_thread] Handler job grabber initialized with 'HANDLER_ASSIGNMENT_METHODS.DB_SKIP_LOCKED' assignment method for handler 'main.1', tag(s):
galaxy.jobs.handler INFO 2022-06-02 11:37:13,862 [pN:main.1,p:3500594,tN:Thread-2] job handler queue started
galaxy.jobs.handler INFO 2022-06-02 11:37:13,864 [pN:main.1,p:3500594,tN:Thread-2] job handler stop queue started
galaxy.jobs.handler INFO 2022-06-02 11:37:13,865 [pN:main.1,p:3500594,tN:WorkflowRequestMonitor.monitor_thread] Handler job grabber initialized with 'HANDLER_ASSIGNMENT_METHODS.DB_SKIP_LOCKED' assignment method for handler 'main.1', tag(s): _default_, None
galaxy.queue_worker INFO 2022-06-02 11:37:13,867 [pN:main.1,p:3500594,tN:Thread-2] Binding and starting galaxy control worker for main.1
[2022-06-02 11:37:13 -0500] [3500594] [INFO] Started server process [3500594]
[2022-06-02 11:37:13 -0500] [3500594] [INFO] Waiting for application startup.
[2022-06-02 11:37:13 -0500] [3500594] [INFO] Application startup complete.
galaxy.queue_worker INFO 2022-06-02 11:37:13,880 [pN:main.1,p:3500594,tN:Thread-2] Queuing async task rebuild_toolbox_search_index for main.1.
galaxy.model.database_heartbeat DEBUG 2022-06-02 11:37:13,972 [pN:main.1,p:3500594,tN:database_heartbeart_main.1.thread] main.1 is config watcher
galaxy.web_stack INFO 2022-06-02 11:37:13,972 [pN:main.1,p:3500594,tN:Thread-2] Galaxy server instance 'main.1' is running
serving on http://127.0.0.1:8080
galaxy.queue_worker INFO 2022-06-02 11:37:14,071 [pN:main.1,p:3500594,tN:Thread-1] Instance 'main.1' received 'rebuild_toolbox_search_index' task, executing now.
galaxy.tools.search DEBUG 2022-06-02 11:37:14,072 [pN:main.1,p:3500594,tN:Thread-1] Starting to build toolbox index of panel default.
galaxy.tools.search DEBUG 2022-06-02 11:37:14,105 [pN:main.1,p:3500594,tN:Thread-1] Toolbox index of panel default finished (33.161 ms)
galaxy.tools.search DEBUG 2022-06-02 11:37:14,105 [pN:main.1,p:3500594,tN:Thread-1] Starting to build toolbox index of panel ontology:edam_operations.
galaxy.tools.search DEBUG 2022-06-02 11:37:14,116 [pN:main.1,p:3500594,tN:Thread-1] Toolbox index of panel ontology:edam_operations finished (10.533 ms)
galaxy.tools.search DEBUG 2022-06-02 11:37:14,116 [pN:main.1,p:3500594,tN:Thread-1] Starting to build toolbox index of panel ontology:edam_topics.
galaxy.tools.search DEBUG 2022-06-02 11:37:14,124 [pN:main.1,p:3500594,tN:Thread-1] Toolbox index of panel ontology:edam_topics finished (7.622 ms)
2022-06-02 11:37:16,127 INFO success: celery entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
2022-06-02 11:37:16,127 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 10 seconds (startsecs)
2022-06-02 11:37:21,134 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 15 seconds (startsecs)

==> /home/ihnagen/soft/galaxy/database/gravity/log/celery-beat.log <==
[2022-06-02 11:42:07,731: DEBUG/MainProcess] beat: Synchronizing schedule...
[2022-06-02 11:42:07,733: DEBUG/MainProcess] beat: Waking up in 5.00 minutes.
[2022-06-02 11:47:07,834: DEBUG/MainProcess] beat: Synchronizing schedule...
[2022-06-02 11:47:07,836: DEBUG/MainProcess] beat: Waking up in 5.00 minutes.
[2022-06-02 11:52:07,936: DEBUG/MainProcess] beat: Synchronizing schedule...
[2022-06-02 11:52:07,938: DEBUG/MainProcess] beat: Waking up in 5.00 minutes.
[2022-06-02 11:57:08,039: DEBUG/MainProcess] beat: Synchronizing schedule...
[2022-06-02 11:57:08,039: DEBUG/MainProcess] beat: Waking up in 5.00 minutes.



# This is the port status
lsof -i tcp:8080
COMMAND      PID    USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
gunicorn 3501081 ihnagen    6u  IPv4 12054736      0t0  TCP localhost:http-alt (LISTEN)
gunicorn 3501132 ihnagen    6u  IPv4 12054736      0t0  TCP localhost:http-alt (LISTEN)

**Comment by mvdbeek** [comment]
This all looks correct. Are you running this on a VM ? Do you maybe need to forward ports ?

**Comment by Ural-Yunusbaev** [comment]
This is not a VM.

**Comment by dannon** [comment]
What exactly doesn't work at `http://127.0.0.1:8080`?  Just totally unresponsive?  Or is there anything obvious in the browser logs indicating the request was blocked, potentially?

**Comment by Ural-Yunusbaev** [comment]
Unable to connect

Firefox can’t establish a connection to the server at 129.130.90.211:9090.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by Ural-Yunusbaev** [comment]
The 129.130.90.211 is the server where the galaxy was installed and running now.

**Comment by Ural-Yunusbaev** [comment]
sudo ufw status
Status: inactive

**Comment by dannon** [comment]
Ok, so it looks like you're trying to access Galaxy on a remote machine.  The default 127.0.0.1:8080 (or the localhost alias) is isolated to the host machine by default.  To expose Galaxy to the outside world, you need a bit of extra configuration here.  See `galaxy.yml` (you may need to copy the .sample over), and edit the `bind` setting.  A simple, permissive setting for this would be `0.0.0.0:8080`, listening on all adapters at port 8080.

**Comment by Ural-Yunusbaev** [comment]
It worked! 
In addition, I disabled the firewall.

Thanks, Dannon!

**Comment by dannon** [comment]
@Ural-Yunusbaev Glad to hear it!
