### ISSUE TITLE
New history hides buttons when stdout too large

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#14014]
**Describe the bug**

On jobs that have stdouts passing the normal size of the expanded stdout box, it the dataset buttons are pushed out of the available history item. This appears to only be true with stdout, not stderr

![image](https://user-images.githubusercontent.com/40246333/171959877-9d8321b4-28af-468b-bd7e-3140c866b60b.png)

**Comment by guerler** [comment]
<img width="282" alt="image" src="https://user-images.githubusercontent.com/2105447/174269634-e88b7d1a-10e2-4c47-b27f-c46f253ece98.png">

**Comment by mvdbeek** [comment]
Can you open a new issue with some text describing the bug if you don't plan to work on this yourself @guerler ?
The bug that @astrovsky01 reported is fixed by moving the buttons above the peek so j don't think it's helpful to reopen the issue.

**Comment by guerler** [comment]
Ok, that might make more sense although this seems like the same underlying issue.

**Comment by guerler** [comment]
Created a new issue, closing this.
