### ISSUE TITLE
Tabbed interface for workflow invocations

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14029]
To improve the look and feel of the workflow invocation interface it would be great if we could have tabs instead of the `<details><summary></summary></details>` tags that we're using now.
For reference, this is how the interface looks like now:
![Screenshot 2022-06-07 at 19 05 29](https://user-images.githubusercontent.com/6804901/172441307-01e8d6a0-6ffc-42f7-8ae0-04e2ca2a63d7.png)

The suggestion is to add tabs, where the first tab just shows summary information, like the step and job states (the green bars), the next tab would inputs and outputs of the workfow, another tab to perhaps see a preview of the workflow, another tab for different types of exports that are possible etc.

**Comment by davelopez** [comment]
If no one else is planning to work on this I'll start doing some prototyping. Feel free to re-assign otherwise :)

**Comment by davelopez** [comment]
What about something like this for a first pass?

![wf_invocation_tabs](https://user-images.githubusercontent.com/46503462/173399820-fe374552-5b9d-4c34-bff3-5de0ee470372.gif)

**Comment by mvdbeek** [comment]
Brilliant! I love it! Depending on how far away we are from rendering the preview we could render a preview with cytoscape https://observablehq.com/@mvdbeek/workflow-preview ... but that's just for bonus points and doesn't need to go into a first version.
