### ISSUE TITLE
Improved Tool Search

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#14028]
Right now tool search takes params and passes them to whoosh which does a bunch of fancy weighting and returns a large set of results in the toolbox on the left that can be toggled into sections or ranked, etc.

With 22.05 we have a new advanced history search, seen here:
![image](https://user-images.githubusercontent.com/155398/172422089-d92150e9-01e2-4ffc-a6d1-33988dfe3cfb.png)

Following that same pattern, the tool search should be updated as follows:

1) 'standard' search should be clientside only quick filtering based on name and ID, and should autocomplete.
2) advanced search should expand to fill the full left column (as does advanced history search), allow for more refined search arguments, and results from this should be displayed in a richer format in the middle panel.  (tool description, search rank, popularity, whatever inline).

This richer tool results presentation could also take inspiration from the `tools/view` seen below in what it presents (though a simple list view with details may be preferable).

![image](https://user-images.githubusercontent.com/155398/172423319-02de2bd7-0c3b-41db-8069-e85bf5b42b44.png)

(xref MPL meeting notes)

**Comment by bgruening** [comment]
A few questions which we could discuss:

* is a all-the-time visible toolbar really necessary 
* how do you find/explore tools on your desktop
* is a keyboard shortcut (for power users) useful to directly go to the search bar - similar to editors or github

**Comment by hexylena** [comment]
Good points @bgruening. It takes up a lot of space, and participants so often have small screens on which to work. [More keyboard shortcuts](https://github.com/galaxyproject/galaxy/issues/8387) would be fab!

**Comment by hujambo-dunia** [comment]
@bgruening maybe an auto-expanding upon hover toolbar. So we still have a tools bar, but greatly reduced in width with option to "stick" (remain expanded) might be one (1)  accessible way to implement that (2) still matches our help materials (more or less).

**Comment by neoformit** [comment]
A comment on the whoosh backend - I had a look and I don't think it boosts for whole word matches. So a search for "grouping" tool doesn't rank "grouping" tool first, because other tools have the word "grouping" in the name or many times in the description/help.

**Comment by hujambo-dunia** [comment]
Other features to consider including:

- search by Tool ID (Cc: @blankenberg)

**Comment by neoformit** [comment]
@bgruening @hujambo-dunia could we improve this by making the existing expand/collapse buttons more obvious? It took me a year to notice these at the bottom of the tool panel!

![image](https://user-images.githubusercontent.com/42562517/179423356-4e8658c7-b345-46de-85f2-d709c8ee032c.png)

If these controls were displayed on the right edge of the tool panel on hover I think they'd be used more often? I think Atom demonstrates this well - the blue arrow appears on hover:

![image](https://user-images.githubusercontent.com/42562517/179423412-d2601064-6d9b-4b63-b893-0da051f7e596.png)

I like Björn's idea about full-page search, maybe with a floating "tool" icon in the bottom-left corner.

**Comment by neoformit** [comment]
It looks like tool search indexes the tool XML `<help>` section. Could we display this in a full-page advanced search?

**Comment by bgruening** [comment]
The backend __do not__ return the weights to the client. Instead, the backend sorts the results and passes it to the client. However, the client resorts the results and messes this up.

* pass the weights to the client
* do not resort the results on the client

**Comment by bgruening** [comment]
I'm not sure this one should be closed. Maybe a follow-up should be created but currently its just using a different interface for the same search imho.

It would be nice to:

1) add advanced search functionalities, like input/output datatype searches - API needed
2) see if a client only search is feasible and better for the "normal/simple/classic" search

**Comment by dannon** [comment]
@bgruening Totally agreed; I especially still want to see the client-only simple match implemented -- this just got autoclosed with the PR merge there.

**Comment by dannon** [comment]
The brunt of this is now in dev; we've discussed followup projects to allow searching by datatypes and other options and those can be specced out separately.
