### ISSUE TITLE
It is possible to have an account with an empty username! And we don't like it.

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1404]
reported by alessandra.mallei
xref: https://biostar.usegalaxy.org/p/15438/

I had a problem trying to download a workflow. Instead of starting the downloading of the ga file, a web page with the following url "https://usegalaxy.org/u//w/project-workflow/json-download​" opened with this error message: "HTTP 404 Errror page not found" (using Microsoft Edge) and "Not found. The resource could not be found. No route for /u/w/project-workflow/json-download" (using Mozilla FireFox). Also the URL for Importing to Another Galaxy gave me the same result. I worked around the problem by publishing my workflow, accessing galaxy without loging in and then using the option "save as". Can you help?

**Comment by martenson** [comment]
The user does not have a Galaxy username set.

**Comment by natefoo** [comment]
Probably should change this issue to "it is possible to have an account with an empty username"

**Comment by hexylena** [comment]
I think we have validation to prevent this now? Not clear where they failed to set a username (registration or deleting after)
