### ISSUE TITLE
Clarifications to "Quota" Forms

### ISSUE THREAD

**Issue by quacksawbones** [galaxyproject/galaxy#14065]
There are a couple of parts of the Galaxy "Quota" system ([./lib/galaxy/webapps/galaxy/controllers/admin.py](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/controllers/admin.py)) where I would like to suggest some clarifications:

- In "Create Quota", "Edit Quota" and "Set Quota", changing `Assign, increase by amount, or decrease by amount?` to a dropdown list or set of radio buttons with valid values and/or include what values are valid in the label (e.g. `Assign ('='), increase by amount ('+'), or decrease by amount ('-')?` or similar).
  - Affects lines [436](https://github.com/galaxyproject/galaxy/blob/fd8826904be3f3201f7e7a3b6ffbadd27f268896/lib/galaxy/webapps/galaxy/controllers/admin.py#L436), [844](https://github.com/galaxyproject/galaxy/blob/fd8826904be3f3201f7e7a3b6ffbadd27f268896/lib/galaxy/webapps/galaxy/controllers/admin.py#L844) and [873](https://github.com/galaxyproject/galaxy/blob/fd8826904be3f3201f7e7a3b6ffbadd27f268896/lib/galaxy/webapps/galaxy/controllers/admin.py#L873) respectively,
- In "Create Quota", under `Is this quota a default for a class of users (if yes, what type)?`, including some information on what a valid "class of user" is in the label and/or a link to more information in the Galaxy documentation (I have no idea where that is).
  - Affects line [742](https://github.com/galaxyproject/galaxy/blob/fd8826904be3f3201f7e7a3b6ffbadd27f268896/lib/galaxy/webapps/galaxy/controllers/admin.py#L742)

Galaxy Version: 22.01

I appreciate these are small UI concerns but these clarifications should make it easier for new Admins to get up to speed with the Quota system.

Thanks,

Darren

**Comment by davelopez** [comment]
Thank you @quacksawbones for the input!
I agree, this form can benefit from a bit more help.

> In "Create Quota", "Edit Quota" and "Set Quota", changing Assign, increase by amount, or decrease by amount? to a dropdown list or set of radio buttons with valid values

For this part I think there is a dropdown where you can select one of those options:
![quotas](https://user-images.githubusercontent.com/46503462/173629746-db228cc4-4e8c-4df8-8598-978e299967a7.gif)

This is on the `dev` branch, I think there was a recent bug that prevented these options to show up but should be fixed now. Is this what you are referring to?

**Comment by quacksawbones** [comment]
HA! Yes, that's exactly what I meant! I'm glad my ideas are sound. 👍 

Thanks for that. Looking forward to having them in the system.
