### ISSUE TITLE
Conda dependency resolver followup

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1406]
- [x] https://github.com/galaxyproject/galaxy/pull/1345#issuecomment-168073436
- [x] address https://github.com/galaxyproject/galaxy/pull/1345#discussion_r48629022 
- [ ] ~~https://github.com/galaxyproject/galaxy/pull/1345#discussion_r48053727~~ (Moved to #1411)

**Comment by jmchilton** [comment]
Replacing the third point with its own issue (see https://github.com/galaxyproject/galaxy/issues/1411). This way #1409 (after the latest update) will close out this issue by addressing the first two points.

**Comment by jmchilton** [comment]
Addressed with #1409.
