### ISSUE TITLE
403 error bulk changing datatype on usegalaxy.org [release-testing][bug]

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#14079]
**Describe the bug**
Trying to change data types in bulk causes an error.

![Screen Shot 2022-06-17 at 10 32 45 am](https://user-images.githubusercontent.com/22670687/174199584-e38d0957-dd87-4763-9915-60dd96eb8908.png)

`PUT https://usegalaxy.org/api/histories/9f009aea5174a709/contents/bulk?q=deleted&qv=false&q=visible&qv=true 403 (Forbidden)`

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05

**To Reproduce**
1. Upload a dataset
2. Click on the checkbox at the top of the history to expose checkboxes for items
3. Select the datasest
4. From the 'All 1 selected' menu, select "Change data type"
5. Select a new data type and click 'OK'

**Expected behavior**
Data types will be updated for selected datasets

**Comment by mvdbeek** [comment]
> **Expected behavior**
> Data types will be updated for selected datasets

The admin needs to enable celery tasks. The only action I can think of is to not show the operation if celery isn't enabled. Technically we could also kick off a regular set metadata job, but we want to get away from that.
