### ISSUE TITLE
On usegalaxy.org, if a history has a 'training' tag, data fetch fails

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#14081]
**Describe the bug**
For histories with the 'training' tag, uploading a file from a url fails with the following error:

```
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/data_fetch.py", line 17, in <module>
    import bdbag.bdbag_api
ModuleNotFoundError: No module named 'bdbag'
```

I've shared the history here https://usegalaxy.org/u/cat-bro/h/datafetch-history.  The first upload succeeds and the second fails because training tag has been added.  I can't think of any other variables that could be affecting it.

**Comment by mvdbeek** [comment]
That is a deployment issue, I assume everything is mapped to singularity on the training destination.
