### ISSUE TITLE
Updating a package doesn't trigger recompilation

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1408]
This has made testing an absolute nightmare as I have to essentially go through a complete re-installation cycle just to get updates.

Here's the scenario: 
- I added a couple new perl module dependencies to a package
- uploaded to the TTS
- re-uploaded downstream dependencies of the parent, updated package
- went to admin, "Update toolshed status", all of the appropriate packages listed updates
- went to the bottom level dependency (the package I added perl modules to) and hit "Get toolshed updates"
- **eafed** is the new, **0de1** is the old

![selection_527](https://cloud.githubusercontent.com/assets/458683/12058850/4aaab256-af16-11e5-89c5-45f6f7caa81f.png)

Galaxy did not download / install  the perl modules that were added. It merely bumped the version and said "OK done." As seen in the above picture, Galaxy did not even change the folder that the package was installed to.

I do not expect a fix, I just wished to note that this is a bug. I expect conda and friends to make this a non-issue.

Further more, after uninstalling Galaxy removes all files from the folder. Great. When I go to reinstall I see this

![selection_528](https://cloud.githubusercontent.com/assets/458683/12058898/194455a4-af17-11e5-982e-1dd92d180ef4.png)

and think "Yay, we're going to get the right version!" However then I check at the command line and see that it's all lies and Galaxy is actually installing the old version??

![selection_529](https://cloud.githubusercontent.com/assets/458683/12058901/27333cac-af17-11e5-8112-ef0003297050.png)

except I'm seeing some of the new modules in there, despite the wildly incorrect version in the path.

**Comment by mvdbeek** [comment]
@erasche are you on the dev branch? At least for the uninstalling/re-installing part there were some recent bugfixes, perhaps some things are not yet in relase/stabe?!

**Comment by hexylena** [comment]
@mvdbeek nope, I was using a docker galaxy container. I remember your thread recently and that PR, I'll have to test at some point. Thanks for the reminder.

**Comment by bgruening** [comment]
@erasche try the `bgruening/galaxy-stable:dev` it is usually updated every 2 days.

**Comment by hexylena** [comment]
Yep, I'd not been using `:dev` and that was a mistake. Closing until I have evidence this is still a problem on dev.
