### ISSUE TITLE
unlimited quota is communicated as 0 bytes

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#14083]
If your quota is unlimited you see `You've got 0 b of total disk quota` on the `/storage` galaxy url. This should probably say `unlimited` or similar.

possibly defined here: https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/User/DiskUsage/Quota/QuotaUsageSummary.vue#L49

**Comment by davelopez** [comment]
Thank you @martenson! I'll have a look!
