### ISSUE TITLE
Running bulk change datatype alters deferred data state

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14096]
I suppose we should skip the set metadata task on deferred data

**Comment by davelopez** [comment]
Is this just a matter of adding a guard at the beginning of the `set_metadata` celery task like:
```python
if dataset_instance.metadata_deferred:
    return
```
Or does it require more actions?

**Comment by mvdbeek** [comment]
We should check what happens if we change the datatype ?

**Comment by davelopez** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14149
