### ISSUE TITLE
[release-testing] New history hides peek when stdout too large

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#14098]
**Describe the bug**
Similar to #14014. The size of the expansion is limited but does not account for large stdouts. As a consequence the expanded history item is cut off and this can lead to glitches with the virtual scroller.

**Expected behavior**
The stdout should be limited to only a few lines.

**Screenshots**
<img width="200" alt="image" src="https://user-images.githubusercontent.com/2105447/174269634-e88b7d1a-10e2-4c47-b27f-c46f253ece98.png">

**Comment by dannon** [comment]
xref #13827
