### ISSUE TITLE
[release-testing] Improving the user experience when changing history name

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#14095]
In the new history, clicking on the pencil icon next to the history name reveals two multi-line text boxes for the history name and annotation. For the former, a single-line text box would be preferable; I can't think of a good reason to insert a newline character in a history name. (Maybe this should be disallowed on the backend as well?)

![image](https://user-images.githubusercontent.com/32272674/174334643-7c097961-a89b-4677-889b-a74d535839cb.png)

In addition, it would be nice if the history name input box was autofocussed, so the user can click on the pencil and start typing without needing to click on the text box. An additional click on the `Save` button is also required - if a single-line input box was used, perhaps it would be possible to save on hitting Enter as well?

Reported by @natefoo, thanks!

**Comment by natefoo** [comment]
Thanks @simonbray! FWIW in the old history you could also click anywhere on the name in order to immediately begin editing the name. I can see how it may not be desirable to have that, however.

**Comment by guerler** [comment]
Yes, thank you for reporting these issues. The benefit of having a multiline field is that one can see longer names without having to scroll, and interestingly it seems that new-lines are removed from the names once saved. Still I agree that e.g. directly focussing on the name input field would help in reducing the required number of clicks to change the history name.

**Comment by guerler** [comment]
Notes from the meeting, we are considering to just show a regular input field instead of a multiline field for the history name to resolve this issue.

**Comment by dannon** [comment]
This should be handled in #14171 if you'd like to test it.  Single line input, autofocus on history name, and auto-save on 'enter' key in history name.
