### ISSUE TITLE
[release-testing] History search: Capitalized name tags are unsearchable

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#14099]
In the history search, a name tag that starts with a capital letter is not searchable:

https://user-images.githubusercontent.com/78516064/174341208-c2233dbf-ab51-4e57-a3d5-21345d53e1e1.mov

**Comment by davelopez** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14127
