### ISSUE TITLE
[release testing] Undelete und purge bulk operation option shown in the wrong places

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#14107]
Testing #13555. A couple of comments:

- If I delete some datasets, the option to purge is no longer visible. If I want to purge, I have to first undelete, before the purge option reappears. I think it should be possible to purge in a single step from the deleted state.
- Selecting purged datasets still provides the `Undelete` option. This should be removed or greyed out IMO.

**Comment by davelopez** [comment]
Thank you @simonbray for reporting! I've made some fixes in https://github.com/galaxyproject/galaxy/pull/14115 can you please try again with those?

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14115
