### ISSUE TITLE
[release testing] Dropdown data for bulk history operations partially covered by navigation bar

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#14106]
Testing https://github.com/galaxyproject/galaxy/pull/13555. When I select two datasets and click on `All 2 selected` the dropdown menu appears:

![image](https://user-images.githubusercontent.com/32272674/174436257-35882abf-befd-4080-9582-739b726526f1.png)

but the top two items `With 2 selected...` and `Hide` are covered by the navigation bar.

You have to zoom in far enough that the space available for the menu beneath the `All 2 selected` button is too small for the menu, but on my screen that is already 100% zoom.

**Comment by davelopez** [comment]
Thanks @simonbray!
The best I could do to fix this is https://github.com/galaxyproject/galaxy/pull/14116, can you please check if that works for you?

**Comment by dannon** [comment]
Fixed with #14116.
