### ISSUE TITLE
[release-testing] Viewing invocations for an individual workflow shows all invocations

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#14101]
Testing https://github.com/galaxyproject/galaxy/pull/13792. Going to the workflow menu, choosing a workflow, clicking the dropdown menu and clicking `Invocations` should display only invocations for that particular workflow. Instead, all invocations are shown (`/workflows/9c49d5aac9fe9dcc/invocations` and `/workflows/invocations` have the same content).

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14102
