### ISSUE TITLE
Cannot access/download bam.bai index from bam datasets (beta history)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#14123]
**Describe the bug**
The `bam.bai` index is not accessible in the beta history (disc icon or link). It is still attached to the `bam` disc in a list in the legacy history.

> Workarounds for End-Users:
> 
> Using the default history at UseGalaxy.org (aka "beta history")
> 1. Start in the original `bam` dataset
> 2. Click on 🖊️   (to reach the Edit Attributes functions)
> 3. Go to the Convert tab 
> 4. Create the index as a new dataset 
> 5. Download from that new `bam.bai` dataset using  💾  or 🔗 
> 
> Using the legacy history at UseGalaxy.org (switch under the History menu ⚙️ )
> 1. Download `bam.bai` data directly from the original `bam` dataset using the list under 💾  (only, the 🔗 has always been just for the `bam`)
>
>  💾  or 🔗 links can be copied to your clipboard in both history views in the "right-click" menu (MacOS)

**Galaxy Version and/or server at which you observed the bug**
UseGalaxy.org
Galaxy version 22.05.dev0, commit [81c8a165272076ca156642459804172ca00d2ca7](https://github.com/galaxyproject/galaxy/commit/81c8a165272076ca156642459804172ca00d2ca7)

**To Reproduce**
1. Go to any `bam` dataset in the beta history
2. Click on 💾  -- single or right-click
3. Starts the download or presents just one link -- instead of presenting a list of two items to choose from(`bam` + `bam.bai`)

**Expected behavior**
Attach the `bam.bai` to the `bam` 💾  in the beta history as in the legacy history

**Screenshots**

**Additional context**

**Comment by guerler** [comment]
Thanks for reporting this @jennaj. It's likely due to a regression (xref: https://github.com/galaxyproject/galaxy/blob/dev/client/src/mvc/dataset/dataset-li.js#L347).
