### ISSUE TITLE
Collection "datatype" metadata vertically justifies up a bit too much if item count > 1 (beta history)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#14122]
**Describe the bug**
The "datatype" seems to be justified vertically to the top, not the bottom, for dataset collections that contain more than one collection item. `fastqsanger` seems to be the only exception, and `fastqsanger.gz` is impacted. Collections with one item seem fine in all cases checked. Non-collection datasets are also fine.

Maybe it is how the browser is rendering the font? See the first screenshot below for the worse cases I found.

**Galaxy Version and/or server at which you observed the bug**
UseGalaxy.org
Galaxy version 22.05.dev0, commit [81c8a165272076ca156642459804172ca00d2ca7](https://github.com/galaxyproject/galaxy/commit/81c8a165272076ca156642459804172ca00d2ca7)

**To Reproduce**
MacOS/Chrome
Safari has a similar appearance

**Expected behavior**
Adjust so the text appears to be all on the same line, not with the "datatype" floating a bit above. 

**Screenshots**

Collections with 2 or more items

<img width="275" alt="datatype-text-vertical-justify-bottom" src="https://user-images.githubusercontent.com/8999735/174687236-facb5ba8-22a6-44d4-ab1a-3d599589a314.png">

Collections with just one item

<img width="270" alt="datatype-text-vertical-justify-bottom2" src="https://user-images.githubusercontent.com/8999735/174687533-237cd8c4-bc09-4e8f-9c78-8854e3093ddf.png">

Collections with 2 or more items, but are `fastqsanger`

<img width="275" alt="datatype-text-vertical-justify-bottom3" src="https://user-images.githubusercontent.com/8999735/174688394-ff9e630d-bb4f-4427-af04-e7d5ab9a885d.png">

**Additional context**

**Comment by davelopez** [comment]
I've been trying to reproduce this one, but unfortunately, I can't.
Is someone else with MacOS experiencing this?

Also even if I could reproduce I don't really know what we should actually change, the line just has a simple bold on it.

https://github.com/galaxyproject/galaxy/blob/b111384289c91e09084976ccf438fad5b290fb0d/client/src/components/History/Content/Collection/CollectionDescription.vue#L4

**Comment by mvdbeek** [comment]
I can't reproduce this either and I've looked quite carefullty. @jennaj can you share that history and your screen resolution ?

**Comment by jdavcs** [comment]
Can't reproduce. @jennaj please reopen if issue resurfaces.
