### ISSUE TITLE
Collection element states are never updated without a page reload

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14129]
Because every element starts out in queued state all collection elements will keep grey no matter what there actual status is until you refresh the page in the browser. To reproduce: just run any job that creates a collection and navigate into the collection at various times (the collection item itself will show the progress correctly, but the elements will stay grey).

**Comment by dannon** [comment]
Need to test this (against main specifically) and add more details to figure out what might be problematic here.

**Comment by wm75** [comment]
Haven't been able to reproduce this so far. Feel free to close for now and I can open a new issue if it happens again and I can pinpoint the exact circumstances.

**Comment by mvdbeek** [comment]
I think the issue is that the poller dies once a request fails, I think this is still an issue.

**Comment by mvdbeek** [comment]
Probably fixed in https://github.com/galaxyproject/galaxy/pull/14233
