### ISSUE TITLE
Collection progress bars width is limited by collection name width

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#14135]
**Describe the bug**
Currently the width of collection progress bars is limited by the width of the name of the collection, not by the available space in the item box (see screenshot below). This means that collections of equal size visually appear to be of different size.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05dev on usegalaxy.org

**Expected behavior**
All progress bars should make use of available space up to where the collection name would get wrapped.

**Screenshots**
![Screenshot from 2022-06-21 14-18-29](https://user-images.githubusercontent.com/4742081/174797530-aa499d89-579c-40a1-8f89-3987f1003885.png)

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/14138

**Comment by wm75** [comment]
Can confirm the behavior is fixed on usegalaxy.org. Thanks everyone!
