### ISSUE TITLE
Collection items start out in green/ok state as long as they have only queued jobs

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14134]
Note from myself: collections don't have state, the old history panel defaulted to grey until the job state or job state summary were available.

**Comment by wm75** [comment]
and I think this might be because of https://github.com/galaxyproject/galaxy/blob/55588910b5939978ae8d1fe7bd9666e83698d239/client/src/components/History/Content/ContentItem.vue#L151-L162
which will return "ok" for queued states, won't it?

**Comment by wm75** [comment]
Working as it should now on usegalaxy.org. Thanks everyone!
