### ISSUE TITLE
Collection progress bar not shown for non-terminal state collections with no currently running jobs

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#14136]
**Describe the bug**
During the life cycle of a collection its progress bar can appear and disappear multiple times. While the collection has running jobs, the progress bar is displayed, but when all remaining jobs are only queued it disappears until the next job starts running.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05dev on usegalaxy.org
Commit: [81c8a165](https://github.com/galaxyproject/galaxy/commit/81c8a165272076ca156642459804172ca00d2ca7)

**Expected behavior**
The progress bar should be displayed until every collection element has reached a terminal state.

**Additional context**
I think the culprit is here: https://github.com/galaxyproject/galaxy/blob/9a39bd40347019b413cd741fde6e7265b5f7b404/client/src/components/History/Content/Collection/CollectionProgress.vue#L6

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/14182
