### ISSUE TITLE
Collection elements are numbered from zero, when regular history items start from 1

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14132]
For consistency I would argue that collection elements should be numbered from 1, too. Only counter-argument I can see would be that the `__EXTRACT_DATASET__` tool uses zero-based indexing (but says so in the help).

**Comment by dannon** [comment]
TODO: verify in old history that we didn't show number at all, but we can probably just +1 this for display.

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14142

**Comment by wm75** [comment]
Can confirm it's fixed on usegalaxy.org. Thanks!
