### ISSUE TITLE
Collections turn green immediately after resuming from "paused" state

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14130]
In the new history, when even a single collection element is in paused state, the entire collection will be displayed as paused (which is a good thing I guess). When you rerun (with remapping) the failed jobs that caused the dependent collection elements to get paused, however, all paused collections switch to green/ok display immediately, even while the previously failed job is still getting processed.

**Comment by wm75** [comment]
Additional observation: it seems that *all* collections start out in green/ok state as long as they have only queued jobs.

**Comment by wm75** [comment]
Fixed on usegalaxy.org now presumably by https://github.com/galaxyproject/galaxy/pull/14143 as expected.
