### ISSUE TITLE
Switch to History panel doesn't show all history items

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#14141]
The Switch to History panel doesn't show all history items in the table.

Branche: `dev`
Galaxy Version: `22.09`
Commit: f33b465f49bd867efcab22f94eca85975f1476b6

**To Reproduce**
1. Watch the screenshot below

**Expected behavior**
Show all available histories

**Screenshots**
![Switch to history](https://user-images.githubusercontent.com/8046843/174842749-64f4571b-5056-4767-86e6-1ec193864477.gif)

**Comment by davelopez** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14183
