### ISSUE TITLE
Last position in new history lost when returning from inside collection

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#14140]
**Describe the bug**
When scrolling to any collection with the old history, going inside a collection, then back out, you'd land at the same position in your history where you left. With the new history that's no longer the case but you're taken to the top of your history.
This is particularly annoying when working with large histories.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05dev at usegalaxy.org
Commit: [81c8a165](https://github.com/galaxyproject/galaxy/commit/81c8a165272076ca156642459804172ca00d2ca7)

**Expected behavior**
Previous scroll pos in the history should be respected.

**Comment by dannon** [comment]
I believe https://github.com/galaxyproject/galaxy/pull/14139 should address this; xref https://github.com/galaxyproject/galaxy/issues/13746 for the original issue.
