### ISSUE TITLE
Multiple versions of  webpack files conflict perhaps caused by unplanned server restart.

### ISSUE THREAD

**Issue by Naibin** [galaxyproject/galaxy#14145]
**Describe the bug**
Multiple versions of  webpack files conflict perhaps caused by unplanned server restart.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version:{"version_major":"22.05","version_minor":"dev0"}
 

**To Reproduce**
I am developing a galaxy-bio-info platform based on a fedora 34 system.
For some reason, I have to restart the fedora. 
Before I restarted , I  typed "run.sh stop" to stop the galaxy.
Sever echoed  these massages:

WARNING: There was an error checking the latest version of pip.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/var/www/new_galaxy/lib/galaxy/dependencies/__init__.py", line 300, in optional
    conditional = ConditionalDependencies(config_file)
  File "/var/www/new_galaxy/lib/galaxy/dependencies/__init__.py", line 41, in __init__
    self.config = load_app_properties(config_file=self.config_file)
  File "/var/www/new_galaxy/lib/galaxy/util/properties.py", line 81, in load_app_properties
    properties = read_properties_from_file(config_file, config_section)
  File "/var/www/new_galaxy/lib/galaxy/util/properties.py", line 109, in read_properties_from_file
    raw_properties = _read_from_yaml_file(config_file)
  File "/var/www/new_galaxy/lib/galaxy/util/properties.py", line 127, in _read_from_yaml_file
    return yaml.safe_load(f)
  File "/var/www/new_galaxy/.venv/lib64/python3.9/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/var/www/new_galaxy/.venv/lib64/python3.9/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/var/www/new_galaxy/.venv/lib64/python3.9/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/var/www/new_galaxy/.venv/lib64/python3.9/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/var/www/new_galaxy/.venv/lib64/python3.9/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/var/www/new_galaxy/.venv/lib64/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/var/www/new_galaxy/.venv/lib64/python3.9/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/var/www/new_galaxy/.venv/lib64/python3.9/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/var/www/new_galaxy/.venv/lib64/python3.9/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/var/www/new_galaxy/.venv/lib64/python3.9/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/var/www/new_galaxy/.venv/lib64/python3.9/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/var/www/new_galaxy/config/galaxy.yml", line 305, column 3
expected <block end>, but found '<block mapping start>'
  in "/var/www/new_galaxy/config/galaxy.yml", line 1672, column 4

I ignored these text and started the server,after fedora come back safely, 
I typed " make client  " to  rebuilt the client.
In the beginning, it  looks quite good,
while at the end of the client-building messages, bugs  were shown as follows:
**Screenshots**
 
![image](https://user-images.githubusercontent.com/7318522/174933581-53e0e1aa-2f87-4106-aec2-7fc5b48a80e6.png)

It is a corruptive error for a running galaxy server.
 I hope this bug would never appear again for me and any other developer.

**Expected behavior**
I have found  there was a same bug report for terra-toolkit 
https://github.com/cerner/terra-toolkit/tree/main/packages/duplicate-package-checker-webpack-plugin#resolving-duplicate-packages-in-your-bundle

 

**Additional context**
 also I modified the   ./client/webpack.config.js file ,still wont work for me .

**Comment by mvdbeek** [comment]
You're galaxy.yml file wasn't valid:
> yaml.parser.ParserError: while parsing a block mapping
in "/var/www/new_galaxy/config/galaxy.yml", line 305, column 3
expected , but found ''
in "/var/www/new_galaxy/config/galaxy.yml", line 1672, column 4

I don't think there's anything we can fix.

**Comment by dannon** [comment]
Yep, just confirming that the webpack output above is expected and not an error.  Check your config at the specified line as Marius mentions

**Comment by Naibin** [comment]
> You're galaxy.yml file wasn't valid:
> 
> > yaml.parser.ParserError: while parsing a block mapping
> > in "/var/www/new_galaxy/config/galaxy.yml", line 305, column 3
> > expected , but found ''
> > in "/var/www/new_galaxy/config/galaxy.yml", line 1672, column 4
> 
> I don't think there's anything we can fix.

Hi, Mr. Marius, 
Thanks for your comments. I modified the ./config/galaxy.yml file.
  in "/var/www/new_galaxy/config/galaxy.yml", line 305, column 3
    shed_tool_config_file: shed_tool_conf.xml   ----->    #shed_tool_config_file: shed_tool_conf.xml

   in "/var/www/new_galaxy/config/galaxy.yml", line 1672, column 4
    show_welcome_with_login: true     ----->    show_welcome_with_login: false  

then I type: run.sh start;
![image](https://user-images.githubusercontent.com/7318522/175058607-03a0d0ff-b190-46a9-8710-d3daebeb91c6.png)


with these errors, the server looks working well, with a  galaxy-personal title shown.
![image](https://user-images.githubusercontent.com/7318522/175058808-4fc8cb95-ad8f-41eb-9858-99149b89d6c5.png)


Furthermore, when I try to  'make client'  
these warning still remains.
![image](https://user-images.githubusercontent.com/7318522/175059656-a725ab34-fbd8-449c-b360-c45735101203.png)

Perhaps a totally new fresh re-install of the galaxy is needed .

I think it is my fault trying to restart the fedora without noticing the error message or something like that .

Thank you once again,
Best regard,

**Comment by mvdbeek** [comment]
Like dannon said, this is not a problem

**Comment by Naibin** [comment]
> Yep, just confirming that the webpack output above is expected and not an error. Check your config at the specified line as Marius mentions

You have been so open and willing to share your comment with me. Thank you

**Comment by Naibin** [comment]
> Like dannon said, this is not a problem

It will take only 1 minute to solve these minor malfunction errors,  but for me, it is a big problem now.

**Comment by mvdbeek** [comment]
Why is it a problem ? These are peer dependencies that need dependencies in different versions, that is not a problem for webpack

**Comment by Naibin** [comment]
Take 'moment' for example,I hope to choose only one version,.With those
warning shown, the client was not built good enough.

Marius van den Beek ***@***.***> 于 2022年6月22日周三 23:04写道：

**Comment by mvdbeek** [comment]
If you're not seeing the user interface in Galaxy it is not because of that message.

**Comment by dannon** [comment]
Yeah, just to clarify this is webpack saying "Hey, we noticed two versions of this dependency are being included -- there may be some optimization you can do here".  It is *not* saying there's a functional problem.

In some cases, I have addressed this by forcing versions to map to a single version.  In other cases we actually do need to ship multiple versions for compatibility with different third party libraries.

If you look at the last line of your client build there, it says something like:
```
webpack 5.68.0 compiled with 3 warnings in 40765 ms
$ (git rev-parse HEAD 2>/dev/null || echo '') >../static/client_build_hash.txt
Done in 43.32s.
```

So that's a success.  Your client is building fine, no worries.

An error, or failed build, would terminate something like this, returning an error exit code:

```
webpack 5.68.0 compiled with 1 error and 3 warnings in 34328 ms
error Command failed with exit code 1.
```
