### ISSUE TITLE
Remote files dialog shows multi-select checkboxes after clicking back

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14166]
**Describe the bug**
If you open the remote files dialog, and you enter a source, then click back, you can choose multiple root elements.
This doesn't make sense, as you can't do anything but enter the root element.

**Galaxy Version and/or server at which you observed the bug**
22.05

**To Reproduce**
![multi-select-remote-files](https://user-images.githubusercontent.com/6804901/175258465-1ec79515-ca67-4b72-88e0-055cfae1e698.gif)

**Expected behavior**
After hitting back we should have the same interface we started with.

**Comment by davelopez** [comment]
Closing this one as duplicate since https://github.com/galaxyproject/galaxy/issues/14178 contains more info.
