### ISSUE TITLE
Please remove the "Purge this History" option from the history menu (beta history)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#14163]
**Describe the bug**
We've discussed before why to not include the purge history option any place other than the User > History view. When we removed it from the legacy history menu, we stopped getting sos requests for help when someone accidentally purged (despite the pop-up extra step). Purged is not recoverable, or very rarely recoverable. We should do the same for the beta history eg make purging entire histories more intentional via the extra clicking into the full history list. Could get fancy and have this be a redirect to the history panel with "this" history highlighted, but that creates a dependency between the two views (yes?). I vote from just removing it, at least for now when the beta history view will be brand new to most users.

"Delete this History" can probably stay in the beta history -- even though we removed it from legacy. Delete is user recoverable for a short time window.

https://github.com/galaxyproject/galaxy/pull/8024

**Galaxy Version and/or server at which you observed the bug**
UseGalaxy.org
Galaxy version 22.05.dev0, commit [81c8a165272076ca156642459804172ca00d2ca7](https://github.com/galaxyproject/galaxy/commit/81c8a165272076ca156642459804172ca00d2ca7)

**To Reproduce**

**Expected behavior**
Remove the option for the beta history menu. Nothing else needs to change.

**Screenshots**

<img width="288" alt="remove-purge-history-option-beta-history-menu" src="https://user-images.githubusercontent.com/8999735/175128741-b06e9fae-ed6a-415a-9ab7-57f3d6ebf11c.png">

**Additional context**

**Comment by bgruening** [comment]
In addition, we now have a storage dashboard where users can clean data. +1 from my side.
