### ISSUE TITLE
AttributeError raised when using `aliased` on a `Select` object.

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#14160]
SQLAlchemy raises an AttributeError as a result of trying to use `aliased` on a `Select` object. Instead, an explicit `subquery` should be used instead.
Error: https://sentry.galaxyproject.org/organizations/galaxy/issues/85840/?project=3&query=is%3Aunresolved&statsPeriod=14d
Place in code: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/model/__init__.py#L2888
Ref in SQLAlchemy docs: https://docs.sqlalchemy.org/en/14/changelog/migration_14.html#a-select-statement-is-no-longer-implicitly-considered-to-be-a-from-clause
Likely solution: https://github.com/sqlalchemy/sqlalchemy/issues/6274#issuecomment-820014436
(spotted by @mvdbeek )

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14164
