### ISSUE TITLE
[release-testing-22.05] Advanced history search datepicker does not display the selected date

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#14165]
**Describe the bug**
Testing https://github.com/galaxyproject/galaxy/pull/13910
When a date is selected using the date picker in the advanced history search, the date text box is not populated with the selected date. After a search, if the advanced history filters are expanded again the date text box is populated but the text does not update with the selection of a new date.  The search works perfectly and the correct filtering is used as per dates picked, the issue only pertains to the date picker text box.

https://user-images.githubusercontent.com/22670687/175141988-eca6da88-8108-43c1-b229-b4b076ea847a.mov

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org, 22.05

**To Reproduce**
1. Select Advanced Search on a history
2. Search by created date using the date picker

**Expected behavior**
Date filter text box is populated/updated with selected date.

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14226
