### ISSUE TITLE
Recently used rules button in Rule-based Upload Manager does not work

### ISSUE THREAD

**Issue by cumbof** [galaxyproject/galaxy#14175]
The `Recently used rules` history button in the Build Rules for Uploading Collections window never shows up on Chrome. It instead appears with Safari but it's like a button without any specific action. There are no errors in the JavaScript console of both browsers.

Woking on [usegalaxy.org](https://usegalaxy.org) version 22.05

Following screenshot comes from Chrome:

<img width="1220" alt="Screenshot 2022-06-23 at 11 23 45" src="https://user-images.githubusercontent.com/3764656/175336788-95a51a38-393f-45d3-9bf9-fc337ccfbc8d.png">

**Comment by mvdbeek** [comment]
@assuntad23 can you take a look at this ?

**Comment by dannon** [comment]
xref https://github.com/galaxyproject/galaxy/pull/14218
