### ISSUE TITLE
Choose remote files in Upload Manager gets stuck

### ISSUE THREAD

**Issue by cumbof** [galaxyproject/galaxy#14178]
I was trying to work with the `Choose remote files` option in the Upload Manager window. 

At first, I noticed that the file selection checkboxes do not appear immediately but only when browsing to a subdirectory or coming back to the main list of folders.

Second, when selecting a folder it gets stuck, probably it just requires some time to select everything inside that specific folder. The problem here is that you can still browse other folders but it doesn't let you select anything else.

Third, when trying to come back with the `Back` button, it shows up an error message `Invalid target parameter supplied [undefined]`

Working on [usegalaxy.org](https://usegalaxy.org) version 22.05 

https://user-images.githubusercontent.com/3764656/175352991-e8d69377-2c39-4752-93db-e9c37b221a1b.mov

**Comment by davelopez** [comment]
xref #14166

**Comment by davelopez** [comment]
Investigating this one...
It seems the checkboxes *wrongly* appear in the root folders only when you stumble upon an error message. Like when your FTP folder is not defined yet, or your dropbox credentials are not set up, etc.
