### ISSUE TITLE
galaxy-app package should depend on galaxy-selenium?

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#14187]
Since https://github.com/galaxyproject/galaxy/pull/14036 , files in `lib/galaxy/tours/` import from `galaxy.selenium.data` . So, since `tours` is included in galaxy-app, this should depend on galaxy-selenium?
Also, that may mean that we need to move selenium from dev dependency to main dependencies in `pyproject.toml` ?

**Comment by dannon** [comment]
xref https://github.com/galaxyproject/galaxy/pull/14150; I think we decided to just avoid using selenium in core?
