### ISSUE TITLE
Histories API: `url` and `url_contents` contains wrong URLs

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#14185]
**Describe the bug**
Reported by @nsoranzo in chat:
> When doing GET /api/histories/c5cb4a23e5df0848 on [usegalaxy.org](http://usegalaxy.org/) (i.e. 22.05), I see that the url field now is `history?id=c5cb4a23e5df0848` which I don't think it's a real thing?

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01 / 22.05
Commit: 216378abd7b0c828341f8c1a0f1c603e9fe2e1c7

**To Reproduce**
1. Go to http://usegalaxy.org/api/histories/<your-history-ID> or in a local galaxy server
2. The `url` and `contents_url` properties display an invalid URL

**Expected behavior**
These URLs are going to be deprecated at some point, but in the meantime, they should display the correct URL or a deprecation message.

**Comment by nsoranzo** [comment]
Interestingly I cannot reproduce it locally in either 22.05 or dev.

**Comment by davelopez** [comment]
You are probably seeing `*deprecated attribute, URL not filled in by server*` locally, right?

**Comment by nsoranzo** [comment]
Yes, sorry.

**Comment by mvdbeek** [comment]
It get's weirder still. I see the deprecation message when I'm logged in, but for a public url in a private browser session I see the odd url.

**Comment by mvdbeek** [comment]
.... which is a valid url btw 😆

**Comment by davelopez** [comment]
Yeah, it is kind of strange, but may be related to some config in `.org` that is falling back to some other `url_for` logic?.
Anyway, I think those ones can be easily fixed in FastAPI and hopefully, the right API URL can be shown.

**Comment by mvdbeek** [comment]
I doubt this is config related, I see this locally and on usegalaxy.org. publishing the history is what makes this different.

**Comment by davelopez** [comment]
Yeah, you're right, nothing to do with the config. I think I got it in #14186
