### ISSUE TITLE
Wrong priorities when calculating collection "state" from elements

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#14199]
**Describe the bug**
https://github.com/galaxyproject/galaxy/pull/14143 has introduced
`HIERARCHICAL_COLLECTION_JOB_STATES = ["error", "failed", "queued", "upload", "paused", "running", "new"]`
to determine an overall collection state from its elements.
By placing "queued" relatively early in the array it now takes precedence over "running", which causes collections with running jobs and at least a single queued element to be rendered in grey when they should be yellow.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05dev on usegalaxy.org

**Expected behavior**
"running" should definitely have higher priority than "queued".
Less sure about the overall order, I *think* it should be `["error", "failed", "running", "upload", "queued", "new", "paused"]`, but I find "paused" hard to decide on and might be wrong about others, too.

**Screenshots**
The two fastp collections below should be displayed as "running", not "queued".
![Screenshot from 2022-06-25 16-06-03](https://user-images.githubusercontent.com/4742081/175777377-8b59271c-c6ea-4c4f-9143-933ec4578008.png)

**Comment by nsoranzo** [comment]
The main issue has been fixed in #14217, I guess we can revisit the order in a separate issue if needed.
