### ISSUE TITLE
New history panel not updated when switching histories while inside a collection

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#14200]
**Describe the bug**
When you switch the active history (via User -> Histories) while you're inside a collection, the page refreshes but the history panel keeps showing the collection elements of the previously active history.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05dev on usegalaxy.org

**To Reproduce**
1. Create a collection in the active history and navigate into it
2. Choose User -> Histories
3. Click any other history on the resulting page to make it the active history
4. Wait for the page to refresh

**Expected behavior**
The history panel should be switched to the top-level view of the new active history (as was the case previously).

**Comment by assuntad23** [comment]
Fixed with #14493
