### ISSUE TITLE
Error on data transfer from Pulsar to Galaxy

### ISSUE THREAD

**Issue by SergeyYakubov** [galaxyproject/galaxy#14212]
**Describe the bug**

during job execution, it fails sometimes with an error "Remote job server indicated a problem running or monitoring this job".

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01
Commit: 9690680ec7

Pulsar Version: 0.15.0.dev0 (latest commit). Galaxy/Pulsar are configured to use RabbitMQ. Pulsar uses curl to send data.

**To Reproduce**
1. Create a job that runs remotely on Pulsar
2. Run a job
3. Sometimes (about 1 time of 10 :( ) job fails

**Expected behavior**

job does not fail

**Additional context**

My wild guess is that there are some problems inside h11 lib during receiving streamed multi-part requests. I tried to switch to Pulsar requests (an alternative to curl) - same problem. Then I replaced requests_toolbelt with standard requests call (which reads the whole file to memory before sending it) here https://github.com/galaxyproject/pulsar/blob/6caf08406667f63c01a036914a798d88f9064a9a/pulsar/client/transport/requests.py#L27 and did not see that error anymore.  
``` 
files = {'file': ('filename', open(path, 'rb'))}
requests.post(url, files=files)
```

But I might be wrong, I do not have too much experience with Galaxy/Pulsar yet. Anyway, this is Galaxy log with error. It expects to see a beginning of an HTTP request (POST ...), but receives the file content (second part of the message?) and fails

```
[2022-06-28 11:53:48 +0000] [83] [WARNING] Invalid HTTP request received.
Traceback (most recent call last):
  File "/galaxy/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 136, in handle_events
    event = self.conn.next_event()
  File "/galaxy/.venv/lib/python3.8/site-packages/h11/_connection.py", line 443, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/galaxy/.venv/lib/python3.8/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
    raise self
  File "/galaxy/.venv/lib/python3.8/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/galaxy/.venv/lib/python3.8/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/galaxy/.venv/lib/python3.8/site-packages/h11/_readers.py", line 72, in maybe_read_from_IDLE_client
    matches = validate(
  File "/galaxy/.venv/lib/python3.8/site-packages/h11/_util.py", line 88, in validate
    raise LocalProtocolError(msg)
h11._util.RemoteProtocolError: illegal request line: bytearray(b'--------------------------7574d80b5abcde95')
[2022-06-28 11:53:48 +0000] [83] [WARNING] Invalid HTTP request received.
Traceback (most recent call last):
  File "/galaxy/.venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 136, in handle_events
    event = self.conn.next_event()
  File "/galaxy/.venv/lib/python3.8/site-packages/h11/_connection.py", line 423, in next_event
    raise RemoteProtocolError("Can't receive data when peer state is ERROR")
h11._util.RemoteProtocolError: Can't receive data when peer state is ERROR
```

**Comment by SergeyYakubov** [comment]
update: just saw the same error with requests without requests_toolbelt. So whatever method Pulsar uses, Galaxy sometime fails with the above error.

**Comment by mvdbeek** [comment]
Thanks for the report and digging through this.

Unrelated to this issue, but it seems you're running the oldest commit of release_22.01, you should update to the latest commit on the release branch (always recommended!). We only tag the release once, so this is typically the oldest commit you could run for a release, while bugfixes go to the release branch.

**Comment by mvdbeek** [comment]
The error is a little cryptic unfortunately, but if we take it at face value it's saying this isn't a valid HTTP request. Any chance you could try https://github.com/galaxyproject/pulsar/pull/299 and see if that fixes it ? Still weird that it would fail with an error message about the request line, but maybe something goes wrong when parsing the request.

**Comment by SergeyYakubov** [comment]
Sure, I can give it a try. But the error should then happen every time, not only occasionally, I guess.

Thanks for the hint with tags! I missed that point and just pulled a specific tag from the master branch.

**Comment by mvdbeek** [comment]
> Sure, I can give it a try. But the error should then happen every time, not only occasionally, I guess.

Only if path would actually require encoding the url. To be honest I'm not quite sure what values path can take, but I could see this occurring for some files but not others. I guess for an exact re-run I would expect the same outcome, that's true.

**Comment by mvdbeek** [comment]
And yes, we've discussed this internally, it is a perfectly reasonable assumption that we update the tags for bug fixes, and we may do that in the future, but for now it's safest to be at the latest commit on any of the release_* branches that have been released (at which point we create the tag ... you see those rules are not great).

**Comment by SergeyYakubov** [comment]
I now updated dependencies and the error seems to be gone. I'll double-check tomorrow and also check if the latest 22.01 and 22.05 are ok or not. E.g. in my version uvicorn was 0.17.1, after update - 0.18.2, in the latest 22.01/05 - 0.17.6.

URL encoding in Pulsar was noop, the problem is somewhere else (I suspect in 3rd party libs or their combination). Although it is indeed surprising that it worked with slashes in url path parameters

**Comment by SergeyYakubov** [comment]
as for tags - my 2c would be - 
a) get rid of them since you have release branches anyway
b) create tags 22.01.1, etc for bugfixes. Updating original tags would be something people do not expect, I think.

**Comment by mvdbeek** [comment]
Yes, sorry, I meant we'd create new tags, of course tags are meant to be stable.

**Comment by SergeyYakubov** [comment]
Hi, after updating to the latest 22.01 I do not see this error anymore. So, although the reason is not 100% clear, I believe we can close this one.
