### ISSUE TITLE
Citation component: decoded URL issue with doi.org 

### ISSUE THREAD

**Issue by agdiaz** [galaxyproject/galaxy#14225]
**Describe the bug**
Although the citation component is able to fetch the citation data from the DOI id, I noticed that `doi.org` is not handling decoded URLs (`%252F` instead of `/` symbol) properly resulting in 404 not found HTTP errors when it comes from a link, at least in Google Chrome.

Each citation link is generated by:

https://github.com/galaxyproject/galaxy/blob/1b680cbd05d6257118a333b72b3069bea271aad9/client/src/components/Citation/Citation.vue#L5-L7

Where the link content is the result of:

https://github.com/galaxyproject/galaxy/blob/1b680cbd05d6257118a333b72b3069bea271aad9/client/src/components/Citation/Citation.vue#L34-L37

In my example, this citation was declared inside the tool XML as:

```xml
<citations>
        <citation type="doi">10.1093/bioinformatics/btz912</citation>
```

I managed to "reverse" the encoded URL by doing:

```javascript
        link() {
            const cite = this.citation.cite;
            const encodedUrl = cite.data && cite.data[0] && cite.data[0].URL;
            const reverseEncodingUrl = encodedUrl.replaceAll("%252F", "/");
            return reverseEncodingUrl;
        },
``` 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: `{"version_major":"22.05","version_minor":"dev0"}`
Commit: `fd8826904be3f3201f7e7a3b6ffbadd27f268896`

**To Reproduce**
1. Go to Workflow
2. Click on 'Create' and fill out the basic information about this new WF (name: 'test issue citations', annotation: empty)
3. Click on 'Create' again
4. Add a tool with the citations block included
5. Click on the tool and scroll down until "Citations"
6. Click the link icon to open the citation using the DOI URL

**Expected behavior**
I expect to click on the "View citation" link of a tool and open the citation through the DOI id without receiving 404 HTTP errors. 

**Screenshots**
The citation content was loaded with no issues:
![image](https://user-images.githubusercontent.com/1646576/176481729-1e34fcf9-1498-4f72-96e2-ecfde1c05f46.png)

However, the URL links to doi.org do not work properly. 

For instance, in the next example, the `href` content is decoded: 

![Screenshot 2022-06-29 172646](https://user-images.githubusercontent.com/1646576/176478531-3d44707d-c586-44dc-b26e-0e9be2a491ec.png)

Link: `https://doi.org/10.1093%252Fbioinformatics%252Fbtz912`
![image](https://user-images.githubusercontent.com/1646576/176481497-08938b76-1785-44da-89e5-6f83c6adbe8d.png)

After the proposed changes:

![image](https://user-images.githubusercontent.com/1646576/176478831-a746ae31-5d31-4d38-969b-88134e92f219.png)

Link: `https://doi.org/10.1093/bioinformatics/btz912` redirects to `https://academic.oup.com/bioinformatics/article/36/7/2076/5670527`:

![image](https://user-images.githubusercontent.com/1646576/176481595-4294baca-d9e3-41a0-b4f7-e5f2a40e2ef4.png)

**Additional context**

**Comment by assuntad23** [comment]
Fixed with #14231
