### ISSUE TITLE
Dropping files into the upload dialog does not work

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#14228]
**Describe the bug**
Dragging a file into the main upload dialog results in the files being 'downloaded' onto the local machine instead of uploaded to Galaxy. This is on Chrome 102.0.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05; usegalaxy.org

**To Reproduce**
1. Go to usegalaxy.org 
2. Click on upload data
3. Drag a file into the dialog

https://user-images.githubusercontent.com/338642/176502845-d8b2d0fe-91b1-43af-8f0f-da25e92166ff.mov

**Comment by mvdbeek** [comment]
Same is true on older releases, likely a change in chrome that broke this, but it was also not working consistently for me for quite some time.

**Comment by mvdbeek** [comment]
Yeah, only happens when you upload on the welcome page of usegalaxy.org, so this is likely an interaction with the linked page.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/14318 fixed it for me, it's live on usegalaxy.org
