### ISSUE TITLE
History dataset database entry overflows

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#14227]
**Describe the bug**
Setting a value for the database on a dataset that exceeds the width of the dataset box overflows the width of the dataset box. The value also breaks onto a new line in this case, causing inconsistent behavior.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05; usegalaxy.org

**To Reproduce**
1. Set database/build value on a history dataset to rice and see the following

![image](https://user-images.githubusercontent.com/338642/176501330-f8461490-3000-47d3-92cc-3e50f57004b4.png)

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14266
