### ISSUE TITLE
Issue with qname_input_sorted.bam unable to connect to samtools sort

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#14234]
**Describe the bug**

we got this error on our own server and I don't get why this is a problem, as I'm pretty sure this used to just work and does work on [usegalaxy.eu](http://usegalaxy.eu/). The output of bowtie2 is "qname_input_sorted.bam" and does not want to connect to e.g. samtools sort, with the error message "Effective output data type [qname_input_sorted.bam] unknown. This tool cannot be executed on this Galaxy Server at this moment, please contact the Administrator."

The unknown datatype is what I don't get, its listed on the admin ui as a datatype and the probably related converters "CONVERTER_bam_to_coodinate_sorted_bam, CONVERTER_bam_to_qname_sorted_bam and CONVERTER_sam_to_unsorted_bam" are loaded as well.

The datatype does seem to be loaded as seen from the admin UI screenshot below.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09
Commit: 8a02e25c45337b

![error](https://i.imgur.com/lhGF7os.jpeg)

<img width="1148" alt="Screenshot 2022-06-30 at 13 48 13" src="https://user-images.githubusercontent.com/102411/176670037-1677a22d-334a-40f5-b0f7-83cf1ee2b3bf.png">

**Comment by scholtalbers** [comment]
yes sorry for the commit hash, probably screwed that due to merging local changes. Last commits are from december, so I will do a minor update. Thanks for the quick answer.

**Comment by mvdbeek** [comment]
Feel free to re-open if that doesn't solve it

**Comment by scholtalbers** [comment]
Got the latest commit from 21.09 52de57bd4a012e6942dcc84d9b36291cb2b5b2ac but still failing.
Running bowtie2 interactively and/or assigning a bam the datatype `qname_input_sorted.bam` and subsequently running samtools sort works. I just cannot connect the tools in the workflow, although `Split BAM datasets on variety of attributes (Galaxy Version 2.4.0)` does accept the connection.

<img width="1158" alt="Screenshot 2022-07-01 at 09 20 57" src="https://user-images.githubusercontent.com/102411/176845213-83b0967d-2e17-442e-923e-7a23cfdbcd25.png">

**Comment by mvdbeek** [comment]
You've rebuilt the client?
