### ISSUE TITLE
Need clearer indication of 'purged' dataset status in new history.

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#14230]
In this screenshot the first dataset is deleted, and the second is purged.  Note that you can actually tell the difference by observing the disabled actions in the top right, and no download/etc in the lower bar, but there's nothing saying *why* those options are different.

![image](https://user-images.githubusercontent.com/155398/176550453-48a80fb1-fd7e-408d-8b68-a5b5026bc4c1.png)

Could be as simple as adding a tooltip, or maybe we want to bring back a more explicit indicator of some sort.  Suggestions welcome.

**Comment by jennaj** [comment]
I'm voting for a really obvious message inside the dataset at the default view. I know the extra warning boxes/links in legacy history datasets created a lot of clutter, but it communicated the info well. Maybe only mark the purged? Those wouldn't need any links embedded. Purged == no more actions possible.

Related: _Some_ datasets note the size of the data. That doesn't change after purging in the beta history, and makes it seem as if the data are still around and possibly available to restore. The legacy history reset the size to "0 bytes" after a purge. I think that was meaningful content and could use a tweak, too, given recent Q&A from users (three in the last day alone). 

I don't have a specific remedy in mind for both -- but glad we are discussing it.

Thanks Dannon!

**Comment by davelopez** [comment]
Just an idea, how about replacing the disabled operations with a badge with a tooltip?

![image](https://user-images.githubusercontent.com/46503462/176633482-01d891f5-23a2-4bd7-99f4-798c80df57c6.png)

Other variants:
![image](https://user-images.githubusercontent.com/46503462/176633996-a897f02f-5015-44fb-a4e6-a19ca2c1c8eb.png)

**Comment by mvdbeek** [comment]
This is what the old history did, I don't think there's anything wrong with just restoring this ?
![Screenshot 2022-06-30 at 11 05 20](https://user-images.githubusercontent.com/6804901/176638176-3be73e20-5696-4130-bfbb-75383f63d492.png)

**Comment by dannon** [comment]
@davelopez I really like the first option there.  Want to PR that?
