### ISSUE TITLE
Galaxy Tours follow-up

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#1423]
Small list with ideas and ToDo items for Galaxy tours in 16.01 and 16.04. 
## 16.01
- [x] Improve initial Galaxy tours
- [x] Add link to main Galaxy Interface tour to the front page
## 16.04
- [x] make the IDs of tool parameters predictable
- [ ] Try to get [ `backdrop` ](http://bootstraptour.com/api/) working. 
      (This was very useful in the intro.js implementation, as you can highlight specific parts of a complex interface.)
- [ ] Tool specific tool as outlined in [PR](https://github.com/dannon/galaxy/pull/7)
  - [ ] merge into dev as soon as we have branched 16.01
  - [ ] figure our if and how we can integrate tool tours in the global tours registry

More:
- [ ] add support for select field manipulation
- [ ] fix next, prev buttons to improve to resilience
- [ ] support showing the list of tours by visiting e.g. https://usegalaxy.org/tours
- [ ] https://github.com/galaxyproject/galaxy/issues/1492
- [x] https://github.com/galaxyproject/galaxy/issues/1491

xref: https://github.com/galaxyproject/galaxy/pull/1422

**Comment by bgruening** [comment]
@martenson @dannon @guerler please feel free to add or remove items.

**Comment by dannon** [comment]
Functionality added to onload.js allows for links like http://usegalaxy.org?tour_id=core.galaxy_ui, and we can use that on welcome.html.

**Comment by martenson** [comment]
Given the speedy process and non-existent enduser testing of the #1422 I propose (after merge) updating Test with tours asap and temporarily enforce the core.galaxy_ui (or any better if there is one) tour to show on homepage landing for every user to get some feedback. Probably via a nginx redirect with the `tour_id` param? (ping @natefoo )

We might want to tweet about it then and bring some traffic to Test for testing it.

**Comment by dannon** [comment]
@martenson I thought about kicking one off by default for new users (which could be everyone at first), but I was worried it'd be very annoying.  I was thinking/hoping that a nice link on the welcome page (and maybe tweet, once the tour content is halfway polished -- certainly not yet) would be enough.

**Comment by martenson** [comment]
I am not concerned about Test users being annoyed. However I would be concerned about automatically triggering this (at any condition) on Main without good field testing on Test.

**Comment by jxtx** [comment]
> I am not concerned about Test users being annoyed.

I am. People, including ourselves, do use test for things like tools that aren't on main. I'd prefer a prominent button on the welcome page.

**Comment by martenson** [comment]
@jxtx This would be temporary, probably until the 16.01 is out (a month maybe?). Yes, it is annoying, but it could end up being way more annoying on Main. Test is for breaking I have been told.
Also after https://github.com/galaxyproject/tools-iuc/issues/488 there shouldn't be much more tools on Test than Main.

I rest my case here though, won't push it any further.

**Comment by martenson** [comment]
- the step showing history structure in the history tour has invalid selector resulting in:
  ![screenshot 2016-01-11 10 52 35](https://cloud.githubusercontent.com/assets/1814954/12238335/83883d2a-b851-11e5-9830-5a439658d953.png)
- Some of the tour step texts are in "".
- Also often there is stuff happening on the screen (opening modals,  pasting texts, clicking on things...) that are not explained in advance and it makes me a bit confused (and I know most of the Glaaxy UI). Not sure what would be the better approach. Maybe creating a `total_noob` tour?

**Comment by dannon** [comment]
(@martenson deleted comment on the previous issue and moved it here, which was a good idea, so I'm doing the same)

Regarding clicking on things -- this is a hugely important point and I'm really glad you noticed it too.  Unless the tour is intended to be a totally automatic sit-back-and-watch-it type tour (which we can actually build with this), I really think we should keep automatic clicking and text entry to a minimum, instead using text like "Now click this element to open the upload dialog". There is a wait state you can apply to a tour step to advance to the next step automatically upon clicking the element in question, which is what I'd prefer using. People learn more and follow along better when they actually click things and enter text themselves, is my hunch.

That said, this is a major improvement on the previous incarnation, and we can definitely still keep working on it. The Galaxy101 tour I'm doing now does not use our preclick/postclick events, intentionally.

**Comment by bgruening** [comment]
@martenson yes I noted this in: https://github.com/galaxyproject/galaxy/pull/1464#discussion-diff-49282585
I'm willing to remove this step, just wanted to get some feedback first and will fix the "" in the text with the next version if no one is faster.

I can only agree to Dannon here, tours gives you a lot of flexibility and we need to figure out what is the best way to demonstrate Galaxy's capabilities to our users. Automatic tours and manual tours both are useful in different areas. We are trying to work on a semi-automated tour here in Freiburg. The boring stuff is automated the interesting stuff is manual to make it more memorable. I guess we need to get a lot of feedback and try a lot of things out during the next month. So please let the feedback and patches coming!

**Comment by martenson** [comment]
The idea of actually having people click and execute things and just provide them with hints is great. I think that is how the most tours on other pages I have seen worked. I will test the tour on some people around and see how confused they are.

**Comment by dannon** [comment]
Several items on the list are being addressed in #1671.

I'll circle back to check them off whenever that's out of WIP and merged.

**Comment by bgruening** [comment]
@dannon feel free to check them off!

**Comment by guerler** [comment]
xref: #13778
