### ISSUE TITLE
Logins seem case sensitive when they shouldn't be

### ISSUE THREAD

**Issue by Guerande29** [galaxyproject/galaxy#14237]
Hello, 

Galaxy won't let me login.

I have an account (mailen.ortega@udea.edu.co), I enter the password and it is not valid, I try to recover the password and it tells me "The format of the email address is not correct.".

To confirm that my account exists, I try to make a new registration and effectively; galaxy tells me that you already have an account associated with that email. So what can I do to access my account?

Could you help me please
Thank you very much in advance

**Comment by Guerande29** [comment]
Ups! 
It wasn't complicated, but I didn't imagine it, thank you very much.
  :D

**Comment by jdavcs** [comment]
Reopening, as this needs to be fixed in the code base.

**Comment by jdavcs** [comment]
Nope, all works as it should: usernames and emails are treated differently: usernames *are case-sensitive*, whereas emails are *not*.

**Comment by mvdbeek** [comment]
Can you tell us how you've checked this ? Cause it does not appear to be true for old accounts.

**Comment by jdavcs** [comment]
As per discussion in the backend channel. On local instance: modified record in local postgresql database, set username and email to mixed-casing. Logging in works with email using any casing, with username - only the casing in the database. This is on the current dev branch.
```
      email       | username 
------------------+----------
 jDavcs@Gmail.COM | Admin
```

**Comment by jdavcs** [comment]
Double-checked locally and on main, both login and password recovery with mixed-cased email address. Everything appears to work correctly. Please feel free to reopen if this issue resurfaces.
