### ISSUE TITLE
Generating list:list:paired (I think) generates large error message on usegalaxy.org

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#14242]
Building a collection from:

```
a a a f https://usegalaxy.eu/robots.txt
a a a r https://usegalaxy.eu/robots.txt
a a b f https://usegalaxy.eu/robots.txt
a a b r https://usegalaxy.eu/robots.txt
a b a f https://usegalaxy.eu/robots.txt
a b a r https://usegalaxy.eu/robots.txt
a b b f https://usegalaxy.eu/robots.txt
a b b r https://usegalaxy.eu/robots.txt
```

The rules:

```
{"rules":[],"mapping":[{"type":"url","columns":[4]},{"type":"paired_identifier","columns":[3]},{"type":"collection_name","columns":[0]},{"type":"list_identifiers","columns":[2,1],"editing":false}]}
```

generates this message:

![image](https://user-images.githubusercontent.com/458683/176882037-608b40f8-d9de-4eee-bf86-05910ee7a9bb.png)

The error message is unselectable text which impairs users sending the error message to their admins.

**Comment by hexylena** [comment]
On usegalaxy.eu this generates a collection, but fails in new and fun ways:

![image](https://user-images.githubusercontent.com/458683/176889685-7465d2fd-a9c2-4788-bbb3-4f2fe516b0a5.png)

**Comment by hexylena** [comment]
Re-running with robots.txt

**Comment by mvdbeek** [comment]
Haven't deployed https://github.com/galaxyproject/galaxy/pull/14245 on main yet, so that makes sense.
This is on my local instance with robots.txt:

<img width="321" alt="Screenshot 2022-07-01 at 15 07 54" src="https://user-images.githubusercontent.com/6804901/176900715-06fe76ba-8c51-4f4a-9864-c8bc2947000c.png">

**Comment by hexylena** [comment]
yep, works on EU too. So just a .org problem then? Or a 22.05 problem, one of the two.

**Comment by hexylena** [comment]
Ahhh ok, missing the new PR that fixes it, ok, that makes sense. Thanks @mvdbeek
