### ISSUE TITLE
Cannot create list of list of pairs from UI

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#14241]
I'm trying to reproduce an issue a user reported, wherein they're trying to flatten a list:list:paired collection. However, the UI prevents me from creating that, it seems? `b` and `c` are both `list:paired`.

![error message reading: The following selections could not be included due to problems:  b is a collection, this is not allowed. a is a collection, this is not allowed ](https://user-images.githubusercontent.com/458683/176880203-2ad572af-3316-4534-98fa-fbcf07f45b8b.png)

I guess this is intentional, but then how should I create my list:list:paired collection?

**Comment by mvdbeek** [comment]
You can use the apply rules tool.

**Comment by hexylena** [comment]
That only works on single collections right, is there a way to use that to create a collection from multiple collections?

**Comment by mvdbeek** [comment]
Not directly, but you can use https://usegalaxy.org/root?tool_id=__BUILD_LIST__ to build a single collection, then reshape it

**Comment by assuntad23** [comment]
Is this a duplicate of #11245?
