### ISSUE TITLE
[release-testing] Delete button on dataset details page does not work

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#14259]
In 22.01 it was possible to delete a dataset via the dataset details page (accessed via the `i` icon in the history) - see the button on the right of the screenshot below.

![image](https://user-images.githubusercontent.com/32272674/177302399-75161bca-76d1-4387-95aa-e35cd6fd2d07.png)

In 22.05 clicking this button has no effect.

**Comment by ahmedhamidawan** [comment]
Maybe use this here? Just an idea...
https://github.com/galaxyproject/galaxy/blob/c14c1f57209faffe736422ea691bd29385fe28f7/client/src/components/History/Content/ContentItem.vue#L123

**Comment by guerler** [comment]
Thanks @ahmedhamidawan, I added a PR. I noticed that `isHistPanel` seems to be equivalent to `isHistoryItem`, can you check to verify that.
