### ISSUE TITLE
Improve SLURM stderr parsing and filtering

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#1426]
Currently we look for this message to detect if a job was killed for exceeding the memory CR:

```
slurmstepd: error: Exceeded job memory limit
```

However, in some versions, the following may be displayed:

```
slurmstepd: Exceeded job memory limit
```

Additionally, SLURM will sometimes log this message even if the job is not killed. This should be stripped from the stderr of successful jobs (and appended to stdout??) to prevent them from failing:

```
slurmstepd: error: Exceeded step memory limit at some point. Step may have been partially swapped out to disk.
```

Related: http://bugs.schedmd.com/show_bug.cgi?id=1682

**Comment by jmchilton** [comment]
Now that we have the tool command in a completely separate script from the job script - I wonder if we should just universally redirect all tool standard output and standard error to files and not have job script problems or metadata logging interfere with the job. It would eliminate false negatives (red boxes that should be green) and seems more correct, but it would create false positives (green boxes that should be red).

**Comment by natefoo** [comment]
+1 to separating, but I think we should then set two different types of failure for the job - system failure or tool failure. In fact I had a trello card for this (but with the added failure type of "the tool asserts that this failure is your own fault").

We could also consider having the job script use `set -e`.

The base runner needs a method to filter things out of stdout/stderr based on a list of regexes, which can then be used by the subclasses to filter out messages that should not cause failure. Or better yet, indicate whether a regex should indicate failure for the tool or not, the failure message if it does indicate failure, and control over whether it should be filtered out of the output.

**Comment by lparsons** [comment]
I also see:

```
slurmstepd: error: Exceeded job memory limit at some point. Job may have been partially swapped out to disk.
```

**Comment by nsoranzo** [comment]
:+1:

I have the same message of @lparsons with SLURM 14.11.4 .

**Comment by lparsons** [comment]
@nsoranzo I've patched slurm.py to avoid errors on tools that don't actually fail for now: see https://gist.github.com/lparsons/c6a0dec011c08891d1a6dd3ecdf09d6b. Not sure if this should just be submitted as a PR since the larger fix seems like it may take time. Thoughts @jmchilton and @natefoo?

**Comment by ericenns** [comment]
@natefoo 

I see the following with slurm 15.08.4:

```
slurmstepd: Job 976744 exceeded virtual memory limit (20144560 > 18454937), being killed
```

**Comment by nsoranzo** [comment]
@ericenns Does the job terminate as failed (i.e. red) in Galaxy? If yes, that's correct.

**Comment by ericenns** [comment]
@nsoranzo It does, but we can't set the job to resubmit with more memory as galaxy doesn't understand it as job failure due to memory

**Comment by nsoranzo** [comment]
@ericenns If you mean automatic job resubmission, then I have to leave it to @natefoo since I never used this feature.

**Comment by mvdbeek** [comment]
I think we've come pretty far with regards to separating tool stdout/stderr from job stdout/stderr in https://github.com/galaxyproject/galaxy/pull/7095 and there's regular PRs coming in to update the regex used to determine the job state in the slurm runner. For further planning we can discuss things in https://github.com/galaxyproject/galaxy/issues/3107
