### ISSUE TITLE
Fix Data Dashboard: listing of histories is incorrect, count is correct

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#14267]
**Describe the bug**
This new function needs a bit more tuning: https://github.com/galaxyproject/galaxy/pull/14253

**Galaxy Version and/or server at which you observed the bug**
UseGalaxy.org as of about 6 hours ago
Galaxy version 22.05.dev0, commit [81c8a165272076ca156642459804172ca00d2ca7](https://github.com/galaxyproject/galaxy/commit/81c8a165272076ca156642459804172ca00d2ca7)

**To Reproduce**
1. Have a registered account with at least one deleted history plus a few deleted datasets in an active history
2. Go to any history and click on the "database" icon to reach the Data Dashboard
3. Click into the button to review your data
4. The left box is for deleted-but-not-purged datasets; the right is for deleted-but-not-purged histories
5. Click in to manage the histories -- the count and size is correct but the listing in the box contains the account's deleted datasets, not deleted histories (these are same datasets as when you click into the right box from what I can tell).

**Expected behavior**
List the deleted histories. The number of items in the list should match the count.

**Screenshots**
<img width="702" alt="Screen Shot 2022-07-05 at 12 46 57 PM" src="https://user-images.githubusercontent.com/8999735/177421925-26a85b39-d04d-4d8e-93c0-643f117ab541.png">

**Additional context**

**Comment by davelopez** [comment]
After some investigation, the problem seems to be related to the way the dialog is shown, not the new plugin for listing deleted histories. 
The one that you open first is the one that will stick around.
Working on a fix...

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14271

**Comment by jennaj** [comment]
Works great!! Thank you

**Comment by jennaj** [comment]
Oh, just found that now the list of deleted datasets is wrong. I don't think it was wrong yesterday -- but it is now. See the new ticket.

**Comment by mvdbeek** [comment]
We haven't updated main. You can see the last build date if you open the javascrip console in your browser:
![Screenshot 2022-07-08 at 11 42 33](https://user-images.githubusercontent.com/6804901/177953817-7ff2000a-47cd-4455-8d23-d01e2de7fac8.png)
