### ISSUE TITLE
Add Data Dashboard: Link account data summary in User > Preferences to the Dashboard view, removing an incorrect FAQ

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#14268]
**Describe the bug**
1. The FAQ linked at the bottom of the User > Preferences page is very stale, and not even displayed on the Hub anymore. 
2. The help will not match the updated UI and was confusing to begin with.
3. The Dashboard should be accessible on the preferences page since it is an account level function. The FAQ was a patch solution with very little value, and none now. We have the real solution as of 22.05 directly in the app. The internal view-to-view content is enough to understand what is going on. We have little trash icons everywhere, and clearer menus and functions about restoring/deleting/purging in the history itself. We have tutorials, help site, etc for all of the details that were … tedious. Those external sites are pending an update. Replacing an old FAQ with new FAQ isn't even possible yet. BUT -- we can help users, now and directly, in the application.

**Galaxy Version and/or server at which you observed the bug**
UseGalaxy.org
Galaxy version 22.05.dev0, commit [81c8a165272076ca156642459804172ca00d2ca7](https://github.com/galaxyproject/galaxy/commit/81c8a165272076ca156642459804172ca00d2ca7)

**To Reproduce**
1. Go to User menu, select Preferences, and scroll to the bottom.

Remove the extra text/URL, internally redirect to the Data Dashboard, and drop the invalid documentation. 

Existing content:

> You are using N.N TB of disk space in this Galaxy instance. Your disk quota is: NNN GB. Is your usage more than expected? See the [documentation](https://galaxyproject.org/learn/managing-datasets/) for tips on how to find all of the data in your account.

Replace with:

> You are using N.N TB of disk space in this Galaxy instance. Your disk quota is: NNN GB. Is your usage more than expected? Review your **Data Dashboard**. 

"Data Dashboard" links to the https://usegalaxy.org/storage view for the account, and that person can use all nested actions the same as if reached the dashboard from the new/beta history.

**Lobby**
The Dashboard is a standout feature. The UX is different in all great ways: larger font, center justified, more graphics than usual, and the focus is clearly just on one conceptual function with context — getting rid of whatever you decided to deleted before, with one last glance, to make room for new work.

That was always the idea for the data management workflow (yes?): active is what you care about, deleted is what you _probably_ don’t care about, and purged finally frees up the space.

I vote for making the app itself as clean and self-referencing as possible, and I think this one more little change would be very good, if not necessary, this release (22.05) to close the loop and avoid user confusion.

**Additional context**

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14270

**Comment by jennaj** [comment]
Hi -- two minor tweaks please

1. The link from User > Preferences is pointing to `https://server.url/storage/management` instead of the top level `https://server.url/storage`. 
2. The linked text "Storage Dashboard" should be in a bold font. It is a bit hard to tell it is a link unless hovered over. Everything else important or linked on that view (user > preferences) is bold, so this makes the styling more consistent.
