### ISSUE TITLE
Running `manage_db.sh upgrade` on an uninitialized database raises an error that is not helpful

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#14276]
Running `manage_db.sh upgrade` on an uninitialized database raises an error that is not helpful at all.

On sqlite (uninitialized, may or may not exist: doesn't matter):
```
[truncated]
    self.dialect.do_execute(
  File "/[path-to-galaxy]/.venv/lib64/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: workflow
[SQL: ALTER TABLE workflow ADD COLUMN source_metadata BLOB]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

On postgresql (uninitialized, but must exist):
```
  File "/[path-to-galaxy]/.venv/lib64/python3.9/site-packages/sqlalchemy/dialects/postgresql/base.py", line 3536, in get_table_oid
    raise exc.NoSuchTableError(table_name)
sqlalchemy.exc.NoSuchTableError: workflow
```

(If the postgresql database does not exist, the error is fine:
```
[truncated]
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "galaxy_t9" does not exist
```

**To Reproduce**
1. Delete the sqlite database (the default one or the one set in `galaxy.yml`) OR get a fresh clone and do NOT start galaxy.
2. Run `./manage_db.sh upgrade`
3. See error

For postgresql, same as above, except the database must exist.

**Expected behavior**
Either the displayed message should be more helpful, or the documentation should include this as a troubleshooting example.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/14329
