### ISSUE TITLE
Fix Data Dashboard: list of deleted datasets is the same as list of deleted histories (reverse of the prior issue)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#14278]
**Describe the bug**
The reverse of this is now happening: https://github.com/galaxyproject/galaxy/issues/14267

History list is correct, dataset list is the history list instead of dataset list but has the correct count

**Galaxy Version and/or server at which you observed the bug**
UseGalaxy.org
Galaxy version 22.05.dev0, commit [81c8a165272076ca156642459804172ca00d2ca7](https://github.com/galaxyproject/galaxy/commit/81c8a165272076ca156642459804172ca00d2ca7)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by davelopez** [comment]
Hi @jennaj!
If you are trying in usegalaxy.org the fix may not be yet deployed.

**Comment by jennaj** [comment]
Ok -- good! Because I seem to be getting the problem both ways today. Seems to depend on if I let the two lists load completely or not before clicking into one of them. I'm testing, but also stress testing a bit with an older account, with a lot of data in all states.

On that second page of the view, maybe we shouldn't let users click to open/review either lists until the page is fully loaded (?). Or maybe that delay is just something that comes up when there is a ton of data to sort through (datasets and histories). 

Once this is on org, I'll test it both ways: 1) new account/little bit of newish data versus 2) old account/lots of mixed data

**Comment by jennaj** [comment]
Works great now! Fabulous new summary functionality.

Tested at: UseGalaxy.org
Galaxy version 22.05.rc1, commit [b0a526da8d4f02d0d4468ba49c4501af727138a0](https://github.com/galaxyproject/galaxy/commit/b0a526da8d4f02d0d4468ba49c4501af727138a0)
