### ISSUE TITLE
'beta' on storage manager doesn't pass WCAG contrast thresholds

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#14298]
The 'beta' label here:

![image](https://user-images.githubusercontent.com/458683/178256583-b9925a06-0eac-4f6f-ac97-72462a3e4f8d.png)

reports a 1.3 contrast ratio, not passing AA. `#717273` is about the minimum to pass contrast.

**Comment by davelopez** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/14302
