### ISSUE TITLE
Storage manager: deleting history then dataset doesn't refresh interface, only lists histories to be deleted

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#14299]
I was going to delete a history, then delete datasets for the release notes demo, and encountered this bug where selecting datasets only showed histories and wouldn't refresh (despite some datasets being available to delete.)

![small storage-dashbaord](https://user-images.githubusercontent.com/458683/178257356-17252d67-7cb6-4b7b-a8ec-6a403f82e4f8.gif)

**Comment by davelopez** [comment]
I think this is a duplicate of #14267
Should be fixed in #14271

**Comment by hexylena** [comment]
thanks @davelopez
