### ISSUE TITLE
Workflow editor scroll based zooming is relative to top left, not mouse location

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#14295]
I think this behaviour contradicts most scroll-to-zoom interfaces, and it could be a bit nicer if the zooming was done around the mouse's position.

![gif of a workflow being zoomed, only zooms in and out of top left corner.](https://user-images.githubusercontent.com/458683/178244710-d945428f-4224-4be2-9aa9-e75954020e03.gif)

**Comment by nsoranzo** [comment]
Duplicate/related to https://github.com/galaxyproject/galaxy/issues/13852 ?

**Comment by dannon** [comment]
Yep, duplicate.

**Comment by hexylena** [comment]
thanks y'all!
