### ISSUE TITLE
Imported workflows do not retain tool positions

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#14303]
I exported this workflow and re-imported it on the same instance, and all of the layout and positioning was lost.

![image](https://user-images.githubusercontent.com/458683/178285390-29562692-cfbb-4744-8664-74ec5ce59615.png)

reported on Galaxy 22.01

**Comment by mvdbeek** [comment]
The editor works very differently at this point, if this still happens feel free to re-open or create a new issue.
