### ISSUE TITLE
Different tool versions are no longer properly handled.

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#14311]
Noticed on release_22.05, while debugging https://github.com/galaxyproject/galaxy/pull/14309 (with different versions).

When switching between tool versions, the version text displayed changes, but the tool inputs, etc. do not change. This is when changing in the UI.

If I manually go to a page and load by tool_id and tool_version, correct details were displayed.

**Comment by mvdbeek** [comment]
Can't confirm, this is working fine, feel free to test this on usegalaxy.org, screenshots are made using the tool version switch button. I guess you'll also want to avoid the tool cache (it's really only there for anvil at this point, I already removed it but we had it back in). Other than that feel free to re-open with instructions for reproducing this.
![Screenshot 2022-07-12 at 11 24 38](https://user-images.githubusercontent.com/6804901/178445765-96e4a22c-d467-49f6-8828-78a103a2ef4e.png)
![Screenshot 2022-07-12 at 11 24 47](https://user-images.githubusercontent.com/6804901/178445780-e567e5c3-0de4-44ce-b630-4b491b53e825.png)

**Comment by blankenberg** [comment]
![tool-interface-no-update](https://user-images.githubusercontent.com/1231190/178545124-fe566408-1a3c-4b53-ac41-f62d69b0b5e8.gif)

**Comment by mvdbeek** [comment]
I don't know what I'm seeing there. You on a vanilla Galaxy ?

**Comment by blankenberg** [comment]
release 22.05, with https://github.com/galaxyproject/galaxy/pull/14309.

**Comment by blankenberg** [comment]
The 1.0.0 has `User inputs` repeat, the 0.3 has `Include data into the environment` multidataset input. But when loaded by clicking from tool panel and switching versions, the tool inputs is always shown as `User inputs` repeat.
