### ISSUE TITLE
Paginate History Store

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#14317]
We are currently [loading all the user histories in the store](https://github.com/galaxyproject/galaxy/blob/release_22.05/client/src/store/historyStore/historyStore.js#L104).
As discussed in the UI/UX meeting we should add pagination there and load only on demand.

**Comment by davelopez** [comment]
I wonder how would the server comparatively performs about *Stack 2* in https://github.com/galaxyproject/galaxy/issues/14322#issuecomment-1184670268 with #14349 and #14347 in place :thinking:

**Comment by mvdbeek** [comment]
It appears we're also triggering a fetch of all histories when opening the tool form (https://usegalaxy.org/api/histories?view=summary). That's also quite expensive for users with a lot of histories. I have about 150 histories on .org (I don't think that's a lot), and the response time varies from 10 seconds to 90 seconds.

**Comment by mvdbeek** [comment]
From the API perspective we have a bunch of useful filters, like `https://usegalaxy.org/api/histories?view=summary&order=update_time&limit=10&q=update_time-gt&qv=2023-02-04T21:39:53.561410` that can be used to restrict the amount of data to fetch when you already have histories in the store.
