### ISSUE TITLE
tool wrapper <options from_dataset> with undocumented behavior

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#14324]
https://docs.galaxyproject.org/en/latest/dev/schema.html#from-dataset doesn not really talk about which kind of format the dataset from which to populate the dropdown should have. Since you populate the dropdown from columns of the dataset, at a minimum those must be defined somehow.
I tested this today with input of format="csv" and it turns out that you never get any options in that case.
Looking into the source code I found that
https://github.com/galaxyproject/galaxy/blob/80b726eb6de08218c652b99ea39b4c3af4385ef9/lib/galaxy/tools/parameters/dynamic_options.py#L555
describes an undocumented attribute "separator", and when I include this in the options like so:
`<options from_dataset="my_input_dataset" separator=",">` then Galaxy will happily populate my dropdown with the selected columns of a csv.

For my specific usecase this is good enough, but:
1. I'm feeling bad using an undocumented feature (or at least I *think* it's undocumented)
2. hard-coding the separator like this does seem strange when Galaxy, for columnar datatypes, should already know about the separator

So is it just oversight that the separator attribute isn't documented and it can be used safely?
Should Galaxy introspect the separator instead?<options from_dataset="genome_list" separator=",">

**Comment by bernt-matthias** [comment]
Can you check if we have a tool test for this?

**Comment by wm75** [comment]
There don't seem to be any tests here and I don't find an example in tools-iuc either. Everything seems to be using tabular input.

Filters? How? With something like `<filter type="multiple_splitter" column="4" separator=","/>`?
That might work (but haven't tested). Wouldn't call it well-defined though because what's column number whatever in a csv file then (it doesn't have just one column does it?)

**Comment by wm75** [comment]
> Btw. does the xml linter complain about the separator attribute. It seems to be missing in the xsd file?

Ah, that's a good point. Had forgotten linting before and, yes, you're right it's failing as you expected.

**Comment by bernt-matthias** [comment]
@wm75 .. have a look here https://github.com/galaxyproject/galaxy/pull/14332 .. I targeted 22.01

**Comment by bernt-matthias** [comment]
We can still think of getting the separator from the datatype.. But I would still keep the separator attribute, since I could also imagine cases where txt files are used.

Could you open a new issue if you agree.
