### ISSUE TITLE
Release notes for 16.01

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1434]
https://github.com/galaxyproject/galaxy/pull/868 and the tag PR had a lot of comments about perceived deficiencies in the release note process. Some people wanted more detail, some less - some people wanted more categories, some less. I don't think there was a clear consensus on anything or when there was I did feel like my process was capturing the spirit of many requests. So in light of that, if someone else wants to do the release notes they should volunteer and demonstrate a new vision, I will take zero offense and go do something more fun.

If no one does by Friday, I'll work on it and I'll adapt my previous process to the new tags. My current feeling is that 15.05 and 15.07 had great release notes and this is what I will continue to strive for automating to (but now with the addition of tags and richer metadata that we now have - or will have once all of the 16.01 PRs are actually tagged properly). 15.10 release notes kind of stunk, I was too busy and distracted with conference stuff.
- https://github.com/galaxyproject/galaxy/blob/dev/doc/source/releases/15.07.rst
- https://github.com/galaxyproject/galaxy/blob/dev/doc/source/releases/15.07_announce.rst
- https://github.com/galaxyproject/galaxy/blob/dev/doc/source/releases/15.05.rst
- https://github.com/galaxyproject/galaxy/blob/dev/doc/source/releases/15.05_announce.rst

I think at some point it was suggested that the release notes could literally just be [this link](https://github.com/galaxyproject/galaxy/pulls?q=is%3Apr+is%3Amerged+milestone%3A16.01) plus a top line summary or a couple key features. If there are multiple +1s to that idea, I am not going to insist on curated release notes - but my current feeling is they provide value.

**Comment by martenson** [comment]
I like the release notes format since 15.07 and would like to continue in the same manner while saving as much time using the metadata from labels.
(iow :+1: for John doing it :D)

**Comment by hexylena** [comment]
:+1: for curated release notes.

**Comment by lparsons** [comment]
:+1: for curated release notes. A complete list of changes is very helpful as well, but something that highlights the big changes is very helpful. Recognition of two major audiences is also potentially helpful, end users and administrators.

While I'm at it, I'd like to suggest that the git instructions should show someone how to get a version, not just stable. IOW, `git checkout 'release_15.10'` instead of `stable`.

**Comment by jxtx** [comment]
+1 for curated notes, these are well worth it.
