### ISSUE TITLE
"Old style" display applications are no longer accessible

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#14341]
e.g. a BED file can no longer be viewed at UCSC genome browser as a custom track, since display links are not listed under datasets in new history and "old style" display applications are not listed under Visualize link.

**Comment by dannon** [comment]
Interesting URL generated for it in the old history, too:
```
https://usegalaxy.org/*deprecated%20attribute,%20URL%20not%20filled%20in%20by%20server*?redirect_url=http%3A%2F%2Fgenome.ucsc.edu%2Fcgi-bin%2FhgTracks%3Fdb%3Dhg19%26position%3Dchr19%3A60951-374421%26hgt.customText%3D%25s&display_url=https%3A%2F%2Fusegalaxy.org%2F%2Adeprecated+attribute%2C+URL+not+filled+in+by+server%2A%2Fdisplay_as%3Fid%3D9323941%26display_app%3Ducsc%26authz_method%3Ddisplay_at
```

**Comment by davelopez** [comment]
> Interesting URL generated for it in the old history, 

Sounds like another `url_for` that needs to call the FastAPI compatible `url_builder` instead.
