### ISSUE TITLE
Change logging statement

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#14354]
Nate was saying he wished the following log statement would be changed, as it is confusing: ´Executed 1 job(s) for tool XXX request:`

I guess its: https://github.com/galaxyproject/galaxy/blob/4644922783bd710d38e7a5dcae199dbffe91ac81/lib/galaxy/tools/execute.py#L36

**Comment by nsoranzo** [comment]
@natefoo What about `Created ${job_count} job(s) for tool ${tool_id} request` ?
