### ISSUE TITLE
Bug: FastQC webpage output fails complete download from disc icon

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#14365]
**Describe the bug**
1. The `webpage` (.html) output from **FastQC** fails to download when using the disc icon.
2. The `raw data` (.txt) output from **FastQC** downloads successfully.
3. The `webpage` (.html) and `raw data` (txt) output from **MultiQC** download successfully.
4. The `webpage` (.html) output from FastQC will downloaded successfully using **curl** or **wget** if the copied dataset URL is modified.
5. _**It is not clear if this is a tool issue (metadata/URL), or an issue related to the 22.05 pre-release.**_ 
6. Presents in both new/beta history and legacy history in the 22.05 pre-release. 

**Galaxy Version and/or server at which you observed the bug**
UseGalaxy.org (bug presents): Galaxy version 22.05.rc1, commit b0a526da8d4f02d0d4468ba49c4501af727138a0
UseGalaxy.eu (but does not present): Galaxy version 22.01

**To Reproduce**
1. Generate a **FastQC** output, or import the test histories below.
2. Click on the download disc icon from `webpage` (html) output.
3. Download will start, stall out, restart a few times, and eventually fail.
4. Presents in at least these web browsers under MacOS: Firefox, Safari, Chrome

**Expected behavior**
Successful download of a `[output].zip` archive of data.

**Screenshots**
<img width="241" alt="failed-download-example" src="https://user-images.githubusercontent.com/8999735/180482312-9de35d0a-8d4b-4864-85c7-718f7ca41f16.png">

**Test histories**
* https://usegalaxy.org/u/jen/h/test-fastqc-webpage-download
* https://usegalaxy.eu/u/jenj/h/test-fastqc-multiqc-download

**Workaround**
1. Copy the URL for the webpage (.html) output dataset, remove "to_ext=html" at the end of the URL, and use **curl** or **wget** on the command line to download a single file named `[output].zip` that extracts to a single file named `[output].html`.
2. Example command string `curl -o out.html --insecure 'https:/usegalaxy.org/api/datasets/f9cad7b01a472135987ad5307248c882/display?'`

**Comment by mvdbeek** [comment]
I don't think that's a UI bug, probably the use of mod-zip is the culprit here.

**Comment by mvdbeek** [comment]
That'll be fixed once we deploy https://github.com/galaxyproject/galaxy/pull/14417
