### ISSUE TITLE
Datatype modules blast, molecules, spaln contain incorrect class method definition

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#14383]
In datatype modules `blast.py`, `molecules.py`, and `spaln.py`, the class method `split` is defined without the `@classmethod` decorator. This was intended to be a class method because (a) it is defined as such in the parent class + in other datatype classes; and (b) the first argument is `cls`. 

In all these cases the method returns `None` if `split_params is None` or raises a `NotImplementedError`. Still, this is incorrect. The method should be either (a) marked as a class method, because if it is invoked as a class method now, it will throw a TypeError; or (b) the first argument should be renamed from `cls` to `self`, otherwise it may cause confusion.

I'm not changing this yet because I am not sure whether it might be invoked as an instance method. I assume not? I'll make the change unless there are comments.

Ref:
Parent class definition: https://github.com/galaxyproject/galaxy/blob/release_22.05/lib/galaxy/datatypes/data.py#L1023
Example of incorrect definition: https://github.com/galaxyproject/galaxy/blob/release_22.05/lib/galaxy/datatypes/blast.py#L236

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/15052
