### ISSUE TITLE
Bug Beta History: View toggles from correct view to "0 GB" at usegalaxy.org 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#14382]
**Describe the bug**
Bug: The history view loads correctly, then toggles to "0 B".
* The dataset icons are reduced down to just "active" with "0" count.
* The "Copy Datasets" function is missing even though the datasets are listed out.

**Galaxy Version and/or server at which you observed the bug**
UseGalaxy.org
Galaxy version 22.05.rc1, commit b0a526da8d4f02d0d4468ba49c4501af727138a0

**To Reproduce**
1. Go to the history view ("house" icon in the masthead)
2. The view may have already flipped to the stripped version at this step.
3. If not, choose a different active history ("switch to history" or under User -> Histories)
4. Sometimes will flip within a few seconds by itself, or do some stuff: load a tool or two into the middle panel, or expand a few datasets.
5. Refresh the view -- doesn't always resolve to the correct view.
6. Reload the history ("switch to history" or under User -> Histories) -- always resolves to the correct view.

**Expected behavior**
A persistent, correct, history view.

**Screenshots**

**correct**

<img width="286" alt="Screen Shot 2022-07-27 at 1 12 18 PM" src="https://user-images.githubusercontent.com/8999735/181365314-9877557c-4ff5-4594-9f11-fb758b340226.png">

**incorrect**

<img width="292" alt="Screen Shot 2022-07-27 at 1 15 31 PM" src="https://user-images.githubusercontent.com/8999735/181365418-ecc3ba65-031c-43c2-abe5-253aa275e4a7.png">

**Additional context**
I think I saw this last Friday, but as of today it is very obvious.

**Comment by davelopez** [comment]
Hi @jennaj, this bug is known and has likely been addressed in #14357 but it seems usegalaxy.org does not have the latest bug and performance fixes deployed yet.

Can you please try again when the server gets updated? Thanks!

**Comment by dannon** [comment]
Confirmed this is fixed locally for me, so I'm going to go ahead and close this.
