### ISSUE TITLE
Copy datasets should be a default "with entire history" option

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#14401]
**Describe the bug**
In the new hstory *Copy Datsets* is the top-most choice for the history datasets operations, but only if there are datasets in the history.

![image](https://user-images.githubusercontent.com/4742081/182819981-550e2d92-6029-46ad-ad5e-6587207c4300.png)

For an empty history, there are no options to select from.

Copy Datsets, however, takes you to a page that allows you to copy datasets from and *to* any history so it can be a way to populate an empty history with some intial data, and the option to do so should be available also in the new history.

Two options here:
- enable the option also for an empty history
- move the option up to the history options if you feel this is the better place then.
  E.g., there could be an item "Copy datasets between histories" just below "Show Histories Side-by-Side".

**Comment by dannon** [comment]
Fixed in #14402
