### ISSUE TITLE
Configurable per-user limits for celery tasks 

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14411]
We don't have a way to set per-user limits like we have for the job running system. For (potentially) longer running celery tasks this is important to add so a single user can't (inadvertently) take over all celery worker resources.

**Comment by claudiofr** [comment]
Please assign this to me.

**Comment by mvdbeek** [comment]
> Can we assume that you will always use a thread based pool rather than a process based pool like prefork

Yes, our cancelable tasks depend on this being a thread based pool.

> How many worker pool instances do you have in production? Do you ever use more than one?

I am not sure how many worker process we run, but on the large Galaxy instances there are ideally multiple VMs dedicated for running celery workers, each with multiple celery worker proceses.

> If we can assume a single thread based pool then I can implement the list of user id’s with the last task schedule time in memory rather than in the database.

I don't think that assumption works for production setups.
