### ISSUE TITLE
Copy workflows on import

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1441]
Currently when importing a StoredWorkflow, the latest_workflow is just assigned to the new StoredWorkflow. This means that `worklfow.stored_workflow` won't work - which is used in various places. I believe the correct solution is to copy the Workflow - this is needed more than ever with subworkflows and should be implemented in 16.01.

**Comment by hexylena** [comment]
Noted on #1387

**Comment by jmchilton** [comment]
Fixed-ish with #1474
