### ISSUE TITLE
Search bar in history panel is case sensitive.

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/galaxy#14416]
**The search bar in the history panel is case-sensitive**

Typing "bamcoverage" yields no results for the bamCoverage tool, as well as typing "join" for the Join tool.

**Observed both on EU and ORG**

* https://usegalaxy.org/api/version: `{"version_major":"22.05","version_minor":"rc1"}`
* https://usegalaxy.eu/api/version: `{"version_major":"22.05","version_minor":"rc1"}`

**To Reproduce**
1. Go to any usegalaxy instance running 22.05rc1
2. Load or import a history
3. Search for any item with a capital letter in the name

**Expected behavior**
I'd expect that "bamCoverage" datasets would be returned for a query of "bamcoverage"
Or, that there would be an option in the drop-down search menu to disable case-sensitive searching.

**Screenshots**
![case](https://user-images.githubusercontent.com/20641402/183607602-1aef8056-6cbf-4d08-85ff-430fbc1b26ce.png)

thanks to Chiara Schröder for finding this!

**Additional Context**

Possibly related to these old bugs: https://github.com/galaxyproject/galaxy/issues/831, https://github.com/galaxyproject/galaxy/issues/9692

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14426, thanks @mtekman @davelopez !
