### ISSUE TITLE
Workflow Editor: Insert steps from starred workflow broken.

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#14421]
**Describe the bug**
Insert steps from workflow (not as subworkflow) is broken in Firefox; works in Chrome.  The modal never appears for confirmation, so nothing happens.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05

**To Reproduce**
1. Go to workflow editor
2. Click icon here:
![image](https://user-images.githubusercontent.com/155398/183663456-01b09d39-407e-4117-a4fb-40603d880a31.png)

**Expected behavior**
Should insert steps into current workflow.  It doesn't.

Reported on Matrix by @innovate-invent.  Thanks!

**Comment by dannon** [comment]
I think I see what's going on here and hope to have a fix shortly; just making an issue for tracking.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/14424
