### ISSUE TITLE
Singulary container local path (cache_directory) needs to be in lowercase

### ISSUE THREAD

**Issue by microfuge** [galaxyproject/galaxy#14425]
Dear All,

I tried to use singularity with release 22.05 and it worked out quite nicely. A minor issue was that the path to where containers are kept `cache_directory` in `container_resolvers_conf` was in camel case in my case e.g `/opt/galRoot/containers/..` . 

Galaxy converted the path to lower case so jobs could not find the containers. Logs also show the lower case conversion of the path to `/opt/galroot/containers...` . 

For testing following code change worked 

```
--- a/lib/galaxy/tool_util/deps/requirements.py
+++ b/lib/galaxy/tool_util/deps/requirements.py
@@ -187,7 +187,7 @@ class ContainerDescription:
         shell: str = DEFAULT_CONTAINER_SHELL,
     ) -> None:
         # Force to lowercase because container image names must be lowercase
-        self.identifier = identifier.lower() if identifier else None
+        self.identifier = identifier if identifier else None
         self.type = type
         self.resolve_dependencies = resolve_dependencies
         self.shell = shell
```
I presume the path to the container gets also gobbled up in the case conversion.  I would be grateful for your advice and convention for the container path.

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14431, thanks for the report @microfuge!
