### ISSUE TITLE
Bug on Tool Search

### ISSUE THREAD

**Issue by hujambo-dunia** [galaxyproject/galaxy#14438]
**Describe the bug**
Moderate front-end bug(s) on the Tool Search. Possibly more than one bug. Possible data bug too.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**
### Issue 1: Want same number of tools on Tool Panel (frontend) and API (backend)
![Greenshot 2022-08-11 16 00 13](https://user-images.githubusercontent.com/3672779/184229891-e889d1f4-ded8-42f6-b9fe-7fdc50bc065e.png)

### Issue 2: Want same position on Tool Panel (frontend) and API (backend)
![Greenshot 2022-08-11 15 47 31](https://user-images.githubusercontent.com/3672779/184226815-56a133db-c07a-42c5-9b67-73230afee0f4.png)
![Greenshot 2022-08-11 15 26 49](https://user-images.githubusercontent.com/3672779/184224335-f3ef53d6-0412-40e5-8335-9b09e6378791.png)

### Issue 3: Want only one version of the Tool
![Greenshot 2022-08-11 15 23 16](https://user-images.githubusercontent.com/3672779/184224368-4945b83d-6298-432a-9097-2919f63b8591.png)
![Greenshot 2022-08-11 15 21 21](https://user-images.githubusercontent.com/3672779/184222603-ccd1d06a-82cc-4be0-9502-9352e2bcedec.png)
![Greenshot 2022-08-11 15 21 29](https://user-images.githubusercontent.com/3672779/184222602-2aea8418-bef8-4a9e-8091-a71371f6486c.png)

**Additional context**

@tcollins2011

**Comment by bgruening** [comment]
I assume this is because those tools appear in two different sections. Galaxy can not handle that :(
If you click on "Show section" do you see them in two different sections?

**Comment by tcollins2011** [comment]
@bgruening  Yes the Galaxy 2 version of goseq is under the **Chemical Tool Box** section, while the Galaxy 0 version is under the **RNA-seq** section.

**Comment by hujambo-dunia** [comment]
@bgruening Possible "StringTie" is an exception. However, on US version it appears in the **same** section.

![Greenshot 2022-08-11 16 19 47](https://user-images.githubusercontent.com/3672779/184234878-1b75b4ea-a0d4-4d7d-860c-d4fb2c0c526c.png)

**Comment by tcollins2011** [comment]
I think in the StringTie case that **StringTie** and **StringTie merge** are two separate tools. The strange part about those is that **StringTie merge** is being shown on the front-end when its not in the backend results.

**Comment by hujambo-dunia** [comment]
@tcollins2011 That would be a relief! 😄

**Comment by tcollins2011** [comment]
I think an even better example of this problem might be just searching "feature". 

When we search for this term the first result that matches our backend generated list is in position 16. 

Our first returned result has an ID of _featurestein_ which corresponds to the tool name **'FeatureStein' Fragment Overlay Scoring**, as seen in the API return below. 

![Feature_API](https://user-images.githubusercontent.com/62220253/184237616-89797313-344c-4e49-96b3-277e12f50815.png)

**However, this result is not shown at the top of the results. It is instead full of Tool IDs that the backend didn't return. StringTie merge shows up again here as does a ton of Circos tools.**

![Feature_Empty](https://user-images.githubusercontent.com/62220253/184237866-593daa6b-bb7c-4e51-847b-b76b5cab5e09.png)


**The first backend tool returned, _featurestein_,  is finally found at position 16.**

![Feature_Found](https://user-images.githubusercontent.com/62220253/184238137-388391ad-0f7c-4500-8b10-c162c15d3ee0.png)

**Comment by hujambo-dunia** [comment]
@tcollins2011 yes - this is an even better example!

**Comment by mvdbeek** [comment]
Uhm, this is an older commit of 22.05, does it make sense to argue over that behavior ? I really think this discussion should be based off of dev.

**Comment by hujambo-dunia** [comment]
**Status update:** Coordinated with @dannon yesterday who is in agreement about the refactoring in the above "Draft PR" #14529. Changes pending (for example, adding front-end tests). Once PR is "Ready for Review" will add commenters as reviewers for final changes.

This frontend tool search bug is fully reproducible both on `dev` branch and `release_22.05` branch. However, is difficult to reproduce with the local database as the data in the local database is not reflective of data used for US and for EU servers. Thus, in order to reproduce this bug locally, you must connect to a database with realistic data. Alternatively, in order to reproduce this bug using static data files, one can test the [use case](https://github.com/galaxyproject/galaxy/issues/14438#issuecomment-1212476290) @tcollins2011 found (using "feature" as a search term) by pulling my "QA branch" here (or one can cherry-pick the commits into whatever branch you prefer): [frontend-tool-search-bug-reproduce-on-release-22.05](https://github.com/hujambo-dunia/galaxy/tree/frontend-tool-search-bug-reproduce-on-release-22.05) (For reproducibility purposes only.)

Copying @tcollins2011 and @ahmedhamidawan who have recently worked on improving other areas of the Tool Search so they are aware.
