### ISSUE TITLE
History items stuck in loading and no entry

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#14434]
History items in new multiple view unexpectedly show loading or no history items available alerts on first load and scroll.
Blocked #13985 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 
  Commit: d5262b992b

**To Reproduce**
1. use pr #13985
2. visit `/histories/view_multiple` path
3. Scroll the histories and change active current history
**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/8046843/184143992-545f5f36-ed77-4310-8a50-afeb1c75b3d3.mp4

**Additional context**

**Comment by itisAliRH** [comment]
5f3d68e79233ecdeba57044e7b15e451b5905791 fixes loading and no entry alert stuck but items will not be loaded until history is selected as the current history

**Comment by mvdbeek** [comment]
That makes a lot of sense, but I think it isn't a bug or anything that needs to be tracked separately. You'll have to think through how you want to receive updates for visible histories.
