### ISSUE TITLE
Workflow Editor, Cannot use workflow parameters in non string fields

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#1445]
Client side validation is not allowing for workflow editor to allow for workflow parameters. Screenshot shows two integer fields that are in error state because their previous values contains strains and not integers. If the user saves the workflow, workflow parameters are gone forever and can only be put back by editing the exported json file.

![](http://i.imgur.com/gAggG71.png)

**Comment by ericenns** [comment]
From some digging in the code, this is partly due to the restriction in client/galaxy/scripts/mvc/ui/ui-slider.js of only allowing numerical keys to be pressed.

Another part is in client/galaxy/mvc/tools.js, IntegerToolParameter tries to parse it as an integer preventing ${variable_name} to be used if you edited a workflow which was imported via json. I.E. if you paste in ${variable_name}, the set_value method resets the field to 0.

**Comment by Takadonet** [comment]
@erasche it worked before the new version of the workflow editor, so can you label this as a bug?

**Comment by hexylena** [comment]
@Takadonet entering invalid values was permitted before? I tagged it enhancement because of how new subworkflow parameters were.

**Comment by Takadonet** [comment]
It was permitted yes.  Workflow parameters are very useful to our lab
because sometimes we need the same value in multiple tools. Reduces the
complexity of using the workflow for our users.

**Comment by guerler** [comment]
This should have been fixed with #1249. Please let me know if not and I'll work on it. See also https://github.com/guerler/galaxy/commit/00452e1b8aecd3ed2fc4c06262f451c9efafa1c6.

**Comment by jmchilton** [comment]
@guerler but those commits are in dev. @Takadonet / @ericenns  is this a problem in dev? If this is not a problem in dev but is in 15.10, we should backport a fix I think.

**Comment by ericenns** [comment]
This issue is in 15.10 and we tried to disable the workflow_toolform_upgrade, but we aren't able to revert to the old working version.

**Comment by guerler** [comment]
I see. Sorry for the inconvenience. Could you please try the following workaround for 15.10: https://github.com/galaxyproject/galaxy/compare/release_15.10...guerler:fix_workflow_parameter_000
This will not disable the warning message but will allow you to enter workflow parameter names into numeric fields and use them in the run workflow form.

**Comment by Takadonet** [comment]
It works.Thanks!

Save me from editing the workflow with a text editor.

Cheers

**Comment by guerler** [comment]
Glad, it works. Thanks for catching it and sorry for the long wait. I should have notified you when the fix went into dev.
