### ISSUE TITLE
Jobs API ignores multiple `tool_id` query parameters

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#14451]
**Describe the bug**
BioBlend passes parameters as lists when you call the `jobs` endpoint like this:
```python
gi.jobs.get_jobs(
    history_id='2feab0580ed5cad2',
    tool_id=[
            'toolshed.g2.bx.psu.edu/repos/iuc/ivar_trim/ivar_trim/1.3.1+galaxy2',
            'toolshed.g2.bx.psu.edu/repos/iuc/ivar_trim/ivar_trim/1.3.1+galaxy0',
            'toolshed.g2.bx.psu.edu/repos/iuc/ivar_trim/ivar_trim/1.2.2+galaxy1'
    ],
    limit=1)
```
Resulting in the following request:
```
https://<galaxy_instance>/api/jobs?limit=1&offset=0&history_id=2feab0580ed5cad2&tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fivar_trim%2Fivar_trim%2F1.3.1%2Bgalaxy2&tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fivar_trim%2Fivar_trim%2F1.3.1%2Bgalaxy0&tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fiuc%2Fivar_trim%2Fivar_trim%2F1.2.2%2Bgalaxy1
```
Even if there are jobs running for the 2nd and 3rd `tool_id` it will return an empty list.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05
Commit: 574a0d42ea0cfe3559590cdf05190ce0f37cbeb9

**To Reproduce**
1. Use BioBlend to find `jobs` like in the description
2. Observe that it will only return the running job if it is running for the first `tool_id`, the rest are ignored.

**Expected behavior**
It should return the same response for tool IDs separated by commas or as a list (multiple instances of the same query parameter).

**Additional context**
If you pass the 3 tool IDs separated by commas in a single query parameter it will work as expected.

Detected by @wm75

**Comment by mvdbeek** [comment]
Since this wasn't covered by any tests, should we call this unspecified behavior and then go with https://fastapi.tiangolo.com/tutorial/query-params-str-validations/#query-parameter-list-multiple-values ?

**Comment by davelopez** [comment]
Yeah, that is the correct fix I think. I guess we need to support both comma-separated and regular lists of parameters since that seems the way `listify` works.
I wonder if we should create a `listify` compatible type alias like `Union[List[str],str]` to support all query parameters that we `listify` in the old API framework. I suspect this will not be the only endpoint that may not work as it used to.

**Comment by mvdbeek** [comment]
Yes, if we can hide that other way of specifying repeated parameters from the schema that would be perfect.

**Comment by davelopez** [comment]
> Yes, if we can hide that other way of specifying repeated parameters from the schema that would be perfect.

@mvdbeek, finally juggling with the `alias` of query parameters and dependencies seems to work as expected

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/14482, thanks so much @davelopez!
