### ISSUE TITLE
Change datatype not applied when including subworkflow

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14463]
from @innovate-invent 

I am not sure if there was a regression, but I am finding that the changed output type is not reflected in the workflow output:
![image](https://user-images.githubusercontent.com/6804901/184835231-77de0edb-c4c7-481d-9f00-23f614165cd4.png)

I have the example workflow above embedded as a subworkflow and I am not able to make connections to tools expecting a newick file despite when I run the workflow it outputs a newick file.

This applies to 21.05, 22.01, 22.05

The change datatype action also doesn't update the output type of the node, no subworkflow needed for that

**Comment by innovate-invent** [comment]
I am noticing that when I select a node with a changed output type, it breaks the connection with the next tool. I am able to remake the connection without issue but there appears to be an issue with the connection validation.

**Comment by mvdbeek** [comment]
Sounds like a different issue, can you describe this, ideally including how to reproduce ?

**Comment by innovate-invent** [comment]
I created a new issue for that #14468, it is probably not related.

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14473, thanks for the report!
