### ISSUE TITLE
Tool link breaks despite having correct format

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#14468]
**Describe the bug**
For tools with their output datatype changed, tool links break when either node is updated. 

This issue is slightly transient. Sometimes it takes selecting another node and then selecting and dragging the first to break the link.
Sometimes you have to "shake" the node while dragging it to break the link.
I am noticing that there is a slight stutter in the UI as the link breaks. Perhaps there is a race condition between the link being re-validated and whatever informs it that the output type has been changed.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01
Commit: 6c43d6664f04f6e0affb5f32fa728f5cbb0ca8b7

**To Reproduce**
1. Import workflow: [break_link.ga.txt](https://github.com/galaxyproject/galaxy/files/9353834/break_link.ga.txt)
2. Open it for editing
3. Drag or update the first node

**Expected behavior**
The link should not break

**Additional Information**
I can reproduce this in both Firefox and Chromium.

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/14473, thanks for the report!
