### ISSUE TITLE
22.01: Merge Collections tool skips last input

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#14460]
**Describe the bug**
The merge collections tool does not include the last input.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01
Commit: 6c43d6664f04f6e0affb5f32fa728f5cbb0ca8b7

**To Reproduce**
1. Import workflow: [Galaxy-Workflow-test_merge.ga.txt](https://github.com/galaxyproject/galaxy/files/9339762/Galaxy-Workflow-test_merge.ga.txt)
2. Execute it

**Expected behavior**
A collection of size two should output

**Comment by mvdbeek** [comment]
That's not a bug, your elements have the same name, so the first one is kept. You can select the behavior:
<img width="1715" alt="Screenshot 2022-08-16 at 10 51 53" src="https://user-images.githubusercontent.com/6804901/184838941-62dcbe6c-dbe2-44bd-9ba3-28f501562829.png">

**Comment by innovate-invent** [comment]
Thanks, I don't know how I have gotten this far without encountering this...

**Comment by mvdbeek** [comment]
I guess the conditional sections could use a bit more highlighting ? I only noticed this in the job info page of the workflow run.
