### ISSUE TITLE
Enhance gff_filter_by_attribute to support dataset_collections

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#1447]
I need this tool https://github.com/galaxyproject/galaxy/blob/dev/tools/filters/gff/gff_filter_by_attribute.py for the CHiP-exo flavor I'm working on.  Upstream tools in this flavor's pipeline produce dataset collections, so this tool needs to be able to support them.  This is my current critical priority task, but I am not clear on the process the core team uses to enhance tools like this.  If this tool receives a collection as input, I assume it should produce one as output, and if it receives a singleton as input, it should produce a singleton as output.  Is this a correct assumption?  Are there any other policies that have been defined for this area of work?

**Comment by gregvonkuster** [comment]
This may not an issue that requires a ticket (let me know if I should close it), but I'm wondering about future plans for dataset collections.  Since the tool form allows tools to accept dataset collections even if the underlying tool has not been written to accept multiple inputs and produce collections, tools that produce dataset collections can be chained to tools that do not accept multiple inputs (which is great).

But many times there are multiple collections or multiple datasets that the user wants to use as inputs to a tool that has not been retrofitted for multiple inputs, so the best that can be done is for the tool to be run multiple times, one for each collection or individual dataset.  This could be improved if all tools accepted multiple inputs (either multiple dataset collections or individual datasets).  I'm not sure how realistic this is, just curious.  I have retrofitted a couple of legacy tools to accept multiple inputs and produce collections if there is interest.  I'm not sure how changes like this should affect the tool version, etc.

**Comment by bgruening** [comment]
Greg what do you mean by `legacy tools`? We had an entire codefest dedicated to port tools to data-collections so yeah there is a huge interest in updating tools :) 

https://github.com/galaxyproject/tools-iuc/issues/239

The version number should be increased during such changes.

**Comment by gregvonkuster** [comment]
I have versions of the following tools that accept multiple inputs and produce collections as outputs.  I don't have the functional tests working for them though because I cannot get any functional tests to pass using either planemo (planemo throws exceptions on startup for me) or the run_test.sh script.  I'm not sure what I'm doing wrong on this testing.

1) https://github.com/galaxyproject/galaxy/blob/dev/tools/extract/extract_genomic_dna.xml - not sure if this one is deprecated, but it is so old maybe it is no longer needed?  I have a similar tool I've developed for CHiP-exo that I will be submitting to tools-iuc soon.

2) https://github.com/galaxyproject/galaxy/blob/dev/tools/filters/gff/gff_filter_by_attribute.xml

3) https://github.com/galaxyproject/galaxy/blob/dev/tools/stats/filtering.xml

**Comment by gregvonkuster** [comment]
Spoke with @blankenberg about this and concluded that the solution for this is to somehow enable multiple dataset collections consisting of datasets with the same datatype to be merged into a single collection.  This may be possible using new sub-workflows (not yet sure), or may be a feature to be added to collection features at some point.  So I'm closing this.
