### ISSUE TITLE
Tabular dataset not displayed

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#14509]
**Describe the bug**
I have a specific tabular dataset generated by eggnog-mapper, that is not displayed at all in galaxy, because of a JS error.
I could reproduce it on a 22.01 server (usegalaxy.fr) and a 22.05 (usegalaxy.eu)
I also tried to cherrypick https://github.com/galaxyproject/galaxy/pull/14396 but I *think* it failed to display too (not 100% sure though)
Apparently downloading then reuploading the file fixes the problem, maybe some metadata problem!?

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01 and 22.05

**To Reproduce**
1. Go to https://usegalaxy.eu/u/stephanierobin/h/tpannotationlepido
2. Try to display the content of dataset 3

**Expected behavior**
The dataset is not empty, it should display

**Comment by mvdbeek** [comment]
> maybe some metadata problem!?

Yes, there are no `column_names` recorded in the metadata.

https://github.com/galaxyproject/galaxy/pull/14396 should fix it, if you didn't restart your server after applying the fix you need to force reloading the client by opening your browser and reloading the page with `Disable cache` enabled.

**Comment by mvdbeek** [comment]
That's how setting column_names through a tool works: https://github.com/galaxyproject/galaxy/blob/c6989fd14960d217d55fb177d6c52e498a7a21a5/lib/galaxy/tools/actions/__init__.py#L928-L934

... this should be a list, but it clearly isn't ...

**Comment by mvdbeek** [comment]
I bet it's the conditional in https://github.com/galaxyproteomics/tools-galaxyp/blob/master/tools/eggnog_mapper/eggnog_mapper/eggnog_mapper.xml#L335-L342

**Comment by abretaud** [comment]
ooh well spotted, do you think it's a problem in the tool xml or in the Galaxy code parsing it?

**Comment by mvdbeek** [comment]
Yes, we're just skipping the conditional in the edge case of a metadata action default tag inside a conditional. https://github.com/galaxyproject/galaxy/pull/14510 normalizes this.

**Comment by bgruening** [comment]
I will update the server now.

**Comment by abretaud** [comment]
Cool thanks for the fix and update :heart_eyes: 
Is the .eu update finished? I've just tested and got the same problem

**Comment by abretaud** [comment]
So it works now, the content is displayed, the only remaining problem is headers are not displayed for this dataset (other ones are ok):

![image](https://user-images.githubusercontent.com/238755/186844979-c4700b71-bda5-43e1-8418-6a07ec9dae58.png)

Any thought @mvdbeek maybe?
