### ISSUE TITLE
Include HID count in quick history menu switcher

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14545]
From https://hackmd.io/3Ib2vyGzSWGsDK2kDGR0Cw

@nekrut thinks it would help distinguish a mess of recent, unnamed histories (1 hour ago isn't super helpful).

From the backend perspective this involved adding a count field to https://github.com/galaxyproject/galaxy/blob/732ac13f484a8ba8031a608581d144d9177260c8/lib/galaxy/managers/histories.py#L411-L426, defining a count property on the galaxy.model.History class (should just be self.hid_counter -1) and adding the count property to galaxy.schema.schema.HistorySummary.

On the frontend you probably only need to add the count property to
https://github.com/galaxyproject/galaxy/blob/732ac13f484a8ba8031a608581d144d9177260c8/client/src/components/History/Modals/SelectorModal.vue#L84-L88

**Comment by nekrut** [comment]
Basically providing any information on how big the history is would help. Is there any other data that can be displayed without prohibiting overhead?

**Comment by bgruening** [comment]
> OTOH I think it's also important we don't overload the user with information.

I would second that. The purpose is that its a __fast history__ selector and adding information and cluttering the user interface is imho counter-productive for the intended use.
If a user can not choose a correct history we should nudge them to tag/name their histories better and also provide a way - from that widget - to get to the more complicated, more enriched history list view.
