### ISSUE TITLE
Bedgraph to BigWig converter error

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/galaxy#14574]
**Describe the bug**
Some users have reported problems while converting Bedgraph files into BigWig.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05

**To Reproduce**
1. History: https://usegalaxy.org/u/gallardoalba/h/imported-miwi2-wgbsabi

**Expected behavior**
Conversion of Bedgraph into BigWig.

**Comment by nsoranzo** [comment]
It looks like the bedgraph file in that history has 6 columns, while the [specification](https://genome.ucsc.edu/goldenPath/help/bedgraph.html) says it should have 4.

**Comment by gallardoalba** [comment]
> It looks like the bedgraph file in that history has 6 columns, while the [specification](https://genome.ucsc.edu/goldenPath/help/bedgraph.html) says it should have 4.

Yes, indeed it worked correctly after reducing the number of columns.
