### ISSUE TITLE
Prefix support for toolshed, reports

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14591]
I don't think we've added this when we moved away from uWSGI, and I guess we should

**Comment by natefoo** [comment]
This appears to work for reports without modification by adding to the gunicorn command line:

```console
$ gunicorn ... --env SCRIPT_NAME=/reports
```

And proxying like so:

```nginx
        location /reports/ {
                proxy_pass http://localhost:9001/;
        }
```

**Comment by hexylena** [comment]
yeah works fine
