### ISSUE TITLE
Windows 11 Can't Unzip Downloaded HTML Output Files

### ISSUE THREAD

**Issue by tcollins2011** [galaxyproject/galaxy#14597]
**Describe the bug**

The default Windows 11 extraction tool and WinRAR are failing to extract downloaded zip files from tool outputs such as Seurat. However, it is possible to extract the html file from the zip folder using 7zip. 

**usegalaxy.org**
Galaxy version 22.05.1

**To Reproduce**
1. Access the linked history on a Windows 11 device: https://usegalaxy.org/u/tcollins/h/seurat
2. Download Seurat on data 1
3. Unzip the file

**Additional context**

When running the same process on the EU instance the zip file was able to be opened normally without having to use 7zip.

**Comment by mvdbeek** [comment]
I think we solved that by disabling the nginx-mod-zip module, but if you can try again that'd be good.
