### ISSUE TITLE
permission denied for creating objects file after a job completes successfully, although the file exists

### ISSUE THREAD

**Issue by code4dna** [galaxyproject/galaxy#14619]
The scripts/external_chown_script.py script is failing to create a file due to permission denied although the empty  file exists

`Cannot create /scratch/user/galaxy/my_galaxy/objects/e/c/7/dataset_ec7a709d-bd3b-4ea3-ac69-a288fa064b71.dat:Permission denied`

v22.05  463779b1b5a02a8f5cfac54c44e852414e511b57

This is failing on our galaxy v22.05 installed on a Slurm cluster that submits jobs as the real user.
The scripts for launching a slurm job and killing a running job work correctly.
sudo -E scripts/drmaa_external_runner.py
sudo -E scripts/drmaa_external_killer.py

The scripts/external_chown_script.py works on a different galaxy instance (v21.01) we have running. 

Here is the part of the log showing the permission denied message:

```
galaxy.jobs.runners.drmaa DEBUG 2022-09-14 15:05:12,724 [pN:main.1,p:208771,tN:SlurmRunner.monitor_thread] (19/6277378) state change: job finished normally
galaxy.util.path DEBUG 2022-09-14 15:05:12,773 [pN:main.1,p:208771,tN:SlurmRunner.work_thread-4] Changing ownership of /scratch/user/galaxy/my_galaxy/jobs_directory/000/19 with: '/usr/bin/sudo -E scripts/external_chown_script.py /scratch/user/galaxy/my_galaxy/jobs_directory/000/19 my_galaxy 24061'
galaxy.tool_util.output_checker INFO 2022-09-14 15:05:12,962 [pN:main.1,p:208771,tN:SlurmRunner.work_thread-4] Job failed because of contents in the standard error stream: [Cannot create /scratch/user/galaxy/my_galaxy/objects/e/c/7/dataset_ec7a709d-bd3b-4ea3-ac69-a288fa064b71.dat:Permission denied]
galaxy.jobs DEBUG 2022-09-14 15:05:13,091 [pN:main.1,p:208771,tN:SlurmRunner.work_thread-4] (19) setting dataset 19 state to ERROR
galaxy.jobs INFO 2022-09-14 15:05:13,189 [pN:main.1,p:208771,tN:SlurmRunner.work_thread-4] Collecting metrics for Job 19 in /scratch/user/galaxy/my_galaxy/jobs_directory/000/19
/sw/hprc/galaxy/my_galaxy/galaxy/lib/galaxy/model/__init__.py:434: SAWarning: Dialect sqlite+pysqlite does *not* support Decimal objects natively, and SQLAlchemy must convert from floating point - rounding errors and other issues may occur. Please consider storing Decimal numbers as strings or integers on this platform for lossless storage.
  self.numeric_metrics.append(metric)
galaxy.jobs DEBUG 2022-09-14 15:05:13,236 [pN:main.1,p:208771,tN:SlurmRunner.work_thread-4] job_wrapper.finish for job 19 executed (244.333 ms)

```
The empty file does exist:
```
ls -l /scratch/user/galaxy/my_galaxy/objects/e/c/7/dataset_ec7a709d-bd3b-4ea3-ac69-a288fa064b71.dat

-rw-r--r-- 1 my_galaxy my_galaxy 0 Sep 14 15:04 /scratch/user/galaxy/my_galaxy/objects/e/c/7/dataset_ec7a709d-bd3b-4ea3-ac69-a288fa064b71.dat
```

**Comment by nsoranzo** [comment]
@bernt-matthias Do you have any suggestion?

**Comment by bernt-matthias** [comment]
@code4dna have you configured Galaxy to output to the job working dir, i.e. `outputs_to_working_directory: true` in `galaxy.yml`

I guess that you have not enabled this. Then the job (which runs as the real user) does not have the privilege to write to Galaxy's file directory. With the option enabled the job will write into the job working dir and Galaxy will move them to their final destination (the files directory) after the job finished.

**Comment by code4dna** [comment]
thanks @bernt-matthias , I missed that one. I have it as true in our other galaxy. I changed it to true and it works. Thanks,

**Comment by bernt-matthias** [comment]
Wonderful
