### ISSUE TITLE
Log rotation with logging.handlers.RotatingFileHandler is not multiprocess-safe

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#14625]
**Describe the bug**
Log rotation with [logging.handlers.RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#logging.handlers.RotatingFileHandler) was added in #14457, but I was somewhat naive in this approach, since using Python logging to log multiple processes to a single file is not supported.

It mostly works, but you could have log messages clobbering eachother. With rotation involved things are worse, since rotation can be triggered by any process and some processes may continue to write to rotated files.

**Galaxy Version and/or server at which you observed the bug**
22.05

**To Reproduce**
1. Set gunicorn processes >> 1 `log_rotate_size` small, and `log_rotate_count` large.
2. Generate some log traffic
3. Observe that some guniicorn workers continue to write to rotated logs

**Expected behavior**
All workers write to current log

**Screenshots**
N/A

**Additional context**
This is a known issue, I just wasn't aware of it at the time.

- A socket-based approach is discussed [in the Python docs](https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes)
- A copy-and-empty approach by implementing a custom `rotator` on the handler is [described here](https://stackoverflow.com/questions/32564472/multiple-processors-logging-to-same-rotate-file/58146863#58146863), but this could be slow and also result in multiple rollovers/lost messages?
- We could return to disabling file handlers and just use gunicorn stdout/stderr capturing as we did before, and then rotate with `logrotate(8)`, but this doesn't offer a nice out-of-the-box solution like we had with uWSGI.

Thoughts and suggestions are welcome.

**Comment by natefoo** [comment]
FWIW this is really only relevant with unicornherder, where gunicorn is run daemonized and so there's no stdout/stderr to capture. For plain gunicorn you can simply use supervisord's built in rotation (which we should make configurable in Gravity) or journald.

**Comment by mvdbeek** [comment]
Since gravity 1.X doesn't use unicornherder I think we can close this.

**Comment by natefoo** [comment]
We should probably deprecate the rotation options.
