### ISSUE TITLE
TRS import via URL

### ISSUE THREAD

**Issue by fbacall** [galaxyproject/galaxy#14636]
Hello from WorkflowHub.

Currently in WorkflowHub we provide a button on Galaxy workflow entries to run the workflow on usegalaxy.eu via a hard-coded URL:
`https://usegalaxy.eu/workflows/trs_import?trs_server=workflowhub.eu&run_form=true` with the ID of the workflow added on. Galaxy then imports this via WorkflowHub's TRS API.

Obviously not every Galaxy workflow will be able to run on usegalaxy.eu, and so we want to provide the option for users to specify which instance their Galaxy workflow will run on.

However, the way the TRS integration currently works is that on the WorkflowHub side we need to know which `trs_server` is configured for WorkflowHub on that particular Galaxy instance. This could potentially vary across different instances, and is probably beyond the average workflow submitter's knowledge.

Could the import instead directly use a TRS URL? e.g.:
```
https://usegalaxy.eu/workflows/trs_import?url=https://workflowhub.eu/ga4gh/trs/v2/tools/109/versions/5/GALAXY
```

Then Galaxy could try and import without prior knowledge about which TRS-enabled registry it is talking to.

I know there were issues in the past about differences between the Dockstore and WorkflowHub TRS implementations, not sure if they affect this.

Cheers,
Finn

**Comment by nsoranzo** [comment]
@fbacall Thanks for opening the issue. I noticed that the TRS URL you suggest doesn't seem to be working, e.g. 
- https://workflowhub.eu/ga4gh/trs/v2/tools/109/versions/5 works
- https://workflowhub.eu/ga4gh/trs/v2/tools/109/versions/5/GALAXY returns a 404

**Comment by fbacall** [comment]
https://workflowhub.eu/ga4gh/trs/v2/tools/109/versions/5/GALAXY is not a valid TRS endpoint by itself, but it is the "base" of some other endpoints:
https://workflowhub.eu/ga4gh/trs/v2/tools/109/versions/5/GALAXY/descriptor
https://workflowhub.eu/ga4gh/trs/v2/tools/109/versions/5/GALAXY/files

I'm not sure which ones you are using internally.

**Comment by dannon** [comment]
Added in #14927
