### ISSUE TITLE
Celery broker_transport_options not configurable

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#14634]
**Describe the bug**
Currently there is no way to specify the broker_transport_options for Celery. This is important for configuring AWS SQS.
I need to decouple the queue name from the url to avoid collisions from multiple deployments.
I also need to be able to specify the urls so that I can pre-provision queues. Currently I need to give galaxy full access to all queues to allow it to create its own queues.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05
Commit: 4d14bb4ae76247038b8cc42a264a8d489db78ee6

**Expected behavior**
Ideally these settings would be able to be provided in the Galaxy config YAML and as a json encoded environment variable.
The environment variable is critical as my config file is baked into the container.

**Additional context**
https://docs.celeryq.dev/en/stable/getting-started/backends-and-brokers/sqs.html#predefined-queues
https://docs.celeryq.dev/en/stable/userguide/configuration.html#new-lowercase-settings

**Comment by jdavcs** [comment]
via #14708
