### ISSUE TITLE
Proposal for unified filesources and URL fetchers

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/galaxy#14658]
**Proposal**

This is a proposal to extend galaxy filesources with support for a more abstract urlsource, so that all url handling in Galaxy can take advantage of the rich features that filesources offer. This proposal consists of 4 elements:

a. Enable galaxy to have more generic, pluggable protocol handlers as extensions of file sources
b. Unify filesources and other url sources through an appropriate abstract interface
c. Allow all url sources to have an injectable user_context, allowing them to access credentials from user preferences, the vault etc. just as file sources do today.
d. Allow non listable url sources to be excluded from the UI

The reason for filing this issue is to get feedback on this proposal, including commentary on design, potential pitfalls etc. @uwwint has kindly volunteered to take on an initial implementation, and I'm happy to assist with PR review etc. ping @jmchilton

**Background & Rationale**

This proposal is based on a discussion at: https://github.com/galaxyproject/galaxy/pull/13949
In particular, it arose from the fact that file-source based urls (protocol `gxfiles://`) have existing functionality for reading and injecting user credentials, vault credentials, app settings etc. when processing urls. Other url sources, such as http, base64 and with the recent [PR above](https://github.com/galaxyproject/galaxy/pull/13949), DRS - do not have this access at present, as they are not considered file sources. However, some DRS implementations would nevertheless need access to user specific credentials, as appropriate tokens need to be injected per request. In addition, even http urls for example, could benefit from allowing admins to securely inject tokens if the server requires some auth mechanism. Therefore, unifying the handling of these urls through file sources would allow all url sources to be treated uniformly, with full access to contextual information that can be injected appropriately. With recent work that has gone into refactoring url handling, this seems even more tractable as all urls handled by Galaxy go through the `stream_url_to_file` method.

@uwwint has proposed making all filesources generic url handlers. i.e. instead of being a galaxy specific protocol of gxfiles://, it would be a filesource appropriate protocol such as `s3://`. Each file source would have a method to assess its ability to handle a particular url, returning a score based on how well matched it is to the task. The best matching file source will be tasked with handling the file. Consequently, there would be generic protocol handlers for urls such as ssh, ftp, s3, http etc. Filesources appear to be already designed for this possibility through an overridable `get_scheme` method, which defaults to `gxfiles`. This also offers the advantage of making all url handlers administrator configurable, with the ability for admins to introduce custom implementations with additional security restrictions, authentication mechanisms etc.

**Examples:**

```yaml
- type: s3fs
  label: Genome Ark
  id: genomeark
  doc: Access to Genome Ark open data on AWS.
  bucket: genomeark
  anon: true

- type: s3fs
  label: 1000 Genomes
  id: 1000genomes
  doc: Access to the 1000 Genomes Project with human genetic variation, including SNPs, structural variants, and their haplotype context.
  bucket: 1000genomes
  anon: true
```

In this example, given a url like `s3://1000genomes/somefile.fa`, both the above filesources would be potential matches, but since 1000genomes is a more specific match, that filesource would take precedence. In the event of collisions, some possible solutions are
a. To introduce a priority system
b. To raise a configuration error

**Notes:**

1. `gxfiles://` style urls would continue to be supported for backward compatibility

**Comment by jmchilton** [comment]
The file sources can already have non-gxfiles prefixes - e.g. gxftp:// works.

I'm certainly a solid +1 on a generalization of stream_url_to_file that can take in the components accessible by file sources and that would defer to file sources if the sources are defined and fallback to more general URIs for reading. I think my concern is the right implementation to me is a URI streaming interface that uses the file source plugins as a component vs... extending file source plugins in this direction... and to me the prior seems to be cleaner. I would rather comment on a specific implementation though because I could be wrong. I imagine they could potentially share a configuration file though - would that make you feel better about that approach?

**Comment by nuwang** [comment]
That sounds good! We're planning to take a first pass at an implementation together next week and we can iterate from there.
