### ISSUE TITLE
[Feature Request] "Copy Selected Datasets to History" option in context menu

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/galaxy#14676]
**Option to copy selected datasets to a different or new history**

For large histories, it is slightly slow and cumbersome to use the Multiple-History-Panel to drag-and-drop datasets from one history to another. It can also be user error-prone too.

An easier way, proposed by a colleague in our lab, would be to simply select the desired datasets (either in the right History side panel, or in View Histories main panel (User->Histories->View History)),  and perform a copy action on the selected datasets.

This should either prompt a list of histories (similar to the existing Switch History floating window), or allow the creation of a new one.

**Galaxy Version:**  {"version_major":"22.05","version_minor":"1"}

**Expected behavior**
1. Click on the multi-select checkbox in the history side panel
2. Select desired datasets
3. In the "X of Y Selected" drop-down menu, select either:
   * "Create New History with Selected Datasets"
       * Brings up the "Copy History" floating window
   * "Copy Selected Datasets to History"
       * Brings up the "Switch History" floating window

**Screenshots**

![Feedback_Galaxy_copy_dataset_edit](https://user-images.githubusercontent.com/20641402/191717649-1418315f-596c-4269-be26-bdc94d5bac63.png)

**Comment by mtekman** [comment]
I see now that this is related to: https://github.com/galaxyproject/galaxy/issues/8798 and https://github.com/galaxyproject/galaxy/issues/1136

**Comment by bgruening** [comment]
@mtekman do you think this will help? https://github.com/galaxyproject/galaxy/pull/14659

**Comment by mtekman** [comment]
@bgruening very cool feature(!) -- but I'm not sure it will help here. One issue is that large histories take a long time to load, and there is still the potential for the user to make an error when dragging and dropping more after 10 or so files

**Comment by bgruening** [comment]
Ok. The new multiple-history view will not load all histories you will select the histories to show. So its way faster to load. If you like test it out :)

**Comment by mtekman** [comment]
Ah that I missed, yes that would definitely simplify the side-by-side loading part of the issue!

**Comment by dannon** [comment]
I think it still makes sense as a bulk operation in that context menu, and then we can maybe do away with this old view completely:
![image](https://user-images.githubusercontent.com/155398/191744545-a3d89e59-0502-481e-9d68-a830f5811207.png)

**Comment by mtekman** [comment]
@dannon How do you access that view? This looks exactly like what my colleague would want.

**Comment by dannon** [comment]
@mtekman In this dataset menu:

![image](https://user-images.githubusercontent.com/155398/191745465-0a485dc7-257e-4a44-8cb3-396db325a1cc.png)

**Comment by mtekman** [comment]
Wow, this perfectly solves the problem! I'm happy to close this issue, unless the drop-down menu option is still needed

**Comment by dannon** [comment]
Sure, we can close this one out and leave the original https://github.com/galaxyproject/galaxy/issues/8798 open as the feature request.  I do think that still makes sense to support, now that we have better selection capabilities in the history.
