### ISSUE TITLE
Rename "hotness" issue tag

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#1469]
Original issue tag proposal: https://github.com/galaxyproject/galaxy/pull/902#discussion_r41880328
In today IRC discussion, it was agreed that "hotness" name should be changed.

Current proposals are:

| Phrase | Votes |
| --- | --- |
| **popularity** | jmchilton, natefoo, erasche, martenson, nsoranzo |
| interest | dannon, jxtx, jennaj |
| demand | nsoranzo |
| hype |  |
| votes |  |
| requests |  |
| support |  |

Modifier proposals are:

| Phrase | Votes |
| --- | --- |
| unpopular (more -1s than +1s), low, medium, significant | jmchilton, erasche, nsoranzo |
| mild, medium, hot | erasche*, martenson* |
| low, medium, significant |  |
| 1, 2, 3 |  |

\* It was explained to voter this was a joke, but voter would still vote for it

Please vote!

**Comment by jennaj** [comment]
**interest** seems the most direct to me, even if a bit muted

**Comment by hexylena** [comment]
I see one implicit vote in the @nsoranzo list of `interest`, and an explicit one from @jennaj so after two weeks+, that sure sounds like a rousing endorsement of "interest".

What should modifier be? low, medium, large?

**Comment by nsoranzo** [comment]
I've added the votes from the IRC discussion on January 11th to the issue description.

**Comment by hexylena** [comment]
Thanks @nsoranzo, made it into a table and voted.

**Comment by martenson** [comment]
I change my vote to 'popularity' as hype does not have enough hype

**Comment by hexylena** [comment]
Added section for modifier votes. Please add your modifier votes if you have them.

**Comment by nsoranzo** [comment]
I'd also prefer popularity over interest, if that's a run-off.

**Comment by hexylena** [comment]
Sounds like it'll be `popularity`. Modifier discussion still needs to be resolved and then we can get this finished

**Comment by hexylena** [comment]
@martenson would you mind closing this out tomorrow (popularity + low/med/sig) if no one else votes and then merge https://github.com/erasche/p4/pull/7 ? We can always revisit tag names and semantics at a later date, but it seems like everyone who has an opinion has expressed that this will be good enough, _pro tempore_.
