### ISSUE TITLE
Scrolling changes values for integer and float parameters

### ISSUE THREAD

**Issue by foellmelanie** [galaxyproject/galaxy#14698]
Hi, 

I currently have quite some problems to set correct values for integer and float parameters in the Galaxy UI. 

Typically after specifying a value I scroll down to have a better view of the next parameters to set. Unfortunately, scrolling up or down after specifying a float or integer parameter changes the value, so I have started several tool runs with wrong parameters. Now I am aware that I need to first click outside the parameter box to be able to scroll and I am spotting it if I accidentally change the value by scrolling, but in my opinion it is very annoying. I hope it's a bug that can be resolved and not a new feature...

Best,
Melanie

**Comment by dannon** [comment]
It's worth considering dropping 'range' sliders completely and using precise numerical inputs.  They look neat on the page, but I think they're generally less usable than a simple input box.

**Comment by dannon** [comment]
@bgruening Ahh!  Thanks for the clarification; I assumed this was the slider based stuff -- I'll take a look.  I think I still want to drop the sliders though ;)
