### ISSUE TITLE
Downgrade "tags" for migrations associated with releases

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#14710]
Just following up on the discussion the other day with @jdavcs and @mvdbeek, I found the new downgrade system difficult but I think that will be resolved with the latest version in dev. That said, we discussed the possibility of less opaque tags. Less opaque isn't necessarily needed, but at least knowing which tag is associated with a release important to allow an admin to downgrade to the right version easily. I'm not sure what the optimal implementation is there, but if there's some way to make that  easy to identify for admins it would be ideal, downgrading is usually somewhat stressful.

xref #14680

**Comment by jdavcs** [comment]
proposed solution described here: https://github.com/galaxyproject/galaxy/issues/14680#issuecomment-1261665529

**Comment by jdavcs** [comment]
Fixed in #14730
