### ISSUE TITLE
Workflow Editor: Upgrade workflow step throws console error

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#14732]
**Describe the bug**
When trying to upgrade a sub-workflow the following error appears in the browser console and nothing happens:
```
TypeError: Cannot read properties of undefined (reading 'id')
    at VueComponent.onUpgradeSubworkflow (FormDefault.vue?1188:148:1)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1863:1)
    at HTMLButtonElement.invoker (vue.runtime.esm.js?2b0e:2184:1)
    at original._wrapper (vue.runtime.esm.js?2b0e:6961:1)
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05
Commit: 4ee6b34240b5d7fb1798411d003d0e49a5089bf8

**To Reproduce**
1. Create a workflow containing a sub-workflow
2. Select the sub-workflow node and click the *Upgrade* button next to the name
3. See the console error in your browser

**Expected behavior**
No console error and the workflow being correctly upgraded or a proper error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/46503462/193065508-7fb96e23-cc08-4f43-be7b-18725028dc03.png)

**Comment by dannon** [comment]
Should be fixed in #14733
