### ISSUE TITLE
Remove handlebars templates, task, and compiler

### ISSUE THREAD

**Issue by carlfeberhard** [galaxyproject/galaxy#1476]
Attempting to continue simplification of front end framework. We've never really used handlebars to it's full potential and the tool menu handlebars templates have essentially become cruft (IMO).
- [x] move tool menu handlebars templates into underscore 
- [x] remove requirement in tool modules and any mako templates
- [x] remove webpack loader, grunt task, and grunt dependency

That's my plan but I'm happy to reverse/stall if anyone objects.

Edit:
- [x] remove from scatterplot

**Comment by martenson** [comment]
+1 to underscore simplistic templates, unless you tell me that handlebars' potential is worth pursuing - then I will convert my underscore templates to handlebars :)

**Comment by davebx** [comment]
One standard-issue +1 from me, underscore looks easier to use than handlebars, at first glance.

**Comment by carlfeberhard** [comment]
Alright, will do. Thanks for the feedback
