### ISSUE TITLE
History scrolling can stall even in small histories

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#14767]
**Describe the bug**
Can stall or get stuck even in small histories
Slightly different from https://github.com/galaxyproject/galaxy/issues/13741

**Galaxy Version and/or server at which you observed the bug**
Org: {"version_major":"22.05","version_minor":"1"}
EU: {"version_major":"22.05","version_minor":"1"}

**To Reproduce**
1. Go to a history that has datasets of type active + deleted
2. Expanding a few datasets will trigger this more often but is optional
3. Scroll through the history 
4. Tends to get stuck at a particular location per history, and more often when scrolling up that down
5. Movies are for org but happens at eu too

**Expected behavior**
Smooth scroll

**Screenshots**

https://user-images.githubusercontent.com/8999735/194617390-aacba299-0ed1-47ca-93f9-b9ad63ae2cfc.mov

https://user-images.githubusercontent.com/8999735/194617426-c06bbaed-c0fc-4352-aa2a-90d0dcfda094.mov

https://user-images.githubusercontent.com/8999735/194617431-a29e3469-fd7a-4dbc-94e1-d73c2502e7c3.mov

https://user-images.githubusercontent.com/8999735/194617476-00f4f187-5db9-46f9-9a12-46438b3de1ea.mov

**Additional context**
Can be worse with slightly larger histories or when a history contains datasets for executing jobs and/or expanded datasets (especially if the expanded datasets have a lower dataset number ie are lower in the history panel)

**Comment by guerler** [comment]
Thank you for reporting this @jennaj, particularly with these screencasts.

**Comment by dannon** [comment]
Retargeting for 23.1 for future improvements.  This should be a bit better in the short term with recent tweaks to the content item fetch count tweaks.

**Comment by igormakunin2** [comment]
The history scrolling issue is also observed on Galaxy Australia running 23.1.5. If I scroll a big history down, the content moves up and down. Mac, Firefox.

**Comment by bgruening** [comment]
@igormakunin2 we have some hope that https://github.com/galaxyproject/galaxy/pull/17353 at least improves the situation. When this gets merged, maybe you can test it and report back? Thanks!
