### ISSUE TITLE
Changing a dataset's datatype does not update the shown datatype in the history

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#14763]
**Describe the bug**
If manually change a dataype of a dataset (via the datatsets edit button) then the datatype is changed, but the history still shows the old datatype. 

Also a history reload does not help. Only reloading the whole page seems to help.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05 (usegalaxy.eu)

**Comment by mvdbeek** [comment]
This might be because changing datatypes doesn't update the history update time ?

**Comment by davelopez** [comment]
It seems to be working now. Maybe some transient high load on EU?
Or was it with one particular datatype?

![change_datatype](https://user-images.githubusercontent.com/46503462/195132976-b3c98b83-e998-4d50-8099-251b1d17ad17.gif)

**Comment by bernt-matthias** [comment]
Can still reproduce it for `cm` <-> `afg` conversion. I chose `afg` at random and `cm` because I wanted to check if I can upload a data set of a type that I can not set in the upload dialog but has a sniffer.


https://user-images.githubusercontent.com/25689525/195182646-445013c8-db4c-433d-ba37-76a0a32f425b.mp4

**Comment by davelopez** [comment]
This is so weird, It still works for me :sweat_smile: I tried Firefox this time just in case...

I'm out of ideas on what can be happening here... :sweat_smile: 

### CM -> AFG
![cm-afg](https://user-images.githubusercontent.com/46503462/195287936-a6ec0168-4f11-43e3-bd87-94870f09c18f.gif)

### AFG -> CM
![afg-cm](https://user-images.githubusercontent.com/46503462/195288046-714a6d89-7bc1-4954-8ac0-9edaf3946f3c.gif)
