### ISSUE TITLE
Collection creation during upload does not hide datasets

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#14761]
**Describe the bug**

If a collection is created for datasets that are currently uploading and the option is selected that datasets should be hidden then the datasets which are still uploaded end up visible in the history.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05 (via `planemo serve --galaxy_branch release_22.05`

**Expected behavior**

All datasets should be hidden.

**Comment by wm75** [comment]
Yes, if datasets are in a non-terminal state when they are hidden as part of making them collection elements, they will become visible again when they reach the terminal state.
So to reporduce you need to be faster than the upload.

**Comment by assuntad23** [comment]
Tied to failing upload pair Selenium test; bandaid fix at #15272

**Comment by dannon** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/15525/files
