### ISSUE TITLE
quota refreshed and still not 0%?

### ISSUE THREAD

**Issue by marwa38** [galaxyproject/galaxy#14780]
Hi 
I am getting that I am using 24% of my space on usegalaxy but I already deleted and purged (even for the hidden). I then refereshed, why I didn't get 0% usage for the quota?
thank you 
Marwa

**Comment by davelopez** [comment]
Hi @marwa38, by "refreshed" do you mean this button in the Storage Dashboard?

![image](https://user-images.githubusercontent.com/46503462/195289827-530319d0-851f-45c1-bbd6-18ca61a135be.png)

**Comment by marwa38** [comment]
yeah exactly thanks for you reply
also there is nothing to delete
![image](https://user-images.githubusercontent.com/68851733/195296365-30541a51-3360-4bea-bd2f-e853046339e5.png)

**Comment by davelopez** [comment]
Those options, `Deleted datasets` and `Deleted histories` will be available **only if you have deleted** histories or individual datasets (but not purged them).

You can check if you have still non-deleted histories by going to your `User -> Histories` menu at the top bar or going directly to the URL https://usegalaxy.org/histories/list (assuming you are using the main Galaxy server).

**Comment by marwa38** [comment]
not sure if there was a problem then other than it takes a time until it is get rid of the deleted stuff but there 10% something there. 
Update: found them now seen that I can delete 
![image](https://user-images.githubusercontent.com/68851733/195700007-ec9a2ecd-9e18-476a-ac85-5ca0e2771260.png)

**Comment by marwa38** [comment]
0GB 
THANK YOU
