### ISSUE TITLE
data libraries offer operations on deleted items

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#14783]
**Describe the bug**

When a library is deleted I think it is not supposed to offer any actions other than "undelete". At the moment the UI elements are fully rendered as if library was not deleted (first screenshot). When the deleted library is e.g. renamed, the backend properly fails with an error `400008` but the client ignores that and changes the value locally anyways (second screenshot).

<img width="999" alt="Galaxy___martenson" src="https://user-images.githubusercontent.com/1814954/195400327-e892ab23-5a71-4efa-b7d6-b7843497322e.png">

<img width="1643" alt="Galaxy___martenson" src="https://user-images.githubusercontent.com/1814954/195400910-1c1ab34b-c0c5-4190-96f5-cf0b13bfc632.png">

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: dev

**Expected behavior**
The deleted library should only have one action available in the UI -- the undelete button.

**Comment by davelopez** [comment]
Good catch @martenson! I'll take a look, should be an easy fix.
