### ISSUE TITLE
implement 'export to github' feature for TS

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1479]
inspired by https://code.google.com/export-to-github/export?project=google-security-research

**Comment by hexylena** [comment]
:+1:

**Comment by jmchilton** [comment]
Tool development should start on github, this feature isn't part of a workflow we should be encouraging so I wouldn't spend time implementing it. There are much fruitful github integrations to persue in my opinion.

**Comment by jxtx** [comment]
I believe the goal is to encourage people with existing repositories in the ToolShed to move to github. This could generate all the appropriate planemo / shed configs and make it easy to get people into the recommended workflow.

**Comment by remimarenco** [comment]
Do we have a doc explaining more precisely the _recommended workflow_? What would it be like? 

GitHub [planemo=> TS (hg)?

**Comment by bgruening** [comment]
@remimarenco my ideal workflow looks like this.
- install planemo
- planemo init
- tool dev
  - planemo lint
  - planemo serve
  - planemo test
- push to IUC (other repos)
- PR gets reviewed and merged
- travis will populate the TS

**Comment by martenson** [comment]
@remimarenco imo the flow should be derived from (or equal to) http://planemo.readthedocs.org/en/latest/writing_standalone.html

**Comment by hexylena** [comment]
Not much interest, and community has settled on "develop on github" so closing this now :)
