### ISSUE TITLE
Link to localhost in job completion notification email when using nginx proxy

### ISSUE THREAD

**Issue by Danoontjes** [galaxyproject/galaxy#14790]
**Describe the bug**
I have setup a Galaxy server with a Nginx reverse proxy. I followed https://docs.galaxyproject.org/en/master/admin/nginx.html
Galaxy is accessible on https://10.5.87.54/
Gunicorn is listening on a unix socket.

When enabling the 'job completion email' I receive a mail with a link that points to localhost:
```
Your Galaxy job generating dataset(s):

Sort on data 2

is complete as of 02:00. Click the link below to access your data: 
http://localhost:8080/histories/view?id=f2db41e1fa331b3e
```

It could be that I missed a config option that substitutes localhost:8080 with something else, like the used IP or server name.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: {"version_major":"22.05","version_minor":"1"}
Commit: 64b75762f1c2740b4f4a38c181ccd5f551832720

**Comment by dannon** [comment]
This should probably be `galaxy_infrastructure_url` as defined in the configuration, and it looks like the code currently does try to use it, here: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/job_execution/actions/post.py#L59

Can you check if you have this setting correctly configured for your Galaxy instance?

**Comment by Danoontjes** [comment]
That was it, now the link is as it should be.

Thanks
