### ISSUE TITLE
SyntaxError raised by lib/galaxy/metadata/__init__.py

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#14819]
Hi,

I see that we have a syntax error coming from `lib/galaxy/metadata/__init__.py`

```
more galaxy_3611.e
Traceback (most recent call last):
  File "metadata/set.py", line 1, in <module>
    from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()
  File "/gpfs1HP/softs/bioinfo/galaxy-prod/lib/galaxy_ext/metadata/set_metadata.py", line 20, in <module>
    from galaxy.metadata.set_metadata import set_metadata
  File "/gpfs1HP/softs/bioinfo/galaxy-prod/lib/galaxy/metadata/__init__.py", line 30
    class MetadataCollectionStrategy(metaclass=abc.ABCMeta):
                                              ^
SyntaxError: invalid syntax

```

https://github.com/galaxyproject/galaxy/blob/330eb07515bb6bc2fe7adefdd95b291604cc558d/lib/galaxy/metadata/__init__.py#L30

This is python `Python 3.8.13` and Galaxy 22.01 installed from ansible.

Thank you

Fred

**Comment by mvdbeek** [comment]
Hmm, yes, it looks like the python used for running the metadata script was an unsupported python version.

**Comment by FredericBGA** [comment]
for the records: This was due to a problem of rights. Everything was working nice on the Galaxy's VM. But when using a computation node, the path to the galaxy's `.venv` was denied. So `python` command was the one in `/bin`, a python2 version of course.

**Comment by pcm32** [comment]
If you are here, for us it was that the ansible install was made pointing to a python binary that was available on the main galaxy machine, but not on the execution nodes of the cluster, so the venv was being correctly activated, but python was not there in the venv for the exec nodes.
