### ISSUE TITLE
The meme tool fails on Galaxy main

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#1481]
Running the meme tool on Galaxy main produces this exception:

```
Warning: Can not convert EPS file to PNG as no install of Image Magick or Ghostscript is usable.
Warning: Can not convert EPS file to PNG as no install of Image Magick or Ghostscript is usable.
Can't locate XML/Parser/Expat.pm in @INC (@INC contains: /galaxy-repl/main/deps/meme/4.11.0/iuc/package_meme_4_11_0/6ee2e1225125/bin /galaxy/main/deps/meme/4.11.0/iuc/package_meme_4_11_0/6ee2e1225125/lib/perl /galaxy/main/perl5/lib/x86_64-linux-thread-multi /galaxy/main/perl5/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /galaxy/main/deps/meme/4.11.0/iuc/package_meme_4_11_0/6ee2e1225125/lib/perl/CheckingSAX.pm line 12.
BEGIN failed--compilation aborted at /galaxy/main/deps/meme/4.11.0/iuc/package_meme_4_11_0/6ee2e1225125/lib/perl/CheckingSAX.pm line 12.
Compilation failed in require at (eval 12) line 3.
    ...propagated at /usr/share/perl5/base.pm line 94.
BEGIN failed--compilation aborted at /galaxy/main/deps/meme/4.11.0/iuc/package_meme_4_11_0/6ee2e1225125/lib/perl/MemeSAX.pm line 3.
Compilation failed in require at /galaxy/main/deps/meme/4.11.0/iuc/package_meme_4_11_0/6ee2e1225125/bin/meme_xml_to_html line 48.
Warning: meme_xml_to_html exited abnormally and may have failed to create HTML output.
Error running MEME.
```

**Comment by natefoo** [comment]
Interesting, ImageMagick should be on `$PATH`. As for `XML::Parser::Expat`, is that supposed to be installed by meme itself?

**Comment by martenson** [comment]
I did not see any error in logs during the installation of meme (but I could have missed it ofc) and Galaxy shows both package and tools as green.

meme package installs this: https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_meme_4_11_0/tool_dependencies.xml

configure looks like this: https://gist.github.com/martenson/429fc50f60a3a5a785ec

**Comment by gregvonkuster** [comment]
@natefoo @martenson The meme tool is working on brubeck as of yesterday.  Nate, I had to uninstall and reinstall the meme package after you had installed ImageMagick, so compiling meme requires ImageMagick to be installed and available on the path.  I'll open a ticket against the meme tool in tools-iuc to add this dependency.  The error that displays on Galaxy main is similar tp what I saw on brubeck before meme was compiled with ImageMagick.  Is it possible that ImageMagick was not found on the main nodes at the time that meme was compiled?  BTW, meme will compile fine without ImageMagick, but it will not render the html output dataset correctly.

**Comment by gregvonkuster** [comment]
@natefoo @martenson FYI: the meme and fimo tools have been enhanced to require ImageMagick in this PR:  https://github.com/galaxyproject/tools-iuc/pull/600  It was merged yesterday, so when updated in the TS, main can be updated with the fix for this.

**Comment by natefoo** [comment]
Thanks @gregvonkuster!

**Comment by martenson** [comment]
I updated the tools on Main, thanks @gregvonkuster
