### ISSUE TITLE
Users with some special email domains can not create an account - domain check fails

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#14829]
**Describe the bug**

Users with the email domain `@edu.unito.it` can not create an account. Instead, they get the error message `The email domain cannot be resolved.` which is created here with a check of the domain exists.

https://github.com/galaxyproject/galaxy/blob/895e028cff83db0ad20f05c3cb87ef6c1b443241/lib/galaxy/security/validate_user_input.py#L103

It seems the domain EDU.unito.it does not exist, `unito.it` does.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05.1

**To Reproduce**
1. Go to the login page
2. try to create an account with `foobar@edu.unito.it`

**Expected behavior**

I can create an account.

**Comment by nsoranzo** [comment]
This is because `edu.unito.it` doesn't have an "A" DNS record, but only an "MX" one.

A neat way to solve this would be:
```diff
diff --git a/lib/galaxy/security/validate_user_input.py b/lib/galaxy/security/validate_user_input.py
index 3a5b0666a7..f9df238903 100644
--- a/lib/galaxy/security/validate_user_input.py
+++ b/lib/galaxy/security/validate_user_input.py
@@ -6,8 +6,9 @@ user inputs - so these methods do not need to be escaped.
 """
 import logging
 import re
-import socket
 
+import dns.resolver
+from dns.exception import DNSException
 from sqlalchemy import func
 
 log = logging.getLogger(__name__)
@@ -71,7 +72,7 @@ def validate_email(trans, email, user=None, check_dup=True, allow_empty=False, v
     message = validate_email_str(email)
     if not message and validate_domain:
         domain = extract_domain(email)
-        message = validate_domain_resolves(domain)
+        message = validate_email_domain_name(domain)
 
     if (
         not message
@@ -97,11 +98,11 @@ def validate_email(trans, email, user=None, check_dup=True, allow_empty=False, v
     return message
 
 
-def validate_domain_resolves(domain):
+def validate_email_domain_name(domain):
     message = ""
     try:
-        socket.gethostbyname(domain)
-    except socket.gaierror:
+        dns.resolver.resolve(domain, "MX")
+    except DNSException:
         message = "The email domain cannot be resolved."
     return message
 
```

which uses the third-party [dnspython](https://www.dnspython.org/) library.
We would need to add `dnspython` to `pyproject.toml` and `packages/data/setup.cfg`, but we already indirectly depend on `dnspython` via `pydantic[email]`, so in practice this wouldn't add new dependencies to the `galaxy-data` package (or Galaxy in general).

Should I go ahead with opening a PR or are there better ideas?

**Comment by bgruening** [comment]
Very cool thanks!
