### ISSUE TITLE
Galaxy Linter does not detect comments in stdio as such

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#14836]
Hi,
**Describe the bug**
See https://github.com/galaxyproject/galaxy-language-server/issues/212
Comments in the stdio section are not detected as comments

**Galaxy Version and/or server at which you observed the bug**
```
$ planemo --version
planemo, version 0.74.9
```

**To Reproduce**
@davelopez may help me here. I only know how to reproduce it in vs code with the galaxy language extension.

**Comment by mvdbeek** [comment]
Thanks @lldelisle, we should probably backport https://github.com/galaxyproject/galaxy/pull/14845 to 22.05 and create a new package.

**Comment by mvdbeek** [comment]
OK, still need to do the packages and create a new planemo release, but this is done on the Galaxy side

**Comment by davelopez** [comment]
Should the latest [galaxy-tool-util v22.1.5](https://pypi.org/project/galaxy-tool-util/) contain the fix from #14852 or would it be included in the next package release?
