### ISSUE TITLE
Workflow List -> Invocations display/navigation issue

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#14851]
"Invocations" dropdown action in workflow list shows incorrect workflow invocations.  On clicking this, I get the set of invocations for a workflow that is not my "no-op IO" test workflow.  The one selected happens to be the bottom one in the list, if that's helpful for debugging.

![image](https://user-images.githubusercontent.com/155398/197805654-2a55254b-2ea0-410a-bc59-eafb5cbf0910.png)

Probably pretty straightforward; just need to trace out where the wrong id is being bound.

**Comment by mvdbeek** [comment]
The page expects /workflows/<stored_workflow_id>/invocations, but we're putting in `<workflow_id>` instead
