### ISSUE TITLE
problem to display the interface to register login and password 

### ISSUE THREAD

**Issue by cantoine27** [galaxyproject/galaxy#14879]
Hello, 
I construct a server with galaxy. I try to display the interface to register (login + password) like this first picture but I don't fonction. It is a capture  from another server with galaxy version 17.09 and debian 9. The server that I try to construct is with galaxy version 22.09 and debian10.  
![galaxy_interface_login](https://user-images.githubusercontent.com/49944213/198600375-f4b25b11-44b3-4456-bef9-6409ec10315e.png)
This second picture is from galaxy version 22.09 and debian10 : 
![deb10-107](https://user-images.githubusercontent.com/49944213/198602060-07334a9b-82d9-4e29-9e86-c1955690ff02.png)

Chloé

**Comment by dannon** [comment]
@cantoine27 Thanks for reporting this, it looks like a regression where `require_login` is no longer working correctly in the latest dev branch.

**Comment by cantoine27** [comment]
@dannon I have verify in my galaxy.yml and it is 'true' 
![deb10-109](https://user-images.githubusercontent.com/49944213/199928420-b0b8fdae-6e92-4de5-89a1-7d620fb15f31.png)
will I be informed when there is a correction? do you know approximately how long it will take?

**Comment by mvdbeek** [comment]
It will likely not be long, but if you're not working on developing galaxy you should use the release_22.05 branch (https://galaxyproject.org/admin/get-galaxy/)

**Comment by cantoine27** [comment]
I am sorry, I made a mistake, I use version 22.05 and not version 22.09 as I wrote

**Comment by cantoine27** [comment]
@dannon I succeeded, there was a problem in my auth.conf file
Everything works now, for my login and the logins of the other users of the domain too. Thanks.

**Comment by dannon** [comment]
@cantoine27 Good to hear, thanks for the update!
