### ISSUE TITLE
New/beta history: add functionality to enable capture of a collection's URL 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#14896]
**Describe the bug**
* Legacy history view has a disc icon where a collection's URL can be captured out of the UI. 
* New/beta history is missing this and there is no direct way for a user to access some parts of that string via the UI to construct it manually. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05, any server

**To Reproduce**
1. Toggle to use the new/beta history view
2. Go to a history with a collection
3. Click into the collection
4. Directly clicking on the "Download" element starts a download
5. Right-clicking on that same element does not present a URL that can be captured
6. Datasets (in collections or not) have two icons -- one to start the download and one capture the link into the clipboard
7. Collections are currently missing that second function

**Expected behavior**
Provide a link to a collection directly in the UI's beta history view that can be captured and used for things like getting data from the command-line via wget or curl. 

Requiring that the history be in a shared state or that the account's API key is included in the final wget/curl command string is fine as it is to me.

End-user Workarounds:
1. Copy the collection into a new history, then create and download a history archive.
2. Toggle to the Legacy history view and use the disc icon.

**Screenshots**

Legacy history

<img width="291" alt="legacy-history-collection-URL-copy-available" src="https://user-images.githubusercontent.com/8999735/199080208-f9f71634-74f1-46c6-9c82-a18e0ffc64ff.png">

Beta/new History

<img width="286" alt="beta-history-collection-URL-copy-wishlist-item" src="https://user-images.githubusercontent.com/8999735/199080410-245197a5-2935-49d6-b03c-dab1dbf4b0fd.png">

**Additional context**
Q&A at GHelp: https://help.galaxyproject.org/t/where-to-find-a-dataset-collection-link-to-download-through-wget-curl/8931

**Comment by dannon** [comment]
@jennaj Thanks for the report, good catch -- this is definitely an oversight and we'll get a fix out shortly.
