### ISSUE TITLE
History tags that are 'names' (#somename) appear as 'name' in history grid lists

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#14893]
**Describe the bug**
Tag a history using a named tag, .e.g. `#somename`, the tag will appear as 'name' when looking at grids/lists of histories, e.g. `histories/list_published` and `histories/list`. This occurs on main and dev@a7d35017d42f78d3f8d46b592402d08be7bb5b56.

**Comment by davelopez** [comment]
Should be fixed now.

Also xref #16368
