### ISSUE TITLE
Regression of Workflow Parameters in Run Form

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#14928]
**Describe the bug**
There have been some regressions regarding the appearance and behavior of workflow parameters in the run form:
1. The highlighting color is missing.
2. The connected input field should not be editable?
3. The workflow parameter field is not optional.
4. Input field changes from `* required` to just `*` without label when data is entered.

**Galaxy Version and/or server at which you observed the bug**
Current dev.

<img width="578" alt="image" src="https://user-images.githubusercontent.com/2105447/200037855-feb61998-5c90-4208-b829-885c93f128a4.png">

**Comment by mvdbeek** [comment]
You'll want to share your workflow too.

> 3\. The workflow parameter field is not optional.

They come as optional and not optional flavors

**Comment by guerler** [comment]
I think that particular issue is independent of the workflow, see e.g.:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/2105447/200039864-ef4a696c-b9ef-46ea-8028-d5de9aaab69a.png">

**Comment by mvdbeek** [comment]
Can you still get into the habit of doing this so we can have a specific discussion ?
 
> The connected input field should not be editable?

not so sure about that, this depends on whether you've used the old style workflow parameters, a workflow would have answered this.

I also would want to point out that it is a mistake to reuse form parameters for non-tool form inputs. Text tool inputs are always optional, and we have to narrow these with an empty value validator ... this is unfortunately legacy behavior we can't get rid of completely, and i think that's leading to these bugs here.

**Comment by guerler** [comment]
Here is the workflow. The input associated with the workflow parameter is not optional.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/2105447/200043692-e065f85e-31eb-4e2d-ac85-f785e80795e6.png">

I generally disagree with not re-using form parameters elsewhere but maybe I do not understand the comment correctly. It would have been (close to) impossible to transition the form components as a consistent set otherwise. Forms and form parameters are used throughout large parts of the UI not only in tools.

**Comment by ElectronicBlueberry** [comment]
As these are areas of the client I worked in, I looked into this, but have trouble understanding some specifics of the issue.

> 1. The highlighting color is missing.

Both the eu live version and the screenshot you provided have green highlighting on the input. Or are you referring to a different highlighting? Please specify.

> 2. The connected input field should not be editable?

I could not recreate this on dev. Connecting a input field makes it uneditable for me, with the same tools you used in the screenshot. Could you provide reproduction steps?

> 3. The workflow parameter field is not optional.

Not a regression. The highlighting is wrong, as addressed in #14914, but the info about the field being optional or required not being transferred to the workflow run form is a missing feature.

> 4. Input field changes from `* required` to just `*` without label when data is entered.

Not a regression, this is a new feature. This particular behavior of the input field is a design choice, to make missing required fields more obvious to colorblind users.

**Comment by guerler** [comment]
Thanks for looking into this:

1) Highlighting color. Notice how the workflow parameter has a green bar on the right. Not sure if that is related to any of your additions.

<img width="916" alt="image" src="https://user-images.githubusercontent.com/2105447/200889831-dcc84472-d5d0-4206-a796-b47730871004.png">

2) Will double check that.
3) Thank you so much for the quick fix! That was what I noticed the most.
4) Thanks for the explanation, I think it would be better to consistently show `* required` instead of dynamically showing/hiding just the `required` part but maybe thats just me.

**Comment by mvdbeek** [comment]
@guerler it would help if you include the workflow, not just the screenshot.

**Comment by guerler** [comment]
@mvdbeek ok. https://gist.github.com/guerler/147aa24a067053161ac68e5832f8144d.
