### ISSUE TITLE
script maintenance.sh fails on 22.01

### ISSUE THREAD

**Issue by martinwolst** [galaxyproject/galaxy#14972]
**The bug**
Running the maintenence.sh script fails with:

```
Traceback (most recent call last):
  File "scripts/cleanup_datasets/cleanup_datasets.py", line 542, in <module>
    main()
  File "scripts/cleanup_datasets/cleanup_datasets.py", line 129, in main
    delete_datasets(app, cutoff_time, args.remove_from_disk, info_only=args.info_only, force_retry=args.force_retry)
  File "scripts/cleanup_datasets/cleanup_datasets.py", line 284, in delete_datasets
    library_dataset_ids_query = sa.select((app.model.LibraryDataset.table.c.id,
AttributeError: type object 'LibraryDataset' has no attribute 'table'
```

Galaxy Version: 22.01
Commit: d75c0fdbc2ab7449917c5e20cb9bdb8cd0a4cd47

**To Reproduce - running in dry-run mode**
switch to the galaxy user and:
 `source /srv/galaxy/venv/bib/activate`
 `export GALAXY_CONFIG_FILE=/srv/galaxy/config/galaxy.yml`
`cd /srv/galaxy/server`
`bash scripts/maintenance.sh` 

**Expected behaviour**
Script runs to clean up data(base)

**Comment by jdavcs** [comment]
Fixed in #15222
