### ISSUE TITLE
HEAD and byte-range support

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#14982]
Should fix https://help.galaxyproject.org/t/cannot-open-file-with-ucsc-genome-browser/9007 and make things like IGV usable without nginx (which of course you'll still want to use for production).

**Comment by jennaj** [comment]
**Tests**
You can display your dataset with the following links:
display at UCSC (**fast, works**) [main](https://usegalaxy.org/display_application/f9cad7b01a47213517ae0d7c76c1b113/ucsc_bigwig/main) )
display in IGB (**slow, keeps restarting the data transfer on a dinky test file?**) ( [View](https://usegalaxy.org/display_application/f9cad7b01a47213517ae0d7c76c1b113/igb_bigwig/View) )
display with IGV (**fast, but doesn't recognize the file type?**) ( [web current](https://usegalaxy.org/display_application/f9cad7b01a47213517ae0d7c76c1b113/igv_bigwig/web_link_main) , (**works, fast**) [local](https://usegalaxy.org/display_application/f9cad7b01a47213517ae0d7c76c1b113/igv_bigwig/local_default) )


Dropping the test data sources + the UCSC test result (where the original problem was found) here as a reference
* Galaxy history https://usegalaxy.org/u/jen/h/test-bigwig-2
* UCSC session http://genome.ucsc.edu/s/Jenjackson/11%2D14%2D22_mm9_bigwig_galaxy
