### ISSUE TITLE
ncbi_datasets_source tool seems dysfunctional

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#14988]
**Describe the bug**

Tool just redirects to the ncbi site. Unclear how / if it works.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.01

**To Reproduce**

Start the tool. 

**Expected behavior**

Tool should work / be deprecated.

**Additional context**

There is now https://github.com/galaxyproject/tools-iuc/tree/master/tools/ncbi_datasets

**Comment by mvdbeek** [comment]
It works, just use the send to Galaxy functionality from ncbi datasets.

**Comment by mvdbeek** [comment]
The original site has been replaced with a alpha version it seems. Was this intentional @BradHolmes ? Should we deprecate the send to galaxy functionality on our side?

**Comment by mvdbeek** [comment]
It has moved a little:
![image](https://user-images.githubusercontent.com/6804901/201948877-7da2cf88-9ad7-4f38-979f-c6363e036950.png)

Is that enough to close it @bernt-matthias ?

**Comment by bernt-matthias** [comment]
> Is that enough to close it 

Certainly. Thanks for checking. Is there anyway to have a help text for data sources?
