### ISSUE TITLE
Collection history outputs do not show job failed info

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/galaxy#14980]
Related to https://github.com/galaxyproject/galaxy/issues/14128.

When a job fails and the only output is a collection, there seems to be no way to view the info on the failed run (i.e. the "info" and "bug report" icons are missing.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05 / dev.usegalaxy.org.au
Commit: 22.05 release

**To Reproduce**
Steps to reproduce the behaviour:
1. On dev.usegalaxy.org.au, run the ["Untar" tool](https://dev.usegalaxy.org.au/tool_runner?tool_id=tar_extract) on a tar archive
3. See the history output when the tool breaks
4. Repeat the above with any failing tool that outputs a collection only, on release 22.05

**Expected behaviour**
The collection should allow access to the tool run info, and bug report submission by displaying the appropriate icons. Perhaps the collection item should expand when clicked to show these icons, rather than dropping into the collection immediately. The UI could show an additional icon (like a chevron) to drop into the collection in one click.

**Screenshots**
The failed history output:
![image](https://user-images.githubusercontent.com/42562517/201554881-c4097ea1-905f-489a-889d-39ec1929abdb.png)

After clicking on the output:
![image](https://user-images.githubusercontent.com/42562517/201554893-0e07f0a1-a2a9-4d35-9f29-ddb1b28658bc.png)

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/12261 is the PR that added this, I'm not seeing the 3 dot menu on the side anymore, so I guess that's where this got lost.

**Comment by mvdbeek** [comment]
This was fixed some time ago.
