### ISSUE TITLE
include HDF5 visualisation into Galaxy

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#14994]
HDF5 is used across all different domains and a good visualization of that would be great.
I was pointed to https://github.com/silx-kit/h5web which looks promising.

**Comment by dannon** [comment]
I looked into this with someone at GCC and this is exactly what we came up with. We need to add the data provider for it, but it would be a really nice addition.

I'll take a first pass it writing up what we talked about then.

**Comment by dannon** [comment]
We can close this one out, thanks again @jarrah42!
