### ISSUE TITLE
Publication of Galaxy Release v 16.01

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1499]
Prep:
- [x] Set freeze date
- [x] Set announce date
- [x] Stage annoucement content (Wiki, Biostars, Bit.ly link) on annouce date to capture date tags. Note: all final content does not need to be completed to do this.
- [x] Finalize Github content

Announce:
- [x] Finalize https://github.com/galaxyproject/galaxy/blob/dev/doc/source/releases/16.01_announce.rst
- [x] Post release notes to https://galaxy.readthedocs.org/en/master/releases/index.html
- [x] Create wiki _highlights_ and post to http://galaxyproject.org News (w/ RSS) and NewsBriefs
- [x] Tweet wiki news _highlights_ (or RTD?) via bit.ly link to https://twitter.com/galaxyproject/
- [x] Post _highlights_ type News to Galaxy Biostars https://biostar.usegalaxy.org
- [x] Email _highlights_ to galaxy-dev and galaxy-announce @lists.galaxyproject.org
- [x] Adjust http://getgalaxy.org text and links to match current master branch

**Comment by jmchilton** [comment]
See also #1434 xref #1435

**Comment by jmchilton** [comment]
I'm going to work on a `Makefile` target to build this issue automatically. I'm going to remove `Set announce date` since we have moved a more fluid setup where we do the "final" (or really first) release or a new version when it is ready not on timelines.

What is meant by "Finalize github content" here? Like release notes?

I'm going to have an itemized TODO list for "branching", "deploying to test and usegalaxy.org", and "creating release notes".

**Comment by jennaj** [comment]
@jmchilton I put in "Finalize Github content" as a placeholder. It means to me that everything code related going into the release is finished and published (merging, tags, etc). Please adjust this (or anyone else) so that it is clearer. I didn't want to duplicate details in other tickets, but details could be added for top-level distinct portions of those, if we wanted.

**Comment by natefoo** [comment]
The initial generation of the release notes is a one time event, right? Now that it's been done, the change mentioned by @mvdbeek (#1347) needs to be added by hand?

**Comment by jmchilton** [comment]
That was added to the dev branch in 16.04 - I don't think we should add it to the release notes yet.

**Comment by natefoo** [comment]
Oh, good catch.

**Comment by mvdbeek** [comment]
> That was added to the dev branch in 16.04 - I don't think we should add it to the release notes yet.

it is in 16.01, I [believe](https://github.com/galaxyproject/galaxy/blob/release_16.01/lib/galaxy/jobs/runners/util/job_script/CLUSTER_SLOTS_STATEMENT.sh)

**Comment by jmchilton** [comment]
Sorry - wrong change - yeah that should be in the release notes.

**Comment by natefoo** [comment]
Just checked and it is already in the release notes.
