### ISSUE TITLE
More convienient ways to create Data Libraries

### ISSUE THREAD

**Issue by mira-miracoli** [galaxyproject/galaxy#15007]
I encountered a few problems yesterday, when I helped [@engynasr](https://github.com/engynasr) to upload her datasets in a Data Library.

1.  The folder upload is only possible for admin users, and only by rsync-ing the files to our galaxy's server
2.  After the upload, I was able to import the files with the admin-only path-import-tool, but it showed an red error pop-up and I dont know if everything worked correctly.
3.  The permissions are automatically set to my user only for all the datasets and I don't see a way to change this efficiently (we have 942 Files, every single one would have to be changed manually

My suggestions:
 - implement a folder upload for users in the Data Libraries. This could also be tied to a certain role or manual permission from admins to prevent abuse
 - make it possible to mutate permissions for all datasets in folders and sub-folders at once
 - fix popups or show errors more accurately and remove '200% completed' text in upload window.
 - if we keep the admin path upload, please specify which paths are allowed, because not all locations worked for me
 
Thank you in advance. I think this could make life easier for both admins and users :)

**Comment by hexylena** [comment]
I'm guessing you don't need it any more, but since this issue came up in admins chat, I shared the rubbish bash script I wrote for the same bullet point: https://github.com/usegalaxy-eu/shared-data/blob/master/run.sh#L12-L26

**Comment by mira-miracoli** [comment]
Thank you :) I created this ephemeris command: https://github.com/galaxyproject/ephemeris/pull/187
Maybe that can be also used until there is a upstream solution

**Comment by hexylena** [comment]
Ah, I'd already forgotten about that command. We should include it in the data library training hmm.
