### ISSUE TITLE
Internal server error for published Galaxy EU workflow

### ISSUE THREAD

**Issue by foellmelanie** [galaxyproject/galaxy#15014]
Hi, 

I have a couple of published Galaxy EU workflows and for one workflow the link does not work anymore "Internal server error". My workflow is shared and published and I can edit it in my the workflow editor of usegalaxy.eu without any problem. 

Link to Workflow: https://usegalaxy.eu/u/melanie-foell/w/bladder-msi-wf2-data-handling-and-preprocessing
Link to crash report: https://gist.github.com/bgruening/70bf5e07073820e214df978b807ea371

Cheers,
Melanie

**Comment by mvdbeek** [comment]
This is working fine now that we've removed the server side mako rendering.
