### ISSUE TITLE
List of UI projects

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#15035]
Copied from WG Meeting 2022.10, linked merged UI/UX PRs since around Nov 1st, and additional relevant PRs.

**23.1 (GCC)**

- Graph View of History [Backend]

- Invocation Display leveraging editor

- Notification Framework

- Vue as the sole framework in primary app

- Zero backbone, Zero jQuery, single entry

- Grids

- Upload

- FormElements
#15016

- First Class Visualizations

- Display API [Backend]

- IGV.js replacing Trackster

- TS Client for Galaxy API [Backend]

- Autogenerated, typed, published

- Archival/Frozen histories [Backend]

- Testing for Accessibility [Testing, GOATS]

- E2e and Linting
#15026

**23.0**

- New Workflow Editor [Workflows]
#14987
#14870
#14853
#14816

- Separate published package

- Graph View Exploration/Precursors

- Input/Output display `related:hid` filter.

- Toolbox/Search Modernization
#14391

- Fast filtering of the toolbox with rich results in middle panel

- Multi-History
#14729
#14703
 #13985

- Unified Export UI

- Pluggable, with RO-Crate & Biocompute

- Modernization
#15012
#15008
#14935
#14930
#14842
#14838
#14832
#14831
#14830

- Toolform Improvements
#14866
#14861

- With Vue2.7 move towards Composition API, Pinia
#14250

- Typescript

- Significantly fewer entry-points, reloads and a single Vue tree now
#14523
#13984

- Accessibility [GOATS]

- WCAG 2.1 AA(A)? Compliance

- Storage Dashboard
#13113

- Visualizations
#15013
#14973

- New Tabular Renderer

- Vue-based visualization plugin

- IT Display Issues

- Accurate status, representation in history

- Prebuilt Production client for releases

- Publication on npm with components

- Bugfixes
#14924
#14907
#14897
#14857
#14828
#14823

**Comment by martenson** [comment]
all the linked PRs are done, I'll close this for the sake of cleanliness but feel free to refresh it
