### ISSUE TITLE
Type error: new history_id fixture conflicts with history_id instance variables

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#15032]
A recent change introduced a bug in our integration testing code. The new `history_id` pytest fixture ([see integration_utils.py](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy_test/driver/integration_util.py#L192)) conflicts with `history_id` instance variables [like this one](https://github.com/galaxyproject/galaxy/blob/dev/test/integration/test_upload_configuration_options.py#L57). This leads to multiple type errors  (~90) which can be triggered by running `mypy test lib` from a galaxy venv.

There have been two PRs that contain fixes to this bug: #14971 (currently a draft) and #15020 (closed). The former leaves the fixture intact and removes all references to `self.history_id`. The latter renames the fixture and updates all tests that use it. The former is a better approach; besides, it also solves the problem of assigning stuff to `self` in the body of a test (in pytest, each test gets its own instance of the class it belongs to ([ref](https://docs.pytest.org/en/7.1.x/getting-started.html#group-multiple-tests-in-a-class)), so assigning anything to `self` in a test is misleading at best).

I'm opening this issue to track the `history_id` bug (which is not the focus of #14971). Fixing this bug removes 91 mypy errors and, therefore, is a prerequisite for #15004.  (ping @nsoranzo, @mr-c)

**Comment by mr-c** [comment]
Thanks for documenting this @jdavcs 

@nsoranzo shall I split out the relevant changes from my PR for quicker review & merging, or do you want to keep them all together?

**Comment by jdavcs** [comment]
> @nsoranzo shall I split out the relevant changes from my PR for quicker review & merging, or do you want to keep them all together?

+1 for splitting out the bug fix. It keeps the PRs focused.

**Comment by mr-c** [comment]
I've opened https://github.com/galaxyproject/galaxy/pull/15037
