### ISSUE TITLE
Galaxy ignores `prefix` for Openlayers visualization plugin

### ISSUE THREAD

**Issue by mahendrapaipuri** [galaxyproject/galaxy#15047]
**Describe the bug**
We are using Openlayers visualization tool on a Galaxy instance served at a prefix `/cos`. It seems that the prefix of the Galaxy is being ignored with making an API request to `histories` endpoint. Here is a screenshot of console log of browser

![Screenshot_20221122_122834_masked](https://user-images.githubusercontent.com/44365948/203319042-a9b5c34a-5624-42ae-952e-d688058b0e40.png)

The failed API request is supposed to be `https://galaxyhost/cos/api/histories/<snippet>`

There was a very similar issue in the past https://github.com/galaxyproject/galaxy/issues/9970

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version:  `22.09-dev0`
Commit: a7d35017d42f78d3f8d46b592402d08be7bb5b56

**To Reproduce**
1. Upload a shape file into Galaxy
2. Click on visualize shape file
3. Click on OpenLayers map
4. Check browser console

**Expected behavior**
Able to visualize the map and plugin making API requests to correct path

**Comment by mahendrapaipuri** [comment]
So, I had bit of time to dig through it and we will have to pass safe URLs to get datasets in the plugins. By modifying URL [here](https://github.com/galaxyproject/galaxy/blob/dev/config/plugins/visualizations/openlayers/src/script.js#L244-L247) to

```
window.bundleEntries.load = function (options) {
    const chart = options.chart;
    const dataset = options.dataset;
    const slash_cleanup = /(\/)+/g;
    const safe_url = `${options.root}/${dataset.download_url}`.replace(slash_cleanup, "/");
    $.ajax({
        url: safe_url,
        success: () => {
            MapViewer.loadFile(safe_url, dataset.extension, options, chart);
        },
        error: () => {
            chart.state("failed", "Failed to access dataset.");
            options.process.resolve();
        }
    });
```
will fix the problem. I have tested it on `dev` branch.

I noticed that there are multiple plugins which use similar implementation to get datasets. So, I guess we need to change them all. 

@mvdbeek I can put up a PR if you agree with changes?

**Comment by yvanlebras** [comment]
Wahou, THANK you Mahendra for taking time to look at it more deeply and identify and propose a fix!!!!
