### ISSUE TITLE
reloading page after hiding the tool panel shows it again

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#15077]
Mentioned by @mvdbeek on the UX call and I remembered just how much this throws me off. Ditto for history panel.

**Comment by ahmedhamidawan** [comment]
Notes from UI meeting: 
- Store the state in `localStorage`

**Comment by ahmedhamidawan** [comment]
This is fixed with the introduction of the `ActivityBar`, for which we track the opened/closed state in localStorage. We can reopen this if we still want to track this for the "non-ActivityBar" side panel?
