### ISSUE TITLE
Ordering versions of tool by date instead of version 

### ISSUE THREAD

**Issue by anilthanki** [galaxyproject/galaxy#15071]
**Describe the bug**
At the moment, Galaxy with more than one version of tools list them out sorting naturally based on version number. But, we have case when someone introduced extra characters in tool version (i.e. +1, +2, +3) sending the latest version of the tool to the bottom of the list. Also with this Galaxy choses other than the latest version of the tool by default.

**To Reproduce**
install more than one version of `scanpy` tool from [ebi-gxa](https://toolshed.g2.bx.psu.edu/repository/browse_repositories_by_user?user_id=1aaf1010134c91da) and try and look at different versions.

**Expected behavior**
Tool should be listed by their push date instead of version, for having latest changes in the top.

**Screenshots**
![image](https://user-images.githubusercontent.com/3940626/204331919-391ef51b-a19b-4b79-9f77-bf4c859ea1d2.png)

**Comment by mvdbeek** [comment]
Sorry, I don't think we can change this, version need to follow a sortable scheme. We're using [pep440](https://peps.python.org/pep-0440/) as implemented via `packaging.version`:

```python
>>> import packaging.version
>>> packaging.version.parse('1.7.2+galaxy0') > packaging.version.parse('1.8.1+1+galaxy0')
True
```

**Comment by pcm32** [comment]
@anilthanki I think that we can fix this in the meantime by changing the version scheme used for those tools and pushing a newer version to the toolshed.

Would it be feasible to check for packaging.version compliance on planemo at lint time perhaps @mvdbeek? The problem I think is that `1.8.1+1+galaxy0` seems to be acceptable to packaging.version (the above snippet is not failing with a parsing exception). I don't see on the planemo code any explicit checks done with `packaging.version`. To avoid these sort of issues in the future I mean.

**Comment by martenson** [comment]
@pcm32 Both of these are compliant versions according to the scheme and Planemo does not necessarily have the info about what the version should be bigger than. Possibly this could be toolshed-enforced I guess?
