### ISSUE TITLE
Activity Bar UI Component

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#15080]
This project would shift activities or areas of the application unrelated to global or user status to an Activity Bar (
https://code.visualstudio.com/api/ux-guidelines/activity-bar), similar to how VSCode organizes different activites.  This frees up masthead space and avoids long menus while giving us a lot more space for expansion, while retaining a persistent navigation context with a persistent footprint.
![image](https://user-images.githubusercontent.com/155398/204806254-2110e696-006c-4d4e-8f7b-435d442b649d.png)

Along the left side we could have an icon for each:

- Tools
- Workflows
- Visualizations
- ITs
- Libraries
- Invocations
- Pages
- ... (activities, etc)

xref #14802 and discussions around that.  This should be split out as a separate project from a search-based hidden toolbox.

**Comment by mschatz** [comment]
This is awesome work. In round numbers I think we should aim for about 8 to 10 buttons (similar to the https://vscode.dev/). Tools, Upload, Workflows, Visualize, Data all make sense. Id also recommend the history picker as another top level icon (https://usegalaxy.org/history/view_multiple)

**Comment by hexylena** [comment]
> so presumably that would be done over a few releases to accommodate adjustment

the counterpoint is it means more small churn for users, and for re-recording trainings, vs one big jump. (Not sure how to balance these two, but either way looking forward to this new component!)

**Comment by mvdbeek** [comment]
The plan to roll this out is to make this opt-in, once were happy and we have good feedback we can switch this over, which would be the point at which things would need to be re-recorded

**Comment by hexylena** [comment]
Ah perfect @mvdbeek!

**Comment by dannon** [comment]
Initial implementation of this is done and opt-in.  Closing this issue in favor of more granular followups as necessary.
