### ISSUE TITLE
Export history to different instance by URL

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/galaxy#15100]
**Describe the bug**

When trying to export a history from *eu to *org.au I got this error:

```
Traceback (most recent call last): File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/imp_exp/unpack_tar_gz_archive.py", line 92, in <module> main(options, args) File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/imp_exp/unpack_tar_gz_archive.py", line 73, in main check_archive(archive_file, dest_dir) File "/mnt/galaxy/galaxy-app/lib/galaxy/tools/imp_exp/unpack_tar_gz_archive.py", line 38, in check_archive with tarfile.open(archive_file, mode="r") as archive_fp: File "/usr/lib/python3.8/tarfile.py", line 1608, in open raise ReadError("file could not be opened successfully") tarfile.ReadError: file could not be opened successfully
```

**Galaxy Version and/or server at which you observed the bug**
"version_major":"22.05","version_minor":"1"

**To Reproduce**
1. Copy this URL from a shared and published history: https://usegalaxy.eu/u/gallardoalba/h/srp201920salmon-1
2. Import it in usegalaxy.org.au: Users/Histories/Import history/Export URL from another Galaxy instance

**Expected behavior**
The history should be shared.

**Screenshots**

![Screenshot from 2022-12-01 19-42-25](https://user-images.githubusercontent.com/26678117/205134298-a064ec81-1b83-4918-9717-2223c3a9a992.png)

**Additional context**

**Comment by davelopez** [comment]
Can you reproduce the same with a smaller history? This history is nearly 400 GB, I can imagine many things can go wrong with such a huge tar file...

**Comment by cat-bro** [comment]
Because this happened on .org.au I was curious and had a look at recent jobs.  All of the IMPORT HISTORY job from url "<galaxy_url>/u/<username>/h/<history_name>" fail.  Some IMPORT HISTORY jobs from a url shaped like "<galaxy_url>/api/histories/<history_uuid>/exports/<some_uuid>" succeed and these URLs are generated from History Menu -> Export History to File then clicking on the "to a link" button.

**Comment by mvdbeek** [comment]
> * Copy this URL from a shared and published history: https://usegalaxy.eu/u/gallardoalba/h/srp201920salmon-1

So .. that can't possibly work, why did you think it would @gallardoalba ? This isn't an export ... although it would of course be cool to import a published history.

**Comment by mvdbeek** [comment]
A simple UI/UX fix is to check that the url points at the proper API route. No, I don't think that was ever possible.
