### ISSUE TITLE
Reformulate "starred" outputs in workflow editor

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#15132]
**Describe the bug**

In the workflow editor under "Output cleanup" the text speaks of (non-) _starred_ outputs: see

https://matrix-client.matrix.org/_matrix/media/r0/thumbnail/matrix.org/PdCDsCQATPBfcMKMEmovXLcM?width=800&height=600&method=scale

should be reformulated to _checked_ / _selected_

Matej Troják

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/15125 ?

**Comment by bernt-matthias** [comment]
Indeed. Did not noticed this one ..
