### ISSUE TITLE
Mpileup failing when used in a workflow on usegalaxy.org and local instance

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#1514]
Getting a lovely stacktrace https://gist.github.com/Takadonet/aab406bc7db49808a593
when I attempt to run a workflow where a mpileup jobs are using a BAM file as input.

Seems to be a race condition because if I submit the jobs 'by hand' it works every time. Issue is reproducible  on usegalaxy.org as well.

**Comment by martenson** [comment]
ref to one offender: https://github.com/galaxyproject/galaxy/blob/release_16.01/lib/galaxy/tools/__init__.py#L1728

**Comment by jmchilton** [comment]
Do you have any more information?
- Is it just this workflow, any workflow that uses freebayes, any workflow that has a bam input, etc...?
- Can you build a minimal workflow that exhibits this bug?
- Is the bam input in the previous step created directly or implicitly (i.e. is the previous output a bam directly or a sam that gets implicitly converted)?

**Comment by Takadonet** [comment]
It's mpileup that is not being created correctly. Freebayes runs to completion. 

The smallest workflow that causes to error on usegalaxy.org is this one : http://imgur.com/36e4p61   

You can import @ https://usegalaxy.org/u/phil/w/test-mpileup

It takes in a list collection but a list paired should fail as well.

Previous bam output was created as a bam and not converted from a sam
