### ISSUE TITLE
Workflow editor: Does not save values for inputs of type="data_column" multiple="True"

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#1521]
Example:
- Create new workflow
- Add "Vegan Rarefaction" tool
- Set "Sample count columns" to 2
- Save
- Close
- Edit workflow

Value for column(s) has not been saved. Parameters with multiple="False" do not seem affected. This was tested on latest dev (49a72dacc678e2be017d7b926afc87d17de7e179), but I did not check other branches.

**Comment by blankenberg** [comment]
16.01 / usegalaxy.org appear to be affected as well.

**Comment by guerler** [comment]
On it.
