### ISSUE TITLE
"__v_isRef" is not defined on the instance

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#15239]
on latest `dev` loading Galaxy yields 27 browser console errors like below

I suspect this could be related to https://github.com/galaxyproject/galaxy/pull/14905?

```
vue.esm.js?a026:5059 [Vue warn]: Property or method "__v_isRef" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <UploadModalContent> at src/components/Upload/UploadModalContent.vue
       <BModal>
         <UploadModal> at src/components/Upload/UploadModal.vue
           <App> at src/entry/analysis/App.vue
             <Root>
```

**Comment by dannon** [comment]
Yeah, we need to follow up on this.  The underlying issue with the uploader is potentially related to #15111, too.  It'd be useful to bisect to see where that particular test started failing.

**Comment by ElectronicBlueberry** [comment]
The errors were present before #14905 
They appear when the UploadModal is loading. The PR loads the upload modal sooner, which is why they more apparent now.

**Comment by ElectronicBlueberry** [comment]
I've tracked it down.

It is caused by these 4 components:

```js
import Composite from "./Composite";
import Collection from "./Collection";
import Default from "./Default";
import RulesInput from "./RulesInput";
```

Specifically these bindings seem to be the cause:
`:app="this"`
