### ISSUE TITLE
Buttons in tool search results not aligned properly

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#15258]
Noticed two minor UI glitches in the advanced search results, 1) the `open` buttons are not aligned properly, 2) the scroll bar becomes partially visible behind the buttons. Just noting it here to keep track.

<img width="838" alt="image" src="https://user-images.githubusercontent.com/2105447/209395839-29214e0f-6818-4589-a860-0e56f25d76a7.png">

**Comment by dannon** [comment]
Should standardize external link icon as well -- other places we use the rectangle with the arrow.
