### ISSUE TITLE
Bug: The default theme is no longer set, when a single theme is provided. Instead, the `blue.scss` values are used.

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#15290]
Bug: The default theme is no longer set, when a single theme is provided. Instead, the `blue.scss` values are used.

_Originally posted by @ElectronicBlueberry in https://github.com/galaxyproject/galaxy/pull/15256#pullrequestreview-1240877379_

**Comment by ElectronicBlueberry** [comment]
This seems to have been caused locally on my end by the celery worker or an old cache, and is fixed.
