### ISSUE TITLE
User Authentication: idP identifier too long

### ISSUE THREAD

**Issue by EGI-ILM** [galaxyproject/galaxy#15294]
I am trying to use a custom Keycloak with Galaxy (EGI Check-in).
It seems to be a problem because there is a "value too long for type character varying(64)". Our identifiers are similar to:

`bb33ce240f126e0f8add0abad6c2f8f37129be3223fac59127a6236bfc2fdfae@egi.eu`

which does not seem to fit inside `external_user_id`:

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/model/__init__.py#L8843

```
class CustosAuthnzToken(Base, RepresentById):
    __tablename__ = "custos_authnz_token"
    __table_args__ = (
        UniqueConstraint("user_id", "external_user_id", "provider"),
        UniqueConstraint("external_user_id", "provider"),
    )

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("galaxy_user.id"))
    external_user_id = Column(String(64))
    provider = Column(String(255))
    access_token = Column(Text)
    id_token = Column(Text)
    refresh_token = Column(Text)
    expiration_time = Column(DateTime)
    refresh_expiration_time = Column(DateTime)
    user = relationship("User", back_populates="custos_auth")
```

Would it be possible to increase the size of the field to accommodate longer identifiers?

Thanks.

**Galaxy Version:** latest

**To Reproduce**
- Configure Check-in as custom Keycloak idP (I can give specific details if needed).
- Attempt to log in.

**Comment by dannon** [comment]
@EGI-ILM Yes, this should be possible and seems reasonable.  What we'd need to do is add a database migration altering the column to extend the length of that field

**Comment by EGI-ILM** [comment]
Hello, I am interested in the state of this issue. It seems the `external_user_id` size is still 64.

**Comment by enolfc** [comment]
Related: #16782
