### ISSUE TITLE
Feature request - symlink files when uploading data to data library using the "from user directory" option

### ISSUE THREAD

**Issue by matthdsm** [galaxyproject/galaxy#1529]
Hi, 

When using the "user_library_import_dir" option user get the possibility to upload files into data libraries. However, it's currently not possible to symlink those files (instead of copying) when selecting a single file. If the user wants to upload an entire folder this option is available.

Is it possible to add the "symlink" checkbox to the upload interface?

Thanks!
Matthias

**Comment by nsoranzo** [comment]
Also requested to me by @ethering.

**Comment by sarah-peter** [comment]
+1
We also made use of this feature with the old data libraries and it would be great to have it back. I'm afraid of users duplicating huge datasets because the option is not directly available for single files.

**Comment by gregvonkuster** [comment]
+1 on this.  This is really needed for very large datasets (5-80 gb) when running in batch mode using the API to import many datasets into data libraries.

**Comment by RJMW** [comment]
:+1:  This would be of great use to us. Similar reasons as @gregvonkuster
