### ISSUE TITLE
addValue tool input datatype does not propagate to output

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#15302]
**Describe the bug**

When running a tool which is supposed to propagate the input's datatype, the datatype is explicitly set to `input` instead.
Here is an example using  a `bed` file and the `addValue` tool:

https://user-images.githubusercontent.com/2105447/212200589-050fc3ab-661c-4f44-ae3b-79208fd34fcd.mov

The tool xml seems to properly specify the metadata source: https://github.com/galaxyproject/galaxy/blob/dev/tools/filters/fixedValueColumn.xml#L21

This being said the tool test only verifies the output content, we should probably also verify the output datatype, once this is fixed.

**Galaxy Version and/or server at which you observed the bug**
Only in current dev. Issue does not exist on main which properly propagates the datatype.

**Comment by martenson** [comment]
I assume the fact that gif is from .org.au which runs 22.05 is non-issue?

**Comment by guerler** [comment]
I was just trying to some themes. Sorry, I restore to the default. This is current dev.

**Comment by bernt-matthias** [comment]
As I have recently noted the built in tool in Galaxy are neither linted nor tested https://github.com/galaxyproject/galaxy/pull/15229 .. so changing the built in tool would not verify the issue.

But we have some functional tool tests that are close to the case reported here: 

- test/functional/tools/output_format.xml .. just misses the ftype test

Maybe you can extend one of these tests or add a new one to verify the issue?

**Comment by mvdbeek** [comment]
This is my bad (https://github.com/galaxyproject/galaxy/commit/350508909d6a7c26f10fa324c6ccb2044fb20d0b), and only concerns this one particular tool. You either have to use `format_source="input"` or you drop the profile version. See https://github.com/mvdbeek/galaxy/commit/b92074e6ff87a19133b4d973577779c4ee6286d7

**Comment by nsoranzo** [comment]
The attribute of the `data` element should be `format_source` not `format`, so it's a bug in the tool.
