### ISSUE TITLE
Workflow import is broken

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#1530]
I'm trying to export a workflow (https://test.galaxyproject.org/u/anton/w/duplexanalysis/json) from test.galaxyproject.org to usegalaxy.org 

It gives the following error:

```
Galaxy could not be reached

You are seeing this message because a request to Galaxy timed out or was refused. 
This may be a temporary issue which could be resolved by retrying the operation you were performing. 
If you receive this message repeatedly or for an extended amount of time, please report it to the Galaxy
 Team at galaxy-bugs@bx.psu.edu with details on what you were trying to do and the URL in the address 
bar. More information on the current state of Galaxy services may be available on the Galaxy status page
 or the @galaxyproject Twitter feed.
```

**Importnatly** it throws you into Admin interface!:
\
![screen shot 2016-01-19 at 9 40 15 am](https://cloud.githubusercontent.com/assets/4291636/12421533/ae5f8fea-be90-11e5-92de-6faec6ec9710.png)

**Comment by jmchilton** [comment]
The workflow is using tools absent on main - it is throwing you back to admin on purpose so you can install them (it wouldn't do this if the tools were present or if your weren't an admin). Something is messed up with the message handling I guess, looking into it.

**Comment by jmchilton** [comment]
Actually - I think what is happening is you are missing many tools and so the repeated calls to the tool shed to find the tool links is causing the request to timeout. This is a very particular deployment problem IMO - it would be best to just delay the fix until things can be re-architected to behave better (async JavaScript, etc...) - but short of that the best fix might be to increase the timeout nginx gives this endpoint. @natefoo can we do that on a per URL basis?

**Comment by natefoo** [comment]
We can increase it, although the timeout is already really high (5 minutes).

**Comment by martenson** [comment]
this happens immediatelly after you click `import` =  it is not a timeout; the message that is supposed to be rendered is visible in the log

![screenshot 2016-01-21 16 42 45](https://cloud.githubusercontent.com/assets/1814954/12495553/59ec5086-c05e-11e5-91fb-e78b0f049bff.png)

**Comment by jmchilton** [comment]
@nsoranzo points out it is actually probably uWSGI chopping up the URL:

```
15:54 < nsoranzo> I have a workflow file an user was trying to import, which contains some 
                  tools which are not present on the Galaxy instance
15:58 < nsoranzo> The file gets imported, but uwsgi discards the last GET request because 
                  the query string (which contains a super long error message with the 
                  list of missing tools) exceeds the maximum length
15:59 < jmchilton> I think the fix is to move that an API endpoint so we aren't actually 
                   using query parameters like that
16:00 < nsoranzo> I can change the buffer-size option of uWSGI from the default of 4096 to 
                  e.g. 16384, but I'm not that's the best solution
16:00 < jmchilton> there are other places in Galaxy where this occurs - I might just 
                   create a Github issue modify the defualt, and move on?
16:01 < jmchilton> We've updated a lot of that workflow stuff to use the API recently - 
                   import is probably coming soon (guerler might have already done it?)
16:01 < nsoranzo> That's on 16.10, if that matters
16:05 < jmchilton> so probably it hasn't been moved to the API yet
6:07 < nsoranzo> Hi guerler!
16:07 < guerler> hey
16:08 < guerler> import of workflows its on the list, ideally once we improved how 
                 workflow modules are handled but i have not touched it yet.
16:09 < nsoranzo> OK, good to know! The workaround is working, so I'll do as jmchilton 
                  suggested and open an issue
16:09 < guerler> awesome
16:09 < guerler> thx for reporting it
16:14 < nsoranzo> I think this is the same bug, but was not correctly identified 
                  https://github.com/galaxyproject/galaxy/issues/1530
```

**Comment by natefoo** [comment]
So we're agreed that the current best solution is to increase the uWSGI `buffer-size` to 16384?

**Comment by nsoranzo** [comment]
@natefoo That worked for me, but that value may not be enough if the error message is very long, depending on how many tools/versions used in the workflow are missing in the Galaxy instance.

**Comment by scholtalbers** [comment]
Till this is fixed, maybe this can be documented on either the 'wiki/hub' or set in the example https://github.com/galaxyproject/galaxy/blob/dev/contrib/galaxy_supervisor.conf file?

**Comment by natefoo** [comment]
Forgot to update the issue, but I did increase the `buffer-size`. Is this still an issue?

**Comment by martenson** [comment]
@natefoo I just imported the WF mentioned in the first message here to Main. Worked fine except of some params warnings due to tool versions probably.
![screenshot 2017-05-19 15 25 41](https://cloud.githubusercontent.com/assets/1814954/26263632/8fd1cb10-3ca7-11e7-85c9-a60afdb73955.png)
