### ISSUE TITLE
TS tool lineage sometimes breaks after repo update

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1532]
I updated MTS with changes in https://github.com/galaxyproject/tools-devteam/pull/320 and the tool lineage for `bwa-mem` tool broke in a way that all versions in between 0.1 and 0.7.12.1 were missing from it. The `bwa` tool lineage was fine. Metadata reset fixed the lineage.

**Comment by nsoranzo** [comment]
:+1: 

This is a recurrent problem with the `bwa` repository and it is always `bwa_mem` that breaks. May be related to the underscore in the tool id?

**Comment by gregvonkuster** [comment]
Its likely due to some "corner case scenario" in the repository change log.  Perhaps a solution would be to somehow automate resetting all repository metadata on each new upload to the Tool Shed.  Can the planemo upload process do something like this?

**Comment by lparsons** [comment]
Just ran into this again with `bwa_mem`, btw.

**Comment by mvdbeek** [comment]
This should be solved on the galaxy side with #4119.
