### ISSUE TITLE
When re-running a tool with default hidden input, changing parameters removes hidden inputs

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1534]
Re-running a tool that uses a hidden dataset...

![selection_548](https://cloud.githubusercontent.com/assets/458683/12427808/e3917424-bea6-11e5-9880-61284f9bf498.png)

Changing a parameter here removes the hidden inputs and defaults to another file.

![selection_549](https://cloud.githubusercontent.com/assets/458683/12427807/e3744e08-bea6-11e5-9b9e-171dff01082e.png)

**Comment by guerler** [comment]
I can reproduce this only if I change the dataset parameter itself, changing any other parameter in the form does not remove the selected hidden dataset for me. Can you verify that?

**Comment by hexylena** [comment]
I'm on dev from a week or so ago. 

I'm afraid I can't reproduce right now, I unhid the dataset where this was occuring and don't have another example handy. I'll try again later.

**Comment by guerler** [comment]
I assume that this only happens when a new dataset is selected. In that case, the backend dataset matcher will not unhide the previously selected dataset since it has no information on previous selections.

**Comment by guerler** [comment]
Thx a lot for catching/documenting this.
