### ISSUE TITLE
Failed Metadata State Display

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#15358]
The old history showed clearly when a dataset was in the 'failed_metadata' state, and the new history just shows it as an error.  `failed_metadata` is also potentially fixable, so it should be indicated clearly.

Also a note, this dataset can be selected as an input, which we might want to prevent?  (or not?)

![image](https://user-images.githubusercontent.com/155398/214124807-f5fcffe7-9c99-45a9-8e16-c75c3175af02.png)

Reported by @natefoo

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/15359
