### ISSUE TITLE
names from deleted and purged roles/groups can not be reused

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#15350]
**Describe the bug**

If roles or groups are deleted and purged the names can not be reused.

**Galaxy Version and/or server at which you observed the bug**

22.05

**To Reproduce**
1. delete and purge a roles or a group
2. try to create a role or a group with the same name
3. Not possible to create the role/group

**Expected behavior**

It should be possible to create a group/role with the same name of a purged role

**Comment by mvdbeek** [comment]
Difficult topic because what happens to previous references? I would say we should not allow this. If you want to do this you can undelete / unpurge the role or group (in the database for now, if it's a common thing an API and UI should be easy enough).

**Comment by bgruening** [comment]
The reference is the role/group ID, not the name, isn't it?

**Comment by mvdbeek** [comment]
Hopefully, in the database? But how did you wanna communicate to users that same group is not same group?

**Comment by ElectronicBlueberry** [comment]
Is it important to know for a user that a new group is not the same as a previously purged one?

**Comment by mvdbeek** [comment]
Yes, I think so.

**Comment by bgruening** [comment]
As an admin, I can rename groups as I like and this would cause the same confusion.

**Comment by mvdbeek** [comment]
Alright, and what happens if you rename the purged group ? is that enough ?

**Comment by bgruening** [comment]
You can not rename purged groups.

**Comment by mvdbeek** [comment]
Undelete, rename, purge again works for me. Given that I still think we should only do that in exceptional circumstances I don't think it's worth spending time on.

**Comment by bgruening** [comment]
Your opinion, I think it's a bug or at least a UX issue that's why I opened it.
