### ISSUE TITLE
unable to save ipython notebook on Main

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1535]
fresh notebook, one line of python in it
`Autosave failed!`
![screenshot 2016-01-19 13 40 04](https://cloud.githubusercontent.com/assets/1814954/12428365/3950aea6-beb2-11e5-91ea-172a0726c59f.png)

(in Jupyter saving works for me)

**Comment by hexylena** [comment]
Any more info with the bad request? Logs from the proxy?

**Comment by mvdbeek** [comment]
Upon special request from @martenson I'm gonna close this one, I'm sure we can get some more recent ones though.
