### ISSUE TITLE
WF editor thinks it "Cannot attach non-collection outputs to mapped over inputs"

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15369]
**Describe the bug**
For WF steps that receive a collection as input to map over for one param, but single dataset input for another param, the WF editor displays the warning:

`Cannot attach non-collection outputs to mapped over inputs, consider disconnecting inputs and outputs to reset this input's mapping.`

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org at 23.0

**To Reproduce**
Import https://usegalaxy.org/u/wolma/w/imported-generic-variation-analysis-on-wgs-pe-data and start editing it.

**Expected behavior**
This perfectly legal situation should not be flagged.

**Screenshots**
![Screenshot from 2023-01-24 10-19-29](https://user-images.githubusercontent.com/4742081/214255140-cf7a1afb-5c1d-4e9a-9e29-9574b9a6fec4.png)

**Comment by mvdbeek** [comment]
Ah, I see what went wrong, that check is supposed to make sure that you're not mixing dataset output and collection output on the **same** input node!
