### ISSUE TITLE
UCSC Main data fetch error 

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/galaxy#15362]
**Describe the bug**
On GTN tutorial [Peaks to Genes](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-peaks2genes/tutorial.html). Data import using the "UCSC Main table browser" failed.

This is working on 22.05 (Galaxy AU).

**To Reproduce**
On Galaxy v23.0, follow the "Data upload from UCSC" section in the tutorial linked above.

**Expected behaviour**
The data should be uploaded successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/42562517/214195683-67f91e78-47fa-4b6e-857d-2c6e26dacc52.png)

Stderr:
```
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/data_source.py", line 16, in <module>
    from galaxy.datatypes import sniff
ModuleNotFoundError: No module named 'galaxy'
```

**Comment by mvdbeek** [comment]
@natefoo deployment issue, right ?
