### ISSUE TITLE
Workflow Editor Outputs select themselves

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/galaxy#15365]
When selecting a tool with two outputs, the second output is always selected.

**To Reproduce**
1. Create an empty Workflow
2. Add Input Dataset
3. Add Scatterplot with ggplot2
4. In ggplot2, select an additional output format
5. Deselect both outputs
6. Select Input Dataset
7. Select ggplot2
8. Second output is selected

**Expected behavior**
Second output is not selected

**Screenshots**
![image](https://user-images.githubusercontent.com/44241786/214250203-70f6acf4-edd7-4af6-b10f-5621053d202c.png)

**Additional context**

**Comment by hujambo-dunia** [comment]
Confirmed, in addition to `ggplot2` this bug occurs on `liftover` (ie. "Convert genome coordinates") which is available in the local environment and also has 2 output options as stated in this Github issue description.

**Comment by mvdbeek** [comment]
I'll take a look at this now, I hope that's ok @hujambo-dunia
