### ISSUE TITLE
Auto-detecting metadata of unavailable datasets gets stuck in detection state

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#15360]
**Describe the bug**
Auto-detecting metadata for unavailable datasets can get stuck without indicating the underlying issue.
This can be reproduced by selecting a dataset in error state and attempting to auto-detect metadata. The dataset remains forever in `Metadata is being auto-detected.` state, however looking at the server log shows the actual issue, which states: `Pausing Job '...', Input dataset '...' is in error state. To resume this job fix the input dataset(s).`.

**Galaxy Version and/or server at which you observed the bug**
Current dev.

**Expected behavior**
It might be enough to yield higher priority, and properly pass the `paused` state vs the `metadata` detection state. Alternatively setting the `metadata` on failed datasets could either be rejected or fail immediately.

**Comment by dannon** [comment]
xref BackendWG meeting -- if a dataset is in 'error' state, you should not be able to reset metadata.  If it's in 'failed_metadata', you should.

So, two parts:
1) client, don't show reset meta button for an errored dataset
2) Ideally backend endpoint handles this better, blocks request, etc.
