### ISSUE TITLE
Remove "required" indicator from certain tool interface parameters

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15368]
**Describe the bug**

The new "required" or "*" indicators on tool parameters are useful, but used in excess in at least two cases:

1. Selects that are displayed as radio buttons (display="radio") are never optional and there is no way for the user to not select any option
2. Simple non-optional dropdown selects currently behave inconsistently.
    Some do not display the indicator (the correct behavior imo since, again, there's no way for the user to not select anything), others do display it.
    I believe the difference stems from presence/absence of `<when>` blocks: if there's at least one `<when>`, then the indicator is not displayed, otherwise it is.

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org at 23.0

**To Reproduce**
The tool [bcftools norm](https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/bcftools_norm/bcftools_norm/1.15.1+galaxy2) illustrates both cases:

- `When any REF allele does not match the reference genome base *` should not display the asterisk.
- `~multiallelics` is a select with `when` that behaves correctly, while `output_type *` is a select without `<when>`.

**Comment by ElectronicBlueberry** [comment]
This was done intentionally, as there are scenarios when these parameters could be left blank:

For radio buttons: When no default is provided, they remain blank.
For non-optional drop-down fields: If no valid option is present, they will remain blank.

**Comment by wm75** [comment]
@ElectronicBlueberry I don't think that's true. Radio buttons just cannot be blank and don't normally specify a default.
A non-optional drop-down of type="select" (not "data"!) can also not have no valid option.

**Comment by bernt-matthias** [comment]
> For radio buttons: When no default is provided, they remain blank.

At least in tool tests the first option is automatically selected if no option is selected explicitly in the tool XML.

**Comment by ahmedhamidawan** [comment]
@wm75 Discussion here https://github.com/galaxyproject/galaxy/pull/15617#issuecomment-1436575704 suggests that the current behavior makes sense for radio and drop-down elements.

**Comment by jdavcs** [comment]
Can we close this as resolved (as per latest comment)? @ahmedhamidawan @wm75

**Comment by ahmedhamidawan** [comment]
> Can we close this as resolved (as per latest comment)? @ahmedhamidawan @wm75 

As per the discussion on that PR, and in the UI WG meeting that this was discussed in, I would say yes.
