### ISSUE TITLE
Editing extracted Workflow leads to JSON response

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/galaxy#15367]
When attempting to edit an extracted workflow, a JSON response object is shown instead of the workflow editor.

**To Reproduce**
1. Press "Extract Workflow" in the options of a History
2. Press "Create Workflow"
3. Click the "edit" link in "You can edit or run the workflow"
4. JSON response is shown

**Expected behavior**
Workflow editor opens

**Additional context**
Using Firefox 108

**Comment by dannon** [comment]
Fixed in https://github.com/galaxyproject/galaxy/issues/15384
