### ISSUE TITLE
Drag-and-drop datasets in multi-history view activates drag-and-drop upload overlay

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/galaxy#15361]
**Describe the bug**
Testing #14659.

The drag-and-drop upload overlay is triggered when trying to copy items between histories in the side-by-side view. This prevents me from completing the action. In the screenshot below, I'm trying to drop the "mutant" dataset into the history but the event is stolen by the overlay. If you drag fast enough between the histories you can avoid triggering the overlay but it's still bad UX.

This doesn't seem to be an issue on 22.05 (Galaxy AU).

**Expected behaviour**
I should be able to drag and drop a dataset from one history to another.

**Screenshots**
![image](https://user-images.githubusercontent.com/42562517/214183854-b3038028-e34c-4a64-8f02-21ea738ebd45.png)

**Comment by dannon** [comment]
Good catch; definitely a new issue.  Drag on content items could set a bit of state that lets the upload overlay know that it's an 'internal' drag action.

**Comment by neoformit** [comment]
Probably related to this - I can't drag-and-drop at all if the destination is an empty history.

**Comment by ElectronicBlueberry** [comment]
> set a bit of state that lets the upload overlay know that it's an 'internal' drag action.

Something similar is present for exactly this case. It may have been broken in #15330, or something else changed which prevents the event from reaching the composable handler.

**Comment by jdavcs** [comment]
> Probably related to this - I can't drag-and-drop at all if the destination is an empty history.

This works: as per your suggestion, just move it fast enough.
