### ISSUE TITLE
New Workflow Form warns about lost changes

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/galaxy#15366]
When creating a new workflow, a confusing popup is shown, warning you of potential lost changes.

**To Reproduce**
* Edit a workflow and change something
* Switch to the workflow overview without saving
* create a new workflow

**Expected behavior**
The workflow editor opens without warning message

**Screenshots**
![image](https://user-images.githubusercontent.com/44241786/214250708-9ae04fb9-eeb7-4194-a23c-94a395b4f4b4.png)

**Additional context**

**Comment by dannon** [comment]
I think I ran into this, too -- IIRC it happens when you edit a workflow, then back out, and try to create a new one?  Or is this just a clean session creating a workflow without ever having been in the editor before?

**Comment by ElectronicBlueberry** [comment]
You're right, it seems to not happen in a clean session.

**Comment by dannon** [comment]
I'm glad you hit this too, because after reporting it to Marius directly I couldnt' figure out what I did!  :)

**Comment by mvdbeek** [comment]
I saw that too, but it doesn't really seem to happen consistently.

**Comment by ElectronicBlueberry** [comment]
Figured out how to recreate it:

* Edit a workflow and change something
* Switch to the workflow overview without saving
* create a new workflow

**Comment by mvdbeek** [comment]
Ah, nice, that worked for me too.
