### ISSUE TITLE
History gets stuck in scroll up/down

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#15364]
That's on usegalaxy.org 23.0.
What I did was open a big history, click on show hidden, and give the magic mouse a good scroll down movement.
That only happens if the data is not in cached yet, but you can't really get out of it.

I captured this without any touch or focus on the history, apart from the initial scroll that is long over:

![history scroll bug](https://user-images.githubusercontent.com/6804901/214249642-bdec80b3-5aea-44a6-a58a-dc7180ea2947.gif)

**Comment by dannon** [comment]
Potentially related to scrolling issues in https://github.com/galaxyproject/galaxy/issues/14767?

**Comment by mvdbeek** [comment]
I think we can concluded this is a different manifestation of https://github.com/galaxyproject/galaxy/issues/14767
