### ISSUE TITLE
WF editor displays error when conditional input gets removed from step

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15374]
**Describe the bug**
When an input feeds into a conditional param (contained in a `<when>` clause of a conditional) and that condtional gets reconfigured in the editor to not use that input anymore, the below error is displayed on the WF step box.

**Galaxy Version and/or server at which you observed the bug**
usegalaxy,org at 23.0

**Expected behavior**
While technically correct and addressable by removing the connected input manually, the error message is really ugly and hard to understand for users.
The old behavior was to disconnect the input without warning, which you could argue was also suboptimal cause when you changed the parameter accidentally it was sometimes hard to remember to reconnect the input so maybe a compromise is needed here though I'm not sure what that would look like.

**Screenshots**
![image](https://user-images.githubusercontent.com/4742081/214262678-307d5ac6-d783-4f80-a472-f88f3f32ce28.png)

**Comment by mvdbeek** [comment]
That's intentional. Did you see the tooltip that says why it is so ?

**Comment by wm75** [comment]
The "Cannot attach to invalid input"? I missed that initially.
My two main concerns though are:
1. both the highlighted error text/param ID and the tool tip are quite technical, and not communicating a solution (to disconnect the input, which is no longer expected) to the user, so the whole thing is not very beginner-friendly
2. This weird status - WF step input for a parameter that is not occurring in the tool state - is written to the WF file.
     Is that a safe thing to do? Or will it cause trouble of some sort (backwards compatibility issues, planemo or gxformat2 issues)?

As said before though, I think the new behavior makes more sense, then the old silent disconnect. Just trying to figure out if it still needs some extra polish.

**Comment by mvdbeek** [comment]
> 2\. This weird status - WF step input for a parameter that is not occurring in the tool state - is written to the WF file.
>     Is that a safe thing to do?

That's exactly what happens with tool upgrades that remove a connected input. It's not ideal, but we can deal with it.

**Comment by assuntad23** [comment]
closed with #15406 to help guide users to expected behavior.  
Future work ^ mentioned by @mvdbeek will help prevent invalid workflows.
