### ISSUE TITLE
Navigating back from a Tool Submisson Page does not navigate to Tool

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/galaxy#15376]
Previously fixed in #14725

**To Reproduce**
See #14515

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/issues/15078

**Comment by ahmedhamidawan** [comment]
Notes:
- In code you don't leave the `ToolForm`

**Comment by mvdbeek** [comment]
Should be backported to 23.0
