### ISSUE TITLE
WF editor mouse-wheel/touchpad zooming too coarse

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15370]
**Describe the bug**
When trying to zoom in or out of the WF display in the WF editor using the mouse wheel or the touchpad (instead of using the dedicated UI buttons), it's almost all or nothing.

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org at 23.0

**Comment by mvdbeek** [comment]
@dannon had the same issue, but it works great on my mouse and touchpad, while on 22.05 i have to scroll like crazy ... I guess there's probably some way to read out the sensitivity ?

**Comment by davelopez** [comment]
Fixed on #15399, thank you @ElectronicBlueberry!
