### ISSUE TITLE
Can not find a tool with its full name

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#15382]
Tools can not be found with the full name but without the first word.
It does not occur on v22.05

**To Reproduce**
1. Click on `search tools` input on the `Tools` panel
2. Search for a tool with the full name; e.g. `Select lines that match an expression`
3. Only works with `lines that match an expression`

**Expected behavior**
Finding a tool by its full name

**Comment by tcollins2011** [comment]
It looks like the search will work if you use the full name in the advanced tool search.

**Comment by tcollins2011** [comment]
@ahmedhamidawan Do you this we should change the Whoosh index on the backend as well?

**Comment by ahmedhamidawan** [comment]
@tcollins2011 I reckon the whoosh index works fine with the `name+description` combination search. We could take a look at it and see if the indexing is behaving weird in the Whoosh return

**Comment by dannon** [comment]
> @tcollins2011 @hexylena
> 
> Yes the advanced search utilizes a `name+description` search, however, the client side does not do it, which I can now add

I think you're right -- just concatenating these together as displayed for what gets indexed should resolve this.

**Comment by jdavcs** [comment]
Fixed in #15434
