### ISSUE TITLE
Download collection broken fails with "file incomplete"

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/galaxy#15390]
**Describe the bug**
I tried to download a small list collection, and the download immediately errors with `Failed - file incomplete`.

**To Reproduce**
Try to download a list collection on Galaxy 23.0

**Comment by davelopez** [comment]
Might be a deployment issue? It works on a local Galaxy.

**Comment by mvdbeek** [comment]
Yep, definitely. I think nginx-mod-zip is at fault here.

**Comment by natefoo** [comment]
Did this just break after the upgrade? I haven't changed the nginx config for this in quite some time.

**Comment by davelopez** [comment]
Anything I can do to help here? or can someone with access to usegalaxy.org logs and config have a closer look? Please feel free to reassign the issue.

**Comment by mvdbeek** [comment]
I don't think this is related to the new release, no. I can't tell for how long it's been broken though.

**Comment by mvdbeek** [comment]
We may give mod-zip another try, any chance @jmchilton or @neoformit could dig out a nice test case ?

**Comment by mvdbeek** [comment]
(since it didn't happen with every collection)

**Comment by neoformit** [comment]
I just failed to recreate this on usegalaxy.org with the same history I reported this against back in release testing. Looks like it works fine now?

**Comment by jdavcs** [comment]
Closing this since it can't be reproduced. Feel free to reopen if this resurfaces.
