### ISSUE TITLE
Convert collection datatype not shown

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/galaxy#15395]
**Describe the bug**
Testing #14646.

I've created a collection with `txt`, `tabular` and `csv` datatypes (two items) and can't access the "convert datatype" feature on the collection.

- The collection is described as "a list with 2 datasets", instead of "a list with 2 `txt` datasets" as Assunta's PR suggests
- When I open "Edit attributes" on the collection I see "Database/build" and "Convert" tabs but not "Datatypes"

**Galaxy Version and/or server at which you observed the bug**
23.0

**To Reproduce**
1. Create a collection of a single datatype e.g. `tabular`
2. Click on pencil icon (edit attributes)
3. Confirm observations above

**Expected behaviour**
I should be able to see a "Datasets" tab where I can convert the datatype of all datasets in the collection.

**Screenshots**
![image](https://user-images.githubusercontent.com/42562517/214460008-dd8dab53-c499-4902-bc92-44a8ef56ce4e.png)

**Comment by assuntad23** [comment]
@neoformit are you testing on main? or locally? Is Celery enabled on main? 
If Celery is not enabled, this will not work. 
afaik, Celery wasn't enabled on main.

**Comment by neoformit** [comment]
Oh yes this is on main - sorry I assumed Celery would be on there. I'll test locally and close if it looks all G.

**Comment by neoformit** [comment]
Ok I still can't get it to work locally, but I don't know if I've enabled celery properly. I set `celery.enable = true` in `galaxy.yml` and ran the internal/external queues but the option is still not presented in the UI.

**Comment by neoformit** [comment]
I set `enable_celery_tasks: true` and it works when run locally with `run.sh` :rocket:
