### ISSUE TITLE
Anonymous users can "try" to create new histories and switch between them

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#15401]
**Describe the bug**
Anonymous users can have only one history, but the UI let them try to create and switch between histories.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0
Commit: 995164d41c6bcd2c072328f1ebeee6169b387c64

**To Reproduce**
1. Log out of Galaxy
2. Create a new history from the UI
3. Try to switch between histories
4. :boom: 

**Expected behavior**
Switching between histories is disabled and clearly indicates that you need to log in before doing it.

**Comment by davelopez** [comment]
I guess creating a new history is fine, since it will replace the existing one, but switching between them is what needs to be disabled.

**Comment by nsoranzo** [comment]
> I guess creating a new history is fine

What happens to the previous history? Is it deleted and purged?
Apart from the new row in the database, I fear this risks leaving data around forever.

**Comment by davelopez** [comment]
Yeah, I just checked, and apparently, there is nothing preventing an anonymous user to create a new history in the UI because there are no restrictions in:

https://github.com/galaxyproject/galaxy/blob/995164d41c6bcd2c072328f1ebeee6169b387c64/lib/galaxy/webapps/galaxy/controllers/history.py#L772

But there are when using the API:

https://github.com/galaxyproject/galaxy/blob/995164d41c6bcd2c072328f1ebeee6169b387c64/lib/galaxy/webapps/galaxy/services/histories.py#L205

And no direct deletion or purging of the previous history is done right after. However, I assume they will be eventually purged because of:

https://github.com/galaxyproject/galaxy/blob/995164d41c6bcd2c072328f1ebeee6169b387c64/scripts/cleanup_datasets/cleanup_datasets.py#L218

Should I disable the create history button too then?

**Comment by dannon** [comment]
Historically we allowed anonymous users to switch to a new history for a quick clean slate, and the old one was cleaned up later as you note, with no way back to it.  You definitely should not be able to utilize multiple anonymously.

That said, I think it would be an improvement to simply disable the actions to create, and hide the option to switch, and warn the user "To use multiple histories, you must have a registered account" or the standard verbiage.
