### ISSUE TITLE
Collection element are not updated in collection view

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#15414]
**Describe the bug**
Related #14129. In the history panel, when opening a collection, all collection elements will keep their latest state from when the collection opened until go back to history and reopen the collection view or refresh the page.

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org (v23.0.rc1)

**Expected behavior**
Collection elements store watch for new changes to update states.

**Comment by wm75** [comment]
Yes, rather annoying but not new.
