### ISSUE TITLE
Inconsistent note/behavior on collections edit page

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15416]
**Describe the bug**
The collections edit page displays this note unconditionally at the top:

![image](https://user-images.githubusercontent.com/4742081/214853353-7a066156-34bd-44e6-a5aa-2cdb156f376f.png)

but this and the actual behavior of different edits is confusing me for several reasons:

- Bulk datatype changes added in #14646 are shown in the video at least (the tab is currently not available on .org) to update the collection in place.

- Bulk updates to the Database/Build *do* create a new collection, but I don't understand why that would be desired.

- Bulk conversions need to create a new collection, but I don't see how that can work without counting towards a user's quota.

**Expected behavior**
1. An appropriate note should be displayed depending on the actually selected tab.
2. Bulk database/build updates should work in place.

**Comment by mvdbeek** [comment]
> * Bulk updates to the Database/Build _do_ create a new collection, but I don't understand why that would be desired.

Collections are supposed to be immutable, but we've lost that fight when we merged the bulk change.

> * Bulk conversions need to create a new collection, but I don't see how that can work without counting towards a user's quota.

Same way as all the database operation tools, they don't create a new dataset.

**Comment by mvdbeek** [comment]
Sorry, conversions do consume consume space, if the message is shown there that isn't correct

**Comment by assuntad23** [comment]
The message does change to drop the phrase "Your quota will not increase." Can you take another look @wm75 ?

> Sorry, conversions do consume consume space, if the message is shown there that isn't correct

**Comment by assuntad23** [comment]
UPDATE: I can see this being a problem when celery is enabled and the 3rd tab is available.
I'm going to clear this up a bit. Thanks @wm75

**Comment by wm75** [comment]
Thanks @assuntad23 ! You're correct that the message changes when you switch over to convert. Don't know how I missed that, sorry, and thanks for looking into the other case.

**Comment by assuntad23** [comment]
closed with #15431
