### ISSUE TITLE
WF editor thinks it cannot attach an integer parameter to an integer input

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15417]
**Describe the bug**

![Screenshot from 2023-01-26 15-21-50](https://user-images.githubusercontent.com/4742081/214860085-cbfc0126-78c5-413f-96b8-d0e2842f9a16.png)

Note how the step inputs are displayed in green, but how the tooltip disagrees. The result is that it's not possible to connect the boxes.

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org at 23.0rc1

**Comment by mvdbeek** [comment]
Interestingly I can connect, but I also see the nonsense tooltip.

**Comment by wm75** [comment]
Kind of bizarre, but whether you can or cannot connect seems browser dependent. Works in FF, but not Chromium.

**Comment by wm75** [comment]
Oh, and that's because you can't connect *anything* in chromium. This thing was just the first thing I tried in that browser.

**Comment by wm75** [comment]
Works now as expected. Thanks @mvdbeek.
The additional chromium issue turned out to be a bug with my installed version of the browser and can be ignored here.
