### ISSUE TITLE
Datasets purged or in error can be copied in datasets list

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#15412]
**Describe the bug**
While fixing #15397 I noticed that we can copy a dataset purged or in error. It feels like a bad idea to allow that. Or is there a use case for that?

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0
Commit: 995164d41c6bcd2c072328f1ebeee6169b387c64

**To Reproduce**
1. Go to https://usegalaxy.org/datasets/list
3. Click on a Dataset name that is in error or purged
4. Select Copy to history

**Expected behavior**
The `Copy` option does not show in those cases

**Comment by nsoranzo** [comment]
Copying the purged/errored dataset (i.e. its metadata) to a new history can still be useful, I think, since than you can re-run it and re-generate the underlying data / fix a transient error without filling the tool form from scratch.

**Comment by davelopez** [comment]
Oh, I see, good to know there is a use case. I'll close it then :+1:
