### ISSUE TITLE
New tab for changing collection element datatypes in bulk is missing

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15415]
**Describe the bug**
#14646 is supposed to have added a tab to the collection edit page for changing collection element datatypes in bulk, which is also mentioned in the release notes.
However that tab is simply missing.

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org at 23.0.rc1

**To Reproduce**
Click the edit button on any collection.

**Comment by mvdbeek** [comment]
> I created a tab to edit the datatype of all elements in a collection, celery tasks must be enabled to see the tab

and those are not enabled on main.

**Comment by wm75** [comment]
Then this should be mentioned in the release notes?

**Comment by nsoranzo** [comment]
I'm worried about the confusion generated by Celery-only UI features, I've added a discussion point to the next Backend WG agenda.

**Comment by assuntad23** [comment]
maybe they need to be listed as a sub category in the release notes, so that folks know that they only get them if they enable Celery

**Comment by mvdbeek** [comment]
> I'm worried about the confusion generated by Celery-only UI features, I've added a discussion point to the next Backend WG agenda.

No per-user rate-limiting = not ready for production IMO. 
- We can mark it as beta in the interface and say it may not be available on all instances.
- We can show "disabled on this Galaxy server" if it's not enabled.
- We can remove the UI generally if this is a huge concern, but we have other features that depend on the instance and instance version (remote file sources, visible tool sources, visible command lines etc).

**Comment by mvdbeek** [comment]
We have user-rate limiting now, so I think there's no reason not to run celery services anymore.

**Comment by davelopez** [comment]
It is present now:

![image](https://github.com/galaxyproject/galaxy/assets/46503462/2ddaadbe-b1a3-468e-bb0d-05ac34ee1728)

Should we close this and open a new issue regarding how to handle/notify users of conditional features?
