### ISSUE TITLE
Workflow editor Configure Output fields not update

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#15411]
**Describe the bug**
In the workflow editor, the `Configure Output` fields (`Rename dataset`, `Change datatype`, `Add Tags`, `Remove Tags` and all `Assign columns` fields) are not updating by clicking on different steps and show data from the first selected step.

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org (v23.0.rc1)

**To Reproduce**
1. Open a workflow in the workflow editor with at least two steps
2. Click on a step and change the above-mentioned `Configure Output` fields
3. Click on another step
4. The last selected step has the same `Configure Output` as the last one

**Expected behavior**
Show the configuration of each step correctly

**Screenshots**
[Screencast from 26.01.2023 11:58:11.webm](https://user-images.githubusercontent.com/8046843/214820259-86bfd441-38b2-424a-b2da-4d63ebfe91fe.webm)

**Comment by mvdbeek** [comment]
If you run 23.0 locally, can you still reroduce this @itisAliRH ?

**Comment by itisAliRH** [comment]
@mvdbeek Not anymore, it seems to be fixed on local and usegalaxy.org
