### ISSUE TITLE
Toolbox needs to break all words to avoid horizontal scroll

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#15429]
**Describe the bug**
Some tools have long names without spaces, these names are not properly broken down and can lead to the appearance of a horizontal scroller in the tool box.

<img width="304" alt="image" src="https://user-images.githubusercontent.com/2105447/215101054-65934eea-0324-4b20-add5-2afed91cc5e0.png">

**Comment by martenson** [comment]
I took the liberty to address this since I was dealing with the same issue in workflow box.
