### ISSUE TITLE
Workflow run input selection not synced with history changes

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#15427]
**Describe the bug**
In the workflow run, to selecting a new history item added should refresh the page. Deleted items can also be selected after deleting.

https://user-images.githubusercontent.com/8046843/215073209-0c316594-a181-43cb-808d-b71dcd7c337b.mp4

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org (v23.0.rc1)

**To Reproduce**
1. Go to the workflow list
2. Run a workflow that needs to select an input
3. Upload data or create a dataset list or delete an item
5. The workflow select input is not getting the newly added/deleted items to the history

**Expected behavior**
Items in the history and workflow data selection must be in sync

**Comment by ahmedhamidawan** [comment]
Closed with #15565
