### ISSUE TITLE
History dropdown is rather small

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#15444]
I know gear wasn't ever the right semantic icon given that most other UIs use a hamburger or a kebab menu icon, but is there a good reason to remove the gear? It was a very familiar button that's familiar to generations of galaxy users.

If there is a good reason, perhaps we could swap to something with a bit higher ink:blank ratio? The triangle is quite small

![image](https://user-images.githubusercontent.com/458683/215473030-b54191e9-e70c-4188-b37e-e8fb950c0acc.png)

**Comment by ElectronicBlueberry** [comment]
I think the reason is this is the default [Bootstrap Vue dropdown look](https://bootstrap-vue.org/docs/components/dropdown). It is indeed very small, even smaller than the font awesome caret down icon. We ought to wrap this component with a more visible default look. It's an issue in other parts of the UI as well, eg. the tool panel.

**Comment by dannon** [comment]
We used to use https://fontawesome.com/v4/icon/cog for this menu but moved away from it as it's a bit less modern and has an implied 'settings' connotation for many.

I might lean towards kebab?  Or, maybe just significantly scale up the caret?  Either of those seem appropriate, the caret is just undersized right now.

**Comment by hexylena** [comment]
Understood @ implied settings connotation.

That all sounds good, thanks y'all :)

**Comment by hexylena** [comment]
Just coming back here to complain about it again :)

it's still so so so tiny
![image](https://github.com/galaxyproject/galaxy/assets/458683/6186abdf-49cc-4812-8a5e-afbac2f901e5)

I don't care which icon is used, but it really should match the amount of 'ink' that's used for the other icons, it's really hard to see on default zoom level for me, especially for such an important icon. Can we please make this one, single, icon bigger? Just for this one case nowhere else in the UI? Or as @dannon suggests changing it.

```css
.dropdown-toggle::after {
  border-left: .6em solid #0000;
  border-right: .6em solid #0000;
  border-top: .8em solid;
}
```

would be good, now I can see there's a button.

![image](https://github.com/galaxyproject/galaxy/assets/458683/0c9cae76-1772-4fd8-959d-d61bb7c4d473)

**Comment by davelopez** [comment]
What about the hamburger menu ☰? or is it too 80's? :stuck_out_tongue_winking_eye:

**Comment by hexylena** [comment]
Hamburger and kebab are both great options. Hamburger has comparatively high ink (a bonus!) and it's what firefox uses, I'm a fan :)

**Comment by hexylena** [comment]
Fixed by https://github.com/galaxyproject/galaxy/pull/17791

(not sure why 'fixes' isn't working)

Thanks y'all, @dannon, I'm so happy to have this fixed.

**Comment by davelopez** [comment]
> not sure why 'fixes' isn't working

https://github.com/galaxyproject/galaxy/pull/17791 needs to be merged forward to `dev` for that to work I think
