### ISSUE TITLE
tool panel sorting should not touch order of WFs in the WF tool panel

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15454]
**Describe the bug**
In the WF version of the tool panel you can expand the Workflows section at the bottom to reveal your WFs and embed them into your current WF.
The new alphabetical tool panel sorting currently extends to this section, but this behavior is not desirable and the old last changed WF first order is much more useful.

**Expected behavior**
Do not apply sorting to the Workflows section of the tool panel

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/15455
