### ISSUE TITLE
password reset links do not work on usegalaxy.org

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#15451]
reported at https://help.galaxyproject.org/t/cannot-reset-password/9373 for usegalaxy.org

**To Reproduce**
1. Go to login
2. Request password reset link
3. Visit the link you received in your mail
4. End up in login page instead

**Expected behavior**
You want to end up on a page to reset password.

**Comment by dannon** [comment]
Fixed in #15453.  Thanks @martenson!
