### ISSUE TITLE
WF editor - Incorrect warning about duplicate labels

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15456]
**Describe the bug**

The WF editor warns about duplicate labels being ignored even if there are no duplicates.
![image](https://user-images.githubusercontent.com/4742081/215771143-6f165aed-ba9d-48f7-87c5-5f590fe82c5f.png)

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.org at 23.0.rc1

**To Reproduce**
1. Create a new WF and add a single tool to it
2. Add a label to any output of the tool
3. Navigate away from the tool interface (e.g. switch to edit attributes of the WF)
4. Navigate back to the WF step and expand the Configure output section again
5. The warning shown in the screenshot above is displayed

**Comment by davelopez** [comment]
If nobody is actively working on this I can try to fix it.
