### ISSUE TITLE
Unhelpful error message when loading workflow

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1546]
This is half-bug report, half-debugging help request.

When loading a particular workflow, I'm faced with the following:

![selection_552](https://cloud.githubusercontent.com/assets/458683/12458929/cf37f4f0-bf71-11e5-8b29-998695c40bc7.png)

Whatever is causing that, is the bug I wish to fix.

Those objects are actually empty

![selection_553](https://cloud.githubusercontent.com/assets/458683/12458941/d870130e-bf71-11e5-964a-c0ef90baed32.png)

The keys however indicate two `<sections />` in my tool:

![selection_554](https://cloud.githubusercontent.com/assets/458683/12458961/eb678fc8-bf71-11e5-8838-934e46b2cc9a.png)

which can be seen in the XML here:
- [config File](https://github.com/galaxyproject/tools-iuc/blob/master/tools/jbrowse/jbrowse.xml#L85)
-  [jbstyle macro](https://github.com/galaxyproject/tools-iuc/blob/master/tools/jbrowse/macros.xml#L201)
- [jbcolor_scale](https://github.com/galaxyproject/tools-iuc/blob/master/tools/jbrowse/macros.xml#L139)

The MWE is a workflow with a single step, JBrowse, a single track group, and a single track. No parameters other than the defaults. <s>Testing out #1545 now</s> doesn't help. I'm on 1b8f5280743526ac420280557067460d40362da5

@guerler any suggestions for debugging?

**Comment by hexylena** [comment]
(Bisecting now) As of 6a47d2d3a7f27b659e5de5fb1b37c7c1f9d04302 the error messages were more helpful:

![selection_555](https://cloud.githubusercontent.com/assets/458683/12460078/917ef4e6-bf77-11e5-8c29-36fe9652e220.png)

**Comment by guerler** [comment]
This might be related to: https://github.com/galaxyproject/galaxy/commit/6c9a82e142c5bf70ae4612f094b8d0c89e3fd2f3#diff-1bef786a2b2ea704c1748e41cd25dd33R2050

**Comment by guerler** [comment]
The message has probably changed with https://github.com/galaxyproject/galaxy/commit/6c9a82e142c5bf70ae4612f094b8d0c89e3fd2f3 which is a fix for the missing parameter name above. However, it seems that the upgrade messages are not properly decoded when displayed.

**Comment by hexylena** [comment]
Appears to be related to `<section />`s

**Comment by hexylena** [comment]
MWE:

``` xml
<tool id="jbx" name="1546-MWE" version="0.1">
  <command><![CDATA[
date > $output
]]></command>
  <inputs>
    <section name="a" title="Test Section" expanded="true">
        <param name="b" type="text" label="asdf" value="feature" />
    </section>
  </inputs>
  <outputs>
      <data format="txt" name="output" />
  </outputs>
</tool>                                                                                                                                  
```

**Comment by hexylena** [comment]
When trying to RUN the workflow I see the following:

```
galaxy.workflow.run ERROR 2016-01-20 15:23:16,655 Failed to schedule Workflow[id=15,name=asdf], problem occurred on WorkflowStep[index=0,type=tool].
Traceback (most recent call last):
  File "/home/hxr/work/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke
    jobs = self._invoke_step( step )
  File "/home/hxr/work/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/home/hxr/work/galaxy/lib/galaxy/workflow/modules.py", line 1188, in execute
    raise Exception(message)
Exception: Failed to create 1 out of 1 job(s) for workflow step.
galaxy.workflow.run ERROR 2016-01-20 15:23:16,656 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/home/hxr/work/galaxy/lib/galaxy/workflow/run.py", line 82, in __invoke
    outputs = invoker.invoke()
  File "/home/hxr/work/galaxy/lib/galaxy/workflow/run.py", line 162, in invoke
    jobs = self._invoke_step( step )
  File "/home/hxr/work/galaxy/lib/galaxy/workflow/run.py", line 228, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/home/hxr/work/galaxy/lib/galaxy/workflow/modules.py", line 1188, in execute
    raise Exception(message)
Exception: Failed to create 1 out of 1 job(s) for workflow step.
127.0.0.1 - - [20/Jan/2016:15:23:16 -0500] "POST /galaxy/workflow/run?id=f2db41e1fa331b3e HTTP/1.1" 500 - "http://localhost:8001/galaxy/workflow/run?id=f2db41e1fa331b3e" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
Error - <type 'exceptions.Exception'>: Failed to create 1 out of 1 job(s) for workflow step.
URL: http://localhost:8001/galaxy/workflow/run?id=f2db41e1fa331b3e
File '/home/hxr/work/galaxy/lib/galaxy/web/framework/middleware/error.py', line 151 in __call__
  app_iter = self.application(environ, sr_checker)
File '/home/hxr/work/galaxy/.venv/local/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/home/hxr/work/galaxy/.venv/local/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/home/hxr/work/galaxy/lib/galaxy/web/framework/base.py', line 126 in __call__
  return self.handle_request( environ, start_response )
File '/home/hxr/work/galaxy/lib/galaxy/web/framework/base.py', line 184 in handle_request
  body = method( trans, **kwargs )
File '/home/hxr/work/galaxy/lib/galaxy/webapps/galaxy/controllers/workflow.py', line 1131 in run
  workflow_run_config=run_config
File '/home/hxr/work/galaxy/lib/galaxy/workflow/run.py', line 22 in invoke
  return __invoke( trans, workflow, workflow_run_config, workflow_invocation, populate_state )
File '/home/hxr/work/galaxy/lib/galaxy/workflow/run.py', line 82 in __invoke
  outputs = invoker.invoke()
File '/home/hxr/work/galaxy/lib/galaxy/workflow/run.py', line 162 in invoke
  jobs = self._invoke_step( step )
File '/home/hxr/work/galaxy/lib/galaxy/workflow/run.py', line 228 in _invoke_step
  jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
File '/home/hxr/work/galaxy/lib/galaxy/workflow/modules.py', line 1188 in execute
  raise Exception(message)
Exception: Failed to create 1 out of 1 job(s) for workflow step.
```

**Comment by hexylena** [comment]
The failure is silent on my production instance I believe because I'm using the beta_workflow_steps or whatever it is called.

**Comment by guerler** [comment]
One part is very likely a displaying issue, the other issue might be related to limited support of the current/classic run workflow form for sections.

**Comment by hexylena** [comment]
f8a7ac082036995573f849b12f64f6d4fbfb8b6b seems to be the first bad commit when trying to run workflow with sections
