### ISSUE TITLE
New history: how to find deleted histories and undelete them?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#15471]
I can do it via the old way (user→histories, please please please never delete this route.), but I cannot figure out how to see deleted histories on test.galaxyproject.org

Trying to write this bug I did:

- View multiple, add my histories
- Use switch to there, and delete one.
- Surprised it doesn't disappear from main panel multi-history view, I refresh
- There is now a blank column (image 1)
- I try and get the history back (image 2) but it is not there, and there is no "advanced" filter to include deleted histories or filtering on published status
- I revert to the ancient method which still works (image 3)

### Image 1

![image](https://user-images.githubusercontent.com/458683/216016986-6426300d-a37a-48f7-baf5-9228c3fc5f58.png)

### Image 2

![image](https://user-images.githubusercontent.com/458683/216017108-d930b202-b139-4a65-a076-5c164149b311.png)

### Image 3

![image](https://user-images.githubusercontent.com/458683/216017579-58427714-015f-49db-a8e5-ddbbd7468f48.png)

**Comment by davelopez** [comment]
The blank column in the multi-history view definitely looks like a bug! thanks for finding it :+1: 

IMO, I think the `Switch to history` should not be used to display deleted histories it is just a quick switch between your active histories. The quick switch is by no means a replacement for the full-featured User->Histories and I think is the correct place to go for managing your deleted histories, etc.

But this opens the question of whether the multi-history view should be able to display deleted histories or not :thinking:

**Comment by dannon** [comment]
Discussed again in UI/UX briefly this week.  We don't see the multi-history as the right avenue for finding and deleting histories, and expect that functionality to stay with the standard grid/list views whereas the multi-history view is primarily for examining and interacting with the *contents* of multiple active histories.

**Comment by hexylena** [comment]
>  We don't see the multi-history as the right avenue for finding and deleting histories

I guess this wasn't about deleting, but rather, switching to a deleted history (and potentially pulling a dataset out of it into an active history, or maybe undeleting it ) but, if that's what you meant, ok, good to know.
