### ISSUE TITLE
fs.dropboxfs is not pinned

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#15489]
**Describe the bug**
Upon a fresh installation of the galaxy virtual environment, galaxy is broken due to this error:
`Exception: FilesSource plugin is missing required Python PyFilesystem2 plugin package [fs.dropboxfs]`

This isn't pinned and the latest version was installed (1.0.1) in which the way DropboxFS is imported has changed. We fixed it by pip installing an older version, 0.2.2.post2.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: release_22.05
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Comment by nsoranzo** [comment]
Should we try to move to the latest release before pinning (on 23.0/dev)?
