### ISSUE TITLE
Tool Search result tools showing in multiple categories 

### ISSUE THREAD

**Issue by tcollins2011** [galaxyproject/galaxy#15480]
**Describe the bug**

While using the EDAM topics view and  searching for tools in the Galaxy tool search there is a chance that the same tool can be shown in multiple categories including uncategorized.

**Galaxy Version and/or server at which you observed the bug**

Galaxy Version: 23.0

**To Reproduce**

1. Switch tool search view to EDAM Topics
2. Go to the tool search bar
3. Search for 'rna star'
4. Look at the results tab and see the same two tools appearing in three different categories

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/62220253/216125118-27529619-6761-4c2d-af8c-41f8cd814d44.png)

**Additional context**

**Comment by ahmedhamidawan** [comment]
Thanks for reporting this! Yes, we shouldn't see more than one instance of a tool in the general _(no-section)_ view of the panel. I'll fix that. 
Other than that, the tool would still show up in multiple sections if the _Show Sections_ view is enabled

**Comment by tcollins2011** [comment]
It would probably be helpful to remove tools from the uncategorized section when sections are shown if they are present in another category as well.

**Comment by tcollins2011** [comment]
After looking at this with Ahmed it seems like the Uncategorized results lead back to 2.7.5B of RNA STAR where as the the results falling under the other EDAM topics lead to the current 2.7.8a+galaxy1.

**Comment by ahmedhamidawan** [comment]
Closing this since the same exact tool (same id) does not show up twice now (some tools have the same name+description but they are different tools due to having different ids)
