### ISSUE TITLE
Builtin sort tool shown twice

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#15499]
**Describe the bug**

On usegalaxy.org and eu the builtin sort tool is shown twice in the tool menu once in `text manipulation` and once in `filter and sort` one is for version 1.2 and the other 1.1 

![Screenshot from 2023-02-03 13-36-07](https://user-images.githubusercontent.com/25689525/216604869-9ff6e431-8a19-4f0d-b913-4daa73abfe29.png)

it should be shown only once

**Comment by ahmedhamidawan** [comment]
This is reported in https://github.com/galaxyproject/galaxy/issues/15480, setting up a fix for this for 23.0

**Comment by bernt-matthias** [comment]
Good to know. But I think this is a but different here, because there old version of the `sort` tool should not be available at all

https://github.com/galaxyproject/galaxy/blob/9d4bad7b33d0b6cf66e202f497c272a81088086c/lib/galaxy/config/sample/tool_conf.xml.sample#L83 ... for the grep tool I might have expected it, but not for the sort tool.

Except if the usegalaxy servers use a special tool conf where the old version has been restored.

**Comment by ahmedhamidawan** [comment]
@bernt-matthias Ohh I see, my bad, you're right. Will be fixed so that only the latest version shows

**Comment by ahmedhamidawan** [comment]
This actually seems to be the case that we have two `different` tools with the same name but different ids, `Sort1` being local and `tp_sort_header_tool` being from a toolshed/repo

**Comment by bernt-matthias** [comment]
I see .. Then we may close this issue.

https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_sort_header_tool/1.1.1
https://usegalaxy.org/root?tool_id=sort1

**Comment by bernt-matthias** [comment]
Thanks for checking @ahmedhamidawan
