### ISSUE TITLE
Output collection given unexpected name when converting datatype

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#15495]
**Describe the bug**
When changing the datatype for a collection, the output collection is not named after the converter. The element datasets are named correctly after the converter.

**Galaxy Version and/or server at which you observed the bug**
Galaxy version 23.0.rc1, commit [fdbe92986e8dd998831b3ccf11e89e8e9b1dc38d](https://github.com/galaxyproject/galaxy/commit/fdbe92986e8dd998831b3ccf11e89e8e9b1dc38d)

**To Reproduce**
1. Go to a collection of uncompressed fastqsanger reads
2. Click on the pencil icon
3. Click into Convert tab
4. Choose the first option (fastqsanger -> fastqsanger.gz)
5. Can also do the reverse on output from 4. 

**Expected behavior**
Original collection name preserved, with the conversion method added to the end (?)

**Screenshots**
<img width="1051" alt="Screen Shot 2023-02-02 at 12 16 53 PM" src="https://user-images.githubusercontent.com/8999735/216443939-d5012925-115b-4dbe-8742-f98110148a0f.png">

<img width="284" alt="Screen Shot 2023-02-02 at 12 33 53 PM" src="https://user-images.githubusercontent.com/8999735/216443964-c9ee05bd-4ec9-4e63-b41a-acb43f763c7f.png">

**Additional context**
This is a small history that can be used for testing https://usegalaxy.org/u/jen/h/test-listpaired-convert-dataype

I'm not sure what "area" this would be in

**Comment by jennaj** [comment]
Update: When extracting a workflow that contains datatype conversions, the wrong converter is picked -- both in the display name _and_ in the workflow itself (this surprised me). That conversion used `fastqsanger-to-fastqsangergz`, and it is at EU running 22.05. Seems related to what we discussed as a maybe-root issue for the odd output collection naming above -- eg picking the first converter in a list vs the actual converter applied. 

@mvdbeek --if needs a different ticket, please lmk, maybe I misunderstood what was explained. Thanks!

https://usegalaxy.eu/u/jenj/h/test-unicycler-fastqsangergz
https://usegalaxy.eu/u/jenj/w/workflow-constructed-from-history-test-unicycler-fastqsangergz


<img width="1439" alt="Screen Shot 2023-02-07 at 11 56 49 AM" src="https://user-images.githubusercontent.com/8999735/217353205-8c07bd14-851f-4109-84d6-9cd1428283f0.png">

**Comment by mvdbeek** [comment]
Thanks @jennaj, fixed in https://github.com/galaxyproject/galaxy/pull/15579
