### ISSUE TITLE
`Histories shared with me` does not render anything

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#15519]
**Describe the bug**

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0
Commit: [15ffadeae9988830f891c637a57b65a7ec48c2af](https://github.com/galaxyproject/galaxy/commit/15ffadeae9988830f891c637a57b65a7ec48c2af)

**To Reproduce**
1. Log in to Galaxy.
2. Go to `Histories shared with me`.
3. Only the masthead is rendered.

**Expected behavior**
The list of histories shared with the user is rendered.

**Additional context**
No visible errors in the browser console.

Reported by a user in the Lobby chat

**Comment by antoniomarco** [comment]
Many thanks! Just asking, is this something to be fixed relatively soon or should we have to wait for a new release? I sort of lost dozens of shared histories that were quite important for your teaching development. Thanks.

**Comment by davelopez** [comment]
This should be fixed relatively soon before the 23.0 version is released, right now usegalaxy.org is running a release candidate version of 23.0, that's why you may experience some instability. Thanks for your understanding!

**Comment by davelopez** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/15531, still may need deployment in usegalaxy.org
