### ISSUE TITLE
Phylogenetic tree vizualisations do not work

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#15513]
**Describe the bug**

Just tried for: https://usegalaxy.org/visualizations?dataset_id=f9cad7b01a47213568cc6c40b6b49b1c

One gives an internal server error, and the other apparently does nothing. 

On my local (22.01) instance phyloviz is working and the other one gives me a popup `Load function 'load' not found.`.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0

**To Reproduce**

See above. I shared the history here  https://usegalaxy.org/u/m.bernt/h/cwl-target-history 

**Expected behavior**

Trees should be shown :) 

**Additional context**

http://biojs.io/ (mentioned in the description of the viz) seems down or gives me a timeout?

**Comment by dannon** [comment]
#15516 will fix phyloviz.

Not sure why phylocanvas isn't working yet (I'm not seeing the load error -- it loads and just shows *nothing* locally), but I'm working on it.

**Comment by bernt-matthias** [comment]
The load error only shows on my 22.01 instance.
