### ISSUE TITLE
Workflow Editor transparent offset handle while dragging

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/galaxy#15512]
When not on default zoom and dragging out a connection, a transparent offset node appears next to the drag position.

**To Reproduce**
1. Open Workflow editor
2. zoom in
3. drag a connection out

**Screenshots**
![Screenshot from 2023-02-06 15-01-46](https://user-images.githubusercontent.com/44241786/216991868-491fd72f-c754-4ad5-9819-425ac7ecbb62.png)

**Additional context**

**Comment by mvdbeek** [comment]
Is there anything special to do to reproduce this ? I'm not seeing this in chrome, firefox, safari on OSX

**Comment by ElectronicBlueberry** [comment]
Strange. Happened to me on Firefox on Linux. Use Galaxy org and latest local release version both had this issue on every Workflow. I'll give it a shot on windows.

**Comment by martenson** [comment]
I see it on Main on macos
![Screenshot_2_6_23__12_40_PM](https://user-images.githubusercontent.com/1814954/217080445-a8c47596-1305-4635-8a02-bb0f5cebc4b5.png)

**Comment by dannon** [comment]
Marius notes we can set a transparent drag image to avoid this, working on options.
