### ISSUE TITLE
Bug with the value of the config variable `email_from`

### ISSUE THREAD

**Issue by vazovn** [galaxyproject/galaxy#15518]
**Describe the bug**
(In galaxy.yml) 
If the variable `email_from` is left to _null_ it is supposed to receive the default value 'galaxy-no-reply@HOSTNAME'. Yet this does not happen if the value is NULL. When clicking on the bug icon to generate a job error report, the sending fails and the error message:

`An error occurred sending the report by email: Error asserting error_msg ` 

pops up.

In the log (journalctl) the error is:

```
Feb 07 10:21:32 galaxy01.educloud.no uwsgi[2573073]: galaxy.tools.error_reports DEBUG 2023-02-07 10:21:32,404 [pN:main.web.1,p:2573073,w:1,m:0,tN:uWSGIWorker1Core0] Bug report plugin <galaxy.tools.error_reports.plugins.email.EmailPlugin object at 0x7f0d99069b38> generated response ('An error occurred sending the report by email: Error asserting frm', 'danger')
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.09
Commit: 72bfa2b76db1aae57e5814e8f10d9755fa81f795

**To Reproduce**
1. Check that the value of `email_from`in galaxy.yml is set to null.
2. Run a job which shall fail
3. Go to the history panel, click on the bug icon of the job
4. Try to send the report
5. See the error above

**Expected behavior**
Smooth job error report sending

**Screenshots**

**Additional context**

**Comment by jdavcs** [comment]
If `email_from` is not set, what should `HOSTNAME` be in the default value? Unless we can extract it from another config value, I suspect that for mail to work, we must make that config option required alongside `smtp_server`?

**Comment by nsoranzo** [comment]
There is some code to deal with this case in https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/job_execution/actions/post.py#L56-L68 , maybe that should be moved to `lib/galaxy/config/__init__.py` ?

**Comment by jdavcs** [comment]
Yes, I think we could use `socket.getfqdn()` iff `config.smtp_server` is set, else we leave it unset. And yes, I'd move this logic into config; however, in that case we can't check for `"host" in action.action_arguments` because `config.email_from` would be always set (unless it were explicitly set to null in galaxy.yml) and there'd be no clean way to check if that value was set by the user (in which case we should leave it as is) or is the default (in which case, as per current logic, we should check `action.action_arguments['host']`).

**Comment by jdavcs** [comment]
> A domain name derived from `app.config.galaxy_infrastructure_url` could probably be used if set, before resorting to `socket.getfqdn()` .

OK, will do.

> `action.action_arguments['host']` is not set by the user (since this is the address which emails come _from_), but by the Galaxy UI in...

Right, but according to the current logic, we use this value *only if* `config.email_from` is not set. In the new logic, `config.email_from` would be *always* set, so we would *never*  check for  `action.action_arguments['host']` - and that's what I'm concerned about. Or do you mean we don't have to? Does this makes sense?

**Comment by nsoranzo** [comment]
I don't think this is something the backend should delegate to the UI, otherwise an API user would need to fill `action_arguments["host"]` themself, I suppose?
But happy to hear other opinions!
