### ISSUE TITLE
Eliminate Datatypes/Model Circular Dependencies

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1552]
- [ ] galaxy.datatypes.registry -> galaxy.datatypes.data -> galaxy.model -> galaxy.datatypes.registry

**Comment by nsoranzo** [comment]
:+1: 
I've tried some time ago without moving files with no luck.

**Comment by jmchilton** [comment]
@nsoranzo It is an oddly fun logic puzzle. Module loading is also an oddly large part of the time spent in testing so if we could load less that would help speed up testing as well.

**Comment by jmchilton** [comment]
@nsoranzo I'm going to start tracking other import issues here https://github.com/galaxyproject/galaxy/issues/1559 - please add any more distinct ones you know about.
