### ISSUE TITLE
Unable to view inner entries in list:list collection

### ISSUE THREAD

**Issue by patrick-austin** [galaxyproject/galaxy#15520]
**Describe the bug**
Attempting to view the inner elements of a `list:list` collection fails.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05
Commit: 5fd1141c385767ba81e2eaf2f299adf81b494fa3

**To Reproduce**
1. Install [test/functional/tools/collection_creates_dynamic_nested.xml](https://github.com/galaxyproject/galaxy/blob/5fd1141c385767ba81e2eaf2f299adf81b494fa3/test/functional/tools/collection_creates_dynamic_nested.xml) (or a tool which generates nested `list:list` collections)
2. Run tool
3. Click on output dataset to see the outer list
4. Click on any of the inner lists
5. No datasets appear in the history pane
6. Server log shows:
```
...
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "WITH": syntax error
[SQL: WITH RECURSIVE element_parents(dataset_collection_id) AS 
(SELECT dataset_collection_element.dataset_collection_id AS dataset_collection_id 
FROM dataset_collection_element 
WHERE dataset_collection_element.child_collection_id = ? OR dataset_collection_element.dataset_collection_id = ? UNION SELECT dce.dataset_collection_id AS dataset_collection_id 
FROM dataset_collection_element AS dce, element_parents AS ep 
WHERE dce.child_collection_id = ep.dataset_collection_id)
 SELECT hdca.id AS hdca_id 
FROM element_parents JOIN history_dataset_collection_association AS hdca ON hdca.collection_id = element_parents.dataset_collection_id 
WHERE hdca.id = ?]
[parameters: (107, 107, 78)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
...
```

**Expected behavior**
Inner datasets should be visible in the history panel.

**Screenshots**
![image](https://user-images.githubusercontent.com/61705287/217238445-f3b7877a-0d3b-42ac-b42e-8ef75004bb76.png)

Based on the above, expect to see `ie1` and `ie2`, but nothing is shown:

![image](https://user-images.githubusercontent.com/61705287/217238661-c2d16d66-02bb-4277-be4b-89ef17278a6b.png)

**Comment by mvdbeek** [comment]
Your sqlite doesn't support WITH RECURSIVE, you'll need at least 3.34
