### ISSUE TITLE
`build_mulled_singularity` container resolver tries to use docker, `cached_mulled_singularity` does nothing when building from UI, and `auto_install` is ignored

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#15570]
**Describe the bug**

Playing around with containers. Would hope that we could shed some light on the container resolvers and maybe add some docs / tests. 

When running a tool on a singularity destination the image is cached and used even if I have `auto_install="False"`. 

When triggering the building of a container in the admin UI I get:

```
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/web/framework/decorators.py", line 337, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/web/framework/decorators.py", line 113, in decorator
    return func(self, trans, *args, **kwargs)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/webapps/galaxy/api/container_resolution.py", line 107, in resolve_toolbox_with_install
    return self._view.resolve_toolbox(**kwds)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tool_util/deps/views.py", line 401, in resolve_toolbox
    rval.append(self.resolve(tool_id=tool_id, **resolve_kwds))
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tool_util/deps/views.py", line 379, in resolve
    resolved_container_description = self._app.container_finder.resolve(**find_best_kwds)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tool_util/deps/containers.py", line 76, in resolve
    return self.default_container_registry.resolve(enabled_container_types, tool_info, **kwds)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tool_util/deps/containers.py", line 352, in resolve
    container_description = container_resolver.resolve(
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 724, in resolve
    mull_targets(targets, involucro_context=self._get_involucro_context(), **self._mulled_kwds)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tool_util/deps/mulled/mulled_build.py", line 270, in mull_targets
    conda_context = CondaInDockerContext(ensure_channels=channels)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tool_util/deps/mulled/mulled_build.py", line 349, in __init__
    super().__init__(
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tool_util/deps/conda_util.py", line 103, in __init__
    info = self.conda_info()
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/tool_util/deps/conda_util.py", line 164, in conda_info
    info_out = commands.execute(cmd)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/util/commands.py", line 95, in execute
    return _wait(cmds, input=input, shell=False, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/util/commands.py", line 112, in _wait
    p = subprocess.Popen(cmds, **popen_kwds)
  File "/software/easybuild-broadwell/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/software/easybuild-broadwell/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
```

Note I have a few debug statements in my code, so line numbers might be slightly off.

My container resolvers config

```
<containers_resolvers>
  <cached_explicit_singularity cache_directory="/data/galaxy_server/galaxy-dev/database/container_cache/singularity"/>
  <explicit_singularity cache_directory="/data/galaxy_server/galaxy-dev/database/container_cache/singularity"/>
  <cached_mulled_singularity auto_install="False" cache_directory="/data/galaxy_server/galaxy-dev/database/container_cache/singularity" />
  <build_mulled_singularity auto_install="False" cache_directory="/data/galaxy_server/galaxy-dev/database/container_cache/singularity"/>
</containers_resolvers>
```

Actually for the tool in question a container is available at biocontainers and I do not understand why the `cached_mulled_singularity` resolver does not pull the container .. in addition to the problem that `build_mulled_singularity` raises. 

Edit: the `auto_install` "problem" (ie that a tool run caches the container) happens only if I add the follwing as 2nd last (not sure what happens if I have this line and install via UI):

```
<mulled_singularity auto_install="False" cache_directory="/data/galaxy_server/galaxy-dev/database/container_cache/singularity"/>
```

Edit: with this line included the container is cached when triggered from the admin UI .. Still everything should work without this line, isn't it .. 

We could also need some schema for the container_resolver config file, or?

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mvdbeek** [comment]
Matthias, i think you've cut off the part of the traceback with the actual error message. The options are explained in https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/container_resolvers_conf.xml.sample,
in particular the difference between cached and regular resolvers explains what your seeing.

docker is necessary on the head node for building mulled containers.

**Comment by bernt-matthias** [comment]
> i think you've cut off the part of the traceback with the actual error message.

Also just noticed. It was along the lines of  `no such file or directory: docker`.

> docker is necessary on the head node for building mulled containers.

In the foreseeable future there will be (at least extremely unlikely) a `docker` on any node on my system :( Maybe `podman` at some point .. but nobody knows .. but at least this part is expected (but maybe still worth fixing).

> difference between cached and regular resolvers explains what your seeing.

The docs for `cached_mulled_singularity`  state _"preferring cached singularity images to building local singularity images"_ which I interpreted such that the resolver takes a cached image if there is one and if not it creates the cache entry, or? 

While `mulled_singularity` makes singularity access the image via URI .. but then there is a confusing statement about images at the end.... hmm.

I just don't get it. Are there already tests for this .. or can we test this at all? It is so hard to reason about or learn by doing if one needs to wait for ~15min for Galaxy to restart for each config change ... 

How about the `auto_install` behavior? Running a tool should not cache the container if I get it right if I set `auto_install="False"`.

**Comment by mvdbeek** [comment]
Well, we could do it without docker, but that pr has been open for years without buyin. 

The cached resolver looks at the disk location for images and otherwise does nothing, auto_install determines if the Galaxy instance should pull the image. The non-cached version can pull images, and the build version can build images. Does that make sense?

That description was community-contributed, a resolver doesn't prefer anything, and the only resolver that builds stuff has it in the name.

**Comment by mvdbeek** [comment]
Also a fantastic case of more documentarion doesn't necessarily make things better, i would say the name of the option would have been clearer without the added text ?

**Comment by bernt-matthias** [comment]
> Well, we could do it without docker, but that pr has been open for years without buyin.

For completeness, you mean https://github.com/galaxyproject/galaxy/pull/9088 ?

> The cached resolver looks at the disk location for images and otherwise does nothing

Clear.

>  auto_install determines if the Galaxy instance should pull the image. 

Just to be sure:

- This means during (or better before) tool execution? If I'm not wrong, this seems broken and the cached image is also created if `auto_install="False"` is chosen.
- Is it correct that this makes sense only for the non-cached resolvers (since cached resolver only looks up on the disk)

> The non-cached version can pull images, and the build version can build images. Does that make sense?

One thing that is/was confusing me is that the resolver seems to yield either

- an URI, e.g. `docker://...` (if `auto_install="false"`?) , or 
- the path to the cached resolver (on the first call with `auto_install="true"`?) ... this is more a guess ... because I can't imagine the process otherwise

> That description was community-contributed, a resolver doesn't prefer anything, and the only resolver that builds stuff has it in the name.

OK. Lets work on the docs

> Also a fantastic case of more documentarion doesn't necessarily make things better, i would say the name of the option would have been clearer without the added text ? 

Indeed, quality of the docs is also important. 

One might also consider it as a case where more developer contributed documentation might have avoided a bit of confusion :) Apparently the code and the contained docs were to difficult to understand.

**Comment by mvdbeek** [comment]
> For completeness, you mean #9088 ?

Yes

> * This means during (or better before) tool execution?

Yes.

> * If I'm not wrong, this seems broken and the cached image is also created if `auto_install="False"` is chosen.

Do you really see the image being pulled by the cached resolver (it's in the logs), or are you just passing through the image name and it gets pulled on your cluster node ?

> One thing that is/was confusing me is that the resolver seems to yield either

I don't understand what you're saying there. Try them in isolation if you have a doubt ?

**Comment by bernt-matthias** [comment]
> Try them in isolation if you have a doubt ?

Excellent idea .. So I did some more systematic testing here. 

1. using only cached resolvers

```
<cached_explicit_singularity cache_directory="/data/galaxy_server/galaxy-dev/database/container_cache/singularity"/>
<cached_mulled_singularity cache_directory="/data/galaxy_server/galaxy-dev/database/container_cache/singularity" />
```

- The cached explicit resolver pulls the image on tool run and when triggered from UI. The tool then uses the downloaded image.
- The cached mulled resolver on its own does nothing, i.e. no image is pulled when a tool is run or build is triggered from admin UI. `auto_install` does nothing (I used it above and just wanted to be sure .. seems also in line with my understanding of the code)


2. using only NON-cached resolvers

```
<explicit_singularity cache_directory="/data/galaxy_server/galaxy-dev/database/container_cache/singularity"/> 
<mulled_singularity auto_install="False" cache_directory="/data/galaxy_server/galaxy-dev/database/container_cache/singularity"/>
```

- The explicit resolver uses URI for singularity, i.e. `cache_directory` has no meaning here.
- The mulled resolver pulls the image to the `cache_directory` before tool execution and then uses the cached image. Installing from UI also pulls the image. 

Then I tried to remove `cache_directory`, but this has no influence. The value I chose appears to be the default. But changing `cache_directory`  has an effect.

Summarizing the result of today: 

1. The `mulled_singularity` resolver is also "cached" (it creates and uses cached container images), while `cached_mulled_singularity` "only" uses existing cached images. The naming of the resolvers is quite confusing. I assume that the behavior of the mulled resolvers its the same for docker since they share common code, i.e. they use the same `resolve` method (but I'm not 100% sure and can't test). 
2. For singularity the cached and the non-cached resolvers work very different for explicit and mulled containers and I see a use in both strategies. But one certainly has to use the explicit container resolvers differently than the mulled ones:
  - For explicit resolvers it seems to make no sense to include the cached and non-cached resolver
  - For mulled ones seems to make sense (the cached should avoid to use the non-cached one .. but I have to try to be sure).
- `auto_install="False"` does not influence if a container is cached to an image

> Do you really see the image being pulled by the cached resolver (it's in the logs), or are you just passing through the image name and it gets pulled on your cluster node ?

Yes. If I understand [the code](https://github.com/galaxyproject/galaxy/blob/db1af977cf69158f5fc91da2d036ab33ae23e6e9/lib/galaxy/tool_util/deps/container_resolvers/mulled.py#L592
) correctly: the `pull` methid is called completely independent of `auto_install` which seems wrong .. but when thinking about it I was also not clear what it means to install a container .. is it to pull it to an image file? In my attempts to debug the function always gets `install=True` which leads to calling the pull function always.

Guess I will continue tomorrow with testing `cached_mulled_singularity` and `mulled_singularity` in action together.

**Comment by bernt-matthias** [comment]
xref https://github.com/galaxyproject/galaxy/pull/15614
