### ISSUE TITLE
Nested input parameters not provided as top level variables in old profile versions

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#15592]
I think our intention was that this only breaks for tools with profile versions < 18.09, but for a bunch of deeptools tools I see
UnboundLocalError exceptions. 
```
        #if $custom_sample_labels_conditional.custom_labels_select == "Yes":
            #set custom_labels=labels
        #end if
```

Here `labels` is a parameter inside a conditional, and since https://github.com/deeptools/deepTools/blob/master/galaxy/wrapper/computeMatrix.xml doesn't specify a profile version this should continue to work.

I don't think we broke this recently, but it's worth fixing IMO.

**Comment by bernt-matthias** [comment]
Access should work: https://github.com/galaxyproject/galaxy/blob/df0b6497589a5dc04073ba0e7b7c7511dd4a1dbe/test/functional/tools/identifier_in_conditional.xml#L12

I guess it should be 

```
#set custom_labels=$labels
```

Tested for out example with `#set x = $input1` which worked.

**Comment by mvdbeek** [comment]
Interesting, could it have been broken for so long ?

**Comment by bernt-matthias** [comment]
Guess this repo needs testing :)

**Comment by mvdbeek** [comment]
It does have tests, but if you're not testing the custom labels you'll never find this issue.

**Comment by nsoranzo** [comment]
So not a Galaxy issue, close?

**Comment by mvdbeek** [comment]
Unclear, this must've worked, I think that's a commonly used option and when you're in a `#` section you're in the normal python namespace. Onde difference with the test tool is that this is deeply nested. I think we need to do some more digging here.

**Comment by mvdbeek** [comment]
https://cheetahtemplate.org/users_guide/language.html#are-all-those-dollar-signs-really-necessary has the answer:

> In expression position, the {$} is { required} if the value comes from the searchList or a “#set global” variable, { recommended} for local/global/builtin variables, and { not necessary} for the special constants {None}, {True} and {False}. This works because Cheetah generates a function call for a searchList placeholder, but a bare variable name for a local/global/builtin variable.

and the param_dict is fed in via searchList. I guess this never worked
