### ISSUE TITLE
unstyled activation banner

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#15601]
After registering new user at usegalaxy.org the activation banner is unstyled, I assume it should be blue/yellow?

![Galaxy](https://user-images.githubusercontent.com/1814954/219455095-a3087e38-a45d-4a8f-9dc3-14d97cbcf7e6.png)

**Comment by dannon** [comment]
It's not supposed to be a banner, it's just the introduction for the contents that you note are broken in #15601.  I'll take a look at that issue which will make this all look correct again.

**Comment by martenson** [comment]
Are you sure? The activation banner used to be warning https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample#L1099

**Comment by dannon** [comment]
Yeah, that's not the activation success page, it's the "New User Welcome" and the bottom is just busted.

**Comment by martenson** [comment]
Apologies for the confusion, I tried to use the screenshot for two bug reports and it was not a good idea.

**Comment by dannon** [comment]
No worries!  I saw the two issues and assumed it was about the same thing instead of, you know, thinking about it.
