### ISSUE TITLE
the /welcome/new page is empty

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#15602]
After registering new user on usegalaxy.org you are redirected to https://usegalaxy.org/welcome/new which talks about clicking on "pages below". However nothing it rendered under the message.

![Galaxy](https://user-images.githubusercontent.com/1814954/219455447-b0197035-9a77-4313-9cd6-778ac13256b1.png)

**Comment by dannon** [comment]
I'll take a look, thanks!
