### ISSUE TITLE
[feature request] Link to training materials from tools

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#15612]
> below at the citation box, have a training box
> this training box could list all training this tool was used (not limited to the specific tool version)

_Originally posted by @bgruening in https://github.com/galaxyproject/training-material/issues/3081_

Yes, I think this is now ready/possible with https://training.galaxyproject.org/training-material/by-tool/devteam/fastqc.html. Can be exposed as a JSON API as well if that's better.

**Comment by ElectronicBlueberry** [comment]
Exposing this as a JSON API could be helpful for displaying the topics and number of tutorials in the tool form.

**Comment by hexylena** [comment]
We've got an "everything" endpoint, but we could do this per tool too. https://training.galaxyproject.org/training-material/api/top-tools.json it's not a huge response currently, and probably won't grow exponentially.

I'll see about splitting it when I have time, but the everything endpoint is available now if it helps scaffold things out.

**Comment by ElectronicBlueberry** [comment]
Thanks! Since this doesn't need to be called often, I think the everything endpoint is fine for now
