### ISSUE TITLE
Email verification link server error

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#15621]
**Describe the bug**
A verification link that sends to a new user makes an internal server error and can not the verify account

![image](https://user-images.githubusercontent.com/8046843/220094377-94e67e2f-2dd5-4d70-b643-2870bb2c5b93.png)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version:  `23.0.rc1` (usegalaxy.org)

**To Reproduce**
1. Register as a new user
2. Click on the verification link that has been sent to your email
3. See the error

**Comment by mvdbeek** [comment]
duplicate of #15604
