### ISSUE TITLE
attribute_value_splitter vs multiple_splitter

### ISSUE THREAD

**Issue by tuncK** [galaxyproject/galaxy#15635]
https://github.com/galaxyproject/galaxy/blob/e7092b6d2f6910765842da81fb4d1da39188ef24/lib/galaxy/tools/parameters/dynamic_options.py#L363

The former is deprecated in favour of the latter. However, it is my impression that attribute_value_splitter does not do the same thing as 2x multiple_splitter. Maybe  attribute_value_splitter should not be deprecated but advertised in dev manual in detail?

The dev manual says "multiple_splitter: split the entries of the specified column(s) in the referenced file using a separator. Thereby the *number of columns is increased.*"  However, the for loop in https://github.com/galaxyproject/galaxy/blob/e7092b6d2f6910765842da81fb4d1da39188ef24/lib/galaxy/tools/parameters/dynamic_options.py#L354 seem to be doubling the number of rows, while maintaining the number of columns. As such, an example input:
 A B C=cc;D=dd E

result of multiple_splitter(2,';')
 A B C=cc E
 A B D=dd E

result of multiple_splitter(2,'=')
 A B C E
 A B cc E
 A B D E
 A B dd E

result of directly applying attribute_value_splitter(2,';','='):
 A B C C=cc;D=dd E
 A B D C=cc;D=dd E

I dont know if this was intended, but attribute_value_splitter seems to have a passive attitude against malformed input files, because it skips the improperly formatted lines (https://github.com/galaxyproject/galaxy/blob/master/lib/galaxy/tools/parameters/dynamic_options.py#L389) without raising an error. Ex, this input:
 A B C=cc;D=dd E
 A B G=gg;H E

becomes:
 A B C C=cc;D=dd E
 A B D C=cc;D=dd E
 A B G G=gg;H E

**Comment by bernt-matthias** [comment]
> The former is deprecated in favour of the latter. However, it is my impression that attribute_value_splitter does not do the same thing as 2x multiple_splitter. Maybe attribute_value_splitter should not be deprecated but advertised in dev manual in detail?

Yes, you are right. Guess this was my mistake. Would be cool to have a test and better docs for this. Would you be able to add this? 

Docs would be cool in the galaxy.xsd file. And a test maybe in test/functional/tools? 

> I dont know if this was intended, but attribute_value_splitter seems to have a passive attitude against malformed input files, because it skips the improperly formatted lines

Seems to be due to: https://github.com/galaxyproject/galaxy/blob/e7092b6d2f6910765842da81fb4d1da39188ef24/lib/galaxy/tools/parameters/dynamic_options.py#L389 .. ie ignore everything that does not split in a pair

**Comment by tuncK** [comment]
> Docs would be cool in the galaxy.xsd file. And a test maybe in test/functional/tools?
Yes, I will try to do that. Though, there is also need to relax the linter's requirements for this to work. Currently: "ERROR pair_separator and name_val_separator not allowed in a filter."

**Comment by tuncK** [comment]
> Seems to be due to:
> 
> https://github.com/galaxyproject/galaxy/blob/e7092b6d2f6910765842da81fb4d1da39188ef24/lib/galaxy/tools/parameters/dynamic_options.py#L389

Yes. Should I let it alone because it serves a purpose, or should I put an else that raises KeyError?

**Comment by bernt-matthias** [comment]
Would leave it
