### ISSUE TITLE
Workflow invocation RO-Crate export  missing metadata elements

### ISSUE THREAD

**Issue by pauldg** [galaxyproject/galaxy#15642]
**Describe the bug**

As outlined in this [PR](https://github.com/ResearchObject/workflow-run-crate/pull/44) some of the json-ld metadata of the [workflow invocation ro-crate export functionality](https://github.com/galaxyproject/galaxy/pull/15101) does not align with the of the [Workflow Run Crate profile](https://www.researchobject.org/workflow-run-crate/profiles/workflow_run_crate) and therefore has to be updated accordingly.

The changes required are some minor restructuring of the json-ld metadata file. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0
Commit: a9c1b60da4bb3cadd90f99700ca0ed997c6a40a3

**Comment by pauldg** [comment]
Fixed by `https://github.com/galaxyproject/galaxy/pull/15841`

**Comment by bgruening** [comment]
Great work @pauldg
