### ISSUE TITLE
fastq.gz is viewed but fasta.gz is not

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/galaxy#15653]
**Describe the bug**
fasta.gz files are downloaded when the view button is clicked. fastq.gz are shown in the view window.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: https://usegalaxy.org/ (v23)

**To Reproduce**
1. Upload the attached files
2. Click on view for both

**Expected behavior**
I would assume a consistent behavior for both files. Expected to see the fasta file.  

**Test files**
[example.fastqsanger.gz](https://github.com/galaxyproject/galaxy/files/10838324/example.fastqsanger.gz)
[examle.fasta.gz](https://github.com/galaxyproject/galaxy/files/10838325/examle.fasta.gz)

**Comment by mvdbeek** [comment]
that's the difference between the display_data methods in the BaseFastq class vs the Sequence class. That's a good starting project if you want to give that a shot @paulzierep
