### ISSUE TITLE
join the interval tool invalid syntax

### ISSUE THREAD

**Issue by cmdickens** [galaxyproject/galaxy#15668]
We have version 22.05 installed with Python 3.7.4.  The "Join the intervals of two datasets side-by-side (Galaxy Version 1.0.0)" tools fails on our system. The bx-python version in our .venv is __version__ = '0.8.13'

<pre>Traceback (most recent call last):
  File "/scratch/user/galaxy/my_galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/join/718d04143c31/join/gops_join.py", line 16, in <module>
    from bx.cookbook import doc_optparse
  File "/sw/hprc/galaxy/my_galaxy/galaxy/.venv/lib/python3.7/site-packages/bx/cookbook/__init__.py", line 14
    yield from flatten(elem)
             ^
SyntaxError: invalid syntax
</pre>

**Comment by mvdbeek** [comment]
It appears that the tools' dependencies are not installed and Galaxy is falling back to the global dependencies provided in Galaxy's virtualenv. You can install dependencies in the admin panel, under "Manage tool dependencies" for Conda or Container requirements.
