### ISSUE TITLE
Forbid singularity to mount `/tmp` by default

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#15673]
**Describe the bug**

From the discussion in https://github.com/galaxyproject/galaxy/pull/14922#discussion_r1121430126

Could be enforced by adding `--no-mount tmp`. 

Guess also if `-B $TMP:$TMP ...`  needs adjustment?

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0

**Comment by mvdbeek** [comment]
> Guess also if `-B $TMP:$TMP ...` needs adjustment?

this is correct, singularity just shouldn't go around mounting /tmp, which can contain sensitive data from other users.

**Comment by bernt-matthias** [comment]
Guess we need to look at this https://github.com/galaxyproject/galaxy/blob/24d7809f4a52cb1cdfcf95992ad6a640fe22760f/lib/galaxy/tool_util/deps/container_classes.py#L231

In practice (on my instance and many panemo runs) I have always seen the else branch in action. Wondering when the if is running, i.e. when `self.job_info.tmp_directory is not None` holds.

> Guess also if -B $TMP:$TMP ... needs adjustment?

We do this for docker and singularity since recently https://github.com/galaxyproject/galaxy/pull/15039

**Comment by bernt-matthias** [comment]
> So we need to add a test that, with the other binds that we pass, /tmp is writable.

This is what I don't get my head around yet. If we want to ensure that  `/tmp` is writable isn't this equivalent to mounting `/tmp` by default?

**Comment by bernt-matthias** [comment]
We might have a per job tmp, e.g. replacing `$TMPDIR:rw,$TMP:rw,$TEMP:rw"`
by something like `${TMPDIR:-xyz}:rw,${TMP:-xyz}:rw,${TEMP:-xyz}:rw"` where xyz may be a created temp dir .. but how to clean up .. and how to ensure that this works in real user configs ...

**Comment by bernt-matthias** [comment]
how about replacing `$_GALAXY_JOB_TMP_DIR:$_GALAXY_JOB_TMP_DIR:rw` by `$_GALAXY_JOB_TMP_DIR:/tmp/:rw`?

**Comment by bernt-matthias** [comment]
My suggestion would be as follows:

- singularity: add `--no_mount tmp` (analogous to docker's default)
- do not bind `$TMPDIR:rw,$TMP:rw,$TEMP:rw` by default
- instead (by default) provide a writable `/tmp` via `$_GALAXY_JOB_TMP_DIR/:/tmp:rw` note that this dir is still also available as `$_GALAXY_JOB_TMP_DIR:rw` 
- allow admins to add an additional `*:/tmp:*` bind that overwrites the default 
  - this "required" a refactoring volume preprocessing 

I think the last point is important to allow admins to provide fast directories as `/tmp` .. maybe even the host's `/tmp` (for instance on our system the compute nodes provide a "RAM disk"  via `/tmp` (shared between users)). 

I implemented this in https://github.com/galaxyproject/galaxy/pull/15614 (because I have a few more tests over there) in the commits 1d353c664ef8fed6b0b5a6221e90d981cddf00d8, 35c5ee415cedec50e402c3ebeb6ef20c1fa991e2, and d4f56438e77a3193be28b2b068997b0805451c5b

If you like you can add your comments here. 

I do not think that we need to backport this (but we can), since it couses trouble only in tests (where everything like job dir, galaxy, is in /tmp).

**Comment by bernt-matthias** [comment]
Had to rebase. The three commits are those with the descriptions: 

- containers: do not mount /tmp/
- refactor volume preprocessing
- remove volumes with duplicate targets
