### ISSUE TITLE
Security Reports

### ISSUE THREAD

**Issue by familiardisaster** [galaxyproject/galaxy#15698]
I submitted several security concerns via huntr.dev and tried to reach out to the mailing list but have received no response so far. Should I re-submit these via private reporting or are they being handled in some way already? I would prefer to resolve through the huntr.dev platform.

**Comment by martenson** [comment]
Hi @familiardisaster, thank you for reaching out! We will double check the `galaxy-committers@lists.galaxyproject.org` we use for the security reporting and get back to you. I believe we do not have any contacts with huntr.dev platform -- so I am not sure what to expect from them.

**Comment by martenson** [comment]
The messages from huntr.dev were held by our moderation filter. We are looking at them now, thank you!

**Comment by familiardisaster** [comment]
Great, thanks. Glad I can help. Let me know about any questions.

**Comment by familiardisaster** [comment]
Hi, saw a fix was already shipped for one of them. Was hoping to get some CVE's assigned :) if that is possible.

**Comment by dannon** [comment]
@familiardisaster Thanks for the reports; I'm going to close this issue out and we'll follow up on them individually.  Yes, we'll assign CVEs as appropriate.
