### ISSUE TITLE
Follow Up On Object Store Selection

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#15692]
Issues related to object store selection implemented in https://github.com/galaxyproject/galaxy/pull/14073 and  refined in https://github.com/galaxyproject/galaxy/pull/15654

- [x] Simple sample in object_store_conf sample (https://github.com/galaxyproject/galaxy/pull/15707)
- [ ] Dump admin portion of PR description into admin/production.rst or something like that
- [ ] Write a test case for having the same subworkflow embedded twice (https://github.com/galaxyproject/galaxy/pull/14073#discussion_r1124348755).  (https://github.com/galaxyproject/galaxy/compare/dev...jmchilton:galaxy:duplicated_nested_workflows?expand=1)
- [x] "I think the type should be a union of EncodedDatabaseId and the literal current here." https://github.com/galaxyproject/galaxy/pull/15654#pullrequestreview-1324015914
- [ ] "Can you use useConfig(true) here please ? The ConfigProvider triggers a new fetch every time." https://github.com/galaxyproject/galaxy/pull/15654#discussion_r1124591059  (@ElectronicBlueberry  said she'll include it in https://github.com/galaxyproject/galaxy/pull/15686/files) 
- [ ] Fix issue with ObjectNotFound (https://github.com/galaxyproject/galaxy/pull/14073#pullrequestreview-1323745533) 
- [x] ``/api/object_store`` -> ``/api/object_stores``
- [x] ~Redo awkward target DOM stuff on HistorySelect component without breaking popover~ (asked about this in UI/UX - maybe it is okay as it)
- [ ] Migrate Vue components to TypeScript and composition API.
   - [x] SelectObjectStore.vue
   - [x] client/src/components/Dataset/DatasetStorage/ObjectStoreRestrictionSpan.vue
   - [x] client/src/components/History/CurrentHistory/HistoryPreferredStore.vue
   - [x] client/src/components/ObjectStore/ObjectStoreBadge.vue
   - [x] client/src/components/ObjectStore/ObjectStoreBadges.vue
   - [x] client/src/components/ObjectStore/ShowSelectedObjectStore.vue
   - [ ] client/src/components/Tool/ToolTargetPreferredObjectStorePopover.vue
   - [ ] client/src/components/User/DiskUsage/Quota/ProvidedQuotaSourceUsageBar.vue
   - [x] client/src/components/User/UserPreferredObjectStore.vue
   - [x] client/src/components/Workflow/Run/WorkflowSelectPreferredObjectStore.vue
   - [ ] client/src/components/Workflow/Run/WorkflowStorageConfiguration.vue
   - [ ] client/src/components/Workflow/Run/WorkflowTargetPreferredObjectStorePopover.vue
- [x] Migrate new axios and providers to fetches and (probably) pinia around quotas.
- Fine tuning “preferred” vs ... “selection” nomenclature in the UI
   -  [x] Automated default based on object store and job configuration stuff.
    - [x] Allow admin to configure this if dynamic job runners are used.

**Comment by mvdbeek** [comment]
- [ ] Simple sample in object_store_conf sample
- [ ] Dump admin portion of PR description into admin/production.rst or something like that
