### ISSUE TITLE
Loading of job submission success page after new request

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15704]
**Describe the bug**
After submitting a new job it sometimes takes substantial time before the jobs/submission/success page is loaded, and often the history gets updated before that happens.
In 23.0, if a user requests another page while loading of the success page is pending, the earlier request is still getting handled and the success page appears suddenly while the user already does something else.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0 on usegalaxy.eu

**Expected behavior**
The old behavior (earlier request got dropped was slightly better, but also somewhat suboptimal. The issue is that in between hitting Run Tool and display of the success page, the system, from a user perspective is in an ill-defined state (did the Run Tool request get handled or not?)
Maybe it would be possible to immediately display some kind of information when it's safe to proceed and display the final job submission details later as they become avaialble?

**Comment by mvdbeek** [comment]
> In 23.0, if a user requests another page while loading of the success page is pending, the earlier request is still getting handled and the success page appears suddenly while the user already does something else.

Could you provide a small screencast of that behavior ? It does sound like a bug, though I'm surprised the component is still active in that case.

I think the thing to do in general is to handle the job setup as a background task, that will be part of https://github.com/galaxyproject/galaxy/pull/14962

**Comment by wm75** [comment]
![job_submission](https://user-images.githubusercontent.com/4742081/223089068-9ed63ae2-eb9e-45f6-a8ad-b94622fa5533.gif)

Needed to do this with a rerun of a failed job or the response is too fast.

**Comment by ahmedhamidawan** [comment]
Notes from @galaxyproject/wg-uiux meeting:
- There could be a `Promise` hanging around from the job submission that causes the Success component to rerender

**Comment by ahmedhamidawan** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/15801
