### ISSUE TITLE
Collection jobs record dataset collection elements instead of HDAs

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15729]
*Edit by @mvdbeek*

Nothing is wrong here, we've improved the provenance tracking, but the UI and job rerun routes don't know how to deal with dataset collection elements, these are minor tweaks, not severe bugs.

**Describe the bug**
When you're running any workflow that is mapping over collections, Galaxy records as input for any collection element not the dataset ID, but a malformed version of the element identifier. With that the possibility to rerun jobs is completely lost!!

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0rc1 on .org and .eu

**To Reproduce**
1. Run any workflow that involves a mapping over a collection
2. Open the output collection and inspect any of the elements

**Expected behavior**
Each element should have its input dataset from the input collection recorded, but in reality what gets recorded is what's shown below

**Screenshots**

![image](https://user-images.githubusercontent.com/4742081/223478654-4fb9c34b-24fb-4ef6-a335-17432b66ed35.png)

**Comment by wm75** [comment]
What do you mean. It is supposed to be a dataset element - that's kind of the point.

**Comment by mvdbeek** [comment]
SRRblabla is a dataset collection element, this has been that way ever since we've shown input datasets in the job info page. But if you can share a history that'd be great.

**Comment by mvdbeek** [comment]
which element in that history should I look at ?

**Comment by wm75** [comment]
any from any simple list. They are all broken.

**Comment by mvdbeek** [comment]
None of it is broken:

<img width="1870" alt="Screenshot 2023-03-07 at 18 21 54" src="https://user-images.githubusercontent.com/6804901/223500004-5dd6a409-cca2-4d93-9dea-9ade262db26c.png">

the UI just doesn't know how to display DCEs. We'd previously track HDAs, which was not quite correct.

**Comment by wm75** [comment]
That's better of course, puh. So just an annoying bug then.

**Comment by wm75** [comment]
Why is this only happening for WFs then, and not for regular job runs on collections?
Why mix things?

**Comment by mvdbeek** [comment]
It also happens (and has been happening) for normal jobs.

**Comment by wm75** [comment]
> It also happens (and has been happening) for normal jobs, just less frequently.

I don't follow I'm afraid why is this about frequencies? Shouldn't it be either/or?

**Comment by mvdbeek** [comment]
We used to track the HDA associated associated with a DCE. You've probably noticed that if you re-run a job from a list you'd re-run on the hda, because the element identifier if the element you consume is gone.

We've always tracked DCEs when the input parameter was a collection, and the actual input was a nested collection (e.g. a list input on a list:list HDCA). We have now removed the special casing for HDAs and pass through the element instead. So now you see this more often.

**Comment by wm75** [comment]
I see, but I thought I had tested earlier today that if you manually run a tool over a collection (not an individual job), the UI has no issue with showing the provenance correctly (that's actually why I thought it can't be the UI in the first place). On my phone now so hard to check again, but that's what I think I remember.

**Comment by mvdbeek** [comment]
I'll check that, but this should be all the same.

**Comment by mvdbeek** [comment]
Yeah, I'll pick this back up.

**Comment by mvdbeek** [comment]
> With that the possibility to rerun jobs is completely lost!!

So I think I fixed the job info page now. Is rerunning these jobs really broken, or did it just seem that way because of the text where you'd expect a dataset ? The import of your example history takes forever, but checking on my instance that all seems to work correctly.

**Comment by wm75** [comment]
It is *really* broken on .eu. I can create a minimal example there for you I guess.

**Comment by wm75** [comment]
Ok,

WF to reproduce the issue:
https://usegalaxy.eu/u/wolfgang-maier/w/minimal-collections-wf

history created with it:
https://usegalaxy.eu/u/wolfgang-maier/h/minimal-collections-wf-1

You should be able to observe the following:
- try to rerun any of the jobs in the `6: Add column` or `10: Add column` collections.
  These will claim that they've been generated with `14: Add column` as input.
- try to hit Run Tool despite the nonsense, and the rerun job will *actually* use `14` as input (you can confirm it's really happening through the contents of the results).
- try to rerun anything in `14: Add column`.
  This should work just fine because that collection was not produced through the WF, but via a manual tool run.

**Comment by mvdbeek** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/15744, I'll probably update .org later today
