### ISSUE TITLE
Workflow invocation slower than before

### ISSUE THREAD

**Issue by tuncK** [galaxyproject/galaxy#15728]
**Describe the bug**
Something I noticed immediately after the 23.0 deployment on [galaxy.eu](http://galaxy.eu/): it takes substantially longer to schedule a workflow for execution (~10s) in contrast to its behaviour the past, where it was immediately starting scheduling jobs and placing placeholders in the history. I do not mean that tools are staying gray/yellow for n seconds but rather that the invocation step itself hangs longer than in the past. 

I am not sure if it is a bug, as if some step in the invocation takes a few seconds of time which now became longer.

**To Reproduce**
Take a reasonably big workflow and invoke on a collection. Immediately after pressing the play button, observe the graphical summary of the invocation status provided by galaxy UI.

**Comment by mvdbeek** [comment]
10 seconds for a loop of the invocation scheduler doesn't seem long, this depends on how many invocations there are to schedule.

**Comment by bgruening** [comment]
I will have a look.

**Comment by mvdbeek** [comment]
Why do you even have this running ? Is it just for the job rules ?

**Comment by mvdbeek** [comment]
A py-spy dump would be helpful too.

**Comment by bgruening** [comment]
yes, for job rules. We had (disabled it now):

```
    watch_core_config: true
    watch_job_rules: true
```

enabled. Has ORG that disabled?

**Comment by bgruening** [comment]
I saw the similar logs in the job handlers with other config files:

> Mar 07 11:58:29 sn06.galaxyproject.eu python[257970]: watchdog.observers.inotify_buffer DEBUG 2023-03-07 11:58:29,791 [pN:handler_sn06_4,p:257970,tN:Thread-17] in-event <InotifyEvent: src_path=b'/opt/galaxy/config/total_perspective_vortex/interactive_tools.yml', wd=1, mask=IN_OPEN, cookie=0, name='interactive_tools.

**Comment by mvdbeek** [comment]
<img width="1294" alt="Screenshot 2023-03-07 at 17 31 44" src="https://user-images.githubusercontent.com/6804901/223486810-a8eeb22a-62a1-4814-8a36-3f97ec95e414.png">

I don't know exactly when we've crated the index though
