### ISSUE TITLE
GeneFamilyClassifier tool not working (RED result box)

### ISSUE THREAD

**Issue by Huiting120** [galaxyproject/galaxy#15735]
**Describe the bug**
GeneFamilyClassifier tool produced no result

**Galaxy Version and/or server at which you observed the bug**
Public galaxy server:
The Galaxy Server is running version [23.0.rc1 ](https://docs.galaxyproject.org/en/release_23.0/releases/23.0_announce_user.html), and the web client was built on Monday Mar 6th 16:38:56 2023 UTC .

**To Reproduce**
![Screen Shot 2023-03-07 at 12 47 41 PM](https://user-images.githubusercontent.com/19787561/223548872-2397ceda-857e-4da7-9f69-46d21239f324.png)

Error:
![Screen Shot 2023-03-07 at 12 48 49 PM](https://user-images.githubusercontent.com/19787561/223549026-c65e486f-dd94-4122-b7b6-23261a0516e6.png)

**Expected behavior**
A tabular output with gene name, Orthogroup assignment, number of sequences from each scaffolding species, superOG assignment, and Annotation

**Additional context**
below is job information from Oct. 2022
![Screen Shot 2023-03-07 at 12 35 22 PM](https://user-images.githubusercontent.com/19787561/223549387-12c1c559-329e-484a-9166-9fe91bc1ff71.png)

below is job information from today (March 7th 2023)
![Screen Shot 2023-03-07 at 12 34 22 PM](https://user-images.githubusercontent.com/19787561/223549520-aa0d83ec-789f-4126-94fd-87fdbc19edcb.png)

Same input and parameters were used for both runs.

The command line version of this tool works well.

**Comment by bernt-matthias** [comment]
Please report the error in the corresponding tool repository https://github.com/gregvonkuster/galaxy_tools/tree/master/tools/phylogenetics/plant_tribes

Ping @gregvonkuster

**Comment by bernt-matthias** [comment]
Sorry, wrong link https://github.com/gregvonkuster/galaxy_tools/
