### ISSUE TITLE
[23.0] Tutorial mode non-functional, missing access to window.Galaxy

### ISSUE THREAD

**Issue by hrukkudyr** [galaxyproject/galaxy#15749]
I'm running through[ this tutorial](https://training.galaxyproject.org/training-material/topics/single-cell/tutorials/scrna-case_JUPYTER-trajectories/tutorial.html) and I am unable to use the tool launcher from within [my history.](https://humancellatlas.usegalaxy.eu/u/graeme_tyson/h/jupyter-scanpy) This is repeatable on both use.galaxy.eu and humancellatlas.usegalaxy.eu

Dev Tools in my browser is showing the following error:
![image](https://user-images.githubusercontent.com/32413040/223970375-5d4901fb-aaaf-45ff-bf99-574786990b95.png)

**Comment by nomadscientist** [comment]
Same issue for me
Mac + Safari = I see the button but clicking it does nothing
Mac + Chrome = the button looks like an outline
<img width="470" alt="Screenshot 2023-03-09 at 12 17 36" src="https://user-images.githubusercontent.com/44605769/224020765-775f8c35-2b39-4caf-83d9-a0593f6a391e.png">
Mac + Firefox = Same as Mac + Chrome
