### ISSUE TITLE
`Show structure`, `Include deleted`, and `Include hidden` buttons missing from whole-page history view

### ISSUE THREAD

**Issue by abueg** [galaxyproject/galaxy#15742]
**Describe the bug**
Hello! 👋🏼 

After the 23.0 update, the whole-page history view seems to be missing the `Show structure`, `Include deleted`, and `Include hidden` buttons from the top of the page where they used to be. There is now only a `Switch to this history` button.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: EU
{"version_major":"23.0","version_minor":"rc1"}

**To Reproduce**
1. From the view of all the histories, click the drop down on your active history and click `View`
2. Observe lack of buttons

**Expected behavior**
Buttons should be visible at the top, see screenshot from an instance running previous galaxy version:
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/48773001/223784915-d4956990-dcdd-4736-b5cb-e8d63056e363.png">

**Screenshots**
Buttons no longer visible at top in current galaxy version:
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/48773001/223785029-93c3c909-bd77-4595-80fa-ae9f6614d6b7.png">

**Additional context**
I observe this on FireFox and Chrome.

**Comment by ahmedhamidawan** [comment]
Fixed in #15913

**Comment by jennaj** [comment]
Hi @ahmedhamidawan 

The counter + size seem to be correct now in this view, thank you!

I created an issue ticket after testing a related view and found a small problem. Eg stale values https://github.com/galaxyproject/galaxy/issues/15948

Questions: 

1. Will we be adding back 'Show structure'? The last two are covered but "Show structure" itself is missing from this view. 

> Show structure, ~~Include deleted, and Include hidden buttons~~ from the top of the page where they used to be

2. The _History options -> Show structure_ function also seems to have been lost.

Did we entirely drop the 'Show structure' view entirely for some reason? I thought it was super helpful eg exposed so many more details in a single view.

If you plan to tackle that in a different ticket wanted to make sure we also fix the other way to reach it (history menu item, not just history list > view.

**Comment by ahmedhamidawan** [comment]
Hey @jennaj ! I've seen the new ticket you put up and yes, that is a bug that is to be fixed.
For `Show structure`, I'm not sure about why we removed it (not familiar with it), will have to discuss this with the @galaxyproject/wg-uiux team

**Comment by dannon** [comment]
Show structure was removed in https://github.com/galaxyproject/galaxy/issues/15742 and will be revisited in the context of the history graph view that's on the roadmap and will be first implemented in the context of individual workflow invocations.
