### ISSUE TITLE
Ability to save invalid workflow

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#15753]
Given that right now we've got some issues with determining the right map over status of a workflow step you sometimes end up with what the editor thinks are invalid connections. We should, after a warning, allow users to attempt to save the workflow anyway.

**Comment by nsoranzo** [comment]
ref. https://github.com/galaxyproject/galaxy/pull/15357#issuecomment-1410690388 ;)

**Comment by wm75** [comment]
@ElectronicBlueberry this might be another case where your UI skills would be more than welcome :)
Currently the workflow editor highlights connections that it *thinks* are invalid *and* disables the save button. A preferable approach for now might be to have a pop-up on pressing the save button saying sth like: "A potential problem has been detected with this WF. Are you sure you want to save it in this state?"

**Comment by wm75** [comment]
If it helps, here's a public WF from .eu that demonstrates the problem: https://usegalaxy.eu/published/workflow?id=4fdbf53ba08ca927

**Comment by mvdbeek** [comment]
I can take this one since that'll help debugging the actual issue, let me know though if you already got something for this @ElectronicBlueberry
