### ISSUE TITLE
History export no longer includes a link which can easily be used to transfer between servers

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#15752]
Regression reported by @nomadscientist, the new history export (which we all agree is fantastic!) does not expose the download link.

Some users previously used this to transfer histories between servers, as you could generate that link, and copy it into the history import of another server, without the expensive overhead of downloading said history to your local, potentially flaky internet connection, instead allowing the server2server transfer which generally happened over more reliable connections.

If it is possible to just expose the URL this would solve that. (Assuming that URL does not require authentication).

**Comment by davelopez** [comment]
Sorry for overnighting this, is https://github.com/galaxyproject/galaxy/pull/15758 intuitive enough for getting this link? Any other UX suggestions are welcome.

**Comment by hexylena** [comment]
overnighting? there is no rush, please don't worry! No that honestly looks great! @nomadscientist any opinions?

**Comment by davelopez** [comment]
I will close this as completed in https://github.com/galaxyproject/galaxy/pull/15758, please feel free to reopen it if needs more clarification. Also, please notice that you can import histories packaged as .zip archives only on servers with version >= 23.0
