### ISSUE TITLE
Clicking "Show Deleted" again does not toggle the filter off

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#15805]
do I have to clear the search in the history search? I expected to again click "show deleted" and instead it would toggle but maybe that's the wrong expectation based on the old history (which toggled show/hide deleted)

**Comment by dannon** [comment]
Basic pass done in #15810; we can make more improvements by tying the filtering model to these icons and allowing granular combinations in dev.

**Comment by hexylena** [comment]
Thanks @dannon!
