### ISSUE TITLE
Same size 'Run Tool' buttons

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#15819]
The floating tool bar with the *Run Tool* button is wonderful and this could be just me but given the two buttons perform the same action, for consistency and implied behavior of "we both do the same thing", I feel it would be better if both buttons were the same size. 

![image](https://user-images.githubusercontent.com/338642/225909317-81b9c4b3-0256-4eef-9b3f-0d595097d0e4.png)

**Comment by guerler** [comment]
Discussed this during our UI meeting and concluded that the sizes of the buttons are consistent with regard their location. The regular button at the bottom is used in many other forms e.g. when creating a workflow, or pages etc., so reducing its size is not favorable. The only other option would have been to increase the size of the button in the header, but that would have the consequence that the height of headers and all drop-downs contained within them would need to be increased also throughout the application. When weighing in these options, most favored to leave the button dimensions as they are, i.e. regular buttons for the bottom, and small buttons for the header bar. However, we can keep this request in mind and revisit this if we come up with a better solution down the road. Thank you for having pointed out this issue.
