### ISSUE TITLE
Nice to have: Hide regular "login/password" fields when login is setup with external (oidc, etc)

### ISSUE THREAD

**Issue by carolg** [galaxyproject/galaxy#15836]
Hi,

I could not find a way to set the Galaxy config so it does not show the regular login name / passwords fields. Is it possible to set this in the config file ?

Since we are starting we want to have a clean slate and force all users to go through CILogon.

Thanks,

**Comment by carolg** [comment]
Precision:
It could be a setting in the Galaxy config for example hide_login_password_fields

**Comment by mvdbeek** [comment]
Hi @carolg, if you remove the password authentication you will not see the username / password login, see https://github.com/galaxyproject/galaxy/issues/13592#issuecomment-1090325415

**Comment by carolg** [comment]
Hi @mvdbeek I mplemented the solution #13592 in my playbook. What it does is redirecting the user directly to CIlogon.
What I would like is to show the login page without seeing this section
![Screenshot_20230331_172151](https://user-images.githubusercontent.com/2634774/229234305-58ff6c24-1f4d-4e0b-9a50-e2783780cebc.png)
And add some specific information to the users prior to send them to CILogon
Is that possible?
Thanks
