### ISSUE TITLE
Published Histories filter-search does not include Annotation

### ISSUE THREAD

**Issue by hujambo-dunia** [galaxyproject/galaxy#15831]
On the Published Histories Page, the placeholder text says `Search name, annotation and tags` but text-search by Annotation does not work. To fix, either remove that "annotation" is searchable in the placeholder text or make "annotation" searchable in the filter method(s).
<img width="440" alt="Greenshot 2023-03-20 17 01 48" src="https://user-images.githubusercontent.com/3672779/226465097-8a1ea8e1-8a61-4c7a-a826-66ebcd1c9d8b.png">

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Go to Published Histories Page (on local: http://127.0.0.1:8081/histories/list_published) ([how to create those records here](https://training.galaxyproject.org/training-material/faqs/galaxy/histories_sharing.html))
3. In the search field, search for text in the Annotation column
4. Should return no results

**Expected behavior**
User should see results matched in Annotation field similar to how Name field is searchable.

**Screenshots**
<img width="444" alt="Greenshot 2023-03-20 17 05 45" src="https://user-images.githubusercontent.com/3672779/226465805-db2fc735-d1e8-4b0d-aee6-acdcf8b90093.png">

**Additional context**

**Comment by dannon** [comment]
xref https://github.com/galaxyproject/galaxy/pull/14985

**Comment by davelopez** [comment]
https://github.com/galaxyproject/galaxy/pull/15897 makes the annotation filtering case insensitive in the backend but please note that you need to use `annotation:something` to search for annotation contents, if you just write `something` in the search box it will be by default a search by name (`name:something`).

@itisAliRH is this the expected behavior or should it use the same term `something` for the 3 attributes (name, annotation, and tag) when you just write in the search box without specifying a tagged search?

**Comment by itisAliRH** [comment]
> #15897 makes the annotation filtering case insensitive in the backend but please note that you need to use `annotation:something` to search for annotation contents, if you just write `something` in the search box it will be by default a search by name (`name:something`).
> 
> @itisAliRH is this the expected behavior or should it use the same term `something` for the 3 attributes (name, annotation, and tag) when you just write in the search box without specifying a tagged search?

@davelopez I believe the placeholder is confusing. 'something' is equal to 'name:something' and not searching for annotation and tags.

**Comment by davelopez** [comment]
So, should we change the placeholder message to something like `Search by name or use the advanced filtering panel`?

**Comment by davelopez** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/15897 and https://github.com/galaxyproject/galaxy/pull/16006
