### ISSUE TITLE
Jupyter broken on Main, iPython broken on Main and Test

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1584]
Main Jupyter: 
`GET https://usegalaxy.org/gie_proxy/ipython/notebooks/ipython_galaxy_notebook.ipynb 502 (Bad Gateway)`

It is unclear how we (the team) should maintain it, how to take care of the proxy, how to restart it when update is made etc. Some short deployment writeup would be much appreciated.

ping @natefoo

**Comment by bgruening** [comment]
@martenson how can I help? Can you look at the proxy logs?

**Comment by martenson** [comment]
@bgruening I can look around, but I do not know where they are

**Comment by bgruening** [comment]
@martenson try under /var/log/supervisord/ hopefully there is something called like nodejs_proxy

**Comment by martenson** [comment]
@bgruening 

logs are from Main (https://github.com/galaxyproject/galaxy/commit/e397ebba585ed578798645ee9352b891e3055372) and probably for Jupyter request
/srv/galaxy/main/log/gie_proxy-access.log:

```
PROXY GET /gie_proxy/ipython/notebooks/ipython_galaxy_notebook.ipynb to iedocker.galaxyproject.org:34892
Proxy error:  { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
PROXY GET /gie_proxy/ipython/notebooks/ipython_galaxy_notebook.ipynb to iedocker.galaxyproject.org:34892
Proxy error:  { [Error: connect ECONNREFUSED]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect' }
```

/srv/galaxy/main/log/gie_proxy-error.log

```
/srv/galaxy/main/interactive_environments/proxy/lib/proxy.js:122
        res.setHeader('Access-Control-Allow-Origin', origin);
            ^
TypeError: Object #<Socket> has no method 'setHeader'
    at Socket.res.writeHead (/srv/galaxy/main/interactive_environments/proxy/lib/proxy.js:122:13)
    at /srv/galaxy/main/interactive_environments/proxy/lib/proxy.js:130:13
    at ClientRequest.onOutgoingError (/srv/galaxy/main/interactive_environments/proxy/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:123:9)
    at ClientRequest.emit (events.js:95:17)
    at Socket.socketErrorListener (http.js:1552:9)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:442:13)
```

**Comment by martenson** [comment]
Jupyter works on Main unless you start it on .ipynb

**Comment by bgruening** [comment]
@martenson is this now fixed?

**Comment by martenson** [comment]
@bgruening No, it is not. I cannot open ipynb in Main

**Comment by bgruening** [comment]
For some reason I can ...

**Comment by martenson** [comment]
```
GET https://usegalaxy.org/gie_proxy/ipython/login?next=%2Fgie_proxy%2Fipython%2Ftree
 502 (Bad Gateway)
```

**Comment by martenson** [comment]
after some attempts of clearing cache normally the thing that helped was to open chrome devtools, press and hold the refresh button and do `empty cache and hard reload`
now it works
