### ISSUE TITLE
Collection upload creates duplicate HDAs

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#15857]
**Describe the bug**

https://user-images.githubusercontent.com/25689525/228185942-ca1dbc28-5a17-4674-a07f-43e24c92316e.mp4

I noted the offset in the dataset indices (5-8 were missing) .. apparently those are created as additional hidden elements.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: I guess 23.0

**To Reproduce**

See video

**Expected behavior**

Probably: no extra hidden elements?

**Comment by mvdbeek** [comment]
That's how it has to work, otherwise you can delete HDAs outside of the collection and destroy collection data that way.
