### ISSUE TITLE
IE UX improvements

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1586]
- provide a clear 'shutdown' button for IEs
- make the Jupyter tooltip  readable (it is too long for default width of history panel)
  ![screenshot 2016-01-26 12 35 49](https://cloud.githubusercontent.com/assets/1814954/12588976/6a62820e-c429-11e5-8643-db82619c0471.png)
- provide a way to start Jupyter without interacting with a dataset

**Comment by hexylena** [comment]
@martenson please merge into #372

**Comment by hexylena** [comment]
- make the Jupyter tooltip readable (it is too long for default width of history panel)
- provide a way to start Jupyter without interacting with a dataset

These two will BOTH be fixed by #1403

**Comment by hexylena** [comment]
Merged myself, closing in favour of #372

**Comment by martenson** [comment]
thanks @erasche
