### ISSUE TITLE
Galaxy breaks with /user URL

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#1587]
Usecase: User wants to return to the login page and edits their URL manually, guided in part by their browser's URL completion.

Both https://usegalaxy.org/user and https://usegalaxy.org/user/ both fail with:

```
Internal Server Error
Galaxy was unable to successfully complete your request
```

Likewise on our local Galaxy, running the dev branch `http://ourserver/galaxy-dev/user` fails:

```
WebError Traceback:
⇝ TypeError: index() takes exactly 3 arguments (2 given)
View as:   Interactive  |  Text  |  XML (full)
URL: http://ourserver/galaxy-dev/user
Module weberror.evalexception:431 in respond         view
>>  app_iter = self.application(environ, detect_start_response)
Module paste.recursive:85 in __call__         view
>>  return self.application(environ, start_response)
Module paste.httpexceptions:640 in __call__         view
>>  return self.application(environ, start_response)
Module galaxy.web.framework.base:126 in __call__         view
>>  return self.handle_request( environ, start_response )
Module galaxy.web.framework.base:184 in handle_request         view
>>  body = method( trans, **kwargs )
TypeError: index() takes exactly 3 arguments (2 given)
Extra Features
>>  Display the lines of code near each part of the traceback
    Show a debug prompt to allow you to directly debug the code at the traceback
```

However, with the trailing slash `http://ourserver/galaxy-dev/user/` redirected to `http://ourserver/galaxy-dev/user/login?use_panels=True&redirect=%2Fgalaxy-dev%2Fuser%2F` giving a login prompt.

**Comment by carlfeberhard** [comment]
Looks like this was borked _at least_ back to 15.07 (didn't check further): lack of a default 'cntrller' would throw.  This url/route probably was only used in the center panel and via an iframe but I'd still consider this broken.

Thanks for the catch, @peterjc
