### ISSUE TITLE
Name tags seem to not be displaying on collections on 23.0 / .org

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#15878]
I have not reproduced this anywhere else yet since EU was having issues but here's the problem. I created a collection with the rule builder, and from the dataset information we see multiple name tags applied

```
request_json | {"targets": [{"destination": {"type": "hdca",  "object_id": 2006930}, "collection_type": "list:paired", "name":  "PRJNA128733", "elements": [{"name": "SRR057629", "collection_type":  "paired", "elements": [{"name": "forward", "dbkey": "hg38", "ext":  "auto", "tags": ["name:carcinoma_C02", "name:GSM554076"], "src": "url",  "url":  "ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR057/SRR057629/SRR057629_1.fastq.gz",  "hashes": [], "in_place": false, "purge_source": false}, {"name":  "reverse", "dbkey": "hg38", "ext": "auto", "tags":  ["name:carcinoma_C02", "name:GSM554076"], "src": "url", "url":  "ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR057/SRR057629/SRR057629_2.fastq.gz",  "hashes": [], "in_place": false, "purge_source": false}]},
```

which looks great. But they're not rendered in most useful views:

`list` doesn't show them | `paired` doesn't show them | individual elements also don't | but show hidden shows everything
--- | --- | --- | ---
![image](https://user-images.githubusercontent.com/458683/229059962-c4e9309a-b802-42f3-85b8-9e5ff6f35c8d.png)| ![image](https://user-images.githubusercontent.com/458683/229060060-b86d0682-32e2-4414-bb2d-ffbf82f74928.png) | ![image](https://user-images.githubusercontent.com/458683/229060121-6e7b6d80-6c90-467d-af32-f74b3729bbc4.png) | ![image](https://user-images.githubusercontent.com/458683/229064781-2337e5cc-cd0c-4032-a185-517327c32f8e.png)

**Comment by hexylena** [comment]
I could have sworn the old implementation tags 'bubbled' up to be present on the top level element, meaning tagging leafs would still result in the base element showing them, but there's a chance I'm mis-remembering that and not worth spinning up an environment to check. **If** that was how it worked, it was 'wrong' especially if you can tag a parent element of a collection, but I think I used it for get a feeling for which datasets were inside without having to browse it.

But ok, thanks for https://github.com/galaxyproject/galaxy/pull/15883, let's say that solves this.

**Comment by mvdbeek** [comment]
I don't remember exactly how it all worked in the old history. There are still cases where tags can bubble up, which is when you reduce child elements. All the tags of the children should appear on the reduced output (in the tumor/normal setting with the funky side-effect of tumor and normal tags when you mask background mutations ... ). We could also do what you describe, but there's a cost to doing arbitrary depth lookups for tags in the summary view that the history requests, I'm not sure which way to go there.

**Comment by hexylena** [comment]
It makes sense, the abritrary depth lookups are not ideal, especially for large collections I'm not sure it'd be useful. And you'd probably want a way to distinguish parent from child tags at that point which is extra UI we don't want or need as it's already complex enough.
