### ISSUE TITLE
Looking for simple DRMAA configuration (job_conf.xml)

### ISSUE THREAD

**Issue by caldodge** [galaxyproject/galaxy#15889]
My apologies if this is the wrong forum for this request.
We have a Galaxy server, and are trying to set it up to use DRMAA to submit jobs.
We've installed slurm-drmaa, and verified that it works for job submission.
So we're looking for a simple job_conf.xml configuration to start with.  The server does NOT use ansible, so ansible recipes are useless to us.
Can anyone provide a simple job_conf.xml example which can be tested (and expanded), using DRMAA for apps?

**Comment by mvdbeek** [comment]
Hi @caldodge, there are examples and explanations in https://docs.galaxyproject.org/en/master/admin/cluster.html#drmaa. For more specific options see https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/job_conf.xml.sample_advanced.

If you have more questions https://help.galaxyproject.org/ or https://matrix.to/#/#galaxyproject_admins:gitter.im are good places to ask.
