### ISSUE TITLE
Using packaging version <22  starts to conflict with other dependencies

### ISSUE THREAD

**Issue by fabianegli** [galaxyproject/galaxy#15898]
The world moves on and packaging <22 as defined in the pyproject.toml dependencies starts being incompatible with some of the packages that might be used in concert with galaxy tool util. The reason why it was restricted is that LegacyVersion was dropped in packaging 22 and is used here to parse package versions which are not SemVer versions. However, there might be a path to resolve this issue by using [packaging.version.parse](https://packaging.pypa.io/en/latest/version/#packaging.version.parse) instead as already mentioned in 

> > Right ... where possible we should probably use https://packaging.pypa.io/en/latest/version/#packaging.version.parse to construct the version.
> 
> IIRC that would allow alpha, beta and similar suffixes to sort lower than the release version.

_Originally posted by @mvdbeek in https://github.com/galaxyproject/galaxy/issues/5408#issuecomment-361363898_

**Comment by fabianegli** [comment]
Alternatively, You could just distribute the code for LegacyVersion, as it is licensed under MIT as well. For reference: https://github.com/pypa/packaging/issues/530#issuecomment-1362592132

**Comment by mvdbeek** [comment]
> Originally posted by @mvdbeek in [#5408 (comment)](https://github.com/galaxyproject/galaxy/issues/5408#issuecomment-361363898)

we've been doing that for years and if course that doesn't help with `LegacyVersion` being dropped.

the second suggestion seems fine, can you open a PR ? you'd probably also need to wrap `parse_verison`

**Comment by nsoranzo** [comment]
See also https://github.com/galaxyproject/galaxy/pull/13570 .

**Comment by fabianegli** [comment]
I am not currently in a position to work on this, if anyone else feels like it, please feel free to have at it.
