### ISSUE TITLE
Any user can view the Admin Panel (but cannot access any functionality)

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#15904]
**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0

**To Reproduce**
1. As an anonymous or regular use go to `https://<galaxy_instance>/admin`
2. You can see the Admin panel

**Expected behavior**
The admin panel should only be seen by Admins and other users should be redirected or given an appropriate message.

**Comment by dannon** [comment]
Fixed in #15906
