### ISSUE TITLE
ScIdx sniffer issue

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1590]
Okay, just downloaded a fresh copy of dev and could reproduce it (so nothing to do with my environment... I think).

This, obviously fasta, fasta file is detected as scidx:

```
>asdf
AGGTT
```

While this one is detected as fasta:

```
>asdf
AGG
TT
```

I've labeled it as bug as I could reproduce in a clean environment, but I'd appreciate it if someone else could confirm.

**Comment by jmchilton** [comment]
This has been fixed in release and just not merged into dev, can you try release_16.01.

**Comment by hexylena** [comment]
Yep, fixed in release_16.01. Sorry, not used to things every not being in dev.

**Comment by gregvonkuster** [comment]
Sorry for causing this for you guys!  :(

**Comment by hexylena** [comment]
@gregvonkuster nah not a problem! Just unfortunate that it hadn't been in dev, hence my surprise.

**Comment by jmchilton** [comment]
Just to echo @erasche - this isn't a big deal. The real problem wasn't the sniffer so much as the lack of testing - that should be corrected with https://github.com/galaxyproject/galaxy/pull/1556. After that is merged - we will test the default datatype configuration and ensure problems like this no longer occur.

**Comment by hexylena** [comment]
Should be fixed by #1591
