### ISSUE TITLE
Published Histories Bugs

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#15917]
Spotted a few bugs with the `/histories/list_published` view:

### 1. In a shared history (only in the case where it's owned by another user), Collections are blank on expand
  
https://user-images.githubusercontent.com/78516064/230680826-b003b05d-54f0-4d64-90c1-0a31331be1ab.mov

### 2. Just viewing an external shared history adds it to the current user's history switch menu (even without importing it). 
**This is temporary until the state refreshes**. When that history is available in the switch history menu, the current user (only if they are an admin) can modify the history, make deletions and changes (even delete the whole history), affecting the external user's actual history.

https://user-images.githubusercontent.com/78516064/230681266-266083c1-02b7-49a0-86b0-ba47bfdd0166.mov

### 3. Importing a new history doesn't potentially set it as current history on server (reported by @natefoo in @galaxyproject/wg-uiux chat)

---

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0 and dev

**To Reproduce**
_Replicate steps in screencasts above_

**Expected behavior** (corresponding to bugs numbered above)
1. User should be able to see collection contents in an external, shared/published history.
2. The external history should not be available in the Switch to History modal.
3. Imported history must also be set as current on the server.

**Comment by hexylena** [comment]
Just encountered the first one, the error message is

```
{"err_msg":"History is not owned by user","err_code":403003}
```

in the console if it helps whoever fixes this.
