### ISSUE TITLE
Expression tools cannot be found by the front-end search

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/galaxy#15932]
**Describe the bug**
Expression tools cannot be found by the front-end search. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0 (.eu), 23.0 (.org) 

**To Reproduce**
1. Go to the workflow editor.
2. Search an expression tool (e.g. Compose text parameter value)
3. It will not show up

**Expected behavior**
Although only a few tools, they should show up in the search.

**Screenshot
![Selection_003](https://user-images.githubusercontent.com/22075451/231730217-ff2f503e-e52a-4a33-920e-c15009221093.png)
creenshots**

**Comment by ahmedhamidawan** [comment]
Fixed in #16022
