### ISSUE TITLE
Set the default filter of Paired List Collection Creator as a galaxy parameter

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#15937]
Hi,
Would be great if the default filter (currently illumina) could be set as a parameter in the yaml galaxy. Here is where it is currently defined:
https://github.com/galaxyproject/galaxy/blob/e33604300236981daa21d8075e553da6527c0308/client/src/components/Collections/PairedListCollectionCreator.vue#L634
Thank you.

**Comment by mvdbeek** [comment]
We've changed this now so that the filter with most matches is being selected as the initial filter. I hope that covers your usecase @lldelisle!

**Comment by lldelisle** [comment]
@mvdbeek you're my heroe

**Comment by mvdbeek** [comment]
haha, that would be @assuntad23! :)

**Comment by lldelisle** [comment]
Then @assuntad23 , you're my heroe.
