### ISSUE TITLE
Show Histories Side-by-Side: counter/size can be stale in the initial view

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#15948]
**Describe the bug**
Show Histories Side-by-Side: dataset counter and history size values can be empty.

Doesn't matter if the selected histories include the currently active history or not. Or how many histories are selected. Or if a history had any changes (new data, metadata updates, etc).

Instead, seems to depend on _when a history was last active_. Recent active histories == ok. "Older" histories (not loaded as active in as little as two days ago? or since whenever you last logged into Galaxy? or when last restarted your browser?) = not updated in this view for some reason. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy version 23.0.1.dev0, commit [a1bdffa43f5f23769dc32d33909cc4631aa01ca5](https://github.com/galaxyproject/galaxy/commit/a1bdffa43f5f23769dc32d33909cc4631aa01ca5)

**To Reproduce**
1. Go to UseGalaxy.org and log in.
2. Use the function 'History -> Show Histories Side-by-Side'
4. Click on 'Select histories'
5. Choose at least one history that has not been an active history for a few days.
6. 'Switch' to a history that is missing counter/size. Will refresh the 'Side-by-Side' view to match what is loaded into the right history panel.

**Expected behavior**
Update the counter and size when selecting a history to 'Show Histories Side-by-Side', regardless of when that history was last an active history. 

**Screenshots**

Before/after

**Initial view.** The second history is missing correct counter/size values.

<img width="1258" alt="Screen Shot 2023-04-17 at 11 32 38 AM" src="https://user-images.githubusercontent.com/8999735/232586418-829bd775-61ad-44c0-9953-7bcffc7aa4d1.png">

**Switching** to that second history updates those values.

<img width="1259" alt="Screen Shot 2023-04-17 at 11 36 10 AM" src="https://user-images.githubusercontent.com/8999735/232586414-55245d7a-f49d-424e-879b-9f24c0aa3d3f.png">

**Additional context**
Not sure if this was caught in another ticket or not.

**Comment by dannon** [comment]
This should be resolved.  Please reopen if seen again.
