### ISSUE TITLE
TRS import should probably ignore items in localhost/etc.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#15959]
I think I added something for this years ago (fetch_url_allowlist??) we should probably block binding to anything in localhost, anything resolving to 127.0.0.1/8, and maybe any class a/b/c network addresses. (Ah thanks @natefoo for finding it in lib/galaxy/files/uris.py, `validate_non_local`)

This is less of a problem than it was for the upload tool since it needs to parse as TRS or an exception is thrown, but, still probably not ideal.

**Comment by mvdbeek** [comment]
That's done now
