### ISSUE TITLE
"Export to BCO" internal server error 500

### ISSUE THREAD

**Issue by agbiotec** [galaxyproject/galaxy#15961]
At https://usegalaxy.org/ public server, 

the "Export to BCO" for completed workflow invocations returns internal server error 500.

For example this internal server error is observed with
workflow with invocation id# 7de4365c4cae6031 has been successfully completed (all green), 
that puts data on history id# 643ea0e16359e250 where all the jobs have been successfully completed.

Screenshots of these on links attached. I believe there was a problem with the "Export to BCO" tool 2-3 weeks back, which was fixed, and in fact I was able to use it to export a BCO successfully for a workflow before it seems to have broken again.

Thank you
![screenshot-3](https://user-images.githubusercontent.com/46310/233122861-2798e398-a899-49f0-a694-21a6beef9511.JPG)
![screenshot-2](https://user-images.githubusercontent.com/46310/233122873-05cf3ec3-1a56-4c55-bb22-8bbc21e7dbba.JPG)
![screenshot-1](https://user-images.githubusercontent.com/46310/233122875-95831e09-d58b-4389-a07b-ef0aef3a9c78.JPG)

**Comment by martenson** [comment]
related [sentry item](https://sentry.galaxyproject.org/organizations/galaxy/issues/108414/events/dab8eb86d26a4439afe8e0beab9e8052/) and trace for this seems to be 

```
 File "galaxy/webapps/galaxy/api/workflows.py", line 1487, in download_invocation_bco
    bco = self._deprecated_generate_bco(trans, invocation_id, merge_history_metadata)
  File "galaxy/webapps/galaxy/api/workflows.py", line 1506, in _deprecated_generate_bco
    return self.invocations_service.deprecated_generate_invocation_bco(trans, invocation_id, export_options)
  File "galaxy/webapps/galaxy/services/invocations.py", line 235, in deprecated_generate_invocation_bco
    export_target.seek(0)
  File "galaxy/model/store/__init__.py", line 2364, in __exit__
    self._finalize()
  File "galaxy/model/store/__init__.py", line 2517, in _finalize
    super()._finalize()
  File "galaxy/model/store/__init__.py", line 2347, in _finalize
    self.app.workflow_contents_manager.store_workflow_artifacts(
  File "galaxy/managers/workflows.py", line 853, in store_workflow_artifacts
    self.app.workflow_contents_manager.store_workflow_to_path(path, workflow.stored_workflow, workflow, **kwd)
  File "galaxy/managers/workflows.py", line 873, in store_workflow_to_path
    abstract_dict = from_dict(wf_dict)
  File "gxformat2/abstract.py", line 32, in from_dict
    normalized_workflow = NormalizedWorkflow(workflow_dict)
  File "gxformat2/normalize.py", line 84, in __init__
    normalized_workflow["inputs"] = inputs_as_normalized_steps(normalized_workflow)
  File "gxformat2/model.py", line 94, in inputs_as_normalized_steps
    for input_def_raw in with_step_ids(inputs):
  File "gxformat2/model.py", line 43, in with_step_ids
    assert step["id"] is not None
```

**Comment by bioitx** [comment]
Hello and thank you for looking into this, I really appreciate your time! I was wondering if there are any updates with fixing the issue ?

Best regards

**Comment by mvdbeek** [comment]
That'll be fixed by https://github.com/galaxyproject/galaxy/pull/16081

**Comment by agbiotec** [comment]
My apologies to bother again, and I really appreciate the effort and pointers to the code for fixing this bug !

Would you know the fix was applied on usegalaxy.org, if not, when would it be rolled out on the public Galaxy ?

Thank you
