### ISSUE TITLE
Reports: clicking on individual jobs in reports generates "failed to connect"

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#15966]
It works fine (lettting me see tables of information, failed jobs, etc.) But as soon as I click on a single job, it fails to connect:

![Screenshot_2023-04-20_10-47-32](https://user-images.githubusercontent.com/458683/233312435-e54399c4-11d0-4c87-be2c-95d513e995d9.png)

because it's connecting to 'localhost' rather than the proper hostname (gat-7)
https://gat-7.eu.galaxy.training/reports/

**Comment by hujambo-dunia** [comment]
Thanks @davelopez for your assistance looking into getting the Reports Admin configuration file loading.

**Comment by davelopez** [comment]
We discussed this in the backend meeting and decided that the reports app is in very low maintenance mode, so this will have little priority and probably won't be fixed soon.

**Comment by hexylena** [comment]
so reports will be unusable for the foreseeable future then, ok. Should we disable the training material? add a big warning box?

we see people accessing it semi regularly, and admins tend to still like setting it up because the grafana stack doesn't do all the same things and is significantly more complex.

**Comment by hexylena** [comment]
oh, of course, I understand. Just wondering how y'all would prefer we handle it on the training side, since that's the primary entrypoint for folks into trying to use reports.

**Comment by mvdbeek** [comment]
It should still work fine without proxy prefix, so a subdomain is a more robust solution (true for Galaxy as well ... but there it's worth spending the effort to fix it) .

**Comment by martenson** [comment]
wait what, why did a different org/repo fix closed this issue, this is confusing to say the least :D
