### ISSUE TITLE
RO-Crate export fails for workflow invocations with a list of pairs collection

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#15968]
**Describe the bug**
When trying to export a workflow invocation for a WF making use of a list:paired collection, Galaxy responds with
`{"err_msg":"Unknown error: 'list:paired'","err_code":500001}` at end points like `https://usegalaxy.eu/api/short_term_storage/******`

My guess is that this is because of list:paired not being a key in

https://github.com/galaxyproject/galaxy/blob/19a4426abb8e304bab22e8559c6dfaf57f59ad90/lib/galaxy/model/store/ro_crate_utils.py#L49

but I might be wrong, of course.

If that's the right place, then likely a list:list would also cause trouble?

**Comment by jdavcs** [comment]
Fixed via #15971
