### ISSUE TITLE
History export interface has too many download buttons

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#15989]
In the rest of the interface they imply this is the primary action (like running a tool), but in this interface I find myself clicking on "Direct download" expecting things to start, until I realize it's a tab:

<img width="685" alt="Screenshot 2023-04-24 at 18 05 22" src="https://user-images.githubusercontent.com/6804901/234053760-528d6b49-d709-4bd8-a379-7caf719bce19.png">

Bonus points for exchanging the history id with the history name.

**Comment by davelopez** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/15991
