### ISSUE TITLE
Tools producing output dataset collections do not retain the input's dbkey

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#1598]
The populate_collection_elements() function in ~/lib/galaxy/tools/parameters/output_collect.py looks for a match on dbkey from the <discover_datasets> tag set, and if there is no match the default dbkey value “?” is associated with the output dataset in the collection.  An example tool that results in this behavior has this tag set:

```
   <collection name="MP" type="list" label="Data MP: ${tool.name} on ${on_string}">
       <discover_datasets pattern="(?P&lt;designation&gt;.*)" directory="data_MP" ext="gff" visible="false" />
   </collection>
```

I’ve not found an example anywhere in the Galaxy code or in tools that have been written to produce output collections that includes a dbkey designation in the <discover_datasets> tag set, so I’m wondering if I am correctly understanding the intent of this code.

I have a work-around fix that works without adding a dbkey designation to the tag set.  The caller of the populate_collection_elements() function is a function named collect_dynamic_collections(), whose signature includes the input datasets from which the dbkey can be retained.

I can submit a PR that includes this approach to a fix, but if the fix is as simple as adding some kind of dbkey designation to the tag set, an example of what that should look like would be much appreciated.

Thanks very much!

Greg Von Kuster

**Comment by jmchilton** [comment]
This is largely legacy cruft from the older style that encoded all this in dataset name. I was not actually aware the dbkey was automatically pass through for normal operations without a `metadata_source` tag. Let me take a look at a fix - if you don't hear from me today (I get distracted easily) maybe spend some more time and open a PR.

**Comment by gregvonkuster** [comment]
Ok thanks!

**Comment by jmchilton** [comment]
@gregvonkuster Any chance you can give #1610 a try and let me know if it fixes the problem?

**Comment by gregvonkuster** [comment]
Sure, just a sec...

**Comment by gregvonkuster** [comment]
@jmchilton This worked for me - thanks for the fix!
