### ISSUE TITLE
`galaxy-app` PyPI package outdated

### ISSUE THREAD

**Issue by domgz** [galaxyproject/galaxy#15999]
**Describe the bug**

The [`galaxy-app` package on PyPI](https://pypi.org/project/galaxy-app/22.1.1/) is outdated. Other packages, such as [Total Perspective Vortex](https://github.com/galaxyproject/total-perspective-vortex/blob/e85243a085e44aedcfc90961f7b164f9216661ce/setup.py#L27) depend on this package.

**Galaxy Version and/or server at which you observed the bug**

Galaxy Version: 22.05, v22.05.1.dev0, v23.0
Commit: [36f0494](https://github.com/galaxyproject/galaxy/commit/36f049410bd12d585df9e36ecb56f0099933188b), [88a986c](https://github.com/galaxyproject/galaxy/commit/88a986c578000ef9296c601743259abfa210ae81), [9503663](https://github.com/galaxyproject/galaxy/commit/95036639dd4f7bd986e93acc99d5dd1be7823286).

**To Reproduce**
1. Visit https://pypi.org/project/galaxy-app/#history

**Expected behavior**
A `galaxy-app` package exists for all recent versions of Galaxy.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/43052541/234500865-8490d94a-3f01-42e0-98ea-ef0d17842302.png)

**Additional context**
\-\-\-

**Comment by mvdbeek** [comment]
That's only needed for tpv tests.

**Comment by kysrpex** [comment]
> This is done now, we're in a good position to create regular point releases.

Thanks, I will definitely take advantage of this in CI workflows :)
