### ISSUE TITLE
Tool link in tutorial does not always work

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#16002]
**Describe the bug**
When you are following a tutorial from the GTN and you click on the tool link you do not always get to the tool page:
- If you are in a multiple history view
- If you are previewing a dataset
- If you are checking the details of a dataset

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: {"version_major":"23.0","version_minor":"1.dev0"}
usegalaxy.eu

**To Reproduce**
1. Go to a history
2. Click on preview, for example: https://usegalaxy.eu/datasets/4838ba20a6d867656f932fd4d0aad330/preview
3. Open a tutorial
4. Click on a tool link (for example filter)
5. The url is now: https://usegalaxy.eu/datasets/4838ba20a6d867656f932fd4d0aad330/preview?tool_id=Filter1 but the screen does not change.

**Expected behavior**
I would expect it to be: https://usegalaxy.eu/?tool_id=Filter1 and see the tool form

If you need anything else, please ask

**Comment by dannon** [comment]
@lldelisle Thanks for making an issue for this, I encountered it as well and will get a fix out.

**Comment by dannon** [comment]
Will be fixed as a part of https://github.com/galaxyproject/galaxy/pull/15684

**Comment by lldelisle** [comment]
Thanks

**Comment by dannon** [comment]
Should be resolved in 23.0 now, thanks again for the report!
