### ISSUE TITLE
Console error trying to inspect vuex

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#16018]
**Describe the bug**
Getting a console error message when trying to inspect changes in Vuex in **Chrome** like so:

https://user-images.githubusercontent.com/78516064/235246385-a39b2b02-e9d1-47c6-bd2a-6f70f44bf307.mov

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: dev
Commit: 701415f634320f080b3890ee49b7d4fa17585953

**To Reproduce**
1. Go to '_the chrome Vue Devtools inspect panel_'
2. Click on 'Vuex'
3. Check console
4. See error:
   ![image](https://user-images.githubusercontent.com/78516064/235247542-c483fd86-6b76-4e08-9aca-587f46ad8c7d.png)

**Error:**
```
 An error occurred in hook 'getInspectorState' registered by plugin 'org.vuejs.vue2-internal' with payload: {inspectorId: 'vue2-vuex-inspector', app: Vue, nodeId: 'history[vdt]', state: null}

Error: Missing module "history" for path "history[vdt]".
    at backend.js:5863:13
    at Array.reduce (<anonymous>)
    at getStoreModule (backend.js:5859:16)
    at backend.js:5461:26
    at handler (backend.js:725:16)
    at DevtoolsHookable.callHandlers (backend.js:746:17)
    at async DevtoolsApi.callHook (backend.js:230:17)
    at async DevtoolsApi.getInspectorState (backend.js:445:21)
    at async sendInspectorState (backend.js:2644:44)
```

**Comment by itisAliRH** [comment]
It can be a browser/extension issue that it's not using the latest store configuration every time in development mode. Removing and reinstalling the `Vue.js Devtools` extension will fix it.

**Comment by dannon** [comment]
Stale cache in devtools plugin; nothing to fix on teh Galaxy side.
