### ISSUE TITLE
Wrong links after setting up 22.05 with prefix

### ISSUE THREAD

**Issue by methylome** [galaxyproject/galaxy#16030]
**Describe the bug**
1. Links to the file contents on dataset detail view and visualization tools are linked without the prefix, 
e.g., for /galaxy_22_05/api/datasets/0b315e5903cfa7d8/display?to_ext=bed
/api/histories/9a03487f5b36d8c9/contents/0b315e5903cfa7d8/display
/display_application/0b315e5903cfa7d8/igb_bed/View

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: {"version_major":"22.05","version_minor":"1"}
Commit: f420a619e4dcb4aa73c693086dbb03869eb0ca8f

galaxy.xml
```
gravity:
    ...
    gunicorn:
        bind: unix:/galaxy_22_05/var/config/gunicorn.sock
        extra_args: --forwarded-allow-ips="*"
   ...
galaxy:
   ...
    galaxy_url_prefix: /galaxy_22_05
   ...
```

**Comment by mvdbeek** [comment]
Could you tell us where you're seeing those links being generated in the user interface ?

**Comment by methylome** [comment]
@mvdbeek ,

Sorry for a delayed response. I saw the links in Dataset Information and Visualize.
