### ISSUE TITLE
NGINX configuration with the prefix using upstream

### ISSUE THREAD

**Issue by methylome** [galaxyproject/galaxy#16032]
**Describe the bug**
If upstream is used, nginx ran into errors.
```
upstream galaxy {
    server unix:/galaxy/var/config/gunicorn.sock:/galaxy_22_05;
}
    location /galaxy_22_05 {
        # This is the backend to send the requests to.
        proxy_pass http://galaxy; 

        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
    }
```
```
 nginx: 2023/05/02 10:05:06 [crit] 4292#0: *1 connect() to unix:/galaxy/var/config/gunicorn.sock:/galaxy_22_05 failed (2: No such file or directory) while connecting to upstream, client: , server: , request: "GET /galaxy_22_05/history/current_history_json?since=2023-04-27T08:24:14.244564 HTTP/1.0", upstream: "http://unix:/galaxy/var/config/gunicorn.sock:/galaxy_22_05:/galaxy_22_05/history/current_history_json?since=2023-04-27T08:24:14.244564", host: "www.", referrer: "https://www./galaxy_22_05/"
```

If upstream is not used, nginx is working.
```
    location /galaxy_22_05 {
        # This is the backend to send the requests to.
        proxy_pass http://unix:/galaxy/var/config/gunicorn.sock:/galaxy_22_05;

        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
    }
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: {"version_major":"22.05","version_minor":"1"}
Commit: f420a619e4dcb4aa73c693086dbb03869eb0ca8f

**Comment by mvdbeek** [comment]
I think upstreams are defined outside of the server section, and I'm not sure your server syntax is correct. Questions that don't directly concern Galaxy are better asked at https://help.galaxyproject.org/ or the admin channel on gitter https://matrix.to/#/#galaxyproject_admins:gitter.im

**Comment by methylome** [comment]
@mvdbeek I followed the configuration on https://docs.galaxyproject.org/en/master/admin/nginx.html#serving-galaxy-at-a-url-prefix. Why do you think the syntax is not right?

**Comment by mvdbeek** [comment]
There's no upstream section in the docs, so I'm not sure why you refer to the docs ?

> Why do you think the syntax is not right?

2 things:
-  the way you've pasted your config I understand you've put your upstream inside a server section, that doesn't work.
- server unix:/galaxy/var/config/gunicorn.sock:/galaxy_22_05; -- that needs to be the path to the socket.
