### ISSUE TITLE
Galaxy data upload returning random dataset (not my uploaded dataset) 26 Jan 2016

### ISSUE THREAD

**Issue by hochoy** [galaxyproject/galaxy#1603]
Hi,

I just ran the galaxy data upload tool a few times in the past hour. Every time I do, I get a *_random dataset that does not belong to me. *_At first, I thought it was a problem with my column/rows/file_format but looking at the data, even the column names, row names, values are definitely not part of my dataset.

**Does anyone know what dataset is this and why the galaxy data upload is giving me a random dataset?**

![image](http://s28.postimg.org/v3eetnzal/Screen_Shot_2016_01_27_at_12_46_23_PM.png)
1. "load you own data"
2. "choose local file", "tabular", genome unspecified, start
3. "View" file ->  The filename is correct but the contents are not my file, completely different (someone else's dataset)

**Comment by carlfeberhard** [comment]
Hi and thanks for the report.

This looks like an older version of Galaxy. Is this a local install or your own server? If so, what version are you using? If not, can you specify which Galaxy it is (the url) and the version they're using?

**Comment by hochoy** [comment]
Hi Carl, thanks for the quick reply.

I have been using the tools at this link [https://huttenhower.sph.harvard.edu/galaxy](https://huttenhower.sph.harvard.edu/galaxy) for the past year and it works splendidly. The only hiccup I've had is today when the server was responding slowly for some reason. After that the data upload kept giving me random files. As of now, the site seems to be loading faster so I will give it a try again and then comment again.

I'm not sure how to check the galaxy version. I'm only using the website not a local copy.
Cheers,
David

**Comment by martenson** [comment]
That Galaxy does not have /api/version which makes it pre release_15.03

**Comment by jxtx** [comment]
Since this is the Huttenhower lab Galaxy, Curtis Huttenhower or George
Weingart are probably the best contacts.

-- jt

**Comment by hochoy** [comment]
Thanks Carl, martenson and jxtx. The issue seems to have resolved itself once their server's speed went back to normal. It works as usual now. I'll let them know.
