### ISSUE TITLE
Page collection display broken

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#16048]
**Describe the bug**
Collection display on the page not working

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: usegalaxy.eu `23.0.1.dev0`

**To Reproduce**

1. Create a collection
2. Go to pages
3. Create/edit a page
4. Add a collection on the page
5. View the page
6. Get collection data request has 404 error and can not be displayed

**Expected behavior**
Display collection

**Screenshots**
![image](https://user-images.githubusercontent.com/8046843/236474401-c63e3e11-aa0f-4a72-a73e-ca8e2b1824a7.png)

**Comment by ahmedhamidawan** [comment]
Just wondering if this is related to [In a shared history (only in the case where it's owned by another user), Collections are blank on expand](https://github.com/galaxyproject/galaxy/issues/15917#:~:text=1.%20In%20a%20shared%20history%20(only%20in%20the%20case%20where%20it%27s%20owned%20by%20another%20user)%2C%20Collections%20are%20blank%20on%20expand)? I might be wrong?

**Comment by itisAliRH** [comment]
I cannot reproduce it anymore. It seems it is fixed:
![image](https://github.com/galaxyproject/galaxy/assets/8046843/2379ab51-798a-42e4-9044-c4e693a94329)
