### ISSUE TITLE
Improve Form Drilldown UX

### ISSUE THREAD

**Issue by assuntad23** [galaxyproject/galaxy#16044]
**Describe the bug**
These bugs were intitially caught in PR #15813 which was vueifying the Form Drilldown component.
Form Drilldown does not display recursively selected options and indentation between parent/child options could be improved.  
Recursivity changes could look like: 
Multiple Recursive: (credit @ElectronicBlueberry)
![image](https://user-images.githubusercontent.com/26912553/236305963-1f0af4d7-89f0-401c-860d-ecbe69ae6ed7.png)
Single Recursive:  (credit @ElectronicBlueberry)
![image](https://user-images.githubusercontent.com/26912553/236306001-25052d60-71b1-4a4e-ba90-3fb0205d3980.png)

Indentation issues are complicated by +/- button that makes this more than just a simple padding fix.  Implementing this will need to take into account that siblings should still try to remain more or less in line with eachother. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1 
Commit: 521ccdd1244899f2537bcae235b4857f3d6711a3

**To Reproduce**
1. (locally) set up test tools
2. Find the drill_down tool
3. Select a parent option, and note that the children are not checked off
4. Look at the indentation between parent/children

**Expected behavior**
When parents are selected, there is some indication that their children were also selected.
Indentation between parents and children is clear, but does not violate alignment with sibling options.

**Comment by hujambo-dunia** [comment]
So, I have made some progress but from this ticket and [these code comments](https://github.com/galaxyproject/galaxy/blame/dev/test/functional/tools/drill_down.xml#L8-L33) it is still not fully clear to me what all the feature's "expected"/correct behavior should be for the drill-down feature. 
Could you help me understand the code comments explaining the difference between `hierarchy="exact"` and `hierarchy="recurse"`? Of course, I know what a "node" is, but what specifically is meant by a `"leave"`, `"inner"`, and the statement `only "leave" are are selectable`? To me, "selectable" (value-based) is not the same as "clickable" (not always value-based) and this comment doesn't make a distinction (I might also update [the docs](https://docs.galaxyproject.org/en/master/dev/schema.html#id52) to be more clear later on).
So far, here is where I am at: [the PR](https://github.com/galaxyproject/galaxy/pull/18074/files) and a [demo video](https://drive.google.com/file/d/1BXznod7kKMZgUpvvYHJFdK2ivyuOFp3u/view?usp=sharing).

Cc: @bernt-matthias @ElectronicBlueberry @dannon
