### ISSUE TITLE
Docker images being pushed with the same tag

### ISSUE THREAD

**Issue by ksuderman** [galaxyproject/galaxy#16053]
Merging code into `release_*` branches causes a new Docker images to be built and pushed with the release version number as the Docker tag. This can result in images with the same tag that are incompatible with each other and may contain breaking changes. Discussion about versioning policy aside, this can result in problems when users attempt to add a new node to a Kubernetes cluster and get a different Docker image even though they are pulling the same tag (e.g. galaxyproject/galaxy-min:22.05).

Until a solution for versioning the release Docker images is developed no more release images should be pushed using the 23.0 (or other release) version numbers.

- [x] Disable building release Docker images in the dev branch
- [x] Disable building release Docker images in release_* branches, at least release_23.0
- [x] Add a new GitHub action to build Docker images for release_* branches with a new revision number. That is 23.0.1, 23.0.2, etc.

**Comment by martenson** [comment]
ooof, that is a good catch 👍

**Comment by ksuderman** [comment]
Closed in #16055
