### ISSUE TITLE
Library import from FTP interface needs "select all" option

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#1606]
When importing multiple datasets clicking on every one of them is very annoying:

![screen shot 2016-01-28 at 9 17 04 am](https://cloud.githubusercontent.com/assets/4291636/12646791/11439384-c5a0-11e5-98ad-5cc1639649ef.png)

**Comment by martenson** [comment]
You can switch to the folder selection, but if you have flat structure as on the pic I understand the need. Will do.
