### ISSUE TITLE
'/api/upload/resumable_upload/' 404

### ISSUE THREAD

**Issue by H1207953831** [galaxyproject/galaxy#16062]
I wrapped galaxy version 22.05 in a docker container and want to run the local version of galaxy in docker for some production work. I've been experimenting with some of these features recently. One of the problems I'm having is that when I upload data from local to the server, it doesn't transfer the data to the server properly. The log result is.
`"HEAD /api/upload/resumable_upload/89a336dbee304610bd45da59921339dc HTTP/1.1" 200` and
`"PATCH http%3A//10.10.10.160%3A8081/api/upload/resumable_upload/89a336dbee304610bd45da59921339dc HTTP/1.1" 404`.
But it is possible to get the corresponding resources from the Internet, for example:
`https://raw.githubusercontent.com/bgruening/galaxytools/adf077b912ddebd97b07b947b855cdd2862ed8ef/tools/augustus/test-data/human_augustus.fa`
`https://raw.githubusercontent.com/bgruening/galaxytools/adf077b912ddebd97b07b947b855cdd2862ed8ef/tools/sailfish/test-data/reads_2.fastq`
`https://raw.githubusercontent.com/bgruening/galaxytools/adf077b912ddebd97b07b947b855cdd2862ed8ef/tools/statistics/test-data/anderson.tabular`
These above URLs are the ones that appear in the tutorial.

**Comment by mvdbeek** [comment]
Documentation for setting up tus is in https://docs.galaxyproject.org/en/master/admin/nginx.html#receiving-files-via-the-tus-protocol.
