### ISSUE TITLE
pysam.ctabix

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#1608]
I'm reimplementing deprecated (upstream) functionality for ctabix to prevent in-place modification and precompressed flag, roll new wheel.  Has to go with 16.01.

**Comment by dannon** [comment]
Just need to build it now:

https://github.com/dannon/pysam/releases/tag/v0.8.4_gxy1

**Comment by natefoo** [comment]
Once galaxyproject/starforge#62 is merged you can open a new Starforge PR for this.

**Comment by natefoo** [comment]
@dannon Go!

**Comment by dannon** [comment]
@natefoo It passed!  Going.

**Comment by dannon** [comment]
Wheels at: https://github.com/galaxyproject/starforge/pull/71

**Comment by dannon** [comment]
I really hate where that close button is.

**Comment by dannon** [comment]
Should be resolved with #1638
