### ISSUE TITLE
Schema Version 2 Tools

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1609]
I'd like to some time to pull the trigger on a new iteration of the tool schema for 16.04 that smooths some of the tooling sharper edges. Perhaps less dramatic than what we have discussed in the passed (like no auto-quoting input parameters).
- [x] `<tool id="foo" version="1.0" profile="16.04">`
- [x] `set -e` in tool command scripts. (Make option to enable/disable - on by default in schema 2 off in schema 1).
- [x] `detect_errors="exit_code"` by default.
- [x] Disable implicit extra file collection. All dynamic extra file collection requires a `<discover_datasets` tag.
- [x] Disable `format="input"` - require explicit metadata targets (`metadata_source`, `format_source`).
- [x] Disable `interpreter=` - hacky and doesn't work as expected in too many circumstances. Use `$__tool_directory__`.
- [x] Disable `$param_file`. (Or at least require a an explicit request for it, the implicit check now is imprecise.)
- [x] Disable default version of `1.0.0`.
- [x] Guarantee them clean directories (is this even related?) https://github.com/galaxyproject/galaxy/issues/1575  
- [x] Do not give the tool Galaxy's virtual environment by default.

Extra Ideas - (more formalized tool contract):
- [ ] Require explicit declaration of tool directory files required - Pulsar and tool packaging will be much more likely to work out of the box.

**Comment by hexylena** [comment]
Can we add a minimum galaxy version please? #1188 

Edit: at the least standardise the notation for it, not necessarily all of 1188.

**Comment by bgruening** [comment]
What about the other ideas of having multiple commands and annotating streaming of tools. Also tests should have an option to check the build command line.

**Comment by natefoo** [comment]
YAML? =)

**Comment by jmchilton** [comment]
@bgruening Tests already have this option! https://github.com/galaxyproject/galaxy/blob/dev/test/functional/tools/job_properties.xml#L45

**Comment by jmchilton** [comment]
@erasche It is an idea we've needed for awhile but it is a little unsettling - tools are meant to be abstract definitions they shouldn't require Galaxy at all let alone a specific version of it.

What if we peggy back on this though - rather than a schema attribute if it has a `galaxy_version="16.04"` tag it automatically inherits all these more reasonable defaults.  No need to branch on schema if we are declaring Galaxy versions.

**Comment by jmchilton** [comment]
@bgruening The streaming idea is fine but should be outlined and developed separately I think. This would be a new feature not a backward incompatible change the way the rest of these ideas are I think.

**Comment by jmchilton** [comment]
@natefoo I'd enable Galaxy's YAML tool parser by default tomorrow if you got the consent of the mega star external contributor and the PI that have expressed concern about the YAML format for tools.

**Comment by hexylena** [comment]
@jmchilton 

> tools are meant to be abstract definitions they shouldn't require Galaxy at all let alone a specific version of it.

Yeah! When I request a minimum Galaxy version, what I'd really like to request is a specific feature set (e.g. support of "<sections />"). Arguably Galaxy could detect this automatically, the simplest implementation seemed to be "I've tested on `release_` and that's the lowest I'm going to make any garuntees about this tools's behaviour". Whatever implementation of this will provide me with some method to warn admins "This tool may not work on your galaxy"

**Comment by pstew** [comment]
>  Require explicit declaration of tool directory files required - Pulsar and tool packaging will be much more likely to work out of the box.

Yes please! This would be incredibly helpful for some tools that we're working on.

**Comment by bgruening** [comment]
@jmchilton this was auto-closed by merging your PR. I guess we want to keep check the boxes before?
