### ISSUE TITLE
Workflow links with query parameters are not properly processed

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#16114]
We automatically attach query parameters to our URLs from the video library to help folks identify where traffic came from (in a _relatively_ privacy preserving way).

URL | Status
--- | --
https://usegalaxy.eu/u/wolfgang-maier/h/removal-of-human-reads-from-sars-cov-2-sequencing-data | Works
https://usegalaxy.eu/u/wolfgang-maier/h/removal-of-human-reads-from-sars-cov-2-sequencing-data?utm_source=schedule&utm_medium=click&utm_campaign=video-library | Doesn't

However Galaxy seems to not process the query parameters correctly resulting in a blank page. We see a 500 internal server error. 
https://sentry.galaxyproject.org/share/issue/7e98e830b0524bbc81746c541aa3a70b/

**Comment by mvdbeek** [comment]
So, yes, it shouldn't be a 500, but a 400 bad request ... which a user should receive when sending invalid parameters. Can you use headers or something else we can ignore ?

**Comment by hexylena** [comment]
Shouldn't it be a 200 ok? Invalid parameters should be ignored, not throwing errors, right?

These marketing parameters are completely valid for usage tracking, consumed by GA/plausible which galaxy supports, and will be consumed by those if they're enabled.

Headers are not possible, they originate from a user-clicked link.

**Comment by mvdbeek** [comment]
> Shouldn't it be a 200 ok? Invalid parameters should be ignored, not throwing errors, right?

No, I don't think that's right.

**Comment by hexylena** [comment]
For the API endpoint I absolutely agree with you. There it makes complete sense to raise an error for invalid or unknown parameters. And that would be appropriate for the case of the UI talking to the backend, and where a user might be sending incorrect query parameters when they're trying to access structured api responses.

Instead this page is a user-facing content-type text/html page, which I generally expect to behave under different rules (i.e. users aren't expected to be manually editing the URL, users generally aren't parsing the outputs, url parameters are ignored.) 

you might be able to strip them in nginx, I'm not sure.
