### ISSUE TITLE
[UI] Unify "Convert" and "Datatypes" tabs in the edit attributes menu. 

### ISSUE THREAD

**Issue by shiltemann** [galaxyproject/galaxy#16151]
The procedure in the UI for changing the datatype is different depending on whether a conversion is possible for the dataset.

E.g. For some datasets you have to click on the "Convert" tab, and for datasets without conversions available the tab is named "Datatypes" tab. To me it would make more sense to always have this tab be "Datatypes", and letting that tab have a convert option or not depending on the datatype.

![image](https://github.com/galaxyproject/galaxy/assets/2563865/ddfb8bbe-5a16-4d8c-b296-e21d9c2e605b)

![image](https://github.com/galaxyproject/galaxy/assets/2563865/2c15342f-f909-43c3-896c-eab98aa23d1d)

e.g. our [FAQ](https://training.galaxyproject.org/training-material/faqs/galaxy/datasets_change_datatype.html) for changing datatype says to click on the convert tab, but sometimes it is the Datatypes tab, and I think it would be easier for users to recognize if it's always the same name.

**Comment by hexylena** [comment]
xref #5768, we have the space for the tabs, we could un-unify them. Or at least give it a unified title/icon, whether showing just datatype change, or datatype change + convert

**Comment by dannon** [comment]
I don't think we want to separate them again -- the problem before was that it was confusing to users why we had two tabs next to one another that did (at face value) similar things.  I think we should probably just make the tab title static and more appropriate reflecting "Things related to the datatype here", as in the original issue.
