### ISSUE TITLE
unwanted value "Dataset Peek" include in my result

### ISSUE THREAD

**Issue by nongbaoting** [galaxyproject/galaxy#16154]
I create a custom tool, the result adds unwanted value.  j=0 to j=21 were automatically added.  why did this happen?

```
>22
j=0
j=1
j=2
j=3
j=4
j=5
j=6
j=7
j=8
j=9
j=10
j=11
j=12
j=13
j=14
j=15
j=16
j=17
j=18
j=19
j=20
j=21
mRNA sequence:  AUGAUGAGGAGGCUCCUCAAG
mRNA structure: ....((((((...))))))..
mRNA folding free energy: -5.90 kcal/mol; mRNA CAI: 0.803
```

**Comment by bgruening** [comment]
To answer your question we would need to see your tool. I assume it's part of the tool output that indicates 22 iterations to find the MFE of your RNA. But please show us the code :-)
Please ask those questions at https://help.galaxyproject.org. This repo is about the Galaxy framework.
