### ISSUE TITLE
Tool Search not doing anything

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#16164]
**Describe the bug**
Hi! 
After an upgrade of [usegalaxy.fr](http://usegalaxy.fr/) to 23.0 (0901ad748fc87ad653929628ac86ec012c4a3342), it seems like the tool search box is not working with the default tool list (but it works for edam or custom list). I see no js error, no error on server side, and the advanced search works well.
Any idea what could be wrong?

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0
Commit: 0901ad748fc87ad653929628ac86ec012c4a3342

**To Reproduce**
1. Go to usegalaxy.fr
2. Search for a tool in the default tool box
3. No change in the tool list even if there should be matches, no "no result" message either

**Comment by bgruening** [comment]
@abretaud can you try removing the tool search cache?

**Comment by mvdbeek** [comment]
Only the advanced search (with the two down arrows) uses the backend search, so that's not it. I guess it's the combination with the custom tool panel.

**Comment by abretaud** [comment]
Yep, recreating the cache did not help
I can try removing the custom panel tomorrow

**Comment by dannon** [comment]
Alright, I took a look at this.  What's going on is the tool search is blowing up when hitting `chemicaltoolbox_label` while iterating thorugh what it expects to be a list of tools.

Fairly trivial patch resolves it, which I will PR to make this more robust, but I'm curious what that label is doing there in the returned tools list.

```
diff --git a/client/src/components/Panels/utilities.js b/client/src/components/Panels/utilities.js
index 2bb5921e70..b3dd24858b 100644
--- a/client/src/components/Panels/utilities.js
+++ b/client/src/components/Panels/utilities.js
@@ -88,21 +88,23 @@ export function hasResults(results) {
 export function searchToolsByKeys(tools, keys, query) {
     const returnedTools = [];
     for (const tool of tools) {
-        for (const key of Object.keys(keys)) {
-            let actualValue = "";
-            if (key === "combined") {
-                actualValue = tool.name.toLowerCase() + " " + tool.description.toLowerCase();
-            } else if (key === "hyphenated") {
-                actualValue = tool.name.toLowerCase().replaceAll("-", " ");
-            } else {
-                actualValue = tool[key] ? tool[key].toLowerCase() : "";
-            }
-            const queryLowerCase = query.trim().toLowerCase();
-            if (actualValue.match(queryLowerCase)) {
-                // do we care for exact matches && is it an exact match ?
-                const order = keys.exact && actualValue === queryLowerCase ? keys.exact : keys[key];
-                returnedTools.push({ id: tool.id, order });
-                break;
+        if (tool && tool.name) {
+            for (const key of Object.keys(keys)) {
+                let actualValue = "";
+                if (key === "combined") {
+                    actualValue = tool.name.toLowerCase() + " " + tool.description.toLowerCase();
+                } else if (key === "hyphenated") {
+                    actualValue = tool.name.toLowerCase().replaceAll("-", " ");
+                } else {
+                    actualValue = tool[key] ? tool[key].toLowerCase() : "";
+                }
+                const queryLowerCase = query.trim().toLowerCase();
+                if (actualValue.match(queryLowerCase)) {
+                    // do we care for exact matches && is it an exact match ?
+                    const order = keys.exact && actualValue === queryLowerCase ? keys.exact : keys[key];
+                    returnedTools.push({ id: tool.id, order });
+                    break;
+                }
             }
         }
     }
 ```

**Comment by abretaud** [comment]
Cool, thanks for the quick fix! Tested in preprod, it's working great
