### ISSUE TITLE
[feature request] add the history filtering bar to published histories.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#16174]
Noticed this while trying to debug a user's issue. I can only toggle between deleted and active datasets, there's no way for me to see both in a shared history. (Didn't this used to be the default behaviour? "Include deleted" and "Include hidden"? I think I miss that, "only deleted" isn't as useful when working as a teacher debugging a student history.)

https://usegalaxy.org/published/history?id=45ecee9ded6a4a6f
![image](https://github.com/galaxyproject/galaxy/assets/458683/98134b7f-ba3c-4b02-9b0c-e6d16f2767b6)

In a personal history I can change the filter to `deleted:true or deleted:false` to see both, but I can't do that in a shared history without importing it. Could we expose the history filtering bar in published histories so I could manually type out the filter?

**Comment by ahmedhamidawan** [comment]
The buttons have been changed from Show hidden/deleted to Include hidden/deleted in `dev` now (in #15996) (which restores the default behavior we used to have).

**Comment by hexylena** [comment]
Oh, `deleted:any` is quite nice, but #15996 is fantastic, thank you for restoring the previous behaviour!
