### ISSUE TITLE
 galaxy-tool-util 23.0.1 has un-declared dependency on Cheetah

### ISSUE THREAD

**Issue by mr-c** [galaxyproject/galaxy#16218]
Hello,

In `cwltool` we use [`galaxy-tool-util`](https://pypi.org/project/galaxy-tool-util/) for tool dependency resolution.

The recent 23.0.1 release imports the Cheetah template engine for this use-case. Not only does that break our usage, but I think Cheetah should not be needed when importing `galaxy.tool_util.deps.containers.ContainerRegistry`

https://github.com/common-workflow-language/cwltool/actions/runs/5219610426/jobs/9421650542?pr=1859#step:7:7501

It isn't urgent; we'll just not upgrade until we really need it.

One workaround reported by @mvdbeek to also depend on ` galaxy-util[template]`

**Comment by nsoranzo** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/16219 , but we need to release a new 23.0.2 galaxy-util package.

**Comment by abretaud** [comment]
Ah nice to see this issue, encountered this while using ephemeris' shed-tools
Is the 23.0.2 galaxy-util release already on its way, or do I play with `galaxy-util[template]` until then?

**Comment by mvdbeek** [comment]
The action takes about 10 minutes each because we build and check every package. https://github.com/galaxyproject/galaxy/actions/runs/5258087246/jobs/9502235835 should upload to test pypi, and then another 10 minutes when the release gets published.
