### ISSUE TITLE
access to public datasets in pages is prevented for anonymous users

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16210]
found by @yvanlebras 

When public dataset is included in a Galaxy Page and the page is accessed by an anonymous user they'll get a 403 error:

`GET https://ecology.usegalaxy.eu/api/datasets/4838ba20a6d8676504b8a214b2e630da/get_content_as_text`

> API authentication required for this request `403`

This is likely due to the `get_authenticated_user` check on the following line:
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/services/datasets.py#L613

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: usegalaxy.eu `{"version_major":"23.0","version_minor":"1.dev0"}`

**Expected behavior**
Dataset should be accessible to anon users based on its permissions.

**Comment by yvanlebras** [comment]
Thank you so much @martenson for making the bridge from my question to this issue, and for identifying the origin of the issue! Hope all is ok on your side! Have a nice end of week Martin!

**Comment by hexylena** [comment]
xref https://github.com/galaxyproject/galaxy/issues/15220
