### ISSUE TITLE
Error while building a docker image，"file not found: /galaxy/server/lib/galaxy/version.py"

### ISSUE THREAD

**Issue by H1207953831** [galaxyproject/galaxy#16234]
**Describe the bug**
I then tried to build an image using the dockerfile in the project, because the python in this image is too new, so I wanted to use python version below 3.9, and the following problem description appeared during the packaging process, I really don't know how to solve it.
fatal: [localhost]: FAILED! => {"changed": false, "msg": "file not found: /galaxy/server/lib/galaxy/version.py"}
Since it is in China, three lines have been added to line 45 at RUN：
&& sed -i 's#http://deb.debian.org/debian#https://mirrors.tuna.tsinghua.edu.cn/debian#g' /etc/apt/sources.list \
&& echo "[global]" >> /etc/pip.conf \
&& echo "index-url = https://pypi.tuna.tsinghua.edu.cn/simple" >> /etc/pip.conf \

**Comment by mvdbeek** [comment]
Hi @H1207953831, which Dockerfile is this ?
The build for .k8s-ci.Dockerfile is tested here: https://github.com/galaxyproject/galaxy/blob/dev/.github/workflows/build_container_image.yaml#L35

Can you include more output from the build process ?

**Comment by H1207953831** [comment]
The dockerfile is https://github.com/galaxyproject/galaxy/blob/dev/.k8s_ci.Dockerfile
To build an image, just using the command docker build -f .k8s_ci.Dockerfile . -t <image_name>:<tag>
Of course I just copied the contents of .k8s_ci.Dockerfile and modified it on top of this one


Just now, I tried to put some files and directories locally and add the corresponding copy command in the dockerfile, for example, after line 66, I added the following copy command.

COPY version.py /galaxy/server/lib/galaxy/version.py
COPY static /galaxy/server/static
COPY dependencies /galaxy/server/lib/galaxy/dependencies
COPY config /galaxy/server/config

After that, no more prompts like this will appear.
And now it goes to the following step and pauses TASK [galaxy : Install Galaxy base dependencies]

**Comment by mvdbeek** [comment]
I assume when you say it pauses you're at this step: https://github.com/galaxyproject/galaxy/actions/runs/5239433129/jobs/9459258730#step:7:656

At this point Galaxy's dependencies are being downloaded and installed.
I don't think there's anything we can do to the dockerfile to help you with this issue, but if being in China plays a role you could let a github workflow build the image for you:

- activate actions in your fork
- commit your changes back to your own fork
- change https://github.com/galaxyproject/galaxy/blob/dev/.github/workflows/build_container_image.yaml#L16 to point at your github username
- add the necessary dockerhub and or quay.io credentials to your repository secrets (or remove the steps for the registries you don't need)
