### ISSUE TITLE
mako files do not recompile if changed

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/galaxy#1624]
Sorry for the lazy bug report, but I have spent around a day fighting with this and I am a bit tired.

The gist of things is: if there is a mako file that is compiled and it is updated (say via a git pull of a new galaxy version) the cache is not re-compiled with a new version.

I would suggest something as simple as a timestamp check between the compiled mako and the original one.

**Comment by hexylena** [comment]
Most of the mako files have now been removed, and everything is migrating to Vue, so closing this. Sorry it caused you issues!

If nothing else can recommend `rm -rf database/compiled_templates` whenever you change versions
