### ISSUE TITLE
Problems with modifying configuration files about galaxyproject/galaxy-min:22.01 previous versions, including version 22.01.

### ISSUE THREAD

**Issue by H1207953831** [galaxyproject/galaxy#16270]
Modify the configuration file galaxy.yml, e.g. add admin_users: and modify tool_config_file: the changes will not take effect.
However, if I modify the original configuration file /galaxy/server/config/tool_conf.xml.sample, for example, modify a few lines in the file, comment it out, then it will take effect immediately:

With this change, the upload function will not appear in the interface.
in the configuration file galaxy.yml the following line of information originally looked like this.
tool_config_file: /galaxy/server/config/tool_conf.xml.sample
if I change it to /galaxy/server/config/tool_conf.xml, and it won't change either, I started with a copy of the file and named it tool_conf.xml.
However, in version 22.05, if I operate the above command, everything will be fine, and it will be displayed immediately after modification.
So I'm asking what's going on and whether similar problems will occur in future versions. Of course, we will do a series of tests before the official deployment in future versions.

**Comment by martenson** [comment]
Some config files are watched and reload on change (like `tool_conf.xml`) and others are not (like `galaxy.yml`). This is by design, if you have a specific question beyond this please clarify.
