### ISSUE TITLE
cached singularity container resolver yields different results for (data manager) tools with same requirement

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#16276]
**Describe the bug**

I found in the (container) dependency UI some tools with identical requirements that resolve differentl (ie one resolves and the other doesn't):

![Screenshot from 2023-06-20 15-44-40](https://github.com/galaxyproject/galaxy/assets/25689525/9955e758-3125-4f04-97d5-feca35bd205f)

my `container_resolver_conf`

```
  - type: cached_explicit_singularity
    cache_directory: /data/galaxy_server/galaxy/database/container_cache/singularity
  - type: cached_mulled_singularity
    cache_directory: /data/galaxy_server/galaxy/database/container_cache/singularity
  - type: mulled_singularity
    auto_install: False
    cache_directory: /data/galaxy_server/galaxy/database/container_cache/singularity
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05
Commit: https://github.com/galaxyproject/galaxy/commit/d0551dda65fc43296a11f1dde587600d492ea18f

**Additional context**

**Comment by mvdbeek** [comment]
Probably the profile version (https://docs.galaxyproject.org/en/latest/dev/schema.html#id3) ? I don't see a 0.0.9 but feel free to re-open if that's not the problem.

**Comment by bernt-matthias** [comment]
Makes sense. Seems that I accidentally downgraded version [in the past](https://github.com/galaxyproject/tools-iuc/pull/3000) :facepalm: ...

So these pre 18.09 profile data managers  will never be executed in a container .. but also not in a conda env.

So this should be fine forr me.
