### ISSUE TITLE
Showing `https://fqdn/null` for not-yet shared histories while loading can be confusing for new users

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#16275]
We saw a number of new users submit, and attempt to submit these sort of histories during smörgåsbord. 

Perhaps it would be helpful that instead of showing https://usegalaxy.eu/null, it could be potentially better to just show nothing / a loading gif while that data is loaded from the backend (noticeable mostly on slow connections.)

cc @shiltemann

**Comment by hexylena** [comment]
Updating this one due to this request which was null with no indication anything was happening for around 2.7 minutes. A spinner could really help here.

Also would suggest removing `url: ` from the link text, it's unncessary and can be annoying when copying if I don't right-click or use the button which I rarely do.

![slow2](https://github.com/galaxyproject/galaxy/assets/458683/0c74e15f-ded4-45b3-97f6-193e9ddceef8)

**Comment by OmarLaham** [comment]
I can handle this one.
In which component can I find this link?

I will go for showing a spinner instead of showing nothing.

**Comment by hexylena** [comment]
Fixed in #17788
