### ISSUE TITLE
fix dataset.download_url to contain galaxy prefix

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16302]
current client hotfix (should be removed once resolved):  https://github.com/galaxyproject/galaxy/pull/16301
past similar fixes https://github.com/galaxyproject/galaxy/pull/16033

**Comment by mvdbeek** [comment]
I think https://github.com/galaxyproject/galaxy/pull/16301 is actually correct (or at least somewhat consistent): If we generate a relative URL (e.g. /api/history/bla) is should not be prefixed ... it's all relative to the app root. If it's a qualified url (http://localhost/api/bla) it should contain the prefix.

**Comment by martenson** [comment]
fair enough, do you want to close this then?
