### ISSUE TITLE
Enhance reactivity on quota refresh

### ISSUE THREAD

**Issue by ErwinBrosens** [galaxyproject/galaxy#16317]
Hi,

i am working at https://usegalaxy.org/workflows/list and the beta version of the account storage does not seem to be working properly. I have deleted all files and histories, purged the storage and history storage but my storage use on top of the screen remains 80% ( in the history panel it is 0). I heard from colleagues that they experienced similar issues.

best Erwin

erwinbrosens/e.brosens@erasmusmc.nl

**Comment by davelopez** [comment]
Hi, can you give us more details to be able to investigate this issue?

A couple of screenshots of https://usegalaxy.org/storage and https://usegalaxy.org/storage/management might help and as much information you can provide about those purged histories.

Thank you!

**Comment by ErwinBrosens** [comment]
Hi, I marked the difference. i have no other histories or data stored. The top percentage seems leading, I cannot upload more data (there should be 250 Gb left.

![2023-06-28 (3)](https://github.com/galaxyproject/galaxy/assets/137876042/42e1768c-eeba-4ae7-a49d-2ea242bfc7f1)

![2023-06-28](https://github.com/galaxyproject/galaxy/assets/137876042/1252e43b-84e9-4f82-a960-3d243c123008)

![2023-06-28 (2)](https://github.com/galaxyproject/galaxy/assets/137876042/12dccb44-4945-477c-a9e7-17cb4083b294)


best Erwin

**Comment by davelopez** [comment]
Thank you for the screenshots!

If the following screenshot is what is confusing you:
![image](https://github.com/galaxyproject/galaxy/assets/46503462/cd9125c8-4646-4e1c-a143-6f60e5033cae)

This just means that your **current** history has no data, but you may have other histories taking up the space.

Can you please go to the top menu to `User->Histories` (or https://usegalaxy.org/histories/list) and see if there are other histories there taking up your space?

**Comment by davelopez** [comment]
Ok, one last thing to try :)

Can you go back to your Storage Dashboard (https://usegalaxy.org/storage) and try to "Refresh" the quota calculation by pressing the `Refresh` button there?

You may need to also **reload the page** after a little while to get the updated values.

**Comment by ErwinBrosens** [comment]
hi David. Thank you for your help. I do not know what changed. refreshing did not help yesterday. But now the usage for my collegue goes to 0 (even though there is data on the server) after refreshing. For me, the usage is at 0 without refreshing (even though there is data on it.). Problem solved?
best erwin

**Comment by davelopez** [comment]
Thank you for reporting!
Using the "Refresh" button should usually help in these situations, but it may take some time to catch up, also *reloading the page* after this refresh is usually a good idea in case the quota value is cached in the browser.

I will leave this issue open and change the title to `Enhance reactivity on quota refresh` to see if we can improve the way the quota value gets updated as it seems to be taking too much time and causing confusion.
