### ISSUE TITLE
Duplicate result in tools search complicates newcomer tutorial.

### ISSUE THREAD

**Issue by hrukkudyr** [galaxyproject/galaxy#16310]
**Describe the bug**
Tool search throws up duplicate results.

**Galaxy Version and/or server at which you observed the bug**
{"version_major":"23.0","version_minor":"1.dev0"}
usegalaxy.eu

**To Reproduce**
1. Go to search tools in left column
2. Search for fastqc
3. Two (identical)  results displayed : "FASTQC: Read quality reports" both link to https://usegalaxy.eu/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Ffastqc%2Ffastqc%2F0.73%2Bgalaxy0

**Expected behavior**
One result per tool (or per tool version)

**Screenshots**
![image](https://github.com/galaxyproject/galaxy/assets/32413040/7254a545-fee0-4b92-aa25-fa946b50dda3)

**Additional context**
To hard core Galaxy users this is not a problem. However we were introducing new users via a GTN tutorial and this problem caused several of them to spend time trying to differentiate between the two, identical, choices. Such extra cognitive load is not ideal when the student is already working in new territory.
Ideally some programmatical filter to hide duplicate links if easily possible?

**Comment by bgruening** [comment]
@hrukkudyr thanks a lot for reporting, I will fix that during the day.

**Comment by hrukkudyr** [comment]
Wow – thanks for the fast response – mild problem but the baby users spend some time trying to ‘spot the difference’ between the two tools From: Björn GrüningSent: 26 June 2023 09:36To: galaxyproject/galaxyCc: ***@***.***; MentionSubject: Re: [galaxyproject/galaxy] Duplicate result in tools search complicates newcomer tutorial. (Issue ***@***.*** thanks a lot for reporting, I will fix that during the day.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ahmedhamidawan** [comment]
This happens when a tool is placed in multiple sections:
<img width="288" alt="image" src="https://github.com/galaxyproject/galaxy/assets/78516064/861ac4d8-84e5-48cd-b865-b3aad2a38ce2">

**Comment by ahmedhamidawan** [comment]
Actually, on closer examination, both tools have different ids:
- `toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.73+galaxy0`
- `toolshed.g2.bx.psu.edu/repos/devteam/fastqc/fastqc/0.74+galaxy0`

**Comment by hrukkudyr** [comment]
Thanks guys - fantastic service (as always) :-)
