### ISSUE TITLE
regular user can modify tags of published items

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16314]
As a regular user I can go to https://usegalaxy.org/histories/list_published and tag any of the histories there with anything I want. These tags will then show for the owner of the histories as their own (and in the published list). Moreover I can delete any tags from the histories including any tag that the owner (or other users) have added.

While fixing this issue I suggest other pages with usage of tags should be reviewed for similar behavior, we use tags in many places.

**Comment by jdavcs** [comment]
You have to be logged in to do that. Not that it makes it less of an issue.

**Comment by dannon** [comment]
These are added as "community tags", right?  This came up pretty recently and I think we decided to just do away with them completely.

**Comment by martenson** [comment]
@dannon as an owner if I add tags to my item I don't think they should be added as "community tags". The whole concept is confusing to me, this is basically free-for-all tagging.

**Comment by dannon** [comment]
> @dannon as an owner if I add tags to my item I don't think they should be added as "community tags" (I did this from the history panel btw). The whole concept is confusing to me though, this is basically free-for-all tagging.

Totally agreed, I think this is why we just want to simplify here and drop the community tags and have not proven useful.
