### ISSUE TITLE
with activity bar enabled toolpanel is no longer collapsible

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16326]
<img width="484" alt="New_Issue_·_galaxyproject_galaxy_and_Galaxy" src="https://github.com/galaxyproject/galaxy/assets/1814954/1b135b99-72a7-44f7-8387-071e6bc03460">

**Comment by guerler** [comment]
Clicking on the `Tools` activity, collapses the panel.

**Comment by davelopez** [comment]
I'll close this as the panel can be collapsed from the corresponding activity. @martenson please reopen if you think there is still an issue.
