### ISSUE TITLE
unclear distinction between toolform parameters

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16325]
It might be just me being a newbie in using Galaxy but when there are multiple params in a section it seems difficult to distinguish between parameter labels, names, help and especially which text belongs to which parameter.

There is a difference in font-weight (400 vs 700) but to be honest it does not help enough for me. Some more polished horizontal grouping could help?

![Galaxy](https://github.com/galaxyproject/galaxy/assets/1814954/ec4a4e8f-51e4-4830-9410-3f1e6a263ca2)

**Comment by hexylena** [comment]
Huh, I miss the parameter name headers there, those were clearer (or maybe 700 renders as 900 for me, and for you actually as 700 decreasing the distinction? I guess you're on a mac?)

![image](https://github.com/galaxyproject/galaxy/assets/458683/094b564d-b3d3-4a11-9f28-a6803be8e509)

**Comment by martenson** [comment]
@hexylena correct, this is chrome on macos. Yours look much better.

**Comment by hexylena** [comment]
darn osx supporting all the font weights accurately. at least easy to just
fix them to 900.

**Comment by hujambo-dunia** [comment]
> It might be just me being a newbie in using Galaxy but when there are multiple params in a section it seems difficult to distinguish between parameter labels, names, help and especially which text belongs to which parameter.
> 
> There is a difference in font-weight (400 vs 700) but to be honest it does not help enough for me. Some more polished horizontal grouping could help?
> 
> ![Galaxy](https://user-images.githubusercontent.com/1814954/249294641-ec4a4e8f-51e4-4830-9410-3f1e6a263ca2.png)

Thanks @martenson - something as a mac-chrome user, I've always wondered about too. I'll be looking at this one this week.

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/16515
