### ISSUE TITLE
Storage space issue

### ISSUE THREAD

**Issue by Fakihaaa** [galaxyproject/galaxy#16336]
Hi,

I am having storage issues. I deleted significant amount of files (permanently) but my storage is still 88% occupied. I am using beta version of galaxy for RNA seq analysis. 

Please advise me on the matter. Thank you.

**Comment by davelopez** [comment]
Hi, can you please verify if what you are experiencing is similar to this https://github.com/galaxyproject/galaxy/issues/16317?

In particular, try to "Refresh" your quota calculation following these steps https://github.com/galaxyproject/galaxy/issues/16317#issuecomment-1611131776

**Comment by davelopez** [comment]
I will assume you are experiencing the same issue as https://github.com/galaxyproject/galaxy/issues/16317

Please reopen if it is not the case :)

**Comment by Fakihaaa** [comment]
Hello, 

I am having this issue yet again. I have been deleting files but they are not showing up in the deleted datasets, tried refreshing as well, didn't work. Please help me resolve this issue. I have just a final tool to use and then I will be done with my analysis.

**Comment by davelopez** [comment]
Do you have any "archived" histories in https://usegalaxy.org/histories/archived?

If you do, those also count towards your quota if they are not purged. Is that the case?
