### ISSUE TITLE
Simple conditional workflow fails?!

### ISSUE THREAD

**Issue by braza2** [galaxyproject/galaxy#16331]
**Describe the bug**
Created a very simple workflow, with two branches and a tab seperated input file containing two columns. In one branch we apply cut to get the first column. The other branch is set to be conditionally skipped, where we apply the transpose tool. 

![image](https://github.com/galaxyproject/galaxy/assets/79978907/5d297700-2401-4f1c-8a05-aeaaf180c9da)

When running the workflow I tested both cases, where cond-bool is set to true and false. I get the following error message:
![image](https://github.com/galaxyproject/galaxy/assets/79978907/a5926ffe-1c6e-4805-b735-47e67dbf2efa)

Invocation scheduling failed because step 4 contains an expression that could not be evaluated.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: https://usegalaxy.eu/

**Comment by mvdbeek** [comment]
Can you share your workflow ?

**Comment by braza2** [comment]
@mvdbeek sorry, just added the screenshot

**Comment by mvdbeek** [comment]
No, can you please share the workflow ?

**Comment by braza2** [comment]
Yep, here is the link

https://usegalaxy.eu/u/hilbertserbe/w/test-conditionals

**Comment by mvdbeek** [comment]
I only get access to the last version, but that isn't a valid version:
<img width="624" alt="Screenshot 2023-06-28 at 12 48 08" src="https://github.com/galaxyproject/galaxy/assets/6804901/106d1c94-6088-4505-82b5-104c68387676">

**Comment by braza2** [comment]
Interesting, this isn't how it looks like when I share the workflow. There it looks like in my screenshot. When I import the shared workflow I get the same problem with the connections. When I fix that in the imported one and share that one, and then import it again, the same connection error appears.

**Comment by mvdbeek** [comment]
Thanks for the report, it turns out I really don't use the user interface enough to notice that the defined workflows use the wrong expression form. https://github.com/galaxyproject/galaxy/pull/16332 will fix this.

**Comment by bgruening** [comment]
Pushed, it will be deployed over night. Thanks @mvdbeek
