### ISSUE TITLE
Tooltip should clear when over Tool Search Input field Clear button clicked

### ISSUE THREAD

**Issue by hujambo-dunia** [galaxyproject/galaxy#16337]
https://github.com/galaxyproject/galaxy/assets/3672779/94efdee7-56ed-4b15-9daa-610959b80adc

Tooltip does not disappear, preventing Tool Search Input field's "x"/clear-icon from being clicked and preventing the search text from being cleared. Other tooltips (further down on the Tool Panel) seem stuck afterwards.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1 (on usegalaxy.org as of Jun 28, 2023)
Browser: Chrome

**To Reproduce**
1. Found accidentally, I created a new Workflow and then searched for some text while the mouse hovered in a place that displayed a tooltip. However, the tooltip did not disappear.

**Expected behavior**

**Screenshots**

**Additional context**
Seems similar to #12738

**Comment by ahmedhamidawan** [comment]
This will be fixed in #16402 when we change the `v-b-tooltip` directive (to a noninteractive one)

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/16506
