### ISSUE TITLE
cannot "clear" upload button in activity bar

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16342]
without the activity bar the "reset" option works, but with it the button always stays green after upload?

<img width="1298" alt="Galaxy" src="https://github.com/galaxyproject/galaxy/assets/1814954/a2826404-74af-4729-833a-f8ec329ead0e">

**Comment by guerler** [comment]
Potentially related to: #17212, i.e. when the upload modal closes, all data of its data is cleared. It might make sense to add a scoped store here and keep track of the upload data, such that closing and opening the modal does not clear the associated data.
