### ISSUE TITLE
History - Filter By State - dropdown selector fails upon "re-selection"

### ISSUE THREAD

**Issue by slmosher** [galaxyproject/galaxy#16366]
**Describe the bug**
In the "search datasets" search bar, just under the history label, one can `Filter by state`. Upon selecting a list item, if one made a mistake or changes one's mind, they are prevented from re-selecting a second option. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: [23.1.rc1](https://docs.galaxyproject.org/en/release_23.1/releases/23.1_announce_user.html)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Go to usegalaxy.org
2. Click on the double downward pointing cheveron icon
3. Scroll down to `filter by state`
5. click the box, make a selection
6. click the box a second time to make a second selection --> fails until the text is deleted, then the dropdown re-appears.

**Expected behavior**
I expected to be able to update my selection, but this does not work. I learned that if I delete the text in the box afterwards, I can then re-select a drop-down menu item.

**Screenshots**

**Additional context**

**Comment by ahmedhamidawan** [comment]
That is an autocomplete dropdown (with recommended states), changing it to a regular dropdown instead. thanks!
