### ISSUE TITLE
release notes bullhorn is blinking on every visit

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16375]
Every page reload resets the blinking so our use of localstorage for state persistence seems to not work correctly.

xref https://github.com/galaxyproject/galaxy/pull/16049

**Comment by davelopez** [comment]
I wonder if it is worth backporting #16371 to 23.1 for this too

**Comment by mvdbeek** [comment]
@galaxyproject/wg-uiux could someone take this on ? This is maybe the highest priority blocker we've got for the release.

**Comment by bgruening** [comment]
ping @itisAliRH

**Comment by dannon** [comment]
This is a result of the prerelease version being run without release notes being available.  Ironically it would fix itself on release.

That said, I'll open a PR that handles this a bit better for, hopefully, the last release of this webhook.
