### ISSUE TITLE
Data Upload Error: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by abuhaby** [galaxyproject/galaxy#16382]
**Describe the bug**

I had successfully installed a new galaxy instance inside oracle cloud but anytime I try to upload a data in any format the subject error persists.

**Galaxy Version and/or server at which you observed the bug**

using oracle ubuntu OS

**Comment by mvdbeek** [comment]
Thanks for the report, do you have any more log messages or instructions to reproduce this ? If you haven't set up Galaxy yourself please contact the entity that did, they may be able to help you. If you have additional log data for us to look at feel free to reopen the issue.
