### ISSUE TITLE
Add Login Required validation for tools that require the user to be logged

### ISSUE THREAD

**Issue by hujambo-dunia** [galaxyproject/galaxy#16396]
At GCC2023 "Machine Learning" training session, we went over the ["Machine Learning Part 3 (CNNs)"](https://training.galaxyproject.org/training-material/topics/statistics/tutorials/CNN/tutorial.html) which creates an image recognition workflow in Galaxy. Even though it was clearly stated at beginning of the course that you needed to be logged into Galaxy, one of the users failed to do so and was at no point in their workflow creation process informed this would be an issue. Nevertheless, their workflow generated various red error messages in the History panel but still allowed them to move through all the steps of the tutorial but, of course, did not generate the correct result at the end of the tutorial.

Galaxy Version: 23.x

1. Go through the steps in the tutorial linked at the top of this Description

**Expected behavior**
(1) Some validation that checks if you must be logged in to use a particular tool (2) decision on if the user should be allowed to move forward anyway or if the user should be stopped from creating additional errors (3) a corresponding UI that informs the user what the issue is and how to solve it (dialog box, notification, etc).

**Screenshots**

**Additional context**
Just a note, I am unsure if this is a "bug", but I believe it should be addressed to: (1) prevent error-log from getting clogged due to user-generated errors (not code errors) and (2) guide the user to successful completion of their workflow.

**Comment by mvdbeek** [comment]
> Even though it was clearly stated at beginning of the course that you needed to be logged into Galaxy, one of the users failed to do so and was at no point in their workflow creation process informed this would be an issue.

do you still have the history available, or screenshots ? You can't actually edit, run or import workflows (the whole interface is missing) when you're not logged in. What server was this at ? Was the account maybe not activated, which is different thing ?

**Comment by mvdbeek** [comment]
Please feel free to re-open if you figure out how to reproduce this.

> (2) decision on if the user should be allowed to move forward anyway or if the user should be stopped from creating additional errors

as long as there are non-errored jobs I think the analysis should continue

3) a corresponding UI that informs the user what the issue is and how to solve it (dialog box, notification, etc).

Workflow runs are monitored in the Workflow Runs / Workflow invocation tab. Recent version of Galaxy do show you what the problem was.
