### ISSUE TITLE
History Pagination is broken if there are archived histories

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#16397]
**Describe the bug**
`api/histories/count` returns `len(current_user.active_histories)`, which currently includes active+archived histories. We need to change that so that if returns only active, not archived, not deleted histories.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1

**To Reproduce**
1. Given no histories have been archived, archive one history
2. Go to the switch to history modal
3. Scroll down to the end, it'll keep expecting 1 more history, as the total count of histories hasn't changed after the archival

**Comment by davelopez** [comment]
Good catch, that is actually a backend issue :+1:

**Comment by davelopez** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/16400, thanks for discovering it!

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/16400
