### ISSUE TITLE
Vueify Uploader Interface

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#16407]
Our Uploader interface needs an overhaul, currently it is still a mix between Vue and Backbone code. We should take this opportunity to not only modernize the underlying code but also the interface itself, by adding features and improving the ability to add upload type variations as necessary.

Current Uploader interface:
<img width="909" alt="image" src="https://github.com/galaxyproject/galaxy/assets/2105447/eb15d6ec-ccee-4d39-87ae-3b3453cd8e3b">

Some ToDo's are:
-   [x] Remove Mixins
-   [x] Remove remaining jQuery listeners
-   [ ] Display interface in center panel instead of modal
-   [x] Use vue-multiselect instead of select2
-   [x] Use popper instead of custom popup code
-   [ ] Re-arrange buttons and drop area
-   [ ] Add support to handle zipped files?
-   [x] Composable Api
-   [ ] Convert to TypeScript
-   [ ] Avoid custom cache use stores instead
-   [ ] Avoid select area to be cut off
-   [ ] Preserve modal content

Related issues:
#16342, #16382, #15697, #15296

Related PRs:
#16408

**Comment by mvdbeek** [comment]
Is the 23.1 milestone realistic here ? The freeze has already happened.

**Comment by jdavcs** [comment]
Fixed in #16472 (Thanks, @guerler! I assume this can be closed?)
