### ISSUE TITLE
[23.0] enable_account_interface: false still allows users to change password

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#16404]
**Describe the bug**

I have a LDAP managed instance and would like to hide all account related preferences from the user using `enable_account_interface: false`. 

After https://github.com/galaxyproject/galaxy/pull/14363 the username and public name have been removed from `Manage Information`. 

But `Change Password` is still shown.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0
Commit: 8d26b5c1b3

**Expected behavior**

The password change option is hidden

**Screenshots**

![Screenshot from 2023-07-14 12-40-52](https://github.com/galaxyproject/galaxy/assets/25689525/0aefe5e5-e926-43d1-83cf-fc4eb26be02b)

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/16464

**Comment by bernt-matthias** [comment]
Thanks @davelopez
