### ISSUE TITLE
Creator section doesn't display anymore in tool form

### ISSUE THREAD

**Issue by hechth** [galaxyproject/galaxy#16416]
**Describe the bug**
The creator element section at the bottom of the tool form is no longer displayed. It used to work on version 22.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version:  23.0.4.dev0  on EU

**Comment by nsoranzo** [comment]
Thanks for reporting! Do you mean the [`<creator>` element](https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-creator) in the tool form?

**Comment by hechth** [comment]
> Thanks for reporting! Do you mean the [`<creator>` element](https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-creator) in the tool form?

Yeah exactly!

**Comment by dannon** [comment]
Looks like this got crossed up here:  https://github.com/galaxyproject/galaxy/pull/14549/files#diff-f242126051048ccc9eb6c6743bf48bf9ea1fec9ebee15f7aab8c5a05cd76c13cL103

Opening a fix.
