### ISSUE TITLE
how to properly work with API decorators

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1642]
this issue was created because of:  https://github.com/galaxyproject/galaxy/pull/1641

the API endpoint at https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/lda_datasets.py#L403 was not correctly handling POST requests with application/json 
This was my mistake because I did not realize that the `kwd` will get correctly populated only with `application/x-www-form-urlencoded` or `multipart/form-data` but not with `application/json`
See: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/web/framework/decorators.py#L152
- What is the correct way of handling this?
- Is the `payload = util.recursively_stringify_dictionary_keys( loads( trans.request.body ) )` that is called for json working correctly? Why do we not populate the kwd?

@jmchilton @carlfeberhard

**Comment by carlfeberhard** [comment]
> - What is the correct way of handling this?

I don't think the way we're loading data from the body is ideal and I think you got hit by one of Galaxy's jagged edges. That said, I'd much rather see _a few things_ in Galaxy be 100% consistent, then move/update/improve them all as much as possible as a singular unit. In this case, using payload is clunky but if we get it consistent with the other calls, we can then move all of them and remain consistent - which, I think, is better than three different styles. You implemented a better (but minority) solution.

> - Is the payload = util.recursively_stringify_dictionary_keys( loads( trans.request.body ) ) that is called for json working correctly? Why do we not populate the kwd?

I think the parameter handling could be a lot better in this decorator. Like above, I'd say it's more important to be consistent (hell - most of our API doesn't even use the newer `expose_api` stuff yet). I dunno; We should think of a way to make this all smoother - I'll let you know if I do.

**Comment by martenson** [comment]
@carlfeberhard by "better (but minority) solution" do you mean https://github.com/martenson/galaxy/commit/3444773f460ad3bd093543e597b14aee5948f09a ?

**Comment by carlfeberhard** [comment]
> by "better (but minority) solution" do you mean martenson@3444773 ?

No, I meant the post body becoming the `kwd`s like you had assumed it did (if I understood correctly). I think that's better and makes more sense - if it's doable. There's potential for key conflict I guess.

**Comment by martenson** [comment]
@carlfeberhard you understood correctly. Thanks for explaining.

I am now overriding the kwd by things in payload, so they take precedence. Not sure what is the standard there though.
