### ISSUE TITLE
Static files per host: order matters, favicon.ico and robots.txt not served correctly

### ISSUE THREAD

**Issue by mira-miracoli** [galaxyproject/galaxy#16429]
**Describe the bug**
related to:
- https://github.com/galaxyproject/galaxy/pull/12379
1. When specifying static_*_by_host in the configuration, the order of the entries matters, which can lead to Galaxy not serving the specified subdomains correctly.
2. For resources that have no PATH_INFO, like `<galaxy.domain>/robots.txt` and `<galaxy.domain>/favicon.ico` the static configuration by host is not working – the part where the configuration is read will never be reached.  

**Galaxy Version and/or server at which you observed the bug**  

Galaxy Version: 23.0
Commit: 2eb6888249fe391bf2c0b8bc563f7ac5bef89d81

**To Reproduce**
1. Steps to reproduce the behavior:
1.1 Serve static configuration with galaxy per host. e.g. add the following to `galaxy.yml`
~~~yaml
    enable_static: true
    static_welcome_html_by_host:
      'example.org': '/srv/galaxy/server/static/welcome.html/'
      'subdomain1.example.org': '/srv/galaxy/server/static-subdomain1/welcome.html/'
      'subdomain2.example.org': '/srv/galaxy/server/static-subdomain2/welcome.html/'
~~~
1.2 Make sure to create the corresponding directories and copy the file structure from `static` to the new static directories.
1.3 Change index.html in `../static-*/welcome.html/index.html` so you can identify them easily.
1.4 Try to load the different subdomains. All subdomains are now being served the `index.html` from `example.org`
1.5 Change the order and move the base domain to the bottom. Everything should work as expected.
2. Steps to reproduce the behavior:
2.1 Serve static configuration with galaxy per host. e.g. add the following to `galaxy.yml`
  ~~~yaml
    enable_static: true
    static_robots_txt_by_host:
      'example.org': '/srv/galaxy/server/static/robots.txt'
      'subdomain1.example.org': '/srv/galaxy/server/static-subdomain1/robots.txt'
      'subdomain2.example.org': '/srv/galaxy/server/static-subdomain2/robots.txt'
  ~~~
2.2 Change the `robots.txt` files in the different directories in a distinguishable way.
2.3 Load the different hosts `example.org/robots.txt` `subdomain1.example.org/robots.txt` and `subdomain1.example.org/robots.txt`. The served file does not show any changes at all, but is the default file.

**Expected behavior**
Galaxy should serve the correct files from the paths configured per host.

**Additional context**
The first issue is probably related to an if statement in [lib/galaxy/web/framework/middleware/static.py
](https://github.com/jmchilton/galaxy/blob/43b6eb2e1f200eb25d710995af4fdb8e762314a5/lib/galaxy/web/framework/middleware/static.py#L39)  
Because `example.org in *.example.org` will always evaluate to true.

I think the second error is related to empty `PATH_INFO`. The function does not reach the ["per host configuration"](https://github.com/jmchilton/galaxy/blob/43b6eb2e1f200eb25d710995af4fdb8e762314a5/lib/galaxy/web/framework/middleware/static.py#L38-L41) part, because it returns, when [this if condition evaluates to true](https://github.com/jmchilton/galaxy/blob/43b6eb2e1f200eb25d710995af4fdb8e762314a5/lib/galaxy/web/framework/middleware/static.py#L21).

**Comment by mira-miracoli** [comment]
Yes, for the first error, I would suggest replacing `in` with `==`

For the second one maybe we could do a temporary redirect to `/static/robots.txt`?

**Comment by mvdbeek** [comment]
Yes, I think that'll work.

**Comment by mira-miracoli** [comment]
Number two is solved by following changes to 
`lib/galaxy/web/framework/middleware/static.py`
~~~diff
--- a/lib/galaxy/web/framework/middleware/static.py
+++ b/lib/galaxy/web/framework/middleware/static.py
@@ -18,7 +18,10 @@ class CacheableStaticURLParser(StaticURLParser):
 
     def __call__(self, environ, start_response):
         path_info = environ.get("PATH_INFO", "")
-        if not path_info:
+        script_name = environ.get("SCRIPT_NAME", "")
+        if script_name == "/robots.txt" or script_name == "/favicon.ico":
+            filename = script_name.replace('/', '')
+        elif not path_info:
             # See if this is a static file hackishly mapped.
             if os.path.exists(self.directory) and os.path.isfile(self.directory):
                 app = FileApp(self.directory)
@@ -26,7 +29,7 @@ class CacheableStaticURLParser(StaticURLParser):
                     app.cache_control(max_age=int(self.cache_seconds))
                 return app(environ, start_response)
             return self.add_slash(environ, start_response)
-        if path_info == "/":
+        elif path_info == "/":
             # @@: This should obviously be configurable
             filename = "index.html"
         else:
~~~

**Comment by mvdbeek** [comment]
Do you want to just open a PR? This looks fine to me.

**Comment by mira-miracoli** [comment]
@mvdbeek  would you like to review it?
Regarding the failed tests, I have no clue how it can be related to my changes.

**Comment by mira-miracoli** [comment]
Closed by
- https://github.com/galaxyproject/galaxy/pull/16459
