### ISSUE TITLE
Tool search stalls at the first character of the query string

### ISSUE THREAD

**Issue by tuncK** [galaxyproject/galaxy#16428]
**Describe the bug**
Tool search stalls at the first character of the query string. It happens only from the workflow editor, but not from the history window. As if it is trying to do something with this first character, whether querying a DB, or in a timeout before showing "query string too short" error blocking user interaction...

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.eu on 21.07.2023 + Firefox

**To Reproduce**
1. Go to Workflow.
2.  Make a new workflow and edit it.
3. Attempt to search for a tool to add, ex: "grep"
4. You should observe that you are stuck at "g" for a few seconds, before "rep" appears.

**Expected behavior**
Should have directly shown "query string too short" message, or even not done anything within a given time window.

**Comment by ahmedhamidawan** [comment]
Fixed in #16505
