### ISSUE TITLE
Document more stuff with new releases?

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1643]
When we simplified the release notes we stopped the initiative to start documenting all new properties in `galaxy.ini`. I was going through github and I came across an issue related to this, so I guess I'd just like to alter the question and move it here.

Should we explicitly document
- [ ] Additions to galaxy.ini.
- [ ] Changes to `datatypes_conf.xml.sample`.
- [ ] Database migrations.
- [x] deprecations

**Comment by martenson** [comment]
Good initiative. As I see it:

yes
maybe
yes

**Comment by martenson** [comment]
examples of inclusion can be seen at https://github.com/galaxyproject/galaxy/pull/4075/commits/c459cd66ba7ebb5fbd0bb49557eabca4bd39433b and https://github.com/galaxyproject/galaxy/pull/4075/commits/c8250ae68aea09fb7a1f15109aa5f28027b50966

Also added to the release checklist via https://github.com/galaxyproject/galaxy/pull/4077

Closing.
