### ISSUE TITLE
Conda requirements are now converted to lowercase

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#16435]
**Describe the bug**
If a requirement tag for a tool with a single requirement has uppercase characters, the matching conda environment previously also had uppercase characters. As of the listed commit/PR, the match is converted to lowercase instead.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1
Commit: d65721c78de7adf9ad749a0e07d0dc7ad8684c2a

**To Reproduce**
1. Install a tool with a single requirement on a package with an uppercase character, e.g. mimodd_info from wolma/mimodd_main on an older revision
2. Ensure the conda dependency installed
3. Run the tool successfully
4. Update to the listed revision or later
5. Run the tool unsuccessfully

**Expected behavior**
Dependencies are resolved correctly.

**Screenshots**
N/A

**Additional context**
Broken in #16181

As a temporary workaround, I symlinked all envs with uppercase characters on usegalaxy.org to their lowercase counterparts.

I have not checked if the lowercasing affects the outcome of the mulled env hash, so that could be an issue as well.

**Comment by nsoranzo** [comment]
Sorry for breaking this!
Given that conda package names must be lowercase, I think that lowercasing the environment names is the correct behaviour, otherwise you could end up with multiple conda environments for tools that have the same requirement but use different capitalisations.

But if this breaks loads of already installed tools and we cannot easily find a workaround, it's probably better to revert that change.

**Comment by natefoo** [comment]
I already have a workaround in place, so I can live with this, although other Galaxy servers will need to be made aware of it. The only concern I think is if this changes the mulled hash, which I haven't checked.

**Comment by bernt-matthias** [comment]
Which conda package is this?

**Comment by bernt-matthias** [comment]
The problem seems to be the tool .. https://github.com/wm75/mimodd_galaxy_wrappers/blob/4a61a4b919b9a6fafd5fe3c76759394d10af9c85/macros.xml#L19C20-L19C20

**Comment by mvdbeek** [comment]
Well, no, we shouldn't ever break old requirements.

**Comment by nsoranzo** [comment]
> The only concern I think is if this changes the mulled hash, which I haven't checked.

By looking at the [code](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tool_util/deps/conda_util.py#L493) I think this is affected as well.

**Comment by bernt-matthias** [comment]
Interestingly, due to this bug also some tool tests passed that should not have passed: https://github.com/galaxyproject/tools-iuc/pull/5413
