### ISSUE TITLE
Collection Operations

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1644]
See huge back story here - https://github.com/galaxyproject/galaxy/pull/1313. Trello card here https://trello.com/c/ryKJrsYc.

These are important changes that were deadlocked in 16.01 on people (@bgruening, @erasche, @jxtx mostly) not being willing to commit JavaScript as a scripting language exposed to bioinformaticains through Galaxy.

I have rebased the changes in my downstream work on CWL for Galaxy just to unify all of my workflow changes in one branch - https://github.com/common-workflow-language/galaxy - so an up to date implementation of collection operations is available there.

**Comment by lparsons** [comment]
Two operations that would be very helpful:
1. Create a _List of Dataset Pairs_ from two _Dataset Lists_
2. Create a _List of Dataset Pairs_ from multiple _Dataset Pairs_
