### ISSUE TITLE
Error parsing tool metadata from bio.tools

### ISSUE THREAD

**Issue by domgz** [galaxyproject/galaxy#16445]
**Describe the bug**
Parsing bio.tools data for tool metadata is broken, ~~probably because of [research-software-ecosystem/content#fd9ed50](https://github.com/research-software-ecosystem/content/commit/fd9ed504b2a8b403f8df43262254f080f868ed1f) or [research-software-ecosystem/content#7b40d92](https://github.com/research-software-ecosystem/content/commit/7b40d92c30c924862a5048e55f2189d3d4f476f8)~~ (sorry, we are [using this feature just since last night](https://github.com/usegalaxy-eu/infrastructure-playbook/compare/master%40%7B2023-07-23%7D...master%40%7B2023-07-24%7D)). The keys "function" and "topic" do not exist any longer for many tools. Thus, such tools fail to load.

- Sample Sentry error report from [usegalaxy.eu](https://usegalaxy.eu/) (key "function" missing):
https://sentry.galaxyproject.org/organizations/galaxy/issues/123152/events/291df96a5e694baa978051863bb16e51/
> [...]
> Error reading tool from path: toolshed.g2.bx.psu.edu/repos/devteam/get_flanks/077f404ae1bb/get_flanks/get_flanks.xml
> [...]
> exception KeyError: 'function'

- Sample Sentry error report from [usegalaxy.eu](https://usegalaxy.eu/) (key "topic" missing): https://sentry.galaxyproject.org/organizations/galaxy/issues/123151/events/9156051efa734ae09f7643d86fa54ac6/
> [...]
> Error reading tool from path: toolshed.g2.bx.psu.edu/repos/iuc/b2btools_single_sequence/b694a77ca1e8/b2btools_single_sequence/b2btools_single_sequence.xml
> [...]
> exception KeyError: 'topic'

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0.4.dev0
Commit: [6af19176966a6e379ca84c406e90d856c45c3abe](https://github.com/usegalaxy-eu/galaxy/commit/6af19176966a6e379ca84c406e90d856c45c3abe) (from the [usegalaxy-eu/galaxy](https://github.com/usegalaxy-eu/galaxy) fork)

**To Reproduce**
1. Start Galaxy (web handlers, e.g. `/opt/galaxy/venv/bin/gunicorn galaxy.webapps.galaxy.fast_factory:factory() --timeout 600 --pythonpath lib -k galaxy.webapps.galaxy.workers.Worker -b unix:/opt/galaxy/mutable-data/gunicorn_2.sock`)
2. Messages such as `Error reading tool from path: toolshed.g2.bx.psu.edu/repos/devteam/get_flanks/077f404ae1bb/get_flanks/get_flanks.xml` show up in the logs. 
3. The [tool's page](https://usegalaxy.eu/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Fget_flanks%2Fget_flanks1%2F1.0.0&version=latest) shows the message _"Loading tool toolshed.g2.bx.psu.edu/repos/devteam/get_flanks/get_flanks21/1.0.0 failed: Could not find tool with id 'toolshed.g2.bx.psu.edu/repos/devteam/get_flanks/get_flanks1/1.0.0'. "_

**Expected behavior**
The tool loads and can be used, which is a better outcome than not loading the tool at all, even if the EDAM annotations become unavailable.

**Screenshots**
![grafik](https://github.com/galaxyproject/galaxy/assets/43052541/392a5ee7-913c-4917-b043-56a5b2e0eef7)

**Additional context**
We created usegalaxy-eu/galaxy#179 to quickly address the problem because a lot of important tools were missing. I would like to suggest that whatever fix you decide to apply, you apply the changes on top of the latest commit from such PR, so that we have a clean history and no merge conflicts when syncing back the upstream fix. Please be aware also of the remark at the end of the PR: you can merge this branch all the way back to Galaxy 21.09 where the code involved in the issue was introduced.

**Comment by mvdbeek** [comment]
This should be fixed in https://github.com/galaxyproject/galaxy/pull/16449, thanks @kysrpex !
