### ISSUE TITLE
Permanently hide or collapse job info sections

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#16441]
I frequently need to see job details when looking at bug reports, and the carbon emission and aws data is in the way (the carbon footprint also appears larger than other elements on that page, so that makes it worse). Can we have the individual sections be configurable in a way that I can hide / show / rearrange them ?

<img width="1768" alt="Screenshot 2023-07-24 at 13 11 24" src="https://github.com/galaxyproject/galaxy/assets/6804901/da58f30a-9820-44e1-8658-fe467e116147">

**Comment by bgruening** [comment]
Would tabs work here?

**Comment by dannon** [comment]
Just shifting it down to the bottom would be enough.  I also would prefer it to be configurable so folks can opt out of all the extra information displayed (both AWS estimate and carbon footprint).

**Comment by bgruening** [comment]
AWS switch: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample#L1236
Carbon switch: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample#L1246

**Comment by dannon** [comment]
@bgruening Ah!  It's always good to think "Huh, this should really work like <X>", and then find out that it does :)  Should have looked before I leapt.

Another option might be to add a user-level preference for hiding/toggling them, if they're particularly disruptive?

**Comment by bgruening** [comment]
I would really go for tabs, link addressable tabs. And potentially move stdout and stderr in a tab interface into the middle panel. Big discussion. But let's think big here. What information is useful for researchers, admins etc ... and what do we maybe want to move more into the user-focus what not.

For the scope of this issue, let's move it to the bottom of the page.
If we do toggling/hiding we could store this in the state I guess. So you need to hide once and it stays.

**Comment by dannon** [comment]
I have some WIP that does link addressable tabs for the dataset view, but it's got view, metadata, details, etc. as toplevel tabs.  I hesitate to add this as one, or worse, have two tiers of tabs?  It's something I want to dust off in the next week or two though.

**Comment by mvdbeek** [comment]
I am aware that option exists, but I can't just disable it at every Galaxy instance I work on ;)
