### ISSUE TITLE
Configuration is loaded twice in the client

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/galaxy#16455]
**Describe the bug**
The configuration is loaded once via API, and once it is included in the initial html.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: dev

**To Reproduce**
1. Open galaxy
2. Check HTML response in network inspector, where configuration is inlined.
3. Check network inspector to see that the configuration is additionally fetched via the API

**Expected behavior**
Configuration is only retrieved once

**Screenshots**

**Additional context**
This was observed in #16454, as these two configurations can diverge.

**Comment by davelopez** [comment]
We discussed this briefly in the last UI/UX meeting.

I've checked again and I think after https://github.com/galaxyproject/galaxy/pull/16514 and https://github.com/galaxyproject/galaxy/pull/16562 we are loading the configuration object only once.

In the meeting, it was mentioned that we may still want to reload the config when logging in (as it can be an admin user with extra config options) but this is working now as we reload the entire app anyway. Once we get to a full single page with 0 reloads we should make sure it's reloading it.

So I will go ahead and consider this done :tada: please reopen if you think there is still an issue.
