### ISSUE TITLE
Disk storage issue

### ISSUE THREAD

**Issue by Fakihaaa** [galaxyproject/galaxy#16468]
Hello, 

I am having this issue yet again just as #16317. I have been deleting files but they are not showing up in the deleted datasets, tried refreshing as well, didn't work. Please help me resolve this issue. I have just a final tool to use and then I will be done with my analysis.

_Originally posted by @Fakihaaa in https://github.com/galaxyproject/galaxy/issues/16336#issuecomment-1652305928_

**Comment by mvdbeek** [comment]
Please contact the server administrators to help you find data.
