### ISSUE TITLE
Memory hungry web workers on 23.1

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#16476]
Since Nate is on holiday I will open this issue.
On ORG we can see unusual memory consumption that is [growing over time](https://stats.galaxyproject.org/d/000000007/big-picture?orgId=1&refresh=1m&viewPanel=14&from=now-24h&to=now). This yields to the need to restart the processes regularly and blocks the update on EU.

**Comment by mvdbeek** [comment]
It should definitely not block the update on .eu, I said before that that is a highly questionable conclusion, definitely wrt the new release. This also only concerns the web worjker. Please update ASAP and give feedback before the relase.
