### ISSUE TITLE
Porting schemas to pydantic 2

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#16498]
There's a migration guide and a migration utility here: https://docs.pydantic.dev/latest/migration/. I do suspect this is going to be a significant amount of work that we should tackle soon.

**Comment by davelopez** [comment]
I can try to give this a go as soon as I finish my current main project (InvenioRDM integration)

**Comment by mvdbeek** [comment]
I did look into that yesterday, and I've made some good progress to the point where I can load the model (but fastapi and fastapi-utils are striking out for now). I think I can finish this soon-ish.

**Comment by davelopez** [comment]
> but fastapi and fastapi-utils are striking out for now

Even after upgrading FastAPI at least to version 0.100.0?

**Comment by mvdbeek** [comment]
Yeah, because we carry some patches that modify the openapi schema

**Comment by mvdbeek** [comment]
Done in #17262
