### ISSUE TITLE
Make it more obvious that you can click on Step to see details in invocation summary

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#16502]
![image](https://github.com/galaxyproject/galaxy/assets/6804901/72de209f-bacb-4725-b666-52b36c7a3355)

Not sure what icon we could use, there are probably quite some options. Maybe a `+` ?

**Comment by davelopez** [comment]
I would suggest a "chevron down" or similar `⌄`
The `+` would align more with "create" or "add" I think.
