### ISSUE TITLE
Galaxy responds 403 to Pulsar POST request for output's extra files

### ISSUE THREAD

**Issue by martindemko** [galaxyproject/galaxy#16508]
**Describe the bug**
When using the `extra_files_path` attribute, the extra files directory is created in `outputs` directory as is the particular output dataset and so it's recognized and transferred. Unfortunately, Galaxy does not accept the transfer and responds with 403. I tracked this error to this [place](https://github.com/galaxyproject/galaxy/blob/77632581bc0a8a21b9279af4b86e793956edbbeb/lib/galaxy/webapps/galaxy/api/job_files.py#L146) and the error I see is written in pulsar log not in Galaxy log but here it is (simplified a bit):
```
"err_code": 403002,
"traceback": "Traceback (most recent call last):
  File \"/srv/galax/server/lib/galaxy/web/framework/decorators.py\", line 337, in decorator
    rval = func(self, trans, *args, **kwargs)
  File \"/srv/galaxy/server/lib/galaxy/webapps/galaxy/api/job_files.py\", line 87, in create
    self.__check_job_can_write_to_path(trans, job, path)
  File \"/srv/galaxy/server/lib/galaxy/webapps/galaxy/api/job_files.py\", line 146, in __check_job_can_write_to_path
    raise exceptions.ItemAccessibilityException(\"Job is not authorized to write to supplied path.\")
galaxy.exceptions.ItemAccessibilityException: Job is not authorized to write to supplied path."
```
normaly it should be `"message": "OK"`. Also I can see the following line:
```
Failures collecting results [Exception('Failed to post_file properly for url https://.../api/jobs/8fd4994e67b80b0d/files?job_key=148e53defffcc655&path=%2Fdata%2Fdatasets%2Ff%2F8%2Fc%2Fdataset_f8c290be-b573-451c-bcea-2b2ddf010a28_files%2Ffile.txt&file_type=output, remote server returned status code of 403.')]
```

I'm aware of [the issue](https://github.com/galaxyproject/pulsar/issues/296#issuecomment-1519000143), and you may see that they use the old attribute `files_path` instead of the newer one `extra_files_path` and that's probably why they needed the hack. Unfortunately, it's not working anymore (at least not in my configuration, as Alphafold is one of the tools I used for testing). As advised, I use `outputs_to_working_directory: false` in destinations for pulsar runner and `outputs_to_working_directory: true` in galaxy.yml under `galaxy:` but I tried to set this general setting to `false` and it was of no help.

[Here](https://github.com/galaxyproject/galaxy/blob/77632581bc0a8a21b9279af4b86e793956edbbeb/lib/galaxy/webapps/galaxy/api/job_files.py#L145C1-L145C1) in this condition, Galaxy checks if file for transfer is not in `working` directory (which is not) and not an output file (which is not) then transfer fails. But if the extra output files are not in `outputs` directory next to the output file (according to `outputs_to_working_directory: false`) then they are ignored according to [this](https://github.com/galaxyproject/pulsar/blob/31d8a99a041d4d53da740d0d4ea8a7661c08f6d9/pulsar/client/staging/down.py#L107), in my humble opinion.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: major 23.0, minor 4.dev0
Pulsar Version: 0.15.2

[app.yml.txt](https://github.com/galaxyproject/galaxy/files/12245265/app.yml.txt)
[galaxy.yml.txt](https://github.com/galaxyproject/galaxy/files/12245266/galaxy.yml.txt)

**Comment by martindemko** [comment]
Since nobody responded, I tried to hack this and added another condition at line 162 in `lib/galaxy/webapps/galaxy/api/job_files.py`:
```
elif os.path.abspath(path).startswith(os.path.abspath(dataset.file_name)[:-4]+"_files/"):
                    return True
```
which forces Galaxy to allow extra files to be downloaded and stored in the proper place. 
However, when I open the HTML output, extra files are still linked badly. I feel desperate cause I really tried, and yet there is another hidden catch. 
Another thing connected with this I don't understand is why these datasets have no value in column _extra_files_path in the database.
Please, can somebody who understands Galaxy+Pulsar connection help me? We can't use our instances like this cause all of them possess the same issue. Thank you.

**Comment by mvdbeek** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/16541
