### ISSUE TITLE
Request for collection dataset tagging

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/galaxy#16512]
Users would like the functionality to tag a dataset inside of a collection, which you can currently only do by going to 'Show hidden datasets' and tagging there

**Comment by bernt-matthias** [comment]
Duplicates 
https://github.com/galaxyproject/galaxy/issues/14399
https://github.com/galaxyproject/galaxy/issues/13416
https://github.com/galaxyproject/galaxy/issues/11745

Maybe this is the solution / workaround https://usegalaxy.eu/root?tool_id=__TAG_FROM_FILE__

**Comment by nsoranzo** [comment]
Duplicate of #14399.
