### ISSUE TITLE
regression of tool panel search for tool id 

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16525]
When searching the panel for an exact (installed) `tool_id` on usegalaxy.org the hit is not found.

try searching e.g. for `liftOver1` or `cshl_fastx_quality_statistics` and check https://usegalaxy.org/root?tool_id=liftOver1

xref original implementation: https://github.com/galaxyproject/galaxy/pull/9744

**Comment by mvdbeek** [comment]
<img width="1913" alt="Screenshot 2023-08-08 at 16 11 02" src="https://github.com/galaxyproject/galaxy/assets/6804901/8a055dd6-faf0-4fc5-bbc8-beb8f550fff3">

close ?

**Comment by martenson** [comment]
@mvdbeek I am aware of advanced search. Is the default search supposed to ignore tool ids?

**Comment by dannon** [comment]
The default isn't a search so much as it is a filtering now, but we could include tool ids in this fast-filtering.

**Comment by mvdbeek** [comment]
I like that you got to go to the advanced search to search for tool id. That seems very niche and bad ids would mess with the search I guess ?

**Comment by ahmedhamidawan** [comment]
So, should we add the `id` as a searchable field to the side panel search?
There could be two ways:
1. we just add `id` to https://github.com/galaxyproject/galaxy/blob/d35ce3dca90e3f1fbf5ae1c4ed65d27253d03e75/client/src/components/Panels/Common/ToolSearch.vue#L14 changing it to:
    ```
    const KEYS = { exact: 4, name: 3, description: 2, combined: 1, id: 0 };
    ```
    and that will make ids searchable (as the lowest priority order) by just searching: filterText = `liftOver1`. This will however mean that the query will return matches for name, description and id fields, producing a large list of results which is something we wanted to avoid with the new `ToolSearch`
2. we add keys to the `filterText`, making the query: filterText = `id:liftOver1`. This will be a bigger code change and potentially confuse users who will expect the `ToolSearch` to work the same way as the `HistoryFilters` in the right panel; where the `filterSettings` for the advanced filters are reactive to the filterText, which is not the case in the `ToolSearch`

**Comment by mvdbeek** [comment]
2 sounds good to me. The search in the advanced search is visually distinct and happening in the main panel, I don't think it will be too confusing ?

**Comment by ahmedhamidawan** [comment]
Alright, so should this change go to 23.1 or 23.2?

**Comment by mvdbeek** [comment]
I think dev is ok, this hasn't worked since we moved to the frontend search and noone noticed until now. Otherwise it should go to 23.0 ?

**Comment by dannon** [comment]
I think dev's totally fine for this.  Looking at it, I'm wondering if option1 would have been fine and more natural, though.  Just how cluttered were the results were without requiring the specific `id` prefix?

**Comment by mvdbeek** [comment]
That depends on how bad your chosen ids are, which is beyond our control. It's a judgement call, but I think only devs search for tool ids, so it shouldn't mess with results by default.
