### ISSUE TITLE
Support genome browser chain file format

### ISSUE THREAD

**Issue by claudiofr** [galaxyproject/galaxy#16539]
Support a new genome browser file format called chain format.

[https://genome.ucsc.edu/goldenPath/help/chain.html](https://genome.ucsc.edu/goldenPath/help/chain.html)

**Comment by claudiofr** [comment]
Please assign this to me.

**Comment by claudiofr** [comment]
Also I noticed there is only a datatypes_conf.xml.sample file in the source tree. There is no datatypes_conf.xml file as the "adding a new datatype" documentation indicates. Do I add the new data type to the .sample file?

**Comment by dannon** [comment]
@claudiofr Yes, that's correct.

**Comment by claudiofr** [comment]
As far as testing is concerned I added a doctest in the sniff_prefix method that sniffed sample chain files and non-chain files. That is the only testing I found for the other file formats. Do I need to do more than that?

**Comment by bernt-matthias** [comment]
My impression is that https://github.com/galaxyproject/galaxy/tree/dev/test/unit/data/datatypes is a better alternative to the unit tests.
