### ISSUE TITLE
BioCompute Object (BCOs) export tool, wrong data URIs

### ISSUE THREAD

**Issue by agbiotec** [galaxyproject/galaxy#16535]
Hello, I found that when exporting BCOs of invoked / completed workflows, the URIs for data reference is:

https://usegalaxy.org/api/datasets/bbd44e69cb8906b55f7a4f45d76d2982/display

the "/display" leads to error when trying to reference the data on the server, it needs to be :
https://usegalaxy.org/api/datasets/bbd44e69cb8906b55f7a4f45d76d2982

Thank you

**Comment by mvdbeek** [comment]
No, this is correct. The file has been deleted on the server.
