### ISSUE TITLE
Missing tool re-run option

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/galaxy#16548]
Sometimes (inconsistently) when tools fail, they don't give me a re-run option (this didn't happen with previous Galaxy versions)

History showing error:
https://humancellatlas.usegalaxy.eu/u/wendi.bacon/h/copy-of-anndata---sce

Photo showing error:
![Screenshot 2023-08-14 at 10 46 50](https://github.com/galaxyproject/galaxy/assets/44605769/65ce9a31-5d95-4fa4-97ea-9555c69235c8)

usegalaxy.eu
Don't know the version, and I use Galaxy via the interface not commandline so...

**Expected behavior**
I should see a re-run button

**Comment by mvdbeek** [comment]
This happens when the tool is not installed, or the web handler hasn't loaded the tool correctly. This is not a Galaxy bug per se, but something the usegalaxy.eu admins would need to look into.

**Comment by nomadscientist** [comment]
Follow-up:
The re-run option DOES exist on the initial (failed) tool run, dataset 7, just not on any subsequent re-runs of the tool.

**Comment by sanjaysrikakulam** [comment]
I have restarted the required handlers (just in case). After importing the shared history I can confirm that the re-run option is available on all the elements.
