### ISSUE TITLE
Workflow report doesn't display png or jpg image

### ISSUE THREAD

**Issue by AnnaSyme** [galaxyproject/galaxy#16558]
**Describe the bug**
Dataset image is included in the workflow report, but it does not display. It says "no content found". Tried for both a png and a jpg, as output from the Bandage tool. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Australia

**Comment by assuntad23** [comment]
Hey @AnnaSyme.
I was unable to reproduce this, myself. Could you check the markdown used to generate the report and ensure that it includes : 
``` galaxy
history_dataset_as_image(output="image")
```

If you try it again, and it still isn't working, please share it with me, so I can copy exactly what you have and continue to attempt reproducing the issue. Thanks!

**Comment by dannon** [comment]
Feel free to reopen with more details, thanks!

**Comment by hexylena** [comment]
https://usegalaxy.eu/published/page?id=cd781148a714c5a6 here's a repro, pulled from https://github.com/galaxyproject/galaxy/issues/15220#issuecomment-1582857106 probably doesn't happen on .org due to default dataset permissions being open

**Comment by martenson** [comment]
that

**Comment by dannon** [comment]
Thank you @hexylena!

**Comment by hexylena** [comment]
thanks for the quick fix @dannon !!
