### ISSUE TITLE
Published history component missing pagination, search by owner

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#16568]
Someone has published https://usegalaxy.org/histories/list_published?f-username=alvin_chew in a paper, it would be nice if we could keep this functional (although of course that url should have never been published). Looking at this, there is no way to search by owner, and we're also missing pagination.

**Comment by martenson** [comment]
Do we really want to support the format of `/histories/list_published?f-username=userA`? And if so will we adapt the rest of the filter parameters to work the same way or will this be a grandfathered exception to some more standard shareable url building we  implement?

**Comment by dannon** [comment]
xpost from slack to keep the discussion here:
 
I don't think we want to encourage that as a formal interface.  Especially as a companion to a publication, I think a proper Galaxy Page with the shared histories embedded (and the option to add custom summary text, etc) would have been the option we should push.  Those are slugified, static URLs intended for sharing.
