### ISSUE TITLE
Feedback for CWL v1.2.1 requested

### ISSUE THREAD

**Issue by acoleman2000** [galaxyproject/galaxy#16566]
Hello,

We are asking for feedback for the CWL v1.2.1 release.

Changelogs for the release can be found below:

Workflow / ExpressionTool / Operation:
https://deploy-preview-115--cwl-v1-2-dev.netlify.app/workflow#Changelog_for_v1.2.1

CommandLineTool:
https://deploy-preview-115--cwl-v1-2-dev.netlify.app/commandlinetool#Changelog_for_v1.2.1

You can provide your feedback, as well as see a full summary of changes here: https://github.com/common-workflow-language/cwl-v1.2/pull/115.

We ask that all feedback be provided by August 31st.

Thanks!

**Comment by mr-c** [comment]
@mvdbeek @nsoranzo is the galaxy-cwl branch using the new conformance tests proposed for CWL v1.2.1 yet? https://github.com/common-workflow-language/cwl-v1.2/blob/1.2.1_proposed/conformance_tests.yaml

**Comment by mr-c** [comment]
> is the galaxy-cwl branch using the new conformance tests proposed for CWL v1.2.1 yet? https://github.com/common-workflow-language/cwl-v1.2/blob/1.2.1_proposed/conformance_tests.yaml

The answer is no; fix for that is at https://github.com/galaxyproject/galaxy/issues/16566

**Comment by mr-c** [comment]
We are now running the CWL v1.2.1 conformance tests in https://github.com/galaxyproject/galaxy/pull/12909/
