### ISSUE TITLE
Tool form does not update

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#16602]
**Describe the bug**
When switching datasets in tool forms associated dynamic parameters such as e.g. the column selector do not properly react to changes.

**Galaxy Version and/or server at which you observed the bug**
In current dev.

**To Reproduce**
1. Go to 'Merge Column' tool
2. Select different tabular datasets
3. Notice how the column selectors are not updated properly

**Demo**

https://github.com/galaxyproject/galaxy/assets/2105447/34eefc7f-c89f-4b43-87c5-7b49c4b5f27f

**Comment by mvdbeek** [comment]
I think you fixed this in https://github.com/galaxyproject/galaxy/pull/16578 ?

**Comment by ElectronicBlueberry** [comment]
I can no longer reproduce this on dev.
@guerler could you please post an updated clip, if you can still reproduce this?

**Comment by guerler** [comment]
Fascinating, yes it does actually seem to be resolved. Thank you for taking a look!
