### ISSUE TITLE
Problem copying/importing list of dataset pair collections

### ISSUE THREAD

**Issue by gallardoalba** [galaxyproject/galaxy#16619]
**Describe the bug**
When a history with a list of dataset pair collection is imported (copied) from other user, the individual files (hidden) get purged, so it is not possible to work on the collection. The same behavior manifests when a list of dataset pair collection is copied between histories.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1 (but also observed in the previous release)

**To Reproduce**
1. Import this history: [https://usegalaxy.eu/u/gallardoalba/h/bazarevichanalysis](https://usegalaxy.eu/u/gallardoalba/h/bazarevichanalysis)
2. Create a new history and rename it as "test history"
3. Copy the dataset **1: All samples** to the new history
4. Run the tool [Extract element identifiers](https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/collection_element_identifiers/collection_element_identifiers/0.0.2) on the copied collection, located in the "test history".
5. Get the error: Input dataset 'forward' was deleted before the job started, Input dataset 'reverse' was deleted before the job started.

**Expected behavior**
Extract ids from collection.

**Screenshots**
![Screenshot from 2023-08-30 12-11-01](https://github.com/galaxyproject/galaxy/assets/26678117/0923f942-9c04-4072-9b3f-1ccab2879571)

**Comment by mvdbeek** [comment]
No, they are not purged, and they are also not available to the user. Sample 1 is on a job that has been deleted.

**Comment by gallardoalba** [comment]
Sorry, I didn't understand the reason. I found a similar error when trying to copy my own list of dataset pair collections (not imported from other user) between histories.

**Comment by gallardoalba** [comment]
Yes, but if you check the [original history](https://usegalaxy.eu/u/gallardoalba/h/bazarevichanalysis), the original ones are there. But it seems that when copying the collection, they are deleted for some reason. So basically it seems currently not possible to copy  list of dataset pair collections between histories.

**Comment by mvdbeek** [comment]
no, they're not. you collection is there, but the members are deleted. like i said, you can do this by showing hidden datasets and then deleting them. This  is the data for your collection: https://usegalaxy.eu/api/dataset_collections/647f0d8eec0a17d2/

**Comment by mvdbeek** [comment]
When did you run something using that collection ? I can't see how that would work **now**. No, I don't think these are the members of your collection.

**Comment by mvdbeek** [comment]
No, but run any tool on the original collection. It shouldn't work now.

**Comment by gallardoalba** [comment]
> No, but run any tool on the original collection. It shouldn't work now.

Yes, you are right, but the fact is that I didn't delete those files. I'll share a different example.

**Comment by gallardoalba** [comment]
This history was for example recently shared by an user with me https://usegalaxy.eu/published/history?id=fa60632374233e95

**Comment by bgruening** [comment]
I guess the point is that no one is deleting actively the datasets and are marked as deleted.

@gallardoalba can you write down a reproducible example, step by step with a new history? Starting by uploading a few tiny datasets, and creating the collection. Copying it and after every step checking the state of the underlying datasets?

I will then try to reproduce that tomorrow.

**Comment by gallardoalba** [comment]
Yes, here for example there's other example that I just generated. This is the original history, where I ran a workflow [https://usegalaxy.eu/u/gallardoalba/h/genome-wide-alternative-splicing-analysis-prjna933625](https://usegalaxy.eu/u/gallardoalba/h/genome-wide-alternative-splicing-analysis-prjna933625) . In this one I just copied from the original history the required datasets for running the workflow [https://usegalaxy.eu/u/gallardoalba/h/genome-wide-alternative-splicing-analysis-prjna933625](https://usegalaxy.eu/u/gallardoalba/h/test-aba-history).  I'm pretty sure that I didn't delete the files from the original history.

**Comment by gallardoalba** [comment]
> Yes, here for example there's other example that I just generated. This is the original history, where I ran a workflow https://usegalaxy.eu/u/gallardoalba/h/genome-wide-alternative-splicing-analysis-prjna933625 . In this one I just copied from the original history the required datasets for running the workflow https://usegalaxy.eu/u/gallardoalba/h/test-aba-history. I'm pretty sure that I didn't delete the files from the original history.

But I only saw that problem with list of dataset pair collections, not with regular collections.

**Comment by gallardoalba** [comment]
> I guess the point is that no one is deleting actively the datasets, but they are marked as deleted.
> 
> @gallardoalba can you write down a reproducible example, step by step with a new history? Starting by uploading a few tiny datasets, and creating the collection. Copying it and after every step checking the state of the underlying datasets?
> 
> I will then try to reproduce that tomorrow.

Yes, I'll create an example with tiny datasets. Thanks for checking!

**Comment by wm75** [comment]
> Yes, here there's other example that I just generated. This is the original history, where I ran a workflow https://usegalaxy.eu/u/gallardoalba/h/genome-wide-alternative-splicing-analysis-prjna933625 . In this one I just copied from the original history the required datasets for running the workflow https://usegalaxy.eu/u/gallardoalba/h/test-aba-history. I'm pretty sure that I didn't delete the files from the original history.

@gallardoalba in https://usegalaxy.eu/u/gallardoalba/h/genome-wide-alternative-splicing-analysis-prjna933625 the elements of `1: All datasets` are not stored as part of the history, but actually live, through yet another indirection in history `b235e5288410a5de`. 
If you check https://usegalaxy.eu/published/history?id=b235e5288410a5de you'll learn that this entire history has been purged.
What's funny is that the actual data is still available. You can download it via dataset details -> File contents

**Comment by wm75** [comment]
What I'm not quite sure about is how you ended up in this situation where you have to follow essentially two links from the history you shared here to the underlying data. Do you recall how you did this?
