### ISSUE TITLE
Wrong keyword?

### ISSUE THREAD

**Issue by vazovn** [galaxyproject/galaxy#16610]
**Describe the bug**
There is a method in` ../server/lib/galaxy/authnz/psa_authnz.py` - _refresh_. Before refreshing, galaxy compares the _auth_time_ and the _expiration time_. The key for the expiration time is "expires"  : see `user_authnz_token.extra_data["expires"]`

This causes the following error :

```galaxy.authnz.managers ERROR 2023-08-29 10:56:11,584 [pN:main.2,p:87810,tN:WSGI_4] An error occurred when refreshing user token: 'expires'
```

and the traceback shows :

```
Aug 29 12:46:53 galaxy01-test.educloud.no galaxyctl[193989]: KeyError: 'expires'
Aug 29 12:46:53 galaxy01-test.educloud.no galaxyctl[193989]: galaxy.authnz.managers ERROR 2023-08-29 12:46:53,289 [pN:main.2,p:194198,tN:WSGI_0] An error occurred when refreshing user token: 'expires'
Aug 29 12:46:53 galaxy01-test.educloud.no galaxyctl[193989]: uvicorn.access INFO 2023-08-29 12:46:53,291 [pN:main.2,p:194198,tN:MainThread] 84.234.130.219:0 - "GET /history/current_history_json?since=2023-08-29T09:42:53.034014 HTTP/1.0" 200
Aug 29 12:46:54 galaxy01-test.educloud.no galaxyctl[193989]: Traceback (most recent call last):
Aug 29 12:46:54 galaxy01-test.educloud.no galaxyctl[193989]:   File "/cluster/galaxy-test/srv/galaxy/server/lib/galaxy/authnz/managers.py", line 333, in refresh_expiring_oidc_tokens_for_provider
Aug 29 12:46:54 galaxy01-test.educloud.no galaxyctl[193989]:     refreshed = backend.refresh(trans, auth)
Aug 29 12:46:54 galaxy01-test.educloud.no galaxyctl[193989]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 29 12:46:54 galaxy01-test.educloud.no galaxyctl[193989]:   File "/cluster/galaxy-test/srv/galaxy/server/lib/galaxy/authnz/psa_authnz.py", line 175, in refresh
Aug 29 12:46:54 galaxy01-test.educloud.no galaxyctl[193989]:     if int(user_authnz_token.extra_data["auth_time"]) + int(user_authnz_token.extra_data["expires"]) / 2 <= int(
Aug 29 12:46:54 galaxy01-test.educloud.no galaxyctl[193989]:    
```

The OIDC providers normally return standard key `expires_in` and this is the correct key in the doc of the file `psa_authnz.py`

Could you replace `expires` by `expires_in` in method _refresh_ in the file `psa_authnz.py`

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version:  23.01

**To Reproduce**

Can be reproduced on any instance with OIDC login enabled. Pops up in the logs.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mvdbeek** [comment]
I assume this can be either `expires` or `expires_in`, do you happen to know @SergeyYakubov ?

**Comment by SergeyYakubov** [comment]
Yes, it seems the problem is with social_core - https://github.com/python-social-auth/social-core/issues/760.

Depending on the backend provider, it sets either `expires` or `expires_in`
e.g. for [Google](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/google.py#L74) or [Atlassian](https://github.com/python-social-auth/social-core/blob/master/social_core/backends/atlassian.py#L14).

So, we should check both.
