### ISSUE TITLE
Improve Sentry Galaxy job error reports

### ISSUE THREAD

**Issue by domgz** [galaxyproject/galaxy#16637]
Sentry is a very powerful tool to keep an eye on everything. However, when it comes to keeping track of Galaxy job errors, the experience is still lacking. I would like to point out what I think can be improved.

## Event message

Currently, it is filled using a template that looks as follows:

```python
ERROR_TEMPLATE = """Galaxy Job Error: {tool_id} v{tool_version}

Command Line:
{command_line}

Stderr:
{stderr}

Stdout:
{stdout}

The user provided the following information:
{message}"""
```

In practice this translates to very verbose error messages that are even redacted because of their length.

> Galaxy Job Error: toolshed.g2.bx.psu.edu/repos/devteam/emboss_5/EMBOSS: compseq14/5.0.0.1 v5.0.0.1 Command Line: compseq -sequence '/data/dnb09/galaxy_db/files/\*/\*/\*/dataset_\*\*\*\*\*\*\*\*-\*\*\*\*-\*\*\*\*-\*\*\*\*-\*\*\*\*\*\*\*\*\*\*\*\*.dat' -outfile '/data/jwd02f/main/\*\*\*/\*\*\*/\*\*\*\*\*\*\*\*/outputs/dataset_\*\*\*\*\*\*\*\*-\*\*\*\*-\*\*\*\*-\*\*\*\*-\*\*\*\*\*\*\*\*\*\*\*\*.dat' -word 2 -frame 0 -auto Stderr: Error: Unable to read sequence '/data/dnb09/galaxy_db/files/\*/\*/\*/dataset_\*\*\*\*\*\*\*\*-\*\*\*\*-\*\*\*\*-\*\*\*\*-\*\*\*\*\*\*\*\*\*\*\*\*.dat' Died: compseq terminated: Bad value for '...

All of this information except for the first line (the event's title) is redundant because it is included later in the form of a Sentry context. I would suggest to remove all of it and just keep the title, because Sentry seems to merge Galaxy job errors exclusively by title. For example, [this diamond report](https://sentry.galaxyproject.org/organizations/galaxy/issues/80064/events/79e5c38f240343c49f64f84835293982/?project=7&query=+is%3Aunresolved+diamond&referrer=next-event&sort=freq&statsPeriod=24h) covers at least two different errors: `Error: Error detecting input file format. First line must begin with '>' (FASTA) or '@' (FASTQ).` and `Error: Error reading input stream at line 2: Invalid character (L) in sequence`.

Moreover, due to the way Sentry merges events, errors for different versions of the same tool are reported as different issues. Removing the version from the event's title would solve this problem.

## Tags

At the moment, two tags are added to bug reports: "tool_id" and "tool_version". The tag "tool_id" includes the tool's version so it cannot be used to filter by tool.

I propose to use three tags instead:
- "tool" for `job.tool_id`
- "tool.name" for the tool's name (tool id without version)
- "tool.version" for the tool's version.

## Report level

Galaxy job error reports are submitted with level "info". I guess it makes sense to submit them with level "error".

## User information

Sentry provides `sentry_sdk.set_user` to attach user information to a report, yet Galaxy puts user information in a "user" context instead, as well as the email (redundantly) in the "job" context. 

The biggest drawback of this approach is that while Sentry allows to see how many users are affected by an issue so that one can use that information to focus on solving the most impactful errors, because Galaxy is not using `sentry_sdk.set_user`, all Galaxy job errors show 0 affected users, rendering this feature useless.

## User's feedback

At the moment the user's feedback message is mixed with the rest of the job's information in the "job" context. I suggest to put it in a separate context "feedback" and, in addition, create a tag that can take the values "yes" or "no" depending on whether the report was automatic or the users provided feedback with the report. This helps to find bug reports sent intentionally.

There is even a better option, make Galaxy send the message to [Sentry's User Feedback API](https://docs.sentry.io/api/projects/submit-user-feedback/).

**Comment by mvdbeek** [comment]
Since y'all are the only users, sure go for it.

**Comment by kysrpex** [comment]
I think it makes sense to make @sanjaysrikakulam (and @mira-miracoli asynchronously) aware before submitting a PR.

**Comment by kysrpex** [comment]
@mvdbeek I see that there is no test coverage for Sentry (I assume because it is far from trivial and needs a Sentry instance). I guess [this Sentry project](https://sentry.galaxyproject.org/organizations/galaxy/projects/sentry-testing/?project=8) was created for testing error reports and I can use it to check that my branch works properly, right? Should I commit some tests, even if disabled with `@pytest.mark.skip` and thus not runnable out of the box? I suggest to disable them by default because they would depend on having a working DSN, which is maybe not a smart choice.
