### ISSUE TITLE
Prevent getting stuck in Tutorial pop-up window for non-tutorial links

### ISSUE THREAD

**Issue by hujambo-dunia** [galaxyproject/galaxy#16634]
![2023-08-31 14-09-21 2023-08-31 14_13_36](https://github.com/galaxyproject/galaxy/assets/3672779/b900060f-76fe-4ea6-b2e2-8d76d275d161)

Solution needed to prevent getting stuck (above video).

![2023-08-31 15-18-57 2023-08-31 15_23_08](https://github.com/galaxyproject/galaxy/assets/3672779/7c5479af-dfbc-4298-947d-63b7b2893b14)

Refreshing page (even when do hard-reload and cache clear) sometimes fails (above video).

Galaxy Version: 23 (on Galaxy US)

**To Reproduce**
1. To open the Tutorial pop-up window, in the top horizontal navigation, click the "graduation-cap" icon.
2. Will see the "Welcome to Galaxy Tutorials" Landing Page
3. Select a Topic. For example, click the "Introduction to Galaxy Analyses" link
4. Select slides from a Lesson. For example, next to "A short introduction to Galaxy" link, click the "slideshare" icon under "Slides" column.
5. Will see the slides load in the Tutorial pop-up window just fine.
6. However, when you close the pop-up and re-open, the user is stuck in the slides and cannot navigate to Tutorial Landing Page without refreshing the page --BUT REFRESHING DOESN'T ALWAYS WORK (see second video). Likely there is happening because there is a useful feature that "bookmarks" a user's place when a tutorial page appears in the pop-up window (possibly, we don't need this feature for non-tutorial content). 
7. Also, likely a user who needs a tutorial may be less likely to be familiar with all the ways to reset the application - as well there could be data in the form fields that the user hasn't saved which may make them reluctant to refresh the page even if that becomes a reliable solution. 

**Expected behavior**
Would be good to have some mechanism that always always user to get to the Tutorial Landing Page to reset the Tutorial pop-up window without refreshing the website. Ideas here include: (1) for the feature that is keeping track of where the user left off in the Tutorial, turn that feature off (or force cache clear?) for non-tutorial pages that get called within the pop-up (2) left-right arrow buttons that appear if mouse hovers to left-right panel of pop-up window (but should also be accessible) similar to a photo gallery (3) top-left "Tutorial Home" button that loads on top of whatever is inside of the pop-up window similar to a chatbot overlay (but with just a single link).

**Comment by hexylena** [comment]
With the popup open, you can just use the browser's back button to navigate out of a slide deck. Additionally there is a (rather small) button at the top of slides to also let you 'escape'

**Comment by hexylena** [comment]
> BUT REFRESHING DOESN'T ALWAYS WORK

refreshing should *never* work, we intentionally retain the page the user is on as a cognitive assist and for their convenience. 

I could definitely see a "get me out of here" type "go back to GTN home" button though, this is a good suggestion!

**Comment by hujambo-dunia** [comment]
Thanks @hexylena for the ideas to improve the interface in the long-term! :)

In the short-term, I think either: (1) removing the extra <A> tag DOM element or (2) controlling when it is turned on/off would work as illustrated in the below video. 

![video_Tutorial_Navigation_Fix_Suggestion](https://github.com/galaxyproject/galaxy/assets/3672779/a91540c5-5ff9-4999-af17-e3bd7857ad29)

**Comment by hujambo-dunia** [comment]
Sounds good - just in case, I found a quick fix which you/@hexylena and/or @shiltemann are welcome to review in [this PR](https://github.com/galaxyproject/training-material/pull/4361) currently in draft mode on your repo.

**Comment by hexylena** [comment]
Merged your PR, that's already a big improvement!

**Comment by dannon** [comment]
Going to close this one out as resolved enough w/ the buttons correctly available in slides.
