### ISSUE TITLE
activity bar sometimes ignores clicks

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16633]
There is something wrong with how activity bar behaves, given a certain sequence of actions it ignores clicks -- see the attached video where I am trying to open a tool panel but it needs 2 click. Similar things happens with inability to open other activity tabs. This is from Main.

https://github.com/galaxyproject/galaxy/assets/1814954/fd1fbbac-7a78-460f-9707-d00325ca7aeb

**Comment by ElectronicBlueberry** [comment]
This happens when the mouse slightly moves during a click, due to the drag handler on the activity bar. One way to work around this is for the drag to replace the click event only if the mouse traveled a set distance. Another could be to move the activity re-ordering to the activity bar settings

**Comment by martenson** [comment]
nice find! drag&drop reordering should be imho hidden by a settings menu/trigger
