### ISSUE TITLE
Layout on Registration Page messed up

### ISSUE THREAD

**Issue by hujambo-dunia** [galaxyproject/galaxy#16646]
![Greenshot 2023-09-05 17 56 08](https://github.com/galaxyproject/galaxy/assets/3672779/199adac2-2399-4fb1-b5e7-1fff8b4796b3)

Various layout inconsistencies on Registration Page. Unsure how this could be missed...

1. HTML Tag visible within the content
2. Terms of Service box cut off, not distinguished enough from rest of layout
3. "Subscribe" checkbox is misaligned

Galaxy Version: Release 23
Browser: Google Chrome on Mac OS

1. Go to https://usegalaxy.org/login/start?redirect=None

**Expected behavior**
The expected behavior is that we give new users a good first-impression.

**Comment by dannon** [comment]
Done in #16652
