### ISSUE TITLE
Cannot import history without modifying the name of the published history

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#16643]
I like the original name of this history, I'd like to keep it. I don't want it to be called "Copy of '...'" in this case, since that's visual noise for me.

![import dialog in galaxy with the import history button disabled](https://github.com/galaxyproject/galaxy/assets/458683/178b8b27-822d-4c7d-ae6b-4c0684428a90)

As soon as I make any modification I'm allowed to import it

![green check on the name validation](https://github.com/galaxyproject/galaxy/assets/458683/9afd6b3f-5710-4e44-bee3-a1849c9460cd)

Workaround: It seems I can import it and then remove the `.` I added to pass validation.

It is not my own history that I'm importing, if that's relevant.

**Comment by ahmedhamidawan** [comment]
Fixed in #16741

**Comment by hexylena** [comment]
Thanks so much @ahmedhamidawan !
