### ISSUE TITLE
Allow setting the name attribute on test collections

### ISSUE THREAD

**Issue by TomHarrop** [galaxyproject/galaxy#16654]
I'd like to be able to set the `element_identifier`  in tests.

If I do this

```xml
<test>
  <param name="paired_input">
    <collection type="paired" name="sample1">
      <element name="forward" ftype="fastqsanger.gz" value="sample1_1.fastq" />
      <element name="reverse" ftype="fastqsanger.gz" value="sample1_2.fastq" />
    </collection>
  </param>
</test>
```

`element_identifier` resolves to *sample1*, so this works as expected.

But linting fails with the error

```
.. ERROR: Invalid XML found in file: tool.xml. Errors [/tmp/tmp4dtg0hlu:245:0:ERROR:SCHEMASV:SCHEMAV_CVC_COMPLEX_TYPE_3_2_1: Element 'collection', attribute 'name': The attribute 'name' is not allowed.]
```

Let me know if this issue should be posted somewhere else.

Thanks!

**Comment by bernt-matthias** [comment]
If I get https://github.com/galaxyproject/tools-iuc/pull/5464#discussion_r1317928279 it's only the xsd that misses the name attribute.

**Comment by bernt-matthias** [comment]
Should be easy to fix.
