### ISSUE TITLE
Very old version of Galaxy is failing to install packages

### ISSUE THREAD

**Issue by atb1r21** [galaxyproject/galaxy#16660]
Hi,

I'm seeing problems trying to install packages on my Galaxy instance. This is a very old version of Galaxy that shouldn't be in production, but out of necessity it is.

The Galaxy version is 16.01

From the web interface I am seeing that Galaxy can no longer install tools, as they get stuck at the cloning stage. Please see the attached image.

I am expecting that the Galaxy interface can install the latest version of tools, as it seems to pick them up from the tool shed but is unable to download and deploy them

If it is possible can I get some assistance regarding fixing this, very ancient instance, so that it works for a few more months until I can upgrade to the latest version?

![image](https://github.com/galaxyproject/galaxy/assets/100304025/82510de0-5623-4bc9-b728-f45ab0fc0969)

**Comment by mvdbeek** [comment]
You're best chance is to manually clone the repository and set up the dependency, but it's very questionably that the tool will even work on an instance that is so old.

**Comment by atb1r21** [comment]
Hi,

Thanks for the advice, is there documentation to do that manually?

Thanks again,
Alister

**Comment by mvdbeek** [comment]
No, it's basically find the tool on the tool shed (e.g. https://toolshed.g2.bx.psu.edu/view/devteam/fastqc/5ec9f6bceaee), find the mercurial link, clone it to a location on the server's disk, then add it to your tool_conf.xml file. 16.01 did not support conda, so I think your best bet is to install fastqc manually somewhere and then make sure the script is available on PATH.
