### ISSUE TITLE
Query tabular showing uncaught exception in exposed API on Galaxy EU

### ISSUE THREAD

**Issue by subinamehta** [galaxyproject/galaxy#16676]
Hello,

We have been having issues with running Query tabular on Galaxy EU. Whenever a word/ letter is typed in SQL query space, the tool shows an API issue. I am attaching two screenshots of the error.
<img width="275" alt="API" src="https://github.com/galaxyproject/tools-iuc/assets/27242621/a6d0032f-62d4-4db3-9ed7-f8c04265ad08">
![Screen Shot 2023-09-11 at 1 05 29 PM](https://github.com/galaxyproject/tools-iuc/assets/27242621/e2bc0cdc-52e0-410b-837b-c7bacdbdd302)

Workflow:https://usegalaxy.eu/u/subina/w/querytabulartest
Input: https://usegalaxy.eu/u/subina/h/copy-of-querytabulartest

The tool itself or within the workflow doesn't work on EU. If you add any SQL query in the SQL query box the tool shows an error. It would be great if someone could resolve this issue as most of the proteomics workflows on the GTN rely heavily on this tool.

Best,
Subina

**Comment by subinamehta** [comment]
How can this be fixed?

**Comment by davelopez** [comment]
We are currently investigating, It is probably something internal, nothing that can be done from the user side AFAIK. No worries, I'll report here our findings.

**Comment by davelopez** [comment]
Thanks Marius, that saved me some more investigation time, I'll install Python 3.11 locally to reproduce it and then try to fix it.

**Comment by mvdbeek** [comment]
https://pypi.org/project/regex/ is an interesting project linked out to from the python re docs, it might be nice to use that so as that we're not hit over the head when upstream re changes that sort of thing.

**Comment by davelopez** [comment]
Alright, I created a quick fix in https://github.com/galaxyproject/tools-iuc/pull/5481 as suggested.

How do we handle the rest of the cases then? 
- [ ] Create a linter
- [ ] Replace `re` with https://pypi.org/project/regex/
- [ ] Add a similar quick fix for all tools using regex in IUC
I think I could give it a try for the linter and the quick fixes, but I'm not so sure about how to start replacing `re` with `regex` :thinking:

**Comment by mvdbeek** [comment]
Ideally we'd do all 3, for the replacement it should be a drop-in replacement:

```diff
diff --git a/lib/galaxy/tools/parameters/validation.py b/lib/galaxy/tools/parameters/validation.py
index 4df3364011..cb5fbd4f53 100644
--- a/lib/galaxy/tools/parameters/validation.py
+++ b/lib/galaxy/tools/parameters/validation.py
@@ -4,7 +4,7 @@ Classes related to parameter validation.
 import abc
 import logging
 import os.path
-import re
+import regex

 from galaxy import (
     model,
@@ -143,7 +143,7 @@ class RegexValidator(Validator):
         if not isinstance(value, list):
             value = [value]
         for val in value:
-            match = re.match(self.expression, val or "")
+            match = regex.match(self.expression, val or "")
             super().validate(match is not None, value_to_show=val)


```
I think we only need to care about the RegexValidator class.

This is untested, but a quick `regex.match('^(?ims)\s*select\s+.*\s+from\s+.*$', 'select id from job where id = 1;')` worked so I assume this should be more or less it (plus adding the dependency)

**Comment by davelopez** [comment]
Cool! Seems easy enough then, do you want to create a PR since you already have it sketched while I try to create the linter? or should I do it?

**Comment by mvdbeek** [comment]
Sure, sounds good!

**Comment by mvdbeek** [comment]
(meaning I'll do the PR ... 😆  )
