### ISSUE TITLE
Documentation on building a job runner - call to parent constructor

### ISSUE THREAD

**Issue by maikenp** [galaxyproject/galaxy#16671]
In the docs we are recommended to do:
```
super(GodockerJobRunner, self).__init__(app, nworkers, **kwargs)
```

But the automatic linting asks you to instead do:

```
super().__init__(app,nworkers,**kwargs)
```

Should the documentation be updated?

**Comment by jdavcs** [comment]
Good catch, thanks! The version in the docs is outdated.
