### ISSUE TITLE
allow deleting things from histories storage view

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16699]
Given the explanation on the page

> you can free up the storage space by selecting them individually in the graph and clicking the Permanently Delete button.

I expected to be able to delete history or at least a dataset, but I did not find how. I found these two places but first just opens list of dataset in a history and the second shows dataset information (where it cannot be deleted afaik)

![Galaxy](https://github.com/galaxyproject/galaxy/assets/1814954/b698eb38-2dbd-4834-9511-8c0872fe26a5)
![Galaxy](https://github.com/galaxyproject/galaxy/assets/1814954/4b824112-2422-403d-8a49-04869737635b)

**Comment by davelopez** [comment]
Are those histories or datasets marked as `Deleted`?
The full help text talks about already deleted datasets and tries to instruct about the fact that deleting is not the same as "permanently" deleted in an attempt to clarify this source of confusion (but It seems I might have created more confusion :sweat_smile:):

> Note: these graphs include **deleted histories**. Remember that, even if you delete histories, they still take up storage space. However, you can free up the storage space by permanently deleting them from the Discarded Items section of the [Storage Manager](https://usegalaxy.eu/storage/management) page or by selecting them individually in the graph and clicking the Permanently Delete button.

**Comment by martenson** [comment]
I think I understand your copy now. So I guess this is a feature request?
