### ISSUE TITLE
Simple workflow inputs show API error when type is deselected.

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#16693]
**Describe the bug**

When the type of a simple (workflow) input is deselected an API error is shown

https://github.com/galaxyproject/galaxy/assets/25689525/c0dc8ba9-af84-4b0b-bf2d-726ecdb934b3

I think the type should not be optional and the user should not be able to unselect it at all, or?

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1.rc1
Commit: 133d9d3d8c4d3238b39cf528e74a80b7749d7eaa

**To Reproduce**

See recording

**Expected behavior**

At least no API error should be raised. Maybe the select should not be optional.

**Screenshots**

**Additional context**

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/16759
