### ISSUE TITLE
UCSC Genome Browser redirects http to https. Use https URLs instead. Change was made for improved user security.

### ISSUE THREAD

**Issue by galt** [galaxyproject/galaxy#16700]
We are now redirecting http URLs to https for genome.ucsc.edu, and genome-euro.ucsc.edu, and genome-asia.edu as well as our other internal servers.  It appears that galaxy does not support redirections. It is however best to just use https urls instead which will be fast and secure and not need to redirect. usegalaxy.org and usegalaxy.eu will need their configurations changed to support hgTables Send to Galaxy checkbox and button functionality, as well as any other cases where Galaxy calls UCSC Genome Browser.

Let us know if you have questions or require further assistance.
Thank you for your kind assistance with this security upgrade at UCSC.

https://help.galaxyproject.org/t/from-peaks-to-genes-error-with-ucsc-main/10790/4

**Comment by mvdbeek** [comment]
Thanks @galt, could you then please update your form ?

This is the source from https://genome.ucsc.edu/cgi-bin/hgTables

<img width="1290" alt="Screenshot 2023-09-15 at 10 07 30" src="https://github.com/galaxyproject/galaxy/assets/6804901/dadcaa94-fe28-4c1b-810e-20b9bd246d6c">

**Comment by galt** [comment]
Thank you for pointing this out, it should be an easy fix for us.

**Comment by galt** [comment]
We are temporarily rolling back our redirect to https for 2 weeks until our next release v454.

We have fixed this URL in hgTables, thanks so much for pointing it out.
It worked in our Galaxy testing.

FYI we tried 307 redirect but it did not help with Galaxy.

Do you have any other spots that Galaxy source code that will need to be modifie to support https URLs to the ucsc genome browser?

Your kind assistance is much appreciated!
Galt

**Comment by jennaj** [comment]
Hi @galt 

What is the day/time of your release? You can let us know later here if not sure yet, even the day of. I'd like to run a very quick sanity check test across the different live production systems just to catch any problems that pop out early. I know this is a bit tricky to fully test before plus that is just how I roll :) Thanks!

> Do you have any other spots that Galaxy source code that will need to be modifie to support https URLs to the ucsc genome browser?

I don't know but maybe others do?

* I just tested the original problem (getting data from the UCSC TB into Galaxy) and that worked. So thanks for that part!
* I also tested pushing data to the UCSC Browser itself for display and that worked fine too, but wasn't an original problem as far as I know.

**Comment by galt** [comment]
So, to give QA more time to test the change, we are pushing its release back to v455 which should be on our production servers in 5 weeks.
