### ISSUE TITLE
Multi-history view does not copy collection contents properly

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#16716]
**Describe the bug**
Collection contents are not copied.

**Galaxy Version and/or server at which you observed the bug**
23.1

**To Reproduce**
Create a dataset collection using the list builder.
Copy it to a new history, notice that the contents haven't been copied.
Delete the source history.
Your data is gone.

**Comment by mvdbeek** [comment]
This is probably the cause of https://github.com/galaxyproject/galaxy/issues/16619.

**Comment by wm75** [comment]
Makes sense. I almost never use multi-history drag and drop, but always go via "Copy datasets" so I failed to reproduce #16619.

**Comment by wm75** [comment]
or would this affect all kinds of copies of a collection?

**Comment by mvdbeek** [comment]
No, we used to pass `copy_elements=true` wherever this was needed. It's a bit safer to do this the other way round though, disable the copy if not necessary (e.g. when building a collection and hiding the source)
