### ISSUE TITLE
UCSC Genome Browser hgTables sendToGalaxy does not work for hyperlinks output type.

### ISSUE THREAD

**Issue by galt** [galaxyproject/galaxy#16715]
This may have been broken for a long time,
but there is code in the kent repo for this output type.

Jen mentioned that maybe Galaxy cannot accept raw html or xml output for security reasons.
On the other hand, perhaps it is intended to process the output somehow.

A co-worker was wondering what use the hyperlinks would be to Galaxy.

I can write some code that disables the hyperlink output when a user chooses it and sendToGalaxy,
so that they would get an error message and nothing would be sent to Galaxy.

Unfortunately I do not have much in the way of documentation or expectations
for the interaction with Galaxy.

Are there any clues in the Galaxy source code here for what was intended to happen?
Shall we try to fix it?

Here is an example of the output when NOT selecting send to Galaxy:

```
<html><body>
<!--StartFragment-->

 
--
  | ENST00000380794.5 at chr2:25160853-25168690 ENST00000395826.7 at chr2:25160860-25168580 ENST00000405623.5 at chr2:25160915-25168903 ENST00000264708.7 at chr2:25160985-25168571 ENST00000449220.1 at chr2:25161146-25168571

<!--EndFragment-->
</body>
</html>[ENST00000380794.5 at chr2:25160853-25168690](https://hgwdev.gi.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chr2:25160853-25168690)
[ENST00000395826.7 at chr2:25160860-25168580](https://hgwdev.gi.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chr2:25160860-25168580)
[ENST00000405623.5 at chr2:25160915-25168903](https://hgwdev.gi.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chr2:25160915-25168903)
[ENST00000264708.7 at chr2:25160985-25168571](https://hgwdev.gi.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chr2:25160985-25168571)
[ENST00000449220.1 at chr2:25161146-25168571](https://hgwdev.gi.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chr2:25161146-25168571)

```

**Comment by mvdbeek** [comment]
> I can write some code that disables the hyperlink output when a user chooses it and sendToGalaxy,

that'd be great! Galaxy is most useful when you can apply downstream analysis or visualizations to incoming data, so while we could disable the sanitizer I think we'd need a good usecase to do that and think through all the corner cases. As you said, I don't know what users would do with these links that would make them want these in Galaxy.

**Comment by maximilianh** [comment]
Galt, I think this can be closed. There is no use case for sending URLs to Galaxy. It's a data analysis website.

**Comment by galt** [comment]
For hgTables, I have disabled the hyperlinks output, and replaced it with a warning that explains to users they need to choose some other output type.  The change should appear in v455 in about 5 weeks.
