### ISSUE TITLE
Display issue : Missing entries in new history 

### ISSUE THREAD

**Issue by BioinformaticsPlatformWIV-ISP** [galaxyproject/galaxy#16723]
**Describe the bug**
Some entries are missing in the new history.  Especially the oldest ones, at the bottom of the history , when scrolling down can disappear, or more precisely won't be displayed at all. This look like a re-scaling bug,  possibly a CSS issue.

Conditions to observe the bug: the history must be big enough to take several screens (from our experience > 60 entries), the zoom and/or screen resolution is important, it doesn't occur in all browser window sizes. Playing with the browser zoom can sometimes help to reproduce the bug. The bug occurs in both Chrome and Firefox and  both Windows and Ubuntu.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version:  22.05
Commit:  591eff44867f3b4154808418652ad9adfab74e1e

**To Reproduce**
1. Go to home page, then hover the history 
3. Scroll down to the bottom of it
5. Alternatively, if the display is fine, you can change the zoom size of your browser (Ctrl+ or Ctrl-), then scroll again to try to make it happen. Worse case scenario, don't scroll at all, just zoom out until you see the bottom of the history missing.

**Expected behavior**
Having the full history displayed  independently of the screen size or zoom used.  

**Screenshots**

Normal behavior : 

![galaxy_history normal display](https://github.com/galaxyproject/galaxy/assets/18479046/022c8bf4-f25c-457f-af71-fe34ec0987fc)

The bug with scrolling at a constant zoom size :

![galaxy_history_bug](https://github.com/galaxyproject/galaxy/assets/18479046/60ec8d8d-dd8e-49b1-a3b7-4bc733c382d5)

The bug triggered by zooming out :

![galaxy_history_zoom_out](https://github.com/galaxyproject/galaxy/assets/18479046/f8ea5dee-02c1-4a08-9648-6f252829ea73)

**Comment by dannon** [comment]
xref https://github.com/galaxyproject/galaxy/issues/14767, let's track this there.  Thank you!
