### ISSUE TITLE
Job resource parameters selector broken on usegalaxu.eu (unknown causes)

### ISSUE THREAD

**Issue by domgz** [galaxyproject/galaxy#16727]
**Describe the bug**
The job resource parameters selector broke on [usegalaxy.eu](https://usegalaxy.eu). For the tool [keras_train_and_eval](https://usegalaxy.eu/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fkeras_train_and_eval%2Fkeras_train_and_eval%2F1.0.10.0&version=latest), the option "Use GPU resources" shows up, but no drop-down menu is available and no items can be selected.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1rc1
Commit: [248078bacc45776a7cca26183b663208a7eadb82](https://github.com/usegalaxy-eu/galaxy/commit/248078bacc45776a7cca26183b663208a7eadb82) (from the [usegalaxy-eu/galaxy](https://github.com/usegalaxy-eu/galaxy) fork)

**To Reproduce**
1. Visit the [keras_train_and_eval tool page](https://usegalaxy.eu/?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fbgruening%2Fkeras_train_and_eval%2Fkeras_train_and_eval%2F1.0.10.0&version=latest).
2. Select "Specify job resource parameters" under "Job Resource Parameters".
3. The parameter "Use GPU resources" shows up.
4. The message "No options available." is shown under the parameter's label.

**Expected behavior**
Two options (_"No (default)"_, _"Yes"_) [should be available](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/8d3532faae4719733d626b89e441acccb63acedd/files/galaxy/config/job_resource_params_conf.xml#L4-L5) in the drop-down menu. In fact, this was working a few days/weeks ago.

**Screenshots**
![image](https://github.com/galaxyproject/galaxy/assets/43052541/c22c7a49-561f-44d0-8e4e-48f318607a33)

**Additional context**
After debugging this issue, the options are available in the XML nodes tagged with "param" [here](https://github.com/usegalaxy-eu/galaxy/blob/248078bacc45776a7cca26183b663208a7eadb82/lib/galaxy/util/__init__.py#L982). They are then [returned](https://github.com/usegalaxy-eu/galaxy/blob/248078bacc45776a7cca26183b663208a7eadb82/lib/galaxy/util/__init__.py#L984) and later [retrieved](https://github.com/usegalaxy-eu/galaxy/blob/248078bacc45776a7cca26183b663208a7eadb82/lib/galaxy/jobs/__init__.py#L644), but by then, the children of the XML node (the options) are gone.

I do not think this is a Galaxy bug but rather something related either to lxml or whatever is doing the garbage collection. On a local Galaxy instance I have in a VM this is not happening.

I have proposed a workaround in #16728.

**Comment by kysrpex** [comment]
@anuprulez This is the problem you mentioned yesterday, and as you see I have also proposed a solution. I think it makes sense to mention you here so that you get notified when the issue gets closed.
