### ISSUE TITLE
Visual hierarchy could improve published workflow display page 

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#16722]
In addition to the workflow preview I've heard is coming from @ElectronicBlueberry (which I am *very* excited about)
I found the lack of visual hierarchy on this page makes it a bit hard to scan:

Everything has the same:

- font size
- weight
- indentation
- semantic hierarchy

![A list of steps, all left aligned, with all the same font size/weight](https://github.com/galaxyproject/galaxy/assets/458683/5511db2f-4896-47e9-8962-dd3b916b1f2d)

And adjust any of these would help make this list easier to scan.

(separately there don't seem to be many headings used on the page, e.g. workflow: name is just regular text, it's actually read *after* the import/download buttons which is sub-optimal but anyway that's separate)

**Comment by mvdbeek** [comment]
Sorry, which page is this and does it still exist after https://github.com/galaxyproject/galaxy/pull/16510 ?

**Comment by hexylena** [comment]
No, this is fixed in the next release by #16510, thank you.
