### ISSUE TITLE
Purging users does not work as expected, prevents reusing email address

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#16767]
**Describe the bug**
Several related issues
1. A user's email address is not reusable after a user is purged.
2. ...which is a consequence of the user's email address not removed from the `role` table. Furthermore, the purged user's email address being present in 2 columns (name and description) is also a data privacy issue.
3. Attempting to create a user with a deleted user's email address will result in an API error, but **also** will create a new user record *without* creating a role for that user. 
4. Furthermore, purging the newly added user that has no associated role will **not** replace the user's username and email address in the database with a hash.

This certainly related to this error we occaionally see on sentry:
```
IntegrityError
(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "ix_role_name"
DETAIL:  Key (name)=(foo) already exists.

[SQL: INSERT INTO role (create_time, update_time, name, description, type, deleted) VALUES (%(create_time)s, %(update_time)s, %(name)s, %(description)s, %(type)s, %(deleted)s) RETURNING role.id]
[parameters: {'create_time': datetime.datetime(2023, 9, 27, 11, 44, 20, 150298), 'update_time': datetime.datetime(2023, 9, 27, 11, 44, 20, 150305), 'name': 'foo', 'description': 'Private Role for foo', 'type': <types.PRIVATE: 'private'>, 'deleted': False}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1 / rc1
Commit: b58f5824abced2e090238000367e1ae1b5ef02df

**To Reproduce**
Create user, delete, then purge. Try to create again. Observe error, new user in list of users. Delete, purge. Check database (user, role tables).

**Expected behavior**
1. Purging a user should remove their email from both the user table and the role table.
2. It should be possible to create a new user with the same email address.

**Comment by mvdbeek** [comment]
See also https://github.com/galaxyproject/galaxy/pull/16349#issuecomment-1614507154 for why we still have these in sentry

**Comment by jdavcs** [comment]
I remember that fix. Apparently the problem is back. I'm on dev. I'll test previous releases.

**Comment by mvdbeek** [comment]
It works correctly for me, both purging from the admin panel or user self-deletion ... just make sure to regularly purge your users. The commit you listed is very old.

**Comment by jdavcs** [comment]
Yep... That's what happens when you have multiple galaxy instances... Thanks! Sorry for the noise :laughing:
