### ISSUE TITLE
Possibility to remove a galaxy user

### ISSUE THREAD

**Issue by vazovn** [galaxyproject/galaxy#16786]
When configuring Galaxy with external authentication we usually need to re-run the procedure of inserting the user into the galaxy user database. However, authenticating methods like LDAP or auth2 always return the same email for the user. This makes it very difficult to repeat the procedure as the user is already in the database. It would be very convenient to allow for user _proper_ deletion in cases where the the user does not have any associations in the database. This will save the future admins the effort of running manual sql requests against the database to delete the user.

**Comment by mvdbeek** [comment]
Are you reporting a bug with user deletion ? If you're on a recent commit you can purge users and their email addresses get obfuscated, so those users can register again.

**Comment by vazovn** [comment]
We just had a BoF yesterday and this issue popped up. I was not aware of this "obfuscating" feature. Thank you.
