### ISSUE TITLE
[Feature request] Cancelling a workflow post invocation

### ISSUE THREAD

**Issue by microfuge** [galaxyproject/galaxy#16781]
Hi,

Follows from https://help.galaxyproject.org/t/cancelling-a-workflow-post-invocation/10888 

Ability for users to cancel a workflow post invocation would be great. Especially when the user realizes that there is a mistake in input/settings. 
The current ways of deleting datasets and purging histories work but are cumbersome and not straightforward. 

We have workflows that spawn thousands of jobs each and many datasets are in collections and/or are hidden. Users find it difficult to delete datasets just to stop jobs. 

Ability to cleanly delete/stop all jobs pertaining to a particular workflow invocation would be great. This even can be extended to deleting generated datasets when a workflow run completes or fails partially. 
Thanks!

**Comment by mvdbeek** [comment]
That's https://github.com/galaxyproject/galaxy/pull/16252, it's a tricky undertaking with the current architecture.
