### ISSUE TITLE
Clientside Routing

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#1678]
Currently there's not a good way to directly navigate to, bookmark, share, etc., many views the client presents.  Implementing more comprehensive clientside routing can fix this.

Right now there's a base application router in apps/analysis.js.  I've implemented a tour route that proved useful in #1671.

The router is also used for workflows and tools, though through the 'home' route (backwards compatibility perhaps?), and those are specified as arguments which do _not_ get pushed back up to the location bar and exposed to the user in a bookmarkable way.  Specific tools kind-of are, though the user has to click through (on the tool form) Options -> Share and then copy out of a popup modal.

Basically, to the degree possible, the current view (and maybe some relevant state info) of the application should be pushed back up into the address bar. 

A walkthrough using the concrete example of the tours index page, which has no web controller endpoint (the view is clientside, backed by the API) -- the URL looks something like `http://usegalaxy.org/#/tours/`.  When that address is navigated to, the server responds from the home endpoint presending the basic application framework.  Then the router picks up the `#/tours` part and executes the relevant method in javascript, `Galaxy.app.display(new ToursView())`, to display it in the center panel.  Given the current router pushState settings, it pushes the browser location to `http://usegalaxy.org/tours`.  Now we have a URL in the address bar that doesn't actually work, however, and this is the main thing I'd like to sort out our implementation for.

Options:
- We could just use these '#' urls and stop cutting them out
  (pros, cons here?)
- The framework can catch 404's and reply with a redirect with the state pushed into a hash that the clientside route will handle.  That is, a request to `usegalaxy.org/tours` redirects to `usegalaxy.org/#/tours`, which is then consumed by the clientside router appropriately (and then pushState makes the URL pretty again)

**Comment by dannon** [comment]
ping @martenson @guerler @carlfeberhard

**Comment by dannon** [comment]
This is a very sketchy planning card and what I'd like to do at this point is try the latter method just to see how it'll work and feel, using the tour, workflow, and tool routes.

**Comment by carlfeberhard** [comment]
@dannon Thanks very much for writing this up

**Comment by guerler** [comment]
:+1: We definitely need consistent routing and using a generic forwarding like you describe it sounds good to me.

**Comment by guerler** [comment]
It will also help us to move forward with the stalled mako to js transformation.

**Comment by dannon** [comment]
@guerler Yep.  Since we haven't had any other feedback, I'm going to go ahead and implement what I mentioned above.

**Comment by martenson** [comment]
few points against #s:
- if we switch to # URLs only we either break our existing URLs or add a lot of complexity if we support both
- things after # in url are usually ignored by crawlers
- if we rely on consuming # on the client side it is difficult to abandon it in the future

pushstate, replacestate and popstate are now widely supported:
![screenshot 2016-03-01 11 03 20](https://cloud.githubusercontent.com/assets/1814954/13432848/4bf97c70-df9d-11e5-846c-8ff218b18b90.png)
http://caniuse.com/#feat=history

**Based on points above I would advocate going all in without the #s.**

I did not find a Backbone router in https://github.com/galaxyproject/galaxy/pull/1671 - @dannon do you perhaps  mean this one? https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/apps/analysis.js#L103

**Comment by dannon** [comment]
@martenson Thanks for chiming in. Yeah, that's exactly the new route I meant, and it it was added in #1671.

I'm definitely leaning away from the non-pushed # urls as well.  Good to have another vote that way!

**Comment by martenson** [comment]
@dannon I am not sure we are on the same page. The proposition in the first post seems like a '# consumer' implementation - I think we should not operate with #s in any way (other than the page anchors). 

It should be possible to always return 'the app' on any URL that is part of the one-page-app and let it load the url-specific functionality on demand (through JS). It is slower (twitter abandoned similar architecture in 2012 - http://engineering.twitter.com/2012/05/improving-performance-on-twittercom.html) but I thought this is our target.

@carlfeberhard do you see this in line with the webpack architecture?

**Comment by dannon** [comment]
@martenson Sorry, wasn't clear.  I agree to killing the #'s completely, there isn't a need for them.

I'm currently trying to figure out the best way to keep a shared 'list of routes which the client is capable of handling', without having to mirror it in lib/galaxy and client.  This is necessary to be able to tell Galaxy when to 404 instead of shipping back a basic analysis page which then routes itself.

**Comment by dannon** [comment]
For more context:   https://github.com/dannon/galaxy/commit/9daf348770bc5ff7576db297bd3f959b8a35d006

The bit I'm working on is the shared map between client and framework, so we don't have to maintain a 'dumb' mirrored list there.

**Comment by martenson** [comment]
Some interesting point here: https://artsy.github.io/blog/2012/06/25/replacing-hashbang-routes-with-pushstate/

**Comment by dannon** [comment]
@martenson Yeah, I did a big survey as well and I think it's generally agreed upon at this point that hashbang isn't awesome.  In that article, the "An added bonus here is a near one to one mapping with the Rails and client routes." bit is what I'm trying to figure out the best way to handle.  I'm not really satisfied with two separate locations for updating URLs which are 'almost' the same, (currently it'd be analysis.js and controllers/root.py in my minimal example above), but we can definitely just start there if we want.

**Comment by martenson** [comment]
I am not sure if you can get away with one location of mappings as the backend has to be independent with regards to client and also cannot assume much about the client architecture.

**Comment by dannon** [comment]
@martenson So you think it'd be problematic to have a single .json file defining routes that is used by both client/server?  That's what I was testing.

**Comment by martenson** [comment]
@dannon I am afraid you would end up needing pretty complex algorithm to parse that json (compare the links below). 
https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/galaxy.library.js#L48
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/buildapp.py#L445

I also do not think that API and client match 1:1 (not in endpoints and not in endpoint signatures either) so you would need to exclude and pick and adapt.

**Comment by martenson** [comment]
Also many endpoints are not defined in the Router but rather in the Model:
https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/library/library-model.js

**Comment by dannon** [comment]
@martenson It wouldn't be a match between those two links, though, right?  It's a mapping of the first link you posted to a simple list that the server can say "Hey, no method serverside?  Ok, I will trust the client to handle this and won't 404".

**Comment by dannon** [comment]
@martenson Yeah, so with the endpoints being defined all over, that's another thing we need to talk about.  Do we _want_ it to be that way, with multiple routes and routers defined per component?  I was actually hoping we could migrate towards a single 'routes.js' which gets used by analysis.js which included everything.  Otherwise it's a real mess.

**Comment by martenson** [comment]
@dannon we could do a single Router for all single-app reachable URLs I think. Alternatively we could have a BaseRouter that would load routes based on what components are available (loaded).
I am aware of three Routers on Galaxy side: Analysis, Libraries and Trackster (not completely sure about that one). Are there more?

Models tend to have their own resource locations that Backbone maps itself against (and we use it that way pretty consistently amongst the JS client). I think this is how it was designed to be used - Model should know where to fetch items without having anything to do with the Router.

**Comment by dannon** [comment]
@martenson Yeah, what I had talked to @guerler (feel free to chime in!) about and what we were leaning towards was a single router, defined in a single file (routes.js or something obvious) for all single-page-app (which is eventually pretty much everything, right?) routes, before we start it sprawling any more than it has to.  On the galaxy side, you're right, it's only those 3 routers right now (analysis, libraries, and trackster).

Models having their own mappings to API-backed resource locations is _totally_ fine and I agree, that's working exactly like it should in most places -- you're right that this is a totally different issue than the URLs we're talking about routing here.

**Comment by martenson** [comment]
One Router could be a good place to start. I would imagine pushing the state of the tool that is opened to the URL would be a nice example of shareable and useful URL.

It could become complicated to make it human-readable though. Something like https://usegalaxy.org/tool/mts/devteam/bowtie2/0_4 seems a bit awkward but anything less is not unique and will introduce collisions.

At this point I am not sure it is worth the hassle and maybe we should focus on making the router work with URLs 'as is' and introduce human-readable URLs later.

@dannon I did not catch a debate with @guerler - I thought that is what this issue is for.

**Comment by dannon** [comment]
@martenson I'm pretty sure your understanding of what the issue is for is ok.  I happened to talk to @guerler in meatspace, which is why I was relaying that here.

**Comment by guerler** [comment]
Yeah I am in favor of one routing location unless there are obvious problems with it. I think it would be much easier to find, add and modify routes.

**Comment by martenson** [comment]
@guerler you mean one routing location on client, right?

**Comment by guerler** [comment]
Yeah.

**Comment by dannon** [comment]
Closing this as the 'tours' work is a complete, concrete example of how new clientside routes should be added in the future.

Relevant references in the code here:
https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/apps/analysis.js#L103
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/buildapp.py#L80
