### ISSUE TITLE
Finalise single cell galaxy subdomain

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/galaxy#16806]
Outstanding CoFest work last week!
Last remaining things:

- [ ] There was the minor issue of the 'Single cell tools' label not working (1 line missing somewhere)
- [ ] Change the colour - purple
- [ ] Redirect link from HCA instance (https://humancellatlas.usegalaxy.eu)
- [ ] Review/merge this: https://github.com/usegalaxy-eu/website/pull/1153
- [ ] Hide/delete HCA instance
- [ ] Instructions for us on how to proceed in future as new tools are made, how do we get them to the appropriate section and/or create new ones? Do we raise an issue each time, for example?

@kysrpex

**Comment by nsoranzo** [comment]
I guess this belongs to a UseGalaxy.eu GitHub repo.

**Comment by nomadscientist** [comment]
<img width="477" alt="Screenshot 2023-10-07 at 11 15 07" src="https://github.com/galaxyproject/galaxy/assets/44605769/f1ef4f65-9de9-4a7a-9f58-1a7301a2a328">
seems reasonable - exactly which repo?

**Comment by bgruening** [comment]
Please put it on website.

**Comment by nomadscientist** [comment]
Done! https://github.com/usegalaxy-eu/website/issues/1154
