### ISSUE TITLE
the infinite scroll within category on TS2.0 does not work

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16813]
Try scrolling https://testtoolshed.g2.bx.psu.edu/repositories_by_category/3c4a991608b4c8dd It has 197 repos but you will only see the first 20 or so.

**Comment by jmchilton** [comment]
Gahhhhh.... I've worked on this for hours this morning. Not a ton of progress.

The behavior seems to mimic the problem outlined here - https://github.com/apollographql/apollo-client/pull/9504. We're fetching the second page of results properly and I think I can even see the GUI extending the initial list... but then the Apollo inner workings are reseting the query and reissuing the request for the first group of results and resetting the table.
