### ISSUE TITLE
tweak vue-multiselect ux

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16823]
| vue-multiselect |
| --- |
| - for a `nullable` selection vue-multiselect offers red highligt of the selected item as an indication together with "press enter to remove" message, see screenshot: |
| <img width="400" alt="Vue-Multiselect___Vue_Select_Library" src="https://github.com/galaxyproject/galaxy/assets/1814954/65ac6c96-6193-4ef3-9e3b-ad44d14dc9b6"> |
| - our implementation (n this case for data input) has that highlight without the message, which I think would be helpful to include |
| <img width="800" alt="Galaxy___Test" src="https://github.com/galaxyproject/galaxy/assets/1814954/8fc67d53-d5f4-4904-bbf4-b11b1c8483fa"> |
| - and it also provides the red highlight on `non-nullable` selections, so it looks the same as above, but works differently |
| <img width="800" alt="Galaxy___Test" src="https://github.com/galaxyproject/galaxy/assets/1814954/548634c3-996f-4993-99a5-d644f7b1ce04"> |

default examples: https://vue-multiselect.js.org/#sub-select-with-search

**Comment by assuntad23** [comment]
We also have vue-multiselect (but with multiple set to false) in the Edit Collection Attributes view. Whatever style changes we make should be applied there as well, if applicable.

**Comment by guerler** [comment]
Closed with #17015.
