### ISSUE TITLE
Toolbox does not respect ordering in tool_conf.xml

### ISSUE THREAD

**Issue by domgz** [galaxyproject/galaxy#16832]
**Describe the bug**

@nomadscientist would like to have the tool sections for the [Single Cell subdomain at usegalaxy.eu](https://singlecell.usegalaxy.eu) in a [specific order](#ordering).

Such ordering has been configured in [tool_conf.xml](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/0b57e355f981dede7631c0b18084a206cb38d801/templates/galaxy/config/tool_conf.xml.j2#L381-L398), yet Galaxy [does not respect it](#screenshot).

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1 (minor 1.dev0)
Commit: [82d96357ca954814a7d6f633ab00e524360f1a12](https://github.com/usegalaxy-eu/galaxy/commit/82d96357ca954814a7d6f633ab00e524360f1a12) (from the [usegalaxy-eu/galaxy](https://github.com/usegalaxy-eu/galaxy) fork)

**To Reproduce**
1. Visit the [Single Cell subdomain](https://singlecell.usegalaxy.eu)

**Expected behavior**
Sections are displayed in the [desired order](#ordering) in the toolbox.

**Screenshots**

<figure style="display: table; text-align:center; margin-left: auto; margin-right:auto">

<span id="screenshot">

![Screenshot](https://github.com/galaxyproject/galaxy/assets/43052541/8caf62dc-cb56-4fa1-b241-85a773a3f190)

</span>

<figcaption style="display: table-caption; caption-side: bottom; text-align:center">

_Wrong toolbox ordering_

</figcaption>

</figure>

<br><br><br><br>

<figure style="display: table; text-align:center; margin-left: auto; margin-right:auto">

<span id="ordering">

![Desired ordering](https://github.com/galaxyproject/galaxy/assets/43052541/9f62cb82-214c-4561-96dc-9b820a05e990)

</span>

<figcaption style="display: table-caption; caption-side: bottom; text-align:center">

_Desired toolbox ordering_

</figcaption>

</figure>

**Additional context**

Relevant locations in usegalaxy-eu's infrastructure playbook to understand the issue.

- [group_vars/gxconfig.yml#L165](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/0b57e355f981dede7631c0b18084a206cb38d801/group_vars/gxconfig.yml#L165) (relevant entry in the Galaxy config file)
- [templates/galaxy/config/tool_conf.xml.j2#L381-L398](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/0b57e355f981dede7631c0b18084a206cb38d801/templates/galaxy/config/tool_conf.xml.j2#L381-L398) (galaxy_config_templates) (tool_conf.xml, there you can see the label "Automated cell annotation" is after the section with id `single-cell-section-interactivetools`, yet it is displayed before).
- [templates/galaxy/config/nagios_tool_conf.xml](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/0b57e355f981dede7631c0b18084a206cb38d801/templates/galaxy/config/nagios_tool_conf.xml) (the other tool_conf file)
- [group_vars/sn06.yml#L438-L439](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/0b57e355f981dede7631c0b18084a206cb38d801/group_vars/sn06.yml#L438-L439) (galaxy_config_templates)

**Comment by nomadscientist** [comment]
Yes!
This seems quite important for subdomains!!!

**Comment by mvdbeek** [comment]
I'm sorry but I can't make sense out of this ansible stuff. Can you please provide the relevant part of the tool_conf.xml file for the single cell instance ? I would also say that we're moving to tool panel sections like you can see in https://github.com/galaxyproject/gx-tool-db-panel-sync/blob/main/singlecell.yml ... that seems like the right level at which to reorder sections. Have you tried this yet ?

**Comment by kysrpex** [comment]
> would also say that we're moving to tool panel sections like you can see in https://github.com/galaxyproject/gx-tool-db-panel-sync/blob/main/singlecell.yml ... that seems like the right level at which to reorder sections. Have you tried this yet ?

Is there documentation for this somewhere?

**Comment by dannon** [comment]
How is the integrated_tool_panel handled in this setup?  That's the final arbiter of this stuff, right?

**Comment by kysrpex** [comment]
> > would also say that we're moving to tool panel sections like you can see in https://github.com/galaxyproject/gx-tool-db-panel-sync/blob/main/singlecell.yml ... that seems like the right level at which to reorder sections. Have you tried this yet ?
> 
> Is there documentation for this somewhere?

Found it [here](https://github.com/galaxyproject/gx-tool-db).

**Comment by kysrpex** [comment]
> How is the integrated_tool_panel handled in this setup? That's the final arbiter of this stuff, right?

Galaxy generates it. I just removed the file and let Galaxy re-create it, that solved the issue.

Thanks @bgruening for the suggestion.
