### ISSUE TITLE
Deleting a collection doesn't delete the elements

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#16866]
Deleting a collection (either via the dropdown in the screenshot below, or just pressing the trash icon) only deletes the collection, not the elements themselves.

![image](https://github.com/galaxyproject/galaxy/assets/32272674/69186aee-2986-45c9-acda-6bc0d282b963)

with this result for the search query `deleted:false visible:any`

![image](https://github.com/galaxyproject/galaxy/assets/32272674/35f07f98-8a90-4265-816b-9afe4feefe1b)

However, choosing the `Delete (permanently)` option does delete the elements:

![image](https://github.com/galaxyproject/galaxy/assets/32272674/610d9511-cb2d-451d-83bf-7551a70e7098)

**Comment by davelopez** [comment]
Thanks for the issue @simonbray!

How do we want to handle this?

There are currently 2 ways of deleting a collection from the history panel (that I can remember):
1. By clicking the "Trash" icon in the collection item. In the UI/UX meeting, we discussed that the previous behavior was showing a menu with 2 options (delete only the collection or collection + elements). Should we bring this menu back or default to delete the elements always?
2. By using the bulk operation menu in your first screenshot. This one is a bit trickier, if you select just collections in the bulk selector we may be able to display these 2 options (delete collection only or collection + elements), but if there are other datasets in the selection or you click the "select all" and the collections are not yet loaded in the history i.e. they are at the very bottom of a long history, then this options will not be available. In this case, we probably want to choose a default behavior for deleting collections in bulk.

And the final open question is, `Do we want to mark all dataset elements as deleted by default when we delete a collection?`, in that case, what would happen to other collections that may be using the same source elements?

**Comment by simonbray** [comment]
The menu seems good to me (maybe just because I'm used to it though?) because it means the user always chooses explicitly what they want to happen.

> a default behavior for deleting collections in bulk

Marius' suggestion seems good, delete only HDAs which are hidden and only have one DCE.

> what would happen to other collections that might be using the same source elements?

Please never delete HDAs if they are being used elsewhere :)

**Comment by davelopez** [comment]
Great thanks!

So then:
- Bring back the menu when deleting from the "Trash" icon.
- On bulk deleting, try to delete the HDA when there is only one DCE associated with it.

**Comment by mvdbeek** [comment]
> * On bulk deleting, try to delete the HDA when there is only one DCE associated with it.

we need to verify that logic is correct ... we may have also not copied the elements, in which case this strategy doesn't work

**Comment by davelopez** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/16879
