### ISSUE TITLE
Invocation Export seems to be hung up

### ISSUE THREAD

**Issue by HadleyKing** [galaxyproject/galaxy#16871]
**Describe the bug**
On Galaxy Main (usegalaxy.org) when trying to export an invocation it appears as if the process is stuck. 

**Galaxy Version and/or server at which you observed the bug**
// 20231017140605
// https://usegalaxy.org/api/version

{
  "version_major": "23.1",
  "version_minor": "1.dev0"
}

**To Reproduce**
1. Go to 'invocations'
2. Click on 'any export method': RO crate, BCO, or File

Using the inspect feature in Chrome the browser submitted over 1,200 requests in about 5 min. Was able to replicate using Safari as well. 

Workflow download worked fine.

**Comment by mvdbeek** [comment]
@natefoo we'll need a celery backend

**Comment by mvdbeek** [comment]
It does actually work fine for me. Can you provide some additional details on how you're exporting the invocations, and maybe an invocation id ?

**Comment by HadleyKing** [comment]
@mvdbeek 
After retrying it it seems to be working now. It just takes a few minutes. 
It was however not completing on Tuesday when I was trying this for a lecture I was giving.
