### ISSUE TITLE
WF Change datatype post-job action not working for collections with discovered elements

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#16876]
**Describe the bug**
The Change datatype post-job action for workflow steps does not seem to work when the step output in question is a collection with its elements discovered dynamically via `discover_datasets`.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1.1 (checked on .eu and .org)

**To Reproduce**
1. Build a simple workflow with one input and one tool that dynamically generates a collection from that input
    I've tried with `toolshed.g2.bx.psu.edu/repos/bgruening/split_file_on_column/tp_split_on_column/0.4`, `toolshed.g2.bx.psu.edu/repos/bgruening/split_file_to_collection/split_file_to_collection/0.5.0`, and `toolshed.g2.bx.psu.edu/repos/iuc/bamtools_split_ref/bamtools_split_ref/2.5.2+galaxy1`
2. Configure a Change datatype post-job action for the output of the tool
3. Run the workflow
4. Inspect the step output
    The format is still the original one produced by the tool.

**Expected behavior**
The format should be changed to the one configured in the post-job action.

**Additional context**
To help with debugging here's a simple workflow using `bamtools_split_ref`: https://usegalaxy.eu/u/wolfgang-maier/w/generated-collection-datatype-change
This one tries to change the datatype of the output to `unsorted.bam`

Originally discovered by @lldelisle in https://github.com/galaxyproject/iwc/pull/227#issuecomment-1756820259.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/17803, thanks for the report @wm75!
