### ISSUE TITLE
Drag and drop upload -- whole overlay vs dropzone; whole overlay works after one display but only drop zone at first (recall discussion)

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#16870]
For clarity, this is referring to the global drag-and-drop seen here:

![image](https://github.com/galaxyproject/galaxy/assets/155398/1ccd277f-a3cc-4c40-b4c0-0d8048b8743f)

**Comment by dannon** [comment]
Make this more obvious that you have to drop right in the middle.

Provide feedback when dropping not in the drop zone?  (toast?  "Upload discarded"?)

Or just drop anywhere?

**Comment by hujambo-dunia** [comment]
![github_16870_AFTER](https://github.com/galaxyproject/galaxy/assets/3672779/77d53cf6-fb13-4551-a857-8a64af0bce3d)

_Above GIF shows the styling of existing/prior version._

**Comment by hujambo-dunia** [comment]
In my opinion, I think the drop-zone would give a better user experience (fewer missed 'drops') if we could extend the height and width of the dashed-line box as some large percentage of the page (~75-90%) of the entire page. So am doing some experimentation to supersede likely module height/width with hard-coded pixel dimensions.

**Comment by hujambo-dunia** [comment]
![github_ 16870_AFTER](https://github.com/galaxyproject/galaxy/assets/3672779/5720b909-fb0a-48d4-9d63-b834bbcda4d0)

**Comment by dannon** [comment]
Done in #16995
