### ISSUE TITLE
Workflow invocation via API breaks w/ tools w/ output dataset collections

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#1687]
The create() method in /lib/galaxy/webapps/galaxy/api/workflows.py initializes outputs for workflow tools with the following call:

```
outputs, invocation = invoke(
            trans=trans,
            workflow=workflow,
            workflow_run_config=run_config,
            populate_state=True,
        )
```

With tools that do not output dataset collections, these outputs are dictionaries.  However, for tools that do output dataset collections, these outputs are "base objects".  Here is an example of these different output types defined in a workflow that contains both tools that produce output dataset collections and those that do not.

```
{1383: 
  {'html_file': <galaxy.model.HistoryDatasetAssociation object at 0x8d12910>, 
   'text_file': <galaxy.model.HistoryDatasetAssociation object at 0x8d12ad0>}, 
 1384: 
{'html_file': <galaxy.model.HistoryDatasetAssociation object at 0xab3ed10>, 
  'text_file': <galaxy.model.HistoryDatasetAssociation object at 0xaec9b10>}, 
1385: 
{'bam_output': <galaxy.model.HistoryDatasetAssociation object at 0x7f7844124250>}, 
1386: 
{'output': <galaxy.model.HistoryDatasetAssociation object at 0x7f78441f5b10>}, 
1387: 
{u'genetrack_output': <galaxy.model.HistoryDatasetCollectionAssociation object at 0xb2aca10>}, 
1388: <object object at 0x4524cf0>, 
1389: <object object at 0x4524cf0>, 
1390: <object object at 0x4524cf0>, 
1391: <object object at 0x4524cf0>, 
1392: <object object at 0x4524cf0>, 
1393: <object object at 0x4524cf0>, 
1394: <object object at 0x4524cf0>, 
1395: <object object at 0x4524cf0>, 
1396: <object object at 0x4524cf0>, 
1397: <object object at 0x4524cf0>, 
1398: {'output': <galaxy.model.HistoryDatasetAssociation object at 0xaece250>}, 
1399: {'output': <galaxy.model.HistoryDatasetAssociation object at 0xaee1090>}, 
1400: {'output': <galaxy.model.HistoryDatasetAssociation object at 0xaec9990>}}
```

Tools that produce outputs that are the base objects in the above list cause problems a bit further downstream in the same method, where code that attempts to iterate over the base object defined by outputs[ step.id ] throws an exception.

```
        # Build legacy output - should probably include more information from
        # outputs.
        rval = {}
        rval['history'] = trans.security.encode_id( history.id )
        rval['outputs'] = []
        for step in workflow.steps:
            if step.type == 'tool' or step.type is None:
                for v in outputs[ step.id ].itervalues():
                    rval[ 'outputs' ].append( trans.security.encode_id( v.id ) )
```

Those outputs that cause these problems are not retained within the rval, so the workflow runs only to the point where the first problematic output occurs.

I've spent some time attempting a fix, but have not been successful.  I'm fairly certain these base objects are related to dataset collections because the workflow stops with the first tool that produces a dataset collection as output.

I've tried various things to get the structure of these objects (e.g., dir(), repr(), etc), and here are the results:

```
dir(step_output): ['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
repr(step_output): <object object at 0x4f08b00>
inspect.getdoc(step_output): The most base type
```

I'm hoping someone can provide a fix for this or some insight into how to go about implementing one.

Thanks very much!

Greg Von Kuster

**Comment by mvdbeek** [comment]
Hi @gregvonkuster,

do you have a simple workflow to reproduce this?
I've been looking into the workflow code during the weekend, perhaps I can spot the problem.
Do I understand correctly that these workflows run fine when called through the UI?

**Comment by gregvonkuster** [comment]
Hi @mvdbeek Thanks for taking a look.  Yes, these workflows run fine when called through the UI.  I'll upload a simple workflow - it'll take a few.  I'll ping you when ready.

**Comment by gregvonkuster** [comment]
@mvdbeek Thanks again for looking into this.

I've attached 4 files below - pease let me know if you do not see them. 

Here are the steps:
1) create a history and get the encoded id for it.
2) upload the 2 attached datasets into the above history and get the encoded ids for them.  When uploading, make sure to set the datatype of the bed file to bed (it will be auto-detected as interval), and the datatype of the scidx file to scidx.  The dbkey for both files is sacCer3.
3) Install these tools into your Galaxy instance:
https://toolshed.g2.bx.psu.edu/view/iuc/genetrack/25cd59a002d9
https://toolshed.g2.bx.psu.edu/view/iuc/bedtools/607c0576c6ab
4) import the attached workflow
5) Place the attached api script (workflow_api_bug.py) into ~/galaxy/scripts/api.
6) Replace the hardcoded values for workflow_id, history_id and the 2 hda_ids to those that you acquire from your own environment in steps 1, 2 and 4 above.
7 Replace the following lines (216, 217) in ~/lib/galaxy/webapps/galaxy/api/workflows.py

```
                for v in outputs[ step.id ].itervalues():
                    rval[ 'outputs' ].append( trans.security.encode_id( v.id ) )
```

with this code:

```
                if isinstance(step_output, dict):
                    for v in step_output.itervalues():
                        rval[ 'outputs' ].append( trans.security.encode_id( v.id ) )
                else:
                    try:
                        rval[ 'outputs' ].append( trans.security.encode_id( step_output.id ) )
                    except AttributeError:
                        log.debug("Object %s does not have an id attribute, so it will be eliminated from legacy output." % str(step_output))
                        pass
```

8) Execute the workflows API script like this:
$python workflow_api_bug.py   

The workflow should start and the selected history will be populated with output dataset up through the genetrack tool's output.  Since genetrack produces a dataset collection on output, the workflow will end at that point, and the following intersect tool will not be included.  Of course, the above code change eliminates the genetrack tool's output from the rval dict.  That is where the problem lies...

[Galaxy-Workflow-WorkflowApiBug.ga.gz](https://github.com/galaxyproject/galaxy/files/121817/Galaxy-Workflow-WorkflowApiBug.ga.gz)
[input_small.scidx.gz](https://github.com/galaxyproject/galaxy/files/121818/input_small.scidx.gz)

[input.bed.gz](https://github.com/galaxyproject/galaxy/files/121820/input.bed.gz)

[workflow_api_bug.py.gz](https://github.com/galaxyproject/galaxy/files/121823/workflow_api_bug.py.gz)

**Comment by jmchilton** [comment]
So this is a deprecated API endpoint and has not been updated to deal with output collections. I'm okay with this and will not update it myself - if you want to open a PR I'll consider it but I think the better thing to do is to target the modern workflow invocation API.

The huge, glaring problem with this older interface to workflows is that it assumes that all workflow outputs are available at the end of scheduling a workflow. Workflows can now have pause steps and dynamic output collections - both which stop evaluation of the workflow until the execution has caught up - and so it is no longer a valid assumption at all the outputs are available. Furthermore, this older endpoint was very inefficient - it may have taken 20 minutes to schedule a moderately large workflow - this causes nginx timeouts, etc....

The new workflow invocation API strategy is to schedule a workflow instead of run it - and get an invocation object back instead of the outputs, the client should then poll on the invocation and jobs and grab the outputs when those are complete.

Might be worth reviewing the calls being tested in the following bioblend PR to understand the new API endpoint:

https://github.com/galaxyproject/bioblend/pull/170/files

**Comment by gregvonkuster** [comment]
@jmchilton I would like to understand how I missed the fact that this was a deprecated workflow endpoint.  Where is information like this being kept?  The API method itself had not information regarding this.  I want to make sure that I'm keeping up to date with new directions for components like this so that I don't make the same mistake of spending time going down the wrong path in the future.  Unfortunately, I also pulled @mvdbeek into this one.

**Comment by mvdbeek** [comment]
> Unfortunately, I also pulled @mvdbeek into this one.

Don't worry about me, we still got #1703 out of it, and the first thing I would have done is to use bioblend to confirm the bug.
Which is probably also the "reference implementation" of how to use the galaxy API.

**Comment by jmchilton** [comment]
@gregvonkuster You know that "deprecated" is a wired word in Galaxy land - things tend to stick around forever - I'll think about how to better handle deprecated API stuff. I guess a warning should appear in the logs when you execute such functionality.

**Comment by gregvonkuster** [comment]
@jmchilton I guess I was out of the "bioblend loop" for new workflow API endpoints.  I understand that "deprecated" code in Galaxy needs to stay around in some cases for backward compatibility.  But in this case, some of the API scripts should have been updated or removed altogether.

For example, this script:
https://github.com/galaxyproject/galaxy/blob/dev/scripts/api/workflow_execute.py
should either be updated to reference the new bioblend approach or be deleted altogether.

In addition, the create() method in this script:
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/workflows.py
should include something like this:

```
@expose_api
def create(self, trans, payload, **kwd):
    """
    POST /api/workflows
    This API endpoint is deprecated, so new implementation should not use it.  The replacement endpoint is located here
```

https://github.com/galaxyproject/bioblend/pull/170/files

```
    Run or create workflows from the api.
    If installed_repository_file or from_history_id is specified a new
    workflow will be created for this user. Otherwise, workflow_id must be
    specified and this API method will cause a workflow to execute.
```

I'm fairly certain there are many additional API scripts that need to include information like this.

I think that in general, new information like this should to be added to the deprecated components at the time the new ones are introduced so that developers coming later can understand what not to use and what to use in its place.

**Comment by gregvonkuster** [comment]
Did bioblend get introduced after release_16.01?  I've been able to get the bioblend api stuff to work on the dev branch, but here's what I get with 16.01:
$ git status

# On branch release_16.01

...
Traceback (most recent call last):
  File "cegr_start_workflows.py", line 3, in <module>
    from bioblend import galaxy
ImportError: No module named bioblend

**Comment by mvdbeek** [comment]
bioblend has been around for some time (> 2 years. i believe) ... it sounds more like a problem with your virtualenv.
There is a difference in the requirements between release (pinned, `bioblend==0.6.1`) and dev (`bioblend`) branch.
In general, `pip install --upgrade bioblend` should give you the latest release, which is backwards-compatible to a large extent.

**Comment by gregvonkuster** [comment]
@mvdbeek Thanks for the info!  I've tried updating as you advised.  Here is the log:
$ pip install --upgrade setuptools
/nfs/brubeck.bx.psu.edu/scratch5/galaxy-pugh/galaxy/.venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/nfs/brubeck.bx.psu.edu/scratch5/galaxy-pugh/galaxy/.venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Collecting setuptools
  Downloading setuptools-20.1-py2.py3-none-any.whl (472kB)
    100% |████████████████████████████████| 475kB 360kB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 19.1.1
    Uninstalling setuptools-19.1.1:
      Successfully uninstalled setuptools-19.1.1
Successfully installed setuptools-20.1
(.venv)[galaxy-pugh@brubeck galaxy]$ pip uninstall distribute
Cannot uninstall requirement distribute, not installed
(.venv)[galaxy-pugh@brubeck galaxy]$ 
(.venv)[galaxy-pugh@brubeck galaxy]$ 
(.venv)[galaxy-pugh@brubeck galaxy]$ 
(.venv)[galaxy-pugh@brubeck galaxy]$ pip install --upgrade bioblend
Collecting bioblend
  Using cached bioblend-0.7.0.tar.gz
Collecting requests>=2.4.3 (from bioblend)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting requests-toolbelt (from bioblend)
  Using cached requests_toolbelt-0.6.0-py2.py3-none-any.whl
Collecting boto>=2.9.7 (from bioblend)
  Using cached boto-2.39.0-py2.py3-none-any.whl
Requirement already up-to-date: pyyaml in ./.venv/lib/python2.7/site-packages (from bioblend)
Collecting six (from bioblend)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: requests, requests-toolbelt, boto, six, bioblend
  Found existing installation: requests 2.8.1
    Uninstalling requests-2.8.1:
      Successfully uninstalled requests-2.8.1
  Found existing installation: requests-toolbelt 0.4.0
    Uninstalling requests-toolbelt-0.4.0:
      Successfully uninstalled requests-toolbelt-0.4.0
  Found existing installation: boto 2.38.0
    Uninstalling boto-2.38.0:
      Successfully uninstalled boto-2.38.0
  Found existing installation: six 1.9.0
    Uninstalling six-1.9.0:
      Successfully uninstalled six-1.9.0
  Found existing installation: bioblend 0.6.1
    Uninstalling bioblend-0.6.1:
      Successfully uninstalled bioblend-0.6.1
  Running setup.py install for bioblend ... done
Successfully installed bioblend-0.7.0 boto-2.39.0 requests-2.9.1 requests-toolbelt-0.6.0 six-1.10.0

However, starting Galaxy reverts bioblend back to an older version:

$ sh run.sh --daemon
Activating virtualenv at .venv
Ignoring indexes: https://pypi.python.org/simple
/nfs/brubeck.bx.psu.edu/scratch5/galaxy-pugh/galaxy/.venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/nfs/brubeck.bx.psu.edu/scratch5/galaxy-pugh/galaxy/.venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: pip==8.0.2+gx2 in ./.venv/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): bx-python==0.7.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.23 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.11 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): SQLAlchemy==1.0.8 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): mercurial==3.4.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): numpy==1.9.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): pycrypto==2.6.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): Paste==2.0.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 16))
Requirement already satisfied (use --upgrade to upgrade): PasteDeploy==1.5.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): docutils==0.12 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 18))
Requirement already satisfied (use --upgrade to upgrade): wchartype==0.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 19))
Requirement already satisfied (use --upgrade to upgrade): repoze.lru==0.6 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): Routes==2.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): WebOb==1.4.1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 22))
Requirement already satisfied (use --upgrade to upgrade): WebHelpers==1.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 23))
Requirement already satisfied (use --upgrade to upgrade): Mako==1.0.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 24))
Requirement already satisfied (use --upgrade to upgrade): pytz==2015.4 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 25))
Requirement already satisfied (use --upgrade to upgrade): Babel==2.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 26))
Requirement already satisfied (use --upgrade to upgrade): Beaker==1.7.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 27))
Requirement already satisfied (use --upgrade to upgrade): Cheetah==2.4.4 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 30))
Requirement already satisfied (use --upgrade to upgrade): Markdown==2.6.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 31))
Collecting bioblend==0.6.1 (from -r requirements.txt (line 34))
/nfs/brubeck.bx.psu.edu/scratch5/galaxy-pugh/galaxy/.venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/nfs/brubeck.bx.psu.edu/scratch5/galaxy-pugh/galaxy/.venv/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://wheels.galaxyproject.org/packages/bioblend-0.6.1-py2-none-any.whl (78kB)
    100% |████████████████████████████████| 81kB 18.5MB/s 
Collecting boto==2.38.0 (from -r requirements.txt (line 35))
  Downloading https://wheels.galaxyproject.org/packages/boto-2.38.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 10.1MB/s 
Collecting requests==2.8.1 (from -r requirements.txt (line 36))
  Downloading https://wheels.galaxyproject.org/packages/requests-2.8.1-py2.py3-none-any.whl (497kB)
    100% |████████████████████████████████| 499kB 14.9MB/s 
Collecting requests-toolbelt==0.4.0 (from -r requirements.txt (line 37))
  Downloading https://wheels.galaxyproject.org/packages/requests_toolbelt-0.4.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): kombu==3.0.30 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 40))
Requirement already satisfied (use --upgrade to upgrade): amqp==1.4.8 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 41))
Requirement already satisfied (use --upgrade to upgrade): anyjson==0.3.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 42))
Requirement already satisfied (use --upgrade to upgrade): sqlalchemy-migrate==0.10.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 45))
Requirement already satisfied (use --upgrade to upgrade): decorator==4.0.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 46))
Requirement already satisfied (use --upgrade to upgrade): Tempita==0.5.3dev in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 47))
Requirement already satisfied (use --upgrade to upgrade): sqlparse==0.1.16 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 48))
Requirement already satisfied (use --upgrade to upgrade): pbr==1.8.0 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 49))
Collecting six==1.9.0 (from -r requirements.txt (line 51))
  Downloading https://wheels.galaxyproject.org/packages/six-1.9.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): Parsley==1.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 52))
Requirement already satisfied (use --upgrade to upgrade): nose==1.3.7 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 53))
Requirement already satisfied (use --upgrade to upgrade): SVGFig==1.1.6 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 54))
Requirement already satisfied (use --upgrade to upgrade): Fabric==1.10.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 57))
Requirement already satisfied (use --upgrade to upgrade): paramiko==1.15.2 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 58))
Requirement already satisfied (use --upgrade to upgrade): ecdsa==0.13 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 59))
Requirement already satisfied (use --upgrade to upgrade): Whoosh==2.4.1+gx1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 66))
Requirement already satisfied (use --upgrade to upgrade): pysam==0.8.4+gx1 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 69))
Installing collected packages: requests, requests-toolbelt, six, boto, bioblend
  Found existing installation: requests 2.9.1
    Uninstalling requests-2.9.1:
      Successfully uninstalled requests-2.9.1
  Found existing installation: requests-toolbelt 0.6.0
    Uninstalling requests-toolbelt-0.6.0:
      Successfully uninstalled requests-toolbelt-0.6.0
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: boto 2.39.0
    Uninstalling boto-2.39.0:
      Successfully uninstalled boto-2.39.0
  Found existing installation: bioblend 0.7.0
    Uninstalling bioblend-0.7.0:
      Successfully uninstalled bioblend-0.7.0
Successfully installed bioblend-0.6.1 boto-2.38.0 requests-2.8.1 requests-toolbelt-0.4.0 six-1.9.0
Requirement already satisfied (use --upgrade to upgrade): psycopg2==2.6.1 in ./.venv/lib/python2.7/site-packages (from -r /dev/stdin (line 1))
Activating virtualenv at .venv
Entering daemon mode

And then I get the same exception when executing a script that uses the bioblend API.

Traceback (most recent call last):
  File "cegr_start_workflows.py", line 3, in <module>
    from bioblend import galaxy
ImportError: No module named bioblend

I assume there must be some configuration issue.  Do you have any ideas?

Thanks a bunch for the help on this!

**Comment by mvdbeek** [comment]
@gregvonkuster it's probably best to use a clean `.venv` for interacting with galaxy, that is different from galaxy's venv.
bioblend doesn't even need to be on the same machine (but it certainly can).
I haven't experimented with bioblend inside galaxy's virtualenv, though I also don't understand why the import is failing.

**Comment by gregvonkuster** [comment]
@mvdbeek So, I got it to work by putting the 2 lines below at the top of my script before the import, but obviously this is a hack.  Im still getting used to Galaxy's fairly recent virtual env, which has changed those things I've been used to doing in the past.  So what I should be doing is setting up a different virtual env outside of Galaxy's to run my scripts that use Galaxy's API.  I'll give that a try.

activate_this = '/nfs/brubeck.bx.psu.edu/scratch5/galaxy-pugh/galaxy/.venv/bin/activate_this.py'
execfile(activate_this, dict(**file**=activate_this))

**Comment by mvdbeek** [comment]
> So what I should be doing is setting up a different virtual env outside of Galaxy's to run my scripts that use Galaxy's API.

yep, I think this would be best.
