### ISSUE TITLE
Incorrect ordering of deleted datasets in the storage dashboard

### ISSUE THREAD

**Issue by pavanvidem** [galaxyproject/galaxy#16898]
The storage dashboard on the EU server shows the incorrect ordering of the deleted datasets when sorted by size. Datasets that were deleted during the job run were ordered to be the largest.  In the following screenshot, I ordered the datasets by size in descending. The first 4 datasets are empty and supposed to be at the end but they were shown at the beginning. The ordering worked from the 5th dataset onwards.

![image](https://github.com/galaxyproject/galaxy/assets/5268277/fc1115e0-9055-4f87-89ed-6c775781697e)

**Comment by davelopez** [comment]
Thanks for the report!
