### ISSUE TITLE
dataset collection element_identifier lost if intermediate collection moved to new history

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#1689]
We're making use of `.element_identifier` in a few wrappers.
This works fine in most cases, except when running a workflow on a dataset collection that has been moved to a new/different history.
Running a single tool that consumes `element_identifier` still works fine on that same collection.
This is on 15.10/16.01 and dev.
To reproduce, create a small dataset collection, run the select first lines tool over it, then move the newly created collection over to a new history. Now `.element_identifier` is never set, instead `.name` is used (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/wrappers.py#L210).

**Comment by jmchilton** [comment]
Fixed with #1693 I think, right @mvdbeek?

**Comment by mvdbeek** [comment]
Right, thanks @jmchilton
