### ISSUE TITLE
remove the "create workflow" form

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16912]
I suggest we drop the whole step on screenshot below and after clicking "create" we directly create a workflow named "unnamed workflow" and open the editor.

![Galaxy](https://github.com/galaxyproject/galaxy/assets/1814954/4f4ee6af-9844-4538-a46e-e9adff5669ec)

**Comment by ahmedhamidawan** [comment]
Currently loaded with the `id` (workflow created once the editor is opened)
Create on first save (force empty name field to be filled before saving)
