### ISSUE TITLE
Strong password mandatory?

### ISSUE THREAD

**Issue by EmmettPeng** [galaxyproject/galaxy#16918]
Hi, this is technically not a bug but is there any chance Galaxy platform can force users to use strong passwords or the security level of the password can be declared? I haven't seen any related settings in ``config/galaxy.yml``.

Emmett

**Comment by dannon** [comment]
The best way to do this right now would be to have Galaxy defer authentication to external auth (keycloak, etc), which can then enforce password strength, mfa, etc.

**Comment by EmmettPeng** [comment]
@dannon Thanks for your reply. Actually, I noticed that on the registration page, there are some rules for public name (Your public name is an identifier that will be used to generate addresses for information you share publicly. Public names must be at least three characters in length and contain only lower-case letters, numbers, dots, underscores, and dashes ('.', '_', '-').). I wonder if i can modify some related script to do the same to the password.

**Comment by dannon** [comment]
@EmmettPeng Sure, it's not configurable out of the box, but check out https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/security/validate_user_input.py#L42.

I think I'd still recommend Galaxy deferring this to an external platform that specializes in auth handling, though.

**Comment by EmmettPeng** [comment]
This script really helped! Thanks for your tips @dannon
