### ISSUE TITLE
SnpEff eff doesn't properly detect snpeffdb version

### ISSUE THREAD

**Issue by masterrite** [galaxyproject/galaxy#16925]
**Describe the bug**
I downloaded snpeff database manually from [their sourceforge db folder](https://sourceforge.net/projects/snpeff/files/databases/v4_3/), but when I upload it to Galaxy, the program detects it only as SNPeff 4.0, instead of 4.3, which is written in the header. This prevented me from using it in SNPeff eff command 

**Galaxy Version and/or server at which you observed the bug**
"version_major": "23.1",
 "version_minor": "2.dev0"

**To Reproduce**
1. Download [the c elegans db](https://sourceforge.net/projects/snpeff/files/databases/v4_3/snpEff_v4_3_WBcel235.86.zip/download)
2. Upload to Galaxy history
3. Check its information by clicking the i icon
4. See SnpEff version as "SnpEff4.0"
5. Try to select this file for genome source in snpeff eff
6. It will be shown as unavailable

**Expected behavior**
I expected the uploaded snpeffdb to show version SnpEff4.3 and be available in snpeff eff command as a genome source

**Screenshots**
![Snipaste_2023-10-25_12-57-36](https://github.com/galaxyproject/galaxy/assets/20837366/15576a51-2723-488c-8ea5-00919523a1f2)

![Snipaste_2023-10-25_12-56-35](https://github.com/galaxyproject/galaxy/assets/20837366/9a427465-2f77-4136-99b8-2a3253579889)

Thanks

**Comment by wm75** [comment]
It is true that uploading snpeffdbs is currently not working as you'd expect. Luckily, that's also not the best way to get the data into Galaxy. You can use the tool [SnpEff Download](https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/snpeff/snpEff_download/4.3+T.galaxy2) instead to transfer the db directly from sourceforge into your Galaxy history. Use `WBcel235.75` as the db identifier and you'll obtain a usable db dataset with correct metadata.

**Comment by masterrite** [comment]
Thanks! I was able download the correct db with snpeff download. I just thought I should report this bug.
