### ISSUE TITLE
published pages list text handling

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#16926]
If you go to https://usegalaxy.org/pages/list_published you'll see some bleed over text in the `title` and `owner` columns. We should handle these better.

<img width="1027" alt="Galaxy" src="https://github.com/galaxyproject/galaxy/assets/1814954/044b1fb6-970e-4707-9afb-ccb191b4fd5e">

**Comment by guerler** [comment]
This is can be resolved by using the `GridList` component for pages and published pages.

**Comment by guerler** [comment]
Fixed in #17487.
