### ISSUE TITLE
Collect Alignment Summary Metrics/RNA Metrics tools on usegalaxy.org failing

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1692]
Fails on BWA-MEM output that is coordinate sorted.

Error: Fatal error: Exit code 1 () Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/scratch Exception in thread "main" java.lang.NullPointerException at htsjdk.samtools.reference.ReferenceSequenceFileWalker.get(ReferenceSequenceFileWalker.java:87) at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:113) at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:53) at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187) at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:89) at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:99)

**Comment by jennaj** [comment]
**Related**

This error was reported for the same tool around the same time period. Different tool options could be a factor in which error comes up: https://github.com/galaxyproject/galaxy/issues/1710

**Comment by martenson** [comment]
I updated devteam/picard on Main, please test

**Comment by jennaj** [comment]
Thank you, in progress.

**Comment by jennaj** [comment]
@martenson This tool now works on Main :)

However, the related tool (CollectRnaSeqMetrics now at 1.136.0) still fails for the original reason. Odd. https://github.com/galaxyproject/galaxy/issues/1710

**Comment by martenson** [comment]
well, at least some progress :) thanks @jennaj
