### ISSUE TITLE
[minor] When viewing a dataset of an Image type that isn't done yet, clicking again does not reload the view

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#16972]
Steps to reproduce:

- Run a tool which produces an image
- Anxiously click on the view icon while the tool is running, notice the "the image cannot be displayed due to errors" (at least in firefox)
- Keep clicking the Eye even after it turns green
- Nothing happens

Workaround:

- get the message
- view another dataset
- view the original failing dataset

I'm guessing someone added a check of "don't reload the view if it's the one we're already viewing in the main panel", but it'd be useful to not have that exclusion, so I can see my dataset without viewing another first.

**Comment by dannon** [comment]
Wasn't an exclusion, just how vue-router works.  It doesn't by default force reload (or do anything) if the exact same route is pushed that you're already at.  Added a workaround in https://github.com/galaxyproject/galaxy/pull/16982

**Comment by hexylena** [comment]
thanks for the quick fix!

**Comment by hexylena** [comment]
I suspect this may also be happening with re-run (and similar routes.)
