### ISSUE TITLE
Unavailable metadata after extracting non-terminal dataset from collection

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#17003]
**Describe the bug**
When running the `__EXTRACT_DATASET__` tool on a collection element, which hasn't reached the OK state yet, metadata, like index files, will not get copied to the extracted element.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: usegalaxy.eu; release_23.1_europe branch

**To Reproduce**
1. Run __EXTRACT_DATASET__ to extract a dataset, for which Galaxy will build an index (e.g. a bam file), from a collection while that dataset is not ready yet.
2. The __EXTRACT_DATASET__ job will enter the running state, but only finish once the collection element becomes available
3. The now green, extracted dataset will continue to say queued and the download button will start a download without presenting a choice to download the index. Downstream tools relying on the index will also fail.

@mvdbeek could be a side-effect of #16931 (which EU has installed) or a related bug that didn't get fixed by the PR.

**Comment by mvdbeek** [comment]
Oh, that's a big oversight actually. This should happen for any output produced with the extended metadata strategy, don't need special tools for this, this should also happen if you e.g. copied a new/queued/running dataset to a new history. And writing the test I also noticed this is broken in a different way for non-extended metadata jobs.

Thanks a lot for the report!
