### ISSUE TITLE
Server File Paths?

### ISSUE THREAD

**Issue by praveenraj2018** [galaxyproject/galaxy#17006]
I am not sure if Galaxy has a provision of Server File Paths for input and output data.

Proposal:

If Server File Path option is provided and enabled, Galaxy should be able to directly access files stored on the server's local or networked drives; therefore, input files do not have to be transferred to or stored on the server. 

Benefit:

Avoiding file transfers can save significant upload time and avoiding file storage can save significant amounts of disk space.

**Comment by bernt-matthias** [comment]
This is already possible by using symlinks in the [user library import dir] (https://github.com/galaxyproject/galaxy/blob/a1b548556d0875d7ff4f645603dd3d456898c8b1/lib/galaxy/config/sample/galaxy.yml.sample#L1819)

See also https://galaxyproject.org/data-libraries/
