### ISSUE TITLE
New Select Component for a Large Number of Options

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/galaxy#17019]
Out current select component works fine for selecting multiple options even if there are many options available. However, it breaks apart when trying to select many options at once. Here's an example from the admin panel (note: these are not real users, but a mock dataset of 100k)

![image](https://github.com/galaxyproject/galaxy/assets/44241786/37d4e657-3a59-43d0-922b-b9e1ea9ab9a6)

(This screenshot is with the changes from #17015 applied)

The searching and selection works fine, but wanting to select many users at once leads to a bad user experience.

For this reason, I propose we introduce a new form element which is made for selecting a large amount of options.
I think this component should be an alternative to the current select element, rather than a replacement, as it is only necessary in cases where many options are selected at once. For other cases I think the current select component offers a good UX.

**Comment by bernt-matthias** [comment]
Wondering if someone really wants to work manually with large numbers of options, or programmatic (api?) would be used anyway.

**Comment by bgruening** [comment]
I think the options are here users. And this can be a lot depending on the instance.
