### ISSUE TITLE
clarify timezone handling in the notification framework

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17010]
We recently used notifications on Test, see the table below. 1 and 3 created via the UI, 2 created via the API with Z timezone signifier (`"publication_time": "2023-11-10T18:35:00.847Z",`), 4 created via the API without timezone signifier (or seconds).

Notably:
- The API schema suggests timezone signifiers are supported but it does not seem so below.
- It would be nice to group notifications into active/expired so admins don't need to do the math
- We could clarify the language like 
  - "Scheduled to publish xx/yy" to "Published on xx/yy (2 days ago)"
  - "Expires on xx/yy" to "Will expire on xx/yy (in 15 mins)"
  - etc...

```
galaxy_test=> select id, create_time, update_time, publication_time, expiration_time, source, category, variant from notification order by id;
 id |        create_time         |        update_time         |    publication_time     |     expiration_time     | source | category  | variant
----+----------------------------+----------------------------+-------------------------+-------------------------+--------+-----------+---------
  1 | 2023-11-10 17:31:21.400551 | 2023-11-10 17:31:21.40056  | 2023-11-10 17:34:00     | 2023-11-10 18:34:00     | admin  | broadcast | warning
  2 | 2023-11-10 18:33:49.887661 | 2023-11-10 18:33:49.88767  | 2023-11-10 12:35:00.847 | 2023-11-10 12:40:00.847 | string | broadcast | warning
  3 | 2023-11-10 18:44:30.074876 | 2023-11-10 18:44:30.074884 | 2023-11-10 18:45:00     | 2023-11-10 18:50:00     | admin  | broadcast | warning
  4 | 2023-11-10 18:50:40.747023 | 2023-11-10 18:50:40.747031 | 2023-11-10 18:51:00     | 2023-11-10 18:54:00     | admin  | broadcast | warning
(4 rows)
```

in the UI it looks like this:

<img width="339" alt="Screenshot 2023-11-10 at 10 54 33 AM" src="https://github.com/galaxyproject/galaxy/assets/1814954/b01be546-73fb-4268-ac93-ec9fb304b00c">

**Comment by natefoo** [comment]
I also created a notification via the API just now on usegalaxy.org using `  "publication_time":"2023-11-10T19:10"`:
```
galaxy_main=> select id, create_time, update_time, publication_time, expiration_time, source, category, variant from notification where id = 3;
 id |        create_time         |       update_time       |  publication_time   |   expiration_time   | source | category  | variant
----+----------------------------+-------------------------+---------------------+---------------------+--------+-----------+---------
  3 | 2023-11-10 19:07:12.414995 | 2023-11-10 19:07:12.415 | 2023-11-10 19:10:00 | 2023-11-13 00:00:00 | admin  | broadcast | warning
(1 row)
```

The notification was created at `19:07:12`, ~3 minutes before the intended broadcast time of `19:10:00` UTC, but the notification was broadcast in the UI immediately.

**Comment by davelopez** [comment]
> The notification was created at 19:07:12, ~3 minutes before the intended broadcast time of 19:10:00 UTC, but the notification was broadcast in the UI immediately.

@natefoo, thanks for reporting this, I can confirm this is a bug that affects only admins because they can always get all broadcasted notifications (even the inactive ones) but it should have an additional filtering in the UI for them.

Thanks also @martenson, I will try to clarify a bit better in the UI how we present times and investigate what is going on with timezones. What I assumed is that we always work on UTC and never on local time but dealing with datetimes is always tricky and there might be something off around the handling here.
