### ISSUE TITLE
Asynchronous data_source tools protocol seems to be broken?

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#17024]
**Describe the bug**
https://galaxyproject.org/admin/internals/data-sources/#asynchronous-data-depositing and https://pubmed.ncbi.nlm.nih.gov/21531983/ describe a asynchronous, two-step protocol for data_source tools, in which the first response of the remote server does not contain a link that results in a data download (like in the synchronous case), but where Galaxy, instead, gets notified and told in a later request where the asynchronously generated data has been made available.

From my local testing with https://github.com/hexylena/galaxy-data_source-examples using modifications in https://github.com/hexylena/galaxy-data_source-examples/pull/7 it appears that this protocol is broken.

Specifically, all the inter-server communication seems to work as documented, but Galaxy generates the history dataset upon receiving the first response (like in the synchronous case) already, but then proceeds to download the actual content (retrieved via the final request) into a second dataset (not visible in the history).

It's of course equally possible I just configured something wrongly since this is my first attempt at using the feature.

**Galaxy Version and/or server at which you observed the bug**
Commit: dev at c85298b4

**To Reproduce**
1. Run the cherrypy server from the repo above
2. Start Galaxy with the cherrypy_async.xml tool from the same repo
3. Run the tool
4. Logs should look like this:

```
galaxy.tools.actions INFO 2023-11-14 09:18:46,742 [pN:main.1,p:15192,tN:WSGI_2] Handled output named output for tool cherrypy_async (1.562 ms)
galaxy.tools.actions INFO 2023-11-14 09:18:46,742 [pN:main.1,p:15192,tN:WSGI_2] Added output datasets to history (0.060 ms)
galaxy.tools.actions INFO 2023-11-14 09:18:46,743 [pN:main.1,p:15192,tN:WSGI_2] Setup for job Job[unflushed,tool_id=cherrypy_async] complete, ready to be enqueued (1.591 ms)
galaxy.tools.actions INFO 2023-11-14 09:18:46,770 [pN:main.1,p:15192,tN:WSGI_2] Flushed transaction for job Job[id=5,tool_id=cherrypy_async] (26.211 ms)
galaxy.web_stack.handlers INFO 2023-11-14 09:18:46,783 [pN:main.1,p:15192,tN:WSGI_2] Flushed transaction for Job[id=5,tool_id=cherrypy_async] (12.523 ms)
galaxy.web_stack.handlers INFO 2023-11-14 09:18:46,783 [pN:main.1,p:15192,tN:WSGI_2] (Job[id=5,tool_id=cherrypy_async]) Handler '_default_' assigned using 'HANDLER_ASSIGNMENT_METHODS.DB_SKIP_LOCKED' assignment method
uvicorn.access INFO 2023-11-14 09:18:46,783 [pN:main.1,p:15192,tN:MainThread] 127.0.0.1:53784 - "GET /async/cherrypy_async/9/6eb98945e3587f0acacd60ddfdca5555ecc478a4?STATUS=OK&URL=http%3A%2F%2Flocalhost%3A8090%2Fdownload%3Ffilepath%3D%2Fhome%2Fwolma%2Fgalaxy-data_source-examples%2Fcherrypy%2Fworkfile.tmp HTTP/1.1" 200
galaxy.jobs.handler INFO 2023-11-14 09:18:47,896 [pN:main.1,p:15192,tN:JobHandlerQueue.monitor_thread] (5) Job dispatched
galaxy.jobs.command_factory INFO 2023-11-14 09:18:48,000 [pN:main.1,p:15192,tN:LocalRunner.work_thread-2] Built script [/tmp/tmpwjtkkt1p/job_working_directory/000/5/tool_script.sh] for tool command [python '/home/wolma/galaxy_39/tools/data_source/data_source.py' '/tmp/tmpwjtkkt1p/job_working_directory/000/5/outputs/galaxy_dataset_c36d718e-fa67-4cd2-8b9d-3a64e6e33356.dat' 0]
```

and the files directory should have this:
```
tree -s /tmp/tmpwjtkkt1p/files
[       4096]  /tmp/tmpwjtkkt1p/files
├── [       4096]  3
│   └── [       4096]  0
│       └── [       4096]  6
│           └── [          0]  dataset_30693a0f-c953-41bf-abcc-e060f64e7d0a.dat
└── [       4096]  6
    └── [       4096]  e
        └── [       4096]  9
            └── [          8]  dataset_6e951e5a-ccaf-4024-b2f0-f0b9498baabc.dat

7 directories, 2 files
```

where the first, empty file is the one associated with the history, but the second one has the data.
In addition, the tool run never gets recognized as finished, but stays yellow indefinitely.

Would be happy if someone can point me to the correct place in the code base to investigate this.

**Comment by wm75** [comment]
We're working on two new data_source tools currently, one for a Galaxy <-> [cBioportal](https://www.cbioportal.org/) interaction. Don't know yet whether the synchronous protocol would work with cBioportal (hope to find out later this week), but would like to have both options.

**Comment by mvdbeek** [comment]
Can you be more specific ? I would also think that the sync data sources are less than ideal for something new

**Comment by wm75** [comment]
So, cBioportal collects data about cancer stduies, cohorts and patients, and stores molecular data (variant calls) for the samples (but not raw sequencing data). The idea we are working on is that auser might want to select, in cBioportal, all samples from a given study that carry particular genetic variants, but would want to confirm the presence of these recorded variants by reanalyzing the raw data in Galaxy, before drawing any conclusions about these samples.
So after the user's selection of a particular set of samples in the cBioportal UI, there should be an option to send sample IDs and/or mutation lists to Galaxy (where the sample IDs would be used to retrieve the raw data for reanalysis).

In practice, that could work like this:
1. on the main page of cBioportal, the user selects a study, then
2. performs a "Query by Gene" (say, BRAF, for example)
3. on the results page, the Download dropdown could then have a "Send to Galaxy option", which would trigger the response to a data_source tool.

We are in touch with cBioportal devs to support this on their side.

A cheap alternative would be to just have a regular tool that uses the cBioportal API to get the same data, but this will feel very awkward for cBioportal users.
Another alternative might be to have a send to Galaxy option for *all* cBioportal users that lets you select a public instance or specify a custom one (like what dockstore has). This one is not unattractive since, like for Galaxy, there are many cBioportal instances so with a data_source tool we'd have to capture instance information somehow (user preferences?)

Is that detailed enough?

**Comment by PlushZ** [comment]
I am working on another data_source tool Galaxy <-> [MaveDB](https://www.mavedb.org/#/). 
Idea is: 
1. user run Galaxy data_source tool that redirects to MaveDB website
2. user searches for gene (say, CALM1), from search results chooses needed URN of the experiment, goes to the corresponding web-page
3. On the experiment web-page there are two buttons to download 'Scores' or 'Mapped Variants'. For both files the choice 'download' and 'send to Galaxy' will be added
4. When chose 'send to Galaxy', a response is sent to the data source tool with a link to download the file.

**Comment by wm75** [comment]
Aha, the bug reported here was on the wrapper side (see https://github.com/hexylena/galaxy-data_source-examples/pull/9). Now that I understand how to make this work, there are a few other followup issues to address:
- [ ] `tool_type="data_source_async"` does not seem to be documented anywhere - I only found it via the source code at: https://github.com/galaxyproject/galaxy/blob/1666892918ca86eb140b59d42b75981a2a184475/lib/galaxy/tools/actions/__init__.py#L481-L485
- [ ] data source tools should probably be modernized to not require `provided_metadata_style="legacy"`
- [ ] when trying to bump synchronous data_source tools (`tool_type="data_source"`) from profile="20.09" to profile="21.09", one encounters an import error:
  ```
  Traceback (most recent call last):
    File "/home/wolma/galaxy/tools/data_source/data_source.py", line 19, in <module>
      from galaxy.datatypes import sniff
  ModuleNotFoundError: No module named 'galaxy'
  ```
  because galaxy/lib isn't in sys.path. Strangely, this is specific to the case of sync data_source tool and profile > 20.09.

**Comment by wm75** [comment]
Addressing all issues above in #17422
