### ISSUE TITLE
open "History Storage Overview" in the middle panel

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17026]
If you press the button on history the overview currently takes over all panels (and the top button [shown below] navigates to dashboard, not back to the previous page). It would be nice if it would just open in the middle pane, leaving side panels as is.

<img width="533" alt="Screenshot 2023-11-16 at 2 05 29 PM" src="https://github.com/galaxyproject/galaxy/assets/1814954/971f4f52-87c6-4416-8569-863fbbb8b4fa">

**Comment by bgruening** [comment]
>  It would be nice if it would just open in the middle pane, leaving side panels as is.

Can you provide a reason why you think it should not take the entire space?

**Comment by ahmedhamidawan** [comment]
> Can you provide a reason why you think it should not take the entire space?

A reasoning i can think of for this is:

User clicks on the storage button _for the current history_ from the `HistoryPanel` and without losing context (they might have scrolled to a point in the history, have filters applied, selected items...), they see the storage overview in the center. (Demo in Screencast in #17043). They could at that point even switch to other histories and see the storage overview for each without losing context of the history panel.

This ofc doesn't mean we always force all the Storage overviews to only show in this multi-panel view (also seen in screencast), if you go to the Storage dashboard directly, it would still show all children routes on the full page.

**Comment by dannon** [comment]
> '...without losing context'

Exactly.  There's just no need to shift a user's entire context.  If the concern is that on small screens folks need more real-estate, then we can make the context more responsive to that, but I continue to not understand the more recent push for 'zen mode' or maximum whitespace just because you don't 'need' particular components in some contexts.  There's significant value in minimizing context changes and using appropriate content display regions when availables.

**Comment by davelopez** [comment]
Sorry, I missed the full discussion and merged this :grimacing: 
But anyway, this change makes a lot of sense to not lose the context of the current history and it is only when directly accessing the storage visualization. Also, in combination with the Activity Bar we have a bit more space in the central area now, so it all fits nicely.
