### ISSUE TITLE
Different types of job messages

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#17023]
I was just trying to add typing to the module and found that these job_messages are sometimes dict and sometimes str:

- https://github.com/galaxyproject/galaxy/blob/c85298b48e3a4ffc61e0377e1c900524b915f5c5/lib/galaxy/tool_util/output_checker.py#L100
- https://github.com/galaxyproject/galaxy/blob/c85298b48e3a4ffc61e0377e1c900524b915f5c5/lib/galaxy/metadata/set_metadata.py#L343C38-L343C38

Guess some type of class might be good for job messages?

Edit: Or just make it a simple `str`?

_Originally posted by @bernt-matthias in https://github.com/galaxyproject/galaxy/issues/17022#issuecomment-1809864463_

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/blob/c85298b48e3a4ffc61e0377e1c900524b915f5c5/lib/galaxy/metadata/set_metadata.py#L343C38-L343C38

oops, that's wrong, we probably need to retrospectively turn that into a dict when serializing the job messages.

**Comment by bernt-matthias** [comment]
A first attempt here https://github.com/bernt-matthias/galaxy/commit/025429abb77fa07dedf026aace60ee331fadfa92

But I have the feeling that job messages as a dict are not ideal .. maybe a class?
