### ISSUE TITLE
Broadcast Notifications do not Accept Local URLs

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/galaxy#17033]
**Describe the bug**
When creating a new broadcast notification and attempting to set a local action link  (e.g "/workflows/list"), the backend returns an error.

There is front-end code in place which makes it seem like this should be supported, [here](https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Notifications/Broadcasts/BroadcastContainer.vue#L53-L58).

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: Dev
Commit: a1b548556d0875d7ff4f645603dd3d456898c8b1

**To Reproduce**
1. Go to Admin Panel
2. Create a new Broadcast with a local action link
3. Click create

**Expected behavior**
Notification is created

**Screenshots**

Example broadcast:
![image](https://github.com/galaxyproject/galaxy/assets/44241786/94e66ff5-9cf0-4d4f-b46a-c3feb060d9e3)

Error Message:
![image](https://github.com/galaxyproject/galaxy/assets/44241786/9eacdc07-7339-433a-a15b-c877e8abb0d0)

**Additional context**
This bug was found while working on #17032

**Comment by mvdbeek** [comment]
yep, it's annotated as a url and it can apparently not be a url. Should it perhaps always be a full URL to avoid ambiguities with whether or not the proxy prefix needs to be included ?

**Comment by hexylena** [comment]
>  Should it perhaps always be a full URL to avoid ambiguities with whether or not the proxy prefix needs to be included ?

given subdomain, perhaps better to not use a full URL, to avoid redirecting users to a subdomain where they're not logged in?

**Comment by mvdbeek** [comment]
how do you want to solve the prefix/no prefix then ?

**Comment by hexylena** [comment]
I don't know. I don't have any solution there, I'm just flagging a potential issue with the full URL version.

**Comment by davelopez** [comment]
I guess we can change the type annotation to make it more relaxed to `Union[AnyUrl, str]` because it was meant to be compatible with relative URLs the handling for relative URLs is done in the `onActionClick` as @ElectronicBlueberry pointed out.
