### ISSUE TITLE
Workflow run form allows submission without selecting required data

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#17040]
<img width="1389" alt="Screenshot 2023-11-16 at 15 55 33" src="https://github.com/galaxyproject/galaxy/assets/6804901/747748c1-7af0-4a02-b9a7-cb0c80e564fc">

let's me click on run and will fail.

**Comment by martenson** [comment]
Dupe of https://github.com/galaxyproject/galaxy/issues/16951 ?

**Comment by bernt-matthias** [comment]
Same seems possible for selects https://github.com/galaxyproject/galaxy/issues/11182

**Comment by mvdbeek** [comment]
Yes, should both be fixed by https://github.com/galaxyproject/galaxy/pull/17048
