### ISSUE TITLE
workflow editor crashes on save with duplicate output names

### ISSUE THREAD

**Issue by dmaticzka** [galaxyproject/galaxy#1704]
The new field "Label" of the Configure Output section in the workflow editor (introduced with 16.01?) is by default unset. These labels have to be unique across the workflow for all outputs marked as workflow output.

When trying to save a workflow with multiple workflow outputs without Label the editor shows a popup with message "Server error Duplicate workflow outputs with name [default] found." When I activate the single ignore button and try to save a second time the workflow editor gets stuck while displaying the saving workflow progress bar and the page has to be reloaded for further editing. At no point the workflow is actually saved.

Having the Labels unset in the first place breaks older workflows with outputs marked as workflow output. In order to edit and save these workflows all Label fields have to be filled in manually before the workflow can be saved again with 16.01. Otherwise the workflow editor crashes as described above and all changes are lost.

**Comment by mvdbeek** [comment]
I have seen this happening as well.

**Comment by bgruening** [comment]
Would be nice to fill in unique ids by default during the workflow migrations.

**Comment by dmaticzka** [comment]
Would also be nice to fill in unique ids whenever the "mark as output" button is pressed in the workflow editor. This button is part of the "tool boxes" but the Label field is found in the tool setting, the connection between the two is not immediately clear.

**Comment by jmchilton** [comment]
I've tried in Chrome and Firefox and I cannot reproduce. Does anyone have a simple set of steps to follow from a new workflow to exhibit this behavior?

**Comment by dmaticzka** [comment]
I can't reproduce it when starting from a new workflow, seems only to happen with workflows created before the 16.01 update. I can try to export one of the failing workflows tomorrow.

**Comment by mvdbeek** [comment]
Yes, same here.

**Comment by jmchilton** [comment]
Tried:
- Checkout 15.10 - create a workflow with 3 concat dataset steps - two with workflow outputs labelled.
- Checkout 16.01 and restart Galaxy
- Load workflow, modify, and save.

And no problems.

I'll see if I can deduce the problem from the reported error.

**Comment by mvdbeek** [comment]
@jmchilton not really able to reproduce it cleanly either, but maybe you have an idea based on these workflows
After upgrade:
https://gist.github.com/mvdbeek/c8d947fcd21385125ad2
Before:
https://gist.github.com/mvdbeek/9e99759a4b4867a68fcf

Look at all those 

```
      "workflow_outputs": [
        {
          "label": null,
          "output_name": "output1",
          "uuid": null
        },
        {
          "label": null,
          "output_name": "output1",
          "uuid": null
        },
        {
          "label": null,
          "output_name": "output1",
          "uuid": null
        },
        {
          "label": null,
          "output_name": "output1",
          "uuid": null
        },
        {
          "label": null,
          "output_name": "output1",
          "uuid": null
        },
        {
          "label": null,
          "output_name": "output1",
          "uuid": null
        },
        {
          "label": null,
          "output_name": "output1",
          "uuid": null
        },
        {
          "label": null,
          "output_name": "output1",
          "uuid": null
        }
      ]
```

Coincidentally that correponds to the number of steps, so I guess this happens ssomewhere during building the steps_dict

**Comment by mvdbeek** [comment]
I just realised it starts at the bowtie step, which had renamed tool_parameters between 0.6 and 0.7 ... that is probably related.

**Comment by dmaticzka** [comment]
I also have these crazy output sections. The number of repetitions are the same within each workflow but are different between workflows. Is it possible that this has to do something with having multiple copies of a workflow during the update?

The following only confirms that they are the reason for the misbehaviour. 

```
            "workflow_outputs": [
                {
                    "label": null, 
                    "output_name": "output", 
                    "uuid": null
                }, 
                {
                    "label": null, 
                    "output_name": "output", 
                    "uuid": null
                }, 
                {
                    "label": null, 
                    "output_name": "output", 
                    "uuid": null
                }
            ]
```

I see this type of construct in all the workflows that are not saveable after the upgrade to 16.01. I can make any of the usaveable workflows saveable again by simply deactivating and activating the "set as output" button on the toolboxes. The resulting workflow then get the workflow_outputs dictionaries correctly set. The section above becomes

```
            "workflow_outputs": [
                {
                    "label": null, 
                    "output_name": "output", 
                    "uuid": "db765105-5391-444e-bf05-1cf06db2b67c"
                }
            ]
```

I can make any workflow non-importable by exchanging a working workflow_outputs section with a dictionary that has "output_name" set to the same string more than once like this. On import I get same error message seen from the workflow editor ("Duplicate workflow outputs with name [output] found.") 

This is the workflow that can't be saved: [online_unsaveable.ga.txt](https://github.com/galaxyproject/galaxy/files/124810/online_unsaveable.ga.txt)
And this is the same workflow after reseting the workflow outputs in the editor: [online_unsaveable_resetoutput.ga.txt](https://github.com/galaxyproject/galaxy/files/124807/online_unsaveable_resetoutput.ga.txt)

All of this works nicely when I start with importing the same workflow with a version saved before the 16.01 update. When I upload an old workflow [offline_pre_update.ga.txt](https://github.com/galaxyproject/galaxy/files/124658/offline_pre_update.ga.txt) the field user_outputs is converted to workflow_outputs [offline_pre_update_after_upload.ga.txt](https://github.com/galaxyproject/galaxy/files/124662/offline_pre_update_after_upload.ga.txt). Resetting the workflow output buttons then fills in workflow_outputs with dictionaries [offline_pre_update_after_upload_resetoutput.ga.txt](https://github.com/galaxyproject/galaxy/files/124664/offline_pre_update_after_upload_resetoutput.ga.txt). This final workflow is identical to the rescued online-workflow, except that the uuids are different.

**Comment by jmchilton** [comment]
Okay... making some progress on my end. I think there is something of a problem pre-16.01 that just didn't matter in the past. 2015 Galaxy can be made to attach multiple workflow outputs for the same output name. Steps to reproduce
- Add the [create_10.xml](https://github.com/galaxyproject/galaxy/blob/dev/test/functional/tools/create_10.xml) to the tool panel.
- Start Galaxy 15.10, create a workflow, add an input and a create 10 step, save and close.
- Reopen - mark output 7 and output 4 as outputs, save and close.
- Reopen - unmark 4 and mark 1, save and close.
- Reopen - unmark 1 and mark 4, save and close.
- Download the export summary for the workflow ID - (e.g. http://127.0.0.1:8080/api/workflows/33b43b4e7093c91f/download?style=editor)
- Notice multiple copies of 7.

```
            "workflow_outputs": [
                "out_file7", 
                "out_file7", 
                "out_file7", 
                "out_file4"
            ]
```

I'm thinking I'll silently fix the workflow on export and let the workflow just "be fixed" on next save.

**Comment by mvdbeek** [comment]
Sounds reasonable.
If you do a PR I will be able to give you feedback from our semi-production server.

**Comment by bwlang** [comment]
This affected many workflows for me and is fixed for me with the latest patch.

Thanks!

**Comment by bgruening** [comment]
@tzk can you confirm that this is fixed for you as well? I would like to close this one :)
Thanks @jmchilton!

**Comment by dmaticzka** [comment]
@bgruening everything working fine now, thanx for the fix @jmchilton!
