### ISSUE TITLE
Implement tadviewer interactive tool

### ISSUE THREAD

**Issue by hechth** [galaxyproject/galaxy#17066]
The current tadviewer interactive tool does not display anything when opened on usegalaxy.eu.

**Comment by mvdbeek** [comment]
Can you add some details here, are you saying the tool is broken and if so how, what version of Galaxy are you're using, do you intend to fix this yourself etc.

**Comment by mvdbeek** [comment]
It also doesn't look like we have such a tool ?

**Comment by hechth** [comment]
@mvdbeek sorry, this is more or less a placeholder.

Yes, the tool exists, it is an interactive tool and yes, I intend to fix this myself.

**Comment by hechth** [comment]
@mvdbeek Oh, I forgot that EU runs a separate fork ... my bad
