### ISSUE TITLE
Multiple Job Handlers Running Workflows

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1706]
@bgruening reported multiple job handlers running the same workflow. This is a real problem. Might explain the slow reported elsewhere also.

https://gist.github.com/bgruening/249c2979600c3274b8ca

**Comment by jmchilton** [comment]
Actually, I updated this code is should distribute workflow scheduling across job handlers. This is expected. I'll open a PR to improve the logging to see if there is a problem with a workflow being scheduled in more than one place.

**Comment by bgruening** [comment]
I also see the same jobs scheduled again and again and can not get rid of them via restart.
