### ISSUE TITLE
`export_remote` fails to S3 bucket with `NotImplementedError` when using `s3fs` file source plugin

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#17089]
**Describe the bug**
Using the following writable file source config:

```yaml
- type: s3fs
  label: Genome Ark EXPORT HERE
  requires_groups: GenomeArkExport
  id: genomeark_galaxy
  doc: Access to Genome Ark open data on AWS.
  bucket: genomeark
  writable: true
  secret: "{{ genomeark_galaxy_aws_secret_access_key }}"
  key: "{{ genomeark_galaxy_aws_access_key_id }}"
```

The export job results in the following traceback:

```pytb
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_export/export_remote.py", line 79, in <module>
    main()
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_export/export_remote.py", line 56, in main
    if write_if_not_exists(file_sources, target_uri, real_data_path):
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_export/export_remote.py", line 35, in write_if_not_exists
    file_source.write_from(file_source_path.path, real_data_path)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/files/sources/__init__.py", line 300, in write_from
    self._write_from(target_path, native_path, user_context=user_context, opts=opts)
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/files/sources/s3fs.py", line 74, in _write_from
    raise NotImplementedError()
NotImplementedError
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1.2.dev0
Commit: 5a1f3f9c7ae0a65bcc841c513c0f4836e2f5575e

**Additional context**
This same config also fails on usegalaxy.eu.

S3 export is working on @abueg's server using the deprecated (removed in 23.1) `s3` plugin.

**Comment by bgruening** [comment]
Arg, I forgot that I had the same problem: https://github.com/usegalaxy-eu/infrastructure-playbook/commit/e85c7caf09dc3f6a23136a057d0eebc126cd4ed9 and then did not tested the upload again :(

**Comment by martenson** [comment]
This was removed as redundant here https://github.com/galaxyproject/galaxy/pull/15497

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/17100, and should be live on usegalaxy.org in a couple of minutes
