### ISSUE TITLE
Sniff error for ebi_sra_main tool with .bz2 compressed data at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1709]
**Example** 

Note that the file is sourced from the "Submit files (galaxy)" column in the data source's table. These should always load.

> EBI SRA: ERR358485 File: ftp://ftp.sra.ebi.ac.uk/vol1/ERA259/ERA259854/fastq/NB_CR561898_R1.fastq.bz2

**Error**

> ---
> 
> info url: XX
> job id: XX
> tool id: ebi_sra_main
> tool version: 1.0.1
> job pid or drm id: XXX.roundup
> ## job tool version:
> 
> job command line:
> ## python /galaxy-repl/instances/main/server/tools/data_source/data_source.py /galaxy-> repl/main/files/XXXX.dat 0
> 
> job stderr:
> 'Data' object has no attribute 'sniff'

**Workaround**

If you are having this problem, copy and paste the link directly into the Upload tool

**What the UI looks like.. dataset 16 is Upload with URL, dataset 17 is EBI SRA direct "Galaxy" link**

<img width="243" alt="screen shot 2016-02-09 at 12 59 03 pm" src="https://cloud.githubusercontent.com/assets/8999735/12930405/f7a151c8-cf2c-11e5-8553-bb63068d87d8.png">

**Comment by yhoogstrate** [comment]
Is it possible this has something to do with it:

https://github.com/galaxyproject/galaxy/compare/dev...yhoogstrate:auto_format?expand=1#diff-9870223666fd2b2f0f958a34bde3ededR12 ?

**Comment by jennaj** [comment]
@yhoogstrate It could. The .bz2 extension for these particular files is new from the data provider (used to be always .gz).

@blankenberg You will know more about the root cause and best fix than I. What do you think?

**Comment by jennaj** [comment]
Any decision made about how to proceed yet? The default "send to Galaxy" links being usable seems important for community usage.

**Comment by jennaj** [comment]
This is now fixed. Test history: https://usegalaxy.org/u/jen/h/ebi-sra-bz2-load-test-err358485
