### ISSUE TITLE
do not display admin notification interface when not enabled

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17108]
I believe when `enable_notification_system=false` (default) the link to `Notifications and Broadcasts` should either be hidden or it should just show a message "Please enable this in the Galaxy configuration first" so admin is not exposed to interface that is not supposed to work.

**Comment by davelopez** [comment]
Good catch, I like the idea of the message telling you to activate it in the config instead of hiding the button :+1:

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/17114
