### ISSUE TITLE
CollectRNASeqMetrics configuration issues at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1710]
**Problem**

Tool errors out due to a problematic dbkey.fa path. Could be .loc files or something else.

**Error: Note the path for the reference genome ... ??**

> tool id: toolshed.g2.bx.psu.edu/repos/devteam/picard/picard_CollectRnaSeqMetrics/1.126.0
> tool version: 1.126.0
> 
> job stderr:
> Fatal error: Exit code 1 ()
> Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/scratch
> Exception in thread "main" picard.PicardException: Sequence dictionaries differ in /galaxy-repl/main/files/XX.dat and /galaxy-repl/main/files/XX.dat
>        at picard.analysis.directed.RnaSeqMetricsCollector.makeOverlapDetector(RnaSeqMetricsCollector.java:76)
>        at picard.analysis.CollectRnaSeqMetrics.setup(CollectRnaSeqMetrics.java:109)
>        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:100)
>        at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:53)
>        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:187)
>        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:89)
>        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:99)
> Caused by: htsjdk.samtools.util.SequenceUtil$SequenceListsDifferException: Sequences at index 20 don't match: 20/227966/chr4_GL456350_random 20/14945/chr4_JH584292_random/UR=file:/space/jen/new_genome/mm10/picard_index/mm10.fa/M5=c2ff41899e0f684fd93b28c58756e02f
>        at htsjdk.samtools.util.SequenceUtil.assertSequenceListsEqual(SequenceUtil.java:121)
>        at htsjdk.samtools.util.SequenceUtil.assertSequenceDictionariesEqual(SequenceUtil.java:169)
>        at picard.analysis.directed.RnaSeqMetricsCollector.makeOverlapDetector(RnaSeqMetricsCollector.java:74)
>        ... 6 more

**Reporter**
1. galaxy-bugs [galaxy-bugs] Galaxy tool error report from XX (picard_CollectRnaSeqMetrics) on 2/5/2016 
1. Galaxy Biostars https://biostar.usegalaxy.org/p/15941/

**Related**

This error was reported for the same tool around the same time period. Different tool options could be a factor in which error comes up: https://github.com/galaxyproject/galaxy/issues/1692

**Comment by martenson** [comment]
I updated devteam/picard on Main, please test

**Comment by jennaj** [comment]
Thank you, in progress.

**Comment by jennaj** [comment]
@martenson CollectRnaSeqMetrics (now at 1.136.0) still fails for the original reason at Main. Odd, since the other picard tool works great now (same version, ticket https://github.com/galaxyproject/galaxy/issues/1692)

<img width="919" alt="screen shot 2016-03-08 at 2 46 05 pm" src="https://cloud.githubusercontent.com/assets/8999735/13619180/90fcef10-e53c-11e5-82d8-9b7879a5b9c1.png">

**Comment by jennaj** [comment]
Think I found the problem - it was with the optional rRNA input. If not used, no error. That input has to be formatted very specifically and the tool form help needs to be improved to describe how. I'll do that, these are the tickets for it:

- https://github.com/galaxyproject/tools-iuc/issues/1254
- https://github.com/galaxyproject/tools-iuc/issues/1255

Update: Inputs are difficult to get right for this tool. Input BAMs must be sorted with **NGS: Picard > ReorderSam** or job fails when using optional rRNA input (also has a picard dict). Add this to the tool form help ticket https://github.com/galaxyproject/tools-iuc/issues/1254.
