### ISSUE TITLE
Creator information becomes invisible after visiting the best practices tab

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#17130]
**Describe the bug**
Creator information is invisible after visiting the best practices tab (I suspect also works via other edits)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1.4dev0
Galaxy: https://usegalaxy.eu

**To Reproduce**

1. import this worklfow https://usegalaxy.eu/u/helena-rasche/w/debugging-missing-creator
2. Open in editor
3. Note that creator/organisations are defined
4. Go to best practices tab
5. Return to edit metadata tab (name/annotation)
6. Note that creator/organisations are missing
7. Download workflow
8. They're still present.

**Comment by nick2432** [comment]
Can I contribute to this issue? I'm new here, but I have experience contributing to many other organizations. Is there a Discord channel or any other channel where I can discuss and get assistance?

**Comment by hexylena** [comment]
(response posted in https://github.com/galaxyproject/galaxy/issues/17136)

**Comment by ahmedhamidawan** [comment]
Fixed in #17406
