### ISSUE TITLE
Multiselect option appears for single select

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#17140]
**Describe the bug**
Noticed that the new advanced multi select component seems to appear also for regular single select fields.

**Galaxy Version and/or server at which you observed the bug**
Current dev.

**Expected behavior**
The caret-icon allowing users to switch to the column-based select field component should not be shown.

**Screenshots**
<img width="916" alt="image" src="https://github.com/galaxyproject/galaxy/assets/2105447/ebf0ee28-7cb5-4c98-a197-1add44864269">

<img width="880" alt="image" src="https://github.com/galaxyproject/galaxy/assets/2105447/2ef69e45-64dc-469c-8340-3ac7ec8f8ee0">

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/17146, I think ?

**Comment by guerler** [comment]
Thank you!
