### ISSUE TITLE
Enhance MultiView by Displaying a Fixed Number of Recent Histories Instead of Always Tracking Pinned Histories, plus other improvements

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#17143]
As discussed [on Dec 07 2023 in galaxyproject/wg-ui-ux](https://matrix.to/#/!XciPHtOkuKNqKoVeKD:gitter.im/$7PiB7hfuavpasdi87FPhuBlKtzlrdlehbQ9CwQ5fP2Y?via=gitter.im&via=matrix.org), the Multi history view currently tracks histories you've loaded up previously. This can be annoying for users as this list of pinned histories is not updated for the histories created/updated recently, and a lot of clicks are needed to utilize this view.

Instead, it would be a more useful view if:
1. By default, the multi-history view is loaded up with the n most recently updated histories. 
    - The user can then, ofc, change the currently "selected" histories for this view, if they want
    - ~~In the case the user changes the currently selected histories, we start tracking the time this occurs, and whatever the currently selected histories are~~
    - ~~... until a certain time limit when we revert to the default n most recent histories.~~
    - In the case the user changes the currently selected histories, we start tracking them (like we already do).
    - Then in addition, we have a button somewhere in the MultiView for "Clear all from view" or "Show only recent", which is more explicit and though it requires a click, it is just one. (as recommended by @davelopez below)
2. Instead of using the modal to change the histories in view, or using the Right `HistoryPanel` to create histories when MultiView is active:
    - we move the History Selector (for the MultiView) to a fixed position in the left panel (?) (maybe in the form of an `ActivityBar` activity?)
    - and, add a `Create History` button in the left "selector" panel as well

**Comment by davelopez** [comment]
I like those improvements, the only concern I have is with the following:

> until a certain time limit when we revert to the default n most recent histories.

I think this time-based approach is somewhat obscure for the user, maybe just adding another button to this new button toolbar for  "Clear all from view" or "Show only recent" is more explicit, it requires a click, but it is just one.
