### ISSUE TITLE
Tool favorites broken

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#17150]
**Describe the bug**

On eu one can favorite a tool, but in the tool menu they are not shown when the favorites icon is clicked (searching for `#favorites`, i.e. the search result is empty.

On org a tool can't be favorited at the moment. The user gets an error, e.g. `Failed to add 'toolshed.g2.bx.psu.edu/repos/devteam/add_value/addValue/1.0.1' to favorites.`.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: Probably 23.1 / 23.2
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**

See above

**Comment by ahmedhamidawan** [comment]
I believe the favorites list needs to be updated (to the userStore or the toolStore) when a favorite is added
