### ISSUE TITLE
Python 3 support.

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#1715]
Python 2.7 [will not be maintained past 2020](http://pythonclock.org/).

Moreover, some Galaxy dependencies dropped Python2 support: cachetools, cmd2, cwltool, numpy, schema-salad

Add support for Python >= 3.5 while maintaining support for Python 2.7.

xref.: https://trello.com/c/dZcCVf9I/2702-migrate-to-python-3

### Useful tools and documentation

https://docs.python.org/3/howto/pyporting.html
https://docs.python.org/2/library/2to3.html
http://python-future.org/
https://six.readthedocs.io/
http://python3porting.com/

### Dependencies which need to be ported, dropped or updated
- [x] [bx-python](https://github.com/bxlab/bx-python): https://github.com/bxlab/bx-python/pull/7, https://github.com/bxlab/bx-python/pull/25, https://github.com/galaxyproject/galaxy/pull/5492
- [x] Cheetah: replaced with [Cheetah3 fork](https://github.com/CheetahTemplate3/cheetah3) in https://github.com/galaxyproject/galaxy/pull/5359
- [x] Fabric: fabric/fabric#1424, replaced with [Fabric3](https://github.com/mathiasertl/fabric/) fork in https://github.com/galaxyproject/galaxy/pull/5359
- [x] [feedparser](https://github.com/kurtmckee/feedparser): was copied inside https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/util/sanitize_html.py , removed in https://github.com/galaxyproject/galaxy/pull/5642
- [x] [mercurial](https://www.mercurial-scm.org/): https://www.mercurial-scm.org/wiki/Python3, we should use the command line interface through `subprocess` instead of using the [Mercurial API](https://www.mercurial-scm.org/wiki/MercurialApi) https://github.com/galaxyproject/galaxy/pull/9065
- [x] [NoseHTML](https://github.com/galaxyproject/nosehtml): PR #https://github.com/galaxyproject/nosehtml/pull/1
- [x] [paste](https://github.com/cdent/paste)
- [x] [pulsar](https://github.com/galaxyproject/pulsar): https://github.com/galaxyproject/pulsar/issues/152, https://github.com/galaxyproject/pulsar/commit/5b663c3027ec31ef2ce2c58335333bcdf593b5f8, https://github.com/galaxyproject/pulsar/pull/156, https://github.com/galaxyproject/galaxy/pull/5494
- [x] [pygithub3](https://github.com/copitux/python-github3): used only in `scripts/bootstrap_history.py`, should be replaced with [PyGithub](https://github.com/PyGithub/PyGithub)
- [x] [sgmllib](https://docs.python.org/2/library/sgmllib.html): removed in https://github.com/galaxyproject/galaxy/pull/5642
- [x] SVGFig: issue #1717, PR #1747
- [x] twill: [branch 2.0](https://github.com/Cito/twill/tree/2.0) of Cito's fork supports Python >= 3.3, then https://github.com/galaxyproject/galaxy/pull/2656 can be reverted. Or better: replace with selenium tests
- [x] [WebError](https://github.com/Pylons/weberror): unmaintained, even the latest 0.13.1 release doesn't support Python 3 and there is no interest in adding support, see e.g. https://github.com/Pylons/weberror/pull/18 . It could be replaced with [Werkzeug](https://palletsprojects.com/p/werkzeug/), as suggested in https://github.com/galaxyproject/galaxy/pull/1017 (weberror removed in https://github.com/galaxyproject/galaxy/pull/8877)
- [x] [WebHelpers](https://bitbucket.org/bbangert/webhelpers): unmaintained, removed in https://github.com/galaxyproject/galaxy/pull/5359
### Tips
- Use

```
2to3 -w -n FILE
```

  to port a file to Python3, then revert unnecessary changes and use `six` for anything that breaks Python2.7
- If 2to3 suggests to enclose a call to the `keys()`, `values()` or `items()` methods of a `dict` inside `list( )`, it may be unnecessary, e.g. if the `dict` is just iterated over a loop. But if items are added or deleted from the `dict` (changing its size) inside the loop, then making a copy of it with `list( )` is necessary.
- Add

```python
from __future__ import print_function
```

  at the top of a file when changing `print` to `print()` in it.
- Substitute `UserDict.DictMixin` with `collections.(Mutable)Mapping` and add missing methods to the class inheriting from it
- Substitute `string.letters`, `string.lowercase` and `string.uppercase` with `string.ascii_letters`, `string.ascii_lowercase` and `string.ascii_uppercase` respectively
- Change calls to `string.maketrans` to:

```python
try:
    maketrans = str.maketrans
except AttributeError:
    from string import maketrans
```
- Change calls to `pipes.quote()` to `six.moves.shlex_quote()`
- Change calls to `filter()` and `map(lambda ...)` to list comprehensions or generator expressions
- If `d` is a `dict`, change:

```python
d.keys()[0]
d.values()[0]
d.items()[0]
```

  to:

```python
next(iter(d.keys()))
next(iter(d.values()))
next(iter(d.items()))
```
- If a class overrides the `__nonzero__()` method, this should be renamed to `__bool__()` and after its definition, the following alias should be added:

```python
    __nonzero__ = __bool__
```
- if the `long` type is needed, add the following line after the imports:
```python
if sys.version_info > (3,):
    long = int
```

- Since Python 3.7 `async` and `await` are keywords, variables with these names need to be renamed.
- In Python 3 the return value from `subprocess.check_output()` is a bytestring. If this value is going to be processed as a string, it needs to be decoded.

**Comment by jmchilton** [comment]
wchartype is just one file with 200 lines it seems, we should probably just bring that into util and update from Python 3

**Comment by jmchilton** [comment]
Cheetah is dead but others are interested in upgrading to Python 3:
- https://github.com/cheetahtemplate/cheetah/pull/7
- https://github.com/cheetahtemplate/cheetah/pull/9
- https://github.com/cheetahtemplate/cheetah/pull/11/files

**Comment by mvdbeek** [comment]
[sanitizie_html.py](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/util/sanitize_html.py) is mostly copied from [feedparser](https://github.com/kurtmckee/feedparser) and uses sgmllib that is not part of python 3 anymore.
We could externalize this dependency and make sure it works well in python3.
Currently there are some hickups with sgmllib import, that should be easy to fix.

**Comment by natefoo** [comment]
For the record, bx-python is [here now](https://github.com/bxlab/bx-python)

**Comment by natefoo** [comment]
@dannon is getting rid of the SVGFig dependency in #1747.

**Comment by natefoo** [comment]
Mercurial is used in Galaxy for tool installations and non-installable-revision updates.

**Comment by nsoranzo** [comment]
@natefoo Feel free to update the issue description for anything missing/wrong!

> Mercurial is used in Galaxy for tool installations and non-installable-revision updates.

Do you think we can get rid of it or use python-hglib?

**Comment by natefoo** [comment]
Or hgapi, possibly. Some parts will be easier than others. There is some pretty low level stuff going on for example [here](https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/util/hg_util.py), that would need to be reimplemented.

**Comment by hexylena** [comment]
> Mercurial is used in Galaxy for tool installations and non-installable-revision updates.

Given that the hg ts api was [deprecated in 15.10](https://github.com/galaxyproject/galaxy/pull/1194), can we please get rid of it instead of re-implementing it?

**Comment by natefoo** [comment]
`hg push` to a TS was deprecated. TS repo versioning and backend format remains hg, as is the install method (clone) and Galaxy-side on-disk updating method (unless I am mistaken).

**Comment by natefoo** [comment]
That said, I am in favor of removing any Galaxy-side hg installation stuff and not opposed to changing the TS repos to another format (but that would be a lot of work).

**Comment by hexylena** [comment]
@natefoo sorry for nitpicking, but 

> The direct access to Tool Shed repositories through the Mercurial API is deprecated

sounds like there _should_ be zero access to the TS HG api, whether push or pull.

> TS repo versioning and backend format remains hg, as is the install method (clone) and Galaxy-side on-disk updating method (unless I am mistaken).

yeah, we aren't going to change the backend format any time soon for TS1. If there's _any_ way we can look at fixing the clone + on-disk update method with tarballs or similar as an interim fix...

**Comment by natefoo** [comment]
Perhaps a poorly worded notification, unless I'm wrong and that was really the intent. But if it was, there's no replacement for installs at this time. @martenson ?

**Comment by hexylena** [comment]
@natefoo I'm sure you're right, I'm just reading it too <s>hopefully</s> closely

**Comment by yhoogstrate** [comment]
There is a small problem when `hg push` will be entirely disabled.

When you create a .tar.gz archive of a file with chmod 444 and you upload it in the tool shed, galaxy can not overwrite the read only file anymore (in an upcoming revision). The only way to overwrite or remove such file is by using mercurial.

**Comment by natefoo** [comment]
@yhoogstrate That's a bug. =)

**Comment by nsoranzo** [comment]
Indeed, @yhoogstrate can you open a separate issue with all the details to reproduce?

**Comment by mr-c** [comment]
Hello, is there interest in Galaxy signing the http://www.python3statement.org/ ?

**Comment by nsoranzo** [comment]
@mr-c I think that 2020 may be too early for us, we still have quite a bit of work to finish Python3 support.

**Comment by mvdbeek** [comment]
There are a bunch of new options:
  - [WebHelpers2](https://github.com/mikeorr/WebHelpers2), but seems unmaintained as well?
  - [Fabric3](https://github.com/mathiasertl/fabric/) should be pretty close to Fabric
  - Cheetah3 seems to work fine

**Comment by nsoranzo** [comment]
@mvdbeek I think we should be able to get rid of at least WebHelpers, I'm working on that.

**Comment by giff-h** [comment]
Fair warning that `next(iter(dict.keys()))` or `values` or `items` or indeed anything will raise `StopIteration` if the dict was empty. Either catch the exception, or use `if dict else None` or some equivalent

**Comment by mvdbeek** [comment]
This is supposed to replace `d.items()[0]`, which would also raise a KeyError if empty, so that seems OK as a replacement.

**Comment by nsoranzo** [comment]
> This is supposed to replace d.items()[0], which would also raise a KeyError if empty, so that seems OK as a replacement.

Indeed, the only difference is that the old code would raise an `IndexError` exception.

**Comment by nsoranzo** [comment]
With a small patch to `nosehtml` I was able to run the Galaxy unit tests on Python 3.4 for the first time:
```console
$ tox -e py34-unit
...
Ran 871 tests in 83.274s

FAILED (SKIP=2, errors=226, failures=48)
```

So 68.5% are already passing, not bad I'd say.

**Comment by bgruening** [comment]
Amazing @nsoranzo!

**Comment by wm75** [comment]
pysam 14, and thus current Galaxy, is incompatible with Python3.7
see https://github.com/pysam-developers/pysam/issues/697

**Comment by wm75** [comment]
also, the Galaxy-installed virtualenv brings with it wheel version 0.24, which is too old to know about Python3.7 and rejects the 37 version tag as unsupported

**Comment by nsoranzo** [comment]
@wm75 Both issues have been fixed in #7008 for the dev branch, thanks for reporting!

**Comment by wm75** [comment]
I've seen it, thanks a lot! Got my first Python3.7-powered Galaxy up and running just seconds ago :+1: :1st_place_medal:

**Comment by wm75** [comment]
Think I'll raise an issue over at pysam though that it would be great if they could provide a whl for 0.15.1 so that you don't have to have devel libs installed to build it yourself.

**Comment by natefoo** [comment]
Should we open individual issues for Python 3 bugs? I got this when attempting to install a tool from the TS:

```pytb
Traceback (most recent call last):
  File "lib/galaxy/web/framework/middleware/error.py", line 154, in __call__
    app_iter = self.application(environ, sr_checker)
  File "/home/nate/work/galaxy2/.venv/lib/python3.5/site-packages/paste/recursive.py", line 85, in __call__
    return self.application(environ, start_response)
  File "/home/nate/work/galaxy2/.venv/lib/python3.5/site-packages/paste/httpexceptions.py", line 640, in __call__
    return self.application(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 143, in __call__
    return self.handle_request(environ, start_response)
  File "lib/galaxy/web/framework/base.py", line 222, in handle_request
    body = method(trans, **kwargs)
  File "lib/galaxy/web/framework/decorators.py", line 101, in decorator
    return func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/controllers/admin_toolshed.py", line 892, in prepare_for_install
    repo_information_dict = json.loads(raw_text)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by martenson** [comment]
I think so, maybe even with own github label.

**Comment by natefoo** [comment]
Moved the bug to #7769.

**Comment by nsoranzo** [comment]
We are now using the [area/python3](https://github.com/galaxyproject/galaxy/labels/area%2Fpython3) label to tag Python3-related issues/PRs instead of cross-referencing this issue.

**Comment by jdavcs** [comment]
Edit to "Useful tools and documentation": six has moved here: https://six.readthedocs.io/

**Comment by stain** [comment]
If I am making a new library for potential future use by Galaxy (say for exporting workspace as [RO-Crate](https://w3id.org/ro/crate)) - am I OK to do this in Python 3 or do I need to make it backwards compatible to Python 2?  From the progress in here it sound like I can dare to be modern..! :)

**Comment by mvdbeek** [comment]
IMO go for python 3. We will have a [deprecation notice](https://github.com/galaxyproject/galaxy/blob/dev/doc/source/releases/19.09_announce.rst#python) in the upcoming release and 19.09 should be the last release that officially supports python 2.

**Comment by martenson** [comment]
Congrats @nsoranzo, this is an accomplishment spearheaded by you that many people will benefit from. Thank you!

**Comment by bgruening** [comment]
Indeed, what a huge effort. I remember when this was started at GCC in Norwich and then later at ISMB in Dublin.

Thanks a lot, @nsoranzo and everyone involved!
