### ISSUE TITLE
Select inputs: select all / none

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#17151]
**Describe the bug**

I remember that in the past select inputs (that allow multiple selections) had a little checkbox to select all / none options. This was quite handy but seems to be gone unfortunately.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: not sure since when this is gone (or if I remember correctly)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Comment by ElectronicBlueberry** [comment]
Is this covered by  #17059?
It will be part of the next release (23.2)

**Comment by bernt-matthias** [comment]
> Is this covered by #17059?

Not to my understanding. I always assumed that the referred PR add a new possibility for selects that can be used for instance in the admin interface. But selects in the tool form stay as they are. But I might very well be wrong.

**Comment by ElectronicBlueberry** [comment]
It adds an option to switch to a different select interface, anywhere where multiple selections can be made, also in the tool from.
This select interface can be switched to / from at will, or set as a default. If there are many select options available, it is switched to by default.

**Comment by bernt-matthias** [comment]
How can a user switch to this new select. Just fired up a planemo serve with 23.2. and could not figure out how to switch (just had  a single select with a few options).

**Comment by ElectronicBlueberry** [comment]
It is only available on selects which allow for selecting more than one item at a time. An option named "switch to column select" should appear  under the select.

**Comment by bernt-matthias** [comment]
> An option named "switch to column select" should appear under the select.

Indeed. Looks really cool and useful.
