### ISSUE TITLE
Drop-down selectors get cut off in modals

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#17163]
**Describe the bug**
There seems to be an issue with CSS and modals using selectors.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.2
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Open any modal dialog with dropdown selectors (like the Upload tool)
2. Try to select something in the drop-down
3. Observe the issue

**Expected behavior**
The drop-down panel should be entirely visible.

**Screenshots**
![image](https://github.com/galaxyproject/galaxy/assets/46503462/286620f3-714d-44ea-aaaa-bd283f305744)

**Additional context**

**Comment by mvdbeek** [comment]
This is actually pretty bad, it would be good to prioritize a fix here
