### ISSUE TITLE
[papercut] input dataset collections don't use thick noodles

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#17162]
output collections from tools are thick 
![image](https://github.com/galaxyproject/galaxy/assets/458683/8aa0bbaa-fd0d-4500-9f59-af08beab804b)

while input DCs are thin
![image](https://github.com/galaxyproject/galaxy/assets/458683/71f8194a-d82a-4e0e-b133-61c87bbf33a1)

**Comment by mvdbeek** [comment]
That's not how it works, it indicates whether or not there is mapping over.
