### ISSUE TITLE
Eliminate or Replace SVGFig

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1717]
xref #1715

**Comment by dannon** [comment]
I looked into alternatives to this a while back and the most promising (if we still want to ship svg) was svgwrite.  py3 compatible, mit licensed.  I'll swap this out since I've tinkered with it in the past.

**Comment by dannon** [comment]
WIP in #1747

**Comment by nsoranzo** [comment]
Fixed in #1747.
