### ISSUE TITLE
[feature request] Allow searching for collections in a history

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#17172]
Usecase: I've hidden my collection because it was an intermediate, now I want that collection, but I can't find it amongst the 1000 other datasets all named 'featureCounts'.

Implementation: `shape:[datatset,list,list:paired]` could be one option, or @ahmedhamidawan's suggestion of "maybe it could be a useful filter? like a toggle between: All items | Datasets | Collections"

Either of these would be great, just seeing any type of collection would already be useful.

while I regularly abuse the fact that collection members are just hidden datasets, perhaps they need to be a different flavour of hidden datasets because as soon as you want to see hidden datasets in a history with large collections, it's immediately cluttered.

**Comment by wm75** [comment]
I think an old attribute for this was `history_content_type`, but it doesn't seem to work anymore?

**Comment by hexylena** [comment]
`history_content_type` is still mentioned in the popover https://github.com/galaxyproject/galaxy/blob/1fb09864a8117d92bafff38b80455723ffd82935/client/src/ui/search-input.js#L135  :thinking:

I've tried with `hdca` and `dataset_collection` but neither seem to return results.
