### ISSUE TITLE
Improve "Collection Type" selection in workflow UI

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#1719]
When adding/modifying an "Input dataset collection", "Collection Type" on the right panel is a text field on Firefox.

![screenshot from 2016-02-12 16 28 24](https://cloud.githubusercontent.com/assets/4924623/13013104/eb8ba548-d1a5-11e5-9a48-9db0502cb808.png)

Can we help the user with a multiple choice select (`list`, `paired`, `list:paired`, `other`)? Or at least add some help? The only problem may be the fact that potentially a user may want to use a `list:list` or `list:list:paired` or something even crazier.

Ping @jmchilton for suggestions.

**Comment by martenson** [comment]
The type selection being discrete (with `other` as possible value that would show additional text field)  
:+1:

**Comment by jmchilton** [comment]
The dropbox appears on mouseover - but there should be some help text for sure in here at least.

**Comment by dannon** [comment]
The arrow on hover/select:
![capture](https://cloud.githubusercontent.com/assets/155398/17179382/01529b48-53e7-11e6-94fa-96f8072f3688.PNG)

The dropdown:
![capture2](https://cloud.githubusercontent.com/assets/155398/17179402/19941d94-53e7-11e6-98ca-505e47d05966.PNG)

This actually seems pretty good to me as-is, though tooltips should be on everything.

**Comment by nsoranzo** [comment]
@dannon: you on Chrome? The issue is in Firefox.

**Comment by dannon** [comment]
@nsoranzo Whoops.  In the hangout it was stated that the bug was in chrome, not FF.  In firefox I'm seeing options as soon as I start typing though.

Either way, this is kinda silly, right?  Should it not just be a dropdown with pre-set options?

**Comment by blankenberg** [comment]
We would need preset options (which are the current datalist options) and also freeform entry (there are more possibilities than the 'standard' 3). 

One current issue is that even with Chrome, by default you don't see the option of `paired`, since the default is `list` and the options are filtered by starting with that.

**Comment by dannon** [comment]
@blankenberg Hadn't noticed it was filtering on chrome, good catch.  So we need to support someone entering `list:list:pair` or something, I get it.  Sticking w/ free-form entry with better tooltip/help text sounds like a good step then.

**Comment by martenson** [comment]
> We would need preset options (which are the current datalist options) and also freeform entry (there are more possibilities than the 'standard' 3).

this is often solved using a select element listing the common choices but which also has `specify` option that would add a textfield element underneath for the freeform entry
