### ISSUE TITLE
Bug with workflows using tools with default values.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1721]
```
20:55 < bwlang> I think https://github.com/galaxyproject/galaxy/pull/1302 is messing 
                things up for workflows containing tools with default values (e.g. 
                seqprep).
20:55 < mrscribe> Title: Improved validation of tools during workflow execution. by 
                  jmchilton · Pull Request #1302 · galaxyproject/galaxy · GitHub (at 
                  github.com)
20:56 < bwlang> I just changed 
https://github.com/galaxyproject/galaxy/blob/release_16.01/lib/galaxy/tools/__init__.py#L1729 adding “and not value is None”, and my workflows can now run.
20:56 < mrscribe> Title: galaxy/__init__.py at release_16.01 · galaxyproject/galaxy · 
                  GitHub (at github.com)
20:56 < bwlang> but I think i’m papering this over.
20:59 < bwlang> Is there a good way to do default expansion so we can get the benefit of 
                validation ?
```

**Comment by jmchilton** [comment]
I forked 16.01 and added a basic test tool that has optional int and float parameters with defaults https://github.com/jmchilton/galaxy/tree/optional_workflow_params.

I can then startup Galaxy with these tools and create a workflow with this tool.

```
GALAXY_RUN_WITH_TEST_TOOLS=1 sh run.sh --reload
```

It seems to run and parameters seem to work fine.

@bwlang can you checkout my branch and modify the tool to exhibit the behavior you are describing?

**Comment by gregvonkuster** [comment]
@jmchilton From what I've seen, I believe you can reproduce this if you have a tool with an optional parameter and the value of the parameter is empty.  I'm pretty sure I've bumped into this behavior using this tool in a workflow: 
https://github.com/galaxyproject/tools-devteam/blob/master/tools/bwa/bwa-mem.xml
which has an optional text parameter (iset_stats) that I am leaving empty.  The bwa-mem tool will execute correctly, but the workflow will end there - the next tool in the workflow will not execute.

**Comment by bwlang** [comment]
Hi john ... Sure ,  but it may take me a few days.

**Comment by bgruening** [comment]
@jmchilton Maybe more informations here: https://github.com/galaxyproject/tools-iuc/issues/603

**Comment by glormph** [comment]
Found this behaviour as well, exactly as @gregvonkuster describes. I ONLY see this behaviour with float params, not integers. Also, if the workflow contains a step with a discover_dataset collection output just before the problematic tool, the problem disappears.

**Comment by glormph** [comment]
I can confirm that the patch (below) from @guerler referenced in galaxyproject/tools#603 does the trick also for this issue.

https://github.com/galaxyproject/galaxy/compare/release_16.01...guerler:fix_check_and_update_release_000?expand=1
