### ISSUE TITLE
Unable to update tool on testtoolshed

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#17214]
**Describe the bug**
I tried to update a tool on the testtoolshed and I got a Unexpected HTTP status code: 500: Internal Server Error

**Galaxy Version and/or server at which you observed the bug**
https://testtoolshed.g2.bx.psu.edu/api/version
{"version_major":"23.3","version":"23.3.dev0","api_version":"v2"}

**To Reproduce**
Copy directory content from https://github.com/lldelisle/tools-lldelisle/tree/4ac9b1d66ba6857357867c8eccb6c9d1ad603364/tools/incucyte_stack_and_upload_omero
Using planemo, version 0.75.19
I do:
```bash
$ planemo shed_update --shed_target testtoolshed --shed_key xxx  --force_repository_creation
cd '/home/ldelisle/Documents/mygit/tools-lldelisle/tools/incucyte_stack_and_upload_omero' && git rev-parse HEAD
galaxy.util.commands WARNING: Passing program arguments as a string may be a security hazard if combined with untrusted input
git diff --quiet
Could not update incucyte_stack_and_upload_omero
Unexpected HTTP status code: 500: Internal Server Error
Unexpected HTTP status code: 404: <html>
 <head>
  <title>404 Not Found</title>
 </head>
 <body>
  <h1>404 Not Found</h1>
  The resource could not be found.<br /><br />
No route for /api/repositories/2ac1194a2eb9fece


 </body>
</html>
Failed to update repository contents and metadata for repository 'incucyte_stack_and_upload_omero' on the test Tool Shed.
```
What is super strange is that when I go to the web interface. It seems to have detected a change:
![image](https://github.com/galaxyproject/galaxy/assets/30404086/ca0d4d15-a5aa-4d88-822c-9306df0bd199)
But if I go to the changelog I see the last update is 3 months ago:
https://testtoolshed.g2.bx.psu.edu/repos/lldelisle/incucyte_stack_and_upload_omero/shortlog

**Expected behavior**
I was expecting my tool to be updated.

**Additional context**
Finally, I put this tool on the main toolshed and it worked.

**Comment by mvdbeek** [comment]
What's missing is the PUT route to update repository metadata, `PUT /api/repositories/{encoded_repository_id}`. I was able to create new changeset revisions and upload new files, so I think 

> But if I go to the changelog I see the last update is 3 months ago:

might have been a temporary deployment issue with hgweb.
FWIW the call in planemo is https://github.com/galaxyproject/planemo/blob/master/planemo/shed/__init__.py#L679

**Comment by mvdbeek** [comment]
It's working now, thanks @lldelisle!
