### ISSUE TITLE
Dataset not visible in a user's history (compressed/uncompressed, same hid)

### ISSUE THREAD

**Issue by mira-miracoli** [galaxyproject/galaxy#17220]
**Describe the bug**
We got a support request from a user, that ran out of storage and can not delete 2 large datasets, because they are not shown in the history (independent of the filter combinations).
In the storage manager, the datasets are listed and you can also find them in `User→Datasets`, but when you then click on `view in history` the datasets will not appear (filters: `deleted:any visible:any hid:61`).
However, what appears is the compressed version, which has the same hid.
When I looked the datasets up in our database using 
~~~
gxadmin query q "select dataset_id, d.uuid, name, hid, visible, d.deleted, d.purged, d.file_size  \
from history_dataset_association inner join dataset d on dataset_id = d.id where history_id = xxxxx and d.purged = 'f'"
~~~
The datasets showed up as follows:
~~~
dataset_id |                                name                                | hid | visible | deleted | purged |  file_size        
------------+--------------------------------------------------------------------+-----+---------+---------+--------+--------------
...
  xxxxxxx55 | Concatenate datasets on data 53, data 57, and data 55 uncompressed |  61 | f       | f       | f      | 166396579020
  xxxxxxx58 | Concatenate datasets on data 63, data 65, and data 64 uncompressed |  66 | f       | f       | f      | 166396579020
~~~
**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1_europe
Commit:  5af8ba0f4c2df9f1fdac11acc3f282023322690c

**To Reproduce**
Not sure how
The user reported that two jobs were running and only one finished and the other one was paused due to using ~200% of disk quota.
Galaxy shows the following message in the paused job:
~~~
Execution of this dataset's job is paused because you were over your disk quota at the time it was ready to run
~~~

**Expected behavior**
Dataset shown in the history and can be deleted and purged;
the compressed and the uncompressed version is visible and the uncompressed version can be deleted.
**Screenshots**

![Screenshot from 2023-12-20 09-06-26-censored](https://github.com/galaxyproject/galaxy/assets/86979912/0360e156-01d2-4ad9-bba5-ab487d8d1094)
![Screenshot from 2023-12-20 09-05-27-censored](https://github.com/galaxyproject/galaxy/assets/86979912/d4a55791-ec0f-4309-8b61-a4dd663fa195)
![Screenshot from 2023-12-20 16-18-21](https://github.com/galaxyproject/galaxy/assets/86979912/a5b8887f-7864-44d5-a846-c377fb150357)

![Screenshot from 2023-12-20 16-18-39](https://github.com/galaxyproject/galaxy/assets/86979912/51d47fb9-03b7-4a13-9c40-1065056be48c)

**Comment by mvdbeek** [comment]
@ahmedhamidawan I think you fixed this in https://github.com/galaxyproject/galaxy/pull/17648/commits/84b627260f7d6cff19262543be8723921abf2b4a

**Comment by ahmedhamidawan** [comment]
> @ahmedhamidawan I think you fixed this in https://github.com/galaxyproject/galaxy/pull/17648/commits/84b627260f7d6cff19262543be8723921abf2b4a

Yes @mvdbeek , thank you!

**Comment by mvdbeek** [comment]
Hmm, guess that wasn't all of it, here's a history with duplicate hids from an implicit conversion:
https://usegalaxy.org/u/marius/h/copy-of-human22chrsnps

Compare UI:
<img width="370" alt="Screenshot 2024-08-02 at 19 22 13" src="https://github.com/user-attachments/assets/1a914f06-e6b9-4914-90af-15e7d9bb4af1">

with API https://usegalaxy.org/api/histories/c845ae1a2747ea06/contents

**Comment by ahmedhamidawan** [comment]
> Hmm, guess that wasn't all of it, here's a history with duplicate hids from an implicit conversion: https://usegalaxy.org/u/marius/h/copy-of-human22chrsnps

For that history for e.g., I was able to come up with a solution where we add a `item.sub_items` property to items in the `historyItemsStore`, which allows us to do something like this:

https://github.com/user-attachments/assets/7c3f9d8f-8e4c-4f7c-ac09-851bdc9ff388

I will open a PR tomorrow for this

**Comment by mvdbeek** [comment]
This looks cool, but the original dataset is the one you'd want to see

**Comment by martenson** [comment]
How does it show in the toolform dataset input?

**Comment by ahmedhamidawan** [comment]
> How does it show in the toolform dataset input?

Oh that would show the "original" dataset, which is set based on what the api returns for the current filter...

**Comment by mira-miracoli** [comment]
Thank you for fixing this @ahmedhamidawan ❤️
