### ISSUE TITLE
user.current_galaxy_session points to the oldest session

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17229]
this bug is visible in the "Last Login" column of the `/admin/users` menu

| 23.0 | 23.2 |
| - | - |
| ![Screenshot 2023-12-22 at 11 38 44 AM](https://github.com/galaxyproject/galaxy/assets/1814954/7d57bf77-0f49-422b-a590-80473039a4d3) | ![Screenshot 2023-12-22 at 11 44 55 AM](https://github.com/galaxyproject/galaxy/assets/1814954/5af5a778-a91c-4535-8193-c50c8f22720b) |

sessions in db for the highlighted user ordered by update time:

```
"2023-12-22 18:34:46.590188" <-- 1 hour ago
"2023-12-22 18:33:50.654605"
"2023-12-22 18:33:50.6546"
"2023-12-22 18:33:50.654593"
"2023-06-23 20:15:26.954217"
"2023-06-23 20:15:26.954204"
"2023-03-10 19:08:28.19145"
"2023-02-27 21:33:25.473806"
"2023-02-27 21:33:25.473799"
"2022-12-14 17:30:00.973089"
"2022-12-14 17:30:00.973085"
"2022-12-14 17:30:00.973079"
```

code relevant to the grid above here: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/controllers/admin.py#L65

possibly related to https://github.com/galaxyproject/galaxy/pull/16604

**Comment by mvdbeek** [comment]
Fixed in #17232
