### ISSUE TITLE
BED files load into Trackster with error at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1722]
**Problem** 

Any BED dataset fails to load. There is a specific error.

**Error**

> Traceback (most recent call last):
>   File "/galaxy-repl/instances/main/server/lib/galaxy/datatypes/converters/interval_to_tabix_converter.py", line 40, in 
>     main()
>   File "/galaxy-repl/instances/main/server/lib/galaxy/datatypes/converters/interval_to_tabix_converter.py", line 30, in main
>     already_compressed=True, index_filename=out_fname)
>   File "pysam/ctabix.pyx", line 738, in pysam.ctabix.tabix_index (pysam/ctabix.c:8259)
> TypeError: tabix_index() got an unexpected keyword argument 'index_filename'

@dannon was looking at it last. Because has been over a day and retesting did not show it was fixed, creating a ticket for users to track. 

Once corrected, please ping for retest.

**Comment by dannon** [comment]
@jennaj It requires a main update to fix (which I have been told is happening soon)

**Comment by jennaj** [comment]
thanks @dannon - I just tested and is still a problem. I'll watch for the main update :)

**Comment by dannon** [comment]
@jennaj This is fixed now, right?

**Comment by jennaj** [comment]
Thanks and I will retest now.

**Comment by jennaj** [comment]
@dannon Bed loading into trackster on Main still produces the same error.
<img width="646" alt="screen shot 2016-03-08 at 2 22 32 pm" src="https://cloud.githubusercontent.com/assets/8999735/13618503/547f4018-e539-11e5-9f5b-b01b69581135.png">

**Comment by dannon** [comment]
@jennaj Thanks, someone else confirmed as well.  I'm working on a new pysam update that'll resolve it.

**Comment by dannon** [comment]
Decided to fix it without updating pysam with https://github.com/galaxyproject/galaxy/pull/1897

**Comment by jennaj** [comment]
@dannon thanks, once the pull is accepted and active on Test/Main, I'll test again.

**Comment by martenson** [comment]
@jennaj please test

**Comment by jennaj** [comment]
@martenson Thanks!

BED datasets are loaded (although slowly, even for smaller datasets). Data for both dm3 + hg19 tested.

Same data, same genomes, in GTF format does not load (fails immediately for missing dependency). See #3499

**Comment by martenson** [comment]
@jennaj thanks for testing, closing this issue and we continue in #3499
