### ISSUE TITLE
Low resolution workflow connectors are visually unpleasant

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1725]
![selection_631](https://cloud.githubusercontent.com/assets/458683/13028981/44221bc6-d244-11e5-8032-2c5c1b3ab63c.png)

If there's any way we could have higher res connectors that'd be great.

**Comment by jxtx** [comment]
For canvas rendering on hidpi displays this should do the trick: https://github.com/jondavidjohn/hidpi-canvas-polyfill

For the terminals, I'd suggest we render them with a canvas on the client and stop using images.
