### ISSUE TITLE
Release Notes Link on Fresh Galaxy install broken

### ISSUE THREAD

**Issue by jgoecks** [galaxyproject/galaxy#17256]
**Describe the bug**
I downloaded and started Galaxy. In the Web UI, I clicked on Release Notes and got this error: ```NoSuchKeyThe specified key does not exist.en/latest/releases/23.3_announce_user.htmlTJQM14HRJC7V14AHN2XuVZXENZUO5mbAIhV+EUH7IDIIEmlpl7snAoFhf378GkuSBy2DuU+/qcva92WmLbw+60vJxeU=```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: version_major: "23.3", version_minor: "dev0"
Commit: 4e332164899bd21c5f0e3079f90de9c39719823d

**To Reproduce**
1. Go to main page and click on the "See Galaxy Release Notes" link

**Screenshots**

![Screenshot 2024-01-09 at 10 28 05 AM](https://github.com/galaxyproject/galaxy/assets/882193/799299b7-5bf5-44cd-be90-90b00444a743)

**Comment by martenson** [comment]
I am not sure this is a bug. When running a pre-release version the notes will not be found because they don't exist yet. This has always been the case afaik.

We could put in some work around though, if deemed worth it.

**Comment by martenson** [comment]
the button and its functionality has been replaced by admin notifications in 24.0 https://github.com/galaxyproject/galaxy/pull/17675
