### ISSUE TITLE
`discover_datasets` broken if the tool has other outputs

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#17263]
**Describe the bug**

I experimented a bit with https://github.com/galaxyproject/tools-iuc/issues/5702 and can reproduce it. I extended one of out functional test tools to have another output. I inserted the other output before and after, resp., the discovered output. 

1. If the other input is before the discovered output (in tool xml) then `assign_primary_output` breaks. 
2. If the output is after the discovered output: 
  a. the other output and the primary output of the discovered output remain in running state (which reproduces https://github.com/galaxyproject/galaxy/issues/16203)
  b. the name of the other output (dataset 8) is overwritten  with info from the discovered output

https://github.com/galaxyproject/galaxy/assets/25689525/9305f175-c585-4d71-b1c4-28706bf33a07

I guess the check for `output_index == 0` [here](https://github.com/galaxyproject/galaxy/blob/b173bd4bf9f0e35317dcc591a5c9ab9c6a026069/lib/galaxy/job_execution/output_collect.py#L507) is wrong and may be the reason for case 1.

Edit: if this check is removed: in case 1 the `assign_primary_output` works, but then the primary remains in state yellow.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: dev (video is recored on dev) .. but I guess it involves also earlier releases
Commit: 4e33216489

**Expected behavior**

- Primary dataset is filled (and no extra dataset is created)
- Datasets are shown as finished
- In case 2 other is not overwritten.

**Screenshots**

**Additional context**

Added the test cases here https://github.com/bernt-matthias/galaxy/tree/topic/assign_primary

**Comment by TomHarrop** [comment]
Thank you for working on this!
