### ISSUE TITLE
Can't unhide multiple datasets in UI

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#17267]
I am currently showing hidden datasets, it should be possible to unhide them via the batch selector interface.

<img width="451" alt="Screenshot 2024-01-11 at 10 56 33" src="https://github.com/galaxyproject/galaxy/assets/6804901/a7737e4f-be45-4ef5-b1a1-deb7be8149e0">

**Comment by davelopez** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/17433
