### ISSUE TITLE
Collapse panel button prevents getting normal scroll handler

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#17277]
I can't grab the small scroll handler. I think that's a side effect of https://github.com/galaxyproject/galaxy/pull/17113

<img width="781" alt="Screenshot 2024-01-12 at 15 34 33" src="https://github.com/galaxyproject/galaxy/assets/6804901/871f4539-0150-4cf4-8aa6-fde6ef854489">

I guess I can get used to it, but I think the collapse button is much too large and I think is generally in the way. I would love to be able to turn this off.

**Comment by ElectronicBlueberry** [comment]
Regarding the collapse button being in the way, just to clarify, is the collapse button always showing for you? It's only supposed to show after hovering the edge for a bit.

**Comment by itisAliRH** [comment]
@ElectronicBlueberry I also see it. The scrollers are thin and are not easy to grab on the first attempt:
Chrome
![image](https://github.com/galaxyproject/galaxy/assets/8046843/0c02b162-39c8-4bd2-8d2b-065aa5dedaa1)
Firefox
![image](https://github.com/galaxyproject/galaxy/assets/8046843/c711f98a-fde8-4c4c-aeac-85007c2c6a42)

**Comment by mvdbeek** [comment]
> It's only supposed to show after hovering the edge for a bit.

Yeah, it does that, but it comes up too quickly when doing other things. It's a minor issue though compared to not being able to grab the scroll bar.
