### ISSUE TITLE
Workflow overview / organization

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#1728]
I have a whole lot of workflows, and finding the right one is a challenge at times.
It would be nice if I could sort my workflows according to tags in the workflow overview page,
or to have workflows organizable in folders.
It's kind-of a duplicate of @scholtalbers suggestion on [trello](https://trello.com/c/AJrd2vuM/2553-idea-improve-workflow-page-allow-to-categorize-workflows).

**Comment by hexylena** [comment]
@mvdbeek maybe part of https://github.com/galaxyproject/galaxy/issues/1161

**Comment by mvdbeek** [comment]
Absolutely. Can you add the folder/tag idea to #1161 ?

**Comment by hexylena** [comment]
@mvdbeek sure thing! Done

**Comment by mvdbeek** [comment]
thanks!
