### ISSUE TITLE
Do not reset parameters when re-running tool with different version

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#1729]
Switching the version in the UI currently resets all parameters.
For tools with a lot of parameters this can be quite painful.

**Comment by blankenberg** [comment]
+1 
Very hard to rerun old analysis using new tool versions now.

**Comment by martenson** [comment]
The fix did not make it to 17.05 yet and this issue is not blocking. Deferring to 17.09.

**Comment by mvdbeek** [comment]
This is implemented now, so I'm closing this.
