### ISSUE TITLE
Updated Multi-select: odd dataset order, on tool forms and history output

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#17320]
**Describe the bug**
When using the multi-select on tool forms, input datasets added to the field are always in the reverse order of the dataset numbering. This was previously smaller > larger dataset number. Some users noticed this. Could we order that way again?

Then, the output order seem to be: _the second highest number_ to the smallest number, followed by the highest number (!!)

Yes, using a collection would solve this. But wondering if sorting small > large for both form and outputs is possible just for UI niceness, plus consistency with earlier Galaxy releases.

**Galaxy Version and/or server at which you observed the bug**
UseGalaxy.org, Galaxy Version Information
The Galaxy Server is running version [23.2.rc1 ](https://docs.galaxyproject.org/en/release_23.2/releases/23.2_announce_user.html), and the web client was built on Wednesday Jan 17th 6:13:41 2024 GMT-8 .

**To Reproduce**
1. test history: https://usegalaxy.org/u/jen-galaxyproject/h/multi-select-reverse-ordering-example
2. pick a tool and add the history datasets one at a time and you'll notice it. Higher numbered datasets are sorted to the front of the listing 
3. submit the job to see the output ordering

**Expected behavior**
Smallest > largest dataset number on both the select box and history outputs. Why? This is how it was originally.

**Screenshots**

Input select:

![Screen Shot 2024-01-17 at 12 03 17 PM](https://github.com/galaxyproject/galaxy/assets/8999735/2b28e54f-2982-4c61-bc8e-f7ee4a66cc92)

Outputs this:

![Screen Shot 2024-01-17 at 12 07 53 PM](https://github.com/galaxyproject/galaxy/assets/8999735/ef82edaf-f72e-4281-a144-e3381ab6223e)

**Additional context**
If someone already reported, please consolidate or merge :) Also, wasn't sure how to tag. Thanks!

**Comment by ElectronicBlueberry** [comment]
These seem like two issues. I think the output ordering is determined on the back-end.

**Comment by mvdbeek** [comment]
> Smallest > largest dataset number on both the select box and history outputs. Why? This is how it was originally.

I don't think that's how it was ? You wouldn't ever want to see the start of the history

**Comment by mvdbeek** [comment]
Oh, the order of the selected datasets, yes, that needs to be the order within which they were selected.

> I think the output ordering is determined on the back-end.

To clarify, I think what @jennaj meant is that if you say, concatenate datasets, the resulting output is not in the order you would expect. This hasn't changed, so I'm removing the backend label.

**Comment by martenson** [comment]
The release-blocking part here is that the selected multi-inputs (with vue-multiselect) are sent to backend in a different order compared to 23.1 (that used basic html form input or select2 -- depending on number of options).

This breaks reproducibility for any tool that relies on the order of inputs (e.g. concatenate multiple files) including reruns.

(While testing note that vue multiselect aditionally tracks the order in which the options are selected by the user -- this is an unwanted behavior as I see it for our use of this input element.)

In 23.1 we ensure that the inputs are ordered by `hid` in an ascending order (1 -> 2 -> 3 etc.). This was done [here](https://github.com/galaxyproject/galaxy/blob/release_23.1/client/src/mvc/ui/ui-select-default.js#L403) and also [here](https://github.com/galaxyproject/galaxy/blob/release_23.1/client/src/mvc/ui/ui-select-content.js#L250)

(Note the available options in the input are always presented in a descending order showing the highest hid first -- so it looks like the history I guess)

In 23.2 I believe we should be doing the same reordering. Likely somewhere around [here](https://github.com/galaxyproject/galaxy/blob/release_23.2/client/src/components/Form/Elements/FormData/FormData.vue#L255). 

I wasn't able to quickly fix this today without setting off a loop of reactive side effects hence tracking the progress here in hope that @guerler, @davelopez, or someone else can have a look.

**Comment by martenson** [comment]
We have fixed the order of inputs sent to API to reflect the previous implementation -- which is "sorted by hid in ascending order".

The actual options were previously shown sorted by hid in descending order. This was the same both in the native form input and select2 form input (shown for >100 options available). This has not changed in 23.2 and switch to vue-multiselect. 

I believe these two were the reported problems in this issue, please reopen or create a new one if I missed something.
