### ISSUE TITLE
News button on top of Galaxy page

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/galaxy#17354]
The current icon for 'Release Notes' on the top of the GUI is the universal 'News' symbol, so I think the 'release notes' should instead be linked under the HELP | ABOUT section, and the megaphone/news button at the top of the GUI should instead pop out to the galaxy NEWS widget

**Comment by martenson** [comment]
afaik release notes are in the masthead because we want to increase their visibility which we wouldn't achieve in help/about. What is galaxy news widget?

**Comment by nomadscientist** [comment]
Less a widget and more just this: https://galaxyproject.org/news/

**Comment by nomadscientist** [comment]
Why do we need to increase visibility of release notes? That's not something Users are particularly interested in, so it's taking up valuable real estate on the main screen.

**Comment by hexylena** [comment]
> Why do we need to increase visibility of release notes? That's not something Users are particularly interested in, so it's taking up valuable real estate on the main screen.

I added this feature, because galaxy changes regularly and users weren't being informed of new features in Galaxy. We have a separate class of release notes specifically for users which focuses on features they're likely to be interested in. In the upcoming release they'll be informed of the new workflow comments.

Otherwise, how should a user find out they're on a new version of Galaxy? Admins need to manually make a blog post (many don't). And how should they find out what new features are available to them?

Why do you feel users aren't interested in the latest galaxy features available on their instance?

**Comment by nomadscientist** [comment]
Interesting, and I see your point! Tbh, it never occurred to me to check that, as 'release notes' seemed like quite a computational thing not meant for me. Now it makes a lot more sense why it has the news icon. Maybe relabelling the pop-up text something like 'What's new in Galaxy' might help?

And the great question of where to post the news posts remains, but doesn't need solving by this.

**Comment by nomadscientist** [comment]
Oh but also - the thing users see whenever they run a tool, like the bee-sexing activity? That would be a nice place to show off new features. It's a constant topic of convo in training courses and in my group meetings

**Comment by hexylena** [comment]
I think that's a great re-labeling, that's definitely more clear than the technical language of 'release note'.

And I guess it will soon be moved to a more obvious location (maybe) of the user's "notifications", so hopefully it'll be more obvious then too.

I think that might *also* solve your issue of where to put news, we would then have a couple of data sources we want to push to users through their notifications:

- site notices (downtime)
- releases (this has to be specific to that galaxy, not sure how that will be solved in a nice way)
- public galaxy news (should this be opt-in? out?)

and it can all be in one place for a user.

**Comment by martenson** [comment]
the button and its functionality has been replaced by admin notifications in 24.0 https://github.com/galaxyproject/galaxy/pull/17675

**Comment by martenson** [comment]
@hexylena @nomadscientist I am not sure if you are proposing modifications to the notification framework or new menu items, if so would you please mind opening a new issue?
