### ISSUE TITLE
[Feature Request] workflow tag from input variables?

### ISSUE THREAD

**Issue by alpapan** [galaxyproject/galaxy#17369]
Would it be logical to allow the #{input} variable notation to be processed by the tag assigner in workflows?
Noting the complexity that # is used for tags that propagate

For example: 

run bwa vs reference1 -> tag "#_vs_reference1" -> lots more processing -> final CRAM file has tag "_vs_reference1"

(obviously in this very specific case, the reference1 is stored as Database but the point remains, for example could be to store a setting that is propagated downstream)

**Comment by mvdbeek** [comment]
There are no plans to add this, tracking identifiers is supposed to happen through collection element identifiers.

**Comment by alpapan** [comment]
Thanks for first phrase, second one is just patronising and dismissive.

Here is what I understood: "There are no plans to allow tags to be added dynamically during a workflow. Something something that doesn't address question."

**Comment by mvdbeek** [comment]
I'm sorry for that, my intention is to give you a reason for why there are no plans to implement this.

**Comment by alpapan** [comment]
I didn't get the reason...
