### ISSUE TITLE
<autoconf> question

### ISSUE THREAD

**Issue by methylome** [galaxyproject/galaxy#1736]
Hello,

The following installs into a system directory /usr/local/ncbi.

```
<action type="autoconf">--with-ngs-sdk-prefix=$NGS_SDK_DIR --build=$INSTALL_DIR</action>
```

But the following installs into the package directory.

```
<action type="autoconf">--prefix=$INSTALL_DIR --with-ngs-sdk-prefix=$NGS_SDK_DIR --with-xml2-prefix=$LIBXML2_ROOT_DIR --build=$INSTALL_DIR</action>
```

Is this a bug to check "prefix", not "--prefix"?

Thanks,
Justin.

**Comment by bgruening** [comment]
Yes, if `prefix=` is included, you need to specify it on your own.

https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py#L452
