### ISSUE TITLE
`CondaTarget` misses `package_name` property

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#17378]
**Describe the bug**

https://github.com/galaxyproject/galaxy/pull/16181/files merged Target (which had `package_name`) into `CondaTarget` (which has `package`). `planemo` uses `package_name` and fails with `AttributeError: 'CondaTarget' object has no attribute 'package_name'` since the 23.1 is used. 

xref https://github.com/galaxyproject/planemo-monitor/pull/46

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1

**Comment by nsoranzo** [comment]
I think it'd be fine to just update planemo to use the new syntax (I can do that), but let me know if you'd prefer to patch Galaxy instead.

**Comment by bernt-matthias** [comment]
I have no preference. Guess nothing except Galaxy itself and planemo use this anyway.
