### ISSUE TITLE
LDAP port not passed on

### ISSUE THREAD

**Issue by alpapan** [galaxyproject/galaxy#17374]
**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1.5.dev0
Commit: 1fe37b099f6f7da20c2483157bb2c1d94a766c67

**Describe the bug**

This took me an hour to fix so i'm documenting it in case it is useful.

When we want to have LDAP activated, the sample config file does not specify a port but it should because the default is not actually passed on.

See `auth_conf.xml.sample`, currently:
```
<server>ldap://dc1.example.com</server>
```

If used like that, it doesn't work.

This is working and correct if port is default:
```
<server>ldap://dc1.example.com:389</server>
```

If i remember correctly, this was not needed last time i went through my galaxy admin journey.

However, from reading `lib/galaxy/auth/providers/ldap_ad.py` it seems that the default should be passed on.

```
# Get server address and port
        url_obj = urlparse(server_url)
        server_address = url_obj.hostname
        try:
            server_port = int(url_obj.port)
        except TypeError:
            # If port is not specified use standard port numbers based on TLS
            if self.ldap_tls:
                server_port = 636
            else:
                server_port = 389
```

It seems that urlparse() does not create a .port object or perhaps whatever it returns, the int() does not return typeerror.

i'm not a python programmer so not sure.

I recommend that the auth_conf.xml.sample include the port. Tiny change that will save the next admin quite a bit of time.

**Comment by bernt-matthias** [comment]
Can you post the complete auth_conf.xml? In particular which of the two ldap providers do you use? 

Are there any messages in the logs?

**Comment by alpapan** [comment]
Hello

For the life of me i can't replicate it by removing the port. So it is not the port.
It's possible because i don't have the original conf file but replicated from the saved log.

The original error from my notebook is below along with config.
The only thing i can think of is that 

`<search-memberof-filter>galaxy_users</search-memberof-filter>` was not setup properly for me due to https://github.com/galaxyproject/galaxy/issues/17375#issue-2104871799. 

but then again i made it to work before i fixed that... but it's 1am here...

it would be nice if the sample config had a fully working definition e.g 
from `<server>ldap://dc1.example.com</server>` to `<server>ldap://dc1.example.com:389</server>`

closing it until i can give you something useful, sorry


log error that didn't work
```

galaxy.auth.providers.ldap_ad DEBUG 2024-01-26 19:36:58,427 [pN:main.2,p:45487,tN:WSGI_2] LDAP authenticate: email is 30042108@westernsydney.edu.au
galaxy.auth.providers.ldap_ad DEBUG 2024-01-26 19:36:58,427 [pN:main.2,p:45487,tN:WSGI_2] LDAP authenticate: username is 30042108
galaxy.auth.providers.ldap_ad DEBUG 2024-01-26 19:36:58,427 [pN:main.2,p:45487,tN:WSGI_2] LDAP authenticate: options are {'allow-register': 'False', 'auto-register': 'False', 'max-retries': '0', 'allow-password-change': 'False', 'auto-create-roles': 'True', 'auto-create-groups': 'True', 'auto-assign-roles-to-groups-only': 'True', 'server': 'ldap.example.com.au', 'ldap-options': None, 'login-use-username': 'True', 'continue-on-failure': 'True', 'search-fields': 'uid,mail', 'search-base': 'dc=example,dc=com,dc=au', 'search-filter': '(|(uid={username})(mail={email}))', 'search-memberof-filter': 'galaxy_users', 'search-user': 'cn=admin,dc=example,dc=com,dc=au', 'search-password': 'secret', 'bind-user': '{dn}', 'bind-password': '{password}', 'auto-register-username': '{uid}', 'auto-register-email': '{mail}', 'auto-register-roles': '{gidNumber}', 'redact_username_in_logs': False}
galaxy.auth.providers.ldap_ad ERROR 2024-01-26 19:36:58,427 [pN:main.2,p:45487,tN:WSGI_2] LDAP authenticate: search exception
Traceback (most recent call last):
  File "/apps/others/galaxy/lib/galaxy/auth/providers/ldap_ad.py", line 173, in ldap_search
    conn = ldap.initialize(_get_subs(options, "server", params))
  File "/apps/others/galaxy/.venv/lib/python3.8/site-packages/ldap/functions.py", line 91, in initialize
    return LDAPObject(
  File "/apps/others/galaxy/.venv/lib/python3.8/site-packages/ldap/ldapobject.py", line 88, in __init__
    self._l = ldap.functions._ldap_function_call(ldap._ldap_module_lock,_ldap.initialize,uri)
  File "/apps/others/galaxy/.venv/lib/python3.8/site-packages/ldap/functions.py", line 52, in _ldap_function_call
    result = func(*args,**kwargs)
ldap.LDAPError: (0, 'Error')
```
