### ISSUE TITLE
change_directory

### ISSUE THREAD

**Issue by methylome** [galaxyproject/galaxy#1737]
Hello,

The following doesn't work:

```
                <action type="change_directory">$INSTALL_DIR</action>
                <action type="make_install" />
```

But the following works:

```
                <action type="shell_command">
                    cd $INSTALL_DIR &amp;&amp; make &amp;&amp; make install
                </action>
```

Thanks,
Justin

**Comment by nsoranzo** [comment]
`change_directory` will not let you move outside of the temporary working directory, see:

https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py#L479
