### ISSUE TITLE
'x' button on multiselect pills is confusing when item cannot be removed.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#17377]
Observed on Galaxy 23.3dev0
in Firefox

![image](https://github.com/galaxyproject/galaxy/assets/458683/f53a56c6-9687-45ac-bb86-335439667509)

The x there does not function when there is only one element in the list, it only functions when I've selected multiple elements, to remove one.

**Comment by bernt-matthias** [comment]
seems related https://github.com/galaxyproject/galaxy/issues/17351

**Comment by hexylena** [comment]
No this is a duplicate of that, you're right, not just related. I clearly didn't know the internal terms for those so didn't manage to find it.
