### ISSUE TITLE
[Feature request] Freeze header row in tabular files

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#17380]
My colleague asked if it could be possible to freeze / lock the header row in tabular files (blue bar with HBOND in the screenshot below) so it always remains visible when scrolling through the tabular. This would make it much easier to read tabulars with a large number of rows and columns.

![image](https://github.com/galaxyproject/galaxy/assets/32272674/96d05fa7-dae3-4c5a-9cfc-8c4bb61c0c81)

Thanks for considering :)

Simon

**Comment by hujambo-dunia** [comment]
@simonbray [This is](https://github.com/galaxyproject/galaxy/pull/17455#issue-2130378768) what your colleague had in mind?
