### ISSUE TITLE
Question about uploading file size in LeFse

### ISSUE THREAD

**Issue by YuhangZhou-med** [galaxyproject/galaxy#17417]
Thanks for reading this issue!
When I upload my own file, it shows "Warning: Request Entity Too Large (413)", this may be because the file is too large. My file size is 1.3-2.9M, is it possible to modify it to upload a larger file? Thank you for your help！
![image](https://github.com/galaxyproject/galaxy/assets/154689112/9a911526-6188-46d7-a531-6396c50ee479)

**Comment by mvdbeek** [comment]
I'm sorry, we can't help you with this as we're not running or maintaining the lefse galaxy instance. Your best chance is to try to  contact someone that maintains the lefse galaxy server, possibly at https://forum.biobakery.org/.

**Comment by YuhangZhou-med** [comment]
> I'm sorry, we can't help you with this as we're not running or maintaining the lefse galaxy instance. Your best chance is to try to contact someone that maintains the lefse galaxy server, possibly at https://forum.biobakery.org/.

Thank you for your help！
