### ISSUE TITLE
upload is targeting an incorrect history

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17418]
**Describe the bug**
Uploading data to Galaxy targets a history different from the active one.

~~note: *I am not able to reproduce this locally.*~~

I reproduced it locally on release_23.2 -- you have to do the actions a little bit faster to trigger this.

My guess would be that maybe the history switching does not bubble all through before the modal opens and the modal has still incorrect history as its target.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.2 (Main)

**To Reproduce**
1. Go to usegalaxy.org
2. (Have at least two histories in your account -- not sure if necessary)
3. Switch to a different history (either through history list or through fast switch button in history header
4. Upload pasted data
5. Observe your datasets are not created in your active history, but in the one you switched *from* instead.

**Expected behavior**
The active history shown in the history panel should be the targeted one.

**Comment by dannon** [comment]
Fixed in #17431
