### ISSUE TITLE
Tool link is not URL encoded

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#17425]
**Describe the bug**

If one copies a link then spaces in tool IDs are not encoded. Guess they should. 

Example `https://galaxy.intranet.ufz.de/root?tool_id=toolshed.g2.bx.psu.edu/repos/devteam/emboss_5/EMBOSS: transeq101/5.0.0`

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1

**Comment by mvdbeek** [comment]
Is it really a bug ? If you use that url and paste it somewhere in into a browser the spaces will be escaped.

**Comment by davelopez** [comment]
I just tried and it works as Marius suggested, I'll close this one then. feel free to re-open with more info if it doesn't work for you.

**Comment by bernt-matthias** [comment]
If one just copy pastes it to some document / email and send it to users it creates problems.

**Comment by bernt-matthias** [comment]
I mean we encode the URLS in the links in the tool menu .. then why not just do the same in the tool form options menu: 

![Screenshot from 2024-02-06 11-34-00](https://github.com/galaxyproject/galaxy/assets/25689525/38d2552e-8998-4e42-977c-3e6b4215893e)

**Comment by bernt-matthias** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/17426?
