### ISSUE TITLE
importing shared history problems

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1743]
on Main first attempt fails with internal server error but probably is caused on the JS side in `popup-menu.js` shich shows this when the modal 'importing history"name"' opens
![screenshot 2016-02-16 13 11 55](https://cloud.githubusercontent.com/assets/1814954/13085986/f064f0e0-d4ae-11e5-914e-61875fb03d3c.png)

(and also tries to load some images from sentry?)
![screenshot 2016-02-16 13 06 58](https://cloud.githubusercontent.com/assets/1814954/13085840/36686c26-d4ae-11e5-8bef-2ca73805f269.png)

second attempt imports it but loads Galaxy within Galaxy
![screenshot 2016-02-16 13 05 47](https://cloud.githubusercontent.com/assets/1814954/13085802/0631cf48-d4ae-11e5-8d54-19ffeb748aaf.png)

**Comment by carlfeberhard** [comment]
I think I can reproduce this. Can you confirm these are the steps you took?:
1. Open the 'shared with you' list from the history panel options menu
2. Click the popup for the history you want to import and select 'view'
3. From inside the center panel history view, click import history
--> error

**Comment by martenson** [comment]
@carlfeberhard confirmed
