### ISSUE TITLE
Setting metadata type to FASTA triggers automatic search - very long time with NGS FASTA

### ISSUE THREAD

**Issue by alpapan** [galaxyproject/galaxy#17451]
**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1.5.dev0
Commit: 1fe37b099f6f7da20c2483157bb2c1d94a766c67

**Describe the bug**
1. When editing a dataset to "Assign Datatype" to a **specific** type, galaxy triggers an auto search rather saving type I gave
2. auto search takes a very long time (~ 30 min) with a FASTA derived from NGS data (e.g. a 100Gb one)

**To Reproduce**
1. Get an NGS FASTQ
2. use seqtk seq to convert to FASTA
```
seqtk seq -q 0 -X 255 -n '0' -l 0 -Q 33 -s 11 -f 1.0 -L 0   -A     '/apps/others/galaxy/database/objects/6/6/e/dataset_66e3f585-fd79-452c-b4fe-6b5c13a2789e.dat'  > '/apps/others/galaxy/database/objects/c/0/7/dataset_c075e127-6a96-4466-8f26-c2759f47f7d0.dat'
```
3. notice that output file is FASTQ not FASTA (that's a separate tool issue)
7. fix error by clicking on `https://mygalaxy.com/datasets/5eecf592a906cc73/edit` and clicking on a `New type` under Data types. 
8. select `fasta`
9. click `Save` (not autodetect or enter key)
10. login into slurm node and observe

![0e2c7524-f027-4d9a-989b-10372d810e97](https://github.com/galaxyproject/galaxy/assets/608484/26f17e44-7c6a-4dca-9165-2b32cb75db0e)

**Expected behavior**
I expect explicitly setting metadata (not automatic) to a specific one to be very quick and independent of file size

```
# cat /apps/others/galaxy/database/jobs_directory/002/2153/configs/tmpu3x0x5cr
from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()
```

**Comment by alpapan** [comment]
(output is correct and metadata is set to FASTA - but it takes ca 30 min and goes through file with single thread.
It uses ca 0.250 Gb of ram)

i expected with setting file to a metadata type to not trigger an autosearch (if that is what is happening)

**Comment by mvdbeek** [comment]
Setting metadata does a whole lot more than just setting the extension in the database, for bam datasets this for instance generates the bam index. For fasta files https://github.com/mvdbeek/galaxy/blob/e02a765b7b1e026b639fdaaa3638d73bd541e2e3/lib/galaxy/datatypes/sequence.py#L109-L127 is what is being run. If your file is a 100GB then yes, that sounds about right. Some datatypes bail out of counting lines or sequences above a certain line, but that of course breaks tools that depend on this type of metadata being available.

**Comment by bernt-matthias** [comment]
Will do. Just wanted to wait on feedback first.

**Comment by martenson** [comment]
The speedups by @bernt-matthias have been merged. @alpapan Galaxy is relied upon to have the metadata available for these datatypes so it cannot afford to simply flip the datatype flag. I hope the speedups help your usecase.
