### ISSUE TITLE
format_source doesn't work with workflows + "Input Datasets"

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1746]
I had to manually specify the output dataset format to be fasta.

The workflow looks like this:

```
Input Dataset -> Tool X -> Tool Y
```

where tool X has the following:

```
  <inputs>
    <param label="Data File" name="input_file" type="data"/>                                                                                           
  </inputs>                                                                                                                                            
  <outputs>                                                                                                                                            
    <data format_source="input_file" name="output_file" label="$input_file.name"/>                                                                     
```

And tool Y happily accepts anything from `Input Dataset`, but will not accept the output of `Tool X`. 

Not tagged as a bug as I haven't tested `:dev` yet

**Comment by jmchilton** [comment]
Huh - you are probably totally right. This should be an easy fix.

**Comment by hexylena** [comment]
Ah, I assumed it would be miserably unpleasant as it'd require working back through the chain of dependencies until it hit one with a hard coded format or an unknown "Input Dataset" element.

Also would be great if we could restrict the formats accepted by "Input Dataset" elements, but that might be a separate issue.

**Comment by jmchilton** [comment]
Spent some time looking into this tonight - I can't replicate the description here and I reviewed the workflow module code for handling `format_source` and it is much smarter than I assumed.

Mind supplying specific tools? Ideally modifications of tools in test/functional/tools.

**Comment by hexylena** [comment]
Tested again, on`release_16.01` and `dev`

![selection_575](https://cloud.githubusercontent.com/assets/458683/13260978/a0bd283a-da23-11e5-9ff7-74dec1684cc2.png)

So! The top two outputs will connect from "tool X" in the middle to "Tool Y" on the right, whilst the bottom two (with `format_source` are unable to connect to tool Y)

``` xml
<tool id="output_format" name="Tool X" version="1.0.0">
  <command>
    echo "test" > 1;
    echo "test" > 2;
    echo "test" > 3;
    echo "test" > 4;
  </command>
  <inputs>
    <param name="input_data_1" type="data" format="data" />
    <param name="input_data_2" type="data" format="data" />
    <param name="input_text" type="text" value="1" />
  </inputs>
  <outputs>
    <!-- WORKS -->
    <data format="txt" from_work_dir="1" name="direct_output" />
    <!-- WORKS -->
    <data format="input" from_work_dir="2" name="input_based_output" />
    <!-- DOES NOT WORK -->
    <data format="txt" from_work_dir="3" name="format_source_1_output" format_source="input_data_1" />
    <!-- DOES NOT WORK -->
    <data format="txt" from_work_dir="4" name="format_source_2_output" format_source="input_data_2" />
  </outputs>
</tool>
```

the last tool just requires `txt` formatted inputs

``` xml
<tool id="require_format" name="Tool Y" version="1.0.0">
  <command>
    echo "test" > 1;
  </command>
  <inputs>
    <param name="input_data_1" type="data" format="txt" />
  </inputs>
  <outputs>
    <data format="txt" from_work_dir="1" name="direct_output" />
  </outputs>
</tool>
```

**Comment by hexylena** [comment]
The above is somewhat understandable--an Input Dataset doesn't have a defined datatype.

This however is more of an issue:
![selection_576](https://cloud.githubusercontent.com/assets/458683/13261159/789e3348-da24-11e5-9dec-c4b5281667c8.png)

Here we have a tool with a hardcoded output format, `txt`, which is being passed to a tool which uses `format_source`. The output format _should_ be able to be calculated, however the "require txt" on the right fails to be able to connect to any output which takes advantage of format_source

**Comment by jmchilton** [comment]
@erasche - You are totally right - that logic that I thought was superior for `format_source` versus `format="input"` is actually worse in this context - it restricts things too much.

**Comment by hexylena** [comment]
Ah ok @jmchilton. Thanks for confirming this issue :) No pressure from me to fix, I've avoided `format_source` up until very recently.

**Comment by jmchilton** [comment]
@erasche any interest in testing out https://github.com/galaxyproject/galaxy/pull/1786?

**Comment by hexylena** [comment]
@jmchilton sure thing, on it. I'm so much more willing after I added the git thing to let me checkout individual PRs. Life is so much better now.

```
[remote "upstream"]
        url = git@github.com:galaxyproject/galaxy
        fetch = +refs/heads/*:refs/remotes/upstream/*
        fetch = +refs/pull/*/head:refs/remotes/upstream/pr/*
```

**Comment by hexylena** [comment]
@jmchilton fix looks good, would you like me to open a separate issue to track the underlying problem?
