### ISSUE TITLE
Password reset link still present in login page when enable_account_interface is set to false

### ISSUE THREAD

**Issue by microfuge** [galaxyproject/galaxy#17472]
Hi,

This is a super minor issue.  

We use ldap to solely handle authentication for users in our local galaxy instance.  So the `enable_account_interface: false` is set so that users can not change any info or reset their passwords. 

This nicely disables all setting in "manage information"  in user -> preferences (which is exactly what we want). 

 
![2024-02-14_17-18](https://github.com/galaxyproject/galaxy/assets/22501424/aeeb02a8-ef3a-4136-950a-2573339312b2)

How ever the login page still still retains the link to reset passwords 

![2024-02-14_17-20](https://github.com/galaxyproject/galaxy/assets/22501424/98636acf-cd0c-4a05-9323-ccb35082ab31)

Before, I commented the link text in the file `client/src/components/login/LoginForm.vue`  so that the link does not appear, but it would be good to have this done by galaxy itself. 

Thanks!

**Comment by dannon** [comment]
Good point, galaxy can definitely do this automatically.
