### ISSUE TITLE
clarify the visual language of selected masthead vs activity bar

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17476]
Different items in activity bar are linked to different places in the masthead. Both activity bar and masthead have a "highlight" feature for the active item. It would be good to unify handling of this to prevent double highlighting.

See highlights for workflow invocation list below.

<img width="47" alt="Screenshot 2024-02-14 at 3 02 12 PM" src="https://github.com/galaxyproject/galaxy/assets/1814954/d0265337-09c8-4779-a9e7-b08f1deee908">
<img width="583" alt="Screenshot 2024-02-14 at 3 02 22 PM" src="https://github.com/galaxyproject/galaxy/assets/1814954/71adaa6b-fd60-4223-9e5d-368411350d25">

**Comment by ahmedhamidawan** [comment]
A potential, partial fix for this will be here: https://github.com/galaxyproject/galaxy/pull/17251/commits/1a44b0ef1cb6e5b6bc05645df898c97410cf6b95
This makes sure the activity is _active_ if we are on the `activity.to` route, unless a "panel-only" activity (like Tools) is active.
