### ISSUE TITLE
Stopping and restarting the Galaxy server eliminates Manage Display Whitelist settings

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#1748]

**Comment by dannon** [comment]
@gregvonkuster Are you seeing any error messages when you go to save the whitelist?  This is something that should be written to file immediately, and would persist across reboots.

**Comment by gregvonkuster** [comment]
Paster log shows this when saving:
galaxy.queue_worker INFO 2016-02-17 08:59:05,978 Sending reload_sanitize_whitelist control task.
127.0.0.1 - - [17/Feb/2016:08:59:05 -0400] "GET /admin/sanitize_whitelist?tools_to_whitelist=localhost%3A9009%2Frepos%2Fiuc%2Fminmjj_generate_map_plot%2Fminmjj_generate_plot_map%2F1.0.0&submit_whitelist=Submit+new+whitelist HTTP/1.1" 200 - "http://localhost:8763/admin/sanitize_whitelist" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4"

The checked whitelist items remain checked until the server is stopped and restarted.  Upon restart, all checked boxes are no longer checked.  There is nothing in the paster log with the restart that refers to the whitelist.

**Comment by dannon** [comment]
@gregvonkuster Thanks for the info, this is a little weird.  Multiprocess server?  What sort of configuration (uwsgi, etc)?  I'll try to reproduce it here.

**Comment by dannon** [comment]
@gregvonkuster No need for more info, I think I've got it. The file is saved correctly and isn't overwritten, it just is't being loaded correctly on start.  Thanks for the report, and I'll have a fix out in a minute!

**Comment by gregvonkuster** [comment]
Thanks @dannon !!

**Comment by dannon** [comment]
Resolved in #1749
