### ISSUE TITLE
Ship all tool error logs to sentry

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1750]
Many of us use and love the sentry integration. It would be incredibly useful to ship tool errors there, as soon as they happen, without respect to whether or not a bug report was sent.

Maybe tool stderr for (certain) tools as well? All of my tools handle non-fatal errors gracefully, given that we already have a system in place for capturing non-fatal errors, it would be nice to re-use that here, somehow, maybe.

**Comment by dannon** [comment]
Love it, and I think it's pretty easily doable.  Will think about it.
