### ISSUE TITLE
Encode ID API endpoint missing

### ISSUE THREAD

**Issue by mira-miracoli** [galaxyproject/galaxy#17503]
**Describe the bug**
Not really a bug, but a feature that is missing.
If I want to interact with the galaxy API and for example delete users, like the [WALL·E script](https://github.com/usegalaxy-eu/WallE) is doing, you need to be able to encode galaxy IDs.
You could do this with the `secret_decoder_ring.py`, but you would need to open subprocess and source Galaxy's virtualenv and pass Galaxy's config file with the id_secret.
This seems to be a bit hacky to me and there might be scenarios where WALL·E runs on nodes, that can not access this secret and/or Galaxy's virtualenv. (Even though I would need to change a few things to reduce dependencis for sure.)

EDIT: I forgot that it actually sources the virtualenv currently, because I can avoid installing packages twice then, so yeah, maybe I can also do it the hacky way and we can close this issue.
(if not someone else finds this endpoint useful and wants to implement it)

I understand that this is not an important feature to implement, but maybe it could serve as a good first issue.

**Expected behavior**
An API endpoint like
`/api/configuration/encode/{decoded_id}`

**Comment by nsoranzo** [comment]
Obviously this would need to be an admin-only endpoint.
