### ISSUE TITLE
Broken Images on UseGalaxy Welcome Email Confirm Page

### ISSUE THREAD

**Issue by hujambo-dunia** [galaxyproject/galaxy#17512]
Didn't have time to research why these images were broken (or what else might be on this page) but just noticed this after registering as a new test user. This is the page one is directed to after confirming their email address. Kind of surprised our CI (or integration tests) didn't catch it as well so maybe we need some test to run for certain high-value pages. Question is: do we want to get in before the code freeze?

<img width="1035" alt="Greenshot 2024-02-20 11 32 47" src="https://github.com/galaxyproject/galaxy/assets/3672779/f3e4b297-e947-4c5b-ac63-38dabfddb388">

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Register on UseGalaxy.org as a new user
2. Click the confirm email link in your inbox

**Expected behavior**
Images should appear instead of broken-link icons.

**Comment by mvdbeek** [comment]
The whole new user welcome has been removed
