### ISSUE TITLE
All file upload methods failing in 23.02

### ISSUE THREAD

**Issue by vazovn** [galaxyproject/galaxy#17539]
**Describe the bug**
After the upgrade from 23.1 to 23.2 all the upload methods are failing!

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.2
Commit: 9c593cd

**To Reproduce**
All 3 methods are failing:

`Choose local file` throws an error displayed in attached file `upload_from_computer.txt`
[upload_from_computer.txt](https://github.com/galaxyproject/galaxy/files/14385919/upload_from_computer.txt)
The jobs run but turn red at the end

`Choose remote files` and `Fetch/Paste`  throw an error displayed in attached file `upload_remote_files.txt`
[upload_remote_files.txt](https://github.com/galaxyproject/galaxy/files/14385914/upload_remote_files.txt)
The jobs for `Fetch/Paste`  run and turn red.
The jobs for `Choose remote files` display a page which is hanging ("Please wait" wheel)

All uploads are executed as slurm jobs.
Uploads (`Choose local file` and  `Fetch/Paste` ) are executed as slurm jobs and the slurm jobs succeed.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mvdbeek** [comment]
It appears that you've got a mix of old and new Galaxy code in your traceback. Can you make sure that everything is synced up properly ? These tracebacks really don't make any sense. 23.2 for instance has no raw_set_dataset_state method or call.

**Comment by vazovn** [comment]
Ok, I will try. Johns fix on OpenIdC works well, how can I assure that I take it in the new code? I am now running

Galaxy Version: 23.2
Commit: https://github.com/galaxyproject/galaxy/commit/9c593cd0ce4642d2d8d4cdf137616ff141a4f0e6

Which will be the commit id containing John's changes ?

Thanks

**Comment by mvdbeek** [comment]
Deploy from the release_23.2 branch as usual, that contains everything.

**Comment by vazovn** [comment]
Hi,

I deployed release_23.2 and things look better. However I still have a problem to upload remote files. I have the file `file_sources_conf.yml`

```
- type: gxuserhome
  id: userhome
  doc: Get your data from FOX home area
  label: FOX Home Area

- type: gxuserprojects
  id: userprojects
  doc: Get your data from FOX project area
  label: FOX project Area
```

and I have the respective lines in `../files/sources/galaxy.py`

```
   .... 
    def get_scheme(self):
        return "gxuserimport"


class UserHomeFilesSource(PosixFilesSource):
    plugin_type = "gxuserhome"
    plugin_kind = PluginKind.stock


    def __init__(self, **kwd: Unpack[PosixFilesSourceProperties]):
        posix_kwds: PosixFilesSourceProperties = dict(
            id="_userhome",
            root="/fp/homes01/u01/${user.username}/",
            label="User Home Directory",
            doc="Galaxy User's Home Directory",
            writable=True,
        )
        posix_kwds.update(kwd)
        super().__init__(**posix_kwds)

    def get_prefix(self) -> Optional[str]:
        return None

    def get_scheme(self) -> str:
        return "gxuserhome"


class UserProjectFilesSource(PosixFilesSource):
    plugin_type = "gxuserprojects"
    plugin_kind = PluginKind.stock

    def __init__(self, **kwd: Unpack[PosixFilesSourceProperties]):
        posix_kwds: PosixFilesSourceProperties = dict(
            id="_userprojects",
            root="/fp/projects01/",
            label="User Projects Directory",
            doc="Galaxy User's Projects Directory",
            writable=True,
        )
        posix_kwds.update(kwd)
        super().__init__(**posix_kwds)

    def get_prefix(self) -> Optional[str]:
        return None

    def get_scheme(self) -> str:
        return "gxuserprojects"


__all__ = ("UserFtpFilesSource", "LibraryImportFilesSource", "UserLibraryImportFilesSource", "UserHomeFilesSource", "UserProjectFilesSource")

```

The file source is actually a nfs4 mounted directory. 

I can list the content but when I click on Start (to upload), I get the following screen:

![error_upload](https://github.com/galaxyproject/galaxy/assets/11718320/a02c14f0-909b-4dc5-9e56-41ced1ff0794)

There is nothing in the galaxy logs. What changed actually? It used to work like a song in 23.1

There is only one suspicious line there in the log, no idea if it is related, it appears just before I click on Start.

```
  Feb 26 14:36:37 galaxy01.educloud.no galaxyctl[2769202]: /cluster/galaxy/srv/galaxy/server/lib/galaxy/managers/interactivetool.py:249: SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
Feb 26 14:36:37 galaxy01.educloud.no galaxyctl[2769202]:   stmt = select(InteractiveToolEntryPoint).where(InteractiveToolEntryPoint.job_id.in_(build_subquery()))
```

Thank you in advance

**Comment by mvdbeek** [comment]
I'm not sure what you're reporting here. Are these custom file source plugins you're developing ? This doesn't seem related to the original issue, and it also seems like that's perfectly definable with the standard posix plugin.

**Comment by jdavcs** [comment]
Reopening this for now, in case @vazovn may have follow up questions or comments.

**Comment by dannon** [comment]
I talked to @vazovn about this over matrix; I can open (and then resolve) the relevant issue.  Yes, it's related to a custom file source plugin.

**Comment by vazovn** [comment]
Hi, @jdavcs thank you for reopening. I have a couple of custom file source plugins which I developed with the help of @dannon in 23.1. The procedure has been then changed from 23.1 to 23.2. In 23.2 all the plugins (protocols) are _hardcoded_ in `../server/client/src/upload-payload.js`  at the top of the file. When missing there, I get the error in the comment above: Error: Invalid url. If I manually add my plugins, this fixes the issues. But it is far from elegant that for every custom plugin one shall need to patch the js file and ... rebuild the client. @dannon said he would look into it. So, what shall we do about this issue, close it and open a new one or solve it here?

**Comment by mvdbeek** [comment]
Can you show us your branch with those changes ? It does appear from the snippet you posted that a custom file source is not necessary.

**Comment by vazovn** [comment]
Hi, the snippet contains my custom plugins, yes. They shall not go into galaxy general code. Yet, they fail due to the change in the way the custom file plugins are handled. Custom file plugins seem to be _hardcoded_ in `../server/client/src/utils/upload-payload.js`. I fixed it temporarily by editing this file (see gist below): 

https://gist.github.com/vazovn/ba8f2907ad717aeeb212e023168c71ce#file-gistfile1-txt

The whole discussion was whether the new way of handling file plugins is relevant - every new file plugin will require editing this file and recompiling the client. 

In 23.1 this was not necessary. I though with every new version we shall gain and not lose flexibility :-)
