### ISSUE TITLE
Deprecations for 16.04

### ISSUE THREAD

**Issue by carlfeberhard** [galaxyproject/galaxy#1757]
Do we have a method for adding deprecations to the notes? Or anywhere? Seems like we should document these.

(I'm assuming it would not be best for me to suggest these be deprecations for 16.01, so) for 16.04:
- API histories (removed from the available serialized data on all calls): 
  - **state, state_details, state_ids** - can be replaced by specifically requesting a single array of contents, each containing `{ id, state, deleted, visible }` (name/key TBD)

**Comment by martenson** [comment]
@carlfeberhard I thought we are handling it like this: https://github.com/galaxyproject/galaxy/commit/5bd898118f96ff30093fcd932de3483fee028453
Do you think we should highlight it more?

**Comment by carlfeberhard** [comment]
Not necessarily - up to you guys. If I want to add to the list I just PR onto https://github.com/carlfeberhard/galaxy/blob/dev/doc/source/releases/16.04_announce.rst?

Will any changes still persist if notes are being auto-generated now?

**Comment by natefoo** [comment]
Yeah, I don't think the manual method there is possible until the release notes PR has been merged. I like the idea of having this as an issue on the 16.04 milestone.

**Comment by martenson** [comment]
What about having a shared 'WIP deprecation pull request' against next release that will gather this information? Issue is fine too though.
edit: issue is better

**Comment by carlfeberhard** [comment]
- API for history datasets (api/histories/{id}/contents/{id}, etc.):
  - **api_type**: removed and unavailable (was 'file' and constant across HDAs) 
  - **display_apps**, **display_types**, **visualization**: removed from the default `detailed` view but still available by calling url with `?keys=display_apps,display_types,visualization` (#1855)

**Comment by carlfeberhard** [comment]
@martenson yeah, I'm not sure the best way to do this. For now I'm adding comments (as opposed to editing) to the original. Hope that works for all.

I guess I should explicitly add this too (from #1602):
- API for history contents, index:
  - **types**: is no longer a valid parameter but accessible using `?q=history_content_type&qv=[dataset | dataset_collection]`
  - **ids**: is no longer a valid url parameter but is accessible using `?q=type_id-in&qv=<e.g. dataset-abcdef123,dataset_collection-987fedcba, ...>`
  - **deleted** and **visible**: are no longer parameters but are still accessible using `q=deleted&qv=[True | False]&q=visible&qv=[True | False]`

**Comment by martenson** [comment]
@carlfeberhard I think this works the best

**Comment by martenson** [comment]
per @natefoo last bitbucket release is 16.04

**Comment by martenson** [comment]
added to notes with https://github.com/galaxyproject/galaxy/pull/2353/commits/93d1d5611e3d62f928af49edd884dfea5fcf4c11
