### ISSUE TITLE
Enhancement: Trap if an unsupported version of python is used in start up scripts

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#17590]
**Describe the bug**
Installing a local Galaxy is complicated. Could we add more to trap a few obvious mixups with `run.sh` and `common_startup.sh`? The message now doesn't come up with _some_ use cases. Maybe add a few more sanity checks with a human-readable message parsed out at a top level?

For an example, see https://help.galaxyproject.org/t/python-command-not-found-on-local-galaxy-istance/11763

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mvdbeek** [comment]
We do have that in place, and https://help.galaxyproject.org/t/python-command-not-found-on-local-galaxy-istance/11763 is a dependency problem.
