### ISSUE TITLE
Not possible to switch to purged (or archived history)

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#17604]
I can't switch to most of these, but that should be possible IMO. Unfortunately we seem to tie that into marking the history as the current history on the backend, which would indeed be problematic.

<img width="1572" alt="Screenshot 2024-03-05 at 17 35 10" src="https://github.com/galaxyproject/galaxy/assets/6804901/baf41c31-b122-4b89-a360-090b20fa4909">

**Comment by davelopez** [comment]
Would be a good compromise solution to change the "Switch to" in those cases to "View" (as read-only view like in `/histories/view?id=<history_id>`)? We could also render a little icon indicating the purged or archived status beside the name.

**Comment by dannon** [comment]
Discussed in UI/UX.  What David said :)

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/17616
