### ISSUE TITLE
[23.2] Workflow ToolBox has `UploadButton`, Favorites button doesn't render

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#17602]
This probably happened when we nested the `ToolBox` under a new `ToolPanel` in https://github.com/galaxyproject/galaxy/pull/16739

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/17634, thanks @ahmedhamidawan!
