### ISSUE TITLE
Show activity bar on the storage dashboard top-level view

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#17617]
**Describe the bug**
Show the activity bar on the storage dashboard view https://usegalaxy.org/storage

**Galaxy Version and/or server at which you observed the bug**
Usegalaxy.org
The Galaxy Server is running version [24.0.rc1 ](https://docs.galaxyproject.org/en/release_24.0/releases/24.0_announce_user.html), and the web client was built on Wednesday Mar 6th 8:15:07 2024 GMT-8 .

**To Reproduce**
1. Go to User > Preferences and turn on the activity bar if not already enabled
2. Got to User > Preferences > Storage Dashboard: 
3. Notice that the activity bar isn't shown. The Masthead still is, so not a dead end.
4. There are likely other views like this. 

**Expected behavior**
Show activity bar on https://usegalaxy.org/storage
I **don't** think it is needed for the sub-views but others can have opinions! 
https://usegalaxy.org/storage/histories
https://usegalaxy.org/storage/management

It is slightly jarring that the per-history view at a URL like https://usegalaxy.org/storage/history/NNNN is inside the middle panel, but if you click on Back to Dashboard link from there, the full view of https://usegalaxy.org/storage removes all navigation except for the masthead. Adding in the activity bar is probably enough. Thanks! 

**Screenshots**

**Additional context**

**Comment by martenson** [comment]
When enabled, the activity bar should never disappear.
