### ISSUE TITLE
make history filters horizontal

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17618]
there is a lot of wasted space making the interface harder to navigate since the actual data are pushed to the narrow view in the bottom of the screen

Bonus points for rephrasing the "Filter on..." texts to something better and reusing the `X` as a visual for cancel instead of the loop arrow.

<img width="1373" alt="Screenshot 2024-03-06 at 10 07 38 AM" src="https://github.com/galaxyproject/galaxy/assets/1814954/eed7ad0c-8031-4872-b288-c4360c914947">

**Comment by ahmedhamidawan** [comment]
Is it ok if we use the `faAngleDoubleUp` instead of `faTimes` (X):
![image](https://github.com/galaxyproject/galaxy/assets/78516064/0b277301-49d1-48f3-bb8a-f74a2b3751c7)

**Comment by martenson** [comment]
My 2c is that either cancel button should have an X or be without an icon. Having different icons for the same functionality in different contexts is a source of confusion. 

You might also consider dropping the cancel button from these interfaces altogether since it just duplicates the functionality of the toggle dropdown button.

As of the popover this might be one of the better uses for it but I would be concerned about accessibility.

**Comment by ahmedhamidawan** [comment]
> You might also consider dropping the cancel button from these interfaces altogether since it just duplicates the functionality of the toggle dropdown button.

For the cancel button, i think this is a good idea, I'll just drop it
