### ISSUE TITLE
do we have usecases for issue/PR templates?

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1762]
new GH feature:

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by hexylena** [comment]
I thought about it a few days ago when there were rumours/examples. Given that 95% of the issues in the repo are developer focused (and not client focused where we might be collecting things like galaxy version / os version / etc), I'd say we actually don't. All that stuff just ends up in biostars / on IRC

**Comment by hexylena** [comment]
3+ years and no comments / need, I'm going with "no"

**Comment by hexylena** [comment]
3+ years and no discussion, so closing and we can revisit it if we ever need :)
