### ISSUE TITLE
Is `allow_cors=True` supposed to be add ACAO headers for visualisation?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#17643]
In `lib/galaxy/datatypes/display_applications/configs/minerva/tabular.xml` we set `<param type="data" name="data" url="galaxy_${DATASET_HASH}.tsv" allow_cors="true" />`

looking at lib/galaxy/webapps/galaxy/controllers/dataset.py L686 it looks like this is indeed used. 
However it doesn't seem to function in a useful way for me.

Looking at the HEAD request, I'm not seeing a ACAO header,

```
$ curl --silent -H "Access-Control-Request-Method: GET" -H "Origin: https://covid19map.elixir-luxembourg.org" --head https://usegalaxy.org/display_application/f9cad7b01a47213579c3a2b970ae5cfc/minerva_tabular/covid19/3be62212b16e0268/data/galaxy_f9cad7b01a47213579c3a2b970ae5cfc.tsv | grep Access
$
```

versus EU who [have a manual `nginx` exception](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/88827358fb31fe7eb5fc4c835b92a7a35afc685e/templates/nginx/galaxy-main.j2#L81) for this visualisation (thanks y'all.)

```
$ curl --silent -H "Access-Control-Request-Method: GET" -H "Origin: https://covid19map.elixir-luxembourg.org" --head https://usegalaxy.eu/display_application/4838ba20a6d867656f60e7ad9f36a860/minerva_tabular/covid19/d3ca1b21b62e6581/data/galaxy_4838ba20a6d867656f60e7ad9f36a860.tsv | grep Access-Con
Access-Control-Allow-Origin: https://covid19map.elixir-luxembourg.org
Access-Control-Allow-Methods: GET
Access-Control-Expose-Headers: Content-Length,Content-Range
Access-Control-Allow-Headers: DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range
```

**Comment by mvdbeek** [comment]
The fun thing is that avivator seems to request byte ranges that go beyond the content length, at least for small files:
<img width="751" alt="Screenshot 2024-03-25 at 19 26 04" src="https://github.com/galaxyproject/galaxy/assets/6804901/902da16f-340c-4f41-942d-90f6327577f9">

I'll try with something bigger. That said `Access-Control-Allow-Origin` and `Access-Control-Allow-Methods` are in principle present, but we might be overriding them in the nginx config.

**Comment by mvdbeek** [comment]
ok, the trick is that we need to return the upstream response header.
I've done this temporarily on one of the upstream web servers:

```
curl --silent -H "Access-Control-Request-Methods: GET" -H "Origin: https://covid19map.elixir-luxembourg.org" --head https://galaxy-web-05.galaxyproject.org/display_application/f9cad7b01a47213579c3a2b970ae5cfc/minerva_tabular/covid19/3be62212b16e0268/data/galaxy_f9cad7b01a47213579c3a2b970ae5cfc.tsv | grep Access
Access-Control-Allow-Origin: https://covid19map.elixir-luxembourg.org
Access-Control-Allow-Methods: GET
```

we are not setting expose and allow, I suppose we'll need them ?

**Comment by mvdbeek** [comment]
and the nginx config is:

```
...
    location /_x_accel_redirect {
        internal;
        alias /;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Content-Type-Options nosniff;
        add_header Access-Control-Allow-Origin $upstream_http_access_control_allow_origin;
        add_header Access-Control-Allow-Methods $upstream_http_access_control_allow_methods;
    }
...
```

**Comment by mvdbeek** [comment]
That was it, avivator is working via galaxy-web-05, I'll open a PR to the docs and our playbook to make that permanent.
Here's a URL to try https://avivator.gehlenborglab.org/?image_url=https://galaxy-web-05.galaxyproject.org/display_application/f9cad7b01a47213564ccacceb7120aa7/avivator/main/14e6c43ce90708ee/data/galaxy_f9cad7b01a47213564ccacceb7120aa7.tiff

**Comment by hexylena** [comment]
I guess we also need to add this to the nginx/apache docs in galaxy

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/17842

**Comment by mvdbeek** [comment]
And https://github.com/galaxyproject/usegalaxy-playbook/pull/386 for the playbook
