### ISSUE TITLE
[24.0] Copy Visualizations from Grid should ask for confirmation

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#17667]
**Describe the bug**
I think it is important to give the chance to cancel the copy since this action will create a new item in the database and there is no way to "purge" a visualization if it was copied by mistake (is that another issue? :thinking:)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Go to https://usegalaxy.org/visualizations/list
2. Click on any visualization
3. Select `Copy`
4. No confirmation dialog is displayed

**Expected behavior**
A confirmation dialog should be displayed giving the chance to cancel the copy.

**Screenshots**
![CopyVisualizationNeedsConfirm](https://github.com/galaxyproject/galaxy/assets/46503462/274a89f4-6772-43cd-925c-b05ec598478c)

**Additional context**

**Comment by dannon** [comment]
I don't know if I agree with this one -- we generally ask for confirmation for destructive actions, but haven't traditionally done so with others -- it's becomes an extra required click for the common case.  

Permanent deletion of visualizations might be fairly straightforward (though would potentially break published pages, etc), though I'm not sure it's really worth it.  I did a quick check against main out of curiosity and the total relation size of the visualization table is 14MB (out of the whole 893GB).
