### ISSUE TITLE
[24.0] Grid filtering needs a loading indicator

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#17666]
**Describe the bug**
When you change the filters in any of the Grid views (History, Pages, etc.) there is a brief window until we get the response that it will appear as there are no results, but it just takes time for them to appear. That can be confusing.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Go to https://usegalaxy.org/histories/list (or any other resource)
2. Make sure you have some deleted or purged items
3. Try to apply different filters
4. Observe the issue

**Expected behavior**
A loading indicator or similar feedback should be displayed while the results are filtered.

**Screenshots**
![FilterNeedsLoading](https://github.com/galaxyproject/galaxy/assets/46503462/a6921d12-00d2-4409-a306-b05aeca2f0c9)

**Additional context**

**Comment by martenson** [comment]
dupe and xref: https://github.com/galaxyproject/galaxy/issues/17650

I clearly failed to explained what I mean :)

**Comment by davelopez** [comment]
Lol sorry, yeah I somehow missed that when looking :sweat_smile:
