### ISSUE TITLE
[24.0] The `is` filter in Grid Views "accepts" any value

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#17668]
**Describe the bug**
If you enter any random text after `is:` it is treated as "no filtering" which might be confusing.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Go to any Grid view, for example, https://usegalaxy.org/histories/list
2. Write in the search bar `is:something`
3. Observe all items are returned as if there was no filtering applied

**Expected behavior**
I would expect either no matching items or a message indicating the filter is not valid.

**Screenshots**
![GridViewIsFilterTooPermissive](https://github.com/galaxyproject/galaxy/assets/46503462/157d942b-28f0-449a-9576-d8da7f0d6204)

**Additional context**
On the other hand, this is exactly what Github filters do... (which I still find confusing) so **feel free to close this one**.

**Comment by jdavcs** [comment]
Fixed in #17684
