### ISSUE TITLE
[24.0] Slow performance when loading published histories

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#17665]
**Describe the bug**
When loading published histories, it takes a considerable amount of time even if only 25 histories are loaded per request.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Go to https://usegalaxy.org/histories/list_published
2. Observe that displaying 25 histories takes a lot of time

**Expected behavior**
I should load 25 histories faster.

**Screenshots**
![PublicHistoriesPerformance](https://github.com/galaxyproject/galaxy/assets/46503462/e2ba896c-6ef5-49d6-ba1d-8ae3a2c64a9b)

**Additional context**
I think the issue (or part of it) might be that we are loading `detailed` views of those histories when we only need the `summary`, and then, we are requesting additional redundant details for each of the histories after the first load.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/17726 is also related here, I would assume that brings performance back down to pre-24.0

**Comment by mvdbeek** [comment]
We're at ~ 700ms now, fixing the `view` parameter in the API was key here. This is still kind of slow (though really not annoyingly so). I'm ready to attribute a lot of that to https://github.com/galaxyproject/usegalaxy-playbook/issues/381. In any case this isn't somehting we need to fix for 24.0, and usegalaxy.eu also requires ~ 500ms. Given https://github.com/galaxyproject/usegalaxy-playbook/issues/381 I would not assume there's a performance regression between the releases now.
