### ISSUE TITLE
[24.0] Collection Scrolling not showing all items 

### ISSUE THREAD

**Issue by tcollins2011** [galaxyproject/galaxy#17677]
**Describe the bug**
When scrolling quickly though a collection larger than 50 elements the scroller will sometimes limit itself to only showing 50 items and will not display the remaining items. This problem can be resolved by reloading the web page.

**Galaxy Version and/or server at which you observed the bug**

Galaxy version 24.0.rc1, commit [a25b23225efe02a35d352681cf7cccb76b86bb43]

**To Reproduce**

1. Using this history: https://usegalaxy.org/u/tcollins/h/copygdscnsoil
2. Open any of the collections that have greater than 50 elements 
3. Quickly scroll up and down the collection
4. There should be an event that suddenly limits the history to only showing 50 elements in the collection

**Expected behavior**
You should be able to see and scroll though all elements inside of a collection.

**Screenshots**

![image](https://github.com/galaxyproject/galaxy/assets/62220253/eb8cc8f1-2a60-44eb-b220-d9b0d5df4b7a)

**Additional context**

I'm not entirely sure what is causing this problem. Upon initial opening of a collection you can scroll though all of the items, but if seems like there is some event trigger that cause a 50 item limit that is persistent until reload.

**Comment by jdavcs** [comment]
More observations: it seems to *sometimes* happen without any scrolling at all, but only after I have scrolled through other >50 item collections in the same history. On some, the scroller will resize 1-2 seconds after rendering, and only 50 items will be available. No obvious patterns.

**Comment by ElectronicBlueberry** [comment]
Update: A significant difference between collections and the history, is that collections rely on a computed side effect. I will try refactoring the code to remove this.
