### ISSUE TITLE
[24.0] Empty history in `My Histories` displays item count as 1

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#17671]
**Describe the bug**
When there are 0 items in the history, the list always displays 1.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Create or make sure you have an empty history
2. Go to https://usegalaxy.org/histories/list
3. Observe the issue

**Expected behavior**
The number of items should be 0

**Screenshots**
![HistoryGridItemsCountIssue](https://github.com/galaxyproject/galaxy/assets/46503462/7186cd4b-6802-47b8-8d5e-5d3d9ca4e7e7)

**Comment by jdavcs** [comment]
The entire list is off by one for me.
(There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-one errors :laughing:)
