### ISSUE TITLE
Manage Activity Bar setting is not remembered across browsers/devices

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#17689]
**Describe the bug**
The Manage Activity Bar setting in user preferences seems to only affect the current browser.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: usegalaxy.org and usegalaxy.eu

**To Reproduce**
1. Enable the activity bar in user preferences
2. Log in to your account in a different browser/from a different device/in a private browser window 
3. Activity bar is not displayed and the setting in user preferences is reset

**Expected behavior**
Like all user preferences this one should be persistent.

**Screenshots**

**Additional context**

**Comment by dannon** [comment]
Thank you for noticing this and starting a discussion.  I think I'd consider this a feature flag or temporary selection to 'opt-in' to testing, not a permanent preference that we'd store to a user's (server-side saved) prefs.

With 24.1 the activity bar is enabled by default, and, with the migration of items from the masthead will be the only way to access many things.  At that point it should no longer be a togglable feature, but rather part of the standard interface.

What do other folks think is most appropriate for this beta/rollout period?  My hunch is that it's okay for this to be purely (local|session)storage for now.

**Comment by davelopez** [comment]
It makes sense **not** to create and save this preference in the database if the Activity bar will be mandatory (no opt-out) in the next release.

We could have communicated better though that this setting is going to be removed after the "Beta" period :sweat_smile: 

![image](https://github.com/galaxyproject/galaxy/assets/46503462/5ce3d582-3d64-4aab-ade9-def1402261a1)

**Comment by dannon** [comment]
@davelopez Good call on the messaging.  I can open PRs to clarify this against 24.0 and dev.

**Comment by dannon** [comment]
This should be resolved now.  Language is clarified for current release, and in dev it's always on.
