### ISSUE TITLE
Tags not reordering correctly on load

### ISSUE THREAD

**Issue by tcollins2011** [galaxyproject/galaxy#17681]
**Describe the bug**

In relation to: #17469

On load, tags are supposed to be ordered by most recently used. However, it seems that tags beginning with '#' are not being ordered correctly upon reload.

**Galaxy Version and/or server at which you observed the bug**
Galaxy version 24.0.rc1, commit [a25b23225efe02a35d352681cf7cccb76b86bb43]

**To Reproduce**
1. open up a history and select an already existing tag that begins with a #
2. add that tag to an item in your history
3. reload the page
4. check the order of the tags and see that the tag you just used isn't at the top of the list of tags

**Expected behavior**
The most recent tag should be seen first.

**Screenshots**

![Galaxy (2)](https://github.com/galaxyproject/galaxy/assets/62220253/ea46d375-1b1a-40a0-b3f6-1b00c3cc7295)

**Additional context**
This problem does not seem to occur on tags that don't begin with a # and the behavior works as normal.

**Comment by jdavcs** [comment]
This seems to work as expected for tags that I've just created, but not for existing tags (both with and without `#`).

**Comment by ElectronicBlueberry** [comment]
Works as expected on Firefox, managed to reproduce on Chrome.

This is likely an indexedDB issue
