### ISSUE TITLE
[RFC] rucio-clients dependency issues

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#17695]
**Describe the bug**
With the merge of https://github.com/galaxyproject/galaxy/pull/17156 , `rucio-clients` is currently listed as a conditional requirement, but it is installed basically everywhere (the only [condition](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/dependencies/__init__.py#L301) is `sys.version_info >= (3, 9)`) independently of its use for an object store.
There are a few issues with this:
1) The `jsonschema` version pinned in `lib/galaxy/dependencies/pinned-requirements.txt` (4.21.1) is incompatible with the [rucio-clients requirements](https://github.com/rucio/rucio/blob/master/requirements.txt#L6) (~=4.20.0), causing a double reinstallation of jsonschema every time Galaxy is started on Python >=3.9 (e.g. https://github.com/galaxyproject/galaxy/actions/runs/8264351393/job/22608256603#step:10:961 ).
2) Unnecessary installation on production systems. This can resolved with this patch:
```diff
diff --git a/lib/galaxy/dependencies/__init__.py b/lib/galaxy/dependencies/__init__.py
index 1664d07e6f..0bb785aa13 100644
--- a/lib/galaxy/dependencies/__init__.py
+++ b/lib/galaxy/dependencies/__init__.py
@@ -298,7 +298,7 @@ class ConditionalDependencies:
         return self.pkce_support
 
     def check_rucio_clients(self):
-        return sys.version_info >= (3, 9)
+        return "rucio" in self.object_stores and sys.version_info >= (3, 9)
 
 
 def optional(config_file=None):
```

3) The patch above causes the `test/integration/objectstore/test_rucio_objectstore.py` integration tests to fail because requirements are only installed at test startup (by `run_tests.sh` calling `./scripts/common_startup.sh`).
In similar situations we add the dependency also to the `[tool.poetry.group.dev.dependencies]` section of `pyproject.toml` and rebuild the requirement files with `make update-dependencies`, which currently results in the following dependencies being added to `lib/galaxy/dependencies/dev-requirements.txt`: `dogpile-cache==1.2.2` , `pbr==6.0.0` , `stevedore==5.2.0`, `tabulate==0.9.0`; and `jsonschema` being downgraded to 4.20.0 in `lib/galaxy/dependencies/pinned-requirements.txt`

4) The rucio-client package [pins its dependencies quite strictly](https://github.com/rucio/rucio/blob/master/requirements.txt#L2-L6), which is likely to cause conflicts with our large set of other dependencies in the future.

I can open a PR with the changes in 2) and 3) above, but I am worried about 4) long-term, so opening this to collect comments. Also ping @SergeyYakubov .

**Comment by SergeyYakubov** [comment]
Agree with everything said. As I see, the same is done for iRODS.

About 4) - I can create an issue in the Rucio repo; maybe they will be willing to relax the requirements.

**Comment by nsoranzo** [comment]
Thanks @SergeyYakubov , that would help! (although it seems there has been push back when this was raised in the past https://github.com/conda-forge/staged-recipes/pull/16601#discussion_r738207331 )

**Comment by nsoranzo** [comment]
Backend group discussion today: I will open a PR with the patch in 2) and add `rucio-clients` to `[tool.poetry.group.dev.dependencies]` , we will deal with dependency conflicts if/when they appear.
