### ISSUE TITLE
Tabular dataset only has lines

### ISSUE THREAD

**Issue by nilchia** [galaxyproject/galaxy#17699]
**Describe the bug**
I uploaded the IRIS.csv file from 'Galaxy 101 for everyone' to usegalaxy.eu and  the number of the columns was not shown.

**Galaxy Version and/or server at which you observed the bug**
Galaxy version 24.0.rc1

**To Reproduce**
1. upload the iris.csv file : https://zenodo.org/record/1319069/files/iris.csv
2. convert it to tabular
3. only the number of lines is shown (151 lines)

**Expected behavior**
both number of the lines and columns (151 lines, 5 columns) 

**Screenshots**
![Screenshot from 2024-03-13 16-23-20](https://github.com/galaxyproject/galaxy/assets/66441226/10962171-b42c-4ee1-a68e-4313a7848c73)

**Comment by wm75** [comment]
The change from https://github.com/galaxyproject/galaxy/pull/17492 does not seem to have made it into 24.0?

**Comment by jdavcs** [comment]
Right! And yet it's milestoned `24.0`. I'll backport it. Thanks for spotting this!

**Comment by jdavcs** [comment]
It's been decided during the backend team weekly call to add it to 24.1.
