### ISSUE TITLE
`PreferredStorePopover` overflows window boundary

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#17707]
https://github.com/galaxyproject/galaxy/assets/78516064/f89458dd-a065-428e-9483-d05fcc64e6b9

**Comment by davelopez** [comment]
xref https://github.com/galaxyproject/galaxy/pull/17460#pullrequestreview-1890691489

Thanks for reporting, I forgot to do so in a formal issue :sweat_smile:

**Comment by jdavcs** [comment]
Fixed in #17742
