### ISSUE TITLE
[24.0] Datepicker in history selector modal filters is not fully accessible

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#17711]
The datepicker in the history selector modal is not fully accessible (probably a z-index issue)

![hidden_datepicker_in_modal](https://github.com/galaxyproject/galaxy/assets/78516064/5d7f35cd-0a5e-4e89-922c-ca6c4afb6681)

**Comment by jmchilton** [comment]
I'll work on this!
