### ISSUE TITLE
Backend seems to ignore view parameter in /api/histories

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#17723]
https://usegalaxy.org/api/histories?limit=25&offset=0&search=&sort_by=update_time&sort_desc=true&show_own=false&show_published=true&show_shared=false&view=summary returns a bunch of things that are not part of HistorySummary (need to eliminate extra="allow" in the model), but in any case the summary view helps.

_Originally posted by @mvdbeek in https://github.com/galaxyproject/galaxy/pull/17717#pullrequestreview-1936969121_

**Comment by davelopez** [comment]
Good catch! I was not expecting that I will try to fix it

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/17726
