### ISSUE TITLE
history storage client works with unencoded IDs

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17729]
These two links (from https://usegalaxy.org/storage/history/213e34fd40cc3941) go to the URLs below instead of using the proper datasets ID `f9cad7b01a472135ada5934941e2bb74`. I assume those are decoded database ids which should not be used on client or returned from the API for that matter.

![Screenshot 2024-03-14 at 9 15 38 AM](https://github.com/galaxyproject/galaxy/assets/1814954/9f59931d-588b-4493-b31d-b7d694d76c09)

https://usegalaxy.org/datasets/115168806/details
https://usegalaxy.org/api/histories/213e34fd40cc3941/contents/datasets/115168806

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0

**Comment by jdavcs** [comment]
Fixed in #17793
