### ISSUE TITLE
[24.0] Published datasets endpoint at `/datasets/list_published` does not display content for anonymous users

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#17730]
Using the masthead, `Data > Datasets` as an anonymous user navigates to `/datasets/list_published` which does not exist.

![image](https://github.com/galaxyproject/galaxy/assets/8046843/aef8a32a-8cfa-4078-8ff4-86efed2d0d3b)
![image](https://github.com/galaxyproject/galaxy/assets/8046843/87c69ff5-51fa-4e2c-a762-e75024d01da4)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Windows, Linux, macOS
Browser: Firefox, Chrome, Chrome-based, Safari

**To Reproduce**
1. Go to from masthead, click on `Data > Datasets`
2. See the error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dannon** [comment]
@itisAliRH Yeah, this is the user's published datasets and shouldn't show without a user.  It looks like the switching ('view in history') is also broken here, I'll take this and handle both issues.

**Comment by martenson** [comment]
I think that URL does not exist, it should be just `/list`

**Comment by dannon** [comment]
Ahh, I thought the intent here was to share public/shared datasets, hence disabling for anonymous.  If it's just the big exhaustive list of datasets that's... interesting?  What are the actual use cases there?

**Comment by martenson** [comment]
mostly searching afaik, that's how I use it

**Comment by itisAliRH** [comment]
> I think that URL does not exist, it should be just `/list`
> 
> It was likely erroneously added with the move to "Data", but there is no "published datasets" concept.

@martenson Yes, it doesn't exist, sorry. I updated the title and description.
