### ISSUE TITLE
nest tool dependecy

### ISSUE THREAD

**Issue by methylome** [galaxyproject/galaxy#1773]
If package A uses package B, and package C uses package B, then should package A be listed on tool_dependencies.xml of package C?

Thanks,
Justin.

**Comment by mvdbeek** [comment]
No, that shouldn't be necessary.
See https://toolshed.g2.bx.psu.edu/view/iuc/package_fontconfig_2_11_1/37b9109e489c
You can see in that list package_zlib_1_2_8, even though it is not defined as a dependency in fontconfig's tool_dependencies.xml.
@bgruening can you confirm this?

**Comment by hexylena** [comment]
No longer using galaxy dependency packages since we've switched to conda, so closing this issue.
