### ISSUE TITLE
name on workflow card should use the full width

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17746]
I think longer workflow names are not unusual and should be well supported. The empty space does not seem to serve any other purpose.

![Screenshot 2024-03-14 at 10 44 39 PM](https://github.com/galaxyproject/galaxy/assets/1814954/c14b39a0-7bdb-4d46-88b7-78d66d07a816)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0

**Browser and Operating System**
Operating System:,, macOS
Browser:, Chrome,

**Comment by itisAliRH** [comment]
#17721 fixes this!

**Comment by martenson** [comment]
@itisAliRH woohoo, two birds with one stone!
