### ISSUE TITLE
silence "Cannot copy to the same history" error

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#17743]
When you accidentally drag something in the history panel, even a millimeter, you will get a big red warning `Cannot copy to the same history`. I think this error should be either silent (as it was in 23.2), or dragging should be enabled only when there are actual targets to drag to.

![Screenshot 2024-03-14 at 9 26 34 PM](https://github.com/galaxyproject/galaxy/assets/1814954/f8609f5b-f505-4b0b-b17e-1593e97e9adc)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0

**Browser and Operating System**

Operating System:,, macOS
Browser:, Chrome,-,

**Comment by jdavcs** [comment]
The box you drag looks as if it's meant to be draggable, and the little arrow disappears from it when it's dragged off the history panel, and then reappears when the box is dragged back onto the history panel OR when it's dragged onto the activity bar. All these visual cues imply some functionality via dragging, which is misleading.

**Comment by ahmedhamidawan** [comment]
As a bug fix for 24.0, I could simply remove this Toast.

For the next release, we could add a composable(?) that references the `eventStore` (which stores all possible, current drop targets), and handles drag and drop within the same file for multiple types of targets (histories, activity bar, tool form input etc.).
... or something else but it would have to be a proper refactor
