### ISSUE TITLE
[right click] on workflows download button should be disabled

### ISSUE THREAD

**Issue by tcollins2011** [galaxyproject/galaxy#17740]
**Describe the bug**
In reference to #17529. Functionality was added to allow for users to right click buttons in the workflow to allow them to open workflows in a new tab. This same functionality was added to the download button, however this functionality isn't need as a download can't be opened in a new tab. It should be treated the same as actions like the copy button on the workflow cards. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy version 24.0.rc1, commit [79aaf26c61755e4102f636b652c4356ace0af7eb]

**Browser and Operating System**
Operating System: Windows
Browser: Chrome

**To Reproduce**
1. Go to the workflow cards
2. Right click on download

**Comment by martenson** [comment]
Right click on the download button allows you to save the url to the workflow and fetch it elsewhere or using something other than a browser. This is a common usage pattern and should be supported site-wide.
