### ISSUE TITLE
Enhancement: Tool panel search: If a tool is included in a tool group, let the tool be found with a search by the group label

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#17741]
**Describe the bug**
When hunting for a tool, you might just remember the tool group label. Right now, searching with that label may or may not find the tools sorted inside of it.

Example: Mothur tools

**Galaxy Version and/or server at which you observed the bug**
any 23.+

**Browser and Operating System**
any

**To Reproduce**
1. Type they keyword "mothur" into the tool panel search
2. See very short listing
3. Reset search to default, and locate Mothur tool group
4. See very long listing 

**Expected behavior**
Find all tools from a particular software package, especially if nested under a common tool group. This may be all that is remembered by a user.

**Screenshots**
![Screen Shot 2024-03-14 at 3 08 22 PM](https://github.com/galaxyproject/galaxy/assets/8999735/582a10dc-6d41-4c0c-841d-605f6d561242)

..
..
![Screen Shot 2024-03-14 at 3 08 46 PM](https://github.com/galaxyproject/galaxy/assets/8999735/934d3df7-5f3e-44c9-968a-a93171d6e1e0)

**Additional context**

**Comment by ahmedhamidawan** [comment]
Maybe adding a `section:` (e.g.: `section:Mothur`) filter could be useful here?
