### ISSUE TITLE
Subworkflows still listed in Invocations List?

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#17760]
**Describe the bug**
I would now not expect `InvocationsList` to show subworkflow invocations because of the change in [Filter out subworkflow invocations 17558](https://github.com/galaxyproject/galaxy/pull/17558)
**To Reproduce**
1. Run a workflow with subworkflows
2. Go to Invocations List
3. Subworkflow-runs will be listed along with the parent workflow invocation

**Expected behavior**
Only the parent workflow invocation should be listed

**Screenshots**

https://github.com/galaxyproject/galaxy/assets/78516064/06b6d02c-24e6-44c1-9269-f3ca011d26d9

**Comment by jdavcs** [comment]
Fixed in #17768
