### ISSUE TITLE
Issues with phylogenetic visualisations

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#17770]
reproduced on eu/au, org wasn't processing uploads so I didn't test there. Browser: firefox 123.0 on fedora 39.

Here is a test file, ensure it's uploaded as newick.

```
((A.olssoni:0.112038213,(A.etheridgei:0.077847429,A.insolitus:0.099160118)1.000:0.024772158)0.822:0.007599289,(A.lucius:0.114136163,Chamaeleolis.barbouri:0.118480033)0.586:0.005775392,(((C.guamuhaya:0.024946956,C.chamaeleonides:0.026488992)1.000:0.091753615,(A.cuvieri:0.087918462,(A.barahonae:0.087645713,A.christophei:0.085645099)0.877:0.009676737)0.888:0.009321961)0.999:0.015032072,(((A.equestris:0.103238807,((A.bartschi:0.087882157,A.vermiculatus:0.081615308)0.998:0.022831987,(A.bahorucoensis:0.114628815,(A.aliniger:0.096918912,A.coelestinus:0.111900872)0.548:0.010531312)0.818:0.006263403)0.748:0.004423624)0.988:0.008963502,(((A.luciae:0.097183457,(A.aeneus:0.057932967,A.richardi:0.058294848)1.000:0.054211298)0.947:0.011584592,(P.nicefori:0.119707992,(A.agassizi:0.079919230,A.microtus:0.086638718)0.998:0.023100142)0.768:0.007101350)1.000:0.020273023,(A.occulatus:0.161429665,(Diplolaemus.darwinii:0.149865535,Phenacosaurus.acutirostrus:0.163660606)1.000:0.036169405)0.574:0.007888565)0.562:0.002582237)0.984:0.007116887,((((A.ophiolepis:0.063383823,A.sagrei:0.061326694)1.000:0.061901936,(A.ahli:0.130768717,((A.equestris2:0.095626231,(A.lineatopus:0.094517009,(A.garmani:0.068897703,A.grahami:0.070781870)1.000:0.027292044)0.497:0.003194941)0.789:0.006371042,(A.lineatus:0.119506403,(A.humilis:0.108520576,A.limifrons:0.112707887)1.000:0.032102291)0.856:0.007943537)0.565:0.010009344)0.601:0.003367963)1.000:0.016218863,((A.bimaculatus:0.104052329,A.wattsi:0.120945126)1.000:0.021146312,((A.brevirostrus:0.096195412,A.distichus:0.086715856)1.000:0.031901490,((Anolis.acutus:0.073619066,A.stratulus:0.064936661)1.000:0.042173701,(A.cristatellus:0.108876325,A.krugi:0.093885183)0.711:0.008361383)0.935:0.009380725)0.887:0.006534556)0.997:0.010828447)0.817:0.003474513,((A.marcanoi:0.122583051,A.strahmi:0.103072538)1.000:0.034296759,((A.alutaceous:0.093801894,A.vanidicus:0.104620885)1.000:0.027894002,(((A.carolinensis:0.052821752,A.maynardi:0.054087446)1.000:0.040905560,(A.loysiana:0.082301718,A.pumilis:0.102100608)0.892:0.010585964)0.867:0.007299079,(A.sheplani:0.134340536,(A.angusticeps:0.050230864,(A.paternus:0.008572260,A.paternus2:0.007116451)1.000:0.046652380)1.000:0.058212520)0.741:0.004669230)0.994:0.011884993)0.904:0.009869425)0.507:0.001600325)0.860:0.003296602)0.608:0.001603994)0.394:0.000846665);
```

## phyloviz

(occurs on eu+au)

- [ ] phyloviz opens in the `_top`, why? I've lost my place now :(
- [ ] The layout is hard to read ![image](https://github.com/galaxyproject/galaxy/assets/458683/c03ac24a-982d-449a-ad29-6a5425f23ea9)
- [ ] hovering over a node shows `<br>` in the label
- [ ] if there's a search button I can't click it
    ![image](https://github.com/galaxyproject/galaxy/assets/458683/319630c0-37be-47a1-a572-6a8b820b7e1d)

## phylogenetic tree visualisation

- [ ] Doesn't load at all on AU (ping @cat-bro)
- [ ] Switching between each of these visualisation options on EU seems to have no effect. (ping @bgruening @mira-miracoli @sanjaysrikakulam)

    ![Screenshot 2024-03-18 at 11-07-02 Galaxy](https://github.com/galaxyproject/galaxy/assets/458683/1b4f69ad-3628-4094-a0b5-3cbe50759569)

**Comment by neoformit** [comment]
@dannon I'm going to look into the "not loading on AU" issue - please let me know if this overlaps with anything you're doing here?

**Comment by hexylena** [comment]
oh cheers @neoformit, i can ping ya in the future. (this was tested due to the aus biocommins phylo tutorial pr that's open so, sure they'd appreciate it working). Let me know if you need any more information

**Comment by neoformit** [comment]
Sorry I got swamped with other jobs and this keeps getting pushed back on my `todo` list...

**Comment by cat-bro** [comment]
Galaxy Australia has just upgraded to release_24.1 and we can now load the Phylogenetic Tree Visualization. I can't comment on any of the style issues but our issue was that it wouldn't load at all, and now it does which is a plus! https://usegalaxy.org.au/u/cat-bro/h/test-phylo-post-241

**Comment by wm75** [comment]
@cat-bro seems to be working fine without any styling issues.

Those are also fixed on Galaxy Europe now (although we don't know exactly how).

**Comment by nsoranzo** [comment]
@hexylena Given the above comments, can this be closed?

**Comment by hexylena** [comment]
PhyloViz seems gone, not sure if that's "fixed" but, i guess that's one interpretation.

Phylogenetic tree viewer indeed functions now in my testing :woman_shrugging: unsettling.
