### ISSUE TITLE
Sections don't show up properly in run-workflow on >=16.01

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1780]
Workflow editor

![selection_571](https://cloud.githubusercontent.com/assets/458683/13260615/db6e69e6-da21-11e5-8990-686e67ad30ba.png)

Run workflow

![selection_572](https://cloud.githubusercontent.com/assets/458683/13260616/db70dfe6-da21-11e5-87ea-b83c03e0cb35.png)

Tool used in #1779

**Comment by guerler** [comment]
xref: https://github.com/galaxyproject/galaxy/issues/927 and https://github.com/galaxyproject/galaxy/issues/1132 just fyi.

**Comment by hexylena** [comment]
Still a bug, fyi.

**Comment by hexylena** [comment]
xref #2077?

**Comment by martenson** [comment]
needs backport to 16.01
