### ISSUE TITLE
HTML sanitise gives 404

### ISSUE THREAD

**Issue by alpapan** [galaxyproject/galaxy#17800]
**Describe the bug**
This happens for all tools with HTML previews:

For the past few weeks, when I turn on sanistise HTML, it gives me a 404 for any file.
When I have it turned off, then is displayed (but satinised)

The dataset does actually exist on the disk and galaxy clearly finds and displays when sanitise is off.
What could be the reason for the 404?

i haven't changed my Apache settings at all.
Not sure what I should do/look at?

![Screenshot 2024-03-21 010455](https://github.com/galaxyproject/galaxy/assets/608484/a4306104-fd0d-4b00-9a36-856c79a0f6dd)
![Screenshot 2024-03-21 010427](https://github.com/galaxyproject/galaxy/assets/608484/9c919ea2-abef-4793-b7ff-cbfd7b8862a6)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: "version_major": "23.1",
    "version_minor": "5.dev0" 
Commit: 4b3bc55067d27bdf0d00dd7039ace0e8e56329d3

**Additional context**

apache
```
        ProxyRequests        Off

        AllowEncodedSlashes        NoDecode
        AddOutputFilterByType DEFLATE text/html text/plain text/xml
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE application/x-javascript application/javascript application/ecmascript
        AddOutputFilterByType DEFLATE application/rss+xml
        AddOutputFilterByType DEFLATE application/xml
        AddOutputFilterByType DEFLATE application/json

         <Location />
                Options Indexes FollowSymLinks MultiViews
                Order allow,deny
                allow from all

                # because we are serving the proxied pages via HTTPS:
                RequestHeader set X-URL-SCHEME https

                RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}

#               here we offload the work to the hill apache server instead of lazebnik galaxy
                RewriteEngine on
                RewriteRule ^/static/style/(.*) /var/www/galaxy/static/june_2007_style/blue/$1 [L]
                RewriteRule ^/static/scripts/(.*) /var/www/galaxy/static/scripts/packed/$1 [L]
                RewriteRule ^/static/(.*) /var/www/galaxy/static/$1 [L]
                RewriteRule ^/favicon.ico /var/www/galaxy/static/favicon.ico [L]
                RewriteRule ^/robots.txt /var/www/galaxy/static/robots.txt [L]
                # Cache on client, see /static location
                SetOutputFilter DEFLATE
                SetEnvIfNoCase Request_URI \.(?:gif|jpe?g|png)$ no-gzip dont-vary
                SetEnvIfNoCase Request_URI \.(?:t?gz|zip|bz2)$ no-gzip dont-vary
                SetEnvIfNoCase Request_URI /history/export_archive no-gzip dont-vary

                SetEnv proxy-nokeepalive 1
                SetEnv proxy-sendchunks 1

                # allow apache to handle data upload/download
                # in order for this to work, we need access to the lazebnik scratch, so no do not do this
                XSendFile on
                XSendFilePath /

        </Location>

        <Location "/api">
             Satisfy Any
             Allow from all
        </Location>


```

**Comment by alpapan** [comment]
I still haven't resolved it except verifying that 
- there are no errors reported to my web proxy (logging to trace).
- Setting console logging to TRACE doesn't glean any information.
- therefore issue seems to be API communicating to galaxy internally, not to the browser
- this white blank page happens consistently for all datasets not satitised (including PDF and text)


any ideas what i can do to figure it out please?

**Comment by mvdbeek** [comment]
Have you checked out the instructions in https://docs.galaxyproject.org/en/master/admin/apache.html?  in particular the section that starts with

> For this to work, the user under which your Apache server runs will need read access to Galaxy’s files_path directory (by default, database/files/) and its contents. ...

**Comment by alpapan** [comment]
> Have you checked out the instructions in https://docs.galaxyproject.org/en/master/admin/apache.html? in particular the section that starts with
> 
> > For this to work, the user under which your Apache server runs will need read access to Galaxy’s files_path directory (by default, database/files/) and its contents. ...

Hello

This helped fix another problem so thank you (below)! But one it still doesn't resolve my main issue.

I believe you're referring to the section titled "Sending Files With Apache", which is not the problem i'm facing. 

FWIW, 
1) the download works fine, it's just the display
2) the galaxy error's had nothing even with log DEBUG.

This is the comment I was writing thinking that the solution was the NFS export.

It gives information of what I did but i'm still at a loss.


>Yes i had followed the instructions but the instructions assumed both the galaxy and the apache live in the same box (which is >never good from a security PoV). So I had to do implement a solution with an NFS export.
>I had recently moved the Galaxy database to a more performant NFS and forgot to update the web server's fstab
>
>FWIW, this may be of use to people who don't host their webserver and galaxy on the same box. 
> (in case you'd like to add it to instructions)
>
> in galaxy.yml set umask to allow for groups `  umask: '007'`
> run `chmod -R g+r /mnt/to/galaxy/database && find /mnt/to/galaxy/database -type d -exec chmod g+x '{}' \;`
>On NFS server, add to /etc/exports
>```
>/mnt/to/galaxy/database WEBPROXYY_IP(ro,root_squash,async,no_subtree_check)
>```
>Reload exports via `systemctl reload nfs-server.service`
>
>on web server 
> add www-data (or similar) to the galaxy group
> add to /etc/fstab
>```
>NFS.server.ip:/mnt/to/galaxy/database /mnt/to/galaxy/database nfs4 ro,rsize=32768,wsize=32768,intr,noatime 0 0
>```
> mount /mnt/to/galaxy/database
>
>Note that the mount must be identical to galaxy_root and the /mnt/to/galaxy does not need to be mounted.
>
> Troubleshooting: 1) clear browser cache 2) Go to the details of a dataset and make sure file is not purged 3) get the 'Full Path' entry
> e.g. `/mnt/to/galaxy/database/objects/b/5/2/dataset_b522b814-2732-4bb6-ab36-17fd404e1d0a.dat`
> do: `sudo -u www-data file /mnt/to/galaxy/database/objects/b/5/2/dataset_b522b814-2732-4bb6-ab36-17fd404e1d0a.dat`
>>```
>>/mnt/to/galaxy/database/objects/b/5/2/dataset_b522b814-2732-4bb6-ab36-17fd404e1d0a.dat: HTML >>document, ASCII text, with very long lines
>>```

**Comment by alpapan** [comment]
Found it.

1) it was the missing NFS as above
2) i had deleted XSendFilePath from my apache config when i was trying to figure it out but had left the `apache_xsendfile: true`

Please note the documentation does not talk about this being an issue for viewing non-sanitised files (like HTML). As I had no issues downloading, it wasn't obvious i should be looking at that.

Also here is my Apache conf in case it helps a future reader (as the one on the docs is for a proxy on the galaxy server):

```
        DocumentRoot /var/www/galaxy/
        KeepAlive Off
        SetEnv proxy-nokeepalive 1
        SetEnv proxy-sendchunks 1

        ProxyPreserveHost On

        ProxyPass / http://lazebnik:16039/ connectiontimeout=1200
        ProxyPassReverse / http://lazebnik:16039/ connectiontimeout=1200
        ProxyRequests        Off

        AllowEncodedSlashes        NoDecode

        SSLEngine on
        ProxyTimeout 2400
        Timeout 2400

        SetOutputFilter DEFLATE
        AddOutputFilterByType DEFLATE text/html text/plain text/xml
        AddOutputFilterByType DEFLATE text/css
        AddOutputFilterByType DEFLATE application/x-javascript application/javascript application/ecmascript
        AddOutputFilterByType DEFLATE application/rss+xml
        AddOutputFilterByType DEFLATE application/xml
        AddOutputFilterByType DEFLATE application/json
        SetEnvIfNoCase Request_URI \.(?:gif|jpe?g|png)$ no-gzip dont-vary
        SetEnvIfNoCase Request_URI \.(?:t?gz|zip|bz2)$ no-gzip dont-vary
        SetEnvIfNoCase Request_URI /history/export_archive no-gzip dont-vary
        SetEnvIfNoCase Request_URI \.(?:woff2?)$ no-gzip dont-vary

        RequestHeader set X-URL-SCHEME https
        RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
        RewriteEngine on
        RewriteRule ^/favicon.ico /static/favicon.ico [L]
        RewriteRule ^/robots.txt /static/robots.txt [L]

        <Location />
                Options -Indexes
                Satisfy Any
                Allow from all
                Require all granted
                XSendFile on
                XSendFilePath /
        </Location>

        <Location /static>
                Options -Indexes
                Satisfy Any
                Allow from all
                Require all granted
                ExpiresActive On
                ExpiresDefault "access plus 24 hours"
                ProxyPass !
        </Location>

        <Location "/config/plugins/(.+)/(.+)/static">
                Options -Indexes
                Satisfy Any
                Require all granted
        </Location>
        RewriteRule ^/plugins/(.+)/(.+)/static/(.*)$ /config/plugins/$1/$2/static/$3 [L]
```

For performance, in this config, the /static is served from the web proxy directly rather than having to be taken from the galaxy server. This requires the DocumentRoot to have the static folder copied from the galaxy server.

```
rsync -purl -a galaxy_server:/mnt/to/galaxy/static /var/www/galaxy/
```

**Comment by dannon** [comment]
@alpapan Glad you sorted it out, thanks for the detailed followup here in consideration of future readers!  :)
