### ISSUE TITLE
DATA_FETCH tool uses a large amount of RAM when autodetecting qza datatype

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#17827]
**Describe the bug**
DATA_FETCH jobs run out of memory. The jobs that use excessive memory are autodectecting the data types, particularly from local files with .qza extensions. We have raised the amount of memory allocated to 12GB per job and this is still not enough for some jobs.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Australia, release_23.1
Commit: a3c14ea

**Comment by mvdbeek** [comment]
This is fixed in https://github.com/galaxyproject/galaxy/pull/17679 and the preceding PRs. I'll backport this further but would encourage you to update to 23.2.
