### ISSUE TITLE
Simplify workflow sharing menu

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1782]
![selection_577](https://cloud.githubusercontent.com/assets/458683/13261325/3172336a-da25-11e5-8024-f1733dd2f46c.png)

"Share and Publish" and "Download and export" could easily be merged into a single page. I wanted to make a workflow publicly available (via workflow .ga format, whilst running on my local computer) and was sitting there thinking "Wait... where's the download button?" (as my caffeine hadn't quite sunk in yet).

**Comment by dannon** [comment]
See #2060
