### ISSUE TITLE
Toolshed tool installation interface in Admin panel unreachable

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#17855]
**Describe the bug**
Attempting to access the tool installation interface through the Admin panel throws a 504 timeout exception.

**Galaxy Version and/or server at which you observed the bug**
Current dev.

**To Reproduce**
1. Go to 'Admin'
2. Click on 'Install and Uninstall'
4. Notice the 504 Timeout exception in the center panel

**Expected behavior**
The list of tool categories should be displayed.

**Screenshots**
<img width="669" alt="image" src="https://github.com/galaxyproject/galaxy/assets/2105447/cd4d43d6-5266-42d8-aa00-3c7dc329b485">

**Additional context**
This is not a new issue but seems to happen much more often recently.

**Comment by martenson** [comment]
I wasn't able to reproduce yet. Do you have any detail in the log about what times out? I assume that is the proxied request to actual TS?

**Comment by guerler** [comment]
Closing this, caused likely due to default server timeout settings and not related to Galaxy.
