### ISSUE TITLE
Workflow editor and tool form inconsistency on data input format parsing

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#17864]
In the case were a tool has a space in the list of input formats (not proper formatting), the tool form will still parse the list and accept all listed formats, leading to it passing tool tests if not caught manually. The workflow editor does not parse in the same way and does not acknowledge formats other than the first as valid, and disallows a connection. To the user, this problem is also not explained and simply looks like it is disallowing a valid input.

![20240328_165327](https://github.com/galaxyproject/galaxy/assets/40246333/b26525e7-22f8-4667-99cb-8c277c363501)

**Comment by mvdbeek** [comment]
Got an example ?

**Comment by astrovsky01** [comment]
Well until such time as the fix was merged, I would have pointed at pretextgraph...
