### ISSUE TITLE
Saving user `Preferences->Manage Information` crashes the tab

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#17862]
**Describe the bug**

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Linux
Browser: Chrome

**To Reproduce**
1. Go to User -> Preferences -> Manage Information
2. Click on Save
3. The tab freezes and displays only the middle panel and masthead

**Expected behavior**
No freeze

**Screenshots**
![image](https://github.com/galaxyproject/galaxy/assets/46503462/fb215094-e10d-458e-b63f-82833f6ac89c)

**Comment by martenson** [comment]
I've reproduced this a couple of times, once even with loading just `/user` without any interaction with the "manage information" settings. However I cannot reproduce this reliably locally, and cannot reproduce at all on Main.

**Comment by martenson** [comment]
I suspect the console errors are a red herring, xref https://github.com/galaxyproject/galaxy/pull/17865

**Comment by martenson** [comment]
it keeps creating DOM nodes ad infinitum
![Screenshot 2024-03-28 at 4 58 53 PM](https://github.com/galaxyproject/galaxy/assets/1814954/4efce4fb-cf86-4032-9df4-85a4f7a5b8d5)

**Comment by martenson** [comment]
after saving, the page sets window.location to `/user` and while loading that page the crash occurs

https://github.com/galaxyproject/galaxy/blob/99aec81ee4788e4846b08f361caaeebda9dd9faf/client/src/components/Form/FormGeneric.vue#L117-L119
