### ISSUE TITLE
Datalibrary import failed 

### ISSUE THREAD

**Issue by pavanvidem** [galaxyproject/galaxy#1787]
I tried to import a dataset from a data library, while viewing it. The error raised was "Dataset not imported. Malformed id (undefined) specified, unable to decode. But it works, if I go one step back in the path, select the dataset and import. 
Screenshot attached. 
![screenshot from 2016-02-24 10 13 44](https://cloud.githubusercontent.com/assets/5268277/13280789/4ae7aa30-dae0-11e5-9560-8c25b9436d9b.png)

Thanks,
Pavan

**Comment by dpryan79** [comment]
This can presumably be closed, it was fixed here: https://github.com/galaxyproject/galaxy/pull/2190 (I happen to have just run into this same problem).

**Comment by martenson** [comment]
thanks for the reminder @dpryan79
