### ISSUE TITLE
Run button in workflow editor triggers save, loses workflow report

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#17903]
I've traced this to https://github.com/galaxyproject/galaxy/blob/661d93ab2aedac3c8bde3e3537d54d89a83278bf/client/src/components/Workflow/Editor/Index.vue#L592. This seems wrong to do, we should not save the workflow when the user has not requested to save it. Secondary bug here (and how @abueg spotted this) is that the workflow report is lost.

Here's @abueg's video:

https://github.com/galaxyproject/galaxy/assets/6804901/07b6312e-309e-4cd2-8ddc-6b47f3f4cda2

Note that there's a tool version mismatch as well ... this doesn't happen if all tool versions are installed. Nevertheless this is a pretty bad bug.

**Comment by ahmedhamidawan** [comment]
> I've traced this to https://github.com/galaxyproject/galaxy/blob/661d93ab2aedac3c8bde3e3537d54d89a83278bf/client/src/components/Workflow/Editor/Index.vue#L592. This seems wrong to do, we should not save the workflow when the user has not requested to save it....

That `onSave()` call is inside the function `routeToWorkflow` which is only ever called from the `doSaveAs` and `onCreate` methods: so it is highly unlikely that that call is being made in the case of this screencast?

Why do we have that `onSave` call when we create or save as a workflow: The idea is that we are at that point creating a new workflow, so we change the current `id` in the component and _then_ save whatever changes the user has there and scope everything to this new id; meaning at that point the user already knows they are creating a new workflow so there wouldn't be any need to reinform the user that the workflow is being saved.

**Comment by ahmedhamidawan** [comment]
I think where this originates is actually:
https://github.com/galaxyproject/galaxy/blob/661d93ab2aedac3c8bde3e3537d54d89a83278bf/client/src/components/Workflow/Editor/Index.vue#L680-L684

where `onNavigate` is called when you run a workflow.

This instead should only save IF the user has changes; and in the case that it does save, it should definitely inform the user of it

**Comment by mvdbeek** [comment]
Yeah, there should be a dialog if there are changes, and you can either discard them or save

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/17907 and https://github.com/galaxyproject/galaxy/pull/17904
