### ISSUE TITLE
[feature-request] import this history, what happens next?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#17933]
![image](https://github.com/galaxyproject/galaxy/assets/458683/e44569ee-0afc-4cff-8a0f-c151cc037d28)

when I click "import this history", there's a popup that does some work and then disappears but no notice, no link to click, no "next action". Where has it gone? I clicked thrice before understnd it was copying and setting it as my active history and there wasn't an error but I should instead go back to the home page.

maybe a popup here would be useful?

**Comment by dannon** [comment]
@jennaj reported this too, and I believe we even briefly discussed it at a UI/UX meeting, but I can't find the relevant issue to link up.  Anyone recall it?
