### ISSUE TITLE
``CONVERTER_gz_to_uncompressed`` can create invalid datatypes

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#17938]
If a user forces an incompatible input dataset in, e.g. fastqsanger. Then we end up with fastsan, because of https://github.com/mvdbeek/galaxy/blob/b971e332634b9b2ccaa6e3a31c019278789c078b/lib/galaxy/datatypes/converters/gz_to_uncompressed.xml#L9 

Noticed in https://sentry.galaxyproject.org/share/issue/084f2ebb62bd44ae83ebcc6bdd760956/

Maybe we could add a datatype.uncompressed_extension property or something like it, and if it doesn't exist fall back to `data`.

**Comment by nsoranzo** [comment]
I guess a small improvement can be:

```
'vcf' if $input1.ext == 'vcf_bgzip' else input1.ext[0:-len('.gz')] if input1.ext.endswith('.gz') else input1.ext
```

**Comment by mvdbeek** [comment]
Can you PR that ? I think that's a good option.

**Comment by nsoranzo** [comment]
Sure

**Comment by nsoranzo** [comment]
@mvdbeek What Galaxy version should I target?

**Comment by mvdbeek** [comment]
23.0 I guess is the last supported one ?
