### ISSUE TITLE
Cannot scramble/build pbs_python (Exception class EggNotFetchable cannot be imported)

### ISSUE THREAD

**Issue by OliPelz** [galaxyproject/galaxy#1795]
Dear developers,

I am trying to scramble the pbs_python module using the instructions found [here](https://wiki.galaxyproject.org/Admin/Config/Performance/Cluster). 
I am using the latest master branch 6a47d2d3a7f27b659e5de5fb1b37c7c1f9d04302
Virtualenv has been set up correctly, here is my commandline:

``` bash
cd galaxy
python scripts/scramble.py -e pbs_python
```

The following error message occurs:

``` bash
Traceback (most recent call last):
  File "scripts/scramble.py", line 22, in <module>
    from galaxy.eggs.scramble import ScrambleCrate, ScrambleFailure, EggNotFetchable
ImportError: cannot import name EggNotFetchable
```

The import of the other classes ScrambleCrate, ScrambleFailure seem to work, if I do manually:

``` bash
python -m pdb scripts/scramble.py -e pbs_python
```

and debug the following content, which runs without a problem:

``` bash
import os
import sys
lib = os.path.abspath( os.path.join( os.path.dirname( __file__ ), os.pardir, "lib" ) )
sys.path.insert( 1, lib )
from galaxy.eggs.scramble import ScrambleCrate, ScrambleFailure
```

If I add the following line afterwards:

``` bash
from galaxy.eggs.scramble import EggNotFetchable
```

I get the same error message as above:

``` bash
*** ImportError: cannot import name EggNotFetchable
```

The EggNotFetchable class is defined in the `__init__.py` file and not in the `scramble.py` file as the other two classes, which may be the problem?

``` bash
grep "ScrambleCrate\|ScrambleFailure\|EggNotFetchable" lib/galaxy/eggs/scramble.py
```

vs.

``` bash
grep "ScrambleCrate\|ScrambleFailure\|EggNotFetchable" lib/galaxy/eggs/__init__.py
```

Thank you for your help.
Oliver

**Comment by natefoo** [comment]
Hi @OliPelz,

As of Wednesday (Feb 24), release 16.01 is out, which replaces eggs with wheels. I would suggest updating to this release.

**Comment by OliPelz** [comment]
Dear @natefoo,

Thanks! Upgrading to 16.01 worked like a charme for building pbs_torque!

**Comment by balaszone** [comment]
Hi Oliver/Nate,

I have the latest version of galaxy too but having difficult time building pbs_python. Could one of you help me figure what i'm doing wrong?

After I modify my job_conf.xml file to reflect 'pbs', I cannot start the galaxy server successfully.
This is the error I'm getting.
.
.
. . AssertionError: The Python pbs-python package is required to use this feature, please install it or correct the following error: ImportError /hpcdata/galaxy/.venv/lib/python2.7/site-packages/pbs/_pbs.so: undefined symbol: pbs_submit_hash_ext

Advice plz..

Tx,
B

**Comment by natefoo** [comment]
@balaszone Beware the pbs-python package on PyPI, this includes some compiled artifacts that most likely won't work on all platforms.

I'd suggest the following instead:
1. Uninstall pbs_python with `pip uninstall pbs-python`
2. Fetch the pbs_python source from https://oss.trac.surfsara.nl/pbs_python
3. Activate the Galaxy virtualenv with `. /path/to/galaxy/.venv/bin/activate`
4. In the pbs_python source, run `python setup.py install`
