### ISSUE TITLE
Connections vanish when upgrading a subworkflow

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#17986]
**Describe the bug**
When I upgrade a subworkflow, all the connections in the workflow disappear. They are still there but invisible. I have to reload the page to make them reappear.
The bug  doesn't happen the very first time it upgrades after the creation of the workflow, but every subsequent time.

**Galaxy Version and/or server at which you observed the bug**
Observed on main and on eu

**Browser and Operating System**
Operating System: macOS
Browser: Chrome and Safari

**To Reproduce**
1. Edit https://usegalaxy.org/u/delphinel/w/vanishing-connections
2. Click on 'Test Subworkflow'
3. Upgrade the subworkflow

**Screenshots**

https://github.com/galaxyproject/galaxy/assets/11195061/6bf174cf-a9e7-4f41-8f7e-e679b8004439

**Additional context**

**Comment by dannon** [comment]
@ElectronicBlueberry Do you think you could take a look at this one?

**Comment by bgruening** [comment]
@dannon Laila is on vacation this week. If it can wait until next week I'm sure she can have a look.

**Comment by ElectronicBlueberry** [comment]
fixed in #18107
