### ISSUE TITLE
RemoteFileSources should provide better exceptions

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#17993]
There are several pyfilesystem2 errors for which we can be more specific, such as PermissionDenied (see https://github.com/PyFilesystem/pyfilesystem2/blob/master/fs/errors.py). It would be good if we can just raise a MessageException style exception.

Exceptions like these are quite common in our logs:
https://sentry.galaxyproject.org/organizations/galaxy/issues/143340/?project=3&query=is%3Aunresolved&referrer=issue-stream

**Comment by davelopez** [comment]
I'm currently planing to work on fixes and improvements in file sources so I'll take this one :+1:

**Comment by davelopez** [comment]
Should be mostly fixed in https://github.com/galaxyproject/galaxy/pull/18027
