### ISSUE TITLE
Rstudio has crashed and I can't open a new one

### ISSUE THREAD

**Issue by marc0911** [galaxyproject/galaxy#17994]
**Describe the bug**
I was running some analyses in Rstudio on the EU server and when i wanted to check if it was finished I got the following error on the webpage : ERR_TOO_MANY_REDIRECTS

Since then the job as turned green in my history and there is no more active interactive tools available. 
When I try reruning RStudio it remains in queue and in the active interactive tools tab it says it has been stopped.

**Browser and Operating System**
Operating System:  macOS
Browser: Chrome

I would like to know if there is any way I can get back to the same Rstudio session as I generated some data already and didn't download it yet.

**Comment by davelopez** [comment]
Hi @marc0911! Thanks for reaching out. 

Server-specific issues should go to the Help forum, in your case, in particular to the EU support sub-forum. 
Here is the link: https://help.galaxyproject.org/c/usegalaxy-eu-support/6 please report there.

Thanks!
