### ISSUE TITLE
depot.galaxyproject.org can't be reached

### ISSUE THREAD

**Issue by trev-f** [galaxyproject/galaxy#18015]
**Describe the bug**
depot.galaxyproject.org can't be reached, and images cannot be downloaded from site URLs.

**Galaxy Version and/or server at which you observed the bug**
N/A

**Browser and Operating System**
Operating System: Windows
Browser: Chrome-based

**To Reproduce**
1. Go to depot.galaxyproject.org
2. See error

**Expected behavior**
Website can be reached and images can be downloaded.

**Comment by nsoranzo** [comment]
@trev-f Seems to work for me, can you check again?

**Comment by trev-f** [comment]
@nsoranzo Thank you, works for me now as well.
