### ISSUE TITLE
Tool errors related to empty result files

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1804]
**Issue** 

When certain tools have empty result output datasets (perhaps intermediate), downstream processes that consume that output, expecting inputs/return info, trigger a job failure because the expected dataset is "not found" (doesn't exist?).

**Where**

Main: Stampede and Roundup. Could be cluster related (Nate suggested that). But if does turn out to be tool specific, open tickets for these tools below for fixes.

**Examples**

**Iterative mapping**

Shared history with testing:  https://usegalaxy.org/u/jen/h/test-iterative-mapping-2 

The option _Minimum requirement of read length for mapping_ is definitely involved in the failure trigger. 21 fails, 15 success. The query fasta input has sequences that range in length from 10 to over 80 bases. Is a round of mapping producing empty files, then triggering error (?).

> info url: https://usegalaxy.org/datasets/X/show_params
> job id: X
> tool id: toolshed.g2.bx.psu.edu/repos/tyty/structurefold/iterative_map_pipeline/1.0
> tool version: 1.0
> job pid or drm id: X.roundup
> ## job tool version:
> 
> job command line:
> ## python /galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/tyty/structurefold/7bb98e9296e9/structurefold/Iterative_mapping/iterative_map.py fasta /galaxy-repl/main/files/X/dataset_X.dat /galaxy-repl/main/files/X/dataset_X.dat 1 20 five_end user /galaxy-repl/main/files/X/dataset_X.dat 3 0 0 1 0 -1 0
> 
> job stderr:
> 
> Usage:   samtools merge [-nr] [-h inh.sam] <out.bam> <in1.bam> <in2.bam> [...]
> 
> Options: -n       sort by read names
>          -r       attach RG tag (inferred from file names)
>          -u       uncompressed BAM output
>          -f       overwrite the output BAM if exist
>          -1       compress level 1
>          -R STR   merge file in the specified region STR [all]
>          -h FILE  copy the header in FILE to <out.bam> [in1.bam]
> 
> Note: Samtools' merge does not reconstruct the @RG dictionary in the header. Users
>       must provide the correct header with -h, or uses Picard which properly maintains
>       the header dictionary in merging.
> 
> open: No such file or directory
> [bam_sort_core] fail to open file /galaxy-repl/main/jobdir/X/combine.bam
> open: No such file or directory
> [main_samview] fail to open "sorted.bam" for reading.
> rm: cannot remove `/galaxy-repl/main/jobdir/X/combine.bam': No such file or directory
> rm: cannot remove`/galaxy-repl/main/jobdir/X/sorted.bam': No such file or directory

**Align families**

Oddly, the "error" is a green, sucessful dataset.

<img width="243" alt="screen shot 2016-02-25 at 12 50 22 pm" src="https://cloud.githubusercontent.com/assets/8999735/13333996/819ac6be-dbbe-11e5-847a-f790d9ac0666.png">

> python: can't open file '/align_families.py': [Errno 2] No such file or directory /scratch/X/xcgalaxy/main/staging/X/command.sh: line 40: /galaxy-repl/main/deps/samtools/0.1.18/env.sh: No such file or directory
> 
> Tool: Du Novo: Align families
> Name: Du Novo: Align families on data 16
> Created:  Tue 23 Feb 2016 11:32:31 PM (UTC)
> Filesize: 0 bytes
> Dbkey:    ?
> Format:   tabular
> Galaxy Tool ID:   toolshed.g2.bx.psu.edu/repos/nick/duplex/align_families/0.3
> Galaxy Tool Version:  0.3
> Tool Version: 
> Tool Standard Output: stdout
> Tool Standard Error:  stderr
> Tool Exit Code:   None
> 
> Input Parameter   Value   Note for rerun
> Input reads   16: Du Novo: Make families on data 13 and data 12  
> Job Resource Parameters   yes 
> Compute Resource  TACC Stampede (beta)

**Comment by hexylena** [comment]
Ugh, yes. We have this exact issue; people hit the bug report on the downstream tool failing which delays helping them.

If we could speficy that a valid output file must have some data, and fail otherwise, that would be perfect. There exist tools which return an empty output and exit successfully with no log messages, but for those tools to really be considered successful, they should have output.

**Comment by jennaj** [comment]
@erasche For these two cases, the empty data and error were generated with one tool. I added in a graphic for the second - the "error" is a green dataset. Inputs all look fine for both tools - although content does seem to be a factor. It seems reasonable that tools like these two could (validly) produce some empty results (no hits). Some tools create a BAM with no content, just headers. Maybe that is the solution? In some way empty results need to be handled by the tool, or cluster, or ?? (not sure what the true issue is - may need to split this one up to be tool specific - waiting for @natefoo to comment after reviewing).

But I agree, the other case happens too. A notice given to the user within the UI that the input is invalid (and why - most can be detected - error, empty, bad format, etc) would be a great enhancement. Should we make another ticket for this idea, so that it is clear (and distinct)?

**Comment by natefoo** [comment]
Specifically with the iterative mapping tool, it is difficult to tell where the error is if the inputs are ok because it uses `os.system()` heavily. Some of these commands (such as the `os.system()` call to `cp`) could be made in to Pythonic versions (e.g. `shutil.copy()`) and the rest ought to use `subprocess.check_call()` so that execution will stop at that step upon failure. As it is currently written, all of the intermediate outputs are cleaned up upon failure, which makes determining what step the tool failed at very difficult. All we know is that `samtools merge` failed, probably because some previous step failed (and was not logged - `log.txt` only contains:

```
[samopen] SAM header is present: 1 sequences.
```

**Comment by jmchilton** [comment]
I was in the middle of responding to this when @natefoo did. I just wanted to say this is a bit sprawling and it would be useful if we could break this down into more specific issues (at least 3 classes that I see here):
- Pulsar (so on usegalaxy.org Stampede jobs) may handle empty files slightly different than Galaxy. If there are any tools that are "red" when empty on local clusters but not on Stampede (or the inverse) - this should be reported as a specific issue to Galaxy or Pulsar issue board.
- If there are particular tools that should never accept empty inputs - the tool wrapper should enforce that right away and provide a clean error message to that end. I have implemented a validator to do that here https://github.com/galaxyproject/galaxy/pull/1808, but @jennaj what you can do is track the tools. Maybe create issues on tools-devteam and tools-iuc for tools that accept empty files and fail with cryptic errors when inputs are empty. After 16.04 is released we can go in and add the new validator to these inputs.
- If there are particular tools that should never produce empty outputs if the run is 'ok' - and the run is still labelled okay after the tool is executed - that is a bug with the tool wrapper. We just need to fix that - again I would just create specific issues on tools-devteam or tools-iuc for these problems.

**Comment by jennaj** [comment]
Thanks @natefoo and @jmchilton - I'll do some more testing roundup vs stampede and break this down into the appropriate tickets, link them here, and close this one out (it is sprawling! the feedback helps to know what to do with it all) :)

**Comment by jmchilton** [comment]
Closing for now, reopen more specific issues as outlined https://github.com/galaxyproject/galaxy/issues/1804#issuecomment-189309187 if this is a still a problem (I suspect there are definitely still places this is a problem).
