### ISSUE TITLE
Comments lost on Workflow Import

### ISSUE THREAD

**Issue by ElectronicBlueberry** [galaxyproject/galaxy#18055]
**Describe the bug**
When importing a workflow via the "Import" button from the workflow share page, a workflows comments are not imported.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0 and dev

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**
1. Share a workflow which contains comments
2. Navigate to the workflows sharing page
3. Click import
4. View the imported workflow

**Expected behavior**
Comments are imported

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/18060, thank you!
