### ISSUE TITLE
Simplified workflow run form warnings are vague

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#18077]
![image](https://github.com/galaxyproject/galaxy/assets/6804901/94def0ca-af81-40c1-a18f-1b46faa8fe54)

We could easily list steps and tools and say what the actual issues are, and maybe offer to allow saving the workflow with those tool state corrections, without visiting the editor.

Also note that we don't allow tool state corrections in the UI (probably for the best in terms of debugging and reproducibility), so the text is misleading ... maybe we need to block submission (or allow tool state corrections ...).

**Comment by ahmedhamidawan** [comment]
Notes from UI meeting:
- Only one message instead of two (the latter implies the first)
- We already show a message in a modal in the workflow editor
- List the actual errors
- Provide a link to the workflow editor
- Maybe disable the run button and force users to go back to the workflow editor?
