### ISSUE TITLE
Drop "Send to cloud" tool and associated cloudauthz code

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#18098]
Opening this to make sure I'm not missing a reason why would need to keep any of this around:

https://github.com/galaxyproject/galaxy/blob/release_24.0/tools/data_export/send.xml and associated authz plumbing should probably be removed. I don't think it ever gained any adoption, there's no test or documentation, and what it is aiming to do we can do with file sources in a more generic way. None of this is needed for https://github.com/galaxyproject/galaxy/pull/15875, but I think it was created specifically for that purpose and doesn't look like it aligns with how we're going to want to bring user-defined object stores and file sources in the future.

Things we can remove:
- https://github.com/galaxyproject/galaxy/blob/release_24.0/tools/data_export/send.xml
- https://github.com/galaxyproject/galaxy/blob/release_24.0/tools/data_export/send.py
- https://github.com/galaxyproject/galaxy/blob/release_24.0/lib/galaxy/webapps/galaxy/api/cloud.py
- https://github.com/galaxyproject/galaxy/blob/release_24.0/lib/galaxy/webapps/galaxy/api/cloudauthz.py
- https://github.com/galaxyproject/galaxy/blob/release_24.0/lib/galaxy/schema/cloud.py
- https://github.com/galaxyproject/galaxy/blob/release_24.0/lib/galaxy/managers/cloud.py
- https://github.com/galaxyproject/galaxy/blob/release_24.0/lib/galaxy/managers/cloudauthzs.py
- https://github.com/galaxyproject/galaxy/blob/release_24.0/client/src/components/User/CloudAuth/*

Removing this would also make it slightly easier to refactor `_get_authnz_backend` and its usage so we can discriminate between real exceptions and expected noise (i.e. we didn't find a disabled provider)

**Comment by dannon** [comment]
Yes, we should clean this up.
