### ISSUE TITLE
Purging users does not work (from bioblend)

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#18104]
**Describe the bug**

The `purge` in `DELETE /api/users/USERID?purge=True` (as initiated when called from bioblend) is currently ignored.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.2

Stange that bioblend has a note on this in the tests https://github.com/galaxyproject/bioblend/blob/b245c40cef50cb6e52f1e113e0352e60573df429/bioblend/_tests/TestGalaxyUsers.py#L28C20-L28C25

**Comment by jdavcs** [comment]
Probable cause: 158944602e00535d997b0d7ac63be980a20b1a1e

Also, see discussion on the dev channel starting [here](https://app.element.io/#/room/#galaxyproject_dev:gitter.im/$g8Yn7-dHITbgUccz6hIGsTri4S62Bh0ysWh4Cli-m-M) (ping @nsoranzo)

**Comment by mvdbeek** [comment]
> Stange that bioblend has a note on this in the tests

You need to configure galaxy to allow purging users, that is not related to this issue.
