### ISSUE TITLE
Include number of columns in preview/sidebar view for tabular data types

### ISSUE THREAD

**Issue by hechth** [galaxyproject/galaxy#18116]
Currently only the number of rows is displayed. It would be great if we could also display the number of columns in the dataset, so having something like `19 lines, 5 columns`.

![image](https://github.com/galaxyproject/galaxy/assets/12066490/6ad9e340-d580-4860-a948-a3eea47fb37a)

**Comment by bernt-matthias** [comment]
The best issues are those that are already solved 😀: have a look here https://github.com/galaxyproject/galaxy/pull/17492 if this is what you intended.

**Comment by hechth** [comment]
Amazing @bernt-matthias ! Thanks a lot!
