### ISSUE TITLE
Cannot switch to purged history / history actions not available

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#18113]
I want to extract a workflow from a purged history. This used to be possible, but it's not now since I can't switch to that history.
Generally speaking I should be able to make a purged history my current history.

**Comment by davelopez** [comment]
I'm going to make `purged` and `archived` histories able to be set as current and then restrict the UI options where appropriate. I can see the value in it. But when I lift the immutable restriction I don't seem to be able to really set purged histories as current. Apparently, this really old condition prevents it:

https://github.com/galaxyproject/galaxy/blob/37aeadd146471061315e24e11525f57fe47f01e6/lib/galaxy/webapps/base/webapp.py#L915

I want to make sure if I should target 24.0 as a fix or if changing this would have other implications that should be moved to `dev`.

**Comment by davelopez** [comment]
Switching to non-active histories should be possible now with https://github.com/galaxyproject/galaxy/pull/18234
Regarding extracting a workflow out of a purged history that is not working, we probably should create a new issue for that if it was working in the past.
