### ISSUE TITLE
Parameter matrix support for workflows and tools

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#1815]
It would be awesome if galaxy supported the definition of parameter matrices or lists of parameters.
Instead of specifying the parameters for each workflow to run, you would enter a range of parameters to try. I think this wouldn't be too hard to implement (one could start by using comma-seperated lists of values), but it would be an enormous benefit if you're doing explorative data analysis in galaxy.

**Comment by bgruening** [comment]
@mvdbeek a related feature is already in Galaxy and called Sweepster: http://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-14-397

**Comment by jmchilton** [comment]
Not exposed in the GUI, but the API does allow tool execution to do this: https://github.com/galaxyproject/galaxy/blob/dev/test/api/test_tools.py#L414. We are planning some extensions to the workflow running API as part of 16.04 to enable the new tool form - I will try to keep this in mind if I am the one hacking on it.

**Comment by mvdbeek** [comment]
For the record this is now https://github.com/galaxyproject/galaxy/blob/1f389ae3e77352920566f09c4f1be1a1e40ff862/test/api/test_tools.py#L832.
And also -- how did I forget about this, we should try getting this in the UI, that's an awesome feature once again just waiting to be used ✨

**Comment by mvdbeek** [comment]
We've got this for workflows now using expression tools. This isn't usable yet from the tool form, but it's a big step forward.
