### ISSUE TITLE
File is incorrectly recognised as csv

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#1818]
The following file should not be recognised as `csv` but as `tabular` with one header.

https://github.com/galaxyproject/tools-iuc/blob/master/tools/datamash/test-data/group_compute_input.txt

**Comment by nsoranzo** [comment]
@bgruening There's a typo in https://github.com/galaxyproject/tools-iuc/commit/e69a1e60f33d60abd0dcaf1edc7947d2ff8f4827#diff-e97dd19c87515b6dc90cdd4fc6b61210R71

**Comment by bgruening** [comment]
Ok, I removed this one error which was my fault due to a type and changed the title and the description to the other error that caused the original tool test to fail.

**Comment by bgruening** [comment]
Maybe related to https://github.com/galaxyproject/galaxy/pull/1156
