### ISSUE TITLE
Bar chart does not show column select field

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#18221]
**Describe the bug**
When creating a bar chart using the visualization framework, the column select field is not visible.

**To Reproduce**
1. Go to 'Visualizations'
2. Click on 'Bar Horizontal (NVD3)'
3. Expand the side panel
4. Switch to the data tab
5. Notice the missing select field

**Expected behavior**
A select field should appear, listing the available dataset columns.

**Screenshots**
<img width="536" alt="image" src="https://github.com/galaxyproject/galaxy/assets/2105447/d6cfb1a5-a077-4637-9a74-8c449b303c7b">

**Additional context**
Likely due to recent upgrades to the select field.

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/18299
