### ISSUE TITLE
Main Tool Shed (MTS) has inactive Help and User pull-down menus

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1822]
https://toolshed.g2.bx.psu.edu

Testing on OSX Chrome and Safari. @blankenberg also confirmed.

**Comment by davebx** [comment]
@martenson is in the process of looking at this issue.

**Comment by martenson** [comment]
dupe of https://github.com/galaxyproject/galaxy/issues/1525
hopefully fixed by https://github.com/galaxyproject/galaxy/pull/1823

**Comment by jennaj** [comment]
Thx! Sorry for dup
