### ISSUE TITLE
Enhancement: allow favouriting of Public Workflows

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#18227]
Currently I can "favourite" my own workflows:

![image](https://github.com/galaxyproject/galaxy/assets/4154788/066f26dc-6837-46b9-b53c-0ae097012c2f)

I cannot, however, add Public Workflows to my list of favourites

![image](https://github.com/galaxyproject/galaxy/assets/4154788/d7c400cc-eae1-435c-8e4e-e95dce85c58d)

This seems strangely inconsistent. As Public Workflows often include "best practice" workflows on a Galaxy server, I would like to be able to favourite them

Galaxy version: 24.0 3.dev0
(on usegalaxy.eu)

**Comment by mvdbeek** [comment]
Done in https://github.com/galaxyproject/galaxy/pull/18247
