### ISSUE TITLE
Enhancement: Allow chanting the name of a collection on the Collection Attributes Page

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#18228]
The UX between clicking the pencil icon on a dataset and clicking it on a collection is inconsistent

For a dataset I get this view that lets me set the name, info, annotation, database build and (on other tabs) datatype and permissions

![image](https://github.com/galaxyproject/galaxy/assets/4154788/9e621b72-2787-41ba-a34a-0b7afda84071)

For a collection, I get a page allowing me to change the database build and (on other tabs) datatype

![image](https://github.com/galaxyproject/galaxy/assets/4154788/dc2f9789-06bf-4e2f-9cf2-b9e23ec9f9f1)

To change the collection name I have to click on the collection name and then edit a text box

![image](https://github.com/galaxyproject/galaxy/assets/4154788/b021b299-7c51-466f-a4f3-d0d879988a39)

This is not intuitive (to me at least) and the interfaces should be more consistent

Galaxy version: 24.0 3.dev0
(on usegalaxy.eu)

**Comment by mvdbeek** [comment]
That's implemented in https://github.com/galaxyproject/galaxy/pull/18071, to be released in 24.1, a preview of which you can find at https://test.galaxyproject.org/
