### ISSUE TITLE
Make tool-ids searchable 

### ISSUE THREAD

**Issue by microfuge** [galaxyproject/galaxy#18232]
Hi,

Please correct me if I am wrong. Seems the exact tool ids are not searchable. Examples `comp1` `CONVERTER_uncompressed_to_gz` .  It would be good to have them searchable. 
Thanks!

**Comment by mvdbeek** [comment]
It's in the advanced search menu, 
<img width="260" alt="Screenshot 2024-05-27 at 11 33 37" src="https://github.com/galaxyproject/galaxy/assets/6804901/74e82271-7e46-433c-9182-2b14124015ac">
and there's also a shortcut for the frontend search, which is `tool_id: CONVERTER_uncompressed_to_gz`

**Comment by microfuge** [comment]
Thanks! I was not aware of this. The issue is resolved from my side.
