### ISSUE TITLE
Unable to renew or see Toolshed API keys due to internal server error 500

### ISSUE THREAD

**Issue by hechth** [galaxyproject/galaxy#18242]
**Describe the bug**
Currently it is not possible for us to update tools on the toolshed and testtoolshed via the CI (https://github.com/RECETOX/galaxytools/actions/runs/9254908691/job/25486748998) or via the planemo CLI.

We get an API key invalid error on the testtoolshed ```bioblend ERROR: GET: error 401: b'{"err_msg":"Provided API key is not valid.","err_code":401001}', 0 attempts left``` and a unknown error 500 when trying to update the regular toolshed.

Additionally, it is not possible to update the Galaxy toolshed API key through the toolshed UI.
Is there a different way to update the API key?

**Browser and Operating System**
Operating System: Windows
Browser: Firefox, Librewolf and Chrome persistently have the same problem displaying the API key.

**Expected behavior**
I'd expect the toolshed UI to allow me to update API keys.

**Screenshots**
This should display the API key though it just doesn't display anything. I am logged in.
![image](https://github.com/galaxyproject/galaxy/assets/12066490/60bad1ff-d814-4da5-868a-7a6bf02f16b0)

**Comment by mvdbeek** [comment]
@natefoo @jdavcs maybe a broken migration ? https://sentry.galaxyproject.org/share/issue/04adfef3d6cc4370bfe2a5bfca671b7c/

**Comment by hechth** [comment]
Seems like the toolshed is now completely down :D

**Comment by jdavcs** [comment]
Apparently this was the last migration on the old sqlalchemy migrate system, and it somehow fell through the cracks. 
Here's the old one: https://github.com/galaxyproject/galaxy/pull/14489/files#diff-fa487f1639fd05014a3ec90f54d78393aa5ae32290b65e3a33d746863d2e91d9

Fix coming up. I'll add a migration and we'll apply it to the TS database.

**Comment by mvdbeek** [comment]
We never intended for the deleted column to be manadator on the TS side, there's more to it.

**Comment by mvdbeek** [comment]
That's fixed now.
