### ISSUE TITLE
[24.1] RNA Structure Viewer "Load function 'load' not found."

### ISSUE THREAD

**Issue by arash77** [galaxyproject/galaxy#18259]
**Describe the bug**
When using `RNA Structure Viewer` to visualize a `dbn` file it will fail and return an error with this message: `Load function 'load' not found.`

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1.rc1 ([test.galaxyproject.org](http://test.galaxyproject.org/))

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**
1. Upload a `dbn` file.
2. Click on `RNA Structure Viewer` in `Visualizations`.
3. Select the `dbn` file.
4. See error.

**Expected behavior**
Show the visualization.

**Screenshots**
![image](https://github.com/galaxyproject/galaxy/assets/2973722/03fda5bc-ee61-462f-b319-3b972d959661)

**Additional context**

This is the content that I used in `test.dbn`:
```
>355d nts=24 [whole]
CGCGAATTCGCG&CGCGAATTCGCG
((((((((((((&))))))))))))
>355d-A #1 nts=12 [chain] DNA
CGCGAATTCGCG
((((((((((((
>355d-B #2 nts=12 [chain] DNA
CGCGAATTCGCG
))))))))))))
```

**Comment by mvdbeek** [comment]
That's a deployment issue, @dannon do you remember the fix for that ?

**Comment by dannon** [comment]
Verified this is working fine on test now, with the parcel updates/rebuild.
