### ISSUE TITLE
Where is the scramble.py file?

### ISSUE THREAD

**Issue by micafer** [galaxyproject/galaxy#1825]
I'm tryin to install the pbs_python module using the instructions found here:
https://wiki.galaxyproject.org/Admin/Config/Performance/Cluster

But in the last release (16.01) this file is not present.

Is the documentation incorrect for last version?

**Comment by bgruening** [comment]
scamble.py is gone in 16.01. We do not use python eggs anymore. Now method of choice is wheels. So this step can be skipped.

The documentation is not up-to-date. Can you add a comment to this step, that this is deprecated in 16.01.

**Comment by martenson** [comment]
@micafer please read more here and re-open if needed: https://docs.galaxyproject.org/en/master/admin/framework_dependencies.html#framework-dependencies
