### ISSUE TITLE
"label updated" pop up triggers too often 

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#18254]
**Describe the bug**
Not a big problem, it just look a bit overkill. When adding a label the pop up "Success" appear every four letters typed or so, which feels a bit weird. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1 on test 

**Browser and Operating System**
Operating System: macOS
Browser: Chrome, Safari

**To Reproduce**
1. Create a new workflow 
2. Add a new input
3. Add a long label 

**Expected behavior**
Maybe trigger the pop up when the user clicks on another box? 

**Screenshots**

https://github.com/galaxyproject/galaxy/assets/11195061/3c46e4e6-fb38-4101-86a5-98f76f9d7eac

**Comment by jdavcs** [comment]
Fixed in #18303
