### ISSUE TITLE
[24.1] Dataset type converter can't generate metadata

### ISSUE THREAD

**Issue by itisAliRH** [galaxyproject/galaxy#18261]
The dataset type converter can't generate metadata after changing a dataset type/format for any type:

![image](https://github.com/galaxyproject/galaxy/assets/8046843/c818f632-d0b6-464b-bea7-072eaeaaca38)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: https://test.galaxyproject.org/
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Windows, Linux, macOS
Browser: Firefox, Chrome, Chrome-based, Safari

**To Reproduce**
1. Upload a dataset
2. Click on the dataset `Edit` button (pencil) 
3. On tab `Datatypes`, assign a new type
4. See the dataset error

**Expected behavior**
Generate metadata and turns green

**Comment by mvdbeek** [comment]
That's a misconfiguration in TPV, `__SET_METADATA__ ` doesn't get a history assigned either (although we could reasonably do that).

**Comment by mvdbeek** [comment]
Fixed now
