### ISSUE TITLE
[24.1] Getting an internal Server Error when looking for public pages

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#18266]
**Describe the bug**
Getting the error `Failed to obtain grid data: Error: Internal Server Error` when looking for public pages on test. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1

**Browser and Operating System**
Operating System:  macOS
Browser: Chrome, Safari

**To Reproduce**
1. Go to Pages
2. Click on "Public Pages"

**Screenshots**
![Screenshot 2024-05-29 at 10 39 06 AM](https://github.com/galaxyproject/galaxy/assets/11195061/9c56b877-bd3b-4ad1-ab36-69c40294ffc4)

**Comment by jdavcs** [comment]
may be fixed in #18263, let's test again after fix is deployed.
