### ISSUE TITLE
[24.1] Wrong link in history import message for anonymous users

### ISSUE THREAD

**Issue by arash77** [galaxyproject/galaxy#18280]
**Describe the bug**
As an anonymous user, when you import a history, the link will point to the history list, which is not accessible to anonymous users.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1.rc1 ([test.galaxyproject.org](http://test.galaxyproject.org/))

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**
1. Go to public histories as an anonymous user
2. Click on a history and click view
3. Click on Import this history and click on Copy history
4. Click on the link "View here"
5. It will redirect to the user login page

**Expected behavior**
Either it should show the history list for anonymous users or redirect to the home page.

**Comment by jdavcs** [comment]
Fixed in #18286
