### ISSUE TITLE
[24.1] Login and register link in history import not working.

### ISSUE THREAD

**Issue by arash77** [galaxyproject/galaxy#18287]
**Describe the bug**
When an anonymous user tries to import a history, they will receive a message prompting them to log in or register. This will redirect the user to `/user/login` or `/user/create`, both of which will return the following error:
`{"err_msg": "No session token set, denying request."}`

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1.rc1 ([test.galaxyproject.org](http://test.galaxyproject.org/))

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**
1. Go to public histories as an anonymous user
2. Click on a history and click view
3. Click on Import this history
4. Click on log in here or register here.
5. See the error

**Expected behavior**
The user should be redirected to `/login/start` instead.

**Comment by jdavcs** [comment]
Fixed in #18289
