### ISSUE TITLE
[24.1] history_dataset_as_image when no image exist.

### ISSUE THREAD

**Issue by arash77** [galaxyproject/galaxy#18281]
**Describe the bug**
In the workflow report, if the data is not an image, using `history_dataset_as_image` will result in an empty entry.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1.rc1 ([test.galaxyproject.org](http://test.galaxyproject.org/))

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**
1. Upload a none image data
2. Create a new workflow
3. Click on the Input dataset and label it
4. Save the workflow
5. Refresh the page (I think this is also a bug that the edit report items are not accessible until refreshing the page)
6. Click on edit the report
7. Under History, click on Image
8. Select the labeled dataset and click on continue
9. Save the workflow and run it
10. Select the non-image data as the input and click on run workflow
11. Click on the report and see the bug

**Expected behavior**
The `history_dataset_as_image` should not be available to use in the workflow report when there is no image data.

**Screenshots**
![image](https://github.com/galaxyproject/galaxy/assets/2973722/9dfd45c7-9999-4b9e-855f-762ab4bd2a77)

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/18309
