### ISSUE TITLE
Extra dependency created in package integration_util by import of toolshed

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/galaxy#18282]
**Describe the bug**
The `integration_util` package imports the toolshed UniverseApplication, creating an avoidable dependency.
```
______________________________________________________________________________________________________________________________ ERROR collecting tests/test_mapper_resubmit.py _______________________________________________________________________________________________________________________________
ImportError while importing test module '/Users/nuwan/work/total-perspective-vortex/tests/test_mapper_resubmit.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Caskroom/miniconda/base/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_mapper_resubmit.py:5: in <module>
    from galaxy_test.driver.integration_util import IntegrationTestCase
.tox/py3.10/lib/python3.10/site-packages/galaxy_test/driver/integration_util.py:36: in <module>
    from .driver_util import GalaxyTestDriver
.tox/py3.10/lib/python3.10/site-packages/galaxy_test/driver/driver_util.py:53: in <module>
    from tool_shed.webapp.app import UniverseApplication as ToolshedUniverseApplication
E   ModuleNotFoundError: No module named 'tool_shed'
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: dev
Commit: dev

related: https://github.com/galaxyproject/galaxy/pull/17747

**Comment by mvdbeek** [comment]
Can you test https://github.com/galaxyproject/galaxy/pull/18296 ?

**Comment by nuwang** [comment]
@mvdbeek I'll give this a shot, but I'm hoping we can get https://github.com/galaxyproject/galaxy/pull/17747 working, so we can catch all these in advance. However, I have had no luck with that. I'm wondering whether release.sh is behaving slightly differently within github: https://github.com/galaxyproject/galaxy/pull/17747/files#diff-688d8b5f8f97e98c2c0b144ac437f4c988d40f29880cffafb43f6d2a4ba6c874R51 because the last time I tried locally, it worked as expected.
