### ISSUE TITLE
[24.1] TypeError this.Galaxy is undefined

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#18298]
Sentry issue: https://sentry.galaxyproject.org/organizations/galaxy/issues/154379

Galaxy Version: 24.1

I think this is related to #17326: `this.Galaxy` is not initialized in embedded mode, but is accessed in `currentHistory` watcher regardless.

**Comment by ElectronicBlueberry** [comment]
fixed by https://github.com/galaxyproject/galaxy/commit/a9c1300fd44b9545efbc258701a2727fddca3cd7
