### ISSUE TITLE
Random stuff can be dragged into the History

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#18302]
**Describe the bug**
Apparently, some buttons and elements in the UI can be dragged around and the History will drop event will accept them only to fail.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Linux
Browser: Chrome

**To Reproduce**
![DragToHistoryBug](https://github.com/galaxyproject/galaxy/assets/46503462/83144db2-91db-4c97-ac51-2b1552605227)

**Expected behavior**
Only items meant to be draggable should be.

**Screenshots**

**Additional context**

**Comment by ElectronicBlueberry** [comment]
> Expected behavior
> Only items meant to be draggable should be.

Many elements are draggable by default, e.g. anchor links or images, so they can be dragged onto a different tab/window.
I think rather than marking ui elements as non-draggable, the history should only respond to history elements being dragged onto it.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/18308
