### ISSUE TITLE
[24.0] `/api/users/` does not include `deleted`

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#18300]
**Describe the bug**

Apparently it did until 23.x https://github.com/galaxyproject/bioblend/pull/487

Not sure if a bug, since `deleted` is a parameter and therefor the info is redundant.
But the example in https://usegalaxy.eu/api/docs#/users/get_users_api_users_get 
also shows it in the response. 

Edit: The [code](https://github.com/galaxyproject/galaxy/blob/9753a0b5a4e56da046d5fbb82a75152fe6a62cb6/lib/galaxy/webapps/galaxy/services/users.py#L253) suggests that only `id` (and maybe `email` and `username`) are included. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0

**Expected behavior**

Not sure if the key should be in the response. But at least the docs should be consistent.

**Comment by davelopez** [comment]
I'm also not sure about when it has to be present, but regarding the docs, the response contains a `Union` of models `List[Union[UserModel, LimitedUserModel]]`. The example value in the doc renders the first one it encounters, but if you want to check other possible models you can check the schema:

![image](https://github.com/galaxyproject/galaxy/assets/46503462/341ae138-12b5-4796-9a75-8a7249f45fd2)

**Comment by davelopez** [comment]
Hmmm now that I look, it might actually be because of this

https://github.com/galaxyproject/galaxy/blob/ef294f905b3e033ee7da7f437a3f106689efa50b/lib/galaxy/webapps/galaxy/services/users.py#L254

If any of these options (expose_user_name or expose_user_email) are set to false the UserModel will fail validation because it expects `username` and `email` to be non-null and FastAPI might choose to return the limited version then :thinking:

**Comment by davelopez** [comment]
I've just compared the admin response for `http://127.0.0.1:8080/api/users` between 23.1 and 24.0 and can confirm that there are unexpected changes. I'll add some integration tests a prepare a fix :+1: 

## 23.1
```json
[
  {
    "model_class": "User",
    "id": "f2db41e1fa331b3e",
    "email": "admin@test.gx",
    "username": "admin",
    "deleted": false,
    "active": true,
    "last_password_change": "2024-02-06T13:04:23.454162"
  },
  {
    "model_class": "User",
    "id": "1cd8e2f6b131e891",
    "email": "t02@test.gx",
    "username": "user02",
    "deleted": false,
    "active": true,
    "last_password_change": "2024-02-06T13:04:23.638815"
  },
  {
    "model_class": "User",
    "id": "f597429621d6eb2b",
    "email": "t01@test.gx",
    "username": "user01",
    "deleted": false,
    "active": true,
    "last_password_change": "2024-02-06T13:04:23.558743"
  }
]
```

## 24.0
```json
[
  {
    "id": "ebfb8f50c6abde6d",
    "username": "user03",
    "email": "t03@test.gx"
  },
  {
    "id": "f597429621d6eb2b",
    "username": "user01",
    "email": "t01@test.gx"
  },
  {
    "id": "f2db41e1fa331b3e",
    "username": "admin",
    "email": "admin@test.gx"
  }
]
```

**Comment by davelopez** [comment]
This should be fixed in https://github.com/galaxyproject/galaxy/pull/18329
