### ISSUE TITLE
Slow down in workflows scheduling.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1831]
https://github.com/galaxyproject/galaxy/pull/1217 made a huge improvement and it seems like the tool optimizations in 15.10 helped also, but workflow scheduling is still slow and there appears to a huge slow down after large collections are created. 

Gist from @blankenberg,  https://gist.github.com/blankenberg/43db2e0f61a566126c45.

From Dan:

"It looks like it happens between step invocations / and/or/around after a new collection output is is created in the wf. 'fast' before `Workflow step 5664 of invocation 962 invoked (675438.745 ms)`, slow after. If i kill the Galaxy instance, and then restart Galaxy, the workflow resumes and everything is fast again, until the next slowdown"

**Comment by blankenberg** [comment]
And just for completeness, this was on dev @ 19a58f745089eea730674158153bf77adbf2bbbc

**Comment by jmchilton** [comment]
I spent another week on this and just opened 5 PRs from this work (#1955 #1956 #1957 #1958 #1959), but using a number of different workflow patterns, input types, etc... I can't seem to duplicate this sharp rise in execution time during workflow execution.
- What PJA are using in the workflow if any?
- Is this the version of column join that uses a multiple input or a list input?
- The slow down doesn't seem to be universal for all new jobs:

```
galaxy.tools.execute DEBUG 2016-03-01 10:41:54,139 Tool [dan-1.bx.psu.edu:9009/repos/iuc/collection_column_join/collection_column_join/0.0.1] created job [282104] (11894.992 ms)
...
galaxy.tools.execute DEBUG 2016-03-01 10:41:55,899 Tool [Grep1] created job [282105] (1698.481 ms)
...
galaxy.tools.execute DEBUG 2016-03-01 10:43:49,632 Tool [toolshed.g2.bx.psu.edu/repos/devteam/kraken_report/kraken-report/1.1.0] created job [282106] (20365.390 ms)
```

Any ideas what the difference between kraken-report/column-join and grep1 one? None of these steps seem to be being mapped over. Are the same or same-ish inputs used for the all three tools?

**Comment by blankenberg** [comment]
- No PJAs.
- multiple input `<param name="input_tabular" type="data" format="tabular" multiple="True" optional="False" label="Tabular files"/>`
- Grep1 is on the output of the column join: single file in, single file out
  - All other tools are running over an input collection list, starting as a list of fasta/q files and passed to the next tool as a collection list; each tool runs once per list item.

**Comment by blankenberg** [comment]
Perhaps the slowdown is at the adding dataset to history step:

```
==> handler2.log <==
galaxy.tools.actions INFO 2016-03-21 16:29:31,344 Added output datasets to history (13482.389 ms)
galaxy.tools.actions INFO 2016-03-21 16:29:31,358 Verified access to datasets for Job[unflushed,tool_id=Cut1] (6.730 ms)
galaxy.tools.actions INFO 2016-03-21 16:29:31,359 Setup for job Job[unflushed,tool_id=Cut1] complete, ready to flush (14.534 ms)
galaxy.tools.actions INFO 2016-03-21 16:29:34,892 Flushed transaction for job Job[id=337697,tool_id=Cut1] (3532.949 ms)
galaxy.tools.execute DEBUG 2016-03-21 16:29:34,893 Tool [Cut1] created job [337697] (17383.540 ms)
```

Each run of the cut tool is on a single input dataset, creating a single output dataset; in the wf, it is given a list of tabular files to loop through.

**Comment by jmchilton** [comment]
:open_mouth: ... I wouldn't have expected slow down there at all, it is quite surprising.

I have more `printf`s if you are willing to produce more logging for me, if not I will continue to try to reproduce the slowdown. 

https://github.com/jmchilton/galaxy/commit/cc1c0970af070d7a7524be312fcb2fab6df613d3

This would be an obnoxious amount of logging to actually put into dev so if you have a way to apply the changes locally that would be ideal.

I'm sure you are - but can you confirm you are using postgres?

**Comment by blankenberg** [comment]
Yes, using postgres, trying the patch now. Thanks.

**Comment by blankenberg** [comment]
Doesn't look to be going into the optimized chunk.
`galaxy.model INFO 2016-03-22 10:49:39,647 history.add_datasets executed (15468.588 ms)`
but
`galaxy.model.mapping INFO 2016-03-22 10:49:44,160 history.db_next_hid executed (8.061 ms)`

https://gist.github.com/blankenberg/611920747e0f9744000a

**Comment by jmchilton** [comment]
Yeah - there was a problem with that optimization logging statement. I would think the optimized version would be fine for a single output tool. I don't have a firm explanation for the slow down yet, but the new logging helped narrow down some things (it isn't anything outside of add_datasets in the actions method, the hid generation is quick, etc...). My best guess is `history.dataset.append` is materializing or refreshing the whole collection? I have no clue why this wouldn't be a constant linear slow down instead of this slowdown though.

Want to abandon those previous log statements and apply these ones: https://github.com/jmchilton/galaxy/commit/fa91f873b247becbe5b3ac9be9c78389652dbd76 ? That would be helpful.

Also, can you confirm that you do not have tool bursting options enabled?

```
#tool_submission_burst_threads = 1
#tool_submission_burst_at = 10
```

**Comment by blankenberg** [comment]
history.datasets.append appears to be expensive

```
==> handler2.log <==
galaxy.tools.actions INFO 2016-03-22 13:42:05,331 Handled output named out_file1 for tool Cut1 (1220.265 ms)
galaxy.model INFO 2016-03-22 13:42:05,332 Optimizing addition of datasets to history? False
galaxy.model.mapping INFO 2016-03-22 13:42:05,341 history.db_next_hid executed (9.164 ms)
galaxy.model INFO 2016-03-22 13:42:20,743 history.datasets.append executed (15401.061 ms)
galaxy.model INFO 2016-03-22 13:42:20,743 history.add_dataset executed (15411.235 ms)
galaxy.model INFO 2016-03-22 13:42:20,743 history.add_datasets executed (15411.713 ms)
galaxy.tools.actions INFO 2016-03-22 13:42:20,743 Added output datasets to history (15411.843 ms)
galaxy.tools.actions INFO 2016-03-22 13:42:20,757 Verified access to datasets for Job[unflushed,tool_id=Cut1] (4.698 ms)
galaxy.tools.actions INFO 2016-03-22 13:42:20,758 Setup for job Job[unflushed,tool_id=Cut1] complete, ready to flush (14.329 ms)
```

I do not have either burst options set.

```
$ grep 'tool_submission_burst_threads' config/galaxy.ini
$ grep 'tool_submission_burst_at' config/galaxy.ini
```
