### ISSUE TITLE
MultipleResultsFound error in file_source_instances manager

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#18316]
version: 24.1

sentry error: https://sentry.galaxyproject.org/organizations/galaxy/issues/154561/?project=2&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=24h&stream_index=13

This is a data access bug: wrong select statement or wrong improper result method (`one_or_none`)

**Comment by mvdbeek** [comment]
Might be anon related

**Comment by jdavcs** [comment]
@jmchilton can you cherry-pick the fix (also see my comment on the commit) and PR it as a fix for this issue? It's a blocker for 24.1.
