### ISSUE TITLE
GET /api/jobs fails with 500 Internal Server Error when not logged in

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#18331]
**Describe the bug**
When visiting https://usegalaxy.eu/api/jobs when not logged in, it fails with a HTTP error 500 (Internal Server Error) instead of 403. Same on usegalaxy.org .

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0

**To Reproduce**
1. Visit https://usegalaxy.eu/api/jobs when not logged in (e.g. on a private browser window), or run `requests.get("https://usegalaxy.eu/api/jobs")` on an Python shell
2. Error 500 (Internal Server Error) is returned

**Expected behavior**
A 403 error, not a server crash.

**Comment by mvdbeek** [comment]
That happens when you don't have a session, but I agree of course we need to handle this.

**Comment by nsoranzo** [comment]
/api/datasets returns 403 for example.

**Comment by mvdbeek** [comment]
that's the old API

**Comment by davelopez** [comment]
I'll take a look

**Comment by davelopez** [comment]
This should be fixed in #18358
