### ISSUE TITLE
Browse tool dependency installation directory

### ISSUE THREAD

**Issue by methylome** [galaxyproject/galaxy#1834]
I cloned galaxy 16_01 yesterday and installed tools. Galaxy web server doesn't list files on browse tool dependency installation directory. For example, `package_bwa_0_7_12` was installed into `/path/software/bwa/0.7.12/iuc/package_bwa_0_7_12/6af9b24ddeee` and the ls command lists:
drwxr-xr-x 2 galaxy galaxy 4096 Mar  1 14:13 bin
-rwxr-xr-x 1 galaxy galaxy  209 Mar  1 14:14 env.sh
-rw-r--r-- 1 galaxy galaxy 2020 Mar  1 14:13 INSTALLATION.log

`tool_dependency_dir` in `galaxy.in` is set to /path/software. This is wired because another server which is the same except the base directory is working well.

**Comment by martenson** [comment]
This is indeed broken in 16.01 - probably a bug brought by https://github.com/galaxyproject/galaxy/commit/e4a1d5727805168a9fd15aca1cdd21630ada2bbc or similar

**Comment by martenson** [comment]
fixed by #2101
