### ISSUE TITLE
TS Error when creating new repo

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#18359]
**Describe the bug**

The following error suggests a problem with a data table .. but the tool has none:

```
HTTP status code: 500: {"err_msg": "Metadata may have been defined for some items in revision '082e9d22c38d'.  Correct the following problems if necessary and reset metadata.<br/><b>dose_response.xml<\/b> - This file requires an entry for \"None\" in the tool_data_table_conf.xml file.  Upload a file named tool_data_table_conf.xml.sample to the repository that includes the required entry to correct this error.  <br/>"}
```

Edit: ~Despite the [failing deploy step](https://github.com/Helmholtz-UFZ/galaxy-tools/actions/runs/9447781693/job/26020506379) the tools seems to have been deployed to the TS: https://toolshed.g2.bx.psu.edu/view/ufz/dose_response_analysis_tool/082e9d22c38d~ In the toolshed the tool is listed under `Invalid tools`

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.1 (I guess this is currently at the TS)

**Expected behavior**

No Error should happen.

**Comment by mvdbeek** [comment]
Did you try resetting metdata on the repo ?
