### ISSUE TITLE
Workflow cards view should provide a way to share links to published WFs

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#18368]
**Describe the bug**
Reported originally by @nomadscientist; currently I cannot find any way to share the link to a published workflow from the workflow cards view.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: any Galaxy version since introduction of WF cards

**Comment by itisAliRH** [comment]
@wm75 What do you think about this?
![image](https://github.com/galaxyproject/galaxy/assets/8046843/88b46bb1-5b83-4cc5-ac5d-111a6cce9342)
![image](https://github.com/galaxyproject/galaxy/assets/8046843/65a459ed-03a5-4274-9e9b-63d4c5428600)
If it looks ok, we also need to replace the imported indicator with the link icon on the top left which conflicts with this new button.

**Comment by wm75** [comment]
looks good, thank you!
