### ISSUE TITLE
Running a WF from an invocation display always runs latest version

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#18367]
Not sure whether there's a simple fix for this, but ...

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: .org (24.1) and .eu (24.0)

**To Reproduce**
1. Run any WF to produce an invocation
2. Edit the workflow
3. Go to the invocation from step 1
4. Run the workflow from the invocation's display

**Expected behavior**
Running a workflow from an invocation display should run the version used for that invocation

**Comment by jdavcs** [comment]
Fixed in #18378
