### ISSUE TITLE
Polling in ``datasets/{dataset_id}/details`` re-renders entire page

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#18375]
If you run a job and open the job info / dataset info page the whole component re-renders:

![rendering](https://github.com/galaxyproject/galaxy/assets/6804901/132241ce-f80d-4603-aae4-cda71248ed8a)

**Comment by jdavcs** [comment]
This happens on 24.1 and dev, not on 24.0.

**Comment by itisAliRH** [comment]
Fixed in #18388
