### ISSUE TITLE
Workflow Editor removes tags on save

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#18394]
When you open the editor for a workflow with tags, they do not show up and if you make changes and save, the tags are removed.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: usegalaxy.org (`release_24.1`)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Add a tag to a workflow in the workflows list
2. Click on 'Edit'
3. See that the tags are not populated in the right panel
4. Make a minor change and save
5. Return to the workflows list and note that the tag you added is no longer present

**Expected behavior**
Tags should be populated on workflow editor load.

**Screenshots**

https://github.com/galaxyproject/galaxy/assets/78516064/96cc01ee-0ad7-4b81-a4a8-48d4a506cc4c

**Comment by itisAliRH** [comment]
Fixed in #18396
