### ISSUE TITLE
New invocation view erroneously shows existing datasets as "purged"

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#18398]
**Describe the bug**
Datasets within an invocation view are show as "purged" while they are not
<img width="730" alt="inv_bug" src="https://github.com/galaxyproject/galaxy/assets/4291636/b595dfd2-a415-4ef5-8ffc-729870fcd112">

**Comment by mvdbeek** [comment]
Can you share the invocation id?

**Comment by ahmedhamidawan** [comment]
For an invocation with collection outputs, I am not seeing any purged datasets:
![image](https://github.com/galaxyproject/galaxy/assets/78516064/4f0cc8cc-09b1-45ff-83df-ad7558cf537b)

Could you please share the workflow so that I can try to reproduce this?

**Comment by mvdbeek** [comment]
@nekrut if this is https://usegalaxy.org/workflows/invocations/9ff94850529c443b, I don't think this is wrong, the dataset was on scratch storage, it is purged now:

<img width="691" alt="Screenshot 2024-06-14 at 17 25 11" src="https://github.com/galaxyproject/galaxy/assets/6804901/11c534f2-a5fe-4ed7-871b-da32d12bfe0d">
<img width="602" alt="Screenshot 2024-06-14 at 17 25 20" src="https://github.com/galaxyproject/galaxy/assets/6804901/60576508-3903-4efa-aac4-fc77643fd267">

**Comment by mvdbeek** [comment]
There is however a bug in that we're not showing the purged status when the collection is being drilled down in the history.

**Comment by nekrut** [comment]
I see. Thanks!
