### ISSUE TITLE
Uploaded TSV files are recognized as txt

### ISSUE THREAD

**Issue by microfuge** [galaxyproject/galaxy#18408]
Hi,

I am seeing this in eu and our local instance. TSV files are recognized as txt when uploaded. I could be wrong but I vaguely remember it was not like that earlier.
Thanks!

**Comment by mvdbeek** [comment]
Can you provide a sample ?

**Comment by microfuge** [comment]
Thanks @mvdbeek . It is available as a public history https://usegalaxy.eu/published/history?id=57d559cd6d0b9f06 . The dataset is "xx.tsv" with tag "TSV".
