### ISSUE TITLE
Purged status not shown on collection element

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#18415]
There is however a bug in that we're not showing the purged status when the collection is being drilled down in the history.

_Originally posted by @mvdbeek in https://github.com/galaxyproject/galaxy/issues/18398#issuecomment-2168291382_

**Comment by davelopez** [comment]
I'll take a look :+1: 
I think we are not serializing the purged value in HDAObjects

**Comment by davelopez** [comment]
Hmmm there is still more to it :thinking: After serializing the purged flag in https://github.com/galaxyproject/galaxy/pull/18420 I observed a strange behavior (but maybe it is how it is supposed to work?):
- I created a simple list out of some datasets (without hiding original datasets)
- The collection, along with the hidden copied HDAs is created
- Then I purged one of the hidden datasets
- The collection now displays the purged status correctly

Now, if you click the info icon in the purged dataset inside the collection the one displayed in the central panel is the original (unpurged) dataset. Is this how it's supposed to be?

**Comment by mvdbeek** [comment]
When you copy the collection we are making copies of the HDAs as well, and these should have different ids. They do point to the same dataset however, and only when purging the last HDA for a dataset do we also purge the dataset.
