### ISSUE TITLE
Column selector in visualizations broken

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#18427]
can't select anything here, so most of the plotting visualizations won't plot anything useful.
this is on 24.0 and 24.1

<img width="415" alt="Screenshot 2024-06-21 at 13 00 25" src="https://github.com/galaxyproject/galaxy/assets/6804901/b1ad186d-0c55-4c1b-b90a-930fa24ae145">

**Comment by dannon** [comment]
xref https://github.com/galaxyproject/galaxy/issues/18221?

**Comment by dannon** [comment]
Yeah, it looks like a subsequent change didn't quite land right.  I'll untangle it.
