### ISSUE TITLE
No-op workflow "relabel" shouldn't result in a notification.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#18436]
Watching @mvdbeek do the advanced workflow training - and every time he gives a new tool or step a label it pops up a message "Label '' updated to 'the name entered' in workflow report", but that workflow report clearly didn't contain that label. I think I meant this message to only appear if the workflow report actually changed.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/18473
