### ISSUE TITLE
Plausible hostname/domain tracking is not working due to the missing config

### ISSUE THREAD

**Issue by sanjaysrikakulam** [galaxyproject/galaxy#18444]
Enabling and adding the following to the Galaxy conf no longer allows the collection of metrics in Plausible.

```
plausible_server: https://plausible.galaxyproject.eu
plausible_domain: https://usegalaxy.eu
```

Once deployed, I could not find the script snippet (`<script defer data-domain="usegalaxy.eu" src="https://plausible.galaxyproject.eu/js/script.js"></script>`) that must be added to the website's `Head` section which allows the domain to push the metrics to the Plausible server ([ref doc](https://plausible.io/docs/subdomain-hostname-filter)).

It would be really great to have this feature.

Also, do you have any suggestions for expanding this to include the subdomains? Can the `plausible_domain` be made to accept a list of domain names?

Galaxy version 24.0

**Comment by mvdbeek** [comment]
Probably fixed in https://github.com/galaxyproject/galaxy/pull/18458 ?
