### ISSUE TITLE
Silence pip upgrade warning if on latest Galaxy forked pip

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#1845]
This kind of message is confusing (but if I understand correctly harmless):

```
$ ./run.sh
...
You are using pip version 8.0.2+gx2, however version 8.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
...
```

e.g. http://dev.list.galaxyproject.org/trouble-with-python-packages-after-galaxy-update-tt4669031.html

As part of the changes Galaxy has made to their fork of pip (for Linux binary wheels used in Galaxy v16.01 onwards), you could also disable this version check - or better modify it to only look for an updated version of the forked pip.

**Comment by natefoo** [comment]
Alternatively, I think we ought to try to keep in sync with the upstream pip. But see also #1864.

**Comment by peterjc** [comment]
Since #1864 was closed, I take it the latest Galaxy is using standard pip - so can we close this issue?
