### ISSUE TITLE
improve displaying of object store names in storage dashboard

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#18454]
I see the following on Main under https://usegalaxy.org/storage/objectstores

It is displaying the IDs of object stores like `corral-repl-psu` which are not very helpful to the user

<img width="904" alt="Screenshot 2024-06-28 at 12 51 31 PM" src="https://github.com/galaxyproject/galaxy/assets/1814954/c045fad1-2aa5-40b7-aee8-00efcaf81a17">

If the object stores have labels we should use that, if they don't we should still display this in a different way but it is not obvious to me right now how that should look like. These internal IDs should basically be never displayed I think.

**Comment by davelopez** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/18525
