### ISSUE TITLE
Trackster: UCSC bed file import error. 

### ISSUE THREAD

**Issue by nturaga** [galaxyproject/galaxy#1849]
This was reported by @malloryfreeberg earlier today about a bug with Trackster. She is having issues adding UCSC bed files as tracks on trackster. The issue is because its having a hard time converting the BED to tabix. The error is most likely happening here, https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/converters/interval_to_tabix_converter.py#L35

```
lib/galaxy/datatypes/converters/interval_to_tabix_converter.py
```

![screen shot 2016-03-03 at 10 25 56 am](https://cloud.githubusercontent.com/assets/2746443/13499530/ca0e6aa4-e12c-11e5-8951-04c9c1138144.png)

![screen shot 2016-03-03 at 10 29 12 am](https://cloud.githubusercontent.com/assets/2746443/13499533/cf9e5b50-e12c-11e5-8f8b-5f41e36826a2.png)

```
Traceback (most recent call last):
 File "/galaxy-repl/instances/main/server/lib/galaxy/datatypes/converters/interval_to_tabix_converter.py", line 40, in <module>
   main()
 File "/galaxy-repl/instances/main/server/lib/galaxy/datatypes/converters/interval_to_tabix_converter.py", line 30, in main
   already_compressed=True, index_filename=out_fname)
 File "pysam/ctabix.pyx", line 738, in pysam.ctabix.tabix_index (pysam/ctabix.c:8259)
TypeError: tabix_index() got an unexpected keyword argument 'index_filename'

```

**Comment by nturaga** [comment]
@remimarenco Unable to assign you to the issue. But tagging should work.

**Comment by dannon** [comment]
This is a duplicate of #1722.  It might be that the workers aren't using the 'new' pysam, checking on that.

**Comment by nturaga** [comment]
Closing this issue cause it was duplicated. #1722 == #1849

**Comment by dannon** [comment]
Followup:  Yep, same issue, should be resolved, all workers should have teh correct pysam now.
