### ISSUE TITLE
Active Interactive Tools page doesn't populate

### ISSUE THREAD

**Issue by almahmoud** [galaxyproject/galaxy#18515]
**Describe the bug**
While having an active IT, going to `/interactivetool_entry_points/list` always renders an empty list, which doesn't refresh until you leave and come back to the page (eg: changing windows/tabs). Refreshing the page also doesn't populate the list, only leaving and coming back seems to work.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.2 / dev branch
Commit: 8274d7d5ff36837a5f0a9b843ebcec14bbc12b08

**Browser and Operating System**
Operating System: macOS
Browser: Chrome

**To Reproduce**
1. Launch IT
2. Go to /interactivetool_entry_points/list
3. Observe that list doesn't populate until one leaves the window/tab and returns

**Expected behavior**
A list populating when first going to the page and/or refreshing.

**Screenshots**
GIF below shows the issue in action, launching an IT, showing that it's active and working, going to the empty Active ITs page, then populating it by switching tabs.

![galaxy-bug-its-2024](https://github.com/galaxyproject/galaxy/assets/14061824/383ef55c-73eb-4b1c-827c-c7cba2e3891a)

**Additional context**
Using kubernetes deployment and native ITs with k8s runner (no reverse proxy etc)

**Comment by mvdbeek** [comment]
Not seeing that on usegalaxy.org or usegalaxy.eu, if I open /interactivetool_entry_points/list before or after launching the IT it always populates. If you go to your browser console do you see the polling requests ?

**Comment by almahmoud** [comment]
I see the call to `https://biocworkshop.bioconductor.org/api/entry_points?running=true` only after I switch tabs/windows.

I tried it on usegalaxy.org and can confirm the issue doesn't happen there. Given that I don't experience it on usegalaxy, I assume it has to do with the galaxy configuration rather than my browser, but not sure how to even start debugging that, so maybe finding the config diff would be a start? I believe neither usegalaxy.* use the native k8s runner for ITs. Is that true, and is there anything that comes to mind related to it that could be related? Do the usegalaxy's use a separate IT database or just another table in postgres?

More generally, if I provide a cluster with a galaxy deployment showing the bug, would it be helpful to give creds to it to someone on the team to look around?

**Comment by almahmoud** [comment]
A new datapoint, in case helpful to get a hint in the right direction: If I press the Active Interactive Tools icon in the new left-side toolbar, it goes to it populated, but if I click of "User Profile" in the blue box, or go to the URL manually, it doesn't populate until I make the window inactive and active again (switching tabs or active windows)... My gut feeling is that it's somehow related to the new celery async processes, but that was all added after I left so I don't really know where to start debugging. Any hint would be appreciated.

**Comment by mvdbeek** [comment]
Celery doesn't do any related task, I don't think that's it. All of the links go to the same component. If you need to switch tabs that might be a hint that the polling is suspended because we think the tab isn't active currently. If you close all your tabs and stay just within the same tab, does it work correctly >?

**Comment by almahmoud** [comment]
Nope still the same, and deployed on a whole new cluster, same behavior. Also got confirmation from someone else on the team that they are experiencing the same thing on a different OS/Browser (Ubuntu OS and Firefox for him, MacOS and Chrome for me), even when it's a fresh browser and it's the only tab. Switching to another window and coming back populates it, so I am fairly confident it's not something specific to my browser.

If it might be helpful to see the bug in action with browser console on your side, you could try it on your end at https://biocworkshop.bioconductor.org (Registration doesn't require confirmation email atm so can use a mock/throwaway email)

**Comment by mvdbeek** [comment]
Ah, we do need to check this on dev. The watcher used to be initiated together with the masthead (https://github.com/galaxyproject/galaxy/blob/release_24.1/client/src/components/Masthead/Masthead.vue#L92), but that's not the case anymore in dev. Any chance you could try 24.1 instead ?

**Comment by mvdbeek** [comment]
@guerler any chance you could take a look at this ? I see useEntryPointStore was removed in https://github.com/galaxyproject/galaxy/pull/17927/files#diff-53682f0577fef1489848de50f78d8f911a56bc31cc256183ce4990c8d51ed506L90

**Comment by almahmoud** [comment]
Tysm Marius for tracking it down!
I'll switch to 24.1. I used `dev` to make it easier to PR k8s runner changes upstream, but can switch to the release version for the production instance!
