### ISSUE TITLE
h5web visualisation doesn't work

### ISSUE THREAD

**Issue by dsavchenko** [galaxyproject/galaxy#18530]
**Describe the bug**
H5Web visualisation for hdf5 files doesn't work, showing `Expected group` instead. 
Tested with different files that are well visualised in web-hosted version of the lib https://h5web.panosc.eu/h5wasm

**Galaxy Version and/or server at which you observed the bug**
Tried with usegalaxy.eu (ver 24.0.3), 24.1, dev

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**
1. Upload [sample dataset](https://github.com/user-attachments/files/16164586/dset.h5.gz) (or other hdf5 file)
2. Click on visualise icon and select H5Web
3. See error

**Expected behavior**
Visualisation should work

**Screenshots**
![image](https://github.com/galaxyproject/galaxy/assets/56398430/e6ff1c0e-81fe-4e1b-8426-8e986d98dea8)

**Additional context**

**Comment by bgruening** [comment]
Is that still valid?

Also related? https://github.com/galaxyproject/galaxy/issues/14994

**Comment by mvdbeek** [comment]
That should have been fixed in #18552

**Comment by dannon** [comment]
Looks like it's working on .eu now, .org either needs the update or there's more going on here.

**Comment by mvdbeek** [comment]
Definitely has been updated many times since then. Let me know if there's anything to look at.

**Comment by dsavchenko** [comment]
I confirm it works now on our astro- staging sever with v24.1.2
