### ISSUE TITLE
Tool state: wrong tool_config path loaded

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#18556]
https://github.com/galaxyproject/galaxy/blob/65480441f94825b667009e6cfc4978ffca6889fa/lib/tool_shed/managers/tools.py#L146 only works as intended if `tool_config ` is not an absolute path, but it is an absolute path. I'm unsure if we should just strip the repo path here, or if we should reset this using a repository metadata reset.

**Comment by mvdbeek** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/18558

**Comment by jmchilton** [comment]
Broken still after deployment.
