### ISSUE TITLE
Export Data tool - bai files exported despite export-metadata-files is set as No

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#18564]
**Describe the bug**
We are exporting bam files in an aws repository by specifying their path/name and deselecting the option "Include metadata files in export?".
Two problems arise: 
1. The bai (bam index) files are exported anyway
2. The bai files are exported in the root directory and not in the path specified for the bam files

The problem is observed on main but not on the Rockefeller instance that uses {"version_major":"22.05","version_minor":"1"}.

**Galaxy Version and/or server at which you observed the bug**

Galaxy Version: Main {"version_major":"24.1","version_minor":"2.dev0"}

**To Reproduce**
1. Use tools https://usegalaxy.org/root?tool_id=export_remote
2. Select "Dataset specifying their names" for "What would you like to export"
3. Insert Dataset
4. Select any .bam file
5. Enter a path and name such as "Test_folder/test_file.bam"
6. Select a Directory URI
7. Set "Include metadata files in export?" to "No"
8. Run tool
9. Look at URI directory, the bai files are exported to the root directory, and the bam file to the specified path

**Expected behavior**
The bai files should not be exported when the option "Include metadata files in export?" is not selected.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/18659 and deployed on .org, if you want to test this again @Delphine-L
