### ISSUE TITLE
Visualizations/Charts: msa viewer stalls during data loading

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#18565]
**Describe the bug**
The MSA viewer will not load at UseGalaxy.org. It will load at other UseGalaxy servers.
Interestingly, you can name and save the still-loading visualization, plus generate a share link.

**Galaxy Version and/or server at which you observed the bug**
The Galaxy Server is running version [24.1.2.dev0 ](https://docs.galaxyproject.org/en/release_24.1/releases/24.1_announce_user.html), and the web client was built on Thursday Jul 18th 1:13:13 2024 GMT-7 .

**Browser and Operating System**
Operating System: Windows, Linux, **macOS**
Browser: Firefox, **Chrome**, Chrome-based, **Safari**

**To Reproduce**
1. Go to a fasta with multiple sequences
2. Click on chart icon
3. Select the msa viewer
4. See error: continually loading

Shared history with fasta: https://usegalaxy.org/u/jen-at-org/h/copy-of-test-charts-for-msa-viewer
Shared stalled visualization: https://usegalaxy.org/u/jen-at-org/v/hello-msa

**Expected behavior**
Load the data at ORG :)

**Screenshots**

**ORG**
![Screen Shot 2024-07-18 at 10 51 39 AM](https://github.com/user-attachments/assets/2b9098fd-4c2e-4aa8-ba22-f89e92f8c4d2)

![Screen Shot 2024-07-18 at 10 51 49 AM](https://github.com/user-attachments/assets/da04f454-5070-420f-bb4e-b8a89a793345)

Same data at **EU**
![Screen Shot 2024-07-18 at 10 56 15 AM](https://github.com/user-attachments/assets/40801e5e-7673-4fc7-b951-bfa8efd32722)

**Additional context**
* Impacts GTN tutorials
* Reported by Frederick Tan

**Comment by dannon** [comment]
A fresh build of msaview is working locally, like a build issue on .org -- following up with what's going on there.

**Comment by dannon** [comment]
This is resolved with the new dependency management and packaging approach in https://github.com/galaxyproject/galaxy/pull/18760
