### ISSUE TITLE
Workflow editor complains about missing datasets in a history.

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#1857]
Hi,

the workflow editor complains about missing datasets in a history. This is very confusing for users and the history should not be touched from the workflow editor imho. This is with 16.01.

See the following ![screenshot](https://cloud.githubusercontent.com/assets/469983/13524784/a20540b0-e1fd-11e5-9625-2bcb5abbbc1e.png).

**Comment by bgruening** [comment]
ping @pavanvidem

**Comment by blankenberg** [comment]
xref https://github.com/galaxyproject/galaxy/issues/1856

**Comment by guerler** [comment]
I can reproduce this. Looking into it.

**Comment by bgruening** [comment]
fixed by #1859
