### ISSUE TITLE
Galaxy behind galaxy_url_prefix returns invalid history link when Email notification is true

### ISSUE THREAD

**Issue by martindemko** [galaxyproject/galaxy#18572]
**Describe the bug**

One of my users noticed that the link in the email to Galaxy history with the results of the finished job is invalid (specifically, it misses the value of galaxy_url_prefix to be valid). Example:
++++++
Your Galaxy job generating dataset(s):

TideCluster on data 1: Archive with complete results,
TideCluster on data 1: GFF3 TideHunter Output,
TideCluster on data 1: GFF3 TideCluster Output,
TideCluster on data 1: Library of tandem repeats,
TideCluster on data 1: TAREAN Report

is complete as of 12:16. Click the link below to access your data:
https://repeatexplorer-elixir.cerit-sc.cz/histories/view?id=2150375cf72b6627
++++++
but the correct link must be:
https://repeatexplorer-elixir.cerit-sc.cz/galaxy/histories/view?id=2150375cf72b6627

**Galaxy Version and/or server at which you observed the bug**
`{"version_major":"23.0","version_minor":"6.dev0"}`

**Browser and Operating System**
Not relevant

**Additional context**
I remember to have a difficult time to set the whole prefix thing correctly with Nginx and although I use galaxy_url_prefix in galaxy.yml my nginx configuration is a bit different than suggested in training materials:
```
upstream galaxy_app {
        server {{ galaxy_config.gravity.gunicorn.bind }};
        # Or if you serve galaxy at a path like http(s)://fqdn/galaxy
        # Remember to set galaxy_url_prefix in the galaxy.yml file.
        # server {{ galaxy_config.gravity.gunicorn.bind }}:/galaxy;
}
server {
        ...
        location {{ galaxy_prefix }}/ {
                # This is the backend to send the requests to.
                proxy_pass http://galaxy_app;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Upgrade $http_upgrade;
        }
        ...
        location {{ galaxy_prefix }}/static {
                alias {{ galaxy_server_dir }}/static;
                expires 24h;
        }
        ...
}
```

**Comment by mvdbeek** [comment]
The value set there is `galaxy_infrastructure_url` ... this isn't at all meant to be used to generate URLs that clients would visit. I guess the quick hack is to set `galaxy_infrastructure_url` to `https://repeatexplorer-elixir.cerit-sc.cz/galaxy`, but not that this also doubles as the URL with which some optional internal services (ITs, pulsar under some circumstances) might try to communicate with your galaxy instance. You'll likely not be breaking anything by doing that, as without the `/galaxy` they'd not be connecting to the right URL anyway.

**Comment by martindemko** [comment]
I can try it, thanks for quick response Marius.

**Comment by martindemko** [comment]
Solved, thanks again
