### ISSUE TITLE
Non-English characters

### ISSUE THREAD

**Issue by arash77** [galaxyproject/galaxy#18584]
**Describe the bug**
Non-English characters in Galaxy are not well handled, leading to several issues:
- [x] The share History/Workflow/Pages/Visualization feature cannot use non-English characters in the URL. (https://github.com/galaxyproject/galaxy/pull/18986 fixes slug generation)
- [x] The name of the dataset is not displayed correctly in the request JSON and when exporting the history. (https://github.com/galaxyproject/galaxy/pull/19120 doesn't need to be fixed)
- [x] Downloading datasets and collection doesn't return the correct name of the dataset. (https://github.com/galaxyproject/galaxy/pull/19161)

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1 2.dev0
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**
1. Type non-English characters into the history name and the dataset name
2. Go to dataset details
3. See that the name of the dataset in request_json is wrong
4. Download the dataset also returns the wrong filename
5. For history, in Export history to file, it will also contain the wrong name of the dataset in `history_attrs.txt`
7. For history, in Share or Publish, it will not show the URL when there are no English characters in the history name
8. For Collections, while downloading them the file name is not the same.

**Expected behavior**
It should show all of the right characters.

**Comment by hexylena** [comment]
> Type non-English characters into the history name and the dataset name

do you have a test case for this that can easily be copy/pasted to test?

**Comment by arash77** [comment]
> > Type non-English characters into the history name and the dataset name
> 
> do you have a test case for this that can easily be copy/pasted to test?

For example:

- ä, ö, ü, ß
- تست
- 测试
- テスト

**Comment by hexylena** [comment]
Ah wow, not even RTL, oof :cry: (should test with emoji too :sweat_smile:)

**Comment by jdavcs** [comment]
@arash77 can you, please, add a checkbox list to the issue description so we can keep track of which items have been fixed (e.g. #18986 fixes slug generation)?

**Comment by arash77** [comment]
For downloading files like datasets or collections, we use `Content-Disposition: attachment; filename=file` in the response header. However, as discussed https://github.com/galaxyproject/galaxy/pull/18583#discussion_r1686749022, the filename parameter cannot include UTF-8 characters because it follows older standards like RFC 2616, which only allowed Latin-1 (ISO-8859-1) encoding.

This limitation seems outdated since newer standards like RFC 6266 and RFC 5987 allow UTF-8 characters in filenames using the filename* parameter. Modern browsers support this feature, enabling proper handling of filenames with special characters or non-Latin alphabets.

Given this, should we update our implementation to support filename* with UTF-8 encoding, or is the current approach sufficient for our needs? Supporting UTF-8 would improve usability for international filenames but might require additional testing and updates to our API.

**Comment by mvdbeek** [comment]
The limitation is not outdated, `filename*=utf-8''%e2%82%ac%20rates` is still encodable in latin-1. As such you can definitely add the additional `filename*` instruction.
