### ISSUE TITLE
Browsing tool repositories in the Admin Panel creates too many requests

### ISSUE THREAD

**Issue by davelopez** [galaxyproject/galaxy#18588]
**Describe the bug**
Browsing tool repositories, in the Admin Panel, creates too many redundant requests too frequently.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0 (likely older versions too)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Linux
Browser: Firefox, Chrome

**To Reproduce**
1. Open or search repositories in http://127.0.0.1:8081/admin/toolshed
2. Expand one of the repositories and observe the client starts polling even if there is no expected change in the status
3. Keep expanding repositories, the polling increases for each one of them

**Expected behavior**
It is ok to get the initial status but the polling should be used only if there is an expected change i.e. waiting for a non-terminal tool installation status, etc.

**Screenshots**
![TooManyRequestsBrowsingTools](https://github.com/user-attachments/assets/96f7b78a-ba6e-4d5a-b3a8-79799fda747d)

**Additional context**
Noticed by @bgruening 
After some time it could start throwing 500 errors due to the maximum database connections reached. This could be a symptom of another issue with the session of the tool_shed_install model.

**Comment by davelopez** [comment]
To fix this in a "nice" way I want to use the [resourceWatcher](https://github.com/galaxyproject/galaxy/blob/dev/client/src/composables/resourceWatcher.ts) which is available in 24.0

The component we need to fix is https://github.com/galaxyproject/galaxy/blob/dev/client/src/components/Toolshed/RepositoryDetails/Index.vue

I know is generally not a good idea to "refactor" a component as part of a bug fix, but to use the composable I need to mix composition API with options API in a really convoluted way...

Can I refactor the component to composition API first while targeting 24.0 or is this a complete no go?

The component has not been updated since 23.1 so it should be conflict-safe to merge forward.

**Comment by mvdbeek** [comment]
This doesn't really seem like a big issue, just targeting dev seems fine.
