### ISSUE TITLE
depot.galaxyproject.org server is down

### ISSUE THREAD

**Issue by ryanjameskennedy** [galaxyproject/galaxy#18597]
**Describe the bug**
The depot.galaxyproject.org server is down

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: Can't check because server is down
Commit: NA

**Browser and Operating System**
Operating System: Windows
Browser: Chrome

**To Reproduce**
1. Go to [galaxy project website](https://depot.galaxyproject.org/)
2. See error

**Expected behavior**
The website functions properly.

**Screenshots**
NA

**Additional context**
NA

**Comment by bernt-matthias** [comment]
Seems to be back.
