### ISSUE TITLE
Editing a group through admin UI can lead to duplication of user_group_association entries

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#18636]
**Describe the bug**
The number of user_group_assocation entries for Galaxy Australia’s most populous user group increased from 3,000 to 19,000 in the space of 10 minutes. In the nginx logs there were 6 requests submitted within 3 minutes of `PUT /admin/manage_users_and_roles_for_group?id=2b32d97164233881` (the same group ID) and all of these requests timed out.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Australia, release_24.1
`3be367228b531c346c10700f07d57ae44394be36`

**To Reproduce**
As admin
1) Add 1000 members to a user group. (Admin -> Groups -> *Group Name*-> Edit Permissions) and save group.
2) Add another user
3) Click Save a few times - the button is not disabled
4) Check db for multiple user_group_association entries `select user_id, group_id, count(id) from user_group_association where group_id = <group_id> group by user_id, group_id having count(id) > 1;`

**Expected behavior**
If a user_group_association exists for user X, group Y another one will not be created.

**Comment by nuwang** [comment]
There are several related problems that seem to be causing this:
1. The database does not have a unique constraint on the (user_id, group_id) combination
2. When a number of users are added/removed from a group [here](https://github.com/galaxyproject/galaxy/blob/7b34535e0bd4c73e3f93b57db8427719e4889914/lib/galaxy/model/security.py#L717), it's not an atomic operation. This means that two operations modifying the same group result in an indeterminate outcome. (And currently, the lack of a unique constraint means that the same user could be associated multiple times with the same group).
3. The same issue is probably present for [`associate_user_role`](https://github.com/galaxyproject/galaxy/blob/7b34535e0bd4c73e3f93b57db8427719e4889914/lib/galaxy/model/security.py#L724), [`associate_group_role`](https://github.com/galaxyproject/galaxy/blob/7b34535e0bd4c73e3f93b57db8427719e4889914/lib/galaxy/model/security.py#L731) and [`associate_action_dataset_role`](https://github.com/galaxyproject/galaxy/blob/7b34535e0bd4c73e3f93b57db8427719e4889914/lib/galaxy/model/security.py#L738).

**Comment by jdavcs** [comment]
Reproduced. Most likely, this must have been caused by clicking the Save button repeatedly. The problem is multi-fold: (a) there should be a unique constraint that will prevent such duplicate records; and (b) the creation of multiple association records is very slow (If 1000 users are selected, we execute 1000 insert statements in 1000 transactions. Yikes.) Also, the button should not be clickable once the request has been submitted (even after we optimize for speed); (c) as @nuwang mentioned, running more than one such admin operation involving a sufficient overlap of data may lead to an indeterminate outcome; etc.

This issue is indeed present on multiple tables. Here're some sample duplicate counts for main and eu:
```
user-group-assoc                                                                                                                                                                  
main: 307                                                                                                                                                                                    
eu: 13939                                                                                                                                                                                    
                                                                                                                                                                                             
user-role-assoc                                                                                                                                                                              
main: 1                                                                                                                                                                                      
eu: 283                                                                                                                                                                                      
                                                                                                                                                                                             
group-role-assoc                                                                                                                                                                             
main: 0                                                                                                                                                                                      
eu: 1751                                                                                                                                                                                     
                                                                                                                                                     
history_user_share_association                                                                                                                                                               
main: 403                                                                                                                                                                                    
eu: 381
                                                                                                                                                                                             
dataset-permission                                                                                                                                                                           
main: 23372                                                                                                                                                                                  
eu: estimate: x3 compared to main
```

There will be separate solutions for each model/table.  I think, each should include the following:
- client-side fix preventing multiple clicks (hide/disable button, show spinnining wheel, show "updating..." message, etc.)
- optimized insert (batch insert or, at least, one transaction only)
- data migration to delete duplicate records
- db schema migration adding the constraint

This will include multiple db schema and data migrations. Given that this issue is not new (on main user-group-assoc records go back to 2021-06-17), I would suggest fixing this on dev, not a previous release. @cat-bro would that be acceptable? Or do we need to fix this for the current release?

@bgruening :point_up: FYI.

**Comment by mvdbeek** [comment]
Can you post the queries you've used and you've also verified that the user group association entries are not created intentionally ?

**Comment by jdavcs** [comment]
Here's a query for the user-group-association: 
```
galaxy_main=> select count(*) from user_group_association; select count(distinct(user_id, group_id)) from user_group_association;
 count 
-------
  1050
(1 row)

 count 
-------
   743
(1 row)

```

**Comment by jdavcs** [comment]
> ... and you've also verified that the user group association entries are not created intentionally ?
I don't think I can verify that, but I can't imagine why they would be created intentionally.

**Comment by mvdbeek** [comment]
I don't know, an association of associations ?
Spot-checking this it looks like we never refer to the association id anywhere, so it's probably fine, but we should check carefully.

**Comment by mvdbeek** [comment]
> dataset-permission                                                                                                                                                                           
> main: 23372                                                                                                                                                                                  
> eu: estimate: x3 compared to main

This one has an action column, at a minimum the query should include the action in the  distinct clause.

**Comment by jdavcs** [comment]
> I don't know, an association of associations ? Spot-checking this it looks like we never refer to the association id anywhere, so it's probably fine, but we should check carefully.

I see what you mean. I didn't check that - it is my understanding that the use of a surrogate primary key (the `id` column) as opposed to a composite key was just a matter of convenience. But that doesn't mean it didn't get used for whatever reason at some point. I'll check for this for each such proposed fix.

Also, this -
> This one has an action column, at a minimum the query should include the action in the distinct clause.

I used a different query for this table that included the `action` column along with the dataset_id and the role_id.

**Comment by mvdbeek** [comment]
> a matter of convenience.

you're being generous, I think we just didn't know better 😆

**Comment by bgruening** [comment]
```
galaxy=> select count(*) from user_group_association; select count(distinct(user_id, group_id)) from user_group_association;
 count 
-------
 25642
(1 row)

 count 
-------
 11703
(1 row)

**Comment by bgruening** [comment]
ping @mira-miracoli and @sanjaysrikakulam ...

**Comment by mvdbeek** [comment]
To be clear, none of this is really a problem beyond it being duplicates. 25K rows is nothing in the larger scheme of things.

**Comment by cat-bro** [comment]
>  I would suggest fixing this on dev, not a previous release. @cat-bro would that be acceptable?

That is fine, thanks @jdavcs !
