### ISSUE TITLE
Keep file size record for purged datasets

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#18648]
Galaxy Australia, release_24.1

Steps to reproduce:
(1) Upload a dataset
(2) Look at file size on the dataset info page
(3) Delete the dataset permanently
(4) Refresh the dataset info page. The dataset size is now '-'

I think this must be new because I look at past job data frequently for the purpose of updating TPV memory allocations. I only recently started seeing jobs with 0 bytes of input.

Not sure if this is a bug.

**Comment by mvdbeek** [comment]
It is not a bug, the file size column is used to calculate the user quota. If the file size is shown while all references to the underlying dataset are purged, that would be a bug.

**Comment by cat-bro** [comment]
Seem like it would be possible to display correctly to the user (if purged display 0) without actually losing the historic size info. Is that being saved anywhere?

**Comment by mvdbeek** [comment]
> It is not a bug, the file size column is used to calculate the user quota.

As @natefoo pointed out, we are of course excluding purged data from quota calculation, and we have indeed only recently started setting the file size to 0 (https://github.com/galaxyproject/galaxy/pull/18342/commits/50b7f8f8daa98d6a22e042744914f4fd13fad19e).
