### ISSUE TITLE
Switch to standard pip

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#1864]
Now that manylinux1/PEP 513 wheels are official and will be supported in pip 8.1 (as of pypa/pip#3497), and because only our psycopg2 wheels use our ["platform specific" wheels](https://docs.galaxyproject.org/en/master/admin/framework_dependencies.html#galaxy-pip-and-wheel), if we simply build psycopg2 (and the rest of our C extension dependencies) as manylinux1 wheels, we can use standard pip 8.1. While I do think there's a use case for "platform specific" wheels (the list of libs bundled into the psycopg2 manylinux1 wheel is pretty extensive, for example), this is a reasonable solution until some future time when we get around to getting official support for platform specific wheels into pip/PyPI/wheel.

**Comment by martenson** [comment]
done (right @natefoo ?)
