### ISSUE TITLE
Importing all datasets from a data library broken

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#18666]
**Describe the bug**

@wm75 via matrix:

> selecting all datasets with the checkbox on top triggers
> XHRGET https://usegalaxy.eu/api/folders/F6bccacbbbe7eae47/contents?limit=0
> which fails with Input should be greater than or equal to 1 in ('query', 'limit')

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.0

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**
1. Go to https://usegalaxy.eu/libraries/folders/F6bccacbbbe7eae47/page/1
2. Click on Checkbox on top to select all datasets
3. Try to Add to History.

Screen greys out and nothing happens.

**Comment by wm75** [comment]
https://github.com/galaxyproject/galaxy/pull/18044 is what broke this I think because checking all datasets triggers a https://usegalaxy.eu/api/folders/F6bccacbbbe7eae47/contents?limit=0 query.

**Comment by davelopez** [comment]
I'll try to fix it

**Comment by davelopez** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/18687
