### ISSUE TITLE
Changing current history with a populated uploader prevents users from beginning upload

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#18662]
**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1.2.dev0 (usegalaxy.org)

**To Reproduce**
1. Open the Uploader
2. Add a file to upload (local file or paste)
3. Do not start upload yet, and exit the modal
4. Change your current history
5. Open Uploader again
6. Click Start but nothing happens

**Expected behavior**
Clicking Start should start the upload into this changed current history

**Screencast**

https://github.com/user-attachments/assets/2bac4031-8625-4c3f-92b0-ed6eebbecd7c

**Comment by davelopez** [comment]
Just to make sure I got this right. 
If we have files in the upload that have not yet been sent to the current history and we change the current history:
- Option 1: the upload queue stops and the remaining files to be uploaded will now target the "new" current history.
- Option 2: we reset the current upload queue and start fresh for the new current history.
- Option 3: something else I didn't get...

What option did we decide on for the fix?

**Comment by mvdbeek** [comment]
Uploads that are defined at the time of clicking the start button go to the current history.

**Comment by davelopez** [comment]
Got it now thanks! :+1:

**Comment by davelopez** [comment]
This should be fixed by https://github.com/galaxyproject/galaxy/pull/18703
