### ISSUE TITLE
Changing datatype with "Pick value" tool in a workflow doesn't work

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#18677]
**Describe the bug**
I want to convert a bed from a bedgraph in a Workflow. 
From tool A I get a bed file as output. I need to use this output with 2 other tools, one take a bed, the other a bedgraph. So I want to use the "Pick value" tool to change the datatype from bed to bedgraph. However the output of "Pick value" remains bed when I run the workflow.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1 both on main and eu

**Browser and Operating System**
Operating System:  macOS
Browser: Chrome

**To Reproduce**
1. Import workflow https://usegalaxy.org/u/delphinel/w/test-output-format-imported-from-uploaded-file
2. Import history https://usegalaxy.org/u/delphinel/h/test-format-change
3. Run the workflow on the bed file (1. seqtktelo)
4. While the job is running, the format is 'bedgraph', but once green the format changes to 'bed'

**Expected behavior**
The output of the "Pick Value" tool should be 'bedgraph'

**Screenshots**
![image](https://github.com/user-attachments/assets/d9fb54d6-32d9-4571-8769-c99e33329970)
![image](https://github.com/user-attachments/assets/87325760-3aef-4fab-bde2-87664a54b17e)

**Additional context**
Note: the connection between tools in the workflow editor is working well, it behave as if the output of "pick value" is a bedgraph, but at run time the tool using the bedgraph is paused.

**Comment by mvdbeek** [comment]
We do have a test showing that this works though. A datatype mismatch should not lead to a downstream tool being paused, that should only happen if a job error occurred. Can you share your history ?

**Comment by mvdbeek** [comment]
Well that's fun 😅:

![Screenshot 2024-08-13 at 11 54 18](https://github.com/user-attachments/assets/b9f4dc1a-6553-49df-84b4-e72778a087f8)

but it finishes as a bed file.

**Comment by Delphine-L** [comment]
> We do have a test showing that this works in principle. A datatype mismatch should not lead to a downstream tool being paused, that should only happen if a job error occurred. Can you share your history ?

https://usegalaxy.eu/u/delphine-l/h/treevalgaljuly31optionalwindowmasker-2-species

But it look like the paused jobs are actually unrelated? the inputs are green in the history but red in the info page (dataset 559)...
![Screenshot 2024-08-13 at 7 27 45 AM](https://github.com/user-attachments/assets/76af5187-9a5f-493d-9c5f-48df3c2538dc)

**Comment by mvdbeek** [comment]
It seems like you're relying on an implicit conversion to bigwig, this requires a dbkey to be set. I assume that doesn't really make sense when you're assembling a genome.
