### ISSUE TITLE
Dataset collection elements cannot be dragged into tool form

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#18692]
**Describe the bug**
Dataset collection elements cannot be dragged into tool form.
Enter a collection and attempt dragging the element.

**Galaxy Version and/or server at which you observed the bug**
24.1

**Browser and Operating System**
Operating System: Windows, Linux, macOS
Browser: Firefox, Chrome, Chrome-based, Safari

![drag collection element](https://github.com/user-attachments/assets/eeab9736-4bc9-4852-af65-31ce5c0a2f6f)

**Comment by ahmedhamidawan** [comment]
Fixed in #18699
