### ISSUE TITLE
Make Workflow Invocations for Public Workflows shareable

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#18695]
As discussed in https://galaxy.slack.com/archives/C02HJDML6/p1723055111792019, it would be useful if a workflow is shared/published, its invocations being shareable as well would be a useful enhancement.

As of now, since the invocations are not published, we get this at the top of a workflow report, as shared by @abueg :
![image](https://github.com/user-attachments/assets/407effd0-5134-4e9f-b0da-27ece91ba4e0)

**Comment by mvdbeek** [comment]
In the meantime making an invocation's history shared might also be used to allow user access to the invocation (as a quick proxy ... it might still be worth sharing or publishing invocations).

**Comment by mvdbeek** [comment]
I'm gonna to the backend for the history access checks ... it is already there and we just need to flip the security checks from owned to accessible.

**Comment by mvdbeek** [comment]
If you share a history that contains an invocation the invocation also becomes accessible now. What is missing is some hint that you might want to share the history if you make a page accessible that references a history or an invocation.

**Comment by ahmedhamidawan** [comment]
I have shared a history (made it published and even individually shared with the other user) but I still get this:

![image](https://github.com/user-attachments/assets/98e43606-3815-4115-91ec-73f09ccc4161)

when I get to the invocation route from the other user. Is that still expected?

**Comment by mvdbeek** [comment]
Thanks for checking, my test didn't actually use a user that wouldn't have access to the invocation 🤣. Should be fixed in https://github.com/galaxyproject/galaxy/pull/18746
