### ISSUE TITLE
Invocation scheduling error message in a subworkflow + infinity scrolling

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#18697]
**Describe the bug**
I have a workflow that apparently ran fine, all the datasets in the history are present and green. However, when I look at the invocation overview,  on a specific subworkflow,  I get an error message : 
"Invocation scheduling failed because step 9 depends on output 'output' of step 3, but this step did not produce an output of that name."
And an infinite number of the same message error (see screen capture)
Observed on main and eu on two versions of the same workflow/subworkflow . Note: On eu, I observe this error before the inputs for the subworkflow are ready and therefore before it ran. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1 main and eu

**Browser and Operating System**
Operating System: macOS
Browser:  Chrome

**To Reproduce**
No idea how to repeat it on a smaller workflow. the subworkflow run fine by itself, but in the workflow it causes weird invocation errors. 
Here are the links : 
On org : 
- Invocation : https://usegalaxy.org/workflows/invocations/a11d3f54288f2b34?from_panel=true
- Workflow : https://usegalaxy.org/u/delphinel/w/treevalgaljuly31optionalwindowmasker-imported-from-uploaded-file
- History: https://usegalaxy.org/u/delphinel/h/test-treevalgal
On eu : 
- Invocation : https://usegalaxy.eu/workflows/invocations/7543743598369d46?from_panel=true
- Workflow : https://usegalaxy.eu/u/delphine-l/w/treevalgalaug12
- History: https://usegalaxy.eu/u/delphine-l/h/copy-of-treevalgaltest5kbralanc5

**Expected behavior**
No infinite scrolling, and no error if the subworkflow ran without problems. 

**Screenshots**

https://github.com/user-attachments/assets/4038345d-ad09-479c-b8c1-5ac73e783275

**Comment by mvdbeek** [comment]
> subworkflow ran without problems.

I am sure there is a problem in your subworkflow, we don't produce this message unless there is a scheduling error. The error does mean that you cannot see anything in the history ... after all we were not able to schedule the step because an output that is used as an input has not been produced.

**Comment by Delphine-L** [comment]
> after all we were not able to schedule the step because an output that is used as an input has not been produced.

What I mean is that all the outputs expected from this subworkflow are produced, and used in the rest of the workflow as if there was no error. 

This error message appears when the input is not ready yet, still running (repeatmasker in the screenshot).  But once it's ready it appears as if the subworkflow ran as it should. I get the Jbrowse instance with all the tracks produced by this subworkflow. 

![Screenshot 2024-08-13 at 2 17 35 PM](https://github.com/user-attachments/assets/9ba51134-f5f9-43a5-8a9d-e6f4775d1296)

**Comment by Delphine-L** [comment]
I downsized the workflow as much as I can while still getting the error: 
Here is the workflow : https://usegalaxy.org/u/delphinel/w/errorinvocation
A history to try it : https://usegalaxy.org/u/delphinel/h/invocation-error

Parameters for the Workflow: 
- Genome assembly to report on : `sub_ref.fasta`
- Will you supply an independent reference genome : `No`
- Independent haplotype or reference genome if available :  `Nothing`
- Will you provide a collection of related species for sequence similarity mapping: `yes`
- Collection of related species: `related species`

Exemple of invocation showing the error : https://usegalaxy.org/workflows/invocations/81739709a81a550d?from_panel=true

![image](https://github.com/user-attachments/assets/77cd196a-5d80-4c93-b79a-c0c2e01cb1cd)

**Comment by Delphine-L** [comment]
> I downsized the workflow as much as I can while still getting the error: 

Actually downsized it even more : 
Workflow : https://usegalaxy.org/u/delphinel/w/test9
History : https://usegalaxy.org/u/delphinel/h/invocation-error

Parameters for the Workflow:
- Genome assembly to report on : sub_ref.fasta
- Will you supply an independent reference genome : No or yes, both fail
- Independent haplotype or reference genome if available : sub_ref.fasta

**Comment by ahmedhamidawan** [comment]
At the subworkflow route:
<img src="https://github.com/user-attachments/assets/52abe9ba-04bd-4c6c-9d2d-017cc509aa23" />

looking at the invocation JSON, there are duplicate error messages for some reason:
```json
{
  "model_class": "WorkflowInvocation",
  ...
  "messages": [
    {
      "reason": "output_not_found",
      "workflow_step_id": 3,
      "output_name": "output",
      "dependent_workflow_step_id": 2
    },
    {
      "reason": "output_not_found",
      "workflow_step_id": 3,
      "output_name": "output",
      "dependent_workflow_step_id": 2
    },
    {
      "reason": "output_not_found",
      "workflow_step_id": 3,
      "output_name": "output",
      "dependent_workflow_step_id": 2
    },
    {
      "reason": "output_not_found",
      "workflow_step_id": 3,
      "output_name": "output",
      "dependent_workflow_step_id": 2
    },
    {
      "reason": "output_not_found",
      "workflow_step_id": 3,
      "output_name": "output",
      "dependent_workflow_step_id": 2
    },
    {
      "reason": "output_not_found",
      "workflow_step_id": 3,
      "output_name": "output",
      "dependent_workflow_step_id": 2
    },
    {
      "reason": "output_not_found",
      "workflow_step_id": 3,
      "output_name": "output",
      "dependent_workflow_step_id": 2
    },
    {
      "reason": "output_not_found",
      "workflow_step_id": 3,
      "output_name": "output",
      "dependent_workflow_step_id": 2
    }
  ]
}
```

**Comment by ahmedhamidawan** [comment]
@Delphine-L Could you please also share the link of the subworkflow?

**Comment by mvdbeek** [comment]
@ahmedhamidawan you can download the workflow, it contains the subworkflow, or take the yaml workflow in https://github.com/galaxyproject/galaxy/pull/18731/commits/565911e85f1aa949ddd74ab873ccc75fbdd9f3ed and upload that to your dev instance.

**Comment by ahmedhamidawan** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/18730
