### ISSUE TITLE
API: named tags broken when uploading data to a library

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#18700]
**Describe the bug**
Some change over the last week broke the BioBlend test `TestGalaxyLibraries.test_upload_file_contents_with_tags` with the following error:

```
    @test_util.skip_unless_galaxy("release_19.09")
    def test_upload_file_contents_with_tags(self):
        datasets = self.gi.libraries.upload_file_contents(self.library["id"], FOO_DATA, tags=["name:foobar", "barfoo"])
        dataset_show = self.gi.libraries.show_dataset(self.library["id"], datasets[0]["id"])
>       assert listify(dataset_show["tags"]) == ["name:foobar", "barfoo"]
E       AssertionError: assert ['name:name:f...'name:barfoo'] == ['name:foobar', 'barfoo']
E         
E         At index 0 diff: 'name:name:foobar' != 'name:foobar'
E         
E         Full diff:
E           [
E         -     'name:foobar',
E         +     'name:name:foobar',...
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: dev
Commit: dev as 2024-08-13

**To Reproduce**
1. See https://github.com/galaxyproject/bioblend/actions/runs/10361199784/job/28681057831

**Expected behavior**
BioBlend test not failing on Galaxy dev.

**Comment by davelopez** [comment]
I'll investigate this
