### ISSUE TITLE
Fasta.gz implicitely converted to tabular instead of fasta with text inputs

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#18709]
**Describe the bug**
When trying to use a text processing tool on a fasta.gz, the tool converts it to tabular before running. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1 main and eu

**Browser and Operating System**
Operating System:  macOS
Browser: Chrome

**To Reproduce**
1. Use history : https://usegalaxy.org/u/delphinel/h/compressed-fasta
2. use any text processing tool (eg https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_replace_in_line/9.3+galaxy1)
3. See that the dataset appears as `Compressed Fasta (as tabular)`
4. After running the dataset is a fast converted to tabular

**Expected behavior**
For text inputs, the conversion should be from fasta.gz to fasta  

**Screenshots**

![Screenshot 2024-08-15 at 12 10 24 PM](https://github.com/user-attachments/assets/5ee50037-2c05-4251-b740-477572ae80df)

**Comment by mvdbeek** [comment]
For now I'd add an explicit decompression step. The problem is that that is a valid conversion, just not the one you actually want.
