### ISSUE TITLE
Invocation view polls rapidly on 403, loading forever

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#18723]
Open a private window and go to https://usegalaxy.org/workflows/invocations/0fb8b2f47669089b?from_panel=true
![Screenshot 2024-08-20 at 11 30 19](https://github.com/user-attachments/assets/bd9a1034-f5c1-4a10-93fd-1b28eb63cd1d)

We need some error handling here.

**Comment by ahmedhamidawan** [comment]
Fixed in #18726
