### ISSUE TITLE
change style in html output

### ISSUE THREAD

**Issue by methylome** [galaxyproject/galaxy#1872]
My tool generates a html file but "view data" doesn't correctly show specified style, e.g., the font size of a table using `<table style="font-size:10pt;">` on release 16_01. The downloaded html file is displayed correctly. Is this expected?

**Comment by dannon** [comment]
The sanitization is expected.  Instance administrators can whitelist particular tools which are known to be 'safe' to display HTML output from, or they can disable display sanitization altogether.  See 'sanitize_all_html' and 'sanitize_whitelist_file' information in galaxy.ini for more.

**Comment by dannon** [comment]
Reopening, because we may be able to look into relaxing some of the slightly more draconian sanitization going on (inline css, like here, for example).

**Comment by methylome** [comment]
Thanks a lot for your quick reply. I can change it.

**Comment by hexylena** [comment]
@dannon I know you mean "relaxing rules in general", but I'd be -1 on inline css specifically. We should be working towards the ability to use strict CSP.

**Comment by dannon** [comment]
@erasche I have a branch where I'm swapping everything over to using bleach (https://github.com/mozilla/bleach) right now, which we can then relax a bit.  I think strict CSP is a long way away.

**Comment by hexylena** [comment]
@dannon okay, sounds great. <3 bleach.

Agreed, CSP is a ways away, I just wanted to keep it in mind.

**Comment by dannon** [comment]
@erasche The bleach work was finished by @nsoranzo as a part of https://github.com/galaxyproject/galaxy/pull/5642.  I'm going to go ahead and close this issue out, since handling should at this point be consistent (and reasonably mainstream) now, with the option to whitelist tools as always.
