### ISSUE TITLE
Option to set "persistent header" in history panel so that scroll moves only through datasets

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1873]
**The "header of a History panel"? What is it and why would it be useful to view/access it without scrolling back all the way up?:** 

The top portion of the history panel can contain important user-added notes about dataset sources and content (in the comments) _but more importantly_, it is where batch operations, tags, and general history metadata are reported. In this context, this top section could be considered a "header" in the same way that certain files have headers that label data columns, etc. and could be set to remain "at the top" for quick access minus the "back to the top" scrolling. Most apps have read-only headers, but in this case, the header would not only have labels (history name, number of datasets active, hidden, deleted - along with display toggle links) but also access to batch dataset functions.

**Enhancement request:** 

It would be a usage convenience feature to be able to have this top portion of the history panel remain persistently at the top of the panel, while the scroll through the datasets moved only through datasets. It would be extra nice if this was an a user set toggle - keep this header section at the top (new default?) or allow the user to revert to the current way a history is viewed in the UI (header scrolls up along with datasets).

**Usage example 1**: 

Access the batch operation features while in the middle of reviewing a history that contains many datasets. Currently, one has to scroll back up to the top, set options, then scroll back again through the datasets, _essentially losing their place among the list of datasets_. **If left as a header, the operations would be accessible for use while targeting datasets lower in the panel scroll window.**

**Usage example 2**: 

Annotation for the history often has notes about which datasets contain different conditions, replicate groups, reference genomes in use, or related. Again, if left as a header, moving through datasets with this annotation visible would be helpful. **It may even make the annotation field a more useful feature to store notes about content in general if it was persistently accessible even in large histories with many datasets.**

Other usage examples are likely obvious.

@carlfeberhard & others .. thoughts?

**Comment by carlfeberhard** [comment]
Yeah - sounds good and good points (and really awesome description/details - thanks for that).

**Comment by jennaj** [comment]
@carlfeberhard Thanks for considering the idea :)

and thanks @nsoranzo for fixing my typo!

**Comment by carlfeberhard** [comment]
An initial take on this is in #2588. It could be further improved by 'compacting' the history header when scrolling down and away from the top.

**Comment by jennaj** [comment]
@carlfeberhard A large and well thought out suite of changes! Thanks for adding this one in.

For comments from @bgruening over there about making usage more obvious (UX stuff), I wonder if we could add in help comments. Options I can think of (certainly are others). We want people to find and use these functions ;)
1. Pop-up help with very short, summarized help text (perhaps not realistic, with so many functions to cover)
2. OR links to the new wiki or some dedicated 'UI help" github wiki (both not ideal, as they move the user's attention to a place external to Galaxy)
3. OR pop-up topic "point-support" in a structured set of docs-text-video-tutorial help built-in to Galaxy (best, IMHO, yet has drawbacks, mainly because involves a new functionality and derivative maintainance). That said, this is a common approach and one that I find useful at other sites/apps.

Too much to discuss here .. belongs in a new enhancement request. If anyone else likes the ideas - or rather the idea that we should think about this and gather ideas - I'll make a new ticket.

**Comment by sszakony** [comment]
I'm assuming all the elements in the following screenshot are desired to remain at the top of the screen, immune to scrolling? I recently submitted a change to the tool panel to keep the search elements stationary, and I'm willing to enable this in the history panel.

![image](https://cloud.githubusercontent.com/assets/9634629/17413980/7ab8be8e-5a51-11e6-895c-ca059efe04e0.png)

**Comment by carlfeberhard** [comment]
Heya, @sszakony Thanks for the offer. This is already done in the dev branch - sorry, I should have closed this issue when 2588 got merged.
