### ISSUE TITLE
Strange screen when using 'Resume paused jobs'

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#18736]
**Describe the bug**
When I click on 'Resume paused jobs' I get this:
![image](https://github.com/user-attachments/assets/02259d91-74e0-4708-aada-9d86f4f471d3)

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.eu {"version_major":"24.1","version_minor":"2.dev0"}

**Browser and Operating System**
Operating System:  Linux, 
Browser: Firefox

This happened because I ran out of disk space and then when I purged a history and restarted, I got this screen. It happened systematically.

**Comment by bgruening** [comment]
This should be fixed since a few hours: https://github.com/galaxyproject/galaxy/pull/18733
