### ISSUE TITLE
[Feature request] Add Directory URI as a type of workflow input

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#18780]
I am using workflows for the VGP project to export files to an AWS repository. These are big workflows with several instances of the "export datasets to remote file sources" tool. Each of these instances requires setting the destination at run time, which means the user must select the path several times at each run. It would be nice to have an input parameter that accepts this input format so it only needs to be set once.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1

**Screenshots**
![Screenshot 2024-09-05 at 10 56 41 AM](https://github.com/user-attachments/assets/31f52d7f-3ed2-486b-9bc3-9a73638cffdc)

**Comment by mvdbeek** [comment]
Done in https://github.com/galaxyproject/galaxy/pull/19093
