### ISSUE TITLE
Attempting to run a workflow takes you to Galaxy Tours

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#1878]
This is in the dev branch

![workflow_run](https://cloud.githubusercontent.com/assets/6947053/13570959/9656d942-e43f-11e5-8f3d-babc0e40ce0b.png)

![tours](https://cloud.githubusercontent.com/assets/6947053/13570969/a6c9ac32-e43f-11e5-8404-a96ea406285d.png)

**Comment by dannon** [comment]
Well that's a new one.  Give me a sec.

**Comment by dannon** [comment]
Ok, I see what's happening here.  With #1870 I added multiple routes mapping to root:index, and the first of those that shows up in the url_for lookup table happens to be a tour route.  Not great, and we'll probably see this happening elsewhere in the app where we use `url_for(controller='root', action='index')` too, so I'm looking into options.

**Comment by dannon** [comment]
Thanks for the bug report, should be resolved in #1879
