### ISSUE TITLE
pick_value tool at v0.2.0 misbehaves when first value is null

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#18795]
Observed with a WF from @Sch-Da.

When the first value to pick from is the output of a skipped step that dataset's type is expression.json and with the change in galaxyproject/tools-iuc#5716 this is what will be used as the output's datatype and hang at metadata detection afterwards (if the picked dataset's content is sufficiently complex I guess).

Version 0.1.0 of the tool works fine with the inputs in the WF (though requiring a change of datatype data to a fixed known datatype).

@Sch-Da maybe you can share a minimal example history here?

**Comment by Sch-Da** [comment]
> well, under output options.

Found. sorry for the confusion, thank you.
