### ISSUE TITLE
sqlite3 error on a local copy of galaxy

### ISSUE THREAD

**Issue by rajkaran27** [galaxyproject/galaxy#18817]
**Describe the bug**
I cloned and hosted a copy of Galaxy version 24.2 . When I tried running a custom tool, or tried uploading a file, I got this error:
```
(sqlite3.OperationalError)
near
"FROM". syntax error
[SQL:
UPDATE history_dataset_association
SET
info = ?,
update_time=?
FROM dataset
WHERE
history_dataset
```

The SQL query from the update_output_states function seems to be wrong:
```

           UPDATE history_dataset_association
            SET
                info = :info,
                update_time = :update_time
            FROM dataset
            WHERE
                history_dataset_association.dataset_id = dataset.id
                AND dataset.job_id = :job_id;


```
This function is located in /galaxy/packages/data/galaxy/model/__init__.py .

**Galaxy Version**
Galaxy Version: 24.2

**Browser and Operating System**
Operating System: Linux
Browser: Microsoft Edge, Google Chrome

**To Reproduce**
1. [Follow first 4 steps to deploy Galaxy on Linux](https://galaxyproject.org/admin/get-galaxy/)
2. Upload a file of any type.
3. See error

**Expected Output**
The file should be successfully uploaded and accessible for viewing.

**Additional context**
Many proposed solutions recommend migrating to PostgreSQL for production environments. However, this specific error appears to only occur in the current version of Galaxy.

**Comment by mvdbeek** [comment]
Your Python version needs to be compiled against a more recent copy of sqlite3, see https://github.com/galaxyproject/galaxy/issues/18380. The easiest way to do this is to update to a newer python version.
