### ISSUE TITLE
Extra user preferences not available when using remote users

### ISSUE THREAD

**Issue by dometto** [galaxyproject/galaxy#18823]
## Description

In order to let users set [vault secrets or extra user preferences](https://docs.galaxyproject.org/en/master/admin/special_topics/vault.html), which can then be leveraged in tools and data/files sources, the user needs access to the `/users/information` route.  However, this currently is impossible when using the `use_remote_user: true` configuration option. Access to the relevant route is blocked [here](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/web/framework/middleware/remoteuser.py#L163-L202).

I imagine this is because the `/user/information` route also allows the user to edit their email address and username, which is clearly undesirable when these are being provided by an external identity provider. However, at the moment this blocks any Galaxy instance using remote users from using important Galaxy features (vault secrets and extra user preferences).

I've investigated a little bit and was able to verify that in principle, it should be possible to use user preferences/vault with remote users. See below.

Apologies if I've missed a way of setting user preferences and vault secrets when using remote users, and would be very grateful if someone could point me in the right direction if so!

## Suggested fix

I would suggest either:

1. Creating a separate route/view, e.g. `/user/extra_preferences`, in which the fields defined in `user_preferences_extra_conf.yml` can be set.
2. Making the controller and view logic for `/user/information` a bit more flexible, so that it allows setting the extra preferences but not changing email and username, when `use_remote_user` is `true`.

### Verification

I've tried to test the contours of the above solutions by simply adding `/user/information` to the [allow list](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/web/framework/middleware/remoteuser.py#L163) here. When doing so, I can successfully reference user preferences from inside a tool, with `use_remote_user` set to `true`.

So it indeed seems that the only thing blocking this is the fact that the UI blocks the relevant route.

**Comment by dometto** [comment]
Since we need the combination of the user preferences functionality and remote users, we would be happy to submit a PR implementing either suggested solution (or another one if preferred). Can someone explain what would be the path to getting such a patch merged?

**Comment by hexylena** [comment]
I suspect the second solution would be preferred.

@dannon you self assigned, will this be discussed in a meeting at some point? I think they're keen to implement it, if y'all have a preference of which method.

**Comment by dannon** [comment]
Yes, we'd love the contribution and discussed this issue on the weekly call briefly -- I flagged myself on here only to remember to follow up later with advice.  Option 2 is the way to go, as long as the user can't change email/username it's safe to expose the rest.

**Comment by dometto** [comment]
Pinging @dannon just to draw attention to the fact that the PR is now open: #18887

**Comment by dannon** [comment]
@dometto Awesome, I'll check it out!
