### ISSUE TITLE
get ur gyatt out of github right now

### ISSUE THREAD

**Issue by antilogical2** [galaxyproject/galaxy#18837]
**Describe the bug**

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Windows, Linux, macOS
Browser: Firefox, Chrome, Chrome-based, Safari

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dannon** [comment]
I assume this is garbage.
