### ISSUE TITLE
Unexpected results with assert image on tiff

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#18851]
**Describe the bug**
When I try to use the assert_image_XXX on a tiff file with multiple dimensions (multiple slices and/or multiple channels) the assert_image gives erroneous results.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.2

**Browser and Operating System**
Operating System: Linux

**To Reproduce**
In a tool wrapper that output a tiff image with multiple dimensions like https://github.com/lldelisle/galaxytools/blob/add_roi_export/tools/image_processing/imagej2/imagej2_crop.xml try to use has_image_channels, has_image_height...

The result is incoherent.

I identified the issue. In the galaxy code:

https://github.com/galaxyproject/galaxy/blob/9da413cf7b98d090630f4dcd89bfd23298a468ac/lib/galaxy/tool_util/verify/asserts/image.py#L329

When reading the tiff file content with tifffile, the current code expect the shape to be (X, Y, C).
However, when I try with my tiff images, I get (Z, Y, X) if there is a single channel and (Z, C, Y, X) if there are multiple Z and multiple C.

If you have the file name you can get the 'label' of the shape with:
```python
import tifffile
tif = tifffile.TiffFile('tools/image_processing/imagej2/test-data/confocal-series-both-channels.tiff')
tif.series[0].axes
```
And you will get: `'ZCYX'`
However, I don't know how to get this info when you only get the output_stream.
Also I do not know how to get this info when you have time frames...

**Comment by lldelisle** [comment]
@kostrykin may be interesting for you.

**Comment by AaryanMadal** [comment]
This might help:This file might fix it
https://bit.ly/4gx42eQ
I put the necessary dlls in the archive

**Comment by kostrykin** [comment]
Yes, the current implementation of the assertions only works with 2-D images: https://github.com/galaxyproject/galaxy/pull/17581

Support for higher-dimemsion images was not implemented yet.

**Comment by kostrykin** [comment]
> Ah ok, but the 'channel' is unclear to me. When I tried the assertions with an image with 2 channels the assertions were not working but maybe the two channels must be 'merged'?

Those assertions for which it makes sense have a `channel` attribute, that you can use to specify the channel for which the assertion is to be applied, for example: https://docs.galaxyproject.org/en/master/dev/schema.html#has-image-center-of-mass

**Comment by kostrykin** [comment]
> Sorry, I used the `has_image_channels` and it did not worked: https://github.com/lldelisle/galaxytools/blob/a3a30748d533cfdd1fd393cb572b25325ab4b7d2/tools/image_processing/imagej2/imagej2_crop.xml#L109-L118

Ah so the reason probably is that the channel axis of the image is not the last axis. This was assumed for the current implementation of the assertions. For the next iteration, we should make this configurable via an attribute, and default to the information from `axes` reported by tifffile. I will put it on my agenda, but I have no clue when I will find time to work on that.

**Comment by lldelisle** [comment]
OK thanks, just also to warn the community in case there are issues with this asserts.

**Comment by kostrykin** [comment]
@lldelisle Can you maybe provide small example images, one which reproduces the issue reported here, and another one for the issue in https://github.com/lldelisle/galaxytools/blob/a3a30748d533cfdd1fd393cb572b25325ab4b7d2/tools/image_processing/imagej2/imagej2_crop.xml#L109-L118, for testing?

**Comment by lldelisle** [comment]
The images are in the same repo:
This image has 2 channels https://github.com/lldelisle/galaxytools/raw/a3a30748d533cfdd1fd393cb572b25325ab4b7d2/tools/image_processing/imagej2/test-data/confocal-series-both-channels_cropped_singleZ.tiff
This image has 2 channels, 25 slices https://github.com/lldelisle/galaxytools/raw/a3a30748d533cfdd1fd393cb572b25325ab4b7d2/tools/image_processing/imagej2/test-data/confocal-series-both-channels.tiff
This image has 1 channel, 25 slices https://github.com/lldelisle/galaxytools/raw/a3a30748d533cfdd1fd393cb572b25325ab4b7d2/tools/image_processing/imagej2/test-data/confocal-series-first-channel_cropped.tiff
```python
>>> import tifffile
>>> tif = tifffile.TiffFile('/home/ldelisle/Documents/mygit/galaxytools/tools/image_processing/imagej2/test-data/confocal-series-both-channels_cropped_singleZ.tiff')
>>> tif.series[0].axes
'CYX'
>>> tif.series[0].shape
(2, 8, 16)
>>> tif = tifffile.TiffFile('/home/ldelisle/Documents/mygit/galaxytools/tools/image_processing/imagej2/test-data/confocal-series-both-channels.tiff')
>>> tif.series[0].axes
'ZCYX'
>>> tif.series[0].shape
(25, 2, 50, 50)
>>> tif = tifffile.TiffFile('/home/ldelisle/Documents/mygit/galaxytools/tools/image_processing/imagej2/test-data/confocal-series-first-channel_cropped.tiff')
>>> tif.series[0].axes
'ZYX'
>>> tif.series[0].shape
(25, 8, 16)
>>> 

```
