### ISSUE TITLE
Fetch Fasta DM on Test reports a configuration issue

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1885]
**Issue:**

Fetch fasta DMs for existing genomes on test/test-installer both fail. Appears to be a configuration or dependency issue.

Fetch fasta DM with new dbkey has not been test yet to avoid creating incorrect data, hindering promotion of good data to Main.

**Utility:** 

Needed to add in brand-new genomes and indexes.

**Related to:**

https://github.com/galaxyproject/galaxy/issues/1470

**Details:**

> Galaxy Tool ID:   toolshed.g2.bx.psu.edu/repos/devteam/data_manager_fetch_genome_all_fasta/data_manager_fetch_genome_all_fasta/0.0.1
> Galaxy Tool Version:  0.0.1

_Original error:_ (Details sent to bugs mailing list in Jan)
<img width="247" alt="screen shot 2016-03-07 at 12 03 41 pm" src="https://cloud.githubusercontent.com/assets/8999735/13581849/ccd8b51c-e45d-11e5-947a-df80fb9bf59d.png">

_Error 3/7/2016:_ (Details sent to bugs mailing list)
<img width="239" alt="screen shot 2016-03-07 at 12 18 16 pm" src="https://cloud.githubusercontent.com/assets/8999735/13582108/1b126b64-e45f-11e5-852e-64d083c2ffe3.png">

**Comment by natefoo** [comment]
This was caused by using the installer server to run DMs. For performance reasons, the installer has `new_files_path` set to a local directory. However, some DMs need this to be set to a cluster-available directory. I set up a new server (https://test-datamanager.galaxyproject.org) for running DMs going forward.

**Comment by jennaj** [comment]
Works great now, thanks!
