### ISSUE TITLE
Toolshed browse by category forget 'Category' choice when clicking on any button

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#18867]
**Describe the bug**
When I go to the tooshed and I want to browse by Category, I see the first page sorted by Name. If I click on the '2' to get the second page, I get the second page of all categories instead of the second page of my chosen category. Same if I click on 'Name' to get the tools in the decreasing alphabetical order.

**Galaxy Version and/or server at which you observed the bug**
https://toolshed.g2.bx.psu.edu/

**Browser and Operating System**
Operating System: Linux
Browser: Firefox

**To Reproduce**
1. Go to https://toolshed.g2.bx.psu.edu/
2. Click on 'Imaging' (there are 4 pages)
3. Click on 'Name'
4. Now there are 182 pages

**Comment by mvdbeek** [comment]
I don't think we're going to fix things in the old tool shed, but at this point checking out if the new tool shed has the minimum functionality we need would be super helpful.

**Comment by lldelisle** [comment]
I checked on testtoolshed to compare and you cannot sort the list on anyway right?

**Comment by lldelisle** [comment]
Should I open a new issue for my ideas/bugs for the testtoolshed?

**Comment by lldelisle** [comment]
(You're too fast)

**Comment by mvdbeek** [comment]
I assume that's something we could have, and yeah new issues would be great! I opened one for the missing sort now, but if you got more that would be amazing!
