### ISSUE TITLE
Set parameter at runtime for subworkflows

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#1887]
Currently it is not possible to set parameters from a subworkflow at runtime. 

I guess the workflows should be flatten before showing the run dialog?

xref: https://github.com/galaxyproject/galaxy/issues/1387
ping @guerler @jmchilton

**Comment by scholtalbers** [comment]
just to note: "workflow parameters" can also not be used in subworkflows

**Comment by mvdbeek** [comment]
Regular runtime parameters can now be set: https://github.com/galaxyproject/galaxy/pull/6664
workflow parameters are still missing -- we'll get to it

**Comment by jmchilton** [comment]
"Workflow parameters" are rendered and used properly with https://github.com/galaxyproject/galaxy/pull/6678 - with Selenium tests.
