### ISSUE TITLE
Shared invocation - how to get to the workflow?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#18896]
I love the new shared invocation (e.g. https://usegalaxy.org/workflows/invocations/84e15596bd4fc608?from_panel=true, thanks @mvdbeek) but I find myself wondering how to get a copy of the workflow.

I can run it, but that doesn't seem to be "import + run" like I'd expected, it's not in my workflow list (unless the sorting is off)

Export, I can export a crate/bco and then extract the .ga file from within there. That works but, it seems like it should be easier to go from a shared invocation (which I can see myself sharing in the future for the nice workflow + report views (though that's 500'ing right now with the above)), and then a user wanting to import that workflow and run it.

perhaps i've just missed a button somewhere?

**Comment by ahmedhamidawan** [comment]
Fixed in #18930
