### ISSUE TITLE
ctrl-click doesn't let you open in new tab on shared workflow invocation page

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#18897]
![image](https://github.com/user-attachments/assets/5ace57ad-1fb1-472d-b374-455b8b9b6ef4)

xref #18896, when I <kbd>ctrl-click</kbd> that link it opens the invocation again, rather than the mentioned history. In fact clicking that link forcibly opens a new tab which removes my choice.

**Comment by ahmedhamidawan** [comment]
Fixed in #18940

**Comment by hexylena** [comment]
Thanks so much @ahmedhamidawan !
