### ISSUE TITLE
Enable display of datasets on BRC related Genome Browsers

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#18901]
At this point a dataset cannot be displayed on a BRC HUB browsers (https://hgdownload.soe.ucsc.edu/hubs/BRC/). In the screenshot below I cannot display a BED dataset with dbKey `GCA_000826245.1` in the browser - the UCSC browser is not in the list accessible browsers in the middle pane:

![image](https://github.com/user-attachments/assets/fdee4832-4137-4f59-914b-1fb38274b152)

**Comment by nekrut** [comment]
This is contingent on https://github.com/galaxyproject/brc-analytics/issues/99

**Comment by natefoo** [comment]
This should be fixed on test.galaxyproject.org, trying to verify it before restarting usegalaxy.org.

**Comment by nekrut** [comment]
Make sure that BRC list and Galaxy ref lists are 1:1 @nekrut @natefoo

**Comment by natefoo** [comment]
These are now available on usegalaxy.org.
