### ISSUE TITLE
ISSUE WITH OUTPUT 

### ISSUE THREAD

**Issue by defaulter-0035** [galaxyproject/galaxy#18906]
while performing variant annotation , the output HTML STATS file do not show any stats figure in output file . Also no guideline is provided for variant annotation on any platform . Kindly help with this .
![WhatsApp Image 2024-09-28 at 19 01 39](https://github.com/user-attachments/assets/166f8cb6-3a21-40f2-aa3c-f50e58a114c5)

**Comment by bgruening** [comment]
Which tool have you used and on which server?

**Comment by defaulter-0035** [comment]
tool - Snpeff eff call variants on Galaxy

**Comment by mvdbeek** [comment]
Sorry, without knowing the server url (what you see in your browser, e.g. https://usegalaxy.org) we can't help you. A better place to ask these questions in the future would be https://help.galaxyproject.org/.
