### ISSUE TITLE
biotools_mappings.tsv includes comma and space separated values leading to incorrect bio.tools IDs.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#18903]
**Describe the bug**

E.g. this is incorrect, that's not a valid bio.tools ID, instead it's two added together with a space.
https://usegalaxy.eu/api/tools/toolshed.g2.bx.psu.edu/repos/iuc/abstracts_by_pmids/abstracts_by_pmids/0.0.2

These all come from https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tool_util/ontologies/biotools_mappings.tsv 

You can ctrl-f for ` `  and `, ` to find other values that aren't ideal.

**Expected behavior**

The parser should perhaps be updated so that when it encounters a space separated value, that it emits multiple bio.tools stanzas rather than a single one with an invalid ID. (and probably that file needs validation/linting of some sort)

**Comment by nsoranzo** [comment]
Thanks for reporting the issue!
Agreed this should be fixed on the Galaxy side, but looking at [`lib/galaxy/tool_util/ontologies/ontology_data.py`](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tool_util/ontologies/ontology_data.py) I believe that, if you care about a specific tool, the preferred long-term solution is to add the bio.tools IDs to the tool wrapper.
