### ISSUE TITLE
i got 1TB spapce, but can not use it.

### ISSUE THREAD

**Issue by jichanghe** [galaxyproject/galaxy#18929]
**Describe the bug**

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Windows, Linux, macOS
Browser: Firefox, Chrome, Chrome-based, Safari

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by davelopez** [comment]
Hi @jichanghe and welcome!

For these kinds of questions we have the Help Forum, please go to https://help.galaxyproject.org/ and search for related questions there, if you don't find the solution then create a new question there. Please be more specific in your question so we can help you, like which Galaxy server you are having issues etc.

This repository is about technical issues of the software so I will close it.

Thank you!
