### ISSUE TITLE
requirement section in local tools

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/galaxy#18934]
https://github.com/galaxyproject/galaxy/blame/3f39b62eed557a6eeed9eaf174b2c4da0577e301/tools/filters/pasteWrapper.xml#L4
@mvdbeek since this local tool has its requirements section, I noticed that each time a job is created with the tool, a new conda env is built in live, which may significantly increase the run time with large collections.

I suppose there is a Galaxy setting to avoid this and to build a permanent conda env once ?
Currently, I manually remove the section.

**Comment by bernt-matthias** [comment]
You need to install the conda environment as an admin (`Manage dependencies`) and probably you should double check the value of [conda_auto_install](https://github.com/galaxyproject/galaxy/blob/4c758038a0aedb3000623350512cee9cdb94851f/lib/galaxy/config/sample/galaxy.yml.sample#L588). 

Feel free to reopen if this does not solve you problem.

**Comment by drosofff** [comment]
Thank you @bernt-matthias `conda_auto_install` is set to default `false`, for sure.
But the playbook role `galaxyproject.miniconda` is run as become: galaxy. It must come from that.
