### ISSUE TITLE
Single cell subdomain in usegalaxy.eu

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/galaxy#18957]
Can the single-cell subdomain page now render from our new Lab page (https://labs.usegalaxy.org.au/?content_root=https://github.com/galaxyproject/galaxy_codex/blob/main/communities/spoc/lab/usegalaxy.eu.yml) please?

Additionally, could our tool panel be organised using that curated list (https://github.com/galaxyproject/galaxy_codex/tree/main/communities/spoc/lab/tool_panel)?

**Comment by natefoo** [comment]
You might want to open this on https://github.com/usegalaxy-eu/infrastructure-playbook? Unless it is for me and you mistyped .eu instead of .org :smile:

**Comment by nomadscientist** [comment]
Epic thanks Nate! I... didn't actually know that repo existed. On it!
