### ISSUE TITLE
depot.galaxyproject.org server is very slow

### ISSUE THREAD

**Issue by mashehu** [galaxyproject/galaxy#18972]
**Describe the bug**
Downloading singularity images from depot.galaxyproject.org is very slow ~20-50KiB/s.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: macOS
Browser: Firefox, Chrome, Safari

**To Reproduce**
1. run `singularity pull  --name depot.galaxyproject.org-singularity-multiqc-1.25.1--pyhdfd78af_0.img.pulling.1728550459893 https://depot.galaxyproject.org/singularity/multiqc:1.25.1--pyhdfd78af_0`

**Expected behavior**
Faster download speed

**Screenshots**

**Additional context**
Started noticing it this morning (CEST)

**Comment by bgruening** [comment]
You should not download images from there. We have a distributed system using CVMFS to get images, please use that.

**Comment by nsoranzo** [comment]
We currently use depot.galaxyproject.org in a test, which has started failing with `urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='depot.galaxyproject.org', port=443): Read timed out.`, see e.g. https://github.com/galaxyproject/galaxy/actions/runs/11273715764/job/31351337921

**Comment by mvdbeek** [comment]
@natefoo any ideas why depot has become that slow ?

**Comment by natefoo** [comment]
It's fine now as far as I can tell, but I've had sporadic issues with network performance on other PSU-hosted stuff lately, so this could be related. We're looking into it.

**Comment by mvdbeek** [comment]
It's still kind of slow at 8MB/s but I guess that's somewhat workable ?
