### ISSUE TITLE
`z` option is mishandled when adding custom `docker_volumes`

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#18989]
my job conf includes:

```
<param id="docker_volumes">$galaxy_root:ro,$tool_directory:ro,$job_directory:ro,$working_directory:z,$default_file_path:z</param>
```

there are five entries. Generated tool scripts look like:

```
-v /home/user/arbeit/galaxy/galaxy:/home/user/arbeit/galaxy/galaxy:ro \                                                                 
-v /home/user/arbeit/emc/infrastructure/files/emc-tools:/home/user/arbeit/emc/infrastructure/files/emc-tools:ro \                       
-v /home/user/arbeit/galaxy/galaxy/database/jobs_directory/000/499:/home/user/arbeit/galaxy/galaxy/database/jobs_directory/000/499:ro \ 
-v /home/user/arbeit/galaxy/galaxy/database/objects:z:rw \ 
--cpus ${GALAXY_SLOTS:-1}
```

note that there are now four `-v` instead of 5, (missing working_directory, I think. `outputs_to_working_directory` is false.

additionally, and more importantly, `:rw` has been added to the end of the mount, and the mount hasn't been reduplicated like usual. I'm guessing this is because there's some code that checks specifically for `:ro` and `:rw`, but doesn't yet consider `:z` or `:Z` (needed when running under selinux.) and assumes those are mount paths inside the container.

**Comment by hexylena** [comment]
guessing it's in lib/galaxy/tool_util/deps/container_classes.py but not sure how L295-305 really work

**Comment by bernt-matthias** [comment]
https://github.com/galaxyproject/galaxy/pull/18998

Is `dev` sufficient for you? Or should I target another branch?
