### ISSUE TITLE
parameter <from_dataset> does not allow for workflow input

### ISSUE THREAD

**Issue by paulzierep** [galaxyproject/galaxy#18990]
**Describe the bug**
The parameter <from_dataset> does not allow supplying the input in a workflow (if more than one value is given). 
If more than one parameter is provided as workflow input as a comma separated list, the tool fails with: `an invalid option was selected`

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1

**To Reproduce**
1. Get this workflow: https://usegalaxy.eu/u/paulzierep/w/ampvis2-subset-workflow-input
2. Get this history: https://usegalaxy.eu/u/paulzierep/h/fromdataset-test-case
3. Run the workflow
4. Using e.g.: ASV2913, ASV2914 as input for Taxonomy Choice 

**Expected behavior**
The workflow should work. The tool itself allows selecting multiple parameters, so should the workflow.

**Screenshots**
Tool alone works:
![Selection_186](https://github.com/user-attachments/assets/eaf377e8-2fcf-4d46-bddd-2e3b3a781871)
Workflow fails:
![Selection_185](https://github.com/user-attachments/assets/03b77459-f75b-47a8-abf4-07ee52a0fe08)

**Additional context**
Supplying only one value works.

**Comment by mvdbeek** [comment]
This will be available in 24.2 (https://github.com/galaxyproject/galaxy/pull/18715), you can test this on test.galaxyproject.org

**Comment by paulzierep** [comment]
> This will be available in 24.2 (#18715), you can test this on test.galaxyproject.org

Do you know a tool, on the test serve, that has such an input ?

**Comment by mvdbeek** [comment]
Ah, I missed the from_dataset part. This is quite the hack we shouldn't support, for starters we can't read in file contents in the Galaxy process, we only read the first MB resulting in arbitrary cutoffs for valid vs invalid selections etc.

Continuing on, those aren't available when building the run form, so take care to select valid options. I don't think this can be improved by the nature of looking at inputs that may or may not exist. Avoid this construct if you can.

**Comment by paulzierep** [comment]
> Ah, I missed the from_dataset part. This is quite the hack we should remove, for starters we can't read in file contents in the Galaxy process, we only read the first MB resulting in arbitrary cutoffs for valid vs invalid selections etc.
> 
> Continuing on, those aren't available when building the run form, so take care to select valid options. I don't think this can be improved by the nature of looking at inputs that may or may not exist. Avoid this construct if you can.

Do you mean the from_dataset should be removed ? So if I want to use a tool that has this parameter type already implemented, should I change the wrapper to e.g. allow the input values to be supplied as a comma separated list, or as a file ?

**Comment by mvdbeek** [comment]
We're not going to break old tools, I'm not sure what a good replacement is. comma-separated values are problems if commas can be part of your values.

**Comment by paulzierep** [comment]
> We're not going to break old tools, I'm not sure what a good replacement is. comma-separated values are problematic if commas can be part of your values.

For our use case, I think to supply the values as a file where each line is a value would be ideal. I can fix that on the wrapper side - no problem. I just wanted to check whether this could be resolved by fixing from_dataset input.

**Comment by mvdbeek** [comment]
I'll check if there's anything obviously wrong with selecting multiple values, but if you want a file anyway that would probably be an improvemen for the wrapper.
