### ISSUE TITLE
clicking "expand to full workflow form" resets inputs

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#19007]
It would be nice if the choices you've already made have been preserved after expanding to the full form.

seen on McOS Main Galaxy version 24.1.3.dev0, commit [b56ad8d12a77da51dc9129e4c80705dd46c19839](https://github.com/galaxyproject/galaxy/commit/b56ad8d12a77da51dc9129e4c80705dd46c19839)

**Comment by nsoranzo** [comment]
Duplicate of https://github.com/galaxyproject/galaxy/issues/11136 ?
