### ISSUE TITLE
History not updated/ui synced

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#19026]
**Describe the bug**

I will occasionally start a job and the history will not update to show the outputs. Additionally when I refresh, the history will occasionally not. Today after updating I've been hitting the refresh key far more often than usual.

**Galaxy Version and/or server at which you observed the bug**

Galaxy Version:  24.1.3.dev0 
Commit: 1a6b7fefd373a7a8f8233c08be6bbe30961b6508

**Browser and Operating System**
Operating System: Linux
Browser: Chrome Version 130.0.6723.58 (Official Build) (64-bit)

**To Reproduce**
1. Run a job (maybe in a large history?)
2. Expand the queued job
3. Click on details
4. Watch the Job Outputs section update and turn green
5. Hover over the history update icon to see it was last refreshed 1 second ago
6. Click the history update button to see it's updated 0 seconds ago, nothing changes, dataset still grey. (Why doesn't this forcibly refresh the history? Rather than just doing the update process that's already happening in the background.)
7. Check network tab to see what's going on. See endlessly requests like `/history/current_history_json?since=2024-10-18T11:28:53.259435` that return `null`

**Expected behavior**

That when I click refresh history it actually refreshes it.

**Screenshots**

![sync2](https://github.com/user-attachments/assets/3053a3c0-0b7a-4e2b-8c69-fa36a059dbcd)

**Additional context**

I cannot reproduce this on EU, and I cannot provide access to the server where it happens, but i can run any queries y'all need or apply patches.

**Comment by mvdbeek** [comment]
Check that the database uses UTC time?

**Comment by natefoo** [comment]
Possibly #17954? Although in my case the history item text updates, but not the styles.

**Comment by hexylena** [comment]
Good thought @mvdbeek.

```
galaxy=# show timezone;
 TimeZone 
----------
 Etc/UTC
(1 row)
```

**Comment by hexylena** [comment]
```
# chronyc -n tracking
Reference ID    : B950F724 (185.80.247.36)
Stratum         : 2
Ref time (UTC)  : Tue Oct 22 09:44:29 2024
System time     : 929.234680176 seconds slow of NTP time
```

I'm gonna go ahead and guess that might have something to do with it :(

**Comment by shenweiyan** [comment]
@hexylena @mvdbeek I encountered the same issue in the local Galaxy instance 24.0.4.dev0. I found that PRC time is used in my Galaxy database, while my server uses CST time. Do I need to change the database time to UTC? If so, how should I specifically operate to do that? Thanks.
```bash
galaxy=> show timezone;
 TimeZone
----------
 PRC
(1 row)
```

```
$ chronyc -n tracking
Reference ID    : 6FE6BDAE (111.230.189.174)
Stratum         : 3
Ref time (UTC)  : Tue Mar 18 07:23:25 2025
System time     : 0.000582530 seconds slow of NTP time
```
