### ISSUE TITLE
NCBI SRA Tools have dependency issue at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#1903]
**Tools**
<img width="232" alt="screen shot 2016-03-10 at 10 01 43 am" src="https://cloud.githubusercontent.com/assets/8999735/13679151/3010f5cc-e6a7-11e5-8139-518af5c6f122.png">

**Example error**

> job stderr:
> Fatal error: Exit code 127 (Could not locate fastq-dump binary)
> /galaxy-repl/main/jobdir/012/086/12086366/tool_script.sh: line 9: vdb-config: command not found
> /galaxy-repl/main/jobdir/012/086/12086366/tool_script.sh: line 9: prefetch: command not found

**Status**
@davebx correcting, In progress

**Comment by davebx** [comment]
This should now be corrected.

**Comment by jennaj** [comment]
Thanks @davebx 

My test on all three tools is running. If a problem comes up, will write back, otherwise consider fully closed as impacts main.

**Comment by jennaj** [comment]
The pileup tool fails on the example data using default options.

> Input Parameter   Value   Note for rerun
> select input type accession_number  
> SRR accession SRR1554537  
> adv  
> aligned region  
> minimum mapping quality   None

Should the tool have more comments about this type of issue? e.g. options for when imported datasets are too large to import on main (use local or cloud with more resources?)

> Job output file grew too large (greater than 150.0 GB), please try different inputs or parameters

**Comment by mvdbeek** [comment]
@jennaj
If you do not enter the aligned region, it fetches the whole file (which is very big in this example).
The last item in the [this history](https://usegalaxy.org/u/marius/h/new-history-ex1) is a run using the parameters from the test-section.

**Comment by mvdbeek** [comment]
we could add a sentence though saying that `if you leave this field empty, the whole file will be downloaded` ?

**Comment by jennaj** [comment]
That sounds like a good option to me. To avoid multiple support questions when the tool fails, could we extend it a bit to state that a tool failure can result when the data is large? In a nice way, something like:

`If you leave this field empty, the whole file will be downloaded. Very large data imports may fail.`

**Comment by jennaj** [comment]
@galaxyproject/guac The tools are problematic at http://usegalaxy.org again. Tool needs to be updated to the most recent in tool shed https://toolshed.g2.bx.psu.edu/view/iuc/sra_tools/26b7446bb17e (2016-12-07 update, v 2.8.0)

Galaxy Tool ID:	toolshed.g2.bx.psu.edu/repos/iuc/sra_tools/fastq_dump/2.7.0.1

Option to extract fastq directly produces this error

> Fatal error: Exit code 3 ()
> 2016-12-09T21:47:50 prefetch.2.7 err: error unexpected while resolving tree within virtual file system module - failed to resolve accession 'SRR1290669' - Obsolete software. See https://github.com/ncbi/sra-tools/wiki ( 406 )
> 2016-12-09T21:47:50 prefetch.2.7 err: path not found while resolving tree within virtual file system module - 'SRR1290669' cannot be found.

Option to extract fastq from .sra archive uploaded into the history produces this error (same accession)

> Fatal error: Exit code 3 ()
>
> An error occurred during processing.
> A report was generated into the file '/galaxy-repl/main/jobdir/XXX/XXX/XXX/working/ncbi_error_report.xml'.
> If the problem persists, you may consider sending the file
> to 'sra@ncbi.nlm.nih.gov' for assistance.
>

**Comment by mvdbeek** [comment]
@natefoo @jennaj 
You'll have to upgrade to 2.8.0, it's already on the toolshed, this is due to NCBI's switch to https.
I'd recommend uninstallling the old versions, since they're guaranteed to fail now.

**Comment by natefoo** [comment]
Thanks @mvdbeek. @martenson can you do the upgrade and uninstalls?

**Comment by jennaj** [comment]
@martenson Just checked and not updated yet on Main. When done, please ping me and I'll test.

**Comment by natefoo** [comment]
I have updated the SRA tools on Main and uninstalled all old versions.

**Comment by jennaj** [comment]
@natefoo all of the tools, all options, now work. Super! Thanks!
