### ISSUE TITLE
Make galaxy installation clean

### ISSUE THREAD

**Issue by AbhishekKumarSingh** [galaxyproject/galaxy#1906]
Hi,

I clone the galaxy repo. After running `sh run.sh` I get the import error as:
`ImportError: No module named urllib3`

I tried installing urllib3 in the virtualenv (.venv) created during the installation process by running:
`.venv/bin/easy_install urllib3` which installed urllib3 in the virtualenv lib

when I continue with `run.sh` it now throws error as:
`from operator import _compare_digest as compare_digest
ImportError: cannot import name _compare_digest
`
traceback: https://dpaste.de/Si2A

I checked the python version installed in `venv` and found that installed version is 2.7.6 which doesn't support `from operator import _compare_digest as compare_digest` statement. 

`.venv/bin/python -c "import sys; print sys.version_info"`
output : sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)
Version needs to be 2.7.7 or higher. ref: http://stackoverflow.com/questions/26535043/python-flask-error-importerror-cannot-import-name-compare-digest

I guess version for python should be updated and also urllib3 should be added as dependency.

**Comment by mvdbeek** [comment]
Hi @AbhishekKumarSingh ,
this looks more like an issue with your python installation.
We're using python 2.7.6 on our production instances and things are work fine.
[Here's](https://gist.github.com/mvdbeek/d69a3176b143850763f5) the log from a fresh clone.

**Comment by AbhishekKumarSingh** [comment]
I see. I had python 2.7.11 installed on my system.
Created virtualenv (uses python 2.7.6 as default) and then ran the installation for galaxy. It worked!

I still wonder since run.sh initially creates .venv (which by default uses python 2.7.6) and uses it then tries the next step of installation. So why does it fails? isn't it doing things(installation requirements) inside virtualenv .venv?

**Comment by hexylena** [comment]
Seems to be a site-specific issue, sorry you experienced it. Hopefully working more reliably now
