### ISSUE TITLE
Allow tools accept URIs for deferred datasets.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#19065]
Some tools would not need to have datasets materialized to work properly - see #19040 and related PRs. My first thought is we could just have https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/wrappers.py provide some sort of syntax ``dataset.path_or_uri()`` | ``dataset.path_or_uri(uri_if_prefix=["http","s3"])`` but then I realized the syntax would only be knowable at evaluation time and we should probably have a more declarative way of handling this so the job evaluation code could deduce we don't need to materialize the dataset more concretely so the syntax should maybe be on the ``param`` tag.  Something like ``<param type="data" allow_uri_if_prefixed="*" />``, ``<param type="data" allow_uri_if_prefixed="http|s3" />``.

**Comment by davelopez** [comment]
Thank you @jmchilton! I'll try to work on this.
