### ISSUE TITLE
A collection element, that cannot be extracted

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#19072]
- I uploaded a fasta sequence for a genome using NCBI Datasets tool into this history: https://test.galaxyproject.org/u/anton/h/unnamed-history-7
- The FASTA file is downloaded as a collection:

![image](https://github.com/user-attachments/assets/500c03f2-8636-4413-a0ad-965177bcedd4)

- If I try to extract this element using https://test.galaxyproject.org/root?tool_id=__EXTRACT_DATASET__  I get another collection, which is weird:

![image](https://github.com/user-attachments/assets/c80d5e7d-3e30-49a8-a1c7-669f4881d4ee)

- If I run https://test.galaxyproject.org/root?tool_id=__EXTRACT_DATASET__ on that collection **again** I do finally get a single fasyta dataset I wanted from the start:

![image](https://github.com/user-attachments/assets/e73b6e75-dcdb-4692-aae7-1a94b8ff43d2)

There seems to be bug that makes this collection to look like a nested collection. This only happened with fasta datasets downloaded using NCBI Datasets tool

**Comment by mvdbeek** [comment]
The first item is a list of lists that represents the chosen accession in the outer list (could be a taxon for instance) and the inner list contains the genomes found for that accession:
```xml
        <collection name="genome_fasta" label="NCBI Genome Datasets: genome fasta" type="list:list">
            <discover_datasets pattern="(?P&lt;identifier_0&gt;.*?)/(?!rna|cds_from)(?P&lt;identifier_1&gt;.*?)(_genomic)?\.(?P&lt;ext&gt;fasta(\.gz)?)" directory="ncbi_dataset/data" recurse="true" match_relative_path="true"/>
            <filter>
                file_choices['include'] and "genome" in file_choices['include']
            </filter>
        </collection>
```
I don't think there is a bug, the tool was explicitly written to support this.

**Comment by mvdbeek** [comment]
We discussed this out of band, it isn't really a bug but how the tool works, which might need another mode for just getting a single species output.
