### ISSUE TITLE
Upload does not keep pasted data when switching tabs

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#19081]
Imagine you specified local files you want to upload while your upload is set to "regular":

![image](https://github.com/user-attachments/assets/4623f8cb-ae37-4af9-8268-4a27db76bd51)

then you realize that you actually want to use "collection" tab:

![image](https://github.com/user-attachments/assets/182093a3-efcb-48bf-872d-f8a52b7432c1)

when you switch between tabs anything you entered in the modal gets lost:

[Screencast from 10-30-2024 11:44:37 AM.webm](https://github.com/user-attachments/assets/79284184-a179-49a8-8464-a64ab4dde3b8)

## How should it behave?

The data (either local files or pasted URLs) should not get lost when switching bwteeen tabs.

**Comment by ahmedhamidawan** [comment]
Fixed in #19083

**Comment by ahmedhamidawan** [comment]
Fixed in #19083
