### ISSUE TITLE
remote files modal persists search string between contexts

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#19119]
When searching at the top level of file sources you are not looking for the data, but for the name of the service. This works correctly I think.

<img width="689" alt="Screenshot 2024-11-08 at 12 39 20 PM" src="https://github.com/user-attachments/assets/efab5714-3f8e-46e5-b7d6-c94771827276">

However when you enter the file source and you are searching for an entry, the form persisted your search, so now you are searching for e.g. "zenodo" repository in "zenodo" file source. I believe it should clear the search instead.

<img width="676" alt="Screenshot 2024-11-08 at 12 39 27 PM" src="https://github.com/user-attachments/assets/b1642630-62c1-4d4d-b4d8-72968c121f70">

This applies to other sources in the modal as well, not just zenodo.

macos chrome on usegalaxy.eu 

{
  "version_major": "24.1",
  "version_minor": "2.dev0"
}

**Comment by kysrpex** [comment]
I also stumbled upon this issue, it definitely makes sense to clear the search box instead.

**Comment by sanjaysrikakulam** [comment]
@itisAliRH is already working on this issue the last I checked. Its tracked [here](https://github.com/galaxyproject/galaxy/issues/18596)

**Comment by martenson** [comment]
@sanjaysrikakulam looks right, closing as a duplicate
