### ISSUE TITLE
Error 400 when trying to open a subworkflow

### ISSUE THREAD

**Issue by Delphine-L** [galaxyproject/galaxy#19133]
**Describe the bug**
Hi! I get this error 400 sometimes when I try to open a subworkflow on main. Most of the times, if I reload the parent workflow is works, sometimes it takes several tries to work.  Doesn't happen with one workflow in particular so it's hard to reproduce. 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: main 24.1.3.dev0

**Browser and Operating System**
Operating System: macOS
Browser: Chrome

**Screenshots**
<img width="1436" alt="Screenshot 2024-11-12 at 10 51 12 AM" src="https://github.com/user-attachments/assets/520af080-fdd2-48b9-9d1a-be7d117ef43c">

**Comment by mvdbeek** [comment]
Were you doing something in particular, like maybe impersonating a user in another tab or logging in and out of accounts ?

**Comment by mvdbeek** [comment]
If you do see it again feel free to re-open. You can check out the response in the network tab, that might help us.
