### ISSUE TITLE
Cannot share history (datasets) with individual user

### ISSUE THREAD

**Issue by lldelisle** [galaxyproject/galaxy#19145]
**Describe the bug**
If I try to share a history with another user I get a new screen asking if I want to put public the datasets and if I select only to me and the people I shared with I get:
" Input should be 'make_public', 'make_accessible_to_shared' or 'no_changes' in ('body', 'share_option') "

**Galaxy Version and/or server at which you observed the bug**
usegalaxy.eu
{"version_major":"24.1","version_minor":"2.dev0"}

**Browser and Operating System**
Operating System: Linux / macOS
Browser: Firefox

**To Reproduce**
I am a bit lazy to write it down but if you need I will.

![image](https://github.com/user-attachments/assets/1e42bb67-c693-43c0-955b-200b1eda613a)

**Comment by davelopez** [comment]
Hi @lldelisle, can you still reproduce this? I tried on 24.1 and it seems to work.

I assume this was likely fixed in https://github.com/galaxyproject/galaxy/pull/18939 so I will close it, but please reopen if it still doesn't work for you.

**Comment by lldelisle** [comment]
I could still reproduce on usegalaxy.eu, now:
[Screencast_20241118_131148.webm](https://github.com/user-attachments/assets/8dbe36fd-731b-48b5-bbfa-0e6fe379ffc0)

**Comment by davelopez** [comment]
Ahh that might be usegalaxy.eu is not up to date with the latest 24.1 fixes.

**Comment by mvdbeek** [comment]
Yep: https://github.com/usegalaxy-eu/galaxy/compare/release_24.1_europe...galaxyproject:galaxy:release_24.1

**Comment by bgruening** [comment]
update in process

**Comment by lldelisle** [comment]
It works, thank you.
