### ISSUE TITLE
"name:DRR..67" is not a valid tag.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#19148]
Is there a technical reason why can't I have two `..`s in a row? If not, I would like to have that restriction removed please :) Especially if `#!@#` is a valid tag I can't think of a reason why `..` would be banned.

**Comment by jdavcs** [comment]
The dot is a tag hierarchical separator, so allowing `..` would create ambiguity for parsing the tag. @dannon you mentioned relaxing the regex; but I'm also wondering about what would happen on the backend, specifically here https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/model/tags.py#L308

**Comment by dannon** [comment]
@jdavcs Sorry if I wasn't clear on the call -- in the example "name:DRR..67" the 'tag' is 'name'.  The 'value' is DRR..67, which does not need to be constrained.
