### ISSUE TITLE
Invocation control looks odd

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#19158]
<img width="2591" alt="Screenshot 2024-11-18 at 17 38 50" src="https://github.com/user-attachments/assets/83f254bd-a7ce-4055-bec7-60a09b346c6d">

The empty area left and right of the progress component looks weird, and the `Waiting to complete invocation` seems kind of unnecessary if we have the progress bar anyway. The blue background there also seems odd. Finally the Generate PDF button ... is redundant with the one in reports ?

**Comment by ahmedhamidawan** [comment]
Would you rather the progress bars be even narrower in width, or be wider all the way to either end?
