### ISSUE TITLE
Workflow annotation in run form could look better

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#19157]
There's enough screen width to show the entire text, so the caret-down looks weird here. It also looks like an input section, maybe there's some visual distinction to make it clear this is workflow metadata ? And what is the point of the `Input History` thing ? I thought at first it's a target history selector, but that's still in the cog wheel ? The history name looks like it's clickable, but doesn't do anything ?

<img width="2679" alt="Screenshot 2024-11-18 at 17 25 34" src="https://github.com/user-attachments/assets/e8223e59-ee6c-4e06-8e86-7ddc29a8f2be">

**Comment by hujambo-dunia** [comment]
The screen resolutions width in the example image above is non-standard. If we're going to limit the type of web browsers Galaxy supports, we should also limit the type of screen resolutions supported.

**Comment by mvdbeek** [comment]
It's standard 4K, 3840 × 2160. Noone has said anything about limiting browser support, and in fact this looks suboptimal on any screen, it's just more obvious when you have more screen estate.
