### ISSUE TITLE
Documentation for Tool Parameters 

### ISSUE THREAD

**Issue by i-am-b-soto** [galaxyproject/galaxy#1917]
Greetings Galaxy Developers. 
So I have a task of uploading a file with the upload tool using Galaxy's API, into a given history on Galaxy. 
I'm looking at the 'create' function in tools.py and I cannot assess what arguments/parameters must be contained in the 'payload' variable in order to run the upload tool, and in what format these parameters must be in. 

I am able to get some tools (specifically the 'gat data' tool) to run on per-existing datasets using the format  "input:{id: <dataset_id>, src: 'hda'}"  and inputting it as an argument to the payload, however I do not know the proper procedure for inputting a specific file and uploading it to Galaxy. 

I have read bioblend and the existing documentation on the Galaxy API and I cannot find a proper solution. If you could inform me the correct steps to take here that would be terrific! thank you!

**Comment by mvdbeek** [comment]
Hi @ Iamsoto,
You can take a look at the help/source for bioblend [here](https://bioblend.readthedocs.org/en/latest/api_docs/galaxy/all.html?highlight=upload%20file#bioblend.galaxy.tools.ToolClient.upload_file)

**Comment by dannon** [comment]
@Iamsoto Were you able to figure this out?  In the event that the bioblend upload reference posted by @mvdbeek wasn't enough, feel free to reply and I can reopen this issue and try to help.
