### ISSUE TITLE
Tool Shed Installs and Conda

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1919]
If tool's don't define a tool_dependencies.xml file during install - attempt a conda install.

This is a relatively high priority because @bgruening has wonderfully made it a best practice to setup the conda dependencies for testing but Galaxy still won't use these dependencies by default - so we encouraging people to create dependencies twice for Galaxy.

**Comment by bgruening** [comment]
@jmchilton it would be wonderful if we could make this configurable. There are benefits in installing tools at runtime. For example to keep a Docker container small. But yes, this would be a great enhancement. Also the TS interface should not display the `missing dependency` warning if there is a conda package available.

**Comment by nsoranzo** [comment]
When you implement this, please keep in mind system administrators which use manually created `env.sh` files e.g. to load cluster modules.

**Comment by jmchilton** [comment]
@nsoranzo - very good point - this should be a checkbox - or there should be an option to enable a checkbox. We should even do a better job and list requirements and what is resolving them, etc....

**Comment by jmchilton** [comment]
I believe this has been done - I'm not claiming it is perfect but newer comments about the UX related to Conda should be associated with a newer, more precise issue.
