### ISSUE TITLE
Jupyter IE rarely starts up

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#1920]
In the majority of cases previously saved IE do not startup. Essentially un-usage. E.g., see  https://usegalaxy.org/u/aun1/h/pnas-2014 history

**Comment by hexylena** [comment]
xref https://github.com/bgruening/docker-jupyter-notebook/pull/6

**Comment by hexylena** [comment]
cc @bgruening

**Comment by bgruening** [comment]
@nekrut what changed in the last month? @erasche is trying to backport a workaround form IPython, but I'm a little bit sceptical that this will fix it. It used to work isn't it? Is your history large from which you try to lunch the notebook?

**Comment by hexylena** [comment]
@bgruening It's not large, there are cases of histories with ~30 datasets that will cause load failure. I'm pretty sure this is a big part of it (main's API is probably slower than yours and mine)

**Comment by natefoo** [comment]
I'll need to pull the new image once it's built.

**Comment by hexylena** [comment]
This should be fixed, yes?

**Comment by bgruening** [comment]
Yeah, during the workshop it worked for 20 people simultaneously.
Great work @natefoo!

**Comment by natefoo** [comment]
Yeah, this was a problem with the way I had the proxy configured across our two front end VMs. All good as far as I am aware.
