### ISSUE TITLE
Harmonize two collections tool generates wrong metadata for second collection output

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#19221]
**Describe the bug**

The current version of the tool creates two output collections with identical names and collection types in the history, but correct content in the history.

**To Reproduce**
1. Run *Harmonize two collections* on a simple list as its first and a list of (fastq) pairs as its second input
2. Observe that name and type of the second output collection are identical to those of the first one even though the type should be list of pairs
3. Try to run bwa-mem on the second output collection and it will fail to find .forward/.reverse attributes of inputs

**Comment by dannon** [comment]
Fixed in #19222
