### ISSUE TITLE
File upload of html does not work (as asked by GTN tutorial)

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#19220]
**Describe the bug**

The GTN tutorial on metagenome assembly asks to upload html: 

https://training.galaxyproject.org/training-material/topics/microbiome/tutorials/metagenomics-assembly/tutorial.html#hands-on-import-generated-metaquast-results

This does not work: upload jobs fail. Datasets say:  `The uploaded file contains invalid HTML content`

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1 (and probably 24.2) .. tested today on org and eu

**To Reproduce**

1. Paste links to upload

**Comment by mvdbeek** [comment]
As it shouldn't. That seems like a mistake in the tutorial ?

**Comment by bernt-matthias** [comment]
Thanks for the feedback. I [reported at GTN](https://github.com/galaxyproject/training-material/issues/5569) and close this one.
