### ISSUE TITLE
IE Provevance

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#1923]
To truly take advantage of IEs such as Jupyter `get` and `put` functions need to be modified so that input and output datasets are trackable in history. This would also allow inclusion of IEs in workflows. An enormous advantage here is that you can quickly write, say, a statistical test function in Jupyter and then use it as a tool. (e.g., see [this](http://googleresearch.blogspot.com/2014/08/doing-data-science-with-colaboratory.html)).

**Comment by hexylena** [comment]
Closing in favour of the bullet point in the existing GIE roadmap.

**Comment by dannon** [comment]
@erasche The bullet on the IE roadmap is linked here.  Should this not remain open as a way to discuss and plan for this particular issue, similar to how other roadmap issues are linked?

**Comment by hexylena** [comment]
@dannon that would possibly be reasonable. How much discussion is warranted on this feature?

There aren't many way to implement, we have evidence that people who are writing notebooks are capable of using the linked google research syntax, and we'll turn that into a tool somehow.

**Comment by martenson** [comment]
ITs can be used in workflows now, I think this issues has been resolved.
