### ISSUE TITLE
Galaxy application profiling and timing statistics

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#1924]
This issue lists additional things we want to time and ship using the statsd middleware.
- [ ] Add decorator to easily time key 

(potentially) useful numbers:
- Time to run tools (execute through appear in history)
- Time to start for queued jobs
- Time to schedule workflow

**Comment by hexylena** [comment]
GIEs
- [ ] GIE startup time (time to first successful connection)
- [ ] GIE launch count per type
- [ ] GIE session duration?

**Comment by natefoo** [comment]
Assigning myself as I'm working on the server.

**Comment by dannon** [comment]
The infrastructure is complete and live at stats.galaxyproject.org.   Stats role in playbook at https://github.com/galaxyproject/infrastructure-playbook/pull/8

**Comment by natefoo** [comment]
#2342 is running on Test, how are things looking?

**Comment by dannon** [comment]
It's all working.  I need to clean out all the existing measurements and build a few dashboards, but it's fully functional with the correct key formatting (for incoming measurements) now.

**Comment by natefoo** [comment]
I can haz account?

**Comment by dannon** [comment]
We've made a few iterations on this since it was first discussed and stats.galaxyproject.org is live and well.
