### ISSUE TITLE
Workflow: Navigation back to Galaxy after a save

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#19269]
**Describe the bug**
After saving a workflow, getting "back to Galaxy" is a bit confusing.

Yes, there is the save and exit in the very bottom left corner of the new activity bar, but I missing the Home icon in the Masthead! 

**Galaxy Version and/or server at which you observed the bug**
This Galaxy server version is 25.0.dev0, and the web client was built on Wednesday Dec 4th 10:32:30 2024 GMT-8 .

**Browser and Operating System**
Operating System: Windows, Linux, **macOS**
Browser: Firefox, Chrome, Chrome-based, **Safari**

**To Reproduce**
1. Edit a workflow
2. Save it
3. Confused!
4. Find the tiny grey icon at the bottom left of the new activity bar. I already saved, but it does say "exit". 

**Expected behavior**
I was looking for the old Home (house) icon, since I always explicitly save, do another quick visual check of what I did eg workflow name and such, _then exit_. Maybe that is legacy behavior due to the Changes listing being available. I know this was discussed a lot in https://github.com/galaxyproject/galaxy/issues/18166 and other places -- but I am just not used to not having the Home icon function super obvious. 

Ideas:

1. Add that back to the masthead, far left next to the Galaxy icon or maybe better, far to the right, before the window manager (scratchbook).
2. If the workflow is already saved -- maybe the icon in activity bar is changed to be the Home icon instead of the disc icon and text states Tools and Current History. 
3. Having both in the activity bar is also a possible. Grey out the Home icon if the workflow is not saved?
4. Move Notifications down to the bottom, since that is the least interesting item in the activity bar.
5. Place Save and Exit higher up in the activity bar. I could see it at the bottom under Download but down justified to "float" right above that first bar, where the others are top justified. I do think keeping it separate is a good idea to prevent accidental clicks.
6. Maybe this Save and Exit icon is made more obvious? An "active" orange color? Bolder lines?

**Screenshots**
![how-do-I-get-back-to-Galaxy](https://github.com/user-attachments/assets/a8badc53-8330-4f51-a5cb-aaf8fe1c1a0a)

**Additional context**

**Comment by jmchilton** [comment]
You can click the Galaxy icon at the top left of the masthead - it serves the same purpose as the old home button. I imagine we decided it was redundant two have to ways to get back to the main landing page - but maybe an UI person can chime in.

**Comment by jennaj** [comment]
Thanks John -- I think you are right that I think about it more. I need to retrain myself! I'm going to close this out.
