### ISSUE TITLE
Deleting an imported workflow (from Dockstore) prevents external workflow execution

### ISSUE THREAD

**Issue by ahmedhamidawan** [galaxyproject/galaxy#19263]
If you use an external site (like https://iwc.galaxyproject.org/ or BRC analytics) to land on the workflow run form in a Galaxy server, that workflow gets added to your workflow list:
![image](https://github.com/user-attachments/assets/db5ad865-a843-4ca4-9549-3512ef20d6fc)

If you delete this workflow, the next time you use that same external site to then land on the same workflow run form in Galaxy, you won't be able to run it (since Galaxy wouldn't have reimported that workflow, and will try to reuse the existing, albeit deleted one):
![image](https://github.com/user-attachments/assets/646c02aa-8358-4b8c-96f1-70d0249cd879)

@dannon 's ideas:
> If a user has deleted the imported one we should either undelete it on import and use the references correctly from there, or use a 'clean' separate import without any linkage to the old deleted one.

**Comment by mvdbeek** [comment]
Not a UI thing, I just need to add the filter for when we check if we already have that workflow.

**Comment by dannon** [comment]
Yep, filtering deleted out correctly would result in the last option up there, the clean separate import right?
