### ISSUE TITLE
Workflow: Problems with inserting another workflow as a sub-workflow on the editor canvas

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#19265]
**Describe the bug**
Testing for https://github.com/galaxyproject/galaxy/pull/19212

The listing of an account's workflows is not updated after an import until the user goes back several steps to "refresh" their listing. This means a user can't add other workflows as a sub-workflow until they are imported. I think that step should instead redirect to a pop-up "Please confirm. Do you want to import this workflow to add it as a subworkflow on the current canvas?". So, do this all in one step, right now it takes several clicks that are not very clear. 

I think these are really great functions, just need a bit of usage tuning! 

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Windows, Linux, **macOS**
Browser: Firefox, Chrome, Chrome-based, **Safari**

**To Reproduce**
This Galaxy server version is 25.0.dev0, and the web client was built on Wednesday Dec 4th 10:32:30 2024 GMT-8 .

Log into account. 
Click on Workflow in activity bar. 
Load up a workflow in the editor. 
Click on workflow in the side activity bar.
Use the default "introduction" tag to filter the listing

Enter the loop

1. Buttons for "Insert as sub-workflow" appear to be active no matter the import state of that workflow. Choose one from the published listing to work with for the next steps.
2. Clicking on **Insert** results in a canvas element displays a warning "user does not own specified item" 
3. Clicking on **Copy** results in "Please confirm. Warning this will add 39 new steps into your current workflow. You may want to consider using a subworkflow instead.". This works great! 
4. Clicking on **Import** (Import this workflow to edit) results in a success dialogue but _the listing of workflows is not updated_. 
5. Clicking on the **Insert** button again on the workflow that is listed loops back around and another items is added to the canvas with "user does not own specified item". I know why but the imported workflow didn't update in my list, so where to click is not clear.
6. Clicking on the activity bar "workflows" **twice** to get the updated listing (first time goes to full canvas, then the second time brings back the list) then the imported workflow is available, along with an Insert button that actually adds the sub-workflow.

Other odd behavior:

Can't save the workflow while any items with the "user does not own" are on the canvas. This makes it hard to know how to back out. Hopefully the user "knows" to click on workflow twice, or how to navigate the undo.

**Expected behavior**
Action that are not available are greyed out. The hover over tool tip has a suggestion of what to do next. 

**Related behavior**
1. On that list of prior actions for undo/redo -- any that didn't work and are unresolved (preventing a "save") should be highlighted in red. The same as the canvas item is in red. https://github.com/galaxyproject/galaxy/issues/19266
2. After saving, I was confused about how to get back to Galaxy! Yes, lower bottom left but I miss the Home icon at the top. https://github.com/galaxyproject/galaxy/issues/19269

**Screenshots**

**Comment by jennaj** [comment]
I'm seeing a change in the behavior of the "insert" button now but I don't see a PR. 

[Release Notes ](https://docs.galaxyproject.org/en/latest/releases/index.html)
This Galaxy server version is 25.0.dev0, and the web client was built on Wednesday Dec 4th 10:32:30 2024 GMT-8 .

Only in MAC/Safari , Chrome and Firefox are Ok. 
1. Clicking on "insert" make the button scrunch up. This is true even if the window is expanded to be "wide" when I click. 
2. Opening that panel really wide then going narrow again resize correctly.
3. Clicking on "copy" also resets to the right size.
4. I see that removing these excess published workflow is planned for 24.2. Maybe this is minor since these won't be listed at all soon. 

![Screen Shot 2024-12-19 at 1 26 47 PM](https://github.com/user-attachments/assets/5ef86d72-8cf7-4c1b-9123-e729f9552331)

**Comment by mvdbeek** [comment]
Yes, can't insert published workflows like that. I'll open a new issue with that screenshot.
