### ISSUE TITLE
Sharing role title does not include "USER PURGED" string instead of purged user's email

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#19267]
A sharing role title includes the email of each user it is shared with. Once a user is purged, that email should be replaced with `USER PURGED`. It is not; instead it is replaced with the hash that replaced the user's email on purge. 

![image](https://github.com/user-attachments/assets/3b8e477f-c9ab-43a0-86ae-5a379bb5ea69)

Introduced: #19096

EDIT: must also look into unit test that was supposed to cover this.

**Comment by martenson** [comment]
I thought that's covered here
https://github.com/galaxyproject/galaxy/blob/6fa4fbba8879af79546a01c77c3fcf62396cfceb/test/unit/data/model/db/test_user.py#L129

**Comment by jdavcs** [comment]
> I thought that's covered here
> 
> https://github.com/galaxyproject/galaxy/blob/6fa4fbba8879af79546a01c77c3fcf62396cfceb/test/unit/data/model/db/test_user.py#L129

I thought so too! Apparently not.

**Comment by jdavcs** [comment]
It is not a sharing role title: it is just a private role of a purged user, so it's displayed as expected. These hashes are displayed everywhere where a purged user's private role was associated with an item. It's not ideal, we probably should replace these long strings with a helpful placeholder on the UI ("purged user"?), but it's not a bug.
