### ISSUE TITLE
UI drop-down menu odd

### ISSUE THREAD

**Issue by nomadscientist** [galaxyproject/galaxy#19278]
**Describe the bug**
UI drop-down menu can lose datasets if the drop-down has too many things in it.

**To Reproduce**
1. Go to usegalaxy.eu or usegalaxy.org.au
2. Try to run any tool with a drop-down menu where you have a lot of options in your history
3. See error
![Screenshot 2024-12-06 at 12 54 25](https://github.com/user-attachments/assets/cedc0b86-d59b-4193-bdd0-58caa0c1c74c)

**Expected behavior**
The scroll bar can sometimes get lost if it is too high / too low

**Additional context**
Reported by new user at Galaxy SPOC Co-Fest, and verified by two others.

**Comment by mvdbeek** [comment]
This might be due to the sticky class of the tool form header. higher z-index on the select might work ?

**Comment by davelopez** [comment]
It should be fixed in https://github.com/galaxyproject/galaxy/pull/19309, thank you!
