### ISSUE TITLE
Workflow: Add option for Create New Workflow to the workflow-specific activity bar

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#19274]
**Describe the bug**
I'm finding that I want to create a workflow while in the new view with the workflow-specific activity bar present.

This might be for a later release. 

**Galaxy Version and/or server at which you observed the bug**
This Galaxy server version is 25.0.dev0, and the web client was built on Wednesday Dec 4th 10:32:30 2024 GMT-8 .

**Browser and Operating System**
Operating System: Windows, Linux, **macOS**
Browser: Firefox, **Chrome**, Chrome-based, Safari

**To Reproduce**
1. Go to Workflows
2. Edit a workflow, decide you want to create a new one
3. Search the activity bar, and decide to exit and save then start over _at the other listing_ to do this.
4. Why not be able to create one from this view?

**Expected behavior**
Smother transition between workflow editing sessions. I can switch to another existing workflow to edit it from the activity bar and I can copy a workflow into a new workflow _but I cannot start over with a new workflow with a blank canvas_. Those seem like similar operations to me. Maybe I want to quickly make my sub-workflow, see that show up in the list, then switch back and add it. 

Leaving the view feels odd, just for that single function. I guess importing could be accessible too. Thoughts?

**Screenshots**
I could see a + sign at the top of the listing, and an item in the activity bar.
![usual-create-workflow](https://github.com/user-attachments/assets/6d5b5aec-0692-4470-8e16-e99e6091acd8)

![add-create-workflow](https://github.com/user-attachments/assets/0ff4066f-56bd-44b2-8255-13b10820e912)

**Additional context**

**Comment by jdavcs** [comment]
Fixed in #19281
