### ISSUE TITLE
Strange behavior when creating collections

### ISSUE THREAD

**Issue by Smeds** [galaxyproject/galaxy#19270]
I encountered unexpected behavior while trying to create multiple collections. Creating the first collection works as expected. However, when I attempt to create a second collection immediately afterward, the 'Create a collection...' popup window appears as soon as I select a new element. Although I can close the window, continue selecting elements, and then click 'Build...' to successfully create multiple collections, the premature appearance of the popup is inconvenient and interrupts the workflow.

**Browser and Operating System**
Operating System: Linux
Browser: Firefox, Chrome

**To Reproduce**
1. Create a collection
2. Directly after start selecting new items to create a second collection

**Expected behavior**
That the popup window doesn't appear before I select "Build ..'

**Screenshots**
![test](https://github.com/user-attachments/assets/f6d92a1e-c029-4162-9fb7-a0a5234cdbaf)

**Comment by davelopez** [comment]
Thank you! I'll investigate.

**Comment by davelopez** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/19276
