### ISSUE TITLE
UI Help for Workflow Metrics

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#19289]
https://github.com/galaxyproject/galaxy/pull/19283 was an important set of ~enhancements~ "fixes" for workflow metrics but it is still rough. I couldn't get the legends in the pie charts to render cleanly when embedded in the page they way they do in the Vega editor and the way the pie charts are laid out in their row is a little off center of the their respective columns in a way that is a little visually unappealing. If someone more knowledgable in the ways of flexbox and/or vega could take a pass - it would mean a lot and help a really important cool new feature from Marius that deserves a lot of highlighting and advertising.

**Comment by davelopez** [comment]
I'll try to take a look :+1:

**Comment by ahmedhamidawan** [comment]
Fixed in #19291
