### ISSUE TITLE
Recently waiting time is too long

### ISSUE THREAD

**Issue by huipingis** [galaxyproject/galaxy#19317]
**Describe the bug**

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: (check <galaxy_url>/api/version if you don't know)
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**Browser and Operating System**
Operating System: Windows, Linux, macOS
Browser: Firefox, Chrome, Chrome-based, Safari

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mvdbeek** [comment]
You can contact the support for these instances with specifics and they will be able to help you further.
