### ISSUE TITLE
"Do not show again" for unselecting history items after select all is forgotten after page reload

### ISSUE THREAD

**Issue by astrovsky01** [galaxyproject/galaxy#19345]
When using multiselect in the history, and selecting all, then unselecting one or more items, a box pops up informing the user that operations will not affect the entirety of the history now. There is also a button on this prompt to permanently dismiss this message. This button works until reload, at which point it will show up again on performing the same actions as before.

https://github.com/user-attachments/assets/9967c714-b8bd-4dae-b2fa-23c691d2b88c

**Comment by davelopez** [comment]
Thanks for the report @astrovsky01! It seems there is a regression here. I'll take a look.

**Comment by davelopez** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy/pull/19348
