### ISSUE TITLE
Galaxy unnecessarily converts tilde (~) to X and single quote to X

### ISSUE THREAD

**Issue by george-weingart** [galaxyproject/galaxy#19371]
We have a an application that needs to receive the following parameters (The single quotes are part of the required parm):
Parameter 1  - $formula1:
'~diagnosis + dysbiosis_state + antibiotics + age + reads'
Parameter 2: $reference1
'diagnosis,nonIBD;dysbiosis_state,none;antibiotics,No'

The parms are defined in the script as follows:

       <param name="formula1" label="formula: For sample use:  diagnosis + dysbiosis_state + antibiotics + age + reads (Galaxy provides the ~)"  value="" type="text" format="text"/>
        <param name="reference1" label="reference: For sample use: diagnosis,nonIBD;dysbiosis_state,none;antibiotics,No "  value="" type="text" format="text"/>

The problem is that they resolve as follows:
--formula=__sq__Xdiagnosis + dysbiosis_state + antibiotics + age + reads__sq__
 --reference=__sq__diagnosis,nonIBDXdysbiosis_state,noneXantibiotics,No__sq__ 
 
 We can overcome the _SQ_ issue and convert it to '  using
  #set $for1 = $for0.replace("_SQ_","'")
  
  The problem are the X's - once it has to resolve to tilde and once to semicolon and it is a buggy solution as a field can have a valid  X in the name 
![Screenshot 2024-12-27 152948](https://github.com/user-attachments/assets/ccf7d8db-34c8-40dc-85b0-8b872e7aeadd)
![Screenshot 2024-12-27 153040](https://github.com/user-attachments/assets/fab0848a-c825-442a-a994-6d7363a29aa4)
![Screenshot 2024-12-27 154304](https://github.com/user-attachments/assets/a13b8803-3125-4443-95c6-703075294c01)
![Screenshot 2024-12-27 154317](https://github.com/user-attachments/assets/fe8dec75-e893-4e51-af23-e8fb4ebfbeb3)

**Comment by nsoranzo** [comment]
Have a look at https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-param-sanitizer

I'd suggest to ask such questions to the [Help forum](https://help.galaxyproject.org/) or the [IUC matrix channel](https://matrix.to/#/#galaxy-iuc_iuc:gitter.im).

**Comment by george-weingart** [comment]
Hello Nicola,
I want to thank you for your prompt and quick response.

Excellent answer,  I used the references you mentioned and that immediately solved our problem.
Good job and many thanks !
Happy Holidays and Happy New Year and Thanks again !
George Weingart PhD
Huttenhower Lab
Harvard School of Public Health
