### ISSUE TITLE
Problem passing input fields with single quotes

### ISSUE THREAD

**Issue by george-weingart** [galaxyproject/galaxy#19370]
We need to pass to an app input from the screen that contains single quotes and are encountering problems:
Enclosed an image of the command:
 
![Screenshot 2024-12-26 132006](https://github.com/user-attachments/assets/e2cac4fe-0c17-4150-93ed-a0c4099256a1)

We want to pass the --formula  and the --reference so that it resolves as above.
The problem:
When we use input parameter fields and try to pass the values we encounter 2 issues:
1. The single quote resolves as _SQ_ - we want it as a single quote
2. The ~ symbol resolves as "X"
![Screenshot 2024-12-26 132210](https://github.com/user-attachments/assets/548c928d-c159-41cc-889b-e9e6765928ef)

How can we overcome these issues?

Below the definition of the fields and screen prints.
Thanks!

 <param name="formula1" label="formula: For sample use: '~ diagnosis + dysbiosis_state + antibiotics + age + reads' "  value="" type="text" format="text"/>
        <param name="reference1" label="reference: For sample use: 'diagnosis,nonIBD;dysbiosis_state,none;antibiotics,No' "  value="" type="text" format="text"/>
  
  We enter in the screen in the field formula1:
  
  '~ diagnosis + dysbiosis_state + antibiotics + age + reads'

and in the field  reference1:

'diagnosis,nonIBD;dysbiosis_state,none;antibiotics,No'

  And it resolves:
  
  Rscript '/export/galaxy-central/tools/maaslin3/R/maaslin3.R' /tmp/tmp.maaslin3_taxonomy.tsv /tmp/tmp.maaslin3_metadata.tsv /tmp/tmp.maaslin3_output --formula=__sq__X diagnosis + dysbiosis_state + antibiotics + age + reads__sq__ --reference=__sq__diagnosis,nonIBDXdysbiosis_state,noneXantibiotics,No__sq__
  
  Which does not work
![Screenshot 2024-12-26 130849](https://github.com/user-attachments/assets/d1849092-f4e7-4a40-8e7f-66a8dcf26542)

**Comment by bgruening** [comment]
@george-weingart I hope you found a solution already. Here is a short answer for completeness. Galaxy sanitises the user inputs by default. This is a security feature to prevent command line injections. You can tweak this using the sanitizer element in your tool metadata description: https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-param-sanitizer

**Comment by george-weingart** [comment]
Hi Bjorn,
I did.

Really appreciate your help!

Nicola immediately responded with an excellent response and I implemented
it and worked.

Thank you so much!
Happy New Year and best regards,
George
