### ISSUE TITLE
Installations from TS broken on dev

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1940]
probably due to the changes in the API

more details here
https://github.com/galaxyproject/galaxy/pull/1821/files/b15a7ff06df23d7004f670f34638fe9ee5d33f92#r56447368

ping @davebx @bgruening

**Comment by bgruening** [comment]
@martenson I can reproduce this easily with a TTS enabled Docker container. I thought this is due to the latest API changes that are still WIP to enable the new TS UI.
Let me know how I can help.
