### ISSUE TITLE
Tools no longer respect display_interface="False" or require_login="True"

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#1951]
A tool interface should not be displayed when `display_interface="False"`, instead the user used to get forwarded to the welcome page.

Tool interface should not be displayed when `require_login="True"`, instead user should get log in screen and be redirected back to the tool after logging in. Tool should not be executable when user is not logged in.

See e.g.: 
tools/genomespace/genomespace_importer.xml
https://usegalaxy.org/?tool_id=genomespace_importer

ping @guerler

**Comment by guerler** [comment]
Since this is at least partially an old issue, it might be reasonable to target dev instead of 16.01 but I leave it up to you. If we target 16.01 we should make sure that there are no missed side effects e.g. toolshed code relying on unconstrained tool access. Maybe @martenson and @jmchilton can help.

**Comment by martenson** [comment]
I do not know about any TS interactions with these params, I suspect the features are pure Galaxy-side.

Do we know since when were they ignored?

**Comment by guerler** [comment]
The api never limited the access for regular tools by checking the `require_login` flag.

**Comment by martenson** [comment]
@guerler are you saying that if you knew the tool ID you could have always submitted a job with the tool?

**Comment by guerler** [comment]
Given that you have a valid API key, I could not find any revision of the api which validates the `require_login` flag. However, I do not think that this is critical. The flag is undocumented. I think all we should do is to double check and make sure that there aren't any other undesired side effects of checking the flag, such as e.g. the one fixed for the tool panel search field.

**Comment by martenson** [comment]
well if you are using API key you are technically 'logged in' - this should prevent anonymous job runs imo

**Comment by guerler** [comment]
You are right, but I just see that the job submission endpoint is actually set to `@expose_api_anonymous` so in this case the api key is not required.

**Comment by blankenberg** [comment]
I'd assume that both of these flags are just something that had fallen through the cracks when we stopped using the old tool form and moved to targeting the API, etc.

**Comment by blankenberg** [comment]
Reopening, due to unexpected behavior. 

Test with e.g. usegalaxy.org/tool_runner?tool_id=genomespace_importer / https://usegalaxy.org/tool_runner?tool_id=genomespace_importer&URL=https%3A%2F%2Fdm.genomespace.org%2Fdatamanager%2Ffile%2FHome%2Fdan%2FGalaxy%2520History%2520Item%25201c084ec747652f8f%2520%28d33e32db742aed56%29%2520-%25202%3A%2520GenomeSpace%2520import%2520on%2520MT%2520Genes.bed.bed

When Not Logged in, you get a "Tool 'genomespace_importer' does not exist." message. You should instead be directed to the Login page, and then redirected back to the tool (along with original parameters, if any) after logging in.

When `display_interface=False`, the tool should only be executed (in this case) when e.g. URL is provided. Galaxy used to do a hard-check for the submit button being included, or a named 'URL' parameter, before attempting to execute tool. Now it is executing the tool with an empty URL parameter. It used to see that the tool was not being executed and then would forward back to the landing/welcome page.

**Comment by blankenberg** [comment]
The not logged in issue is fixed with https://github.com/galaxyproject/galaxy/pull/2180. 

But the executing when URL is not provided is still outstanding.

**Comment by blankenberg** [comment]
Longer issue about generic problems with parameters similar to `URL` here: https://github.com/galaxyproject/galaxy/issues/2200

**Comment by guerler** [comment]
Closing issue in favor of #2200
