### ISSUE TITLE
[16.01] Everything div in main page is duplicated

### ISSUE THREAD

**Issue by carlfeberhard** [galaxyproject/galaxy#1975]
Using 16.01 to Look at "[galaxy] After upgrade to release_16.01: jobs are no longer run" in galaxy-dev and the user deactivation banner problems there, I saw that the div with id 'everything' is now appearing twice. This includes all it's contents: background, banners, left, right, and center panels.

Backbone views are now being attached in one or the other '#everything's.

Looks like PR #1407 and specifically this line: https://github.com/galaxyproject/galaxy/commit/339ad57f3fa626fe30c1bf26f90e0647be038cc9#diff-f12b71b76f35a53beaaff59d5cc86ba7L45

This doesn't happen previous to this commit.

@guerler

**Comment by dannon** [comment]
Closed with #1976
