### ISSUE TITLE
makefile grooming

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#1979]
_list under construction_
- [x] every make command starts with 

```
Makefile:170: warning: overriding commands for target `help'
Makefile:19: warning: ignoring old commands for target `help'
```
- [x] `lint` target lints everything in the folder and seems to ignore setup.cfg? - I have hundreds of failures in test/ scripts/ lib/ (e.g. E128 which should be ignored)
- [ ] `make docs` will yield `no theme named 'sphinx_rtd_theme' found (missing theme.conf?)` unless you `pip install sphinx_rtd_theme` - do we want to stress this out?
  - [ ] maybe even add these to the requirements-dev.txt along with e.g. pygithub that is also needed?

**Comment by hexylena** [comment]
@jmchilton added in a new help target as part of https://github.com/galaxyproject/galaxy/commit/eee044aa707f9fa6d4c800b4d655fd01b2e08e84

**Comment by hexylena** [comment]
I'll fix that now

**Comment by nsoranzo** [comment]
> `lint` target lints everything in the folder and seems to ignore setup.cfg? - I have hundreds of failures in test/ scripts/ lib/ (e.g. E128 which should be ignored)

This is due to a bug in flake8: https://gitlab.com/pycqa/flake8/merge_requests/53 , workaround is to delete `~/.config/flake8` .

**Comment by hexylena** [comment]
for make docs should we just add a line to `pip install sphinx_rtd_theme`?

**Comment by martenson** [comment]
@erasche also maybe `pip install sphinx` ?

**Comment by hexylena** [comment]
@martenson +1

**Comment by martenson** [comment]
so, @natefoo  @jmchilton should these requirements be in the official dev-requirements.txt?

**Comment by hexylena** [comment]
dev. (Maybe someday we can ship browsable docs with galaxy at which point it'd make more sense for sphinx to be built-in, but until then dev is a great place IMO. Not that you asked me :P)

**Comment by martenson** [comment]
This seems resolved
