### ISSUE TITLE
Issue with API method Groups update

### ISSUE THREAD

**Issue by i-am-b-soto** [galaxyproject/galaxy#1987]
Hello Galaxy Developers. 

I'm writing PHP wrapper functions for Galaxy API methods. 
When I write a PHP function calling the 'update' function of groups using the HTTP request PUT, on the URL /api/groups/<group_id>  
I receive a 404 error.  

I am curious as to the mistakes I am committing here. for the post field data I am inputting 
'user_ids' => json_encode (array(user_id_1, user_id_2))
'role_ids'=> json_encode (array(user_id_1, user_id_2))
'name'=> 'name'

But this does not seem to work. Would there perhaps be any explanation why? Thank you.

**Comment by martenson** [comment]
@Iamsoto are you an admin when creating the request? Because the method is annotated with `@web.require_admin`
https://docs.galaxyproject.org/en/master/_modules/galaxy/webapps/galaxy/api/groups.html#GroupAPIController.update

**Comment by hexylena** [comment]
Closed pending more feedback
