### ISSUE TITLE
Problem with 'function build_for_rerun' in jobs api

### ISSUE THREAD

**Issue by cwytko** [galaxyproject/galaxy#1988]
localhost:8080/api/jobs/63cd3858d057a6d1/build_for_rerun?key=636a1ff620704091c81ae2559d8c4d2c

The above url gives the following response:

{

```
"err_msg": "[history_id=None] Failed to retrieve history. History unavailable. Please specify a valid history id.",
"err_code": ​0
```

}

This is an api call to ./galaxy/lib/galaxy/webapps/galaxy/api/jobs.py to the function build_for_rerun, the only input parameter that I was aware to give to the function was a job id (as specified in the comment block). 
I've attempted this GET request from curl and from a web browser only to receive this response; I do  not understand why it's telling me that a history_id is needed.
Thank you

**Comment by dannon** [comment]
Followed up with guerler, #2668 should probably fix this.
