### ISSUE TITLE
Trackster suddenly doesn't display data

### ISSUE THREAD

**Issue by malloryfreeberg** [galaxyproject/galaxy#1994]
I have a collection of bigWig, bigBed, bed, and gtf files that I've loaded onto Trackster from Galaxy for the ce10 genome. The tracks load fine (Fig 1), and I've been looking at them for an hour or so. Some of the bed tracks I "hide" during this time. I left for an hour and came back, and now all the tracks that were originally showing are now blank (Fig 2). There are no errors thrown. I tried the following things to bring the data back: hide/show the track, refreshing the page, re-adding the same track, changing the display type/color/scale. The data still don't show. This is true for all the bigWig, bed, and gtf tracks that were originally showing. Strangely, the bigBed tracks that were initially hidden are displaying correctly (Fig 3). To fix the issue, I have to re-upload the data file into Galaxy, reformat each data file, and then re-add to Trackster. Please help!
![fig1](https://cloud.githubusercontent.com/assets/10993501/13995301/021ef9cc-f0ff-11e5-9466-6452f8d6efd1.png)
![fig2](https://cloud.githubusercontent.com/assets/10993501/13995303/0220e458-f0ff-11e5-8bc3-4af271c14edc.png)
![fig3](https://cloud.githubusercontent.com/assets/10993501/13995302/021fdc34-f0ff-11e5-97c3-5e5dace91099.png)

**Comment by jxtx** [comment]
Looks like some incorrectly generated URLs

![image](https://cloud.githubusercontent.com/assets/79973/13997270/ae782ca4-f107-11e5-822b-b47d90b1251d.png)

**Comment by malloryfreeberg** [comment]
Some of the bigWig and bigBed tracks are displaying now (after sharing the track, not sure if related). Gtf and bed files still not displaying.

Getting similar js errors regarding URLs, but "500 (Internal Server Error)"

![errors1](https://cloud.githubusercontent.com/assets/10993501/13997477/c158da3e-f108-11e5-8bf9-80b85f6cf598.png)

**Comment by jxtx** [comment]
Okay, I suspect what I'm seeing is a different problem related to the shared view.

**Comment by dannon** [comment]
URL generation should be fixed in #1999.  Now on to the first part.

**Comment by malloryfreeberg** [comment]
wig and gtf files still disappearing....

![error1_4-8-16](https://cloud.githubusercontent.com/assets/10993501/14391449/0f17b7ee-fd8a-11e5-8fc5-d34043478ea6.png)
![error2_4-8-16](https://cloud.githubusercontent.com/assets/10993501/14391450/0f1a2baa-fd8a-11e5-8cd4-bf7f6e98d933.png)

**Comment by malloryfreeberg** [comment]
Any update on fixing this issue? I had a good stretch of time where my tracks weren't disappearing. Then it happened again today to all the bed/gtf/bam tracks I had loaded. I'm not sure if this is helpful, but it happened immediately after I purged my history of hidden and deleted datasets. Perhaps this is also deleting hidden datasets being used by Trackster?

**Comment by dannon** [comment]
@malloryfreeberg That extra bit of info is super helpful.  The error message (from those API calls -- no such file or directory) makes complete sense given the context of purged hidden datasets.

I'll try think of a more graceful solution here, but I guess one option is to have trackster automatically regenerate the extra files it needs when they are found to be deleted.  Seems heavy-weight to me.  Use of 'hidden' datasets for things like this (and allowing direct deletion of them) is something we've talked about revisiting the handling of a few times in the past, though.

**Comment by malloryfreeberg** [comment]
It just clicked today. I'm usually very OCD about clearing out my history of unneeded datasets, but I hadn't been doing it for a while due to laziness. I hope this helps resolve things quickly!
