### ISSUE TITLE
fix fontawesome issues in data libraries

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2001]
- [x] default icon sizes are unexpected after some fontawesome change (should be addressed by #2000 )
- [x] somehow text in some buttons is being rendered as fontawesome family instead of our usual family
  ![screenshot 2016-03-23 16 53 55](https://cloud.githubusercontent.com/assets/1814954/14000516/ed2802ac-f117-11e5-8101-9d8b307ce162.png)
  ![screenshot 2016-03-23 16 54 50](https://cloud.githubusercontent.com/assets/1814954/14000532/f94c89cc-f117-11e5-9a34-af15996e092c.png)

**Comment by martenson** [comment]
@guerler @carlfeberhard do you guys have any tip why is the text in the left 3 buttons behaving like that?
the markup is:

``` html
<button data-toggle="tooltip" data-placement="top" title="Import dataset into history" class="btn btn-default toolbtn-import-dataset primary-button toolbar-item" type="button">
<span class="fa fa-book"> to History</span>
</button>
```

the 'permissions' button has a different markup (`<a><button></button></a>`)

**Comment by carlfeberhard** [comment]
I believe it'll work if you move the text out of the span.
(Edit) in other words:

```
 <span class="fa fa-book"></span> to History
```

**Comment by martenson** [comment]
Thanks a lot @carlfeberhard  - seems to be the issue!

**Comment by martenson** [comment]
related to #1177
