### ISSUE TITLE
common_startup does not install optional wheels for TS

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2034]
when trying to start fresh TS clone using postgres DB I end up with 

```
ImportError: No module named psycopg2
```

ref d15b1030c5bad75f41e46bdc38d860ebb35bd4fe
ping @natefoo 

is it because `$GALAXY_CONFIG_FILE` does not exist? https://github.com/galaxyproject/galaxy/blob/dev/scripts/common_startup.sh#L166

**Comment by natefoo** [comment]
Yes, this is why. You can install manually pretty easily:

``` console
$ ./.venv/bin/pip install --index-url=https://wheels.galaxyproject.org/simple psycopg2
```

**Comment by martenson** [comment]
@natefoo but theoretically we want that to be automated during startup, right?

**Comment by natefoo** [comment]
Sure. It's the tool shed though, so if it's a lot of work, having one manual step is not a huge deal.
