### ISSUE TITLE
TS with psycopg 2.6.1 won't run on OSX

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2035]
possibly caused by https://psycopg.lighthouseapp.com/projects/62710/tickets/111-library-not-loaded-libssl100dylib and solved by http://mithun.co/hacks/library-not-loaded-libcrypto-1-0-0-dylib-issue-in-mac/

```
  File "/Users/marten/devel/git/toolshed/galaxy/.venv/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
ImportError: dlopen(/Users/marten/devel/git/toolshed/galaxy/.venv/lib/python2.7/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: libssl.1.0.0.dylib
  Referenced from: /Users/marten/devel/git/toolshed/galaxy/.venv/lib/python2.7/site-packages/psycopg2/_psycopg.so
  Reason: image not found
```

not sure if we can do anything on our side...

**Comment by martenson** [comment]
as a bonus you have to restart OSX in  recovering mode following this procedure: https://telatbandel.wordpress.com/2016/01/14/copying-file-libssl-1-0-0-dylib-to-usrlib-on-os-x-el-capitan/ in order to be able to change the links in /usr/lib/
Thanks @apple

**Comment by martenson** [comment]
interestingly, for whatever reason, my development clone of TS (different from this one I created the report for) runs on the same pysocpg2 version without a problem...

**Comment by nsoranzo** [comment]
@martenson Is this still relevant?

**Comment by martenson** [comment]
@nsoranzo most probably not, I run TS locally without an issue now
