### ISSUE TITLE
Local testing on OSX

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#2041]
Per conversation with @martenson, many tests are failing on OSX specifically, causing Jenkins to be the sole testing mechanism for some people.  This is a placeholder issue for us to follow up on those failures and resolve the issues so Jenkins isn't the only way the tests get run.
- [ ] #2034 
- [ ] #2035

**Comment by mvdbeek** [comment]
@dannon This is just my experience, perhaps it helps:
In general the tests run fine for me (OSX 10.11.2), except for the tools.test_watcher.test_watcher unit test, which always fails for me.

```
======================================================================
FAIL: tools.test_watcher.test_watcher
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/marius/src/galaxy/.venv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/marius/src/galaxy/test/unit/tools/test_watcher.py", line 26, in test_watcher
    wait_for_reload(lambda: toolbox.was_reloaded("cool_tool"))
  File "/Users/marius/src/galaxy/test/unit/tools/test_watcher.py", line 56, in wait_for_reload
    assert reloaded
AssertionError
```

I did notice some failing api/framework tests, but they disappeared when I installed gnu-coreutils and python-2.7.10 through brew.
I'm running the run_tests.sh to confirm this.

**Comment by nsoranzo** [comment]
We are again running `py27-first_startup` tox test under macOS on Travis, and many core team developers use macOS laptop, so I am not sure this is still relevant as a tracker issue.
