### ISSUE TITLE
bug with hidden_data?

### ISSUE THREAD

**Issue by methylome** [galaxyproject/galaxy#2050]
https://github.com/galaxyproject/tools-devteam/issues/341
In release 16_01, devteam's cufflinks 2.2.1.0 was failed and I guess it's caused by a galaxy's bug with hidden_data. Actually I can't find how hidden_data is set.

In cufflinks_wrapper.xml, the following code 
...
`## Include reference annotation?`
`#if $reference_annotation.use_ref == "Use reference annotation":`
`-G $reference_annotation.reference_annotation_file`
`$reference_annotation.compatible_hits_norm`
`#end if`
`#if $reference_annotation.use_ref == "Use reference annotation guide":`
`-g $reference_annotation.reference_annotation_guide_file`
`--3-overhang-tolerance=$reference_annotation.three_overhang_tolerance`
`--intron-overhang-tolerance=$reference_annotation.intron_overhang_tolerance`
`$reference_annotation.no_faux_reads`
`#end if`
`...`
`## Include global model if available.`
`#if $global_model:`
`--global_model=$global_model`
`#end if`
`...`
`<param name="global_model" type="hidden_data" label="Global model (for use in Trackster)" optional="True"/>`

generated the following in tool_script.sh where `$global_model` is set to the value of `$reference_annotation.reference_annotation_guide_file`.

`python /home/galaxy/dev/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/cufflinks/64698e16f4a6/cufflinks/cufflinks_wrapper.py --input=/home/galaxy/dev/database/files/000/dataset_634.dat --assembled-isoforms-output=/home/galaxy/dev/database/files/000/dataset_654.dat --num-threads="${GALAXY_SLOTS:-4}" -I 300000 -F 0.1 -j 0.15   -g /home/galaxy/dev/database/files/000/dataset_26.dat --3-overhang-tolerance=600 --intron-overhang-tolerance=50   -b --ref_file=/data/hg19/hg19dip.fa  -u  --global_model=/home/galaxy/dev/database/files/000/dataset_26.dat`

**Comment by nsoranzo** [comment]
@methylome I think `global_model` should be set inside `<trackster_conf>` in cufflinks.xml to the path of the output dataset `total_map_mass`, so what you are seeing is really suspicious.
But I'm not sure this is what causes galaxyproject/tools-devteam#341 for you.

**Comment by methylome** [comment]
I haven't had this problem in release 15_10.

**Comment by martenson** [comment]
possible solvers: @blankenberg @jmchilton @guerler

**Comment by martenson** [comment]
needs backport to 16.01

**Comment by guerler** [comment]
I was not successful in reproducing this. I tested Cufflinks on main a couple times, but the optional hidden_data field remained empty.

**Comment by methylome** [comment]
Can you show me your command line in tool_script.sh?

**Comment by guerler** [comment]
Sure. Thanks for this report btw. So my local run creates this script:
`PACKAGE_BASE=/Users/guerler/galaxy-toolshed/cufflinks/2.2.1/devteam/cufflinks/a1ea9af8d5f4; export PACKAGE_BASE; . /Users/guerler/galaxy-toolshed/cufflinks/2.2.1/devteam/cufflinks/a1ea9af8d5f4/env.sh; cufflinks 2>&1 | head -n 1 > /Users/guerler/galaxy/database/tmp/GALAXY_VERSION_STRING_2715 2>&1; python /Users/guerler/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/cufflinks/a1ea9af8d5f4/cufflinks/cufflinks_wrapper.py --input=/Users/guerler/galaxy/database/files/002/dataset_2696.dat --assembled-isoforms-output=/Users/guerler/galaxy/database/files/002/dataset_2714.dat --num-threads="${GALAXY_SLOTS:-4}" -I 300000 -F 0.1 -j 0.15`

and these are the parameter details from Main:
![cufflinks](https://cloud.githubusercontent.com/assets/2105447/14290068/992a2f7c-fb2b-11e5-8c07-3178cef14e2b.png)

**Comment by methylome** [comment]
@guerler I think you didn't specify a GTF file. `global_model' is set as the GTF file.

**Comment by guerler** [comment]
`PACKAGE_BASE=/Users/guerler/galaxy-toolshed/cufflinks/2.2.1/devteam/cufflinks/a1ea9af8d5f4; export PACKAGE_BASE; . /Users/guerler/galaxy-toolshed/cufflinks/2.2.1/devteam/cufflinks/a1ea9af8d5f4/env.sh; cufflinks 2>&1 | head -n 1 > /Users/guerler/galaxy/database/tmp/GALAXY_VERSION_STRING_2719 2>&1; python /Users/guerler/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/cufflinks/a1ea9af8d5f4/cufflinks/cufflinks_wrapper.py --input=/Users/guerler/galaxy/database/files/002/dataset_2696.dat --assembled-isoforms-output=/Users/guerler/galaxy/database/files/002/dataset_2729.dat --num-threads="${GALAXY_SLOTS:-4}" -I 300000 -F 0.1 -j 0.15   -G /Users/guerler/galaxy/database/files/002/dataset_2726.dat --compatible-hits-norm  -b --ref_file=/Users/guerler/galaxy/database/files/002/dataset_2681.dat  -u   --library-type=ff-firststrand --mask-file=/Users/guerler/galaxy/database/files/002/dataset_2724.dat --inner-mean-dist=45 --inner-dist-std-dev=20 --max-mle-iterations=5000 --junc-alpha=0.001 --small-anchor-fraction=0.09 --overhang-tolerance=8 --max-bundle-length=3500000 --max-bundle-frags=1000000 --min-intron-length=50 --trim-3-avgcov-thresh=10 --trim-3-dropoff-frac=0.1`

**Comment by methylome** [comment]
It looks we are testing different version: `a1ea9af8d5f4` vs `64698e16f4a6`.

**Comment by methylome** [comment]
![cufflinks](https://cloud.githubusercontent.com/assets/9466414/14291233/a0e812d8-fb30-11e5-8be1-2f273da3bc15.png)
As shown in the attached file, I have the latest version but it's different from yours and the tool shed.

**Comment by nsoranzo** [comment]
a1ea9af8d5f4 is the latest, 64698e16f4a6 is the one before, but should be a minor update.

**Comment by martenson** [comment]
devteam/package_cufflinks_2_2_1 has only one revision: 899067a260d1
devteam/cufflinks has 10 revisions: `a1ea9af8d5f4` is the latest and `64698e16f4a6` is the penultimate one.

**Comment by methylome** [comment]
I think the problem occurs before package because wrong command line is generated. Why my galaxy can't recognize the latest version?

**Comment by nsoranzo** [comment]
In the admin interface, click "Manage installed tools" on the left menu, then click "Update tool shed status" on the upper right corner.

**Comment by mvdbeek** [comment]
@methylome just for reference, you're not using [this patch](https://github.com/galaxyproject/tools-iuc/issues/631#issuecomment-191254337) anymore? It shouldn't hurt, but it's better to be on release_16.01 which has a better solution for that problem.

Also, can you give us the output of `git status` and `git branch -v` ?

**Comment by methylome** [comment]
@mvdbeek I am using your patch and will remove it. Yesterday, I merged into the latest version of branch release_16.01: 65a7ebe (origin/release_16.01) Merge pull request #2072 from mvdbeek/backport_1738. 
@nsoranzo Now I can see a1ea9af8d5f4 is installed on `Installed tool shed repositories`, but 64698e16f4a6 is shown in `Installed tool shed repository 'cufflinks'`. I'm gonna remove and install it.

**Comment by methylome** [comment]
I tried to reinstalled with and without mvdbeek's patch. New installed version is 64698e16f4a6, not a1ea9af8d5f4. On another galaxy instance, I can see a1ea9af8d5f4 is really installed. I'm pretty sure both instances are the same.

**Comment by martenson** [comment]
@methylome you should not be able to install `64698e16f4a6` because it is not an installable revision. The only way it can be on your Galaxy is from a previous install (are you 'uninstalling' or 'deactivating' ?) - that had to happen before the revision a1ea9af8d5f4 was in the TS.

at `Installed tool shed repositories` menu try selecting advanced search and browse `Deactivated or uninstalled` repos. Use it to find deactivated or uninstalled cufflinks, and reinstall it.

**Comment by methylome** [comment]
@martenson I uninstalled and confirmed the directory was gone.

**Comment by martenson** [comment]
@methylome and the new install still gives you `64698e16f4a6`? :/

**Comment by methylome** [comment]
@martenson Yes. It's wired.

**Comment by martenson** [comment]
@methylome can you please come to IRC for a minute? I will watch the MTS logs while you try installing
https://wiki.galaxyproject.org/Support/IRC

**Comment by martenson** [comment]
```
15:34:26  mehylome | What can I do for you?                                                                                                                             │
15:34:40 martenson | could you please uninstall the devteam/cufflinks ?                                                                                                 │
15:34:47 martenson | and then try to install the latest revision                                                                                                        │
15:35:46  mehylome | Uninstalling ...                                                                                                                                   │
15:36:24  mehylome | Done.                                                                                                                                              │
15:36:59  mehylome | Installing...                                                                                                                                      │
15:37:11  mehylome | Cloning..                                                                                                                                          │
15:37:18  mehylome | Setting tool version                                                                                                                               │
15:37:21  mehylome | Installed.                                                                                                                                         │
15:37:24 martenson | revision?                                                                                                                                          │
15:37:43  mehylome | Same. /home/galaxy/dev/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/cufflinks/64698e16f4a6/cufflinks                                            │
15:37:48 martenson | you requested "/repository/get_tool_versions?owner=devteam&changeset_revision=a1ea9af8d5f4&name=cufflinks"                                         │
15:38:10 martenson | could you please loon in the tool folder                                                                                                           │
15:38:48 martenson | and tell me if tehre is exactly this string "<regex match="Exception" />"                                                                          │
15:38:54 martenson | in cuff_macros.xml                                                                                                                                 │
15:39:11  mehylome | ls /home/galaxy/dev/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/cufflinks/                                                                     │
15:39:13 martenson | (without the outside ")                                                                                                                            │
15:39:17  mehylome | 64698e16f4a6  9aab29e159a7                                                                                                                         │
15:39:36 martenson | 9aab is even older revision                                                                                                                        │
15:39:47 martenson | please open the 6469                                                                                                                               │
15:40:37  mehylome | Yes it's in line 14.                                                                                                                               │
15:41:24 martenson | so there is no semicolon, as in "<regex match="Exception:" />"                                                                                     │
15:41:37  mehylome | No semicolon                                                                                                                                       │
15:41:39 martenson | that means you actually have a1ea9af8d5f4                                                                                                          │
15:41:42 martenson | just in the wrong folder                                                                                                                           │
15:41:45 martenson | damn
```

**Comment by methylome** [comment]
@guerler I've reproduced this with Perform Bias Correction. However, it doesn't always happen. I attached 3 files of which one was succeeded and the others failed. The latter was run for the same input. Is it possible this error depends on the input?
[cufflinks1.txt](https://github.com/galaxyproject/galaxy/files/205319/cufflinks1.txt)
[cufflinks2.txt](https://github.com/galaxyproject/galaxy/files/205320/cufflinks2.txt)
[cufflinks3.txt](https://github.com/galaxyproject/galaxy/files/205321/cufflinks3.txt)

**Comment by martenson** [comment]
@methylome We still have trouble reproducing it so please bare with us.

How are you executing cufflinks? Are you selecting it from the tool panel, running it in a workflow or using re-run on the dataset? Are you using Trackster?

**Comment by martenson** [comment]
since we do not have a WIP for this yet, I am pushing it to 16.07

**Comment by methylome** [comment]
I've run it in a workflow and then reloaded and selected it from the tool panel. This error didn't happen in a fresh run of the workflow. I'm not sure what happened, but have updated the galaxy to the latest commit of release_16.01. However, even in the latest version, rerunning a failed job hasn't been succeeded as I posted a few days ago.

**Comment by martenson** [comment]
@methylome are you re-running a failed job that was originally created by a workflow run or are you re-running a failed job that has been created by running cufflinks through the tool form?

**Comment by methylome** [comment]
The former to use the output of tophat.

**Comment by martenson** [comment]
and within your workflow are you attaching any input to the `global_model` variable?

**Comment by methylome** [comment]
I don't think so because the pipeline worked in release_15.10.

**Comment by methylome** [comment]
I attached my pipeline which doesn't use the variable.
[Galaxy-Workflow-Tuxedo_2.2_for_known_genes_in_two_conditions.ga.zip](https://github.com/galaxyproject/galaxy/files/210712/Galaxy-Workflow-Tuxedo_2.2_for_known_genes_in_two_conditions.ga.zip)

**Comment by martenson** [comment]
@methylome as you can see here:
![screenshot 2016-04-08 15 11 43](https://cloud.githubusercontent.com/assets/1814954/14394845/419709ec-fd9c-11e5-8752-8fcb5829a96f.png)
it seems you _did_ attach input to the global_model

Please try to remove it and run the workflow.

**Comment by methylome** [comment]
That's difference from what I can see it. I have two pipelines: Tuxedo 2.2 for known genes in two conditions and Tuxedo 2.2 for novel and known genes in two conditions.
![pipeline1](https://cloud.githubusercontent.com/assets/9466414/14394963/ef820ee4-fd9c-11e5-86a1-a98228f7f8a9.png)

**Comment by methylome** [comment]
Does the pipeline have cuffmerge?

**Comment by martenson** [comment]
@methylome I have just imported the workflow you shared with me i.e. the printscreen with input attached to the global model is from your workflow.

**Comment by methylome** [comment]
Yes, the pipeline uses the variable.

**Comment by martenson** [comment]
well it shouldn't - that variable is supposed to be hidden - it is used only in Trackster

**Comment by methylome** [comment]
As I said, a fresh run was succeeded even with setting the variable because the command line for cufflinks doesn't have it. Anyway, thanks a lot. I'll remove this from the pipeline.

**Comment by martenson** [comment]
@methylome sorry for the bug that caused this (showing this option) - it should be fixed by the PR from @guerler linked above

**Comment by guerler** [comment]
Thx @martenson.

**Comment by methylome** [comment]
Great! My pipeline works well. Thanks a lot.

**Comment by martenson** [comment]
Awesome. Thank you for using Galaxy @methylome .
