### ISSUE TITLE
set_user_disk_usage and --dry-run

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#2053]
``` console
# python scripts/set_user_disk_usage.py -h
Usage: set_user_disk_usage.py [options]

Options:
  -h, --help            show this help message and exit
  -c CONFIG, --config=CONFIG
                        Path to Galaxy config file (config/galaxy.ini)
  -u USERNAME, --username=USERNAME
                        Username of user to update
  -e EMAIL, --email=EMAIL
                        Email address of user to update
  --dry-run             Dry run (show changes but do not save to database)

# python scripts/set_user_disk_usage.py -u eric-rasche --dry-run -c config/galaxy.ini
Loading Galaxy model...
eric-rasche <esr@tamu.edu>: old usage: 193.6 GB change: -12.6 GB

# python scripts/set_user_disk_usage.py -u eric-rasche --dry-run -c config/galaxy.ini
Loading Galaxy model...
eric-rasche <esr@tamu.edu>: old usage: 181.0 GB change: none
```

is the dry run flag supposed to be functional? It immediately made changes to the db.

**Comment by dannon** [comment]
Yes, it's supposed to be functional.  Using postgres or something else?

**Comment by hexylena** [comment]
@dannon postgres.

**Comment by dannon** [comment]
Weird, I tested that and it was working for me.  Which sqlalchemy were you using?  Galaxy's current .venv?

That said, I'm a little wary of how it works, even though it works for me.  It currently actually does a connection.execute("UPDATE..."), which then gets rolled back if it's a dry run.  Except that rollback didn't work for you, something flushed the connection prior to that happening.

**Comment by hexylena** [comment]
- venv
- SQLAlchemy==1.0.8
- postgres 9.4.5

rolling back the transaction is kinda really gross. I'm ignorant of the underlying code, is there a reason it has to do it this way and isn't a simple `SELECT...` query or similar rather than an `UPDATE`?

**Comment by dannon** [comment]
Well, it's an update with a collated select to accurately calculate the disk size.  I'm going to split the query into two bits right now and differentiate the dry run without using the rollback.

**Comment by hexylena** [comment]
@dannon sounds good! Happy to test anything you come up with.
