### ISSUE TITLE
Crash when extracting workflow when using Dataset Collections built under "Analyze Data"

### ISSUE THREAD

**Issue by dtnorth** [galaxyproject/galaxy#2068]
Reported against Version 569b87dc with fastqc d2cf2c0c8a11 from toolshed.g2.bx.psu.edu

To repeat:
- create a dataset collection list of 2 or more .bam files
- run fastqc Read Quality Reports tool with the 'Short read data from your current history' set to the dataset collection list
- The fastqc tool should finish with no issues
- Select to extract the workflow from the history menu
- Click the 'create workflow' button.

The operation fails, with the following output to logs:

```
URL: http://server:8124/workflow/build_from_current_history
File '/home/derek/galaxy_config/galaxy/.venv/lib/python2.7/site-packages/weberror/evalexception.py', line 431 in respond
  app_iter = self.application(environ, detect_start_response)
File '/home/derek/galaxy_config/galaxy/.venv/lib/python2.7/site-packages/paste/recursive.py', line 85 in __call__
  return self.application(environ, start_response)
File '/home/derek/galaxy_config/galaxy/.venv/lib/python2.7/site-packages/paste/httpexceptions.py', line 640 in __call__
  return self.application(environ, start_response)
File '/home/derek/galaxy_config/galaxy/lib/galaxy/web/framework/base.py', line 131 in __call__
  return self.handle_request( environ, start_response )
File '/home/derek/galaxy_config/galaxy/lib/galaxy/web/framework/base.py', line 190 in handle_request
  body = method( trans, **kwargs )
File '/home/derek/galaxy_config/galaxy/lib/galaxy/webapps/galaxy/controllers/workflow.py', line 1016 in build_from_current_history
  workflow_name=workflow_name
File '/home/derek/galaxy_config/galaxy/lib/galaxy/workflow/extract.py', line 29 in extract_workflow
  steps = extract_steps( trans, history=history, job_ids=job_ids, dataset_ids=dataset_ids, dataset_collection_ids=dataset_collection_ids )
File '/home/derek/galaxy_config/galaxy/lib/galaxy/workflow/extract.py', line 145 in extract_steps
  raise Exception( "Failed to extract job." )
Exception: Failed to extract job.
```

This does not fail when there is just one item in the dataset collection.

Happy to support any debug effort.

**Comment by dtnorth** [comment]
As an addition to the above, the same failure is present when attempting to extract any workflow utilising dataset collections, not just FASTQC.

I encountered the same error with PICARD MarkDuplicates built under "Analyse Data "using a dataset collection as input.

> > URL: http://server:8124/workflow/build_from_current_history
> > Module weberror.evalexception:431 in respond         view
> >  app_iter = self.application(environ, detect_start_response)
> > Module paste.recursive:85 in **call**         view
> >  return self.application(environ, start_response)
> > Module paste.httpexceptions:640 in **call**         view
> >  return self.application(environ, start_response)
> > Module galaxy.web.framework.base:131 in **call**         view
> >  return self.handle_request( environ, start_response )
> > Module galaxy.web.framework.base:190 in handle_request         view
> >  body = method( trans, **kwargs )
> > Module galaxy.webapps.galaxy.controllers.workflow:1006 in build_from_current_history         view
> >  workflow_name=workflow_name
> > Module galaxy.workflow.extract:29 in extract_workflow         view
> >  steps = extract_steps( trans, history=history, job_ids=job_ids, dataset_ids=dataset_ids, dataset_collection_ids=dataset_collection_ids )
> > Module galaxy.workflow.extract:145 in extract_steps         view
> >  raise Exception( "Failed to extract job." )

**Comment by jmchilton** [comment]
I believe this was solved with https://github.com/galaxyproject/galaxy/pull/2625. Sorry for the delay in reporting this.
