### ISSUE TITLE
Error after finish a job

### ISSUE THREAD

**Issue by methylome** [galaxyproject/galaxy#2083]
I got the following and don't know what the problem is. This problem occurred even in the latest commit of V16.01.

```
galaxy.jobs.runners.drmaa DEBUG 2016-04-04 13:19:16,995 (861/19145) state change: job finished normally
galaxy.jobs.output_checker INFO 2016-04-04 13:19:18,173 Job 861: Log: tool progress
galaxy.jobs.output_checker INFO 2016-04-04 13:19:18,174 Job 861: Log: tool progress
galaxy.datatypes.metadata DEBUG 2016-04-04 13:19:18,946 loading metadata from file for: HistoryDatasetAssociation 2159
galaxy.datatypes.metadata DEBUG 2016-04-04 13:19:19,480 loading metadata from file for: HistoryDatasetAssociation 2160
galaxy.datatypes.metadata DEBUG 2016-04-04 13:19:20,212 loading metadata from file for: HistoryDatasetAssociation 2161
galaxy.datatypes.metadata DEBUG 2016-04-04 13:19:20,885 loading metadata from file for: HistoryDatasetAssociation 2162
galaxy.datatypes.metadata DEBUG 2016-04-04 13:19:21,466 setting metadata externally failed for HistoryDatasetAssociation 2163: [Errno 2] No such file or directory
galaxy.jobs.runners ERROR 2016-04-04 13:19:23,669 (861/19145) Job wrapper finish method failed
Traceback (most recent call last):
  File "/home/galaxy/dev/lib/galaxy/jobs/runners/__init__.py", line 590, in finish_job
    job_state.job_wrapper.finish( stdout, stderr, exit_code )
  File "/home/galaxy/dev/lib/galaxy/jobs/__init__.py", line 1214, in finish
    dataset.datatype.set_meta( dataset, overwrite=False )
  File "/home/galaxy/dev/lib/galaxy/datatypes/binary.py", line 314, in set_meta
    exit_code = subprocess.call( args=command, stderr=open( stderr_name, 'wb' ) )
  File "/opt/rh/python27/root/usr/lib64/python2.7/subprocess.py", line 524, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/opt/rh/python27/root/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/opt/rh/python27/root/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by nsoranzo** [comment]
What tool were you running? I guess something that created a BAM file.
Please check that `samtools` is installed on the machine which is running the job and is in the PATH of the user under which the job is running.

**Comment by methylome** [comment]
I ran BWA and TOPHAT. You are right another tools worked and samtools are not in PATH, but it worked before, maybe in v 15.10.
Thanks a lot.

**Comment by FredericBGA** [comment]
Hi,

I open this again because I have the same problem (see [https://github.com/galaxyproject/tools-iuc/pull/1446](url))

Samtools is in the path of both machines. The bam file is well created (on another machine, job is launched throught PBS). And I can see it on the Galaxy machine with samtools view.

Any other idea ?
The error message is the same, maybe I miss something obvious ?

Thank you.

> galaxy.datatypes.registry WARNING 2017-08-24 17:16:14,098 Datatype class not found for extension 'bai', which is used as target for conversion from datatype 'bam'
> galaxy.datatypes.registry WARNING 2017-08-24 17:16:14,105 Datatype class not found for extension 'bai', which is used as target for conversion from datatype 'bam'
> galaxy.datatypes.registry WARNING 2017-08-24 17:16:14,108 Datatype class not found for extension 'bai', which is used as target for conversion from datatype 'bam'
> galaxy.datatypes.registry WARNING 2017-08-24 17:16:14,109 Datatype class not found for extension 'bai', which is used as target for conversion from datatype 'bam'
> galaxy.datatypes.registry WARNING 2017-08-24 17:16:14,137 Datatype class not found for extension 'bai', which is used as target for conversion from datatype 'bam'
> galaxy.datatypes.registry WARNING 2017-08-24 17:16:14,142 Datatype class not found for extension 'bai', which is used as target for conversion from datatype 'bam'
> galaxy.datatypes.registry WARNING 2017-08-24 17:16:14,161 Datatype class not found for extension 'bai', which is used as target for conversion from datatype 'bam'
> galaxy.datatypes.registry WARNING 2017-08-24 17:16:14,162 Datatype class not found for extension 'bai', which is used as target for conversion from datatype 'bam'
> galaxy.datatypes.registry WARNING 2017-08-24 17:16:14,163 Datatype class not found for extension 'bai', which is used as target for conversion from datatype 'bam'
> galaxy.datatypes.registry WARNING 2017-08-24 17:16:14,171 Datatype class not found for extension 'bai', which is used as target for conversion from datatype 'bam'
> 192.168.29.12 - - [24/Aug/2017:17:16:13 +0200] "POST /api/tools/toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_bedtobam/2.26.0.0/build HTTP/1.1" 200 - "https://xxx/?job_id=d84d690b80a9abc3&__identifer=vjgvz9oqcur" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0"
> 192.168.29.12 - - [24/Aug/2017:17:16:14 +0200] "GET /api/histories/82f6599ac4995fdb/contents?details=0ab99d9abe7139e7%2Cf67d903ad9ac696f%2Cf71a932e5f894be8%2Ce1e9a449e352cddf%2Cf7ee613a0b936267%2C5d38f2cbda130702&order=hid&v=dev&q=update_time-ge&q=deleted&q=purged&qv=2017-08-24T15%3A16%3A10.000Z&qv=False&qv=False HTTP/1.1" 200 - "https://xxxx/?job_id=7f435cc3e3baa764&__identifer=6ulynozokh6y" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
> galaxy.jobs.runners.drmaa DEBUG 2017-08-24 17:16:16,209 (2284/74594.universe) state change: job finished normally
> galaxy.model.metadata DEBUG 2017-08-24 17:16:16,424 setting metadata externally failed for HistoryDatasetAssociation 2859: 'invalidated'
> galaxy.jobs.runners ERROR 2017-08-24 17:16:16,521 (2284/74594.universe) Job wrapper finish method failed
> Traceback (most recent call last):
>   File "/softs/bioinfo/galaxy-prod/lib/galaxy/jobs/runners/__init__.py", line 630, in finish_job
>     job_state.job_wrapper.finish( stdout, stderr, exit_code )
>   File "/softs/bioinfo/galaxy-prod/lib/galaxy/jobs/__init__.py", line 1266, in finish
>     dataset.datatype.set_meta( dataset, overwrite=False )
>   File "/softs/bioinfo/galaxy-prod/lib/galaxy/datatypes/binary.py", line 391, in set_meta
>     exit_code = subprocess.call( args=command, stderr=open( stderr_name, 'wb' ) )
>   File "/softs/add-ons/Python-2.7.12/lib/python2.7/subprocess.py", line 523, in call
>     return Popen(*popenargs, **kwargs).wait()
>   File "/softs/add-ons/Python-2.7.12/lib/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/softs/add-ons/Python-2.7.12/lib/python2.7/subprocess.py", line 1343, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

**Comment by FredericBGA** [comment]
Hi,

I tried to relaunch the python script in job_working_directory.
I have activated the .venv, set `PYTHONPATH` to `~/lib`
It works, metadata files are filled. 

> more metadata_results_HistoryDatasetAssociation_2859_y_djCF
> [true, "Metadata has been set successfully"]

The content of the file was previously:

> [false, "'invalidated'"]

So there is something broken but during the run

**Comment by nsoranzo** [comment]
@FredericBGA Please open a new issue, the errors seems to be different.

**Comment by FredericBGA** [comment]
fine, sorry.
