### ISSUE TITLE
Workflow with Collection fails

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#2084]
Creating a workflow:
![78ef465e-f1b0-11e5-91f2-409bbeed9528](https://cloud.githubusercontent.com/assets/2105447/14284634/551e5d5e-fb16-11e5-8faa-10a4520f7b8e.png)

Produces this error when executed:
`File "/Users/guerler/galaxy/lib/galaxy/workflow/run.py", line 82, in __invoke outputs = invoker.invoke() File "/Users/guerler/galaxy/lib/galaxy/workflow/run.py", line 163, in invoke jobs = self._invoke_step( step ) File "/Users/guerler/galaxy/lib/galaxy/workflow/run.py", line 230, in _invoke_step jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step ) File "/Users/guerler/galaxy/lib/galaxy/workflow/modules.py", line 1074, in execute workflow_invocation_uuid=invocation.uuid.hex File "/Users/guerler/galaxy/lib/galaxy/tools/execute.py", line 75, in execute params = param_combinations[0] IndexError: list index out of range`

**Comment by martenson** [comment]
this might be duplicate of https://github.com/galaxyproject/galaxy/issues/2581 (or rather vice versa) and could be already fixed by https://github.com/galaxyproject/galaxy/pull/2634

could you please re-test @guerler ?

**Comment by guerler** [comment]
This works fine for me now. Thanks for the reminder.
