### ISSUE TITLE
renaming workflow gives wrong feedback

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2098]
after hitting enter here:
![screenshot 2016-04-06 10 57 21](https://cloud.githubusercontent.com/assets/1814954/14321231/5eace18a-fbe6-11e5-84f9-98336893b562.png)
I will get this
![screenshot 2016-04-06 10 57 43](https://cloud.githubusercontent.com/assets/1814954/14321240/690d403e-fbe6-11e5-9376-23d58323df20.png)
and after page refresh I see this
![screenshot 2016-04-06 10 58 42](https://cloud.githubusercontent.com/assets/1814954/14321275/8ed38b66-fbe6-11e5-8ced-ef0d8a4a1e3a.png)

**Comment by mvdbeek** [comment]
Can't reproduce this anymore, probably got fixed some time ago
