### ISSUE TITLE
Feature suggestions:  link to tool help from tool output in history

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#2100]
Many times I get questions from users about how to interpret the output from a tool. Often, this information is actually contained in the tool help. However, it's not obvious or intuitive for a user to "rerun" the tool to see information about the output in their history. Having an icon for each history item that is clearly labeled "help" and gave them an easy link to the tool help might be useful.

**Comment by mvdbeek** [comment]
Yes, that is a good idea. And we shouldn't forget users who ran another users workflow.
In that case it's even less obvious.
