### ISSUE TITLE
Mercurial 3.7 breaks cloning repositories.

### ISSUE THREAD

**Issue by davebx** [galaxyproject/galaxy#2103]
To reproduce:
- Create a local toolshed tracking dev
- Create a repository
- Try to install that repository into your local galaxy

I managed to make repositories installable again by rolling back to the 3.4 wheel, but it would obviously be a good thing to make things work for real before the release.

And it took me a while to track this down, because the traceback contains the supremely informative:

```
URL: http://gaius.example.com:8008/repos/test/mummer
Module galaxy.web.framework.middleware.error:151 in __call__
>>  app_iter = self.application(environ, sr_checker)
Module paste.debug.prints:107 in __call__
>>  environ, self.app)
Module paste.wsgilib:547 in intercept_output
>>  if data[0] is None:
IndexError: list index out of range
```

**Comment by martenson** [comment]
I confirmed this behavior on my instance. Weirdly installing from TTS is fine despite it having mercurial 3.7

**Comment by davebx** [comment]
At first glance, I would suspect that the hg middleware might be throwing an error that galaxy's error middleware doesn't know how to handle, hence the profoundly uninformative traceback.

**Comment by davebx** [comment]
With additional additional testing, I've determined that mercurial>=3.6 causes the imperfect behavior, specifically at this changeset: https://selenic.com/repo/hg/rev/7df5d4760873

**Comment by martenson** [comment]
As stated on the PR linked above: 

> Note that the issue in question obviously only occurs when debug is enabled.
