### ISSUE TITLE
Import Data Library Folder as Collection

### ISSUE THREAD

**Issue by ThomasWollmann** [galaxyproject/galaxy#2108]
Wouldn't it be nice to import a library directory directly as collection into the history? Especially when you have a folder with thousands of files it would made possible to handle them in the ui. Currently we need to do it via the API. 

I suggest a checkbox next to the import button labelled with something like "folders to collection". If this is not preferred a modal dialog would also be a solution.

Subfolders could be added as nested collection of course.

**Comment by bgruening** [comment]
Thanks @ThomasWollmann!

**Comment by RJMW** [comment]
:+1:

**Comment by Tomnl** [comment]
Agree, this would be very useful
👍

**Comment by martenson** [comment]
this is now possible thanks to https://github.com/galaxyproject/galaxy/pull/5080
