### ISSUE TITLE
Restore Fetch Taxonomic Representation tool to http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2128]
The tool is used in many Galaxy tutorials and workshops. Many users have been requesting it since it was hidden/removed. Test has the tool still, but the workspace (10 GB) is too small for most to do analysis.

Kraken is the replacement, but genomes are not yet populated on Main. https://github.com/galaxyproject/galaxy/issues/1679

Ping @natefoo @davebx @martenson

**Comment by martenson** [comment]
The only person who can do anything related to tools on Test and Main is @natefoo now

**Comment by jennaj** [comment]
Use Kraken instead. Closing.
