### ISSUE TITLE
clean up after #2093

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2129]
The PR at https://github.com/galaxyproject/galaxy/pull/2093 has some unaddressed comments

from @nsoranzo 

> @davebx sys.path.insert() still need to be updated in many Python files moved in scripts/tool_shed/:
> scripts/tool_shed/check_filesystem_for_empty_tool_dependency_installation_paths.py
> scripts/tool_shed/check_repositories_for_functional_tests.py
> scripts/tool_shed/check_s3_for_empty_tool_dependency_installation_paths.py
> scripts/tool_shed/check_tool_dependency_definition_repositories.py
> scripts/tool_shed/deprecate_repositories_without_metadata.py
> scripts/tool_shed/show_tool_dependency_installation_dir_contents.py

one bug was already addressed by https://github.com/galaxyproject/galaxy/pull/2121 and needs backporting to 16.04 (ping @nturaga)

**Comment by nsoranzo** [comment]
It seems that `scripts/tool_shed/check_repositories_for_functional_tests.py` and `scripts/tool_shed/check_tool_dependency_definition_repositories.py` (and also `install_and_test_tool_shed_repositories.sh`) are broken because `install_and_test_tool_shed_repositories` was removed in commit 962866478a020b3fc794f76f89696ada60881d17 by @jmchilton.

**Comment by jmchilton** [comment]
:cry: sorry about prematurely merging that.

**Comment by nsoranzo** [comment]
@jmchilton @davebx Should we remove also the 3 mentioned files or is there any other solution?

**Comment by jmchilton** [comment]
@nsoranzo I'd say any files related only to install_and_test_tool_shed_repositories should be removed.

**Comment by davebx** [comment]
I'm with @jmchilton. That functionality is unused and unlikely to be restored.

**Comment by martenson** [comment]
Is this done? @nsoranzo @jmchilton

**Comment by nturaga** [comment]
I think @nsoranzo made a PR to remove those files, (https://github.com/galaxyproject/galaxy/pull/2133)

**Comment by martenson** [comment]
yeah, but there were more PRs and more issues; so I would like to get few +1s before closing

**Comment by nsoranzo** [comment]
Can be closed.

**Comment by martenson** [comment]
thanks @nturaga @nsoranzo
