### ISSUE TITLE
Beta Install lists repositories that are not installable

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2132]
the beta interface shows
![screenshot 2016-04-11 15 08 29](https://cloud.githubusercontent.com/assets/1814954/14439068/44a6a126-fff7-11e5-8d75-a24ae29255a6.png)
even when it does not have any revisions

ping @davebx

**Comment by hexylena** [comment]
I guess problems with beta interface have been fixed in past 3 years
