### ISSUE TITLE
Provide a visual UI cue when an account is locked due to pending activation

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2134]
**Situation**

A user creates a new account but does not activate it within 6 hours. Jobs are then on hold and new actions cannot be started. New users may not understand why this is.

**Solution**

Provide UI cues (pop-ups or annotation within grey datasets, or both), or other suitable notifications.

**Suggested by**

[vladimir.gritsenko](https://biostar.usegalaxy.org/u/6788/) via Galaxy Biostars https://biostar.usegalaxy.org/p/16892

**Comment by martenson** [comment]
This feature is present since activation was added, it seems to be broken recently.
ping @guerler

**Comment by jennaj** [comment]
Right - Think I remember a banner being present at one point (?). Be great to have that back. Thanks @martenson  & @guerler !

**Comment by martenson** [comment]
the `page.js` is not getting the needed options to render the box
