### ISSUE TITLE
Saved history error state

### ISSUE THREAD

**Issue by ChristopheH** [galaxyproject/galaxy#2135]
I am running my local instance with the latest release (pull done yesterday) 16.01, with a postgresql DB (UTF8 encoding) on the master branch.
One of my user have this error when trying to go in "saved histories" : 
https://gist.github.com/ChristopheH/ae317a86ee3e0245ff47bf1934196364
and this error when trying to go to "histories shared with me"
https://gist.github.com/ChristopheH/b139f2d2a85d7a1cf84cee2f43c347d6

I already met errors that look like this one, but it was because of special characters in history name. I double checked but I found nothing like this here .. Only one user have this bug.
I hope we can find the reason of this issue.

**Comment by dannon** [comment]
Closed w/ #2138
