### ISSUE TITLE
Problem after Ubuntu upgrade: libmysqlclient error

### ISSUE THREAD

**Issue by philip-holmgren** [galaxyproject/galaxy#2147]
Background: we have our own Galaxy webserver running on Ubuntu10. Galaxy is on a networkshare runnning with Python version 2.6.5 running in a virtual environment. 

Currently: we want to upgrade our Galaxy webserver to Ubuntu 14. I installed python2.6 using apt-get and made a new virtualenv for Galaxy, now 2.6.9. 

Using the run.sh script the virtualenv is started and everything seems to work fine (all packages are downloaded). Opening handler0.log, it shows the following error:

```
Traceback (most recent call last):
  File "/galaxy/galaxy-dist/lib/galaxy/webapps/galaxy/buildapp.py", line 63, in paste_app_factory
    app = galaxy.app.UniverseApplication( global_conf=global_conf, **kwargs )
  File "/galaxy/galaxy-dist/lib/galaxy/app.py", line 55, in __init__
    self._configure_models( check_migrate_databases=True, check_migrate_tools=check_migrate_tools, config_file=config_file )
  File "/galaxy/galaxy-dist/lib/galaxy/config.py", line 860, in _configure_models
    create_or_verify_database( db_url, config_file, self.config.database_engine_options, app=self )
  File "/galaxy/galaxy-dist/lib/galaxy/model/migrate/check.py", line 31, in create_or_verify_database
    engine = create_engine( url, **engine_options )
  File "/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 386, in create_engine
    return strategy.create(*args, **kwargs)
  File "/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 75, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 92, in dbapi
    return __import__('MySQLdb')
  File "/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 19, in <module>
    import _mysql
ImportError: libmysqlclient_r.so.16: cannot open shared object file: No such file or directory
```

So, it's looking for what seems to be an outdated libmysql version (libmysqlclient_r.so.16) which is not present on Ubuntu14.

Because I thought this might be related to python2.6, I made a virtualenv with python2.7 and started it up: same problem. Funny thing is that if I install MySQLdb locally with the Ubuntu 14's default pip, I import the package without a problem. 
Leads me to question whether it is related to Galaxy's pip (we use GXPIP_VERSION='8.0.2+gx2'). We 
MySQLdb version being installed is 1.2.5 so that looks good.

Oh yeah: I also installed just about any package you can find with aptitude relating to mysql and python. I think that's the reason why it works locally. But when I try to put it in a virtualenv it downloads it's own package and always lead to the same error. Even tried to upgrade MySQLdb to 1.2.7 but activating virtualenv degrades it back to 1.2.5.

I'm at the point where I might be missing a quite obvious solution right in front of me, so I wonder if someone has any idea how to fix this?

Cheers

**Comment by nsoranzo** [comment]
@colicab Are you on Ubuntu 14.04 or 14.10?

Also, please keep in mind that Galaxy 16.01 is the last release to support Python 2.6, see https://docs.galaxyproject.org/en/master/releases/16.01_announce.html#deprecation-notices

**Comment by philip-holmgren** [comment]
@nsoranzo we're on the latest Ubuntu 14.04.4

I understand Python2.6 might be a problem on it's own. We expect additional problems by upgrading to Python2.7 (some of our own tools) that the main reason we prefer to stick to python2.6 for now.
As I said, I'm also not sure it the problem is going to be fixed with Python2.7. I made a virtualenv with 2.7 an this resulted in the same error.

Also checked out Galaxy version (should be fine then?)
`changeset:   17047:e9926c3b0a23
branch:      stable
tag:         tip
parent:      17045:b3337bd87fe5
parent:      17046:ccabdd21cb20
user:        Nate Coraor <nate@bx.psu.edu>
date:        Wed Feb 24 21:33:32 2016 -0500
summary:     Merge release_16.01 to stable`

**Comment by nsoranzo** [comment]
The `master` branch is supposed to track the latest stable release branch (16.01 at the moment), but usually does not get the latest fixes. I'd advise you to `git checkout release_16.01` instead.

P.S.: this and the Python 2.7 are just general suggestions, may or may not fix your specific problem.

**Comment by hexylena** [comment]
Galaxy has since dropped support for MySQL. If at all possible you can use PostgreSQL which should be much more stable.
