### ISSUE TITLE
Galaxy Main Get Data Biomart link broken

### ISSUE THREAD

**Issue by lynnoyoung** [galaxyproject/galaxy#2148]
Hi,

In Main, if we go to "Get Data" --> BioMart, we get the following error.

Not Found

The requested URL /biomart/martview was not found on this server.

Apache/2.4.18 (Unix) Server at www.biomart.org Port 80

Thank you,
Lynn

**Comment by martenson** [comment]
Seems the moved hosting of the app to http://www.ensembl.org/biomart/martview without telling us, we need to update.
