### ISSUE TITLE
Tophat bug when running a single unpaired fastq query at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2155]
**Issue**

Running Tophat with a single fastq file (unpaired) produces this error.

Not sure if dependency related on Main or a true bug in the wrapper (if the latter, we can move the ticket).

**Details**

```
-----------------------------------------------------------------------------
info url: https://usegalaxy.org/datasets/bbd44e69cb8906b568d1f23956be5cf6/show_params
job id: 12444439 (bbd44e69cb8906b55ad7cc460b5f79df)
tool id: toolshed.g2.bx.psu.edu/repos/devteam/tophat2/tophat2/0.9
tool version: 0.9
job pid or drm id: None
job tool version: None
-----------------------------------------------------------------------------
job command line:
None
-----------------------------------------------------------------------------
job stderr:

-----------------------------------------------------------------------------
job stdout:

-----------------------------------------------------------------------------
job info:
cannot find 'mate_inner_distance' while searching for 'singlePaired.mate_inner_distance'
-----------------------------------------------------------------------------
job traceback:
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 166, in prepare_job
    job_wrapper.prepare()
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 889, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 445, in build
    raise e
NotFound: cannot find 'mate_inner_distance' while searching for 'singlePaired.mate_inner_distance'
```

**Comment by jennaj** [comment]
Fix implimented and passes tests at http://usegalaxy.org

**Comment by ChaoyuanYeh** [comment]
I just installed Tophat2 on my local galaxy server and I ran into the exact same problem. Where can I get updated wrapper? (Is it wrapper issue?)

**Comment by bgruening** [comment]
@ChaoyuanYeh do you have this problem on Galaxy-Main?

**Comment by ChaoyuanYeh** [comment]
On https://usegalaxy.org/  , this is what I had 

>  Unable to run job due to a misconfiguration of the Galaxy job running system.  Please contact a site administrator.

**Comment by jennaj** [comment]
@ChaoyuanYeh - This is a different error at http://usegalaxy.org and a known problem that our administrators are looking into right now. If you would like to send in a bug report from one of your error datasets, you will then receive an email back when the issues have been resolved - in short, letting you know when to re-run failed jobs.

For your local, uninstalling the tool and reinstalling from the Tool Shed should resolve the original problem by capturing the latest wrapper with the updates. See the linked pull requests above for the details of what changed.

**Comment by ChaoyuanYeh** [comment]
@jennaj  I checked the main tool shed and found the version to be the same as what I previously installed ( owener: devteam, revision: 4eb3c3beb9c7, 2015-10-09 ). I reinstalled it anyways, but the problem persists on my local Galaxy. Where eaxctly can I find updated Tophat2 wrapper ? ( Or say, what should I do from the Galaxy admin panel?)

**Comment by nsoranzo** [comment]
@ChaoyuanYeh This should be a Galaxy issue, what release are you using?

**Comment by ChaoyuanYeh** [comment]
@nsoranzo  How do I know which release I'm using ?

**Comment by nsoranzo** [comment]
@ChaoyuanYeh If you cloned the https://github.com/galaxyproject/galaxy/ git repository and never changed branch, you are probably on the `dev` branch. To check, go inside the galaxy repository, then execute:

```
git status
```

and paste the result here.

**Comment by ChaoyuanYeh** [comment]
@nsoranzo   I didn't use git. I downloaded the program in a zip file from the git repository. What I do know is the time that I did this. It was two weeks ago. I suppose you that would tell you what release I downloaded?

**Comment by nsoranzo** [comment]
@ChaoyuanYeh This is not a good way to install Galaxy because you will not be able to update easily. The recommended way to get the latest stable release is:

```
git clone https://github.com/galaxyproject/galaxy/
cd galaxy/
git checkout release_16.01
```

**Comment by ChaoyuanYeh** [comment]
@nsoranzo Thank you! That solved my problem. Tophat2 now runs without a problem.
