### ISSUE TITLE
Histories sidebar does not update if tools were submitted by API

### ISSUE THREAD

**Issue by enuggetry** [galaxyproject/galaxy#2160]
This might be related to #1220 ?

It appears the histories sidebar conditions are driven by polling and apparently once processing is complete it stops polling.  If a tool operation is initiated via API, the  GUI does not get updated.  A manual page refresh is needed for the page to realize there are active operations.

Is there a way to get it to continuously poll?

This might be better implemented with a sub/pub framework.

**Comment by carlfeberhard** [comment]
Heya!

> Is there a way to get it to continuously poll?

Can you provide a bit more context on what you're trying to do? Are you calling the API from something like jbrowse (inside/outside galaxy)?

> This might be better implemented with a sub/pub framework.

Can you explain how you meant this? Do you mean server-side events or websockets?

(Only tangentially related to 1220 unfortunately)

**Comment by enuggetry** [comment]
Hi,
Sure.  I'm creating a server application for jbrowse that submits blast searches (megablast) to galaxy using galaxy rest APIs.  My server application sits side-by-side with galaxy and submits rest requests to galaxy.  It all functions rather nicely, but I noted the GUI does not reflect API job submissions by itself.

Yes, I was referring to websockets for faye, for example, to let the client know about updates without polling.  The client could subscribe to update notifications.  Just a thought since I noticed a the polling going on.  But once the polling stops, it doesn't seem to start up by itself.

In my own app, I use sails sub/pub framework (websockets based) to notify jbrowse clients of any state changes.

Just a thought.
Thanks for the timely response.
Eric

**Comment by hexylena** [comment]
Probably will be fixed in https://github.com/galaxyproject/galaxy/pull/8441, closing in advance.
