### ISSUE TITLE
non shared virtualenv and ssh runner

### ISSUE THREAD

**Issue by ThomasWollmann** [galaxyproject/galaxy#2170]
When using the ssh runner (cli.py) to submit a job to a pbs cluster and the virtualenv is not shared with the target machine the metadata can't be calculated. Since disabling metadata calculation causes troubles #2163 #1894 it is not a stable option.

**Comment by hexylena** [comment]
The common solution to this is to distribute the virtualenv to the remote machines, either with `rsync`, or using ansible to build the venv in both locations.
