### ISSUE TITLE
Steps after a subworkflows that output collections aren't queued

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#2179]
I created a workflow that took two collections, ran a subworkflow on them both, and then ran a tool (DESeq2) that consumed the output collections from the subworkflows. However, when I run that workflow, only the subworkflows run, the final tool (DESeq2) never gets queued.

**Comment by lparsons** [comment]
~~I'm also running into a similar issue with a workflow that first runs [`fastx_barcode_splitter_enhanced`](https://toolshed.g2.bx.psu.edu/view/lparsons/fastx_barcode_splitter_enhanced/0fb7e9130a70) followed by some other tools. `fastx_barcode_splitter_enhanced` uses a `discover_datasets` call to generate a collection list. However, the downstream tools never get queued (there are no boxes in the history for them) and thus are never run.~~

Nevermind, just the issue with subworkflows that produce collections.

**Comment by gregvonkuster** [comment]
+1 on getting a fix for this.  I am seeing a similar issue with a workflow that includes the fimo tool here https://github.com/galaxyproject/tools-iuc/blob/master/tools/meme/fimo.xml that outputs both a collection and a single output.  These outputs are used as the inputs to a following tool.  No sub-workflows are involved.  The fimo tool produces the collection just fine, but no following tools are executed.

**Comment by MoHeydarian** [comment]
I am also seeing this issue. Like @lparsons described, jobs that link from a sub-workflow aren't executed.

**Comment by jmchilton** [comment]
Thanks for the reports. I'd have to review the individual tools but I suspect that if #5013 didn't fix this problem, #5145 will. Both hopefully will be included in 18.01. If there are still problems after that is branched - I'd recommend reviewing logs and sending stack traces - but I think this will be fixed.

**Comment by mvdbeek** [comment]
Feel free to re-open or preferably open a new issue if this is still an issue.
