### ISSUE TITLE
MAF tools have a dependency issue at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2187]
**Error**

> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/tools/maf/interval2maf.py", line 142, in <module>
>     **main**()
>   File "/cvmfs/main.galaxyproject.org/galaxy/tools/maf/interval2maf.py", line 112, in **main**
>     for block in index.get_as_iterator( src, region.start, region.end ):
>   File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/bx/interval_index_file.py", line 167, in get_as_iterator
>     for block, index, offset in self.get_as_iterator_with_index_and_offset( src, start, end ):
>   File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/bx/interval_index_file.py", line 171, in get_as_iterator_with_index_and_offset
>     for block, idx, offset in index.get_as_iterator_with_index_and_offset( src, start, end ):
>   File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/bx/interval_index_file.py", line 249, in get_as_iterator_with_index_and_offset
>     yield self.get_at_offset( val ), self, val
>   File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/bx/interval_index_file.py", line 254, in get_at_offset
>     return self.read_at_current_offset( self.f, *_self.data_kwargs )
>   File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/bx/align/maf.py", line 37, in read_at_current_offset
>     return read_next_maf( file, *_kwargs )
>   File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/bx/align/maf.py", line 136, in read_next_maf
>     line = readline( file, skip_blank=True )
>   File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/bx/align/maf.py", line 201, in readline
>     line = file.readline()
>   File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/bx/misc/seeklzop.py", line 117, in readline
>     self.fix_dirty()
>   File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/bx/misc/seeklzop.py", line 77, in fix_dirty
>     self.current_block = StringIO( self.load_block( chunk ) )
>   File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/site-packages/bx/misc/seeklzop.py", line 69, in load_block
>     value = lzo.decompress( data )
> NameError: global name 'lzo' is not defined

Reported by

[ana16](https://biostar.usegalaxy.org/u/8561/) at https://biostar.usegalaxy.org/p/17067/

**Comment by jennaj** [comment]
@natefoo @davebx This is still a problem. Is it that the MAF indexes cannot be found by these tools?

**Comment by natefoo** [comment]
@jennaj Could you try it now please?

**Comment by jennaj** [comment]
@natefoo working now for both native indexes and those from the history. Thanks!

**Comment by natefoo** [comment]
For the record, in the unlikely event that anyone has the same problems (you would have to explicitly manually create lzo-compressed and indexed MAFs), the fix is to install Python-LZO into the job virtualenv.
