### ISSUE TITLE
Incorrect handling of non-user-specified Parameters in Tools

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#2200]
Parameter handling logic for parameters that are not specified by a user/client does not occur. 

This includes the use of `<request_param_translation>`, `<hidden>` parameters, and perhaps other cases.

Example 1: 
For example, the UCSC Table browser Tool: https://usegalaxy.org/?tool_id=ucsc_table_direct1 (`/tools/data_source/ucsc_tablebrowser.xml`)
Click execute. Preparing job fails due to missing parameter: `Error executing tool: cannot find 'organism'`. 

However, this tool contains `<request_param_translation>` that should handle setting the `organism` parameter to `"unknown species"` previous to executing.

Example 2: 
GenomeSpace importer: http://usegalaxy.org/tool_runner?tool_id=genomespace_importer (`/tools/genomespace/genomespace_importer.xml`)
When loading just `http://usegalaxy.org/tool_runner?tool_id=genomespace_importer`, the tool runs and throws an error about not being able to split on None, because the `URL` parameter hasn't been provided.
When loading with an empty URL `http://usegalaxy.org/tool_runner?tool_id=genomespace_importer&URL=`, an empty string is passed (expected behavior in both cases), and gives a different error `ValueError: unknown url type:` due to an empty string not having a protocol.

You can see these differences (e.g. via show dataset info) by the fact that the URL parameter is not saved when not set `URL    not used (parameter was added after this job was run)`, vs when the URL is provided `URL`(empty string).

For additional ways to test this behavior, you can make these modifications:

```
diff --git a/tools/genomespace/genomespace_importer.xml b/tools/genomespace/genomespace_importer.xml
index ab77dd7..f0fe7d1 100644
--- a/tools/genomespace/genomespace_importer.xml
+++ b/tools/genomespace/genomespace_importer.xml
@@ -11,10 +11,13 @@
         --token "${token}"
         --json_parameter_file "${output_file1}"
         --genomespace_toolname="\${GENOMESPACE_TOOLNAME:-Galaxy}"
+        "$URL"
     </command>
     <inputs check_values="False">
         <!-- <param name="file_name" type="text" value="" /> -->
-        <param name="URL" type="hidden" value="" />
+        <param name="URL" type="hidden" value="">
+            <validator type="empty_field" message="You must provide a URL to this tool."/>
+        </param>
     </inputs>
     <outputs>
         <data format="auto" name="output_file1" />
```

**Comment by guerler** [comment]
In the second case `display_interface` and `check_values` are set to `False`. The latter seems to be in conflict with the requested parameter validation. I will look again into this later today.

**Comment by blankenberg** [comment]
The parameter validation isn't the problem in this case, and is more-or-less working when URL has been provided (empty or not). When URL isn't provided, the validator is still being called, but it is getting a value of `None`, which passes the validation check on `value ==`''`. This validator should only ever be getting a string. (I did test with type as string, vs the hidden field to same effect.) 

The point about `check_values` and `<validator>` is a good one. Right now, in this case it is doing validation against `None`, (via a `dict.get( name, None )` ), but then not including the value that was validated in the param dict.

**Comment by guerler** [comment]
In some cases there is no `URL` parameter, but the `BASE_URL` contains: `runtool_btn=Execute`: https://github.com/galaxyproject/galaxy/blob/dev/tools/genomespace/genomespace_file_browser_prod.xml#L7. In other cases there is a `URL` parameter set to `value=''`: https://github.com/galaxyproject/galaxy/blob/dev/tools/genomespace/genomespace_importer.xml#L17. Another variation is that the `URL` parameter is missing but added through `request_param`:
https://github.com/galaxyproject/galaxy/blob/dev/tools/data_source/biomart.xml#L18. Yet, in other cases the `URL` parameter is entirely missing: https://github.com/galaxyproject/galaxy/blob/dev/tools/data_source/zebrafishmine.xml. This makes it challenging to come up with a consistent validation mechanism using the shared api endpoint, so I suggest to re-introduce the handling only for the `tool_runner` controller endpoint: #2208.

**Comment by martenson** [comment]
This is an issue, [16.04] tag applies to PRs only to make the target branch more visible, removing.

Also unless it is a release blocking issue it should not have 16.04 milestone specified.

**Comment by martenson** [comment]
The resolution of this issue did not make it to 16.04 so I am pushing it to 16.07
