### ISSUE TITLE
Summary Statistics fails for missing rpy dependency at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2210]
**Error**

> ---
> 
> info url: https://usegalaxy.org/datasets/XX/show_params
> job id: XX (XX)
> tool id: Summary_Statistics1
> tool version: 1.1.0
> job pid or drm id: XX.roundup
> ## job tool version:
> 
> job command line:
> ## python /cvmfs/main.galaxyproject.org/galaxy/tools/stats/gsummary.py /galaxy-repl/main/files/XX/dataset_15316209.dat /galaxy-repl/main/files/XX "c5"
> 
> job stderr:
> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/tools/stats/gsummary.py", line 10, in <module>
>     from rpy import BASIC_CONVERSION, NO_CONVERSION, r, RException, set_default_mode
> ImportError: No module named rpy

**Comment by jennaj** [comment]
Error now produced: 

> job stderr:
> Error in dyn.load(file, DLLpath = DLLpath, ...) :
>   unable to load shared library '/galaxy/software/linux2.6-x86_64/pkg/r-2.11.0_g2main/lib64/R/library/stats/libs/stats.so':
>   libf77blas.so.3gf: cannot open shared object file: No such file or directory
> During startup - Warning message:
> package stats in options("defaultPackages") was not found
> Computation resulted in the following error: Error in function (x)  : could not find function "sd"

ping @natefoo @davebx

**Comment by natefoo** [comment]
Is this fixed now?

**Comment by jennaj** [comment]
@natefoo Yes, testing with multiple example histories passes. Thanks!!
