### ISSUE TITLE
Tool UI - When editing a Text input, the cursor jumps to the end of the line after a single character is typed.

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#2217]
- Fill out a text field in a tool.
- Move cursor to someplace inside the text.
- Start typing.
- Cursor jumps to end of line along with the rest of your input.

**Comment by blankenberg** [comment]
Makes writing regex interesting if you like to do grouping by writing the `(` and `)` first and then fill in, for example.

**Comment by guerler** [comment]
Thanks for reporting this @blankenberg.

**Comment by hexylena** [comment]
:+1:, here too.

**Comment by blankenberg** [comment]
Thanks!
