### ISSUE TITLE
How to get username in galaxy tool?

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#2221]
I want to dynamically generate a pdf from a tool in galaxy (knitr) and I'd like to pass the user's name to my script. Is there a cheetah variable for the executing user's name?

**Comment by mvdbeek** [comment]
I don't know if user name is available, but the email address is with

```
$__user_email__
```

I guess it wold be nice to have the public name as well ...

**Comment by dannon** [comment]
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/model/__init__.py#L271 is used in tool evaluation to template in these extra user variables and should offer what you're looking for.
