### ISSUE TITLE
MACS2 2.1.1.20160309.0 has dependency issue at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2226]
**Be sure to see the latest status below for current tool issues/version**

Few tools involved, same error (macs2 not found). These have been identified, testing for rest WIP @jennaj

Have dep issue:
 - [x] toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_bdgdiff/2.1.1.20160309.0
 - [x] toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_bdgbroadcall/2.1.1.20160309.0

Passed testing:
 - [x] toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_predictd/2.1.1.20160309.0

----
**Original Issue**

All output options (Unique regions in condition 1, Unique regions in condition 2, Common regions in both conditions) produce empty green successful datasets under a variety of parameters and input test sets. _The empty data result does not appear to be content related based on form filter criteria._

**Version**

toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_bdgdiff/2.1.0.20151222.0

**Tested at**

Galaxy Main http://usegalaxy.org

**Note**

Checking dependencies on Main seems like a good first pass check, so reporting here first. Move issue to the tool repo if is later determined to be a wrapper problem. One test run produced an empty green output file with "queued" in the info field (?).

**Reported at**

Galaxy Biostars by a few users plus independently tested https://biostar.usegalaxy.org/p/15781/

**Comment by jennaj** [comment]
@galaxyproject/guac Update - tested MACS2 line command on some example inputs that produced emtpy outputs on Galaxy Main .. and it produces results that way. Tested using same command line as Galaxy uses with Conda MACS2 packages for both conda-available versions: 2.1.0.20150420 and 2.1.1.20160309. The wrapped tool uses version 2.1.0.20151222 (not conda).

This makes me think there is a dependency problem.. agree?

**Comment by natefoo** [comment]
According to Galaxy, the tool dependencies are all properly installed, but if you can send me a job id or share a history I can check the jobs directly and see if I can figure anything else out about why it failed.

**Comment by jennaj** [comment]
Apologies for taking so long to get back. I both shared a history direct (bx account) and forwarded a bug report that shows the problem in detail. It makes use of user data, so cannot be shared publically.

**Comment by jennaj** [comment]
@nate: Update, the latest version fails for not finding the tool at all when tested at http://usegalaxy.org

Tool/version
```
MACS2 bdgdiff Differential peak detection based on paired four bedgraph files (Galaxy Version 2.1.1.20160309.0)
```

Job Information
```
Galaxy Tool ID:	toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_bdgdiff/2.1.1.20160309.0
Galaxy Tool Version:	2.1.1.20160309.0
Tool Version:	/galaxy-repl/main/jobdir/015/568/15568063/tool_script.sh: line 9: macs2: command not found
```

Error
```
Dataset generation errors
Dataset 245: MACS2 bdgdiff on data 231, data 225, and others (Common)

Tool execution generated the following error message:
Fatal error: Exit code 127 ()
/galaxy-repl/main/jobdir/X/X/X/tool_script.sh: line 9: macs2: command not found
```
cc @davebx @nekrut

**Comment by jennaj** [comment]
Same error for this macs2 tool (updated version): toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_bdgbroadcall/2.1.1.20160309.0

**Comment by jennaj** [comment]
Update: Tools still have dependency issues (macs not found, same as above). Tx!

**Comment by jennaj** [comment]
@davebx The prior macs tools with problems now pass testing on a few prior reported full size datasets. Closing out. Thank you!!

**Comment by dktanwar** [comment]
I am facing similar problem
 

Galaxy Tool ID: | toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_callpeak/2.1.1.20160309.0
-- | --
Galaxy Tool Version: | 2.1.1.20160309.0
Tool Version: | /export/galaxy-central/database/job_working_directory/000/251/tool_script.sh: line 25: macs2: command not found

**Comment by natefoo** [comment]
@dktanwar check the MACS tool dependencies under "Manage Tool Dependencies" in your Admin panel.

**Comment by dktanwar** [comment]
There were no dependencies missing for MACS2


Packages which had missing dependencies, I have installed them now and restarted the galaxy. I am still getting same error

MACS2 bdgcmp, MACS2 randsample, MACS2 refinepeak, MACS2 bdgpeakcall, MACS2 filterdup, MACS2 predictd, MACS2 callpeak    /export/tool_deps/_conda/envs/__macs2@2.1.1.20160309    macs2   2.1.1.20160309  Conda   True    [http://192.168.99.100:32816/static/june_2007_style/blue/ok_small.png]


On Oct 16, 2017, at 4:17 PM, Nate Coraor <notifications@github.com<mailto:notifications@github.com>> wrote:


@dktanwar<https://github.com/dktanwar> check the MACS tool dependencies under "Manage Tool Dependencies" in your Admin panel.

**Comment by mvdbeek** [comment]
You can activate those environments by hand and check that those binaries are there. If they are not, you can remove the folder for this environment and re-install them.

**Comment by borauyar** [comment]
I get the same error with MACS2 bdgdiff. 

```
Galaxy Tool ID: | toolshed.g2.bx.psu.edu/repos/iuc/macs2/macs2_bdgdiff/2.1.1.20160309.0
Galaxy Tool Version: | 2.1.1.20160309.0
Tool Version: | /data/galaxy/database/job_working_directory/037/37855/tool_script.sh: line 41: macs2: command not found
```

I checked the dependencies of these tools on the admin panel and they all look fine (installed via Conda). 

Interesting thing is that we have two different galaxy servers (one development and one production server) running and I get this error only on the production server.  Same galaxy version (v17.05) is installed on both servers.

**Comment by bgruening** [comment]
@borauyar can you see if you have a __macs2@ environment in your _conda folder? Is this functional from the commandline?

**Comment by borauyar** [comment]
@bgruening yes, I can see it there. `source activate __macs2@2.1.1.20160309` works and I can initiate 'macs2' within the environment.

**Comment by baberlevi** [comment]
I'm currently having this same issue:

> /export/galaxy-central/database/job_working_directory/000/164/tool_script.sh: line 25: macs2: command not found

Is there a known fix or workaround ?

**Comment by natefoo** [comment]
@baberlevi Is your MACS2 dependency installed via Conda? You should be able to check the tool script for the conda environment setup, which would log any errors it encounters while doing so. Additional messages should be present in the Galaxy job handler log, where dependency resolution occurs.
