### ISSUE TITLE
Multiple history view and 'Saved histories' do not work on test

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#2232]
On test galaxy site there is no way to go back to previously generated histories.

**Comment by martenson** [comment]
for multiview:

```
Uncaught Error: Load timeout for modules: libs/backbone,i18n!nls/locale_unnormalized2,i18n,libs/bootstrap-tour
```

for saved histories it is: https://sentry.galaxyproject.org/sentry/test/issues/40077/

**Comment by carlfeberhard** [comment]
Looks like fs problems:

(https://test.galaxyproject.org/workflow)

```
https://test.galaxyproject.org/static/images/silk/add.png Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

(https://test.galaxyproject.org/visualization/list)

```
IOError: [Errno 5] Input/output error: 'templates/webapps/galaxy/visualization/list.mako'
...
fp = open(path, mode)
```

**Comment by natefoo** [comment]
This was a problem with squid on our CVMFS stratum 1 servers - in the case of both, they were not responding. I am looking in to why, but restarting squid seems to have fixed it.

**Comment by martenson** [comment]
@natefoo view_multiple still timeouts
https://test.galaxyproject.org/history/view_multiple

**Comment by natefoo** [comment]
Works for me...

**Comment by dannon** [comment]
Yep, working again for me too.

**Comment by martenson** [comment]
loads for me now too
