### ISSUE TITLE
Rerunning a failed dataset collection element should substitute the failed element

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#2235]
Presently if an element of a dataset collection fails (e.g. for a problem on a cluster node), rerunning it will create a new history dataset outside of the collection. In this way, the collection will remain in a failed state and it won't be possible to use it as input for other tools.

This is a serious problem for large collections with thousands of elements, in which the probability of having a randomly failed job is quite high.

**Comment by chambm** [comment]
+1

**Comment by nsoranzo** [comment]
@jmchilton Should this go on the Roadmap #1928?
