### ISSUE TITLE
Not possible to undelete a deleted dataset collection

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#2237]
If one deletes a dataset collection by mistake, it is not possible to undelete it like for datasets (at least in the UI).

Contained datasets are not affected by the collection deletion, so undeleting shouldn't be complicated.

**Comment by carlfeberhard** [comment]
It's possible:
1.) Click show deleted
2.) Turn on multiselect
3.) Select the deleted collection
4.) Click the 'for all selected' and press 'undelete'

I understand that you were looking for the 'undelete' link in the header of the dataset collection, and I'd agree if we have it for datasets we should have it for collections. I think in the long run, I'd rather get rid of those links, though.

**Comment by nsoranzo** [comment]
@carlfeberhard Thanks for the workaround! Indeed having a consistent way to undelete datasets and collections is important.

When you say that you'd like to get rid of the "Undelete it" link, do you mean that the preferred method to undelete should be the one you explained above? If so, I am not sure this would be a good idea. In my experience, the average users do not discover multiselect by themselves and often forget its existence. Also, while deleting a number of datasets is a common operation, undeleting is usually confined to a single or few selected elements.

**Comment by dannon** [comment]
Closing the issue as it is possible.  I'd guess planning/discussion for other improvements (if any) to be made here should be a separate issue.
