### ISSUE TITLE
HTML data displays as a blank page at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2240]
**Issue**

Click on the "eye" icon to review an html output dataset (FastQC html report, MACS2 callpeak html report) and the result is a new blank middle panel, no content.

**Reported at Galaxy Biostars, confirmed on Main**
- https://biostar.usegalaxy.org/p/17189/
- https://biostar.usegalaxy.org/p/17182/

ping @dannon

**Comment by martenson** [comment]
`GET /datasets/bbd44e69cb8906b59a2e92f0e9cdb21c/display/?preview=True => generated 0 bytes in 370 msecs`

**Comment by dannon** [comment]
@martenson Let me know if you have any particular ideas I can track down.  First hunch was something new with the main configuration, but now I'm looking at the recent sanitize_html changes.

**Comment by dannon** [comment]
@jennaj Can you give me a list of affected tools which output html reports like this?  I've fixed it for fastqc. (underlying issue to dig at still, but it's resolved for main's purposes, that is)

**Comment by martenson** [comment]
@dannon Barcode Splitter is another one I heard about

**Comment by dannon** [comment]
#2263 should resolve this in a more permanent fashion, restoring functionality to how it was before.  

The whitelist exceptions I added for these tools, though, might should probably stay.  The reports look _way_ nicer for fastqc for example.  We just need to make sure they're super safe.

**Comment by martenson** [comment]
The outside links in the unsanitized fastqc will yield errors as they usually go to non https urls (e.g. on Main). :/

**Comment by dannon** [comment]
@martenson Cool.  We can work on the pretty whitelisted display in a different issue, but #2266 should fix the root issue here and we can remove the whitelisting for tools that it's not wanted (or where it exhibits this problem) and work on that next.

**Comment by dannon** [comment]
@jennaj Should be resolved now, #2266 has been applied to main.
