### ISSUE TITLE
Architecture Documentation (Sphinx + Slides)

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#2244]
@remimarenco and I are going to make sure that Galaxy has great architecture documentation and a set of slides that lives with the code before [our workshop at the GCC 2016](https://gcc16.sched.org/event/5VsE/galaxy-architecture). Ideally, the documentation and slides can draw on the same text sources - sources that can be updated along with the code in PRs as Galaxy evolves.
- [ ] Extend the in-code Galaxy documentation to allow Markdown (see https://github.com/galaxyproject/planemo/commit/069e7ba58ec15f276d9310a8c103d4c90d4e7925).
- [ ] Convert the GCC 2015 talk to Markdown slides using Remark (see https://github.com/galaxyproject/planemo/commit/069e7ba58ec15f276d9310a8c103d4c90d4e7925) and include in the documentation.
- [ ] Convert the wiki page to a Markdown page that prefixes the slides in the documentation - https://wiki.galaxyproject.org/Develop/Architecture. Duplicated information should be smoothed over and both documents should feel natural.
- [ ] Replace the wiki page with a link to the documentation once the code has been updated.
- [ ] Extend Galaxy with a new linter for docstrings using [Pep257](http://pep257.readthedocs.org/en/latest/error_codes.html). Start with a whitelist and by only checking D100 (all public modules must have a docstring).
- [ ] Expand whitelist to include all of Galaxy - all modules should a docstring at least by the GCC.
- [ ] Ensure the slides include documentation on all top-level modules in Galaxy and select relevant sub-modules.
- [ ] Extend slides to include updated 2016 information on the front-end of Galaxy as well - how to build, what the key-top level modules are, etc....
- [ ] Ensure slides contain updated 2016 information on a top-level view of the whole Galaxy ecosystem - covering starforge, the tool shed, pulsar, planemo, etc....
- [ ] Ensure documentation contains detailed code-level documentation on the major God-objects in Galaxy as well as at least one slide for each - including:
  - [ ] `app`
  - [ ] `trans`
  - [ ] `config`
- [ ] Ensure information related to contributing to Galaxy is linked into the documentation in some form.
- [ ] Ensure documentation and at least one slide exists for each major extension point of Galaxy.
  - [ ] Controllers
  - [ ] Job runner.
  - [ ] Job destination.
  - [ ] Dependency resolver
  - [ ] Tools

Stretch Goals:
- [ ] Extend Galaxy with a new linter for import order using [flake8-import-order](https://github.com/public/flake8-import-order). Start with a whitelist and by only checking I100 and I101 - this will ensure that Galaxy's Python code doesn't have circular imports - a key facet of backend design. 
- [ ] Expand whitelist to include all of Galaxy.

After the GCC:
- [ ] Create a new issue outlining the increased usage of PEP-257 to constantly improve Galaxy's in-code documentation. Determine through discussion what to whitelist and what to check. 
- [ ] Create a new issue outlining the increased usage of the import order linter to constantly improve Galaxy's backend design. Determine through discussion what to whitelist and what to check.

**Comment by hexylena** [comment]
> contains detailed code-level documentation on the major God-objects in Galaxy 

:heart: :100:

**Comment by souravsingh** [comment]
I would like to work on the docstrings linter. How do I start?

**Comment by souravsingh** [comment]
@jmchilton I would like to work on the PEP-257 issue. How do I start?

**Comment by martenson** [comment]
@jmchilton @remimarenco could you please update the state of this issue? E.g. what is left to be done and how to approach it. Alternatively please remove the hacktoberfest tag.

**Comment by jmchilton** [comment]
Something is core - I'll update it sometime before the GCC to be a lot nicer.
