### ISSUE TITLE
Conda versioning for samtools not working

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#2247]
I guess this is due to galaxy's internal use of samtools for generating the .bai file.
I can see samtools at the right version (0.1.19) getting linked into the environment, but right at the end I get `__package_samtools@__unversioned__` which installs the latest version of samtools.
Manually deleting `__package_samtools@__unversioned__` and then setting conda_auto_install = false in the galaxy.ini works, but is less than ideal.

Ping @bgruening

**Comment by bgruening** [comment]
This is odd, I haven't seen this on our server. Which tools do you run if you see this?
Galaxy's internal bam handling should be separate from any tool.

**Comment by mvdbeek** [comment]
This is with https://toolshed.g2.bx.psu.edu/view/portiahollyoak/temp/e96a0d0f8dd6, I'll try to reduce this to a minimal tool tomorrow.

**Comment by mvdbeek** [comment]
Ok, so we can also get rid of the unwanted dependency by setting versionless=false in https://github.com/galaxyproject/galaxy/blob/dev/config/dependency_resolvers_conf.xml.sample .
I think the problem is the [iteration of resolvers](https://github.com/galaxyproject/galaxy/blob/b167a741a444c3988447b0d63a1ba3dc5e4e62f5/lib/galaxy/tools/deps/__init__.py#L140-L140) (first exact version, then versionless) and "tools" that don't specify a version.
Logically, I think that if versionless=true, we need to somehow make sure that a dependency chain that includes samtools(versionless) and samtools==0.1.19 accepts 0.1.19 as the versionless version.

**Comment by mvdbeek** [comment]
Adding to this, this only occurs when enable_beta_tool_command_isolation is set to true.
So I guess the dependency resolution already handles everything nicely, but since metadata generation is treated as a new command, it resolves the dependencies again, this time to the latest version of samtools.

**Comment by mvdbeek** [comment]
So there are multiple ways to solve this problem:

1) Replace samtools dependency for metadata jobs with pysam
2) Make sure that unversioned tools can be satisified by already loaded versioned dependency
(A hack is in https://github.com/galaxyproject/galaxy/compare/dev...mvdbeek:hack_metadata_env?expand=1)
3) Create and activate an isolated conda-metadata-env in addition to conda-env

I think option 3 would be the way to go .. thoughts, @bgruening @jmchilton ?

**Comment by nsoranzo** [comment]
Both 1) and 3) sounds good: 1) would free us from many support questions about "samtools not installed" errors, 3) is more general.

**Comment by mvdbeek** [comment]
Yeah, I think we should actually go for option 1 and 3, since that would remove the guesswork for which samtools is actually installed. But that would mean that pysam needs to be installed if metadata is supposed to be generated on the cluster, right?

**Comment by bgruening** [comment]
Aren't Galaxy's wheel available during metadata generation?
Great work Marius!

**Comment by mvdbeek** [comment]
> Aren't Galaxy's wheel available during metadata generation?

I guess that depends on the active python environment in which set_metadata.py is run.
So ideally there would be a virtualenv on the cluster that has galaxylib and pysam.

**Comment by bgruening** [comment]
Agreed and I think/hope this is already in place. Boarding time ...
