### ISSUE TITLE
Two tiered jobs-ready-to-run-query

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#2270]
Job limits are currently implemented in the "job ready to run" loop, where a SQL query returns all of the jobs whose inputs allow them to run. From this query, each job is checked against the number of jobs currently running for that user/session. The user's job counts are cached for each iteration of the loop so that the amount of lookups aren't excessive, but with collections and API job submission, some users may have thousands of jobs "ready" and waiting on limits, which makes one iteration of the readiness loop pretty slow.

A solution to this problem is to add a new "tier" to job states, just as we did with the "paused" state for outputs whose inputs end in the error state. In this case, when we first pull jobs from the database whose inputs are in a state such that they are ready to run, if the concurrency limit checks determine that a job is waiting due to limits, it can be moved to a new state (e.g. `limited`), which will effectively move it to a different "queue". That way these jobs aren't returned by the regular "jobs ready to run" query any more, which should speed that loop up. A second thread/loop would then be responsible for checking limits of `limited` state jobs and running them as limits allow.

One thing off the top of my head to make sure we do when implementing this: Any jobs returned by the regular readiness query will need to be compared against any jobs currently in the `limited` state to ensure that the oldest jobs are run first. One potential way to do this might be to put jobs directly into the `limited` state (instead of `new`) when they are created if the user/session already has > 0 limited jobs.

**Comment by natefoo** [comment]
@dannon I wrote a description, fix if it's missing anything.
