### ISSUE TITLE
Separate out user errors from tool errors?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#2275]
I have some tools which intentionally fail if you have not completed some required training on them (by requiring you to register for the system they talk to). This is not a tool error but a user error.

As a result:
- it shouldn't show up in sentry as a bug
- it might be nice if there was a way to explicitly inform the user "You have done something wrong, not the system, please read the error message"

**Comment by jmchilton** [comment]
Second part is kind of doable with stdio tags write? Can map error codes to specific messages or even craft messages based on regex very crudely. #6685 improves the UI around these also. I guess marking them as user errors and preventing sentry bugs is not yet possible though with this mechanism.

**Comment by hexylena** [comment]
Stdio tags would be sufficient. In the end we reworked the tool
