### ISSUE TITLE
libpq-dev package now required to run Galaxy with postgres (debian)

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#2287]
Updated my Galaxy instance (tried both dev and release_16.04) and it went to update a bunch of wheels. Tried to install a new psycopg wheel, died with an error of unable to build, and message `Error: You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.`

`apt-get install libpq-dev` did fix the problem, but this instance did not have the same problem before the Galaxy update (it has been using wheels for a while now).

ping @natefoo

**Comment by natefoo** [comment]
The dev package shouldn't be necessary, only the postgresql libraries. It sounds like you downloaded the source distribution of psycopg2, not the wheel.
1. Were you using `common_startup.sh` or running `pip` by hand?
2. What OS/distro/arch?

**Comment by martenson** [comment]
@natefoo fyi this was brubeck instance

**Comment by natefoo** [comment]
I figured. Brubeck runs wheezy (Debian 7) and there are psycopg2 wheels built for wheezy, so this should have worked.

**Comment by mvdbeek** [comment]
I guess this has been fixed for a while.
