### ISSUE TITLE
How to export a workflow to the tool shed 

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/galaxy#2297]
Hello, 
It doesn't seem that there exists an easy way to upload a workflow to the tool shed, without writing a tool dependency file by hand. On my galaxy, I have all the tools installed, and I have a workflow which uses some fraction of them, which I've published. It should be easy to generate a public workflow by just making all the tools in the workflow dependencies and specifying how the workflow joins the tools and uploading all this information to the tool shed, but it doesn't seem that's possible. Am I missing something, or is this a feature that should be added? 

@bgruening suggests roughly a year ago that the way of going about this is to write a file by hand: 
http://gmod.827538.n3.nabble.com/Uploading-workflow-to-toolshed-td4046555.html

**Comment by martenson** [comment]
@zfrenchee are all the tools your workflow is using in the Main Tool Shed?

Have a look at https://toolshed.g2.bx.psu.edu/view/bgruening/chemicaltoolbox_library_hole_filling_workflow/c326f1405473

**Comment by alexlenail** [comment]
Hi @martenson 
Yes, all the tools are on the Main Tool Shed. 
It seems like the repository you linked has a big workflow inside, but I suspect @bgruening wrote it by hand. It links to https://toolshed.g2.bx.psu.edu/view/bgruening/chemicaltoolbox/c799c6211cbd which links to each of the repositories for the tool. My point is that there should be a way to do this automatically from within galaxy. Don't you think? Is there a way, and I'm not seeing it?

**Comment by bgruening** [comment]
@zfrenchee I guess this would fit perfectly in planemo. A subcommand that creates this tool_dependencies.xml given a *.ga file.
But maybe it's not worth the effort as tool_dependencies.xml will be deprecated soon in favour of other dependency resolution systems.

**Comment by martenson** [comment]
@zfrenchee the workflow was definitely not written by hand, it was exported from a Galaxy. The `repository_dependencies.xml` file was written by hand. You need to list all repositories that your wf depends on in there and you should be good.

**Comment by alexlenail** [comment]
@bgruening where can I find more information about 

> tool_dependencies.xml will be deprecated soon in favour of other dependency resolution systems.

@martenson Right, I have my .ga file, I just wish the dependencies could be automatically exported too. It makes sense, since the information about the dependencies is already there.

What should we do about this issue? I'm happy closing it and writing the dependency file by hand, but I think this feature should be built.

**Comment by bgruening** [comment]
@zfrenchee feel free to contribute such a script to planemo.
Ideally Galaxy will just consume this workflow and knows which tool to install.

No official information yet about the deprecation. It's not deprecated yet and we will discuss this at GCC I guess. Here is one link with more information https://github.com/galaxyproject/tools-iuc/issues/522 and all the other efforts involving conda packages in Galaxy.

**Comment by alexlenail** [comment]
#2702
