### ISSUE TITLE
metadata generation for some gtf files is incorrect

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2298]
it would show `1 line, 717,655 comments` as contents despite no comments present in the file

see https://usegalaxy.org/u/martenson/h/import-gtf for an example

reported at https://biostar.usegalaxy.org/p/17397/

ping @blankenberg 

this affects Main

**Comment by jennaj** [comment]
Think this is resolved now (ghost ticket). Closing. Thanks!
