### ISSUE TITLE
Lint Python Import Order

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#2300]
This is part of xref #2244.

There are currently 4 votes to use flake8-import-order and 3 votes for the "[cryptography](https://github.com/public/flake8-import-order/blob/master/tests/test_cases/complete.py)" style import order and 1 vote for "[smarkets](https://github.com/public/flake8-import-order/blob/master/tests/test_cases/complete_smarkets.py)". These are more specific import order definitions than prescribed by the PEP8 standard.

Any votes against linting in this fashion? Any additional votes on the "style"?

**Comment by hexylena** [comment]
vote for smarkets.

**Comment by remimarenco** [comment]
Smarkets seems good to me too. I like the fact it stays coherent in term of import / from chaining.

**Comment by jmchilton** [comment]
xref original discussion https://github.com/galaxyproject/galaxy/pull/2292

Current Votes:

cryptography: John, Martin (John and Martin don't feel strongly)
smarkets: Dannon, Rémi, Eric, Nicola

**Comment by martenson** [comment]
resolved in https://github.com/galaxyproject/galaxy/pull/2661 (smarkets)
