### ISSUE TITLE
CloudMap: "Hawaiian Variant Mapping with WGS" dependency issue http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2304]
Error:

> Tool execution generated the following error message:
> Error in dyn.load(file, DLLpath = DLLpath, ...) : 
>   unable to load shared library '/galaxy/software/linux2.6-x86_64/pkg/r-2.11.0_g2main/lib64/R/library/stats/libs/stats.so':
>   libf77blas.so.3gf: cannot open shared object file: No such file or directory
> During startup - Warning message:
> package stats in options("defaultPackages") was not found 
> The tool produced the following additional output:
> Error in lines(loess.smooth(x, y, span = 0.1), lwd = 5, col = "red") : 
>   could not find function "loess.smooth"
> 
> There was an error creating the location plot pdf... Please try again

ping @natefoo Some in this group were fixed, but this one still a problem

**Comment by jennaj** [comment]
ping to @gminevich 

Plus please add in related tools and any additional comments that you think will help with fix, deployment, and/or testing on main.

**Comment by gminevich** [comment]
It looks like the R package "stats" is not installed. This affects the following CloudMap tools:

Hawaiian Variant Mapping with WGS data 
Variant Discovery Mapping with WGS data 
EMS Variant Density Mapping 

These tools also require the R "graphics" package.

**Comment by natefoo** [comment]
I believe this is now fixed. Could one of you test it out, please?

**Comment by laherrera2015** [comment]
I am getting an error about my loess span being too small, but that must mean that the tool is working, but my input is bad.

**Comment by jennaj** [comment]
@natefoo testing

**Comment by gminevich** [comment]
Yes, all three CloudMap plotting tools are working. Thank you! 

@laherrera2015 the span error is indeed due to bad input — increase the size of the span.

**Comment by jennaj** [comment]
Agree, all pass on main. Those with persistent errors have other problems (usage, etc).

**Comment by natefoo** [comment]
Great, sorry it took so long!

**Comment by jennaj** [comment]
@gminevich Sorry to bother you - the problem was with the inputs after all! Closing again
