### ISSUE TITLE
Data Libraries "go to parent folder" button sends user back to lib list (blank until server catches up)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2321]
**Issue** clicking on this button sends the view up one level to all libraries if only one level deep https://usegalaxy.org/library/list?#. 

<img width="509" alt="20160505_parent-folder-libraries" src="https://cloud.githubusercontent.com/assets/8999735/15059789/0e9737f8-12da-11e6-8dbd-76586c3bf7dd.png">

**Enhancement** It would be nicer if this returned to the prior viewed page / search results

**Use case** Perform a search to narrow down folders, go into one and examine, want to back out and examine another from that search. Cannot be done - must start over from scratch with another search. The browser "back" button is not an alternative.

**Comment by martenson** [comment]
Libraries resemble folder structure and even the icon is a reference to `cd ..`\- the only reasonable action that the button can do is to go one level up, which is the list of libraries in this case. It is slow in case you are an admin, because you are loading ~300 libraries. 

That needs to be improved (I tried to get rid of outdated libraries but on Main we are basically in a stage where we do not know who owns what library so I will probably do it via https://github.com/galaxyproject/galaxy/issues/2288).

How did you perform search to narrow down folders?

**Comment by jennaj** [comment]
I have been searching by known keywords. Some nesting or consistent use of terms like those below would help people to find data associated with published workflows/histories/tutorials (including vid tutorials). 

In short, the larger goal is to make available example data easier to find. Perhaps even put in a direct link at the top (cached searches?). This was brought up before and is likely in another ticket somewhere, but not sure which.. perhaps implied by current priorities - linked with staging/organizing more example data in libs?

Rough draft of how I would think a user would want to find data below.

By data association:
- test/ing
- train/ing
- sample (might result in cluttered results .. but maybe not if public only)
- tutorial
- example

By data "type" .. (not "datatype") .. are at least a few categories:

One:
- DNA
- RNA
- RNA-seq
- ChIP-seq
- Variant

Another:
- Reference gene/transcript/splice annotation (gtf, gff3)
- SNP, etc (vcf)
- Others?

**Comment by martenson** [comment]
@jennaj There is no searching in folders implemented, so I am still unsure what you mean by searching. Do you mean browser page search?

**Comment by jennaj** [comment]
Yes - the only search available, right? We can chat in slack if you want. Or just leave this for consideration later on.

**Comment by martenson** [comment]
@jennaj I am unclear of what the problems or proposed enhancements are. Please create a new ticket with a narrower scope.

**Comment by jennaj** [comment]
We can just leave it. The goal was to have some way of searching the contents of all public libraries. How that is implemented or even if others think that is useful was the enhancement idea. It is difficult to find datasets now and in the prior data library model keyword searches were possible against library contents. Thanks!
