### ISSUE TITLE
Consider creating a method to simplify Data Libraries default browsing view

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2322]
**Issue** all data libs displayed by default

The list of libraries on http://usegalaxy.org is very long. Many of these are internal projects with restricted access not usable by community users. Unfortunately, many are at the top of the list of libraries by default but also clutter up further down the list. Browsing is tedious. One can search, but perhaps we could simplify the view?

**Simplify view** by creating an option to "hide/unhide" data libraries
1. New library hidden/unhidden metadata attribute that can be assigned upload loading or after. 
2. Add hide/unhide as toggle for any library dir or file, to top of library home list, in a way that it can be used even when the list view has been filtered by a search. 
3. Show how many hidden/unhidden the same way as datasets are at the top of the History panel - active links with counts? 
4. Hide internal restricted libraries by default.
5. Bonus: Have Galaxy "remember" the hidden/unhidden state for a user. Same session or better across sessions (global user preference).
6. Show hidden/hide/unhide is for users. Only admin accounts can permanently hide/unhide a data lib dir or file.

ping @martenson - not sure if on a to-do list already or not. merge if it is. thanks!

**Comment by martenson** [comment]
You see the ~300 libraries only because you are an admin. Normal user sees 49 (3 pages).

related to https://github.com/galaxyproject/galaxy/issues/2288

**Comment by jennaj** [comment]
Ok, I think your ticket covers it (missed it when opened this). Let's close this one. Thanks!
