### ISSUE TITLE
Notification System

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#2324]
Speaking of https://github.com/galaxyproject/galaxy/issues/2323

I would really like to be notified of histories being shared with me. My PI sometimes emails me saying "Didn't you get the history I shared with you?"

**Comment by jennaj** [comment]
@erasche agree, would be very useful!

**Comment by martenson** [comment]
email?

**Comment by hexylena** [comment]
@martenson sure. Email is fine. A toast notification if the user was logged in might also be nice.

If we're really feeling adventurous I'd love a persistent notification system. (Pretend the bottom are Histories / Data Libraries / Workflows instead of their icons)

![](http://realtimetricks.com/wp-content/uploads/2012/10/notifications.gif)

**Comment by martenson** [comment]
I feel adventurous, but we need to fix the stuff we have before adding more... :/

**Comment by hexylena** [comment]
@martenson agreed :) Hence tagged friendliness/intermediate in case community wants to run with it.

**Comment by frederikcoppens** [comment]
notifications could be very useful indeed for all kind of things

**Comment by bgruening** [comment]
A few more use-cases here:

* GDPR/terms updated, please read this and accept our terms ....
* Admins redirect certain users/groups to special hosts/queues (needed for TIaaS)
* certain group has new data in the data library and the admin would like to inform them

**Comment by hexylena** [comment]
Apparently I opened this issue twice. Oops. https://github.com/galaxyproject/galaxy/issues/1023 was the original for a site-wide notification system. At least we know people want this :) I'll close the other one.

**Comment by bgruening** [comment]
More thoughts are also here: https://docs.google.com/document/d/1EA6RBqaWNBYYOYcUSxDoPPNQ4GaGbZCDwWWinLTpQNg

**Comment by mvdbeek** [comment]
This should be doable with a generalization of the history subscription work I'm doing currently.

**Comment by hexylena** [comment]
@bgruening that looks great, that seems about exactly what I had in mind. new table, everything.

**Comment by hexylena** [comment]
From @bgruening's document:


Use-cases:

- Galaxy deployers are changing the terms of use and need to inform all users. Optionally the deployers of Galaxy might want to know who accepts it.
- Cookie policy needs to be agreed on (https://foundation.wikimedia.org/wiki/Cookie_statement).
- We lost data from a single user and want to inform them.
- A user did violate the Terms of use and we need to inform them.
- Downtime or other urgent notifications.
- New dataset was uploaded for you in this data library ...
- TIaaS notifications
- Subscribe to workflow updates

Implementation:

- Database gets a notification table
- Certain users/groups/roles can be assigned to one or more notifications
- Notifications-reactions from the user should be tracked.
- Notifications are in markdown, can contain links
- Notifications should be on-top of everything until a user reacts to them.
- Create notifications:
	- Notifications can be created via the Admin panel and a markdown editor with preview function.
	- API
	- Or an more advanced yaml file

Questions:

- Should this system be that flexible that special people can create notifications for special groups? **Helena says yes, it should.** But all of our stuff should be like that, using the giant RBAC system in galaxy. There should be some privileged roles (notification-creator, impersonator) and those roles can have those privileges.

**Comment by hexylena** [comment]
First steps toward this here: https://github.com/galaxyproject/galaxy/pull/12396 because I really need to get release notes to users.

I'd love to see the above system implemented, I agree with all of Björn's implementation suggestions.

**Comment by davelopez** [comment]
https://github.com/galaxyproject/galaxy/pull/15663 should cover the groundwork for this. Please open new issues with specific improvement suggestions and new extensions :)
