### ISSUE TITLE
Conda resolver issue: _conda/bin/activate: [[: not found

### ISSUE THREAD

**Issue by remimarenco** [galaxyproject/galaxy#2344]
Hi,

I am trying to install locally, on a Galaxy 16.01, a tool ([trfBig on testtoolshed](https://testtoolshed.g2.bx.psu.edu/view/remimarenco/trfbig/3cb9ef4d65d4)) with Conda dependencies. The tool is taking trfBig dependency from [ucsc-trfbig BioConda recipe](https://github.com/bioconda/bioconda-recipes/tree/18694b1f486d64a55587bf71acb0388b635fcb9a/recipes/ucsc-trfbig).

Once I installed the tool, successfully if I follow ToolShed output, I have these kinds of errors when I want to start a trfbig job:

`Tool execution generated the following error message:`

```
Fatal error: Exit code 127 ()
/home/remi/Dev/galaxy_remi/database/job_working_directory/000/54/tool_script.sh: 9: /home/remi/Dev/galaxy_remi/database/job_working_directory/000/54/tool_script.sh: trfBig: not found
```

`The tool produced the following additional output:`

```
/home/remi/Dev/galaxy_remi/database/job_working_directory/000/54/tool_script.sh: 6: /home/remi/Dev/dependency_dir/_conda/bin/activate: [[: not found
/home/remi/Dev/galaxy_remi/database/job_working_directory/000/54/tool_script.sh: 15: /home/remi/Dev/dependency_dir/_conda/bin/activate: [[: not found
/home/remi/Dev/galaxy_remi/database/job_working_directory/000/54/tool_script.sh: 17: /home/remi/Dev/dependency_dir/_conda/bin/activate: [[: not found
Only bash and zsh are supported
/home/remi/Dev/galaxy_remi/database/job_working_directory/000/54/tool_script.sh: 6: /home/remi/Dev/dependency_dir/_conda/bin/activate: [[: not found
/home/remi/Dev/galaxy_remi/database/job_working_directory/000/54/tool_script.sh: 15: /home/remi/Dev/dependency_dir/_conda/bin/activate: [[: not found
/home/remi/Dev/galaxy_remi/database/job_working_directory/000/54/tool_script.sh: 17: /home/remi/Dev/dependency_dir/_conda/bin/activate: [[: not found
Only bash and zsh are supported
/home/remi/Dev/galaxy_remi/database/job_working_directory/000/54/galaxy_54.sh: 6: /home/remi/Dev/dependency_dir/_conda/bin/activate: [[: not found
/home/remi/Dev/galaxy_remi/database/job_working_directory/000/54/galaxy_54.sh: 15: /home/remi/Dev/dependency_dir/_conda/bin/activate: [[: not found
/home/remi/Dev/galaxy_remi/database/job_working_directory/000/54/galaxy_54.sh: 17: /home/remi/Dev/dependency_dir/_conda/bin/activate: [[: not found
```

Do you know why the tool is not working and why I have these outputs about conda virtualenv?

**Comment by bgruening** [comment]
@remimarenco make sure you are using `bash` not `sh`. There is a config in galaxy.ini.

**Comment by remimarenco** [comment]
Hey @bgruening, thanks for chiming in. It seems I am using bash (Ubuntu 14.04):

```
(galaxy_env) remi@remi-VirtualBox:~/Dev/galaxy_remi$ echo $0
/bin/bash
```

**Comment by bgruening** [comment]
@remimarenco not you, but Galaxy :)
Have you changed this: https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.ini.sample#L316

**Comment by remimarenco** [comment]
I checked that too and it is disabled...that's why I thought I should check my shell type ^^

**Comment by bgruening** [comment]
You are using 16.01 so you see `#default_job_shell = /bin/sh` is this correct? Please change it to bash ;)

**Comment by remimarenco** [comment]
Hmmm I have `#default_job_shell = /bin/bash`. But I explicitly activated it to bash now, let's see!

**Comment by remimarenco** [comment]
Ok reinstalled everything on my Virtual Machine and seems fine. Closing as I can't reproduce.
