### ISSUE TITLE
Dataset collection cannot be connected to a tool in workflow editor

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#2347]
Dataset collection cannot be connected to a collection aware tool as shown below:

![screen shot 2016-05-11 at 2 14 48 pm](https://cloud.githubusercontent.com/assets/4291636/15191450/bfd9f652-1782-11e6-9c85-cd358db2ee2f.png)

**Comment by nekrut** [comment]
On a related note this likely leads to a server error when workflow containing collections is extracted from history. A good history to try is  https://usegalaxy.org/u/aun1/h/pnas-2014

**Comment by jmchilton** [comment]
Did you change the type of the collection from `list` to `list:paired` - you need to do that and make sure the form saves - it can be a bit sluggish. 

![screenshot from 2016-05-11 14 22 16](https://cloud.githubusercontent.com/assets/216771/15191741/04388d44-1784-11e6-98db-b003da287dd6.png)

**Comment by nekrut** [comment]
I see!
