### ISSUE TITLE
Conda path too long for placeholders

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#2349]
I tried activating the conda dependency resolver on our galaxy prod server, but I had to disable it because I encountered this kind of error (testing with trinity IUC tool):

`ERROR: placeholder '/root/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placehold_p' too short in: ncurses-5.9-4`

It seems to happen because the jobs conda-env path can be very long if galaxy itself is installed in a long path, for example:
/some-very/long_path/galaxy-dist/database/job_working_directory/032/32135/conda-env/bin/ = 88 chars = too long compared to the 80 chars placeholder

I found a conda issue for it there: https://github.com/conda/conda-build/pull/877

I don't know if there's anything that can be done for it on the galaxy side, but I create this issue just in case someone would encounter the same problem

**Comment by bgruening** [comment]
Can you symlink some `/data/0/database/` patch to your real one and use this in Galaxy?

**Comment by abretaud** [comment]
Hum, yes, but it's not really ideal as I would need to do it on all computing nodes too...

**Comment by bgruening** [comment]
:( I know. I will lobby to fix this in conda. Not sure if we can do much about this in Galaxy.

**Comment by bgruening** [comment]
@abretaud are you using the object-store? You can set the job_working directory to something else then this long path.

**Comment by abretaud** [comment]
Yep, maybe it will be fixed when I'm back from holidays ;)
Never tried the object-store no, I'll have a look at it!

**Comment by lecorguille** [comment]
Is it not due to the conda_prefix path in galaxy.ini?
Because when I set it close to /, it's work well.

For example, a symlink of your tool_deps?

**Comment by jmchilton** [comment]
This bug came up over and over but I think it has been fixed for the most part - if a specific bioconda dependency exhibits this bug the thing to do at this point is just rebuild and reship it with an updated version of conda-build.
