### ISSUE TITLE
Files uploaded via FTP cannot be imported if their name contain Unicode characters

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#2356]
In 16.04 at 013813691ac1d67a432a267c0c596a8efde611fb:

``` pytb
Traceback (most recent call last):
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/upload.py", line 429, in <module>
    __main__()
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/upload.py", line 418, in __main__
    add_file( dataset, registry, json_file, output_path )
  File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/upload.py", line 104, in add_file
    if not os.path.exists( dataset.path ):
  File "/cvmfs/main.galaxyproject.org/venv/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 77: ordinal not in range(128)
```

**Comment by nsoranzo** [comment]
I tried to make `os.file.exists()` raise `UnicodeEncodeError` without success. Is any of the involved servers using a non-UTF8 locale?

**Comment by natefoo** [comment]
Yes, we use `LC_ALL=C` on the job destinations for sorting:

https://github.com/galaxyproject/usegalaxy-playbook/blob/master/templates/galaxy/usegalaxy.org/config/job_conf.xml.j2#L159

**Comment by nsoranzo** [comment]
I think you can use `LC_ALL=C.UTF-8` . That should fix your bug.

**Comment by mvdbeek** [comment]
Closing this, as this code has changed so much. if this is still an issue feel free to reopen.

**Comment by natefoo** [comment]
Thanks for cleaning up @mvdbeek! For completeness, this is no longer happening as of today, but I don't think we ever implemented @nsoranzo's suggestion. I noticed that we dropped `$LC_ALL` from our non-Pulsar destinations, and that was probably not intentional but probably also the reason it's no longer an issue.
