### ISSUE TITLE
slurmstepd warnings cause successful jobs to end in a error state

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#2359]
For some reason, PR #2309 isn't working for me. Just got this error message on a job:

```
slurmstepd: error: Exceeded step memory limit at some point. Step may have been partially swapped out to disk.
```

I did some quick debugging, but didn't see the issue, so for the time being I'm reverting to my patch (which admittedly, doesn't handle Nate's case).

**Comment by natefoo** [comment]
Could it be that the job's terminal state was not "DONE" (i.e. it failed for other reasons)? These messages are only looked for and ignored if the job is not already in error.

**Comment by lparsons** [comment]
Good thought, I just checked though, and according to SLURM, the job
completed normally.

**Comment by nsoranzo** [comment]
@lparsons Can you also check the job state in the Galaxy database?

**Comment by lparsons** [comment]
@nsoranzo Sure, which column in which table would be helpful?

**Comment by nsoranzo** [comment]
@lparsons `state` column in `job` table.

**Comment by lparsons** [comment]
@nsoranzo Finally getting back to this, the `state` in the job table is `error`, the SLURM state is `COMPLETED`. The message in the Galaxy history is:

```
slurmstepd: error: Exceeded step memory limit at some point. Step may have been partially swapped out to disk.
```

**Comment by nsoranzo** [comment]
It seems that the job failed for some other reason, the `Exceeded step memory limit` messages are removed from stderr only if the job final state is `done`.

**Comment by lparsons** [comment]
No, I'm fairly certain that the reason the `state` is `error` is that the `Exceeded step memory limit` message was _not_ removed from stderr. If I use my original patch, I've not seen this issue. 

Currently working on setting up a tool that pushes these message to stderr on purpose to test.

**Comment by lparsons** [comment]
Well, I'm having a hard time reproducing the problem... which is making me suspect that somehow you are right @nsoranzo and there is some _other_ reason that jobs are getting the status set to `error` even though they are successful... It's seems very coincidental, however, that this hasn't happened with my old patch and has occurred twice with the newer code (which has been running for less time).

**Comment by lparsons** [comment]
Looking at the code, it seems that if the jobstate was `FAILED` it should have given me some additional message about why. However, there are additional job states defined in [`drmaa.py`](https://github.com/nsoranzo/galaxy/blob/3005bba5e389c86fccabe129326a1f3a675c6911/lib/galaxy/jobs/runners/drmaa.py#L72) and I suppose it's possible the state was one of those? This is starting to get into realms I'm much less familiar with though.

**Comment by nsoranzo** [comment]
@lparsons What Galaxy release are you on? I've pushed some fixes for SLURM DRMAA mainly in 16.04. Please also use `<param id="internalexception_retries">5</param>` in `config/job_conf.xml` .

**Comment by lparsons** [comment]
@nsoranzo I'm on 16.04. I don't have that parameter set (it seems it's new?). The `job_conf.xml.sample_advanced` file mentions that the various options are explained in detail on the Galaxy wiki, but I can't seem to find those explanations. Closest I can find is: https://wiki.galaxyproject.org/Admin/Config/Performance/Cluster?highlight=%28drmaa%29#DRMAA.

**Comment by nsoranzo** [comment]
@lparsons It's not new, it was documented in commit e1913c1b75bf237afdfaa7d97cd9070a147884f8 and released in 14.02, but it's a bit hidden. It seems @natefoo started to update the docs in https://wiki.galaxyproject.org/nate/Sandbox , but never merged it in https://wiki.galaxyproject.org/Admin/Config/Performance/Cluster

**Comment by lparsons** [comment]
Just ran into this error again. Job was completed successfully (according to SLURM) with a zero exit code. It's a simple concatenate job (of probably large files). I'm going to try some more testing, but I'm not optimistic.

**Comment by nsoranzo** [comment]
@lparsons Are you using `<param id="internalexception_retries">5</param>` in `config/job_conf.xml` as suggested above?

**Comment by lparsons** [comment]
@nsoranzo Yes, I've got it set in `job_conf.xml' like this:

```
    <plugin id="slurm" type="runner" load="galaxy.jobs.runners.slurm:SlurmJobRunner">
        <param id="internalexception_retries">5</param>
    </plugin>
```

I haven't seen the error in a while, so perhaps this helped but did not eliminate it?

**Comment by nsoranzo** [comment]
@lparsons Good, can you grep the Galaxy logs for the SLURM job id and post the relevant lines?

**Comment by lparsons** [comment]
@nsoranzo I'm not sure which logs you're referring to, but neither the galaxy web logs nor the handler logs contain the SLURM job id. It's a production system, so debug is not turned on.

**Comment by lparsons** [comment]
For what it's worth, I am not able to reproduce this by outputting those strings to stderr. I am starting to suspect issues with reading stderr from slurm jobs (we've had lots of issues with NFS latency, etc.) that are somehow causing an issue with this (race condition?). I don't know how else to explain things.

**Comment by nsoranzo** [comment]
@lparsons I'm referring to the handler logs. If you have an updated release_16.04 (after Jun 13), and the problem is the one I suspect, you should see these messages at the warning level: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/runners/drmaa.py#L260

BTW, I run my production system with `log_level = DEBUG` in `config/galaxy.ini`, helps a lot!

**Comment by lparsons** [comment]
Thanks @nsoranzo. I'll update my `log_level` to `DEBUG` and report back if I see this again.

**Comment by natefoo** [comment]
@lparsons, are you still having this issue or should we close it?

**Comment by lparsons** [comment]
Haven't seen it in a while (of course after turning on `DEBUG`). I guess I'll go ahead and close it and revisit it if I see issues again.
