### ISSUE TITLE
Bowtie2 job not running in Galaxy

### ISSUE THREAD

**Issue by sejal1090** [galaxyproject/galaxy#2365]
Whenever I try to run the Bowtie2 on the dataset it just adds in a queue. In the History under the bowtie2 step it is just showing "This job is waiting to run" since the job is add. Its been a day long I have added my job but still bowtie2 have not been executed. Please suggest as what should I do with this situation.

**Comment by jennaj** [comment]
How to ask questions and get support: https://galaxyproject.org/support/#help-resources
