### ISSUE TITLE
Replace paste#http with uwsgi

### ISSUE THREAD

**Issue by jxtx** [galaxyproject/galaxy#2393]
Currently `run.sh` calls paster.py, which reads the main ini file and in turn launches paste#http. Most Galaxy instances do not change this, and just add a proxy server (e.g. uwsgi) in front. Instances that choose to replace paste#http with another wsgi server often use uwsgi (e.g. galaxy main).

uwsgi is a much more powerful and flexible solution than paste#http. It allows for multiple concurrency modes and allows for advanced routing and rewriting of requests before they reach the wsgi app (see #2385), and could allow multiple concurrency modes (e.g. endpoints that do websockets or talk directly to message queues).

Steps:
- [x] build and test uwsgi wheel
- [x] modify run.sh to call uwsgi from .venv by default

Questions:
- Compatibility with Galaxy run all? Multiple servers are less needed since uwsgi can do multi-process management. But what about job runner processes? Handlers?

**Comment by natefoo** [comment]
Wheels are [here](https://depot.galaxyproject.org/nate/wheelhouse/) but most likely they won't work for you:

``` pytb
(test)nate@weyerbacher% uwsgi --ini-paste config/galaxy.ini
[uWSGI] getting INI configuration from config/galaxy.ini
*** Starting uWSGI 2.0.13.1 (64bit) on [Fri May 27 12:24:18 2016] ***
compiled with version: 4.8.2 20140120 (Red Hat 4.8.2-15) on 27 May 2016 01:12:24
os: Linux-4.2.0-1-amd64 #1 SMP Debian 4.2.1-2 (2015-09-27)
nodename: weyerbacher
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /home/nate/git/tmp
detected binary path: /home/nate/.virtualenvs-stretch/test/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 127910
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:8192 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:41326 (port auto-assigned) fd 3
Python version: 2.7.11 (default, May 26 2016, 18:02:34)  [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
Python main interpreter initialized at 0x1d44170
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 249168 bytes (243 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
Loading paste environment: config:/home/nate/git/tmp/config/galaxy.ini
Traceback (most recent call last):
  File "/home/nate/.virtualenvs-stretch/test/local/lib/python2.7/site-packages/paste/deploy/__init__.py", line 3, in <module>
    from paste.deploy.loadwsgi import *
  File "/home/nate/.virtualenvs-stretch/test/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 8, in <module>
    import pkg_resources
  File "/home/nate/.virtualenvs-stretch/test/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 21, in <module>
    import io
  File "/usr/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: No module named _io
```

The statically linked libpython from the manylinux build image is not compatible with the actual python libs on the installed system. I can generate "platform specific" wheels that'd probably fix this but we just ditched "Galaxy pip" in favor of standard manylinux wheels. Perhaps there is a better solution (can the whole python lib be shipped with uwsgi? Do we even want that?).

**Comment by jxtx** [comment]
This is why I was hoping to get it dynamically linking. I'll look at that
more unless you do first.

**Comment by natefoo** [comment]
I could build manylinux images that don't strip libpythonX.Y.so, but, there's this: https://www.python.org/dev/peps/pep-0513/#libpythonx-y-so-1

**Comment by natefoo** [comment]
uWSGI 2.0.15 has been released, this includes all the components we need to build as a Python extension, meaning we can have uWSGI wheels, meaning we can release 17.05 with `uWSGI==2.0.15` in requirements.txt.

I don't know if we will get the rest of the supporting work done in time (although I think @jmchilton has most of it done already), but I have added this issue to the 17.05 milestone in the hopes that we will.

The wheels have been built in galaxyproject/starforge#118

**Comment by natefoo** [comment]
Work is in #3179

**Comment by natefoo** [comment]
Done #4475 in #5105.
