### ISSUE TITLE
Enhancement: Ability to name collection in a workflow

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#2398]
Add the ability to name a collection that is output from a tool in a workflow. Currently, only datasets can be renamed (and labeled), but not collections.

**Comment by jmchilton** [comment]
This is https://github.com/galaxyproject/galaxy/issues/1680 - you want the postjobaction of "rename" to work on the collection right?

**Comment by lparsons** [comment]
@jmchilton I believe that could work.

I think it's important to come up with a comprehensive plan and making sure all the pieces are in place before rolling out any changes in stable.

For example, right now, the "rename" action using the inputs is the only way I can get files out of Galaxy that have meaningful names. Including the element identifier as a variable would help, but #2140 / #2023 would be even better.If the datasets  in a collection were automatically named as in the above proposals, then I think having the rename work on the collection (instead of each dataset) would make sense and work well.

**Comment by lparsons** [comment]
@jmchilton IMHO, it would be nice to "merge" theses various issues into a single issue with some sub-items. I feel like that might facilitate thinking about the various pieces holistically and clean up a lot of duplicate/related issues.

**Comment by jmchilton** [comment]
This is fixed I think (dup of https://github.com/galaxyproject/galaxy/issues/2398?). Not using the element identifier in renames but the rename operation works on collections now (18.01 or new I believe).

**Comment by lparsons** [comment]
@jmchilton Rename seems pretty broken with collections now (at least for me). It seems to rename BOTH the collection and the individual datasets (which makes no sense). It would seem logical to use the "Label" portion of the postJobAction to name the collection and the rename to rename individual files (though having this be automatic using the element id would be AWESOME).

**Comment by lparsons** [comment]
@jmchilton Rename seems pretty broken with collections now (at least for me). It seems to rename BOTH the collection and the individual datasets (which makes no sense). It would seem logical to use the "Label" portion of the postJobAction to name the collection and the rename to rename individual files (though having this be automatic using the element id would be AWESOME).
