### ISSUE TITLE
depot.galaxyproject.org and wheels.galaxyproject.org are down

### ISSUE THREAD

**Issue by julozi** [galaxyproject/galaxy#2399]
Hi all,

I'm not able to install any tool dependencies hosted on depot.galaxyproject.org. I always get timeout errors.

This problem has been noticed when deploying deeptools suite or diffbind from the Main ToolShed.

Thanks for any help,

Julien

**Comment by julozi** [comment]
wheels.galaxyproject.org is down too...

**Comment by dannon** [comment]
Thanks, we're aware of both and are working on a resolution.

**Comment by bgruening** [comment]
@dannon do you know https://bintray.com. Maybe we can use this to mirror wheels and other critical packages?

**Comment by dannon** [comment]
Hrmm, I don't, though as we're finding out it'd it'd be a good idea to have some sort of redundancy here.   Bintray looks promising, but the pricing is a little unclear.  Are there any download limits on the open source plan?

**Comment by dannon** [comment]
@julozi wheels.galaxyproject.org is back up and running

**Comment by lecorguille** [comment]
Many thanks!

**Comment by julozi** [comment]
Any news about depot.galaxyproject.org ?

**Comment by slegras** [comment]
Still blocked with depot.galaxyproject.org. Right during a french hackathon on Galaxy tool wrapping... That's a pity! :'(

**Comment by raphenya** [comment]
@dannon Thank you.

**Comment by martenson** [comment]
depot is up now, sorry for the inconvenience

**Comment by anastazie** [comment]
Hello, 
depot.galaxyproject.org seems to be down again.
Noticed when trying to install fastq_groomer.

Anastassiya
