### ISSUE TITLE
Suggestion: Setup a Github Organization

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#2400]
Minor issue, but I was wondering if it would be helpful to setup a Galaxy [Github "organization"](https://github.com/blog/674-introducing-organizations). At the very least, this would allow custom routing of notifications based on this organization (helpful for me at least) and possibly has other organizational benefits.

**Comment by dannon** [comment]
@lparsons https://github.com/galaxyproject is configured as an organization unless I misunderstand what you're asking for.

**Comment by lparsons** [comment]
@dannon Apparently, I misunderstood what I was asking for. ;-) Seems one needs to be a "member" of an organization in order to modify notification routing... Sorry. And thanks @jmchilton for inviting me...

**Comment by martenson** [comment]
@lparsons as you are a member of galaxyproject org now please ensure you have a strong GitHub password

**Comment by lparsons** [comment]
@martenson Sure thing, and two-factor auth... ;-)
