### ISSUE TITLE
create dynamic /api docs landing page

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2405]
as jenkins does https://jenkins.galaxyproject.org/api/

it would include the basics of how to programatically access the Galaxy instance

**Comment by carlfeberhard** [comment]
I agree: https://trello.com/c/FFMFtuVT/679-api-overview-at-api

**Comment by hexylena** [comment]
:+1: wanted this forever. Everything in doc should be served.

**Comment by martenson** [comment]
additionally we could pack built docs with Galaxy, so every instance would self-host the docs of its own version (at `/docs` ?)

**Comment by hexylena** [comment]
(was that not what we were talking about? I assume "how to use the API" was part of docs, and if we were including the API how to, we'd just include all the docs)

**Comment by martenson** [comment]
@erasche at first I thought we would just provide one page summary of the available API resources and how to consume them rather than fullblown docs (more beginner oriented)

**Comment by hexylena** [comment]
Let's merge this into https://github.com/galaxyproject/galaxy/issues/3211 I guess we could link to the docs.galaxyproject.org or bioblend samples as well? I think swagger generates really nice documentation for "how to make requests"
