### ISSUE TITLE
datasets shown as (unavailable) in toolform

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2419]
I am trying to run a tool on a bam file but the toolform prefixes the dataset name with `(unavailable)`
![screenshot 2016-05-26 10 33 49](https://cloud.githubusercontent.com/assets/1814954/15578150/5cc80994-232d-11e6-8c3d-4659c7bbf05f.png)

When I try to execute it I will get:
![screenshot 2016-05-26 10 34 47](https://cloud.githubusercontent.com/assets/1814954/15578182/7bb4ca9a-232d-11e6-91ae-f060a4e1ee04.png)

Am I doing something wrong?
This is on Main at https://github.com/galaxyproject/galaxy/commit/5db5e1395880876ac3066fc91397e7cb1618ea62 with Chrome on OSX

**Comment by guerler** [comment]
The dataset is tagged as 'unavailable' if it did not match any of the active datasets in the history (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/parameters/basic.py#L2069). This may happen if one attempts to re-run a tool with datasets which have been deleted after tool execution. Or someone re-runs a tool which was part of a workflow and some of the dependent jobs failed. However, the 'unavailable' tag is for information only, and when executing the job, a regular attempt will be made to access and use the dataset. Can you share the history?

**Comment by martenson** [comment]
@guerler yeah I will, once Galaxy is up (I have only web-01 url now)

**Comment by martenson** [comment]
@guerler https://usegalaxy.org/u/martenson/h/bams

**Comment by hexylena** [comment]
@guerler it also occurs on hidden datasets as of late. That said, I seem to be able to submit jobs OK. Just the new "unavailable" instead of "hidden" label, which might confuse my end users.

997 is being re-run here, which depends on the hidden 996.

![utvalg_857](https://cloud.githubusercontent.com/assets/458683/15580041/a85eee1c-2356-11e6-82ac-d0c46069bf60.png)

**Comment by guerler** [comment]
@erasche yeah i agree that seems to work as its supposed too and we should probably improve the label.

**Comment by guerler** [comment]
After importing the history, clicking on a collapsed/green dataset triggers this error. This might be an unrelated issue tho.
![error](https://cloud.githubusercontent.com/assets/2105447/15581029/d8848354-2338-11e6-8c09-caec24060b70.png)

**Comment by martenson** [comment]
the Job submission failed because of exception error that should be fixed with the PR linked above.

The (unavailable) behavior is caused by the lack of permissions for the datasets (it is a restricted dataset). I was using an admin account so could see/download it but I cannot execute jobs on it. Sam was able to import it and see my history but he couldn't do anything with the dataset. 

The (unavailable) message is shown because toolform automatically preselects the latest matching dataset in the history and checks the permissions afterwards. That also explains why the other two bams were not available to select at all.

Thank @guerler for help with this.

@erasche please open a new issue if you feel like something is wrong with the hiding.
