### ISSUE TITLE
searching for a way to clarify the UX of 'new' state

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2422]
Currently it looks and reads like this:
![screenshot 2016-05-26 13 52 23](https://cloud.githubusercontent.com/assets/1814954/15584563/274f5332-2349-11e6-8ea7-eac50bbf967d.png)

Fueled by the recent JS trouble with jobs being stuck in this state I would like to try come up with a better representation of the state. Users sometimes seem confused whether the state requires their attention and what actually it represents. 

Some ideas:
- We could change the icon from `fa-var-exclamation-circle` to something else (e.g. the `fa-time` that we use for scheduled?) to avoid the "warning - pay attention here" interpretation
- We could rephrase the message from "This is a new dataset and not all of its data are available yet" to something that explains the state clearer. Maybe something like "This is a new dataset and is waiting for being scheduled"? (to be honest I was unsure of the exact meaning of this state until yesterday so please come up with a better alternative)

What do you think @carlfeberhard ?

**Comment by carlfeberhard** [comment]
@martenson Sure. I can change both to whatever you guys want.

**Comment by martenson** [comment]
@carlfeberhard I can change these too, I am more interested in whether you think it can help. :)

**Comment by jxtx** [comment]
I don't understand why this needs to be visually different from the queued state. We can make the text slightly different if we need to be able to know, but from a user perspective the dataset is either waiting or running.

**Comment by martenson** [comment]
@jxtx When I asked this I was told that sometimes the user can interact with this state by making sure the inputs are ready (e.g. when you are hitting concurrency limit you can cancel some other job to make inputs available sooner). I am not convinced there are enough benefits for the presence of this new state though.

**Comment by martenson** [comment]
dupe of https://github.com/galaxyproject/galaxy/issues/4478 - also closing
