### ISSUE TITLE
Jupyter save button does nothing

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#2426]
Saving a Jupyter notebook as a Galaxy history item does not work. Repeated clicking on the green "upload" button does trigger any visible action. And then your contained dies 😢

**Comment by bgruening** [comment]
@nekrut I just tested it. It seems to work for me on usegalaxy.org.
Do you have anything special in your setup? Some special kernel?

**Comment by nekrut** [comment]
Hmmm...I'm using usegalaxy.org as well.

**Comment by bgruening** [comment]
@nekrut you need to reload the history if you click the button.

**Comment by nekrut** [comment]
This looks like an intermittent problem. Closed it for now

**Comment by nekrut** [comment]
It appears age dependent. If a nb is old enough (ah hour or so) it cannot be saved

**Comment by bgruening** [comment]
Copy the code to a text file Anton. I will try to reproduce it on usegalaxy.org.

**Comment by nekrut** [comment]
It only happens when I have a running cell, so I guess it is not a bug. Once no running cells - it saves fine

**Comment by bgruening** [comment]
For me this is working ... was it working for you as well in the end?
