### ISSUE TITLE
Galaxy 16.04 API: associating a dbkey with a dataset when importing from a data library to a history does not update the history item

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#2433]
Using Galaxy version 16.04, the API for importing a data library dataset into a history does not allow for associating a dbkey with the dataset upon import.  This seems to be a new restriction - I believe this was possible with 1 step in 15.10.  

So the process now seems to require 2 API calls:
1. Import the dataset from the data library to the history using this call:
   `gi.histories.upload_dataset_from_library(history_id, dataset_id)`
   The above call will automatically set the following metadata attribute values:
   'genome_build': '?'
   'metadata_dbkey': '?'
2. Update the dataset using this call - I do not understand the reason for having both `metadata_dbkey` and `genome_build parameters`, so I just set both to the same value (e.g., hg19).
   `gi.histories.update_dataset(history_id, dataset_id, metadata_dbkey=dbkey, genome_build=dbkey)`

This 2nd call updates the associated hda metadata values:
'genome_build': 'hg19'
'metadata_dbkey': 'hg19'

However, the "database" label in the history item is not updated, it keeps displaying the default value assigned in step 1, a "?".

Perhaps I am missing something.  Is this possible with a single call in 16.04?

In any case, I think the database label in the history item needs to be updated, and even though the metadata attributes seem to be updated, executing tools that require the dbkey to be set (e.g., bwa) on the datasets produces the following error:

```
Traceback (most recent call last):
  File "/gpfs/cyberstar/p/pughhpc/galaxy-cegr/galaxy/lib/galaxy/jobs/runners/__init__.py", line 166, in prepare_job
    job_wrapper.prepare()
  File "/gpfs/cyberstar/p/pughhpc/galaxy-cegr/galaxy/lib/galaxy/jobs/__init__.py", line 885, in prepare
    tool_evaluator.set_compute_environment( compute_environment, get_special=get_special )
  File "/gpfs/cyberstar/p/pughhpc/galaxy-cegr/galaxy/lib/galaxy/tools/evaluation.py", line 63, in set_compute_environment
    visit_input_values( self.tool.inputs, incoming, validate_inputs )
  File "/gpfs/cyberstar/p/pughhpc/galaxy-cegr/galaxy/lib/galaxy/tools/parameters/__init__.py", line 104, in visit_input_values
    visit_input_values( input.cases[ values[ '__current_case__' ] ].inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload )
  File "/gpfs/cyberstar/p/pughhpc/galaxy-cegr/galaxy/lib/galaxy/tools/parameters/__init__.py", line 110, in visit_input_values
    callback_helper( input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context )
  File "/gpfs/cyberstar/p/pughhpc/galaxy-cegr/galaxy/lib/galaxy/tools/parameters/__init__.py", line 75, in callback_helper
    new_value = callback( **args )
  File "/gpfs/cyberstar/p/pughhpc/galaxy-cegr/galaxy/lib/galaxy/tools/evaluation.py", line 61, in validate_inputs
    value = input.from_json( value, request_context, context )
  File "/gpfs/cyberstar/p/pughhpc/galaxy-cegr/galaxy/lib/galaxy/tools/parameters/basic.py", line 1902, in from_json
    raise ValueError( "History does not include a dataset of the required format / build" )
ValueError: History does not include a dataset of the required format / build
```

**Comment by nsoranzo** [comment]
`gi.histories.upload_dataset_from_library()` should import the dataset with all its metadata, so if you set the dbkey on the _library_ dataset, it should be copied over when the dataset is imported in the history.

**Comment by gregvonkuster** [comment]
Thanks @nsoranzo.  I'm using an automated process that follows this scenario.  I believe this is a fairly standard process for facilities.
1. Get raw datasets produced by a sequencer and imports them into a Galaxy data library
2. Take 1 or 2 of these library datasets defined for a sample and import them to a history, associating them with a dbkey at that time
3. Map the imported dataset with bwa or bwa_mem

In my case I am mapping the same sample library datasets against multiple dbkeys, executing a workflow for each dbkey mapping, so this does not allow me to assign a single dbkey to the dataset within the data library.

**Comment by nsoranzo** [comment]
@gregvonkuster That's fine, I was just pointing out that I think that it is ok to require a second API call to _change_ the dbkey.

Regarding the `gi.histories.update_dataset()` call, you don't need to specify `metadata_dbkey=dbkey`. The API seems to work fine for me, i.e. the `genome_build` attribute is updated correctly as you already find out, and also the 'database' field in the history dataset info UI is.

**Comment by gregvonkuster** [comment]
@nsoranzo Thanks for the help on this!  When you pointed out that the API call worked for you, I looked at my end and found the problem.  The json dicts returned for api calls for datasets from both libraries and histories include both an 'id' entry and a 'dataset_id' entry:

```
'dataset_id': 'ab905c6c78309568', 'file_size': 8151951595, 'file_ext': 'fastqsanger', 'id': 'd6169cfdd98197d3',...
```

The bioblend api methods always use 'dataset_id' in the method signatures:

```
    def update_dataset(self, history_id, dataset_id, **kwds):
        """
        Update history dataset metadata. Some of the attributes that can be
        modified are documented below.

        :type history_id: str
        :param history_id: Encoded history ID

        :type dataset_id: str
        :param dataset_id: Id of the dataset
```

So when upgrading my Galaxy instance from 15.10 (which allowed adding a dataset to a history and setting the dbkey in a single call) to version 16.04 (which forced a 2nd call to the history api's update_dataset() method above), I inadvertently passed the 'dataset_id' entry from the json dict for the dataset rather than the 'id' entry since the update_dataset method does not make this clear.

I am curious about why we now seemingly have 2 attributes for storing the dbkey for datasets (i.e., genome_build and metadata_dbkey), but I'm sure I'll discover that as I continue working with the code.

Thanks a bunch for the help on this!  ;)
