### ISSUE TITLE
How to get tool input/output field details

### ISSUE THREAD

**Issue by i-am-b-soto** [galaxyproject/galaxy#2439]
Hi, we're working on a PHP wrappers of the Galaxy API.  This is so we can natively launch jobs on Galaxy via a PHP app (https://github.com/tripal/GalaxyLib-PHP).  We intend to use this for Tripal (http://tripal.info) so that we can integrate a Galaxy workflow on a Tripal site.   We have a lot of it working but we need information about the input fields for a workflow such as the type of field (e.g. boolean, string) and properties about it (e.g. max length, default values, etc).  We can't seem to find the API function to pull this out.  We can get information about the workflow, it's tools and the input fields, and we can get information about the tools.  But not information about the input field types. Is there an API function to retrieve this info?

Thanks,

**Comment by remimarenco** [comment]
Hi @Iamsoto,

Your project sounds really interesting!

I think @jmchilton could help you on this, but I would strongly suggest to join us on [#galaxy-project](https://wiki.galaxyproject.org/GetInvolved#IRC_Channel) to have more informations, and direct feedback.

See you on it ;)

**Comment by dannon** [comment]
@Iamsoto and I chatted on IRC about this; the pointer he needed was to the `tools/<tool_id>/build` endpoint.
