### ISSUE TITLE
Invoking IE on BAM dataset is complicated

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#2442]
I many cases it may be necessary to poke around BAM files using IE. This cannot be done in a straightforward way at present because clicking on "Visualize" button (a button with bar chart) immediately opens Trackster. For BAM datasets this button should operate in exactly the same way it behaves for other datasets: give user options, one of which should be Jupyter.

**Comment by frederikcoppens** [comment]
+1
