### ISSUE TITLE
unable to change the default number of local_slots on 16.01

### ISSUE THREAD

**Issue by dyusuf** [galaxyproject/galaxy#2448]
Hi guys,

I try to reset local_slots to change the default number, 1. I followed the instruction on  https://wiki.galaxyproject.org/Admin/Config/Performance/Cluster#Local

For the testing purpose, I tried to set the local_slots to 2.

Here is the related gist,
https://gist.github.com/dyusuf/3889f29ccc46ad846d4dbdda9ec41980

The configuration does not work with galaxy 16.01 while I remember it worked before 16.01.

Could you guys help out?

thanks in advance.

**Comment by nsoranzo** [comment]
@dyusuf What do you mean exactly with "the configuration does not work"?
Can you also please add the relevant output or Galaxy log, if any?

**Comment by dyusuf** [comment]
@nsoranzo thanks for the prompt response. sorry for the brevity. 

I run the command Ribotaper.sh that requires number of cores > 1 otherwise the script will exit before the execution. So if the local_slots cab be reset then "\${GALAXY_SLOTS:-12}" should pass value 2 to Ribotaper.sh.

The current configuration seems still passing value 1 to  Ribotaper.sh that throws the error,

  !!!!!   n of cores required >1.

**Comment by nsoranzo** [comment]
@dyusuf I'd suggest to enable job metrics in your Galaxy:
- go to the `config/` directory
- copy `job_metrics_conf.xml.sample` to `job_metrics_conf.xml`
- uncomment `<env />`
- restart Galaxy.

Then, if you launch any tool as an admin user, you can see all the environment variables (including GALAXY_SLOTS) that are defined when the job is run by clicking on the (i) "View details" icon.

**Comment by dyusuf** [comment]
@nsoranzo thanks for the trick to view the environment variables

I figure out the problem is not with galaxy but with planemo which had been unconsciously omitted in my consideration while opening the issue.

To test the tool, I used "planemo test --conda_dependency_resolution" which does not respect the changes in job_cof.xml.

Thanks a lot for the help!

I close the issue now.
