### ISSUE TITLE
Convert BAM to ScIdx fails for dependency issues at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2460]
Fails for dependency problems.

`Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/scratch`

(CleanSam/SortSam run on test cases prior to this tool)

Galaxy Version 1.0.0

toolshed.g2.bx.psu.edu/repos/iuc/bam_to_scidx/bam_to_scidx/1.0.0

ping @gregvonkuster @natefoo 

Hello Martin or Dave, (from Greg, 6/12/16)

> This fix is now available in the MTS (https://toolshed.g2.bx.psu.edu/repository?repository_id=642b78707940da3a&changeset_revision=ebbf2a6a4c55), so can you please schedule an update to Galaxy main when it is convenient?  I’m also wondering if this same issue will affect other Java based ChIP-exo tools on main.  I guess we’ll find out, and if so, I’ll add the fix to them as well.

**Comment by gregvonkuster** [comment]
@jennaj Thanks for this report.  @natefoo says this issue should be fixed with this PR: https://github.com/galaxyproject/tools-iuc/pull/761.  Has main been updated with this fix?

**Comment by martenson** [comment]
MTS is up to date now (the fix wasn't there before) and @natefoo promised he will have a stab at updating Main (it is fairly difficult now due to the change of the file system). Sorry for the inconvenience @gregvonkuster

**Comment by gregvonkuster** [comment]
No Problem - let me know if I can help out with anything.  ;)

**Comment by martenson** [comment]
@gregvonkuster scidx on Main updated

**Comment by gregvonkuster** [comment]
@martenson Thanks!  But it looks like the "fix" didn't fix things.  Its still producing this.

```
Tool execution generated the following error message:
Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/galaxy-repl/main/scratch
```

**Comment by gregvonkuster** [comment]
@natefoo @jennaj @martenson I'm not quite clear on what causes this problems for these Java tools on main.  Does this happen for all Java tools or just these ChIP-exo tools?  If this problem is restricted to the ChIP-exo Java tools, then is there a change in the Java code I can have the author make that will correct this?  I can easily get any changes made to the Java code if that will work.  I just don't know what change is needed.

**Comment by jennaj** [comment]
I'm not sure which are Java-based in the same way as this tool. @natefoo @martenson ?

ps: Thanks Martin for helping is to move forward with this by doing the updated install yesterday!

**Comment by gregvonkuster** [comment]
@natefoo @martenson This issue looks like it has been resolved with the latest update to the tool on main.  At least my tests that I have executed on main have now passed for this tool.

**Comment by martenson** [comment]
@gregvonkuster so the 15Jun update helped then? Or was there some other update I do not know about?

**Comment by gregvonkuster** [comment]
I believe it was the 15Jun update. ;)

**Comment by martenson** [comment]
alright, happy it works! closing then
