### ISSUE TITLE
the history datasets peek shows only first row

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2461]
I think it used to show 5. Discovered when doing Galaxy101 where @nekrut's screenshots have the same datasets with 5 rows in the peek.

![screenshot 2016-06-06 17 11 53](https://cloud.githubusercontent.com/assets/1814954/15838000/e201c390-2c09-11e6-893a-388578f0812a.png)

**Comment by carlfeberhard** [comment]
Not a rendering issue apparently. I think this must've been changed on the back end a while ago (possibly in datatypes). You can still see five rows on your older datasets.

Is this happening with lddas, too?

**Comment by carlfeberhard** [comment]
Definintely a bug, tho:

```
In [6]: hda.peek
Out[6]: u'##gff-version 2\n\n\n\n\n'
```

**Comment by martenson** [comment]
@carlfeberhard I can see long peeks in libraries (https://usegalaxy.org/library/list#folders/F5bee13e9f312df25/datasets/93e786a54eae47db)
![screenshot 2016-06-07 10 35 32](https://cloud.githubusercontent.com/assets/1814954/15861828/960b3588-2c9b-11e6-87f6-21c9f672a417.png)

**Comment by martenson** [comment]
Correction: I can see it in libraries for older datasets, for a new one I see one row only

**Comment by ericenns** [comment]
This was caused by a off by one error in lib/galaxy/datatypes/data.py, where it kept the newline from the previous file and then would truncate the line later on so that it was always 0 length.

**Comment by martenson** [comment]
thanks for fixing this @ericenns !
