### ISSUE TITLE
Bug: Collections in copied histories point to the original datasets, not the copy in the new history

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#2462]
Steps to replicate:
1. Create `History original` with `Collection A` containing `Dataset 1` and `Dataset 2`.
2. Copy `History original` to `History copy`
3. Go to `History copy`, `Collection A`, and edit the attributes of `Dataset 1`. Rename it to `Dataset 1 renamed`.
4. Unhide the datasets in `History copy` and view the name of `Dataset 1`. It will remain `Dataset 1`.
5. Unhide the datasets in `History original` and view the name of `Dataset 1`, it will have been renamed `Dataset 1 renamed`.

**Comment by lparsons** [comment]
I've found another oddity that I think is related to this issue. Essentially, when I copy a collection from History A to History B, I can view the collection from History B, but History B does NOT contain the datasets contained in the collection. In other words, History A has a number of hidden datasets that are part of the collection, but History B does not have those same hidden datasets. This seems like a bug to me, or at least an unintuitive result.

@jmchilton Perhaps this behavior on copying collections is actually by design?

**Comment by lparsons** [comment]
I believe this is being addressed by #1810.

**Comment by jmchilton** [comment]
Sorry for missing this sooner. Yeah - I guess it was by design but the design is not good and needs to be addressed. I'll address this as part of #1810.

**Comment by mvdbeek** [comment]
Pretty sure we've changed this some time ago, and I can't reproduce this anymore. If you copy a collection (as part of copying a history) we copy the datasets as well, so you should only be editing the copy in that case.
