### ISSUE TITLE
Workflow sharing via link is broken. Workflow SVG generation is broken.

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#2465]
Two major issues here:
- Going to a link shown in this image ( https://usegalaxy.org/u/aun1/w/duplex-analysis-from-reads) produces server error.
- Clicking on **Create image** button produces `This XML file does not appear to have any style information associated with it. The document tree is shown below.` where the _document below_ is empty.

![screen shot 2016-06-08 at 7 33 16 am](https://cloud.githubusercontent.com/assets/4291636/15893055/6605a796-2d4b-11e6-89ba-72d0d02bc182.png)

**Comment by martenson** [comment]
@nekrut The WF display is fixed by https://github.com/galaxyproject/galaxy/pull/2473 and https://github.com/galaxyproject/galaxy/pull/2471
The SVG export we will investigate tomorrow

The link is working fine on Main now https://usegalaxy.org/u/aun1/w/duplex-analysis-from-reads

**Comment by mr-c** [comment]
I just ran into this, was hoping to use a workflow graph in my lightning talk :-(

**Comment by martenson** [comment]
@mr-c what galaxy?

**Comment by mr-c** [comment]
@martenson Galaxy Main

**Comment by frederikcoppens** [comment]
@martenson also on the cloud instance we used for the datathon we had the same SVG issue

**Comment by dannon** [comment]
This is actually due to uwsgi.  I'm working on a fix now.

**Comment by dannon** [comment]
Should be fixed in #2628.

**Comment by martenson** [comment]
fixed WF export and deployed on Main, thanks @dannon and others
