### ISSUE TITLE
No Visual Indication of Mapping over a Collection

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#2467]
If I pass a data collection parameter of `collection_type` `paired` - a dataset pair - it will just run one job and produce an output. If I pass it a list of paired datasets - a very different operation occurs - it will map over the inputs and produced outputs collected together. Yet the web UI just lists these options together in the same select box and doesn't provide any indication even after being selected that a very different thing is going to occur.

The distinction should mirror that of datasets IMO (as it used to) - passing a `paired` parameter a `list:paired` input is very much like passing a `data` parameter a `list` input - and the UI should be similar. But even if I'm overruled and there is a desire to stick it all in one drop down - there should be some visual indication somehow made.

What are your thoughts @guerler?

**Comment by jmchilton** [comment]
I just tested 15.10 and there was a small visual indicator after selecting a collection to map over - this is a regression actually.

(Still think it should mirror regular datasets though :wink:.)

**Comment by guerler** [comment]
I am open for suggestions (sketch?) and can definitely help implementing them.

**Comment by jmchilton** [comment]
@guerler Restoring the description that would show up in 15.10 would be a start - I imagine it wasn't removed intentionally.

**Comment by hexylena** [comment]
I think this is fixed?
