### ISSUE TITLE
LEfSE - 'Format Data for LEfSE' issue

### ISSUE THREAD

**Issue by Jamesokis** [galaxyproject/galaxy#2474]
Hi, 
I am getting the following screen after uploading a file onto LEfSe and clicking on the 'Format Data for LEfSe' page. Does anyone know what is going on? I have previously formatted the same file for LEfSe successfully.

Section Links

```
Source
Template
Extra Data
Traceback
```

Hi, I'm source!
Extra Data
CGI Variables
CONTENT_LENGTH  '0'
HTTP_ACCEPT     'text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8'
HTTP_ACCEPT_ENCODING    'gzip, deflate, br'
HTTP_ACCEPT_LANGUAGE    'en-GB,en;q=0.5'
HTTP_CONNECTION     'close'
HTTP_COOKIE     'galaxysession=c6ca0ddb55be603a599c18a3878b5d4a3bf6aa544036331babbcfe448a5f98171c067e705ff34945'
HTTP_HOST   'huttenhower.sph.harvard.edu'
HTTP_REFERER    'https://huttenhower.sph.harvard.edu/galaxy/'
HTTP_USER_AGENT     'Mozilla/5.0 (Windows NT 6.0; rv:47.0) Gecko/20100101 Firefox/47.0'
HTTP_X_REAL_IP  '88.166.253.122'
HTTP_X_SCHEME   'https'
PATH_INFO   '/tool_runner'
QUERY_STRING    'tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fgeorge-weingart%2Flefse%2FLEfSe_for%2F1.0'
REMOTE_ADDR     '88.166.253.122'
REQUEST_METHOD  'GET'
SCRIPT_NAME     '/galaxy'
SERVER_NAME     'huttenhower.sph.harvard.edu'
SERVER_PORT     '8080'
SERVER_PROTOCOL     'HTTP/1.0'
Extra Data
WSGI Variables
application     <paste.recursive.RecursiveMiddleware object at 0x2b8f942a4c10>
is_api_request  False
paste.cookies   (<SimpleCookie: galaxysession='c6ca0ddb55be603a599c18a3878b5d4a3bf6aa544036331babbcfe448a5f98171c067e705ff34945'>, 'galaxysession=c6ca0ddb55be603a599c18a3878b5d4a3bf6aa544036331babbcfe448a5f98171c067e705ff34945')
paste.evalexception     <weberror.evalexception.middleware.EvalException object at 0x2b8f71389410>
paste.evalexception.debug_count     1465230661
paste.expected_exceptions   [<class 'paste.httpexceptions.HTTPException'>]
paste.httpexceptions    <paste.httpexceptions.HTTPExceptionHandler object at 0x2b8f952ba0d0>
paste.httpserver.thread_pool    <paste.httpserver.ThreadPool object at 0x2b8f6bf4de50>
paste.recursive.forward     <paste.recursive.Forwarder from /galaxy>
paste.recursive.include     <paste.recursive.Includer from /galaxy>
paste.recursive.include_app_iter    <paste.recursive.IncluderAppIter from /galaxy>
paste.recursive.script_name     '/galaxy'
paste.throw_errors  True
request_id  '49e972fa2e0311e688e600163e4aedda'
weberror.evalexception  <weberror.evalexception.middleware.EvalException object at 0x2b8f71389410>
weberror.evalexception.debug_count  1465230661
webob._parsed_query_vars    (MultiDict([('tool_id', 'toolshed.g2.bx.psu.edu/repos/george-weingart/lefse/LEfSe_for/1.0')]), 'tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fgeorge-weingart%2Flefse%2FLEfSe_for%2F1.0')
wsgi process    'Multithreaded'

No Template information available.
Error Traceback:
View as:   Interactive (full)  |  Text (full)  |  XML (full)
⇝ IndexError: list index out of range
URL: http://huttenhower.sph.harvard.edu/galaxy/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fgeorge-weingart%2Flefse%2FLEfSe_for%2F1.0
Module weberror.evalexception.middleware:364 in respond         view

> >  app_iter = self.application(environ, detect_start_response)
> > Module paste.recursive:84 in **call**         view
> >  return self.application(environ, start_response)
> > Module paste.httpexceptions:633 in **call**         view
> >  return self.application(environ, start_response)
> > Module galaxy.web.framework.base:132 in **call**         view
> >  return self.handle_request( environ, start_response )
> > Module galaxy.web.framework.base:190 in handle_request         view
> >  body = method( trans, *_kwargs )
> > Module galaxy.webapps.galaxy.controllers.tool_runner:90 in index         view
> >  template, vars = tool.handle_input( trans, params.**dict** )
> > Module galaxy.tools:2116 in handle_input         view
> >  state, state_new = self.**fetch_state( trans, expanded_incoming, history, all_pages=all_pages )
> > Module galaxy.tools:2230 in __fetch_state         view
> >  state = self.new_state( trans, history=history, all_pages=all_pages )
> > Module galaxy.tools:2015 in new_state         view
> >  self.fill_in_new_state( trans, inputs, state.inputs, history=history )
> > Module galaxy.tools:2024 in fill_in_new_state         view
> >  state[ input.name ] = input.get_initial_value( trans, context, history=history )
> > Module galaxy.tools.parameters.grouping:535 in get_initial_value         view
> >  rval[ child_input.name ] = child_input.get_initial_value( trans, child_context, history=history )
> > Module galaxy.tools.parameters.basic:943 in get_initial_value         view
> >  options = list( self.get_options( trans, context ) )
> > Module galaxy.tools.parameters.basic:763 in get_options         view
> >  return eval( self.dynamic_options, self.tool.code_namespace, other_values )
> > Module ?:1 in <module>         view
> > Module ?:41 in get_cols         view
> >  lines = [(red((rc+"#"+str(i+1)+":"+v.split()[0]),max_len),'%d' % (i+1),False) for i,v in enumerate(open(fname))]
> > IndexError: list index out of range
> > URL: http://huttenhower.sph.harvard.edu/galaxy/tool_runner?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fgeorge-weingart%2Flefse%2FLEfSe_for%2F1.0
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/eggs/WebError-0.8a-py2.7.egg/weberror/evalexception/middleware.py', line 364 in respond
> >   app_iter = self.application(environ, detect_start_response)
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/eggs/Paste-1.7.5.1-py2.7.egg/paste/recursive.py', line 84 in __call**
> >   return self.application(environ, start_response)
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/eggs/Paste-1.7.5.1-py2.7.egg/paste/httpexceptions.py', line 633 in **call**
> >   return self.application(environ, start_response)
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/web/framework/base.py', line 132 in **call**
> >   return self.handle_request( environ, start_response )
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/web/framework/base.py', line 190 in handle_request
> >   body = method( trans, *_kwargs )
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/webapps/galaxy/controllers/tool_runner.py', line 90 in index
> >   template, vars = tool.handle_input( trans, params.**dict** )
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/**init**.py', line 2116 in handle_input
> >   state, state_new = self.**fetch_state( trans, expanded_incoming, history, all_pages=all_pages )
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/__init**.py', line 2230 in **fetch_state
> >   state = self.new_state( trans, history=history, all_pages=all_pages )
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/__init**.py', line 2015 in new_state
> >   self.fill_in_new_state( trans, inputs, state.inputs, history=history )
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/**init**.py', line 2024 in fill_in_new_state
> >   state[ input.name ] = input.get_initial_value( trans, context, history=history )
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/parameters/grouping.py', line 535 in get_initial_value
> >   rval[ child_input.name ] = child_input.get_initial_value( trans, child_context, history=history )
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/parameters/basic.py', line 943 in get_initial_value
> >   options = list( self.get_options( trans, context ) )
> > File '/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/parameters/basic.py', line 763 in get_options
> >   return eval( self.dynamic_options, self.tool.code_namespace, other_values )
> > File '<string>', line 1 in <module>
> > File '../shed_tools/toolshed.g2.bx.psu.edu/repos/george-weingart/lefse/db64b6287cd6/lefse/home/ubuntu/lefse_to_export/format_input_selector.py', line 41 in get_cols
> >   lines = [(red((rc+"#"+str(i+1)+":"+v.split()[0]),max_len),'%d' % (i+1),False) for i,v in enumerate(open(fname))]
> > IndexError: list index out of range
> > <?xml version="1.0" ?>
> > <traceback>
> >     <sysinfo>
> >         <language version="2.7.8">Python</language>
> >     </sysinfo>
> >     <stack>
> >         <frame>
> >             <module>weberror.evalexception.middleware</module>
> >             <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/eggs/WebError-0.8a-py2.7.egg/weberror/evalexception/middleware.py</filename>
> >             <line>364</line>
> >             <function>respond</function>
> >             <operation>app_iter = self.application(environ, detect_start_response)</operation>
> >             <operation_context>        try:
> >             **traceback_supplement** = errormiddleware.Supplement, self, environ
> >             app_iter = self.application(environ, detect_start_response)
> >             try:
> >                 return_iter = list(app_iter)
> > </operation_context>
> >         </frame>
> >         <frame>
> >             <module>paste.recursive</module>
> >             <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/eggs/Paste-1.7.5.1-py2.7.egg/paste/recursive.py</filename>
> >             <line>84</line>
> >             <function>**call**</function>
> >             <operation>return self.application(environ, start_response)</operation>
> >             <operation_context>        environ['paste.recursive.script_name'] = my_script_name
> >         try:
> >             return self.application(environ, start_response)
> >         except ForwardRequestException, e:
> >             middleware = CheckForRecursionMiddleware(
> > </operation_context>
> >         </frame>
> >         <frame>
> >             <module>paste.httpexceptions</module>
> >             <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/eggs/Paste-1.7.5.1-py2.7.egg/paste/httpexceptions.py</filename>
> >             <line>633</line>
> >             <function>**call**</function>
> >             <operation>return self.application(environ, start_response)</operation>
> >             <operation_context>                           []).append(HTTPException)
> >         try:
> >             return self.application(environ, start_response)
> >         except HTTPException, exc:
> >             return exc(environ, start_response)
> > </operation_context>
> >         </frame>
> >         <frame>
> >             <module>galaxy.web.framework.base</module>
> >             <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/web/framework/base.py</filename>
> >             <line>132</line>
> >             <function>**call**</function>
> >             <operation>return self.handle_request( environ, start_response )</operation>
> >             <operation_context>        self.trace( message=&quot;Starting request&quot; )
> >         try:
> >             return self.handle_request( environ, start_response )
> >         finally:
> >             self.trace( message=&quot;Handle request finished&quot; )
> > </operation_context>
> >         </frame>
> >         <frame>
> >             <module>galaxy.web.framework.base</module>
> >             <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/web/framework/base.py</filename>
> >             <line>190</line>
> >             <function>handle_request</function>
> >             <operation>body = method( trans, *_kwargs )</operation>
> >             <operation_context>        kwargs.pop( '_', None )
> >         try:
> >             body = method( trans, *_kwargs )
> >         except Exception, e:
> >             body = self.handle_controller_exception( e, trans, **kwargs )
> > </operation_context>
> >         </frame>
> >         <frame>
> >             <module>galaxy.webapps.galaxy.controllers.tool_runner</module>
> >             <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/webapps/galaxy/controllers/tool_runner.py</filename>
> >             <line>90</line>
> >             <function>index</function>
> >             <operation>template, vars = tool.handle_input( trans, params.**dict** )</operation>
> >             <operation_context>        # so make sure to create a new history if we've never had one before.
> >         history = tool.get_default_history_by_trans( trans, create=True )
> >         template, vars = tool.handle_input( trans, params.**dict** )
> >         if len( params ) &gt; 0:
> >             trans.log_event( &quot;Tool params: %s&quot; % ( str( params ) ), tool_id=tool_id )
> > </operation_context>
> >         </frame>
> >         <frame>
> >             <module>galaxy.tools</module>
> >             <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/**init**.py</filename>
> >             <line>2116</line>
> >             <function>handle_input</function>
> >             <operation>state, state_new = self.**fetch_state( trans, expanded_incoming, history, all_pages=all_pages )</operation>
> >             <operation_context>        all_states = []
> >         for expanded_incoming in expanded_incomings:
> >             state, state_new = self.__fetch_state( trans, expanded_incoming, history, all_pages=all_pages )
> >             all_states.append( state )
> >         if state_new:
> > </operation_context>
> >         </frame>
> >         <frame>
> >             <module>galaxy.tools</module>
> >             <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/__init**.py</filename>
> >             <line>2230</line>
> >             <function>**fetch_state</function>
> >             <operation>state = self.new_state( trans, history=history, all_pages=all_pages )</operation>
> >             <operation_context>            new = False
> >         else:
> >             state = self.new_state( trans, history=history, all_pages=all_pages )
> >             new = True
> >         return state, new
> > </operation_context>
> >         </frame>
> >         <frame>
> >             <module>galaxy.tools</module>
> >             <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/__init**.py</filename>
> >             <line>2015</line>
> >             <function>new_state</function>
> >             <operation>self.fill_in_new_state( trans, inputs, state.inputs, history=history )</operation>
> >             <operation_context>        else:
> >             inputs = self.inputs_by_page[ 0 ]
> >         self.fill_in_new_state( trans, inputs, state.inputs, history=history )
> >         return state
> >     def fill_in_new_state( self, trans, inputs, state, context=None, history=None ):
> > </operation_context>
> >         </frame>
> >         <frame>
> >             <module>galaxy.tools</module>
> >             <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/**init**.py</filename>
> >             <line>2024</line>
> >             <function>fill_in_new_state</function>
> >             <operation>state[ input.name ] = input.get_initial_value( trans, context, history=history )</operation>
> >             <operation_context>        context = ExpressionContext( state, context )
> >         for input in inputs.itervalues():
> >             state[ input.name ] = input.get_initial_value( trans, context, history=history )
> >     def get_param_html_map( self, trans, page=0, other_values={} ):
> >         &quot;&quot;&quot;
> > </operation_context>
> >         </frame>
> >         <frame>
> >             <module>galaxy.tools.parameters.grouping</module>
> >             <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/parameters/grouping.py</filename>
> >             <line>535</line>
> >             <function>get_initial_value</function>
> >             <operation>rval[ child_input.name ] = child_input.get_initial_value( trans, child_context, history=history )</operation>
> >             <operation_context>        child_context = ExpressionContext( rval, context )
> >         for child_input in self.cases[current_case].inputs.itervalues():
> >             rval[ child_input.name ] = child_input.get_initial_value( trans, child_context, history=history )
> >         return rval

</operation_context>
        </frame>
        <frame>
            <module>galaxy.tools.parameters.basic</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/parameters/basic.py</filename>
            <line>943</line>
            <function>get_initial_value</function>
            <operation>options = list( self.get_options( trans, context ) )</operation>
            <operation_context>            # Really the best we can do?
            return UnvalidatedValue( None )
        options = list( self.get_options( trans, context ) )
        value = [ optval for _, optval, selected in options if selected ]
        if len( value ) == 0:
</operation_context>
        </frame>
        <frame>
            <module>galaxy.tools.parameters.basic</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/parameters/basic.py</filename>
            <line>763</line>
            <function>get_options</function>
            <operation>return eval( self.dynamic_options, self.tool.code_namespace, other_values )</operation>
            <operation_context>            return self.options.get_options( trans, other_values )
        elif self.dynamic_options:
            return eval( self.dynamic_options, self.tool.code_namespace, other_values )
        else:
            return self.static_options
</operation_context>
        </frame>
        <frame>
            <module>?</module>
            <filename>&lt;string&gt;</filename>
            <line>1</line>
            <function>&lt;module&gt;</function>
        </frame>
        <frame>
            <module>?</module>
            <filename>../shed_tools/toolshed.g2.bx.psu.edu/repos/george-weingart/lefse/db64b6287cd6/lefse/home/ubuntu/lefse_to_export/format_input_selector.py</filename>
            <line>41</line>
            <function>get_cols</function>
            <operation>lines = [(red((rc+&quot;#&quot;+str(i+1)+&quot;:&quot;+v.split()[0]),max_len),'%d' % (i+1),False) for i,v in enumerate(open(fname))]</operation>
            <operation_context> else:
        rc = ''
        lines = [(red((rc+&quot;#&quot;+str(i+1)+&quot;:&quot;+v.split()[0]),max_len),'%d' % (i+1),False) for i,v in enumerate(open(fname))]
    return opt+lines

</operation_context>
        </frame>
    </stack>
    <exception>
        <type>IndexError</type>
        <value>list index out of range</value>
    </exception>
</traceback>
<?xml version="1.0" ?>
<traceback>
    <sysinfo>
        <language version="2.7.8">Python</language>
    </sysinfo>
    <stack>
        <frame>
            <module>weberror.evalexception.middleware</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/eggs/WebError-0.8a-py2.7.egg/weberror/evalexception/middleware.py</filename>
            <line>364</line>
            <function>respond</function>
            <operation>app_iter = self.application(environ, detect_start_response)</operation>
            <operation_context>        try:
            **traceback_supplement** = errormiddleware.Supplement, self, environ
            app_iter = self.application(environ, detect_start_response)
            try:
                return_iter = list(app_iter)
</operation_context>
        </frame>
        <frame>
            <module>paste.recursive</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/eggs/Paste-1.7.5.1-py2.7.egg/paste/recursive.py</filename>
            <line>84</line>
            <function>**call**</function>
            <operation>return self.application(environ, start_response)</operation>
            <operation_context>        environ['paste.recursive.script_name'] = my_script_name
        try:
            return self.application(environ, start_response)
        except ForwardRequestException, e:
            middleware = CheckForRecursionMiddleware(
</operation_context>
        </frame>
        <frame>
            <module>paste.httpexceptions</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/eggs/Paste-1.7.5.1-py2.7.egg/paste/httpexceptions.py</filename>
            <line>633</line>
            <function>**call**</function>
            <operation>return self.application(environ, start_response)</operation>
            <operation_context>                           []).append(HTTPException)
        try:
            return self.application(environ, start_response)
        except HTTPException, exc:
            return exc(environ, start_response)
</operation_context>
        </frame>
        <frame>
            <module>galaxy.web.framework.base</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/web/framework/base.py</filename>
            <line>132</line>
            <function>**call**</function>
            <operation>return self.handle_request( environ, start_response )</operation>
            <operation_context>        self.trace( message=&quot;Starting request&quot; )
        try:
            return self.handle_request( environ, start_response )
        finally:
            self.trace( message=&quot;Handle request finished&quot; )
</operation_context>
        </frame>
        <frame>
            <module>galaxy.web.framework.base</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/web/framework/base.py</filename>
            <line>190</line>
            <function>handle_request</function>
            <operation>body = method( trans, *_kwargs )</operation>
            <operation_context>        kwargs.pop( '_', None )
        try:
            body = method( trans, *_kwargs )
        except Exception, e:
            body = self.handle_controller_exception( e, trans, **kwargs )
</operation_context>
        </frame>
        <frame>
            <module>galaxy.webapps.galaxy.controllers.tool_runner</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/webapps/galaxy/controllers/tool_runner.py</filename>
            <line>90</line>
            <function>index</function>
            <operation>template, vars = tool.handle_input( trans, params.**dict** )</operation>
            <operation_context>        # so make sure to create a new history if we've never had one before.
        history = tool.get_default_history_by_trans( trans, create=True )
        template, vars = tool.handle_input( trans, params.**dict** )
        if len( params ) &gt; 0:
            trans.log_event( &quot;Tool params: %s&quot; % ( str( params ) ), tool_id=tool_id )
</operation_context>
        </frame>
        <frame>
            <module>galaxy.tools</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/**init**.py</filename>
            <line>2116</line>
            <function>handle_input</function>
            <operation>state, state_new = self.**fetch_state( trans, expanded_incoming, history, all_pages=all_pages )</operation>
            <operation_context>        all_states = []
        for expanded_incoming in expanded_incomings:
            state, state_new = self.__fetch_state( trans, expanded_incoming, history, all_pages=all_pages )
            all_states.append( state )
        if state_new:
</operation_context>
        </frame>
        <frame>
            <module>galaxy.tools</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/__init**.py</filename>
            <line>2230</line>
            <function>**fetch_state</function>
            <operation>state = self.new_state( trans, history=history, all_pages=all_pages )</operation>
            <operation_context>            new = False
        else:
            state = self.new_state( trans, history=history, all_pages=all_pages )
            new = True
        return state, new
</operation_context>
        </frame>
        <frame>
            <module>galaxy.tools</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/__init**.py</filename>
            <line>2015</line>
            <function>new_state</function>
            <operation>self.fill_in_new_state( trans, inputs, state.inputs, history=history )</operation>
            <operation_context>        else:
            inputs = self.inputs_by_page[ 0 ]
        self.fill_in_new_state( trans, inputs, state.inputs, history=history )
        return state
    def fill_in_new_state( self, trans, inputs, state, context=None, history=None ):
</operation_context>
        </frame>
        <frame>
            <module>galaxy.tools</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/**init**.py</filename>
            <line>2024</line>
            <function>fill_in_new_state</function>
            <operation>state[ input.name ] = input.get_initial_value( trans, context, history=history )</operation>
            <operation_context>        context = ExpressionContext( state, context )
        for input in inputs.itervalues():
            state[ input.name ] = input.get_initial_value( trans, context, history=history )
    def get_param_html_map( self, trans, page=0, other_values={} ):
        &quot;&quot;&quot;
</operation_context>
        </frame>
        <frame>
            <module>galaxy.tools.parameters.grouping</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/parameters/grouping.py</filename>
            <line>535</line>
            <function>get_initial_value</function>
            <operation>rval[ child_input.name ] = child_input.get_initial_value( trans, child_context, history=history )</operation>
            <operation_context>        child_context = ExpressionContext( rval, context )
        for child_input in self.cases[current_case].inputs.itervalues():
            rval[ child_input.name ] = child_input.get_initial_value( trans, child_context, history=history )
        return rval

</operation_context>
        </frame>
        <frame>
            <module>galaxy.tools.parameters.basic</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/parameters/basic.py</filename>
            <line>943</line>
            <function>get_initial_value</function>
            <operation>options = list( self.get_options( trans, context ) )</operation>
            <operation_context>            # Really the best we can do?
            return UnvalidatedValue( None )
        options = list( self.get_options( trans, context ) )
        value = [ optval for _, optval, selected in options if selected ]
        if len( value ) == 0:
</operation_context>
        </frame>
        <frame>
            <module>galaxy.tools.parameters.basic</module>
            <filename>/n/galaxy/www/galaxy_hutlab14/galaxy-hutlab14-20150109/lib/galaxy/tools/parameters/basic.py</filename>
            <line>763</line>
            <function>get_options</function>
            <operation>return eval( self.dynamic_options, self.tool.code_namespace, other_values )</operation>
            <operation_context>            return self.options.get_options( trans, other_values )
        elif self.dynamic_options:
            return eval( self.dynamic_options, self.tool.code_namespace, other_values )
        else:
            return self.static_options
</operation_context>
        </frame>
        <frame>
            <module>?</module>
            <filename>&lt;string&gt;</filename>
            <line>1</line>
            <function>&lt;module&gt;</function>
        </frame>
        <frame>
            <module>?</module>
            <filename>../shed_tools/toolshed.g2.bx.psu.edu/repos/george-weingart/lefse/db64b6287cd6/lefse/home/ubuntu/lefse_to_export/format_input_selector.py</filename>
            <line>41</line>
            <function>get_cols</function>
            <operation>lines = [(red((rc+&quot;#&quot;+str(i+1)+&quot;:&quot;+v.split()[0]),max_len),'%d' % (i+1),False) for i,v in enumerate(open(fname))]</operation>
            <operation_context> else:
        rc = ''
        lines = [(red((rc+&quot;#&quot;+str(i+1)+&quot;:&quot;+v.split()[0]),max_len),'%d' % (i+1),False) for i,v in enumerate(open(fname))]
    return opt+lines

</operation_context>
        </frame>
    </stack>
    <exception>
        <type>IndexError</type>
        <value>list index out of range</value>
    </exception>
</traceback>

Extra Features

> >  Display the lines of code near each part of the traceback
> >     Show a debug prompt to allow you to directly debug the code at the traceback

**Comment by hexylena** [comment]
Hi, I'm afraid we cannot provide support for the LEfSE server, you will need to contact their admins.
