### ISSUE TITLE
JS eror on Main: Failed to parse SourceMap

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2475]
While browsing on Main (e.g. analysis, workflows or admin interface) I see this JS error appearing in the console:

`Failed to parse SourceMap: https://usegalaxy.org/static/scripts/bundled/libs.bundled.js.map`

**Comment by martenson** [comment]
I was unable to reproduce this in Firefox, however in Chrome it happens consistently.

**Comment by mvdbeek** [comment]
This doesn't seem to be the case anymore, at least I don't see it on our server or usegalaxy.eu
