### ISSUE TITLE
Multi-process setups require restarts after tool shed installs.

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#2478]
As discussed with christh on IRC, when installing a new tool, the tool is available on the Galaxy tool menu but executing it gets the error "This tool was disabled before the job completed." (described in more details here: https://biostar.usegalaxy.org/p/18014/)

The server christh reported the problem mentioned in biostars on was a 16.01 server in a uwsgi + 2 handlers configuration. I reproduced the problem on a dev (as of June 2016) server also in a uwsgi + 2 handlers configuration. To reproduce I did:

1) Install a tool (pitagora/unix_tools from the testtoolshed).
2) Execute the tool. The error described above occurs.

As soon as the Galaxy server is restarted (with `sudo service supervisor restart`)  the Galaxy server is able to execute the tool. I understand from @nsoranzo on IRC that this is known/expected behaviour but it is still, from the admin/user perspective, a bug.

**Comment by jmchilton** [comment]
I think a better title for this issue would be "Multi-process setups require restarts after tool shed installs." - mind if I change it?

**Comment by pvanheus** [comment]
Go ahead @jmchilton

**Comment by martenson** [comment]
I think this issue is now resolved since all processes should be monitoring the tool_conf for changes.
