### ISSUE TITLE
Open a dataset's "View details" (info) page as a scratchbook pop-up window

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2482]
The current display goes to the middle panel. It would be easier to compare two or more jobs runs if the view could be scratchbook enabled.
<img width="697" alt="screen shot 2016-06-09 at 1 22 32 pm" src="https://cloud.githubusercontent.com/assets/8999735/15945195/0b20f686-2e46-11e6-85c2-3d6bfa79d2e7.png">

**Comment by sszakony** [comment]
I think this was fixed with the changes made for issue 2747.

**Comment by guerler** [comment]
Yes I think so too. Thanks.
