### ISSUE TITLE
SSL releated backtrace when doing Toolshed "install to galaxy"

### ISSUE THREAD

**Issue by platyna** [galaxyproject/galaxy#2493]
Dear All,

I have found a following issue (exists also in newest Galaxy code (up to commit 5a97b8feac49df3f1e9fe0b2e0645b9240eb8291).

How to reproduce: run a SSL based Galaxy instance, pick any tool from toolshed and choose "install to Galaxy". See the attached file. 

How to fix - I have created a patch, excuse me if the quality of this code is poor - I am not a Python programmer. However it had been tested to work fine. See the attached file. 

[galaxy-bt.txt](https://github.com/galaxyproject/galaxy/files/312207/galaxy-bt.txt)

```
URL: https://fqdn/admin_toolshed/prepare_for_install?changeset_revisions=4de5efbfdb9f&repository_ids=666a10d0e9ba74e0&tool_shed_url=https%3A%2F%2Ftoolshed.g2.bx.psu.edu%2F

<snip>

File '/home/galaxy-test/galaxy-python/lib/python2.7/urllib2.py', line 1240 in https_open
  context=self._context)
File '/home/galaxy-test/galaxy-python/lib/python2.7/urllib2.py', line 1197 in do_open
  raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

[common_util.py-new.patch.txt](https://github.com/galaxyproject/galaxy/files/312208/common_util.py-new.patch.txt)

``` patch
--- galaxy-dist/lib/tool_shed/util/common_util.py.orig  2016-06-13 17:50:51.343437000 +0200
+++ galaxy-dist/lib/tool_shed/util/common_util.py   2016-06-13 17:51:58.675057000 +0200
@@ -1,12 +1,23 @@
 import json
 import logging
 import os
+import ssl

 from galaxy import util
 from galaxy.util.odict import odict
 from galaxy.web import url_for
 from tool_shed.util import encoding_util, xml_util

+try:
+
+    _create_unverified_https_context = ssl._create_unverified_context
+except AttributeError:
+    # Legacy Python that doesn't verify HTTPS certificates by default
+    pass
+else:
+    # Handle target environment that doesn't support HTTPS verification
+    ssl._create_default_https_context = _create_unverified_https_context
+
 log = logging.getLogger( __name__ )

 REPOSITORY_OWNER = 'devteam'
```

**Comment by mvdbeek** [comment]
Glad you found a solution for yourself, however you're disabling certificate validation, this is definitely not something we want to encourage.
There is plenty of information out there on how to fix the SSL setup for python installations (https://lists.galaxyproject.org/pipermail/galaxy-dev/2017-April/025605.html / https://access.redhat.com/articles/2039753). I'm closing this since it isn't really related to Galaxy.
