### ISSUE TITLE
Limited Collection Types Render in History

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#2495]
The history UI will only render `paired`, `list`, and `list:paired` I believe. Other collection types - including useful ones such as `list:list` and `list:list:paired` will not render and the history panel gives no indication there is a problem.

The tool form does properly render these options.

I thought there was an issue for this, but I cannot find one.

xref #2434

**Comment by mvdbeek** [comment]
It does work now, no idea when this was implemented.
