### ISSUE TITLE
Request a fix in the Galaxy framework for pbs_python / torque 4.x series incompatibility

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#2500]
I'm running a ChIP-exo Galaxy instance on ICS HPC here at PSU.  The cluster is using PBS and Torque 4.x series, so I am regularly bumping into this issue: 
http://dev.list.galaxyproject.org/Errors-running-DRMAA-and-PBS-on-remote-server-running-Torque-4-td4662169.html#a4662574.

Job errors are not always the same, making it more difficult to determine that the Torque server needs to be restarted.  I have worked with @davebx on this, so he is aware of the problem.  I can work with Dave to get a fix for this if he would like.

Thanks!

**Comment by natefoo** [comment]
As per conversation with @davebx it looks like we should be able to fix this by switching from `pbs_submit()` to `pbs_submit_hash()` in the pbs job runner.

**Comment by davebx** [comment]
I just need to figure out the syntax for `pbs_submit_hash()`, which has subtle differences.

**Comment by gregvonkuster** [comment]
Thanks for taking a look at this as it is critical for the Galaxy ChIP-exo instance I am managing here.  This instance is within an environment that is fully automated to process sequence runs, sending them through the ChIP-exo workflow.  This process fails for every sample because of this difference in pbs_python vs. torque 4.x due to the number of PBS jobs that are submitted per run.  If I get the torque server restarted at the beginning of a run, jobs will succeed for a time, but will fail before the run completes, and it is likely that no complete workflow will successfully finish for a single sample.  Please let me know how I can help out with this.  It would be really great if we can get a fix for this this week.

**Comment by gregvonkuster** [comment]
Thanks a bunch @davebx nd @natefoo for helping me out with this - especially @davebx, whom I am deeply indebted to.  Dinner and drinks are on me when you get back from GCC!

We ended up fixing the torque library rather than the Galaxy code, since the problem really isn't in the Galaxy code base.  So I'll close this issue, but if anyone encounters this behavior we have a work-around for it!

**Comment by Brentbin** [comment]
Hi @gregvonkuster 
I was meet the same trouble as yours
And could you give me some info?

**Comment by gregvonkuster** [comment]
@Brentbin 
@davebx did the heavy lifting here, so he can provide more details (or correct flaws in my details) if you need them.

I'm running Galaxy version 16.04 within a VM set up to access a cluster.  The 16.04 version includes a Python virtual environment that comes with the Galaxy install.  I've installed pbs_python 4.6 within this Python VM.

To work around this issue with pbs_python and Torque 4.x, we compiled the torque library using the approach described here: https://oss.trac.surfsara.nl/pbs_python/ticket/54

Specifically,

```
diff --git a/src/lib/Libifl/pbsD_submit.c b/src/lib/Libifl/pbsD_submit.c
index e096aa8..ca41cca 100644
--- a/src/lib/Libifl/pbsD_submit.c
+++ b/src/lib/Libifl/pbsD_submit.c
@@ -131,7 +131,7 @@ char *pbs_submit_err(

   if ((script != NULL) && (*script != '\0'))
     {
-    if (PBSD_jscript(c, script, NULL) != 0)
+    if (PBSD_jscript(c, script, return_jobid) != 0)
       {
       *local_errno = PBSE_BADSCRIPT;
```

We made sure that this local torque library (i.e., local to the VM in which I've installed Galaxy) will be found rather than the torque library installed on the cluster.

We recompiled pbs_python against this local torque library and everything worked just fine.

**Comment by natefoo** [comment]
I commented on the pbs_python issue linked by @gregvonkuster so I'll get a notification if/when it's fixed there, so we can update pbs_python when there's a release.
