### ISSUE TITLE
Rerun for datasets does not open Advanced Options when previously set (usage issue)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2502]
Found with the tools in the group: NCBI SRA Tools

To reproduce:
1. Load one of these tools
2. Enter an ID - example SRR566827
3. Open Advanced Options and change one of them
4. Start the job
5. Click on rerun before the tool starts to execute
6. The ID is present, and the changed Advanced Option is preserved, but the section is not expanded as it is normally
7. (Ignore that the data is too large to load with some tools/options, is over 30 GB - the tool limit - testing to see if actual and not another problem)

Impact: Complicates re-runs with different parameters

**Comment by jennaj** [comment]
Is this low priority? Should we close it?

**Comment by jennaj** [comment]
Still a problem in "Download and Extract Reads in BAM format from NCBI SRA (Galaxy Version 2.8.1.2)". 

Test history: https://usegalaxy.org/u/jen/h/test-history-ncbi-tools---rerun-view

One has one dataset. A SAM file was extracted and under advanced options a change was made to not output the header.  Job completed successfully (green). If rerun is used, there is no indication on the form this was modified. Most (if not all) other tools leave advanced options open, if originally was open when the job was executed, with a rerun, _even if nothing was changed_.

**Comment by jennaj** [comment]
When tool updated at https://usegalaxy.org, test again: https://github.com/galaxyproject/usegalaxy-playbook/issues/68

**Comment by guerler** [comment]
As far as I know the section will not automatically open when the page has been reloaded unless we added a feature to handle that i.e. the section head has to be clicked to expand the section.

**Comment by jennaj** [comment]
@guerler It used to do that automatically for all tools if something inside the advanced options was modified or if it was simply left expanded at runtime. 

This seems minor now, especially since the NCBI's tools were updated to avoid this particular use case (a potentially unintended no-header BAM output).

Let's close this out and revisit later if we need to.
