### ISSUE TITLE
Rename dataset disappear when importing published workflow

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#2507]
When importing a workflow from **Shared Data** => **Published Workflow** page, all options under the _Configure output_ section of all tools are not been imported/copied over.

Original user/creator workflow & no importing: 

http://imgur.com/dTXIi6p

Workflow imported from another user : 

http://imgur.com/2h4Ahyu

**Comment by dannon** [comment]
The problem here is that PJAs aren't copied when workflows are imported; I was looking into this for @erasche as well.  I have a fix I'll PR shortly.

**Comment by Takadonet** [comment]
@dannon Thanks!

**Comment by dannon** [comment]
@Takadonet #2508 should resolve your issue; let me know if it does not.

**Comment by Takadonet** [comment]
@dannon Works! Thanks
