### ISSUE TITLE
Multi-join has dependencies issues at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2511]
Multi-Join (combine multiple files) (Galaxy Version 1.0.0)

Error:

> job stderr:
> Can't locate Sort/Key/Natural.pm in @INC (you may need to install the Sort::Key::Natural module) (@INC contains: /galaxy/main/deps/perl/5.18.1/iuc/package_perl_5_18/114b6af405fa/lib/perl5 /galaxy/main/deps/perl/5.18.1/iuc/package_perl_5_18/114b6af405fa/lib/site_perl/5.18.1/x86_64-linux /galaxy/main/deps/perl/5.18.1/iuc/package_perl_5_18/114b6af405fa/lib/site_perl/5.18.1 /galaxy/main/deps/perl/5.18.1/iuc/package_perl_5_18/114b6af405fa/lib/5.18.1/x86_64-linux /galaxy/main/deps/perl/5.18.1/iuc/package_perl_5_18/114b6af405fa/lib/5.18.1 .) at /galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/37e1eb05b1b4/text_processing/multijoin line 8.
> BEGIN failed--compilation aborted at /galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/37e1eb05b1b4/text_processing/multijoin line 8.

Reported by https://biostar.usegalaxy.org/p/18123

**Comment by jennaj** [comment]
Related: Multi-join has frozen tool form options at http://usegalaxy.com
https://github.com/galaxyproject/galaxy/issues/2512

**Comment by jennaj** [comment]
@natefoo @martenson This tool is still a problem. Any ETA on when it will be fixed? Tx

**Comment by natefoo** [comment]
This tool's dependency `text_processing_perl_packages` claimed to be installed correctly but was not. I have reinstalled it and hopefully this should now be working.

**Comment by jennaj** [comment]
@natefoo testing

**Comment by jennaj** [comment]
@natefoo The tool works now, but has a few functionality issues. This probably needs a ticket against the tool repo. A form redesign could be needed.
- The output "datatype" is the same as the input datatypes. This would probably be better as "tabular" in most cases, since the output columns to preserve are user specified on the form. The output from d4 is an example - two BED files were input, but the result is definitely not BED format.
- Strangely, that same output (d4) also is deciding that the first line is real data and the rest of the output contains comment lines. If the first line was in a different format (number of columns or the column content itself differed) than the second, I could see where they might come up by datatype autodetect. Instead - what I think is going is that the assigned datatype doesn't match the fields and the tool is "saving" itself by calling the first line output and the rest comments (that don't match spec). Yes, this prevents a tool failure, but it also could mean the file is problematic when used for downstream operations.

I suggest that it should be tabular datatype always. BAM would present the only type that would be the same in-out .. maybe .. am running another test to see if that is true.

Shared history:  https://usegalaxy.org/u/jen/h/multi-join-test

**Comment by bgruening** [comment]
@jennaj please feel free to ping me if my tools are broken :)

I have something here but would appreciate help: https://github.com/bgruening/galaxytools/pull/413
I suppose many more tools have the same problem, e.g. cut, simple-join?

**Comment by jennaj** [comment]
Cut will break column assignments when not longer in spec (outputs tabular). Column-Join will incorrectly promote BED datatype to outputs (it also maintains interval, but technically that is OK if one of the inputs is interval and intact). Neither have a problem with comments vs data lines. I can't think of other with a problem right now but will watch/test again when the pull is accepted.
