### ISSUE TITLE
Multi-join has frozen tool form options at http://usegalaxy.com

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2512]
Multi-Join (combine multiple files) (Galaxy Version 1.0.0)

How to see the problem: Bring up the tool form. The highlighted section below is inactive using OSX/Chrome.

<img width="533" alt="screen shot 2016-06-16 at 1 48 39 pm" src="https://cloud.githubusercontent.com/assets/8999735/16133021/9c61d4b0-33ca-11e6-800d-535781ae22ad.png">

@bgruening I am not sure if this is just main or impacts other types of Galaxies (which?). Ticket could be moved to the tool repo if global. https://toolshed.g2.bx.psu.edu/view/bgruening/text_processing/288462ec2630

**Comment by carlfeberhard** [comment]
I _believe_ this is another instance of #1716. The control is not de-activated; the icons aren't being drawn properly. 

Edit: does the tool output properly if you click a choice (even though there's no checkbox for feedback)?

**Comment by jennaj** [comment]
@carlfeberhard I was unable to select a choice before. Pulled up the same history/setting and now I can select. Executed the tool, it produced an error, but seems to be dependency related - making it not an ideal test (error captured here https://github.com/galaxyproject/galaxy/issues/2511). Details about inputs and behavior in the history annotation. https://usegalaxy.org/u/jen/h/multi-join-issue

I am thinking that this ticket can be closed out and just leave the other ... ? Unclose if that seems best.

**Comment by jennaj** [comment]
Wait - it was about missing icons at one level - so that is fixed. This is the tool form now in graphic (icons present, option can be selected)

<img width="565" alt="screen shot 2016-06-22 at 10 27 47 am" src="https://cloud.githubusercontent.com/assets/8999735/16277088/39f4a3c0-3866-11e6-95f5-fe90e4bc1368.png">
