### ISSUE TITLE
implement quotas on MTS and TTS

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2517]
We host dozens of repositories that are in between 300MB - 1GB. These are not reasonable sizes - we expect the repos to be under 10MB (and even that should happen only when you cannot trim down test data). Repos this large are consuming our resources and are also almost impossible to install.

We need to implement repo size-quota to manage this. Users would still have unlimited number of repos.

ping @natefoo

**Comment by natefoo** [comment]
Might be sufficient to simply set this as an nginx limit. `client_max_body_size` on radegast is (inexplicably) currently set to 1GB.

**Comment by bgruening** [comment]
During last GCC we discussed to stop putting test data into the TS. We need some planemo love to make this happen, but there is only one use-case that is worth to put test data in the TS and this use-case is not widely used (TDT).

**Comment by peterjc** [comment]
TDT = ?

I would still love to be able to run the tests as the final step of installing a tool into Galaxy from the Tool Shed. For that to work, we still need to bundle the test data on the Tool Shed.

**Comment by peterjc** [comment]
@martenson How will affected tool authors know they are over the limit? Will future uploads/updates fail with a message about being over quota?

**Comment by martenson** [comment]
@peterjc I think Bjoern meant test driven development?

> How will affected tool authors know they are over the limit? Will future uploads/updates fail with a message about being over quota?

I am currently testing various scenarios on TTS, will post in the IUC gitter once I am done. 

Generally speaking the test data size is currently not the issue, most often it is the user mistakes. I agree that test data are valuable and the tools benefit from the adjacency of the test data.

**Comment by peterjc** [comment]
Thanks, I'll try to keep an eye on Gitter then...

**Comment by bgruening** [comment]
@peterjc  what we discussed during GCC is a `url`/`uri` tag in the test section of a tool, so that Galaxy can fetch it during testing. This way it does not need to be stored on every local Galaxy instance and the TS. But this really needs to engineering work and we need to find a way how planemo can upload tools to the TS and the test data to a magic test-data repo.

**Comment by martenson** [comment]
>This way it does not need to be stored on every local Galaxy instance

I have nothing against the idea, but if we can limit the size of test data and still have good test the benefits of such changes are limited.

**Comment by bgruening** [comment]
@martenson check the size of your shed_tools directory and you know why we need it! :) Freeing the TS is a nice benefit!

**Comment by davebx** [comment]
> @peterjc I think Bjoern meant test driven development?

My guess would be Tool Data Tables.

**Comment by bgruening** [comment]
I think he meant `Tool Describing Tours`, which is only enabled at usegalaxy.eu I guess - so not a super important use-case. But if we have `url`s in the tool-tests, TDT could also work for people with internet access.

**Comment by martenson** [comment]
So the concern is the disk space on Galaxy host? How big is shed_tools for galaxy eu? (the most tools on galaxy I know about)

**Comment by bgruening** [comment]
> du -h shed_tools
> 39G	shed_tools/

**Comment by martenson** [comment]
The changes are live, nobody is able to upload anything bigger than 64MB to Main or Test toolshed effective now.

@peterjc 
This is how the errors look like when you try uploading something bigger than 64MB from web/planemo: 
![screenshot 2019-02-11 11 53 16](https://user-images.githubusercontent.com/1814954/52580036-771ae700-2df5-11e9-8e90-953777d6fa45.png)
![screenshot 2019-02-11 12 04 30](https://user-images.githubusercontent.com/1814954/52580037-771ae700-2df5-11e9-87b3-62145b438fb9.png)
