### ISSUE TITLE
imported data-library datasets are not displayable and downloadable

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#2519]
I have a strange issue with datasets downloaded from a data library.
All items in our data library are symlinked via path and can be imported. The imported datasets _can_ be used by tools and in workflows.

However, these datasets can not be viewed and can not be downloaded (not from the history and not from the data library). I see different behaviours from different files. E.g. this link is visible `http://galaxy.uni-freiburg.de/datasets/ae7eca43c36ad114/display/?preview=True` but this one not: `http://galaxy.uni-freiburg.de/datasets/ae7eca43c36ad114/display/`.

I get this error in Galaxy (no stack trace in the logs):
`The requested URL /datasets/ae7eca43c36ad114/display/ was not found on this server.`

We tried to not symlink data into a data library and it seems to work. So this can mean it is a problem with handling of symlinks in the data libraries.

**Comment by martenson** [comment]
@bgruening Thanks for the report. What version are you at?

**Comment by bgruening** [comment]
16.04, latest git.

**Comment by martenson** [comment]
@bgruening Thanks. Is this the first time you used this feature and observe this behaviour? Did you just update from 16.01?

**Comment by bgruening** [comment]
No it worked before. We just updated recently, but I can not say for sure it worked with 16.01. Usually you just import data and run things on it .. which still works. Just downloading and looking at these data is broken.

**Comment by sszakony** [comment]
Our production server is still on 16.01, and I'm able to see and download a fasta file imported from our linked data sets. Also tested on our pre-production server, which is on 16.04, and had no issues. Possible I may not be duplicating your conditions exactly. Let me know if I can help further.

**Comment by martenson** [comment]
I am closing this since I was not able to replicate it. If you can, please let me know and I will gladly reopen.
