### ISSUE TITLE
2016 GCC Data Hackathon Hub

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2520]
New Home: https://github.com/bxlab/galaxy_hackathon/issues/31

**Comment by yvanlebras** [comment]
Hi everyone,

A first rapid proposition list I wrote for myself and maybe can be of interest... or not ;) :
- Data and metadata
  - Data collection use and improvement
  - ISA metadata system and tools  
- Material for Teaching
  - Create [interactive tours](https://github.com/galaxyproject/galaxy-tours)
    -Documentation on the step options of the[ Bootstrap tour dedicated page documentation](http://bootstraptour.com/api/)
  - Update the [RADSeq first try](https://github.com/galaxyproject/galaxy-tours/tree/master/rad-seq) 
  - Working on [Galaxy pages](https://wiki.galaxyproject.org/Learn/GalaxyPages) 
- Create workflows for exchange on the Tool shed
  - Is the tool shed really a good place to exchange workflows ??? 
- Galaxy flavours
  - Create / update Galaxy flavours, [Metagenomics example](https://github.com/bgruening/galaxy-metagenomics) 
- Testing Galaxy instance / tools

**Comment by bgruening** [comment]
@yvanlebras see this idea on the code side: https://github.com/bxlab/galaxy_hackathon/issues/4

**Comment by yvanlebras** [comment]
Thanks @bgruening ! Concerning interactive tour, I found the [Bootstrap tool](http://bootstraptour.com/).. Thank you also for info!

**Comment by griffinp** [comment]
Philippa Griffin here... I would like to work on area 4) finding some good example datasets - e.g. for variant calling, and/or for RADseq (but happy to work on other topics)
I will only be here part of Saturday as I'm teaching on Sunday.

**Comment by nathanweeks** [comment]
Ideas:
1. Create a Galaxy tool for the Canu Assembler
2. Pipelines in Galaxy (UI design and backend implementation w/ Unix pipes)

**Comment by ghost** [comment]
Ideas (Krzysztof Poterlowicz):
1. Galaxy flavour for epigenomics analysis
2.Teaching materials for biomedical students (i.e epigenetics)

**Comment by ssander5** [comment]
I am most interested in working on:
1) writing tutorials that go along with the Shared Data Libraries
2) helping set up and establish Shared Data Libraries
3) developing best practice workflows

Also, I don't know if this exists already (as I said, I am new to galaxy), but I think it would be useful to have some means of exporting workflows into command line syntax.  My previous lab was half command line friendly and half not, both stubbornly sticking to what they knew.  I don't think this is uncommon and it would be useful to have the ability to export a workflow used in galaxy to also be used on command line, with the same parameters, etc.  This would also serve as an easy way to transition people from learning bioinformatics on galaxy to also gaining comfort/familiarity on command line.  Just a thought ^_^.

**Comment by MoHeydarian** [comment]
Data visualization/plotting - the chart/visualization tools in Galaxy are limiting. It would be nice to be able to visualize/plot data with the same flexibility you have in R (with ggplot2, for example), but not have to move your data out of Galaxy.

**Comment by devikaatgit** [comment]
I have 3 points to make:
1.  I am interested in developing a stable pipeline/workflow for genomic as well as transcriptomic assembly and differential expression of prokaryotic microorganisms - for both paired end and single end reads... - easy to use for biologists like me
2.  Integration of bioconductor package workflows; I am specially interested in Ballgown - an R package for statistical analysis of assembled transcriptomes that I wish to use after Stringtie.
3.  Also i feel it would be good if the data visualization tools can be improved a little more, like plotting graphs and even networks (Genes as nodes/Interactions or co-expression data from RNA-seq etc as edges)... Even venn diagrams now take up only upto 3 sets... aspects like that can be improved...

My points come from the application point of view that i make use of in Galaxy. I am still not sure if these are the ones expected for the hackathon, 

Nevertheless these are what I think of. Let us move forward.

Happy Hackathon everyone!!!

**Comment by BoughAida** [comment]
I am interested on:
1. Creating Galaxy workflow for variant calling with GATK for prokaryotic genomes (existing already in command-line)
2. Exporting a Galaxy workflow into command-lines

I would like to help on Finding some good example datasets - e.g. for variant calling (Yvan's idea)

**Comment by firaan1** [comment]
Aarif here... I have a couple of issues and interests...

accessing galaxy from commandline api (sort of),
handling dataset names in workflow and deleting intermediate datasets after workflow completion,
rnaseq variant calling pipeline,
ggploting tools
Multiple history panel functionalities
apply workflows directly on data from datalibraries ( not just histories)
Openbis and galaxy (any hope??)

all other topics too

**Comment by BoughAida** [comment]
I am also interested on devikaatgit's points. We have the same research issues.

**Comment by MoHeydarian** [comment]
Agree with Aarif. Handling data set names in workflows needs improvement. Some tools cooperate with  naming terminal data sets, but most do not.

**Comment by jxtx** [comment]
@MoHeydarian regarding dataset names, this is probably relevant: https://github.com/bxlab/galaxy_hackathon/issues/13

**Comment by ghost** [comment]
Hi Guys,
I am interested in the couple of things you mentioned including:
- ggploting tools
- Exporting a Galaxy workflow into command-lines
- Shared Data Libraries
- integration of bioconductor package workflows

**Comment by MoHeydarian** [comment]
We should ask the Coding hackers if anyone is interested in updating **Trackster to output high resolution images** from genomic regions (like a pdf). The UCSC genome browser does this, but this requires additionally formatting data (ex: BAM to bedgraph), renaming files, and moving it out of Galaxy (not ideal).

**Comment by dannon** [comment]
@MoHeydarian I know @msauria was interested in outputting nice trackster figures.  See https://github.com/bxlab/galaxy_hackathon/issues/17

**Comment by yvanlebras** [comment]
Some interesting [hackathon issues](https://github.com/bxlab/galaxy_hackathon/issues?page=1&q=is%3Aissue+is%3Aopen):
- [IGV.js](https://github.com/bxlab/galaxy_hackathon/issues/18)
-  [JBrowse extension](https://github.com/bxlab/galaxy_hackathon/issues/10)
-  [Enhance charts visualization](https://github.com/bxlab/galaxy_hackathon/issues/27)
-  [Data sharing between instances](https://github.com/bxlab/galaxy_hackathon/issues/24)
-  [Galaxy workflow / Common Workflow Language](https://github.com/bxlab/galaxy_hackathon/issues/21)
-  [Submit Galaxy wf to TS](https://github.com/bxlab/galaxy_hackathon/issues/4)

**Comment by crutching** [comment]
One thing we really need, and I think this need is universal, is a framework from which to validate genomics workflows quickly.  As new tools are developed, it is difficult for clinical genomicists to actually adopt them as the barrier towards CLIA/CAP validation is significant.  Additionally, finding the correct parameter sets for a given tool is also not trivial, and requires some sort of rapid parameter sweep and results evaluation.

**Comment by kkamieniecka** [comment]
Galaxy workflow for epigenomics analysis
