### ISSUE TITLE
Add latestest UCSC genomes to builds.txt plus .len data to http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2530]
**Impact**
- Cannot assign "database" metadata
- Indexes are not available for some tools, are available for others
- Creating custom builds.txt entries could create duplicates/conflicts in build names if added. 

**Added as custom builds on test-installer, but did not make it to Main (adding could be the solution)**
- [x] rn6 Rat 
- [x] aptMan1 Brown Kiwi 
- [x] danRer10 Zebrafish

**Related**
- **rn6 and danRer10** missing len. Causes tool failures. data https://github.com/galaxyproject/galaxy/issues/2884

**Comment by jennaj** [comment]
@blankenberg updated the build.txt but it looks like it created duplicates for what we (well, I) added as new dbkeys with the DM (before the update).

@natefoo this is another data item we'll need to correct at some point. The dbkeys are the same so "assuming" we can just pick one and the indexes will still be found correctly by tools. But, Dan, correct me if that is wrong so we sort this out correctly so the .len & indexes map right.

Examples from just those three above. A few others were added before that update and suspect are also dups now.

<img width="642" alt="screen shot 2017-10-25 at 10 10 32 am" src="https://user-images.githubusercontent.com/8999735/32012649-710a6226-b96d-11e7-9b29-66911a8a7d76.png">
<img width="637" alt="screen shot 2017-10-25 at 10 11 01 am" src="https://user-images.githubusercontent.com/8999735/32012650-7135f0c6-b96d-11e7-8b1e-abb9be8865b9.png">
<img width="641" alt="screen shot 2017-10-25 at 10 11 54 am" src="https://user-images.githubusercontent.com/8999735/32012651-714bb596-b96d-11e7-85da-1720b84876fd.png">

**Comment by bernt-matthias** [comment]
No len files are available for ucsc data. So for instance CONVERTER_bed_gff_or_vcf_to_bigwig_0 fails bacause it can't find tool-data/shared/ucsc/chrom/hg38.len (the directory is completely empty, ie it wont work for any genome)

**Comment by jennaj** [comment]
Duplicates captured here: https://github.com/galaxyproject/usegalaxy-playbook/issues/55

Closing
