### ISSUE TITLE
Conda dependency resolver auto_installer fails if conda_prefix is too long

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#2537]
The conda dependency resolver (unsurprisingly) is affected by this conda issue: https://github.com/rtfd/readthedocs.org/issues/1902 . In short, if the conda_prefix and resulting environment name is longer than the name of the prefix used during package build time, the installer will fail. A typical error message is:

```
Error: ERROR: placeholder '/root/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placehold_p' too short in: ncurses-5.9-4
```

I doubt there is anything that can be done from the Galaxy side to fix this, but perhaps a documentation patch is in order.

**Comment by bgruening** [comment]
@pvanheus I think this was fixed upstream: https://github.com/conda/conda-build/pull/877
Unfortunately,  we are still stuck with an older version because of this: https://github.com/conda/conda/issues/2035

**Comment by nsoranzo** [comment]
@bgruening The broken conda packages still need to be rebuilt, see https://github.com/conda/conda/issues/2353#issuecomment-226594839

**Comment by bgruening** [comment]
Sure, but this is a larger effort. It only happens for users with a large prefix afaik.

**Comment by pvanheus** [comment]
I've written a new test (part of https://github.com/galaxyproject/galaxy/pull/2538) that will fail when we use a conda with this issue fixed) and added a warning message if the prefix is > 50 characters. This issue should be mentioned in the conda dependency manager docs too.

**Comment by jmchilton** [comment]
This seems to be fixed with recent conda upgrade and is included in 17.01. xref #3482

**Comment by bernt-matthias** [comment]
But, there is still the message if the prefix is to long and galaxy.ini also contains text on to long prefix. Should be changed if the bug is fixed (also for job_working_directory).

**Comment by jmchilton** [comment]
@bernt-matthias What message are you seeing?

If it looks something like:

```Error: ERROR: placeholder '/root/miniconda3/envs/_build_placehold_placehold_placehold_placehold_placehold_p' too short in: ncurses-5.9-4```

You may need to ping someone on bioconda to rebuild the package - this shouldn't happen with newer packages.

**Comment by bernt-matthias** [comment]
Sorry, I should have been more specific. The warning message that is printed during galaxy (17.01) startup is: 

`galaxy.tools.deps.resolvers.conda WARNING 2017-05-02 07:13:47,479 Conda install prefix '/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda' is 65 characters long, this can cause problems with package installation, consider setting a shorter prefix (conda_prefix in galaxy.ini)`

galaxy.ini contains the following comment: 

```
# IMPORTANT: Due to a current limitation in conda, the total length of the
# conda_prefix and the job_working_directory path should be less than 50 characters!
```

**Comment by mvdbeek** [comment]
~~Yeah, this is a legacy warning by now. We can remove this, I think.~~
I think we already removed this in dev.

**Comment by nsoranzo** [comment]
> I think we already removed this in dev.

@mvdbeek Not in `config/galaxy.ini.sample` .
