### ISSUE TITLE
Right click contextual menu

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#2546]
We're considering the use of a right click contextual menu to handle a very specific user education case (more on that later).

In exploring this, we considered how such a menu could actually be useful outside of this one corner case, and realised that we could place all of the actions available in the current datasets within a single right click menu (or a single hamburger menu for better discoverability).

This would radically simplify dataset representations into a much cleaner, more streamlined design.

Con:
- Changes
- Extra Click

Pro:
- Cleaner design
- We handle our use case

![2016-06-26-001121_1366x768_scrot](https://cloud.githubusercontent.com/assets/458683/16359825/f0cebb88-3b33-11e6-8602-3e5b6b00b262.png)
![2016-06-26-001402_1366x768_scrot](https://cloud.githubusercontent.com/assets/458683/16359899/5e993f1a-3b36-11e6-8082-441cdbd7c09b.png)

See? So much better ;) Double clicking the dataset could view it (for streamlined access, similar to how google docs functions).

Our corner use case: When displaying files from a secondary domain (for security), we are considering the use of a token for access (like github does) for private files. Naturally this means that file would be accessible long term to anyone with the URL. While it's a reasonable assumption github users would understand the implications of a `?token=asdfasdf`, it's less reasonable for non-coders. Thus, we need to intercept and do some user education when people use the right click - open in new tab, or right click - copy link sort of functionality.

(This isn't sarcasm, but is suggested in good humour, and possibly to ruffle some feathers ;))

cc @bgruening @tnabtaf @nekrut

**Comment by jxtx** [comment]
How about a pie menu ;)

**Comment by hexylena** [comment]
We are reconsidering as single use tokens which would avoid user education. This requires more JS magic, but is not insurmountable and possibly easier.

:+1: to pie menus!!!
