### ISSUE TITLE
Idea: Tour Recorder

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#2558]
overlay, record clicks / click targets, pop up and ask for an annotation, store steps in storage, output a workflow?

**Comment by mvdbeek** [comment]
:+1

**Comment by bgruening** [comment]
We have done some evaluation of technologies which we can use for this and searching for an intern to implement it. Get in touch if you are interested.

**Comment by frederikcoppens** [comment]
+1 
Would be needed for wider adoption IMO

**Comment by bgruening** [comment]
I bet @wookoouk could get this running in a week ... I will bribe him with :beers:

**Comment by doomedramen** [comment]
Could someone give me a little context on this plz?

**Comment by bgruening** [comment]
We have intergrated http://bootstraptour.com/ in Galaxy and can define now a yaml file that defines such a tour. To make it easier to create such a tool it would be nice if we can track all clicks on the fly and record them to create such a tour without much coding.

**Comment by hexylena** [comment]
@wookoouk @dannon mentioned starting work on it already.

**Comment by doomedramen** [comment]
👍

**Comment by hexylena** [comment]
@dannon can you make a hard commitment to getting this implemented in the next month or two?

If not, @wookoouk has done great things in the past and seems to be open to beer bribes :) This is a feature we (the community) would love to see and start iterating upon sooner rather than later.

**Comment by remimarenco** [comment]
👍

**Comment by hexylena** [comment]
https://github.com/TailorDev/galaxy-tourbuilder fixes this. Thanks @willdurand
