### ISSUE TITLE
Create toolshed section for Flow Cytometry

### ISSUE THREAD

**Issue by cristhomas** [galaxyproject/galaxy#2565]
Hello,
Could someone please create a section in the toolshed for flow cytometry analysis? We have a bunch of tools that we'd ideally want to share, but they really are specific to FCS files and can't really fit in any of the existing sections.
Thank you much!

**Comment by martenson** [comment]
Hi @cristhomas , I can do that for you. Give me please the full name and description of this category.

**Comment by cristhomas** [comment]
Ah that was fast. What do you need exactly in terms of description?
Full name should be something like "Flow cytometry analyses"

**Comment by cristhomas** [comment]
analysis*

**Comment by martenson** [comment]
@cristhomas have a look at other category descriptions for inspiration. https://testtoolshed.g2.bx.psu.edu/

I will put in `Flow Cytometry Analysis` then, please send me the description.

**Comment by cristhomas** [comment]
Right, description should be "Tools for manipulating and analyzing FCS files"

**Comment by martenson** [comment]
I created the category in the TTS (https://testtoolshed.g2.bx.psu.edu/). Please check it out and try uploading a repo.

**Comment by cristhomas** [comment]
looks good, thank you. how does that work if we want to also have the flow tools on the not-test toolshed?

**Comment by martenson** [comment]
@cristhomas It has now been created on the Main Tool Shed.https://toolshed.g2.bx.psu.edu/

 Thanks for contributing to Galaxy!
