### ISSUE TITLE
"Annotation/notes" not saved on Galaxy Main's workflow interface

### ISSUE THREAD

**Issue by mr-c** [galaxyproject/galaxy#2567]
1. Enter text, click out or hit "enter",

![annotation-step-1](https://cloud.githubusercontent.com/assets/1330696/16421456/f59e7a2c-3d22-11e6-9242-28086e8b98b9.png)
2. It disappears

![annotation-step-2](https://cloud.githubusercontent.com/assets/1330696/16421455/f5900dfc-3d22-11e6-9881-ae0ed29db8ec.png)

**Comment by dannon** [comment]
More info in #2606.

**Comment by hexylena** [comment]
Working now

**Comment by mr-c** [comment]
Thanks!
