### ISSUE TITLE
Button to have checkboxes to select datasets e.g. collections is not evident

### ISSUE THREAD

**Issue by frederikcoppens** [galaxyproject/galaxy#2571]
I spent quite some time figuring out how I could make a collection, because I didn't make the connection with the "checkbox button" and the popover "operations on multiple datasets" & collections. 
Maybe change the icon to the folder icon used for collections elsewhere? Or have a dedicated button?

**Comment by hexylena** [comment]
Ping @guerler

**Comment by jmchilton** [comment]
There is a dedicated tab within the uploader now. I think this might be solved? Feel free to re-open with more advice about making the multi-select options more explicit though.
