### ISSUE TITLE
Why no "include deleted datasets" anymore in history options?

### ISSUE THREAD

**Issue by frederikcoppens** [galaxyproject/galaxy#2573]
You can unhide deleted datasets through the "deleted" at the top of the history, but I would also expect it in the history options. 
I assume there is a reason why it's not there anymore, but would advocate to reinstate it ;-)

**Comment by hexylena** [comment]
Why - to clean up the menu since it was overwhelming.

Yeah, a change for users, I  hope yours could adapt to it in the past years!
