### ISSUE TITLE
Galaxy 16.04 problem with tools using dataset collections

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#2581]
I've encountered a problem where a tool will not properly create a dataset collection when the input to the tool is a dataset collection, although the tool will function correctly if the input is not a dataset collection.  This problem occurs regularly in workflows, causing the workflow to stop executing at that step.  I believe this issue may be related to other issues (e.g., https://github.com/galaxyproject/galaxy/issues/2179), so hopefully fixing this will help to close other tickets as well.

I've spent some time looking into this and hope that the following details will help to get a quick resolution as I believe this issue is the last obstacle to have a fully functional ChIP-exo workflow for Galaxy.

I've included a tool here  named test_first that can be used to reproduce this issue.

test_first.xml

```
<tool id="test_first" name="Test first" version="1.0.0">
    <description></description>
    <requirements>
    </requirements>
    <command>
        <![CDATA[
            mkdir -p output &&
            python $__tool_directory__/test.py
            --input1 "${input1}"
        ]]>
    </command>
    <inputs>
        <param name="input1" type="data" format="txt" label="Input 1"/>
    </inputs>
    <outputs>
        <collection name="my_first_coll" type="list" label="My first collection">
            <discover_datasets pattern="(?P&lt;name&gt;.*)" directory="output" visible="false" />
        </collection>
    </outputs>
    <tests>
    </tests>
    <help>
    </help>
    <citations>
    </citations>
</tool>
```

test.py

```
#!/usr/bin/env python
import argparse
import os

parser = argparse.ArgumentParser()
parser.add_argument('--input1', dest='input1', help='input 1')
args = parser.parse_args()

collection_path = os.path.join(os.getcwd(), 'output')

i = 0
for line in open(args.input1, 'r'):
    i += 1
    file_name = os.path.join(collection_path, 'FILE%s.txt' % i)
    fh = open(file_name, 'wb')
    fh.write(line)
    fh.close()
```

When executed with this input dataset (which is not a dataset collection)...
<img width="213" alt="input" src="https://cloud.githubusercontent.com/assets/6947053/16521039/1c133ecc-3f62-11e6-9d79-b0b7e8a0e88c.png">

...the tool properly produces this dataset collection.
<img width="210" alt="collection" src="https://cloud.githubusercontent.com/assets/6947053/16521578/d32d3ed4-3f65-11e6-8036-a597967d3fc1.png">

In this scenario, the dataset collection is initially created with 0 elements - here is the entry in the Galaxy paster log.

```
galaxy.managers.collections DEBUG 2016-07-01 08:05:07,956 Created collection with 0 elements
```

When the tool executes, the datasets are added to the dataset collection produced by the tool.  Here are the entries from the Galaxy paster log.

```
galaxy.tools.parameters.output_collect DEBUG 2016-07-01 08:05:41,184 (11101) Created dynamic collection dataset for path [/gpfs/cyberstar/pughhpc/galaxy-cegr/job_working_directory/011/11101/working/output/FILE1.txt] with element identifier [FILE1.txt] for output [my_first_coll] (102.013 ms)
...
galaxy.tools.parameters.output_collect DEBUG 2016-07-01 08:05:41,234 (11101) Created dynamic collection dataset for path [/gpfs/cyberstar/pughhpc/galaxy-cegr/job_working_directory/011/11101/working/output/FILE2.txt] with element identifier [FILE2.txt] for output [my_first_coll] (49.324 ms)
...
galaxy.tools.parameters.output_collect DEBUG 2016-07-01 08:05:41,286 (11101) Created dynamic collection dataset for path [/gpfs/cyberstar/pughhpc/galaxy-cegr/job_working_directory/011/11101/working/output/FILE3.txt] with element identifier [FILE3.txt] for output [my_first_coll] (51.444 ms)
...
galaxy.tools.parameters.output_collect DEBUG 2016-07-01 08:05:41,377 (11101) Add dynamic collection datsets to history for output [my_first_coll] (91.413 ms)
...
galaxy.jobs INFO 2016-07-01 08:05:41,508 Collecting metrics for Job 11101
galaxy.jobs DEBUG 2016-07-01 08:05:41,529 job 11101 ended (finish() executed in (666.016 ms))
```

Our Galaxy history now includes the original input dataset and our new collection.
<img width="211" alt="history1" src="https://cloud.githubusercontent.com/assets/6947053/16521700/979b98a6-3f66-11e6-91f7-66fd33db6b71.png">

The error is encountered when we use the dataset collection we just produced as the input when we execute the tool a 2nd time.
<img width="483" alt="collection_input" src="https://cloud.githubusercontent.com/assets/6947053/16521744/f3d760b4-3f66-11e6-979c-008401f50a0e.png">

In this scenario, the dataset collection is initially created with 3 elements.  Here is the Galaxy paster log entry.

```
galaxy.managers.collections DEBUG 2016-07-01 08:37:10,469 Created collection with 3 elements
```

This occurs due to the __load_element() function in ~/lib/galaxy/managers/collections.py, which includes the following comment:

```
# Previously created collection already found in request, just pass
# through as is.
```

As the tool executes, the 3 datasets that are supposed to be added to the collection point to the same file.  Here are the Galaxy paster log entries.

```
galaxy.tools.parameters.output_collect DEBUG 2016-07-01 08:37:38,289 (11108) Created dynamic collection dataset for path [/gpfs/cyberstar/pughhpc/galaxy-cegr/job_working_directory/011/11108/working/output/FILE1.txt] with element identifier [FILE1.txt] for output [my_first_coll] (70.213 ms)
...
galaxy.tools.parameters.output_collect DEBUG 2016-07-01 08:37:41,341 (11109) Created dynamic collection dataset for path [/gpfs/cyberstar/pughhpc/galaxy-cegr/job_working_directory/011/11109/working/output/FILE1.txt] with element identifier [FILE1.txt] for output [my_first_coll] (49.238 ms)
...
galaxy.tools.parameters.output_collect DEBUG 2016-07-01 08:37:51,117 (11107) Created dynamic collection dataset for path [/gpfs/cyberstar/pughhpc/galaxy-cegr/job_working_directory/011/11107/working/output/FILE1.txt] with element identifier [FILE1.txt] for output [my_first_coll] (50.875 ms)
```

The job finishes successfully:

```
galaxy.jobs INFO 2016-07-01 08:37:51,343 Collecting metrics for Job 11107
galaxy.jobs DEBUG 2016-07-01 08:37:51,363 job 11107 ended (finish() executed in (471.584 ms))
```

But our history does not include the properly constructed dataset collection for the output.  Notice, however, that there are some hidden outputs now.
<img width="213" alt="history2" src="https://cloud.githubusercontent.com/assets/6947053/16522125/b32d2910-3f69-11e6-98c6-5ecd2f852689.png">

Looking at the hidden items shows the 3 datasets that should be included in the collection (although they all point to the same data files on disk), but they seem to be somehow disconnected from the collection itself.
<img width="209" alt="history3" src="https://cloud.githubusercontent.com/assets/6947053/16522186/0cd17eda-3f6a-11e6-9038-b61866d44b2f.png">

This issue occurs in a workflow when tool 1 produces a dataset collection which is used as the input to tool 2.  The workflow will stop at tool 2, with a Galaxy paster log entry like this:

```
handler1.log:galaxy.tools.execute DEBUG 2016-06-25 18:22:43,515 Executed 0 job(s) for tool toolshed.g2.bx.psu.edu/repos/iuc/resize_coordinate_window/resize_coordinate_window/1.0.1 request: (27.811 ms)
```

Please let me know if / how I can help out in getting this resolved as it is critical for the ChIP-exo Galaxy flavor.

Thanks in advance.  ;)

**Comment by bongsoopark** [comment]
+1 on fixing this. Please check this problem. It is critical for fixing our ChIP-exo pipeline. We are very close to the first production version of ChIP-exo Galaxy flavor! Thanks! :-)

**Comment by grettadarmstrong** [comment]
+1 on fixing this issue that is needed for fixing our ChIP-exo pipeline. Thanks very much for the assist!

**Comment by gregvonkuster** [comment]
Would it be possible for someone from the committer's team to label this as a bug with a priority of critical or similar?  This issue is the only remaining "show stopper" for the Galaxy ChIP-exo flavor.  Also, I am hopeful that a fix for this issue will help to close other tickets.  Thanks!

**Comment by bgruening** [comment]
@gregvonkuster most of us are probably still travelling or on holidays.

**Comment by gregvonkuster** [comment]
I've looked into this further to see if I could find a proper fix or at least a work-around.  I think I've discovered an option for the latter, hoping the work-around is not producing different results than the proper fix will ultimately produce.  

With the work-around, the proper set of output collections is created in the history, and each collection consists of the correct datasets (at least in my testing so far).

Also, my ChIP-exo workflow executes all tools - it no longer stops at the step where a tool produces an output collection that is used as input to another tool that is not specifically designed to accept a collection as input.

Here is the work-around for Galaxy  version 16.04.

```
$ git diff lib/galaxy/tools/actions/__init__.py
diff --git a/lib/galaxy/tools/actions/__init__.py b/lib/galaxy/tools/actions/__init__.py
index 5cfee0f..aefcd14 100644
--- a/lib/galaxy/tools/actions/__init__.py
+++ b/lib/galaxy/tools/actions/__init__.py
@@ -414,7 +414,8 @@ class DefaultToolAction( object ):

                         collection_type = input_collections[collection_type_source].collection.collection_type

-                    if mapping_over_collection:
+                    #if mapping_over_collection:
+                    if False:
                         dc = collections_manager.create_dataset_collection(
                             trans,
                             collection_type=collection_type,

```

Here is the work-around for the dev branch.

```
$ git diff lib/galaxy/tools/actions/__init__.py
diff --git a/lib/galaxy/tools/actions/__init__.py b/lib/galaxy/tools/actions/__init__.py
index 91e2722..1dee77a 100644
--- a/lib/galaxy/tools/actions/__init__.py
+++ b/lib/galaxy/tools/actions/__init__.py
@@ -689,7 +689,8 @@ class OutputCollections(object):

             collection_type = input_collections[collection_type_source].collection.collection_type

-        if self.mapping_over_collection:
+        #if self.mapping_over_collection:
+        if False:
             dc = collections_manager.create_dataset_collection(
                 self.trans,
                 collection_type=collection_type,
```

**Comment by gregvonkuster** [comment]
I'm just now starting to stress test the above work-around, so I may discover it creates other issue.  I'll post anything I find here...

**Comment by gregvonkuster** [comment]
I spoke too soon - my complete ChIP-exo workflow still stalls before it finishes...  :(

**Comment by gregvonkuster** [comment]
Ping @jmchilton Help on this would be very much appreciated - this issue is blocking progress on the Galaxy ChIP-exo flavor.

**Comment by WilliamKMLai** [comment]
+1 on fixing this issue. It is blocking our ChIP-exo workflow pipeline. Thanks for the assistance. :-)

**Comment by blankenberg** [comment]
@jmchilton Presumably the test_first tool when run against the initial dataset collection list should be creating a list of (3) lists, in this case where each sub-list contains a single item `File1`, `File1`, and `File1`, but the contents are `line 1`, `line 2`, and `line 3`? Edit: or maybe just output 3 lists, both?

@gregvonkuster your `discover_datasets` pattern might be better as e.g. `<discover_datasets pattern="__designation_and_ext__" directory="output" visible="false" />` since the one used in the example here doesn't assign a proper datatype (although the lack of a collection output remains the same).

**Comment by gregvonkuster** [comment]
@blankenberg Thanks for taking a look at this.  Yes, this is just a dummy tool that can certainly be improved.  The tool on which I based it (and which uncovered this issue in our ChIP-exo instance) is this one:  https://github.com/galaxyproject/tools-iuc/blob/master/tools/meme/fimo.xml

**Comment by carlfeberhard** [comment]
> should be creating a list of (3) lists

@gregvonkuster can you show me (here or in a gist) what the API returns for your test history contents: `api/histories/{:history_id}/contents`

**Comment by shaunmahony** [comment]
+1 on fixing this. Thanks!

**Comment by gregvonkuster** [comment]
@carlfeberhard Here you go - thanks!

```
[
    {
        "dataset_id": "3340d4509d81c658", 
        "deleted": false, 
        "extension": "txt", 
        "hid": 1, 
        "history_content_type": "dataset", 
        "history_id": "59606d2a36c77a56", 
        "id": "40913bcf86326466", 
        "name": "Pasted Entry", 
        "purged": false, 
        "state": "ok", 
        "type": "file", 
        "type_id": "dataset-40913bcf86326466", 
        "url": "/api/histories/59606d2a36c77a56/contents/40913bcf86326466", 
        "visible": true
    }, 
    {
        "collection_type": "list", 
        "deleted": false, 
        "hid": 2, 
        "history_content_type": "dataset_collection", 
        "history_id": "59606d2a36c77a56", 
        "id": "09d8568e61ebd1d9", 
        "name": "My first collection", 
        "populated": true, 
        "populated_state": "ok", 
        "populated_state_message": null, 
        "type": "collection", 
        "url": "/api/histories/59606d2a36c77a56/contents/dataset_collections/09d8568e61ebd1d9", 
        "visible": true
    }, 
    {
        "dataset_id": "4cbca26c4377455f", 
        "deleted": false, 
        "extension": null, 
        "hid": 3, 
        "history_content_type": "dataset", 
        "history_id": "59606d2a36c77a56", 
        "id": "43b77686951b80f1", 
        "name": "FILE1.txt", 
        "purged": false, 
        "state": "ok", 
        "type": "file", 
        "type_id": "dataset-43b77686951b80f1", 
        "url": "/api/histories/59606d2a36c77a56/contents/43b77686951b80f1", 
        "visible": false
    }, 
    {
        "dataset_id": "e6b26674ddb3219d", 
        "deleted": false, 
        "extension": null, 
        "hid": 4, 
        "history_content_type": "dataset", 
        "history_id": "59606d2a36c77a56", 
        "id": "ee8cc55b8ef9e3bb", 
        "name": "FILE2.txt", 
        "purged": false, 
        "state": "ok", 
        "type": "file", 
        "type_id": "dataset-ee8cc55b8ef9e3bb", 
        "url": "/api/histories/59606d2a36c77a56/contents/ee8cc55b8ef9e3bb", 
        "visible": false
    }, 
    {
        "dataset_id": "d8e59aa87d0a50ce", 
        "deleted": false, 
        "extension": null, 
        "hid": 5, 
        "history_content_type": "dataset", 
        "history_id": "59606d2a36c77a56", 
        "id": "d6a7b515213e680c", 
        "name": "FILE3.txt", 
        "purged": false, 
        "state": "ok", 
        "type": "file", 
        "type_id": "dataset-d6a7b515213e680c", 
        "url": "/api/histories/59606d2a36c77a56/contents/d6a7b515213e680c", 
        "visible": false
    }, 
    {
        "collection_type": "list:list", 
        "deleted": false, 
        "hid": 6, 
        "history_content_type": "dataset_collection", 
        "history_id": "59606d2a36c77a56", 
        "id": "b3e4e0c76fe49b64", 
        "name": "My first collection", 
        "populated": true, 
        "populated_state": "ok", 
        "populated_state_message": null, 
        "type": "collection", 
        "url": "/api/histories/59606d2a36c77a56/contents/dataset_collections/b3e4e0c76fe49b64", 
        "visible": true
    }, 
    {
        "dataset_id": "7e6eed4b7bfe6518", 
        "deleted": false, 
        "extension": null, 
        "hid": 7, 
        "history_content_type": "dataset", 
        "history_id": "59606d2a36c77a56", 
        "id": "0240acc469c2caad", 
        "name": "FILE1.txt", 
        "purged": false, 
        "state": "ok", 
        "type": "file", 
        "type_id": "dataset-0240acc469c2caad", 
        "url": "/api/histories/59606d2a36c77a56/contents/0240acc469c2caad", 
        "visible": false
    }, 
    {
        "dataset_id": "06063ae7b135aa0f", 
        "deleted": false, 
        "extension": null, 
        "hid": 8, 
        "history_content_type": "dataset", 
        "history_id": "59606d2a36c77a56", 
        "id": "d000b35fe611f87a", 
        "name": "FILE1.txt", 
        "purged": false, 
        "state": "ok", 
        "type": "file", 
        "type_id": "dataset-d000b35fe611f87a", 
        "url": "/api/histories/59606d2a36c77a56/contents/d000b35fe611f87a", 
        "visible": false
    }, 
    {
        "dataset_id": "3dfda6d381dceb16", 
        "deleted": false, 
        "extension": null, 
        "hid": 9, 
        "history_content_type": "dataset", 
        "history_id": "59606d2a36c77a56", 
        "id": "318789a490fafad0", 
        "name": "FILE1.txt", 
        "purged": false, 
        "state": "ok", 
        "type": "file", 
        "type_id": "dataset-318789a490fafad0", 
        "url": "/api/histories/59606d2a36c77a56/contents/318789a490fafad0", 
        "visible": false
    }
]
```

**Comment by carlfeberhard** [comment]
@gregvonkuster Thanks. I should have something to get you to the next step today or tomorrow on dev.

**Comment by gregvonkuster** [comment]
@carlfeberhard Awesome - thanks!

**Comment by carlfeberhard** [comment]
@gregvonkuster you may want to try this test pipeline with #2613. It may not get you all the way there, but the display was at least part of the problem. Let me know if you have any problems with that PR, please.

**Comment by gregvonkuster** [comment]
@carlfeberhard I'm running Galaxy 16.04 and this is basically a production environment.  I'm not a git expert, so what is the best way to apply this to my environment in such a way that it will not get too screwed up?

**Comment by carlfeberhard** [comment]
That's unfortunate. I'm no git expert either and don't like advising people on how to test on a production server.

Let me be clear, tho, that, if I'm reading the above convo correctly, this is only part of your problem. This will allow you to see the list:list created on the second run of the tool in the history. **I don't believe this will solve your workflow stalling problem**. Ultimately, it may not be worth it at this point to focus on the display part of the issue.  

I can gist a patch of the base js (vs. 16.04) changes and you could call `make client` to compile them. If you'd still like that ASAP, let me know and I'll see what I can do.

**Comment by gregvonkuster** [comment]
Thanks for the advice @carlfeberhard .  What do you think will be required to get the workflow issue resolved?  Will this require @jmchilton, or someone else?

It's pretty easy to reproduce this in a workflow.  Here is one that I can use to reproduce it:
<img width="778" alt="test_first_wf" src="https://cloud.githubusercontent.com/assets/6947053/16843886/f98291d8-49b0-11e6-8592-30528e534af8.png">
The final step in the workflow will not execute, and the Galaxy paster log displays this:

```
galaxy.managers.collections DEBUG 2016-07-14 10:48:56,374 Created collection with 3 elements
galaxy.workflow.run DEBUG 2016-07-14 10:48:56,417 Workflow step 216 of invocation 7 invoked (200.499 ms)
galaxy.tools.execute DEBUG 2016-07-14 10:48:56,449 Executed 0 job(s) for tool test_first request: (15.394 ms)
galaxy.workflow.run ERROR 2016-07-14 10:48:56,464 Failed to schedule Workflow[id=48,name=Workflow constructed from history 'Test First'], problem occurred on WorkflowStep[index=3,type=tool].
Traceback (most recent call last):
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/workflow/run.py", line 163, in invoke
    jobs = self._invoke_step( step )
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/workflow/run.py", line 233, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/workflow/modules.py", line 1077, in execute
    workflow_invocation_uuid=invocation.uuid.hex
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/tools/execute.py", line 86, in execute
    params = param_combinations[0]
IndexError: list index out of range
galaxy.workflow.run ERROR 2016-07-14 10:48:56,464 Failed to execute scheduled workflow.
Traceback (most recent call last):
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/workflow/run.py", line 82, in __invoke
    outputs = invoker.invoke()
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/workflow/run.py", line 163, in invoke
    jobs = self._invoke_step( step )
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/workflow/run.py", line 233, in _invoke_step
    jobs = step.module.execute( self.trans, self.progress, self.workflow_invocation, step )
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/workflow/modules.py", line 1077, in execute
    workflow_invocation_uuid=invocation.uuid.hex
  File "/Users/gvk/work/git_workspace/galaxy/lib/galaxy/tools/execute.py", line 86, in execute
    params = param_combinations[0]
IndexError: list index out of range
```

**Comment by carlfeberhard** [comment]
@gregvonkuster difficult for me to say on that. Hopefully others can help on that part.

**Comment by gregvonkuster** [comment]
Thanks again @carlfeberhard 
When we have a fix for this, could the PRs for both it and your UI fix be applied to the 16.04 branch?

Just to clarify, in workflows this bug is restricted to a particular step where an initial tool produces a dataset collection and the following tool that accepts it as input must be written to not specifically accept an input collection.

So I think a "following" tool with this will work:

```
    <inputs>
        <param name="input" type="data_collection" collection_type="list" format="gff" label="Gff input"  />
    </inputs>
```

But a "following" tool with this will not work.

```
    <inputs>
        <param name="input" type="data" format="gff" label="Gff input"  />
    </inputs>
```

**Comment by blankenberg** [comment]
The major part of the bug appears to be that the workflow scheduling dies (https://github.com/galaxyproject/galaxy/issues/2581#issuecomment-232689767) when it tries to parse over the `list:list` (to create a `list:list:list`, in this case).

I was able to use the tool interactively on the `list:list` in collections mode, and it did create a proper `list:list:list` (not displayed, but the `list:list:list` output isn't necessarily the important part here).

Having workflows function across `list:list`s is important and likely to happen any time a workflow contains a tool that creates a `list` itself, but the workflow consumes a `list`, or has a step that creates a `list` that then eventual inputs into the tool that creates a `list`.

@jmchilton any thoughts on the workflow scheduler here?

**Comment by jmchilton** [comment]
It should work for sure - sometimes empty collections will break things - the param_combinations throwing an index error makes me think that might be the problem here - not some more fundamental issue with `list:list:list` objects. I can try to write some tests to verify greater list nesting doesn't break anything if we know the problem isn't an empty list.

**Comment by gregvonkuster** [comment]
It is definitely not an empty list causing this.  ;)

**Comment by gregvonkuster** [comment]
The problem is with the workflow framework and how it delivers a list:list to a tool, no matter what the tool produces on output.

To clarify:
In the small test workflow above, the tool in the last step will produce a list:list:list if run outside of a workflow.  The current UI now supports only list:list with @carlfeberhard fix, so the list:list:list will not be displayed.  But fixing this is not important in the short term.

The same small workflow above dies on the last step when the tool attempts to consume the list:list.  This (consuming) issue is what is blocking the ChIP-exo flavor, so fixing it is what is most critical in the short term.  None of the downstream tools in the ChIP-exo workflow produce collections, so the depth of the collection will not be greater than list:list.

**Comment by jmchilton** [comment]
I think I have a test case here - https://github.com/jmchilton/galaxy/tree/list_list_list_problem. This is important and I will fix it - but the "major" label here troubles me - workflows like this could have been attempted since 2014 and this is the first time anyone has tried it out. I'm happy, actually excited, people are exercising this functionality - but there are so many bugs that affect existing workflows today.

Update: I meant "workflow" in a broad way - but I guess it applies in the specific Galaxy way as well.

**Comment by jmchilton** [comment]
I think the problem could be described this way - the workflow should be delayed but it is not. Collections have a concept of "populated" - which specifies if their structure (element counts and identifiers) are ready to go (so a collection with queued datasets could be "populated" - as long as we know what datasets are populated).

There is a bug in this populated logic - in that it only looks at the top level. If the elements at the top level are defined - it is considered "populated". So in my test case - the list:list is created and the workflow is delayed until the list:list is created - but then it should be delayed until the list:list:list is created but it is not since the element identifiers for the top level of the list:list:list are known (it is a simple map over the list:list).

I'm not sure how to fix it - but I'll think about it and hopefully try some things tonight or tomorrow.

**Comment by blankenberg** [comment]
@jmchilton awesome. Thanks for looking into this :)

**Comment by gregvonkuster** [comment]
Thanks for looking at this @jmchilton
