### ISSUE TITLE
BAM to BigWig fails for Trackster loading

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#2582]
I have some BAM files generated using hisat2 that I am trying to load against hg20 on our local (16.04) instance. After much hackery (effectively satisfying the galaxy_packages dependency resolver) I got ucsc_tools to be resolved but now I get an error from CONVERTER_bam_to_bigwig_0:

temp.bg is not case-sensitive sorted at line 18294564.  Please use "sort -k1,1 -k2,2n" with LC_COLLATE=C,  or bedSort and try again.

The BAM from hisat2 is already sorted (the wrapper ends with samtools sort) so I do not know where this error is coming from.

**Comment by remimarenco** [comment]
@jgoecks :)

**Comment by nsoranzo** [comment]
In `lib/galaxy/datatypes/converters/bam_to_bigwig_converter.xml`, the command is:

```
bedtools genomecov -bg -split -ibam $input -g $chromInfo > temp.bg ; bedGraphToBigWig temp.bg $chromInfo $output
```

So it seems that the output of `bedtools genomecov` is not sorted as required by `bedGraphToBigWig`.

**Comment by pvanheus** [comment]
I was looking at that last night - where does $chromInfo come from? It is not an input. I notice I've got the same problem on usegalaxy.org btw.

**Comment by nsoranzo** [comment]
@pvanheus `$chromInfo` is filled in by Galaxy, converters are special tools. Anyway, not relevant for this problem.

**Comment by lparsons** [comment]
I'm running into this issue as well. I'm pretty sure it has to do with the way bedtools sorts vs. how bedGraphToBigWig sorts in relation to certain characters. Anyone have any thoughts on how to resolve it?

**Comment by lparsons** [comment]
@nsoranzo Actually, I think that the `$chromInfo` is relevant to this issue. It seems that `bedtools genomecov` outputs the bedgraph chromosomes in the order they are presented in `$chromInfo`. I believe the best way to fix this is to introduce a sort into the converter. Not sure if this should be piped, or use another temporary file. Thoughts?
