### ISSUE TITLE
Add a PUT method to api to change user's email address

### ISSUE THREAD

**Issue by moskalenko** [galaxyproject/galaxy#2589]
See https://github.com/galaxyproject/galaxy/issues/1992#issuecomment-230916667 for reference.

Thank you,

Alex

**Comment by hexylena** [comment]
Should be supported sometime since this issue was opened https://docs.galaxyproject.org/en/master/api/api.html#galaxy.webapps.galaxy.api.users.UserAPIController.update

**Comment by moskalenko** [comment]
Excellent. Thanks for the update.
