### ISSUE TITLE
Composite Datatype upload panel needs text fix on buttons

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#2591]
![utvalg_920](https://cloud.githubusercontent.com/assets/458683/16657210/2dbb2308-4451-11e6-82e7-7db9af2dae07.png)

**Comment by martenson** [comment]
@erasche please share your env
![screenshot 2016-07-07 10 49 24](https://cloud.githubusercontent.com/assets/1814954/16657441/8848b6bc-4430-11e6-91e9-0d2ad6bf87d0.png)

**Comment by nsoranzo** [comment]
I can see the same of @erasche on Chrome 51.0.2704.106 under Ubuntu 14.04.4.

**Comment by hexylena** [comment]
@martenson 

![utvalg_921](https://cloud.githubusercontent.com/assets/458683/16657769/2d642c04-4453-11e6-885d-9dde64536853.png)

**Comment by hexylena** [comment]
I'm assuming resolution dependence? 1366x768

**Comment by martenson** [comment]
@erasche I meant OS and browser versions, resolution should not matter because the view does not change when I resize.

I am on chrome Version 51.0.2704.103 (64-bit) on MacOS and fine.

**Comment by guerler** [comment]
I could not reproduce it locally either yet. Thanks for reporting it.

**Comment by hexylena** [comment]
| Key | Value |
| --- | --- |
| Google Chrome | 51.0.2704.103 (Offisiell delversjon) (64-bit) |
| Version | aa7c8d23c098e96a388ffedf6698230bda650bb3-refs/branch-heads/2704@{#723} |
| OS | Linux |
| Blink | 537.36 (@aa7c8d23c098e96a388ffedf6698230bda650bb3) |
| JavaScript | V8 5.1.281.65 |
| Useragent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36 |

**Comment by sszakony** [comment]
Some additional information... this occurs on Chrome and Safari, but Firefox doesn't exhibit the width problem.

**Comment by martenson** [comment]
@sszakony what OS?

**Comment by davebx** [comment]
Chromium also has incorrect rendering.

**Comment by martenson** [comment]
So it seems that the troublesome combination is Linux+Chrome. @sszakony I cannot reproduce it on Safari, do you have like Safari in Wine on Linux or something? :)

**Comment by martenson** [comment]
FF on Linux also exhibits bad behavior (arrow on a different line than text although text is not broken in two)

**Comment by martenson** [comment]
xref #2703

**Comment by dannon** [comment]
This was closed in #2703
