### ISSUE TITLE
Galaxy user ids too restrictive for LDAP integration

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/galaxy#2593]
With our server, user authentication is provided by an external LDAP server. While things work from an architectural point of view, there are some restrictions on galaxy user IDs that are quite problematic with existing LDAP servers. For example user ids in LDAP can have underscores, but not on Galaxy.

This can be an issue with pluging galaxy to existing Single-Sign On infrastructure

**Comment by tiagoantao** [comment]
Sorry, where I said user id, I meant user name
so a user name of
aa_bbb will not work, but a user name of aabbb will work fine

**Comment by hexylena** [comment]
@tiagoantao are there any other issues with integration, or just the underscore issue? If so we could rename the issue appropriately.

**Comment by tiagoantao** [comment]
@erasche Just renamed it, but note that in general it is not only underscores

**Comment by hexylena** [comment]
@tiagoantao could you provide other examples of issues? This should be easy to correct, just want to fix all the issues at once :)

**Comment by tiagoantao** [comment]
According to the standard, any Unicode (UTF-8) character should be admissible, but I have read somewhere that non-ASCII should be rejected. It is not totally clear to me.

See e.g. http://www.alvestrand.no/objectid/1.3.6.1.4.1.1466.115.121.1.15.html or http://www.zytrax.com/books/ldap/apa/types.html

So, I do not know what would be a wise suggestion here. But at the very least the usual characters that you see on unix user ids. I suspect spaces might also be possible with Active Directory stuff (but I am not sure)

**Comment by nsoranzo** [comment]
@tiagoantao This has been fixed in `dev` branch (future release_16.10) for the '.' and '_' characters, feel free to open a new issue if you need more!
