### ISSUE TITLE
Upload is problematically padding spaces to tabs when number of pasted columns varies

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2602]
**Example text pasted into Upload tool form. The gear option "Convert spaces to tabs" was used.**

> line 1  A   B   C
> line 2  A   B   C   D
> line 3  A   B   C   D   E   F   G   H
> line 4  A   B   C   D   E   F   G   H

**Result: Note that the first two lines do not have columns padded. And was auto-detected as pileup instead of tabular?**

<img width="323" alt="screen shot 2016-07-11 at 8 35 11 am" src="https://cloud.githubusercontent.com/assets/8999735/16736584/7230ebd2-4742-11e6-94a6-88deea9d52c3.png">

<img width="238" alt="screen shot 2016-07-11 at 8 38 49 am" src="https://cloud.githubusercontent.com/assets/8999735/16736697/019b990c-4743-11e6-84d6-c465e10f4daf.png">

Using "Convert delimiters to TAB" after upload on this file does not repair it: the columns are not padded. Upload it again with no trailing whitespace does not resolve the issue (should the upload tool automatically strip trailing whitespace for all pasted text?). Rearranging the lines so that a longer one is first does not resolve. Uploading the same data from a text file does NOT work if the option to convert spaces > tabs is used/not used. 

I cannot find a way to load tabular variable-column data correctly. This kind of file could only be created by tools directly - and those I tested that perform manipulations after (correctly formatted) either 1) do not interpret all dataset lines well or 2) take correctly formatted input columns but output these incorrectly (see last Concatenate run - d20).

Updated testing history includes the annotated examples: 
 https://usegalaxy.org/u/jen/h/yet-another-copy-of-copy-of-tabular-data-test  

More information https://biostar.usegalaxy.org/p/18422

**Comment by jlparmley** [comment]
Hi, this is a ticket that has been linked to one of my own.
In our own work we have discovered similar bugs, and in our case it turns out to be an issue with split functions. 
I know that Galaxy is Python based, but I think the following is common to several languages. 

In Groovy (Java) if you were to split the first line above into a list, you would lose the empty strings relating to the end of the string if you use the following code:

list = string.split("\t")

However, you can specify that the trailing empty strings should be used by giving a range to the split:

list = string.split("\t", -1) will make sure that the whole line is maintained and not trimmed of empty strings. 

This may be the issue here, as my ticket was not related to the upload tool, but has similar behaviour of loss of trailing whitespace. If there are instances of splitting and joining to upload files or in my ticket, in the comparison tool then maybe this could be a cause?

Many thanks

**Comment by jennaj** [comment]
@dannon Thoughts?

**Comment by dannon** [comment]
@jennaj I looked into this a bit and I think the first problem is merely a display issue.  On the back end, it is actually converting spaces to tabs.  I don't have a _fix_ for the display issue yet, but I think tools will consume this dataset correctly.

**Comment by dannon** [comment]
@jennaj I've changed the tabular display in #2845 to render individual cells in this situation, correctly separating them into tabs.  Previously, it was following the 'comment line' logic in these situations, making that assumption because of the number of columns on the line.

**Comment by dannon** [comment]
@jlparmley Do you have an example of something I can test to see if this would resolve the issues you're observing that are similar to this?

**Comment by jlparmley** [comment]
@dannon Thanks for looking into this. There is an example on my original ticket here:
https://biostar.usegalaxy.org/p/18422/
Is this enough, or would you like more information?

**Comment by jennaj** [comment]
@dannon @jlparmley In the example history I provided (initial report, but also here: https://usegalaxy.org/u/jen/h/yet-another-copy-of-copy-of-tabular-data-test) tools were consuming the data poorly (and failing) .. so I am not sure if this is limited to display. Dannon, perhaps test with both in your dev environment? Then once there is a working solution and the fix is on Test, I can do a retest on that server before we push to Main, to determine if the solution works with tool usages (text mani, etc). Thanks!!

**Comment by dannon** [comment]
@jlparmley Your problem from the biostar ticket looks like a bug specifically in the compare tool, to me, and I'll hopefully have a fix soon.

@jennaj I think the convert tool issues you're seeing are a _different_ problem, which was compounded by the display issues I fixed in #2845.

**Comment by jennaj** [comment]
@dannon Thanks for looking into this. I see that the fix is for 16.10. Could we update Test with your fix now and then I can test it out with tools there. Thanks!

**Comment by jlparmley** [comment]
@dannon I was wondering if you have any news about the other issue above, or if there is a different thread to follow for it now? Many thanks

**Comment by jennaj** [comment]
@dannon @jlparmley 

9-3-16 update: 

Testing on Test is a PASS for all three issues (upload, cat, convert with mixed length tabular data). It would be better if autodetect gave these the datatype "tabular" instead of "pileup" but that is another issue (here https://github.com/galaxyproject/galaxy/issues/3001). https://test.galaxyproject.org/u/jenjackson/h/tabspace-issue-testing

Test re-runs in original shared history shows that all three are still failing at http://usegalaxy.org. https://usegalaxy.org/u/jen/h/yet-another-copy-of-copy-of-tabular-data-test

Test rerun d20 is in d21 (cat) - fail
Test re-run d2 is in d22 (upload) - fail
Test re-run d16 in in d23 (convert) - fail

**Comment by jennaj** [comment]
This was fixed long ago, sorry for the delay in closing. Catching up on smaller retests!
