### ISSUE TITLE
Cannot copy history from saved history list when filtered by search or viewing by page or all

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#2624]
Experienced on 16.04 and newer (probably 16.01 as well).

Steps:
- Click history options -> saved histories
- You can click the dropdown for a history and Copy. A popup will appear. Hover link is `javascript:void(0)` [don't worry about actually doing the copy]
- Use the search box to search
- Now try to copy a history. 

The hover link is no longer javascript and the direct copy operation was removed in https://github.com/galaxyproject/galaxy/pull/1303 (although the link is still generated for it). The page just refreshes to the first page of the filtered history list; forgets 'all' or current page.

I also lose the javascript attachment for the Copy action when just clicking to view a different page or all.

Currently the only way to copy a history that is not in the first page is to switch to it and copy from the history options; this can be a pain especially for large histories.

**Comment by dannon** [comment]
+1, fixes it for me (side note, looks like it actually used to work, at least in firefox, if you just did the 'copy' action twice, which is maybe why we didn't hear about it more)

Edit:  This is not the PR.  Closing at #2629
