### ISSUE TITLE
add a tar datatype which won't be extracted

### ISSUE THREAD

**Issue by mariabernard** [galaxyproject/galaxy#2635]
Hi everyone,

Sorry for the plagiarism @lecorguille but you know me enough.

A month ago I added a comment on the issue opened by @lecorguille ( https://github.com/galaxyproject/galaxy/pull/1665 ) to add a tar datatype, same as him for the zip datatype. It was maybe not the best way to report my issue, so I opened a new one here, and paste my previous comment (sorry to insist)
###### ##############"

I have a similar situation as @lecorguille with the tar archive (or tar.gz). Last year we developped a tool for uploading a tar archive into galaxy (for our old version 15.10) , see : https://github.com/geraldinepascal/FROGS/tree/master/tools/upload

But this tool is not more working on the almost last version 16.01.

I made same corrections as @jmchilton https://github.com/galaxyproject/galaxy/pull/1665/commits/b81f3149bfb624b26e84c95b4efd519850045981 for tar archive and it's working very well.

Your are maybe not instersting to add all kind of archive type as galaxy datatype, but tar would be very appreciated. Would it be possible to add it in the dev and future master branch ?
Or do you think to add a common archive datatype as mentionned by @bgruening ?

Thank you for your help.

Best regards

Maria Bernard

**Comment by bgruening** [comment]
Hi Maria,

I responded on github. But essentially there is a generic
compressedArchive datatype.

https://github.com/galaxyproject/galaxy/blob/master/config/datatypes_conf.xml.sample#L186

Hope this helps,
Bjoern

Am 20.07.2016 um 08:43 schrieb mariabernard:

**Comment by mariabernard** [comment]
Hi,

Yes it works, sorry for that. I was trouble by the specific "CompressedZipArchive" so I thought it would be the same for Tar.

Would it be possible to add tar datatype line in the datatypes_conf.xml.sample in future version of Galaxy ?
`<datatype extension="tar" type="galaxy.datatypes.binary:CompressedArchive" subclass="True" display_in_upload="True"/>`

Thank you for your help

Maria

**Comment by bgruening** [comment]
You can try to get a PR in Galaxy with this additional feature :)

**Comment by mariabernard** [comment]
ok, thank you!

**Comment by lecorguille** [comment]
@mariabernard What a shame, you copy me! 😄 
If you need help on this PR, just ping me. 
And good luck, Maria! You should need some if we interprete the "You can try" of Björn 😝 
A plus 🇫🇷

**Comment by bgruening** [comment]
> And good luck, Maria! You should need some if we interprete the "You can try" of Björn 😝 

:smile: no intention from my side!

**Comment by lecorguille** [comment]
https://github.com/galaxyproject/galaxy/pull/1665 is merged
@mariabernard You can now close this issue
