### ISSUE TITLE
Pin flake8 in tox.ini so older Galaxies don't break in CI

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#2665]

**Comment by nsoranzo** [comment]
It would be good to also update the `RELEASE_ISSUE_TEMPLATE` in `scripts/bootstrap_history.py` to add a point to the release checklist to pin flake8 at branch time.

**Comment by nsoranzo** [comment]
Fixed for releases 16.01 to 16.07 in commit f4cb63d6f27f68814bd6131f43c1eee6fa8d099e .
