### ISSUE TITLE
External Auth + impersonate logout

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#2671]
Unable to deactivate impersonate.  This used to work and is a new regression.  Reported on galaxy-dev by Ryan G.

http://dev.list.galaxyproject.org/possible-bug-found-unable-to-log-out-of-impersonated-user-when-external-authentication-enabled-td4669752.html for the mailing list thread

**Comment by dannon** [comment]
I've tried to reproduce this and had to request more information on the mailing list.  This seems to be working fine with my local setup.

Anyone else?

**Comment by sszakony** [comment]
I am also unable to duplicate this on my pre-production server (16.04).
