### ISSUE TITLE
Error when building local galaxy

### ISSUE THREAD

**Issue by ZB2016** [galaxyproject/galaxy#2676]
1
<img width="672" alt="screen shot 2016-07-27 at 2 39 24 pm" src="https://cloud.githubusercontent.com/assets/17168831/17189649/05f87b88-5408-11e6-9c2e-73295e82e233.png">
2
<img width="702" alt="screen shot 2016-07-27 at 2 45 08 pm" src="https://cloud.githubusercontent.com/assets/17168831/17189798/c7751e38-5408-11e6-92b2-027e5e96e9d9.png">

The run.sh script failed to build wheel for mercurial and pysam. It seems that pip tries to install the newest package while the up-to-date pysam package is not compatible with python2.7(because the command line 'pip install pysam'  worked fine when the environment was python3.5 and report error when I tried to do the same thing on python2.7 env ). For the problem with mercurial, I have no idea.

I'm using mac(OS X EI Capitan Version 10.11.5). All I do was:
1. git clone https://github.com/galaxyproject/galaxy/
2. cd galaxy
3. pyenv local 2.7
4. git checkout -b master origin/master
5. sh run.sh
exactly the instruction of galaxy wiki page

**Comment by nsoranzo** [comment]
@ZB2016 Thanks for the bug report! Can you start from scratch (remove your `galaxy/` dir) and repeat the above steps, but skipping point 3? I don't think pyenv is mentioned anywhere in the [wiki](https://wiki.galaxyproject.org/), in fact Galaxy uses [virtualenv](https://virtualenv.pypa.io/) and creates its own virtual environment automatically when you execute `run.sh` for the first time.

**Comment by ZB2016** [comment]
@nsoranzo My global environment is Python 3.5.1 :: Anaconda 2.5.0 (x86_64). The virtualenv settings in galaxy doesn't automatically download or change the environment to python 2.7, right? If I run the command line directly, the error is

>  'Traceback (most recent call last):
>   File "./scripts/check_python.py", line 17, in check_python
>     assert sys.version_info[:2] == ( 2, 7 )
> AssertionError'

So I need to change the version of python myself. In fact I also tried the following:

> 1. mkdir galaxy-python
> 2. pyenv local 2.7
> 3. git clone https://github.com/galaxyproject/galaxy/
> 4. cd galaxy
> 5. git checkout -b master origin/master
> 6. sh run.sh

It set up the python version outside the galaxy folder. Still, the same error happened.

The following file gives detail about where the errors are reported when run 'sh run.sh' command.
[Error detail.pdf](https://github.com/galaxyproject/galaxy/files/388743/Error.detail.pdf)
As you can see, other packages are successfully installed except pysam and mercurial.

In fact, I did see mecurial after all these error happened. That was confusing.

> dhcp-10-105-158-117:galaxy Zhiheng$ pip freeze
> bx-python==0.7.3
> MarkupSafe==0.23
> mercurial==3.8.4
> PyYAML==3.11
> SQLAlchemy==1.0.8
> dhcp-10-105-158-117:galaxy Zhiheng$ pip install mercurial
> Requirement already satisfied (use --upgrade to upgrade): mercurial in /Users/Zhiheng/.pyenv/versions/2.7/lib/python2.7/site-packages 

What I did to check(as mentioned before) was running 'pip install pysam' in 'Python 3.5.1 :: Anaconda 2.5.0 (x86_64)' env and 'Python2.7' env.  This command line worked on python3.5 while report error on python2.7.

**Comment by ZB2016** [comment]
@nsoranzo  It works well on Linux on another computer... I guess there might be some compatibility issue with my mac. Anyway,it not really a bug, but I appreciate it if you can provide any help.

**Comment by martenson** [comment]
@ZB2016 Could you please share a gist of your whole startup log? (eg in https://gist.github.com)

edit: please delete the .venv/ and clear the pip cache before you do the startup to get the log that might help

**Comment by mvdbeek** [comment]
@ZB2016 the easiest way would be to deactivate your conda environment, and then running galaxy. You can do this with `deactivate`. Then type `python --version`. If you don't see `Continuum Analytics, Inc.` you should be good to go.

**Comment by nsoranzo** [comment]
New pysam 0.15.1 wheels for macOs are now available at https://wheels.galaxyproject.org/ (which is used by `./scripts/common_startup.sh` as the primary wheel repository).
