### ISSUE TITLE
Pagination skips elements upon delete/hide

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#2707]
Delete N items from page 1 of a history, then go to the second page of the history, N items will have been skipped because of the way the deleted/hide + offsets logic interacts currently.

Concretely, in this example history I have, the last hid is 526, first item in page 2 is 525.  From page 1, delete 2 items, then go to page2, and note that 525, 524 are not there.  Go back to page 1 and there they are.

**Comment by martenson** [comment]
Happy second anniversary, bug! 🎉 We might squish you for 18.09 though 🐛 !

**Comment by mvdbeek** [comment]
Guess we can close this now that we have the beta history panel and we're not going to do more work with the old panel.
