### ISSUE TITLE
History iteration

### ISSUE THREAD

**Issue by carlfeberhard** [galaxyproject/galaxy#2709]
- [ ] bug: searching in multipanel doesn't immediately re-render (10/10)
- [ ] bug: loss of one history in multipanel list
- [ ] bug: parameter walking broken when moving off the current page of datasets
- [ ] bug: loss of droptarget in multiview after first drop and too much space above drop target when visible
- [ ] #2707 
- [ ] remove deprecated elements
- [ ] Bjoern's feedback from iteration 1: #2588 
- [ ] possible collapsing of history header

**Comment by hexylena** [comment]
Most of these are now fixed in multi-history view, or will be fixed in #8441
