### ISSUE TITLE
No PID file exists in paster.pid

### ISSUE THREAD

**Issue by victorylin** [galaxyproject/galaxy#2724]
deploy the lastest galaxy version to EC2 Ubuntu VPS.

$useradd -m -s /bin/bash galaxy

$sh run.sh --daemon

Activating virtualenv at .venv
No PID file exists in paster.pid
Could not stop daemon
Entering daemon mode

But the server was launched in fact, i can access the site through http://127.0.0.1:8080

what is the problem?

**Comment by sszakony** [comment]
I see this as well, using the latest version on RedHat 6.7.

**Comment by nsoranzo** [comment]
I've fixed this in #2765, which is only available in the `dev` branch. I will backport it.
