### ISSUE TITLE
Code Files / Retrieving a Dynamic List of Files / Directories

### ISSUE THREAD

**Issue by hrhotz** [galaxyproject/galaxy#2725]
One of our use cases for the code tag is uploading the sequences of sanger sequencing reads:

The sequencing is done externally, and the data is dumped into group specific folders, with subdirectories by year and run on our central storage system.

Our local upload tool works like this:
- 1. a list with all groups is dynamically generated. The user selects a group and a year
- 2. based on the selected group and year, all runs from that group from that year are listed. The user selects a run
- 3. based on the selected run, all sequences are listed. The user selects one or more sequences

**Comment by hrhotz** [comment]
let me add my own comments, just to clarify:
- I use this trick for several local upload tools
- I am looking into ways of auto-generating data libraries, which will eventually make this trick obsolete. However, despite the recent improvements, I still think the the UI for the data libraries is not very user friendly, especially, when you have a lot of data libraries - IMHO

**Comment by hexylena** [comment]
(rolled into main issue)
