### ISSUE TITLE
Add additional Jenkins build slave(s)

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#2736]
To reduce the load on leeroy and increase the number of concurrent workers we can have.

Ping @martenson @jmchilton

**Comment by natefoo** [comment]
`n4.galaxyproject.org` is now installed and minimally set up for this purpose. jenkins@leeroy can now ssh to n4 as the jenkins user. Changes in galaxyproject/infrastructure-playbook@7b9d8254aa93aac7821dfd0fba84b6e3d4a1cc7e

**Comment by natefoo** [comment]
Oh and jenkins can run docker on n4.

**Comment by martenson** [comment]
yahoooo!!

**Comment by natefoo** [comment]
Are you gonna work on the Jenkins side of this? I can maybe do it but I don't really know my way around Jenkins so well. =)

**Comment by martenson** [comment]
maybe :)

**Comment by martenson** [comment]
@natefoo 

```
jenkins@leeroy:~$ ssh jenkins@n4.galaxyproject.org
no such identity: /var/lib/jenkins/.ssh/id_rsa_slave: No such file or directory
jenkins@n4.galaxyproject.org's password:
```

**Comment by martenson** [comment]
@natefoo please install java on n4

**Comment by martenson** [comment]
@natefoo please install `make` on n4

**Comment by martenson** [comment]
@natefoo please make n4 be able to rsync the same way n3 can

```
+ rsync -avr doc/build/html/ docs@delirium.galaxyproject.org:/srv/nginx/docs.galaxyproject.org/root/en/latest/
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]
```

**Comment by natefoo** [comment]
Ok, this should work now

**Comment by martenson** [comment]
it did, yay!

**Comment by martenson** [comment]
we should be good now
