### ISSUE TITLE
Scratchbook shouldn't consume login dialog

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#2747]
As an anonymous user, enable scratchbook.  Then click user->login.  The center pane content ends up getting shunted into a scratchbook block, and it should not.  Minor bug, but a bug.

Talking to @guerler, this affects any link in the masthead, but should be made much more concise.

**Comment by guerler** [comment]
Fixed with https://github.com/galaxyproject/galaxy/pull/2808
