### ISSUE TITLE
Add "Data Export" category to MTS and TTS

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#2775]
For https://github.com/TGAC/earlham-galaxytools/blob/master/tools/export_to_cluster/export_to_cluster.xml

**Comment by martenson** [comment]
@nsoranzo 

https://testtoolshed.g2.bx.psu.edu/repository/browse_repositories_in_category?id=faf52b7a99ec14da

https://toolshed.g2.bx.psu.edu/repository/browse_repositories_in_category?id=fafc098a908feea9

**Comment by nsoranzo** [comment]
Thanks a lot @martenson!
