### ISSUE TITLE
ImportError: No module named migrate.versioning.shell

### ISSUE THREAD

**Issue by matthdsm** [galaxyproject/galaxy#2793]
Hi

I'm trying to update our local galaxy installation from 16.04 to 16.07. However, this requires a database upgrade. When I try to run manage_db.sh I get the following error:

```
[galaxy] galaxy:galaxy-dist $ bash ./manage_db.sh                                                                                                  [10:26:42]
Traceback (most recent call last):
  File "./scripts/manage_db.py", line 7, in <module>
    from migrate.versioning.shell import main
ImportError: No module named migrate.versioning.shell
```

Any idea why? Is could there be something missing in my `$PYTHONPATH`?

Thanks!
M

**Comment by mvdbeek** [comment]
The syntax for calling manage_db.sh is

```
sh manage_db.sh -c ./config/galaxy.ini upgrade
```

You should get these instructions when you start run.sh after switching to 16.07,
but we should definitely fail the script with a reasonable error message in case required parameters are mising.

**Comment by nsoranzo** [comment]
@matthdsm You have some problem with your Python virtual environment, the failing import is from `sqlalchemy-migrate` which should be in your virtualenv. If your virtualenv is in a directory different from the default `.venv`, then you need to export the `GALAXY_VIRTUAL_ENV` environment variable before running the script.

```
$ export GALAXY_VIRTUAL_ENV=my_venv
$ sh manage_db.sh
Activating virtualenv at .venv
Usage: manage_db.py COMMAND ...
```

**Comment by matthdsm** [comment]
Thanks @mvdbeek  and @nsoranzo for your time. The issue is that our galaxy doesn't run in a venv, but in a conda env, which already has sqlalchemy installed. I've used pip to install sqlalchemy-migrate into the galaxy conda env. Everything is up and running now.

Thanks a lot!
M
