### ISSUE TITLE
Bug: `AttributeError` in `shed_util_common.can_eliminate_tool_dependency`

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#2796]
When attempting to update tools to new revisions, `shed_util_common.can_eliminate_tool_dependency` throws an exception on line 109: `AtributeError: 'list' object has no attribute 'get'`

Full stacktrace at: https://gist.github.com/lparsons/3937cce0ea8f942a1fe4bca391b027d6

Originally uncovered in https://github.com/galaxyproject/tools-iuc/issues/905

**Comment by nsoranzo** [comment]
Duplicate of #2111, should be fixed by #2116, which probably needs to get backported. What version of Galaxy are you using?

**Comment by lparsons** [comment]
Using 16.04.
