### ISSUE TITLE
error in authentication with Apache LDAP server

### ISSUE THREAD

**Issue by ieguinoa** [galaxyproject/galaxy#2805]
Hi, 

just came up with a problem while trying to authenticate using ldap. I get this error:

```
 File "/galaxypsb/src_dev/lib/galaxy/auth/providers/ldap_ad.py", line 167, in authenticate
    whoami = l.whoami_s()
  File "/galaxypsb/src_dev/miniconda/envs/galaxy/lib/python2.7/site-packages/ldap/ldapobject.py", line 596, in whoami_s
    return self._ldap_call(self._l.whoami_s,serverctrls,clientctrls)
  File "/galaxypsb/src_dev/miniconda/envs/galaxy/lib/python2.7/site-packages/ldap/ldapobject.py", line 99, in _ldap_call
    result = func(*args,**kwargs)
PROTOCOL_ERROR: {'info': 'unsupported extended operation', 'desc': 'Protocol error'}
```

The problem is that in ldap_ad.py (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/auth/providers/ldap_ad.py), after setting up the connection, Galaxy calls whoami_s() to check it (I guess this was added for debugging purposes only), but apparently it is not implemented in all type of servers. In my case commenting the lines associated with that function gets ldap working. Not sure how general is this problem (I guess it works fine with other auth servers) but it may be of interest for others using same server as me.

cheers,
Ignacio

**Comment by nsoranzo** [comment]
@ieguinoa Thanks for your report! This check was not added for debugging, but because some LDAP servers allow anonymous bind, letting a user login with a valid username/email and an empty password, see commit 2a1b2dbb5ae83b3c6b7d4360a674432698e216da .

Can you try this patch and tell us if it works for you? https://gist.github.com/nsoranzo/d7f9c0e5a909399b20ac04686c502135

**Comment by ieguinoa** [comment]
@nsoranzo  Thanks for the quick reply. Just tested the patch in the dev branch and works perfectly.

**Comment by nsoranzo** [comment]
@ieguinoa Thanks for the feedback! Are you running [ApacheDS](https://directory.apache.org/apacheds/)? Because that seems to have support for the "Who Am I?" extended operation since version 2.0.0-M17 (released in 2014).
