### ISSUE TITLE
BUG: AttributeError Exception when running workflow that includes a tool that consumes a collection

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#2806]
Running this workflow consistently generates an exception.

Workflow: https://gist.github.com/lparsons/22c019a295ede562ee8583e44718170a

Exception: https://gist.github.com/lparsons/6962086d8a8c02d46b3857d8b0ad0441

`AttributeError: 'HistoryDatasetAssociation' object has no attribute 'dataset_instance'`

**Comment by lparsons** [comment]
Unfortunately, I'm still seeing this on version 16.07. Is there anything I can do to help troubleshoot for this?

**Comment by jmchilton** [comment]
It is nearly impossible to visualize these JSON files - can you post a screenshot also?

**Comment by jmchilton** [comment]
Does that last step with the input:

```
<param name="inputs" type="data" label="Input .bam File(s)" format="bam" help="(--input-file)" multiple="true"/>
```

Have a single dataset or a list of datasets going into it?

**Comment by lparsons** [comment]
Sure, here's a link to screenshot: http://i.imgur.com/rlKm0k8.png

Not sure which step you're referring to...

**Comment by lparsons** [comment]
Ahhh... Yes, that's the XML from the `genebody_coverage.xml` tool. Yes, that has a list going into it.

**Comment by jmchilton** [comment]
@lparsons - can you try cloning the workflow, deleting that step and running the result workflow?

**Comment by lparsons** [comment]
@jmchilton - sure, I did that and it ran without issue.

**Comment by jmchilton** [comment]
Does that tool run on the outputs on its own now (outside a workflow) - it looks like this is a exception in the exception handling is why I ask?

**Comment by lparsons** [comment]
Yes, it runs find on a list outside of a workflow. (and yes, on those same outputs).

**Comment by jmchilton** [comment]
Did this happen prior to 16.07 also?

I'd guess something is getting double wrapped with these Galaxy wrapper objects, if that is the case the following patch may help https://gist.github.com/jmchilton/5cba0e67744f02148dcb16d5dc3f2743.

**Comment by lparsons** [comment]
Yes, this happened on 16.04 as well (not sure about before that). I'll try out the patch and see what happens.

**Comment by lparsons** [comment]
@jmchilton - that seemed to fix it... Though now I get a proxy error due to a timeout issue (takes too long to create all the jobs, but they get created.
