### ISSUE TITLE
Editing of reference genome selection in workflow running interface does not work

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#2827]
Clicking on the edit icon does nothing:

![screen shot 2016-08-22 at 10 02 00 am](https://cloud.githubusercontent.com/assets/4291636/17857412/a7015878-684f-11e6-963b-cf494e077eb0.png)

**Comment by gregvonkuster** [comment]
xref https://github.com/galaxyproject/galaxy/issues/1881

**Comment by guerler** [comment]
This has been fixed with the new run workflow form in dev.
