### ISSUE TITLE
Bug: View workflow svg before installing from toolshed seems broken

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/galaxy#2833]
So let's assume I'm interested in installing a workflow from the galaxy tool shed. I open the toolshed from the admin panel and find @bgruening's nice workflows. I click on it and it brings me to this page:

<img width="1420" alt="screen shot 2016-08-22 at 12 39 44 pm" src="https://cloud.githubusercontent.com/assets/2761597/17862980/b40322ca-6865-11e6-947e-392e24bed44b.png">

I'm interested in the workflows and I see the message `Workflows - click the name to view an SVG image of the workflow`. I click the name, and get an empty page. (Note: I've tried a couple different workflow repositories, so I'm pretty sure this is not unique to this one repo of workflows)

Can you reproduce this? 

I'm running Bjoern's docker image (from a couple days ago) on an Ubuntu 14.04 VM.

**Comment by hexylena** [comment]
Installing workflows from the toolshed is not the current best practice or easy to do, and the community mostly shares workflows on GitHub. I'm sorry, it's unlikely anyone finds time to fix this if it hasn't been already.
