### ISSUE TITLE
Tophat may produce output datasets with problematic metadata. Tested at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2838]
Issue: The Jetstream cluster may produce output datasets with problematic metadata. 

Tools: Tophat and potentially others

Current workaround: Expand the dataset by clicking on the name and reset metadata with the link provided in the yellow box. 

Complete resolution pending by @natefoo

**Comment by jmchilton** [comment]
From a developer perspective - I believe this is a problem with tool that produce outputs with metadata files when using Pulsar and remote metadata calculation.

**Comment by natefoo** [comment]
@jmchilton Correct

**Comment by jennaj** [comment]
Closing, tool is being deprecated. Use HISAT instead.
