### ISSUE TITLE
BWA-MEM default options produces BAM that fails ValidateSamFile at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2846]
ValidateSamFile needs tuning?

**Tools** 
- Map with BWA-MEM - map medium and long reads (> 100 bp) against reference genome (Galaxy Version 0.7.12.1)
- ValidateSamFile assess validity of SAM/BAM dataset (Galaxy Version 1.136.0)

**Options**
- BWA-MEM = Paired-end, hg19 native, remainder defaults
- ValidateSamFile = Summary mode, only report errors and ignore warnings= true, remainder defaults

**Failure report**

> ## HISTOGRAM  java.lang.String
> 
> Error Type    Count
> ERROR:HEADER_RECORD_MISSING_REQUIRED_TAG  1
> ERROR:INVALID_TAG_NM  23
> ERROR:MISSING_PLATFORM_VALUE  1

**Failure if Verbose is used instead for just ERROR:HEADER_RECORD_MISSING_REQUIRED_TAG**

> ERROR: File /galaxy-repl/main/files/XXX/XXX/dataset_XXX.dat, Error parsing SAM header. @RG line missing SM tag. Line:
> @RG   ID:XXX

**Comment by mvdbeek** [comment]
If still relevant it's a tool issue.

**Comment by jennaj** [comment]
I'll retest and open a ticket in the tools repo if still a problem. Thanks!

**Comment by jennaj** [comment]
Pass -- Version 2.18.2.1 tested at usegalaxy.org with HISAT2 (mm10 native index) && BWA-MEM (custom genome fasta). Test history in case we need it again: https://usegalaxy.org:/u/jen/h/test-validatesamfile
