### ISSUE TITLE
Galaxy framework dependencies using conda.

### ISSUE THREAD

**Issue by ieguinoa** [galaxyproject/galaxy#2867]
Hi everybody, Im writing to report some problems Im finding in v16.07 while using conda for both framework and tool dependencies.
I first tried to follow the instructions in https://docs.galaxyproject.org/en/master/admin/framework_dependencies.html to install the environment using pinned requirements.
After creating ( conda create --name galaxy --file lib/galaxy/dependencies/conda-environment.txt)  and activating the environment, I just tried to run galaxy the standard way using run.sh with no extra parameters. The runner correctly detects that I'm using conda so it does not install venv and does not replace pip (therefore using pip from conda env). I then get the following error:
Found existing installation: requests 2.11.1
    Uninstalling requests-2.11.1:
      Successfully uninstalled requests-2.11.1
  Found existing installation: requests-toolbelt 0.5.0
Cannot remove entries from nonexistent file /home/ieguinoa/galaxy/miniconda2/envs/galaxy/lib/python2.7/site-packages/easy-install.pth

As far as I know the problem here is with conda's pip installation (more information in https://github.com/ContinuumIO/anaconda-issues/issues/542).
My workaround was to run pip with --ignore-installed to install requirements.txt and then run.sh --skip-wheels. This works for preinstalling but cannot be used inside run.sh because otherwise every time I restart the server it will reinstall all the requirements.

Once I managed to get all the requirements working I found a problem associated with conda's tool dependencies. The tool_script.sh created to run the tool activates the environment that contains the tool dependency, but the problem is that conda's activate 'bin' also deactivates any previous environment that is loaded. This is clearly in line with the idea of switching environments in conda  but in the case we are running a base env with all the galaxy framework requirements then it will definitely crash the whole run. 
My simple workaround was to just remove the line in conda activate script that deals with the deactivation of previous environment:
source "$_CONDA_DIR/deactivate".
Since Im running jobs in a cluster this fix works quite well because env vars are set and unset for just that execution but a cleaner solution would be to deactivate the environment used after running the job. 

Hope to get some feedback on these issues to be sure I'm making the right changes.
Best,
Ignacio

**Comment by hexylena** [comment]
The installation using conda for dependency has changed significantly in the intervening time, I imagine it works better now.
