### ISSUE TITLE
Beta API tool installation improvements

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2873]
xref: #2769 and #2823
@davebx 
- [x] The interface lists all repositories of a given category, including the empty/invalid ones which cannot be installed - attempting so results in the following error:
  `
  VM1808 browse_toolsheds:541 Uncaught TypeError: Cannot read property     'includes_tools_for_display_in_tool_panel' of undefined
  `
- [x] Need to modify the search box to plug in whoosh searching
- [x] Remove duplicated text.
- [x] Show a preview of the tool form when clicking the button in the screenshot below.
- repo install page (bugs red, ideas blue)
  ![repo_install](https://cloud.githubusercontent.com/assets/1814954/18098353/ede74fac-6eaf-11e6-87a6-3ddc46224504.png)

**Comment by martenson** [comment]
Also we should deploy this on TTS and test intensively. We can push this out of Beta for 16.10 if we keep working on it.

**Comment by davebx** [comment]
Absolutely, this needs extensive testing before I'd be confident calling it a new feature.

**Comment by martenson** [comment]
my thinking was to polish it and encourage usage/adoption in the next release notes highlight section

**Comment by davebx** [comment]
As of 5309c8e, all the bugs in this issue have been fixed.
