### ISSUE TITLE
Question: multiple output with html format in Galaxy Unknown parameter type (<type 'NoneType'>)

### ISSUE THREAD

**Issue by psnehal** [galaxyproject/galaxy#2874]
I am trying to zip output file from my custom tool using html functionality in galaxy. When I run the  tool, I can see the folder created and files created. But as soon as job finished those files are deleted and when I click on the download result I get following error:

File '/home/snehal/Galaxy/galaxyLatest/galaxy/lib/galaxy/util/**init**.py', line 488 in sanitize_param raise Exception('Unknown parameter type (%s)' % ( type( value ) )) Exception: Unknown parameter type (<type 'nonetype'="">)

Does anybody know about this error?

Thanks Snehal

**Comment by hackdna** [comment]
FWIW: http://dev.list.galaxyproject.org/Problem-downloading-HTML-datasets-td4670034.html

**Comment by hexylena** [comment]
It looks like this might have been fixed by upgrading Galaxy. Thanks for the link @hackdna
