### ISSUE TITLE
Upload: Problem with pasted text that ends with a carriage return.

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2886]
Error

> Could not access the value for column 3 on line: "
> ". Make sure file is tab-delimited.

Example history: https://usegalaxy.org/u/jen/h/imported-problem-with-grouping

Likely introduced in Galaxy v 16.04. Reported by @hrhotz

ping @dannon - is this possibly related to other tabular data issues? See the output from the Cut tool - includes an extra dot "." line not present in the original dataset

**Comment by jennaj** [comment]
@hrhotz @dannon 

Test update 9-3: Turns out this was format all along. Considering this closed now.

SOLUTION: _Do not upload files that have extra whitespace lines_, and do not paste in text with a trailing carriage return _**these lines are undetected/hidden in user interface**_. Tools will fail on them for bad format. Detecting these could be an enhancement.

Looks like entire problem was with an extra space in the last line of the orignal file (d1). This isn't in the display/line count metadata (or when in highlighted "eye" view). **Only detected with Line/Word/Char count.** Tools like Convert will not fix the problem (will strip/merge whitespace on a line with data, but does not strip lines that contain ONLY whitespace). Selecting rows will pick just the active lines - but all that assumes one knows to do this/how many actual lines. This test was very short - larger files with extra whitespace-only lines will be difficult to detect/fix.
- Uploaded file with 3 data lines and one line of whitespace only chars. d1. Whitespace only line is undetected/not in line count.
- Cut (d3) and Group (d4) FAIL on this data (d1)
- Cut has problems on the last column of a file. Test d3 + d5
- Group has problems on the last column of a file. Test d2 + d4
- **Reupload data convert spaces>tabs with no trailing line. d6 - use as input and retest each:**
  - **Group test d7 - PASS**
  - **Cut test d8 - PASS**
- Copy original to see if content (extra line) detected. d11. FAIL.
  - Group on d11 - FAIL
  - Cut on d11- FAIL
- Convert on d11 to "fix". d14. FAIL
  - Group on d14 - d15 FAIL
  - Cut on d14 - d16 FAIL
- **Select first 3 lines of d1 to produce d19 - PASS (whitespace line removed)**
  - **Group on d19 PASS**
  - **Cut on d19 PASS**
- Line/Word/Character count on the 5 different versions of the file. Only two are correct with no extra whitespace line - and these produce valid tool results. 
  - d9 on d1 (extra line original)
  - **d10 on d6 (correct - fresh upload, no extra lines/spaces)**
  - d17 on d11 (extra line kept wtih Copy)
  - d18 on d14 (extra line kept with Convert)
  - **d19 on d1 (correct - extra line removed with Select first lines)**

**Comment by hrhotz** [comment]
It is not a line with whitespace in my original example. It is just a carriage return, isn't-it? And it is very common to end a tabular file with a carriage return IMHO.

Hans-Rudolf

**Comment by jennaj** [comment]
Yes, that is correct. I believe it was an end-of-line character that caused the problem. It is detected as a white-space character. When I paste in text data I never use a return at the end to avoid this problem. Ideal, not. Uploaded text files with carriage returns load just fine. This is a parsing problem probably.

Should we ask to have this stripped at the same time spaces are converted to tabs (part of that function). I think it would be helpful.

@guerler What do you think about cleaning up a bit more for pasted data? I modified the name on this ticket so we can keep using it. Doesn't have to be an immediate enhancement, just next time you are in there.
