### ISSUE TITLE
Import from usegalaxy.org https URL not working with our McAfee Proxy - works if switch to urllib2

### ISSUE THREAD

**Issue by dtrudg** [galaxyproject/galaxy#2896]
Our site uses a McAfee Web Gateway proxy server, with no direct internet access. A user was trying to fetch data from an https usegalaxy.org address but this was failing (invalid HTML content error). The download was working with wget, curl etc from the same machine. `http_proxy` and `https_proxy` were set correctly for galaxy.

The proxy was reporting:

```
Host: usegalaxy.org
Reason: Can't initialize server context:EnduserException:server state 1:state 8:Application response 500 handshakefailed
```

Investigating this further from the command line I found that a `urllib.urlopen(...)` will fail with this issue, but `urllib2.urlopen(...)` will succeed. 

Consequently this diff fixesthe issue for us:

``` diff
diff --git a/tools/data_source/upload.py b/tools/data_source/upload.py
index 59fa187..c912efe 100644
--- a/tools/data_source/upload.py
+++ b/tools/data_source/upload.py
@@ -10,7 +10,7 @@ import os
 import shutil
 import sys
 import tempfile
-import urllib
+import urllib2
 import zipfile
 from json import dumps, loads

@@ -94,7 +94,7 @@ def add_file( dataset, registry, json_file, output_path ):

     if dataset.type == 'url':
         try:
-            page = urllib.urlopen( dataset.path )  # page will be .close()ed by sniff methods
+            page = urllib2.urlopen( dataset.path )  # page will be .close()ed by sniff methods
             temp_name, dataset.is_multi_byte = sniff.stream_to_file( page, prefix='url_paste', source_encoding=util.get_charset_from_http_headers( page.headers ) )
         except Exception, e:
             file_err( 'Unable to fetch %s\n%s' % ( dataset.path, str( e ) ), dataset, json_file )
```

I guess I also need to replace other `urllib.urlopen` to `urllib2.urlopen` in our install to avoid the issue elsewhere.

We are running RHEL 6.8 with a python 2.7.11 built from source, system openssl etc. Not sure whether this is an issue anyone else would hit, and if it's worth changing in Galaxy?

**Comment by hexylena** [comment]
Hi @dctrud, thanks for the report, we've since changed the requesting method so the behaviour might be different currently, but based on the lack of feedback in this issue I guess we won't apply this patch. Thanks for figuring it out for the next person googling it though!
