### ISSUE TITLE
devise a way to bootstrap visualizations repo during Galaxy startup

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2915]
Given we will have https://github.com/guerler/galaxy-charts under our GH organization I believe we want to [fetch it](https://github.com/galaxyproject/galaxy/pull/2875/files#diff-449f7c2e078a6c4632754cb4d885a7feR5) during the startup based on a config value changed by an admin(`auto_init_viz`?). Once the fetched files are in place Galaxy should be aware of it/check its presence (registry) and propagate the information to the frontend - so UI can be rendered appropriately offering the viz to the enduser. 

Does this sound feasible?
@natefoo @guerler @jmchilton @jxtx @jgoecks @erasche @dannon 

xrefs: 
#2875 - charts to external repo
#1191  - distribute viz through TS
#1380 - make viz plugins more portable
#2861 - add BioJS plugins to codebase (closed)

**Comment by martenson** [comment]
One thing to mind is to not try build a second Tool Shed which this kinda leads to. E.g. how to treat updates? Where is the UI to manage these visualizations?

**Comment by natefoo** [comment]
Shouldn't there be a config file that allows an admin to configure which visualizations to fetch?

**Comment by martenson** [comment]
for now the charts extensions stay with the galaxy codebase, see #2875 for details
