### ISSUE TITLE
Launching a workflow with a batch of collections - menu collapses when selecting first collection

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/galaxy#2919]
When I try to launch a workflow with a batch of collections the selection menu collapses (to individual selection mode) once I select a single collection. This prevents running a batch of collections through a workflow.

**Comment by guerler** [comment]
Does this happen on main or dev-tip?

**Comment by MoHeydarian** [comment]
Yes. I'm having this issue on usegalaxy.org .
