### ISSUE TITLE
remove the repo repair feature from the codebase

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2929]
based on the [comment](https://github.com/galaxyproject/galaxy/pull/2250#issuecomment-247565356) from @mvdbeek 

When in trouble the repo re-installation is the recommended path, I believe 'repair' covers some subset of these cases but in the end behaves like blackbox that admins (and me) don't understand.

Benefits: simplification of repo maintenance; remove code, reduce complexity

**Comment by mvdbeek** [comment]
We should probably replace repair with re-install, to minimize the amount of frustrating click and wait and click (and wait ...). Re-install should be a light-weight function that sequentially calls uninstall and then install. Does that make sense?

**Comment by bgruening** [comment]
I think the point of repair was to recursively traverse the dependency tree, a single reinstall button can not "replace" this.
ping @gregvonkuster

**Comment by martenson** [comment]
@mvdbeek implementing reinstall button makes great sense now when we have hot reload

**Comment by mvdbeek** [comment]
> I think the point of repair was to recursively traverse the dependency tree, a single reinstall button can not "replace" this.

Hmm, that may be a show-stopper for TS packages, you're right. Though I wonder if you're not ultimately better off uninstalling the packages that don't work followed by reinstalling the tool?

**Comment by bgruening** [comment]
I also use it rarely, maybe in 6 month when conda is established?

**Comment by martenson** [comment]
@bgruening do we need this feature given we have Conda?

>recursively traverse the dependency tree

**Comment by hexylena** [comment]
I guess we don't need this any more?

**Comment by mvdbeek** [comment]
I think this is done now.
