### ISSUE TITLE
Testing metadata column_names

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#2941]
This might be a Galaxy or a Planemo problem, but I wanted to verify column meta-data in tests using e.g. https://github.com/peterjc/tools-iuc/commit/40fd0e1b667e6cc273e200a03391d08ca1aee766

``` xml
         <test>
             <param name="alignments" value="featureCounts_input1.bam,featureCounts_input2.bam" ftype="bam" />
             <param name="reference_gene_sets" value="featureCounts_guide.gff" ftype="gff" />
             <param name="format" value="tabdel_short"/>
             <param name="include_feature_length_file" value="true"/>
             <output name="output" file="output__short.tab"/>
             <output name="output_summary" file="output_summary.tab"/>
             <output name="output_feature_lengths" file="output_feature_length.tab">
                 <metadata name="column_names" value="Feature,Length"/>
             </output>
          </test>
```

My example above was based on https://github.com/jmchilton/planemo/blob/xsd_and_docs/docs/schema.md#tool%7Ctests%7Ctest%7Coutput%7Cmetadata - the draft XSD derived documentation from @jmchilton linked to from #2923

Example which should fail https://github.com/peterjc/tools-iuc/commit/2509d94fefaf77359e57b04a200f2d3211b526bb

``` xml
        <test>
            <param name="alignments" value="featureCounts_input1.bam,featureCounts_input2.bam" ftype="bam" />
            <param name="reference_gene_sets" value="featureCounts_guide.gff" ftype="gff" />
            <param name="format" value="tabdel_short" />
            <output name="output" file="output__short.tab">
                <metadata name="column_names" value="Foo,Bar"/>
            </output>
            <output name="output_summary" file="output_summary.tab">
                <metadata name="column_names" value="Alpha,Beta,Gamma"/>
            </output>
        </test>
```

However Planemo test is passing:

https://travis-ci.org/peterjc/tools-iuc/builds/161379564

**Comment by peterjc** [comment]
@yhoogstrate worked on the code to set the column names in pull request #961  - should this metadata testing of the column names work?

**Comment by yhoogstrate** [comment]
Hey @peterjc,

Sorry to get here so late. I did not implement anything on the testing of the column names, but it looks like it is already working on your failing test case:

```
Dataset metadata verification for [metadata_column_names] failed, expected [Alpha,Beta,Gamma] but found [[u'Status', u'featureCounts_input1.bam']]. ... truncated
```

The positive test however also fails:

```
... [Status,featureCounts_input1.bam] but found [[u'Status', u'featureCounts_input1.bam']]. ...
```

This is because the metadata value does not get exploded on the comma and it's comparing a string with a list. I think this should be quite easy to fix, if you know where to look in the code.

I definitely need to add some documentation on the wiki and the iuc-standards. (https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax#A.3Cactions.3E_type_metadadata_tag_set)

Youri

**Comment by peterjc** [comment]
Thanks @yhoogstrate - I realise now that featureCounts is in `.tt_blacklist` which explains why my test changes made no difference to TravisCI.

It sounds like you're right, this will only need a small change to Galaxy at a key point...

**Comment by peterjc** [comment]
Thanks @yhoogstrate - now that thanks to https://github.com/galaxyproject/tools-iuc/pull/960 featureCounts is not blacklisted in TravisCI, I have rebased my test branch...

**Comment by nsoranzo** [comment]
@peterjc This may be a Galaxy bug, code is at https://github.com/galaxyproject/galaxy/blob/dev/test/base/interactor.py#L100
Presently it seems to not support lists or any data structure, just single values. Ping @jmchilton

**Comment by jmchilton** [comment]
Yeah - it basically just works for strings currently. Any chance either of you (@peterjc or @yhoogstrate) can produce a very minimal tool that sets output column names to serve as an example. I can then add it to https://github.com/galaxyproject/galaxy/tree/dev/test/functional/tools and update the test framework to support the test. This will serve to validate the feature, document the feature, and validate the testing.

**Comment by peterjc** [comment]
Does the merging of #2970 mean this issue is fixed (once using the very latest Galaxy with Planemo)?

**Comment by nsoranzo** [comment]
> Does the merging of #2970 mean this issue is fixed (once using the very latest Galaxy with Planemo)?

@peterjc Yes!

**Comment by peterjc** [comment]
Great - closing this, thanks all.

**Comment by peterjc** [comment]
For an example using the test framework to check column names in metadata, see https://github.com/galaxyproject/tools-iuc/blob/master/tools/featurecounts/featurecounts.xml
