### ISSUE TITLE
Workflow, missing tools do not remove connections on deletion

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#2942]
Steps:
- I import a Galaxy 101 wf from here: https://usegalaxy.org/u/dan/w/galaxy-101/json
- It displays that it is missing GOPs Join.
- I Install GOPs Join from TS (it is still missing...)
- I Edit workflow.
- Delete Red/Missing tool.
- I add GOPs join from Tool Panel.
- I cannot Connect New GOPs join to 'Group' tool.
- I notice, on hover, that the input dataset in Group has an 'X' to delete input connection
- Click 'X' to delete nonexistant connection.
- Can now connect input, as per normal.
- dev @ commit 35d0fed80145c7d07c0512ebcb9b4a23c4293072

**Comment by nsoranzo** [comment]
@anilthanki also saw that on 17.01, still an issue.

**Comment by mvdbeek** [comment]
That's done, but of course it's followed by https://github.com/galaxyproject/galaxy/issues/7141 ;)
