### ISSUE TITLE
Copy Dataset bug

### ISSUE THREAD

**Issue by broodjeaap** [galaxyproject/galaxy#2964]
When copying datasets from one history to a new history:
![capture](https://cloud.githubusercontent.com/assets/1033693/18782775/619b2294-8188-11e6-89a0-4dfff5709d78.PNG)
The file(s) are copied to both the new history and the one selected in the dropdown:
![capture2](https://cloud.githubusercontent.com/assets/1033693/18782842/b3b05fc2-8188-11e6-846f-4c43788c7874.PNG)

**Comment by nsoranzo** [comment]
May be fixed by https://github.com/galaxyproject/galaxy/pull/2957. @blankenberg?

**Comment by blankenberg** [comment]
Yes, should be.

**Comment by nsoranzo** [comment]
@broodjeaap This should have been fixed in the `dev` branch, do you need the fix in a Galaxy release? Which one are you using?

**Comment by broodjeaap** [comment]
Don't need a fix that fast, thank you though, glad to hear it's going to be in a future release.

**Comment by nsoranzo** [comment]
@broodjeaap OK, I'll close the issue then. Thanks for reporting!
