### ISSUE TITLE
Many TIFF images are not recognized by sniffer

### ISSUE THREAD

**Issue by ThomasWollmann** [galaxyproject/galaxy#2981]
Just try some of https://www.openmicroscopy.org/site/support/ome-model/ome-tiff/data.html
Some are not recognized at all.

**Comment by dannon** [comment]
I did a bit of digging and it looks like PIL (or pillow) does not detect these as .tiff correctly while the basic imghdr python library does.  I'm going to open a PR converting to the simpler, dependency-less imghdr extension and see if there are incompatibilities the other way around (so, whether there's actually a good reason to use PIL).

**Comment by bgruening** [comment]
Interesting, I saw this too. @dannon is there any progress? I saw you have worked on a new pillow library?

**Comment by dannon** [comment]
@bgruening Check out #3042, it should work.  I still want to do more here, but I don't have the time to deal with that failing Pillow build on starforge at the moment.
