### ISSUE TITLE
Rework a job's version string path to be in the job directory.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#2985]
The tmp thing doesn't scale and we shouldn't be using. Also right now it is being written to the tmp directory which is not mounted rw by default for Docker. This is fixable by setting up `docker_volumes` but it'd be better to improve the out-of-the-box experience.

**Comment by hexylena** [comment]
This seems to be fixed now, job version strings are written to JWD afaict

**Comment by jmchilton** [comment]
Indeed, thanks!
