### ISSUE TITLE
Toolbox reloading does not load special internal tools (e.g. __SET_METADATA__)

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#2988]
The new toolbox reloading introduced in #2840 and #2901 does not reload the special internal tools such as `__SET_METADATA__`, `__IMPORT_HISTORY__`, and `__EXPORT_HISTORY__`.

**Comment by mvdbeek** [comment]
OK, I'll have a look. what are the symptoms if they are not loaded/reloaded?

**Comment by natefoo** [comment]
Thanks @mvdbeek. Symptoms for `__SET_METADATA__` not loading is that clicking the metadata auto-detect button (from a dataset's "edit" page) after a toolbox reload will result in the job failing (and not updating the HDA state back from `setting_metadata` - but this is an unrelated problem) with the log message `This tool was disabled before the job completed.  Please contact your Galaxy administrator.`

I would imagine you'd get similar results for the other two tools when attempting to export or import a history.
