### ISSUE TITLE
Cuffmerge v 2.2.1 failing at http://usegalaxy.org - Problem with selecting multiple input files?

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#2989]
The tool fails with version 2.2.1 but the same exact input with v 0.0.6 is successful. v 2.2.1 has not been changed in two years. **This seems to be a Galaxy problem related to how multiple inputs are chosen on the tool form and then processed.**

**Workaround for users** = Use Tool version 2.2.1 without Multi-File select when using collections **or** Use Tool version v 0.0.6 for individual multiple file input

_Note how the different forms allow the user to organize the input gtf files produced by Cufflinks._ 

---

**v 0.0.6 - Success**

Form set up: 
<img width="647" alt="screen shot 2016-09-30 at 8 57 17 am" src="https://cloud.githubusercontent.com/assets/8999735/18998374/577a5e64-86ed-11e6-9068-deac7ce60177.png">

Info page:
<img width="642" alt="screen shot 2016-09-30 at 8 54 52 am" src="https://cloud.githubusercontent.com/assets/8999735/18998355/3a3273dc-86ed-11e6-9cf2-9ed819c01102.png">

No error, is successful

---

**2.2.1 - Failure**

Form set up:
<img width="639" alt="screen shot 2016-09-30 at 8 57 43 am" src="https://cloud.githubusercontent.com/assets/8999735/18998385/67c208da-86ed-11e6-92c5-091a11f02163.png">

Info page:
<img width="640" alt="screen shot 2016-09-30 at 8 55 21 am" src="https://cloud.githubusercontent.com/assets/8999735/18998337/2810a61a-86ed-11e6-8115-889aa66a0a0a.png">

Error generated:

> Dataset generation errors
> Dataset 226: Cuffmerge on data 134, data 203, and others: merged transcripts
> 
> Tool execution generated the following error message:
> Fatal error: Matched on Error
> Error running cuffmerge. 
> ## [Fri Sep 30 10:50:11 2016] Beginning transcriptome assembly merge
> 
> [Fri Sep 30 10:50:11 2016] Preparing output location cm_output/
> [Fri Sep 30 10:50:14 2016] Converting GTF files to SAM
> [10:50:14] Loading reference annotation.
> [10:50:14] Loading reference annotation.
> [10:50:15] Loading reference annotation.
> [10:50:15] Loading reference annotation.
> [Fri Sep 30 10:50:15 2016] Quantitating transcripts
> You are using Cufflinks v2.2.1, which is the most recent release.
> Command line:
> cufflinks -o cm_output/ -F 0.05 -g /galaxy-repl/main/files/XXX/XXX/dataset_XXX.dat -q --overhang-tolerance 200 --library-type=transfrags -A 0.0 --min-frags-per-transfrag 0 --no-5-extend -p 4 cm_output/tmp/mergeSam_fileKE0583 
> [bam_header_read] EOF marker is absent. The input is probably truncated.
> [bam_header_read] invalid BAM binary header (this is not a BAM file).
> File cm_output/tmp/mergeSam_fileKE0583 doesn't appear to be a valid BAM file, trying SAM...
> [10:50:15] Loading reference annotation.
>   [FAILED]
> Error: could not execute cufflinks
> 
> The tool produced the following additional output:
> merge_cuff_asms v1.0.0
> cuffmerge -o cm_output  -p 4  -g /galaxy-repl/main/files/XXX/XXX/dataset_XXX.dat  --min-isoform-fraction 0.05 /galaxy-repl/main/jobdir/XXX/XXX/XXX/working/tmpXXX

**Comment by jennaj** [comment]
Input was okay here (original data not truncated)- @natefoo confirmed. Weird problem - is it Main related (internal job that converts input to BAMs running out of memory?) . I don't think this is an issue with the wrapper - wrapper not new and not everyone has the problem. 

Looking at another two examples to see if can find root cause

**Comment by natefoo** [comment]
Could this be due to the ordering of GTF inputs no longer being controllable with the new style selector? Does the order matter?

**Comment by jennaj** [comment]
The order of the Cufflinks GTF files should not matter. It seems like they are not passed correctly in the wrapper anymore - perhaps due to other changes?

**Comment by jmchilton** [comment]
@jennaj Do you have the command-line for the older version of the tool?

**Comment by jennaj** [comment]
@jmchilton Sending you a shared history link direct. It is private data so cannot be shared here.

Update: couldn't find the history before - just did! Shared

**Comment by jmchilton** [comment]
I still haven't seen the command-line for the older working version of this tool vs. the newer one. I think you sent me a history with DESEQ2 - which I believe is unrelated to this problem.

**Comment by jennaj** [comment]
I shared the history with the two (and the command lines are below for reference, if needed later), but I now think this is probably an input problem of some sort with the gff3 input. Let's close it out, can open later if comes up again.

toolshed.g2.bx.psu.edu/repos/devteam/cuffmerge/cuffmerge/0.0.6

```
python /galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/cuffmerge/424d49834830/cuffmerge/cuffmerge_wrapper.py  --num-threads="${GALAXY_SLOTS:-4}"  -g "/galaxy-repl/main/files/017/208/dataset_17208094.dat"   --merged-transcripts="/galaxy-repl/main/files/017/353/dataset_17353588.dat"  "/galaxy-repl/main/files/017/208/dataset_17208094.dat" "/galaxy-repl/main/files/017/208/dataset_17208090.dat" "/galaxy-repl/main/files/017/208/dataset_17208086.dat" "/galaxy-repl/main/files/017/207/dataset_17207907.dat"
```

toolshed.g2.bx.psu.edu/repos/devteam/cuffmerge/cuffmerge/2.2.1.0

```
python /galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/cuffmerge/b6e3849293b1/cuffmerge/cuffmerge_wrapper.py --num-threads="${GALAXY_SLOTS:-4}"  -g "/galaxy-repl/main/files/017/204/dataset_17204511.dat"   --min-isoform-fraction="0.05"  --merged-transcripts="/galaxy-repl/main/files/017/353/dataset_17353638.dat"   "/galaxy-repl/main/files/017/207/dataset_17207907.dat" "/galaxy-repl/main/files/017/208/dataset_17208086.dat" "/galaxy-repl/main/files/017/208/dataset_17208090.dat" "/galaxy-repl/main/files/017/208/dataset_17208094.dat"
```
