### ISSUE TITLE
Some tool wrapper's are not Conda compatible

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2993]
...even when the package is available. 

See the example with trimmomatic here: https://github.com/fls-bioinformatics-core/galaxy-tools/issues/21

ping @bgruening @mvdbeek @jmchilton

**Comment by mvdbeek** [comment]
In this case the wrapper relies on the `TRIMMOMATIC_DIR` env var defined in the tool shed dependency and could be changed to fallback on the `trimmomatic` wrapper script provided by the conda trimmomatic package. I don't see a reliable automatic way to handle this (on galaxy's side). We already touched on the issue of env vars in conda [here:](https://github.com/galaxyproject/galaxy/issues/2649).

I think what's the most frustrating in this situation is that this requires manual try-and-error to see which dependency works, which in addition requires expert understanding of how tool dependency resolution works.

If we want to be more upfront on this we could ask tool authors to specify conda-compatibility in the tools's metadata perhaps and then display this to the admin somehow?
Or (longer term) start running tool tests on the TS again, and report if a tool passes tests with conda dependencies?

**Comment by bgruening** [comment]
A little bit more background regarding JAVA tools and environment variables.

This one `-jar \$TRIMMOMATIC_DIR/trimmomatic-0.36.jar --help` is not possible in Conda. You can not set an ENV var during installation. We are using a script (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/trimmomatic/trimmomatic.sh), nowadays a python script, that wrapps the JAVA magic into a single executable `trimmomatic`. 

The above command becomes `trimmomatic --help`, way easier to handle. But both versions are not compatible. We did a little bit of bash magic to support Conda and TS dependencies in parallel like here: https://github.com/galaxyproject/tools-iuc/blob/master/tool_collections/snpsift/snpSift_macros.xml#L13 and it seems to work.

This will hopefully all go away if we drop TS dependencies in newer versions.

**Comment by nsoranzo** [comment]
Completely agree with @bgruening, I don't think Galaxy can/should do something here, tool authors can either go Conda-only or use the mentioned workaround.

**Comment by mvdbeek** [comment]
This is all fine from the tool-author side, and also, I agree that Galaxy can't do much here, but keep in mind that the admin has no clue for a given tool which dependency should be installed/used.

**Comment by nsoranzo** [comment]
> the admin has no clue for a given tool which dependency should be installed/used.

@mvdbeek I still think the correct solution for this is to implement what I have proposed in https://github.com/galaxyproject/galaxy/issues/1927#issuecomment-231698125 .

**Comment by mvdbeek** [comment]
Yes, that would be a good solution. This wouldn't exclude a mapping file approach either. What do you think about this, @jmchilton ?

**Comment by bgruening** [comment]
If there is a tool_dependency.xml file the admin should install TS dependencies, correct? If there is none ... take conda/docker. Isn't this enough?

**Comment by jmchilton** [comment]
:+1: to @bgruening's comment I think. I think we are just going to install both and use the tool shed dependency though - no reason to give most admins a choice I think. @martenson is going to simplify the default UI.

Annotating the requirement breaks the abstraction we (I hate using we - we can say I) want to establish and it is a stop gap I think.

**Comment by mvdbeek** [comment]
> If there is a tool_dependency.xml file the admin should install TS dependencies, correct? If there is none ... take conda/docker. Isn't this enough?

That would work. So what you're saying is that the presence of a tool_dependencies.xml means "don't use conda" ?. If we want to be coherent here, I think we should also not install conda or allow fallback to conda, to not send mixed signals. Or at least not do that by default.

**Comment by martenson** [comment]
> we could ask tool authors to specify conda-compatibility in the tools's metadata

I think that in addition to @jmchilton's points this falls short because this will necessarily (we will fail to reach many/majority owners) omit many tools that are conda-compatible and thus setting the whole Conda effort back a bit.

> This will hopefully all go away if we drop TS dependencies in newer versions.
1. We retain past versions and want them to work.
2. The trimmomatic wrapper will still fail even if there is no tool_dependencies.xml right? Does the wrapper not need to be changed to support Conda trimmomatic package?

> If there is a tool_dependency.xml file the admin should install TS dependencies, correct?

I feel we are losing something here. Conda can work in environments that TS deps won't, when we force admins to avoid Conda if there is tool_dependencies.xml present we are denying them this possibility.

---

Are we confident to recommend Conda installation of tools that went through travis/planemo tests (i.e. iuc, devteam)?

**Comment by mvdbeek** [comment]
> Are we confident to recommend Conda installation of tools that went through travis/planemo tests (i.e. iuc, devteam)?

I haven't seen a case yet where the planemo tests pass and subsequently it didn't work for a user. Granted, not many users yet, but at least we would have a chance to understand what is going wrong, which is a difficult task with TS deps.
The only trouble I have with conda are upstream conda problems (i.e short prefix, outdated conda version and `activate` sometimes missing). Once conda works on a system, I think it's far more reliable.
For me the answer is yes, but I think I'm biased here.

**Comment by jmchilton** [comment]
> The trimmomatic wrapper will still fail even if there is no tool_dependencies.xml right? Does the wrapper not need to be changed to support Conda trimmomatic package?

I've argued over and over that the tool shed environment variables are an anti-pattern. No other packaging system provides this - none. There was a period of time when the "best practice" for tools that wrap Java programs was to use this pattern. In my opinion this was a poor choice - in a sense these wrappers were deformed to adapt to the tool shed - they would have never run without tool shed install dependencies (i.e. wouldn't run with local testing, local installs, `planemo test`, etc...).

So yes - many tools including trimmomatic have been warped by the tool shed and they will need to be un-warped. The process will make them better tools - they will be more compatible with more packaging systems - they will work better with local, non-shed installs, they will work better with planemo. Certainly we need to be careful about what `tool_dependencies.xml` files we drop and we will need to improve some tools as we drop them.

> I feel we are losing something here. Conda can work in environments that TS deps won't, when we force admins to avoid Conda if there is tool_dependencies.xml present we are denying them this possibility.

What do you think about like advanced options to enable this (hidden at first on the form). This way a majority of deployers don't need to worry about it but deployers who want to exercise Conda functionality can?

**Comment by jmchilton** [comment]
I feel like we have discussed this and there aren't really concrete actions left - we've improved the UI somewhat and will improve it some more, we are working on updated documentation for writing tool dependencies, etc.... Anyone should feel free to re-open if there are specific things left to do or perhaps open a new more specific issue.
