### ISSUE TITLE
certain Conda-resolved dependencies are masked by Galaxy's lib module

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#2994]
This affects tools with dependencies derived from Galaxy's code (`package_galaxy_ops_1_0_0` and `package_galaxy_utils_1_0`) but also any other dependencies matching Python imports from `/lib/`.

Issue was originally tracked here: https://github.com/galaxyproject/tools-devteam/issues/389

@jmchilton proposed:
- disabling the addition of Galaxy to PYTHONPATH if the tool is a tool shed tool
- Alternatively we can make a whitelist of tools that require Galaxy's `lib` on path and probably ignore this for any local tools (from `tool_conf.xml`).

**Comment by jmchilton** [comment]
This approach doesn't help if admins have explicitly sourced the Galaxy environment with an ``env`` statement. :cry:

**Comment by jmchilton** [comment]
WIP @ https://github.com/jmchilton/galaxy/tree/clean_python.
