### ISSUE TITLE
Step handler of tool shed recipes uses very old virtualenv

### ISSUE THREAD

**Issue by rene-rex** [galaxyproject/galaxy#3002]
Hi

I ran into a problem installing one of my tools with matplotlib as a dependency. The log files revealed that pip tried to compile matplotlib from source instead of using the binary package (whl). It turned out that the version of pip is too old: 1.3.1 (current is 8.1.2). This pip originates from an old version of virtualenv installed in tool_dependencies/__virtualenv_src. Finally, I tracked this down to this [line of code](https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py#L24).

This hard-codes a very old version of virtualenv. Is there any good reason for this or could you update this? One possible way would be to use the tarball of the master branch on github: https://github.com/pypa/virtualenv/tarball/master
- René

**Comment by nsoranzo** [comment]
Updating the link to e.g. `https://pypi.python.org/packages/8b/2c/c0d3e47709d0458816167002e1aa3d64d03bdeb2a9d57c5bd18448fd24cd/virtualenv-15.0.3.tar.gz` seems fair.

**Comment by hexylena** [comment]
Fixed in #5202
