### ISSUE TITLE
UX reports

### ISSUE THREAD

**Issue by ThomasWollmann** [galaxyproject/galaxy#3014]
Some of the users first trying Galaxy reported me the following UX issues:
- [ ] the  forbidden sign cursor if an item is disabled in the history is confusing
- [ ] there is a lack of "visible back buttons" in features like the data library,
- [ ] The browser alert, which appears, if you exit an IE, is confusing and conveys to some users, that the whole browser tab will be closed.
- [ ] UI loading time often exceeded their patience threshold (maybe just caused by our setting)

**Comment by martenson** [comment]
@ThomasWollmann could you please specify what you mean in your first bullet?

**Comment by ThomasWollmann** [comment]
Several times the forbidden sign is used for a disabled item. I'll ask for a specific confusing example.
