### ISSUE TITLE
Tools installed from ToolShed no longer use GUID after install, until reboot

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#3017]
- Install a Tool from the toolshed.
- Hover over link of newly installed tool, or run tool and check info for job.
- Tool will have the 'old id' (e.g. "fastq_paired_end_joiner") instead of the correct GUID (e.g. "toolshed.g2.bx.psu.edu/repos/devteam/fastq_paired_end_joiner/fastq_paired_end_joiner/2.0.1")
- Restart Galaxy, and the tool will now have the correct ID.

This breaks reproducibility, and causes issues for rerun, etc.

Found on dev @ 2b10e2047293ee95ea8084657c55a5e354ce3b23

**Comment by mvdbeek** [comment]
Hmm, I'm on 3345dd4a92b9224a6a4e864326b60c8e92f29ad0, and at least in the run.sh scenario I haven't seen this happening. Do you still have the logs of when you installed the tool?
Do you see the short id when the toolbox reloads?
For me this is the output when installing a new tool:

```
...
galaxy.tools.toolbox.base DEBUG 2016-10-07 16:39:19,892 Loaded tool id: toolshed.g2.bx.psu.edu/repos/devteam/fastq_paired_end_deinterlacer/fastq_paired_end_deinterlacer/1.1, version: 1.1 into tool panel....
galaxy.tools.toolbox.base DEBUG 2016-10-07 16:39:19,892 Loaded tool id: toolshed.g2.bx.psu.edu/repos/devteam/fastq_paired_end_interlacer/fastq_paired_end_interlacer/1.2, version: 1.2 into tool panel....
galaxy.tools.toolbox.base DEBUG 2016-10-07 16:39:19,892 loading tool panel took 0 seconds
galaxy.tools.deps DEBUG 2016-10-07 16:39:19,895 Unable to find config file './dependency_resolvers_conf.xml'
galaxy.tools.special_tools DEBUG 2016-10-07 16:39:19,928 Loaded history import tool: __IMPORT_HISTORY__
galaxy.tools.special_tools DEBUG 2016-10-07 16:39:19,930 Loaded history export tool: __EXPORT_HISTORY__
galaxy.queue_worker DEBUG 2016-10-07 16:39:19,941 Toolbox reload took 0 seconds
...
```

**Comment by martenson** [comment]
After 5 different tools installed I cannot reproduce this (I am on https://github.com/galaxyproject/galaxy/commit/a08b849f6db5041dc56173051bc45aaa8c469ae4) 

But I saw it hapenning on @blankenberg's machine 🤔

**Comment by mvdbeek** [comment]
˜˜OK, I switched machines to my old mac, and suddenly I see this too.
In fact it's enough to reload the toolbox in the admin panel, and all tools use the old style tool id.˜˜
That was because I messed up an if/elif/else clause while trying to fix this problem here.
