### ISSUE TITLE
Tool form banner alert "There is a newer version of this tool" for re-run jobs is not displaying anymore

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3021]
The above is missing now. This was useful info. Possible to get it back?

I wonder if the newer pop-ups that state "when a tool versions switch" occurs are related.

@guerler or @carlfeberhard ?

**Comment by jennaj** [comment]
The tool panel now also loads the older version of the tool instead of the newer one. Users are reporting problems with the older tool version for certain use-cases.

Could we adjust the tool panel settings for all VCF Mani tools to make sure the most current wrapper version is loading?

----

Example:

**Old version**: VCF-VCFintersect: Intersect two VCF datasets (Galaxy Version 0.0.3)

**Updated version**: VCF-VCFintersect: Intersect two VCF datasets (Galaxy Version 1.0.0_rc1+galaxy0)

For end-users: Make sure to **use updated tool version** or errors may come up.

ping @martenson @natefoo

**Comment by dannon** [comment]
@guerler did you figure anything out on this one?  If not, want to brief me and I'll take care of it?

**Comment by guerler** [comment]
Sounds good.

**Comment by guerler** [comment]
The message should be generated here: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/__init__.py#L2034

**Comment by jennaj** [comment]
The VFC-VCF intersect tool is still in the tool panel twice, is not found with a search, the older version does not point to the newer version, and the newer version does not have a "Versions" menu.

Most problems are at both .org and .eu. (.eu does have a versions menu, but the older tool is what is launched from the tool panel). Same for other VCF* tools. Seems like a combination of issues with those unrelated to the original, more general versions warning issue. 

I'll make a distinct issue ticket against the tool repo (and playbook for tool panel dups/final testing of this once on main) and link those back here to keep all distinct. 

**Update** tools launch with the latest version now (did a double check using 18.09 release at .org), thanks!
