### ISSUE TITLE
Macros are not documented in galaxy.xsd

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#3029]
Macros (`<macros>`, `<import>`, `<token>`, `<xml>`, `<yield/>`, `<expand>`) are not documented in `lib/galaxy/tools/xsd/galaxy.xsd` .

**Comment by bgruening** [comment]
@davelopez something you would like to work on during the event?

**Comment by davelopez** [comment]
Sure! This is something I can try! :)
