### ISSUE TITLE
Heatmap 1.0.0 missing dependencies at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3030]
**Tool** 

toolshed.g2.bx.psu.edu/repos/guru-ananda/heatmap/heatmap_1/1.0.0

**Error**

> bash: /galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/guru-ananda/heatmap/89902ebc58b9/heatmap/heatmap//galaxy/main/shed_tools/toolshed.g2.bx.psu.edu/repos/guru-ananda/heatmap/89902ebc58b9/heatmap/r_wrapper.sh: No such file or directory

**Comment by jennaj** [comment]
The tool is still producing the error about an open dependency issue.

ping @galaxyproject/guac

**Comment by jennaj** [comment]
Still an issue, example test history: https://usegalaxy.org/u/jen/h/test-heatmap-tool

**Comment by jennaj** [comment]
Update: Should be fixed when this pull-request is incorporated: https://github.com/galaxyproject/tools-iuc/pull/1321

**Comment by mvdbeek** [comment]
closing as this is not a Galaxy issue
