### ISSUE TITLE
"Edit Attributes" button/link in Workflow Editor Options Doesn't Work

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#3038]
Steps:
- Edit a workflow
- Click Gear Icon
- Click "Edit Attributes"
- Nothing happens

Seen in usegalaxy.org and in local instance on dev @ 58d608b9060d7608c33d711183790e3b19c313cc using Chrome

**Comment by guerler** [comment]
This works for me.

**Comment by dannon** [comment]
Yep, working for me too.  If we see this again, we can reopen.
