### ISSUE TITLE
Histories containing only a Collection display as (empty)

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#3050]
Copy a Collection into a new history using the multiple history view. You have a history item 1, but it is displayed as being both `1 shown` and `(empty)`, as there are no HDAs in the history. You can use this History/item and perform an analysis, however. Perhaps it would be better to show usage as `0 bytes`, in this case? (although it _theoretically_ should prevent dataset cleanup purging, so not really 0 usage.)

![image](https://cloud.githubusercontent.com/assets/1231190/19365970/3c35eb70-9163-11e6-8cce-6c41d90bd082.png)

**Comment by mvdbeek** [comment]
I think John fixed the history state summary some time ago, and we do copy HDAs now when copying collections, so this shouldn't be an issue anymore.
<img width="212" alt="Screen Shot 2019-05-19 at 10 39 23" src="https://user-images.githubusercontent.com/6804901/57979750-6a281800-7a22-11e9-9d27-62d7f6ec50e9.png">
