### ISSUE TITLE
Request to increase memory allocation for Du Novo tools at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3057]
What is the current allocation? Bump?

ping @natefoo @nekrut

**Comment by martenson** [comment]
I talked to Barbara, who uses it. Please bump.

M.

On Fri, Oct 14, 2016, 16:17 JennaJ notifications@github.com wrote:

What is the current allocation? Bump?

ping @natefoo https://github.com/natefoo @nekrut
https://github.com/nekrut

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/galaxyproject/galaxy/issues/3057, or mute the thread

**Comment by jennaj** [comment]
Any decisions or action yet? A status update has been requested. Thanks all!

**Comment by natefoo** [comment]
This tool already runs with 30GB. @NickSto can we make estimates on how much memory would be needed, or limit the tool's memory needs without significantly adversely affecting performance?

**Comment by natefoo** [comment]
Assuming we are talking about align_families.

**Comment by martenson** [comment]
30GB, lol

> 640KB ought to be enough for anyone.

**Comment by NickSto** [comment]
@jennaj What size inputs are we talking?

**Comment by jennaj** [comment]
@NickSto ~420,000 lines, 389.9 MB

**Comment by NickSto** [comment]
@jennaj Hey, sorry for the delay. I'm just having trouble figuring out how the memory limit is being reached. All the Du Novo tools operate on a stream, and so they use almost no memory. I can't find a point when that's not the case. Do you have example histories/datasets that run into the limit?

Barbara said she's run into the wall clock limit. It certainly takes a lot of time, so I'd expect it to be CPU-bound instead. Are you sure that's not the issue?

**Comment by jennaj** [comment]
@nsoranzo The error reported had the regular memory failure reported (not wall-time), although she may have others that failed for that as well (none were in the bug report history). I'll share the history.

**Comment by natefoo** [comment]
Not sure about the memory errors but I've allowed this tool to run on Jetstream, Barbara has successfully run it on both roundup and jetstream at this point, so I think we're okay to close this?

**Comment by jennaj** [comment]
Agree, closing

**Comment by jennaj** [comment]
The tool needs to have walltime increased and Jetstream targetted again. Here is the note from Barbara. Another user also reported the walltime error last night. I am opening the ticket again.

> Hi! I think with the new version of the DuNovo pipeline, the settings for the maximum allowed job run 
> time are again back to the standard settings. Would it be posssible to increase the maximum allowed 
> run time again for the Align_families step, that larger datasets can also be run?
> It would also be great if this step could be run on Jetstream again (since this is also something that 
> doesn't work anymore since the update).
> Barbara

**Comment by jennaj** [comment]
@natefoo Did this get resolved? Would like to close it out again if so, tx

**Comment by jennaj** [comment]
Tested and now closed. Reruns on prior failed jobs now pass.
