### ISSUE TITLE
gff_filter_by_attribute missing test files

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#3065]
The following test files are missing from https://github.com/galaxyproject/galaxy/blob/dev/tools/filters/gff/gff_filter_by_attribute.xml
- `gff_filter_attr_in1.gff` (input)
- `gff_filter_by_attribute_out1.gff` (output)
- `gff_filter_by_attribute_out2.gff` (output)

As far as I can see, this tool has not been moved to the Tool Shed.

**Comment by nsoranzo** [comment]
These test data have been removed and placed in a separate repository: https://github.com/galaxyproject/galaxy-test-data . `./run_tests.sh` should be aware of that, see GALAXY_TEST_FILE_DIR in its help. The same GALAXY_TEST_FILE_DIR env variable can be used in Planemo, I think.

**Comment by peterjc** [comment]
Thanks Nicola, yes - the files are there:
- https://github.com/galaxyproject/galaxy-test-data/blob/master/gff_filter_attr_in1.gff
- https://github.com/galaxyproject/galaxy-test-data/blob/master/gff_filter_by_attribute_out1.gff
- https://github.com/galaxyproject/galaxy-test-data/blob/master/gff_filter_by_attribute_out2.gff
