### ISSUE TITLE
Towards Galaxy workflow hosting

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#3066]
This issue is going to outline the path towards developing a hosting service for Galaxy workflows.
1. Workflows with better IDs
2. Augment TS API to search on better IDs & on tool versions
3. Index & Search API
4. Tooling - Ephemeris
5. UI
6. name it
7. ...
8. profit!

**Comment by hexylena** [comment]
I think this is solved with workflow-hub.eu, TRS probably.
