### ISSUE TITLE
docs building is missing import

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#3075]
Since we added the architecture slides that used recommonmark jenkins is failing probably because we do not have the wheel to satisfy `from recommonmark.parser import CommonMarkParser`

https://jenkins.galaxyproject.org/job/latest-Sphinx-Docs/lastFailedBuild/console

recommonmark added here:
https://github.com/galaxyproject/galaxy/commit/3e737c99ea21dcb7ea3a326d36aee9c715c8d70b#diff-555c472a89566734e0d8567fb205d5dfR19

**Comment by nsoranzo** [comment]
How do you specify the Python deps needed? There are also `sphinx` itself and `sphinx_rtd_theme` at least.

**Comment by martenson** [comment]
yeah, seems we have it only in the jenkins build job :/

**Comment by martenson** [comment]
```
pip install sphinx
pip install sphinx_rtd_theme
pip install lxml
pip install recommonmark
```
