### ISSUE TITLE
History Panel missed event

### ISSUE THREAD

**Issue by enuggetry** [galaxyproject/galaxy#3081]
On occasion, the history panel will leave a job unfinished when it is actually finished.  Apparently, it missed an update event or something.
![ice_screenshot_20161021-165137](https://cloud.githubusercontent.com/assets/10053377/19614982/005ed9a2-97af-11e6-91ad-469f416fffbb.png)

Refreshing the page solves it:
![ice_screenshot_20161021-165630](https://cloud.githubusercontent.com/assets/10053377/19615018/60f8d3da-97af-11e6-80c8-828c170f81a1.png)

**Comment by hexylena** [comment]
Unknown issue, sorry @enuggetry but hopefully should be better with upcoming history panel rewrite.
