### ISSUE TITLE
Run a tool with a collection against a collection

### ISSUE THREAD

**Issue by JenCabral** [galaxyproject/galaxy#3083]
I have a tool which can run a collection against a database. It works fine with one database, however I want to run a collection against a collection of databases. When I try this, the tool won't run and the logs just show a 400 error:
_127.0.0.1 - - [24/Oct/2016:07:46:47 -0500] "POST /api/tools HTTP/1.1" 400 - "http://127.0.0.1:8080/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36_
and the following pop up shows up:
![screenshot from 2016-10-24 07-46-14](https://cloud.githubusercontent.com/assets/9087682/19646238/24caae90-99be-11e6-96cb-a1703fd29d8f.png)

Is there anyway to create a tool that would accept 2 collections in this way which would create an output of NxM datasets?

**Comment by hexylena** [comment]
Hi @JenCabral sorry we could not help with this issue at the time. Hopefully it works better now, work has been done in the past years to make collection tools and workflows better.
