### ISSUE TITLE
Export Histories into Research Objects

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#3088]
@dannon and I talked yesterday about better and more structured way of exporting and reusing Galaxy histories. Exporting this into a http://www.researchobject.org might be a good solution.

**Comment by lparsons** [comment]
Many of my users would also love a way to export a history _without_ the data (sort of like a workflow). In a way, "Create workflow from history" kind of does this, but it's often a bit broken and doesn't save the names/etc. Basically, having a way to retain history items, but remove the underlying dataset, would be very useful for archival purposes. One could retain the input data and some final output datasets, but remove the unnecessary intermediate files without losing the history of what was done.

**Comment by nsoranzo** [comment]
Export of histories as BagIt bags was implemented in https://github.com/galaxyproject/galaxy/pull/7367 , but it was just a first step as explained in https://github.com/galaxyproject/galaxy/issues/4345#issuecomment-480811571 .

**Comment by HadleyKing** [comment]
This is something we are looking at with [BioCompute](https://github.com/biocompute-objects) using the galaxy history AND galaxy workflow JSON outputs. I have been searching but have not been able to find specific documentation about how the the key:value pairs are generated and what they mean, for either of those objects. Does this exist?

**Comment by stain** [comment]
Now it would make sense as a BagIt to just add a `ro-crate-metadata.json` file according to [RO-Crate](https://w3id.org/ro/crate/1.0/) - this could at least describe the workflow JSON and the derivation. 

Adding BioCompute IEEE 2791 would also make sense as I don't think it has a packaging at the moment.

Further work could look at the history provenance and model it according to [CWLProv](https://w3id.org/cwl/prov) with timestamps etc - but that would be more detailed and kept in a separate [PROV](https://www.w3.org/TR/prov-overview/) document - we would have to decide which flavour, e.g. PROV-XML vs PROV-JSON vs JSON-LD vs Turtle.

**Comment by stain** [comment]
See also #9077. We suggested this as topic for the BCC [CoFest](https://www.open-bio.org/events/bosc/collaborationfest/) - hoping @HadleyKing et al will join!

**Comment by HadleyKing** [comment]
> Now it would make sense as a BagIt to just add a `ro-crate-metadata.json` file according to [RO-Crate](https://w3id.org/ro/crate/1.0/) - this could at least describe the workflow JSON and the derivation.
> 
> Adding BioCompute IEEE 2791 would also make sense as I don't think it has a packaging at the moment.
> 
> Further work could look at the history provenance and model it according to [CWLProv](https://w3id.org/cwl/prov) with timestamps etc - but that would be more detailed and kept in a separate [PROV](https://www.w3.org/TR/prov-overview/) document - we would have to decide which flavour, e.g. PROV-XML vs PROV-JSON vs JSON-LD vs Turtle.

Right now the #9077 is creating a BioCompute [IEEE 2791](https://opensource.ieee.org/2791-object/ieee-2791-schema/) compliant JSON via API and mostly the [workflow invocation](https://github.com/biocompute-objects/galaxy/blob/482b92d9b10701eb1bf94b7d0ce1134c70a6ab3a/client/galaxy/scripts/components/bco/BioComputObject.vue). There is a [download feature](https://github.com/biocompute-objects/galaxy/blob/482b92d9b10701eb1bf94b7d0ce1134c70a6ab3a/client/galaxy/scripts/components/WorkflowInvocationState/WorkflowInvocationState.vue#L67) and I am working on finishing up allowing some basic editing and modification via a [UI](https://github.com/biocompute-objects/galaxy/blob/e11c49c1b55eace66c23c6692f12b1d588f3a1f7/client/galaxy/scripts/components/WorkflowInvocationState/WorkflowInvocationState.vue#L64), all of which @nsoranzo and I will be presenting as a lightening talk, demo, and poster at BCC2020 

Looking through all (RO, CWL) of the material you have linked to @stain I see many correlations as well as very similar edits to the same spaces in the galaxy code. We should defiantly see where we can overlap our existing and future efforts. Thanks for the invite, I will be there!

**Comment by HadleyKing** [comment]
@syntheticgio @skeeney01 @kee007ney 
This could also tie in nicely with the BCO class definition implementation. There is a lot to unpack here, but this could be a good use case to start with.

**Comment by mvdbeek** [comment]
Implemented in https://github.com/galaxyproject/galaxy/pull/14595
