### ISSUE TITLE
[15.05] Regression: not possible for admins to see dataset file_name through API

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#313]
Since `release_15.05` it is not more possible for (only) admins to see the `file_name` in the dataset dict returned by the API calls `/api/datasets/<dataset_id>` and `/api/histories/<history_id>/contents/<dataset_id>`.
Setting `expose_dataset_path = True` in `config/galaxy.ini` would still allow all users to see the file paths.

Relevant code is at: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/managers/datasets.py#L176

Ping @carlfeberhard .

**Comment by carlfeberhard** [comment]
Good catch, nsoranzo: thanks very much!
