### ISSUE TITLE
TO and FROM address are the same for the "galaxy tool error report"

### ISSUE THREAD

**Issue by hrhotz** [galaxyproject/galaxy#3144]
When sending a "galaxy tool error report" mail, the TO and FROM address are the same. For example on our server:

From: help.bioinformatics@fmi.ch
Subject: Galaxy tool error report from hansrudolf.hotz@fmi.ch (Grouping1)
To: help.bioinformatics@fmi.ch, hansrudolf.hotz@fmi.ch

mails sent to "help.bioinformatics@fmi.ch" end up in our helpdesk ticketing system. However, a change in the helpdesk ticketing system we use, does not allow the creation of a ticket where  the TO and FROM address are the same anymore. As a result the error reports get unnoticed. I can fix that on our side.

Nevertheless, I wonder, what is the reason for sending out a mail with such a configuration? I have looked at the code (~/lib/galaxy/tools/errors.py). At line 233, the FROM address gets the value of the TO address. It has been like this for years. Why? Wouldn't it make more sense, to change the FROM address to the user's address if there is one?

I don't wanna make a pull request yet, but I am happy to do so....unless there is a reason for this situation

Hans-Rudolf

**Comment by nsoranzo** [comment]
@hrhotz I think that forging the FROM address to be the user email would not be accepted by many SMTP servers.

**Comment by hrhotz** [comment]
@nsoranzo thank you very much for the explanation. This makes sense.
Though, it seems, our SMTP server does accept it.

**Comment by nsoranzo** [comment]
That's bad practice as it allows [email spoofing](https://en.wikipedia.org/wiki/Email_spoofing) and can be used by spammers.
Can we close the issue or do you have alternative suggestions?

**Comment by hrhotz** [comment]
sure we can close
