### ISSUE TITLE
Feature request: Supporting SAML as External Authenticator 

### ISSUE THREAD

**Issue by abdulrahmanazab** [galaxyproject/galaxy#3146]
Hi Galaxy,

You are now supporting openID as external authenticator, which is great :) 

Now, this feature is requested by ELIXIR-EU and NeIC (Nordic e-Infrastructure Collaboration). The main benefit is to be able to support eduGAIN and Kalmar2 (both are based on SAML). Not having SAML supported is stopping us from having more public servers. We have one in Oslo 'Lifeportal' where we had to hack Galaxy to support Kalmar2 and eduGAIN, which is not the best practice.

**Comment by nsoranzo** [comment]
https://en.wikipedia.org/wiki/Security_Assertion_Markup_Language

**Comment by jxtx** [comment]
Thanks @nsoranzo. Why is this not best handled at the webserver proxy level by an authentication module? Is more support needed from Galaxy than just authentication here?

**Comment by abdulrahmanazab** [comment]
Thanks for the response! 
@jxtx Technically the answer is 'yes'. But the issue is not only technical, but political (especially for NeIC). It is 'for some reason' a requirement that that portal application 'itself' supports SAML for it to be deployed in certain sites. What is needed from Galaxy (in this issue) is to provide support for SAML based External authenticators (similar to Galaxy's support for openID).

**Comment by bgruening** [comment]
So @abdulrahmanazab are you planning to work on this :)

**Comment by hexylena** [comment]
Most people who need this do so via apache/nginx, and probably solved for everyone in this thread with AAI :)
