### ISSUE TITLE
GFF file sniffed as BED

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#3148]
Any uploaded file with 60 initial lines of comment (empty or starting with '#') will be sniffed as BED.
Relevant code from `lib/galaxy/datatypes/interval.py`:
```python
class Bed( Interval ):
...
    def sniff( self, filename ):
        headers = get_headers( filename, '\t' )
        try:
            if not headers:
                return False
            for hdr in headers:
                if (hdr[0] == '' or hdr[0].startswith( '#' )):
                    continue
...
            return True
        except:
            return False
```

**Comment by mvdbeek** [comment]
I also noticed this, the latest gff for dm6 has ~2000 scaffolds listed in the header.

**Comment by nsoranzo** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/4239.
