### ISSUE TITLE
Feature request: Add a 'whitelist_file' attribute in galaxy.ini

### ISSUE THREAD

**Issue by abdulrahmanazab** [galaxyproject/galaxy#3156]
Hi Galaxy,

This feature request is from NeIC (Nordic e-Infrastructure Collaboration). You have a cool attribute in galaxy.ini, 'blacklist_file' is used for filtering out users that are using disposable email address during the registration. We would like to have a 'whitelist_file' attribute. 
This should be very easy to implement ;)
If you are extremely busy, guide me where to fix this in the code and I can submit a pull request (if you think it is a good feature to have off course :)

**Comment by martenson** [comment]
This is now configurable here: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/galaxy.yml.sample#L774
