### ISSUE TITLE
Draw phylogeny 1.0.0 has dependency issue at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3158]
**Tool**

- Draw phylogeny (Galaxy Version 1.0.0)
- https://toolshed.g2.bx.psu.edu/view/devteam/t2ps/4d9910e996f7

**Error**

> Detailed Job Information
> 
> Job environment and execution information is available at the job Info Page.
> Job ID	XXX
> Tool ID	toolshed.g2.bx.psu.edu/repos/devteam/t2ps/Draw_phylogram/1.0.0
> Tool Version	1.0.0
> Job PID or DRM id	XXX.roundup
> Job Tool Version	
> Job Execution and Failure Information
> 
> Command Line
> 
> python /galaxy/test/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/t2ps/dee81096ec71/t2ps/t2ps_wrapper.py /galaxy/test/files/XXX /galaxy/test/files/XXX 8 8 0 1
> 
> stderr
> 
> /bin/sh: ps2pdf: command not found
> 
> stdout
> 
> Job Information
> 
> None

cc @galaxyproject/guac

**Comment by natefoo** [comment]
This tool needs to have a dependency on ghostscript added. Probably worth filing an issue on galaxyproject/tools-devteam for it? It should be a pretty quick/easy fix since there's already a TS ghostscript package (and it could use Conda as well).

**Comment by jennaj** [comment]
Closing, tool is no longer supported or on http://usegalaxy.org
