### ISSUE TITLE
Link to a Galaxy intro tour from the default welcome page

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#3164]
suggested by @lparsons

**Comment by peterjc** [comment]
Do you mean an introductory video?

**Comment by martenson** [comment]
@peterjc I mean Galaxy Tour (e.g. https://usegalaxy.org/tours/core.galaxy_ui)

**Comment by peterjc** [comment]
Very cool - I missed this in the 2016.01 release, described in  https://wiki.galaxyproject.org/News/2016_01_GalaxyRelease

Is there any documentation for how to use this on a local Galaxy instance (even just running the provided tours locally)? Otherwise there is no point putting it on the default welcome page.

**Comment by martenson** [comment]
@peterjc Newer Galaxies should have 3 basic tours included and others are in the making (https://github.com/galaxyproject/galaxy-tours). It is under the Help menu.

**Comment by bgruening** [comment]
@peterjc and it is an integral part of the recent GTN efforts: https://github.com/bgruening/training-material

@dannon has also a prototype of a FF plugin to create those tools!!!!

**Comment by peterjc** [comment]
Confirmed - thanks. That does exist on our local instance. Just the handy URL of `.../tours/` does not seem to work. Should it?

**Comment by dannon** [comment]
@peterjc What release are you at on your local instance?  I created the routing for that URL after the initial release of tours.

**Comment by peterjc** [comment]
@dannon We are be on `release_16.01`, specially commit https://github.com/galaxyproject/galaxy/commit/e77d3f009a8e2fb51e97f41b4c47e397c90cbcea on master branch - sounds like we'll get the URL routing next time we update :)
