### ISSUE TITLE
Issue with Ldap on version 16.07 SERVER_DOWN: {'desc': "Can't contact LDAP server"} however server is working

### ISSUE THREAD

**Issue by squancey88** [galaxyproject/galaxy#3178]
We are attempting to update our galaxy installation. I pulled the existing git over the top of the current install. This all worked fine and we have an operational galaxy server however we used LDAP to authenticate users and this stopped working after the update. In the logs we got the following error.

> Traceback (most recent call last):
>   File "/home/galaxy/galaxy-dist/lib/galaxy/auth/providers/ldap_ad.py", line 126, in authenticate
>     l.simple_bind_s()
>   File "/home/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 223, in simple_bind_s
>     resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all=1,timeout=self.timeout)
>   File "/home/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 514, in result3
>     resp_ctrl_classes=resp_ctrl_classes
>   File "/home/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 521, in result4
>     ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
>   File "/home/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 106, in _ldap_call
>     result = func(*args,**kwargs)
> SERVER_DOWN: {'desc': "Can't contact LDAP server"}

I tested the LDAP connection myself and from the native python on the machine I could connect using the LDAP module method simple_bind_s() however when I activate the venv of galaxy I could not. I was able to fix the issue by reinstalling the python-ldap module from source in the venv.

Not sure if there is an issue with the python-ldap module you use to setup the virtual env?

**Comment by nsoranzo** [comment]
@squancey88 Thanks for your report! Can you double check that you can reproduce the problem after executing the following:

```
$ cd /home/galaxy/galaxy-dist/
~/galaxy-dist$ . .venv/bin/activate
(.venv)~/galaxy-dist$ pip uninstall -y python-ldap
Uninstalling python-ldap-2.4.27:
  Successfully uninstalled python-ldap-2.4.27
(.venv)~/galaxy-dist$ ./scripts/common_startup.sh
...
Installing collected packages: python-ldap
Successfully installed python-ldap-2.4.27
```

**Comment by squancey88** [comment]
@nsoranzo I have done as suggested, and the error still occurs, with the same error message as before.

**Comment by squancey88** [comment]
@nsoranzo I should have mentioned this earlier but I forgot, when I installed the python-ldap from source it did complain about missing a header file, which I think was sasl.h (I can confirm this later). But the one included in galaxy didn't appear to have the same issue.

I am running on a VM so have the luxury of rolling back to pre-update to try again, so I attempted another update but first installing the missing dependency then updating galaxy but still had the same issue. Hope this bit of extra info helps, if you need any clarification just ask.

**Comment by nsoranzo** [comment]
> I should have mentioned this earlier but I forgot, when I installed the python-ldap from source it did complain about missing a header file, which I think was sasl.h (I can confirm this later). But the one included in galaxy didn't appear to have the same issue.

That's because the wheel installed by Galaxy is pre-compiled.

Regarding the source of your problem, are you maybe using a self-signed certificate for the LDAP server? If yes, you can try to add:

```
<ldap-options>OPT_X_TLS_REQUIRE_CERT=OPT_X_TLS_ALLOW</ldap-options>
```

to your `config/auth_conf.xml` file.

**Comment by squancey88** [comment]
Thanks for response. Had a look at the ldap settings (I was not involved in the original installation of galaxy). It is using ldaps as the protocol but not sure if its self signed, can contact our information services department for confirmation. 

I tried adding the line as you suggested, still not able to login but I get a different error now.

> galaxy.auth.providers.ldap_ad DEBUG 2016-11-17 11:19:23,324 LDAP authenticate: Valid LDAP option pair OPT_X_TLS_REQUIRE_CERT=OPT_X_TLS_ALLOW -> 24582=3
> galaxy.auth.providers.ldap_ad ERROR 2016-11-17 11:19:23,324 LDAP authenticate: search exception
> Traceback (most recent call last):
>   File "/home/galaxy/galaxy-dist/lib/galaxy/auth/providers/ldap_ad.py", line 117, in authenticate
>     ldap.set_option(_opt)
>   File "/home/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/ldap/functions.py", line 135, in set_option
>     return _ldap_function_call(None,_ldap.set_option,option,invalue)
>   File "/home/galaxy/galaxy-dist/.venv/local/lib/python2.7/site-packages/ldap/functions.py", line 66, in _ldap_function_call
>     result = func(_args,**kwargs)
> ValueError: option error

Any thoughts? The only change I made was suggested line. I know the file worked (minus line you suggested) when I compile the library myself.

**Comment by nsoranzo** [comment]
You are right, I can replicate the "option error" using the pre-compiled wheel, but not using `python-ldap` from PyPi.
There seems to be something wrong in how the `python-ldap` wheel has been compiled on StarForge, ping @abretaud.

**Comment by abretaud** [comment]
For the option error, maybe a ssl/tls related lib is missing?
Are using ssl (ldaps:// in the server url)?
I use the wheel on our servers without problem, but it's not using ssl

**Comment by squancey88** [comment]
Hi @abretaud, sorry for late reply. Yeah we are using ldaps:// if I use the wheel version I cannot get it to work but if I install python ldap myself it works fine

**Comment by kassammo** [comment]
Hello @squancey88 ,

I have the same probelm like you, we are using ldaps://, have you find a solution ?

Thanks

Mohamed

**Comment by wholtz** [comment]
I am seeing the same behavior. The wheel version cannot connect using ldaps:// but if I compile python-ldap myself, then l can connect over ldaps://. 

The wheel version does return 1 for ldap.TLS_AVAIL and ldap.SASL_AVAIL, indicating those optional functionalities were configured at build time.

**Comment by nsoranzo** [comment]
Can someone open an issue at https://github.com/galaxyproject/starforge/issues for this?

**Comment by abretaud** [comment]
Done: https://github.com/galaxyproject/starforge/issues/130
It's in my todo list, but not at the top for now :/

**Comment by bernt-matthias** [comment]
Is there a temporary workaround for this issue? Could one replace the python ldap module in the galaxy venv by a self-compiled version?

**Comment by wholtz** [comment]
@bernt-matthias - Yes, I have been able to locally compile python-ldap and use it with galaxy 16.07 to make ldaps:// connections. 

On a Ubuntu 16.04 system I needed the following packages to compile python-ldap with SSL support: libsasl2-dev python-dev libldap2-dev libssl-dev libsasl2-dev packages.

I believe the steps I took were simply:
source galay-dist/.venv/bin/activate
pip install --upgrade python-ldap

I don't think I had to remove anything, but my notes are not comprehensive.

**Comment by bernt-matthias** [comment]
That was really helpful and nearly correct: 

I needed cyrus-sasl. And I compiled openldap using the configure option --enable-spasswd (not sure if really necessary, but it integrates sasl support). 

What took me most time that after pip install --upgrade python-ldap the old python-ldap version is reinstalled, since the version is pinned in the requirements. So I needed to edit: lib/galaxy/dependencies/conditional-requirements.txt

**Comment by kalylia** [comment]
My workaround is to use STunnel. Galaxy connects to ldap://localhost:someport and STunnel connects that localhost-port with the ldaps-port of my ldap-server.

**Comment by abretaud** [comment]
I finally found some time to work on this in https://github.com/galaxyproject/starforge/pull/146
If you have the possibility it would be nice to test the wheels that were generated there:
https://depot.galaxyproject.org/starforge/wheels/build-213/

**Comment by bernt-matthias** [comment]
Wonderful. I could test it on our instance, but I would need some more detailed instructions. I'm unexperienced with wheels and still quite new to galaxy.

**Comment by abretaud** [comment]
Ah yes, to test, on a galaxy instance you will need to activate the galaxy virtualenv:
```
cd /to/galaxy/root/dir
. .venv/bin/activate
```

then remove the installed python-ldap module:

```
pip uninstall python-ldap
```

And install the new one:

```
pip install https://depot.galaxyproject.org/starforge/wheels/build-213/python_ldap-2.4.41-cp27-cp27mu-manylinux1_x86_64.whl
```
(choose the right one depending on your architecture)

You can get back to the previous install by removing the new python-ldap (`pip uninstall python-ldap`) then reinstalling the one you had before (`pip install python-ldap` I suppose)

**Comment by abretaud** [comment]
@bernt-matthias did you find the time to test it?

**Comment by bernt-matthias** [comment]
Sorry for the delay. 

`pip install https://depot.galaxyproject.org/starforge/wheels/build-213/python_ldap-2.4.41-cp27-cp27mu-manylinux1_x86_64.whl
`
gives me:

`python_ldap-2.4.41-cp27-cp27mu-manylinux1_x86_64.whl is not a supported wheel on this platform.`

**Comment by abretaud** [comment]
Ok, you can try this one instead: https://depot.galaxyproject.org/starforge/wheels/build-213/python_ldap-2.4.41-cp27-cp27m-manylinux1_x86_64.whl

**Comment by bernt-matthias** [comment]
Got it installed. Now I get the old error in the galaxy logs: 

```
galaxy.auth.providers.ldap_ad DEBUG 2017-09-07 12:42:45,221 LDAP authenticate: Valid LDAP option pair OPT_X_TLS_REQUIRE_CERT=OPT_X_TLS_ALLOW -> 24582=3
galaxy.auth.providers.ldap_ad ERROR 2017-09-07 12:42:45,241 LDAP authenticate: set_option exception
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/auth/providers/ldap_ad.py", line 117, in authenticate
    ldap.set_option(*opt)
  File "/data/galaxy_server/galaxy-dev/.venv/lib/python2.7/site-packages/ldap/functions.py", line 135, in set_option
    return _ldap_function_call(None,_ldap.set_option,option,invalue)
  File "/data/galaxy_server/galaxy-dev/.venv/lib/python2.7/site-packages/ldap/functions.py", line 66, in _ldap_function_call
    result = func(*args,**kwargs)
ValueError: option error
```

**Comment by abretaud** [comment]
Oops, strange. Did you restart galaxy?

**Comment by bernt-matthias** [comment]
Yep I did .. and verified that the 2.4.41 version is really installed. 

But actually I'm a bit confused at the moment, because I have a working solution ... 

Currently I use python-ldap 2.4.43 (which is installed manually with pip inside Galaxy's venv .. seems to be the latest). As far as I can see in addition I compiled the following software from source: 
- Python-2.7.13 (which I needed to do to get Galaxy running, because our CentOS had only a really old python installed which made problems - probably this is not necessary for this problem)
- cyrus-sasl-2.1.25
- openldap-2.4.45 (with configure options --disable-slapd --enable-spasswd)

and then the python-ldap 2.4.43 from pip worked. To get this into Galaxy I just needed to edit lib/galaxy/dependencies/conditional-requirements.txt to allow newer versions of python-ldap. Otherwise python-ldap is downgraded on startup (I needed a while to figure this out).

So the python-ldap==2.4.27 (which is currently Galaxy's default) and your version don't work, but the python-ldap 2.4.43 from pip works if I setup the openldap libraries appropriately. 

Maybe its not working with your wheel because my openldap-2.4.45 in compiled in a wrong way?

**Comment by abretaud** [comment]
That's odd...
Your openldap version shouldn't be a problem as our wheel is linked statically to the *good* openldap version
You changed the version to 2.4.41 in conditional-requirements.txt when you tested?
I'll make more tests next week (and update to 2.4.44, I didn't notice all these releases in the last days!)

**Comment by abretaud** [comment]
Ok, some libraries were missing for ldaps connection, can you test this new wheel ?
https://depot.galaxyproject.org/starforge/wheels/build-254/python_ldap-2.4.44-cp27-cp27m-manylinux1_x86_64.whl

**Comment by bernt-matthias** [comment]
I did some tests. It installs without problems and it also works.

**Comment by abretaud** [comment]
Cool, thanks!

**Comment by PreenaPrakash** [comment]
Caught LDAPError while authenticating : SERVER_DOWN({u'info': 'Transport endpoint is not connected', 'errno': 107, 'desc': u"Can't contact LDAP server"},)

I am trying to Integrate Active Directory to my application.
using Django==1.11.26

django-auth-ldap==1.7.0

python-ldap==3.2.0


Anyone please help on this ?
