### ISSUE TITLE
History options part of the History Introduction tour is broken

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#3182]
Discovered with @moheydarian, the part of the History Introduction tour that clicks on the history options cog is broken leading to the following screen:
![screen shot 2016-11-16 at 11 36 59 am](https://cloud.githubusercontent.com/assets/338642/20356225/dce7060a-abf1-11e6-95e5-4ddb1f081b2b.png)

**Comment by dannon** [comment]
@afgane Thanks, I'll check this out and fix it!

**Comment by dannon** [comment]
Fixed in #3185
