### ISSUE TITLE
list:paired collections fail as input to tools with collection_type="paired"

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#3202]
If you create a simple list:paired collection and try to use this with the iuc's sickle (which accepts paired collections), the job submission fails with
```
The server could not complete the request. Please contact the Galaxy Team if this error persists. Error executing tool: Problem decoding element identifier {'src': 'new_collection', 'collection_type': '', 'name': u'r', 'element_identifiers': [{'__object__': <galaxy.model.HistoryDatasetAssociation object at 0x7fd43d0f00d0>, 'name': u'forward'}, {'__object__': <galaxy.model.HistoryDatasetAssociation object at 0x7fd420577950>, 'name': u'reverse'}]} - must contain a 'src' and a 'id'.
{
    "tool_id": "toolshed.g2.bx.psu.edu/repos/iuc/sickle/sickle/1.33",
    "tool_version": "1.33",
    "inputs": {
        "readtype|single_or_paired": "pe_collection",
        "readtype|input_paired": {
            "values": [
                {
                    "hid": 11,
                    "id": "54f2a3a23292eb07",
                    "map_over_type": "paired",
                    "name": "list of pairs",
                    "src": "hdca"
                }
            ],
            "batch": true
        },
        "qual_threshold": "20",
        "length_threshold": "20",
        "no_five_prime": "false",
        "trunc_n": "false"
    }
}
```
My understanding is that this should work and create a new job per paired dataset in the list collection, right?
I'm checking now if this is a recent regression (I'm on the latest dev).

**Comment by mvdbeek** [comment]
This is also failing on release_16.07, so not a new bug.

**Comment by jmchilton** [comment]
This seems like a bug - is it easy to test even older versions of Galaxy?

**Comment by mvdbeek** [comment]
Sure, going back now.

**Comment by jmchilton** [comment]
We do have tests for this though... is there something odd with your collection or maybe the tool?

**Comment by mvdbeek** [comment]
Hmm, I came across this doing my own tool, and then went on to confirm this with sickle.
BTW, 16.04 same problem:
```
Error executing tool: Problem decoding element identifier {'src': 'new_collection', 'collection_type': '', 'name': u'1r', 'element_identifiers': [{'__object__': , 'name': u'forward'}, {'__object__': , 'name': u'reverse'}]} - must contain a 'src' and a 'id'.
```

**Comment by jmchilton** [comment]
Hmm... well this stinks. I'll try to take a look today.

**Comment by mvdbeek** [comment]
Might have to do with the input section being in a conditional. I'll see if other tools that accept paired collections work.

**Comment by mvdbeek** [comment]
So hisat2 does work ...

**Comment by mvdbeek** [comment]
@jmchilton 
Taking out the `structured_like=` tag [here](https://github.com/galaxyproject/tools-iuc/blob/master/tools/sickle/sickle.xml#L142) makes the tool run ... but produces 2 lists of dataset pairs (I have 1 list of 2 dataset pairs), which is wrong.

**Comment by mvdbeek** [comment]
I guess this fails somewhere around https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/parser/output_objects.py#L128, because element is still a paired dataset?!

**Comment by mvdbeek** [comment]
> Taking out the structured_like= tag here makes the tool run ... but produces 2 lists of dataset pairs (I have 1 list of 2 dataset pairs), which is wrong.

I really don't know how I managed to get to that conclusion, but that's just wrong. Taking out the structured_like tag produces a single list with paired dataset collections, as it should, except that the element identifiers seem to be lost.
