### ISSUE TITLE
Enhance admin UI to allow manual user activation.

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#3208]
To circumnavigate issues with unreliable email providers that eat the activation emails.

ping @jennaj

**Comment by jmchilton** [comment]
Hey @ic4f - how does this sound?

**Comment by jdavcs** [comment]
I'm on it.

**Comment by martenson** [comment]
for bonus points, xref: https://github.com/galaxyproject/galaxy/issues/6981

**Comment by jmchilton** [comment]
Amazing and awesome, thanks so much @ic4f !

**Comment by dannon** [comment]
Added in #9143
