### ISSUE TITLE
HTTP API - create workflow from_history_id

### ISSUE THREAD

**Issue by jibe-b** [galaxyproject/galaxy#3225]
The HTTP API is currently needed to create workflows from stored histories programmatically as discussed in [this issue](https://github.com/galaxyproject/bioblend/issues/204).

When passing the request
> POST
> /api/workflows
> Content-Type: application/json
> payload: {\"from_history_id\": \"123123123123\",  \"workflow_name\": \"w0\"}

a workflow is created but it does not contain the steps of the original non empty history.

**Comment by bgruening** [comment]
Which steps does it contain? I'm wondering what the UI is actually using if someone triggers the history extraction option ...

**Comment by jibe-b** [comment]
I follow the track of `build_from_current_history`

**Comment by jibe-b** [comment]
it simply executes [galaxy/lib/galaxy/webapps/galaxy/controllers/workflow.py](github/galaxy/lib/galaxy/webapps/galaxy/controllers/workflow.py)

**Comment by jibe-b** [comment]
while the API executes [ galaxy/lib/galaxy/webapps/galaxy/api/workflows.py
](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/workflows.py)

**Comment by jibe-b** [comment]
The payload must contain the job_ids in order to extract steps.

In http://galaxy.readthedocs.io/en/master/lib/galaxy.webapps.galaxy.api.html#module-galaxy.webapps.galaxy.api.workflows

> job_ids (str) – If from_history_id is set - optional list of jobs to include when extracting a workflow from history

is a bit misleading: if one wants to extract a workflow with steps, job_ids are not optional (to what I understood by using the API).
