### ISSUE TITLE
[Errno 13] Permission denied: '/galaxy-repl/main/files/_metadata_files/000'

### ISSUE THREAD

**Issue by federico86** [galaxyproject/galaxy#3231]
Hi,
since few days, when trying to visualize my Bowtie2 data on IGV or UCSC, I get this error message :

There was a conflict when trying to complete your request. 
Error generating display_link: [Errno 13] Permission denied: '/galaxy-repl/main/files/_metadata_files/000'

Any idea how to solve this?

Thank you for your help.
Best,
Federico

**Comment by natefoo** [comment]
We are transferring some missing metadata files that were missed in a recent storage move. This should be done within the next 24 hours or so.

**Comment by jennaj** [comment]
Older and seems resolved, closing
