### ISSUE TITLE
Deployment Testing

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3246]
Extend testing framework and the forthcoming galaxy_selenium project to implement a customizable deployment testing suite. In particular, add a test for Jupyter which seems to break frequently. Tests for upload, certain tools, etc... should be added as well.

Create a configuration for test.galaxyproject.org and usegalaxy.org. Run them on jenkins.galaxyproject.org and let Nate when things break.

**Comment by natefoo** [comment]
+1. Had something like this that worked briefly back in the buildbot days.
