### ISSUE TITLE
UI problems with input datasets in workflow editor

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#3249]
To reproduce,

1. Log into a Galaxy, e.g. http://usegalaxy.org
2. Create a new history
3. Click upload tool, select paste/fetch data, txt format:

```
alpha
beta
gamma
delta
epsilon
```

4. Run "Line/Word/Character count" tool on this text file, pick "Word count" only, no headers
5. Confirm history has second dataset, tabular format, just one line of text:

```
5
```

6. Click on the top right "cog" icon for "History options", select "Extract workflow"
7. Leave dataset one ticked as "Treat as input dataset", leave "Pasted entry" as caption
8. Click "Create Workflow"
9. Blue banner appears, click on "edit" workflow
10. Workflow appears with "Input dataset" and "Line/Word/Character count"
11. Click on "Input dataset", name should be "Pasted entry" in right hand "Details" column (but see #3247)
12. Click on name, change it to "Words to count". Nothing changes in the main display.

![screen shot 2016-12-01 at 16 41 40](https://cloud.githubusercontent.com/assets/63959/20802814/298c3378-b7e5-11e6-9b26-b88947e90505.png)

13. Click on the yellow text above this, surprisingly can change the tool name. Make it "THIS SHOULD BE READ ONLY". Notice the main display of the workflow updates to use this.

![screen shot 2016-12-01 at 16 40 58](https://cloud.githubusercontent.com/assets/63959/20802830/3570237a-b7e5-11e6-864c-1cf12aae3f9d.png)

14. Save the workflow. Run the workflow
16. Should get:

Step 1: Input dataset
Words to count
etc

Notice the input name changed correctly, but the tool name change had no effect.

17. Go back and edit the workflow, notice both the tool name "THIS SHOULD BE READ ONLY" and the input name "Words to count" have been preserved.
18. Download the workflow as a ``*.ga`` file confirms both these strings are saved.

Expected behaviour:

It is very strange that the UI allows *both* the tool name (on a yellow background) and the name below it (on a white background) to be editable. Only the second seems to be functionally important.

Personally I think the input tool should have a fixed name "Input dataset" (the yellow field should be read only), but in the main workflow "noodle" display, rather than this, it should show the name given to the input data (the same caption shown to the user when the workflow is executed).

![screen shot 2016-12-01 at 16 43 21 copy](https://cloud.githubusercontent.com/assets/63959/20802993/acb9b950-b7e5-11e6-878e-56c40ae100dd.png)

**Comment by peterjc** [comment]
Basically I think there should be one editable field here, which gets shown to the user when running the workflow AND gets used on the workflow editor main window to title the yellow box. You could also do this:

![screen shot 2016-12-01 at 16 43 21](https://cloud.githubusercontent.com/assets/63959/20803291/8c8c2a36-b7e6-11e6-9b0b-9a99e812aff1.png)

In some ways this is nicer as it means the yellow background is always used for the main workflow editor box title AND the right hand side details pane. The input datasets are always going to be a special case so this seems OK to me.

(You'd need to be careful at a technical level though for backwards compatibility about which fields are used for this text - right now there are two separate strings but only one is shown to the user when executing the workflow)

**Comment by jmchilton** [comment]
This is a very expanded and informative clarification of the small point in checkbox 3 on #1325 and discussed in #1251. Thanks a bunch for this issue!

Absolutely agree that there should be just one concept. I think this comes down to eliminating the "name" - the workflow step label (thing in the title bar) is the better since every kind of workflow step type can use it. It is more useful when programmatically building these things up, its uniqueness is ensured, etc.... 

If it gets merged, we are taking a step toward eliminating "name" with #3369. I guess it might be a bit of a sideways step relative to what you requested here but I think it is the right direction to move in.

@guerler has some outstanding work in replacing the backend for that side form where the name appears. After it is merged I think the next step is to just eliminate that name field in the workflow editor.

If we load a workflow with input dataset names - just pop up a display confirming to the user that we are replacing the names with labels and ensuring they are unique and the changes will take affect the next time they save the workflow.

Existing backend API work supporting the older input dataset name is all well tested and can sit around indefinitely IMO. But the display of these things should focus on labels and concepts that span step types.

**Comment by guerler** [comment]
I am not sure what the consensus is. Do we want to remove the `name` field or the newer `label` field? Would the later not be easier, since `name` has been supported for quite some time and can be augmented to exhibit the same benefits.

**Comment by dannon** [comment]
Hrmm.  Yeah, taking a quick look at it, it does seem like we should have just enhanced 'name' instead of adding 'label' in the first place.  I'm digging through the label PR now to look at rationale.

**Comment by jmchilton** [comment]
The label applies uniformly to all node types and is guaranteed to be unique. I think that these are important points. If you start building up workflows in a text editor or writing workflow test files or using the API I think these properties are important.

Update: I guess I argued labels are cool and important. I'd also argue that "name"s are a bit problematic. They don't apply at all to tool steps - and here I think it is as important as inputs. What is this particular cut, mapping, or filtering step doing if there are two instances. Also storing this field that should apply to all workflow steps inside a JSON blob that has a conflicting meaning for tools is problematic. The database should be normalized as much as possible so the label should be a column in the database.

**Comment by dannon** [comment]
I'm not sure it's cleaner to add this new field and migrate (or not)  and deprecate, or whether it'd be better *for most users* to use the existing field they're used to, and just enhance it.

Edit: to be clear, I don't disagree that both additions are important, I'm just trying to sort out how we can get this functionality in a way that's easy for users to understand and start (or continue) using.

**Comment by jmchilton** [comment]
If you think about how to add names to tool steps - to my mind it is clear that we can be most consistent the UI if we do this the same way for inputs and tools and other modules. If we want to special case inputs though and retain the input box - I guess it is fine but it seems like a mistake to me.

**Comment by dannon** [comment]
Sorry, wasn't clear.  I'm not questioning anything about the UI changes here.  I don't want to keep the input box UI element at all, so +1 to moving this into that step title bar, for sure.  What I'm concerned with is related to my hunch (though we could certainly check this) that a lot of users have never used the new labels, and that most people have annotated their workflows using the 'name' fields, if at all.

It seems like, even if we go with the new 'label' model, we should have a simple migration that automatically moves previously applied 'names' forward.  Maybe we should have done this when it was first introduced, it'd have been easier, but it'd still be possible for a vast majority of cases I'd guess.

**Comment by jmchilton** [comment]
> we should have a simple migration that automatically moves previously applied 'names' forward

Absolutely - I agree with this and try to convey it above. Users shouldn't need to care and this should be rather automatic - just a small note in the UI that is going to happen on save. I'll implement this today if we can all get onboard for labels.

> Maybe we should have done this when it was first introduced, it'd have been easier,

Agreed - probably it would have been easier and clearer - but I don't think there are many workflows that have both.

> but it'd still be possible for a vast majority of cases I'd guess.

Agreed.

**Comment by jmchilton** [comment]
Also #3369 falls back to using the older dataset name if a label isn't present - so if we agree to changing the UI to use the title bar I'm not sure anything is changing for users that aren't using say API scripts.

**Comment by dannon** [comment]
> I'll implement this today if we can all get onboard for labels

I'm on board with labels if we implement this path forward, sounds good to me!

**Comment by jmchilton** [comment]
> I'm on board with labels if we implement this path forward, sounds good to me!

Awesome sauce - thanks for talking this through @dannon. I think this will be a much clearer user experience than the current status quo. 

@guerler - how does this sound to you? If you are on board do you me to to drop these changes on top of #3369 or resolve this in a separate PR more focused on just the workflow editor?

**Comment by guerler** [comment]
Cool. Its up to you. A separate PR sounds good to me.

**Comment by peterjc** [comment]
This plan sounds good, thanks.

**Comment by jmchilton** [comment]
I want to buildup more visual cues about editing labels and provide improved help messages for tool version upgrades and label modifications before opening a PR on this - but I do have the guts working with https://github.com/jmchilton/galaxy/commit/aebf685fb5be00534913c1bb0b7365ebcb16cae3 and the start of a Selenium test in https://github.com/jmchilton/galaxy/commit/c14220f9a1e12ac5c34713f47c0bc1e6a3ebbc64.

**Comment by guerler** [comment]
This has been addressed in #3644. Please re-open if something is missing.
