### ISSUE TITLE
user search box UI problems when expose setting false

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#3250]
This test and the screenshots were done with Chrome 54.0.2840.98 on Mac OS X.

1. Log into https://usegalaxy.org/
2. If you haven't already, create a test workflow
3. Click on "Workflows" in the top ribbon
4. For any of your workflows, select the drop down menu entry "Share or Download"
5. Click on "Share with a user"
6. Prompted to enter another user's email address (implicitly as used within this Galaxy instance)

![screen shot 2016-12-01 at 17 25 16](https://cloud.githubusercontent.com/assets/63959/20804536/34a92b2a-b7eb-11e6-927e-3754b8b20b15.png)

7. The UI control has a drop down and search, but no real matches come up.
8. If you start typing and pause, e.g. "Dave", it looks like a match is found, and you can click on it.

![screen shot 2016-12-01 at 17 26 56](https://cloud.githubusercontent.com/assets/63959/20804615/79c89146-b7eb-11e6-9eff-162efba8822c.png)

9. The text "Dave" appears in the box - not the email address of a user called Dave.

This non-functional search box is enormously frustrating, especially the apparent autocompletion feature.

This also happened on our local Galaxy instance, and presumably is dependent on these setting in ``config/galaxy.ini``:

```
# Expose user list.  Setting this to True will expose the user list to                                         
# authenticated users.  This makes sharing datasets in smaller galaxy instances                                
# much easier as they can type a name/email and have the correct user show up.                                 
# This makes less sense on large public Galaxy instances where that data                                       
# shouldn't be exposed.  For semi-public Galaxies, it may make sense to expose                                 
# just the username and not email, or vice versa.                                                              
#expose_user_name = False                                                                                      
#expose_user_email = False                                                                                     
```

Perhaps if these expose setting(s) are false, shouldn't prompt should be a plain text box only?

Right now we have ``expose_user_name = True`` on our local instance and it seems to work OK.

**Comment by peterjc** [comment]
@erasche is this the select2  prompt you worked on, e.g. #1111

**Comment by hexylena** [comment]
@peterjc hmm, ok, I see your point, for sites that have BOTH of those settings false, then maybe it would be best to have a plain text box.

**Comment by peterjc** [comment]
Especially as both false is the default. Thanks!
