### ISSUE TITLE
Apache Spark on Galaxy

### ISSUE THREAD

**Issue by leobiscassi** [galaxyproject/galaxy#3254]
Hi galaxy community,
I'd like to know if any of this works [1] [2] are available to general public.

[1] [https://t.co/C4zySDtmw8](https://t.co/C4zySDtmw8)
[2] [https://gcc16.sched.org/event/7Jc3/infinite-galaxy](https://gcc16.sched.org/event/7Jc3/infinite-galaxy)

**Comment by leobiscassi** [comment]
no reply yet

**Comment by dannon** [comment]
@leobiscassi Sorry there wasn't a response here -- I should have suggested earlier to reach out to those authors directly, they may not see this channel.

**Comment by leobiscassi** [comment]
Hi @dannon, no problem. I closed the issue because I solved my problem in other way. Thanks for your suggestion.

**Comment by dannon** [comment]
@leobiscassi Great!
