### ISSUE TITLE
Galaxy seems to not log Conda package installation progress

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#3259]
I have just installed new conda-only fastqc on Main and the only conda-related thing in the log was 

`
galaxy.tools.deps.conda_util DEBUG 2016-12-02 20:08:43,307 Executing command: /galaxy/main/deps/_conda/bin/conda create -y --name __fastqc@0.11.5 fastqc=0.11.5
`

The package installed fine and is actually in the correct folder and seems working.

I checked with @natefoo and he also was used to seeing conda fetching the deps with progress bar and other info.

Was there any change to this? @mvdbeek @bgruening @jmchilton

**Comment by mvdbeek** [comment]
Yes, this is a side-effect of https://github.com/galaxyproject/galaxy/pull/3129/files.
We're only displaying stdout and stderr (as part of a `CommandLineException`) if there is a non-zero exit code.
Would be easy enough to log this unconditionally, if you prefer that.

**Comment by martenson** [comment]
I think it would be useful to include the conda installation progress every time. This is something that admins are looking for, especially during this Conda transition period.

**Comment by natefoo** [comment]
+1, I liked seeing it.
