### ISSUE TITLE
Metadata not being set on dataset collection elements produced by tools

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#3267]
I'm running the tip of the dev branch, and I've recently noticed that metadata is not being generated for output dataset collection elements with tools that produce dataset collections on output.

Here is a simple tool that can be used to reproduce this issue.
```
<tool id="multi_output" name="Multi_Output" version="0.1.0">
  <command>
    <![CDATA[
        #import os
        mkdir -p output &&
        #for $i in range(2):
            #set ofile = 'output_%d.txt' % $i
            #set opath=os.path.join('output', $ofile)
            echo "Hello world" > $opath
        #end for
    ]]>
  </command>
  <inputs>
    <param name="input" type="integer" value="2" />
  </inputs>
  <outputs>
      <collection name="outs" type="list">
          <discover_datasets pattern="__name__" directory="output" visible="false" format="txt" />
      </collection>
  </outputs>
  <tests>
    <test>
    </test>
  </tests>
  <help>
    Help me
  </help>
  <citations />
</tool>
```
The history items that are elements of the collection will not display the expected info: or peek, and, with the exception of the 'dbkey: ?' entry, the metadata is missing in the database for the history_dataset_association records for each collection element.

**Comment by gregvonkuster** [comment]
This is a fairly critical bug for anyone using tools that produce dataset collections.  I hope it doesn't fall through the cracks.  ;)

**Comment by jmchilton** [comment]
It is likely a serious bug - I agree completely. It is restricted to collections discovered dynamically I believe though and it isn't a regression - if this isn't working I doubt it ever did. I can try to take a look today - thanks for the prodding @gregvonkuster.

**Comment by gregvonkuster** [comment]
Thanks @jmchilton ;)

**Comment by jmchilton** [comment]
Failing test case here https://github.com/jmchilton/galaxy/commit/854cb45555f36fcaa83e455f2bb20ef9578322e5 that should probably pass if this was working.

**Comment by gregvonkuster** [comment]
@jmchilton Thanks for taking a look at this.  I've tested your patch extensively and it fixes things for me.
