### ISSUE TITLE
Implicit conversion fails in workflow invocations

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#3268]
When executing a workflow using an implicitly converted dataset, the workflow invocations shows a success message but fails to process. The error shown is:
`Cannot create histories from a work request context.`

**Comment by mvdbeek** [comment]
I've seen this as well.

**Comment by natefoo** [comment]
Is this a new bug? I'm about to push the 16.10 release.

**Comment by mvdbeek** [comment]
I'm not sure, to me it seems this has always been a bit flaky. Maybe put it
in a  "known issues" section and release anyway?

**Comment by natefoo** [comment]
Ok, thanks!
