### ISSUE TITLE
fix links to tours included in sample welcome

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#3273]
somehow it does not work anymore, I remember testing it when I implemented it though :/

added in https://github.com/galaxyproject/galaxy/pull/3176

**Comment by dannon** [comment]
Yeah, they worked with the original ```/``` prefixed URLs, which we then changed to relative, without realizing that relative would be in ```/static/```.  I opened a PR fixing it, which should work in all situations.
