### ISSUE TITLE
Missing frame in the API-Key view

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/galaxy#3275]
If the menu item "Workflow" is selected and after it "Users -> API-Key" the frame with the galaxy logo, menu, the tools and the history side pane are missing. 
![screenshot from 2016-12-06 16-51-50](https://cloud.githubusercontent.com/assets/13435136/20932398/cc9be318-bbd4-11e6-8a32-40ed4eebeb07.png)

**Comment by martenson** [comment]
@joachimjacob This shouldn't be the case anymore in latest `dev` - PR that changes user preferences menu has been merged recently. It will be part of the 17.01 release.
