### ISSUE TITLE
display ranking of tool search results

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/galaxy#3276]
- The ranking of search results is not as good as it could be. With the default ranking settings, a search for the tool "BAM-to-SAM" is having an exact hit but is only ranked at position three of three. See attached image.

- It looks like k-mers are not computed. A little typo like "PileOMth" instead of "PileOMeth" generates no result instead of one. It would be better for the users if little typos are allowed. 
![screenshot from 2016-12-06 17-16-59](https://cloud.githubusercontent.com/assets/13435136/20933464/662e2e20-bbd8-11e6-9c66-f06ed9d9e1fd.png)

**Comment by martenson** [comment]
@joachimjacob 
You can configure the instance's search here: https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.ini.sample#L891

The results shown are not ranked top to bottom - it respects their order in the tool panel instead.

Agreed that fuzzy search would be an improvement and worth an issue.

**Comment by joachimwolff** [comment]
@martenson 
I understand why it is done this way right now and i know how to tune the parameters. With not that many tools it is a good way to present the search results. But with an increasing number of tools it is getting confusing where the tool is - and if it was found. For example "cufflinks" is an exact hit and it is at position number nine. 
![screenshot from 2016-12-06 17-31-35](https://cloud.githubusercontent.com/assets/13435136/20934184/8acf811e-bbda-11e6-99d2-4ccbef577e56.png)

**Comment by martenson** [comment]
@joachimjacob I think one of the reasons why the search results are not re-ordered dynamically for each call is to prevent confusion. 

Positions in the toolpanel after search are not ordered, so there is no 'position nine' for cufflinks. Also what you call an 'exact hit' is not that clear in many cases since we search on more attributes than the displayed name.

Maybe you could try experimenting with `tool_search_limit` to provide less results to filter this?

I understand what you are asking for though and it makes sense to me too.

**Comment by nsoranzo** [comment]
Since fuzzy search was implemented in https://github.com/galaxyproject/galaxy/pull/3356 and I don't think we are going to support a ranking of results, I'm going to close this. Feel free to re-open if I've missed something.

**Comment by joachimwolff** [comment]
I strongly disagree. Ranking should be supported, give us please an option in the galaxy.ini config to activate it if we want to us it. At all our galaxy courses the users ask us why the tools are always 'somewhere' and not number 1 hit as they know it from google. The current search leads to the use of a second search: ctrl + f. This can not be wanted.

Thanks for reconsidering!

**Comment by martenson** [comment]
@joachimwolff I am willing to try implementing this as a configurable option.

**Comment by martenson** [comment]
@joachimwolff  I think this is a valuable issue and with the rewrite of toolpanel by @inkuzmin that made it to 19.09 this is now substantially closer.

**Comment by martenson** [comment]
Implemented in #9579 I believe.

**Comment by joachimwolff** [comment]
It is better now, but still not fixed. You need to search for the right prefix and typos are not allowed.

**Comment by martenson** [comment]
@joachimwolff Does your instance have fuzzy search configured? https://github.com/galaxyproject/galaxy/pull/3356
