### ISSUE TITLE
Ensure clean job working directory if job was re-queued

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#3289]
Want to ensure that the job working directory is always empty when a job starts up.

In our cluster environment, jobs can be requeue by slurm because a higher priority job has bump it off or a node has failed. When the job is re-queue using slurm, it will still have the same job ID and working directory but its <job_directory>/working could have some partial datasets already because it already ran but not to completion.  As such most tools expect to have an empty working/ .

My solution would be to add _rm -rf working/_ at 
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/command_factory.py#L89
i.e
commands_builder.prepend_command("**rm -rf working/ ;** mkdir -p working; cd working")

**Comment by jmchilton** [comment]
Simple solution - that should probably work. I like it. I'll open a PR.

**Comment by Takadonet** [comment]
Sweet.
