### ISSUE TITLE
Overhaul Job Resubmission

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3293]
- Current allow resubmission conditions for jobs include ``walltime_reached``, ``memory_limit_reached``. There needs to be a way to say "potential_infrastructure_failure" and "infrastructure_failure". There will be many cases where we won't be able to say if infrastructure is the problem but there will also be cases where it is clearly a connection problem with Pulsar or a node disappearing. We should be able to dispatch on both.
  - Longer term it would also be nice to provide tools a way to say - X will never work - regardless of cluster, memory, and walltime.
- There should be an easy way to just resubmit to the same destination X number of times (e.g. on infrastructure problems or potential infrastructure problems).
- There should be a way to delay or backoff jobs as part of the resubmission framework. A new ``DELAYED`` job state.

These three things should be fairly easy to do, fairly easy for admins to specify in job_confs, and should make collection-based and other large workflows much more robust against infrequent random cluster failures.

Ping @natefoo - is this the right low hanging fruit?

**Comment by natefoo** [comment]
Yeah, I think this is good. See also overlap with #3107.

**Comment by jmchilton** [comment]
My current status is that I have resubmission on "unknown errors" for any runner working and test in this branch - https://github.com/galaxyproject/galaxy/compare/dev...jmchilton:job_resubmission?expand=1 that builds on #3291.

My concrete next steps are:
- Test resubmit without a condition - should just resubmit to the same destination.
- Refactor ``condition`` check on destinations into a whitelisted Python DSL - you can think of the current values like ``walltime_reached`` as variables that will be injected.
- Add test for ``or`` in a destination ``condition``.
- Add variable ``any_error`` which is like ``walltime_reached or memory_limit_reached or unknown_error``.
- Add variable ``attempt`` to condition language which is the resubmission count for the current destination. Allows easy conditions like ``<resubmit condition="any_error and attempt < 2" />``
- Add variables ``time_since_queued`` and ``time_running`` to condition language. Easily allow simple resubmission for jobs that die right away.

After that I will continue with this concept of delayed jobs. Resubmission right away will likely fail - best to delay in many cases I suspect.
