### ISSUE TITLE
Release a 17.01?

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3297]
We had a devteam meeting to work on the Roadmap issue - https://github.com/galaxyproject/galaxy/issues/1928. Given how late the last release was - we discussed perhaps skipping 17.01. If we could upgrade to the newest version of Conda and enable that by default we all agreed that it would warrant a release. Otherwise, we didn't really predict anything awesome enough happening in December to make a release worth it.

Thoughts?

**Comment by bgruening** [comment]
We could maybe use this one month and all spend some time to go through the issue tracker and fix small but annoying things.

Ubuntu had once (not sure if this is still active) the One Hundred Papercut initiative https://wiki.ubuntu.com/One%20Hundred%20Papercuts. Everyone was invited to send in very small issues, probably most UI things and we can fix them and polish our stack. Including testing, Tours, Wiki and test the new conda release ... maybe building IUC every week once? In January we have a small just more polished release.

X-mas time is ideal for this I think, nothing really big but everyone can contribute and we can list the Papercut Ninjas at the end?

**Comment by jmchilton** [comment]
We are doing a release - but @bgruening I did fix a bunch of random papercuts over break. Hopefully we can keep it up.

**Comment by bgruening** [comment]
Thanks John!
