### ISSUE TITLE
Get updates does not trigger toolbox reload

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#3298]
Getting updates for a repository ( the type of repository update without tool version bump) doesn't trigger a toolbox reload. Manually reloading the toolbox works, but should happen automatically.

**Comment by davebx** [comment]
It's supposed to, as I recall, so this might need to go kind/bug.

**Comment by nsoranzo** [comment]
Fixed by #3814 on `dev`.
