### ISSUE TITLE
Workflow: Post action fail on rename dataset with variable 

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#3307]
Testing out the current release branch 16.10 and looks like a regression where you cannot do a post action of renaming a dataset with a variable + extra text. So it WILL work if all you have is a variable i.e ${work}. BUT if you have any text with it, it seems to chop one  beginning and end characters from the name.

So if your rename datasets looks like this : http://imgur.com/JZPNL1F in workflow editor. 

When you attempt to run it as a workflow, it will look like this : http://imgur.com/IEEdt3K
After running it, it looks like the original input found in the workflow editor.

Current on branch release_16.10 on commit 2c833499b130aca72ab78d112692f2a9f0d4d9e6

**Comment by Takadonet** [comment]
Willing to be a tester if need be. @carlfeberhard

**Comment by dannon** [comment]
@Takadonet I'll take a look at this later today.

**Comment by Takadonet** [comment]
awesome thanks!

**Comment by dannon** [comment]
@Takadonet We've figured out the issue and are working on a fix now.  You're correct, this was a regression in the new run workflow interface and the way it was handling workflow parameters within strings.

**Comment by dannon** [comment]
Just to update you, @guerler and I worked on it Friday and it should be fixed with #3329

**Comment by Takadonet** [comment]
Works great!

**Comment by dannon** [comment]
Merging forward from 16.10 now, so this will be applied to dev.
