### ISSUE TITLE
No action for /user/change_password on test.galaxyproject.org

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#3312]
Just now requested a password reset to get the following link:
https://test.galaxyproject.org/user/change_password?token=randomtoken

The url however, is broken..

**Comment by dannon** [comment]
The endpoint was (perhaps erroneously) removed in https://github.com/galaxyproject/galaxy/commit/14e635aaee2699cb395443d802dede15d6f25240, a part of the user preferences rewrite in https://github.com/galaxyproject/galaxy/pull/3118.  I'll check and see if there's a new way to do this (and we need to update the email generated, and maybe even redirect) or if the endpoint just needs to be put back as it was.

**Comment by dannon** [comment]
I looked through, and it doesn't look like there was replacement functionality built into the new preferences interface.  Thanks for pointing this out @scholtalbers; @guerler and I will get a fix out soon.

**Comment by dannon** [comment]
Ok, this should be fixed with #3313, but we're going to revisit and rewrite this functionality in the near future.
