### ISSUE TITLE
History option "View Structure" results in Internal Server Error at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3314]
Happens for even small histories

Works fine on a default 16.10 local with no mods. Fails on Main.

cc @galaxyproject/guac

**Comment by mvdbeek** [comment]
Many fixes here in the meantime.

**Comment by jennaj** [comment]
thanks for finding/closing the orphan ticket! The function is definitely working at usegalaxy.org
