### ISSUE TITLE
Need to refresh history to see the status change on a job state

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy#3315]
Hi,

When I upload a data or launch a tool, the job is started in grey. To see that the job is running (yellow box), I need to refresh history. 
I check on the Freiburg Server and also on the useGalaxy server. The issue is similar.

Am I the only one with this issue?

Bérénice

**Comment by mvdbeek** [comment]
Hi @bebatut,

there were also some reports on the mailing list, which I can't seem to find.
I am also experiencing this, but not reliably, unfortunately. What I do see sometimes
is that datasets go from grey directly to green (even if they run for a few minutes).
Does that happen for you as well? This would help to narrow down the problem, I guess.

**Comment by Takadonet** [comment]
What you describe is what we are seeing here as well on release 16.10 branch.

**Comment by jvolkening** [comment]
Don't know the status of this, but I am experiencing similar behavior (also not reliable) on 16.10. It seems to occur mostly when a queued task starts automatically after waiting on a previous step, but this isn't a rigorously tested observation

**Comment by mvdbeek** [comment]
I think we fixed this some time ago. Had always been affected by this but it's working reliably now.
