### ISSUE TITLE
environment_variable is not specified in the Galaxy Tool XSD file

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#3316]
The feature is implemented https://github.com/galaxyproject/galaxy/blob/71cea6604d43c5fe6215f5656462ba6c1af69bb6/lib/galaxy/tools/parser/xml.py#L114 and can look like this:

```
    <requirements>
        <requirement type="package" version="2016.10.26">msgf_plus</requirement>
        <environment_variable name="LC_ALL" action="set_to">C</environment_variable>
    </requirements>
```

Found during the GalaxyP hackathon.

**Comment by jmchilton** [comment]
They are defined in the XSD file I believe - they belong in a top-level ``environment_variables`` tag not in ``requirements`` though.

**Comment by bernt-matthias** [comment]
This has been fixed here https://github.com/galaxyproject/galaxy/pull/4871
