### ISSUE TITLE
Publication of Galaxy Release v 17.01

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#3321]
- [X] **Prep**

    - [X] ~~Create this release issue ``make release-issue RELEASE_CURR=17.01``.~~
    - [X] ~~Set freeze date (2017-01-02).~~

- [x] **Branch Release (on or around 2017-01-02)**

   - [x] Ensure all [blocking milestone PRs](https://github.com/galaxyproject/galaxy/pulls?q=is%3Aopen+is%3Apr+milestone%3A17.01) have been merged, delayed, or closed.

            make release-check-blocking-prs RELEASE_CURR=17.01
   - [x] Merge the latest release into dev and push upstream.

            make release-merge-stable-to-next RELEASE_PREVIOUS=release_16.10
            make release-push-dev

   - [x] Create and push release branch:

            make release-create-rc RELEASE_CURR=17.01 RELEASE_NEXT=17.05

   - [x] Open PRs from your fork of branch ``version-17.01`` to upstream ``release_17.01`` and of ``version-17.05.dev`` to ``dev``.

   - [x] Open PR against ``release_17.01`` branch to pin flake8 deps in tox.ini to the latest available version.

   - [x] Update ``next_milestone`` in [P4's configuration](https://github.com/galaxyproject/p4) to `17.05` so it properly tags new PRs.

- [x] **Deploy and Test Release**

   - [x] Update test.galaxyproject.org to ensure it is running a dev at or past branch point (2017-01-02 + 1 day).
   - [x] Update testtoolshed.g2.bx.psu.edu to ensure it is running a dev at or past branch point (2017-01-02 + 1 day).
   - [x] Deploy to usegalaxy.org (2017-01-02 + 1 week).
   - [x] Deploy to toolshed.g2.bx.psu.edu (2017-01-02 + 1 week).
   - [x] [Update bioblend testing](https://github.com/galaxyproject/bioblend/commit/b74b1c302a1b8fed86786b40d7ecc3520cbadcd3) to include a ``release_17.01`` target - add ``env`` target ``- TOX_ENV=py27 GALAXY_VERSION=release_17.01`` to ``tox.ini``.

- [x] **Create Release Notes**

   - [x] Review merged PRs and ensure they all have a milestones attached. [Link](https://github.com/galaxyproject/galaxy/pulls?q=is%3Apr+is%3Amerged+no%3Amilestone)
   - [x] Checkout release branch

            git checkout release_17.01 -b 17.01_release_notes
   - [x] Check for obvious missing metadata in release PRs

            make release-check-metadata RELEASE_CURR=17.01
   - [x] Bootstrap the release notes

            make release-bootstrap-history RELEASE_CURR=17.01
   - [x] Open newly created files and manually curate major topics and release notes.

        - [ ] inject 3 witty comments
        - [ ] inject one whimsical story
        - [ ] inject one topical reference (preferably satirical in nature) to contemporary world event
   - [x] Commit release notes.

            git add docs/; git commit -m "Release notes for 17.01"; git push upstream 17.01_release_notes
   - [x] Open a pull request for new release note branch.
   - [x] Merge release note pull request.

- [x] **Do Release**

   - [x] Ensure all [blocking milestone issues](https://github.com/galaxyproject/galaxy/issues?q=is%3Aopen+is%3Aissue+milestone%3A17.01) have been resolved.

            make release-check-blocking-issues RELEASE_CURR=17.01
   - [x] Ensure all [blocking milestone PRs](https://github.com/galaxyproject/galaxy/pulls?q=is%3Aopen+is%3Apr+milestone%3A17.01) have been merged or closed.

            make release-check-blocking-prs RELEASE_CURR=17.01
   - [x] Ensure previous release is merged into current. (TODO: Add Makefile target or this.)
   - [x] Create and push release tag:

            make release-create RELEASE_CURR=17.01

- [ ] **Do Docker Release**

   - [x] Change the [dev branch](https://github.com/bgruening/docker-galaxy-stable/tree/dev
) of the Galaxy Docker container to 17.05
   - [ ] Merge dev into master

- [x] **Ensure Tool Tests use Latest Release**

   - [x]  Update GALAXY_RELEASE in https://github.com/galaxyproject/tools-iuc/blob/master/.travis.yml#L6

   - [x]  Update GALAXY_RELEASE in https://github.com/galaxyproject/tools-devteam/blob/master/.travis.yml#L6

- [x] **Announce Release**

   - [x] Verify release included in https://docs.galaxyproject.org/en/master/releases/index.html
   - [x] Review announcement in https://github.com/galaxyproject/galaxy/blob/dev/doc/source/releases/17.01_announce.rst
   - [ ] Stage annoucement content (Wiki, Biostars, Bit.ly link) on annouce date to capture date tags. Note: all final content does not need to be completed to do this.
   - [ ] Create wiki *highlights* and post to http://galaxyproject.org News (w/ RSS) and NewsBriefs. [An Example](https://wiki.galaxyproject.org/News/2016_04_GalaxyRelease).
   - [x] Tweet docs news *highlights* via bit.ly link to https://twitter.com/galaxyproject/ (As user ``galaxyproject``, password in Galaxy password store under ``twitter.com / galaxyproject`` ). [An Example](https://twitter.com/galaxyproject/status/733029921316986881).
   - [x] Post *highlights* type News to Galaxy Biostars https://biostar.usegalaxy.org. [An Example](https://biostar.usegalaxy.org/p/17712/).
   - [x] Email *highlights* to [galaxy-dev](http://dev.list.galaxyproject.org/) and [galaxy-announce](http://announce.list.galaxyproject.org/) @lists.galaxyproject.org. [An Example](http://dev.list.galaxyproject.org/The-Galaxy-release-16-04-is-out-tp4669419.html)
   - [x] Adjust http://getgalaxy.org text and links to match current master branch (TODO: describe how to do this)

- [ ] **Prepare for next release**

   - [x] Ensure milestone ``17.05`` exists.
   - [x] Create release issue for next version ``make release-issue RELEASE_CURR=17.05``.
   - [ ] Schedule committer meeting to discuss re-alignment of priorities.
   - [ ] Close this issue.

**Comment by jmchilton** [comment]
Well it isn't just you @natefoo - see #3323. Something broke the formatting here :(.

Update: I think the problem is #2865 - there were no triply nested TODO lists prior to that.

**Comment by martenson** [comment]
@jmchilton that is not is, after removal of #2865 it is still broken

https://github.com/martenson/galaxy/issues/20

**Comment by nsoranzo** [comment]
6-spaces indentation is what breaks it, reducing to 4 or 2 spaces seems to fix it.

**Comment by martenson** [comment]
@nsoranzo Yep, but we did not change that, the processing of the string changed maybe? It just treats whitespace differently than before (also notice the extra empty lines).

**Comment by nsoranzo** [comment]
> the processing of the string changed maybe?

I guess so.

> also notice the extra empty lines

Where?

**Comment by martenson** [comment]
@nsoranzo compare empty lines in https://github.com/galaxyproject/galaxy/issues/2940 and here

**Comment by nsoranzo** [comment]
I think they were removed from the Markdown in #2940 (if I get what you mean).

**Comment by martenson** [comment]
@nsoranzo I do not think they were, I created that issue and I do not remember manually removing empty lines.

**Comment by nsoranzo** [comment]
Well, they are not there... not very important at this point? We just need to fix the spacing in `scripts/bootstrap_history.py`

**Comment by martenson** [comment]
I did not claim it is important. I think it is a lead to why things are different (whitespace processing).

**Comment by martenson** [comment]
Just updated Test to latest dev.

**Comment by martenson** [comment]
TTS updated to latest dev.

**Comment by bgruening** [comment]
docker container branched to 17.01: https://github.com/bgruening/docker-galaxy-stable/pull/285

**Comment by martenson** [comment]
Main is now running 17.01

**Comment by martenson** [comment]
MTS is now running 17.01 too

**Comment by martenson** [comment]
bioblend integration testing updated with https://github.com/galaxyproject/bioblend/commit/1ef807f5c5f2d903ba7757cc5d2ec24397a8ed2d

**Comment by martenson** [comment]
PR with notes opened - please help curating it. https://github.com/galaxyproject/galaxy/pull/3497

**Comment by martenson** [comment]
Released, tweeted, posted to biostar. Good job all!
