### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ww102111** [galaxyproject/galaxy#3341]
$ sh run.sh
Fetching https://pypi.python.org/packages/source/v/virtualenv/virtualenv-13.1.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1679k  100 1679k    0     0   193k      0  0:00:08  0:00:08 --:--:--  311k
Verifying /tmp/galaxy-virtualenv-8ybKuM/virtualenv-13.1.2.tar.gz checksum is aabc8ef18cddbd8a2a9c7f92bc43e2fea54b1147330d65db920ef3ce9812e3dc
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: [Errno 2] No such file or directory: '/tmp/galaxy-virtualenv-8ybKuM/virtualenv-13.1.2.tar.gz'

**Comment by peterjc** [comment]
The URL seems to be working (now), is it possible your ``/tmp`` was full?
