### ISSUE TITLE
Samtools Filter on BAM or SAM fails at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3353]
Fails immediately. Was a problem last week, then worked, now fails again on some runs, but not all. Same exact inputs.

**Error**:

> Job environment and execution information is available at the job Info Page.
> Job ID	XXX
> Tool ID	toolshed.g2.bx.psu.edu/repos/devteam/samtool_filter2/samtool_filter2/1.1.2
> Tool Version	1.1.2
> Job PID or DRM id	None
> Job Tool Version	None
> Job Execution and Failure Information

> Command Line
> 
> None
> stderr
> 
> 
> stdout
> 
> 
> Job Information
> 
> Can't instantiate abstract class SafeStringWrapper(galaxy.datatypes.tabular.TabularData:<class 'galaxy.tools.wrappers.ToolParameterValueWrapper'>,<class 'galaxy.util.object_wrapper.SafeStringWrapper'>,<class 'numbers.Number'>,<type 'NoneType'>,<type 'NotI
> Job Traceback
> 
> ```
> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
>     job_wrapper.prepare()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/jobs/__init__.py", line 909, in prepare
>     self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/tools/evaluation.py", line 445, in build
>     raise e
> TypeError: Can't instantiate abstract class SafeStringWrapper(galaxy.datatypes.tabular.TabularData:<class 'galaxy.tools.wrappers.ToolParameterValueWrapper'>,<class 'galaxy.util.object_wrapper.SafeStringWrapper'>,<class 'numbers.Number'>,<type 'NoneType'>,<type 'NotImplementedType'>,<type 'bool'>,<type 'bytearray'>,<type 'ellipsis'>) with abstract methods set_meta
> ```
cc @galaxyproject/guac @natefoo

**Comment by natefoo** [comment]
This is a new bug since upgrading to 16.10 and I don't really have any immediate ideas on what's causing it. Does anyone know if any command line generation stuff has changed? @jmchilton?

**Comment by jmchilton** [comment]
Yeah - I retested this on older Galaxies and this was broken in 16.10. Nothing immediately occurs to me as the cause - I'll think about it some more though. The tool XML bleeds a ton of Galaxy details and Python details in - very simple things like equality checks seem to be implemented in a way to promote breaking as quickly as possible.

**Comment by jmchilton** [comment]
Still working on this but it is broken as of the merge commit 3fd0e405fd6cb3333397ec19e627a4cf6ae36fe6 for #2690. Makes sense I guess given the datatype references in the error message.

**Comment by jennaj** [comment]
Thanks @natefoo & @jmchilton ! I'll watch the fix ticket.
