### ISSUE TITLE
Sicer fails for an intermediate working file not found at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3355]
**Version**:

Tool ID	toolshed.g2.bx.psu.edu/repos/devteam/sicer/peakcalling_sicer/0.0.1

**Error**:

> stderr
> 
> Traceback (most recent call last):
>   File "/galaxy/main/migrated_tools/toolshed.g2.bx.psu.edu/repos/devteam/sicer/82a8234e03f2/sicer/sicer_wrapper.py", line 157, in <module>
>     if __name__=="__main__": __main__()
>   File "/galaxy/main/migrated_tools/toolshed.g2.bx.psu.edu/repos/devteam/sicer/82a8234e03f2/sicer/sicer_wrapper.py", line 153, in __main__
>     raise e
> IOError: [Errno 2] No such file or directory: '/galaxy-repl/main/scratch/tmpIdFHbu/input_bed_file-W200-G200-islands-summary'

**Not sure if core tool issue or server related - can move to tool repo if needed**

cc @galaxyproject/guac @natefoo

**Comment by natefoo** [comment]
Is this with all inputs?

**Comment by jennaj** [comment]
@natefoo Not exactly sure what you mean, but the tool form inputs are Ok. Seems like one of the outputs created by the tool is the dataset "not found". Am rerunning again now to eliminate a transient problem, will reply once that job is done with the result status.

**Comment by jennaj** [comment]
@natefoo job failed. One of the output is named "34 SICER on data 2 and data 3 (test-W200-G200-islands-summary)" - same as the not found file name. Also double checked inputs - both BED datasets are fine. I can share history if that would help.

Also re-ran a prior successful job that uses BAM inputs instead of BED. Failed the same way, but much quicker for some reason.

**Comment by jennaj** [comment]
This has been reported again. Running a few tests - the tool might still need a correction. Or maybe a better error message if there is some input content that triggers this problem (haven't found it yet).

**Comment by jennaj** [comment]
@natefoo @davebx Sicer is definately failing for what might be a dependency issue (same error as above). This is a test history from one of our tutorials that has the test case in it: https://usegalaxy.org/u/jen/h/sicer-test

> Traceback (most recent call last):
>   File "/galaxy/main/migrated_tools/toolshed.g2.bx.psu.edu/repos/devteam/sicer/82a8234e03f2/sicer/sicer_wrapper.py", line 157, in 
>     if __name__=="__main__": __main__()
>   File "/galaxy/main/migrated_tools/toolshed.g2.bx.psu.edu/repos/devteam/sicer/82a8234e03f2/sicer/sicer_wrapper.py", line 153, in __main__
>     raise e
> IOError: [Errno 2] No such file or directory: '/galaxy-repl/main/jobdir/017/652/17652579/_job_tmp/tmpcLZaF6/input_bed_file-W200-G600-islands-summary'

Also fails at Freiburg. Going to make a ticket against the devteam repo - this is probably a tool problem. Will link it back here. Test history: https://galaxy.uni-freiburg.de/u/jenj/h/copy-of-test-history-sicer

**Comment by jennaj** [comment]
Moved to tools-devteam repo: https://github.com/galaxyproject/tools-devteam/issues/498
