### ISSUE TITLE
Initial admin user? How do I log in during development?

### ISSUE THREAD

**Issue by buchanae** [galaxyproject/galaxy#3363]
The galaxy `run.sh` is impressive in its ease of use, but I haven't found an easy way to create a user and log in. Maybe a "create-admin.py" helper script and clear documentation is needed.

**Comment by buchanae** [comment]
Ah, I did find the docs for the admin config, and of course all I had to do was go to "Register". D'oH!

**Comment by bgruening** [comment]
@buchanae welcome! We are trying to consolidate your docs under: https://github.com/galaxyproject/galaxy-hub
So hopefully this will be easier next year.

Merry Christmas!
