### ISSUE TITLE
History sharing form exposes user e-mails inappropriately

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3372]
This form doesn't respect 

```
expose_user_name
expose_user_email
```

the way say the workflow sharing form does.

xref #3250

**Comment by hexylena** [comment]
Gah. That's unfortunate. Will fix when back from holiday, if no one else does sooner.

**Comment by nsoranzo** [comment]
Is this also fixed by #3373?

**Comment by jmchilton** [comment]
Nope. I just discovered it when implementing that PR.
