### ISSUE TITLE
conda channel order in galaxy and planemo

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#3389]
The channel order mechanism has changed between conda 3.19.3 (what we've been shipping galaxy with initially) and >= 4. The changes are documented [here](http://conda.pydata.org/docs/channels.html). This led us to notice that there are problems with the current order.

- [x] currently planemo conda_install writes out a channel order that is wrong (i.e. different from bioconda). The current order is `[defaults, conda-forge, r, bioconda, iuc]` while it should be `iuc, bioconda, r, defaults, conda-forge]`.

- [x] need to verify that galaxy's channel order is correct

- [ ] looking up galaxy's channel order should be easy. log in galaxy log? log in tool run information ?

**Comment by bgruening** [comment]
Adding to the last point, the complete environment of a tool + channel order should be dumped as part of the metadata.

**Comment by nsoranzo** [comment]
> while it should be `[iuc, bioconda, defaults, r, conda-forge]`

According to https://github.com/bioconda/bioconda-recipes/blob/master/config.yml , this should be:

`[iuc, bioconda, r, defaults, conda-forge]`

which is also what we already use in `config/galaxy.ini.sample` .

**Comment by mvdbeek** [comment]
updated the above -- I think that was a mistake when we we're working through some problems in gitter

**Comment by jmchilton** [comment]
Moved these logging issues to a new issue and closing this one.
