### ISSUE TITLE
17.01 Release Meeting

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3394]
Let's have a meeting to triage 17.01 PRs and issues before a branch?

I'll throw Wednesday 2017/01/11 at [11am EST](https://www.timeanddate.com/worldclock/fixedtime.html?month=01&day=11&year=2017&hour=11&min=0&sec=0&p1=43) out there?

I was supposed to add this to the release issue generation but I guess I didn't.

**Comment by dannon** [comment]
Assuming you meant 11am EST, can we bump that to 1  (or maybe 11am wednesday) ?  I have a midmorning appointment.

**Comment by nsoranzo** [comment]
Also the timeanddate.com link was for year 2007 (I fixed that) and day=11 (should be 10, I guess).

**Comment by jmchilton** [comment]
Thanks @nsoranzo & @dannon - I've updated the top line to be Wednesday at 11 am.

**Comment by dannon** [comment]
@jmchilton Thanks!  Hopefully the extra 24h warning helps out others as well :)

**Comment by martenson** [comment]
ping @galaxyproject/core

**Comment by dannon** [comment]
Update:  We're going to try for tomorrow at 11 AM ET after a little more advertisement of this.

(https://www.timeanddate.com/worldclock/fixedtime.html?month=01&day=12&year=2017&hour=11&min=0&sec=0&p1=43)

**Comment by martenson** [comment]
Sent email to committers.

> Hello committers,
>
>we would like to have a 17.01 release meeting tomorrow 11am EST (find your time here https://www.timeanddate.com/worldclock/fixedtime.html?month=01&day=12&year=2017&hour=11&min=0&sec=0&p1=43).
>
>We will send a hangouts link before the meeting via this email thread tomorrow.
>
>The meeting also has its GitHub issue: https://github.com/galaxyproject/galaxy/issues/3394
>
>If you feel so inclined you can go through the opened issues/PRs in advance and clean what you can: https://github.com/galaxyproject/galaxy/milestone/6
>
>Thanks and have a great day.
