### ISSUE TITLE
Tool form defaults are changing in repeats elements

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#3421]
Hi Aysam,

we have a strange case. We have some select params and all of them are `optional="True"`. These params are in a repeat. The first repeat element everything is fine. The second repeat we get filled select boxes. So the `nothing is selected` option is not choosen. This yields to wired unexpected results.

**Comment by guerler** [comment]
Alright. Thanks for reporting this.

**Comment by guerler** [comment]
I looked into it, and it worked fine for me with static selects, empty and with options. Can you share the xml or parts of it?

**Comment by bgruening** [comment]
@guerler seen with this one: https://github.com/maxplanck-ie/HiCExplorer/blob/master/galaxy/wrapper/hicPlotMatrix.xml

**Comment by guerler** [comment]
Hmm...when I load the `hicPlotMatrix.xml` into Galaxy, its tool form contains a single repeat-block with a text-field for Chromosome names. There are no select-fields specified within the repeat-block. Am I using the right tool?

**Comment by bgruening** [comment]
damn, sorry, https://github.com/maxplanck-ie/HiCExplorer/blob/master/galaxy/wrapper/hicPlotTADs.xml
