### ISSUE TITLE
Problem running dockerized tests as user with UID 109.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3425]
```
Launching docker container for testing...
/usr/sbin/deluser: The user 'galaxy' does not exist.
groupadd: GID '109' already exists
Build step 'Execute shell' marked build as failure
```

The relevant part of code from test/docker/run_test_wrapper.sh is here:

```
deluser galaxy | true
groupadd -r galaxy -g "$GALAXY_TEST_UID"
useradd -u $GALAXY_TEST_UID -r -g galaxy -d /home/galaxy -c "Galaxy User" galaxy -s /bin/bash
echo "galaxy:galaxy" | chpasswd
chown -R galaxy:galaxy /galaxy_venv
```

I guess it should be restructured to just add the new ``galaxy`` user in container to the existing group with GID 109.

**Comment by osallou** [comment]
Setting commands chained should do the job:

    groupadd -r galaxy -g "$GALAXY_TEST_UID" ; useradd -u $GALAXY_TEST_UID -r -g galaxy -d /home/galaxy -c "Galaxy User" galaxy -s /bin/bash

Even if groupadd fails because it already exists, user will use it. If group is not present, it will be created

**Comment by jmchilton** [comment]
@osallou Great point - thanks a bunch!

I have WIP at https://github.com/jmchilton/galaxy/commit/05d94f519c8fd98e467c2e43c44de1d5d47cea8c based on this point and extending it to user creation also. Running some tests now.
