### ISSUE TITLE
Zip Collection Operator: Cannot edit attribute.

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#3437]
Attempting to edit attributes of a single element in a zip collection and getting the following stacktrace in logs.

https://gist.github.com/Takadonet/2cd22d87d604bbc9e49d7e835733cac4

Looks like no user assigned to the new element being linked/created.

**Comment by nsoranzo** [comment]
Actually that means that `data.history` is `None`.

**Comment by Takadonet** [comment]
my bad
