### ISSUE TITLE
Workflows should save automatically

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/galaxy#3459]
Every time you make a change. This might be much easier after the JS rewrite, but I think it's important galaxy catch up to the rest of the world. It's 2017! You shouldn't have to save things online anymore.

**Comment by bgruening** [comment]
I think this is a good point to discuss, but it is (at least to me) not obvious that this change is what a user expects. So catching up to the rest of the world might be a little bit harsh, I still using many program that do not save every automatically, or this needs to be enabled separately. I also think that if you have this you should offer a way to automatically roll back changes, which is way harder to do.

What I would like to see more than an automatic save is a tracking of changes, a versioning, or optionally a direct integration with github.

**Comment by alexlenail** [comment]
That last idea is super interesting. I defer to your better judgement, Bjoern!
