### ISSUE TITLE
Workflow import from file with missing tools

### ISSUE THREAD

**Issue by vebaev** [galaxyproject/galaxy#3473]
When the workflow have missing tool, the Galaxy report Forbidden page on import, and than the workflow is imported but uneditable.
@bgruening mention @guerler have already a patch?

Related thread:
https://github.com/bgruening/docker-galaxy-stable/issues/284

**Comment by bgruening** [comment]
I was referring to https://github.com/galaxyproject/galaxy/pull/3181 ... Maybe something is in there that improves the situation.
