### ISSUE TITLE
random ordering of datasets from multiple workflows in one history 

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#3474]
The new workflow scheduler is in place, we can split the scheduling of one workflow across different workers. Submitting one workflow for multiple times, seems to result in an unpredictable ordering of datasets from different workflow runs. 

Our power-users complain a lot about this as it is not possible to get the correct datasets back. The solution to send every workflow to it's own history does not really work, as switching and managing many workflows is cumbersome.

I consider this as a critical regression as it makes the flow of how users work obsolete and moreover, it might result in wrong results if you pick the wrong dataset.

One interim solution would be to name the datasets according to their workflow-invocation, so if I start a workflow on 3 files names `a,b,c` than every element that is created in workflow one get a prefix calle `a`. This only happens in the case of multiple workflows ending up in one history.

Any other idea?
ping @jmchilton @guerler

**Comment by guerler** [comment]
A fix for this would be great. Just fyi, we discussed this awhile ago and this behavior is reflected in the following test:
https://github.com/galaxyproject/galaxy/blob/dev/test/api/test_workflows.py#L1614.

**Comment by jmchilton** [comment]
The right long term solution is to display in the invocations in the history panel which is on the priority list I believe. If we want to implement a solution in the short term we could either have the client submit them one at a time and monitor before submitting the next or we could add a column to the database on workflow invocations to implement dependent invocations and force one workflow to be scheduled before the next is. These are both gross and have corner cases with bad user experiences. Alternatively these workflows could be rewritten to use collections - submitting many datasets this way is somethinhg of a workaround from a time before collections.

**Comment by bgruening** [comment]
@jmchilton using collections might be an other alternative, but they are still to complex for many users - we are lacking training material for them and so on. I don't think this is a valid solution right now - if it is we should prevent users to use their old habits and creating a mess in there histories. Currently, we allow this and this is just bad UX. 

What do you think about adding an identifier to the name of the dataset for the time being - in this specific case?

**Comment by bgruening** [comment]
So it turns out this is not only happening for workflows but with any selection of multiple datasets. I got my first mails with the question if we can rollback the release :(

**Comment by jmchilton** [comment]
I don't even know where to start with the naming - it is a mistake in general to add it so I don't want to add it and have to support it forever. I'd rather just add workflow dependencies - because this will be easier to support going forward and doesn't conflict with other things we want to do (it is "like" other things we want to do).

I don't think anything changed with respect to tool executions - so I'm not sure about your last comment. I should still all be ordered on the backend. @guerler any ideas?

**Comment by bgruening** [comment]
Can we set the number of parallel workers to 1, to simulate the old behavior? This could be configurable... Currently, I care more about usability and not about performance.

**Comment by guerler** [comment]
I would like to have deterministic backend handling of this too. I have not looked into it yet tho.

**Comment by bgruening** [comment]
>  don't even know where to start with the naming - it is a mistake in general to add it so I don't want to add it and have to support it forever. 

I don't think we need to support this forever, this is a pure UI detail to make it possible for a user to find his/her data.

**Comment by dannon** [comment]
I was working on a fix, but from IRC, @jmchilton pointed me to https://github.com/jmchilton/galaxy/commit/d797a537d756956bf1a63f9dcafb692da7f31f91, which may be a way to handle it.

**Comment by jmchilton** [comment]
Yeah - I thought I linked to it here. I'm not endorsing the linked approach - I think it is a mistake.

**Comment by martenson** [comment]
I merged #3520 as a temporary, optional, and wrong solution for this. I am leaving this issue open and hopefully it will lead to a better approach.

**Comment by jmchilton** [comment]
We implemented a better approach that is still "technically correct" and does a better though not perfect job maintaining order. @bgruening seemed satisfied so I am closing this -I think #3520 should be reverted at some point because it causes serious performance problems when enabled and @bgruening was our only known user and he is no longer using it.
