### ISSUE TITLE
Tool request on useGalaxy.org - FeatureCounts

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/galaxy#3480]
Could FeatureCounts be added to Main? 

FeatureCounts performs the same task as htseq-count, but is much much faster. We include FeatureCounts in the RNAseq tutorial @malloryfreeberg and I are creating as part of the [training materials effort](https://github.com/galaxyproject/training-material) that will (hopefully) get frequent usage on Main from the various courses that utilize them.

**Comment by martenson** [comment]
Asking for a green light from @jxtx or @nekrut 

Also please add the info to which section it should be added @MoHeydarian .

**Comment by MoHeydarian** [comment]
FeatureCounts should be added to the 'RNA Analysis' section.

Thanks, Marten!

**Comment by jxtx** [comment]
For the tools-iuc repository? Sure.

**Comment by martenson** [comment]
done, please test @MoHeydarian 
https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/featurecounts/featurecounts/1.4.6.p5

**Comment by MoHeydarian** [comment]
Thanks, @martenson. The tool works (using [this workflow](https://github.com/MoHeydarian/Workshed/blob/master/Galaxy-Workflow-4_sample_RNAseq_DeNoTrR_-_v2.ga)).
