### ISSUE TITLE
Unhide hidden datasets - broken in 17.01

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#3481]
We have just noticed that "Unhide hidden datasets" in the menu does not work.

```
analysis.bundled.js?v=1485288921:11 Uncaught TypeError: e.ajaxQueue is not a function
    at n.func (analysis.bundled.js?v=1485288921:11)
    at HTMLAnchorElement.<anonymous> (analysis.bundled.js?v=1485288921:9)
    at HTMLAnchorElement.dispatch (libs.bundled.js?v=1485288921:25)
    at HTMLAnchorElement.m.handle (libs.bundled.js?v=1485288921:25)
```

**Comment by jennaj** [comment]
btw - Hidden datasets are not available to tools either. Opening a separate ticket for that issue, may be related so will link it back.

**Comment by dannon** [comment]
Just to update the ticket, I'm pretty sure this is due to the model's 'hidden' datasets not being populated anymore.  Working on a fix.

**Comment by dannon** [comment]
Another update, the 'deleted' filtering of a collection is also innacurate, when we fetch a subset of the history, preventing 'purge deleted', etc., from working.

**Comment by dannon** [comment]
Should work in #3621.  Will be rewriting this functionality for the next release.

**Comment by martenson** [comment]
moving this to 17.05

**Comment by dannon** [comment]
@martenson This is fixed.  I'll open a new issue for the selector changes.

**Comment by martenson** [comment]
@dannon thanks!
