### ISSUE TITLE
Orphan steps in workflows cause log clogging

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#3488]
Hello everyone,
A friend developed a workflow that had a few orphan steps (no inputs or outputs). When this workflow was running, it finished everything except the orphan steps. The result was that Galaxy continued to produce log lines describing that the steps were being executed, which would immediately terminate and would then be rerun. This is on Galaxy 15.10 (I understand I am serveral versions behind).

**Comment by hexylena** [comment]
I guess this is working better now (on recent / supported versions of Galaxy), if not please re-open :)

**Comment by MatthewRalston** [comment]
Thanks, last I checked with my old company it was still clogging the logs. Ooof.
