### ISSUE TITLE
prevent display app config from interfering with datatypes config

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#3494]
either by separating the two or by other means

background: After https://github.com/galaxyproject/galaxy/pull/3145 was merged, on Main datatypes config needs to be re-populated from sample but given the display app config is not in the sample the two files need to be smartly 'merged'. 

>No admin solutions to dev problems. Galaxy should be able to define these display sites in a separate file and merge them

@natefoo @jmchilton

**Comment by jmchilton** [comment]
I have work in progress on this - will open a PR in a few.
