### ISSUE TITLE
Trackster will not load gff datasets at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3499]
Error with trackster

> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/converters/gff_to_interval_index_converter.py", line 16, in 
>     from galaxy.datatypes.util.gff_util import convert_gff_coords_to_bed, GenomicInterval, GFFReaderWrapper
> ImportError: No module named galaxy.datatypes.util.gff_util

@galaxyproject/guac @martenson Not sure if related to 17.01 upgrade/prep

**Comment by MoHeydarian** [comment]
This applies to bed (bed6) formatted data as well.

**Comment by jennaj** [comment]
Related tickets:

Metadata column assignment for BED/Interval datasets problematic https://github.com/galaxyproject/galaxy/issues/2175

BED files load into Trackster with error https://github.com/galaxyproject/galaxy/issues/1722

**Comment by mvdbeek** [comment]
The initial report is probably related to https://github.com/galaxyproject/galaxy/pull/3364.
We may need to add `CONVERTER_gff_to_interval_index_0` to the `GALAXY_LIB_TOOLS`.
Ping @jmchilton

**Comment by jmchilton** [comment]
Sorry about that all - this should be fixed #3690.

**Comment by jennaj** [comment]
Great to have Trackster fixed for these data, thank you! Do we need to ping anyone to get this on Main?

**Comment by jennaj** [comment]
This still hasn't made it onto Main. Could we leave it open until that happens?

**Comment by martenson** [comment]
@jennaj the mentioned PR is already deployed on Main. Maybe this is caused by something else. ping @jmchilton

**Comment by jmchilton** [comment]
- Is it the same traceback? 
- Is it a problem with the original datasets that needed conversion or do new datasets have the same problem still?

**Comment by jennaj** [comment]
I used different datasets to test - nearly any GTF extracted from UCSC main can be used to test this (dm3, hg19). Avoid dm6 - that indexed genome does not work with trackster still for some reason (is in another ticket)

**Comment by jmchilton** [comment]
Ahh @hrhotz to the rescue - he fixes bed files with https://github.com/galaxyproject/galaxy/pull/3822 but in the same directory there is a similar script for gtf files. I don't know how I missed both of these.

**Comment by martenson** [comment]
@jennaj deployed, please re-test

**Comment by jennaj** [comment]
@martenson Doesn't seem to be working yet. Did anyone else get a gtf/gff dataset to load?
<img width="952" alt="screen shot 2017-03-28 at 7 47 57 am" src="https://cloud.githubusercontent.com/assets/8999735/24411544/fdbbcd4c-138a-11e7-896a-539b6421f08b.png">

**Comment by jennaj** [comment]
@martenson @galaxyproject/guac Just tested again, same error. This seems important to fix.

**Comment by jmchilton** [comment]
@jennaj Can you look at the page source there and tell me what Python file has that error? Starts with ``/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/converters/interval_to``?

**Comment by jmchilton** [comment]
My GTF test on main did not encounter that import error - is it possible you created a new visualization instead of a new dataset?

Can you point me to particular GTF file by URL and tell me what to put in for the genome to recreate?

**Comment by MoHeydarian** [comment]
Here is an example GTF that should load on Trackster, it is in a published history on Main (genome is mm10):  https://usegalaxy.org/u/mheydarian/h/gtf-file-cuffmerge-output-for-testing-trackster

**Comment by MoHeydarian** [comment]
I tested the GTF in the published history above around 8 pm EST and got the same error Jen posted (four comments ago). I tried loading it again around 9 pm EST and the GTF loaded as it should. It isn't clear what the fix was so I'll leave this issue open.

**Comment by jennaj** [comment]
Tested and fixed! Details:

1. A new GTF dataset (even in an older history) will load
1. A GTF dataset that previously failed trackster load will now load if the "try again" link is used within trackster
1. A saved trackster visualization that had a prior failed GTF load, when opened, will now start loading the data without any additional user action (this is great!)

Users that encounter problem 2 above will need to know about the "Try again" solution. Not sure if worth a permanent support help page, let's see how many ongoing questions about this we get first and decide.
