### ISSUE TITLE
possible bug in workflow->new history with multiple datasets

### ISSUE THREAD

**Issue by jvolkening** [galaxyproject/galaxy#3500]
See [here](https://biostar.usegalaxy.org/p/21402/).

In short, after upgrading to 16.10, sending workflow with multiple linked inputs to new histories fails. There seems to be a bug on line 191 of $INSTALL//lib/galaxy/workflow/run_request.py.

`nh_name = '%s on %s and %s' % ( nh_name, ', '.join( ids[ 0:-1 ] ), ids[ -1 ] )`

Quick fix seems to be:

`nh_name = '%s on %s and %s' % ( nh_name, ', '.join( map(str,ids[ 0:-1 ] )), ids[ -1 ]`

(at least this worked on our instance to allow this functionality). I'm happy to submit a PR but there's probably a better fix than this (I'm not really a Python coder) and I'm not certain it's not a problem with my install (since I can't find any other reports of it).

**Comment by nsoranzo** [comment]
Ping @guerler

**Comment by guerler** [comment]
Thanks for reporting and fixing this.

**Comment by nsoranzo** [comment]
Fixed in #3532.
