### ISSUE TITLE
Old revisions of tools in "Manage installed tools" list

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#3501]
1. Log into a Galaxy instance as a local administrator
2. Click on the top ribbon menu entry "Admin"
3. From the left hand column, click on "Manage installed tools"
4. Browse the table, and look for a batch of entries for the same tool e.g.

<img width="1137" alt="screenshot 2017-01-27 11 16 21" src="https://cloud.githubusercontent.com/assets/63959/22369198/647a8858-e482-11e6-98bb-25a7cf71afea.png">

This example shows three revisions of my Tool Shed repository ``tmhmm_and_signal`` are installed, with up-red, up-red and green-tick icons.

The legend key reads:

* orange-warning-triangle = Updates are available in the Tool Shed for this revision
* up-red-arrow =  A newer installable revision is available for this repository
* green-tick =  This is the latest installable revision of this repository
* red-cross = This repository is deprecated in the Tool Shed
* grey-cog = This repository contains exported workflows
* blue-question =  Unable to get information from the Tool Shed

Q: It is sensible for the table to show multiple rows when multiple revisions of a tool are installed?

Q: Given I have the latest version of  ``tmhmm_and_signal`` installed (third entry, wth green-tick), it is misleading to show the two older versions with an up-red-arrow given the current meaning "A newer installable revision is available for this repository". There IS NOT a newer installable version available  - the newest installable version is *already* installed.

Should the old installed revisions be hidden? Or do they just need a new unique icon, something muted/grey indicating they are an old superseded version with a newer copy already installed?

**Comment by nsoranzo** [comment]
This may be fixed using the new beta interface enabled with:
```
enable_beta_ts_api_install = True
```
in `config/galaxy.ini` (but I haven't tried it).

**Comment by martenson** [comment]
@peterjc I have WIP at https://github.com/galaxyproject/galaxy/pull/2930 that is reworking this view completely. Amongst other things it will collapse multiple versions of the same repository into one row.

You can see some screenshots at https://github.com/galaxyproject/galaxy/pull/2250

**Comment by nsoranzo** [comment]
Ah, that was it @martenson, sorry for the confusion!

**Comment by peterjc** [comment]
Thanks @martenson - the ideas and screenshots describing how to handle multiple versions, and the subtleties of minor revisions vs new versions, seems to cover everything I have flagged here (i.e. #3501).

**Comment by martenson** [comment]
I think we have addressed all points of this issue with recent changes to this view, already merged to dev, notably: https://github.com/galaxyproject/galaxy/pull/8601

Closing.
