### ISSUE TITLE
Job scheduling page lists hidden outputs

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#3518]
This just struck me as a bit odd, the successful submission of a job with hidden outputs lists those in the green box. They were hidden from the user by default in their history, I'd argue they should be hidden in this list too. 

In the following, 39 is the only output that doesn't have `hidden="true"` set on it.
![utvalg_106](https://cloud.githubusercontent.com/assets/458683/22449380/ccc60e32-e757-11e6-9a0e-be7bc6b7ab44.png)

**Comment by blankenberg** [comment]
I'd counter that the hidden elements should be demarcated as hidden, but known to the user; they are consuming HIDs and do exist in the history. 

But, agreed, kinda goofy to look like four items, but only have one visible.

Bonus points for a click spot to unhide the extra items, that you may want, in this message.

**Comment by hexylena** [comment]
I guess it hasn't bothered anyone else in 2,5 years so closing this.
