### ISSUE TITLE
History disappears

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/galaxy#3519]
Sometimes it happens that a history is not shown in the 'View all histories'. To get it back it helps to search for it or to use a different browser. It is an annoying bug, should be fixed asap. 

Thank you.

**Comment by dannon** [comment]
@joachimjacob Can you elaborate?  Is the history possibly deleted, and that's why it's not showing up originally?

**Comment by joachimwolff** [comment]
No of course it is not deleted. If that would be the case it would be weird if it shows up at the search or on another browser. It looks like the caching mechanism or so is not working as it should be. I cannot really elaborate it. I just click on 'View all histories' and sometimes not all histories are shown. I am using Google Chrome if this information helps.

If I can run any checks to help to find out whats going on just ask.

**Comment by ieguinoa** [comment]
I'm deploying a new instance to production and I'm experiencing the same trouble, that is, not all histories are shown in 'View all histories'. As far as I could test:

- There is no clear pattern of which stories are/aren't shown. Although, it seems that the histories created previously to the current one are 'usually' listed. 

- As far as I can tell this problem occurs only in v16.10. Tested on v16.07 and there is no problem.

- In my case it is not related to the browser I'm using (though I've only tested on Chrome and Firefox).

- The problem is the same with both sqlite and mysql.

- The problem also stays the same whether I use a proxy (we use Apache) or not.

- There is also a possibly related problem: if I change something in welcome page (static/welcome.html) it's really hard to get the update in my browser: It is not updated if I just refresh the page, but instead I have to remove all cache from my browser or right click over the page and reload the frame. The thing is that this also happens only with v16.10 and not v16.07 (proxy and server configuration is the same) and could also be related with a possible cache-like problem. 
At the moment I ran out of ideas to further test this.

Maybe @joachimwolff already found the cause/solution?

Thanks in advance for the help.

**Comment by mvdbeek** [comment]
I have also seen this happen, but so infrequently that I thought I'm just blind and not finding my history. Seems I'm not.
FWIW I haven't had that problem with the old view saved history button.

**Comment by dannon** [comment]
I think this is likely related to the 'null' history bug I'm trying to reproduce.  I'll keep this issue in mind when I work on that.

**Comment by joachimwolff** [comment]
@ieguinoa  Only solution so far is to delete the browser cache.

**Comment by hexylena** [comment]
@elenimijalis and I see this happen too. Note that missing histories do show up in the old view histories menu, as far as I can tell.

**Comment by maxf130** [comment]
I am also experiencing this bug.  Sometimes some histories are not displaying in the 'View all histories' browser.  They do show up when searching, or when viewing the 'Saved Histories' page. This has been noted by two users, and I've been able to reproduce the effect while impersonating one of them.

We are currently running galaxy 17.01, so this is not limited to the 16.xx branch.

Here is a description of the problem by one of the affected users:

> I have two Histories set up in Galaxy for each of my runs – so I didn’t get the separate runs confused. This has been working fine for the whole time I have been using Galaxy. However, I seem to be having an issue at the moment. Having finished aligning the samples in the 1st run – I switched histories to the second run. This went fine. But when I went to switch back to the 1st run to retrieve the b.tau fasta file, the 1st history is no longer in the Histories page – so there is nothing for me to switch to, all I can see is my current history of run 2! Yet my percentage space used is still accounting for having all the data present for both histories. I’ve checked this on Mozilla, Chrome and Explorer – just in case it was a glitch with the browser. I’ve also logged out of Galaxy several times – no reappearance of the data, but no change in the disk space allowance – says I am using 144 GB – but the data set it is letting me see only has 35 GB in it.
> 
> 
> 
> There is also an option on the histories page to let you view deleted histories – I’ve clicked this, just in case I managed to delete it, but it still doesn’t appear.
> 

EDIT:

@joachimwolff Clearing the cache does not appear to help.  I'm using Firefox 52.1.0 for reference.

**Comment by blankclemens** [comment]
I can confirm this bug as well - that's when I started to really think about proper titles to find them again. ;)

**Comment by maxf130** [comment]
@blankclemens It's clearly an undocumented feature to encourage users to use descriptive names.

**Comment by blankclemens** [comment]
Hehe, it clearly is!

**Comment by mvdbeek** [comment]
I've added a milestone, even though 17.09 is probably not realistic. I'm sure this affects a lot of people and is quite annoying.

**Comment by dannon** [comment]
Can folks in this thread comment on the likelihood of the problem being what I'm seeing in #4605?

It's looking incredibly likely, to me, that that's the root of this.  We assume (incorrectly) that the 'current' history is the most recently updated one, and if that isn't the case, the most recently updated (non-current) history is excluded from the set of histories presented in the multiview.

Does that scenario fit with what you've all reported here?

**Comment by maxf130** [comment]
I can't be certain that that was happening with us, but it certainly seems likely.  

Just try fixing #4605 in the way described.  Worst case scenario is: You will only fix one bug.

**Comment by dannon** [comment]
@maxf130 Yeah, that's the plan, just trying to nail this issue down to a particular likely cause while I'm at it :)

**Comment by hexylena** [comment]
@dannon this would go with some comments I've heard. I don't remember it behaving like this at $oldjob, but at $currentjob, I've heard reports about new histories and those disappearing so it'd make sense.

**Comment by mvdbeek** [comment]
So for me https://github.com/galaxyproject/galaxy/pull/4610 solved the problem, if someone else can confirm this I think this issue can be closed (unless we want to backport the fix).

**Comment by cche** [comment]
Hi Marius,
I can confirm that this solves the issue in 17.05.
Thanks a lot @dannon ! This was really annoying my users quite a bit.
