### ISSUE TITLE
Miniconda 2 Python Problems

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3525]
Certain packages such as unicycler fail to automatically pick up the Python 3 dependency when installed via Conda from miniconda2. We should figure out a workaround for this and document it on the Conda FAQ.

**Comment by bgruening** [comment]
For miniconda2 environments, the workaround would be to include python=3.5.2 as a dependency. @mvdbeek and me tried a few packages and this seems to be a general miniconda2 problem. We do not see the same problem with miniconda3 and picking up python2 environments.

**Comment by mvdbeek** [comment]
Right, I think that's a conda bug. I have opened https://github.com/conda/conda/issues/4492 for this.

**Comment by mvdbeek** [comment]
yay, I think they've actually fixed this.
