### ISSUE TITLE
Galaxy support for Synnefo Object Store

### ISSUE THREAD

**Issue by saxtouri** [galaxyproject/galaxy#3526]
Hello,

I work for www.grnet.gr and I'm developing a Galaxy storage backend for Synnefo (www. synnefo.org) Object Store (code named "Pithos+", REST API is based on OpenStack). You can find it here: https://github.com/saxtouri/galaxy/tree/feature-pithos

Synnefo is being used by www.grnet.gr to power the okeanos.grnet.gr academic cloud with thousands of users from the Greek and European academic community. Galaxy is going to be adopted as a core component for the OpenMinTeD (Open Mining for Text and Data) project, in which we participate as infrastructure providers. Plenty of other projects funded by European academic institutions make use of our cloud infrastructure and we expect to host even more in the future, so I think this patch is going to be useful in a variety of contexts.

I hope the galaxy community is interested in supporting more cloud platforms. What can we do to ensure that our patch can reach a state of maturity good enough for a pull request?

**Comment by mvdbeek** [comment]
Hello @saxtouri 

> I hope the galaxy community is interested in supporting more cloud platforms. What can we do to ensure that our patch can reach a state of maturity good enough for a pull request?

We generally welcome all PRs, include those you are still working on. Feel free to open as early as you want, there is no minimum required maturity. The earlier we can provide feedback the better.
We will try to assist you if you are having issues.

We aim to have object store related code in a single module in https://github.com/galaxyproject/galaxy/tree/dev/lib/galaxy/objectstore, so this is fairly isolated from the rest of galaxy. If it works for you and doesn't impact other functionality I'm fairly certain we will include your code.

**Comment by hexylena** [comment]
@fpsom might be interesting to you.

I guess we've answered the original question regarding how to help them, in Marius' answer. <s>Hope you contribute this at some point @saxtouri!</s> Oh it was contributed! Awesome :D
