### ISSUE TITLE
Unbounded readline in genbank datatype.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3529]
https://github.com/galaxyproject/galaxy/pull/3339 This is merged with a unbounded readline - this causes memory problems on certain inputs.

Creating an issue here to track but I'll open a PR with a fix in a bit.

**Comment by hexylena** [comment]
Crap, sorry @jmchilton. Thanks for noticing. That should have been `.read(5)`, it was in a previous iteration.
