### ISSUE TITLE
ImportError: No module named galaxy.util.ucsc at http://usegalaxy.org with GOPS tools

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3539]
Dependency missing?

**Example tool: Operate on Genomic Intervals > Wiggle-to-Interval** 

Error

> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/tools/filters/wiggle_to_simple.py", line 13, in <module>
>     from galaxy.util.ucsc import UCSCLimitException, UCSCOutWrapper
> ImportError: No module named galaxy.util.ucsc

History with test case 
https://usegalaxy.org/u/jen/h/wiggle-to-interval-tool-test

cc @galaxyproject/guac

**Comment by jmchilton** [comment]
Fixed in #3540 - sorry about that. Thanks for tracking these down.
