### ISSUE TITLE
Request: Increase memory allocation for Kraken tools at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3543]
The [Kraken Classification tool](http://toolshed.g2.bx.psu.edu/repos/devteam/kraken/kraken/1.2.1) leads many others in failing for this error by exceeding memory resources. Users have also reported bug-report failures and the inputs are not large (~ 2 GB fastq, paired).

Default cluster:
> This job was terminated because it used more memory than it was allocated.

Jetstream targetted:
> Fatal error: Exit code 71 (Tool exception)
classify: unable to mmap 
> /cvmfs/data.galaxyproject.org/managed/kraken_database/bacteria/Bacteria/database.kdb: Cannot allocate memory

Workarounds for users encountering this job failure:

 - Run FastQC on the input and address data quality issue issues (trim/filter), then rerun.
 - Consider testing/using the option "Enable quick operation?" set to "Yes" with max hits at "1".
 - Move to a [local or cloud Galaxy](https://new.galaxyproject.org/big-picture/choices/) with increased memory resources. **This option is required if the target database is Bacteria.**

To-do: link to other tool memory resource requests/issues

cc @galaxyproject/guac

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/issues/2666

**Comment by blankenberg** [comment]
This tool is going to use memory approximately equal to the size of the database that it is loading, input file size shouldn't really matter.

In this specific case, thats ~66GB.
```
ls -lah bacteria/Bacteria/database.kdb 
-rw-r--r-- 1 cvmfs cvmfs 66G May  6  2015 bacteria/Bacteria/database.kdb
```

**Comment by martenson** [comment]
I think we have only 16 and 64GB extra brackets now :/

**Comment by jennaj** [comment]
Until the memory resource is available, should we:

1. Remove the Bacteria database active on main? Jobs will always fail.
2. Check the size of the other databases and remove any that are also over the limit of 64 GB? Jobs against any other database over the limit would also always fail.

**Comment by Slugger70** [comment]
You could use minikraken.. its only ~4GB. Or have it as an option

**Comment by jennaj** [comment]
Closed: https://github.com/galaxyproject/usegalaxy-playbook/issues/34
