### ISSUE TITLE
checksum example tool is broken

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3544]
See conversation here https://github.com/galaxyproject/galaxy/pull/3530

**Comment by nsoranzo** [comment]
I'm actually more worried by `planemo lint` and `planemo test` not complaining about a test on a non-existent output.

**Comment by jmchilton** [comment]
@nsoranzo I wouldn't describe myself as worried per se - but I agree that is more important. I don't think it is something planemo has ever done but I think it should obviously. I'll try to find some time to work on that - I'm trying to think about if there are any corner cases or if it is in fact as straight forward to implement that as it would seem.

**Comment by jmchilton** [comment]
In planemo's master branch - this would have been caught as of https://github.com/galaxyproject/planemo/commit/5e1e4f4fa7f0e3ac3281abe007066cee51c9fae8 and https://github.com/galaxyproject/galaxy-lib/commit/d7cdd38f867d1d2c2a5323f0e4504d8a78ddeea3.
