### ISSUE TITLE
Kraken missing dependencies at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3556]
Fixes:

- [ ] Update kraken on main to use conda dependencies.
- [x] Update krona pie chart on main to use conda dependencies.
- [x] Update kraken2tax with conda dependency, update repository on main

**Error**:

> "Fatal error: Exit code 127 (Tool exception)
> /cvmfs/main.galaxyproject.org/deps/kraken/0.10.6-eaf8fb68/iuc/package_kraken_0_10_6_eaf8fb68/0743afe4dcb8/bin/classify: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory"

**Comment by jennaj** [comment]
Other Kraken tools have issues as well at Main:

**Krona pie chart from taxonomic profile (Galaxy Version 2.6.0)**

> Tool execution generated the following error message:
> tput: No value for $TERM and no -T specified
> tput: No value for $TERM and no -T specified

**Convert Kraken data to Galaxy taxonomy representation (Galaxy Version 1.1)**

No taxonomy databases available on the tool form

cc @davebx @galaxyproject/guac

**Comment by jennaj** [comment]
Related: https://github.com/galaxyproject/galaxy/issues/2536

**Comment by jennaj** [comment]
Problems persist. Some of the errors above are linked to the roundup cluster.

**Comment by davebx** [comment]
@jennaj Kraken to taxonomy should work as of tool version 1.2

**Comment by jennaj** [comment]
thanks @davebx - testing in progress

**Comment by davebx** [comment]
@jennaj Krona appears to be working as of 2.6.1.

**Comment by jennaj** [comment]
Great, will test that portion and (hopefully) get this closed out

**Comment by tshippy** [comment]
When I try to use the Convert Kraken to Taxonomy tool (version 1.2), I still don't see any taxonomy databases in the pull down menu.  Were you able to get it to work?  I have used the tool successfully on the Galaxy Test server, but would like to incorporate it into a workflow on the Main server.

**Comment by jennaj** [comment]
Hello - the tool Convert Kraken data to Galaxy taxonomy representation (Galaxy Version 1.2) has a single taxonomy database available at https://usegalaxy.org (NCBI-2015-10-5). Please try again now.

Krona is also again now working as expected. Closing out.
