### ISSUE TITLE
https://galaxy.readthedocs.io is still online but not updated

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#3563]
See here: https://galaxy.readthedocs.io/en/master/releases/index.html
Found at the GAT2017 in Melbourne.

**Comment by martenson** [comment]
We tried to address this with @jxtx in the past using: https://github.com/galaxyproject/readthedocs-redirect

I tried to finish the job now so http://galaxy.readthedocs.io/en/master/ will now redirect you to https://docs.galaxyproject.org/en/master/ however we were not able to redirect subpages.
