### ISSUE TITLE
Default fastq uploads to fastqsanger

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#3571]
Something that comes up at nearly every community event is user confusion over the fastq/fastqsanger datatypes. Given that (it is my understanding that) the sequencing industry and tool developers long ago settled on the Sanger standard for FASTQ files, can we now default FASTQ uploads to the fastqsanger datatype?

**Comment by bgruening** [comment]
Yes please!

**Comment by jxtx** [comment]
I think this is fine.

(We could maybe do a quick check for signs that something is not
fastqsanger, while we can't detect what score a given file uses you can
detect when it is *not* for some files).


-- jt

**Comment by hexylena** [comment]
Fun fact: this is *the* most upvoted issue in galaxyproject/galaxy (exploring the new sort by reaction feature.)

**Comment by jennaj** [comment]
FYI - testing this on main, feedback soon, thank you @dpryan79 !!

**Comment by dpryan79** [comment]
@jennaj Thanks, I'm looking forward to upgrading to 17.09 :)

**Comment by jennaj** [comment]
This has been included in the upcoming `17.09` and tested at https://usegalaxy.org and a local. Closing out! Thanks everyone
