### ISSUE TITLE
Toolshed : Broken download link for package_weblogo_3_3

### ISSUE THREAD

**Issue by maudeardin** [galaxyproject/galaxy#3574]
In the tool_dependencies.xml file,
the download link http://weblogo.googlecode.com/files/weblogo-3.3.tar.gz is broken.

The new download link is on github : https://github.com/WebLogo/weblogo/archive/master.zip.

**Comment by nsoranzo** [comment]
@maudeardin Thanks a lot for reporting! The correct download location for version 3.3 is https://github.com/WebLogo/weblogo/archive/3.3.0.tar.gz .

For future reference, the best place to report a bug in a Tool Shed repository is indicated in the "Development repository" field of its page, which for https://toolshed.g2.bx.psu.edu/view/devteam/package_weblogo_3_3/ is https://github.com/galaxyproject/tools-devteam/
