### ISSUE TITLE
Galaxy Architecture Documentation - Iteration 2

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3588]
# Overview

This is a follow up on #2244, #2283, and #3060 that resulted in bringing a set of Galaxy Architecture slides and diagrams into the main code base - as Markdown and PlantUML. 

## Main Goals before the GCC

- [ ] Update content for late 2016 and early 2017 changes.
- [ ] Expand content to cover or link out to in-depth information about:
   - [ ] Contributing to Galaxy.
   - [ ] Admin topics (proxies, uwsgi, supervisor, etc...).
   - [ ] Dependency resolution.
   - [ ] Conda FAQ.
   - [ ] Webhooks.
   - [ ] Testing.
   - [ ] Authentication.
   - [ ] Datatypes.
- [ ] Align with training_material (and Galaxy Hub by extension).
    - [x] ~Use common Markdown to Slide technology (remarkjs).~
    - [x] Use training_material CSS for remarkjs in Galaxy core.
    - [ ] Find a way to export and link out to the Galaxy module from training_material.
- [ ] Align with sphinx in core (docs.galaxyproject.org).
   - [ ] Find a way to include an extended version of the slides into the Sphinx documentation.

## Extended Goals

- [ ] Implement a IPython notebook walking the code base and describing things.

**Comment by martenson** [comment]
GAME admin training is now done and the dagobah repos are very relevant to at least this:

> Admin topics (proxies, uwsgi, supervisor, etc...).
> Authentication.

xref: https://github.com/gvlproject/dagobah-training/issues/4

**Comment by hexylena** [comment]
@jmchilton how do you feel about the progress on this with the training materials tutorials? Did we accomplish a sufficient portion of this?

**Comment by jmchilton** [comment]
Those slides are very out of date - but I guess a new issue should be created on Training Materials for that.
