### ISSUE TITLE
Tool reload button does not respect galaxy path prefix

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#3591]
- {"extra": {}, "version_major": "17.01"}
- galaxy available at /galaxy
- request made to /api (should be /galaxy/api)

![utvalg_147](https://cloud.githubusercontent.com/assets/458683/22838262/5423af08-efbc-11e6-8e2e-d2ee54d96c76.png)

**Comment by nsoranzo** [comment]
Fixed in #3595.
