### ISSUE TITLE
Search box stays visible in firefox after closing tool panel

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#3592]
![utvalg_149](https://cloud.githubusercontent.com/assets/458683/22839103/fffc7bc2-efbf-11e6-8b61-87d0af61770a.png)

- load usegalaxy.org in firefox
- close tool panel
- box is still visible

I'm on 51.0.1, x64, linux

**Comment by dannon** [comment]
This is fallout from positioning tweaks to get the search box to stay at the top of the tool panel.  The structure makes it difficult to handle in a uniform fashion, so I'm just going to revert that change I think.  It'll be easier when we restructure the toolbox.

**Comment by martenson** [comment]
just a note: this works well on Chrome@macOS

**Comment by scholtalbers** [comment]
Just to note, this is still happening on Firefox 57.0.1 (64-bit) on macOS High Sierra:

<img width="235" alt="screen shot 2017-12-11 at 16 32 51" src="https://user-images.githubusercontent.com/102411/33838986-4c8dfc20-de91-11e7-84cc-1b7c24334348.png">

**Comment by martenson** [comment]
This seems to work well with the latest redesign as seen on test.galaxyproject.org
