### ISSUE TITLE
Enforcing permissions on sensitive files?

### ISSUE THREAD

**Issue by jvolkening** [galaxyproject/galaxy#3597]
There are at least two files (`galaxy.ini`, log file) and maybe others than can contain sensitive information that would allow unauthorized access if read. With the default umask settings of many distros, these files will be initially created as world-readable, which would be a security risk if the system had other local users and the permissions were not adjusted.

Some software (`ssh` comes to mind, for instance) will check for proper file permissions on potentially sensitive files and refuse to run if not set correctly. I'm wondering if doing something similar in Galaxy would make sense as an extra layer to protect against local misconfiguration. I tried looking through the source to implement this myself but couldn't figure out exactly where it should properly be done (`run.sh` or `paster.py` or `lib/galaxy/util/pastescript/serve.py`, etc...). If this seems like a good idea to others and you can point me in the right direction, I can try to implement.

**Comment by blankenberg** [comment]
Galaxy permission model should match and exceed Linux PAM.

**Comment by jvolkening** [comment]
> Galaxy permission model should match and exceed Linux PAM.

'Exceed' in this case meaning Galaxy enforces a policy (e.g. no global read) on sensitive files? This is what I'm wondering about. Plenty of applications do this for config files, etc, beyond what is set in the PAM default umask.

**Comment by hexylena** [comment]
We've enforced best practices in the Ansible Galaxy playbooks, they are built in options to ensure correct permissions and privilege separation. We encourage administrators of production systems to use that setup and to do privilege separation by default, and read our documentation on securing Galaxy. This has mostly been sufficient.
