### ISSUE TITLE
Fix Tour Testing

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3598]
# Major Bug

- core_galaxy_ui tour test is broken on Jenkins and will be disabled. It passes most of the time - but there seems to be some problem

# Enhancements

- Develop standalone tool for testing tours.
- Embed information in tours about preconditions to make them more robust.
- Make tour testing more robust by placing a small sleep between each step to allow transitions to complete. If an item is clickable and then not clickable and then clickable again catch that and process just the last state.

**Comment by bgruening** [comment]
xref: https://github.com/bgruening/docker-galaxy-stable/pull/278

**Comment by guerler** [comment]
Seems to have been resolved, `core_galaxy_ui` is part of the selenium tests in current dev, and pass reliably. Closing this for now.
