### ISSUE TITLE
rheMac3 has 2 copies of the index files listed in the data table, but at different directories at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3605]
Found by @blankenberg in a bug report

> Job Execution and Failure Information
>
> Command Line
>
> tophat2  --num-threads ${GALAXY_SLOTS:-4}  --read-mismatches 2  --read-edit-dist 2 --read-realign-edit-dist 1000 -a 8 -m 0 -i 70 -I 500000 -g 20 --min-segment-intron 50 --max-segment-intron 500000 --segment-mismatches 2 --segment-length 25 --library-type fr-unstranded  --max-insertion-length 3 --max-deletion-length 3         /galaxy/data/rheMac3/bowtie2_index/rheMac3,/cvmfs/data.galaxyproject.org/managed/bowtie2_index/rheMac3/rheMac3 "/galaxy-repl/main/files/XX/XX/XX.dat"
>
> stderr
> 
> Fatal error: Tool execution failed
>
> [2017-02-06 17:03:13] Beginning TopHat run (v2.1.0)
>
> -----------------------------------------------
> [2017-02-06 17:03:13] Checking for Bowtie
> 		  Bowtie version:	 2.2.5.0
> [2017-02-06 17:03:13] Checking for Bowtie index files (genome)..
> Error: Could not find Bowtie 2 index files (/galaxy/data/rheMac3/bowtie2_index/rheMac3,/cvmfs/data.galaxyproject.org/managed/bowtie2_index/rheMac3/rheMac3.*.bt2)

cc @galaxyproject/guac @natefoo

**Comment by mvdbeek** [comment]
Not really a Galaxy issue (but going to work on the reliability of data managers)
