### ISSUE TITLE
DMs broken in the datamanager Galaxy instance

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#3606]
None of the installed DMs loads in the 'local data' admin menu.

found by @natefoo 
to be investigated by @blankenberg 

The culprit might be the explicit call to `store_tool_path=False` at https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/data_manager/manager.py#L45

**Comment by bgruening** [comment]
Mh, I do see all my DMs in 17.01.

**Comment by davebx** [comment]
Resolved with #3989
