### ISSUE TITLE
Make pipefail the shell default for jobs in profile >= XX.XX 

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3612]
Thanks to @mvdbeek for the idea https://github.com/galaxyproject/tools-iuc/commit/c2c2f416675d003e521d7178b07fb28f7833aa32#commitcomment-20880370

**Comment by nsoranzo** [comment]
:-1: 

Quoting from http://cfajohnson.com/shell/cus-faq-2.html#Q11 :

> Note that cmd1 exit code could be non-zero and still don't mean an error. This happens for instance in
> ```
> cmd | head -1
> ```
> you might observe a 141 (or 269 with ksh93) exit status of cmd1, but it's because cmd was interrupted by a SIGPIPE signal when "head -1" terminated after having read one line.

**Comment by mvdbeek** [comment]
~~OK, so is it an option to just ignore 141 (and 269, just in case ...), or are there other cases?~~

I guess that wouldn't be very easy ... .
