### ISSUE TITLE
Collections: How to provide a list of paired files and return a list of files in the XML file?

### ISSUE THREAD

**Issue by brkldj** [galaxyproject/galaxy#3617]
Hi all,

I am making a galaxy tool that should take a collection (a list of paired files), and return one file per pair (a list of files). More specifically, as the input the user should provide fastq files (paired) from RNA-seq for different conditions (thus, a list of paired files). The program should take one pair at the time, map the reads, and return one bam file per pair (a list of files). It sounds like a straightforward problem but I am failing at specifying the inputs and outputs in the XML file.
Here is what I have so far:

```
<tool id="mapper" name="mapper">
  <description>Align RNA reads from several experiments to the reference genome, one experiment at the time</description>
  <command interpreter="bash"> 
    #for $pair in $list_pairs.keys()#
    perl mapper.pl -g $genome --r1 $list_pairs[$pair]['forward'] --r2 $list_pairs[$pair]['reverse'] --outbam $outbam[$pair]
    #end for#
  </command>
  <inputs>
	<param name="genome" format="fasta" type="data" value="" label="Genome fasta file"/>
	<param name="list_pairs" type="data_collection" collection_type="list:paired" value="" label="collection with a list of pairs"/>
  </inputs>
  <outputs>
    <collection name="outbam" type="list" inherit_from="list_pairs" label="list of BAMs"></collection>
  </outputs>
</tool>
```
The error that I get is `Error executing tool: Cannot pre-determine structure for collection of type list`.

For example, it is unclear to me how to access the paired files (my attempt is `$list_pairs[$pair]['forward']`), especially since in the examples I found [online](https://github.com/galaxyproject/galaxy/blob/dev/test/functional/tools/collection_two_paired.xml), a call for the forward file has a different syntax from the reverse file.
Also, should I specify that the output inherits_from the list of pairs even though it is only a list of files?

Any help is greatly appreciated.

**Comment by mvdbeek** [comment]
Hi @brkldj 
A bunch of things to note here

`<command interpreter="bash">` is deprecated. Change this to a simple `<command>`.
If you want to ship the script with the tool, you can do `perl $__tool_directory__/mapper.pl`.

It doesn't look like your tool should be limited to a `"list:paired"`, you can simply ask for a `"paired"` collection.
If you have a list of pairs, that will run the tool once per pair, creating a list of BAM files.
In the output section you don't need to create a collection, a simple single BAM output is fine.
If the input is a pair, you'll get a single BAM file, if the input is a list of pairs, you'll get a list.

Have  a look at https://github.com/galaxyproject/tools-devteam/blob/master/tools/bwa/bwa.xml#L316
which is accepting a variety of collection and non-collection fastq input and produces a simple BAM output.

Finally if you want to continue the route you're on (I would advise you not to do that), remove the `inherit_from="list_pairs"` and explicitly specify the format.

In general I think this type of request is better served on the [galaxy mailing list](https://wiki.galaxyproject.org/MailingLists),  [biostars](https://biostar.usegalaxy.org/), or the [iuc gitter channel](https://gitter.im/galaxy-iuc/iuc).
We try to keep this repository for the development of core galaxy.
