### ISSUE TITLE
Importing history data might fail but still report success

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/galaxy#3627]
[16.10][Minor]

I am importing a history from a previous Galaxy instance, that import fails (which is itself a bug, to be reported on a separate issue), but the job is reported as successful.

In my case the fail is occurring in
unpack_tar_gz_archive.py

As a side issue (not really a bug?) the part of the file that is read, is still imported (so I end up with an incomplete history imported)

![galaxy](https://cloud.githubusercontent.com/assets/34787/23043923/575c4f88-f45b-11e6-844f-0ebc483afe99.png)

**Comment by mvdbeek** [comment]
Fixed that a long time ago, so for the late feedback
