### ISSUE TITLE
Workflows - input dataset names do not appear on launch form

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/galaxy#3633]
Since the update to 17.01 on Main the names and annotation/notes of input datasets assigned in the workflow editor do not appear on the workflow launch form. This is the case for workflows starting from standard and collection-based input.

**Comment by guerler** [comment]
Fixed with #3593

**Comment by bgruening** [comment]
@guerler but this only targets dev, isn't it?

**Comment by guerler** [comment]
Thats true, I can work on a fix for 17.01 today.
