### ISSUE TITLE
Request to add Ballgown to http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3639]
**NGS: RNA Analysis** tool addition

Tool Shed link: https://toolshed.g2.bx.psu.edu/view/iuc/package_ballgown_1_0_3/3b4172677e20

**Comment by bgruening** [comment]
@jennaj thats just the package. Afaik @davebx was working on a wrapper ... ?

**Comment by martenson** [comment]
Conda has 2.2.0 https://api.anaconda.org/search?name=ballgown

**Comment by jennaj** [comment]
Agree, package only in MTS, no tool wrapper. Wasn't sure if missing part was just not loaded yet or still in progress.

**Comment by martenson** [comment]
@jennaj if there is no PR in iuc and devteam repos or tool in TTS you can probably mail to dev-list and ask. 

However it seems there is no wrapper for balgown yet, closing.

**Comment by martenson** [comment]
@jennaj (you could create an issue in iuc using label ~~new software~~ [wrapper-request](https://github.com/galaxyproject/tools-iuc/labels/wrapper-request)

**Comment by jennaj** [comment]
@martenson Ok, will do that.

**Comment by jennaj** [comment]
I couldn't assign the label (no permissions) - would someone else be able to do that? Thanks!
