### ISSUE TITLE
managing user information broken

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#3647]
On Main (17.01) as an admin managing user (in the admin/user menu) I am getting:
```
Not Found

The resource could not be found. 
No action for /user/manage_user_info
```

Probably connected to https://github.com/galaxyproject/galaxy/pull/3118

ping @anuprulez @dannon

**Comment by dannon** [comment]
Yep, looks like it's related.  I'll get a fix out in a sec.

**Comment by nsoranzo** [comment]
Saw that too but forgot to open an issue, thanks @martenson.

**Comment by guerler** [comment]
Thanks @dannon. Sorry for missing that. Looks like it needs to be re-routed to the users endpoint.

**Comment by dannon** [comment]
Yeah, of course this is noted *after* the release :)  No worries though, should be fixable today.

**Comment by martenson** [comment]
Obviously - due to a completely unrelated bug report with activation. :D
