### ISSUE TITLE
common_startup.sh does not take into account GALAXY_UNIVERSE_CONFIG_DIR environment var

### ISSUE THREAD

**Issue by IyadKandalaft** [galaxyproject/galaxy#3650]
The common_startup.sh script that is executed by run.sh does not use paths defined in galaxy.ini to create new configuration files. As a result, it creates configuration files in ./config/ by removing the ".sample" suffix and copying them in place.

Known affected branches include all release_16.x and release_17.10

**Comment by IyadKandalaft** [comment]
Recommendation is to use the galaxy config parser to parse out all the config file paths and have them created there.

**Comment by hexylena** [comment]
I think this might be working now? Please re-open if it's still an issue :)
