### ISSUE TITLE
Salmon failing for dependency issues at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3660]
Error: 

> salmon: error while loading shared libraries: libgomp.so.1: cannot open shared object file: No such file or directory

Details:

```
Tool ID	toolshed.g2.bx.psu.edu/repos/bgruening/salmon/salmon/0.7.2
Tool Version	0.7.2
Job PID or DRM id	9269475.roundup
```

Looks like a fix was made here when the dependencies were needed by another tool: https://github.com/galaxyproject/tools-iuc/pull/1040

**Comment by jennaj** [comment]
@davebx @bgruening Is this something we could get fixed at http://usegalaxy.org? I wasn't 100% sure if the problem was an install dependency issue (Main only) or if this impacts the repo/dep config too.

**Comment by bgruening** [comment]
We should update to version 0.8.2 .... @davebx do you have time to update the wrapper?

**Comment by jennaj** [comment]
While this error still is present for proper .fq input (full dataset, uploaded), if the fq results from another tool ("output mapped/unmapped reads), it fails for a different reason (standard memory-exceed failure). Yet, doesn't look to be size related. The sequence identifiers may be the problem. I can share an example direct if that would help.

I am testing to see if the format of the identifiers is the problem, as they were non-standard for this case, but the tool is given fwd/rev reads on the form, so the content of the identifiers on the title should not really matter, correct?

**Comment by davebx** [comment]
@jennaj this seems to be resolved with wrapper version 0.8.2, courtesy of @martenson

**Comment by jennaj** [comment]
Great - I see bugs abt this from 18th I was holding on v 0.7.2 - will run test v 0.8.2 and then close out if resolved. Give me a few. Tx!

**Comment by jennaj** [comment]
I cannot get a successful run (memory failures). Might be due to this: https://github.com/galaxyproject/galaxy/issues/4102

**Comment by jennaj** [comment]
Got one to go through. Thanks for the tool update!! Closing this one out. But we should still look at the memory allocation (in the other ticket).
