### ISSUE TITLE
typo in tool syntax doc

### ISSUE THREAD

**Issue by jvolkening** [galaxyproject/galaxy#3667]
There was a typo introduced to the [tool syntax documentation](https://docs.galaxyproject.org/en/latest/dev/schema.html) that prevents the `delta` attribute from showing up properly on the webpage. I have no idea how to test this so I'm not submitting a PR, but I believe the culprit is line 1098 of `/lib/galaxy/tools/xsd/galaxy.xsd`. Is there a missing backtick at the end of the line (e.g. the single should be double)?

**Comment by martenson** [comment]
`make docs` should build this locally in order to test this. I am on it though. Thanks @jvolkening

**Comment by hexylena** [comment]
Delta shows up now
