### ISSUE TITLE
17.01: missing input dataset labels in workflow run menu

### ISSUE THREAD

**Issue by shiltemann** [galaxyproject/galaxy#3672]
Hi all,

I upgraded to release_17.01 and noticed that in the workflow run menu, the input dataset labels are no longer shown (this can also be observed on usegalaxy.org):

![image](https://cloud.githubusercontent.com/assets/2563865/23361403/d1737966-fcf0-11e6-85bf-13350d90f430.png)

Compared to how it looks on 16.10:

![image](https://cloud.githubusercontent.com/assets/2563865/23361448/04ab52f4-fcf1-11e6-8fcf-4f401bd1e62d.png)

P.S. and on dev I'm currently getting the following:

![image](https://cloud.githubusercontent.com/assets/2563865/23361568/a19f1262-fcf1-11e6-8e55-bea38cca3e6f.png)

**Comment by guerler** [comment]
In dev this has been fixed with #3644. I am looking now into release.
