### ISSUE TITLE
Workflows queuing (scheduler?) stops working.

### ISSUE THREAD

**Issue by ieguinoa** [galaxyproject/galaxy#3677]
Hi all,

I'm experiencing a problem when running workflows. Everything was working ok about 2 weeks ago when we first launched the server but after a few days (no changes in the server whatsoever) the launching of workflows runs stopped working. The invocation works fine, it shows the green box on top with: 'Successfully invoked workflow....' but the associated jobs are not shown in the history, not being scheduled for running, and not even created.  

What I see in the log is:
galaxy.workflow.run_request INFO 2017-02-28 11:25:25,741 Creating a step_state for step.id 3
galaxy.workflow.run_request INFO 2017-02-28 11:25:25,742 Creating a step_state for step.id 5
galaxy.workflow.run_request INFO 2017-02-28 11:25:25,742 Creating a step_state for step.id 4
galaxy.workflow.run_request INFO 2017-02-28 11:25:25,742 Creating a step_state for step.id 1
galaxy.workflow.run_request INFO 2017-02-28 11:25:25,743 Creating a step_state for step.id 2

....but then nothing.

The most relevant thing is that, if I restart the server, all the jobs for the workflows that were invoked are now automatically created and queued as normal. Also, after restart I'm able to run workflows and it works perfectly normal. Of course, after some time (few days?) it just stops working again.

I'm using version 16.10.  We also have a test server with the same setup, I will upgrade that server to 17.01 and try to see if the same problem arises (hard to tell, as the problem is hard to replicate).

Thanks in advance.

**Comment by mblue9** [comment]
I just experienced something similar to this with current 17.09 `087537a`. 

>The invocation works fine, it shows the green box on top with: 'Successfully invoked workflow....' but the associated jobs are not shown in the history, not being scheduled for running, and not even created.

I started a workflow and also got this nice green indication that told me the workflow was successfully invoked but then Nothing... no jobs and nothing obvious in the logs.

Then I found this issue and this restart of the server also fixed it for me (thanks @ieguinoa!!) I can now run the workflow. But it also kicked off an explosion of jobs that had been trapped somewhere. Pretty weird.

**Comment by mblue9** [comment]
Just to update - this workflow submission weirdness I experienced yesterday may have been the result of a brief power outage that affected part of our cluster.

We'd also just updated to 17.09 `087537a` from 17.09 `24da84a` but I had been able to run a few workflows with `087537a` before this odd behaviour started happening. So am thinking maybe the power outage disrupted something in the SLURM job scheduling and caused this.

**Comment by bgruening** [comment]
@jmchilton any idea here. I get reports from Docker users that this is happening quiet a lot with collection enabled workflows.

**Comment by mvdbeek** [comment]
A workflow where this happens reproducibly would probably be very helpful.

**Comment by mmiladi** [comment]
One issue that i am aware of: Marking optional tool outputs as the output of workflow, i.e. star them in wf editor, causes immature termination of the wf run. The solution would be to un-star all optional and not required outputs.

**Comment by ieguinoa** [comment]
I wish I could help with this but as randomly as it appeared it also disappeared, or at least I haven't experienced it in a while. I did updated Galaxy with each release but not sure where it was fixed or even if it was fixed at all.

**Comment by Tomnl** [comment]
We are experiencing the same problem with our Galaxy server i.e.

> The invocation works fine, it shows the green box on top with:  'Successfully invoked workflow....' but the associated jobs are not shown in the history, not being scheduled for running, and not even created.

And the only way to get the workflows to run again as normal is to restart the server. 

We do have a lot of workflows that use data collection so perhaps that is the source of the problem.

@ieguinoa  what version of Galaxy are you using?  (We are still having the problem in version 17.09)


@RJMW

**Comment by ieguinoa** [comment]
We are using Galaxy 17.09 and as of now the problem still persists. It's really hard to figure out a way to reproduce it, only thing that always repeats is that by just restarting the server the called workflows with all the steps are automatically invoked correctly.

**Comment by pcm32** [comment]
I see the same problem on our Galaxy-Kubernetes setup, on long term running instances, after some weeks of running. I think that we see it with both collection related workflows and non-collection workflows. At restart, lots of jobs get scheduled. Same behaviour, exactly as described above. I'm relieved that this is not due to our setup, but still not an ideal behaviour. Very difficult to reproduce.

**Comment by pcm32** [comment]
I have seen it mostly on 17.05, but probably on 17.09 as well.

**Comment by mvdbeek** [comment]
Generally speaking it's helpful to dump the stack of the stuck handler using `py-spy dump --pid <pid of the workflow handler / job handler>`, but it seems this hasn't been much of an issue lately. It should become even less of a problem with the switch to db-skip-locked or transaction-isolation that will become the default handler assignment mechanism in 21.05.
