### ISSUE TITLE
Tools that are Manually added don't appear in Galaxy 

### ISSUE THREAD

**Issue by CicoZhang** [galaxyproject/galaxy#3682]
I am using the release 16.10 locally (git). I have manually added some tools and then edited tool_conf.xml. After restarting Galaxy, the tools still don't appear. 

However, I added the tools into Galaxy docker container, it works. 

Are there any special settings that I should be aware of?

**Comment by nsoranzo** [comment]
Check the Galaxy logs when the server is started, tools are loaded in the order specified in `tool_conf.xml`, so an error should easy to find.

**Comment by CicoZhang** [comment]
@nsoranzo  Could you please how to read the log of Galaxy? I didn't find a document that shows how to get the log of Galaxy. :)

**Comment by martenson** [comment]
@CicoZhang By default Galaxy logs into the console it is run from.

**Comment by CicoZhang** [comment]
Thank you, @martenson  I notice there are a few errors, which are not only about my added tools.

galaxy.tools.toolbox.base ERROR 2017-03-01 15:58:06,912 Error reading tool configuration file from path: extract/liftOver_wrapper.xml
galaxy.tools.toolbox.base ERROR 2017-03-01 15:58:07,497 Error reading tool configuration file from path: evolution/codingSnps.xml
galaxy.tools.toolbox.base ERROR 2017-03-01 15:58:07,499 Error reading tool configuration file from path: evolution/add_scores.xml
galaxy.tools.toolbox.base ERROR 2017-03-01 15:58:07,504 Error reading tool configuration file from path: phenotype_association/sift.xml
galaxy.tools.toolbox.base ERROR 2017-03-01 15:58:07,564 Error reading tool configuration file from path: galax-circos-tool/circgraph.xml  (this one is added by me)

**Comment by martenson** [comment]
I would make sure the files are present at the given path and as a next step validate the XML itself. Ideally using `planemo lint` command from [Planemo utilities](https://planemo.readthedocs.org)

**Comment by CicoZhang** [comment]
I use this tool. https://github.com/TAMU-CPT/galaxy-circos-tool 

I have installed it successfully once in a Galaxy container.

Now I cannot reproduce the success.

**Comment by jmchilton** [comment]
Should "galax-circos-tool" be "galaxy-circos-tool" in your config file?

**Comment by CicoZhang** [comment]
@jmchilton That is it!

Thank you for everyone's help.
