### ISSUE TITLE
Team focus for 17.05

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#3687]
Areas of focus for the next release. Please review and add. The goal is to see progress on these. If there are blockers - these need to be discussed. 

@martenson  

 - API install
 - Installing missing tools from workflow
 - Admin JS
 - improve libraries a bit

@blankenberg 

 - Metagenomics
 - Collection operations

@natefoo 

 - swarm
 - admin docs
 - job feedback
 - jetstream scaling

@jmchilton 

 - upload datasets to collections directly ***
 - CWL stage 1 from the GA4GH challenge
 - more collection operations
 - Rerunning a failed dataset collection element does substitute the
failed element #2235
 - rerunning entire collection

@jennaj 

 - hub clean up
 - testing new and existing tools (with @davebx) 
 - biostar

@davebx 

 - API install with a cart system
 - Main tool updates and maintenance until automated (with @jennaj) 
 - Tool upgrades

@NickSto 

 - du novo

@guerler

 - dataset tag, propagation and filtering with @dannon
 - assistance if needed with the composite uploader @jmchilton is working on
 - new visualization support for @anup, @bgruening

@dannon 

- workflow invocation rendering in the history
- tag propagation, display, and filtering with @guerler 
- ObjectStore refactoring and improvements for S3 with @vjalili
- hub launch
- time permitting, tours

@afgane 

- Explore containerized Galaxy deployment
- Scaling on Jetstream
- Regional clone(s) of Galaxy Main

@moheydarian 

- Ggplot2 wrappers ready for Main
- Test/try out UI features and tools mentioned above as needed 

@vjalili

- Implementing improved caching for ObjectStore
- Authentication/authorization ObjectStore enhancements for per-user storage on Cloud providers

**Comment by MoHeydarian** [comment]
@moheydarian 
- Ggplot2 wrappers ready for Main
- Test/try out UI features and tools mentioned above as needed

**Comment by martenson** [comment]
xref: https://github.com/galaxyproject/galaxy/issues/1928

**Comment by jmchilton** [comment]
That release has passed so I'm closing this issue. It is possible we didn't quite finish all of this - but I see a couple bullets we made progress on - good job all!
