### ISSUE TITLE
Write converter tests.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3693]
We could add ``<test>`` tags and add them to ``-framework`` tests or hand craft API tests for them (see test/api/test_tools.py for example tool tests) - either approach would be fine.

**Comment by mvdbeek** [comment]
I think I would prefer adding regular `<test>` tags. Adding those tags would be a nice thing we could propose for beginners to do during the GCC hackathon.

**Comment by mvdbeek** [comment]
I think most converters have tests now. If not, just add them like we would do for any other tool. They will be tested with https://github.com/galaxyproject/galaxy/blob/dev/.github/workflows/converter_tests.yaml
