### ISSUE TITLE
Inconsistent and Unhelpful uploaded dataset names

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#3695]
This is a follow up to https://github.com/galaxyproject/galaxy/pull/3674.

Problems:
 - Inconsistency: Upload Name is set after the job completes, so if a tool is queued for run, and that tool uses the name of input dataset as part of it's name, it will be different than if the tool was executed after the upload job completed.
 - The 'easy' way of moving datasets between Galaxy instances loses all the important information. Where a dataset may have previously been called `http://asdf.bx.psu.edu/datasets/badfcf2cda375bda/display?to_ext=xml` it will now be called simply  `display?to_ext=xml`. If I want to copy over even just two files, they can no longer be tracked back.

**Comment by nekrut** [comment]
Yes, I have not thought of this, but showing the whole path is the history is still crazy

**Comment by nsoranzo** [comment]
Maybe the full URL can be automatically copied as the dataset description (i.e. "Info" when clicking on the pencil icon), which is normally empty for datasets uploaded in this way.

**Comment by blankenberg** [comment]
We could also make use of the filename content headers being returned by external webserver. In the case of this Dataset in Galaxy it would be something like `Galaxy4-[NCBI_EFetch_on_data_3].xml`

**Comment by martenson** [comment]
This change has been reverted
