### ISSUE TITLE
BUG: Workflow input names no longer visible in "run workflow" form

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#3700]
When running a workflow, the user defined names for inputs are not visible on the form. All inputs are simply `#:input dataset`.

**Comment by nsoranzo** [comment]
What Galaxy release and commit? I think this is a duplicate of the recently fixed issue https://github.com/galaxyproject/galaxy/issues/3672 .

**Comment by guerler** [comment]
Has #3681 fixed this?

**Comment by lparsons** [comment]
This was on `release_17.01`, not sure exactly which commit. I'm updating to the latest `release_17.01` now and will let you know if it's resolved.

**Comment by lparsons** [comment]
This seems to be fixed in the latest `release_17.01`, thanks all!
