### ISSUE TITLE
DEXseq tools have dependencies issues at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3709]
Error

> Detailed Job Information
> 
> Job environment and execution information is available at the job Info Page.
> Job ID	X (X)
> Tool ID	toolshed.g2.bx.psu.edu/repos/iuc/dexseq/dexseq_count/1.20.1
> Tool Version	1.20.1
> Job PID or DRM id	X.roundup
> Job Tool Version	
> Job Execution and Failure Information
> 
> Command Line
> 
> dexseq_prepare_annotation.py -r yes '/galaxy-repl/main/files/X/X/dataset_X.dat' '/galaxy-repl/main/files/X/X/dataset_X.dat'
>
> stderr
> 
> Fatal error: Exit code 127 ()
> /galaxy-repl/main/jobdir/X/X/X/tool_script.sh: line 9: dexseq_prepare_annotation.py: command not found

**Comment by jennaj** [comment]
Primary tool **DEXSeq** may also have the problem, but since the upstream tool is non-functional, it cannot be tested on Main

**Comment by davebx** [comment]
@jennaj this should now be resolved on main

**Comment by davebx** [comment]
History with successful DEXseq-count jobs: https://usegalaxy.org/u/dave-b/h/dexseq

**Comment by jennaj** [comment]
@davebx The other tool from the package **DEXseq 1.20.1** has the same dependency problem, so am reopening the ticket.

toolshed.g2.bx.psu.edu/repos/iuc/dexseq/dexseq/1.20.1

```
Fatal error: An undefined error occured, please check your input carefully and contact your administrator.
Error in library("DEXSeq") : there is no package called 'DEXSeq'
```

The typo in the error message should also be corrected ("occured" > "occurred") but that will be in another ticket.

**Comment by davebx** [comment]
There is now a package called 'DEXSeq' for the other tool as well.

**Comment by jennaj** [comment]
Dependency issue resolved, thanks!
