### ISSUE TITLE
the step's uuid for one workflow will change?

### ISSUE THREAD

**Issue by lucky-nj** [galaxyproject/galaxy#3712]
when i changed the layout of workflow,i get the step's uuid by bioblend,i found the uuid will change to another.

```
from bioblend import galaxy
gi=galaxy.GalaxyInstance(url=url,key=key)
workflow=gi.workflows.export_workflow_json(workflow_id=workflow_id)
for k in workflow['steps']:
    print workflow['steps'][k]['uuid']
```

**Comment by hexylena** [comment]
Hi @Lucky-lai, unfortunately this cannot easily be fixed. Maybe you can use a different method to identify the tools or inputs that you need such as giving tool outputs an easily identified name, or searching based on tool ID?
