### ISSUE TITLE
Where are tools installed from tool shed store?

### ISSUE THREAD

**Issue by CicoZhang** [galaxyproject/galaxy#3726]
For the tool manually installed, I just simply place the files in the directory 'tools'; how about the tools installed from tool shed? Where are they (xml files, scripts) stored? 

For example, I installed DEseq2 from tool shed, where is the xml wrapper stored locally?

**Comment by martenson** [comment]
The tool entries are in config/shed_tool_conf.xml, the repositories
themselves are in folder specified at the start of the mentioned
configuration. The dependencies (if any) are specified by
tool_dependency_dir = database/dependencies in galaxy.ini.

Martin

**Comment by CicoZhang** [comment]
@martenson  Thank you very much. I find it!

I find the code in that config file:`<toolbox tool_path="../shed_tools">`, the config file is in the directory `config`, I had thought `shed_tools`should be parallel with `config`, but actually with the level above `galaxy-central`.
