### ISSUE TITLE
Tool 'Filter' filters NA

### ISSUE THREAD

**Issue by CicoZhang** [galaxyproject/galaxy#3727]
How to use the embedded tool 'filter' to filter the data by one of its columns whose value is not NA. How to write the rule here? 

![image](https://cloud.githubusercontent.com/assets/11710225/23717932/0eccad4a-0436-11e7-9a8f-6d1f2c26f544.png)

**Comment by MoHeydarian** [comment]
These types of questions are generally posted to the [Galaxy Biostars page](https://biostar.usegalaxy.org/), where similar questions are asked, answered, and logged for the user community to reference. 

To remove rows with 'NA' in first column, you would use:

c1!='NA'

If this answers your question, please close this issue (or let us know it worked and we can close the issue). 

Thanks for using Galaxy!

**Comment by CicoZhang** [comment]
To test whether it works, actually I have used `c1=='NA'` to show the rows with NAs, it shows nothing. Then I have to download the data file and filter it using Pandas. 

Thank you for letting me know that. Actually, I didn't know where to pose the question, since I didn't Google anything helpful. I'll do it next time. :-)

**Comment by bgruening** [comment]
@MoHeydarian do you mind to add it to: https://github.com/bgruening/galaxy-tricks/blob/master/README.md ?
