### ISSUE TITLE
Boring documentation and unconstructive rant

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#3735]
This is a huge issue. I just hate how well documented the code is (sooo awsome... I never find any projects out there in the community about this) but since most of the documentation is in the readthedocs stuff, I have to spend so much time as an admin browsing through low-level source code documentation. :( 

I got stuff to do, ladies and gentlemen. Is there any wiki, jira, or something (Trello is blocked by most corporate IT) where I can post some utility functions/scripts and/or scenarios? Also, shouldn't you have a donation form somewhere? FFS. Take my money you elitist ivory tower fools.

Anyway, I am looking for a way to automate tool installation in my Galaxy server, such that someone runs a command similar to below to install tests, scripts, and configuration xml into the Galaxy environment.

```javascript
galaxy install /path/to/my/tool_repo // Install a tool (unless it already exists) into Galaxy, check if the server can be restarted (jobs etc.), and restart the server's shell script.
galaxy update /path/to/my/tool_repo // Push/pull a submodule's updates into Galaxy
```

**Comment by martenson** [comment]
I am unclear on what your question is. Hopefully this will help:

There is an Ansible [playbook](https://github.com/afgane/galaxy-tools-playbook) that will install tools into Galaxy using the API.

Admin & Dev documentation is currently under heavy review and we are on a path towards unification at https://docs.galaxyproject.org (built from galaxy repo sources in `doc/src/`).

Alternatively we have more user facing docs at https://new.galaxyproject.org written in markdown and gathered in this [repo](https://github.com/galaxyproject/galaxy-hub). This ~~will soon replace~~ already replaced https://galaxyproject.org

**Comment by MatthewRalston** [comment]
I like the Ansible playbook! It seems like that only works for tools in a ToolShed. I like the toolshed concept a lot! I can't use it in my company though and I don't know how to make one. How do I make my own toolshed server?

I also really like the new documentation. I'll try to contribute some pull requests! Thank you.

I am still unsure about how to check how many jobs are running (total, not as an indivudal user) and their status from the REST API (it wasn't in bioblend)?

**Comment by MatthewRalston** [comment]
After reviewing the documentation, it seems like there isn't a REST API component exposed that would allow admins to list the number of jobs currently running. Something like this, when coupled to an admin's API key, could allow other instances and/or applications to monitor load on a particular cluster. Also, it could allow admins to automate things like server restarts (by waiting until the queue is clear before restarting).

Restarting the server via the REST API doesn't make much sense in terms of the application structure, but it would make an interesting feature nonetheless.

**Comment by martenson** [comment]
@MatthewRalston one approach to obtaining this information would be to query the DB for jobs in `running` state or communicate with your job schedulers.
