### ISSUE TITLE
Drop google as an openID provider

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#3741]
deprecated 2015: https://developers.google.com/identity/protocols/OpenID2

Strip from UI and documentation

Other ID providers need to be tested to ensure all working OK

Found by @vjalili

**Comment by martenson** [comment]
This illustrates just how used the feature was/is :)

**Comment by VJalili** [comment]
Yahoo, AOL, and Launchpad OpenID connections are working fine. 
But I was not able to test Genomespace. There is some information on [this page](http://www.genomespace.org/support/guides/tool-guide/sections/galaxy-GS-capabilities), but I think it works for _how to login to Galaxy from genomespace_ 

It could be useful if user is hinted where to find OpenID url for each provider. Maybe adding following information to [OpenID manage](https://usegalaxy.org/user/openid_manage?use_panels=True) page would help. 

- Yahoo OpenID URL: 
  1. Go to: http://openid.yahoo.com
  2. Login if required
  3. The OpenID URL is generated, and highlighted in the center of the page. 
- AOL: openid.aol.com/your_username_on_aol
- Launchpad: https://launchpad.net/~your_username_on_launchpad

**Comment by blankenberg** [comment]
GenomeSpace openID worked well last time I tried it, ~2 weeks ago.

**Comment by martenson** [comment]
This has been done, see https://github.com/galaxyproject/galaxy/pulls?q=is%3Apr+openid+is%3Aclosed
