### ISSUE TITLE
Creating a custom build using a .len file triggers an error

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#375]
Description is in this biostars post. Replicated on Main by jen. To replicate as well, just use the example data. Fails for both a browsed/loaded len file or for one that is pasted in.

https://biostar.usegalaxy.org/p/12710/#12740

**Comment by jennaj** [comment]
This still fails on Main. Has been a while now. Error message:

objectstore, _call_method failed: get_filename on , kwargs: {}

**Comment by blankenberg** [comment]
This PR should fix this issue: https://github.com/galaxyproject/galaxy/pull/475

**Comment by dannon** [comment]
Merged #475, closing.
