### ISSUE TITLE
shed_tool_conf.xml update on tool uninstallation

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#3761]
When a tool is uninstalled in galaxy the shed_tool_conf.xml is not updated. 

This leads to error messages during startup: 

galaxy.tools.toolbox.base ERROR 2017-03-14 11:15:17,605 Error reading tool from path: toolshed.g2.bx.psu.edu/repos/devteam/bwa/53646aaaafef/bwa/bwa.xml
Traceback (most recent call last):
  File "/home/berntm/galaxy/lib/galaxy/tools/toolbox/base.py", line 560, in _load_tool_tag_set
    tool.tool_shed = tool_shed_repository.tool_shed
AttributeError: 'NoneType' object has no attribute 'tool_shed'

As quick fix I edited the xml file manually.

**Comment by mvdbeek** [comment]
I'll look into this, but just to exclude a bunch of possibilities: 
You did uninstall this through the admin panel, right?
Did you check the 'remove from disk' option?
Are you using the run.sh method to start galaxy or do you have a uwsgi setup or multiple paste processes?

**Comment by bernt-matthias** [comment]
Yes I uninstalled through the admin panel. 

I'm not entirely sure if I clicked the 'remove from disk' option? I just played around with both possibilities. And both worked without leading to an error. 

I'm using the run.sh method. 

So I can't reproduce the error. The odd thing is that the xml file mentioned in the error is present. 

Btw. In shed_tool_conf.xml the toolbox tool_path is per default configured as ../shed_tools, i.e. it is installed outside of the main galaxy directory. Is this intended?

**Comment by nsoranzo** [comment]
That happened to me when sharing the `shed_tools/` directory with multiple Galaxy instances. For example, if 2 Galaxy instances are installed in `SOME_DIR/galaxy1/` and `SOME_DIR/galaxy2/` , then by default, both will install tools in `SOME_DIR/shed_tools/` . So if you uninstall a tool in `galaxy1`, the error will appear in `galaxy2`. The default directory can be changed by modifying this line:
```
<toolbox tool_path="../shed_tools">
```
in `config/shed_tool_conf.xml` .
