### ISSUE TITLE
Ensure that similarly used objects have unique ids client-wide.

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#3787]
A bug unearthed in https://github.com/galaxyproject/galaxy/pull/3559 points to some issues we might have with id handling. There a library was populated with datasets from a collection that had the same ID as one of the datasets inside. Given how BBone collection works (enforces uniqueness on it) it treats them as one object and discards one.

There were some hints that history already uses some solution to this, maybe based on `type_id` property of hd(c)a.

The solution to this needs to be system-wide as imports/exports will expect same dogma.

tagging people that were in the gitter debate: @jmchilton @dannon @mvdbeek

**Comment by hexylena** [comment]
Is this still an issue? Will it be fixed in the history rewrite or is it already better with Vue stuff?

**Comment by martenson** [comment]
I believe this is still an issue, however I did not review the rewrite, it should probably fix it.

**Comment by hexylena** [comment]
Cool :+1:

xref #8441

**Comment by martenson** [comment]
I think we should verify though.

**Comment by mvdbeek** [comment]
It's not a problem anymore with vue, and I think we can use type hints on the particular entity ids to avoid accidentally using the wrong id.
