### ISSUE TITLE
Enable Read The Docs webhook

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#379]
From http://read-the-docs.readthedocs.org/en/latest/webhooks.html :

"We have support for hitting a URL whenever you commit to your project and we will try and rebuild your docs. This only rebuilds them if something has changed, so it is cheap on the server side. As anyone who has worked with push knows, pushing a doc update to your repo and watching it get updated within seconds is an awesome feeling."

Instructions on how to enable the GitHub webhook are on the same page.

**Comment by hexylena** [comment]
+1

man. 22. jun. 2015, 09.11 skrev Nicola Soranzo notifications@github.com:

**Comment by martenson** [comment]
done

**Comment by martenson** [comment]
didn't want to close, we should wait and see how it works :)

**Comment by nsoranzo** [comment]
Maybe also add a badge to README.rst ?

``` rst
.. image:: https://readthedocs.org/projects/galaxy/badge/?version=master
:target: https://readthedocs.org/projects/galaxy/?badge=master
:alt: Documentation Status
```

**Comment by hexylena** [comment]
Maybe add `latest` instead? After all the travis build points to `:dev`

``` rst
.. image:: https://travis-ci.org/galaxyproject/galaxy.svg?branch=dev
    :target: https://travis-ci.org/galaxyproject/galaxy
```

**Comment by nsoranzo** [comment]
@erasche No problem for me.

**Comment by martenson** [comment]
@nsoranzo sounds good, wanna open PR?
@erasche I think the docs should point to master; devs will find the latest themselves

**Comment by hexylena** [comment]
@martenson I just want consistency between badges. I'm pretty ambivalent to which points where. :)

**Comment by nsoranzo** [comment]
Should the target URL be the suggested https://readthedocs.org/projects/galaxy/?badge=master or http://galaxy.readthedocs.org/en/master/ ?

**Comment by hexylena** [comment]
The second.

man. 22. jun. 2015 kl. 11.22 skrev Nicola Soranzo <notifications@github.com

**Comment by martenson** [comment]
@erasche travis for master and docs for dev are less informative than their counterparts -> does that address your consistency mindset? :)

**Comment by hexylena** [comment]
@martenson sigh, I suppose. If you really feel that they should point to different places, I won't -1 it. 

Just seems awful strange to me. If you want build status for latest, why wouldn't you want the documentation for the same? 

Also why do you say "docs for dev [is] less informative than [its] counterpart"?

**Comment by jmchilton** [comment]
We don't recommend people run against dev - so if there is some problem we don't care to point them at dev docs. If the docs were more about formal code documentation - this might be different - but I don't think that is our target use case with the badge.

Put another way - 3/4 badges are for deployers (or people wearing that :tophat:) - the Travis badge is different since it is for developers (or people wearing that :tophat:).

**Comment by hexylena** [comment]
Okay, that rationale makes sense.

**Comment by nsoranzo** [comment]
@martenson I'm not sure the webhook is working, is it supposed to rebuild at each commit? The last build I see is one I accidentally started ~2 hours ago.

**Comment by martenson** [comment]
GH reports the service is running and that deliveries are succesfull. No idea why readthedocs ignores it.

**Comment by nsoranzo** [comment]
@martenson Maybe something needs to be done on the https://readthedocs.org/projects/galaxy/ side?

**Comment by nsoranzo** [comment]
But I see 3 new doc builds, so maybe there is just a big delay (long queue?).

**Comment by martenson** [comment]
I looked around and googled but did not find anything. I would give it some
time.

**Comment by nsoranzo** [comment]
No new build for the last 37 hours, while for BioBlend commits is working immediately.

**Comment by martenson** [comment]
No idea why this is not triggering.

**Comment by nsoranzo** [comment]
@martenson I've created a personal nsoranzo_galaxy.readthedocs.org and I think I've found the trick: the Versions in RTD should be 'master' and 'dev' (not 'stable', 'latest', 'master') with 'master' still the default version.

**Comment by martenson** [comment]
This probably means that readthedocs will build only the branch that is being pushed to and we are missing 'dev' at readthedocs and pushing only there so it never meets.
I made `dev` version active on readthedocs to test this.

**Comment by martenson** [comment]
merge of https://github.com/galaxyproject/galaxy/pull/406 to `dev` did not trigger the build :/

**Comment by hexylena** [comment]
We're now building our own, so closing this.

**Comment by martenson** [comment]
sadly building :/

**Comment by hexylena** [comment]
![](http://memecrunch.com/meme/1BPQQ/sad-doge/image.png?w=200&c=1)

But I'm happy with less reliance on third parties

**Comment by natefoo** [comment]
> But I'm happy with less reliance on third parties

Posted on Github. ;D
