### ISSUE TITLE
"Get repository updates" fails to update in memory version of Tool

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#3813]
This is a regression.

- In admin interface update a tool repository, without version change
- Tool on disk is updated.
- Tool in memory is not, the old form is displayed and the old tool logic (cmdline, configfiles, etc) is used.
- Current Workaround: You can manually click 'Reload Tool XML' in the tool interface as an admin to fix the problem. (or restart Galaxy)

**Comment by mvdbeek** [comment]
Xref https://github.com/galaxyproject/galaxy/issues/3298

**Comment by nsoranzo** [comment]
Duplicate of #3298.
