### ISSUE TITLE
Display bigWig datasets in IGV

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#3815]
At present Galaxy (main) is unaware that bigWig files can be displayed at IGV. This should be enabled.

![screenshot from 2017-03-25 14-17-08](https://cloud.githubusercontent.com/assets/4291636/24324930/c743af4a-1165-11e7-8f6e-365fd3ee4767.png)

**Comment by blankenberg** [comment]
Should be fixed with https://github.com/galaxyproject/galaxy/pull/3828 after update. If not, the display is missing from the datatypes conf for bigwig:

```
    <datatype extension="bigwig" type="galaxy.datatypes.binary:BigWig" mimetype="application/octet-stream" display_in_upload="true">
      <display file="ucsc/bigwig.xml" />
      <display file="igb/bigwig.xml" />
      <display file="igv/bigwig.xml" />
    </datatype>
```

ping @natefoo

**Comment by nekrut** [comment]
:+1:
