### ISSUE TITLE
Enact procedure to backout of quickly merged PRs

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#382]
Merging PRs quickly keeps us moving forward fast - but could potentially be abused. Rather than imposing a minimum wait time @jxtx had the idea that a -1 could force a backout and review after the fact.
- What is a reasonable amount of time for that - 72 hours?
- Is anyone going to object to this?
- Anything else to think about before composing this procedures PR.

**Comment by hexylena** [comment]
+1

**Comment by martenson** [comment]
Why is there 'quickly' in the PR title? Why not 'every'?

**Comment by jmchilton** [comment]
I was imagine that if we opt for 72 hours for instance - it would be from the push push of the last commit - not from the time the PR was merged. If a clean PR has been opened for 3 weeks and then is merged - I don't think a -1 should allow backout.

**Comment by martenson** [comment]
ay, sorry I was reading it as backout `quickly merged PRs` instead of `backout quickly` merged PRs

edit: no I am still confused, I think I will leave this lawyer talk to you guys

**Comment by jmchilton** [comment]
Ah - sure. Updated title with betterer grammar.
