### ISSUE TITLE
Importing a workflow does not add UUIDs to steps

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#3845]
Steps to reproduce on 17.01

- new workflow
- add some steps
- import all steps from another workflow into this one (the copy button)
- export as json
- uuids for imported steps are None while created steps have non-None UUIDs.

**Comment by jmchilton** [comment]
There is definitely a bug here - I'm looking into it.

**Comment by hexylena** [comment]
awesome, thanks @jmchilton. you rock.
