### ISSUE TITLE
Potentially delaying 15.07 Freeze Date until after GCC?

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#385]
Today was intended to be the freeze date for the 15.07 release.  I'd like to open this issue to discuss freezing _after_ GCC instead, to allow for contributions from the Hackathon and other things that may arise in the next couple weeks.  My guess is also that people will have less time than ever in the next three weeks to actually test and fix this release, so delaying would benefit that effort as well.

**Comment by bgruening** [comment]
:+1: for delaying.

**Comment by jmchilton** [comment]
:+1: for delaying - my rationale remains the same as in https://github.com/galaxyproject/galaxy/pull/269.

**Comment by hexylena** [comment]
:+1:

**Comment by davebx** [comment]
I agree with @dannon's reasoning, :+1:

**Comment by martenson** [comment]
I am sad that this has been brought up now and not 20 days ago given that no reasons here appeared in the past three weeks. I won't oppose though.

**Comment by dannon** [comment]
Seems like this is supported.  I'll open a PR to update the projected timeline.

**Comment by dannon** [comment]
Closing the issue, we'll resolve it one way or another in #386.  Thanks for chiming in, everyone!
