### ISSUE TITLE
Expand API Test Coverage

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3853]
## Overview

This issue is meant to be a long running issue that tracks API tests that need to be written. While this card and our testing in general will never be exhaustive, it would be ideal that everytime a new API or a new API function is added - this card is amended unless that API extension/modification comes with its own tests.

## How To Run API Tests

If you haven't contributed to the Galaxy core project before, start by forking and cloning Galaxy. More information about cloning Galaxy and creating pull requests can be found in [CONTRIBUTING.md](https://github.com/galaxyproject/galaxy/blob/dev/CONTRIBUTING.md).

From Galaxy's root directory, just make sure you can start Galaxy. This verifies Galaxy has required dependencies and stuff needed to run API tests.

```
$ ./run.sh
Activating virtualenv at .venv
Requirement already satisfied: pip>=8.1 in ./.venv/lib/python2.7/site-packages
Requirement already satisfied: bx-python==0.7.3 in ./.venv/lib/python2.7/site-packages (from -r requirements.txt (line 2))
...
galaxy.webapps.galaxy.buildapp DEBUG 2017-03-31 09:44:20,453 Prior to webapp return, Galaxy thread <GalaxyQueueWorker(Thread-1, started daemon 123145497706496)> is alive.
Starting server in PID 95261.
serving on http://127.0.0.1:8080
```

If that works, hold control and press C to kill Galaxy. Now you should be able to use the ``run_tests.sh`` script to execute API tests. The API tests are located in ``test/api``. 

First start by running ``run_tests.sh -help`` and scan through the extensive help documentation. Every small detail is not important, but pay particular attention to how to run specific tests.

Next run a couple particular tests, here are some easy but still interesting ones:

```
$ ./run_tests.sh -api test/api/test_users.py:UsersApiTestCase.test_update
$ ./run_tests.sh -api test/api/test_datatypes.py
$ ./run_tests.sh -api test/api/test_tools.py:ToolsTestCase.test_run_cat1
```

Verify the tests run properly and try to find the original test definitions in ``test/api``.

The top-level definitions for the actual API controllers used by Galaxy are in [lib/galaxy/webapps/galaxy/api](https://github.com/galaxyproject/galaxy/tree/dev/lib/galaxy/webapps/galaxy/api), but you will likely need to navigate a lot more of Galaxy to debug or extend the API. Likewise a knowledge of how to use Galaxy is probably essential to understand the basic concepts.

More information on the API can be found on the [Galaxy hub](https://galaxyproject.org/develop/api/) and information about the architecture of Galaxy can be found in [this PDF](http://schd.ws/hosted_files/gcc16/56/galaxy_architecture_2016.pdf) on Galaxy Architecture.

## Tests to Write

- [ ] User API endpoint related.
  - [ ] get_password / set_password
  - [ ] get_permissions / set_permissions
  - [ ] get_toolbox_filters / set_toolbox_filters
- [ ] Webhooks - The webhook API endpoints appear to have no tests.
- [ ] Tools 
   - [ ] build - This is a very crucial endpoint for building up tool state but it doesn't really have any tests I don't think. There are tons of tests that should be written to explore different facets of tool state.
   - [ ] all_requirements / requirements
   - [ ] reload / diagnostics - this is probably better tested as an integration test (see ``test/integration`` for examples)
   - [ ] citations
   - [ ] Job re-running - not an endpoint in particular - but the create behaves different ways for re-run I think and it should be test. This would also cover ``JobController.build_for_rerun``.
- [ ] Roles - there appears to be no ``test/api/test_roles.py`` - there probably should be. May want to grep around other tests to verify this isn't being tested elsewhere though.
- [ ] Quotas - there appears to be no tests for the quota API endpoint.
- [ ] Provenance - there appears to be no ``test/api/test_provenance.py`` - there probably should be. May want to grep around other tests to verify this isn't being tested elsewhere though.
- [ ] Metrics - For client metrics
- [ ] Tagging and Annotation - See annotations.py and item_tags.py - I don't think any of this is tested but maybe it is in another test case.
- [ ] Groups - Three separate group controllers - I don't think any have tests.
- [ ] Data libraries. This TODO should be flushed out more, we have an extensive library API and a very small amount of it is tested in ``test/api/test_libraries.py``.
- [ ] genomes.py - I don't think this controller is tested.
- [ ] Anonymous API tests from CasperJS. Galaxy previously had two methods for testing the API - the tests described here and CasperJS tests. We would like to get rid of the CasperJS tests and started to with #3288 but more files are remaining to migrate.
   - [ ] api-anon-history-permission-tests.js
   - [ ] api-anon-history-tests.js
- [ ] In addition to the above existing anonymous API tests - all of Galaxy's functionality that is available to anonymous users should be tested with an anonymous API test.
   - [ ] tool index / details / building 
   - [ ] metrics
   - [ ] Tours
   - [ ] Webhooks
   - [ ] Libraries
   - [ ] Datatypes 
   - [ ] Configuration

**Comment by bgruening** [comment]
Love it! Thanks John! I would also like to see some kind of swagger integration and maybe automatic tests generated from swagger. This would improve testing and documentation.

**Comment by jmchilton** [comment]
Ping @MaxGreil - to continue our conversation from https://github.com/galaxyproject/galaxy/issues/3241#issuecomment-290113870 - I'd take a crack at one of these. I think the easiest thing is probably going to be to test the ``api/tools/<tool_id>/citations`` endpoint by adding a test to ``test/api/test_tools.py``. The test tool test/functional/tools/bibtex.xml has some citations that you can use and you can add a new test tool that expands from a DOI. The requirement related tool tests would also be useful and pretty easy.

The group test tools are probably relatively easy to build basing them off existing user tests - though I could be wrong.

**Comment by MaxGreil** [comment]
@jmchilton thank you for your suggestion for the API tests and your detailed description. I have a look at it and see what I can do.

**Comment by Gasta88** [comment]
Hi, I'm new to this project and I would like to lend a hand to test these APIs.

I'm starting with the top one for `users.py`, but unfortunately I'm not able to import the module `base` from line 5:

```python
import json
from requests import put, get
from base import api
```

How can I find it?

**Comment by jmchilton** [comment]
These are largely done.
