### ISSUE TITLE
FTP upload advice in upload tool

### ISSUE THREAD

**Issue by malloryfreeberg** [galaxyproject/galaxy#3858]
It would be nice if, when a user clicks "Upload file" > "Choose FTP file", there was some helpful information about how to do an FTP transfer or even a link to the FTP transfer Hub page.

A Jetstream-launched 16.07 image has an example command:
<img width="600" alt="screen shot 2017-03-31 at 4 49 40 pm" src="https://cloud.githubusercontent.com/assets/10993501/24569152/d1289486-1632-11e7-9a6b-763a81d9f7e6.png">

But currently Main has no example:
<img width="600" alt="screen shot 2017-03-31 at 4 49 54 pm" src="https://cloud.githubusercontent.com/assets/10993501/24569169/f01f9c54-1632-11e7-88c4-b8748031e5a2.png">

Just a simple example command in that info window like `ftp usegalaxy.org` or a link to the [Hub page](https://galaxyproject.org/ftp-upload//) with information on what FTP is and how to use it would be helpful, I think.

**Comment by dannon** [comment]
The difference here is that jetstream defines 'ftp_upload_site' as 'ftp://blah' whereas usegalaxy reuses {{ galaxy_instance_hostname }}.  I'll tweak this to add teh protocol for usegalaxy.org.

**Comment by malloryfreeberg** [comment]
I'm just wondering what is the easiest and most-straightforward thing to show users who might not know how to use FTP. Pointing to the Hub page, I agree, is probably best. I think the goal is to not have this be a roadblock for users who have files >2GB (which is like every deep sequencing fastq file) but who are less computer-savvy.

**Comment by dannon** [comment]
https://github.com/galaxyproject/usegalaxy-playbook/commit/46a503d82374c0a3cae7427de15f302d6f3bd44d should be a step forward, we can also follow up with the hub stuff.

**Comment by hexylena** [comment]
We now link to hub docs there.
