### ISSUE TITLE
Error: Cannot connect to Galaxy

### ISSUE THREAD

**Issue by dabs17** [galaxyproject/galaxy#3860]
I keep getting the following popup error:

"Cannot connect to Galaxy

Galaxy is currently unreachable. Please try again in a few minutes. Please contact a Galaxy administrator if the problem persists."

I have tried logging out and re-signing in. I reset my internet connection. The error pops up if I try to do anything in my History. I can select any tools from the toolbox, but as soon as I submit a job, the error pops up again.
![galaxy error](https://cloud.githubusercontent.com/assets/10619753/24572142/12d780e8-162b-11e7-806a-5da7704a83e1.PNG)

**Comment by martenson** [comment]
seems solved: https://biostar.usegalaxy.org/p/22422/
