### ISSUE TITLE
Workflow Editor - Can't connect two data collection params within a conditional.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3872]
From @glormph on gitter:

> Hi, I just encountered something funny testing a new tool in a WF
The tool defines some params in a conditional: <conditional name="mzids"> <param name="inputtype" type="select" display="radio"> <option value="single">Single mzIdentML</option> <option value="multi">Multiple mzIdentMLs</option> </param> <when value="single"> <param name="target" type="data" format="mzid" label="Target MSGF+ results" /> <param name="decoy" type="data" format="mzid" label="Decoy MSGF+ results" /> </when> <when value="multi"> <param name="target" type="data_collection" collection_type="list" format="mzid" label="Target MSGF+ results" /> <param name="decoy" type="data_collection" collection_type="list" format="mzid" label="Decoy MSGF+ results" /> </when> </conditional>
> A crap formatting.
> Anyway, when I select "multi" the input params become 2 data_collection param elements of type list
> But, in a workflow, I can only ever use one of them. As soon as I have dragged an output to the input, the other input will not become green again.
Wondering if this was a bug in the WF editor.

**Comment by glormph** [comment]
This is on 17.01, tool code is in https://github.com/galaxyproteomics/tools-galaxyp/blob/master/tools/percolator/percolator_converters.xml

**Comment by glormph** [comment]
Also, it works just fine when trying to pass 2 collections of type `list`. The problem occurs when the collections are of type `list:list`.
