### ISSUE TITLE
Database migration after initial installation slow. 

### ISSUE THREAD

**Issue by sneumann** [galaxyproject/galaxy#3879]
Hi, when installing a new instance of Galaxy, on first invocation 
Galaxy is running the database migration script(s) from 1 -> 2 and 2-> 3 ... 100 and more. 
If you fire-up (and tear down) a Galaxy installation on a regular basis,
this is a significant part (>50%) of the installation time.  
=> Is there a way to either 1) Include roll-up SQL migration 1 -> 100,
or a way to get the final current schema in case of a fresh installation 
to an empty database ? Yours, Steffen

Tags: enhancement

**Comment by nsoranzo** [comment]
[Planemo](https://planemo.readthedocs.io/en/latest/) uses a recent empty SQLite database from https://github.com/jmchilton/galaxy-downloads/

**Comment by sneumann** [comment]
We have PostgreSQL as backend, @pcm32 and @ilveroluca could we do the same ?

**Comment by dannon** [comment]
Last time I looked at this (years ago), the best long term plan was probably to switch to Alembic, but I think it'll be quite a lot of work.  http://alembic.zzzcomputing.com/en/latest/ is the relevant info, and it'd allow for faster migrations.

**Comment by bgruening** [comment]
Hi @sneumann!
We have this running in the compose version of the Galaxy Docker image. Have a look at: https://github.com/bgruening/docker-galaxy-stable/tree/dev/compose
Especially here: https://github.com/bgruening/docker-galaxy-stable/tree/dev/compose/galaxy-postgres

Hope that helps!
Bjoern

**Comment by hexylena** [comment]
This will now be fixed in latest galaxy that does all migrations in one go.

**Comment by martenson** [comment]
@erasche whaaaat 👀

**Comment by hexylena** [comment]
That's what I heard? https://github.com/galaxyproject/galaxy/pull/8300
