### ISSUE TITLE
Cuffmerge fails to display indexed genomes on Main

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#388]
Cuffmerge -> 
Use sequence data :Yes -> 
Choose the source for the reference list: Locally cashed ->
Using reference genome: No options available

In certain cases, the first genome indexed for this tool with show up for a second (hg19), then "No options available" will replace it.

In other cases, "No options available" will display with a spinner at the end of the selection line.

To replicate, just click on the tool and use the path above. If you want to test it with real data, import any RNA-seq history based on hg19 from "Saved Histories" to provide the tool with input. Other histories will work, since hg19 is not the only indexed genome, but this is a simple test.

**Comment by richhogg** [comment]
Has a solution or work-around been found for this?

**Comment by natefoo** [comment]
The location files and data tables look ok. Ping @guerler, could this be a tool form problem?

**Comment by jennaj** [comment]
Just an update: on Main this is still an issue for CuffMerge. A similar issue with Cuffdiff was resolved a few weeks ago. Both tools present with the problem on the training day cloud build. Am testing on the latest cloud build from launch.

**Comment by richhogg** [comment]
The only workaround i found for this was the re-run a previous cuffmerge job where the locally cached sequence data was working and then change the settings so you produce the merged file you want. I hope this helps anyone who may be stuck.

**Comment by guerler** [comment]
Can someone share a history such that I may reproduce the issue and the workaround on main?

**Comment by jennaj** [comment]
Sam, updated, use this one I just shared: https://usegalaxy.org/u/jen-bx-galaxy-edu/h/cuffmerge-test-7-2015

Can use just the cufflinks outputs (datasets 2&3), or also add in the ref annotation (dataset 1).

Option Use Sequence Data -> Yes. hg19 should come up and does not. Or may flash for a few seconds, then go away. Let me know if need more info! jen

**Comment by guerler** [comment]
It seems that multi-select data tool parameters cannot be used as reference to filter data tables: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/parameters/dynamic_options.py#L130. I wonder if this behavior changed in the past or if previous versions of this tool worked differently? This might be somewhat related to https://github.com/galaxyproject/galaxy/issues/445.

**Comment by jennaj** [comment]
I think we should drop the functionality. It is new-ish. So, meaning, stop attempting to interpret the input(s) database metadata and selecting that for the ref genome in the menus. Instead, just let the user do it. 

I know this seems like a helpful thing, but I cannot think of one usage question in the past about this ("How to pick the appropriate ref genome on the tool form?" once at this stage in an analysis). This has been a problem on usegalaxy.org & cloudman for a long time now.

my 2 pence: We should fix now if can. The option to go back and add in the 'pick ref genome based on input(s) database functionality' - correctly - later - is still there if a use case/need arrises.

**Comment by guerler** [comment]
In this case I suggest to remove the corresponding filter from the tool's xml. This would resolve this issue. For the future, we might want to extend the logic and filter the genomes by the common subset between all selected input datasets.

**Comment by jennaj** [comment]
Agree, thanks sam

**Comment by jmchilton** [comment]
Taking a holistic view of the Galaxy eco-system - we (I) put this broken cuffmerge tool out there into the ether that doesn't work in some scenarios and we want Galaxy to work that way and we want the tool to work that way - I would be eager to call filtering not working on a multiple data parameter a bug and push a fix into 15.05 or 15.07 so it lands up on main - this way older versions of that tool work.

I'll work on the fix today - I guess we can continue to debate where it should actually go (dev or a release).
