### ISSUE TITLE
Library upload from path fails with "upstream sent too big header"

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/galaxy#3882]
I'm using @bgruening's docker image, and I try to add a directory with data into galaxy. It contains 20 bam files, totally a couple TB. For that reason, I'm not copying but hoping to create links. When I hit "add" it freezes for a minutes then throws a 403 with the message: 
```
2017/04/05 17:02:21 [error] 793#0: *27 upstream sent too big header while reading response header from upstream, client: 18.111.31.78, server: , request: "POST /library_common/upload_library_dataset HTTP/1.1", upstream: "uwsgi://127.0.0.1:4001", host: "answer.csbi.mit.edu", referrer: "https://answer.csbi.mit.edu/_upload?nginx_redir=/library_common/upload_library_dataset"
```

Any ideas where this error comes from? Is this a known bug in Galaxy or the docker image?

**Comment by martenson** [comment]
It seems you are using the old interface in the `Admin` section, am I right?

**Comment by alexlenail** [comment]
How old is old? I think I'm using 16.10?

**Comment by martenson** [comment]
@zfrenchee there are two interfaces to interact with libraries, one is under Admin menu in the top, other is under Shared Data in the menu. Please the one under shared data. Details here: https://galaxyproject.org/data-libraries

**Comment by alexlenail** [comment]
Thanks @martenson
