### ISSUE TITLE
Batch-download multiple datasets from Galaxy history (Select All)

### ISSUE THREAD

**Issue by AjitPS** [galaxyproject/galaxy#3898]
It may be a useful feature to allow users to multi-select datasets from their **History** via the 'Select All' feature and **_batch-download_**. Currently, users need to individually download files which is tedious for 100's of datasets, unless they _merge_ them (not possible in all cases).

Also posted by @rob123king at https://gitter.im/galaxyproject/Lobby

**Comment by jennaj** [comment]
Duplicate ticket, closing. 

But thank you for the additional information! The developers will see all now that these are linked.
