### ISSUE TITLE
Please add pull policy configuration for Kubernetes Runner

### ISSUE THREAD

**Issue by mwalzer** [galaxyproject/galaxy#3900]
Hi there,

Would it be possible to set the pull policy for tools on the Kubernetes runner? This would allow for some offline usage once images have been pulled initially!

Thanks!

**Comment by pcm32** [comment]
The PR above should provide the functionality that you're after. Will update Galaxy Helm chart and associated container soon to make use of the changes, will let you know!

**Comment by pcm32** [comment]
@mwalzer @jmchilton on my side at least, I think that this issue can be closed, as functionality for this has been added.

**Comment by bgruening** [comment]
Thanks @pcm32!
