### ISSUE TITLE
Multi-threaded job scheduling in workflows.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3903]
Somewhere around 16.01 - I introduced the concept of tool bursting to allow multiple threads to schedule individual jobs from a collection of jobs during tool execution. This seemed to speed up tool submission in some cases - but could be much more powerful when applied to workflows - since each workflow thread could potentially have dedicated scheduling threads - thereby reducing the overhead of actually spinning up and tearing down these threads.

I think the speed up in scheduling large collection workflows would be fairly dramatic as you throw more threads at the problem.

 - [ ] Fix and implement test cases for #2259.
 - [ ] Refactor workflow scheduling manager to allow configuration of specific job creation threads (building on https://github.com/galaxyproject/galaxy/pull/3844) - use these threads when bursting.

**Comment by mvdbeek** [comment]
We've added and removed this in the meantime ... 😆 . I think we'll want to break down expensive steps and schedule them as celery tasks going forward.
