### ISSUE TITLE
Intersect genomic intervals on Main returns empty files

### ISSUE THREAD

**Issue by snuernberg** [galaxyproject/galaxy#3905]
Hi,

somehow the Operate On Genomic Intervals - Intersect the intervals of two data sets doesn't work. Data sets which clearly have overlapping intervals (I checked on UCSC browser) return empty intersect files (green, no error message). I generated narrow peak files from peak calling in galaxy and then tried to intersect those: empty files on 3 technical replicates from a published dataset. Then cut just the first 6 columns and converted into bed with defined attributes: still the same.

Can somebody please check what's going on with that tool?

**Comment by bgruening** [comment]
@snuernberg can you provide test data so we can investigate?

**Comment by snuernberg** [comment]
Sure - this is my history on Galaxy: https://usegalaxy.org/u/atvb2017/h/unnamed-history
I was trying to intersect either of 27, 30, 33 or 44, 45, 47....

**Comment by jennaj** [comment]
Solution at Biostars. In short, the tool required Chip-seq inputs with forward strand assignment, not ambiguous, and this is easily modified within Galaxy. 
https://biostar.usegalaxy.org/p/22510/#22531
