### ISSUE TITLE
Sequences are not currently available for the specified build

### ISSUE THREAD

**Issue by lifepillar** [galaxyproject/galaxy#3908]
Hi,
I have some trouble reproducing the tutorial on [Finding variants in diploid genomes](https://galaxyproject.org/tutorials/var_dip/) in my local instance (release 17.01). This has likely to do with the way I've added the reference sequence. What I've done is download [hg19 assembly](http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/) (chromFA.tar.gz) from UCSC, which has a FASTA file for each chromosome. Then, at *Admin > Local data* I have created a new dbkey called `chr19-hg19` and I've selected `chr19.fa` from my directory on the server (creating a symlink). To be on the safe side, I have indexed the sequence with several data managers: SAM FASTA index, Picard index, TwoBit, and BWA-MEM index.

In the FreeBayes tool, I can select the reference chromosome, but when I click on Execute I get the message in the subject. As far as I understand, the read data in the tutorial refers only to chromosome 19, so I think that it is not necessary to add the whole genome (btw, how do I do that? Do I need to merge all chromosomes into a single multifasta?). What else do I need?

**Comment by mvdbeek** [comment]
Hi @lifepillar,

> In the FreeBayes tool, I can select the reference chromosome, but when I click on Execute I get the message in the subject.

Questions about tool usage are more in the scope of biostars (https://biostar.usegalaxy.org/) or the repository where the tool is being developed, which is https://github.com/galaxyproject/tools-iuc.

That said my best guess is that your bam file does not have the correct database assigned. You can set the database for the bam file using the pencil icon next to the dataset.

> btw, how do I do that? Do I need to merge all chromosomes into a single multifasta?

You can install data_manager_fetch_genome_dbkeys_all_fasta from the toolshed, and then run this datamanager to download the hg19 index directly from UCSC, or from a file in your history.
If you want to prepare these yourself then yes, you have to make a multifasta file out of the individual files.

**Comment by lifepillar** [comment]
>Questions about tool usage are more in the scope of biostars […] or the repository where the tool is being developed […]

My apologies. I am new to the Galaxy ecosystem, still trying to figure out somethings. I'll keep it in mind for future requests.

>my best guess is that your bam file does not have the correct database assigned.

That's it. Thanks!

>If you want to prepare these yourself then yes, you have to make a multifasta file out of the individual files.

Exactly what I needed to know. I have tried to fetch the genome using the data manager, but my test machine has few resources and I got a memory error.

**Comment by mvdbeek** [comment]
No worries, glad it works for you.

**Comment by mvdbeek** [comment]
> Exactly what I needed to know. I have tried to fetch the genome using the data manager, but my test machine has few resources and I got a memory error.

That seems like a bug then (absolutely possible given the latest changes), we would appreciate a bugreport on https://github.com/galaxyproject/tools-iuc/issues
