### ISSUE TITLE
TravisCI: check everything with flake8.

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#391]
Presently the `py27-lint` and `py26-lint` tox environments for TravisCI execute `bash .ci/flake8_wrapper.sh`, which in turn uses [flake8](https://gitlab.com/pycqa/flake8) to check:
- a subset of Python files (listed in `.ci/pep8_sources.txt`) for all errors/warnings (as defined in `setup.cfg`)
- most Python files for a small subset of errors.

The goal is to incrementally extend `.ci/pep8_sources.txt` to include all Python files, so that all future pull requests will be automatically checked with flake8, even the one adding new Python files.

Part of this task can be done at the [GCC2015 Coding Hackathon](http://gcc2015.tsl.ac.uk/Hackathon/).

Update 2016 by John - adding checklist of what remains.
- [x] scripts/api/
- [x] scripts/data_libraries/
- [x] scripts/loc_files/
- [x] scripts/microbes/
- [x] scripts/others/
- [x] scripts/scramble/
- [x] scripts/tool_shed/
- [x] scripts/tools/
- [x] scripts/transfer.py
- [x] tools/data_source/
- [x] tools/filters/
- [x] tools/genomespace/
- [x] tools/meme/
- [x] tools/metag_tools/
- [x] tools/phenotype_association/
- [x] tools/plotting/
- [x] tools/solid_tools/
- [x] tools/sr_assembly/
- [x] tools/sr_mapping/
- [x] tools/validation/
- [x] tools/visualization/

**Comment by hexylena** [comment]
Added a card for you https://trello.com/c/zfiZqCen/8-increase-coverage-of-flake8

**Comment by jmchilton** [comment]
:+1: great goal.

**Comment by hexylena** [comment]
Is this done? The blacklist looks pretty small. https://github.com/galaxyproject/galaxy/blob/dev/.ci/flake8_blacklist.txt

**Comment by jmchilton** [comment]
@nsoranzo is out for a while, but attempting to look at the black list through eagle eyes I can predict he will think all of `tools/` and `scripts/` should be taken off the black list before this is closed. Indeed doing this is probably a prerequisite to Python 3 support (since getting code to lint with Python 3 has been done before testing it with Python 3 in the other projcts - bioblend, planemo, pulsar, etc...).

**Comment by hexylena** [comment]
Ok. Was just browsing through old issues and figured I'd get an update :)

**Comment by jmchilton** [comment]
@erasche Yeah no problem at all, thanks for looking through the issues. I've added a checklist.
