### ISSUE TITLE
Galaxy Scratchpad fixed window sizes

### ISSUE THREAD

**Issue by ThomasWollmann** [galaxyproject/galaxy#3910]
Is it possible to provide an option to freely set the a window size. Currently in scratchpad mode the window snaps to predefined steps.

**Comment by guerler** [comment]
Technically it is possible by changing the cell size at https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/ui/ui-frames.js#L56. Once the cell size has been changed e.g. to the minimum value of 1, the default frame size above should be adjusted and the scripts need to be repacked by running 'make client' in the Galaxy root directory. However this will change the window behavior for all views. Can you provide more details why you are interested in this feature?

**Comment by ThomasWollmann** [comment]
My users complained about the missing freedom when arranging windows. Especially if you want to compare results side by side they struggled arranging their windows how they wanted to.

**Comment by hexylena** [comment]
It seems like we cannot easily implement this as a server config option since it requires a client recompile, but that it is possible to do if certain sites need it. Hope that helps!
