### ISSUE TITLE
Building dataset lists/pairs across multiple history pages not possible

### ISSUE THREAD

**Issue by JenCabral** [galaxyproject/galaxy#3911]
You are unable to build dataset lists or pairs (or list of dataset pairs) from samples across multiple pages in your history. You can select all on each page. When going between the pages, the datasets remain selected but when you choose one of the 3 build options, only the samples selected on the current page are included in that list/pair/list of pairs.

**Comment by mvdbeek** [comment]
The discussion is continuing in #4350, so I'll close this one.
