### ISSUE TITLE
Drag-and-drop does not work on the first dataset

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#3923]
If you are using chrome on linux you cannot drag the first dataset in history. The second drags just fine.

**Comment by guerler** [comment]
I tried to reproduce this but was not succesful so far. Can someone take a look and help to reproduce this, maybe @martenson?

**Comment by dannon** [comment]
I tried this on test.galaxyproject.org using chrome/linux and haven't been able to reproduce it either.  Anything different about that first dataset in the history that you can think of?  Is it on test where I could share/try too?

**Comment by martenson** [comment]
@guerler @dannon I am also unable to reproduce but I remember seeing it on Anton's desktop. Also note that 'first dataset' in here is the bottommost one (was counterintuitive to me).

**Comment by dannon** [comment]
I think we've isolated this to a destructive rendering operation that happens when tagging a dataset with the editor.  Working on a fix.

**Comment by guerler** [comment]
I assume this has been fixed. Please reopen if not.

**Comment by dannon** [comment]
Yep, it was fixed in #4052.
