### ISSUE TITLE
ucsc_tools dependency missing in bioconda

### ISSUE THREAD

**Issue by ieguinoa** [galaxyproject/galaxy#3929]
Hi all,

not sure if at some point there was a big full package in bioconda containing all ucsc tools but right now there is none. There are several tools containing ucsc_tools as requirement so they fail with missing commands errors (like lib/galaxy/datatypes/converters/bed_gff_or_vcf_to_bigwig_converter.xml).
I solved this by just installing ucsc_tools environment, using Galaxy naming convention and the package obtained from mvdbeek's channel.
There is, though, a related topic. In some tools that have dependencies (e.g lib/galaxy/datatypes/converters/bam_to_bigwig_converter.xml) the whole package is set as requirement although only bedGraphToBigWig tool is needed, which can be resolved using bioconda ucsc-bedGraphToBigWig as requirement. What is the suggestion (if any) in these cases? should tools include the specific requirements or the whole package?

thanks in advance!
Ignacio

**Comment by nsoranzo** [comment]
@ieguinoa There's work on a `ucsc_tools` meta-package for Galaxy at https://github.com/galaxyproject/conda-iuc/pull/9 , which is mainly for backward compatibility and is going to include only the packages really used by Galaxy tools and converters.

**Comment by ieguinoa** [comment]
Great! thanks for the information and sorry I didn't find that thread before.

**Comment by nsoranzo** [comment]
`ucsc_tools` 332-1 package from `iuc` Conda channel should include all the necessary binaries.
