### ISSUE TITLE
improve visibility of advanced searching syntax

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#3937]
Applies to histories https://galaxyproject.org/tutorials/histories/#advanced-searching and possibly to the toolpanel too.

One option is to have "?" next to the search box documenting most useful syntax and linking to docs. (@jxtx's idea)

**Comment by assuntad23** [comment]
@martenson The link that is on this ticket for Advanced Search instructions is specific to Histories. Is there a different place where Advanced Search tips can be found for the tool panel?

**Comment by martenson** [comment]
@assuntad23: not yet, the syntax for toolpanel is limited and also has own button, so history search is the main thing to take on

this is being implemented in https://github.com/galaxyproject/galaxy/pull/9213

**Comment by hexylena** [comment]
I think this if fixed with the new advanced searches that have the little drop down icon that helps folks find it.
