### ISSUE TITLE
Scaling Collection Performance - A meta issue

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3939]
The goal is to be able to handle tens of thousands of datasets in a relatively usable manner in the GUI.

 - Fix uploading of large collections
   - Bundle uploads so upload form scales to hundreds or thousands of datasets.
     - https://github.com/galaxyproject/galaxy/issues/1567
     - https://github.com/galaxyproject/galaxy/issues/1090
   - Rework the collection builder for scale - redo the paired
collection builder to try different patterns and be more aggressive
with its initial guess if it can match everything (and not offer an
initial guess if it cannot match anything).
 - Add pagination and search to collection view within history panel.
   - https://github.com/galaxyproject/galaxy/issues/3054
 - Scale up tool execution and workflow scheduling.
   - Intra-step recovery of workflow step.
(https://github.com/galaxyproject/galaxy/issues/3883)
   - Multi-threaded job creation during workflow threading
(https://github.com/galaxyproject/galaxy/issues/3903)
   - General database optimizations for scheduling. #4959
   - Optimize memory consumption for workflow scheduling. #5044
 - [x] Fix tool form performance issues - database and datatype matching optimizations. #3865.
 - Increase robustness and ability for user for respond intelligently
to failures:
   - Improve failed job re-submission to include tool indicated
errors. (https://github.com/galaxyproject/galaxy/issues/3320)
   - Allow re-running mapped jobs in the history panel.
   - Allow re-running only failed jobs within mapped jobs in the
history panel (https://github.com/galaxyproject/galaxy/issues/2235)
   - Fix "resume" workflow for the above two fixes.

**Comment by mvdbeek** [comment]
This seems mostly done, and for the next steps we should create a new issue. I'm gonna say we've reached the 10K datasets goal now.
