### ISSUE TITLE
fetch user API key non-destructively

### ISSUE THREAD

**Issue by jvolkening** [galaxyproject/galaxy#3945]
Is there a way (via the REST API) to fetch a regular user's current API key when connected under an admin account. I am able to generate and return a new API key for a user this way, but this clobbers the old one and would be inconvenient if the user is making use of it themselves. My use case is to be able to run workflows on behalf of a user from the admin account.

**Comment by nsoranzo** [comment]
`GET /api/users/<user_id>/api_key/inputs`

**Comment by jvolkening** [comment]
Thanks.
