### ISSUE TITLE
Changing datatype in workflow not working for collections

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#3947]
It looks like changing the datatype in a workflow doesn’t work for collections. I have a collection of tabular files, I run the the `regex_replace` tool over that collection (which produces txt files), and I change the datatype to tabular in the workflow editor. Unfortunately tools that require tabular input will not accept the workflow output, even though the individual elements are tabular now.

[This](https://gist.github.com/mvdbeek/d228a65e4966f0f54d856e3bf15ea7f1) is a simply workflow that demonstrates the problem.

Not sure if this is a bug or if that has never been implemented.

**Comment by jmchilton** [comment]
> Not sure if this is a bug or if that has never been implemented.

I think it is both - I've never implemented a test case for this anyway so I'm not surprised it doesn't work.

**Comment by mvdbeek** [comment]
Done with https://github.com/galaxyproject/galaxy/pull/7480
