### ISSUE TITLE
Jupyter dataset upload bug

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#3974]
There are two ways to start up Jupyter notebook in Galaxy. Both cases are "dataset centric" meaning that you start the notebook on a particular dataset. However, this dataset is not copied onto Jupyter's docker file system. This can be solved by either actually copying the dataset or allowing to start jupyter without requiring user to select the dataset explicitly. 

In the image below the dataset is selected using `Datasets` dropdown. But this selection (although it is mandatory) does nothing - dataset is not copied to jupyter container.

![screen shot 2017-04-25 at 3 45 54 pm](https://cloud.githubusercontent.com/assets/4291636/25404512/4ae6057a-29ce-11e7-8d06-f8915b976d6b.png)

Here, you start Jupyter by selecting it via the graph button adjacent to the dataset. Again, it does nothing in terms of copying dataset into Jupyter's container.  

![screen shot 2017-04-25 at 3 47 22 pm](https://cloud.githubusercontent.com/assets/4291636/25404567/7fe1121a-29ce-11e7-9d02-fc4dced9818e.png)

In addition, the Jupyter startup via the graph button adjacent to the dataset only works with tabular datasets. This is also a bug as it is easy to envision a scenario in which you want to start Jupyter on BAM or any other non tabular dataset.

**Comment by martenson** [comment]
Is this issue resolved?

**Comment by bgruening** [comment]
ping @nekrut

**Comment by nekrut** [comment]
I don't know

**Comment by martenson** [comment]
I have tested on Main that Jupyter loads the dataset it has been started from. (`Select random lines on data 61.txt` below) and it also loads a dataset when launched from menu.

```
!ls
[29783723] Select random lines on data 61.txt  ipython_galaxy_notebook.ipynb
```

It still cannot be started on bam, nor you can select multiple datasets when launching.

Close? @nekrut
