### ISSUE TITLE
Remove the 'reload tool XML' button from toolform

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#3987]
As it should no longer be needed with hot reload, or is there a usecase? @guerler @mvdbeek 

![screenshot 2017-04-27 14 39 14](https://cloud.githubusercontent.com/assets/1814954/25498810/619d7502-2b57-11e7-8f7c-007f4a250f9a.png)

**Comment by nsoranzo** [comment]
But `watch_tools` is disabled by default: https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.ini.sample#L256

**Comment by martenson** [comment]
@nsoranzo Hot reload and watchdog are not the same features I think. However they have different usecase I guess.

**Comment by martenson** [comment]
@jmchilton so is there other usecase than local tool development?

**Comment by hexylena** [comment]
I like it. I use it to reload tools on my instance

**Comment by mvdbeek** [comment]
I think we do check all loaded tools for changes now (starting with 17.05), so that does for a large part what `watch_tools` does. I'm not sure we still need the button.

**Comment by martenson** [comment]
@erasche can you please describe your case a bit?

**Comment by jmchilton** [comment]
> I think we do check all loaded tools for changes now (starting with 17.05)

I had no clue - tried it and it worked despite no watchdog. That is utterly fantastic! Is it performant, if yes should I go in and remove all the watchdog stuff?

**Comment by mvdbeek** [comment]
> Is it performant, if yes should I go in and remove all the watchdog stuff?

Hard to say, on my server I noticed no problems. Maybe we can keep it in for a while. Also, for monitoring directories of tools we still need watchdog, right?

I just saw @martenson put as milestone 17.09, that sounds OK then to me.

**Comment by martenson** [comment]
These are all tool developer features though, I would like to remove the button. Or make it configurable and disabled by default at least.

We might consider something like `tool_development = True` flag for features like this

**Comment by jmchilton** [comment]
I'm totally cool with axing it if they reload automatically - that is fantastic. 

I think there is a usecase where local admins manage tools locally and this could be useful in a production-y environment as @erasche points out - so I'd dispute this is a "tool developer" only feature. But it is moot since they seem to just magically reload now - which is simply amazing!

**Comment by hexylena** [comment]
Yupp, per @jmchilton's comment, all of our local set of tools are installed to our galaxy via a git repo on the server. It's not "IUC best practices using a TS and travis", but it works and the reload tool button is quite nice when we have a new tool that's going through a couple of iterations. to just be able to click that where we are rather than having to go into admin.

You also cannot reload hidden=True tools via admin, so this is extra useful there.

**Comment by mvdbeek** [comment]
but even that use case is covered with the auto reloading, you'd just need to upgrade to 17.05 once it's out.

**Comment by martenson** [comment]
@erasche If they are in the toolconfig they will get monitored without watchdog. How can you see `hidden=True` tools in toolpanel though?

**Comment by hexylena** [comment]
@mvdbeek 

- If it is performant, sure.
- How does that work? We do not load tools from NFS, but I would be wary of tool reloading and issues with that as well.

@martenson you can't, you access them by ID. We use this to hide quizzes.

**Comment by mvdbeek** [comment]
> If it is performant, sure.

It seems to be. Our server is loading tools over sshfs and so far no problems. I guess the verdict will be in once usegalaxy.org and/or @bgruening is doing the upgrade.

**Comment by hexylena** [comment]
> It seems to be.

works for me, I'm happy to give this feature up if it is soon to be completely automatic, that's awesome.

**Comment by martenson** [comment]
This morning @davebx reported that a tool does not reload when changes happen to its macro. This is without watchdog I believe.

**Comment by jmchilton** [comment]
Well watchdog isn't going to fix the macros issue - we just don't monitor macros regardless. I'm not sure that is enough to warrant saving the button though.

**Comment by nsoranzo** [comment]
> I'm not sure that is enough to warrant saving the button though.

I see no rush in removing it, it's visible to admin only.

**Comment by davebx** [comment]
> If it is performant, sure.

I can say that main has this code, and reloads seem to work quite smoothly.

**Comment by mvdbeek** [comment]
We should still remove this when we don't need it anymore.

**Comment by martenson** [comment]
now when https://github.com/galaxyproject/galaxy/pull/4635 is in place, do we remove the button?

**Comment by hexylena** [comment]
So if this is now working perfectly, should we set `watch_tools = True` as default? Or at least `polling`? Right now admins get to discover that their beloved reload-tool button is now missing and have to know that tools are instead supposed to be reloaded by an automatic method that isn't enabled by default for them. Or at least a note in the admin UI where the "reload tool" disappeared, pointing to the admin docs for setting up tool watching?

**Comment by mvdbeek** [comment]
> that isn't enabled by default for them

Actually it should be the other way round, this is already enabled by default, but in addition you can enable watch_tools, which would monitor whole directories of tools (the current method watches only tools registered in one of the tool_conf.xml files)

**Comment by martenson** [comment]
@erasche I think all tools now reload on change by default.

**Comment by hexylena** [comment]
>  in addition you can enable watch_tools, which would monitor whole directories of tools (the current method watches only tools registered in one of the tool_conf.xml files)

so right now automatic reload only works for the first listed tool conf by default? that sounds confusing/unexpected.

@martenson this says "false", so I was under the impression nothing would auto-reload https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.yml.sample#L282

**Comment by mvdbeek** [comment]
sorry, I meant "any one of all the registered tool_conf.xml files"

**Comment by mvdbeek** [comment]
> @martenson this says "false", so I was under the impression nothing would auto-reload https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.yml.sample#L282

Nope, that's for the (never really documented) `watch_dir` (or was it `monitor_dir`?) directive that you can put in your tool conf file.

**Comment by martenson** [comment]
@erasche all tools in any tool conf are auto reloaded on change and there is no config to turn it off

@mvdbeek `watch_tools` is now just for the tool directories listed in tool confs?

**Comment by mvdbeek** [comment]
Right, that's how it should be at least.
