### ISSUE TITLE
show information about collections

### ISSUE THREAD

**Issue by kaktus42** [galaxyproject/galaxy#400]
It would be nice  to be able to see information about collections in the history.
At least how many elements the list has.
Further maybe a summary of the content (if possible)

**Comment by bgruening** [comment]
Indeed this would be useful. I wonder if there is a technical reason that a `data collection` does not offer similar options as a data set, e.g download, rerun, view (photo gallery like) ...

**Comment by carlfeberhard** [comment]
@kaktus42 do you mean in the _un-expanded_ collection view or after you click the collection and _expand_ it?

**Comment by kaktus42** [comment]
@carlfeberhard It's already some time ago, but I think, that's what I meant.

**Comment by carlfeberhard** [comment]
@kaktus42 Understandable. Thanks for responding and sorry it took so long for me to follow up.

**Comment by carlfeberhard** [comment]
This will end up being expensive as is. It requires a second query to fetch the elements inside the collection. 

If the collections were immutable I would say that we could set something up when they're created, but I don't think that will work. Collection elements aren't copies - they behave more like symlinks (apparently). If the original dataset is deleted, the one inside the collection is too. I don't know if it _has_ to be that way - but I would think a deleted element wouldn't count toward the total collection count --> mutable.

I'll try to think of a cheap way to do this for potentially 100s of collections (in a history).

**Comment by kaktus42** [comment]
@carlfeberhard: Would it be possible to cache it?

**Comment by carlfeberhard** [comment]
There may be a way to cache it in the browser (I'd rather not do it in the db), and reduce the pain down to one call per collections and remove the need for subsequent. I'd like to make that a separate API call, tho, that 'decorates' the already usable collection item in UI after everything's loaded. We'll see.

**Comment by pvanheus** [comment]
When will we see @carlfeberhard ? Just to be clear there are 2 things discussed here thus far:

1) Show count of number of items in collection (possibly also number running, number error, etc)
2) What @bgruening said: " I wonder if there is a technical reason that a data collection does not offer similar options as a data set, e.g download, rerun, view (photo gallery like) ..." - I would like to be able to download a collection at least. Other operations (rerun) are not quite as straightforward. The "photo gallery" idea is intriguing but needs fleshing out.

**Comment by carlfeberhard** [comment]
@pvanheus 1) Sometime after #1374 and before many other things. Thanks for being patient.
