### ISSUE TITLE
Upload issue shows service unavailable

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#4002]
Filling this one on behalf of my current boss, he tried to upload a file and this errored with 503 Service Unavailable.

![snipimage](https://cloud.githubusercontent.com/assets/458683/25595777/a00168f6-2eb5-11e7-976c-8eebd5da9b39.JPG)

Looking on the backend, it looks like uWSGI through a read error.  My best guess is that it is due to a network issue (he has a really flaky network). Would it be possible to show this error (timeout on read) in the frontend somehow? Instead of just the 503? (I realise this is a long shot, but see first sentence.) We've had this a couple of times, wonder if anyone else has seen this issue / knows a root cause.

![utvalg_062](https://cloud.githubusercontent.com/assets/458683/25595788/aaf5d620-2eb5-11e7-8c94-d804e0aab66c.png)

**Comment by martenson** [comment]
we no longer uwsgi, so this should be a noop now, hopefully
