### ISSUE TITLE
Output dataset collections are not properly set to an error state in all cases

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#4032]
I'm running the tip of the dev branch.  I have a tool that defines an output like this
```
<outputs>
    <collection name="transcripts" type="list">
        <discover_datasets pattern="__name__" directory="assemblyPostProcessing_dir" visible="true" ext="fasta" />
    </collection>
</outputs>
```
When a job ends in an error, this function is reached
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/__init__.py#L1123
where the received parameters are:
```
stdout: ''

stderr: 'Coding sequence prediction was not successful.
Either ESTScan is not properly installed or there a problem with reference score matrices you provided.
Alternatively, you data might not have sequences with credible coding regions.
Terminating...'

tool_exit_code:1
```
I'm wondering if this function is the intended destination for dataset collections as the code doesn't seem to support them.

The tool produces 2 elements in the output collection, which are both empty files.  This is expected, but the status of the elements and the parent history item are green when they are expected to be red.

Processing ultimately reaches this line in the function https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/__init__.py#L1196, the entire block of which is skipped since these are both empty:
```
job.output_datasets + job.output_library_datasets 
```
Should this block also include ```job.output_dataset_collection_instances```, maybe something like this?
```
for dataset_assoc in job.output_datasets + job.output_library_datasets + [c.dataset_collection_instance.collection for c in job.output_dataset_collection_instances]:
```
The above didn't work for me since ```c.dataset_collection_instance.collection``` is empty.  I believe the ultimate list should consist of hdas, but not quite sure how to get them from the output collection.

**Comment by jmchilton** [comment]
Some of my initial experiments related to this are here #4044. Any chance you'd share the problematic tool with me?

**Comment by gregvonkuster** [comment]
Thanks for taking a look at this @jmchilton 

The tool is installable from the TTS here https://testtoolshed.g2.bx.psu.edu/view/greg/assembly_post_processor/c631e136d5e7.  

You'll have to add ```gregvonkuster``` to your conda channels so the dependencies will install - I've not yet moved them to bioconda, but coming soon.

I've attached a screen shot of the tool settings.

The scores matrices file ```Arabidopsis_thaliana.smat``` is available for download at https://sourceforge.net/projects/estscan/files/matrices/December-2006/Arabidopsis_thaliana.smat.gz/

I've attached an input dataset ```transcripts_pep.fasta.txt``` that will produce the behavior using the tool setting in the attached screenshot.

[transcripts_pep.fasta.txt](https://github.com/galaxyproject/galaxy/files/986930/transcripts_pep.fasta.txt)

<img width="687" alt="app" src="https://cloud.githubusercontent.com/assets/6947053/25855259/afd319aa-34a0-11e7-893e-e2ebfd447d8b.png">

**Comment by jmchilton** [comment]
Better in 18.01? I believe failing jobs with collection outputs are more intuitively failed in 18.01 - though there is still considerable room for improvement. Next up I want to be able to see the job details from output collections - I may work on that next week since it is important for #5380.
