### ISSUE TITLE
configfiles -> inputs - the JSON does not export data parameters

### ISSUE THREAD

**Issue by blankclemens** [galaxyproject/galaxy#4040]
When using 

```
<configfiles>
    <inputs name="inputs" />
<configfiles>
```
as described in https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-configfiles-inputs one would expect that all input parameters will be exported. It seems that this is not the case for data fields, e.g. input files from the history. I'm not sure if this is a bug or a feature, but I feel that this contradicts a common use case for this option - to ease passing parameters. Especially when you can have an arbitrary amount of them like with the data parameter.

**Comment by bernt-matthias** [comment]
Seems to be possible now with the `data_style` attribute.
