### ISSUE TITLE
Update Deseq2 from 2.11.38 to 2.11.39 at http://usegalaxy.org 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4046]
Please update to [2.11.39](https://toolshed.g2.bx.psu.edu/view/iuc/deseq2/6f91b8ce6e07) (main has v 2.11.38): https://github.com/galaxyproject/tools-iuc/pull/1231

cc @davebx @galaxyproject/guac

**Comment by davebx** [comment]
2.11.39 has been installed on main
