### ISSUE TITLE
allow profile-bound language setting

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4048]
Due to the (awesome) contributions such as [this](https://github.com/galaxyproject/galaxy/pull/4045) that include automated translations of strings to other locales (in order to 'start things up') I believe we are in need of having features that override the default i18n behavior. In this case I think that we use whatever locale is in `navigator.languages, navigator.language or navigator.userLanguage` property of browser (default requirejs plugin settings).

I am not sure how automatic translation performs for other languages but it is _really_ bad for Czech - especially regarding software. I can also spot problems in our German translation despite my basic knowledge.

I think providing users with autotranslated strings that are possibly of poor quality reflects poorly on Galaxy's user experience. The only option to opt out that the user currently has is to change their browsers locale which is complicated and has broad effects.

I think we should:

- provide a UI for users to set their locale preference that ignores their browser settings
- grade translations based on quality (at least beta vs production)
    - make 'beta' translations (such as automated translations) as opt-in

**Comment by yvanlebras** [comment]
Hi @martenson ! Good idea! Furthermore, as I'm working with @ValentinChCloud to translate others fields as "general" Galaxy tools, maybe we can exchange about the best way to propose language dependant content as tools... We are using here a dedicated french Tool shed... 

![image](https://cloud.githubusercontent.com/assets/7910679/26101140/6a729c42-3a30-11e7-9e84-84da16b7d08e.png)

**Comment by lecorguille** [comment]
I agree with Martin!
Specially, since we are updating our Galaxy instance which hosts some screencasts (like some HowTo) in English.

**Comment by hexylena** [comment]
This was fixed in https://github.com/galaxyproject/galaxy/pull/5282
