### ISSUE TITLE
Upload into collections cannot be realistically used

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#4057]
Suppose you are uploading files from the web using links and would like to immediately put then into a collection. You start with the upload tool where you choose **Collection** tab, click **Paste/Fetch data** button and then paste the URLs in:

----

![screen shot 2017-05-11 at 2 44 57 pm](https://cloud.githubusercontent.com/assets/4291636/25966855/46b043ec-365a-11e7-87ee-ff7843145afa.png)

----

Obviously it is easier to paste all datasets into a single paste box as shown above. Once you click **Start** the data gets uploaded and the **Build** button gets exposed:

----

![screen shot 2017-05-11 at 2 45 52 pm](https://cloud.githubusercontent.com/assets/4291636/25966960/987710ac-365a-11e7-9f0e-3ab7c17f5bf0.png)

----

If you click on build button, you get this:

----

![screen shot 2017-05-11 at 2 46 26 pm](https://cloud.githubusercontent.com/assets/4291636/25966992/afda5f88-365a-11e7-9b2c-fc65cd9c89fb.png)

----

which is not what I expected. It seems that collection creator only sees the top dataset pasted into the paste box. 

If I paste URLs into individual boxes - everything works correctly, but it is hardly a feasible solution when you have even a dozen datasets.

So the upload tool has to be able to recognize that a number of URLs have been uploaded through a single box.

**Comment by nekrut** [comment]
As was discussed on gitter since it is unlikely that many users upload data using URLs we should just prevent pasting multiple URLs in

**Comment by jmchilton** [comment]
Will be fixed with merging of #4058.
