### ISSUE TITLE
Multipart upload with S3

### ISSUE THREAD

**Issue by zzsoni** [galaxyproject/galaxy#4060]
Hi,

We are testing ObjectStore Backend with our Object Storage (CEPH cluster with S3-compatible frontend), and we have a TypeError with multipart upload (mandatory for big files).

Version: Galaxy 16.10 with Python : 2.7.9

```
galaxy.jobs.runners.local ERROR 2017-05-09 14:06:22,458 Job wrapper finish method failed
Traceback (most recent call last):
  File "/storage/groups/galaxy/crri/lib/galaxy/jobs/runners/local.py", line 133, in queue_job
    job_wrapper.finish( stdout, stderr, exit_code )
  File "/storage/groups/galaxy/crri/lib/galaxy/jobs/__init__.py", line 1258, in finish
    self.app.object_store.update_from_file(dataset.dataset, create=True)
  File "/storage/groups/galaxy/crri/lib/galaxy/objectstore/__init__.py", line 502, in update_from_file
    return self._call_method('update_from_file', obj, ObjectNotFound, True, **kwargs)
  File "/storage/groups/galaxy/crri/lib/galaxy/objectstore/__init__.py", line 513, in _call_method
    return store.__getattribute__(method)(obj, **kwargs)
  File "/storage/groups/galaxy/crri/lib/galaxy/objectstore/s3.py", line 610, in update_from_file
    self._push_to_os(rel_path, source_file)
  File "/storage/groups/galaxy/crri/lib/galaxy/objectstore/s3.py", line 390, in _push_to_os
    multipart_upload(self.s3server, self.bucket, key.name, source_file, mb_size)
  File "/storage/groups/galaxy/crri/lib/galaxy/objectstore/s3_multipart_upload.py", line 87, in multipart_upload
    enumerate(split_file(tarball, mb_size, cores)))):
  File "/storage/groups/galaxy/crri/lib/galaxy/objectstore/s3_multipart_upload.py", line 104, in wrap
    return func(self, timeout=timeout if timeout is not None else 1e100)
  File "/opt/core/python-2.7.9/lib/python2.7/multiprocessing/pool.py", line 659, in next
    raise value
TypeError: transfer_part() takes exactly 6 arguments (1 given)
```

After some investigations, it seems that Pool.imap (in multiprocessing module) can only be used with function with only one argument...
Here is an ugly workaround which fixes the bug for us :
```diff
diff --git a/lib/galaxy/objectstore/s3_multipart_upload.py b/lib/galaxy/objectstore/s3_multipart_upload.py
index 9b40b70..19b97b6 100644
--- a/lib/galaxy/objectstore/s3_multipart_upload.py
+++ b/lib/galaxy/objectstore/s3_multipart_upload.py
@@ -53,7 +53,7 @@ def mp_from_ids(s3server, mp_id, mp_keyname, mp_bucketname):
 
 
 @map_wrap
-def transfer_part(s3server, mp_id, mp_keyname, mp_bucketname, i, part):
+def transfer_part((s3server, mp_id, mp_keyname, mp_bucketname, i, part)):
     """Transfer a part of a multipart upload. Designed to be run in parallel.
     """
     mp = mp_from_ids(s3server, mp_id, mp_keyname, mp_bucketname)
```

Thanks.

**Comment by arbernard** [comment]
Just a quick comment to say that I have recently updated a Galaxy instance to the latest version available on the master branch and that it seems that this issue is still here.

**Comment by dannon** [comment]
Thanks for the ping here @arbernard.  I'll take a look at this and see what I find.  With the pending 17.09 release, it'd be good to resolve this.

**Comment by dannon** [comment]
@arbernard Actually, I knew this was familiar.  This should have been resolved with 4b52476b24fd6cb196eac32295e6ae1a30228b2f.  Which version of galaxy exactly are you using right now?

**Comment by arbernard** [comment]
The instance I was speaking about is based on the master branch and should be at the last commit available on this branch.

Is this issue just fixed on the dev branch at the moment ?

**Comment by dannon** [comment]
@arbernard That explains it.  Correct, it's only in dev and the forthcoming release_17.09 right now.  Once 17.09 is final and released, it'll be in master as well.

**Comment by arbernard** [comment]
That's great, thanks :)

**Comment by dannon** [comment]
Cool.  Closing this issue, then.  If you find that it's not resolved with https://github.com/galaxyproject/galaxy/commit/4b52476b24fd6cb196eac32295e6ae1a30228b2f, feel free to reopen.
