### ISSUE TITLE
webhooks do not make use of proxy_path

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#4064]
cc @bgruening  @anatskiy most of the examples of webhooks (and those people copy off of) all use code like

```
$.getJSON("/api/...)
```

which unfortunately does not behave under if galaxy is running under some path other than `/`. It would be nice if this could be automatic. I understand that webhooks are mostly for sites that are focusing on customising a single instance. For the gcc event I'm going to deploy many galaxies and I noticed that I'll have to edit every webhook at boot time to correct the path.

**Comment by bgruening** [comment]
Can we fix this is 17.05 for you? Does it work if you add `Galaxy.root` in-front of `/api/`.

**Comment by hexylena** [comment]
Yes it does! I'll PR this to all the existing plugins.

**Comment by mvdbeek** [comment]
I'll close this since @erasche PR has been merged into 17.05.
