### ISSUE TITLE
offer 'copy to clipboard' button on datasets

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4073]
To make clear and easier that people can share the datasets using that URL.

@natefoo 's nice idea

**Comment by anurag-ks** [comment]
I would like to work on this.

**Comment by OlegZharkov** [comment]
> To make clear and easier that people can share the datasets using that URL.
> 
> @natefoo 's nice idea

Do you want to introduce new button `copy download URL to the clipboard` in histories?

**Comment by martenson** [comment]
Maybe a dropdown on the "save" icon that has `Download` and `Copy link` options?

**Comment by mvdbeek** [comment]
The download button is probably our 2nd most used button, as a user I would probably not be happy about the additional click, I think. An additional button (or dropdown, if we can think of other thing we need to add) when the dataset is expanded still seems ok to me.

**Comment by nsoranzo** [comment]
We could use https://fontawesome.com/icons/link as an icon for "copy link"

**Comment by martenson** [comment]
I suspect https://fontawesome.com/icons/clipboard is sort of a standard, at least on the websites I visit.

**Comment by nsoranzo** [comment]
I think the link icon makes it clearer that what is copied to the clipboard is the link to the dataset, not its content. Twitter uses this icon when sharing a tweet.

**Comment by OlegZharkov** [comment]
> 

Ok I will add this button then. 


Basically, I agree with @martenson, we probably should use https://fontawesome.com/icons/clipboard. Most of the time it means clipboard

**Comment by martenson** [comment]
Note that we already have such interface for copying, with another icon. 
![Galaxy](https://user-images.githubusercontent.com/1814954/96882808-f80dfb00-147f-11eb-9d35-c621b8fe41e4.png)

**Comment by OlegZharkov** [comment]
> Note that we already have such interface for copying, with another icon.
> ![Galaxy](https://user-images.githubusercontent.com/1814954/96882808-f80dfb00-147f-11eb-9d35-c621b8fe41e4.png)

Ah, I remember that one.... it's from https://github.com/galaxyproject/galaxy/pull/10124
 we should use the same symbol then
