### ISSUE TITLE
liftOver tool could additionally use the -bedPlus option

### ISSUE THREAD

**Issue by dpryan79** [galaxyproject/galaxy#4074]
A lot of people would like to liftOver not just BED/GFF files, but also BED-like files where there are additional columns with other values (e.g., multiple columns of coverage intensity). These can be handled on the command line with the `-bedPlus=` option, but that's not exposed in Galaxy. Would it be possible to add this?

Additionally, the tool shouldn't accept `interval` input, but rather `BED` instead. The interval files don't get reordered and liftOver then croaks.

**Comment by hexylena** [comment]
There's also crossMap now?

**Comment by dpryan79** [comment]
Yeah, that's largely replaced liftOver in the past couple years. This can be closed given that.

**Comment by hexylena** [comment]
> This can be closed given that

:tada::heart:
