### ISSUE TITLE
Galaxy PIL Library error -- "ValueError: Attempted relative import in non-package"

### ISSUE THREAD

**Issue by rbrown1422** [galaxyproject/galaxy#4090]
Good afternoon Galaxy Support,

We needed to upgrade PIL via PILLOW 4.1 on Redhat Linux and now we receive the following error in our Production version of Galaxy. We have tried several things to work-around it, to no avail. 

There appears to be some pathing going on internally that we cannot figure out impacting __init__.py  from being located.

Your assistance is much appreciated.

Thanks,

Bob Brown

>
> At least that is consistent with what we see.
> I will work on Dev to see if we can recreate and resolve this error.
> thanks
> Bob
>

>> On May 9, 2017 at 1:30 PM "Laroche,Sylvain" <slaroche@mdanderson.org> wrote:
>>
>> Whoa, error:
>>
>> # service galaxy restart
>>
>> Stopping galaxy... Traceback (most recent call last):
>>
>>   File "./scripts/paster.py", line 31, in <module>
>>
>>     from galaxy.util.pastescript import serve
>>
>>   File "/shelter/rppa/galaxy/lib/galaxy/util/__init__.py", line 43, in <module>
>>
>>     import docutils.writers.html4css1
>>
>>   File "/shelter/rppa/galaxy/eggs/docutils-0.7-py2.7.egg/docutils/writers/html4css1/__init__.py", line 23, in <module>
>>
>>     import Image                        # check for the Python Imaging Library
>>
**>>   File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 27, in <module>
>>
>>     from . import VERSION, PILLOW_VERSION, _plugins
>>
>> ValueError: Attempted relative import in non-package
>>**
>> done.
>>
>> Starting galaxy... 
>>
>> Traceback (most recent call last):
>>
>>   File "./scripts/paster.py", line 31, in <module>
>>
>>     from galaxy.util.pastescript import serve
>>
>>   File "/shelter/rppa/galaxy/lib/galaxy/util/__init__.py", line 43, in <module>
>>
>>     import docutils.writers.html4css1
>>
>>   File "/shelter/rppa/galaxy/eggs/docutils-0.7-py2.7.egg/docutils/writers/html4css1/__init__.py", line 23, in <module>
>>
>>     import Image                        # check for the Python Imaging Library
>>
>>   File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 27, in <module>
>>
>>     from . import VERSION, PILLOW_VERSION, _plugins
>>
>> ValueError: Attempted relative import in non-package
>>
>> ...done.
>>

**Comment by hexylena** [comment]
Given that galaxy now will enforce the use of a virtualenv with its own package versions, hopefully this issue is now resolved.
