### ISSUE TITLE
Non-name/hash tags shouldn't propagate. 

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4099]
At the team meeting everyone agreed I think that tags shouldn't in general propagate at tool execution - just name/hash tags.

@dannon you have mentioned you were going to take a crack at this so I'm pinging you. I know you are out of the country - I'm about to leave myself or I'd offer to help with this while you are away. I can help next week if you'd like though. Creating an issue to block the release because I guess I think we should not release with this current behavior.

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/issues/3730

**Comment by dannon** [comment]
Hrmm, thought I did this on the spot at SAB, maybe it got lost in the chaos.  Let me find it.

**Comment by dannon** [comment]
Yep.  https://github.com/dannon/galaxy/tree/tags_continued, just never made the PR :(
