### ISSUE TITLE
Please add tool "Salmon" to usegalaxy.org playbook job_conf.xml

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4102]
https://github.com/galaxyproject/usegalaxy-playbook/blob/master/templates/galaxy/usegalaxy.org/config/job_conf.xml.j2#L614

cc @natefoo @martenson

**Comment by martenson** [comment]
Please create issues in their respective repositories. https://github.com/galaxyproject/usegalaxy-playbook/pull/28

**Comment by jennaj** [comment]
Will do going forward. Thanks @martenson for adding the tool
