### ISSUE TITLE
"Show/hide hidden" link should stay visible when the search box is non-empty

### ISSUE THREAD

**Issue by chambm** [galaxyproject/galaxy#4103]
I can't think of a good reason for it to disappear when searching. Maybe a "Show/hide show/hide hidden link" link is necessary. ;)

**Comment by chambm** [comment]
This continues to irk. Does no one else have trouble with this when they have a large history? Turning on hidden files when I have 1000s of hidden files just so I can then enter a filter and see the 100 hidden files I was looking for is not ideal. (maybe already fixed in 17.09?)

**Comment by dannon** [comment]
Addressed with #4581
