### ISSUE TITLE
Workflow rename text box is too short, and create/import buttons are lonely

### ISSUE THREAD

**Issue by chambm** [galaxyproject/galaxy#4109]
![image](https://cloud.githubusercontent.com/assets/5011937/26384656/6ea2bf06-4000-11e7-9a17-7ffcc076a10a.png)

I spent a few minutes looking through the code and found the add_text() call but I couldn't figure out a way to specify that the text box should be wider. A brief search in CSS yielded nothing either. I figure an actual Galaxy dev will know how to do it in 5 seconds. :) I see no reason that the rename text box should be shorter than half the size of the containing panel (which as you can see is very wide!)

On a related note, I have a 2K monitor and the workflow menu could be more friendly to my eyes:
![image](https://cloud.githubusercontent.com/assets/5011937/26384761/01790286-4001-11e7-80a7-de0200bf1b9b.png)

The main points of interaction here - the workflows themselves and the create/import buttons - should stay on the same side of the screen.

**Comment by hexylena** [comment]
:+1:, I've done the same and couldn't figure it out. It's really rather annoying

**Comment by chambm** [comment]
Any ideas from UI guys?

**Comment by hexylena** [comment]
This may be resolved with the new workflow screen in https://github.com/galaxyproject/galaxy/pull/4047? Alternatively it'll be even worse as the buttons will be further to the right...

**Comment by nsoranzo** [comment]
This is fixed in Galaxy 18.05 (or earlier).
