### ISSUE TITLE
Issue tagging individual dataset through "configure output" option on a workflow step

### ISSUE THREAD

**Issue by yvanlebras** [galaxyproject/galaxy#4128]
If we configure a workflow step to tag an output dataset, when the workflow is executed, the dataset is tagged BUT there is no "beautiful display" e.g. no display of the tag on a "blue bullet" under the dataset name....
![image](https://cloud.githubusercontent.com/assets/7910679/26625855/af7fce42-45f5-11e7-9ac7-74681548b06f.png)

**Comment by mvdbeek** [comment]
I think the conversion of `#` to `name:` is not working properly right now in the workflow editor. If you change the tag in the workflow editor to `name:Observation`, it should work.

**Comment by dannon** [comment]
The 'normal' tag editor simply converts `#`-prepended tags to 'name' prior to saving, it's intended as a shorthand.  (So, the tag is still `name`, and the tag value is `Observation` )

I'll spiff up the workflow tag editor to handle things consistently.

**Comment by mvdbeek** [comment]
Closing this as it has been fixed in #4139. Feel free to re-open if the problem pops up again.
