### ISSUE TITLE
Interactive environment launcher - no options available

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/galaxy#4129]
The "Galaxy Interactive Environment Launcher" (accessed from the Visualization tab on the top center panel) on useGalaxy.org loads but the drop-down menus for the "GIE", "Image", and "Datasets" are missing. Screenshot:

<img width="1083" alt="2017 5 31 gie launcher" src="https://cloud.githubusercontent.com/assets/1814954/26640169/f9282806-45f4-11e7-941f-6ac34117ed12.png">

**Comment by martenson** [comment]
just now: 
![screenshot 2017-05-31 11 34 20](https://cloud.githubusercontent.com/assets/1814954/26640212/1b96f2b4-45f5-11e7-82f9-11e498fd812c.png)

**Comment by martenson** [comment]
can you re-check @MoHeydarian ?

**Comment by MoHeydarian** [comment]
Thanks for checking @martenson. Yes, I now see the drop-down menus. 

I'll close the issue and keep an eye on the launcher page.
