### ISSUE TITLE
Old workflows with parameters cannot be executed after upgrade

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/galaxy#4132]
@guerler: this is a much bigger issue for me than #4131
When a user attempts to run an workflow from around 16.04 vintage, it's rendered ok - but typing into the parameter box does not update the tool inputs using that parameter and the user cannot execute the workflow.

Editing, moving a box and saving is not enough to make it executable.
Editing, then renaming all instances of the parameter is enough.

**Comment by guerler** [comment]
Thanks for these reports. Can you share a workflow which exhibits this behavior? I created one using workflow parameters with 16.04, 15.10 and 15.05 and was able to load and execute them with 17.05 with and without re-saving them.

**Comment by bwlang** [comment]
Are these exports helpful?
I'm diffing them now....

[broken_Copy_of__Std_DNA_PE___Trim___MapStat_v.0.5.ga.zip](https://github.com/galaxyproject/galaxy/files/1042554/broken_Copy_of__Std_DNA_PE___Trim___MapStat_v.0.5.ga.zip)
[working_Copy_of__Std_DNA_PE___Trim___MapStat_v.0.5.ga.zip](https://github.com/galaxyproject/galaxy/files/1042555/working_Copy_of__Std_DNA_PE___Trim___MapStat_v.0.5.ga.zip)

**Comment by bwlang** [comment]
differences between the JSON for ToolForm.View rendered for each workflow:

difference | working| broken
-------- | --------- | ----
step_label | "" | null
annotation | missing | present
text_value | "Not available" | "No dataset."
value | {"__class__": "RuntimeValue"} | null
has_upgrade_messages | false | true

**Comment by guerler** [comment]
There are quite a few tools in here. I am trying to install them locally now to access the run form page, unless there is a reproducible smaller example available somewhere. The exports should be very helpful. Thanks.

**Comment by guerler** [comment]
I might have identified the issue. I am working on a fix now. I will keep you posted.

**Comment by bwlang** [comment]
I think the problem may be the presence of () in parameter names... i'm testing that now, but wanted to let you know in case it's helpful.

**Comment by guerler** [comment]
Yeah, I have a fix now. Thank you so much and sorry for the inconvenience.
