### ISSUE TITLE
Report on the number of lines of fastqsanger.gz datatype

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/galaxy#4144]
When we have a number of lines count on a fastqsanger.gz (i.e on the right column of history executions), the count is from the compressed file. This makes little sense, it would be more helpful if it was from the uncompressed file (e.g. to compare paired reads).

In case this is not clear, imagine a file seqs.fq.gz:
```
$ zless seqs.fq.gz |wc
 989364 1236705 88366482
$ wc seqs.fq.gz 
   88020   515400 24417349
```

Galaxy reports 88020, I think it would make more sense to report 989364.

**Comment by dpryan79** [comment]
I'll try to implement this during the GCC hackathon, since it's bothered me as well :)
