### ISSUE TITLE
Bug with "Create DBKey and Reference Genome"

### ISSUE THREAD

**Issue by tiagoantao** [galaxyproject/galaxy#4165]
I am trying to load a new genome on our local database. This is from the model species C. elegans (ce11). Whatever the way I try to do it I have a out of memory error. In my case the process takes 2TB of memory (which is all there is available).

I have tried loading from a local history, UCSC and NCBI.
This can be repeated (on the last Docker stable) with:
UCSC ce11
NCBI GCA_000002985.3
Or a local history concatenation of the genome.

Thanks

**Comment by mvdbeek** [comment]
That's an issue of this data manager, which is maintained by the IUC. There is already an issue about this [here](https://github.com/galaxyproject/tools-iuc/issues/1244).
