### ISSUE TITLE
Export [shared] history to file

### ISSUE THREAD

**Issue by cumbof** [galaxyproject/galaxy#4168]
I'm facing with an issue concerning the action of exporting a shared history to a file. The resulting file should be a .tar.gz archive containing all the data inside the history but I obtain a .dat file. These are the steps to reproduce the issue:

1. access a shared history like: [https://test.galaxyproject.org/u/fabiocumbo/h/iwtomics-etn-example](https://test.galaxyproject.org/u/fabiocumbo/h/iwtomics-etn-example)
2. click on _Import history_
3. export the current history to file

**Comment by jennaj** [comment]
@fabio-cumbo  Hello - This was probably a temporary situation on the test server. Looks as if it is working correctly again now (with your test example) and also on main (my own test example), so am closing this out. Should your ever run into the problem on the main server, please let us know.

Thanks!!

<img width="779" alt="screen shot 2017-09-21 at 9 58 47 am" src="https://user-images.githubusercontent.com/8999735/30708483-ebf586d4-9eb3-11e7-96f8-aa25e5b27487.png">
