### ISSUE TITLE
Toolshed installation errors not picked up

### ISSUE THREAD

**Issue by chambm** [galaxyproject/galaxy#4170]
I had some improper permissions set in my Galaxy 17.05 directory, such that when I installed a tool which had to install something in tool-data, it got 'Permission denied'. However, the installing status hung at "Cloning". If I didn't suspect the install should have happened very quickly, I might have waited all day! :relieved: To reproduce:
```
chown root:root $GALAXY_ROOT/tool-data -R
```
Then install `samtools_sam_to_cram` from admin interface. Then re-chown your tool-data directory.

**Comment by mvdbeek** [comment]
yeah, I guess we should intercept this and set the state to error.
