### ISSUE TITLE
Enhancement: Add confidence level to branches in Charts Phylocanvas and Phyloviz 

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#4171]
Phylogenetic tree datasets with Galaxy datatype ```nhx``` can be viewed in both the Phylocanvas and Phyloviz visualization plugins.

<img width="390" alt="phyloviz" src="https://user-images.githubusercontent.com/6947053/26936508-deedfdbe-4c3c-11e7-83b1-51004b574661.png">

These ```nhx``` datasets can be produced by both FastTree and RAxML inference methods, which both have support values on the branch nodes that represent a confidence level of the tree topology.  FastTree outputs SH-like support values and RAxML outputs bootstrap values.  Most tree viewers are able to display these value on the tree topology.

<img width="631" alt="confidence_levels" src="https://user-images.githubusercontent.com/6947053/26936617-3063cb7e-4c3d-11e7-9a69-71538958fae1.png">

It would be great if both the Phyloviz and Phylocanvas visualization plugins could be enhanced to display these confidence level values for branches if they are available in the datasets.

**Comment by gregvonkuster** [comment]
I've taken a look at this and believe it is fairly trivial.  However, it is not clear how the Javascript source maps and other files are being created since there does not seem to be a ```Gruntfile``` associated with this plugin.  I've not found clarification for this in the Galaxy visualization documentation.

From the Galaxy installation root directory, I believe this file should be changed:
```
./config/plugins/visualizations/charts/static/repository/visualizations/biojs/phylocanvas/wrapper.js
```
Here is the ```git diff``` for the enhancement:
```
$ git diff config/plugins/visualizations/charts/static/repository/visualizations/biojs/phylocanvas/wrapper.js
diff --git a/config/plugins/visualizations/charts/static/repository/visualizations/biojs/phylocanvas/wrapper.js b/config/plugins/visualizations/charts/static/repository/visualizations/biojs/phylocanvas/wrapper.js
index d3a5755..4816929 100644
--- a/config/plugins/visualizations/charts/static/repository/visualizations/biojs/phylocanvas/wrapper.js
+++ b/config/plugins/visualizations/charts/static/repository/visualizations/biojs/phylocanvas/wrapper.js
@@ -27,6 +27,8 @@ define( [ 'utilities/utils', 'plugins/biojs/phylocanvas/phylocanvas' ], function
                         tree.setNodeSize( node_size );
                         tree.setTextSize( text_size );
                         tree.lineWidth = line_width;
+                        // Show bootstrap confidence levels
+                        tree.showBootstrap = true;
                         // Register click event on tree
                         tree.on( 'click', function ( e ) {
                             var node = tree.getNodeAtMousePosition( e );

```
Of course, I very well may be missing something here - again I'm not clear on how the various files are being created for this plugin:
```
$ find . | grep phylocanvas
./config/plugins/visualizations/charts/static/repository/build/biojs_phylocanvas.js.map
./config/plugins/visualizations/charts/static/repository/build/biojs_phylocanvas.js
./config/plugins/visualizations/charts/static/repository/plugins/biojs/phylocanvas
./config/plugins/visualizations/charts/static/repository/plugins/biojs/phylocanvas/phylocanvas.js
./config/plugins/visualizations/charts/static/repository/visualizations/biojs/phylocanvas
./config/plugins/visualizations/charts/static/repository/visualizations/biojs/phylocanvas/logo.png
./config/plugins/visualizations/charts/static/repository/visualizations/biojs/phylocanvas/config.js
./config/plugins/visualizations/charts/static/repository/visualizations/biojs/phylocanvas/wrapper.js
[greg@bigsky galaxy]$ vim ./config/plugins/visualizations/charts/static/repository/plugins/biojs/phylocanvas/phylocanvas.js
```
Help is greatly appreciated!  Thanks!  ;)

**Comment by gregvonkuster** [comment]
ping @anuprulez

**Comment by anuprulez** [comment]
@gregvonkuster 

For updating the visualization related files, the local instance of the Galaxy needs to have 'grunt' installed at this path:

`/config/plugins/visualizations/charts`

For each visualization plugin, the library (phylocanvas.js) and code files (wrapper.js and config.js) are compressed into one. For example, Phylocanvas has a file named 'biojs_phylocanvas.js' at:

`config/plugins/visualizations/charts/static/repository/build`

If we update the files like wrapper.js or config.js for any visualization, we should delete the compressed files for that visualization (`biojs_phylocanvas.js `and `biojs_phylocanvas.js.map` for Phylocanvas). Then, we execute this command to port the changes in wrapper.js or config.js to the compressed file:

`config/plugins/visualizations/charts$ webpack`

The compressed files are created again with our latest changes. Does this answer to your question?

Regarding the enhancement you have mentioned, I will check if is already provided by the library or we need to update the Phylocanvas library file to have 'confidence level' entity in the branches.

**Comment by gregvonkuster** [comment]
@anuprulez Thanks for the info - this is helpful.  It would be great if you have the time to add this enhancement.  If not, I will try out your instructions and see if I can get it added.

**Comment by anuprulez** [comment]
@gregvonkuster I will do this update. Do you have a sample data for any Phylocanvas tree which has this entity value so that I can verify when I am done?

**Comment by gregvonkuster** [comment]
Thanks @anuprulez I think this dataset should work.  Please let me know if you discover that it doesn't or if there is anything I can do to help out with testing, etc. 
[treefile.txt](https://github.com/galaxyproject/galaxy/files/1125200/treefile.txt)

**Comment by anuprulez** [comment]
@gregvonkuster I updated the code to have 'showBootstrap' feature in Phylogenetic Tree Visualization. It is committed [here](https://github.com/bgruening/galaxy/tree/enhancement_phylocanvas).

By default, this feature is disabled. So, in the "Customize" section of "Phylogenetic Tree Visualization", "Show bootstrap confidence values" property needs to be set to "true" to enable it. The tree you shared looks like this when "showBootstrap" is enabled. Please share your feedback. 
If everything is ok, we can open a PR :)

![bootstrap](https://user-images.githubusercontent.com/3022518/27875190-a23113e4-61b2-11e7-8967-0dd2e4ee47d0.png)

**Comment by gregvonkuster** [comment]
Yes, this is just what I was looking for - this looks great!  Thanks so much for your help @anuprulez !!  ;)

**Comment by anuprulez** [comment]
Thanks @gregvonkuster. I opened a [PR](https://github.com/galaxyproject/galaxy/pull/4284) for this feature.

**Comment by gregvonkuster** [comment]
The Phylocanvas plugin handles this enhancement request via https://github.com/galaxyproject/galaxy/pull/4284.  It would be great if the Phyloviz plugin could be enhanced to provide the same feature.

**Comment by anuprulez** [comment]
@gregvonkuster To add the confidence level for Phyloviz, I updated this information in the tooltip for nodes as other entities like the distance and annotation are also being displayed there. 

Here is how it looks:

![phyloviz_confidence_level](https://user-images.githubusercontent.com/3022518/27922466-6986a71a-627b-11e7-8612-2d065419242c.png)

Is it ok like this? It might need more time if we need to display it as text just beside these nodes like we do it in Phylocanvas. If it is ok, I can open a PR for this change.

It is committed [here](https://github.com/bgruening/galaxy/tree/enhancement_phylocanvas). Thanks!

**Comment by gregvonkuster** [comment]
@anuprulez Thanks for doing this.  This is a great step forward and will be ok for the current time.  Ideally the weights should be displayed on each branch though as this makes it much easier to see information for all branches.  This improvement can wait until it is more convenient though.  Thanks again for all of your help on this!  ;)

**Comment by anuprulez** [comment]
@gregvonkuster I updated the Phyloviz library to show the bootstrap value as text on the Phylogenetic tree branches. It needed a small change. Initially I was not sure :)

It looks like this:

![bootstrap_phyloviz](https://user-images.githubusercontent.com/3022518/27956923-45580a04-631c-11e7-9a05-d6a43a3a829c.png)

Does it look ok now?

**Comment by nsoranzo** [comment]
Nice!

**Comment by anuprulez** [comment]
I created a PR for this change #4292 
Thanks @nsoranzo and @gregvonkuster!

**Comment by gregvonkuster** [comment]
Excellent!!  Thanks a bunch @anuprulez for all of your help.  It is greatly appreciated!  ;)

**Comment by gregvonkuster** [comment]
Closed via https://github.com/galaxyproject/galaxy/pull/4292 and https://github.com/galaxyproject/galaxy/pull/4284.
