### ISSUE TITLE
Dataset rename PJA not repeated when retrying failed job

### ISSUE THREAD

**Issue by chambm** [galaxyproject/galaxy#4172]
When a workflow step fails and I manually resubmit it (and usually click resume dependencies), the rename PJA is not rerun. It triggers me a bit so I have to delete all the jobs and rerun the workflow. :disappointed_relieved: Is this easy to fix (something I could try) or are the PJAs not accessible at the time the job is retried?

**Comment by dannon** [comment]
@chambm The resubmit code probably just doesn't hook PJAs up like the workflow invocations do -- it should be fairly easy to fix since you have a handle to the original job at that point.  Let me know if you need more pointers and I can look

**Comment by scholtalbers** [comment]
This is indeed unfortunate as this is a recurring issue: #560

**Comment by dannon** [comment]
I looked into this a bit.  The good news is the PJAs get copied, the bad news is that there's no re-execution of the 'immediate' PJAs -- only the ones that happen on job finish.  We need to dig up the original workflow request w/ parameters and execute the immediate actions again at job resubmit time.

**Comment by cgirardot** [comment]
Hi, what is the status on this? We are also very affected by this bug. As chambm mentioned, users then rerun the whole workflow to get correct naming which ends up in huge resource waste and causes frustration (when errors occurs after few hours of run). We would love to see it fixed in the next release. What are the chances ? 
Thx

**Comment by dannon** [comment]
@cgirardot We should be able to get this into the release.  I did track down where we need to amend the rerun context, I just haven't had a chance to implement it yet.

**Comment by dannon** [comment]
(re-milestoned since the PR/fix is open now)
