### ISSUE TITLE
Uncaught Exception when running a workflow through REST API.

### ISSUE THREAD

**Issue by theosotr** [galaxyproject/galaxy#4184]
Ι run a workflow through JAVA API library and I'm getting the following error.

```
galaxy.web.framework.decorators ERROR 2017-06-11 16:49:32,443 Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/srv/galaxy/lib/galaxy/web/framework/decorators.py", line 281, in decorator
    rval = func( self, trans, *args, **kwargs )
  File "/srv/galaxy/lib/galaxy/webapps/galaxy/api/workflows.py", line 275, in create
    for v in outputs[ step.id ].values():
AttributeError: 'object' object has no attribute 'values'
```
with a little debugging, the value of `output [step.id ]` is `STEP_OUTPUT_DELAYED` which is a simple `object()`.

When I run this workflow from UI, nothing fails.

**Comment by galanisd** [comment]
More specifically....
We are running a workflow of 3 processors/components.
Dataset Collection Reader -> PDF2XMI -> FundingMining

PDF2XMI : Extracts text from a set of PDFs and creates the respective XML (XMI) files with the content of the PDFs. More info here: https://github.com/galanisd/omtd-simple-workflows
--> Example 1.

FundingMining: Gets a sets of XML(XMI) files and finds funding info...
More info here: https://github.com/openminted/FundingMining_OMTD

We call the the workflow programmatically via a version of blend4j (https://github.com/greenwoodma/blend4j/) and we are getting the error that we mentioned above.

If we call the worklflow from the Galaxy UI we do not get error....
Also results from the first component (PDF2XMI ) are produced but we still have some issues with the second (FundingMining).

PDF2XMI and FundingMining are dockerized and run in a Mesos cluster.

When we run workflows with 1 docker no issues have been identified yet.
e.g. 
Dataset Collection Reader -> NamedEntityRecongizer (Dockerized)
Dataset Collection Reader -> TopicInferencer (Dockerized)

In both cases (Galaxy UI and blend4j) we get  the expected results...and we are able to download them.

**Comment by galanisd** [comment]
Also attached the Galaxy wrappers for the workflow for which we get the error.
[wrappers.zip](https://github.com/galaxyproject/galaxy/files/1111811/wrappers.zip)

**Comment by greenwoodma** [comment]
turns out that this was related to running a workflow via the now deprecated run REST API rather than the new invoke calls. The same workflow runs without issue via the invoke REST API so this issue can be closed.

**Comment by thobalose** [comment]
I am using https://github.com/phac-nml/irida to launch workflows and keep hitting the same issue. Kindly help.
