### ISSUE TITLE
Executing "make client" change locale fr for analyze and workflow pages

### ISSUE THREAD

**Issue by yvanlebras** [galaxyproject/galaxy#4187]
If we have to execute "make client" on a galaxy server (for example to modify the time we have to wait for an GIE to be launched on galaxy/client/galaxy/scripts/galaxy.interactive_environments.js), it seems that some pages (as "analyze data" and "workflow") are not accessible in a french language anymore....

**Comment by dannon** [comment]
That's weird.  Do you have any local changes to those locale files?

**Comment by yvanlebras** [comment]
no differences on the locale.js files apparently..

**Comment by dannon** [comment]
But some of the localization still works?

**Comment by yvanlebras** [comment]
Apparently, we have the good french localization for all the pages (workflow/shared data/visualization/admin/help) exept analyze data and user..... in US...

**Comment by dannon** [comment]
@yvanlebras Are you guys still seeing this?  I've significantly overhauled the client build process in recent releases, so hopefully this isn't happening anymore.  If you're good to go, I'd like to close this as I'm trying to clear out old issues.

**Comment by yvanlebras** [comment]
Thanks @dannon, ok for me to close this issue, it seems to be ok now, if I encounter an issue, I will open a new one. Thanks!

**Comment by dannon** [comment]
@yvanlebras Sure, thanks!
