### ISSUE TITLE
Xml parser failing building tool definition

### ISSUE THREAD

**Issue by guilhemheinrich** [galaxyproject/galaxy#4190]
This xml definition tool is working, tool_id got found and tool works normally.
[working.txt](https://github.com/galaxyproject/galaxy/files/1074507/working.txt)

This xml definition tool is not working, tool_id is not recognized.
[not_working.txt](https://github.com/galaxyproject/galaxy/files/1074506/not_working.txt)

After a bit of investigation, it seems that including '--' in any comment section reproduce the bug.

**Comment by nsoranzo** [comment]
That's not a bug, it's the XML syntax, see e.g. the "Comments in XML" section of https://www.w3schools.com/xml/xml_syntax.asp:
```Two dashes in the middle of a comment are not allowed.```
