### ISSUE TITLE
Duplicate tour_ids in tool form when using conditionals

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#4193]
Element ids should always be unique.

One example in "Known issues" here: https://github.com/galaxyproject/galaxy/pull/4019

**Comment by dannon** [comment]
Correction, this isn't duplicate dom IDs, it's duplicate tour_ids on the elements in the tool form.

I've argued in the past that we should just remove tour_ids completely and use sensible, unique, and predictable dom ids for elements where we need control like this.  Having a second layer of semantic markup to create/maintain just seems silly.

**Comment by willdurand** [comment]
> I've argued in the past that we should just remove tour_ids completely and use sensible, unique, and predictable dom ids for elements where we need control like this. Having a second layer of semantic markup to create/maintain just seems silly.

I second this! 👍 

There are also invalid generated IDs in the menu since they seem to be generated from tool/section names. For instance, `:` is not allowed in a HTML ID, _cf._ screenshot below. I also found newlines.

![screen shot 2017-07-18 at 16 23 28](https://user-images.githubusercontent.com/217628/28322122-98ddd66a-6bd5-11e7-80d8-a2010a15e132.png)

**Comment by martenson** [comment]
This is labeled as bug so I am pushing this back to 18.09 - it can be fixed any time. Maybe even milestone clearing could be considered. @dannon

**Comment by dannon** [comment]
@martenson Pushing to 18.09 is good -- this is something I'd like to address in the next cycle.

**Comment by jmchilton** [comment]
Push again?

**Comment by dannon** [comment]
@jmchilton Yeah, this is waiting on some work on other components to be able to address.

**Comment by guerler** [comment]
Resolved in #13252.
