### ISSUE TITLE
Update FastQC to the latest version released 6-5-2017 (v69 - http://usegalaxy.org has v68) 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4196]
Community request:  https://biostar.usegalaxy.org/p/23543/

Toolshed: https://toolshed.g2.bx.psu.edu/view/devteam/fastqc/9337dd1fbc66

**Comment by davebx** [comment]
FastQC 0.69 has been installed on main.

**Comment by tshtatland** [comment]
Thank you very much! All set.

**Comment by jennaj** [comment]
Tool passed tests. 

Note: @martenson found that Solexa quality scores are not an accepted input format (ASCII required now). At some point prior they were. 

**Workflow for Solexa data users:** Convert to ASCII quality values with the Fastq Groomer before using this tool.
