### ISSUE TITLE
Old API keys are shown in admin interface

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#4206]
When I generate a new API key its added to the data base, i.e., there are multiple API keys in the DB for one user. The admin interface shows the first result which is the oldest.

**Comment by bernt-matthias** [comment]
Problem still exists in 17.09 and dev.

**Comment by dannon** [comment]
@bernt-matthias Thanks for reporting and bumping this, sorry I missed it the first time around.  I'll get a fix out for this.

**Comment by bernt-matthias** [comment]
just for curiosity: will the fix be to remove duplicate api keys or to present the latest?

**Comment by dannon** [comment]
It should present the 'active' (newest) API key, and old keys should no longer work for Galaxy access, which I'll verify.

**Comment by bernt-matthias** [comment]
FYI: Old keys already do not work when using ephemeris.

**Comment by dannon** [comment]
@bernt-matthias Good to know, that's the correct behavior; just a mental note on my end to verify it and make sure we have a solid test for it.

**Comment by hexylena** [comment]
Currently only see the current one.

**Comment by bernt-matthias** [comment]
I can verify this. Thanks.
