### ISSUE TITLE
Make "Multi-select dataset" open again to permit filters

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4215]
Was once an option, then changed, but is no longer available at least as of 17_01 & 17_05. Not certain exactly when functionality was lost or if the change was intentional. Be nice to have it back.

End-user request for functionality: https://biostar.usegalaxy.org/p/23639

For end-users:  The workaround is to use a **Dataset collection** instead of multi-select. This is how: https://galaxyproject.org/tutorials/collections/

Reference for prior related change for this functionality: https://github.com/galaxyproject/galaxy/pull/1019

ping @guerler 

Graphics are from a 17_01 local, but the same is true in 17_05 (and at Galaxy Main http://usegalaxy.org)

Single select has an open filter:

<img width="718" alt="screen shot 2017-06-21 at 12 33 55 pm" src="https://user-images.githubusercontent.com/8999735/27403236-936f342e-567e-11e7-9f0d-768cddf52eb1.png">

Multi select **does not** have an open filter:

<img width="715" alt="screen shot 2017-06-21 at 12 34 10 pm" src="https://user-images.githubusercontent.com/8999735/27403289-c234ccec-567e-11e7-928c-b58d584bdc16.png">

Collection select has an open filter:

<img width="717" alt="screen shot 2017-06-21 at 12 34 29 pm" src="https://user-images.githubusercontent.com/8999735/27403294-c7d01152-567e-11e7-9938-40ed0275b700.png">

**Comment by chambm** [comment]
Interesting. My instance release_17.05 **does** have an open filter. Now it's your turn to post browser/OS version @jennaj . :) I see this with Windows 7 / Chrome 58.0.3029.110:
![image](https://user-images.githubusercontent.com/5011937/27404065-55f444fe-5692-11e7-990d-f2485dfbc109.png)

My issue is actually that I can only select one result at a timeafter filtering.

This is a demo of the functionality I want:
http://jsbin.com/seqonozasu/1/edit?html,js,output
It's apparently not built-in to select2. I'd rather be able to just press CTRL-A, but a visible button will suffice.

**Comment by dannon** [comment]
I'm not 100% on the current implementation, though I can look if need be, but this used to switch modes based on how many options were available.  For example, with more than 20 options, you'd see the select2 version, otherwise the 'normal' select.

**Comment by chambm** [comment]
Ah, that is likely. I have ~200 fastqs there. I still want a way to filter them and select all options that match the filter (even ones not loaded into the select box yet)

**Comment by guerler** [comment]
Yes @chambm is correct. The user preference here was to display the classic select field whenever possible, however we display the select2 field when more +100 entries are found for performance reasons. I am open for suggestions. Sorry for the confusion.

**Comment by chambm** [comment]
@guerler This was my suggestion: http://jsbin.com/seqonozasu/1/edit?html,js,output - I tried to implement it myself but Node.js is not my strong suit! However, Jenna discovered that the classic select field has lost its filter capability (and I confirmed that with a smaller input set), so that needs to be fixed too.

**Comment by guerler** [comment]
As far as I know, the classic select field did not have a filter option.

**Comment by bwlang** [comment]
@guerler 
This is a big deal for my users ... we can't use collection yet - (seqtk, seqprep, ... can't handle them )
Need a way to type  ".1.fastq" then range select all the read 1s (and read twos in a separate box)
Can you point me in the right direction to implement it?

**Comment by bwlang** [comment]
@chambm's suggestion looks workable to me...

**Comment by jmchilton** [comment]
@bwlang 
- What seqtk tool isn't collection ready? My understanding is they mostly work on a single file at a time - so you should be able to map collections over them.
- Is it this [seqprep](https://toolshed.g2.bx.psu.edu/repository/display_tool?repository_id=32298bd663d862d5&render_repository_actions_for=galaxy&tool_config=database%2Fcommunity_files%2F000%2Frepo_666%2FseqPrep.xml&changeset_revision=c0ecd158e2a7) tool? You can take a collection of paired reads and use the unzip tool produce two flat lists - these flat tools should be able to be passed to that tool.

I'd be happy to see more usable selections of large number of files also - just want to make sure you aren't dismissing collections for the wrong reasons.

**Comment by bwlang** [comment]
@jmchilton  maybe i'm missing something... I'd like to be able to run seqtk sample on the two input files (using the same seed) to get a consistent number of reads for every library. Then I want to feed those pairs into seqprep to trim adapters (i'd also be happy with seqpurge or skewer - not wrapped yet). Downstream steps are more standard (alignment etc.) 
e.g. 
Am I doing something dumb here? 
![image](https://user-images.githubusercontent.com/61636/28046392-3f9bb4d4-65b1-11e7-9455-aeb555bf9007.png)
I can't connect from unzipped collection to seqtk sample...

**Comment by jmchilton** [comment]
If you disconnect the outputs to HISAT from seqtk_sample you should be able to make that connection - and then you should be able to reconnect to HISAT. The editor isn't giving you visual feedback on this but the output is sort of constraining the workflow to take a sort of shape and so you cannot drop the input and make it mapping operation.

Update: Do the sample operations have different parameters? If you are sampling them the same way - you don't even need to unzip the collection - it will just map over pair as well.

**Comment by bwlang** [comment]
@jmchilton dang! - i never would have figured that out.  Thanks.  First collection enabled produ workflow running now ;)

**Comment by bwlang** [comment]
I still think we should fix the input boxes to use select2 all the time though...

**Comment by guerler** [comment]
Thanks @chambm and @bwlang. Ill work on a PR to always show select2 and add the 'select all' feature.

**Comment by guerler** [comment]
I talked to @dannon. #4435 will come with a select2 update which includes the `Adapters` needed to resolve this issue.

**Comment by hexylena** [comment]
Fixed in #4435? :)
