### ISSUE TITLE
Transiently Failing List Downloader Test

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4218]
Added by @mvdbeek with https://github.com/galaxyproject/galaxy/pull/4098. I took a stab at debugging it with https://github.com/galaxyproject/galaxy/pull/4156 but it didn't help me come to any conclusions. I guess we should just strip it out until we have an idea? It is really odd that very similar tests don't seem to fail the same way.

**Comment by guerler** [comment]
Thanks (:

**Comment by jmchilton** [comment]
Seems fixed.
