### ISSUE TITLE
Renaming dataset collection does not rename in history

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#4242]
If you click on a collection, and click on the name you can rename the collection:

![image](https://user-images.githubusercontent.com/4154788/27585320-11610026-5b3c-11e7-8fea-436f5fd0d86c.png)

When you click back to the history this change is not visible:

![image](https://user-images.githubusercontent.com/4154788/27585348-317c48a2-5b3c-11e7-950a-b75c39224059.png)

If you refresh the history this change becomes visible:

![image](https://user-images.githubusercontent.com/4154788/27585376-5b8ce1e2-5b3c-11e7-9c12-ebc170735880.png)

**Comment by martenson** [comment]
Just tested this, still an issue.

**Comment by mvdbeek** [comment]
That history doesn't exist anymore, and if you enter the collection you can rename it. https://github.com/galaxyproject/galaxy/issues/17257 tracks the request for changing via the pencil icon
