### ISSUE TITLE
Tools with white space in IDs not displayed in tool panel in 17.05

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#4260]
Using version 17.05 I have found that tools that include white space in their ID like this one https://github.com/galaxyproject/tools-iuc/blob/master/tools/extract_genomic_dna/extract_genomic_dna.xml#L1 are properly loaded into the tool panel upon startup, but for some reason they are no longer displayed in the tool panel. I assume some recent changes to the tool panel code has caused this behavior, but I've not yet tracked it down.

Since tool IDs should ideally not include white space (I'm not sure if any except this particular tool do), I'm wondering if this tool ID should be fixed by eliminating the white space. This approach will, of course, pose some problems with reproducibility, but perhaps the new lineage code can map white space to "_" or something like this.

**Comment by gregvonkuster** [comment]
Update on this - it looks like the Extract genomic DNA tool will display properly in the tool panel with 17.05 if it is installed within a panel section that includes other tools.  It is not displayed if it is installed into a panel section by itself.

**Comment by hexylena** [comment]
This seems to be working now?
