### ISSUE TITLE
a bug in galaxy/lib/galaxy/web/framework/helpers/grids.py

### ISSUE THREAD

**Issue by fieldwang** [galaxyproject/galaxy#4264]
I build a local galaxy in my linux. I found there is a bug in /galaxy/lib/galaxy/web/framework/helpers/grids.py in line 811:
 the right code should be "elif not item.slug:"

**Comment by nsoranzo** [comment]
@fieldwang If you are willing, opening a pull request would give you credit for the fix.

**Comment by hexylena** [comment]
I guess this is fixed?
