### ISSUE TITLE
Workflow run menu performance issues

### ISSUE THREAD

**Issue by shiltemann** [galaxyproject/galaxy#4286]
Hi All :)

I have been having some problems loading the workflow run menu for some of my larger workflows in recent versions of Galaxy. 

For example, hitting *run* on the Mothur SOP tutorial workflow on main (https://usegalaxy.org/u/saskia-hiltemann/w/mothur-miseq-sop-tutorial) takes a very long time (more than a minute) to load and is all but unresponsive once it does, if it doesn't just outright crash my browser..

In the old workflow run menu this workflow loads instantly and without problems. I have been forced to hold my Metagenomics Galaxy server back at version 16.07 because of this issue.

**Comment by bgruening** [comment]
We accidentally discussed this with @guerler at GCC. He has a lot inside in this.

**Comment by guerler** [comment]
Can you forward this workflow? I tried to export it from usegalaxy but the export failed.

**Comment by guerler** [comment]
Fixed, see #5265. Feel free to reopen if not.
