### ISSUE TITLE
Messed up example/test for list collection

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#4288]
Check out [test/functional/tools/collection_creates_list.xml#L3](https://github.com/galaxyproject/galaxy/blob/master/test/functional/tools/collection_creates_list.xml#L3) where it is assigning outputs based on the output keys, which at time of output generation, contains no outputs! Yo dawg. lol

Thanks!

**Comment by jmchilton** [comment]
If you run the test:

```
./run_tests.sh --framework -id collection_creates_list
```

it should work. It does on our Jenkins test server and on my laptop. Here is the relevant output that demonstrates that ``list_output`` does indeed have keys:

```
galaxy.jobs.command_factory INFO 2017-07-06 17:10:56,959 Built script [/var/folders/78/zxz5mz4d0jn53xf0l06j7ppc0000gp/T/tmpT4e0m8/tmpEImqMt/tmpexXFtS/database/job_working_directory_mNpiZw/000/3/tool_script.sh] for tool command [echo "identifier is l11" > "/var/folders/78/zxz5mz4d0jn53xf0l06j7ppc0000gp/T/tmpT4e0m8/tmpEImqMt/tmpexXFtS/database/files/000/dataset_3.dat";  echo "identifier is l12" > "/var/folders/78/zxz5mz4d0jn53xf0l06j7ppc0000gp/T/tmpT4e0m8/tmpEImqMt/tmpexXFtS/database/files/000/dataset_4.dat";  echo 'ensure not empty']
```

The secret is that the output defines the attribute ``structured_like``, so the outputs are known ahead of time and can be used during command generation. They will match the corresponding inputs names. There is a bit more discussion on this here (http://planemo.readthedocs.io/en/latest/writing_advanced.html#computable-element-count). Hope this helps.
