### ISSUE TITLE
CTD v 1.0.0 missing dependencies at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4303]
**Tool Name**

CTD analysis of chemicals, diseases, or genes (Galaxy Version 1.0.0)

**MTS Repo** 

https://toolshed.g2.bx.psu.edu/repository?repository_id=1bfaeb4a59acfee8

**Error**

> Can't locate LWP/UserAgent.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /galaxy/main/migrated_tools/toolshed.g2.bx.psu.edu/repos/devteam/ctd_batch/4a32700dcaa2/ctd_batch/ctd.pl line 3.
> BEGIN failed--compilation aborted at /galaxy/main/migrated_tools/toolshed.g2.bx.psu.edu/repos/devteam/ctd_batch/4a32700dcaa2/ctd_batch/ctd.pl line 3.

**Test history**

https://usegalaxy.org/u/jen/h/test-history-ctd

ping @galaxyproject/guac @davebx

**Comment by natefoo** [comment]
This tool has no requirements tags and was last updated when migrated from Galaxy in 2013. If there is not a replacement, it should at least be updated to have a requirements on Perl, LWP::UserAgent, and HTTP::Cookies (if Conda packages for these Perl modules exist). Otherwise, I vote for removing this tool from Main.

**Comment by jennaj** [comment]
+1 to remove if doesn't work and we don't have resources to fix it

**Comment by natefoo** [comment]
It might be as simple as:

```xml
<requirements>
    <requirement type="package">perl</requirement>
    <requirement type="package">perl-libwww-perl</requirement>
    <requirement type="package">perl-http-cookies</requirement>
</requirements>
```

But someone should test that.

**Comment by jennaj** [comment]
Maybe do this on Test? After the release stuff is finalized.

We could also bring it up at next team mtg for roadmap/priority. If no one uses it, and it hasn't worked since 2013 ... maybe removing is better all around.

**Comment by jennaj** [comment]
removed from main, closing.
