### ISSUE TITLE
Memory Issues with sniffers using sniff.get_headers()

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#4319]
Using sniff.get_headers(), especially with a large `count` value can consume tremendous amounts of memory. In many cases, these sniffers are actually loading entire files into memory (as a list of lists).

For example, with a `ped` file that is 2.8G, and only 759 lines (each line after the header has >900,000 columns), some sniffers will use on the order of ~20G of RAM. A handful of the more egregious violators are 

- mothur.lower.dist, count=300
- mothur.square.dist, count=300
- mothur.ref.taxonomy, count=300
- pdb, count=300
- fastq, count=1000 (actually most of the fastq subclasses now just inherit from baseFastq without overriding `def sniff`, so this gets called a bunch of times)

however, even for the sniffers that use the default count=60, the memory usage was around 5Gish.

Any file that has a large amount of data on the first few lines is going to end up using lots of RAM several different times during the execution of `upload.py`, which is a most-likely cause behind increasing memory usage failures with the upload tool on Galaxy Main.

Current workaround is to manually set datatype during upload so that sniffing functions are not executed.

This is similar, but different, to the issue discussed here https://github.com/galaxyproject/galaxy/issues/3796 wrt setting metadata and using `sniff.get_headers()`.

**Comment by blankenberg** [comment]
A possible quick fix would be to have an `iter_headers()` method that is a generator so that only one line is stored at a time. 

This could be done by making minor modifications to `get_headers` and then having `get_headers` just return `list(iter_headers())`. 

In many cases, `iter_headers` could then be used as a drop in replacement in the afflicted sniffers.

**Comment by mvdbeek** [comment]
@blankenberg are you working on this or should I give it a try?

**Comment by mvdbeek** [comment]
Alright, I think the most severe cases should be handled in #4388, but as @blankenberg and @jmchilton noted we can still consume excessive memory with extremely long lines and we should probably cache the headers somehow. I'll remove a milestone, since this doesn't seem to be a pressing issue atm.

**Comment by natefoo** [comment]
Isn't the use of `get_headers()` pretty much undoing the point of `iter_headers()` in the first place?

**Comment by mvdbeek** [comment]
Right, the idea was to use `iter_headers` where possible

**Comment by natefoo** [comment]
Ah, I missed the part where `get_headers(count=n)` will only yield `n` times from the iterator, so as long as `count` is used, the only remaining problem is long lines.

**Comment by mvdbeek** [comment]
I think we've addressed most of this quite some time ago. For datatypes that may contain a large amount of data in the first few lines we can use `sniff_prefix` now, which will only provide a small portion of the file (and buffer it).
