### ISSUE TITLE
Update Extract Genomic DNA to v 3.0.3 at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4320]
https://toolshed.g2.bx.psu.edu/view/iuc/extract_genomic_dna/53db9cb721f1

Current version on Main is 2.2.3

Consider placing the update 3.0.3 on Test first, then reviewing, then pushing to Main?

Has one reported usage error (not confirmed with the latest version): https://biostar.usegalaxy.org/p/23896/

ping @davebx @galaxyproject/guac

**Comment by nsoranzo** [comment]
xref #636

**Comment by jennaj** [comment]
I don't think that 3.0.3 has the changes needed that would address this root problem. In short, any DM created indexes are not accessed (tool is not "data table aware"): https://github.com/galaxyproject/galaxy/issues/5493

Looks like @bernt-matthias found the same issue https://github.com/galaxyproject/galaxy/pull/5618#issuecomment-369637031

**Comment by bgruening** [comment]
@jennaj please add a dbkey to your gtf/interval file and use this tool. You will see you can access the reference genome. The tool is actually one of the rare cases that is using the dbkey to filter the reference genome list.

**Comment by jennaj** [comment]
My original test history had the dbkey assigned (I knew about this trick ;)

Captured here: https://github.com/galaxyproject/galaxy/issues/5493

Rerun still errors: https://usegalaxy.org/u/jen/h/test-history-danrer10

@blankenberg reviewed this with me earlier this month and that is how the ticket for https://github.com/galaxyproject/galaxy/issues/5493 was born.

**Comment by jennaj** [comment]
Freiburg testing here: https://github.com/galaxyproject/galaxy/pull/5618#issuecomment-370083830

@davebx @natefoo can we put the latest version on test and main and see if it resolves https://github.com/galaxyproject/galaxy/issues/5493? I don't think it is a huge risk to put directly on Main, already has serious problems with the current version.

**Comment by jennaj** [comment]
https://github.com/galaxyproject/galaxy/pull/5618

Remove old version as non-functional and replace? Is no longer in the distribution, only from MTS (migrated).

**Comment by jennaj** [comment]
Tool update for usegalaxy.org is now tracked here https://github.com/galaxyproject/usegalaxy-playbook/issues/97

Thanks for the tool fix!!! Closing this out to keep all in one place.
