### ISSUE TITLE
Using a collection [from a list of collections] as tools input

### ISSUE THREAD

**Issue by cumbof** [galaxyproject/galaxy#4324]
Currently it is not possible to use a collection as input for any tool if this collection is inside a list of collections. I have encountered this problem for the tool referring to the pull request [#1380](https://github.com/galaxyproject/tools-iuc/pull/1380) under the [tools-iuc](https://github.com/galaxyproject/tools-iuc) repository. The output of the tool is the following:

```
<collection name="list_output" type="list:list" label="${tool.name} Output Collection">
        <discover_datasets pattern="(?P&lt;identifier_0&gt;[^_]+)_(?P&lt;identifier_1&gt;[^_]+)_(?P&lt;ext&gt;[^_]+)_(?P&lt;dbkey&gt;[^_]+)" ext="auto" visible="False" directory="tmp" />
</collection>
```

@nekrut @jmchilton

**Comment by nekrut** [comment]
@jmchilton when you are here, can you talk to @fabio-cumbo about this?

**Comment by jmchilton** [comment]
@fabio-cumbo Here is the related issue I was talking about I think - https://github.com/galaxyproject/galaxy/issues/740. If you are interested in maybe trying to extend Galaxy to allow tools to output multiple collections at runtime - create another issue and I can try to flush out how to do that - but I'm not sure I'd have time to work on it myself.

**Comment by cumbof** [comment]
Thanks @jmchilton!

**Comment by jmchilton** [comment]
> If you are interested in maybe trying to extend Galaxy to allow tools to output multiple collections at runtime - create another issue and I can try to flush out how to do that - but I'm not sure I'd have time to work on it myself.

This part - allowing a dynamic number of collections - is included in #5220. If anyone is interested in writing a tool that would do this I can document how to do that as part of the PR or in a follow up.

**Comment by cumbof** [comment]
Thanks @jmchilton, it would be great if this will be documented

**Comment by mvdbeek** [comment]
I think this works for a while now, and if not 19.01 should work.
