### ISSUE TITLE
Create CPU usage section in galaxy reports.

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/galaxy#4335]
Currently in the Galaxy reports section I could not find the amount of cpu/hours per user. This is a useful feature for (internal) billing.

**Comment by hexylena** [comment]
We've added [queries for this](https://usegalaxy-eu.github.io/gxadmin/#/README.query?id=query-user-cpu-years) in `gxadmin` which may be interesting to you? With a command line tool it's probably also easier to do "billing" type things with monthly reports/etc.
