### ISSUE TITLE
Subworkflow Problems

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4338]
I'm having real issues with running subworkflows over the couple releases.

- Connecting input to md5sum to a subworkflow is not working.
- It looks like subworkflows might not work if one of the outputs is a collection.

**Comment by mvdbeek** [comment]
> It looks like subworkflows might not work if one of the outputs is a collection.

I do have that working on 17.05 (both transposon tagging subworkflows produce collections), but I have noticed that `()` in the output label crashes the workflow editor when reopening a composed workflow.

![screen shot 2017-07-24 at 4 13 39 pm](https://user-images.githubusercontent.com/6804901/28527607-5813e8da-708b-11e7-9f3b-7d772072fd57.png)

**Comment by hexylena** [comment]
> Connecting input to md5sum to a subworkflow is not working.

xref https://github.com/galaxyproject/galaxy/pull/5140 ?

**Comment by mvdbeek** [comment]
This should work now, the first item point I just tested, the second might be related to the noodle issues, for which we have separate issues.
