### ISSUE TITLE
Bugs in the interface with Google's Chrome on Ubuntu

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/galaxy#4339]
I recognized two bugs concerning chrome and the galaxy interface. 

1. In the case a job is submitted and is yellow (aka 'running'), my cpu usage is about 25% caused by this. I tested it in other browsers and there it does not happen. Tested on Ubuntu 16.04 with Chrome 59. It does not happen with Firefox on the same system.
2. If an image is opened in galaxy and it is bigger than the available space in the middle, the picture is not scaled down to fit in the available space. Instead it is displayed at full size and I need to scroll (vertical and horizontal). With Firefox the image is scaled down.

Can someone reproduce this? If yes, what could be done? 

Thanks for your help!

**Comment by blankclemens** [comment]
While I don't see this spike for a single spinning animation on Chrome with Windows, I do see a huge amount of CPU usage often for just showing the Galaxy tab.

E.g. with dozens of tabs, Chrome doesn't use a single percentage of CPU regardless which page I'm on, but as soon as I switch to the Galaxy tab it often (not always) takes 10-15% - even if I wait minutes without any interaction.

**Comment by joachimwolff** [comment]
Just want to mention that CPU usage with Chrome 62, KDE 5 and Ubuntu 17.10 is 3 - 4%. Can someone check this with the up-to-date version of Chrome on other settings? Maybe it was just a bug with Chrome 59.

**Comment by dannon** [comment]
@joachimwolff I haven't seen this, but since you have the environment to reproduce it, could you pop open the chrome developer tools and profile the cpu usage for a second or two when this behavior happens?

**Comment by hexylena** [comment]
I still see this on current chrome on linux, fwiw. I've attached profiles. Chrome running in incognito tab, no other tabs open, no other chrome instances running.

Profile screenshot, not sure how to read the crosshatched portion?

![image](https://user-images.githubusercontent.com/458683/62937847-07021380-bdce-11e9-9643-d5df8f6fb101.png)

Upload running:

![image](https://user-images.githubusercontent.com/458683/62937594-5d228700-bdcd-11e9-8052-f8a2e07d7773.png)

Upload finished:

![image](https://user-images.githubusercontent.com/458683/62937727-c0acb480-bdcd-11e9-96a5-5393b43c9289.png)

Profile:

[upload-cpu-on-chrome-linux.json.txt](https://github.com/galaxyproject/galaxy/files/3496703/upload-cpu-on-chrome-linux.json.txt)
