### ISSUE TITLE
Collection builder list of dataset pairs not working as expected

### ISSUE THREAD

**Issue by blankclemens** [galaxyproject/galaxy#4349]
I tried to build a collection list of dataset pairs (paired end reads) and wonder if I just do it wrong, or if there is some intuitive functionality missing - tested on latest dev version:

I thought if I filter the left and right tables to the same amount of files, it shouldn't require much logic to just combine them with `Auto-pair` - however, this doesn't work:

![paired_collection_1](https://user-images.githubusercontent.com/12255194/28676824-fe362734-72eb-11e7-9d95-8fa60e46b3c5.png)

To avoid other conflicts, I filtered even more, with the same result:

![paired_collection_2](https://user-images.githubusercontent.com/12255194/28676826-014319a0-72ec-11e7-9b54-6f7343785d38.png)

Is this intended, am I using it wrong? I ended up clicking `Pair these datasets` around 500 times, which worked better than it sounds, seems like it queues the clicks (finally putting my esport skills to good use).

**Comment by mvdbeek** [comment]
I tried your example, it seems it just doesn't reach the score threshold for matching ... I was able to set https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/collection/list-of-pairs-collection-creator.js#L208 to 0.6, recompile the client javascript (`make client`) and then your example worked. Alternatively you can also increase the length of the input dataset names ... which doesn't make a lot of sense as a workaround.

![screen shot 2017-07-27 at 5 47 37 pm](https://user-images.githubusercontent.com/6804901/28679760-813303e8-72f4-11e7-9b91-93dba609dd66.png)

**Comment by mvdbeek** [comment]
@jmchilton do you think setting the score threshold lower is a possibility ? Or perhaps we could have a slider in the collection builder and expose this to the user with a warning that there could be mismatches ?

**Comment by blankclemens** [comment]
Yes, with `0.6` it works for me too - sadly I cannot change this value on the productive instance. I could see three solutions:

- lowering the value by default
- expose this value to the user or
- give an option that it will do the `Pair these datasets` for all - so that the user has to make sure he used the right filtering but then doesn't have to click it multiple times

**Comment by jmchilton** [comment]
@mvdbeek I'm fine with lowering this value - sounds like a good idea.

**Comment by blankclemens** [comment]
Since this is quite a useful change, could we add this to the 17.09 milestone?

**Comment by jmchilton** [comment]
I'll open a PR for this right now.

**Comment by blankclemens** [comment]
Thanks!
