### ISSUE TITLE
Galaxy Tours: is 'preclick' still working? 

### ISSUE THREAD

**Issue by hrhotz** [galaxyproject/galaxy#4354]
Hi 
I am struggling to get 'preclick' to work....Though, when I was checking the functionality using the "History Introduction" Tour locally, on main, and on the Freiburg galaxy server, I realized it is also not working. In particular, the 'preclick' on the information symbol, the eye symbol, the pencil button, does not seem to work.
Is it broken? or do I miss something?

Regards, Hans-Rudolf

**Comment by hrhotz** [comment]
looks like it is now working again (at least on usegalaxy.org)

**Comment by dannon** [comment]
@hrhotz Sorry I missed this issue when you posted it!  Let me know if you have any more problems with Tours.

**Comment by hrhotz** [comment]
@dannon no worries. I was looking at it with @bgruening yesterday and all worked as expected. I will check on our local server next week, once I have updated to 17.09 on Monday
