### ISSUE TITLE
Standardize "Public Name" label on all Galaxy GUI forms

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4359]
**Username** is the label for the value on the account login form.

**Public name** is the label for the value on the account registration form.

**Public name** is the label for the value once logged in and User > Preferences is reviewed and/or modified.

**All should be "Public name"** - to clearly distinguish between "username" that is common nomenclature in FTP clients where the account email address is the expected input. There may be other places in the Galaxy GUI where "[U/u]sername" is present - the intention of this change is to make all consistently labeled as "[P/p]ublic name"

**Comment by nsoranzo** [comment]
The use of the email address is allowed in the login form, so maybe this could be changed to "Public name/email"?

**Comment by jennaj** [comment]
ping @dannon 

See the linked ticket for screenshots everywhere I could find it. 

We probably need to check registration & password reset emails to make sure consistent in those as well.

**Comment by jennaj** [comment]
Any chance this could get into 19.05?

@jmchilton potential project this week?

**Comment by jmchilton** [comment]
This doesn't seem high priority to me. The inconsistency is a bug though so we in theory could fix it at any time and patch 19.05.

**Comment by jennaj** [comment]
Wow -thanks all!
