### ISSUE TITLE
Enforce tool profile across tool shed and galaxy

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#4361]
This came up during the GCC (and the last GCC as well, I think ...).
Tool authors should be able to specify a minimum version of galaxy that is required to run a tool.
We already have the [profile atribute](https://docs.galaxyproject.org/en/master/dev/schema.html#attributes), but currently galaxy instances will happily load tools regardless of the tool profile version, and the tool shed will not block or notify admins that a minimum galaxy version is required.

We can probably not rely on this retroactively, but we should have a mechanism in place so that in the future we can change certain defaults.

So what I would propose is that galaxy refuses to load a tool with a profile version higher than the running galaxy version, and that the toolshed installation process will inspect a repository for the minimum required galaxy version.

**Comment by nsoranzo** [comment]
:+1:

**Comment by mvdbeek** [comment]
I realize now this is a duplicate of #2086 ...
