### ISSUE TITLE
Implement API for datatype changes

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#4363]
xref https://github.com/galaxyproject/bioblend/issues/243

**Comment by mvdbeek** [comment]
This is probably a little tricky, since (at least how we do it currently), you'd need to make sure no running job is using this dataset. ping @erasche

**Comment by martenson** [comment]
I am implementing an API that will change datatype of a library dataset. This, however, does not affect the underlying dataset I believe.

**Comment by hexylena** [comment]
@mvdbeek currently there's an error if you try to reset the datatype of a running job, right? If so I'm not sure what the issue is, I assume the api would return an error as well. It is up to the user to check that it isn't running.

**Comment by mvdbeek** [comment]
No, the UI will prevent you from doing this. But yeah, the API could of course do the same.

**Comment by simonbray** [comment]
Hey, was any progress made on this?

**Comment by nsoranzo** [comment]
As I was mentioning on the bioblend Gitter channel, I think this could be  implemented for both history and library datasets by adding a deserializer for `'extension'` to `DatasetAssociationDeserializer.add_deserializers()` in `lib/galaxy/managers/datasets.py`

**Comment by simonbray** [comment]
I tested out @nsoranzo's solution and it seems to work. Any objection if I make a PR? I have over a thousand datasets which need updating so really need this feature. :)

**Comment by nsoranzo** [comment]
@simonbray Absolutely, go for it! PRs are the best way to get feedback on an implementation idea.
