### ISSUE TITLE
implicit conversions do not work with collections

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#4364]
During our workshop we had one participant that tried to use collection in the following workflow.

FASTQ -> BWA (SAM file) -> idxstats

idxstats only takes BAM files as input, which works in non-collection mode as Galaxy internally converts the datasets (I suppose). This does not work for collections, no dataset is offered in the UI at least for the tool idxstats.

**Comment by jmchilton** [comment]
Yes this is a deficiency of collections - this was on like the original Trello card for collection followups but no one ever complained too loudly I don't think. I'm sure we could just let Galaxy create a bunch of uncollected implicitly converted datasets - but given the originals are in a collected state I'm not sure this would be best. If it at all possible I would prefer a workflow that explicitly converted the data until this has been thought through.

**Comment by bgruening** [comment]
Is it hard to run the auto-convert tools as an intermediate step and just hide the collection that is produced inbetween?

**Comment by mvdbeek** [comment]
We should start working on this, it's one of the last issues with collections, xref https://github.com/galaxyproject/galaxy/issues/4654#issuecomment-330877175

**Comment by mvdbeek** [comment]
For reference I started some work here: https://github.com/galaxyproject/galaxy/compare/dev...mvdbeek:implicit_conversion_for_dataset_collections?expand=1

Turns out that at least for mapping over operations the API already supports implicit conversions. I had some more important things intervening, but I'll pick this up again for 18.05 unless someone beats me to it.

**Comment by mvdbeek** [comment]
This should be fixed with https://github.com/galaxyproject/galaxy/pull/6144!
