### ISSUE TITLE
Selection of element_identifier source for mapped-over matched dataset collections unspecified

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#4366]
Take a tool that has two inputs (`inputA` and `inputB`) that are regular inputs and connect two separate dataset collections of identical structure to the inputs. These collections will be matched and we get 1 output per element, but which collection will be the source of the element identifiers?

This happens to be the collection connected to `inputB` in https://github.com/galaxyproject/tools-iuc/blob/master/tools/bedtools/windowBed.xml, even though this is not explicitly defined, and since the `metadata_source` and `format_source` point to inputA, it should have probably been `inputA`.

So, should we infer this from `metadata_source` and `format_source` ? Should we introduce a new attribute to specify this explicitly (`identifier_source` perhaps) ?

**Comment by jmchilton** [comment]
I've always wished this were available in the tool form as an option - how should mapping occur - "use input param 1", "use input param 2", "require identifiers match", "supply a regex", etc....  Should this really be a property of the tool and not a property that is set by the user - I'd argue in most cases no?

So maybe make the property ``default_identifier_source`` - so it opens the possibility of doing this in the GUI down the road? Or if we just switched the behavior to use first input being mapped over would that be a sensible enough default for most common tools and let us muddle through until this option is available in the GUI?

**Comment by mvdbeek** [comment]
> I've always wished this were available in the tool form as an option - how should mapping occur - "use input param 1", "use input param 2", "require identifiers match", "supply a regex", etc.... Should this really be a property of the tool and not a property that is set by the user - I'd argue in most cases no?

Yes, that would be great.

> So maybe make the property default_identifier_source - so it opens the possibility of doing this in the GUI down the road? Or if we just switched the behavior to use first input being mapped over would that be a sensible enough default for most common tools and let us muddle through until this option is available in the GUI?

To be honest I have only experienced this with tools from the bedtools suite (but e.g deseq2 should have similar problems, I didn't test that though)  ... it's kind of tempting to just go with the first input, since I wouldn't need to change the tools. But then the output identifiers may change when upgrading galaxy, while a separate tag would allow us to bump the tool version ... and a default may be useful even if at some point we have the UI.

**Comment by jmchilton** [comment]
> But then the output identifiers may change when upgrading galaxy

Yeah - but the current default behavior is kind of terrible if it really is use the last input or something worse like a random input 😓.

You can add the tag - that is totally fine with me - like you say it can even be useful when there is a GUI for modifying these options. It is just a really subtle thing.
