### ISSUE TITLE
Automatically build and test new versions of wheels

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#437]
We want to update to new _minor_ versions of our dependency packages whenever they become available, and this needs to be automated or else it will never be done on a reasonable time frame.

@jxtx suggested pinning to an exact version of dependencies but automatically running Galaxy unit tests for new versions and committing the version change if tests pass. Ideally we'd just do this with Travis.

xref #428

**Comment by hexylena** [comment]
:+1:

**Comment by natefoo** [comment]
Dependency versions are now being regularly updated with pipenv.
