### ISSUE TITLE
Too hard to customize galaxy top bar

### ISSUE THREAD

**Issue by seahurt** [galaxyproject/galaxy#4372]
I found that if I want to change the navi bar, like the words of the menu or the brand title, I have to change the js file. I have to change the js file in ./client, and run grunt command then restart the server. It takes me half a day just to change a single string... Do you think it is reasonable？Or there just exists a super simple method that I have missed? After all, I am not a front end programmer.

**Comment by bgruening** [comment]
@seahurt you can change the brand by simply changing this config variable in your galaxy.ini: https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.ini.sample#L581

For more customizations you can use Galaxy webhooks. For more information please see: https://docs.galaxyproject.org/en/latest/admin/webhooks.html

**Comment by mvdbeek** [comment]
You can set the brand in https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.ini.sample#L581

To rebuild the client, you can do `make client` form galaxy's source directory, or to list for changes in live you'd do `make webpack-watch` and `make grunt-watch-develop`. You never need to restart galaxy if you change JS or mako files.

**Comment by mvdbeek** [comment]
Also you need to refresh the browser cache ...

**Comment by seahurt** [comment]
Thanks. I know what you mean. But I think the content should be separated with the logical part. Using an easy-modified temple file may be better?

**Comment by mvdbeek** [comment]
I think for most people modifying the brand in galaxy.ini is sufficient. If you have any concrete suggestions we're happy to look into it and we always welcome PRs.
