### ISSUE TITLE
scripts/extract_dataset_part.py missing six

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#4381]
As part of a TravisCI test run using the Galaxy dev branch (where I am trying to switch to conda for my tool dependencies), I had this failure:

https://travis-ci.org/peterjc/galaxy_blast/jobs/261852287

```
======================================================================
FAIL: NCBI BLAST+ blastn ( ncbi_blastn_wrapper ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/test/functional/test_toolbox.py", line 302, in test_tool
    self.do_it( td )
  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/test/functional/test_toolbox.py", line 78, in do_it
    raise e
JobOutputsError: Job in error state.
Job in error state.
-------------------- >> begin captured stdout << ---------------------
History with id 3777da040b354424 in error - summary of datasets in error below.
--------------------------------------
| 3 - megablast rhodopsin_nucs.fasta vs 'three_human_mRNA.fasta'
 (HID - NAME) 
| Dataset Blurb:
|  error
| Dataset Info:
|  Fatal error:
|  /tmp/tmp8JSldT/job_working_directory/000/68/task_0:
|  Traceback (most recent call last):
|  File "./scripts/extract_dataset_part.py", line 17, in <module>
|  import galaxy.model.mapping  # need to load this before we unpickle, in order to se
| Dataset Job Standard Output:
|  *Standard output was empty.*
| Dataset Job Standard Error:
|  Fatal error:
|  /tmp/tmp8JSldT/job_working_directory/000/68/task_0:
|  Traceback (most recent call last):
|  File "./scripts/extract_dataset_part.py", line 17, in <module>
|  import galaxy.model.mapping  # need to load this before we unpickle, in order to setup properties assigned by the mappers
|  File "/home/travis/build/peterjc/galaxy_blast/galaxy-dev/lib/galaxy/model/__init__.py", line 21, in <module>
|  from six import string_types
|  ModuleNotFoundError: No module named 'six'
|
--------------------------------------
```

Strangely ``six`` is being installed and is listed in ``lib/galaxy/dependencies/requirements.txt`` etc.

Is there something special about the context in which Galaxy's ``scripts/extract_dataset_part.py`` gets run which does not use the same Python virtual environment?

**Comment by mvdbeek** [comment]
Are you somehow importing from galaxy or from galaxy's datatypes ? This does not happen for 17.05 ?

**Comment by peterjc** [comment]
I don't call ``extract_dataset_part.py`` directly in any of my code, which is why I suspect this is a Galaxy issue somewhere.

I do however attempt to manually install/replace the BLAST datatypes if present in the Galaxy branch being tested:

https://github.com/peterjc/galaxy_blast/blob/33cdcdc4b898fdb0a8e7a74fbed75a75764edf25/.travis.yml#L110

**Comment by mvdbeek** [comment]
Hmm, it looks like the testing uses parallelism from the log output (`job_working_directory/000/68/task_0`), but I can't find this in your wrappers.
We did change the `Task` object in https://github.com/galaxyproject/galaxy/pull/4375/commits/faee2b65c29ee405d475d54a630d54c7b29a4159 ... maybe self.parent_job.parameters was actually correct ? :/

**Comment by mvdbeek** [comment]
Ah, wait, you are actually using `parallelism` .... hmmm, I'm not sure if we fixed or broke it though.

**Comment by nsoranzo** [comment]
I thought `parallelism` is used only if `use_tasked_jobs` is set to `True` in `config/galaxy.ini` , which doesn't seem to be the case in https://github.com/peterjc/galaxy_blast/blob/33cdcdc4b898fdb0a8e7a74fbed75a75764edf25/.travis.yml#L110

**Comment by mvdbeek** [comment]
interesting, that would explain why I can't reproduce it. But I think one problem is that the task splitting is injected with the regular command, while it needs access to the datatypes, which need galaxy's virtualenv.

**Comment by mvdbeek** [comment]
fwiw, this is the command I see with blastn and activated `use_tasked_jobs`:
```
galaxy.jobs.command_factory INFO 2017-08-07 20:36:24,976 Built script [/Users/mvandenb/src/galaxy/database/jobs_directory/000/460/task_0/tool_script.sh] for tool command [[ "$CONDA_DEFAULT_ENV" = "/Users/mvandenb/miniconda3/envs/__blast@2.5.0" ] ||
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . /Users/mvandenb/miniconda3/bin/activate '/Users/mvandenb/miniconda3/envs/__blast@2.5.0' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done ; /Users/mvandenb/src/galaxy/extract_dataset_parts.sh /Users/mvandenb/src/galaxy/database/jobs_directory/000/460/task_0; blastn -query '/Users/mvandenb/src/galaxy/database/jobs_directory/000/460/task_0/dataset_483.dat'  -subject '/Users/mvandenb/src/galaxy/database/jobs_directory/000/460/task_0/dataset_484.dat'  -task megablast -evalue 0.001 -out '/Users/mvandenb/src/galaxy/database/jobs_directory/000/460/task_0/dataset_488.dat' -outfmt '6 std sallseqid score nident positive gaps ppos qframe sframe qseq sseq qlen slen salltitles'  -num_threads "${GALAXY_SLOTS:-8}" -strand both -dust yes]
g
```

Which would mean that the `extract_dataset_part.py` script would be run in the conda environment -- which it should not. Despite this it appears to work on my dev instance, probably because six happens to be in my conda environment.

So the question is ... why does @peterjc's travis setup use task splitting ? Did you perhaps set an environment variable for this ?

**Comment by peterjc** [comment]
We have use_tasked_jobs set locally so using it on my Travis setup would be a good idea for my own tool testing...

**Comment by jmchilton** [comment]
Still digesting this but it is kind of related to dependency issues in https://github.com/galaxyproject/galaxy/pull/1816.

**Comment by jmchilton** [comment]
This might fix it - anyone have an easy test setup to apply this in? 
 https://github.com/galaxyproject/galaxy/commit/aa29b3a1a18d9ee528bd33e58eb2cd8ff180f544

**Comment by mvdbeek** [comment]
I think this is correct, this would be the command with the fix applied:
```
/Users/mvandenb/src/galaxy/extract_dataset_parts.sh /Users/mvandenb/src/galaxy/database/jobs_directory/000/462/task_0; [ "$CONDA_DEFAULT_ENV" = "/Users/mvandenb/miniconda3/envs/__blast@2.5.0" ] ||
MAX_TRIES=3
COUNT=0
while [ $COUNT -lt $MAX_TRIES ]; do
    . /Users/mvandenb/miniconda3/bin/activate '/Users/mvandenb/miniconda3/envs/__blast@2.5.0' > conda_activate.log 2>&1
    if [ $? -eq 0 ];then
        break
    else
        let COUNT=COUNT+1
        if [ $COUNT -eq $MAX_TRIES ];then
            echo "Failed to activate conda environment! Error was:"
            cat conda_activate.log
            exit 1
        fi
        sleep 10s
    fi
done ; blastn -query '/Users/mvandenb/src/galaxy/database/jobs_directory/000/462/task_0/dataset_483.dat'  -subject '/Users/mvandenb/src/galaxy/database/jobs_directory/000/462/task_0/dataset_484.dat'  -task megablast -evalue 0.001 -out '/Users/mvandenb/src/galaxy/database/jobs_directory/000/462/task_0/dataset_490.dat' -outfmt '6 std sallseqid score nident positive gaps ppos qframe sframe qseq sseq qlen slen salltitles'  -num_threads "${GALAXY_SLOTS:-8}" -strand both -dust yes
```

I didn't have @peterjc's issue, but this looks like a solid improvement regardless.

**Comment by nsoranzo** [comment]
@peterjc Sorry for asking again, is job splitting somehow configured already in your Travis config? Otherwise I don't understand how you encountered the bug on Travis.

**Comment by peterjc** [comment]
@nsoranzo I do not believe my TravisCI setup where this showed up (currently a branch where I switched from manually installing BLAST to using conda for dependencies) is using parallelism via ``use_tasked_jobs = True`` in ``config/galaxy.ini``

https://github.com/peterjc/galaxy_blast/blob/33cdcdc4b898fdb0a8e7a74fbed75a75764edf25/.travis.yml#L110

excerpt:

```yaml
before_install:
 - ...
 - echo "Fetching Galaxy ${GALAXY_BRANCH} branch..."
 - cd ${TRAVIS_BUILD_DIR}
 - wget https://codeload.github.com/galaxyproject/galaxy/tar.gz/${GALAXY_BRANCH}
 - tar -zxvf ${GALAXY_BRANCH} | tail
 - cd galaxy-${GALAXY_BRANCH}

install:
 - cd ${TRAVIS_BUILD_DIR}/galaxy-${GALAXY_BRANCH}
 - export GALAXY_TEST_UPLOAD_ASYNC=false
 - export GALAXY_TEST_DB_TEMPLATE=https://github.com/jmchilton/galaxy-downloads/raw/master/db_gx_rev_0127.sqlite
 - rm -f lib/galaxy/datatypes/blast.py
 - ln -s ${TRAVIS_BUILD_DIR}/datatypes/blast_datatypes/blast.py lib/galaxy/datatypes/blast.py
 - ln -s ${TRAVIS_BUILD_DIR}/.travis.datatypes_conf.xml datatypes_conf.xml
 - bash scripts/common_startup.sh --no-create-venv --dev-wheels

script:
 - cd ${TRAVIS_BUILD_DIR}
 - planemo --version
 - planemo test --conda_dependency_resolution --galaxy_root ${TRAVIS_BUILD_DIR}/galaxy-${GALAXY_BRANCH} --skip_venv tools/
```

Should I not be using ``--skip_venv`` with ``--conda_dependency_resolution``?

Curiously the Galaxy ``dev`` branch gives the missing ``six`` error, but the Galaxy ``master`` branch just seemed to time out somewhere - I have not (yet) attempted to re-run this TravisCI job:

https://travis-ci.org/peterjc/galaxy_blast/jobs/261852286

**Comment by nsoranzo** [comment]
I've finally found out that `use_tasked_jobs` is not enabled by Planemo, but by Galaxy test framework in https://github.com/galaxyproject/galaxy/blob/dev/test/base/driver_util.py#L201 . So `planemo test` always runs with task splitting enabled and the TaskedJobRunner with 2 workers are loaded. @jmchilton correct?

**Comment by jmchilton** [comment]
@nsoranzo Yes - I knew it was enabled for the framework tests it didn't occur to me that tools were using the same framework - but obviously they do so that was silly of me not to realize right away. Good catch.

**Comment by peterjc** [comment]
Excellent detective work @mvdbeek, @nsoranzo - its very useful to know the parallel setting is getting used routinely in some setups 👍  - and thank you for the quick fix @jmchilton

**Comment by nsoranzo** [comment]
@peterjc Is this fixed on Travis now for the dev branch?

**Comment by peterjc** [comment]
Trying again with a rebased branch: https://travis-ci.org/peterjc/galaxy_blast/builds/262612654

(I could have re-run the failed TravisCI build, but that would replace the interesting log of the failure)

**Comment by peterjc** [comment]
https://travis-ci.org/peterjc/galaxy_blast/builds/262612654 finished.

Good news: ``ModuleNotFoundError: No module named 'six'`` fixed when testing against Galaxy ``dev`` branch.

Bad news: Getting ``ModuleNotFoundError: No module named 'six'`` problem when testing against Galaxy ``master`` branch. However, the build timed out in the initial report, so this is probably not a new issue.

Does #4383 need back porting to master and/or any recent releases?
