### ISSUE TITLE
Filezilla sends commands that abort a connection when set to FTP Active mode

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4384]
**Passive mode within Filezilla app** = TSL connection, no problems with dir listings

**Active mode within Filezilla app** == TSL connection, then connection failure when dir listings are requested (is a default action). Is there a way to mitigate the problem with the MLSD command?

ping @natefoo 

> Status:       	Resolving address of usegalaxy.org
> Status:       	Connecting to XXX
> Status:       	Connection established, waiting for welcome message...
> Status:       	Initializing TLS...
> Status:       	Verifying certificate...
> Status:       	TLS connection established.
> Status:       	Logged in
> Status:       	Retrieving directory listing...
> Command: 	PWD
> Response: 	257 "/" is the current directory
> Command: 	TYPE I
> Response: 	200 Type set to I
> Command: 	PORT 10,0,0,7,235,90
> Response: 	200 PORT command successful
> Command: 	MLSD
> Error:         	Connection timed out after 20 seconds of inactivity
> Error:         	Failed to retrieve directory listing
> Status:       	Disconnected from server
> Status:       	Resolving address of usegalaxy.org
> Status:       	Connecting to XXX
> Status:       	Connection established, waiting for welcome message...
> Status:       	Initializing TLS...
> Status:       	Verifying certificate...
> Status:       	TLS connection established.
> Status:       	Logged in
> Status:       	Retrieving directory listing...

^^ This never resolves. Disconnects eventually, after looping.

**Notes**
 - Example biostars post: https://biostar.usegalaxy.org/p/24299/#24301
 - Filezilla-specific help updated in hub: https://galaxyproject.org/ftp-upload/#upload-from-client

**Comment by natefoo** [comment]
Active mode is not going to work for most people, it requires that your client host be able to open random ports to the internet. This means it won't work for anything that uses NAT and most hosts that are behind a firewall. Passive mode was created to solve this problem and should work for 99% of users.

If active mode does not work for a particular user, that's not something we can fix.

**Comment by jennaj** [comment]
Ok - let's close this out then. Passive should be used.
