### ISSUE TITLE
Additional configuration on local instance needed to run BWA (or NGS mappers in general)?

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/galaxy#4393]
Hi Galaxy Community! 
Hope everyone is doing very well!

I'd like to run BWA (and other mapping tools) on a local Galaxy instance and am running into an error. After installing Galaxy using the command under [cloning new](https://galaxyproject.org/admin/get-galaxy/#for-production-or-single-user) (or installing the latest [Galaxy-Docker-NGS-Preprocessing](https://github.com/bgruening/docker-galaxy-ngs-preprocessing)) and installing BWA from the toolshed when I run very minuscule dataset I get the error:

The Galaxy framework encountered the following error while attempting to run the tool:

```
Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/jobs/runners/__init__.py", line 630, in finish_job
    job_state.job_wrapper.finish( stdout, stderr, exit_code )
  File "/galaxy-central/lib/galaxy/jobs/__init__.py", line 1266, in finish
    dataset.datatype.set_meta( dataset, overwrite=False )
  File "/galaxy-central/lib/galaxy/datatypes/binary.py", line 391, in set_meta
    exit_code = subprocess.call( args=command, stderr=open( stderr_name, 'wb' ) )
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Tool execution generated the following error message:
`Unable to finish job`

I get the same error when trying to use Bowtie2.

The same dataset runs through BWA successfully on Main ([shared history here](https://usegalaxy.org/u/mheydarian/h/sample-data-tiny-for-testing-bwa)). 

Are there some additional parameters that need to be configured to get a local or Docker based Galaxy instance to run mapping jobs? 

Thanks in advance for any guidance. 

Hope things are groovy for all ;)

Cheers,
Mo

**Comment by mvdbeek** [comment]
You'll need samtools, I suppose. You can install this globally on that machine, or if you're running 17.05, you can go to "Manage tool dependencies" in the admin section and install the dependencies for `Set External Metadata`.

**Comment by mvdbeek** [comment]
We should put this information right up there ... do you want to give this a try ?

**Comment by MoHeydarian** [comment]
Thanks @mvdbeek, that fixed the issue! 

Closing the issue.
