### ISSUE TITLE
Interactive Environment, Why environment variables are uppercased

### ISSUE THREAD

**Issue by xgaia** [galaxyproject/galaxy#4402]
Hello everyone,

I'am working on an interactive environment and i need to pass environment variables to my docker.

When an IE is lauched, the environment variables can be set with `env_override` But why they are uppercased ? [(here)](https://github.com/galaxyproject/galaxy/blob/ecf634a619e93ffe98b5b785e3de10125940adce/lib/galaxy/web/base/interactive_environments.py#L256)

My app needs case sensitive variables and I can't use them. Is there a special reason to uppercase the variables ?

**Comment by hexylena** [comment]
Because most environment variables are upper cased, as is historical. We could probably add some way to opt-out of this upper casing.

**Comment by xgaia** [comment]
Thanks @erasche for your answer

I propose [this](https://github.com/galaxyproject/galaxy/pull/4454) PR to add the functionality
