### ISSUE TITLE
GetFastaBed fails to retrieve data for non-DM genomes

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4412]
Tool is looking for input where it will not exist for any genome created without a DM. More details below with error/command-line. 

**Tool**: GetFastaBed v 2.26.0.0 (updated 2017-07-05, IUC tool)

**Tool repo**: https://toolshed.g2.bx.psu.edu/view/iuc/bedtools/b73962f8fcbf

**Test history, mm10 + mm9 fail, hg38 success, all success with Extract**: https://usegalaxy.org/u/jen/h/test-history-getfastabed

**Command line for successful hg38**
`bedtools getfasta     -fi '/galaxy/data/hg38/seq/hg38.fa' -bed '/galaxy-repl/main/files/020/919/dataset_20919268.dat' -fo '/galaxy-repl/main/files/020/919/dataset_20919271.dat'`

**Command line for UNsuccessful mm9**
`bedtools getfasta     -fi '/galaxy/data/mm9/seq/mm9.fa' -bed '/galaxy-repl/main/files/020/919/dataset_20919426.dat' -fo '/galaxy-repl/main/files/020/919/dataset_20919491.dat'`

**Error for UNsuccessful mm9**
```
Fatal error: Exit code 1 ()
index file /galaxy/data/mm9/seq/mm9.fa.fai not found, generating...
could not open index file /galaxy/data/mm9/seq/mm9.fa.fai for writing!
```

The file 'mm9.fa.fai' will not exist in this location (will be nested under /galaxy/data/mm9/samtools) for any genome not created with a Data Manager. Non-DM data is most of the content at http://usegalaxy.org.

Extract is fine because it accesses the loc for 2bit data.

**Should this ticket be against the tool repo (to expand where it looks for the input, the samtools loc is one option, but could have own loc or ??) or should we create symlinks in our data?**. The concern with just adding symlinks is that users also sometimes add in data without DMs (example: if getting from rsynch). A more robust tool might be the best solution.

ping @natefoo @davebx

**Comment by mvdbeek** [comment]
That's a problem with the tool, it should symlink to the working directory, since the `all_fasta` table typically doesn't contain indexes. That said, the datamanager should also create the fasta index.
@jennaj Can you open this on the IUC repo ?
