### ISSUE TITLE
HTML titles mismatch

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4416]
When quickly poking around I found:

|location|17.05 | dev|
|-|-|-|
|main admin page|`Galaxy Administration`|`Galaxy`|
|workflow list|`Workflow home`|`empty`|
|workflow canvas|`Galaxy`|`Galaxy \|`|
|published histories list|`Galaxy \| Published histories`|`Galaxy`|

I believe this is at least partially caused by https://github.com/galaxyproject/galaxy/pull/4272

ping @erasche

**Comment by hexylena** [comment]
progress

- [ ] main admin page - won't accept my title changes for some reason. the title is correct in template but not being rendered
- [ ] workflow list - not yet sure how to fix this one since it is all JS now
- [x] workflow canvas
- [ ] history list

**Comment by hexylena** [comment]
the common theme seems to be "removed mako => broken window titles". so, not entirely my fault. At least one I can fix though. If there are suggestions for attacking the next ones, I'd be happy to implement them. I don't seem to see the brand passed along in the Galaxy object but I may be wrong.

**Comment by bgruening** [comment]
ping @anuprulez @guerler

**Comment by anuprulez** [comment]
I will have a look at the title of the workflow page - the difference in 17.05 and dev. thanks

**Comment by martenson** [comment]
I am adding this to the 17.09 milestone since I think it would be bad to ship these ux flaws.

**Comment by anuprulez** [comment]
As we are going from mako to pure JS, we can update the HTML titles in `galaxy/scripts/apps/analysis.js` for the corresponding routes like published histories, workflow list and so on.

`window.document.title = title_text`

Analysis.js file serves the starting point for loading the resources which belong to a route. I think it would good to have the correct titles here. Moreover, we can include the localization for these texts as well. But, I could not find the corresponding text (translated versions in different languages) in the locale files. 

@martenson @erasche @guerler @bgruening
