### ISSUE TITLE
trinity_psc v 0.0.1 (Trinity at http://usegalaxy.org) fails with green datasets with fasta input

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4418]
**MTS repo:** https://toolshed.g2.bx.psu.edu/view/nate/trinity_psc/1de64ac61b4e

ping @natefoo this tool is sourced from your github repo. Would you rather have the ticket there?

**Usage problem:**

Tool assumes that input is `fastq`, however tool form allows the input of `fasta` datasets. This is close but not quite a "bug", yet does impact usability and seems important. Several users have reported the problem/error and we might be able to check our logs to see how many actual times it has occurred.

`trinityrnaseq.xml` has the lines for determining the input type commented out. There is nothing on the tool form that indicates that only `fastq` input is accepted and fasta datatypes are listed in the input filtered select menu. When `fasta` is given, the results are an empty result file and comments in the log file about the inputs not passing basic QA (the count checks for this are running on the assumption the input is `fastq`). If the job failed (as it did), it should be red and not green.

**Example history:** https://usegalaxy.org/u/jen/h/test-history-trinity-fasta-input-problem

**Suggested solution options:**

1. Modify the input select so that only `fastq` inputs are shown/available. This is the simple solution and probably enough for now.
2. OR Modify the script to detect if `fastq` vs `fasta` input is given and pass that to PSC Bridges in the command line. The tool works with both inputs command-line. Not sure about the Bridges service...

**This does not seem like a good solution:**

3. Leave wrapper code alone and put something in the help comments or in the support FAQs that the only valid inputs are `fastq` datasets.

**Whichever is decided, this should be an enhancement before taken out of Beta:**

4. Have true errors come back into the history as red datasets. The log with the error trace should still be readable by users for troubleshooting.

**Comment by natefoo** [comment]
@davebx is working on merging this wrapper with the vastly improved IUC version, which should address this issue.

**Comment by natefoo** [comment]
It's in galaxyproject/tools-devteam#486

**Comment by mvdbeek** [comment]
This is a fairly old issue, there's an IUC version of the tool and in general this doesn't seem to be a Galaxy issue.
