### ISSUE TITLE
upload modal and switching history

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#442]
@jennaj just showed me that while uploading 12 files through upload dialogue on the cloud she encountered a bug. When you switch history let's say after 5 files are added to the history the remaining 7 files will be added to the new history instead. 

This is probably a bug. @guerler

**Comment by guerler** [comment]
This issue has been fixed. @jennaj can you re-test?

**Comment by jennaj** [comment]
Yes, I can test. Main and a cloud current with latest release? Or wait for 16.01?
