### ISSUE TITLE
Prototype published history grid using Vue.js

### ISSUE THREAD

**Issue by jxtx** [galaxyproject/galaxy#4425]
To evaluate Vue.js for #4424 we will implement the Published History grid using Vue.js and the technologies described therein. 

- [ ] Determine appropriate API endpoints for grid
- [ ] Specify these endpoints on OpenAPI
- [ ] Determine how to generate models and API access layer from OpenAPI specification
- [ ] Create Vue.js component for Grid
   - [ ] Nested component for ratings?
   - [ ] Nested component for tags?
   - [ ] Nested component for search?

**Comment by guerler** [comment]
I looked a little bit more into it, and I think that we should start with the workflows selection grid i.e. http://127.0.0.1:8080/workflow. It is already API-driven and decoupled from the other grids. The benefits would be that 1) we could prototype vue-code as soon as the webpack upgrade is in dev, 2) the other grids would not be forked into a third grid variation and 3) can be transformed all together once we completed the grid mako removal. This would not necessarily effect the items on the checklist above, fyi.

**Comment by bgruening** [comment]
@guerler we have implemented testing for the "Published History grid" in https://github.com/galaxyproject/galaxy/issues/4425 and will do "workflows selection grid" next. Ok?

**Comment by mvdbeek** [comment]
I am working on the workflow grid in https://github.com/galaxyproject/galaxy/pull/4476 (need to update the PR with my local changes) changing quite a few things. I think I could include the tests in there.

https://github.com/galaxyproject/galaxy/pull/4502 looks great, nice example PR to see how to implement these tests.

**Comment by bgruening** [comment]
@jxtx small tiny example: https://github.com/galaxyproject/galaxy/pull/4593

**Comment by guerler** [comment]
Adding @dannon since he wants to work on this afaik. Please correct if there is a misunderstanding.

**Comment by dannon** [comment]
We can probably just close this one out, since we've talked about this at length, elsewhere.  The workflows list is going to be the grid prototype, and has been discussed in #5469.

I'll copy relevant details there, now.
