### ISSUE TITLE
quota API seems to be broken in dev

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#4441]
Galaxy Docker testing disclose a potential regression with the latest changes to the quota API.

For more information please see here and the bioblend test that we run:
https://travis-ci.org/bgruening/docker-galaxy-stable/builds/265334821

@guerler can this be with your latest grid changes?

**Comment by mvdbeek** [comment]
Is that still an issue ? The last build seems to have timed out, but there was also an issue [here](https://travis-ci.org/bgruening/docker-galaxy-stable/jobs/266609707#L4576)

**Comment by guerler** [comment]
Possibly, I look into it. Thanks for reporting.
