### ISSUE TITLE
Uploading UTF16 encoded files gives proxy error

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#4442]
A user on our local galaxy instance tried to upload an UTF16 encoded fasta file (the linux file tool tells me that it's "Little-endian UTF-16 Unicode text, with CRLF line terminators"). What happens is that the upload progress bar goes to 100%, but no data set is added to the history, instead a Proxy error 502 is mentioned in the upload dialog. The logs seem to contain no information that there is a problem. 

I provide a small test data set (and hope that the encoding is not changed when uploading to github ..). 

When I convert the file to ASCII (iconv -f UTF16 -t ASCII ...) file upload works. 

I guess its kind of a bug, but at least the error message could be more specific. 

P.S. my knowledge on the encoding topic is quite limited, so my wording might be imprecise

**Comment by mvdbeek** [comment]
The dataset seems to be missing.

**Comment by bernt-matthias** [comment]
[2017-02-07_RS_Robogut_Synergistetes.txt](https://github.com/galaxyproject/galaxy/files/1230739/2017-02-07_RS_Robogut_Synergistetes.txt)

**Comment by bernt-matthias** [comment]
Sorry. Forgot the file. I changed the extension of the fasta file to txt since upload was not possible otherwise.

**Comment by bernt-matthias** [comment]
I just checked the upload on usegalaxy.org .. there the problem manifests differently. The file is added  the history, but the preview says "The uploaded binary file contains inappropriate content" and viewing the files does not show anything.

**Comment by nsoranzo** [comment]
I think the proxy error in the original description above is not related to Galaxy, but to the proxy configuration.
What happens on usegalaxy.org (and on the dev instance on my laptop) seems appropriate to me, the attached file is recognised as binary by the operating system and I don't think it will be supported by Galaxy.
Feel free to re-open if that's not the case.

**Comment by bernt-matthias** [comment]
We just switched to nginx now and have the usegalaxy behavior. 

Wondering what to do about the error. As far as I remember the file is a tsv export from excel that contained some special chars...

**Comment by nsoranzo** [comment]
You need to use something like `iconv` to convert the file to UTF-8 before uploading.

**Comment by bernt-matthias** [comment]
Indeed I could do this, but I'm thinking more of the Galaxy users running in this "trap" :)
