### ISSUE TITLE
<filter> tag does not work on output collections

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#445]
Hello,
I have an instance where I am trying to allow users to run a subsampling program on files with support for paired-end subsampling. I use a conditional to specify the list:paired input and the user should get a matching list:paired output dataset with list:paired input. However, the filter xml tag does not work on dataset collections or their nested "data" or "collection" children. Some example code which returns a very cryptic error message with ouput, implicit collections, and a few things. Any help is appreciated 

```
 <inputs>
   <conditional name="single_vs_paired">
     <param name="single_vs_paired_selector" type="select" label="What type of Fastq files do you have?">
<option value="single_files">Single fastq files.</option>
    <option value="list_of_files">A list of fastq files</option>
    <option value="list_of_paired_files">A list of paired-end fastq files</option>
      </param>
      <when value="single_files">
    <param name="single_fastq_files" type="data" format="fastq,fastqsanger" multiple="true" label="Single fastq files." />
      </when>
      <when value="list_of_files">
    <param name="list_fastq_files" type="data_collection" collection_type="list" format="fastq,fastqsanger" label="List of fastq files" help="Read documentation on creating a list of files." />
      </when>
      <when value="list_of_paired_files">
    <param name="paired_fastq_files" type="data_collection" collection_type="paired" format="fastq,fastqsanger" label="Paired list of fastq files" help="Read documentation on creating a list of paired files." />
      </when>
    </conditional>    
    <param name="readsRequested" type="integer" min="1" value="100000" label="Total number of reads you want from the file"/>
  </inputs>

  <outputs>
    <data format="fastq" name="single_output" label="Subsampled single file ${on_string}" >
      <filter>single_vs_paired["single_vs_paired_selector"] == "single_files"</filter>
    </data>

    <collection name="list_output" type="list" structured_like="list_fastq_files" inherits_format="true" label="Subsampled ${on_string}">
    <filter>single_vs_paired["single_vs_paired_selector"] == "list_of_files"</filter>
    </collection>
    <collection name="paired_list_output" type="list:paired" structured_like="paired_fastq_files" inherits_format="true" label="Subsampled ${on_string}">
      <collection name="pairs" type="paired">
    <data format="fastq">
      <filter>single_vs_paired["single_vs_paired_selector"] == "list_of_paired_files"</filter>
    </data>
    <data format="fastq">
      <filter>single_vs_paired["single_vs_paired_selector"] == "list_of_paired_files"</filter>
    </data>
      </collection>
    </collection>
  </outputs>
```

**Comment by MatthewRalston** [comment]
I have also noticed in the instances when Galaxy is not understanding the input-output data/collection type mapping that it tends to return this error;

{
    "implicit_collections": [],
    "jobs": [],
    "output_collections": [],
    "outputs": []
}

**Comment by MatthewRalston** [comment]
Related https://biostar.usegalaxy.org/p/13018/#13064

**Comment by bgruening** [comment]
Thanks for you bug report! 
I hope @jmchilton can help you here, he is our collection expert :)

**Comment by jmchilton** [comment]
Yup - I have the test case up and running and see in the implementation that `<filter>` tags are in fact not supported for output collections. Working on this now - should hopefully not be too difficult to implement.

**Comment by MatthewRalston** [comment]
Thank you John!

**Comment by MatthewRalston** [comment]
@jmchilton would this work in the following case? I'm developing a tool which gives users the option to specify a paired-list input or single-end input. The output should be either a paired-list or single-end output, respectively. This is kind of a combination of the [explicit paired-list outputs](https://github.com/galaxyproject/galaxy/blob/dev/test/functional/tools/collection_creates_dynamic_list_of_pairs.xml)  with the [filtering of collections](https://github.com/galaxyproject/galaxy/blob/release_15.07/test/functional/tools/output_collection_filter.xml). I want to release this after these two additions are in a stable release.

```
   <collection name="output_list_paired" type="list:paired" label="${tool.name} on ${on_string}: Fastq">
      <discover_datasets pattern="(?P&lt;identifier_0&gt;[^_]+)_(?P&lt;identifier_1&gt;[^_]+)\.fq" ext="fastqsanger" visible="true" />
      <filter>str( $single_vs_paired.single_vs_paired_selector ) == "list_of_paired_files"</filter>
    </collection>
```

**Comment by jmchilton** [comment]
Something like that should work yes, does it not?
