### ISSUE TITLE
Error during suite_mothur package installation from the MainToolShed

### ISSUE THREAD

**Issue by arbernard** [galaxyproject/galaxy#4453]
Clicking the **Install to galaxy** button on the preview page of the **suite_mothur** package (by the IUC and available on the MainToolShed) will cause the interface to hang for roughly 60s before displaying the following error message:

```
uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 331] during GET /admin_toolshed/prepare_for_install?changeset_revisions=50f1227b870c&repository_ids=1e1a6faad90b82fa&tool_shed_url=https%3A%2F%2Ftoolshed.g2.bx.psu.edu%2F (**IP address**)
IOError: write error
```
Here is what is displayed in the log file:

```
**IP address** - - [28/Jul/2017:14:33:43 +0200] "GET /admin_toolshed/prepare_for_install?changeset_revisions=50f1227b870c&repository_ids=1e1a6faad90b82fa&tool_shed_url=https%3A%2F%2Ftoolshed.g2.bx.psu.edu%2F HTTP/1.1" 200 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36"
Fri Jul 28 14:35:24 2017 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) !!!
Fri Jul 28 14:35:24 2017 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 331] during GET /admin_toolshed/prepare_for_install?changeset_revisions=50f1227b870c&repository_ids=1e1a6faad90b82fa&tool_shed_url=https%3A%2F%2Ftoolshed.g2.bx.psu.edu%2F (**IP address**)
IOError: write error
[pid: 10250|app: 0|req: 19/38] **IP address** () {56 vars in 1402 bytes} [Fri Jul 28 14:33:43 2017] GET /admin_toolshed/prepare_for_install?changeset_revisions=50f1227b870c&repository_ids=1e1a6faad90b82fa&tool_shed_url=https%3A%2F%2Ftoolshed.g2.bx.psu.edu%2F => generated 17303 bytes in 100482 msecs (HTTP/1.1 200) 2 headers in 73 bytes (1 switches on core 0)
```

This issue does not appears on a local Galaxy instance where there is no [uwsgi] section in the galaxy.ini configuration file.

I've tried to edit some timout related parameters in the galaxy.ini [uwsgi] section without success.

**Comment by nsoranzo** [comment]
@shiltemann may have suggestions here.

**Comment by shiltemann** [comment]
if it's always exactly 60 seconds it sounds like a timeout somewhere. If you are using nginx you could try increasing [uwsgi_read_timeout](http://nginx.org/en/docs/http/ngx_http_uwsgi_module.html#uwsgi_read_timeout) in the config maybe?

For anybody encountering the same and looking for a workaround, I have added a [tools.yaml](https://github.com/galaxyproject/tools-iuc/blob/master/tools/mothur/tools.yaml) file to the repo for easy installation via api as well

**Comment by arbernard** [comment]
> if it's always exactly 60 seconds it sounds like a timeout somewhere. If you are using nginx you could try increasing uwsgi_read_timeout in the config maybe?

I don't have admin rights on the server where the Galaxy instance that gives the error is installed so i can't change the nginx configuration.

Can someone confirm that this modification of the configuration solve the issue please ?

**Comment by nsoranzo** [comment]
I have it at 300, but I never tried to install the mothur suite.

**Comment by mvdbeek** [comment]
I think the new beta installation interface would probably not have problems with big suites, but it does need a lot of work to be usable.

**Comment by hexylena** [comment]
We use the expanded file, not the suite, and this works a bit better. Hopefully the new interface helps as well!
