### ISSUE TITLE
Running shared workflow loses left and right panes

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/galaxy#4459]
When a user runs a shared workflow, they lose the left an right panes.
They must reload the browser to recover them.
Running a copy of the shared workflow does not cause this effect.

**Comment by mvdbeek** [comment]
That is on 17.05 ?

**Comment by bwlang** [comment]
yep 17.05, I just shared a workflow with you on main. I could not test
there since i only have one account....

**Comment by mvdbeek** [comment]
That isn't pretty:
![screen shot 2017-08-18 at 3 56 39 pm](https://user-images.githubusercontent.com/6804901/29461977-f8f22428-842d-11e7-811b-da6ceaf63119.png)

**Comment by mvdbeek** [comment]
On the bright side 17.09 solves this because the workflow menu stays in the center.
Still we should fix this.
