### ISSUE TITLE
Prevent running jobs that have already been run

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#4468]
I was looking at my collection of workflows, and I was thinking about the duplicate steps in them.
I have one workflow for QC, which trims fastq files, maps them to the genome, marks duplicates, ... and ends with MultiQC.

Then I have another for structural variants, one for detecting TE insertions, .... the things is that they expect different starting points, while potentially running the same job again (like adapter trimming or genome alignment or duplicate marking). It would be fantastic if galaxy could check, based on the input file and the parameters chosen, that this job has already been run, and if the dataset is not deleted, use the existing dataset instead of running the job again.

This way I can create these workflows including all steps from start to finish, and I wouldn't need to care about which steps have been run already and which have not been run.

**Comment by mvdbeek** [comment]
So I thought about this some more, and I see that there is already some code in the API for fetching jobs that correspond to a tools input parameter in https://github.com/galaxyproject/galaxy/blob/release_17.09/lib/galaxy/webapps/galaxy/api/jobs.py#L252. ~~A first step could then be creating tests for this API endpoint (I don't think there are any~~) and move the code to somewhere where it can be reused.

**Comment by hexylena** [comment]
@mvdbeek think you (mostly) accomplished this?

**Comment by mvdbeek** [comment]
Yes, followup is in https://github.com/galaxyproject/galaxy/issues/6887
