### ISSUE TITLE
Change virtual directory from `.venv`

### ISSUE THREAD

**Issue by joelostblom** [galaxyproject/galaxy#447]
Would it be possible to add an option to the config file to specify the directory for the python virtual environment that galaxy searches for? I am using [conda](http://www.continuum.io/blog/conda) to manage virtual environments, but unlike `virtualenv`, `conda` doesn't allow the creation of virtual environments starting with '.' (dot/period).

Cheers

**Comment by dtrudg** [comment]
The `.venv` is picked up in the `run.sh` script which doesn't have access to the galaxy.ini settings etc.

For conda environments I've just done something like...

``` sh
module add python/2.7.x-anaconda
source activate galaxy-python27
```

... within `config/local_env.sh` to get conda on the path and load an environment on our cluster. `run.sh` will source that file at startup.

**Comment by bgruening** [comment]
@joelostblom does the tip from @dctrud works for you? Can we close this issue?

**Comment by dannon** [comment]
I'll second @dctrud's suggestion here.  Between $GALAXY_LOCAL_ENV_FILE (`config_local_env.sh` by default) and `--skip-venv` this should be covered.

**Comment by joelostblom** [comment]
Sorry for not replying to the previous mention. I stopped using Galaxy for other reasons and never got around to reinstalling it to test the suggested fix.

Just for reference, the [issue I create for this on the Conda repo](https://github.com/conda/conda/issues/1427#event-1077056789) just got resolved, and it is now possible to create environment prefixed with a period in Conda.
