### ISSUE TITLE
remove/replace the exclamation mark for jobs in new state

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4478]
I am dealing with repeated confusion about this element. It looks like a 'warning, pay attention to me' but it should read as 'wait, nothing to see here' most (if not all) of the time.

Opinions?

![exclamation](https://lh3.googleusercontent.com/-L79twMcE5Ac/WZxyYVM0eXI/AAAAAAAANqU/x0xD_fKg1_QAGQe1Ma_7-4A-JUJRFmYAACL0BGAYYCw/h124/Screen%2BShot%2B2017-08-22%2Bat%2B2.05.06%2BPM.png)

**Comment by bgruening** [comment]
I guess instead of this Icon we can display an icon that displays @natefoo queue-state work at some point. Removing this item seems to be a good idea at this moment.

**Comment by jennaj** [comment]
What about a coffee-cup icon in the interim? Plays off of language in some tutorials when there is an expected "wait", though perhaps too casual. 2nd removing till state/status is available

**Comment by martenson** [comment]
http://fontawesome.io/icon/coffee/

**Comment by jxtx** [comment]
Why do we need a unique icon here? We can just use the clock that is used for queued?

**Comment by martenson** [comment]
@jxtx I do not think we need a unique icon here, in fact my preference would be to remove this icon.

**Comment by jxtx** [comment]
I'd suggest using the clock because otherwise there will be a visual jump when moving from new to queued.
