### ISSUE TITLE
Workflow fails to run after optional input is added to tool

### ISSUE THREAD

**Issue by tshtatland** [galaxyproject/galaxy#4481]
After a new optional input is added to a tool, the workflows that contain it do not run. After clicking [Run] they generate the error message:

> "Some tools in this workflow may have changed since it was last saved or some errors were found. The workflow may still run, but any new options will have default values. Please review the messages below to make a decision about whether the changes will affect your analysis.
> ...
> No value found for '...'. Using default: ''."

The newly added parameter has `type='data' optional='true'`. This issue occurs with Galaxy v.17.05. A few versions prior to this (16.01), warnings were issued, but the workflow could still run using default value (no input for this optional parameter), as expected.

The current workaround is labor intensive for the users due to a very large number of workflows that contain a frequently changing tool. Here is the workaround that may be useful until this is fixed:

Click on top menu:
`Workflow`

For each affected workflow, do once per workflow:

  Select workflow > `Edit`
  You will get a message such as: `"Issues loading this workflow ... No value found for .... Using default"`
  Click [`Continue`]
  Move any tool (so that this workflow appears "changed")
  From the "gears" icon (upper right), select "`Save`", then "`Close`"

After the workflow is "changed" and saved like this, it is fixed and can be run repeatedly.

**Comment by martenson** [comment]
closed by the PR ref'd above, not sure why it did not close automatically

**Comment by nsoranzo** [comment]
@martenson Because it was not merged forward to `dev`, I suppose.
