### ISSUE TITLE
Tags / annotation for histories is producing server errors at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4482]
Adding tags and/or annotation to a history is fine until a "trigger" is hit, then any changes (add tags, sometimes adding annotation, deleting tags/sometimes anno) cause the same server error to pop-up.

ping @dannon 

One trigger identified: Adding a tag starting with number. Often it needs to be the 2nd or 3rd tag, and sometimes needs to lead with a zero "0". Odd but reproducible.

 - Start a new history
 - Name it (optional, probably)
 - Add in the first tag
 - Add in any others that you want
 - Now add in this one "0.5"
 - Any new tags added or removed from this point forward, leading/containing numbers or not, pre-existing tag or not, and sometimes changes to the history annotation field, all toss the same server error. 

Update: tags containing numbers, not just leading with a number, also are triggering the problem when not the first tag (but is inconsistent behavior). Ex: `v.0.5`

Example histories with different tags/ordering that can be used to see the behavior/error message: 
 - https://usegalaxy.org/u/jenhjackson/h/test-history-tags
 - https://usegalaxy.org/u/jen/h/hello
 - https://usegalaxy.org/u/jenhjackson/h/test-history-tag-3
 - https://usegalaxy.org/u/jen/h/hello2 

Tested with MAC [10.12.6 (16G29)]. Problems come up with both Chrome [60.0.3112.101] and Safari [10.1.2]

**Comment by dannon** [comment]
So the error here is that `0` and `5` are too short for tag names in your example.  Tags must be at least two characters.  Tags are hierarchical, so `0.5` is actually a `0` tag with a `5` subtag, both of which are too short.

If we need single character tags, we can probably relax that constraint, but in any event the clientside validation and error handling of the tags editor needs to be improved.

**Comment by jennaj** [comment]
Ok, thanks @dannon for explaining how this is modeled.

Using a dash `-` or underscore `_` instead of a dot `.` avoids the problem. Let's consider this closed. We can always open again if becomes an issue users report.
