### ISSUE TITLE
Bundled 'Extract features from GFF data' tool needs access to core Galaxy library

### ISSUE THREAD

**Issue by pjbriggs** [galaxyproject/galaxy#4488]
After upgrading from Galaxy 16.07 to 17.05, we've observed that the `Extract features from GFF data` tool (which is included within the Galaxy distribution as `tools/filters/gff/extract_GFF_Features.xml`) fails with the error:

    Traceback (most recent call last):
      File "/mnt/rvmi/centaurus/galaxy/production/galaxy-dist/tools/filters/gff/extract_GFF_Features.py", line 12, in <module>
        from bx.cookbook import doc_optparse
    ImportError: No module named bx.cookbook

It appears that this tool implicitly requires access to the core Galaxy library (specifically the `bx-python` module), which is denied following changes in PR #3364 since the tool is missing from the whiteliste in `lib/galaxy/tools/__init__.py`.

The suggested workaround in the 17.01 release notes (https://docs.galaxyproject.org/en/master/releases/17.01_announce.html#deprecation-notices) to set `preserve_python_environment = legacy_and_local` in galaxy.ini solved this problem for us. More generally however the tool should probably be added to the whitelist.

**Comment by nsoranzo** [comment]
Thanks for reporting the issue @pjbriggs!
The above mentioned PR and release notes refer to the removal of the Galaxy modules from the Python import path, but many tools included with Galaxy still require libraries from the Galaxy virtualenv.
What I usually do is to add:
```xml
<env file="PATH_TO_GALAXY_VENV/bin/activate" />
```
inside each destination in `config/job_conf.xml`.

**Comment by hexylena** [comment]
Looks like there is a solution in place, and we have not received too many repeat issues of this, so maybe safe to leave it like it is? Thanks for the bug report though!
