### ISSUE TITLE
Megablast failing for config error at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4498]
Appears to have been a sporadic problem for ~ 3-4 weeks. Is failing again now.

ping @natefoo @davebx 

> **Workaround**: For metagenomic analysis, consider using Kraken instead.

**Tool**: Megablast compare short reads against htgs, nt, and wgs databases (Galaxy Version 1.2.0)

**Repo**: https://toolshed.g2.bx.psu.edu/view/devteam/megablast_wrapper/fb2e0e1dac89

**Error:** (fails against all databases, and quickly)

`Unable to run job due to a misconfiguration of the Galaxy job running system.  Please contact a site administrator.`

**Test history**: https://usegalaxy.org/u/jen/h/test-history-megablast

**Comment by natefoo** [comment]
Fixed in galaxyproject/usegalaxy-playbook@b51faf9bdb1333357ab654e47a995e2155f34acf.

**Comment by jennaj** [comment]
Test still in progress, same history as above.

**Comment by jennaj** [comment]
test completed and was successful! Thanks nate
