### ISSUE TITLE
Collection Operations still not working in Workflows

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4509]
I thought https://github.com/galaxyproject/galaxy/pull/3848 fixed collection operations in workflows - certainly there are tests proving the backend support this now but there are reports the operations themselves cannot work in at least 17.05.

From  @TKlingstrom
> I tried creating a workflow from a history with a merge and it failed. When looking at the Usegalaxy.org workflow editor the "Merge collections" and "filter failed dataset" tools are unavailable (greyed out italics).

**Comment by glormph** [comment]
I can confirm the greyed out in 17.05. My guess was that they could be run but not shown due to uncertainty of their output or something. I solved the problem for the `filter_from_file` and `relabel_from_file` in our instance because I really needed the tools (see below). Not sure if this is a good solution though, I assume there is good reason to have `type_source="input"`

If needed I can do a PR.

```
diff --git a/lib/galaxy/tools/filter_from_file.xml b/lib/galaxy/tools/filter_from_file.xml
index 6dbb282..40a6875 100644
--- a/lib/galaxy/tools/filter_from_file.xml
+++ b/lib/galaxy/tools/filter_from_file.xml
@@ -22,9 +22,9 @@
         </conditional>
     </inputs>
     <outputs>
-        <collection name="output_filtered" format_source="input" type_source="input" label="${on_string} (filtered)" >
+        <collection name="output_filtered" format_source="input" type="list" label="${on_string} (filtered)" >
         </collection>
-        <collection name="output_discarded" format_source="input" type_source="input" label="${on_string} (discarded)" >
+        <collection name="output_discarded" format_source="input" type="list" label="${on_string} (discarded)" >
         </collection>
     </outputs>
     <tests>
diff --git a/lib/galaxy/tools/relabel_from_file.xml b/lib/galaxy/tools/relabel_from_file.xml
index 797e647..5bd8145 100644
--- a/lib/galaxy/tools/relabel_from_file.xml
+++ b/lib/galaxy/tools/relabel_from_file.xml
@@ -24,7 +24,7 @@
         </conditional>
     </inputs>
     <outputs>
-        <collection name="output" format_source="input" type_source="input" label="${on_string} (relabelled)" >
+        <collection name="output" format_source="input" type="list" label="${on_string} (relabelled)" >
         </collection>
     </outputs>
     <tests>
```

**Comment by jmchilton** [comment]
@glormph Ah - of course - ``type_source`` isn't implemented in the workflow editor. That should be doable...
