### ISSUE TITLE
Editable input parameter is uneditable when running workflows (and crash workflow if edited via API)

### ISSUE THREAD

**Issue by TKlingstrom** [galaxyproject/galaxy#4520]
Description
We have a workflow using the MACS2 callpeak tool at Usegalaxy.org. When running the workflow it is impossible to edit the "Effective genome size" unless the workflow is set to "user defined". If it for example is set to M. musculus, then it is impossible to change for this specific tool.

When retrieving the same workflow by API there is no indication that this field is hardcoded in the workflow and if it is altered then the entire workflow crashes before running on the usegalaxy.org server.

Workflow:
https://usegalaxy.org/u/tomkl/w/subworkflowgalaksiocase
Subworkflow that is required to run it:
https://usegalaxy.org/u/tomkl/w/subworkflowgalaksiocase

History with test data:
https://usegalaxy.org/u/tomkl/h/chip-seq-megakaryocytes

**Comment by mvdbeek** [comment]
FWIW the issue can be reproduced in isolation with the MACS2 callpeak tool and is independent of subworkflows.

**Comment by guerler** [comment]
Is this reproducible through the ui?

**Comment by mvdbeek** [comment]
Yes, lemme put together an example.

**Comment by mvdbeek** [comment]
https://gist.github.com/mvdbeek/e86a7d4f7d78d40c0927beb99a30580f

Note how you can't interact with the effective genomesize dropdown.

**Comment by mvdbeek** [comment]
The main issue is probably that you can't set select boxes to "Set at runtime".

**Comment by guerler** [comment]
Regular select fields can be set at runtime, but that select box is a conditional parameter. Conditional parameters cannot be changed during runtime since they may cause changes in the input/outputs of a tool step.

**Comment by mvdbeek** [comment]
Hmm, that's unfortunate but makes sense. I guess a consequence of this is that we should avoid conditionals for things that don't change input or output. Thanks @guerler.
