### ISSUE TITLE
Ability to update/select subworkflow versions

### ISSUE THREAD

**Issue by TKlingstrom** [galaxyproject/galaxy#4521]
(Marius van den Beek is already working on this issue but this is added for some discussion on the issue).

When setting up a workflow with a subworkflow. Then the subworkflow will always work with the input it was provided the first time it was run. This is a partial "work as intended" as it means that workflows won't break just because a subworkflow was updated. The downside is that when editing a workflow you have no indication of the input settings being wrong (for example aligning to the wrong genome) and it is only visible in case the detailed information about a generated dataset contains that information. 

The short term solution is probably to make it possible to alter which version (invocation?) of a subworkflow to run. But in our particular use case we control workflows through the API and it would be very valuable to be able to alter the input parameters for a subworkflow at runtime so that the same workflow can be used for multiple tasks or genomes.

**Comment by mvdbeek** [comment]
> The short term solution is probably to make it possible to alter which version (invocation?) of a subworkflow to run. But in our particular use case we control workflows through the API and it would be very valuable to be able to alter the input parameters for a subworkflow at runtime so that the same workflow can be used for multiple tasks or genomes.

That's two separate things though, one is being able to set subworkflow parameters at runtime, tracked in https://github.com/galaxyproject/galaxy/issues/1887. The other is the possibility to interact with the non-StoredWorkflow versions of a workflow (in the workflow editor, but also in the overview page).

**Comment by TKlingstrom** [comment]
I would say that from a user perspective the issues are related in the sense that they are two different solutions to the same usability issue. From a coding perspective it is however as you say two completely different questions.

**Comment by scholtalbers** [comment]
I just started using subworkflows (and its pretty awesome!) but I also encountered the issue of not being able update a subworkflow. One thing that is definitely needed, is to be able to update the subworkflow as you would also change a tool version. Especially for large workflows it can be quite tedious to reconnect inputs to a minor updated subworkflow.

**Comment by mvdbeek** [comment]
Absolutely, that is definitely needed.

**Comment by innovate-invent** [comment]
It would also be great if a bulk update option is provided in the event that many workflows use a subworkflow that has been updated.

**Comment by Tomnl** [comment]
This would be really useful functionality!

Any new developments on this?

**Comment by mvdbeek** [comment]
You can update subworkflows now from the editor (what @TKlingstrom asked for). I would say bulk-updating all workflows that embed a given workflow is risky business, and you should probably do that one by one for each parent workflow.
