### ISSUE TITLE
Collections Operations Tools Not Available in Workflows

### ISSUE THREAD

**Issue by TheZetner** [galaxyproject/galaxy#4537]
Hi @jmchilton,

@Takadonet told me I should bring this to your attention...

I was setting up some workflows earlier that involve a number of steps starting and ending with collections operations and noticed that they are unavailable to be included as steps in workflows. The tools in particular are:  

 * _Merge Collections into single list of datasets_
 * _Filter failed datasets from a list_
 * _Filter List from contents of a file_
 * _Relabel List Identifiers from contents of a file_

Have they been disabled in workflows due to instability or some other issue? Can we expect to be able to use them in the near future?

Thanks a ton!

**Comment by martenson** [comment]
Hi @TheZetner 

with https://github.com/galaxyproject/galaxy/pull/4514 the collection operations should be working I think

edit: the linked PR has been merged yesterday, feel free to test

**Comment by TheZetner** [comment]
Wonderful, thanks @martenson!
