### ISSUE TITLE
Workflows with missing tools no longer load in editor

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4548]
Previously a modal would pop-up showing a message that a tool was no longer available, but now the editor hangs in the "Workflow loading..." screen with no obvious exception in either the JavaScript console or in the Galaxy logs. It seems like this likely happened during the 17.09 development cycle (I'll update this issue if I can verify that though).

<img width="1679" alt="screen shot 2017-09-04 at 9 27 10 pm" src="https://user-images.githubusercontent.com/216771/30041419-ea43efbe-91b7-11e7-9349-d6e39319688d.png">

- Failed test -
 https://jenkins.galaxyproject.org/job/selenium/210/testReport/selenium_tests.test_workflow_editor/WorkflowEditorTestCase/test_missing_tools/
- Previously passing test -
 https://jenkins.galaxyproject.org/job/selenium/203/testReport/selenium_tests.test_workflow_editor/WorkflowEditorTestCase/test_missing_tools/

**Comment by mvdbeek** [comment]
reverting https://github.com/galaxyproject/galaxy/pull/4476 fixed it for me ... I bet it's the exception handling that I have changed in there.
