### ISSUE TITLE
17.09 Release Review Meeting

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#4554]
@galaxyproject/core, it's time to get 17.09 rolling. I propose a meeting this week if possible (sorry for the short notice), mid-morning EDT (UTC -0400). Let's say 10 AM EDT on Thursday as a first attempt at a time, reply with any conflicts and preferences you have if this doesn't work. I believe any time should be good for me as long as it's not Friday super early in the morning.

Also, if there are any issues or PRs you'd like to draw attention to before the meeting, please do so here.

timezone link: https://www.timeanddate.com/worldclock/fixedtime.html?msg=17.09+pre-release+meeting&iso=20170907T10&p1=43&ah=1

**Comment by mvdbeek** [comment]
Thursday works for me
