### ISSUE TITLE
Some datatype sniffer grep through whole file

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#4558]
Notably SDF and MOL2 do this (SDF even does it twice), and that can take quite a while for very large files.

**Comment by bgruening** [comment]
The grep should actually just be a count for the metadata as far as I remember. If we do not need a accurate count we can drop this.

**Comment by mvdbeek** [comment]
That's fine for metadata setting, but not for sniffing. The relevant lines are 
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/molecules.py#L91-L108
and
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/molecules.py#L170-L186
