### ISSUE TITLE
Trinity errors at http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#4583]
Related to PSC Bridges.

Jobs will produce red datasets with this error message:

`Remote job server indicated a problem running or monitoring this job.`

Updates will be posted here.

ping @natefoo

**Comment by natefoo** [comment]
We're currently unable to run jobs on [Bridges](https://www.psc.edu/bridges) and are working on a fix.

**Comment by jennaj** [comment]
Corrected. Thanks Nate
