### ISSUE TITLE
admin display whitelisting URI too long

### ISSUE THREAD

**Issue by alpapan** [galaxyproject/galaxy#4585]
When does it happen: 
release 17.05; When you have installed QIIME and Mothur and wish to whitelist the display. You have to select a large number of check boxes to make this happen.

What happens:
The requested URL's length exceeds the capacity limit for this server.
Apache/2.4.7 (Ubuntu) Server at gpi.westernsydney.edu.au Port 443

**Comment by alpapan** [comment]
(solution could be a file for sanitize_whitelist_file but still, shouldn't break!)

**Comment by dannon** [comment]
Thanks for pointing this out!  All of these do get persisted to the sanitize_whitelist_file, so you're correct in that using that method for specifying tools is a workaround.

That said, you're also very right that it shouldn't break like this!  :)

It won't be in time for the 17.09 release (unless someone else does it), but we should be able to adjust this request to fix the problem.

**Comment by dannon** [comment]
@alpapan I was originally thinking we'd roll this into the forthcoming admin interface overhaul, but it should be fixed with #4625.
