### ISSUE TITLE
bcf converters missing from dev branch

### ISSUE THREAD

**Issue by alpapan** [galaxyproject/galaxy#4590]
./lib/galaxy/datatypes/converters/bcf_bgzip_to_bcf_converter.xml
./lib/galaxy/datatypes/converters/bcf_to_bcf_bgzip_converter.xml

I think are missing (run.sh complaints) but i don't know if that happens on a clean install or it is just my packages (it wasn't complaining for release_17.05)

**Comment by mvdbeek** [comment]
This has been changed in https://github.com/galaxyproject/galaxy/commit/da5b72a030d8d07c663566527fc64560e067eb54#diff-d5c80b3279bf41b0a8f1368025c840c7, the converters have been renamed.
If you have changed the datatypes_conf.xml.sample file you need to update it.

**Comment by alpapan** [comment]
oops!
