### ISSUE TITLE
minor doc: docker iptables

### ISSUE THREAD

**Issue by alpapan** [galaxyproject/galaxy#4596]
Hello

May I suggest that this doc
https://docs.galaxyproject.org/en/master/admin/interactive_environments.html

includes the suggestion that admins create an iptables rule named DOCKER?
```iptables -N DOCKER```

Not sure if this is required just by galaxy or all docker setups but it caught me.

May I also suggest adding 'docker run hello-world' test? it's kinda hard to debug what's going wrong when setting it up for the first time but it could also be useful as a test after updates?

**Comment by bgruening** [comment]
@alpapan pleas feel free to open a PR with your improvements. I'm not aware of changing iptables is necessary. I never did it.

**Comment by hexylena** [comment]
Docker has made a lot of changes in recent years and it is mostly up to the admin to install docker and ensure it is working, I'm not sure we should document that as well.
