### ISSUE TITLE
[Feature Request] Explicit production of list:paired datasets

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#460]
Hello everyone, I have a few tools where i'd like to explicitly create a list:paired collection, rather than a paired collection several times over a list:paired input. In such cases, the implicit list:paired collection generation does not apply and I find it difficult to configure tools in this way. For example, given a script which, when given an SRA accession, retrieves sample metadata and ftp locations for fastq files it would be interesting to create a tool which downloads all fastq.gz files from these ftp locations and loads them into galaxy into a list:paired collection.

**Comment by jmchilton** [comment]
Thanks for the feature request and use case description - have been working on this today and yesterday. WIP @ https://github.com/galaxyproject/galaxy/compare/galaxyproject:dev...jmchilton:nested_collections?expand=1.

**Comment by MatthewRalston** [comment]
If I can, I would love to contribute this tool. Might be useful for others (could result in lots of data usage XD  )

**Comment by bgruening** [comment]
@MatthewRalston feel free to contribute this tool to the IUC repository: https://github.com/galaxyproject/tools-iuc
Also please have a look at: https://toolshed.g2.bx.psu.edu/view/matt-shirley/ncbi_sra_toolkit

Thanks for your work!
Bjoern

**Comment by MatthewRalston** [comment]
Thanks everyone, I appreciate this. :) The ncbi_sra_toolkit looks great! I would be able to use it when I can convert a single input (e.g. an SRA "SRP" project accession) into a list RE: #469 (of SRA files), which could then be converted into fastq by this toolkit. Practically, it would just seem simpler to provide an SRP to download all available fastq files from an experiment.

**Comment by jmchilton** [comment]
Waiting for #464 to be merged and I then I will open a PR with this https://github.com/jmchilton/galaxy/commit/cfa6f0df2a245ccd7681ef24f144f9b35c4b1cf5. That should allow fully dynamic creation of `list:paired` collections as would be required for an SRA download tool.

**Comment by MatthewRalston** [comment]
+1 Would that commit also imply the dynamic creation of list collections with something like

```
<outputs>
   <collection name="list_output" type="list">
      <discover_datasets etc="etc"/>
   </collection>
</outputs>
```

**Comment by mdshw5** [comment]
Hey @MatthewRalston. If you are interested in iterating over SRP accessions you could open an issue / PR in mdshw5/sra-tools-galaxy.

**Comment by MatthewRalston** [comment]
Thank you, I have something that does 90% of what I need right now, and should be fine now that #538 was merged

**Comment by hexylena** [comment]
Please re-open if still an issue.
