### ISSUE TITLE
minor regressions in the updated dataset 'pencil' menu 

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4601]
as of https://github.com/galaxyproject/galaxy/commit/26c7abb130bade73b64284956f0077f35067095f

* dataset’s ‘edit attributes’ on dev branch refresh the page before displaying the form
* the history box highlight (so you can see what dataset are you operating on) is not present anymore

**Comment by natefoo** [comment]
This is on Main now, any chance we can fix it before the release? It's not show stopping but it does make for a less than ideal experience.

I'm seeing it with things under the gear menu as well (e.g. "Saved Histories")

**Comment by martenson** [comment]
the bug-report button also reloads the whole page instead of targeting middle pane

**Comment by martenson** [comment]
'saved histories' and 'histories shared with me' are also refreshing the page

**Comment by martenson** [comment]
The only thing missing here is the the history dataset highlight

**Comment by martenson** [comment]
other two issues were not regressions, I opened new issues for them and closing, thanks @guerler

https://github.com/galaxyproject/galaxy/issues/4786
https://github.com/galaxyproject/galaxy/issues/4785
