### ISSUE TITLE
admin group creation switch is mislabeled and broken

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4618]
![screenshot 2017-09-14 16 09 08](https://user-images.githubusercontent.com/1814954/30453513-1cf468e2-9967-11e7-9057-0c744f06d45e.png)

the label should read 

>Create a new group of the same name for this role:

Also the switch seems ignored and the group is actually never created.

**Comment by hexylena** [comment]
I have this same screenshot sitting in a folder! Glad you caught this as well since I forgot to file it
