### ISSUE TITLE
Workflow-to-Job Scheduling Parameters

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4637]
## Five Steps

1. Augment Galaxy to be able to define these parameters.
2. Augment the workflow run form to expose a new class of parameters for scheduling.
3. Augment the workflow invocation API to read in these parameters.
4. Augment the workflow invocation API to write these parameters to the database.
5. Augment the dynamic job destination subsystem and the DTD to read these parameters in.

### 1.

An easy first cut at this would just be to add a global parameter to config.py (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config.py) - a simple string - that would reference one of the parameter sets in the job_resources_param_file https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config.py#L50 to render parameters for. This is nice because admins are already used to adding parameters to this file and all the parameter -> tool parsing is done already.

Some links with hints on how job resource parameters work:

- https://github.com/galaxyproject/galaxy/commit/7dc073a8b79332fe3c199199b3f673e9a0ee32d7
- https://github.com/galaxyproject/galaxy/pull/3291/commits/b78287f1508db2c06f0c309ed8d3747adb4d17fa

### 2.

The backend builds up a representation of the workflow "form" to run in this method:

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/managers/workflows.py#L350

Now ideally I'd prefer to pass structured data to the frontend and let the UI render a new class of parameters but a first pass at this could simple augment the workflow definition with the parameters specified in (1) and add them as workflow parameters at this step. I'd given them a special prefix like "__job_resource" or something so that UI and following steps can separate them out and identify them as scheduling parameters and not workflow parameters.

Follow up steps would be pass them in a different structure and parse them separately in the UI with different styling and such.

### 3/4.

These two steps kind of blur together in my mind currently.

Galaxy has the concept of WorkflowRequestInputParameter that have different types.

The table for this was created here: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/model/migrate/versions/0123_add_workflow_request_tables.py#L16

These written to and read from the database here:
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/workflow/run_request.py#L310

The model object and valid "type" parameters for such workflow-level inputs is defined here https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/model/__init__.py#L4207.

One way to think about workflow execution is it happens in two steps. (a) The request to execute the workflow in persisted to the database and then (b) a workflow invocation handler picks up the request in another thread and starts scheduling jobs. We will likely want to write out the parameters in step 1 as WorkflowRequestInputParameter with a new "type". During step (a) we will want to read in the information from the users request and persist it out and during step (b) we may want to pull it out of the database. Alternatively, we may not want to pull it out yet and just let the dynamic dispatch code do that later. I'm sure run_request.py will need to be modified to do the persisting and model/__init__ will need to be modified to add a new type of workflow parameter.

### 5.

It is worth reviewing the following commit which exposes a workflow invocation ID to the dynamic job scheduler stuff:

https://github.com/galaxyproject/galaxy/commit/f9be760b28ae60a85611df51474d8f0ebf9e6724

You will likely either want the DTD to use that invocation ID to find the workflow parameters you persisted earlier or you will want to pass through the previously loaded parameters the same way we are passing around the invocation ID. I'm not sure which is better.

## Further Work

This will be a first cut, there will be several important directions to take the work after that.

- Use the workflow parameters to actually scheduler higher priorities workflows ahead of lower ones (so don't just put them in the job queue with a higher priority - put them in the job queue sooner).
- Structured data in the API and improved GUI styling described above for step 2.
- Rework job_resource_param stuff to be just "resource parameters" or something more generic - provide cleaner ways to specify defaults and such.
- Implement some sort of mapping (either via file or in the database) to allow different workflows to have different sets of parameters. This might only work for published workflows - but even then they get copied before a user uses them - so I'm not sure how to tag the workflow in an admin persistent fashion that the user cannot override.

**Comment by JeffreyThiessen** [comment]
I am currently on step 5 and am having trouble figuring out how I can access the column I added to `WorkflowRequestInputParameter_table` that will store the parameters.

In "dynamic_tool_destination.py" _def map_tool_to_destination(...)_ I can access the "__workflow_invocation_uuid__" for the job but I don't know how I can properly make a query to the db for the parameters I want. I thought that I might pass the data through the job parameters like "__workflow_invocation_uuid__" does in "lib/galaxy/jobs/mapper.py" _def __invoke_expand_function(...)_ but I ran into a dead end there too.

In both of these approaches the functions do not hold the `trans` variable that I have seen used to create db queries (like in https://docs.galaxyproject.org/en/master/_modules/galaxy/managers/workflows.html#WorkflowsManager.get_stored_workflow). 

If you have some suggestions or code examples for how I could do this it would be very helpful. Thanks.
