### ISSUE TITLE
[feature request] Offline mode

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#4643]
As I'm sitting here and staring at absolutely miserable network connectivity with the inability to do anything other than submit questionable ideas... ;)

![auswahl_064](https://user-images.githubusercontent.com/458683/30584078-f56744be-9d28-11e7-9f04-19b98b3262fb.png)

Now that we're moving more views to the client side, I'd like to request an offline mode. Or...if not a full "offline" mode, at least allow for poor connectivity by queueing actions and resolving them when possible / retrying if we aren't sure that an action has been ack'd

Expected UX:

- I can search (client side) for tools, configure them, and launch them.
- I can change histories (maybe with only a subset being available in the client)
- I can create new histories and switch to them.
- I can create workflows and launch them (stretch goal)

How:

- Store a queue of actions to resolve when network is available, and as the network comes back start resolving the chain of actions the user made (in the order the user executed them)
- If an action fails and there are no dependent actions, just show a failure popup and link to where the failure occurred (if the user switched histories)
- If an action fails and there are downstream actions (e.g. create history (fails), switch to history, create job, then everything after create_history would fail.) We try and execute the maximal number of actions the user requested.
- I recently saw a nice solution for dealing with this issue of maximal-once-submission. (I'm sure there are others). We (client side) generate an UUID when building the data to post. We can then post again and again and again and just check that we do not have duplicates on the server side. 

If the user *knows* they'll be going offline, they could additionally click some button that would start downloading and caching objects client side, e.g. caching the toolbox, caching tool-data tables, caching the contents of the current history and then the next N additional histories until we hit a size limit.

**Comment by hexylena** [comment]
cc @joachimwolff @blankclemens

**Comment by blankclemens** [comment]
I'm torn apart between total ignorance towards bad/no internet connection (if we deny its existence we might accelerate the need for ~~universe~~ galaxy wide free internet access) and the beautiful idea of an offline mode in general.

Just out of interest: How big would the caches be at the moment? E.g. for the tool search, for the tool forms etc.? Since that might make sense for parts anyways (e.g. accelerating the tool search).

**Comment by hexylena** [comment]
Compromising on only the latest tool being available (this seems reasonable)

Dataset | Size
--- | ---
/api/tools | 1,3M
/api/tools/*/build | 6,1M
/api/histories/ | ehhh probably only a couple megs? let's say 2.

I'd say this is pretty reasonable to ask the client to store in client side storage.

**Comment by blankclemens** [comment]
Totally agree.

**Comment by martenson** [comment]
Pretty challenging idea.

A thing to consider is that the search(es) won't work the same locally as when using backend whoosh indices, results will differ.

**Comment by mvdbeek** [comment]
There are other things to consider as well. Some of our IDs that are being passed around are simply incremental. Things could go really very wrong if the order is messed up.

**Comment by hexylena** [comment]
@martenson yes, quite challenging. Hence the friendliness tag :) 

Does not matter that searches return different results. This is acceptable IMO. Maybe even no need for search, just expand every section and let the user ctrl-f

@mvdbeek do you have a specific example in mind where we're generating a sequential ID? In my view, order would be preserved within a user's session.

**Comment by mvdbeek** [comment]
history ids, hda ids, collection ids ... . If order preserving would work reliably that wouldn't be an issue. maybe I'm too pessimistic :).

**Comment by martenson** [comment]
The IDs are always generated on the backend I think, so if we preserve the request queue we might be fine? The queue would probably need to be resolved in a series once online.

**Comment by hexylena** [comment]
https://brandur.org/idempotency-keys
