### ISSUE TITLE
Minor UI glitch

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#4646]
When a tool is uninstalled. There is a small green notification box that should show the same uninstalled tools in bold. But its not bold but the `<b>` tags are shown: 

`The repository named <b>lefse</b> has been uninstalled.`

**Comment by scrathat** [comment]
@bernt-matthias can this be closed?

**Comment by mvdbeek** [comment]
Well, it's still there, and is going to be in 19.09. But it'll be gone in dev as we replace that view entirely, probably not worth fixing at this point.

**Comment by martenson** [comment]
Given the UI does not exist anymore I assume yes.
