### ISSUE TITLE
Access DataLibrary files from tool form

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#4667]
I would like to submit some ideas that could help users (these ideas are based on comments from the users of our Galaxy server).
Discussions have started here : http://dev.list.galaxyproject.org/Displaying-tool-select-list-according-to-user-td4671049.html

It could be great to be able to access to a file stored in a library, without the the import to current history step

Like @peterjc has pointed I really don't know how it could be straightforward or a nightmare to implement.

As these are requests from my own users, I would be glad to help!

And fell free to make any change in this issue in order to make it clearer...

thank you.

**Comment by mvdbeek** [comment]
That sounds like a good idea. We do have some rudiments in https://github.com/galaxyproject/galaxy/blob/master/lib/galaxy/tools/parameters/basic.py#L1975. I believe the idea there is that you add a parameter of type `library_data ` (instead of `data`) to your tool wrapper. I haven't seen a tool in the wild using it though, so I'm not sure what the current status is.

**Comment by martenson** [comment]
I imagine this as a part of the rework of the input select element in the toolforms. I think there is no need to put this logic in the wrapper, it is just a dataset after all.

**Comment by mvdbeek** [comment]
> it is just a dataset after all.

Right, I think this also a step up from data tables/.loc files, since we have provenance, storage in the object store and creating these isn't necessarily an admin-only functionality.

**Comment by peterjc** [comment]
Yes - all those good things plus data library files give us role based permissions, which was the driving use case for opening this issue.

**Comment by FredericBGA** [comment]
It works , Galaxy is really an amaizing tool !
I think it needs some improvements.
Maybe it coul be useful to be able to choose a library or a folder which will be used as root ?

I notice (a small test with 2 libs) that every few seconds, there is a refresh, and if the second lib was selected (in the first list), the list below (which holds the lib content) will be populated again with the content of the first lib of the list !
