### ISSUE TITLE
Impossible to retrieve invocations from a shared workflow using Galaxy API

### ISSUE THREAD

**Issue by TKlingstrom** [galaxyproject/galaxy#4675]
**Scenario:**
User A have created a workflow and shared it with User B.
User B executes the workflow on his data using a third party tool interacting with Galaxy by the API (Galaksio).

After running the workflow Galaksio is now unable to retrieve details regarding the invocation and the request fails with a  "User does not own specified item." reply when trying to retrieve the invocation using the GET /api/workflows/{workflow_id}/invocations/ function. It is possible to find the  workflow_invocation_id using the API for jobs but we would then need to send a large number of requests to the server in order to find out which pairings of invocation IDs and workflow IDs are accepted by the server

Making the API provide a list of invocations made by the user when requesting the list of invocations of a workflow not belonging to the user would therefore be very valuable to anyone developing third party applications.

Furthermore the above functionality makes us wonder if User A is able to retrieve other peoples workflow invocations from a workflow he have shared with them which would be a minor security hole.

**Comment by mvdbeek** [comment]
This sounds like https://github.com/galaxyproject/galaxy/issues/4401, for which a fix will appear in 17.09.

**Comment by TKlingstrom** [comment]
Yes that seems to be the same issue and sorry for not checking Github better, I did not think of checking the closed pile as well as the open issues.

Thank you!

**Comment by mvdbeek** [comment]
No worries, let us know if something doesn't work as expected. FYI https://test.galaxyproject.org/ is already running the 17.09 branch.
