### ISSUE TITLE
SnpEff Download retrieving wrong genome

### ISSUE THREAD

**Issue by madelaineb** [galaxyproject/galaxy#4677]
Tested 'SnpEff Download' with Zea_mays and Zhouia_amylolytica_ad3 - in both cases the tool is downloading Yersinia_pseudotuberculosis_gca_001110725.

**Comment by jennaj** [comment]
Thanks @madelaineb - the issue is tracked here so I am going to close this out and link the two.

https://github.com/galaxyproject/tools-iuc/issues/1354
