### ISSUE TITLE
Custom galaxy tool greyed out in workflow editor

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#468]
Hello everyone. I have a situation where I have a valid tool that works fine in Galaxy otherwise. However, in the workflow creator GUI, the tool appeared greyed out. Similar tools that I have created are fine. Can someone point me in the right direction?

**Comment by jmchilton** [comment]
The workflow editor did not support tools that produce collections explicitly until the as yet unreleased version 15.07. Is this still a problem on the dev branch?

**Comment by MatthewRalston** [comment]
Ahh i haven't tried. I'm working on release 15.05. Thanks John.
