### ISSUE TITLE
How can I trace the job that is producing "Marking step Y outputs of invocation X delayed..." log?

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#4683]
Hi there!

Thanks for all the fantastic work here! In one of my instances I'm getting this message repeatedly on the logs for a few different step numbers and invocation numbers. However, I find no trace of a job number 297 or equivalent. On the API dashboard for managing jobs, I have deleted all jobs, but this still keep coming up. Do I need to find this in the database? How do I map from this to its parent job?
 Please see below one example which keeps repeating:

```
galaxy.workflow.run DEBUG 2017-09-24 09:05:47,277 Marking step 2120 outputs of invocation 297 delayed (dependent collection [83] not yet populated with datasets)
```

Closest issue I have found is: 
https://github.com/galaxyproject/galaxy/issues/2581

But apparently not entirely related. This is on version 17.05.

Any hints very much appreciated! Thanks!

**Comment by jmchilton** [comment]
There are a couple root problems that might cause this - there is a postgres workaround for stopping the continued scheduling of that workflow here https://github.com/galaxyproject/galaxy/issues/3555#issuecomment-324707614. 

When whatever job was going to populate collection with ID 83 was cancelled or killed - the collection itself should have been marked as failing to populate and it should cause this workflow to stop scheduling. The fact that it didn't is a Galaxy bug.

**Comment by pcm32** [comment]
Many thanks @jmchilton, this is very useful! Will follow from where you suggest.
