### ISSUE TITLE
Cryptic error/exception while generating a list output from single data input

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#469]
Custom galaxy tools that create a list collection (most often without a data collection input) produce the following json, which I assume comes from some exception or error, but no clue as to how to correct the issue or why a single datum input ->list mapping is undesirable or forbidden.

```
{
    "implicit_collections": [],
    "jobs": [],
    "output_collections": [],
    "outputs": []
 }
```

From the following xml inputs and outputs

```
  <inputs>
    <param name="sra_data" type="data" label="Provide an SRA txt file "/>
  </inputs>
  <outputs>
    <data format="txt" name="log" label="log"/>
    <collection name="sraFiles" type="list" label="sra files">
      <data name="sraFile" />
    </collection>
  </outputs>
```

**Comment by MatthewRalston** [comment]
Previously when I encountered these errors while trying to provide a list:paired -> list:paired conversion, the solution was to provide the "structured-like" (and sometimes the "inherits_format") attribute to the output collection tag. In this case, the mapping is from a single parameter to a list.

**Comment by MatthewRalston** [comment]
Is this related to the "discover_datasets" tag with the exception of putting outputs into a list, rather than separate history items?

**Comment by jmchilton** [comment]
There is a test case to verify output_collections is non-empty https://github.com/galaxyproject/galaxy/blob/dev/test/api/test_tools.py#L411. I'm going to mark this as resolved since it sounds like it isn't needed anymore after #460 is in place?

**Comment by MatthewRalston** [comment]
Okay. I haven't encountered this error in a long time. Thank you.
