### ISSUE TITLE
Tours directory not monitored

### ISSUE THREAD

**Issue by selten** [galaxyproject/galaxy#4692]
The tours directory is not being watched. Thus adding tours requires a restart of Galaxy.

**Comment by dannon** [comment]
It'd be good to add the same watching mechanisms that we have for tools, etc., here.  I can take a stab at this.

**Comment by selten** [comment]
There is no way to trigger an update through the admin panel, however an update can be triggered through the API. This is a workaround for tours directory not being monitored.

**Comment by dannon** [comment]
Correct, there's a helper that Galaxy admins can access with a POST to:

```
<galaxy_instance>/api/tours/tour_id_to_update/
```

And it'll reload that tour from disk.  Not exactly elegant, and reloading tours automatically with watchdog (like tools, etc.) would be a nice improvement that I'm hoping to get to soon.

(and, sorry I didn't mention this before!)

**Comment by selten** [comment]
I was merely mentioning it here for people who could use this information.

However, this can all be done in a CI script with the API. Regardless, I'm looking forward to the watcher.
