### ISSUE TITLE
Guidance for using resource requirements with Kubernetes runner

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#4702]
Hi there!

I'm starting to implement resource usage specification for jobs in our Kubernetes-based deployments. Basically my understanding of what we need to do is as follows:

1. At the initial job level definition, identify the container with which the jobs should be run, store at the job or job_wrapper somewhere. Currently we get containers definition from the destinations that we use (we use containers as destinations), we would need to move away from this. **Question:** besides setting this in the tool itself, are there any other options where we could specify pairs (tool,container)?

2. Create a job_resource_params_conf.xml file which includes the resource variables that we want to have as user configurable at the tool level interface. **Question:** Can I set different defaults for each tool, so that the user has a reasonable starting point? How or where would this be done?

3. Create a dynamic destination where the `resource_params` dictionary (as specified in the previous file) is passed as argument to the function, taking care of the destination generation. On this function the resource parameters are mapped into actual parameters that the to be created JobDestination can use.

4. Once the job destination is created, use the parameters here in the actual job creation to set relevant parts in the Kubernetes Job creation. 

Is this correct? am I missing something? Thanks!

**Comment by pcm32** [comment]
I have a working version of this now, and I have made a PR #4751 with the core functionality of the runner.

**Comment by jmchilton** [comment]
It looks like you got this mostly figured out - can I close out this issue or is there still part of this that is open?

**Comment by pcm32** [comment]
We can close it. Thanks for all the help at the PR!
