### ISSUE TITLE
changing the tool version does not refresh tool form

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#4703]
When playing around with hisat2 I found that the tool form is not reloaded when switching the version. 

The green box stating that `Now you are using 'HISAT2' version 2.0.5.1, id 'toolshed.g2.bx.psu.edu/repos/iuc/hisat2/hisat2/2.0.5.1'.` is shown. 

The form remains the one of the other version which is also shown in the title `HISAT2 A fast and sensitive alignment program (Galaxy Version 2.1.0)`. 

One thing: by accident I installed the two versions in different categories. So it also shows up twice in the tool panel. This might be related...

**Comment by hexylena** [comment]
This looks like it is ok now?

**Comment by bernt-matthias** [comment]
Unsure. Just trying to come up with a tool where the form changed ...

**Comment by bernt-matthias** [comment]
Yes. Reloading works.
