### ISSUE TITLE
Importing workflow (that is not a workflow) does not display error

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#4712]
Importing a "workflow" by e.g. URL, that isn't a valid format or isn't accessible, no longer displays the error -- just looks like a page refresh to the user. The error message is still encoded in the page's URL query parameters, however. release_17.09

**Comment by dannon** [comment]
@blankenberg Good catch; I'll get a fix out before release

**Comment by dannon** [comment]
(fixed in #4716)
