### ISSUE TITLE
Workflow page slow

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#4747]
On usegalaxy.org this takes 12 seconds for my measly 23 workflows. I think https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/workflows.py#L113 could be improved by either making the number of steps a property of the StoredWorkflow model, or by joinedloading the relevant attributes up front (tag, annotations, steps).

**Comment by martenson** [comment]
fixed in https://github.com/galaxyproject/galaxy/pull/5755
