### ISSUE TITLE
Allow running of published workflows

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/galaxy#4761]
users often do not want to modify a workflow before running it.
I'd like to allow people to directly run published workflows (just as we do with workflows that are shared with directly with a user).

See #298 for more context

**Comment by hexylena** [comment]
Per #298, I (still) strongly believe that this should be the default behaviour. That "importing" a workflow just gives you reference to the published workflow that is *always* the latest version of the published workflow.

If the user really wants to edit the workflow, that should be an extra button click. The vast majority of importing workflows is with the end goal of running them, not editing them.

**Comment by nsoranzo** [comment]
xref https://github.com/galaxyproject/galaxy/issues/5898

**Comment by mvdbeek** [comment]
I'ts done https://github.com/galaxyproject/galaxy/pull/6428
