### ISSUE TITLE
Run as real user: CondaEnvironmentError

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#4767]
When I run Trim Galore! for the first time in a setup where jobs are started as real user I get the following error: 

`Failed to activate conda environment! Error was: CondaEnvironmentError: Environment error: Cannot activate environment bash. User does not have write access for conda symlinks. Fatal error: Exit code 1 ()`

It seems that the environment is activated as the actual user which can not write. As a workaround I 
- switched to the a setup to run jobs as galaxy user, 
- run the tool 
- switched back to the run jobs as real user 

The question is if this is a galaxy or a tool bug? I could not find the bash dependencies in the `Manage Tool Dependencies` admin page.

**Comment by bernt-matthias** [comment]
No tool bug: happened also for hisat2.

**Comment by natefoo** [comment]
I do my tool installs into an environment that becomes read-only at tool runtime and this one has bit me numerous times as well. Conda expects there to be symlinks from `<conda>/envs/<env>/bin/{conda,activate,deactivate}` to their counterparts in `<conda>/bin`, and if they don't exist when you attempt to activate an environment it will create them. It seems that sometimes they are created when the env is created and sometimes they are not. As a workaround for this, my post-tool-installation script checks all envs to make sure these 3 symlinks exist and creates them if they do not:

```bash
for env in ${CONDA}/envs/*; do
    for link in conda activate deactivate; do
        [ -h ${env}/bin/${link} ] || { set -x; ln -s ${CONDA}/bin/${link} ${env}/bin/${link}; }
        { set +x; } 2>/dev/null
    done
done
``` 

There was a PR or issue about this by @mvdbeek but I can't find it, I think Conda > 3 was supposed to fix it, but it still happens pretty regularly for me.

**Comment by bernt-matthias** [comment]
Thanks for the tip. I added this to my ansible scripts. Lets see if the problem reappears.

**Comment by hexylena** [comment]
Lol @bgruening , just found this one, we had a script like this @natefoo! https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/roles/hxr.galaxy-misc/files/fix-conda.sh We have since disabled that script and things seem to be working fine?

**Comment by bgruening** [comment]
I think gxadmin should contain those fixes in a special section ... kind of wired workarounds ... this would also give us an easy way to distribute those fixes to other admins.

**Comment by bernt-matthias** [comment]
Ultimately this should be fixed in conda ...  but maybe it is already. As far as I recall the problem still exists for me.

**Comment by hexylena** [comment]
Done @bgruening

**Comment by natefoo** [comment]
I believe it was fixed in later versions of Conda, which is why this isn't a problem for most people (I'm still using 4.3.x).

**Comment by bernt-matthias** [comment]
Same here. Do you think its safe to update to the latest version?

**Comment by natefoo** [comment]
Check your version of Galaxy for the default version that would be installed (e.g. [here](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tool_util/deps/conda_util.py#L38) in dev).

**Comment by bgruening** [comment]
> (mulled-v1-a8259c1b65c5d282750e47963d88f7d939acc8a28c8ab855de159198845685cc) galaxy@sn04:~$ conda --version
conda 4.6.14

And I'm happy to upgrade to the 4.7 at the weekend and try if you like. I'm surprised 4.3 is still working :)

**Comment by bernt-matthias** [comment]
Seems to be 4.6.14 in 19.05 https://github.com/galaxyproject/galaxy/blob/b6e7f4685723d768a0c1cfae35146e1d1ea6a1e3/lib/galaxy/tools/deps/conda_util.py#L38

**Comment by bernt-matthias** [comment]
Just for curiosity, wouldn't a conda auto update to this version be neat?

**Comment by bgruening** [comment]
I guess it falls in the same category as auto-db updates. Better you monitor it and do it manually these few times.

**Comment by bernt-matthias** [comment]
Just updated to 4.6.14 and everything seems to work.
