### ISSUE TITLE
List:List tool output unrecoverable

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#4768]
I noticed this using https://github.com/galaxyproject/tools-iuc/tree/master/tools/sra-tools.
These output a dynamically discovered list. If you create a collection with accessions, and then map the tool over these accessions the state of the outer collection remains running forever, even if the tool has finished and metadata has been successfully loaded.

**Comment by jmchilton** [comment]
Is this interactively or with workflows?

Any chance you can recreate this with the test tools? If I could write or had a test case it'd be easier for me to visualize the problem and solve it.

```
GALAXY_RUN_WITH_TEST_TOOLS=1 sh run.sh
```

**Comment by mvdbeek** [comment]
I'll keep it on my todo list.

**Comment by mvdbeek** [comment]
This should be fixed by #5413
