### ISSUE TITLE
Using filters for tools hides them from the 'Reload Tool' admin menu

### ISSUE THREAD

**Issue by mkempenaar** [galaxyproject/galaxy#4793]
I have a tool filter in `galaxy/lib/galaxy/tools/toolbox/filters/examples.py` that I use for students to see only their own custom tools. This is done by checking if their galaxy username is in the tool ID field (pretty simple and works great!).

However, once the tools are added I (as admin) cannot reload their tools because the tool filter is also applied to the `Reload a tool's configuration` admin menu. While I allow tools with the same `name` field (28 students created a `VCF Filter` tool..) I understand that it will be difficult to show all these tools when using their name. 

Maybe add a `Reload all existing tool descriptions` button would help? For now I am required to restart the galaxy web interface.

<img width="336" alt="screenshot 2017-10-12 09 40 54" src="https://user-images.githubusercontent.com/1861590/31484657-7b4c9e02-af31-11e7-8c8f-aa53515eea92.png">
This screenshot shows that I only see my own custom tool which has my galaxy name embedded in its `id` field and thus unable to reload the other 20+ similar tool descriptions.

**Comment by nsoranzo** [comment]
> Maybe add a Reload all existing tool descriptions button would help? For now I am required to restart the galaxy web interface.

@mkempenaar In the picture above, hidden below the pop-up list of tools there's a box titled "Reload Toolbox", if you click on the "here" link all tools will be reloaded.

**Comment by mkempenaar** [comment]
Hi Nicola, thanks for your reponse.

The description of that particular link does however state: `Individual tools, even ones with modified tool descriptions willl not be reloaded.` and thus I do not trust it to do just that, reload individual, existing tool descriptions. According to the description it only *adds* tools to the list that were not yet discovered etc. 

Can it be confirmed that existing tools are actually reloaded and if so, the description of that link be altered to reflect it's actual function?

**Comment by nsoranzo** [comment]
> Can it be confirmed that existing tools are actually reloaded and if so, the description of that link be altered to reflect it's actual function?

I think that the description here has not been updated, ping @mvdbeek.
@mkempenaar If you can actually try it and confirm if it does work for you, we can update the description.

**Comment by mvdbeek** [comment]
Well, that link only reloads the tools in the web handler that responds to this request -- it is misleading and should be removed altogether. It only works for galaxys that run a single process.
Tool changes should be automatically reflected without further action. Always bump the version when you make changes, that way you can follow if the tool has been properly reloaded.

**Comment by nsoranzo** [comment]
In `templates/admin/reload_tool.mako`, the `here` link sends a PUT API request to `/api/configuration/toolbox`, which in `lib/galaxy/webapps/galaxy/api/configuration.py` executes:
```python
send_control_task(self.app.toolbox.app, 'reload_toolbox')
```
So I think it should reload the toolbox in every process, no?

**Comment by mvdbeek** [comment]
@nsoranzo 
You're right, I forgot about this detail and mixed it with another (unrelated) problem, which is that non-uwsgi (job) handlers can't communicate with uwsgi frontend, which was a problem with reloading the data manager tables atfer a data manager job finished!

In any case the reload should be automatic -- if it doesn't work we should spend some more energy in trying to debug why it doesn't work.

**Comment by guerler** [comment]
Does the reload work automatically?

**Comment by martenson** [comment]
I think automatic tool reloads are implemented now. Are you still seeing this @mkempenaar?

**Comment by hexylena** [comment]
Closed pending further response, let us know if it's still an issue!
