### ISSUE TITLE
Workflows: allow linking one tools's parameter value to another tool's parameter value

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#4797]
Value can be either the same or use some sort of modification/user-defined lookup table. 

Consider e.g. the simple task of a workflow having Kraken and kraken report in it -- the same database must be selected in multiple steps. Similar to workflow parameters, but would need to work for all parameter types (not just text imputs).

**Comment by mvdbeek** [comment]
I'd love to see this as well! maybe we can sketch out how that would look like in the *.ga / yaml files, to have something concrete to work along ?

**Comment by mvdbeek** [comment]
We can do this now -- text parameters can connect to select lists.
