### ISSUE TITLE
Update client documentation for new build architecture

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4803]
xref #4435 

- [x] Update client/README with newer information at level of detail of old information.
- [ ] Review and update architecture slides - add information about yarn, drop information about bower.

**Comment by dannon** [comment]
Thanks for making a note of this, definitely an important TODO that I'll get to soon.

**Comment by dannon** [comment]
Updated client/README (in #4435)

**Comment by dannon** [comment]
Working on updating the architecture slides now in advance of GCC.

**Comment by hexylena** [comment]
@dannon I'm assuming that that's done? :)
