### ISSUE TITLE
Tool parameters now ignore 'refresh_on_change' attribute

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#4810]
This breaks tools using `dynamic_options` that rely on a previously set parameter's value. e.g. the Rsync with g2 data manager tool, that should reload select lists based upon `dbkey` change.

```
    <inputs>
        <param name="dbkey" type="genomebuild" label="dbkey to search for Reference Data" help="Specify ? to show all"/>

        <param name="data_table_names" type="select" display="checkboxes" multiple="True" optional="True" refresh_on_change="dbkey"
            label="Choose Desired Data Tables" dynamic_options="galaxy_code_get_available_data_tables( __trans__ )" />

        <param name="data_table_entries" type="select" display="checkboxes" multiple="true" optional="false" refresh_on_change="dbkey"
            label="Choose Desired Data Tables Entries" dynamic_options="galaxy_code_get_available_data_tables_entries( __trans__, dbkey, data_table_names )" />
    </inputs>
```

**Comment by guerler** [comment]
I think `refresh_on_change="True"` should be set for the `dbkey` parameter, see: https://docs.galaxyproject.org/en/master/dev/schema.html#tool-code.

**Comment by martenson** [comment]
@guerler refresh_on_change is [listed](https://docs.galaxyproject.org/en/master/dev/schema.html#id29) as valid attribute for param.

**Comment by blankenberg** [comment]
What @guerler suggested does work, setting `True` on the parameter that you want to cause the refresh fixes things, and makes sense.

What is strange (concerning wrt backwards compatibility) is that this used to work with the refresh set to the target parameter, but perhaps that was a helpful bug...

**Comment by martenson** [comment]
@blankenberg if it used to work that way we should probably just acknowledge the breaking change in the release notes I guess...

**Comment by blankenberg** [comment]
@martenson indeed. I suppose that there are two possible scenarios:
 1. This attribute (was previously undocumented in this usage and it) had been working as intended (similar to data_meta --> ref of options) and behavior changed to a true/false.
2. Some bug was allowing it to work when it should not have.

A quick grep didn't show any other tools that were using this attribute, so no clues there. The nice thing about having it reference a specific parameter is that it would be potentially fewer parameters that need to be updated due to a change. The nice thing about having the refresh being true for a parameter is that it simplifies things to always just refresh everything when that one parameter changes. 

Normally I'd be all for trying to figure out what was going on before when this tool was working, but with limited time, I'll just accept that it should be True on the parameter that is changing.

**Comment by jmchilton** [comment]
> with limited time, I'll just accept that

Cleveland has changed you man, I don't even know who you are anymore.

**Comment by blankenberg** [comment]
> Cleveland has changed you man, I don't even know who you are anymore.

I know, right?  I mean, I am totally for someone spending time to figure it out, and I do want to know, but alas...

**Comment by martenson** [comment]
I added the functionality deprecation to the RN. I am not sure where to announce deprecation of @blankenberg though 😈
