### ISSUE TITLE
Workflow Post Job Action of Change Datatype ignored when connecting tools in editor

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#4813]
Tool 1 (FLASH) outputs 'fastq'. Tool 2 (FASTQ joiner) accepts fastqsanger (and others). 

Can extract a workflow from history with these two tools connected:
![image](https://user-images.githubusercontent.com/1231190/31634781-a3849cb2-b292-11e7-86b5-4db1106d14d7.png)

As soon as you add post job action of changing datatype to fastqsanger (which is actually accepted) the connections are destroyed and cannot be recreated. Same behavior when trying to create from scratch:
![image](https://user-images.githubusercontent.com/1231190/31634830-c4dcea7c-b292-11e7-9d43-c0e59ce06b56.png)

**Comment by mvdbeek** [comment]
Funny enough it seems to work for the first output (merged_reads).

**Comment by mvdbeek** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/7989 / https://github.com/galaxyproject/galaxy/pull/8040
