### ISSUE TITLE
Clicking on unassigned dbkey (?) in UI brings user to a JSON dump

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#4819]
When dbkey is not assigned, it is listed as a `database: ?`, clicking this `?` should bring the user to the edit attributes page, to allow setting dbkey, but is now bringing to the user to a JSON page.

![image](https://user-images.githubusercontent.com/1231190/31687722-12b0b7c2-b358-11e7-8c89-c40807ef5711.png)

clicking on `?`:

![image](https://user-images.githubusercontent.com/1231190/31687807-57341aa6-b358-11e7-89e2-5128c1298736.png)

**Comment by dannon** [comment]
Well that's not helpful.  I'll take a look now.

**Comment by dannon** [comment]
It looks like this has already been fixed in dev, just not release_17.09.  I'll figure out what we need to backport and open a PR.

**Comment by blankenberg** [comment]
Ah cool, thanks. Was actually just using main this time... but since you're looking at this, on dev, it is opening up in a new window. 

The target is set to `top` instead of probably `_top`, however, it would be great if a total page reload wasn't needed. There was a PR recently for this for the pencil icon: #4779

**Comment by dannon** [comment]
Yeah, I noticed the new tab, too -- definitely not ideal.  Might be tomorrow at this point, but I'll get a fix out.

**Comment by blankenberg** [comment]
Cool, thanks. No rush, the obvious work around is to just use the pencil icon, so its not critical :)

**Comment by mvdbeek** [comment]
I guess this is fixed in #4823
