### ISSUE TITLE
Summary Headers for Collections in the UX?

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4820]
Collections have these little subtitles - "a list of datasets" that once populated the UX has some time to churn become "a list of 4 datasets". In addition to adding state #4735 I'd like to revisit this summary. 

If there are jobs queued and running - would it make more sense to summarize the jobs then number of elements? How should a list of lists (or a list of lists of pairs) be summarized - by the total size or the size of the top list.

It is an expensive operation and we don't do extra summary information for "collapsed" files - should we even bother to do this for collections? Would it be better to have a summary button that popped up a little modal with information about job state counts and dataset counts?

**Comment by jmchilton** [comment]
Also should there be a visual distinction between simple collections coming from a single tool or upload and implicitly mapped collections that may corresponding to any number of jobs? They aren't different in terms of how they can be used - but they are different in terms of how you may want to view a summary of their state.

**Comment by bgruening** [comment]
> If there are jobs queued and running - would it make more sense to summarize the jobs then number of elements?

Jobs. If we display jobs your second comment will also be solved I think.

> How should a list of lists (or a list of lists of pairs) be summarized - by the total size or the size of the top list.

Top list. I would assume the number of direct elements included and not recursively. I tend to think for collections like folders. You also don't get the recursive amount of files displayed in a file browser.

**Comment by jmchilton** [comment]
```
if collection corresponds to one or more failed jobs
   make collection red, display message about # of failed jobs
elif collection is coming from many jobs and any are non-terminal:
  display progress bar with multiple colors demonstrating job progress [done|running|queued]
  overlay number of elements at top level - this is known...
  collection is grey until first job is running, yellow till last job is 'ok'
elif collection is coming from a non terminal job:
   display collection type and number of elements at top level (if known)
   collection color loosely maps to HDA job color
else:
   display collection type and number of elements at top level
   collection is green
```

This will be more polling than we currently do but with the change to tracking collection jobs together in flat list of DB elements - none of the queries will be recursive and everything should be doable in a fixed number of db calls.
