### ISSUE TITLE
tool_script activates conda environment multiple times

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#4821]
For get_length_and_gc_content on a (quite recent) dev instance I found that the tool_script tries to activate the conda environment multiple times. 

[tool_script.txt](https://github.com/galaxyproject/galaxy/files/1394382/tool_script.txt)

I guess this does not hurt, but still seems unnecessary (since file system on our cluster is really bad at the moment it actually hurts here .. but this is not Galaxy's fault).

**Comment by bernt-matthias** [comment]
In Manage Tool Dependencies I also see four conda dependencies for this tool (four times the same): 

Gene length and gc content | /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/mulled-v1-3c393731404066af7e214d4d32f4cc9ae7c6ea24c133932fd997e41622e5e038 | r-optparse | 1.3.2 | Conda | True |  
-- | -- | -- | -- | -- | -- | --
  |   | /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/mulled-v1-3c393731404066af7e214d4d32f4cc9ae7c6ea24c133932fd997e41622e5e038 | r-reshape2 | 1.4.2 | Conda | True |  
  |   | /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/mulled-v1-3c393731404066af7e214d4d32f4cc9ae7c6ea24c133932fd997e41622e5e038 | r-data.table | 1.10.4 | Conda | True |  
  |   | /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/mulled-v1-3c393731404066af7e214d4d32f4cc9ae7c6ea24c133932fd997e41622e5e038 | bioconductor-rtracklayer | 1.34.2 | Conda | True |  

I guess running a unique somewhere would fix this.

**Comment by mvdbeek** [comment]
Yeah, that's something we should address!
