### ISSUE TITLE
Relax client code formatting conventions

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#4828]
With #4436 we started to apply strict code style conventions. In some cases this has reduced the readability. Here we can discuss how/if certain conventions should be relaxed to resolve that. Difficulty to read the code will make it hard to find bugs, resolve issues or apply enhancements.

**Comment by dannon** [comment]
Thanks for opening the issue; we can definitely continue to refine the style to what works best for us.  To document some of the conversation on IRC:   

- template literals will help a lot of the string formatting
- templates over some number of reasonable lines (5ish?) should be moved to separate large template files, which we can pull in with a loader at build time
- line length is a funny thing; longer lines might make some things more readable, but others less so.  We should aim for the common case here (that may TBD)

In general, I think we should aim at having as few exceptions to the rule as possible.

That said `// prettier-ignore` does exist and we can use it for extreme cases when the parser just does something *really* stupid.

**Comment by guerler** [comment]
Here is a list of four major changes:

1. There are many new new-lines due to the column limitation. The number of code lines to read increased a lot, see: https://gist.github.com/guerler/9920d825508ab323cdc2eb66e2828e22.

2. Another convention is related to indentions. Previously dictionary keys and values appeared in separate columns. This was widely used throughout the client, see:
https://gist.github.com/guerler/e19ff997edfdfcccb3dd3d4fa8629a47.

3. String templates lost their structural information, this makes any change challenging, see: https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/toolshed/repository-view.js#L407.

4. Dictionary values in a arrays are now separated by two instead of a single new line, this wastes vertical and horizontal space, see: https://gist.github.com/guerler/57d2d9c4af8dc5bdada4ba53b8d03e79.

**Comment by guerler** [comment]
xref: #4865

**Comment by jxtx** [comment]
Point 1 is happening in some highly indented lines. Is there some alternative refactoring that should be done here? Pull out a function?

**Comment by guerler** [comment]
I think thats exactly the issue. The convention exists for a good reason. It's likely that the previous freedom lead to unnecessarily long lines which are now somewhat distorted and need to be refactored throughout the client. On the other hand, the first command in a backbone function comes after four indentions leaving a net column width of 64 characters. Before we refactor, I wonder how it would look if we relax the conditions within reasonable limits e.g. setting the column-limit to 100 and tab-size to 2 would increase the available space by 43%, increasing the column-limit to 120 by 75%.

**Comment by martenson** [comment]
I am strongly with @guerler on relaxing the 80char line limit.

**Comment by dannon** [comment]
I'll open a PR showing what 120 would look like for comparison.  I do think we should live with the code as-is for a little bit longer before relaxing much, though.  The initial reformat is a bit of a shock, but I'm really enjoying it so far.  

( edit: see #4875 -- it actually does look better to me in most (edit again: almost all, to me) cases, but I'm having an internal philosophical struggle with it, still :) )

**Comment by dannon** [comment]
Ok, just had a good discussion with @guerler about a lot of this.

I think we agree that the line length extension, as in #4875, would be a positive thing, after having reviewed a lot of the changes it makes.  Statements that are overly compact seem, to me, to mostly be overly complicated conditionals that (at least I) think we could rewrite using standard if/else logic anyway, to be more clear.

String templates will be much, much better using template literals and externally loaded html fragments for large bits.

Dictionary values in 'columns' can be viewed as a code smell.  Generally speaking, things like https://gist.github.com/guerler/e19ff997edfdfcccb3dd3d4fa8629a47 should be rewritten using _.extend or the like.

So, maybe we bump the line length now and leave the rest to grow accustomed to?

**Comment by martenson** [comment]
Points 3 and 4 and https://github.com/galaxyproject/galaxy/issues/4865 are relevant (to me) even if we relax to 120. 

edit: I am without opinion on 2.

**Comment by dannon** [comment]
3 is resolved with string literals and externally loaded html, as mentioned.  (I hope?  If not, we can definitely look into it more -- didn't want this to come off the wrong way)

4 is the only one @guerler and I were still split on, I think.  Personally I prefer the structure of the latter, where it is more clear that you have an array of dicts (to me), though I think sam likes the former still.  The good news is that this seemed the most minor of the points we discussed.

**Comment by martenson** [comment]
> 3 is resolved with string literals and externally loaded html, as mentioned.

That is not a remedy, that is 'broken, but we can start from scratch'. The actual html indent information is preserved only in pre-es6 state so I am afraid it is gone since every new commit makes it more difficult to automate the porting of this.

**Comment by dannon** [comment]
@martenson Okay, I'm not sure what you're either looking for or suggesting, then, regarding point 3.

Digging the exact formatting out of the history sounds like more work than just making a pass to convert it all to template literals and loaders.  *Especially* for the larger fragments, we'll move them to new files, autoformat in an editor, and it'll be better and more readable html formatting than it was to start with.

**Comment by guerler** [comment]
I am glad we could resolve this so quickly. Thanks @dannon, and I agree, the column-limit is the most critical issue. Point 2 got too few votes and regarding point 4, I do like the previous format more but its not that critical, unless more ppl are in favor.

Edit: Rewriting all templates mentioned in point 3 could potentially be quite a bit of work.

**Comment by dannon** [comment]
@guerler You're definitely right, there, in the edit.  I'll look into ways to automate it, and hand-massage it from there.  It's not a *fun* process, but that's how all the rest of these updates have gone, and, well, someone's gotta do it eventually :)

**Comment by guerler** [comment]
I think the conversation can continue in #4875. Feel free to re-open if not.
