### ISSUE TITLE
ES6 For QUnit Testing?

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4843]
I've been playing around with modernizing the QUnit test suite and I hit some snags. One nice thing the current QUnit tests allow is just opening test/qunit/tests/<test_name>.html right in a web browser and refreshing to rerun a test suite and get a report. It does this without transpiling and without a web-server. I try to replicate this with stealjs and systemjs since they both offer to transpile on the file with generating artifacts on the file system for the web browser and offer interfaces similar to requirejs that is being used currently. Unfortunately, in both cases CORS issues were hit because they attempt to load JS resources from the file system on asynchronously (at least with Chrome). It seems like we need cannot load ES6 into the web browser directly without a simple webserver - some possibilities are to 

- [ ] Not use ES6 and continue to use JavaScript for testing.
- [ ] Transpile tests ahead of time and add watching and browser sync tasks for testing.
- [ ] Require a simple web server to host testing assets.
- [x] Abandon web-browser based testing and just use CLI tooling with some approach for native ES6.
- [ ] Something I'm missing...

**Comment by dannon** [comment]
@jmchilton I haven't thought a whole lot about this, but I am now with #4827 wrapping up.  Obviously the tests fail completely.  Did you have any great new ideas in the past week?

**Comment by jmchilton** [comment]
Chose an option and rewrote tests in ES6. No more interactive web browser based testing 😢.

**Comment by dannon** [comment]
@jmchilton That's not actually true; you can use the interactive browser testing w/ karma and what we have right now.  Just open up a browser and connect to the karma server that starts up.
