### ISSUE TITLE
Release tarballs not updated with security patches.

### ISSUE THREAD

**Issue by rhpvorderman** [galaxyproject/galaxy#4848]
The [latest release tarball](https://github.com/galaxyproject/galaxy/releases) is 17.05 on may 24th.
[Ample security commits](https://github.com/galaxyproject/galaxy/commits/release_17.05) have been made to this branch since May 24th.

Furthermore, the releases do not contain a .git folder and are therefore **impossible** to patch, since the patches use git.

It therefore seems to me that everything on the [releases page](https://github.com/galaxyproject/galaxy/releases) is completely insecure.

**Comment by nsoranzo** [comment]
@rhpvorderman Please follow the instructions on https://galaxyproject.org/admin/get-galaxy/ , we generally use branches instead of tags/releases.

**Comment by rhpvorderman** [comment]
@nsoranzo 
Thank you. However, my issue is not that a secure galaxy is provided elsewhere. My issue is that an insecure galaxy is provided on the releases page.
Should an insecure option be provided to the users on the releases page?

**Comment by jmchilton** [comment]
@rhpvorderman 

I think you are right that we need to do something about this - we need to either always create release tags after we push security updates or we need to automate the deletion of all these "releases". Please understand though we neither create those releases ourselves nor advocate using them anywhere - it is cruft generated by Github by our tags as far as I can tell.

**Comment by rhpvorderman** [comment]
@jmchilton. Thank you for your answer.
The issue came up when checking if the docker galaxy image was updated with the latest security patches. It also downloads a tarball, but this is a branch tarball, and not a tag tarball. So the security patches are incuded. It did cause some confusion with me hence I filed the issue.
