### ISSUE TITLE
Optionally run jobs in unique cgroups

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#4862]
This would allow us to do a number of things directly without the need of scheduler support, including memory limiting and recording the memory usage metric without the need for collectl (by reading the cgroup's `memory.max_usage_in_bytes`).

**Comment by hexylena** [comment]
I wasn't under the impression that we could create/modify/destory cgroups as a non-root process? Did you have a plan for how to handle that?

**Comment by natefoo** [comment]
An administrator would need to create a group that Galaxy would be able to run jobs under, e.g.

```console
# cgcreate -a galaxy:galaxy -t galaxy:galaxy memory,cpu:galaxy
```

Then galaxy can:

```console
$ cgcreate -g memory,cpu galaxy/job_<id>
$ cgexec -g memory,cpu:galaxy/job_<id> /path/to/galaxy_<id>.sh
$ cgdelete -g memory,cpu galaxy/job_<id>
```

Although perhaps it's better to rely on the DRM to do the cgroup setup in the prolog/epilog, if it's possible to get the DRM to `cgexec` the job script.

I haven't looked in to the security of this yet.

**Comment by natefoo** [comment]
FWIW, Slurm already runs them in a cgroup if you use `TaskPlugin=task/cgroup`. But it looks like one big cgroup for all jobs on the node?:

```console
$ srun --pty /bin/bash
$ cat /proc/$$/cgroup
10:perf_event:/
9:cpuset:/
8:memory:/system.slice/slurmd.service
7:freezer:/
6:blkio:/system.slice/slurmd.service
5:net_cls,net_prio:/
4:devices:/system.slice/slurmd.service
3:pids:/system.slice/slurmd.service
2:cpu,cpuacct:/system.slice/slurmd.service
1:name=systemd:/system.slice/slurmd.service
```

**Comment by hexylena** [comment]
Oh that's awesome, I didn't realise that you could delegate like that. That's so helpful!

**Comment by scholtalbers** [comment]
FYI, on our slurm (17.11.3-2) setup the cgroup is created per job:
```
$ cat /proc/$$/cgroup
11:blkio:/
10:pids:/
9:perf_event:/
8:cpuacct,cpu:/slurm/uid_20239/job_12102491/step_0/task_0
7:hugetlb:/
6:cpuset:/slurm/uid_20239/job_12102491/step_0
5:freezer:/slurm/uid_20239/job_12102491/step_0
4:memory:/slurm/uid_20239/job_12102491/step_0/task_0
3:net_prio,net_cls:/
2:devices:/system.slice/slurmd.service
1:name=systemd:/system.slice/slurmd.service
```

**Comment by natefoo** [comment]
Oh neat, maybe this is a newer slurm (or, maybe I don't have it configured right, since I guess the slice in my case probably comes from systemd). Thanks @scholtalbers!

**Comment by hexylena** [comment]
So solution is: responsibility of job runner
