### ISSUE TITLE
prettier bug in comment indentation

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4865]
I think this should look different
```
/**
     * User clicked the checkbox in the table heading
     * @param  {context} event
     */
            selectAll: function(event) {
```

**Comment by dannon** [comment]
Pretty sure this was a bug that was just fixed in prettier, and will be fixed in the next release.  (https://github.com/prettier/prettier/pull/2470)

**Comment by dannon** [comment]
(assigning myself to remember to close this when prettier is updated, unless someone gets to it first)
