### ISSUE TITLE
Linking data overwrites source files when job finish method fails

### ISSUE THREAD

**Issue by ieguinoa** [galaxyproject/galaxy#4868]
The problem is, if the upload runs ok but then the job wrapper finish method fails, the runner calls fail() method afterwards: [https://github.com/galaxyproject/galaxy/blob/f4d45549cf9e59a6b3fe00b44744ef69683a149a/lib/galaxy/jobs/runners/init.py#L633](url) 
If the special case of upload by linking is not taken into account then the fail method overwrites the files that you are trying to link!

Not sure what are the odds of finish method failing, in my case it was because the data in peek was containing unicode character and that couldn't be inserted in the database with latin-1 coding format. Don't know where this character came from since its a fastq file but this can happen, for example, when trying to link a pdf as fastqsanger.bz2. (that's the test case I used)
Then your input pdf is overwritten !!
The solution for this case should be simple #4858 , but I'm reporting this because the  link_file_check solution (https://github.com/ieguinoa/galaxy/blob/74dc8a0cb55f91d9efa37936446a2d6b1304195a/lib/galaxy/jobs/__init__.py#L1739) may be ignored somewhere else.

**Comment by mvdbeek** [comment]
Thanks for reporting and fixing this (https://github.com/galaxyproject/galaxy/pull/4858) @ieguinoa !
