### ISSUE TITLE
Galaxy run.sh and common_startup.sh source virtual env without passing empty arguement

### ISSUE THREAD

**Issue by IyadKandalaft** [galaxyproject/galaxy#4882]
When the run.sh and common_startup.sh source the virtual environment using a command as follows
` . $GALAXY_VIRTUAL_ENV/bin/activate`
causes the parameters of the parent script to be passed in as arguments. This is effectively the same as
` . $GALAXY_VIRTUAL_ENV/bin/activate $@`

Some virtual environments such as virtualenv wrapper and conda environments interpret these arguments and fail to load as a result.  

The proposed fix is to modify sourcing the virtual environment's activate scripts as follows
` . $GALAXY_VIRTUAL_ENV/bin/activate ""`
which stops the parent script's arguements $@ from being passed in to the virtual environment's activate script.  As a result, conda environment and virtualenv wrapper environments can function as intended.

**Comment by nsoranzo** [comment]
@IyadKandalaft Thanks for report!

This seems to be a Bash extension, it's not in POSIX: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#dot

The proposed workaround seems valid, do you want to open a pull request to get appropriate credit?

**Comment by IyadKandalaft** [comment]
@nsoranzo - i'm digging a little deeper into it.  It seems that run.sh is fine because it consumes all the arguments in the while loop before sourcing the virtualenv.  common_startup.sh on the other hand does not consume them.  The issue is that DASH, unlike BASH, will pass the parent script's arguments to the a child script that is being sourced regardless.  It might be best to fix the common_startup.sh to consume the variables to remain POSIX compliant.

Here's an example using DASH on ubuntu 14.04
parent.sh contains:
```
#! /bin/sh

echo Parent.sh params are $@

. "/tmp/child.sh" ""
```
child.sh contains
```
$ cat child.sh 
#! /bin/sh

echo Child params are $@
```
I execute the parent with a parameter and the child automatically sees the parameter as its own.
```
$ sh parent.sh --parent-param
Parent.sh params are --parent-param
Child params are --parent-param
```

**Comment by IyadKandalaft** [comment]
I think I've settled on leaving run.sh alone since it consumes the args.  I'm proposing that I'll submit a pull request to modify common_startup.sh to iterate over the args and shift them as they are recognized.  Unrecognized arguments should be disposed of.  That way, we can leave sourcing the virtual environments as is and remaining compliant with the POSIX approach and achieving maximum compatibility.

**Comment by nsoranzo** [comment]
Ping @natefoo

**Comment by natefoo** [comment]
Discarding them in a sourced file would discard them for the parent as well, which I don't think we want. The safest option may be to store the variables before sourcing `activate` and restore them after:

parent.sh:

```bash
#!/bin/dash

args="$@"
echo "parent params are $@"
. ./child.sh
echo "parent params after child are $@"
set -- "$args"
echo "parent params after restore are $@"
```

child.sh:

```bash
#!/bin/dash

echo "child params are $@"
set --
echo "child params after unsetting are $@"
```

Output:

```sh-session
$ ./parent.sh -asdf   +foo bar "baz   quux"
parent params are -asdf +foo bar baz   quux
child params are -asdf +foo bar baz   quux
child params after unsetting are 
parent params after child are 
parent params after restore are -asdf +foo bar baz   quux
```

I put the save/restore in the parent here but in Galaxy they should probably go immediately before/after the virtualenv sourcing.

**Comment by hexylena** [comment]
>  I'm proposing that I'll submit a pull request

Closing in lieu of such a PR. Thanks for looking into this everyone!
