### ISSUE TITLE
cannot visualize vcf on iobio using Main

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4890]
reported by @nicoleruiz

for both test vcf files I have tried (new uploads) it ends up failing in the preparation status, see screenshot

![screenshot 2017-10-27 15 49 08](https://user-images.githubusercontent.com/1814954/32122475-68fc0eaa-bb2e-11e7-83b0-a8e861d1aa1e.png)

**Comment by jennaj** [comment]
The visualization is still a problem. The iobio application opens, but the Galaxy URL never submits.

Can anyone else still reproduce?

**Comment by jennaj** [comment]
Works now, thanks! Closing

I had to make a copy of the original history with the failed indexes to get it to go through. If a user asks, they should do the same. Having prior indexes clear (and not cache) would be the longer term solution, re: https://github.com/galaxyproject/usegalaxy-playbook/issues/89#issuecomment-407514900
