### ISSUE TITLE
Main fails to unzip a vcf.gz file

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4892]
same file works fine for me locally (on dev)

[test.vcf.gz](https://github.com/galaxyproject/galaxy/files/1423277/test.vcf.gz)

![screenshot 2017-10-27 15 54 52](https://user-images.githubusercontent.com/1814954/32122678-31f1659e-bb2f-11e7-9c24-962c17519b0a.png)

**Comment by jennaj** [comment]
Files like `vcf.gz` uploaded with autodetect for datatype used to uncompressed `vcf` (as recently as ~3 weeks ago). 

Now they are assigned `vcf_bgzip` with a metadata warning. This test history has a vcf dataset I downloaded, gz compressed locally, then uploaded back up with autodetect. https://usegalaxy.org:/u/jen/h/test-vcfgz-upload

Looks like there are a few moving parts here.

Should we consolidate the tickets?

**Comment by jennaj** [comment]
Annnddd ... now looks that is fixed again in the code. Sorry, didn't refresh and see that was done already.

The other ticket (https://github.com/galaxyproject/galaxy/issues/7364) is different -- the implicit converter should work for that problem. So keep both.

**Comment by jennaj** [comment]
thanks @nsoranzo !!
