### ISSUE TITLE
bib2json regression in dev

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4906]
This piece of code was meant to prevent the need to hack ``bibtex.js`` so we could just pull it npm. I don't think it works though - ``_`` doesn't mutate its arguments it creates new ones. I tried setting the properties directly and that doesn't seem to work either.

```
    _.extend(parseBibtex.ENTRY_TYPES_, {
        online: 998, // Galaxy MOD: Handle @online entries for preprints.
        data: 999 // Galaxy MOD: Handle @data citations coming from figshare.
    });
```

The latest Github variant of this package supports online but it hasn't been published to npm in a very long time. figshare DOIs no longer return these ``data`` entries so I'd be fine with just getting the latest variant of this from GIthub somehow - otherwise I think we need a better hack or need to restore our variant.

Ping @dannon - any thoughts?

I have a test case to verify some of this stuff but it fails obviously - let me know if that would be helpful.

**Comment by dannon** [comment]
Sure, I'll take a look.  Yeah, the intent was monkey patching parseBibtex so we didn't have to run a custom version.

And, of course, that test case would be handy!

**Comment by jmchilton** [comment]
Thanks @dannon - FWIW I'd resolve #4827 first and then revisit this. It won't be pressing until 18.01 is branched. Up to you though - thanks again.

**Comment by dannon** [comment]
@jmchilton Heh, a good point.  I thought this would be a pretty simple fix, but ended up down the rabbithole a bit on javascript tex parsing libraries.

**Comment by jmchilton** [comment]
@dannon Been down that rabbithole myself 😄 - it is deep and there is rabbit poop everywhere.

**Comment by dannon** [comment]
Yep.  And the documentation is awesome, everywhere. /s  Mathjax's docs even pull a lmgtfy in the 'maybe you shouldn't use this if you need a LaTeX-to-HTML converter' section.
