### ISSUE TITLE
pysam updated : cannot import name ctabix

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#4938]
pysam has been updated and then this will fail:
`from pysam import ctabix`
and it should be replaced by:
`from pysam import libctabix as ctabix`

[http://pysam.readthedocs.io/en/latest/release.html?highlight=import#release-0-10-0](url)
[https://github.com/pysam-developers/pysam/issues/446](url)

Those files are impacted in galaxy lib:

- ./galaxy/visualization/data_providers/genome.py
- ./galaxy/datatypes/converters/bgzip.py
- ./galaxy/datatypes/converters/interval_to_tabix_converter.py
- ./galaxy/datatypes/converters/tabular_to_dbnsfp.py
- ./galaxy/datatypes/converters/vcf_to_vcf_bgzip.py

**Comment by mvdbeek** [comment]
It's not as simple a fix, please use the pysam referenced in https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/dependencies/requirements.txt#L73.

We're working on this in https://github.com/galaxyproject/galaxy/pull/4497.

**Comment by FredericBGA** [comment]
ok, sorry, I've checked for "pysam" in open issues but not in PR.

**Comment by mvdbeek** [comment]
no worries, it's good to keep dependencies updated, but it's also the safest route to use what is specified in the requirements.txt
