### ISSUE TITLE
Local Galaxy cant upload data

### ISSUE THREAD

**Issue by qchengray** [galaxyproject/galaxy#4940]
I try to build a local Galaxy platform, but I can't upload the data to execute the program. the error is : Failed: Bad Request (400). Multiple values provided but parameter dbkey is not expecting multiple values.

**Comment by hexylena** [comment]
No, `dbkey` is a single value, the current interface does not allow uploading of datasets with multiple dbkeys. I'm afraid there's not enough information here to help so I'm closing, you can also use https://help.galaxyproject.org for issues like these

**Comment by qchengray** [comment]
Thank you very much！

**Comment by qchengray** [comment]
> No, `dbkey` is a single value, the current interface does not allow uploading of datasets with multiple dbkeys. I'm afraid there's not enough information here to help so I'm closing, you can also use https://help.galaxyproject.org for issues like these

Thank you very much！
