### ISSUE TITLE
Local galaxy does not allow CORS

### ISSUE THREAD

**Issue by ricardo-hb93** [galaxyproject/galaxy#4941]
Hello everyone. I’m trying to do ajax requests to a local instance of Galaxy, but I’m facing a problem. When I try to do a get of "http://localhost:8080/", it shows a message telling it needs the CORS (Cross Origin Resources Sharing) header. I tried creating the galaxy.ini file, and changing this line:
allowed_origin_hostnames = None
By this one:
allowed_origin_hostnames = /.*/
But the same error message appears. I’d like to know what do I have to do in order to actually configure this parameter in my Galaxy instance.

**Comment by hexylena** [comment]
you'll need to specify the hostname you're making the request from. You might be able to use `allowed_origin_hostnames = *` but this isn't as secure.

**Comment by ricardo-hb93** [comment]
Hi, thanks for your answer. I tried also using `allowed_origin_hostnames = *`, but the same message appears when I do an ajax request. I wonder if there are other configuration files to take into account when I want to configure this characteristic.

**Comment by hexylena** [comment]
If not, you can always use the hostname you are making the requests from?

**Comment by ricardo-hb93** [comment]
Alright, it worked, thanks :+1:
