### ISSUE TITLE
New toolshed categories for Annotation and CRISPR?

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/galaxy#4955]
Hello, I was wondering if I could request two new categories to be added to the toolshed please so I can add them to the .shed.yml files for some new tools I'm adding to IUC. Annotation is for the annotateMyIDs tool (PR here: https://github.com/galaxyproject/tools-iuc/pull/1535) and CRISPR is for MAGeCK (https://sourceforge.net/projects/mageck/) which I'll be submitting soon.

**Comment by martenson** [comment]
Can you give me names and descriptions of such categories please? 

ping @nsoranzo @bgruening

**Comment by nsoranzo** [comment]
Maybe "Genome annotation"? I'd move e.g. `prokka` and other tools there then.

Instead of "CRISPR", I'd propose the more general "Genome editing".

**Comment by mblue9** [comment]
"Genome annotation" and "Genome editing" sound good to me!

**Comment by mblue9** [comment]
For descriptions for those categories would something like "Tools for annotating genomic information" and "Tools for analyzing genome editing data" work?

**Comment by mblue9** [comment]
Would be good to add a category for single-cell analysis too at some stage, as have you seen how many tools there are for that now!!... :open_mouth:
https://www.scrna-tools.org/
https://github.com/seandavi/awesome-single-cell

**Comment by bgruening** [comment]
ping @martenson 
I upvoted the suggestions from @mblue9 and @nsoranzo . Makes sense for me.

**Comment by martenson** [comment]
I have created "Genome annotation" and "Genome editing" on both TTS and MTS. What about single cell @bgruening ?

**Comment by martenson** [comment]
We agreed with @nsoranzo that single cell can wait until there are tools that would make use of it. Thanks @mblue9 !

**Comment by mblue9** [comment]
Thanks @martenson for adding these categories!
