### ISSUE TITLE
enable_new_user_preferences should be removed from galaxy.ini

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#4956]
Its good enough, isn't it?

**Comment by dannon** [comment]
This setting is completely ignored by the configuration, unless I'm missing something.  It's always enabled.

(so, yes, we should remove the no-longer-valid option! :) )

**Comment by dannon** [comment]
Opened #4957; I'm looking at these beta features and there are several no-longer-valid options; I'll clean them up.
