### ISSUE TITLE
reports app is trying to load webhooks

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#4969]
This is what is in the console twice after loading the reports homepage.

`VM555:1 GET http://127.0.0.1:9001/api/webhooks/onload/all 404 (Not Found)`

**Comment by dannon** [comment]
(Whoops, thought this was threaded into #4967 replying via mail)

Webhooks have never worked in the reports app; I'll fix that in a sec.

**Comment by nsoranzo** [comment]
Fixed by #5116.
