### ISSUE TITLE
Workflow handlers are not working as expected

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#4976]
Here is a list of what we found during our trial of workflow handlers.

1) We just defined work0 and work1 (see below) but in the database they ended up as work2 and never were scheduled
  - the jobs ended up in nowhere, a user could not see them in the history
  - setting the work2 workflows to `failed` gave also no visual indication 
2) work2 workflows, even as we started additional handlers (work2, work4 in supervisord) were not picked up
  - also not after restarting uwsgi and/or handlers

As we understood the jobs, after scheduled by the workflow-scheduler ( workflow_invocations -> workflow_state = scheduled), still ended up in the jobs-queue and the normal handlers needs to schedule them? Is this correct?

```
[program:workflow_handler]
 command         = /usr/local/galaxy/galaxy-dist/.venv/bin/python /usr/local/galaxy/galaxy-dist/scripts/galaxy-main -c /usr/local/galaxy/galaxy-dist/config/galaxy.ini --server-name=work%(process_num)s --log-file=/var/log/galaxy/workflow_handler_%(process_num)s.log
 directory       = /usr/local/galaxy/galaxy-dist/
 process_name    = work%(process_num)s
 numprocs        = 2
 umask           = 022
 autostart       = true
 autorestart     = true
 startsecs       = 20
 user            = galaxy
 startretries    = 4
 environment     = VIRTUAL_ENV="/usr/local/galaxy/galaxy-dist/.venv/",PATH="/usr/local/galaxy/galaxy-dist/.venv/bin:%(ENV_PATH)s",PYTHON_EGG_CACHE="/usr/local/galaxy/galaxy-dist/.venv/.python-eggs"

```

```
<?xml version="1.0"?>
<!-- If workflow_schedulers_conf.xml exists it defines the workflow scheduling
     plugins to load and how to configure them. Currently only the core workflow
     scheduling is available.
-->
<workflow_schedulers default="core">
  <!-- Each element in this file corresponds to a workflow scheduling plugin
       in lib/galaxy/workflow/schedulers. -->

  <!-- Core plugin schedules whole workflow at outset inside Galaxy and doesn't
       require any external dependencies. -->
  <core id="core" />

  <handlers default="workflow_handlers">
    <handler id="work0" tags="workflow_handlers" />
    <handler id="work1" tags="workflow_handlers" />
  </handlers>
</workflow_schedulers>
```

**Comment by nsoranzo** [comment]
@bgruening @erasche I've been happily using a separate workflow handler for about a year, is this still a problem for you?

**Comment by hexylena** [comment]
Have not been brave enough to re-test. We'll close this for now.
