### ISSUE TITLE
Drag and drop in multi history view broken

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#4983]
This is on the latest dev

<img width="1440" alt="screen shot 2017-11-11 at 19 31 07" src="https://user-images.githubusercontent.com/6804901/32692404-b484fd38-c717-11e7-9b11-e1768f8124ba.png">

**Comment by dannon** [comment]
@mvdbeek Looks like this was broken in #4933.  I see what the problem is and will PR a fix in a sec.
