### ISSUE TITLE
missing python module ipaddress

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#4999]
After update to 17.09 `sh manage_db.sh upgrade` gives an error about a missing python module 

```
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/config.py", line 7, in <module>
    import ipaddress
ImportError: No module named ipaddress
```

My workaround was to `pip install py2-ipaddress` in galaxy's python2 venv. 

I guess I should switch to python3?

**Comment by nsoranzo** [comment]
No, Python3 support is still far away. I think that `ipaddress` is missing from our requirements.txt file, PR incoming.

**Comment by bernt-matthias** [comment]
There were a few more missing. Here are all with versions: 

py2-ipaddress 3.4.1
h5py 2.7.1
bz2file 0.98

**Comment by mvdbeek** [comment]
Did you run scripts/common_startup.sh before running manage_db.sh ? Some of these are new dependencies in 17.09, but I think they are correctly listed https://github.com/galaxyproject/galaxy/blob/release_17.09/lib/galaxy/dependencies/pinned-requirements.txt#L16 (but yes, ipadress seems to be missing)

**Comment by bernt-matthias** [comment]
No I didn't. I followed https://galaxyproject.org/admin/maintenance/ should I add this step there?

**Comment by nsoranzo** [comment]
> No I didn't. I followed https://galaxyproject.org/admin/maintenance/ should I add this step there?

Yes, definitely, before `sh manage_db.sh upgrade`. It's good to run `./scripts/common_startup.sh` anyway before restarting the server, otherwise multiple processes may try to update the virtualenv at the same time.
