### ISSUE TITLE
Galaxy startup fails during migration due to too many open files

### ISSUE THREAD

**Issue by crashfrog** [galaxyproject/galaxy#5009]
Encountered this during a planemo test but it seems to be a Galaxy issue. Migrations don't seem to close file handles? See attached output log of ```planemo t --install_galaxy```

[errors.txt](https://github.com/galaxyproject/galaxy/files/1472478/errors.txt)

`OSError: [Errno 24] Too many open files: '/private/var/folders/55/98d70mnj5ps9nwffx39skrw40009rn/T/tmp2lhrw74a/galaxy-dev/lib/galaxy/datatypes/converters/interval_to_interval_index_converter.py'`

`IOError: [Errno 24] Too many open files: './lib/galaxy/datatypes/converters/bed_to_gff_converter.xml'`

**Comment by mvdbeek** [comment]
Thanks for reporting this. This is a problem with watchdog on OSX (it's using kqueue instead of FSEvents, which it should), I'll look into this (unless someone beats me to it, pretty busy till friday). In the meantime you could use `--galaxy_branch 17.05` or  increase the number of allowed descriptors with `ulimit -n 1024` as per https://pypi.python.org/pypi/watchdog.

**Comment by crashfrog** [comment]
Great, thanks for taking a look. Googling wasn't giving any joy. I'll try your workarounds. Thanks!

**Comment by crashfrog** [comment]
Hi,

```--galaxy_branch dev``` seemed to work for ```planemo serve``` but now I'm seeing the same error with ```planemo test``` regardless of which branch I specify, and I do already have ```ulimit -n 1024``` in my ```.profile``` and it's had no effect. I'm still seeing Galaxy startup fail on too many open files. Is there a fix for this, yet? It's really stalled our tool development.

**Comment by crashfrog** [comment]
Hi, not fixed. ```planemo test``` on all galaxy release versions fails under Mac OS X with 

```IOError: [Errno 24] Too many open files: './lib/galaxy/datatypes/converters/bam_to_bigwig_converter.xml'```

from kqueue.
