### ISSUE TITLE
Tool help text is missing in workflow mode

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#501]
Every tool should offer a better parameter description in it's help section. But this information is not displayed in the workflow mode. We can include a small symbol next to every parameter, which displays the help text on mouse hover.

from @bgruening on [trello](https://trello.com/c/i4LNJdDj/2318-html-tags-shown-in-toolshed-banner-messages)

**Comment by guerler** [comment]
I agree with this. In the current dev version we are actually showing the help text. Now, we could either leave it this way or move the help text to a tooltip/mouse-over popup.

**Comment by nsoranzo** [comment]
@bgruening I think this can be considered solved, if not please reopen!
