### ISSUE TITLE
Better tool_config_file default in galaxy.ini

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#502]
Currently the tool_config_file section of galaxy.ini reads like this:

```
# Tool config files, defines what tools are available in Galaxy.
# Tools can be locally developed or installed from Galaxy tool sheds.
# (config/tool_conf.xml.sample will be used if left unset and
# config/tool_conf.xml does not exist).
#tool_config_file = config/tool_conf.xml,shed_tool_conf.xml
```

If you activate that setting by just removing the # from the last line, then, for an otherwise unmodified clone of Galaxy, you're getting an error
1. because the last entry should be config/shed_tool_conf.xml (include the path)
2. because Galaxy then stops using config/tool_conf.xml.sample as a fallback if config/tool_conf.xml does not exist
3. even config/shed_tool_conf.xml does not initially exist

So users have to change three things (add the missing path, and manually copy and rename both tool_conf.xml.sample and shed_tool_conf.xml.sample) to be able to use this line.

Either:
- the .sample files should always be used as fallback, not just with the line commented out
- the line should list the .sample files
- Galaxy should auto-generate tool_conf.xml and shed_tool_conf.xml from the .sample files on first run (didn't it do that in earlier releases ?)

from [trello](https://trello.com/c/RSmsIShe/2280-better-tool-config-file-default-in-galaxy-ini)

**Comment by jmchilton** [comment]
`shed_tool_conf.xml` -> `config/shed_tool_conf.xml` has been fixed.

I'm happy with the current state - the default states the sample will be used and if the line is uncommented the sample definitively should not be used in my opinion.

So this is half fixed and half wontfix.
