### ISSUE TITLE
HTML tags shown in ToolShed banner messages

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#503]
Using the main ToolShed or the TestToolShed (in Safari on a Mac), after creating a new repository, a green banner message was shown with the raw HTML bold tags visible:

```
Repository <b>package_biopython_1_65</b> has been created.
```

After uploading a file, the same problem was observed.

From @peterjc on [trello](https://trello.com/c/i4LNJdDj/2318-html-tags-shown-in-toolshed-banner-messages)

@martenson is this still an issue?

**Comment by martenson** [comment]
probably a remnant of over escaping, we are tracking them here: https://trello.com/c/oX6i51Mn/2298-back-off-over-escaping

**Comment by hexylena** [comment]
This looks to have been fixed, judging by the trello card.
