### ISSUE TITLE
Client Unit Testing Overhaul

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#5030]
We discussed client unit testing again today in #galaxyproject (https://botbot.me/freenode/galaxyproject/2017-11-16/?msg=93612098&page=1), and again I think we're all agreed that we need to swap to Karma to drive our client testing.  

- Karma has a webpack plugin, so we can quit relying on the individually transpiled code we don't actually ship to clients anyway for testing. https://github.com/webpack-contrib/karma-webpack  With this shift, and the bundling of the rest of the require()d code, we can get rid of the whole gulp-scripts build stream.
- Karma has a qunit plugin, so we shouldn't have to rewrite all the tests.  https://github.com/karma-runner/karma-qunit
- Karma-driven webpack should make it easy to test `.vue` single file components using the same loaders and processing we use for the live code.  The alternative for `.vue` is something like vueify via gulp to generate individual modules we can require(), but that's not ideal for a lot of reasons.

**Comment by dannon** [comment]
Added an 18.01 milestone since w/ #4978 and the addition of Vue single file components, our current Qunit testing is going to be broken.

**Comment by jmchilton** [comment]
Karma is a thing now and all our tests are running - if not perfectly so I'm going to close this out - hope that is okay.

**Comment by dannon** [comment]
Yep, definitely functional enough to close this out and keep on improving it naturally down the road.
