### ISSUE TITLE
Manage installed tools should not show all installed versions? 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5034]
Currently all installed tool versions are shown in "Manage installed tools" and older versions are marked with "A newer installable revision is available for this repository". 

Example: I have installed clustalw revisions f8aad74cc8c1 and d6694932c5e0 which seem to be the latest revisions of versions 2 and 3, respectively. Version 2 shows up as "A newer installable revision is available for this repository"  and the dropdown menu allows to update which leads to an error message: Revision <b>d6694932c5e0</b> of repository <b>clustalw</b> owned by <b>devteam</b> has already been installed.

My main concern is that it should be easy to spot tool versions for which new revisions are available. 

This is Galaxy 17.09

**Comment by mvdbeek** [comment]
Yep, that's on the roadmap https://github.com/galaxyproject/galaxy/issues/1928
