### ISSUE TITLE
Frontend rendering in iOS

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/galaxy#5035]
Rendering is not as it should be in iOS 11 and Safari. Maybe not the highest priority issue... :) With macOS High Sierra and Safari it works. Can someone confirm this bug?
![a7a165ab-9d14-46d2-8e14-094090edb128](https://user-images.githubusercontent.com/13435136/32970493-7e84fedc-cbe9-11e7-9192-b1216332c6c7.jpeg)

**Comment by martenson** [comment]
All usegalaxy.org, Freiburg Galaxy and latest dev render fine in Safari on MacOS Sierra 10.12.6. What exact configuration do you see this problem at?

**Comment by joachimwolff** [comment]
With iOS 11.1 and Safari on an iPad Pro 10.5 inch.

**Comment by martenson** [comment]
@joachimwolff did this improve?
