### ISSUE TITLE
reports_wsgi.ini should be renamed

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#504]
reports_wsgi.ini should be renamed to reports.ini to be consistent with galaxy.ini

from @bgruening on [trello](https://trello.com/c/DV88kzCF/2195-reports-wsgi-ini-should-be-renamed)

**Comment by souravsingh** [comment]
I would like to work on the issue.

**Comment by bgruening** [comment]
@souravsingh awesome! Let us know if you need any help!

**Comment by souravsingh** [comment]
I wasn't able to find the reports_wsgi.ini file.Am I doing something wrong?

**Comment by bgruening** [comment]
@souravsingh here you go: https://github.com/galaxyproject/galaxy/blob/dev/config/reports_wsgi.ini.sample
It's called sample in git. The admin can rename it to `reports_wsgi.ini` and change the config without getting merge conflicts with new versions of the same (*.sample) file.

**Comment by martenson** [comment]
fixed via https://github.com/galaxyproject/galaxy/pull/1181
thanks @souravsingh
