### ISSUE TITLE
Conda errors after conda upgrade 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5041]
After the upgrade to 4.3.24 I observed two errors:

`/gpfs1/data/galaxy_server/galaxy/database/dependencies/_conda/bin/conda create -y --override-channels --channel iuc --channel bioconda --channel conda-forge --channel defaults --channel r --unknown --offline --prefix /gpfs1/data/galaxy_server/galaxy/jobs_dir/003/3769/conda-metadata-env --file ./database/tmp/jobdepsqumoqlf795a38a38496af1ff491d0cf89e7e5d9fe737e5c36da3dd56c71ad608bb9b15/__samtools@1.3.1 > /dev/null
`

gives

```
CondaError: RuntimeError('EnforceUnusedAdapter called with url https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2017.11.5-0.tar.bz2\nThis command is using a remote connection in offline mode.\n',)
CondaError: RuntimeError('EnforceUnusedAdapter called with url https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2017.11.5-0.tar.bz2\nThis command is using a remote connection in offline mode.\n',)
CondaError: RuntimeError('EnforceUnusedAdapter called with url https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2017.11.5-0.tar.bz2\nThis command is using a remote connection in offline mode.\n',)
```

`/gpfs1/data/galaxy_server/galaxy/database/dependencies/_conda/bin/conda clean --tarballs -y`

```
Cache location: 
There are no tarballs to remove
galaxy.jobs.runners ERROR 2017-11-20 10:27:27,205 (3769) Failure preparing job
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/jobs/runners/__init__.py", line 175, in prepare_job
    modify_command_for_container=modify_command_for_container
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/jobs/runners/__init__.py", line 209, in build_command_line
    container=container
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/jobs/command_factory.py", line 112, in build_command
    __handle_metadata(commands_builder, job_wrapper, runner, remote_command_params)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/jobs/command_factory.py", line 203, in __handle_metadata
    kwds={'overwrite': False}
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/jobs/__init__.py", line 1695, in setup_external_metadata
    dependency_shell_commands = metadata_tool.build_dependency_shell_commands(job_directory=self.working_directory, metadata=True)
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/__init__.py", line 1450, in build_dependency_shell_commands
    tool_instance=self
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/deps/__init__.py", line 113, in dependency_shell_commands
    return [dependency.shell_commands(requirement) for requirement, dependency in requirement_to_dependency.items()]
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/deps/resolvers/conda.py", line 470, in shell_commands
    self.build_environment()
  File "/gpfs1/data/galaxy_server/galaxy/lib/galaxy/tools/deps/resolvers/conda.py", line 465, in build_environment
    raise DependencyException("Conda dependency seemingly installed but failed to build job environment.")
DependencyException: Conda dependency seemingly installed but failed to build job environment.
```

I guess the second is a consequence of the first.

**Comment by bernt-matthias** [comment]
Workaround: remove the conda package ..

**Comment by mvdbeek** [comment]
I guess https://github.com/galaxyproject/galaxy/issues/5024 would address that.

**Comment by mvdbeek** [comment]
I meant post that in #5039

**Comment by bernt-matthias** [comment]
Already forgot this one. Thanks.

**Comment by mblue9** [comment]
Hi, 

I don't know if I should ask this here but we're on conda 4.3.24 and I'm having trouble installing some tools, specifically dexseq at the moment.

I'm wondering if I can just do a conda update conda? which I think will give v4.5.12.

This is our production instance so am a bit wary of just trying it there.

It's also Galaxy 17.09 in case that makes a difference.

**Comment by bgruening** [comment]
That should not be a problem and you could always go back to the old conda version if you need to.

**Comment by nsoranzo** [comment]
@mblue9 Using the latest `conda` *should* work, and the process to update is indeed `/path/to/miniconda3/bin/conda update conda` . I'd also recommend to update to a security-supported release, see https://github.com/galaxyproject/galaxy/blob/dev/SECURITY_POLICY.md#supported-versions .

**Comment by mblue9** [comment]
Ok great, thanks for the advice guys!

@nsoranzo I would so love us to update, that was supposed to happen months ago, but due to several reasons I'm stuck with 17.09 for another couple of months at least 😢

**Comment by bernt-matthias** [comment]
Guess we can close this one.
