### ISSUE TITLE
API key used isn't logged anywhere

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#505]
As far as I can tell...the API key used isn't logged anywhere (apache, uWSGI, paste, handler logs).

If old API keys are kept around, ostensibly for auditing purposes, the API key used for a given request should probably be logged?

(here I understand "auditing purposes" to mean, for example, "someone uploaded bad things to our galaxy")

submitted by @erasche on [trello](https://trello.com/c/xK5ha2h0/2173-api-key-used-isn-t-actually-logged-anywhere)

**Comment by dannon** [comment]
I'm not sure I understand this issue.  Saving API keys in logs does not seem to be a safe idea at all to me.

For auditing purposes, you'd still see which _user_ uploaded the data, regardless of whether or not their API key changed over time.

**Comment by hexylena** [comment]
Hmm, you raise a fair point, if we're still seeing which user uploaded the data, then that's acceptable. 

It just seemed like "if the database specifically expires keys, then it should be logged somewhere auditable".
