### ISSUE TITLE
trackster - add a custom build link broken

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5052]
Menu link to 'new track browser' (http://127.0.0.1:8080/visualization/trackster) opens a modal in which the link to Add a Custom Build (http://127.0.0.1:8080/user/dbkeys?use_panels=True) is ultimately yielding this js error: `http://127.0.0.1:8080/undefined 404 (Not Found)`  and Galaxy `Failed to load resource undefined.`

**Comment by millelog** [comment]
Had the same issue. It looks like the link under new track browser for adding a custom build links to some old way dealing with custom builds? I was able to create one by going to users->custom builds and then that one showed up in the list under new track browser to use.

**Comment by dannon** [comment]
This was fixed in cd91e8d85cb, which is in release_18.01, so I'm closing this issue out.

@millelog What revision of Galaxy are you using?
