### ISSUE TITLE
strip build artefacts out of the Galaxy codebase - make the git repo smaller

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#5057]
@jmchilton discovered that https://github.com/galaxyproject/galaxy/pull/4978, which we all wanted to see happen so eagerly (thanks @dannon), added a bunch of MBs to the git repo of Galaxy. This has triggered an interesting discussion on IRC/gitter and I think it is worth to evaluate if we can strip out some MB of build artifacts to generally trim down the size of Galaxy's repo.

This could happen after the we agreed on how to handle the new client side builds and how to handle artifacts in general.

Just wanted to track the issue so that we keep track of our repo size.

**Comment by dannon** [comment]
Yep, I imagined we'd do something like this when package-based installations were the norm.  +1.  I've stripped the sourcemaps out in #5054, and am working on refactoring bundles and bundle-loading to trim the deployed application size down a bit.

That said, repo size is probably the least of our concerns right now ;)

**Comment by hexylena** [comment]
I think this is done! :tada::tada:
