### ISSUE TITLE
"View all histories" shows nothing when coming from deleted history

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5061]
Steps to reproduce (in 17.09): 

- "Delete permanently" in the history menu
- "View all histories"

Shows empty screen. 

Workaround: create a new history and then "View all histories"

**Comment by martenson** [comment]
@bernt-matthias was that your only history that you deleted?

**Comment by bernt-matthias** [comment]
no: there are many. as soon as I create a new one all are shown again.

**Comment by dannon** [comment]
@bernt-matthias Thanks for the report, I'll take a look!

**Comment by dannon** [comment]
Just to update the issue, I reproduced this locally (in dev, too), and will work on a fix.
