### ISSUE TITLE
Numpad doesn't work for integer inputs

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#507]
Just had another user who could reproduce this (on a different OS+browser), so I'm reporting it here.

Numerical inputs (just an `type="integer"`) won't accept entry from numpads (num lock is set correctly), only from the normal numeric keys above the keyboard on a standard QWERTY keyboard.

cc @guerler 

from @erasche and @Unode on [trello](https://trello.com/c/Ix3U8pFI/2602-numpad-doesn-t-work-for-integer-inputs). 

Confirmed this is still a bug on `:dev` for numerical inputs. Text inputs work just fine.

**Comment by guerler** [comment]
Should be fixed later today.

**Comment by hexylena** [comment]
Wonderful, thanks @guerler!
