### ISSUE TITLE
Too many hashtags with huge input collections

### ISSUE THREAD

**Issue by arbernard** [galaxyproject/galaxy#5100]
Hello everyone,

As discussed recently on Gitter with @dannon, the new Hashtag system can cause some display issues (and a slower response time on many actions that can be performed on Galaxy histories) in one particular case.

For example, if you have a tool that takes a huge collection of dataset (like a hundred datasets) as input and generate several output files then each output dataset will have as many hashtags as there are datasets in the input collection.

In this case, browsing the history or select input datasets on the parameter selection page of a tool/workflow becomes really slow and hard.

Limiting the number of displayed hashtag can be an initial solution. A switch that allow the user to hide/show hashtags might be good too.

I also think that, instead of displaying the hashtags of every dataset of the input collection, it might be better to just display a single hashtag derived from the name of the input collection.

Thanks in advance for the fix :)

----

**Visual examples of the issue:**

![too_many_hashtags_in_history](https://user-images.githubusercontent.com/25177525/33434629-1fe95480-d5e0-11e7-802b-8f5700677d95.png)

![too_many_hashtags_in_drop-down_menus](https://user-images.githubusercontent.com/25177525/33434636-26b01ae2-d5e0-11e7-8886-6d8a02f64872.png)

**Comment by mvdbeek** [comment]
Of course it would be great to support this use case, the elephant in the room here is that I'm not sure adding a tag per dataset is a great idea. We also touched upon this briefly in https://github.com/galaxyproject/galaxy/issues/4212

**Comment by dannon** [comment]
Thanks for writing this up @arbernard.  The rendering of nametags definitely wasn't designed with this in mind; I'll work on a few options today.

**Comment by arbernard** [comment]
Thanks @dannon :)

In the meantime, if anyone else is encountering the issue, please know that there is a manual workaround to continue using your affected histories.

As @dannon explained on Gitter, you can create bookmarklets in your browser to execute a javascript command that will hide all hashtags (until refresh).

To hide the hashtags of the datasets in an history use this bookmarklet: `javascript: $(".dataset .nametags").hide()`

To hide the hashtags of the datasets in drop-down menus use this bookmarklet: `javascript: $(".ui-tags .label").hide()`
