### ISSUE TITLE
there is no direct link to undelete collection

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5102]
The feature exists and is accessible through 'operations on multiple datasets' menu. We might want to extend the shorcut here too.
![screenshot 2017-11-30 10 46 35](https://user-images.githubusercontent.com/1814954/33439575-c65f6acc-d5bb-11e7-876c-9dc78b802bdb.png)

edit: not sure about the 'permanently delete' feature and its handling with collections...

**Comment by mvdbeek** [comment]
xref https://github.com/galaxyproject/galaxy/issues/2319

**Comment by mvdbeek** [comment]
(I think the permanently undelete just halts the delete operation)

**Comment by martenson** [comment]
@mvdbeek permanently remove it from disk is 'user purge', no?
