### ISSUE TITLE
Tool Shed is trying to load webhooks - console errors

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5112]
This is on production. On every page.

`VM835:1 GET https://testtoolshed.g2.bx.psu.edu/api/webhooks/onload/all 404 (Not Found)`

xref: https://github.com/galaxyproject/galaxy/issues/4969

**Comment by dannon** [comment]
Yeah, same problem as reports.  I poked at a fix when I was working on all the client refactoring but didn't like it.  The good news is that it's pretty much harmless, but I'll take another stab at it now.
