### ISSUE TITLE
Assign (and create) roles to users based on their LDAP group

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#5129]
AD/LDAP can contain quite some information about users. One useful attribute that may be available is one describing the users membership to a 'unit' or 'group'.

If the Auth providers are allowed to return Group/Roles names to which the user will be automatically assigned, it can reduce admin manual work.

In addition, one might think to also auto create a data library based on this information - but this is even more specific and out of the scope for this issue.

**Comment by bernt-matthias** [comment]
Link to PR: https://github.com/galaxyproject/galaxy/pull/5136

**Comment by scholtalbers** [comment]
Also related #5238
