### ISSUE TITLE
"Galaxy could not be reached"

### ISSUE THREAD

**Issue by rmarroqu** [galaxyproject/galaxy#5132]
Hello,

This is likely a combination of errors. I am trying to import data from a shared history to the history on my account. The site timed out on me, and I'm not sure if this has to do with the size of the data file or with login problems. I was already logged in with the shared history file, however, when I attempted to login from a different window, it would not allow me to do so. Concerned that I had the wrong password, I tried to reset it. I never received the reset password email. It appears that I am still logged in when I click the shared history--but Galaxy will not import the data. Not quite sure what the problem is. Here is the URL in the address bar: https://usegalaxy.org/histories/list. All help is appreciated!

Thanks.

**Comment by martenson** [comment]
This was most probably a temporary server downtime. Closing.
