### ISSUE TITLE
Subworkflow output collection cannot be connected to tool/subworkflow collection input

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#5158]
xref. https://github.com/galaxyproject/galaxy/issues/1889 and https://github.com/galaxyproject/galaxy/issues/4338

Reported by @anilthanki.

**Comment by jmchilton** [comment]
I'll take a look at this before 18.01 is finalized since I've been bragging about fixing all the bugs on Twitter 😆.

**Comment by jmchilton** [comment]
Despite the spate of workflow editor and subworkflow fixes I can confirm this is still a problem with the latest dev. 

Mapping collections over flat subworkflows and connecting them to other subworkflows - causes both to be properly mapped - at least in simple cases.

<img width="986" alt="screen shot 2017-12-08 at 2 11 44 pm" src="https://user-images.githubusercontent.com/216771/33782368-79908714-dc26-11e7-9d25-3a5497514308.png">

Collection input modules can connect to subworkflows with collection inputs, and non-collection outputs cannot connect to collection inputs in subsequent steps.

<img width="871" alt="screen shot 2017-12-08 at 2 34 25 pm" src="https://user-images.githubusercontent.com/216771/33782399-955962cc-dc26-11e7-8bac-cf415e1ad398.png">

But without even any mapping involved - collection outputs cannot connect to collection inputs on tool steps (let alone collection inputs).

<img width="917" alt="screen shot 2017-12-08 at 2 41 48 pm" src="https://user-images.githubusercontent.com/216771/33782462-d8d85094-dc26-11e7-8913-41a265c89eef.png">

When collection outputs connect to flat inputs - there is no ribbon - so the workflow editor doesn't promote the next step to a mapped over step. It runs properly with the mapping as it needs to be - but the rendering in the editor is definitely wrong and consistent with subworkflow steps just not looking like collections from the editor logic's point of view.

<img width="947" alt="screen shot 2017-12-08 at 2 49 37 pm" src="https://user-images.githubusercontent.com/216771/33782545-25b574b4-dc27-11e7-8646-9c5fac9c2eb4.png">

It would/will be a lot of work to setup a very general language for describing workflow editor tests - but probably they would be very valuable - a lot of edge cases here that need to be thought about and that are difficult to manually test.

Looking at the backend - it does appear we don't check the target tool output to determine the collection type or anything so it makes sense that all outputs look like files. We also aren't grabbing extension information that might be valuable to use in the editor.

```
    def get_data_outputs(self):
        outputs = []
        if hasattr(self.subworkflow, 'workflow_outputs'):
            for workflow_output in self.subworkflow.workflow_outputs:
                if workflow_output.workflow_step.type in {'data_input', 'data_collection_input'}:
                    # It is just confusing to display the input data as output data in subworkflows
                    continue
                output_step = workflow_output.workflow_step
                label = workflow_output.label
                if not label:
                    label = "%s:%s" % (output_step.order_index, workflow_output.output_name)
                output = dict(
                    name=label,
                    label=label,
                    extensions=['input'],  # TODO
                )
                outputs.append(output)
        return outputs
```
