### ISSUE TITLE
Trackster on dev: Uncaught ReferenceError: view is not defined

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#5160]
This happens when you try to view a track:
![screen shot 2017-12-08 at 11 39 17](https://user-images.githubusercontent.com/6804901/33762460-c8b98c56-dc0c-11e7-83ec-4c30623d8204.png)

**Comment by dannon** [comment]
@mvdbeek Yeah, I was following up with these in my require_elimination branch, which is when I found out our tabix indexing was busted in the first place :)

**Comment by dannon** [comment]
This was fixed in https://github.com/galaxyproject/galaxy/pull/5261
