### ISSUE TITLE
Track and Fix Transiently Failing Selenium Tests

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5169]
It has gone okay I think - but isn't quite as stable as the other checks yet. 

- [ ] Some uploads fail - I think because things happen so fast ``file_type`` isn't somehow set in the GUI to the correct default.
  
   Good Upload

    "message": "http://localhost:9119/static/scripts/bundled/analysis.bundled.js?v=1512747564 0:14360 \"uploadbox::uploadpost() Posting following data. {\\\"data\\\":{\\\"payload\\\":{\\\"tool_id\\\":\\\"upload1\\\",\\\"history_id\\\":null,\\\"inputs\\\":\\\"{\\\\\\\"file_count\\\\\\\":1,\\\\\\\"dbkey\\\\\\\":\\\\\\\"?\\\\\\\",\\\\\\\"file_type\\\\\\\":\\\\\\\"auto\\\\\\\",\\\\\\\"files_0|type\\\\\\\":\\\\\\\"upload_dataset\\\\\\\",\\\\\\\"files_0|space_to_tab\\\\\\\":null,\\\\\\\"files_0|to_posix_lines\\\\\\\":\\\\\\\"Yes\\\\\\\",\\\\\\\"files_0|dbkey\\\\\\\":\\\\\\\"?\\\\\\\",\\\\\\\"files_0|file_type\\\\\\\":\\\\\\\"auto\\\\\\\"}\\\"},\\\"files\\\":[{\\\"name\\\":\\\"files_0|file_data\\\",\\\"file\\\":{}}],\\\"error_message\\\":null},\\\"url\\\":\\\"/api/tools\\\",\\\"maxfilesize\\\":2048,\\\"error_filesize\\\":\\\"File exceeds 2GB. Please use a FTP client.\\\",\\\"error_default\\\":\\\"Please make sure the file is available.\\\",\\\"error_server\\\":\\\"Upload request failed.\\\",\\\"error_login\\\":\\\"Uploads require you to log in.\\\"}\"", 

   Bad Upload

    "message": "http://localhost:9119/static/scripts/bundled/analysis.bundled.js?v=1512747564 0:14360 \"uploadbox::uploadpost() Posting following data. {\\\"data\\\":{\\\"payload\\\":{\\\"tool_id\\\":\\\"upload1\\\",\\\"history_id\\\":null,\\\"inputs\\\":\\\"{\\\\\\\"file_count\\\\\\\":1,\\\\\\\"dbkey\\\\\\\":\\\\\\\"?\\\\\\\",\\\\\\\"file_type\\\\\\\":\\\\\\\"\\\\\\\",\\\\\\\"files_0|type\\\\\\\":\\\\\\\"upload_dataset\\\\\\\",\\\\\\\"files_0|space_to_tab\\\\\\\":null,\\\\\\\"files_0|to_posix_lines\\\\\\\":\\\\\\\"Yes\\\\\\\",\\\\\\\"files_0|dbkey\\\\\\\":\\\\\\\"?\\\\\\\",\\\\\\\"files_0|file_type\\\\\\\":\\\\\\\"\\\\\\\"}\\\"},\\\"files\\\":[{\\\"name\\\":\\\"files_0|file_data\\\",\\\"file\\\":{}}],\\\"error_message\\\":null},\\\"url\\\":\\\"/api/tools\\\",\\\"maxfilesize\\\":2048,\\\"error_filesize\\\":\\\"File exceeds 2GB. Please use a FTP client.\\\",\\\"error_default\\\":\\\"Please make sure the file is available.\\\",\\\"error_server\\\":\\\"Upload request failed.\\\",\\\"error_login\\\":\\\"Uploads require you to log in.\\\"}\"",
  
  https://jenkins.galaxyproject.org/job/docker-selenium/563/artifact/563-test-errors/test_run_data2017120816221512750132/
- [ ] https://jenkins.galaxyproject.org/job/docker-selenium/630/testReport/junit/selenium_tests.test_tool_form/ToolFormTestCase/test_bibtex_rendering/
- [ ] https://jenkins.galaxyproject.org/job/docker-selenium/1684/console This job finished in a failed state but hung until killed by Jenkins, there are no timestamps but it seemed to hang for at least 10 minutes while I was watching it. That shouldn't happen.

**Comment by martenson** [comment]
I think we are in a pretty good shape atm. Closing.
