### ISSUE TITLE
Improve quota display by distinguishing active and deleted but not purged space

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#518]
More often than not users delete datasets or histories without purging resulting in unexpected quota being used.
In the case of full histories it's somewhat hidden how you can list which deleted but not purged entries you may have.

In addition, the set_user_disk_usage.py script only displays:

```
user <email> old usage: 1.5GB change: none
```

So it's also not easy for an administrator to see where the quota is being used.

I therefore suggest 2 enhancements, one on the set_user_disk_usage.py script that instead shows:

```
user <email> old usage: 1.5GB (active: 500MB, deleted: 1GB) change: none
```

Additionally the galaxy user interface could display a tooltip (clicking or hovering the quota widget) which would inform the user that a given % of their quota is being taken by unpurged datasets or histories.

from @Unode on [trello](https://trello.com/c/aILtCpdi/2212-improve-quota-display-by-distinguishing-active-and-deleted-but-not-purged-space)

**Comment by martenson** [comment]
I like this idea a lot.

**Comment by dannon** [comment]
xref #13113

**Comment by hexylena** [comment]
Updated the dashboard to `fixes` this issue, since, yeah, I don't want to care as an admin, I'd rather my users manage it themselves. Super exciting this is finally happening
