### ISSUE TITLE
mis-indexing sub-workflow output names

### ISSUE THREAD

**Issue by mmiladi** [galaxyproject/galaxy#5183]
There is an inconsistency in sub-workflow naming on index number prefixes. In the below sub-workflow with 7 tools and 6 inputs:
![screenshot from 2017-12-10 17-55-03](https://user-images.githubusercontent.com/6370737/33807273-685ac342-ddd4-11e7-8c7c-d5ff566965c1.png)

Included to the super-workflow (the left box):
![screenshot from 2017-12-10 17-51-21](https://user-images.githubusercontent.com/6370737/33807284-8638e2ea-ddd4-11e7-8412-762a978eb25f.png)

In  runtime, the scheduler complains of not being able to find output type. Expecting ` 12:final_soft` but available list has name `6:final_soft'` :
```
handler0-stderr---supervisor-1MPSEY.log:galaxy.workflow.run ERROR 2017-12-10 16:51:49,012 Failed to schedule Workflow[id=95,name=MultiRoundClustering], problem occurred on WorkflowStep[index=7,type=subworkflow].

handler0-stderr---supervisor-1MPSEY.log-Exception: Workflow evaluation problem - failed to 
find output_name 12:final_soft in step_outputs {u'6:combined_cm_out': 
<galaxy.model.HistoryDatasetAssociation object at 0x7f46a2819090>, u'6:clusters': 
<galaxy.model.HistoryDatasetCollectionAssociation object at 0x7f46a03a2f90>, 
u'6:final_soft': <galaxy.model.HistoryDatasetAssociation object at 0x7f46a2353ed0>, 
u'6:output': <galaxy.model.HistoryDatasetAssociation object at 0x7f467366cfd0>, 
u'6:black_list': <galaxy.model.HistoryDatasetAssociation object at 0x7f46a0134610>, 
u'6:RESULTS_zip': <galaxy.model.HistoryDatasetAssociation object at 0x7f46a23534d0>,
 u'6:final_used_cmsearch': <galaxy.model.HistoryDatasetAssociation object at 0x7f46a01c7cd0>, 
u'6:fast_cluster': <galaxy.model.HistoryDatasetAssociation object at 0x7f46a010b990>}

```

It seems somewhere the output listing name index is fixed and overridden to 6, the index of the first output.

**Comment by jmchilton** [comment]
I never really intended subworkflows to be used this way - I was hoping people would define labels on their outputs in the subworkflow. These can be set in the side bar in the subworkflow by clicking on the output name.

<img width="309" alt="screen shot 2017-12-10 at 1 12 21 pm" src="https://user-images.githubusercontent.com/216771/33807909-d3dbb618-ddab-11e7-871e-14e092a234aa.png">

We have no test coverage of these dynamic ``index:output_name`` style implicit output names. I can work on building up test coverage for those but in the meantime do you want to try this with explicitly labelled outputs?

**Comment by mmiladi** [comment]
@jmchilton Right. Sorry I remembered now that we have done same thing to label them with previous sub-workflows. So it works fine for us to do the manual labeling.

However it would  be kind of problematic yet, in the sense that a non-expert user would never find out what causes immature termination.
Do you think it would be feasible to have one of these enhancements? either a) automatically label them with a unique/random prefix number, or b) warn users when sub-workflow with no-label is instantiated or c) report the exception in the history panel

**Comment by jmchilton** [comment]
@mmiladi I think the automatically assigned labels just need to work - based on your report there is a bug in there that just needs to be fixed. I was just mentioning to you that assigning labels is a way to get around that for now - since in general it is better supported. Longer term, we definitely want these automatically generated labels working.

**Comment by mmiladi** [comment]
@jmchilton Alright I see :+1:

**Comment by mvdbeek** [comment]
I think i've fixed those a while bakc, please re-open if this is still an issue.
