### ISSUE TITLE
Need API call to delete data library folders

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#519]
My tool automatically manages certain folders of a library to reflect data contents elsewhere on server (available versions of data).  I'd like to see the API extended with a library_delete_folder() call; (it currently has library_delete_dataset() call, which works fine!).  Nice if bioblend picks this up too!

from @ddooley on [trello](https://trello.com/c/kaIuqoIr/2263-need-api-call-to-delete-data-library-folders)

(Judging by my reading of [library api](https://github.com/galaxyproject/galaxy/blob/90ddc23714766c9605b09ca8eb9ff88e6f17091c/lib/galaxy/webapps/galaxy/buildapp.py#L388) and [folder api](https://github.com/galaxyproject/galaxy/blob/90ddc23714766c9605b09ca8eb9ff88e6f17091c/lib/galaxy/webapps/galaxy/buildapp.py#L467) this looks to still be a bug)

**Comment by Public-Health-Bioinformatics** [comment]
ok.  And it is still desired!  Thx.

**Comment by martenson** [comment]
In your mind would the folder_delete call delete all its contents recursively?

**Comment by hexylena** [comment]
versus having to manually figure out the tree and going bottom up, deleting folders one at a time? Yes, absolutely. (Alternatively a `recursive=True` flag of some sort...)

**Comment by Public-Health-Bioinformatics** [comment]
> "versus having to manually figure out the tree and going bottom up, deleting folders one at a time? Yes, absolutely. (Alternatively a recursive=True flag of some sort...)"

Both ideas sound good to me.

**Comment by martenson** [comment]
Soooo it seems this is already possible since 15.03
https://github.com/galaxyproject/galaxy/commit/c14342b2
The new UI also implements this.

**Comment by nsoranzo** [comment]
Also available in BioBlend since December 2014.

**Comment by martenson** [comment]
ping @Public-Health-Bioinformatics in case you do not follow all notifications

**Comment by Public-Health-Bioinformatics** [comment]
Assuming we're talking about the recursive deletion of a library folder here.  Ok, thanks.  I won't be able to check it out soon, but eventually a recoding will be in order.

Regards,

Damion
