### ISSUE TITLE
Can't upload file to Galaxy Hutlab for LEfSe

### ISSUE THREAD

**Issue by wzamaral** [galaxyproject/galaxy#5203]
I'm getting the error while trying to upload a text file from my computer to Galaxy Hutlab for LEfSe:
Failed: Gateway Time-out (504)

The file is formatted per instructions and "LEfSe" is selected for the file type.

Thanks in advance,
Wellington.

**Comment by wzamaral** [comment]
Screenshot:

![screen shot 2017-12-11 at 4 36 32 pm](https://user-images.githubusercontent.com/34492476/33911661-aa6fad4e-df58-11e7-918c-074a83ae5de5.png)

**Comment by nsoranzo** [comment]
For Hutlab Galaxy support you need to contact http://huttenhower.sph.harvard.edu/contact
