### ISSUE TITLE
workflow editor js Uncaught ANY_COLLECTION_TYPE_DESCRIPTION

### ISSUE THREAD

**Issue by mmiladi** [galaxyproject/galaxy#5205]
Adding a 'filter failed' step to a workflow then saved it. Now the workflow editor is halted:  Browser console reports: `Uncaught Cannot append to ANY_COLLECTION_TYPE_DESCRIPTION`
Galaxy version is 17.09

![screenshot from 2017-12-13 13-48-13](https://user-images.githubusercontent.com/6370737/33939709-75f96ca8-e00c-11e7-9a00-fa8282299d8b.png)

**Comment by dannon** [comment]
@mmiladi I'll take a look, thanks!  (I fixed this being undefined in 30bada4c4a9, but it looks like the behavior still wasn't quite right)

**Comment by mmiladi** [comment]
@dannon This happened in our Freiburg Galaxy server. Probably it's not been updated within these days. @erasche what would you think?

**Comment by dannon** [comment]
@mmiladi Can you show me the other steps?  Is it just an input dataset and a filter failed step?  I'm not seeing the error on 17.09 either.  (I don't think the change I made mentioned above would necessarily fix the problem you're having)

**Comment by hexylena** [comment]
@mmiladi we're on the latest 17.09, I'm not seeing any commits that we are currently missing.

**Comment by dannon** [comment]
@mmiladi Is that input dataset actually attached to the filter?  I am only able to attach it to an input dataset collection.  

![image](https://user-images.githubusercontent.com/155398/33957041-80e3f67c-e00e-11e7-9dd8-7ec293f17740.png)

**Comment by mmiladi** [comment]
@dannon I was waiting for the latest docker build of `dev` to test. Here is the scenario:

![screenshot from 2017-12-14 13-57-48](https://user-images.githubusercontent.com/6370737/33993514-1c3ab296-e0d7-11e7-8c1e-4bba2b59e086.png)

If it helps, I can send you the workflow file via Gitter.

**Comment by mmiladi** [comment]
@erasche thanks for the info. The problem is persistent with 17.09 and also dev branch.

**Comment by mmiladi** [comment]
@dannon  An update on tracking the issue: I could reproduce the error without having the wf-editor halted. Same exception arises while trying to build the wf from scratch on cmsearch output. Exception is thrown by trying to connect and drag the cmsearch output : 

![screenshot from 2017-12-17 18-50-26](https://user-images.githubusercontent.com/6370737/34082305-b1965b52-e35b-11e7-8752-992f3e81cd5f.png)

Please note that the data collection input for cmsearch is dynamic, hidden by default and pops-up by selecting "Covariance model from your history"

**Comment by mmiladi** [comment]
@dannon Have you had  time to check the workflow?

**Comment by dannon** [comment]
@mmiladi Yep, sure have, and I have reproduced it locally.  Working on a fix.

**Comment by mmiladi** [comment]
Many thanks @dannon !

**Comment by dannon** [comment]
I reproduced this locally and then handed off to @guerler.  Did you make any progress on the right fix for this one Sam?

**Comment by mvdbeek** [comment]
@mmiladi Is this still an issue ? I tried a couple of things that seemed to have worked
<img width="800" alt="screen shot 2018-05-01 at 17 35 12" src="https://user-images.githubusercontent.com/6804901/39479620-0dcd4236-4d66-11e8-8fee-fd93902f6cd5.png">

**Comment by guerler** [comment]
I have not looked into this in detail yet but can do so if the issue still exists.

**Comment by mmiladi** [comment]
@mvdbeek I checked now. It's still an issue, on usegalaxy.eu at least. This occurs most probably due to the dynamic input port. Do you agree @dannon ?

>Please note that the data collection input for cmsearch is dynamic, hidden by default and pops-up by selecting "Covariance model from your history"

**Comment by dannon** [comment]
@mmiladi @guerler Yes, it's still an issue (18.05), and yes it seems related to the dynamic toggling of the I/O types related to collections.  My guess was the toggling doesn't reinitialize the connectors correctly or something along those lines.

**Comment by guerler** [comment]
I have trouble reproducing this. This seems to work for me.

![untitled](https://user-images.githubusercontent.com/2105447/39497750-b16e5b4e-4d72-11e8-979a-d975ace67091.png)

**Comment by mmiladi** [comment]
Thanks much for looking into it @guerler . Could you please try to see if it works to connect the cmsearch outfile to another tool?

![screenshot from 2018-05-02 11-54-24](https://user-images.githubusercontent.com/6370737/39517351-ea3e9d3e-4dff-11e8-8c54-05eede156438.png)

**Comment by guerler** [comment]
Thanks @mmiladi for reporting this issue. It can be reproduced by using built-in collection tools. Clicking the output terminal of the ZIP collection tool triggers the exception.

![example](https://user-images.githubusercontent.com/2105447/39797563-9959cdd2-532a-11e8-86f3-823ae7d086a1.png)

The problem is that the filter failed, filter list and relabeling tools for collections do not specify a fixed collection output type i.e. they rely on the input type source. Adding subsequent steps in the workflow editor leaves the collection types undetermined. A possible fix is to allow appending to the generic type descriptor as in https://github.com/galaxyproject/galaxy/compare/dev...guerler:terminals. An alternative might be to validate `otherMapOver.canMapOver(otherCollectionType)` before appending https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/workflow/workflow-terminals.js#L359. ping @jmchilton.

**Comment by mvdbeek** [comment]
This is related to https://github.com/galaxyproject/galaxy/issues/6514, I'm working on propagating the correct collection_type on the backend and front-end
