### ISSUE TITLE
API endpoint for config settings

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#5207]
I think it may be helpful to have an API endpoint (and maybe a simple form) that just dumps everything in app.config. Given that we have a few different ways to define config settings I think it would be helpful to display what galaxy is really using.

**Comment by nsoranzo** [comment]
Isn't what `/api/configuration` from `lib/galaxy/webapps/galaxy/api/configuration.py` supposed to do?

**Comment by mvdbeek** [comment]
why yes ... how did I not know about this?

**Comment by hexylena** [comment]
public-galaxy-servers consumes it, it's super helpful. If you implement new features and want to track adoption, consider adding the flag to the configuration api.

See bottom half of:
https://grafana.denbi.uni-freiburg.de/dashboard/db/public-galaxy-servers
