### ISSUE TITLE
errors in upload are not shown as erroneous dataset

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5214]
Errors happening during download don't mark the created data set as error.

![screenshot from 2017-12-14 13-19-40](https://user-images.githubusercontent.com/25689525/33992121-b7ae7830-e0d1-11e7-82ed-3558baf7adad.png)

**Comment by mvdbeek** [comment]
That's because the upload tool sets error using the stderr, but upload.py redirects stderr into galaxy.json, which is read after determining whether a job should fail based on its profile. I'm working on a fix.

**Comment by bernt-matthias** [comment]
Wonderful. Thanks

**Comment by mvdbeek** [comment]
Thanks for reporting. That's a bug we really should have noticed.
