### ISSUE TITLE
On resume dependend jobs: The previously selected dataset has entered an unusable state

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#5222]
After a workflow job failed I rerun it with 'resume dependend jobs'. 
- The restarted job, trimmomatic, generates a **hidden** `fastqsanger.gz` (i.e. not a bam with a missing .bai ;) )
- The next job, STAR, errors with "The previously selected dataset has entered an unusable state."
  - the inputs for STAR are:
     - the hidden fastqsanger.gz
     - reference and gtf file from a different history from where the workflow was started

After unhiding the fastq generated by trimmomatic I can manually rerun the STAR job successfully.

Related logs:
```
galaxy.jobs.handler DEBUG 2017-12-15 09:04:34,777 (3332) Dispatching to slurm runner
galaxy.jobs DEBUG 2017-12-15 09:04:34,808 (3332) Persisting job destination (destination id: cluster16c40)
galaxy.jobs.runners DEBUG 2017-12-15 09:04:34,815 Job [3332] queued (37.893 ms)
galaxy.jobs.handler INFO 2017-12-15 09:04:34,822 (3332) Job dispatched
galaxy.jobs.runners ERROR 2017-12-15 09:04:34,874 (3332) Failure preparing job
Traceback (most recent call last):
  File "/galaxy/lib/galaxy/jobs/runners/__init__.py", line 170, in prepare_job
    job_wrapper.prepare()
  File "/galaxy/lib/galaxy/jobs/__init__.py", line 878, in prepare
    tool_evaluator.set_compute_environment(compute_environment, get_special=get_special)
  File "/galaxy/lib/galaxy/tools/evaluation.py", line 73, in set_compute_environment
    visit_input_values(self.tool.inputs, incoming, validate_inputs)
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 106, in visit_input_values
    visit_input_values(input.cases[values['__current_case__']].inputs, values, callback, new_name_prefix, label_prefix, parent_prefix=name_prefix, **payload)
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 112, in visit_input_values
    callback_helper(input, input_values, name_prefix, label_prefix, parent_prefix=parent_prefix, context=context)
  File "/galaxy/lib/galaxy/tools/parameters/__init__.py", line 77, in callback_helper
    new_value = callback(**args)
  File "/galaxy/lib/galaxy/tools/evaluation.py", line 71, in validate_inputs
    value = input.from_json(value, request_context, context)
  File "/galaxy/lib/galaxy/tools/parameters/basic.py", line 1676, in from_json
    raise ValueError("The previously selected dataset has entered an unusable state")
ValueError: The previously selected dataset has entered an unusable state
```

**Comment by mvdbeek** [comment]
Yeah, there are surely some improvements necessary for the resume functionality.

**Comment by scholtalbers** [comment]
This workflow demonstrates this issue: https://usegalaxy.org/u/_jelle/w/test-resume-unusable
![screen shot 2017-12-22 at 14 39 07](https://user-images.githubusercontent.com/102411/34299936-fd8a630a-e725-11e7-8690-adb615bede5b.png)

Just take any fastq as input. The 'grep' tool will be put in an error state due to the incorrect `-100` value. Rerun with `0` and try to resume the jobs. Bowtie2 will then end in `The previously selected dataset has entered an unusable state`

**Comment by mvdbeek** [comment]
Thanks for the concise example, that should help!
