### ISSUE TITLE
Workflow tool upgrade path is messy

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#523]
From an IRC conversation:

> jelle_ | how does Galaxy handle tool updates that would normally break workflows? They just break and one has to figure out how to reconnect newer tools? I guess you could at least get a workaround where you delete older workflows that people imported - and even import the newer one in their workflow overview but my problem is more that I do not know which tools people depend on, that's why I keep them installed but hidden. Because as soon as I delete it, they might have broken workflows and for some workflows it is hard to figure out what the appropriate parameters were

Partially I believe this would be solved by read-only workflows that users can run without importing.

from @erasche and @scholtalbers on [trello](https://trello.com/c/aPAxnNl4/2423-workflow-tool-upgrade-path-is-messy)

**Comment by guerler** [comment]
Fixed with #4373.
