### ISSUE TITLE
documentation strategy 

### ISSUE THREAD

**Issue by baberlevi** [galaxyproject/galaxy#5236]
I've been working on setting up a local galaxy instance to be used for class instruction, and I am having some pretty major struggles finding any coherent administrative documentation.

- I see the old wiki here: https://moin.galaxyproject.org/
- The new galaxy-hub documentation here: https://galaxyproject.org/admin/
- And a readthedocs site here: https://docs.galaxyproject.org/en/master/

I'm also aware of the biostars Q&A board: 
https://biostar.usegalaxy.org/

From what I can tell, none of the 3 documentation sources are complete, and they frequently point to an older version - though often with broken links.  The biostar site has a lot of answers that reference documentation, but those links are also often broken.

I've made a few small updates to the galaxy-hub documentation so far to correct things I've found:
https://github.com/galaxyproject/galaxy-hub/pull/351

I have some other changes I could submit, but I want to be sure I understand the documentation strategy first. 

- Is Galaxy-Hub supposed to be the canonical source of documentation ?
- Is the readthedocs site still active, or has it been abandoned (I can't find the git repo for it)?
- Is there a strategy to ensure broken links are handled with redirects or updated ?
- If biostars is going to permit links in answers, those links should persist. Alternatively, maybe a strategy like stackoverflow uses should be adopted where answers are required to contain the full answer in order to avoid this problem.

**Comment by nsoranzo** [comment]
> I see the old wiki here: https://moin.galaxyproject.org/

That's definitely deprecated and kept around only for pages that haven't been ported to the Hub.

> Is Galaxy-Hub supposed to be the canonical source of documentation ?

Mostly yes, apart from release notes, API docs, and some admin documentation that changes among releases and is therefore available at https://docs.galaxyproject.org/en/release_17.09/ and similar URLs.

@jmchilton @martenson Maybe we should somehow present links for the release-specific docs on https://docs.galaxyproject.org/ instead of redirecting to /en/master .

> Is the readthedocs site still active, or has it been abandoned (I can't find the git repo for it)?

This has been abandoned in favour of https://docs.galaxyproject.org/ because of limitations introduced by rtd for the documentation build process. The git repo for this documentation is this one.

**Comment by martenson** [comment]
>Maybe we should somehow present links for the release-specific docs on https://docs.galaxyproject.org/ instead of redirecting to /en/master

We should and we will. The per-branch documentation builds are fairly new and this is definitely something we want to incorporate better.

I am sorry about the broken links @baberlevi -  we are trying to fix them when we see them and your contributions are more than welcome here (thanks a lot for https://github.com/galaxyproject/galaxy-hub/pull/351 !)

@baberlevi as @nsoranzo pointed out the readthedocs site has been abandoned and we are hosting our own docs (but with the readthedocs style) at docs.galaxyproject.org

If something is unclear or subpar in the docs please feel free to ping us at https://gitter.im/galaxyproject/Lobby and we should be able to clarify quickly and in turn improve the docs
