### ISSUE TITLE
"Join two Datasets" (join1) does not preserve column headers

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#524]
I am referring to the tool https://github.com/galaxyproject/galaxy/blob/dev/tools/filters/joiner.xml implemented as the Python script https://github.com/galaxyproject/galaxy/blob/dev/tools/filters/join.py currently still part of the main Galaxy distribution.

Based on the example in the help text, consider the following as _tabular_ files with a simple header:

```
#chr    start   end gene
chr1    10  20  geneA
chr1    50  80  geneB
chr5    10  40  geneL
```

and:

```
#gene   description
geneA   tumor-supressor
geneB   Foxp2
geneC   Gnas1
geneE   INK4a
```

Current output with default options,
- Keep lines of first input that do not join with second input: No
- Keep lines of first input that are incomplete: No
- Fill empty columns: No

```
chr1    10  20  geneA   geneA   tumor-supressor
chr1    50  80  geneB   geneB   Foxp2
```

My desired output would preserve the column headers:

```
#chr    start   end     gene    gene    description
chr1    10  20  geneA   geneA   tumor-supressor
chr1    50  80  geneB   geneB   Foxp2
```

Likewise changing the options to:
- Keep lines of first input that do not join with second input: Yes
- Keep lines of first input that are incomplete: Yes
- Fill empty columns: Yes
- Only fill unjoined rows: Yes
- Fill Columns by: Single fill value
- Fill value: .

gives:

```
#chr    start   end gene    .   .
chr1    10  20  geneA   geneA   tumor-supressor
chr1    50  80  geneB   geneB   Foxp2
chr5    10  40  geneL   .   .
```

Here I would like the column headers from the second file to be included:

```
#chr    start   end gene    gene    description
chr1    10  20  geneA   geneA   tumor-supressor
chr1    50  80  geneB   geneB   Foxp2
chr5    10  40  geneL   .   .
```

Note separately that if the first dataset is considered as a bed file, then the output file is also considered bed, and this appears to wrongly mark column c6 (description) as strand.

from @peterjc on [trello](https://trello.com/c/Hidhf6b4/2411-join-two-datasets-join1-does-not-preserve-column-headers)

**Comment by peterjc** [comment]
Should the bed column 6 problem (at the end of the original report) be logged as a separate GitHub issue?

**Comment by hexylena** [comment]
That would be a logical separation, but arguably if someone is bothering to fix the bulk of this issue, they'll probably find the few minutes for fixing the data format bug. I'll bear the format bit in mind with https://github.com/galaxyproject/galaxy/pull/361

**Comment by zuckerruebe** [comment]
I will give it a go and have a look at it...

**Comment by zuckerruebe** [comment]
I think the examples given above would make for good unit tests. Is there some infrastructure already in place in the project for this?

**Comment by bgruening** [comment]
@zuckerruebe sure! 
http://planemo.readthedocs.org/en/latest/

`pip install planemo --user`
planemo lint && planemo test are your friends.
Thanks @zuckerruebe!

**Comment by zuckerruebe** [comment]
Thanks @bgruening, that was quick. :)

I ran planemo on the current joiner.xml. All tests passed - as indicated as well in the nice html report. However, on the console I got the following output:

```
Ran 4 tests in 418.941s

OK
functional_tests.py INFO 2015-10-31 19:52:48,187 Shutting down
functional_tests.py INFO 2015-10-31 19:52:48,188 Shutting down embedded web server
functional_tests.py INFO 2015-10-31 19:52:48,196 Embedded web server stopped
functional_tests.py INFO 2015-10-31 19:52:48,197 Shutting down app
galaxy.jobs.handler INFO 2015-10-31 19:52:48,197 sending stop signal to worker thread
galaxy.jobs.handler INFO 2015-10-31 19:52:48,197 job handler queue stopped
galaxy.jobs.runners INFO 2015-10-31 19:52:48,199 TaskRunner: Sending stop signal to 2 worker threads
galaxy.jobs.runners INFO 2015-10-31 19:52:48,208 LocalRunner: Sending stop signal to 5 worker threads
galaxy.jobs.handler INFO 2015-10-31 19:52:48,220 sending stop signal to worker thread
galaxy.jobs.handler INFO 2015-10-31 19:52:48,223 job handler stop queue stopped
functional_tests.py INFO 2015-10-31 19:52:48,224 Embedded Universe application stopped
functional_tests.py INFO 2015-10-31 19:52:48,227 Cleaning up temporary files in /tmp/tmpk4bkAg/tmpmFctoI
galaxy.jobs.handler INFO 2015-10-31 19:52:48,913 sending stop signal to worker thread
galaxy.jobs.handler INFO 2015-10-31 19:52:48,917 job handler queue stopped
galaxy.jobs.runners INFO 2015-10-31 19:52:48,918 TaskRunner: Sending stop signal to 2 worker threads
galaxy.jobs.runners INFO 2015-10-31 19:52:48,919 LocalRunner: Sending stop signal to 5 worker threads
galaxy.jobs.handler INFO 2015-10-31 19:52:48,920 sending stop signal to worker thread
galaxy.jobs.handler INFO 2015-10-31 19:52:48,921 job handler stop queue stopped
All 4 test(s) executed passed.
join1[0]: failed
join1[1]: failed
join1[2]: failed
join1[3]: failed
```

Just thought I'd mention it. :)

**Comment by bgruening** [comment]
Can you post this as issue here https://github.com/galaxyproject/planemo/issues

Thanks!

**Comment by zuckerruebe** [comment]
OK, done: https://github.com/galaxyproject/planemo/issues/363.

**Comment by bgruening** [comment]
Awesome, thanks! But this shouldn't stop you :)
Maybe this tool can help you: https://github.com/bgruening/galaxytools/blob/master/tools/text_processing/text_processing/cut.xml

**Comment by zuckerruebe** [comment]
Can I just put

```
#chr    start   end gene
chr1    10  20  geneA
chr1    50  80  geneB
chr5    10  40  geneL
```

and 

```
#gene   description
geneA   tumor-supressor
geneB   Foxp2
geneC   Gnas1
geneE   INK4a
```

and the desired outputs into seperate *.tab files in the test-data directory? Any particular naming convention you want me to follow?

**Comment by bgruening** [comment]
Follow the naming convention that is already used or something like `input1.bed` and `join_result1.tabular`.

**Comment by lecorguille** [comment]
I'm interesting in this issue and plan to work on it today during the GCC Hack The Galaxy session

**Comment by lecorguille** [comment]
https://github.com/galaxyproject/galaxy/pull/4229
