### ISSUE TITLE
Collection Builder and setting_metadata

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5241]
There is a history on main which was build using the upload collections functionality (I think - I'll verify) and has a couple datasets in the "setting_metadata" state. Maybe the original datasets changed state and these were not updated - or maybe they aren't supposed to update and we shouldn't have built the collection until everything was 'ok'. Need to investigate further.

**Comment by mvdbeek** [comment]
By now I guess we've change a lot and it'll be difficult to dig into what happened, so I'm closing this one.
