### ISSUE TITLE
workflow run form initialization is very resource-demanding and causes browser crashes

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5265]
originally reported by @blankenberg 

![screenshot 2018-01-04 13 04 14](https://user-images.githubusercontent.com/1814954/34579862-bd33554a-f158-11e7-8b0b-0fbceae43153.png)

>it looks to be happening in the `_configure` function on the tool-form-composite
while running through each step of the WF it creates a very high stack of `fn.extend`
and takes 50s before it actually calls `render`
together with the 18s of getting data from API it makes ~80s loading time on ‘run form’ of a workflow
also it creates a very big heap, that is probably the reason why every subsequent operation on that tab has huge problems and/or crashes
I failed to measure just how big yet, because it crashes the developer tools while gathering it
the closest culprit for the stack is `visitInputs` in form-data https://github.com/galaxyproject/galaxy/blob/release_17.09/client/galaxy/scripts/mvc/form/form-data.js#L197
`context = $.extend( true, {}, context );` maybe?
I think this line is what is causing the stack height
because visitInputs is recursive the context really bloats

edit: I analyzed the profile on the following workflow: https://usegalaxy.org/u/martenson/w/imported-browser-go-boom-mothur-miseq-sop-mod (which is a slightly modified version of https://github.com/galaxyproject/training-material/tree/master/topics/metagenomics/tutorials/mothur-miseq-sop/workflows/)
 
edit2: cpu profile from chrome devtools: https://files.gitter.im/galaxyproject/Lobby/y4lM/CPU-20180104T125048.cpuprofile

**Comment by mvdbeek** [comment]
@martenson can you share the workflow ?

**Comment by blankenberg** [comment]
Example history for input: https://usegalaxy.org/u/dan/h/mothur-sop-test

Although, it looks like browser go boom with an empty history too.

**Comment by martenson** [comment]
I also suspect that there is a memory leak/loop since the memory consumed by the 'run workflow form' tab seems to be increasing over time without a limit (I am at 6GB now after starting with 2GB an hour ago, the form is either frozen or very laggy)

**Comment by martenson** [comment]
The problematic visitInputs calls are invoked from this spot in the form-composite: https://github.com/galaxyproject/galaxy/blob/release_17.09/client/galaxy/scripts/mvc/tool/tool-form-composite.js#L150

**Comment by dannon** [comment]
Fixed in #5271

**Comment by blankenberg** [comment]
Was workflow execution actually tested?

The workflow run page loads now, and I can click execute (send results to new history), but after 1 hour, the newly created history remains empty. 

It looks like starting the workflow was successful and there are no error messages presented to the user.

After manually digging with the API, the workflow invocation failed, moving discussion over to https://github.com/galaxyproject/galaxy/issues/5142.
