### ISSUE TITLE
Interactive environments running on Kubernetes (k8s)

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#5275]
Within PhenoMeNal we want to take advantage of the excellent work done by the community here on interactive environments. I would like to share the thought process I have so far after looking at the source code and understanding what would be needed allow the containers to be scheduled to k8s instead of docker directly.

It would be desirable to depend only on the pykube library already used by Galaxy when dispatching jobs to k8s, to avoid the additional dependency on the `kubectl` binary. On the other hand, treating the launch process as a shell operation as I think it is currently done (code seems to be build a docker run call essentially) might make it simpler to adapt the code for this extra case. A reasonable compromise might be a python code that we call through the shell that uses the same virtualenv as galaxy.

In terms of Kubernetes setup, currently we have all its settings in the runner definition on the job_conf.xml file. How complicated or desirable would be to obtain these settings from there? or should we move the k8s connection settings to a higher level on the galaxy.ini file?

In terms of the galaxy codebase, my understanding is that the launch method https://github.com/galaxyproject/galaxy/blob/62826a116054030ba50b801f3923a24768de197c/lib/galaxy/visualization/plugins/interactive_environments.py#L458 builds the docker command taking care of volumes and other elements, through _launch_legacy and _launch_container_interface methods (question one, in which one should I focus for this case? what is the idea behind the container interface method?). Is not very clear to me from where InteractiveEnvironmentRequest's `launch` is called though (I found some usages inside pulsar, is it done through it?). I see as well a call to the class from InteractiveEnvironmentPlugin's _render.

Then, once the container is running, the inspect_container method provides data that is used to somehow inform the node.js proxy of the additionally running service internal URL and port, right?

Given the high coupling of the code with docker calls, at this point I wonder whether I should try instead an OO approach where I extend the InteractiveEnvironmentRequest class? 

Another thing that is not clear to me from the code is how do you bring down the interactive environment (by this I mean stopping those containers). Or is that left to the UI of the container (in which case in Kubernetes I would need to make container part of a non-restartable object). If this would be the case, is the point at which `launch` is called adequate to be able to decide on one flavour of the object or the other?

Would appreciate any comments or suggestions on how to take this forward!

**Comment by pcm32** [comment]
My other concern is that from rel_17.09 that we are working in PhenoMeNal as base to current dev, `interactive_environments.py` has been moved from `web/base` to `visualization/plugins/interactive_environments.py`. Beside the moved file, is there any major change I should be aware between these two for the sake of IEs?

**Comment by jmchilton** [comment]
Thanks for the issue, I'm closing in lieu of https://github.com/galaxyproject/galaxy/issues/9448 - hope that is okay! I think IEs are a development dead-end if not formally deprecated.
