### ISSUE TITLE
option "repair repository" missing

### ISSUE THREAD

**Issue by NCEichner** [galaxyproject/galaxy#5277]
Hi everyone!

Is this a bug or a feature that the option "Repair repository" is missing in the "Repository Actions" menu since december?
We miss this option hard because without this we cannot (re-)install some elder tools e.g. because some file needed as dependency has moved to another location and even conda cannot resolve this because the needed file/version is not part of the conda repositories.

If this is a feature you may need to open a new github section for broken tools which are only available as (elder) mercurial repository and need some overhauling. 
This would be an interesting idea anyway as we here run at least two mercurial tools which we had to patch after installation because they did not work correctly in the original repository. These tools seem to be no longer maintained as the current versions are dated somewhen around 2012. And because in mercurial I didn't find any existing bug reporting system (comparable with the one here on github) I never knew were to adress these fixes.

**Comment by martenson** [comment]
Removing that option was a decision we took, since we couldn't think of a situation where this would be helpful anymore.

@NCEichner Could you please point at what exact tools you are having problems with that 'repair feature' would solve?

**Comment by NCEichner** [comment]
Hi @martenson 
Sorry for the delay - I was busy with other stuff.
After resetting the galaxy server because of the conda bug (#5187) and reinstalling about half of the tools I admit that the problem with repairing installation scripts really got smaller over the time. The most commonly used tools work and e.g. 'weblogo3' meanwhile has also been repaired (condafied?) so we don't get the error about the missing .tar.gz file anymore.

At the moment for us 'seqprep' is the most prominent tool that we could repair after failed installation. In the first instance via tool shed the installation brakes down in the 'make'-command because of multible errors. Conda afterwards succeeds to compile the newer version 1.2 of seqprep downloaded from bioconda but looses the 'seqlens.py' file which is needed in the wrapper commandline. Finally the .env variable is not set. So SeqPrep wrapper is shown in grey as installed with missing dependencies.
Within our last working install process in short we removed the make-command from the script and copied the 'seqprep' exeutable compiled by conda into the correct folder. Maybe there would be another (even easier) way just to skip the 'git reset ...' command. Testing the installation script 'manually' on the commandline recently ended in a successful compliation process on our debian 'stretch' system.  

Another problem could be about the different 'homer' tools. But this is a new request from our collegues - so for now I cannot tell if I could get it repaired by changing the install scripts. 
'homer47' installation is stuck in installing 'ghostscript-9.07' package as the corresponding .tar.gz file was deleted/moved (Btw. an alternative download location for this dependency would be 'http://downloads.ghostscript.com/public/old-gs-releases/ghostscript-9.07.tar.gz'.)
For us the tool 'homer' seems to be the more interesting alternative as it for sure contains wrapper scripts. Here the install script wants to install the homer package but the source has moved to 'http://homer.ucsd.edu/homer/configureHomer.pl'. Some needed sequence data/homer packages are also not installed. Then conda installs the version 4.9 which is different from the expected version 4.1 and the additional data is still missing. 
So far we tried to install homer as global installation with the additional data and modified $PATH variable but the direct call for e.g. the 'annotatPeaks.pl' script in the wrapper does not work. The 'error running annotatePeaks' seems to be raised because of a 'file not found' error as on the commandline you have to execute a perlscript somehow like 'perl /path/to/script/a_script.pl' and not just by 'a_script.pl' - even if it's located in the $PATH. So for us it's not clear if this tool would work with an correctliy set .env variable or if the wrappers themselves are quite 'alpha stage' and unfinished/buggy.

If we find more tools I will add them here in another additional post...

(Oftopic) About the broken mercurial tools problem:
As I already mentioned last time there are also some tools only distibuted over mercurial which seem not to be maintained any more but need some correction. Examples are the tools 'tab_collapse' (error in column counting) and 'memelogo' (error in commandline [option $title] and a more telling preset value). As the fixes can be done by altering the wrapper scripts AFTER succesful installation these tools do not fit into this topic of missing repair button but any suggestion how to deal with this is appreciated. E.g. would it help to write pull requests for these tools within the devteam or iuc repositories?

**Comment by hexylena** [comment]
I guess this is now solved with more or less requiring conda packages.

> E.g. would it help to write pull requests for these tools within the devteam or iuc repositories?

yes definitely!
