### ISSUE TITLE
Display issue with hashtags on collections

### ISSUE THREAD

**Issue by arbernard** [galaxyproject/galaxy#5280]
Hi Galaxy devs,

As reported in https://github.com/galaxyproject/galaxy/issues/5100 and fixed in https://github.com/galaxyproject/galaxy/pull/5155 the new hashtag system can cause display issues in the history panel as well as in the drop-down menus on the parameter selection page of tools/workflows.

In this issue, and as discussed yesterday on Gitter with @dannon, I'm reporting another issue with these hashtags.

This time the display problem appears when you click on a collection in the history panel.

After the click, the history panel refreshes and displays the details of the collection in 3 parts: title bar, hashtag edition box and datasets.

The problem is only visible when the collection have a lot of hashtags.

In that particular case, the hashtag edition box occupy almost the entire height of the history panel and, therefore, the users can't see the datasets. They also have no way to scroll down to them because no scrollbar is available.

----

**Here is a visual example of the issue:**

![tag_box_on_collection](https://user-images.githubusercontent.com/25177525/34712769-52f86c4a-f524-11e7-894c-fa053f68c9dd.png)

Please note that this screenshot has been made on a Galaxy instance in version 17.09 master branch (and, as a consequence, don't include the modifications made in https://github.com/galaxyproject/galaxy/pull/5155).

**Comment by dannon** [comment]
@arbernard Thanks for making the issue for this!  My current idea is to, past a certain number of tags, pop this tag editor panel out of the surrounding context so we can use it anywhere, regardless of the amount of screen space available.  I'll tinker with a few options, though.
