### ISSUE TITLE
"Set it manually or retry auto-detection" confusing

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#5281]
I have some fastq files (data library uploads) that somehow tend to end up in this state. 
What is confusing, is that the current behavior of clicking the link/action `Set it manually or retry auto-detection` does not do anything but list some dataset(?) information. And it does not go to a more practical `edit attributes` page (or better yet, the action `autodetect` should be directly available).
See screenshots. This happens on a local instance, 17.09.

![screen shot 2018-01-09 at 10 45 49](https://user-images.githubusercontent.com/102411/34714619-4d76321a-f52a-11e7-880f-0c7585139246.png)

 ⬇️
![screen shot 2018-01-09 at 10 35 17](https://user-images.githubusercontent.com/102411/34714456-c6ffd07e-f529-11e7-8540-c258ace2236b.png)

**Comment by dannon** [comment]
@scholtalbers Should be fixed in #5289 to the previous behavior, which was to go to the edit page.

**Comment by dannon** [comment]
Resolved in #5289.
