### ISSUE TITLE
filter:proxy-prefix section missing from reports.yml.sample

### ISSUE THREAD

**Issue by Petraea** [galaxyproject/galaxy#5285]
It looks like the proxy-prefix config is missing from the newly migrated reports.yml.example, so proxying e.g. https://hostname/reports isn't configurable.

**Comment by abretaud** [comment]
It looks like it's the same now for [galaxy.yml.sample](https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.yml.sample) too. I think some people will find this problematic when updating to 18.01. Will the old .ini file still be supported or migration to yml will be mandatory?

**Comment by mvdbeek** [comment]
Th old ini file files will remain supported at least until 18.05, but probably quite a bit longer.

**Comment by abretaud** [comment]
Ok, good, it gives some time to find a solution

**Comment by mvdbeek** [comment]
Fixed by https://github.com/galaxyproject/galaxy/pull/7216, thanks for reporting @Petraea and sorry for the long delay.
