### ISSUE TITLE
How can I index a file with tabix?

### ISSUE THREAD

**Issue by emmannaemeka** [galaxyproject/galaxy#5292]
I used freeBayes to call variants. Running it on the program I wanted to use it for it returned this
[W::vcf_parse] Contig 'cneoH99_Chr1' is not defined in the header. (Quick workaround: index the file with tabix.)
[W::vcf_parse] Contig 'cneoH99_Chr9' is not defined in the header. (Quick workaround: index the file with taxi.)

Please can someone help me with how to index a file with tabix in galaxy?

**Comment by nsoranzo** [comment]
@emmannaemeka This is not a Galaxy bug, can you please use [Galaxy Biostar](https://biostar.usegalaxy.org/) for this kind of issues?
