### ISSUE TITLE
TypeError: to_dict() got an unexpected keyword argument 'other_values'

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#5305]
In https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/__init__.py#L1874 `other_values` is defined but in https://github.com/galaxyproject/galaxy/blame/dev/lib/galaxy/tools/parameters/grouping.py it is not defined. This causes:

```
TypeError: to_dict() got an unexpected keyword argument 'other_values'
  File "galaxy/tools/__init__.py", line 1908, in populate_model
    tool_dict = input.to_dict(request_context, other_values=other_values)
```

e4de7ee292ff496e8582588d55556617 from galaxy-freiburg

**Comment by mvdbeek** [comment]
I vaguely remember that we fixed this some time ago.
