### ISSUE TITLE
Links of the datasets (imported from any data library) in "Show structure" throw malformed folder id error

### ISSUE THREAD

**Issue by anuprulez** [galaxyproject/galaxy#5307]
Steps to reproduce the error:

1. Open any data library and export some datasets to any history.

![error1](https://user-images.githubusercontent.com/3022518/34920303-f3dc2e9e-f970-11e7-88b2-a795b0135f6e.png)

2. Make this history as "current history" and see "Show Structure".

![error2](https://user-images.githubusercontent.com/3022518/34920304-f8c437f8-f970-11e7-9fc6-e0f47988f50b.png)

3. Click on the links: "Library: <library_path>" (datasets which were imported from data library).

![error3](https://user-images.githubusercontent.com/3022518/34920305-fcdd496a-f970-11e7-9961-470f0c3041df.png)

4. Malformed folder id error.

There is an extra "F" character getting added (prefix to a folder id) to the data library url. I am working on migrating makos related to "show structure" which would fix this issue.

**Comment by martenson** [comment]
>There is an extra "F" character getting added (prefix to a folder id) to the data library url

That seems like the probable culprit, nice find @anuprulez !

**Comment by nsoranzo** [comment]
Fixed in #5327.
