### ISSUE TITLE
data libraries: unable to edit 'description/message'

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#5309]
Using the new interface one cannot modify the `description` column(or `message` as it is called in the 'details' overview). In this instance I'm logged in as an admin.

See:
![screen shot 2018-01-15 at 08 15 19](https://user-images.githubusercontent.com/102411/34931003-a4f10438-f9cc-11e7-8bd8-bfc3946aaba3.png)

vs

![screen shot 2018-01-15 at 08 15 01](https://user-images.githubusercontent.com/102411/34930952-68ff1da2-f9cc-11e7-8ae5-06d17459bd6b.png)

**Comment by martenson** [comment]
Should be fixed by the PR linked above, thanks for the report @scholtalbers !
