### ISSUE TITLE
Also delete HDAs when deleting HDCA ?

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#5310]
Ideally we should be able to delete an HDA **if** it is private to a collection, but currently nothing happens to the state of HDAs when deleting a collection. And HDAs in collections should be private, right ?

**Comment by jmchilton** [comment]
They exist inside and outside the HDCA unfortunately - if they were just private this would easier for sure. Someday we will get there I think. It would be good to at least have an option to do this though for sure in the meantime. Brought up by @bebatut also on gitter today.

I'll attach an 18.05 milestone to this and assign myself feel free to beat me to it though if I let you down.

**Comment by martenson** [comment]
resolved by the PR linked above I think
