### ISSUE TITLE
Deleting a workflow does not remove it from the Tool Panel (when pinned)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#5318]
Where tested: Galaxy version 17.09 as run at https://usegalaxy.org

Use-case:

1. Create a workflow and check the box "Show in tools panel" to pin it so it shows up.
2. Delete the workflow.
3. The deleted-but-pinned workflow still shows up in the tool panel. When clicked on, it populates the center panel and _appears usable_ (but I didn't test that).
4. The deleted-but-pinned workflow _does not_ show up under "All workflows" or on that same page when reached directly from the masthead "Workflow" link.
5. There is no method to review deleted workflows to change the pinned setting.

ping @dannon 

Reported by: https://biostar.usegalaxy.org/p/26317/

**Comment by dannon** [comment]
@jennaj Thanks for making the issue here -- I saw this one come in too and have a hunch that I'll test out.

**Comment by jennaj** [comment]
@dannon @mvdbeek I'm still seeing this problem at ORG running pre-release 18.09.

Is a bugfix that can happen after release (right?).

**Comment by jennaj** [comment]
Oh, nevermind, I needed to completely refresh Galaxy, not just the tool panel to get this to take effect. Closing again & thanks for fix!
