### ISSUE TITLE
Documentation: lots of errors on Cluster page

### ISSUE THREAD

**Issue by lachlansimpson** [galaxyproject/galaxy#5319]
If you look at [the documentation page for using Galaxy with a cluster](https://docs.galaxyproject.org/en/master/admin/cluster.html) you will see that it has a number of compilation errors.

For the best example of this see [the anchor for job plugins](https://docs.galaxyproject.org/en/master/admin/cluster.html#job-plugins)

**Comment by scholtalbers** [comment]
Something is going wrong indeed. More examples:
- https://docs.galaxyproject.org/en/master/dev/schema.html#attributes
- https://docs.galaxyproject.org/en/master/dev/schema.html#reserved-variables

**Comment by nsoranzo** [comment]
@scholtalbers That's a different issue, due to how when generate the schema.html page.
