### ISSUE TITLE
data managers and tools that output to file_path dont work if jobs are run as real user

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5323]
Data managers read and write (the same) json file during the execution. This file is stored in file_path and no chown is executed before and after the execution. Hence the writing the json file does not work. 

```
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/shed_tools/toolshed.g2.bx.psu.edu/repos/iuc/data_manager_mothur_toolsuite/ab7a7e798c34/data_manager_mothur_toolsuite/data_manager/fetch_mothur_reference_data.py", line 559, in <module>
    open(jsonfile, 'wb').write(json.dumps(data_tables))
IOError: [Errno 13] Permission denied: '/gpfs1/data/galaxy_server/galaxy-dev/database/files/004/dataset_4529.dat'
```

I verified this with multiple data managers (hisat2, bowtie, mothur). 

Wouldn't it be better to have the json file in the job_dir (chown of the job_dir is executed)?

**Comment by mvdbeek** [comment]
You're right that it would be better to do this in the job working directory. There should be plenty of tools though that write directly to the output location, do they all fail for you ?

**Comment by bernt-matthias** [comment]
I did not stumble over such a tool. Do you have an example? Then I could try.

**Comment by mvdbeek** [comment]
bwa, bowtie2, basically all tools that don't use `from_work_dir="<some_output_file>"`. But I guess the answer will be that that works for you. I'll have to dig through the run_as_real_user code to see why it works most of the time but not for data managers.

**Comment by mvdbeek** [comment]
The workaround would be to change the data managers to use `from_work_dir`.

**Comment by mvdbeek** [comment]
Can you check if this works for you? https://gist.github.com/mvdbeek/63dfd2e29b2efbdfe0dab6f8156e01f7

**Comment by bernt-matthias** [comment]
@mvdbeek I did some experiments. 

> There should be plenty of tools though that write directly to the output location, do they all fail for you ?

I checked a tool that does not use from_work_dir for the output (I tested randombed from the bedtools). As you suggested the tool fails if the job is started as real user, since the tool tries to write directly to file_path. So I guess that many tools are affected. 

Its odd that this never happened to me before .. 

> Can you check if this works for you? https://gist.github.com/mvdbeek/63dfd2e29b2efbdfe0dab6f8156e01f7

I did the equivalent modifications to the hisat2 data manager and it did not work, because the json file is also used as input which is seemingly generated by Galaxy (I do not understand the data manager workflow at this point). This input file does not exist when the tool is started.

I see two possible solutions:
- all output files should be generated in the working directory (or another directory that is writable by the user) and moved to the file_path after the ownership is changed back to the galaxy user. 
- The output files need to be created (touched .. then it would work also for data managers where the file already exists) and threated by the external chown script. 

I think the former is the cleaner solution.

**Comment by mvdbeek** [comment]
Ah, I was looking for this yesterday but didn't find it.
Did you set `outputs_to_working_directory` to True in your galaxy.ini ? That may also help things.

**Comment by bernt-matthias** [comment]
@mvdbeek That saved my day. If `outputs_to_working_directory` is set to true everything works perfectly. Thank you so much. I will check if I can improve the documentation in galaxy.ini to avoid misconfiguration.

**Comment by mvdbeek** [comment]
Awesome!

I think mentioning this option makes sense above `drmaa_external_runjob_script` in the galaxy.ini.
`outputs_to_working_directory ` is already mentioned in https://docs.galaxyproject.org/en/latest/admin/cluster.html#configuration, but the link hasn't been updated in the galaxy.ini.

**Comment by nsoranzo** [comment]
> `outputs_to_working_directory` is already mentioned in https://docs.galaxyproject.org/en/latest/admin/cluster.html#configuration, but the link hasn't been updated in the galaxy.ini.

There's a redirect in place.
