### ISSUE TITLE
Upload tool failing on OSX due to warning message (kqueue import failure)

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#5341]
![](https://user-images.githubusercontent.com/13082854/35129590-6a97eb70-fd10-11e7-8eab-1b120a55a310.png)

We ended up having all of our workshop participants comment out line 74 ~/.planemo/gx_venv/lib/python2.7/site-packages/watchdog/observers/init.py

```
warnings.warn("Failed to import fsevents. Fall back to kqueue")
```

Which thereby allowed uploads (so planemo serve, planemo test) to both work.

originally filed as https://github.com/galaxyproject/planemo/issues/751

**Comment by mvdbeek** [comment]
Hmm, forgot about this one. The issue is that watchdog is a pure python wheel on linux, but on OSX it is compiled against fsevents, we were working on this here: https://github.com/galaxyproject/starforge/pull/183

**Comment by mvdbeek** [comment]
Alright, thanks for the report @erasche. The fixed wheels are up, I've removed my ~/.planemo folder and tried planemo serve and uploading a file.
