### ISSUE TITLE
Containers interface improvements

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#5348]
`galaxy.containers` has a few TODO items:

- Implement the Docker API interface<sup>1</sup>
- Round robin support for the host option, at least for Docker swarm (running multiple managers is fairly useless if the manager that Galaxy uses for communication goes down)

<sup>1. this entire library grew out of the GIE command line docker interface which is why I implemented the CLI docker interface in the first place, although I should have abandoned that effort for the API early on, but... I didn't, so here we are.</sup>

**Comment by hexylena** [comment]
Guess this one will be irrelevant in future

**Comment by natefoo** [comment]
I also did both of these things, ha. Didn't realize I'd created an issue for them.
