### ISSUE TITLE
Data Library parameter allows to select deleted dataset versions

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#535]
The data library input parameter fails to properly display multiple versions of the same underlying library dataset. The library API call should either not return deleted datasets or deleted datasets need to be filtered from its response. See also: https://github.com/galaxyproject/galaxy/pull/132#issuecomment-115925257

**Comment by martenson** [comment]
If user is an admin and the `deleted` flag is not specified the /api/libraries will list all libraries (deleted or not). If you specify the `deleted=false` in the call you should get only non-deleted libraries which is what you probably want. see https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/managers/libraries.py#L114

Is there a problem with library dataset API regarding versions? The idea is that you call `/api/libraries/datasets/{encoded_dataset_id}` which gives you the latest dataset and ldda_ids of the expired versions https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/lda_datasets.py#L74
and the individual versions you can retrieve via `/api/libraries/datasets/:encoded_dataset_id/versions/:encoded_ldda_id` (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/lda_datasets.py#L88)

You are probably the first user of the ldda version API besides myself so it can be pretty buggy. :)

**Comment by guerler** [comment]
That sounds good. Thanks.

**Comment by guerler** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/546
