### ISSUE TITLE
Collection operation problems 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5355]
The tool "flatten collection" duplicates data sets: For the duplicates the full path and the data set number is the same. The later one shows some "inheritance chain"

Unzip collection produces no results. The data set list is shown, but exploring it gives a completely empty history panel.

**Comment by mvdbeek** [comment]
I have seen the first happen when you run collection operation tools on collections created in that same history when you choose not to hide the source dataset, and that makes sense code-wise. The collection operation tools though should probably always produce hidden HDAs.

**Comment by mvdbeek** [comment]
I think we've solved this by always copying HDAs when creating collections from the history.
