### ISSUE TITLE
Upload Purge is Inconsistent

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5361]
Depending on the upload options and file types involved - many times it doesn't actually purge. Given that it has never consistently purged all files - my preference going forward would be to:

- Swap the default to ``False``.
- Allow override to True and then consistently delete the original file even if a ``shutil.move`` isn't used to remove in ``upload.py``.

**Comment by mvdbeek** [comment]
I think @jmchilton mostly fixed that some time ago, right ?
