### ISSUE TITLE
LookupError: Entry point 'prefix' not found in egg 'PasteDeploy'

### ISSUE THREAD

**Issue by mandorodriguez** [galaxyproject/galaxy#5362]
I just did an update to the recent version. Did the compile procedure for node.js and when i try and start the server i get this error. 

LookupError: Entry point 'prefix' not found in egg 'PasteDeploy'

I didn't change any of my configuration files, are some of the older options causing this?

**Comment by martenson** [comment]
@mandorodriguez which version did you update to and from?

**Comment by mandorodriguez** [comment]
Don't remember the previous version but It didn't need the node.js compilation, the update is to the current version available from a pull.

**Comment by martenson** [comment]
@mandorodriguez are you on the `dev` branch? Run `git status` in the repository folder to find out.

**Comment by mandorodriguez** [comment]
Yessir, I am on Dev branch.

**Comment by martenson** [comment]
Unless you are developing in Galaxy or are very confident about running unreleased version I very much recommend to run a 'release' version. The latest is currently the `release_17.09` branch and how to obtain it is explained in https://galaxyproject.org/admin/get-galaxy/.

Please answer a few questions to help me troubleshoot your issue:
Do you run Galaxy behind proxy?  Do you have `galaxy.ini` file in the config folder? Does it contain an option similar to `#filter-with = proxy-prefix`?

**Comment by mandorodriguez** [comment]
Yes it's run a proxy to feed the app running on port 8090 to just a regular url at port 80. The proxy-prefix option is set:

[app:main]
filter-with = proxy-prefix
cookie_path = /galaxy

**Comment by martenson** [comment]
What is the config value of `prefix` ?

**Comment by mandorodriguez** [comment]
[filter:proxy-prefix]
use = egg:PasteDeploy#prefix                                                                                                                                 
prefix = /galaxy

**Comment by martenson** [comment]
@mandorodriguez all of that looks fine. Could you please share the whole config file with me? Please take care of removing passwords and secrets from it.

**Comment by mandorodriguez** [comment]
Ok here. I've migrated it from version to version for years without any issues. 

[galaxy.ini.txt](https://github.com/galaxyproject/galaxy/files/1653114/galaxy.ini.txt)

**Comment by martenson** [comment]
Using your config I am able to start Galaxy so I suspect your Paste egg might be the culprit here? Ping @natefoo - the admin expert.

**Comment by mandorodriguez** [comment]
@martenson gotcha, thanks a bunch!

**Comment by natefoo** [comment]
What's the output of `./.venv/bin/pip list`?

**Comment by mandorodriguez** [comment]
@natefoo I never enabled a virtual env for this galaxy instance. It just ran it off of anaconda python as this is the only app running off of this server.

[pip_list.txt](https://github.com/galaxyproject/galaxy/files/1653365/pip_list.txt)

**Comment by natefoo** [comment]
This looks ok. Are you running Galaxy as a paste server or with uWSGI?

**Comment by mandorodriguez** [comment]
Currently running as a paste server.

**Comment by natefoo** [comment]
I'll need to try to recreate this. I suspect the way we changed config file detection and loading isn't working with the conda setup. Do you start with `run.sh --skip-venv` or call `scripts/paster.py` directly?

**Comment by natefoo** [comment]
One additional question: what method did you use to install the dependencies?

**Comment by mandorodriguez** [comment]
@natefoo  I had a server script that called the paster like:

python ./scripts/paster.py serve

It does the same thing if I call it via just using run.sh with no args. Which is one of the other ways I'd call it. 

To install all the dependencies to that current anaconda build I did:

conda install --yes --file ./lib/galaxy/dependencies/requirements.txt

**Comment by natefoo** [comment]
That `requirements.txt` doesn't account for our pinned versions, and isn't conda requirement syntax compatible anyway. There's a process [here](https://docs.galaxyproject.org/en/master/admin/framework_dependencies.html#conda) but it's somewhat out of date, so I'm working on updating it.

**Comment by mandorodriguez** [comment]
@natefoo okies, thanks!

**Comment by mandorodriguez** [comment]
@natefoo  Is the yml configuration the "new" way to set up a galaxy config? Was thinking of converting my older file to it if that's the case to see if I have any luck.

**Comment by martenson** [comment]
@mandorodriguez yes, from 18.01 onwards the new config will be yaml based and Galaxy running on uwsgi (old continue to work and run on paste)

**Comment by natefoo** [comment]
A slight clarification, you can also switch to using uWSGI but keep your ini config. However, migration to the YAML config should be preferred in the long run.

**Comment by natefoo** [comment]
@mandorodriguez I can't reproduce this with conda - I suspect it's an issue with the dependency versions in your conda environment. Can you post `conda list` to show which were installed from pip and which from conda?

**Comment by mandorodriguez** [comment]
@natefoo @martenson  Seems to be wanting the proxy-prefix section when parsing the older ini file

LookupError: No section 'proxy-prefix' (prefixed by 'filter') found in config /var/local/galaxy-site/universe_wsgi.ini

And this is the section generating my error and still not sure why:

#[filter:proxy-prefix]                                                                                                                          
use = egg:PasteDeploy#prefix                                                                                                                   
prefix = /galaxy

**Comment by mandorodriguez** [comment]
@natefoo  
Sure
[conda_list.txt](https://github.com/galaxyproject/galaxy/files/1661538/conda_list.txt)

I know the method throwing the error find_egg_entry_point is in this module in my galaxy download.

lib/galaxy/util/pastescript/

**Comment by martenson** [comment]
@mandorodriguez the `[filter:proxy-prefix]` seems to be commented out in the gist you sent? Is that a typo?

**Comment by mandorodriguez** [comment]
@martenson yes a typo I had commented it out completely previously. Uncommenting it all produces the error I've been getting:

LookupError: Entry point 'prefix' not found in egg 'PasteDeploy' (dir: /usr/local/anaconda/lib/python2.7/site-packages; protocols: paste.filter\
_factory, paste.filter_app_factory; entry_points: )

**Comment by natefoo** [comment]
@mandorodriguez This may be pretty tough to get to the bottom of with your environment. Can you try creating a new environment and running `pip install --index-url https://wheels.galaxyproject.org/simple/ --extra-index-url https://pypi.python.org/simple/ -r requirements.txt` in it, and let us know if you still get the error with that?

I've updated the documentation with a new procedure and script for installing dependencies with Conda 4.4+ in #5390 that would at least control the versions of dependencies when installing from Conda.

**Comment by mandorodriguez** [comment]
@natefoo Will do, I just converted my file over into the yaml format. 

Seems it doesn't like my old postgres database line and isn't connecting to the db:

OperationalError: (psycopg2.OperationalError) FATAL:  database "galaxy" does not exist
 (Background on this error at: http://sqlalche.me/e/e3q8)

Looking into it now.

**Comment by mandorodriguez** [comment]
@natefoo  Not sure if I should start a new issue here but I'm having a problem with the proxy settings after doing the update and converting over to the yaml config. 

Error I'm getting is:

> Not Found
> The requested URL /root/login was not found on this server.

I'm attempting to serve it from a proxy subdirectory '/galaxy' the way I had it before.
Attached is the new yaml config (with database address and pass removed), my old galaxy proxy settings that worked on the paste server and the newer one.

[galaxy.conf.txt](https://github.com/galaxyproject/galaxy/files/1679446/galaxy.conf.txt)
[galaxy.conf.old.txt](https://github.com/galaxyproject/galaxy/files/1679447/galaxy.conf.old.txt)
[galaxy.yml.txt](https://github.com/galaxyproject/galaxy/files/1679448/galaxy.yml.txt)

**Comment by natefoo** [comment]
The procedure is different with uWSGI, see the documentation here: https://docs.galaxyproject.org/en/latest/admin/nginx.html

**Comment by mandorodriguez** [comment]
@natefoo I switched over from apache to nginx, set up the configuration files and get this error when trying to start the server to test:

> RuntimeError: function attributes not accessible in restricted mode

**Comment by mandorodriguez** [comment]
@natefoo @martenson Is port 8080 hardcoded anywhere in release_17.09? I set galaxy to use port 8090 due to tomcat using 8080 and i keep getting binding errors.

**Comment by martenson** [comment]
@mandorodriguez I am pretty sure it is not, the configuration port is respected

**Comment by mandorodriguez** [comment]
@martenson Aah sorry my mistake, it was picking up config/galaxy.ini.sample

**Comment by natefoo** [comment]
I think the original issue reported has been addressed, feel free to open issues for any additional issues you have.
