### ISSUE TITLE
[Feature Request]: Sort Data Library items by size

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/galaxy#5366]
Right now (at least in Galaxy 17.05) it's only possible to sort data library items alphabetically. It would help me a lot if there were other sorting methods in the UI.

**Comment by martenson** [comment]
latest version sorts on datatype, desc, state, and name

sorting on size could be useful I guess

**Comment by bwlang** [comment]
Would also be good to sort library items by time updated too...

**Comment by martenson** [comment]
implemented in https://github.com/galaxyproject/galaxy/pull/8281 by the wonderful @bwlang
