### ISSUE TITLE
Unable to enter value in numerical input with keyboards that use 'shift' for numbers

### ISSUE THREAD

**Issue by vloux** [galaxyproject/galaxy#5370]
Seem to be related to #507 

Impossible to enter a numerical value with a french keyboard mapping (using the numeric keys above azerty line) on numerical inputs. I spot it on a local Galaxy instance and can reproduce it on main usegalaxy ( Tool text Manipulation/Select first lines from a dataset  , "Number of lines" box)

 It is nevertheless Ok with numpad, or Ok if I switch my keyboard mapping to US/English .

**Comment by mvdbeek** [comment]
My colleague had the same problem, though I think it worked in firefox and chrome, but not safari.

**Comment by vloux** [comment]
Sorry, 
obviously should have mentionned the OS and browser version.

Bug reproducible on :
Mac OS 10.13.2  
&
- Safari 11.02
- Chrome 63.0.3239.132

It works on Firefox 57.0.4
