### ISSUE TITLE
missing len files (ucsc)

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5372]
No len files are available for ucsc data. So for instance CONVERTER_bed_gff_or_vcf_to_bigwig_0 fails bacause it can't find tool-data/shared/ucsc/chrom/hg38.len (the directory is completely empty, ie it wont work for any genome)

**Comment by gallardoalba** [comment]
We recently got an error report related to this issue. Would it make sense to modify those tools in order to use the fetchChromSizes conda package to download the chrom.sizes file from the UCSC database? I guess that those are small datasets.

**Comment by mvdbeek** [comment]
I think admins were supposed to run cron/build_chrom_db.py at one point, not sure if that still works ?

**Comment by bgruening** [comment]
This script still works. @gallardoalba for which genome you are missing len files?

**Comment by nsoranzo** [comment]
It does work, I use `cron/updateucsc.sh.sample`, rename it to `cron/updateucsc.sh` and run it through cron.

**Comment by gallardoalba** [comment]
> This script still works. @gallardoalba for which genome you are missing len files?

WuhCor1 is the required len file.

**Comment by bgruening** [comment]
@bgruening that should be fixed now.
