### ISSUE TITLE
Rule Builder / Uploader Issues for Iteration 1

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5380]
Issues / Bugs:

- [x] ~Issue a warning to the user if they attempt to run this with non HDAs for now.~ (Reported by @mvdbeek.) a29a42a64b55330e5e3ca2e305275f0c41ed020a
- [x] ~Everything breaks if a regex is invalid - I baked in some error handling and display but not for this it seems.~ (Reported by @mvdbeek.) 755d865dee81330274e75e69aad6b90b0b9dbed7
- [x] ~No warning on jagged tables - it just renders only the number of columns in the first row.~ 4997ba6208e7de5f8c9439276cc5799f9f18e422
- [x] ~Column labels are only assigned on the result - so the description of the columns can be quite off. We could either remove this information (so display "concatenate columns" instead of "concatenate columns A and B" or track the column information over time and render the right label for the corresponding operation step). By the same token editing rules originally added earlier in the rules list results in showing the final resulting columns.~ c2527f52b2919d1beb27d5adf08b3037bbab29fb
- [x] ~Update job state and display warning about longer jobs in fetch API mode.~ eebb084994b6f1182e3ba1fc11bd372dbaa50841
- [x] ~Only display FTP-related information and options if FTP is enabled.~ d29ce13226a1daa6c115a305d2012519a3ed48b7
- [x] ~Jobs are not displayed in the history panel at all - and the fetch tool doesn't have any fixed outputs so if the user dismisses the dialog that monitors the upload or leaves and comes back - they don't status updates and need to refresh the history to see the final result. We could tweak the API to pre-create the outputs specified or we could do what a lot of tools do and just add a log of the outputs that is always created. We could throw some information in there.~ Tweaked the API to pre-create datasets and/or a collection outline #5609 99a93f79ba64d2404cfc0937f6c6673735cc2223
- [x] ~Sometimes horizontally scrolling the data seems broken.~ (Reported by @mvdbeek.) 4997ba6208e7de5f8c9439276cc5799f9f18e422
- [x] ~Fixing the above item seems to have added double scroll bars to the table in the screenshots from the Selenium tests.~
- [x] ~Sort seems to be pretty broken.~
- [x] ~Eliminate multi-select for list identifiers - they are ordered - need something like individual selectors and a button to add new ones.~

Enhancements:

- [ ] Add drop target for text datasets. (Suggested by @mvdbeek.)
- [x] ~Display column definitions in the table in some way.~ 72b072665f01984510f5b6dde2b50808a3abf018
- [ ] Separate but related to the above - allow column headers from the original data.
- [ ] New filter - contains value.
- [x] ~New column adder - regex with specified number of groups to capture (makes splitting much easier for instance).~ (Re-did regex column adder - has different modalities including this.)
- [ ] Add checkbox requiring multiple collections to be matching - currently one can create two collections with the same structure but there is no way to force that they are the same structure and warn if they aren't. Would then implement #3916.
- [ ] Handle mouse-over for rules:
    - High-light columns of the table for various column addition operations.
    - Display filter statistics.
- [ ] Allow setting path for admins.

**Comment by nuwang** [comment]
@jmchilton Just wanted to flag this issue: https://github.com/galaxyproject/galaxy/issues/4443 since you seem to be heavily refactoring the uploader. It would be great if the data source tools and upload tool can be made consistent when it comes to compressed file handling.
