### ISSUE TITLE
Cant' view newly uploaded fasta file

### ISSUE THREAD

**Issue by lijingbu** [galaxyproject/galaxy#5394]
Hi Galaxy developers,

We have recently deployed the Galaxy version 17.09 on our local server. We found the "view data" functions doesn't work for newly uploaded (pasted) fasta files. **Upload by choosing a local file works fine. Just upload by pasting data shows error.**  It shows the error message below. The button/function works well for the tabular format. And if I change the uploaded fasta file to tabular format, it works fine to display the content. If I change to txt format, it won't work either. Can anyone help? Thanks! 

`The requested URL /galaxy/datasets/a5453f3e6cc79810/display/ was not found on this server.`

Also paste the log for the **success view** 
`xxx.xxx.xxx.xx - - [25/Jan/2018:15:50:44 -0600] "GET /galaxy/datasets/9e190f8c9e0c9cbc/display/?preview=True HTTP/1.1" 200 - "https://taos.alliance.unm.edu/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Fncbi_blast_plus%2Fncbi_blastp_wrapper%2F0.2.01&version=0.2.01&__identifer=mth020hhksq" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"
129.24.145.60 - - [25/Jan/2018:15:50:44 -0600] "GET /galaxy/api/webhooks/onload/all HTTP/1.1" 200 - "https://taos.alliance.unm.edu/galaxy/datasets/9e190f8c9e0c9cbc/display/?preview=True" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"`

and the log for the **failed view**
`xxx.xxx.xx.xxx - - [25/Jan/2018:15:51:07 -0600] "GET /galaxy/datasets/a5453f3e6cc79810/display/?preview=True HTTP/1.1" 200 - "https://taos.alliance.unm.edu/galaxy?tool_id=toolshed.g2.bx.psu.edu%2Frepos%2Fdevteam%2Fncbi_blast_plus%2Fncbi_blastp_wrapper%2F0.2.01&version=0.2.01&__identifer=mth020hhksq" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"`

**Comment by jennaj** [comment]
Posted as a question at Biostars: https://biostar.usegalaxy.org/p/26484

It may need dev review/input.
