### ISSUE TITLE
api/tools error for datacollection

### ISSUE THREAD

**Issue by fmareuil** [galaxyproject/galaxy#5399]
Hello,

I encountered an error with the request :
https://usegalaxy.org/api/tools/toolshed.g2.bx.psu.edu/repos/iuc/mothur_get_groups/mothur_get_groups/1.36.1.0?io_details=True
This error appears only when tools have a datacollection output.
I can fix it with changing the inheritance of ToolOutputCollection from ToolOutputBase to ToolOutput (line 70 : lib/galaxy/tools/parser/output_objects.py) but I'm not sure if it's the best way to fix it.

Best regards,

**Comment by hexylena** [comment]
The tools have seen significant changes since then, it is likely this is resolved in newer versions
