### ISSUE TITLE
Jenkins is running API tests as part of tool framework test sutie.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5404]

**Comment by jmchilton** [comment]
It hasn't been running framework tests at all I think - it has been running the API tests twice. Looks like the Jenkins job description was changed. From a custom command-line to using the actual scripts in .ci/jenkins but it was pointing at api instead of framework. Should be fixed for new PRs and runs now.

**Comment by martenson** [comment]
@jmchilton I probably broke it, when I was updating the invocations to use the scripts, sorry.

https://gitter.im/galaxyproject/Lobby?at=5a6a1f26d9f895c3605e7d5a

**Comment by jmchilton** [comment]
No problem at all - thanks for updating it. I'm excited to be using the scripts now!

**Comment by martenson** [comment]
I just updated the API tests to also use the script. It seems I overwrote the framework test config with what I wanted to have in the api test config or sth. Blah.

**Comment by nsoranzo** [comment]
Here's the wrong change https://jenkins.galaxyproject.org/job/docker-framework/jobConfigHistory/showDiffFiles?timestamp1=2018-01-25_13-16-37&timestamp2=2018-01-25_13-23-12
