### ISSUE TITLE
Transpose a set of collections

### ISSUE THREAD

**Issue by hepcat72** [galaxyproject/galaxy#5409]
I tried searching for this as a pre-existing feature request about this, but I couldn't find it, so I hope this isn't a duplicate...

I currently have a workflow that requires me to download, run a local script, and then upload to run the next galaxy step.  There's probably some other work-around for this issue, so this might be a poor example - or perhaps this has already been solved and I just don't know how to do it, but for what it's worth, here's specifically what I'm doing:

I've been running htseq-count multiple times, each with a different feature type.  The input is the same collection of samples each time, resulting in 1 collection output for each feature type.  I then, for each sample, want to concatenate (and sort) the outputs across those collections so that my final output is a single collection with 1 data file for each sample containing the counts of all the feature types I've run on.

Is there a way to take multiple collections, each with a set of same-named output files and perform a task on a cross-section of those samples?  Or can I take multiple collections and "transpose" them to create collections composed of the cross-sections of their files?  E.g. Let's say I've run htseq-count 5 times (with 5 feature types resulting in 5 collections, each with the same 10 samples).  Could I create 10 collections, each containing the 5 "same-named" files, so that I can concatenate them, and then create one merged output collection of all the samples in a single workflow?

My local script does the concatenation currently, which I then upload as a single collection.

**Comment by mvdbeek** [comment]
So if I understand this correctly you would like to take collection A, run htseq-count with different parameters on collection A, which will give you as many collections as you will run htseq-count. Let's call them B,C,D,E, F.

Now you can use `Concatenate datasets tail-to-head` and concatenate collections B,C,D,E,F. That should do the right thing and concatenate the matching collection elements. The result would be a collection, whose elements will be the concatenated output of the different htseq runs.
Is that what you would like to achieve ?

**Comment by hepcat72** [comment]
If I understand your wording correctly, yes, but just to be explicit, let me extend the example by a degree of granularity.  Given collections B,C,D,E,F, each containing samples 1,2,3... i.e.:

```
B.1
B.2
B.3
C.1
C.2
C.3
...
```

I want to concatenate all the `.1`'s, `.2`'s, and `.3`'s together, producing my final collection `G`, containing 3 samples:

```
G.1   #Composed of cat B.1,C.1,D.1,E.1,F.1
G.2   #Composed of cat B.2,C.2,D.2,E.2,F.2
G.3   #Composed of cat B.3,C.3,D.3,E.3,F.3
```

**Comment by mvdbeek** [comment]
Yep, that is what should happen

**Comment by hepcat72** [comment]
Well OK, great. I guess I just didn't understand how it worked. Thanks for your help.
