### ISSUE TITLE
Subworkflow and parameter changes on run-time

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy#5410]
Hi,

I am testing the subworkflow functionality. It is a really nice! I just got some errors..

Currently for a workflow calling a subworkflow, the parameters of the subworkflow can not be changed before running the "master" workflow:

![screen shot 2018-01-30 at 09 26 02](https://user-images.githubusercontent.com/1842467/35555510-ae4cadaa-059f-11e8-8903-31465bcaab72.png)

If in the subworkflow there is parameters "set at runtime", the values for the parameters can not selected, but the workflow can still be launched and the corresponding tool will fail with:
 
![screen shot 2018-01-30 at 09 30 19](https://user-images.githubusercontent.com/1842467/35555689-457d5eea-05a0-11e8-9b55-24fa5d292bdc.png)

But nothing in `stderr` or when clicking on "View or report this error"

![screen shot 2018-01-30 at 09 30 32](https://user-images.githubusercontent.com/1842467/35555701-4e4a9326-05a0-11e8-8742-dd814bad2b33.png)

I got these errors both on Freiburg instance and a Docker instance

Bérénice

**Comment by mvdbeek** [comment]
Yes, that doesn't work currently, the right fix would be to be able to set the nested workflows parameters (https://github.com/galaxyproject/galaxy/issues/1887). We should fail to validate these workflows in addition.

**Comment by mvdbeek** [comment]
I think this should be solved with #6664. We still don't display all of the subworlfow in the run form, so you can only change the parameters that are set as runtime parameters, but I think that is OK and makes the variable parts of a workflow more explicit.
