### ISSUE TITLE
Toolshed throwing exceptions on repo update

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5425]
and also seems to mark installable revisions wrongly

from gitter:
>[greg__] Starting about yesterday afternoon, every changeset uploaded a repo in the TTS produces this exception:
[greg__] Metadata may have been defined for some items in revision '99102499271a'. Correct the following problems if necessary and reset metadata.
[greg__] ideas_preprocessor.xml - type object 'HistoryTagAssociation' has no attribute 'table'
[greg__] This issue results in a new installable changeset revison for the repo, while it should be an update to the previous installable revision.
[greg__] This forces admins to install the latest revision of the repo into Galaxy rahter than just getting an update to the current installed revision.
[greg__] Yeah, I've not tried more than 1 repo, but it looks like a recent metadata change may have done this?
[greg__] The key is htis exception: HistoryTagAssociation' has no attribute 'table'

>Marius van den Beek @mvdbeek 09:28 Yeah, I'd roll back the TTS update ... there's clearly a bug there

As of 11:17am Wednesday the TTS has been rolled back to 17.09 and is waiting for a fix.

**Comment by davebx** [comment]
Fixed in galaxyproject/galaxy#5433
