### ISSUE TITLE
Dataset hashtags display problem in select lists

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#5428]
The dataset hashtags are each displaying with a prefix added == `name` in tool form select menus. 

<img width="951" alt="screen shot 2018-01-31 at 11 29 41 am" src="https://user-images.githubusercontent.com/8999735/35643298-ba58d444-067a-11e8-84a5-10902ebf7667.png">

Galaxy version (as run at https://usegalaxy.org): Galaxy version 17.09, commit a82d325d18375797ce8ab53366320f3c9a772ab7

Test history: https://usegalaxy.org/u/jen/h/test-history-sort-sam-bam

Ping @jmchilton @guerler

**Comment by hexylena** [comment]
Merging into #6147 :(
