### ISSUE TITLE
Collection operation tools don't map over correctly

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#5430]
Say you've got Collection A, with elements A,B,C,D.

If you have another collection B with elements A,B,C, with content A,B,C, we should be able to map over collection B in the `Filter List from contents of a file` tool, creating 2 (one for the included elements, one for the excluded element) X 3 collections (one for each element in B). Instead we are only creating 2 collections that are deeply nested and remain grey.

**Comment by mvdbeek** [comment]
Or should we actually be creating nested lists here ?

**Comment by mvdbeek** [comment]
OK, my bad, this should actually produce a nested collection, but something in the structure of that collection is not quite right.

**Comment by mvdbeek** [comment]
And this is also not specific to collection operation tools, the same thing happens with a variant of relabel from file where I removed the directives that are specific to collection operation tools. Makes me think that this could be a recent regression.

**Comment by mvdbeek** [comment]
That still works on 17.09, I will bisect this.

**Comment by mvdbeek** [comment]
Alright, the bad commit seems to be 78babab6455f4cd1c51aed0b1ddf6b4b29ad6d03

**Comment by jmchilton** [comment]
And you are sure you didn't already fix this with https://github.com/galaxyproject/galaxy/pull/5413? I've been known to spend hours tracking down issues I've fixed in other branches 🤣.

**Comment by mvdbeek** [comment]
uff, I'll double-check!

**Comment by mvdbeek** [comment]
No, I may have just fixed it now :D

**Comment by mvdbeek** [comment]
This is fixed now, thanks again @jmchilton !
