### ISSUE TITLE
Upload form does not display the Reset button for composite uploads

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#5432]
The "composite" tab on the upload form is missing the "Reset" button, so after uploading a composite dataset it is not possible to upload another one without restarting the server.

**Comment by mvdbeek** [comment]
As a better workaround than restarting the server, the entire upload form should be refreshed after a browser refresh  -- does that work for you ?

**Comment by gregvonkuster** [comment]
Yes, better workaround.
