### ISSUE TITLE
HDCA Deletion Broken in 18.01.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5435]
From @mvdbeek:

I think previously permanently deleting a HDCA resulted in the datasets being deleted as well
Now deleting an HDCA doesn't do anything, I think
except for deleting the HDCA in the history

General issues maybe can be tracked here (https://github.com/galaxyproject/galaxy/issues/5402) but I want to make sure the regressions are fixed for 18.01 so I'm creating this issue.

**Comment by jmchilton** [comment]
@mvdbeek  In working on #5442 I saw no code that would lead me to believe that at any point  "permanently deleting a HDCA" would delete the datasets as well. There is no link anywhere for permanently deleting an HDCA except for in multi-action menu and it looks like that would be broken - https://github.com/galaxyproject/galaxy/issues/5117 seems like what I would expect to happen based on the code.

Can I close this out when #5442 or some variant of that is merged?

**Comment by mvdbeek** [comment]
Absolutely, with these PRs I have nothing to complain about anymore :).
