### ISSUE TITLE
ToolShed tests fail locally since #4833

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#5452]
Some TS tests fail consistently on my laptop, e.g.:

```console
$ ./run_tests.sh -toolshed test/shed_functional/functional/test_1470_updating_installed_repositories.py
```

which produces [this log](https://gist.github.com/nsoranzo/ee18e4bbf0ff20fe38cce784043bd732).

In this setup, Galaxy and the TS use SQLite, but I'm not sure using PostgreSQL as on Jenkins would fix the issue.

I was able to fix the problem for this test with the following patch:

```patch
diff --git a/lib/galaxy/webapps/galaxy/controllers/admin_toolshed.py b/lib/galaxy/webapps/galaxy/controllers/admin_toolshed.py
index 8a48c6eaab..e171f5b55d 100644
--- a/lib/galaxy/webapps/galaxy/controllers/admin_toolshed.py
+++ b/lib/galaxy/webapps/galaxy/controllers/admin_toolshed.py
@@ -1619,7 +1619,8 @@ class AdminToolshed(AdminGalaxy):
                                                               tool_shed=tool_shed_url,
                                                               name=name,
                                                               owner=owner,
-                                                              changeset_revision=changeset_revision)
+                                                              changeset_revision=changeset_revision,
+                                                              refresh=True)
         original_metadata_dict = repository.metadata
         original_repository_dependencies_dict = original_metadata_dict.get('repository_dependencies', {})
         original_repository_dependencies = original_repository_dependencies_dict.get('repository_dependencies', [])
```

`git bisect` reveals that the problem started after the merge of https://github.com/galaxyproject/galaxy/pull/4833 , but I'm not sure that is to be blamed either, it probably just exposes an underlying issue with the `ToolShedRepositoryCache` (introduced in https://github.com/galaxyproject/galaxy/pull/3909).

`app.tool_shed_repository_cache` is rebuilt in various places (e.g. during toolbox reload), but I think that should probably be called more specifically when TS repos are installed, updated or removed.

**Comment by mvdbeek** [comment]
The fix looks correct to me, this is what it should have been in the first place IMO.

> app.tool_shed_repository_cache is rebuilt in various places (e.g. during toolbox reload), but I think that should probably be called more specifically when TS repos are installed, updated or removed.

Yes, that was the intention, but IIRC (trying to find the issue/email) we needed to also rebuild the cache when reloading the toolbox because we would get a new database session, but then the ToolShedRepository objects would be disconnected from the session.

**Comment by mvdbeek** [comment]
I didn't find the actual issue, but the exception would be the same as in https://github.com/galaxyproject/galaxy/issues/3902#issue-220385473

**Comment by hexylena** [comment]
Has been patched
