### ISSUE TITLE
Slow grid / list view problems

### ISSUE THREAD

**Issue by jxtx** [galaxyproject/galaxy#5473]
Need to both improve load/render performance AND add loading indicators. 

- [ ] History list view
- [ ] Workflow list view
- [ ] All published item grids
- [ ] Probably other grids?

**Comment by jmchilton** [comment]
Tackled performance issues for history list with #5472 - though a loading indicator would be nice as a framework-wide improvement.

**Comment by martenson** [comment]
I made a Grafana dashboard for all lists API calls: https://stats.galaxyproject.org/dashboard/db/published-lists

**Comment by jmchilton** [comment]
xref https://github.com/galaxyproject/galaxy/issues/5523

**Comment by jmchilton** [comment]
For my own benefit as much as anyones - WIP on tag loading optimizations at:
 - https://github.com/galaxyproject/galaxy/pull/5538
 - https://github.com/jmchilton/galaxy/commit/5b938a13ab7b199e509e71a86d082a9007d88645

**Comment by jmchilton** [comment]
I opened a PR for loading indicators with #5582.

**Comment by martenson** [comment]
We put many optimizations in place, and we improved from superslow to slow imo. I do not think #5582 should be closing this issue.

![screenshot 2018-02-21 19 46 39](https://user-images.githubusercontent.com/1814954/36513951-19969038-1740-11e8-9e9c-35e4586695b2.png)

**Comment by jmchilton** [comment]
@martenson Feel free to re-open when the PR merge closes this. I was thinking https://github.com/galaxyproject/galaxy/pull/5576 would significantly bring that workflow list time down considerably also and was including that in the list of optimizations.

I still have WIP on tagging optimizations to speed this up - but it feels like with these optimizations in place this would no longer be such a sore spot and warrant such a high spot on the team priorities. It is fine if I was wrong about that - certainly the tagging could be vastly optimized still.

**Comment by martenson** [comment]
I propose leaving this issue open until we have data that imply higher confidence when saying 'done'. 

We do not have a hard goal for the loading times I guess, so I very much respect your approach though.

**Comment by martenson** [comment]
I think the issue closure is warrantied now, thanks @jmchilton.

![screenshot 2018-03-07 10 30 52](https://user-images.githubusercontent.com/1814954/37101088-b361c568-21f2-11e8-93a4-7bb10c529e21.png)
