### ISSUE TITLE
Authentication and authorization: OIDC and Oauth

### ISSUE THREAD

**Issue by jxtx** [galaxyproject/galaxy#5475]

**Comment by VJalili** [comment]
Consists of two parts: 

1. User authentication (and authorization), aka Authnz #4474. This leverages OpenID Connect (OIDC) protocol to identify a user on trusted identity providers (e.g., Google). In other words, a user can login to Galaxy using his/her Google account without having to create a Galaxy user. 

2. Access delegation to cloud-based resources. In other words, a user who is authenticated on a trusted identity provider (step 1) can delegate read/write access to his/her cloud-based resources (e.g., Amazon S3) _without_ sharing credentials (e.g., _access key_ and _secret key_). See [cloud-authz](https://github.com/galaxyproject/cloud-authz).

**Comment by martenson** [comment]
@VJalili during the penultimate meeting I think we called issue done. Is this ready to be closed?

**Comment by VJalili** [comment]
@martenson yes, we can close it, thanks.
