### ISSUE TITLE
Problem with assigning LDAP cert file location

### ISSUE THREAD

**Issue by ooobik** [galaxyproject/galaxy#5486]
Currently, the way to set python-ldap options is through the auth-conf.xml file, with the ldap-options param. 
Now trying to set OPT_X_TLS_CACERTFILE='/etc/ssl/certs/ca-bundle.crt' results in an interesting problem, namely in lib/galaxy/auth/providers/ldap_ad.py the \_parse_ldap_options() function checks for both key and value with the prefix OPT_ , and hence the location cannot be specified with the ldap-options param.
Here is an excerpt from the auth-config
 
```xml
<!-- LDAP-specific options -->
<server>ldaps://hostname.example</server>
<ldap-options>OPT_X_TLS_REQUIRE_CERT=OPT_X_TLS_DEMAND,OPT_X_TLS_CACERTFILE='/etc/ssl/certs/ca-bundle.crt'</ldap-options>
```
and with the location of the CA bundle not being loaded, we get the following error, since it thinks the certificate is self-signed
```
galaxy.auth.providers.ldap_ad DEBUG 2018-02-08 10:44:56,180 LDAP authenticate: Valid LDAP option pair OPT_X_TLS_REQUIRE_CERT=OPT_X_TLS_DEMAND -> 24582=2
galaxy.auth.providers.ldap_ad WARNING 2018-02-08 10:44:56,180 LDAP authenticate: Invalid parameter pair OPT_X_TLS_CACERTFILE='/etc/ssl/certs/ca-bundle.crt'. ''/etc/ssl/certs/ca-bundle.crt'' doesn't start with prefix OPT_
galaxy.auth.providers.ldap_ad ERROR 2018-02-08 10:44:56,197 LDAP authenticate: search exception
Traceback (most recent call last):
  File "/srv/galaxy/server/lib/galaxy/auth/providers/ldap_ad.py", line 131, in authenticate
    l.simple_bind_s()
  File "/srv/galaxy/server/.venv/lib/python2.7/site-packages/ldap/ldapobject.py", line 228, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/srv/galaxy/server/.venv/lib/python2.7/site-packages/ldap/ldapobject.py", line 222, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/srv/galaxy/server/.venv/lib/python2.7/site-packages/ldap/ldapobject.py", line 108, in _ldap_call
    result = func(*args,**kwargs)
SERVER_DOWN: {'info': 'error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed (self signed certificate in certificate chain)', 'desc': "Can't contact LDAP server"}
```
This is probably not the only python-ldap option whose value doesn't start with OPT_ .
As of this moment, i have not found any alternatives on specifying the ca-bundle location to python-ldap through galaxy configuration settings. I do have to note, that without TLS authentication works flawlessly

**Comment by nsoranzo** [comment]
@Alkhatraz Thanks for the detailed report! I've opened pull request https://github.com/galaxyproject/galaxy/pull/5556 to fix it, if you want to test it.
