### ISSUE TITLE
failure to convert bam_native to bam

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#5496]
I just started exploring the new bam_native datatype. I uploaded a bam file sorted by read names to the main server with its datatype declared as bam_native.
Next, I tried to use the dataset (as bam) with `NGS: Samtools Sort` with the goal to produce a coordinate-sorted bam from it. What happened though is that the job paused as the original uploaded dataset was switched to an error state because the `CONVERTER_bam_native_to_bam` failed with
```
sort: invalid option -- '@'
sort: invalid option -- 'O'
sort: invalid option -- 'T'
open: No such file or directory
[bam_sort_core] fail to open file 1
```
As a weird side effect of this, the original dataset now appears twice in my history (once in green and once in red), but that's probably a different issue.

Since this is a converter problem the same happens with any other tool that tries to use a bam_native dataset as bam, so currently bam_native datasets can only be used with tools that explicitly accept bam_native as input format.

**Comment by wm75** [comment]
Thinking about it this looks like a samtools version problem. So maybe that's related to the failing tests you saw in the original bam_native PR #5180 ?

**Comment by mvdbeek** [comment]
Yes, you'll need the samtools version that is declared in the converter. Did you use usegalaxy.org or your own server ? In the latter case you can go to the admin panel -> `Manage dependencies` and make sure you install the dependency for the converter.

**Comment by wm75** [comment]
This is on Galaxy Main.

**Comment by mvdbeek** [comment]
@natefoo @martenson can you make sure the new converters get the correct dependencies installed ?

**Comment by wm75** [comment]
a related question: how would you update a tool like the `NGS: Samtools Sort` tool so that it produces `bam_native` output when it's sorting reads by names instead of coordinates in a backwards compatible way? I guess if you just change the output format to `bam_native` when, e.g., the `-n` option is in use, any older version of Galaxy that doesn't know about `bam_native` would fail, right?

**Comment by mvdbeek** [comment]
> a related question: how would you update a tool like the NGS: Samtools Sort tool so that it produces bam_native output

I wouldn't do this at all, we need a readname sorted datatype for this. See #5497 

> the -n option is in use, any older version of Galaxy that doesn't know about bam_native would fail, right?

Actually all versions of galaxy wold fail with modern samtools, this is just hidden because the samtools sort tools does not look at the exit code:/

**Comment by mvdbeek** [comment]
> reads by names instead of coordinates in a backwards compatible way

So this is simple, we can declare `profile="18.01"` in the tool, which will prevent loading the new tool in old galaxy instances. Otherwise the datatype wouldn't be recognized and you output in the `data` format.

**Comment by wm75** [comment]
I see. An explicit readname sorted datatype really sounds like the right thing 👍
Regarding declaring `profile="18.01"`: my point is that you can keep using a read name sorted bam dataset as long as the error is hidden, _i.e._, as long as the dataset is not in an error state. So a thing like the `-n` option in the `Sort` tool is useful on older instances. So would actually have to maintain two versions of the tool then - one for 18.01+ that uses a dedicated datatype, but isn't loaded in older instances, and a legacy tool that outputs bam?

**Comment by mvdbeek** [comment]
> So would actually have to maintain two versions of the tool then - one for 18.01+ that uses a dedicated datatype, but isn't loaded in older instances, and a legacy tool that outputs bam?

That's the straightforward option, otherwise we could also deposit the datatype in a toolshed repo that you can refer to. TS datatypes will be ignored when a galaxy instance has a newer built-in datatype

**Comment by natefoo** [comment]
I've installed Samtools 1.6 on Main, please let me know if this doesn't take care of it. Prior to that it was picking up the "default" 0.1.18, around from the pre-TS (let alone pre-Conda) days.

**Comment by jennaj** [comment]
~~Upload + FTP upload now correctly autodetect and assign `bam_native` in some tests I did after Nate's changes ^^.~~

All "looks" well but is not, see next comment.

**Comment by jennaj** [comment]
Took a closer look, the FTP'd BAM is slightly larger than the browser uploaded version. It is a sorted BAM (header intact). The size is well under 2 GB. "CONVERTER_bam_native_to_bam" was used? Why is the dataset still assigned as bam_native? 

Both uploaded bams are not in a usable state by other tools. See the last two graphics below.

**Peak view FTP upload BAM**

<img width="648" alt="screen shot 2018-02-12 at 2 34 08 pm" src="https://user-images.githubusercontent.com/8999735/36123742-7b2a296c-1002-11e8-9e51-57fe0398522c.png">

**Peak view browser uploaded BAM**, note the dataset size difference and message about a truncated BAM. Doesn't seem to be truncated during actual upload. 

<img width="642" alt="screen shot 2018-02-12 at 2 33 26 pm" src="https://user-images.githubusercontent.com/8999735/36123754-87e0542e-1002-11e8-819c-cc9e4c6f0625.png">

**Some tools will start up, then pause. Some will not submit at all.** SortSam needs the text updated re: bam_native. Sort BAM fails outright on a queryname sort. We can identify the tools that have issues like this and fix as a secondary group of adjustments to work with/offer more help about the new datatype.

<img width="917" alt="screen shot 2018-02-12 at 2 53 27 pm" src="https://user-images.githubusercontent.com/8999735/36124403-b8af0be8-1004-11e8-95b5-72eea7fec8b9.png">

**Refreshing the history panel then brings up the errored convert step datasets** (are not shown when first loaded into history panel - although the primary dataset from the load will refresh through queue-executing-green (aka done) without a history panel refresh).

<img width="249" alt="screen shot 2018-02-12 at 3 02 03 pm" src="https://user-images.githubusercontent.com/8999735/36125198-e3c5e4e8-1007-11e8-9f60-a7303cfc66f9.png">

**Comment by mvdbeek** [comment]
The test datasets would be helpful, but we really need https://github.com/galaxyproject/galaxy/issues/5497 ... BamNative isn't really all that useful and we should perhaps prevent uploading those.

**Comment by mvdbeek** [comment]
> Why is the dataset still assigned as bam_native?

If you select (=force) a datatype the datatype is always being used. Regular BAM files will be sniffed to BAM if you don't force a datatype

**Comment by mvdbeek** [comment]
Also forcing to bam_native then running a tool that consumes bam works fine for me. I'd check if main doesn't do anything funny to compressed files during upload? Can you do the same thing but upload regular bam, then set (not convert!) the file to bam_native and do what you were doing before ?
If that works something is happening during upload to the file.

fwiw this all behaves as it should for me:

![screen shot 2018-02-13 at 14 48 42](https://user-images.githubusercontent.com/6804901/36153084-6ef4e346-10cd-11e8-92e1-b1e2f222d55d.png)

The yellow datatset is the implicitly converted dataset, the rest finished just fine.

**Comment by mvdbeek** [comment]
> "CONVERTER_bam_native_to_bam" was used? Why is the dataset still assigned as bam_native?

Are you looking at the right file ? The implicitly converted datasets are hidden by default and have the same HID

**Comment by jennaj** [comment]
Thanks - these BAM were uploaded using "autodetect" for the datatype. They are marked as sorted in the header. Bam_native should never be involved for these .. yet it is and is causing problems.

It does this for any BAM I load at main right now. Was your test above at main or elsewhere? I haven't tested this other places but can. Could be a server-specific issue. ping @natefoo

**Comment by mvdbeek** [comment]
> They are marked as sorted in the header

We don't trust the headers, they need to be indexable to become BAM. ~~proper BAM~~ my coordinate sorted BAM files are sniffed as BAM files, on main and on my local server.

**Comment by mvdbeek** [comment]
That said if you can share a small problematic BAM file we can figure out what's wrong with those.

**Comment by jennaj** [comment]
I am building up a test history with a few use cases. More soon & thanks for the help. We have many bug reports around bam_native/that converter. I haven't had a chance to look at all yet - the conda fixes on main made troubleshooting those difficult yesterday. More soon. It is possible the conda fixes addressed this as well!

**Comment by jennaj** [comment]
@mvdbeek After more testing (in Galaxy and samtools line-command) - it turns out that a truncated BAM dataset will be assigned to bam_native with no immediate warning that the dataset is problematic. 

Test history - data8 was purposefully truncated during FTP loading with Filezilla. data33 was loaded as bam, then had bam_native assigned after. All BAMs had a series of tools run on them to show how they pause or error. https://usegalaxy.org/u/jen/h/bam-upload

Once downstream tools fail outright, or enter a paused state, or will not launch at all, (yes, all three can occur) -- the user is still NOT alerted about why there is a problem right away. The job just queues longer. AND a history refresh does not reveal the problem, rather a downstream tool has to enter a paused state, then the hidden convert step will show up in the history (same HID, as expected). That error reports the BAM cannot be indexed because it is "probably truncated". But it is not obvious to sci users to look for new red error datasets and not all tools trigger the hidden red dataset reveal (some won't even accept the input at submit and instead present with a red message on the tool form that the input is in an unusable state - nothing about a truncated input/missing index).

**If a BAM dataset is truncated and not usable (cannot be indexed), that should be made clear to the user in the GUI at upload** or we'll be getting odd reported problems. Downstream tools don't deal with this non-indexed-bam-dataset-state consistently. 

Catching the problem at the start avoids those downstream problems. Could we consider handling this use-case with an error? **Specifically, if a BAM dataset is truncated or cannot be indexed, that should result in a red failed upload dataset**, instead of a green dataset that appears usable, with bam_native assigned as a datatype, and an initially hidden error dataset, same HID. 

Thoughts?

**Comment by mvdbeek** [comment]
> data33 was loaded as bam, then had bam_native assigned after.

So that's a good example, this failed in the converter because on large files samtools writes to stderr
(`[bam_sort_core] merging from 4 files and 1 in-memory blocks...`). That should be fixed by https://github.com/galaxyproject/galaxy/pull/5532.

> Once downstream tools fail outright, or enter a paused state, or will not launch at all, (yes, all three can occur) -- the user is still NOT alerted about why there is a problem right away. The job just queues longer. AND a history refresh does not reveal the problem, rather a downstream tool has to enter a paused state, then the hidden convert step will show up in the history (same HID, as expected).

That is how galaxy visualises queued, hidden jobs, I'm not sure there's a better way. It's not related to the new datatypes, I would say.

> If a BAM dataset is truncated and not usable (cannot be indexed), that should be made clear to the user in the GUI at upload or we'll be getting odd reported problems.

I'll see what I can do, it's possible that we may need to just disable sniffing for bam_native if checking for this would require sorting (since then you might as well sort to BAM in the first place)

**Comment by jennaj** [comment]
Agree - uploading all BAMs as `bam` (coordinate sort) would avoid the issues. Can always queryname sort after and have the sort tools assign `bam_native` or optionally output `sam` or the new datatype people have been discussing to designate that sort order in bam. 

One of our sort tools already outputs sam only for queryname, the other produces an unusable bam. I was waiting to ticket all that until we decided if queryname sorted bams would get a new datatype.

**Comment by natefoo** [comment]
If I understand correctly, everything is ok on Main now?

**Comment by jennaj** [comment]
Not quite there yet but closer. More comments are at gitter > committers so we can discuss what to do. https://gitter.im/galaxyproject/committers?at=5a860a28c0c10af4538b97c9 @natefoo

**Comment by mvdbeek** [comment]
I think we solved all of this, if not feel free to reopen.
