### ISSUE TITLE
Lefse and Picrust troubles to run

### ISSUE THREAD

**Issue by SPotgens** [galaxyproject/galaxy#5503]
Hi, we have used Lefse and Picrust plenty of times in the pasr but for our last analysis we fail to load the files and to run the different steps. We know it is not a problem of format but well a loading problem (it takes a long time to finally fail). We have tried to use it at various time of the day on several days for 3 weeks now but it never went well.
Could you please indicate me how to do to perform my analyses?
Thanks a lot for your help!

**Comment by nsoranzo** [comment]
@SPotgens On which server are you experiencing this issue?

**Comment by SPotgens** [comment]
I use this URL : http://huttenhower.sph.harvard.edu/galaxy/

**Comment by nsoranzo** [comment]
@SPotgens Unfortunately we cannot help, since we don't manage this server, but you can contact the maintainers at http://huttenhower.sph.harvard.edu/contact
