### ISSUE TITLE
tests do not clean after themselves

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5509]
They build client now, but leave all the new (dev) artifacts behind.

**Comment by jmchilton** [comment]
This is only if you are using the CI script right?

I checked the Jenkins server and the files seem to have the correct permissions - so this doesn't cause tests to fail right or problems with Jenkins being able to clean up after itself?

I'm fine if you'd like to just maintain a clean local working directory - I'm just trying to understand the scope of the problem. I'm sure there is some git foo we could employ to remove untracked files from static - but that would only work if Galaxy is obtained via Git - probably would be enough though?

**Comment by martenson** [comment]
I observed this locally after running unit tests. Re-running now to confirm.

**Comment by martenson** [comment]
I am unable to reproduce what I reported, I must have done something weird then. Sorry for the nooise. Closing.
