### ISSUE TITLE
Background Queue for Dataset Purging

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5520]
Purging on usegalaxy.org seems to take a while - disk operations like this should happen in the background and not in web requests if possible. We should quickly mark the dataset deleted and then use a message queue of some kind to really purge the dataset I think.

I've been thinking about batching up deletion operations in the history panel (#5472 , #5495) - and to me it makes some good sense for just marking a dataset deleted - but for purging I'm concerned it will bog everything down waiting for the request and the more responsive user experience is the current one until such a time as we have background dataset purging implemented.

If we had robust message queuing in place out of the box this would hopefully be easy but I don't think we do yet.

**Comment by martenson** [comment]
the timings for the datasets purge webcontroller calls: https://stats.galaxyproject.org/dashboard/db/published-lists?panelId=14&fullscreen

**Comment by martenson** [comment]
sloreq logs: https://sentry.galaxyproject.org/sentry/main/issues/288707/

**Comment by mvdbeek** [comment]
I think we could do a simple version of this using `send_local_control_task`, but maybe that's a good usecase for implementing a `SimpleQueue` or `SimpleBuffer` using kombu, which should work fine for most/all deployment scenarios after #7548

**Comment by mvdbeek** [comment]
I've added a task to purge datasets here: https://github.com/galaxyproject/galaxy/pull/11720/commits/012a8e1ea6a628bad313ccedf5789e1f1c11c65b

We could add a second task for batch deletion of histories / many datasets, but this is a start
