### ISSUE TITLE
Bug reporting seems to fail

### ISSUE THREAD

**Issue by cganote** [galaxyproject/galaxy#5524]
I've noticed an issue with bug reporting in Galaxy release 17.09 that I'm not sure is due to my local settings. When poking at it with chrome, I see the following:
dataset-error.js:152 Uncaught TypeError: e.messages.forEach is not a function

at Object.success (dataset-error.js:152)

at l (jquery.js:3232)

at Object.fireWith [as resolveWith] (jquery.js:3362)

at n (jquery.js:9840)

at XMLHttpRequest.e (jquery.js:10311)

No mail gets sent, the UI is blank, and I added some log lines to util__inity.py in the send mail function that never print. Anything I can do here?

**Comment by martenson** [comment]
Do you have any report-specific config in place? Can you add a screenshot of the UI please?

**Comment by cganote** [comment]
I have some things in galaxy.ini:
smtp_server = localhost
error_email_to = help@ncgas.org

I tried changing around the smtp_server, and adding smtp_ssl = True just in case. No change in behavior though.

Here's a screenshot of the report:
![image](https://user-images.githubusercontent.com/5487606/36173249-565494c2-10d6-11e8-8bd7-3e5ef5f1caf6.png)
After I click on Report:
![image](https://user-images.githubusercontent.com/5487606/36173307-945ad54c-10d6-11e8-885e-66004835703b.png)

**Comment by martenson** [comment]
Interesting. Did it work for you before, or was it always broken for you on 17.09?

**Comment by cganote** [comment]
I'm not sure! I think this might be the first time I tried on 17.09, since we moved to it in December.

**Comment by martenson** [comment]
@cganote is this still happening for you? If so can you please give me the exact changeset you are at?

**Comment by hexylena** [comment]
Closing pending more information
