### ISSUE TITLE
GenomeSpace importer/exporter broken on Galaxy 18.01

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/galaxy#5527]
Currently, the tool is broken on Galaxy main and I received a bug report from Ted Liefeld which I'm in turn reporting here.

The issue appears to have been caused by some client related revisions made recently.

**Comment by jennaj** [comment]
Let's leave this open until https://usegalaxy.org get updated with the final fix. I am sharing this with users of that server so they can follow for updates. Thx!
