### ISSUE TITLE
When installing ncbi_blast_plus from shed it does not complete

### ISSUE THREAD

**Issue by enuggetry** [galaxyproject/galaxy#5529]
Usually when attempting to install ncbi_blast_plus from the toolshed, it does not complete installing the dependencies.  I usually have to repeat the process, some times 2-3 times before all dependencies get installed.

![ice_screenshot_20180213-234102](https://user-images.githubusercontent.com/10053377/36192753-d30a8e54-1117-11e8-9321-c712cac9b319.png)

**Comment by bernt-matthias** [comment]
The installed package_... indicates that the requirement is resolved the old way. With recent Galaxy releases you should use conda. In order to know what exactly is going on the (relevant part of the) log would be useful.

**Comment by hexylena** [comment]
Fixed with conda
