### ISSUE TITLE
Upload offloading without the nginx upload module

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#5536]
Maintaining nginx packages to include it is a bit of a pain, the module is barely maintained, and it appears to break http/2. Ideally the alternative would be supported on Apache as well. The most important feature needed is the ability to restart Galaxy without breaking in-progress uploads. Performance is a secondary benefit.

Chunking (#573, #5516) partially fixes this since it would add retry support. But keeping it external to Galaxy still has additional benefits.

One possibility would be to find (if one exists) or write a very simple server that largely does what the upload module does, that we could launch independently of Galaxy. Non-chunked uploads wouldn't survive the restart of that server, but it shouldn't need to be restarted often.

Some nginx-only solutions (maybe similar features exist in Apache, I have not looked):

- https://github.com/ardinusawan/Nginx-direct-file-upload-without-passing-them-through-backend/blob/master/README.md
- https://stackoverflow.com/questions/44371643/nginx-php-failing-with-large-file-uploads-over-6-gb/44751210#44751210
- https://scribie.com/blog/2014/09/chunked-upload-with-nginx-and-nodejs/

Even if we don't come up with a non-nginx solution, it'd still be good to switch to the `client_body_in_file_only` method above (assuming it works well) so we can stop messing with nginx packaging for the upload module.

**Comment by nsoranzo** [comment]
Do this need to be updated now that chunked uploads are in production?

**Comment by natefoo** [comment]
Yeah. I think the upload module is still going to break http/2 though, unfortunately. Unless we can redirect uploads to a subdomain, or put some work in to the upload module (if it would even be possible to support) I think we still need to address this.

**Comment by mvdbeek** [comment]
That's done with https://github.com/galaxyproject/galaxy/pull/12656
