### ISSUE TITLE
data and citations

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5543]
Currently only tools have citations, but often also data sets are associated with publications. This is currently not reflected in Galaxy. 

Maybe data_managers can be extended to include citations?

**Comment by jmchilton** [comment]
Dataset level citations are included on a citation roadmap I threw together here https://github.com/galaxyproject/galaxy/issues/5165. We need it, it would be tremendously helpful I think, not sure how to find the time to do it though.

**Comment by bernt-matthias** [comment]
Good, then this is (kind of) covered.
