### ISSUE TITLE
Missing wheels for 18.01

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#5546]
Packages which are built when Galaxy creates its virtualenv:

- [x] MarkupSafe 1.0 https://github.com/galaxyproject/starforge/pull/192
- [x] PyYAML 3.12 https://github.com/galaxyproject/starforge/pull/192
- [x] SQLAlchemy-Utils 0.32.19 https://github.com/galaxyproject/starforge/pull/177
- [x] repoze.lru 0.6 (there is a wheel https://wheels.galaxyproject.org/simple/repoze.lru/ , but pip try to get it from https://wheels.galaxyproject.org/simple/repoze-lru/ , i.e. replacing the dot with a hyphen. We should rename the directory on wheels.galaxyproject.org)
- [x] docopt 0.6.2 https://github.com/galaxyproject/starforge/pull/194
- [x] pycparser 2.18 https://github.com/galaxyproject/starforge/pull/177
- [x] python-genomespaceclient 0.1.8 https://github.com/galaxyproject/starforge/pull/177

**Comment by nsoranzo** [comment]
Ping @natefoo for `repoze.lru`, here's the log for what I've described above:
```console
$ rm -rf .cache/pip
$ pip install -v --index-url https://wheels.galaxyproject.org/simple repoze.lru==0.6
Collecting repoze.lru==0.6
  1 location(s) to search for versions of repoze.lru:
  * https://wheels.galaxyproject.org/simple/repoze-lru/
  Getting page https://wheels.galaxyproject.org/simple/repoze-lru/
  Looking up "https://wheels.galaxyproject.org/simple/repoze-lru/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): wheels.galaxyproject.org
  "GET /simple/repoze-lru/ HTTP/1.1" 302 0
  Status code 302 not in [200, 203, 300, 301]
  Looking up "https://pypi.python.org/simple/repoze-lru/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/repoze-lru/ HTTP/1.1" 200 737
  Updating cache with response from "https://pypi.python.org/simple/repoze-lru/"
  Caching b/c date exists and max-age > 0
  Analyzing links from page https://pypi.python.org/simple/repoze-lru/
...
```

**Comment by natefoo** [comment]
- MarkupSafe, PyYAML, and docopt are published to wheels.galaxyproject.org
- I've upgraded pypiserver on wheels.galaxyproject.org to 1.1.10 which includes a fix for the package name normalization issue with repoze.lru.

**Comment by nsoranzo** [comment]
Thanks @natefoo! I've added pycparser to the list, which was missing:
```
Collecting pycparser (from cffi>=1.4.1->pynacl>=1.0.1->paramiko==2.2.1->-r requirements.txt (line 87))
  Downloading pycparser-2.18.tar.gz (245kB)
...
  Running setup.py bdist_wheel for pycparser ... done
```

**Comment by martenson** [comment]
All wheels ready for the ride!
