### ISSUE TITLE
Cache Datatypes and Genomes?

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5547]
These two calls:

```
GET /api/datatypes?extension_only=False
GET /api/genomes
```

are made frequently but the results should probably rarely change. Maybe add a checksum Galaxy computes on load or each time the underlying data is updated and then allow the client to cache on that checksum and store the values in web storage?

**Comment by jmchilton** [comment]
Maybe not worth it - but I wanted to track the work somewhere - here is a backend optimization for the datatypes query https://github.com/jmchilton/galaxy/commit/bd037b85fe213be09de50ba11f09c039dea74b22. Rebuilds the whole raw response and caches it every time the datatypes change. Eliminates some unneeded null fields to reduce the size of the response as well.

**Comment by jmchilton** [comment]
Note from Martin on Gitter:

```
I think we have soft cache in place at majority of the datatypes and genomes fetches already
it does not persist to local storage though afaik
so hard load and you ahve nothing
(and we still do hard load often because we are not SPA yet)
https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/utils/utils.js#L118
```

**Comment by hexylena** [comment]
- xref #4571
- checksums → would be nice to send ETags if we could provide that checksum in the response

**Comment by hexylena** [comment]
https://github.com/galaxyproject/galaxy/issues/8117#issuecomment-499930838 there marius describes doing this in the proxy level which I think makes a lot of sense, those are easily cached by a proxy, might make more sense to leave the code simpler and cache at a higher level?
