### ISSUE TITLE
update docker fork to latest version

### ISSUE THREAD

**Issue by matthdsm** [galaxyproject/galaxy#555]
Hi

Are there any plans to update the fork that is used for galaxy-in-docker to version 15.07?
We are planning to deploy Galaxy in the coming weeks and would like to start of with the latest release.

Thanks!
Matthias

**Comment by bgruening** [comment]
@matthdsm as far as I know 15.07 is not released. There are still a few bugs that needs to be fixed.
We usually try hard to release a new version of the Galaxy Docker Image a few days after a regular Galaxy release.

Hope this answers your question.
Bjoern

**Comment by bgruening** [comment]
@matthdsm if have pinned the next Docker Image to the release_15.07 branch. https://github.com/bgruening/docker-galaxy-stable/commit/bf7f067e568bfcac0561829d21185646c3167537

If you check out `brgruening/galaxy-stable:dev` in a few hours you will have an image which will become the next Galaxy Docker Image. Testing appreciated.

`docker pull brgruening/galaxy-stable:dev`

**Comment by matthdsm** [comment]
Thanks! I’ll check it out!

Matthias

Op 5-aug.-2015, om 15:35 heeft Björn Grüning <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

@matthdsmhttps://github.com/matthdsm if have pinned the next Docker Image to the release_15.07 branch. bgruening/docker-galaxy-stable@bf7f067https://github.com/bgruening/docker-galaxy-stable/commit/bf7f067e568bfcac0561829d21185646c3167537

If you check out brgruening/galaxy-stable:dev in a few hours you will have an image which will become the next Galaxy Docker Image. Testing appreciated.

docker pull brgruening/galaxy-stable:dev

**Comment by jmchilton** [comment]
This seems solved so closing this now. Probably best to create the issue at https://github.com/bgruening/docker-galaxy-stable anyway.
