### ISSUE TITLE
optimize the main page loading process

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5563]
Currently on Main every load of the root analysis page is delayed by ~2s because that is how long it takes us to deliver root/index to even start fetching other things.

![screenshot 2018-02-19 13 51 45](https://user-images.githubusercontent.com/1814954/36393073-0c17348c-157c-11e8-9571-476e79032d2b.png)

I suspect that at least a part of this is that we fetch the whole tool panel as part of the json `app` dump which results in 42k lines / 2mil characters of 'configuration' in that html. 

We should probably deliver the first html with basic configuration ASAP and let other things load in an async manner.

**Comment by martenson** [comment]
We also seem to be including the toolpanel config literally **twice** https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/controllers/root.py#L58

**Comment by dannon** [comment]
We dicsussed improvements for this a few months back, but much of it depended on the refactoring and architecture improvements going on.  I can't find an issue for it, though.  @guerler, do you remember this?

It's definitely the plan, though, to strip the initial client shipment to the bare minimum and progressively load details like the toolbox, etc.

**Comment by hexylena** [comment]
![auswahl_320](https://user-images.githubusercontent.com/458683/36416957-88c21258-1622-11e8-96ef-2bd733d39734.png)

We recently started running a [subdomain](https://hicexplorer.usegalaxy.eu) with a limited toolbox, the full toolbox adds somewhere between .75 and 3 seconds to the load time (but it's pretty variable.) [Here's the graph](https://stats.usegalaxy.eu/dashboard/db/nagios?orgId=1&from=now-3h&to=now).

**Comment by martenson** [comment]
with #5570 in place

![screenshot 2018-02-20 20 11 00](https://user-images.githubusercontent.com/1814954/36458229-c80fe6fc-167b-11e8-872d-70bd4d6b1af0.png)

**Comment by guerler** [comment]
This is fantastic @martenson. Particularly considering the large number of tools and many page reloads we still have on main. Never experienced the left tool panel box as critical in local tests (which is not surprising). Shows that its even more important that we quickly create a large test sqllite db for local tests.

**Comment by hexylena** [comment]
<3 can't wait til this supports our filters.

**Comment by martenson** [comment]
I think we improved this a lot with https://github.com/galaxyproject/galaxy/pull/5616 and related PRs

https://twitter.com/martenson/status/969596617581125632
