### ISSUE TITLE
Selection of tool version in workflow editor

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#557]
After installing multiple versions of a tool, it is not possible to select old versions when adding it as a step in the workflow editor

From @nsoranzo on [trello](https://trello.com/c/d7B3XHCR/1270-after-installing-multiple-versions-of-a-tool-it-is-not-possible-to-select-old-versions-when-adding-it-as-a-step-in-the-workflow-)

**Comment by nsoranzo** [comment]
:+1:

**Comment by mvdbeek** [comment]
:+1:

**Comment by bwlang** [comment]
maybe related... sometimes the most recent version is not selected (e.g. cutadapt 1.1.a is selected by default, not 1.6 when both are installed)

**Comment by remimarenco** [comment]
👍

**Comment by nsoranzo** [comment]
Maybe of interest for @guerler.

**Comment by RJMW** [comment]
:+1:

**Comment by bgruening** [comment]
@mvdbeek you are the best!
