### ISSUE TITLE
Viewing BAMs shows repeated content

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#5577]
Viewing certain BAM files (eye icon) shows incorrect contents.
Possible cause here is a very small BAM (4 line header only). It will continue to load and show the same 4 lines, repeating infinitely, as you scroll down.

Example history: https://usegalaxy.org/u/dan/h/bad-bam-view

![image](https://user-images.githubusercontent.com/1231190/36485535-7b1f6aa6-16ea-11e8-9137-91e896db4bc7.png)

**Comment by dannon** [comment]
@blankenberg Thanks for the report, should have a fix in a sec.

**Comment by dannon** [comment]
Fixed in #5579
