### ISSUE TITLE
Upgrading tools within workflows

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#558]
An issue that I run into quite often is the need to update workflows to use new versions of tools. Without the ability to update the version of a tool, this is very tedious as I have to add the new tool and manually "move" over all of the parameters, output renaming, annotations, etc. which is very tedious and error prone.

related to #523 #557 

from @lparsons on [trello](https://trello.com/c/d7B3XHCR/1270-after-installing-multiple-versions-of-a-tool-it-is-not-possible-to-select-old-versions-when-adding-it-as-a-step-in-the-workflow-)

**Comment by chambm** [comment]
:+1: Especially problematic when developing tools and rapidly iterating.

**Comment by guerler** [comment]
Fixed with #4373.
