### ISSUE TITLE
Help icon for history datasets should load help into center panel

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#5586]
Clicking on the question/help icon of a history datasets, expands the help text into the history panel. Its difficult to scroll and read, additionally images are only partially visible.

**Comment by dannon** [comment]
@guerler Totally agreed; I think there may be an issue for this already though?

Edit:  Yep, https://github.com/galaxyproject/galaxy/issues/4028

**Comment by guerler** [comment]
Ah I see. Cool.
