### ISSUE TITLE
Tool form Multi-select parameter problem

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#5599]
I'm running the tip of the dev branch, and I've seen an issue with the Select parameter on tool forms when multiple="true" is used.  Here is my parameter definition.
```
            <param name="life_stages" type="select" multiple="true" label="Select life stages for plotting">
                <option value="All" selected="true">All</option>
                <option value="Egg">Egg</option>
                <option value="Nymph">Nymph</option>
                <option value="Adult">Adult</option>
            </param>
```
Selecting a single option works fine, but any multiple selection results in this exception.
<img width="883" alt="multi_select" src="https://user-images.githubusercontent.com/6947053/36609475-ec0a8d34-189a-11e8-8339-a3806534492d.png">

The initial display also seems a bit confusing to me since the user has to know to click the ```Select/Unselect all``` icon twice to display the multiple options.  
<img width="886" alt="multi_select" src="https://user-images.githubusercontent.com/6947053/36609563-487376d0-189b-11e8-97ee-a56557a38b84.png">

The fist click clears the select list, and the second click displays the multiple options from which the user then unselects some.
<img width="889" alt="multi_select" src="https://user-images.githubusercontent.com/6947053/36609644-919205b6-189b-11e8-9a09-de8879031099.png">

I'm not sure how this particular multi-select displays with a large number of options.  Is this a more modern multi-select?  Maybe I'm just used to the old list that pops up that doesn't use new buttons.

**Comment by martenson** [comment]
I talked with @gregvonkuster about the usability issue and think that is now clear. We might want to provide a hint in this case for people that are not used to select2 UX - which might be fairly large group.

The validation bug also looks valid.

**Comment by gregvonkuster** [comment]
Thanks for the help on this @martenson ;)

**Comment by martenson** [comment]
So I tested this locally on dev with the xml code @gregvonkuster pasted above, and I am not running into the validation issue. Could you please share the whole tool?

**Comment by gregvonkuster** [comment]
The tools ia available for install from the TS here: https://toolshed.g2.bx.psu.edu/view/greg/insect_phenology_model/bd5e35775e20.  The GitHub repo is here: https://github.com/gregvonkuster/galaxy_tools/tree/master/tools/entomology/insect_phenology_model

In both cases, I do not have multiple="true" set for the following select list, so if you install it, you have to add that attribute to the param tag.
```
            <param name="life_stages" type="select" label="Select life stages for plotting">
                <option value="Total" selected="true">All</option>
                <option value="Egg">Egg</option>
                <option value="Nymph">Nymph</option>
                <option value="Adult">Adult</option>
            </param>
```

**Comment by gregvonkuster** [comment]
It's strange that you're not seeing it.  I'm running this rev of the dev branch.
```
commit f354b9d3f589e41020766968fe5827e99fd97c9d
Merge: 6d94009 d937273
Author: Nicola Soranzo <nicola.soranzo@earlham.ac.uk>
Date:   Thu Feb 22 15:26:30 2018 +0000

    Merge branch 'release_18.01' into dev
```

**Comment by gregvonkuster** [comment]
Hmm...maybe because in my case, the select list is a conditional param?
```
<conditional name="life_stages_cond" label="Select life_stages for plotting">
    <param name="life_stages" type="select" label="Select life stages for plotting">
        <option value="Total" selected="true">All</option>
        <option value="Egg">Egg</option>
        <option value="Nymph">Nymph</option
        <option value="Adult">Adult</option>
    </param>
...
```

**Comment by martenson** [comment]
in a conditional the validation fails for me too

**Comment by martenson** [comment]
Looking at https://github.com/gregvonkuster/galaxy_tools/blob/master/tools/entomology/insect_phenology_model/insect_phenology_model.xml#L69 I think I understand what you are trying to do, but I am afraid that is not supported. 

Do you think you could replace the multiselect with boolean switch for each value? Then it would work with conditionals.

**Comment by gregvonkuster** [comment]
Yeah, after thinking about this, I realized as well that multi-selects in conditionals were probably not supported.  Sorry about the time you spent.  I'll take a look at another way to get the behavior I need for this.  Thanks @martenson ;)
