### ISSUE TITLE
Rename PostJobAction not working on 'resume job dependencies'

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#560]
If a workflow has one or more 'rename postjobactions' and the run fails, rerunning the failed tool with 'resume job dependencies' will not run the rename actions (or perhaps with wrong values). Unfortunately, for some of our workflows the renaming action is essential.

from @scholtalbers on [trello](https://trello.com/c/BiisIQnJ/2656-rename-postjobaction-not-working-on-resume-job-dependencies)

**Comment by dannon** [comment]
@scholtalbers and I looked at this during the GCC Hackathon.  When the remap processing happens creating the new jobs, it doesn't copy the PJAs, and it needs to (or just reassign them).

**Comment by dannon** [comment]
Should be resolved with #730
