### ISSUE TITLE
server_name templating and mangling issues

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#5601]
With the new uWSGI features it was necessary to do more intensive post-fork `server_name` mangling. In addition, with multiple ways to start the server (Paste w/ PasteDeploy, uWSGI w/ PasteDeploy, plain uWSGI, and webless `scripts/galaxy-main`), there are multiple different ways to set the base value of `server_name` pre-fork (which is needed for things like job handlers).

Complicating this is the fact that the default `server_name` under PasteDeploy is `main`, whereas under uWSGI with the YAML config files, it's the app name, which is the key to the config dict, i.e. `galaxy`.

My intent was to make it possible to configure a base `server_name` in `galaxy.{ini,yml}`, for that to be templated with `galaxy.util.facts`, and for it to be overrideable e.g. with `paster.py --server-name=` or `scripts/galaxy-main --server-name=` etc. It appears these have not all worked as intended and so they need to be revisited.

I discovered this in the course of figuring out how some of the uWSGI workers on my front end VM 1 were receiving `rebuild_toolbox_search_index` async tasks via the message queue before they had themselves reloaded the toolbox and queued the task; it's because the workers on VM 2 had already done it, 2's workers had queued the tasks, and because they *both* have workers with `server_name`s of `main.web.{0..7}`, 1 was picking up those tasks that 2 had intended for itself. So it should be documented somewhere that `server_name` will need to include a hostname-unique element if you use the same internal message queue with multiple hosts. Alternatively, we can automatically include some kind of host identifier when those exchanges are set up. Thoughts @dannon?

Milestoned to 18.01 because we need to get a fix in 18.01, but it's a bug, so that's fine - this should *not* block release.

**Comment by martenson** [comment]
amongst the things that this causes is unreliable search response since some workers may have outdated search index

**Comment by martenson** [comment]
pushed to 18.09

**Comment by martenson** [comment]
Pushing to 19.05

**Comment by natefoo** [comment]
#7712 will fix the specific problem I described with overlapping `server_names` on multiple VMs, but I'm not sure exactly what I was referring to when I said:

> It appears these have not all worked as intended and so they need to be revisited.

I think there's still a bug with one of the multitude of ways you can specify `server_name`, but I don't recall the specifics, so until it pops up again, #7712 can close this issue. I'll probably try to find it again whenever I get to #7289 .

**Comment by mvdbeek** [comment]
I've cleared the milestone in case you'll want to revisit the actual server name config.
