### ISSUE TITLE
[Feature Request]: A better view for "View All Histories"

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/galaxy#5614]
When I go to view all histories: 

<img width="95" alt="screen shot 2018-02-27 at 1 09 37 pm" src="https://user-images.githubusercontent.com/2761597/36746121-81aac65c-1bbf-11e8-9bdf-894789fda999.png">

I get a view with all the histories side-by-side. If I have 20+ histories, this already can be kind of onerous. What if there were an option to view a list of histories? The could be [accordions](https://getbootstrap.com/docs/4.0/components/collapse/#accordion-example) or even just using the  data library UI as a first pass would be nice.

**Comment by martenson** [comment]
Have you seen https://usegalaxy.org/histories/list ?

**Comment by alexlenail** [comment]
@martenson I had not seen /histories/list. When was it added? I'm running 17.05 and that page won't load on my galaxy...

**Comment by martenson** [comment]
That page has always been there, it is the target of 'Saved histories' link from the history menu (or also from the user top menu)

**Comment by alexlenail** [comment]
@martenson I see. The /histories/list endpoint doesn't work for me, but navigating to User > Saved Histories does. This feature looks good enough to me for the time being, so I'll close the issue. Thanks!
