### ISSUE TITLE
As admin, how to delete and purge all users hisrories and datesets?

### ISSUE THREAD

**Issue by shenweiyan** [galaxyproject/galaxy#5649]
For my local galaxy，I want to delete and purge all users hisrories and datesets. As admin, I can't see any options in admin web panel.

**Comment by martenson** [comment]
Do you want to wipe the whole Galaxy (all users) or just your account?

**Comment by shenweiyan** [comment]
I want to wipe the whole Galaxy (all users) hisrories and datesets.

**Comment by martenson** [comment]
@istevenshen The easiest way may be to do a full wipe and just instal a new Galaxy. If you want to preserve the users or such then you can mark all datasets in the DB as 'deleted' and then use the following scripts to clean up: https://github.com/galaxyproject/galaxy/tree/dev/scripts/cleanup_datasets

You can learn more from this slide deck: https://galaxyproject.github.io/dagobah-training/2018-oslo/19-storage/storage.html#1
