### ISSUE TITLE
job splitting bug when jobs are resubmitted and run as real user 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5654]
I was experimenting with job splitting for blastp (since multi threading seems to be quite unperformant). 

The jobs hit the run time limit and were resubmitted which caused the following exception:

```
galaxy.jobs.runners.tasks ERROR 2018-03-07 15:33:16,694 failure running job 3280
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/runners/tasks.py", line 59, in queue_job
    tasks = splitter.do_split(job_wrapper)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/splitters/multi.py", line 90, in do_split
    input_type.split(input_datasets, get_new_working_directory_name, parallel_settings)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/datatypes/sequence.py", line 437, in split
    cls._count_split(input_file, batch_size, subdir_generator_function)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/datatypes/sequence.py", line 492, in _count_split
    part_file = open(part_path, 'w')
IOError: [Errno 13] Permission denied: '/work/songalax/galaxy-dev/database/jobs_directory/003/3280/task_0/dataset_5676.dat'
```

I guess galaxy tries to split the data again before restarting the jobs. But the job dir still belongs to the real user.

**Comment by hexylena** [comment]
I guess job splitting isn't really well supported/encouraged? So bugs may be expected with configurations like this :/ I'm not sure anyone will work on them soon. I'm assuming in intervening year you've probably either found a workaround or given up?

**Comment by bernt-matthias** [comment]
Given up :) 

I guess collections are often the way to go. More generic anyway, since splitting only was implemented for a few data types. 

Just started recently to experiment with the tool `Split file to dataset collection`. 

Lets close it for now.
