### ISSUE TITLE
Add select all button to admin/manage_tool_dependencies

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#5656]
Moved a server between different architectures and needed to reinstall dependencies, a select all button would be super helpful here.

Workaround is to open console in web browser and enter:
`$(':checkbox').prop('checked', true);`

**Comment by mvdbeek** [comment]
Also we should submit via payload instead of query parameters, that's also limiting.

**Comment by blankenberg** [comment]
Agreed, for now if using uwsgi, can set buffer-size to workaround that in some cases: https://github.com/galaxyproject/galaxy/pull/5658

**Comment by martenson** [comment]
we have the checkbox for select all now!
