### ISSUE TITLE
Feature request: greyout conditional outputs in workflow editor

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#5661]
Some tools have conditional outputs, however all are displayed (with for users cryptic names). It would help a lot to hide/greyout outputs that will not be generated. Currently workflow steps on non generated outputs will just silently be ignored and the user has to guess what was wrong. A particular example is [FeatureCounts](https://github.com/galaxyproject/tools-iuc/blob/master/tools/featurecounts/featurecounts.xml), where 4 different output formats can be selected - resulting in >4 selectable outputs in the workflow editor: 

<img width="753" alt="screen shot 2018-03-08 at 10 59 45" src="https://user-images.githubusercontent.com/102411/37144961-dc530068-22bf-11e8-9eb6-0ac47af9a7d8.png">

**Comment by hexylena** [comment]
xref my original https://github.com/galaxyproject/galaxy/issues/1418 and your bug report that looks like it as well https://github.com/galaxyproject/galaxy/issues/5322

**Comment by scholtalbers** [comment]
@erasche thanks for making those connections! (sometimes one uses the wrong search terms to locate duplicate issues :))

**Comment by hexylena** [comment]
No problem! I knew I'd filed a similar issue but couldn't find it under the same search terms either, ended up going through all issues I'd filed. I should've used 'conditional', like, anywhere in the text. I end up commenting on that issue every time it happens to me which is starting to be a lot...

**Comment by hexylena** [comment]
The eventual workflow scheduling error also shows up as a bug report in sentry. E.g.https://sentry.denbi.uni-freiburg.de/share/issue/47ca0a18767a44bda21dfb057b101126/ This is pretty annoying as it is a user-facing error rather than something a sysadmin should see. Whenever we fix this/1418/5322 we should be sure that that exception is caught and displayed to the user rather than logged in sentry. I've got 300 events for this error, surely main has even more.

**Comment by mvdbeek** [comment]
We're now (tip of 19.01) filtering out outputs that aren't going to be produced in the workflow editor, so while you can still run into this with old workflows it should be harder to create broken workflows now. If a workflow doesn't run now you can open them up in the workflow editor and check that all steps are properly connected. The plan is still to prevent submission of these workflows, at which point we could actually grey out conditional outputs but still offer to connect outputs that are conditional, for workflows that are intentionally designed to have these optional branches of execution.
Thanks a lot for reporting this @scholtalbers and @erasche, I hope this will cause much less pain now.
