### ISSUE TITLE
Workflow Editor tool search box missing clear / closing X

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#5671]
and escape key doesn't work

in workflow editor:
![image](https://user-images.githubusercontent.com/1231190/37227818-8428acd8-23ac-11e8-8a89-301e1067e7fc.png)

vs analysis:

![image](https://user-images.githubusercontent.com/1231190/37227886-b3c49ab0-23ac-11e8-9525-2a990d144418.png)

**Comment by dannon** [comment]
Fixed in #6290
