### ISSUE TITLE
improve performance of api/workflows index

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5673]
It works well if you have no/little workflows (doh), but it gets increasingly annoying the more you have.

![screenshot 2018-03-12 10 16 39](https://user-images.githubusercontent.com/1814954/37288806-90d66f5e-25de-11e8-9da5-3d4fd339b6f4.png)

**Comment by martenson** [comment]
according to Sentry around 300 of Main's users are experiencing >1s for this call.

**Comment by blankenberg** [comment]
Takes around 2 minutes for me, and I don't even have that many workflows on main. 

A loading indicator in the gui would be helpful as well, since it just looks like it is broken and that I have no workflows while the API call is running in the background.

**Comment by dannon** [comment]
The API endpoint (which the graph above shows) can/should definitely be worked on.  The clientside responsiveness/indicators will happen as a part of the bootstrap-vue rewrite of the list in this next release cycle.

**Comment by martenson** [comment]
@blankenberg How many is not many? Are they big?

**Comment by jmchilton** [comment]
They query really shouldn't be bad, maybe we are missing an index somewhere. I can try to take another pass at this soonish.

**Comment by jmchilton** [comment]
WIP at https://github.com/galaxyproject/galaxy/pull/5755
