### ISSUE TITLE
Trackster Performance, cannot add track

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#5712]
On main, trying to add a dataset to trackster, it just hangs for many minutes.  

`https://usegalaxy.org/visualization/list_history_datasets?f-dbkey=mm10` is the stalled URL. 

Possibly enabling some smart paging / lazy loading will help?

**Comment by dannon** [comment]
@blankenberg No error in the JS console, just a stalled fetch, right?

**Comment by blankenberg** [comment]
Looks to be related to a specific issue with usegalaxy.org ATM.
