### ISSUE TITLE
cleanup_datasets with No module named galaxy.app error

### ISSUE THREAD

**Issue by shenweiyan** [galaxyproject/galaxy#5722]
In running a local instance of galaxy release-17.09 on my Cenos-7.4，I got some errors when I want to cleanup datasets.

```
$ cd <GALAXY_ROOT> 

$ . .venv/bin/activate

(.venv)steven@ecs-steven-dev 15:53:23 /data/galaxy 
$ python ./scripts/cleanup_datasets/update_dataset_size.py 
Traceback (most recent call last):
  File "./scripts/cleanup_datasets/update_dataset_size.py", line 13, in <module>
    import galaxy.app
ImportError: No module named galaxy.app

(.venv)steven@ecs-steven-dev 16:13:56 /data/galaxy 
$ which python
/data/galaxy/.venv/bin/python

(.venv)steven@ecs-steven-dev 16:14:16 /data/galaxy 
$ python -V
Python 2.7.14
```

I got the same error with `admin_cleanup_datasets.py`，so does someone know what the peoblem is?

**Comment by nsoranzo** [comment]
@istevenshen It seems these scripts have been broken for many years, pull request to fix them is coming.

**Comment by nsoranzo** [comment]
This will be fixed by https://github.com/galaxyproject/galaxy/pull/5725 .
