### ISSUE TITLE
is it possible to reorder datatypes_conf for faster sniffing

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5726]
based on real data? Could this improve sniffing performance?

sample data from usegalaxy.eu:

![screenshot 2018-03-19 11 11 20](https://user-images.githubusercontent.com/1814954/37604005-5e452a52-2b66-11e8-9ca9-57b859a379e9.png)

in the datatypes_conf.xml.sample `fasta` is the 37th datatype to be sniffed. Is it specific enough (or can we improve it) so it will be the first thing to sniff? Would that help?

ping @jmchilton @natefoo

**Comment by martenson** [comment]
xref: https://github.com/galaxyproject/galaxy/pull/5689

**Comment by hexylena** [comment]
oooh yay our data is useful @bgruening :)

**Comment by bgruening** [comment]
Cool!

**Comment by jmchilton** [comment]
Do we have any data that sniffing consumes a lot of time? If it is a significant bottleneck I'm sure https://github.com/galaxyproject/galaxy/pull/5793 will solve all the problems. If it is still is a problem, it also introduces more sniffing tests so we can more confidently re-organize the sniff orders.

**Comment by hexylena** [comment]
@bgruening btw I broke that page. I'm re-building it to be a bit more accurate and let us slice and dice the data in new and interesting ways :) Sorry for any inconvenience.

**Comment by martenson** [comment]
I think the concern of this issue should be remedied by #5793, closing
