### ISSUE TITLE
Chunked file uploads

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#573]
It is presently very difficult to upload very big (> 2 GB) files to Galaxy. To workaround this, an FTP server has to be used as described in https://galaxyproject.org/admin/config/upload-via-ftp/ . A more user-friendly solution, which would also reduced the admin work and the attack surface, is to integrate a library like https://github.com/blueimp/jQuery-File-Upload .

@guerler mentioned on IRC that this should feasible.

xref: https://trello.com/c/odrFJx7G/1267-improvements-for-the-new-upload-dialog

**Comment by nsoranzo** [comment]
Maybe I can bribe @anuprulez to take a stab at this ;)

**Comment by anuprulez** [comment]
@nsoranzo I will have a look at it...

**Comment by nsoranzo** [comment]
@anuprulez Thanks, no pressure!

**Comment by mblue9** [comment]
This would be great!! For a lot of the users I've worked with, Galaxy is their first time to use ftp transfers, Filezilla etc, so not having to use ftp to get files >2GB in would save them time and hassle.

**Comment by nsoranzo** [comment]
Fixed by #5516, thanks @guerler!!

**Comment by guerler** [comment]
Thanks a lot for your help @nsoranzo
