### ISSUE TITLE
[Feature Request]: Download Collection

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/galaxy#5744]
In the same way datasets have a "download" icon next to them, allowing HTTP download of a dataset, collections should have a similar icon which downloads a tarball of a collection, or just starts a download for each item in the collection. 

For galaxy to scale to large scale experiments, collections need to be a first-class citizen, and that means it needs to be possible to download a collection!

**Comment by mblue9** [comment]
@zfrenchee do you mean an icon like in this screenshot:

<img width="250" alt="screen shot 2018-03-21 at 11 34 41 am" src="https://user-images.githubusercontent.com/5591821/37689933-0fedd8bc-2cfc-11e8-94ac-80b0a8ff4b03.png">

What Galaxy version are you using? As I can see that icon in v18.01 and 17.09 and clicking it downloads a tar file of the datasets.

**Comment by nekrut** [comment]
It is certainly available at both usegalaxy.org and usegalaxy.eu

**Comment by alexlenail** [comment]
@mblue9 I'm on 17.05 and don't have it. Glad this has been addressed!!!

**Comment by mblue9** [comment]
>Glad this has been addressed!!!

Me too 😄 I was using it this morning and feeling very glad it was there. 

Btw if you're using collections with MACS2 and control samples you might want to keep an eye on this: https://github.com/galaxyproject/tools-iuc/pull/1782. As currently if I input a collection of treatment samples to MACS2 with a control collection they all get the control name used for the output peak files, which is not ideal 😞

**Comment by alexlenail** [comment]
@mblue9 thanks for the heads up!
