### ISSUE TITLE
BagIt, Upload 2.0, and Library Follow Up Issues

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5753]
- [ ] Better testing for linked data checks. I think something must have been missed.
- [x] Synchronize with datatype changes from Nate in https://github.com/galaxyproject/galaxy/pull/5689. Implement more tests to match.
- [x] Add ephemeris script and examples for this functionality.
- [x] Add a training-material example for the YAML format.
- [x] Scope out issue for UI for BagIt/zip/YAML uploads.
- [ ] Fix bagit test that is now skipped because of URL contents changing.

**Comment by bgruening** [comment]
Would it be possible to push GB of data into Galaxy. Sequencing facilities often are not allowed to provide public links to data, so it would be nice to push data directly into Galaxy accounts.
ping @anatskiy
