### ISSUE TITLE
default_identifier_source doesn't work with collections and affects use of MACS2

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/galaxy#5756]
Currently if you use MACS2 with collections and have a control sample, the Control element_identifier gets used for the output identifier instead of the Treatment. And if you input multiple Treatments with the same Control they all get the same identifier from the Control. In my case I end up with 5 files all called "input-1" :(. 

See discussion here: https://github.com/galaxyproject/tools-iuc/pull/1782

**Comment by mblue9** [comment]
@mvdbeek just wondering if there's any update on this or if you know what the issue is? as now that diffbind can handle collections I'd love to try macs2 next week with diffbind and knowing which sample is which would help a lot :)

**Comment by mvdbeek** [comment]
Sorry, I've been pretty busy over the last weeks with non-galaxy stuff, but I think I can look at this next week.

**Comment by mvdbeek** [comment]
Alright, so it seems to work in simple cases, but I have a hunch that in the macs2 case this is because `input_treatment_file ` is in a conditional.

**Comment by mvdbeek** [comment]
Yep, need to prefix with `conditional|`, so in the macs2 case it'd be `treatment|input_treatment_file`.
Opened https://github.com/galaxyproject/tools-iuc/pull/1865 to fix this.
