### ISSUE TITLE
Hashtags on Collections are lost when Histories are imported or copied by other users

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/galaxy#5757]
I discovered yesterday that the Histories I've been creating and sharing with users lose all the lovely hashtags when the users import (or copy) the histories 😞 into their accounts. This is with 17.09 and I haven't tested with 18.01 but afaik there's been nothing fixed in 18.01 for that.

**Comment by mblue9** [comment]
This appears to be specific to collections as the hashtags on the individual datasets remain.

e.g. In my history if I have:

![screen shot 2018-03-22 at 12 41 09 pm](https://user-images.githubusercontent.com/5591821/37746470-760dfed8-2dce-11e8-8a45-3836345f80a3.png)

then share that with a user, on importing the history they get:

<img width="521" alt="screen shot 2018-03-22 at 12 39 02 pm" src="https://user-images.githubusercontent.com/5591821/37746501-aa14cbda-2dce-11e8-99f6-adcc7c988f07.png">

**Comment by jmchilton** [comment]
Hmm... I'll take a stab at this. Sorry.

**Comment by mblue9** [comment]
Thanks a lot @jmchilton, much appreciated!!
