### ISSUE TITLE
Merge "Convert" and "Datatypes" in edit attributes?

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#5768]
Feels like these two tabs should be combined into a single "Datatype" column with a little blurb at the top explaining the difference between the two actions a little better.

![image](https://user-images.githubusercontent.com/155398/37793169-3a167282-2de4-11e8-9972-e5c121ced71b.png)
![image](https://user-images.githubusercontent.com/155398/37793184-3ef22364-2de4-11e8-8b55-24082e3673d6.png)

**Comment by hexylena** [comment]
Found this issue while filing another
