### ISSUE TITLE
having a shared workflow takes api/workflows response from 300ms to 20s

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5777]
After a bunch of testing @jmchilton and me tracked down the issue of slow loading 'my workflows' page. The API call is quick until you have a shared workflow with you. Then it slows down 100 times.

edit: this is on *Main*

**Comment by jmchilton** [comment]
On main - it doesn't slow down for me locally I don't think. Might be a missing index for that sharing query - I'll take a look.
