### ISSUE TITLE
collection does not finish loading its contents

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5781]
When looking at directly using link (e.g. https://usegalaxy.org/u/martenson/h/imported-fastqgz-sample). Instead it is stuck in grey loading forever with no pending xhr.

Can be related to https://github.com/galaxyproject/galaxy/issues/5629

![screenshot 2018-03-26 12 25 26](https://user-images.githubusercontent.com/1814954/37919048-cd4a0d02-30f0-11e8-8a02-682bbd3f4066.png)

**Comment by hexylena** [comment]
Fixed in #6165
