### ISSUE TITLE
history peeks for compressed datatypes are unreliable

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5785]
We should fix them or remove them since they are confusing to users.

* number of lines in a sequence is wrong most/all of the time
* the peek has extra whitespace that is not present when uncompressed

**Comment by martenson** [comment]
examples: 

same fastqsanger file with gz results in different peek than uncompressed
![screenshot 2018-03-26 14 48 10](https://user-images.githubusercontent.com/1814954/37926227-c4d179d0-3104-11e8-90e0-425ac9af648a.png)

genbank seems different, but this looks just like a formatting diff, unlike the fastqsanger that looks like different data
![screenshot 2018-03-27 16 01 05](https://user-images.githubusercontent.com/1814954/37991814-2bdbf898-31d8-11e8-81b9-8c2a830bc261.png)

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/issues/2694

**Comment by hexylena** [comment]
Looks good now :)
