### ISSUE TITLE
[Tool Shed] Not possible to add "Development repository" to existing repositories

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#579]
To reproduce:
1. Go to https://toolshed.g2.bx.psu.edu/
2. Login
3. Click on "Repositories I own"
4. Select a repository created some time ago (when "Development repository" field was not available)
5. In the "Manage repository" page there is no "Development repository" field between "Detailed description" and "Sharable link to this repository".

**Comment by martenson** [comment]
I am on it.

**Comment by nsoranzo** [comment]
Thanks @martenson !

**Comment by nsoranzo** [comment]
That was fast, thanks again!
