### ISSUE TITLE
Formal Support for Compressed Type Variants

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5790]
We let something a ad-hoc in for FASTQ datatypes and now that anti-pattern is spreading (#5553 , #5772 ). We should really cut it off ASAP so we can guarantee backward compatibility.

- This should just be a flag on datatypes_conf (e.g. ``compressable="true|false"``) - that auto-generates the compressed datatype and handles details such as metadata. We should also generate the converters automatically in memory at first.
- Ultimately though w should not use implicit type conversions - the file should be decompressed or compressed as needed during job staging/unstaging.

**Comment by mvdbeek** [comment]
Hmm, that seems difficult to get right.
Say I run 10 jobs that require the uncompressed input, would this be uncompressed 10 times ?
Same scenario, but jobs require compressed input and I have uncompressed input.
As it is now it seems like a decent compromise, but maybe I'm too blind to see how this would be done efficiently.
I guess it'd be great to outline how this should flow in more detail.

**Comment by mvdbeek** [comment]
Mostly talking about the second part, the first part I can see.

**Comment by martenson** [comment]
Is there benefit in compressing on the fly? Are there tools that take *only* compressed datatypes, or are the tools faster with compressed?

**Comment by mvdbeek** [comment]
That depends on the compression level and datatype we're talking about. vcf to bgzipped and indexed vcf.gz is a lot faster than raw vcf. For aligners compressed input can be faster. Staging may be faster as well depending on how well the input compresses.

**Comment by jmchilton** [comment]
> Say I run 10 jobs that require the uncompressed input, would this be uncompressed 10 times ?

Fair consideration. I have a very workflow-centric view of things which may be off.

I'd expect the typical analysis to not decompress the FASTQ dataset at all right - so 10 times seems a bit much. Maybe once or twice is even an outlier case? And even in those cases, aren't more Galaxy instances concerned about the space usage then the extra compute to decompress a file a few times? The other thing is that big shared NFS is the typical use case for Galaxy but it doesn't scale - if we are sending files around for jobs anyway is there any reason not to decompress it right before it hits the final destination?

Certainly the other use case is workable if you have a usage pattern that would benefit from uncompressed FASTQs - just upload the file as uncompressed.

An interesting question is to think about this outside of Galaxy - do modern bioinformatics workflows keep uncompressed FASTQ files on the disc ever in this fashion? I was under the impression these things are always kept compressed right up until they are streamed to a tool or read by the tool typically. I was also under the impression that people considered Galaxy ever thinking about uncompressed FASTQs as one of the reasons it is seen as kind of a toy in some ways?

These are just my impressions - I'll defer to you about actual workflows because I do not run them.

**Comment by mvdbeek** [comment]
> I'd expect the typical analysis to not decompress the FASTQ dataset at all right - so 10 times seems a bit much

It completely depends what you're doing, but you're right that typically you would use the input once or twice. There are some (non-canonical) workflows where you'd start aligning your fastq to a bunch of species or things like that. I do like that as a user you have control over this if you understand the tradeoffs, but maybe that is not worth the complexity ? Worst case you can convert explicitly.

> more Galaxy instances concerned about the space usage then the extra compute to decompress a file a few times?

Probably yes.

> An interesting question is to think about this outside of Galaxy - do modern bioinformatics workflows keep uncompressed FASTQ files on the disc ever in this fashion?

Definitely yes.

I guess if we go compressed by default that would be fine.

**Comment by martenson** [comment]
>I'd expect the typical analysis to not decompress the FASTQ dataset at all 

As the first step of many analyses Galaxy has been decompressing all .gz for years. The typical analysis is this imo. This makes me wary of enabling gz sniffing or defaulting to compressing everything. Unless it is transparent to the user.

>more Galaxy instances concerned about the space usage then the extra compute to decompress a file a few times?

It is extra compute AND time - especially when you have data locally to runner.

**Comment by jmchilton** [comment]
> defaulting to compressing everything

Has anyone suggested compressing gz files that are initially uncompressed?

**Comment by martenson** [comment]
@jmchilton I understood that much from

> the file should be decompressed or compressed as needed during job staging/unstaging.

**Comment by jmchilton** [comment]
> the file should be decompressed or compressed as needed during job staging/unstaging.

What I mean is that if there is some tool that takes in only a fastqsanger input - we should modify the tool form to allow "fastqsanger.gz" inputs and decompress on the worker node. Because it is the right thing to do typically and because it save spaces in general and time on usegalaxy.org and other sophisticated setups. A sophisticated user who knows they want uncompressed inputs for their workflows - can still do that - but most people, most of the time wouldn't want to do that and we don't want them to do that typically and admins in general don't want them to do that typically.

**Comment by martenson** [comment]
> we should modify the tool form to allow "fastqsanger.gz" inputs and decompress on the worker node

yes!


Thank you for clarifying.

**Comment by mvdbeek** [comment]
So a summary of the proposition is to replace implicit conversion with a staging phase ? That sounds good to me

**Comment by martenson** [comment]
I think this has been resolved with https://github.com/galaxyproject/galaxy/pull/5794
