### ISSUE TITLE
allow anonymous users to report bugs

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5791]
Currently only logged in users can do it, maybe we want to allow anonymous users to report too. I do not expect spammers catching on here.

**Comment by mvdbeek** [comment]
I think that works -- some of it was broken (https://github.com/galaxyproject/galaxy/issues/6675) but https://github.com/galaxyproject/galaxy/pull/6742 should have fixed that. Let me know if this is some other bug reporting.
