### ISSUE TITLE
uWSGI restart failing

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#5796]
Hi,
I'm preparing to update galaxy.genouest.org to 18.01, switching to uwsgi and yml conf.
I have a problem when trying to restart a running galaxy with `runs.sh restart` -> galaxy gets completely killed and not restarted at all.

Here's the full workflow:
```
cd /opt/galaxy-dist # that's where it is installed
./run.sh start
```

Then some logs (`executing: .venv/bin/uwsgi --yaml config/galaxy.yml --master --daemonize2 galaxy.log --pidfile2 galaxy.pid`), and finally `*** daemonizing uWSGI ***` => galaxy is running!

And now I try to restart it:

```
./run.sh restart
```

I get this log:

```
[...]
Activating virtualenv at .venv
executing: .venv/bin/uwsgi   --reload galaxy.pid
```

And then all galaxy processes are killed, and I see this in galaxy.log:
```
[...]
galaxy.app DEBUG 2018-03-28 12:01:45,442 [p:16436,w:4,m:0] [Dummy-5] Finished shutting down
galaxy.web.stack INFO 2018-03-28 12:01:45,469 [p:16442,w:5,m:0] [Dummy-5] Application stack interface shutting down
galaxy.app DEBUG 2018-03-28 12:01:45,469 [p:16442,w:5,m:0] [Dummy-5] Finished shutting down
galaxy.jobs.runners INFO 2018-03-28 12:01:45,552 [p:16459,w:0,m:3] [MainThread] DRMAARunner: Sending stop signal to 5 worker threads
galaxy.jobs.runners INFO 2018-03-28 12:01:45,562 [p:16459,w:0,m:3] [MainThread] LocalRunner: Sending stop signal to 4 worker threads
galaxy.jobs.handler INFO 2018-03-28 12:01:45,572 [p:16459,w:0,m:3] [MainThread] sending stop signal to worker thread
galaxy.util.monitors DEBUG 2018-03-28 12:01:45,572 [p:16459,w:0,m:3] [MainThread] Joining monitor thread
galaxy.jobs.handler INFO 2018-03-28 12:01:45,592 [p:16459,w:0,m:3] [MainThread] job handler stop queue stopped
galaxy.web.stack INFO 2018-03-28 12:01:45,593 [p:16459,w:0,m:3] [MainThread] Application stack interface shutting down
galaxy.web.stack.transport INFO 2018-03-28 12:01:45,593 [p:16459,w:0,m:3] [MainThread] Joining application stack transport dispatcher thread
galaxy.app DEBUG 2018-03-28 12:01:45,593 [p:16459,w:0,m:3] [MainThread] Finished shutting down
mule 1 (pid: 16448) annihilated
mule 2 (pid: 16454) annihilated
worker 1 buried after 3 seconds
worker 2 buried after 3 seconds
worker 3 buried after 3 seconds
worker 4 buried after 3 seconds
worker 5 buried after 3 seconds
mule 3 (pid: 16459) annihilated
binary reloading uWSGI...
chdir() to /opt/galaxy-dist
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:43854)
running /opt/galaxy-dist/.venv/bin/python
Unknown option: --
usage: /opt/galaxy-dist/.venv/bin/python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
```

Don't know if it's a misconfiguration somewhere or a bug, any clue on how to fix it?

**Comment by dannon** [comment]
**Edit:**  Well, that's a second bug.  @abretaud I misread your issue at first -- I've restarted uwsgi manually by sending a `SIGHUP` to the uwsgi process, but the regular reload command should work, we'll have to fix that.

**Comment by abretaud** [comment]
Oh, I just saw your edit.
I'm looking into it right now:
- sending a SIGHUP crashes the same way
- the problem is the same with the report app
- when it says `running /opt/galaxy-dist/.venv/bin/python`, it looks like the command that is run by uwsgi is:
```/opt/galaxy-dist/.venv/bin/python --yaml /opt/galaxy-dist/config/reports.yml --master --daemonize2 reports_webapp.log --pidfile2 reports_webapp.pid```
while it should be:
```/opt/galaxy-dist/.venv/bin/python .venv/bin/uwsgi --yaml /opt/galaxy-dist/config/reports.yml --master --daemonize2 reports_webapp.log --pidfile2 reports_webapp.pid```

I don't see why the `.venv/bin/uwsgi` is not there

**Comment by abretaud** [comment]
Ok, I think I understand what happens: `.venv/bin/uwsgi` is a python script with a shebang like this:
```
/opt/galaxy-dist/.venv/bin/python
```
which means this command is launched by run.sh:
```
.venv/bin/uwsgi --yaml /opt/galaxy-dist/config/reports.yml --master --daemonize2 reports_webapp.log --pidfile2 reports_webapp.pid
```
and it appears in `ps` as:
```
/opt/galaxy-dist/.venv/bin/python .venv/bin/uwsgi --yaml /opt/galaxy-dist/config/reports.yml --master --daemonize2 reports_webapp.log --pidfile2 reports_webapp.pid
```

When uwsgi tries to reload the app, it stops the old process and tries to rerun it [like this](https://github.com/unbit/uwsgi/blob/master/core/master_utils.c#L607)

-> it uses a binary_path which [comes from /proc/](https://github.com/unbit/uwsgi/blob/master/core/utils.c#L2687) and which is `/opt/galaxy-dist/.venv/bin/python` instead of `.venv/bin/uwsgi`

I had not seen this problem in the docker image because I suspect that supervisor detects that the reload crashes and immediately restart the process from crash. As we use systemd on this instance, it just crashed.

Now... no idea how to make uwsgi detect the right binary_path...

**Comment by hexylena** [comment]
@abretaud did this ever start working again?

**Comment by abretaud** [comment]
Ah, I've been using stop/start since I created this issue, but I just made a new test: it seems to work fine now
It's odd as I see no change in the corresponding code in uwsgi... Anyway I'm happy now :)
