### ISSUE TITLE
Regression in CRAM support in 18.01?

### ISSUE THREAD

**Issue by dpryan79** [galaxyproject/galaxy#5801]
I have [a test that uses a CRAM file](https://github.com/deeptools/deepTools/blob/hotfix/alignmentSieveWrapper/galaxy/wrapper/alignmentSieve.xml#L155-L160) as part of the most recent deepTools release. I've noticed that this test has recently started failing and it turns out that if I use planemo with either the `master` or `release_18.01` branches then `$bamfile.metadata.cram_index` is `None` for CRAM files, whereas in `release_17.09` this pointed to the appropriate file. I've not tracked down exactly what change caused this, but it at least appears that there was regression in the support for CRAM files somewhere between 17.09 and 18.01.

BTW, there is an index generated for that file under release_18.01, but for some reason it's a bai file, which won't work for a CRAM file.

**Comment by dpryan79** [comment]
One can test this with `planemo test --galaxy_branch release_18.01 ...` and `planemo test --galaxy_branch release_17.09 ...`.

**Comment by dpryan79** [comment]
The earliest commit where this seems to break is https://github.com/galaxyproject/galaxy/commit/889e0839d4c32afa280fae12ef9a063a01653411. I have no idea how that could lead to the behavior I'm seeing.

**Comment by mvdbeek** [comment]
Thanks for the report! I got that wrong while transitioning from samtools to pysam, I'll have a fix in a minute.

**Comment by mvdbeek** [comment]
I didn't see the creation of `.bai` indexes though, if you see that again let me know.
