### ISSUE TITLE
Create a readme/docs for Galaxy dependency handling

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5818]
Introduction of pipenv and changes in https://github.com/galaxyproject/galaxy/pull/5776 should be (better) documented, so contributors can add/modify requirements easily.

@nsoranzo @natefoo @jmchilton 

edit: there is also `make update-dependencies`

**Comment by nsoranzo** [comment]
I added this to https://github.com/galaxyproject/galaxy/issues/5483, not sure if you want to keep this open anyway.
