### ISSUE TITLE
conda_auto_install not used with requirement in tool.xml

### ISSUE THREAD

**Issue by brigidar** [galaxyproject/galaxy#5820]
Hi,
I have a local instance of galaxy installed with conda already installed. I set conda_auto_install and have put the packages that need to be installed as requirements in the xml files of the tools that I uploaded locally (in development), but I don't see any automatic installation of the packages prior to running the script. It only works if I manually install biopython and pandas and then run the tool. How do I get to check the conda bin for the package and then grab it if it is not already present in conda? Not sure what I am missing. I am using version 18.01 of galaxy and 4.4.10 for conda on a Mac OS Sierra.

**Comment by hexylena** [comment]
We've used this option recently and everything works ok? Perhaps an issue in the older version of Galaxy then.
