### ISSUE TITLE
'data_manager_fetch_genome_all_fasta' cloning status forever

### ISSUE THREAD

**Issue by biomendi** [galaxyproject/galaxy#5824]
Hi everyone:

I want to add a reference genome for shared use in our local Galaxy instance. To do so, I am following this tutorial: https://github.com/galaxyproject/dagobah-training/blob/2017-montpellier/sessions/05-reference-genomes/ex1-reference-genomes.md 

I have already modified the galaxy.ylm file and restarted the server as stated. Then I did: Admin > Tool Management > Install new tools (Beta) > Data Managers >  data_manager_fetch_genome_all_fasta and tried to install that. However, its installation status remains "cloning" forever. 

How can I solve this issue? Thank you!

**Comment by hexylena** [comment]
This should be working better with condafied dependencies, and also with CVMFS which is now [included in the admin training](https://training.galaxyproject.org/training-material/topics/admin/tutorials/cvmfs/tutorial.html)? Maybe these will help your case
