### ISSUE TITLE
Uploading png fails with "inappropriate content"

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#5832]
Hi,
We're doing some tests with the 18.01 release, and we have a problem with uploading some png or jpg file in the history.

With whatever image, the dataset gets in error state with a message saying "The uploaded binary file contains inappropriate content".
Another (maybe unrelated) thing: if trying to change its datatype, the dataset gets yellow forever with the "setting metadata" message, although no job is launched on the server.

We've seen this problem on our test 18.01 instance and usegalaxy.org (18.01 too I think?). In our production instance (17.09) and usegalaxy.eu (17.09 too I guess), we don't see this problem, the png/jpg files are properly detected when uploaded.

**Comment by nsoranzo** [comment]
I can replicate this and I'm bisecting it.

**Comment by nsoranzo** [comment]
I tracked this down to commit 0e0acb5200720cddaaff32bddf71c65f6cfe777e , debugging it now.

**Comment by abretaud** [comment]
Thanks @nsoranzo!

**Comment by nsoranzo** [comment]
The problem seems to be that the `Image` class does not inherit from `Binary`, looking for possible solutions.

**Comment by nsoranzo** [comment]
This has been fixed in the `dev` branch by @natefoo in commit ef6f7f62ab679928045c816a3cb719fb3bcea507 , but that's too big to be backported as is.
