### ISSUE TITLE
BS4 data libraries

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#5844]
* pagination buttons do not work
* include deleted /exclude restricted are not aligned well

**Comment by bgruening** [comment]
library buttons are bigger then before, which yields to top-aligned text in other columns:

![grafik](https://user-images.githubusercontent.com/469983/38324510-d66206a4-3840-11e8-859a-55eb1e112ccf.png)

**Comment by martenson** [comment]
Fixed all toolbar/pagination things in the following commits

Will have a look at the data rows themselves now.

https://github.com/galaxyproject/galaxy/pull/5807/commits/2b975b2d6a5cc4bce11001d6b4900a64479fe580
https://github.com/galaxyproject/galaxy/pull/5807/commits/8e876963612ba9a043b0ce7d168b767d390bd0ca
https://github.com/galaxyproject/galaxy/pull/5807/commits/d59508c9029876a79eb27f6bf327c3b38d37a8fd
https://github.com/galaxyproject/galaxy/pull/5807/commits/3181fbb442b6a048255439c6dce1222f2a4dc919

**Comment by martenson** [comment]
row alignment improved with https://github.com/galaxyproject/galaxy/pull/5807/commits/f05a1393a19e15f942376db22dd51334d6232676
