### ISSUE TITLE
Manage Users/Groups/etc...

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#5848]
the create button doesn't always separate from title and move to other side of page.

This happens in my browser but not in Selenium tests so this is really odd. I'm confused.

**Comment by dannon** [comment]
@jmchilton Are you still seeing this in your browser?  I'm not sure if something fixed it, but I haven't been able to cause it in either FF or Chrome.

**Comment by jmchilton** [comment]
Current commit:

<img width="1636" alt="screen shot 2018-04-04 at 2 44 40 pm" src="https://user-images.githubusercontent.com/216771/38327654-c4f3b3f6-3816-11e8-837a-6b48c1cee4e1.png">

Random commit from last night:

<img width="1653" alt="screen shot 2018-04-04 at 2 42 12 pm" src="https://user-images.githubusercontent.com/216771/38327565-87585452-3816-11e8-881f-b067bc6bc2f6.png">

**Comment by dannon** [comment]
@jmchilton Argh, weird, thanks for the screenshot.  Can you check two things when you have a sec?

1) that the `ul.manage-table-actions` containing that button has a `float:right`
2) check chrome's computed size for the `.grid-header`, and see if it's full width

**Comment by jmchilton** [comment]
If I give the table tag for the grid template a "grid-table" class and assign it 100% width it fixes it for me (ping @guerler any downside to that?).

I'll revert those changes and see what I see @dannon...

**Comment by jmchilton** [comment]
<img width="1442" alt="screen shot 2018-04-04 at 2 59 23 pm" src="https://user-images.githubusercontent.com/216771/38328403-da178d28-3818-11e8-8ce6-c985696a69d2.png">
<img width="1441" alt="screen shot 2018-04-04 at 2 59 36 pm" src="https://user-images.githubusercontent.com/216771/38328406-dc0d3be6-3818-11e8-97dd-6e70317779c9.png">

**Comment by dannon** [comment]
@jmchilton It wouldn't be a local extension or webhook or something you were tinkering with, right?  I'm running out of ideas on this one -- is anyone else seeing it?

Can you try firefox or something on your local galaxy and see if it's happening there, too?

**Comment by bgruening** [comment]
@dannon I can reproduce it in Chrome/chromium if I zoom out to 90%. FF seems to be ok.

**Comment by dannon** [comment]
@bgruening Ah-ha!  Chrome and zoom, I have reproduced it now, thanks!

**Comment by dannon** [comment]
@jmchilton I tinkered with this a bit and it's a chrome rendering bug; google suggests several of these exist w/ zoom.  I can confirm the table width fix works, and I'm not seeing any downside -- added this fix in 54db0df20ba977b239cf4ec5db12e31ab74b5d06
