### ISSUE TITLE
Upload dialog 

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#5850]
* [x] "settings" icon not working in a row item
* [x] Inconsistent UI alignment in the upload dataset modal popup for search and computer screen icons. In the same modal, search and setting icons do not work on clicking.

![bug3](https://user-images.githubusercontent.com/3022518/38251054-a41ef77e-3750-11e8-9073-ba1b11a3c968.png)

* [x] In the same dataset upload modal, for composite tab, “Select” dropdown has two carets.

![bug4](https://user-images.githubusercontent.com/3022518/38251095-c68b4934-3750-11e8-8151-e67b2eea3dc8.png)

~~* Cannot remove the item uploaded to the modal but not yet uploaded to the history in the composite tab. For regular tab, it is possible to remove any item before uploading the others to history. I am not sure if it is a feature. I can replace this item by choosing another one.~~

![bug5](https://user-images.githubusercontent.com/3022518/38251167-f823db82-3750-11e8-9970-001007bb9dd0.png)
* [x] the 'choose ftp file' button in the upload modal does not work

**Comment by anuprulez** [comment]
As I fix something from this list, I will comment here. thanks!

**Comment by dannon** [comment]
Deduplicated items listed here.  

@anuprulez fixed most if this in 75d03ddf19f697ae048e9bbd6775388888351031
a46df8ce6bbc0a7f62d798b1699ea3584b1326ce
and a46df8ce6bbc0a7f62d798b1699ea3584b1326ce

The last remaining item is not a BS4 issue, moved enhancement idea to https://github.com/galaxyproject/galaxy/issues/5863

**Comment by dannon** [comment]
@anuprulez Thanks for all the work on this!
