### ISSUE TITLE
BS4 Buttons 

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#5851]
Buttons (coloring and dropdown functionality) everywhere needs a review.

* [x] Multiple History View Buttons are pretty ugly now

![image](https://user-images.githubusercontent.com/155398/38319943-302cccc2-3801-11e8-88aa-254ede371a76.png)

* [x] tool citations button looks off

![grafik](https://user-images.githubusercontent.com/469983/38306493-048560b0-3811-11e8-8db4-40db1f017117.png)

* [x] restore border

* [ ] drop shadow focus removed (for now, we should consider the new standard focus indicator though)

**Comment by dannon** [comment]
Migrated items from #5830 related to buttons

**Comment by dannon** [comment]
Regarding restoring borders, and the drop shadow -- a bit of devil's advocate.  Should we be pushing back against the bootstrap4 button styling, or should we adjust the theme to make the borderless buttons and dropshadow look better for our use?

**Comment by martenson** [comment]
+1 Adjusting the theme. Pushing back will lead to inconsistencies between 'us' and 'them' and I think they are better in design than we are.

Most importantly we shouldn't be breaking any bs4 classes knowingly (like outline buttons are now) so everybody can come and use 'galaxy bootstrap'. edit: without any prior or internal knowledge

**Comment by martenson** [comment]
the border has been re-added in https://github.com/galaxyproject/galaxy/pull/5807/commits/4eb40607dee22381861933747c07e44ca824c691

this should make our transition to bootstrap button style smoother

**Comment by martenson** [comment]
addressed multiview styling in these:

https://github.com/galaxyproject/galaxy/pull/5807/commits/05c99b9ff7e172a36f0ff265179144ee04f2defe
https://github.com/galaxyproject/galaxy/pull/5807/commits/fd3f8c9b635ed6e51b21068bd14c929487980573


I think the new focus indicator(last item here) works ok now so I am closing this issue.
