### ISSUE TITLE
Center Pane on test is not aligned properly

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#5856]
Penn State, Hopkins, OHSU logos are all screwed up:

![screen shot 2018-04-05 at 9 45 29 am](https://user-images.githubusercontent.com/4291636/38369594-19059db6-38b6-11e8-83a3-79a0b6a15014.png)

**Comment by dannon** [comment]
@nekrut Thanks, should be fixed now. (https://github.com/galaxyproject/usegalaxy-playbook/commit/169ef847fb90bf78a2c067358c1981d1db0a2a96)
