### ISSUE TITLE
Tool Forms do not look right (example)

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#5857]
Single dataset, multiple datasets, and collection buttons have radiobuttons which should not be there:

![screen shot 2018-04-05 at 9 47 31 am](https://user-images.githubusercontent.com/4291636/38369793-882009ca-38b6-11e8-89dc-3791a65155f6.png)

**Comment by dannon** [comment]
The radio buttons should be fixed in the branch, but I'll leave this open until we can redeploy to test.

**Comment by bgruening** [comment]
It is fixed, but the alignment is still wrong a little bit and the buttons needs to have borders.

**Comment by blankenberg** [comment]
Selecting button on tool form doesn't display selected state.

Before selecting:

![image](https://user-images.githubusercontent.com/1231190/38377453-f8daf5f0-38c8-11e8-9062-dbe86e03eee4.png)


After selecting (and toggling back and forth):
![image](https://user-images.githubusercontent.com/1231190/38377478-0781e168-38c9-11e8-85c1-893a88c77ece.png)

**Comment by dannon** [comment]
Ping @guerler -- did you come across this in your tool form work yesterday?

**Comment by mvdbeek** [comment]
I think that's (partly?) because the tool panel is wrongly expanded, but that's pre-existing. I've bisected this to https://github.com/galaxyproject/galaxy/commit/fc7beca6d1d379ddfc1ea4769edfc8c22d74fb10

**Comment by dannon** [comment]
@mvdbeek Thanks!  I thought this sounded like what you had mentioned on gitter (I think) a little while back.

**Comment by guerler** [comment]
@mvdbeek What browser are you using? It works fine for me on dev.

**Comment by mvdbeek** [comment]
Any browser will do. See the screenshot on mobile Android, this is bwa-mem
and should be hidden, you can compare this with bwa-mem on usegalaxy.org

**Comment by guerler** [comment]
Maybe we are looking at different issues. I am referring to "Selecting button on tool form doesn't display selected state." and to "...radiobuttons which should not be there".

**Comment by mvdbeek** [comment]
~~I strongly suspect this is linked, what dan has described works for me if the button is not (supposed to be) hidden under a conditional. I.e it doesn't work when leaving the default of "Do not set", but when you select "Set read groups" you can actually switch and the button state changes.~~

That doesn't actually work in either case and is hence not BS4 related, but still it would be great if this can be fixed. Makes working with dev very cumbersome.

**Comment by guerler** [comment]
@mvdbeek yeah I am on it. Should have a fix later today. Thanks!

**Comment by guerler** [comment]
@mvdbeek conditional handling fixed in dev. Toggling of radio buttons fixed in #5807.
