### ISSUE TITLE
improve UX of the tour list

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5860]
We have 3 tours on Main, but nobody can tell without reading the whole page.

![screenshot 2018-04-05 15 04 48](https://user-images.githubusercontent.com/1814954/38386461-bd6c209c-38e2-11e8-99db-90b289d8f94c.png)

**Comment by dannon** [comment]
Yeah, agreed.  We started out with a simple list, added this interface for category sorting with the intent to follow up on it.  Not sure if there's already another issue, though, so thanks for making this one!

**Comment by selten** [comment]
I'll take a stab at it. I'm kinda responsible for this mess anyway.

**Comment by jxtx** [comment]
Simple list with tags and "faceted filtering" seems most appropriate here?

**Comment by dannon** [comment]
@jxtx Yep, exactly what we'd talked about in IRC a bit, +1

**Comment by selten** [comment]
And possibly a search function as well to search by the tour name?

**Comment by selten** [comment]
@dannon can this issue now be closed?

**Comment by dannon** [comment]
Yep!
