### ISSUE TITLE
Bootstrap dependency loading (TDT error)

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#5865]
Dependencies pulled in via require() fail to load, yet again, with this migration.

I made a lot of progress towards eliminating dependence on random galaxy libraries with the recent shift to parcel for the vizualization framework, but this needs to be finished across the board.  Plugins cannot rely on arbitrary libraries from Galaxy, or we'll break stuff every single time -- they need to be prebundled with their requirements, *or* use a defined entrypoint into a Galaxy bundle, a-la the 'extended' bundle we created.

I think this is what's causing the tool driven tours to fail in the BS4 branch.

**Comment by anatskiy** [comment]
I'll fix this.

**Comment by dannon** [comment]
@anatskiy Great!  Let me know if you want to talk through the potential solutions, I'm happy to help you out.

Edit: just to add it here, the easiest thing as a preliminary fix, I think, would be to include the necessary libraries and components in the `extended` application entrypoint, and use window.bundleEntries instead of require(), kinda like we do for charts and the other things that do, to some extent, rely on Galaxy code -- see https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/apps/extended.js#L115 for examples.

**Comment by dannon** [comment]
My 'easiest' suggestion is going to either require loading the extended bundle on all pages (since webhooks are shipped everywhere), or an additional bundle.  I started work on bundling then webhook itself, yesterday, here:  https://github.com/dannon/galaxy/commits/bundled_webhooks  That scaffolds out the general idea, just needs to have a dependency conflict resolved and it's good to go.

**Comment by dannon** [comment]
@anatskiy I added extra staging in https://github.com/dannon/galaxy/commit/1861d11e42f66bcd5970a15e3be821dcc434e7c0, which should fix tour library loading via require() for the TDTs, and I'll fix the tour tests in this branch now.

We should still pursue bundling, and it'd be great if you wanted to take that branch of mine and continue to work on it.

**Comment by anatskiy** [comment]
@dannon sure. What needs to be done now?

**Comment by dannon** [comment]
@anatskiy For this particular branch, nothing, I think we're good to go.  For future work, check out https://github.com/dannon/galaxy/commits/bundled_webhooks and see if that approach makes sense to you.  This is how we've been doing visualizations, and it's working pretty nicely there.  There's a backbone/underscore conflict to resolve left in the branch, so it doesn't *quite* work yet, but the goal is basically to remove require()-driven loading from any plugins.

**Comment by anatskiy** [comment]
@dannon yeah, I like the new approach. Does this mean that all new (and old) webhooks need to use it too? It introduces the use of `package.json` and `.babelrc`, so the things become slightly more complicated. And the docs will have to be updated, too.

**Comment by dannon** [comment]
Webhooks without any dependencies won't need to use either -- we only need package.json to annotate how to build the standalone webhook bundle.  And in this case, I added the `.babelrc` to try to fix the underscore importing (with `babel-plugin-auto-import`), but that isn't working correctly yet anyway, so we may be able to dump that here.

**Comment by anatskiy** [comment]
But if a webhook does have dependencies, then it needs to be bundled?

**Comment by dannon** [comment]
Correct, this is to create atomic, complete plugins, instead of relying on a particular set of dependencies and versions of those being available in the galaxy client, or in `/static/scripts/libs/*`, etc.  An additional benefit here is that without this separation, plugins may only work with certain versions of Galaxy due to the libraries used in the client, etc.

**Comment by anatskiy** [comment]
Gotcha! This approach gives more flexibility and robustness. I like it!

**Comment by dannon** [comment]
Great!  With this `bs4` branch fixed, I'm going to move on to other stuff, but please do take that `bundled_webhooks` branch and run with it (though, of course, no rush now!).   Let me know if you need any help!
