### ISSUE TITLE
Flatten Collection runs before job that discovers collection elements

### ISSUE THREAD

**Issue by anilthanki** [galaxyproject/galaxy#5867]
I am trying to use the 'Flatten Collection' tool to flatten a nested list within a workflow, but it produces an empty list.

When used outside a workflow, it works fine. Also, if the nested list is a workflow input connected to 'Flatten Collection', it works. But if the nested list is generated by another tool as part of the workflow and feeds into 'Flatten Collection', it won't work.

Thanks
Anil

**Comment by jmchilton** [comment]
I tried to write a test case (https://github.com/galaxyproject/galaxy/pull/6541) for this and I cannot reproduce it - is it possible this has been fixed since it was filed? Otherwise do have any ideas how I can expand the test case to catch this behavior?

**Comment by anilthanki** [comment]
Hi John

If your input is nested collection it will work, but if you generate nested list inside the workflow it creates empty list.

Let me know if you want me to share a test workflow with you?

**Comment by jmchilton** [comment]
That test workflow generates the nested collection from a tool in the workflow. Maybe the step before it needs to be a mapping step? In the example you have is the previous step:
- A tool directly generating the nested collection
- A mapping step over a list input with list output so a nested list is generated.
- A mapping step over a nested list input and data output so a nested list is generated.

Does that make sense? Maybe if you shared a test workflow that would be helpful.

**Comment by anilthanki** [comment]
Here it is

https://usegalaxy.eu/u/anilthanki/w/homology-classifier-imported-from-uploaded-file  

Where input is collection of genetree from TreeBeST..

**Comment by kcoe01** [comment]
I am having the same problem with my workflow. The flatten collection tool is executing before the nested collection it is suppose to operate on is even finished, resulting in an empty list.

**Comment by mvdbeek** [comment]
This is a problem that only occurs if the collection contents are dynamically discovered using `discover_datasets` and where mapping over occurs. I can manually fix this in the code by delaying https://github.com/galaxyproject/galaxy/blob/05fbcc41de9db805892f557beb5a035e9fa72b3b/lib/galaxy/tools/execute.py#L101.

**Comment by anilthanki** [comment]
Thanks a lot, @mvdbeek I tested locally and #7633 fixes the issue
