### ISSUE TITLE
Saved Histories list -- options that don't work yet or could use tuning plus ok's

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#5871]
Ok:

 - **Change Permissions** - proper page, in the center panel. Great! However, clicking on "Save" returns the entire history list, not the one the user started from. Same idea for improved UI as for Share or Publish "Bonus" below.
 - **Rename** - proper page, in the center panel. Same "Save" issue as for others - returns to full, unfiltered history list.
 - **Delete/Undelete/Perm Delete** - all work as expected. Yea!

Problematic:

 - **Switch** - nothing happens
 - **View** - nothing happens
 - **Copy** - nothing happens

Could use tuning:

 - **Share or Publish** - proper page, but not in the center panel (uses up entire window). So, no masthead and the "Back to Histories List" link is really tiny at the bottom (always been that way) but maybe could be at the top of the page/more obvious? 

**Bonus**: It would be nice if the original list (however filtered) was gone back to - right now it just reloads the same as "User/History > View Saved Histories" -- meaning the full default list. _This means one has to filter again each time a function is used and the history list is returned to._

**Side issue:** Using the browser back button: May not matter since works on Test (at least rn), but when compared to Main, the back button results in a "nested" Galaxy view, inside of the center panel (Mac OSX, Chrome). This happened sometimes before but not with this exact function afaik. Is something I do often since the "Back to Histories List" link is so far down on the Share page and not as quick to use. Not sure what the underlying trigger is to get a nested view, but it does happen even when using just links in the UI, so putting it out there as something to watch for in the New.
<img width="1167" alt="screen shot 2018-04-09 at 1 39 43 pm" src="https://user-images.githubusercontent.com/8999735/38521807-97f1af14-3bfb-11e8-8294-3a1c6686a9e0.png">

Merge this ticket if this is a duplicate

**Comment by jennaj** [comment]
All needs to be retested at usegalaxy.org @jennaj vs 18.09

**Comment by martenson** [comment]
I think this view is in a decent shape now. @jennaj please create independent issue(s) for the ideas you mentioned.
