### ISSUE TITLE
Can not select a list of pairs for input with multiple=true

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy#5875]
Hi,

As spotted for MultiQC (https://github.com/galaxyproject/tools-iuc/issues/1658), if we run FastQC on a list of paired data, we get as a result also a list of pairs, but these are not selectable as input in a MultiQC analysis. We thought it is maybe because of the `multiple=true` in the input.

I tested on FastQC (simpler to test, with Planemo) and I can reproduce the same behavior:

- Normal case (not `multiple=true`): I can select the list of pairs as input for FastQC
- Case with `multiple=true`: I can not select the list of pairs as input for FastQC

Is it an expected behavior?

Bérénice

**Comment by jennaj** [comment]
Same issue, tracking for .org update: https://github.com/galaxyproject/usegalaxy-playbook/issues/114

**Comment by jmchilton** [comment]
This is the expected the behavior as discussed on the tools-iuc issue, closing this.
