### ISSUE TITLE
pipefail and errexit in all tool_scripts

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5884]
@mvdbeek recently introduced pipefail in the bwa wrappers (https://github.com/galaxyproject/tools-iuc/pull/1823). I would suggest to introduce these commands in the galaxy_...sh scripts (or the tool_script.sh): 

```
set -o | grep -q pipefail && set -o pipefail;
set -o | grep -q errexit && set -o errexit;
```

The later command should not affect tools that combine commands with `&&` or `||` (https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html : "The shell does not exit if the command that fails is ..., part of any command executed in a && or || list except the command following the final && or ||, any command in a pipeline but the last... "). 

This might simplify tool development a bit, since we can save all the `&&` and errors within piped command chains would be caught.

**Comment by nsoranzo** [comment]
`set -e` (equivalent to `set -o errexit`) is already applied if adding `strict="true"` to the `<command>` element or `profile` >=16.04 to the `<tool>` element, see https://docs.galaxyproject.org/en/latest/dev/schema.html#strict
Maybe it's time to change the default for the next release?

**Comment by bernt-matthias** [comment]
Ah - OK. How about adding pipefail in case of `strict="true"`. I would agree to changing the default.

**Comment by bernt-matthias** [comment]
> set -e (equivalent to set -o errexit) is already applied if ... profile >=16.04 

Actually it seems not: https://github.com/galaxyproject/galaxy/pull/9962

> Maybe it's time to change the default for the next release?

You mean the default profile?

How about adding pipefail?

**Comment by nsoranzo** [comment]
> > Maybe it's time to change the default for the next release?
> 
> You mean the default profile?

Yes.
 
> How about adding pipefail?

It may be good, but it's not POSIX so it may not work when executing jobs on containers (which use `sh` instead of `bash`).
