### ISSUE TITLE
BAM sort order discussion

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5889]
Currently there are several data types for BAM: Bam, BamInputSorted, BamQuerynameSorted (and BamNative). Bam seems to implicitly assume sorting by coordinate.  

While implementing samtools v1.7 galaxy tools (https://github.com/galaxyproject/tools-iuc/pull/1801) I found it often cumbersome to use these data types in order to determine the sort order, e.g.: if I need coordinate sorted input I need to check if (Bam and not (BamInputSorted or BamQuerynameSorted)). 

The BAM (SAM/CRAM) format has the nice SO header entry which gives the sort order, which is already recorded in the Bam (and BamNative) data types (https://github.com/galaxyproject/galaxy/blob/30e3658b8b0e2f6b975dc6ccccb0cc8cc040247c/lib/galaxy/datatypes/binary.py#L200), but set to `visible=False`. I guess this forbids the use of this metadata in galaxy tools?

Making this metadata element accessible by tools would simplify the usage of the data type in tools and give the additional advantage to allow for different sort orders (e.g. by read group or tag). At the same time the BamInputSorted and BamQuerynameSorted data types could be dropped (at the moment no Galaxy tool seems to use them anyway).

**Comment by mvdbeek** [comment]
> if I need coordinate sorted input I need to check if (Bam and not (BamInputSorted or BamQuerynameSorted)).

That's not correct, BAM is the only coordinate sorted datatype. The other datatypes will not be selected, so the `and not` part is not necessary.

**Comment by bernt-matthias** [comment]
@mvdbeek thanks for the clarification. I will fix this in my PR. I implicitly assumed that the type of the object is used (then it would have been problematic because of inheritance), but its the extension. 

Just to be sure: for CRAM I can not assume any sort order? 

Which data type should I assume for unsorted BAM or tag sorted BAM (`samtools sort -t TAG`)? Would this be BamNative?

**Comment by mvdbeek** [comment]
Correct, unsorted should be bam_native, and tag sorted as well (due to the lack of a tag-specific datatype). 
CRAM could be any sort order, but IIRC you can index all CRAM files independent of sort order. We may want to narrow this down similar to what we're doing with BAM files.

Which is a little sub-optimal, see https://github.com/galaxyproject/galaxy/issues/5790 for a discussion concerning compressed file types, but I think the same concerns apply.

**Comment by bernt-matthias** [comment]
OK. Thanks for the clarifications.

**Comment by bernt-matthias** [comment]
@mvdbeek Just one more question: Is it correct that the inheritance structure of the data type classes is considered for the selecting data sets in the Galaxy UI? For instance if I have a tabular input field also SAM is allowed (which makes sense). 

I guess this was the source of my misconception of the `is_of_type` function.

**Comment by nsoranzo** [comment]
@bernt-matthias Yes, that's the case.

**Comment by bgruening** [comment]
@bernt-matthias can we close this?

**Comment by bernt-matthias** [comment]
jep.
