### ISSUE TITLE
History import view does not show error messages in latest Safari

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#5901]
To reproduce, use a new version Safari e.g. 11.1 (13605.1.33.1.2), click on gear-icon in history panel and select the (last) dropdown option for history import. Submitting the form without any inputs does not display the error message. This works fine in Chrome and Firefox. It seems that the ajax done/fail-callbacks do not fire. 

See:
https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/components/HistoryImport.vue#L51

**Comment by dannon** [comment]
I think I've figured out the problem, hopefully will have a fix in a few.

**Comment by dannon** [comment]
@guerler Well, I thought I had it.  I rewrote it using axios and the other stuff, but Safari does the same thing with FormData hanging.  Did this interface use FormData before?

**Comment by guerler** [comment]
Yeah this component always used the FormData object afaik. Can you point me to the axios version of this?

**Comment by dannon** [comment]
@guerler Sure, let me dig it up.  Might as well PR it since it uses the more modern fetch anyway, I guess.

**Comment by dannon** [comment]
Ok, found it (edit: my stashed change, not the actual safari problem).  Now that I think about it, I'm going to swap it to b-form and b-form-file, too, now that that's integrated, to see if that handles the safari weirdness any better.
