### ISSUE TITLE
multiview history misalignment

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5910]
![screenshot 2018-04-18 11 07 59](https://user-images.githubusercontent.com/1814954/38940711-db784924-42f8-11e8-83d7-27f780233947.png)

**Comment by dannon** [comment]
@martenson This just popped up after the merge, right?  It was all working before :/

I'll take a look.

**Comment by martenson** [comment]
@dannon not sure, I did not check it recently.

**Comment by dannon** [comment]
Ok.  This is with fresh dev, clean client build, in chrome?  I'm not seeing the same thing on my end, but I'll experiment a bit.

**Comment by martenson** [comment]
I was actually on a feature branch, but on dev I can see it too, just different columns though :D
![screenshot 2018-04-18 11 18 20](https://user-images.githubusercontent.com/1814954/38941302-42eb772e-42fa-11e8-9b82-50455ce1733d.png)

Clean build, chrome.

**Comment by dannon** [comment]
@martenson Weird, I'll try to replicate that.  Seeing perfectly aligned columns on my end, but maybe I need to create a bunch of big histories.

I see it now, the second screenshot tipped me off that it was likely related to late-loaded columns.  Thanks!
