### ISSUE TITLE
change_format deprecated?

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5911]
According to https://github.com/galaxyproject/galaxy/blob/d7a0fdfaa748ca427dda1cef74b81e253f1921d5/doc/source/releases/17.05.rst the `<change_format>` tag is deprecated (but seems still functional). 

This is currently not reflected in the Galaxy tool xml documentation -- which is confusing.

**Comment by nsoranzo** [comment]
`<change_format>` is not deprecated, only the `input_dataset` and `attribute` attributes of the contained `<when>` element are, see https://github.com/galaxyproject/galaxy/pull/3579/files
