### ISSUE TITLE
Jenkins Selenium tests broken against dev.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5912]
```
cd client && yarn install --network-timeout 120000 --check-files
yarn install v1.3.2
warning Skipping preferred cache folder "/.cache/yarn" because it is not writable.
warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-999".
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: clone https://github.com/sorich87/bootstrap-tour.git /tmp/.yarn-cache-999/v1/.tmp/1a3424707d9452cd61fff0ced1104c47
Directory: /var/jenkins/workspace/docker-selenium/client
Output:
Cloning into '/tmp/.yarn-cache-999/v1/.tmp/1a3424707d9452cd61fff0ced1104c47'...
fatal: unable to look up current user in the passwd file: no such user
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Makefile:144: recipe for target 'node-deps' failed
make: *** [node-deps] Error 1
Launching docker container for testing with extra args -e GALAXY_TE
```

**Comment by dannon** [comment]
@jmchilton We saw this a couple times in the bs4 branch, but it seemed intermittent and reruns fixed it.  It may be that certain nodes have git/users configured that others do not?

**Comment by martenson** [comment]
Nodes shouldn't have git users at all I think (or we shouldn't use them), Jenkins provides the environment. But tracking which node(s) this happens on could be useful.

**Comment by jmchilton** [comment]
Doesn't it seem like this is happening in a docker container? If it is intermittent maybe the Jenkins user id is different on different workers. I think n4 has a different jenkins user id (1000) than the others (999) - 1000 is probably configured in the container and not 999. Hmmmm....

**Comment by dannon** [comment]
Yeah, shouldn't have/need node-specific git users.  The container inherits $UID, and just calls regular `git` under the hood, I think, via yarn, but that is bombing because whoever $UID is isn't in the passwd config.  That said, git shouldn't bomb when this happens, I wouldn't think -- maybe a really old version of git?

@jmchilton That seems like a big clue, why the difference in UIDs from n4 to the others?

**Comment by martenson** [comment]
based on [this answer](https://stackoverflow.com/a/42529728) it seems git does need a user entry in `/etc/passwd`
