### ISSUE TITLE
HTML tags shown in Tool Shed "Export this revision"

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#593]
To reproduce:
1. Open Tool Shed in the browser
2. Select a random repository having repository dependencies
3. From "Repository Actions" menu select "Export this revision"
4. See HTML tags shown in the first line, e.g.: `The following additional repositories are required by revision 0:f048033da666 <i><font color="#666666">(2015-06-19)</font></i> of the abyss repository and they can be exported as well.` from https://toolshed.g2.bx.psu.edu/repository/export?repository_id=82ab1904790830ef&changeset_revision=f048033da666

I guess the error comes from https://github.com/galaxyproject/galaxy/blob/dev/templates/admin/tool_shed_repository/common.mako#L100

**Comment by hexylena** [comment]
@nsoranzo duplicate of #503? (Or if not a dupe, do we want to track all these issues in one place?)

**Comment by nsoranzo** [comment]
@erasche Not a duplicate. I've already added this bug to the Trello card mentioned in https://github.com/galaxyproject/galaxy/issues/503#issuecomment-125965335 .

**Comment by hexylena** [comment]
looking through old issues, the url is now broken, but the button/link is still there. Could be quick to remove that link in the dropddown?

**Comment by martenson** [comment]
With TS2.0 out I am closing this issue since we are not likely to work in its predecessor.
