### ISSUE TITLE
 UI bug starring outputs in workflows

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#5931]
Originally reported by @mtekman, present before and after we upgraded from 17.09 to 18.01

Un-toggling a starred output of a tool also untoggles (or appears to untoggle) other starred outputs if you mouseover and then mouseout on them

Steps to reproduce error:
 - Create a workflow
 - Add a random tool with multiple outputs (e.g. featureCounts)
 - Click on one of the outputs to star it
 - Click on another of the outputs to star it
 - Click on one of these starred outputs to unstar it
 - Mouseover the other starred output
 - Move mouse away
 - Both outputs are now unstarred

Note carefully the mouse clicks in this gif:
![out3](https://user-images.githubusercontent.com/20641402/39001278-33fd2648-43f6-11e8-8a8a-a608f4ff6b96.gif)

I believe he's using firefox on arch linux.

**Comment by mtekman** [comment]
Thanks @erasche  -- Firefox 59.0.2 (64-bit), if that helps

**Comment by jmchilton** [comment]
Can reproduce this on dev and with Chrome on Mac. Ugh... well thanks for the report.
