### ISSUE TITLE
cleanup scripts and config.ini -> config.yml

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#5941]
I have a kind of question/issue. Do the cleanup script need to be updated to the new yml config file? I guess this would be only the .sh files.

**Comment by nsoranzo** [comment]
The Python scripts should work without specifying the config file, e.g.:
```
cd GALAXY_DIR
. .venv/bin/activate
python scripts/cleanup_datasets/cleanup_datasets.py -d 10 -1
```
The `.sh` scripts should be updated to remove `./config/galaxy.ini` from the invoked Python command, would like to open a PR?

**Comment by bernt-matthias** [comment]
Could open a PR. But unsure since the config variables that derive from the parsed config seem to be used in the python script.

**Comment by nsoranzo** [comment]
The Python scripts have been updated to look for config/galaxy.(ini.yml)(.sample) in the appropriate order.

**Comment by bernt-matthias** [comment]
OK. PR ready which removes the parameter.
