### ISSUE TITLE
an API for exposing 'histories shared with me'

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#595]
Claus Børnich - author of https://play.google.com/store/apps/details?id=no.uio.bmi.claus has a usecase for it - you could inspect and give feedback on shared histories on your smartphone.
ping @Tarostar

**Comment by yhoogstrate** [comment]
I think this could be useful for Galaxy-Fuse as well

**Comment by martenson** [comment]
@yhoogstrate what is Galaxy-Fuse?

**Comment by yhoogstrate** [comment]
@martenson 
https://github.com/gvlproject/gvl_commandline_utilities
https://github.com/drpowell/galaxy-fuse

This tool allows you to mount all your galaxy histories as virtual folders. The file names of the histories and the history items are being preserved instead of dataset_000.dat

**Comment by bgruening** [comment]
@yhoogstrate we have something similar implemented in Galaxy Shell (gsh). Let me know if you wish to know something more about it.
