### ISSUE TITLE
upload dialog - search icon next to datatype non-functional

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#5950]
From @anuprulez 

> I fixed this error in [this PR](https://github.com/galaxyproject/galaxy/issues/5807) when I was doing hackthon with Dannon in this PR

Ignore the CSP warnings, only the last one is relevant:

![](https://raw.githubusercontent.com/anuprulez/issues/master/upload_error.png)

Reproducible on usegalaxy.*

**Comment by martenson** [comment]
That PR you linked is merged, so I assume you are asking for a backport? It might be not worth it, it is not even a search, it is just a 'description popover' 
![screenshot 2018-04-21 09 21 22](https://user-images.githubusercontent.com/1814954/39084526-7af8f6f8-4545-11e8-8f95-1c7787cdaf63.png)

**Comment by hexylena** [comment]
Yeah. Not sure it's worth a backport, just filing that this feature is broken on usegalaxy.* for 18.01. I've literally never used it but just filing because the optics may not be great for new users when simple things are non-functional, so someone might want to fix it.

**Comment by martenson** [comment]
We will have 18.05 soonish which has a fix for this in it. I am closing this issue since it does not qualify for backport I think. I will test if someone opens a backport PR though.
