### ISSUE TITLE
Can't edit component attributes when using use_remote_user

### ISSUE THREAD

**Issue by greenwoodma** [galaxyproject/galaxy#5955]
I've discovered a small issue with editing workflows when Galaxy is configured with `use_remote_user = True`. The problem is that if a user is directed straight to the workflow editor without having previously visited the Galaxy home page, then while they can add and remove components, they can't edit the attributes of components already in the workflow as clicking on a component results in an empty right hand side panel.

![image](https://user-images.githubusercontent.com/3025272/39119589-24be3f50-46e4-11e8-96e9-13ff53026d63.png)

As you can see we are using a slightly edited version of Galaxy, and this is based on 17.09, but I don't believe any of the changes we have made are responsible (I've actually backed out most of the changes during testing and the problem remains).

Clearly the proxy in front of this instance is working as the user is logged in correctly, but as I say unless they have visited the home page of the Galaxy instance this problem occurs. It is easy to replicate this using a private browsing session to first visit the workflow editor for an existing workflow and see that the attributes don't appear, then in another tab visit the home page, and then finally refresh the tab showing the editor, at which point everything works as intended.

I've tried to figure out what's going on but so far have had little success. There are no obvious errors in the console, or any network errors (i.e. no 404 or 403 responses). My guess is that something in the session isn't being set correctly if you don't first visit the home page. Unfortunately in our use case we don't want users going to any page but the workflow editor (hence the UI changes to remove access to the rest of Galaxy). I know we are using an older version of Galaxy but does anyone have any thoughts/suggestions as to what might be going wrong. I'm happy to poke around and try and provide a fix if someone can suggest where I should look.

**Comment by dannon** [comment]
@greenwoodma Thanks for the bug report here -- I've reproduced the problem locally and am taking a look.

**Comment by greenwoodma** [comment]
Thanks @dannon let me know if there is anything I can usefully do to help.

**Comment by dannon** [comment]
Just to update this ticket a bit, it looks like it's actually the load_workflow endpoint that isn't working correctly with remote user.  The config_form that's displayed in those panes is `null` in the response, when it should describe the forms.  I'm digging deeper, my guess is related to potentially not having a history set for trans; we've had similar issues in the past, though with this being a web controller endpoint (and not API), it shouldn't behave like this.

**Comment by dannon** [comment]
@greenwoodma This should be fixed now that #6075 is merged and merged forward.  Let me know if you have any other trouble with your remote user setup.

**Comment by greenwoodma** [comment]
Thanks @dannon. I've incorporated the change into our edited version of Galaxy 17.09 and it seems to work perfectly. Thanks again for looking at this so quickly.
