### ISSUE TITLE
toolshed does not have menu

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5961]
latest dev deployed on https://testtoolshed.g2.bx.psu.edu/
![screenshot 2018-04-23 14 18 58](https://user-images.githubusercontent.com/1814954/39145302-50258032-4701-11e8-854b-3f28701f61f3.png)

**Comment by dannon** [comment]
Well, this isn't great.  I'll take a look.

**Comment by dannon** [comment]
The toolshed generates the masthead in the custom base panels mako -- upgrading it now.
