### ISSUE TITLE
Library -> Rule Builder a bit broken still.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5967]
- [ ] Modal header implies you are uploading a collection.
- [ ] File type and genome selectors are available - but they shouldn't be since this doesn't create datasets just collections.
- [ ] Collection name column is missing so can't build multiple collections.

I'll open a bug fix PR for this against stable branch after branched. Sorry all.

**Comment by martenson** [comment]
Nurries mate, we will have plenty to fix during the freeze.
