### ISSUE TITLE
database migration problem

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5971]
while testing https://github.com/galaxyproject/galaxy/pull/5544 I got:

```
Exception: Your database has version '140' but this code expects version '141'. Please backup your database and then migrate the database schema by running 'sh manage_db.sh upgrade'.

$ sh manage_db.sh upgrade

AssertionError: There is no script for 141 version
```

**Comment by jmchilton** [comment]
You just need to clean out old pyc files I think?

**Comment by martenson** [comment]
@jmchilton that worked, sometimes it is starting to be a bit much when switching galaxy branches on macos: manual `kill -9` of old uwsgis that dont end, no-cache clean installations of uwsgi from pypi to avoid segfaults, various remnants of client builds and yarn.locks etc... :/

**Comment by HadleyKing** [comment]
Saving this here because for some reason I keep ending up back at this page....
;-)

> You just need to clean out old pyc files I think?


```
find . -name '*.pyc' -delete
```
> @jmchilton that worked, sometimes it is starting to be a bit much when switching galaxy branches on macos: manual `kill -9` of old uwsgis that dont end, no-cache clean installations of uwsgi from pypi to avoid segfaults, various remnants of client builds and yarn.locks etc... :/

Then `open ~/.bashrc`
Add
```
	#prevent Python from ever writing .pyc files
export PYTHONDONTWRITEBYTECODE=1
```
and `source ~/.bashrc`

**Comment by martenson** [comment]
@HadleyKing thanks for that tip, neat!
