### ISSUE TITLE
handsontable peer deps

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#5978]
dev startup

`warning " > @handsontable/vue@2.0.0-beta1" has incorrect peer dependency "handsontable@^0.38.1".`

**Comment by dannon** [comment]
xref #6166 we're intentionally going to go with the newer version of handsontable.  My expectation is that it's likely that's what handsontable/vue is going to be pinned against when it's out of beta, anyway.

(so, just ignore the warning for now)
