### ISSUE TITLE
job_conf dynamic with handlers section

### ISSUE THREAD

**Issue by selten** [galaxyproject/galaxy#5984]
Haivng a job_conf with a handlers section caused jobs not to be submitted to local or computing cluster. Even the configuration that used to be displayed in job_conf.xml.sample_basic before https://github.com/galaxyproject/galaxy/pull/5981 would not work.

Quote from @natefoo: 
> it's supposed to work around the case where the handlers section is set to the default like that, not sure why it's not working. =/

Example of a conf that wouldn't work:
```
<job_conf>
    <plugins>
        <plugin id="RUNNER" type="runner" load="galaxy.jobs.runners.drmaa:DRMAAJobRunner">
           <!-- Override the $DRMAA_LIBRARY_PATH environment variable -->
           <param id="drmaa_library_path"></param>
        </plugin>
    </plugins>
    <handlers>
        <handler id="main" />
    </handlers>
    <destinations id="lsf" default="dynamic">
        <destination id="dynamic" runner="dynamic">
            <param id="type">python</param>
            <param id="function">default_runner</param>
        </destination>
    </destinations>
</job_conf>
```

**Comment by martenson** [comment]
I think we have solved this with https://github.com/galaxyproject/galaxy/pull/5981 ?

**Comment by selten** [comment]
From my understanding, even if you define the handlers, it should submit the jobs. It doesn't do that. Therefore to my understanding there is an underlying issue somewhere that causes jobs not to be submitted in this scenario.

**Comment by hexylena** [comment]
I think the issue is it submits jobs, but you have to be running handlers with those names to process those jobs? So the documentation fix is correct, we shouldn't really be doing something strange if they have one handler defined and it's named 'main', that might be counterintuitive?

**Comment by selten** [comment]
I think maybe my idea on how it worked was incorrect. In 18.01 that configuration didn't submit jobs while it did work in 17.09. That was the odd part of this. I don't see this issue anymore though so I'm closing it.
