### ISSUE TITLE
Select behaviour in UI and tool test cases 

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#599]
I'm wrapping the bcftools suite, and there are many options that I'm leaving as "optional". I went about figuring out how I would test those both in Cheetah and test cases, and found some issues I'm having trouble resolving. 
## Example

``` xml
<?xml version="1.0"?>
<tool id="test" name="test" version="1.0">
  <description></description>
  <command>
echo $sec_default.annotations;
#if str($sec_default.annotations) is not "None":
    cat $sec_default.annotations >> $output;
#end if

echo $sec_default.int;
#if str($sec_default.int) != "":
    echo $sec_default.int >> $output;
#end if

echo $sec_default.s;
#if str($sec_default.s) != "":
    echo $sec_default.s >> $output;
#end if

echo $sec_default.so;
#if str($sec_default.so) != "":
    echo $sec_default.so >> $output;
#end if
  </command>
  <inputs>
    <section expanded="true" name="sec_default" title="Default Options">
      <param format="data" name="annotations" optional="True" type="data"/>
      <param name="int" optional="True" type="integer"/>
      <param name="s" optional="True" type="select">
          <option value="rot">Rot</option>
          <option value="blau">Blau</option>
      </param>
      <param name="so" optional="True" type="select">
          <option value="rot">Rot</option>
          <option value="blau" selected="True">Blau</option>
      </param>
    </section>
  </inputs>
  <outputs>
      <data format="txt" name="output" />
  </outputs>
  <tests>
      <test>
          <param name="annotations" value="ex1.txt" />
          <output name="output" file="ex1.o" />
      </test>
      <test>
          <output name="output" file="ex2.o" />
      </test>
      <test>
          <param name="int" value="32" />
          <output name="output" file="ex3.o" />
      </test>
      <test>
          <param name="s" value="rot" />
          <output name="output" file="ex4.o" />
      </test>
      <test>
          <param name="so" value="" />
          <output name="output" file="ex5.o" />
      </test>
  </tests>
  <help>asdf.</help>
  <expand macro="citations"/>
</tool>
```
## Test Cases

My test cases look like:

| Test Case | Expected output |
| --- | --- |
| ex1.o | contents of ex1.txt + "\nblau" |
| ex2.o | "blau" |
| ex3.o | "32\nblau" |
| ex4.o | "rot\nblau" |
| ex5.o | <empty> |

**4/5 test cases fail**

The actual output is in illuminating:

| Test Case | Expected Output | Actual Output |
| --- | --- | --- |
| ex1.o | contents of ex1.txt + "\nblau" | contents of ex1.txt + "\nrot\nblau" |
| ex2.o | "blau" | "rot\nblau" |
| ex3.o | "32\nblau" | "32\nrot\nblau" |
| ex4.o | "rot\nblau" | "rot\nblau" (passes) |
| ex5.o | <empty> | `Error creating a job for these tool inputs - {u'type': u'error', u'data': {u'sec_default': {u'so': u"An invalid option was selected for so, u'', please verify."}}}` |
## Takeaways
- optional selects, without a default value specified, take their first value. 
  - I think this is wrong, and is 3/4 of my failures above. 
  - This is how the UI behaves. I think this is likewise a bug, as I expect the "No selection" as the default if I don't specify a default and say `optional="True"`. Until then I'm going to have to manually provide a "No selection" option just so I can use it in test cases and cheetah.
- I cannot find a way to specify that a test case should select the UI default of "No selection". I've tried:
  - `""`
  - `"None"`
  - `"none"`
  - `"null"`

**Comment by nsoranzo** [comment]
I think `optional="true"` was never supposed to work with selects, as the UI implies. It is instead the default if `multiple="true"`.

I'd say: not a bug.

**Comment by hexylena** [comment]
Why shouldn't it work with a select?

If you have `optional="True"` the UI automatically supplies a `No selection` element for you, and I seem to remember it defaulting to it (but I may be wrong on that count). The bug is more that the existing feature cannot be tested.

Assuming this is the intended functionality of optional parameters on selects, the UI can make use of the automatically generated option to perhaps supply a localized "No selection" string (someday).

**Comment by nsoranzo** [comment]
Ah, the `No selection` option is new in 15.05, it was not here in 15.03 and previous releases. Maybe it should be removed before a complete implementation is provided.

Edit: I got the versions wrong, it's also in 15.05.

**Comment by hexylena** [comment]
@nsoranzo, no, it's not new. (Well the text "No selection" is new compared to "Nothing selected")

I booted up 15.01, with the old tool form (couldn't quite get 14.10 to start/wasn't worth the effort).

![nope](https://cloud.githubusercontent.com/assets/458683/9254908/b609c588-41ab-11e5-8352-fdd02b45c6e8.png)

**Comment by nsoranzo** [comment]
I've tested again on 15.01 using toolshed.g2.bx.psu.edu/repos/iuc/bedtools/bedtools_closestbed/2.22.0 , which has 2 optional selects, and there is no "Nothing selected", probably because both selects have one option with `selected="True"`. So I wouldn't say it was working properly.

Anyway, we just need to make it work now (or disable it).

**Comment by hexylena** [comment]
Okay, sounds good. :)

Edit; I'm fine with either, but I'll patch my tools in the short term to have a custom NOP, "Nothing selected" option that's set as default.
