### ISSUE TITLE
Add option to mark a dataset in error or failed state as "ok"

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#5998]
On our instance we sometimes encounter that jobs fail but the dataset is **ok** 
(generally this is caused due to the way our SLURM reports OOM events (but not the only reason)).

Of course its better to resolve the underlying problem, however, it would be great if the user or the admin at least, has the option to mark a failed dataset to be "ok" so it can be used in further analysis without rerunning the tool again, consuming again resources and worse, waiting for the same dataset to be completed.

**Comment by hexylena** [comment]
Thanks for the issue @scholtalbers, closing as 

duplicate of https://github.com/galaxyproject/galaxy/issues/4021
