### ISSUE TITLE
18.05 Central pane grid sizing overlap

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#6002]
Some undesired overlap with the page elements:
![image](https://user-images.githubusercontent.com/338642/39368733-65bcb0e6-4a08-11e8-9694-8872b219ab8f.png)

**Comment by afgane** [comment]
One more: the upload button tooltip does not clear after the modal opens:
![image](https://user-images.githubusercontent.com/338642/39369304-ed0635e4-4a09-11e8-95f5-25d0b538ff30.png)

**Comment by afgane** [comment]
On the tooltips topic, the `View data` tooltip on a dataset does not clear after clicking the button:
![image](https://user-images.githubusercontent.com/338642/39369564-a8c695c6-4a0a-11e8-8159-08dd5b664a20.png)

It does not do this for `Edit attributes` button.

**Comment by martenson** [comment]
We might want to consider changing the default, since our design really does not expect tooltips being stuck
![screenshot 2018-04-27 11 13 30](https://user-images.githubusercontent.com/1814954/39370117-19c31ac8-4a0c-11e8-92e8-626dc1792b37.png)
