### ISSUE TITLE
Gviz rtracklayer IdeogramTrack

### ISSUE THREAD

**Issue by mrlmachado** [galaxyproject/galaxy#6008]
I found myself now without any ideas for solving what I faced in my local galaxy server. I'm runing version 18.01 of galaxy with nginx and interactive environment enabled and I build a tool with Gviz package dependency resolving by conda. Galaxy resolve all dependencies correctly but when I call IdeogramTrack function from R it throws a Bad Request 400 Error only within galaxy environment. If I execute from the server with Rscript, my code runs perfectly. I tried disable GIE and enable debug level of logs from nginx and wsgi but no success to find what is causing this error. I know this function call ucsc uri to download hg tables, but it works from the very server where galaxy is running and within galaxy it does not work. I really need help here to understand what is happening and how can I solve this out.

Attached is the xml tool definition file and the R script. To run the script I used the parameters in the tests section of the tool definition xml file. I used a local data table too, with a data manager to download hg19 to use as fasta reference with galaxy.
[gviz.tar.gz](https://github.com/galaxyproject/galaxy/files/1956822/gviz.tar.gz)

**Comment by mrlmachado** [comment]
Sorry for the delay, now I'm posting the STDERR from Galaxy job. It's in portuguese, if any translation is required, please ask.

`

Stderr
---
Carregando pacotes exigidos: methods
Carregando pacotes exigidos: S4Vectors
Carregando pacotes exigidos: stats4
Carregando pacotes exigidos: BiocGenerics
Carregando pacotes exigidos: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, cbind, colMeans, colnames,
    colSums, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, lengths, Map, mapply, match,
    mget, order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rowMeans, rownames, rowSums, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which, which.max, which.min


Attaching package: ‘S4Vectors’

The following object is masked from ‘package:base’:

    expand.grid

Carregando pacotes exigidos: IRanges
Carregando pacotes exigidos: GenomicRanges
Carregando pacotes exigidos: GenomeInfoDb
Carregando pacotes exigidos: grid
Carregando pacotes exigidos: GenomicFeatures
Carregando pacotes exigidos: AnnotationDbi
Carregando pacotes exigidos: Biobase
Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.


Carregando pacotes exigidos: XVector

Attaching package: 'Biostrings'

The following object is masked from 'package:base':

    strsplit

Starting read the DNA sequence from fasta reference file: /home/galaxy/galaxy/tool-data/hg19/seq/hg19.fa
Fasta reference file processed:  /home/galaxy/galaxy/tool-data/hg19/seq/hg19.fa
Iniciando o sequence Track
Importando Rsamtools
Indexando o bam
Iniciando o pdf
Plotando o pdf
Checking associations
Association found, getting axis track
Applying names to ranges names
Setting chr number to track
Setting Ideogram track
Starting get the ideogramtrack on genome hg19 and chromosome chr5
Error getting the ideogramtrack
Here's the original error message:
Bad Request
Ideogram track function processed: 
setting chr to each level of ideogram track
Error in plotGviz(sTrack, ref_genome, txdb, annotation, chr, pos, bams,  : 
  tentativa de obter um slot "bandTable" de um objeto de uma classe básica ("logical") sem slots
Apagando arquivos

`

**Comment by mrlmachado** [comment]
After all I found what it was the issue. It was related with rtracklayer version and Gviz version in bioconda recipes. I submitted a pull request for both to update their versions and it worked. https://github.com/bioconda/bioconda-recipes/pull/8764 and https://github.com/bioconda/bioconda-recipes/pull/8765 

Thanks for all the time people tracking this and specially to @bgruening

**Comment by dannon** [comment]
@mrlmachado Great, glad it's sorted!
