### ISSUE TITLE
Filter Failed tool in workflow coerces wrong noodle type when connecting collection data

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/galaxy#6012]
Hi, I'm not sure whether this is really a bug with a workflow, or an issue with these specific tool inputs.

1 .Connecting a Collection output to a tool expecting multiple inputs:

  * Tool1 → {1:N} → Tool2 → {N:N} → ToolN.

![edited_1](https://user-images.githubusercontent.com/20641402/39426510-78fe946a-4c80-11e8-9a07-4245b98ce838.gif)

2. Connecting a Collection output to `Filter_Failed` and then connecting to a tool expecting multiple inputs:

  * Tool1 → {1:1} → FilterFailed → {1:N} → Tool2 → {N:N} → ToolX
  * (This is what I expect to be working fine)

![edited_2](https://user-images.githubusercontent.com/20641402/39427341-b302f5cc-4c83-11e8-913e-e1da41b1a5f9.gif)

3. However, the workflow does not actually like the above arrangement because any attempts to create more output noodles are refused (causing the tool to be dragged instead).

  * Tool1 → {1:1} → FilterFailed →  {1:N} → Tool2  → {N:N} → Stuck!

![edited_3](https://user-images.githubusercontent.com/20641402/39426827-a508da10-4c81-11e8-922a-d5b9003914f6.gif)

4. Attempting to rectify this by linking downstream tools first via 1:1 noodles, and then linking Filter Failed tool does not work:

 * Tool1 → {1:1} → FilterFailed → {Stuck!} → Tool2 → {1:1} → ToolN

![edited_4](https://user-images.githubusercontent.com/20641402/39426949-2503016e-4c82-11e8-9279-583b2462dd38.gif)

 * Tool1 → {Stuck!} → Tool2 → {1:1} → ToolN 

![edited_5](https://user-images.githubusercontent.com/20641402/39427062-a2b5e52c-4c82-11e8-87d5-deb2b77c4897.gif)

5. Unlinking all and re-linking as per our initial setup works fine:

    * Tool1 → {1:N} → Tool2 → {N:N} → ToolN.
![edited_6](https://user-images.githubusercontent.com/20641402/39427116-e47a34ae-4c82-11e8-8580-5707dbd42719.gif)

**Comment by guerler** [comment]
Possibly related to #5205

**Comment by mvdbeek** [comment]
I should have a fix for this soon. xref https://github.com/galaxyproject/galaxy/issues/6514

**Comment by mvdbeek** [comment]
Pretty sure this should be fixed in 19.01.
