### ISSUE TITLE
( or ) in workflow labels break subworkflows. 

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#6031]
[original title Workflow becomes unloadable after marking outputs as workflow output]

I created a parent workflow with two subworkflows. Once one of the parent workflow outputs was "marked as a workflow output", the workflow became broken. I could save it, but not load it or run it. I've attached the offending workflow:

[Galaxy-Workflow-ehunter__TnSeq-20180501_compare_groups_-_broken.ga.tar.gz](https://github.com/galaxyproject/galaxy/files/1965149/Galaxy-Workflow-ehunter__TnSeq-20180501_compare_groups_-_broken.ga.tar.gz)

**Comment by mvdbeek** [comment]
Can you try this without ( or ) in the labels ? We need to sanitize this better

**Comment by lparsons** [comment]
I downloaded the workflow as a file. Uploading it resulted in the same broken behavior. However, I edited the txt file and replaced all `(` and `)` with `_` and loaded it and everything worked as expected. I would say that somewhere, there are issues with escaping characters. Good guess @mvdbeek !
