### ISSUE TITLE
Unable to add workflow to tools menu

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#6033]
Checking the box next to a workflow in the workflow list appears to submit a for (and reload the page), but no error occurs (in the log either), the checkbox goes back to unselected, and the tool menu doesn't change (the workflow is not added). Version 17.09.

**Comment by mvdbeek** [comment]
This works on 18.01/18.05 and I remember we've worked on this in 17.09. Any chance updating to the latest commit on 17.09 solves this ?

**Comment by lparsons** [comment]
I am on the latest 17.09, will try to update to 18.01 soon and update this issue.

**Comment by lparsons** [comment]
This seems to work in 18.05 at least.
