### ISSUE TITLE
server error when download collection item through the 'save' icon

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6035]
I suspect the endpoint is exposed only 'anonymous' since normal datasets don't need authentication, but for collection items you do.

This is the save icon on the expanded  detail of dataset, not on the collection header.

xref https://github.com/galaxyproject/galaxy/issues/5629

**Comment by jmchilton** [comment]
Seems likely that this is restricted to just nested collections. Still bad though and should be fixed.

**Comment by mvdbeek** [comment]
You're downloading through a regular browser session ?

**Comment by martenson** [comment]
@mvdbeek correct
