### ISSUE TITLE
rulebuilder regex handling 

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6038]
When trying to apply the following regex @Delphine-L gets the following error in the console (and nothing happens in UI):

But e.g.  'create column matching expression' seems to work.

![screen shot 2018-05-02 at 11 18 13 am](https://user-images.githubusercontent.com/1814954/39532359-b09db830-4dfa-11e8-933d-beef0aabc4b7.png)

**Comment by martenson** [comment]
The problem seems to be related to the actual regex, for some other uses I am able to create column from regex replacement but with `005` as input regex on the ftp path column (only some of the rows contain '005') it goes into this error (and it will log this thousands of times until the browser tab expldoes)

**Comment by jmchilton** [comment]
I'll fix the error handling, but from a functionality perspective that expression needs to match every row. If it doesn't one can use the filter by regex first and then do this. If you do want to keep all the rows and apply this regex to only some of them - the regex needs to be more sophisticated.

**Comment by jmchilton** [comment]
I'm going to open a fix that makes the following happen if the regex doesn't match one or more rows:

<img width="828" alt="screen shot 2018-05-02 at 12 00 23 pm" src="https://user-images.githubusercontent.com/216771/39535036-e60dc2f2-4e00-11e8-8492-84a1020bc99a.png">

**Comment by martenson** [comment]
lgtm
