### ISSUE TITLE
history link in error mails gives only json

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6049]
When galaxy sends me error reports via mail the link that should lead to the history gives me only json (link looks like http://141.65.122.16:8080/history/view/0ac9e5567ab6a667) and the result is 
![screenshot from 2018-05-03 10-10-08](https://user-images.githubusercontent.com/25689525/39566083-a8b2a19c-4eba-11e8-900e-969a3867950f.png)

Happens in firefox and chromium.

**Comment by dannon** [comment]
@bernt-matthias Which version of Galaxy is this?  I'll take a look, should be an easy fix.

**Comment by bernt-matthias** [comment]
Its a quite up to date dev branch. If you need to know exactly its this fork https://github.com/bernt-matthias/galaxy.

**Comment by dannon** [comment]
@bernt-matthias Thanks for the info, checking into it now.

**Comment by dannon** [comment]
@bernt-matthias #6051 should fix your problem when it's applied and merged forward.  Thanks for reporting this!
