### ISSUE TITLE
collection dropdown menu renders under elements

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6077]
![screenshot 2018-05-07 16 03 51](https://user-images.githubusercontent.com/1814954/39722347-5fedce1a-5210-11e8-8368-916d83870dd3.png)

**Comment by martenson** [comment]
this seems to happen only in the history multiview

**Comment by martenson** [comment]
@jmchilton this is the part you liked about bs4, right? :D

**Comment by dannon** [comment]
Should be a trivial fix.  I'll take a look.

For what it's worth, many of these were broken because the framework expects a standard set of z-index settings and we had overridden them in a lot of places.

**Comment by martenson** [comment]
@dannon agreed, we shouldn't mess with the z-index, thanks for fixing it
