### ISSUE TITLE
Kubernetes (k8s) runner should instantiate GALAXY_SLOTS env var for job

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#6083]
Currently the k8s runner can receive resource usage settings from either a dynamic destination or from the user interface, and while this is being used to set the `limits` and `requests` of the created k8s job, we are not are not making use of the CPU boundaries to set the GALAXY_SLOTS var.

**Comment by jmchilton** [comment]
Was this fixed?

**Comment by mvdbeek** [comment]
Yes, in https://github.com/galaxyproject/galaxy/pull/6958
