### ISSUE TITLE
`formatter: generic` line in `galaxy.yml` logging section makes Galaxy fail to start

### ISSUE THREAD

**Issue by TamsenSpelchak** [galaxyproject/galaxy#6086]
While setting up advanced logging for a Galaxy instance by following [this](https://docs.galaxyproject.org/en/release_18.01/admin/config_logging.html#yaml) documentation, I've noticed that Galaxy refuses to start up if the line `formatter: generic` is placed in the `logging` section of `galaxy.yml` as it is in the second example. While trying to start up, Galaxy instead throws the following error:
```
ValueError: Unable to configure handler 'console': Unable to set formatter 'generic': 'generic'
```

Removing the `formatter: generic` line seems to fix the issue for me,  as once I do Galaxy correctly starts up and creates and writes to logfiles corresponding to its handlers, rather than one large file.

Is this just an issue of the documentation being out of date, or is there perhaps something wrong with the way Galaxy is parsing/handling the `logging` section in `galaxy.yml`?

**Comment by TamsenSpelchak** [comment]
Upon further inspection, it seems the error only occurs when running Galaxy via `uwsgi`, like so:

```
uwsgi --plugin python --virtualenv [path/to/venv] --yaml [path/to/galaxy.yml]
```

**Comment by martenson** [comment]
we no longer support uwsgi so this issue is likely outdated
