### ISSUE TITLE
making a copy of large history takes 30m+

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6113]
'cog' wheel -> copy history

You'll get backend timeout from Galaxy after some time, presented as red error modal in frontend. But the copy process actually runs and if you keep checking the saved-histories page you will sse it grow. 

For history with lower thousands of datasets this takes ~30m. This seems too long, especially when there shouldn't be any physical copying I think.

reported by @Delphine-L

**Comment by dannon** [comment]
This is a perfect example of the kind of endpoint we'd want to flag and surface with the slow request timing.  I'm going to tinker with what we talked about yesterday, adding different 'severity' tags on the response timing logged to sentry.

**Comment by lecorguille** [comment]
Some copies from shared histories can take several hour (around 40k files).
I don't know if it's some latency around the DB, or the server itself which need to deal with a lot of API instruction ??

**Comment by mvdbeek** [comment]
I suppose that'll be much better with https://github.com/galaxyproject/galaxy/pull/6531, which will be in 18.09
