### ISSUE TITLE
Upload datatype sniffer problems: fasta and numerical tabular

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6116]
At usegalaxy.org under pre-release 18.05

test history: https://usegalaxy.org/u/jen/h/test-history-upload-and-peek-view-scroll

problem: fasta is assigned to "align" (should be fasta) and numerical tabular is assigned to "otu_map" (should be tabular).

fastq, gft, alphanumeric tabular == all ok

<img width="249" alt="screen shot 2018-05-10 at 11 54 48 am" src="https://user-images.githubusercontent.com/8999735/39888428-a16b4d50-5449-11e8-8697-05eae17590c8.png">

ping @guerler 

Was originally testing the scrolling for peek view with different datatypes. Am ticking issues with that and will link back.

**Comment by jennaj** [comment]
@jmchilton @guerler Are the most current updates to upload/autodetect on main now? There are still problems with very common datatypes. Do we need to even autodetect `otu_map`? **Seems to be causing problems when the first column is numerical in `tabular` or `gtf` data.**

No idea why and the result seems to differ by the GTF source/chromosome naming/header-or-not.

Users had reported getting `gff` autodetected instead of `gtf`, and I had seen that before too when the `gtf` had comment/header lines. One reported that `gff` was auto-assigned for Ensemble GTFs even without the headers. But, I'm getting the datatype `otu_map`. 

**`fasta` is still auto-detected as `align`. This seems important to correct as well.**

Test history: https://usegalaxy.org/u/jen/h/test-history-upload-fasta-gtf-bam-sam

<img width="246" alt="screen shot 2018-05-15 at 1 05 47 pm" src="https://user-images.githubusercontent.com/8999735/40080894-4a0528aa-5841-11e8-991b-4cd064f856f6.png">

Next loaded the same data again but with a different name to see if that made a difference. It's not supposed to, and it didn't, which is some good news :)

**Comment by jennaj** [comment]
Oh, and loading datasets with the same name again still broken with upload (doesn't even get loaded into the Upload queue). Is this fix still pending?

**Comment by jmchilton** [comment]
I don't know what the align datatype is - but it isn't in Galaxy proper. Maybe it is a tool shed datatype? Can we uninstall that (@natefoo / @davebx ) or is there a way to disable sniffing of a tool shed datatype? You example fasta file sniffs as fasta with a clean release_18.05 - so that isn't a framework issue I don't think?

**Comment by jennaj** [comment]
align is related to the Mothur tool suite, the same as out_map. I think you are right about the shed datatypes... maybe better to not use these with Upload on Main?

very good news that a default test 18.05 doesn't do this -- lowers the impact for everyone else.

**Comment by martenson** [comment]
mothur does not seem to have its own datatypes in the ts repository, it has some in the sample though, e.g. a subclass of fasta: https://github.com/galaxyproject/galaxy/blob/release_18.05/config/datatypes_conf.xml.sample#L579

**Comment by jmchilton** [comment]
> align is related to the Mothur tool suite, the same as out_map

Ah - it is called something else in the distro. I think we just need to uninstall the tool shed datatypes but this will break older copies of mothur. I don't think this is avoidable with tool shed datatypes though.

As for the otu problem....

Here is our test example otu file?

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/test/mothur_datatypetest_false.mothur.otu

Here is the sniffer:

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/mothur.py#L81

@shiltemann Is there anything we can do to tighten up this sniffer? Are any of these values like "label" "numOtus" always populated for instance? If not do you have opinions about just removing it from the sniffer list?

@jennaj There are always going to be problems with sniffing tabular - it is the default if all other sniffers have failed and it is tabular data - so we can maybe remove this datatype or make it tighter but some other datatype is going to match after that I suspect. People really should be encouraged to set datatypes IMO, especially if the desired result is tabular. If it is affecting gtf/gff files though that is quite fixable I think - we could probably just move the mothur sniffers after the gtf/gff sniffer.

**Comment by jennaj** [comment]
Retesting this

**Comment by shiltemann** [comment]
sorry, this got lost in my notifications, I have another branch tightening up one of the other mothur datatype sniffers, will go through them all to see where we can be more stringent. Also yes, I am ok with removing sniffers for ones that are too general, such as align or some of these tabular formats.

**Comment by jennaj** [comment]
`fasta` sequence is still autodetected as `align`. Getting this right seems important.

@natefoo Did the toolshed datatypes removal/fix get applied to main yet?

@jmchilton @shiltemann Am considering the fix for "`tabular` detected as `otu_map`" as a nice to do, but lower priority than `fasta`.

All retests in the same history as above

**Comment by natefoo** [comment]
What's being proposed here? Should I be removing all mothur datatypes?

**Comment by shiltemann** [comment]
@natefoo the "new" mothur datatypes shipped with Galaxy all have a prefix of `mothur.` so these reported by @jennaj appear to be old definitions, probably once included in toolshed mothur repo. Since I don't see these old versions of the tool installed on main I think it is safe to remove them. As for the current ones, I will tighten up the sniffers, and can remove some of the too-generic ones since I think 90% of people will start analysis with fasta files and not mothur datatypes anyway and not unreasonable to ask people to set datatype manually.

P.S. only a small number of the mothur tools seem to be installed currently on main?

**Comment by natefoo** [comment]
@shiltemann ok thanks!

I'm not sure why only a few are installed. Maybe some aren't loading correctly? I'll have a look.

**Comment by natefoo** [comment]
After digging through the code, I think the only "proper" way to disable shed datatypes is to uninstall the tool? Anyway, I have disabled them by renaming the old (JJ) mothur repo's datatypes_conf.xml on disk. For the record, those versions of the tools are still installed, they're just hidden so they can still be rerun or run from old workflows. So this may make such reruns/workflows inoperable. It certainly produces some fun output on startup:

```
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,433 Datatype class not found for extension 'tre', which is used in the 'format' attribute of parameter 'tree'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,433 Datatype class not found for extension 'groups', which is used in the 'format' attribute of parameter 'group'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,434 Datatype class not found for extension 'names', which is used in the 'format' attribute of parameter 'name'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,434 Datatype class not found for extension 'count_table', which is used in the 'format' attribute of parameter 'count'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,450 Datatype class not found for extension 'seq.taxonomy', which is used in the 'format' attribute of parameter 'taxonomy'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,452 Datatype class not found for extension 'count_table', which is used in the 'format' attribute of parameter 'count'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,466 Datatype class not found for extension 'oligos', which is used in the 'format' attribute of parameter 'oligos'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,467 Datatype class not found for extension 'seq.taxonomy', which is used in the 'format' attribute of parameter 'taxonomy_in'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,467 Datatype class not found for extension 'names', which is used in the 'format' attribute of parameter 'name_in'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,467 Datatype class not found for extension 'groups', which is used in the 'format' attribute of parameter 'group_in'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,495 Datatype class not found for extension 'list', which is used in the 'format' attribute of parameter 'otu'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,495 Datatype class not found for extension 'shared', which is used in the 'format' attribute of parameter 'otu'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,496 Datatype class not found for extension 'names', which is used in the 'format' attribute of parameter 'repname'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,496 Datatype class not found for extension 'count_table', which is used in the 'format' attribute of parameter 'count'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,496 Datatype class not found for extension 'groups', which is used in the 'format' attribute of parameter 'group'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,510 Datatype class not found for extension 'list', which is used in the 'format' attribute of parameter 'otu'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,510 Datatype class not found for extension 'sabund', which is used in the 'format' attribute of parameter 'otu'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,511 Datatype class not found for extension 'count_table', which is used in the 'format' attribute of parameter 'count'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,523 Datatype class not found for extension 'align', which is used in the 'format' attribute of parameter 'fasta'
galaxy.tools.parameters.basic WARNING 2018-05-26 22:38:35,523 Datatype class not found for extension 'names', which is used in the 'format' attribute of parameter 'name'
... 
```

**Comment by jennaj** [comment]
Retested in same test history in first post, datasets 21-22-23

fasta = autodetects correctly
gtf = autodetects correctly
numerical tabular = autodetects as interval, probably Ok, would be difficult to not sniff this data that way.

Closing this out, thanks!!
