### ISSUE TITLE
Maybe backoff history polling?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#6118]
![auswahl_124](https://user-images.githubusercontent.com/458683/39925498-73044e44-551b-11e8-9981-65eb45bdcbb4.png)

My history has datasets that are entirely in terminal states. Maybe we should back off the polling if there's nothing that's non-terminal? Since (unfortunately) users can't collaborate on a single history, it might make sense to decrease load.

**Comment by martenson** [comment]
The frontend does not have the full information on what datasets are being created, so we cannot stop I think. We could increase the interval when everything appears terminal though.

**Comment by hexylena** [comment]
yeah, exactly, just back off the requests, don't stop them. I would not expect that since we don't have websockets/server sent events.

**Comment by martenson** [comment]
I've tested this on multiple histories in multiple situations both on dev and Main and this actually works well for me. Once everything is in terminal state it completely stops sending history ajax requests. Could you please share a history where this is not the case @erasche ?

**Comment by natefoo** [comment]
I think backoff here means increase the interval between requests. So you start at some very small interval and then after a while if the datasets are non-terminal, you increase the interval by some increment over some time up to some maximum value. We do this in GIE spinning, for example. I think this would be a really good thing to do.

Adding new datasets (queueing new jobs) probably ought to reset the interval to its initial value.

**Comment by martenson** [comment]
@natefoo but @erasche above claims everything is in terminal state

**Comment by natefoo** [comment]
Oh hey reading is good.

**Comment by martenson** [comment]
Alright so the forever-polling seems to happen when you have at least one collection in the history. No matter what the state is.

**Comment by hexylena** [comment]
Should be fixed with new history menu #8441

**Comment by mvdbeek** [comment]
it has to, this is fine though and we disable polling when the window/tab is inactive. https://github.com/galaxyproject/galaxy/issues/14317 has a much higher impact

**Comment by hexylena** [comment]
Not polling in inactive tabs is great!

Does it have to poll as often though? It surely doesn't need to be every second for an empty history, it's a lot of noise. 

I guess my proposal here was something like "as long as there is no change in state, increase check frequency from 1s to 15s or similar (even while active.) Since you can tell on e.g. job submission that you need to reset the backoff.

**Comment by mvdbeek** [comment]
> Does it have to poll as often though? It surely doesn't need to be every second for an empty history, it's a lot of noise.

it's not every second, and yes, we should.



> I guess my proposal here was something like "as long as there is no change in state, increase check frequency from 1s to 15s or similar (even while active.) Since you can tell on e.g. job submission that you need to reset the backoff.

given this almost never appears in any of the relevant stacks I would say this is premature optimization.

**Comment by hexylena** [comment]
Alright. I'm not sure I see the case for polling an empty history regularly (I guess I'm missing would be changing that would be caught by a poll, that wouldn't be user-initiated like an upload/tool run) but if it's not relevant it's not relevant.

**Comment by mvdbeek** [comment]
Everything is driven by the API these days (so not necessarily from the same tab/window/browser), we have external upload scripts that populate histories, we have workflows starting scheduling in the background. I'm not saying we shouldn't consider it, but only after the more urgent things are addressed.
