### ISSUE TITLE
[GDPR] History import bugs

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#6120]
I produced [this script](https://github.com/galaxyproject/bioblend/issues/262) which downloaded my history (note the explicit request for include_hidden, include_deleted.)

And I got this out:

![auswahl_126](https://user-images.githubusercontent.com/458683/39927648-7b093350-5522-11e8-9cd7-aa21afe57a06.png)

- [ ] Deleted datasets were dropped completely
- [ ] History tags were not imported (included in `history_attrs.txt`)
- [ ] Dataset tags were not imported (included in `dataset_attrs.txt`)
- [ ] "Size on disk" is zero/wrong
- [ ] Job metrics are completely missing :(
- [ ] API does not give back a future-history-id so I'm unable to automatically correct the name. (Also frustrating that I can't tell if it's "done" or not (assuming active use of the account) so I guess I'll just tell the target galaxy to handle 300 histories at once? (Sure, I could do some sort of check for how many histories now vs when started, but that's not optimal under active use scenario)
- [ ] Failed datasets were marked as successful (despite including `state: "error"` in `job_attrs.txt`)

    ![auswahl_125](https://user-images.githubusercontent.com/458683/39927698-9ef2b782-5522-11e8-85fa-e6e6a5f841fb.png)

- [ ] I tried adding some history + dataset annotations + dataset tags to see if those would work, but galaxy immediately returned the new history archive, not recognising that things were different.
- [ ] Deleting successful datasets also does not permit a new archive download

xref #6082

**Comment by mvdbeek** [comment]
This has changed a ton, I think we can close this
