### ISSUE TITLE
Upload naming issues

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#6138]
From galaxy-bugs:

with latest release if you upload a file via browser but  then repeat the process, say if you needed to edit the file and reupload, the dialog box will not populate unless the filename is changed.  In other words, 
get data-->choose local file--> FILENAME --> success
 REPEAT 
get data-->choose local file--> FILENAME --> empty screen, nothing happens
get data-->choose local file--> FILENAME_1 --> success

**Comment by jennaj** [comment]
Was this applied to usegalaxy.org already? I am still seeing the problem. 

There is slightly different behavior - using "reset" in Upload used to be a workaround to allow the same dataset to be loaded. Now reset doesn't do that - no workaround.

ping @guerler & @dannon (saw that you tested it, so maybe main just needs an update?)

**Comment by guerler** [comment]
This was fixed for dev in #6168.

**Comment by jennaj** [comment]
Double checked fix was still in place for pre-release 18.09 at ORG - it is, thanks!
