### ISSUE TITLE
Interactive Environments Fail When `:` in Dataset Name

### ISSUE THREAD

**Issue by TamsenSpelchak** [galaxyproject/galaxy#6143]
Hello,

I've found that when I try to launch an interactive environment user Docker, if the mount location of one of the volumes contains a colon character (`:`), then the docker host will error out creating the container.

This naming scheme commonly occurs in Galaxy when the user-facing name of the dataset contains a colon.

 This error is outputted in Galaxy's log.:
```
docker: Error response from daemon: invalid volume specification: '/path/to/data/000/dataset_739.dat:/import/[1467] Prokka on data 1: gff.gff:rw'.
```

It seems that this occurs because Docker uses the colon character to delimit volume source, target, and mode in its command line syntax.

**Comment by dannon** [comment]
(xpost from IRC) did a little digging and it looks like the real fix here is to swap to the `--mount` syntax.  `-v` doesn't support colons.  I'll take a stab at this later.

**Comment by hexylena** [comment]
we could `re.sub()` the filename when linked into the container. It would make sense to remove `[:/]`

**Comment by dannon** [comment]
@erasche Thought about that, but the advice I saw in most places was that `-v` should be deprecated and swapped out anyway, so that's what I'm going to do once 18.05 ships.  (it'll be a more robust fix in the long term)

**Comment by hexylena** [comment]
`-v` should be deprecated? For what? (Edit: apparently `--mount`?)

**Comment by hexylena** [comment]
> However, starting with Docker 17.06, you can also use --mount with standalone containers

Just consider that this may not be desirable for some admins. Some of us aren't on dockers that new yet. (e.g. my GIE machine is SL6 which only has docker 1.7.1)

(That said I'm all for forcing people to upgrade their docker.)

**Comment by dannon** [comment]
@erasche Yeah, `--mount`.  I guess we could check the version and just try the older syntax, too, if we need to support old docker versions.

**Comment by hexylena** [comment]
I feel like smallest amount of work with greatest compatibility would be to continue to use legacy mount syntax and just munge filenames. The new syntax looks like it's focused on other use cases like mounting directly from NFS server, not a huge priority for us at least? As you like, if you have time for new mount syntax + version detection, maybe another group would find this useful

**Comment by dannon** [comment]
@erasche I need a https://caniuse.com/ for Docker, argh.  Yeah, I'll do a little more digging on what to expect people will actually be running.  I figured folks would keep a very modern docker, just for security/etc., but maaaybe I'm too optimistic.

**Comment by hexylena** [comment]
Oh yeah, caniuse for docker would be *super* nice. Have encountered those issues before. Security? What's that again? (Yeah, I'll upgrade docker when I move to a swarm cluster or something. I meant to do that when @natefoo was here but we didn't get around to it in time.)

**Comment by natefoo** [comment]
If you enable the beta containers interface it'll use the Docker API to create the container, which should hopefully not have this problem.

**Comment by hexylena** [comment]
I guess this is fixed with combination of future plans / new volume tihng / beta container interface.
