### ISSUE TITLE
Hashed dataset tags are displaying in tool selects with "name:" included

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6147]
Not sure if this has been reported or not yet ... ping @dannon 

<img width="626" alt="screen shot 2018-05-15 at 5 07 15 pm" src="https://user-images.githubusercontent.com/8999735/40089839-dc2dad9e-5862-11e8-933f-e30995bde6e7.png">

<img width="621" alt="screen shot 2018-05-15 at 5 08 20 pm" src="https://user-images.githubusercontent.com/8999735/40089840-dc46239c-5862-11e8-8531-63fd93901396.png">

**Comment by jennaj** [comment]
Also shows up in Saved Datasets:

<img width="380" alt="screen shot 2018-05-15 at 5 11 59 pm" src="https://user-images.githubusercontent.com/8999735/40089895-2af553d2-5863-11e8-97c8-1ffec5cae319.png">

**Comment by jennaj** [comment]
Hashed history tags have the same problem in Saved Histories

<img width="875" alt="screen shot 2018-05-15 at 5 15 49 pm" src="https://user-images.githubusercontent.com/8999735/40089992-ba6bc1ae-5863-11e8-9ef2-b8b98f51d953.png">

Unhashed tags display fine -- may be a clue to help find out why hashed tags are getting parsed in an unintended way.

<img width="881" alt="screen shot 2018-05-15 at 5 18 22 pm" src="https://user-images.githubusercontent.com/8999735/40090036-17a8ce3e-5864-11e8-8de5-b10a8eb394fe.png">

**Comment by hexylena** [comment]
Still a bug, and affects the colouring making it harder for users to match.

xref https://github.com/galaxyproject/galaxy/issues/8436

![image](https://user-images.githubusercontent.com/458683/63092713-e8815100-bf62-11e9-9e63-5f258ed080f2.png)

**Comment by hexylena** [comment]
Duplicate of https://github.com/galaxyproject/galaxy/issues/5428, will leave this one open since it has more information.

Test history: usegalaxy.org/u/jen/h/test-history-sort-sam-bam

**Comment by hexylena** [comment]
tool run form - fixed
history list - fixed
datasets - fixed

awesome!
