### ISSUE TITLE
History title no longer click-editable

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#6154]
Noticed in ~~18.05~~ dev, reported by @blankenberg

**Comment by dannon** [comment]
(if anyone else reproduces this, please note it here -- I'm not having good luck with it)

**Comment by blankenberg** [comment]
I was seeing it in dev, not 18.05

**Comment by dannon** [comment]
@blankenberg Ahh, thanks, I thought this was on usegalaxy.org.  I'll check that out.

**Comment by dannon** [comment]
Yeah, I see the problem, will have a fix out shortly.

**Comment by blankenberg** [comment]
Cool, thanks.
