### ISSUE TITLE
BS4 compliant HTML

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#6161]
We need to revisit our custom bs wrappers so they produce valid bs4 templates (e.g. https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/ui/ui-popover.js#L189)

Some of this could also be converted bootstrap-vue, instead.

(converted card from BS4 board for future work)

**Comment by mvdbeek** [comment]
@dannon is there there still actionable stuff in here or can we close this?

**Comment by dannon** [comment]
I think we got most of this stuff in the various component refactors and style overhauls over the last couple years.
