### ISSUE TITLE
"selected" datasets are not always what is submitted to the job

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#6163]
xref: https://github.com/galaxyproject/usegalaxy-playbook/issues/125

It's not possible to milestone issues across repos yet, but this is potentially a release blocker.  It needs to be reproduced and fixed, or ruled out as a recent code issue (and, specifically, a usegalaxy.org issue) before release.

**Comment by martenson** [comment]
this has been fixed by https://github.com/galaxyproject/galaxy/pull/6185
