### ISSUE TITLE
Get Data: UCSC Main reporting metadata problems with all imports

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#6164]
xref: https://github.com/galaxyproject/usegalaxy-playbook/issues/119

It's not possible to milestone issues across repos yet, but this is potentially a release blocker. It needs to be reproduced and fixed, or ruled out as a recent code issue (and, specifically, a usegalaxy.org issue) before release.

**Comment by martenson** [comment]
I was not able to reproduce this locally on release_18.05. None of the ucsc/archaea datasets had this warning present.

**Comment by martenson** [comment]
I was able to reproduce the second problem reported in the issue linked above and I made a separate issue for it: https://github.com/galaxyproject/galaxy/issues/6186

**Comment by martenson** [comment]
This issue is fixed by https://github.com/galaxyproject/galaxy/pull/6196
