### ISSUE TITLE
When a workflow is sent to a new history, that history link is not in the "launched" message anymore

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6167]
<img width="750" alt="screen shot 2018-05-17 at 4 52 44 pm" src="https://user-images.githubusercontent.com/8999735/40209294-3becddc2-59f3-11e8-9594-f0974b8b6bbc.png">

I had to go check in Saved Histories to find it. Could we add the "new history name with link" back to the message?

<img width="417" alt="screen shot 2018-05-17 at 4 57 45 pm" src="https://user-images.githubusercontent.com/8999735/40209369-9961f5f0-59f3-11e8-9ac6-ee02e5ba703c.png">

At https://usegalaxy.org running pre-release 18.05

ping @dannon

**Comment by dannon** [comment]
@jennaj Yeah, it bugged me when we dropped this (intentionally, I believe).  I'll see if I can figure out a good way to get it back.

**Comment by nsoranzo** [comment]
:+1: This affects 18.01 too, really annoying!
