### ISSUE TITLE
Get Data - server error on ucsc/archaea all fields import

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6186]
on `release_18.05`

go to Get Data/UCSC Archaea, select 'all fields from selected table' as output format and click 'get data'

You will end up with red dataset and this traceback:

```
  File "lib/galaxy/jobs/runners/local.py", line 152, in queue_job
    self._finish_or_resubmit_job(job_state, stdout, stderr, exit_code)
  File "lib/galaxy/jobs/runners/__init__.py", line 433, in _finish_or_resubmit_job
    job_state.job_wrapper.finish(stdout, stderr, exit_code, check_output_detected_state=check_output_detected_state)
  File "lib/galaxy/jobs/__init__.py", line 1288, in finish
    dataset.init_meta(copy_from=dataset)
  File "lib/galaxy/model/__init__.py", line 2202, in init_meta
    return self.datatype.init_meta(self, copy_from=copy_from)
  File "lib/galaxy/model/__init__.py", line 2132, in datatype
    return datatype_for_extension(self.extension)
  File "lib/galaxy/model/__init__.py", line 2042, in datatype_for_extension
    ret = datatypes_registry.get_datatype_by_extension(extension)
  File "lib/galaxy/datatypes/registry.py", line 565, in get_datatype_by_extension
    return self.datatypes_by_extension.get(ext, None)
TypeError: unhashable type: 'list'
```

originally reported at: https://github.com/galaxyproject/usegalaxy-playbook/issues/119

**Comment by dannon** [comment]
@martenson This is the same as #6164 right?

**Comment by martenson** [comment]
@dannon There are at least two issues reported originally, this is making them atomic.

**Comment by dannon** [comment]
@martenson Sure, if you think that's useful, okay.  You are sure they're not related?

**Comment by martenson** [comment]
@dannon no, I am not sure they are not related, but I think so.

**Comment by dannon** [comment]
@martenson Ok, cool.  Can't hurt to have more documentation of the problems, in any event.

**Comment by jennaj** [comment]
Retested just now, see the other ticket.

There are two failure types. One is metadata (green) the other is an outright fail (red). 

The outright red "list" failures are for tabular data from UCSC (bed, gtf, fasta give metadata error), gtf/fastq/bam data from GenomeSpace (bed data works fine, no problems), and fastq/srr from EBI SRA.

Other Get Data tools could be impacted, haven't tested all.

**Comment by martenson** [comment]
This issue is fixed by https://github.com/galaxyproject/galaxy/pull/6196
