### ISSUE TITLE
"Copy Dataset" function strips any previously assigned tags/hashtags

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6190]
True even when the "copy" is placed back into the same history

Not sure if related to data collection tag propagation issues

**Comment by bgruening** [comment]
We got an error report about this as well with latest 18.05.
ping @dannon

**Comment by dannon** [comment]
@bgruening Thanks for the ping.  Might use a code path with custom copy functionality not using the standard model-based copy or something -- I'll take a look.

**Comment by mvdbeek** [comment]
Should be fixed with https://github.com/galaxyproject/galaxy/pull/6532

**Comment by jennaj** [comment]
Retested at ORG running pre-release 18.09 to double check will be in the release/work at public servers. Pass - dataset hastags + tags both copy now, whether copy sent back to original history or a new one. Thanks!
