### ISSUE TITLE
indication of outdated tools seems dysfunctional 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6193]
In the "manage (installed) tools" section of the admin interface tools which have a newer version in the TS are not indicated. Seems to be the case in 17.09 and dev. 

I noticed this for galaxyp's peptideshaker package. 

![screenshot from 2018-05-22 15-51-09](https://user-images.githubusercontent.com/25689525/40366693-14355636-5dd8-11e8-8fc8-07606fe18a9d.png)
![screenshot from 2018-05-22 15-51-24](https://user-images.githubusercontent.com/25689525/40366694-1462c4d6-5dd8-11e8-8b92-9aa8bcd4228a.png)

In both cases the installed version is < then the latest available: 45:5fa8b409599e

**Comment by bernt-matthias** [comment]
If I install also the latest then both versions are shown as up-to-date: 

![screenshot from 2018-05-22 16-06-09](https://user-images.githubusercontent.com/25689525/40367623-282f8fa6-5dda-11e8-846c-54dc97a83e23.png)

**Comment by mvdbeek** [comment]
That's working fine for me. Try "Update tool shed status" in the upper right corner. You can also periodically update the status by setting https://github.com/galaxyproject/galaxy/blob/release_18.05/config/galaxy.yml.sample#L324

**Comment by bernt-matthias** [comment]
Cool. Learned something :) 

I tried the "Update too shed status" button, which resulted in a time out (on dev) and a proxy error (on 17.09). The latter might be a problem with our apache proxy .. but I guess its not. Maybe the update just takes longer than the browser timeout?

However, the galaxy.ini method works.

**Comment by martenson** [comment]
The update is a really slow TS API call, it is quite possibly a valid timeout :/

**Comment by bernt-matthias** [comment]
Then I'm fine. Thanks a lot.
