### ISSUE TITLE
rethink upload dialogue icons

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#621]
Our usage of upload dialogue icons where for FTP we use 'code-fork' and for fetch we use 'pencil' is ambiguous. This is not what the icons are designed for and how they are used on other sites. If we do not have good icon for the activity let's not use an icon at all.
![uploaddialogue](https://cloud.githubusercontent.com/assets/1814954/9367439/4ad532ea-468b-11e5-926a-501bfd96e46e.png)

**Comment by hexylena** [comment]
agreed, fork is the wrong icon. Maybe the server icon? http://fortawesome.github.io/Font-Awesome/icon/server/

**Comment by martenson** [comment]
I was also thinking about folder-open http://fortawesome.github.io/Font-Awesome/icon/folder-open/

**Comment by hexylena** [comment]
Oh, yes, good choice!

ons. 19. aug. 2015 kl. 15.35 skrev Martin Cech notifications@github.com:

**Comment by guerler** [comment]
I like the folders too. Anyone with suggestions for the pencil? I think the latter is less critical tho.

**Comment by martenson** [comment]
I can live with the pencil :)

**Comment by guerler** [comment]
I went with the http://fortawesome.github.io/Font-Awesome/icon/folder-open-o/ version of the open folder. Seemed to fit better with the laptop symbol but is up for discussion. Also changed the pencil to an edit symbol for the same reason.

**Comment by martenson** [comment]
good job @guerler
