### ISSUE TITLE
Tags incorrect when reducing a collection ?

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#6224]
![screen shot 2018-05-25 at 16 12 50](https://user-images.githubusercontent.com/6804901/40549085-cf35715e-6036-11e8-973e-e426cbeca1d4.png)
This dataset was produced by reducing the collection with the tag `Tumor` using a `multiple="True"` input.

I'll follow up if I find some time

**Comment by jmchilton** [comment]
Probably one of the individual inputs in the source collection had the tag "Heads"?

**Comment by mvdbeek** [comment]
Interesting, actually all datasets in the collection have the opposite tag! bizarre, but I probably did something weird on the way ...
