### ISSUE TITLE
values in job_resource_params_conf.xml not applied to LSF or SLURM job params

### ISSUE THREAD

**Issue by charmichaeld** [galaxyproject/galaxy#6232]
We have Galaxy v18.01 installed in an HPC environment and want to use the job_resource_params_conf.xml file to allow the user to adjust walltime. The galaxy.ini job_resource_params_file parameter is enabled and the 'Job Resource Parameters' option is showing up at the bottom of the tool interface but when the job is submitted, the user's new input value is not applied. The job defaults to the default destination (1day1core in our case). I noticed the job_resource_params_conf.xml.sample file uses PBS params in the help messages. Are the LSF BSUB params supported?

![job_params](https://user-images.githubusercontent.com/4388946/40562262-ce57f3f8-6025-11e8-9ee4-5e84deabf997.png)

=== config/job_resource_params_conf.xml ===
```
<parameters>
  <param label="Processors" name="processors" type="integer" size="2" min="1" max="20" value="20" help="Number of processing cores, '#BSUB -n' value (1-20). Leave blank to use default value." />
  <param label="Memory" name="memory" type="integer" size="3" min="1" max="12300" value="2500" help="Memory size in gigabytes, '#BSUB -M' value (1-12300). Leave blank to use default value." />
  <param label="Time" name="time" type="integer" size="3" min="1" max="168" value="23" help="Maximum job time in hours, 'walltime' value (1-168). Leave blank to use default value." />
  <param label="Project" name="project" type="integer" size="12" value="" help="Project to assign resource allocation to. Leave blank to use your default myproject account." />
</parameters>
```

=== config/job_conf.xml ===
```
    <destinations default="1day1core">
        <destination id="1day1core" runner="drmaa" tags="normaljobs">
            <param id="nativeSpecification">-n 1 -L /bin/bash -W 26:00 -M 2500 -R span[ptile=1]</param>
        </destination>
...
    <tools>
        <tool id="upload1" destination="local"/>
        <tool id="DownloadFiles" destination="local"/>
        <tool id="trinity_small" resources="time"/>
    </tools>
```

**Comment by charmichaeld** [comment]
We now have version 18.09 on a cluster using SLURM. The Job Resource Parameters option shows up in the tool GUI. The SLURM job runs using the default destination instead of the selected time. The selected time is not being applied to the SLURM --time job parameter.

**Comment by hexylena** [comment]
Hi @charmichaeld sorry for the delayed response. We've just overhauled some of the training documentation and I learnt for the first time that resource selectors require writing a dynamic job destination in order to utilise any numbers used in the resource parameters configuration.

Please see the updated training here: https://galaxyproject.github.io/training-material/topics/admin/tutorials/connect-to-compute-cluster/tutorial.html#job-resource-selectors

**Comment by charmichaeld** [comment]
Thanks @erasche, In section 4 of the Job Resource Selectors section, the resources is set to "testing_resources" although this id is nowhere else on the page. 

`    <tool id="testing" destination="dynamic_cores_time" resources="testing_resources"/>`

I think it might be resources="testing" since in item 3 of that same section, the group id="testing".
	In the following section "A dynamic destination" the DESTINATION_IDS are slurm and slurm-2c. Should the DESTINATION_IDS be "dynamic_cores_time" since this is the destination created in the Job Resource Selectors section?

**Comment by hexylena** [comment]
It seems we corrected the training due to the first part of your comment, I'll update the second one. Thanks for noticing this!
