### ISSUE TITLE
Using cutadapt in a workflow with list:paired input produces 2 list collections containing fastq files of type "data"

### ISSUE THREAD

**Issue by hepcat72** [galaxyproject/galaxy#6247]
Galaxy version: 17.09
cutadapt wrapper version: 1.16

I ran this twice (2 different datasets of 12 fastq files each).

The input is a collection of type list:paired:

![listpaired](https://user-images.githubusercontent.com/2300532/40732394-394c6098-6401-11e8-811d-ebb7ddf22860.png)

and I double-checked that all input files were of type fastqsanger.  E.g.:

![fqs](https://user-images.githubusercontent.com/2300532/40732532-82b167f6-6401-11e8-9446-1bc3585eebd8.png)

The out1 and out2 types had the "change datatype" set as "leave unchanged":

![leaveunchanged](https://user-images.githubusercontent.com/2300532/40732469-5d84d8e6-6401-11e8-9994-c2656a86d0a1.png)

Side notes:

I had to change the output datatype of 48 files manually to fastqsanger before I could proceed.  It would be nice to have that fixed so that's not necessary, but it would also be nice to have a way to bulk-change datatypes in these scenarios, because it seems to happen frequently enough.  Plus it would be nice to see a unique set of datatypes contained in a collection at the top of the collection after you click on it or event in the little gray message under the collection name that says "a list of 12 datasets" (with a warning if multiple types are contained) without having to scroll to the selection, click the collection, click the sample, click forward, and click reverse to inspect each datatype.  Like, for example: "a list of 12 *fastqsanger* datasets" or a red message saying: "a list of 12 *mixed-type* datasets".

And when you're manually changing each datatype, you have to do that whole process each time: scroll & perform 3 clicks (while memorizing where you left off), plus click the pencil, click "Datatypes", click the select list, paste (or type) the type name, click to select, then click "Change datatype" each time. After that last click, it goes back to your main history.  When you have a long history with lots of similar collection names, it's surprisingly time consuming to get back to where you just were.  (I usually do a browser search (command-e & command-g) to jump back to the collection.)  So I was thinking, at least it would be nice to not bring the user back to the main history after clicking "change datatype", but rather just let them back out of the pair on their own when they're done editing.

**Comment by lparsons** [comment]
Is it possible this is fixed by version 1.16.1 of the cutadapt wrapper? https://github.com/galaxyproject/tools-iuc/commit/e2e3f38311fa628b29b59eae6f165b9f5244f643

**Comment by jmchilton** [comment]
@lparsons Yeah - that recent round of fixes corrected a lot of datatype issues so I'd think this will fix this problem. This fix (https://github.com/galaxyproject/galaxy/pull/6253) will probably be needed also - which might require an upgrade depending on how far we back port it.

**Comment by mvdbeek** [comment]
So we've backported the fixes to 18.01, together with cutadapt >= 1.16.1 this should work now. If not feel free to open this again (and of course many thanks for the detailed report!).
