### ISSUE TITLE
manage_db.py does not properly ensure dependencies are updated

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#6256]
When updating galaxy, I have a script that runs `manage_db.sh db_version` and `manage_db.sh version` to check to see if I need to update the database. However, when dependencies are added, this can run into problems since the new dependencies haven't been downloaded yet.

I believe adding a some lines to `manage_db.sh` just before the call to `setup_python` should do the trick:
```
parse_common_args $@

run_common_start_up
```

I wasn't really sure about the common args stuff though, so I didn't submit a PR (yet). Comments @natefoo and other admin folks?

**Comment by lparsons** [comment]
Looks like the official recommendation is to run `common_startup.sh` prior to upgrading the db (http://galaxyproject.github.io/training-material/topics/admin/tutorials/upgrading/slides.html), so I guess this can be closed? (Thanks @nsoranzo)

**Comment by hexylena** [comment]
Done :) Using Ansible solved a bunch of these problems for us, things we definitely forgot about too.

**Comment by lparsons** [comment]
Curious, do you use the stuff from https://github.com/galaxyproject/ansible-galaxy or did you role your own, or both. I've got my own, but considering stripping out a lot, using the published ones, and then just adding some stuff specific to our instance in separate roles...

**Comment by hexylena** [comment]
We use that role, since it's the 'official' one. Can definitely recommend using it, it's been quite flexible for our use case :) E.g. [ours](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/galaxy.yml#L110) does that role, then a BUNCH of custom ones
