### ISSUE TITLE
"Your Workflows" GUI - last workflow in listing has incomplete pull-down menu

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6258]
ping @dannon 

Tested in a few accounts (admin, non-admin) and with Chrome/Safari on OSX. Same results in all. Probably a small bug in GUI.

<img width="742" alt="workflow_menu_issue_pic_1" src="https://user-images.githubusercontent.com/8999735/40808103-f6164368-64da-11e8-8fb3-cc729ce08779.png">

<img width="741" alt="workflow_menu_issue_pic_2" src="https://user-images.githubusercontent.com/8999735/40808104-f62e3766-64da-11e8-9e02-1b5fa10f820a.png">

**Comment by dannon** [comment]
@jennaj I think it's that you're not the owner of that bottom workflow, but 'jen' is.  Is that incorrectly displayed, or is that the case?

**Comment by jennaj** [comment]
@dannon let me test that & sorry if was the reason, feedback soon

**Comment by jennaj** [comment]
Thanks! I get mixed up with this Workflow view structure
