### ISSUE TITLE
"View data" pops are sticky in Analyze Data > History view with composite and collection datasets

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6259]
ping @dannon 

Did a bit more testing before building ticket - it is not just composite data but also data collections (all types). 

**Problem:** The pop-ups for "view data" are sticky in these nested datatype. Do not go away until another icon is clicked on -- and sometimes these can "stack up" when hover over other view icons, blocking the view of other icons/history content.

**Tests:** Compared behavior in both Chrome and Safari on OSX. **Chrome presents with the problem, Safari does not.**

I haven't run into this with an individual dataset in the history since that was fixed before 18.05 was released.

**Test history:** https://usegalaxy.org/u/jen/h/test-history-multiqc-hidden-fastqc-rawdata (includes all three data structures: individual, collection, composite)

**Examples:**

See "stats" output from MultiQC (data 13, composite)

<img width="251" alt="screen shot 2018-05-30 at 5 59 32 pm" src="https://user-images.githubusercontent.com/8999735/40808429-eb6b9a66-64db-11e8-8ec1-f15554b82eba.png">

See collection "list of pairs" (data 29)

<img width="247" alt="screen shot 2018-05-31 at 2 25 22 pm" src="https://user-images.githubusercontent.com/8999735/40809286-d4f1dd10-64de-11e8-8ada-bc02904c31a8.png">

Same behavior with collection "list" (data 28) and collection "pair" (dataset 30)

**Comment by mvdbeek** [comment]
Very annoying but I think that might be fixed with https://github.com/galaxyproject/galaxy/pull/6745

**Comment by jennaj** [comment]
I can't reproduce this anymore, so think it is fixed, too @mvdbeek -- thank you!

Let's close it out and if someone else runs into it, we can reopen.
