### ISSUE TITLE
IGV Track naming

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#6268]
For a dataset with a "normal" name:

![screenshot from 2018-06-04 07-23-18](https://user-images.githubusercontent.com/4291636/40914953-31ec56f8-67c8-11e8-8df1-37e4e7a36de2.png)

the corresponding track name in IGV will be non-intuitive (it is `galaxy_bbd44e69cb8906b55db2a2fa7102b1c3.bed`):

![igv_names](https://user-images.githubusercontent.com/4291636/40914990-5c862466-67c8-11e8-8e21-ae9c04ce9a22.png)

when submitting multiple tracks this becomes a nightmare to figure out what is what.

also see https://github.com/galaxyproject/usegalaxy-playbook/issues/122

**Comment by mvdbeek** [comment]
That's probably a combination of IGV issue and galaxy issue. I think that older versions of IGV still display the name, but I'll double-check. On top of that we may want to include element identifiers if available

**Comment by nekrut** [comment]
Yes. I was hoping this is easy to fix

**Comment by mvdbeek** [comment]
I think I have narrowed this down to https://github.com/igvteam/igv/pull/549. This doesn't look like it's a galaxy issue since simple renaming of tracks also doesn't work atm.

**Comment by mvdbeek** [comment]
This has been fixed in https://github.com/igvteam/igv/commit/2111e50ec89beacc2ca942390a219d700cbbf778 and should be in IGV > 2.4.10.
