### ISSUE TITLE
GRT script not exporting dataset sizes

### ISSUE THREAD

**Issue by atyryshkina** [galaxyproject/galaxy#6272]
The GRT script scripts/grt/export.py was not gathering the sizes of the datasets used by the jobs.   The GRT script gathered the data into three files:  job.tsv, a params.tsv, and a metric_num.tsv file.
I've made it so that it also outputs a datasets.tsv file.  
It's currently in a pull request, https://github.com/galaxyproject/galaxy/pull/6263.

**Comment by martenson** [comment]
fixed with the PR linked above
