### ISSUE TITLE
Minor issue with NCBI BLAST+ blastx tool

### ISSUE THREAD

**Issue by nvk747** [galaxyproject/galaxy#6275]
Dear Galaxy Team,
I request you to add NCBI NR protein database as an option under locally installed blast databases under **Subject database/sequences.**  Currently, no options are available for the tool to run when using locally installed databases. 
regards,
Vijay
![image](https://user-images.githubusercontent.com/39386288/40942136-2dc184a6-681b-11e8-8383-549de9b57746.png)

**Comment by bgruening** [comment]
@nvk747 which Galaxy instance are you using? You should talk to your Galaxy admin, we can not help here much as you local Galaxy admin need to install those databases.

**Comment by nvk747** [comment]
@bgruening Thanks for letting me know, I am currently running galaxy instance provided by CyVerse at the Texas Advanced Computing Center.
