### ISSUE TITLE
drop many superfluous API calls after job submission

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6276]
I think these are useless API calls that go on as long as history is being polled, see the annotation below

![galaxy_and_forklift](https://user-images.githubusercontent.com/1814954/40941673-9df06938-6819-11e8-9c1a-203372aacc33.png)

**Comment by martenson** [comment]
To reproduce I think your best bet is to execute a job that takes some time (easiest to reproduce on Main I guess) since the calls to `/build` last only as long as the history polling.

**Comment by martenson** [comment]
The calls to `Request URL: https://usegalaxy.org/api/tools/toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_cat/0.1.0/build` seem to only be called after the history polling has a non-empty response.

**Comment by guerler** [comment]
xref #6118.

**Comment by guerler** [comment]
We could disable the history listener after job submission. Can you test this: https://github.com/galaxyproject/galaxy/compare/dev...guerler:history_polling.

**Comment by martenson** [comment]
The branch linked above does not call the build/ in my testing, so maybe enough of a fix @guerler?

**Comment by mvdbeek** [comment]
We're done with this, right ? The webhooks thing should probably its own issue ?

**Comment by martenson** [comment]
Yeah, majority is fixed I think.

**Comment by martenson** [comment]
webhooks xref https://github.com/galaxyproject/galaxy/issues/5565
