### ISSUE TITLE
18.05 Backport Client Fixes

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#6282]
Tracking dev client stuff that needs to be backported. Want to do it all at once to reduce number of client builds:

- #6281
- #6231
- #6279

Anything else?

**Comment by martenson** [comment]
this needs rebuild 

https://github.com/galaxyproject/galaxy/pull/6238
https://github.com/galaxyproject/galaxy/pull/6226
https://github.com/galaxyproject/galaxy/pull/6243
https://github.com/galaxyproject/galaxy/pull/6237
https://github.com/galaxyproject/galaxy/pull/6260

**Comment by martenson** [comment]
this needs rebuild: https://github.com/galaxyproject/galaxy/pull/6243
