### ISSUE TITLE
History menu does not scroll. Can get "cut-off" when working on smaller display or with a larger font

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6284]
Related recent fixes for menus in general: https://github.com/galaxyproject/galaxy/issues/5927

If in those other fixes and just not applied to main yet, let me know and I'll move this to a tracking ticket/testing in usegalaxy-playbook/issues/. Same behavior presents at eu but they would capture the fix at next update after this is applied. 

Needing a scroll might apply to other menus, although this is the longest list in the GUI I think and more likely to present with the problem unless someone is trying to the app from a phone/tablet or have a larger font applied in the browser. 

A user ran into this problem today and reported it at Biostars: https://biostar.usegalaxy.org/p/28280

I tested on MAC OSX, both Safari and Chrome.

ping @dannon @martenson @jmchilton 

Added fixathon tag, minor but users are getting confused. Please remove it if lower priority. @nekrut

**Comment by martenson** [comment]
700px is the height of the menu in my browser. I am not surprised some screens won't fit it. :/

**Comment by jennaj** [comment]
Thanks. The user who reported it had to make their font smaller to see it. Hopefully, we can help. Scroll or alt ideas to help with full menu access.

**Comment by martenson** [comment]
that menu needs simplification/split - that would be my choice over scrolling within popover

**Comment by hexylena** [comment]
The cleaned up history menu is definitely helping this :)

Reduced to 530 px on dev

![image](https://user-images.githubusercontent.com/458683/63092451-187c2480-bf62-11e9-9d2f-7b326ba93fe0.png)
