### ISSUE TITLE
Select2 field performance issues

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#6287]
Selecting many options at once (>500) causes the browser window to freeze. This ticket keeps track of this issue which we should be able to resolve by replacing select2 with a more resilient selector component. Note that the use of Select2 is already limited in the run workflow form due to performance issues. In the run workflow form only data fields are presented as Select2 fields. Thanks for reporting this @jgoecks.

**Comment by mvdbeek** [comment]
This is probably heading towards vue-multiselect.

**Comment by mvdbeek** [comment]
I think the UI/UX group has other issues open already for the migration, it might happen soon, but not for the release.
Closing in favor of https://github.com/galaxyproject/galaxy/issues/11944 / https://github.com/galaxyproject/galaxy/issues/11076
