### ISSUE TITLE
Edit Collection Datasets Broken Until Details Expanded

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#6291]
This ID used to fetch the edit https://usegalaxy.eu/datasets/edit?dataset_id=d1921a3da8fdd043.

@erasche tested this and it was clearly broken with https://github.com/galaxyproject/galaxy/pull/5703/files.

**Comment by mvdbeek** [comment]
I think https://github.com/galaxyproject/galaxy/pull/10427/files fixed this.
