### ISSUE TITLE
Internal Server Error clicking on some published workflows

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#6296]
https://usegalaxy.org/u/mheydarian/w/copy-of-4-sample-rnaseq-denotrr---v2-imported-from-uploaded-file

If I import the workflow by searching for `mheydarian` in https://usegalaxy.org/workflows/list_published (it's the one called "RNA-seq de novo transcriptome reconstruction tutorial workflow"), and then edit the imported copy, I get:
```
Issues loading this workflow
Please review the following issues, possibly resulting from tool upgrades or changes.

    Step 44: Join two Datasets
        No value found for 'Keep the header lines'. Using default: ''.
    Step 45: Join two Datasets
        No value found for 'Keep the header lines'. Using default: ''.
```

**Comment by guerler** [comment]
This seems to be fixed. Please reopen if not.
