### ISSUE TITLE
history view styling problems

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6309]
* history items have no break between each other
* collection-type items are significantly narrower

![screenshot 2018-06-08 13 05 05](https://user-images.githubusercontent.com/1814954/41171145-7807d240-6b1d-11e8-8d49-4a365ab34a76.png)

I thought the first item would be fixed by https://github.com/galaxyproject/galaxy/pull/6197 but the screenshot is from Main ~~that has this change~~ will have it after https://github.com/galaxyproject/galaxy/pull/6238

**Comment by hexylena** [comment]
I haven't seen this recently on eu at least?
