### ISSUE TITLE
Rule builder is stuck with latest collection in history

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#6320]
Even if I select another collection it'll show the wrong collection content,
so in this context I only see the content of collection 6.

![screen shot 2018-06-12 at 15 42 33](https://user-images.githubusercontent.com/6804901/41294028-494bf9e4-6e57-11e8-8fec-0eba81a1dcc8.png)

I can delete collection 6 and then I see the correct content

**Comment by jmchilton** [comment]
Yeah - I've noticed this too - the test case screenshots would show the wrong collections being previewed in the rule builder but the right collections being executed. I really don't have an excuse for this not being fixed yet. Sorry.
