### ISSUE TITLE
improve toolpanel design in firefox

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6323]
it looks pretty terrible currently

![screenshot 2018-06-12 15 55 26](https://user-images.githubusercontent.com/1814954/41313880-1d2bb8c0-6e59-11e8-9b67-a716b65c9f44.png)

**Comment by dannon** [comment]
There's an issue open already for that box floating when the banner is in place.  I wanted (at the time) to revert the pinned-to-top behavior, but now that we're using BS4 I should hopefully have an easier fix for this.

**Comment by dannon** [comment]
(the underlying issue is discussed here https://github.com/galaxyproject/galaxy/issues/3592)

**Comment by martenson** [comment]
There is also a gap before the first tool section which shouldn't be there.

**Comment by dannon** [comment]
@martenson Yeah, that gap is where the search *would* go if it was embedded correctly.
