### ISSUE TITLE
18.05 Backports

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#6327]
Another running list of client changes to dev that need to be backported to 18.05:

- #6326

**Comment by martenson** [comment]
https://github.com/galaxyproject/galaxy/pull/6303

**Comment by martenson** [comment]
this is probably fine to close @jmchilton ?

**Comment by martenson** [comment]
your thing has been backported in https://github.com/galaxyproject/galaxy/pull/6691 I beleive

**Comment by jmchilton** [comment]
Thanks!
