### ISSUE TITLE
maf metadata is not determined

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6329]
- when uploading maf its detected as txt. 
- when changing the datatype manually metadata info says: `? blocks `
- The MAF tools are unusable, eg. "Filter MAF blocks by Species" does not allow to select species (which indicates that also the species metadata is missing)
- when selecting maf during upload the bahaviour is analogous
- while the above happen on 18.05 on dev I have also seen the message "Warning: The file 'Type' was set to 'maf' but the file does not appear to be of that type"

test eg with https://github.com/bgruening/galaxytools/blob/master/tools/rna_tools/rnacode/test-data/coding.maf (I tested more)

**Comment by mvdbeek** [comment]
Pretty sure we fixed that some time ago (https://github.com/galaxyproject/galaxy/pull/6631 perhaps or some of the followups that touched on similar things), please open again if this still happens.
