### ISSUE TITLE
Enhancement: Enable tag/anno edits for queued, executing, failed jobs

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6330]
Would it be possible to add these in? Would make it possible to annotate jobs right after being launched, to better keep track of data, rather than needing to go back in after and figure out what was done. Inherited tags are not always enough, and annotation is not inherited.

Alternatively, could add in a function to tools that allow tag/annotation manipulations. Could be placed on all forms right above "submit". Bigger project yet is a better function when doing runs in batch.

For failed jobs, would be useful to add tag/anno in for reruns, troubleshooting, experimenting with params, etc. 

<img width="249" alt="screen shot 2018-06-13 at 10 55 11 am" src="https://user-images.githubusercontent.com/8999735/41369059-a7bed41e-6ef8-11e8-81b3-e5d1b14768af.png">

<img width="255" alt="screen shot 2018-06-13 at 10 49 52 am" src="https://user-images.githubusercontent.com/8999735/41369075-afb651ba-6ef8-11e8-8b54-ec503b675e45.png">

<img width="248" alt="screen shot 2018-06-13 at 10 55 25 am" src="https://user-images.githubusercontent.com/8999735/41369079-b33a0c8c-6ef8-11e8-9677-ee188e5884b4.png">

**Comment by jennaj** [comment]
@ic4f This was assigned to you by @nekrut in https://github.com/galaxyproject/usegalaxy-playbook/projects/2#card-14475567

We were unable to assign the issue ticket to you in GH using "@ic4f" for some reason. Could you check why and assign yourself? Thanks!

**Comment by jdavcs** [comment]
Can't self-assign - already tried: self-assign option not available. (will ask on slack)
But to acknowledge, yes, this issue is on me.

**Comment by dannon** [comment]
@jennaj @ic4f I took a look and fixed it up, @ic4f can now be assigned issues.

**Comment by jennaj** [comment]
@ic4f Thanks for taking this on. Doing this for collections might be tricky but we would want to include that.

**Comment by jennaj** [comment]
@ic4f Adding tags is now possible. I did notice a few things, not sure what can be done about any though.

 - If the dataset state changes while I am creating a tag, the GUI freezes for a few seconds and the tag is lost.

 - *About one of ten tries* when adding a tag to a grey/queued dataset right after launching a job, the tag is added but then a red pop-up comes up (the one about the history not reloading correctly, usually indicates the database isn't caught up with the GUI display). Then the entire history content disappears. Using the "refresh" button at the top doesn't display/fix the history view. After a few tries, I found that waiting for a bit (3-5 minutes) or starting up another job (datasets in the history can still be selected as inputs) will both result in the history resetting and rendering correctly.

I don't think we can do anything about these issues, or at least the first one -- but what do you think? Is there some way the performance could be tuned before 19.01 is finalized? @dannon or @natefoo or anyone working with the new GUI might have input about this. 

I would much rather have new tag functionality included, even with the small problems, than be forced to redact the enhancement. It might only impact really big servers/databases, or users with big accounts and/or histories, or something like that.

Leaving this open until we decide if or what anything else should be done.

**Comment by jennaj** [comment]
Closing out! Thanks @ic4f
