### ISSUE TITLE
Get Data > EBI SRA is assigning fastqsanger to fastqsanger.gz output

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6334]
Causes downstream tool problems such as this one: https://github.com/galaxyproject/usegalaxy-playbook/issues/144

ping @davebx @martenson

**Comment by jennaj** [comment]
**Workaround until fixed:**

Reassign the datatype metadata to be `fastqsanger.gz` for your fastq inputs. The data is compressed but is not being labeled that way -- we'll be fixing that. Please follow this ticket for updates.

How to change metadata is in the Galaxy FAQs: https://galaxyproject.org/support/

 - How do I find, adjust, and/or correct metadata? https://galaxyproject.org/support/metadata/

Or, if your accession is at NCBI, the tool **NCBI SRA Tools > Download and Extract Reads in FASTA/Q format from NCBI SRA** can be used instead. That tool sets the metadata correctly depending on the output datatype selected on the form.

**Comment by jennaj** [comment]
Duplicate with more scope: https://github.com/galaxyproject/galaxy/issues/6472

**Comment by jennaj** [comment]
Ping again @natefoo @davebx @martenson 

This is still an issue and _triggers errors with any downstream tool used_ -- until the user updates to the correct datatype themselves. Most don't know what is going wrong with those errors, so this is coming up often still in bug reports/biostars questions.

Is there a priority/plan for the fix?

**Comment by jennaj** [comment]
Another bug with the tool: **if the data is really in "fastqcssanger.gz" format, it is assigned "fastqsanger"**. The datatype "fastqsanger.gz" cannot be automatically applied to all outputs from this source.  Example: SRR033795

**Fastq Groomer** will convert correctly if the datatype is first changed to fastqcssanger.gz. Manipulate Fastq will also do the conversion. Test history: https://usegalaxy.org/u/jen/h/test-history-ebi-sra-solid-fastq

**Comment by martenson** [comment]
jen:
>the issue is that 1) fastqsanger.gz is given the fastqsanger datatype when imported to Galaxy 2) related but less important, fastqcssanger.gz is given fastqsanger. so the user has to change to fastqcssanger.gz, then use the groomer
If only the first was fixed that will address all but one reported problem. item 1 is reported daily (again today already)

dan:
>It seems like the real issues are 1.) compressed datatypes are uncompressed for sniffing/detection and ext assignment, but are then finalized in their compressed form. 2.) the fastqsanger sniffer is not correct

jmchilton
> test_data_source.xml that reuses data_source.py sniffs a fastqsanger.gz correctly, so it isn't in the sniffing generally... let me think what else might be causing this

**Comment by martenson** [comment]
To close this: the 18.09 should not decompress compressed data anymore. This is a configurable option, and this is the default behavior now. 

It should behave like that for every datatype in `datatypes_conf.xml(.sample)` that has `auto_compressed_types` property set. Other things will get decompressed automatically. (right @jmchilton ?)

The other issue is a faulty sniffer, I will open a new ticket for it.

**Comment by jennaj** [comment]
**Note to usegalaxy.* users:** This is resolved at usegalaxy.org now. It will be resolved soon at usegalaxy.eu and usegalaxy.org.au and other public Galaxy servers when those servers update to the next Galaxy release.

If your data is in `fastqcssanger.gz` format, you will still need to adjust the datatype until https://github.com/galaxyproject/galaxy/issues/6734 is resolved/closed out.
