### ISSUE TITLE
proxy-prefix not working for "View all histories"

### ISSUE THREAD

**Issue by some2** [galaxyproject/galaxy#6335]
Hi all,

I'm running a galaxy 18.01 installation (with Apache 2.4 as reverse proxy) at "https://hostname/galaxy" with (galaxy.ini):

[filter:proxy-prefix]
use = egg:PasteDeploy#prefix
prefix = /galaxy

This also works without problems, except for the "View all histories" function (top right button in the History bar). This function seems to ignore the proxy prefix. I get the following error message:

> {
  "userAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:52.0; WIA enabled) Gecko/20100101 Firefox/52.0",
  "onLine": true,
  "version": "18.01",
  "xhr": {
    "readyState": 4,
    "responseText": "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /api/histories was not found on this server.</p>\n<hr>\n<address>Apache/2.4.25 (Debian) Server at hostname Port 443</address>\n</body></html>\n",
    "status": 404,
    "statusText": "Not Found"
  },
  "options": {
    "parse": true,
    "silent": true,
    "limit": 1,
    "filters": {
      "encoded_id-in": "260c504afc0157fc",
      "deleted": null,
      "purged": ""
    },
    "reset": true,
    "offset": 0,
    "remove": false,
    "traditional": true,
    "data": {
      "limit": 1,
      "offset": 0,
      "order": "update_time",
      "view": "dev-detailed",
      "q": [
        "encoded_id-in",
        "deleted"
      ],
      "qv": [
        "260c504afc0157fc",
        "None"
      ]
    },
    "emulateHTTP": false,
    "emulateJSON": false,
    "textStatus": "error",
    "errorThrown": "Not Found"
  },
  "url": "https://hostname/galaxy/history/view_multipl/galaxy/api/webhooks",
  "model": [],
  "user": {
    "id": "260c504afc0157fc",
    "username": "u-username",
    "total_disk_usage": 0,
    "nice_total_disk_usage": "0 bytes",
    "quota_percent": null,
    "is_admin": true,
    "deleted": false,
    "tags_used": [],
    "last_password_change": "2018-03-14T11:50:22.920481",
    "active": false,
    "model_class": "User"
  }
}

https://hostname/galaxy/api/histories exists while https://hostname/api/histories does not exist.

Note: the real username and hostname have been replaced by username/hostname.

**Comment by dannon** [comment]
Opened a backport of the fix for this at #6336
