### ISSUE TITLE
Duplicate history entries

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#6350]
Possibly related to #3818. I noticed multiple times recently duplicate entries in the history. Created this to keep track of it.

![duplicates](https://user-images.githubusercontent.com/2105447/41490826-d1e4e4b4-70c3-11e8-8900-1d5c3f34fa7e.png)

**Comment by mvdbeek** [comment]
Have you been using the collection operation tools on a collection containing those datasets ? I have seen this happening in these circumstances, I belive this happens when we add new HDAs to a history [here](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/__init__.py#L2630)

**Comment by guerler** [comment]
Interesting. Thanks @mvdbeek, and yes, it occurs in relation to collection operations.

**Comment by jmchilton** [comment]
I wasn't even trying to fix this but I think https://github.com/galaxyproject/galaxy/pull/6370/files will fix it.

**Comment by mvdbeek** [comment]
Yeah, we solved this a while back I think.
