### ISSUE TITLE
When there are too many issues in a workflow you cannot click continue

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#6352]
![auswahl_039](https://user-images.githubusercontent.com/458683/41531384-ae49c436-72e2-11e8-96f7-894dbe57f1f1.png)

- I could zoom out but this is sub-optimal.
- Yes I know this should never happen.

**Comment by dannon** [comment]
(didn't mean to assign myself this one when I was poking through earlier this morning)
