### ISSUE TITLE
workflow in a Galaxy Page stops rendering with an error

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6353]
reported here: https://biostar.usegalaxy.org/p/28436/

looks like this: 
![screenshot 2018-06-18 10 47 02](https://user-images.githubusercontent.com/1814954/41543528-f8a17eaa-72e4-11e8-889e-09943ec94cc5.png)

the workflow: https://usegalaxy.org/u/mwolfien/p/trapline---manual
It has more than 100 steps but the rest is not rendered

error when editing after import: 
![screenshot 2018-06-18 10 45 52](https://user-images.githubusercontent.com/1814954/41543486-e4944c08-72e4-11e8-9947-130ef6aeb113.png)

**Comment by martenson** [comment]
It seems like in Galaxy Pages the default is not being properly set? Ping @guerler

**Comment by AndrzeJKoc** [comment]
I am following this topic but the bug is still there and I can't read the manual. Will it be fixed?

**Comment by martenson** [comment]
@AndrzeJKoc yes, we already have a solution in review and will deploy the fix within a week I estimate

**Comment by AndrzeJKoc** [comment]
Any progress?

**Comment by martenson** [comment]
@AndrzeJKoc yes, the fix has been merged and will be deployed tomorrow.

**Comment by martenson** [comment]
The fix has been deployed and seems to work well. Closing.
