### ISSUE TITLE
After sharing a history with one user, you cannot share with additional users

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#6356]
Steps to reproduce:

- Create a history
- Share history
 - Share with a user
 - Provide an email
 - Submit
 - Share with a user. *Button does not function.*

Short term workaround:

- unshare with your previous users
- re-share with all of them in a new comma separated list.

Affects:

- usegalaxy.eu
- usegalaxy.org

**Comment by dannon** [comment]
#6358 Should fix this.
