### ISSUE TITLE
Uwsgi doesn't quit with error exit

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#6357]
Running via `run.sh` under uwsgi, default config.  If your database isn't migrated correctly and Galaxy (correctly) refuses to start, the uwsgi process remains running, requiring a manual pkill.  It should instead exit cleanly when a startup failure is kicked back to the console.

Noticed in 18.05 when switching between branches, having an out-of-sync database.

**Comment by martenson** [comment]
we no longer uwsgi, this is likely resolved/outdated
