### ISSUE TITLE
Tool panel search is not displaying all results

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6376]
ping @martenson 

Example search where the tool is not found:

<img width="246" alt="screen shot 2018-06-21 at 11 54 16 am" src="https://user-images.githubusercontent.com/8999735/41741516-2ab59008-7550-11e8-8897-4155de930055.png">

When directly hunted for, the tool is there:

<img width="229" alt="screen shot 2018-06-21 at 11 49 42 am" src="https://user-images.githubusercontent.com/8999735/41741532-3b16ba3a-7550-11e8-9d20-572370f8a240.png">

**Comment by martenson** [comment]
there are 20 results returned on main for `snpeff` query, including the ‘snpeff build’ tool but only 16 are shown in toolpanel

**Comment by mvdbeek** [comment]
I think we fixed that with #6737, can you check again once main is updated and close ?

**Comment by martenson** [comment]
works on Main now
