### ISSUE TITLE
Unable to run galaxy within an iframe

### ISSUE THREAD

**Issue by enolfc** [galaxyproject/galaxy#6384]
Trying to run a Galaxy server embedded in a iframe I get the following error in the console:

[Error] SecurityError: Blocked a frame with origin "https://mygalaxyhost" from accessing a frame with origin "https://thepagethatembedsgalaxy". Protocols, domains, and ports must match.
	get (5:142)
	initialize (253:85)
	View (2:1225)
	child (2:1885)
	initialize (252:49)
	View (2:1225)
	child (2:1885)
	(anonymous function) (44:72)
	forEach (1:153)
	initialize (44:68)
	View (2:1225)
	child (2:1885)
	(anonymous function) (251:364)
	fire (0:3187)
	fireWith (0:3317)
	ready (0:3536)
	completed (0:3552)

I have already set the x_frame_options empty and also added to the web server the folowing header 
Content-Security-Policy: frame-ancestors https://*.thepagethatembedsgalaxy 'self'

Is this supported? Any idea of what could be wrong?
Thanks

**Comment by jmchilton** [comment]
If you set x_frame_options to the empty string in config.yml/config.ini I think this should work. Alternatively you should be able to more securely restrict to just your origin by setting it to 'ALLOW-FROM https://example.com/' I think. I'm not expert on this topic but we were told it is more secure to restrict this by default so we have.

xref https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
xref https://github.com/galaxyproject/galaxy/commit/e1f768789415815993e2b38ee1fd1972ede9c53e

**Comment by enolfc** [comment]
Thanks for the hint @jmchilton, but the issue is not the browser refusing to load the iframe because restrictive ALLOW-FROM but the javascript inside the iframe trying to access the top object here:

https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/utils/utils.js#L124

**Comment by hexylena** [comment]
I'm not sure this is a configuration we currently intend to support. We have not had other requests to run this way, I guess if it comes up in the future as an important deployment option we can consider it? Otherwise closing for now.
