### ISSUE TITLE
The text field of tools can't support special characters in local galaxy

### ISSUE THREAD

**Issue by aifennng** [galaxyproject/galaxy#6390]
OS: CentOS 7 X64
Lang: en_US.UTF-8
Galaxy Version: 18.05
I develop some tools by myself. Sometime I want to input some special characters. But I found that the text field of tools can't support special characters, such as Greek alphabet and Chinese, neither other Parameter Types. If I input these characters, the tool get the value as "XXXXXX".
Is there any way to fix it? I have try to modify the file "lib/galaxy/tools/parameters/basic.py", not succeed.

**Comment by nsoranzo** [comment]
Have a look at https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-param-sanitizer , I think that should solve your issue.

**Comment by aifennng** [comment]
@nsoranzo Thank you for your help! I fix it by this
`<sanitizer sanitize="false" />`
