### ISSUE TITLE
Enable resource requests for data_manager tools

### ISSUE THREAD

**Issue by moskalenko** [galaxyproject/galaxy#6396]

**Comment by moskalenko** [comment]
This is from a discussion at the galaxy admins training session. It seems that data_manager tools do not have the resource request interface hook, so it's not possible to use resources appropriate to the genome size in questions, but a sometimes very high water mark has to be set based on the largest genome as a default instead. It would be great if we could actually set cpus, memory, and time when running data managers. All our admins are real users and have SLURM allocations.

**Comment by mvdbeek** [comment]
So we're limiting the resource selection at https://github.com/galaxyproject/galaxy/blob/65c1cd761c48ba121a847d4d501eb8a97a911e70/lib/galaxy/jobs/__init__.py#L383 to regular tools. I don't think there's a reason why we couldn't include data manager tools. We can look at that during the hackathon, or if you get a chance for testing this I'm happy to change this into `if tool_id and tool_type in ('default', 'manage_data'):`

**Comment by moskalenko** [comment]
I just tested it. I have a bowtie2 builder job running with a custom resource request. Yay! This is great.

Thank you!

Alex
