### ISSUE TITLE
Prevent tool from disappearing from tool panel if tool is broken during editing

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#6398]
I.e if you run planemo serve, modify the tool xml and break the syntax, the tool disappears from the tool panel and isn't watched anymore. This should be straightforward to fix.

**Comment by mvdbeek** [comment]
That's done and will be in 18.09

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/pull/6681
