### ISSUE TITLE
Migrations broken on mysql

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#6401]
This is with a fresh mysql 5.7 installation and database:

https://gist.github.com/mvdbeek/ef980138db903a9a0ad617f2ac95b025

Some of them are harmless and referencing keys that we eliminated later on, but a couple newer ones seem problematic, like

~~https://gist.github.com/mvdbeek/ef980138db903a9a0ad617f2ac95b025#file-mysql_migration-txt-L536~~ sequencing request table, eliminated long ago

~~https://gist.github.com/mvdbeek/ef980138db903a9a0ad617f2ac95b025#file-mysql_migration-txt-L872~~ eliminated in migration 91

https://gist.github.com/mvdbeek/ef980138db903a9a0ad617f2ac95b025#file-mysql_migration-txt-L1241 -- probably breaks data manager job association table on mysql, solution is to change TEXT type to `TrimmedString(255)` for `data_manager_id` in DataManagerJobAssociation. Which we also do for the tool_id, so this feels like the right thing to do

https://gist.github.com/mvdbeek/ef980138db903a9a0ad617f2ac95b025#file-mysql_migration-txt-L1391 -- needs to be 64 chars long max, so `workflow_invocation_step_output_dataset_collection_association_ibfk_1` is too long.

**Comment by FredericBGA** [comment]
https://gist.github.com/mvdbeek/ef980138db903a9a0ad617f2ac95b025#file-mysql_migration-txt-L1426
breaks workflow_invocation_step_output_dataset_collection_association which is not created in my database.
`workflow_invocation_output_dataset_collection_association_ibfk_1` is too long

**Comment by mvdbeek** [comment]
Right, missed that one. Same issue as with workflow_invocation_step_output_dataset_collection_association_ibfk_1

**Comment by dannon** [comment]
xref galaxy-dev ml thread: http://dev.list.galaxyproject.org/MySQL-errors-and-warnings-with-a-fresh-install-of-Galaxy-18-05-td4671440.html

**Comment by FredericBGA** [comment]
So, in order to do a simple test, how many tables do I will have at the end of migration ?
Right now:
> mysql> show tables;
>[...]
> 169 rows in set

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/issues/8400

**Comment by FredericBGA** [comment]
You can close this now.
