### ISSUE TITLE
Workflow step identification

### ISSUE THREAD

**Issue by saxtouri** [galaxyproject/galaxy#6405]
Hello,

I'm trying to find a way to identify a workflow step from the job runner. I use the "chronos.py" job runner. This is the flow so far:

1. An external application uses Galaxy REST API to start a workflow.
2. Galaxy sents workflow steps to a Chronos scheduler for execution
3. Steps are executed on a Mesos cluster
4. A monitoring service aggregates information from the cluster and extracts information on resource consumption, combining information from the REST API and the task execution logs on the Mesos cluster.

In order to do that, on step 2 I can attach metadata on the chronos tasks, which are then be identified by the monitoring service. I found out how to do that and it works.

The only step missing is, what metadata should I use?

I need some kind of id which is unique for each workflow step and is accessible in the code of a job runner (e.g. can be extracted from a job_wrapper object). This id should also be accessible through the Galaxy REST API. What id would you suggest I should use?

**Comment by mvdbeek** [comment]
@saxtouri If I understand the requirements correctly the workflow invocation step id should probably be appropriate, which associates a job and a step of a workflow, which you should be able to query using the job id. If instead the ID you want is the step of the workflow that is currently running and that should be the same for all jobs that run as part of the step you can use the workflow step id which you can recover from the workflow invocation step table.
That's fairly abstract, let me know if you need more details!

**Comment by hexylena** [comment]
Should be fixed in Marius' comment :)
