### ISSUE TITLE
Workflow editor needs an undo button

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#644]
Use case:
- Editing a workflow
- Haven't saved in a couple steps
- Accidentally delete a step and lose all of that progress
- Tears

**Comment by jmchilton** [comment]
Agreed this would be nice, but I'm switching label from bug to enhancement @erasche :).

**Comment by hexylena** [comment]
@jmchilton fair enough :)

**Comment by IsmailM** [comment]
+1

**Comment by nsoranzo** [comment]
:+1:

**Comment by mvdbeek** [comment]
We don't have an undo button, but nowadays you can select the last saved version, that is essential a undo operation.

**Comment by hexylena** [comment]
Sounds good for implementation. But maybe we could communicate this in a better way though (e.g. left / greyed out right buttons in the workflow editor top bar)? I don't think I would've thought to revert to a previous version.

and also I guess the previous version can be quite far back, maybe we can start generating more of these stored versions to ensure it behaves closer to a back button? E.g. an auto-save feature.
