### ISSUE TITLE
validator tag broken in 15.07

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#645]
report from https://biostar.usegalaxy.org/p/13905/

Since  the update to the version galaxy release_15.07,
the tag validator doesn't not work
the line below
`<validator type="regex" message="Error">^^[,0-9]+$ </validator>`
work with the previous version
since the lastet version it's failed

https://github.com/galaxyproject/galaxy/commits/dev/lib/galaxy/tools/parameters/validation.py

**Comment by guterl** [comment]
I have change for a test  the public  tool  galaxy-dist/tools/filters/fixedValueColumn.xml

the line

<param name="exp" size="20" type="text" value="1" label="Add this value"/>

is changed to

<param name="exp" size="20" type="text" value="1" label="My Add this value">
<validator type="regex" message="Not gonna happen">^^[,0-9]+$</validator>
  </param>
    <conditional name="taxonomy">
        <param name="taxo" type="select" label="Taxonomy" help="Select the taxonomies " >
           <option value="9606">Homo Sapiens</option>
           <option value="Other">Other</option>
   </param>
<when value="Other">
<repeat name="taxoId" title="taxonomy Id ">
<param type="text" name="taxo_id" label="Taxonomy ID" >
<validator type="regex" message="Not gonna happen">^^[,0-9]+$</validator>
</param>
</repeat>
</when>
</conditional>

with release 14-10 it's work fine

with release 15.07 the validator tag does nothing

**Comment by guterl** [comment]
have change for a test  the public  tool  galaxy-dist/tools/filters/fixedValueColumn.xml

the line

param name="exp" size="20" type="text" value="1" label="Add this value"

is changed to

`<param name="exp" size="20" type="text" value="1" label="My Add this value">`
`<validator type="regex" message="Not gonna happen">^^[,0-9]+$</validator>`
`</param>`
 `<conditional name="taxonomy">`
         `<param name="taxo" type="select" label="Taxonomy" help="Select the taxonomies " >`
            `<option value="9606">Homo Sapiens</option>`
            `<option value="Other">Other</option>`
    `</param>`
 `<when value="Other">`
 `<repeat name="taxoId" title="taxonomy Id ">`
 `<param type="text" name="taxo_id" label="Taxonomy ID" >`
 `<validator type="regex" message="Not gonna happen">^^[,0-9]+$</validator>`
 `</param>`
 `</repeat>`
 `</when>`
 `</conditional>`

with release 14-10 it's work fine

with release 15.07 the validator tag does nothing

in any field exp and taxo_id the error msg from validator are displayed

**Comment by guerler** [comment]
Closing this after tests with current release.
