### ISSUE TITLE
Choose data table from parameter

### ISSUE THREAD

**Issue by davidchristiany** [galaxyproject/galaxy#6475]
I successfully built a dropdown menu from a data table with "from_data_table", but didn't find how to do it dynamically by giving a parameter value containing the file name to from_data_table.

I would like to do it this way, I don't know if it is possible : 
`<param name="ids" type="select">`
`<options from_data_table="$ref"/>`
`</param>`

It works when I put the name referenced in the tool_data_table but when it is a value from a parameter it doesn't. I wonder if we can do it, the idea is to load the correct file to create a dropdown menu in function of a parameter.

**Comment by mvdbeek** [comment]
Can you elaborate on what you'r'e trying to achieve ?
The syntax you're suggesting indeed doesn't work, but I'm not sure I understand the rationale.

How would $ref in this example be defined ? Any chance the options could instead be taken from a dataset https://docs.galaxyproject.org/en/latest/dev/schema.html#from-dataset ? The options can then be further filtered using https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-param-options-filter

**Comment by hexylena** [comment]
Closed pending user response
