### ISSUE TITLE
Galaxy crashes for huge downloads

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6485]
I notices that my dev Galaxy crashes for huge downloads (28 GB bam file). There is nothing in the log. 

This galaxy runs on a virtual machine with limited memory and I noticed that memory usage increases fast when the download is initiated (it actually never starts) to approx 25GB. So I guess its a memory problem.

**Comment by nsoranzo** [comment]
How do you start the download? Clicking on the "disk" icon for the dataset?

**Comment by bernt-matthias** [comment]
Exactly. Is there another way for users?

**Comment by hexylena** [comment]
If you're encountering this issue you should use the `sendfile` extensions in apache/nginx
