### ISSUE TITLE
ftp_upload_purge flag in galaxy.yml is broken

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#6492]
I am attempting to get the desire behavior where files that are uploaded from the ftp_dir are then cleaned up from the directory. In release 17.09 that was the default behavior but not so in 18.05 .

I have set [ftp-upload-purge](https://docs.galaxyproject.org/en/latest/admin/options.html?highlight=ftp_upload_purge#ftp-upload-purge) to True in galaxy.yml and still does not clean uploaded ftp files.

After taking a look at the [upload.py](https://github.com/galaxyproject/galaxy/blob/release_18.05/tools/data_source/upload.py#L87) , it seems that is happening  ftp_upload_purge from galaxy.yml is not being used when determining if we are setting the in_place flag to True or false. 
When in_place is set to False, later on in [upload](https://docs.galaxyproject.org/en/latest/_modules/galaxy/datatypes/sniff.html#handle_uploaded_dataset_file_internal) , it will create a new temporary converted_path file instead of using the original one. That temporary file will be removed but not the original.

**Comment by Takadonet** [comment]
May look like that we have to modify this [line ](https://github.com/galaxyproject/galaxy/blob/release_18.05/tools/data_source/upload.py#L144)

`shutil.move(converted_path or dataset.path, output_path)`

because need to remove both converted_path **and** dataset.path when we have ftp-upload-purge set

**Comment by Takadonet** [comment]
Thanks for merging!

Question, is there any plans for back porting this regression into release_18.05 branch?

**Comment by martenson** [comment]
@Takadonet I will open the backport shortly

**Comment by Takadonet** [comment]
awesome! 
Thanks again.
