### ISSUE TITLE
Restore a deleted workflow

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6493]
potentially stupid question: is there a way to restore a deleted workflow. In Galaxy 18.05 and dev I could not find a way that does not involve editing the data base.

**Comment by mvdbeek** [comment]
They are just being marked as deleted. Undeleting is definitely something I would like to expose in the UI and API.

**Comment by natefoo** [comment]
A bit more info for admins: the table in question is `stored_workflow`. Once you find the correct workflow (e.g. with the help of the `user_id` column), update `deleted = false`.

This would be great to have in the UI/API.

**Comment by assuntad23** [comment]
Closed with #14794 & #14816
