### ISSUE TITLE
line number approximation of tabular data

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6506]
For tabular data (in my examples gtf) an approximate number of lines is shown. This approximation is often quite off, e.g.

- `~30,000,000 lines` for a data set with `28,147,144` lines
- `~8,700,000 lines` for a data set with `8,232,791` lines

I would like to know if there is a technical reason (but I could not find something in the code). And if not suggest one of the following solutions: 
- actually show a shorter representation like `~30 * 10^6`
- show the precise number (which would use the same space)

If I know where and have a suggestion how to solve this I would volunteer.

**Comment by tougai** [comment]
I have experienced the same problem, ie. different approximations when extracting first column of tabular file with cut (~3,300,000) and original file (~2,800,000). When i look at the files and do a wc -l on command line, i get the same number (2,711,716) for both .dat files.

**Comment by bernt-matthias** [comment]
Just found the code used for the estimation: 

https://github.com/galaxyproject/galaxy/blob/4b92f95e87b1af27bbb338e849f171176b320a89/lib/galaxy/datatypes/data.py#L787
