### ISSUE TITLE
Filter Failed does not take a collection output from a sub-worfklow as an acceptable input

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/galaxy#6514]
![out2](https://user-images.githubusercontent.com/20641402/42897089-2f196b40-8abf-11e8-8118-915bc65c7be2.gif)

The sub-workflow takes a list:paired collection as input (oddly, this is only represented as a single noodle) and outputs a collection of text files (also only represented as a single noodle).

The list:paired input *does* connect to Filter Failed, but as you can see from the Gif above, the output collection from the sub-workflow does not.

**Comment by mtekman** [comment]
Related to https://github.com/galaxyproject/galaxy/issues/6012

**Comment by jmchilton** [comment]
Do you have any idea if your Galaxy includes (https://github.com/galaxyproject/galaxy/pull/6178) - that might fix the problem or might not.

**Comment by hexylena** [comment]
Yes that is included, and we have rebuilt the client as of this morning due to an unrelated issue. @mtekman could you try it again now that we've rebuilt the client?

**Comment by mtekman** [comment]
Still no change on my side, the noodle fails to connect on either input or output as shown in the gif previously

**Comment by bgruening** [comment]
The same workflow has an additional problem as it seems, so I think this might be related. If it is executed all jobs from the subworkflow are scheduled and are running, the last step, the one after the subworkflow (column join) is not even scheduled and does not appear in the history.

The input in the subworkflow are two files and one paired-list, the expected output is one file. Now we are feeding a collection of paired-lists into the subworkflow so the expectation would be a list as output. But this seems to be broken as it seems. 
I would also expect a fat-noodle from paired-collections to the subworkflow and from the subworkflow to the column-join tool.

The workflow from above is here: https://usegalaxy.eu/u/mehmet-tekman/w/celseq2-new-super-workflow
The subworkflow is here: https://usegalaxy.eu/u/mehmet-tekman/w/celseq2-nodemulti-todo-update-featurecounts-include-umitools-count

**Comment by mvdbeek** [comment]
I'm working on this -- there are multiple problems, one of which is that we don't look up the `collection_type` if `collection_type_source` source is specified. This works OK for regular inputs, but not for instance `multiple="true"` inputs. In the same direction we need to update the collection type description when we connect and disconnect tools.

**Comment by mvdbeek** [comment]
Should be done in https://github.com/galaxyproject/galaxy/pull/6732 -- it'll be in 18.09
