### ISSUE TITLE
subworkflow runs do not iterate correctly over inputs

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#6518]
The following image is showing a job that is not able to run because it waits for themself to be finshed. `15: ... on 15`

@jmchilton I could get more information as this seems to be reproducible on usegalaxy.eu with 18.05.

![workflow_error](https://user-images.githubusercontent.com/469983/42966798-8a37b632-8b9e-11e8-84fd-76fae79df50b.png)

**Comment by mvdbeek** [comment]
Could you share the workflows? This isn't necessarily a bug if 15 is the result of an implicit conversion.

**Comment by bgruening** [comment]
Sure: https://usegalaxy.eu/u/mehmet-tekman/w/celseq2-new-super-workflow
I will check for implicit conversion, but it is just this single dataset out of a collection.

**Comment by bgruening** [comment]
Thanks for the hint about the implicit conversion. I just looked at all the files of the user and found one set that was marked as deleted. So this is the reason I guess, will test it shortly. There was no indication for the users what went wrong and that the dataset was marked as deleted and the numbering of the datasets seems still to be a bug, isn't it?

Should I keep this issue open?

**Comment by mvdbeek** [comment]
The dataset will turn blue and there should be a notification in dev / 18.09 when this happens.
The numbering (HID) of implicitly converted datasets is always the same as the unconverted dataset. I'd be open to remove that specialcase if someone knows why this is being special-cased in the first place.

**Comment by mvdbeek** [comment]
When I look at the json I also see
```json
...
"tool_state": "{\"__page__\": null, \"extract_method\": \"\\\"string\\\"\", \"input_type\": \"{\\\"input_readpair\\\": {\\\"__class__\\\": \\\"RuntimeValue\\\"}, \\\"barcode\\\": {\\\"barcode_select\\\": \\\"first_read_only\\\", \\\"__current_case__\\\": 0}, \\\"type\\\": \\\"paired_collection\\\", \\\"__current_case__\\\": 2}\", \"__rerun_remap_job_id__\": null, \"bc_pattern\": \"\\\"NNNNNNCCCCCC\\\"\", \"print_log\": \"\\\"true\\\"\", \"prime3\": \"\\\"true\\\"\", \"quality\": \"{\\\"quality_selector\\\": \\\"false\\\", \\\"__current_case__\\\": 0}\", \"barcodes\": \"{\\\"filter_correct\\\": \\\"false\\\", \\\"filter_barcode_file\\\": {\\\"__class__\\\": \\\"RuntimeValue\\\"}, \\\"__current_case__\\\": 1, \\\"use_barcodes\\\": \\\"yes\\\"}\"}",
...
```
There are some runtime values in the subworkflow at the umi-extract step, this is currently not working, I think.

**Comment by bgruening** [comment]
> The numbering (HID) of implicitly converted datasets is always the same as the unconverted dataset.

As far as I can tell this was __not__ and implicit conversion. The datasets inside the paired-dataset was marked as deleted.

**Comment by bgruening** [comment]
> There are some runtime values in the subworkflow at the umi-extract step, this is currently not working, I think.

The workflow, at least for the parts that are not stuck in the grey state, seems to run through.
`input_readpair` is the paired-collection that goes into the subworkflow and the other RuntimeValue is `filter_barcode_file` which is supposed to be the barcode file afaik. So both are inputs in the subworkflow.

Thanks for looking into it.

**Comment by mvdbeek** [comment]
> The workflow, at least for the parts that are not stuck in the grey state, seems to run through.

Alright, though I'm not sure how that is even possible if there are RuntimeValues in the state. Grey states / No warning being shown when an input is deleted will be fixed with a new release, but that's too intrusive to backport IMO (https://github.com/galaxyproject/galaxy/pull/6036).

> The following image is showing a job that is not able to run because it waits for themself to be finshed. 15: ... on 15

I'm not convinced this is waiting for itself, this probably couldn't even be scheduled. Can you share the history ?

**Comment by mvdbeek** [comment]
@bgruening any chance we can look at the history ?

**Comment by mvdbeek** [comment]
I'm gonna close this, we can re-open this if it re-appears.
