### ISSUE TITLE
Workflow fails to launch after extracting and using "run" link, with no warnings

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6522]
test history: https://usegalaxy.org/u/jen/h/test-history-dinky-wf

Contains one input and two jobs. Both jobs run from the history fine and represent different versions of the tool.

When a workflow is extracted from the history, using the "run" link produces this, *whether the new or old version of the tool is included in the extracted wf*:

<img width="227" alt="screen shot 2018-07-20 at 2 49 47 pm" src="https://user-images.githubusercontent.com/8999735/43027237-19427332-8c2e-11e8-96c8-a130e0026f45.png">

ping @dannon

**Comment by mvdbeek** [comment]
I think this was fixed in https://github.com/galaxyproject/galaxy/pull/6571
