### ISSUE TITLE
[Feature Request]: Users should be allowed to run published workflows without making a personal copy first

### ISSUE THREAD

**Issue by alexlenail** [galaxyproject/galaxy#6526]
In our group, we have a reference workflow for RNA-seq, among others. Users would like to run that workflows. Unfortunately, right now, they must go to shared data > workflows and _make a copy_ of each workflow before they can use it. If the reference workflow is updated, then they still have a copy of the outdated workflow. With many users and a frequently updating reference workflow, this means any given user might have any given version of the reference workflow. What would be better is if they could run the published reference workflow without copying it first.

**Comment by mvdbeek** [comment]
Will be in 18.09, xref #6428
