### ISSUE TITLE
Workflow doesn't run jobs on history

### ISSUE THREAD

**Issue by drthanwho** [galaxyproject/galaxy#6527]
After running a workflow whether it is in the same a history or send to a new one there are now queued job initiated in the history.  After running workflow I will get the green box confirmation for running the workflow and a new history will be created if I have chosen to run in a new one but absolutely nothing else happens after that. I saw that this has happened before and it was fixed but seems like it is still occurring. 

Anyone has any ideas about this? (Running on main)

**Comment by soufanom** [comment]
@drthanwho Is the workflow based on an input collection? Can you share what you receive in the log output files? I am facing a very similar issue at the moment. When I tried to use "Input dataset collection" from Inputs tab, it seems it is able to start running only if I re-run the whole local galaxy server!

**Comment by drthanwho** [comment]
I don't know about that but workflows are failing in general in the main galaxy server. It has been an ongoing issue for the past week.  I have been able to run them just fine on the Europe server however

**Comment by mvdbeek** [comment]
There were some bugfixes recently to this, but for problems with the public servers it'd be more helpful to post on biostars (https://biostar.usegalaxy.org/) or to pop in on gitter (https://gitter.im/galaxyproject/Lobby).
