### ISSUE TITLE
unicycler tool error

### ISSUE THREAD

**Issue by daschiemann** [galaxyproject/galaxy#6530]
all unicycler jobs result in tool error! Before it used to work.

**Comment by bgruening** [comment]
@daschiemann where does this happen? usegelaxy.eu?

**Comment by daschiemann** [comment]
Hello Björn,
I run unicylcer under galaxy and get an tool error during assembly with any
dataset I use.
Thanks for your efforts!

**Comment by bgruening** [comment]
But which Galaxy server are you using, your own local one or one of the public ones?

**Comment by daschiemann** [comment]
public one!

**Comment by daschiemann** [comment]
Is there anything wrong with the public ones?

**Comment by bgruening** [comment]
Which one :) https://usegalaxy.eu or https://usegalaxy.org?

**Comment by daschiemann** [comment]
.org

**Comment by bgruening** [comment]
Ok, I don't have any control about this server. I will ping some friends and see what they can do. You could try to use https://usegalaxy.eu in the meantime.

**Comment by bgruening** [comment]
Ok, I don't have any control about this server. I will ping some friends and see what they can do. You could try to use https://usegalaxy.eu in the meantime.
