### ISSUE TITLE
Tool Form Enhancements - ids and rendering

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#6540]
I started looking at this to deprecate tour_ids (xref #6471, per https://github.com/galaxyproject/galaxy/compare/dev...dannon:deprecate-tour-id?expand=1), and of course it's a little more complicated than I had hoped.

Right now we need form-data uids (like `uid-1234`, on every input) to map between all possible inputs and the 'flattened' input names like `input0|input`, etc. which are actually used server side.  The problem is that between the branches of a conditional, we'll have the same ids, like `conditional|input0`, for both branches.  The back end handles this fine with the flattened naming scheme because it takes into account the toggling of the conditional to know which parameter the value applies to.  The front end just uses `uid-1234` notations and a lookup table to add all of this to the dom at once, relying on those lookups and element selectors to reason about things.  Instead of using the dom to find/iterate child elements, each form section should just have object handles, as well.  Then we can drop all the lookup tables, use `id` elements on page that match exactly the elements the API takes, and everything is a lot simpler.

It will likely even improve performance to only add to the dom the half of the conditional we need (destroying/creating elements on toggle, not creating for *everything*) and it'd allow us to drop the extra uid-1234 -> `input0|input` mapping.

Long term, it'd be *really* great to rewrite this all as vue components using data bound to template conditionals and the like.  Short term, it might suffice to stop injecting and hiding form inputs, and add them to the table on conditional/section toggles?

@guerler Let me know if I missed something.

**Comment by guerler** [comment]
One benefit to keep in mind is that switching back-and-forth between conditionals should not reset parameters within the briefly disabled conditional sections. The current approach does this somewhat naively by preserving the entire structure and values of nested conditionals and repeats. There is one complete representation of the tool form, represented as an XML-tree, containing all input identifiers. Only a subsection of these are mapped to the flat-representation when communicating with the server.

**Comment by guerler** [comment]
`tour-ids` have been deprecated, instead input elements can now be accessed through `[id='form-element-NAME']`. All lookup tables have been dropped when the forms were vueified. Closing this for now, please re-open if I missed something here.
