### ISSUE TITLE
More emphasis on selected option for booleans

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#6543]
![image](https://user-images.githubusercontent.com/155398/43277653-afef4772-90d6-11e8-991b-a89223c63a5c.png)

It's not immediately obvious (without toggling it and playing with the options) which one of these is selected.  We should probably add something extra to make it more clear at-a-glance.

I tinkered with adding a `(yes)`, but didn't like it.  Maybe an `*` in the text of the currently selected one?  I dunno, will require some experimentation.

Suggested by @Slugger70 on IRC.

**Comment by mvdbeek** [comment]
~~From the tool authors' side this should probably always be phrased avoiding the negative. The option would be unambiguous if it were "use compression", right?~~ Or is this about whether yes is actually selected?

**Comment by dannon** [comment]
Definitely agreed there, and some tools do, I just picked the worst example I found quickly, requiring a double negative here :)

**Comment by guerler** [comment]
How about changing the background from dark gray to green for the selected option?

**Comment by dannon** [comment]
@guerler Yeah, I experimented with color a bit but the very bright green we use for affirmative was super distracting (visually) on the form, to me.  Maybe if we do the green, but muted? (using the defaults, it stood out even more than the execute button, to me)

**Comment by jxtx** [comment]
Why not brand primary rather than success`?

**Comment by dannon** [comment]
@jxtx Then it's the same color as the execute button, which seems to de-emphasize it too much.  A lighter version of it though, might work better.

**Comment by martenson** [comment]
I like the implementations that are imitating the actual switch buttons
(can be seen in both ios and android). Something like:

**Comment by mblue9** [comment]
Maybe not possible or a good idea here, but I was just doing some BLAST searches and noticed they highlight non-default in yellow and with an icon like this:

![screen shot 2018-07-27 at 12 02 33 pm](https://user-images.githubusercontent.com/5591821/43297546-484e0454-9195-11e8-9d1c-5a1cd274f2b8.png)

Actually, I think that's more relevant for identifying non-default than what's already selected as default. For identifying what's default selected, what about an arrow like this (from https://ux.stackexchange.com/questions/46207/how-to-highlight-the-selected-option-when-there-are-only-2-elements)

>As you correctly point out, this is a typical problem you encounter when you have a set of only two elements: it's never quite clear which element is selected. It seems to be difficult to highlight or otherwise emphasize the currently selected element. In my experience, stemming mostly from user research we did, what works for one user, doesn't work for others. You can't imagine how many discussions I had and how much advice I got on how to make this clear. Even using a highlight color (e.g. blue) wasn't always working
In the end, what worked best for us was to connect the buttons with the view they toggle and to indicate the currently selected view with an arrow.

**Comment by martenson** [comment]
added pic, seems email-to-github ignores them

![toggle](https://user-images.githubusercontent.com/1814954/43369314-088b7bfc-936c-11e8-8cfa-dceef87ad489.jpeg)

**Comment by Slugger70** [comment]
I like that style @martenson. The whole thing came up in a tutorial I was giving and about 4 of the students said it wasn't obvious. Thanks for working on it. I pointed out to the students that this response is an example of why we should be using Galaxy.. 😄

**Comment by dannon** [comment]
Yeah, I experimented a bunch with just changing the active colors and wasn't really happy with any of it -- I'm also leaning towards a more structural representation of the selected option, whether skeuomorphic or something simpler like a `^` at the bottom of the selected toggle, etc.

**Comment by bernt-matthias** [comment]
Seems implemented as suggested by @martenson .
