### ISSUE TITLE
Expose API call equivalent to View Details (i) icon in the current Web UI

### ISSUE THREAD

**Issue by andreyto** [galaxyproject/galaxy#6556]
This is very useful for getting a record of how a given dataset was produced. For example, in a clinical application where a requirement is to have a human-readable record that another end user can later use to reproduce the prior results through the UI. This means listing the names of the parameters as they are called in the rendered tool Web form, not as the Cheetah variables. Such application, however, requires a way to pull this information automatically from the backend through the API.

The 'i' icon corresponds to `datasets/<history content API ID>/show_params` URL in the Web controller.

![image](https://user-images.githubusercontent.com/136912/43410157-f3143eb6-93f3-11e8-94ea-56ede5947563.png)

The closest API call would fit the bill is `/api/jobs/{id}/build_for_rerun`, but it still requires quite a bit of processing to make the output user-readable.

**Comment by dannon** [comment]
We'll need this information to convert the `show_params.mako` to a new-style component as well.

**Comment by mvdbeek** [comment]
We still need to convert show_params.mako, but the API endpoints that builds parameter key value pairs on the backends are
```
        * GET /api/jobs/{job_id}/parameters_display
        * GET /api/datasets/{dataset_id}/parameters_display
```
This was added in https://github.com/galaxyproject/galaxy/pull/8022
