### ISSUE TITLE
Auto-labelling for subworkflows broken

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#6560]
This functionality was introduced in https://github.com/galaxyproject/galaxy/pull/4346, but seems completely untested.

An example from @selten where this breaks down is this:
https://files.gitter.im/galaxyproject/Lobby/RqlO/2018-07-31-18_44_14-Galaxy.png
![image](https://user-images.githubusercontent.com/6804901/43475467-3402a568-94f6-11e8-9fe8-3664a6914b6d.png)
![image](https://user-images.githubusercontent.com/6804901/43475478-3bb3c332-94f6-11e8-993b-d6921ab0b684.png)
![image](https://user-images.githubusercontent.com/6804901/43475501-482f3d80-94f6-11e8-9c8f-882ab9c8be00.png)
 
The error is `Exception: Workflow evaluation problem - failed to find output_name 2:out_file1 in step_outputs {u'1:output': <galaxy.model.HistoryDatasetAssociation object at 0x7f32e4154990>, u'1:out_file1': <galaxy.model.HistoryDatasetAssociation object at 0x7f32a8ef6450>}`

Manually labelling the output works

**Comment by mvdbeek** [comment]
I've tried reproducing this, and I can't, but I've noticed that sub2 shows you 2 possible outputs, `0:output` and `1:out_file1`. IIRC this a bug we fixed, and might well be the issue you're seeing. In any case we don't have automated tests for this, so I will add those.

**Comment by mvdbeek** [comment]
Actually `0:ouput` is the input module, that is what has been fixed by https://github.com/galaxyproject/galaxy/pull/4346. This should have been in 17.09 from the beginning. @selten What version of galaxy are you using ?

**Comment by selten** [comment]
@mvdbeek I have tested it on both 17.05 and 18.01. The results were the same.

**Comment by mvdbeek** [comment]
Did you redo the sub2 workfow on 18.01 ?

**Comment by mvdbeek** [comment]
I tested this on 18.01 just now and it works as well, I'm inclined to believe this is an issue with the parent workflow being created on 17.05 (with a HEAD that predates the backported fix in https://github.com/galaxyproject/galaxy/pull/5172)

**Comment by selten** [comment]
![2018-08-06 10_58_57-galaxy _ workflow editor](https://user-images.githubusercontent.com/961090/43707216-d085b392-9967-11e8-8872-ffb39466f4c6.png)
This doesn't execute sub2.
`Exception: Workflow evaluation problem - failed to find output_name 1:out_file1 in step_outputs {u'2:out_file1': <galaxy.model.HistoryDatasetAssociation object at 0x7ff5682e8f50>}`

**Comment by mvdbeek** [comment]
Can you upload the workflow (or send it to me) ?

**Comment by mvdbeek** [comment]
Nevermind, I got it, I didn't include the Line/Word/Character count step, with it I can reproduce the issue. I think the problem is that we reference the steps numerically, but if we include another step we shift around the step numbers. I think if reference the step UUID this should work.

**Comment by selten** [comment]
[Galaxy non-working workflow.zip](https://github.com/galaxyproject/galaxy/files/2261872/Galaxy.non-working.workflow.zip)
[Galaxy working workflow 1705.zip](https://github.com/galaxyproject/galaxy/files/2261879/Galaxy.working.workflow.1705.zip)

One of them is the one that works on 17.05 (with labelling).
The other one doesn't work on 17.05 or 18.01.

**Comment by selten** [comment]
I just put that step in so dataset recognition worked

**Comment by mvdbeek** [comment]
OK, I think I figured it out -- we're replacing the step index when executing with the outer workflow step (which is subject to change when adding new steps), when it should be the inner step. Just gotta think about a good test and then I'll open a PR.
