### ISSUE TITLE
Job API reports job state from DB, history contents api disagrees

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#6576]
I killed a bunch of jobs that had never started, moving their state to `new_manually_dropped` (and later one to `error` in case that would fix it.)

Jobs API:

![auswahl_176](https://user-images.githubusercontent.com/458683/43828951-5c8bd7fa-9aed-11e8-8830-5454f735aab7.png)

history contents API

![auswahl_175](https://user-images.githubusercontent.com/458683/43828920-4a04a5d0-9aed-11e8-84fa-9c7d8bd733d7.png)

Do I need to take some extra step? Just following instructions from https://github.com/galaxyproject/galaxy/issues/5944

**Comment by hexylena** [comment]
ping @natefoo

**Comment by hexylena** [comment]
![image](https://user-images.githubusercontent.com/458683/51396295-bb88cf00-1b36-11e9-8dcf-e565e7331ad4.png)

looks kinda funny :)

**Comment by natefoo** [comment]
The history contents API/UI comes from the hda and dataset `state` columns, which are not updated when a job's `state` is manually updated. I have a change to `scripts/helper.py` that can actually fail jobs by ID and properly set output states, I'll PR that (or better yet, integrate into gxadmin) when I have a minute.

**Comment by hexylena** [comment]
I have a function in gxadmin for this now. Can close this.

Op do 14 feb. 2019 00:14 schreef Nate Coraor <notifications@github.com:

**Comment by hexylena** [comment]
https://github.com/usegalaxy-eu/gxadmin#mutate-fail-terminal-datasets can be used for anyone who needs this.
