### ISSUE TITLE
purge Galaxy users and their data/histories/data libraries - recommended approach?

### ISSUE THREAD

**Issue by AjitPS** [galaxyproject/galaxy#6603]
As the Admin of the _**Galaxy** instance_ at our institute, I am trying to free up storage space by removing users who have left the institute or no longer use Galaxy (i.e., with a last login cut-off time of 3 years).

I can go into the **Admin** panel and _delete a user_, then **purge** them. But that _doesn't_ get rid of all the data (to free up disk space/ quota) used by them. (similar to #930)

After purging some users, I tried running the **clean_up scripts** (in the recommended order) but that doesn't seem to free up space either. https://galaxyproject.org/admin/config/performance/purge-histories-and-datasets/#deleting-datasets-purging-dataset-instances

What is the _recommended way_ of going about this?, i.e., permanently removing a user account and their data/histories. Thanks.

**Comment by mvdbeek** [comment]
So these instructions always require histories or HistoryDatasetAssociations to be deleted before any space is freed by deleting the actual dataset. I am not sure that deleting a users also deletes their histories, but that would be reasonable, I think.

**Comment by mvdbeek** [comment]
So one way to do this is to mark the deleted users' history as deleted, and I will see if we can add an option for that to the cleanup scripts.

**Comment by AjitPS** [comment]
Thanks, it would be useful if an Admin deletes a user via the Admin Panel, and then also purges the account, for all history and datasets of that user to be marked deleted so the clean-up scripts can remove them.

**Comment by AjitPS** [comment]
What I have currently are 30+ deleted and `purged` user accounts (including some using 4-5 TB of disk space) on our _institute's Galaxy instance_, but their disk space is still shown _in use_.

If I now _undelete_ them via the admin panel, I can impersonate them but find **no** data/history in their account. 

However, the clean-up script doesn't free up any of the space that we expected, as I guess the user is marked deleted and purged but the history/dataset if left as is in `/database/files/`. I thought it would be a `userless` history and so that clean-up script would remove it but it doesn't seem so.

Any advice on _how_ to proceed and **free up space** would be helpful. Thanks.

**Comment by AjitPS** [comment]
If for all purged users, their histories are set to be *userless*, then that running that clean-up script: `scripts/cleanup_datasets/delete_userless_histories.sh` would free up all their user disk space.

**Comment by hexylena** [comment]
This will be fixed in https://github.com/galaxyproject/galaxy/pull/8309

I guess the current workaround would be to write some SQL to mark those user's histories as deleted, and then running the cleanup scripts.
