### ISSUE TITLE
Saved Pages malformed id in usegalaxy.org

### ISSUE THREAD

**Issue by toniher** [galaxyproject/galaxy#6617]
Sorry if this is not the proper location to report it, since yesterday's migration, it seems that many pages in https://usegalaxy.org/pages/list_published are getting a malformed id error.
As example I created one a few days ago https://usegalaxy.org/u/toniher/p/deeptools-pergola , I can continue editing it, but I cannot view its content.
Let me know if I should report it somewhere else.

Thanks!

**Comment by dannon** [comment]
@toniher Thank you for reporting this, I'll take a look!

**Comment by dannon** [comment]
So the problem here is that pages internally save the contents hashes instead of raw ids.  I'm working on ideas for fixes, but it's going to take a little work.

**Comment by toniher** [comment]
It seems it's already working! Thanks for solving this!

**Comment by dannon** [comment]
@toniher It is!  Sorry I forgot to update this issue, we took care of it last week.
