### ISSUE TITLE
infinite site reloading for API keys page

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6625]
I just started a clean dev galaxy, added a user and made him a admin. When loading the AKIKeys section in the admin panel the page reloads all the time.

**Comment by mvdbeek** [comment]
I can reproduce this, it doesn't even need to be a new user, thanks for the report.

**Comment by dannon** [comment]
I can take a look.  I deleted this interface and combined it with the user admin grid recently (dev)~~, but we'll still need a fix for 18.05~~.  I misread, this is in dev?  That interface shouldn't exist, let me see what's up.

**Comment by mvdbeek** [comment]
Maybe we'll have to delete the compiled mako templates

**Comment by dannon** [comment]
It's all javascript now.  I don't know if it was a bad merge that put it back or what, but that menu item shouldn't exist.  I'm opening a PR to fix it now.
