### ISSUE TITLE
Galaxy 18.05 - favicon.ico missing, changes to welcome.html?

### ISSUE THREAD

**Issue by AjitPS** [galaxyproject/galaxy#6634]
Hi, we have recently updated our **Galaxy** instance from 17.05 to `18.05`, but I'm getting an **html** error for `favicon.ico` (`404 not found`) despite us not making any changes/additions to the welcome page's `<head>` code, for the UI.

We did customize `/static/welcome.html` to add some info in the `<body>` section but strangely, when we load the homepage, browser console says `not found` for `favicon.ico` but the rest works fine. I'm wondering why didn't it use the Galaxy defaults for `favicon`?

**Comment by mvdbeek** [comment]
Not sure what's going on here, but could this be a proxy issue ? Are you serving galaxy on a subdir ?

**Comment by martenson** [comment]
favicon does not show for me on dev or 18.05 (without proxy) and it should. I do not get the 404 though

@AjitPS what is the exact path that returns the 404?

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/usegalaxy-playbook/blob/8825178e89a49d611e92a5a01606dbaf8324c6d8/env/main/templates/nginx/usegalaxy.j2#L101 -- you'll have to add this or the apache equivalent to your proxy config.

**Comment by AjitPS** [comment]
Thanks, this error popped up on our **test** instance. But, I do **not** get _**that**_ error message in our live, **production** instance (yet **no** `favicon` is displayed). 

@mvdbeek We have the following in the `nginx.conf`, using full path to `favicon.ico`:
`location /favicon.ico {`
`            alias /home/usern/galaxy/static/favicon.ico;`
`        }`


So, is this a bug in **18.05** then? As, on both our **production** and **test** instances, the `favicon `doesn't show up though (**Galaxy 18.05**).

**Comment by AjitPS** [comment]
On our **production** instance, 1 issue we have is what my colleague **Asier** pointed out on Gitter earlier this morning, we have customized the `/static/welcome.html` page to change logo in <head> besides adding other info. in <body>.

Everything works, but the **logo** image in <head> doesn't show up and so we have no logo in browser tab <head>

**Comment by AjitPS** [comment]
> show

So, is this a bug in 18.05 then?

**Comment by mvdbeek** [comment]
No, it should have always been there, and it works for usegalaxy.org or my local instances.

**Comment by AjitPS** [comment]
> favicon does not show for me on dev or 18.05 (without proxy) and it should. I do not get the 404 though
> 
> @AjitPS what is the exact path that returns the 404?

so it works for you now? Am not sure what we are missing here, as we have the correct settings in `nginx.conf` as well

**Comment by mvdbeek** [comment]
did you restart nginx ?

**Comment by mvdbeek** [comment]
Also without a proxy in front this is dynamically rewritten to static/favicon.ico, so you will see a 404 if you got to url/favicon.ico, but the icon is actually correctly displayed.

**Comment by AjitPS** [comment]
Haven't restarted nginx as before our recent update to **18.05**, this was working.
also, I can view the `favicon` at `url/static/favicon.ico`. I don't get a 404 now, since the last Galaxy-test restart but it doesn;t get displayed in the browser either.

Secondly, if when we edited the `welcome.html`, most of our changes went fine. But changing the `<title>` from _Galaxy_ (default) to _Galaxy-test_ for our test instance didn't work.

**Comment by mvdbeek** [comment]
> Secondly, if when we edited the `welcome.html`, most of our changes went fine. But changing the `<title>` from _Galaxy_ (default) to _Galaxy-test_ for our test instance didn't work.

If you want to change the brand you would do this in the galaxy.ini https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.yml.sample#L653

> Haven't restarted nginx as before our recent update to **18.05**, this was working.

So if you didn't already have the favicon.ico in your nginx.conf then it probably didn't work before either.

> also, I can view the `favicon` at `url/static/favicon.ico`. I don't get a 404 now, since the last Galaxy-test restart but it doesn;t get displayed in the browser either.

It has always been at static/favicon.ico

**Comment by mvdbeek** [comment]
To verify that all is working correctly behind a proxy you need to navigate to `url/favicon.ico`, and then you should see the galaxy logo. If there's no proxy the routing will be done by a  middleware, so you expect a 404 at url/favicon.ico

**Comment by AjitPS** [comment]
> > If you want to change the brand you would do this in the galaxy.ini https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.yml.sample#L653
> 
> So if you didn't already have the favicon.ico in your nginx.conf then it probably didn't work before either.
> 

> It has always been at static/favicon.ico

Thanks for the `brand` info. Have changed it now.

Regarding `favicon` logo, we have _always_ had the `static/favicon.ico` location in our `nginx.conf` and it worked for us in the past few years. Just verified the settings and restarted `nginx`. And now, when I logout and login again on Galaxy-test, brower console shows: `GET http://galaxy-test.rothamsted.ac.uk:8080/favicon.ico 404 (Not Found)`

**Comment by mvdbeek** [comment]
Then your redirection doesn't work. Is it Galaxy you're connecting to or nginx ?

**Comment by AjitPS** [comment]
We haven't changed the `nginx` settings since using Galaxy 15.01. I can try and ask our sys-admin @William-Brown for some input as he knows more about our nginx setup

**Comment by mvdbeek** [comment]
This should be fixed with #6743, but if that works for you it means that you're not actually using nginx at all.

**Comment by martenson** [comment]
note that browsers cache the favicon of all visited sites, so it can take some time to refresh unless you force it to
