### ISSUE TITLE
Enhancement request: Add wig/bigWig input datatypes to LiftOver 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6646]
Consider adding in this functionality. 

Related UCSC Genome Browser Google group Q&A: 

 - Original: https://groups.google.com/a/soe.ucsc.edu/d/msg/genome/rKYp4g9NtJE/ys-_bmbXAAAJ
 - Reply:

**Comment by hexylena** [comment]
I think crossMap is the current alternative?

**Comment by jennaj** [comment]
I'll check it out, thanks for tip!
