### ISSUE TITLE
Jupyter doesn't currently work at .org, .eu and .org.au

### ISSUE THREAD

**Issue by mblue9** [galaxyproject/galaxy#6649]
Just to let you know. I've tried to launch a Jupyter IE at all three usegalaxy* (usegalaxy.org, usegalaxy.eu and usegalaxy.org.au) and none of them appear to work.

It either hangs on launching like below:
<img width="580" alt="screen shot 2018-08-29 at 9 19 38 am" src="https://user-images.githubusercontent.com/5591821/44756189-c7b2c680-ab6c-11e8-8dd7-e08f0d7aa4ba.png">

Or gives the error:
<img width="767" alt="screen shot 2018-08-29 at 9 18 29 am" src="https://user-images.githubusercontent.com/5591821/44756202-d4371f00-ab6c-11e8-9879-8c30b521669d.png">

**Comment by martenson** [comment]
This has been long resolved, sorry for keeping this issue alive.
