### ISSUE TITLE
job environment variables in job_conf

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6650]
Tried to set environment variables via `<env id="VAR">CONTENT</>` the destinations of my job_conf. On my dev instance (not the latest commits...) this seems not to work. 

I tried the (essentially) identical configuration on mt 18.05 instance where it works (the variable is exported in the galaxy_JOBID.sh).

**Comment by mvdbeek** [comment]
We have at least 1 test for this https://github.com/galaxyproject/galaxy/blob/release_18.09/test/integration/test_cli_runners.py#L74, so this shouldn't be broken, if this is still a problem let us know how we can reproduce this.
