### ISSUE TITLE
tool_dependencies action type="shell_command" stops after comment

### ISSUE THREAD

**Issue by yhoogstrate** [galaxyproject/galaxy#666]
In tool_dependencies.xml, it seems that XML comments terminate the functionality of a shell_command.
The following code:

```
<action type="shell_command">
    echo "a" ; 
    echo "b" &amp;&amp;
    echo "c" ;

    <!--
    comment
    -->

    echo "d" ; 
    echo "e" &amp;&amp;
    echo "f" 
</action>
```

Results in the following INSTALLATION.log:

```
#############################################
<env stuff>


                    echo "a" ; 
                    echo "b" &&
                    echo "c" ;


STDOUT
a
b
c
#############################################

#############################################
<env stuff>


                    echo "a" ; 
                    echo "b" &&
                    echo "c" ;


STDERR

#############################################
```

**Comment by nsoranzo** [comment]
I think you can use XML comments only between elements:

``` xml
<action type="shell_command">echo "a"</action>
<!-- comment -->
<action type="shell_command">echo "b"</action>
```

while inside a "shell_command" action you can only use shell comments.

**Comment by davebx** [comment]
With the base python XML parser, comments inside action tags don't break the processing.

**Comment by yhoogstrate** [comment]
@nsoranzo The thing is that the comment should not be interpreted by the toolshed parser at all, since it's at the XML level. A valid XML parser should strip the comment before passing it through to galaxy. If that is done correctly, inside a "shell_command" action, only the actual command remains which would echo a, b, c, d, e, and f.

The comment from the example is valid according to the XML specification: _"Comments may appear anywhere in a document outside other markup"_ (http://www.w3.org/TR/REC-xml/#sec-comments)

@davebx do you mean that you can not reproduce this issue? (I don't know how galaxy takes care of this internally)

**Comment by nsoranzo** [comment]
I was just explaining how it works now and suggesting a workaround, I'm all for fixing it.

**Comment by davebx** [comment]
@yhoogstrate I can reproduce the issue, trying to figure out a fix now.

**Comment by yhoogstrate** [comment]
I found another issue related to comment tags in tool_dependencies.xml.
Comments inside the _`<package />`_ tag break the installation of tools, resulting in the following error:

_Error installing tool dependency `<tool name>`: 'NoneType' object has no attribute 'process_tag_set'_

An example is given in the following 2 figures:

![xml](https://cloud.githubusercontent.com/assets/2264697/9578487/b3f9b4d6-4fea-11e5-9d52-f76a23c3ddbe.png)
![error](https://cloud.githubusercontent.com/assets/2264697/9578490/b8181710-4fea-11e5-88cf-6afd60adc7ff.png)

**Comment by davebx** [comment]
@yhoogstrate Is that your crossmap on the main toolshed?

**Comment by yhoogstrate** [comment]
yes, it works since I've removed the comments
