### ISSUE TITLE
v18.05 tarball's run.sh does not work on CentOS 7.5

### ISSUE THREAD

**Issue by eslerm** [galaxyproject/galaxy#6667]
This was tested on a fresh CentOS 7.5 VM and a Debian 9.5 VM under a non-root user account. On CentOS I additionally installed gcc and bzip2 and on Debian I installed gcc and make.

`sh run.sh` works when using a fresh git clone of galaxy and using the [most recent github commit of branch release_18.05](https://github.com/galaxyproject/galaxy/commit/03c485ee45e96784b269896a23223d233c566b890) on both VMs.

`sh run.sh` does not work when using the [v18.05 tarball](https://github.com/galaxyproject/galaxy/releases) or checking out [the commit which the tarball was made from](https://github.com/galaxyproject/galaxy/commit/ce362e60abbafdffa65acaf68f9492cec7196a9d) on CentOS. `sh run.sh` works on the Debian VM just fine.

The CentOS error comes from yarn not finding `package.json` in the galaxy directory. Perhaps something else is not running to make this file?

Updating the v18.05 zip and tar file to the [most recent commit on the release_18.05 branch](https://github.com/galaxyproject/galaxy/commit/03c485ee45e96784b269896a23223d233c566b890) should resolve this issue.

**Comment by nsoranzo** [comment]
@eslerm Running from a tarball has never been supported. It's very likely that the bug you encountered has been fixed on the release_18.05 branch (which is what we support).
I'm therefore closing the issue, but feel free to comment if you don't agree.

**Comment by eslerm** [comment]
@nsoranzo, the issue has been fixed in the way you suggest. The v18.05 tarball [[1](https://github.com/galaxyproject/galaxy/releases)] uses an old commit from the release_18.05 branch [[2](https://github.com/galaxyproject/galaxy/commit/ce362e60abbafdffa65acaf68f9492cec7196a9d)]. Using the most recent commit of the release_18.05 [[3](https://github.com/galaxyproject/galaxy/commit/03c485ee45e96784b269896a23223d233c566b89)] branch fixes the issue.

Should the v18.05 tarball be updated to the most recent commit of branch release_18.05? My intention is to use the tarball on throw away boxes where downloading the entire git repo is not desirable (e.g., [[4](https://github.com/galaxyproject/ansible-galaxy/commit/7ed9bbfd1b3351f1f300843183898db54f07038c)]).

[1] https://github.com/galaxyproject/galaxy/releases
[2] https://github.com/galaxyproject/galaxy/commit/ce362e60abbafdffa65acaf68f9492cec7196a9d
[3] https://github.com/galaxyproject/galaxy/commit/03c485ee45e96784b269896a23223d233c566b89
[4] https://github.com/galaxyproject/ansible-galaxy/commit/7ed9bbfd1b3351f1f300843183898db54f07038c

_edited to update link 3 to the correct url_

**Comment by nsoranzo** [comment]
Then the solution would probably be to download https://github.com/galaxyproject/galaxy/archive/release_18.05.zip .

**Comment by eslerm** [comment]
Hi @nsoranzo,

The issue appears when I download that zip file on CentOS. The zip and tar file are made with https://github.com/galaxyproject/galaxy/commit/ce362e60abbafdffa65acaf68f9492cec7196a9d which has a `run.sh` error in CentOS.

If the zip and tar files were updated to the commit which is HEAD of branch release_18.05, https://github.com/galaxyproject/galaxy/commit/03c485ee45e96784b269896a23223d233c566b89, `run.sh` should work properly on CentOS.

**Comment by nsoranzo** [comment]
To clarify what I said above, instead of downloading https://github.com/galaxyproject/galaxy/archive/v18.05.zip (which downloads the repo at the v18.05 tag), you need to download https://github.com/galaxyproject/galaxy/archive/release_18.05.zip (which downloads the repo at the latest commit of the release_18.05 branch).

**Comment by eslerm** [comment]
@nsoranzo, thank you for the clarification and help!

At first neither zip was working. The issue was that my CentOS VM was too small all along :|
