### ISSUE TITLE
Galaxy 18.05 [uWSGIWorker1Core0] Wrong session token found, denying request.

### ISSUE THREAD

**Issue by gad83** [galaxyproject/galaxy#6671]
Hello,

I was able to create a user when I installed my new version of galaxy.
However after setting up my config in galaxy.yml, job_conf.xml and apache proxy, I always get this error when I try to login:
galaxy.web.framework.webapp WARNING 2018-09-05 13:24:53,834 [p:10753,w:1,m:0] [uWSGIWorker1Core0] Wrong session token found, denying request.
And the webpage says: Failed to authorize action.

Here is my galaxy.yml configuration:
diff config/galaxy.yml.sample config/galaxy.yml
19a20
>   socket: 127.0.0.1:7112
24c25
<   http: 127.0.0.1:8080
- - -
>   #http: 127.0.0.1:8080
30c31
<   buffer-size: 16384
- - -
>   buffer-size: 32768
35c36
<   processes: 1
- - -
>   processes: 2
38c39
<   threads: 4
- - -
>   threads: 1
42c43
<   offload-threads: 2
- - -
>   offload-threads: 1
53c54
<   master: false
- - -
>   master: true
68c69
<   thunder-lock: false
- - -
>   thunder-lock: true
87a89,92
>   mule: lib/galaxy/main.py
>   mule: lib/galaxy/main.py
>   farm: job-handlers:1,2
>
88a94
>   server_name: main
93c99
<   #filter-with: proxy-prefix
- - -
>   filter-with: proxy-prefix
100a107
>   cookie_path: /galaxy-prod/
107a115
>   database_connection: mysql://galaxy:password@localhost/galaxy_db_prod?unix_socket=/var/lib/mysql/mysql.sock
122a131
>   database_engine_option_pool_recycle: 7200
168a178
>   file_path: /home/galaxy/galaxy-prod/database/files
171a182
>   new_file_path: /home/galaxy/galaxy-prod/database/tmp
177a189
>   tool_config_file: '/home/galaxy/galaxy-prod/config/tool_conf.xml,/home/galaxy/galaxy-prod/config/shed_tool_conf.xml'
192a205
>   migrated_tools_config: /home/galaxy/galaxy-prod/config/migrated_tools_conf.xml
199a213
>   integrated_tool_panel_config: /home/galaxy/galaxy-prod/config/integrated_tool_panel.xml
214a229
>   tool_dependency_dir: /home/galaxy/galaxy-prod/database/dependencies
281a297
>   tool_sheds_config_file: /home/galaxy/galaxy-prod/config/tool_sheds_conf.xml
342a359
>   tool_data_table_config_path: /home/galaxy/galaxy-prod/config/tool_data_table_conf.xml
351a369
>   shed_tool_data_table_config: /home/galaxy/galaxy-prod/config/shed_tool_data_table_conf.xml
441a460
>   job_working_directory: /home/galaxy/galaxy-prod/database/jobs_directory
445a465
>   cluster_files_directory: /home/galaxy/galaxy-prod/database/pbs
508a529
>   smtp_server: smtp.smtp.ca:25
522a544
>   smtp_ssl: false
535a558
>   error_email_to: rootbac@domain.com
542a566
>   email_from: Galaxy ESI Project <esi-galaxy-no-reply@domain.com>
564a589
>   user_activation_on: true
775a801
>   apache_xsendfile: true
786a813
>   upstream_gzip: false
976a1004
>   debug: false
989a1018
>   use_interactive: false
1204a1234
>   id_secret: abcdefghijk
1256a1287
>   admin_users: rootbac@domain.com
1259a1291
>   require_login: true
1263a1296
>   show_welcome_with_login: true
1267c1300,1301
<   #allow_user_creation: true
- - -
>   allow_user_creation: true
>   #allow_user_creation: false
1270a1305
>   allow_user_deletion: true
1273a1309
>   allow_user_impersonation: true
1282a1319
>   allow_user_dataset_purge: true
1288a1326
>   new_user_dataset_access_role_default_private: true
1493a1532
>   enable_quotas: true
1499a1539
>   expose_dataset_path: true
1532a1573
>   job_config_file: /home/galaxy/galaxy-prod/config/job_conf.xml
1622a1664
>   cleanup_job: onsuccess

Here is my job_conf.xml configuration
`<job_conf>
  <plugins>
    <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner"/>
    <plugin id="drmaa" type="runner" load="galaxy.jobs.runners.drmaa:DRMAAJobRunner"/>
  </plugins>
  <handlers default="main.job-handlers.1">
    <handler id="main.job-handlers.1" tags="handlers"><plugin id="local"/></handler>
    <handler id="main.job-handlers.2" tags="handlers"><plugin id="drmaa"/></handler>
  </handlers>
  <destinations default="local">
    <destination id="local" runner="local"></destination>
    <destination id="torque" runner="drmaa"><param id="native_specification">-l nodes=1:ppn=8</param></destination>
  </destinations>
  <tools>
    <tool id="upload1" handler="main.job-handlers.1" destination="local"/>
  </tools>
</job_conf>
`

Finally, here is my apache configuration:
User galaxy
Group users

Listen 8081

NameVirtualHost *:8081

<VirtualHost *:8081>
  # don't decode encoded slashes in path info
  AllowEncodedSlashes NoDecode

  # enable compression on all relevant types
  #AddOutputFilterByType DEFLATE text/html text/plain text/xml
  #AddOutputFilterByType DEFLATE text/css
  #AddOutputFilterByType DEFLATE application/x-javascript application/javascript application/ecmascript
  #AddOutputFilterByType DEFLATE application/rss+xml
  #AddOutputFilterByType DEFLATE application/xml
  #AddOutputFilterByType DEFLATE application/json

  # allow access to static content
  <Directory "/home/galaxy/galaxy-prod/static">
    AllowOverride None
    Require all granted
  </Directory>

  # allow up to 3 minutes for Galaxy to respond to slow requests before timing out
  ProxyTimeout 180

  # uWSGI on a TCP socket
  ProxyPass /galaxy-prod/ uwsgi://127.0.0.1:7112/

  # serve framework static content
  RewriteEngine On
  RewriteRule ^/galaxy-prod$ /galaxy-prod/ [R]
  RewriteRule ^/galaxy-prod/static/style/(.*) /home/galaxy/galaxy-prod/static/style/blue/$1 [L]
  RewriteRule ^/galaxy-prod/static/(.*) /home/galaxy/galaxy-prod/static/$1 [L]
  RewriteRule ^/galaxy-prod/favicon.ico /home/galaxy/galaxy-prod/static/favicon.ico [L]
  RewriteRule ^/galaxy-prod/robots.txt /home/galaxy/galaxy-prod/static/robots.txt [L]
  #RewriteRule ^/galaxy-prod(.*) http://127.0.0.1:7112$1 [P]

  # enable caching on static content
  <Location "/static">
    ExpiresActive On
    ExpiresDefault "access plus 24 hours"
  </Location>

  # serve visualization and interactive environment plugin static content
  <Directory "/home/galaxy/galaxy-prod/config/plugins/(.+)/(.+)/static">
    AllowOverride None
    Require all granted
  </Directory>
  RewriteRule ^/galaxy-prod/plugins/(.+)/(.+)/static/(.*)$ /home/galaxy/galaxy-prod/config/plugins/$1/$2/static/$3 [L]

  <Location "/">
    XSendFile on
    XSendFilePath /
  </Location>

  # Log levels
  LogLevel debug
  ErrorLog /var/log/httpd/galaxy-prod-error_log
  CustomLog /var/log/httpd/galaxy-prod-access_log common
</VirtualHost>

Please help...!

**Comment by mvdbeek** [comment]
Maybe try clearing your cookies, this is related to CSRF protection. This might be your previous instances' token.

**Comment by mvdbeek** [comment]
Feel free to re-open if that doesn't solve your problem.

**Comment by gad83** [comment]
Hey @mvdbeek ,

I tried it many times on chrome: I could not login or create another user.
However, I tried it on Edge, I could NOT login but I was able to create a user.
But when I got the email I could NOT open the verification link...
Any ideas?

side not, I'm using httpd 2.2.15 so I believe that's why I'm getting urls that looks like this:
http://server1.domain.com:8081/galaxy-prod///root/

**Comment by gad83** [comment]
ok it might have been the cookies!
Thank you @mvdbeek
