### ISSUE TITLE
conda prefix variable for tool wrapper parsing

### ISSUE THREAD

**Issue by eslerm** [galaxyproject/galaxy#6673]
Could the variable `$__conda_prefix__` be added to the Galaxy tool wrapper parser?

A tool I'm working on has a database in the `share` directory of the conda wrapper. Because of this, the tool must be passed the conda prefix path in the wrapper.

A work around is to call the environmental variable with `\$CONDA_PREFIX`. This kludge may not be robust enough for a distributed computing where the environment changes. Is there a better solution already implemented?

**Comment by mvdbeek** [comment]
I think that would be a little problematic as we start binding tools to the way the dependencies will be satisfied. I think the `\$CONDA_PREFIX` is not so bad, as that is actually set by sourcing the environment.

**Comment by eslerm** [comment]
Thanks for the explanation @mvdbeek :)

I'm going to close this issue. It may be worth re-opening to make a `$__tool_directory__` equivalent for conda wrapped tools.
