### ISSUE TITLE
'Import from path'  in data libraries skip filenames with '+' character

### ISSUE THREAD

**Issue by ashvark** [galaxyproject/galaxy#6674]
For some reasion, "import files from path" in data libraries does not accept filenames having '+' character in it.
Actually, I am not getting any error message. Galaxy is simply ignoring/skipping the files. Even, I could not see any errors in the galaxy logs.

**Comment by ashvark** [comment]
#7211 has some fix to this issue

**Comment by mvdbeek** [comment]
Fixed by https://github.com/galaxyproject/galaxy/pull/7432.
