### ISSUE TITLE
Cannot submit bug report as anonymous user (18.05)

### ISSUE THREAD

**Issue by loraine-gueguen** [galaxyproject/galaxy#6675]
Having the same issue as https://github.com/galaxyproject/galaxy/issues/5195 in 17.09 (white page displaying instead of "report error" form and 403 error in logs), I have updated to 18.01, but I had the same issue. I have then updated to 18.05: the "report error" form is now displayed, but there is another 403 error in logs when clicking on the report button after filling the form in (see below), and an error message appears on the top of the Galaxy window "Error occured while saving. Please fill all the required fields and try again."

"POST /api/jobs/30858b0ba227edd6/error HTTP/1.1" 403 - "http://webtools.sb-roscoff.fr/datasets/error?dataset_id=xxxxx&__identifer=yyyy" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"

**Comment by mvdbeek** [comment]
Thanks for the report, that is indeed unfortunate. We fixed this with https://github.com/galaxyproject/galaxy/pull/6742, which includes a test that will hopefully prevent us form breaking this again in the future.

**Comment by loraine-gueguen** [comment]
Thanks for the fix!
