### ISSUE TITLE
Galaxy uses conda packages despite of SafetyError

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6686]
```
2018-09-10 16:39:20,635 DEBUG [galaxy.tools.deps.conda_util] Executing command: /home/berntm/miniconda3/bin/conda create -y --override-channels --channel iuc --channel bioconda --channel conda-forge --channel defaults --name mulled-v1-1668c1578e9b8a19043edc472da65a1bb6b1f892609a865b6ea1d79664b68939 searchgui=3.3.3 zip=3.0
sqlite-3.24.0        | 1.5 MB    | ########## | 100% 
libffi-3.2.1         | 51 KB     | ########## | 100% 
ca-certificates-2018 | 136 KB    | ########## | 100% 
setuptools-40.2.0    | 554 KB    | ########## | 100% 
certifi-2018.8.24    | 139 KB    | ########## | 100% 
openssl-1.0.2p       | 3.5 MB    | ########## | 100% 
mono-5.14.0.177      | 130.1 MB  | ########## | 100% 
gettext-0.19.8.1     | 3.5 MB    | ########## | 100% 

SafetyError: The package for searchgui located at /home/berntm/miniconda3/pkgs/searchgui-3.3.3-1
appears to be corrupted. The path 'share/searchgui-3.3.3-1/searchgui'
has a sha256 mismatch.
  reported sha256: 86217dd9e4f9f0472fce972481954358a258aa2e07a34d50c5b94f1b582390eb
  actual sha256: 12a001d57b172db56a939de906afd5ef7a99ca8367b9cb2cac29833b319e130a
```

**Comment by mvdbeek** [comment]
Does this actually finish setting up the environment ?
Conda is supposed to set a non-zero exit code in this case, which will trigger Galaxy to remove this environment.

**Comment by bernt-matthias** [comment]
seems so. this happened in a planemo test and the test was successful. 

not sure if reproducible, I have never seen this before.

**Comment by mvdbeek** [comment]
I really doubt it, and if it continued I'd think this is a conda bug.

**Comment by mvdbeek** [comment]
To clarify, if there's no:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate __intervene@0.6.4
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

then it didn't finish installing

**Comment by bernt-matthias** [comment]
Hmm. Odd. First, planemo never shows me these messages. When executing the command outside of Galaxy/planemo I get them. 

The point was that I tried to update the environment by deleting it and reinstalling -- which led to the error. But when deleting the pkg files in addition it worked. 

Not sure if Galaxy should/can handle such an error. Anyway the "installed"  environment was usable.

**Comment by mvdbeek** [comment]
Yeah, saw this now too:
```
Downloading and Extracting Packages
mkl-2019.0           | 154.4 MB  | ############################################# | 100%
intel-openmp-2019.0  | 1.0 MB    | ############################################# | 100%
Preparing transaction: done
Verifying transaction: |
SafetyError: The package for r-base located at /Users/mvandenb/miniconda3/pkgs/r-base-3.4.1-4
appears to be corrupted. The path 'lib/R/doc/html/packages.html'
has a sha256 mismatch.
  reported sha256: 7d66db1bf6965741f31d52ee0085f61fac29983b5ba6d5372785531af39c0299
  actual sha256: 4532968581a69be211f334da91a005525fb2361d84c15de726809fd55ecdb85a

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge::gsl-2.1-2, conda-forge::readline-7.0-0
  path: 'share/info/dir'




done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate mulled-v1-01ebc4307d50c7c4995bfb94516c76fdbeecd9fc4cfed777fe4fe7e44deceb59
#
# To deactivate an active environment, use
#
#     $ conda deactivate
 ~/src/tools-iuc/tools/zerone_damid   upset_plot_tool ? ⍟9  echo $?
0
```

So yeah -- if this really is an error Conda should return a non-zero exit code. I don't think we want to get into the business of correcting Conda bugs

**Comment by nsoranzo** [comment]
Is that reproducible for a given set of packages? I tried with Matthias' command and it worked fine for me.

**Comment by mvdbeek** [comment]
I think it probably depends on the packages already in a `conda_prefix/pkgs` ?
I can't reproduce it for the searchgui case either

**Comment by nsoranzo** [comment]
By looking a bit at the conda code, these seem to be warnings by default, they're considered as error only if `safety_checks` is `enabled`, e.g.: `conda config --set safety_checks enabled`.

xref. https://github.com/conda/conda/issues/6689

**Comment by bernt-matthias** [comment]
In my case it the cause could then be that I ununstalled environments by deleting the folder, but not the packages. If there is then an update to a package and it is not downloaded again it might give this chacksum mismatch .. just a guess.

Is there a clean way to uninstall environments?

Then it might be a good idea to enable this flag?

**Comment by nsoranzo** [comment]
> Is there a clean way to uninstall environments?

```
$ conda env remove -n /PATH/TO/ENV
```

By looking at the above-mentioned conda issue, this seems more related to "manually" modifying files in one of the older envs that hardlink the affected package, which results in the warning when the package is re-used in the new env.

**Comment by bernt-matthias** [comment]
@mvdbeek can you verify this as cause?

Then the solution is to start using conda as intended.. still a safety check could not be bad for users like me :)

**Comment by mvdbeek** [comment]
No, definitely not the cause. I never touch those environemnts outside of conda. I suspect though that the channel order switch might be involved here.

**Comment by mvdbeek** [comment]
(which also fits the issue description, but is something we'll see a lot after swapping bioconda and conda-forge)

**Comment by bernt-matthias** [comment]
OK sounds like we don't need to care about it. And I will try to learn more conda :) 

Thanks a lot
