### ISSUE TITLE
problems with installing tool updates

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6698]
With ephemeris (and ansible-galaxy-tools which is using ephemeris) we have noticed problems when updating tools: https://github.com/galaxyproject/ephemeris/issues/111

examples are tools with
- new revision but same tool version number
- tool suites (e.g. openms_suite)

I checked the later via the Galaxy UI  on a "recent" dev instance and got `Repository has already been installed` for installing the openms_suite when outdated versions of the suite are installed already.

**Comment by natefoo** [comment]
Fixed in #8815
