### ISSUE TITLE
drmaa runner can not kill jobs

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6704]
In https://github.com/galaxyproject/galaxy/commit/a1c58a708829d79859426ecb7c39b5c5f69ad735#diff-5805bf58afdc31ee4a9c4e788301b11d (@natefoo ) an additional parameter dest_params was added to the get_destination_configuration function in lib/galaxy/model/__init__.py. 

The parameter was not added to the call in the stop_job function which renders it currently dysfunctional: 
https://github.com/galaxyproject/galaxy/blob/ed6f5d45a9ecbf0cf8a85341e0213b82a9132a46/lib/galaxy/jobs/runners/drmaa.py#L316

The log just shows 

```
User killed running job, but error encountered removing from DRM queue: getattr(): attribute name must be string
```
The actual traceback is:

```
Traceback (most recent call last):
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/jobs/runners/drmaa.py", line 347, in stop_job
    kill_script = job.get_destination_configuration(self.app.config, "drmaa_external_killjob_script", None)
  File "/gpfs1/data/galaxy_server/galaxy-dev/lib/galaxy/model/__init__.py", line 886, in get_destination_configuration
    config_value = getattr(config, key, param_unspecified)
TypeError: getattr(): attribute name must be string
```

I would change it my own, but I still don't understand to little ....

**Comment by natefoo** [comment]
This is fixed in #6912. Thanks for reporting and sorry I missed it!
