### ISSUE TITLE
Galaxy 18.05 mysql Too many connections

### ISSUE THREAD

**Issue by gad83** [galaxyproject/galaxy#6716]
Hello gents,

I just finished installing a new GALAXY 18.05 installation.
After half an hour running, mysql (version 5.1.73-8.0.1) is getting over 512 connections and hitting that limit. Nobody is connected except me.
So I increased it to 1024 and I tried database_engine_option_pool_recycle = 7200 and 300 and it still hits the max connection (=1024).
Any ideas?

Thanks,
Edgar

**Comment by gad83** [comment]
This was my mistake: an old table was still present in the innodb file and wasn't in the database.
When galaxy was trying to create it, it failed and left an open communication.
I had to delete and recreate the database which was thankfully brand new...

**Comment by dannon** [comment]
@gad83 Glad you figured it out, thanks for the update!
