### ISSUE TITLE
X-sendfile alternative? (or BAM/BigWig support in JBrowse)

### ISSUE THREAD

**Issue by sveinugu** [galaxyproject/galaxy#6718]
With Apache version 2.4, mod_xsendfile has been deprecated due (as far as I can see) to the fact that the code of the module is not maintained for years and might pose a security risk. See:

https://serverfault.com/questions/879130/is-mod-xsendfile-deprecated

Which means that we cannot use it on our production Galaxies (I will not even try asking the tech department about installing mod_xsendfile, as they will definitely not allow it).

So could you look into alternatives for mod_xsendfile for sending files through an Apache proxy.

@erasche As far as I can see, this feature is required to make JBrowse work with BigWig/BAM files, if you have set up your server with Apache proxying: 

https://depot.galaxyproject.org/hub/attachments/events/gcc2015/S4_L3_jbrowse-tool.pdf

I am currently on 17.09 so it might be that uWSGI changes things..

**Comment by hexylena** [comment]
uWSGI should be doing proper byte range requests, so first I would say try upgrading to that. If your admins aren't happy with XSendFile, then you can switch to NGINX. So, closing this since it should be working in a newer version.
