### ISSUE TITLE
Hover background color change for tool box is not functional

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#6721]
Sometime after https://github.com/galaxyproject/galaxy/pull/4470 the CSS for hovering over a tool (first image) broke.

cc @bgruening who complained it was not working during a training we're giving now

**Comment by martenson** [comment]
I swear I never saw it in action :D

**Comment by hexylena** [comment]
It worked when I took the screenshot! :P

**Comment by mvdbeek** [comment]
Fixed by #7437, thanks @erasche!
