### ISSUE TITLE
Tool panel does not show searched tools under certain unknown conditions

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#6724]
EU and @nsoranzo experience this but main does not.

**Steps to reproduce**
1. Search for `HISAT2` on usegalaxy.eu
2. Only stringtie shows up.

It is noticed that [the API](https://usegalaxy.eu/api/tools?q=hisat2) shows the tool as expected, but for some unknown reason this is not showing up in the tool panel.

**Comment by martenson** [comment]
So I think this is actually related to the problems in https://github.com/galaxyproject/galaxy/pull/6707 and similar. In short our inclusion of `+` in the version ID looks like the culprit. Looking further.

**Comment by nsoranzo** [comment]
@martenson Very good point, updating to the latest commit of 18.05 fixed the `hisat2` search for us!

**Comment by martenson** [comment]
I think we actually fixed this with the linked PR and related work. Please reopen if you see it again.

**Comment by hexylena** [comment]
Yes. Just finished testing. Thank you for fixing the underlying bug and finding the fix again to let us know we just needed to update. Best possible outcome, we were just a couple commits behind. Thank you.

**Comment by hexylena** [comment]
Now we're having trouble accessing tools with a `+` in the ID:

https://usegalaxy.eu/?tool_id=Remove+beginning1

Shows up in the tool panel but will not load

**Comment by nsoranzo** [comment]
Actually it's a tool with a space in the id, encoded as `+`: https://github.com/galaxyproject/galaxy/blob/dev/tools/filters/remove_beginning.xml

**Comment by martenson** [comment]
Thanks for reopening, will have a look.

**Comment by martenson** [comment]
At the moment I think we should change those links to have space encoded as `%20`. That said I am no expert in uri construction and this seems a bit like a grey area.

>A space may only be encoded to "+" in the "application/x-www-form-urlencoded" content-type key-value pairs query part of an URL

further reading:
* https://bugs.python.org/issue13866
* https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20#1634293

**Comment by nsoranzo** [comment]
@martenson The consensus in the Stackoverflow page you linked above is that: `You should have %20 before the ? and + after.`
So https://usegalaxy.eu/?tool_id=Remove+beginning1 seems correct.

**Comment by martenson** [comment]
I do not think that is the consensus from that SO thread. It *may* be encoded as `+`, but only in `application/x-www-form-urlencoded`. It can always be encoded as `%20`. 

We have more difficult situation since literal `+` can be part of the value of the very same parameter. I think %-encoding everything makes the most sense (but it would break old urls with tool ids containing space). Alternatively we could do some sort of magic treating the version portion of the id parameter differently but that feels very error prone and inconsistent.

**Comment by nsoranzo** [comment]
Works for us on 18.05 with the inclusion of https://github.com/galaxyproject/galaxy/pull/6737 .

**Comment by martenson** [comment]
Marvelous!
