### ISSUE TITLE
Not possible to add a dataset to a library from an import dir if there is a file with an UTF-8 name.

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#673]
To reproduce:
- configure `library_import_dir` or `user_library_import_dir` in config/galaxy.ini and restart Galaxy
- in the configured directory, create a with an UTF-8 name, e.g. `”test”` 
- from the "Share Data" menu select "Data Libraries Beta"
- click on a library to which you can add datasets
- click on the icon "Add Datasets to Current Folder" and select "from User Directory"
- a red pop-up error appear saying: "Could not create tree representation of the given folder: /path/of/the/library/import/dir". No files or folders are showed on the "Please select folders or files" pop-up.

No errors if the UTF-8 file is removed or renamed.

**Comment by nsoranzo** [comment]
The error comes from `lib/galaxy/webapps/galaxy/api/remote_files.py` .

**Comment by nsoranzo** [comment]
The API call which generates the error is `/api/remote_files?target=userdir&format=jstree`

**Comment by martenson** [comment]
this needs to be propagated to 15.10 and dev, then this issue can be closed

**Comment by martenson** [comment]
This proved that issues are closed via @mention only when the PR is targeting `dev`
