### ISSUE TITLE
Camera having two take picture buttons

### ISSUE THREAD

**Issue by Rainmaker61** [galaxyproject/galaxy#6735]
The camera when opened has two camera buttons to take a picture. One where it normally always is and the other floats near the first is if the phone is vertical, then if you turn the phone sideways the button is in the middle of the screen.

**Comment by Rainmaker61** [comment]
This is on a galaxy s7

**Comment by dannon** [comment]
@Rainmaker61 Sorry, but I think you have the wrong repo!  Do you maybe want https://github.com/TheGalaxyProject?

**Comment by Rainmaker61** [comment]
Thank you I google the issue and where to submit and that's where it
directed me. Appreciate the help.
