### ISSUE TITLE
Edit Step Action: rename dataset is missing input hints

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#674]
With the new workflow tool form it is not possible to know the names of _available inputs_. The old form had a list of all available names in the box. I attached two pictures to illustrate this problem. This seems to be an regression to previous releases so I added the label `bug`.
Anyone know to what the term `(newname)` is referring?

![old](https://cloud.githubusercontent.com/assets/469983/9566451/28943a9a-4f06-11e5-8221-6d60af78fd33.png)
![new](https://cloud.githubusercontent.com/assets/469983/9566452/289517c6-4f06-11e5-9817-f3ccaa3e08f5.png)

**Comment by dannon** [comment]
I poked at this a bit last week, Guy noticed this as well and submitted the same issue on biostar.  It's definitely a regression.  'newtype' actually refers to the field's name, and is something I was removing -- it might make sense for some fields but not for something where there's no point in exposing it to the user.

**Comment by bgruening** [comment]
@dannon thanks for fixing!
