### ISSUE TITLE
Documentation doesn't say that you need pip to install Galaxy

### ISSUE THREAD

**Issue by lauhuema** [galaxyproject/galaxy#6752]
Hi! I tried installing after only checking the python dependency on MacOS and I got:

```
New python executable in .venv/bin/python
Installing setuptools, pip, wheel...done.
Activating virtualenv at .venv
Collecting pip>=8.1
  Could not find a version that satisfies the requirement pip>=8.1 (from versions: )
No matching distribution found for pip>=8.1
```

I thought I mentioned this for your documentation on the landing page of the repo.

**Comment by nsoranzo** [comment]
That's quite weird, can you provide the output for the following commands:
```shell
$ cd YOUR_GALAXY_DIR
$ . .venv/bin/activate
(.venv) $ pip --version
```

**Comment by nsoranzo** [comment]
May be related to https://github.com/galaxyproject/galaxy/issues/7375 .

**Comment by martenson** [comment]
Closing pending response from creator.
