### ISSUE TITLE
Edit attributes is a blank page

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/galaxy#6756]
When we click on the Edit Attributes pencil button, we just get a blank page 
and this message in the uWSGI log.

```
galaxy.web.framework.decorators ERROR 2018-09-21 22:02:02,371 [p:10163,w:3,m:0] [uWSGIWorker3Core1] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "/work/project/w4m/galaxy4metabolomics/galaxy/lib/galaxy/web/framework/decorators.py", line 154, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "/work/project/w4m/galaxy4metabolomics/galaxy/lib/galaxy/webapps/galaxy/controllers/dataset.py", line 282, in get_edit
    all_roles = [(r.name, trans.security.encode_id(r.id)) for r in trans.app.security_agent.get_legitimate_roles(trans, data.dataset, 'root')]
  File "/work/project/w4m/galaxy4metabolomics/galaxy/lib/galaxy/security/__init__.py", line 345, in get_legitimate_roles
    return self.get_all_roles(trans, cntrller)
  File "/work/project/w4m/galaxy4metabolomics/galaxy/lib/galaxy/security/__init__.py", line 211, in get_all_roles
    return self.sort_by_attr([role for role in roles], 'name')
  File "/work/project/w4m/galaxy4metabolomics/galaxy/lib/galaxy/security/__init__.py", line 177, in sort_by_attr
    intermed = [(getattr(v, attr), i, v) for i, v in enumerate(seq)]
AttributeError: 'NoneType' object has no attribute 'name'
```

We (@fgiacomoni, @cduperier and me) have just updated our instance to the 18.05. But we also change a lot of thing as using NGINX (instead of Apache), uWSGI (instead of Paste). So which one of those changes is the guilty?
That is the question!

**Comment by mvdbeek** [comment]
@lecorguille is this a library dataset or a normal history dataset ?

**Comment by lecorguille** [comment]
@mvdbeek Normal datasets

**Comment by mvdbeek** [comment]
Thanks, I think I see what the problem is

**Comment by mvdbeek** [comment]
Are you using remote user auth ? Does this also happen if the users logs out and back in again ?

**Comment by lecorguille** [comment]
We use the native [LDAP authentification](https://github.com/galaxyproject/galaxy/blob/dev/config/auth_conf.xml.sample#L4)

**Comment by mvdbeek** [comment]
Hmm, does this happen for all users ? Do you know if this user had its email changed at any point ?

**Comment by lecorguille** [comment]
Wow, impressive!

Yes, we changed our user email address within the database. They had some
email with the same domain @workflow4metabolomics.org (we had some alias to
map their real address) at that time we indeed have an remote
authentification.
We change that for their real email address this summer.

**Comment by lecorguille** [comment]
👍
It did the job!
@mvdbeek Thanks a lot for your time and this fix!

**Comment by fgiacomoni** [comment]
...and he did the job !!! Thank you @mvdbeek
