### ISSUE TITLE
Display output labels in workflow editor

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#6764]
from @mblue9 in https://github.com/galaxyproject/tools-iuc/pull/2103#issuecomment-424235825
![screen shot 2018-09-25 at 3 10 24 pm](https://user-images.githubusercontent.com/5591821/45998934-aa2f3900-c0e7-11e8-9817-f3004bdfa7a5.png)

> I received some user feedback that in the editor view the featurecounts outputs are a bit confusing, see below (e.g. it's not very obvious to users what `output_short`, `output_medium` and `output_full` are).

This should be straightforward, we can display the label (maybe on hover, to not cram too much text in there ?)

**Comment by mblue9** [comment]
Displaying the labels would be really great (if that's possible)!

**Comment by mvdbeek** [comment]
As usual I haven't thought about this enough. Many tools use cheetah to fill in a couple of things, this is most of the time `{on_string}` and/or `{tool.name}`. We could try to fill those in using cheetah, but we'd probably miss some of the more extravagant labels like `${input.name} (as BAM)`. A quick grep through the IUC tells me this isn't used a lot and would probably improve the situation for 95% of the tools. Or we just display the label as it is defined in the xml (`${tool.name} on ${on_string}: junction counts`) for the featureCounts example.

**Comment by mvdbeek** [comment]
I made some progress on this, I think this is actually feasible if we replace `on_string` with `input dataset(s)`:
![screen shot 2018-09-25 at 18 58 57](https://user-images.githubusercontent.com/6804901/46030036-53c8f700-c0f5-11e8-9515-ce2878d30256.png)
Concatenate datasets here doesn't have a label, but the others do.
This is from https://github.com/mvdbeek/galaxy/commit/4cdd0774c5fd5b9a1eaafe034ae1c20c077abf92 -- Just need to figure out what to do with the actual variable name. We have to display it somewhere so that the rename actions make sense.

**Comment by mvdbeek** [comment]
I think I got this right now, and in addition I'm also displaying the available inputs as a list, with the variable name in bold and the label as you see it in the editor next to it -- that should hopefully make things easier:
![screen shot 2018-09-26 at 10 39 35](https://user-images.githubusercontent.com/6804901/46068134-c5965480-c178-11e8-8352-9b61159062aa.png)
