### ISSUE TITLE
18.09 pre-release on Main: Uploaded BAMs using autodetect given datatype "auto"

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6769]
test history: https://usegalaxy.org:/u/jen/h/test-history-bam-autodected-upload

data1 == this problem

data2 == copy of data1 after edit attributes > datatype > change to bam

gtf, sam, fastqsanger all autodetect correctly

ping @guerler

**Comment by mvdbeek** [comment]
I confirm, this is seriously broken, we should fix this ideally before the release.

**Comment by mvdbeek** [comment]
(can't believe we didn't catch this in any test ...)

**Comment by mvdbeek** [comment]
Turns out the dataset is actually correctly being sniffed, but then spontaneously reverts while setting metadata. Thanks for the report @jennaj

**Comment by jennaj** [comment]
There may be still some issue, possibly only with larger BAMs. Or possibly with partial BAMs obtained via URL. 

Connection somehow interrupted - resulting in green, not red dataset - and the bam datatype cannot be directly assigned. 

@martenson is running some tests. Can put results here or open new issue, whichever you all prefer. 

Thanks for quick fix @mvdbeek !

**Comment by mvdbeek** [comment]
Yes, please open a different issue

**Comment by martenson** [comment]
I think it behaves alright. I have some bams that are detected as 'data' and 'auto' and metadata is never set on them despite being green. However new uploads of these datasets work fine so I assume they are in some weird state that happened when the regression was in place.

The two misbehaving datasets can be seen here: https://usegalaxy.org:/u/martenson/h/unnamed-history-3  under hids 1 and 3.

**Comment by mvdbeek** [comment]
You should be able to rest metadata to fix this, does that work ?
(and yes, we can't retroactively fix this for datasets that are in this state, but resetting metadata should work)

**Comment by martenson** [comment]
@mvdbeek no, that does not work

**Comment by mvdbeek** [comment]
And if you switch to fastqsanger first?

**Comment by martenson** [comment]
@mvdbeek alright, so that magic actually works

**Comment by jennaj** [comment]
Tested in pre-release 18.09 as installed at ORG, still working correctly now. Was just a double check it this didn't regress at some point / interact with other changes.

Thanks for quick fix!

**Comment by martenson** [comment]
@jennaj thanks for the extra check, these problems revolving around datatypes and bams needed that
