### ISSUE TITLE
cannot scroll on a published history

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6777]
found on Main

when you expand multiple datasets the scrollbar is never offered

example: https://usegalaxy.org/u/zhangxi/h/circrna

**Comment by dannon** [comment]
@martenson Thanks, I'll take a look!

**Comment by dannon** [comment]
This is related to recent flexbox changes; looking at 1) how pervasive this might be, and 2) the right fix.  Will follow up.

**Comment by blankenberg** [comment]
Also workflows: https://usegalaxy.org/u/aun1/w/metagenomic-analysis-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1


(1)

**Comment by dannon** [comment]
Should be fixed in #6791
