### ISSUE TITLE
peek/metadata not being set properly for empty datasets

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6795]
seen on Main from @blankenberg 

> it looks like peek/metadata for number of sequences is being inherited from inputs, but not being set properly when datasets are empty. Causing empty datasets to list that they have regions, e.g.:

![image 1](https://user-images.githubusercontent.com/1814954/46218333-4ccb0000-c312-11e8-9db7-910892e3283e.png)

**Comment by mvdbeek** [comment]
There's a chance https://github.com/galaxyproject/galaxy/pull/6789 fixes it, I guess main's not running that yet ?

**Comment by martenson** [comment]
@mvdbeek correct, will be soon though
