### ISSUE TITLE
Bam data type stumbles over empty files

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6804]
the samtools phase tool uses an empty bam file for testing and probably samtools phase really generates an empty bam file. This triggers the following. 

```
Traceback (most recent call last):
  File "/tmp/tmpH3VbtC/galaxy-dev/lib/galaxy/jobs/runners/local.py", line 152, in queue_job
    self._finish_or_resubmit_job(job_state, stdout, stderr, exit_code)
  File "/tmp/tmpH3VbtC/galaxy-dev/lib/galaxy/jobs/runners/__init__.py", line 433, in _finish_or_resubmit_job
    job_state.job_wrapper.finish(stdout, stderr, exit_code, check_output_detected_state=check_output_detected_state)
  File "/tmp/tmpH3VbtC/galaxy-dev/lib/galaxy/jobs/__init__.py", line 1301, in finish
    dataset.datatype.set_meta(dataset, overwrite=False)
  File "/tmp/tmpH3VbtC/galaxy-dev/lib/galaxy/datatypes/binary.py", line 429, in set_meta
    pysam.index(dataset.file_name, index_file.file_name)
  File "/home/berntm/.planemo/gx_venv_None/local/lib/python2.7/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: "/tmp/tmpH3VbtC/files/000/dataset_5.dat" is in a format that cannot be usefully indexed\n'
```

Question is if this should be considered upstream / if Galaxy should handle it.

**Comment by mvdbeek** [comment]
I am a little surprised by this, I have tested empty bam uploads and they work, as long as the header is present, was that the case ?

**Comment by bernt-matthias** [comment]
It seems that the output of `samtools phase` is not the problem -- pysam.index works on them. The problem is the test-data that is currently supplied in the wrapper. There was one empty.bam which was actually an empty file. But if I replace this I still get the error. 

It seems that also the files `samtools_phase_out_1_phase0.bam` in the test-data create an error. On a first look they look fine for me. They are not empty, have a header and an alignment. Mysterious.

**Comment by mvdbeek** [comment]
> samtools_phase_out_1_phase0.bam

just uploaded that file, has been correctly sniffed as BAM and an index has been created. Is there a command that will fail ?

**Comment by bernt-matthias** [comment]
On my local computer `planemo test` fails for this tool (1st and 3rd test). 

I also checked `pysam.index(file, index)` manually for the file and it failed for me.

**Comment by bernt-matthias** [comment]
Maybe my planemo does not use the latest dev?

**Comment by mvdbeek** [comment]
Haven't changed this since 18.05 (or maybe even 18.01).

**Comment by mvdbeek** [comment]
planemo by default tests against master and sometimes gets stuck using an old master. You can `rm` ~/.planemo/gx_repo in that case. I am running the samtools phase tests, let's see what results I get.

**Comment by mvdbeek** [comment]
yeah, it fails for me too, but not on the input dataset, dataset_5.dat should be the `chimera` output. I'd argue that this should indeed fail because an empty file it is not a bam file. Not sure what to do with optional outputs at runtime ... we could create a BAM file using only the input headers if the file size is 0 ?

**Comment by mvdbeek** [comment]
I guess what would be really cool on the Galaxy side is to only fail an output dataset, not an entire Job if the metadata setting fails.

**Comment by bernt-matthias** [comment]
Got it. Actually there was a typo in the `from_work_dir` filename. This led to the empty data set dataset_5.dat which could not be indexed. 

So the question actually is if this behavior is intended?

**Comment by mvdbeek** [comment]
Yes, I think this is desired -- we wouldn't have caught the bug, right ? Outside of technicalities though I think that if an input can't be guaranteed to be valid we should error, instead of continue. Better to have no results than wrong results.

**Comment by bernt-matthias** [comment]
Agreed. Thanks a lot.
