### ISSUE TITLE
cgroups metrics plugin produces strange numbers for some metrics

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#6813]
Hi there!

When activating `<cgroups />` metrics I see the following for a job:

Field | Value
-- | --
CPU Time | 128085.4462259644266666666667 hours and 26.7735578656 minutes
Failed to allocate memory count | 0
Max memory usage (MEM) | 0 bytes
Max memory usage (MEM+SWP) | 0 bytes
Memory limit on cgroup (MEM) | 8.0 EB
Memory limit on cgroup (MEM+SWP) | 8.0 EB
Memory softlimit on cgroup | 8.0 EB
OOM Control enabled | Yes
Was OOM Killer active? | No

I checked that cgroups where active on the execution node:

```
$ cat /proc/mounts | grep cgr
tmpfs /sys/fs/cgroup tmpfs ro,nosuid,nodev,noexec,mode=755 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/usr/lib/systemd/systemd-cgroups-agent,name=systemd 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,nosuid,nodev,noexec,relatime,freezer 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,nosuid,nodev,noexec,relatime,net_prio,net_cls 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,nosuid,nodev,noexec,relatime,cpuacct,cpu 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,nosuid,nodev,noexec,relatime,memory 0 0
```

Any other checks I should be making? Should I be setting it up differently in the metrics config? The job clearly didn't take that much CPU time and surely used more than 0 in memory. Collectl is also producing weird numbers, will open a separate issue for that.

Thanks!

**Comment by mvdbeek** [comment]
@natefoo @erasche might have some experience with this.

**Comment by natefoo** [comment]
It looks like you're seeing the max values for all of these - I get them for the memory limits but this is a configuration issue with my nodes. If your jobs are all running in a single cgroup, these metrics will not be valid on a job context.

Slurm sets up per-task cgroups automatically if the right options are enabled, I am not sure about other DRMs. What DRM are you using?

**Comment by pcm32** [comment]
Thanks @natefoo, I'm using LSF through the cli-runner. I will look if I can give any options for LSF to setup cgroups per task as you suggest. Or would this be part of central DRM configuration rather than per job submission?

**Comment by pcm32** [comment]
Apparently there is some central setup needed http://www-01.ibm.com/support/docview.wss?uid=isg3T1022063

**Comment by pcm32** [comment]
Anyone knows if collectl is using cgroups underneath? as I also get weird unfeasible values with it.

**Comment by natefoo** [comment]
Collectl never worked for me, but I believe it was an issue with CentOS 6. I never tried it with CentOS 7.

**Comment by hexylena** [comment]
Looks like this needs to be configured with job runner and nothing for us to do.
