### ISSUE TITLE
problem when using the ShellJobRunner

### ISSUE THREAD

**Issue by Chabrier** [galaxyproject/galaxy#6831]
Hi,
i'm trying tho use the ShellJobRunner. The job submission does work, the cluster targetted does execute the job.
But the job always stay in the "grey" state (This job is waiting to run).
The job does not seem to be monitored.

The same job executed with the local job runner is correctly monitored.

Am i missing something?

My job_conf.xml lok like this:

```xml
<?xml version="1.0"?>
<!-- A sample job config that explicitly configures job running the way it is configured by default (if there is no explicit config). -->
<job_conf>
    <plugins>
        <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner" workers="4"/>
	<plugin id="cli" type="runner" load="galaxy.jobs.runners.cli:ShellJobRunner" workers="4"/>
    </plugins>
    <destinations default="ssh_slurm">
        <destination id="local" runner="local"/>
        <destination id="ssh_slurm" runner="cli">
            <param id="shell_plugin">SecureShell</param>
            <param id="job_plugin">Slurm</param>
            <param id="shell_username">me</param>
            <param id="shell_hostname">thecluster.fr</param>
            <param id="job_time">2:00:00</param>
            <param id="job_ncpus">4</param>
            <param id="job_partition">defq</param>
        </destination>
    </destinations>
    <tools>
	<tool id="runtask" destination="ssh_slurm" />
    </tools>
</job_conf>
```

Thanks fo the help

Cordially.

**Comment by mvdbeek** [comment]
How did you set up your job handlers ?

**Comment by Chabrier** [comment]
I did keep the default setting, by just copying workflow_schedulers_conf.xml.sample to  workflow_schedulers_conf.xml. I knew i was missing something. If you have any documentation entry point or configuration example, it would be helpfull.

**Comment by Chabrier** [comment]
I did keep the default setting, by just copying workflow_schedulers_conf.xml.sample to workflow_schedulers_conf.xml. I knew i was missing something. If you have any documentation entry point or configuration example, it would be helpfull.

**Comment by mvdbeek** [comment]
you shouldn't need to change `workflow_schedulers_conf.xml.sample`, but you should setup a `job_conf.xml` file. If you're running the current stable release (18.05) I'd suggest to start with the all-in-one job handling described here: https://docs.galaxyproject.org/en/master/admin/scaling.html#uwsgi-all-in-one-job-handling

**Comment by Chabrier** [comment]
Does this mean no handlers should be explicitly specified?
Or Should i explictly define a handler and also modify the galaxy.yml to?

**Comment by mvdbeek** [comment]
That depends on what you want to achieve. I'd start with the simplest setup and then incrementally customize until you're happy. So to check what's going on, yes, I'd not set a handler and use the default settings.

**Comment by Chabrier** [comment]
With the default settings, without handlers, exactly the job.conf in the first post, the job is not monitored.

**Comment by mvdbeek** [comment]
Please include the logs that you see, and a verbatim copy of your `job_conf.xml` file, as the one you posted is not complete.

**Comment by mvdbeek** [comment]
OK, and you didn't define any mules or farms in galaxy.yml ? What do you see in the logs when you submit a job ?

**Comment by Chabrier** [comment]
No mules of frarms defined yet.
[galaxy.log](https://github.com/galaxyproject/galaxy/files/2456298/galaxy.log)
[job_conf.txt](https://github.com/galaxyproject/galaxy/files/2456304/job_conf.txt)

**Comment by mvdbeek** [comment]
This looks OK, your job handlers are properly picking up the jobs.
Could you apply https://github.com/mvdbeek/galaxy/commit/f24678e5e2a4d7fb235be6301c3a947293989343 and see what message you see in the logs ?

**Comment by Chabrier** [comment]
Done, but i think i did try this also and my conclusion was that this part of the code is not called.
[galaxy.log](https://github.com/galaxyproject/galaxy/files/2456484/galaxy.log)

**Comment by mvdbeek** [comment]
Hmm, could you try the `ParamikoShell` plugin, I'm using this myself and that should be suprior to the SecureShell plugin. You may need to add something like `<param id="shell_private_key">/path/to/private_key</param>` if it doesn't work out of the box.

**Comment by Chabrier** [comment]
OK, Thanks

**Comment by Chabrier** [comment]
Ok, but Ko, same behaviour, even wih the ParamikoShell the status of the task does not change and finishes at "grey state" even if i can view an output.
I really miss someting.

**Comment by mvdbeek** [comment]
OK, I might have found why this isn't running the monitor, could you try 1e4d00557d ?
If that is the issue it would probably also solve a couple of other reported issues.

**Comment by Chabrier** [comment]
Hi,
What i get now.
[galaxy.log](https://github.com/galaxyproject/galaxy/files/2459404/galaxy.log)

**Comment by mvdbeek** [comment]
Awesome, that means that the job monitor started working, but that your slurm doesn't know about the %t option. Can you tell me what version of slurm you are using ?

**Comment by Chabrier** [comment]
[chabrierp@muse-login02 ~]$ sinfo --version
slurm 16.05.2

**Comment by mvdbeek** [comment]
can you try those 2 commands:
```
squeue -a -o '%A %t'
```

and
```
squeue -a -o %A %t
```

The first one should fail, the second one may work. If that's the case we just need to patch up the command.

**Comment by Chabrier** [comment]
```
[chabrierp@muse-login02 ~]$ squeue -a -o '%A %t'
JOBID ST
610177 PD
951596 PD
951648 PD
952782 PD
952789 PD
501317 R
501764 R
607464 R
610193 R
610194 R
612490 R
```
...
```
[chabrierp@muse-login02 ~]$ squeue -a -o %A %t
squeue: error: Unrecognized option: %t
Usage: squeue [-A account] [--clusters names] [-i seconds] [--job jobid]
              [-n name] [-o format] [-p partitions] [--qos qos]
              [--reservation reservation] [--sort fields] [--start]
              [--step step_id] [-t states] [-u user_name] [--usage]
              [-L licenses] [-w nodes] [-ahjlrsv]
```
...

In fact the first one did work :)

**Comment by mvdbeek** [comment]
OK, I'm writing up a test case for this, I could also reproduce this using a docker image here.

**Comment by Chabrier** [comment]
I'm not familliar with docker, so i'm not sur to get the purpose. 
Anyway, thanks for spending time on this.

**Comment by mvdbeek** [comment]
It's just a lightweight way to test logging in by ssh into a tiny slurm cluster.

**Comment by Chabrier** [comment]
Ok, i got it.

**Comment by mvdbeek** [comment]
OK, I see this only with the `SecureShell` plugin, not with `ParamikoShell`, can you confirm this ?

**Comment by Chabrier** [comment]
Not sure, what you want me to confirm?

**Comment by mvdbeek** [comment]
Using ParamikoShell and the last patch should work or at least result in a
different error.

**Comment by mvdbeek** [comment]
Meh, I see this was already paramiko in your log. That's strange, I could reproduce this only with the SecureShell plugin.

**Comment by mvdbeek** [comment]
Hmm, I'm not sure what I can do to reproduce this. Is there a specific login-shell set on the head-node for the galaxy user ? What OS and shell is galaxy running on ?

There's a chance that https://github.com/mvdbeek/galaxy/commit/57a1f19b069597bde97852b3e0d0a3e1c0068bc4 would fix the issue you're seeing at least for the `SecureShell` plugin. It is a bit unfortunate though that the paramiko-based one doesn't work for you, as it is more robust and can re-use open connections.

I could try adding another shell plugin based on https://github.com/ParallelSSH/ssh2-python, but it might ultimately have the same issue.

**Comment by Chabrier** [comment]
Hi Marius,

after applying the patch mvdbeek@57a1f19, evrything seems to work better on my side. Either the SecureShell and the ParamikoShell approach are more functionnal. The status of the job are monitored and graphically also. Thans for this. If you want me to do more, just tell.

**Comment by mvdbeek** [comment]
OK, glad this works. I think for now this is OK, but do let me know if you notice any further issues.

**Comment by mvdbeek** [comment]
Alright https://github.com/galaxyproject/galaxy/pull/6836 and https://github.com/galaxyproject/galaxy/pull/6845 are merged and should fix this. Thanks for the report and for following up @Chabrier!
