### ISSUE TITLE
Problems when I would like to upload local files

### ISSUE THREAD

**Issue by jsaintvanne** [galaxyproject/galaxy#6847]
Hello everyone,

I start to explain my case : I'm on Windows 10 and I use the "Ubuntu on Windows" to have a linux environnement on my computer. I download galaxy path and I would like t run it locally to be able to test some tools...
But I have some troubles : 
`Warning: Tool not found or not accessible.`
This is the Warning when I want to upload one file in my local Galaxy.

Secondly I configured the config/tool_conf.xml file to be able to access my tools but only some one are good.

Someone can help me please??

I think these problems are a lot due to the Ubuntu on Windows cause paths are quite stranges and difficult to obtain...

Thanks !

**Comment by martenson** [comment]
This would be hard for us to troubleshoot since we do not have the environment to reproduce (and no experience troubleshooting this environment, I do not even know if it is possible to run it like this). I also have some troubles understanding your report. How do you start Galaxy? Does it finish starting for you? Can you see the interface?

**Comment by jsaintvanne** [comment]
Sorry to be not clear...

I start Galaxy with simple command sh run.sh when I'm in the Galaxy path. I run this command on the application Ubuntu on Windows. That application open to me a command panel where I can write linux commands. 
I can run correctly my Galaxy and I can go on the interface yes ! My command line finish with the http adress. The only one ERROR I obtain in my command lines is this one : 
`galaxy.tools.toolbox.base ERROR 2018-10-11 08:50:32,109 [p:8103,w:0,m:0] [MainThread] Error reading tool configuration file from path '/mnt/c/Users/Me/Documents/my_tool.xml': [Errno 2] No such file or directory`
 Just to know that this path "/mnt/c/Users/Me" is the path where I can find my file througth Ubuntu commands....
And this morning I don't know why yet but I don't obtain the same problem....
Yesterday I would like to upload a file and when i clic on start button it passed immediatly in red and with the following message : "Warning: Tool not found or not accessible."
Today I can clic on start button but my file (1.3Mb) is always in "adding to history" with the little wheel turning just next to it.

**Comment by martenson** [comment]
@jsaintvanne thanks for the details. Do you see any errors in the console when the upload is stuck in 'adding to history'?

As a general advice, when on Windows, I would recommend to run Galaxy in a VM with ubuntu or in a container using e.g. https://docs.docker.com/docker-for-windows/install/

There is a pre-configured docker image available at https://github.com/bgruening/docker-galaxy-stable

**Comment by martenson** [comment]
Please comment if you still need help, or ask at biostar.usegalaxy.org
