### ISSUE TITLE
Masthead does not refresh after new account creation

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6853]
Even though user is logged in (and is told so). This is confusing to users.

**Comment by martenson** [comment]
it also does not refresh after a logout.

This leads to some confusing scenarios where if you click on the logout the second time you will receive 'action not authorized page' and lose the menu completely.

**Comment by jmchilton** [comment]
We still comfortable blocking the release on this?

**Comment by martenson** [comment]
I don't think this was ever blocking.

**Comment by mvdbeek** [comment]
I think both bugs have been fixed somewhere along the way ... a quick test seems to work correctly on dev. But feel free to re-open if I missed something here.
