### ISSUE TITLE
dataset states of multi-bam producing jobs does not switch to OK 

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#6856]
Despite the jobs ending fine. We have thousands of datasets on Main in this state causing confusion amongst users since the 'job never ends'.

Tracked down by @natefoo and @jmchilton. 
Possible culprit(s): https://github.com/galaxyproject/galaxy/pull/6789 and https://github.com/galaxyproject/galaxy/pull/6531
Possible solution: https://github.com/galaxyproject/galaxy/pull/6855

**Comment by martenson** [comment]
ping @mvdbeek

**Comment by mvdbeek** [comment]
well, at least the library upload issue is reproducible and happens without #6789 too.

**Comment by mvdbeek** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/6789
