### ISSUE TITLE
Retaining original sample names through multi-step, ad-hoc analyses on dataset collections

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/galaxy#686]
Hello everyone,
I wish that every analyst built their analyses into bona-fide workflows, although it's clear that not every analysis proceeds this way. This has been asked a few times with a few workarounds proposed, and even strong support for sample naming/renaming was implemented in Galaxy workflows. It would be useful for tool developers to have access to the original sample names so that our tools can produce more consistent and useful sample names. Also, it seems that Galaxy retains this information in its own way, as sequential collections retain the appropriate original sample name.

I have a tool "A" that produces a report for a fastq file which requires the name of the original sample passed in through a CLI parameter. When "A" is run over an unprocessed collection of fastq files, the [$input.name](https://github.com/peterjc/galaxy_blast/commit/31e31c4b5deadd60828ce6e6a381a5f90357393d) trick works fine. But I've found a situation where this won't work.

I have another tool "B" which subsamples single or paired-end fastq files. When I inspect the collection in my history, I can see that the sample name is retained somewhere in the galaxy application, even if the collection has been renamed. Then, when I pass $input.name to each invocation of "A" on each sample in the collection, $input.name instead produces  "Random subsample on data 1, 2, 3, and others" which is the name of the collection produced from "B" instead of the original sample name. 

I understand that datasets can be renamed and such within workflows. However, it would be useful to have access to the original sample name in the XML/cheetah tool configuration, especially for dataset collections. It is clear that the sample name exists somewhere in the application (ORM or otherwise) as new collections contain samples appropriately named.

**Comment by bgruening** [comment]
This might be related: https://trello.com/c/JnhOEqow

**Comment by jmchilton** [comment]
This is available as ``$input.element_identifier``. I'd check out this document for more information - http://planemo.readthedocs.io/en/latest/writing_advanced.html#processing-identifiers. Let me know if you want me to tackle this more on.
