### ISSUE TITLE
Handle (or inform) out of memory job failure in the cli-plugin job runners

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#6864]
Hi there,

I would like the cli-runner to be able to handle gracefully (or at least inform the user) that a job failed due to being out of memory (or some other resource constraint). What would be the place to add a call to the plugin to inform this for the job? Here maybe:

https://github.com/galaxyproject/galaxy/blob/5e71401a7eb502479c7a9b69e60a2351a82258d7/lib/galaxy/jobs/runners/cli.py#L177

That would be roughly where the k8s runner for instance is making calls to a _handle_failure or alike method, which in this case should be called from the cli job plugin I presume (handling if this is not yet implemented in the plugin of course). @jmchilton what would be your advice on this? Or I'm I missing something that is already in place? I got here because I noticed some jobs on my LSF (running through the cli) failed due to our of memory, but Galaxy just reports as a failure.

Thanks!

**Comment by mvdbeek** [comment]
Yes, I think if you set the state to `memory_limit_reached` we should be able to use the existing resubmission code.

**Comment by mvdbeek** [comment]
We have some integration test cases for this in https://github.com/galaxyproject/galaxy/blob/dev/test/integration/test_job_resubmission.py#L59 and for the cli runner https://github.com/galaxyproject/galaxy/blob/dev/test/integration/test_cli_runners.py#L115, it should be possible to setup a test case for this combining the two.

**Comment by hexylena** [comment]
Fixed in #6866
