### ISSUE TITLE
Renaming histories that contain ' quotes are problematic

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#6873]
Moved (are not server-specific) Details: https://github.com/galaxyproject/usegalaxy-playbook/issues/169

**Comment by jennaj** [comment]
The problem is still present at ORG running pre-release 18.09.

Are we sure this is actually fixed and made it into the release? Or is this a Bugfix for after release? @almahmoud @dannon

**Comment by martenson** [comment]
@jennaj Main was not updated yet.

**Comment by jennaj** [comment]
Still an issue. Main has been restarted (I see newly pushed cvmfs indexes). 

There are a few more bugfixes, one as recent as today, that would be nice to get on the public server. Maybe wait for this to be backported to 18.09 first? https://github.com/galaxyproject/galaxy/pull/6998 If yes, could test/close out the post-release fixes together.

adding in @natefoo

**Comment by jennaj** [comment]
Test when 19.01 goes live on Main then close out when it passes

**Comment by jennaj** [comment]
Going to close this out now but will still integration retest in `19.01` at Main/ORG once released (tracked at the linked project) -- we can reopen if something is problematic about it.

**Comment by jennaj** [comment]
Passes in 19.01 :)
