### ISSUE TITLE
running short job with galaxy.jobs.runners.cli:ShellJobRunner ends in the fail state

### ISSUE THREAD

**Issue by Chabrier** [galaxyproject/galaxy#6880]
Hi,

This happens for me when using the galaxy.jobs.runners.cli:ShellJobRunner, just to mention, even if this not very accurate. When a job is very short, it does not seem to be correctly monitored or handled. Even if everything seems to work fine, the last status of the job goes to fail(red).

If the job is arbitrary slowed, everything works fine.

**Comment by mvdbeek** [comment]
Can you post the logs when you run such a short job please ?

**Comment by Chabrier** [comment]
Sorry about the time lag.

[galaxy.log](https://github.com/galaxyproject/galaxy/files/2490533/galaxy.log)

In order to test I did simply use the "cat tool" to concat 2 single line files.

**Comment by mvdbeek** [comment]
Hmm, so the integration test also just runs some very quick test. Is the file on a network file system ? Maybe you could add the `-noac` mount option if this is NFS ? We have another setting that deals with remote file systems, https://github.com/galaxyproject/galaxy/blob/dev/config/galaxy.yml.sample#L1607, but at the path in the code where this fails for you we don't try again to access the file. But maybe we should ...

**Comment by Chabrier** [comment]
Yes the file is on a network system. We are using sshfs and the no cache option was the solution (sshfs -o cache=no ...). Now, everything seems  to work fine.

**Comment by mvdbeek** [comment]
Thanks for the feedback. We might still want to retry the file collection at this point, but it's good to know this worked for you.
