### ISSUE TITLE
Workflows in tool menu are duplicated for every workflow version update

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#6889]
From #6410:

When adding workflow to the tool menu "Show in tools panel" every version but with the same name will show up, not just the latest. This is very confusing and difficult to cleanup - one has to remove the checkmark multiple times, a click and page reload for every workflow version.

**Comment by mvdbeek** [comment]
Can you attach a screenshot ? I either am looking for the wrong thing or I can't reproduce this.

**Comment by scholtalbers** [comment]
Ok, so now I'm *not able to reproduce* getting them in as duplicates anymore, but here is a screenshot of where it is duplicated, and I had to uncheck the "Show in tools panel" at least two times to get rid of it. 

<img width="908" alt="screen shot 2018-10-17 at 15 23 27" src="https://user-images.githubusercontent.com/102411/47089806-dc811180-d221-11e8-9031-a6b23b15c1fa.png">

After "unchecking" both workflows once:

<img width="919" alt="screen shot 2018-10-17 at 15 29 34" src="https://user-images.githubusercontent.com/102411/47089805-dc811180-d221-11e8-8660-aaa6e43d75b6.png">

**Comment by mvdbeek** [comment]
This whole workflow in tool menu thing is a bit wonky, I'll have a look if we can improve this.

**Comment by selten** [comment]
![workflow panel](https://user-images.githubusercontent.com/961090/48544278-87d5c280-e8c3-11e8-8b1f-54ab77f5fe55.png)
![tool panel](https://user-images.githubusercontent.com/961090/48544279-87d5c280-e8c3-11e8-8a33-0b88925bb006.png)
These images illustrate the same bug, however also when the "show in tool panel" is unchecked, they don't disappear. These screenshots were taken on Galaxy 18.01.

**Comment by selten** [comment]
Steps to reproduce:

1. Share a workflow with another user personally (so they don't import it).
2. Check the `Show in tools panel` box and it will show up in your tools and subsequently can't be removed anymore unless the database is altered.

Query to clean this for the user: `DELETE FROM stored_workflow_menu_entry WHERE user_id=X;` (for reference if other people want to clean up after this bug).
