### ISSUE TITLE
Using objectstore and S3 to upload remote datasets to galaxy

### ISSUE THREAD

**Issue by najitaleb** [galaxyproject/galaxy#6894]
Hello. I was taking a look at the issue mentioned here ( https://github.com/galaxyproject/galaxy/issues/1568 )regarding being able to symlink to remote files to upload to galaxy, rather than just symlinking from the local path (link_data_only). This issue seems to allude to the fact that this can be done to datasets and that the poster would like it implemented for libraries. My question is how would you use S3 to do this for datasets, and whether or not that's also a WIP like S3 for data libraries. Also, can it be done through bioblend/ API calls? Thank you.

**Comment by hexylena** [comment]
Hi, sorry for the lack of response. It is not currently possible to do this at all. If you really need this, you could mount s3fs on the Galaxy head node or something like this.
