### ISSUE TITLE
"python setup.py egg_info" Error

### ISSUE THREAD

**Issue by JJCSPR** [galaxyproject/galaxy#6895]
Greetings, 

I have been trying to install Galaxy on my Mac, but have been unable to install it. Whenever I run "sh run.sh", I get the error seen in the screenshot below. I have tried several fixes available online, and have not had success. I have confirmed that python --version returns that I am using 2.7.14. I am using macOS High Sierra (version 10.13.6), in case anyone was wondering.

Does anyone have a solution or could point me to where I could obtain a solution? If not, I am going to go ahead and install a Linux distribution and work with that instead.

Best,

Jorge

![44349776_473778189783553_1691184230823886848_n](https://user-images.githubusercontent.com/23179127/47120528-568bb780-d26f-11e8-9ee8-b8606313a50e.png)

**Comment by mvdbeek** [comment]
For some reason the python interpreter couldn't guess your locale and falls back to ASCII, which is too restrictive. You may want to have a look at the accepted answer in https://stackoverflow.com/questions/7165108/in-os-x-lion-lang-is-not-set-to-utf-8-how-to-fix-it

**Comment by JJCSPR** [comment]
Hi mbdbeek,

It turns nothing was assigned to LC_ALL on my system. I followed the instructions you linked to on StackOverflow, and now have the locale output returned in the accepted answer.

I ran into the same problem again in a new terminal session after I had already implemented the recommended fixes. I would like to know if you could point me in a direction where I could find a possible solution.

**Comment by mvdbeek** [comment]
I'd guess this is still not set up correctly. You can do the inverse check and run `LC_ALL=en_US.UTF-8 sh run.sh`.

**Comment by hexylena** [comment]
Closed pending user response
