### ISSUE TITLE
local tool unavailable if (older version) from TS is installed

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6901]
I like to debug tools by installing them locally (adding them manually to tool_conf.xml). I just manually installed a new version of spades (3.11.1+galaxy2) and have also 3.11.1+galaxy1 and 3.11.1 from the toolshed

During startup I see the expected messsages like (list not complete):
```
Loaded tool id: spades, version: 3.11.1+galaxy1 into tool panel..
Loaded tool id: spades, version: 3.11.1+galaxy2 into tool panel..
Loaded tool id: toolshed.g2.bx.psu.edu/repos/nml/spades/spades/3.11.1+galaxy1, version: 3.11.1+galaxy1 into tool panel....
```

But I can not select the version 3.11.1+galaxy2 of the tools since only the older ones are available. Only uninstalling all older versions allowed me to select the new version. 

But then all previous runs of spades can not be restarted, and the tool info page of older jobs tells me

```
Unable to load parameters.
```

I guess I forgot some detail on how to manually install tools....

**Comment by mvdbeek** [comment]
We only monitor the shed_tool_conf.xml file, we could also monitor the regular tool_conf.xml file.
Initially I just wanted to avoid poeple having to restart Galaxy when installing new tools, but this is a valid use case as well. We currently also have the option to monitor an entire directory, but I'm always forgetting the syntax, and it has never been documented AFAIK.

**Comment by bernt-matthias** [comment]
> We only monitor the shed_tool_conf.xml file, we could also monitor the regular tool_conf.xml file.
Initially I just wanted to avoid poeple having to restart Galaxy when installing new tools, but this is a valid use case as well. We currently also have the option to monitor an entire directory, but I'm always forgetting the syntax, and it has never been documented AFAIK.

Actually I restarted the Galaxy.

**Comment by mvdbeek** [comment]
And your tool's not broken and you modified the correct tool_conf.xml(.sample) file ? Cause that works for me (as well as changing the local tool triggering a reload).

**Comment by mvdbeek** [comment]
Meh, I guess so, since you see it loading in the logs. Any chance the tool is just outside of the expected panel section?

**Comment by bernt-matthias** [comment]
Exactly, I added the new version to a "debug" category and the others were in another category. So this might be the problem...

**Comment by mvdbeek** [comment]
OK, I guess we're not joining the lineages back into the tool shed tools' lineage. I guess you can switch from the non tool shed installed tool to the tool shed tools, but not the other way round. Would be good to have this.

**Comment by martenson** [comment]
Mixing shed and local tools into one lineage does not sound like a good idea. The local one can change any time into any version including conflicting or invalid. I would rather have them separate under different ID (e.g. `spades_local`).

**Comment by mvdbeek** [comment]
I don't agree, if you don't have the same lineage you can't just take a previous run and verify whatever you're fixing is fixed. The tool ids will be different, so there's no reproducibility issue. We can display a warning if you think that'd be better.

**Comment by mvdbeek** [comment]
Counter argument is of course "write a test for what you're fixing", but sometimes that is tricky with real data.

**Comment by bernt-matthias** [comment]
Just need this sometimes for temporary testing. For me its sufficient to have a solution. I can

-  install it in the same section
- just give it temporarily a different name

From my side we can close this.

**Comment by mvdbeek** [comment]
OK, given it's not undisputed we can revisit this if necessary.
