### ISSUE TITLE
auto_compressed_types / converter question

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#6902]
During evaluating the spades tool (which accepts fastq only). I discovered the following behaviour when I give it fastq.gz. 

- There are extra jobs created which gunzip dumps the fastq content to a new data set (`GALAXY_ROOT/database/files/XXX/dataset_ZZZ.dat`) 
- These files are then used as input to spades 

I'm wondering if links to these data sets are stored somewhere (history, data base,...), and how they are supposed to be deleted. My intuition is that the cleanup jobs are supposed to do this (which I have not set up so far). 

- If so: how is it ensured that the cleanup job does not delete during the execution of spades.
- If not: how should this data be cleaned?

As far as I understand these auto_compressed_types (found only very little documentation) automatically add a converter. Is the same happening when a converter is started (also here it seems difficult to find documentation since docs.galaxy... only brings up references source code).

**Comment by nsoranzo** [comment]
The automatically converted datasets are deleted by the cleanup script when the datasets (or the history they are in) are purged.

**Comment by bernt-matthias** [comment]
Just to be sure: The data set is also deleted if the history is purged by the user? 

I remember now why I never set up the scripts: I didn't like the idea that deleted data is automatically purged after X days.

**Comment by hexylena** [comment]
> deleted if the history is purged by the user

That's probably also dependent on the scripts?
