### ISSUE TITLE
UUID based workflow invocation missing meta-data

### ISSUE THREAD

**Issue by kellrott** [galaxyproject/galaxy#691]
If supplied with a workflow input such at {"id" : <uuid>, "src" : "uuid"} it looks for a matching dataset, adds it to the history, and invokes the workflow. (The data matching step occurs at https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/workflow/run_request.py#L237). Currently the `add_dataset` method is called, and a new HDA instance is created with no initialized meta-data. (https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/workflow/run_request.py#L245)

This works most of the time. The problem is that it does nothing to setup the meta-data, so when you have tools that look for things like BAM file indexes, ie the command line template `${bam_file.metadata.bam_index}`, that value is blank, and the command will be bad.

What would be the best way to fix this? I would think it might be to scan the ldda's and then the hda's to find the first instance it, and copy the file type meta-data to the newly created hda.

**Comment by jmchilton** [comment]
I think when we added this we knew it would be a problem for real applications. Can you use the search API to find an LDA corresponding to the dataset with the given UUID and use that as an input instead. I'd prefer to put that logic in the client because in your case you know there will be only one LDA but that is not true in general.

**Comment by blankenberg** [comment]
I'm surprised that this would work in general as a Dataset found and the DatasetInstance created by this method is not even going to have a datatype that could have the metadata associated with it. For most tools that restrict input to certain datatypes (such as BAM), they shouldn't even be able to run with the default datatype -- an input hda with the wrong datatype should be a fatal error before the job runs.

**Comment by jmchilton** [comment]
Sounds like @kellrott started doing this client tracking on the client side. I'm going to close this issue, feel free to open a new one for your issue @blankenberg.
