### ISSUE TITLE
optional select is not optional by default

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#692]
Hi,

the following optional select is `"--non_directional"` by default. I would expect it is optional and nothing is selected. I tried `expanded="False"` and also to set every option to `selected=False` but this does not work either.

```
    <param name="non_directional_option" type="select" optional="True" label="Non directional library options">
         <option value="--non_directional">Non directional (--non_directional)</option>
         <option value="--pbat">Post-Bisulfite Adapter Tagging (--pbat)</option>
    </param>
```

**Comment by hexylena** [comment]
Related to https://github.com/galaxyproject/galaxy/issues/599
