### ISSUE TITLE
Resume jobs in history panel only resumes first paused job

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#6926]

**Comment by cgirardot** [comment]
I have the same here I think. Note we migrated to 18.09 yesterday. 
This night two of my workflows failed. After re-running the failed jobs with the *resume paused jobs* option checked, only the direct next jobs were resumed while the other paused jobs were not. I can restart *the next wave* of paused job using the global history control *Resume Paused Jobs* but the dependent jobs would hang again. I basically have to monitor the WFs and *Resume Paused Jobs* until my WF is complete...
