### ISSUE TITLE
Download button for dataset collection member does not behave as for dataset (18.05/Chrome)

### ISSUE THREAD

**Issue by eschen42** [galaxyproject/galaxy#6939]
@dannon 
In Galaxy 18.05 (using Chromium on Ubuntu or Chrom on Windows), I:

- click on a list (i.e., a collection of datasets of one type)
- click on the name of one of the list members to reveal the download button
- click on the download button

The **observed behavior** is that the dataset is sent to my browser window, encoded with characters from the set `[0-9a-zA-Z/+?]` (I don't know what this encoding is).

The **expected behavior** would be to download the file exactly as happens when I click the download button for a dataset in the history pane.

**Comment by eschen42** [comment]
Workaround: I can click on the eyeball, which (for a large file) displays the beginning of the file and gives me a `save` link that I can use to download the file.

**Comment by dannon** [comment]
@eschen42 What type of data is this?  Or, is this happening with everything?

**Comment by dannon** [comment]
@eschen42 Nevermind, I've reproduced it and can work on a fix.  Thanks for the report!

**Comment by dannon** [comment]
@eschen42 Thanks again for the report, should be fixed in #6960

**Comment by jmchilton** [comment]
Closing because fixed, thanks @dannon!
