### ISSUE TITLE
`nodeenv` not found on updated install `release_18.09`

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#6940]
I'm updating my test system to 18.09, following the steps in https://galaxyproject.github.io/training-material/topics/admin/tutorials/upgrading/slides.html. Running `common_startup.sh` I get the error:
```
The Galaxy client has not yet been built and will be built now.
Installing node into /galaxy/galaxy-app/.venv with nodeenv.
./scripts/common_startup.sh: line 228: nodeenv: command not found
```
I'm assuming that `nodeenv` has been inadvertently left off the requirements list?

**Comment by nsoranzo** [comment]
```
soranzon@localhost:~/software/galaxyproject_galaxy_release_18.09$ grep nodeenv requirements.txt 
nodeenv==1.3.2
```

**Comment by dannon** [comment]
@lparsons I replied on gitter, but just so it doesn't get lost in the noise -- please ping me when you have a sec so we can dig into this.

**Comment by lparsons** [comment]
Turns out this was an issue with my local git repository being in a strange state (not really sure how). Resolving that and getting the proper files updated fixed this issue.
