### ISSUE TITLE
Enabling a galaxy instance in Azure cloud to schedule jobs to an external on-premises HPC cluster 

### ISSUE THREAD

**Issue by aklwong** [galaxyproject/galaxy#6947]
We are working on a project in providing a Cloud based research platform for Health Informatics and Bioinformatics. Long story short, one of the components to be provided by the project is a Galaxy Server for our genomics researchers; and on the other hand, George Washington University also has a HPC system for high performance and high throughput computing.

Our Galaxy Server for this project is hosing in the Cloud (Azure) and the HPC cluster is onsite at GW data center. To allow a galaxy server to utilize external compute power of a HPC, galaxy has provided job runner plugins of DRMAA for job schedulers as well as Pulsar. For our situation, the HPC is a remote system w.r.t. the Galaxy server in the cloud and thus there isn't a shared file system between them. It seems to me that Pulsar would be the appropriate solution for us. Am I on the right track?

I have a similar post sent to the galaxy-dev email list and in fact Bjoern Gruening from the galaxy team has replied telling me that I am on the right track. :)

So now I am digging deeper into it. I have come up with the following scenario: 
We have:
1) a galaxy server running on Azure; 
2) a HPC cluster which is with the Slurm job scheduler at GW.
We are setting up a "job submission node" for our HPC cluster which is for hosting the Pulsar server. 
We will also need to install and configure slurm-drmaa for the Slurm of our HPC.

By having these set up, I believe the Galaxy server (in Azure) and the Pulsar server (in GW) will have the galaxy job staging (moving in/out data and codes) being handled; and because the Pulsar server (on the job submission node) and the HPC cluster both are at GW in the same internal network with a shared file system mounted thus slurm-drmaa can be configure to handle job submission to the HPC.

Any suggestions are much appreciated!

**Comment by mvdbeek** [comment]
That sounds about right but isn't exactly a bug or feature request. For further questions I'd suggest the mailing list.
