### ISSUE TITLE
Unexpected UI behaviour: clicking on quota usage details redirects to galaxyproject.org

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#6964]
![grafik](https://user-images.githubusercontent.com/458683/48003225-befae580-e105-11e8-863e-2db80a2ba022.png)

Redirects to https://galaxyproject.org/support/account-quotas/

Ideally this should redirect to a screen which shows 

- Largest datasets
- Largest histories

in two lists so the users can prune things themselves.

If that's too much work, at least it should be made configurable

**Comment by nsoranzo** [comment]
I also noticed this few hours ago with a user. Maybe the link can point to the "User preferences" (i.e. `/user`) which already has this line at the bottom:

> You are using 123.2 GB of disk space in this Galaxy instance. Your disk quota is: 2.0 TB. Is your usage more than expected? See the [documentation](https://galaxyproject.org/learn/managing-datasets/) for tips on how to find all of the data in your account.

**Comment by ElectronicBlueberry** [comment]
Clicking on quota usage details now redirects to a storage dashboard.
