### ISSUE TITLE
Yarn and certifi error on CentOS 7 with improper version

### ISSUE THREAD

**Issue by shenweiyan** [galaxyproject/galaxy#6973]
When running `sh run.sh` on a Galaxy instance with release_18.09 I ran into the some errors with yarn and certifi. I use Miniconda2 for my base env.
```
$ sh run.sh
Initializing config/migrated_tools_conf.xml from migrated_tools_conf.xml.sample
...
Initializing static/welcome.html from welcome.html.sample
Found conda at: /galaxy-dist/miniconda2/bin/conda
Found Conda, virtualenv will not be used.
To use a virtualenv instead, create one with a non-Conda Python 2.7 at .venv
Creating Conda environment for Galaxy: _galaxy_18.09
To avoid this, use the --no-create-venv flag or set $GALAXY_CONDA_ENV to an
existing environment before starting Galaxy.
...
Found existing installation: certifi 2018.10.15
Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```
I change `certifi==2018.10.15` in requirements.txt, certifi goes well.

```
$ sh run.sh
...
Executing transaction: done
cd client && yarn install --network-timeout 120000 --check-files
yarn install v1.12.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @handsontable/vue@2.0.0-beta1" has incorrect peer dependency "handsontable@^0.38.1".
[4/4] Building fresh packages...
Done in 216.45s.
cd client && yarn run build-production-maps
yarn run v1.12.1
$ NODE_ENV=production gulp staging && concurrently "yarn run style" "yarn run webpack-production-maps" "yarn run gulp clean && yarn run gulp-production-maps" && yarn run save-build-hash
gulp[24634]: ../src/node_contextify.cc:637:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x996c88 node::Abort() [gulp]
 2: 0x996d79  [gulp]
 3: 0x9c66a4 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0xbf5e00  [gulp]
 5: 0xbf786d v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 6: 0x349a95f0409d
/tmp/yarn--1541471531952-0.18039486465344767/node: line 3: 24634 Aborted                 "/galaxy-dist/miniconda2/envs/_galaxy_18.09/bin/node" "$@"
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [client-production-maps] Error 1
ERROR: Galaxy client build failed. See ./client/README.md for more information, including how to get help.
```

I force `yarn=1.7.0` in `GALAXY_ROOT/scripts/common_startup.sh`:
```
echo "Installing yarn into '$CONDA_DEFAULT_ENV' Conda environment with conda."
            $CONDA_EXE install --yes --override-channels --channel conda-forge --channel defaults --name $CONDA_DEFAULT_ENV yarn=1.7.0
```

Then I run `sh run.sh` to reinstall, all goes well. It seems something wrong with the versions, but I don't confirm. Thank you.

**Comment by mvdbeek** [comment]
@istevenshen we don't have the resources or automation yet to keep galaxy's dependencies synced with conda requirements. What you can do if you want to use conda's python interpreter is using the virtualenv package that is modified to work with conda. To do this,
-  install virtualenv via conda (`conda install virtualenv -c conda-forge`)
- create a virtualenv for galaxy (`virtualenv <path to galaxy>/.venv`)

From there on this environment will use the exact packages that have undergone testing and work reliably with galaxy. This is your best bet while Galaxy is not yet installable through pip or conda.

**Comment by shenweiyan** [comment]
> @istevenshen we don't have the resources or automation yet to keep galaxy's dependencies synced with conda requirements. What you can do if you want to use conda's python interpreter is using the virtualenv package that is modified to work with conda. To do this,
> 
> * install virtualenv via conda (`conda install virtualenv`)
> * create a virtualenv for galaxy (`virtualenv <path to galaxy>/.venv`)
> 
> From there on this environment will use the exact packages that have undergone testing and work reliably with galaxy. This is your best bet while Galaxy is not yet installable through pip or conda.

Thank you very much for your advice.

**Comment by mvdbeek** [comment]
Note that I edited my initial post, virtualenv should come from the conda-forge channel (i've added the `-c conda-forge`).

**Comment by mvdbeek** [comment]
I've also opened a PR to make this the default procedure if you run `run.sh` and we detect `conda` on PATH here: #6975
