### ISSUE TITLE
Test framework: do not call _bam_to_sam for compare="contains"

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#700]
The test framework will try to show a diff when the output file does not match, and for the special case of BAM files Galaxy will attempt to convert to SAM prior to generating the diff (see function `_bam_to_sam` in `test/base/twilltestcase.py`).

Example test:

```
<test>
    ...
    <param name="bam_wanted" value="true"/>
    <output name="out_fasta" file="U13small_m.mira4_de_novo.fasta" ftype="fasta" />
    <output name="out_bam" file="empty_file.dat" compare="contains" ftype="bam" />
    <output name="out_maf" file="U13small_m.mira4_de_novo.mira" ftype="mira" />
    <output name="out_log" file="empty_file.dat" compare="contains" ftype="txt" />
</test>
```

I'm being a little sneaky here using `compare="contains"` and an empty file - essentially all I test is that the file exists.

In any case, the very fact I am using `compare="contains"` means that the reference file is not expected to be a full BAM file, and therefore attempting to call `samtools view` on it is likely to fail.

On this test run https://travis-ci.org/peterjc/pico_galaxy/jobs/78430789 for what ever reason this test fails - yet Galaxy attempts to run `samtools view` on the partial BAM file (here literally an empty file):

```
======================================================================
FAIL: MIRA v4.0 de novo assember ( mira_4_0_de_novo ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/peterjc/pico_galaxy/galaxy-dev/test/functional/test_toolbox.py", line 289, in test_tool
    self.do_it( td )
  File "/home/travis/build/peterjc/pico_galaxy/galaxy-dev/test/functional/test_toolbox.py", line 73, in do_it
    raise e
JobOutputsError: History item  different than expected, difference (using contains):
( /home/travis/build/peterjc/pico_galaxy/galaxy-dev/test-data/empty_file.dat v. /tmp/tmpfQXvtU/tmpUpgWsf/new_files_path_Kp4f1Q/tmpS8u1Wdempty_file.dat )
Converting local (test-data) bam to sam failed: (cmd=[samtools view -h -o "/tmp/tmpfQXvtU/tmpUpgWsf/new_files_path_Kp4f1Q/local_bam_converted_to_sam_eYrn8e.sam" "/home/travis/build/peterjc/pico_galaxy/galaxy-dev/test-data/empty_file.dat"], stdout=[], stderr=[[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "/home/travis/build/peterjc/pico_galaxy/galaxy-dev/test-data/empty_file.dat".
])
```

I think that `_bam_to_sam` should not be called for  `compare="contains"` tests, so propose a small change:

```
$ git diff
diff --git a/test/base/twilltestcase.py b/test/base/twilltestcase.py
index 88fdae4..c2afe9b 100644
--- a/test/base/twilltestcase.py
+++ b/test/base/twilltestcase.py
@@ -2302,7 +2302,7 @@ class TwillTestCase( unittest.TestCase ):
                 if attributes is None:
                     attributes = {}
                 compare = attributes.get( 'compare', 'diff' )
-                if attributes.get( 'ftype', None ) == 'bam':
+                if attributes.get( 'ftype', None ) == 'bam' and compare != "contains":
                     local_fh, temp_name = self._bam_to_sam( local_name, temp_name )
                     local_name = local_fh.name
                 extra_files = attributes.get( 'extra_files', None )
```

Arguably the BAM to SAM conversion could be skipped for `compare="sim_size"` but that seems OK either way.

With this change "contains" with a BAM file ought to work at the raw binary level, so it would should then be possible to check for the GZIP header, or special 28 bytes empty GZIP block used as the BGZG/BAM end-of-file (EOF) marker. 

Alternatively for a BAM output file using "contains" could expect a snippet of SAM format, then only the generated BAM file should be converted into SAM.

(I've not tested this proposed fix yet, and will not be able to for a couple of days at least - posting this issue now so that we have a record of it)

**Comment by peterjc** [comment]
Depending on what you want to test, providing a snippet of SAM format would work fine for doing a contains test on a BAM file.

I forget now what my original motivation was in logging this issue, beyond surprise at the implicit BAM to SAM conversion.

**Comment by peterjc** [comment]
Reminded of this issue via a tweet from John from samtools/htslib - even subtle changes in library versions can result in different compressed output, so in general he recommends comparing the decompressed contents:

https://twitter.com/jomarnz/status/1098153857803317249
https://github.com/samtools/htslib/issues/827

In this case, with BAM we could compare the 'naked BAM' binary data (e.g. pipe though gunzip), but SAM is generally more meaningful to use.

**Comment by nsoranzo** [comment]
Looks like this can be closed then, feel free to reopen if I have misinterpreted.
