### ISSUE TITLE
Repetitive login triggers locked database exception

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#7002]
I noticed that login in, followed by login out and then login back in consistently triggers an uncaught exception. Currently only observed in dev.

Does anyone else observe this? Where there any recent recent changes to the login mechanism?

**Comment by mvdbeek** [comment]
Do you have the traceback ?

**Comment by guerler** [comment]
https://gist.github.com/guerler/86d4032f4b0088990b64646b3ea3fd80

**Comment by martenson** [comment]
I think almost nobody uses sqlite so we don't see it, but the cause seems to be the space usage recalculation on logout.

**Comment by guerler** [comment]
Good call. Thanks.

**Comment by jmchilton** [comment]
Removing 19.01 milestone, probably shouldn't be spending too much time on sqlite and it doesn't seem to be related to this release.
