### ISSUE TITLE
Failing metadata script by overwhelming # of jobs

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#7011]
I am starting to see more and more jobs failure not because of the jobs themselves but the metadata script that runs after each job. Example stacktrace available  [here](https://gist.github.com/Takadonet/c6e1138abfc7709ff75880f27bc3c3de)

 It starting to look more and more that we are simply overwhelming our cluster nodes and/or storage since we are hitting daily job spikes of 25k with an average of 10k. 

There is an option in galaxy.yml called retry_metadata_internally but I feel that just cause my fronted to collapse by the weight of all the jobs. 

I just added condition statement to default_job_resubmission_condition: 'attempt < 3 and unknown_error' but does not apply when metadata.py fails. If you take a look at the stacktrace above at the link, we do have Galaxies venv located on our NFS which is backed by Isilion system.

Anyone has any ideas?

**Comment by mvdbeek** [comment]
Could you have the nodes cache the venv in node-local scratch and set `GALAXY_VIRTUAL_ENV` in your destination to that local dir ? That might help a bit

**Comment by Takadonet** [comment]
What would be the best way to cache the venv and ensure that it stays in sync? (probably never really change but when it does)

**Comment by mvdbeek** [comment]
I guess an rsync every X minutes might be fine ?

**Comment by Takadonet** [comment]
Will give that a try. Thanks! Will report back what works...

**Comment by Takadonet** [comment]
So having a local venv on each compute node was the best solution. Not only did it  completely solved the failed metadata, it decrease overall run time as well. 

Thanks @mvdbeek !
