### ISSUE TITLE
Tutorial broken: "Installing Tools into Galaxy"

### ISSUE THREAD

**Issue by olisteadman** [galaxyproject/galaxy#7015]
In [this](https://galaxyproject.org/admin/tools/add-tool-from-toolshed-tutorial/#open-the-tool-shed) line of your first-steps "tutorial on how to install tools to Galaxy", you ask first-time users to "Go to Galaxy [Admin Interface](https://galaxyproject.org/admin/) and click `Search Tool Shed`."

This `Search Tool Shed` button exists in none of 3 intuitive places:

1. the page `https://galaxyproject.org/admin` (to which the instruction links)

2. the Admin panel of a locally running Galaxy instance (`http://127.0.0.1:8080/admin`) following installation and adding of user to admin_users in config/galaxy.yml

3. the public equivalent `https://usegalaxy.org/admin` when logged in as a new user.

Surely this needs an urgent fix? In the meantime, where does a first-time user go, to learn about installing tools?

![selection_303](https://user-images.githubusercontent.com/12253176/48568803-16643700-e8f8-11e8-9929-231936d1ab44.png)

**Comment by martenson** [comment]
Thanks for the insight.

fixed with https://github.com/galaxyproject/galaxy-hub/commit/b512a2b0880899bb5daf3d8e96725fcbc1fb2975
