### ISSUE TITLE
how to resolve uwsgi working wrong  during install galaxy

### ISSUE THREAD

**Issue by GeorgeBGM** [galaxyproject/galaxy#7024]
![image](https://user-images.githubusercontent.com/26595839/48674424-fbf3bd00-eb86-11e8-9804-9232be6d2117.png)

I have try   command ( ps |grep 'uwsgi'),there have none uwsgi  working,but 
(uwsgi --yaml /home/users/ddu/software/Galaxy/galaxy/config/galaxy.yml --static-safe /home/users/ddu/software/Galaxy/galaxy/config/plugins/visualizations --static-safe /home/users/ddu/software/Galaxy/galaxy/config/plugins/interactive_environments
[uWSGI] getting YAML configuration from /home/users/ddu/software/Galaxy/galaxy/config/galaxy.yml)  cannot work, I can make sure uwsgi is the latest version,Can someone give me some advice?Thanks!

**Comment by hexylena** [comment]
If you receive messages about something already bound, you can use the command

```
netstat -planet | grep 8080
```

(there's another version with the more modern `ss` but I don't remember it, probably `ss -tpn | grep 8080`.)

Which will give you the process ID and you can then kill this process.
