### ISSUE TITLE
tags are not styled in 'saved histories'

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#7025]
this is on usegalaxy.org

![screenshot 2018-11-19 11 29 45](https://user-images.githubusercontent.com/1814954/48720811-802d5b00-ebee-11e8-8ccc-905c62368eb9.png)

**Comment by WilliamHolden** [comment]
@martenson Are you still seeing this issue? It looks like the tags are styled now when i go to usegalaxy.org. 

There is another issue on usegalaxy.org where hovering over the "x" shows a broken image but that seems to be fixed on release_19.05 branch

**Comment by dannon** [comment]
Ahh, yeah, this was fixed with the tags display/editor overhaul.  Thanks for following up on it!
