### ISSUE TITLE
Where is the tool execution form?

### ISSUE THREAD

**Issue by AlvaroFaure** [galaxyproject/galaxy#7026]
I'm trying to keep a record of all executions in my Galaxy. To do this I thought to send the information of the process that will run once the user presses the "Execute" button of a tool in the execution form. I would need to find the code of the view in which this button is found, could someone be able to tell me where I can make these changes? Thanks!

**Comment by martenson** [comment]
@AlvaroFaure Galaxy keeps track of all tools executions automatically. Every dataset has the `<i>` icon where you can see all the parameters that were used for the execution (including the full commandline if you are an admin)

**Comment by AlvaroFaure** [comment]
Yes, I know that, but what I need is to automatically keep some simple statistics about which tools are used in my instance of Galaxy, so the only thing I would need is to send certain information even before the tool runs, just by pressing the "Execute" button, that's why I need to find where this view is.

**Comment by martenson** [comment]
@AlvaroFaure All this information is stored in the database, so you could mine/visualize that instead of modifying the code. 

That said, the toolform execute button is here: https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/tool/tools.js#L818
