### ISSUE TITLE
Containerized, Database-Free Job Creation and Completion

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#7050]
Establish internal APIs consuming and producing JSON and detached from the database for every part of command execution. Rewrite these functions that can consume and produce database
models directly as currently or an alternative JSON-ified representation of the relevant models.

Job Setup:

- Command-line generation.
- Environment construction.
- Input staging from object store.
  - Simple datasets.
  - Composite datatypes.
  - Collections.
- Dependency resolution.

Job Completion:

- Job failure detection.
- Dynamic dataset discovery.
- Metadata collection.
- Output writing to object store.

The medium term goal would be placing all these operations into two containerized jobs (setup and completion) and allow splitting Galaxy job execution into a three containerized jobs. The first consuming a JSON-ified description of job inputs and parameters (including input dataset metadata, composite dataset paths) and generate a command-line for the second stage tool described container (typically a biocontainers container), and then a final job completion container.

If done well, one can then imagine a variant of Pulsar (or some other task execution API) that would stage its own files from the object store, generate its own command-line, and unstage files back to the object store by itself, and then just send a much more expansive version of galaxy.json back to Galaxy containing just the data to serialize to the database. This would allow data to live near compute without having to be loaded back to Galaxy workers for metadata collection or through Galaxy workers for input staging. This could dramatically decrease network transfers for large files and could prevent Galaxy from needing to directly touch say protected data to perform computation on it (as long as there is some container-aware service closer to the data that can be used).

While not the end goal, even this medium term goal could help a number of issues with Galaxy jobs.
- Job handlers could potentially not have to do dynamic file discovery - which can sometimes take hours and freeze job handlers for large jobs. https://github.com/galaxyproject/galaxy/issues/1854
- Pulsar could handle dynamic job discovery and staging of galaxy.json defined outputs correctly. https://github.com/galaxyproject/pulsar/issues/93
- We can imagine finally making progress on Pulsar caching of outputs. https://github.com/galaxyproject/pulsar/issues/48
- We can start to imagine a real library for Galaxy tool execution (the piece sitting inside the container) - that could be used by Tool building GUIs, for tool testing without requiring a whole Galaxy server, or by other platforms to leverage Galaxy tools without a Galaxy runtime.
- We can imagine a real library for Galaxy datatypes and metadata handling, sniffing, etc...

The longer term goal will be link these trios of containers together to serialize a description of full Galaxy workflow into a concrete, database-free representation. So that Galaxy workflows can be serialized into a form that could potentially be executed via a [Workflow Execution Service](https://github.com/ga4gh/workflow-execution-service-schemas).

**Comment by natefoo** [comment]
FWIW dynamic output discovery should be much less painful if you limit it to job working directories (`collect_outputs_from: job_working_directory`). But it can still be bad if the tool's written an exorbitant number of files there.

**Comment by afgane** [comment]
Can we also talk a bit more about the data resolution in this context? With all of this, it's starting to feel like we can entirely remove the shared file system and have the job handle data on an individual basis. So the job/Pulsar will receive a UUID for the input datasets, contact the internal API to resolve that UUID to a signed URL (or a destination such as S3 along with the necessary credentials), retrieve the data locally for processing and then largely repeat the process of contacting the object store to get a destination for depositing the output datasets, right?
If so, would the internal API communicate with a Galaxy object store (micro)service that does the dataset resolution and also a credentials (micro)service (such as Custos) to obtain the necessary temp creds? For that to work, these services could be part of Galaxy but could also be external, largely standalone services. Pulsar (or similar) could implement a variety of protocol handlers to be able to obtain data from a cloud objects store, NFS, CVFMS, etc. at the expense of implementing all those plugins.

**Comment by jmchilton** [comment]
> With all of this, it's starting to feel like we can entirely remove the shared file system and have the job handle data on an individual basis

This is the whole point I think largely - keeping the data off the Galaxy server. Though I'd move the UUID discussion to a new issue and add those abstractions in some useful way to the objectstore, I'm starting with dataset IDs I think.

So I think some of what you described can be done for inputs today - or is very close to being able to be done. Galaxy can now defer to an object store dynamically based on job destination:

https://github.com/galaxyproject/galaxy/commit/7882a067c8cbcf564aff605b91beea8d7849fb00#diff-3c62e82e72ce988e633066c5a9b670bb

While deactivated, one such option is to defer to Pulsar to do the staging and figure out what the paths would be on the Pulsar server (which would be configured with its own concrete objectstore)

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/objectstore/pulsar.py#L11

This can't really be done for outputs yet because of metadata collection for instance. It would be a lot easier to be done for inputs also - if the command-line could be generated remotely. That's what this issue is about.

**Comment by jmchilton** [comment]
We did the job cleanup portion of this over the course of a year culminating in extended metadata (though it still has some issues). I'm going to close this out and create a new issue for the job setup portion of this.
