### ISSUE TITLE
Issue using diffbind

### ISSUE THREAD

**Issue by niphilli** [galaxyproject/galaxy#7051]
Getting the following error when running diffbind. Running three replicates in two groups; I tried with and without control bam files.  Any ideas? Thanks in advance.

> [1] "en_US.UTF-8"
> Fatal error: An undefined error occured, please check your input carefully and contact your administrator.
> Warning: namespace ‘RMySQL’ is not available and has been replaced
> by .GlobalEnv when processing object ‘collapse’
> Warning: names

**Comment by bgruening** [comment]
Are there more lines of the error message? I have seen a similar error report lately, but the error was much further down.

**Comment by niphilli** [comment]
Yes, apologies. Here is the entire error output...

> Fatal error: An undefined error occured, please check your input carefully and contact your administrator.
> Warning: namespace ‘RMySQL’ is not available and has been replaced
> by .GlobalEnv when processing object ‘collapse’
> Warning: namespace ‘RMySQL’ is not available and has been replaced
> by .GlobalEnv when processing object ‘collapse’
> Warning: namespace ‘RMySQL’ is not available and has been replaced
> by .GlobalEnv when processing object ‘collapse’
> Warning: namespace ‘RMySQL’ is not available and has been replaced
> by .GlobalEnv when processing object ‘collapse’
> MACS2_callpeak_on_data_19_and_data_14__narrow_Peaks_ MACS2_callpeak_on_data_19_and_data_14__narrow_Peaks_  LEFT_only2reps_84and86  NA raw
> MACS2_callpeak_on_data_22_and_data_16__narrow_Peaks_ MACS2_callpeak_on_data_22_and_data_16__narrow_Peaks_  LEFT_only2reps_84and86  NA raw
> MACS2_callpeak_on_data_19_and_data_15__narrow_Peaks_ MACS2_callpeak_on_data_19_and_data_15__narrow_Peaks_  RIGHT_only2reps_84and86  NA raw
> MACS2_callpeak_on_data_22_and_data_17__narrow_Peaks_ MACS2_callpeak_on_data_22_and_data_17__narrow_Peaks_  RIGHT_only2reps_84and86  NA raw
> Warning messages:
> 1: In message(as.character(samples$SampleID[i]), " ", as.character(samples$Tissue[i]),  :
>   NAs introduced by coercion
> 2: In cbind(NULL, c(sampID, tissue, factor, condition, consensus, peak.caller,  :
>   NAs introduced by coercion
> 3: In message(as.character(samples$SampleID[i]), " ", as.character(samples$Tissue[i]),  :
>   NAs introduced by coercion
> 4: In cbind(NULL, c(sampID, tissue, factor, condition, consensus, peak.caller,  :
>   NAs introduced by coercion
> 5: In message(as.character(samples$SampleID[i]), " ", as.character(samples$Tissue[i]),  :
>   NAs introduced by coercion
> 6: In cbind(NULL, c(sampID, tissue, factor, condition, consensus, peak.caller,  :
>   NAs introduced by coercion
> 7: In message(as.character(samples$SampleID[i]), " ", as.character(samples$Tissue[i]),  :
>   NAs introduced by coercion
> 8: In cbind(NULL, c(sampID, tissue, factor, condition, consensus, peak.caller,  :
>   NAs introduced by coercion
> converting counts to integer mode
> gene-wise dispersion estimates
> mean-dispersion relationship
> final dispersion estimates
> Warning message:
> No sites above threshold 
> Error in pv.getPlotData(DBA, attributes = attributes, contrast = contrast,  : 
>   Unable to plot -- no sites within threshold
> Calls: dba.plotHeatmap -> pv.getPlotData

**Comment by niphilli** [comment]
Just tried to rerun with FDR filter at 1 to see if that was the source off the error, and it worked.

**Comment by mvdbeek** [comment]
Not sure if that resolved your issue, but if not feel free to open an issue at https://github.com/galaxyproject/tools-iuc/issues
