### ISSUE TITLE
Cannot undo use of snowflakes in workflow

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#7055]
On 18.09 and usegalaxy.org the effect of snowflakes is not correctly undone. Once a workflow had one(or more) snowflake set (and saved) the hide post action stay even after removing all snowflakes. I believe this tends to happen after adding a new step and then removing the snowflakes. 

Example: https://usegalaxy.org/u/_jelle/w/no-more-snowflakes (downloading the workflow will show the post actions)

**Comment by mvdbeek** [comment]
Yeah, this is buggy. If there are no stars on the ouputs this will initially be interpreted as no PJA, while as soon as you set one, all other will be assumed to be hidden. Now if if unstar all they remain in the hidden state.

**Comment by dannon** [comment]
@mvdbeek I can take a look at this one unless you're looking at it right now.  It used to work, not sure when this broke, but it should be straightforward.  (I was going to roll that other feature request into it)

**Comment by mvdbeek** [comment]
I think I know where this is going wrong, but I haven't written any code. I think it makes sense to address the bug individually ?

**Comment by dannon** [comment]
@mvdbeek I was thinking it'd make sense to bundle it, since we might want the ability to 'fix' workflows that have been busted like this explicitly, not relying on someone re/un-snowflaking and resaving.

**Comment by mvdbeek** [comment]
They are separate IMO, the UI is correctly displaying no star, so a simple save or edit would suffice, no need for an additional button.

**Comment by dannon** [comment]
@mvdbeek Right, but there's no explanation of what's going on in the UI suggesting that a re-save is necessary.

**Comment by mvdbeek** [comment]
I guess bonus points for starting out with all stars -- that'd be more restful and easier to grasp for people that don't know the rules. And I guess that'd simplify the code as well.
