### ISSUE TITLE
can not connect to https://toolshed.g2.bx.psu.edu/

### ISSUE THREAD

**Issue by zhuangfjnu** [galaxyproject/galaxy#7069]
Hi all ,
I can not  connect to https://toolshed.g2.bx.psu.edu/ and can't install tools in local galaxy. Anyone have  same issue?

Zhen

**Comment by martenson** [comment]
You are correct, we are working on a fix. Details will be here: https://help.galaxyproject.org/t/main-tool-shed-down/85/2
