### ISSUE TITLE
unable to add emoji hashtags to Test Galaxy

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#7075]
works on usegalaxy.eu

on test.galaxyproject.org after saving the `#🐟` you will get `name` or `##`

![screenshot 2018-12-05 15 23 19](https://user-images.githubusercontent.com/1814954/49541826-e3cbaf80-f8a1-11e8-80ab-eb56c9321c15.png)
![screenshot 2018-12-05 15 24 03](https://user-images.githubusercontent.com/1814954/49541827-e3cbaf80-f8a1-11e8-924b-07e28a33d723.png)

**Comment by hexylena** [comment]
Yeah! Now that I've discovered I can just #:bee: for my apiMel3 samples and all my :hankey: samples can be easily labeled... I can't live without it. ;)

![grafik](https://user-images.githubusercontent.com/458683/49542145-a4668880-f8cc-11e8-8e4c-fe6bafe3319c.png)

**Comment by martenson** [comment]
I guess somewhere between 18.05 and dev we started treating tag names differently?

**Comment by hexylena** [comment]
Update, cannot see emojis in 18.09, @bgruening also noticed that they stopped working. So between 18.05 and 09.

**Comment by mvdbeek** [comment]
Fixed by https://github.com/galaxyproject/galaxy/pull/7310

**Comment by martenson** [comment]
🎉
