### ISSUE TITLE
xlsx datatype not usable

### ISSUE THREAD

**Issue by yvanlebras** [galaxyproject/galaxy#7077]
Hi Galaxistes, 

I'm creating a wonderfull Galaxy tool... allowing extraction of a Excel sheet into a tabular file (godness ;) ). And trying to use xlsx Excel files, I can't make the tool working, but using xls it works. In fact, it seems the issue is really related to the definition of the xlsx Galaxy datatype (galaxy.datatypes.binary:Xlsx) who is not well defined. This can be seen uploading xlsx data specifying the xlsx datatype on a usegalaxy.* instance (.eu here) where the uploaded dataset contains these informations lines:
```
Warning: The file 'Type' was set to 'xlsx' but the file does not appear to be of that type
```
Can anyone have a look at this? Maybe the issue was existing considering xls old datatype and thus I see the old xls datatype definition is deprecated and we have to use the excel.xls one...

**Comment by yvanlebras** [comment]
Hmm.. Looking at https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/binary.py#L1544 it seems the xlsx datatype is related to a compress one. Maybe it's part of the issue ?

**Comment by mvdbeek** [comment]
This seems to work fine during a quick test on the last 18.09 commit as well as usegalaxy.org.
Can you attach the file that isn't working ?
![screen shot 2018-12-06 at 12 09 11](https://user-images.githubusercontent.com/6804901/49580707-dbca4900-f94f-11e8-889f-ff723e839b15.png)

**Comment by mvdbeek** [comment]
Yeah, so this doesn't work on usegalaxy.eu, I'm suspecting a deployment issue, maybe https://github.com/galaxyproject/galaxy/pull/6867 hasn't been applied.

**Comment by hexylena** [comment]
It is not so much a deployment issue as we have not upgraded to 18.09 yet. Correct, #6867 has not been applied. Please see the large notice on our home page regarding this. 
![grafik](https://user-images.githubusercontent.com/458683/49591510-89485700-f966-11e8-8af8-f4af20c0d649.png)

**Comment by yvanlebras** [comment]
Thank you @mvdbeek @erasche for your rapid and detailled feedbacks! True, I encounter the error on usegalaxy.eu but initially on a Galaxy flavour so maybe updating the container will fix the issue OR I have to fix this manually following https://github.com/galaxyproject/galaxy/pull/6867/files. Thank you so much!
