### ISSUE TITLE
Rendering errors for collections in shared history

### ISSUE THREAD

**Issue by jxtx** [galaxyproject/galaxy#7089]
Regular datasets render at full width, but collections only fill the width partially.

![image](https://user-images.githubusercontent.com/79973/49757894-85c90e80-fc8b-11e8-9070-894503c4a446.png)

**Comment by dannon** [comment]
Does this happen against dev, too?  I thought I already fixed this in a separate issue, maybe we didn't backport the fix to 18.09?

**Comment by jxtx** [comment]
This is on test which appears to be running dev from Friday or so.

**Comment by dannon** [comment]
Hrmm, definitely wasn't since Friday -- I looked at this a month or more ago when we had all those various positioning issues related to flex.  @guerler I can take a look and dig up what I did before, if you want.

**Comment by guerler** [comment]
Sure, that works for me. I too remember that this issue occured a few weeks ago.
