### ISSUE TITLE
Publication of Galaxy Release (v 15.10)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#713]
Items:
- [x] Finalize https://github.com/galaxyproject/galaxy/blob/dev/doc/source/releases/15.10_announce.rst
- [x] Post release notes to https://galaxy.readthedocs.org/en/master/releases/index.html
- [x] Create wiki _highlights_ and post to http://galaxyproject.org News (w/ RSS) and NewsBriefs
- [x] Tweet wiki news _highlights_ (or RTD?) via bit.ly link to https://twitter.com/galaxyproject/
- [ ] Post _highlights_ type News to Galaxy Biostars https://biostar.usegalaxy.org
- [ ] Email _highlights_ to galaxy-dev and galaxy-announce @lists.galaxyproject.org

**Comment by hexylena** [comment]
Maybe turn into a formalized document, à la [planemo's](https://github.com/galaxyproject/planemo/blob/master/docs/developing.rst)?

**Comment by jmchilton** [comment]
@erasche I think we are going to try to do this 15.10. I'll create a separate issue for documenting and automating the release process - but I think each release will have a specific issue and checklist like this one.

**Comment by hexylena** [comment]
Assuming all of these happened at some point

**Comment by martenson** [comment]
Only the first two happeened :/
release notes at https://docs.galaxyproject.org/en/master/releases/15.10_announce.html

**Comment by jennaj** [comment]
@erasche @martenson I'll do the rest .. try to get to it by tomorrow. Bug me if you don't see it :)

**Comment by martenson** [comment]
@jennaj It might be too late for the email... not sure
the tweet actually hapenned: https://twitter.com/galaxyproject/status/671787288909717504

**Comment by jennaj** [comment]
@martenson Ok, let's leave it alone this time. We can update the wiki once it is in the new format to have a complete list of releases with highlights/links for reference. For some reason I am imagining a search function that would scan all. Would be very helpful to find new/update/fix by keyword.

**Comment by martenson** [comment]
@jennaj If you want to update the wiki for this, please feel free to do it now. We won't lose any data during the conversion.

**Comment by jennaj** [comment]
@martenson ok, then I'll add, tx!

**Comment by jennaj** [comment]
done
- https://wiki.galaxyproject.org/News/2015_10_GalaxyRelease
- https://wiki.galaxyproject.org/News
- https://wiki.galaxyproject.org/DevNewsBriefs

**Comment by martenson** [comment]
thanks Jen!

**Comment by jennaj** [comment]
I usually stage drafts for release content, all sites, once we are confirmed a go to announce. This ensures auto-tagged dates match up. Content can be adjusted for everything (except emails, once gone). If not automated by next round, make sure to ping me so I can do that in a timely way.

No email, no Biostars this round. Speak up all if you want those to go out now.

**Comment by jennaj** [comment]
Onward! https://github.com/galaxyproject/galaxy/issues/1499
