### ISSUE TITLE
Multi History drop datasets broken in dev

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#7137]
I can't copy datasets from another history, the drop target is properly displayed, there are no errors in the console, and no request is made. The only warning I see it: `Does app ever run? Is it ever not-named app?`

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/issues/7138

**Comment by jmchilton** [comment]
Ping @guerler ?

**Comment by mvdbeek** [comment]
This is still an issue on dev.
![multi_history_copy_bug](https://user-images.githubusercontent.com/6804901/50959530-7673f580-14c3-11e9-8172-952a65e5ec8a.gif)

**Comment by mvdbeek** [comment]
Fixed by #7218
