### ISSUE TITLE
Drag into upload broken in dev

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#7138]
If you try dragging a file into the upload field the browser just displays the file.
The workflow drag handler works fine though.

**Comment by guerler** [comment]
xref #4901

**Comment by guerler** [comment]
A possible workaround is to replace the event listener i.e. https://github.com/galaxyproject/galaxy/commit/c37b413b4c45e30b78a11245b1ff32d6608a5463, but it would be nice to fix the actual underlying problem instead of resolving the symptom. @dannon do you think that's possible?
