### ISSUE TITLE
Saving a broken workflow hangs forever and requires a page refresh

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#7140]
Seen on dev with @shiltemann, if you upload a 'broken' workflow with missing tools/etc, and try to save it, the safe dialog hangs and renders the interface unresponsive. You must refresh the page and lose your changes. It should just show the error message / toast that the saving failed / something, and let you regain control of the interfac.e

**Comment by guerler** [comment]
Can you share a workflow which causes that?

**Comment by guerler** [comment]
This happens to any workflow with missing tools. It seems to be caused by #6741.

**Comment by mvdbeek** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/7227, please re-open if you see it again.
