### ISSUE TITLE
Document and Automate Release Process

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#715]
Goal here should be to create a transparent release process with anything that can be reasonably automated done so and documented.

An example would be [planemo's documentation](https://github.com/galaxyproject/planemo/blob/master/docs/developing.rst) and corresponding [Makefile](https://github.com/galaxyproject/planemo/blob/master/Makefile) - but obviously things are much more challenging with Galaxy.

Create a `Makefile` with commands for:
- [x] Creating a new release issue (like [15.10](https://github.com/galaxyproject/galaxy/issues/713#issuecomment-139374875)).
   Goal would be to automate the creation of the issue and checklist put together by @jennaj using a command like `make release-issue VERSION=15.12`.
- [x] Stub out release notes. (e.g. expose existing script using `make release-notes OLD_VERSION=15.07 VERSION=15.10`)
- [x] Tagging a release. `make release-tag VERSION=15.10`.

Create release documentation including complete process for issuing a release. Even if we cannot for instance completely automate the back porting of releases to mercurial - we should document the strategy at a high level.
- [ ] Document creating release notes.
- [ ] Document tagging the release. 
- [ ] Document creating release issue on github.
- [ ] Document publicizing the release (wiki, tweet to wiki, news to biostars, posting highlights to dev and announce).

**Comment by jmchilton** [comment]
Wonder if the ultimate goal should be that everyone involved in the release process document every detail with 15.10 and then we have different team members take on these responsibilities for 15.12. These other people will encounter the holes in the documentation and be able to fix them quickly I think.

**Comment by mr-c** [comment]
@jmchilton Alternating who did release improved our checklist and automation greatly; I recommend it.

**Comment by jennaj** [comment]
@jmchilton where do you want to document this? RTD?

**Comment by hexylena** [comment]
Pinging all since 16.01 is just around the corner.

**Comment by natefoo** [comment]
Pong

Once the bitbucket push is dropped, this will be much easier.

**Comment by natefoo** [comment]
``` console
nate@weyerbacher% git checkout dev
Switched to branch 'dev'
Your branch is up-to-date with 'origin/dev'.
nate@weyerbacher% git pull upstream dev
  ...
From https://github.com/galaxyproject/galaxy
  ...
nate@weyerbacher% git push origin dev
  ...
To git@github.com:natefoo/galaxy
  ...
nate@weyerbacher% git checkout -b release_16.01
Switched to a new branch 'release_16.01'
nate@weyerbacher% git push origin release_16.01
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:natefoo/galaxy
 * [new branch]      release_16.01 -> release_16.01
nate@weyerbacher% git push upstream release_16.01
Total 0 (delta 0), reused 0 (delta 0)
To https://natefoo@github.com/galaxyproject/galaxy.git
 * [new branch]      release_16.01 -> release_16.01
nate@weyerbacher% git checkout -b version-16.01
Switched to a new branch 'version-16.01'
nate@weyerbacher% vim lib/galaxy/version.py
nate@weyerbacher% git add lib/galaxy/version.py
nate@weyerbacher% git commit
[version-16.01 a0610ec] Update version to 16.01.rc1
 1 file changed, 1 insertion(+), 1 deletion(-)
nate@weyerbacher% git checkout dev
Switched to branch 'dev'
nate@weyerbacher% git checkout -b version-16.04.dev
Switched to a new branch 'version-16.04.dev'
nate@weyerbacher% vim lib/galaxy/version.py
nate@weyerbacher% git add lib/galaxy/version.py
nate@weyerbacher% git commit 
[version-16.04.dev a4b252b] Update version to 16.04.dev
 1 file changed, 1 insertion(+), 1 deletion(-)
nate@weyerbacher% git merge version-16.01
Auto-merging lib/galaxy/version.py
CONFLICT (content): Merge conflict in lib/galaxy/version.py
Automatic merge failed; fix conflicts and then commit the result.
nate@weyerbacher% git checkout --ours lib/galaxy/version.py
nate@weyerbacher% git add lib/galaxy/version.py
nate@weyerbacher% git commit
[version-16.04.dev e9f6a73] Merge branch 'version-16.01' into version-16.04.dev
nate@weyerbacher% git push origin version-16.01:version-16.01
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 434 bytes | 0 bytes/s, done.
Total 5 (delta 4), reused 0 (delta 0)
To git@github.com:natefoo/galaxy
 * [new branch]      version-16.01 -> version-16.01
nate@weyerbacher% git push origin version-16.04.dev:version-16.04.dev 
Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 585 bytes | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
To git@github.com:natefoo/galaxy
 * [new branch]      version-16.04.dev -> version-16.04.dev
```

And then I PR'd `version-16.01` against `release_16.01` and `version-16.04.dev` against `dev`.

**Comment by hexylena** [comment]
Thanks @natefoo. :) I'll write up a Makefile for this soon.

**Comment by jmchilton** [comment]
Lots of work on this in https://github.com/galaxyproject/galaxy/pull/1613, including my prodding to swap some jobs around or 16.04 and have everyone document what they are doing for 16.01.
