### ISSUE TITLE
Fastqc result does not display properly

### ISSUE THREAD

**Issue by 19zhangt** [galaxyproject/galaxy#7151]
Galaxy doesn't seem to display html results properly. This is the test result in Galaxy version 19.01.dev
![default](https://user-images.githubusercontent.com/39303150/50416564-50f8b200-085c-11e9-85c3-a1b862db27b0.png)

**Comment by bernt-matthias** [comment]
The admin of this Galaxy instance needs to add FastQC to the whitelist.

**Comment by 19zhangt** [comment]
Thank you very much！
