### ISSUE TITLE
Issues with prefix path (/galaxy)

### ISSUE THREAD

**Issue by ashvark** [galaxyproject/galaxy#7162]
I am using galaxy 18.09 version with old galaxy.ini format. 

I am getting javascript error in the multiple history view. When I debug the issue i realised that galaxy request url does not contains the prefix (/galaxy) . for example http://localhost:8082/api/histories/0a248a1f62a0cc04/contents/datasets/e90facaf332c3038 . This issue happens only in the multiple history view.

![image](https://user-images.githubusercontent.com/7712157/50595796-36e55200-0ea2-11e9-8270-8dc32a1019cb.png)

Also, several links in the top menu seems to be broken. In this case the prefix path is duplicated
http://localhost:8082/galaxy/galaxy/workflows/list?__identifer=h0cm1bzxuc
http://localhost:8082/galaxy/galaxy/visualizations?__identifer=lt0el2s7baq
http://localhost:8082/galaxy/galaxy/user?__identifer=39ze7z0ldbc
http://localhost:8082/galaxy/galaxy/custom_builds?__identifer=juay9tburl8

if would be great if someone can provide a solution to fix this issue.

**Comment by ashvark** [comment]
All the links (Workflow, Create Visualize, Shared Histories ) are working fine when accessing from the shared data libraries page whereas the same links are broken ("/galaxy/galaxy/*****) when accessing from the home page.

**Comment by ashvark** [comment]
Also the issue with multi history panel seems to work with the latest dev version, I think  #7005 should have some fixes to this issue.

**Comment by ashvark** [comment]
I made some dirty fixes in my galaxy application to overcome the issue with broken top menu links. I made following changes in the file ` client/galaxy/scripts/layout/menu.js`
```javascript
                    if (options.target == "__use_router__" && typeof Galaxy.page != "undefined") {
                        //Galaxy.page.router.push(options.url);
                        Galaxy.page.router.push(options.url.replace("/galaxy/","/"));
                    } else {
                        options.url=String(options.url).startsWith("/galaxy")? options.url : "/galaxy" + options.url;
                        Galaxy.frame.add(options);
                    }
```

```javascript
                    if (model.attributes.target == "__use_router__" && typeof Galaxy.page != "undefined") {
                        Galaxy.page.router.push(model.attributes.url.replace("/galaxy/","/"));
                        //Galaxy.page.router.push(model.attributes.url);
                    } else {
                        model.attributes.url= String(model.attributes.url).startsWith("/galaxy")? model.attributes.url : "/galaxy" + model.attributes.url
                        Galaxy.frame.add(model.attributes);
                    }
```
I hope there will be a permanent fix in the next galaxy release.

**Comment by hexylena** [comment]
There have been numerous routing fixes since then, hopefully it's working now.
