### ISSUE TITLE
Tool IU - parameter mins no longer expressed to users and are silently enforced

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#7172]
Integer and floating parameter types with a min specified is not properly relayed to user. Values entered by a user are 'silently' changed (replaced without notice), see attached gif. 

Previously this would cause a validation error to be displayed to the user, and tool would not execute until user corrected.

![screen recording 2019-01-04 at 4 55 55 pm](https://user-images.githubusercontent.com/1231190/50713316-84002a00-1042-11e9-9b1b-a361301da758.gif)

May also be helpful to confirm that all validation failures are still being properly displayed to the user and not automatically corrected and executed.

**Comment by nsoranzo** [comment]
This is happening since at least Galaxy 15.10 (the oldest version I was able to start on my laptop).

The value is changed via JavaScript as soon as the focus is moved from the param value.

**Comment by jmchilton** [comment]
Ping @guerler

**Comment by guerler** [comment]
@nsoranzo is correct. This is the expected behavior. However it makes sense to highlight the field if the user attempts to change the value out of range.

**Comment by blankenberg** [comment]
Awesome, thanks!
