### ISSUE TITLE
Tool syntax: allow multiple options of a conditional

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#7173]
Thinking of something like this: 

```
<conditional name="action_cond" label="Actions">
            <param name="action_select" type="select" multiple="true" label="action sel">
                <option value="option1" selected="True">option1</option>
		<option value="option2">option2</option>
		<option value="option3">option3</option>
            </param>
            <when value="option1">
            ....
            </when>
            <when value="option2">
            ....
            </when>
            <when value="option3">
            ....
            </when>
```

So if option1 and option2 are selected, then the parts of both options should be shown.

This could be useful for instance if a program has several actions that can be applied and each action has its own set of parameters. This way the user gets only those options that are relevant for her choice.

**Comment by bernt-matthias** [comment]
Also `optional="true"` would be neat.

**Comment by nsoranzo** [comment]
@bernt-matthias Cannot this be achieved with `<section>`s?

**Comment by bernt-matthias** [comment]
I mean to have a optional select variable: `<param name="action_select" type="select" optional="true" label="action sel">`. I don't see how to achieve the same with sections.

**Comment by bernt-matthias** [comment]
Superseded by https://github.com/galaxyproject/galaxy/issues/13931
