### ISSUE TITLE
embed dataset in pages : user error 

### ISSUE THREAD

**Issue by davidchristiany** [galaxyproject/galaxy#7178]
It is impossible to create a page with embed dataset if you don't have an admin account in galaxy 18.09. When you save the page you get the following error : 

![image](https://user-images.githubusercontent.com/39336353/50774510-e865f800-1293-11e9-989d-8ef4fb8f5b2c.png)

You can however save embed dataset without getting this error (history of embed dataset which got an error)

It seems to be link to the user metadata :
`if (item.user != trans.user) and (not item.importable) and (trans.user not in item.users_shared_with_dot_users):`
`AttributeError: 'HistoryDatasetAssociation' object has no attribute 'user'`

I am having this error on my own datasets (I tried with newly created dataset and newly created page)

I did not have this issue with the previous version of galaxy, it seems to be related to the 18.09 galaxy version.

**Comment by dannon** [comment]
@davidchristiany Thanks for reporting this, I'll take a look now.
