### ISSUE TITLE
after browser-back Galaxy loads plain welcome.html without panels

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#7194]
* visit usegalaxy.org
* click login or register
* click forgotten password
* click 'back' in browser
* log in
* you load `https://usegalaxy.org/static/welcome.html` without any panels

xref: https://github.com/galaxyproject/galaxy/issues/6853

**Comment by WilliamHolden** [comment]
Hey @martenson, Is this still an issue? Maybe I'm doing it wrong but I'm having trouble reproducing.

**Comment by martenson** [comment]
I think the login form has since been rewritten. Thanks for checking. Closing.
