### ISSUE TITLE
Workflows not available in workflow menu on 18.09

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#7212]
![image](https://user-images.githubusercontent.com/458683/51115958-9b3cd580-1801-11e9-988a-f6a741ea99c2.png)

It has `display: none`, for some reason. Screenshot from usegalaxy.org, applies to .eu as well.

**Steps to reproduce**

1. create a workflow with some tools.
2. Create a new workflow
3. Try to insert it.

cc @bgruening noticed by @wm75

**Comment by mvdbeek** [comment]
Is there something special in the steps to reproduce ?
I just did that on usegalaxy.org and it worked fine.

**Comment by mvdbeek** [comment]
1. Create a new workflow, I added the input dataset step and plotHeatmap.
2. Go back to workflow menu, create a new workflow
3. Insert workflow from step 1.

**Comment by mvdbeek** [comment]
There is a little delay though for the workflow links to appear ... is that maybe what you're seeing ?

**Comment by hexylena** [comment]
It was reported by @bebatut with firefox/mac, myself with firefox/linux. Works according to @wm75 in https://www.falkon.org/

**Comment by hexylena** [comment]
It is not a delay, they're loaded with the style `display:none`, as seen in the picture in the original issue. Here you can see the `wf a` which is my other workflow on .org

![image](https://user-images.githubusercontent.com/458683/51116414-f9b68380-1802-11e9-91e3-919d3cbb38c1.png)

**Comment by mvdbeek** [comment]
I see, I have the same issue with firefox, chrome and safari are fine.

**Comment by hexylena** [comment]
Seems to be back, not sure when this was fixed.
