### ISSUE TITLE
Issue with pinned-requirements.txt

### ISSUE THREAD

**Issue by yanglipmed** [galaxyproject/galaxy#7223]
I am trying install Galaxy into Bash on Windows 10, but got an alert:

Activating virtualenv at .venv
Requirement already satisfied: pip>=8.1 in ./.venv/lib/python2.7/site-packages (18.1)
Invalid requirement: 'lib/galaxy/dependencies/pinned-requirements.txt'
It looks like a path. It does exist.

How to solve it? I have install pip and virtualenv. Thanks

**Comment by nsoranzo** [comment]
Unfortunately Bash on Windows 10 is not a supported platform, but we can try to help you.
Galaxy dependencies are installed using the command:

```
pip -r requirements.txt --index-url https://wheels.galaxyproject.org/simple --extra-index-url https://pypi.python.org/simple
```

where `requirements.txt` is a symbolic link to `lib/galaxy/dependencies/pinned-requirements.txt`, which in turn is symbolic link to `lib/galaxy/dependencies/pipfiles/default/pinned-requirements.txt` .
I fear that the symbolic links are somehow messed up under Bash/Win10.

**Comment by hexylena** [comment]
Closed pending user response
