### ISSUE TITLE
Trackster Group/Filter errors

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy#7224]
Noticed when trying to understand the functionality and track down the undefined var here:  https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/viz/trackster/filters.js#L657

I need to dig more, but when trying to use groups to set up filters I ran into several errors, potentially related to the es6 rewrite and global elimination a while back.

**Comment by jennaj** [comment]
@dannon Here are the Trackster issues with details. I tried to cover what works and what does not, so the scope of the problem is clear with reproducible test cases. Is not server-specific -- exact same behavior at ORG & EU. Thanks!

https://github.com/galaxyproject/usegalaxy-playbook/issues/276
