### ISSUE TITLE
Dropping workflow files into the workflow list panel broken

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#7230]
Instead of uploading the workflow the browser displays the workflow content.
Probably same root cause as #7138 #7137.

**Comment by dannon** [comment]
I'm taking a deeper dive on this since it has popped up so many times; the culprit looks to be a conflict between jquery.event.drop and backbone event handling.  Working on a fix.

**Comment by mvdbeek** [comment]
Fixed by https://github.com/galaxyproject/galaxy/pull/7415
