### ISSUE TITLE
tool search results display inconsistently

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#7238]
two subsequent searches for `peakachu` on usegalaxy.eu yielded different results for me in firefox, the first does not show in client, the second does

there might be some interaction when search results omit the latest version

@erasche @nsoranzo

```json
["toolshed.g2.bx.psu.edu/repos/rnateam/peakachu/peakachu/0.1.0.1", "toolshed.g2.bx.psu.edu/repos/rnateam/peakachu/peakachu/0.1.0.0"]
```

```json
["toolshed.g2.bx.psu.edu/repos/rnateam/peakachu/peakachu/0.1.0.1", "toolshed.g2.bx.psu.edu/repos/rnateam/peakachu/peakachu/0.1.0.0", "toolshed.g2.bx.psu.edu/repos/rnateam/peakachu/peakachu/0.1.0.2"]
```

_Originally posted by @martenson in https://github.com/galaxyproject/galaxy/issue_comments#issuecomment-455598974_

**Comment by hexylena** [comment]
Reported by @Florian-H-Lab, also noticed by @wm75

**Comment by hexylena** [comment]
Could be due to multiple zerglings responding to requests. Closing until it's reported again.
