### ISSUE TITLE
After logging out, the "User" menu still displays email address, back button stalls and reveals last active history

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#7249]
The logout behavior has changed. **Should we change it back?** 

This changed in maybe release `18.05`? Tried to get used to it but think it is problematic. 

1. Is cumbersome to "click twice" for what used to be a single action (click home page, wait for reload, then access "login or register).
2. Users likely expect that "logging out" removes any personal info from being displayed further. Yet the GUI is exposing the logged-out-account's email address.

How to reproduce:

**Before**: after logging out, the prior user was completely anonymous in the GUI. The login or register menu was made available in the masthead, with no "User menu".

**Now**: after logging out, the prior user's email is still visible in the GUI under the "User" menu. Actions on history menu stall out, sometimes exposing the last history the prior user had loaded. One needs to click on the link to "go to the homepage" to completely reset the GUI. 

Screenshot for **Now**

<img width="958" alt="logout_gui" src="https://user-images.githubusercontent.com/8999735/51499514-70153180-1d7f-11e9-9c99-3b992d111b12.png">

**Comment by Nerdinacan** [comment]
Happy to take a peek!

**Comment by Nerdinacan** [comment]
This is ready to go, soon as we fix the problems with the current dev build I'll put up a PR.

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/issues/6853
https://github.com/galaxyproject/galaxy/issues/7194

**Comment by Nerdinacan** [comment]
Associated PR:
https://github.com/galaxyproject/galaxy/pull/7255

**Comment by dannon** [comment]
Fixed in #7255

**Comment by jennaj** [comment]
I don't think this is quite working as expected. I noticed this earlier, sorry didn't write back sooner!

Logout leaves the prior user's quota usage displayed, test with both admin and non-admin accounts at https://usegalaxy.org:

<img width="1145" alt="screen shot 2019-02-28 at 5 25 10 pm" src="https://user-images.githubusercontent.com/8999735/53609926-f0e4fb80-3b7d-11e9-813b-8453a2a7cd14.png">


I expected logout to take me all the way back here, without needing to click on anything else (how it used to work):

<img width="1010" alt="screen shot 2019-02-28 at 5 21 07 pm" src="https://user-images.githubusercontent.com/8999735/53609822-8df36480-3b7d-11e9-990c-dd1693ece709.png">

**Comment by jennaj** [comment]
Oh rats, and the user menu is still active, too, displays the prior email address associated with the "logged out" account. This will need some more tuning, hopefully for 19.05?

<img width="1240" alt="screen shot 2019-02-28 at 5 38 17 pm" src="https://user-images.githubusercontent.com/8999735/53610527-20950300-3b80-11e9-95fb-40d11257daba.png">

Clicking on Preferences does give a warning and finally redirects to clear home page:

<img width="669" alt="screen shot 2019-02-28 at 5 38 46 pm" src="https://user-images.githubusercontent.com/8999735/53610521-1c68e580-3b80-11e9-8a91-714ff9f70dab.png">

@Nerdinacan Did this work in the local you tested? I haven't tested in one yet.

**Comment by nsoranzo** [comment]
@jennaj The fix mentioned in https://github.com/galaxyproject/galaxy/issues/7249#issuecomment-457236610 is indeed only available in the `dev` branch (future 19.05).

**Comment by jennaj** [comment]
Ah -- ok -- thanks, that clears it up. I saw the PR was still in limbo but didn't dig deaper till saw this closed out. This should stay open until resolved please. 19.05 would be great :)

**Comment by jennaj** [comment]
Changed mind, we can close here, I've got this tracked to test when 19.05 is on public servers for final intergration testing.

**Comment by jennaj** [comment]
Issues again in `19.09`.

Now the tab logged out of works, but other tabs open to the server still show all the prior account data. Freezes up (at least at org). Should be a "global" log out, right? Used to be. New issue or keep it here. IMO we need to make sure this doesn't regress, ongoing.

ping @dannon @natefoo others.. not sure who would fix this. Or if we are really Ok with it being this way?

**Comment by jennaj** [comment]
Logout works at bit better now but is not quite a "full" log out yet. Some cached data remains. Intentional?

**Comment by dannon** [comment]
This should work better with the new changes to client bootstrapped data being cached.  Reopen if it's still an issue.
