### ISSUE TITLE
Tool installation breaks shed_tool_conf.xml

### ISSUE THREAD

**Issue by loraine-gueguen** [galaxyproject/galaxy#7250]
Each time a new tool or revision is installed through the toolshed, the shed_tool_conf.xml that is updated with the new tool / revision is broken because line breaks are added inside the tag values (see below) and the shed_tool_conf.xml is not loaded correctly when galaxy is restarted (see logs below). This can be corrected by removing the break lines.

This happens since we have updated Galaxy from 17.05 to 18.09
Do you have an idea why this is happening and what can be done to solve this problem ?

Extract of updated shed_tool_conf.xml:

>     <section id="fasta_fastq_manipulation" name="Fasta Fastq Manipulation" version="">
>         <tool file="toolshed.g2.bx.psu.edu/repos/peterjc/seq_filter_by_id/fb1313d79396/seq_filter_by_id/tools/seq_filter_by_id/seq_filter_by_id.xml" guid="toolshed.g2.bx.psu.edu/repos/peterjc/seq_filter_by_id/seq_filter_by_id/0.2.5">
>             <tool_shed>
>                 toolshed.g2.bx.psu.edu
>             </tool_shed>
>             <repository_name>
>                 seq_filter_by_id
>             </repository_name>
>             <repository_owner>
>                 peterjc
>             </repository_owner>
>             <installed_changeset_revision>
>                 fb1313d79396
>             </installed_changeset_revision>
>             <id>
>                 toolshed.g2.bx.psu.edu/repos/peterjc/seq_filter_by_id/seq_filter_by_id/0.2.5
>             </id>
>             <version>
>                 0.2.5
>             </version>
>         </tool>
>     </section>
> 

Extract of error logs when Galaxy is restarted:

> galaxy.tools.toolbox.base DEBUG 2019-01-21 21:37:22,733 [p:27522,w:0,m:0] [MainThread] Error while loading tool toolshed.g2.bx.psu.edu/repos/peterjc/seq_filter_by_id/fb1313d79396/seq_filter_by_id/tools/seq_filter_by_id/seq_filter_by_id.xml
> galaxy.tools.toolbox.base ERROR 2019-01-21 21:37:22,917 [p:27522,w:0,m:0] [MainThread] Error reading tool from path: toolshed.g2.bx.psu.edu/repos/peterjc/seq_filter_by_id/fb1313d79396/seq_filter_by_id/tools/seq_filter_by_id/seq_filter_by_id.xml
> Traceback (most recent call last):
>   File "/w/galaxy/galaxy3/galaxy/lib/galaxy/tools/toolbox/base.py", line 563, in _load_tool_tag_set
>     tool_shed_repository = self.get_tool_repository_from_xml_item(item, path)
>   File "/w/galaxy/galaxy3/galaxy/lib/galaxy/tools/toolbox/base.py", line 629, in get_tool_repository_from_xml_item
>     raise Exception(msg)
> Exception: Attempted to load tool shed tool, but the repository with name '
>                 seq_filter_by_id
>             ' from owner '
>                 peterjc
>             ' was not found in database
>

**Comment by mvdbeek** [comment]
Hi Loraine,

I'm not sure what could have caused this.
You could try removing all newlines (`sed -i.bak 's/\n//g' shed_tool_conf.xml`, or `sed -i.bak 's/\r//g' shed_tool_conf.xml` for carriage returns) and install a new tool.
Installing a tool will rewrite a properly formatted config file.

**Comment by mvdbeek** [comment]
It would also help if you could upload the whole broken file to https://gist.github.com/

**Comment by mvdbeek** [comment]
OK, it's not enough to just remove newlines.
https://github.com/galaxyproject/galaxy/pull/7252 should fix it for you.

**Comment by loraine-gueguen** [comment]
Thanks for the fix Marius!

**Comment by lecorguille** [comment]
Tested and approved! Thanks @mvdbeek 
But it remains the question: why are we the only one to complain about that?
Mysterious

**Comment by mvdbeek** [comment]
My best guess is some manual editing that left behind a non-unix line break, but hard to know for sure.
