### ISSUE TITLE
Workflow section missing in sidebar (when in the Workflow Editor)

### ISSUE THREAD

**Issue by mtekman** [galaxyproject/galaxy#7282]
Steps to reproduce:

1. Click on Workflow from main UI
1. Tick box "Show in tools panel" for any workflow 
1. Verify said workflow exists is now accessible in sidebar
1. Click on '+' to create new workflow
1. Check the sidebar → workflow section missing

**Comment by mvdbeek** [comment]
There's a chance I'm misunderstanding this, but the tool panel only displays tools in the workflow editor. All the workflow are listed under `Workflows` if you'd like to copy or include them into the workflow. This is independent of the "show in tool panel" functionality.

**Comment by mtekman** [comment]
My apologies, this seems to appear only in my local intstance

**Comment by hexylena** [comment]
@mvdbeek no, this is a duplicate of https://github.com/galaxyproject/galaxy/issues/7212 that I guess still isn't fixed. It isn't just your instance @mtekman it appears on usegalaxy.eu and .org

**Comment by mtekman** [comment]
Oh, right -- good

**Comment by mvdbeek** [comment]
Hmm, the description sounds distinct from #7212 but if it's the same issue we should close this and continue in #7212

**Comment by hexylena** [comment]
It is a duplicate of #7212, so closing for that reason, sorry.

**Comment by hexylena** [comment]
The description sounds slightly distinct but I think step 1/2 is not relevant for reproduction?

**Comment by mtekman** [comment]
The ticking the "show in tool panel" step?

No, it isn't, I was just showing that I had at least one workflow that is accessible from the sidebar
