### ISSUE TITLE
Tool tip on hover to report why a tool link can't be made

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#7283]
In the workflow editor it would be great if while dragging a new connection over a input, a tool tip popped up reporting why the connection can't be made.

Currently I have to guess and check why the connection is failing. 
I have seen connections fail due to a constraint on the output being a single file rather than the multifile connection. Breaking the output link, setting the input and then remaking the output was the work around but it took some time to figure out why the input connection couldn't be made.

There is also the issue of related formats inexplicably not linking with no debug output as to why.

**Comment by dannon** [comment]
This was done in https://github.com/galaxyproject/galaxy/pull/7642
