### ISSUE TITLE
Related formats not allowing link in workflow

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#7284]
Linking the output of a tool in `newick` format to a tool expecting `nhx` should be allowed but fails.

```xml
<datatype extension="nhx" type="galaxy.datatypes.data:Newick" subclass="true" display_in_upload="true"/>
<datatype extension="newick" type="galaxy.datatypes.data:Newick" display_in_upload="true"/>
```
is this because the `subclass="true"` is missing from `newick`?

**Comment by nsoranzo** [comment]
Unfortunately they cannot be both `subclass` at the same time. `nhx` being a subclass of `newick` means that a `nhx` dataset will be accepted by tools requiring `newick`, but not viceversa.
Your best bet is to update the tool expecting `nhx` to use `newick` instead.

**Comment by innovate-invent** [comment]
The typing system should take a list of extensions if this is the case. nhx and newick are just aliases of each other AFAIK.
For now I changed the output of the tool to nhx

**Comment by nsoranzo** [comment]
nhx and newick are not aliases, nhx is an extension of newick (nhx = New Hampshire eXtended), see https://www.cs.cmu.edu/~aiton/split/Manual-2.6.master014.html

**Comment by innovate-invent** [comment]
Oh! I should have looked closer at it. Thanks

**Comment by innovate-invent** [comment]
If nhx is an extension of newick, would that mean a tool accepting nhx should also accept newick?

**Comment by nsoranzo** [comment]
I think it's the other way around: a tool accepting `newick` should be able to ignore the extra info contained in `nhx` files, while a tool accepting `nhx` may fail on `newick` files because they miss required fields, but I'm speculating.

**Comment by hexylena** [comment]
I think it's been cleared up?
