### ISSUE TITLE
metadata setting problems

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#7312]
I experienced unusual memory consumption of my dev Galaxy. At the same time the log has lines as:

```
galaxy.jobs DEBUG 2019-02-05 14:26:33,618 [p:9826,w:0,m:1] [UnivaJobRunner.work_thread-1] job 8631 ended (finish() executed in (7202963.348 ms))
galaxy.model.custom_types WARNING 2019-02-05 14:26:34,960 [p:9826,w:0,m:1] [UnivaJobRunner.work_thread-2] Refusing to bind metadata key reference_names due to size (39710561)
galaxy.tools.parameters.output_collect DEBUG 2019-02-05 14:26:35,476 [p:9826,w:0,m:1] [UnivaJobRunner.work_thread-2] (8630) Created dynamic collection dataset for path [/work/songalax/galaxy-dev/database/jobs_directory/008/8630/working/stacks_outputs/bl.9_7.matches.bam] with element identifier [bl.9_7.matches] for output [bams] (8532.979 ms)
```

Besides the memory issue there are two odd things: 
- set_meta should run with the job
- the run time (2h for setting metadata of a single bam file out of approx 400)

Might be a Galaxy / configuration / tool issue.

Running this tool https://testtoolshed.g2.bx.psu.edu/view/matthias/stacks2_tsv2bam/56eb0bc12179

Discussion started here: https://github.com/pysam-developers/pysam/issues/763

Maybe related to the memory and run time problem: https://github.com/pysam-developers/pysam/issues/762#issuecomment-460952096

Just discovered some messages of interest in my logs (maybe unrelated): 

```
galaxy.web.stack DEBUG 2019-02-03 03:49:39,240 [p:30298,w:0,m:1] [MainThread] JobConfiguration: No job handler assignment methods were configured but a uWSGI farm named 'job-handlers' exists, automatically enabling the 'uwsgi-mule-message' assignment method
galaxy.web.stack DEBUG 2019-02-03 03:49:39,240 [p:30298,w:0,m:1] [MainThread] JobConfiguration: Removed 'db-self' from handler assignment methods due to use of mules
galaxy.web.stack DEBUG 2019-02-03 03:49:39,240 [p:30298,w:0,m:1] [MainThread] JobConfiguration: handler assignment methods updated to: uwsgi-mule-message
galaxy.util.handlers INFO 2019-02-03 03:49:39,241 [p:30298,w:0,m:1] [MainThread] JobConfiguration: No job handler assignment method is set, defaulting to 'uwsgi-mule-message', set the `assign_with` attribute on <handlers> to override the default
galaxy.jobs INFO 2019-02-03 03:49:39,241 [p:30298,w:0,m:1] [MainThread] Job handler assignment methods set to: uwsgi-mule-message
```

ping @mvdbeek

**Comment by mvdbeek** [comment]
OK, so this is the dynamic job output discovery, which unders some circumstances can be a) extremely slow and b) run on the handler. I think the 2h runtime might indicate a problem copying files back and forth. I know @jmchilton has done some work on optimizing this in dev, but as far as I can tell we're still copying the file to the object store in https://github.com/galaxyproject/galaxy/blob/681225bc9cb0f25c5e717658f37a4302c1c4166a/lib/galaxy/tools/parameters/output_collect.py#L503 which happens on the handler. If that's being done for many files at once it can be a big bottleneck.

**Comment by bernt-matthias** [comment]
Sounds reasonable. Copying can be quite slow on our cluster when the file system load is high. Typically 4min are needed for one of the BAM files. 

Remains the unusual high memory consumption. I might ask our users to run the job again in order to see if its reproducible. Any suggestion how I could debug this in more detail?

**Comment by mvdbeek** [comment]
I think this would probably require some larger refactoring on the Galaxy side to make this more efficient. I think in rough terms the idea is that jobs would request a temporary directory from the object store, and during the output discovery phase you'd just need to move outputs to the correct location (if the object store backend supports that).  I had a look at the tool, but I'm not sure if this is possible: If you know that you generate a static number of outputs you could just copy or move them to the correct output element in the too wrapper, that might be more efficient.

**Comment by bernt-matthias** [comment]
Unfortunately, the number of output bam files depends on the input.

**Comment by mvdbeek** [comment]
On our production instance I'm using https://github.com/mvdbeek/galaxy/commit/07416612220a74fe68fb6d855303eedb58346f42 that is not part of Galaxy, maybe you could check if that works for you and improves the situation ?

**Comment by mvdbeek** [comment]
This would of course only help if a move from the job_working_directory to the object_store is more lightweight than a copy -- which it is for us.

**Comment by bernt-matthias** [comment]
Thanks for the tip. I will check if this is the case also for our file system. And test eventually.

**Comment by martenson** [comment]
this issue is likely outdated but please feel free to reopen of I am wrong
