### ISSUE TITLE
"Repository Actions" action menu exploded

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#7314]
Branch affected: dev (future 19.05), 19.01 works fine

How to reproduce: in the admin interface, click on "Manage tools" and then on one repository name; the "Repository Actions" menu on the top right is exploded in multiple buttons

![screenshot_2019-02-06 galaxy installed tool shed repositories](https://user-images.githubusercontent.com/4924623/52364488-3d389200-2a3d-11e9-98ee-2637e7253439.png)

`git bisect` says the cause is commit 21b2dd8 .

**Comment by dannon** [comment]
@nsoranzo Thanks for making the issue, I'll get a fix out shortly.

**Comment by bernt-matthias** [comment]
For me also the "Repository actions" button has no effect at the moment. Might be unrelated.

**Comment by davebx** [comment]
@bernt-matthias that button is supposed to explode the menu because the menu should be not exploded.

**Comment by martenson** [comment]
reopening with one more instance of the same problem

![galaxy](https://user-images.githubusercontent.com/1814954/52452318-91f90d00-2b10-11e9-8b7d-76a95dbea5d8.png)

**Comment by dannon** [comment]
Interesting, that should have been covered.  I'll take a look, may use a different setup, thanks @martenson.

After pulling dev and making client, I'm not seeing what's in your screenshot on the "Install new tools" page, where I assumed this was.  Where'd you see this happen?

**Comment by martenson** [comment]
@dannon same here, I thought I have latest but didn't😳

**Comment by nsoranzo** [comment]
I see them for half a second, then they disappear. The menu works fine.

**Comment by dannon** [comment]
@martenson No worries!

@nsoranzo Yeah, the function executes slightly later than it used to, but we'll replace this with standard bs4-style buttons in a second pass, so the 'flash' is temporary.

**Comment by nsoranzo** [comment]
Cool, thanks! I just mentioned it because I saw no flashing on the fixed "Repository Actions" menu.
