### ISSUE TITLE
Cannot uninstall "certifi"

### ISSUE THREAD

**Issue by cizydorczyk** [galaxyproject/galaxy#7324]
Hi,

I'm trying to install a local instance of Galaxy (first time) and when I run run.sh, I get the following error:

`Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

Note that it does find a previous installation of "certifi":

`Found existing installation: certifi 2018.11.29`

I am trying to install on Ubuntu 18.04 with conda version 4.6.2. It creates the _galaxy_YY.MM conda environment just fine but fails when it gets to this part.

Would changing the certifi version in the requirements.txt file work? I noticed it is 2018.8.24...This issue appears somewhat similar to #6973 

Any help in resolving this issue is much appreciated.

Thank you,
Conrad Izydorczyk

**Comment by mvdbeek** [comment]
Sorry for the late reply, please have a look at https://docs.galaxyproject.org/en/master/admin/framework_dependencies.html?highlight=framework%20dependencies#conda, and I'd recommend updating to the recently released 19.01 version.

**Comment by pcm32** [comment]
This comes up if you follow the steps mentioned in the doc for a fresh download of galaxy-18.05 from the release page (using macOS and conda):

```
  Found existing installation: certifi 2018.11.29
Cannot uninstall 'certifi'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by pcm32** [comment]
This also comes up when trying to install a fresh download of galaxy-18.09 from the release page.
