### ISSUE TITLE
Collection weirdness - duplicating collection inputs when creating list?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#7327]
Steps to reproduce:

- Upload 3 datasets (does not matter what, used a/b/c)
- multi-select datasets
- create list from datasets, select all
- check hide original datasets
- create collection

The outcome is that there are multiple hidden datasets, all duplicates of the input, every time you create a collection

![image](https://user-images.githubusercontent.com/458683/52445335-b78f1200-2b22-11e9-88cb-ce8a902f88fc.png)

**Comment by hexylena** [comment]
Example history on .org, https://usegalaxy.org/u/helena-rasche/h/unnamed-history applies to 18.09+

**Comment by mvdbeek** [comment]
Yeah, as long as we want people to be able to unhide datasets of collections we will have this situation.  I don't think there's an easy way around it. I'd argue that this is nice, it means you can delete a collection including its datasets without unknowingly deleting the members of another collection. In the same way duplicating the HDA means that we are, in theory, free to change metadata and/or datatype without affecting other collections.

**Comment by mvdbeek** [comment]
Can we close this ?

**Comment by hexylena** [comment]
~~But why are there 2x the number of input datasets created as hidden elements? I'd understand if it was 3, but 6 is surprising~~

Ok, it creates hidden duplicates of the originals, then hides originals. Still strange in the HID but OK
