### ISSUE TITLE
create atomic Jenkins tasks for the Galaxy test suite

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#733]
We have https://jenkins.galaxyproject.org now and should make a use of it.

I started to work on a few tasks (TS func tests, devteam&iuc planemo shed_diff) but could definitely use help as we want to cover as much as possible.

Right now all Jenkins users have permissions to modify all tasks so don't be afraid to touch/copy things and build upon.
If you do not have one yet please create an account at Jenkins and let me know that you did so I can give you permissions.
## Docker Tasks
- [X] ~~Register a Dockerhub account for the galaxy project~~(https://hub.docker.com/u/galaxyprojectdotorg/ - @bgruening and @jmchilton have password - same as planemo and toolshed).
- [x] Register the testing container in Dockerhub. Tag a release of it for testing.
  ## Testing Tasks
- [X] ~~Run Tool Shed functional tests.~~
- [x] Run API tests in postgres and mysql containers.
- [x] Run tool framework tests in postgres container (`run_tests.sh --framework`). 
- [x] Run full casperjs test suite on jenkins server. (`run_tests.sh --casperjs`).
- [x] Add --xunit_report_file option to tool shed test entrypoint (works for Galaxy ones currently).
- [x] Switch to using the `--xunit_report_file` for Jenkins to tracks tests over time.
- [ ] Document important tests being run in `test/` somewhere, including location of ansible recipe for Ansible server.
## Planemo Tasks
- [x] shed_diff devteam vs MTS
- [x] shed_diff iuc vs MTS

**Comment by martenson** [comment]
Right now there are bunch of failing tests for `$ ./run_tests.sh -toolshed` report visible here
https://jenkins.galaxyproject.org/job/TS-functional-tests/TS_funtional_tests/

Would be cool to track down why are these failing on the machine when they run fine localy for at least few of us (me, Nicola, John)

**Comment by hexylena** [comment]
@martenson, if you'd like to delegate any of these to me, please let me know :)

**Comment by martenson** [comment]
@erasche If you would like to contribute to any of these, please go ahead. :)

**Comment by jmchilton** [comment]
@erasche Yes, what @martenson said :).

**Comment by hexylena** [comment]
Okay, just didn't want to get in the way of anyone's work!

**Comment by jmchilton** [comment]
Basically all of it should be running in Docker containers I think, this will make the tests perfectly portable and make it easier to debug problems encountered on jenkins locally. I've assigned @natefoo this task (https://github.com/galaxyproject/infrastructure-playbook/issues/3) - if someone else has privileges to do it though that would be awesome too.

**Comment by hexylena** [comment]
Yep, +1 for docker containers. Should be easy enough to do that in a matrix build, spin up a container, use some bash fu to construct a DBURI, and run tests.

**Comment by jmchilton** [comment]
The DBURI's are provided by the containers actually - see https://github.com/galaxyproject/galaxy/tree/dev/test/docker.

So what I imagine is the tests themselves are very close to the code, the most transparent place for them to be. So for instance each jenkins command block would just be one script.
- `.ci/scripts/toolshed_functional.sh`,
- `.ci/scripts/api_functional_postgres.sh`,
- `.ci/scripts/api_functional_mysql.sh`,
- `.ci/scripts/framework_functional.sh`

And these would just connect the jenkins environment to various `./run_tests.sh` calls. It should be pretty transparent how to get `run_tests.sh` to execute each of these tests in a Docker container on a local laptop.

**Comment by hexylena** [comment]
@jmchilton, OH, running tests inside of docker containers. Yeah, brilliant. I was mostly thinking running outside of the container because I'm used to treating the database as a matrix axis, rather than parts of a single set of tests in Jenkins.

**Comment by jmchilton** [comment]
@erasche Lots of ways to dice things up, and it could well make sense to do things with arguments and matrix style builds - but I feel like we should start with the a small number of really smart testing tasks with hyper concrete purposes. We tested too much stuff previously, a lot of it was duplicated stuff, and all the red was a turn off I think.

**Comment by hexylena** [comment]
@jmchilton makes sense. Definitely proven with the linting being done in incremental steps, people took that up quite nicely. I'll try and get some jenkins jobs built after work today.

**Comment by martenson** [comment]
@bgruening @jmchilton we already have https://hub.docker.com/u/galaxy/ registered; we do not have to fallback on galaxyprojectdotorg

**Comment by bgruening** [comment]
@martenson awesome!

**Comment by jmchilton** [comment]
Working on a Dockerhub build for the Galaxy testing image @ https://hub.docker.com/r/galaxy/testing-base/.

**Comment by martenson** [comment]
What are we missing here? Should I set up something for Pulsar @jmchilton ?

**Comment by jmchilton** [comment]
@martenson I think we disagree about this, but I'd like to have jenkins-specific wrappers around run_tests.sh so that the jenkins command is literally just calling the script.

```
./ci/jenkins_toolshed.sh
./ci/jenkins_api.sh
./ci/jenkins_framework.sh
./ci/jenkins_casperjs.sh
```

This would allow others to setup the same Jenkins job trivially and would serve as open source documentation about what jenkins is doing.

The ease of running CI tests against forks is a huge advantage of Travis or Jenkins, but I think we could close the gap by trying to make Jenkins more transparent.

I'll remove the pulsar task though.

**Comment by martenson** [comment]
@jmchilton 
Jenkins is now running this:

```
find lib -iname '*pyc' -exec rm -rf {} \;
./run_tests.sh --dockerize --db postgres --external_tmp --xunit_report_file xunit-${BUILD_NUMBER}.xml -api
```

and you want it to run this?

```
./run_tests.sh --cleanPYC --dockerize --db postgres --external_tmp --xunit_report_file xunit-${BUILD_NUMBER}.xml -api
```

or am I missing sth?

**Comment by jmchilton** [comment]
No I want to create a script called `.ci/jenkins_api_tests.sh` that looks like:

```
#!/bin/bash
./run_tests.sh --cleanPYC --dockerize --db postgres --external_tmp --xunit_report_file xunit-${BUILD_NUMBER:-api}.xml -api
```

Because it serves as documentation for what Jenkins is running and makes it easier to replicate that exact command locally.

**Comment by martenson** [comment]
gotcha

**Comment by jmchilton** [comment]
Implemented in #3239

**Comment by martenson** [comment]
seems unusual to close issue before the PR is merged

**Comment by jmchilton** [comment]
@martenson Better remedy that by merging the PR :stuck_out_tongue_closed_eyes:.
