### ISSUE TITLE
CORS blocking TTS access

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#7335]
so nobody can install tools from there

reported by @rdvelazquez

![galaxy___administration](https://user-images.githubusercontent.com/1814954/52452900-f74dfd80-2b12-11e9-9959-0767c5f77948.png)

**Comment by Nerdinacan** [comment]
Ahhh yeah. The old tool installer runs inside an iframe and the init buffer was being installed in window.top, which resulted in a CORS error. The beta installer should work, but I'll see what happens if I store that init buffer in the window instead.

**Comment by dannon** [comment]
Xref the previous fix for this: https://github.com/galaxyproject/galaxy/pull/7135

So the init buffer broke it again?

**Comment by Nerdinacan** [comment]
Last time it was the singleton I believe? This time it was the init buffer.

```
// initQueue.js
const queue = (window.top._initQueue = new BehaviorSubject([]));
```

**Comment by dannon** [comment]
@Nerdinacan Ahh, yeah, was the singleton.  Should we hang the initqueue off Galaxy instead of window, since we've already narrowed it to having a single Galaxy singleton?

**Comment by Nerdinacan** [comment]
@dannon Well the point of the init queue was to collect initializations before galaxy was built, right? I just stored it in window.

**Comment by dannon** [comment]
@Nerdinacan Yeah, chicken and egg I guess.  Was trying to trim a global, but it might not be worth the gymnastics.

**Comment by Nerdinacan** [comment]
@dannon I agree, it's a bit distasteful, but there's probably some kind of graph theory that proves that we need to have a global to aggregate global behavior, haha. 

I was talking to Jeremy about the tool servers, more generally. How hard would it be to just turn the tool repos into an API instead of a site hosting its own UI?

**Comment by dannon** [comment]
@Nerdinacan That's exactly what the beta installer is working towards.

**Comment by Nerdinacan** [comment]
@dannon Good news then!

**Comment by Nerdinacan** [comment]
@dannon You know what, the only point of the window storage of that buffer was to store initializations across iframes in the same domain. If we're not bothering with that any more, it can probably just be a closure variable inside the module. So at least it's not on window. Let me try that.

**Comment by dannon** [comment]
Ahh, good thinking, I like that!

**Comment by martenson** [comment]
the new installer uses only API, I will spend some time this release to polish it and we can roll it out as default in 19.05

**Comment by martenson** [comment]
The functionality seems restored after https://github.com/galaxyproject/galaxy/pull/7338

However I am still getting a CORS console error. This is on local `dev` galaxy and TTS.

![screenshot 2019-02-14 11 36 54](https://user-images.githubusercontent.com/1814954/52802080-30272e80-304d-11e9-992d-e76007864334.png)

**Comment by dannon** [comment]
@martenson Yeah, that's the other (harmless) issue I mentioned on IRC when we were reviewing this before.  I'll have a separate fix out for it shortly.
