### ISSUE TITLE
Upgrade node when the pinned version changes

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#7349]
Right now node is installed once via common_startup.sh, but is not upgraded when newer versions are pinned. I am not sure if nodeenv provides a mechanism to upgrade when using the virtualenv feature, but we'll need to figure out some way to do it if not. Currently older Galaxies upgrading to 19.01 will break, my solution for Test was to wipe the venv and recreate, but this isn't a good solution.

**Comment by nsoranzo** [comment]
I think that has been already implemented in commit bad8cffdbca2afbd2e5653041326abdfde3673bd , we just need to backport it to 19.01.

**Comment by nsoranzo** [comment]
Actually there is already a backport PR https://github.com/galaxyproject/galaxy/pull/7239 I approved 24 days ago, but it needs a second +1.

**Comment by dannon** [comment]
Yep.  Once that PR is merged, I'll merge it forward and will resolve the correct version pins.  The point is to do exactly what this issue requests.

**Comment by martenson** [comment]
I merged it, thanks. I also suspect our ansible playbooks do not use the common startup, but we should be able to use same logic there.

**Comment by natefoo** [comment]
Thanks! It does seem to install right overtop the old version just fine, and it doesn't look like any modules need to be cleaned up when changing versions.

@martenson the playbook installs a fixed version as well with `nodeenv -n <version> -p` so it should work as-is.

Closing this issue, thanks all!
