### ISSUE TITLE
Galaxy startup fail - installed os-service-types not working on MacOS 

### ISSUE THREAD

**Issue by amricaf** [galaxyproject/galaxy#7375]
Please help! After running sh run.sh packages install until it gets to os-service-types

After looking at the traceback I can see there's an issue with collecting the package:

![screen shot 2019-02-18 at 3 30 18 pm](https://user-images.githubusercontent.com/47731726/52928094-26296680-3392-11e9-937a-ce1a58d0725c.png)

Viewing my installed pip packages I can see I satisfy the requirements:

![screen shot 2019-02-18 at 3 31 17 pm](https://user-images.githubusercontent.com/47731726/52928113-42c59e80-3392-11e9-8b56-994bb846cf19.png)

Please help!

**Comment by nsoranzo** [comment]
@amricaf Thanks for your report! I think this is due to https://stackoverflow.com/questions/49768770/not-able-to-install-python-packages-ssl-tlsv1-alert-protocol-version

Can you try the following patch and see if it helps?

```patch
diff --git a/scripts/common_startup.sh b/scripts/common_startup.sh
index c9e24e1..640e0b3 100755
--- a/scripts/common_startup.sh
+++ b/scripts/common_startup.sh
@@ -121,7 +121,7 @@ if [ $SET_VENV -eq 1 -a $CREATE_VENV -eq 1 ]; then
                     echo "Creating Conda environment for Galaxy: $GALAXY_CONDA_ENV"
                     echo "To avoid this, use the --no-create-venv flag or set \$GALAXY_CONDA_ENV to an"
                     echo "existing environment before starting Galaxy."
-                    $CONDA_EXE create --yes --override-channels --channel conda-forge --channel defaults --name "$GALAXY_CONDA_ENV" 'python=2.7' 'pip>=9' 'virtualenv>=16'
+                    $CONDA_EXE create --yes --override-channels --channel conda-forge --channel defaults --name "$GALAXY_CONDA_ENV" 'python=2.7' 'pip>=9.0.3' 'virtualenv>=16'
                     unset __CONDA_INFO
                 fi
                 conda_activate
@@ -185,7 +185,7 @@ fi
 : ${PYPI_INDEX_URL:="https://pypi.python.org/simple"}
 : ${GALAXY_DEV_REQUIREMENTS:="./lib/galaxy/dependencies/dev-requirements.txt"}
 if [ $REPLACE_PIP -eq 1 ]; then
-    pip install 'pip>=8.1'
+    pip install 'pip>=9.0.3'
 fi
 
 requirement_args="-r requirements.txt"
```

I am not sure it will work, but you may get a different error, in which case can you post it here again?

**Comment by hexylena** [comment]
Closed pending user feedback. Hopefully Nicola's patch helped!
