### ISSUE TITLE
Galaxy update breaks link/path to some dataset files

### ISSUE THREAD

**Issue by AjitPS** [galaxyproject/galaxy#7377]
Hi, we have our own Galaxy prod. and test instances running, currently using `SGE DRM` but we are finally migrating (test one 1st) to `Slurm`.

We have noticed an **issue** that whenever we update Galaxy (most recent we did: `18.05`, but will do another update very soon) at our end (i.e., pull code from a newer release Git branch, restart galaxy, update the postgres DB), it `breaks the link`/path to some existing datasets that we then need to *re-link* as jobs start failing... wonder why this happens?

as we didn't change any config or .loc files, unless the postgres `db update` changes a flag, etc. on the path/link entry?

**Comment by mvdbeek** [comment]
Hi @AjitPS, can you explain what 

> `breaks the link`/path to some existing datasets that we then need to _re-link_ as jobs start failing

means ? What is the symptom ? In general Galaxy never utilises symlinks, but I'm not sure that's what you mean by link.

**Comment by AjitPS** [comment]
Hi Marius, our `admin` users occasionally upload data to Galaxy data libraries and do the `upload from path` (and check `link files instead of copying`), and when we update to a newer version of Galaxy, these datasets don't anymore (they can be seen in history with a warning of 1 or more attributes missing).

We fix this by re-doing the upload from path whenever this happens but that's quite cumbersome for admins... @mvdbeek

**Comment by AjitPS** [comment]
also, what's the **recommended way** to start|**stop** Galaxy. We used to do the `./run.sh start|stop|restart` way earlier but stopping Galaxy via this is **failing** now:
`Unsetting $PYTHONPATH`
`Activating virtualenv at .venv`
`Executing: .venv/bin/uwsgi   --stop "galaxy.pid"`
`signal_pidfile()/kill(): No such process [core/uwsgi.c line 1690]`
​​​​​​​
Not sure if we need to do this? https://galaxyproject.org/admin/get-galaxy/#shutting-down-galaxy

**Comment by mvdbeek** [comment]
One explanation could be that the initial upload didn't succeed in setting the metadata. This often happens when your datatype_conf.xml file doesn't match the Galaxy version you are using. What `link files instead of copying` does is store the primary file location as the path from which the file had been imported instead of copying this to the object store. So if you check the path for such a file and the file is still present at the location there was an issue at the time the file had been imported.

**Comment by AjitPS** [comment]
ok, will double-check; fyi @William-Brown ... but it does seem to happen with most `upload from path` datasets

**Comment by hexylena** [comment]
Closed pending user feedback
