### ISSUE TITLE
some static resources loaded from wrong path on Galaxy prefix-served installation

### ISSUE THREAD

**Issue by lcodo** [galaxyproject/galaxy#7383]
When configuring Galaxy behind a proxy with a prefix set as defined in #7378, the server works, yet some of the static resources are not found (branch [release_19.01](https://github.com/galaxyproject/galaxy/tree/release_19.01)).
The browser console error is the next:
![image](https://user-images.githubusercontent.com/20204636/52968799-a4940180-33ae-11e9-91a2-4fa9871ff59f.png)

How could I fix it?

**Comment by dannon** [comment]
Thanks for making this issue, I'll take a look at what's going on here with FontAwesome.

**Comment by dannon** [comment]
This is fixed in fixed in #7481
