### ISSUE TITLE
Prevent concurrent access to some ``ToolCache`` class attributes 

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#7444]
Both `cleanup()` and `cache_tool()` methods of `ToolCache` access the following class attributes when a tool is reloaded:

- `_hash_by_tool_paths`
- `_mod_time_by_path`
- `_new_tool_ids`
- `_tools_by_path`
- `_tool_paths_by_id`

This causes the failure of unit test `ToolBoxTestCase.test_tool_reload_for_broken_tool`, see e.g.: https://travis-ci.org/galaxyproject/galaxy/jobs/476364519

**Comment by martenson** [comment]
I still see the failures e.g. https://circleci.com/gh/galaxyproject/galaxy/2002 which is on a PR from today: https://github.com/galaxyproject/galaxy/pull/7515

**Comment by mvdbeek** [comment]
Yeah, it's still not quite right. I will add some more logging in the tests.

**Comment by martenson** [comment]
@mvdbeek @nsoranzo thank you both very much for looking into this!
