### ISSUE TITLE
v19.01: Interactive Tours dialogs misplaced

### ISSUE THREAD

**Issue by mmiladi** [galaxyproject/galaxy#7456]
Hello,

A subset of dialog windows of the interactive tours are slightly misplaced (pinned to very top or very bottom of the screen) once opened in server version 19.01. Probably it's expected, since the UI seems to be changed quite a lot. Still it would be nice to have an automatic solution for this subsets.

![screenshot from 2019-03-04 13-20-38](https://user-images.githubusercontent.com/6370737/53733146-57209580-3e80-11e9-949f-7a5f5e157e65.png)

**Comment by dannon** [comment]
Thanks for this report, I'll take a look @mmiladi

**Comment by mblue9** [comment]
Just to add here it has been reported that during many of the tours, the pop-ups appear directly covering the history, making it difficult to implement the instructions in the pop-up.

**Comment by martenson** [comment]
All of the [three tours on Main](https://usegalaxy.org/tours) are unable to open tool panel (and subsequently navigate the UI I think) thus cannot be finished successfully.
