### ISSUE TITLE
please review your workflow in 19.01

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#7469]
I fail to run a really simple workflow on 19.01 (Blast XML to Tabular)
Nothing happens in history...
Error in the log is:
> MessageException: Error due to input mapping of 'NCBI BLAST+ blastn' in 'db_opts|histdb'.  A common cause of this is conditional outputs that cannot be determined until runtime, please review your workflow.

I've tried on usegalaxy.org, you can find the WF here:
[https://usegalaxy.org/u/fredbga/w/blast](url)
Nothing happens, I think that the problem is the same.

Is this related to #7454 and its solution #7458 ?
Thank you.

**Comment by mvdbeek** [comment]
Yes, histdb is a hidden parameter.

**Comment by FredericBGA** [comment]
@mvdbeek it works now after fetch and merge! Thank you.
