### ISSUE TITLE
Workflow collection operation "Build list": no hide; no delete intermediate data

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#7473]
Tool: Build List from one or more datasets (Galaxy Version 1.0.0)

At least two problems, might be related:

1. The tool job itself ends up in the history output -- not following the hidden/show toggle or the post job action "delete intermediate datasets".
1. The datasets the tool uses as inputs are copied back into the same history and are not hidden either. 

History: https://usegalaxy.org:/u/jen/h/test-buildlist-wf-dup-data

Workflow:  https://usegalaxy.org/u/jen/w/testbuildlist

ping @dannon @jmchilton

**Comment by jennaj** [comment]
Other collection operation tools are presenting with the same behavior (do not hide): Merge collections, Relabel collections

These all seem to be "repackaging" other collections/datasets already in the history. Maybe that is a clue?

**Comment by garethp94** [comment]
I am also having this issue

**Comment by CatherineMcBride1** [comment]
Same here.

**Comment by dannon** [comment]
Thanks for the extra info on this one @jennaj.  Looks like I need to look into how collection operations execute and see how to best link in the existing post job actions.

**Comment by mvdbeek** [comment]
I was going to work on https://github.com/galaxyproject/galaxy/issues/3947, which is sort-of related ... while I'm there I could also take a look at this.

**Comment by dannon** [comment]
@mvdbeek Awesome, all you, thanks!

**Comment by RachelleIrwin** [comment]
I am also experiencing this problem!

**Comment by mvdbeek** [comment]
Keeping it open till the backport is in.
