### ISSUE TITLE
resolve visualization dependencies on the fly

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#7482]
using npm to prevent including/shipping static

cc @dannon 

xref: https://github.com/galaxyproject/galaxy/pull/6484

**Comment by dannon** [comment]
@martenson Thanks for making a handle for this!

**Comment by martenson** [comment]
pushing to 19.09 but please feel free to correct me

**Comment by dannon** [comment]
No, that's fine.  When this rolls out I want to have converted most of our built-in visualizations and pushed packages out for use, with testing, 19.09 is a much safer target.

**Comment by mvdbeek** [comment]
I think this is done now, and a tutorial is available at https://training.galaxyproject.org/training-material/topics/dev/tutorials/visualization-charts/tutorial.html

**Comment by dannon** [comment]
@mvdbeek Yep, I did this, we just forgot to close the issue looks like.
