### ISSUE TITLE
Automatically migrate database when running with plain run.sh

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#7488]
Enhancement idea from @joachimwolff, could be nice if the `manage_db.sh upgrade` was run automatically. Especially for really simple developer setups, it would be one less thing for users to do.

**Comment by nsoranzo** [comment]
I think the idea was to push people to do a database backup before executing `manage_db.sh upgrade` . I'd suggest a `galaxy.yml` config option defaulting to `false`.

**Comment by jmchilton** [comment]
+1 to @nsoranzo comment and the config option is already available (database_auto_migrate).
