### ISSUE TITLE
purge of history deletes dataset collection even if it has been copied 

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#7493]
If you copy a collection from one history to another (in the multiple history view) and then purge the collection from which the collection was originated, the datasets in the copied collection show up as purged. This is surprising behaviour, something @jennaj noted in #5402. Personally I expected a kind of "reference counting" semantics where the datasets would only be purged if there were no more collections referencing them.

**Comment by jennaj** [comment]
This happens also if someone imports a history, then the original owner purges. 

Since the data "counts" toward quota of the new owner, seems the data should stay intact until deleted by that new owner. Meaning, dataset state should not be dependent on whoever shared it originally.
