### ISSUE TITLE
Adding "reference genome" as parameter type of input parameters

### ISSUE THREAD

**Issue by sveinugu** [galaxyproject/galaxy#7496]
would be extremely useful!

**Comment by mvdbeek** [comment]
Starting with release 20.01 you can connect text parameters to select options, so this should be possible now.

**Comment by innovate-invent** [comment]
I would say this is not done. The input needs a way to reference the genomes list, including custom builds.

**Comment by sveinugu** [comment]
> I would say this is not done. The input needs a way to reference the genomes list, including custom builds.

As the original issue creator, I agree. You still have to know exactly what the dbkey of the genome is, which is a hassle to users. A real pulldown list of genomes, and yes, including custom builds, would really improve usability of workflows.

@mvdbeek ?

**Comment by mvdbeek** [comment]
You may not have tried this recently ?

<img width="355" alt="Screenshot 2020-12-10 at 19 11 31" src="https://user-images.githubusercontent.com/6804901/101812394-93842980-3b1b-11eb-86a8-48144a91f51d.png">
<img width="1284" alt="Screenshot 2020-12-10 at 19 11 40" src="https://user-images.githubusercontent.com/6804901/101812401-95e68380-3b1b-11eb-94cc-0c87f14272cf.png">

**Comment by sveinugu** [comment]
Hehe! Nope. 2020.09?

Looks awesome! 

I was going to write: "given there has not been any recent developments I am not aware of". I remember it was not implemented when this issue was closed, so I did a 2+2=5 without checking. I think I misunderstood @innovate-invent.

**Comment by innovate-invent** [comment]
This doesn't work if the input is connected to a tool expecting a selection and a tool with a text input.

**Comment by mvdbeek** [comment]
It really should though, I'll check tomorrow

**Comment by FredericBGA** [comment]
Hi,
I guess this is related to the genome build. Can we change this and set a .loc file?

**Comment by innovate-invent** [comment]
@mvdbeek any luck?
