### ISSUE TITLE
Trackster: Chromosome navigation and zoom in/out are hidden with release_19.01 and dev branches

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/galaxy#7501]
This is a screen shot from usegalaxy.org with dm6 as dbkey and a gtf obtained from UCSC table. These settings in release_18.09 allow displaying the navigation and zoom bar.

The issue may be related to #946

<img width="977" alt="Capture d’écran 2019-03-10 à 15 38 09" src="https://user-images.githubusercontent.com/11705625/54093032-5feafd00-4393-11e9-93e7-7a69fcd15e88.png">

**Comment by drosofff** [comment]
Hellooooo...
Is there anybody using trackster in Galaxy, actually ? ;-)

**Comment by bgruening** [comment]
Urgs, this looks like a client side thing that was lost during the CSS migration. It looks like an upstream bug.

ping @MoHeydarian

**Comment by dannon** [comment]
Thanks for the bump on the issue, I'll take a quick look now.

Yeah, I see what's going on.  The controls are there, it's just a styling issue with them being behind other elements.  Should have a fix shortly, hopefully.

**Comment by dannon** [comment]
@drosofff Ok, sorry for the delay here.  https://github.com/galaxyproject/galaxy/pull/7845 should fix the problem.
