### ISSUE TITLE
RData file gets recognized as a "gzipped file" on upload

### ISSUE THREAD

**Issue by nturaga** [galaxyproject/galaxy#753]
<img width="246" alt="screen shot 2015-09-18 at 1 04 09 pm" src="https://cloud.githubusercontent.com/assets/2746443/9965690/d2be6a0a-5e05-11e5-804c-e8db8cf08631.png">

**Comment by nturaga** [comment]
Identified which commits the problem occurs, but still no idea what is causing it as the commits have nothing to do with the datatypes.

Good commit: 3fae23368b85682c99b82a855c8ddf0d28238e7b (August 7th)

Bad commit: 94676038ec6a6f4396e331e7c374fc40087b1c0e (August 8th)

I'm lost on this one. If someone wants to scroll the commits on github then use 
https://github.com/galaxyproject/galaxy/commits/dev?page=16

**Comment by dannon** [comment]
It was https://github.com/galaxyproject/galaxy/pull/567 where the detected datatype for this changed.  There's somewhere in the code still not using extension.lower for comparison, is my guess.  I'm digging.

**Comment by nturaga** [comment]
https://github.com/galaxyproject/galaxy/pull/774 Fixes the issue.

**Comment by martenson** [comment]
@nitesh1989 just a nitpick (sorry) - it might be useful to not close the issue before the PR is merged in order to avoid async

**Comment by nturaga** [comment]
@martenson No worries, I just thought that since the issue was resolved it would make sense to close it. But i'll keep it in mind for the next time.

**Comment by dannon** [comment]
This makes it easy:
https://github.com/blog/1506-closing-issues-via-pull-requests  (the pull
request, when phrased correctly, will automatically close associated issues)
