### ISSUE TITLE
Workflow invocation doesn't wait for tool dependency autoinstall

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#7552]
Running a workflow doesn't wait for tool dependency automatic installs to complete before executing the tool.

**Comment by mvdbeek** [comment]
Nothing waits for auto-installations, auto-install is at the moment a feature I'd' only activate in dev instances. This is mostly a duplicate of https://github.com/galaxyproject/galaxy/issues/5655 which has more details.
