### ISSUE TITLE
wrapper based on https://singularity-hub.org/ hosted singularity images?

### ISSUE THREAD

**Issue by Chabrier** [galaxyproject/galaxy#7557]
Hi, just asking,

are galaxy features to write wrappers mature enough to enable the production of wrappers
that enable to use images hosted  https://singularity-hub.org/. I mean by using the <container>
tag?

best regards

**Comment by mvdbeek** [comment]
Two things here: Yes, Singularity support in Galaxy is mature enough for production use, and I use it in production. This is via pulling biocontainers from quay.io or building them on-the-fly using mulled_singularity. 
No, we don't support pulling from singularity hub right now. The Singularity registry is quite small at this point, so there is little interest in supporting this at the moment.

**Comment by Chabrier** [comment]
I a agree, there was 2 things merged.
I had guessed this,  that "pulling biocontainers from quay.io" was possible.
And so far i did not spent time to understand mulled_"things".
Anyway, thanks for the timeliness of the response.
