### ISSUE TITLE
Negative impact of new design on tool help

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#7559]
With the design changes in 19.01 tool help has become, IMO, harder to read in several places. In particular, I feel the following points are problematic:

- [x] The parameter help underneath dataset select boxes is not left-aligned with the rest of the tool interface, but indented to the level of the actual select box.

- [x] The start of Help sections is not clearly set apart from the rest of the tool interface anymore.
  With the new design the border around the tool form got removed, which now places the Help
  section right underneath the *Execute* button with hardly any spacing.

- [ ] Hyperlinks in the help section are no longer underlined and, thus, much harder to spot than previously.

- [x] The display of `class:: Warning mark` in Help sections has suffered: The class does no longer display an actual warning mark icon, but only puts the contained text into a highlighted box of a very light yellowish color that is, IMO, painful to the eye. Together, this turns Warning mark sections into what looks just like highlighted text.

Compare the old and new design in the following screenshots of the `gemini_load` tool, which illustrates all four issues:

Before | After
--- | ---
![gemini_load_old_design](https://user-images.githubusercontent.com/4742081/54595488-0342ae80-4a33-11e9-86a2-3fa951feb559.png) | ![gemini_load_new_design](https://user-images.githubusercontent.com/4742081/54595869-cdea9080-4a33-11e9-9921-0d12fc42d627.png)

**Comment by martenson** [comment]
Nicely summarized design feedback, thank you @wm75 !

**Comment by jxtx** [comment]
I believe hyperlinks was a deliberate change application wide? Definitely debatable.

All of these other issues I would consider bugs and need to be fixed. 

Thanks!

**Comment by guerler** [comment]
Thanks for the detailed description, I am looking into fixes.

**Comment by wm75** [comment]
Thanks for addressing things so quickly!
