### ISSUE TITLE
Idea: a tool xml that creates an iframe

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#7563]
I would like to submit an idea.
I want galaxy to become the main (and maybe the sole one) entry point of our bioinformatics plateforme.
But there are some tools (ie : primer3, https://primer3plus.com/cgi-bin/dev/primer3plus.cgi) that are not easily  "galaxy-able".

For those, I need links.

Rather than modifiying the `static/welcome.html`  in order to create these links (what I do right now), I would like to be able to integrate them in the tools panel. 
Not for being able to run some analysis but only in order to store their links and use the tool search bar.

Do you think it would be possible to design a kind of XML that will build a tool that acts as an iframe ?

With only a few things to configure : the tool URL and maybe two options in order to hide left and front panels.

**Comment by jxtx** [comment]
Have a look at data source tools (like UCSC Table Browser, etc). Even if there is not a way to send the data back to Galaxy you can still make a tool that will just link out to another website.

**Comment by FredericBGA** [comment]
Thank you James!

```
 <tool id="dev" name="dev" version="0.01" tool_type="data_source">
 <description>Test Primer3</description>
    <inputs action="https://primer3plus.com/cgi-bin/dev/primer3plus.cgi" check_values="false"  method="get" target="_blank">
    </inputs>
 </tool>
```
I did not manage to open in a new tab  even with `target="_blank"` but I think it will be enough for what I wanted.

It looks like that  the `command `tag is mandatory with at least some value: `<command>echo 1</command>`. Otherwise you won't be able to download the XML:
```
    tool_command = tool.command.strip().split()[0]
IndexError: list index out of range
```
