### ISSUE TITLE
One UI Notification Color Glitch Night Mode

### ISSUE THREAD

**Issue by FrAgMeNtS17** [galaxyproject/galaxy#7579]
At random intervals the lock screen will ignore night mode for notification and they will turn white when they should be black. Does not respond to toggle on and off. Must restart phone to restore lock screen night mode. They will go from white to black and back to white when the panel is pulled down and pushed back up.

**Comment by dannon** [comment]
@FrAgMeNtS17 I think you might have the wrong Galaxy project!

**Comment by hexylena** [comment]
@dannon we definitely need a night mode though ;)
