### ISSUE TITLE
Calls to /api/workflows/<workflow-id> lose step labels

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#7580]
When calling /api/workflows/<workflow-id> the returned json doesn't include the step label for non-input steps:

```
"1": {
      "tool_id": "testtoolshed.g2.bx.psu.edu/repos/ebi-gxa/scanpy_filter_cells/scanpy_filter_cells/1.3.2+galaxy0",
      "tool_version": "1.3.2+galaxy0",
      "id": 1,
      "input_steps": {
        "input_obj_file": {
          "step_output": "output",
          "source_step": 0
        }
      },
      "tool_inputs": {
        "subset": {
          "__class__": "RuntimeValue"
        },
        "__page__": null,
        "parameters": [
          {
            "__index__": 0,
            "max": "1000000000.0",
            "name": "n_genes",
            "min": "5000.0"
          }
        ],
        "input_format": "loom",
        "input_obj_file": {
          "__class__": "RuntimeValue"
        },
        "__rerun_remap_job_id__": null,
        "__job_resource": {
          "__current_case__": 0,
          "__job_resource__select": "no"
        },
        "output_format": "anndata"
      },
      "type": "tool",
      "annotation": null
    }
```

this is relevant for our ability to run workflows programatically having the freedom to inject parameters so that the are associated to a step label rather than a step number (that is prone to change easily on workflow updates). Is it possible to make the same API call with parameters to include the additional needed field or we need to edit the code that is responding to that API call? How do I find the code that responds to a particular API entrypoint? Thanks!

**Comment by mvdbeek** [comment]
The code is https://docs.galaxyproject.org/en/latest/_modules/galaxy/webapps/galaxy/api/workflows.html#WorkflowsAPIController.show, and the actual place where we add labels is in https://github.com/galaxyproject/galaxy/blob/4a308130b332f981708eb3ade61754a7755d3c1e/lib/galaxy/managers/workflows.py#L967

Showing the labels for input steps is on purpose at this endpoint though:
```
GET /api/workflows/{encoded_workflow_id}

Displays information needed to run a workflow from the command line.
```
We don't really consider changing parameters that are not marked as input or workflow parameters as something that you should change at runtime, because that can break in all sorts of unpredictable ways.

Still you can get the full representation by looking at 
`/api/workflows/<workflow_id>/download`.

**Comment by pcm32** [comment]
Thanks @mvdbeek. Is `/api/workflows/<workflow_id>/download` available through bioblend? maybe we could make it available through an additional option on show_workflow? Thanks

**Comment by pcm32** [comment]
Could you elaborate on this:
> because that can break in all sorts of unpredictable ways.

it seems to be the behaviour allowed through invoke_workflow on bioblend, where you provide a map of steps and parameters.

**Comment by pcm32** [comment]
Ok, I see it is exposed through `export_workflow`.

**Comment by pcm32** [comment]
When I call `/api/workflows/<workflow_id>/download` though it brings back the workflow with the undesired schema of having tool parameters as a single text line (as opposed to the proper parameters formatting provided by `/api/workflows/<workflow_id>`):


```
      },
      "tool_state": "{\"subset\": \"{\\\"__class__\\\": \\\"RuntimeValue\\\"}\", \"__page__\": null, \"parameters\": \"[{\\\"__index__\\\": 0, \\\"max\\\": \\\"1000000000.0\\\", \\\"min\\\": \\\"5000.0\\\", \\\"name\\\": \\\"n_genes\\\"}]\", \"input_format\": \"\\\"loom\\\"\", \"input_obj_file\": \"{\\\"__class__\\\": \\\"RuntimeValue\\\"}\", \"output_format\": \"\\\"anndata\\\"\", \"__job_resource\": \"{\\\"__current_case__\\\": 0, \\\"__job_resource__select\\\": \\\"no\\\"}\", \"__rerun_remap_job_id__\": null}",
      "id": 1,
```

as opposed to the nicer

```
"parameters": [
          {
            "__index__": 0,
            "max": "1000000000.0",
            "name": "n_genes",
            "min": "5000.0"
          }
        ]
```

it would be great if labels could be optionally made available on the output that includes the well formed json for parameters.

**Comment by jmchilton** [comment]
``/api/workflows/<workflow_id>/download`` is a much more useful endpoint. It should be available as ``export_workflow_dict``.
