### ISSUE TITLE
SecureShell or ParamikoShell destination with a containerized tool

### ISSUE THREAD

**Issue by Chabrier** [galaxyproject/galaxy#7600]
I'm trying to run with singularity on a remote host (either SecureShell or ParamikoShell) a wrapped tool.

it did specify a container dependency like this:

```
<requirements>
      		<container type="singularity">chabrier/explorefleche:latest</container>
</requirements>
```
I don't see differences when having a look inside the working folder generated,
like this
'grep -ri singularity  database/jobs_directory/000/41/*'

I believe i miss something or a configuration?
Or maybe it's not even possible to mix SecureShell or ParamikoShell with containerized tools?

**Comment by Chabrier** [comment]
issue not mature enough

**Comment by mvdbeek** [comment]
This works for me, did you enable singularity in your destination ?
For testing I'd start with `<container type="docker">chabrier/explorefleche:latest</container>` 
if `chabrier/explorefleche:latest` can be pulled from the docker registry.

**Comment by Chabrier** [comment]
I went farther..
but inside the tool i had to specify the image like this:

`<container type="singularity">docker://chabrier/explorefleche:latest</container>`

not very confident about this.

i did also enable singulartity on my job destination,(this is the point i was missing :))

**Comment by mvdbeek** [comment]
I'm assuming it works for you then ? Feel free to re-open if that' not the case.
