### ISSUE TITLE
Admin -> Manage Tools problems due to mixed contents

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#7610]
In The Admin -> Manage tools section some of the drop down actions seem dysfunctional due to mixed content (http/https). 

I noticed this when I tried to reactivate a uninstalled tool. The hover of the menu item shows: 

`https://galaxy.intranet.ufz.de/admin_toolshed/restore_repository?id=93d64bb15673369f`

If I click nothing happens, but the firefox debug console contains:

`Blocked loading mixed active content “http://galaxy.intranet.ufz.de/admin_toolshed/reselect_tool_panel_section?id=93d64bb15673369f”`

Setup: 
- release 19.01
- https via apache proxy

Everything works if I disable firefox's security checks.

**Comment by bernt-matthias** [comment]
Also happens in the "Repository Actions" menu (on the page for one tool) for some items:

- Get repository updates
- Reset Repository metadata

**Comment by dannon** [comment]
@bernt-matthias Thanks, I'll take a look!

**Comment by dannon** [comment]
@bernt-matthias I don't see an obvious new error here (yet) -- this is something that just happened with 19.01, or is it something that may have existed as an issue before but was not noticed?

**Comment by bernt-matthias** [comment]
I don't know.

**Comment by bernt-matthias** [comment]
Problem stiil exists in 19.05. Just have seen message: 

```
Blocked loading mixed active content “http://galaxy.intranet.ufz.de/static/welcome.html”
```

**Comment by bernt-matthias** [comment]
`Blocked loading mixed active content “http://galaxy.intranet.ufz.de/admin_toolshed/update_to_chang…revision=26693e21c3c8&latest_changeset_revision=3fc2116ac6d9” 2 repositories`

**Comment by bernt-matthias** [comment]
We just migrated from apache to nginx. Mixed content problems seem gone. So it was likely a configuration problem.

**Comment by dannon** [comment]
@bernt-matthias Thanks for following up, good to know the culprit.
