### ISSUE TITLE
User registration errors

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#7617]
Just observed (on dev) this error when a user tried to register (which should actually be forbidden on our server). 

```
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 283, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/controllers/user.py", line 114, in login
    return self.__validate_login(trans, payload, **kwd)
  File "lib/galaxy/webapps/galaxy/controllers/user.py", line 135, in __validate_login
    message, status, user, success = self.__autoregistration(trans, login, password, status, kwd)
  File "lib/galaxy/webapps/galaxy/controllers/user.py", line 90, in __autoregistration
    message, status, user, success = self.__register(trans, **kwd)
AttributeError: 'User' object has no attribute '_User__register'
```

Furthermore users seem to see the option to register even if `allow_user_creation: false` is set in my config.

**Comment by bernt-matthias** [comment]
When clicking in the User tab on the login screen the browser shows:

```
{
    "err_msg": "No session token set, denying request."
}
```

**Comment by dannon** [comment]
@bernt-matthias There was some refactoring of the underlying registration code somewhat recently; I'll take a look.

**Comment by dannon** [comment]
I just had a chance to take a deeper look and as I suspected we missed this in https://github.com/galaxyproject/galaxy/pull/6621, which overhauled the registration code; I'm working on a fix now.

**Comment by bernt-matthias** [comment]
Wonderful. Thanks for the update. Happy to test when ready.

**Comment by dannon** [comment]
@bernt-matthias ~I'm assuming you're using external user config -- can you let me know what that looks like so I can verify the fixes here?~

Edit: Nevermind!  I dug up your message on galaxy-dev and I see the context I needed now.  Thank you!

**Comment by dannon** [comment]
@bernt-matthias Does #7749 work for you?

**Comment by bernt-matthias** [comment]
Partial success. I don't see the error message in the logs anymore. But the user still does not get registered. The user sees the following error message: 

```
User registration is disabled. Please contact your local Galaxy administrator for an account. Contact: MYEMAIL
```

Might this be due to a misconfiguration? In auth.conf I have 

```
       <allow-register>Challenge</allow-register>
       <auto-register>True</auto-register>
```

and in galaxy.yml

```allow_user_creation: false```

**Comment by dannon** [comment]
@bernt-matthias I think I see what's going on.  I believe that's the correct configuration, I just need to add a bypass for the auto-registration in the newly refactored code that that PR is adjusting for.

**Comment by bernt-matthias** [comment]
@dannon Thanks for the info. Just tell me if I can test again.

**Comment by dannon** [comment]
@bernt-matthias Sure thing.  Can you actually do me a favor and verify that the auto-created users in the database have no password set (for users created when this was working, of course)?  That was the last thing I need to reintegrate, and then it's basically good to go.

**Comment by bernt-matthias** [comment]
Hi all my users have a password set (in the password column of the galaxy_user table). Looks like 

`PBKDF2$sha256$10000$HASH`

Wondering how this works if the password stored in LDAP changes (we force the users to change the password every year)?

**Comment by dannon** [comment]
@bernt-matthias That's exactly what I was wondering, too.  I thought external auth always set a null password, relying on the outside one, but that didn't seem to be what I was seeing consistently in the code.

**Comment by bernt-matthias** [comment]
I can verify that I still can login after at least 1 password changes. Maybe Galaxy needlessly stores the password in the DB and authenticates against the one it gets from LDAP.

**Comment by dannon** [comment]
@bernt-matthias Thanks for checking that.  I still have to fix up the testing framework to accommodate the changes, but if you have a chance you could try the current state of that PR and see if users are creating correctly for you now.  I'm going to follow up on the password being stored separately, since that doesn't seem to be a new change.

**Comment by bernt-matthias** [comment]
I can try tomorrow (but I guess it will not happen before beginning of next week) - since I need to test this with an actual user that has not registered yet.

**Comment by bernt-matthias** [comment]
Hi @dannon. I tested the current state. Seems to work -- a new user was auto-registered at first login. No errors or warnings in the logs.

**Comment by dannon** [comment]
@bernt-matthias Thanks for testing it, and for the patience on this bug -- good to hear it works now.  We'll get this merged into dev and make sure it's in the forthcoming release.

**Comment by bernt-matthias** [comment]
Sounds great :+1: Since registration still works in 19.01 no production system will be affected.

**Comment by guerler** [comment]
Yes, thanks a lot @bernt-matthias for having reported this issue! Very helpful.
