### ISSUE TITLE
UCSC tools from bioconda openssl error with version 357

### ISSUE THREAD

**Issue by monprin** [galaxyproject/galaxy#7618]
When doing a fresh install of v19.01, there is an out of the box issue with the ucsc tools that are getting installed from bioconda as version 357.

When running them, such as to use trackster on a bam file, I am presented with this error: 
```
Fatal error: Exit code 127 ()
bedGraphToBigWig: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

After some digging, I found this is due to the fact that in version 357 on bioconda they are not version constrained to ensure they have the correct version of openssl installed. Now that there is a new release of openssl, they are broken. In the most recent release (377) this issue is fixed and I can confirm that at least upgrading the relevant environment does solve the trackster error. 

It would be helpful if these were upgraded for 19.05 (and if possible 19.01) to obviate the need for ugly workarounds that I am currently employing.

Thank you.

**Comment by mvdbeek** [comment]
Thanks for the report @monprin, these should indeed be updated.

**Comment by jmchilton** [comment]
Ping @bgruening - any chance you can fix the bioconda packages for ucsc at version 357? Otherwise we can update Galaxy to point at a new version, but this will cause existing Galaxies to download newer versions of the packages and break reproducibility at the site.

**Comment by nsoranzo** [comment]
@jmchilton @mvdbeek  It seems that the ucsc bioconda packages with version >= 366 correctly pin a compatible openssl version range. Are you OK with me updating the tool version and requirements for the affected tools shipped with Galaxy?

**Comment by mvdbeek** [comment]
That's fine with me, but it does mean admins need to re-install dependencies on update

**Comment by nsoranzo** [comment]
> but it does mean admins need to re-install dependencies on update

That happens every now and then, we should probably mention that in our upgrade documentation and tutorial.

**Comment by bgruening** [comment]
@jmchilton yes I was trying it here: https://github.com/galaxyproject/conda-iuc/pull/18
But as usual, I need to update either the build infrastructure or I can push a local build.

**Comment by nsoranzo** [comment]
@bgruening That wouldn't help for 19.01, we are not using the `ucsc_tools` package any more.

**Comment by bgruening** [comment]
We don't? What are we using? Than it might be even easier.

**Comment by nsoranzo** [comment]
The various `ucsc-*` packages from bioconda.

**Comment by bgruening** [comment]
I think this is fixable.

**Comment by bgruening** [comment]
@monprin can you please try this again? There is a chance that we fixed that.

**Comment by nsoranzo** [comment]
Thanks @bgruening , https://github.com/bioconda/bioconda-recipes/pull/14405 fixes it for me.

**Comment by mvdbeek** [comment]
Excellent, thanks @monprin and @bgruening !

**Comment by monprin** [comment]
Hey @bgruening, 

Should I try it with the dev version or 19.01?

Thanks for taking care of this!
Joe

**Comment by mvdbeek** [comment]
Any version will do, the old package was fixed. Just make sure it really fetches the new version by removing the old install and running `conda clean -itp`.

**Comment by monprin** [comment]
I did a fresh install with the ansible role plus my additions and it does seem to work now.

Thanks!
