### ISSUE TITLE
pasting URL into upload dialog does not work

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#762]
If you paste a URL or some other content into the upload dialog with your mouse (right click) the _filesize_ label is not triggered to be updated and without a size the upload will be aborted.

**Comment by dannon** [comment]
Should be resolved with #778

**Comment by bgruening** [comment]
Thanks @dannon for the quick fix! Can we move this over to stable?

**Comment by dannon** [comment]
@bgruening If that's a +1 (yielding two +1s), then I'll cherry-pick it over and merge forward.

**Comment by martenson** [comment]
I am +1 on this being in 15.07 but I do not think the votes are transitive in this direction.

**Comment by dannon** [comment]
We have in the past, but I'll just make a separate PR, that's fine.

**Comment by dannon** [comment]
Was clunky to apply anyway, due to conflicts and recent changes.  I reopened a new PR against 15.07.
