### ISSUE TITLE
Incorrect output format detected when using `format_source` for `fastqsanger.gz` dataset for the 1st run

### ISSUE THREAD

**Issue by bebatut** [galaxyproject/galaxy#7622]
Hi,

@wm75 and I identified a strange "bug" with output format detection using `format_source`

**Issue**: incorrect output format detected when using `format_source` for `fastqsanger.gz` (as fastqsanger) datasets run for the 1st run
**Usecase**: SortMeRNA on usegalaxy.eu but also using Planemo
**How to reproduce it**:
1. Auto-detect (same issue if `fastqsanger.gz` as format) 
	1. Upload a fastq.gz file with auto-detection of the format
	2. Run SortMeRNA with the uploaded file as input file (`(as fastqsanger)`)
	3. Check the generated file: `format: data`
    4. Re-run SortMeRNA
	5. Check the generated file: `format: fastqsanger` (what is expected)
2. Force `fastqsanger` format on upload
	1. Upload the same fastq.gz file by forcing `fastqsanger` format
	2. Run SortMeRNA with the uploaded file as input file (no `(as fastqsanger)` displayed)
	3. Check the generated file: `format: fastqsanger`

It seems that the format detection for the output using `format_source` of the input is made before the correct metadata of the input are assigned 
We echoed `ext` in the command section: it is always `fastqsanger`. So the output format detection is made before the command section.

Any idea how we could fix that?

Thanks a lot

Bérénice

**Comment by mvdbeek** [comment]
> 3\. Check the generated file: `format: data`

So is that where it is going wrong ? This should have been fastqsanger ?

**Comment by martenson** [comment]
is `sniff_compressed_dynamic_datatypes_default: true` on *.eu?

**Comment by hexylena** [comment]
@martenson https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/group_vars/gxconfig.yml#L332

**Comment by mvdbeek** [comment]
I can reproduce this, this is unrelated to any eventual sniffing. https://github.com/galaxyproject/galaxy/pull/7682 should fix this.

**Comment by mvdbeek** [comment]
Alright, this should be fixed by https://github.com/galaxyproject/galaxy/pull/7682, it'll just need to be deployed on usegalaxy.*
