### ISSUE TITLE
Values added to specific tool fields do not display in the editor on subsequent openings of workflows

### ISSUE THREAD

**Issue by hepcat72** [galaxyproject/galaxy#7624]
This is an issue I've noticed specifically with the "Cut" (v1.1.0) tool's "fields" text field.

Concrete example:

1. Add Cut v1.1.0 to a workflow
2. Select "Cut by" -> "fields"
3. In "List of fields", enter "1,3"
4. Save the workflow
5. Close the editor
6. Re-open the workflow & click the cut tool to view its parameters

If you do this (both in galaxy 18.09 and 19.01), the "List of Fields" text box is empty after step 6.  However, if you run the workflow, the entries are shown in the run form.  Here's a screenshot of 2 overlapping private browser windows.  The editor (after step 6) is on the left & the run form is on the right:

![image](https://user-images.githubusercontent.com/2300532/55245847-62b27280-521a-11e9-8b74-6f29ff7814dd.png)

**Comment by mvdbeek** [comment]
Thanks @hepcat72, this is probably specific to tools that use the `ColumnListParameter` type of parameters. These look like select lists in the tool form but get cast into a text field in the workflow editor.

**Comment by mvdbeek** [comment]
OK, this was already unintentionally fixed by https://github.com/galaxyproject/galaxy/pull/7534, which is not yet on usegalaxy.*, but if you update your local 19.01 branch it works.
