### ISSUE TITLE
Use more cryptographically secure hashing method

### ISSUE THREAD

**Issue by VJalili** [galaxyproject/galaxy#7635]
We're using sha1 for a number of hashing requirements: 

https://github.com/galaxyproject/galaxy/blob/d538dc05b8ad60879e1c0164a985ada5aa56e2d2/lib/galaxy/util/hash_util.py#L68-L76

However, sha1 is not the latest crypto-secure hashing method and shall be replaced by latest methods.

**Comment by mvdbeek** [comment]
We don't even need any cryptographic hashes here, this was just chosen out of convenience. We control the source of the hashes (via the requirement tag, that tool authors are free to choose anyway) and we control their deposition (https://github.com/BioContainers/multi-package-containers/). So the only reason would be to avoid accidental collision, which is extremely unlikely.

**Comment by VJalili** [comment]
This is used for encrypting user passwords: 

https://github.com/galaxyproject/galaxy/blob/d538dc05b8ad60879e1c0164a985ada5aa56e2d2/lib/galaxy/model/__init__.py#L325-L333

**Comment by mvdbeek** [comment]
Right, that may warrant an update then, but that wasn't in your issue description. Changing the hashing method for requirements would be a large piece of work.

**Comment by mvdbeek** [comment]
Oh, I think we're not talking of the same thing here, I misunderstood hashing requirements here ;).

**Comment by VJalili** [comment]
Sorry I was not clear, I am talking about cryptographically hashing sensitive data (e.g., passwords) before storing them in the database.

**Comment by martenson** [comment]
It is there only for legacy reasons. The default is

```
def hash_password_PBKDF2(password):
    # Generate a random salt
    salt = b64encode(urandom(SALT_LENGTH))
    # Apply the pbkdf2 encoding
    hashed_password = pbkdf2_bin(password, salt, COST_FACTOR, KEY_LENGTH, getattr(hashlib, HASH_FUNCTION))
    encoded_password = unicodify(b64encode(hashed_password))
    # Format
    return 'PBKDF2${0}${1}${2}${3}'.format(HASH_FUNCTION, COST_FACTOR, unicodify(salt), encoded_password)
```

```
  # Allow disabling pbkdf2 hashing of passwords for legacy situations.
  # This should normally be left enabled unless there is a specific
  # reason to disable it.
  #use_pbkdf2: true
```

**Comment by VJalili** [comment]
Sounds great!
