### ISSUE TITLE
GenomeSpace interaction no longer possible

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#7648]
Due to removal of OpenID (https://github.com/galaxyproject/galaxy/pull/7028), GenomeSpace tools will no longer work.

```
galaxy.jobs.runners ERROR 2019-04-02 17:07:26,665 [p:64478,w:1,m:0] [LocalRunner.work_thread-0] (1353) Failure preparing job
Traceback (most recent call last):
  File "lib/galaxy/jobs/runners/__init__.py", line 223, in prepare_job
    job_wrapper.prepare()
  File "lib/galaxy/jobs/__init__.py", line 871, in prepare
    self.command_line, self.extra_filenames, self.environment_variables = tool_evaluator.build()
  File "lib/galaxy/tools/evaluation.py", line 454, in build
    raise e
AssertionError: Invalid token. You must be logged into GenomeSpace through OpenID.
```

**Comment by dannon** [comment]
Well this isn't great. I tried to check http://www.genomespace.org/ for updated documentation to figure out paths forward, but it's down.  Is there a way to use openid connect here?

**Comment by blankenberg** [comment]
Good question. My understanding was that OIDC was within the development plan for GenomeSpace, but I am not sure of the current status. The jsui (https://gsui.genomespace.org/jsui/) is working, but I also can't connect to the docs webserver right now. 

FWIIW, if you have GenomeSpace setup (e.g. in <=19.01) via OpenID and then update to dev, things will work (after inclusion of https://github.com/galaxyproject/galaxy/pull/7647) as long as the token remains valid. Obviously not a way for users to make use of GenomeSpace, but I wanted to make note of this for any testing purposes.

**Comment by nuwang** [comment]
The last time I spoke to Ted Liefeld from the GenomeSpace team, he said that no active development was being done on GenomeSpace, in which case, OpenID connect support may not be forthcoming. This was some time back though, so I've just sent an email to him asking for some input.

**Comment by dannon** [comment]
@nuwang Thanks!

**Comment by liefeld** [comment]
Because funding for the GenomeSpace project ends soon we will not be able to make the changes required to continue communication between Galaxy and GenomeSpace. We sincerely regret any inconvenience this may cause you and other Galaxy users.

**Comment by dannon** [comment]
@liefeld You just mean in terms of implementing OIDC?  Or is the whole project shutting down?  If I were to restore OpenID connectivity from the Galaxy side, how long should be expected to continue to work?

**Comment by nuwang** [comment]
One possibility here is to go ahead and remove the openid integration, and instead, use the token returned by the GenomeSpace dialogue to authenticate. Ted modified the GenomeSpace file browse dialogue to return that auth token, so that we could use the GenomeSpace tool in Galaxy without having to manually setup the open id link. Once the token is available, the python-genomespaceclient can authenticate with the Genomespace API.

This worked in the past, however, the mistake I made was sending in the parameter as a tool parameter, which got stored in the database and created a big security issue. As a result, that bit was rolled back in favour of the open_id integration again. However, if there's a way to communicate this token from the front-end to the backend without it being a tool parameter, we could still make things work. Perhaps the front-end can be special cased to send in the token through a cookie or something and let the tool wrapper read it in through user_preferences as usual? (https://github.com/galaxyproject/galaxy/blob/dev/tools/genomespace/genomespace_importer.xml#L6) Just throwing it out there.

**Comment by guerler** [comment]
Thanks for looking into it and coming up with options to solve this issue @nuwang. I added #7676 and ran a few tests. It seems to work well. It restores some OpenID features as a contained module and makes it available in the user preferences view.

**Comment by nuwang** [comment]
I did see that PR. I was just thinking that if openid is only used by genomespace, perhaps it would still be worthwhile dropping openid if an alternative is available? Regardless, between the two PRs, there's a reduction of ~500 lines, so nice work @guerler!

**Comment by guerler** [comment]
Thank you. Also with this PR the OpenID feature is self-contained. If we would delete the openid directory and the controller file, Galaxy would work as usual with only one invalid UI link to it while it was pretty embedded in other processes previously.

**Comment by liefeld** [comment]
@dannon it means the project is shutting down.  Funding should last us through February 2020 so if you restore OpenID that will allow a good transition time for the Galaxy/GenomeSpace users (145 unique individual users in March 2019).  I know it's a nuisance to re-instate but we do want to keep it useful to our users as long as possible (908 users in last March total)

**Comment by blankenberg** [comment]
@liefeld I think we currently have everything working correctly in both the current release and dev/for 19.05. OpenID for GenomeSpace will continue to work, and a few updates/fixes to the underlying import/export tools were made. 

usegalaxy.org should be updated sometime soon to latest 19.01, which will fix the issue with OpenID not actually logging the user in.

**Comment by martenson** [comment]
usegalaxy.org is updated now

**Comment by blankenberg** [comment]
Awesome, thanks @martenson! 

@liefeld things look to be mostly working for me now. There is a small issue still with datasets exported from Galaxy to GenomeSpace turning red (error), but actually succeeding. Once, this commit/PR (https://github.com/galaxyproject/galaxy/pull/7697#issuecomment-481339779) is added to 19.01 that issue should be resolved as well. 


Please let us know if you are still encountering issues.
