### ISSUE TITLE
Poor table rendering in docs.galaxyproject.org

### ISSUE THREAD

**Issue by hepcat72** [galaxyproject/galaxy#7653]
Not sure if this is the right place to report this, but the rendering of tables at:

https://docs.galaxyproject.org/en/master/dev/schema.html

inserts random spaces in the text.  See screen shot attached.

This affects all 3 browsers I checked on my mac: Safari, Chrome, & Firefox.

<img width="730" alt="galaxydoc_table_rendering_issue" src="https://user-images.githubusercontent.com/2300532/55497555-9a049300-560f-11e9-8f66-e05b70fa9dd3.png">

**Comment by nsoranzo** [comment]
This is fixed already on the `dev` branch: https://docs.galaxyproject.org/en/latest/dev/schema.html
