### ISSUE TITLE
Support for conditional execution in workflows

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#7662]
Conditional execution of workflow steps is very useful when a workflow includes a quality control step that might act as a gate to permit / deny further execution. Some other ideas for conditional support for workflows are in the CWL issue tracker here: https://github.com/common-workflow-language/common-workflow-language/issues/725

Is conditional execution of Galaxy (sub?) workflows going to come in the future?

**Comment by mvdbeek** [comment]
Yep, part of 23.0 via https://github.com/galaxyproject/galaxy/pull/15328 and https://github.com/galaxyproject/galaxy/pull/14846
