### ISSUE TITLE
Setting decompress="True" on tool tests will pass even when the file is not compressed

### ISSUE THREAD

**Issue by lparsons** [galaxyproject/galaxy#7671]
When setting `decompress="True"` in a tool output in a test (See https://docs.galaxyproject.org/en/latest/dev/schema.html#id86), the test passes even when the tool (incorrectly) outputs a non-compressed file. See https://github.com/galaxyproject/tools-iuc/pull/2361/files#r272678112.

**Comment by martenson** [comment]
Because it is not part of the assertion, it only decompresses when needed to be able to `assert` diff. 

```
If compare is set to diff, attempt to decompress both produced output and expected output files if 
needed before performing the diff. This flag is useful for testing gzipped outputs that are non-
deterministic despite having deterministic decompressed contents. This is available in Galaxy since 
release 17.05 and was introduced in pull request #3550.
```

**Comment by lparsons** [comment]
Makes total sense... Is there a way I can assert that the file is, in fact, a zipped file? In addition to checking decompressed diffs?

**Comment by martenson** [comment]
imo `ftype` should do that: 

```
If specified, this value will be checked against the corresponding output's data type. If these do not match, the test will fail.
```

**Comment by lparsons** [comment]
No, `ftype` simply checks that Galaxy set the output filetype to the specified value. That was already happening, the problem was that the while the filetype was set to `fastqsanger.gz`, the actual file wasn't zipped. The PR I submitted fixes that, but I wanted a test that would fail with the old version and pass with the new one.

**Comment by lparsons** [comment]
Basically, I want to assert that the file actually decompresses to match the contents of the specified test file. IMHO, `decompress="True"` should do that. In other words, `decompress="True"` should fail if the output file was not, in fact, a compressed file.

**Comment by martenson** [comment]
> while the filetype was set to fastqsanger.gz, the actual file wasn't zipped

this means the sniffer failed?

**Comment by lparsons** [comment]
> > while the filetype was set to fastqsanger.gz, the actual file wasn't zipped
> 
> this means the sniffer failed?

I suppose it did? I'm not really sure what, if anything, should/could have caught this. However, nothing did catch the problem. No errors were produced anywhere until a downstream tool attempted to use the output. That downstream tool would fail since it was told the file was `fastqsanger.gz` when the file on disk was actually `fastqsanger`.

**Comment by mvdbeek** [comment]
> this means the sniffer failed?

There's no sniffing when you set a datatype for an output, this is only done for `format="auto"`. I think we just don't have a way to assert whether an output really is what it claims to be beyond the normal comparisons. If `decompress` is `"False"` or not defined this works as expected, right ? I think Bjoern is right that we'd want to compare using file size and, if necessary, a delta.

**Comment by lparsons** [comment]
So, did we decide we do not want to add a method to assert that an output is actually compressed? I suppose the sim_size and delta could work, but it doesn't really test the output too carefully. However, perhaps it's good enough.

**Comment by bernt-matthias** [comment]
I guess the `has_archive_member` assertion is what you are looking for. It's now well documented: https://docs.galaxyproject.org/en/master/dev/schema.html#has-archive-member and can also be combined with other assertions like `has_text`

There are some tests https://github.com/galaxyproject/galaxy/blob/a277c2421af56c1d2d97bead0248fb25d721ab04/test/functional/tools/validation_tar_gz.xml, https://github.com/galaxyproject/galaxy/blob/a277c2421af56c1d2d97bead0248fb25d721ab04/test/functional/tools/validation_tar.xml, https://github.com/galaxyproject/galaxy/blob/a277c2421af56c1d2d97bead0248fb25d721ab04/test/functional/tools/validation_zip.xml which should be a good starting point if the docs should still be insufficient.

Guess I can close this - feel free to reopen if needed.
