### ISSUE TITLE
very slow response when going into repo detail installation

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#7692]
using the beta installation interface

e.g. fastqc (Request URL: http://127.0.0.1:8080/api/tool_shed/repository?tool_shed_url=https:%2f%2ftoolshed.g2.bx.psu.edu%2f&repository_id=ca249a25748b71a3
) takes 12seconds to get response for

**Comment by davebx** [comment]
I believe #6652 resolved this.

The code in that PR is present on TTS, and the same repository's url would be http://127.0.0.1:8080/api/tool_shed/repository?tool_shed_url=https:%2f%2ftesttoolshed.g2.bx.psu.edu%2f&repository_id=2ae6b061c7e09f75, which loads in under 2 seconds for me.

**Comment by davebx** [comment]
I'm calling this resolved, if it recurs I'll take another look.

**Comment by martenson** [comment]
it is much better, thanks for closing @davebx !
