### ISSUE TITLE
/api/workflows/{}/invocations not accessible

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#7710]
Same problem as https://github.com/galaxyproject/galaxy/issues/4401

I am not sure how your model queries work but check_security might be used as a filter here: [workflows.py#L217](https://github.com/galaxyproject/galaxy/blob/d05ee64e64601afaea631b435fad3a5fe1f2b932/lib/galaxy/managers/workflows.py#L217)

This won't work though as check_security throws an exception rather than return false.

**Comment by mvdbeek** [comment]
Thanks for the report, should be fixed with https://github.com/galaxyproject/galaxy/pull/7711
