### ISSUE TITLE
[15.07] Workflow runs tool with wrong input when tool creating output collection is present

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#776]
This problem was found by @anilthanki and me while creating a very big workflow, but we were able to create a minimal example that reproduce the same problem.

![Reduce broken workflow](http://i.imgur.com/Pl1Wj29.png)

Description of the problem: `hcluster_sg_parser` tool produces a list collection, `Filter by FASTA IDs` should be run on the **top** dataset (protein sequence) and this list (producing a new output list), instead it is run on the **bottom** dataset (cds) and the list.
N.B.: Nothing changes if the bottom dataset is connected to other tools. We tried to change tool id, param ids,... and nothing changed, I think this is connected to the job scheduling performed by the workflow invoker, which for some reason uses the wrong dataset.

Here are the workflow and the inputs: https://gist.github.com/nsoranzo/59d1b9480eb9cd44758c

The workflow needs these tools:
- https://github.com/TGAC/tgac-galaxytools/tree/master/tools/hcluster_sg_parser
- https://toolshed.g2.bx.psu.edu/view/galaxyp/filter_by_fasta_ids/463ebeccb854

This bug affects both release_15.07 and dev branches.

**Comment by jmchilton** [comment]
Reproducible interactively using existing test tools. I'll draw up an API test today and work against that.

![test_tools](https://cloud.githubusercontent.com/assets/216771/10077818/eb12e9b8-62d9-11e5-8edb-d0d0921c90a4.png)

**Comment by dannon** [comment]
(technically not closed for 15.07 yet -- needs to be merged forward once #794 has a second emoji_thumbs_up)
