### ISSUE TITLE
Fix Look and Feel in Dataset Libraries

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#7764]
Although we made progress aligning the Data Library's Look and Feel to the rest of Galaxy, there are still some remaining issues. Here, our goal is to remove most if not all custom-styles and hard-coded style tags, and use Bootstrap4 classes instead.

I recommend to start by fixing the code format of the template functions by inserting indentions and using multi-line strings (``) as shown in #7234, instead of joining string arrays. This will restore readability of the template functions. Remember to run `make client-watch` to automatically repack the client-code after making changes.

Here is a list:

 - [ ] Fix `Create New Library` modal. Currently inputs are lined up in one row, should be replaced with a regular input form e.g. like login or tool form.
See: https://getbootstrap.com/docs/4.0/components/forms/

- [ ] Replace Toastr messages with regular alert messages. Toastr messages overlap with underlying options and in some cases produce a third layer i.e. Library View + Modal + Toastr.
See: https://getbootstrap.com/docs/4.0/components/alerts/

- [ ] Use regular small buttons for `Save`, `Cancel`, `Delete`, `Edit` and `Manage`.
See: https://getbootstrap.com/docs/4.0/components/buttons/

 - [ ] Fix `Adding datasets from your history` modal content, `Select all`, `Unselect all` spacing, use table for list, use default style select fields, fix overall appearance.

- [ ] Fix `Create History Collection from Datasets`, use regular input elements e.g. radio button and select field, remove custom styling.

- [ ] Remove `How many libraries per page do you want to see?` alert and use an editable field instead of using the `change` link.

- [ ] Use regular fonts and highlighting for table-rows in main library list view

ping @bgruening, @martenson.

**Comment by inkuzmin** [comment]
Hello @guerler!
Can I help with these tasks?

**Comment by bgruening** [comment]
@inkuzmin that would be awesome!

**Comment by martenson** [comment]
@inkuzm yes please! :)

I would be wary of the toastr replacement though, some of the notifications are asynchronous and should not be replaced with an alert I think.

**Comment by inkuzmin** [comment]
@bgruening @martenson, excellent!

@martenson, I am not sure I've got your concerns; can you, please, explain why do you expect the proposed replacement to make an issue in case of asynchronous notifications?

**Comment by martenson** [comment]
@inkuzm Pease pick other issues from the list and leave the toastr last, I believe we will have consensus by then.

**Comment by inkuzmin** [comment]
@martenson, alright!
