### ISSUE TITLE
Expression tool(s) for workflow parameterization

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#7774]
https://github.com/galaxyproject/galaxy/pull/7556 has introduced expression tools (`tool_type="expression"`) that produce non-data outputs of a specific type that can be connected to parameters of the correct type in the workflow editor.

We should have a set of default tools that allow turning a given input dataset into 
- [x] integer
- [x] float
- [x] text
- [x] boolean

values. 
For a start we could just assume that the input dataset contains a single value.
(As a user / workflow developer you can massage the input however necessary using standard Galaxy tools).

**Comment by qiagu** [comment]
It seems Galaxy only supports the above-mentioned 4 types of parameters. In my tools, inputting list/tuple of the 4 types is quite often. What I did was inputting text first, then converting to list/tuple using `ast.literal_eval` in the tool script. It works but I feel it's tedious and kind of extra computation involved. Do you think it's a good practice to make a new parameter type in Galaxy to work with `literal_eval` directly?   @mvdbeek @jmchilton and others.

**Comment by mvdbeek** [comment]
Do you have an example of such a tool ?

**Comment by qiagu** [comment]
Like the `Estimator parameter` in our searchcv tool, https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/bgruening/sklearn_searchcv/sklearn_searchcv/1.0

Besides, I am wrapping the deep learning tools these days. A lot of parameters are in tuple format, like 2D, 3D shape for images

**Comment by mvdbeek** [comment]
Is this related to expression tools ?
If you want to add an additional parameter type feel free to outline something.
The text parameter you're using now seems fine, another option is a repeat.
But it looks like your issue is with getting lists of things into python, I don't think we can do anything in Galaxy about this ? You can also write your arrays into a `<configfile></configfile` and load them from there or you can dump your input section as json and manipulate the parameter value to your liking.

**Comment by qiagu** [comment]
>Is this related to expression tools ?

Probably not. I just saw you mention those parameter types.  :)

>You can also write your arrays into a <configfile></configfile and load them from there or you can dump your input section as json and manipulate the parameter value to your liking.

This is what I'm doing, I think.

>But it looks like your issue is with getting lists of things into python, I don't think we can do anything in Galaxy about this ? 

I'm not sure, but if we can make something like `type="python_list"` and let Galaxy generate list directly, which could make the tool wrapping easier. It is not a must though.
