### ISSUE TITLE
Warnings in workflow editor when opening tool form for some tools

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#7776]
In this case it's deseq2, it doesn't happen for all tools, and it only happens on dev:
<img width="558" alt="Screen Shot 2019-04-19 at 15 22 05" src="https://user-images.githubusercontent.com/6804901/56426041-0a214300-62b7-11e9-9f2d-ff1f4b7a26af.png">

**Comment by dannon** [comment]
@mvdbeek I fixed another one of these recently, I can take a look.
