### ISSUE TITLE
Ticket to capture GUI display/rendering items found

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#7787]
Found on Test at https://test.galaxyproject.org/admin/data_manager/

Note the `<h4> and `</h4>` exposed tags. @dannon also thinks the big "Wiki" tag (label?) could be improved.

<img width="690" alt="Screen Shot 2019-04-19 at 1 47 20 PM" src="https://user-images.githubusercontent.com/8999735/56443956-9c234e80-62ab-11e9-8c58-82cb17bcc56a.png">

**Comment by jennaj** [comment]
Found another one, not sure if known yet:

<img width="600" alt="export-history-to-file-dialog" src="https://user-images.githubusercontent.com/8999735/56916160-1fdbf880-6a6d-11e9-9094-71423abbe104.png">

**Comment by dannon** [comment]
@jennaj I think the message issue there is likely fixed with #7751, which is merged.  The Data Manager one is fixed in #7811 which is still waiting or someone to merge it.

**Comment by jennaj** [comment]
On main and eu, after generating a share link, if I click on the little pencil to edit the link name, the middle pane flips to being blank. This is 100% reproducible across many histories, both servers. 

Known? Is there a ticket or PR?

**Comment by dannon** [comment]
@jennaj No open ticket.  Let's create individual issues for these moving forward, instead of using a mega ticket like this, though.  I'll create an individual one for that, and close this out now.
