### ISSUE TITLE
filtering on tag from within a shared page is broken

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#7792]
this is from Main

https://usegalaxy.org/u/mkerdawyy/p/identification-of-snps-ten-single-cell-whole-genome-sequencing-of-brain-cells-of-alzheimers-disease

![p-tags](https://user-images.githubusercontent.com/1814954/56522286-400f3300-6514-11e9-8d37-6728dd720e48.gif)

**Comment by martenson** [comment]
the same is true with shared workflows, histories etc

**Comment by WilliamHolden** [comment]
Opened up PR: https://github.com/galaxyproject/galaxy/pull/7923.

The issue was that the clickURL was using the singular name for controller instead of plural. Eg. "page" instead of "pages"
