### ISSUE TITLE
Expression tools should be hidden if not in workflow editor

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#7795]
If you try to load them up in the analysis app it'll just say `Tool execution through the `tool_runner` requires a `runtool_btn` flag or `URL` parameter.`. Since the expression tools are not very useful outside of workflows (at the moment at least) we should probably only display them in the workflow editor.

**Comment by martenson** [comment]
The tools are hidden, but the empty section is visible.
![Galaxy](https://user-images.githubusercontent.com/1814954/67028038-a6969780-f0d8-11e9-88fe-184312ae7164.png)

**Comment by mvdbeek** [comment]
Bug, but not blocking, I think.
