### ISSUE TITLE
Multiple datasets with the same ID/number & wrong one being used in next workflow step

### ISSUE THREAD

**Issue by hepcat72** [galaxyproject/galaxy#7821]
I have a workflow that at one point runs:

1. Concatenate 2 fastqsanger.gz files
2. awk on the output of step 4 (to count the sequences)

Step 1 produces 3 datasets with the same ID/number, each with a different format:

1. fastqsanger (" uncompressed" is appended to the dataset name)
2. fqtoc (which appears to be JSON)
3. fastqsanger.gz

<img width="274" alt="3datasetssameid" src="https://user-images.githubusercontent.com/2300532/56748907-ad0e0d00-674e-11e9-9bc8-6e71291f8796.png">

The awk code `END{print int( NR / 4 )}` in the workflow produces `0` as the output, so I tried rerunning using each of the 3 versions of the dataset.  I unhid all 3 datasets and the all appear in the select list.  If you select items 1 or 3 above in the multiple select list, they both get selected, but only if you select item 1 in the single select list, do you get an output other than `0`.

I discovered that awk is being run (by the workflow) on the FQTOC file instead of the uncompressed fastqsanger (which is the only one that produces the expected output):

<img width="274" alt="awkrunonfqtocfile" src="https://user-images.githubusercontent.com/2300532/56748556-15a8ba00-674e-11e9-88f1-82e2c65f278f.png">

Is there a way for me to explicitly specify that a subsequent tool should use a particular version of a dataset so that I don't have to manually run these and all subsequent steps?

This multiple version dataset issue appears to be widespread throughout the history of my workflow, but this appears to be the only step where the wrong version was used.

**Comment by bernt-matthias** [comment]
> I have a workflow that at one point runs:
> 
>     1. Concatenate 2 fastqsanger.gz files
> 
>     2. awk on the output of step 4 (to count the sequences)

What is step 4?

> Step 1 produces 3 datasets with the same ID/number, each with a different format:

How can concatenate 2 fastq.gz (which tool are you referring to ... ?) produce 3 outputs. 

> <img alt="3datasetssameid" width="274" src="https://user-images.githubusercontent.com/2300532/56748907-ad0e0d00-674e-11e9-9bc8-6e71291f8796.png">

The image shows something with "cutadapt..." 

> The awk code `END{print int( NR / 4 )}` in the workflow produces `0` as the output, so I tried rerunning using each of the 3 versions of the dataset. I unhid all 3 datasets and the all appear in the select list. If you select items 1 or 3 above in the multiple select list, they both get selected, but only if you select item 1 in the single select list, do you get an output other than `0`.

What is this awk tool doing ... ?  

> I discovered that awk is being run (by the workflow) on the FTQOC file instead of the uncompressed (which is the only one that I found produces expected output):

What is FTQOC? I guess details on the workflow are needed. What is included, how is it connected, what did you change after creating the workflow.

> <img alt="awkrunonfqtocfile" width="274" src="https://user-images.githubusercontent.com/2300532/56748556-15a8ba00-674e-11e9-88f1-82e2c65f278f.png">
> 
> Is there a way for me to explicitly specify that a subsequent tool should use a particular version of a dataset so that I don't have to manually run these and all subsequent steps?
> 
> This multiple version dataset issue appears to be widespread throughout the history of my workflow, but this appears to be the only step where the wrong version was used.

What galaxy version are you running? 

So many questions ...

**Comment by hepcat72** [comment]
> > I have a workflow that at one point runs:
> > ```
> > 1. Concatenate 2 fastqsanger.gz files
> > 
> > 2. awk on the output of step 4 (to count the sequences)
> > ```
> 
> What is step 4?

Yeah, sorry.  Please ignore "step 4".  I was trying to remove the irrelevant bits of my notes to focus on the parts relevant to this issue and I missed the step 4 reference.  In this context, it should be "step 1" (the concatenation).

> > Step 1 produces 3 datasets with the same ID/number, each with a different format:
> 
> How can concatenate 2 fastq.gz (which tool are you referring to ... ?) produce 3 outputs.

Exactly.  That's the crux of this issue (3 outputs) - and is what I'm saying is an issue.  It should only produce 1 output dataset, but it is producing 3, all with the same ID.  In the screenshot, they're all "412".  (Note, they're unfortunately named "Cutadapt on..." - (I'm still getting the hang of using those `#{input | basename}` variables).

The concatenate tool is `Concatenate datasets tail-to-head (Galaxy Version 1.0.0)`.

> > <img alt="3datasetssameid" width="274" src="https://user-images.githubusercontent.com/2300532/56748907-ad0e0d00-674e-11e9-9bc8-6e71291f8796.png">
> 
> The image shows something with "cutadapt..."

See above comment.  They say cutadapt, but they are from the concatenate tool.

> > The awk code `END{print int( NR / 4 )}` in the workflow produces `0` as the output, so I tried rerunning using each of the 3 versions of the dataset. I unhid all 3 datasets and the all appear in the select list. If you select items 1 or 3 above in the multiple select list, they both get selected, but only if you select item 1 in the single select list, do you get an output other than `0`.
> 
> What is this awk tool doing ... ?

**(to count the sequences)**

> > I discovered that awk is being run (by the workflow) on the FQTOC file instead of the uncompressed (which is the only one that I found produces expected output):
> 
> What is FQTOC? I guess details on the workflow are needed. What is included, how is it connected, what did you change after creating the workflow.

I do not know what FQTOC is.  It looks like a json file.  I did not intentionally create it.  It's the format of one of the 3 datasets apparently created by the concatenate tool (as seen in the screenshot) when it is run on the output of 2 different cutadapt tool calls in the workflow (one of which is reverse complemented).  Let me just paste a screenshot from the workflow:

<img width="1252" alt="ca-ca-rc-concat" src="https://user-images.githubusercontent.com/2300532/58507638-33f44200-8160-11e9-8966-0828b41d1cf5.png">

And that feeds directly into the awk tool.  The only step before the image above is a call to FLASH to stitch the forward and reverse reads together.

The formats of the 3 datasets that last concatenate tool (in the above image) adds to my history (all with the same ID) are:

- fastqsanger
- fastqsanger.gz
- FQTOC

> > <img alt="awkrunonfqtocfile" width="274" src="https://user-images.githubusercontent.com/2300532/56748556-15a8ba00-674e-11e9-88f1-82e2c65f278f.png">
> > Is there a way for me to explicitly specify that a subsequent tool should use a particular version of a dataset so that I don't have to manually run these and all subsequent steps?
> > This multiple version dataset issue appears to be widespread throughout the history of my workflow, but this appears to be the only step where the wrong version was used.
> 
> What galaxy version are you running?

19.01

> So many questions ...

Indeed.  So a bit of context...  The user I was helping was having an issue where much of her data was not making it through the entire workflow each time and so I wanted to figure out which step was causing the most data loss.  The cause of the data loss from different sequencing runs was different, so I wanted some QC output to display data loss after each step.  There are about 5 steps in the overall pipeline which have the ability to discard reads for various reasons (FLASH and 4 calls to cutadapt for a 5' template (in either orientation) and 2, 3' sequences (linker and poly-A)), so I shunted the sequence outputs from those 5 steps to tools that count the sequences remaining after each step.  One of those steps is the awk call where I discovered this problem.  The awk call, as I indicated earlier, is simply to count the number of sequences (which I assume to be the number of lines in the fastq file divided by 4).  I then concatenate those numbers in a single file and plot them in a custom multiQC graph so I can see which step is causing the loss of the most number of reads.

I should point out that I have since discovered 2 work-arounds to this issue.  If I connect the output of the concatenate tool to "FASTQ to Tabular" and then connect that to the awk tool, awk runs on the sequences instead of the FQTOC file.  The other workaround is to run the workflow on uncompressed data.  So I have a fully working workflow currently.

I have a hunch that when it is gzip data that is passing through the workflow and it connects to awk, the file that should be selected to be sent to awk is the fastqsanger file, but the FQTOC file was selected instead somehow.  And I suspect that those 3 files from the history with the same ID are files that are usually obfuscated from the user (and shown as 1 file) and that since the FQTOC file was what awk ran on, those usually hidden files became visible.  So I suspect that perhaps, there's a case that is erroneously selecting FQTOC instead of fastqsanger.

**Comment by bernt-matthias** [comment]
Can you provide a sample history on some usegalaxy server?

**Comment by hepcat72** [comment]
It's an enormous history.  There are 5 sub-flows.  However, I recently posted the workflows for the ensuing publication:

https://github.com/hepcat72/RNAseP-MRP

They are under the subfolder named "maturing_polya_abundance_analysis".  The FLASH and cutadapt calls are in the main workflow:

- Mature_RNA_Abundance_Analysis_v4_(streamlined).ga

And the awk call (currently "fixed" via inserting the FASTQ to tabular tool) is in the 5th subworkflow named:

- Mature_RNA_Abundance_Analysis_Helper_5_(collate_survival).ga

You can re-introduce the errant behavior but cutting out the FASTQ to Tabular tool.

Let me know if that's helpful.

**Comment by hepcat72** [comment]
I’ll see if I can throw together a toy example, perhaps tomorrow.

**Comment by hepcat72** [comment]
A small version of the workflow:

https://usegalaxy.org/u/hepcat_72/w/galaxy-issue7821-3---dupe-ids-imported-from-uploaded-file

I copied each of the history items from our galaxy instance to usegalaxy.org:

https://usegalaxy.org/u/hepcat_72/h/issue7821

Note: I would have simply re-run the workflow on the one input file, but usegalaxy.org doesn't have the necessary tools and tool versions to run the workflow:

cutadapt version 1.16.5 fails in the second step of the workflow (because of a bug in the first step that's fixed in version 1.16.6), but if both steps 1 and 2 are version 1.16.6 works - it just needs to be installed.

- Step 2: Cutadapt
    - Using version '1.16.5' instead of version '1.16.6' specified in this workflow.
- Step 3: Cutadapt
    - Using version '1.16.5' instead of version '1.16.6' specified in this workflow.
- Step 5: toolshed.g2.bx.psu.edu/repos/bgruening/text_processing/tp_awk_tool/1.1.1
    - Tool is not installed

Note, the output of the awk tool should contain the number of sequences in the file that was input into it, but instead, it has `0`, which is erroneous.  It also says that the file format of awk's output file is `fqtoc`, which suggests that it ran on the fqtoc file instead of the `fastqsanger` file.  I should probably have modified it to be txt or tabular or something in the workflow, but I'd left is as unchanged.

**Comment by valdirbarth** [comment]
I am having this exact same issue but with Trim galore. If you feed it (in my workflow) a fastqsanger.gz file instead of a fastqsanger it generates 3 files (a "fqtoc", "fastqsanger.gz", "fastqsanger", all witht the same ID in the history) but it feeds the fqtoc file to the rest of the workflow, which of course causes the next step to fail. I wonder if you managed to find a fix other than the turn arounds you mentioned?

**Comment by hepcat72** [comment]
I think this may be a duplicate of #8801 and may have been fixed by https://github.com/galaxyproject/galaxy/pull/8932

What version of galaxy are you running @vbarth4 ?

**Comment by valdirbarth** [comment]
I was using version 19.09, I updated to 20.01 which looks like it fixed it! Thanks.
