### ISSUE TITLE
Sharing histories with Galaxy API

### ISSUE THREAD

**Issue by crutching** [galaxyproject/galaxy#783]
Currently there is no way to share histories between users via the API.  A system where multiple users are running workflows and the sharing their results would benefit from being able to automate this behavior.

**Comment by yhoogstrate** [comment]
\+ https://github.com/galaxyproject/galaxy/issues/595

**Comment by nsoranzo** [comment]
@yhoogstrate This is a different issue, it asks for an API to share an existing history with another user, not to view the histories shared by others with the current user.

**Comment by carlfeberhard** [comment]
This is part of the way there: querying the api works for permissions and deserializing _should_ work as well. IIRC, role creation may be where there's a gap.

**Comment by crutching** [comment]
@carlfeberhard I would be happy to work on this, but it would be helpful to get some help as to where in the code I need to focus my efforts.

**Comment by carlfeberhard** [comment]
@jhl667 I believe most of the pieces are in place for this - let me do some review and I'll get back to you today.

**Comment by carlfeberhard** [comment]
@jhl667 

The history uses the Sharable permissions system. When shared, a model that uses this creates an entry in a <Item>UserShareAssociation and that's checked to see if a user has access for reading/copying the item. The Sharables (so far) are histories, workflows, pages, and visualizations.

(Datasets and Libraries use an RBAC permission system which is evil and must be destroyed - let us never speak of it again)

So, the way I'd do it is to think of this as a getter/setter situation, starting at the client interface endpoint, the API: 
- the getter: **histories.show** should contain a key that has a list of encoded user ids of the users the history has been shared with
- the setter: **histories.update** should accept a similar list of user ids, compare it with it's current list, unshare with any that are now missing, and share with any new ids

That's where the API client would interact with but, inside the codebase, the part you'd need to change is actually a layer below in the managers. managers/histories.HistoryManager inherits from managers/sharable.SharableManager. This is where publishing, accessing, sharability, and slugs happens. By adding the user share stuff here, we can add it to histories, workflows, pages, and visualizations at the same time:
- the getter: **managers/histories/SharableModelSerializer**: I'd define a serialize_users_shared_with that called manager.get_share_assocs and returned the encoded ids of the .user for each
- the setter: **managers/histories/SharableModelDeserializer**: (a bit more complicated) you'd need to get the users that are removed and those added and look up each and validate them (preferably). Then use manager.unshare_with and manager.share_with to create the shares. You can use the flush keyword here to keep the number of transactions down IIRC - but optimizing can happen later. 

Anyway, that's how I had planned to do it. Let me know if you need more info and I'm happy to help. If you don't think you'll have time, I can do it (in 16.04) if you'd prefer. I apologize for this having taken a while.

**Comment by crutching** [comment]
@carlfeberhard I really appreciate the details, this will give me a good first place to begin the dig!  I'm going to do my best to find bandwidth to finish this one, but I will keep you in the loop.  Thanks.

**Comment by crutching** [comment]
@carlfeberhard If you do indeed have bandwidth, it would probably be easier for you to address this issue.  I would really like to spend the time on this, but I keep getting hit with other projects.  :-(

**Comment by carlfeberhard** [comment]
@jhl667 Understood. Will do.
