### ISSUE TITLE
Deleting app

### ISSUE THREAD

**Issue by 07sydsm** [galaxyproject/galaxy#7833]
Searched for an app in the app drawer. Held and pressed to open menu to uninstall app. After hitting uninstall, it uninstalled the app in that same location on the main page. Incorrectly uninstalled app icon remained but there was no pathway. Intended app to uninstall remained. 
After trying again the app uninstalled properly.

**Comment by martenson** [comment]
This project has nothing to do with the mobile phones. You are probably looking for https://www.samsung.com/us/support/.
