### ISSUE TITLE
AWS EKS + FSx: Issues with HDF5

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#7842]
I'm currently testing running on AWS using FSx (Lustre) as shared file system (very nice 0.7 GB/s throughput). However when trying to run some of our Scanpy workloads, I get issues with Lustre and HDF5:

```
  File "/usr/local/lib/python3.6/site-packages/h5py/_hl/files.py", line 176, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (file locking disabled on this file system (use HDF5_USE_FILE_LOCKING environment variable to override), errno = 38, error message = 'Function not implemented')
```

happily the error message is descriptive, but this takes me to the issue of where this should be forced to the setup. Since this is a very file system specific issue (the need for setting HDF5_USE_FILE_LOCKING environment variable), should this be handled at the tool wrapper level (probably not, but the easier), at the runner level (although inconvenient since we would need to do it for each runner, which is a pain) or at an overall Galaxy level? One would think the correct way would be at the Galaxy level, but then this would impose the behaviour on all tools, is this desirable... possibly yes since it is a file system restriction I guess.

Supposing the last suggestion is the correct, is there a place where one could add env vars to Galaxy that get pushed to the execution script on runtime?

**Comment by mvdbeek** [comment]
To me this is something that should be set using `<env></env>` [directive](https://github.com/galaxyproject/galaxy/blob/dev/config/job_conf.xml.sample_advanced#L599) on the destination, which has been designed exactly for this purpose..

**Comment by pcm32** [comment]
Thanks! my destinations are set at the container level, which would mean I would need to setup a container for Lustre on its own (supposing one doesn't want this setting on other filesystems). 

I do rely a lot on dynamic destinations (which would get me out of my problem), maybe I could indicate through an env var outside if the file system requires this and then set it at the dynamic destination. I wonder if I can set 'env' on a dynamic destination. Will try that, thanks @mvdbeek. I guess we can close this, since you answer answers my concern on how to do this.

For the record, I was thinking on setting `environment_setup_file` through an env var, and injecting/writing the file, but I think the solution you propose is better.

**Comment by mvdbeek** [comment]
Setting env vars via dynamic destinations shouldn't be a problem. You'll need to be on 19.05 or include https://github.com/galaxyproject/galaxy/pull/6958 for this to work.

**Comment by pcm32** [comment]
I have made this work on a different setup now via destinations or the runner, as suggested by @mvdbeek, so I suspect this should work as well on FSx.
