### ISSUE TITLE
feature request: share history offline and across galaxy

### ISSUE THREAD

**Issue by qiagu** [galaxyproject/galaxy#7862]
Just come across an idea. It will be great if we can pack a whole history in one server and transfer to another server, then unpack and rebuild it in the original state.

I think this could help increase reproducibility and transparency. People can run experiments on any galaxy server, and share the history over internet.

**Comment by mvdbeek** [comment]
That exists: https://galaxyproject.org/support/download-data/
And it has received a lot of improvements in 19.05.
