### ISSUE TITLE
Workflow Editor: No new "Configure output" section created for conditional outputs

### ISSUE THREAD

**Issue by shiltemann** [galaxyproject/galaxy#7876]
When adding a tool in the workflow editor, and then selecting a parameter setting that results in an additional output, the new output becomes visible on the box, but no corresponding "Configure output" section appears until you exit and reopen the editor.

For example, add the mothur tool "Summary.seqs" to a new workflow, then select the option "Output logfile":

![image](https://user-images.githubusercontent.com/2563865/57078833-53c65080-6cef-11e9-860e-067769930db3.png)

**Comment by mvdbeek** [comment]
What version of Galaxy is this ? This works on usegalaxy.org, usegalaxy.eu and on my local dev instance.

**Comment by mvdbeek** [comment]
Nvm, I was looking at the tool form

**Comment by mvdbeek** [comment]
That is still a bug on 21.01

**Comment by mvdbeek** [comment]
That's fixed ... not sure when, probably with the last reworking of the workflow editor in 23.0 or when we modernized the tool form.
