### ISSUE TITLE
issues with history sharing

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#7893]
this is from Main

I am unable to edit URL of a shared history

![cannot-edit](https://user-images.githubusercontent.com/1814954/57165180-5d6db800-6dc4-11e9-9317-a176afa60e3c.gif)

js console has `GET https://usegalaxy.org/api/histories/undefined/sharing 400 (Bad Request)`

bonus: the url has an extra `:` in the link name
![Galaxy](https://user-images.githubusercontent.com/1814954/57165121-30210a00-6dc4-11e9-806a-0d53adfbbff9.png)

**extra extra bonus** get rid of the custom yellow 'pencil icon' and replace with standard font awesome

**Comment by blankenberg** [comment]
Noticed this during workshop today as well. main/19.01 and test/19.05 are at least effected.

**Comment by WilliamHolden** [comment]
I am working on this issue in another ticket which is a duplicate as @nsoranzo pointed out: https://github.com/galaxyproject/galaxy/issues/7868#issuecomment-491070300
I also have a fix for the colon issue which I will include in the PR as well. That one also has another open ticket: https://github.com/galaxyproject/galaxy/issues/7244

**Comment by martenson** [comment]
closing as dup, thanks for working on it @WilliamHolden !

**Comment by martenson** [comment]
dammit

**Comment by martenson** [comment]
Thanks @WilliamHolden !
