### ISSUE TITLE
workflow editor: unzip collection can not connect to downstream tools 

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#7930]
In this example workflow I would like to connect the outputs of `Unzip collection` to a tool that accepts data sets and collections (via `<param type="data" multiple="true"/>`). But this seems to be impossible. 

https://usegalaxy.eu/u/maze/w/unnamed-workflow

Odd thing is that if I export this from a history a connection is created:

https://usegalaxy.eu/u/maze/w/workflow-constructed-from-history-unnamed-history

I have the same on our 19.01 instance and dev instance. There I also had the impression that export and import via a file removes the connection again. But I need to verify this.

**Comment by bernt-matthias** [comment]
Just checked with the new feature to show the reason for not connecting. There are two messages: 

- "Effective output data type(s) [data] do not appear to match input type(s)...." 
- Can't map over this input with output collection type - an output of this tool is not mapped over constraining this input. Disconnect output(s) and try again."

The former is quite clear and appears for tools created new in the editor. The latter is cryptic to me and appears for the downstream tool created during the extraction from history.

**Comment by jennaj** [comment]
The usual path is to un-connect all noodles then reconnect them starting from the inputs > downstream steps. This resets the workflow internal metadata. 

Two related tickets (and more linked from them). Think most of what can be done, has been done. But maybe the message could be improved/clarified? 

This part is confusing. Translates into the action of "disconnecting downstream noodles then reconnecting, starting from the input" eg left-to-right.

>Disconnect output(s) and try again

This part seems too technical:

>Can't map over this input with output collection type - an output of this tool is not mapped over constraining this input.

https://github.com/galaxyproject/galaxy/issues/5632
https://github.com/galaxyproject/galaxy/issues/7431

ping @jmchilton @mvdbeek @dannon 

I could help rewrite these, and others that are new messages in WF help. Where would I look to view all of them?

**Comment by bernt-matthias** [comment]
I guess the messages are defined here: 
https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/workflow/workflow-terminals.js

**Comment by jennaj** [comment]
@bernt-matthias I am going to close this out but we can reopen if needed. 

The goal is to reset the workflow's metadata. To do that, reconnecting noddles `input > output` is still required afaik if that is all you have, for any changes that present with a metadata conflict in the editor (and prior types of workflow failures -- addressed now). Or, exporting a fresh workflow from history will work as you found. I don't think that generating a workflow share link, copying, then pasting that back into Galaxy will reset the metadata (it does create a new copy) but that is something to try. 

cc @jmchilton

**Comment by jorondo1** [comment]
Sorry for re-opening an old thing, but I found a case where even disconnecting-reconnecting doesn't wully work. 

<img width="958" height="400" alt="Image" src="https://github.com/user-attachments/assets/ad463061-d1bc-453f-abfd-a0adda38df64" />

These were connected manually by disconnecting all upstroam links and reconnecting them. Here, I can connect a first Unzip collection output to Sort collection (box 37), but not the second one (box 36). If I disconnect the successful Unzip collection –> Sort collection connection I made, I cannot reconnect it as you can see. Even worse: if I so much as move the box of the successful connection, it becomes orange (this is when the connection became orange on the screencap).

Could the problem be that the output of Unzip collections is considered to be a dataset, when it is actually a connection?

**Comment by jorondo1** [comment]
Partially solved by uncovering a weird behaviour I found by "messing around" : 
1. disconnected all connections upstream of sort collection (all the way to my input data)
2. in Unzip collection parameters, switch Output cleanup on
3. Reconnect, all is fine
4. If I *move* a Sort collection box, connection becomes orange again
5. but if I then move the Unzip collection box, connection turns back blue

So I have "solved" this but the behaviour is weird and something seems to be up... maybe that deserves its own issue ticket?

**Comment by bernt-matthias** [comment]
FYI: if you have a workflow for single datasets and want to input a collection you can: create a new workflow, add a collection input and import the other workflow as subworkflow. 

> maybe that deserves its own issue ticket?

if reproducible -> yes :)
