### ISSUE TITLE
Workflow editor randomly sets tool output to workflow output

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#7959]
version 19.05
I am not sure if it does this on load or on save but random tool outputs are being 
starred as workflow outputs in the editor.

**Comment by mvdbeek** [comment]
If no output is set at all, everything is starred, that has always been the intention but was broken under some circumstances. New modules are starred by default. If you can describe what looks like a bug in more detail that would be great.

**Comment by innovate-invent** [comment]
I haven't been able to consistently reproduce the behavior. It might be if I have a tool that is a leaf of the graph but none of its outputs are starred as a workflow output that it stars all connected tools including itself. This isn't consistent though.

It might also occur for subworkflows, the subworkflow outputs are starred if the subworkflow is updated.

@mvdbeek I just confirmed, subworkflow outputs are starred on workflow reload.

**Comment by guerler** [comment]
Is this still an issue?
