### ISSUE TITLE
GenomeSpace import of fastqsanger.gz creates hidden fastqsanger upon import

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#7961]
Unnecessarily explodes the quota usage with hidden datasets

 - Most current versions of tools now accept fastqsanger.gz compressed inputs
 - Any tools that don't would implicitly convert the data at that step

What do you think @blankenberg? Are there reasons to keep this behavior as-is?

cc @jmchilton maybe a project that could be done in time for 19.05, depending on what dan's feedback is.

**Comment by martenson** [comment]
With genomespace going away in a month (http://www.genomespace.org/news/the-genomespace-project-is-ending) I am closing this issue.

**Comment by jennaj** [comment]
agree
