### ISSUE TITLE
Changing output format on extract dataset tool has no effect in subworkflows

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#7965]
version 19.05
It seems to have no effect when the tool is flagged as the output of a subworkflow.
The subworkflow reports the output type as `data` despite being set to `newick` in the tool.
This prevents connections to other tools.

**Comment by mvdbeek** [comment]
Just to confirm, this is via the `Configure Output` -> `Change datatype` post job action, right ?

**Comment by innovate-invent** [comment]
Yup
