### ISSUE TITLE
Feature Request: Run rule builder on data in history

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#7968]
So the rulebuilder is great and I'd love to be able to use this, but some of my datasets are only stored locally (or available in my history.)

I'd rather not upload these datasets somewhere to be able to use this feature to rename + tag + organise uploaded datasets.

Edit: this can be done by creating a list of datasets, and applying rules to dataset collection, but it would be nice if there was a simpler option as well maybe?

Edit 2: this apply to existing, misses the ability to add group/name tags.

**Comment by jmchilton** [comment]
"Operations on Multiple Datasets" -> Select Datasets -> "For all selected..." -> "Build Collection from Rules" is available... but you don't want to "collect" the datasets, you want to bulk edit them I take it? I had never considered that but it sounds reasonable. Our bulk edit API is very new and doesn't do any of the stuff we'd need yet and rule builder itself would need some real work - but I like the idea.

**Comment by hexylena** [comment]
Ok, build collection from rules would work in that specific case, but exactly, it wasn't necessary to "collect" the datasets, just sort of bulk editing/tagging based on name.

yeah, exactly, just an idea that might be interesting for end users. In the end I could upload to FTP and this worked well for my case.

**Comment by hexylena** [comment]
Closing this, bulk operations are available / can just operate on collections
