### ISSUE TITLE
Cannot manage new empty repository on TTS

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#7973]
Just created a new, empty repository on the TTS.  The repo was created, but immediately the following message was displayed.  Now when I click on the repository link to try to upload files, the same message is displayed.
```
The Tool Shed could not be reached

You are seeing this message because a request to The Tool Shed timed out or was refused. This may be a temporary issue which could be resolved by retrying the operation you were performing. If you receive this message repeatedly or for an extended amount of time, please contact an administrator.
```

**Comment by martenson** [comment]
The machine is out of space, we are trying to remedy this. I will post here when I know more.

**Comment by gregvonkuster** [comment]
Awesome - thanks a bunch @martenson .  I was trying to bug @davebx directly on this earlier this AM, but figured it'd be more appropriate to use this process.  :)

**Comment by martenson** [comment]
It should be better now, I will push again for a more reliable remedy. Thanks for reporting.
