### ISSUE TITLE
Job Search/cache  not finding equivalent BWA, bowtie and other mappers jobs

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#7975]
Been playing around with the job caching ability that @mvdbeek has implemented a few releases ago and works very well for most of our tools.

Only exception is that all mapper tools will never find their equivalent job. To my knowledge is looks like the issue is that the job_to_input_dataset table is not matching up with the name column for datasets.

Below is JSON values of parameters being checked. What is  NOT matching in the table is **fastq_input1** and **ref_file** values. So either we have to add _input_type_ and _reference_source_ into the job_to_input_dataset table or remove it from JSON when searching. 

`{**'name_2': 'input_type|fastq_input1'**

 'name_3': 'analysis_type'

 **'name_1': 'reference_source|ref_file'**

 'name_6': 'input_type'

 'tool_version_1': '0.7.17.4'

 'name_4': 'reference_source'

 'name_5': 'rg'

 'state_1': 'new'

 'state_3': 'waiting'
 'state_2': 'queued'
 'state_5': 'ok'
 'state_4': 'running'
 'value_4': '{"\__current_case__": 2
 "adv_se_options": {"\__current_case__": 1
 "adv_se_options_selector": "do_not_set"}
 "fastq_input1": {"values": [{"id": %
 "src": "hda"}]}
 "input_type_selector": "single"}'
 'value_1': '{"\__current_case__": 0
 "analysis_type_selector": "illumina"}'
 'value_3': '{"\__current_case__": 3
 "rg_selector": "do_not_set"}'
 'value_2': '{"\__current_case__": 1
 "index_a": "auto"
 "ref_file": {"values": [{"id": %
 "src": "hda"}]}
 "reference_source_selector": "history"}'
 'tool_id_1': 'toolshed.g2.bx.psu.edu/repos/devteam/bwa/bwa/0.7.17.4'
 'dataset_version_1': 0
 'dataset_version_2': 0
 'param_1': 1
 'id_2': 9
 'id_1': 4}
`  
 

---------------------------------------------------------------

 id  | job_id | dataset_id |     **name**     | dataset_version 
-----+--------+------------+--------------+-----------------
 269 |    125 |          4 | **ref_file**       |              90
 270 |    125 |          9 | **fastq_input1** |              13

**Comment by Takadonet** [comment]
Looks like [shovill](https://toolshed.g2.bx.psu.edu/view/iuc/shovill/865119fcb694) also does not work. Issue probably the nested input sets.

**Comment by hellothisisMatt** [comment]
Awesome job @mvdbeek. Glad I could help!
