### ISSUE TITLE
Feature request: Access to current user's API key

### ISSUE THREAD

**Issue by jancrichter** [galaxyproject/galaxy#7981]
Hello,

for the purpose of using the API from within tools it would be very useful to be able to supply the current user's API key to a tool. I can see that this is possible from within Interactive Envrionments, but from within tools would be of much use.

Possible use cases:

* Calling other tools/workflows when executing a tool
* Manipulating items in current user's history
* Transferring history items to a remote location
* all the range of functionality offered by the API

Best regards

**Comment by hexylena** [comment]
Hi @jancrichter, this is already possible if you know where to look. The following can be used in your tool code block:

```
$__user__.obj.api_keys[0].key
```

I would guess that it is not really encouraged to be done.
