### ISSUE TITLE
tool version of subworkflows within workflows not updated

### ISSUE THREAD

**Issue by jancrichter** [galaxyproject/galaxy#7982]
Hello,

when a tool version used in a workflow becomes unavailable, but a newer version of the tool is present, this is automatically used and the user informed about this. For subworkflows within such a workflow the `tool_id` field of the tool is updated but the `tool_version` field is not. This results in the workflow not finding the tool that the subworkflow is looking for. Changing the `tool_version` field to the correct version was sufficient to resolve the issue.

**excerpt form the workflow JSON:**

```
...
"13": {"tool_id": "REPO_LOCATION/REPO_NAME/TOOL_NAME/0.1.1", 
         "tool_version": "0.1",
...
```

Best regards

**Comment by davelopez** [comment]
The inconsistency with `tool_version` was addressed in https://github.com/galaxyproject/galaxy/pull/14701 so I will close this now.
Please feel free to reopen or create a new issue if needed. Thanks!
