### ISSUE TITLE
Tool run uses ellipses slightly too soon

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#7984]
With 4 items probably makes sense to print all four since there's room for 3 + ellipsis? And only if ≥5 then use ellipses

![image](https://user-images.githubusercontent.com/458683/57848046-3eb1ed00-77d8-11e9-931b-62a349eabd86.png)

**Comment by dannon** [comment]
Somewhat jokingly, you could do "Well, if there's room for N+ellipsis" forever, right?

Concretely, should we just always display *all* the outputs for a single tool execution that are known at runtime?  The middle panel can scroll.

**Comment by martenson** [comment]
>display all the outputs for a single tool execution that are known at runtime? The middle panel can scroll.

:+1:

**Comment by WilliamHolden** [comment]
> Concretely, should we just always display _all_ the outputs for a single tool execution that are known at runtime? The middle panel can scroll.

Sounds good to me. As long as there are no objections, I will update the pr to include this functionality

**Comment by WilliamHolden** [comment]
PR updated and ready for review https://github.com/galaxyproject/galaxy/pull/8018
