### ISSUE TITLE
Button to log out all other sessions (+ session / ip list)

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#7988]
E.g.:

![image](https://user-images.githubusercontent.com/458683/57865077-3ae49180-77fd-11e9-9bcd-cfec985c00f6.png)

**Comment by blankenberg** [comment]
Just FYI, I added the ability to sign out all sessions previously, but an overall activity page might not be a bad idea, and also allow signing out all others but the current one.
<img width="320" alt="Screen Shot 2019-05-16 at 11 14 08 AM" src="https://user-images.githubusercontent.com/1231190/57865570-d3fab480-77cb-11e9-8171-73c18f21b176.png">

**Comment by hexylena** [comment]
Oh, Useful! I think I never read the grey text, and just saw "sign out".

Op do 16 mei 2019 17:20 schreef Daniel Blankenberg <notifications@github.com
