### ISSUE TITLE
Stability of Toolshed search requests

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#7996]
![firstfailure](https://user-images.githubusercontent.com/2105447/57924688-d1ec3080-7873-11e9-8384-62147b335746.png)
![secondfailure](https://user-images.githubusercontent.com/2105447/57924694-d7497b00-7873-11e9-9c9c-c20dd37fe09a.png)

**Comment by martenson** [comment]
Sheds are out of space again. :/

**Comment by mvdbeek** [comment]
This seems stable now, feel free to re-open if it happens again.
