### ISSUE TITLE
Enhance History functions "Operations on multiple datasets" to include Edit Attributes functions (esp reassign/redetect datatype)

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#8013]
**Note: If just made reassigning datatype in batch possible, that alone would be a big win.**

Branched off from comments here:  https://github.com/galaxyproject/galaxy/issues/3195 
 >> https://github.com/galaxyproject/galaxy/issues/3195#issuecomment-261427643

Discussion

GTN Gitter: https://gitter.im/Galaxy-Training-Network/Lobby?at=5ce4307cb313d7231404f1b4 (scroll up for context)

GTN: Tuto feedback https://github.com/galaxyproject/training-material/issues/989#issuecomment-494162268

GHelp: https://help.galaxyproject.org/t/convert-from-bam-to-fastq/1318/11?u=jennaj

**Comment by mblue9** [comment]
Thanks @jennaj! Would be great to be able to edit attributes in batch. We ran into this issue in training and in our case we only had small datasets but for users with normal/large files being able to edit attributes in batch without having to do a re-import would be very helpful.

dbkey would be another good one to be able to change in batch as if users want to use featurecounts built-in genomes e.g. mm10 but have selected the wrong dbkey or haven't selected a dbkey at all then they have to do the manual one-by-one editing of each dataset to change the dbkey (sometimes I've done the one-by-one editing for them as I don't like getting them do it because it's makes Galaxy seem silly).

**Comment by jennaj** [comment]
few other issues that are related, all link from this one. just linking it all up. looks like many have had the same ideas around this :)

https://github.com/galaxyproject/galaxy/issues/1136

@mblue9 for dbkey 👍 👍 👍

**Comment by hexylena** [comment]
batch adding of tags would be nice too!

**Comment by jennaj** [comment]
**This ticket:**

1. Find/replace/add/remove for all also nice to have (labels eg tags/info/annotation + metadata)

2. Full + "parts of" when that makes sense 

3. Include variables to capture the content of existing, specific metadata/label types

4. Use that to modify the same metadata/label PLUS apply it to other types

5. Allow complex/multiple changes per query

Psudeo example. Could be a GUI form with preset syntax options (pull-down menus)

>  [ find ($dbkey=="hg38") | add ($tag=="#some-"$dbkey"-other-info")` | replace ($info==$info/n"More useful info related to "$dbkey" and whatever else" ]

**Related:** Don't think any of these have tickets but the first one should be done anyway if tags are made batch editable. 

1. Tags should be on the existing `Edit Attributes` forms too -- probably the first tab. If tags are batch editable on an "Operate on multiple datasets > Edit Attributes" form, should also be available for individual datasets on "pencil > Edit Attributes" form.

2. Tags would also be great on `Upload` for non-rule-based file loads (rule-based includes this.. I think)

3. Log ALL metadata/label changes + timestamps somewhere accessible in the GUI with an "edit version". Pull-down menu to "revert" to a prior state would be a huge bonus. Be able to hide versions but never remove them -- are an important artifact to preserve IMO. For this usage and other reasons in general.

4. "Job info" view should capture which version of a dataset was used for that specific run. Same as tool version.

5. "Rerun" should bring up the tool from selecting the original input version (reproducibility) but user should be able to select alternative versions, with the "lastest" clearly marked. _Warn if not using the latest version of a dataset_ -- same as for tool versions

**Comment by jennaj** [comment]
Related: Changing datatype of collections: https://github.com/galaxyproject/galaxy/issues/12725

**Comment by davelopez** [comment]
xref #13877

**Comment by mvdbeek** [comment]
We got this now: https://github.com/galaxyproject/galaxy/pull/13877
