### ISSUE TITLE
object_store_conf.xml.sample contains invalid xml

### ISSUE THREAD

**Issue by simpsonw** [galaxyproject/galaxy#8014]
The sample configurations for the various cloud providers (Amazon S3, Azure Blob, etc) in object_store_conf.xml.sample have comments in them that explain that the size for the cache is in gigabytes:

```
        <!-- Cloud ObjectStore: Amazon Simple Storage Service (S3) -->
        <!--
        <object_store type="cloud" provider="aws" order="0">
            <auth access_key="..." secret_key="..." />
            <bucket name="..." use_reduced_redundancy="False" />
            <cache path="database/object_store_cache" size="100" /> <!-- size is in gigabytes -->
            <extra_dir type="job_work" path="database/job_working_directory_s3"/>
            <extra_dir type="temp" path="database/tmp_s3"/>
        </object_store>
        -->
```
The problem is that these sections are commented out by default.  So if you copy `object_store_conf.xml.sample` to `object_store_conf.xml` and uncomment the section you want to use, Galaxy will be unable to parse the configuration file since it contains nested comments, which are invalid in XML.

**Comment by bernt-matthias** [comment]
Seems to be solved by https://github.com/galaxyproject/galaxy/pull/8016 .. close?

**Comment by nsoranzo** [comment]
Yep, thanks @simpsonw and @bernt-matthias !
