### ISSUE TITLE
subworkflow messes up job dependencies

### ISSUE THREAD

**Issue by cgirardot** [galaxyproject/galaxy#8026]
I have a simple subworkflow situation which I believe is a very simple but useful use case for many people: from a table of SRA accession, it downloads dozens of chip-seq samples and performs basic processing.

Tests made on usegalaxy.eu today .

# Background 
The subWF is a basic ChIP-seq and accepts a table describing fastq files by SRR accession, all of which are technical replicates of the same sample (identical SRX for all).  The WF fecthes fastq files from SRA, map and filter reads individually for each tech rep, merge all bams into a single one, remove dupes and generate a bigwig coverage file for visualization. 

The main WF accepts a table with many samples (SRX accession) like : 

|SRX|SRR
|----|----
|SRXA|SRR1
|SRXA|SRR2
|SRXB|SRR3
|SRXB|SRR4

splits this by column based on SRX and call the ChIP-seq with each resulting SRX-table. 

Here are screenshots to help you get the situation:

## Main WF
<img width="946" alt="mainWF" src="https://user-images.githubusercontent.com/10990795/58271221-d80a7180-7d8b-11e9-9390-e7ef328b5d05.png">

## Sub WF
<img width="1482" alt="chipseq_subworkflow" src="https://user-images.githubusercontent.com/10990795/58271224-dccf2580-7d8b-11e9-88a3-5ac615162fe4.png">

# Problem 

As shown on the screenshots below, when the subworflow starts, later steps are executed almost directly while fastq downloads haven't even started ()! Of course everything fails....

<img width="290" alt="Execution_step1" src="https://user-images.githubusercontent.com/10990795/58271394-3cc5cc00-7d8c-11e9-8119-0649512e9b18.png">

<img width="296" alt="Execution_failed" src="https://user-images.githubusercontent.com/10990795/58271414-45b69d80-7d8c-11e9-90a0-acc5a387b86f.png">

Please let me know if I am missing something here...

**Comment by mvdbeek** [comment]
Probably fixed by https://github.com/galaxyproject/galaxy/pull/7633, but not sure if usegalaxy.eu has updated to that commit already. Any chance you could try this on usegalaxy.org ?

**Comment by mvdbeek** [comment]
Yep, usegalaxy.eu is a little behind the release_19.01 branch, so that will be fixed soon.

**Comment by cgirardot** [comment]
Full of hopes we updated our local galaxy this morning, I am afraid subworkflows still suffers from many issues preventing the use of this feature. Below is the list of the different issues I found. 

First, what I did.

I run the WF with a table containing 5 rows (plus 1 header row) describing 3 SRX with 2+2+1 SRR. So 5 fastq to be processed in total, which would results in three bigwig in the end. 
Although the behavior looked better, it still fired late job too soon. 
 
<img width="286" alt="job still ahead" src="https://user-images.githubusercontent.com/10990795/58314398-b6eb6480-7e0f-11e9-96df-7e650851e27f.png">


I then slightly modified the workflow to see if this was due to reconverting a dataset into a list  (`Build List` step at the end). With the modified subworkflow (see below) it runs till the end. Note that the subworkflow now includes renaming/tagging steps before we copy the datasets to our NFS (`Dataset Exporter` step, a local tool soon in the toolshed). Of course, the subworkflow works like a charm in "conventional" use. 

<img width="1896" alt="subwf" src="https://user-images.githubusercontent.com/10990795/58313902-e9489200-7e0e-11e9-8c14-86ac71496cee.png">

What happens : 

It starts great and execution now waits the downloads to complete. Inspecting the result of the download step gives me the expected 5 files. 

<img width="288" alt="Screenshot 2019-05-24 at 10 43 56" src="https://user-images.githubusercontent.com/10990795/58314941-d8991b80-7e10-11e9-8fa7-11e26479ac5f.png">


but then I noticed that the number of jobs were not correct as I have 3 times more jobs than needed eg galaxy launches 15 trim galore jobs (I did have 15 trim galore running on the cluster) instead of 5 ! After the BAM merge occurred, the WF launches 9 jobs instead of 3. 

<img width="611" alt="great flow" src="https://user-images.githubusercontent.com/10990795/58314766-7a6c3880-7e10-11e9-8d7d-d8af28b31f8b.png">

Still the WF did complete but one step: the Dataset Exporter. Actually of the 3 Dataset Export steps, only one was instantiated. We are not sure what is happening here. 

Finally, the list structure produced is weird ie .
- Download result is fine : first level named after the SRX, second level the SRR ; as expected 

<img width="629" alt="downloads_list_struct" src="https://user-images.githubusercontent.com/10990795/58315784-76411a80-7e12-11e9-80a3-2c14ed7d3dbf.png">

- Trim Galore results (and next) have a level too much IMO

<img width="1176" alt="screwed_nesting" src="https://user-images.githubusercontent.com/10990795/58316099-172fd580-7e13-11e9-9372-b92651270f9f.png">

- I have doubts that the BAM merging operate on the right files ; the UI actually gives me an error when I try to chech the info tab (which would give me the command line) and bringing up the "rerun" panel has nothing in the input selector 

<img width="1209" alt="Screenshot 2019-05-24 at 11 02 00" src="https://user-images.githubusercontent.com/10990795/58316227-5cec9e00-7e13-11e9-95e1-9468b1a4d843.png">

**Comment by mvdbeek** [comment]
> it still fired late job too soon.

At what step do you think something ran too early ?

I'm having a hard time following this example. Could you narrow the description down to what you think went wrong and show only the relevant steps ?

**Comment by cgirardot** [comment]
OK, sorry for the complex post. 
- First picture. `Build List`  which results in the error on dataset 275 => this was executed while trim galore was running. 

Anyway, I think I understand what is going on: as soon as my subworflow contains a step operating on collection i.e.  `Build List` or `Relabel List Identifiers`, things get screwed.  
I have now run a simplified version of my workflow (see below) i.e. **no `Relabel List Identifiers` after the download**. And this now runs fine, proper number of jobs and my collections properly have 2 levels.

<img width="1251" alt="Screenshot 2019-05-24 at 11 39 29" src="https://user-images.githubusercontent.com/10990795/58318694-9a9ff580-7e18-11e9-95e8-e634567a6ce1.png">

<img width="287" alt="Screenshot 2019-05-24 at 11 26 53" src="https://user-images.githubusercontent.com/10990795/58318778-c4f1b300-7e18-11e9-9fa8-a657333defba.png">

hope this is clearer

**Comment by mvdbeek** [comment]
OK, I think I see. This is probably not related to subworkflows, it's the discovery of output collections that are immediately fed into collection operation tools. I suspect this would work fine if you place the label identifier from file tool after trim galore. If that's true we just need to delay the collection operation tools until all collections are finalized.

**Comment by cgirardot** [comment]
tried to move the renaming as suggested : same effect. The renaming steps screws the nested structure (3 levels instead of 2). 

<img width="293" alt="Screenshot 2019-05-24 at 13 05 21" src="https://user-images.githubusercontent.com/10990795/58323659-e6f13280-7e24-11e9-9ee9-2398eb4e38f2.png">

**Comment by mvdbeek** [comment]
Can you upload the workflow that works and the one that doesn't ?

**Comment by mvdbeek** [comment]
Ah, wait a second, there's an unequal number of datasets in the lowest level, right ? if you remove the accession that only contains one dataset does it work correctly (with the renaming step)?

**Comment by cgirardot** [comment]
in the arch, you have the 2 subworkflows + a template for the meta WF (you still need to inject the usbworkflow) and the starting table of accessions

[testdata.zip](https://github.com/galaxyproject/galaxy/files/3216585/testdata.zip)

**Comment by mvdbeek** [comment]
Where and how are you testing this again ?
I tried this on a local 19.05 instance and it works correctly, including the rename step.
I limited the download to the first 2 spots since it'd take forever to test, and I replaced the awk tool with a regex.
https://gist.github.com/mvdbeek/0fed5eb2824052febcb61f17c35b4373

![Screen Shot 2019-05-24 at 15 04 24](https://user-images.githubusercontent.com/6804901/58329739-89b1ad00-7e35-11e9-9fa3-d6c514c2c0ed.png)

**Comment by cgirardot** [comment]
I am testing this on local galaxy that we updated this morning. 
The workflow runs fine if not used as a subworflow. Have you tried it as a subworkflow ?

**Comment by mvdbeek** [comment]
not at the time, but I tried it now, no difference, still works. Which makes sense, the weird thing happens inside the subworkflow.
![Screen Shot 2019-05-24 at 15 18 29](https://user-images.githubusercontent.com/6804901/58330492-435d4d80-7e37-11e9-96e6-394614e63121.png)

**Comment by mvdbeek** [comment]
OK, so you've got the split file part in the parent workflow. I see it now.

**Comment by cgirardot** [comment]
but you are not testing it the same way as I do. Please look at the very first pictures I posted. The whole point is about to split the table by SRX in the main WF (resulting in a list of tables) and call the subworkflow on each of the generated table. And the main goal of using subworkflow here is that at the end of the workflow, I collapse all BAM into one.

**Comment by cgirardot** [comment]
exactly

**Comment by cgirardot** [comment]
@scholtalbers  just told me we are on 19.01

**Comment by mvdbeek** [comment]
OK, this is unrelated to the subworkflow, I get the same issue if I include the split file step in the main workflow. The datasets actually get multiplied at the relabel step, which doesn't make much sense.

**Comment by cgirardot** [comment]
will you re-open the issue or submit a new one more focuses?

**Comment by mvdbeek** [comment]
I will open a new issue, but we've already discussed this some time ago on gitter. This doesn't neatly fit  into Galaxy's model of how data flows, unless there's a heuristic we can use. FWIW you can make this workflow work by adding a step that concatenates multiple datasets into a single datasets for the identifiers, which will prevent mapping over the relabel step:

<img width="872" alt="Screen Shot 2019-05-24 at 17 34 47" src="https://user-images.githubusercontent.com/6804901/58339632-51689980-7e4a-11e9-8311-b2d72973ea37.png">


Ultimately I think we want to be able to scale up a workflow by nesting the input datasets deeper. This mostly works but there are a few sharp edges still, one of which is this issue.

**Comment by cgirardot** [comment]
Sorry but I don t see how this addresses what I am trying to do.
My goal is to merge BAMs of many technical replicates (same SRX) together, after the bowtie step.  
Did I miss something here ?

**Comment by mvdbeek** [comment]
Your issue is that you get an additional nesting level because the label identifiers are one per file. If you collapse that to a single file you don't get the additional level and all should work fine. Just give it a go.

**Comment by cgirardot** [comment]
I'll try. In the meantime, please try to add a MergeSamFiles step after the bowtie2 and you ll understand my problem.

**Comment by mvdbeek** [comment]
I just launched your exact workflow (meta with the workflow that doesn't work but with an additional collapse step) on usegalaxy.eu: https://usegalaxy.eu:/u/m.vandenbeek/h/split-subworkflow-demo

We'll see what happens but I think this should work.

**Comment by mvdbeek** [comment]
arg, the awk tool doesn't work there

**Comment by cgirardot** [comment]
the concatenate step as instructed has strictly no effect, the structure of the output is like the input.
Nevertheless, this concatenate gave me an idea : adding a `Collapse Collection `  step after the download. It seems to properly cat the SRR fastq files together and give me a list a 3 datasets. About to try this

**Comment by mvdbeek** [comment]
> the structure of the output is like the input.

Except when the outer input is already a collection. In which case the input will be mapped over. I tested this, and it does indeed solve the problem of 15 instead of 5 jobs.

**Comment by cgirardot** [comment]
The workflow editor does not let me make a connection to the Collapse step ...
<img width="1542" alt="Untitled" src="https://user-images.githubusercontent.com/10990795/58343073-6ea16600-7e52-11e9-9396-f27f1f5a7da4.png">

**Comment by cgirardot** [comment]
> > the structure of the output is like the input.
> 
> Except when the outer input is already a collection. In which case the input will be mapped over. I tested this, and it does indeed solve the problem of 15 instead of 5 jobs.

which concatenate did you use ? The one 1.0.0 or the one that says `(cat)` and has a version 0.1.0 ?

**Comment by mvdbeek** [comment]
0.1.0, the other one is not a `multiple="true"` input

**Comment by cgirardot** [comment]
OK we are on the same page(no multiplication of jobs), except that the Renaming step ...did not rename the collection. And even if it did, I still cannot merge my BAM by SRX...back to my comment : my goal is to merge techinical replicates... 
Interactively, I can collapse the downloaded fastq by SRR but the workflow editor does not let me insert this step (see above). Any idea why ?

**Comment by cgirardot** [comment]
@mvdbeek have you noticed my last comment/question about running the `Collapse Coolection` tool on the SRA downloaded collection (a list of list ) => the result is indeed what I need as it collapses the collection as I need :

- SRA SE List : 
   - SRX1
      - SRR1
      - SRR2
   - SRX2
      - SRR3
      - SRR4

becomes a list as : 
- Collapsed collection : 
   - SRX1 (cat of SRR1 + SSR2)
   - SRX2 (cat of SRR3 + SSR4)

Problem : I cannot hook this tool after the SRA download in the WF. Is this a bug ? This would solve my whole issue.

**Comment by mvdbeek** [comment]
Yeah, that's been fixed in the 19.05 dev cycle, https://github.com/galaxyproject/galaxy/pull/7435
This is a little too complicated to backport to 19.01.

**Comment by cgirardot** [comment]
great! do you already know when 19.05 will be officially released ? thx
