### ISSUE TITLE
__TAG_FROM_FILE__ cannot use #named:tags

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#8033]
On 19.01
It seems one cannot use the tool "Tag elements from file"/`__TAG_FROM_FILE__` to tag datasets with named tags. See also https://lists.galaxyproject.org/archives/list/galaxy-dev@lists.galaxyproject.org/thread/TBF6KDBKQ7RSVZBKXSAIPP2UC545UVYU/

Related, through the UI it looks one is allowed to add a `tag:name` (without `#`) but reloading the history shows that no label was saved..

**Comment by mvdbeek** [comment]
`#` is shorthand for `name:`. Only name tags are displayed in the history overview. If you want to see tags without name (like group tags) you need to click on a dataset and look at the associated tags.

If you want to add name tags with the tag from file tool you need to use the `name:value` form

**Comment by scholtalbers** [comment]
> `#` is shorthand for name:

that I didn't know, now it indeed seems to work! Thanks Marius

**Comment by mvdbeek** [comment]
We can still improve this, if a tag starts with `#` we can treat that as `name:`

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/8038, I'll open a PR against 19.05
