### ISSUE TITLE
Setting up pycharm - request for help

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#8052]
Hi there,

I would like to setup Pycharm to run Galaxy, so that I can run in debug mode for instance for the python part. When we used to use the old paster.py it was easy to setup on Pycharm, but now with the more decomposed setup, is not very clear to me how you would do this. Anyone developing Galaxy on Pycharm?

Thanks!

**Comment by martenson** [comment]
I think @mvdbeek does.

**Comment by mvdbeek** [comment]
I do, but I'm still using paste and galaxy.ini:
![image](https://user-images.githubusercontent.com/6804901/58560478-8186b280-8225-11e9-8acd-6fb422bfa7a2.png)

This could also be made to work with tornado or any other WSGI python server, but not uwsgi, I think.

**Comment by mvdbeek** [comment]
https://stackoverflow.com/a/27463713 might be a path forward, but it's not as simple. If you're not actually debugging uwsgi-specific features (atm I think that's only mules) using paste is far easier.

**Comment by pcm32** [comment]
Thanks @mvdbeek!

**Comment by martenson** [comment]
many devs now run vscode and gunicorn which work quite nicely together

**Comment by ksuderman** [comment]
If anyone else comes across this after Googling and would like to actually use PyCharm this is my setup that seems to work. You may want to tweak the environment variables to your liking.  I have:

```
PYTHONUNBUFFERED=1
GALAXY_SKIP_CLIENT_BUILD=1
GALAXY_CONFIG_FILE=/path/to/your/galaxy.yml
```
Of course, you will need to change `GALAXY_CONFIG_FILE` to the path of your config file as well as setting the `Working directory` to the root of the Galaxy source tree.

<img width="811" alt="Image" src="https://github.com/user-attachments/assets/c6d64640-0bb7-4e3b-83b6-cd8ad16c7ce4" />
