### ISSUE TITLE
Account registration in 19.05 pre-release missing account terms

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#8066]
<img width="771" alt="Screen Shot 2019-05-29 at 8 17 12 AM" src="https://user-images.githubusercontent.com/8999735/58668350-75662800-82ed-11e9-9358-5e5a4f667957.png">

ping @jmchilton

**Comment by jennaj** [comment]
Tracked here: https://github.com/galaxyproject/usegalaxy-playbook/projects/2#column-5163771

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/pull/8185

**Comment by dannon** [comment]
This is fixed in #8951
