### ISSUE TITLE
Dynamic Watching and Reloading of a subset of config.py

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#8072]
Break ``config.py`` into a subset of variables that can safely be reloaded after app start -``message_box_content``, ``admin_users``, ``cleanup_job``, and ``welcome_url``. A monitor task should be added to monitor the config file for changes and reloading these.

Potentially relevant xrefs:
- https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/config_watchers.py
- https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config.py
- https://github.com/galaxyproject/galaxy/pull/4617/files
- https://github.com/galaxyproject/galaxy/pull/6215

For the variables we that are updated to do this - we should make sure they aren't cached on objects (``self.admin_users = app.config.admin_users`` - they always need to be accessed through the ``config`` object - or some cool proxy thereof).

---

Discussion:

@natefoo Any chance I could convince you to add to the "main tasks" making a dynamically changeable masthead banner?

@jmchilton
Next week of course and certainly!
How do you want it to work?

@natefoo
Either watching (via fs events) a file on disk or something in the UI
(open to suggestions)

@jmchilton
All the plumbing for a masthead is already there right? We just need to change it? We could do that

@natefoo
Yeah, currently it's done via the config file though, so changing it requires a restart

@jmchilton
``message_box_content``
Alright. I'll sketch something out and assign it, perfect

@natefoo
Awesome sauce

**Comment by martenson** [comment]
could we please add tool panel search related configs?
```
  #tool_name_boost: 9.0
  #tool_section_boost: 3.0
  #tool_description_boost: 2.0
  #tool_label_boost: 1.0
  #tool_stub_boost: 5.0
  #tool_help_boost: 0.5
  #tool_search_limit: 20
  #tool_enable_ngram_search: false
  #tool_ngram_minsize: 3
  #tool_ngram_maxsize: 4
```

**Comment by jmchilton** [comment]
@martenson That requires rebuilding the search index though I think, I like the idea but it requires more plumbing to issue a callback on changed values or something - so I'd prefer to defer that to an iteration 2.

**Comment by martenson** [comment]
@jmchilton boosts are attributes of the search instance, not the index creation

**Comment by jmchilton** [comment]
Sounds easy enough then, thanks @martenson !

**Comment by jdavcs** [comment]
Could someone please take a quick look at https://github.com/galaxyproject/galaxy/pull/8230 and see if this is overall a reasonable approach? If so, I'll add tests (I didn't do test first intentionally) and it'll be be ready. Thanks!

**Comment by jdavcs** [comment]
Closing: completed. Ref: https://github.com/galaxyproject/galaxy/pull/8475
