### ISSUE TITLE
Search histories broken on the multi-history view

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#8084]
I can't retrieve an history on multi-history view when using the search box "search histories"

The "search all datasets" works.

Tested on galaxy.org / galaxy.eu and our 19.01 Galaxy.

It works on our former 17.09 Galaxy.

**Comment by mvdbeek** [comment]
Yep, thanks for the report. That's been broken for a long time

**Comment by FredericBGA** [comment]
Thank you @mvdbeek . This is not a big deal but as we have given access to a new 19_01 galaxy interface to our users, I have users that talk to me about all this little things.

**Comment by martenson** [comment]
@FredericBGA Thank you very much for reporting those, we appreciate it.

**Comment by dannon** [comment]
Should have a fix for this shortly; I see what's going on.
