### ISSUE TITLE
Tool Command Isolation

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#809]
There is a beta option - `enable_beta_tool_command_isolation` that separates the tool command environment from the metadata collection environment in jobs so that they can have independent dependencies.

It is still in beta but at some point it should be the default. This issue is tracking progress toward that.
- [x] From @bgruening "Is it worth to include requirement tags into all converters and try/except around the `import egg` lines?".
- [ ] The metadata evaluation should probably source samtools and bcftools env files if available.

**Comment by jmchilton** [comment]
@bgruening - I guess there are going to be subset of tools that really just need Galaxy's dependencies, maybe we should just hard code a list and skip isolation on these or add a tag to the tools `inherit_galaxy_environment="true"`.

`enable_beta_tool_command_isolation` still causes Galaxy to be added to the Python path though right? I'm not sure why this would cause an error for the converters.

**Comment by bgruening** [comment]
> @bgruening - I guess there are going to be subset of tools that really just need Galaxy's dependencies, maybe we should just hard code a list and skip isolation on these or add a tag to the tools `inherit_galaxy_environment="true"`.

I thought about this as well, but for all Tools that are not from the TS. This check should avoid a white/black list.

> `enable_beta_tool_command_isolation` still causes Galaxy to be added to the Python path though right? I'm not sure why this would cause an error for the converters.

Not sure about this.
`docker pull bgruening/galaxy-deeptools` based on https://github.com/bgruening/docker-recipes/blob/master/galaxy-deeptools/Dockerfile failed as soon as you try to convert interval to BED for example.

**Comment by bgruening** [comment]
@jmchilton maybe this is just a bug in `:dev` I can not run these tools in all dev versions regardless of this parameter. 

`docker run bgruening/galaxy-stable:dev` is not working
`docker run bgruening/galaxy-stable` is working

```
Traceback (most recent call last):
  File "/galaxy-central/lib/galaxy/datatypes/converters/interval_to_bed_converter.py", line 6, in <module>
    pkg_resources.require( "bx-python" )
  File "/galaxy-central/lib/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/galaxy-central/lib/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: bx-python
```

**Comment by bgruening** [comment]
I'm testing right now, but I'm confident this bug is solved now. Will update soon.

**Comment by bgruening** [comment]
I think this is fixed now. Thanks!

**Comment by jmchilton** [comment]
Reopening and just checking that one bug off - we still need to figure this out and deal with adding samtools and bcftools to the metadata generation environment.

**Comment by blankenberg** [comment]
Was going to open a new issue, but this also falls under this topic. We should be sure to work towards preventing filesystem pollution of the job working directory. 

For example: https://github.com/bgruening/galaxytools/commit/f883575df0bc5244421e85917b9d2b472000621c was needed due to the presence of `galaxy_1234.sh` and `set_metadata_XYZPWE.py`. Otherwise just scooping up the job working dir would have worked perfectly.

Another file to consider would be `galaxy.json` as passed to tools.

First thought would be to have some sort of directory hierarchy with the job working dir at a leaf.

**Comment by jmchilton** [comment]
@blankenberg Created a separate issue for your idea here https://github.com/galaxyproject/galaxy/issues/1575.
