### ISSUE TITLE
KubernetesJobRunner, error for specifying requests_memory 

### ISSUE THREAD

**Issue by markxiao** [galaxyproject/galaxy#8121]
Hi, I was using 19.05, and was trying its KubernetesJobRunner. It seems Galaxy cannot recognize parameter requests_memory. The job_conf.xml looks like this:
`
    <plugins>
        <plugin id="local" type="runner" load="galaxy.jobs.runners.local:LocalJobRunner" workers="4"/>
        <plugin id="k8s" type="runner" load="galaxy.jobs.runners.kubernetes:KubernetesJobRunner" workers="1">
            <param id="k8s_config_path">/home/galaxy/.kube/config</param>
            <param id="k8s_persistent_volume_claims">mnt-pvc:/mnt</param>
            <param id="requests_cpu">3500m</param>
            <param id="requests_memory">15Gi</param>
            <param id="k8s_supplemental_group_id">4000</param>
            <param id="k8s_fs_group_id">4000</param>
        </plugin>
    </plugins>
`
And got the following error in the log:

galaxy.jobs.runners DEBUG 2019-06-09 03:21:52,418 [p:14839,w:0,m:0] [MainThread] Loading KubernetesRunner with params: {'requests_memory': '15Gi', 'k8s_config_path': '/home/galaxy/.kube/config', 'requests_cpu': '3500m', 'k8s_fs_group_id': '4000', 'k8s_persistent_volume_claims': 'mnt-pvc:/mnt', 'k8s_supplemental_group_id': '4000'}
Traceback (most recent call last):
  File "lib/galaxy/webapps/galaxy/buildapp.py", line 49, in app_factory
    app = galaxy.app.UniverseApplication(global_conf=global_conf, **kwargs)
  File "lib/galaxy/app.py", line 204, in __init__
    self.job_manager = manager.JobManager(self)
  File "lib/galaxy/jobs/manager.py", line 26, in __init__
    self.job_handler = handler.JobHandler(app)
  File "lib/galaxy/jobs/handler.py", line 50, in __init__
    self.dispatcher = DefaultJobDispatcher(app)
  File "lib/galaxy/jobs/handler.py", line 941, in __init__
    self.job_runners = self.app.job_config.get_job_runner_plugins(self.app.config.server_name)
  File "lib/galaxy/jobs/__init__.py", line 599, in get_job_runner_plugins
    rval[id] = runner_class(self.app, runner['workers'], **runner.get('kwds', {}))
  File "lib/galaxy/jobs/runners/kubernetes.py", line 69, in __init__
    super(KubernetesJobRunner, self).__init__(app, nworkers, **kwargs)
  File "lib/galaxy/jobs/runners/__init__.py", line 660, in __init__
    super(AsynchronousJobRunner, self).__init__(app, nworkers, **kwargs)
  File "lib/galaxy/jobs/runners/__init__.py", line 83, in __init__
    self.runner_params = RunnerParams(specs=runner_param_specs, params=kwargs)
  File "lib/galaxy/util/__init__.py", line 1101, in __init__
    self._param_unknown_error(name)
  File "lib/galaxy/jobs/runners/__init__.py", line 59, in _param_unknown_error
    raise Exception(JOB_RUNNER_PARAMETER_UNKNOWN_MESSAGE % name)
Exception: Invalid job runner parameter for this plugin: requests_memory

**Comment by nuwang** [comment]
Hi, try using the runner parameter `k8s_default_requests_memory`, which applies globally to the runner. The parameter `requests_memory` applies to individual destinations.

**Comment by markxiao** [comment]
Thanks! I guess the information on job_conf.xml.sample_advanced is not updated yet.
