### ISSUE TITLE
'job is paused because you were over your disk quota' message with 'enable_quotas: false' in config

### ISSUE THREAD

**Issue by MoffMade** [galaxyproject/galaxy#8125]
Some users have reported receiving intermittent messages `Execution of this dataset's job is paused because you were over your disk quota at the time it was ready to run` when submitting a job, although the galaxy they are accessing has quotas disabled via the yml config. This does not occur all of the time, nor does it seem tied to specific tools or workflows. 

I am running 19.01 UWSGI+Mules with Postgresql as the database and job completion is via HTCondor.

This may be due to my galaxy's seemingly unique setup. I have 2 instances running from the same DB and /galaxy directory, but using different galaxy.yml and job_conf.xml configurations. Supervisorctl manages the processes and starts them each with the direct uswgi command in venv, one pointing at galaxy.yml mounted at /galaxy and one pointing at galaxy-pub.yml mounted at /galaxy-pub. 

The issue then may arise because galaxy.yml has external authentication and `enable_quotas: false` and galaxy-pub.yml has galaxy managed authentication and `enable_quotas: true'

**Comment by martenson** [comment]
This is quite unique setup which I'd expect you having more problems with actually. Hopefully you resolved your quotas issue.
