### ISSUE TITLE
Updating shared name of published history results in blank screen

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8127]
![image](https://user-images.githubusercontent.com/458683/59262975-87768d80-8c40-11e9-987e-213ea0909f11.png)

Clicking on the pencil icon there blanks the main panel, and doesn't let you update the history's name. I don't see any errors in JS console, not sure what went wrong there.

**Comment by blankenberg** [comment]
xref https://github.com/galaxyproject/galaxy/issues/7893 & https://github.com/galaxyproject/galaxy/pull/7991 & https://github.com/galaxyproject/galaxy/issues/7868

**Comment by blankenberg** [comment]
If you really need to modify a link on a prod instance, the current work around I am using is to manually replace the `href="#"` with `href="javascript:void(0)"` via inspect element.

**Comment by hexylena** [comment]
Closing as duplicate
