### ISSUE TITLE
[Discussion] search box vs history renaming papercut

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8131]
The number of students I see enter a history name into the search box and then be confused that their datasets disappeared is really surprising. This is one of those papercut issues.

I'd propose:

- if history's name is "Unnamed history"
- and they enter something in search
- AND it returns no results

maybe show a quick "You searched for X, did you mean to rename history?" box? in the history itself?

**Comment by nsoranzo** [comment]
We could also switch the position of the history name and the search box (i.e. put the history name on top).

**Comment by martenson** [comment]
I am not sure that adding more text to troubleshoot problems, that users who don't read have, is gonna help it.

@nsoranzo that is worth an experiment I think

**Comment by hexylena** [comment]
Could also hide search under a 'search' icon next to multi-select?

**Comment by martenson** [comment]
Imo search should be the most prominent way to interact with a history.

@nsoranzo :
![Galaxy_and__Discussion__search_box_vs_history_renaming_papercut_·_Issue__8131_·_galaxyproject_galaxy](https://user-images.githubusercontent.com/1814954/59284472-4f6c4c00-8c3a-11e9-85ec-3e8014799536.png)

**Comment by nsoranzo** [comment]
@martenson I like it, this way the search box is closer to the search results!

**Comment by martenson** [comment]
@nsoranzo 
![Galaxy](https://user-images.githubusercontent.com/1814954/59293078-70d63380-8c4c-11e9-9781-3489d014dec3.png)

**Comment by nsoranzo** [comment]
Good idea to move the disk space, but I fear the line with the "N shown" may interfere with the buttons in case of "NNN shown, NNN deleted, NN hidden".

**Comment by martenson** [comment]
naively it should fit (ignore the misalignments)

![Galaxy](https://user-images.githubusercontent.com/1814954/59294290-18546580-8c4f-11e9-91b9-325aba5fc1dc.png)

**Comment by nsoranzo** [comment]
With N in the thousands it may not.

**Comment by hexylena** [comment]
Radical Idea: Remove the "History" completely and just place the title there.

**Comment by martenson** [comment]
It would break the symmetry with the Tool panel and it would be awkward to wrap to multiple lines when there is the topright menu present. Definitely worth thinking about though. 

@Nerdinacan has some WIP on histories, what is your thinking here?

**Comment by hexylena** [comment]
You could also remove the "Tools" from tool panel ;) But yeah, the wrapping would be odd unless you moved the icons, but those icons are in a really good place.

**Comment by hexylena** [comment]
Oh, look and old papercut! 

@martenson I love this, any objection to it being implemented? https://github.com/galaxyproject/galaxy/issues/8131#issuecomment-500888468

It makes so much more sense hierarchically to me:
- name
- filter(s)
- datasets

**Comment by hexylena** [comment]
I looked to fix this today because yet again someone had this issue, but I could not figure it out.

https://github.com/galaxyproject/galaxy/blob/dev/client/src/mvc/history/history-view.js#L562 makes it look like it should be rendered below the rest of the components, but the HTML I received from the client has it above the controls? I cannot tell what moves it around in there but maybe someone can provide a pointer?

**Comment by hexylena** [comment]
This is fixed with the new beta history, I'm so excited! 

![image](https://user-images.githubusercontent.com/458683/104583759-d167f680-5661-11eb-9ad9-0056767808bd.png)

 I wish I could've gotten help figuring out the client from someone, but, the new history works just as well.
