### ISSUE TITLE
[GIE] File mounted as directory in remote host.

### ISSUE THREAD

**Issue by rdallet** [galaxyproject/galaxy#8150]
Hi,
I am working on interactive environment and trying to run my dockerized app on a dedicated remote host. But the user file from which I run the GIE is mounted as a directory in my remote host. I don't understand why ... I specify that it works locally (file mounted as file).
I follow the GIE [documentation](https://docs.galaxyproject.org/en/master/admin/special_topics/interactive_environments.html#docker-on-another-host)

The docker daemon is running on the remote host.

Here is my IE.ini config file:
```
[main]

[docker]
command = docker -H tcp://<REMOTE_IP>:4243 {docker_args}
docker_hostname = <REMOTE_IP>
```

Can someone help me? Need more info?

**Comment by martenson** [comment]
Hi @RomainDallet, we've prepared hands-on [training material](https://training.galaxyproject.org/training-material/topics/admin/tutorials/interactive-tools/tutorial.html) that comes with pre-configured ansible roles to help you develop and troubleshoot interactive tools.

Come chat with other Galaxy admins in case of questions: https://app.element.io/#/room/#galaxyproject_admins:gitter.im
