### ISSUE TITLE
History search does not include HIDs

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8169]
I got an error

![image](https://user-images.githubusercontent.com/458683/59663486-6f0df200-91af-11e9-936f-a616cff188c8.png)

and went to search for 107, but search doesn't include the hid, only the name, so it finds datasets that 107 was part of but not 107:

![image](https://user-images.githubusercontent.com/458683/59663457-5dc4e580-91af-11e9-99b5-c3180f3bbb3c.png)

Yes I can type the full name, but I think for users it might be counter-intuitive that the hid isn't part of the name that's searched, but displays/renders like it is.

**Comment by martenson** [comment]
Many attributes on a dataset are searchable if you use the advanced syntax. That also solves the problem whether to include all results or just some of them given we search both fulltext and filter-like.

![Galaxy](https://user-images.githubusercontent.com/1814954/59694422-9b793c80-91b6-11e9-8b77-cd1877a1857a.png)

**Comment by hexylena** [comment]
Huh, super neat.

Is there any documentation for what parameters are available under the advanced syntax? I looked for it last time I was getting weird results and couldn't find anything then. (Or if not docs, where is that filtering in the codebase?)

**Comment by hexylena** [comment]
I was pointed to [this page](https://galaxyproject.org/tutorials/histories/#advanced-searching) the last time the question came up, but I had a feeling there were some more that we might be missing.

Edit: fixed url

**Comment by mvdbeek** [comment]
`state=` is pretty helpful when you need to delete hundreds of errored datasets

**Comment by martenson** [comment]
I've added the mentioned keywords and improved the clarity of the docs a bit. Hopefully. Closing unless objections.

**Comment by hexylena** [comment]
xref https://github.com/galaxyproject/galaxy-hub/commit/645310eb6ae0857541f9eff5431862ce116992f7

Yeah, guess no real objections other than "it may be counterintuitive for people who don't know what a hid is, they see one bold string that is the name, but can only search on part of it"

**Comment by hexylena** [comment]
But that's a hypothetical I suppose, I don't have evidence people are searching on hids (other than n=1 of me).

Edit: oh, well, you can search on datatypes without a prefix. That's probably how I was mislead, some attributes require a prefix, sometimes optional?

**Comment by nsoranzo** [comment]
Are the docs somehow linked near the search box? Otherwise it's very neat feature but not discoverable.

**Comment by martenson** [comment]
duplicate of https://github.com/galaxyproject/galaxy/issues/3937

**Comment by martenson** [comment]
I improved the docs a bit more (https://galaxyproject.org/tutorials/histories/#advanced-searching) but the xref'd issues is still a good idea
