### ISSUE TITLE
Dataset tagger no longer suggesting close matches for name tags

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8173]
I feel like this used to be more "search" like? And would filter responses based on what you were typing? Now it seems to offer this list when I provide a `#` as first character.

![image](https://user-images.githubusercontent.com/458683/59667649-63262e00-91b7-11e9-9b68-ebd74f91bc2c.png)

Any normal, non-name tag inputs seem to respond in proper filtering of suggestions.

**Comment by davelopez** [comment]
Likely fixed with the new component. Please reopen if not.
