### ISSUE TITLE
Tool Search box loads with active spinner

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#8184]
behind the X, seen on latest dev and https://test.galaxyproject.org/.

![tool-search-spinner](https://user-images.githubusercontent.com/1231190/59706687-f159de80-91ce-11e9-964b-aa3e60b976c4.gif)

**Comment by martenson** [comment]
also the spinner is off-center 👀

**Comment by dannon** [comment]
I tracked this down a few weeks ago to a57ebcaf01e561964710007b95c0f1a27dda24bb.  @Nerdinacan was going to take a look IIRC.  (My hunch was the fontawesome icon refactoring, but I didn't dig deep)

Thanks for creating the issue; I should have done that previously.

**Comment by martenson** [comment]
seems fixed
