### ISSUE TITLE
Proxy prefix not respected on Import history modal

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#8193]
When wanting to import a history as an anonymous user and a modal shows up with links to login or register, the proxy prefix does not seem to be respected. See the URL structure in the screenshot and the link hover:

![Screen Shot 2019-06-19 at 12 36 02 PM](https://user-images.githubusercontent.com/338642/59785141-0d728400-9292-11e9-8a60-633cf3d04ab0.png)

Another place the proxy prefix is missing is under Admin → Local data → ToolShed link when no Data Managers are installed:

![Screen Shot 2019-06-19 at 12 56 20 PM](https://user-images.githubusercontent.com/338642/59785147-119ea180-9292-11e9-9654-50ea4e3a53c2.png)

**Comment by mvdbeek** [comment]
This was fixed in https://github.com/galaxyproject/galaxy/pull/8205 and https://github.com/galaxyproject/galaxy/pull/7811
