### ISSUE TITLE
Select lists are less convenient when we run a workflow

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#8200]
There is a difference in the way the lists are displayed when we use a tool or we we use the same tool in a workflow.

Example with BlastN:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/7pswb8s/2019-06-20-Screen-Hunter-04.jpg" alt="2019-06-20-Screen-Hunter-04" border="0"></a>

I can start to enter `UNI` in order to shrink the list

But if BlastN is used in a workflow, when I run the worflow I can't do the same:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/5vjgWQJ/2019-06-20-Screen-Hunter-05.jpg" alt="2019-06-20-Screen-Hunter-05" border="0"></a>

And we can't select all, or have a nice boxe when a genome is selected:
<a href="https://imgbb.com/"><img src="https://i.ibb.co/jDWTgyt/2019-06-20-Screen-Hunter-06.jpg" alt="2019-06-20-Screen-Hunter-06" border="0"></a>

Is it possible to display lists the same way ? Is it simple to do that (javascript / bootstrap issue) ?

Because I'm back from two days of training of our users, and this behavior will be an issue for me.

Our reference genome list is quite long (and will be possibly longer...). And our users complain about that.
It is somewhat related to #8145 
I tried to add a filter, but this is not a great solution (in my admin point of view). I don't want to modify all XML that deal with a .loc file!

I'm still using 19_01, I will try to upgrade to 19_05 next week.

**Comment by FredericBGA** [comment]
@nsoranzo I would be happy to submit a PR for that (like I said in Freiburg). Maybe @guerler could help me?

**Comment by dannon** [comment]
@guerler Do you know off the top of your head why this toggles to the other display?

**Comment by guerler** [comment]
This is due to performance considerations. Since Select2 fields are pretty 'expensive' in terms of memory usage, we decided to use the regular select fields for non-dataset selectors in the workflow run form. The select field is switched to not-searchable i.e. non-select2 at https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/form/form-parameters.js#L103.

**Comment by FredericBGA** [comment]
thank you.
is this something that could be added in galaxy.yml, let the admin decide if he wants Select2 fields or not ?

**Comment by dannon** [comment]
Making this configurable seems reasonable; might also be really nice to be able to automatically switch to the degraded non-select2 version only when some (massive) number of inputs is detected?

**Comment by martenson** [comment]
close by https://github.com/galaxyproject/galaxy/pull/9105 I believe
