### ISSUE TITLE
Input collection drag and drop does not validate datatype, leads to obscure error

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#8202]
reported by @pcm32:

> Hi, we have someone trying to run cutadapt on a paired-end collection (a collection which elements are paired sequences). This was built from a Data Library using the List of Pairs option. The tool never recognises the collections in the drop down, but the person trying this just dragged the collection on the data field (I wasn’t aware you could do this). I guess that the fact that the tool is not recognizing the collection is not a good thing. The error we get on execution is:

```
galaxy.tools ERROR 2019-06-20 09:34:16,858 [p:29357,w:1,m:0] [uWSGIWorker1Core3] Exception caught while attempting tool execution:
Traceback (most recent call last):
  File "lib/galaxy/tools/__init__.py", line 1429, in handle_single_execution
    collection_info=collection_info,
  File "lib/galaxy/tools/__init__.py", line 1511, in execute
    return self.tool_action.execute(self, trans, incoming=incoming, set_output_hid=set_output_hid, history=history, **kwargs)
  File "lib/galaxy/tools/actions/__init__.py", line 491, in execute
    handle_output(name, output)
  File "lib/galaxy/tools/actions/__init__.py", line 426, in handle_output
    output.actions.apply_action(data, output_action_params)
  File "lib/galaxy/tools/parser/output_actions.py", line 34, in apply_action
    action.apply_action(output_dataset, other_values)
  File "lib/galaxy/tools/parser/output_actions.py", line 112, in apply_action
    case.apply_action(output_dataset, other_values)
  File "lib/galaxy/tools/parser/output_actions.py", line 75, in apply_action
    return super(ToolOutputActionConditionalWhen, self).apply_action(output_dataset, other_values)
  File "lib/galaxy/tools/parser/output_actions.py", line 34, in apply_action
    action.apply_action(output_dataset, other_values)
  File "lib/galaxy/tools/parser/output_actions.py", line 318, in apply_action
    value = self.option.get_value(other_values)
  File "lib/galaxy/tools/parser/output_actions.py", line 245, in get_value
    value = value.child_collection[attr_name].element_object
AttributeError: 'HistoryDatasetCollectionAssociation' object has no attribute 'child_collection'
```

**Comment by bgruening** [comment]
xref from the WG meeting

https://github.com/galaxyproject/galaxy/pull/9809

It seems the file picker had the filter functionality ...

**Comment by dannon** [comment]
xref https://github.com/galaxyproject/galaxy/pull/13222; we'll want to handle drop (and direct selection) with more guardrails on the client with the new select components

**Comment by natefoo** [comment]
It's not just collections, you can also drag and drop datasets of a completely incorrect datatype on to the field and run the tool. Here I've taken the html output of FastQC and dragged it to the fastq input of Trimmomatic:
![image](https://github.com/galaxyproject/galaxy/assets/286969/b664b80d-2069-4ae6-b51f-c403c4b8e3a2)

The `(unavailable)` is interesting, I normally only see that when rerunning jobs in imported histories where the user deleted the input, but the dataset does exist in the history, and Galaxy will happily run this job.

**Comment by pcm32** [comment]
I have to say that this "feature" is helpful when the slot accepts only certain flavours of text and your have a different one which should be still acceptable. I use it quite often 😁.
