### ISSUE TITLE
[Workflows] input dataset can't be optional

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#8218]
Like `Simple inputs used for workflow logic` I would like to be able to set an input file as optional.
Right now the workflow will not start until a file is provided.

**Comment by mvdbeek** [comment]
This is also listed in https://github.com/galaxyproject/galaxy/issues/1325, but I think this will be difficult to implement (hence the unfriendly label) in a user-friendly way. A start might be to just allow optional datasets in tool inputs that are optional, this is probably not that hard, but long term I think it would also be great to have some conditional logic that will be used based on whether an optional dataset has been provided or not.

**Comment by FredericBGA** [comment]
ok.  Allow inputs to specify a input type is nice too!

**Comment by mvdbeek** [comment]
Thanks @FredericBGA, we do have optional input datasets now.
