### ISSUE TITLE
Small-to-Medium Tasks to Improve Galaxy Packages.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#8240]
As mentioned in https://github.com/galaxyproject/galaxy/issues/8140 improving Galaxy ``packages/`` provides a lot of small-to-medium size issues that could be tackled by newcomers with different skillsets and help a wide variety of different parts of the Galaxy code base.

We also now have some rudimentary CI for these packages now. Hence, each new package that has tests of any complexity ensures that pytest imports all the files and finds any dependency issues during CI.  This ensures over the long term we're dealing with dependencies between packages more intelligently, tracking external dependencies in a more structured way, etc.. This will have a large, automatically enforced impact on the quality of the code we are writing. This has the makings of some of the really great hackathon projects of GCCs past.

- [x] Merge @natefoo's installable branch galaxyproject/galaxy#921
- [ ] Add Sphinx docs to the projects and shared build system - focused on docstrings and improved READMEs at first.
   - [ ] Could think about how to split out some of the docs for things like the mulled utilities (there are docs in galaxy-lib but not in Galaxy, that needs to be fixed).
- [ ] Review all non-.py files in all the ``packages/`` and make sure they are being added to the ``PACKAGE_DATA`` in the corresponding ``setup.py`` file.
- [x] Fix galaxy-data importing a couple ``tool_shed/`` utilities. Possibly refactor ``tool_shed/util/common_util``, ``tool_shed/util/encoding_util``, and ``tool_shed/util/common_util`` out into ``galaxy-util``. Possibly refactor ``galaxy.model.tool_shed_install`` out of ``galaxy-data``. Possibly refactor the model methods that require the ``common_util`` import into ``galaxy-app``.
- [x] Make sure all unit tests find a home. Pick a unit test not symbolically linked in, find a home, make sure the dependencies are correct and it works on CI.
- [x] Refactor ``galaxy.quota`` to not consume ``trans`` so it belongs more neatly in ``galaxy-data``. The methods consume ``trans`` also take in a user and and a history - so the idea would be anywhere they are called with ``agent.f(trans=trans)``  refactor by adding a method to ``trans`` so it would be ``def trans.f(): agent(user=self.user, history=self.history)`` for better encapsulation. 
- [ ] Create a ``Pipfile`` for each package - hard dependencies should be tracked as close as possible to the code, write some infrastructure for merging them and building our main ``Pipfile`` from these.
- [x] Add a unit test to ``packages/containers`` so we can enable CI testing of that package. Even something super simple would cause pytest to do imports, etc.. and so would be worthwhile. https://github.com/galaxyproject/galaxy/pull/8302
- [x] Figure out why ``packages/tool_util`` isn't being tested and fix the problems.
- [x] Refactor the rest of ``galaxy-lib`` into ``galaxy-tool-util`` (e.g. refactor ``galaxy.tools.linters`` ->  ``galaxy.tool_util.linters`` and add to ``setup.py``.) xref. https://github.com/galaxyproject/galaxy/issues/8073
- [x] Rework Planemo to use ``galaxy-tool-util``.
- [x] Figure out why ``packages/data`` isn't being tested and fix the problems (probably tool_shed_install issue above).
- [x] Figure out why ``packages/job_execution`` isn't being tested and fix the problems. https://github.com/galaxyproject/galaxy/pull/8269
- [x] Add a unit test to ``packages/auth`` so we can enable CI testing of that package. Even something super simple would cause pytest to do imports, etc.. and so would be worthwhile.
- [x] Find or/write unit tests so that all remaining packages are under CI testing.
- [x] Figure out what to do with top-level stuff in ``lib/`` - log_tempfile.py, mimeparse.py, psyco_full.py. Are they needed?
- [x] Place top-level ``galaxy/`` queue, config, version stuff into galaxy-app.
- [x] Place top-level ``galaxy/`` app.py and main.py into galaxy-web-apps.
- [x] Refactor main.py so it doesn't need to be in galaxy-web-apps and can be in galaxy-app instead.
- [x] Refactor all the scripts to be wrappers in to ``lib/`` - find the right package for each, add to setup.py, etc.. Pulsar is something of a model for how to do this.

**Comment by jdavcs** [comment]
Just a quick reaction: I'll be happy to dive into/take on any of these. So when any of this is discussed next week at GCC, please count me in.

**Comment by jmchilton** [comment]
This was a massive project but I think it is done - thanks for all the help everyone. Still lots to do in terms of packing but we made tremendous progress on these tasks involving getting all the relevant code and tests into packages.
