### ISSUE TITLE
Workflow evaluation problem error

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#8248]
I have try to reproduce an error we are facing (with a much bigger workflow)

The workflow is simple. Filter a collection (with` Filter List`) based on a file (`input dataset`)  and then select first lines (with `Select First`)  of selected files. The number of line to keep is a `Simple input`

It works.

But when we try to add another step (in my example `Search in textfiles`) it fails.

Maybe you can see this error:

> Failed to schedule Workflow[id=385,name=Grep Before], problem occurred on WorkflowStep[index=5,type=tool].

> Exception: Workflow evaluation problem - failed to find output_name output in step_outputs {}

Using [this history](https://usegalaxy.eu/u/fredbga/h/unnamed-history) and [this workflow](https://usegalaxy.eu/u/fredbga/w/failed) I think you will be able to reproduce the error.

**Comment by mvdbeek** [comment]
Thanks for the report, I can reproduce this. https://github.com/galaxyproject/galaxy/issues/8248 should fix the issue.
