### ISSUE TITLE
Cannot import history from shared/public history on another server

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8260]
Found by @MoHeydarian @jennaj maybe they can flesh it out with some more details

**Comment by MoHeydarian** [comment]
Found when trying to import a history from usegalaxy.ORG to usegalaxy.EU.

History was made accessible by link on usegalaxy.org, that link was provided to Import history. A green message appears that the history will be made made visible once ready, but nothing happens.

**Comment by jennaj** [comment]
@jennaj Test this again, EU server was under heavy usage during GCC
