### ISSUE TITLE
Tools Panel - Vue Component

### ISSUE THREAD

**Issue by inkuzmin** [galaxyproject/galaxy#8262]
We've discussed this task with @bgruening during the ELIXIR All Hands meeting in Lisbon and with @martenson during the third day of GCC2019 in Freiburg.

The idea is twofold:

1. To create a vue component for the tool panel.
2. To provide a better search results view.
2.1. To expand the panel with results over the middle panel.
2.2. To sort results by score.

Right now I am going to prototype it. Any comments or suggestions will be welcomed!

**Comment by dannon** [comment]
Maybe pursue this as a hackathon project and loop in a few more folks to help?  This sounds like an ideal project for that.

It'd be great if this could unify the toolbox components between the standard interface and the workflow editor in the process.
