### ISSUE TITLE
Input format of tools in workflow editor is case-sensitive

### ISSUE THREAD

**Issue by chambm** [galaxyproject/galaxy#831]
When my upstream tool outputs "idpdb" and my downstream tool accepts "idpDB", Galaxy lets me feed the output from the upstream tool to the downstream one without a problem. But when I try to connect them in a workflow, it doesn't allow the connection. When I made the case consistent (lower case in my downstream tool), the workflow editor worked fine. This inconsistency seems like a bug (probably in the editor).

**Comment by bernt-matthias** [comment]
Datatypes are case sensitive. Downstream tool should be modified to accept `idpdb`.
