### ISSUE TITLE
Build dataset list (collection) 500 entry limit

### ISSUE THREAD

**Issue by mmiladi** [galaxyproject/galaxy#8328]
Hello,

I am trying to build a collection from about 600 fastq entries, by selecting all entries in all pages, then "Build Dataset List"-> Create entry with hide options. However the process fails by only making a 500 element list and ignoring the rest. There seems to be a hard-coded/pre-configured(?) 500 or 1000 size limit somewhere.. :-)

Thanks,
Milad

**Comment by jmchilton** [comment]
Duplicate with https://github.com/galaxyproject/galaxy/issues/4350.
