### ISSUE TITLE
xlsx format is not recognize

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#8341]
on galaxy 19_05 we can't upload an xlsx file and let galaxy sniff the datatype.
it works when you set the datatype yourself.

the errors on galaxy.eu and galaxy.org are different...
I have the same error as galaxy.org on my instance.

galaxy.eu
> Fatal error: Exit code 1 ()
> [Errno 2] No such file or directory: SafeStringWrapper(unicode:__lt__class __sq__galaxy.tools.wrappers.ToolParameterValueWrapper__sq____gt__,__lt__class __sq__galaxy.util.object_wrapper.SafeStringWrapper__sq____gt__,__lt__class __sq__numbers.Number__sq___

galaxy.org:
> Traceback (most recent call last):
>   File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/upload.py", line 326, in <module>
>     __main__()
>   File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/upload.py", line 319, in __main__
>     metadata.append(add_file(dataset, registry, output_path))
>   File "/cvmfs/main.galaxyproject.org/galaxy/tools/data_source/upload.py", line 128, in add_file
>     convert_spaces_to_tabs=dataset.space_to_tab,
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/upload_util.py", line 54, in handle_upload
>     convert_spaces_to_tabs=convert_spaces_to_tabs,
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/sniff.py", line 724, in handle_uploaded_dataset_file_internal
>     auto_decompress=auto_decompress,
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/sniff.py", line 663, in handle_compressed_file
>     sniffed_ext = run_sniffers_raw(filename, sniff_datatypes)
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/sniff.py", line 482, in run_sniffers_raw
>     file_prefix = FilePrefix(filename_or_file_prefix)
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/datatypes/sniff.py", line 541, in __init__
>     compressed_format, f = compression_utils.get_fileobj_raw(filename, "rb")
>   File "/cvmfs/main.galaxyproject.org/galaxy/lib/galaxy/util/compression_utils.py", line 50, in get_fileobj_raw
>     with zipfile.ZipFile(filename, mode) as zh:
>   File "/cvmfs/main.galaxyproject.org/python/lib/python2.7/zipfile.py", line 729, in __init__
>     raise RuntimeError('ZipFile() requires mode "r", "w", or "a"')
> RuntimeError: ZipFile() requires mode "r", "w", or "a"

**Comment by mvdbeek** [comment]
Are you working on a fix @wm75 or should I take this on ?

**Comment by wm75** [comment]
@mvdbeek I have the fix for the ZipFile issue ready.
It's really trivial (just remove 'b' from the mode before passing it to ZipFile) but I thought it should be combined with some tests of the underlying decompression function and I haven't yet found the time for that.
If you have some spare time at the moment, just go ahead. Otherwise I can work on it during next week.

**Comment by mvdbeek** [comment]
just drop a xlsx file into lib/galaxy/datatypes/test, this will test pretty much everything

**Comment by mvdbeek** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/8362
