### ISSUE TITLE
objectstore vs object_store

### ISSUE THREAD

**Issue by mr-c** [galaxyproject/galaxy#835]
Which is the canonical name? I'll submit a PR normalizing the name if a decision is made. Made it a little hard to trace the codepaths as I was only searching for `objectstore` and not `object_store` as well.

**Comment by dannon** [comment]
So currently it looks like the only split is that instances are always referred to as `object_store`, though per pep8 (package underscores discouraged) the package itself is `objectstore`.  This looks ok to me as-is, unless I'm missing something you're seeing.

**Comment by jxtx** [comment]
I agree. It is consistent with PEP-8 that an instance of a class named ObjectStore is called object_store, while the package it is in is called objectstore. (Whether we like that is a different questions).

**Comment by hexylena** [comment]
I guess fixed in #853
