### ISSUE TITLE
admin 'install or uninstall' should work with toolshed down

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#8352]
Atm, when MTS is down the page does not load and you are given JS error:

`TypeError: _this.categories.reduce is not a function`

**Comment by guerler** [comment]
The error message should be fixed by #8585, but it is true that the toolshed client requires the toolshed server to be available in order to retrieve repository details.

**Comment by martenson** [comment]
I am on 19.09 and I see `Uncaught exception in exposed API method:`
