### ISSUE TITLE
Update tool defaults in subworkflows when a workflow is opened and saved

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8354]
If a workflow used a tool that had its inputs change, it would usually only show an warning when you edit it and then populate the defaults. With subworkflows this is not the case and you have to open the original workflow, save it, and then reimport it into the parent workflow and relink all of its connections.

Ideally, subworkflows should maintain some sort of link to the original workflow, or subworkflows should be editable from within the parent.

This is related to #8353

**Comment by mvdbeek** [comment]
> Ideally, subworkflows should maintain some sort of link to the original workflow, or subworkflows should be editable from within the parent.

They are now editable from within the parent, there's a edit button when you select an embedded workflow.

**Comment by innovate-invent** [comment]
Does this mean I have to open every subworkflow to update the tool defaults? This is problematic especially when there are nested subworkflows. It is also misleading when the message tells you it is updating the defaults when the workflow loads.
I know my original suggestion was simply to allow editing, but the logic that runs when a workflow loads should also run on subworkflows.

**Comment by mvdbeek** [comment]
> Does this mean I have to open every subworkflow to update the tool defaults?

I don't understand this question. You can either open and edit, or update to the latest version. Version selection is also planned.

**Comment by innovate-invent** [comment]
When a workflow is opened for editing it triggers a bunch of logic that will validate tool inputs and if the tool inputs have changed it will update them. This will show a warning that the tools inputs have been updated. When a workflow contains subworkflows, the tools in the subworkflow do not have this logic applied. I believe you are telling me that I then have to go through the workflow and open for editing every instance of a subworkflow to trigger this update logic. That is very inconvenient and prone to issues. The warning shown when the parent workflow is updated is also misleading because I would think that it would have checked the subworkflows and that they have been updated when they have not.

**Comment by mvdbeek** [comment]
Have you tried it at all ? 

> When a workflow is opened for editing it triggers a bunch of logic that will validate tool inputs.

Yes, but that is independent of upgrading an embedded workflow. You'll have to do that once. When done you have a new workflow version that can be updated in all parents that use this embedded workflow.

**Comment by innovate-invent** [comment]
> Have you tried it at all ?

Do you mean that this has been recently fixed?

> Yes, but that is independent of upgrading an embedded workflow. You'll have to do that once. When done you have a new workflow version that can be updated in all parents that use this embedded workflow.

So you are saying that it is intentional that all subworkflows have to be manually opened and saved to trigger this logic on them?
Is it possible to create a UI option to allow triggering the logic on the subworkflows with the parent? Having to manually walk through a large workflow with lots of nested subworkflows will get tedious quickly.

**Comment by mvdbeek** [comment]
Please give it a try and then provide feedback. 

> So you are saying that it is intentional that all subworkflows have to be manually opened and saved to trigger this logic on them?

You have the option of editing, or to update to the latest version with a single click. That assumes the latests version is what you want, if not you'll have to edit once, I can't think of a way around that.
