### ISSUE TITLE
LEfSe:  A) Format Data for LEfSe

### ISSUE THREAD

**Issue by brockmt** [galaxyproject/galaxy#8370]
using the web-based version of Galaxy/LefSe generates an error when clicking on the Format Data for LEfSe link. The error reports: "Tool request failed: Uncaught exception in exposed API method:". This error did not happen yesterday when I used the website. I've clicked on additional LEfSe options and they seem to be working fine.

**Comment by brockmt** [comment]
using the web-based version of Galaxy/LefSe generates an error when clicking on the Format Data for LEfSe link.  The error reports:  "Tool request failed:  Uncaught exception in exposed API method:".  This error did not happen yesterday when I used the website.  I've clicked on additional LEfSe options and they seem to be working fine.

**Comment by mvdbeek** [comment]
We don't have any control over LefSe, this is the development repository for Galaxy. You might want to contact the administrator of the Galaxy instance you are using.
