### ISSUE TITLE
"null" string input in workflow ui does not persist

### ISSUE THREAD

**Issue by crutching** [galaxyproject/galaxy#8375]
I was trying to use the string "null" for one of my "text" tool params in the workflow UI.  Upon saving the workflow, then reentering the workflow editor, the input box is blanked out.  In the resulting workflow json, entry appears as empty quotes.  Was able to reproduce for multiple text parameters.

**Comment by martenson** [comment]
I suspect javascript `null` value masking this at some point.

**Comment by crutching** [comment]
One other note, I am currently using v19.05.  In a much older instance running off of v15.05, this issue did not exist.

**Comment by mvdbeek** [comment]
Looking at this I see that the payload coming in via `PUT /api/workflows/{id}` already contains `""` as the parameter value when you enter the string `null`, so probably something is going wrong on the client side.

**Comment by dannon** [comment]
xref #9484, which was old WIP exploring what's going on here.
