### ISSUE TITLE
Relative tool file destination in tool_conf.xml and `$__tool_directory__`

### ISSUE THREAD

**Issue by rdallet** [galaxyproject/galaxy#8381]
Hi,

I have an issue about the tool file destination in `tool_conf.xml`.

To contextualize, the xml file of my tool is in `galaxy/test/functional/tools/` and contains a command that calls `$__tool_directory__`. But this variable refers to `/path/to/galaxy/lib/galaxy/tools/test/functional/tools` instead of `/path/to/galaxy/test/functional/tools`. 

The tool configuration (`tool_conf.xml`) below:
```
<section id="functest" name="Functional Test Tools">
    <tool file="../test/functional/tools/my_tool.xml" />
</section>
 ```

I found that the relative path was the problem but I don't understand why ?

My current solution is to use the absolute path instead of the relative but may be there is a better solution ? Or maybe the problem comes from elsewhere?

**Comment by gbbio** [comment]
Check the tool_path in galaxy.yml

**Comment by jmchilton** [comment]
Also you can set the location for relative paths with tool_path at the top of the file.

https://github.com/galaxyproject/galaxy/blob/dev/test/functional/tools/samples_tool_conf.xml
