### ISSUE TITLE
Tool Grouping1 (Group data) adds extra lines for 1 column input

### ISSUE THREAD

**Issue by tshtatland** [galaxyproject/galaxy#8383]
The tool "Group data by a column and perform aggregate operation on other columns. (Galaxy Version 2.1.3)" generates 1 extra line with the result of the aggregate function such as "count" for each line in the "group by" column. Expected to have no extra lines, so that each line in "group by" column as the result of the aggregate function on the same line. Occurs with 1-column tabular input, but not with 2 column input.

I think usegalaxy has the current version: id="Grouping1" name="Group" version="2.1.3".

To reproduce, see:
history = dat_190726_1.test_join_tool
This history is currently accessible via link and published:
https://usegalaxy.org:/u/tshtatland/h/dat1907261testjointool

Input 1-column tabular file:

```
a
b
c
b
c
c
```

Incorrect output (6 lines, expected 3 lines:
```
a
	1
b
	2
c
	3
```

**Temporary workaround:**

As seen in the history above. Add a dummy second column to your 1-column tabular file. For example, paste the file with itself. Use tool "Paste two files side by side (Galaxy Version 1.0.0)" with your 1-column file as input 1 and input 2:

```
a	a
b	b
c	c
b	b
c	c
c	c
```

With this input, the Group tool works as expected.

**Comment by bernt-matthias** [comment]
Should be solved by: https://github.com/galaxyproject/galaxy/pull/8953
