### ISSUE TITLE
Add datasets to new history as collection adds to current history

### ISSUE THREAD

**Issue by bwlang** [galaxyproject/galaxy#8384]
When using the  feature of adding a set of datasets from a library to a history a new history is created, but the datasets are added to the current history too.

I reproduced this on usegalaxy.org using https://usegalaxy.org/library/list#folders/F5419cb7acafcaf3c as though the reps were read 1 and read 2
![image](https://user-images.githubusercontent.com/61636/61977938-d04e8f80-afbd-11e9-89be-585f8e2cd1c1.png)
Note that I added to a (misspelled) "new hisotry" , but the datasets also appear in the "Deleted Datasets Test" history (which was the current history when I went to the data library 
![image](https://user-images.githubusercontent.com/61636/61977908-bad96580-afbd-11e9-8213-92bd5d443f43.png)

**Comment by bwlang** [comment]
@martenson : is this your area?

**Comment by martenson** [comment]
@bwlang I think so, I'll have a look.

**Comment by OlegZharkov** [comment]
Not the case anymore. this has been fixed during the library rewrite. Someone with access should close this issue

**Comment by mvdbeek** [comment]
That was fixed in https://github.com/galaxyproject/galaxy/pull/10508.
