### ISSUE TITLE
workflow menu click action

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#8391]
A click on a workflow in the workflow menu launches the editor. Somehow I have the feeling that it should be start the workflow. 

IMHO the intention should be that  the option (run/edit) which is chosen more often by users is the default. Ideally workflows are more often started than edited.

**Comment by WilliamHolden** [comment]
Hey @bernt-matthias, I just checked and it looks like the new workflow menu has it's own run button and clicking on a workflow now opens a menu with a list of options. If it looks good to you, feel free to close this. Thanks!

**Comment by bernt-matthias** [comment]
Just checked on the latest dev. Still the same.

**Comment by bernt-matthias** [comment]
Fixed with the separate run button.
