### ISSUE TITLE
Search result visualization

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/galaxy#8397]
Hi,

1. Searching an item via 'All histories' --> 'Search datasets' gives an unpleasant representation of the results. It simply shows all histories and you have to scroll through all instead of just having the matching ones listed (First image). In contrast, this works as expected for 'All histories' --> 'Search histories'. (Second image)
2. Moreover, if a search for datasets was done, and next a history search is run, the selection of the dataset search is not removed. See second image.

![search_galaxy](https://user-images.githubusercontent.com/13435136/62286103-59027b00-b457-11e9-91e9-ef445322df67.png)
![searchII](https://user-images.githubusercontent.com/13435136/62286105-5b64d500-b457-11e9-9d44-665b91a7373e.png)

Would be nice if this can be fixed / improved.

Best,

Joachim

**Comment by hexylena** [comment]
I think users might prefer a more google-esque experience here.

One search box, returning multiple items in one list (or maybe separated into categories):

- matched histories
- matched datasets / collections / datasets-in-collections
- matched histories-shared-with-me
- matched datasets in histories-shared-with-me
- matched shared data

I understand the initial design's rationale. For large histories this is not working so well for us currently, and having a single entry point to search might provide us with more benefit than the current history-based representation?  If dataset search filtered out non-matching histories this would already probably be a good improvement.
