### ISSUE TITLE
Unable to view bigwig and bigbed files in IGB uploaded through galaxy instance.

### ISSUE THREAD

**Issue by nzahara1** [galaxyproject/galaxy#8401]
I have hosted galaxy on Amazon EC2 instance.
Trying to view bigwig and bigbed files in IGB uploaded via galaxy and getting the below error message in IGB : Error reading R+ tree header: bad magic = -2003829722 while reading the file.

Galaxy console error : 
"GET /display_application/df7a1f0c02a5b08e/igb_bigwig/View/383651628846c1ff/data/BigWig_HomoSapien.bigWig HTTP/1.1" 200 8841495 "-" "IGB/9.1.0; Mac OS X/10.14.5 (x86_64); en_US; Java/1.8.0_221"
[uwsgi-http key: 54.208.249.92:8080 client_addr: 209.239.128.14 client_port: 38882] hr_write(): Broken pipe [plugins/http/http.c line 565]

**Comment by martenson** [comment]
some other info from chat:

> it is using ngnix; It is just happening with bigbed and bigwig files; I am able to visualize the data for other file formats

I was able to reproduce this locally with a test bigwig file

**Comment by nzahara1** [comment]
The issue is happening for bed files as well... 

Error message : http://54.208.249.92:8080/display_application/1e8ab44153008be8/igb_bed/View/4dabc5eb4dd2db33/data/Bed_HomoSapien.bed is not reachable, and is not cached!

Galaxy console message :

 GET /display_application/1e8ab44153008be8/igb_bed/View/4dabc5eb4dd2db33/data/Bed_HomoSapien.bed => generated 7405568 bytes in 590 msecs (HTTP/1.1 200) 3 headers in 100 bytes (116 switches on core 3)
[uwsgi-http key: 54.208.249.92:8080 client_addr: 209.239.128.14 client_port: 1534] hr_write(): Broken pipe [plugins/http/http.c line 565]

**Comment by mvdbeek** [comment]
You need a proxy that supports byte-range requests for data types that support this, which includes bigwig and bam files. You mention that you're using nginx, but `[uwsgi-http key: 54.208.249.92:8080 client_addr: 209.239.128.14 client_port: 1534] hr_write(): Broken pipe [plugins/http/http.c line 565]` indicates that uwsgi is responding directly.

Make sure to use nginx's uwsgi protocol, not http. An extensive documentation is at https://docs.galaxyproject.org/en/release_19.05/admin/nginx.html.

To verify byte-range requests work you can use curl:

`curl -v -X GET -H "range: bytes=1-8" http://10.50.11.98/display_application/219085ee374ee4da/igv_bam/local_default/858c591b9a7a7b45/data/galaxy_219085ee374ee4da.bam > output`

should return something like
```
curl -v -X GET -H "range: bytes=1-8" http://10.50.11.98/display_application/219085ee374ee4da/igv_bam/local_default/858c591b9a7a7b45/data/galaxy_219085ee374ee4da.bam > output
Note: Unnecessary use of -X or --request, GET is already inferred.
* Uses proxy env variable no_proxy == 'localhost,127.0.0.1,127.0.1.1,192.168.99.0,local.home,10.50.10.172'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 10.50.11.98...
* TCP_NODELAY set
* Connected to 10.50.11.98 (10.50.11.98) port 80 (#0)
> GET /display_application/219085ee374ee4da/igv_bam/local_default/858c591b9a7a7b45/data/galaxy_219085ee374ee4da.bam HTTP/1.1
> Host: 10.50.11.98
> User-Agent: curl/7.64.1
> Accept: */*
> range: bytes=1-8
>
< HTTP/1.1 206 Partial Content
< Server: nginx/1.4.6 (Ubuntu)
< Date: Fri, 02 Aug 2019 10:15:56 GMT
< Content-Type: application/octet-stream
< Content-Length: 8
< Last-Modified: Sun, 28 Jul 2019 22:07:58 GMT
< Connection: keep-alive
< Set-Cookie: galaxysession=c6ca0ddb55be603af16cf8fd4716b2d197c6160b48e6274f5784ca0515fe7c63287946046f1a8811; expires=Thu, 31-Oct-2019 10:15:55 GMT; httponly; Max-Age=7776000; Path=/; Version=1
< ETag: "5d3e1cbe-1449ddb1"
< Content-Range: bytes 1-8/340385201
<
{ [8 bytes data]
100     8  100     8    0     0     52      0 --:--:-- --:--:-- --:--:--    52
```

In your case the url to try should be http://54.208.249.92:8080/display_application/df7a1f0c02a5b08e/igb_bigwig/View/383651628846c1ff/data/BigWig_HomoSapien.bigWig

but also the 8080 is suspicious here, you'd usually serve on 80 or 443 with nginx.

**Comment by martenson** [comment]
@mvdbeek is correct, you need to configure your galaxy to use proxy, and enable byte-range requests on proxy. The exact details are here: https://docs.galaxyproject.org/en/release_19.05/admin/nginx.html#sending-files-with-nginx

I have tested this locally, and the `_x_accel_redirect` nginx configuration is what does the trick.
