### ISSUE TITLE
Show upload status in history item

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/galaxy#8419]
Hi,

To upload data can take a while especially if NCBI or ENBI ENA ftp upload is used. For larger files it can take a few days, but all I see as a user is the spinning wheel in the yellow status. Sometimes to unknown reasons uploads crash but the status stays yellow. 

I think a good solution would be to give the user a feedback via a progress bar or sth like '10.2 GB of 50GB uploaded'. This would help to estimate when I can come back to continue my work with this data or to figure out on my own if an upload failed. In the last case I could just restart the upload without the need to contact an admin.

Thanks for considering.

Best,

Joachim

**Comment by hexylena** [comment]
There is currently no mechanism for feedback of the job's during runtime.

 I agree, this would be nice for big files. For the other jobs, I would say providing "live" logs from the job is less of a priority (but more commonly requested), but for uploads from remote endpoints this could be really nice for users when they get stuck all the time like yours have at EU (xref #8425)
