### ISSUE TITLE
Restart failed uploads via item

### ISSUE THREAD

**Issue by joachimwolff** [galaxyproject/galaxy#8420]
Hi,

Sometimes it happens due to network timeouts on the Galaxy server side that an upload of a job fails. So far there is no option to just restart this upload job. Currently I have to copy&paste all again to the upload dialog.

Feature request: A rerun upload option in case the upload failed.

Thanks for considering.

Best,

Joachim

**Comment by hexylena** [comment]
For pasted URLs this would be really great. I can't imagine there are any technical limitations?
