### ISSUE TITLE
Output filters referring to inputs recieve an unexpected type when in a workflow

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8428]
`galaxy.tools.actions DEBUG 2019-08-07 12:02:09,472 [p:99934,w:1,m:0] [uWSGIWorker1Core0] Dataset output filter failed: 'ConnectedValue' object has no attribute 'is_of_type'`

[<filter>draft.is_of_type("genbank")</filter>](https://github.com/brinkmanlab/galaxy-tools/blob/277f89a7c9a9ef32e364709a9c45874c7493cf83/mauve_contig_mover/mauve_contig_mover.xml#L78)

[RuntimeValue](https://github.com/galaxyproject/galaxy/blob/acbc8d9ca177b8611977912e3a4bc8643c31c715/lib/galaxy/tools/parameters/basic.py#L2358) is being passed to the filter in place of the dataset. RuntimeValue does not expose the same interface as the dataset object and throws an exception. The same goes for ConnectedValue.

**Comment by mvdbeek** [comment]
That's nothing fatal, this just means your filter doesn't work in the editor. It will work when running the workflow. Nothing to be done there.

**Comment by jmchilton** [comment]
I'd encourage you to replace that filter on datatype with a conditional that prompts the user for an input type - then use a more specific input for each when value and the output can use this when filtering. Imagine mapping a mixed collection over that input - the result is not something Galaxy knows how to handle at all and won't work.

**Comment by innovate-invent** [comment]
@mvdbeek I suppose this issue is more a feature request to provide some information from the ConnectedValue if it is available.
