### ISSUE TITLE
Histories can't be deleted

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8434]
In the most recent version of Galaxy 19.05 there is no menu option to delete a history in the Analyze Data view. 
In the View All Histories view the option is present but clicking either Purge or Delete has no effect. It does not even trigger a network request in the browser.

**Comment by bernt-matthias** [comment]
> In the most recent version of Galaxy 19.05 there is no menu option to delete a history in the Analyze Data view.

There is one in the history menu:

![Screenshot from 2019-08-09 13-39-53](https://user-images.githubusercontent.com/25689525/62776619-6220c700-baab-11e9-8b7e-df1276828867.png)

> In the View All Histories view the option is present but clicking either Purge or Delete has no effect. It does not even trigger a network request in the browser.

I have a similar issue in the tool installation dialogs. In my case the browser is blocking mixed active content. In the Web Developers console I see: `Blocked loading mixed active content ...`. But this doesn't  happen here.

**Comment by martenson** [comment]
The history deletion works for me in both mentioned location. Please provide more details on when this happens.

**Comment by bernt-matthias** [comment]
Same here.

**Comment by martenson** [comment]
@bernt-matthias as in the bug happens to you too, or that it works for you?

**Comment by innovate-invent** [comment]
![image](https://user-images.githubusercontent.com/1768820/62791146-7059ed80-ba81-11e9-81f8-c82a7ed0db90.png)

**Comment by martenson** [comment]
@innovate-invent that is screenshot from `dev`, we have dropped the delete items from the menu to make it less convoluted (https://github.com/galaxyproject/galaxy/pull/8024)

The deletion of histories is available in the 'saved histories' menu.

**Comment by innovate-invent** [comment]
I think my sys admin may have messed up...
It might be worth having some sort of pop-up when accessing that menu that the functionality has moved. I don't think I have ever used the "Saved Histories" view, it took some searching to find it.
