### ISSUE TITLE
Uncaught exception in exposed API method: get_total_size

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#8448]
Uncaught exception in exposed API method:

```
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/jobs.py", line 184, in common_problems
    if input_dataset_instance.get_total_size() == 0:
AttributeError: 'NoneType' object has no attribute 'get_total_size'
```

**Comment by hexylena** [comment]
Which API?

**Comment by bernt-matthias** [comment]
Good question :) That's all I got from the Galaxy logs.

**Comment by hexylena** [comment]
Ah ok, asked because I've been going through old issues and some are not solvable without more info. Have you setup sentry? If not I can recommend it, you'll get much more information and context that will be helpful.

**Comment by bernt-matthias** [comment]
>  I've been going through old issues

LOL. "opened this issue 31 minutes ago"

**Comment by mvdbeek** [comment]
This is also a very new endpoint.

> common_problems

is supposed to help admins debug. I suppose the real issue is that `input_dataset_instance` is a `NoneType`

**Comment by hexylena** [comment]
> asked because I've been going through old issues [not this one] and some [of those old issues] are not solvable without more info

was the key point, worried that this issue would languish like some I had seen today, that had insufficient information to help, so asked for more in case similar things happened here

**Comment by bernt-matthias** [comment]
Sure. Here is a somewhat larger snippet: 

```
[pid: 30033|app: 0|req: 173/246] 127.0.0.1 () {48 vars in 899 bytes} [Mon Aug 12 16:01:08 2019] GET /api/jobs/cd7f0d87752ddad9?full=True => generated 6379 bytes in 75 msecs (HTTP/1.1 200) 3 headers in 139 bytes 
(1 switches on core 0)
galaxy.web.framework.decorators ERROR 2019-08-12 16:01:09,278 [p:30033,w:2,m:0] [uWSGIWorker2Core1] Uncaught exception in exposed API method:
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/jobs.py", line 184, in common_problems
    if input_dataset_instance.get_total_size() == 0:
AttributeError: 'NoneType' object has no attribute 'get_total_size'
```

**Comment by mvdbeek** [comment]
Do you know what tool produced this error ?

**Comment by nsoranzo** [comment]
@bernt-matthias Which Galaxy release are you using? I think this should be fixed by https://github.com/galaxyproject/galaxy/pull/8194 in 19.05.

**Comment by bernt-matthias** [comment]
@mvdbeek unfortunately not. I can not see any common lines preceding the Tracebacks in the logs

@nsoranzo Its 19.05, but I just recently incorporated the latest commits. Haven't seen the error since then. 

I guess we can close it and reopen if necessary.
