### ISSUE TITLE
Old style workflow parameters are not recognised when used in a subworkflow 

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8459]
Galaxy 19.05

Having ${foo} in a tool parameter in a subworkflow is not detected in the parent workflow or at invocation time.

**Comment by mvdbeek** [comment]
I just test this and it seems to work. tests are in https://github.com/mvdbeek/galaxy/blob/e161ca928c3cf799eec05ee618167e02db0df550/lib/galaxy_test/selenium/test_workflow_run.py#L153-L168 as well.
