### ISSUE TITLE
Workflows with tools version replacements are not handled properly.

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#8472]
* Create and save workflow with tool of a particular `version`.
* Change `version` of tool. [old tool `version` is no longer available]

Try to run workflow:
* Workflow gives **warning** message at top that previous version of tool does not exist, have loaded with current version (and to get rid of message, open and save workflow)
* Run workflow --> get server error about missing tool `id`. (so despite 'loading' the run page and seeming like it will work, it does not work)

Try to fix workflow:
* Open workflow in editor, get warning about tool `version`s being changed.
* Select tool with changed version, it displays new `version`.
* Click save
* Workflow appears to save to user, but actually does not -- saved workflow still has old `version`.

Workaround is to open editor and move one of the boxes around before clicking save and trying to run.

**Comment by blankenberg** [comment]
This was seen with a locally installed tool, did not test with toolshed installed tool.

**Comment by mvdbeek** [comment]
> * Run workflow --> get server error about missing tool `id`. (so despite 'loading' the run page and seeming like it will work, it does not work)

I'd be in favor of disallowing this correction mode. If a tool has changed there's a pretty high chance that some outputs have changed or some parameters have, or other surprising things. We should require that the workflow be explicitly updated. Do you agree with this ?

> Workaround is to open editor and move one of the boxes around before clicking save and trying to run.

We can fix that, I'll take a look.

**Comment by dannon** [comment]
Should be resolved with #10570
