### ISSUE TITLE
Cannot install from Toolshed in fresh checkout

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#8484]
On a fresh checkout of `dev`, shed_tool_conf.xml.sample no longer exists, so shed_tool_conf.xml will not end up existing.

UI does not raise any error, but log shows:
```
galaxy.webapps.galaxy.api.tool_shed_repositories DEBUG 2019-08-20 12:18:52,926 [p:93571,w:1,m:0] [uWSGIWorker1Core0] The tool_config_file setting in galaxy.ini must include at least one shed tool configuration file name with a <toolbox> tag that includes a tool_path attribute value which is a directory relative to the Galaxy installation directory in order to automatically install tools from a tool shed into Galaxy (e.g., the file name shed_tool_conf.xml whose <toolbox> tag is <toolbox tool_path="database/shed_tools">).  For details, see the "Installation of Galaxy tool shed repository tools into a local Galaxy instance" section of the Galaxy tool shed wiki at https://galaxyproject.org/installing-repositories-to-galaxy/
```

Can manually restore a shed_tool_conf.xml from a previous .sample as workaround for now...

Most likely occurred around https://github.com/galaxyproject/galaxy/pull/921

Someone should confirm that all needed sample config files are available or being handle properly from a _fresh_ checkout.

**Comment by nsoranzo** [comment]
I thought I fixed this with commit 397be57d0c27d7a16ed716502e3f5cf11afbc59b .

**Comment by nsoranzo** [comment]
Also it's weird the error (which comes from `lib/galaxy/webapps/galaxy/controllers/admin_toolshed.py` ) mentions `galaxy.ini` !

**Comment by martenson** [comment]
I can confirm this.

@nsoranzo the file was just removed, it does not exist in `/lib/galaxy/config/sample/` either. Even when the sample is restored, it will not auto-create the non-sample instance.

**Comment by martenson** [comment]
I think it is supposed to create it on the fly: https://github.com/galaxyproject/galaxy/pull/921/files#diff-cea58efb2821a0da628a91bc6221dd03R41

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/pull/921/files#r318298279

**Comment by martenson** [comment]
fixed by the above
