### ISSUE TITLE
Rule based uploader layers cell selections

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8486]
![image](https://user-images.githubusercontent.com/458683/63423865-7d75c580-c40d-11e9-9fb8-e933b97b389c.png)

Clicking multiple times stacks increasing numbers of divs.

**Comment by jmchilton** [comment]
I can't replicate this - is it possible it has been fixed? Maybe the JS powering the table broke due to some other bug?

**Comment by hexylena** [comment]
Definitely
