### ISSUE TITLE
Refactor configuration schema loading

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#8493]
Currently, default values for configuration properties are specified in `config_schema.yml` files + Python modules (under `config/` for galaxy and `webpapps/` for reports and TS). The values from the `config_schema.yml` files are read in by scripts called from Makefiles (in root + `doc/` directories). The values hardcoded into Python modules are loaded into Configuration objects at startup. Needless to say, this duplication can be eliminated.

Furthermore, in a [recent modification](https://github.com/galaxyproject/galaxy/pull/8475) a property attribute ('reloadable') has been added to the schema. The value of this attribute determines how the property is processed at runtime. Properties marked as 'reloadable', along with their default values are now being read from `webapps/galaxy/schema_config.yml`, whereas all other properties are still assigned default values hardcoded in `config/__init__.py`.

Based on the discussion [here](https://github.com/galaxyproject/galaxy/commit/c5356b298c76c0c65cb288a84dc7caa23a9815bd) (and, to some extent, [here](https://github.com/galaxyproject/galaxy/pull/8475) ), I propose to refactor this, so that `config_schema.yml` is the single source of truth for configuration schema information stored there (default values and more).

If there are no objections, I'd like to take this on.

**Comment by jdavcs** [comment]
The bulk of this work is done: config options (+ their attributes) are loaded from schema. The rest is ongoing refactoring, enhancement, cleanup, etc. 
Keeping this open because there's still much redundancy between the schema and the config processing code.

**Comment by ic4f** [comment]
This can be closed now (see #10172).
