### ISSUE TITLE
Add setting to allow anonymous users to have multiple histories

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8500]
Currently I have to build around this limitation by enabling remote auth and assign a cookie that is copied into the REMOTE_USER header at the proxy.

This complicates having authenticated users as well. 

Ideally there would be a config setting allowing anonymous users to have multiple histories.

**Comment by jmchilton** [comment]
This is really baked into how we handle quota tracking, job security, etc... at a very deep level. I'm going to close this as "won't fix", I don't think the committers want to touch it. If you have specific ideas for how to create temporary users, etc... better I think those would be more worth pursuing.
