### ISSUE TITLE
Rule based uploader allows selecting deleted + error datasets

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8504]
![image](https://user-images.githubusercontent.com/458683/63586915-e93d6700-c5a2-11e9-9882-e23bf83c4e26.png)

**Comment by jmchilton** [comment]
This should almost certainly use @guerler's dataset selector instead of the ad-hoc widget I created as quickly as I could just for this form - see also https://github.com/galaxyproject/galaxy/issues/8505.

**Comment by jmchilton** [comment]
This is a good paper cut and it is two for one with  #8505 - so I'll work on these. I think the only hard part will be updating the selenium tests.
