### ISSUE TITLE
tags color inconsistency and visibility in data set selector

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#8520]
Found some issues with tags: 

- the tag colors shown in the history are different from the colors in the data set chooser.
- no tags are shown for selecting multiple data sets

One might also consider to add the tags of the data sets when creating a collection.

**Comment by hexylena** [comment]
Colour inconsistency is due to the `name:` prefix showing in the selector, should be an easy fix for anyone with time :)

**Comment by mvdbeek** [comment]
I think that's done in https://github.com/galaxyproject/galaxy/pull/9281
