### ISSUE TITLE
Input dataset paths resolving to empty string for all tools

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8522]
I am on commit 9071402e31c372c0b2351789ebb5af057f09368d in the release_19.05 branch.
The deployment was patched with https://github.com/ComputeCanada/galaxy/commit/393132a965ad01d420bfcdf9fb14e0c838541c2c to get it to work on our compute cluster.

Testing the sed tool generates this command output:
```shell
sed --sandbox -r -f '/project/rpp-fiona/ncm3/galaxy-19.05-git/galaxy-database/jobs_directory/000/187/tmpnCGjQF' '' > '/project/rpp-fiona/ncm3/galaxy-19.05-git/galaxy-database/files/000/dataset_221.dat'
```

the `''` before the `>` was supposed to be the input dataset path

This occurs for all tools I have tested.

Further testing a new tool with `<param name="input" ...` and in the command I have `$input $input.ext` gives the extension but not the dataset path.

**Comment by hexylena** [comment]
We saw this on our test instance at one point but could not reproduce, and ended up destroying the VM / rebuilding.

**Comment by innovate-invent** [comment]
Could this be a dependency issue? I am not running in any sort of container and cant destroy the environment.

**Comment by mvdbeek** [comment]
What is happening is that the input dataset is not being created explicitly. Testing against a vanilla 19.05 I can't reproduce this (of course all tests would fail anyway, so no surprise here). Now this might be a complex interaction with the object store, so if you have set up anything special there please let us know.

**Comment by innovate-invent** [comment]
This is running off two filesystems:
/project is hosting the data
/home is hosting the code base
Everything is being kicked off just using the run.sh.

Could this be an issue with the database state? My sysadmin mentioned having to run migrate_db.sh at one point when moving some things around.

**Comment by mvdbeek** [comment]
> Could this be an issue with the database state? My sysadmin mentioned having to run migrate_db.sh at one point when moving some things around.

Very unlikely. So you are not using a custom object_store_conf.xml file ? Have you tried this with other input datasets?

**Comment by innovate-invent** [comment]
the only conf files I have are job_conf.xml and galaxy.yml.

What table stores the path of the datasets? `dataset_source` appears empty...

update:
I just uploaded a new dataset and the issue doesn't occur.

**Comment by mvdbeek** [comment]
aha! How did you get the dataset in, was an asynchronous source or a library dataset ?

**Comment by innovate-invent** [comment]
I just used the upload tool. The datasets that I was originally using were uploaded before the issue came up.

If you can tell me where the dataset paths are stored I can compare it to a backup.

**Comment by mvdbeek** [comment]
> The datasets that I was originally using were uploaded before the issue came up.

Are you sure about that ?

> If you can tell me where the dataset paths are stored I can compare it to a backup.

It isn't, https://github.com/galaxyproject/galaxy/blob/4856e9152cbda24911326114c0a3c8ab92576db3/lib/galaxy/objectstore/__init__.py#L352

The code constructs the path using the dataset id, if you're admin you can see the file path in the UI or in the API.

**Comment by innovate-invent** [comment]
Yea, all datasets were uploaded. Work was done using Galaxy, everything was (sort of, I was trying to isolate an unrelated issue) ok. An issue came up with our filesystem quotas requiring my sysadmin to move the Galaxy codebase to another filesystem. Everything seemed to stand back up ok, except for this issue.

I looked at the dataset information for the new and old datasets. The old one has its Full Path field empty. There is also no error in the logs about the dataset.

Setting `legacy_eager_objectstore_initialization: true` also has no effect.

**Comment by mvdbeek** [comment]
Did this ever re-occur ? Can we close it ?

**Comment by innovate-invent** [comment]
I'll close for now, we are reworking how Galaxy is deployed on our cluster.
