### ISSUE TITLE
Remote User problem with Apache2

### ISSUE THREAD

**Issue by kkech** [galaxyproject/galaxy#8529]
Hi!

I am trying to configure a remote user using Apache2. I followed the guides, I found in the galaxy site, but even I was able to log in and navigate in the galaxy, every time I get this error:

{
“userAgent”: “Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36”,
“onLine”: true,
“version”: “19.05”,
“xhr”: {
“readyState”: 4,
“responseText”: “{“err_msg”: “History is not accessible by user”, “err_code”: 403002}”,
“responseJSON”: {
“err_msg”: “History is not accessible by user”,
“err_code”: 403002
},
“status”: 403,
“statusText”: “Forbidden”
},
“options”: {
“parse”: true,
“data”: “keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter”,
“emulateHTTP”: false,
“emulateJSON”: false,
“textStatus”: “error”,
“errorThrown”: “Forbidden”
},
“url”: “http://dl036.madgik.di.uoa.gr/galax/galaxy/api/histories/f2db41e1fa331b3e?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter”,
“model”: {
“model_class”: “History”,
“id”: “f2db41e1fa331b3e”,
“name”: “Unnamed history”,
“state”: “new”,
“deleted”: false,
“contents_active”: {
“active”: 0,
“deleted”: 0,
“hidden”: 0
},
“contents_states”: {},
“hid_counter”: 1,
“update_time”: “2019-08-26T08:26:03.972Z”,
“user_id”: null,
“importable”: false,
“tags”: [],
“contents_url”: “/galaxy/api/histories/f2db41e1fa331b3e/contents”,
“slug”: null,
“username_and_slug”: null,
“url”: “/galaxy/api/histories/f2db41e1fa331b3e”,
“genome_build”: “?”,
“create_time”: “2019-08-26T08:26:03.972Z”,
“published”: false,
“annotation”: null,
“size”: 0,
“purged”: false,
“nice_size”: “(empty)”
},
“user”: {
“id”: “f2db41e1fa331b3e”,
“username”: “admin”,
“total_disk_usage”: 0,
“nice_total_disk_usage”: “0 bytes”,
“quota_percent”: null,
“is_admin”: false,
“preferences”: {},
“tags_used”: [],
“deleted”: false,
“purged”: false,
“quota”: null
}
}

Also, I would like to know, if I can have both external users (remote user) authentication and also the galaxy to be accessible using credentials directly through the galaxy interface. Now, I am trying to log in directly to the galaxy, but I keep taking this error:

Access to Galaxy is denied
Galaxy is configured to authenticate users via an external method (such as HTTP authentication in Apache), but a username was not provided by the upstream (proxy) server. This is generally due to a misconfiguration in the upstream server.

Please contact your local Galaxy administrator.

Thank you very much.

I have also created a ticket in the help forum:
https://help.galaxyproject.org/t/remote-user-problem-with-apache2/1994

**Comment by nsoranzo** [comment]
Replied on the help forum.
