### ISSUE TITLE
Mixed Content error not loading some parts of the UI

### ISSUE THREAD

**Issue by ieguinoa** [galaxyproject/galaxy#8557]
Hi,

I'm having a problem loading the centre panel of the main page of our server.
The panel is just not loading and the error I'm getting is:

libs.chunk.js?v=1567073605:66 Mixed Content: The page at 'https://usegalaxy.be/' was loaded over HTTPS, but requested an insecure resource 'http://usegalaxy.be/static/welcome.html'. This request has been blocked; the content must be served over HTTPS.

- The panel loads correctly if I allow loading of unsafe content (Chrome) or similar in Firefox
- In our setup SSL encryption is provided through Apache. 
- The error is of course not occurring  when ssl is disabled.
- The error started with v19.05 but we jumped from v18.05 to 19.05 so can't tell if the error would have happened with any of the intermediate versions.
- I saw a similar problem reported here: https://github.com/galaxyproject/galaxy/issues/7610
where it says it was solved by migrating the proxy from Apache to nginx so I assume it could be the same problem that we are facing but we would like to avoid that for the moment.

Thanks in advance.
Ignacio

**Comment by bernt-matthias** [comment]
Any chance that you switch to NGINX? This solved problems with mixed contents for us .. which also indicates that the problem is due to Apache - not Galaxy.

**Comment by ieguinoa** [comment]
That's not an option right now but we are planning to do that in the near future. Would be great if we can solve this somehow now, even if its an ugly solution and then we will move everything to nginx.

any ideas?

**Comment by bernt-matthias** [comment]
Unfortunately not.

**Comment by hexylena** [comment]
Did you set the variable that it's an https proxy? 

```
# Galaxy needs to know that this is https for generating URLs
RequestHeader set X-URL-SCHEME "%{REQUEST_SCHEME}e"
```

**Comment by ieguinoa** [comment]
Great, that did the trick! 
Thanks @erasche
