### ISSUE TITLE
Apply rule to collection, filter rows rule invert tooltip reversed

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8563]
The tooltip for 'invert' in the the filter rows rule says the opposite of what it does.

![image](https://user-images.githubusercontent.com/1768820/64194463-0ccea000-ce34-11e9-8c6b-209f8a7788b1.png)

Selecting invert removes all rows matching the supplied value.

**Comment by martenson** [comment]
the string is [here](https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/components/RuleCollectionBuilder.vue#L1008)

**Comment by assuntad23** [comment]
Merged with #11204
