### ISSUE TITLE
Relabel List Identifiers more restrictive than tool to build collection

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8564]
https://github.com/galaxyproject/galaxy/blob/e9d8c900cb2a6e794b90a99e351c281b71d9123e/lib/galaxy/tools/__init__.py#L2966

There is no real specification on what is and isn't permitted in a collection element identifier.
This restricts it to nothing more than alpha-numeric, dash, and underscore. That is more restrictive than the upload tool to create collections.

**Comment by bernt-matthias** [comment]
Do you know of any restrictions in the upload tool, or is it simply unrestricted. 

As far as I remember from discussions here https://github.com/galaxyproject/galaxy/pull/7937 (an maybe linked PRs) the consens seems to be that identifiers can be anything, i.e. no restrictions. 

I like to ask you to open a PR  removing this if branch. Lets see what the community thinks about this. 

Just for you information: many tools will strip such characters (all other chars not in `[\w\-_]`) from the identifiers, so it not a good idea to use such characters anyway.

**Comment by innovate-invent** [comment]
Can you provide an example of another tool that will strip characters?

**Comment by bernt-matthias** [comment]
Please note first that there is a good reason for stripping. In all cases the identifiers are to be used as file names where special characters make create all sorts of problems: 

Searching the IUC tools with `grep -r "re.sub" tools | grep ident| cut -d":" -f1 | sort | uniq  ` gave this list:

tools/bedtools/intersectBed.xml
tools/cutadapt/cutadapt.xml
tools/diffbind/diffbind.xml
tools/fastp/fastp.xml
tools/fastqc/rgFastQC.xml
tools/fermikit/fermikit_run_calling.xml
tools/gffcompare/gffcompare.xml
tools/hicexplorer/hicPlotDistVsCounts.xml
tools/intervene/macros.xml
tools/macs2/macs2_callpeak.xml
tools/mageck/mageck_count.xml
tools/mothur/filter.seqs.xml
tools/mothur/make.group.xml
tools/multiqc/multiqc.xml
tools/picard/picard_macros.xml
tools/picard/picard_NormalizeFasta.xml
tools/quast/quast.xml
tools/rseqc/geneBody_coverage.xml
tools/rseqc/read_hexamer.xml
tools/scpipe/scpipe.xml
tools/slamdunk/alleyoop.xml
tools/slamdunk/slamdunk.xml
tools/snippy/snippy.xml
tools/stringtie/stringtie.xml
tools/taxonomy_krona_chart/taxonomy_krona_chart.xml
tools/trinity/abundance_estimates_to_matrix.xml
tools/trinity/analyze_diff_expr.xml
tools/umi_tools/umi-tools_counts.xml

**Comment by innovate-invent** [comment]
That is actually exactly what I am doing with my workflow. Identifiers are being used as file names and so I am escaping all POSIX special characters:

```awk
function escape_posix(a) {
    gsub("\\[", "[esc]", a); # Must be first
    gsub("&", "[amp]", a);
    gsub("/", "[slash]", a);
    gsub("\\", "[baskslash]", a);
    gsub("\\?", "[question]", a);
    gsub("%", "[percent]", a);
    gsub("\\*", "[star]", a);
    gsub(":", "[colon]", a);
    gsub("\\|", "[pipe]", a);
    gsub("\"", "[dblquot]", a);
    gsub("<", "[lt]", a);
    gsub(">", "[gt]", a);
    gsub("\\.", "[dot]", a);
    gsub(" ", "[space]", a);
    gsub("\t", "[tab]", a);
    gsub("'", "[quot]", a);
    return a;
}

function unescape_posix(a) {
    gsub("\\[amp]", "&", a);
    gsub("\\[slash]", "/", a);
    gsub("\\[baskslash]", "\\", a);
    gsub("\\[question]", "\\?", a);
    gsub("\\[percent]", "%", a);
    gsub("\\[star]", "\\*", a);
    gsub("\\[colon]", ":", a);
    gsub("\\[pipe]", "\\|", a);
    gsub("\\[dblquot]", "\"", a);
    gsub("\\[lt]", "<", a);
    gsub("\\[gt]", ">", a);
    gsub("\\[dot]", "\\.", a);
    gsub("\\[space]", " ", a);
    gsub("\\[tab]", "\t", a);
    gsub("\\[quot]", "'", a);
    gsub("\\[esc]", "[", a); #Must be last
    return a;
}
```

The issue is that the current filter is over restrictive.

**Comment by bernt-matthias** [comment]
Sure. Lets see what others think about the PR. Thanks for that.

**Comment by innovate-invent** [comment]
Turns out the program I am wrapping takes issue with a large number of filename characters.
I had to go with this in the end:
```awk
# Extract sequence ids and associate to current collection id
function escape_posix(a) {
    gsub("_", "_esc_", a); # Must be first
    gsub("&", "_amp_", a);
    gsub("/", "_slash_", a);
    gsub("\\", "_baskslash_", a);
    gsub("\\?", "_question_", a);
    gsub("%", "_percent_", a);
    gsub("\\*", "_star_", a);
    gsub(":", "_colon_", a);
    gsub("\\|", "_pipe_", a);
    gsub("\"", "_dblquot_", a);
    gsub("<", "_lt_", a);
    gsub(">", "_gt_", a);
    gsub("\\.", "_dot_", a);
    gsub(" ", "_space_", a);
    gsub("\t", "_tab_", a);
    gsub("'", "_quot_", a);
    return a;
}

function unescape_posix(a) {
    gsub("_amp_", "&", a);
    gsub("_slash_", "/", a);
    gsub("_baskslash_", "\\", a);
    gsub("_question_", "\\?", a);
    gsub("_percent_", "%", a);
    gsub("_star_", "\\*", a);
    gsub("_colon_", ":", a);
    gsub("_pipe_", "\\|", a);
    gsub("_dblquot_", "\"", a);
    gsub("_lt_", "<", a);
    gsub("_gt_", ">", a);
    gsub("_dot_", "\\.", a);
    gsub("_space_", " ", a);
    gsub("_tab_", "\t", a);
    gsub("_quot_", "'", a);
    gsub("_esc_", "_", a); #Must be last
    return a;
}
```
