### ISSUE TITLE
Document: Tool datatypes_conf.xml

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8565]
Looking at the toolshed there appears to be some mechanism in Galaxy that allows to distribute custom datatypes with a tool. I can't find any documentation as to how this all works.

Does a tools datatypes_conf.xml support the full schema of the Galaxy datatypes_conf.xml?

How are these merged?

When installing a tool not from the tool shed, how is the tools datatypes_conf.xml referenced?

When installing a tool from the tool shed, does it automatically locate the tools datatypes_conf.xml?

Are there path requirements for a tool datatypes_conf.xml within the tools repository?

**Comment by martenson** [comment]
All datatypes should be defined in Galaxy, making them installable from TS was an experiment that has proven to be short-sighted. See https://github.com/galaxyproject/galaxy/pull/8531

**Comment by innovate-invent** [comment]
How do you distribute a tool with a custom datatype without being dependent on a future galaxy version?

**Comment by martenson** [comment]
You don't. Just add the datatype to Galaxy codebase, we will merge it.

**Comment by innovate-invent** [comment]
That requires some jenky workarounds then. You literally have to wait for everyone to update their Galaxy version before they can use your tool.

**Comment by martenson** [comment]
Correct, or for local usage run a Galaxy fork.

**Comment by innovate-invent** [comment]
That will only encourage people to write tool wrappers that output 'txt' files rather than properly labeling the structured text based format that it actually outputs.
There is also the issue that many bioinformatics tools invent their own crappy formats. Are you going to merge data types that only apply to specific, obscure, tool suites?

**Comment by martenson** [comment]
You can explore how we handle new datatypes by researching what datatype PRs look like: https://github.com/galaxyproject/galaxy/pulls?q=is%3Aopen+is%3Apr+label%3Aarea%2Fdatatypes

For the future we are separating datatypes into a subpackage together with other data-related functionality. This package won't have to follow main release schedule. https://github.com/galaxyproject/galaxy/tree/dev/packages/data
