### ISSUE TITLE
Multiple = true input does not accept list:list when tool already mapped over

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8587]
A tool that is already mapped over will not allow a list:list connection to a multiple = true input.
Each sublist should pair with the other input element that is being mapped.

**Comment by jmchilton** [comment]
I think it generally does, but you may need to be careful the order you connect nodes in. We've gotten better at displaying details around connection of nodes.

**Comment by innovate-invent** [comment]
I just tested in 20.09. Looks like it works now.
