### ISSUE TITLE
Chromosome naming conventions

### ISSUE THREAD

**Issue by malloryfreeberg** [galaxyproject/galaxy#860]
I often find myself having to reformat chromosome names within uploaded datasets depending on where I acquired the dataset. For example, I've seen the mitochondrial chromosome referred to as "chrmt", "chrM", "chrmtdna", "chrMtDNA" etc. I've also seen names like "chr01" instead of "chrI", and it is a pain to manually change the naming scheme depending on what the Galaxy tools or Trackster requires.

Is there a way that chromosome names can be automatically reformatted for whichever tool is being executed?

**Comment by jennaj** [comment]
+1 on the idea!

Related and perhaps a precursor is providing mappings between ref genomes that are known to be based on the same assembly build plus workflows to do the replacement. That idea is captured in this ticket: https://trello.com/c/ASSc3im6 

Maybe merge the two. Automatic mapping is certainly nicer than a library of mappings and workflows. The gotcha here is in ensuring that the mapped identifiers are in fact from the same exact ref genome assembly/build. But that seems like a solvable issue.

The mappings in the Trello ticket above are just one public option vetted by the larger bioinfo community. These could be curated in other ways. And if the solution included options for user-given "custom mappings" (to be used in a published workflow that did the remapping, or by a built-in method), this would be super useful for many.

**Comment by bgruening** [comment]
@jennaj the plan is to have a deeptools tool that uses these files for mapping. I will keep you posted.

**Comment by jennaj** [comment]
Wow, this will be a huge deal if it works out. Thanks so much @bgruening and @dpryan79 for considering the ideas to make the mappings simpler (and integrated!!!).

**Comment by dpryan79** [comment]
@bgruening Ah, so this is what inspired that idea that you mentioned earlier! Whether its via deepTools or something else it would be nice to incorporate this into Galaxy.

**Comment by bgruening** [comment]
@dpryan79 indeed - user requests are the best.
xref: https://github.com/dpryan79/ChromosomeMappings/issues/6

**Comment by jennaj** [comment]
This looks old so am closing out. 

For end-users, try this tool: `Replace column by values which are defined in a convert file`. It will require a "convert" file -- some are already curated/available for common genome build/versions, or you can create and use your own.

For administrators, the tool is in the ToolShed here: https://toolshed.g2.bx.psu.edu/view/bgruening/replace_column_by_key_value_file/d533e4b75800
