### ISSUE TITLE
Login fails if e-mail in different case than stored in the database

### ISSUE THREAD

**Issue by hgsommer** [galaxyproject/galaxy#8602]
The galaxy server in question uses authentication via LDAP exclusively, with auto-registration enabled. The e-mail address returned from the LDAP server for a specific user is in the form `User.Name@example.org` (note the upper case letters), but stored in the galaxy database completely in lower case. If the user tries to log in using the e-mail address, the login fails with the following message: `Auto-registration failed, contact your local Galaxy administrator. User with that email already exists.`

**Comment by nsoranzo** [comment]
That's true, I've seen this in the form of users using different capitalisations of their email address and ending up with a new user.
