### ISSUE TITLE
/api/genomes returns invalid record

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8612]
https://github.com/galaxyproject/galaxy/blob/a6ccf05a8837903d66dd3bc3482f6674a690a81c/lib/galaxy/util/__init__.py#L1205-L1206

The above code stuffs an unexpected record into the response. Why is this?

**Comment by assuntad23** [comment]
I don't think this is a bug. 
It's the default value, which is important for uploads that we don't know the dbkey of yet. It allows users to select the dbkey themselves, when they edit the dataset.  It is also possible that we don't have the dbkey for their genome in our list. 

In short, I think appending the default value the correct thing to do.

**Comment by mvdbeek** [comment]
Definitely a bug though, `----- Additional Species Are Below -----'` should not be in the API response

**Comment by assuntad23** [comment]
Well then, where do you propose we add it, just in the UI?

**Comment by mvdbeek** [comment]
Yes

**Comment by assuntad23** [comment]
Alright - I can work on that a bit.

**Comment by assuntad23** [comment]
Fixed in #12481
