### ISSUE TITLE
python-ldap on python3

### ISSUE THREAD

**Issue by selten** [galaxyproject/galaxy#8615]
When setting up 19.09 on python3 (probably this doesn't just affect 19.09) and using LDAP as authentication mechanism, it tries to use python-ldap version 2.4.44 however this gives the following error:
```python
  Downloading https://files.pythonhosted.org/packages/bb/6c/ad05e4d337bd0079d830604ec0cbcafa2b7ddd4376030cc14dde0e15766e/python-ldap-2.4.44.tar.gz (298kB)
    100% |████████████████████████████████| 307kB 26.6MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ofdbvfak/python-ldap/setup.py", line 53
        print name + ': ' + cfg.get('_ldap', name)
                 ^
    SyntaxError: invalid syntax	
```

I switched the dependency to 3.2.0 in https://github.com/galaxyproject/galaxy/blob/release_19.09/lib/galaxy/dependencies/conditional-requirements.txt. I will comment on this once I confirm that this works.

**Comment by nsoranzo** [comment]
@selten Thanks for the report! We already have wheels for python-ldap 3.2.0 at https://wheels.galaxyproject.org/simple/python-ldap/ , so if that works for you can you please open a pull request to update the `conditional-requirements.txt` file?
