### ISSUE TITLE
Apache UWSGI Proxy

### ISSUE THREAD

**Issue by ocfmatt** [galaxyproject/galaxy#8624]
Hello,

I've installed a fresh clean copy of Galaxy 19.05 for a customer and successfully setup Apache as a URL prefixing proxy on http using a UWSGI tcp socket. To improve security, the proxy needed to be moved to https so I went about setting this up following https://docs.galaxyproject.org/en/master/admin/apache.html

When Galaxy was moved to https session cookies were not being written correctly so anything accessing galaxy root (FQDN/galaxy) was failing back to the login screen. Anything in a non-root a path (eg FQDN/galaxy/admin FQDN/galaxy/workflows) worked leading to much confusion.

Several hours later I've found the cookie_path needs to be set in galaxy.yml directly contradicting:
```
Older versions of Galaxy required you to set the cookie_path option. 
This is no longer necessary as of Galaxy release 19.05 as it is now set automatically, 
but the (now undocumented) option still remains and overrides the automatic setting. 
If you have this option set, unset it unless you know what you’re doing.
```

My OS is CentOS 7.6.
Relevant Apache packages:
```
httpd-2.4.6-89.el7.centos.1.x86_64
mod_proxy_uwsgi-2.0.17.1-2.el7.x86_64
mod_ssl-2.4.6-89.el7.centos.1.x86_64
```

Under normal circumstances of serving Galaxy with a URL prefix should the cookie_path option be needed or have I misinterpreted the extract from the docs I posted above?

Happy to provide any further information that might be needed to verify whether a bug is present.

Regards,
Matt.

**Comment by martenson** [comment]
I hope this has been resolved.
