### ISSUE TITLE
Galaxy left panel scrollbar hidden

### ISSUE THREAD

**Issue by shenweiyan** [galaxyproject/galaxy#8626]
The left panel scrollbar of https://test.galaxyproject.org/ was hidden on my Chrome as well as  Galaxy release 19.09. My screen resolution: 1366 x 768.
![Galaxy test home page](https://user-images.githubusercontent.com/26101369/64746675-172d2000-d53f-11e9-8e8d-999a006f2387.png)

**Comment by martenson** [comment]
@shenweiyan is this on Windows? Can you please try firefox?

**Comment by shenweiyan** [comment]
> @shenweiyan is this on Windows? Can you please try firefox?

Yes, it is on Windows 7.  And here is the screenshot on my Firefox:
![firefox screenshot for galaxy test ](https://user-images.githubusercontent.com/26101369/64930390-f298b700-d862-11e9-9bed-e7ce7536e47d.png)

**Comment by shenweiyan** [comment]
The left panel scrollbar was still hidden on https://usegalaxy.org/, when will this problem fix?
