### ISSUE TITLE
Pagination / scrolling on new tool shed install interface is not obvious on large screens 

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#8653]
At first I thought there was an issue listing the categories, but if I make the window smaller scrolling down will fetch more repositories. There's no visual indication that scrolling will load more repos.

![Screenshot 2019-09-17 at 13 50 55](https://user-images.githubusercontent.com/6804901/65040231-33bcc400-d954-11e9-9ee8-8b2b0182af8c.png)

**Comment by martenson** [comment]
Are you on latest release? https://github.com/galaxyproject/galaxy/pull/8621 increased the default page size to 50 in order to help this. It is still a good idea to explicitly indicate.

edit: you are also missing the clear button and more, please update.

**Comment by mvdbeek** [comment]
Yeah, increasing page size is a good workaround. Wanna close ?

**Comment by martenson** [comment]
@mvdbeek I'd like to rephrase it into infinite scrolling implementation improvement if you don't mind.

**Comment by mvdbeek** [comment]
sure

**Comment by martenson** [comment]
I'll actually open it fresh :)
