### ISSUE TITLE
shed requires options to boot it shouldn't

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#8656]
https://github.com/galaxyproject/usegalaxy-playbook/commit/294f464d67bc30a898ce223aad37cd6aa77ff1d5

stacktrace of failed boot: https://gist.github.com/martenson/374e8e24e25034228d085953b9e87a09#file-gistfile1-txt

TS boot should also never go this path I think: `galaxy.tool_util.deps.installable WARNING 2019-09-10 11:57:13,602 [p:31286,w:0,m:0] [MainThread] Conda not installed and auto-installation disabled.`

**Comment by jdavcs** [comment]
~~This may have been caused (indirectly)~~ by https://github.com/galaxyproject/galaxy/pull/8573 . (apparently, not) 
In any case, I'm looking into it.
