### ISSUE TITLE
Installing tool via api does not install full repository

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8671]
I installed the RGI tool from the toolshed via the api. It installed ok but the data manager in the same repo did not also get installed. There was no way to install the data manager individually via the admin ui either. I had to uninstall the tool and reinstall everything via the admin ui.

**Comment by mvdbeek** [comment]
Can't reproduce this on 19.09 (which uses the API) or 19.05 (which uses the controller).
