### ISSUE TITLE
interactive environments fail to load

### ISSUE THREAD

**Issue by jkanche** [galaxyproject/galaxy#8682]
I understand there's a new API for interactive environments/tools. but also testing existing IE's fail on the current dev branch.

I am also working on my own IE (works with galaxy 19.05), but has issues on the most recent dev branch. When i choose the IE, I can see in the console that it did spin up the docker instance, but fails to load.

First, Is there a migration guide for the new interactive environments/tools API ? or a hello-world-ie example ? 

Thank you very much for your help!

**Comment by jkanche** [comment]
one of the errors is 

> galaxy.web.proxy DEBUG 2019-09-20 08:17:42,402 [p:28099,w:1,m:0] [uWSGIWorker1Core2] Cmd: lib/galaxy/web/proxy/js/lib/main.js --sessions /home/jayaram/Desktop/projects/planemo/galaxy/database/database/session_map.sqlite --ip 0.0.0.0 --port 8800 --reverseProxy --verbose
> galaxy.visualization.plugins.plugin ERROR 2019-09-20 08:17:42,402 [p:28099,w:1,m:0] [uWSGIWorker1Core2] IE plugin template fill failed
> Traceback (most recent call last):
>   File "lib/galaxy/visualization/plugins/plugin.py", line 277, in _render
>     return trans.fill_template(template_filename, template_lookup=self.template_lookup, **render_vars)
>   File "lib/galaxy/web/framework/webapp.py", line 936, in fill_template
>     return self.fill_template_mako(filename, **kwargs)
>   File "lib/galaxy/web/framework/webapp.py", line 949, in fill_template_mako
>     return template.render(**data)
>   File "/home/jayaram/Desktop/projects/planemo/galaxy/.venv/lib/python2.7/site-packages/mako/template.py", line 476, in render
>     return runtime._render(self, self.callable_, args, data)
>   File "/home/jayaram/Desktop/projects/planemo/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py", line 883, in _render
>     **_kwargs_for_callable(callable_, data)
>   File "/home/jayaram/Desktop/projects/planemo/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py", line 920, in _render_context
>     _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
>   File "/home/jayaram/Desktop/projects/planemo/galaxy/.venv/lib/python2.7/site-packages/mako/runtime.py", line 947, in _exec_template
>     callable_(context, *args, **kwargs)
>   File "/home/jayaram/Desktop/projects/planemo/galaxy/database/compiled_templates/jupyter.mako.py", line 73, in render_body
>     'additional_ids': additional_ids if not ie_request.use_volumes else None,
>   File "lib/galaxy/visualization/plugins/interactive_environments.py", line 533, in launch
>     self._launch_legacy(image, env_override, volumes)
>   File "lib/galaxy/visualization/plugins/interactive_environments.py", line 460, in _launch_legacy
>     container_ids=[container_id],
>   File "lib/galaxy/web/proxy/__init__.py", line 75, in setup_proxy
>     container_interface,
>   File "lib/galaxy/web/proxy/__init__.py", line 260, in handle_requests
>     with FileLock(self.proxy_session_map):
>   File "lib/galaxy/util/filelock.py", line 68, in __enter__
>     self.acquire()
>   File "lib/galaxy/util/filelock.py", line 43, in acquire
>     self.fd = os.open(self.lockfile, os.O_CREAT | os.O_EXCL | os.O_RDWR)
> OSError: [Errno 2] No such file or directory: '/home/jayaram/Desktop/projects/planemo/galaxy/database/database/session_map.sqlite.lock'

**Comment by jmchilton** [comment]
Any clue how the ``database/database/`` appears in the configs? That would seem to be the problem - I'm not sure if that is a problem with the default config or how you configured it or if something changed recently.

**Comment by jdavcs** [comment]
that *could be* related to the recent config system updates. I'm checking..

**Comment by jdavcs** [comment]
If the config value for `dynamic_proxy_session_map` is set to the previously suggested default, `database/session_map.sqlite`, it will be then resolved w.r.t the current `data_dir` ("database"), which will cause the final path to contain "database/database". 

The solution to this is under revision in #8689 (it's functional, so should be ready for merge as soon as code review+revision is done - any day). Ping @natefoo @nsoranzo : unless I am mistaken, that's an example of what we've been discussing. @jkanche : sorry for the inconvenience! Working on it.

EDIT: @jkanche : I suggest removing "database/" from the current config, if that is the case.

**Comment by jmchilton** [comment]
Closing this because we've largely dropped support for IEs, hopefully it is not still a problem.
