### ISSUE TITLE
sqlite3 error when starting interactive environment

### ISSUE THREAD

**Issue by sunyi000** [galaxyproject/galaxy#8706]
I'm exploring IEs in Galaxy 19.05. My node version is 10.16.3, npm version 6.9.0

after npm install in 
lib/galaxy/web/proxy/js , 
I have got node-v64-linux-x64 folder in 
node_modules/sqlite3/lib/binding/

however when IE starts up, I can see in galaxy error log, it looks for node-v59-linux-x64 instead.
I have tried npm rebuild,but it does not help, I'm not sure why galaxy keeps looking for the old version.

Thanks for any helps

**Comment by jmchilton** [comment]
We've largely dropped support for IEs so I'm going to close this, I hope that is okay. There have been some updates to the dependencies that have hopefully solved the problem - if not you may want to check out https://github.com/galaxyproject/gx-it-proxy
