### ISSUE TITLE
Galaxy fails to install tools with dependencies

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#8715]
On dev when I do not set `tool_dependency_dir` in galaxy.yml it should default to `database/dependencies` but instead installation fails.

cc @ic4f @guerler @natefoo 

```
  # Various dependency resolver configuration parameters will have
  # defaults set relative to this path, such as the default conda
  # prefix, default Galaxy packages path, legacy tool shed dependencies
  # path, and the dependency cache directory.  Set the string to None to
  # explicitly disable tool dependency handling. If this option is set
  # to none or an invalid path, installing tools with dependencies from
  # the Tool Shed or in Conda will fail.
  #tool_dependency_dir: database/dependencies
```

`err_msg: "Tool dependencies can be automatically installed only if you set the value of your 'tool_dependency_dir' setting in your Galaxy configuration file (galaxy.ini) and restart your Galaxy server.  "`

**Comment by jdavcs** [comment]
I'm looking into it.

**Comment by jdavcs** [comment]
`tool_dependency_dir` was never set in `config/__init__` in 19.09. It *was*, however, in 19.05. - that's where it was set to what's in kwargs or `database/dependencies` by default. 

With the new config it's (currently) automatically set to `dependencies`, and **not** resolved w.r.t anything, at least not in `config/__init.py__`. #8689 should fix that (it's under review, should be ready shortly, once code review is resolved - working on it at the moment).

However, if this is an issue now, we can simply do a quick temporary hack and add this:
```python
if self.tool_dependency_dir:
    self.tool_dependency_dir = os.path.join(self.data_dir, self.tool_dependency_dir)
```
adding it here: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/__init__.py#L231

I can make this PR in a few minutes, if that's a reasonable temporary solution.

**Comment by martenson** [comment]
> tool_dependency_dir was never set in config/__init__ in 19.09

19.09 works without explicitly setting `tool_dependency_dir`

xref: https://github.com/galaxyproject/galaxy/commit/8b423a7c82f92a1caef17a5a4e14a000f2100be7#diff-cea58efb2821a0da628a91bc6221dd03L1163

**Comment by jdavcs** [comment]
Then, I think, it must be caused by one of the more recent changes to dev, but not to `config/__init__.py`. In any case, the upcoming 8689 should fix this.

**Comment by martenson** [comment]
@ic4f `ic4f:sg_config12` demonstrates the same issue

**Comment by jdavcs** [comment]
That's not good. I'll look into it after lunch. It must be overwritten somewhere, because as far as the `GalaxyAppConfiguration` object is concerned, it's set to the schema default and resolved to `data_dir`, unless the user sets it to null.

**Comment by nsoranzo** [comment]
@ic4f The `config.tool_dependency_dir` is unused, have a look at https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tool_util/deps/__init__.py which uses `config.config_dict`

**Comment by jdavcs** [comment]
@nsoranzo thanks!

**Comment by jdavcs** [comment]
Can't reproduce this on dev. `database/dependencies` is recreated if value unset in galaxy.yml.

**Comment by nsoranzo** [comment]
I think this has been solved, please reopen otherwise.

**Comment by martenson** [comment]
On latest dev it works, 23 commits back it does not. Thanks for fixing to whoever fixed it.

**Comment by nsoranzo** [comment]
I fixed it in https://github.com/galaxyproject/galaxy/commit/edc22b353bf5585bae3d86cac799d6a2850b15bc#diff-cea58efb2821a0da628a91bc6221dd03R1170

**Comment by martenson** [comment]
@nsoranzo That is just a revert, right? It still hardcodes something that should be configurable.

**Comment by nsoranzo** [comment]
@martenson Yes, it's a revert to the 19.09 code. `default_tool_dependency_dir` must be the same value used as default for `tool_dependency_dir` in Galaxy config (so not configurable). This default is not accessible from `build_dependency_manager`, which is part of the `tool_util` package, so needs to be passed from `_init_dependency_manager()`  (code linked above).
The only generalisation we can apply it to change that line to:

```python
        default_tool_dependency_dir = os.path.join(self.app.config.data_dir, self.app.config.appschema['tool_dependency_dir'].get('default'))
```

Not sure it's worthy, but I'd approve such a PR.

**Comment by martenson** [comment]
@nsoranzo I opened it: https://github.com/galaxyproject/galaxy/pull/8731

**Comment by jdavcs** [comment]
That would be a *very* good change because that would get rid of hardcoding "dependencies". Maybe also this: https://github.com/galaxyproject/galaxy/commit/edc22b353bf5585bae3d86cac799d6a2850b15bc#diff-b8221cd7ed7a26d1f22a110d8490a841R296

**Comment by martenson** [comment]
@ic4f feel free to push that change to my branch

**Comment by jdavcs** [comment]
@martenson  in a min

**Comment by nsoranzo** [comment]
@ic4f There you would need to read it from `lib/galaxy/webapps/galaxy/config_schema.yml` , which I don't think it's worthy.

**Comment by jdavcs** [comment]
@nsoranzo i agree - was just about to say that there's no way of getting to the app object, so, @martenson  i take it back.
