### ISSUE TITLE
Interactive tool simple

### ISSUE THREAD

**Issue by rdallet** [galaxyproject/galaxy#8723]
Hi,

I am testing interactive tools in order to make my owns but I encounter some difficulties with the "interactive tool simple" in my local instance (last pull from the dev branch 26/09).

I copied pasted it from `test/functional/tools/` to `tools/interactive/`, and added the configurations needed following the documentation in `doc/source/admin/special_topics/interactivetools.rst`. I also added the `galaxy_infrastructure_url` configuration.

The problem is the first time I run the tool, it works fine. But the second time I execute it (and the nexts), the tool "waiting for view to become active". And in the `User -> Active Interactive tools` menu, tool name is not clickable.

Does anyone have a solution?

**Comment by rdallet** [comment]
If this can help you, I also tried to rerun manually the "interactive tool simple" by executing the `galaxy/database/jobs_directory/000/XX/galaxy_XX.sh` file.

This makes the tool active but stop the docker container.


And I also rerun manually the galaxy_XX.sh file without :
```
_on_exit() {
  docker kill 795cfd323a1f4756aa6a16bd86fe926e &> /dev/null
}
trap _on_exit 0
```
This makes the tool active but when I click on the tool name, the redirection doesn't work and disconnects me of my instance (as user).

**Comment by rdallet** [comment]
Do you have any idea? @bgruening @blankenberg

**Comment by bgruening** [comment]
We see this from time to time as well ... but we are running 10s of containers in parallel and our assumption was that something with concurrent writes to sqlite is not correct. Can you check if you have a containres_runtime.json file in your job directory - next to your tool_script.sh? What is the content?

**Comment by rdallet** [comment]
I have a container_runtime.json file. Here is the content : 
```
{"7000": {"tool_port": 7000, "host": "0.0.0.0", "protocol": "tcp", "port": 32808}}
```

**Comment by bgruening** [comment]
@RomainDallet you are running everything on localhost? Normal standard local job runner?

**Comment by rdallet** [comment]
Yes, everything running on localhost.

**Comment by bgruening** [comment]
Mh ... can you please look into your interactivetools.sqlite file ... with e.g. sqlitebrowser and tell us what is included if you start a few IEs. Btw. is any other IE working?

**Comment by bgruening** [comment]
Try also removing this sqlite file.

**Comment by rdallet** [comment]
Can I ask you where the interactive tool sqlite file is located? I don't find it.

EDIT : Ok, find it!

And no other IE working.

**Comment by rdallet** [comment]
sqlite file content : 
```
   "host": "0.0.0.0",
        "info": "",
        "key": "5564089c81cf7fe8",
        "key_type": "interactivetoolentrypoint",
        "port": "32778",
        "token": "2e771672c1ed4104b1d9b7329f151c7b"
    },
    {
        "host": "0.0.0.0",
        "info": "",
        "key": "6fc9fbb81c497f69",
        "key_type": "interactivetoolentrypoint",
        "port": "32799",
        "token": "7df17502cfe64791935b96d8a29c69ba"
    },
    {
        "host": "0.0.0.0",
        "info": "",
        "key": "5114a2a207b7caff",
        "key_type": "interactivetoolentrypoint",
        "port": "32801",
        "token": "2dfdb177628c4e8d80c4d25bea5a91ca"
    },
    {
        "host": "0.0.0.0",
        "info": "",
        "key": "06ec17aefa2d49dd",
        "key_type": "interactivetoolentrypoint",
        "port": "32802",
        "token": "b4541f5f261940ee8d02c9c3eee671bf"
    },
    {
        "host": "0.0.0.0",
        "info": "",
        "key": "24d84bcf64116fe7",
        "key_type": "interactivetoolentrypoint",
        "port": "32804",
        "token": "76b2153b03894794b8397bbd95b55ab8"
    },
    {
        "host": "0.0.0.0",
        "info": "",
        "key": "500665cb113baad6",
        "key_type": "interactivetoolentrypoint",
        "port": "32805",
        "token": "6bed8391ca4f4951a923e11ce8e6b8c2"
    },
    {
        "host": "0.0.0.0",
        "info": "",
        "key": "290670ee50ab85f0",
        "key_type": "interactivetoolentrypoint",
        "port": "32808",
        "token": "f0c62348fcf74d51a6b435627abef843"
  }
```

**Comment by rdallet** [comment]
I try to delete the sqlite file and when I run the interactive tool after nothing change. Still "waiting for view to become active"

And the new sqlite file looks like :

```
[
    {
        "host": "0.0.0.0",
        "info": "",
        "key": "c851ab275e52f8af",
        "key_type": "interactivetoolentrypoint",
        "port": "32769",
        "token": "37309194f5294890b74a1285f21efdb3"
    }
]
```

**Comment by rdallet** [comment]
Hi @bgruening ,

I started again from the beginning with a pull of the last release (19.09) and Sqlite issues were solved. I don't know what was wrong before (I was also in 19.09) but it's ok now.

I just have, I hope, an ultime issue. When I click on my active interactive tool, it doesn't run in the main center panel but in another page. Here is the URL I got: `http://4b187121143038ff-498c376daedc4133abeb72abba1dbf61.interactivetoolentrypoint.interactivetool.localhost:8080/`

Do you think it's a configuration error?

interactivetools_map.sqlite content : 
```json
{
        "host": "127.0.1.1",
        "info": "",
        "key": "4b187121143038ff",
        "key_type": "interactivetoolentrypoint",
        "port": "32773",
        "token": "498c376daedc4133abeb72abba1dbf61"
}
```

**Comment by jmchilton** [comment]
Looks like this got resolved? Hopefully interactive tools have gotten a little more robust since then.
