### ISSUE TITLE
Deprecate Toolshed related API endpoints in 19.09

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#8733]
The following Toolshed related Galaxy API endpoints are considered deprecated and staged for removal in the next release

* We intend to deprecate the following endpoints in `api/toolshed.py`:
    * category
    * repository
    * search
    * show
    * status
    * tool_json
&nbsp;
* We intend to deprecate the following endpoints in `api/toolshed_repositories.py`:
    * check_for_updates
    * exported_workflows
    * get_latest_installable_revision
    * import_workflow
    * import_workflows
    * install
    * repair_repository_revision
    * shed_category
    * shed_repository
    * shed_search
    * status

The <b>remaining</b> API endpoints are:

* Remaining endpoints in `api/toolshed.py`:
    * index
    * request 
<br/>

* Remaining endpoints in `api/toolshed_repositories.py`:
    * index
    * show
    * install_repository_revision
    * install_repository_revisions
    * uninstall_repository
    * reset_metadata_on_installed_repositories

Please feel free to add more endpoints to this list.

xref: #8734

Bioblend test cases related to repository operations in Galaxy:
https://github.com/galaxyproject/bioblend/blob/master/bioblend/galaxy/toolshed/__init__.py

**Comment by martenson** [comment]
I think the bioblend adjustments (if any needed) need to be part of the same (Galaxy) release as the API removal.

**Comment by nsoranzo** [comment]
By looking at the changes, I think BioBlend doesn't use any of the removed API endpoints. We lack tests for these functionalities in BioBlend unfortunately.

**Comment by mvdbeek** [comment]
> * check_for_updates

We may still need some way for an admin to see if the repos are up to date. Do you have some replacement for this in mind ?

**Comment by guerler** [comment]
Good point. I added https://github.com/galaxyproject/galaxy/pull/8860 to start off by displaying the actual toolshed status to indicate the availability of a newer repository version. Can we update the toolshed status for all repositories through a cron job or should the client trigger a request for that?

**Comment by mvdbeek** [comment]
I think clients requesting a status update would be preferable, but a cron job could work too.

**Comment by martenson** [comment]
Galaxy has no notion of a cron job afaik so I think client should trigger it. If there is no good api for doing that I volunteer to adapt old / write new. Same with 'update all' button that is a long requested feature.

**Comment by guerler** [comment]
I restored the `check_for_updates` endpoint at https://github.com/galaxyproject/galaxy/pull/8860/commits/10f7fcc96fdcd097354b900b444a5a058b9bee69 but it does timeout given a reasonable number of installed repositories.

**Comment by bgruening** [comment]
@guerler that is a long-time problem on EU as well. It would be nice to make this async.
