### ISSUE TITLE
CORS Preflight

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#8740]
OPTIONS requests are sent to cross origin domains to check the server for a CORS header.
Galaxy doesn't seem to respond to these request types, returning 404. This causes the proxy embedding the CORS header to not send the header and forward the 404 code.

**Comment by jmchilton** [comment]
I don't imagine we're going to do this until we have a structured description of the API. This will be a lot easier after #3211 - e.g. https://connexion.readthedocs.io/en/latest/cookbook.html#cors-support.

**Comment by dannon** [comment]
Sorry, I didn't know about this issue.  I actually added basic support for this in #10077 that works for my standalone-client use case and likely this one.

**Comment by dannon** [comment]
@innovate-invent Let me know if what I implemented in #10077 isn't working for you, but I'm going to call this one addressed.
