### ISSUE TITLE
Jobs with optionally written outputs fail when job destination has outputs_to_working_directory=True

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#8743]
Have a tool that creates a bunch of output files, on an optional basis, using `from_work_dir` -- sometimes the dataset isn't created. This works fine when `outputs_to_working_directory` is False. But the job fails when `outputs_to_working_directory=True` due to:
https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/jobs/__init__.py#L1593
```
        outputs_to_working_directory = util.asbool(self.get_destination_configuration("outputs_to_working_directory", False))
        if outputs_to_working_directory and not self.__link_file_check():
            for dataset_path in self.get_output_fnames():
                try:
                    shutil.move(dataset_path.false_path, dataset_path.real_path)
                    log.debug("finish(): Moved %s to %s" % (dataset_path.false_path, dataset_path.real_path))
                except (IOError, OSError):
                    # this can happen if Galaxy is restarted during the job's
                    # finish method - the false_path file has already moved,
                    # and when the job is recovered, it won't be found.
                    if os.path.exists(dataset_path.real_path) and os.stat(dataset_path.real_path).st_size > 0:
                        log.warning("finish(): %s not found, but %s is not empty, so it will be used instead"
                                    % (dataset_path.false_path, dataset_path.real_path))
                    else:
                        # Prior to fail we need to set job.state
                        job.set_state(final_job_state)
                        return self.fail("Job %s's output dataset(s) could not be read" % job.id)
```

Error message when `outputs_to_working_directory=True` is `Job 1824's output dataset(s) could not be read`.

Job should complete as green, just the same as when `outputs_to_working_directory=False`.

**Comment by mvdbeek** [comment]
With `on an optional basis` you mean there is a filter on these outputs ?

**Comment by blankenberg** [comment]
> With `on an optional basis` you mean there is a filter on these outputs ?

Sorry, that was totally not clear. The underlying command itself may-or-may-not create the output, depending upon e.g. contents of the dataset. But there isn't a good way for a Galaxy tool to figure out if it will be created or not - so no filter in Galaxy. So if the tool doesn't create the file, Galaxy was failing the jobs.

**Comment by bernt-matthias** [comment]
Would you consider it a fix if the tool would `touch '$outfile'` at some point? Should work at least for simple textual output files.

**Comment by mvdbeek** [comment]
Seems we fixed this somewhere along the way (https://github.com/galaxyproject/galaxy/pull/11073 passes)
