### ISSUE TITLE
Tool panel cannot be hidden?

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8761]
Teaching a training today we noticed that the tool panel seems to be lacking controls for resizing or hiding?

We often hid this to show e.g. fastqc reports. We either would hide both panels, or just the tool panel. Hiding the history panel alone was uninteresting, as then we lost the context of "which report we're looking at" that was being communicated to the students. Hiding the tool panel was appealing because it was a lot of visual noise unrelated to what we wanted to communicate?

Was this done intentionally? Is there some reason we should not be able to hide that?

**Comment by dannon** [comment]
I don't think this was intentional.

**Comment by hexylena** [comment]
Oh yay :) I was worried for a minute

Op ma 7 okt. 2019 13:38 schreef Dannon <notifications@github.com>:

**Comment by martenson** [comment]
This seems firefox-specific. The controls work fine for me (chrome) on Main, Test, and dev. cc @inkuzmin 

edit: actually firefox on dev works fine too, missing on Main and Test

**Comment by nsoranzo** [comment]
> This seems firefox-specific. The controls work fine for me (chrome) on Main, Test, and dev. cc @inkuzmin
> 
> edit: actually firefox on dev works fine too, missing on Main and Test

On Ubuntu 18.04:
- Chrome 77.0.3865.90: both usegalaxy.eu and dev work
- Firefox 69.0.1: both usegalaxy.eu and dev do NOT work.

**Comment by hexylena** [comment]
Thanks so much y'all!

**Comment by inkuzmin** [comment]
Thank you for the quick fix!
