### ISSUE TITLE
S3.py delete function OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by sanman-99** [galaxyproject/galaxy#8770]
Galaxy Version: 19.05
OS version: Centos 7

We are running into an issue where the delete function in s3.py is failing, throwing an OSError.  In the example below the file does actually exist so we aren't sure why it is throwing this error.  This is happening almost constantly and is definitely causing issues.  If it would be helpful to attached the entire log let me know.

`Traceback (most recent call last):
  File "lib/galaxy/objectstore/s3.py", line 621, in delete
    os.unlink(self._get_cache_path(rel_path))
OSError: [Errno 2] No such file or directory: '/data/object_store_cache/000/456/dataset_456895.dat'

[root@ip-172-32-8-191 jsanders]# ls -al /data/object_store_cache/000/456/dataset_456895.dat
-rw-rw-r-- 1 galaxy galaxy 527509268 Aug  5 16:08 /data/object_store_cache/000/456/dataset_456895.dat

[jsanders@ip-172-32-8-191 ~]$ aws s3 ls s3://cfsan-galaxy-store-prd/000/456/dataset_456895.dat
2019-08-05 16:08:05  527509268 dataset_456895.dat
[jsanders@ip-172-32-8-191 ~]$`

**Comment by osallou** [comment]
could be  a *delay* on your shared filesystem?
I already experimented on some shared filesystems issues (not galaxy related) where file is created on a node, but not seem immediatly on an other node, causing issues when process on an other node try to access it.

For debugging purpose, you may modify s3.py to add a delay before the unlink (a sleep of several seconds) and see if it fixes your issue.

**Comment by jmchilton** [comment]
Sorry for the issue. Debug is a good idea. Hopefully you figured this out, let us know if not.
