### ISSUE TITLE
Data libraries list is not scrollable when overflowing the screen

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#8781]
Due to new CSS it seems that if the data lib list is longer than the page, you can't scroll within that page to reach the bottom and must search/zoom out.

**Comment by martenson** [comment]
I found the culprit I think. 
![DevTools_-_127_0_0_1_library_list](https://user-images.githubusercontent.com/1814954/66579614-1641db00-eb4b-11e9-977e-de69b4cf4c47.png)

**Comment by martenson** [comment]
Oh, and it is present on 19.09 so we need to fix for release I think.

**Comment by martenson** [comment]
is this possible? https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/style/scss/base.scss#L158 https://github.com/galaxyproject/galaxy/blob/dev/config/plugins/visualizations/hyphyvision/static/main.css#L7756

**Comment by martenson** [comment]
This is the fix, but I don't know what I am breaking.

```diff
diff --git a/client/galaxy/style/scss/base.scss b/client/galaxy/style/scss/base.scss
index e605f95e06..529bbfb3fb 100644
--- a/client/galaxy/style/scss/base.scss
+++ b/client/galaxy/style/scss/base.scss
@@ -134,7 +134,7 @@ body {
 #right {
     @extend .position-absolute;
     @extend .h-100;
-    @extend .overflow-hidden;
+    // @extend .overflow-hidden;
 }
 #left {
     @extend .unified-panel;
@@ -154,7 +154,7 @@ body {
     }
 }
 #center {
-    @extend .overflow-hidden;
+    // @extend .overflow-hidden;
     left: $panel-width;
     right: $panel-width;
     .center-container {
```
