### ISSUE TITLE
Data lib upload by url => 'NoneType' object has no attribute 'writable_files'

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#8820]
Hi,
I was trying to upload all GTN libraries into our (19.05) instance with https://github.com/usegalaxy-eu/shared-data (with up-to-date ephemeris 0.10.4), but got this error in the logs:

```
Traceback (most recent call last):
  File "lib/galaxy/web/framework/decorators.py", line 282, in decorator
    rval = func(self, trans, *args, **kwargs)
  File "lib/galaxy/webapps/galaxy/api/library_contents.py", line 250, in create
    status, output = self._upload_library_dataset(trans, library_id, real_folder_id, **payload)
  File "lib/galaxy/webapps/galaxy/api/library_contents.py", line 337, in _upload_library_dataset
    **kwd)
  File "lib/galaxy/actions/library.py", line 108, in _upload_dataset
    uploaded_datasets = upload_common.get_uploaded_datasets(trans, cntrller, tool_params, dataset_upload_inputs, library_bunch=library_bunch)
  File "lib/galaxy/tools/actions/upload_common.py", line 289, in get_uploaded_datasets
    uploaded_datasets.extend(dataset_upload_input.get_uploaded_datasets(trans, params))
  File "lib/galaxy/tools/parameters/grouping.py", line 548, in get_uploaded_datasets
    writable_files = d_type.writable_files
AttributeError: 'NoneType' object has no attribute 'writable_files'
```

The datasets are created in the libraries, but they are empty.

Looking at https://build.galaxyproject.eu/job/usegalaxy-eu/job/shared-data/lastBuild/console, there were also 500 errors in the last upload to usegalaxy.eu, but tracebacks are not visible.

**Comment by mvdbeek** [comment]
hmm, do you know which file or file type caused this error ? I can only force this error if I specify a non-existing file_type on upload.

**Comment by abretaud** [comment]
> The datasets are created in the libraries, but they are empty.

I was wrong:
- for datasets that don't throw an error, I was just too impatient, they ended up being uploaded correctly
- the ones that throw the exception are just not in the library (the whole directory is absent = the whole tutorial data-library.yaml file in GTN)

The list of files throwing an error from GTN:
https://zenodo.org/api/files/67d95c38-5a06-4184-b3a0-a6d3c9f25268/wt_H3K4me3_read1.fastq.gz
https://zenodo.org/api/files/67d95c38-5a06-4184-b3a0-a6d3c9f25268/wt_H3K4me3_read2.fastq.gz
https://zenodo.org/api/files/853abf60-5799-4ab5-bed6-f9d6acde9bda/ltpmsi-chilli.ibd
https://zenodo.org/api/files/463f6b73-0c42-4be4-8b52-181a8e093abd/mouse_kidney_cut.ibd
https://zenodo.org/api/files/bbfa3626-aa14-479b-bd62-234cc63520f3/qExactive01819.raw
https://zenodo.org/api/files/bbfa3626-aa14-479b-bd62-234cc63520f3/qExactive01819.raw

The 2 first ones are easy to fix, the file type was `gz` instead of `fastsanger.gz` (changed in https://github.com/galaxyproject/training-material/pull/1636)
The other types are `ibd` and `raw`

**Comment by abretaud** [comment]
And ibd and raw are not known by galaxy (not in datatypes_conf.xml, not in admin)

**Comment by mvdbeek** [comment]
ok, that makes sense. I'm now debating whether we should return with an explicit error (rather than the cryptic exception raised in the legacy library upload) or silently change the datatype to `data`, which is what the newer `fetch_data` endpoint does.

**Comment by martenson** [comment]
@mvdbeek I vote for silent change. Optionally adding a flag 'strict' to disable it?

**Comment by mvdbeek** [comment]
Hmm, @jmchilton thinks explicit error is better here. I also tend to think that'd be better, especially since this bug report came in preparation of a training. Knowing that a library upload failed because of a wrong or missing datatype might save quite some headache during the training.

**Comment by abretaud** [comment]
Both options are ok for me, I guess we could fix the remaining ones in GTN

**Comment by bgruening** [comment]
ibd is part of a composite filetype called `imzml`. I think @jmchilton was working on composite uploads at some point. Don't know if this was finished :(

ping @foellmelanie for the `raw` files.

**Comment by martenson** [comment]
Galaxy will now throw proper error. If there is another problem with composite datatypes please open a new issue.
