### ISSUE TITLE
Run.sh aborting on initiation

### ISSUE THREAD

**Issue by guswnddiq** [galaxyproject/galaxy#8822]
Mac OS X version: 10.15
Python version: 2.7.16

Error screenshot:
<img width="1439" alt="Screen shot 2" src="https://user-images.githubusercontent.com/56412267/67061990-f8b6d780-f12f-11e9-89e7-e0dd1de629db.png">

run.sh aborts on "Activating virtualenv at .venv" step. (Two lines below Done in 96.27s)
run.sh: line 54: 2659 Abort Trap: 6    python ./scropts/manage_tool_dependencies.py init_if_needed.

Installation continues but finishes with bind(): Address already in use.

Re-running run.sh aborts the script on "Activating virtualenv at .venv" step, with
./scripts/common_startup.sh: line 187: 4099 Abort trap: 6        pip install 'pip>=8.1'

Any help on how to proceed with installation is appreciated. Thank you.

**Comment by nsoranzo** [comment]
For the "Address already in use" error, you need to kill whatever process is listening on port 8080.

@VJalili reported the "Abort trap: 6 pip install 'pip>=8.1'" error on Gitter few days ago, not sure if/how he solved it.

**Comment by VJalili** [comment]
not solved, still having that issue.

**Comment by VJalili** [comment]
I suspect if @guswnddiq kills the process, then the first, and the blocking error they will see at next Galaxy start up is `Abort trap: 6 pip install 'pip>=8.1`. At least that is what happens on my end.

**Comment by martenson** [comment]
What is the source of the python used?

**Comment by VJalili** [comment]
when `.venv` activated, it is from source, when not, from system.

**Comment by martenson** [comment]
that means you have probably created the venv with system python, can you try using a different one?

**Comment by VJalili** [comment]
galaxy creates this `.venv`.

**Comment by martenson** [comment]
using whatever python is on the path, which in your case seems to be the system one

**Comment by jdavcs** [comment]
@guswnddiq : just do `ps aux | grep uwsgi`, then `kill -9 [whatever is the pid]` That should, hopefully, take care of that error. If you see the abort trap error when you rerun it after this, that's a different issue entirely.

**Comment by guswnddiq** [comment]
Hey all, first I appreciate all the responses. 

And as @VJalili said, re-running run.sh after  "ps aux | grep uwsgi, then kill -9 [whatever is the pid]" aborts the script at  "Activating virtualenv at .venv" step, with abort trap he mentioned. 

@martenson do you mind elaborating on "using different python"? Would I need to remove system python before installing another one? or else how would i have run.sh script to recognize another python other than system one?

 Thanks in advance

**Comment by jdavcs** [comment]
OK, so it is this error after all. I think here's what you can try: create a virtual env (specifying the python to use for it, so virtualenv `--python=[other-python]`), then activate it, and then run galaxy with the `--skip-venv` option. HOWEVER, I'm not sure this is the way to do it, and I may be completely wrong, so I'd wait for what the others have to say. But, in any case, do not remove your system python.

**Comment by VJalili** [comment]
Please be specific, where is the `other-python`? do you mean we should have multiple python 2 installations? I have python 2 and 3, and those are the only two pythons I have, and each virtual environment inherits from either of these. 

Regardless, I am definitely not in favor of "workarounds", rather I am interested in "solutions" only.

**Comment by jdavcs** [comment]
Yes, you can have multiple python installations, including, I believe, multiple python 2s. '[other-python]' should point to the location of the python interpreter you want to use (which depends on where you installed it; for example, I have python 3.4/5/6/7 in `usr/local/bin/python.3.x`).

**Comment by guswnddiq** [comment]
Hey all, again, I appreciate for your time and advises. 

Fortunately, the issue just has been solved for me:

I did factory reset on my Macbook Pro and cloned the Galaxy Project "without updating Mohave to the Catalina OS. I am pretty sure it would the solution because I also have tried to do factory reset and Catalina OS update prior to cloning Galaxy.   

I hope it helps!

Thanks.

**Comment by mvdbeek** [comment]
Oh, this has been fixed in https://github.com/galaxyproject/galaxy/pull/8843 / https://github.com/galaxyproject/galaxy/pull/8845, I don't think there's a need to downgrade from Catalina.

**Comment by dannon** [comment]
Oof, sorry for the slow closing of this issue and the extra resetting time you put in.  @mvdbeek is correct -- if you pull the latest code it should work fine in 19.09 and current dev branches.
