### ISSUE TITLE
Mysql migration

### ISSUE THREAD

**Issue by DanBerrios** [galaxyproject/galaxy#8825]
We, (like others who have reported issues with this) are using mysql and having a migration issue...we cannot migrate up from 135->136 due to mysql-specific constraints on length of identifiers created during the migration. It looks like at one point you were changing the model to fix this issue, but then abandoned those changes in the release branch (?)   Is there a work around for this? We are trying to get our 17.01 instance up to 19.....   It looks like support for migration of mysql users was abandoned...is that right?  If so, is there a work-around for our upgrade problems?

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/8473 should have fixed the migrations, this will be part of the 19.09 release, which shouldn't be too far out.
