### ISSUE TITLE
Request: Change default behavior of editing a textarea to store on blur.

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#883]
it has bitten me a few times to type a chunk of text in the workflow annotation and then to unselect it...only enter stores the text
ping @erasche

**Comment by hexylena** [comment]
:+1: 

(wish I could ping/assign to a "UI/UX" sub team).

**Comment by dannon** [comment]
@erasche Like that?

**Comment by hexylena** [comment]
... I ... haven't had my coffee yet. :| Thanks @dannon

**Comment by carlfeberhard** [comment]
I've seen both styles in the wild. It may be that it's working well for the silent majority.

The main reason I've argued against this, tho, is the reversibility angle. I'd rather have a single, more purposeful action (pressing enter) be the commit-to-change than the more general blur (which can happen many ways). The edit is destructive and you'll lose what was there before (non-reversible) - which more often is less on your mind than what you're trying to enter.

**Comment by martenson** [comment]
I am with Carl here. Unless we can provide a clear 'cancel' element making everything save on blur feels less usable as you are improving one usecase (clean update) but neglecting - and in this case even removing - other (cancelation of edit).
