### ISSUE TITLE
'module' object has no attribute '_magic_number'

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#8831]
yields Internal Server Error
https://usegalaxy.org/histories/list_published

```
AttributeError: 'module' object has no attribute '_magic_number'
mako.template in _compile_from_file
```

https://sentry.galaxyproject.org/sentry/main/issues/352282/

**Comment by martenson** [comment]
~~oh this is one of the magic number things, anon browser displays it fine~~

scratch that, this is not just me, Sentry says 82 users and started 2 days ago

and it only happens on web-05

**Comment by mvdbeek** [comment]
did you try removing database/compiled_templates and restarting the processes ?

**Comment by martenson** [comment]
That's not that easy to do on Main. I can give it a shot tomorrow.

**Comment by martenson** [comment]
seems that was it, thanks @mvdbeek
