### ISSUE TITLE
LDAP auth failure should not raise a warning

### ISSUE THREAD

**Issue by osallou** [galaxyproject/galaxy#8833]
When auth with ldap fails, it should not raise a warning but only an info or debug message.
Warning indeed polutes logs and sentry with lots of *errors* for basic connection errors.

A warning could be raised after 3 failures for exemple, but for a simple login failure, it is a bit *too much*.

https://github.com/galaxyproject/galaxy/blob/d3f8f216121f490305104f01cf0ab6ad03485b27/lib/galaxy/auth/providers/ldap_ad.py#L247

Would be nice to lower this warn level.

**Comment by nsoranzo** [comment]
We probably want different log levels depending on the exception, I will take a look.

**Comment by osallou** [comment]
here this is only a bind error (login/password failed), so not big deal from operational point of view

**Comment by nsoranzo** [comment]
@osallou I think this will be fixed by #8907.
