### ISSUE TITLE
Option to compare test output size to a value rather than a file

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#8838]
If I want to check the file size of an output when writing a test for a tool, I have to use `compare="sim_size"`. When a test output is large (let's say 1MB) it seems a bit ridiculous to upload a file just to do this comparison. It would be nice to also have an option like `check_size="1000000"`.

Is there a good reason not to implement such a feature? If not, I'd like to give it a try.

**Comment by simonbray** [comment]
Or maybe something like this already exists, but I couldn't find anything in the docs. :)

**Comment by martenson** [comment]
@simonbray I don't think it exists and it sounds like a good idea.
