### ISSUE TITLE
The "i" info form is not reporting dataset numbers in the inheritance chain

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#887]
This information is located at the very bottom of the form. I believe that this just appeared in the last few days. 

Note that the inherited dataset is missing a "dataset number" in this screenshot taken 2015-10-09 from http://usegalaxy.org
![screenshot 2015-10-09 Main](http://i.imgur.com/mdq1HBH.png)

**Comment by pvanheus** [comment]
Is this related to https://trello.com/c/yOdMJbpY/2671-inheritance-chain-displays-only-the-current-node ? For those who want to look at this, the inheritance chain is built when a HDA is retrieved from the DB, see https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/controllers/dataset.py#L992

**Comment by jennaj** [comment]
@carlfeberhard This is related to the other change you made, think we can close it out.

dup:
https://github.com/galaxyproject/galaxy/pull/2411

unique:
https://github.com/galaxyproject/galaxy/pull/2415
