### ISSUE TITLE
Implement internal cron service 

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#8881]
Could use https://uwsgi-docs.readthedocs.io/en/latest/Cron.html

First application would be the whoosh index building for toolshed search, but I can think of more.

This would lower the admin requirements for deploying such services, that in turn can speed up certain things.

**Comment by dannon** [comment]
To follow up on this with the discussion from Gitter --  we'd planned on implementing Celery a few years ago for task management, and it supports periodic tasks (https://docs.celeryproject.org/en/latest/userguide/periodic-tasks.html) that'd be ideal here.  Rebuilding whoosh indexes periodically is a great prototype project for it, and @mvdbeek is going to give it a fresh shot.

**Comment by martenson** [comment]
another application xref https://github.com/galaxyproject/galaxy/issues/6254

**Comment by martenson** [comment]
Note: With the above PR we are now using the built in uwsgi cron-like service for the shed index creation. Proper celery queue would still be useful for this though.

**Comment by martenson** [comment]
another application  https://github.com/galaxyproject/galaxy/issues/8733#issuecomment-545571686

**Comment by innovate-invent** [comment]
Could leverage #11721

**Comment by mvdbeek** [comment]
Closing this in favor of https://github.com/galaxyproject/galaxy/issues/11721. We do have a cron-style celery task already.
