### ISSUE TITLE
Deprecate GenomeSpace tools

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#8889]
From http://www.genomespace.org/news/the-genomespace-project-is-ending : "The GenomeSpace project ends on November 15, 2019 due to expiration of its NHGRI funding and we will be shutting down the GenomeSpace servers on that date.
...
If you wish to retain copies of data you have in your GenomeSpace account, you should transfer them to your own storage from GenomeSpace before the termination date. After that time they will be deleted from the GenomeSpace servers as part of the shutdown process."

**Comment by bernt-matthias** [comment]
Is there only a single GS? Or are there multiple installations, eg at other institutions?

**Comment by mvdbeek** [comment]
Possibly, but the code has been removed from bitbucket as well, so I doubt even those private instances will operate for much longer. I don't think this is a release blocker, can I move it to 20.01 @nsoranzo ?

**Comment by nsoranzo** [comment]
I think it would be better to have a deprecation added to the release notes for 19.09, so we can remove the tools in 20.01.
