### ISSUE TITLE
get_tool_repository_from_xml_item fails if installed_changeset_revision is not in the repo path

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#8892]
The shed_tool_conf.xml file on main.galaxyproject.org has some entries where tools are loaded from a path that doesn't contain the `installed_changeset_revision` and are loaded instead from a path that contains the (apparent) changeset revision. For instance this one here:
```xml
        <tool file="toolshed.g2.bx.psu.edu/repos/gregory-minevich/ems_variant_density_mapping/58a3878549ef/ems_variant_density_mapping/EMS_VariantDensityMapping.xml" guid="toolshed.g2.bx.psu.edu/repos/gregory-minevich/ems_variant_density_mapping/ems_variant_density_mapping/1.0.0">
            <tool_shed>toolshed.g2.bx.psu.edu</tool_shed>
            <repository_name>ems_variant_density_mapping</repository_name>
            <repository_owner>gregory-minevich</repository_owner>
            <installed_changeset_revision>5cc9b35b5a52</installed_changeset_revision>
            <id>toolshed.g2.bx.psu.edu/repos/gregory-minevich/ems_variant_density_mapping/ems_variant_density_mapping/1.0.0</id>
            <version>1.0.0</version>
        </tool>
```

 IIRC this shouldn't happen, and previously these tools would be loaded with ToolConfRepository items, but that  broke in https://github.com/galaxyproject/galaxy/commit/9e288071c5c3af478c176d23f8cf3adc3375370b under the assumption that tools are always loaded from a path that contains the installed_changeset_revision. Sooo ... is main's shed_tool_conf.xml not intact and should it be fixed ? Am I making wrong assumptions here ? Should we guess the changeset_revision from the tool path and fetch repositories that way?

**Comment by mvdbeek** [comment]
In the install database this repo is listed with `58a3878549ef` as installed_changeset_revision (which seems correct based on the tool path but not the installed_changeset_revision tag). The changeset_revision for this repo in the database is `5cc9b35b5a52`, which is the `installed_changeset_revision` in the xml tag.

So it looks like the shed_tool_conf.xml file has some wrong items, and we shouldn't account for that in Galaxy, but maybe I'm wrong ?

**Comment by natefoo** [comment]
Do you happen to have a list of these tools?

**Comment by mvdbeek** [comment]
https://gist.github.com/mvdbeek/e780591aabe3db21e5d5563deb6cb54a
that's just parsed from the startup logs, if that'd be of help I can write a script to correct this as well.

**Comment by natefoo** [comment]
Even better, the actual installed changeset appears to be:

```console
(hg)ndc@galaxy-web-05% hg summary
parent: 14:ddfef7773c2d tip
 Uploaded
branch: default
commit: (clean)
update: (current)
```

**Comment by mvdbeek** [comment]
That's the installed changeset, a.k.a `changeset_revision`. The` installed_changeset_revision` is where the mercurial repo has been cloned at. In this case it is at  `./toolshed.g2.bx.psu.edu/repos/gregory-minevich/ems_variant_density_mapping/58a3878549ef/ems_variant_density_mapping` which is in agreement with the install database. So I'd say let's use the path as the source of truth for the `installed_changeset_revision`. Doing that loads all tools from main's shed_tool_conf.xml

**Comment by mvdbeek** [comment]
Fixed by https://github.com/galaxyproject/galaxy/pull/8985
