### ISSUE TITLE
creating a collection:list from library uses two histories

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#8898]
This is on Main [19.09] - I am creating a list from library datasets and selected a target history. The List is made in the correct history but the underlying hdas are created in the current history (and also are not hidden despite the checkbox was checked).

![Galaxy___Histories](https://user-images.githubusercontent.com/1814954/67724342-22d08b00-f9b5-11e9-9e6a-a8dcf64044fe.png)

**Comment by mvdbeek** [comment]
Pretty sure Assunta fixed that some time ago.
