### ISSUE TITLE
Composite dataset batch upload

### ISSUE THREAD

**Issue by abretaud** [galaxyproject/galaxy#8909]
It doesn't seem to be possible to upload composite datasets using the batch upload API.
There is a case in GTN where this would be useful: [upload of ibd+imzml file](https://github.com/galaxyproject/training-material/blob/1bcf1e74d7b36b5f24ccfcdba23c406c691e36d9/topics/metabolomics/tutorials/msi-analyte-distribution/data-library.yaml#L16)
Discussed in https://github.com/galaxyproject/training-material/pull/1636

**Comment by jmchilton** [comment]
This is possible now with https://github.com/galaxyproject/galaxy/pull/9860.
