### ISSUE TITLE
Working directory depends on first action in tool_dependencies.xml

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#896]
See https://github.com/galaxyproject/planemo/issues/320 which touched on an inconsistency with the working directory used when executing a `tool_dependencies.xml` file.

https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/install_manager.py currently has:

``` python
class InstallToolDependencyManager( object ):

    def __init__( self, app ):
        self.app = app
        self.install_model = self.app.install_model
        self.INSTALL_ACTIONS = [ 'download_binary', 'download_by_url', 'download_file',
                                 'setup_perl_environment', 'setup_python_environment',
                                 'setup_r_environment', 'setup_ruby_environment', 'shell_command' ]
        ...

    def install_and_build_package( self, install_environment, tool_dependency, actions_dict ):
        ...
                    if action_type in self.INSTALL_ACTIONS:
                        # Some of the parameters passed here are needed only by a subset of the step handler classes,
                        # but to allow for a standard method signature we'll pass them along.  We don't check the
                        # tool_dependency status in this stage because it should not have been changed based on a
                        # download.
                        tool_dependency, filtered_actions, dir = \
                            step_manager.execute_step( tool_dependency=tool_dependency,
                                                       package_name=package_name,
                                                       actions=actions,
                                                       action_type=action_type,
                                                       action_dict=action_dict,
                                                       filtered_actions=filtered_actions,
                                                       env_file_builder=env_file_builder,
                                                       install_environment=install_environment,
                                                       work_dir=work_dir,
                                                       current_dir=None,
                                                       initial_download=True )
                    else:
                        # We're handling a complex repository dependency where we only have a set_environment tag set.
                        # <action type="set_environment">
                        #    <environment_variable name="PATH" action="prepend_to">$INSTALL_DIR/bin</environment_variable>
                        # </action>
                        filtered_actions = [ a for a in actions ]
                        dir = install_dir
        ...
```

I believe this means if the first action_type is white-listed in `INSTALL_ACTIONS` the working directory is set to a temporary folder (most cases), but otherwise `$INSTALL_DIR` is used (corner case).

Planemo PR https://github.com/galaxyproject/planemo/pull/321 to replicate this special case within `planemo dependency_script`.

In testing this planemo PR, only a handful of packages appear to trigger this corner case. A check of the full Test and main Tool Shed might be informative.

Can we get rid of this special list `INSTALL_ACTIONS` and always use the temporary working folder?

**Comment by bgruening** [comment]
@davebx @gregvonkuster how do you feel about this?

**Comment by gregvonkuster** [comment]
@bgruening @davebx I think that in general it is more safe / secure to use the temporary working directory as the initial location for performing installation tasks.  The underlying install framework has been implemented in such a way that recipe actions cannot be performed outside of the temporary directory hierarchy.  The use of the $INSTALL_DIR location should be restricted to either moving files into it using the "move_file" or "move_directory_of_files" (or similar) actions or as a compile flag (e.g., --prefix=$INSTALL_DIR).  I think that $INSTALL_DIR should not be allowed to replace the intended use of the temporary working directory.  Recipes that do this should be fixed if possible.  Exceptions, if any are necessary, should be fully justified.

**Comment by peterjc** [comment]
We should add a warning about this path oddity to the `else` branch saying in future rather than `$INSTALL_DIR` the installation will use a temporary working directory.

I can revise the Planemo PR  https://github.com/galaxyproject/planemo/pull/321 to issue an explicit warning from `planemo dependency_script` here, and use that to check for the remaining offenders in thttps://github.com/galaxyproject/tools-iuc and https://github.com/galaxyproject/tools-devteam which we can revise.

Separately it would be great if someone at Galaxy could scan all the TTS and main TS recipes for other potential problems.

One that is done, we should be safe to change the corner case `else` branch which currently uses `$INSTALL_DIR` starts to use the temp working directory regardless of the first action type.

**Comment by hexylena** [comment]
`tool_dependencies.xml` is no longer used, so think this is ok to close? Conda seems to handle these things better :)
