### ISSUE TITLE
Can not select all needed files from library if not on 1 page

### ISSUE THREAD

**Issue by erxleben** [galaxyproject/galaxy#8965]
When files in the data library are on different pages because there a too many, you lose the check boxed ones when going to the second page. This can be avoided by increasing the number of files to be shown at the bottom but it may be not obvious to all users. If they are not aware they may forget some files because they are not imported.

Could that be changes to keep all selected files or by default to show all files in a folder (and not necessary to go to page 2,...)

Thanks a lot!

**Comment by martenson** [comment]
Selecting items from multiple pages is a classic UX pickle that has no really good solution. Most modern interfaces are trying to avoid this pitfall completely by switching to infinite loading presentation. That has its downsides too (e.g. cannot link to a page).

Would providing a "select all" button cover your use cases?

**Comment by martenson** [comment]
This has been solved, when importing to history there is "select all" option.
