### ISSUE TITLE
Add the PDF datatypes to the upload tool

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#897]
Advice from @guerler for update:

pdf extension in datatypes_conf.xml needs to contain the display_in_upload="True" attribute

Trello this was promoted from: https://trello.com/c/oEP5D6s1

**Comment by nsoranzo** [comment]
Fixed in #901.

**Comment by jennaj** [comment]
Re-tested at usegalaxy.org ... pdf is not listed in the Upload tool drop-down menu. Loading with "auto-detect" will assign the correct metadata.

Sam @guerler - is this linked to a release or does main just need an update?

I suggest that we do not close out tickets that were detected on main until re-tested on main as functional. How best to go about doing that? It is becoming very difficult to track the flow of corrections: issue reported -> fix -> implimented on main

Updated: added to this github wiki to track - is temporary, manual, and tedious. Would be better to have integration/user testing as part of the larger process. https://github.com/jennaj/support-known-issues/wiki

**Comment by guerler** [comment]
This probably requires updating mains datatypes_conf.xml. Maybe @natefoo can help.

**Comment by natefoo** [comment]
It's been updated on Test. There were a lot of changes, can someone check it out? If things look ok I'll update it on Main.

**Comment by martenson** [comment]
`pdf` is visible in upload on Test

**Comment by jennaj** [comment]
When this goes to main, ping here, thanks!

**Comment by martenson** [comment]
@jennaj you can apprx. track what is on Main when you click in the footer github link at usegalaxy.org (you can immediately see the age of the latest revision and compare it with age of this being merged)

I think it is safe to assume that nobody will remember to get back and make you remember to retest. :)

**Comment by nsoranzo** [comment]
@martenson I guess this will require a manual modification/merge of `config/datatypes_conf.xml` on Main by @natefoo or you.

**Comment by natefoo** [comment]
Done.

**Comment by jennaj** [comment]
PDF is now a upload dropdown datatype on main, thank you.

To be clear, the suggestion was to update the SDLC to include final QA in the issue tickets themselves. Specific and simple. Matrix mode - anyone can check and close out once done.
