### ISSUE TITLE
Flatten collection tool couldn't recognize nested list generated by discover_datasets

### ISSUE THREAD

**Issue by qiagu** [galaxyproject/galaxy#8975]
The issue occurs in v19.09
The flatten collection tool takes list, but not a list:list generated by discover_datasets.
Not sure it's a common issue or not.

**Comment by jmchilton** [comment]
<img width="1401" alt="Screen Shot 2020-10-20 at 8 16 45 PM" src="https://user-images.githubusercontent.com/216771/96657858-3cc75400-1311-11eb-9172-492406d1fbef.png">

This works for me and we have tests. I think there was something wrong with your discover dataset generated collection - I'm going to try to implement a collection UI form and APIs to help with this (https://github.com/galaxyproject/galaxy/issues/9183#issuecomment-713197086).
