### ISSUE TITLE
Upload tool: individual file metadata changes should not change others in the queued list

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#899]
Behavior: changing the datatype for any file in the queue will assign that datatype to any still set as "unspecified"

Usage issue: UNExpectedly can change files "above" in the load queue that have already been configured.

Better: Use the global attribute assignments at the bottom of the form for the batch assignments. Never use the assignment of an individual dataset to modify the settings for another individual dataset.

Moved from Trello https://trello.com/c/ALSF2wtS

**Comment by nsoranzo** [comment]
+1, this was unexpected also for me.

**Comment by jennaj** [comment]
Needs a re-test .. I haven't seen any tickets about changes. @guerler does this need another ticket or is it in progress?

**Comment by jennaj** [comment]
Should we wait to close this out until it has been integration tested (Test, then Main, plus default locals and cloudman)?
