### ISSUE TITLE
Error: Unable to access jarfile /trimmomatic.jar

### ISSUE THREAD

**Issue by guswnddiq** [galaxyproject/galaxy#8992]
Hi, 

I have tried to trim my NGS sequencing data with Trimmomatic in Galaxy project on my Mac, but when I try to run it, the following error message keeps coming up:

"Error: Unable to access jarfile /trimmomatic.jar
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
Trimmomatic did not finish successfully"

Any advise on this matter will be appreciated. 

Thank you very much for your time in advance.

**Comment by nsoranzo** [comment]
Hi, thanks for reporting the issue. This is not a bug in Galaxy, but in the Trimmomaic wrapper. Can you please open an issue on https://github.com/fls-bioinformatics-core/galaxy-tools instead?

**Comment by mvdbeek** [comment]
Actually this has been fixed in newer versions of trimmomatic, you just need to update the tool.

**Comment by nsoranzo** [comment]
@mvdbeek The reported error mentions illegal option -f , which is what the latest version uses after your patch.
