### ISSUE TITLE
set a walltime limit for a specific destination?

### ISSUE THREAD

**Issue by fmareuil** [galaxyproject/galaxy#8996]
We would like to know if it's possible to set a walltime limit on a specific destination like the destination_user_concurrent_jobs limit and destination_total_concurrent_job limit?

Best regards,
Thank you.

**Comment by nsoranzo** [comment]
If you are running the job on a cluster infrastructure, that is normally set at the cluster scheduler level (e.g. Slurm partition limits).
Then you would map a Galaxy destination to that partition with something like:

```xml
        <destination id="hpc_long" runner="slurm">
            <param id="nativeSpecification">-p long_time_limit_partition</param>
        </destination>
```

**Comment by mvdbeek** [comment]
Or if you want to have control over this in your galaxy destination you can also set this, assuming your scheduler supports it as in
https://github.com/galaxyproject/galaxy/blob/9662164ad68b39adf5a5606a7aa8e388f6a79f1e/lib/galaxy/config/sample/job_conf.xml.sample_advanced#L897

**Comment by fmareuil** [comment]
Hello @nsoranzo and @mvdbeek, Thank you for your answer indeed the solution of @mvdbeek  works very well.
