### ISSUE TITLE
Feature Request: More informative workflow submission page

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#900]
Instead of the current backgrounded job queueing process and possible display of "You've launched these jobs in this history" green page, I'd really like to see something like a progress bar which counts up as jobs are submitted via the API.

I had one user launch a workflow on ~150 datasets \* 13 workflow steps, only to see the page return an internal server error after a while of waiting. This could be much friendlier.

On revision 69ea94747883f7bf2ad0ddfae84914703f6d6297

**Comment by hexylena** [comment]
![wrkflow-mockup](https://cloud.githubusercontent.com/assets/458683/10520315/2daf0e4a-732f-11e5-8c2a-4ad7166972ad.png)

**Comment by hexylena** [comment]
Second time recently that this has happened. Mind you, every job is actually submitted and the entire workflow seems to be running, but the request took long enough to time out while Galaxy was rendering that page

![ugh](https://cloud.githubusercontent.com/assets/458683/10521202/1c45f61e-7334-11e5-8f8b-66011fe2599f.png)

**Comment by scholtalbers** [comment]
@erasche do you actually have this option set? It should remove those errors.

```
# Workflows containing more than the specified number of steps will always use
# the Galaxy's beta workflow scheduling.
force_beta_workflow_scheduled_min_steps=1
```

See also: https://botbot.me/freenode/galaxyproject/2015-04-21/?msg=37133133&page=1

**Comment by hexylena** [comment]
@scholtalbers I had it set at the default, good point. Dropped to `min=1` as well... testing now. Would be nice if calculated that number as not "number of workflow steps" and instead "number of jobs created".

**Comment by jmchilton** [comment]
@erasche For advanced cases, Galaxy no longer really has anyway of knowing the number of jobs a workflow will create until after it is done.

**Comment by hexylena** [comment]
@jmchilton yeah. Not a problem. I'll see if dropping it to 1 improves the situation and kill this bug if so.

**Comment by hexylena** [comment]
The new workflow submission is significantly better in terms of time (though a bit dull UI-wise), so closing
