### ISSUE TITLE
new_file_path get priority over  object_store in 19.09

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#9005]
It seems that the `new_file_path` from Galaxy main config gets a priority over the one in an object-store. I think this behavior has changed in 19.09

@natefoo something to watch out.

object store backend:

```
        <backend id="files9" type="disk" weight="1">
            <files_dir path="/data/dnb02/galaxy_db/files"/>
            <extra_dir type="temp" path="/data/dnb02/galaxy_db/tmp"/>
            <extra_dir type="job_work" path="/data/dnb02/galaxy_db/job_working_directory"/>
        </backend>
```

and in galaxy.ini we have:

`new_file_path = /data/7/galaxy_temp`

I do see massive traffic in `/data/7/galaxy_temp` but I beliefe there should be no traffic.

**Comment by natefoo** [comment]
@bgruening did you close this on purpose?

**Comment by bgruening** [comment]
Yes, I was not sure if I was talking bs ... I found an old commit from myself, so I think this was like it is today even in 19.05. However, not sure if this is the expected behaviour.

**Comment by jdavcs** [comment]
..And just as a sanity check, I did take a quick look to make sure I didn't break this as part of the recent config modifications. Seems like I didn't.

**Comment by natefoo** [comment]
Actually - If I recall correctly, I believe I never implemented `type="temp"`.

**Comment by bgruening** [comment]
@natefoo I don't understand? You mean https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/object_store_conf.xml.sample#L20  ? does not exist?

**Comment by natefoo** [comment]
I believe that is correct
