### ISSUE TITLE
EBI SRA has an updated website. The Get Data tool included in the release is non-functional.

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#9028]
Remove the tool from the distribution? Or is a tool update planned? 

No links on the older website are functional. ~~I'm not even able to connect to the new website at all.~~ Just tried again, is working. Maybe a server hiccup

There are no "send to Galaxy" options (yet?) but the FTP link for data can be copy/pasted into the Upload tool. Example: https://www.ebi.ac.uk/ena/browser/view/SRR925743

Test to see how the "view in the old website" links work right now. Didn't retrieve data two weeks ago. https://www.ebi.ac.uk/ena/data/view/SRR925743 > FASTQ files (Galaxy) > File 1
https://usegalaxy.org/u/jen/h/ebi-sra-test

**Help for End Users:**

The alternative tools for SRA data retrieval are:

* Download and Extract Reads in FASTA/Q format from NCBI SRA
* Faster Download and Extract Reads in FASTQ format from NCBI SRA
* Find these under the "Get Data" tool group on public servers or in the [ToolShed](https://toolshed.g2.bx.psu.edu/) for installation into your own Galaxy server.

**Comment by jennaj** [comment]
Well, the older website works now. Maybe that is enough, closing.

**Comment by hebamuh68** [comment]
There are no "send to Galaxy" options?

![Screenshot from 2022-09-18 12-52-30](https://user-images.githubusercontent.com/69214737/190898478-014f8cc3-c565-4d70-930a-a691cf596379.png)
