### ISSUE TITLE
Publish history - HistoryDatasetAssociation permission denied

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#903]
v15.07
If a history is made public and a user imports it, the user may receive this error upon inspecting a history item: `HistoryDatasetAssociation is not accessible by user`
If on the other hand, the owner shares the history with a particular user, the owner is asked if the permissions on the datasets should be changed. When then set to public, any user can use the imported history without issues.

**Comment by hexylena** [comment]
Mostly fixed with new permissions updating dialogs upon sharing
