### ISSUE TITLE
19.09 galaxy.yml tool_config_file incorrect relative path

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#9039]
I just finished installing Galaxy 19.09 and it appears that all paths in the galaxy.yml are now relative to its location. An exception is the `tool_config_file` parameter is relative to the galaxy root. This feels like a bug.

**Comment by jdavcs** [comment]
It's not a bug: quite a few paths are indeed resolved against galaxy root. If you look at the config processing code https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/__init__.py you'll find many examples of `os.path.join(self.root, ...`. Also, there'll be more info on how paths are resolved in the schema: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/config_schema.yml . Some do look like bugs (here's one example: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/webapps/galaxy/config_schema.yml#L628 - this is **not** the same config directory as `config/galaxy.yml`), but the description (`desc`) will usually provide an explanation.

Thanks for noticing/bringing this up. We're still working on improving the config, and that could've been an inconsistency or a bug.

**Comment by innovate-invent** [comment]
Would it be better that all paths were relative to a consistent location?

At least the tool_conf.xml usually accompanies the galaxy.yml

**Comment by jdavcs** [comment]
It does sound like a logical and reasonable assumption, but the config system has to handle more complexity than one would expect, and placing all such files in one location simply won't work for all scenarios under which galaxy runs. A packaged and installable galaxy is just one case when `cwd/config` wouldn't make much sense. (ping @natefoo : Nate, correct me if I'm wrong)

**Comment by jdavcs** [comment]
Closing this (I assume it's resolved, but please feel free to reopen).
