### ISSUE TITLE
data manager is not cleaning up after crash

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#904]
The bowtie data manager is crashing with the following error message if a previous run crashed for example because of to less memory. It's seems the directory is not cleaned up properly if a data manager fails.

```
Traceback (most recent call last):
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/runners/__init__.py", line 590, in finish_job
    job_state.job_wrapper.finish( stdout, stderr, exit_code )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/jobs/__init__.py", line 1316, in finish
    self.tool.exec_after_process( self.queue.app, inp_data, out_data, param_dict, job=job )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/__init__.py", line 3014, in exec_after_process
    data_manager.process_result( out_data )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/data_manager/manager.py", line 302, in process_result
    self.process_move( data_table_name, name, output_ref_values[ name ].extra_files_path, **data_table_value )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/tools/data_manager/manager.py", line 360, in process_move
    util.move_merge( source, target )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/util/__init__.py", line 1233, in move_merge
    move_merge( os.path.join( source, name ), os.path.join( target, name ) )
  File "/usr/local/galaxy/galaxy-dist/lib/galaxy/util/__init__.py", line 1235, in move_merge
    return shutil.move( source, target )
  File "/usr/local/python/2.7/lib/python2.7/shutil.py", line 299, in move
    copy2(src, real_dst)
  File "/usr/local/python/2.7/lib/python2.7/shutil.py", line 128, in copy2
    copyfile(src, dst)
  File "/usr/local/python/2.7/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
Error: `/data/3/galaxy_db/files/000/295/dataset_295631_files/danRer7.fa` and `/data/db/data_managers/danRer7/bowtie2_index/danRer7/danRer7.fa` are the same file
```

**Comment by mvdbeek** [comment]
I can conform this, and state that the hisat data manager has the same problem.
This als happens if by accident you generate the same index twice.

**Comment by jennaj** [comment]
I made a wish-list for data manager usage a short time after this was posted as an issue. The same sorts of requests come in often, still, even today at Gitter https://gitter.im/galaxyproject/Lobby?at=5acff5005d7286b43a22e6b3). 

If interested in what things I think we should consider based on my own usage and end-user/admin Q&A, please see: https://github.com/galaxyproject/galaxy/issues/1471

**Comment by blankenberg** [comment]
This should only happen if the data has been placed there manually before or if the datamanger was run successfully before.

Data will not be copied if the underlying command processes fail [i.e. is red], e.g. bowtie2 runs out of memory. If the underlying process failed, but the tool wrapper is written incorrectly and reports success [green] erroneously, then it could happen.

In other words, all datamanger file creations happen as part of a Galaxy job, after job completion, the data is only placed into it's final location if the job was reported as completing successfully (green). If the job is reported as error (red) then nothing is placed into the final location and no entries are written.

**Comment by mvdbeek** [comment]
> Data will not be copied if the underlying command processes fail

I think the `exec_after_process` hook may still run if the job runner didn't signal a job error but the exit code did or any other fail condition as determined by https://github.com/jmchilton/galaxy/blob/07569c14300a1df8654b24a673aab15226611044/lib/galaxy/jobs/__init__.py#L1575

I'll try writing a test for this.

**Comment by mvdbeek** [comment]
OK, it doesn't run if there is an error, but lots of data managers don't properly error when there is an issue, which is likely the source of issues here. I'll close this one.
