### ISSUE TITLE
Subworkflow step jobs not returned by workflow invocation API

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#9058]
`GET /api/workflows/{workflow_id}/invocations/{invocation_id}/step_jobs_summary`
`GET /api/workflows/{workflow_id}/invocations/{invocation_id}/jobs_summary `
`GET /api/workflows/{workflow_id}/invocations/{invocation_id}?step_details=true`

None of the above API endpoints return a means of determining the invocation state of subworkflows. Other than looking at the history state, is there a workaround for this in the meantime?

**Comment by mvdbeek** [comment]
We've added the subworkflow_invocation_id some time ago for the invocation details component. `/api/workflows/{workflow_id}/invocations/{invocation_id}?step_details=true` should include it.

**Comment by innovate-invent** [comment]
Does this mean that multiple requests are required to get the workflow invocation state?
There should be an option to return the subworkflow state with the workflow state.
