### ISSUE TITLE
No module named boltons.iterutils

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#9100]
Galaxy 19.09 fresh install.

I get the following exception in the tool stdout when tools run successfully or fail:

```
Traceback (most recent call last):
  File "metadata/set.py", line 1, in <module>
    from galaxy_ext.metadata.set_metadata import set_metadata; set_metadata()
  File "/srv/galaxy/lib/galaxy_ext/metadata/set_metadata.py", line 20, in <module>
    from galaxy.metadata.set_metadata import set_metadata
  File "/srv/galaxy/lib/galaxy/metadata/__init__.py", line 14, in <module>
    import galaxy.model
  File "/srv/galaxy/lib/galaxy/model/__init__.py", line 22, in <module>
    from boltons.iterutils import remap
ImportError: No module named boltons.iterutils
```

**Comment by mvdbeek** [comment]
The metadata process needs boltons, this is part of Galaxy's requirements. What you're seeing is the internal metadata fallback fixing it for you. Make sure that your virtualenv has up to date requirements.

**Comment by innovate-invent** [comment]
I am not sure I understand. This is a fresh git clone of the release_1909 branch.
The server is run via `./run.sh --daemon`
Does the venv need to be manually modified?

I can't verify the execution environment until #8808 is resolved. The galaxy_***.sh file is what activates the environment and it is being deleted.

**Comment by innovate-invent** [comment]
Looks like it was an issue with permissions on the .venv folder.
I'll close this but it would be good if some sort of debug output occurred when the worker fails to source the environment.
