### ISSUE TITLE
Utilize the GA4GH TRS Interface

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#9107]
MVP: For the AnVIL project, I told the Dockstore team I'd have a prototype of browsing querying [a TRS interface](https://github.com/ga4gh/tool-registry-service-schemas) for Galaxy workflows from inside the Galaxy UI done during Q2 of 2020. Supporting TRS will I think continue to have value as we implement CWL in Galaxy and probably will be compatible with ongoing efforts to stand up the next iteration of myexperiment.

That said - I've wanted a way to get tool-based information from the Tool Shed (current APIs are all repository-based) and we've talked for a long time about having a Galaxy workflow registry. A tool-centric API for the tool shed could enable us to build a stand-alone workflow editor and could aid in workflow validation/linting from Planemo. So I think there is a lot of value in standing up a Galaxy-flavored TRS (with Galaxy-specific extensions) inside the Tool Shed and then another new service that would monitor Github for workflows.

It'd be nice to have a little, light weight, interface and implementation on PyPI for testing against - but biocontainers-backend (https://github.com/BioContainers/biocontainers-backend) - has that permanent indexing piece down (Mongo) and a deployment strategy (Kubernetes). It is tempting to fork it and see if we can make it work for Galaxy. Another option would just be to extend it for Galaxy and let biocontainers.pro monitor and index our workflows for us.

I talked @bgruening about this plan and he has a lot of reasonable concerns. His first point was that most Galaxy workflows are made by Galaxy users inside of Galaxy and are fairly one-off and most of these users would not be interested in publishing to Github. I think this is reasonable and I agree, but there is still a need I think for a set of professionally managed, tested, versioned "best practice" starting points. He agreed.

He pointed out some existing, ongoing work in this direction aimed at Galaxy-to-Galaxy sharing/searching:
- https://github.com/scrathat/galaxy.workflow.query
- https://github.com/usegalaxy-eu/galaxy/pull/17
- https://github.com/anuprulez/galaxy_neo_tools_graph

I think we both agree that we need mechanisms to address both reviewed and managed Github-based workflows as well as user-to-user workflows published in and between Galaxies. The AnVIL use cases (no workflow sharing, promise of publication to Dockstore) and my personal research interests cause me to be focused on the former, but the latter is at least as important. Potentially implementing TRS within Galaxy as an interface for published workflows could allow bridging these use cases more easily - but I can appreciate the ease and richness of the native, existing Galaxy APIs is more appealing for Galaxy-to-Galaxy use cases.

**Comment by martenson** [comment]
> current APIs are all repository-based

fwiw there is a tool search API: https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/webapp/search/tool_search.py#L33
