### ISSUE TITLE
Simplified Workflow Landing Entry Point

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#9109]
This is the first of two pages we outlined in http://bit.ly/simplified-workflow-ui - it would be the landing for the simplified workflow-centric interface to Galaxy. The page would show the workflows available to the users and some sort of representation of recent invocations - including the ability to browser outputs, invocation reports, etc..

We were able to convince ourselves that exposing histories was unneeded - a new history for each invocation can be created automatically. Data can be uploaded as needed using extensions to the data selection dialog (see https://github.com/galaxyproject/galaxy/issues/9110) - eliminating the need to browse shared data, perform upload, etc.. The use case here is for workflow-centric usage of Galaxy so history content, ad-hoc visualizations/scratchbook, the tool panel, etc.. should be down played and not visible by default (though everything should eventually be configurable in terms of what level of interactivity is encouraged/allowed). 

This is in some ways a compliment to #9037 and in some ways a rival idea. I suspect if we can implement the ideas we had around uploading the data in a context specific way directly from the run tool form (see https://github.com/galaxyproject/galaxy/issues/9110) - the ideas would largely collapse into one.

WIP in #9030

**Comment by hexylena** [comment]
Just as a reference from what's going on in other communities, I was recently pointed to https://cloud.tower.nf/ which looks a lot like what I'd want in a simplified workflow run interface https://help.tower.nf/21.12/core-concepts/definitions/#pipelines 

1. Pick a workflow in their "launchpad"
2. it goes to a parameters form (our run interface) 
3. See [ongoing/past runs](https://help.tower.nf/21.12/monitoring/overview/#runs) (using invocation list)

And obviously without the complexity of "choose your computer environment"!
