### ISSUE TITLE
Data library API includes bad call to url with two slashes

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#911]
The route called was `https://fqdn/galaxy/api/folders//Fa411ce27cdcc0a37` from the "Data Libraries (Beta)" create folder view.

Removing the extra slash and re-sending the request corrects the problem. https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/mvc/library/library-foldertoolbar-view.js#L166 appears to be the line with the issue but I'm not confident in making client side changes.

**Comment by martenson** [comment]
this seems to not change the behaviour though, finishes with 200 and folder created
![screenshot 2015-10-13 18 00 00](https://cloud.githubusercontent.com/assets/1814954/10469568/43e4fd8e-71d4-11e5-98a2-b4f42b432108.png)

**Comment by hexylena** [comment]
Okay, for me I get a 404.

![data-lib-error](https://cloud.githubusercontent.com/assets/458683/10469606/390095ac-71cc-11e5-84bc-15c7848dc6bc.png)

but 200 OK without the extra slash

![data-lib-error1](https://cloud.githubusercontent.com/assets/458683/10469618/488381f6-71cc-11e5-937c-599119fb93a7.png)

**Comment by martenson** [comment]
nevertheless it is still wrong, I will fix it

**Comment by hexylena** [comment]
Okay, thanks! :)

**Comment by martenson** [comment]
this is fixed by #1162
