### ISSUE TITLE
Simplified Workflow Run Component

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#9111]
This is the second of two pages we outlined in http://bit.ly/simplified-workflow-ui - it would be a simplified workflow run component.

For the purposes of this issue - lets call a best practice workflow one with "no disconnected runtime inputs" - i.e. all inputs are actually annotated input modules (data_input, data_collection_input, or parameter_input modules). These have been improving rapidly and #9086 will address a number of remaining issues that might have previously forced a workflow to use runtime inputs instead of inputs (inputs will now be connectable to select parameters, input files can be optional, etc..). 

By requiring best practice workflows (we can validate this server side before rendering the form), we believe we can and should focus on providing a very simplified interface by default that just exposes workflow inputs, and not individual steps. The document above has a longer discussion of this.

If only inputs are being sent to the GUI and rendered - the workflow run should render a lot faster and the API call to run the workflow form can just send the inputs (no need to send the full tool state for every step) which should be more robust long term and is how we should encourage users to use the workflow API.

An “advanced” button to switch out of this simplified mode and to the full workflow run form with all steps could be exposed for typical Galaxy instances. Clinical applications, or any server where the maintainers decide additional workflow tweaking should be prohibited, would have the option to remove the “advanced mode” (could also be role-based).

**Comment by hexylena** [comment]
Is this complete with #9151?

**Comment by mvdbeek** [comment]
I'm gonna say yes ✅   ... I don't think we're missing anything from the description. Thanks so much @jmchilton!
