### ISSUE TITLE
Invocation Grid - Make Workflow Outputs Navigable/Downloadable

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#9113]
I'm not sure the invocation report is enough, I think it would be good if you can navigate to or download the outputs of a workflow. Maybe with some context about what the workflow output label is - Hisat on Dataset 45 is probably not as good a name in this context as forward_reads_mapped.

**Comment by HadleyKing** [comment]
See 42ba7dbec5af8f21c8244872291053d06b54a7d7
Eh? Eh? 
What do you think? 
Could we duplicate the Invocation Report and add fields that will accept user input and run the `export_invocation_bco` from `workflows.py`

**Comment by HadleyKing** [comment]
Or... Maybe we use the galaxy [pages](http://localhost:8080/pages/create/pages/create) to create a MD that has the info from `export_invocation_bco`

**Comment by mvdbeek** [comment]
I think we can call this done with the workflow invocation details component.
