### ISSUE TITLE
Markdown Pages Follow Up

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#9118]
Issues encountered in review of #8512 - WIP will update as I make progress on review comments.

- [x] Components don't match - already tracked in #9112.
- [x] It'd be nice to be able to select datasets / collections from other histories than the current one. This would be addressed by #9110 / #9114.
- [ ] Editor context should offer a live preview.

**Comment by mvdbeek** [comment]
Would be great if we can resize embedded images
