### ISSUE TITLE
hiding history panel is broken

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#9130]
if you hide history panel with the little arrow at the bottom of the screen it does not disappear, it actually moves itself to the right, and if you scroll, you will see it again. Especially annoying on pages that use actual horizontal scrolling in the middle pane since it messes up the navigation.

![history-panel-hide](https://user-images.githubusercontent.com/1814954/71021437-5f268a80-20cc-11ea-818e-6ebd965a8e63.gif)

**Comment by jmchilton** [comment]
Fixed by #9688
