### ISSUE TITLE
/workflows/sharing endpoint broken

### ISSUE THREAD

**Issue by afgane** [galaxyproject/galaxy#9131]
![image](https://user-images.githubusercontent.com/338642/71024429-ebd44700-20d2-11ea-857c-96abeb0eca38.png)

Got there by clicking the `Back to Workflow's Sharing Home` button here: 
![image](https://user-images.githubusercontent.com/338642/71024557-2c33c500-20d3-11ea-9249-033e6a4af792.png)

**Comment by martenson** [comment]
![Galaxy__](https://user-images.githubusercontent.com/1814954/71024533-24742080-20d3-11ea-996d-f97ab8066401.png)

**Comment by martenson** [comment]
There seems to be an extra `s` in the url

**Comment by afgane** [comment]
Thanks for the super-quick turnaround @martenson!
