### ISSUE TITLE
Improve the "History > Copy Datasets" form display for usability

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#915]
1. Put the submission button closer to the top of the form. 
2. Wrap dataset names even if there is no whitespace (will currently extend across page)
3. Adjust pull-down menu width to always fit inside the form boxes (will extend beyond)

<img width="272" alt="copy_datasets1" src="https://cloud.githubusercontent.com/assets/8999735/10491621/606cc364-725c-11e5-8af7-9091d8d3d8a5.png">
<img width="400" alt="copy_datasets2" src="https://cloud.githubusercontent.com/assets/8999735/10491625/645a5324-725c-11e5-8f18-1113629956cb.png">
<img width="400" alt="copy_datasets3" src="https://cloud.githubusercontent.com/assets/8999735/10491641/6d6c78c0-725c-11e5-9023-6fdbafe41899.png">

**Comment by carlfeberhard** [comment]
This form/template has been completely removed in #1303, greatly improving its usability.

**Comment by martenson** [comment]
well played @carlfeberhard!

**Comment by jennaj** [comment]
perfect :) thanks @carlfeberhard
