### ISSUE TITLE
"Galaxy An error occurred while updating information with the server. Please contact a Galaxy administrator if the problem persists."

### ISSUE THREAD

**Issue by theokirkland** [galaxyproject/galaxy#9152]
The error occurred while I was trying to do the NGS tutorial.  The tutorial call for using TopHat, but that is depricated, so I tried to use HiSat2.  I got the data successfully, but HiSat2 won't run.

Any ideas?

Theo  tkrikland@ucsd.edu

**Comment by martenson** [comment]
Is this on the usegalaxy.org server?

**Comment by theokirkland** [comment]
Yes it is.

Theo

**Comment by martenson** [comment]
> so I tried to use HiSat2. I got the data successfully, but HiSat2 won't run.

I have trouble understanding the situation at hand. Could you please describe the steps you are taking and when did you actually see the error? Do you still see it?

**Comment by theokirkland** [comment]
I tried running the fast data from the NGS tutorial with Hisat2.  The error was  "Galaxy An error occurred while updating information with the server. Please contact a Galaxy administrator if the problem persists." (#9152).   It took hours before the job got out of the queue.  The error is not visible	now.

Thanks

Theo

**Comment by jmchilton** [comment]
Sorry about these issues. This seems like a cluster issue, hopefully this got resolved? Typically Galaxy usage help is better sought on help.galaxyproject.org.
