### ISSUE TITLE
Low level volume adjustment broken after Nov 29 update.

### ISSUE THREAD

**Issue by echoota** [galaxyproject/galaxy#9174]
I use my Galaxy s10 phone and BT earbuds to help me sleep.  Prior to the Nov29 update I could reduce the volume to the lowest level using the volume rocker AND further adjust the volume lower using the on-screen volume control.  This is a vital function that I grown to depend on. 

Now after the Nov29 update, the last 2 lowest levels of volume using the volume rocker are virtually identical, and WAY to louder than the lowest levels used to be prior to the Nov29 update.  Also when adjusting the volume using the on-screen volume control there is no audible change in the volume below 25%.  

It seems I can't adjust the volume below 25% until I reach 0% which turns off audio.

**Comment by bgruening** [comment]
@echoota this Galaxy project is about a scientific data analysis workbench and not a mobil phone :)

I will close this bug report.
Happy new year!
