### ISSUE TITLE
datatype issue

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/galaxy#9176]
Here is my `mzxml` data :

```xml
<?xml version="1.0" encoding="utf-8"?>
<indexedmzML xmlns="http://psi.hupo.org/ms/mzml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.2_idx.xsd">
  <mzML xmlns="http://psi.hupo.org/ms/mzml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://psi.hupo.org/ms/mzml http://psidev.info/files/ms/mzML/xsd/mzML1.1.0.xsd" id="QC1_014" version="1.1.0">
    <cvList count="2">
      <cv id="MS" fullName="Proteomics Standards Initiative Mass Spectrometry Ontology" version="3.65.0" URI="http://psidev.cvs.sourceforge.net/*checkout*/psidev/psi/psi-ms/mzML/controlledVocabulary/psi-ms.obo"/>
      <cv id="UO" fullName="Unit Ontology" version="12:10:2011" URI="http://obo.cvs.sourceforge.net/*checkout*/obo/obo/ontology/phenotype/unit.obo"/>
    </cvList>
    <fileDescription>
      <fileContent>
        <cvParam cvRef="MS" accession="MS:1000579" name="MS1 spectrum" value=""/>
      </fileContent>
      <sourceFileList count="1">
```

Using the default [datatypes_conf.xml.sample](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/datatypes_conf.xml.sample), it is sniffed as a `blastxml`: 
 - The sniffer: `    <sniffer type="galaxy.datatypes.blast:BlastXml"/>
 - The code :  [blast.py](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/blast.py#L51-L91)

Strange, isn't it?

**Comment by mvdbeek** [comment]
That is odd, this excerpt shouldn't be sniffed as blastxml according to https://github.com/mvdbeek/galaxy/blob/3f4bef05f7a5dd834a0e326284b6a27afaf0a7e0/lib/galaxy/datatypes/blast.py#L85

Can you upload the file in question to gist.github.com, and maybe double-check that the file on disk is really this one ?

**Comment by lecorguille** [comment]
It is this file: https://zenodo.org/record/3244991/files/HU_neg_048.mzML

**Comment by mvdbeek** [comment]
uploading this to my test instance resulted in a `mzml` file. Can you try it again, and if it still fails can you check if you maybe have a very old blastxml datatype installed from the tool shed ? Those should have a lower priority than the built in datatypes, but worth checking.

**Comment by lecorguille** [comment]
The instance is rather new. But indeed, this datatype is indeed also installed: https://toolshed.g2.bx.psu.edu/view/devteam/blast_datatypes/01b38f20197e

But according to the log:
```
galaxy.datatypes.registry DEBUG 2020-01-05 22:21:34,421 [p:22565,w:0,m:2] [MainThread] Overriding conflicting datatype with extension 'blastxml', using datatype from /shared/mfs/data/galaxy/server/config/datatypes_conf.xml.sample.
```

(By the way, Happy New Year Marius @mvdbeek!)

**Comment by lecorguille** [comment]
Hum, you were write, here is the guilty : https://toolshed.g2.bx.psu.edu/view/devteam/blast_datatypes/01b38f20197e
So it seems that it overwrite somehow the one shipped with Galaxy.

I had to uninstall it through the admin panel but I don't like that so much. We aim to only manage our instance using ansible. 
Do you know a way to do that programatically?
Or is there a way to tweak this datatype?

**Comment by jmchilton** [comment]
Issues like this is why I discourage tool shed based datatypes - there is just no way to resolve these things let alone provide usable information to admins. Sorry about this.
