### ISSUE TITLE
Enhancement: Consider a bit longer "show/hide" display timing for scroll bars

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#9187]
The "Analyze Data" view's 3 panels scroll bars go away very quickly now. (left tool, center, right history)

Would it be possible to extend the "show" display timing to be a bit longer? Across views/panels? 

I've noticed this in the History & Tool panels using Mac OSX with Chrome, Safari, and Firefox. The scroll bars can be a bit small/thin, plus difficult to hover over and capture. 

An end-user noticed this when working on a PC using Chrome and Firefox. Details (OS/browser versions) along with a screenshot: https://help.galaxyproject.org/t/galaxy-left-panel-scrollbar-hidden/2745. 

In that screenshot, it does appear as if the center/right panels have "persistent" scroll bars on a PC using Chrome (?), but the left panel does not, which makes the display inconsistent. Perhaps someone who uses a PC could see if they can reproduce? 

I cannot reproduce that on a Mac with any browser. Only one panel has an active scroll bar at any particular time, and only when in use. Meaning, none are ever persistent and having two displayed at the same time is not even possible.

ping @guerler or maybe @dannon for feedback?

**Comment by jennaj** [comment]
Hum, this might actually be a browser "feature", not Galaxy: https://support.google.com/chromebook/thread/1654780?hl=en

**Comment by shenweiyan** [comment]
The real reason is that I changed the browser's default font size to small. When I changed the font in my browser to `Medium(Recommended)`, everything was fine.
![setting Font size to `Medium(Recommended)`, everything was fine ](https://user-images.githubusercontent.com/26101369/71947105-b10f8b80-3206-11ea-9a88-8bb4e3836d9a.png)

**Comment by martenson** [comment]
In my experience the scroll bars are best to be left for browsers to manage. By default they look different on every browser/OS combination and even though css has means to change them they will always look off place with other pages / everything else on the system when customized.

Similarly when forcing Galaxy to use different font size than it is designed for inconsistencies are going to appear, which I believe are too niche to track and fix (unless it completely breaks something critical).

I am closing this for now, but thanks for bringing it up.
