### ISSUE TITLE
Dataset tags: "name:tag" displayed in workflow+tool form input select lists. "#tag" would be better/more consistent

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#9191]
Might be ticketed or adjusted for an upcoming release already .. if so, please close this out as dup with link to other. It definitely is not new (has been discussed before) but can't find a ticket or PR for it. ping @guerler @dannon 

__Punch-line__: Could we display tags in the workflow/tool select menus the same way are displayed in other views? For UX consistency? eg: `#tag` & `tag`. 

**Good-1:** A dataset in a history panel - collapsed. Example dataset has two tags, `#original` and `original`. The display is as expected (hash-prefixed tags shown + no-hash-prefixed tags hidden).

<img width="264" alt="dataset-with-two-tag-types-collapsed" src="https://user-images.githubusercontent.com/8999735/71999334-1018d480-31f6-11ea-99a6-ce3b3db641f0.png">

**Good-2:** That same dataset in a history panel - expanded with "edit tags" toggled to show. This display is informative & easily interpreted by end-users. Tags are displayed exactly as entered:

<img width="261" alt="dataset-with-two-tag-types-expanded" src="https://user-images.githubusercontent.com/8999735/71999597-9503ee00-31f6-11ea-8ee8-778fb1b1a460.png">

**Good-3:** That same dataset in the "Saved Datasets" view (User > Datasets). This display is also informative & easily interpreted.

<img width="1048" alt="dataset-with-two-tag-types-in-saved-datasets-view" src="https://user-images.githubusercontent.com/8999735/72003269-cfbd5480-31fd-11ea-9678-c5d7914e6e85.png">

**Odd-1:** That same dataset in a workflow's dataset select list. The display is informative _yet inconsistent with other views_. Notice the difference between how `#original` versus `original` is shown. Each "hash-prefixed" tag has extra `name:` added in (cryptic/exposed code artifact?). Can see in screenshot how cluttered this type of tag display formatting can become if 2+ hash-prefixed tags are assigned to datasets:

<img width="720" alt="dataset-with-two-tag-types-in-wf-input-select-list" src="https://user-images.githubusercontent.com/8999735/72000591-7dc60000-31f8-11ea-80c8-028f9215f01b.png">

**Odd-2:** That same dataset in a tool form's dataset select list. Same display as workflow select, eg: `name:tag` instead of `#tag`.

<img width="728" alt="dataset-with-two-tag-types-in-tool-input-select-list" src="https://user-images.githubusercontent.com/8999735/72005542-aeab3280-3202-11ea-9ce3-6194f37ebed1.png">

**Comment by jmchilton** [comment]
Fixed by #9281 I believe. @jennaj create a new issue or reopen this if this is still a problem?
