### ISSUE TITLE
Document that compiled mako templates need to be removed when moving to python 3

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#9211]

**Comment by nsoranzo** [comment]
Actually I think it's a good practice with any release upgrade, together with `find . -name '*.pyc' -delete`

**Comment by mvdbeek** [comment]
Added this to https://github.com/galaxyproject/galaxy/pull/9271, so dropping the milestone here. We may want to check if we can prevent creating these files in the first place. I doubt that having the cache has any advantage in the way we use mako.

**Comment by mvdbeek** [comment]
I guess mako is on the way out, probably not worth investing time here.
