### ISSUE TITLE
tool_dependencies.xml action autoconf without auto-prefix

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy#922]
In discussion on https://github.com/galaxyproject/tools-iuc/pull/330 we discussed an example recipe for QT which does this:

``` xml
<action type="shell_command">./configure -prefix $INSTALL_DIR -opensource -confirm-license -qt-xcb</action>
<action type="make_install" />
```

See https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_qt_4_8/tool_dependencies.xml and https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_qt_5_1/tool_dependencies.xml

Switching from a `shell_command` to the `autoconf` action would be nice, but the later will automatically add `--prefix=$INSTALL_DIR` unless the optional arguments include `prefix=`, see:

https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py#L459

For this slightly unusual configure scripts @yhoogstrate suggests an enhancement along these lines:

``` xml
<action type="autoconf" autoprefix="False">-prefix $INSTALL_DIR -opensource -confirm-license -qt-xcb</action>
```

This would also help with the R recipes, e.g.

```
./configure CPPFLAGS=-I$READLINE_INCLUDE_PATH LDFLAGS="-L$READLINE_LIB_PATH -L$NCURSES_LIB_PATH -lreadline -lncurses" --enable-R-shlib --with-x=no --libdir=$INSTALL_DIR/lib/ --bindir=$INSTALL_DIR/bin/ --datarootdir=$INSTALL_DIR/share/
make
make install
```

becomes:

``` xml
<action type="autoconf" autoprefix="False">CPPFLAGS=-I$READLINE_INCLUDE_PATH LDFLAGS="-L$READLINE_LIB_PATH -L$NCURSES_LIB_PATH -lreadline -lncurses" --enable-R-shlib --with-x=no --libdir=$INSTALL_DIR/lib/ --bindir=$INSTALL_DIR/bin/ --datarootdir=$INSTALL_DIR/share/</action>
```

CC @bgruening

**Comment by bgruening** [comment]
I'm +/-0 on this. 
I think in such special cases it's ok to fallback to:

```
<action type="shell_command"></action>
<action type="make_install" />
```

**Comment by peterjc** [comment]
I'm quite happy with the fall back too, the `tool_dependencies.xml` mini-language is already overly complex.

**Comment by nsoranzo** [comment]
I'd also vote for leaving it like it is now.

**Comment by jmchilton** [comment]
Yeah - I am also -0 on this. I'd close this issue but it was an interesting discussion!

**Comment by martenson** [comment]
the `tool_dependencies.xml` is very deprecated now so this should not be needed anymore
