### ISSUE TITLE
mercurial in release_19.09

### ISSUE THREAD

**Issue by drosofff** [galaxyproject/galaxy#9229]
https://github.com/galaxyproject/galaxy/blob/56362e3be2f75e912306efe6fdd94eba2bddb675/lib/galaxy/dependencies/pipfiles/default/pinned-requirements.txt#L86

Hi
I am currently testing the release_19.09 in a python 3.5 environment.
From this line (I understand that) no mercurial modules will be installed if in python 3 env. However I noticed that the requirement is reintroduced (irrespective of the python env) in both the 20.01 and the dev branch.

Is it a bug or a feature ? Maybe a question for @nsoranzo ?

**Comment by mvdbeek** [comment]
That's right, mercurial is only python 3 compatible starting with 5.2, and we started using it with https://github.com/galaxyproject/galaxy/pull/9065. We had to adapt some tool shed code that used deprecated mercurial functions. So if you want to run Galaxy release 19.09 (so not the toolshed) on python 3 today I would suggest installing a global system mercurial, or mercurial >= 5.2 in galaxy's virtualenv.

**Comment by drosofff** [comment]
OK @mvdbeek thanks !

Does that mean that the 19.09 officially does not work under py3, unless manual adaptation by the server admin ? (asking this for planning the py3 migration we already discussed on the ansible side).

What do you mean by "(so not the toolshed)" ?

**Comment by mvdbeek** [comment]
Only the tool shed server doesn't run on python 3, everything else is working fine. Yes, mercurial needs to be installed manually on release <= 19.09

**Comment by drosofff** [comment]
Thanks. Should I close the issue ?
