### ISSUE TITLE
Not able to install tools via tool shed

### ISSUE THREAD

**Issue by DrGuantanamo** [galaxyproject/galaxy#9235]
This issue might be related to #7059. I am using a local installation of 19.09 release branch on a quite fresh centos 8 distribution. 

As stated in #7059, I get the following errors in my error log:
> Phase: Tool Loading
> File: /home/cseifert/usegalaxy/galaxy/tools/phenotype_association/sift.xml
> [Errno 2] No such file or directory: '/home/cseifert/usegalaxy/galaxy/tool-data/sift_db.loc'

> Phase: Tool Loading
> File: /home/cseifert/usegalaxy/galaxy/tools/evolution/add_scores.xml
> [Errno 2] No such file or directory: '/home/cseifert/usegalaxy/galaxy/tool-data/add_scores.loc'

> Phase: Tool Loading
> File: /home/cseifert/usegalaxy/galaxy/tools/evolution/codingSnps.xml
> [Errno 2] No such file or directory: '/home/cseifert/usegalaxy/galaxy/tool-data/codingSnps.loc'

Example to reproduce the issue:
- Log in as Admin user
- Tool Management > Install or Uninstall > Search: fastqc
- Select fastqc > click install (rev. 20 fastqc 0.72+galaxy1)
- Choose "Statistics" from Target selection > click ok
Directly after clicking ok, the install button changes to "error". There is no change to "cloning" or something else. No error message appears, no additional link appears in the Tool Management section.

Unfortunately, I just understand half of what is written in #7059 since I am new to galaxy and new to python. 

Information that might help:
The issue is reproducible with selinux in permissive mode and firewall switched of.
Yesterday, I tried to using a dev branch clone. With the dev branch, I did not encounter this tool installation error. But later on some other instabilities occurred that might be normal for a development branch installation, but these issues kept me away from my actual work with the genomes. So, I tried to go back to the last stable branch 19.09 and file this report to track down this issue.  

I am sorry I forgot something to mention. Please stay clement, since this is my first issue that I ever posted on github. I am willing to learn. ;-)

**Comment by bernt-matthias** [comment]
Does the tool appear in the list of tools when you check 'manage tools' in the admin panel?

I think the error messages about missing loc files are unrelated.

**Comment by DrGuantanamo** [comment]
Thank you for answering.

> Does the tool appear in the list of tools when you check 'manage tools' in the admin panel?

Yes, it does.
The table row consists of:
- Name: Drop down button named "fastqc" with options:
   - Update tool shed status
   - Deactivate or uninstall
   - Reset to install
- Description: Read QC reports using FastQC
- Owner: Devteam
- Revision: e7b2202befea
- Installation status: Error [no mouse over label and not clickable for further error details]
- Tool shed: toolshed.g2.bx.psu.edu 

> I think the error messages about missing loc files are unrelated.

I added this information since coincidentally #7059 had the same error logs and the two noticeable problems might have the same root cause. But of cause, a short copy command from the sample files in the same folder would solve the missing loc file problem for me.

**Comment by DrGuantanamo** [comment]
Sorry. I did a stupid newbie mistake. The Drop down button is clickable as well. There are further Error details:

Red box as header:
This repository is not installed correctly (see the Repository installation error below). Choose Reset to install from the Repository Actions menu, correct problems if necessary and try installing the repository again.

Repository installation error:
Error cloning repository: [Errno 2] No such file or directory: 'hg': 'hg'

**Comment by mvdbeek** [comment]
Ah, you need to install mercurial, you're probably on python 3, where on release < 20.01 we can't install mercurial automatically.

**Comment by DrGuantanamo** [comment]
Thank you very much. You made my day! :)

Installing mercurial and restarting solved the problem.
A full reinstallation (with python 3.6 and mercurial 4.8.2) solved the problem as well (of cause), but did not solve the missing loc file topic. As @bernt-matthias expected, this does not seem to be related.
I will solve this with copies from the respective sample files.

Thanks again for the fast help.

**Comment by mvdbeek** [comment]
Sure, no problem, and welcome to the community :).

**Comment by laurentierney** [comment]
Hi @DrGuantanamo  & @mvdbeek 

I am having the same issue, I have updated my python and installed mercurial but still having issues, the tools now download and appear but when I try to use them, the output is 0 bytes ( so I take it the tools is there but not functional) When you say "A full reinstallation" what does this mean? uninstalling local galaxy from the pc and reinstalling it? 

I have also have the error with the missing loc files, I have since duplicated the sample loc files and renamed one, removing the "sample" part but the errors still returns when I try downloading a tool, again was this solved by removing the local galaxy and reinstalling it?

**Comment by mvdbeek** [comment]
You've successfully installed the tool, that's a different problem you're having then. I'd suggest you have a look at your logs, which should contain more information as to why your tool is failing. For these kind of questions I would suggest asking for help at help.galaxyproject.org.
