### ISSUE TITLE
Rerun failed tool does not use previously selected, now hidden datasets.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#926]
This is a workflow/tool form bug.

In previous versions of Galaxy, rerunning a tool would fill out the tool form with the CORRECT, now hidden (due to workflow) dataset. Now, the tool form does not see the hidden datasets, and chooses another arbitrary dataset which matches the data type. This requires you to manually unhide the correct dataset and is incredibly unpleasant.

Reported by 
- me https://botbot.me/freenode/galaxyproject/2015-04-03/?msg=35769182&page=1
- @scholtalbers https://botbot.me/freenode/galaxyproject/2015-10-09/?msg=51514202&page=1

to @dannon, @guerler, and @blankenberg. 

Still not fixed (upgraded to :dev yesterday) so raising this issue on GH with a whole mess of people tagged :)

**Comment by dannon** [comment]
@guerler is on it, we talked about this a few days ago.

**Comment by hexylena** [comment]
Yep, assuming after @scholtalbers brought it up. I just now found that when searching for mentions of this in IRC :)

**Comment by guerler** [comment]
It seems that this can be fixed by revising the dataset matcher such that it includes hidden datasets. Ping @jmchilton. https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/parameters/basic.py#L2164

**Comment by scholtalbers** [comment]
Just adding a comment to emphasize the need for a fix ;) (assuming it hasn't since the ticket is still open). This can be so confusing and cumbersome with bigger workflows/histories...

**Comment by blankenberg** [comment]
This is a significant regression.

**Comment by chambm** [comment]
I'm on 17.05 and when I rerun a failed HISAT2 dataset that ran on a collection, the rerun form shows the collection rather than the individual failed dataset. Is that by design?
