### ISSUE TITLE
LDA Effect size error (LEfSE)

### ISSUE THREAD

**Issue by cmk6jm** [galaxyproject/galaxy#9262]
Hello,

First of all thank you for all of your hard work developing such an informative and intuitive tool. I have been successful in running the LEfSE analyses for some of my data, but unfortunately, for the majority I get an error message when it comes to the step where the Effect size is calculated. The error message is copied below:

/galaxy_venv/local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:185: RRuntimeWarning: Error in (function (file = "", n = NULL, text = NULL, prompt = "?", keep.source = getOption("keep.source"),  : 
  <text>:1:47: unexpected numeric constant
1: effect.size <- abs(mean(LD[sub_d[,"class"]==""1
                                                  ^

  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "/shed_tools/testtoolshed.g2.bx.psu.edu/repos/george-weingart/lefse/a6284ef17bf3/lefse/run_lefse.py", line 89, in <module>
    if params['rank_tec'] == 'lda': lda_res,lda_res_th = test_lda_r(cls,feats,class_sl,params['n_boots'],params['f_boots'],params['lda_abs_th'],0.0000000001,params['nlogs'])
  File "/export/shed_tools/testtoolshed.g2.bx.psu.edu/repos/george-weingart/lefse/a6284ef17bf3/lefse/lefse.py", line 199, in test_lda_r
    robjects.r('effect.size <- abs(mean(LD[sub_d[,"class"]=="'+p[0]+'"]) - mean(LD[sub_d[,"class"]=="'+p[1]+'"]))')
  File "/galaxy_venv/local/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 358, in __call__
    p = _rparse(text=StrSexpVector((string,)))
rpy2.rinterface.RRuntimeError: Error in (function (file = "", n = NULL, text = NULL, prompt = "?", keep.source = getOption("keep.source"),  : 
  <text>:1:47: unexpected numeric constant
1: effect.size <- abs(mean(LD[sub_d[,"class"]==""1
                                                  ^

For your reference, I am using this tool to analyze human gut microbiome data.

Also, I cross-posted to the forum (link: https://help.galaxyproject.org/t/lda-effect-size-error/2840)

Any guidance would be greatly appreciated.

all the best,
Caroline

**Comment by nsoranzo** [comment]
Dear Caroline,
this issue tracker is reserved to issues with Galaxy itself, while this is a tool issue. The correct place is the forum where you already posted, or the repository where the tool is developed.
