### ISSUE TITLE
Unknown parameters in workflow invocation menu

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#927]
From the devteam/ncbi_blast_plus blastp tool:

![ugh1](https://cloud.githubusercontent.com/assets/458683/10522036/93de6f90-7338-11e5-88d7-2bdc753c5817.png)
- no idea what parameters those are
- or why they're non-editable despite having an edit box.

@nsoranzo mentioned to ping @guerler

**Comment by hexylena** [comment]
More workflow toolform issues that might go away if the workflow invocation was updated to use the toolform:

![workflow-toolform](https://cloud.githubusercontent.com/assets/458683/10622047/4cfb7706-774a-11e5-806b-b2b5cc2ffa53.png)

The new tool form uses a search box which lets my users find exactly what they're looking for (even if the string appears at the end of the list). The old form means that it's basically impossible for them to find the right element that they want.

**Comment by guerler** [comment]
Thanks for collecting these, we should be able to test them soon in the new run workflow tool form.

**Comment by hexylena** [comment]
@guerler, great! Happy to test/help however I can.

**Comment by hexylena** [comment]
More of this:

**Tool Invocation**

![repeat-issue1](https://cloud.githubusercontent.com/assets/458683/10679855/ce52e1da-78e0-11e5-9d6e-f68ccdeb0048.png)

**In Workflow**

![repeat-issue](https://cloud.githubusercontent.com/assets/458683/10679900/1e31f2b8-78e1-11e5-88b9-29eab72eb3f8.png)
