### ISSUE TITLE
Caught LDAPError while authenticating : SERVER_DOWN({u'info': 'Transport endpoint is not connected', 'errno': 107, 'desc': u"Can't contact LDAP server"},)

### ISSUE THREAD

**Issue by PreenaPrakash** [galaxyproject/galaxy#9274]
Caught LDAPError while authenticating : SERVER_DOWN({u'info': 'Transport endpoint is not connected', 'errno': 107, 'desc': u"Can't contact LDAP server"},)

I am trying to Integrate Active Directory to my application.
using Django==1.11.26

django-auth-ldap==1.7.0

python-ldap==3.2.0

Anyone please help on this ?

_Originally posted by @PreenaPrakash in https://github.com/galaxyproject/galaxy/issues/3178#issuecomment-579633597_

**Comment by hexylena** [comment]
The error does not sound related to the Galaxy project (we don't use Django for anything) so I'm afraid we cannot help. You might look to the django-auth-ldap community for help. https://django-auth-ldap.readthedocs.io/en/latest/
