### ISSUE TITLE
Workflow Extraction of Column Parameters

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#928]
@nekrut reported that workflow extraction of column parameters don't show up in the workflow editor correctly. Either they are breaking at extraction time or when displaying the workflow. The workflow editor changed more recently so that would be my guess.

**Comment by nekrut** [comment]
This is absolutely horrific bug = you create a workflow from a history and most of your parameters are lost, so the workflow is unusuable

**Comment by martenson** [comment]
ping @guerler

**Comment by nekrut** [comment]
in fact, you do not know that it is unusable - you rerun and it fails for unknown reason (the actual reason is that parameters are filled with blank values).

**Comment by nekrut** [comment]
Here is how to replicate this problem:
- Import this history:  https://usegalaxy.org/u/aun1/h/galaxy-101-2015
- Extract workflow
- Edit workflow and click on, say, `Group` tool. You will see that the `Group by column` parameter is empty

**Comment by guerler** [comment]
Thx for the example. It seems that this bug effects the display in the workflow editor form if the history/workflow extraction feature is used. The values are available and properly displayed in the run workflow form on workflow execution but its obviously still a serious issue.
