### ISSUE TITLE
config file cleanup error

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#9285]
I'm on 19.09 (47c5a0e): error during config_file cleanup

```
Unable to cleanup job 56296
Traceback (most recent call last):
  File "lib/galaxy/jobs/__init__.py", line 1728, in cleanup
    os.remove(fname)
FileNotFoundError: [Errno 2] No such file or directory: '/work/songalax/galaxy/database/jobs_directory/056/56296/tmp807_qtb0'
```

The tool was https://github.com/galaxyproject/tools-iuc/blob/master/tools/collection_element_identifiers/collection_element_identifiers.xml, but I guess this is irrelevant.

**Comment by mvdbeek** [comment]
Should be fixed by https://github.com/galaxyproject/galaxy/pull/9245/commits/3568629c7103c1f8d41e2b4c8a83b10304c7c472
