### ISSUE TITLE
Galaxy email message delivered thru smtp is different from the imap append on sent folder

### ISSUE THREAD

**Issue by nvsnvikram** [galaxyproject/galaxy#9295]
We are seeing that galaxy email app sends a different mime message through smtp that has no rfc822 message id while imap append has rfc822 message id. Can we make this consistent?

Here is an example:
****************** SMTP Sent Message
Date: Fri, 31 Jan 2020 16:00:13 -0800
Subject: My subject
Importance: normal
From: "foo user" <foouser@foo.com>
To: foouser1@foo.com
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="--_com.samsung.android.email_13261114560360030"

----_com.samsung.android.email_13261114560360030
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: base64

VGVzdCBtZXNzYWdlIGJvZHlCaW5TZW50IGZyb20gbXkgVmVyaXpvbiwgU2Ftc3VuZyBHYWxheHkg
c21hcnRwaG9uZQ==

----_com.samsung.android.email_13261114560360030
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: base64

PGh0bWw+PGhlYWQ+PG1ldGEgaHR0cC1lcXVpdj0iQ29udGVudC1UeXBlIiBjb250ZW50PSJ0ZXh0
L2h0bWw7IGNoYXJzZXQ9VVRGLTgiPjwvaGVhZD48Ym9keSBkaXI9ImF1dG8iPjxkaXYgZGlyPSJh
dXRvIj48Zm9udCBmYWNlPSJzYW5zLXNlcmlmIj5UZXN0IG1lc3NhZ2UgYm9keTwvZm9udD48L2Rp
dj48ZGl2IGRpcj0iYXV0byI+PGJyPjwvZGl2PjxkaXYgZGlyPSJhdXRvIj48YnI+PC9kaXY+PGRp
diBkaXI9ImF1dG8iPkJpbjwvZGl2PjxkaXYgaWQ9ImNvbXBvc2VyX3NpZ25hdHVyZSIgZGlyPSJh
dXRvIj48ZGl2IHN0eWxlPSJmb250LXNpemU6ODUlO2NvbG9yOiM1NzU3NTciIGRpcj0iYXV0byI+
U2VudCBmcm9tIG15IFZlcml6b24sIFNhbXN1bmcgR2FsYXh5IHNtYXJ0cGhvbmU8L2Rpdj48L2Rp
dj48ZGl2IGRpcj0iYXV0byI+PGJyPjwvZGl2PjwvYm9keT48L2h0bWw+

---_com.samsung.android.email_13261114560360030-

****************** IMAP Append Message
Subject: My subject
From: "foo user" <foouser@foo.com>
Date: Fri, 31 Jan 2020 16:00:13 -0800
To: foouser1@foo.com
Content-Type: multipart/mixed; boundary="----6E8R42K0C62YSLVYLD7R1P4BCHR0MS"
MIME-Version: 1.0
Message-ID: <3oktb8bbokmhtmdkf1247p6k.1580515223142@email.android.com>

------6E8R42K0C62YSLVYLD7R1P4BCHR0MS
Content-Type: text/html;
charset=utf-8
Content-Transfer-Encoding: base64

PGh0bWw+PGhlYWQ+PG1ldGEgaHR0cC1lcXVpdj0iQ29udGVudC1UeXBlIiBjb250ZW50PSJ0ZXh0
L2h0bWw7IGNoYXJzZXQ9VVRGLTgiPjwvaGVhZD48Ym9keSBkaXI9ImF1dG8iPjxkaXYgZGlyPSJh
dXRvIj48Zm9udCBmYWNlPSJzYW5zLXNlcmlmIj5UZXN0IG1lc3NhZ2UgYm9keTwvZm9udD48L2Rp
dj48ZGl2IGRpcj0iYXV0byI+PGJyPjwvZGl2PjxkaXYgZGlyPSJhdXRvIj48YnI+PC9kaXY+PGRp
diBkaXI9ImF1dG8iPkJpbjwvZGl2PjxkaXYgaWQ9ImNvbXBvc2VyX3NpZ25hdHVyZSIgZGlyPSJh
dXRvIj48ZGl2IHN0eWxlPSJmb250LXNpemU6ODUlO2NvbG9yOiM1NzU3NTciIGRpcj0iYXV0byI+
U2VudCBmcm9tIG15IFZlcml6b24sIFNhbXN1bmcgR2FsYXh5IHNtYXJ0cGhvbmU8L2Rpdj48L2Rp
dj48ZGl2IGRpcj0iYXV0byI+PGJyPjwvZGl2PjwvYm9keT48L2h0bWw+

------6E8R42K0C62YSLVYLD7R1P4BCHR0MS
Content-Type: text/plain;
charset=utf-8
Content-Transfer-Encoding: base64

VGVzdCBtZXNzYWdlIGJvZHlCaW5TZW50IGZyb20gbXkgVmVyaXpvbiwgU2Ftc3VuZyBHYWxheHkg
c21hcnRwaG9uZQ==

-----6E8R42K0C62YSLVYLD7R1P4BCHR0MS-

**Comment by dannon** [comment]
@nvsnvikram I think you've found the wrong Galaxy.  This repository relates to the open source data science platform, not the telephone.
