### ISSUE TITLE
Bug reporting page asks for email even when logged in

### ISSUE THREAD

**Issue by nuwang** [galaxyproject/galaxy#9296]
There are two issues here. One is that it doesn't seem necessary to ask for the email since we already know what it is. The second is that the user can enter an arbitrary email, which means you could potentially spam someone with it. The behaviour seems particularly desirable when `require_login=True`, and/or `user_activation_on=True`, since the user email on record is guaranteed to be correct.

**Comment by nsoranzo** [comment]
Agreed the form should be pre-filled with the email associated with the logged-in user,  but I'd keep it an editable field. I don't think this has been or will ever be a serious source of spam, at least no more than other thousands of support page forms all over the Internet.

**Comment by guerler** [comment]
I opened a PR to revise the dataset error form. I think that the email information is redundant. Also, error reports may or may not lead to a response from the administrator, reporting however should still be made as simple as possible, such that relevant information is still collected.
