### ISSUE TITLE
display application (IGV): too many tracks are created.

### ISSUE THREAD

**Issue by FredericBGA** [galaxyproject/galaxy#9298]
I have shared an history on galaxy.eu: [one vcf on Hg19](https://usegalaxy.eu/u/fredbga/h/igv-display-application). When I use the `display with IGV local Human hg19 ` link, my local IGV will open at least 10 tracks.
The genome is grab from [the Broad Institute](http://data.broadinstitute.org/igvdata/genomes/genomes.txt). And the vcf also (ftp://ftp.broadinstitute.org/bundle/hg19/).

Can you reproduce the bug? I'm using IGV 2.8.0.
This is the same behaviour with my Galaxy instance (19_05) and my private data.

**Comment by mvdbeek** [comment]
Looks fine to me:
<img width="1266" alt="Screenshot 2020-02-03 at 09 23 28" src="https://user-images.githubusercontent.com/6804901/73636723-dc02c900-4666-11ea-92e9-afc74c8c80b4.png">

**Comment by mvdbeek** [comment]
I'd perhaps try updating IGV and try a different browser ?

**Comment by FredericBGA** [comment]
@mvdbeek thank you. The problem was Firefox. Opened for too long? A restart and this strange behavior is gone.
I close the issue.
