### ISSUE TITLE
Check if we need to change StopIteration handling in generators

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#9325]
[PEP0479](https://www.python.org/dev/peps/pep-0479/), active by default in python 3.7, will transform StopIteration to RuntimeError if raised in a generator, so catching StopIteration may not work.

https://www.python.org/dev/peps/pep-0479/#writing-backwards-and-forwards-compatible-code explains how we should handle this.

**Comment by jdavcs** [comment]
Yes, I think we should. Unless you're working on it, I'll take it on. There are a few places in the codebase that will need to be modified; not sure about tools though (the sequence utilities suite will need to be updated).

**Comment by mvdbeek** [comment]
Yeah, if you can go over it that would be awesome.

**Comment by jdavcs** [comment]
i'm on it.

**Comment by nsoranzo** [comment]
I'm under the impression this has a very limited impact, hopefully.

**Comment by mvdbeek** [comment]
Yeah, not all uses are wrong, but we do need to update galaxy-sequence-utils, the vcf reader doesn't work: https://github.com/galaxyproject/sequence_utils/blob/master/galaxy_utils/sequence/vcf.py#L126

**Comment by jdavcs** [comment]
yes, that and same case in fastq.py and fasta.py (sequence-utils)

**Comment by jdavcs** [comment]
@mvdbeek I think the vcf code is correct (the line you referenced). The `StopIteration` is not raised in that code block, it's raised in `next()`, which is not a generator function - so it is not converted to a `RuntimeError` (it's propagated as a StopIteration). Unless I'm misreading the code.. How did yours break?

**Comment by mvdbeek** [comment]
Hmm, you're right, that should be fine. Guess I jumped to conclusions, the issue is probably in `vcf_to_maf_customtrack.py` (which is a mess).
The traceback is
```
|  Traceback (most recent call last):
|  File "/usr/local/lib/python3.7/site-packages/galaxy_utils/sequence/vcf.py", line 121, in __iter__
|  yield self.next()
|  File "/usr/local/lib/python3.7/site-packages/galaxy_utils/sequence/vcf.py", line 116, in next
|  raise StopIteration
|  StopIteration
|  The above exception was the direct cause of the following exception:
|  Traceback (most recent call last):
|  File "/Users/mvandenb/.planemo/planemo_tmp_h1hqti86/vcf_to_maf_customtrack.py", line 163, in <module>
|  main()
|  File "/Users/mvandenb/.planemo/planemo_tmp_h1hqti86/vcf_to_maf_customtrack.py", line 104, in main
|  for vc, variants in vcf_file:
|  File "/Users/mvandenb/.planemo/planemo_tmp_h1hqti86/vcf_to_maf_customtrack.py", line 60, in __iter__
|  yield next(self)
|  File "/Users/mvandenb/.planemo/planemo_tmp_h1hqti86/vcf_to_maf_customtrack.py", line 40, in __next__
|  vc = next(self.reader)
|  RuntimeError: generator raised StopIteration
```

**Comment by mvdbeek** [comment]
Mystery solved, @ic4f fixed this in https://github.com/galaxyproject/sequence_utils/commit/082b429cdc3c30f1201f45328394b31b09a282b8 but we never rolled out a new version 🤣

**Comment by jdavcs** [comment]
Oh, good. I'll double check the rest + the galaxy code base.

**Comment by mvdbeek** [comment]
I think there were no further problems. Thanks @ic4f !
