### ISSUE TITLE
Tool Shed: Incorporate Info and Help for content and links

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#933]
General idea is to incorporate pop-up help text for the links and other key content directly within the Tool Shed UI. The model used in Cloudman via the use of "?" - "what does this do" icons could be a good model to use. Keeps everything "Galaxy UI" consistent.

For example, the github link could have a pop-up noting that this is the place to review/report issues for a tool. ![toolshed_ui_help](http://i.imgur.com/cWaHYC9.png)

**Comment by martenson** [comment]
With TS2.0 out I am closing this issue since we are not likely to work in its predecessor.

Also the UI has been trimmed down and most use will stem from APIs.
