### ISSUE TITLE
"Appy Rule to Collection tool -- Bug with preserving number of groups from regex filter

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#9333]
**All details here:** https://github.com/galaxyproject/usegalaxy-playbook/issues/282

Not sure if a known or not.

This impacts a specific part of a GTN tutorial, plus, anyone else using the tool.

@jmchilton @mvdbeek

**Comment by jmchilton** [comment]
@jennaj I suspect this has been fixed by https://github.com/galaxyproject/galaxy/pull/10390 - I don't know if that commit has made it to usegalaxy.org yet though.

**Comment by jennaj** [comment]
Ok, thanks -- I try a retest, thanks!

**Comment by mvdbeek** [comment]
Pretty sure this is working alright.
