### ISSUE TITLE
Text editor tool

### ISSUE THREAD

**Issue by simonbray** [galaxyproject/galaxy#9352]
It would be useful to have a simple text editor tool in Galaxy. For example, I'm working on developing molecular dynamics tools on usegalaxy.eu; these tools use config files which often need to be modified slightly between runs. It would be really nice to be able to do this in Galaxy rather than downloading and reuploading.

The tool should work as follows: the user selects a dataset to edit, the dataset is loaded into a very simple text editor interface and the user makes some changes. Then the results are saved to a new dataset. Optionally a diff file could be saved as well.

As always I'm willing to implement this myself but would appreciate some tips where to start.

(I'm aware this is also possible using the interactive tools on usegalaxy.eu but this seems like overkill for such a simple functionality.)

**Comment by simonbray** [comment]
ping @anuprulez, @OlegZharkov - maybe one of you is interested in helping? I would probably need some help with JS stuff. Björn suggested this could be integrated as a visualization.

**Comment by simonbray** [comment]
(Though this poses the same problem that Pavan has currently, i.e. how to return an output from the visualization to the history as a dataset.)

**Comment by bernt-matthias** [comment]
Do you have an example of such a file. Wondering if there is an alternative...

**Comment by simonbray** [comment]
We've been discussing a number of alternatives. One would be to create tools based on packages like parmed or GromacsWrapper (https://github.com/ParmEd/ParmEd; https://github.com/Becksteinlab/GromacsWrapper), but I don't think this provides the required flexibility.

Another idea I had was a generic tool for manipulating text files (PR: https://github.com/bgruening/galaxytools/pull/954) but I think this is not very intuitive for the user.

**Comment by OlegZharkov** [comment]
@simonbray and @pavanvidem. If you just want to export (modified) visualization to history, here is how you do it. 
https://github.com/galaxyproject/galaxy/blob/1a60ac03e477602290ab11cf0015c18efc917c73/config/plugins/visualizations/editor/templates/editor.mako#L34-L49
Maybe I will  need to make it as a separate library

**Comment by simonbray** [comment]
ping @pavanvidem

**Comment by OlegZharkov** [comment]
@simonbray @pavanvidem

**Comment by pavanvidem** [comment]
sorry, somehow I missed this thread regardless of multiple pings. This is exactly what we were also looking for our visualization. @anuprulez is the developer of this visualization. He should understand better than me how it works. From the comments I understood that there is a way which is great!
