### ISSUE TITLE
Installed tools disappear from tool panel after Galaxy restart if shed_tool_config_file not explicitly set

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#9356]
This happens on 19.09 and has been previously reported at https://help.galaxyproject.org/t/updated-to-19-09-tool-menu-items-disappear/2563 and again today on gitter.
Most existing Galaxy installations just append the `shed_tool_conf.xml` file to `tool_config_file`, so this should ideally continue to work.

**Comment by natefoo** [comment]
Do we know the circumstances under which this occurs?

**Comment by mvdbeek** [comment]
Yeah, I think I get it now:
If no `shed_tool_config_file` is set and there isn't any other shed enabled tool config file we inject it at startup (so as to not surprise deployers with a new shed config file) here: https://github.com/mvdbeek/galaxy/blob/fcb1a9d2c72c6630d22d212eb553df095d915d93/lib/galaxy/config/__init__.py#L1026

But we don't actually call `toolbox._load_tool_panel()` after that, so while loaded, the tools are not in the toolbox. Once we reload the toolbox we do get the full panel, because that also calls `toolbox._load_tool_panel()` with the full tool_config list. So I think all of the logic for selecting which config files to inject belongs in the toolbox. Pretty sure that would fix it.

**Comment by mvdbeek** [comment]
I think https://github.com/galaxyproject/galaxy/pull/9364 should fix this.
