### ISSUE TITLE
DOI link appears twice in citations 

### ISSUE THREAD

**Issue by stephanflemming** [galaxyproject/galaxy#9365]
Two DOI links are displayed for each citation.

![Screenshot from 2020-02-12 14-13-52](https://user-images.githubusercontent.com/5413255/74338519-a8304d80-4da2-11ea-969a-920a57caf7dc.png)

ping @OlegZharkov

**Comment by OlegZharkov** [comment]
That should be easy to fix. Which one would you like to keep? ```[doi:number]``` or ```[Link]```?

**Comment by dannon** [comment]
I haven't looked at this code in a while, but I think in some cases these might be different links, and we can just drop the [link] in the case of doiUrl being used again.  So, something like https://gist.github.com/3ce563158af7dfee0106c555d01044a3

**Comment by OlegZharkov** [comment]
@dannon I was thinking just to
```const url = fields.url``` ~~|| doiUrl;~~
But I wasn't sure which field to keep, thanks. Will you commit your diff?

**Comment by dannon** [comment]
@OlegZharkov yeah, that'd work too -- I was just simplifying; seemed silly to have an extra reference for the single attribute handle.  And, sure, I can open a PR of that if you want.
