### ISSUE TITLE
Special characters in a citation

### ISSUE THREAD

**Issue by stephanflemming** [galaxyproject/galaxy#9369]
Special characters are not displayed properly. 

See https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/sina/sina/ for example.

`Jörg Peplies, Frank Oliver Glöckner`

is displayed as 

`Peplies, JÃ¶rg and GlÃ¶ckner, Frank Oliver`

ping @OlegZharkov

**Comment by OlegZharkov** [comment]
Looks like backend problem https://usegalaxy.eu/api/tools/toolshed.g2.bx.psu.edu/repos/iuc/sina/sina/1.5.0+galaxy1/citations returns  ```'\\u00c3\\u00b6'``` which is UTF-8 encoded version of ```ö``` as hex representation (0xc3b6) .  I guess, can be possibly fixed on frontend with something like:
```
str = "\\u00c3\\u00b6".replaceAll("\\u00","")
b = {Library}.fromHexToBytearray(str)
b.decode('UTF-8')
```
But I guess, that would be quite hackish. We need to fix backend API
