### ISSUE TITLE
Custom datatypes disappear after restart (19.09)

### ISSUE THREAD

**Issue by RJMW** [galaxyproject/galaxy#9370]
Custom datatypes installed via the toolshed disappear after restarting Galaxy.

We experienced this issue after upgrading Galaxy from 19.05 to 19.09.

**Comment by mvdbeek** [comment]
So you install a datatype from the toolshed, and then after a restart the datatype is not there anymore ? Is that for all custom datatypes or a specific one ?

**Comment by Tomnl** [comment]
The following custom datatypes are installed via the toolshed and then disappear after a restart

rdata_xcms_datatypes
rdata_camera_datatypes

I think it is the same for all custom datatypes installed from the toolshed though

**Comment by RJMW** [comment]
@lecorguille - shall we create a PR to get all xcms and camera datatypes into galaxy core?

**Comment by lecorguille** [comment]
Strange, we didn't have this issue.
@RJMW Really old request https://github.com/workflow4metabolomics/tools-metabolomics/issues/56

I just never put that on top of my TODO list.
Do you want to take that in charge @RJMW ?

**Comment by erikking** [comment]
I have similar issue with 20.01

please find detail in 
[https://github.com/galaxyproject/galaxy/issues/9536](url)

**Comment by dannon** [comment]
I think this is likely fixed with https://github.com/galaxyproject/galaxy/pull/9364/files; please let us know if you still encounter the problem after upgrading to that commit.
