### ISSUE TITLE
Data Tables v20.01 new location and visibility

### ISSUE THREAD

**Issue by code4dna** [galaxyproject/galaxy#9381]
I have v20.01 from Fri Feb 14 installed. The 'Data Tables' section in the Admin section do not list the data tables from config/tool_data_table_conf.xml. The data tables list does show up in the 'Local Data' section but only after at least one Data Manager is installed. If the Data Manager is uninstalled, the data tables in the 'Local Data' disappear again.

**Comment by code4dna** [comment]
This has been fixed with commit 80cf8acc[](https://github.com/galaxyproject/galaxy/commit/80cf8acceed947b98c2c505af092c7730486f5cf) on Feb 25. Works great.

**Comment by dannon** [comment]
@code4dna Thanks for following up on this; I missed that there was actually an issue open when I fixed it, sorry!
