### ISSUE TITLE
Extract Genomic DNA not recognizing mm9 

### ISSUE THREAD

**Issue by rtrumbly** [galaxyproject/galaxy#9396]
Trying to run Extract Genomic DNA on bed file with mm9 as genome. The tool says no options available for locally cached reference genome. when I edit the file to hg19 genome, it is recognized, but not for mm9 which is the correct genome. I have attached a screenshot of the problem. Here is a screen shot of the problem.
![Extract Genome DNA bug](https://user-images.githubusercontent.com/10078772/74846551-a1538e80-52fe-11ea-83ec-ff58c6506027.PNG)

**Comment by mvdbeek** [comment]
That means there is no index installed for mm9. I would suggest contacting the administrator of the Galaxy instance you are using. If that is not an option you can upload a fasta file for the mm9 genome and change "Choose the source for the reference genome" to history and select your fasta file with the genome sequence.

**Comment by jennaj** [comment]
Hello @rtrumbly 

If you are working at Galaxy Main https://usegalaxy.org, please use **bedtools GetFastaBed**  instead. It performs the same basic function plus has more options. You will find mm9 and many other genomes indexed.

**Comment by rtrumbly** [comment]
Jennifer,

Thanks for your help, that solves my problem.

Bob Trumbly
