### ISSUE TITLE
Feature Request: Copy workflow step incl. set parameters

### ISSUE THREAD

**Issue by scholtalbers** [galaxyproject/galaxy#940]
Currently its only possible to duplicate a workflow step by clicking on the same tool from the tool list and re-enter all needed parameters. It would be really helpful to just be able to duplicate a tool/workflow step by for example, double click or pressing some button.

**Comment by rylanshearn** [comment]
This would save me a lot of time, and probably everyone else that uses workflows in galaxy

**Comment by mvdbeek** [comment]
I agree, this would be nice.

**Comment by hexylena** [comment]
:+1:

**Comment by hexylena** [comment]
:+1: voting for this again as it is still an annoyance.

**Comment by hexylena** [comment]
FINALLY!!!! #5087 will solve this. Thanks @anatskiy, you rock!
