### ISSUE TITLE
output files can't be collected. 

### ISSUE THREAD

**Issue by jianlianggao** [galaxyproject/galaxy#9420]
Dear all,

I used a dockerized tool on Galaxy (launched by `sh run.sh`). The tool ran ok because I mounted `/opt/galaxy_data` and I could see output files in the dir. But my Galaxy instance returned error with collecting the files. 
My output in my tool xml is configured as
```
<outputs>
   <data name="output3" file="/opt/galaxy_data/data_wide_Symb.csv" label="data.wide_Symb.csv"/>
</outputs>
```
My code is R code, the "error" message just printed R message as I ran the docker locally. Those messages were normally display not real errors. Can anyone please help? Thank you very much.

Best regards,
Jianliang

**Comment by mvdbeek** [comment]
`file` is not a valid attribute and will be ignored.
Please have a look at the output documentation and the allowed attributes in the data tag here: https://docs.galaxyproject.org/en/latest/dev/schema.html#id65
I would also suggest working through the planemo tutorial at https://planemo.readthedocs.io/en/latest/writing_standalone.html

**Comment by jianlianggao** [comment]
Hi Marius, @mvdbeek 

Thank you very much.
I changed to 
```
<data name="data_long" format="csv" from_work_dir="data_long.csv" label="data_long.csv"/>
```
still failed.
What happened?

Best regards,
Jianliang

**Comment by mvdbeek** [comment]
Can you create a post with the Galaxy logs for the tool execution and the full tool xml at https://help.galaxyproject.org/ ?

**Comment by jianlianggao** [comment]
Thank you very much. I posted at https://help.galaxyproject.org/t/jobs-outputs-not-collected/3044
