### ISSUE TITLE
reserved variable for tool current working directory

### ISSUE THREAD

**Issue by sunyi000** [galaxyproject/galaxy#9422]
is there a reserved variable for the current tool working directory, which is similar to $__tool_directory__ ?
it will be useful to have it.

thanks

**Comment by mvdbeek** [comment]
You can use the standard `$PWD` variable. If referenced in the command section don't forget to escape it like so `\$PWD`.

**Comment by bgruening** [comment]
@mvdbeek I think this issue was to not use $PWD but a variable similar to `$__tool_directory__`. From looking at IUC, how many times $pwd was used, I think it makes sense.

**Comment by mvdbeek** [comment]
We shouldn't re-invent the wheel and introduce more Galaxy-isms, I don't think it is a good idea. I mean, if you want to do it, the implementation is 
```
diff --git a/lib/galaxy/tools/evaluation.py b/lib/galaxy/tools/evaluation.py
index 10aab1d624..1c0ddedbca 100644
--- a/lib/galaxy/tools/evaluation.py
+++ b/lib/galaxy/tools/evaluation.py
@@ -375,6 +375,7 @@ class ToolEvaluator(object):
         param_dict['__tool_directory__'] = self.compute_environment.tool_directory()
         param_dict['__get_data_table_entry__'] = get_data_table_entry
         param_dict['__local_working_directory__'] = self.local_working_directory
+        param_dict['__tool_working_directory__'] = os.path.join(self.local_working_directory, working)
         # We add access to app here, this allows access to app.config, etc
         param_dict['__app__'] = RawObjectWrapper(self.app)
         # More convienent access to app.config.new_file_path; we don't need to
```
but we'd need to update this for staging environments and that just looks unnecessarily complex.
