### ISSUE TITLE
Default value for build_sites_config_file not respected

### ISSUE THREAD

**Issue by blankenberg** [galaxyproject/galaxy#9426]
Need to uncomment the `build_sites_config_file: config/build_sites.yml.sample` for the defaults to be loaded.

```
  # File that defines the builds (dbkeys) available at sites used by
  # display applications and the URL to those sites.
  #build_sites_config_file: config/build_sites.yml.sample
```

**Comment by mvdbeek** [comment]
that should have been fixed in #9297 , do you have those commits?

**Comment by jdavcs** [comment]
Does it appear under `config/config/` instead?

**Comment by jdavcs** [comment]
Is the default supposed to be `config/build_sites.yml.sample`? If so, the problem is that by default the value is `config/build_sites.yml` (no `.sample` suffix).  I assume the latter (no suffix) is correct?

**Comment by blankenberg** [comment]
> that should have been fixed in #9297 , do you have those commits?

Was on dev 6622ad1acb91866febb3d2f229de7cfb8af3a9f6. 

It should use the `.yml` if exists, otherwise default back to using the `.sample`

**Comment by jdavcs** [comment]
@blankenberg - and I don't think it does it by default for all config values. Which would explain the error. Next commit should fix it , I think.

**Comment by jdavcs** [comment]
This should be fixed now, so I'm closing the issue. @blankenberg please reopen if it still doesn't work as expected.
