### ISSUE TITLE
Importing library dataset collection to history does not restrict history items to the collection

### ISSUE THREAD

**Issue by gregvonkuster** [galaxyproject/galaxy#9435]
Running Galaxy 20.01, importing a list of library datasets into a collection in the history successfully creates the collection, but all history items are also displayed outside of the collection.  Checking or unchecking the "Hide original elements?" checkbox makes no difference.

**Comment by gregvonkuster** [comment]
Bump.  Wondering if anyone else is seeing this.  If not, perhaps I'm doing something wrong?  This is really a problem with larger dataset collections like > 10 elements.

**Comment by gregvonkuster** [comment]
@mvdbeek Can you point me to a starting point in the Galaxy code for this?  I'll see if I can figure out a fix.  This is really hindering our progress since our bacterial analysis requires hundreds of data library datasets to be imported into our histories, and browser limits are continually hit.  The Galaxy framework code has changed so much since I was involved with data libraries that I can no longer easily find it.  :(

**Comment by mvdbeek** [comment]
My usual process would be to check for some of the unique text and go from there.
Searching for `Create History Collection from Datasets` brings me to https://github.com/mvdbeek/galaxy/blob/8382f5d438a898ed7eb6bd8b41fb0dd47f6cf5cf/client/galaxy/scripts/mvc/library/library-foldertoolbar-view.js#L1276

which via via seems to go to https://github.com/mvdbeek/galaxy/blob/8382f5d438a898ed7eb6bd8b41fb0dd47f6cf5cf/client/galaxy/scripts/mvc/library/library-foldertoolbar-view.js#L1400

The important parameter seems to be `hide_source_items` so I traced that to https://github.com/mvdbeek/galaxy/blob/2b62d22f308404135befad739da8911e8bb1366c/lib/galaxy/managers/collections.py#L433 for HDAs, and for LDDAs this is just missing.

So there you go, will open a PR in a minute.

**Comment by gregvonkuster** [comment]
Thanks @mvdbeek you are marvelous! :)

**Comment by gregvonkuster** [comment]
Thanks everyone - this is very much appreciated!  :)
