### ISSUE TITLE
Can't add or remove users to quota once it is created v20.01

### ISSUE THREAD

**Issue by code4dna** [galaxyproject/galaxy#9457]
Not sure if this is by design but parameters for a saved quota can be changed such as rename, amount, type and 'unset as default' but there is no option to change users or groups.

**Comment by mvdbeek** [comment]
That works fine for me, are you sure you're using the right menu for that ?
<img width="346" alt="Screenshot 2020-02-28 at 11 34 14" src="https://user-images.githubusercontent.com/6804901/75541480-592f1d00-5a1e-11ea-8646-dd58f6535925.png">

**Comment by code4dna** [comment]
I'm accessing Admin -> Quotas
I have 20.01 commit aa0b8833ee  Feb 26

![image](https://user-images.githubusercontent.com/17836321/75569209-503c4c80-5a1a-11ea-83f4-e39ff4977321.png)

**Comment by dannon** [comment]
The issue is that that's set as a default quota, meaning (in this case) all registered users will get that unless something else is assigned.  So there's no way to manage the groups for it.  If you want to assign that to particular users instead of as a default, do 'unset as default'.
