### ISSUE TITLE
Trackster navigation menu no longer visible 

### ISSUE THREAD

**Issue by nturaga** [galaxyproject/galaxy#946]
The trackster navigation menu, which includes dropdown options for chromosome number etc are no longer visible.  The two screen shots of bed files with hg19 are shown as example below. This is from the galaxy main instance.

<img width="1425" alt="screen shot 2015-10-19 at 5 27 05 pm" src="https://cloud.githubusercontent.com/assets/2746443/10591895/c4248af8-7686-11e5-9689-2375717826ac.png">

<img width="1424" alt="screen shot 2015-10-19 at 5 25 00 pm" src="https://cloud.githubusercontent.com/assets/2746443/10591897/c6707d58-7686-11e5-9552-09d0e8b50db4.png">

**Comment by martenson** [comment]
Maybe somebody who works with trackster sees this clearly but could you please specify what is not visible and where? E.g. with screenshot where it is visible? Thanks.

**Comment by msauria** [comment]
The gray bar immediately under the blue bar at the top of the window should have a navigation panel, including the chromosome select dropdown, coordinate span, and zoom in/out icons. The break occurred in commit 53b84fd17f662ba595d0a72ca79a24d5792ec0f8.

**Comment by martenson** [comment]
ping @guerler

**Comment by guerler** [comment]
Should be fixed in #953.

**Comment by nturaga** [comment]
Should this issue be closed if its fixed?
