### ISSUE TITLE
Tighten up datatypes

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#948]
```
# STOCKHOLM 1.0
#=GF ID   MADE1
#=GF AC   DF0000629.2
#=GF DE   MADE1 (MAriner Derived Element 1), a TcMar-Mariner DNA transposon
#=GF AU   Finn RD, Hubley R, Jones T, Jurka J, Smit A, Wheeler T
```

was recently detected as `bed` which is just _so_ wrong. Given how recently #864 occurred, I'm feeling that it is definitely time tests were added for datatypes and sniffing. Yes, I'm volunteering to do that, but will gladly accept any help that's offered.

**Comment by nsoranzo** [comment]
:+1:

**Comment by hexylena** [comment]
Merging into #1419
