### ISSUE TITLE
cookie_path needed in config and shouldn't be

### ISSUE THREAD

**Issue by code4dna** [galaxyproject/galaxy#9495]
Hi, we have installed the 20.01 release and all is great except we cannot switch histories on most computers. The history switch button does rearrange the histories but when clicking the Galaxy logo or the Analyze Data button, the history reverts back to the previous working history. This error occurs on most of our computers but not all. I've tried removing galaxy from the browser cache but that didn't help.
The following error message may not be related to the issue since it occurs whenever Latin is on the browser's languages list and the message is displayed when using computers where history switching does work: 

`galaxy.web.framework.webapp DEBUG 2020-03-05 11:19:52,001 [p:44458,w:1,m:0] [uWSGIWorker1Core2] Error parsing locale 'la;q=0.4'. <class 'babel.core.UnknownLocaleError'>: unknown locale 'la'`

On a computer where history switching does not work, I am able to switch histories at usegalaxy.org

History switching is working properly on our other Galaxy which is v19.05 even on the computers where it is not working on version 20.01

**Comment by dannon** [comment]
@code4dna The `la` locale and latin language settings are a red herring I think -- that debug statement is wrapped in a try/catch and when a perceived invalid language pops up Galaxy just logs the error and moves on with the rest of the available locales.

To be clear, you mean the 'switch to' button in the multi-history view seen here, right?
![image](https://user-images.githubusercontent.com/155398/76113548-58643100-5fb2-11ea-9499-36f62cd5e5d1.png)

On one of these machines where this fails, can you open the developer tools in your browser and verify there isn't an error in the request or the console, as seen below, here:

![image](https://user-images.githubusercontent.com/155398/76113706-9eb99000-5fb2-11ea-916c-079f561be3f8.png)

Barring that, is there anything else in teh log at all around the time of the request to `set_as_current` that'd be an error?

**Comment by code4dna** [comment]
Thanks for the advice. I was able to see in the browser developer tool that there were two network requests, one to galaxy and one to /galaxy/
The problem was the trailing forward slash due to having a forward slash after galaxy in the ProxyPass line as well as having one after the port number in the rewrite rule in our httpd conf file. It works now using the following:
```
    ProxyPass /galaxy            uwsgi://localhost:4003/
    RewriteRule ^/galaxy/$ /galaxy [R,L]
```
Thanks again,

**Comment by dannon** [comment]
@code4dna Ah-ha, makes sense, glad you figured it out!  Your original configuration -- was that a reference you saw somewhere that we should update to include the rewrite rule that we can improve?

(please do let me know if we can improve the docs here, but I'm going to go ahead and close this issue out in this repo)

**Comment by code4dna** [comment]
We had the trailing forward slash `ProxyPass /galaxy/` in our v15.07 installation and it was working. We probably referred to our v15.07 httpd config and applied the trailing forward slash to our new installation. Couldn't tell if it originated from any Galaxy documentation since we haven't updated galaxy since 2015 which was installed by someone else.

**Comment by code4dna** [comment]
@dannon Well, I thought I had this figured out but was working on a computer where history switching was working. I've tried different httpd configs but when history switching works (which I got it to work by allowing trailing forward slashes), job submitting does not work. Using a different httpd configuration, history switching does not work but job submitting works.
Here is our httpd.conf for our Galaxy v19.05 in which history switching and submitting jobs works:
```
    ProxyPass /galaxy1905            uwsgi://localhost:4002
    ProxyPassReverse /galaxy1905     uwsgi://localhost:4002
    RewriteRule ^/galaxy1905/$ /galaxy1905 [R,L]
```

However, the same config for our Galaxy v20.01 doesn't work. History switching does not work but job submitting does work. I also tried with a slash after just the port 4003/
```
    ProxyPass /galaxy2001           uwsgi://localhost:4003
    ProxyPassReverse /galaxy2001    uwsgi://localhost:4003
    RewriteRule ^/galaxy2001/$ /galaxy2001 [R,L]
```

Earlier when I had history switching working, I was using the trailing forward slash and using the rewrite rules below to keep the trailing forward slash and history switching was working but job submitting was not working. When I submitted a job, it just showed the welcome.html page with no side panels.
```
    ProxyPass /galaxy2001/           uwsgi://localhost:4003/
    ProxyPassReverse /galaxy2001/    uwsgi://localhost:4003/
    RewriteRule ^/galaxy2001//$ /galaxy2001/ [R]
    RewriteRule ^/galaxy2001$ /galaxy2001/ [R,L]
```
The browser debugger that showed galaxy and /galaxy/ requests was just showing that /galaxy/ requests were rerouted to galaxy

**Comment by code4dna** [comment]
@dannon  Here are the log files from one of our Galaxies at v19.05 where history switching works and another of our Galaxies at v20.01 where history switching does not work. I noticed that the same history id is in both logs: set_as_current?id=96228697dff25cef not sure if that is expected. Notice in the last four lines after returning to Galaxy home for v20.01, the history id gets reverted back to 175d328a1016fbc3


==> GALAXY 19.05 (history switching works)
==> CLICK SWITCH BUTTON:
```
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:40:26 -0500] "GET /galaxy19.05/history/set_as_current?id=96228697dff25cef HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy19.05/history/view_multiple" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 28492|app: 0|req: 984/1306] 172.11.11.11 (myuserid) {78 vars in 2184 bytes} [Thu Mar 26 16:40:26 2020] GET /galaxy19.05/history/set_as_current?id=96228697dff25cef => generated 586 bytes in 91 msecs (HTTP/1.1 200) 5 headers in 171 bytes (1 switches on core 2)
```
==> GALAXY 19.05 (history switching works)
==> RETURNED TO GALAXY HOME:
```
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:40:51 -0500] "GET /galaxy19.05/ HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy19.05/history/view_multiple" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 28492|app: 0|req: 985/1307] 172.11.11.11 (myuserid) {78 vars in 2055 bytes} [Thu Mar 26 16:40:51 2020] GET /galaxy19.05 => generated 507001 bytes in 88 msecs (HTTP/1.1 200) 2 headers in 88 bytes (1 switches on core 3)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:40:52 -0500] "GET /galaxy19.05/api/webhooks HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy19.05" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 28492|app: 0|req: 986/1308] 172.11.11.11 (myuserid) {78 vars in 2073 bytes} [Thu Mar 26 16:40:52 2020] GET /galaxy19.05/api/webhooks => generated 2 bytes in 15 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 1)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:40:52 -0500] "GET /galaxy19.05/api/webhooks HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy19.05" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 28492|app: 0|req: 987/1309] 172.11.11.11 (myuserid) {78 vars in 2073 bytes} [Thu Mar 26 16:40:52 2020] GET /galaxy19.05/api/webhooks => generated 2 bytes in 15 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 0)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:40:52 -0500] "GET /galaxy19.05/api/datatypes?extension_only=False HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy19.05" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 28492|app: 0|req: 990/1310] 172.11.11.11 (myuserid) {80 vars in 2108 bytes} [Thu Mar 26 16:40:52 2020] GET /galaxy19.05/api/datatypes?extension_only=False => generated 49966 bytes in 26 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 2)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:40:52 -0500] "GET /galaxy19.05/api/genomes HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy19.05" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 28492|app: 0|req: 990/1311] 172.11.11.11 (myuserid) {80 vars in 2057 bytes} [Thu Mar 26 16:40:52 2020] GET /galaxy19.05/api/genomes => generated 55436 bytes in 35 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 3)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:40:52 -0500] "GET /galaxy19.05/history/current_history_json HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy19.05" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 28492|app: 0|req: 990/1312] 172.11.11.11 (myuserid) {78 vars in 2153 bytes} [Thu Mar 26 16:40:52 2020] GET /galaxy19.05/history/current_history_json => generated 586 bytes in 58 msecs (HTTP/1.1 200) 5 headers in 171 bytes (1 switches on core 1)
[pid: 28492|app: -1|req: -1/1313] 172.11.11.11 (myuserid) {76 vars in 2307 bytes} [Thu Mar 26 16:40:52 2020] GET /galaxy19.05/static/scripts/bundled/assets/68f6ead9b879fa12c09aa5ea225584f0.png => generated 87 bytes in 0 msecs via offload() (HTTP/1.1 200) 3 headers in 110 bytes (0 switches on core 0)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:40:52 -0500] "GET /galaxy19.05/welcome HTTP/1.1" 302 313 "https://mygalaxy.tamu.edu/galaxy19.05" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 28492|app: 0|req: 991/1314] 172.11.11.11 (myuserid) {78 vars in 2072 bytes} [Thu Mar 26 16:40:52 2020] GET /galaxy19.05/welcome => generated 313 bytes in 13 msecs (HTTP/1.1 302) 4 headers in 189 bytes (1 switches on core 2)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:40:52 -0500] "GET /galaxy19.05/api/users/96228697dff25cef HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy19.05" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 28492|app: 0|req: 993/1315] 172.11.11.11 (myuserid) {78 vars in 2143 bytes} [Thu Mar 26 16:40:52 2020] GET /galaxy19.05/api/users/96228697dff25cef => generated 287 bytes in 85 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 3)

172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:40:52 -0500] "GET /galaxy19.05/api/histories/96228697dff25cef/contents?limit=500&offset=0&order=hid&v=dev&q=deleted&q=purged&q=visible&qv=False&qv=False&qv=True HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy19.05" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 28492|app: 0|req: 993/1316] 172.11.11.11 (myuserid) {78 vars in 2387 bytes} [Thu Mar 26 16:40:52 2020] GET /galaxy19.05/api/histories/96228697dff25cef/contents?limit=500&offset=0&order=hid&v=dev&q=deleted&q=purged&q=visible&qv=False&qv=False&qv=True => generated 3540 bytes in 90 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 1)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:40:52 -0500] "GET /galaxy19.05/api/histories/96228697dff25cef?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy19.05" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 28492|app: 0|req: 994/1317] 172.11.11.11 (myuserid) {78 vars in 2280 bytes} [Thu Mar 26 16:40:52 2020] GET /galaxy19.05/api/histories/96228697dff25cef?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter => generated 117 bytes in 59 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 0)
```

============================================================================

==> GALAXY 20.01 (history switching does not work)
==> CLICK SWITCH BUTTON:
```
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:32 -0500] "GET /galaxy20.01/history/set_as_current?id=96228697dff25cef HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy20.01/history/view_multiple" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 8891|app: 0|req: 57/74] 172.11.11.11 (myuserid) {78 vars in 2189 bytes} [Thu Mar 26 16:44:32 2020] GET /galaxy20.01/history/set_as_current?id=96228697dff25cef => generated 582 bytes in 80 msecs (HTTP/1.1 200) 5 headers in 171 bytes (1 switches on core 1)
```
==> GALAXY 20.01 (history switching does not work)
==> RETURNED TO GALAXY HOME:
```
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:50 -0500] "GET /galaxy20.01/ HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy20.01/history/view_multiple" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 8891|app: 0|req: 58/75] 172.11.11.11 (myuserid) {78 vars in 1964 bytes} [Thu Mar 26 16:44:50 2020] GET /galaxy20.01 => generated 104284 bytes in 83 msecs (HTTP/1.1 200) 8 headers in 413 bytes (1 switches on core 3)
[pid: 8891|app: -1|req: -1/76] 172.11.11.11 (myuserid) {78 vars in 2226 bytes} [Thu Mar 26 16:44:50 2020] GET /galaxy20.01/static/scripts/bundled/analysis.bundled.js?v=1585257457 => generated 0 bytes in 0 msecs (HTTP/1.1 304) 0 headers in 29 bytes (0 switches on core 2)
[pid: 8891|app: -1|req: -1/77] 172.11.11.11 (myuserid) {78 vars in 2266 bytes} [Thu Mar 26 16:44:50 2020] GET /galaxy20.01/static/style/jquery-ui/smoothness/jquery-ui.css?v=1585257457 => generated 0 bytes in 0 msecs (HTTP/1.1 304) 0 headers in 29 bytes (0 switches on core 0)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:50 -0500] "GET /galaxy20.01/api/webhooks HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy20.01" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 8891|app: 0|req: 59/78] 172.11.11.11 (myuserid) {78 vars in 2078 bytes} [Thu Mar 26 16:44:50 2020] GET /galaxy20.01/api/webhooks => generated 2 bytes in 17 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 1)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:50 -0500] "GET /galaxy20.01/api/configuration HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy20.01" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:50 -0500] "GET /galaxy20.01/api/users/current HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy20.01" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 8891|app: 0|req: 61/79] 172.11.11.11 (myuserid) {76 vars in 2051 bytes} [Thu Mar 26 16:44:50 2020] GET /galaxy20.01/api/configuration => generated 2324 bytes in 38 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 2)
[pid: 8891|app: 0|req: 61/80] 172.11.11.11 (myuserid) {76 vars in 2051 bytes} [Thu Mar 26 16:44:50 2020] GET /galaxy20.01/api/users/current => generated 271 bytes in 44 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 3)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:51 -0500] "GET /galaxy20.01/api/webhooks HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy20.01" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 8891|app: 0|req: 62/81] 172.11.11.11 (myuserid) {78 vars in 2078 bytes} [Thu Mar 26 16:44:51 2020] GET /galaxy20.01/api/webhooks => generated 2 bytes in 14 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 0)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:51 -0500] "GET /galaxy20.01/api/datatypes?extension_only=False HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy20.01" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 8891|app: 0|req: 65/82] 172.11.11.11 (myuserid) {80 vars in 2113 bytes} [Thu Mar 26 16:44:51 2020] GET /galaxy20.01/api/datatypes?extension_only=False => generated 52722 bytes in 69 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 1)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:51 -0500] "GET /galaxy20.01/welcome HTTP/1.1" 302 315 "https://mygalaxy.tamu.edu/galaxy20.01" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 8891|app: 0|req: 66/83] 172.11.11.11 (myuserid) {78 vars in 2077 bytes} [Thu Mar 26 16:44:51 2020] GET /galaxy20.01/welcome => generated 315 bytes in 37 msecs (HTTP/1.1 302) 4 headers in 190 bytes (1 switches on core 0)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:51 -0500] "GET /galaxy20.01/api/genomes HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy20.01" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 8891|app: 0|req: 66/84] 172.11.11.11 (myuserid) {80 vars in 2062 bytes} [Thu Mar 26 16:44:51 2020] GET /galaxy20.01/api/genomes => generated 55436 bytes in 102 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 2)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:51 -0500] "GET /galaxy20.01/history/current_history_json HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy20.01" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 8891|app: 0|req: 66/85] 172.11.11.11 (myuserid) {78 vars in 2158 bytes} [Thu Mar 26 16:44:51 2020] GET /galaxy20.01/history/current_history_json => generated 582 bytes in 142 msecs (HTTP/1.1 200) 5 headers in 171 bytes (1 switches on core 3)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:51 -0500] "GET /galaxy20.01/api/users/96228697dff25cef HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy20.01" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 8891|app: 0|req: 68/86] 172.11.11.11 (myuserid) {78 vars in 2148 bytes} [Thu Mar 26 16:44:51 2020] GET /galaxy20.01/api/users/96228697dff25cef => generated 271 bytes in 45 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 1)

172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:51 -0500] "GET /galaxy20.01/api/histories/175d328a1016fbc3/contents?limit=500&offset=0&order=hid&v=dev&q=deleted&q=purged&q=visible&qv=False&qv=False&qv=True HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy20.01" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 8891|app: 0|req: 68/87] 172.11.11.11 (myuserid) {78 vars in 2392 bytes} [Thu Mar 26 16:44:51 2020] GET /galaxy20.01/api/histories/175d328a1016fbc3/contents?limit=500&offset=0&order=hid&v=dev&q=deleted&q=purged&q=visible&qv=False&qv=False&qv=True => generated 2 bytes in 67 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 0)
172.11.11.11 - myuserid@tamu.edu [26/Mar/2020:16:44:51 -0500] "GET /galaxy20.01/api/histories/175d328a1016fbc3?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter HTTP/1.1" 200 - "https://mygalaxy.tamu.edu/galaxy20.01" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
[pid: 8891|app: 0|req: 69/88] 172.11.11.11 (myuserid) {78 vars in 2285 bytes} [Thu Mar 26 16:44:51 2020] GET /galaxy20.01/api/histories/175d328a1016fbc3?keys=size%2Cnon_ready_jobs%2Ccontents_active%2Chid_counter => generated 112 bytes in 55 msecs (HTTP/1.1 200) 3 headers in 139 bytes (1 switches on core 2)

```

**Comment by dannon** [comment]
@code4dna Thanks for the traceback; reopening the issue so I don't forget to come back and go through it when I have a sec.

**Comment by code4dna** [comment]
If I click User -> Histories and select a different history, the new history shows up in the right panel but if I click Galaxy home or Analyze Data, the history gets reverted back to the original history which is the same behavior as if I used the 'View all histories' approach. But I am able to switch histories if I click User -> Histories then select a different history and immediately run a tool without clicking Galaxy home or Analyze Data.

**Comment by code4dna** [comment]
This looks like a browser version issue as it works on older Firefox browser versions but not newer versions and not on the latest Chrome.
I have a laptop with Fedora 29 that has an older version of Firefox and all works well but the latest version of Chrome on the same laptop does not work:
```
Firefox quantum 68.0.0esr (64-bit) fedora 1.0
Chrome Version 83.0.4103.61 64-bit
```

My office desktop CentOS 7 has an older version of Firefox and all works well:
`Firefox quantum 60.4.0esr (64-bit)
`

My home office desktop Fedora 31 has newer versions of Firefox and Chrome and history switching does not work in either:
```
Firefox 72.0.2 64-bit fedora 1.0
Chrome Version 80.0.3987.122 (Official Build) (64-bit)
```

**Comment by code4dna** [comment]
@dannon What could be the difference between our server and the usegalaxy.org server that might be causing this browser version issue since all works well for us at usegalaxy.org? We have the following:
CentOS Linux release 7.7.1908 (Core)
httpd-2.4.6-90.el7.centos.x86_64
httpd24-httpd-2.4.34-15.el7.x86_64

**Comment by code4dna** [comment]
I see that usegalaxy.org uses nginx to proxy requests so this may be an issue with proxying with apache

**Comment by code4dna** [comment]
@dannon The free version of nginx does not support our CAS authentication so we are stuck with Apache.
I am sure it is an issue with new features introduced to the newer versions of web browsers. I installed Firefox Extended Support Release 68.9.0esr (64-bit) and am able to switch histories on a computer where the newer versions of Firefox versions 70+ are not working with our 20.01 install.

**Comment by dannon** [comment]
@code4dna Sorry for the lack of movement on this, I am just perplexed.  Interesting that you tracked it down to newer firefox browser issues.  I'm assuming you would have mentioned it, but are there any warnings related to the new on-by-default privacy features or tracking protection?  (Long shot, just the only thing that comes to mind related to newer FF versions).

And, to try to isolate what's happening here, can you bypass Apache and access the 20.01 galaxy server directly in the browser?

**Comment by code4dna** [comment]
@dannon I didn't notice any warnings. I tried disabling content blocking, tracking, cryptominers and fingerprinters but still can't switch histories.
In a separate test, I bypassed Apache and loaded Galaxy 20.01 using localhost:8080 and history switching works in both an older Firefox browser version, 68.4.1esr and a newer Firefox version, 77.0 with all the privacy features set at defaults.

**Comment by dannon** [comment]
@code4dna Okay, so it is definitely something about the Apache configuration that's breaking things.   @natefoo Do you have any idea here?

**Comment by code4dna** [comment]
I installed a new instance of 19.05 and history switching is not working properly with the newer browsers. It is on the same server as our other 19.05 where history switching is still working on newer browsers. I guess it's something on our end and we'll have to live with it if we can't figure it out. Thanks,

**Comment by code4dna** [comment]
got it working (whew!). v20.05 works after adding the following to galaxy.yml in the `galaxy:` section
`  cookie_path: '/mygalaxy'`

documentation for v20.05 says cookie_path is automatically set and setting it is not necessary but in our case it is needed

**Comment by dannon** [comment]
@code4dna Oh wow, glad you sorted that out!  We should probably follow up to understand why cookie_path wasn't automatically set in your case, but I'm really glad you got past this.

**Comment by jmchilton** [comment]
Keeping this issue open to address that cookie_path issue, but I'll rename it. @code4dna do you happen to have any clues why cookie_path might be needed in your setup? It has been a while since I've heard of anyone needing to set it so I think it should work without being set in proxy prefix environments.

**Comment by code4dna** [comment]
I ran a test using two of our galaxies running on the same server and set both without cookie_path. I cleared the cookies from my browser and started the first galaxy and history switching was working. I then started the second Galaxy and history switching did not work for the second galaxy but continued to work for the first Galaxy. I then cleared the cookies from my browser and history switching stopped working for the first Galaxy.

**Comment by code4dna** [comment]
It may be a combination of our setup that uses Apache and CAS user authentication

**Comment by code4dna** [comment]
we now have 22.05 installed and this is no longer an issue. we don't need to set cookie_path

**Comment by dannon** [comment]
Great, glad this has been resolved!
