### ISSUE TITLE
sh run.sh not opening http://localhost:8080

### ISSUE THREAD

**Issue by gm9756** [galaxyproject/galaxy#9534]
I am trying to start up Galaxy release version 20.01. When I run the command sh run.sh I get a long message that ends with the following 3 lines:

```
Starting server in PID 30647.
serving on http://localhost:8080
galaxy.model.database_heartbeat DEBUG 2020-03-18 10:21:36,986 [p:30647,w:1,m:0] [database_heartbeart_main.web.1.thread] main.web.1 is config watcher
```
It will not allow me to open the local server.  I have tried adding conda to the PATH as suggested by the tutorial but it does not fix the issue.

**Comment by mvdbeek** [comment]
This looks correct as far as the startup goes. Please use https://help.galaxyproject.org/ for remaining questions.
