### ISSUE TITLE
tools and datatypes installed in toolshed disappear after restart in 20.01

### ISSUE THREAD

**Issue by erikking** [galaxyproject/galaxy#9536]
I tested the cases in three environments 

1. New installed Galaxy 19.05
no issue
2. Galaxy 20.01, upgraded from 19.05
tools installed in 19.05 and then upgrade to 20.01, no issue
3.  New installed Galaxy 20.01
tools and data type installed in 20.01, when everytime restart Galaxy, the tools disappear in tool panel, and data types do not work, need reinstall at least one tool and data type to make all other tools and data type work. 

tools:
xcms_fillpeaks
xcms_group
xcms_merge
xcms_plot_chromatogram
xcms_retcor
xcms_summary
xcms_xcmsset
etc.

datatype:
rdata_xcms_datatypes

**Comment by mvdbeek** [comment]
What commit of 20.01 are you using ? This should have been fixed by https://github.com/galaxyproject/galaxy/pull/9364/files

**Comment by erikking** [comment]
> What commit of 20.01 are you using ? This should have been fixed by https://github.com/galaxyproject/galaxy/pull/9364/files

Thanks very much, after updating to latest commit, it fix the issue.
