### ISSUE TITLE
Allow Tools with Custom/Graphical Javascript Interfaces

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#9542]
This feature follows in the footsteps of interactive tools and would making visualizations executable just like regular tools. The user interface of the visualization could be used to filter or select data and these tools could be integrated into workflows and reports, improve testing, versioning and reproducibility etc.

**Comment by dannon** [comment]
> Making visualizations executable would allow us to integrate them into Workflows and Reports, improve testing etc.

The plan for this right now is to integrate them as first class embedded items (think modernized page components) that we can integrate into workflow invocation reports (and more! -- imagine being able to just drop the live Galaxy component into https://covid19.galaxyproject.org/cheminformatics/ (see the little squiggly)), etc.

**Comment by guerler** [comment]
Live dropping visualization as JS-Objects is our priority. This issue suggests to add to it and by allowing visualizations to be run individually as regular tools with consistent 'tool.xml' and produce outputs i.e. it would be nice if all visualizations would be available as tools too, similar to interactive tools but without a separate docker image.

**Comment by bgruening** [comment]
Oh, I love where this is going! :100:
