### ISSUE TITLE
conda installation requested and failed... when loading galaxy local

### ISSUE THREAD

**Issue by laurentierney** [galaxyproject/galaxy#9564]
HI,

When I try to run galaxy local, I get the message "conda installation requested and failed".
 Error: did not recognise option 'Book/Galaxy/galaxy/database/dependencies/_conda', please try -h

I have gone into the galaxy.yml file and amended it as so:

 conda_prefix: <tool_dependency_dir>/_conda

tool_dependency_dir: dependencies

 conda_auto_init: true

I cannot understand what the issue is. Despite this, it allows me to open galaxy on the web and download tools but the tools do not work. 

any help would be much appreciated!!

**Comment by mvdbeek** [comment]
I see you also opened https://help.galaxyproject.org/t/conda-installation-requested-and-failed-local-galaxy/3236/2, which is the right place for usage questions, so I will close this.
