### ISSUE TITLE
Tool versions order

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/galaxy#9573]
<img width="1077" alt="Capture d’écran 2020-03-29 à 22 20 37" src="https://user-images.githubusercontent.com/11072022/77859776-92b89b00-720b-11ea-97f3-49d251984e74.png">

In usegalaxt.fr, I can't figure out why the version of camera_annotate `2.2.5` is the default version over the `2.2.6+camera1.42.0+galaxy1`?

Do you have an idea?

**Comment by nsoranzo** [comment]
That's because `2.2.6+camera1.42.0+galaxy1` is not a valid version string (too many local version identifiers):

```
In [1]: import packaging.version                                                

In [2]: packaging.version.parse('2.2.6+camera1.42.0+galaxy1')                   
Out[2]: <LegacyVersion('2.2.6+camera1.42.0+galaxy1')>
```

All LegacyVersion are  considered smaller than proper versions, see https://packaging.pypa.io/en/latest/version/

**Comment by lecorguille** [comment]
@nsoranzo Thanks for the tip
```
>>> p1 = packaging.version.parse('2.2.6+camera1.42.0-galaxy1')
>>> p2 = packaging.version.parse('2.2.6+camera1.42.0+galaxy1')
>>> p3 = packaging.version.parse('2.2.5')
>>> p1 > p2
True
>>> p2 > p3
False
>>> p1 > p3
True
```

I will use this form: `2.2.6+camera1.42.0-galaxy1`, it seems ok.

For the history, my issue is that at the beginning of the wrapper, we choose a wrong versionning nomenclature. So until the CAMERA version jump over 2.2.6, we are stuck with this ugly version number.

Or `2.2.6+camera1.42.0-galaxy2.2.6` ?
