### ISSUE TITLE
Create a collection of paired datasets: put DEFAULT_FILTERS into Galaxy config, add: dot12s: [".1.fastq", ".2.fastq"]

### ISSUE THREAD

**Issue by tshtatland** [galaxyproject/galaxy#9589]
Our users have *.1.fastq and *.2.fastq paired end reads. They typically use collections to analyze these data. We need to enable easier filter selection for creating collections.

The typical use case is a follows. The user goes to History tab, selects fastq files, goes to:
```
For all selected | Build list of dataset pairs
Choose filters
Choose from the following filters to change which unpaired reads are shown in the display:
Forward: _1, Reverse: _2
Forward: _R1, Reverse: _R2
Change to:
Forward: .1.fastq, Reverse: .2.fastq
(note the leading dot)
```
I suggest to control the defaults (`DEFAULT_FILTERS: "illumina"`) using a Galaxy config parameter. This would allow the admin to select the most commonly used extensions as defaults.  Also add to the list commonFilters this very commonly used pattern: `dot_fastqs: [".1.fastq", ".2.fastq"],`, see [`client/galaxy/scripts/mvc/collection/list-of-pairs-collection-creator.js`](https://github.com/galaxyproject/galaxy/blob/d7921ae4dda5388dfda1f346a6a3b5ca7436a9ee/client/galaxy/scripts/mvc/collection/list-of-pairs-collection-creator.js):
```
        /** map of common filter pairs by name */
        commonFilters: {
            illumina: ["_1", "_2"],
            Rs: ["_R1", "_R2"],
        },
        /** which commonFilter to use by default */
        DEFAULT_FILTERS: "illumina",

```

**Comment by bernt-matthias** [comment]
@tshtatland would you like to open a pull request, since you already found the place in the code?

**Comment by jmchilton** [comment]
https://github.com/galaxyproject/galaxy/pull/10212/commits/b628309c80d7d7188bd9d4dc40a0ebcae1d59908 is a good example I just did of how to get a simple config option from Galaxy's YAML to the frontend and work with it. That might make this easier.

**Comment by assuntad23** [comment]
completed as part of PR #10240

**Comment by lldelisle** [comment]
I think this is still interesting to have `COMMON_FILTERS` and potentially `commonFilters` as galaxy config parameter.
https://github.com/galaxyproject/galaxy/blob/d7921ae4dda5388dfda1f346a6a3b5ca7436a9ee/client/galaxy/scripts/mvc/collection/list-of-pairs-collection-creator.js#L288-L294

**Comment by bernt-matthias** [comment]
I think it would be best to open a new issue. Definition seems to be here: [client/src/components/Collections/PairedListCollectionCreator.vue](https://github.com/galaxyproject/galaxy/pull/10240/files#diff-13199dd1324083321db7619c97f987a249d1ab28f50e3cb5847aa6db914bd0c8)

**Comment by lldelisle** [comment]
Thanks, see #15937
