### ISSUE TITLE
Connected workflow parameters appear in subworkflow run menu / prevent wf submission

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#9594]
https://usegalaxy.org/u/aun1/w/download-and-sepe-illumina-covid-workflows is a subworkflow that runs 3 workflow. One of them has a workflow parameter connected to a text parameter. This parameter appears in the run workflow form (it shouldn't, it is properly connected). When trying to submit the workflow the API returns `{"err_msg": {"input|accession": "An accession is required"}, "err_code": 0, "err_data": {"3": {"input|accession": "An accession is required"}}}`

<img width="517" alt="Screenshot 2020-04-08 at 23 43 53" src="https://user-images.githubusercontent.com/6804901/78836714-f2c0f580-79f2-11ea-829f-8b79bd5b34fd.png">

**Comment by guerler** [comment]
Is this a recent issue?

**Comment by mvdbeek** [comment]
Not sure, it may have never worked.

**Comment by mvdbeek** [comment]
I mean, it's a new feature, so never is a relatively short time ;). I do have a new bug though for you, will open a new issue for that.

**Comment by mvdbeek** [comment]
Fixed in https://github.com/galaxyproject/galaxy/pull/9685
