### ISSUE TITLE
Setting welcome_url in galaxy.yml not working correctly

### ISSUE THREAD

**Issue by CicadaDennis** [galaxyproject/galaxy#9596]
I found this issue in 19.05, then updated to 20.01 and am still seeing this issue.
I am using the galaxy ansible role to set up Galaxy on a remote.
I am using root configuration.
I am trying to set the welcome page to a location that is not a subdirectory of the `{{ galaxy_root }}/server` directory.

I have tried absolute and relative paths and neither work. In any path that includes dots (eg: .. ) the dots are eliminated from the path that Galaxy tries to look for. In all of the cases below, the file at the welcome_url exists.

```
welcome_url: /home/trinity/galaxy/static/welcome.html
```

yields in the welcome panel:
404 Not Found
The resource could not be found.
No route for /home/trinity/galaxy/static/welcome.html

(But the absolute path: `/home/trinity/galaxy/static/welcome.html` does exist.)

```
welcome_url: ../static/welcome.html
```

yields in the welcome panel:
404 Not Found
The resource could not be found.
No route for /static/welcome.html

But if I put the welcome file into `{{ galaxy_root }}/server/static/welcome.html` it does find it, even without a restart, showing that in this case it is assuming that the welcome_url us relative to `{{ galaxy_root }}/server` (but why are the dots ignored?)

```
welcome_url: /../static/welcome.html
```

yields in the welcome panel:
404 Not Found
The resource could not be found.
No route for /static/welcome.html

Other tests yielded other strange results in the messages:
```
welcome_url: static/../tmp/welcome.html
```
yields in the welcome panel:
404 Not Found
The resource could not be found.
No route for /tmp/welcome.html

```
welcome_url: static/static/../tmp/welcome.html <did this by accident, but the 
result was surprising)>
```
yields in the welcome panel:
404 Not Found
The resource could not be found.
No route for /static/tmp/welcome.html

```
welcome_url: /static/../tmp/welcome.html
```

yields in the welcome panel:
404 Not Found
The resource could not be found.
No route for /tmp/welcome.html

**Comment by mvdbeek** [comment]
I think there's a misunderstanding here. This sets the url, not a filesystem path, to whatever Galaxy should display in the center panel. You can remap the url to anywhere you like in in your proxy setup.
Say for instance you set `welcome_url: static/hi.html`. If you want to serve this from somewhere else you would add
```
        location /static/hi.html {
            alias /some/path/on/disk/welcome.html;
        }
```
If you don't have a proxy and you serve Galaxy from root and you enable serving of static content galaxy will serve up content from the static directory.
