### ISSUE TITLE
Bayescan Galaxy Europe

### ISSUE THREAD

**Issue by ribaslej** [galaxyproject/galaxy#9607]
Hello Galaxy Team,

I'm running some online RADseq analysis at Galaxy Europe Server and would like to run BayeScan on my data. Although this function is not directly available, there is a repository with it at https://toolshed.g2.bx.psu.edu/view/iuc/bayescan/72f3a333f155 . Is there any way of installing or uploading it to my online session? If not, do you intend to make it available any time soon?

Best regards,
Luiz Eduardo

**Comment by beatrizserrano** [comment]
Hi Luiz,

bayescan is now included in the list of tools to install (see [PR](https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/290)). You will have it available to use by tomorrow :)

Thanks, and enjoy!
