### ISSUE TITLE
Circos tool UI performance

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#9615]
Re-running Circos jobs is incredibly slow (~30 seconds, locally, client-production, from clicking re-run to the tool being shown) 

I'm responding to reviewers currently, and one asked for lessons learned and limitations. There are a number, but one of the real user experience problems is how slow it is to load the interface. The jobs actually runs more quickly than pressing re-run.

## The Tool

Here is the xml of the version I'm testing with all macros expanded. (What is in IUC currently, but maybe this is easier for people)

[circos.xml](https://github.com/galaxyproject/galaxy/files/4480120/circos.xml.txt)

The parameter set for this tool is quite large, which is unavoidable:

![image](https://user-images.githubusercontent.com/458683/79246038-40b57d80-7e79-11ea-9662-3c2eed4afbb2.png)

So

## Some profile screenshots 
![image](https://user-images.githubusercontent.com/458683/79245368-4ced0b00-7e78-11ea-8468-0004f4316f9b.png)

or in chrome

![image](https://user-images.githubusercontent.com/458683/79245713-c127ae80-7e78-11ea-840b-f2013f9fc5fa.png)

## Profiles

Below I've attached the profiles of clicking the re-run button for a single job. Is there any development time in the near future that will be allocated for such performance issues with large tools? Should we add a spinner in the main panel in the short term?

There are no network requests between build for rerun, and then images from help loading

![image](https://user-images.githubusercontent.com/458683/79319012-12cb4a00-7f08-11ea-9981-129eea4aa2e0.png)

Profiles:

[firefox-circos-rerun-profile.json.txt](https://github.com/galaxyproject/galaxy/files/4480040/firefox-circos-rerun-profile.json.txt)
[chrome rerun profile.json](https://usegalaxy.eu/static/vgcn/chrome-rerun-profile.json.txt)
[chrome rerun profile empty history.json](https://usegalaxy.eu/static/vgcn/chrome-profile-empty-history.json.txt)

## Reproducing

You can mostly reproduce this issue with an older version of the tool than the one I've included above with [this history on EU](https://usegalaxy.eu/u/helena-rasche/h/circos-microbe-tutorial) That takes ~10-15 seconds to load, not as bad.

And [here is a history export](https://usegalaxy.eu/static/vgcn/Galaxy-History-Circos-testing-for-export.tar.gz) from my current history, with the latest "Circos Plot" being the one in question. 

## Solutions?

Short term maybe a spinner in the main area? I know I've hit re-run again when I thought it wasn't doing anything.

**Comment by hexylena** [comment]
From @mvdbeek 

> @hexylena I’m giving up on the rendering issue. this is all still backbone, I suppose we’ll be porting this to vue soon, hoping this issue solves itself at that point
> I can repoduce this locally though with a history import

let me know when things are done in vue and I'll test again and mayb

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/pull/10083, which optimizes rendering of conditionals, brings it down from 46 to 7 seconds locally (with profiling enabled). I guess we can still squeeze out a little better performance by using this technique for repeats and sections.

**Comment by hexylena** [comment]
That's incredible!!!!!!

man. 10. aug. 2020, 16:32 skrev Marius van den Beek <
notifications@github.com>:
