### ISSUE TITLE
Beta workflow submission should show history name when "sent to another history"

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#962]
In the old workflow submission pane, a link was provided if you sent the jobs to another history. This is a regression.

**Comment by guerler** [comment]
Can you specify what you mean with old/beta workflow submission? The workflow submission form we are currently working on is not visible/complete yet.

**Comment by hexylena** [comment]
@guerler sure thing! The old workflow submission looked like this:
![gx-workflow-old](https://cloud.githubusercontent.com/assets/458683/10716994/0ee88cd4-7b18-11e5-8f88-2514c14954ae.png)
Note the blue link to the history your jobs are running in. If you set 
`force_beta_workflow_scheduled_min_steps=1` in your galaxy.ini the new workflow submission page lacks this very useful link. 
![gx-workflow-old2](https://cloud.githubusercontent.com/assets/458683/10717029/74ab1450-7b19-11e5-80fa-92ad31da4ca9.png)

**Comment by hexylena** [comment]
FYI This is still an issue.

**Comment by dannon** [comment]
I think I addressed this in https://github.com/galaxyproject/galaxy/pull/6240, which overhauled the workflow submission text.
