### ISSUE TITLE
tool favorite gets lost with tool update

### ISSUE THREAD

**Issue by foellmelanie** [galaxyproject/galaxy#9623]
Hi, 

I like the tool favorite option a lot :) 

Unfortunately, with every version update of a tool, the tool is no longer marked as favorite tool and needs to be added again.

Maybe the favorites are linked to a certain version of a tool instead of only the tool id? 

Thanks,
Melanie

**Comment by dannon** [comment]
This has been addressed in #9873 and followup in #11360
