### ISSUE TITLE
Tool tests no longer timeout.

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#964]
They used to, but we've now received multiple reports including the framework tests hanging.

**Comment by martenson** [comment]
We got a stuck jenkins test ( https://jenkins.galaxyproject.org/job/docker-framework/627/consoleFull ). The relevant part of the log is here: https://gist.github.com/martenson/974b329ff6a9de486100
I think that after that exception the test run got stuck and was just waiting forever.
