### ISSUE TITLE
Boolean "Simple input used for workflow logic" do not attach in workflows (Galaxy 20.01)

### ISSUE THREAD

**Issue by Tomnl** [galaxyproject/galaxy#9646]
When using the boolean option for "Simple input used for workflow logic" a connection cannot be made.

See below for example using Galaxy tool msPurity.dimsPredictPuritySingle

![image](https://user-images.githubusercontent.com/5541632/80025478-a2f52a80-84d8-11ea-9013-df9c9fc96dc9.png)

**Comment by innovate-invent** [comment]
can you post a link to the tool xml?

**Comment by Tomnl** [comment]
Sure. 

https://github.com/computational-metabolomics/mspurity-galaxy/blob/master/tools/msPurity/dimsPredictPuritySingle.xml#L93

I have tested for other tools though and get the same problem
e.g. XCMS fillpeaks (https://github.com/workflow4metabolomics/tools-metabolomics/tree/master/tools/xcms_fillpeaks) - (https://github.com/workflow4metabolomics/tools-metabolomics/blob/master/tools/xcms_macro/macros_xcms.xml#L93)

Marius on gitter mentioned that there is a problem with the editor for Galaxy @mvdbeek

**Comment by mvdbeek** [comment]
Thanks for the report @Tomnl, this should be fixed by https://github.com/galaxyproject/galaxy/pull/9648
