### ISSUE TITLE
New Reports' homepage takes 5 mins to load on Main

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#966]
We need to make this faster. Any ideas @Airistotal ?

![screenshot 2015-10-21 14 00 35](https://cloud.githubusercontent.com/assets/1814954/10645518/202e6b2c-77fc-11e5-832f-46da8576e8a5.png)

**Comment by OldWorldBoa** [comment]
Hey Martin,

Sorry for replying so late. I've been super busy with school. I don't
really know much about SQL and how to optimize it, but I think that to make
the stats page I loop through every item that's returned by the query. What
you could do is short it and lip through the results until you find one
item outside the time range for the graph, thus avoiding looking at all the
results of the query.

Regards,
Daniel

**Comment by hexylena** [comment]
Some of this has been fixed, and I guess we've been using grafana more heavily in the meantime. If there are still queries now that I've spent 12 months doing nothing but writing SQL, I'm happy to look :P
