### ISSUE TITLE
Hide empty workflow section in toolpanel

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#9660]
There is an always visible toolpanel section named "Workflows" with id of `title_XXinternalXXworkflow` that has nothing in it.

https://github.com/galaxyproject/galaxy/blob/dev/client/galaxy/scripts/components/Panels/ToolBox.vue#L26

I assume this is used for workflow editor? It should not be visible in the normal tool panel.

Present e.g. on Main.

ping @inkuzmin @guerler who touched this recently and could know more

**Comment by jmchilton** [comment]
My first thought was bookmarked workflows - but they are in another div. This does appear to just be used by the workflow editor. Thanks for the catch @martenson

**Comment by inkuzmin** [comment]
Hi @martenson! Indeed, it was ported from https://github.com/galaxyproject/galaxy/blob/90a6e55fac7c7b3ef88b97567ac45be4e070ca5b/client/galaxy/scripts/apps/panels/tool-panel.js#L121-L128
I didn't find whether the `title_XXinternalXXworkflow ` id was referenced from somewhere else, so it was kept as is in case it actually has some role and under the assumption that having this id in place would increase the chances that it won't break.

Your report makes me speculate that may be the id attribute was there to hide the section when it's not needed, but visually I remember it to be present.

**Comment by jmchilton** [comment]
This was done recently by @guerler
