### ISSUE TITLE
Workflow reports - enable embedding of extra files produced by tools

### ISSUE THREAD

**Issue by wm75** [galaxyproject/galaxy#9689]
In a nutshell, what I would like to be able to do is something along the lines of:

`invocation_outputs(primary_dataset.files_path['very-informative-extra-file'])`

Think of a tool like FastQC for example. The html it produces is a report on its own already and embedding that whole thing in an outer workflow report often feels a bit awkward. What I would typically like to do instead is just embed one or two particular images from the tool report into the workflow report. Those images are actually available as separate files referenced by the primary dataset's files_path attribute. If those extra files could be made accessible through syntax similar to the one above, it'd be great!

**Comment by wm75** [comment]
@OlegZharkov If you would like to work on this, I can explain things in more detail offline if you want.

**Comment by jmchilton** [comment]
Sounds like a great idea - @OlegZharkov want to prototype this and then ping me on it? Thanks so much.

**Comment by OlegZharkov** [comment]
@jmchilton 
Well, it will take a while to do. Can you assign me on this issue, please?

**Comment by jmchilton** [comment]
This has been done by @OlegZharkov - thanks for the request and for the implementation. Really nice stuff!
