### ISSUE TITLE
Wrong path migrate directory for tools database

### ISSUE THREAD

**Issue by Takadonet** [galaxyproject/galaxy#9702]
Attempt to upgrade from Galaxy 19.05 => 20.01 and receive the following [stacktrace](https://gist.github.com/Takadonet/0fe0233ef57d99d1dbf09f7823d659a5) when running ansible playbook command :

 `python /Galaxy/scripts/manage_db.py -c /Galaxy/config/galaxy.yml db_version tools`

Looks like between version 19.09 and 20.01 the **tool_shed/galaxy_install/migrate** directory was moved to **galaxy/model/tool_shed_install/migrate**

PR #9699 addresses this issue.

**Comment by jmchilton** [comment]
Fix was merged, thanks @Takadonet !
