### ISSUE TITLE
Tool Search improvements

### ISSUE THREAD

**Issue by juleengraham** [galaxyproject/galaxy#9741]
- [ ] Tool Search doesn't return tool when it should be an exact match e.g. "cat1" returns no results but the Concatenate Datasets tool_id is "cat1"
- [x] Tools not showing up for partial strings e.g. "ilter" doesn't return any filter tools
- [x] Fuzzy tool search for potential typos and misspellings

**Comment by martenson** [comment]
For fuzzy search check https://github.com/galaxyproject/galaxy/pull/3356

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/issues/2272

**Comment by wm75** [comment]
Not sure whether to report 20.05 search issues here, or in the old thread.
Here's an old one that still does not work correctly in 20.05:
https://github.com/galaxyproject/galaxy/issues/2272#issuecomment-573080510

Type any search term ending in a trailing whitespace and the search will return what appears to me like arbitrary results.
Solution to this might be as easy as stripping trailing whitespace from the query before searching?

**Comment by bgruening** [comment]
I think what @wm75 is seeing is that the tool search or the index-build step is not recognizing `hidden="true" ` tools.

EU has toolshed.g2.bx.psu.edu/repos/iuc/snpeff/snpEff/4.3r.1 installed, which is hidden. toolshed.g2.bx.psu.edu/repos/iuc/snpeff/snpEff/4.3+T.galaxy1 is not hidden. The search returns `4.3r.1` which is hidden in the tool panel and will not be shown.

**Comment by wm75** [comment]
> I think what @wm75 is seeing is that the tool search or the index-build step is not recognizing `hidden="true" ` tools.

Yes, that's another observation, but it's independent from the whitespace issue above.

**Comment by mvdbeek** [comment]
Since I've been playing with this today:

> * Tools not showing up for partial strings e.g. "ilter" doesn't return any filter tools
> * [ ]  Fuzzy tool search for potential typos and misspellings

that works when using `tool_enable_ngram_search`, but not without. Maybe we should make this the default ?

**Comment by martenson** [comment]
I think there are parts here that still need addressing.

**Comment by mvdbeek** [comment]
Ah, it shouldn't have closed the whole issue, I just referenced https://github.com/galaxyproject/galaxy/issues/9741#issuecomment-667956458. That said, I'm gonna tick off the last 2 boxes, since that seems to work.
