### ISSUE TITLE
Problems upgrading to 20.01

### ISSUE THREAD

**Issue by bampolsk** [galaxyproject/galaxy#9745]
I'm trying to upgrade from galaxy 17.01 to 20.01. I initially run:

git fetch origin && git checkout release_20.01 && git pull --ff-only origin release_20.01

And, get a message that I need to commit local changes:

error: Your local changes to the following files would be overwritten by checkout:
config/plugins/interactive_environments/jupyter/config/jupyter.xml
config/plugins/interactive_environments/jupyter/templates/jupyter.mako
config/plugins/interactive_environments/rstudio/static/js/rstudio.js
config/plugins/interactive_environments/rstudio/templates/rstudio.mako
config/plugins/tours/core.galaxy_ui.yaml
config/plugins/tours/core.history.yaml
config/plugins/tours/core.scratchbook.yaml
config/plugins/visualizations/charts/config/charts.xml
config/plugins/visualizations/charts/package.json
config/plugins/visualizations/charts/templates/charts.mako
config/plugins/visualizations/csg/templates/csg.mako
config/plugins/visualizations/graphviz/config/graphviz.xml
config/plugins/visualizations/graphviz/static/js/toolPanelFunctions.js
config/plugins/visualizations/graphviz/templates/graphviz.mako
config/plugins/visualizations/scatterplot/templates/scatterplot.mako
config/tool_conf.xml.main
Please, commit your changes or stash them before you can switch branches.
Aborting

So, I backout the update and run git commit.  I get the following:

[root@paros-web galaxy]# git commit
On branch release_17.01
Your branch is up-to-date with 'origin/release_17.01'.
Changes not staged for commit:

<long list of deleted/modified files> and then:
Untracked files:
	ca-cert.pem
	client-cert.pem
	client-key.pem
	config/plugins/visualizations/charts/Gruntfile.js
	config/plugins/visualizations/charts/static/app.css
	config/plugins/visualizations/charts/static/app.js
	config/plugins/visualizations/charts/static/charts/
	config/plugins/visualizations/charts/static/library/
	config/plugins/visualizations/charts/static/models/
	config/plugins/visualizations/charts/static/plugins/
	config/plugins/visualizations/charts/static/views/
	config/plugins/visualizations/graphview/
	paster.log.2017-05-26
	static/cats/
	static/images/avispa.png
	static/images/biociph_biglogo.png
	static/images/penn_fulllogo.png
	static/majiq-cat
	static/majiq_spel/
	static/rbp-pokedex/
	static/rnagroup/
	static/voila/
	tools/majiq_spel/
	tools/prime/
	xxx

no changes added to commit

Then I do git push origin:

[root@paros-web galaxy]# git push origin
Username for 'https://github.com': bampolsk
Password for 'https://bampolsk@github.com':
remote: Permission to galaxyproject/galaxy.git denied to bampolsk.
fatal: unable to access 'https://github.com/galaxyproject/galaxy.git/': The requested URL returned error: 403
[root@paros-web galaxy]#

I know that  when i start git push origin, that my entered password is correct.  Is it possible I don't have commit access?  or?  I must get this done before I can rerun

git fetch origin && git checkout release_20.01 && git pull --ff-only origin release_20.01

I would appreciate any suggestions as soon as possible so I can complete this upgrade.

**Comment by hexylena** [comment]
Generally you cannot skip versions when updating. Apolgoies that this never received a response, in the future I can recommend writing in the [admins channel](https://app.element.io/#/room/#galaxyproject_admins:gitter.im) for help.
