### ISSUE TITLE
[feature-request] Use API keys for all API calls

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#976]
Given how painful `REMOTE_USER` can be to set up and get working with API calls, there's a pretty simple solution to this problem: Use API keys for all API calls.

Then those of us under REMOTE_USER (i.e. many universities) can simply remove authentication from the `/api` route and trust API keys there, like how most other APIs work. Bioblend will then work at the command line, and we won't have to do any crazy routing to just to get requests through to the API.

This is up for discussion, please feel free to say "No that's an awful idea".

**Comment by dannon** [comment]
@erasche You can already remove authentication from the API route -- no session should ever be established that way, and arriving at it _with_ an established browser session will continue to work regardless of REMOTE_USER if a session exists.

If I fix that bug, of course ;)

**Comment by hexylena** [comment]
@dannon removing auth from API (used to) break uploads for us, so we deemed it unusable. I briefly experimented with hardcoding a remote_user username but that failed spectacularly as well.

**Comment by hexylena** [comment]
This was fixed a while ago.
