### ISSUE TITLE
[ dev ] error importing the multiarray numpy extension module

### ISSUE THREAD

**Issue by davelsio** [galaxyproject/galaxy#9763]
#### OS Details (Windows 10 x64 - WSL2)

```sh
uname -a           //=> Linux 4.19.84-microsoft-standard #1 SMP x86_64 GNU/Linux
python --version   //=> Python 3.8.2
```

#### Issue Description

Building the `dev` branch via `sh run.sh`, I've run into what appears to be a runtime error when importing `numpy` multiarray module (relevant snippet below).

> ImportError:
> Importing the multiarray numpy extension module failed
> ...
> Original error was: .../galaxy/.venv/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so: undefined symbol: cblas_sgemm

I found a similar issue in numpy/numpy#10714, which was dismissed as likely a compilation problem.

#### Workaround

Upgrading `numpy` to the latest version ([1.18.4](https://github.com/numpy/numpy/releases/tag/v1.18.4)), either by modifying `requirements.txt` or manually `pip install --upgrade --force-reinstall numpy` solves this issue. Note that forcing a reinstall of `numpy@1.16.6` does _not_ fix this.

**Comment by mvdbeek** [comment]
Sorry for the late response, I suppose that's been fixed a some time ago.
