### ISSUE TITLE
[ dev ] Incompatible markdown@3.1.1 (sphinx-markdown-tables requires 3.0.1)

### ISSUE THREAD

**Issue by davelsio** [galaxyproject/galaxy#9764]
Minor issue, if at all, but I haven't found a related report, so I'm leaving it here for future reference.

When building the `dev` branch with `sh run.sh`, I get the following (non-critical) error:

> ERROR: sphinx-markdown-tables 0.0.12 has requirement markdown==3.0.1, but you'll have markdown 3.1.1 which is incompatible.

The `sphinx-markdown-tables` require is stated in `lib/galaxy/dev-requirements.txt`.

This was fixed in version 0.0.13 ([#23587bc](https://github.com/ryanfox/sphinx-markdown-tables/commit/25b922235a883d77204b705b14a30c9f7a40a24b)). In theory, updating it to the latest version should do the trick.

**Comment by nsoranzo** [comment]
This doesn't create any really issue that I'm aware of.

I think we cannot resolve this until we stop supporting Python2 for good, i.e. compile our `requirements.txt` files for Python>=3.5.

**Comment by davelsan** [comment]
Hi, thanks for the prompt reply.

That's fair enough. Do you think it could be a good idea to leave this open until resolved? It may work as an answer for other people wondering about the error message. Open or closed I'm satisfied with the answer, so I'm okay either way.

**Comment by bgruening** [comment]
I guess we can close this, people will still find it if they are searching for it, left?

Thanks for raising this issue. Please keep your questions coming and join our gitter channels:

https://gitter.im/galaxyproject/Lobby or https://gitter.im/galaxyproject/dev
