### ISSUE TITLE
Share-by-username currently only used in histories, missing from workflow/admin pages

### ISSUE THREAD

**Issue by dtrudg** [galaxyproject/galaxy#977]
Now that we have people using Galaxy I need to share workflows frequently. Because of our LDAP setup I am more likely to know user names than email addresses.

Would be nice to be able to enter usernames, preferably multiple, in the 'Share Workflow with Another User' page.

**Comment by hexylena** [comment]
@dctrud I added support for this a while back for sharing histories. I had not finished implementing it everywhere so it isn't available in the share-history dialog. One sec and I'll link docs.

**Comment by dtrudg** [comment]
Ahh yes - I see that, looks nice there for histories. Hadn't ever had need to share a history, so hadn't noticed.

**Comment by hexylena** [comment]
@dctrud see the config options in https://github.com/galaxyproject/galaxy/commit/60ad9e934b3e4c50389a624a28578aa9fc326f32 which tell galaxy to expose username and email.

@erasche: xref https://github.com/galaxyproject/galaxy/issues/816

**Comment by hexylena** [comment]
@dctrud I'll try and get this patched shortly since I need to handle #816 while I'm at it.

**Comment by dtrudg** [comment]
Cool - thanks. I'd actually turned on the expose options when configuring - just never tried the history sharing to see it.

**Comment by hexylena** [comment]
Sorry for the delay @dctrud, I've finally got a fix out for this issue in #1110. Thanks again for reporting it! :)

**Comment by dtrudg** [comment]
Awesome. Look forward to being able to get that here on next upgrade. Many thanks for your efforts!

**Comment by hexylena** [comment]
Sure thing @dctrud! Let me know if you notice any places where this feature isn't used yet and I'll get that patched.
