### ISSUE TITLE
discover_datasets one extra empty file

### ISSUE THREAD

**Issue by gbbio** [galaxyproject/galaxy#9770]
Somehow I always get one extra empty file when using ```discover_datasets```. Is this a known <s>problem</s> thing?

**Comment by jmchilton** [comment]
I think a lot of people have used this feature and not bumped into that. Can you share the relevant tool XML and an example of what the output directory you're discovering from looks like after the job is complete?

**Comment by gbbio** [comment]
Thanks for your reply.

This is the XML output part:

```
<data name="split" format="zip" label="Samples">
        <discover_datasets pattern="__designation_and_ext__" directory="output" visible="true" />
        <filter>conditional_modes['execution_mode'] == "split"</filter>
</data>
```
In this case I want to get all .zip files from the directory output.

**Comment by nsoranzo** [comment]
The code looks correct, have you also checked the whole XML file with `planemo lint` ?

**Comment by gbbio** [comment]
I just did, and no warnings or errors related to the output. I did not used planemo to create the xml.
The tool also outputs a log, the log file output is written directly to the output path that galaxy generates. I will apply discover_datasets on that log file and see if I get an empty file as well to test if it is not a zip thing.

Could it be because of that when the first zip file is being created it starts with a size of 0kb and slowly grows in size?

**Comment by gbbio** [comment]
This:
```
<data name="split" format="zip" label="Samples">
    <discover_datasets pattern="__designation_and_ext__" directory="output" visible="true" />
    <filter>conditional_modes['execution_mode'] == "split"</filter>
</data>
```` 
Also detects the log.txt file. Thought is should only detect .zip files.

**Comment by nsoranzo** [comment]
Yes, that's expected, see https://planemo.readthedocs.io/en/latest/writing_advanced.html#individual-datasets where logtest is what is called the "parent" dataset.

I think for your scenario you may want the log file to be the parent, so something like:

```xml
<data name="log" format="txt" label="Log" from_workdir="output/log.txt">
    <discover_datasets pattern="(?P&lt;designation&gt;.+)\.zip" format="zip" directory="output" visible="true" />
    <filter>conditional_modes['execution_mode'] == "split"</filter>
</data>
```

**Comment by gbbio** [comment]
Oh! Thanks! Did noticed the parent part. (which makes sense)
Is there a way to choose a different label for the zip files? If not I close this issue and maybe can make a paper-cut for the next time.
