### ISSUE TITLE
shed_tool_conf.xml not automatically created in 20.05

### ISSUE THREAD

**Issue by AndreasSko** [galaxyproject/galaxy#9777]
When installing new tools on a clean Galaxy setup, the `shed_tool_conf.xml` file is not created anymore. Rather the error occurs:

> galaxy.util.tool_shed.xml_util ERROR 2020-05-16 14:32:31,473 [p:229,w:1,m:0] [uWSGIWorker1Core2] Exception attempting to parse /galaxy/config/shed_tool_conf.xml: Error reading file '/galaxy/config/shed_tool_conf.xml': failed to load external entity "/galaxy/config/shed_tool_conf.xml"
> Traceback (most recent call last):
>   File "lib/galaxy/util/tool_shed/xml_util.py", line 75, in parse_xml
>     tree = galaxy_parse_xml(file_name, remove_comments=False, strip_whitespace=False)
>   File "lib/galaxy/util/__init__.py", line 237, in parse_xml
>     tree = etree.parse(fname, parser=parser)
>   File "src/lxml/etree.pyx", line 3519, in lxml.etree.parse
>   File "src/lxml/parser.pxi", line 1839, in lxml.etree._parseDocument
>   File "src/lxml/parser.pxi", line 1865, in lxml.etree._parseDocumentFromURL
>   File "src/lxml/parser.pxi", line 1769, in lxml.etree._parseDocFromFile
>   File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
>   File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
>   File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
>   File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
> OSError: Error reading file '/galaxy/config/shed_tool_conf.xml': failed to load external entity "/galaxy/config/shed_tool_conf.xml"
> galaxy.tool_shed.galaxy_install.tools.tool_panel_manager ERROR 2020-05-16 14:32:31,475 [p:229,w:1,m:0] [uWSGIWorker1Core2] Exception attempting to parse /galaxy/config/shed_tool_conf.xml: Error reading file '/galaxy/config/shed_tool_conf.xml': failed to load external entity "/galaxy/config/shed_tool_conf.xml"

In earlier versions, Galaxy would create this file on its own if it didn't exists yet. I think this started with https://github.com/galaxyproject/galaxy/pull/9759

**Comment by ic4f** [comment]
Yep, confirmed: happens on 20.05, dev; does not happen on 20.01. Working on it. @AndreasSko thanks for catching this!

**Comment by ic4f** [comment]
Fixed in #9788 Thanks @mvdbeek!
@AndreasSko : please feel free to reopen if issue appears not resolved. Thanks again!
