### ISSUE TITLE
Error occurred setting the metadata

### ISSUE THREAD

**Issue by priscilla607** [galaxyproject/galaxy#9786]
I am working with trimmomatic and fastQC and keep getting "An error occurred setting the metadata for this dataset. Set it manually or retry auto-detection" on all my outputs which I cannot use for any downstream analysis. Using the link in the orange box and trying to autodetect the data type does not resolve the issue.
 The tools were not giving me this warning when I used them yesterday on the same input files so it seems to be a new issue.

Thanks

**Comment by mvdbeek** [comment]
Hello @priscilla607, you may want to post this at https://help.galaxyproject.org/, and please include the URL of the Galaxy server you are working on.
