### ISSUE TITLE
sh run.sh fails with yarn upgrade

### ISSUE THREAD

**Issue by herbercr** [galaxyproject/galaxy#9792]
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`           
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`

I get these two errors before my installation stalls.
Im using ubuntu on windows subsystem and I tried updating conda, ubuntu, and packages as well as  installing yarn on windows and linux but it still stalls in the same place.

**Comment by dannon** [comment]
@herbercr Those are just warnings, and not related to whatever is causing run.sh to fail.  Are you able to post more of the log here?

**Comment by herbercr** [comment]
The Galaxy client has not yet been built and will be built now.                                                     
yarn install v1.22.4                                                                                               
[1/4] Resolving packages...                                                                                         
success Already up-to-date.                                                                                         
Done in 28.61s.                                                                                                    
yarn run v1.22.4                                                                                                   
 $ NODE_ENV=production gulp && yarn run webpack-production-maps && yarn run save-build-hash                         
 [18:32:40] Using gulpfile /mnt/c/galaxy/client/gulpfile.js                                                          [18:32:41] Starting 'default'...                                                                                   
 [18:32:41] Starting 'fonts'...                                                                                      
[18:32:41] Starting 'stageLibs'...                                                                                 
 [18:32:41] Starting 'cleanPlugins'...                                                                               
[18:32:41] Finished 'stageLibs' after 47 ms                                                                        
 [18:32:42] Finished 'cleanPlugins' after 628 ms                                                                    
 [18:32:42] Starting 'buildPlugins'...                                                                              
 [18:32:42] Finished 'buildPlugins' after 3.6 ms                                                                     
[18:32:42] Starting 'stagePlugins'...                                                                              
 Installing Dependencies for /mnt/c/galaxy/config/plugins/visualizations/annotate_image/                             [1/4] Resolving packages...                                                                                         
success Already up-to-date.                                                                                         
Building  /mnt/c/galaxy/config/plugins/visualizations/annotate_image/                                               $ parcel build src/script.js -d static --no-source-maps                                                            
 ✨  Built in 4.80s.                                                                                                                                                                                                                     static/script.js    356.11 KB    165ms                                                                             
 Installing Dependencies for /mnt/c/galaxy/config/plugins/visualizations/hyphyvision/                                [1/4] Resolving packages...                                                                                         
success Already up-to-date.                                                                                         
Building  /mnt/c/galaxy/config/plugins/visualizations/hyphyvision/                                                  
$ webpack --mode production                                                                                        
 Hash: dc0a09843ff2fff68ce6                                                                                          
Version: webpack 4.43.0                                                                                             
Time: 9124ms                                                                                                        
Built at: 05/19/2020 6:33:29 PM                                                                                        
 Asset      Size  Chunks                    Chunk Names                                                           
main.css   272 KiB       0  [emitted]  [big]  main                                                                
 script.js  2.65 MiB       0  [emitted]  [big]  main                                                                 
Entrypoint main [big] = main.css script.js                                                                          
 [5] (webpack)/buildin/global.js 472 bytes {0} [built]                                                              
[10] ./node_modules/underscore/modules/index-all.js + 1 modules 326 bytes {0} [built]                                    |    2 modules                                                                                                
 [14] ./src/index.js 215 bytes {0} [built]                                                                           
[42] (webpack)/buildin/amd-define.js 85 bytes {0} [built]                                                           
[43] (webpack)/buildin/amd-options.js 80 bytes {0} [built]                                                          
[65] ./node_modules/react-router-dom/es/index.js + 29 modules 76.8 KiB {0} [built]                                       |    30 modules                                                                                                   
 + 64 hidden modules                                                                                                                                                                                                                 WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).                    This can impact web performance.                                                                                   
 Assets:                                                                                                              
 main.css (272 KiB)                                                                                                  
script.js (2.65 MiB)                                                                                                                                                                                                                  WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.                                                                             Entrypoints:                                                                                                         
 main (2.92 MiB)                                                                                                         
main.css                                                                                                            
script.js                                                                                                                                                                                                                                                                                                                                             WARNING in webpack performance recommendations:                                                                     You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.                                                                                                                 
For more info visit https://webpack.js.org/guides/code-splitting/                                                   Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/hyphy-vision/dist/hyphyvision.css:       Entrypoint mini-css-extract-plugin = *                                                                                 2 modules                                                                                                    
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js!node_modules/phylotree/build/phylotree.css:           
Entrypoint mini-css-extract-plugin = *                                                                                
 2 modules                                                                                                    
Installing Dependencies for /mnt/c/galaxy/config/plugins/visualizations/openlayers/                                 [1/4] Resolving packages...                                                                                         
success Already up-to-date.                                                                                         
Building  /mnt/c/galaxy/config/plugins/visualizations/openlayers/                                                   
$ parcel build src/script.js -d static --no-source-maps                                                             
✨  Built in 7.23s.                                                                                                                                                                                                                     static/script.js    ⚠️  1.26 MB    3.45s                                                                            
[18:33:55] Finished 'fonts' after 1.22 min                                                                          
[18:34:11] Finished 'stagePlugins' after 1.48 min                                                                  
 [18:34:11] Finished 'default' after 1.5 min                                                                         
$ GXY_BUILD_SOURCEMAPS=1 webpack -p                                                                                 Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`            
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`

**Comment by herbercr** [comment]
It always get through to the last part then stalls.
Could it be the webpack performance warning?

**Comment by dannon** [comment]
Unlikely.  Do you know how much memory is available to the WSL Virtual Machine?

**Comment by herbercr** [comment]
1.02 GB of available virtual memory.

I tried it and got an error
cd client && yarn install --network-timeout 300000 --check-files                              
Usage: yarn [options]                                                                                                                                                                         yarn: error: no such option: --network-timeout                                                 
make: *** [Makefile:146: node-deps] Error 2

**Comment by herbercr** [comment]
available physical memory is 937 MB

**Comment by dannon** [comment]
Ahh, this makes sense.  I've only seen similar errors on low memory machines.  Can you try the following?

```
source .venv/bin/activate
cd client
NODE_OPTIONS=--max-old-space-size=1024 yarn build
```

If this still fails, I don't have a good solution other than increasing the available memory for your VM.

**Comment by herbercr** [comment]
Wow it worked! Ill definitely get more memory though.
Thank you!

**Comment by dannon** [comment]
Fantastic!  It's good to know this might be a solution for lower memory machines.  Good luck, and thanks for reporting this!
