### ISSUE TITLE
Offloading collection archive creation

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#9794]
We create the archive now in Galaxy here https://github.com/mvdbeek/galaxy/blob/dev/lib/galaxy/webapps/galaxy/api/history_contents.py#L318.
This blocks the uwsgi listen queue during the entire time the file is being served.

We could use [mod_zip](https://github.com/evanmiller/mod_zip) to push archive creation to nginx, and/or have a tool that creates archives and then serves the link to the archive like the history export tool does (maybe even serving the files out of a FTP server).

**Comment by nsoranzo** [comment]
See https://stackoverflow.com/questions/10405210/create-and-stream-a-large-archive-without-storing-it-in-memory-or-on-disk and https://github.com/aykevl/python-zipseeker for Python solutions that allow to stream an archive on-the-fly.

**Comment by hexylena** [comment]
@nsoranzo Isn't that what we want to get away from? From python doing the zip creation? That's part of what's causing the eu zerglings to be busy, doing archive creation that could be offloaded to nginx or jobs.

**Comment by nsoranzo** [comment]
There's also a (Py3-only) async version of the Python zip stream idea, if that would help. I am just concerned about an nginx-only solution, and as Marius mentioned on Gitter using a Galaxy job to create the archive is not great for usability.

**Comment by mvdbeek** [comment]
I don't think this is a problem for small to medium-sized instances, so I do think that we can require nginx (and rabbitmq for other purposes) if you want to serve a large number of users.

**Comment by mvdbeek** [comment]
We've gone with nginx mod-zip for production loads now, it's documented in https://docs.galaxyproject.org/en/master/admin/nginx.html#creating-archives-with-mod-zip. Note that this would be easy to replace with other, similar approaches. E.g the list of files we return when `upstread_mod_zip` is enabled could also be assembled into zip files on the client side with something like https://github.com/Touffy/client-zip
