### ISSUE TITLE
Update builds.txt.sample to match the most complete, current version in use on http://usegalaxy.org

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy#981]
Or, consider using the version added in the latest Cloudman build.

Other external display site config files (ensembl, igv) could also benefit from an update.

See this link for the exact files (ignoring all_fasta)
https://github.com/galaxyproject/galaxy/search?utf8=%E2%9C%93&q=sacCer2

**Comment by hexylena** [comment]
It's been updated since this issue, sacCer2 now included. But maybe we want to reopen for some generic method of updating? Is this a CVMFS problem? I've never used the "build sites"

**Comment by jennaj** [comment]
The data is outdated again on main. Is a stand-alone tool that pulls in genomes for database lists and creates .len files for them. Not ideal and not automated in any way I know of. I've never run it myself (@blankenberg did in the long long ago).

And yes, could probably be pushed to a CVMFS function and pulled down.  Linking over to IDC so we can think about it there.
