### ISSUE TITLE
slow workflow scheduling (with paired collection outputs?)

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#9818]
In the admin channel, a few discussed a potential bug during running the COVID-19 workflows. It seems that single step can take up to minutes to be scheduled by the workflow-scheduler.

Some comments from gitter:

----------------

* I upped the number of mules to help this.. But for a collection with 1200 pairs, it was still only scheduling one job ~20sec.
* I've found that it also depends on the tool in question. Some parts of the workflow go quickly and others slower.

I think I have a hunch in what it could be.
I can run the COVID-19 workflows on normal list-collections super fast, even on big collections.
This aligns with my observations that our cheminformatics workflows also run 1000+ items in minutes.

However, the COVID-19 PE-collection workflows is a pain. So I played a little bit around with it and it turns out that removing
the fastp tools fixes the problem. The PE-collection now goes directly into the mapping tool.
For me, this indicates a limitation or problem with https://github.com/galaxyproject/tools-iuc/blob/master/tools/fastp/fastp.xml#L328
At least it seems to be related to paried outputs and not inputs.

If I replace the fastp step (which creates a PE-collection) with cutadapt (which just creates 2-list-collections) the workflows still run and are fast.

----------------------

 ping @wm75 @Slugger70 @jmchilton @Takadonet @mvdbeek

**Comment by wm75** [comment]
Yes, this could very well be related to list:paired collections.
Your cutadapt finding, however, is the direct opposite of what I found when testing trimmomatic (which also generates only simple list collections). Trimmomatic on a large list:paired collection as input was **not** faster than fastp.

**Comment by wm75** [comment]
Oh wait: forget about my previous comment. Trimmomatic does in fact generate list:paired collections!
So that could really be it.

**Comment by wm75** [comment]
and Trimmomatic on list:paired data is slow even outside workflows, but fast on simple lists.

**Comment by wm75** [comment]
same thing for fastp. The slowness with list:paired output is *not* WF-related

**Comment by jmchilton** [comment]
I think Marius has done a lot of amazing things in this regard. Is this still a problem spot?

**Comment by bgruening** [comment]
It was not a problem recently. I will close and keep an eye on it. Thanks all!
