### ISSUE TITLE
slow web-routes resulting in an unresponsive interface

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#9819]
On EU we have a lot of pressure on our uwsgi web-handlers. This results in a full-uwsgi queue and finally in an unresponsible interface.

I will try to collect slow web-routes that seem to block uwsgi requests for multiple seconds or even minutes. One that seems to be used a lot and is in the range of 4s to 10s per request is `api.uploads.create`.

![grafik](https://user-images.githubusercontent.com/469983/83001196-b16cbf80-a00b-11ea-83f5-60e51f70ad8e.png)

**Comment by bgruening** [comment]
Another even more clear graph about `api.uploads.create`:

![grafik](https://user-images.githubusercontent.com/469983/83186175-6ac2b680-a12c-11ea-8e6a-b057318c126b.png)

**Comment by gmauro** [comment]
and I think we are still here, from last 24 hours:
![Screenshot from 2021-09-30 15-52-15](https://user-images.githubusercontent.com/4559911/135469491-f70ab7dc-07e2-4818-9d10-ef69fe1cf3d7.png)

During each `api.uploads.create` peaks, handlers stopped sending new jobs to the computing cluster.

**Comment by mvdbeek** [comment]
I think you'll want to disable the chunked uploader (set `chunk_upload_size` to 0) and use the old nginx upload mechanism.

**Comment by mvdbeek** [comment]
> During each `api.uploads.create` peaks, handlers stopped sending new jobs to the computing cluster.

that said this I cannot explain, as the upload blocks the web handler, but new jobs should have been created and dispatched through already queued jobs and workflows via the job and workflow handlers.

**Comment by gmauro** [comment]
we are using Nginx for uploading, `chunk_upload_size` is not unset
https://github.com/usegalaxy-eu/infrastructure-playbook/blob/03a5f68dc76adb63de23de8a6feee22361ce3861/templates/nginx/galaxy-main.j2#L87

**Comment by mvdbeek** [comment]
We can also modernize this endpoint and make it async ... that's not as good as https://github.com/pgaertig/nginx-big-upload but it would be a start. I think that might actually help a lot with slow user uploads and should be pretty easy because this endpoint doesn't need to interact with the database.

**Comment by mvdbeek** [comment]
I think this is fixed with https://github.com/galaxyproject/galaxy/pull/12656, I'll leave it open until it's deployed on the usegalaxy.* instances.
