### ISSUE TITLE
make /api/tools return tool's exact revision

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#982]
The API currently returns only version of the tool which is not enough to uniquely pinpoint a tool in Tool Shed

xref: https://biostar.usegalaxy.org/p/14672/

**Comment by scholtalbers** [comment]
FYI the workflow export/api is also lacking the tool revision

**Comment by mvdbeek** [comment]
:+1:

**Comment by martenson** [comment]
fixed by PR linked above
