### ISSUE TITLE
Missing curly braces in tool env activation

### ISSUE THREAD

**Issue by innovate-invent** [galaxyproject/galaxy#9823]
https://github.com/galaxyproject/galaxy/blob/a30fe9863a54011c70545728d3fd0c0826e48de7/lib/galaxy/tool_util/deps/resolvers/conda.py#L45-L46

It appears that `[ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '{environment_path}')" ] || MAX_TRIES=3` should be `[ "$(basename "$CONDA_DEFAULT_ENV")" = "$(basename '{environment_path}')" ] || { MAX_TRIES=3 .... }` otherwise the while condition fails to evaluate when the environment is already active

**Comment by nsoranzo** [comment]
I think that everything from `MAX_TRIES=3` to `done` should be inside the curly braces. Ping @mvdbeek

**Comment by innovate-invent** [comment]
Yes, sorry, that is what I meant by the ellipses.

**Comment by innovate-invent** [comment]
Sure, incoming..
