### ISSUE TITLE
Top menu disappears at width=991px

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#9844]
The menu's `ul` element becomes vertical. Happens due to `flex-direction: column` for `.navbar-nav`, I think.
Maybe display a horizontal scrollbar in the middle pane instead?

![1](https://user-images.githubusercontent.com/6132258/83655630-a2968780-a58c-11ea-9d1f-021870628666.png)
![2](https://user-images.githubusercontent.com/6132258/83655648-a6c2a500-a58c-11ea-846d-2c7ff72cf9f4.png)

**Comment by martenson** [comment]
Can reproduce. This renders Galaxy interface completely useless while working with multiple browser windows or on mobile.

**Comment by dannon** [comment]
Fixed in #10641
