### ISSUE TITLE
Composite upload function broken

### ISSUE THREAD

**Issue by foellmelanie** [galaxyproject/galaxy#9877]
Hi, 

a composite file upload is not possible anymore on usegalaxy.org. Composite file types are not available in the select field at the bottom. 

I hope this can be fixed soon. 

Thanks,
Melanie

**Comment by foellmelanie** [comment]
![image](https://user-images.githubusercontent.com/16114269/84645253-956c8780-af00-11ea-8fbd-00dd9a0f2182.png)

**Comment by mvdbeek** [comment]
Thanks @foellmelanie, we've fixed this on the dev branch already (https://test.galaxyproject.org/ already has the fix) and we'll update usegalaxy.org once https://github.com/galaxyproject/galaxy/pull/9878 is merged. Can you confirm this works as expected on https://test.galaxyproject.org/ ?

**Comment by foellmelanie** [comment]
Thank you very much @mvdbeek it works as expected :)

**Comment by mvdbeek** [comment]
I'm gonna keep this open until it's merged and deployed :).
