### ISSUE TITLE
Toolshed is unhappy with HTML content, planemo errors on upload.

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#992]
```
hxr@leda:~/work/tools-iuc/tools/macs2$ planemo shed_update -t testtoolshed --force_repository_creation .
cd '/home/hxr/work/tools-iuc/tools/macs2' && git rev-parse HEAD
cd '/home/hxr/work/tools-iuc/tools/macs2' && git diff --quiet
Could not update macs2
Unexpected response from galaxy: 400: {"content_alert": "The file \"/srv/toolshed/test/var/data/repos/000/repo_749/dir2html.py\" contains HTML content.\n", "e
rr_msg": "No changes to repository."}
Repository metadata updated.
Failed to update a repository.
hxr@leda:~/work/tools-iuc/tools$ planemo shed_update -t testtoolshed --force_repository_creation gatk2/
cd '/home/hxr/work/tools-iuc/tools/gatk2' && git rev-parse HEAD
cd '/home/hxr/work/tools-iuc/tools/gatk2' && git diff --quiet
Could not update gatk2
Unexpected response from galaxy: 400: {"content_alert": "The file \"/srv/toolshed/test/var/data/repos/000/repo_674/gatk2_wrapper.py\" contains HTML content.\n
The file \"/srv/toolshed/test/var/data/repos/000/repo_674/test-data/gatk/gatk_analyze_covariates/gatk_analyze_covariates_out_1.html\" contains HTML content.\n
", "err_msg": "No changes to repository."}
Repository metadata updated.
Failed to update a repository.
```

@martenson I'll help however I can. We're TWO tool repositories away from 100% parity between TTS and github. I want to resolve this :)

**Comment by hexylena** [comment]
And again

```
Unexpected response from galaxy: 500: {"content_alert": "The file \"/srv/toolshed/test/var/data/repos/002/repo_2815/json2iframe.py\" contains HTML content.\n",
```

it's _supposed_ to have HTML content. That's the purpose of that tool!
I'll base64 encode it to make the TS happy but that seems ridiculous.

**Comment by remimarenco** [comment]
I +1 on this. I was really suprised, and it is quite blocking for (my main) tool development.

**Comment by martenson** [comment]
hear, hear

**Comment by martenson** [comment]
ping @dannon

**Comment by dannon** [comment]
The HTML content issue was a red herring, and shouldn't be presented to the user as an error here.  @remimarenco's issue that presented this same way was a datatypes_conf.xml in the tool tarball that referenced a datatype that didn't exist.

I'll follow up here and close this with more details, but the toolshed _does_ allow html content uploads.  The content_alert is actually composed to allow notification of toolshed admins when _potentially_ inappropriate content is uploaded, and it does not actually block the upload.

**Comment by remimarenco** [comment]
Yes, exactly as @dannon said. The message error does not match the true issue. I believe this is a need to fix the exception raised in ToolShed?
