### ISSUE TITLE
Galaxy ignores HTTPS through Apache proxy

### ISSUE THREAD

**Issue by alxcost** [galaxyproject/galaxy#9924]
Hi folks,

I have a galaxy instance running through an Apache reverse proxy with HTTPS.

Most things seem to be running fine, but a few resources keep being accessed through HTTP, which is breaking things.

The main thing that seems to be breaking are datasource tools and static resources (such as the welcome page). I've already followed the guide for [Proxying with Apache](https://docs.galaxyproject.org/en/latest/admin/apache.html), so hopefully I'm not missing something?

Datasource tools seem to be the most affected by this. When I click to open a new tab for a datasource on my browser, this is what the URL looks like:
```
https://<datasource url>/study/1?GALAXY_URL=http://<galaxy url>/galaxy/tool_runner&tool_id=<sometool>
```

You'll notice the `GALAXY_URL` completely ignores the HTTPS and just puts HTTP, which redirects the browser to an invalid page, since there is no galaxy instance running on HTTP.
It works fine if I edit the URL manually to HTTPS, but this is some strange behavior. 

Do you know what could be causing this?

Best regards,
Alex

**Comment by alxcost** [comment]
Hello again,

Adding `ProxyPreserveHost On` to the reverse proxy configuration fixes this issue.
Here is my final configuration for future reference:

```
<Location /galaxy>
    ProxyPass http://galaxy
    ProxyPassReverse http://galaxy

    ProxyPreserveHost On

    # serve framework static content
    RewriteEngine On
    RewriteRule ^/galaxy/$ /galaxy [R,L]
    RewriteRule ^/galaxy/static/(.*) ${galaxy_root}/static/$1 [L]
    RewriteRule ^/galaxy/favicon.ico ${galaxy_root}/static/favicon.ico [L]
    RewriteRule ^/galaxy/robots.txt ${galaxy_root}/static/robots.txt [L]
</Location>
```

Best regards,
Alex

**Comment by nsoranzo** [comment]
@alxcost Thanks for following up on this issue! Your configuration seems a bit different with respect to the one in https://docs.galaxyproject.org/en/master/admin/apache.html , so I'm not sure if `ProxyPreserveHost On` would apply there too, but I am definitely not an Apache expert.

@natefoo Suggestions?
