### ISSUE TITLE
Export using FilesSource plugins

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#9948]
With any luck https://github.com/galaxyproject/galaxy/pull/9888 will be merged and we will have a consistent abstraction (backend plugins, consistent use across upload APIs, consistent use with remote files API, and frontend GUI) to describe sources of files to import into Galaxy from. Adding another method to the interface to write files out and using the folder selection GUI included in that commit would provide a powerful abstraction to export files to in a more robust way than sort of ad hoc interfaces and DB tricks we do now.

We could allow users to write their history exports, collection exports, direct datasets, markdown PDF exports to all the interfaces we can target with that plugin infrastructure - including NFS directories, their library and FTP directories, WebDAV, Dropbox, etc.. (Terra and buckets soon hopefully). This would be a much more robust way to get data out of Galaxy and build archives. It would also give admins hooks to tie into existing infrastructure (SCP, aspera, etc..).

**Comment by jmchilton** [comment]
backend https://github.com/galaxyproject/galaxy/pull/10993
frontend https://github.com/galaxyproject/galaxy/pull/11054

**Comment by hexylena** [comment]
I think @Slugger70 has the same issue, wanting to send individual/a few datasets through to a file sources backend. Currently they're using a tool for this.

**Comment by bgruening** [comment]
related I think: https://github.com/galaxyproject/galaxy/pull/11613
