### ISSUE TITLE
testtoolshed.g2.bx.psu.edu down

### ISSUE THREAD

**Issue by CarlosHorro** [galaxyproject/galaxy#9961]
Hi,

I've found that the Galaxy Test Toolshed is down for some days, and this happened one week ago too. Will this toolshed be removed? or are they just temporary problems? 

Greetings,
Carlos

**Comment by bgruening** [comment]
Temporary problems, sorry.

**Comment by hexylena** [comment]
Will not be removed. Please follow updates on https://status.galaxyproject.org/
