### ISSUE TITLE
[Feature request] "Upgrading Galaxy" section

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#9965]
We should probably have an "upgrading" section covering anything people need to know regarding the upgrade? Should we patch the 20.05 notes, or just for going forward? 

This is coming up because of https://github.com/galaxyproject/galaxy/pull/9306, which you just have to know about, and isn't necessarily apparent to the more casual admin.

I think any changes to the apache/nginx/uwsgi config probably should be noted in the main release notes. What else should go in? Should we include "new / deprecated galaxy.yml" options?

**Comment by nsoranzo** [comment]
Supported Python version!

**Comment by mvdbeek** [comment]
I'm not sure why we still keep this open, we've been producing diffs for a while, and larger changes include upgrade instructions.
