### ISSUE TITLE
Visualization plugin issue with Galaxy served by prefix "/galaxy"

### ISSUE THREAD

**Issue by mtangaro** [galaxyproject/galaxy#9970]
Dear experts,
I have an issue with the visualization plugins when serving Galaxy under a URL Prefix with NGINX:
The plugin is not correctly loaded and results not usable:

<img width="1440" alt="Schermata 2020-07-08 alle 17 47 11" src="https://user-images.githubusercontent.com/16704987/86943658-00e3f680-c147-11ea-80f9-467d662d5593.png">

I have the same problem on Galaxy 19.05 and 20.05.
Galaxy 19.05 has been tested on centos (following the documentation for the installation).
Galaxy 20.05 has been installed using the training material on Ubuntu.
Here my galaxy.yml and nginx.conf configuration:
https://gist.github.com/mtangaro/1daa214521002aa44e7b8e02d0b55e05

I tried to modify the relevant section, but it simply seems to be ignored.

```
# serve visualization and interactive environment plugin static content
location ~ ^/plugins/(?<plug_type>.+?)/(?<vis_name>.+?)/static/(?<static_file>.*?)$ {
    alias $galaxy_root/config/plugins/$plug_type/$vis_name/static/$static_file;
    expires 24;
}
```

And therefore Nginx is giving me this error:

```
2020/07/08 15:46:48 [error] 18398#0: *67 access forbidden by rule, client: 93.44.89.88, server: _, request: "GET /favicon.ico HTTP/1.1", host: "90.147.75.201", referrer: "http://90.147.75.201/galaxy/visualizations"
2020/07/08 15:46:50 [error] 18398#0: *41 open() "/home/galaxy/galaxy/static/scripts/libs/jquery/jquery.js" failed (2: No such file or directory), client: 93.44.89.88, server: _, request: "GET /galaxy/static/scripts/libs/jquery/jquery.js?v=1594222730 HTTP/1.1", host: "90.147.75.201", referrer: "http://90.147.75.201/galaxy/plugins/visualizations/nvd3_horizontal/show?dataset_id=a55b9f7ee2e3b64c"
2020/07/08 15:46:50 [error] 18398#0: *68 open() "/home/galaxy/galaxy/static/scripts/libs/jquery/jquery-ui.js" failed (2: No such file or directory), client: 93.44.89.88, server: _, request: "GET /galaxy/static/scripts/libs/jquery/jquery-ui.js?v=1594222730 HTTP/1.1", host: "90.147.75.201", referrer: "http://90.147.75.201/galaxy/plugins/visualizations/nvd3_horizontal/show?dataset_id=a55b9f7ee2e3b64c"
2020/07/08 15:46:50 [error] 18398#0: *69 open() "/home/galaxy/galaxy/static/scripts/libs/jquery/jquery.migrate.js" failed (2: No such file or directory), client: 93.44.89.88, server: _, request: "GET /galaxy/static/scripts/libs/jquery/jquery.migrate.js?v=1594222730 HTTP/1.1", host: "90.147.75.201", referrer: "http://90.147.75.201/galaxy/plugins/visualizations/nvd3_horizontal/show?dataset_id=a55b9f7ee2e3b64c"
2020/07/08 15:46:51 [error] 18398#0: *70 open() "/home/galaxy/galaxy/static/scripts/libs/jquery/jquery.js" failed (2: No such file or directory), client: 93.44.89.88, server: _, request: "GET /galaxy/static/scripts/libs/jquery/jquery.js?v=1594222730 HTTP/1.1", host: "90.147.75.201", referrer: "http://90.147.75.201/galaxy/plugins/visualizations/nvd3_horizontal/show?dataset_id=a55b9f7ee2e3b64c"
2020/07/08 15:46:51 [error] 18398#0: *70 open() "/home/galaxy/galaxy/static/scripts/libs/jquery/jquery.migrate.js" failed (2: No such file or directory), client: 93.44.89.88, server: _, request: "GET /galaxy/static/scripts/libs/jquery/jquery.migrate.js?v=1594222730 HTTP/1.1", host: "90.147.75.201", referrer: "http://90.147.75.201/galaxy/plugins/visualizations/nvd3_horizontal/show?dataset_id=a55b9f7ee2e3b64c"
2020/07/08 15:46:51 [error] 18398#0: *70 access forbidden by rule, client: 93.44.89.88, server: _, request: "GET /api/datasets/a55b9f7ee2e3b64c HTTP/1.1", host: "90.147.75.201", referrer: "http://90.147.75.201/galaxy/plugins/visualizations/nvd3_horizontal/show?dataset_id=a55b9f7ee2e3b64c"
2020/07/08 15:46:51 [error] 18398#0: *71 access forbidden by rule, client: 93.44.89.88, server: _, request: "GET /static/plugins/visualizations/nvd3/nvd3_horizontal/static/logo.png HTTP/1.1", host: "90.147.75.201", referrer: "http://90.147.75.201/galaxy/plugins/visualizations/nvd3_horizontal/show?dataset_id=a55b9f7ee2e3b64c"
```

The fact is that if I remove the prefix configuration, of course, everything is working fine, without any further action.
Probably this is my configuration fault and I hope you can help me to fix this.

Kind regards,
Marco

**Comment by jmchilton** [comment]
This is challenging. One of the lines make it look like this line https://github.com/galaxyproject/galaxy/blob/dev/client/src/mvc/visualization/chart/utilities/datasets.js#L77 is a/the problem - it isn't taking account of Galaxy's prefix. This usually happens because a developer forget to prepend the URL with galaxy's root. But ``getAppRoot()`` is being used in there and has been for two years at least. So I'm confused.

I guess I should have known that wasn't the problem though because even before that line in the error log there were some issues. Those static assets have moved a few times, I'm not sure what the expected current location or configuration is.

**Comment by dannon** [comment]
The problem here is almost certainly what I fixed in https://github.com/galaxyproject/galaxy/pull/10391.  Please test with that and reopen if it's still a problem.
