### ISSUE TITLE
OIDC case sensitivy

### ISSUE THREAD

**Issue by selten** [galaxyproject/galaxy#9981]
When users log in initially through OIDC, if their accounts on galaxy have email `firstname.lastname@test.com` and the OIDC account is `Firstname.Lastname@test.com`, clicking on the OIDC button will actually create a new account. I believe this should be made case-insensitive so the accounts are linked successfully without having to go through the 'user' menu.

**Comment by nsoranzo** [comment]
I fixed the same issue for LDAP in https://github.com/galaxyproject/galaxy/pull/8631 .

**Comment by selten** [comment]
Should be solved with #11251
